### ISSUE TITLE
TextPainter miscalculates size

### ISSUE THREAD

**Issue by kalaganov** [flutter/flutter#142302]
Copy the code below and run it on emulator or even dartpad.

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    const text = 'Prioritization';

    const textStyle = TextStyle(fontSize: 32);

    final textPainter = TextPainter(
      text: const TextSpan(text: text, style: textStyle),
      textDirection: TextDirection.ltr,
      maxLines: 1,
      textWidthBasis: TextWidthBasis.longestLine,
    );

    textPainter.layout();

    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text('text painter width: ${textPainter.width}'),
          Container(
            width: textPainter.width,
            color: Colors.grey,
            child: const Text(text, style: textStyle),
          ),
        ],
      ),
    );
  }
}
```
and result
<img width="279" alt="Screenshot 2024-01-26 at 16 18 41" src="https://github.com/flutter/flutter/assets/13645580/17632b01-4c0d-4a6d-b954-7e0669f3a381">

but if you wrap e.g. `Column` with `DefaultTextStyle` it will "fix" an issue
```
      body: DefaultTextStyle(
        style: const TextStyle(),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('text painter width: ${textPainter.width}'),
            Container(
              width: textPainter.width,
              color: Colors.grey,
              child: const Text(text, style: textStyle),
            ),
          ],
        ),
      ),
```
<img width="302" alt="Screenshot 2024-01-26 at 16 20 12" src="https://github.com/flutter/flutter/assets/13645580/82707252-6665-46ba-8ff8-457ebc78278e">

look at width numbers - they're equals but now text shows correctly

I'm totally sure there is a bug in TextPainter source code but can't find it.

I found few discussions about it but all of them already closed and there is no solution or fix yet.
Obviously, this is not a font issue.

I didn't add flutter doctor because you can easily reproduce it in Dartpad.

**Comment by LongCatIsLooong** [comment]
The issue is likely that the text style you're using to configure the TextPainter is not the same as the one the Text widget uses.

**Comment by kalaganov** [comment]
<img width="554" alt="Screenshot 2024-01-27 at 00 29 46" src="https://github.com/flutter/flutter/assets/13645580/74428efa-41ae-4f04-9ef0-b8c6bd9f3b2a">

and  
```
      maxLines: 1,
      textWidthBasis: TextWidthBasis.longestLine,
 ```
 are not required, nothing changed if remove them

**Comment by LongCatIsLooong** [comment]
Ah. `layout()` takes the maximum input width as the parameter. If not specified, the max width is unlimited and there won't be any soft line breaks. 

Also Text adds additional text style to the text.

**Comment by moffatman** [comment]
It's likely other text properties are added to the `Text` via the `DefaultTextStyle` as you discovered. You could get the calculation to be the same by using `DefaultTextStyle.of(context).style` as part of your `style` for the `TextPainter`.

**Comment by kalaganov** [comment]
looks like `inherit: false` "fix" this issue

`const textStyle = TextStyle(fontSize: 32, inherit: false);`

but the main questions still remains - why `TextPainter` calculates "wrong" `width` by default so it has to wrap last letter

**Comment by moffatman** [comment]
Because your TextPainter doesn't have access to the `DefaultTextStyle` in ancestor `context`
