### ISSUE TITLE
Request to add `duration` property to `ExpansionTile` widget. 

### ISSUE THREAD

**Issue by imp-sike** [flutter/flutter#142363]
### Use case

I am currently using the `ExpansionTile` widget in my Flutter application and would like to have more control over the expansion and collapse animation duration. The current implementation has a hardcoded duration, and I believe it would be beneficial to expose this duration as a property for customization.
The [hardcoded duration](https://github.com/flutter/flutter/blob/3c22b1c773824982dcfa37b16551c68e4897cebd/packages/flutter/lib/src/material/expansion_tile.dart#L19) for the expansion and collapse animation is limiting for my use case. I would like to provide a custom duration for a more fluid and responsive user experience.

### Proposal

I propose adding a duration property to the ExpansionTile widget that allows developers to customize the expansion and collapse animation duration. This would provide more flexibility and control over the user interface.
```dart
ExpansionTile(
  title: Text(directoryModel.directories[index].name),
  maintainState: true,
  leading: const Icon(Icons.folder),
  duration: Duration(milliseconds: 500), // custom duration
)

```

**Comment by fischerscode** [comment]
I think this is a duplicate of #138047 and has therefore already been implemented in #139664. 🥳

**Comment by imp-sike** [comment]
Thank you for pointing that out! I appreciate the information. I'm glad to hear that this feature has already been implemented in issue #139664. Looking forward to seeing it in action! 🎉

**Comment by fischerscode** [comment]
If you need it right now, it's available in the beta channel.

**Comment by TahaTesser** [comment]
Thanks for linking the fix @fischerscode
