### ISSUE TITLE
`DropdownMenu` doesn't have a focusNode

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#142384]

**Comment by MaherSafadii** [comment]
ran into the same issue.

**Comment by Hixie** [comment]
I have a fix I just need to write a test. If anyone wants to do that for me that'll save me a bunch of time. ;-)

**Comment by TahaTesser** [comment]
> I have a fix I just need to write a test. If anyone wants to do that for me that'll save me a bunch of time. ;-)

I can help

**Comment by TahaTesser** [comment]
@Hixie 
If you could file a PR with your fix, assign me to review then I'll be to add test as " Maintainers are allowed to edit this pull request."

**Comment by Hixie** [comment]
The PR is: https://github.com/flutter/flutter/pull/142516

I tried a variety of ways to test this but couldn't find a way to prove that in a test the dropdown menu reacts to the focus node being focused. It seems to work fine in production.

Here's the skeleton of a test:

```dart
  testWidgets('DropDownMenu.focusNode', (WidgetTester tester) async {
    final FocusNode focusNode = FocusNode();
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
        body: DropdownMenu<String>(
          focusNode: focusNode,
          dropdownMenuEntries: const <DropdownMenuEntry<String>>[
            DropdownMenuEntry<String>(
              value: 'Yolk',
              label: 'Yolk',
            ),
            DropdownMenuEntry<String>(
              value: 'Eggbert',
              label: 'Eggbert',
            ),
          ],
        ),
      ),
    )); 
    // expectation showing the drop-down isn't focused
    focusNode.requestFocus();
    await tester.pump();
    // expectation showing the drop-down _is_ focused
  });
```

Things I tried:
* using `tester.sendKeyEvent` to see if the text field is getting text input
* doing a `paints` expectation to see that the focus ring is showing
* checking the `primaryFocus` to see if it changes

None of these things could prove the patch was changing anything. When I `flutter run` the test I can see it get focused when the `requestFocus` call is made, so I really don't understand what's going on.
