### ISSUE TITLE
[Icons] Missing Google Font Icons (eg Camping) in Flutter 

### ISSUE THREAD

**Issue by mongoose13** [flutter/flutter#142386]
### Use case

As a Flutter Developer, I can use the Icon Class in Dart to access the Camping Google Fonts Icon, so I can have a consistent user experience and code base for Icons supported by Google Fonts.

There are some missing Google Font Icons which if integrated into Flutter will allow the community to leverage them.

For example - There is a missing "camping" icon in Flutter - https://api.flutter.dev/flutter/material/Icons-class.html

The icon exists in

Google Fonts - https://fonts.google.com/icons?icon.query=camping and
Repo - https://github.com/google/material-design-icons/tree/master/symbols/web/camping

Can you please help integrate the missing "icons? Thank you for your help! 

### Proposal

I propose that we pull the code for missing icons from [Google Fonts repo](https://github.com/google/material-design-icons/tree/master/symbols/web/camping) into [Flutter Icon Class](https://api.flutter.dev/flutter/material/Icons-class.html)

Flutter users can then access "Camping" icon via the Icon class similar to all the other icons already available. 

Hope this helps! Please let me know if I can provide any more information.

**Comment by mongoose13** [comment]
I did some digging into the Flutter repository and it seems like this file will need to be updated to get the missing icons integrated - https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart

**Comment by thisisjaymehta** [comment]
Looks like its an auto generated file and we shouldn't manually update the files:
https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons

I would suggest changing title of issue to start with `[Icons]` as mentioned in the link above.

I'm surprised there are parts of flutter locked for only "Google". This is quite opposite of "Open Source". Process to update Icons in Open Source Framework should be, well open.
