### ISSUE TITLE
Scaffold 's persistentFooterButtons is not aware the safe area of iPhone X.

### ISSUE THREAD

**Issue by tsangpozheng** [flutter/flutter#14238]
## Steps to Reproduce

```
@override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Client'),
      ),
      body: new Column(children: <Widget>[
        new ListTile(
          title: const Text('Email'),
          trailing: new Text('${data['email']}'),
        ),
        new ListTile(
          title: const Text('Name'),
          trailing: new Text('${data['name']}'),
        ),
      ]),
      persistentFooterButtons: <Widget>[
        new FlatButton(
            onPressed: () {
              Navigator.pushReplacementNamed(context, '/servers');
            },
            child: const Text('Logout')),
        new FlatButton(
            onPressed: () {
              Navigator.pushReplacementNamed(context, '/servers');
            },
            child: const Text('Next')),
      ],
    );
  }
```

![image](https://user-images.githubusercontent.com/32248/35300606-eaf69594-00c3-11e8-8145-19feb4d64074.png)

## Flutter Doctor

/Users/tsangpo/workspace/sdk/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Mac OS X 10.13.2 17C205, locale zh-Hans-CN, channel alpha)
    • Flutter at /Users/tsangpo/workspace/sdk/flutter
    • Framework revision 8f65fec5f5 (6 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/tsangpo/workspace/sdk/android-sdk
    • Android NDK at /Users/tsangpo/workspace/sdk/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.0
    • ANDROID_HOME = /Users/tsangpo/workspace/sdk/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 5.0.2 (API 21) (emulator)
    • iPhone X                     • C9E5111B-A4B8-419F-965D-4F7965513CC9 • ios         • iOS 11.2 (simulator)

**Comment by cbracken** [comment]
Fixed by #14512
