### ISSUE TITLE
The default Android page transition is not up to date for M3.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142352]
See also:

the android zoom page transition relies on a cache to be effective, but these cache causes fidelity problems with common patterns. I will investigate some existing android samples to determine if this is actually the most current android page transition.

**Comment by jonahwilliams** [comment]
From

* https://m3.material.io/styles/motion/transitions/transition-patterns

I do not see the zooming behavior, that seems to have been an "M2" transition. there are different lateral/top-level transitions which we could initially approximate

**Comment by jonahwilliams** [comment]
Spec is here: https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md#shared-axis

The old zoom transition is the m2 one:

See https://m2.material.io/design/navigation/navigation-transitions.html#peer-transitions , Top Level transitions

**Comment by jonahwilliams** [comment]
FYI @goderbauer @johnmccutchan 

I also ran through compose-samples repo and could not find an example of the old transition.

**Comment by goderbauer** [comment]
Looks like we need to update our transition. @HansMuller Is this already on the list of remaining work for M3?

**Comment by HansMuller** [comment]
CC @QuncCccccc

**Comment by justinmc** [comment]
FYI @QuncCccccc I have plans to make PredictiveBackPageTransitionsBuilder the default transition for Android ([like this](https://github.com/flutter/flutter/pull/146788/files#diff-41923961de924e865545ad350e284d38a886d56134da05aaed3e551b3640a237R760)). It has a fallback transition that it uses when not doing predictive back, [currently set to ZoomPageTransitionsBuilder](https://github.com/flutter/flutter/blob/086b0d709c/packages/flutter/lib/src/material/predictive_back_page_transitions_builder.dart#L60). So assuming that the solution to this issue will be a new PageTransitionsBuilder class, we will need to update that fallback in PredictiveBackPageTransitionsBuilder. It also probably makes sense to check what the new transitions looks like during a predictive back gesture.

**Comment by QuncCccccc** [comment]
Thanks a lot for the information!
