### ISSUE TITLE
Request to add inputFormatters property to DropDownMenu for its text field.

### ISSUE THREAD

**Issue by sprabhdeep** [flutter/flutter#142374]
### Use case

I add certain fields in firestore in particular format. I want my text field to search if data already exists, if not then add to my firestore collection. DropDownMenu already has searchable filterable feature, it is just that I cannot add new user input values in certain format automatically.

I have tried creating my own searchable dropdown below textfield using other widgets including Stack, and cannot tap my entries in custom created dropdown to select them.

Thanks

### Proposal

Feature requested is inputFormatters as below like TextFormField already has it -

DropDownMenu(
 inputFormatters: [..]
 dropdownMenuEntries: //....
)

**Comment by fischerscode** [comment]
*Not related to the actual Feature Request!*

I'm not sure if I understand your problem correctly. But did you consider something like this?
```dart
class _MyHomePageState extends State<MyHomePage> {
  final controller = TextEditingController();
  final dropDownItems = {"Item1", "Item2"};

  @override
  void initState() {
    controller.addListener(() {
      if (mounted) {
        setState(() {});
      }
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: DropdownMenu(
            controller: controller,
            onSelected: (value) {
              print("${value} selected");
              if (value != null) {
                setState(() {
                  dropDownItems.add(value);
                });
              }
            },
            dropdownMenuEntries: [
              if (controller.text.isNotEmpty &&
                  !dropDownItems.contains(controller.text))
                DropdownMenuEntry(
                    value: controller.text, label: controller.text),
              for (var item in dropDownItems)
                DropdownMenuEntry(value: item, label: item)
            ]),
      ),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}
```
![grafik](https://github.com/flutter/flutter/assets/45403027/08459156-aba3-48fd-8bc8-2786476981a2)

**Comment by sprabhdeep** [comment]
Yes I am using this. But ... For example user types in a new client name in the textfield which is not present in my database and hence not present in drop down menu items as I fetch items (names in my example) for my dropdownEntries from database. Then this new client is saved in my database, but user generally do not type first alphabets of name capital, so I want a inputFormatter property where in I can pass my FisrtAlphabetCapitalOfAllWords function and make it visible to user when he types in and also store my data in the format I want.

usage required is -
DropDownMenu(
  inputFormatters: [FisrtAlphabetCapitalOfAllWords()]
  controller: myController
  dropdownMenuEntries : //....
)

If there is another way to format the user text that'll also help.

**Comment by sprabhdeep** [comment]
And if I'm correct, caps or noCaps do not matter in the search/filter feature of DropDownMenu, so, it still will search through items if they have those characters irrespective of their case. Thanks

**Comment by justinmc** [comment]
This seems reasonable to me at first glance. I don't think there's any other way to set the inputFormatters on the TextField that is generated by DropDownMenu, so it makes sense to add a parameter and pass it through.

@QuncCccccc I'm not super familiar with the DropDownMenu API, do you have any thoughts on whether this parameter is a good idea?

If no one objects then I'd be happy to review a PR for this!

**Comment by piedcipher** [comment]
would like to take this up, once proposal is approved.

**Comment by sprabhdeep** [comment]
Please add this if no one has objections ??

**Comment by QuncCccccc** [comment]
> This seems reasonable to me at first glance. I don't think there's any other way to set the inputFormatters on the TextField that is generated by DropDownMenu, so it makes sense to add a parameter and pass it through.
> 
> @QuncCccccc I'm not super familiar with the DropDownMenu API, do you have any thoughts on whether this parameter is a good idea?
> 
> If no one objects then I'd be happy to review a PR for this!

I don't think we currently support this, so adding a inputFormatters sounds good to me! Sorry for the late response. Would be happy to review a PR as well!

**Comment by piedcipher** [comment]
> > This seems reasonable to me at first glance. I don't think there's any other way to set the inputFormatters on the TextField that is generated by DropDownMenu, so it makes sense to add a parameter and pass it through.
> > @QuncCccccc I'm not super familiar with the DropDownMenu API, do you have any thoughts on whether this parameter is a good idea?
> > If no one objects then I'd be happy to review a PR for this!
> 
> I don't think we currently support this, so adding a inputFormatters sounds good to me! Sorry for the late response. Would be happy to review a PR as well!

kicking off the work! thanks 👍🛠️
