### ISSUE TITLE
[Impeller] guassian blurs fail in opengl

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#142355]
Seen in 125180b8a7204de823544d658e89f7d3dac65e11

Example failure:
<img width="1027" alt="Screenshot 2024-01-26 at 4 27 07 PM" src="https://github.com/flutter/flutter/assets/30870216/a0acee36-e9bc-4bb8-aa2b-0c86b78aa7a9">

**Comment by chinmaygarde** [comment]
Cursory investigation reveals that this may be related to https://github.com/flutter/flutter/issues/141732 as there are tons of log messages about missing mips.
