### ISSUE TITLE
Can't run flutter tests on CircleCI - missing libglu.1.so

### ISSUE THREAD

**Issue by paulcbetts** [flutter/flutter#14239]
(I can't really file this on the CircleCI repo, so I wanted to make a note here even though it's not actually Flutter's fault)

## Steps to Reproduce

1. Set up a CircleCI build using the `circleci:/android-*` images
1. Run `flutter test` in CI

```sh
Shell: /home/circleci/todo/vendor/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory
00:00 +0 -1: loading /home/circleci/todo/test/widget_test.dart [E]
  Failed to load "/home/circleci/todo/test/widget_test.dart":
  Shell subprocess crashed with unexpected exit code 127 before connecting to test harness.
  Test: /home/circleci/todo/test/widget_test.dart
  Shell: /home/circleci/todo/vendor/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester
  ```

I'm going to try to patch this into https://github.com/circleci/circleci-images and reference this and hopefully CircleCI will be amenable

**Comment by paulcbetts** [comment]
Fixed! Not sure when they push new images to Docker (since a full build probably generates 30GB+ of Docker images every build), but this should be taken care of

**Comment by dazza5000** [comment]
Do you have a tutorial / circle.yaml you could share?
