### ISSUE TITLE
Upgrade Phase 2 for iOS 17 (more x86 prod bots)

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#142326]
Prod pool:

x86 - Upgrade 3 devices (6 / 12)
- [x] Upgrade device on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-7
- [x] Upgrade device on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-8
- [x] Upgrade device on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-9

---

**Please quarantine the bot before upgrading.**

Steps after upgraded to iOS 17 on iPhone devices.

* Open Xcode 15 from /opt/flutter/xcode/15a240d/XCode.app
* In the top bar, open Window > Device and Simulators
* The window that opens should show the connected device
* Accept the Trust dialog on the iPhone device
* If you get the dialog on the device twice, you may need to accept it once, disconnect, reconnect, and accept again.
* Wait for the yellow bar at the top of the Device and Simulators window to go away - It should take a minute or so to Copy cache symbols

Once all steps above are complete, the device can be taken out of quarantine.

**Comment by yusuf-goog** [comment]
@kentnguyen99 lets start with these devices. Lets complete each device before moving on to the next. Confirm with @vashworth if you need to verify the upgrade is correct.

**Comment by kentnguyen99** [comment]
@vashworth The following iPhone devices have been upgraded IOS 17 for mac-7, mac-8 & mac-9. Will you check these Bots before these Bots into productions. Thanks.

**Comment by vashworth** [comment]
All devices look good and working. Thanks!
