### ISSUE TITLE
Test order flake in flutter_tool test/general.shard/dart/language_version_test.dart

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#142376]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_tests_general/15533/overview

It looks like the global variable here is causing some cross-test pollution: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/language_version.dart#L20

**Comment by eliasyishak** [comment]
Closing since this was done in:
- https://github.com/flutter/flutter/pull/142378

**Comment by zanderso** [comment]
Ah, sorry this was unclear. This issue was meant to track fixing the tests in the file so that the `no-shuffle` flag could be removed.

**Comment by eliasyishak** [comment]
Ah my mistake, just going through issue triage and this came up
