### ISSUE TITLE
"git describe":  Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.

### ISSUE THREAD

**Issue by lubi888** [flutter/flutter#14232]
Hi guys,
I just ran 'flutter upgrade' but instead my flutter installation is now not running code.

I have taken a look at [#8612](https://github.com/flutter/flutter/issues/8612) and I've also cloned a fresh copy of flutter but I'm still stuck with some UTF-8 error. There's no answer on Stackoverflow.

Is this a Git issue? The flutter directory has no strange characters in the directory path and sits under /home/user/dart/flutter. 

I don't know how to get flutter working again.
```
flutter doctor
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.

flutter doctor --bug-report
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.

$ flutter doctor -v
[  +25 ms] [/home/iveagh/dart/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +122 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/master
[   +1 ms] [/home/iveagh/dart/flutter/] git rev-parse --abbrev-ref HEAD
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +1 ms] [/home/iveagh/dart/flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +1 ms] [/home/iveagh/dart/flutter/] git log -n 1 --pretty=format:%H
[  +22 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8059aea365f7527f2a8ac3d639f8af375060457d
[   +1 ms] [/home/iveagh/dart/flutter/] git log -n 1 --pretty=format:%ar
[  +17 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 14 hours ago
[   +3 ms] [/home/iveagh/dart/flutter/] git describe --match v*.*.* --exclude *-* --first-parent --long --tags
[  +20 ms] Exit code 129 from: git describe --match v*.*.* --exclude *-* --first-parent --long --tags
[   +1 ms] error: unknown option `exclude'
           usage: git describe [<options>] [<commit-ish>...]
              or: git describe [<options>] --dirty
           
               --contains            find the tag that comes after the commit
               --debug               debug search strategy on stderr
               --all                 use any ref
               --tags                use any tag, even unannotated
               --long                always use long format
               --first-parent        only follow first parent
               --abbrev[=<n>]        use <n> digits to display SHA-1s
               --exact-match         only output exact matches
               --candidates <n>      consider <n> most recent tags (default: 10)
               --match <pattern>     only consider tags matching <pattern>
               --always              show abbreviated commit object as fallback
               --dirty[=<mark>]      append <mark> on dirty working tree (default: "-dirty")
[  +11 ms] Could not interpret results of "git describe": 
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.

flutter analyze -v  (gives the same output as flutter
[  +12 ms] [/home/iveagh/dart/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/home/iveagh/dart/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/home/iveagh/dart/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/home/iveagh/dart/flutter/] git log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8059aea365f7527f2a8ac3d639f8af375060457d
[        ] [/home/iveagh/dart/flutter/] git log -n 1 --pretty=format:%ar
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 14 hours ago
[   +1 ms] [/home/iveagh/dart/flutter/] git describe --match v*.*.* --exclude *-* --first-parent --long --tags
[   +5 ms] Exit code 129 from: git describe --match v*.*.* --exclude *-* --first-parent --long --tags
[        ] error: unknown option `exclude'
           usage: git describe [<options>] [<commit-ish>...]
              or: git describe [<options>] --dirty
           
               --contains            find the tag that comes after the commit
               --debug               debug search strategy on stderr
               --all                 use any ref
               --tags                use any tag, even unannotated
               --long                always use long format
               --first-parent        only follow first parent
               --abbrev[=<n>]        use <n> digits to display SHA-1s
               --exact-match         only output exact matches
               --candidates <n>      consider <n> most recent tags (default: 10)
               --match <pattern>     only consider tags matching <pattern>
               --always              show abbreviated commit object as fallback
               --dirty[=<mark>]      append <mark> on dirty working tree (default: "-dirty")
[   +3 ms] Could not interpret results of "git describe": 
[ +571 ms] Analyzing 1368 files...
```

**Comment by jason-simmons** [comment]
The git describe error is happening because older versions of git lack the git describe --exclude flag.  Upgrade to git 2.13.0 or later.

The Dart_NewStringFromUTF8 error is probably happening because some string taken from the environment is not valid UTF-8.  However I can't tell from the log what the specific string might be.

**Comment by lubi888** [comment]
Hi Jason

I updated Git from 2.7.4 to 2.15.1 so that worked.

I have removed all the other files from the folder where flutter is installed via git clone. Flutter is sitting on its own under /home/user/dart/flutter so I don't understand where this interfering string is coming from.

Thanks for your help, Jason

flutter doctor -v
[  +12 ms] [/home/iveagh/dart/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/home/iveagh/dart/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/home/iveagh/dart/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/home/iveagh/dart/flutter/] git log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8059aea365f7527f2a8ac3d639f8af375060457d
[        ] [/home/iveagh/dart/flutter/] git log -n 1 --pretty=format:%ar
[   +3 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 17 hours ago
[        ] [/home/iveagh/dart/flutter/] git describe --match v*.*.* --exclude *-* --first-parent --long --tags
[  +15 ms] Exit code 0 from: git describe --match v*.*.* --exclude *-* --first-parent --long --tags
[        ] v0.0.20-294-g8059aea36
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.

**Comment by lubi888** [comment]
Hi Jason,

just to let you know I got my flutter back.

I found a file in my home folder with an incorrect name [���0��0 (invalid encoding)]. How it got there I have no idea. Once it was removed flutter doctor -v worked again.

I didn't find it before because I presumed that dart||git would not need access to the /home/user folder. I thought linux permissions would stop this. Obviously, this is not the case. 

The erroneous file was under the usr folder, /home/user/���0��0 (invalid encoding), and for some reason this was throwing off the dart within the flutter installation in /home/usr/dart/flutter.

**Comment by Hixie** [comment]
Reopening to handle old gits better.
