### ISSUE TITLE
Flutter final constant error

### ISSUE THREAD

**Issue by FluffPawz** [flutter/flutter#142388]
Hello, I have been trying to follow tutorials for flutter. It goes well until I come to this part. I am unsure of how to really word what goes wrong, but it's probably something simple.

class MyTextField extends StatelessWidget {
  final controller;

  const MyTextField({
    super.key,
    required this.controller,
});

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(horizontal: 25.0),
      child: TextField(
        controller: controller,
),

I am getting the error "An uninitalized field shoud have an explicit type annotation." On the first part of the code for the controller,

I've had to stop 2 projects because, I am missing something here. 
The basic idea is to grab the info a user will put in for a Login page.
Any help is appreciated. Thanks for looking!

**Comment by Cierra-Runis** [comment]
```
final TextEditingController controller;
```

**Comment by philwamba** [comment]
You declared the ```controller``` field in your ```MyTextField``` class without a type.

You should declare it as such:
```dart
class MyTextField extends StatelessWidget {
  final TextEditingController controller;  // Specify the type

  const MyTextField({
    super.key,
    required this.controller,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 25.0),
      child: TextField(
        controller: controller,
      ),
    );
  }
}
```

**Comment by FluffPawz** [comment]
Awesome, that fixed the first part, thanks so much.

      child: TextField(
        controller: controller,
)
I am still getting an error there saying Invaild constant value.

**Comment by Cierra-Runis** [comment]
```dart
return Padding(
  padding: EdgeInsets.symmetric(horizontal: 25.0),
  child: TextField(
    controller: controller,
  ),
)
```

Please learning `dart` again.

**Comment by FluffPawz** [comment]
I enjoy learning by doing, thanks for the advice!

**Comment by FluffPawz** [comment]
> Remove `const` as below:
> 
> ```dart
> return Padding(
>   padding: const EdgeInsets.symmetric(horizontal: 25.0),
>   child: TextField(
>     controller: controller,
>   ),
> )
> ```
> 
> Please learning `dart` again and close this issue.

I said I was trying to learn :)
