### ISSUE TITLE
Step 6 of the Firebase tutorial has an incorrect step.

### ISSUE THREAD

**Issue by rdurel423** [flutter/flutter#14234]
I'm not sure if this is the place to post this as it's not a code-related issue, but after scratching my head over a crash that kept occurring on iOS when Google Sign-In should launch I noticed that the following step under **Configure Google Sign-In on iOS** is incorrect;

> Add the bindle ID and reverse URL of your client id to the main dictionary of your app's `GoogleService-Info.plist` file:

should be

> Add the **bundle** and reverse URL of your client id to the main dictionary of your app's `Info.plist` file.

**Comment by Hixie** [comment]
cc @Sfshaza @collinjackson

**Comment by Sfshaza** [comment]
@rdurel423, this is a codelab that we have retired. Sorry for the confusion. Closing.
