### ISSUE TITLE
One blink of text cursor costs 2 frames on the GPU thread

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#14242]
![img_20180123_175938](https://user-images.githubusercontent.com/211513/35310676-62b76912-0067-11e8-97c9-06729170de40.jpg)

/cc @cbracken

**Comment by dannyvalentesonos** [comment]
The issue is the opacity animation on the cursor. When making it act like an Android device, by forcing **cursorOpacityAnimates** to be false on the EditableText widget, the blinking cursor takes up barely any time to render.

**Comment by iapicca** [comment]
Hi @yjbanov is this issue still meant to be open?

**Comment by yjbanov** [comment]
No. EditableText has been rewritten so many times since I filed this one, it's no longer relevant. Closing.
