### ISSUE TITLE
Make hello_world__memory run if the build configuration is modified 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#142450]
https://github.com/flutter/flutter/pull/142300#issue-2102312089

Either Configure post submit test `Linux_android hello_world__memory` to run in presubit if one of the build files is modified OR setup a test where the code is compiled but the memory performance test does not run in presubmit.

**Comment by reidbaker** [comment]
Possibly related https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/github/webhook_subscription.dart

**Comment by CaseyHillers** [comment]
In the ci.yaml for the target, 

```yaml
--- presubmit: false
+++ runIf:
+++  - .ci.yaml
+++  - examples/hello_world/android/**
```
