### ISSUE TITLE
Embedder for Systems with no OpenGL support

### ISSUE THREAD

**Issue by ElectraV** [flutter/flutter#142415]
### Use case

Evaluating Flutter on i.MX93, we observed poor performances as this platform has no GPU, only a 2D engine called Pixel Processing Pipeline.  
Researching, we found multiple embedders, but all of them are using OpenGL. 

### Proposal

Is there any plan to develop an Embedder for Systems with no OpenGL support?

**Comment by stuartmorgan** [comment]
Anyone is welcome to create an embedder for their specific use case: https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders

Closing as out of scope, since the Flutter team is not involved in the creation of third-party embedders.

**Comment by jwinarske** [comment]
You can try swiftshader with d2d backend enabled, then use one of the existing embedders that supports d2d vulkan.  No need to reinvent the wheel.
