### ISSUE TITLE
generate_gradle_lockfiles is not run on CI

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#142475]
I think we should run [generate_gradle_lockfiles](https://github.com/flutter/flutter/blob/1d5c2c51187e5c608f36e81d6f89c1782918ab85/dev/tools/bin/generate_gradle_lockfiles.dart) on (pre/post – idk)submit tests. 

### Problems

Sometimes, regenerating gradle lockfiles results in git changes. I don't think that it should be happening, i.e. the running:

```
find . -type d -name 'android' | dart dev/tools/bin/generate_gradle_lockfiles.dart
```

should result in no git changes.

Sometimes, it fails altogether (often on different project - look at the logs carefully):

[crash_logs_1.txt](https://github.com/flutter/flutter/files/14089272/crash_logs_1.txt)

[crash_logs_2.txt](https://github.com/flutter/flutter/files/14089273/crash_logs_2.txt)

I didn't debug thse crashes further but usually re-reunning results in a different failure.

**Comment by christopherfujino** [comment]
FYI @gmackall, if you end up running the script from the pub roller bot

**Comment by christopherfujino** [comment]
Re-opening as it is still not working.
