### ISSUE TITLE
Remove "Using the Impeller rendering backend" error that logs on every `flutter run`.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#142488]
1. Using Impeller shouldn't be an error.
2. Now that impeller is the default on iOS https://github.com/flutter/engine/pull/40405, let's switch this to only log if Impeller is _off_.

```
Launching lib/main.dart on iPad Pro 11 in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: S8QB4VV633
Running Xcode build...
 └─Compiling, linking and signing...                      2,940ms
Xcode build done.                                           14.3s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Installing and launching...                                        21.8s
```

**Comment by zanderso** [comment]
From triage:
1. We should not print a message when Impeller is used on iOS, but should still indicate in the logs in release mode which backend is in-use by instead printing that Skia is being used.
2. The printed message should not be an error, so we'll need a new log-level.
