### ISSUE TITLE
[Android] Re-land `flutter.groovy` logic needed to support Gradle Kotlin DSL

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#142487]
https://github.com/flutter/flutter/pull/142464 reverts logic in `flutter.groovy` in order to fix https://github.com/flutter/flutter/issues/141940, but in the process, has removed some logic required to add support for the Gradle Kotlin DSL that was added in https://github.com/flutter/flutter/pull/140744. This issue serves as a reminder to re-land this logic to maintain that support.

This involves two steps:

- [ ] Replace the [old implementation](https://github.com/flutter/flutter/pull/142464/files#diff-f0cdaf8963c97a175f64fe0fad130260d0614dd6cecd5cbe9580628bd51c5a4cR767-R770) of `doesSupportAndroidPlatform` with the [new implementation](https://github.com/flutter/flutter/pull/140744/files#diff-f0cdaf8963c97a175f64fe0fad130260d0614dd6cecd5cbe9580628bd51c5a4cR458-R469) created in https://github.com/flutter/flutter/pull/140744.
- [ ]  When https://github.com/flutter/flutter/pull/137115 is re-landed, add back logic that [checks for Gradle settings configuration](https://github.com/flutter/flutter/pull/140744/files#diff-f0cdaf8963c97a175f64fe0fad130260d0614dd6cecd5cbe9580628bd51c5a4cR476-R486) for both Groovy or Kotlin

**Comment by camsim99** [comment]
cc @Gustl22 since I believe you will take the second task when re-landing your change?

**Comment by Gustl22** [comment]
Thank you for raising. I'll take care of that. I hope I find a solution described [here](https://github.com/flutter/flutter/issues/141940#issuecomment-1915427379)
