### ISSUE TITLE
How to get a refresh token in google_sign_in plugin?

### ISSUE THREAD

**Issue by csbenjamin** [flutter/flutter#14245]
I want to do a server side authentication, so I need a refresh token to request an access token on server side. How can I get that?

**Comment by pulyaevskiy** [comment]
Similar use case.

Trying to integrate this Flutter plugin with https://pub.dartlang.org/packages/googleapis_auth which provides auto-refreshing HTTP client implementation, however this requires (afaik) refreshToken.

`GoogleSignInAuthentication` does not expose it currently. 

The question is: does the plugin refresh access token for us when it expires automatically (meaning we can fetch updated accessToken somehow)?

**Comment by premtemp1** [comment]
any solution to this issue?

**Comment by lookfirst** [comment]
I just ran into this. Consider it another vote! This is a major issue.

**Comment by lookfirst** [comment]
FML. I tried to use signInSilently to refresh the users idToken and now I get this on the server when I try to verify it. It is the same project, for sure.

Firebase ID token has incorrect "aud" (audience) claim. Expected "bleep" but got "BLEEEP.apps.googleusercontent.com". Make sure the ID token comes from the same Firebase project as the service account used to authenticate this SDK. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.

**Comment by lookfirst** [comment]
I think I've figured it out. Latest version has `getIdToken(refresh:bool)`. This issue can likely be closed.

**Comment by VladyslavBondarenko** [comment]
Please follow up on https://github.com/FirebaseExtended/flutterfire/issues/1079,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
