### ISSUE TITLE
[Impeller] mipmaps for subpass caused difference in TileMode render

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#142542]
https://github.com/flutter/engine/pull/50157 added mipmaps to things drawn with blur image filters.  This caused `AiksTest.CanRenderClippedBlur` to have a difference:
<img width="690" alt="Screenshot 2024-01-30 at 9 10 05 AM" src="https://github.com/flutter/flutter/assets/30870216/789bd73f-4b9a-49e2-9deb-386a39306c81">

The burring effect has to do with the behavior when sampling outside of a texture.  Since the blur was set to use `kClamp`, that creates the blurring effect.

I switched the test to use `kDecal` so that the output matches the old output.

I suspect that the old rendering with `kClamp` was incorrect.  That there was some optimization that was avoiding the subpass that wasn't taking into account the TilingMode of the blur.

It would be nice to know if that is in fact the case, this issue is to investigate this problem and to leave a tombstone for this decision.  This may change someones render, but the fix is just to adjust the TilingMode.

cc @jonahwilliams @bdero

**Comment by jonahwilliams** [comment]
Since this is WAI (THe new image is correct, the old one incorrect), I think we should close this issue.
