### ISSUE TITLE
[Impeller] Filter graph should make an effort to re-use cmd buffers.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142545]
Command Buffers can encode multiple render or blit passes, provided that the previous render pass has completed before a new one is added. Since there is some overhead in creating and submitting a cmd buffer, we can slightly improve CPU performance on filter heavy scenes (backdrop blur benchmark) by utilizing the same cmd buffer in parts of the filter graph.

For example, the gaussian blur shader performs multiple render passes in sequential order, but uses a different cmd buffer for each one. These could be combined into a single cmd buffer.

**Comment by jonahwilliams** [comment]
FYI @bdero

**Comment by jonahwilliams** [comment]
Using the macrobenchmarks app backdrop perf example:

ToT: 427 Cmd buffers.

If we institute some basic reuse in the filter graph, we can reduce that to 250.

**Comment by jonahwilliams** [comment]
is that worth doing? uh question mark. Need to profile on iOS. In theory it shouldn't matter for Vulkan, and obvs not for GLES.

**Comment by bdero** [comment]
Nice to have, but ultra low priority? If you have enough GPU filters for this to make a dent, you're probably fucked on the GPU anyway.

**Comment by jonahwilliams** [comment]
This is done, sort of!
