### ISSUE TITLE
[go_router] redirect to shell router

### ISSUE THREAD

**Issue by rebazjabar** [flutter/flutter#142547]
hello 
it is for long time i try to fix this problem but i couldn't find the solution from the official videos and documentation.
i wanna use redirect while the user logs in. It goes to the Shell route, not the homepage. What is the solution  for that case as you know most of the developers use Shell route for landing page while user logging in .

please as soon as possible answer me 
import 'package:buy_online_shopping/_shared/services/user_preferences.dart';
import 'package:buy_online_shopping/screens/auth/presentation/pages/sign_in.dart';
import 'package:buy_online_shopping/screens/auth/presentation/pages/sign_up.dart';
import 'package:buy_online_shopping/screens/intro/presentation/pages/onboardingpage.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:buy_online_shopping/screens/intro/presentation/pages/splash.page.dart';
import 'package:buy_online_shopping/screens/landing/presentation/pages/home.page.dart';
import 'package:buy_online_shopping/screens/landing/presentation/pages/landing.page.dart';
import 'package:buy_online_shopping/screens/website/presentation/pages/web_links_page.dart';
import 'package:buy_online_shopping/_helpers/utils.dart';

`final goRouteProvider = Provider((ref) {
  return GoRouter(
      routerNeglect: true,
      initialLocation: SplashPage.route,
      navigatorKey: Utils.mainNav,
      redirect: (context, state) async {
        var userLoggiedIn = await RememberUserPrefs.readUserInfo();

        if (userLoggiedIn != null) {
          //i wanna return Shell route not landing page
          //it should be  GoRouter.of(Utils.mainNav.currentContext!).go('/homepage');
          //but it will return null

          return LandingPage.route;
        } else {
          return SplashPage.route;
        }
      },
      routes: [
        GoRoute(
          parentNavigatorKey: Utils.mainNav,
          path: SplashPage.route,
          builder: (context, state) {
            return const SplashPage();
          },
        ),

        GoRoute(
          parentNavigatorKey: Utils.mainNav,
          path: OnboardingPage.route,
          builder: (context, state) {
            return const OnboardingPage();
          },
        ),
        GoRoute(
          path: SignIn.route,
          builder: (context, state) => const SignIn(),
        ),
        GoRoute(
            path: SignUp.route, builder: (context, state) => const SignUp()),

//Bottom Appbar
        ShellRoute(
            navigatorKey: Utils.tabNav,
            builder: (context, state, child) {
              return LandingPage(child: child);
            },
            routes: [
              GoRoute(
                parentNavigatorKey: Utils.tabNav,
                path: HomePage.route,
                pageBuilder: (context, state) {
                  return const NoTransitionPage(
                    child: HomePage(),
                  );
                },
              ),
              GoRoute(
                parentNavigatorKey: Utils.tabNav,
                path: WebLinksPage.route,
                pageBuilder: (context, state) {
                  return const NoTransitionPage(
                    child: WebLinksPage(),
                  );
                },
              ),
            ]),
      ]);
});
`

**Comment by huycozy** [comment]
Hi @rebazjabar 
The goal of this Github repo is not to assist in personal code or the whole package/plugin project but to improve Flutter framework reporting bugs or feature requests.

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. If you believe there is a bug in `go_router` package and propose a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing from here as this is more of a `how-to` question rather than a bug or feature request.
