### ISSUE TITLE
Plugin HTML -> PDF (android part complete)

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#14259]
I use this feature in my Android Apps. 
Its useful if you want to show the user information which they can view now, save for later reference or print.

HTML to PDF conversion works well in Android and I read that it is supported in IOS.

**Comment by Rockvole** [comment]
I have created a plugin for this. I only have experience of Android development - so only the Android side works - incase anyone needs this also and wants to add the IOS side.
https://github.com/Rockvole/pdfview

**Comment by gedw99** [comment]
This is awesome !
The Method Channel just calls "pdfiew". Is PDFView some native thing included in android ?

Also if anyone knows the IOS way to do this please shout :)

**Comment by mit-mit** [comment]
Hi @Rockvole, can you clarify if this bug tracks some issue you encountered?

If you are looking to share the plugin with others, you should consider publishing it to Pub, see https://flutter.io/developing-packages/#publish for details.

**Comment by Rockvole** [comment]
Converting html to pdf is part of Android. I've had that code in my android apps for a long time, so I just copy-pasted.
Here is a tutorial for converting html to pdf for ios :
http://www.cuelogic.com/blog/convert-html-to-pdf-in-ios/

This issue was originally a bug - but once I realised its not too hard to make a plugin I changed this bug to a half-bug, since it addresses android but not ios.

I think it would be better to publish this when it is complete - devs will just be frustrated its not multi-platform.

**Comment by gedw99** [comment]
Sounds great. Will be really awesome to try this out.

**Comment by mit-mit** [comment]
There's no issue with publishing something for just one platform (see for example https://pub.dartlang.org/packages/android_alarm_manager), so if the Android support is fairly complete I'd still recommend that.

**Comment by Rockvole** [comment]
Looks like someone has added the IOS part from a fork of my plugin.
I have not tried it myself yet.

https://github.com/rsixel/pdfview

**Comment by gedw99** [comment]
Wow that's fortunate. Thanks for the heads up.

**Comment by Rockvole** [comment]
I tried running the pdfview by rsixel, but it looks like there is a missing file, so I get the error :

    Xcode build done.                                            1.7s
    Failed to build iOS app
    Error output from Xcode build:
    ↳
        ** BUILD FAILED **
    
    Xcode's output:
    ↳
        === BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
        /work/projects/flutter/pdfview/ios/Classes/PdfviewPlugin.m:6:13: fatal error: 'pdfview/pdfview-Swift.h' file not found
            #import <pdfview/pdfview-Swift.h>
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
        1 error generated.
    Could not build the application for the simulator.
    Error launching application on iPhone 6s Plus.

Unfortunately rsixel has not turned on the ability to file github issues and doesn't have his email address on github, so it looks like ios is a no-go for now :(

**Comment by gedw99** [comment]
Rascal !

**Comment by Rockvole** [comment]
Its possible this is a Xcode 8 (Swift 2) vs Xcode 9 (Swift 3) issue.
I tried rsixels code in Xcode 8.2.1 and there were no errors (so I assume the code is Swift 2). 

Unfortunately flutter no longer supports running with Xcode 8.
https://github.com/flutter/flutter/issues/14553

**Comment by rsixel** [comment]
Hi All,

Sorry to not comment on thread. I'm back to try to solve this. I'm trying to produce HTL->PDF using swift. Due to Xcode and Swift upgrade I'll try to use Xcode 10 and Swift 4 to do that.

As far as I have it done I'll send a pull request to you @Rockvole.

Regards

**Comment by Hixie** [comment]
@Rockvole This looks great! Can you elaborate on what you would like us to do with this issue?

**Comment by Rockvole** [comment]
You can close the issue if you think it should be community driven.
My plugin doesn't work in IOS so is only partially useful as a flutter plugin.

**Comment by Rockvole** [comment]
My plugin stopped work so well due to dart 2 upgrades and various flutter config changes.
Anyway, I tidied it up and also renamed it since the name was not very descriptive.
https://pub.dartlang.org/packages/flutter_html2pdf_viewer/

(Still android only however.)

**Comment by Afur** [comment]
I've created working HTML to PDF plugin with works with Android and iOS and supports Image rendering on iOS :) 

https://pub.dartlang.org/packages/flutter_html_to_pdf

@Rockvale it also works with iOS so maybe it'll resolve your problems

**Comment by Afur** [comment]
Source: https://github.com/Afur/flutter_html_to_pdf

**Comment by Rockvole** [comment]
Neat - this should allow displaying pdfs in combination with this plugin :
https://pub.dartlang.org/packages/pdf_viewer_plugin

Although it is preferable in my use case to not store the pdf file to disk, since a new pdf would be saved every time the user is in the app. The user gets the option to save / print from the device pdf viewer anyway.

**Comment by sjeet11** [comment]
> Check out my example project, I'm generating PDF file and then I display it by using different plugin:
> https://pub.dartlang.org/packages/flutter_full_pdf_viewer
> 
> You can delete generated file by just calling File.delete(); method :)

Is there an option to change the scale of the PDF, because few of pages are getting cropped due to scale issue.

**Comment by stuartmorgan** [comment]
It sounds like there are community plugins covering this use case now, so I'm going to go ahead and close this.
