### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by sendhyrama** [flutter/flutter#142584]
## Command
```
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target C:\devs\git-repo\sanberappflutter\lib\main.dart
```

[✓] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.22631.3085], locale en-ID)
    • Flutter version 3.16.7 on channel stable at C:\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (3 weeks ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Sendhy Ramadhinata\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.85.2)
    • VS Code at C:\Users\Sendhy Ramadhinata\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3085]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.83

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ef1af02aead6fe2414f3aafa5a61087b610e1332
### Plugins
firebase_auth-4.16.0
firebase_auth_web-5.8.13
firebase_core-2.24.2
firebase_core_web-2.10.0

**Comment by dam-ease** [comment]
Hello @sendhyrama.
Do you get any more logs after this exception is triggered? If so, can you provide the same here?
Also, is this exception occurring consistently every time you run the said command?

**Comment by sendhyrama** [comment]
> Hello @sendhyrama. Do you get any more logs after this exception is triggered? If so, can you provide the same here? Also, is this exception occurring consistently every time you run the said command?

Hi @dam-ease,
Appreciate your attention. I've managed to resolve the issues. It turns out I made an error in specifying dependencies in the build.gradle, with discrepancies between the app module and the root project.
