### ISSUE TITLE
flutter app draw on photo

### ISSUE THREAD

**Issue by patansako** [flutter/flutter#142511]
import photo from gallery and draw polygons and lines on it but when I save the photo polygon size become small and change its position and come at top left ..how can I fix this issue?thanks in advance

**Comment by dam-ease** [comment]
Hello @patansako.
Thanks for filing this.
The code sample you shared contains third-party packages and some codes that might not be necessary for reproducing this issue.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

Also, kindly provide more information on the issue you are experiencing as specified in the issue template, most especially, your `flutter doctor -v` output and the `Expected` vs `Actual` Results.

**Comment by patansako** [comment]
Thank you for response, sorry I'm new at this field . I am building a app to import photo from gallery and draw polygon . While drawing reduce the dimension of photo to fit in sizeBox but when i save the photo in local storage photo's size back to original size and drawn polygon size reduce and position is also changed.
![Screenshot_20240131-091946](https://github.com/flutter/flutter/assets/120083723/fcc27ea4-a3c3-44c9-af30-6281c161a53b)
![Screenshot_20240131-091946 1](https://github.com/flutter/flutter/assets/120083723/68cad792-c995-4bb7-8d1d-977e056346ce)

<this is how try to save >
`if (_image != null) {
        final recorder = ui.PictureRecorder();
        final canvas = Canvas(recorder);
        final paint = Paint();

        // Draw the image
        final scaleX = _image!.width.toDouble() / _image!.width;
        final scaleY = _image!.height.toDouble() / _image!.height;
        final scaledImageRect = Rect.fromPoints(
          const Offset(0, 0),
          Offset(_image!.width.toDouble() * scaleX, _image!.height.toDouble() * scaleY),
        );
        canvas.drawImageRect(
          _image!,
          Rect.fromPoints(
            Offset.zero,
            Offset(_image!.width.toDouble(), _image!.height.toDouble()),
          ),
          scaledImageRect,
          paint,
        );

        linePainter.paint(canvas, Size(_image!.width.toDouble(), _image!.height.toDouble()));
        final picture = recorder.endRecording();
        final img = await picture.toImage(
          (_image!.width * scaleX).toInt(),
          (_image!.height * scaleY).toInt(),
        );
        final byteData = await img.toByteData(format: ui.ImageByteFormat.png);

        if (byteData != null) {
          final buffer = byteData.buffer.asUint8List();
          final filePath = '${appDir!.path}/image_with_polygons_and_lines.png';

          await File(filePath).writeAsBytes(buffer);
          print('Image saved at: $filePath');`

<this is how i draw polygon>
` @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..strokeWidth = 2.0
      ..color = Colors.red
      ..style = PaintingStyle.stroke;
final scaleX = size.width / image.width;
    final scaleY = size.height / image.height;

  
    final scaledImageRect = Rect.fromPoints(
      const Offset(0, 0),
      Offset(image.width.toDouble() * scaleX, image.height.toDouble() * scaleY),
    );

    canvas.drawImageRect(
      image,
      Rect.fromPoints(
        Offset.zero,
        Offset(image.width.toDouble(), image.height.toDouble()),
      ),
      
      scaledImageRect,
      paint,
    );

   
    
    final fillPaint = Paint()..style = PaintingStyle.fill;

    for (final polygon in polygons) {
      fillPaint.color = polygon.color.withOpacity(0.5);

      final path = Path();
      final borderPath = Path(); // Define the path here

      String label1 = 'x';
      String label2 = 'x2';
      String label3 = 'y2';
      String label4 = 'y';

      for (int i = 0; i < polygon.points.length; i++) {
        if (i == 0) {
          path.moveTo(polygon.points[i].dx, polygon.points[i].dy);
          borderPath.moveTo(polygon.points[i].dx, polygon.points[i].dy);
        } else {
          path.lineTo(polygon.points[i].dx, polygon.points[i].dy);
          borderPath.lineTo(polygon.points[i].dx, polygon.points[i].dy);
        }
`

**Comment by dam-ease** [comment]
Thanks for your response @patansako.
Please can you modify the code into a single `main.dart` file that can be run at once to reproduce the issue?

**Comment by patansako** [comment]
Thanks for your response @dam-ease 
[asdtest.txt](https://github.com/flutter/flutter/files/14108664/asdtest.txt)

**Comment by dam-ease** [comment]
Thanks for sharing this @patansako.
`permission_handler` and `flutter_colorpicker` are third-party packages, please can you take out these to be left with the least possible code required to reproduce this.
I ran this on my end and can see the polygon shifted to the extreme left even when the polygon draw is done at the center before image gets saved. Does this occur on your end as well or the changes in position only occurs when image is saved?

**Comment by patansako** [comment]
thank you for helping @dam-ease 
I'm really sorry to send you the updated code , in the first scenario i had only scaled image  which caused the drawn polygon to appear normal. However, when I saved the image, it didn't match the scale of the original image, resulting in the polygon being size and  positioned incorrectly. In this updated code i had scaled both that's why polygon being positioned incorrect .
[asdtest.txt](https://github.com/flutter/flutter/files/14122033/asdtest.txt)

`final scaleX = size.width / _image.width;
 final scaleY = size.height / _image.height;
 for (final polygon in polygons) {
    final scaledPolygon = polygon.points.map((point) {
  return Offset(point.dx *scaleX*4.1,point.dy*scaleY*4.7);
}).toList();
`
If scaleX and scaleY of polygon  multiple by number like above ,both in canvas and when save it looks normal but with the different image size it didn't work well..

` ( flutter doctor -v):
[√] Flutter (Channel beta, 3.17.0-0.0.pre, on Microsoft Windows [Version 10.0.19045.3930], locale ja-JP)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.85.2)
[√] Connected device (4 available)
[√] Network resources`

i have removed permission_handler and flutter_colorpicker  third-party packages 
[asdtest.txt](https://github.com/flutter/flutter/files/14122057/asdtest.txt)

**Comment by dam-ease** [comment]
Thanks for your response @patansako.
Running this, I have the behaviour below:

https://github.com/flutter/flutter/assets/53122008/ecee2995-7c80-48ef-a30e-4b7ba423b1df

Is the issue you are referencing with the change in this positioning?

**Comment by patansako** [comment]
thank you for helping @dam-ease sorry i can't play your video ...

**Comment by dam-ease** [comment]
Hello @patansako.
Sharing the video here:


https://github.com/flutter/flutter/assets/53122008/1bafe7c5-ce5d-43e5-bc96-da301459741f

Is the issue you are referencing with the change in this positioning?

**Comment by patansako** [comment]
sorry for late reply.. thank you for helping @dam-ease,
 `(point.dx *scaleX*4.1,point.dy*scaleY*4.7);` Yes, I also have the same issue. By adjusting the number, it comes to the right place. However, if I try to debug on any other device, I have to adjust the number again.

**Comment by dam-ease** [comment]
Thanks for your response @patansako.
This might be an issue with your code when calling with respect to the device size/dimension.
You might want to try out using `MediaQuery`, also, it seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this doesn't seem to be an issue with flutter itself.
If you disagree, please comment with reasons and I'll reopen this.
Thank you!
