### ISSUE TITLE
Flutter Web: Scrolling doesn't work

### ISSUE THREAD

**Issue by xinoxapps** [flutter/flutter#142529]
### Steps to reproduce

1. Open DartPad from gist: https://dartpad.dev/?id=f50e1aed6f222ab54f9a94bc2d504cda
2. Run
3. Adjust screen size so that the content becomes scrollable.

On Windows 11 Home, Using Chrome.
Scrolling by dragging doesn't work. Only by scroll wheel or dragging the bars.

On MacOs, Using Chrome.
Scrolling works by dragging. No issues.

### Expected results

Scrolling content by dragging.

### Actual results

No scrolling

### Code sample

<summary>Code sample</summary>

https://dartpad.dev/?id=f50e1aed6f222ab54f9a94bc2d504cda

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Not relevant

### Flutter Doctor output

Not relevant

**Comment by Marco4763** [comment]
You can solve this by adding a **scrollBehavior** that recognize the mouse as drag by gesture device in your MaterialApp, like this:
```
return MaterialApp(
      scrollBehavior: const MaterialScrollBehavior().copyWith(
        dragDevices: {
          PointerDeviceKind.mouse,
          PointerDeviceKind.touch,
          PointerDeviceKind.stylus,
          PointerDeviceKind.unknown,
        },
      ),
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
```

**Comment by danagbemava-nc** [comment]
Hi @xinoxapps, @Marco4763  is right. You need to configure the scrollBehavior. See https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag

Closing from here as a solution has been provided. If you still face this issue after applying the scrollBehaviour, kindly leave a comment below and I will reopen this. 

Thank you

**Comment by xinoxapps** [comment]
So basically.

Flutter Web Windows, doesn't work, unless you add a scroll fix yourself.

Please open the issue again and fix it properly in the sdk.

**Comment by Marco4763** [comment]
@xinoxapps from what we can see in the [dragDevices property](https://api.flutter.dev/flutter/widgets/ScrollBehavior/dragDevices.html) information, the mouse is not set to **dragDevice** by default because mouse dragging makes difficult to select text in a scrollable widget. That's why in the link above mentioned by @danagbemava-nc we explain more about this and at the end of the documentation we can see issue #71322 and PR #81569 which end up making it optional for the dev to add the mouse as a **dragDevice** and handler the effects secondary.

**Comment by xinoxapps** [comment]
Hi Marco,

It is clear, but regardless you still have a very serious bug which needs to be addressed.

**The flutter web-app is not working as the user expects on a Windows machine.**

The workaround has a side-effect that text selection is messed up.  (needs to be addressed)

And if the user is working via Virtual Desktop Interface then it is still not possible to scroll. (needs to be addressed)
