### ISSUE TITLE
Allow building a web app under WSL from Windows

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#142619]
### Use case

I want to test and tune my CI scripts from Windows. I installed the Flutter SDK on Windows and referenced the flutter-sdk/bin directory on WSL. So that I can run the flutter command without installing the flutter SDK twice on the same system.

### Proposal

By side setting the PATH variable I installed dart a second time on WSL. When I run in this setup:
```diff
$ flutter build web
Target dart2js failed: ProcessException: Process exited abnormally:
Snapshot not compatible with the current VM configuration: the snapshot requires
-'release no-code_comments no-dwarf_stack_traces_mode lazy_dispatchers no-dedup_instructions no-tsan no-asserts use_field_guards use_osr no-branch_coverage x64 windows no-compressed-pointers null-safety' but the VM has
+'release no-code_comments no-dwarf_stack_traces_mode lazy_dispatchers no-dedup_instructions no-tsan no-asserts use_field_guards use_osr no-branch_coverage x64 linux no-compressed-pointers null-safety'
  Command: /mnt/c/dev/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /mnt/c/dev/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/mnt/c/dev/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812/ --native-null-assertions --no-source-maps -o /mnt/c/dev/my-test-project/example/.dart_tool/flutter_build/7d8fbe4d2db82a2a0d507a395b75f3fe/app.dill --packages=.dart_tool/package_config.json --cfe-only
  /mnt/c/dev/my-test-project/example/.dart_tool/flutter_build/7d8fbe4d2db82a2a0d507a395b75f3fe/main.dart
```

I got that error above, I just changed the line breaks to better see the differences. I'm curious why the Windows vs Linux capability matters in this case.

Out of my view this is not relevant. I also noted that a `flutter pub get` breaks somehow the "cache" for Windows where I need to run `flutter pub get` again to work in Android Studio

**Comment by eliasyishak** [comment]
From discussions with @christopherfujino on discord

The errors that are coming up are due to the operating system mismatches. You downloaded Windows specific binaries but use WSL so dart thinks it is running in a Linux operating system. The best thing we think we can do is catch this error by caching your operating system in the `path/to/flutter/bin/cache/flutter.version.json` file and ensuring upstream that your current operating system matches what is in that file.

**Comment by eliasyishak** [comment]
I don't believe this to be the best solution for this problem. As we discussed on the discord, I think the best way for us to solve this issue and raise an error to the user is to have a check that happens within dart code that checks the current platform against a cached value that indicates what platform the binaries are intended for.

So if we have windows binaries downloaded on the machine and we detect we are running on Linux within dart code, we should be raising the error there as opposed to redirecting within the bash script.

**Comment by andrewkolos** [comment]
Thanks for contributing this issue. Unfortunately, I don't believe supporting these kind of environments is clearly worth the maintenance burden it could impose upon the tool. See https://github.com/flutter/flutter/issues/146526.
