### ISSUE TITLE
How to set 'writting-mode' for text?

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#14262]
There is some properties in Html ,like below: 
/* Keyword values */
writing-mode: horizontal-tb;
writing-mode: vertical-rl;
writing-mode: vertical-lr;

/* Global values */
writing-mode: inherit;
writing-mode: initial;
writing-mode: unset;

<img width="179" alt="2018-01-25 12 38 59" src="https://user-images.githubusercontent.com/13853/35375402-d8dae17a-01e1-11e8-8551-15415a853285.png">
<img width="394" alt="2018-01-25 12 38 47" src="https://user-images.githubusercontent.com/13853/35375415-df7423a2-01e1-11e8-9a1a-72c9383674d4.png">

Does Flutter support i?

**Comment by Hixie** [comment]
We don't support vertical text. For horizontal text we support ltr and rtl. We do support rotating text, for what that's worth.

We do not intend to add vertical text support.

**Comment by 1l0** [comment]
I had hoped that one day this will be supported. But your comment deprived me of the hope completely.

**Comment by Hixie** [comment]
I apologize for dashing your hopes so thoroughly. This was an early design decision. Properly supporting vertical text requires a significantly more elaborate architecture from the beginning and we concluded that the additional cost to the project was too high.

**Comment by realcarlos** [comment]
In China and Japan , people like vertical text reading app ,so please consider the huge market and potential user.

**Comment by Hixie** [comment]
I'm going to close this issue because as discussed above, this was an early decision that informed the entire architecture. It would be very non-trivial for us to switch to a mode where we support both horizontal and vertical text.

**Comment by CrazyCoderShi** [comment]
@realcarlos 
[try this](https://github.com/flutter/flutter/issues/15710#issuecomment-449887329)

**Comment by suragch** [comment]
I realize this isn't going to get implemented in the Flutter engine, but to document that the functionality is also needed for Mongolian I will paste an image:

<img width="351" alt="mongolian" src="https://user-images.githubusercontent.com/10300220/60469996-98993580-9c13-11e9-886d-b2944f9bb4bc.png">

The bottom view (shown in [Android](https://github.com/suragch/mongol-library)) is how Mongolian script should be laid out. Top-to-bottom, left-to-right line wraps, ideographs and emoji maintain same orientation as horizontal script.

Test string:
```
ᠨᠢᠭᠡ ᠬᠣᠶᠠᠷ ᠭᠣᠷᠪᠠ ᠳᠥᠷᠪᠡ ᠲᠠᠪᠤ ᠵᠢᠷᠭᠤᠭ᠎ᠠ ᠳᠣᠯᠣᠭ᠎ᠠ ᠨᠠ‍ᠢᠮᠠ ᠶᠢᠰᠦ ᠠᠷᠪᠠ one two three four five six seven eight nine ten 😃🐐汉字 한국어 モンゴル語 English? ᠮᠣᠩᠭᠣᠯ︖
```

**Comment by rrousselGit** [comment]
`RotatedBox` is enough for sideway texts as said by @hixie on a duplicate issue.

And now that we have inline widgets support for texts, the smiley case is supported too:

```dart
RotatedBox(
  quarterTurns: 1,
  child: RichText(
    text: TextSpan(
      text: 'Hello World',
      style: DefaultTextStyle.of(context).style,
      children: [
        WidgetSpan(
          child: RotatedBox(quarterTurns: -1, child: Text('😃')),
        )
      ],
    ),
  ),
),
```

![image](https://user-images.githubusercontent.com/20165741/60499817-7b1ea700-9cb9-11e9-907b-d60b4b250ca7.png)
