### ISSUE TITLE
[RFW] Update  the initial state of remote widget with data model.

### ISSUE THREAD

**Issue by peixinli** [flutter/flutter#142647]
### Use case

We should support set the remote widget initial state with data model. 

### Proposal

For example:
```
widget Screens { selectedScreen: data.screen.foo } = Screen(
  screenInfo: state.selectedScreen,
  onNext: set state.selectedScreen = data.screen.bar
)
```
Right now it doesn't seem to work.

**Comment by tugorez** [comment]
QQ: Does the shared example compile?

**Comment by peixinli** [comment]
> QQ: Does the shared example compile?
No I think the rfw only support init state with rfw primitive types directly.

**Comment by Hixie** [comment]
@peixinli Are you working on this one?

**Comment by peixinli** [comment]
> @peixinli Are you working on this one?

Not yet:).
