### ISSUE TITLE
Step 8.1 missing code

### ISSUE THREAD

**Issue by tiborrr** [flutter/flutter#14266]
Make the Send button context-aware step in 8 of the Building Beautiful UIs with Flutter is missing a line of code.
The message list is missing, see code:

`class ChatScreenState extends State<ChatScreen> with TickerProviderStateMixin {`
`  final TextEditingController _textController = new TextEditingController();`
`  bool _isComposing = false; `

should be:

`class ChatScreenState extends State<ChatScreen> with TickerProviderStateMixin {`
`  final TextEditingController _textController = new TextEditingController();`
`  final List<ChatMessage> _messages = <ChatMessage>[];`
`  bool _isComposing = false; `

**Comment by Hixie** [comment]
I have forwarded this feedback to the codelab maintainer. Leaving this bug open until it's resolved in the published codelab. Thanks for the feedback!

**Comment by Sfshaza** [comment]
Thanks so much, @tiborrr, for reporting that bug! Thanks for adding that line, @Hixie!
Fixed.
