### ISSUE TITLE
PlatformDispatcher.displays appears to be reporting logical screen sizes on MacOS

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#142629]
`Display.size`'s [documentation](https://main-api.flutter.dev/flutter/dart-ui/Display/size.html) says (emphasize mine):

> The **physical** size of this display.

When I access this on my MacOS system, the reported value appears to be in **logical** pixels, though:

```
Display.size: Size(2560.0, 1440.0)
Display.devicePixelRatio: 2.0
RenderView in full screen:
RenderView#09fb4
 │ debug mode enabled - macos
 │ view size: Size(5120.0, 2880.0) (in physical pixels)
 │ device pixel ratio: 2.0 (physical pixels per logical pixel)
 │ configuration: BoxConstraints(w=2560.0, h=1440.0) at 2.0x (in logical pixels)
```

**Comment by goderbauer** [comment]
cc @dnfield since you implemented this in https://github.com/flutter/engine/pull/41998: I assume, the docs are correct (since dart:ui typically deals in physical pixels) and the implementation is buggy? Looks like it may be missing a conversion from the logical size obtained from the platform to physical pixels?

cc @dkwingsmt

**Comment by dnfield** [comment]
I assumed that https://developer.apple.com/documentation/appkit/nsscreen/1388387-frame?language=objc returned things in physical pixels, but it looks like it does so in logical pixels. I can't seem to find anything on `NSScreen` to get physical pixels, but we can calculate it.
