### ISSUE TITLE
Add custom color scheme picker to the Material Design 3 sample website

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#142698]
### Use case

The Material Design 3 sample [website](https://flutter.github.io/samples/web/material_3_demo/) shows how Flutter components change their theme's when a main color changes. It would be very useful for designers to be able to simulate their apps' own color palettes in the website, and see how the app would look like with all those MD3 widgets.

### Proposal

Allow the website to accept a custom color scheme.

**Comment by QuncCccccc** [comment]
Hi! Thanks for filing this issue. I'm going to work on this once new ColorScheme roles are added(#138521).

This is duplicate issue. We can track this one https://github.com/flutter/flutter/issues/138274

**Comment by feinstein** [comment]
Amazing, thank you!
