### ISSUE TITLE
`flutter run` could offer to open the simulator for you?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14261]
Suggestion from @paulcbetts in https://twitter.com/paulcbetts/status/955887325019455488

https://github.com/flutter/flutter/blob/159db5ca442f9891a24f2a4273e2fad0884b1d2a/packages/flutter_tools/lib/src/commands/run.dart#L185

is the code in question.

**Comment by iapicca** [comment]
Hi @eseidelGoogle is this issue still meant to be open?

**Comment by anaisbetts** [comment]
But like, what if you just did it for them?
