### ISSUE TITLE
Make Vulkan validation layers opt-in with a flag in debug builds at the end of the preview period.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#142659]
The performance impact of Vulkan validation layers can be quite high. To avoid impacts to developer workflows, the validation layers should be opt-in when the Impeller/Vulkan on Android preview period ends.

cc @jonahwilliams

**Comment by gaaclarke** [comment]
We should have a PR queued up.  There is some benefit from delaying landing it until we're ready.
