### ISSUE TITLE
App turn into totally black all of a sudden on iPhone X, iOS11

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#14265]
## Steps to Reproduce

It seems difficult to reproduce.
It should be happened when waked up from the background to foreground.

![1](https://user-images.githubusercontent.com/817851/35386104-c1fb8bd4-0205-11e8-9cba-ec3bd5fd100c.png)
![2](https://user-images.githubusercontent.com/817851/35386105-c23e21ce-0205-11e8-8237-26b79cc54696.png)

The ipa is built with flutter on master branch  and the problem occurs in an ad-hoc distribution running on a iPhoneX.

**Comment by eseidelGoogle** [comment]
Odd.  Wonder if this is fallout from a Skia change or some refactor from @chinmaygarde?

@cbracken might know.

**Comment by eseidelGoogle** [comment]
My understanding from reading your text @kangwang1988 is that this happens on physical devices (not simulators)?

Could you paste the `flutter version` information?  (We can also test locally today.)

**Comment by cbracken** [comment]
@chinmaygarde's refactoring hasn't landed yet. Question -- does this happen only when you foreground (or start) the app, then continue execution?

**Comment by kangwang1988** [comment]
@eseidel  It happens on a real iPhoneX device.
The flutter version output is given below:
flutter --version
Flutter 0.0.21-pre.294 • channel master • git@github.com:flutter/flutter.git
Framework • revision 8059aea365 (7 days ago) • 2018-01-22 18:12:39 -0800
Engine • revision 171d032f86
Tools • Dart 2.0.0-dev.16.0

**Comment by kangwang1988** [comment]
@cbracken It's reported by my colleague and it's said that it happens when awaking from the background.

**Comment by najeira** [comment]
I have a same problem.

This occurs rarely when returning from a native screen such as ImagePicker.

alpha 0.0.20

**Comment by xster** [comment]
Likely #14228 and fixed upstream. 

Please re-open if it's still reproducible on the latest build.
