### ISSUE TITLE
Can Tween have a const constructor?

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#1426]
`Animatable<>` has a const constructor, so can we do the same for `Tween`?

**Comment by Hixie** [comment]
Tween isn't immutable -- you can dynamically change the begin and end points.

**Comment by abarth** [comment]
Yeah, there's a trade-off: we can give you a const constructor but then we need to make Tweens immutable.  We can look through the code we have to see how it uses mutability.  I think we use it quite a bit to reconfigure Animation objects that we've already given to someone else.

**Comment by Hixie** [comment]
Yeah, I was just looking. There aren't that many callers, but e.g. timePicker creates a tween, uses it to make an Animation, and then later tweaks it.

**Comment by Hixie** [comment]
We could have a ConstTween class that implements Animatable and isn't mutable.

**Comment by jimbeveridge** [comment]
Thanks for the background - I wasn't aware of that use case. Sounds like the cognitive complexity to make the change work isn't worth the gain.

**Comment by Hixie** [comment]
If we want it, it's not particularly hard: https://github.com/flutter/flutter/pull/1427 (ConstTween)

I could also look at changing the callers so that they don't mutate Tween. There aren't many.

**Comment by jimbeveridge** [comment]
I retract my request. In my newer code, most of my Tweens end up being mutated.
