### ISSUE TITLE
More old gen GCs following mark through new space

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#142687]
On the engine roll here https://github.com/flutter/flutter/commit/db828a8351dc0057d0a9b0682ccf6094e9ead6c8

Containing the Dart roll https://github.com/flutter/engine/commit/8a4aa8e7ef7a8894952e5b347e397eac8b071116

Which contained the mark through new space change https://dart.googlesource.com/sdk.git/+/4e6cd29eef8fc604721dad422ededa2ad98b9925

SkiaPerf recorded additional old gen gcs, slightly increased hot reload time, and in once double the amount of time spent in gc across the whole benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1705447828&end=1706757785&keys=Xbf6a2bff761684258798c56d5695008c&requestType=0&selected=commit%3D39031%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253DhotReloadVMReloadMillisecondsAfterChange%252Ctest%253Dhot_mode_dev_cycle_macos_target__benchmark%252C&xbaroffset=39031

cc @rmacnak-google @a-siva

**Comment by rmacnak-google** [comment]
Where does the Flutter benchmark harness save the timeline?

The benchmark seems to make a change to a constant in dev/integration_tests/flutter_gallery. If I manually hot reload that change and look at the timeline, the only significant difference I see is that there is now an idle compaction running after the post-reload frame. If this is also what happens under the benchmark harness, it is not interesting.

**Comment by zanderso** [comment]
It looks like CI is not saving the full timeline https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_ios%20hot_mode_dev_cycle_ios__benchmark/251/overview.

@christopherfujino Do you know if the hot reload benchmarks do save the timelines, and I'm just not finding the link?

**Comment by jonahwilliams** [comment]
This test is essentially instrumenting the flutter tool and is not attached directly to the timeline, so you won't be able to get timeline data unless you modify the test.

**Comment by jonahwilliams** [comment]
Absent any other unknown regressions, this change seems fine - though it seemingly did not improve any of our benchmarks and that itself might entail some investigation from the Dart team.
