### ISSUE TITLE
ERROR PUB

### ISSUE THREAD

**Issue by Ralle001** [flutter/flutter#14267]
D:\git\flutter>flutter doctor
Updating flutter tool...
The system can't find the route.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

**Comment by cbracken** [comment]
Thanks for reporting! Can you try running `flutter doctor --verbose` and paste the log here?

**Comment by zoechi** [comment]
dup of #15014  ?

**Comment by zoechi** [comment]
Duplicate of #15014

**Comment by emmanuelJet** [comment]
https://pub.dartlang.org/ refuse to open. It has been saying "This site can’t be reached"
