### ISSUE TITLE
RuntimeType function is not the same in the emulator Web as it is on the public server

### ISSUE THREAD

**Issue by JoeBlack92** [flutter/flutter#142729]
### Steps to reproduce

Calling the .runtimeType of a variable `"List"` or `"List<String>",` if you print it in the console locally versus on a public server, the same type does not appear.

### Expected results

I was expecting the console output to be the same in both the local emulator and the server.

### Actual results

![Bug RuntimeType](https://github.com/flutter/flutter/assets/12937000/a62a0ec9-f143-4914-9f98-f8bdeb035a4b)

### Code sample

// Testing the browser inspector console on the web emulator and on the public server.

```
List variable = [];
List<String> variable2 = [];

print("TYPE (List):  ${variable.runtimeType}");
print("TYPE (List<String>): ${variable2.runtimeType}");
```

### Screenshots or Video

![Bug RuntimeType](https://github.com/flutter/flutter/assets/12937000/edb83928-ccb9-46d7-91d6-e80de8c8e1fe)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Versi¢n 10.0.22631.3007], locale es-ES)
    • Flutter version 3.13.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (4 months ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\msanc\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = C:\Users\msanc\AppData\Local\Android\Sdk
    • Java binary at: C:/Program Files/Android/Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.20)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32929.386
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Android Studio (version 2021.2)
    • Android Studio at C:/Program Files/Android/Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:/Program Files/Android/Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\msanc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] VS Code, 64-bit edition (version 1.65.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Versi¢n 10.0.22631.3007]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 121.0.6167.86
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 121.0.2277.83

</details>

**Comment by darshankawar** [comment]
@JoeBlack92 
I think this issue belongs to dart-lang repo so you need to report it there. https://github.com/dart-lang/sdk/issues
Closing from here.
