### ISSUE TITLE
Issues installing Android SDK command-only tools for flutter: Flutter requires Android SDK 29 and the Android BuildTools 28.0.3 (My version is 25.0.2)

### ISSUE THREAD

**Issue by erion043** [flutter/flutter#142764]
### Steps to reproduce

Im trying to use the command-only tools (I do not want Android Studio) and even after updating with "sdkmanager" my sdk is still too outdated for flutter.

### Actual results

1. Firstly, I try "~/Apps/android_sdk/cmdline-tools/latest/bin $ ./sdkmanager --update"
    - "No updates available"

2. Then I try  "~/Apps/android_sdk/tools/bin $ ./sdkmanager --update"
    -"Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
      at ..."

3. "$flutter doctor" gives -
    - [!] Android toolchain - develop for Android devices (Android SDK version 25.0.2)
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed                                       instructions.

### Logs

<details open>
<summary>Logs</summary>

```console
//OUTPUT FROM RUNNING STEP 2//

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console


[✓] Flutter (Channel stable, 3.16.9, on Arch Linux 6.7.2-arch1-2, locale en_US.UTF-8)
    • Flutter version 3.16.9 on channel stable at /home/erion/Apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (7 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 25.0.2)
    • Android SDK at /home/erion/Apps/android_sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.28.2
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.7.2-arch1-2
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
@erion043 
You are probably hitting https://github.com/flutter/flutter/issues/91960 that you can check and confirm.
It has SO link that you can go through and see if it helps to resolve the issue or not.

Also check [this](https://github.com/flutter/flutter/issues/62924#issuecomment-668904152) and see if it helps or not.

**Comment by erion043** [comment]
> @erion043 
> 
> You are probably hitting https://github.com/flutter/flutter/issues/91960 that you can check and confirm.
> 
> It has SO link that you can go through and see if it helps to resolve the issue or not.
> 
> 
> 
> Also check [this](https://github.com/flutter/flutter/issues/62924#issuecomment-668904152) and see if it helps or not.
> 
> 

I installed Android Studio. Google said on the installation guide that android studio is required for dealing with the android SDK.

"Note: Flutter relies on a full installation of Android Studio to supply its Android platform dependencies. However, you can write your Flutter apps in a number of editors; a later step discusses that."
https://docs.flutter.dev/get-started/install/linux
