### ISSUE TITLE
TextFormField with `TextInputType.streetAddress` removes new lines when focus with tab key

### ISSUE THREAD

**Issue by ThHareau** [flutter/flutter#142727]
### Steps to reproduce

1. Create a form with two `TextFormField`. The second must have `keyboardType: TextInputType.streetAddress` and a multiline initial value.
2. From flutter web, click on the first `TextFormField`. 
3. Press <kbd>Tab</kbd>.

The second `TextFormField` should now be focused. **Any new lines are removed from the second field.**

### Expected results

The second field is focused and its content is not modified. 

### Actual results

The second field is focused but every new lines are removed. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            TextFormField(
              initialValue: 'Press tab from this field',
            ),
            TextFormField(
              initialValue:
                  'The new line between here\nand here will be removed\n',
              keyboardType: TextInputType.streetAddress,
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

This is fully reproducible on DartPad using the master flutter channel. 

```console
[✓] Flutter (Channel stable, 3.16.8, on Fedora Linux 39 (Workstation Edition)
    6.6.13-200.fc39.x86_64, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by ThHareau** [comment]
This is probably linked to https://github.com/flutter/flutter/issues/93373, even though this is not exactly the same issue

**Comment by darshankawar** [comment]
Thanks for the report @ThHareau 
The root-cause seems to be explained in https://github.com/flutter/flutter/issues/93373#issuecomment-993841954.

See https://github.com/flutter/engine/blob/50ccb0fffb1ccad43c0ea283250639ee4e04ef73/lib/web_ui/lib/src/engine/text_editing/input_type.dart#L9-L36

which doesn't have `streeAddess` as an input type and hence you are most probably seeing the behavior.
Check the same and I think once the linked issue is fixed, this issue will be resolved as well, so you may follow-up in it for further updates.
