### ISSUE TITLE
App crashes in ios 17.0 devices only

### ISSUE THREAD

**Issue by JithinPOmanakuttan** [flutter/flutter#142789]
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString containsObject:]: unrecognized selector sent to instance 0x8aa79aec91e52c30'
*** First throw call stack:
(0x1b647e69c 0x1ae78fc80 0x1b650efdc 0x1b63c3e08 0x1b6504950 0x1d2b6fd44 0x105966b34 0x105968690 0x1d2b2cbc0 0x1d2b6e344 0x105966b34 0x105968690 0x1d2b1e150 0x1d2b8f124 0x1d2b10830 0x1d2b10260 0x1d2b100a8 0x1d2b0ffec 0x104c3119c 0x104c30f60 0x105964f50 0x105966b34 0x10596e98c 0x10596f728 0x10597c5f8 0x10597bc2c 0x22028b964 0x22028ba04)
libc++abi: terminating due to uncaught exception of type NSException
```

**Comment by dam-ease** [comment]
Hello @JithinPOmanakuttan.
Please can you provide more information on this issue?

- Does this happen with a newly created flutter project or an existing one?
- Please provide other information as well as indicated in the issue template such as a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), the output of `flutter doctor -v` and reproduction steps

Thank you!

**Comment by JithinPOmanakuttan** [comment]
Hi @dam-ease ,
It happened with an existing flutter project 
and working fine in a newly created flutter project
