### ISSUE TITLE
gen_defaults_test.dart is non-hermetic

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#142716]
The daily random test shuffling seed caused some tests to fail:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20framework_tests_misc/77/overview
```
00:00 +4 -1: Tokens logger color function logs when not providing a default [E]                                                                                                                        
  Expected: contains '\x1B[31mSome referenced tokens do not exist: 1\x1B[0m'
    Actual: [
              '',
              'Tokens used: 0/0',
              '',
              '\x1B[31mSome referenced tokens do not exist: 7\x1B[0m',
              '  foo',
              '  bar',
              '  foo.shape',
              '  shape.large',
              '  bar.shape',
              '  shape.full',
              '  color_foo_req'
            ]
     Which: does not contain '\x1B[31mSome referenced tokens do not exist: 1\x1B[0m'
  
  package:matcher                     expect
  test/gen_defaults_test.dart 355:7   main.<fn>.<fn>
  dart:async                          _CustomZone.run
  test/gen_defaults_test.dart 253:53  main.<fn>.overridePrint.<fn>
  

To run this test again: /Volumes/Work/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test /Volumes/Work/s/w/ir/x/w/flutter/dev/tools/gen_defaults/test/gen_defaults_test.dart -p vm --plain-name 'Tokens logger color function logs when not providing a default'
```

cc @davidmartos96  @guidezpl @goderbauer

**Comment by zanderso** [comment]
I haven't dug into this deeply (hoping an expert can do that), but this global getting used across tests is very suspicious:

https://github.com/flutter/flutter/blob/master/dev/tools/gen_defaults/lib/token_logger.dart#L8

**Comment by zanderso** [comment]
Adding no-shuffle in the test file didn't work. https://github.com/flutter/flutter/pull/142721 will disable it in the test driver.

**Comment by goderbauer** [comment]
@QuncCccccc Can you take a look at why the tests for the material token generator are failing with today's seed? I think to reproduce you want to locally revert the two PRs (https://github.com/flutter/flutter/pull/142717 and https://github.com/flutter/flutter/pull/142721) and then run the tests in `dev/tools/gen_defaults` with `flutter test --test-randomize-ordering-seed=20240201`.

(I am going to take a look at the likely unrelated issue with with `widget_tester_test.dart` mentioned in https://github.com/flutter/flutter/pull/142721)

**Comment by QuncCccccc** [comment]
Taking a look!

**Comment by QuncCccccc** [comment]
@davidmartos96 just provided a fix: https://github.com/flutter/flutter/pull/142743!
