### ISSUE TITLE
video player not working in android get the video from file and show that error.VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/mp4v-es, null, 707854, null, [320, 410, 25.0], [-1, -1]), format_supported=YES, null, null

### ISSUE THREAD

**Issue by Talha137m** [flutter/flutter#142728]
### Steps to reproduce

![error](https://github.com/flutter/flutter/assets/99283895/8fed7a34-8bdb-4aee-bf1e-f89f6b9d964c)

### Expected results

working properply 

### Actual results

VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/mp4v-es, null, 707854, null, [320, 410, 25.0], [-1, -1]), format_supported=YES, null, null

### Code sample

<details open><summary>Code sample</summary>

```dart
      videoPlayerController = VideoPlayerController.file(File(path))
        ..initialize();
      await videoPlayerController.seekTo(videoPlayerController.value.duration);
      state =
          ThumbNailLoadedState(videoPlayerController: videoPlayerController);```

</details>


### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![error](https://github.com/flutter/flutter/assets/99283895/3daba49c-5aae-4679-88ad-f2f2d802a637)


### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.4, on Ubuntu 22.04.3 LTS 6.5.0-15-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by zeeshan-rsys** [comment]
hi all, 
same issue i am facing, here is the scenario 
For every first time launch video is working fine for about 2,3 min after that getting this error i have already updated package version also 


`video_player: ^2.8.2
  chewie: ^1.7.4
`


<img width="1053" alt="Screenshot 2024-02-04 at 1 37 33 AM" src="https://github.com/flutter/flutter/assets/101088061/bb8a8abb-256e-4aae-bf5b-b5a34f580bbf">




```
 Observer(builder: (context) {
                          return DefaultPlayer(
                            data: path,
                            videoPlayerController: path.startsWith("http")
                                ? VideoPlayerController.networkUrl(
                                    Uri.parse(path),
                                    formatHint: VideoFormat.other,
                                  )
                                : VideoPlayerController.file(
                                    File(path),
                                  ),
                          );
                        });
```






`Widget build(BuildContext context) {
    final theme = AppTheme.of(context);

    return Chewie(
      controller: ChewieController(
        autoPlay: false,
        autoInitialize: true,
        allowMuting: true,
        allowFullScreen: true,
        draggableProgressBar: true,
        looping: false,
        errorBuilder: (_, msg) {
          return Center(
              child: Text(
            "${msg}",
            style: theme.textStyle.body.regular.copyWith(color: AppColor.error),
          ));
        },
        cupertinoProgressColors:
            ChewieProgressColors(bufferedColor: AppColor.primary),
        showOptions: false,
        videoPlayerController: widget.videoPlayerController,
      ),
    );`

**Comment by zeeshan-rsys** [comment]
> Thanks for your input @zeeshan-rsys. I see you are making use of the `chewie` package as well, this might be similar or related to #81804. Can you check this out as well?

i have also added `implementation ('com.google.android.exoplayer:exoplayer:2.19.1')` but still getting same issue
