### ISSUE TITLE
@darshankawar Yes, it has no problem accounting for longer text in the content rows, but longer text in the header row overflows.

### ISSUE THREAD

**Issue by sohrabonline** [flutter/flutter#142706]
@darshankawar Yes, it has no problem accounting for longer text in the content rows, but longer text in the header row overflows.

I'm pretty new to flutter, but I looked at the code and there doesn't appear to be anything looking at the cell widgets you send in to get length in data_table.dart.  The DataTable widget also sends both header and table rows in one bucket to the Table widget, so it's probably not up there.  The places where I see differences are in data_table.dart, where for both header and data rows it puts the label in a container but then wraps it in either `DefaultTextStyle` or `AnimatedDefaultTextStyle`.

Header cell is done like this:

```
      child: AnimatedDefaultTextStyle(
        style: effectiveHeadingTextStyle,
        softWrap: false,
        duration: _sortArrowAnimationDuration,
        child: label,
      ),
```

Data cell is done like:

```
      child: DefaultTextStyle(
        style: effectiveDataTextStyle.copyWith(
          color: placeholder
              ? effectiveDataTextStyle.color!.withOpacity(0.6)
              : null,
        ),
        child: DropdownButtonHideUnderline(child: label),
      ), 
```

So looks like it could be the *TextStyle wrapper, `softwrap: false`, or `DropdownButtonHideUnderline` wrapper.  Or something entirely different that a newbie like myself doesn't see :-)

Thanks for looking at this.

_Originally posted by @jpangburn in https://github.com/flutter/flutter/issues/100633#issuecomment-1077875784_

**Comment by sohrabonline** [comment]
**BEFORE**
![Screenshot 2024-02-01 at 18 19 55](https://github.com/flutter/flutter/assets/63860581/2931a1cc-6679-4eff-9552-55461bba39e7)


**AFTER**
![Screenshot 2024-02-01 at 18 20 08](https://github.com/flutter/flutter/assets/63860581/6f3dd16b-9f7b-47f6-95d8-6efc782a2d8c)

**Comment by sohrabonline** [comment]
<img width="684" alt="Screenshot 2024-02-01 at 17 38 36" src="https://github.com/flutter/flutter/assets/63860581/60e13914-b445-442d-8ea4-d2a28003e221">

**Comment by sohrabonline** [comment]
<img width="665" alt="Screenshot 2024-02-01 at 18 21 59" src="https://github.com/flutter/flutter/assets/63860581/e377a5dd-7920-45d1-9c6a-e617b95e792c">

**Comment by sohrabonline** [comment]
`    label = Container(
      padding: padding,
      // height: effectiveHeadingRowHeight,
      alignment:
          numeric ? Alignment.centerRight : AlignmentDirectional.centerStart,
      child: Padding(
        padding: Paddings.paddingV4,
        child: AnimatedDefaultTextStyle(
          style: DefaultTextStyle.of(context)
              .style
              .merge(effectiveHeadingTextStyle),
          softWrap: true,
          duration: _sortArrowAnimationDuration,
          child: Align(alignment: Alignment.topCenter, child: label),
        ),
      ),
    );`

**Comment by darshankawar** [comment]
@sohrabonline 
We recommend not to use comment from other issues to file a new issue, because it doesn't properly help to understand what exactly the issue are you reporting. 
There are [new issue templates](https://github.com/flutter/flutter/issues/new/choose) that you should use, fill out requested details so that we can properly address the issue.

Closing for now.

**Comment by sohrabonline** [comment]
> @sohrabonline We recommend not to use comment from other issues to file a new issue, because it doesn't properly help to understand what exactly the issue are you reporting. There are [new issue templates](https://github.com/flutter/flutter/issues/new/choose) that you should use, fill out requested details so that we can properly address the issue.
> 
> Closing for now.

okay, please analyze issue, and help me send request for solve problem :/
