### ISSUE TITLE
[Impeller] delete `--enable-impeller-vulkan` and `--enable-impeller-opengles`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#142725]
Instead of making these flags that people have to specify when compiling the engine we should make them fixed based on the target platform.

We have hooked up SwiftShader and ANGLE on macOS, the default for macOS builds should include them.

By having multiple build variants, it makes our testing story harder.  For example, someone could be happily running `impeller_unittests` against metal and not realize they broke vulkan.

A less drastic step would just be to change these values to be default on for macOS.

cc @chinmaygarde

**Comment by chinmaygarde** [comment]
Yes! This is super annoying. I think we needed these when the various backends were under construction and in various states of brokenness. But with the playgrounds working with either Molten, SwiftShader, or Angle, I think this is less of an issue.

Flipping the default might be a easy first step to see what breaks but I don't think we should have these flags at all.

**Comment by jonahwilliams** [comment]
Lets remove these flags.

**Comment by jonahwilliams** [comment]
Actually, just a thought: can we do this without linking Vulkan and GLES into macOS desktop builds?

**Comment by matanlurey** [comment]
I attempted this here https://github.com/flutter/engine/pull/50622 - it's not as easy as changing the defaults. The validation error aside, we still try to use Vulkan on MacOS hosts that don't have Vulkan, causing failures.

Unassigning as I have plenty on my plate.

**Comment by jonahwilliams** [comment]
These flags still exist but they default to True now:

https://github.com/flutter/engine/blob/main/tools/gn#L1240-L1252

If nothing is setting them to false, it should be safe to delete
