### ISSUE TITLE
Many Windows tests failing on Infra error

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#142730]
### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

Seems like a bunch of Windows tests are failing on recipes crash on step "upload results". This is blocking tree

```
Uncaught Exception: ValueError('No steps have been run yet, and you are asking for a previous step result.')
```

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_arm64%20flutter_gallery_win_desktop__compile/1484/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_arm64%20flutter_gallery_win_desktop__start_up/1490/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_arm64%20hot_mode_dev_cycle_win_target__benchmark/1484/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20module_test/15908/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20complex_layout_win_desktop__start_up/8888/overview

@keyonghan Perhaps caused by https://flutter.googlesource.com/recipes/+/48ee2c741b7189b18c2a542335bbd124b8166d07?

**Comment by keyonghan** [comment]
The recipes CL has been reverted: https://flutter-review.googlesource.com/c/recipes/+/54701

**Comment by vashworth** [comment]
Looks like that worked. Tree is green again. Closing.
