### ISSUE TITLE
App crashes immediately on simulator or device

### ISSUE THREAD

**Issue by dgaedcke** [flutter/flutter#142786]
### Steps to reproduce

I'm running:
flutter build ios --verbose

and getting the error dump shown below in actual results and I can't make any sense of it ... happy to share my repo or perhaps someone here can tell me what all this means?

### Expected results

I expect the app to run ... but something is seriously crashing without any helpful error messages ..

### Actual results

```
Failed to build iOS app
[   +2 ms] Uncategorized (Xcode): Exited with status code 1

[   +7 ms] Could not build the application for the simulator.
[   +1 ms] Error launching application on iPhone 15 Plus.
[ +683 ms] "flutter run" took 13,413ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:705:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
       <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
``` 

### Code sample

I can share the project repo but have no way to narrow the problem given the amorphous error messages I'm getting (see above)

### Screenshots or Video

see error dump above

### Logs

no logs available

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.86.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for dgiphone. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

**Comment by dam-ease** [comment]
Hello @dgaedcke.
Does this occur with a new project or an existing one?

> ! Error: Browsing on the local area network for dgiphone. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

From this log, are you using a corporate restricted system, I see similar issues relating to this 
https://forums.developer.apple.com/forums/thread/739325
https://forums.developer.apple.com/forums/thread/741537
Can you check them out to resolve the error in flutter doctor to see if this issue still occurs afterwards.

**Comment by Percyyfrost** [comment]
I'm having the same issue
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.6.1 22G313 darwin-x64, locale
    en-ZA)
    • Flutter version 3.10.6 on channel stable at /Users/vuyani/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vuyani/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • E2B01AB3-E8DE-44D8-9099-92B2A3F88AA7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 13.6.1 22G313 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

In my case this issue only occurs with an existing project, and only on an iOS emulator

**Comment by dgaedcke** [comment]
It's an existing project ... 2 years old & recently upgraded to the new Flutter.  I'm not using any kind of corporate restricted network ... not even sure what that is or how that might relate but will read those two links!!  thanks

**Comment by dgaedcke** [comment]
OK ... I figured my XCode config had gotten screwed up somehow and so I used Flutter to regenerate a brand new IOS folder and I went through and reconfigured all that stuff.  And then when I ran XCode->Build (or Run), I see this error below.

My guess is that the flutter tooling has a problem when the Target (Runner) has an embedded extension or plugin ... UNNotificationServiceExtension in this case!!

Thoughts??

XCode output:

Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': ExtractAppIntentsMetadata
○ Target 'Runner' has copy command from '/Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/TsPnImages.appex' to '/Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/TsPnImages.appex'
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/TsPnImages.appex' to '/Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/TsPnImages.appex'


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/ExtractedAppShortcutsMetadata.stringsdata ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ExtractAppIntentsMetadata ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--embed-pods-frameworks> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--embed-pods-frameworks ->

node: /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-611CADF0B7E4FE311909D346-Pods-Runner-frameworks-Debug-input-files-0c1690ce4641c2482b215d674cf222e3-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFileList-611CADF0B7E4FE311909D346-Pods-Runner-frameworks-Debug-input-files-0c1690ce4641c2482b215d674cf222e3-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5-copy-files> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5-copy-files ->

node: <Copy /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/TsPnImages.appex> ->

CYCLE POINT ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/TsPnImages.appex /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/TsPnImages.appex ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

node: <execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->

node: /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist/ ->

directoryTreeSignature: � ->

directoryContents: /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist ->

node: /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/Info.plist /Users/dgaedcke/dev/notify_coordinator/example/ios/Runner/Info.plist ->

node: /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/TsPnImages.appex ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/Runner.app/PlugIns/TsPnImages.appex /Users/dgaedcke/Library/Developer/Xcode/DerivedData/Runner-bbzxrnkugootduccejpnulrizpqm/Build/Products/Debug-iphonesimulator/TsPnImages.appex

**Comment by dgaedcke** [comment]
@Percyyfrost  -- does your project include an IOS plugin / extension?

**Comment by dgaedcke** [comment]
OK ... not sure if this is a Flutter or Xcode problem, but in my case the solution was to move "Thin Binary" down in the build phases!

<img width="369" alt="image" src="https://github.com/flutter/flutter/assets/1172930/0d55d055-27bd-47f8-9a2b-89a92539c936">
