### ISSUE TITLE
Add copyWith feature to Paint

### ISSUE THREAD

**Issue by bramp** [flutter/flutter#142871]
### Use case

When painting to a canvas I find myself reusing very similar Paint object with just one field tweaked. For example, multiple Paints with the same stroke/strokeWidth, but with a different colour. Making a decision to change the strokeWidth could be error prone. For example:

```dart
  final item1Stroke = Paint()
    ..color = Colors.red
    ..style = PaintingStyle.stroke
    ..isAntiAlias = false
    ..strokeWidth = 10;

  final item2Stroke = Paint()
    ..color = Colors.green
    ..style = PaintingStyle.stroke
    ..isAntiAlias = false
    ..strokeWidth = 10;

  final item3Stroke = Paint()
    ..color = Colors.blue
    ..style = PaintingStyle.stroke
    ..isAntiAlias = false
    ..strokeWidth = 10;
```

### Proposal

Instead add a copyWith method, for example:

```dart
  final defaultStroke = Paint()
    ..style = PaintingStyle.stroke
    ..isAntiAlias = false
    ..strokeWidth = 10;

  final item1Fill = defaultStroke.copyWith(
    color: Colors.red
  );
  final item2Fill = defaultStroke.copyWith(
    color: Colors.blue
  );
  final item3Fill = defaultStroke.copyWith(
    color: Colors.green
  );
```

This proposal was filed previously: https://github.com/flutter/flutter/issues/40497 but that issue was closed without explaination, and at that time had 21 thumbs up (if that's any kind of signal).

**Comment by matanlurey** [comment]
I (a) agree with this change and (b) think it might be difficult unless we freeze (`final`) `Paint`.

I'll take this temporarily and discuss with the team.

**Comment by matanlurey** [comment]
So I don't think `copyWith` is the best pattern for two reasons:

1. We have 4 implementations of `Paint` (1 native, 3 web), with very complex semantics.
2. `copyWith` is typically used with immutable objects, `Paint` is mutable.

So I'm proposing instead adding a slightly more idiomatic, and easy to implement `Paint.from`:

```dart
final class Paint {
  Paint.from(Paint other) { /* ... */ }
}
```

It would work essentially the same as above:

```dart
final defaultStroke = Paint()
    ..style = PaintingStyle.stroke
    ..isAntiAlias = false
    ..strokeWidth = 10;
final item1Fill = Paint.from(defaultStroke)
    ..color = Colors.red;
```

I have a prototype PR that admittedly I have not tested to get some feedback.

**Comment by bramp** [comment]
The `Paint.from(other)` pattern works for me and solved my issue if that's the route you end up going. Thanks

**Comment by dnfield** [comment]
I don't think we should do this.

For the trivial example here, it would be inexpensive, but if the paint has any shader objects or mask filters or blend modes, those would also either need to be immutable or have their own copy methods.

We don't typically add convenience methods like this to `dart:ui`. I'd expect to see the example here written as something like

```dart
 Paint createDefaultPaint(Color color) => Paint()
    ..style = PaintingStyle.stroke
    ..isAntiAlias = false
    ..strokeWidth = 10
    ..color = color;

  final item1Fill = createDefaultPaint(Colors.red);
  final item2Fill = defaultStroke.copyWith(Colors.blue);
  final item3Fill = defaultStroke.copyWith(Colors.green);
```

If you're really desparate for this to be a method on `Paint`, you could also implement it as an extension method - but I'd recommend not doing that, because if your `Paint` object has any more complicated objects on it like a `FragmentShader`, what do you expect? Should all the objects share the same `FragmentShader` instance, or should that somehow be copied?

**Comment by matanlurey** [comment]
> For the trivial example here, it would be inexpensive, but if the paint has any shader objects or mask filters or blend modes, those would also either need to be immutable or have their own copy methods.

I did a cursory glance through, and didn't see any shader objects/mask filters/blend modes that were not immutable.

**Comment by Solido** [comment]
Few will understand but at that time I was deeply involved with low level graphics in Flutter and having such verbose and fragile code was a top frustration.
Thank you for reviving and completing this feature!

**Comment by matanlurey** [comment]
> Few will understand but at that time I was deeply involved with low level graphics in Flutter and having such verbose and fragile code was a top frustration. Thank you for reviving and completing this feature!

Well, sorry it took so long - hope you are well and will try graphics in Flutter again :)
