### ISSUE TITLE
[packages] flutter->packages roller is blocked in `web_benchmarks` on tooling changes for wasm

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#142809]
The flutter/flutter->flutter/packages roller is [failing](https://github.com/flutter/packages/pull/6036), on `web_benchmarks` custom tests:

```
03:00 +2: Can run a web benchmark with an alternate initial page                                                                                                                                       
03:00 +2: Can run a web benchmark with wasm                                                                                                                                                            
03:00 +2: Can run a web benchmark with wasm                                                                                                                                                            
Building Flutter web app (renderer: canvaskit, compiler: dart2wasm)...
Build took 0s to complete.
Shell: 
Shell: "--web-renderer" cannot be combined with "--wasm"
Shell: 

03:01 +2 -1: Can run a web benchmark with wasm [E]                                                                                                                                                     
  Exception: Failed to build the benchmark.
  package:web_benchmarks/src/runner.dart 144:7  BenchmarkServer.run
```

The failure is in
https://github.com/flutter/packages/blob/0f677d370a1f2f5c7ad01d8ffa874fb6f881eede/packages/web_benchmarks/tool/run_tests.dart#L43-L51
which runs
https://github.com/flutter/packages/blob/0f677d370a1f2f5c7ad01d8ffa874fb6f881eede/packages/web_benchmarks/testing/web_benchmarks_test.dart#L29-L35

/cc @yjbanov @eyebrowsoffire Some change needs to be made here such that the roller can resume; based on the description of https://github.com/flutter/flutter/pull/141396 it sounds like the test script is no longer valid, but I'm not sure what the expected change is.

**Comment by eyebrowsoffire** [comment]
I'll make some updates to the packages repo to fix this.
