### ISSUE TITLE
flutter provides incorrect help when android studio not found.

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#142879]
### Steps to reproduce

On Ubuntu 23.04 I've installed android studio using snap.

```
 which android-studio
/snap/bin/android-studio
```
I then run:
```
flutter config --android-studio-dir=/snap/bin/android-studio
```
and then
```
flutter doctor
Could not find the Android Studio installation at the manually configured path "/snap/bin/android-studio".

Please verify that the path is correct and update it by running this command: flutter config --android-studio-dir '<path>'
To have flutter search for Android Studio installations automatically, remove
the configured path by running this command: flutter config --android-studio-dir
```

You can see here that I'm told to run `flutter config --android-studio-dir`

The problem is that when I run that command I get the following error:

```flutter config --android-studio-dir
Missing argument for "android-studio-dir".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

So it looks like the given instructions are invalid.

Foot Note: I find it rather frustrating that I need to install android studio when I'm a vs-code user.

### Actual results

detailed above.

The correct message from flutter should be:
```
flutter doctor
Could not find the Android Studio installation at the manually configured path "/snap/bin/android-studio".

Please verify that the path is correct and update it by running this command: flutter config --android-studio-dir '<path>'
To have flutter search for Android Studio installations automatically, remove
the configured path by running this command: flutter config --android-studio-dir=

```

Note the additional '=' on the last line.

### Logs

```
flutter -v config --android-studio-dir
[   +9 ms] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +15 ms] Missing argument for "android-studio-dir".
           
[   +1 ms] Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
[  +10 ms] ensureAnalyticsSent: 0ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 64
```

### Flutter Doctor output

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on Ubuntu 22.04.3 LTS 6.2.0-39-generic, locale en_AU.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by huycozy** [comment]
It seems you set the wrong path. Could you try this one?

```console
flutter config --android-studio-dir="/snap/android-studio/current"
```
