### ISSUE TITLE
Roadmap 2024

### ISSUE THREAD

**Issue by ltOgt** [flutter/flutter#142865]
### Use case

Not sure where to put this, but in the last years around January, it was always nice reading the roadmap for the upcoming year.

Currently it is still showing 2023: https://github.com/flutter/flutter/wiki/Roadmap

### Proposal

Is there a new version for this document in the works?

**Comment by danagbemava-nc** [comment]
I believe the best place for this would be discord.

I understand one is being worked on but it is not available yet. The wiki entry will be updated when it is available. 

You may reach out to Hixie on discord for further information. 

Closing from here as the roadmap will be updated when it is ready. 

Thank you
