### ISSUE TITLE
change icons color (back and actions) in  SliverAppBar with flexibleSpace when page is scrolled

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#14289]
Is possible change icons color (back and actions) in  SliverAppBar with flexibleSpace when page is scrolled?
I need change color from black to white
How can i do?
Thanks

**Comment by Hixie** [comment]
You can listen to the scroll position (or the scroll controller) and call setState and then in the builder select a color appropriately.

This isn't really the right forum for questions, though; StackOverflow would be a better place for questions. This is the forum for bugs or for requests for additional documentation. Is there somewhere we should have documented this where you would have found the answer? (In other words, where in the documentation did you look before filing the bug? Then we can add the answer there.)

**Comment by ogXxX** [comment]
@romaluca I was wondering if you've a working example for me? I'm pretty new to flutter and tried to build it by myself but I failed.. Please let me know! :)

**Comment by seeps001** [comment]
@ogXxX @romaluca any luck with this? Did you post on StackOverflow?

**Comment by goderbauer** [comment]
Closing as per comment above. Please ask these kind of questions on StackOverflow.
