### ISSUE TITLE
[Impeller] "EntityPass (Depth=1) contains one or more clips with an unresolved depth value" on flutter gallery.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142846]
E/flutter ( 7379): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: EntityPass (Depth=1) contains one or more clips with an unresolved depth value.

Spamming validation, not clear if it is going to cause rendering problems if the depth buffer isn't used yet?

@bdero

**Comment by jonahwilliams** [comment]
I think this is happening when ImageFilters are applied.

**Comment by jonahwilliams** [comment]
(From a stretch overscroll)

**Comment by bdero** [comment]
It won't cause problems right now (other than log spam), but it definitely will when we flip on the depth buffer because some clips won't have a correct depth value assigned.

**Comment by bdero** [comment]
I'm able to repro this with the material dropdown.

**Comment by bdero** [comment]
Ugh, found the bug.
