### ISSUE TITLE
[iOS] Mutator clips should not be applied to clipped elements that are scrolled "offscreen"

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142828]
Run the example from https://github.com/lucalooz/flutter_ads_list_perf , for this one I made sure that I could have one ad on screen that is scrolled off the bottom. The ListView is wrapped in a clip rect, which will apply a mutator if the platform view intersects it partially.

If you scroll the ad slightly off the bottom of the screen, the clip mutator still applies. This could be skipped, as the native view will be clipped by the screen anyway.

![flutter_01](https://github.com/flutter/flutter/assets/8975114/3e2d610e-caba-47f3-824d-5b02e3992941)

**Comment by jmagman** [comment]
I'm working on this one.
cc @hellohuanlin

**Comment by jonahwilliams** [comment]
This was fixed by making the clipping much cheaper!
