### ISSUE TITLE
I cant run my project and i get this : Could not determine the dependencies of task ':flutter_plugin_android_lifecycle:test'. this and base files have different roots

### ISSUE THREAD

**Issue by ArthNote** [flutter/flutter#142893]
### Steps to reproduce

1. if i run the project it gives me the erros
2. if i try ./gradlew build i get the same problem
3. the project was working fine, then it just happened

### Actual results

* What went wrong:
Could not determine the dependencies of task ':flutter_plugin_android_lifecycle:test'.
> Could not create task ':flutter_plugin_android_lifecycle:testReleaseUnitTest'.
   > this and base files have different roots: E:\Apps\Flutter\Flutter projects\tutorial2\build\flutter_plugin_android_lifecycle and C:\Users\taehy\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_plugin_android_lifecycle-2.0.17\android.
   
1. i tried deleting the cache folder and running flutter clean then flutter pub get, but i still get it

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by dam-ease** [comment]
Hi @ArthNote, thanks for filing the issue.

I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/105395.

You can try the temporary workaround here https://github.com/flutter/flutter/issues/105964#issuecomment-1155406556.

And can also keep tracking the issue https://github.com/flutter/flutter/issues/88666 that might be related.

Closing as a duplicate, please follow up on them for further updates.
