### ISSUE TITLE
[iOS] try using clipToBounds instead of masks for rectangular clips.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142830]
From https://github.com/flutter/flutter/issues/142813 , it seems like ClipRects implemented via mask views might create their masks via software rasterization. We might be able to perform rectangular clips more efficiently by using a parent UIViews frame and clipToBoundsProperty.

This is discussed as one of the answers in https://stackoverflow.com/questions/11391058/simply-mask-a-uiview-with-a-rectangle . We could confirm this is working via CPU profiles.

**Comment by jmagman** [comment]
I'll look at this one.
cc @hellohuanlin

**Comment by matanlurey** [comment]
Reverted by https://github.com/flutter/engine/pull/53220.

**Comment by ditman** [comment]
`ditman closed this as completed in ditman/flutter-engine@40d7aaa 4 hours ago`

Bah, I thought that using the github interface to keep my 'master' fork wouldn't trigger these auto-merges, but I guess that's wrong :/
