### ISSUE TITLE
First wave of Phase1 upgrade of devicelab iphones to iOS 17

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#142829]
### Type of Request

infra task

### Infrastructure Environment

devicelab, ios

### What is happening?

Please upgrade the iphones connected to the following hosts to iOS 17

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-1
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-38
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-2

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
Will look into and work on it afternoon today.

**Comment by vashworth** [comment]
@kentnguyen99 After upgrading, please also ensure device is paired:

* Open Xcode 15 from /opt/flutter/xcode/15a240d/XCode.app
* In the top bar, open Window > Device and Simulators
* The window that opens should show the connected device
* Accept the Trust dialog on the iPhone device
  * If you get the dialog on the device twice, you may need to accept it once, disconnect, reconnect, and accept again.
* Wait for the yellow bar at the top of the Device and Simulators window to go away - It should take a minute or so to Copy cache symbols

**Comment by yusuf-goog** [comment]
@vashworth these phones are now at 17. Please confirm that they functioning as required.

**Comment by vashworth** [comment]
I confirmed all bots and devices are working as expected. Thanks for your help!
