### ISSUE TITLE
New Flutter photo picker requires several steps to get to Google Photos

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#142840]
### Steps to reproduce

The new Flutter photo picker requires the following steps to allow a user to select photos from Google Photos, on the latest released version of Android (on Pixel 7 Pro):

1. A screen opens with two buttons, "Photos" and "Albums", and a three-dot menu at the top right.
  * It used to be that Google Photos popped right up, and it does on Android 33 on the emulator.
  * The "Photos" and "Albums" buttons only show you photos locally stored on the phone.
2. The user has to tap the three-dot menu, which has only one option, "Browse".
  * Why is there even a menu button here, if there is only one option? It would be better to have a Browse button, because that would be much more discoverable.
 3. "Browse" takes you to a screen that says "Search this phone" at the top, and has a list of apps: "Browse files in other apps".
   * Google Photos is not even shown on the first page of these icons (I see three Drive icons, then "Media picker").
   * There is no visual indication anywhere that this list of icons can be scrolled, so that you can see more icons on the right. This is totally un-discoverable UI.
 4. The user has to scroll the icons list to the left (to see more icons on the right), then can tap Photos.
 5. Finally, the list of Google Photos albums pops up.
 
This is a ridiculously complicated way to get to your photos, when your primary means of interacting with the photos you have taken in the past is through Google Photos. (I don't have even a fraction of all my photos actually physically cached on my phone...)

cc @stuartmorgan 

### Expected results

The buttons for Google Photos or other album software should appear on the very first modal bottom sheet that pops up, and if the icons don't all fit on the screen, there should be a way to scroll this, just how the Share modal bottom sheet works right now, displaying all apps that can handle the Share intent.

### Actual results

It takes a lot of hunting effort and some creativity to even find the Google Photos albums, and that leads to a very negative user experience, because users think they can't select photos from their albums anymore.

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel beta, 3.19.0-0.1.pre, on Fedora Linux 39 (Workstation Edition) 6.6.9-200.fc39.x86_64, locale en_US.utf8)
    • Flutter version 3.19.0-0.1.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a9a60d044 (3 weeks ago), 2024-01-10 13:38:09 -0800
    • Engine revision bbebee1465
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6 (Fedora 17.0.6-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.81.20231227

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.79.20231130

[✓] Connected device (4 available)
    • Pixel 7 Pro (mobile)       • 29161FDH300BLP • android-arm64  • Android 14 (API 34)
    • sdk gphone x86 64 (mobile) • emulator-5554  • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux          • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.6.9-200.fc39.x86_64
    • Chrome (web)               • chrome         • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by moffatman** [comment]
That popup is not implemented by Flutter, it just calls out to Android with the following activity:

`usePhotoPickerAndroid` -> `ActivityResultContracts.PickVisualMedia`
`!usePhotoPickerAndroid ` -> `Intent(Intent.ACTION_GET_CONTENT)`

https://developer.android.com/training/data-storage/shared/photopicker

**Comment by lukehutch** [comment]
Why not use `Intent.ACTION_PICK`? I think that brings up a list of all apps that can be used to pick photos.

**Comment by moffatman** [comment]
I think `Intent.ACTION_PICK` is not well supported and deprecated, also requires base URI to start picking from. But anyway, I think google photos still works with `ACTION_GET_CONTENT`, no?

**Comment by lukehutch** [comment]
Possibly it does, I haven't tested this directly (I am working in Flutter). I se to rembe Ron another picker issue that I filed that it's not going to be possible to use anything but the new Android photo picker in future, which seems ridiculous to me, because it is such a bad experience. Can you at least make it possible in perpetuity for apps to set `usePhotoPickerAndroid = false`?

**Comment by moffatman** [comment]
I don't expect `usePhotoPickerAndroid = false` will be removed as long as it has this advantage over the new picker and is still supported by Android.

**Comment by stuartmorgan** [comment]
Closing since, as explained above (and [as I have explained previously](https://github.com/flutter/flutter/issues/139111#issuecomment-1829701306)), none of the UI you are providing feedback on is part of the plugin. Feedback about the new Android photo picker experience itself would need to be directed to the Android team.

> cc @stuartmorgan

Please don't just CC arbitrary people when filing issues. We have a triage process that routes bugs.

**Comment by lukehutch** [comment]
@moffatman I was able to test this with `usePhotoPickerAndroid = false` and `usePhotoPickerAndroid = true`.

**First issue:** this setting is not even exposed in `image_picker`, you have to add a direct dependency upon `image_picker_platform_interface` and `image_picker_android` to get to this setting, and then run the following code:

```dart
  if (Platform.isAndroid) {
    ImagePickerAndroid.registerWith();
    (ImagePickerPlatform.instance as ImagePickerAndroid).useAndroidPhotoPicker = true;
  }
```

**Second issue:** at least on Pixel 7 Pro, on Android, all that setting `useAndroidPhotoPicker = true` does is remove the three-dot menu at the top right of the picker sheet, which has the single menu option "Browse".

On Pixel 7 Pro, Android 14, with `useAndroidPhotoPicker = false`:

![image](https://github.com/flutter/flutter/assets/811305/ad6e8199-8c1f-4ee3-980c-68bc366e7486)

On Pixel 7 Pro, Android 14, with `useAndroidPhotoPicker = true`:

![image](https://github.com/flutter/flutter/assets/811305/5d94983f-38e0-498e-b170-7c816977a43e)

Whereas, on the Android emulator, API level 33, with `useAndroidPhotoPicker = false`, I get the following (this is what I want to happen on Pixel 7 / Android 14, also):

![image](https://github.com/flutter/flutter/assets/811305/174121b2-d00a-4b74-aaca-f34499c5b71b)

vs. on the Android emulator, API level 33, with `useAndroidPhotoPicker = true`, I get the same very limited Android photo picker with no "Browse" menu option:

![image](https://github.com/flutter/flutter/assets/811305/5dd11333-f018-4ca0-b08e-6159f2ccb55c)

**What the problems are:** 

Despite the fact that these issues I am filing keep getting closed, there is still a major issue here.

(1) For whatever reason, on Pixel 7 Pro / Android 14, `ACTION_GET_CONTENT` just uses the same really limited Android photo picker, albeit adding a Browse menu item. I assume that the default Android photo picker is intercepting this intent, or something. There is no way to ask for `image_picker` to try using a different intent. Please add a config option to select photos with a different intent. This is a plugin issue, NOT an Android issue, which my issues keep getting closed for.

(2) I want to be able to set `useAndroidPhotoPicker = false` from the `image_picker` API, and that is not exposed right now. I don't want the default Android photo picker to run, ever. This is also a plugin issue, NOT an Android issue.

**Comment by stuartmorgan** [comment]
> I want to be able to set useAndroidPhotoPicker = false from the image_picker API

The current approach is our standard model for settings that are fundamentally linked to a single platform. We will not be re-exposing this from the app-facing package.

> There is no way to ask for `image_picker` to try using a different intent. Please add a config option to select photos with a different intent.

We will not be adding yet another mode to the Android implementation of `image_picker`. You are welcome to make your own unendorsed Android implementation that has an alternate approach, or to use a different plugin that allows sending arbitrary intents.
