### ISSUE TITLE
[iOS] Platform view slicing is inefficient

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#142817]
Run the example from https://github.com/lucalooz/flutter_ads_list_perf , I added more ads so that there were at least two on screen at one time. I ran the application thorugh XCode and captured a metal system trace. If you notice, there are three SurfaceFrame::Render calls below.

![image](https://github.com/flutter/flutter/assets/8975114/25325ce2-b38d-4f86-9a53-38fbd5a6e47d)

It turns out that two of them are completely empty. We're making the engine and iOS do a lot more work, and making the compositor do a lot more work with these. 

![image](https://github.com/flutter/flutter/assets/8975114/996d9561-8201-4117-ba41-746df5fb9753)

We need to investigate how we are slicing up the Flutter UI and ensure that we have appropriate fast paths when slices are empty.

**Comment by jmagman** [comment]
cc @hellohuanlin

**Comment by dnfield** [comment]
The EmbeddedViews does have some kind of check about whether it's empty which it gets from `DisplayList::bounds` - I wonder what that's reporting in these cases?

**Comment by loic-sharma** [comment]
cc @hellohuanlin to write an update

**Comment by jonahwilliams** [comment]
I think this was actually fixed, it was the subpixel boundary issue.

**Comment by hellohuanlin** [comment]
I agree. Closing it as complete.
