### ISSUE TITLE
SelectionArea's contextMenuBuilder should be dynamically updatable

### ISSUE THREAD

**Issue by AlienKevin** [flutter/flutter#142806]
### Use case

Currently, the context menu in a SelectionArea is created once by the contextMenuBuilder and cannot be updated. However, there are cases when one wants to update the buttonItems in the context menu based on selected text.

For instance, I'm developing a dictionary app and want to quickly looking up words in the example sentences. Customizing the context menu seems like an intuitive solution: I can add a "lookup" buttonItem to the menu so that the user can click on it and see a popup showing the definition of the word. However, it wouldn't make sense to show the "lookup" button if the selected text is not a word or not in the dictionary at all. Since the selected text can change as the user drags the selection endpoints around, I need a way to dynamically update the buttonItems based on the current selected text.

Here's a sample snippet of what I want to achieve:
```dart
SelectionArea(
  contextMenuBuilder: (
    BuildContext context,
    SelectableRegionState selectableRegionState,
  ) {
    return AdaptiveTextSelectionToolbar
        .buttonItems(
      anchors: selectableRegionState
          .contextMenuAnchors,
      buttonItems: [
        selectionInDictionary ? [ContextMenuButtonItem(
          onPressed: () {
            ContextMenuController.removeAny();
            print(model.selectedContent);
          },
          label: 'Lookup',
        )] : [],
        ...selectableRegionState
            .contextMenuButtonItems,
      ],
    );
  }, ...)
```

### Proposal

Consider calling the contextMenuBuilder on selection change, or provide an alternative way to update the context menu dynamically.

**Comment by AlienKevin** [comment]
I just noticed that the `SelectionState` provider I'm using doesn't auto-update the context menu because the `selectionInDictionary` is passed in by value. After I hoisted the Provider up to the root of the app and accessed the `selectionInDictionary` property through that provider, the context menu is updating:

```dart
SelectionArea(
                      contextMenuBuilder: (
                        BuildContext context,
                        SelectableRegionState selectableRegionState,
                      ) {
                        return AdaptiveTextSelectionToolbar.buttonItems(
                          anchors: selectableRegionState.contextMenuAnchors,
                          buttonItems: [
                            ...context.watch<SelectionState>(). selectionInDictionary
                                ? [
                                    ContextMenuButtonItem(
                                      onPressed: () {
                                        ContextMenuController.removeAny();
                                        print(context
                                            .read<EntryState>()
                                            .selectedContent);
                                      },
                                      label: 'Lookup',
                                    )
                                  ]
                                : [],
                            ...selectableRegionState.contextMenuButtonItems,
                          ],
                        );
                      },
```

However, it would nice if I can keep the provider local to the widget. I had to hoisted it to root because the context menu is achieved as an Overlay which has a higher scope than its parent.

**Comment by darshankawar** [comment]
@AlienKevin 
Does adding a `controller` help in your case ? If so, can you check if https://github.com/flutter/flutter/issues/127025 resembles your case or not ?

**Comment by AlienKevin** [comment]
I think my case is different from the controller's use case. I'd like the contextMenuBuilder to be under the scope of its parent widget, just like any other widgets in the build method. However, it is currently behaving like an OverlayEntry and is very high up in the hierarchy. This makes updating the context menu based on local state difficult because they are not in the same scope. I think it may be useful to have a parameter in contextMenuBuilder that gives access to the parent's context, rather than the context of the overlay. This way the normal Provider scoping can be preserved.

**Comment by Renzo-Olivares** [comment]
cc @justinmc if you had any input on this issue.

**Comment by justinmc** [comment]
@AlienKevin Can you reproduce the bug without `provider`? I'm wondering if the problem is with `provider` or with contextMenuBuilder.

Also, this example is somewhat related, in case you haven't seen it before. It shows changing the buttons based on the current selection: https://github.com/flutter/flutter/blob/master/examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart
