### ISSUE TITLE
Fuchsia CIPD upload is failing frequently

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#142811]
Here's an example:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_fuchsia/1238/overview

In the last day or so this has flaked many many times, resulting in sporadic engine tree closures. When the upload fails, the top-level retry performs the entire build again, wasting resources.

cc @keyonghan infra gardener
fyi @matanlurey engine sheriff.

**Comment by zanderso** [comment]
Maybe related https://github.com/flutter/flutter/issues/142467

**Comment by keyonghan** [comment]
The suspicious culprit is https://github.com/flutter/engine/pull/50058/files. 

The real issue is increased build time of subbuild: `fuchsia_release_x64`.

The timeout example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/574235/overview (40 mins), which builds:
```
build fuchsia_release_x64 flutter/shell/platform/fuchsia:fuchsia flutter/shell/platform/fuchsia/dart_runner:dart_runner_tests fuchsia_tests
```

The old build example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/567302/overview (less than 10mins), which builds:
```
build fuchsia_release_x64 flutter/shell/platform/fuchsia:fuchsia
```

The issue started right after the mentioned PR:
![Screenshot 2024-02-02 at 9 24 49 AM](https://github.com/flutter/flutter/assets/54558023/05081097-6148-4f46-9eb7-2a33dfcfd1ff)

/cc @zijiehe-google-com @CaseyHillers

**Comment by zanderso** [comment]
@keyonghan I don't understand how a longer build time could cause the upload to fail?

**Comment by zanderso** [comment]
@keyonghan @CaseyHillers Moving this to staging here: https://github.com/flutter/engine/pull/50288

**Comment by keyonghan** [comment]
> @keyonghan I don't understand how a longer build time could cause the upload to fail?

The longer subbuild execution time contributes to the orchestrator's execution time, which is 60min: https://github.com/flutter/engine/blob/main/.ci.yaml#L196

The failed builds are roughly around 1h. Do we want to keep the changes? If yes, a `timeout` bump will fix the issue. If not, then we should revert the change.

**Comment by CaseyHillers** [comment]
The increased build time seems to have started on 1/30, which makes me think it's related to https://github.com/flutter/engine/pull/50058.

That PR added tests for release artifacts, which is what's taking so long here.  https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/570434/overview shows the build step is taking a large amount of time.

@zijiehe-google-com do you see anything obvious that is taking too long on release builds?

**Comment by zijiehe-google-com** [comment]
My change started building `fuchsia_tests` on release which was unfortunately broken for a while. It's expected to need more time. https://github.com/flutter/engine/pull/50058/files#diff-bb4548f308ab113cc9b814ff34d2dca5f28d7bf88ce8f59baa59ec83a3948dc4

**Comment by zijiehe-google-com** [comment]
For the case like https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_fuchsia/1240/overview, https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8757189347893436433/+/u/Global_generators/Upload_to_CIPD_for_arch:_x64/stdout showed the cipd stuck in the cipd verification. It's the case happened before in chromium and we never got a real solution to resolve it - increasing the timeout usually is just a waste of time. The reliability and variance of uploading speed of cipd seem never reaching a headache-free state - I think previously it wasn't designed to handle traffics from automatic systems like builders.

In chromium, the cipd uploading is now handled by a separate recipe module: http://cs/h/chromium/chromium/tools/build/+/main:recipes/recipe_modules/archive/examples/archive_cipd.py?l=5, and the regular builders only need to generate yaml files (https://crsrc.org/c/build/fuchsia/cipd/BUILD.gn) to define the cipds without needing to upload them ourselves.

**Comment by CaseyHillers** [comment]
> In chromium, the cipd uploading is now handled by a separate recipe module: http://cs/h/chromium/chromium/tools/build/+/main:recipes/recipe_modules/archive/examples/archive_cipd.py?l=5, and the regular builders only need to generate yaml files (https://crsrc.org/c/build/fuchsia/cipd/BUILD.gn) to define the cipds without needing to upload them ourselves.

CIPD is a red herring. The builds go from 20~30 minute runtime to 60 minutes with the change. CIPD is unfortunately the last step, so when LUCI kills the build, it looks like it's the culprit. We could extend the timeout of the Fuchsia builder from 60 minutes to 75 minutes if this is expected, but the engine repo requires all blocking builders to finish in <30 minutes. Increasing this timeout would require us to not block the tree as well.

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/50058 should be reverted until the extra work can be made to fit into the existing timeout.

**Comment by zanderso** [comment]
Put up a revert here https://github.com/flutter/engine/pull/50291

**Comment by zanderso** [comment]
Shifting to P0 because moving the builder to staging has caused the engine roll to the framework to fail.

**Comment by zijiehe-google-com** [comment]
Quickly talked with @CaseyHillers , I will redo https://github.com/flutter/engine/pull/50291 without adding new targets in release builder to eliminate the extra time cost.
For the cipd, Casey is working on moving away from it in favor of gcs, so it won't be in the scope anymore.

Also a follow up change will bring up a separate linux_fuchsia_release builder to include extra targets & tests.

After merging https://github.com/flutter/engine/pull/50291, https://github.com/flutter/engine/pull/50288 can be reverted as well.

**Comment by zijiehe-google-com** [comment]
It turned out to be a false alarm, the first several runs were penetrated by the cold goma cache and fairly slow, but the last one (https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_fuchsia/1240/overview) was caused by the unreliable cipd upload as I mentioned above. Giving it a little bit time may or may not resolve the issue, but it will be migrated away in favor of gcs, I won't care too much about it.

Uploading cipd during try runs is still a problem, but out of the scope.

Since now the cache is warm, the build time dropped to a reasonable range. But to ensure the safety of the change, I will increase the timeout of linux_fuchsia to 75 minutes in https://github.com/flutter/engine/pull/50295.

**Comment by zijiehe-google-com** [comment]
The prod builder has no `--no-lto` gn parameter as the try builder; it increased the compilation time from <5 min to over 30 min.
I am digging out the meaning of this parameter.

**Comment by zijiehe-google-com** [comment]
Latest run behaved correctly with `--no-lto`. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/578695/steps
