### ISSUE TITLE
Building and install software onto new 4 Arm Windows machines.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#142823]
### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

Building and install software onto new 4 Arm Windows machines.

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by yusuf-goog** [comment]
bots are setup, win-17..20
