### ISSUE TITLE
Document how to generate an IPA for iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1428]
_From @sethladd on January 27, 2016 18:17_

Similar to this doc: https://flutter.io/building-apk/ but for iOS. For example, how can I configure the name of my app? My icon? How do I use the command line, or Xcode?

Thanks!

_Copied from original issue: flutter/website#151_

**Comment by sethladd** [comment]
cc @chinmaygarde would you be able to draft something up for us to test?

**Comment by qchong** [comment]
@chinmaygarde Ping. Can you please share instructions for this?

**Comment by qchong** [comment]
Marking as closed.

Chinmay has provided documentation in this [Google doc](https://docs.google.com/document/d/1ii94IoGA-34t9lrqCBDeT5jKKZlPSwAVI14O5IvSvAs/edit#heading=h.nlcqufm0xd8c). 

For the purpose of the dry-run codelab, we should just mention that the tooling generates the IPA file and point to the location for the generated file. We should also be explicit that the generated IPA is for testing purposes only and should not be submitted to the Apple Store.

**Comment by chinmaygarde** [comment]
That Google doc has been published at https://flutter.io/ios-release/
