### ISSUE TITLE
Properly render the warmup frames

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#142851]
We should incorporate the warmup frames into the current rendering structure, so that the warmup frames can be rendered and presented onto the screen.

### Why
While it might sound against the purpose for warmup frames, we've discovered that the warmup frames should actually be rendered and presented.

As soon as the Dart isolate is started, a warm up frame is scheduled, which immediately render the widget tree to a layer tree and submit it to the engine. If we don't present this layer tree, then the user will have to wait for the next vsync to see the first frame, which is bound to be later. This delay was actually flagged as a performance regression earlier (b/307872797).

### Analysis
This is how a regular frame is presented:.
* A frame is scheduled (such as via `PlatformDispatcher.scheduleFrame`), which causes the `Animator` to submit a task  for the next vsync.
* The next vsync task:
  * Calls `Animator::BeginFrame`
    *  Produces a pipeline continuation
    * Calls `RuntimeController.BeginFrame`, which
      * Calls `PlatformDispatcher.onBeginFrame`
      * Clears microtasks
      * Calls `PlatformDispatcher.onDrawFrame`
        * which calls `FlutterView.render` for all views, which just stores the layer tree in `Animator`.
  * Calls `Animator::EndFrame`
    * which submit the stored layer trees to the pipeline continuation.

Therefore, rendering a frame requires the pipeline continuation produced in `BeginFrame`, and the submission in `EndFrame`. This is why we proposed to enforce the render rule in https://github.com/flutter/flutter/issues/137073.

However, the render rule forbids `FlutterView.render` calls out of vsyncs, which are warm up frames. 

<details>
<summary>
We initially proposed a "workaround mechanism". We've abolished this plan. Expand here to see the details.
</summary>
Currently, we implemented a workaround mechanism in `RuntimeController`:
* In `RuntimeController::Render`, if all registered views have been rendered, then it calls `Animator::EndFrame`.

This allows the multiview pipeline to coexist with existing warmup frame situations. But it is not only an ugly rule, but also can not detect the case where only part of all views are warmup frames.
</details>

The tentative plan is to add a new function, `PlatformDispatcher.forceFrame`, which does everything of the "vsync task" as mentioned above, but is run directly instead of within a vsync. 

The render rule should be enforced after this issue is resolved.

### Real app testing

To illustrate the difference, I added some logging statements to the engine, and tested on an app on macOS. 

Case 1: This is how the app starts up on an unmodified engine (the number at the start is time in milliseconds):

```
[    0] Animator::BeginFrame
[    0]   created continuation
[    3] Animator::EndFrame
[  947] Animator::BeginFrame
[  947]   use existing continuation
[  950] Animator::EndFrame
[ 2879] Animator::Render      <-- The warmup render, out of vsync
[ 2879]   Fabricate recorder
[ 2879] Animator::EndFrame
[ 2879]   OnAnimatorDraw
[ 2879] Rasterizer::Draw
[ 2879] Rasterizer::DoDraw
[ 3006] Animator::BeginFrame
[ 3006]   created continuation
[ 3131] Animator::Render
[ 3131] Animator::EndFrame
[ 3131]   OnAnimatorDraw
[ 3158] Rasterizer::Frame callback
[ 3167] Rasterizer::Draw
[ 3167] Rasterizer::DoDraw
[ 3179] Rasterizer::Frame callback
[ 3187] Animator::BeginFrame
[ 3187]   created continuation
[ 3239] Animator::Render
...
```

Case 2: This is how the app starts up if out-of-vsync render calls are skipped (basically with https://github.com/flutter/engine/pull/45555 applied):

```
[    0] Animator::BeginFrame
[    0]   created continuation
[    5] Animator::EndFrame
[ 1081] Animator::BeginFrame
[ 1081]   use existing continuation
[ 1083] Animator::EndFrame
[ 3149] Animator::BeginFrame
[ 3150]   use existing continuation
[ 3283] Animator::Render      <-- The first regular render, within vsync
[ 3283] Animator::EndFrame
[ 3283]   OnAnimatorDraw
[ 3283] Rasterizer::Draw
[ 3283] Rasterizer::DoDraw
[ 3293] Animator::BeginFrame
[ 3293]   created continuation
[ 3357] Animator::Render
[ 3357] Animator::EndFrame
[ 3357]   OnAnimatorDraw
[ 3359] Animator::BeginFrame
[ 3359]   continuation full
[ 3360] Animator::EndFrame
[ 3378] Animator::BeginFrame
[ 3378]   continuation full
[ 3378] Animator::EndFrame
[ 3394] Animator::BeginFrame
[ 3394]   continuation full
[ 3394] Animator::EndFrame
[ 3410] Animator::BeginFrame
[ 3410]   continuation full
[ 3410] Animator::EndFrame
[ 3413] Rasterizer::Frame callback
[ 3417] Rasterizer::Draw
[ 3417] Rasterizer::DoDraw
[ 3428] Animator::BeginFrame
[ 3428]   created continuation
...
```

We can see that in case 2, the first `Animator::Render` is as late as the 3rd `Animator::BeginFrame`, while in case 1 the first render is between the 2nd and the 3rd `Animator::BeginFrame`. Having an earlier `Animator::Render` means that the first `Rasterizer::DoDraw` is earlier, and the first frame is drawn sooner.

**Comment by dnfield** [comment]
I talked about this with @goderbauer a little while ago.

My question was: if the rule is wrong, why are we trying to enforce it? Why does multi-view have to change the way this subsystem is working?

**Comment by dnfield** [comment]
IOW, it seems like we've discovered that a rule we thought would make sense actually causes problems, and instead of saying the rule is bad, we're trying to figure out how to make the rule work.

**Comment by dkwingsmt** [comment]
Thanks for your comments. I can see the concern.

We're not trying to keep the rule around by making the environment fit, which I agree is bad. Instead, we're just looking for a way to submit multiple views. And the entire hustle with the rule is more like saying "the option with this rule, which require some other modifications, is what we ended up choosing."

Let me review the options we've thought about.

### Option 1 (relying on the render rule)

* Idea: 
  * Keep the `FlutterView.render` API, and adds no end-of-frame call API.
  * This ensures the best backward compatibility for dart:ui apps (i.e. apps that do not use the framework, but call dart:ui APIs directly.)
* `FlutterView.render` must make `Animator` store the layer tree.
* Without an end-of-frame call, the only place to reliably submit the layer trees to the pipeline is the end of the vsync task.
* Therefore, it requires the render rule, i.e. all `FlutterView.render` must take place within the vsync task. This rule has been written in the document since day 1 anyway, just not enforced.
* Since the warmup frames must take place out of vsync, we need an additional function to draw the warmup frames. (Violations will be ignored, so not a real breaking change for dart:ui apps.)

### Option 2 (explicit end-of-frame call)

* Idea:
  * Keep the `FlutterView.render` API, but requires an explicit end-of-frame API (let's say, `PlatformDispatcher.submitFrame`) to submit these layer trees to the pipeline.
* This gives the framework the best flexibility. The warmup frames will work as well.
* However, this breaks all existing single-view dart:ui apps, since their `FlutterView.render` no longer implicitly submit the view to the pipeline.

### Option 3 (grouped submission)

* Idea:
  * Add a dedicated `PlatformDispatcher.renderViews` method, which submits a list of layer trees to the engine.
  * We can also keep the `FlutterView.render` API for a while, and deprecate it later.
* This works well with both warmup frames and regular frames, and requires no "rules".
* However, this adds a new API and deprecate another. This will be a burden to dart:ui app developers, and will invalidate historical dart:ui apps some time in the future.

------

Feel free to let me know of any other ideas. But as of the 3 that I can think of, it's mostly between option 1 and 3, and both have their pros and cons. Previously we chose option 1 since its API is completely compatible with existing apps, while option 3 requires a deprecation. However, with the discovery of the warmup frames, I agree that it's becoming more debatable. 

Also cc @loic-sharma

**Comment by loic-sharma** [comment]
@dnfield We'd like the engine's pipeline to apply back pressure for scenes _across_ frames but not for scenes within a frame. To do so, the engine needs to be able to distinguish the start and end of a frame.

> Why can't the animator just submit whatever it has the pipeline every vsync?

This would significantly regress the GPay app's startup benchmarks as the framework's warm up frame is presented on Android. (FWIW, this behavior is arguably incorrect: frames should only be presented only on a vsync).

> Why would we artificially delay rendering so that all views are done?

We'd like to avoid this. Our preferred solutions don't need to artificially delay rendering.

**Comment by dkwingsmt** [comment]
After offline discussion, we've come to the agreement of option 1 but without going through a workaround as seen in https://github.com/flutter/engine/pull/49950/commits/47e6cdd938f46d5859b05ae290896606d7cb9523.

**Comment by dkwingsmt** [comment]
This has been implemented. The warm up frames are now properly rendered and unit tests have been added to verify it. See https://github.com/flutter/engine/pull/50570.

In the future we might want to really make the warmup frame use the codepath of `PlatformConfiguration::BeginFrame` and remove the two callbacks in `scheduleWarmUpFrame`. But that's a low priority cleanup for another day.
