### ISSUE TITLE
Linux build run not working fedora ( I have solution )

### ISSUE THREAD

**Issue by KarthiDreamr** [flutter/flutter#142802]
### Steps to reproduce

karthi@hiwatari-fedora:~/your project path $ flutter run
Connected devices:
Linux (desktop) • linux  • linux-x64      • Fedora Linux 39 (Workstation Edition)
6.6.13-200.fc39.x86_64
Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.139
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (or "q" to quit): 1
Launching lib/main.dart on Linux in debug mode...
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  flutter/ephemeral/.plugin_symlinks/desktop_webview_auth/linux/CMakeLists.txt:21 (pkg_check_modules)

Building Linux application...                                           
Exception: Unable to generate build files

### Actual results

sudo dnf install libsecret-devel jsoncpp-devel

https://stackoverflow.com/a/76977437/18976379 solves the issue

### Flutter Doctor output

flutter doctor all checks are OK

**Comment by stuartmorgan** [comment]
> flutter/ephemeral/.plugin_symlinks/desktop_webview_auth/linux/CMakeLists.txt:21 (pkg_check_modules)

Per the error message, this is coming from the build file for the `desktop_webview_auth` plugin. Issues with third-party packages need to be reported to the developers of the package.
