### ISSUE TITLE
Can't archiving ios app, always get error like this from path_provider repository's

### ISSUE THREAD

**Issue by mohbasirudin** [flutter/flutter#142800]
I need this repo to get directory path's. I can build to simulator, but always get error when try to archiving via xcode. cause i need export .ipa to upload in App Store.

**My tech**
1. Sonoma 14.x
2. XCode 15.x
3. Flutter 3.16.x
4. path_provider: ^2.1.2

**ERROR MESSAGE**
> path_provider_foundation

> .../Library/Developer/Xcode/DerivedData/Runner-ccitxbruqixsvlflhiutogwtcdcy/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/path_provider_foundation/path_provider_foundation.framework/Headers/path_provider_foundation-Swift.h

> .../Library/Developer/Xcode/DerivedData/Runner-ccitxbruqixsvlflhiutogwtcdcy/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/path_provider_foundation/path_provider_foundation.framework/Headers/path_provider_foundation-Swift.h:280:9 (fatal) module 'Flutter' not found

> .../Library/Developer/Xcode/DerivedData/Runner-ccitxbruqixsvlflhiutogwtcdcy/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/path_provider_foundation.build/VerifyModule/path_provider_foundation_objective-c++_arm64-apple-ios12.0_gnu++14/Test/Test.framework/Headers/Test.h

> .../Library/Developer/Xcode/DerivedData/Runner-ccitxbruqixsvlflhiutogwtcdcy/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/path_provider_foundation.build/VerifyModule/path_provider_foundation_objective-c++_arm64-apple-ios12.0_gnu++14/Test/Test.framework/Headers/Test.h:1:9 (fatal) could not build module 'path_provider_foundation'

![image](https://github.com/flutter/flutter/assets/46457480/49ec9e73-9e28-4301-86f6-7640a355e75f)

**Comment by dam-ease** [comment]
Hello @mohbasirudin.
Thanks for filing this.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code we can use to reproduce this?
Please also try taking out the `path_provider` package to see if this is specific to this package.

**Comment by dam-ease** [comment]
Thanks for your response @mohbasirudin.
Kindly share a simple repo we can use to reproduce this on our end.

**Comment by mohbasirudin** [comment]
> Thanks for your response @mohbasirudin.
> Kindly share a simple repo we can use to reproduce this on our end.

Sorry, simple repo like what? I didn't add any repo besides path_provider. I just add it and set Ios Development Target to 12, then archive via xcode in menu product > archive, and that is it, and got that's error :(

**Comment by dam-ease** [comment]
Hello @mohbasirudin.
The sample repo being referred to here is a code sample or github repo you can share that can be run on our end to reproduce this issue. See more about this here https://stackoverflow.com/help/minimal-reproducible-example.
I tried archiving my app using the package example here: https://pub.dev/packages/path_provider/example, but I can't see any error on my end. Can you try this as well?

**Comment by mohbasirudin** [comment]
> Hello @mohbasirudin. The sample repo being referred to here is a code sample or github repo you can share that can be run on our end to reproduce this issue. See more about this here https://stackoverflow.com/help/minimal-reproducible-example. I tried archiving my app using the package example here: https://pub.dev/packages/path_provider/example, but I can't see any error on my end. Can you try this as well?

oh yeah, oke, this is a simple example of my code [https://github.com/mohbasirudin/sample_path_provider](url)

**Comment by dam-ease** [comment]
Hello @mohbasirudin 
Please can you try with the example app shared here https://github.com/flutter/flutter/issues/142800#issuecomment-1926324934?

**Comment by mohbasirudin** [comment]
> Hello @mohbasirudin 
> Please can you try with the example app shared here https://github.com/flutter/flutter/issues/142800#issuecomment-1926324934?

I just create this in my code

```
  var path = "-";

  void _getPath() async {
    try {
      var dir = await getApplicationDocumentsDirectory();
      path = dir.path;
    } catch (e) {
      path = "error path: $e";
    }

    setState(() {});
  }
```

but, if i delete that's code, i still get same error

**Comment by mohbasirudin** [comment]
> Hello @mohbasirudin 
> Please can you try with the example app shared here https://github.com/flutter/flutter/issues/142800#issuecomment-1926324934?

I think that's not about code, but about a minimum ios, in your pub description it can run in ios 11+, but i got error when i try to change minimum ios in my pod to 12+. Cause in xcode 15.x, minimum was set to ios 12+, and ios11 is deprecated in xcode 15.x. Maybe, it just my argument.

**Comment by dam-ease** [comment]
Thanks for your response @mohbasirudin.

>  but i got error when i try to change minimum ios in my pod to 12+. Cause in xcode 15.x, minimum was set to ios 12+, and ios11 is deprecated in xcode 15.x

Not sure I completely got this but I tried archiving your repo and can't seem to reproduce these errors but only a PrivacyInfo error, do you get any logs if you try building ipa with `flutter build ipa --release`?

**Comment by mohbasirudin** [comment]
> Thanks for your response @mohbasirudin.
> 
> > but i got error when i try to change minimum ios in my pod to 12+. Cause in xcode 15.x, minimum was set to ios 12+, and ios11 is deprecated in xcode 15.x
> 
> Not sure I completely got this but I tried archiving your repo and can't seem to reproduce these errors but only a PrivacyInfo error, do you get any logs if you try building ipa with `flutter build ipa --release`?

i've try it, using `flutter build ipa --release` and get success.

but, why i still get same error when build ipa via xcode? if check all this checkbox after run `pod install --update-repo`
![image](https://github.com/flutter/flutter/assets/46457480/db857273-1fb4-4b53-9e4d-1908c33629cc)

and will get success build ipa when uncheck this all checkbox. it will ignore minimum ios11? cause if i check all this checkbox it will set all package to minimum ios 12.
![image](https://github.com/flutter/flutter/assets/46457480/e0c1a20b-1982-4b7a-aee4-9475b525a9cf)

**Comment by dam-ease** [comment]
Thanks for your response @mohbasirudin.
From your findings, if I got you correctly, this works fine when:

- you try building with `flutter build ipa --release` and 
- when you uncheck all the checkboxes

I'm able to archive my app with the `path_provider` package setting the minimum iOS deployment target to `12.0`.
This might be an issue with Code signing instead, can you please check this out? 
This might be best suited for support channels like StackOverflow, please ask the same there for solutions if any or also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

**Comment by mohbasirudin** [comment]
> Thanks for your response @mohbasirudin.
> From your findings, if I got you correctly, this works fine when:
> 
> - you try building with `flutter build ipa --release` and 
> - when you uncheck all the checkboxes
> 
> I'm able to archive my app with the `path_provider` package setting the minimum iOS deployment target to `12.0`.
> This might be an issue with Code signing instead, can you please check this out? 
> This might be best suited for support channels like StackOverflow, please ask the same there for solutions if any or also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

No, i'm not use xcode if i was use `flutter build ipa --release` to build ipa. So, i use 2 method to build ipa:
1. Using command `flutter build ipa --release`, and then i can upload to appstore using transporter. [SUCCESS].
2. Using xcode, if i check all check, it will FAIL. But, if i uncheck all, it will give me a SUCCESS build ipa. If success, then upload to App Store using transporter.

About stackoverflow, i was open case in stackoverflow too. but, nobody response.

**Comment by darshankawar** [comment]
> this is a simple example of my code [https://github.com/mohbasirudin/sample_path_provider](url)

I tried this repo on my setup in which I wasn't able to replicate the reported behavior. Maybe this will require xcode 15 and ios 17 combination.



> I think that's not about code was i created, but about a minimum ios, in your pub description it can run in ios 11+, but i got error when i try to change minimum ios in my pod to 12+. Cause in xcode 15.x, minimum was set to ios 12+, and ios11 is deprecated in xcode 15.x. Maybe, it just my argument.

can you try by running `flutter pub upgrade` ?

**Comment by mohbasirudin** [comment]
> > this is a simple example of my code [https://github.com/mohbasirudin/sample_path_provider](url)
> 
> I tried this repo on my setup in which I wasn't able to replicate the reported behavior. Maybe this will require xcode 15 and ios 17 combination.
> 
> > I think that's not about code was i created, but about a minimum ios, in your pub description it can run in ios 11+, but i got error when i try to change minimum ios in my pod to 12+. Cause in xcode 15.x, minimum was set to ios 12+, and ios11 is deprecated in xcode 15.x. Maybe, it just my argument.
> 
> can you try by running `flutter pub upgrade` ?

yap, i was running on xcode15 & ios17. and i was tried to updagrade my repo using `flutter pub upgrade` or `manually`, but nothing has changed

**Comment by dam-ease** [comment]
Hello @mohbasirudin 
Thanks for your response. I’m unable to reproduce this with the same config.
I’ll label this for more insights.

**Comment by hellohuanlin** [comment]
cc @jmagman

**Comment by jmagman** [comment]
I can't even build this sample app at https://github.com/mohbasirudin/sample_path_provider, you have `ENABLE_USER_SCRIPT_SANDBOXING` on, which Flutter requires to be off, presumably set with "Updated to recommended settings".

1. I'm on 3.16.9
2. Create a new flutter project.  Add `path_provider: ^2.1.2` to the pubspec.  Xcode project is already set to iOS 12 minimum.
3. `open ios/Runner.xcworkspace` 
4. Archive in Xcode

And it succeeds.

What version of Flutter are you on?  3.16.6 enforces iOS 12 https://github.com/flutter/flutter/issues/136060#issuecomment-1885787485 but you only told us "3.16.x".
