### ISSUE TITLE
Flutter iOS Impeller "Break on 'ImpellerValidationBreak' to inspect point of failure: Could not acquire current drawable."

### ISSUE THREAD

**Issue by danielL22** [flutter/flutter#142891]
### Steps to reproduce

1. Set FLTUseFlutterMetalLayer to 'true'
2. Set CADisableMinimumFrameDurationOnPhone to 'true'
3. Set FLTEnableWideGamut to 'true'
4. Use any Widget with an animation

### Expected results

Animation should perform smooth

### Actual results

Animation stops, error is reported in xcode and animation jumps to finished state after 1-2 seconds

I'm really sorry I can't provide any more information as for right now. I have a deadline to meet until end of this month and really dont have much time on creating a reproducable code sample. 

I still thought I should provide at least some info to that issue. If this is known or not helpfull at all just close that issue again. I can try to provide more info next month when my deadline is over and I have more time again.

Yesterday I was preparing my App for iOS and noticed heavy lags in all animations. I started googling and it seems its already known that this happens with Apples changes in Metal and current Flutter Impeller Engine? Well, if I understood this correctly.
Today I tried switching the flutter channel to beta and the lags where much less heavy. So I also experimented with the keys in the info.plist and noticed that if the "FLTEnableWideGamut" key is set to true the animations break and an error is reported in XCode: 
[ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not acquire current drawable.
Setting the key to false fixes the issue. Animations are not as smooth as on android though but better than on current stable branch.

Again, I'm really sorry I cant provide more info, I probably also wont be able to actively respond to this issue. I try my best to provide some more information as soon as possible.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.19.0-0.4.pre, on macOS 14.3 23D56 darwin-arm64,
    locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2.4)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@danielL22 
Can you provide us complete runnable reproducible code sample along with `flutter doctor -v` so that we can verify it further properly ?

**Comment by jonahwilliams** [comment]
Thanks for the bug report @danielL22 . The option you selected is currently experimental and while you're free to use it I don't recommend shipping with it
