### ISSUE TITLE
Google testing stuck in queueing for multiple days

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#142808]
### Type of Request

bug

### Infrastructure Environment

Google Testing

### What is happening?

[Please be descriptive.](https://github.com/flutter/flutter/pull/142524) has been stuck for multiple days

### Steps to reproduce

NA

### Expected results

Google testing to finish relatively quickly.

**Comment by ricardoamador** [comment]
Here's another example: https://github.com/flutter/flutter/pull/142334

**Comment by gmackall** [comment]
Another example here https://github.com/flutter/flutter/runs/21287795277

**Comment by CaseyHillers** [comment]
Tracking bug is in b/287507462. Initial investigation is tests that result in an infra error have a race condition where they end up never reporting a failed state.

As a workaround, Googlers can mark the PR as exempt on FRoB, and indicate it was an infra issue.

**Comment by Jasguerrero** [comment]
Marking as fixed due b/287507462 being fixed
