### ISSUE TITLE
Make Linux Template simpler/Have a gobject subclass FlutterApplication

### ISSUE THREAD

**Issue by jane400** [flutter/flutter#142920]
### Use case

Adding desktop-specific quirks more easily in the Flutter engine. 
- the titlebar is not needed on linux mobile environments like phosh, as the window isn't draggable and always maximised (so listening to XDG_CURRENT_DESKTOP and looking at a certain GSettings schema) 
- adding a headerbar manually if we're on GNOME (to integrate better into the platform style) (currently solved by having a code path in the template that forces a headerbar on wayland and strcmp the wm_name on X11) (I would like to change that for every flutter application, that the XDG_CURRENT_DESKTOP env variable is read instead)

### Proposal

The template seems like it's doing more and more stuff. I'm proposing that we create a Subclass of GtkApplication called FlApplication symmetrical to FlutterActivity on Android. This subclass should be extensible (so not final), that application developers can still override all the behavior they want. But the `_client` code of the template should be moved into that.

**Comment by jane400** [comment]
I'm willing to implement this, just want to hear from someone if they are interested in this.

**Comment by huycozy** [comment]
This is somewhat related/similar to https://github.com/flutter/flutter/issues/111453, could you check it and confirm?

**Comment by jane400** [comment]
It's related for sure, but only in the sense of making it easier to fix that issue.

**Comment by gspencergoog** [comment]
Yes, this seems interesting. We'd be happy to look at a PR if you're interested in implementing it.

cc @robert-ancell

**Comment by robert-ancell** [comment]
Sounds like a good idea to me!
