### ISSUE TITLE
Phase 1 (wave 2) upgrade iOS 17 devices

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#142940]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

Please upgrade the iphones connected to the following hosts to iOS 17:

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-3
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-6

Put host into quarantine before starting.

After upgrading, please also ensure device is paired and symbols cached:
* Open Xcode 15 from /opt/flutter/xcode/15a240d/XCode.app
* In the top bar, open Window > Device and Simulators
* The window that opens should show the connected device
* Accept the Trust dialog on the iPhone device
* If you get the dialog on the device twice, you may need to accept it once, disconnect, reconnect, and accept again.
* Wait for the yellow bar at the top of the Device and Simulators window to go away - It should take a minute or so to Copy cache symbols

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
Upgrading IOS 17 iPhone device for mac-3 & mac-6 have been completed and both iPhone devices are ready for service.
