### ISSUE TITLE
Investigate differences between iPhone 11 devices or hosts in staging vs prod pool

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#142989]
This change

https://github.com/flutter/flutter/commit/809a27ea6764510a3483797d2566965c1c0f1643

moved the benchmark `flutter_gallery__transition_perf_e2e_ios` from the prod pool to the staging pool. With only that change, SkiaPerf noted some significant changes to the benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1706047246&end=1707234104&keys=X5594dc78a7604c4378e5335bfbf9408d&requestType=0&selected=commit%3D39179%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dflutter_gallery__transition_perf_e2e_ios%252C&xbaroffset=39179

What are the differences between the staging environment and the prod environment that could explain this change?

cc @vashworth @yusuf-goog

**Comment by vashworth** [comment]
I think it's most likely because staging environment is exclusively iOS 17 devices - that's the only explanation I can think of

**Comment by zanderso** [comment]
@jonahwilliams Is this something you've seen between iOS 16 and 17 by any chance? cc @chinmaygarde

**Comment by vashworth** [comment]
I audited some other tests and can see a correlation of `99th_percentile_frame_rasterizer_time_millis` increasing when ran on iOS 17 devices

Here's another example:
https://flutter-flutter-perf.skia.org/e/?begin=1706940000&queries=arch%3Dintel%26branch%3Dmaster%26device_type%3DiPhone_11%26host_type%3Dmac%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26test%3Dtiles_scroll_perf_ios__timeline_summary&requestType=0

Tests where it spiked were all iOS 17:
* https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_ios%20tiles_scroll_perf_ios__timeline_summary/15503/overview
  * "99th_percentile_frame_rasterizer_time_millis": 24.968
* https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_ios%20tiles_scroll_perf_ios__timeline_summary/15504/overview
  * "99th_percentile_frame_rasterizer_time_millis": 25.574
* https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_ios%20tiles_scroll_perf_ios__timeline_summary/15505/overview
  * "99th_percentile_frame_rasterizer_time_millis": 25.932
* https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_ios%20tiles_scroll_perf_ios__timeline_summary/15508/overview
  * "99th_percentile_frame_rasterizer_time_millis": 24.984
* https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_ios%20tiles_scroll_perf_ios__timeline_summary/15515/overview
  * "99th_percentile_frame_rasterizer_time_millis": 25.271
  
So I'm pretty sure it's an iOS 17 issue

**Comment by vashworth** [comment]
@zanderso @jmagman Do you think we should stop upgrading device in prod to iOS 17 until this is resolved?

**Comment by jonahwilliams** [comment]
You should not stop the upgrade. The goal of the benchmarks is to be representative of the devices our users run on. If it has regressed then it has regressed

**Comment by vashworth** [comment]
I was planning to move `Mac_build_test  flutter_gallery__transition_perf_e2e_ios` back to prod, would it be beneficial to keep it in staging for now while this is investigated?

**Comment by jonahwilliams** [comment]
Slowdowns in devicelab benchmarks that aren't attributable to individual commits can't really be investigated

**Comment by vashworth** [comment]
I moved the test back to prod (https://github.com/flutter/flutter/pull/142987), so benchmarks will probably mostly go back to normal until we introduce more iOS 17 devices into prod.

**Comment by zanderso** [comment]
It sounds like this SkiaPerf alert was caused by a change to the environment and is not currently actionable, so I'll go ahead and close this issue.
