### ISSUE TITLE
[Impeller] Direct encode on Vulkan doesn't account for dynamic state.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#142943]
This reproduces as a validation error in `Play/RendererTest.CanRenderToTexture/Vulkan` and perhaps others. The error:
```
Trigger: Validation Error: [ VUID-vkCmdDraw-None-07839 ] Object 0: handle =
0x1208bed48, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle =
0xb6bee80000000073, name = Pipeline BoxFade Pipeline, type =
VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x56f23620 | vkCmdDraw():
VK_DYNAMIC_STATE_STENCIL_REFERENCE state not set for this command buffer. The
Vulkan spec states: If the bound graphics pipeline state was created with the
VK_DYNAMIC_STATE_STENCIL_REFERENCE dynamic state enabled, and if the current
stencilTestEnable state is VK_TRUE, then vkCmdSetStencilReference must have been
called in the current command buffer prior to this drawing command
(https://vulkan.lunarg.com/doc/view/1.3.268.1/mac/1.3-extensions/vkspec.html#VUID-vkCmdDraw-None-07839)
```

I believe this happens because there is no call to set the stencil reference value because that value is already present in the pipeline state object. Except, we have said that it will be dynamic. So, on the begin, we must read the value from the PSO and make an explicit encode call.

**Comment by chinmaygarde** [comment]
cc @jonahwilliams Looking into this now. Double checking my hypothesis.

**Comment by jonahwilliams** [comment]
We don't support dynamic state, so I'm not sure how direct encode would support it?

**Comment by jonahwilliams** [comment]
If you're adding support for conditionally enabling dynamic state, my recommendation would be to encode that in the caps / context state so that the render pass is constructed with the correct settings.

**Comment by chinmaygarde** [comment]
> We don't support dynamic state...

Yes, [we do](https://github.com/flutter/engine/blob/472df4138488eea7220967be29808398e6e8f545/impeller/renderer/backend/vulkan/pipeline_vk.cc#L201). Are you thinking of the extended dynamic states?

Though, I see `RenderPass::SetStencilReference` and its not on the PSO. So perhaps the default value has not been encoded?

**Comment by chinmaygarde** [comment]
> If you're adding support for conditionally enabling dynamic state

Nothing as fancy as that. Just saw this error on ToT and thought it was related a default value not being encoded.

**Comment by jonahwilliams** [comment]
Right, the extended dynamic state. But then why would this be related to direct encode if we always assume the same dynamic state settings?

**Comment by chinmaygarde** [comment]
Before direct encode, we always took the stencil reference value from the command and encoded it. Now, we encode when the render pass sets the reference. But perhaps this test is missing the default? Looking into it now. Need to stash a few things.

**Comment by jonahwilliams** [comment]
Ahh Ok. So the problem is that there is no longer a default stencil value. We could fix this easily by setting the stencil ref to zero - the same default as the command object -  in the render_pass_vk and render_pass_mtl constructor
