### ISSUE TITLE
[web][a11y]: Testing tools for flutter web

### ISSUE THREAD

**Issue by niteshsh4rma** [flutter/flutter#142982]
### Steps to reproduce

Are there any testing tools or extensions to test accessibility for flutter web applications?

### Actual results

All tools fails because no DOM is generated.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@niteshsh4rma 
Check the [documentation](https://docs.flutter.dev/ui/accessibility-and-internationalization/accessibility?tab=browsers#testing-accessibility-on-web) and see if it helps to answer your question.

**Comment by niteshsh4rma** [comment]
@darshankawar not helpful as such, because it creates only semantics tree which helps only for Aria label things, but there are other metrics as well like Contrast Ratio, Text Zooming etc.

**Comment by darshankawar** [comment]
For contrast ratio, you can follow-up in [this](https://github.com/flutter/flutter/issues/142973) issue.
For text zooming, probably [this](https://github.com/flutter/flutter/issues/97305) is similar.

Closing this issue. If you disagree, write in comments and I'll reopen it.
