### ISSUE TITLE
[web] a11y: Support windows high contrast settings

### ISSUE THREAD

**Issue by PatrickR315516** [flutter/flutter#142973]
### Use case

To increase the accessibility for web target, the flutter engine should support high contrast user settings in windows settings. 

### Proposal

Tested with flutter version: `Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.3803], locale de-DE)` 

![WindowsHighContrast1](https://github.com/flutter/flutter/assets/122024451/37ca736f-afc8-49d8-8da1-e927a9a15c44)
![WindowsSettings](https://github.com/flutter/flutter/assets/122024451/cd606f73-18c8-4abe-8b3b-f0fb645bf857)

Used the flutter demo project.

**Comment by yjbanov** [comment]
Deduplicating into https://github.com/flutter/flutter/issues/118853
