### ISSUE TITLE
android_defines_test passing even when no devices are found

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#142998]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8756889553112536529/+/u/run_android_defines_test/stdout

**Comment by godofredoc** [comment]
@zanderso FYI

**Comment by zanderso** [comment]
At the bottom of the logs I'm seeing this:
```
Task result:
{
  "success": false,
  "reason": "Task failed: DeviceException: No Android devices detected"
}


════════════════╡ ••• Finished task "android_defines_test" ••• ╞════════════════



══════════════╡ ••• Flaky status for "android_defines_test" ••• ╞═══════════════

Consistently failed across all 3 executions.
flaky: false
```

Does that not mean that the task failed?

**Comment by godofredoc** [comment]
That's correct but I'd expect the test step to be red 
![image](https://github.com/flutter/flutter/assets/54371434/7c6fd219-1b2a-40f4-b27c-3741cbc83d0a)

Not sure if the test_util.test is not propagating the exit code or the test itself is not reporting the proper exit code.

@keyonghan would you mind taking a look the test_util method?

**Comment by keyonghan** [comment]
Maybe related to our recent retry wrapper change. Taking a look.

**Comment by keyonghan** [comment]
It's not. It should be related to the exit code.

Another example where the step failed but shown as green: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20complex_layout_scroll_perf_impeller_gles__timeline_summary/98/overview

Another issue here is: the task is marked as `failed` in dashboard though the build is marked as `success`.
<img width="584" alt="Screenshot 2024-02-06 at 11 48 44 AM" src="https://github.com/flutter/flutter/assets/54558023/02f41736-c381-4989-bdcb-30bc95ef3c61">

**Comment by keyonghan** [comment]
The most recent tree red on `Linux analyzer_benchmark` has same issue. The test step fails but the build is `Succeed`.
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20analyzer_benchmark/7177/overview

**Comment by keyonghan** [comment]
Wondering if the sh/ps1 wrapper somehow hides the exit code in some corner cases.
https://flutter-review.googlesource.com/c/recipes/+/54763/7/recipe_modules/test_utils/api.py#137

**Comment by zanderso** [comment]
This seems to be a bit more widespread. I added @godofredoc and @keyonghan to a chat thread. Is there a recent change that should be reverted?

**Comment by keyonghan** [comment]
A fix is landing: https://flutter-review.googlesource.com/c/recipes/+/54925

**Comment by zanderso** [comment]
This probably needs a PSA to discord and flutter-team@.

**Comment by keyonghan** [comment]
Fix landed. Marking as resolved.
Correct status is now surfaced: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20technical_debt__cost/16684/overview

**Comment by vashworth** [comment]
@keyonghan Is this happening again?

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_arm64%20run_release_test_windows/1586/overview

Test shows as passed but logs indicate it failed and the tree is saying it failed:
```
Task result:
 {
   "success": false,
   "reason": "Task failed: Did not find expected line\n\nBuilt build\\windows\\x64\\runner\\Release\\app.exe\n\nin flutter run --release stdout\n\n[√ Built build\\windows\\x64\\runner\\Release\\ui.exe, , Flutter run key commands., h List all available interactive commands., c Clear the screen, q Quit (terminate the application on the device)., , Application finished.]\n"
 }
 Finished task "run_release_test_windows"
 Flaky status for "run_release_test_windows"
 Consistently failed across all 3 executions.
 flaky: false
 ```

**Comment by keyonghan** [comment]
We should add similar logic to windows (.ps1) file as well.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/54932 fixes the windows case. Please reopen if you see this again.
