### ISSUE TITLE
Add new win arm bots (win-17..20) into flutter prod pool

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#142948]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

Add the 4 new win arm hosts into the flutter prod pool.

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by godofredoc** [comment]
Closing as complete!!!
