### ISSUE TITLE
Stuck on "Flutter: Hot restarting..."

### ISSUE THREAD

**Issue by simplenotezy** [flutter/flutter#142983]
### Steps to reproduce

- Attempt to start a (larger ?) app in debug mode.
- Make some code changes
- Click "Restart" - sometimes a few times

### Expected results

It should restart every time without issues

### Actual results

It's often stuck in "Flutter: Hot restarting..." when making changes and then restarting.

It happens several times a day, seriously hindering developer productivity - and has done so for at least 12 months - on different (mainly ARM) setups, both to me and colleagues.

Related: https://github.com/flutter/flutter/issues/139651

### Code sample

I am willing to share our code-base with a flutter contributer, but apart from that I don't think theres anything concrete I can share to reproduce this issue.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/3786627/458be893-bbe4-4377-b746-adba6dd411b7

<img width="386" alt="image" src="https://github.com/flutter/flutter/assets/3786627/38c9b615-fecc-46b0-9bcf-d77fc4af000a">

</details>

### Logs

It's run through vs code - not sure how I can share the logs

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.1, on macOS 14.1.1 23B81 darwin-arm64, locale en-DK)
    • Flutter version 3.13.1 on channel stable at /Users/mf/fvm/versions/3.13.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (6 months ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mf/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008120-000210C63420C01E • ios            •
      iOS 17.1.2 21B101
    • Chrome (web)                         • chrome                    • web-javascript •
      Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@simplenotezy Hello again :)

Revisiting this issue, I think this maybe similar to https://github.com/Dart-Code/Dart-Code/issues/4958 which seems to have been fixed per https://github.com/Dart-Code/Dart-Code/issues/4958#issuecomment-1910990796, so please try upgrading to latest stable and check if you still get same behavior or not.

If you still get same behavior on latest stable, you will probably need to report in vscode's plugin dedicated repo.

**Comment by simplenotezy** [comment]
I'll continue the conversation here https://github.com/Dart-Code/Dart-Code/issues/4958

Thanks @darshankawar
