### ISSUE TITLE
`FocusManager` does not respond to changes in app lifecycle state

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#142929]
### Steps to reproduce

1. Open a Flutter app in Windows, MacOS, or Google Chrome
2. Click on a `TextField` (or any other widget that uses a `FocusNode`)
3. Click away from the window, and notice that the cursor doesn't stop blinking.

### Expected results

It doesn't matter whether I'm using Google Chrome, VS Code, Discord, or a Terminal window: any time a text cursor is blinking, it means that the characters I type will show up there.

And this isn't limited to text fields: if I repeatedly press `Tab` to navigate through a website, there's a visual indicator that goes away if I click away from the window, and it comes back if I click or `Alt+Tab` back into it.

### Actual results

Flutter apps do not follow this pattern.

### Code sample

```dart
Widget build(BuildContext context) {
  return TextField();
}
```

### Screenshots or Video

<details open>
<summary>GIF demonstration</summary>

Here's a recording of a Chrome window, as an example of how Flutter should behave:
![focus node](https://github.com/flutter/flutter/assets/10457200/bef42cd9-28e5-4214-b071-b7ef56b26609)

</details>

I've already implemented a fix and have opened a pull request: #142930

**Comment by huycozy** [comment]
Thanks for your report and PR. But I see there is a known issue being tracked at https://github.com/flutter/flutter/issues/87061. I will close this in favor of https://github.com/flutter/flutter/issues/87061, so please mention that issue on your PR. Thanks!
