### ISSUE TITLE
Regression in backdrop filter benchmark

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#142990]
SkiaPerf is flagging a couple of recent performance regressions in the backdrop filter benchmark on iPhone 11.

https://flutter-flutter-perf.skia.org/e/?begin=1703159098&end=1707198160&keys=X7ab4563cac63a71fe20c1025b2c2403d&requestType=0&selected=commit%3D39142%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=39142

cc @gaaclarke

**Comment by zanderso** [comment]
From chat @gaaclarke writes

> 1) The first regression is because we are using discrete steps for downsampling with round.  So some sigma values will be faster, some slower as the are rounded up to a lower scalar.
> 2) The second regression comes from an explicit decision to expand the band of sigmas that will evaluate to 1/8 scalar instead of 1/16.  This gives higher quality at the expense of more compute.  We have a constant we can adjust to tweak this if we want and it's somewhat arbitrarily set where I cranked it to the max and it looked good.
> 
> So here's followup items:
> 1) Testing just one sigma value is not going to be a good representation of the performance of the blur.  We should make sure to adjust the sigma in the benchmark.
> 2) I'll look at bringing down that constant to see if we can lower the 1/8->1/16 threshold a bit and still be happy with the results.
> I suspect that benchmark has sigmas in the range 50-100, otherwise that change shouldn't have been noticed

**Comment by gaaclarke** [comment]
Jonah made a good point that the less we downsample, the higher relative cost the downsampling pass has.  This is where potentially we'd want to sample directly from the mip level instead of downsampling.

**Comment by gaaclarke** [comment]
Right now my recommendation is that we get a few more datapoints after the "move 1/8->1/16 border" PR to get a better idea of where we are.

**Comment by gaaclarke** [comment]
I'm dropping the 1/8 to 1/16 barrier in https://github.com/flutter/engine/pull/50405.

Looking more closely at the test code I don't think it is using sigmas in that range though.  It looks like it is going sigma=[0, 16].  So I suspect the jump is noise in the test.  Fine tuning that value doesn't hurt though.

**Comment by gaaclarke** [comment]
<img width="1559" alt="Screenshot 2024-02-07 at 1 46 16 PM" src="https://github.com/flutter/flutter/assets/30870216/13afafc9-331e-4b93-8f23-71da92fa09d7">

Closing as expected and things are looking good, we had a bad sample that made it seem worse at first.

**Comment by gaaclarke** [comment]
Net result is ~40% faster.
