### ISSUE TITLE
--dart-define-from-file does not work with flutter build ipa

### ISSUE THREAD

**Issue by nayefradwi** [flutter/flutter#142976]
### Steps to reproduce

1. create a json/.env file for your environmental variables, for my case I have a `.staging.json` file in my project directory

2. run the following command
```
flutter build ipa --flavor staging --export-method=ad-hoc --dart-define-from-file=.staging.json
```

when I install the IPA the env variables do not load, how ever they work on android as well as running 
`flutter build ios --flavor staging --dart-define-from-file=.staging.json`, it seems pretty weird that specifically for IPA it does not work.

### Expected results

using `String.fromEnvironment("ENV_KEY")` should return the value based on the file

### Actual results

using `String.fromEnvironment("ENV_KEY")` returns an empty string

### Code sample

<details open><summary>Code sample</summary>

```dart
enum Flavor {
  dev,
  staging,
  prod;

  factory Flavor.fromString(String flavor) {
    // this throws an exception when using flutter build ipa
    return switch (flavor.toLowerCase().trim()) {
      "staging" => Flavor.staging,
      "prod" => Flavor.prod,
      "dev" => Flavor.dev,
      _ => throw Exception("Unknown flavor $flavor"),
    };
  }
}

const _flavor = String.fromEnvironment("FLAVOR");

Flavor getFlavor() {
  return Flavor.fromString(_flavor);
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-QA)
    • Flutter version 3.16.9 on channel stable at /Users/nayefmazen-mb/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/nayefmazen-mb/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/nayefmazen-mb/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/nayefmazen-mb/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Nayef’s iPhone (mobile) • 00008110-001845992652401E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Brave Browser 120.1.61.114

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the bug report @nayefradwi 
Maybe your issue is similar to https://github.com/flutter/flutter/issues/126901 that you can check and confirm.
Can you try by running `flutter run --flavor dev --dart-define=host=` and see if using it, you get same behavior or not ?
That way we can confirm that it may not be an issue only with `ipa`.

**Comment by nayefradwi** [comment]
> Thanks for the bug report @nayefradwi Maybe your issue is similar to #126901 that you can check and confirm. Can you try by running `flutter run --flavor dev --dart-define=host=` and see if using it, you get same behavior or not ? That way we can confirm that it may not be an issue only with `ipa`.

So I have run the following commands:
```
flutter run --flavor staging --dart-define=HOST="test"
flutter run --flavor staging --dart-define-from-file=.staging.json
flutter build ios --release --flavor staging --dart-define-from-file=.staging.json
flutter build apk --release --flavor staging --dart-define-from-file=.staging.json
```

they all seem to work fine and define the env variables from the json file correctly. However this command does not work: 
```
flutter build ipa --release --flavor staging --export-method=ad-hoc --dart-define-from-file=.staging.json
```

**Comment by darshankawar** [comment]
Thanks for the update @nayefradwi 
Can you provide us the file as you mentioned ?

> 1. create a json/.env file for your environmental variables, for my case I have a `.staging.json` file in my project directory

**Comment by nayefradwi** [comment]
@darshankawar here is the .staging.json
```json
{
    "FLAVOR": "staging",
    "BASE_HOST": "https://starlinkqatarstore.myshopify.com",
}
```

**Comment by darshankawar** [comment]
Thanks for the update. Using the details provided above, I was able to replicate the reported behavior only using `flutter build ipa` command.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.16.9, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.16.9 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.20.0-3.0.pre.19, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.20.0-3.0.pre.19 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db141ecd28 (60 minutes ago), 2024-02-06 20:00:08 -0800
    • Engine revision 808886312e
    • Dart version 3.4.0 (build 3.4.0-104.0.dev)
    • DevTools version 2.32.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by andrewkolos** [comment]
Rerouting to tool team since this is _probably_ a tool bug.

For whatever it's worth, the framework has a built-in constant, [appFlavor](https://api.flutter.dev/flutter/services/appFlavor-constant.html), that can be used to determine what flavor your app was run/built with in your Dart code.

**Comment by nayefradwi** [comment]
> Rerouting to the tools team since this is _probably_ a tool bug (the PR introducing the `--dart-define-from-file` feature was reviewed by the tools team).
> 
> For whatever it's worth, the framework has a built-in constant, [`appFlavor`](https://api.flutter.dev/flutter/services/appFlavor-constant.html), that can be used to determine what flavor your app was run/built with in your Dart code.

Thanks for letting me know about it. This would be useful if I only dependent on the appFlavor, how ever there are different environmental variables that are required. Do you suggest any workaround to this issue?

**Comment by kjxbyz** [comment]
The `ios/Flutter/Generated.xcconfig` file does not contain the variables defined in `--dart-define-from-file`

`flutter build ipa --export-options-plist=ios/xxx.plist --dart-define-from-file=xxx.json`

**Comment by den0206** [comment]
If you are using `dart-define-from-file` 
I found a very useful article. 
This setup worked perfectly with `3.19.0`!

https://zenn.dev/altiveinc/articles/separating-environments-in-flutter
Author(s). [@riscait](https://github.com/riscait)
(This article is Written in Japanese.)

## iOS
   - add scripts `ios/scripts/extract_dart_defines.sh`
``` sh
#!/bin/sh

# Specifies the file path to which the Dart define is written.
# We will create a file named `Dart-Defines.xcconfig`.
OUTPUT_FILE="${SRCROOT}/Flutter/Dart-Defines.xcconfig"
# The file is initially emptied so that the old properties do not remain when the contents of the Dart define are changed.
: > $OUTPUT_FILE

# This function decodes the Dart define.
function decode_url() { echo "${*}" | base64 --decode; }

IFS=',' read -r -a define_items <<<"$DART_DEFINES"

for index in "${!define_items[@]}"
do
    item=$(decode_url "${define_items[$index]}")
    # Dart definitions also include items that are automatically defined on the Flutter side. 
    # However, if we export those definitions, we will not be able to build due to errors, # so we do not output items that start with flutter or FLUTTER.
    lowercase_item=$(echo "$item" | tr '[:upper:]' '[:lower:]')
    if [[ $lowercase_item != flutter* ]]; then
        echo "$item" >> "$OUTPUT_FILE"
    fi
done
```

   - run scripts before build Xcode Product > Scheme > Edit Scheme > Pre-actions
      - add `${SRCROOT}/scripts/extract_dart_defines.sh`


<img  height ="300" alt="スクリーンショット 2024-02-17 10 48 30" src="https://github.com/flutter/flutter/assets/43921126/bd003b86-e070-45f1-b7fc-02af83ef54f3" >

   -  Allow command
      - `chmod 755 ios/scripts/extract_dart_defines.sh`

   - Include the generated files in `ios/Flutter/Debug.xcconfig` and `ios/Flutter/release.xcconfig`

```
// ios/Flutter/Debug.xcconfig
...
#include "Dart-Defines.xcconfig"
```

```
// ios/Flutter/release.xcconfig
...
#include "Dart-Defines.xcconfig"
```

Modify `info.plist` to change the display name

``` 
<key>CFBundleName</key>
<string>flutter_app_template</string>
<string>$(appName)</string>
<key>CFBundleDisplayName</key>
<string>$(appName)</string>
```

Modify `ios/Runner.xcodeproj/project.pbxproj` to change the ID

```
PRODUCT_BUNDLE_IDENTIFIER = "$(appId)";
```

## Android
   - Modify `android/app/build.gradle` to decode and receive Dart-defines.
``` gradle
// Declares a variable to contain the dart-define.
def dartDefines = [:];
if (project.hasProperty('dart-defines')) {
    // Decode dart-defines, which are comma-separated and encoded in Base64, and store them in a variable.
    dartDefines = dartDefines + project.property('dart-defines')
        .split(',')
        .collectEntries { entry ->
            def pair = new String(entry.decodeBase64(), 'UTF-8').split('=')
            [(pair.first()): pair.last()]
        }
}
...
...

defaultConfig {
    minSdkVersion flutter.minSdkVersion
    targetSdkVersion flutter.targetSdkVersion
    versionCode flutterVersionCode.toInteger()
    versionName flutterVersionName
     applicationId "${dartDefines.appId}"
     resValue "string", "app_name", "${dartDefines.appName}"
}
```

  - Modify `android/app/src/main/AndroidManifest.xml` to Change App DisplayName
 
``` xml
android:label="@string/app_name"
```


For more detailed information on Firebase, icons, etc., please see [the Article](https://zenn.dev/altiveinc/articles/separating-environments-in-flutter)!

**Comment by josh-burton** [comment]
> If you are using `dart-define-from-file` I found a very useful article. This setup worked perfectly with `3.19.0`
> 
> [zenn.dev/altiveinc/articles/separating-environments-in-flutter](https://zenn.dev/altiveinc/articles/separating-environments-in-flutter) Author(s). [@riscait](https://github.com/riscait) (This article is Written in Japanese.)
> 
> ### relation issue.
> * [`--dart-define-from-file` entries are available in the environment during Xcode build when they should not be #136444](https://github.com/flutter/flutter/issues/136444)
> * [Concerns Regarding the Removal of `--dart-define-from-file` Feature #138793](https://github.com/flutter/flutter/issues/138793)
> 
> ## iOS
> * add scripts `ios/scripts/extract_dart_defines.sh`
> 
> ```shell
> #!/bin/sh
> 
> # Specifies the file path to which the Dart define is written.
> # We will create a file named `Dart-Defines.xcconfig`.
> OUTPUT_FILE="${SRCROOT}/Flutter/Dart-Defines.xcconfig"
> # The file is initially emptied so that the old properties do not remain when the contents of the Dart define are changed.
> : > $OUTPUT_FILE
> 
> # This function decodes the Dart define.
> function decode_url() { echo "${*}" | base64 --decode; }
> 
> IFS=',' read -r -a define_items <<<"$DART_DEFINES"
> 
> for index in "${!define_items[@]}"
> do
>     item=$(decode_url "${define_items[$index]}")
>     # Dart definitions also include items that are automatically defined on the Flutter side. 
>     # However, if we export those definitions, we will not be able to build due to errors, # so we do not output items that start with flutter or FLUTTER.
>     lowercase_item=$(echo "$item" | tr '[:upper:]' '[:lower:]')
>     if [[ $lowercase_item != flutter* ]]; then
>         echo "$item" >> "$OUTPUT_FILE"
>     fi
> done
> ```
> 
> * run scripts before build Xcode Product > Scheme > Edit Scheme > Pre-actions
>   
>   * add `${SRCROOT}/scripts/extract_dart_defines.sh`
> 
> <img alt="スクリーンショット 2024-02-17 10 48 30" height="300" src="https://private-user-images.githubusercontent.com/43921126/305590039-bd003b86-e070-45f1-b7fc-02af83ef54f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTA3MzMsIm5iZiI6MTcwODE1MDQzMywicGF0aCI6Ii80MzkyMTEyNi8zMDU1OTAwMzktYmQwMDNiODYtZTA3MC00NWYxLWI3ZmMtMDJhZjgzZWY1NGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA2MTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZDg3MDJiOTMxMWNhNWQzYTUxYTZhYjRjMDJiYjM1M2NhMTI2ZDE3NDc4ODllOGM2MjYyNGU3NjM5MWNkZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0m-immnOzzguUMb6LUmO6Rk9QWvh0QHK3m_jeQ07MYc">
> * Allow command
>   
>   * `chmod 755 ios/scripts/extract_dart_defines.sh`
> * Include the generated files in `ios/Flutter/Debug.xcconfig` and `ios/Flutter/release.xcconfig`
> 
> ```
> // ios/Flutter/Debug.xcconfig
> ...
> #include "Dart-Defines.xcconfig"
> ```
> 
> ```
> // ios/Flutter/release.xcconfig
> ...
> #include "Dart-Defines.xcconfig"
> ```
> 
> Modify `info.plist` to change the display name (Replace key **appName** with your definition)
> 
> ```
> <key>CFBundleName</key>
> <string>flutter_app_template</string>
> <string>$(appName)</string>
> <key>CFBundleDisplayName</key>
> <string>$(appName)</string>
> ```
> 
> Modify `ios/Runner.xcodeproj/project.pbxproj` to change the ID (Replace key **appid** with your definition)
> 
> ```
> PRODUCT_BUNDLE_IDENTIFIER = "$(appId)";
> ```
> 
> ## Android
> * Modify `android/app/build.gradle` to decode and receive Dart-defines.
>   (Replace keys **appid**  & **appName** with your definition)
> 
> ```groovy-gradle
> // Declares a variable to contain the dart-define.
> def dartDefines = [:];
> if (project.hasProperty('dart-defines')) {
>     // Decode dart-defines, which are comma-separated and encoded in Base64, and store them in a variable.
>     dartDefines = dartDefines + project.property('dart-defines')
>         .split(',')
>         .collectEntries { entry ->
>             def pair = new String(entry.decodeBase64(), 'UTF-8').split('=')
>             [(pair.first()): pair.last()]
>         }
> }
> ...
> ...
> 
> defaultConfig {
>     ...
>      applicationId "${dartDefines.appId}"
>      resValue "string", "app_name", "${dartDefines.appName}"
> }
> ```
> 
> * Modify `android/app/src/main/AndroidManifest.xml` to Change App DisplayName
> 
> ```
> android:label="@string/app_name"
> ```
> 
> For more detailed information on Firebase, icons, etc., please see [the Article](https://zenn.dev/altiveinc/articles/separating-environments-in-flutter).

While it seems like this is what is needed to be able to use dart-defines-from-file variables in the native build systems after 3.19.0, I would argue that the tooling has taken a step backwards by excluding these variables.

The behaviour in 3.16.x was great and no extra steps were needed to use the dart defines variables in gradle or xcode.

**Comment by josh-burton** [comment]
I understand that it may have been confusing if dart-defines variables had the same name as native environment variables, so perhaps the fix should be to pass through each dart define variable to a native one but prefixed with `DART_DEFINES_`

**Comment by jeiea** [comment]
@reefki, it appears that your issue may be a duplicate and unrelated to this one. Please refer to #55870.

**Comment by nayefradwi** [comment]
for me upgrading to the latest flutter has worked 3.19.4

**Comment by abdullahalamodi** [comment]
> If you are using `dart-define-from-file` I found a very useful article. This setup worked perfectly with `3.19.0`
> 
> https://zenn.dev/altiveinc/articles/separating-environments-in-flutter Author(s). [@riscait](https://github.com/riscait) (This article is Written in Japanese.)
> 
> ### relation issue.
> * [`--dart-define-from-file` entries are available in the environment during Xcode build when they should not be #136444](https://github.com/flutter/flutter/issues/136444)
> * [Concerns Regarding the Removal of `--dart-define-from-file` Feature #138793](https://github.com/flutter/flutter/issues/138793)
> 
> ## iOS
> * add scripts `ios/scripts/extract_dart_defines.sh`
> 
> ```shell
> #!/bin/sh
> 
> # Specifies the file path to which the Dart define is written.
> # We will create a file named `Dart-Defines.xcconfig`.
> OUTPUT_FILE="${SRCROOT}/Flutter/Dart-Defines.xcconfig"
> # The file is initially emptied so that the old properties do not remain when the contents of the Dart define are changed.
> : > $OUTPUT_FILE
> 
> # This function decodes the Dart define.
> function decode_url() { echo "${*}" | base64 --decode; }
> 
> IFS=',' read -r -a define_items <<<"$DART_DEFINES"
> 
> for index in "${!define_items[@]}"
> do
>     item=$(decode_url "${define_items[$index]}")
>     # Dart definitions also include items that are automatically defined on the Flutter side. 
>     # However, if we export those definitions, we will not be able to build due to errors, # so we do not output items that start with flutter or FLUTTER.
>     lowercase_item=$(echo "$item" | tr '[:upper:]' '[:lower:]')
>     if [[ $lowercase_item != flutter* ]]; then
>         echo "$item" >> "$OUTPUT_FILE"
>     fi
> done
> ```
> 
> * run scripts before build Xcode Product > Scheme > Edit Scheme > Pre-actions
>   
>   * add `${SRCROOT}/scripts/extract_dart_defines.sh`
> 
> <img alt="スクリーンショット 2024-02-17 10 48 30" height="300" src="https://private-user-images.githubusercontent.com/43921126/305590039-bd003b86-e070-45f1-b7fc-02af83ef54f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTk3NTEsIm5iZiI6MTcxNjM5OTQ1MSwicGF0aCI6Ii80MzkyMTEyNi8zMDU1OTAwMzktYmQwMDNiODYtZTA3MC00NWYxLWI3ZmMtMDJhZjgzZWY1NGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE3MzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMWE3OGM5NjQ0NTU4MGJhN2ZjOGJlMTExYjI4OGFlZWUyMTI1NDEyZmM3Y2M0ZDBiM2I2OWRmMjk5M2RiZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rXdsqM4KnIZaVE1vMEOjbxGVUfattUefRMb_XLeCArM">
> * Allow command
>   
>   * `chmod 755 ios/scripts/extract_dart_defines.sh`
> * Include the generated files in `ios/Flutter/Debug.xcconfig` and `ios/Flutter/release.xcconfig`
> 
> ```
> // ios/Flutter/Debug.xcconfig
> ...
> #include "Dart-Defines.xcconfig"
> ```
> 
> ```
> // ios/Flutter/release.xcconfig
> ...
> #include "Dart-Defines.xcconfig"
> ```
> 
> Modify `info.plist` to change the display name (Replace key **appName** with your definition)
> 
> ```
> <key>CFBundleName</key>
> <string>flutter_app_template</string>
> <string>$(appName)</string>
> <key>CFBundleDisplayName</key>
> <string>$(appName)</string>
> ```
> 
> Modify `ios/Runner.xcodeproj/project.pbxproj` to change the ID (Replace key **appid** with your definition)
> 
> ```
> PRODUCT_BUNDLE_IDENTIFIER = "$(appId)";
> ```
> 
> ## Android
> * Modify `android/app/build.gradle` to decode and receive Dart-defines.
>   (Replace keys **appid**  & **appName** with your definition)
> 
> ```groovy-gradle
> // Declares a variable to contain the dart-define.
> def dartDefines = [:];
> if (project.hasProperty('dart-defines')) {
>     // Decode dart-defines, which are comma-separated and encoded in Base64, and store them in a variable.
>     dartDefines = dartDefines + project.property('dart-defines')
>         .split(',')
>         .collectEntries { entry ->
>             def pair = new String(entry.decodeBase64(), 'UTF-8').split('=')
>             [(pair.first()): pair.last()]
>         }
> }
> ...
> ...
> 
> defaultConfig {
>     ...
>      applicationId "${dartDefines.appId}"
>      resValue "string", "app_name", "${dartDefines.appName}"
> }
> ```
> 
> * Modify `android/app/src/main/AndroidManifest.xml` to Change App DisplayName
> 
> ```
> android:label="@string/app_name"
> ```
> 
> For more detailed information on Firebase, icons, etc., please see [the Article](https://zenn.dev/altiveinc/articles/separating-environments-in-flutter).

thank you this is incredible. making dart-define-from-file work again event with this tricky way is very appreciated.

**Comment by andrewkolos** [comment]
> for me upgrading to the latest flutter has worked 3.19.4

I'll be closing the issue since this appears to be resolved[^1]. Many of the recent here comments seem to have gone off topic and are instead discussing https://github.com/flutter/flutter/issues/139289 (and its predecessor, https://github.com/flutter/flutter/issues/138793) instead.

[^1]: https://github.com/flutter/flutter/issues/142976#issuecomment-2027095962
