### ISSUE TITLE
SnackBars show behind the keyboard

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#143]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Tuesday Aug 25, 2015 at 20:39 GMT_
_Originally opened as https://github.com/flutter/engine/issues/810_

----

Not sure if they're supposed to sit above the keyboard or what?  Or maybe we're supposed to use a different widget when the keyboard is visible?

I discovered this by entering an invalid number in the fitness app.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/j9brown"><img src="https://avatars.githubusercontent.com/u/102276?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [j9brown](https://github.com/j9brown)**
_Tuesday Aug 25, 2015 at 21:06 GMT_

----

FWIW, Android won't tell you whether the keyboard is visible.

So in general the application is left with deciding how it wants to deal
with incursions into its space by an IME or other parts of the system UI
based on other information provided during layout, particularly the content
insets.

The Android window manager provides the application with content inserts
which represent what part of the window will be visible.  The app may be
able to draw outside of that region but what it draws there may or may not
be visible since it might be covered by decorations like the status bar but
that's how translucent decorations work.  Typically the app will adjust its
content view's layout to fit that region (the framework can do this
automatically).

If you've got a snack bar, you'll want to anchor it to the bottom of the
content region of the window.

It may help to think of the app's layout as having both an outer decor part
(which contains the background and decor elements like the title bar which
fill the window) and an inner content part (which fits within the decor and
adjusts as the content region changes).

NB. I might be getting the details slightly wrong.  There are also
affordances for things like overscan regions but I think most of that is
hidden from the API.

See also:
https://developer.android.com/reference/android/view/View.html#setFitsSystemWindows(boolean)

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Monday Aug 31, 2015 at 21:14 GMT_

----

See also #147.

**Comment by mohammedhasna2015** [comment]
this worked for me : remove this line : resizeToAvoidBottomInset:false 
from Scaffold
