### ISSUE TITLE
AppDelegate.swift:4:1 'UIApplicationMain' is deprecated; this is an error in Swift 6

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#143044]
In Xcode 15.3 beta I see a deprecation warning in a newly created Flutter iOS Xcode project.  `@UIApplicationMain` was renamed to `@main` in Swift 5.3. 
```
AppDelegate.swift:4:1 'UIApplicationMain' is deprecated; this is an error in Swift 6
```
https://github.com/flutter/flutter/blob/db141ecd28e166b2ba0f4903c3fd9fb13e4eb1f3/packages/flutter_tools/templates/app_shared/ios-swift.tmpl/Runner/AppDelegate.swift#L4

We already require Xcode 14, and Swift 5.3 was introduced in Xcode 12.

I bet the same is needed for `@NSApplicationMain` but I didn't check.
https://github.com/flutter/flutter/blob/db141ecd28e166b2ba0f4903c3fd9fb13e4eb1f3/packages/flutter_tools/templates/app_shared/macos.tmpl/Runner/AppDelegate.swift#L4

I'm not sure if there are other implications to using `@main` instead of `@UIApplicationMain` (scene delegates?)

**Comment by hellohuanlin** [comment]
From https://stackoverflow.com/questions/67429098/what-is-the-differnce-between-main-and-uiapplicationmain

Looks like for our use case they are the same (we don't have a custom main class to annotate)

**Comment by christopherfujino** [comment]
cc @eliasyishak

**Comment by loic-sharma** [comment]
> I'm not sure if there are other implications to using @main instead of @UIApplicationMain (scene delegates?)

From: https://forums.swift.org/t/se-0383-deprecate-uiapplicationmain-and-nsapplicationmain/62375/9

> For example, one could go out of their way to declare a static func main() {} in their app delegate that, upon migration, would get automatically called instead of the main provided by an application delegate conformance:
> 
> ```swift
> @main // was @UIApplicationMain
> actor AppDelegate: NSObject, NSApplicationDelegate {
>   static func main() {
>     fatalError("oops")
>   }
> }
> ```
>
> They'd need to change the name of this function in addition to adopting the @main attribute to avoid the code exploding. This example would crash on launch, and a less contrived example wouldn't call UIApplicationMain or NSApplicationMain to set anything up, so I think the authors of such an implementation would catch it pretty quickly.

If we wanted to, we could guard against this by checking if the app delegate has something that looks like `static func main()`. However, I don't think that's a bit overboard - [Swift's migration doesn't bother to check this either](https://github.com/apple/swift/pull/62151/files#diff-3bc0cc994ca64e028b87cc642aa365c708aaefd346dceb500e5f8b7495af8b1f).
