### ISSUE TITLE
[webview] let WebViewController support `shouldInterceptRequest` for loading offline resources

### ISSUE THREAD

**Issue by JunhuaLin** [flutter/flutter#143053]
### Use case

[webview_flutter](https://github.com/flutter/packages/tree/main/packages/webview_flutter)

Let the WebVIew's WebViewController support shouldInterceptRequest for loading offline resources.

In WebView loading optimization, local resources will be used to replace network resources to provide webview loading speed. In this case, use the [shouldInterceptRequest](https://developer.android.com/reference/android/webkit/WebViewClient#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest)) of WebViewClient of Android WebView to replace resource request intercepting with local resources.

### Proposal

![image](https://github.com/flutter/flutter/assets/20511081/dd731815-e5c4-44e6-9d1e-5136ac4cae03)

**Comment by stuartmorgan** [comment]
Supporting this without a way of doing synchronous calls to Dart would be extremely cumbersome, so this would likely need to wait for if/when there is a solution for synchronously calling Dart code on the platform isolate.

**Comment by stuartmorgan** [comment]
I just noticed that this was already filed as https://github.com/flutter/flutter/issues/27896. Closing as a duplicate.
