### ISSUE TITLE
flutter application showing strange Behavior in release build.

### ISSUE THREAD

**Issue by shijinthottiyil** [flutter/flutter#143042]
### Steps to reproduce

1.flutter build apk --debug
2.flutter build apk --release

### Actual results

I'm working on a flutter Android Application. The app is working fine in debug mode. But when I take the release build using flutter build apk --release the app is not working as intended. I'm sharing the app screenshot both in debug build and release build for reference.

| debug | release | 
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/115061533/ec582bb8-880c-457e-8ca7-b6bdd16b6192" width="300" /> | <img src="https://github.com/flutter/flutter/assets/115061533/80a210de-2f1d-4f2a-8703-7ac6cb14b22b" width="300" /> |

### Flutter Doctor output

<details open>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.16.1, on Microsoft Windows [Version 10.0.22000.2538], locale en-AE)
    • Flutter version 3.16.1 on channel stable at C:\Users\WORK\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (2 months ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\WORK\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.23)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33214.272
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.86.0)
    • VS Code at C:\Users\WORK\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.85
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.98

[√] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @shijinthottiyil, thanks for filing this issue. Please provide a complete minimal reproducible code sample so that we can investigate this issue. 

Thank you

**Comment by shijinthottiyil** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:vazhipad/features/otp/view/otp_view.dart';
import 'package:vazhipad/features/widgets/auth_button_widget.dart';
import 'package:vazhipad/utils/ui/constants/app_assets.dart';
import 'package:vazhipad/utils/ui/constants/app_colors.dart';
import 'package:vazhipad/utils/ui/constants/app_spacing.dart';

class LoginView extends StatelessWidget {
  const LoginView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          width: context.width,
          height: context.height,
          margin: AppSpacing.padSH40,
          decoration: BoxDecoration(
              // color: Colors.red,
              ),
          child: SingleChildScrollView(
            child: Column(
              children: [
                AppSpacing.gapH150,
                Image.asset(
                  AppAssets.kLogo,
                  width: 250.w,
                  height: 110.h,
                ),
                AppSpacing.gapH36,
                Text(
                  'Log in or Sign up',
                  style: context.textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                AppSpacing.gapH48,
                Container(
                  height: 70.h,
                  alignment: Alignment.center,
                  padding: AppSpacing.gapPSH16,
                  decoration: ShapeDecoration(
                    shape: StadiumBorder(
                      side: BorderSide(
                        color: AppColors.kLightGray,
                      ),
                    ),
                    color: AppColors.kWhiteWhisper,
                  ),
                  child: TextField(
                    decoration: InputDecoration.collapsed(
                      hintText: 'Enter your number',
                    ),
                  ),
                ),
                AppSpacing.gapH40,
                AuthButtonWidget(
                  onTap: () {
                    Get.to(() => OtpView());
                  },
                  buttonName: 'Login',
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

I think the issue is because of the package flutter_screen_util

**Comment by shijinthottiyil** [comment]
I have removed the flutter_screen_util package still the issue persists

**Comment by shijinthottiyil** [comment]
removed the flutter screenutil package but still the issue persists. Now the app is stuck in a blank grey page.

**Comment by danagbemava-nc** [comment]
I see you're using `getx` & other third-party packages in your project, we will need a complete sample without the use of any of those packages to confirm that this is indeed an issue with the framework and not your code. 

Thank you

**Comment by dam-ease** [comment]
Thanks for your response @shijinthottiyil.
I removed third-party packages and codes and reduced the shared code to the code sample below.

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () {
        FocusManager.instance.primaryFocus?.unfocus();
      },
      child: MaterialApp(
        scrollBehavior: const ScrollBehavior()
            .copyWith(physics: const BouncingScrollPhysics()),
        home: const LoginView(),
      ),
    );
  }
}

class AppSpacing {
  AppSpacing._();

  // Width
  static const gapW4 = SizedBox(width: 4);
  static const gapW8 = SizedBox(width: 8);
  static const gapW12 = SizedBox(width: 12);
  static const gapW16 = SizedBox(width: 16);
  static const gapW20 = SizedBox(width: 20);
  static const gapW24 = SizedBox(width: 24);
  static const gapW28 = SizedBox(width: 28);
  static const gapW32 = SizedBox(width: 32);
  static const gapW36 = SizedBox(width: 36);
  static const gapW40 = SizedBox(width: 40);
  static const gapW44 = SizedBox(width: 44);
  static const gapW48 = SizedBox(width: 48);
  static const gapW52 = SizedBox(width: 52);
  static const gapW56 = SizedBox(width: 56);
  static const gapW60 = SizedBox(width: 60);
  static const gapW64 = SizedBox(width: 64);
  static const gapW100 = SizedBox(width: 100);

  // Height
  static const gapH4 = SizedBox(height: 4);
  static const gapH8 = SizedBox(height: 8);
  static const gapH12 = SizedBox(height: 12);
  static const gapH16 = SizedBox(height: 16);
  static const gapH20 = SizedBox(height: 20);
  static const gapH24 = SizedBox(height: 24);
  static const gapH28 = SizedBox(height: 28);
  static const gapH32 = SizedBox(height: 32);
  static const gapH36 = SizedBox(height: 36);
  static const gapH40 = SizedBox(height: 40);
  static const gapH44 = SizedBox(height: 44);
  static const gapH48 = SizedBox(height: 48);
  static const gapH52 = SizedBox(height: 52);
  static const gapH56 = SizedBox(height: 56);
  static const gapH60 = SizedBox(height: 60);
  static const gapH64 = SizedBox(height: 64);
  static const gapH80 = SizedBox(height: 80);
  static const gapH92 = SizedBox(height: 92);
  static const gapH100 = SizedBox(height: 100);
  static const gapH125 = SizedBox(height: 125);
  static const gapH150 = SizedBox(height: 150);
  static const gapH200 = SizedBox(height: 200);
  static const gapH250 = SizedBox(height: 250);

  // Padding
  static const gapPSH16 = EdgeInsets.symmetric(horizontal: 16);
  static const padSH40 = EdgeInsets.symmetric(horizontal: 40);
}

class LoginView extends StatelessWidget {
  const LoginView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          margin: AppSpacing.padSH40,
          decoration: const BoxDecoration(
              // color: Colors.red,
              ),
          child: SingleChildScrollView(
            child: Column(
              children: [
                AppSpacing.gapH150,
                Image.asset(
                  "assets/images/img.jpg",
                  width: 250,
                  height: 110,
                ),
                AppSpacing.gapH36,
                const Text(
                  'Log in or Sign up',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                AppSpacing.gapH48,
                Container(
                  height: 70,
                  alignment: Alignment.center,
                  padding: AppSpacing.gapPSH16,
                  decoration: const ShapeDecoration(
                    shape: StadiumBorder(
                      side: BorderSide(
                        color: Colors.grey,
                      ),
                    ),
                    color: Colors.white,
                  ),
                  child: const TextField(
                    decoration: InputDecoration.collapsed(
                      hintText: 'Enter your number',
                    ),
                  ),
                ),
                AppSpacing.gapH40,
                TextButton(onPressed: () {}, child: const Text("Login"))
              ],
            ),
          ),
        ),
      ),
    );
  }
}

``` 

</p>
</details> 

Running this, I'm unable to reproduce the issue you seem to be experiencing 

| Debug | Release |
|--------|--------|
| <img src="https://github.com/flutter/flutter/assets/53122008/74801291-b5e1-4040-955e-aac46a86713a"> | <img src="https://github.com/flutter/flutter/assets/53122008/8bca900b-58ac-4a29-af26-f3427cb98bf9"> | 

Can you please try with the code sample above to see if this issue still reproduces on your end?

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.16.9 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (2 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)            
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 Pro (mobile)      • 79E44FCE-BEA4-4C4B-9C1C-EFBD9964E172 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.20.0-4.0.pre.37, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.20.0-4.0.pre.37 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 720f73a4da (6 hours ago), 2024-02-08 00:19:37 -0500
    • Engine revision 22e1241e98
    • Dart version 3.4.0 (build 3.4.0-116.0.dev)
    • DevTools version 2.32.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)      • 00008110-001964480AE1801E            • ios            • iOS 17.1.1 21B91
    • iPhone 15 Pro (mobile)          • 79E44FCE-BEA4-4C4B-9C1C-EFBD9964E172 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by shijinthottiyil** [comment]
Yes this thing works fine. I have already tried this. But the problem here is that 
import 'package:flutter/material.dart';

class AppSpacing {
  AppSpacing._();

  // Width
  static const gapW4 = SizedBox(width: 4);
  static const gapW8 = SizedBox(width: 8);
  static const gapW12 = SizedBox(width: 12);
  static const gapW16 = SizedBox(width: 16);
  static const gapW20 = SizedBox(width: 20);
  static const gapW24 = SizedBox(width: 24);
  static const gapW28 = SizedBox(width: 28);
  static const gapW32 = SizedBox(width: 32);
  static const gapW36 = SizedBox(width: 36);
  static const gapW40 = SizedBox(width: 40);
  static const gapW44 = SizedBox(width: 44);
  static const gapW48 = SizedBox(width: 48);
  static const gapW52 = SizedBox(width: 52);
  static const gapW56 = SizedBox(width: 56);
  static const gapW60 = SizedBox(width: 60);
  static const gapW64 = SizedBox(width: 64);
  static const gapW100 = SizedBox(width: 100);

  // Height
  static const gapH4 = SizedBox(height: 4);
  static const gapH8 = SizedBox(height: 8);
  static const gapH12 = SizedBox(height: 12);
  static const gapH16 = SizedBox(height: 16);
  static const gapH20 = SizedBox(height: 20);
  static const gapH24 = SizedBox(height: 24);
  static const gapH28 = SizedBox(height: 28);
  static const gapH32 = SizedBox(height: 32);
  static const gapH36 = SizedBox(height: 36);
  static const gapH40 = SizedBox(height: 40);
  static const gapH44 = SizedBox(height: 44);
  static const gapH48 = SizedBox(height: 48);
  static const gapH52 = SizedBox(height: 52);
  static const gapH56 = SizedBox(height: 56);
  static const gapH60 = SizedBox(height: 60);
  static const gapH64 = SizedBox(height: 64);
  static const gapH80 = SizedBox(height: 80);
  static const gapH92 = SizedBox(height: 92);
  static const gapH100 = SizedBox(height: 100);
  static const gapH125 = SizedBox(height: 125);
  static const gapH150 = SizedBox(height: 150);
  static const gapH200 = SizedBox(height: 200);
  static const gapH250 = SizedBox(height: 250);

  // Padding
  static const gapPSH16 = EdgeInsets.symmetric(horizontal: 16);
  static const padSH40 = EdgeInsets.symmetric(horizontal: 40);
}
For example I have declared two late variables one is screenHeight and another one screenWidth and i have initialized these variables in the build method of the MyApp stless widget. Then an issue is shown in release build. Please not screenHeight, screenWidth variables are used inside AppSpacing class for making the app responsive.

**Comment by dam-ease** [comment]
Hello @shijinthottiyil.
Not too sure I understood your last comment. Please can you help with more information? The best way out will be by providing a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) i.e a single `main.dart` file as I shared in https://github.com/flutter/flutter/issues/143042#issuecomment-1934223645 that we can run at once on our end to reproduce your issue.
Thank you!

**Comment by shijinthottiyil** [comment]
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class AppSpacing {
  AppSpacing._();

  static late double screenWidth;
  static late double screenHeight ;

  // Width
  static final gapW4 = SizedBox(width: screenWidth * 0.02);
  static final gapW8 = SizedBox(width: screenWidth * 0.04);
  static final gapW12 = SizedBox(width: screenWidth * 0.06);
  static final gapW16 = SizedBox(width: screenWidth * 0.08);
  static final gapW20 = SizedBox(width: screenWidth * 0.1);
  static final gapW24 = SizedBox(width: screenWidth * 0.12);
  static final gapW28 = SizedBox(width: screenWidth * 0.14);
  static final gapW32 = SizedBox(width: screenWidth * 0.16);
  static final gapW36 = SizedBox(width: screenWidth * 0.18);
  static final gapW40 = SizedBox(width: screenWidth * 0.2);
  static final gapW44 = SizedBox(width: screenWidth * 0.22);
  static final gapW48 = SizedBox(width: screenWidth * 0.24);
  static final gapW52 = SizedBox(width: screenWidth * 0.26);
  static final gapW56 = SizedBox(width: screenWidth * 0.28);
  static final gapW60 = SizedBox(width: screenWidth * 0.3);
  static final gapW64 = SizedBox(width: screenWidth * 0.32);
  static final gapW100 = SizedBox(width: screenWidth * 0.5);

  // Height
  static final gapH4 = SizedBox(height: screenHeight * 0.02);
  static final gapH8 = SizedBox(height: screenHeight * 0.04);
  static final gapH12 = SizedBox(height: screenHeight * 0.06);
  static final gapH16 = SizedBox(height: screenHeight * 0.08);
  static final gapH20 = SizedBox(height: screenHeight * 0.1);
  static final gapH24 = SizedBox(height: screenHeight * 0.12);
  static final gapH28 = SizedBox(height: screenHeight * 0.14);
  static final gapH32 = SizedBox(height: screenHeight * 0.16);
  static final gapH36 = SizedBox(height: screenHeight * 0.18);
  static final gapH40 = SizedBox(height: screenHeight * 0.2);
  static final gapH44 = SizedBox(height: screenHeight * 0.22);
  static final gapH48 = SizedBox(height: screenHeight * 0.24);
  static final gapH52 = SizedBox(height: screenHeight * 0.26);
  static final gapH56 = SizedBox(height: screenHeight * 0.28);
  static final gapH60 = SizedBox(height: screenHeight * 0.3);
  static final gapH64 = SizedBox(height: screenHeight * 0.32);
  static final gapH80 = SizedBox(height: screenHeight * 0.4);
  static final gapH92 = SizedBox(height: screenHeight * 0.46);
  static final gapH100 = SizedBox(height: screenHeight * 0.5);
  static final gapH125 = SizedBox(height: screenHeight * 0.625);
  static final gapH150 = SizedBox(height: screenHeight * 0.75);
  static final gapH200 = SizedBox(height: screenHeight * 1.0);
  static final gapH250 = SizedBox(height: screenHeight * 1.25);

  // Padding
  static const gapPSH16 = EdgeInsets.symmetric(horizontal: 16);
  static const padSH40 = EdgeInsets.symmetric(horizontal: 40);
}


main.dart file 

initializing the two variables screenHeight and screenWidth and then using them later

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:vazhipad/features/login/view/login_view.dart';
import 'package:vazhipad/utils/ui/constants/app_spacing.dart';
import 'package:vazhipad/utils/ui/constants/app_theme.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
AppSpacing.screenWidth = MediaQuery.of(context).size.width;
AppSpacing.screenHeight = [MediaQuery.of(context).size.height;](s)
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () {
        FocusManager.instance.primaryFocus?.unfocus();
      },
      child: GetMaterialApp(
        scrollBehavior: const ScrollBehavior()
            .copyWith(physics: const BouncingScrollPhysics()),
        defaultTransition: Transition.cupertino,
        theme: AppTheme.lightTheme,
        home: const LoginView(),
      ),
    );
  }
}

later in release build if i use any of the variables from the AppSpacing class it showing unexpected behaviour

**Comment by bleroux** [comment]
In release mode, on Android, the first frame might be rendered with a window size sets to `Size.zero`.

This is intended for performance reason (waiting for the real size will delay the first frame). This is mentionned in https://api.flutter.dev/flutter/dart-ui/FlutterView/physicalSize.html.

The solution is to rely on `MediaQuery.of(context)` and to not save permanent values based on that.
In your code sample your rightly rely on `MediaQuery.of(context)` to get the screen width and height. But all the other variables are initialized once based on the first value of `screenHeight` or `screenHeight`.

The issue is particularly visible on release mode (because of the zero size that might be returned on fast devices) but it would also be reproducible on debug mode, for instance by going to landscape mode when using a device emulator or a real device. It would also be reproducible when launching the app as a desktop application and resizing the windows (this is my own preferred way to check responsiveness).

About the zero size at startup, I agree it is annoying (been there too), but the reasonning is to favor performance which is right. I proposed the following solution to mitigate this issue: https://github.com/flutter/flutter/issues/106858#issuecomment-1517733501. It might be implemented in the future.

**Comment by darshankawar** [comment]
Thanks for the insights @bleroux 
Also, @shijinthottiyil check [this](https://github.com/flutter/flutter/issues/36533#issuecomment-718699728) and see if it helps to understand the behavior properly.
