### ISSUE TITLE
Notifications about stalled autoroller PRs are not being sent

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#143009]
The Skia roll here https://github.com/flutter/engine/pull/50399 has been stalled for 4 hours. Following https://github.com/flutter/flutter/issues/125451, after 2 hours, the sheriff should have received an email notification, but @chinmaygarde is the sheriff this week, and did not receive an email.

cc @keyonghan

**Comment by keyonghan** [comment]
The alert was triggered around 10:40am
<img width="1320" alt="Screenshot 2024-02-06 at 1 09 17 PM" src="https://github.com/flutter/flutter/assets/54558023/65c17f52-2a59-46fd-a845-64c063263d2e">

Please double check the email with title containing keyword: `Stale engine PR`.

**Comment by zanderso** [comment]
@chinmaygarde could you double check?

**Comment by chinmaygarde** [comment]
Nope. I also checked all emails I received around the time of the trigger. Interestingly though, I did get an email saying that the trigger was fired. But that doesn't say what PR it was or any other information. Was this email directed to the right address?
<img width="1164" alt="Screenshot 2024-02-06 at 2 47 21 PM" src="https://github.com/flutter/flutter/assets/44085/20ac90c6-15f7-4647-8a20-bc5ed8bb6265">

**Comment by keyonghan** [comment]
The second email (in the pasted pic) is the alert email.
See the `Policy documentation` re how to find the detailed log. (unfortunately GCP alert doesn't provide a way to paste the log directly in the email alert).

**Comment by zanderso** [comment]
@keyonghan is there any way to edit the email subject line?

**Comment by keyonghan** [comment]
Unfortunately the subject is not customizable: b/261302137.
I tried including the alert details (the hanging PR info) in the email body with a variable ${textPayload}, but not sure if it works (not listed [here](https://cloud.google.com/monitoring/alerts/doc-variables)).

**Comment by zanderso** [comment]
kk. I will close this as not actionable.

**Comment by zanderso** [comment]
Re-opening this since this PR was stalled for 2 days and @jason-simmons did not receive the email: https://github.com/flutter/flutter/pull/143428.

**Comment by zanderso** [comment]
@keyonghan Could we have the alert sent to a mailing list in addition to the sheriff?

**Comment by keyonghan** [comment]
> Re-opening this since this PR was stalled for 2 days and @jason-simmons did not receive the email: #143428.

Huh, I see we did catch the hang in the log:
![Screenshot 2024-02-16 at 9 04 59 AM](https://github.com/flutter/flutter/assets/54558023/a9ffb5c2-290c-4cd3-94f1-897f80fe989a)

**Comment by keyonghan** [comment]
Ah, I see the issue. From the alert side, we are filtering **`engine`** repo...
I have fixed the filtering.

**Comment by keyonghan** [comment]
> @keyonghan Could we have the alert sent to a mailing list in addition to the sheriff?

What email list do you want to cc? This should be doable.

**Comment by zanderso** [comment]
@keyonghan I shared the address with you in internal chat.

**Comment by jason-simmons** [comment]
I just received a series of "Stale engine PR" alert emails related to the engine->framework roller failing.

The logs in the incident details console say:
`auto_submit: Pull request https://github.com/flutter/flutter/pull/143641 from flutter repo auto roller has been running over 2 hours due to: [flutter-gold]`.

But the PRs are actually being closed due to a Dart analyzer error.
(see https://github.com/flutter/flutter/pull/143641)

Also, the text payload field mentioned in https://github.com/flutter/flutter/issues/143009#issuecomment-1932541557 does not appear to be working.  The "Stale engine PR" email contains an `Unrecognized variable: textPayload` error.

**Comment by keyonghan** [comment]
Thanks @jason-simmons for the feedback.

1) For the series of alerts: the alert is configured to send alert email every 2 hours if the PR remains open (the check remains hanging). After the PR is closed, the alert email should stop too.
2) For the `textPayload` error, I have removed it from the email body to avoid confusion.

**Comment by keyonghan** [comment]
It should start sending alerts to the group as well. Please reopen if you see any other issues.
