### ISSUE TITLE
how can I rebuild the dropdowmmenu instantly after deleting the item  without closing it .

### ISSUE THREAD

**Issue by M-R-007** [flutter/flutter#143043]
### Use case

I have dropdownButton with dropdownMenuItem ,  I have a feature like on  longpress the item i get the popup  menu with delete option , once I delete the item I want  the item to be removed from the list instantly . It gets updated when I close and open dropdown again . 

### Proposal

<img width="300" alt="image" src="https://github.com/flutter/flutter/assets/144330704/efd79380-1b8b-4119-873a-ec259d7ab05f">

**Comment by devfemibadmus** [comment]
this is not a issue this is a how to, its off-topic

try below

```dart
// usual in ur DropDownButton
onChanged: (newValue) {
            setState(() {
              _selectedItem = newValue;
            });
          },
// ...other codes

// then in your popup menu

setState(() {
          _dropdownItems.remove(selectedItem);
          if (_selectedItem == selectedItem || _dropdownItems.isEmpty) {
            _selectedItem = null;
          }
        });
```

**Comment by devfemibadmus** [comment]
@M-R-007  fixed?
