### ISSUE TITLE
Tutorial on how to access sqlite in Flutter

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1430]
_From @sethladd on December 1, 2015 21:25_

sqlite is found in both Android and iOS. We can document and explain how to access sqlite from Flutter.

_Copied from original issue: flutter/website#104_

**Comment by FlutterIssues** [comment]
_From @abarth on December 1, 2015 21:30_

We first need to make it possible to access sqlite.

**Comment by FlutterIssues** [comment]
_From @sethladd on December 1, 2015 21:33_

Yes. :)  I'll open another issue for that.

See also: https://github.com/flutter/flutter/issues/654

**Comment by mit-mit** [comment]
Closing this: we plan on writing general documentation for how to write plugins (incl. a tutorial; tracked in https://github.com/flutter/flutter/issues/1432). That should be sufficient.

**Comment by alextekartik** [comment]
As I stumble on this issue, I created an experimental plugin that provide SQLite access for iOS and Android to show that it is definitely feasible: https://github.com/tekartik/sqflite.dart
