### ISSUE TITLE
In apple review they can still see debug tag!?

### ISSUE THREAD

**Issue by toknT** [flutter/flutter#143037]
### Steps to reproduce

Just build a ipa and submit it to apple review. Even I set  `debugShowCheckedModeBanner: false` , however we can't see the debug tag in our testfligh devices.

I know is a strange issue **but it really happen**.

#### Some info may help

May be it's an issue in apple's review system not flutter **they will review your old version's app even you seletct and resubmit a latest one ** . I had built an old version use `flutter build ipa` without `--release` flag , `debugShowCheckedModeBanner: false` in code and mistaked use a development certificate to sign that. Some of **their screenshot even contact the deleted feat in pre version**

### Expected results

the debug tag be removed

### Actual results

the debug tag still appear when applle reviewing it.

### Code sample

<details open><summary>Code sample</summary>

```dart
return MaterialApp(
      title: '***',
      themeMode: ThemeMode.light,
      debugShowCheckedModeBanner: false,
      theme: myLightTheme,
      // darkTheme: myDartTheme,
      initialRoute: '/',
      routes: {
        '/': (context) => const InitPage(),
        '/home': (context) => const HomePage(),
        '/user_upload': (context) => const UserUploadPage(),
        '/search': (context) => const SearchPage(),
        '/upload': (context) => const UploadPage(),
        '/me': (context) => const MePage(),
      },
    );
```

</details>

### Screenshots or Video

![build-bug](https://github.com/flutter/flutter/assets/15935037/a81ce981-49ed-43d0-8ac5-a981d83e6e4e)
![build-bug2](https://github.com/flutter/flutter/assets/15935037/03f737ff-0362-49bb-93b9-a2b562d64676)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```sh
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.7, on macOS 13.6.3 22G436 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.16.7 on channel stable at /Users/wangcheng/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (4 weeks ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.6.3 22G436 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.139
```

**Comment by dam-ease** [comment]
Hello @toknT 
Thanks for filing this.
Do you still reproduce this when you run `flutter build ipa —release` i.e. with the release flag?

**Comment by dam-ease** [comment]
Thanks for your response.
This looks similar to what was described in https://github.com/flutter/flutter/issues/52242 which was marked a Duplicate of https://github.com/flutter/flutter/issues/51673. Please check out the comment here  https://github.com/flutter/flutter/issues/51673#issuecomment-597215128 to see if it helps in your case?

**Comment by toknT** [comment]
> Thanks for your response. This looks similar to what was described in #52242 which was marked a Duplicate of #51673. Please check out the comment here [#51673 (comment)](https://github.com/flutter/flutter/issues/51673#issuecomment-597215128) to see if it helps in your case?

The app I built already has no debug banner in any mode release,debug or profile on both debug device and testflight device (even no development certificat in appple developer's account). So it's not similar.

Anyway I did these today.

- check the config in xcode again 
- built a new release after updated macos , xcode 
- submit a new apple review 

Let's wait the next review result.

**Comment by toknT** [comment]
Sorry , it's the screenshot in ios emulator has debug tag. I forget retake and upload them to Apple's store.(My company didnt provide ios devices meet the requirement of pixel so I take them on a emulator)
