### ISSUE TITLE
Windows build_tests timing out on "Install VS build" 

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#143018]
### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

Windows build_tests failing on Infra step "Install VS build" - times out

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_5_7/896/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_6_7/905/overview

Blocking framework tree

### Expected results

I expect step to pass

**Comment by vashworth** [comment]
Not sure if it's just flakey or happening consistently yet

**Comment by vashworth** [comment]
Seems to be happening repeatedly: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_5_7/897/overview

**Comment by vashworth** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/142197.

**Comment by godofredoc** [comment]
Moving to P1 as it is not blocking the tree.

**Comment by godofredoc** [comment]
I didn't see it was already closed.
