### ISSUE TITLE
`DevFS::update` has an optional parameter, `rootDirectoryPath` which is unused

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#143041]
https://github.com/flutter/flutter/blob/ac7879e2aa6de40afec1fe2af9730a8d55de3e06/packages/flutter_tools/lib/src/devfs.dart#L554-L575

`projectRootPath` is not used.

**Comment by jonahwilliams** [comment]
IIRC this was historical to a time when hot reload required us to copy source code to the device.
