### ISSUE TITLE
Dart processes not exiting in `flutter/engine` are hard to debug on CI

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143021]
### Type of Request

feature request

### Infrastructure Environment

I'm not sure.

### What is happening?

Example: https://github.com/flutter/engine/pull/50255/commits/c6e7b5ba4fbfe1c0da0c7595d8b4d33875986e2a.

I inherited a tool (a Dart script called `android_integration_tests.dart`), that has a bug where it never terminates on CI. I'm still not sure why, but figuring out that the problem was never terminating on CI (since it does terminate locally) was really hard to debug.

@keyonghan and @christopherfujino [asked me to file something](https://discord.com/channels/608014603317936148/1204129687245430794):

> Looks like the OS info is available in the beginning: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1936229/overview
> but not collected when timing out.
> Yeah, could you help file a bug to track OS info in the end?
>
> I thought I landed a recipe change to do this (log OS info after a time out). Let me look it up, and see if I just missed some edge case. 
> never mind, I guess I just did that for devicelab tests: https://flutter.googlesource.com/recipes/+/24cc8a0d05ff25f461d4aac5e48cc6f726d93627%5E!/#F8

**Comment by keyonghan** [comment]
We should set up a time out of the specific test (smaller than the build timeout) to allow the os info collection to run in the end.

**Comment by keyonghan** [comment]
Also, if this is related to an emulator crash, the test should be able to catch the crash and exit early.

**Comment by matanlurey** [comment]
Just to be clear my specific case was a _Dart_ script that _ran_ an emulator, but I don't think the emulator crashed.

**Comment by matanlurey** [comment]
Just to be clear my specific case was a _Dart_ script that _ran_ an emulator, but I don't think the emulator crashed.

**Comment by godofredoc** [comment]
Add default timeouts for global/build tests: https://flutter-review.googlesource.com/c/recipes/+/55162

**Comment by godofredoc** [comment]
@matanlurey infra changes and docs have landed, can you please help us assigning the appropriate timeouts to the emulator tests in the engine json config files?

**Comment by matanlurey** [comment]
> @matanlurey infra changes and docs have landed, can you please help us assigning the appropriate timeouts to the emulator tests in the engine json config files?

Yup, would love to do that - my only confusion is what to do if I'm happy with the default 1h timeout?

Just close this issue as done?

**Comment by godofredoc** [comment]
Yes, I believe we can close this bug as done, with enough time for the build to complete we will have access to the generic logs collection and process cleanup steps. We can also collect test specific logs updating the test script to collect any additional information and save it to "FLUTTER_LOGS_DIR" https://github.com/flutter/engine/blob/main/ci/builders/README.md#tests.

The defaults for tests steps are now:

* 3 retries on failures.
* 30 mins timeout

If a test times out it will retry it automatically, if you are ok with the default 30 mins test timeout then my only recommendation would be to increase the [build timeout](https://github.com/flutter/engine/blob/main/.ci.yaml#L61) to something that allows enough time for the logs collection step to run. In this case something like 120 mins.

With enough time for the build to complete the dart processes being killed will be available in the cleanup step:

![image](https://github.com/flutter/flutter/assets/54371434/d23b94d9-6c15-4ca5-b62e-3af53e41304a)

**Comment by matanlurey** [comment]
Perfect! This is great, thanks all!
