### ISSUE TITLE
GitHub check doesn't display special characters correctly

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#143162]
### Type of Request

bug

### Infrastructure Environment

LUCI + Github

### What is happening?

LUCI error output in GitHub doesn't display all characters correctly.

<img width="709" alt="image" src="https://github.com/flutter/flutter/assets/6655696/c0808ae5-6f41-4c79-938e-25bff1156fe6">
 in LUCI

looks like 

<img width="1332" alt="image" src="https://github.com/flutter/flutter/assets/6655696/89a867e5-97a5-4e24-8a83-a20e9800a4e1">

in GitHub checks

### Steps to reproduce

1. Get a failed flutter-dashboard / LUCI check on a PR, e.g. https://github.com/flutter/flutter/pull/143130/checks?check_run_id=21348700368

### Expected results

I expect to be able to see the LUCI output with correct characters

**Comment by godofredoc** [comment]
Similar issues: 
* https://github.com/flutter/flutter/issues/117099
* https://github.com/flutter/flutter/issues/126942

**Comment by godofredoc** [comment]
This is fixed now. Some examples:

* https://github.com/flutter/flutter/pull/145850/checks?check_run_id=23167576764
* https://github.com/flutter/flutter/pull/145850/checks?check_run_id=23180862179
* https://github.com/flutter/flutter/pull/145850/checks?check_run_id=23167571102

**Comment by godofredoc** [comment]
@Hixie @goderbauer @christopherfujino after two years, several fixes in test runners, bash/powershell script wrappers and backend services I am happy to announce the special characters are now being presented correctly in the GitHub UI.

**Comment by godofredoc** [comment]
Recipes CL: https://flutter-review.googlesource.com/c/recipes/+/56720

**Comment by goderbauer** [comment]
Nice! Should this issue be closed then? Or is there more to do?

**Comment by guidezpl** [comment]
Unfortunately, this seemed to have pop back up, reopening the issue.

 https://github.com/flutter/flutter/pull/148408/checks?check_run_id=25001247171

<img width="545" alt="image" src="https://github.com/flutter/flutter/assets/6655696/6a405885-25d1-496d-ad31-1e6946e9464c">
