### ISSUE TITLE
Remove use of deprecated UnmodifiableUint8ListView API in image_picker_platform_interface package

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#143113]
Some unmodifiable typed data list view APIs were deprecated in https://dart.googlesource.com/sdk/+/7ef215a4a5ec884dd147c51a0a87c2a7d35a4b94

The new API (`Uint8List.asUnmodifiableView`) is available in Dart 3.3.0.

https://github.com/flutter/packages/blob/main/packages/image_picker/image_picker_platform_interface/lib/src/types/picked_file/html.dart is using `UnmodifiableUint8ListView` and needs to be migrated.

**Comment by ditman** [comment]
I've fixed this, but the offending code is in a type that should be used only by a version of the API that we deprecated a long time ago. All users should be using methods that return `XFile` (from `package:cross_file`), rather than the `PickedFile` that is internal to this package only.
