### ISSUE TITLE
The class 'SingleTickerProviderStateMixin' can't be used as a mixin because it extends a class other than Object. (mixin_inherits_from_not_object)

### ISSUE THREAD

**Issue by stevenroose** [flutter/flutter#14317]

**Comment by sroddy** [comment]
I think it’s a problem with your analysis_options file. You need to enable them otherwise the analyzer will complain.
I suggest you to copy the one from flutter repo to start with and maybe remove some of the stricter constraints

**Comment by sroddy** [comment]
The flag is this one:

enableSuperMixins: true

**Comment by stevenroose** [comment]
I just have strong mode on without anything else. So Flutter is incompatible with string mode, then?

**Comment by mraleph** [comment]
This is not related to strong mode, but rather to how mixins were specified in Dart 1 - where it was indeed illegal to have a mixin extend anything other than an Object. This requirement was since relaxed (see dart-lang/sdk#23770), but the relaxation is not yet enabled by default - you have to enable it yourself via `enableSuperMixins` flag.

**Comment by mraleph** [comment]
@slightfoot the real solution is to enable super-mixins feature like so:

```
analyzer:
  language:
    enableSuperMixins: true
```

See https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml

**Comment by slightfoot** [comment]
@mraleph ahh good to know. I was trying with underscores ;) doh.

**Comment by dyardyGIT** [comment]
Restart vscode after creating analysis_options.yaml file

**Comment by alamboley** [comment]
Having the issue myself with latest flutter beta channel. Having all the files `analysis_options_repo.yaml`, `analysis_options_user.yaml` and `analysis_options.yaml` with `enableSuperMixins: true`.

Like @slightfoot mentioned, I create a file named `analysis_options.yaml` in the same directory as pubspec.yaml and everything works fine.

**Comment by ArcticZeroo** [comment]
I also cannot use `enableSuperMixins: true`, the Dart Analysis server says the option is not recognized

**Comment by zoechi** [comment]
@ArcticZeroo you might have configured the wrong Dart SDK in your IntelliJ Dart Plugin settings

**Comment by zoechi** [comment]
Do you have it under analyzer > language ?
 
```yml
analyzer:
  language:
    enableSuperMixins: true
```

**Comment by ArcticZeroo** [comment]
@zoechi yep, that is the exact layout of my analysis file

**Comment by zoechi** [comment]
Actually I have my doubts. 
I can only reproduce your error if I remove the `language:` node.
With the language node, there is no way to get the error for line 2

**Comment by ArcticZeroo** [comment]
@zoechi idunno, maybe it has the analysis file cached? Because I didn't have the language node the first time I restarted it, then I added the node and it's still been giving me the warning. I'll try again in a few hours I suppose -- not home right now to restart it again.

The analysis file is certainly set properly though on the most recent revision.

**Comment by zoechi** [comment]
There is a `~/.dart-server` directory with a subdirectory containing ~20k files.
If you delete it it will be recreated. Also not on my computer for more accurate info.

**Comment by allandaleho** [comment]
I'm not sure if this is the right place to ask. I tried updating one of my Flutter projects to use built_value and I notice after sometime that there was an issue with my implementation of SingleTickerProviderStateMixin

I tried checking the analysis_options.yaml and enableSuperMixins was set to true, I also checked another project that uses SingleTickerProviderStateMixin and it doesn't complain on that project.

Hope anyone replies.

**Comment by zoechi** [comment]
@allandaleho 

>  I notice after sometime that there was an issue with my implementation of SingleTickerProviderStateMixin

That's quite vague. This issue is closed since a while. Can you please create a new issue with full information that allows to reproduce?

**Comment by mit-mit** [comment]
As of Dart 2.1 -- and it's support for [super mixins](https://github.com/dart-lang/language/issues/7) -- no flags are needed to support mixins that extend from other classes.

**Comment by Xbobo5530** [comment]
> Do you have it under analyzer > language ?
> 
> ```yaml
> analyzer:
>   language:
>     enableSuperMixins: true
> ```

sow where exactly should this be added??

**Comment by zoechi** [comment]
@Xbobo5530 that's obsolete. Update to a newer Flutter version (perhaps `dev` channel until a new `beta` comes out).

**Comment by Xbobo5530** [comment]
Thanks ... I did an update...and now the Dart analyser still throws the warning though the app runs fine. I guess I'll just wait out the beta

**Comment by ifrankyu** [comment]
same problem.
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.11.4-pre.5, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.29.0)
[✓] Connected device (1 available)

**Comment by zoechi** [comment]
@ifrankyu use `mixin UserModel` instead of `abstract class UserModel`

**Comment by stonkeep** [comment]
> @slightfoot the real solution is to enable super-mixins feature like so:
> 
> ```
> analyzer:
>   language:
>     enableSuperMixins: true
> ```
> See https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml

not working for me 
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)

**Comment by zoechi** [comment]
@rafbanaan please check https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by rafbanaan** [comment]
@zoechi Did the repair, but I still receive the error. It was also a fresh install.

```
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (5 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.195], locale en-BE)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
```

**Comment by zoechi** [comment]
@rafbanaan I'd suggest to create a new issue with properly filled issue template and as much information as possible that would allow us to reproduce like a runnable code example that leads to the error.

**Comment by bulgariamitko** [comment]
i am getting the same error:

Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (преди 5 седмици) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by rafbanaan** [comment]
@bulgariamitko I got it fixed. There was a mistake at my side. I was still using the class and extends in stead of the mixin and on notation.

**Comment by bulgariamitko** [comment]
@rafbanaan , this is my code 

`class MainModel extends Model with ConnectedProductsModel, UserModel, ProductsModel {
}
`

`class ConnectedProductsModel extends Model {
  List<Product> _products = [];
  User _authenticatedUser;
  int _selProductIndex;
  ...
}`

where am I mistaking?

**Comment by rafbanaan** [comment]
@bulgariamitko Udemy Flutter course I see :p 

class ConnectedProductsModel extends Model

Should be

mixin ConnectedProductsModel on Model

**Comment by bulgariamitko** [comment]
@rafbanaan , yes i am still learning :) 

I can fix this error like you suggest, but after that i get other error on:
`class ProductsModel extends ConnectedProductsModel {`
**Classes can only extend other classes**

and now I am in the cycle of death :(

**Comment by zoechi** [comment]
If you make it a plugin, then you can't extend it. Use `class ProductsModel extends Object with ConnectedProductsModel` (not sure if `extends Object` is still required)

**Comment by bulgariamitko** [comment]
after doing that @zoechi i am getting `error: The class doesn't implement the required class 'Model'. (mixin_application_not_implemented_interface at [flutter_course] lib/scoped_models/connected_products.dart:35)` and also `error: Missing concrete implementations of Model.addListener, Model.notifyListeners, Model.removeListener and getter Model.listenerCount. (non_abstract_class_inherits_abstract_member_four at [flutter_course] lib/scoped_models/connected_products.dart:35)`

**Comment by zoechi** [comment]
@bulgariamitko I'd suggest to move the question to StackOverflow with a proper question that contains the related code. I can't make any sense from the fragments above and this is not the right place.

**Comment by bulgariamitko** [comment]
i get that, @zoechi , i just have one question is it possible after upgrading to dart 2.1 to get those errors or i am mistaking?

**Comment by rafbanaan** [comment]
@bulgariamitko You have to also for that. Everywhere in the ConnectedProducts file. So for ProductModel, Usermodel and UtilityModel.

**Comment by bulgariamitko** [comment]
after changing to 
`class MainModel extends Model with ConnectedProductsModel, UserModel, ProductsModel {`
and
`mixin ConnectedProductsModel on Model {`
`mixin ProductsModel on ConnectedProductsModel {`
`mixin UserModel on ConnectedProductsModel {`

i dont have any errors, thanks for the help!

**Comment by realtebo** [comment]
@bulgariamitko what is `ConnectedProductsModel` ?

**Comment by bulgariamitko** [comment]
@realtebo, this is my project related class. It seems when you get this error it is something you mix up with your code and there is nothing to do with error in the source code, so this issue should be in github at all to be honest. this should be a stackoverflow question.

**Comment by lanrehnics** [comment]
> after changing to
> `class MainModel extends Model with ConnectedProductsModel, UserModel, ProductsModel {`
> and
> `mixin ConnectedProductsModel on Model {`
> `mixin ProductsModel on ConnectedProductsModel {`
> `mixin UserModel on ConnectedProductsModel {`
> 
> i dont have any errors, thanks for the help!

Just to note here arrangement really matters .. BaseClass must come first before the classes extending..
