### ISSUE TITLE
skwasm errors in wonderous

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#143185]
Building & Running wonderous app similar to instructions given [here](https://github.com/dart-lang/sdk/issues/54845) but with the newest Dart SDK commit.

After some browsing, going to terminal and coming back to chrome I saw this skwasm error:

<img width="1648" alt="Screenshot 2024-02-08 at 22 14 44" src="https://github.com/flutter/flutter/assets/5757092/bf9c0c9c-87ee-40e1-b7c7-126dcc42bf99">
<img width="1677" alt="Screenshot 2024-02-08 at 22 16 13" src="https://github.com/flutter/flutter/assets/5757092/28bca05f-797e-47b3-827b-48ae75382d21">

/cc @eyebrowsoffire @mit-mit @kevmoo

**Comment by eyebrowsoffire** [comment]
I believe this is a duplicate of https://github.com/flutter/flutter/issues/140504
