### ISSUE TITLE
TabBar builds short-lived states for tabs in between transitions

### ISSUE THREAD

**Issue by stevenroose** [flutter/flutter#14316]
When going from tab 1 to tab 3 (by tapping on tab 3), the state for tab 2 gets built and immediately disposed. This is because the TabBarView swipes through the tabs like one continuous view.

This is kind of weird behavior. While possibly intentional, it's also cumbersome, especially for stateful widgets. This kind of overlaps with https://github.com/flutter/flutter/issues/13080: if the state of the tabs would be retained, it would make sense to slide over intermediate tabs, but since the state is disposed immediately, it makes little sense.

In my specific case, I load an async resource in `initState` and call `setState` on the callback from the future. However, the state is already disposed of at that time, causing a crash.

**Comment by Hixie** [comment]
You should always cancel async work in the dispose() method (or, at least, not call `setState` if `mounted` is false), this is just helping you find a bug. ;-)

What happens if you have more than three tabs? I am surprised we do this. This is definitely not intentional.

**Comment by atfa** [comment]
> You should always cancel async work in the dispose() method (or, at least, not call `setState` if `mounted` is false), this is just helping you find a bug. ;-)
> 
> What happens if you have more than three tabs? I am surprised we do this. This is definitely not intentional.

If we have 4 tabs, and now we are on 1st one, we click tab 4, Flutter will:
1. tab 1 init
2. tab 3 dispose
3. tab 3 init
4. tab 1 dispose

Flutter's TabBar and TabView confused me. My tabs will be reload even I am using AutomaticKeepAliveClientMixin on every tab page.

**Comment by devfelipereis** [comment]
I have the same issue.

**Comment by li7228166** [comment]
I have the same issue.

**Comment by TOTOROYang** [comment]
> > You should always cancel async work in the dispose() method (or, at least, not call `setState` if `mounted` is false), this is just helping you find a bug. ;-)
> > What happens if you have more than three tabs? I am surprised we do this. This is definitely not intentional.
> 
> If we have 4 tabs, and now we are on 1st one, we click tab 4, Flutter will:
> 
> 1. tab 1 init
> 2. tab 3 dispose
> 3. tab 3 init
> 4. tab 1 dispose
> 
> Flutter's TabBar and TabView confused me. My tabs will be reload even I am using AutomaticKeepAliveClientMixin on every tab page.

same issue

**Comment by orischwartz** [comment]
Minimal runnable reproduction in https://github.com/flutter/flutter/issues/29225#issuecomment-479542107

**Comment by xb284524239** [comment]
I have this issue too.

**Comment by xb284524239** [comment]
I found a way to solve this problem. Here's my code below, you can try it:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Don't rebuilt!",
      theme: ThemeData(primarySwatch: Colors.blue),
      home: FirstPage(),
    );
  }
}

class FirstPage extends StatelessWidget {
  FirstPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("I'm the first page")),
        body: Center(
          child: RaisedButton(
            child: Text("go to the tab page"),
            onPressed: () => Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => MyTabPage(),
                  ),
                ),
          ),
        ));
  }
}

class MyTabPage extends StatefulWidget {
  MyTabPage({Key key}) : super(key: key);
  @override
  _MyTabPageState createState() => _MyTabPageState();
}

class _MyTabPageState extends State<MyTabPage> with SingleTickerProviderStateMixin {
  TabController _tabController;

  int _currentTabIndex = 0;
  List<Widget> _realPages = [Tab1(), Tab2(), Tab3(), Tab4()];

  //lazy init
  List<Widget> _tabPages = [Tab1(), Container(), Container(), Container()];
  List<bool> _hasInit = [true, false, false, false];

  List<Widget> _tabsButton = [
    Tab(child: Text("tab1", style: TextStyle(color: Colors.black))),
    Tab(child: Text("tab2", style: TextStyle(color: Colors.black))),
    Tab(child: Text("tab3", style: TextStyle(color: Colors.black))),
    Tab(child: Text("tab4", style: TextStyle(color: Colors.black))),
  ];

  @override
  void initState() {
    print("MyTabPage initState.");
    super.initState();
    _tabController = TabController(length: _realPages.length, vsync: this)
      ..addListener(() {
        int selectedIndex = _tabController.index;
        if (_currentTabIndex != selectedIndex) {
          if (!_hasInit[selectedIndex]) {
            //lazy init
            _tabPages[selectedIndex] = _realPages[selectedIndex];
            _hasInit[selectedIndex] = true;
          }
          setState(() => _currentTabIndex = selectedIndex);
        }
      });
  }

  @override
  void dispose() {
    print("MyTabPage dispose.");
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Don't rebuilt!")),
      body: IndexedStack(index: _currentTabIndex, children: _tabPages),
      bottomNavigationBar: TabBar(controller: _tabController, tabs: _tabsButton),
    );
  }
}

class Tab1 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _Tab1State();
  }
}

class _Tab1State extends State<Tab1> {
  @override
  void initState() {
    super.initState();
    print("tab1 initState");
  }

  @override
  void dispose() {
    print("tab1 dispose");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Center(child: Text("I'm tab1")));
  }
}

class Tab2 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _Tab2State();
  }
}

class _Tab2State extends State<Tab2> {
  @override
  void initState() {
    super.initState();
    print("tab2 initState");
  }

  @override
  void dispose() {
    print("tab2 dispose");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Center(child: Text("I'm tab2")));
  }
}

class Tab3 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _Tab3State();
  }
}

class _Tab3State extends State<Tab3> {
  @override
  void initState() {
    super.initState();
    print("tab3 initState");
  }

  @override
  void dispose() {
    print("tab3 dispose");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Center(child: Text("I'm tab3")));
  }
}

class Tab4 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _Tab4State();
  }
}

class _Tab4State extends State<Tab4> {
  @override
  void initState() {
    super.initState();
    print("tab4 initState");
  }

  @override
  void dispose() {
    print("tab4 dispose");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: Center(child: Text("I'm tab4")));
  }
}

``` ```

``` log
I/flutter (21209): MyTabPage initState.
I/flutter (21209): tab1 initState
I/flutter (21209): tab3 initState
I/flutter (21209): tab2 initState
I/flutter (21209): tab4 initState
I/flutter (21209): tab1 dispose
I/flutter (21209): tab2 dispose
I/flutter (21209): tab3 dispose
I/flutter (21209): tab4 dispose
I/flutter (21209): MyTabPage dispose.

**Comment by besserwisser** [comment]
Can you elaborate what solved the issue? Just posting the whole app code is not a good way to share your findings...

**Comment by serkanince** [comment]
I have the same issue

**Comment by gitfornncn** [comment]
I have the same issue

**Comment by aytunch** [comment]
@besserwisser  I guess `IndexedStack` did the trick for that code. Which in my opinion defeats the purpose..

**Comment by boucoding** [comment]
same issue

**Comment by akshg05** [comment]
This needs to be looked into. Surprised no one has had taken this up yet in two years!

**Comment by boucoding** [comment]
I have solved this issue by using indexed stack widget and prevent creating new states when navigate occurs

**Comment by dungnv2602** [comment]
> I have solved this issue by using indexed stack widget and prevent creating new states when navigate occurs

IndexedStack => No Swipe => Not A Clean Solution

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (9 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

``` 

</details>

**Comment by febg11** [comment]
This was a problem last year... Still happening even now. Is there any chance of a fix soon?

**Comment by febg11** [comment]
Sorry but I was wondering how long does a bug with the P4 label take to get fixed?

**Comment by liyuqian** [comment]
"Customer: dream (g3)" is reporting the same issue in b/158727949. This could significantly impact the performance when the tab is expensive to build as we're building a tab unnecessary twice.

Specifically, I believe the unnecessary build is triggered by the transition animation as follows.

Suppose we're currently in `a`-th tab with content `A` and are transitioning to `b`-th tab with content `B` where index `a + 1 < b` (they're at least 2 tabs apart).

Flutter first swaps `a`-th tab with `b-1`-th tab. This caused the `b-1`-th tab to be built unnecessary. After the swap, tabs with content `A` and `B` are adjacent, so Flutter can then do the translation transition animation (`A` moving out, `B` moving in). After the animation, Flutter swaps `a`-th tab and `b-1`-th tab again to restore the tab order. This second swap caused a second unnecessary build of `b-1`-th tab.

CC @goderbauer @Hixie to see what's the best way to fix this.

@kf6gpe @pcsosinski , considering b/158727949, do we need to adjust the priority?

**Comment by aytunch** [comment]
@liyuqian Does this problem exist in the case of a `BottomNavigationBar` with each item corresponding to a page in a `PageView`

**Comment by liyuqian** [comment]
The default `BottomNavigationBar` as shown in the sample code of https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html doesn't seem to have any translation transition so I think this problem doesn't exist there. If you have an sample app that uses both `PageView` and `BottomNavigationBar`, I can help debug it locally and see if there's any evidence of the problem.

**Comment by febg11** [comment]
has this been fixed?

**Comment by plam50** [comment]
This is also affecting me, are there any updates on this?

**Comment by pierre42100** [comment]
Here is a temporary workaround for the issue, just wrap your Tab Pages with the following widget :

```dart
class TabTransitionWidget extends StatefulWidget {
  final Widget child;

  const TabTransitionWidget(this.child, {Key key})
      : assert(child != null),
        super(key: key);

  @override
  _TabTransitionWidgetState createState() => _TabTransitionWidgetState();
}

class _TabTransitionWidgetState extends State<TabTransitionWidget> {
  var _show = false;

  @override
  void initState() {
    super.initState();
    Future.delayed(Duration(microseconds: 10)).then((value) {
      if (mounted) setState(() => _show = true);
    });
  }

  @override
  Widget build(BuildContext context) {
    if (!_show)
      return Center(child: CircularProgressIndicator());
    else
      return widget.child;
  }
}
```

**Comment by jd-debug** [comment]
Hello,
are there any new updates about this bug?

**Comment by genehsun** [comment]
Any new?

**Comment by ljhang** [comment]
hell no.still this issue.

**Comment by jd-debug** [comment]
How can we make this bug more visible? I think else this bug will just die in the backlog...

**Comment by liyuqian** [comment]
Upvote (thumb up) would make it more visible. This issue is definitely on Flutter team's radar.

**Comment by kf6gpe** [comment]
b/158727949 is higher priority in the upstream tracker. I'm going to bump the priority on this based on the crowd feedback and that fact. Still not sure when we'll get a resource assigned, though.

**Comment by slagathor2094** [comment]
LOL how is this still an issue?

**Comment by plam50** [comment]
makes no sense how this is still not fixed just a joke at this point 

everyone give the eye emoji reaction to show them how many people are watching it

**Comment by kf6gpe** [comment]
@goderbauer This is a P1 on the upstream issue (b/158727949), and is getting a lot of traction from our users. Any chance we can schedule this for work in Q4?

**Comment by liyuqian** [comment]
Yes, this is ranked very high in Q4 performance prioritization. I may spend some time on it if no one beats me to it.

**Comment by goderbauer** [comment]
The problem fairly easily reproduces with the following code:

```dart
import 'package:flutter/material.dart';

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 5,
        child: Scaffold(
          appBar: AppBar(
            bottom: const TabBar(
              tabs: <Widget>[
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
                Tab(icon: Icon(Icons.directions_boat)),
                Tab(icon: Icon(Icons.directions_bus)),
              ],
            ),
            title: const Text('Tabs Demo'),
          ),
          body: const TabBarView(
            children: <Widget>[
              TabBody(index: 0),
              TabBody(index: 1),
              TabBody(index: 2),
              TabBody(index: 3),
              TabBody(index: 4),
            ],
          ),
        ),
      ),
    );
  }
}

class TabBody extends StatefulWidget {
  const TabBody({ Key key, this.index }) : super(key: key);

  final int index;

  @override
  State<TabBody> createState() => TabBodyState();
}

class TabBodyState extends State<TabBody> {
  @override
  void initState() {
    print('init: [<${widget.index}>]');
    super.initState();
  }

  @override
  void dispose() {
    print('dispose: [<${widget.index}>]');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('${widget.index}'),
    );
  }
}

void main() {
  runApp(TabBarDemo());
}
```

Click on tab 3 and you will see the following sequence of events:

**init: 2
dispose: 2**
init: 3
**init: 2
dispose: 2**
dispose: 0

Obviously, the events in bold shouldn't be there.

## Investigation

To achieve the scrolling animations, we temporarily swap the current tab (here: tab 0) to be right next to the destination tab (here: tab 3). That means that in our example tab 0 and tab 2 are swapping places.

The tab widgets are all keyed, thanks to 

https://github.com/flutter/flutter/blob/085f1daa430c794b4f9ae8e4bdeba8e4bfda2f81/packages/flutter/lib/src/material/tabs.dart#L1272

If the SliverMultiBoxAdaptorElement (which backs the TabBarView) discovers that a keyed widget child has moved, it will move the corresponding element to the new index as well (this is important to preserve the state of tab 0 in our example above). In addition to re-using the old element at the new location, it will also ensure that a new element is instantiated for the old location:

https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/widgets/sliver.dart#L1111-L1112

Since "tab 2" is now at the old location, it will get instantiated and build. I do not remember why we decided to instantiate the element for the old index (@chunhtai do you remember why we did this?). Interestingly, if I remove the line quoted above, all tests still pass and this problem goes away...

In the same frame, the RenderSliverFixedExtentBoxAdaptor (which ultimately backs the TabBarView) then realizes, that the newly instantiated element at index 0 (our tab 0) is not visible and that element is garbage collected:

https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L189-L191

One the animation is completed, we switch tab 0 and 2 back to their correct positions and the whole dance outlined above starts again.

**Comment by goderbauer** [comment]
> Since "tab 2" is now at the old location, it will get instantiated and build. I do not remember why we decided to instantiate the element for the old index (@chunhtai do you remember why we did this?). Interestingly, if I remove the line quoted above, all tests still pass and this problem goes away...

I wonder if we need that line for the case where a widget with a key that's currently visible in the viewport (possibly as the first element in the list) is moved to a position where it is no longer visible. In that case we probably need something at its old index. We should have a test for that...

**Comment by chunhtai** [comment]
Either way it will be corrected in performlayout.  the problem is we don't know if the old index is in the viewport or not in perform rebuild. Now i think this, we should just let the performlayout to correct it...

This issue will be solved as part of https://github.com/flutter/flutter/issues/31269

**Comment by alparslana** [comment]
Working like a charm now, thanks!

**Comment by febg11** [comment]
I am not sure whether this is actally fixed. I just copied the test code from [](url) above and added extra tabs so there is 11 (0-10) overall.
if you follow these steps 
Tap [<0>]
Tap [<9>]
Tap [<3>]
Tap [<7>]
Tap [<1>]
Tap [<8>]
Tap [<1>]
Tap [<5>]
( It loads [<6>] as well)

And Then 

Tap [<10>]
Tap [<5>]
(It loads[<7>] as well)
(It loads [<6>] as well)

Please correct me if my flutter version is not up to date with the merged version. I switched to channel master and ran flutter upgrade. I will post my code and flutter doctor output below. 

My flutter doctor is 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-4.0.pre.51, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

```

And my extended code is 

```
import 'package:flutter/material.dart';

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 11,
        child: Scaffold(
          appBar: AppBar(
            bottom: const TabBar(
              isScrollable: false,
              tabs: <Widget>[
                Tab(icon: Text("0")),
                Tab(icon: Text("1")),
                Tab(icon: Text("2")),
                Tab(icon: Text("3")),
                Tab(icon: Text("4")),
                Tab(icon: Text("5")),
                Tab(icon: Text("6")),
                Tab(icon: Text("7")),
                Tab(icon: Text("8")),
                Tab(icon: Text("9")),
                Tab(icon: Text("10")),
              ],
            ),
            title: const Text('Tabs Demo'),
          ),
          body: const TabBarView(
            children: <Widget>[
              TabBody(index: 0),
              TabBody(index: 1),
              TabBody(index: 2),
              TabBody(index: 3),
              TabBody(index: 4),
              TabBody(index: 5),
              TabBody(index: 6),
              TabBody(index: 7),
              TabBody(index: 8),
              TabBody(index: 9),
              TabBody(index: 10),
            ],
          ),
        ),
      ),
    );
  }
}

class TabBody extends StatefulWidget {
  const TabBody({ Key key, this.index }) : super(key: key);

  final int index;

  @override
  State<TabBody> createState() => TabBodyState();
}

class TabBodyState extends State<TabBody> {
  @override
  void initState() {
    print('My_App_Log: init: [<${widget.index}>]');
    super.initState();
  }

  @override
  void dispose() {
    // print('My_App_Log: dispose: [<${widget.index}>]');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('${widget.index}'),
    );
  }
}

void main() {
  runApp(TabBarDemo());
}

```



> The problem fairly easily reproduces with the following code:
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> class TabBarDemo extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: DefaultTabController(
>         length: 5,
>         child: Scaffold(
>           appBar: AppBar(
>             bottom: const TabBar(
>               tabs: <Widget>[
>                 Tab(icon: Icon(Icons.directions_car)),
>                 Tab(icon: Icon(Icons.directions_transit)),
>                 Tab(icon: Icon(Icons.directions_bike)),
>                 Tab(icon: Icon(Icons.directions_boat)),
>                 Tab(icon: Icon(Icons.directions_bus)),
>               ],
>             ),
>             title: const Text('Tabs Demo'),
>           ),
>           body: const TabBarView(
>             children: <Widget>[
>               TabBody(index: 0),
>               TabBody(index: 1),
>               TabBody(index: 2),
>               TabBody(index: 3),
>               TabBody(index: 4),
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class TabBody extends StatefulWidget {
>   const TabBody({ Key key, this.index }) : super(key: key);
> 
>   final int index;
> 
>   @override
>   State<TabBody> createState() => TabBodyState();
> }
> 
> class TabBodyState extends State<TabBody> {
>   @override
>   void initState() {
>     print('init: [<${widget.index}>]');
>     super.initState();
>   }
> 
>   @override
>   void dispose() {
>     print('dispose: [<${widget.index}>]');
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Center(
>       child: Text('${widget.index}'),
>     );
>   }
> }
> 
> void main() {
>   runApp(TabBarDemo());
> }
> ```
> 
> Click on tab 3 and you will see the following sequence of events:
> 
> **init: 2 dispose: 2**
> init: 3
> **init: 2 dispose: 2**
> dispose: 0
> 
> Obviously, the events in bold shouldn't be there.
> 
> ## Investigation
> To achieve the scrolling animations, we temporarily swap the current tab (here: tab 0) to be right next to the destination tab (here: tab 3). That means that in our example tab 0 and tab 2 are swapping places.
> 
> The tab widgets are all keyed, thanks to
> 
> https://github.com/flutter/flutter/blob/085f1daa430c794b4f9ae8e4bdeba8e4bfda2f81/packages/flutter/lib/src/material/tabs.dart#L1272
> 
> If the SliverMultiBoxAdaptorElement (which backs the TabBarView) discovers that a keyed widget child has moved, it will move the corresponding element to the new index as well (this is important to preserve the state of tab 0 in our example above). In addition to re-using the old element at the new location, it will also ensure that a new element is instantiated for the old location:
> 
> https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/widgets/sliver.dart#L1111-L1112
> 
> Since "tab 2" is now at the old location, it will get instantiated and build. I do not remember why we decided to instantiate the element for the old index (@chunhtai do you remember why we did this?). Interestingly, if I remove the line quoted above, all tests still pass and this problem goes away...
> 
> In the same frame, the RenderSliverFixedExtentBoxAdaptor (which ultimately backs the TabBarView) then realizes, that the newly instantiated element at index 0 (our tab 0) is not visible and that element is garbage collected:
> 
> https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L189-L191
> 
> One the animation is completed, we switch tab 0 and 2 back to their correct positions and the whole dance outlined above starts again.

**Comment by TahaTesser** [comment]
hI @febg11 
Can you please file a new issue with all the details 
Thank you

**Comment by Akiat** [comment]
I just switched to master to fix this issue, and it's much better, but as @ febg11 said, there is still some problems.

I was able to reproduce with it's code (and got the same with mine currently).

@ febg11 did you open a new issue?

**Comment by febg11** [comment]
Sorry didn't get round to it

**Comment by febg11** [comment]
Made a new issue 

https://github.com/flutter/flutter/issues/71273

**Comment by AlmogRnD** [comment]
I'm having this issue was it fixed? I'm on the latest stable build as of Feb 24 2021

**Comment by chunhtai** [comment]
@AlmogRnD can you try with master branch? Some of fixes may not be in stable.

**Comment by AlmogRnD** [comment]
@chunhtai thanks but we are getting ready to launch the app so I want to stay on stable will wait for now
