### ISSUE TITLE
Document flutter.yaml

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1431]
_From @sethladd on November 20, 2015 17:15_

* What is this file?
* What is it used for?
* What do I put in it?

See also https://github.com/flutter/flutter/issues/300

_Copied from original issue: flutter/website#92_

**Comment by eseidelGoogle** [comment]
@qchong needs this for the hackathon.

**Comment by eseidelGoogle** [comment]
Partially documented here:
https://github.com/flutter/website/search?l=markdown&q=flutter.yaml&utf8=%E2%9C%93

What I imagined as a resolution of this bug is something like this:
https://www.dartlang.org/tools/pub/pubspec.html

Even if its just dumped into this bug for later formatting by @qchong
