### ISSUE TITLE
[go_router] Pub.dev Getting started page returns a 404 error

### ISSUE THREAD

**Issue by eshfield** [flutter/flutter#143168]
### Steps to reproduce

1. Go to the [package main page](https://pub.dev/packages/go_router)
2. Click [Getting started](https://pub.dev/documentation/go_router/latest/topics/Get%20started-topic.html) link under `Documentation` topic

**Comment by lifeShadow59** [comment]
Hii @chunhtai 

I need your assistance in fixing an issue. Upon my observation in the [Documentation](https://pub.dev/packages/go_router#documentation) section, it seems that there are spaces in the words, causing the URL to break. You can see in the video which contains in below URL. 

Could you please help me resolve this and provide guidance on how to address the spacing issue in the documentation?

[https://drive.google.com/file/d/13oWNIERJzjf6o1eeNs4B2KfMTEE6wBP3/view?usp=sharing](https://drive.google.com/file/d/13oWNIERJzjf6o1eeNs4B2KfMTEE6wBP3/view?usp=sharing)

**Comment by lifeShadow59** [comment]
@chunhtai 

https://github.com/flutter/flutter/assets/40498553/4197f1a3-1e01-41c6-859c-464686eccee0

**Comment by darshankawar** [comment]
@lifeShadow59 
Please don't tag the team members unnecessarily. If you would like to contribute, please go through the [guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md).

**Comment by eshfield** [comment]
@huycozy that's correct—all topics with a space symbol in the title are working fine now
