### ISSUE TITLE
[CP] Disable surface producer

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#143102]
### Issue Link

https://github.com/flutter/flutter/issues/142952

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/50410

### Changelog Description

Disables the surface producer code paths in beta because of a bug that impacts some platform views (e.g. https://github.com/flutter/flutter/issues/142952).

Cherry picking the correct fix is too complicated as it is multiple dependent PRs with lots of conflicts.

This PR just disables the code path for the beta.

### Impacted Users

All Android users

### Impact Description

Broken Android Platform Views

### Workaround

N/A

### Risk

low

### Test Coverage

yes

**Comment by Jasguerrero** [comment]
Merged to stable 3.19
