### ISSUE TITLE
Show VS Code / Dart Code in flutter doctor if VS Code is installed

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#14314]
An idea from @mit-mit which I might do some investigation into:

If VSCode is installed on the user’s machine, we should show a flutter doctor line item for it (either “[x] VSCode and Dart-Code vxxx installed”, or “[ ] VSCode detected; consider installing the Dart-Code plugin for Dart and Flutter support”). If VSCode is not installed, we should not show a doctor item - it would look like an error to the user when having it is just value-add. (while we are at it, we should probably do the same for IntelliJ)

**Comment by DanTup** [comment]
@devoncarew When running `flutter doctor` and something crashes, this happens:

```text
Dannys-MacBook:~ danny$ FLUTTER doctor -v
Building flutter tool...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 422acc5567324620)
Crash report written to /Users/danny/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

Is there a way to prevent sending crash reports and also dump the error to the console easily? I had a look through the code and found there's some code to suppress analytics but I couldn't figure out how to cause the flag to be set, but also not sure if that'd dump the error to the console.

(I have found the error in the log file; just wondering if there's something to make the cycle a bit faster.. no doubt there will be many exceptions =))

**Comment by devoncarew** [comment]
> Is there a way to prevent sending crash reports and also dump the error to the console easily?

I don't know of one, (but it should be easy enough to create a local modification for this).

**Comment by DanTup** [comment]
Having local modifications I shouldn't commit kinda scares me (I already actually committed the `includeInsiders` flag as `true` in this change several times today). It's not a problem now (my errors here were schoolboy errors and it now largely works) but if it becomes a common issue maybe we could discuss having a flag or env var or something we could use to handle this? Currently even if you have the debugger attached, it doesn't break, it just dumps the generic message and writes a log to a new file (such that you can't even just keep the error log open and let it refresh). It'd be ideal if there was a debugger attached if it could break on the error to allow easy debugging.
