### ISSUE TITLE
[Impeller] Use ASurfaceControl/ASurfaceTransaction/AHardwareBuffer instead of a Vulkan API based swapchain on Android

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#143105]
We should be able to create an `ASurfaceControl` from the `ANativeWindow`, and use that `ASurfaceControl` to create one or more `ASurfaceTransaction`s that set an `AHardwareBuffer` to them (using `ASurfaceTransaction_setBuffer`).

This should replace the current swapchain implementation on Vulkan - we'd have to wrap the `AHardwareBuffer`s into whatever Vulkan objects (I assume a VkImage?) that get used by the rest of Impeller.

This gives us a few more knobs that aren't available in the straight Vulkan APIs:

- Better HDR support (not 100% clear on how but it's in the docs).
- Set a completion callback that gives us [stats](https://developer.android.com/ndk/reference/group/native-activity#group___native_activity_1ga0888abcde70caccd9e7759457df8b3af)
- Some more methods we could try to use to handle cases where we submit two frames in a single vsync, e.g. https://developer.android.com/ndk/reference/group/native-activity#asurfacetransaction_setframetimeline and https://developer.android.com/ndk/reference/group/native-activity#asurfacetransaction_setdesiredpresenttime and https://developer.android.com/ndk/reference/group/native-activity#asurfacetransaction_setenablebackpressure

In theory it could help as well since we'll be talking directly to surfaceflinger with this API rather than going through whatever the Vulkan driver is doing. These APIs are all 29+, but we're already restricting Vulkan on Impeller to 29+ anyway.

This last part is what I think will give us better integration with Android native tracing capabilities.

@johnmccutchan @jonahwilliams @chinmaygarde fyi

**Comment by chinmaygarde** [comment]
I think we can de-duplicate this issue with https://github.com/flutter/flutter/issues/132512

**Comment by chinmaygarde** [comment]
Per the discussion in the last Impeller Weekly, this is no longer a priority and @johnmccutchan is also no longer blocked.
