### ISSUE TITLE
scrollControllerList.position.maxScrollExtent doesnt scroll down fully.

### ISSUE THREAD

**Issue by osh91** [flutter/flutter#143158]
### Steps to reproduce

I have `Expand` include a `Scrollbar` and `ListView.Builder.` I've set controllers for both of them.

However, I'm encountering an issue. For instance, when a user presses a button, the scroll should smoothly move down to the last item (last `ListTile`). Unfortunately, it doesn't; instead, it shows one item above the last one, failing to scroll down fully.

I came across this [post](https://github.com/flutter/flutter/issues/120583) where support suggested trying `itemExtent` .I followed the advice, but it didn't resolve the issue. I also experimented with changing the animation `Timer` instead of using `animationTo` and attempted using `jumpTo() `but none of these solutions worked.

Here's the interesting part: When the program runs, if a user adds one item and then presses button, the scrollbar doesn't scroll down fully. _However_, if the user presses the cancel button, it scrolls down to the bottom correctly. Could this be a rendering issue with Flutter?

### Expected results

Let's say I have 10 ListTiles. If user press button it has to scroll down to the bottom , 10th ListTile. 

### Actual results

Let's say I have 10 ListTiles. If user press button it will scroll down to 9th ListTile not 10th.

### Code sample

```
  void scrollToBottom()  {
    scrollControllerList.animateTo(
      scrollControllerList.position.maxScrollExtent, // THIS ONE IS THE PROBLEM
      duration: Duration(milliseconds: 800),
      curve: Curves.ease,
    );
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.9, on Ubuntu 22.04.3 LTS 6.5.0-15-generic, locale en_US.UTF-8)
    • Flutter version 3.16.9 on channel stable at ....
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (2 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at ...
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 76.3.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • R5CN7191Z7D (mobile) • R5CN7191Z7D • android-arm    • Android null (API null)
    • Linux (desktop)      • linux       • linux-x64      • Ubuntu 22.04.3 LTS 6.5.0-15-generic
    • Chrome (web)         • chrome      • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0

**Comment by moffatman** [comment]
It depends on the length of your scrollview. Because flutter lazily builds and lays it out, at many points the `maxScrollExtent` is just an estimate

**Comment by darshankawar** [comment]
This looks similar to https://github.com/flutter/flutter/issues/129768, so please follow-up in it for further updates.
Closing this as a duplicate. You may share your findings in that issue for better tracking.
