### ISSUE TITLE
Stuck on Hot Reload and Hot Restart with message: resume: (-32000) Bad state: The client closed with pending request "resume"

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#143150]
resume: (-32000) Bad state: The client closed with pending request "resume". #0 new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45) #1 VmService._call (package:vm_service/src/vm_service.dart:2499:21) #2 VmService.resume (package:vm_service/src/vm_service.dart:2374:7) #3 IsolateManager.resumeThread (package:dds/src/dap/isolate_manager.dart:317:33) #4 DartDebugAdapter.continueRequest (package:dds/src/dap/adapters/dart.dart:821:26) #5 BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:141:20) #6 BaseDebugAdapter.handleIncomingRequest (package:dds/src/dap/base_debug_adapter.dart:384:7) #7 BaseDebugAdapter._handleIncomingMessage (package:dds/src/dap/base_debug_adapter.dart:295:7) #8 ByteStreamServerChannel._readMessage (package:dds/src/dap/protocol_stream.dart:82:18) #9 ByteStreamServerChannel.listen.<anonymous closure> (package:dds/src/dap/protocol_stream.dart:53:24)

================================================================
Flutter Doctor output:

-------------------------------------------------------------------

[✓] Flutter (Channel stable, 3.16.8, on macOS 13.0.1 22A400 darwin-arm64, locale en-IN)
    • Flutter version 3.16.8 on channel stable at /Users/faizal/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (3 weeks ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/faizal/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    
   [✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • Poco X5 Pro 5G (mobile) • 98c4b9ca • android-arm64  • Android 13 (API 33)
    • macOS (desktop)         • macos    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)            • chrome   • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by dam-ease** [comment]
Hello @faisalansari0367
This is similar to https://github.com/flutter/flutter/issues/139181 which has been closed as fixed. Can you upgrade to the latest channels to confirm this no longer persists?
