### ISSUE TITLE
Dart roll to the engine is stopped.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#143110]
The engine roll to the framework started failing at https://github.com/flutter/engine/pull/50437, which contained the Dart roll at https://github.com/flutter/flutter/pull/143099, which contained https://dart.googlesource.com/sdk.git/+/7ef215a4a5ec884dd147c51a0a87c2a7d35a4b94, which deprecated unmodifiable typed data views.

That change appears to be breaking analysis of plugins:

```
Running command: "dart analyze --fatal-infos" in /b/s/w/ir/x/t/flutter_packages.OXOEAL/packages/image_picker/image_picker_platform_interface
Analyzing image_picker_platform_interface...

   info - lib/src/types/picked_file/html.dart:30:38 - 'UnmodifiableUint8ListView' is deprecated and shouldn't be used. Use Uint8List.asUnmodifiableView() instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use

1 issue found.
```

From

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20flutter_plugins/64343/overview

That package will need to be migrated before the deprecation can roll into the framework.

**Comment by zanderso** [comment]
cc @stuartmorgan @rakudrama

**Comment by stuartmorgan** [comment]
If the replacement isn't available yet on `stable`, you can file an issue describing the migration, and then add an analysis suppression to that line with a comment linking to the issue, which will unblock the roll.

**Comment by jason-simmons** [comment]
The replacement API (`Uint8List.asUnmodifiableView()`) is not available in the Dart 3.2.6 SDK used on the current Flutter framework stable branch.

**Comment by mraleph** [comment]
Could we adopt a protocol which does not require Dart SDK deprecations to be blocked on Flutter changes? Deprecations are non-breaking. Flutter team decided that they want to break their builds on deprecations - that's fine. But this does not imply that Dart SDK has to be affected by this. 

The current approach is causing a lot of unnecessary churn for us on the Dart SDK side.

**Comment by stuartmorgan** [comment]
> Could we adopt a protocol which does not require Dart SDK deprecations to be blocked on Flutter changes?

For flutter/packages, https://github.com/flutter/flutter/issues/108555 is the most likely thing that would change that behavior. Feel free to add discussion there, or file a more general tracking issue.

**Comment by matanlurey** [comment]
> Could we adopt a protocol which does not require Dart SDK deprecations to be blocked on Flutter changes? Deprecations are non-breaking. Flutter team decided that they want to break their builds on deprecations - that's fine. But this does not imply that Dart SDK has to be affected by this.
> 
> The current approach is causing a lot of unnecessary churn for us on the Dart SDK side.

@jonahwilliams and I have proposed modifying the Flutter team policy around deprecations.

I'll start a thread internally and we can chat more.

**Comment by zanderso** [comment]
When https://github.com/flutter/flutter/pull/143161 lands in the framework, we can restart the Dart -> Engine rolls. cc @jason-simmons @chinmaygarde

**Comment by jonahwilliams** [comment]
The dart to engine roller is running again, closing.
