### ISSUE TITLE
Camera for windows failed to initialize camera on some camera such as Elgato Facecam Pro or OBSBot

### ISSUE THREAD

**Issue by poktkm** [flutter/flutter#143151]
### What package does this bug report belong to?

camera

### What target platforms are you seeing this bug on?

Windows

### Have you already upgraded your packages?

Yes

### Dependency versions

name: test_camera
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera_platform_interface: ^2.1.2
  camera_windows: ^0.2.1+9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  uses-material-design: true

### Steps to reproduce

1. Connect 2 webcam. one logitech Brio 4 webcam and one Elgato Facecam pro
2. Start window's default camera application to verify both camera is working in windows.
3. Run camera_windows example code and 2 cameras was found
4. Switch camera to logitech webcam and press create camera and preview is displayed.
5. Switch camera to Elgato Facecam Pro and press create camera, Error message appear "Failed to initialize camera: camera_error: Failed to initialize video preview".

### Expected results

Since both webcam is working normally in default windows camera application, it should work normally in flutter.

### Actual results

In general, normal/generic webcam is working fine wht camera_window but some more expensive webcam such as OBSBot Tiny, Instra360 Link and most recently Elgato Facecam Pro do not work and having problem when it try to connect and initialize preview. 

### Code sample

<details open><summary>Code sample</summary>

```dart
  Widget _buildPreview() {
    return CameraPlatform.instance.buildPreview(_cameraId);
  }
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

https://youtu.be/B3ctjTXAQh0

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22621.3007], locale en-AU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
[!] Android Studio (not installed)
[√] VS Code (version 1.86.0)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by darshankawar** [comment]
This looks similar to https://github.com/flutter/flutter/issues/140014 so please follow-up in it for further updates.
Closing as duplicate. If you disagree, write in comments and I'll reopen it.
