### ISSUE TITLE
Images in ListView disappear when changed/updated

### ISSUE THREAD

**Issue by DanVancPdx** [flutter/flutter#14313]
## Steps to Reproduce

Images in ListView disappear when updated.  (by the way - updates to text, icons, and checkboxes all work, it's just images not rendering on change).

Code to reproduce at [https://github.com/DanVancPdx/listview_problem](https://github.com/DanVancPdx/listview_problem)

What should happen?  When an image is clicked, a popup box (alert) shows images.  When an image in the popup box is selected (tapped), it should change the image in the ListView.

This error occurs on the Alpha channel and Master as well (as of Jan 29).

To Reproduce: 

1. Run App.  The following screen is presented.  Click on the IMAGE of the apple.

![device-2018-01-27-094845 custom](https://user-images.githubusercontent.com/31054514/35474952-c5ec7014-034a-11e8-9397-2213c1436c47.png)

2. A pop-up screen appears (alert), and select any image other than apple.  Click SET.

![device-2018-01-27-094951 custom](https://user-images.githubusercontent.com/31054514/35474958-d79054de-034a-11e8-9224-db8a3750dfb6.png)

3. Note that the apple image is gone.  In it's place should be the selected image.

![device-2018-01-27-095824 custom](https://user-images.githubusercontent.com/31054514/35474961-dad564c2-034a-11e8-9f89-26365883002b.png)

4. The Sort Ascending and Sort Descending buttons do sort the list successfully, the text shows correctly in sorted order, but some images disappear. 

Note: I've tried setting keys at various levels, all un-successful for me.   Maybe I'm setting them at the wrong place(s).  I've removed all key setting in this example to start fresh with the problem.

Changes to text, icons, and checkbox status work in the ListView - just Images don't.

```Dart
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'dart:async';

void main() => runApp(new MaterialApp(home: new ItemsSelect(), theme: new ThemeData(primarySwatch: Colors.green), routes: <String, WidgetBuilder>{}));

class FruitList {
  FruitList({
    this.fruitName,
    this.fruitPhotoAsset,
  });

  String fruitName;
  String fruitPhotoAsset;
}

class ItemsSelect extends StatefulWidget {
  ItemsSelect({
    Key key,
  })
      : super(key: key);

  ItemsSelectState createState() => new ItemsSelectState();
}

class ItemsSelectState extends State<ItemsSelect> with RouteAware {
  List<FruitList> fruitsList;

  @override
  initState() {
    super.initState();
    fruitsList = <FruitList>[
      new FruitList(
        fruitName: "{Empty}",
      ),
    ];
    fruitsList.clear();
    this.getData();
  }

  Future<String> getData() async {
    this.setState(() {
      fruitsList.add(new FruitList(
        fruitName: "apple",
        fruitPhotoAsset: "assets/apple.png",
      ));
      fruitsList.add(new FruitList(
        fruitName: "banana",
        fruitPhotoAsset: "assets/banana.png",
      ));
      fruitsList.add(new FruitList(
        fruitName: "pear",
        fruitPhotoAsset: "assets/pear.png",
      ));
      fruitsList.add(new FruitList(
        fruitName: "pineapple",
        fruitPhotoAsset: "assets/pineapple.png",
      ));
      fruitsList.add(new FruitList(
        fruitName: "strawberry",
        fruitPhotoAsset: "assets/strawberry.png",
      ));
    });
    return "Success!";
  }

  _changePhoto(int index) async {
    int _selectedValue = 1;
    var alert = new AlertDialog(
        title: new Text('Set selected image:'),
        content: new SingleChildScrollView(
          child: new ListBody(children: <Widget>[
            new FlatButton(
                color: Theme.of(this.context).primaryColor,
                child: const Text('Set image to watermellon.'),
                onPressed: () {
                  Navigator.of(this.context).pop();
                  _updatePhotoAsset(index, "assets/watermellon.png");
                }),
          ]),
        ));
    showDialog(context: this.context, child: alert);
  }

  _updatePhotoAsset(int i, String asset) {
    setState(() {
      //*** This is the problem area.  The photoAsset is changed, but it usually
      //*** now goes blank on the device.
      //***
      //*** However, the text field does get updated with the appended x.
      fruitsList[i].fruitPhotoAsset = asset;
      fruitsList[i].fruitName += 'x';
      print("photo asset $i updated to: $asset");
    });
  }

  _sortAscending() {
    setState(() {
      fruitsList.sort((x, y) => x.fruitName.compareTo(y.fruitName));
    });
  }

  _sortDescending() {
    setState(() {
      fruitsList.sort((y, x) => x.fruitName.compareTo(y.fruitName));
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Container(
          color: Colors.blue.shade100,
          child: new Column(children: <Widget>[
            new Text("\n\n\n"),
            new Container(
                padding: const EdgeInsets.all(8.0),
                color: Colors.blue.shade100,
                child: new Row(
                  children: <Widget>[
                    new Expanded(child: new Text(" ")),
                    new RaisedButton(
                      child: new Text("Sort Asc"),
                      onPressed: () {
                        setState(() {
                          _sortAscending();
                        });
                      },
                    ),
                    new RaisedButton(
                      child: new Text("Sort Desc"),
                      onPressed: () {
                        setState(() {
                          _sortDescending();
                        });
                      },
                    ),
                    new Text("       Tap image to change"),
                  ],
                )),
            new Expanded(
                child: new ListView.builder(
                    itemCount: fruitsList == null ? 0 : fruitsList.length,
                    itemBuilder: (BuildContext context, int index) {
                      return new Card(
                          child: new Container(
                              color: Colors.red.shade100,
                              height: 60.0,
                              child: new ListTile(
                                trailing: new Container(
                                  child: new Row(
                                    mainAxisAlignment: MainAxisAlignment.end,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: <Widget>[
                                      new GestureDetector(
                                        onTap: () {
                                          setState(() {
                                            _changePhoto(index);
                                          });
                                        },
                                        child: new Image.asset(
                                          fruitsList[index].fruitPhotoAsset,
                                          //*** this photo should get changed by onTap, but doesn't
                                          width: 55.0,
                                          height: 55.0,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                title: new Text('${fruitsList[index].fruitName}', style: new TextStyle(fontWeight: FontWeight.bold)),
                                //*** while this text does get updated by the above onTap
                              )));
                    })),
          ])),
    );
  }
}
```

## Logs

Run your application with `flutter run` and attach all the log output.

`Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
Configuration 'profileCompile' in project ':app' is deprecated. Use 'profileImplementation' instead.
Configuration 'releaseCompile' in project ':app' is deprecated. Use 'releaseImplementation' instead.
Built build\app\outputs\apk\app-debug.apk (23.1MB).
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(27235): onResume setting current activity to this
D/EGL_emulation(27235): eglMakeCurrent: 0x7feef2ceb4a0: ver 2 0 (tinfo 0x7feef2ce8fe0)
Syncing files to device Android SDK built for x86 64...
D/        (27235): HostConnection::get() New Host Connection established 0x7feef2ce0140, tid 27250
D/EGL_emulation(27235): eglMakeCurrent: 0x7feef2ceb4a0: ver 2 0 (tinfo 0x7feef33fe200)
I/Choreographer(27235): Skipped 52 frames!  The application may be doing too much work on its main thread.`

Run `flutter analyze` and attach any output of that command also.

`Analyzing C:\Users\Daniel\Documents\Flutter_Projects\ListViewWithImages\listview_problem...
  hint - The member 'activity' can only be used within instance members of subclasses of 'ScrollPosition' at lib\imagePicker.dart:266:30 - invalid_use_of_protected_member
1 issue found.
(Ran in 10.9s)`

## Flutter Doctor

`Microsoft Windows [Version 10.0.16299.192]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Daniel>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-US, channel alpha)
    • Flutter at C:\Users\Daniel\flutter
    • Framework revision 8f65fec5f5 (7 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Daniel\AppData\Local\Android\sdk
    • Android NDK at C:\Users\Daniel\AppData\Local\Android\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[√] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)`

#

**Comment by csbenjamin** [comment]
I have a similar issue that seams to be releated. When I load my app the images show as expected
![screenshot_20180204-193449](https://user-images.githubusercontent.com/2938621/35782719-a3151d3a-09e3-11e8-8191-939071c7761e.png)
then if I put the app in background and bring it again to front, the images do not show as expected, but I get a white hole where the images should appear
![screenshot_20180204-193510](https://user-images.githubusercontent.com/2938621/35782773-6baede70-09e4-11e8-80f9-6bd98a3d7830.png)

**Comment by csbenjamin** [comment]
Maybe this is releated to this https://github.com/flutter/flutter/issues/14228

**Comment by csbenjamin** [comment]
Well, my issue was solved when I did a flutter upgrade using the master branch. Try do that

**Comment by DanVancPdx** [comment]
thanks csbenjamin!  Upgrade to master branch and problem is resolved.  Yay!
