### ISSUE TITLE
[Proposal][tool] Add Flutter version to project template pubspec

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#143159]
### Use case

Developers that work together on Flutter projects might run into Flutter version conflicts.
To alleviate this issue, the Flutter version can be specified in the pubspec, using `flutter: <version constraint>`

### Proposal

Specify `flutter: '>= {{currentFlutterVersion}}'` in the project pubspec.yaml template.

I.e. in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/pubspec.yaml.tmpl

**Comment by navaronbracke** [comment]
Since I am familiar with this part of the tool, I'll write a fix for it.

**Comment by christopherfujino** [comment]
@mit-mit do you have opinions about this?

**Comment by christopherfujino** [comment]
@navaronbracke actually, since the Dart SDK version will certainly roll in between different Flutter SDK versions, setting a lower bound on the Dart SDK essentially also sets a lower bound for the Flutter SDK. Or is there some situation where this would not be sufficient?

**Comment by navaronbracke** [comment]
> @navaronbracke actually, since the Dart SDK version will certainly roll in between different Flutter SDK versions, setting a lower bound on the Dart SDK essentially also sets a lower bound for the Flutter SDK. Or is there some situation where this would not be sufficient?

Yeah, I was also thinking that that would be sufficient. However, I had seen an issue on my end where person A was locally running Flutter 3.16 and person b was running Flutter 3.13, while the pubspec of their project listed `sdk: '>=3.0.0 <4.0.0'` and no Flutter constraint. (so I assume theDart SDK lower bound never changed)

Due to the TextScaler change in Flutter 3.16, person b hit a compilation error (which is expected).

Personally I think that
a) being able to manually set the `flutter:` constraint isn't being advertised (enough?) as a possible option
b) people tend to forget that they should update their lower bound on the Dart SDK when upgrading Flutter in their projects,
merely because "they don't specifically need new Dart features", but they _do want_ the new Flutter features that are enabled by updating the minimum.
c) the fact that you can pin the Flutter version in two ways (both with the Dart SDK bound, or explicitly), gives users different ways to do the same thing, which might lead to some confusion

**Comment by christopherfujino** [comment]
> > @navaronbracke actually, since the Dart SDK version will certainly roll in between different Flutter SDK versions, setting a lower bound on the Dart SDK essentially also sets a lower bound for the Flutter SDK. Or is there some situation where this would not be sufficient?
> 
> Yeah, I was also thinking that that would be sufficient. However, I had seen an issue on my end where person A was locally running Flutter 3.16 and person b was running Flutter 3.13, while the pubspec of their project listed `sdk: '>=3.0.0 <4.0.0'` and no Flutter constraint. (so I assume the Dart SDK lower bound never changed)

The Dart SDK version DID change between Flutter 3.13 and 3.16, the issue here is that this project was likely created with an even older Flutter SDK, I'm guessing version 3.10.0 (see https://docs.flutter.dev/release/archive?tab=linux). Your proposed fix would not have avoided this issue.

> c) the fact that you can pin the Flutter version in two ways (both with the Dart SDK bound, or explicitly), gives users different ways to do the same thing, which might lead to some confusion

I agree that two different ways to do this is confusing, and thus I would prefer we rely on the Dart SDK constraint. Unfortunately, I don't think also pinning the Flutter SDK version is the correct approach, so I am going to close this issue.
