### ISSUE TITLE
Dismissible widget docs say key is optional

### ISSUE THREAD

**Issue by dudeofawesome** [flutter/flutter#14319]
[The docs for the `Dismissible` widget](https://docs.flutter.io/flutter/widgets/Dismissible-class.html) say that the `key` parameter is only required if the `Dismissible` is a list item. However, [`key` is annotated with `@required`](https://github.com/flutter/flutter/blob/370c73d9bce0e5c99937724555f4d12cc8d04ea1/packages/flutter/lib/src/widgets/dismissible.dart#L77), and if that annotation is ignored [it fails an assert as well](https://github.com/flutter/flutter/blob/370c73d9bce0e5c99937724555f4d12cc8d04ea1/packages/flutter/lib/src/widgets/dismissible.dart#L86).

Should the docs be updated, or is `Dismissible` not behaving as intended?

---

From: https://docs.flutter.io/flutter/widgets/Dismissible-class.html
> If the Dismissible is a list item, it must have a key that distinguishes it from the other items and its onDismissed callback must remove the item from the list.

**Comment by Hixie** [comment]
That's a tough one. It's so frequently omitted when in lists that we really want to help people remember to set it... maybe we should just say it's always required.

**Comment by dudeofawesome** [comment]
Would it be possible to see if the widget has a `ListView` ancestor, and
only assert the presence of a `key` then?

**Comment by Hixie** [comment]
Widgets can't see what their parent is (indeed they can be placed in the tree many times simultaneously, or can be build at compile time and then only inserted later).

**Comment by Hixie** [comment]
Let's just update the docs to admit the key is required.

**Comment by tp** [comment]
Docs have been updated, I think this can be closed:

> The [key] argument must not be null because [Dismissible]s are commonly
> used in lists and removed from the list when dismissed. […]

https://api.flutter.dev/flutter/widgets/Dismissible/Dismissible.html

**Comment by darshankawar** [comment]
Hi @dudeofawesome, 
Since the [doc](https://api.flutter.dev/flutter/widgets/Dismissible/Dismissible.html) has been updated specifying `key` is required, closing this issue as fixed.
