### ISSUE TITLE
Add Impeller support to `testing/scenario_app`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143171]
As of https://github.com/flutter/engine/pull/50414, [`scenario_app` ](https://github.com/flutter/engine/tree/main/testing/scenario_app)on Android is now [running on CI and is enforced](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8756639939896351233/+/u/test:_Scenario_App_Integration_Tests/stdout).

As a next step, I'd like to run the same set of tests with `--enable-impeller`. A few caveats/points:

1. Based on my chat with @dnfield, we'll do Vulkan and OpenGLES. 
2. iOS is already running on Impeller, I don't plan to make changes to have it run the Skia backend as well.
3. We'll have to deal with cases where there is an expected failure/crash, as not everything is implemented in every backend yet.

---

A few complications to solve (I just don't know how to do it yet):

- [x] How do I start `scenario_app` with `--enable-impeller`?

    In "real" land, I'd pass the argument to [`FlutterMain.ensureInitializationComplete`](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/view/FlutterMain.java#L75).

- [x] How do I "shard" the Skia gold tests so that different backends use different keys?

    I'm guessing we have prior-art elsewhere in Impeller, I just don't know about it yet.

- [x] How do I allow certain tests to fail (I want to avoid a "status file"-type messes)

    Maybe this is built-into JUnit and I just need to look a little deeper?

There might be other things I need to tackle, but that's what I know so far.

/cc @gaaclarke @dnfield @jonahwilliams @johnmccutchan for FYI.

**Comment by zanderso** [comment]
The iOS scenario app is built/run with/without Impeller by injecting a plist file in the xcodebuild command:

https://github.com/flutter/engine/blob/main/testing/scenario_app/run_ios_tests.sh#L114

**Comment by matanlurey** [comment]
A tad horrifying but I guess it's an option

**Comment by dnfield** [comment]
You could inject an Android manifest, but you can also just set the shell arguments in places like https://github.com/flutter/engine/blob/main/testing/scenario_app/android/app/src/main/java/dev/flutter/scenarios/TestActivity.java#L76 and possibly elsewhere.

Alternatively, you can add the intent arguments the way the tool does depending on how it's launched. I'm not sure if there's a great way to do that for FTL,but for an emulator you definitely can.

**Comment by dnfield** [comment]
For the second question, see for example https://github.com/flutter/engine/blob/6f5b6a37107bbe60d0b9ee3f8323bd3e3074ef68/testing/dart/goldens.dart#L43-L49

**Comment by matanlurey** [comment]
Thanks all! I think I'll go with a combination of `TestActivity.java` arguments and Skia gold metadata.
