### ISSUE TITLE
Building with plugins requires symlink support

### ISSUE THREAD

**Issue by Guidemarcus** [flutter/flutter#143181]
### Steps to reproduce

Start a new flutter app
Install flutter_localization -> flutter pub add flutter_localization
Try building on windows

### Expected results

The app should build and deploy

### Actual results

the build fails with this error
```
Exception: Building with plugins requires symlink support.

Please enable Developer Mode in your system settings. Run
  start ms-settings:developers
to open settings.
```

### Code sample

flutter run -d windows

run this command on a new project with flutter_localization

### Logs

Exception: Building with plugins requires symlink support.

Please enable Developer Mode in your system settings. Run
  start ms-settings:developers
to open settings.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22621.3007], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.5)
[√] Android Studio (version 2023.1)
[√] VS Code, 64-bit edition (version 1.86.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by Guidemarcus** [comment]
Also, It is important to add that my dev mode is enabled on my windows machine. I also can install apps from any source and this is including loose files

**Comment by darshankawar** [comment]
Thanks for the report @Guidemarcus 


> run this command on a new project with flutter_localization

Can you confirm if this behavior occurs without adding this dependency ?

**Comment by Guidemarcus** [comment]
@darshankawar Yes I can confirm it. When I just have the new flutter ap without any dependencies, I can build and launch without any problem. The issue starts when I add flutter_localization

**Comment by darshankawar** [comment]
Thanks for the update @Guidemarcus 
My colleague verified this behavior on Windows 11 machine (same build number as yours) using latest stable and he was able to build properly using the package, so, it is strange that you are seeing the error.
Can you provide verbose log by running `flutter run -d windows -v` to check if it gives any additional logs that might be useful to properly analyze this issue ?
Also, can you try with any other package to confirm if it occurs only with `flutter_localizations` ?
