### ISSUE TITLE
resume: (-32000) Bad state: The client closed with pending request "resume"

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#143148]

**Comment by dam-ease** [comment]
Hello @faisalansari0367.
From the issue title, it seems you are experiencing a crash similar to that reported in https://github.com/flutter/flutter/issues/139181 which has been fixed and shouldn't occur in newer versions, kindly upgrade to the latest versions to see this fix.
Closing this as a duplicate of that issue, if you disagree, kindly provide more information on how this was reproduced or update the issue template with the information being asked.
