### ISSUE TITLE
Getting "404 Not Found" for the Go Router Error Handling and Deep Linking documentation links

### ISSUE THREAD

**Issue by AlexHodges13** [flutter/flutter#143285]
### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Android, iOS, Web, macOS, Linux, Windows

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. Go to pub.dev page for go_router package
2.  Under "Readme" tab, click either the "Error handling" or "Deep linking" links in the Documentation section

### Expected results

Clicking links navigates to corresponding documentation page for either error handling or deep linking information related to go_router

### Actual results

Links take you to a 404 Not Found page in browser

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Looks like everything else from `Deep linking` leads to a `404` page.

**Comment by huycozy** [comment]
This seems to be fixed as I don't see 404 error anymore, @AlexHodges13 could you confirm this on your side?

| | |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/ae0bc256-4cd0-4f94-a35c-52424c004734"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/19046973-12ba-45e9-b5d0-b28a8606a319">

**Comment by danagbemava-nc** [comment]
This has indeed been fixed. Closing as such. 

Thanks for reporting this.
