### ISSUE TITLE
Cloud Firestore Plugin missing documentation

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#14324]
I am having trouble to find the necessary documentation for the use of document references in the Cloud Firestore plugin for Flutter. 
For the problem in question I am trying to pass a Cloud Firesore document reference from the Home widget to a VideoView widget in order to query the necessary data from Cloud Firestore  in the VideoView widget.

Is this possible with the Cloud Firestore plugin right now and if so, is any documentation available to follow along?

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by neiljaywarner** [comment]
@Hixie  @collinjackson  bump.

**Comment by Hixie** [comment]
cc @amirh @bparrishMines @mklim

**Comment by kroikie** [comment]
@stemuk

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/906. Any further collaboration will be done there.
