### ISSUE TITLE
Please upgrade flutter_test dependencies

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter#14322]
flutter_test pulls in some very old library versions which typically clash with the same libraries included in  the project yaml file and this results in the library version downgrade.

For example:
code_builder-1.0.4 - the latest version is 3.0.0, 
observable-0.14.0+1- the latest version is 0.20.4 + 3, 

The solution is to take out the flutter_test dependency and stop writing tests for the time being. 
Is there any other way to get around it maybe force the newer versions somehow?

**Comment by Hixie** [comment]
Looks like we don't depend on those packages anymore, so I'm going to close this bug.
Please let me know if this is still a problem. In theory we are relatively up to date now.
