### ISSUE TITLE
Python formatter and format correctness checker disagree and cause issues only caught on CI.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#143243]
For Python files in the engine, we seem to be using YAPF for formatting and Pylint for checking if the Python file is "correctly" formatted.

But the two tools don't seem to agree on what the correct formatting is. So even if you perform a `./ci/format.sh --fix` and submit the patch, it is possible that your file is still incorrectly formatted per Pylint.

In my case, the line was [apparently too long](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8756618366552569857/+/u/test:_pylint__2_/stdout) (101 chars instead of <=100).

Perhaps the linter should check formatting using YAPF since that is used to fix formatting too?

Not a super high priority but an annoyance I want to document. To be clear, I don't care how we format the files. Just want consistency so I can tell my editor to format on save.

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/50510

**Comment by chinmaygarde** [comment]
Closing as fixed with https://github.com/flutter/engine/pull/50510
