### ISSUE TITLE
Increase machine size for RBE prod pools

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#143234]
### Type of Request

infra task

### Infrastructure Environment

rbe, devicelab

### What is happening?

The performance associated with current RBE machines are not at par with goma.

@zanderso has requested that the RBE prod project machine type be upgraded to `e2-highmem-8` instead of the current `e2-standard-2`.

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by yusuf-goog** [comment]
New machine types have rolled out.

FYI, @zanderso we are now at our quota limits. So if you foresee any additional requests in terms of machine types or quantities, please let me know, so that we can setup the necessary quota limits.

**Comment by zanderso** [comment]
Thanks!
