### ISSUE TITLE
Windows arm64 failing on installing certs.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#143271]
I haven't gone through all the failures, but it seems like most of these are the same as this error:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8756516234988058369/+/u/Dependencies/Install_Certs/stdout?format=raw

<img width="481" alt="Screenshot 2024-02-10 at 12 03 30" src="https://github.com/flutter/flutter/assets/6343103/0e19b83a-4dd8-47bd-b6b6-4621c32e99de">

**Comment by zanderso** [comment]
I moved the Windows arm64 tests to `bringup: true`: https://github.com/flutter/flutter/pull/143272 cc @godofredoc @loic-sharma

**Comment by loic-sharma** [comment]
Error is:

> c:\opt\s\w\ir\cache\certs\install.ps1 : File C:\opt\s\w\ir\cache\certs\install.ps1 cannot be loaded because running 
> scripts is disabled on this system. For more information, see about_Execution_Policies at 
> https:/go.microsoft.com/fwlink/?LinkID=135170.

Looks like one or more Windows Arm64 machines need to be configured to allow running arbitrary PowerShell scripts. Relevant docs: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.4#examples

/cc @yusuf-goog

**Comment by yusuf-goog** [comment]
We added 4 new win arm machines last week (win-17..20).

Due to differences in the windows installation, there are security policies that look to be causing these problems. 

We are quarantining these bots and are looking to making the necessary policy changes in the OS.

**Comment by vashworth** [comment]
https://github.com/flutter/flutter/issues/143180 was the same issue

**Comment by ricardoamador** [comment]
Closing this issue in favor of https://github.com/flutter/flutter/issues/143180 where the work is being tracked.
