### ISSUE TITLE
Text: character offset, new lines and overflow

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#14326]
Hello, 
A feature request here

Currently there's no way to know where a text is overflowing/wrapping.
Which means we can't extract the N first line or the overflowing part to show it somewhere else (think of Google doc). This would be useful when facing a huge wall of text

For now it may potentially be possible to call `TextPainter.layout` and  `TextPainter.height` in a loop to somehow calculate these breaking points. But that is extremely ineficient. 

I think it would be interesting to have a lower layer these informations.

**Comment by Hixie** [comment]
Does `TextPainter.getBoxesForSelection` provide the information you need?

**Comment by zoechi** [comment]
@rrousselGit can this be closed or are you still looking for more information?

**Comment by rrousselGit** [comment]
Yeah sorry, I forgot to close this issue. Done
