### ISSUE TITLE
stuck on flutter precache

### ISSUE THREAD

**Issue by zer09** [flutter/flutter#143286]
### Steps to reproduce

1. Download flutter installer archive
2. Extract archive
3. Add flutter to env path
4. Run `flutter precache`

### Actual results

after downloading the flutter engine and building the flutter tool, it got stuck on resolving dependencies.

![image](https://github.com/flutter/flutter/assets/780780/d3a841c1-341d-4846-925c-e64f2fd252ec)

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

No doctor output, stuck on precache

```

</details>

**Comment by zer09** [comment]
It was caused by adguard, unable to pub ugrpade

**Comment by viroth-ty** [comment]
I had this problem too.

**Comment by lofiluffy** [comment]
Also face this problem. Any solution.
