### ISSUE TITLE
Custom google map marker is blurry on Web

### ISSUE THREAD

**Issue by abigotado** [flutter/flutter#143398]
### Steps to reproduce

On Web create a Google map, add marker with custom marker (I provide a code sample below) with some text, made with canvas.

### Expected results

Marker looks normally.

### Actual results

When I add marker of normal size (48, for example) marker looks blurry. When I add a huge marker (size = 192) or add `..scale(4)` method to `Canvas()` widget - marker looks okay.

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<BitmapDescriptor> getClusterBitmap(
    final int size, {
    final String? text,
  }) async {
    final ui.PictureRecorder pictureRecorder = ui.PictureRecorder();
    final Canvas canvas = Canvas(pictureRecorder);
    final Paint paint1 = Paint()..color = SquadColors.blue600.withOpacity(0.3);
    final Paint paint2 = Paint()..color = SquadColors.blue600;
    final Paint paint3 = Paint()..color = Colors.white;

    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.0, paint1);
    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.4, paint2);
    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.6, paint3);

    final TextPainter painter = TextPainter(textDirection: TextDirection.ltr);
    painter.text = TextSpan(
      text: text,
      style: TextStyle(
        fontSize: size / 3,
        color: SquadColors.blue600,
        fontWeight: FontWeight.w500,
      ),
    );
    painter.layout();
    painter.paint(
      canvas,
      Offset(size / 2 - painter.width / 2, size / 2 - painter.height / 2),
    );

    final ui.Image img =
        await pictureRecorder.endRecording().toImage(size, size);
    final ByteData data =
        (await img.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(data.buffer.asUint8List());
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

These markers have size 48 `await getClusterBitmap(48, text: 5)` and look blurry:
<img width="308" alt="Снимок экрана 2024-02-13 в 18 21 13" src="https://github.com/flutter/flutter/assets/82471392/b2509f56-fc7c-4613-a92a-14c610aa1d6a">

These markers have size 192 `await getClusterBitmap(192, text: 12)` and look normal:
<img width="732" alt="Снимок экрана 2024-02-13 в 18 23 47" src="https://github.com/flutter/flutter/assets/82471392/17bcecae-4015-4812-9006-219b69ffaade">

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3.1 23D60 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.86.1)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @abigotado 
I tried including your code sample in the plugin example in `marker_icons.dart` but wasn't able to make it to run properly that shows the reported behavior.
Can you provide us runnable complete code sample that we can directly copy paste and run to verify it further ?
Also, meanwhile, can you try [this](https://github.com/flutter/flutter/issues/34657#issuecomment-615458858) and check if it helps in your case ?

**Comment by abigotado** [comment]
@darshankawar Thank you for your response!

Unfortunately, the link you provided doesn't suit my case as a solution for converting images to `BitmapDescriptor`, but in my case it's not an image, it's just a canvas painting with text.

Here is complete code sample:

<details open><summary>Code sample</summary>

```dart
import 'dart:math';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(
    const MapsPage(),
  );
}

class MapsPage extends StatelessWidget {
  const MapsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MapsHome(),
    );
  }
}

class MapsHome extends StatefulWidget {
  const MapsHome({super.key});

  @override
  State<MapsHome> createState() => _MapsHomeState();
}

class _MapsHomeState extends State<MapsHome> {
  final LatLng _kMapCenter = const LatLng(52.4478, -3.5402);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _setMarkers(),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        if (snapshot.hasData) {
          return GoogleMap(
            initialCameraPosition: CameraPosition(
              target: _kMapCenter,
              zoom: 18.0,
            ),
            markers: snapshot.data,
          );
        } else {
          return const Center(
            child: CircularProgressIndicator(),
          );
        }
      },
    );
  }

  Future<Set<Marker>> _setMarkers() async {
    final BitmapDescriptor icon1 = await volleyball(
      context,
    );
    final BitmapDescriptor icon =
        await SvgConverter.getClusterBitmap(48, text: '48');

    return {
      Marker(
        markerId: const MarkerId('marker_1'),
        position: _kMapCenter,
        icon: icon,
      ),
      Marker(
        markerId: const MarkerId('marker_2'),
        position: const LatLng(52.4476, -3.5405),
        icon: icon1,
      ),
    };
  }

  /// Volleyball icon.
  static Future<BitmapDescriptor> volleyball(final BuildContext context) async {
    return SvgConverter.getBitmapDescriptorFromSvgAsset(
      context,
      'assets/volleyball.svg',
    );
  }
}

/// Utility for converting SVG.
class SvgConverter {
  /// Converts SVG to [BitmapDescriptor].
  static Future<BitmapDescriptor> getBitmapDescriptorFromSvgAsset(
    final BuildContext context,
    final String assetName, {
    final Size size = const Size.square(30),
    final ColorMapper? colorMapper,
  }) async {
    final ui.FlutterView view = View.of(context);
    final PictureInfo pictureInfo = await vg.loadPicture(
      SvgAssetLoader(assetName, colorMapper: colorMapper),
      context,
    );

    final double devicePixelRatio = view.devicePixelRatio;
    final int width = (size.width * devicePixelRatio).toInt();
    final int height = (size.height * devicePixelRatio).toInt();

    final double scaleFactor = min(
      width / pictureInfo.size.width,
      height / pictureInfo.size.height,
    );

    final ui.PictureRecorder recorder = ui.PictureRecorder();

    ui.Canvas(recorder)
      ..scale(scaleFactor)
      ..drawPicture(pictureInfo.picture);

    final ui.Picture rasterPicture = recorder.endRecording();

    final ui.Image image = rasterPicture.toImageSync(width, height);
    final ByteData bytes =
        (await image.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(bytes.buffer.asUint8List());
  }

  static Future<BitmapDescriptor> getClusterBitmap(
    final int size, {
    final String? text,
  }) async {
    final ui.PictureRecorder pictureRecorder = ui.PictureRecorder();
    final Canvas canvas = Canvas(pictureRecorder);
    final Paint paint1 = Paint()..color = Colors.blue.withOpacity(0.3);
    final Paint paint2 = Paint()..color = Colors.blue;
    final Paint paint3 = Paint()..color = Colors.white;

    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.0, paint1);
    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.4, paint2);
    canvas.drawCircle(Offset(size / 2, size / 2), size / 2.6, paint3);

    final TextPainter painter = TextPainter(textDirection: TextDirection.ltr);
    painter.text = TextSpan(
      text: text,
      style: TextStyle(
        fontSize: size / 3,
        color: Colors.blue,
        fontWeight: FontWeight.w500,
      ),
    );
    painter.layout();
    painter.paint(
      canvas,
      Offset(size / 2 - painter.width / 2, size / 2 - painter.height / 2),
    );

    final ui.Image img =
        await pictureRecorder.endRecording().toImage(size, size);
    final ByteData data =
        (await img.toByteData(format: ui.ImageByteFormat.png))!;

    return BitmapDescriptor.fromBytes(data.buffer.asUint8List());
  }
}
```

</details>

We are rendering two markers here - a Canvas drawing and an svg. Both looks blurry, not sharp in small sizes.

<img width="409" alt="Снимок экрана 2024-02-14 в 10 06 51" src="https://github.com/flutter/flutter/assets/82471392/7da324e0-d6f0-4b17-bf83-94e2d5a0c017">

**Comment by yjbanov** [comment]
Is the image extracted from the picture recorder blurry? Or does it only become blurry when rendered into the map? If it's the latter, then the issue must be with the Google Maps API.

**Comment by abigotado** [comment]
@yjbanov Well, I've tried to pass the circle icon to the `Image.memory()` widget. i've rendered it with `PictureRecorder` and then converted to `Uint8List`, not `BitmapDescriptor`.  And it still looks blurry, without Google Maps.


<img width="194" alt="Снимок экрана 2024-02-15 в 18 35 54" src="https://github.com/flutter/flutter/assets/82471392/36236fde-714b-43ec-96c1-06479a5dc6f8">

**Comment by ditman** [comment]
`BitmapDescriptor.fromBytes` supports a `size` parameter that is needed on the web to tell the maps SDK what's the actual *logical size* of the incoming image bytes. [Code](https://github.com/flutter/packages/blob/main/packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart#L294-L314).

You should be able to pass a [`size` parameter to `AssetImage.fromBytes`](https://github.com/flutter/packages/blob/main/packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/bitmap.dart#L160) to pass info.

Can you please try to:

1. Create your canvas at a resolution that is: `logicalSize * dpr`
2. Define the `fromBytes` asset passing `logicalSize` as the `size` argument

That should make dynamically generated icons render sharply on the web (or it used to!)

**Comment by ditman** [comment]
(Super related: https://github.com/flutter/packages/pull/4055)

**Comment by abigotado** [comment]
@ditman Hi! Tried to do what you've described. Using scaled size for canvas and logical size in `fromBytes`. It works perfectly! Thank you!

**Comment by ditman** [comment]
@abigotado this is going to get better once we merge the PR I linked above.

PS: should we close this issue?

**Comment by abigotado** [comment]
@ditman Sounds cool! Thank you very much! Yes, I'm closing it, as the problem is solved :)
