### ISSUE TITLE
[shared_preferences] Allow specifying the preferences store name on Android

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#14337]
In Android you can store preference files by different filenames. I use this for example to store data for multiple users, or for different preference pages.
e.g. (In Android)
```java
    SharedPreferences settings = context.getSharedPreferences("scores.xml", Context.MODE_PRIVATE);
    SharedPreferences.Editor editor = settings.edit();
    editor.putBoolean("won", true); 
    editor.putInt("score",783);
    editor.apply();
```

**Comment by Rockvole** [comment]
For people looking for this functionality, I created a class which does this. It just reads and writes xml files in the android preferences file format. I have not added all the types. To be more complete it would be better if it emulated the ios preference file format under ios.

https://github.com/Rockvole/flutter/tree/master/filename_preferences

**Comment by ronshapiro** [comment]
For reference, iOS also has a mechanism for named NSUserDefaults.

**Comment by axel-op** [comment]
Hi, 

So I worked in this over the last few days, and I implemented a way to manage multiple Shared Preferences files. With this change, you just have to add a parameter to the `getInstance` method (optional, so it's backward-compatible) to specify the file to use (automatically created if it doesn't already exist).

I edited the files in Dart code and also in Java platform code.
However, as I'm not an iOs developer, I wasn't able to change the iOs specific code (though this isn't broken and still continues to work with the default file). 

If anyone is interested and would like to review/edit my changes, and provide the iOs implementation, in order to make a pull request, here's my fork: https://github.com/axel-op/plugins.

**Comment by marcoabensur** [comment]
> For people looking for this functionality, I created a class which does this. It just reads and writes xml files in the android preferences file format. I have not added all the types. To be more complete it would be better if it emulated the ios preference file format under ios.
> 
> https://github.com/Rockvole/flutter/tree/master/filename_preferences

This functionality saves and look for data in "/app_fluter" folder. But, I needed to access and edit stored xml data from "/shared_prefs" folder.

So I just made a small change in the code in the function "Future<File> _getLocalFile(String fileName)":

```dart
  Future<File> _getLocalFile(String fileName) async {
    // get the path to the document directory.
    String dir = (await getApplicationDocumentsDirectory()).path;
    // Change saved directory from /app_flutter to /shared_prefs
    dir = dir.substring(0, dir.length - ('app_flutter'.length));
    dir = dir + 'shared_prefs';
    File f = new File('$dir/$fileName');
    return f;
  }
```

**Comment by MarloKessler** [comment]
Hey everybody,

thanks @axel-op for your work, I implemented the iOS specific code and also converted the java code to kotlin. Also I removed the deprecated `commit()` method, so it is not fully backwards compatible (even though the `commit()` method had no real function). The plugin can be found [here](https://github.com/MarloKessler/flutter-extended_shared_preferences).

Feel free to fork and add stuff.

**Comment by Ayan4044** [comment]
There are workarounds for achieving this but, multiple sharedpref files should be given in Flutter in the coming days.

**Comment by leszekkrol** [comment]
Any updated in this case?

**Comment by shihuayong** [comment]
Any updates so far?

**Comment by jjliu15** [comment]
Adding on to this - there should be a way to specify using the default shared preferences. This is needed to support setting [IAB settings for ads](https://developers.google.com/ad-manager/mobile-ads-sdk/android/privacy/ccpa#shared_preferences_for_rdp)
