### ISSUE TITLE
salt-call state.apply scripts still running issues for Ubuntu 20.04.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#143333]
### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

salt-call state.apply command running issues for Ubuntu 20.04.

flutter@flutter-devicelab-linux-20:~/Downloads$ sudo salt-call state.apply
/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py:98: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
  salt.utils.versions.warn_until(
[ERROR   ] Command '/usr/local/bin/cipd' failed with return code: 5
[ERROR   ] retcode: 5
[ERROR   ] Command '/usr/local/bin/cipd' failed with return code: 5
[ERROR   ] retcode: 5
/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509.py:211: DeprecationWarning: The x509 modules are deprecated. Please migrate to the replacement modules (x509_v2). They are the default from Salt 3008 (Argon) onwards.
  salt.utils.versions.warn_until(
[ERROR   ] Command '/usr/local/bin/cipd' failed with return code: 5
[ERROR   ] retcode: 5
[ERROR   ] Command '/usr/local/bin/cipd' failed with return code: 5
[ERROR   ] retcode: 5
[ERROR   ] Command '/usr/local/bin/cipd' failed with return code: 5
[ERROR   ] retcode: 5
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2423, in call
    ret = self.states[cdata["full"]](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
    return f(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509.py", line 709, in certificate_managed
    contents = __salt__["x509.create_certificate"](text=True, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 1451, in create_certificate
    get_public_key(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 720, in get_public_key
    if isinstance(key, M2Crypto.X509.X509):
AttributeError: module 'M2Crypto' has no attribute 'X509'

[ERROR   ] Command '/opt/s/__salt.tmp.rwb9xoe6.py' failed with return code: 1
[ERROR   ] stderr: Traceback (most recent call last):
  File "/opt/s/__salt.tmp.rwb9xoe6.py", line 9, in <module>
    with open(r'/var/lib/luci_machine_tokend/token.json', 'r') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/luci_machine_tokend/token.json'
[ERROR   ] retcode: 1
[ERROR   ] {'pid': 20352, 'retcode': 1, 'stdout': '', 'stderr': 'Traceback (most recent call last):\n  File "/opt/s/__salt.tmp.rwb9xoe6.py", line 9, in <module>\n    with open(r\'/var/lib/luci_machine_tokend/token.json\', \'r\') as fd:\nFileNotFoundError: [Errno 2] No such file or directory: \'/var/lib/luci_machine_tokend/token.json\''}
local:
----------
          ID: /usr/local/share/ca-certificates/intca.crt
    Function: file.managed
      Result: True
     Comment: File /usr/local/share/ca-certificates/intca.crt is in the correct state
     Started: 14:13:37.024336
    Duration: 248.999 ms
     Changes:   
----------
          ID: /etc/udev/rules.d/99-android.rules
    Function: file.managed
      Result: True
     Comment: File /etc/udev/rules.d/99-android.rules is in the correct state
     Started: 14:13:37.273564
    Duration: 139.011 ms
     Changes:   
----------
          ID: reload_udev_rules
    Function: cmd.run
        Name: udevadm control --reload-rules
udevadm trigger

      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 14:13:37.414359
    Duration: 0.007 ms
     Changes:   
----------
          ID: remove_system_fastboot
    Function: pkg.removed
        Name: fastboot
      Result: True
     Comment: All specified packages are already absent
     Started: 14:13:37.830928
    Duration: 28.066 ms
     Changes:   
----------
          ID: install_fastboot
    Function: cipd.ensure
      Result: True
     Comment: Packages installed
     Started: 14:13:37.859957
    Duration: 48.589 ms
     Changes:   
----------
          ID: install_fastboot
    Function: file.symlink
        Name: /usr/bin/fastboot
      Result: True
     Comment: Symlink /usr/bin/fastboot is present and owned by root:root
     Started: 14:13:37.908953
    Duration: 1.146 ms
     Changes:   
----------
          ID: python3
    Function: cipd.ensure
      Result: True
     Comment: Packages installed
     Started: 14:13:37.910165
    Duration: 49.092 ms
     Changes:   
----------
          ID: psutil3
    Function: cmd.run
        Name: /opt/swarming-support/bin/python3 /opt/swarming-support/bin/pip3 install psutil
      Result: True
     Comment: All files in creates exist
     Started: 14:13:37.959430
    Duration: 231.307 ms
     Changes:   
----------
          ID: packages
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 14:13:38.195071
    Duration: 7.036 ms
     Changes:   
----------
          ID: install_psutil
    Function: pip.installed
        Name: psutil
      Result: True
     Comment: Python package psutil was already installed
              All specified packages are already installed
     Started: 14:13:38.202172
    Duration: 716.095 ms
     Changes:   
----------
          ID: ensure_device_doctor
    Function: cipd.ensure
      Result: True
     Comment: Packages installed
     Started: 14:13:38.918374
    Duration: 187.083 ms
     Changes:   
----------
          ID: ensure_device_doctor_staging
    Function: cipd.ensure
      Result: True
     Comment: Packages installed
     Started: 14:13:39.105568
    Duration: 181.104 ms
     Changes:   
----------
          ID: /opt/flutter/provision/fqdn.sh
    Function: file.managed
      Result: True
     Comment: File /opt/flutter/provision/fqdn.sh is in the correct state
     Started: 14:13:39.286784
    Duration: 148.884 ms
     Changes:   
----------
          ID: fix_fqdn
    Function: cmd.run
        Name: /opt/flutter/provision/fqdn.sh fix
      Result: True
     Comment: unless condition is true
     Started: 14:13:39.435874
    Duration: 18.729 ms
     Changes:   
----------
          ID: docker
    Function: group.present
      Result: True
     Comment: Group docker is present and up to date
     Started: 14:13:39.454815
    Duration: 1.107 ms
     Changes:   
----------
          ID: android-tools-adb
    Function: pkg.installed
      Result: True
     Comment: unless condition is true
     Started: 14:13:39.456102
    Duration: 11.731 ms
     Changes:   
----------
          ID: git
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 14:13:39.467931
    Duration: 6.867 ms
     Changes:   
----------
          ID: python3-pip
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 14:13:39.474856
    Duration: 4.666 ms
     Changes:   
----------
          ID: pip3-m2crypto
    Function: pip.installed
        Name: m2crypto == 0.31.0
      Result: True
     Comment: Python package m2crypto == 0.31.0 was already installed
              All specified packages are already installed
     Started: 14:13:39.479734
    Duration: 828.202 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/machine_tokend
    Function: cipd.ensure
      Result: True
     Comment: Packages installed
     Started: 14:13:40.308068
    Duration: 48.626 ms
     Changes:   
----------
          ID: /etc/pki
    Function: file.directory
      Result: True
     Comment: The directory /etc/pki is in the correct state
     Started: 14:13:40.357475
    Duration: 0.578 ms
     Changes:   
----------
          ID: /etc/pki/flutter-devicelab-linux-20.mtv.corp.google.com.key
    Function: x509.private_key_managed
      Result: True
     Comment: File /etc/pki/flutter-devicelab-linux-20.mtv.corp.google.com.key is in the correct state
     Started: 14:13:40.358192
    Duration: 2.326 ms
     Changes:   
----------
          ID: /etc/pki/flutter-devicelab-linux-20.mtv.corp.google.com.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2423, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509.py", line 709, in certificate_managed
                  contents = __salt__["x509.create_certificate"](text=True, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 1451, in create_certificate
                  get_public_key(
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 720, in get_public_key
                  if isinstance(key, M2Crypto.X509.X509):
              AttributeError: module 'M2Crypto' has no attribute 'X509'
     Started: 14:13:40.360711
    Duration: 0.61 ms
     Changes:   
----------
          ID: /var/lib/luci_machine_tokend
    Function: file.directory
      Result: True
     Comment: The directory /var/lib/luci_machine_tokend is in the correct state
     Started: 14:13:40.361398
    Duration: 0.465 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh
    Function: file.managed
      Result: True
     Comment: File /opt/luci/machine_tokend/run.sh is in the correct state
     Started: 14:13:40.362083
    Duration: 386.969 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-linux-20.mtv.corp.google.com.crt
     Started: 14:13:40.749587
    Duration: 0.001 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh >/dev/null 2>&1
    Function: cron.present
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-linux-20.mtv.corp.google.com.crt
     Started: 14:13:40.749785
    Duration: 0.001 ms
     Changes:   
----------
          ID: /usr/local/bin/validate_json.py
    Function: file.managed
      Result: True
     Comment: File /usr/local/bin/validate_json.py is in the correct state
     Started: 14:13:40.749812
    Duration: 134.072 ms
     Changes:   
----------
          ID: /etc/systemd/system/swarming-start-bot.service.d/override.conf
    Function: file.managed
      Result: True
     Comment: File /etc/systemd/system/swarming-start-bot.service.d/override.conf is in the correct state
     Started: 14:13:40.884089
    Duration: 379.224 ms
     Changes:   
----------
          ID: dialout
    Function: group.present
      Result: True
     Comment: Group dialout is present and up to date
     Started: 14:13:41.263382
    Duration: 0.349 ms
     Changes:   
----------
          ID: kvm
    Function: group.present
      Result: True
     Comment: Group kvm is present and up to date
     Started: 14:13:41.263788
    Duration: 0.3 ms
     Changes:   
----------
          ID: plugdev
    Function: group.present
      Result: True
     Comment: Group plugdev is present and up to date
     Started: 14:13:41.264142
    Duration: 0.905 ms
     Changes:   
----------
          ID: swarming
    Function: user.present
      Result: True
     Comment: User swarming is present and up to date
     Started: 14:13:41.266114
    Duration: 4.314 ms
     Changes:   
----------
          ID: /etc/sudoers
    Function: file.append
      Result: True
     Comment: File /etc/sudoers is in correct state
     Started: 14:13:41.270893
    Duration: 2.492 ms
     Changes:   
----------
          ID: /opt/s
    Function: file.directory
      Result: True
     Comment: The directory /opt/s is in the correct state
     Started: 14:13:41.273625
    Duration: 0.956 ms
     Changes:   
----------
          ID: /opt/s/bot_code.py
    Function: cmd.script
      Result: False
     Comment: Command '/opt/s/bot_code.py' run
     Started: 14:13:41.275002
    Duration: 595.805 ms
     Changes:   
              ----------
              pid:
                  20352
              retcode:
                  1
              stderr:
                  Traceback (most recent call last):
                    File "/opt/s/__salt.tmp.rwb9xoe6.py", line 9, in <module>
                      with open(r'/var/lib/luci_machine_tokend/token.json', 'r') as fd:
                  FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/luci_machine_tokend/token.json'
              stdout:
----------
          ID: /etc/systemd/system/swarming-start-bot.service
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: luci/swarming./opt/s/bot_code.py
     Started: 14:13:41.871304
    Duration: 0.002 ms
     Changes:   
----------
          ID: swarming-start-bot
    Function: service.running
      Result: False
     Comment: One or more requisite failed: luci/swarming./etc/systemd/system/swarming-start-bot.service, luci/swarming./opt/s/bot_code.py
     Started: 14:13:41.871784
    Duration: 0.001 ms
     Changes:   
----------
          ID: fuchsia/salt-version-base
    Function: event.send
      Result: True
     Comment: Event fired
     Started: 14:13:41.871823
    Duration: 196.812 ms
     Changes:   
              ----------
              data:
                  ----------
                  hash:
                      291981568ba5d2273e54f70698a27c93892f9503
                  date:
                      2023-10-23
              tag:
                  fuchsia/salt-version-base

Summary for local
-------------
Succeeded: 33 (changed=2)
Failed:     6

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by yusuf-goog** [comment]
This is due to a deprecation of current x509 apis in salt modules. we need to use an older salt release, or, ideally upgrade to using x509 v2 api.

**Comment by kentnguyen99** [comment]
I uninstalled current version of Salt package then reinstalled older version of Salt package. 
linux-20 is back online and running fine now, this service ticket can be closed.
