### ISSUE TITLE
Engine roll to the framework is stopped

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#143342]
The roll here https://github.com/flutter/flutter/commit/1e6a9024738787f862db8991ed325efead5b09d0

Turned the tree red as in:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__memory_nav/13426/overview

We're currently unsure which commit in that engine roll is the culprit, so the engine roll to the framework is paused pending investigation.

The most suspicious looking commit is https://github.com/flutter/engine/pull/50540, but there is no local repro yet

cc @dnfield

**Comment by dnfield** [comment]
https://github.com/flutter/engine/pull/50586 fixed the roll, roller is back on.
