### ISSUE TITLE
[Impeller] Metal golden tester seems to miss certain validation failures.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#143324]
While investigating a fix for https://github.com/flutter/flutter/issues/142358 , @gaaclarke noticed that the test case actually failed for Metal when run locally. As a result, we fixed this particular issue, but nevertheless we have a problem if the metal tester is covering up these failures

![image](https://github.com/flutter/flutter/assets/8975114/1d1cdd58-76cc-4837-a17a-e617dd17594c)

**Comment by jonahwilliams** [comment]
zach: metal validation is only enabled on arm64 macOS hosts. We should enable it everywhere?

**Comment by jonahwilliams** [comment]
I tried triggering this failure on this PR: https://github.com/flutter/engine/pull/51080/

Confusingly if I look in the mac unopt shard, it looks like no tests ran?

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20mac_unopt/849/overview

FYI @zanderso

**Comment by zanderso** [comment]
Tests are on the subbuilds as in https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/743809/overview

**Comment by jonahwilliams** [comment]
Ahh OK. That is unfortunate, it means we still don't catch this error (actually I'm unsure if this causes a validation check beyond the pink square)

**Comment by jonahwilliams** [comment]
Unassigning as I don't know how to get this working :(

**Comment by jonahwilliams** [comment]
We think this is related to not actually running metal validations.

**Comment by jonahwilliams** [comment]
We enabled additional validation checks but its not clear if we're able to get more failures out of this, closing as infeasible.
