### ISSUE TITLE
[Build Moot]: Solve the `libpng` aliasing problem and create a recipe for others

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143336]
As discussed today in Flutter Build Moot (https://github.com/flutter/flutter/issues/67373).

Zach and Matan are going to look at https://github.com/flutter/engine/pull/49057, and see if we can solve at least ~2 generic "aliasing" problems (hard-coded expected paths) with GN aliases.

Let's aim for Monday February 26th for the next update.

**Comment by zanderso** [comment]
I moved libpng here https://github.com/flutter/engine/pull/50571. I think `boringssl` might also be straightforward to move the same way.

**Comment by matanlurey** [comment]
Done, and updated the documentation.
