### ISSUE TITLE
[Windows] increasing memory every time I change the size of the application window

### ISSUE THREAD

**Issue by zura-kh** [flutter/flutter#143354]
### Steps to reproduce

Mentioned at https://github.com/flutter/flutter/issues/119468

### Expected results

Mentioned at https://github.com/flutter/flutter/issues/119468

### Actual results

Mentioned at https://github.com/flutter/flutter/issues/119468

### Code sample

Mentioned at https://github.com/flutter/flutter/issues/119468

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22621.3007], locale ka-GE)
    • Flutter version 3.16.9 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34525.116
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code, 64-bit edition (version 1.85.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.112

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @zura-kh, what are the memory jumps that you see when you resize your window? What device are you testing this on? 
Do you notice this with any other apps? 

Thank you


PS: In the future, please file new issues with the relevant details within the issue. We shouldn't need to revisit an older issue that was seemingly fixed to investigate new issues.

**Comment by zura-kh** [comment]
@danagbemava-nc Thank you for looking into this.

Testing on Windows 11 desktop. The release build of the default click counter app. Initially, the memory usage is within 82-87 MB. Stays within the range when using the app - clicking the button or inside the window, moving the window. Memory usage quickly jumps  to 300MB, then 1GB, and more as soon as I start resizing the window (by mouse dragging). Quickly went to 4GB+, does not seem to stop increasing. Releasing the mouse and waiting stops the memory usage growth but does not free it.

This does not happen with other (non-Flutter) apps.

**Comment by danagbemava-nc** [comment]
Hi @zura-kh, what are the specs of the device you're testing on? And what can you tell us about your device? I tested this on my dell xps 13 but I don't see any sharp memory increase when I resize the window. See the recording below. 

Also, how are you running the app? Are you running it with `flutter run --release` or are you building it first and then launching the `.exe` file that is generated? 

https://github.com/flutter/flutter/assets/88313112/a872a5d0-1164-42fa-b920-9d42d7677972

**Comment by zura-kh** [comment]
@danagbemava-nc 

> what are the specs of the device you're testing on?

13th gen i9 desktop CPU with _integrated Intel UHD 770 Graphics_.  Maybe this is the reason? i.e. you can't see abnormal memory usage growth because your device has a dedicated GPU, which is used by Flutter. Try measuring your GPU memory growth during window resizing. Please also try testing on a device with an integrated GPU.



> Also, how are you running the app? Are you running it with `flutter run --release` or are you building it first and then launching the `.exe` file that is generated?

I tried both with the same results.

**Comment by danagbemava-nc** [comment]
Hi @zura-kh, the device I'm testing on only has Intel UHD graphics, no other graphics card. It is a core i7 10th gen xps 13. I checked the |GPU memory usage, but there wasn't any spikes when I was resizing the window. 

There's a new version of the stable channel out, can you upgrade to that version to see if you still experience this?
