### ISSUE TITLE
ServiceMap's update method needs to be renamed before Dart 2.0.

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#14338]
flutter_tools has a [class ServiceObject](https://github.com/flutter/flutter/blob/10f721c8a5873a7477984507c1d0db7109049586/packages/flutter_tools/lib/src/vmservice.dart#L316) and a [class ServiceMap](https://github.com/flutter/flutter/blob/10f721c8a5873a7477984507c1d0db7109049586/packages/flutter_tools/lib/src/vmservice.dart#L1235) that `extends ServiceObject` and `implements Map`:

```dart
/// Base class of all objects received over the service protocol.
abstract class ServiceObject {
  /// Update [this] using [map] as a source. [map] can be a service reference.
  void update(Map<String, dynamic> map);
  /// Implemented by subclasses to populate their model.
  void _update(Map<String, dynamic> map, bool mapIsRef);
}

class ServiceMap extends ServiceObject implements Map<String, dynamic> {}
```

Unfortunately, Dart 2.0 is going to include a new `update` method for Map that updates a value with the result of a function:

```dart
dynamic update(String key, dynamic update(dynamic value), { dynamic ifAbsent() });
```

In order for ServiceMap to still implement Map in Dart 2.0, the existing `update` method (and presumably `_update` method) must be renamed. Something like `updateWith` and `_updateWith` would work.

**Comment by srawlins** [comment]
I have a change almost ready for this (using `updateWith` and `_updateWith`). I'll send a PR.

**Comment by srawlins** [comment]
CC @tvolkert

**Comment by tvolkert** [comment]
Yup, renaming it to `updateWith` sgtm

**Comment by Hixie** [comment]
Closing since the PR was closed. Please let me know if we actually still need this.
