### ISSUE TITLE
Replace deprecated `window`

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#143399]
```
• 'window' is deprecated and shouldn't be used. Look up the current
FlutterView from the context via View.of(context) or consult the PlatformDispatcher directly instead.
Deprecated to prepare for the upcoming multi-window support. This feature was deprecated after
v3.7.0-32.0.pre. Try replacing the use of the deprecated member with the replacement. •
deprecated_member_use
```

Many of these are part of the same calls as https://github.com/flutter/flutter/issues/143397

**Comment by ditman** [comment]
> it is not-obvious to me what the desired behavior of the code calling it would be in a multi-view context, so I can't do a mechanical fix here.

The mechanical fix in this case is to use `PlatformDispatcher.instance.implicitView`, which explodes on multi-view mode, but I'd say there's other things in this test that are broken in multi-view.

(Maybe related: https://github.com/flutter/flutter/issues/143883)

((PS: Preparing a PR with the mechanical fix I described above!))
