### ISSUE TITLE
Impeller compiler unit tests are not hermetic, can't be run by gtest-parallel.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#143330]
Tests can't run in parallel due to collisions on this directory:

https://github.com/flutter/engine/blob/main/impeller/compiler/compiler_test.cc#L13

These are part of impeller_unittests, which would be helpful to run with gtest-parallel. Otherwise `impeller_unittests` is likely too slow to run in unopt with asan etc. enabled.

**Comment by matanlurey** [comment]
I can take this issue Zach.

**Comment by chinmaygarde** [comment]
That just creates the directory structure if it doesn't already exist. Perhaps its is missing an `EEXIST` as not an `errno` check?

**Comment by zanderso** [comment]
The goal is to be able to add `gtest=True` as a parameter to this call to `run_engine_executable`, which confusingly causes the test binary to be wrapped in `gtest-parallel`.

**Comment by zanderso** [comment]
That one or any of the others. The one that I'd really like to run in parallel is this one:
https://github.com/flutter/engine/blob/main/testing/run_tests.py#L1203

Since that will unlock the ability to run `impeller_unittests` under sanitizers.

**Comment by matanlurey** [comment]
So far @jonahwilliams @christopherfujino @gaaclarke and myself all look at this in some capacity.

We're currently under the impression that these tests might never had really worked, and that `WriteAtomically`, at least on Linux, is flaky/unreliable. We were able to reproduce on @jonahwilliams's machine that we were getting failures even without `gtest-parallel`.

This code is not used much, and @gaaclarke suggested we just use the C++ 17 `filesystem` APIs and don't think too hard about how to fix this code. I'm inclined to agree.

**Comment by gaaclarke** [comment]
I didn't look at it much too but if you are parallelizing things across multiple processes then getting errors when moving a file, I suspect you are trying to move a file that a process is actively using.  One thing you could try to do is attach a uuid to the files that are used to guarantee that no 2 tests are using the same file.  Or maybe add the test name instead of a uuid.

**Comment by matanlurey** [comment]
@jason-simmons I assigned this to you just for tracking, but if you don't end up working on it feel free to throw back.
