### ISSUE TITLE
Make the `flutter/engine` block on untriaged goldens, similar to `flutter/flutter`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143352]
Currently, the gold integration in `flutter/engine` is _different_ than `flutter/flutter`:

- We allow PRs to land that create untriaged goldens, and some do so regularly (i.e. the Skia roller)
- Untriaged goldens do not turn the tree red

According to @zanderso, this is mostly due to historics and technical debt. My wording below:

- There isn't a good way to notify gardeners that a PR has stalled. [Some work](https://github.com/flutter/flutter/issues/125451) was done, but the email the gardener receive is not the best and is unlikely to improve in the short-term.
- A stalled roller would often stall for hours or days at a time, frustrating/slowing down upstream teams.

As a result, at the time of this writing, we have [almost 200 untriaged digests](https://flutter-engine-gold.skia.org/) (up about 10 from this AM):

![Screenshot 2024-02-12 at 5 42 22 PM](https://github.com/flutter/flutter/assets/168174/8980321c-4491-441b-9f3b-b6e7570fa770)

This has the following side-effects:

1. When Skia Gold doesn't filter based on PR as expected (happens often), 100s of untriaged digests show up instead of the (less than 100s) expected.
2. It's possible to regress due to out-of-stream updates (i.e. updates to Skia, Vulkan Deps, SwiftShader, etc) that aren't caught.

---

This issue is a proposal to change that. We would:

- [ ] Triage all untriaged goldens
- [ ] Block rollers that have untriaged goldens, expecting the engine gardener to intervene
- [ ] Turn the tree red if 1+ untriaged goldens exist, as we should never have any (similar to framework)

We believe this will most impact the gardener, and the web team (under @yjbanov).

/cc @jonahwilliams @Piinks @dnfield @yjbanov

**Comment by johnmccutchan** [comment]
This sounds great @matanlurey

**Comment by Piinks** [comment]
cc @mdebbar 
I am less familiar with how the engine uses Gold.
