### ISSUE TITLE
`Text` and `MarkdownBody` widgets are not using `liga` and `kern` OpenType `fontFeatures`

### ISSUE THREAD

**Issue by jcpsantiago** [flutter/flutter#143300]
### Steps to reproduce

Create a `Text` or `MarkdownBody` widget and set their `style`/`styleSheet` to use a font with `liga` and `kern` OpenType features (NOTE: these are usually turned on by default to begin with, which is the case in Source Serif Pro, the font I'm using in the reproducible example in https://github.com/jcpsantiago/flutter-opentypefeatures-bug):

```dart
final TextStyle fontStyle = TextStyle(
  fontSize: 32,
  fontFeatures: const <FontFeature>[FontFeature.enable('liga'), FontFeature.enable('kern')],
);
```

Also set the `AppBar` (or the the `fontFamily` via ThemeData) to use the same style.

### Expected results

`AppBar`, `Text` and `MarkdownBody` widgets should show text rendered the same way using ligatures and kerning (i.e. "correct" letter spacing).

Explicitly disabling the features should make `AppBar`'s text render the same as the other widgets:
 ```dart
final TextStyle fontStyle = TextStyle(
  fontSize: 32,
  fontFeatures: const <FontFeature>[FontFeature.disable('liga'), FontFeature.disable('kern')],
);

```

### Actual results

Only `AppBar` is rendered correctly, while `Text` and `MarkdownBody` (which uses `Text` internally) "ignore" these features and render the text without ligatures and wider letter spacing than expected i.e. no kerning.

Other OpenType features such as `frac` and `smcp` are correctly used (no screenshot of this).

Setting the style to use `FontFeature.disable("<liga/kern>")` does not change how the text in `AppBar` is rendered.

### Code sample

See https://github.com/jcpsantiago/flutter-opentypefeatures-bug (includes Source Serif Pro font).

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="375" alt="signal-2024-02-12-120352" src="https://github.com/flutter/flutter/assets/789796/f5784f15-747a-47ab-b972-ef1470438a29">

Different letter spacing (top from `AppBar`, bottom `Text`). Notice the pairs `os`, `se` and `or`:
![Screenshot 2024-02-12 at 12 33 59](https://github.com/flutter/flutter/assets/789796/5171dab3-e3f0-41df-9943-280f84a0f783)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.6.3 22G436 darwin-x64, locale en-DE)
    • Flutter version 3.16.9 on channel stable at /usr/local/Caskroom/flutter/3.16.9/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/santi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (2 available)
    • Eva 01 (mobile) • xxx • ios        • iOS 17.3.1 21D61
    • macOS (desktop) • macos                     • darwin-x64 • macOS 13.6.3 22G436 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by LongCatIsLooong** [comment]
The material 3 theme uses a non-zero letterspacing. IIRC in SkParagraph using a >0 letterspacing disables ligatures.

**Comment by jcpsantiago** [comment]
Got it. Not a bug then, I was simply caught by surprise. Issue can be closed.
