### ISSUE TITLE
Add empty privacy manifest to FlutterMacOS

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#143381]
We've been considering privacy manifests to be an iOS-only issue so far, but while [Required Reason APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc) explicitly list every platform **but** macOS, https://developer.apple.com/support/third-party-SDK-requirements/ doesn't actually specify anything about platform, and [privacy manifests](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) are for any platform—they just don't need `NSPrivacyAccessedAPITypes` on macOS (per the note on that page).

In practice, https://developer.apple.com/support/third-party-SDK-requirements/ doesn't list any of our macOS plugin implementations, and it doesn't list FlutterMacOS, so it's effectively iOS-only for us right now. However, adding an empty manifest to the engine on macOS would be easy, and would future-proof us against having to do work later that would need to percolate through the release channels (or require a cherry-pick), and should be harmless even if never needed. Given that, we should consider just going ahead and doing that.

(Signing might be more complex to do? I'm not clear on that part of the pipeline.)

/cc @cbracken @jmagman

**Comment by jmagman** [comment]
That wouldn't be too hard.  
1. Move [PrivacyInfo.xcprivacy](https://github.com/flutter/engine/blob/0ca2f38ef249948a1e1ebe55f108809ed3bf57ab/shell/platform/darwin/ios/framework/PrivacyInfo.xcprivacy) into `common`, update the `licenses_flutter` path
2. Add [`copy_framework_privacy_manifest`](https://github.com/flutter/engine/blob/400f156d6fbd8d3dd7307313e45e883a0ac84d43/shell/platform/darwin/ios/BUILD.gn#L385)to the `darwin/macos/BUILD.gn`

There aren't any codesigning implications to just adding the xcprivacy file.

See https://github.com/flutter/engine/pull/48951

Separately, once FlutterMacOS is built as a xcframework (https://github.com/flutter/engine/pull/50300) that should be codesigned. https://github.com/flutter/flutter/issues/140934 (also pretty easy to do). cc @vashworth

**Comment by stuartmorgan** [comment]
I'm not sure we want to share manifests; the required reason list audit ignored macOS-only files. It would be safer to have a manifest without that key at all on macOS, rather than us making claims that may not be accurate for macOS if Apple decides to expand it to macOS in the future.

**Comment by jmagman** [comment]
Fair enough, probably won't hurt anything, but easy enough to keep separate.

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/engine/pull/55078
