### ISSUE TITLE
[Impeller] Changes needed to get the OpenGL backend running on desktop Linux

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#143387]
After landing https://github.com/flutter/engine/pull/50416 I was able to get an app to run with the embedder using the Impeller GLES backend on desktop Linux.
But it required some additional changes for desktop OpenGL.

* Current versions of desktop OpenGL do not support the `GL_ALPHA` texture format in `glTexImage2D`.
  * The glyph atlas needs to instead use `GL_RED`.
* `BufferBindingsGLES::BindVertexAttributes` must bind to a vertex array object before calling `glVertexAttribPointer`

Also, the Linux/OpenGL embedder is no longer rendering anything on screen after https://github.com/flutter/engine/pull/50539.

https://github.com/flutter/engine/pull/50539 was originally specific to the Vulkan back end.  Does the OpenGL backend need to do something to match Vulkan's behavior?

@jonahwilliams @chinmaygarde

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/50539 actually fixed a bug in both Metal and Vulkan backends. (See https://github.com/flutter/flutter/issues/143324 ). I'm surprised that is causing problems on OpenGL, but do we have any sort of rendering error?

RE: GL_ALPHA

I have https://github.com/flutter/engine/pull/50534 which needs more adjustments, but we can change DesktopGL to use GL_RED instead.

**Comment by jonahwilliams** [comment]
err, by rendering error I mean something like a GL status code.

**Comment by jason-simmons** [comment]
The app does not report any failures of GL APIs.  But the Linux desktop embedder window is not painting anything.

**Comment by jonahwilliams** [comment]
which application are you running? I can try to debug a bit.

**Comment by jason-simmons** [comment]
That issue was happening because the call to `SurfaceFrame::Submit` made by `EmbedderExternalViewEmbedder::SubmitFlutterView` was rendering an empty display list.

Before https://github.com/flutter/engine/pull/50539 the empty display list would not render anything.  But with that change the GL backend was clearing the surface to transparent black.

Other `flutter::Surface` implementations support a `render_to_surface` flag.  The embedder can clear the flag to tell the `Surface` that the layers were rendered elsewhere and the frame submit callback should do nothing. `GPUSurfaceGLImpeller` needs to add support for this flag.
