### ISSUE TITLE
Rendering difference between canvaskit and skwasm for wonderous demo

### ISSUE THREAD

**Issue by Liedtke** [flutter/flutter#143317]
I compared
- https://vsm-wonderous-js-canvaskit.web.app/#/welcome (linear wasm)
- https://vsm-wonderous-wasm-skwasm.web.app/#/welcome (optimized wasmgc)

When clicking right on the #/welcome screen (note that with the links above apparently the URL has to be manually changed back to #/welcome as it keeps forwarding to #/home for me) the canvaskit application fades out the current picture and simultaneously fades in the new picture.
With skwasm the picture seems to just disappear (with a small delay?), then while the text is being "moved" only the black background is visible. After the text animation is finished, the new picture just seems to pop in.

CC @eyebrowsoffire

**Comment by eyebrowsoffire** [comment]
I think the root cause of this was addressed with https://github.com/flutter/engine/pull/50928, as I can no longer reproduce this problem after that change.
