### ISSUE TITLE
Two Flutter labs Windows Arm64 machines are offline - flutter-win-7 and flutter-win-8

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#143462]
### Type of Request

infra task

### Infrastructure Environment

Flutter labs bots that have self-quarantined due to ?1024 files in %TEMP%, and so are unavailable for the Dart CI builder
https://ci.chromium.org/ui/p/dart/builders/luci.dart.ci.sandbox/pkg-win-release-arm64 : 

bot:flutter-win-7.mtv.corp.google.com
bot:flutter-win-8.mtv.corp.google.com

### What is happening?

These 2 machines are in the dart CI pool used to run test builders, and both are offline.

**Comment by keyonghan** [comment]
Bots have been recovered.
