### ISSUE TITLE
win-8 is out of space, and needs attention

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#143457]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

win-8 is hitting the following issue and needs fixing:

> 1024 files in TEMP (C:\Users\swarming\AppData\Local\Temp)

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
Removing all files under folder /Users/Swarming/AppData/Local/Temp to clear the errors on win-8 Windows Bots.
