### ISSUE TITLE
Add a test that would have caught another Android engine Flutter "bad build" regression

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143484]
We should look at historic Flutter "bad builds" around external textures and platform views, and reproduce at least 1, possibly a few, within the `scenario_app` environment, and then check them in as tests to increase our confidence of shipping.

This is to validate all of the work that is being put into `scenario_app`.

/cc @xster

**Comment by xster** [comment]
@tugorez to share an example

**Comment by matanlurey** [comment]
Closing as not having something specific to do here, feel free to open a new issue.
