### ISSUE TITLE
go_router backButtonDispatcher

### ISSUE THREAD

**Issue by Mohdx** [flutter/flutter#143426]
### Question
Is there a method to detect the pressing of the back button on Android devices? 
The problem arises when invoking `context.go('/')`, triggering the `onExit` function, which contains `onWillPop()` aiming to hinder the user from exiting the app until they press the back button once more.

### Expected results

Expecting `GoRouter.of(context).backButtonDispatcher.hasCallbacks` to return `true` only on a press of a back button.

### Actual results/issue/bug

Current Result that `GoRouter.of(context).backButtonDispatcher.hasCallbacks` returns `true` even when navigation to any new route.

### Code sample

<details open><summary>Code sample</summary>

```dart
GoRoute(
        name: home,
        path: '/',
        onExit: (BuildContext context) {
          // Expecting `GoRouter.of(context).backButtonDispatcher.hasCallbacks` to return `true` only on a press of a back button.
          if (GoRouter.of(context).backButtonDispatcher.hasCallbacks) {
            return Tools.onWillPop();
          }
          return true;
        },
        builder: (BuildContext context, GoRouterState state) {
          return Structure(query: state.uri.queryParameters);
        },
        routes: <GoRoute>[
        ...
```

</details>

**Comment by darshankawar** [comment]
@Mohdx 
Check below issues to see if they help to resolve your question or not.

https://github.com/flutter/flutter/issues/139398
https://github.com/flutter/flutter/issues/135094
