### ISSUE TITLE
Full stdout is being presented in the flaky step

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#143463]
### Type of Request

bug

### Infrastructure Environment

Recipes, LUCI

### What is happening?

It looks like with the recent change to log streaming we are sometimes(?) getting the full stdout string in the LUCI UI step presentation. 

see: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20module_host_with_custom_build_test/17480/overview

Looks like the string is encode which might be producing the extraordinarily long string.

### Steps to reproduce

The issue presented during a flaky run of Windows module_host_with_custom_build_test.

### Expected results

Normal output presentation without the encode string.

**Comment by ricardoamador** [comment]
https://flutter-review.googlesource.com/c/recipes/+/55186

@keyonghan do you mind if I assign this issue to you?

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/55186 updates the logs and step status, but the log link needs a fix.

**Comment by keyonghan** [comment]
Last piece to close this bug: https://flutter-review.googlesource.com/c/recipes/+/55221

**Comment by ricardoamador** [comment]
Thanks for quick fix here @keyonghan!

**Comment by keyonghan** [comment]
Working as expected: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64_ios%20module_test_ios/10379/overview. Closing.
