### ISSUE TITLE
[ios]Platform view always has a FlutterOverlayView of height 1, even when there's no overlap between flutter widget and platform view. 

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#143420]
By running the example with multiple ad banners, and inspect the view hierarchy. We notice that each platform view is accompanied with an overlay view of height 1 pixel (0.5 points)

![1 pixel height overlay](https://github.com/flutter/flutter/assets/41930132/60bea4e5-75d6-40b7-9571-fcb4975c8f8c)

### Proposal

This is related to the [unobstructed platform view](https://docs.google.com/document/d/1ESHoQq1i2_WQAH1dIcYOCbPG73_ELrB8SmR6KEmLZUE/edit?tab=t.0#heading=h.7wjtkl7wgx3l) work. I suspect that this is due to [roundOut](https://api.skia.org/structSkRect.html#a8a82140d34549c4add33cd988c7dded8) when computing the intersection of flutter widgets and platform view. 

For example, if we interleave flutter widget and platform view in a list, and let's say we have a flutter widget (top = 0, bottom = 100.1), and a platform view below that widget (top = 100.1, bottom = 200). They are NOT supposed to be overlapping. 

However, after rounding out (expanding out), we will get flutter widget (top = 0, bottom = 101), and platform view (top = 100, bottom 200). This will result in 1 pixel overlap as long as there's a floating point in the coord. 

Likely can be resolved in `flow` level, but can experiment on iOS embedder first.

**Comment by jonahwilliams** [comment]
Looks like this might be the cause of https://github.com/flutter/flutter/issues/142817 ?

**Comment by hellohuanlin** [comment]
> Looks like this might be the cause of #142817 ?

Very possible. if i am not mistaken, it should reduce the number of frames submitted, which i should be able to check. This feels quite promising.
