### ISSUE TITLE
Flutter Web displays fonts in a different way in different environments and devices

### ISSUE THREAD

**Issue by RohithKilaparthi** [flutter/flutter#143442]
### Steps to reproduce

We are using a custom font (Gilroy) that is applied to the entire app by default in the Material App

Text(
       "Enter your mobile number",
        style: style(
          color: Colors.black,
          fontSize: 24,
          fontWeight: FontWeight.w400,
        ),
      ),

### Expected results

The text should be displayed similarly on any platform

### Actual results

It is displayed as if the properties of the font on different devices is different

### Code sample

<details open><summary>Code sample</summary>

```dart

Text(
       "Enter your mobile number",
        style: style(
          color: Colors.black,
          fontSize: 24,
          fontWeight: FontWeight.w400,
        ),
      ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Comparison](https://github.com/flutter/flutter/assets/13035828/54b6ba0a-4d17-40c4-972f-9243edf175aa)
</details>

### Logs

<details open><summary>Logs</summary>

```
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```
flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.12.0-4.0.pre.72, on Microsoft Windows [Version 10.0.22000.2538], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[!] Android Studio (version 2022.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.86.1)
[√] Connected device (2 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by devfemibadmus** [comment]
> [Comparison](https://github.com/flutter/flutter/assets/13035828/54b6ba0a-4d17-40c4-972f-9243edf175aa)
![Comparison](https://github.com/flutter/flutter/assets/13035828/54b6ba0a-4d17-40c4-972f-9243edf175aa)

**Comment by iapicca** [comment]
possibly related to 
- https://github.com/flutter/flutter/issues/77023
see [comment](https://github.com/flutter/flutter/issues/97909#issue-1125266477)

**Comment by huycozy** [comment]
Hi @RohithKilaparthi 
I don't see you use `Gilroy` font on your sample code. For us to investigate this issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 

Also, you are using an old Flutter version. Could you try upgrading to the latest stable/master channel and re-check this? Thanks!
