### ISSUE TITLE
Customize floatingLabelStyle for error in InputDecorationTheme

### ISSUE THREAD

**Issue by BuyMyBeard** [flutter/flutter#143488]
### Use case

I want to customize my TextField entirely through themeData so I don't have to create a specific widget as a wrapper for it.

Right now my form field looks like this: 
![image](https://github.com/flutter/flutter/assets/95039323/1c29771d-ea21-453c-81aa-7fc15259009c)
![image](https://github.com/flutter/flutter/assets/95039323/274b61fd-207d-461b-bec0-0aebdaff192a)
![image](https://github.com/flutter/flutter/assets/95039323/1a3fe973-1b54-49f0-bbb1-a7f5c44cc7bb)
![image](https://github.com/flutter/flutter/assets/95039323/53439733-233b-46dc-9171-203363d3ea88)

InputDecorationTheme doesn't expose any parameters to customize textStyle of floatingLabel when validating textField with an error. I can't change the color of the floatingLabel when focused on the textField, and unfocusing it makes the label take the default dark theme error color.

![image](https://github.com/flutter/flutter/assets/95039323/ec375336-3e82-4784-ab22-bceb78b6bb43)

### Proposal

Give inputDecorationTheme optional parameters focusedErrorFloatingLabelStyle and errorFloatingLabelStyle.

**Comment by nate-thegrate** [comment]
Hey @BuyMyBeard, thanks for submitting this issue!

If/when my pull request is merged and included in a release, you'll be able to do the following:

```dart
const inputDecorationTheme = InputDecorationTheme(
  floatingLabelStyle: InputDecorationStyle(
    normal: TextStyle(color: Colors.orange),
    error: TextStyle(color: Colors.red),
    focusedError: TextStyle(color: Colors.redAccent),
  ),
);
```

For now, feel free to use this:

```dart
final inputDecorationTheme = InputDecorationTheme(
  floatingLabelStyle: MaterialStateTextStyle.resolveWith((states) {
    if (states.contains(MaterialState.error)) {
      if (states.contains(MaterialState.focused)) {
        return const TextStyle(color: Colors.redAccent);
      }
      return const TextStyle(color: Colors.red);
    }
    return const TextStyle(color: Colors.orange);
  }),
);
```

**Comment by nate-thegrate** [comment]
It looks like a convenient `floatingLabelStyle` constructor won't be added anytime soon.

For now, the best solution is to extend the `MaterialStateTextStyle` class or to use its `.resolveWith()` constructor.

**Comment by nate-thegrate** [comment]
Update: `WidgetState.map()` constructor has been implemented, tests are passing, and PR is approved!

Just waiting on a final thumbs-up and we'll be good to go 👍👍

**Comment by nate-thegrate** [comment]
New `WidgetStateProperty` constructor just dropped:

```dart
const InputDecorationTheme(
  floatingLabelStyle: WidgetStateTextStyle.fromMap({
    WidgetState.error:   TextStyle(color: AppColor.red),
    WidgetState.focused: TextStyle(color: AppColor.orange),
    WidgetState.any:     TextStyle(color: AppColor.grey),
  }),
),
```
