### ISSUE TITLE
Tutorial: how to access Android services like Camera

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1434]
_From @sethladd on November 5, 2015 23:22_

Assuming some services come pre-bundled (I don't need to write a mojom), it would be helpful to show our new users how that can:

* find what services are available
* what it means to access a service
* how to use one of the services as an example (e.g. camera)

_Copied from original issue: flutter/website#49_

**Comment by sethladd** [comment]
Dupe
