### ISSUE TITLE
showDialog should take a builder rather than a child

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#14341]
...so that any `context` passed to children is the right context (the one inside the dialog route, instead of the one the dialog is using to find the navigator).

**Comment by mravn-google** [comment]
So instead of
```dart
showDialog(context: context, child: myWidget);
```
I guess we'd write
```dart
showDialog(
  context: context,
  builder: new Builder(builder: (_) => myWidget),
);
```
If we expand the _ it would almost read like poetry :-)

Would it make sense to reduce on the number of times we mention `builder` here with a signature such as `showDialog(BuildContext, WidgetBuilder)` and do
```dart
showDialog(
  context: context,
  builder: (_) => myWidget,
);
```

**Comment by jonahwilliams** [comment]
@mravn-google I think that is a much nicer API, I don't see any disadvantage to just passing the closure

**Comment by mravn-google** [comment]
@jonahwilliams `MaterialPageRoute` takes a `WidgetBuilder` argument too, so there is at least one precedent for doing it that way. It is not clear to me if @Hixie actually meant a builder or a Builder.

**Comment by Hixie** [comment]
definitely the closure, this is a well established pattern.

One thing we might want to do is accept both child and builder, and pass the child to the builder, like we do in AnimationBuilder.

**Comment by Malouda** [comment]
> So instead of
> 
> ```dart
> showDialog(context: context, child: myWidget);
> ```
> 
> I guess we'd write
> 
> ```dart
> showDialog(
>   context: context,
>   builder: new Builder(builder: (_) => myWidget),
> );
> ```
> 
> If we expand the _ it would almost read like poetry :-)
> 
> Would it make sense to reduce on the number of times we mention `builder` here with a signature such as `showDialog(BuildContext, WidgetBuilder)` and do
> 
> ```dart
> showDialog(
>   context: context,
>   builder: (_) => myWidget,
> );
> ```

why are we passing   _   as argument to the closure of the builder argument?
