### ISSUE TITLE
Delete the 2018-era Android v1 embedder

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143531]
(Partial copy from chat in another castle)

I asked about the status of https://flutter.dev/go/android-project-migration because we have two copies of the Android embedding libraries: [old](https://github.com/flutter/engine/blob/a9081cce1f0dd730577a36ee1ca6d7af5cdc5a9b/shell/platform/android/io/flutter/view/FlutterView.java#L72-L79), [new](https://github.com/flutter/engine/blob/a9081cce1f0dd730577a36ee1ca6d7af5cdc5a9b/shell/platform/android/io/flutter/embedding/android/FlutterView.java), and I struggled to understand what the plan is to delete the former, or if there is any plan.

@johnmccutchan mentioned:

> _old_ has been deprecated since before I joined the team. It is on my list of things to delete when we do a spring cleaning on the android embedder ... there is no official plan but I have intentionally not been implementing new features in _old_. 

@jonahwilliams mentioned:

> The embedding v2 has been the default since like 2018.

I have no idea if this code is used in our own CI or google3/customer testing, so I guess there is one way to find out.

**Comment by matanlurey** [comment]
Unassigning as I have enough work on my plate.

**Comment by gmackall** [comment]
I'm currently working on this, adding a task list to help track 
- [ ] Delete references to v1 embedding in framework/tool code (done in https://github.com/flutter/flutter/pull/144726)
- [ ] Finish out b/227653111 (cl in progress)
- [ ] Delete the embedding in the engine (pending https://github.com/flutter/engine/pull/51229, waiting on above)

**Comment by gmackall** [comment]
Reopening for now, will close when the roll ->framework->g3 completes

**Comment by ricardoamador** [comment]
Why does it say I closed this?

**Comment by gmackall** [comment]
I think if a commit contains "fixes <issue_link>", and then you update your fork with the github ui, it re-closes any associated issues, unfortunately. 

Which means this happens a lot when an issue is fixed and then reverted, and then someone updates their branch which includes pulling in the fix that was reverted.

**Comment by ricardoamador** [comment]
Ah okay, it makes me feel a little better that this isn't just happening because of something I happened to do.
