### ISSUE TITLE
[Impeller] Concurrent VkPipeline creation is slow on Mokey Device.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#143540]
Impeller will create min(4, hardware_concurrency) threads to boot strap VkPipelines after creating the context_vk. On the Mokey deivce, using 4 threads is actually much slower than using 1.  The Mokey is only a 4 core device so at a minimum we should reduce the max concurrency to something like hardware_concurrency / 2.

### 4 thread (~3 seconds)

![image](https://github.com/flutter/flutter/assets/8975114/3c953dca-4e55-4c09-a5ac-18e4d8a91626)

### 1 thread ( ~ 2 seconds)

![image](https://github.com/flutter/flutter/assets/8975114/009a9eb6-cb04-4926-81d4-b641000a75c6)

We should figure out how to adjust the concurrency level based on device performance.

**Comment by jonahwilliams** [comment]
We could potentially add a "lazy bootstrap" setting, though we'd need to make sure the context can handle shaders with no immediate default.

**Comment by jonahwilliams** [comment]
A potentially better solution:

1. one pipeline cache per thread. Not externally sychronized, no internal synchronization.
2. Use https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkMergePipelineCaches.html at the end.

**Comment by jonahwilliams** [comment]
FYI @chinmaygarde  ^

**Comment by gaaclarke** [comment]
Another option for speeding this up that jonah pointed out is that `vkCreateGraphicsPipelines` can take in multiple arguments.  Currently it is called once for each pipeline we create.

The vulkan spec states:
> Applications can group together similar pipelines to be created in a single call, and implementations are encouraged to look for reuse opportunities when creating a group.

That means there may be savings that can only be achieved with batching `vkCreateGraphicsPipelines`.  It's plausible that creating a triangle and a triangle strip variant of a pipeline may have overlapping calculations that can be reused.

Letting the driver manage parallelism may lead to worse performance on particular devices though.

**Comment by gaaclarke** [comment]
Here is a profile that Jia Hao did too.  We can see that while we have 2 worker threads, they are mostly operating serially.

<img width="1059" alt="Screenshot 2024-04-18 at 10 06 09 AM" src="https://github.com/flutter/flutter/assets/30870216/c0cea48e-5395-4309-bb55-317ffea86ef2">

**Comment by gaaclarke** [comment]
Here is a doc with a class diagram and a sequence diagram for pipeline creation for background information to help understand how this works today: https://docs.google.com/document/d/1MzL_U4M63BEyg35asxksZ-fQTi0gLBHiCO48kVXXMe8/edit#heading=h.l5nbn6yk543e

**Comment by chinmaygarde** [comment]
I think I initially misunderstood @jonahwilliams suggestion about the pipeline caches per thread that are eventually merged. I was incorrectly operating under the assumption that this would need `VK_PIPELINE_CACHE_CREATE_EXTERNALLY_SYNCHRONIZED_BIT` from `VK_EXT_pipeline_creation_cache_control`. But the synchronization overhead isn't the issue, its the actual contention. So I do think that a fine start and should give us an immediate improvement on the Mokey. On subsequent runs, we can initialize the TLS caches using the same merged blob and then re-merge before saving back to disk.

@gaaclarke s suggestion is interesting and I haven't tried if it actually improves things. I did try `VK_PIPELINE_CREATE_DERIVATIVE_BIT` for the pipeline variants but that didn't move the needle at all. So it may depend on the driver. But, it should be possible to build this on top of @jonahwilliams suggestion.

**Comment by gaaclarke** [comment]
It looks like every time we create a pipeline we also allocate a new render pass (see `renderPass` in  https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkGraphicsPipelineCreateInfo.html).

Another optimization that we could do is to use the same render pass when allocating all the default pipelines.  That field seems to be used for setup and as long as all the render passes are the same setup, they should be equivalent.

**Comment by gaaclarke** [comment]
I profiled on a pixel 4a and I don't see the same serialization problem happening.  Creating the pipelines is taking up 550ms.

<img width="1648" alt="Screenshot 2024-04-22 at 3 01 25 PM" src="https://github.com/flutter/flutter/assets/30870216/fc8a90e0-a48b-448a-a0a8-665a6d603b2f">

https://ui.perfetto.dev/#!/?s=3a3959a7cc3a6e2f315c6e7b95414b2090f3b360ccd80fd6f0487186655ed23d

That seems to indicate that the serialization is happening in the driver.

Profiled at 259bc4b44987f0cc14a24e84c273dd3898fd2212

**Comment by gaaclarke** [comment]
As an experiment I turned off the cache and it ended up taking 2x as long.
```diff
--- a/impeller/renderer/backend/vulkan/pipeline_cache_vk.cc
+++ b/impeller/renderer/backend/vulkan/pipeline_cache_vk.cc
@@ -121,7 +121,7 @@ vk::UniquePipeline PipelineCacheVK::CreatePipeline(
   }
 
   auto [result, pipeline] =
-      strong_device->GetDevice().createGraphicsPipelineUnique(*cache_, info);
+      strong_device->GetDevice().createGraphicsPipelineUnique(nullptr, info);
   if (result != vk::Result::eSuccess) {
     VALIDATION_LOG << "Could not create graphics pipeline: "
                    << vk::to_string(result);
@@ -137,7 +137,7 @@ vk::UniquePipeline PipelineCacheVK::CreatePipeline(
   }
 
   auto [result, pipeline] =
-      strong_device->GetDevice().createComputePipelineUnique(*cache_, info);
+      strong_device->GetDevice().createComputePipelineUnique(nullptr, info);
   if (result != vk::Result::eSuccess) {
     VALIDATION_LOG << "Could not create compute pipeline: "
                    << vk::to_string(result);
```
profile: https://ui.perfetto.dev/#!/?s=d803805446dbf6e7c4ebaae9467acf98036700a8b486e27b59b594765d958fc4

**Comment by gaaclarke** [comment]
Okay, I was able to get [batching working](https://github.com/flutter/engine/pull/52311).  I batched up a handful of pipelines, whichever were convenient to batch.  The results are negative.  It looks like it takes the same amount of time but the bigger batch size leads to worse parallelization where ultimately all threads were left waiting on a single batch job to finish.

<img width="537" alt="Screenshot 2024-04-23 at 2 33 27 PM" src="https://github.com/flutter/flutter/assets/30870216/e2f2521a-1576-4af8-9c36-181c18478bf2">

https://ui.perfetto.dev/#!/?s=7dd410c583a55a8fb77c4d6ee5f3996b14491a00c2b56d61f9b81be11b3ebfe2

**Comment by gaaclarke** [comment]
> Is there a trace for the version captured earlier in [#143540 (comment)](https://github.com/flutter/flutter/issues/143540#issuecomment-2064753404)?

It's in this internal doc: https://docs.google.com/document/d/1n7im-6EaeRYlerbuBtJayg2zWEDjgVMXuJx7elpT0JU/edit?tab=t.0#heading=h.ybl0gfg8pr0r

> It looks like your version is getting core utilization.

Yea, I was [seeing that on the pixel 4a](https://github.com/flutter/flutter/issues/143540#issuecomment-2071027694) before this change though too.  It is possible that batching does make a difference with the mokey.  I'm not sure we'd want to accept something that regresses other devices though.

**Comment by chinmaygarde** [comment]
> I'm not sure we'd want to accept something that regresses other devices though.

Yeah. I think squeezing the pipeline counts seems like a better way to go. Did we try the per thread pipeline cache with subsequent merge?

**Comment by gaaclarke** [comment]
> Yeah. I think squeezing the pipeline counts seems like a better way to go. Did we try the per thread pipeline cache with subsequent merge?

Not yet.  I can try that out starting tomorrow.  I need a little breather from this.

**Comment by jonahwilliams** [comment]
I have a few more clean ups that will reduce shader count, namely the removal of points.comp (which doesn't provide much speedup over the CPU computation right now), the removal of uv.comp, and the removal of position_color.vert and vertices.frag.

We could:
* Combine glyph_atlas.frag and glyph_atlas_color.frag (not working on this now).
* Go back to using the solid_fill shader for clip.frag.
* Find a way to do the texture_fill_strict_src math on the CPU.
* Remove KernelDecal/NoDecal on platforms that only need 1 due to natively supported decal.


Beyond that, we could explore lazy initialization for certain infrequently used shader variants. This has a risk of introducing jank though.

**Comment by jonahwilliams** [comment]
@gaaclarke when I'm at the office tomorrow I'll try your patch on a mokey. If its negative there I say we probably have to abandon the effort.

**Comment by gaaclarke** [comment]
# Merge pipeline caches design sketch

Implementing the merge behavior is going to be tricky:

1) There needs to be a mechanism to switch over worker threads to the new merged
   cache.  In order to preserve paralellism, it would have to be a
   stop-the-world mechanism for the worker threads.
1) Using a pipeline cache will now dynamically have to decide if a mutex is
   necessary, as is the case for the merged cache, or not.

It will have to look something like this:

```c++
static PipelineCache merged_cache;
static Mutex merged_mutex;
static atomic<bool> did_merge = false;
static thread_local PipelineCache tls_cache;
static vector<PipelineCache*> caches;
static Mutex caches_mutex;

void ContentContext::InitializeDefaultPipelines() {
  foo_pipeline_.CreateDefault();
  bar_pipeline_.CreateDefault();
  //...

  shared_ptr<atomic<int>> counter(worker_pool_.count());
  // `ForEachWorker` doesn't exist but posts the same task to all workers.
  worker_pool_.ForEachWorker([counter]{
    if (counter->fetch_sub(1) == 0) {
      // Now we know that all default pipelines have finished.

      // `PostStopTheWorld` doesn't exist today but blocks all threads except
      // one who executes. 
     worker_pool_->PostStopTheWorld([]{
        MergePipelines();
      });
    }
  });
}

ContentContext::~ContentContext() {
  worker_pool_.ForEachWorker([]{
    tls_cache.reset();
  });
}

Pipeline PipelineCacheVK::CreatePipeline(PipelineCreateInfo info) {
  if (did_merge.load()) {
    Lock lock(merged_mutex);
    return device_->CreatePipeline(merged_cache, info);
  }
  if (!tls_cache) {
    tls_cache = device_->CreatePipelineCache();
    Lock lock(caches_mutex);
    caches.push_back(&tls_cache);
  }
  return device_->CreatePipeline(tls_cache, info);
}

void PipelineCacheVK::MergePipelines() {
  // No need for caches_mutex or merged_mutex since this is executed in
  // StopTheWorld.
  merged_cache = device_->MergePipelines(caches);
  did_merge.store(true);
}
```

Explored alternatives:

1) Don't use StopTheWorld -- This resulted in serializing usage of tls_cache
   because we had to make sure they weren't used while a merge was happening.

**Comment by jonahwilliams** [comment]
I think the TLS cache is likely not worth pursuing. Since the cacheless initial bootstrap had the same or worse performance, its likely that we're serialized in the driver shader compilation and not in cache read/write.

**Comment by gaaclarke** [comment]
> I think the TLS cache is likely not worth pursuing. Since the cacheless initial bootstrap had the same or worse performance, its likely that we're serialized in the driver shader compilation and not in cache read/write.

There was the hypothesis that the worse performance without a cache was because the cache provides a speed boost when creating subsequent pipelines.  As a quick check we could try profiling with just a tls cache, but no merge.

**Comment by jonahwilliams** [comment]
Yeah seems like a reasonable idea

**Comment by gaaclarke** [comment]
Thread local caches without merges were slower too on a pixel4a:

https://ui.perfetto.dev/#!/?s=2bec2aca8611ae2e454d1c0043ad1a8b7cfd41091b50ddd53453da6a719f1df2

<img width="1323" alt="Screenshot 2024-04-24 at 12 37 30 PM" src="https://github.com/flutter/flutter/assets/30870216/2beae0b2-b174-4d9d-931c-7ab21945d128">

<details>

```diff
diff --git a/impeller/entity/contents/content_context.cc b/impeller/entity/contents/content_context.cc
index 1a7a8a9b02..dd93f2f8e0 100644
--- a/impeller/entity/contents/content_context.cc
+++ b/impeller/entity/contents/content_context.cc
@@ -266,6 +266,11 @@ ContentContext::ContentContext(
     return;
   }
 
+  {
+    TRACE_EVENT0("flutter", "WaitingForPipelines");
+    sleep(15);
+  }
+
   auto options = ContentContextOptions{
       .sample_count = SampleCount::kCount4,
       .color_attachment_pixel_format =
diff --git a/impeller/renderer/backend/vulkan/pipeline_cache_vk.cc b/impeller/renderer/backend/vulkan/pipeline_cache_vk.cc
index 49ee504e5b..fc9af4052c 100644
--- a/impeller/renderer/backend/vulkan/pipeline_cache_vk.cc
+++ b/impeller/renderer/backend/vulkan/pipeline_cache_vk.cc
@@ -13,45 +13,74 @@
 
 namespace impeller {
 
+static thread_local vk::UniquePipelineCache tls_cache;
+static std::mutex s_caches_mutex;
+static std::vector<vk::PipelineCache*> s_caches;
+static vk::UniquePipelineCache s_merged_cache;
+static std::mutex s_merged_cache_mutex;
+
+static vk::PipelineCache& GetPipelineCache(
+    const std::shared_ptr<DeviceHolderVK>& device_holder) {
+  if (!tls_cache) {
+    vk::PipelineCacheCreateInfo cache_info;
+    cache_info.flags = vk::PipelineCacheCreateFlagBits::eExternallySynchronized;
+
+    auto [result, cache] =
+        device_holder->GetDevice().createPipelineCacheUnique(cache_info);
+    FML_CHECK(result == vk::Result::eSuccess);
+    {
+      std::scoped_lock lock(s_caches_mutex);
+      s_caches.push_back(&cache.get());
+    }
+    tls_cache = std::move(cache);
+  }
+  return tls_cache.get();
+}
+
+void MergePipelineCaches() {
+  std::scoped_lock lock(s_caches_mutex);
+
+}
+
 static constexpr const char* kPipelineCacheFileName =
     "flutter.impeller.vkcache";
 
-static bool VerifyExistingCache(const fml::Mapping& mapping,
-                                const CapabilitiesVK& caps) {
-  return true;
-}
+// static bool VerifyExistingCache(const fml::Mapping& mapping,
+//                                 const CapabilitiesVK& caps) {
+//   return true;
+// }
 
 static std::shared_ptr<fml::Mapping> DecorateCacheWithMetadata(
     std::shared_ptr<fml::Mapping> data) {
   return data;
 }
 
-static std::unique_ptr<fml::Mapping> RemoveMetadataFromCache(
-    std::unique_ptr<fml::Mapping> data) {
-  return data;
-}
-
-static std::unique_ptr<fml::Mapping> OpenCacheFile(
-    const fml::UniqueFD& base_directory,
-    const std::string& cache_file_name,
-    const CapabilitiesVK& caps) {
-  if (!base_directory.is_valid()) {
-    return nullptr;
-  }
-  std::unique_ptr<fml::Mapping> mapping =
-      fml::FileMapping::CreateReadOnly(base_directory, cache_file_name);
-  if (!mapping) {
-    return nullptr;
-  }
-  if (!VerifyExistingCache(*mapping, caps)) {
-    return nullptr;
-  }
-  mapping = RemoveMetadataFromCache(std::move(mapping));
-  if (!mapping) {
-    return nullptr;
-  }
-  return mapping;
-}
+// static std::unique_ptr<fml::Mapping> RemoveMetadataFromCache(
+//     std::unique_ptr<fml::Mapping> data) {
+//   return data;
+// }
+
+// static std::unique_ptr<fml::Mapping> OpenCacheFile(
+//     const fml::UniqueFD& base_directory,
+//     const std::string& cache_file_name,
+//     const CapabilitiesVK& caps) {
+//   if (!base_directory.is_valid()) {
+//     return nullptr;
+//   }
+//   std::unique_ptr<fml::Mapping> mapping =
+//       fml::FileMapping::CreateReadOnly(base_directory, cache_file_name);
+//   if (!mapping) {
+//     return nullptr;
+//   }
+//   if (!VerifyExistingCache(*mapping, caps)) {
+//     return nullptr;
+//   }
+//   mapping = RemoveMetadataFromCache(std::move(mapping));
+//   if (!mapping) {
+//     return nullptr;
+//   }
+//   return mapping;
+// }
 
 PipelineCacheVK::PipelineCacheVK(std::shared_ptr<const Capabilities> caps,
                                  std::shared_ptr<DeviceHolderVK> device_holder,
@@ -65,39 +94,41 @@ PipelineCacheVK::PipelineCacheVK(std::shared_ptr<const Capabilities> caps,
 
   const auto& vk_caps = CapabilitiesVK::Cast(*caps_);
 
-  auto existing_cache_data =
-      OpenCacheFile(cache_directory_, kPipelineCacheFileName, vk_caps);
-
-  vk::PipelineCacheCreateInfo cache_info;
-  if (existing_cache_data) {
-    cache_info.initialDataSize = existing_cache_data->GetSize();
-    cache_info.pInitialData = existing_cache_data->GetMapping();
-  }
-
-  auto [result, existing_cache] =
-      device_holder->GetDevice().createPipelineCacheUnique(cache_info);
-
-  if (result == vk::Result::eSuccess) {
-    cache_ = std::move(existing_cache);
-  } else {
-    // Even though we perform consistency checks because we don't trust the
-    // driver, the driver may have additional information that may cause it to
-    // reject the cache too.
-    FML_LOG(INFO) << "Existing pipeline cache was invalid: "
-                  << vk::to_string(result) << ". Starting with a fresh cache.";
-    cache_info.pInitialData = nullptr;
-    cache_info.initialDataSize = 0u;
-    auto [result2, new_cache] =
-        device_holder->GetDevice().createPipelineCacheUnique(cache_info);
-    if (result2 == vk::Result::eSuccess) {
-      cache_ = std::move(new_cache);
-    } else {
-      VALIDATION_LOG << "Could not create new pipeline cache: "
-                     << vk::to_string(result2);
-    }
-  }
-
-  is_valid_ = !!cache_;
+  // auto existing_cache_data =
+  //     OpenCacheFile(cache_directory_, kPipelineCacheFileName, vk_caps);
+
+  // vk::PipelineCacheCreateInfo cache_info;
+  // if (existing_cache_data) {
+  //   cache_info.initialDataSize = existing_cache_data->GetSize();
+  //   cache_info.pInitialData = existing_cache_data->GetMapping();
+  // }
+
+  // auto [result, existing_cache] =
+  //     device_holder->GetDevice().createPipelineCacheUnique(cache_info);
+
+  // if (result == vk::Result::eSuccess) {
+  //   cache_ = std::move(existing_cache);
+  // } else {
+  //   // Even though we perform consistency checks because we don't trust the
+  //   // driver, the driver may have additional information that may cause it
+  //   to
+  //   // reject the cache too.
+  //   FML_LOG(INFO) << "Existing pipeline cache was invalid: "
+  //                 << vk::to_string(result) << ". Starting with a fresh
+  //                 cache.";
+  //   cache_info.pInitialData = nullptr;
+  //   cache_info.initialDataSize = 0u;
+  //   auto [result2, new_cache] =
+  //       device_holder->GetDevice().createPipelineCacheUnique(cache_info);
+  //   if (result2 == vk::Result::eSuccess) {
+  //     cache_ = std::move(new_cache);
+  //   } else {
+  //     VALIDATION_LOG << "Could not create new pipeline cache: "
+  //                    << vk::to_string(result2);
+  //   }
+  // }
+
+  is_valid_ = true;
 }
 
 PipelineCacheVK::~PipelineCacheVK() {
@@ -121,7 +152,8 @@ vk::UniquePipeline PipelineCacheVK::CreatePipeline(
   }
 
   auto [result, pipeline] =
-      strong_device->GetDevice().createGraphicsPipelineUnique(*cache_, info);
+      strong_device->GetDevice().createGraphicsPipelineUnique(
+          GetPipelineCache(strong_device), info);
   if (result != vk::Result::eSuccess) {
     VALIDATION_LOG << "Could not create graphics pipeline: "
                    << vk::to_string(result);
@@ -137,7 +169,8 @@ vk::UniquePipeline PipelineCacheVK::CreatePipeline(
   }
 
   auto [result, pipeline] =
-      strong_device->GetDevice().createComputePipelineUnique(*cache_, info);
+      strong_device->GetDevice().createComputePipelineUnique(
+          GetPipelineCache(strong_device), info);
   if (result != vk::Result::eSuccess) {
     VALIDATION_LOG << "Could not create compute pipeline: "
                    << vk::to_string(result);
@@ -154,8 +187,8 @@ std::shared_ptr<fml::Mapping> PipelineCacheVK::CopyPipelineCacheData() const {
   if (!IsValid()) {
     return nullptr;
   }
-  auto [result, data] =
-      strong_device->GetDevice().getPipelineCacheData(*cache_);
+  auto [result, data] = strong_device->GetDevice().getPipelineCacheData(
+      GetPipelineCache(strong_device));
   if (result != vk::Result::eSuccess) {
     VALIDATION_LOG << "Could not get pipeline cache data to persist.";
     return nullptr;
```

</details>

**Comment by jonahwilliams** [comment]
We've reduced the shader count as much as we can (~50 down to ~30) and moved bootstrapping as early as possible. Closing as fixed (as well as it can be).
