### ISSUE TITLE
[web][engine dev] Remove test_core internals from test_platform.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#143599]
While adding a new lint to the engine repo ([PR](https://github.com/flutter/engine/pull/50727)), @goderbauer needed to add a bunch of `//ignore: implementation_imports` to some of our script tools, because they're importing from `package:test_core/src/...`

Is there any way of achieving the same without importing from private bits of a dependency? This can make the dependency very hard to update!

(If not possible, IMO we should document the reason in this ticket or somewhere, and then link to the *why* from the code itself).

**Comment by yjbanov** [comment]
Unfortunately, this is the standard way to import these libraries. This is also what the [Flutter Tool does](https://github.com/flutter/flutter/blob/52d45c41846c225f773df39d9a4f6b8ad8a32a5a/packages/flutter_tools/lib/src/test/test_wrapper.dart#L7). For as long as this is considered a "feature" in the test runner I don't think it's actionable on the Flutter side (I forget how it went exactly, but I think the justification was that there shouldn't be too many custom runners, and so implementation import is a way to discourage them, although the Flutter team did ask that custom runners are made part of the public API).

Closing, but feel free to reopen if you disagree.

**Comment by ditman** [comment]
I don't disagree, but this may become a problem / break things if the `implementation_imports` lint becomes un-ignorable somehow.
