### ISSUE TITLE
[video_player] Configuration option to allow negative playback speed / reverse playback

### ISSUE THREAD

**Issue by tannker** [flutter/flutter#143571]
### Use case

I am building a video analysing application, where videos should be played on both directions (forward and backwards). In Apple ecosystem where AVPlayer is used, reverse playback is supported out of the box if AVPlayerr's canPlayReverse parameter returns true for specific video. However, video_player does not allow currently negative values, hence not allowing to play videos in reverse even if underlying player supports it.

### Proposal

Is there any plan to add configuration option to video_player to support reverse video playback?

With flutter video_player package I have discovered that if I modify plugin code and allow negative playback speed, then for some videos (e.g. HEIC MOV on MacOS) reverse playing is working well. I guess this is due to fact that underlying Apple's AVPlayer generally supports reverse playback if its canPlayReverse property returns true for a specific video file.

Instead of forking the package and modifying its code, it would be more sustainable to have some configuration option to allow the reverse playback (negative playback speed) support. It would be sufficient functionality for applications, where videos are in specific format and are known to support reverse playback.

**Comment by dam-ease** [comment]
Thanks for proposing this @tannker 
I see there is a similar issue currently open. Can you please checkout https://github.com/flutter/flutter/issues/27591 to confirm it describes what you are proposing as well.
