### ISSUE TITLE
[Impeller] PowerVR devices rendering incorrectly if vertex/fragment stage varyings have mismatched relaxed precision.

### ISSUE THREAD

**Issue by woutervanwijk** [flutter/flutter#143573]
### Steps to reproduce

Build and run app with impeller enabled on a Galaxy Tab 7 Lite (Android 14)
Immediately visible

### Expected results

Properly working app

### Actual results

Ugly font, unreadable
Green backgrounds
Missing icons
See screenshots

### Code sample

<details open><summary>Code sample</summary>
Just use the default demo app. And add this to the AndroidManifest.xml in release:

```xml
<meta-data
    android:name="io.flutter.embedding.android.EnableImpeller"
    android:value="true" />
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

![Screenshot_20240216_113751](https://github.com/flutter/flutter/assets/480348/394a028a-7bdd-4491-8ecd-458648823bb4)

![Screenshot_20240216_104341](https://github.com/flutter/flutter/assets/480348/f229e8ed-f335-4828-909e-99dfb097de9a)

</details>

### Logs

<details open><summary>Logs</summary>

```console
wouter$ flutter run --release -d "SM T220"

Launching lib/main.dart on SM T220 in release mode...
Running Gradle task 'assembleRelease'...                           94.3s
✓  Built build/app/outputs/flutter-apk/app-release.apk (6.9MB).
Installing build/app/outputs/flutter-apk/app-release.apk...        16.9s

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
E/flutter (23388): [ERROR:flutter/shell/platform/android/android_context_vulkan_impeller.cc(52)] Using the Impeller rendering backend (Vulkan).

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.3.1 23D60 darwin-arm64, locale en-NL)
    • Flutter version 3.19.0 on channel stable at /Users/wouter/.flutter_sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wouter/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/wouter/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • Touwer (mobile) • 00008110-000864E211FB801E • ios            • iOS 17.3.1 21D61
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @woutervanwijk 
I see that you are running in release mode. Does the same behavior persists in debug mode as well on same device ?

**Comment by woutervanwijk** [comment]
It's the same in Debug mode indeed

`D/ViewRootImpl@b3e2d1c[MainActivity]( 2772): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
D/OpenGLRenderer( 2772): CFMS:: SetUp Pid : 2772    Tid : 2821
D/ViewRootImpl@b3e2d1c[MainActivity]( 2772): reportDrawFinished
I/ViewRootImpl@b3e2d1c[MainActivity]( 2772): registerCallbackForPendingTransactions
I/ViewRootImpl@b3e2d1c[MainActivity]( 2772): handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
D/ViewRootImpl@b3e2d1c[MainActivity]( 2772): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007ab7962800}
D/InputMethodManagerUtils( 2772): startInputInner - Id : 0
I/InputMethodManager( 2772): startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
D/InputMethodManagerUtils( 2772): startInputInner - Id : 0
I/InsetsController( 2772): onStateChanged: host=com.example.impelbug7/com.example.impelbug7.MainActivity, from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:7134, state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1340, 800), mDisplayCutout=DisplayCutout{insets=Rect(0, 0 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=0 displayHeight=0 physicalDisplayWidth=0 physicalDisplayHeight=0 density={0.0} cutoutSpec={} rotation={0} scale={0.0} physicalPixelDisplaySizeRatio={0.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=17, center=Point(17, 17)}, RoundedCorner{position=TopRight, radius=17, center=Point(1323, 17)}, RoundedCorner{position=BottomRight, radius=17, center=Point(1323, 783)}, RoundedCorner{position=BottomLeft, radius=17, center=Point(17, 783)}]}  mRoundedCornerFrame=Rect(0, 0 - 1340, 800), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(1282, 0 - 1340, 32) rotation=3}, mDisplayShape=DisplayShape{ spec=-2118105561 displayWidth=800 displayHeight=1340 physicalPixelDisplaySizeRatio=1.0 rotation=3 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {a6b30001 mType=navigationBars mFrame=[0,736][1340,800] mVisible=true mFlags=[]}, InsetsSource: {a6b30004 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {a6b30005 mType=mandatorySystemGestures mFrame=[0,736][1340,800] mVisible=true mFlags=[]}, InsetsSource: {a6b30006 mType=tappableElement mFrame=[0,736][1340,800] mVisible=true mFlags=[]}, InsetsSource: {a6b30024 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {3a9a0000 mType=statusBars mFrame=[0,0][1340,32] mVisible=true mFlags=[]}, InsetsSource: {3a9a0005 mType=mandatorySystemGestures mFrame=[0,0][1340,32] mVisible=true mFlags=[]}, InsetsSource: {3a9a0006 mType=tappableElement mFrame=[0,0][1340,32] mVisible=true mFlags=[]} }
I/InsetsSourceConsumer( 2772): applyRequestedVisibilityToControl: visible=false, type=ime, host=com.example.impelbug7/com.example.impelbug7.MainActivity`

**Comment by jonahwilliams** [comment]
Thank you for the bug report! I haven't seen anything like this before, but I'll try to get access to one of those tablets to see if I can reproduce it. Possibly an issue with supported color formats?

**Comment by jonahwilliams** [comment]
@woutervanwijk Can you provide us with the exact device model number? This should be in the settings app.

**Comment by jonahwilliams** [comment]
You could also download the Vulkan capabilities view: https://vulkan.gpuinfo.org/download.php and provide the info it grabs from the device GPU and driver to help us narrow it down.

**Comment by jonahwilliams** [comment]
FYI @chinmaygarde

**Comment by woutervanwijk** [comment]
> @woutervanwijk Can you provide us with the exact device model number? This should be in the settings app.

It's a Samsung SM-T220

The GPU is PowerVR Rogue GE8320

The Caps app says the device is already in the database

What do you need from the app?

**Comment by jonahwilliams** [comment]
Perfect, that is it then. Thank you!

**Comment by chinmaygarde** [comment]
This issue is pretty reliably reproducible with any app on PowerVR GE8320 device. I have one I got at Best Buy for < $50. Mine is a Samsung A03s. Its on go/impeller-android-devices with a report at https://vulkan.gpuinfo.org/displayreport.php?id=17029. Will take a look at whats going on.

**Comment by Shunt22** [comment]
Samsung SM-T220 here too.
Same issue. 

Any updates on this issue? Would love to test impeller.

**Comment by jonahwilliams** [comment]
With some help from @chinmaygarde , we've found the issue that causes this and are working on a fix.
