### ISSUE TITLE
[ios] benchmarks/platform_views_layout project is too heavy in non-platform view

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#143534]
### Use case

The non-platform view part is too expensive (https://github.com/flutter/flutter/blob/master/dev/benchmarks/platform_views_layout/lib/main_non_intersecting.dart#L93-L94), making it not ideal test for platform view performance. Even if we completely remove platform view from this test, this project is almost as poor performing due to non-platform view widgets. 

### Proposal

A better project that measures platform view performance should use lighter-weight non-platform views.

**Comment by jmagman** [comment]
Reopening, the benchmark was reverted, it broke Android tests:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20platform_views_scroll_perf_impeller__timeline_summary/1661/overview
