### ISSUE TITLE
Tutorial: Intro on how to make an HTTP connection

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1435]
_From @sethladd on November 4, 2015 18:26_

Connecting to HTTP (GET, POST) from a Flutter app will be a very common activity. Let's include a mention and example of this in the Tutorial.

_Copied from original issue: flutter/website#43_

**Comment by Hixie** [comment]
This is already well documented for Dart in general (just google "dart http"). I think we can wait for a stackoverflow question before worrying about it.
