### ISSUE TITLE
Warning after upgrade to latest alpha with dart 2 preview

### ISSUE THREAD

**Issue by killermonk** [flutter/flutter#14354]
## Steps to Reproduce

Upgrade to alpha v0.0.21

`flutter run --preview-dart-2` an app

## Logs

Run your application with `flutter run` and attach all the log output.

(Flutter repo is at: /Users/brianarmstrong/workspace/flutter)
```
→ flutter run --preview-dart-2
Launching lib/main.dart on iPhone 8 in debug mode...
compiler message: file:///Users/brianarmstrong/workspace/flutter/packages/flutter/lib/src/rendering/binding.dart:295:11: Warning: Superclass has no method named 'hitTest'.
compiler message:     super.hitTest(result, position); // ignore: abstract_super_member_reference
compiler message:           ^
Running Xcode build...                               14.7s
Syncing files to device iPhone 8...
compiler message: file:///Users/brianarmstrong/workspace/flutter/packages/flutter/lib/src/rendering/binding.dart:295:11: Warning: Superclass has no method named 'hitTest'.
compiler message:     super.hitTest(result, position); // ignore: abstract_super_member_reference
compiler message:           ^
```

Run `flutter analyze` and attach any output of that command also.
N/A

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale en-US, channel alpha)
    • Flutter version 0.0.21 at /Users/brianarmstrong/workspace/flutter
    • Framework revision 2e449f06f0 (8 hours ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/brianarmstrong/Library/Android/sdk
    • Android NDK at /Users/brianarmstrong/Library/Android/sdk/ndk-bundle
    • Platform android-26, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • iPhone 8 • B2A6D06C-9B34-45BE-ACDB-BC1E1666C76D • ios • iOS 11.1 (simulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
cc @aam

**Comment by cbracken** [comment]
Haven't looked into it, but can confirm that I can repro this locally.

**Comment by mraleph** [comment]
This is tracked upstream in dart-lang/sdk#31994. 

Short summary is that Flutter uses language features that never existed in Dart language specification (namely super-mixins). We are going to add the flag into front-end to suppress this particular warning one way or another.

**Comment by Hixie** [comment]
Fixed upstream.
