### ISSUE TITLE
Web tests in flutter/packages repo only test against HTML renderer

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#143543]
Right now, all the web unit tests in flutter/packages run against the HTML renderer. If we are going to run them against only one renderer, CanvasKit should probably be the one we test. Or we could test both. But right now, HTML is our least recommended renderer option, and so our tests should probably not default to that.

**Comment by ditman** [comment]
We have very few web tests that actually rely on rendering anything (and AFAIK none that have to do with golden files).

I'm not 100% sure but I think we could flip them all to `canvaskit` and only some `example/index.html` would need an update to ensure they're embedding flutter in a way that matches the expected renderer.

(But I haven't checked, so I'm not sure...) I'll get these updated next week.

**Comment by eyebrowsoffire** [comment]
Some of the tests did break on (unintentionally) switching to CanvasKit, so there is some sort of difference going on

**Comment by eyebrowsoffire** [comment]
Context is in this Discord thread: https://discord.com/channels/608014603317936148/608020293944082452/1207377829373812807

Basically with the dual compile changes, I fixed the way the web renderer was being plumbed through the test infrastructure.

Here is an example failure when the roller wasn't working:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux_web%20web_dart_unit_test_shard_2%20master/5823/overview

Test looks like:
```
00:02 +2: PaletteGenerator.fromImage works                                                                                                                                                             
00:02 +2 -1: PaletteGenerator.fromImage works [E]                                                                                                                                                      
  Expected: <1>
    Actual: <2>
  
  dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 328:3       throw_
  packages/matcher/src/expect/prints_matcher.dart.js 464:22                         fail
  packages/matcher/src/expect/prints_matcher.dart.js 461:12                         _expect
  packages/matcher/src/expect/prints_matcher.dart.js 396:12                         expect$
  packages/flutter_test/src/test_text_input_key_handler.dart.js 10436:12            expect$
  palette_generator_test.dart.js 511:23                                             <fn>
  dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
  packages/stack_trace/src/stack_zone_specification.dart.js 242:98                  <fn>
  packages/stack_trace/src/stack_zone_specification.dart.js 294:16                  [_run]
  packages/stack_trace/src/stack_zone_specification.dart.js 242:80                  <fn>
  dart-sdk/lib/async/zone.dart 1407:47                                              _rootRunUnary
  dart-sdk/lib/async/zone.dart 1308:19                                              runUnary
...
```

**Comment by ditman** [comment]
Ah thanks, I remember those!

The PaletteGenerator is a package I have never touched, so it makes sense, everything I said about tests "not being tied to the renderer" or "not painting anything" probably don't apply to that one :P

**Comment by ditman** [comment]
Because of this issue[^1], we've decided to migrate the tests to default to `canvaskit` rather than `html`, rather than attempting to have both suites running in parallel.

[^1]: [Intent to deprecate and remove the HTML renderer in Flutter Web](https://github.com/flutter/flutter/issues/145954)

**Comment by stuartmorgan** [comment]
Can we prioritize this ASAP, given https://github.com/flutter/flutter/issues/149826 ? Running flutter/packages tests against something that isn't what the vast majority of users will be using isn't ideal. And longer term, I don't want to be in a situation where the flutter->packages roller is blocked indefinitely because the default changes to `canvaskit` but the flutter/packages web tests haven't yet been made to work with `canvaskit`.

**Comment by mdebbar** [comment]
I'll take this one if you don't mind @ditman
