### ISSUE TITLE
Allow `debugForceSurfaceProducerGlTextures` in `scenario_app`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143539]
Would close/supersede https://github.com/flutter/flutter/issues/143471.

## Background

Our (current) Android embedding APIs are inverted, we ask our users to create a _specific_ backend texture (i.e. `createSurfaceTexture` or `createImageTexture`). This has problems for backwards and forwards compatibility, and means the Flutter engine lacks the ability to migrate our implementations to better techniques without a migration.

We've solved this by introducing a new opaque API, `createSurfaceProducer`, that picks the appropriate backend for the user. You can read more about that API, and the migration to come at https://github.com/flutter/flutter/issues/139702.

The tl;dr is that `createSurfaceProducer` is now a multi-branched API that either:

1. Creates a `SurfaceTexture` (API version <= 28)
2. Creates an `ImageReader` (API version >= 29)

In other words, to be able to answer the question "our Android embedder can render stuff", we need (currently) to be able to run a real device or emulator at Android API version 28, which, for reasons I don't quite yet understand, are very flaky (https://github.com/flutter/flutter/issues/143471). I'll also add that due to the complexity of running Android emulator v28 tests locally on an ARM64 Mac, that any progress to significantly improve this situation is likely to be _very_ slow (days -> weeks, not hours -> days).

## Proposal

Make [`FlutterRenderer.debugForceSurfaceProducerGlTextures`](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java#L60) `public` and use it in `scenario_app`.

This would remove the need to configure and debug an Android v28 emulator at the cost of worrying about the use of public `@VisibleForTesting` APIs (of which we appear to have many already: 

![Screenshot 2024-02-15 at 12 01 40 PM](https://github.com/flutter/flutter/assets/168174/1806c75e-c4bb-4343-890e-24be8f76fd93)

**Comment by jonahwilliams** [comment]
LGTM

We should document this API as "do not use or you will be fired" and/or explicitly ignore the setting in release configurations so that it is difficult for anyone besides ourselves to rely on it.

**Comment by gaaclarke** [comment]
LGTM.  Another thing you could consider is loading this from the AndroidManifest instead of expanding the public API.  We do that already to force devices to use opengles for testing purposes.

**Comment by matanlurey** [comment]
> LGTM. Another thing you could consider is loading this from the AndroidManifest instead of expanding the public API. We do that already to force devices to use opengles for testing purposes.

The problem is I want this conditionally.

I've been trying to avoid ephemeral disk I/O as part of testing (just more things to get wrong).

**Comment by johnmccutchan** [comment]
LGTM

**Comment by matanlurey** [comment]
@dnfield I am going to assume you're on the same page - if you're not ping me and let's chat.

Closing as LGTM.
