### ISSUE TITLE
[camera_android_camerax] The readme has a typo

### ISSUE THREAD

**Issue by Bassiuz** [flutter/flutter#143572]
### What package does this bug report belong to?

camera

### What target platforms are you seeing this bug on?

Android, iOS, Web, macOS, Linux, Windows

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. Read the `README.md` of the camera_android_camerax package.
2. Notice it mentions `pubsecp.yaml` instead of `pubspec.yaml`

### Expected results

The readme should mention the correct file name, `pubspec.yaml`

### Actual results

The readme mentions `pubsepc.yaml`

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Thanks for the report!
I can see this as well under Usage section of the README https://github.com/flutter/packages/blob/main/packages/camera/camera_android_camerax/README.md#usage

**Comment by TahaTesser** [comment]
Fixed by https://github.com/flutter/packages/pull/6143
