### ISSUE TITLE
[codelabs]

### ISSUE THREAD

**Issue by ChTiSh** [flutter/flutter#143592]
### Steps to reproduce

1. Launch Visual Studio Code.
2. Open the command palette (F1 or Ctrl+Shift+P or Shift+Cmd+P) then type "flutter new". When it appears, select the Flutter: New Project command.
3. Select Empty Application. 
4. Name your project
5. In the left pane of VS Code, click on Explorer.

### Expected results

![expectedexplorerofemptyapplication](https://github.com/flutter/flutter/assets/94409079/4d589fdd-e7fa-4f8e-a223-fcf840947ed4)

### Actual results

<img width="683" alt="Screen Shot 2024-02-16 at 09 53 47" src="https://github.com/flutter/flutter/assets/94409079/0a1c901b-16dc-4c44-bbcc-8e85e78c14ac">

### Code sample

This issue does not involve code. The file structures of the empty application has changed. The instructions and screenshots provided in the codelabs has not.

https://codelabs.developers.google.com/codelabs/flutter-flame-brick-breaker#2

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ChTiSh, everything works as expected when I create a new project in vscode. See the recording below. Can you make sure you're using the latest version of vscode and the flutter extension in vscode? You can also try reloading your window after creating the project to see if this still persists. 

If it does, you may file an issue on the [dart-code repo](https://github.com/Dart-Code/Dart-Code/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) as this is not an issue with the code lab. 

Closing from here. Thank you

https://github.com/flutter/flutter/assets/88313112/28758f56-fec9-4688-9463-12c4cbc3a339
