### ISSUE TITLE
[BUG] Dart-define-from-file is broken from 3.19.0+  

### ISSUE THREAD

**Issue by maxakak1998** [flutter/flutter#143633]
### Steps to reproduce

Running  `flutter run --dart-define-from-file=config/dev.json`

dev.json:
```json
{
 "app_name":"Test"
}
```

It still works for 3.16.5

### Expected results

I should see the variables in Generated.xcconfig in Xcode

```
app_name=test
```

### Actual results

There is no variables in Generated.xcconfig in Xcode.
I can see there is the encoded-base64 value  but no actual value

```
DART_DEFINES=YXBwX25hbWU9dGVzdA==
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
![image](https://github.com/flutter/flutter/assets/50696626/0a8f6c90-7262-4d97-a78f-2004826b932e)

</details>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.20.0-9.0.pre, on macOS 14.3 23D56 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
```

</details>

**Comment by kevinrobert3** [comment]
Encountered the same issue with v3.19.0. Downgrading for now to a lower version

**Comment by maxakak1998** [comment]
Im using Shorebird and the latest release is using 3.19.0@beta flutter to fix the critical bug with Dio package.
https://github.com/shorebirdtech/shorebird/releases/tag/v0.26.0

Still trying to work around from this bug.

I have tried to write the custom bash script for pre-build phase. It will decode base64 and append variable to the Generated.xcconfig file but still get the error.

If there is some way we can add these values to User-Defined setting of Xcode i think it will work.

**Comment by eseidel** [comment]
Based on the commit history, my guess is @andrewkolos would know if this is intentional or not 🤷

**Comment by danagbemava-nc** [comment]
Hi all, this was an intentional change. See  https://github.com/flutter/flutter/issues/138793 and the underlying comments https://github.com/flutter/flutter/issues/138793#issuecomment-1821923832 and https://github.com/flutter/flutter/issues/138793#issuecomment-1832732494

There is an issue to provide a similar feature that will serve that purpose in https://github.com/flutter/flutter/issues/139289. 

For now, I'll be closing this in favor of the proposal to add a similar feature, linked above. Please upvote the proposal. 

Thank you

**Comment by eseidel** [comment]
Thanks for the reply.  I will note, that 87 👍 is an impressive number of reactions, looks like this hit a surprising number of users. https://github.com/flutter/flutter/issues/138793

**Comment by sbatezat** [comment]
Please see my comment here https://github.com/flutter/flutter/issues/139289#issuecomment-1954103555 for a quick fix.
