### ISSUE TITLE
flutter 中没有类似 enablesReturnKeyAutomatically实现吗? text为空   retrun禁止

### ISSUE THREAD

**Issue by simanlx** [flutter/flutter#143640]
### Steps to reproduce

flutter 中没有类似 enablesReturnKeyAutomatically实现吗? text为空 retrun 禁止

### Actual results

flutter 中没有类似 enablesReturnKeyAutomatically实现吗? text为空 retrun 禁止

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
> flutter 中没有类似 enablesReturnKeyAutomatically实现吗? text为空 retrun 禁止

"Is there no implementation similar to enablesReturnKeyAutomatically in flutter? text is empty retrun is prohibited" - _Using Google translate_

This sounds like similar to https://github.com/flutter/flutter/issues/112198. You may follow https://github.com/flutter/flutter/issues/93915 as well. Closing as a duplicate.
