### ISSUE TITLE
Tutorial: Intro to how to read/write data on the device

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1436]
_From @sethladd on November 4, 2015 18:27_

Storing data, reading data, etc will be a very common activity in Flutter apps. Let's mention this with perhaps a simple example in the Tutorial.

_Copied from original issue: flutter/website#44_

**Comment by bobacadodl** [comment]
Is this even currently possible with flutter? I still can't find any explanations on how to do it.

**Comment by sethladd** [comment]
Should be able to use the File/Directory classes from dart:io (http://docs.flutter.io/flutter/dart-io/dart-io-library.html) and http://docs.flutter.io/flutter/services/PathProvider-class.html for device locations.

Still, we need more docs here :)

**Comment by Hixie** [comment]
@sethladd Is this bug still valuable for you?

**Comment by sethladd** [comment]
To the extent that we're keeping issues open which reflect work we believe we should do, then yes, it's valuable :)

However, we can move out of Milestone 3.

**Comment by Sfshaza** [comment]
This is now a section in the Flutter cookbook. Closing.

https://flutter.io/cookbook/persistence/reading-writing-files/
