### ISSUE TITLE
[flutter_markdown] Supports returning markdown text when a section of text is selected

### ISSUE THREAD

**Issue by flyer1b** [flutter/flutter#143666]
### Use case

I want to implement selection highlighting in flutter_markdown, but I can only get the selected plain text, so I can't locate the position of this text in the markdown text, and I can't highlight the text, so I request to add a return to the selected text corresponding callback for markdown text.

### Proposal

Added markdown text selection callback.

**Comment by huycozy** [comment]
I think this is more detailed at https://github.com/flutter/flutter/issues/128170. So I will close this issue in favor of that one. Please follow up on it for updates. Thanks!
