### ISSUE TITLE
[Fonts] [Icons] Time to update the material font (missing heart_plus, etc)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#143656]
I tried to update the Material Icons font for Flutter but the instructions on https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons don't let non-Googlers do it.

I need the heart_plus icon (U+F884) which I see on the fonts.google.com site but isn't available in the Icons list.

**Comment by parlough** [comment]
I think `heart_plus` is only part of Material Symbols, rather than Material Icons. https://github.com/flutter/flutter/issues/102560 tracks support for the new icon set.

**Comment by Hixie** [comment]
Ah, I see.
