### ISSUE TITLE
image_picker: pick images on a specific day / date 

### ISSUE THREAD

**Issue by YesThatGy** [flutter/flutter#143653]
### Use case

I'm writing a flutter app for some schools for field trips; keeps track of where kids are by their phone, and a request is to allow students to share pictures taken. 

image_picker is the obvious choice, but if possible, I'd like the images to be uploaded to only come from the day of the event; if the student took nude selfies or something before/after the event, I don't want them accidently uploading that! 

Is there a way to specify to image_picker that, when being sent to the photo gallery or whatever, to only show pictures on the day(s) of the event? 

I see nothing of the kind in the dox. 

Alternatives I've explored: 
1) Only upload pictures taken from within the app. (doesn't allow for retroactive uploads) 
2) images_picker doesn't have the functionality I want, either. 
3) Look at the exif data or file metadata to just reject pictures picked on other days. (Not very user friendly, especially for kids)

### Proposal

Something like: 

// define the start/ending times of the event
startTime = dateTime(eventDate);
endTime = dateTime(eventDate + eventDuration);
// .... 
FloatingActionButton(
              onPressed: () {
                isVideo = false;
                _onImageButtonPressed(
                  ImageSource.gallery,
                  context: context,
                  isMultiImage: true,
                  isMedia: true,
                  startTime: startTime,
                  endTime: endTime,
                );
              },
              heroTag: 'multipleMedia',
              tooltip: 'Pick Multiple Media from gallery',
              child: const Icon(Icons.photo_library),
            ),

**Comment by moffatman** [comment]
I don't believe either Android or iOS allows setting such a restriction on the image picker. The only way would be to ask for and receive full gallery access, and check the file metadata yourself, implementing your own picker. Not such a great solution....

**Comment by stuartmorgan** [comment]
As noted above, the underlying OS-provided controls that `image_picker` is providing access to don't have this functionality. Features that would require implementing a custom picker from scratch are out of scope for this plugin, so closing.
