### ISSUE TITLE
Run flutter pub get 'package:~~' to cause flutter to crash

### ISSUE THREAD

**Issue by robertgao2023** [flutter/flutter#143684]
### Steps to reproduce

1. clone code https://github.com/boskokg/flutter_blue_plus.git
2. use VS CODE on windows 11, targeting an android emulator
3. flutter doctor -v report no issue
4. try to run the get pub from terminal: $ flutter pub get 'package:flutter_test/flutter_test.dart'
5. it crash and create a crash report

### Expected results

it supposed to add the package to the project.

### Actual results

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter pub get package:flutter_test/flutter_test.dart

## exception

FileSystemException: FileSystemException: Exists failed, path = 'C:\Users\rober\MyDevSandBox\flutter_blue_plus\package:flutter_test/flutter_test.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#5      findProjectRoot (package:flutter_tools/src/base/os.dart:598:27)
#6      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:266:18)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1687:12)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version
    10.0.22631.3155], locale en-US)
    [32m•[39m Flutter version 3.16.9 on channel stable at
      C:\Users\rober\MyDevSandBox\my-flutter-app\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 41456452f2 (4 weeks ago), 2024-01-25 10:06:23 -0800
    [32m•[39m Engine revision f40e976bed
    [32m•[39m Dart version 3.2.6
    [32m•[39m DevTools version 2.28.5

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\rober\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.0)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.9.34607.119
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[32m[✓][39m VS Code (version 1.86.2)
    [32m•[39m VS Code at C:\Users\rober\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.82.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.22631.3155]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.128

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Could you elaborate on why you put `package:flutter_test/flutter_test.dart` in the command? Or is it a mistyped issue?

**Comment by navaronbracke** [comment]
This seems to be a user error, as `flutter_test` is vendored by the Flutter SDK itself, and not Pub, hence why pubspecs list

```
flutter_test:
   sdk: flutter
```

and why pub is not resolving it during a `flutter pub add` command.

**Comment by robertgao2023** [comment]
First of all, appreciate any comments and advices! I am new to the flutter world, it's facinating tech, however, it seems take me too much time to setup, there are so many prep to be done which need some detailed guide lines. I am sure there are lots of things there to learn. Please help me to get started. 
@huycozy the reason I was trying to get the package via command line is that the pubspec.yaml seems not to find the specific package and it crashed is not by design even by user error, I believe. To follow up with the comment by @navaronbracke, you are prabably correct, but why it is not resolved by  
~~~
flutter_test:
   sdk: flutter
~~~
by my pubspec.yaml file. Any pointers to follow, such as what could be the issue normally? Some environment variable settings? Or anything else?
Thanks in advance...

**Comment by huycozy** [comment]
>pubspec.yaml seems not to find the specific package and it crashed is not by design even by user error, I believe.

@robertgao2023 Please check [Using packages](https://docs.flutter.dev/packages-and-plugins/using-packages#using-packages) docs which clearly explains how to use a package in your project.

`flutter_test` should be there by default when you create a new Flutter project:

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
```

Did you modify it in `pubspec.yaml`? Could you share your `pubspec.yaml` file content?

**Comment by robertgao2023** [comment]
I wonder where the flutter_test package is. It seems to be on top of test, However, I searched and not finding flutter_test package. Where to find the syntax for modify pubspec.yaml? I was imitating the stuff already there. ;)
Thanks...

**Comment by robertgao2023** [comment]
For the past 24 hours, I have tried to reinstall everything for flutter and its dependencies, plus android and ios emulators. On windows and also on Mac as well. It looks like the code analysis generates these errors always on my windows dev environment. On ios, I seem have got a little better luck - these PROBLEMS disappeared. I noticed that one extension: Extension Pack for Java v0.25.15 will for sure cause some of the flutter complaints on both platforms.

**Comment by huycozy** [comment]
>Here is the pubspec.yaml
>I wonder where the flutter_test package is. 

I see it's `flutter_blue_plus`'s pubspec.yaml file. I guess the author doesn't need `flutter_test` in his plugin/package, so he removed it.

If you try [Create the package](https://docs.flutter.dev/packages-and-plugins/developing-packages#step-1-create-the-package-1) from scratch, `flutter_test` should be there in `pubspec.yaml` file. 

This is more like an implementation issue rather than a Flutter framework issue, I'm going to close this from here. If you still believe this is a Flutter framework bug, please write in the comments and I will reopen it.
