### ISSUE TITLE
Would like to view the "Run Tracker" demo in the Flutter Gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#14369]
We have a beautiful demo here: https://github.com/flutter/posse_gallery/blob/master/lib/screens/demos/customized_design.dart

But it's hard for users to see it, and thus we're missing an opportunity to show it off to users.

We'd like to add this demo to Flutter Gallery so that we can ship it to users and inspire them.

**Comment by sethladd** [comment]
cc @Hixie

**Comment by guidezpl** [comment]
Closing as the demo link is dead. Please file any new issue at https://github.com/flutter/gallery.
