### ISSUE TITLE
[feature request] add optional use pkl-lang to generate config files (.yaml .gradle.kts, .plist, etc)

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#143662]
## Use case

a flutter app has several `configuration` files in different "languages"
- dart/flutter -> yaml
- android -> gradle / kotlin dsl
- ios -> plist / xcscheme
etc..

### developer experience

it's highly likely that at some point developers 
will interact with those, possibly in a language is not very familiar with

### validation and error messages

often misconfiguration of are evident only at build time
and the deriving error message could be hard to read
for the reason highlighted above

### DRY / error prone

some information are repeated across multiple configuration files, 
this is an error prone practice that could cause mismatches 
and tedious manual editing (eg: flavors, app naming / renaming, etc)

## Proposal

Using [pkl](https://pkl-lang.org/index.html) to generate config files in the respective languages and platforms
would alleviate those problems.

The obvious draw back for developers is to learn `pkl`, 
but if this feature would be *only optional* shouldn't be problematic

#

cc @christopherfujino

**Comment by darshankawar** [comment]
@iapicca 
Can you take a look at [this](https://github.com/flutter/flutter/issues/119191) open proposal and check if it resembles your case or not ?

**Comment by iapicca** [comment]
> > Can you take a look at https://github.com/flutter/flutter/issues/119191 open proposal and check if it resembles your case or not ?
>
> [...] When developing a cross-platform app using Flutter, updating the app's version number, permissions, icons, splash screens, and package/bundle names for both iOS and Android can be time-consuming and labor-intensive, as they need to be managed separately for each platform. [...]

I think this issue is tangentially related, 
using [pkl](https://pkl-lang.org/index.html) can be a way to achieve **_some_** of the goals of that issue 
(eg:  app's version number, package/bundle names and permissions) 
but all, for won't help example icons, splash screen, etc

Moreover the issue you mentioned seems to 
"[...] propose the development of a unified config file to simplify the management of version information [...]", 
while I feel like I'm proposing a very specific solution (adopt `pkl-lang`) to a very specific problem

**Comment by iapicca** [comment]
> How would introducing yet another language be preferable to using yaml as the source of truth for shared elements (as is already the case with version on most platforms)?

@stuartmorgan 
I'm not proposing switching from `yaml` to `pkl`, 
but to provide the option to use either 
and possibly integrate the former with the latter.

For example, even using yaml, the `read()` feature of pkl could make `pubspec` 
even more a single "source of truth" unlocking the possibility of easily generate native config
(with extra steps under the hood while using yaml)

- declare the values in `pubspec.yaml`
  ```yaml
  name: my_awesome_app
  ### ...
  android:
    applicationId: 'com.example.my_awesome_app'
  ```
- (under the hood) use `read()` and validate the values in `{whatever}.pkl`
  (I'm not sure about the syntax for reading from file but it can/supposed-to-be-able-to do it)
  
  ```pkl
   android = (androidConfig) {
     applicationId = read(pubspec.yaml:android:applicationId)
   }
   ios = (iosConfig) {
     bundleName = read(pubspec.yaml:name)
   }
  }
  ```
- (under the hood) generate native stuff
  - build.gradle.kts 
  ```kts
     defaultConfig {
        applicationId "com.example.my_awesome_app" // from pkl androidConfig.applicationId
  ```
  - info.plist
  ```
    <key>CFBundleName</key>
    <string>my_awesome_app</string> // from pkl iosConfig.bundleName
  ```

I think this [video](https://youtu.be/ckbqhf8P_cg?si=jDJKgOtjqS3jGwmm) could provide a TLDR of the features offered by pkl

**Comment by stuartmorgan** [comment]
> > How would introducing yet another language be preferable to using yaml as the source of truth for shared elements (as is already the case with version on most platforms)?
> 
> @stuartmorgan I'm not proposing switching from `yaml` to `pkl`, but to provide the option to use either

That doesn't seem to answer my question. For it to be worth the implementation, API, documentation, etc. complexity of having two ways of specifying everything, there would have to be a compelling advantage to doing so. What is that advantage?

> For example, even using yaml, the `read()` feature of pkl could make `pubspec`
> even more a single "source of truth" unlocking the possibility of easily generate native config

What you are describing here and in the rest of the comment sounds like one possible implementation of https://github.com/flutter/flutter/issues/119191 rather than a stand-alone proposal. Is that the suggestion, rather than something user-facing as suggested in the original comment? If so, this should probably just be discussed in #119191 as a possible implementation.

**Comment by iapicca** [comment]
> > > How would introducing yet another language be preferable to using yaml as the source of truth for shared elements (as is already the case with version on most platforms)?
> > 
> > 
> > @stuartmorgan I'm not proposing switching from `yaml` to `pkl`, but to provide the option to use either
> 
> That doesn't seem to answer my question. For it to be worth the implementation, API, documentation, etc. complexity of having two ways of specifying everything, there would have to be a compelling advantage to doing so. What is that advantage?

- validation
- read values from file
- ide integration

> What you are describing here and in the rest of the comment sounds like one possible implementation of #119191 rather than a stand-alone proposal. Is that the suggestion, rather than something user-facing as suggested in the original comment? If so, this should probably just be discussed in #119191 as a possible implementation.

fair enough, I've already [commented](https://github.com/flutter/flutter/issues/119191#issuecomment-1952039881) referencing pkl as a solution for some of the goals of that issue

closing the issue for now
