### ISSUE TITLE
TypeError: Class constructor IndexedDBLocalPersistence cannot be invoked without 'new'

### ISSUE THREAD

**Issue by kkgkaundal** [flutter/flutter#143697]
### Steps to reproduce

Add firebase packages to flutter 

### Expected results

Running application smooth 

### Actual results

TypeError: Class constructor IndexedDBLocalPersistence cannot be invoked without 'new'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 462:37   _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39   dcall
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:48595                 _getInstance
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:144495                _initializeAuthInstance
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:144643                instanceFactory
https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js 977:39                   getOrInitializeService
https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js 921:31                   initialize
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:68877                 initializeAuth
packages/firebase_auth_web/src/interop/auth.dart 24:40                             getAuthInstance
packages/firebase_auth_web/firebase_auth_web.dart 91:43                            <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                 runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                 _async
packages/firebase_auth_web/firebase_auth_web.dart 90:33                            <fn>
packages/firebase_core_web/src/firebase_core_web.dart 316:41                       <fn>
dart-sdk/lib/internal/iterable.dart 403:20                                         moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1140:20  next
dart-sdk/lib/async/future.dart 516:16                                              wait
packages/firebase_core_web/src/firebase_core_web.dart 308:18                       initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                 <fn>
dart-sdk/lib/async/zone.dart 1661:54                                               runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                         handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                         handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                         _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                          [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                   _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                    _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                 <fn>
The webOnlyAssetManager getter is deprecated and will be removed in a future release. Please use `assetManager` from `dart:ui_web` instead.
The webOnlyAssetManager getter is deprecated and will be removed in a future release. Please use `assetManager` from `dart:ui_web` instead.
TypeError: Class constructor IndexedDBLocalPersistence cannot be invoked without 'new'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 462:37   _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39   dcall
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:48595                 _getInstance
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:144495                _initializeAuthInstance
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:144643                instanceFactory
https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js 977:39                   getOrInitializeService
https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js 921:31                   initialize
https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js 1:68877                 initializeAuth
packages/firebase_auth_web/src/interop/auth.dart 24:40                             getAuthInstance
packages/firebase_auth_web/firebase_auth_web.dart 91:43                            <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                 runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                 _async
packages/firebase_auth_web/firebase_auth_web.dart 90:33                            <fn>
packages/firebase_core_web/src/firebase_core_web.dart 316:41                       <fn>
dart-sdk/lib/internal/iterable.dart 403:20                                         moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1140:20  next
dart-sdk/lib/async/future.dart 516:16                                              wait
packages/firebase_core_web/src/firebase_core_web.dart 308:18                       initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                 <fn>
dart-sdk/lib/async/zone.dart 1661:54                                               runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                         handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                         handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                         _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                          [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                   _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                    _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                 <fn>

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@kkgkaundal 
The error is related to firebase which seems to have been fixed and new version is released as mentioned [here](https://github.com/firebase/flutterfire/issues/12291#issuecomment-1952179549). Check the same. If the error still persists, write in the linked issue.

Closing from here, as this isn't a flutter sdk issue.

**Comment by kkgkaundal** [comment]
@darshankawar
Thanks
