### ISSUE TITLE
Error on -flutter doctor-

### ISSUE THREAD

**Issue by dovahkiin98** [flutter/flutter#14363]
When I try to run 'flutter doctor' it fails and gives me this output
>```
> D:\flutter\bin>flutter doctor -v
> [  +28 ms] [D:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
> [ +214 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [   +1 ms] origin/alpha
> [        ] [D:\flutter\] git rev-parse --abbrev-ref HEAD
> [ +193 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] alpha
> [        ] [D:\flutter\] git ls-remote --get-url origin
> [ +153 ms] Exit code 0 from: git ls-remote --get-url origin
> [        ] https://github.com/flutter/flutter.git
> [        ] [D:\flutter\] git log -n 1 --pretty=format:%H
> [ +145 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
> [   +1 ms] 2e449f06f0a3be076e336ad6b30b0e9ec99dbdfe
> [   +2 ms] [D:\flutter\] git log -n 1 --pretty=format:%ar
> [ +140 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
> [   +1 ms] 18 hours ago
> [   +2 ms] [D:\flutter\] git describe --match v*.*.* --first-parent --long --tags
> [ +152 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
> [   +1 ms] v0.0.21-0-g2e449f06f
> [ +413 ms] Downloading package sky_engine...
> [  +33 ms] "flutter doctor" took 197ms.
> 
> Oops; flutter has exited unexpectedly.
> [  +51 ms] Sending crash report to Google.
> [+1507 ms] Crash report sent (report ID: 5422a551a9ae2383)
> Crash report written to D:\flutter\bin\flutter_06.log;
> please let us know at https://github.com/flutter/flutter/issues.
> [ +473 ms] ensureAnalyticsSent: 1ms
> [   +3 ms] exiting with code 1

Log file :

> Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> ## command
> flutter --no-color doctor
> ## exception
> 
> FileSystemException: FileSystemException: Exists failed, path = 'D:\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\6921873c71e700235c0f68f0359be2332f93c8bc
> w' (OS Error: The filename, directory name, or volume label syntax is incorrect.
> , errno = 123)
> 
> 
> ```
> #0      _Directory.existsSync (dart:io/directory_impl.dart:73)
> 
> #1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:41)
> #2      _ensureExists (package:flutter_tools/src/cache.dart:535)
> #3      _downloadFile (package:flutter_tools/src/cache.dart:528)
> <asynchronous suspension>
> #4      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:296)
> <asynchronous suspension>
> #5      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:322)
> <asynchronous suspension>
> #6      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:293)
> #7      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:309)
> #8      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:447)<asynchronous suspension>
> #9      CachedArtifact.update (package:flutter_tools/src/cache.dart:256)<asynchronous suspension>
> #10     Cache.updateAll (package:flutter_tools/src/cache.dart:223)<asynchronous suspension>
> #11    FlutterCommand.verifyThenRunCommand(package:flutter_tools/src/runner/flutter_command.dart:265) <asynchronous suspension>
> #12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:219)<asynchronous suspension>
> #13     CommandRunner.runCommand (package:args/command_runner.dart:194)<asynchronous suspension>
> #14     FlutterCommandRunner.runCommand(package:flutter_tools/src/runner/flutter_command_runner.dart:284)<asynchronous suspension>
> #15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
> #16     new Future.sync (dart:async/future.dart:222)
> #17     CommandRunner.run (package:args/command_runner.dart:109)
> #18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
> #19     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
> <asynchronous suspension>
> #20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
> <asynchronous suspension>
> #21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
> #22     _rootRun (dart:async/zone.dart:1126)
> #23     _CustomZone.run (dart:async/zone.dart:1023)
> #24     runZoned (dart:async/zone.dart:1501)
> #25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
> #26     run (package:flutter_tools/runner.dart:60)<asynchronous suspension>
> #27     main (package:flutter_tools/executable.dart:44)<asynchronous suspension>
> #28     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
> #29     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
> #30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
> ```
> ## flutter doctor
> 
> ```
> encountered exception: Invalid argument(s): Cannot find executable for D:\flutter\bin\cache\artifacts\engine\windows-x64\dart-sdk\bin\dart.exe.
> #0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
> #1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
> #2      Cache.engineDartVersion (package:flutter_tools/src/cache.dart:139)
> #3      FlutterVersion.engineDartVersion (package:flutter_tools/src/version.dart:86)
> #4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:215)
> <asynchronous suspension>
> #5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:106)<asynchronous suspension>
> #6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:236)
> #7      AppContext._run (package:flutter_tools/src/base/context.dart:76) <asynchronous suspension>
> #8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
> #9      _rootRun (dart:async/zone.dart:1126)
> #10     _CustomZone.run (dart:async/zone.dart:1023)
> #11     runZoned (dart:async/zone.dart:1501)
> #12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
> #13     _doctorText (package:flutter_tools/runner.dart:236)<asynchronous suspension>
> #14     _createLocalCrashReport (package:flutter_tools/runner.dart:211)<asynchronous suspension>
> #15     _handleToolError (package:flutter_tools/runner.dart:166)<asynchronous suspension>
> #16     run.<anonymous closure> (package:flutter_tools/runner.dart:93)<asynchronous suspension>
> #17     AppContext._run (package:flutter_tools/src/base/context.dart:76)<asynchronous suspension>
> #18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
> #19     _rootRun (dart:async/zone.dart:1126)
> #20     _CustomZone.run (dart:async/zone.dart:1023)
> #21     runZoned (dart:async/zone.dart:1501)
> #22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
> #23     run (package:flutter_tools/runner.dart:60)<asynchronous suspension>
> #24     main (package:flutter_tools/executable.dart:44)<asynchronous suspension>
> #25     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
> #26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
> #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
>```

**Comment by goderbauer** [comment]
Can you post the content of the crash report in `D:\flutter\bin\flutter_06.log`?

**Comment by dovahkiin98** [comment]
@goderbauer i've added the log file, pretty long

**Comment by Hixie** [comment]
@dovahkiin98 I don't see the log file anywhere?
