### ISSUE TITLE
Impeller OpenGLES (Scenario App) Tests are unstable on CI

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143626]
For example, https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/596502/overview:

> ✅  test: Android Scenario App Integration Tests (Skia)
> ✅  test: Android Scenario App Integration Tests (Impeller/Vulkan)
> 🚫  test: Android Scenario App Integration Tests (Impeller/OpenGLES)

When they do fail, it's a timeout (terminated at ~60m), [for example](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8755883953602566321/+/u/test:_Android_Scenario_App_Integration_Tests__Impeller_OpenGLES_/stdout).

Talking with @jonahwilliams, we should add some more logging to understand what step is terminating.

See also: https://github.com/flutter/flutter/issues/143458.

**Comment by jonahwilliams** [comment]
IMO this is not a P1 as our immediate goal is not to ship Impeller OpenGLES, so we only need to be concered about 1) Skia and 2) Impeller Vulkan.

**Comment by matanlurey** [comment]
Yeah that's fair, I think the real P1 is to make this bringup: true and ignore it for now.

**Comment by zanderso** [comment]
This is currently failing in staging because the staging role account doesn't have upload permission to a storage bucket: https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20Staging%20Engine%20Drone/91435/overview. The bucket seems related to SkiaGold?

**Comment by matanlurey** [comment]
Yes, https://github.com/flutter/flutter/issues/144064. Also  https://discord.com/channels/608014603317936148/1210734169550758009

**Comment by matanlurey** [comment]
Removed from CI.
