### ISSUE TITLE
Making `flutter-engine-gold.skia.org` blocking w/o causing tree pain

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143617]
_🚫 Blocking https://github.com/flutter/flutter/issues/143352_.

In [April 2023, we made the SkiaGold check _non-blocking_](https://github.com/flutter/flutter/issues/123979) with the assumption the engine sheriff would review them.

In practice, that has not (IMO) worked out particularly well:

1. The sheriff is poorly suited to make decisions other than "this needs further triage" or not
2. Lack of a blocking tree means its easy to [introduce unstable or even broken golden tests](https://github.com/flutter/flutter/issues/143591)
3. Finding the right person to review and act on untriaged goldens a time consuming and error-prone task.

We need to decide:

- [ ] Do we want to block the tree on untriaged goldens
- [ ] If yes, how do we deal with tree breakages due to untriaged goldens

The rest of this issue assumes "yes", but please chime in if you think the answer should be "no".

Questions to answer:

- What if a team wants to "try" goldens on CI, without committing to them?
  - Do we have "bringup"-style goldens?
  - Do we consider either a dimension that means "can fail" or even a separate tree (`flutter-engine-bringup.skiagold`)?
- What if a golden is flaky, i.e. a slightly different image is emitted and Skia gold can't stabilize?
- What if the tree somehow makes it to a red state out of band (i.e. there is no obvious PR to revert)?
- Should the sheriff be disabling failing/flaky golden tests in order to bring the tree green?

@zanderso @dnfield @gaaclarke @jmagman @reidbaker @johnmccutchan @jonahwilliams @Piinks @yjbanov @mdebbar

**Comment by jonahwilliams** [comment]
> What if a team wants to "try" goldens on CI, without committing to them?
>  Do we have "bringup"-style goldens?

Yes. There is a Skia Gold setting to ignore them more or less. Its what we're doing for the Impeller goldens in the framework repo. Though I am working on getting them stable...

**Comment by matanlurey** [comment]
> Yes. There is a Skia Gold setting to ignore them more or less

I did not know that! Could you share exactly what that is/how to use it?

**Comment by jonahwilliams** [comment]
I sure can't! but @Piinks can :)

**Comment by Piinks** [comment]
Ignore rules. We can ignore a given paramset in Gold if we know it is unstable. This means it will not alert at all though if it changes. Not on presubmit, postsubmit, or the dashboard. It will effectively be like skipping the test. You can view the images though on the dashboard.

See here where we are ignoring impeller in the framework: https://flutter-gold.skia.org/ignores

If there are unstable images in the engine, in the engine instance's dashboard, navigate to Ignores in the sidebar, click create new ignore rule, and select the parameters (can be just a test name) and a timeline, and then it's all set.

**Comment by reidbaker** [comment]
Without other information I lean towards yes they should block. 

For preventing flakey introductions if we have a way of running a test multiple times  locally or with a CI setting then maybe we can add a policy that before a new test is added to blocking it needs to have 100(0?) Passing runs. 

In an ideal state the team or person responsible for re enabling the test would be required to approve before a test could be disabled.

**Comment by zanderso** [comment]
Making them blocking sgtm.

**Comment by matanlurey** [comment]
Just to be clear, I want input on how we're going to deal with failures, not just if they should block 😅

**Comment by gaaclarke** [comment]
So is the idea that the sheriff will handle the blocked tree and identify tests that are flakey, putting them in some sort of ignore state and filing an issue?

It seems like not all tests are equal.  Impeller tests should be stable since we own the code here that decides what to render.  Web tests are bringing in dependencies that can cause them to drift more.  I think a bringup mechanism could handle that though.

**Comment by matanlurey** [comment]
> So is the idea that the sheriff will handle the blocked tree and identify tests that are flakey, putting them in some sort of ignore state and filing an issue?

From talking to @reidbaker and @johnmccutchan, I think folks are hoping we _don't_ do that.

Henceforth this thread, we should have alignment on how flaky or failing golden tests will be treated.



> It seems like not all tests are equal. Impeller tests should be stable since we own the code here that decides what to render. Web tests are bringing in dependencies that can cause them to drift more. I think a bringup mechanism could handle that though.

I could see having "classes" of tests, though I'd want to be careful that we aren't creating too much work for the sheriff.

**Comment by johnmccutchan** [comment]
I'm okay with disabling tests temporarily so long as person(s) have a P0 task to fix the new flakes. This would be in truly exceptional cases, because if we prioritize staying at 0% flakes across our tree, we should just be able to revert whatever change introduced the new flakes.

**Comment by zanderso** [comment]
> Just to be clear, I want input on how we're going to deal with failures, not just if they should block 😅

Yeah, sorry, was just a bit confused by the question since I don't quite understand why they'd be different from any other test when flaky. We'd follow the the process @johnmccutchan mentions in https://github.com/flutter/flutter/issues/143617#issuecomment-1949503538.

**Comment by keyonghan** [comment]
Same as mentioned in https://github.com/flutter/flutter/issues/143617#issuecomment-1954571056 by @zanderso , there are not expected to be difference to handle golden flakes or other test flakes from Infra side.

If a rerun is needed, it just consumes an extra build (bot/bots). If a disabling test PR lands, it then rerun the whole row to green the tree.
