### ISSUE TITLE
"Error: Unable to update Dart SDK" with "Start-BitsTransfer : HTTP status 403"

### ISSUE THREAD

**Issue by dovahkiin98** [flutter/flutter#14361]
When i try to update Flutter, the command line gives me this message

> C:\Users\Ahmad Sattout\flutter\bin>flutter
> Checking Dart SDK version...
> Downloading Dart SDK 2.0.0-dev.16.0...
> Start-BitsTransfer : HTTP status 403: The client does not have sufficient access rights to the requested server object.
> At C:\Users\Ahmad Sattout\flutter\bin\internal\update_dart_sdk.ps1:48 char:1
> + Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
>     + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits
>    TransferCommand
> 
> Error: Unable to update Dart SDK. Retrying...
> 
> Waiting for 4 seconds, press CTRL+C to quit ...

What do I have to do?

**Comment by goderbauer** [comment]
It is working on my Windows machine...

In addition to what @cbracken said: Are you by any chance behind a proxy? Flutter doesn't support that (see https://github.com/flutter/flutter/issues/10903), but that usually gives you a different error ("HTTP status 407: Proxy authentication is required.").

**Comment by sam43** [comment]
I am facing the same issue while updating the dark sdk... logs -

```
E:\>flutter doctor --verbose
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
Start-BitsTransfer : The service cannot be started, either because it is disabled or because it has no enabled devices
associated with it. (Exception from HRESULT: 0x80070422)
At E:\flutter\bin\internal\update_dart_sdk.ps1:47 char:1
+ Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], COMException
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits
   TransferCommand

Error: Unable to update Dart SDK. Retrying...
```

**Comment by jjccgggg** [comment]
I have a similar problem.
C:\>flutter doctor --verbose
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...

and nothing more happens.

I Have try to delete it and install from Android Studio, and is Cheking Dart SDK Version forever.

**Comment by Hixie** [comment]
Some of the errors above may have been resolved. Please try downloading flutter again but instead of "beta" use "master". If this fixes your problem, the fix will be published to the beta branch with the next beta roll in a few weeks; please do let us know here if that's the case.

@dovahkiin98 can you describe your network topology? It's not clear what might be causing this problem, it's quite surprising and we haven't seen it before.

@sam43 looks like 0x80070422 is a different issue than the one posted at the top. I recommend filing a new bug for that issue.

**Comment by cafej** [comment]
Is there a fix to this problem? I'm facing the same error

**Comment by michaelreiser** [comment]
My issues seems to be with my local 7-zip install (on Windows.)  flutter doctor uses a Powershell script, and it was failing on the unzip if else clauses.  I commented all the options out except the PS native unzip, and it now works:

`<#If (Get-Command 7z -errorAction SilentlyContinue) {
    # The built-in unzippers are painfully slow. Use 7-Zip, if available.
    & 7z x $dartSdkZip -o"$cachePath" -bd | Out-Null
} ElseIf (Get-Command 7za -errorAction SilentlyContinue) {
    # Use 7-Zip's standalone version 7za.exe, if available.
    & 7za x $dartSdkZip -o"$cachePath" -bd | Out-Null
} ElseIf (Get-Command Expand-Archive -errorAction SilentlyContinue) {
    # Use PowerShell's built-in unzipper, if available (requires PowerShell 5+).
    Expand-Archive $dartSdkZip -DestinationPath $cachePath
} Else {#>
    # As last resort: fall back to the Windows GUI.
    $shell = New-Object -com shell.application
    $zip = $shell.NameSpace($dartSdkZip)
    foreach($item in $zip.items()) {
        $shell.Namespace($cachePath).copyhere($item)
   # }
}`

**Comment by kitesoft** [comment]
https://powershell.org/forums/topic/bits-transfer-with-github/

**Comment by Hixie** [comment]
@cafej Please file a new bug with more precise details of your situation, if you're still seeing this.

@dovahkiin98 I'm going to close this bug since without the information requested in my earlier comment, there's not much we can do. Please file a new bug if you still see this. Thanks.
