### ISSUE TITLE
I encountered an error: ld: framework not found Flutter. Please help me check what is causing this

### ISSUE THREAD

**Issue by cmmourinho** [flutter/flutter#143663]
i found error when run : flutter build ios --release --no-codesign
In log 

Running pod install...                                              8.1s
Running Xcode build...                                          
Xcode build done.                                            5.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cmmourinho** [comment]
close this issue : i fix by re-install flutter

**Comment by darshankawar** [comment]
@cmmourinho 
Reinstalling sdk is not an ideal solution. We would like to know what exactly was the error you were getting so as to address it properly. If you encounter it again, please provide us verbose log that'll help us to analyse the issue better.

Closing for now.
