### ISSUE TITLE
Proposals for Dart 4.0

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [flutter/flutter#143645]
### Use case

Improve the Dart language ecosystem so that the platform has greater growth

### Proposal

The details are described in this [link](The details are described in this link https://github.com/dart-lang/language/issues/3617)

**Comment by clragon** [comment]
Duplicating issues into the wrong repository is counter-productive as the people here can not help with this.
Advertising issues in repositories that have issues representing mistakes or errors or feature suggestions just clogs up the channels.

**Comment by stuartmorgan** [comment]
Closing as off-topic for this repository.
