### ISSUE TITLE
🐛 [google_sign_in_web] Bad state: GoogleSignInPlugin::init() or GoogleSignInPlugin::initWithParams() must be called before any other method in this plugin. 

### ISSUE THREAD

**Issue by thunderbug1** [flutter/flutter#143693]
Original issue: https://github.com/firebase/flutterfire/issues/12346

Apparently the "renderButton" method does not wait for initialisation of the plugin in flutter web.

My workaround:

import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    show GoogleSignInPlatform;
...
final plugin = GoogleSignInPlatform.instance as GoogleSignInPlugin;
      await plugin.init();
with this it at least renders the login page after hanging for a couple of seconds.

**Comment by darshankawar** [comment]
@thunderbug1 
Have you looked at below implementation to check if it helps in your case or not ?

https://github.com/flutter/packages/blob/0af905d779d52fc81ffc239c211e8c5956154f34/packages/google_sign_in/google_sign_in_web/example/lib/button_tester.dart#L73

**Comment by thunderbug1** [comment]
Not really. I tried different button configurations but they seem to only change the styling, not the functionality.

For now, I settled with this workaround:
```
FutureBuilder(
future:
    (GoogleSignInPlatform.instance
            as GoogleSignInPlugin)
        .init(),
builder: (context, snapshot) {
  if (snapshot.connectionState ==
      ConnectionState.waiting) {
    return const SizedBox(
        height: 20,
        width: 20,
        child:
            CircularProgressIndicator());
  }
  return web.renderButton(
      configuration: web
          .GSIButtonConfiguration(
    minimumWidth: 360,
    size: GSIButtonSize.large,
    shape: GSIButtonShape.pill,
    logoAlignment:
        GSIButtonLogoAlignment
            .center,
    theme: web
        .GSIButtonTheme.outline,
  ));
})
```

**Comment by darshankawar** [comment]
Can you provide us complete runnable code sample that shows the error before you added the workaround ?

**Comment by lucasbstn** [comment]
After running into this issue as well, the proper way to fix it is to create an instance of GoogleSignIn somewhere before calling the web.renderButton function.

```dart
class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final googleSignIn = GoogleSignIn();

  @override
  Widget build(BuildContext context) {
    return web.renderButton();
  }
}
```
