### ISSUE TITLE
[Regression] [iOS] ViewInsets in not updated when keyboard gets opened master, 3.20.0-7.0.pre.17

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#143642]
### Steps to reproduce

Run this sample
https://github.com/delfme/flutter-native-text-input-repo

### Expected results

The bottomBar should move up when keyboard is opened

### Actual results

The bottomBar doesnt move up when keyboard is opened coz viewInsets `bottom` is zero.
Issue occurs only on iOS.

### Code sample

https://github.com/delfme/flutter-native-text-input-repo

### Screenshots or Video

Video below:

https://github.com/flutter/flutter/assets/53510751/433fbad2-d659-476f-bcd6-3112ee3fd49d

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 Flutter (Channel master, 3.20.0-7.0.pre.17, on macOS 14.2.1 23C71 darwin-arm64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by TahaTesser** [comment]
I can reproduce the regression. It is caused by https://github.com/flutter/engine/pull/50364. Looking into reverting the fix.

**Comment by delfme** [comment]
@TahaTesser thx for the quick fix.
Would you be so kind as to also have a look at some jerking that was used to occur during animation? Basically, when viewInsets animates the UI while keyboard raises up, there was some jerking due to the fact that flutter animation and native animation can get out of sync at times.
No idea if that issue is still reproducible on master.

**Comment by TahaTesser** [comment]
> Would you be so kind as to also have a look at some jerking that was used to occur during animation? 

That's an unrelated issue. There have been such reports.
