### ISSUE TITLE
[web]: <Flutter web element embedding after build>

### ISSUE THREAD

**Issue by volkaankarakus** [flutter/flutter#143699]
### **Experiment** 
Using a project built with element embedding on Flutter Web in another JS project

With element embedding on Flutter web, I can use a flutter project in another js project without any problems, as shown in Flutter seminars and Stackoverflow.
But what I want to do now is to give someone the build file created after flutter build and have that person combine their own project with the build files I sent.
So let's assume that the other party has no flutter knowledge and only the built js files are given to the other party and they are trying to integrate it.

### **Problem** 
How can the other party assemble the project with index.html, flutter.js, flutter.main.js in the build file under these conditions?
The project example I am trying to combine is a project with its own html and js files as below.
https://github.com/lassiecoder/E-CommerceWebsite

**Comment by huycozy** [comment]
Could you check [Community Contributions](https://github.com/flutter/samples/tree/main/web_embedding#community-contributions) with sample code there to see if it helps?
