### ISSUE TITLE
Certain files (such as `android/**/GeneratedPluginRegistrant.java`) should never exist

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143782]
See https://github.com/flutter/engine/pull/50795.

A `.gitignore` file is useful to keeping the source tree and CI from being corrupted, but actually papers over the fact that it's easy to corrupt your _local_ source directory. One off-the-wall suggestion with @zanderso and @dnfield was some sort tool/check that verifies that the source tree never contains certain files.

As a strawman, a `.gitnogoaway`:
```txt
**/android/**/GeneratedPluginRegistrant.java
```

... which is failed if it exists on CI or locally.

There is an existing file that matches this pattern in our source tree, so we'll need to rename that file.

**Comment by dnfield** [comment]
This is triggering for me on `./third_party/dart/third_party/pkg/http/pkgs/cronet_http/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java`. Is that intended...

**Comment by dnfield** [comment]
It's because I ran it from `src` as `./flutter/ci/format.sh`
