### ISSUE TITLE
Investigate power on settings for win arm bots

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#143775]
### Type of Request

infra task

### Infrastructure Environment

devicelab, win arm

### What is happening?

@kentnguyen99  please take a look at this options and see if you can find the setting to have the win arm bots startup automatically after power loss:

**Here's how to set a reboot on power loss in UEFI:**
Restart your computer
Press the key to enter the BIOS or UEFI firmware setup
Find a setting related to power management or power-on options
Change the setting to allow your computer to start up automatically when power is connected
Save the settings and exit the BIOS 

**The "Restore on AC/Power Loss" setting can be found under different places inside BIOS setup according to computer manufacturer.** 
Here are some steps to enable power on restore AC power loss/AC recovery/AC BACK:
Press F7 to enter Advanced Mode
Visit Settings > Advanced > Power Management Setup
Set Restore after AC Power Loss to Power On
Visit Settings > Advanced > Save & Exit
Select Save Changes and Reboot 

**You can also set the automatic power-on state in BIOS:**
From the System Utilities screen, select System Configuration > BIOS/Platform Configuration (RBSU) > System Options > Server Availability > Automatic Power-On
Select a setting
Choose "Always Power On" so the system automatically returns to a power on state, even if it was in the “off” state when power was lost 

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
I have tried all steps was instructed in this ticket but none of steps were applied to ARM Windows Kits working.  According to Microsoft website instruction - BIOS doesn't exist on ARM Windows Kits hardware like x86 hardware.

**Comment by kentnguyen99** [comment]
There is no option to set auto power on when power outage come back online for Windows Dev Kit 2023 Desktop PC. This service ticket is closed.
