### ISSUE TITLE
Assets no longer renders after pushing native VC and locking on iPhone X

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14374]
Have a screen with asset images, push a native ViewController, lock the screen, unlock and pop back to the first screen. Images no longer render and shows black boxes

**Comment by csbenjamin** [comment]
Is it related to this? https://github.com/flutter/flutter/issues/14228

**Comment by xster** [comment]
Thanks. It seems like it is since I can no longer reproduce this.
