### ISSUE TITLE
Javascript source maps does not work

### ISSUE THREAD

**Issue by woprandi** [flutter/flutter#143703]
### Steps to reproduce

1. Create new app
2. Add `throw Exception("test")` somewhere
3. Build on web with `--source-maps` flag
4. `cd build/web`
5. Test locally `python -m http.server` for example

### Expected results

Original Dart code stack trace

### Actual results

Minified Javascript code stack trace

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    throw Exception("test");
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
       colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Text("test"),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/1449422/d45ee160-c9ae-4ffa-937b-43099992a209)
</details>

Javascript source maps is enabled on Chrome 
![image](https://github.com/flutter/flutter/assets/1449422/dc4988fd-784c-486a-b4a9-4bc98fc34f9b)

### Logs

<details open><summary>Logs</summary>

`main.dart.js.map` is correctly generated and loaded by browser

```console
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /flutter.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] code 404, message File not found
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /flutter.js.map HTTP/1.1" 404 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /manifest.json HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /main.dart.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /icons/Icon-192.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /main.dart.js.map HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /assets/FontManifest.json HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /assets/fonts/MaterialIcons-Regular.otf HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /assets/packages/cupertino_icons/assets/CupertinoIcons.ttf HTTP/1.1" 200 -
127.0.0.1 - - [19/Feb/2024 14:00:16] code 404, message File not found
127.0.0.1 - - [19/Feb/2024 14:00:16] "GET /main.dart HTTP/1.1" 404 -
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.0, on Fedora Linux 39 (Workstation Edition) 6.7.4-200.fc39.x86_64, locale fr_FR.UTF-8)
    • Flutter version 3.19.0 on channel stable at /home/william/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (il y a 5 jours), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/william/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/william/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6 (Fedora 17.0.6-2.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/william/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin version 77.1.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at /home/william/.local/share/JetBrains/Toolbox/apps/intellij-idea-community-edition
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.86.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.7.4-200.fc39.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate the reported behavior using latest stable and master versions.

<img width="751" alt="Screenshot 2024-02-20 at 12 03 06 PM" src="https://github.com/flutter/flutter/assets/67046386/79e27f36-dff7-4260-89d1-8093f32d44bc">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.19.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.19.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.20.0-10.0.pre.50, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.20.0-10.0.pre.50 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2d422a3261 (31 minutes ago), 2024-02-19 21:49:05 -0800
    • Engine revision e96c18b6c5
    • Dart version 3.4.0 (build 3.4.0-155.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by yjbanov** [comment]
This looks like a regression. I don't see source maps generated at all.

**Comment by woprandi** [comment]
@yjbanov There are `main.dart.js.map` in my example but it seems invalid

**Comment by yjbanov** [comment]
@woprandi Could that file be a left-over from an old build? Is the file still there if you `flutter clean` before `flutter build`?

**Comment by woprandi** [comment]
@yjbanov No I tested again after removing build folder, the map file is created

**Comment by woprandi** [comment]
I'm doubful, the map file was already generated but I'm not able to see dart stacktrace. I tested with the referenced PR and I don't see any behavior changes

**Comment by eyebrowsoffire** [comment]
@woprandi you're saying you tried this on the master channel after https://github.com/flutter/flutter/pull/144832 landed but you're still not getting the right source map files when running `flutter build web`? And you've done a `flutter clean` and hard refreshed your browser/cleared cache?

**Comment by woprandi** [comment]
Yeah I checkout master branch 1 hour ago.
I always had a source map (even before your patch). Chrome says it's loaded but I'm still unable to get a dart stacktrace appears in the browse console.
Does my test code works for you ?

**Comment by eyebrowsoffire** [comment]
Ah, actually I think there has been a bit of a misunderstanding with this bug.

Your original report is about the stack trace reported to console. I believe there isn't a mechanism that uses the source maps to deobfuscate *that* stack trace. However, with the proper source maps, if you pause on exception in Chrome devtools, devtools can load the source maps and show the original names and dart source locations for each frame of the stack trace.

When we were looking into this issue, we attempted to reproduce on the master channel, only to find that source maps were not actually being copied the output build folder at all. That was actually due to a regression introduced in 3.21, which is on the beta channel. But this problem is actually unrelated to your original issue, I think we originally misunderstood and immediately assumed that's what you were reporting. But you were actually running against 3.19, which did not have the issue with generating the source maps.

I think the issue you're describing is a limitation of dart itself in how it spits stack traces out to console on the web. I think this your issue is basically similar/a duplicate of to https://github.com/dart-lang/sdk/issues/40117. For now though, if you can repro your issue and you want to see stack traces you can set Chrome devtools to pause on exceptions, and it will deobfuscate the stack traces with the source maps.

**Comment by woprandi** [comment]
Ok I understand. That can be a viable workaround
But there are another bugs, when I set Chrome to pause on exceptions, it searches a `/lib/main.dart` file (which does not exists on {build/web` folder)

![image](https://github.com/flutter/flutter/assets/1449422/099c2e6b-a311-41fd-b309-aa1c3701e188)

**Comment by laszukdawid** [comment]
Hi, I've been hunting this issue, i.e. missing `flutter.js.map` for the last few hours. I'm on flutter 3.19.0. Do I understand correctly that this issue has been reproduced and fixed, and would be expected in some newer version?

**Comment by woprandi** [comment]
I'd keep issue open because we have to copy dart source manually to `build/web` to be able to debug

**Comment by eyebrowsoffire** [comment]
Copying over the source files into the build folder automatically is not something we should do in the flutter tool as part of `flutter build web`. Using `flutter run` already ensures that the local flutter web server serves source files and source maps for debugging. If you're using `flutter build web` and running your own local HTTP server, you can either host both the source folder and the build output folder, or do the copying yourself. Most scenarios where people are running `flutter build web` they will not want to be including all their sources in the released bundle.

**Comment by laszukdawid** [comment]
@eyebrowsoffire I'm using snap for flutter and changed the channel to "master" which gives me
```
$ flutter --version
Flutter 3.21.0-4.0.pre.14 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1ca88730a0 (26 hours ago) • 2024-03-11 18:31:25 -0700
Engine • revision 6745955bb4
Tools • Dart 3.4.0 (build 3.4.0-220.0.dev) • DevTools 2.33.1
```

After building with `flutter build web --source-maps --no-tree-shake-icons --web-renderer html` I still don't see `flutter.js.map` in the `build/web`. I do see `main.dart.js.map` which in `html` render where there before as well.

In case it helps, after building with the above command, my dir structure is
```
$ tree build/web/ -L 1
build/web/
├── assets
├── canvaskit
├── favicon_bg.ico
├── favicon_bg.png
├── favicon.png
├── flutter.js
├── flutter_service_worker.js
├── icons
├── index.html
├── main.dart.js
├── main.dart.js.map
├── manifest.json
└── version.json
```


For my use case, I'm serving web app in a docker via ngnix. Can definitely copy/rename files if that's a need. But, I'm honestly a bit lost here what is what. I'm fairly new to the flutter ecosystem and documentation doesn't share much.

**Comment by woprandi** [comment]
@eyebrowsoffire Not copying sources automatically but map files without original sources are useless

**Comment by eyebrowsoffire** [comment]
@laszukdawid Ah you're asking about `flutter.js.map`. That's a separate issue from `main.dart.js.map`. We haven't ever included `flutter.js.map` in the output folder, but that may be worth doing. I filed https://github.com/flutter/flutter/issues/145111 to track it

**Comment by laszukdawid** [comment]
I see, thanks @eyebrowsoffire for the explanation and sorry for the extending this thread. I'll watch the opened ticket :)

In case it isn't a problem for you (or anyone), any chance one can share resources on how to use that `main.dart.js.map` source map?
My lack of experience/understanding might shine through, but although I have the source map in the deployed web app (directory as above), I only see minified `mart.dart.js`. Since I'm serving from docker via nginx I've double checked that files are in the same location. In case anyone is curious, the web app is https://console.homehero.pro/.

**Comment by Apidcloud** [comment]
> Copying over the source files into the build folder automatically is not something we should do in the flutter tool as part of `flutter build web`. Using `flutter run` already ensures that the local flutter web server serves source files and source maps for debugging. If you're using `flutter build web` and running your own local HTTP server, you can either host both the source folder and the build output folder, or do the copying yourself. Most scenarios where people are running `flutter build web` they will not want to be including all their sources in the released bundle.

We are doing exactly this. We use 'flutter build' with source maps and then copy the build result onto our staging server (i.e., without flutter run). I was able to copy the `/lib` where our dart code is located to the server and then change main.dart.js.map `sourceRoot` to match the server configurations.

But I noticed that obviously other files coming from packages or dart sdk are not found: "Could not load content for org-dartlang-sdk:///lib/ui/canvas.dart"

What do you recommend in case we want to do the copy ourselves?
