### ISSUE TITLE
Missing PrivacyInfo.xcprivate

### ISSUE THREAD

**Issue by eaceto** [flutter/flutter#143772]
### Steps to reproduce

0) Using Xcode 15.2 in macOS Sonoma

1) Install version 0.8.9+1 of image_picker_ios

2) Run `flutter run --release`on an iOS Device

This command will output something like:

Error (Xcode): /Users/.../.pub-cache/hosted/pub.dev/image_picker_ios-0.8.9+1/ios/Resources/PrivacyInfo.xcprivacy: No such file or directory

### Expected results

A correct build

### Actual results

The build fails because library does not have a Privacy Manifest (https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) 

### Code sample

* it's a build problem, it happens when importing this library *

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64, locale en-GB)
    • Flutter version 3.19.0 on channel stable at /Users/kimi/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (7 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kimi/SDKs/Android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/kimi/SDKs/Android
    • Java binary at: /Applications/Android Studio Dolphin.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Dolphin.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Users/kimi/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 233.11799.172

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)            
    • macOS (desktop)                • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                   • chrome                    • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.
</details>

**Comment by stuartmorgan** [comment]
Does `dart pub cache repair` resolve this? That file [does exist](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker_ios/ios/Resources), so this is likely an issue with your cached copy.

**Comment by kimi-argentech** [comment]
Sorry for that. I'll close this issue. Thanks very much
