### ISSUE TITLE
Update the instruction of compiling and running engine and its tests on Fuchsia

### ISSUE THREAD

**Issue by zijiehe-google-com** [flutter/flutter#143787]
### Document Link

https://github.com/flutter/flutter/wiki/Compiling-the-engine/86125392094c1ce69fb34dcdd53e3c57d3aaa91a

### What problem are you solving?

The existing document is out-of-date and the recent changes I have submitted simplified the process to match other platforms without needing to know fuchsia details.

Unfortunately github does not support creating a PR for wiki pages, and I'd like to have someone reviewed my change before submitting.

The updated wiki can be found at https://github.com/flutter/flutter/wiki/Compiling-the-engine/86125392094c1ce69fb34dcdd53e3c57d3aaa91a#compiling-for-fuchsia

The diff of raw file can be found at https://github.com/flutter/flutter/wiki/Compiling-the-engine/_compare/d8c83a07afacbcd6e3938e83bb6976fa73f65f8e...86125392094c1ce69fb34dcdd53e3c57d3aaa91a.

**Comment by CaseyHillers** [comment]
Thanks for updating this, this LGTM!

Instead of editing `.gclient` directly, would `gclient config --custom-var=run_fuchsia_emu=True` be preferred?

**Comment by zijiehe-google-com** [comment]
Oh, yes, it's much clear. Updated.

**Comment by zijiehe-google-com** [comment]
I will go ahead and merge the doc.

**Comment by zijiehe-google-com** [comment]
Done with 584c4a7eb8f857cc41e2e60828b0dc668c019f43
