### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: Address family not supported by protocol family, errno = 47

### ISSUE THREAD

**Issue by praveenkutta08** [flutter/flutter#143707]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: Address family not supported by protocol family, errno = 47
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:228:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:184:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:429:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:615:5)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.13.9 on channel stable at /Users/praveen/Documents/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d211f42860 (4 months ago), 2023-10-25 13:42:25 -0700
    [32m•[39m Engine revision 0545f8705d
    [32m•[39m Dart version 3.1.5
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/praveen/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15C500b
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.82.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Praveen Kumar’s iPhone (mobile) • 00008110-0002582C2280A01E            • ios            • iOS 17.3 21D50
    [32m•[39m iPhone 15 (mobile)              • 5AD6DBDD-3BF6-4BCA-8001-3D2840B6A8BB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    [32m•[39m macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                               • web-javascript • Google Chrome 121.0.6167.184

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.4.4+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
android_id-0.3.6
audio_session-0.1.18
audioplayers-1.2.0
audioplayers_android-1.1.3
audioplayers_darwin-1.0.4
audioplayers_linux-1.0.2
audioplayers_web-2.1.0
audioplayers_windows-1.1.1
cloud_firestore_web-2.8.10
connectivity_plus-3.0.6
device_info-2.0.3
device_info_plus-9.1.1
file_picker-5.5.0
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_analytics-9.3.8
firebase_analytics_web-0.4.2+7
firebase_core-1.24.0
firebase_core_web-1.7.3
firebase_crashlytics-2.9.0
firebase_messaging-13.1.0
firebase_messaging_web-3.2.0
flutter_appauth-4.2.1+1
flutter_audio_recorder3-0.0.5
flutter_dtmf-2.0.2
flutter_image_compress-1.1.3
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_local_notifications-12.0.4
flutter_plugin_android_lifecycle-2.0.17
flutter_secure_storage-6.1.0
flutter_secure_storage_linux-1.2.0
flutter_secure_storage_macos-1.1.2
flutter_secure_storage_web-1.1.2
flutter_secure_storage_windows-1.1.3
flutter_vibrate-1.3.0
fluttertoast-8.2.4
image_picker-0.8.9
image_picker_android-0.8.9+1
image_picker_for_web-2.2.0
image_picker_ios-0.8.9
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
just_audio-0.9.36
just_audio_web-0.4.9
package_info-2.0.2
path_provider-2.1.1
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
record-4.4.4
record_linux-0.4.1
record_macos-0.2.2
record_web-0.5.0
record_windows-0.7.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
speech_to_text-6.5.1
speech_to_text_macos-1.0.2
sqflite-2.3.0
twilio_voice_call_plugin
uni_links-0.5.1
uni_links_web-0.1.0
uri_to_file-0.2.0
url_launcher-6.2.2
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.1
vibration-1.8.4
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment]
Hi @praveenkutta08, you are using an older version of the flutter framework. Kindly upgrade to the latest version of flutter stable (3.19.0) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`. 

Thank you
