### ISSUE TITLE
Add Tooltips to the Close Button of Snackbar

### ISSUE THREAD

**Issue by dsanagustin** [flutter/flutter#143793]
### Use case

We want to make our application more accessible. As part of that effort, we have been attaching tooltips/labels to buttons so that screen readers can read out more helpful descriptions to their users instead of the default "Button" or "Push Button".

`Snackbar` provides no way to do this easily, even for classes extending it.

### Proposal

I would like the Flutter team to either:

1. Allow the ability to pass in a close button tooltip via the constructor. OR
2. Use `MaterialLocalizations.closeButtonTooltip` as the tooltip to the IconButton representing the close button on the Snackbar.

**Comment by HansMuller** [comment]
@dsanagustin - I'm closing this - assuming that https://github.com/flutter/flutter/pull/143934 fixes the problem. If not, please reopen.
