### ISSUE TITLE
Warning: CocoaPods version 1.0.0 or greater not installed. Skipping pod install.

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#14379]
When I try and flutter run an app on an ios device that uses plugins, I see:

Launching lib/main.dart on iPhone 7 in debug mode...
Warning: CocoaPods version 1.0.0 or greater not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
  For more info, see https://flutter.io/platform-plugins
To install:
  brew install cocoapods
  pod setup

but in fact I have installed cocoapods, when I run pod -- version , it displays '1.3.1' 
Now I have to run pod install menually everytime I add new plug-in ,what should I do?

**Comment by zoechi** [comment]
Just a wild guess. Did you open Xcode and let it install missing dependencies?

**Comment by manujbahl** [comment]
Did you figure out a solution? I have the same problem and xcode does not report any missing dependencies

**Comment by xster** [comment]
Duping into #14293

**Comment by Romnn** [comment]
I'm having same trouble 
![screen shot 2018-05-16 at 12 34 58 pm](https://user-images.githubusercontent.com/16022010/40100893-5745f534-5905-11e8-85b4-0abc46069d0d.png)

**Comment by junyou131** [comment]
error for:pubspec.yaml
Is a plug-in version of the problem
