### ISSUE TITLE
Unclear how to add/edit platform view code to an existing Flutter app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14373]
More or less the reverse of https://github.com/flutter/flutter/issues/8945. 

Given a new Flutter project, if some code needs to be done in the platform side:

- [ ] How to open Xcode, how is the iOS code structured
- [ ] How to open Android Studio, how is the Android code structured
- [ ] How to bring in existing local iOS/Android source code
- [ ] How to refer to existing iOS/Android packages using gradle / CocoaPods

cc @sethladd, @Sfshaza

**Comment by sethladd** [comment]
Is documentation sufficient, or do we need tooling additions as well?

**Comment by xster** [comment]
I think it's just documentation (and potentially run over small bugs while testing in). Nothing conceptually blocking it from a technical perspective.

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/14821 https://github.com/flutter/flutter/issues/12765 https://github.com/flutter/flutter/issues/12827 https://github.com/flutter/flutter/issues/8945 https://github.com/flutter/flutter/issues/10348 . We could probably coalesce some of these. :)

**Comment by eseidelGoogle** [comment]
@mit-mit would you like to keep this one or https://github.com/flutter/flutter/issues/14821?

**Comment by mit-mit** [comment]
Let's keep #14821, please (it's the one we have been asking customers to 'vote' on; it has 23 votes currently).

@xster I'll close this; feel free to edit the description of #14821 if it need more details!
