### ISSUE TITLE
Upgrade remaining flutter devicelab mac bots to macOS 13.6.x

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#143768]
### Type of Request

infra task

### Infrastructure Environment

devicelab, mac

### What is happening?

Per https://github.com/flutter/flutter/issues/134737 :

upgrade remaining mac bots to macOS 13.6.1:

`prod` pool:
flutter-devicelab-mac-22
flutter-devicelab-mac-24
flutter-devicelab-mac-25
flutter-devicelab-mac-31
flutter-devicelab-mac-36
flutter-devicelab-mac-42
flutter-devicelab-mac-44

`try` pool:
flutter-devicelab-mac-14
flutter-devicelab-mac-17
flutter-devicelab-mac-46

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by vashworth** [comment]
Once upgraded, ensure the following:

Delete any directories within `/opt/flutter/xcode` if applicable.

Also verify `/opt/flutter/xcode` is owned by `swarming` user.

Also, ensure `DevToolsSecurity` is enabled.

Run `DevToolsSecurity` - should get response "Developer mode is already enabled."
If you don't get the message, run `sudo /usr/sbin/DevToolsSecurity -enable` to enable.

**Comment by kentnguyen99** [comment]
All Bots listed in this ticket have been upgrade MacOS 13.6.4 as requested. All works completed and ticket is closed.
