### ISSUE TITLE
[tool_crash] _TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))

### ISSUE THREAD

**Issue by Bryan-Growdev** [flutter/flutter#143718]
## Command
```
flutter build apk --analyze-size --target-platform android-arm64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75))
```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:548:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.6, on Ubuntu 23.10 6.5.0-17-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.10.6 on channel stable at /opt/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f468f3366c (7 months ago), 2023-07-12 15:19:05 -0700
    [32m•[39m Engine revision cdbeda788a
    [32m•[39m Dart version 3.0.6
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /home/bryan-growdev/Android/Sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-123.10)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[31m[✗][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Ubuntu clang version 16.0.6 (15)
    [32m•[39m cmake version 3.27.4
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 1.8.1
    [31m✗[39m GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[33m[!][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /snap/android-studio/148
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m VS Code
    [32m•[39m VS Code at /snap/code/current
    [32m•[39m Flutter extension version 3.82.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-17-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.160

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.19+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5464c5bac742001448fe4fc0597be939379f88ea
### Plugins
app_settings-4.2.0
connectivity_plus-4.0.1
device_info_plus-9.1.2
file_selector_linux-0.9.2
file_selector_macos-0.9.3
file_selector_windows-0.9.3
firebase_analytics-10.8.0
firebase_analytics_web-0.5.5+12
firebase_core-2.24.2
firebase_core_web-2.10.0
firebase_crashlytics-3.4.9
firebase_performance-0.9.3+8
firebase_performance_web-0.1.4+16
flutter_blue_plus-1.29.6
flutter_plugin_android_lifecycle-2.0.15
flutter_vibrate-1.3.0
image_picker-1.0.0
image_picker_android-0.8.7+3
image_picker_for_web-2.2.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_windows-0.2.1
local_auth-2.1.6
local_auth_android-1.0.32
local_auth_ios-1.1.3
local_auth_windows-1.0.8
network_info_plus-4.0.1
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.4
path_provider_linux-2.1.11
path_provider_windows-2.1.7
permission_handler-10.4.1
permission_handler_android-10.3.0
permission_handler_apple-9.1.2
permission_handler_windows-0.1.3
share_plus-7.1.0
shared_preferences-2.2.0
shared_preferences_android-2.2.0
shared_preferences_foundation-2.3.0
shared_preferences_linux-2.3.0
shared_preferences_web-2.2.0
shared_preferences_windows-2.3.0
sqflite-2.2.8+4
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.1.12
url_launcher_android-6.0.38
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.6
url_launcher_web-2.0.18
url_launcher_windows-3.0.7

**Comment by danagbemava-nc** [comment]
Hi @Bryan-Growdev. This has been fixed in the latest version of flutter stable. See [flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3134-september-13-2023](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3134-september-13-2023). This was fixed in 3.16.0

Closing from here. If you still face this issue on the latest version of flutter stable (3.19.0), kindly leave a comment below and I will reopen this.

See https://github.com/flutter/flutter/issues/132695 for the original issue.

Thank you
