### ISSUE TITLE
Lightweight engines use significantly more memory for loading fonts

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#143701]
See https://github.com/jiahaog/bug_font_memory_multiple_engines/commit/b794f2513005a590c7acf3ce22313ee81eccb6b5 for a Flutter app that can be used to repro this.

In release mode on a Pixel 6a, I collected the following profiles with the [Perfetto Heap Profiler](https://perfetto.dev/docs/data-sources/native-heap-profiler). We need to use a local unstripped engine build so that symbols from libflutter.so can be symbolicated. A userdebug build for the device may also be needed. 

The number of engines can be toggled through this constant [here](https://github.com/jiahaog/bug_font_memory_multiple_engines/blob/1f89cf3d0225679aba8390b56c58da275be45ef1/android/app/src/main/java/com/example/bug_font_memory_multiple_engines/RecyclerViewAdapter.java#L20).

1. Install the app, then close it.
    ```sh
    flutter run \
      -d 'Pixel 6a' \
      --release \
      --local-engine=$HOME/dev/engine/src \
      --local-engine=android_release_unopt_arm64 \
      --local-engine-host=host_release_unopt
    ```
4. Run 
    ```sh
    tools/heap_profile -n com.example.bugfontmemory
    ```
5. Start the app, wait 20 sec
6. Press ctrl-c in the terminal to stop recording.

Profiles:

- [1 engine](https://ui.perfetto.dev/#!/?s=e65c3deb680826946057ea45ca694bc52b99449513224d74a83a5222d09d0da2)
- [16 engines](https://ui.perfetto.dev/#!/?s=feb243b5e00b41327bc21966df839609f60f313f598d00ec38f4c2d382ea3af2)

Actually the perfetto UI is unable to handle such deeply nested stacks, but should be able to download the profiles, open it with pprof to see the following:

![image](https://github.com/flutter/flutter/assets/7111741/f67381ab-9a78-47e9-a699-1e8b9cb1296a)

Observe that in the screenshot, for `flutter::AssetManagerFontStyleSet::createTypeface(int)`, the difference here is 4.711 MiB (many engines) vs 1.577 MiB (single engine).

As mentioned by @dnfield, this is likely due to https://github.com/flutter/engine/pull/34473.

This is with:

```
Flutter 3.20.0-10.0.pre.11 • channel main • git@github.com:flutter/flutter
Framework • revision a603a17875 (3 days ago) • 2024-02-16 09:43:50 +0200
Engine • revision dd530f1556
Tools • Dart 3.4.0 (build 3.4.0-148.0.dev) • DevTools 2.33.0-dev.6
```

See also http://shortn/_afwYysWZou for more details internally. I have also attached links to uploaded profiles onto pprof there.

**Comment by jonahwilliams** [comment]
@dnfield would it make sense to revert #34473 to unblock the g3 work here, or do you think there is a way we could adjust this behavior (or make it configurable?)

**Comment by dnfield** [comment]
I think reverting it locally and verifying that it fixes things is worth validating, if it does I think we can come up with another way to solve that problem without directly reverting

**Comment by jiahaog** [comment]
Thanks Dan. I'm still trying to verify if I missed something in my setup, but it seems like neither https://github.com/flutter/engine/pull/50812 nor a revert of https://github.com/flutter/engine/pull/34473 (in https://github.com/jiahaog/flutter-engine/commit/9d5f22b6a7c461073579ba740560dace7e9ecc8e) seems to solve the problem.


With pprof, I was able to collect the following readings:

```
pprof -top  /tmp/heap_profile-latest/*.gz | grep createTypeface
```


```sh
# With https://github.com/flutter/engine/pull/50812
## Multi-engine
         0     0%   100%     4.72MB 15.59%  flutter::AssetManagerFontStyleSet::createTypeface(int)
## Single engine 
         0     0%   100%     1.57MB  6.21%  flutter::AssetManagerFontStyleSet::createTypeface(int)

# With https://github.com/flutter/engine/commit/9d5f22b6a7c461073579ba740560dace7e9ecc8e
## Multi-PR 
         0     0%   100%     4.71MB 15.63%  flutter::AssetManagerFontStyleSet::createTypeface(int)
## Single engine
         0     0%   100%     1.57MB  6.21%  flutter::AssetManagerFontStyleSet::createTypeface(int)
```

(We would expect the values for the fourth column above (for cumulative unreleased memory) to be the same for multi-engine and the single engine rows if the issue is fixed)

**Comment by jiahaog** [comment]
When https://github.com/flutter/engine/pull/34473 is reverted, I think the reason why `Engine::UpdateAssetManager`doesn't [return early](https://github.com/flutter/engine/blob/224367a524413a47a95508c3b0ce422d063bfeda/shell/common/engine.cc#L177) is that even though we're [creating](https://github.com/flutter/engine/blob/c96300c1ee6810243b7eb157c6f8c02d1238892b/shell/platform/android/platform_view_android_jni_impl.cc#L277) and reusing the same instance of the `AssetManager`, the `Engine` object *instance* is different when `Engine:UpdateAssetManager` is called multiple times in a multi-engine scenario.

I checked this in a two engine scenario - for both times `Engine::UpdateAssetManager` is called, while [`new_asset_manager`](https://github.com/flutter/engine/blob/224367a524413a47a95508c3b0ce422d063bfeda/shell/common/engine.cc#L176) points to the same raw object address, `this` (the `Engine`) is different each time, and [`asset_manager_`](https://github.com/flutter/engine/blob/224367a524413a47a95508c3b0ce422d063bfeda/shell/common/engine.h#L1032) points to `nullptr`. As such, the equality check to return early always fails.
