### ISSUE TITLE
[Flutter 3.16.9] Textfield magnifier breaks when using canRequestFocus

### ISSUE THREAD

**Issue by ciganovic-milan** [flutter/flutter#143843]
### Steps to reproduce

Present on both platforms: [Android & iOS]

1. Create a simple textfield with the code provided in the code sample
2. Try to magnify the text inside the textfield on both platforms

### Expected results

The magnifier's overlay entry should disappear and not be blended into the screen.

### Actual results

Magnifier is blended into the screen and does not disappear until the app is restarted.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const AppBarApp());

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TextField(canRequestFocus: false),
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3 23D56 darwin-arm64, locale en-RS)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
[✓] VS Code (version 1.86.2)
[✓] Connected device (4 available)            
[✓] Network resources

**Comment by dam-ease** [comment]
Thanks for filing this @ciganovic-milan.
This seems similar/related to https://github.com/flutter/flutter/issues/130011.
Can you check this out?

**Comment by ciganovic-milan** [comment]
@dam-ease Yeah, thats it, we can close it then as a duplicate 👍
