### ISSUE TITLE
[CP] Hot fix `package:unified_analytics` version to `5.8.0+1`

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#143886]
### Issue Link

https://github.com/flutter/flutter/issues/143792

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/143885

### Changelog Description

Bumps the version for analytics to a hotfixed version that fixes flakey bug around parsing session json file

### Impacted Users

All flutter users

### Impact Description

This error would periodically crash the flutter tool which in turn would crash running apps.

### Workaround

No workaround

### Risk

medium

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
Released in 3.19.2
