### ISSUE TITLE
HLS (.m3u8) format video from file not playing on iOS devices 

### ISSUE THREAD

**Issue by sthakrishnakumar** [flutter/flutter#143822]
### Steps to reproduce

Download any HLS Video offline and play from file in iOS devices.

### Expected results

.m3u8 file should be played in iOS devices.

### Actual results

I am trying to play videos offline, and this works on Android but on iOS, even when run on real device it's showing the following error:
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Failed to load video: The operation couldn’t be completed. (CoreMediaErrorDomain error -12865.), null, null)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @sthakrishnakumar 
Which iOS version are you checking this on? This looks similar to https://github.com/flutter/flutter/issues/116021 which pointed out that it's not an issue on video_player plugin, but instead Apple's issue. You may try playing your video with SwiftUI code at https://github.com/flutter/flutter/issues/116021#issuecomment-1329595006 to see if it works or not.
