### ISSUE TITLE
ServiceMap needs methods (or stubs) to continue implementing Dart 2.0's Map

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#14389]
In Dart 2.0, Map is getting a few new methods, so implementors need to also have these methods. See https://github.com/dart-lang/sdk/issues/31814 and https://github.com/dart-lang/sdk/issues/31812. Here are the new method signatures:

```dart
Map<K2, V2> cast<K2, V2>();
Map<K2, V2> retype<K2, V2>();
Iterable<Null> get entries;
void addEntries(Iterable<Object> entries)
Map<K2, V2> map<K2, V2>(Object transform(K key, V value));
V update(K key, V update(V value), { V ifAbsent() });
void updateAll(V update(K key, V value));
void removeWhere(bool test(K key, V value));
```

flutter_tools has a [class ServiceMap](https://github.com/flutter/flutter/blob/10f721c8a5873a7477984507c1d0db7109049586/packages/flutter_tools/lib/src/vmservice.dart#L1235) that implements Map.

ServiceMap already implements an `update` method (#14338), and needs methods (or more likely, method stubs) before Dart 2.0 is released.

I have a patch ready.

CC @tvolkert

**Comment by srawlins** [comment]
Ping. The new methods on Map are landing in Dart ~2.0.0-dev.22.0.

**Comment by Hixie** [comment]
Closing since the PR was closed. Please let me know if we actually still need this.
