### ISSUE TITLE
Widget to support Swipe Actions

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#14388]
A common pattern for swiping horizontally on a list item is to display a set of action icons at can be tapped on to perform some task. On iOS, this is commonly implemented using a UITableView  (https://developer.apple.com/documentation/uikit/uitableviewrowaction).

The Dismissible widget gets part of the way there, but only supports swipe to dismiss; would it be possible to extend the widget, or have a new widget, that supports wipe actions?

**Comment by Hixie** [comment]
We could implement this in the framework, but I would recommend that `customer: gold` implement it directly. Using Dismissible as a guide for a new widget seems reasonable.

**Comment by letsar** [comment]
I implemented a widget for this: https://github.com/letsar/flutter_slidable.

- It supports the swipe in the two directions.
- It has 4 built-in animations, but you can customize your own.
- Any widget can be used has a slide action (but there are also 2 built-in actions that supports the tap gesture).

For now, it can't be dismissed but I will work on this.

If it's ok with the Flutter team, maybe I could do a PR to merge my widget into the Flutter codebase, after finishing the ongoing work?

**Comment by HansMuller** [comment]
I don't think the Material spec covers this particular pattern, maybe @willlarche can shed some light on that.

**Comment by willlarche** [comment]
Swiping is fine! We have had them in the past and should look at them for the future. Hans' discretion for whether to support.

**Comment by HansMuller** [comment]
@letsar -  https://github.com/letsar/flutter_slidable looks like a useful package, thanks for making it public! We'd prefer to let mature/grow as a separate package for a while, before considering making it part of Flutter.

**Comment by fryette** [comment]
@HansMuller seems that this package is died, because it has a lot of issues with no answer

**Comment by Hixie** [comment]
Closing as per conversation above. This is best done either bespoke in an application or in a package.
