### ISSUE TITLE
FirebaseMessaging - disableNetwork and enableNetwork

### ISSUE THREAD

**Issue by haidarmehsen** [flutter/flutter#143835]
### Use case

For my app, which completely relies on firebase fcm service to function, when the internet connection is intermittent, firebase messaging has a delay of couple of minutes to get to receive messages again, which makes my app completely useless.

I already asked a [question](https://stackoverflow.com/questions/77964208/flutter-app-not-receiving-notification-from-firebase-in-specific-cases) about this with no answers, and opened a [discussion](https://github.com/firebase/flutterfire/discussions/12360) about it in flutterfire repo, and searched alot for a way to force firebase to reconnect, but with no luck.

Currently the only solution I am facing is to change firebase fcm service and use another notifications provider, which is so bad because I will need to make alot of changes to my code on FE and BE.

It would be very nice if firebase had an option to force it to reconnect in this case.

- Note: my app is listening to firebase messages in the foreground, and the app is always on charger and screen is on and the app is always opened, so this is NOT A BACKGROUND MESSAGES ISSUE.

- Note : this request is similar to #21300 if I understand correctly

Thank you. 

### Proposal

- Enable a way to prompt firebase library to reconnect if the connection was gone then restored.

**Comment by dam-ease** [comment]
Hello @haidarmehsen 
This is a request/issue relating to `Firebase_messaging` and `Firebase_messaging` related issues should be reported in dedicated repo: https://github.com/firebase/flutterfire/issues.
Kindly file this issue there.
Closing from here as this isn't an issue with Flutter itself.
