### ISSUE TITLE
Clickable - for circle inside google maps

### ISSUE THREAD

**Issue by mabrar312** [flutter/flutter#143825]
### Steps to reproduce

1. Add Google maps widget.
2. Add Circle parameter and its details.
3. Try to add polygons dynamically by clicking
4. Inside the circle polygons or markers are getting created

### Expected results

# Flutter web.

On tap of inside or outside of the circle, irrespective of any place markers or polygons has to be created, I have already used customTapEvents and onTap but its not working.

I tried in javascript, inside circle a parameter called clickable is there value was set for false, which allows users to tap, so markers and polygons created in required place.

This feature is accessible in javascript. example link: https://jsfiddle.net/mabrar/0ryo9x45/

### Actual results

After creating circle, to that specific space iam trying to add marker or polygon its not working.
But outside the circle both marker and polygon is getting created. 

### Code sample

<details open><summary>Code sample</summary>

import 'package:bitsila/core/extensions.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class PantherGoogleMapsForPolygon extends StatefulWidget {
  const PantherGoogleMapsForPolygon({super.key});

  @override
  State<PantherGoogleMapsForPolygon> createState() =>
      _PantherGoogleMapsForPolygonState();
}

class _PantherGoogleMapsForPolygonState
    extends State<PantherGoogleMapsForPolygon> {
  GoogleMapController? googleMapController;
  List<LatLng> mapLatLngs = [];

  @override
  void dispose() {
    if (googleMapController != null) googleMapController!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: context.height / 1.25,
      child: GoogleMap(
        onMapCreated: (GoogleMapController mapController) {
          setState(() {
            googleMapController = mapController;
          });
        },
        onTap: (LatLng latLng) {
          setState(() {
            mapLatLngs.add(latLng);
          });
        },
        markers: {
          ...mapLatLngs
              .map(
                (e) => Marker(
                  markerId: MarkerId("$e"),
                  position: e,
                ),
              )
              .toSet()
        },
        polygons: {
          Polygon(
            polygonId: const PolygonId("each_polygon"),
            points: mapLatLngs,
            fillColor: context.secondaryColor.withOpacity(0.5),
            strokeColor: context.secondaryColor,
            strokeWidth: 3,
          )
        },
        circles: {
          Circle(
            strokeWidth: 3,
            strokeColor: context.secondaryColor,
            fillColor: context.secondaryColor.withOpacity(0.2),
            circleId: const CircleId("each_circle"),
            center: const LatLng(
              12.907008,
              77.5436652,
            ),
            radius: 1000.0,
            consumeTapEvents: true,
          )
        },
        initialCameraPosition: const CameraPosition(
          zoom: 16.0,
          target: LatLng(
            12.907008,
            77.5436652,
          ),
        ),
      ),
    );
  }
}

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Sample demonstration using HTML and javascript

HTML Code
<img width="580" alt="image" src="https://github.com/flutter/flutter/assets/138851831/8166e7f2-4487-4163-86db-ffc2387db300">

Javascript Code
<img width="569" alt="image" src="https://github.com/flutter/flutter/assets/138851831/ac15053c-8be6-489d-83ae-3c1c06674eaf">

Required Output
<img width="559" alt="image" src="https://github.com/flutter/flutter/assets/138851831/382875cb-5e80-4e98-b6f4-daa113e33060">

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.6, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

</details>

**Comment by dam-ease** [comment]
Hello @mabrar312.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code or a simple repo we can run to verify this?
Also, kindly include the output of your `flutter doctor -v`.
