### ISSUE TITLE
[CustomScrollView] Scroll performance issues

### ISSUE THREAD

**Issue by xyun52** [flutter/flutter#143920]
### Steps to reproduce

 Scroll content switching leads to a decrease in program performance

### Expected results

fast

### Actual results

slow

### Code sample

The test source code: [myapp.zip](https://github.com/flutter/flutter/files/14369914/myapp.zip)

### Screenshots or Video

![动画](https://github.com/flutter/flutter/assets/5417624/65629b64-991d-4f4a-a793-e788e316310e)

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):

```
[√] Flutter (Channel stable, 3.19.1, on Microsoft Windows [版本 10.0.22631.3155], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.86.2)
```

**Comment by dam-ease** [comment]
Hello @xyun52.
Thanks for filing this.
I tested this on the latest `master` and `stable` channels but can't seem to reproduce on the `master` channel.

https://github.com/flutter/flutter/assets/53122008/1b9c75ab-261e-41d7-8cb3-18ac0ff1ec49

Can you please check this video out to see if the slowness you are describing exists or if you are able to verify on the master channel as well?

**Comment by xyun52** [comment]
Your frequency is not enough. I started noticeably declining in performance around 7 times @dam-ease

**Comment by Dev2409** [comment]
> ### Steps to reproduce
> Scroll content switching leads to a decrease in program performance
> 
> ### Expected results
> fast
> 
> ### Actual results
> slow
> 
> ### Code sample
> The test source code: [myapp.zip](https://github.com/flutter/flutter/files/14369914/myapp.zip)
> 
> ### Screenshots or Video
> ![动画](https://private-user-images.githubusercontent.com/5417624/306890587-65629b64-991d-4f4a-a793-e788e316310e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTg1NTksIm5iZiI6MTcwODU5ODI1OSwicGF0aCI6Ii81NDE3NjI0LzMwNjg5MDU4Ny02NTYyOWI2NC05OTFkLTRmNGEtYTc5My1lNzg4ZTMxNjMxMGUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTAzNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ0ZmI5YTkyNmIyYmU4MjYzYjhiNjU5Mzc0NGUyNDIxZDA3ZTAyNGQ3M2FhYjIwMDIwYTRlN2RlNjEzMTUwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r14apBJG29hmG2oy4ppjS5oDDmIFNaq0SySbvTzTfN8) [ ![动画](https://private-user-images.githubusercontent.com/5417624/306890587-65629b64-991d-4f4a-a793-e788e316310e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTg1NTksIm5iZiI6MTcwODU5ODI1OSwicGF0aCI6Ii81NDE3NjI0LzMwNjg5MDU4Ny02NTYyOWI2NC05OTFkLTRmNGEtYTc5My1lNzg4ZTMxNjMxMGUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTAzNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ0ZmI5YTkyNmIyYmU4MjYzYjhiNjU5Mzc0NGUyNDIxZDA3ZTAyNGQ3M2FhYjIwMDIwYTRlN2RlNjEzMTUwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r14apBJG29hmG2oy4ppjS5oDDmIFNaq0SySbvTzTfN8) ](https://private-user-images.githubusercontent.com/5417624/306890587-65629b64-991d-4f4a-a793-e788e316310e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTg1NTksIm5iZiI6MTcwODU5ODI1OSwicGF0aCI6Ii81NDE3NjI0LzMwNjg5MDU4Ny02NTYyOWI2NC05OTFkLTRmNGEtYTc5My1lNzg4ZTMxNjMxMGUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTAzNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ0ZmI5YTkyNmIyYmU4MjYzYjhiNjU5Mzc0NGUyNDIxZDA3ZTAyNGQ3M2FhYjIwMDIwYTRlN2RlNjEzMTUwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r14apBJG29hmG2oy4ppjS5oDDmIFNaq0SySbvTzTfN8) [ ](https://private-user-images.githubusercontent.com/5417624/306890587-65629b64-991d-4f4a-a793-e788e316310e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTg1NTksIm5iZiI6MTcwODU5ODI1OSwicGF0aCI6Ii81NDE3NjI0LzMwNjg5MDU4Ny02NTYyOWI2NC05OTFkLTRmNGEtYTc5My1lNzg4ZTMxNjMxMGUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTAzNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ0ZmI5YTkyNmIyYmU4MjYzYjhiNjU5Mzc0NGUyNDIxZDA3ZTAyNGQ3M2FhYjIwMDIwYTRlN2RlNjEzMTUwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r14apBJG29hmG2oy4ppjS5oDDmIFNaq0SySbvTzTfN8)
> 
> ### Logs
> _No response_
> 
> ### Flutter Doctor output
> Doctor summary (to see all details, run flutter doctor -v):
> 
> ```
> [√] Flutter (Channel stable, 3.19.1, on Microsoft Windows [版本 10.0.22631.3155], locale zh-CN)
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> [√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [√] Chrome - develop for the web
> [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
> [√] Android Studio (version 2021.1)
> [√] VS Code (version 1.86.2)
> ```

Hey actuallly i have resolved performance issue

**Comment by Dev2409** [comment]
I fixed this issue but i am not able to generate pull request

**Comment by xyun52** [comment]
@dam-ease Not only scrolling, please note that the time for adding data to each frame is also getting longer and longer

**Comment by xyun52** [comment]
**The first click**
![1](https://github.com/flutter/flutter/assets/5417624/f499a4ea-2a42-44f0-9af7-9311355caa59)

**20th click**
![20](https://github.com/flutter/flutter/assets/5417624/2e4dc3bf-37c1-4669-b27f-e2cf058a81bb)

**Comment by xyun52** [comment]
This bug affects the entire app and the pop page cannot improve, so the webpage must be refreshed

**Comment by dam-ease** [comment]
Thanks for your responses @xyun52 @Dev2409.
I see that this occurs only after multiple clicks and can reproduce on my end as well after about 10+ times.
 

https://github.com/flutter/flutter/assets/53122008/f6377200-c5a2-4ca4-8ee9-21cfacb15243

> I fixed this issue but i am not able to generate pull request

@Dev2409 What issues are you facing with this?

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.19.1, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.19.1 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (2 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • Damilola’s iPhone (mobile) • 00008110-001964480AE1801E • ios            •
      iOS 17.1.1 21B91
    • macOS (desktop)            • macos                     • darwin-arm64   •
      macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)               • chrome                    • web-javascript •
      Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.20.0-11.0.pre.107, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.20.0-11.0.pre.107 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `flutter` on your path resolves to /Users/damilolaalimi/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fcd154bd24 (2 hours ago), 2024-02-22 20:24:21 -0800
    • Engine revision 0f3ad23b84
    • Dart version 3.4.0 (build 3.4.0-167.0.dev)
    • DevTools version 2.33.0-dev.11
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile)      • 00008110-001964480AE1801E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by Dev2409** [comment]
hey @dam-ease i am attaching the screen recording so can you please check is the issue resolved? 

https://github.com/flutter/flutter/assets/91386391/5ae464bb-5c21-4005-a915-3129581ab067

**Comment by xyun52** [comment]
@dam-ease SingleChildScrollView also has issues

**Comment by Piinks** [comment]
Can someone provide a code sample within this issue we can run to reproduce the issue?

**Comment by Piinks** [comment]
I downloaded the .zip file, but please refrain from providing code in this way in the future.

The issue here is that the CustomScrollView is full of SliverToBoxAdapters. This is not going to be performant as the children will not be laid out lazily. Instead, you could use a ListView.builder to build rows on demand, or more directly a SliverList of SliverFixedExtentList.

**Comment by xyun52** [comment]
This is not a scrolling performance issue caused by element height, it is a decrease in application performance caused by multiple switching of scrolling content @Piinks

**Comment by xyun52** [comment]
I created a new sample with automatic switching @Piinks 
[newdemo.zip](https://github.com/flutter/flutter/files/14429295/newdemo.zip)

![11](https://github.com/flutter/flutter/assets/5417624/dfb6115d-192c-458e-8dc1-933afc8af2ff)

**Comment by xyun52** [comment]
@dam-ease Can this problem be solved
