### ISSUE TITLE
Update `runIf`/`runIfNot` to `run_if`/`run_if_not` to be consistent across .ci.yaml

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#143958]
Most of variables in .ci.yaml have been using snake case fomat, but `runIf`/`runIfNot` were created as camel case. Nit to keep all variables consistent across all repos.

This also needs cocoon change to reference the correct name.

Related: https://github.com/flutter/flutter/issues/143671

**Comment by matanlurey** [comment]
This feature was removed.
