### ISSUE TITLE
Flutter driver is causing hinderance with connect on socket

### ISSUE THREAD

**Issue by sunnykarira-ms** [flutter/flutter#143930]
### Steps to reproduce
Platform: Linux - Ubuntu 20, Ubuntu 22
Architecture
Linux Flutter Application <-> FFI Bridge <-> C++ code

1. Create a tcp socket and try to set socket timeout on that socket using the operation setsockopt and finally connect on the socket.

2. Socket Type IPv4.
```C++
#Sample Snippet
setsockopt(s, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof(timeout)
ret = connect(s, (sockaddr*)&saddr, sizeof(saddr));
```

3. When I run the application in debug or release mode. I am correctly able to create socket and run the connection.
4. But when I run the application using flutter driver. The application errors out on the connect code point. The connect call returns an error.
```
 Error while os connect:  Interrupted system call
```
5. When I remove the setsockopt operation then everything from flutter driver works perfectly.
6. I am not able to understand how both of these scenarios are working differently. 

*Commands run in flutter drive.*
flutter drive --dart-entrypoint-args="" --target= --use-application-binary=  --device-id=linux  --debug --verbose

### Expected results

The application binary and flutter driver should produce same results.

### Actual results

The socket operation is not working in flutter driver but working in application binary when ran standalone.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on Ubuntu 22.04.3 LTS 6.5.0-17-generic,
    locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by mraleph** [comment]
> But when I run the application using flutter driver. The application errors out on this code point.

What does it mean "the application errors"? It crashes? The call returns an error? It the call returns an error - what error does it return, etc.

Please include as much information into your bug report as possible - otherwise it is next to impossible to help you.

**Comment by sunnykarira-ms** [comment]
@mraleph  I have updated the error

**Comment by dcharkes** [comment]
So if I understand this correctly, some native is not able to deal with the SIGPROF events our profiler sends, but some other native code is. So it's on a case by case basis. I wonder how often users run into this.

If it's often, we should consider automating blocking the profiling signal with an FFIgen option (when we generate C wrappers with native assets) or adding a bool argument to FFI calls.

(Unrelated to this issue, but also profiler related is that out FFI callbacks don't support profiling currently. https://github.com/dart-lang/sdk/issues/52814)
