### ISSUE TITLE
local_auth 2.2.0 did a breaking change so should have been 3.0.0

### ISSUE THREAD

**Issue by krispypen** [flutter/flutter#143942]
### What package does this bug report belong to?

local_auth

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Steps to reproduce

depending on local_auth: ^2.1.3
we use IOSAuthMessages from 'package:local_auth_ios/local_auth_ios.dart'
since yesterday 2.2.0 is released where IOSAuthMessages moved to another package

This should have been a breaking change

### Expected results

It should have been release 3.0.0

### Actual results

It does not compile anymore

### Code sample

<details open><summary>Code sample </summary>
This is taken from the readme:
```dart
import 'package:local_auth_android/local_auth_android.dart';
import 'package:local_auth_darwin/local_auth_ios.dart';
// ···
    final bool didAuthenticate = await auth.authenticate(
        localizedReason: 'Please authenticate to show account balance',
        authMessages: const <AuthMessages>[
          AndroidAuthMessages(
            signInTitle: 'Oops! Biometric authentication required!',
            cancelButton: 'No thanks',
          ),
          IOSAuthMessages(
            cancelButton: 'No thanks',
          ),
        ]);
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
  error • Target of URI doesn't exist: 'package:local_auth_ios/local_auth_ios.dart' • lib/some/package/biometrics_service.dart:10:8 • uri_does_not_exist
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.0 23A344 darwin-arm64, locale en-BE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by stuartmorgan** [comment]
> ```
> Target of URI doesn't exist: 'package:local_auth_ios/local_auth_ios.dart'
> ```

How does this URI not exist? `local_auth_ios` is still a package, it's just discontinued.

Were you `import`ing a package that you didn't have a `pubspec.yaml` dependency on, relying on the transitive dependency from another package?

**Comment by stuartmorgan** [comment]
For reference the governing semver rule is [this one](https://semver.org/spec/v2.0.0-rc.1.html#spec-item-9):

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.

The set of packages in the `dependencies` list of a package are not considered to be part of that package's public API.

**Comment by krispypen** [comment]
@stuartmorgan does that mean if someone wants to use local_auth with an AuthMessages config, that he also should include the local_auth_darwin or local_auth_ios dependency with a ^x.x.x version reference? Maybe something to add to the README file?
I thought all the [platform packages](https://github.com/flutter/packages/blob/main/packages/local_auth/local_auth/pubspec.yaml#L14C5-L14C14) where handled by pub so that's why I did not add it here.

**Comment by krispypen** [comment]
I'm did a test here, using version 2.2.0 and still using local_auth_ios iOSAuthMessage compiles but it doesn't work, which is even worse. it completely ignores the iOSAuthMessage from local_auth_ios

**Comment by darshankawar** [comment]
@krispypen 
Can you check the 2.2.0 [changelog](https://pub.dev/packages/local_auth/changelog#220) and see if it helps in your case ?

**Comment by krispypen** [comment]
@darshankawar it states indeed: 
`Clients directly importing local_auth_ios for auth strings should switch dependencies and imports to local_auth_darwin. No other change is necessary.`
But that is my point, it should have been a 3.0.0 version release because on a minor release you can't expect users to check the changelog

**Comment by stuartmorgan** [comment]
> it completely ignores the iOSAuthMessage from local_auth_ios

That should not be the case; I specifically tested for that before publishing the switchover (and I just re-tested from scratch) and I see the expected behavior, which is that a project that correctly depends on `local_auth_ios` and also still uses `local_auth_ios` in their Dart code will still pick up the strings. They should only be ignored if you are using a mix of `local_auth_ios` and `local_auth_darwin`.

Please provide:
- the exact Dart code you used,
- the exact pubspec, and
- the output of running `grep local_auth .dart_tool/flutter_build/dart_plugin_registrant.dart` in your project directory after building.

> But that is my point, it should have been a 3.0.0 version release because on a minor release you can't expect users to check the changelog

I did not expect users to check the changelog; that's why the entry says "should" not "must". Users whose projects were correctly configured (i.e., depended on `local_auth_ios` if they were `import`ing it) should continue to work without any changes.

**Comment by stuartmorgan** [comment]
> @stuartmorgan does that mean if someone wants to use local_auth with an AuthMessages config, that he also should include the local_auth_darwin or local_auth_ios dependency with a ^x.x.x version reference?

Yes. There is no circumstance in Flutter/Dart that I can think of where `import`ing a package that you do not depend directly on is a good idea.

> Maybe something to add to the README file?

I can file an issue to update the README to explicitly remind people to follow standard package usage practices here, sure.

> I thought all the [platform packages](https://github.com/flutter/packages/blob/main/packages/local_auth/local_auth/pubspec.yaml#L14C5-L14C14) where handled by pub so that's why I did not add it here.

I'm not sure what "handled by pub" means exactly. It is the case that it's possible to `import` things that you only have transitive dependencies on, but it's a bad idea as explained above.
