### ISSUE TITLE
`didPopRoute` doesn't get invoked when pressing back button.

### ISSUE THREAD

**Issue by hasanmhallak** [flutter/flutter#143925]
### Steps to reproduce

1. set `android:enableOnBackInvokedCallback="true"` in application tag in android manifest.
2. run the code provided belwo
3. press the button to navigate to Main Screen
4. try to press back or swipe.

### Expected results

the back event should be intercepted because flutter is actually getting the pop event. I made sure of that by setting the navigation handler using `SystemChannels.navigation.setMethodCallHandler`

### Actual results

`didPopRoute` is not getting invoked.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: TextButton(
          onPressed: () {
            Navigator.of(context)
                .push(MaterialPageRoute(builder: (_) => Main()));
          },
          child: Text('To Main Screen'),
        ),
      ),
    );
  }
}

class Main extends StatefulWidget {
  const Main({Key? key}) : super(key: key);
  @override
  State<Main> createState() => _MainState();
}

class _MainState extends State<Main> with WidgetsBindingObserver {
  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    super.initState();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Future<bool> didPopRoute() async {
    print('didPopRoute');
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: TextButton(
          onPressed: () {
            showAboutDialog(context: context);
          },
          child: Text('Show About Dialog'),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 13.5.2 22G91 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.86.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @hasanmhallak.
I can reproduce this on my end as well on the latest `master` and `stable` channels.
But from the [documentation](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didPopRoute.html).

> Not all system backs will result in a call to this method. Some are handled entirely by the system without informing the Flutter framework.

This might be WAI. Can you check this out if it helps provide more insights?

**Comment by hasanmhallak** [comment]
after a little bit of digging I think I understand why this is happening.  

The `MeterialApp` will create a `WidgetApp` that will register an Observer that will handle poping the route and returning true. And since observers are called in registration order, until one of the returns true. any new navigation observer will never be called.

**Comment by goderbauer** [comment]
This is intended behavior as documented:

> Observers are notified in registration order until one returns true.

from https://main-api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didPopRoute.html
