### ISSUE TITLE
Converting engine scenario run scripts to python or dart

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#143953]
### Use case

Currently, engine scenario tests are run through a bash script. I had to [add some logic](https://github.com/flutter/engine/pull/50835) to fix a bug.

@zanderso commented:
> My sense is that the logic in this script is outgrowing what we'd normally like to maintain in a bash script. We should consider porting this to Python, or ideally Dart if possible.
https://github.com/flutter/engine/pull/50835#pullrequestreview-1896463532

### Proposal

Instead of using a bash script to run the tests, use a python or dart script.

**Comment by matanlurey** [comment]
Fixed in https://github.com/flutter/engine/pull/53717, though we might revert and re-land due to https://github.com/flutter/flutter/issues/154956.
