### ISSUE TITLE
Replace method that expose dart to java wrapper classes with one that uses a dart object. 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#143955]
### What package does this bug report belong to?

in_app_purchase

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

As part of exposing alternative billing apis I (@reidbaker) exposed some internal wrapper classes. After landing the prs I realized the antipattern. 
Deprecate instances of AlternativeBillingOnlyReportingDetailsWrapper and BillingChoiceMode from in_app_purchase_android_platform_addition and replace them with versions that use pure dart objects without the json serialization logic. 

This bug does not cover BillingResultWrapper which is used in more than a few places and has existed as part of the api surface for a much longer time.

**Comment by gmackall** [comment]
@reidbaker should this be assigned to you?

**Comment by reidbaker** [comment]
This ended up being public for too long. The in_app_purchase_android implementation is converted to pigeon and there is a larger bug to get rid of all json serialization in the package after an appropriate amount of time.
