### ISSUE TITLE
Make it easier to diagnose invisible text with unspecified text style

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14399]
In a skeleton bare-bone app such as 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new Container(
      color: Colors.white,
      child: new WidgetsApp(
        color: Colors.red, // Doesn't matter
        onGenerateRoute: (RouteSettings settings) {
          return new PageRouteBuilder(
            pageBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
              return new Text('Hello World');
            },
          );
        })));
}
```

The text isn't visible because no TextStyle is specified and the font color defaults to white.

Perhaps enforce that a TextStyle must exist in the tree before using Text like TextDirection. 

Or add a debug overlay in Text when detecting that the text color is the same as the background like Flex's overflow overlay.

**Comment by xster** [comment]
Or we can make WidgetsApp.textStyle @required

**Comment by Hixie** [comment]
This is documented in several places. I think it makes sense to have a default text style otherwise the hello world app is going to start getting quite complex. If we have a default text style, then there will always be a background color where you can't see the text.

**Comment by mit-mit** [comment]
Or maybe move that text defaulting, and the standard routing (as in the MaterialApp) into a specialization of WidgetsApp (StandardApp?)?

**Comment by Hixie** [comment]
@mit-mit Not sure what you mean exactly. FWIW, MaterialApp does provide a default text style (red and yellow, to catch the case where you haven't used a Material, which itself has a default text style). It may make sense for us to have a CupertinoApp for the case where you want cupertino styles.

**Comment by Hixie** [comment]
debugPaintSizeEnabled will highlight the text box, maybe we could make RenderParagraph highlight text in debugPaint differently? Maybe add a shadow, or outline, or some such?

**Comment by Abdullah-Zakhoi** [comment]
@xster @Hixie @mit-mit @markusaksli-nc as @Hixie said it makes sense to have a default `backgroundColor` in`TextStyle` Class ... as `grey[500]` color !

**Comment by Abdullah-Zakhoi** [comment]
@xster @Hixie @mit-mit @markusaksli-nc what is the reason in this code `TextStyle ` has `black` color, and the background of the screen is `white` color when we use `MaterialApp` and `Scaffold`?
```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: new Container(
            child: Text(
              'Hello World',
            )),
      ),
    ),
  ));
}
```

**Comment by SaiSuvamPatnaik** [comment]
Hi, I have some initial idea on how to fix this issue, but I am unsure of where to make the changes. I am a beginner and I would like to work on this issue. @xster @Hixie @mit-mit @kf6gpe Kindly guide me on how to start working on this issue.

**Comment by Hixie** [comment]
@Abdullah-Zakhoi in that code the Scaffold is introducing a Material which sets a background color and text color to match Material Design guidelines.

@SaiSuvamPatnaik Ping me on the #hackers-new channel on our Discord (see our contributing guide for details) and I can help you out!

**Comment by gerryau** [comment]
Is this issue still open? It seems this is no longer an issue.

**Comment by Hixie** [comment]
Unfortunately in the years that this bug has been open we've not really found a good solution here. Fundamentally, if there's a default background color, it'll always be possible to set the text color to be the same, and if there's a default text color, it'll always be possible to set the background color to be the same. It's basically impossible to detect this case reliably, and it's not always a bug, so you can't really lint for it. We can't not have defaults without making the API less usable in general.

We've tried to make the defaults good, and Material tries to flag when you don't set a text style or forget a background. I think that may be as good as we can get. So I'm going to close this for now.

If anyone comes up with a concrete actionable solution here please don't hesitate to open a new bug for it!
