### ISSUE TITLE
Please provide version changelog

### ISSUE THREAD

**Issue by kjxbyz** [flutter/flutter#143914]
### Use case

Whether it is a major version, a minor version or a repaired version, please provide a changelog for each release. I will decide whether to upgrade the flutter version based on the changelog.

### Proposal

Whether it is a major version, a minor version or a repaired version, please provide a changelog for each release. I will decide whether to upgrade the flutter version based on the changelog.

**Comment by sejun2** [comment]
https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel
Is this page you expected ?

**Comment by kjxbyz** [comment]
> https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel Is this page you expected ?

Yes, I can view the changelog for the fixed version.
