### ISSUE TITLE
Docs confusion: is MaterialColor.primary a color index or a color value?

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#14393]
Creating a MaterialColor, and it's not clear from the documentation if I should use a color from the swatch as the primary value or if I should use the index of a color in the swatch as the primary value.

Can this be clarified?

**Comment by Hixie** [comment]
Does https://github.com/flutter/flutter/pull/14407 answer your question?

**Comment by DaveShuckerow** [comment]
Yes, that's clear.  Closing.
