### ISSUE TITLE
All arm64 windows bots in prod are offline

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#143948]
<img width="1188" alt="Screenshot 2024-02-22 at 9 21 30 AM" src="https://github.com/flutter/flutter/assets/54558023/9c136e3e-ab3e-4505-b8a9-903a6495fe43">

**Comment by godofredoc** [comment]
This can be related to the latest updates to vs_build dependency.

**Comment by yusuf-goog** [comment]
Looks like this could be the culprit: https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/flutter_deps/api.py;l=636

**Comment by yusuf-goog** [comment]
Most bots are recovered (logs in temp have been deleted).

**Comment by godofredoc** [comment]
Fix landed: https://flutter-review.googlesource.com/c/recipes/+/55460
