### ISSUE TITLE
[web] Drop console.print for `Flutter Web Bootstrap: Programmatic.`

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#143976]
`Flutter Web Bootstrap: Programmatic.`

We should avoid random things in the console unless it's helpful.
Maybe we should change this out to warn folks who are "doing it wrong" and point to docs to update to latest.

if `Flutter Web Bootstrap: Programmatic` is "the right thing to do" there is no upside in printing this for every (production) user!

**Comment by yjbanov** [comment]
I agree. When everything works normally, there should be zero output.

**Comment by yjbanov** [comment]
The code uses `debug` though: https://github.com/flutter/engine/blob/c5d2e011652b53fb89b38baeb4aba8ad1124f97e/lib/web_ui/lib/ui_web/src/ui_web/initialization.dart#L50

**Comment by kevmoo** [comment]
It's still noise. Maybe we only print it in debug mode?

**Comment by ditman** [comment]
The log only shows in the console if you've customized the log levels of the JS console. Should we fix things that only break for other misconfigurations of the browser? Like purposefully setting a wrong DNS? :P
