### ISSUE TITLE
flutter need  a  multi platform  nosql  local  database   written in dart

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#143906]
### Use case

As flutter is  multi platform we need a nosql  database  in dart  which can  support any platfrom  

### Proposal

Need a local nosql database  in pure dart  so that it support all platfrom

**Comment by danagbemava-nc** [comment]
There are several cross-platform local nosql databases on pub.dev that you can use today. Examples include hive, isar, sembast, objectbox. 

Some written in pure dart(isar, hive, sembast) and others that I may not know of. 

Given that there are already several community packages on pub that already do this, I'll be closing this issue. 

In the future, if you're looking for a package, please ask on stackoverflow or search pub.dev. 

Thank you
