### ISSUE TITLE
Only Moto G4 in staging  was taken offline last week, several tests not running since then

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#143915]
https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.staging/Linux_android%20platform_views_scroll_perf_impeller__timeline_summary?limit=400

@yusuf-goog Could you please give some notification when taking the only instance of a configuration offline for an extended period to give us some time to migrate?

**Comment by zanderso** [comment]
The issue about migrating devicelab away from Moto G4 is here https://github.com/flutter/flutter/issues/140893, but it is very far from being completed.

@yusuf-goog are there are any A02s devices in staging attached to Linux hosts for these tests to be migrated to?

**Comment by yusuf-goog** [comment]
Staging tasks typically shouldn't trigger P0 incidents. 

If these are critical tasks, we should move them in production or environments with comparable support.

**Comment by yusuf-goog** [comment]
The motoG4 testbed in `staging` has been restored.

Closing this issue for now, will follow up on the long term strategy for our pool allocations and usage.
