### ISSUE TITLE
New renderer on 18.2.0 of the Maps SDK for Google Maps flutter

### ISSUE THREAD

**Issue by sunilhari9** [flutter/flutter#143917]
Google says "To provide an improved user experience and app performance, apps built with the Maps SDK for Android will be automatically updated to the [latest renderer](https://notifications.google.com/g/p/ANiao5pxaNa-3BacL9wv-mQmeE4Ry2ywI78_BLUhv1NVJxU1Op3IKX9tZ1Q-lUCHezM9mh0g8YRvS2DflUyRFKpp7Y0BO-RQtuAV0hjdWUo5yi4jANRxnLe0NTaCcQsLTi05StxCMbjPEn2FBLR5gW1XCN8G2oEvujxFBoxg0UBC1cbSSe4uijE1Gd9HqlPKRR5WaxefgCiMlp5PDuVOpm3-6GJD_2xpZUAQdWEpv6Zq3ah3GCrMvH_BwZKlRYaP-lvnCA) beginning March 4, 2024. The legacy renderer is scheduled for decommissioning on March 3, 2025."

I have a list of my apps that are using google maps  so i would like to know if google_maps_flutter is prepared for this change and how can i change / test the new renderer.

What should we do if we are already using google_maps_flutter version 2.2.3.

**Comment by darshankawar** [comment]
@sunilhari9 
This seems to be already supported if I am not mistaken. https://github.com/flutter/flutter/issues/114004
Closing based on it. If you disagree, write in comments and I'll reopen it.

**Comment by darshankawar** [comment]
@sunilhari9 
The plugin already seems to be using the `18.2.0` version:

https://github.com/flutter/packages/blob/078c2a304a01b69c587e4d99a28812a907796b0f/packages/google_maps_flutter/google_maps_flutter_android/android/build.gradle#L43C9-L43C74
