### ISSUE TITLE
Tutorial: how to write your own mojom to access platform's APIs/services

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1439]
_From @sethladd on November 5, 2015 23:23_

Assuming there are some platform services that don't exist as pre-bundled mojoms/Dart wrappers, we could help new users understand how to build their own mojom to access platform capabilities.

_Copied from original issue: flutter/website#50_

**Comment by sethladd** [comment]
Looks like we don't need this one anymore, as we've moved away from Mojo and towards our own string/JSON-based message passing API.
