### ISSUE TITLE
Performance regression when supporting arbitrary shaped material

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#14403]
https://github.com/flutter/flutter/pull/14367 regressed some performance benchmarks.

The benchmarks that regressed are:
`complex_layout_scroll_perf__timeline_summary average_frame_rasterizer_time_millis` and `complex_layout_scroll_perf__timeline_summary missed_frame_rasterizer_budget_count`.

I suspect PhysicalShape is performing worse than PhysicalModel, both widgets are clipping and drawing shadows for a given outline, for PhysicalShape the outline is specified as a Path and for PhysicalModel it's specified as an RRect.

https://github.com/flutter/flutter/pull/14367 makes us always use PhysicalShape with a path that's specified by the same RRect that was previously passed to PhysicalModel. We did not expect a significant performance regression as Skia should know that the path is just a rounded rectangle.

Currently investigating.

**Comment by amirh** [comment]
It looks like the root cause is an optimization we have in PhysicalModel but not in PhysicalShape: in the non-compositing paint branch, if the shape is a rectangle PhysicalModel skips saveLayer (under the heuristic assumption that anti-aliasing on the edges is probably not needed). 

I'm going to add the same optimization to to PhysicalShape.

**Comment by amirh** [comment]
Further investigation shows that the root cause is the saveLayer done for the root canvas (Material with type Canvas).

Discussed this with @Hixie and we're going to fix this by not treating canvas material as a physical layer, conceptually canvas is infinite, so we won't be doing any clipping or elevation for canvas which will improve the performance (at the cost that misuse of canvas not as an infinite element will not work anymore).

**Comment by Hixie** [comment]
@amirh you landed this right?

**Comment by amirh** [comment]
not yet, waiting for https://github.com/flutter/flutter/pull/14447 to land
