### ISSUE TITLE
[web] Trying to use the project I built with flutter in an html css file

### ISSUE THREAD

**Issue by volkaankarakus** [flutter/flutter#144010]
### Done Before
I created Flutter Element Embedding without any problems by building the Flutter project with Flutter Build Web and opening a file called Flutter in a new HTML CSS project and copying the build files there.
The code I use here is as follows in index.html at <body> : 
```
<script>
        window.addEventListener("load", function(ev) {
            console.log("Flutter is ready");

            let target = document.querySelector("#flutter_target");
            // Download main.dart.js 
            _flutter.loader.loadEntrypoint({
                entrypointUrl: "/flutter/main.dart.js",
                onEntrypointLoaded: async function(engineInitializer) {
                    let appRunner = await engineInitializer.initializeEngine({
                        assetBase: "/flutter/",
                        hostElement: target,
                    });
                    await appRunner.runApp();
                },
            });
        });
    </script>
```

### Problem
What I'm trying to do now is to build the 1st project via firebase instead of copying these build files to the 2nd project and using the URLs from there. i.e. not copying files to the 2nd project.

Considering that the first project build site is https://stlylisttest.web.app/, the code here is as follows.
```
<script>
        window.addEventListener("load", function(ev) {
            console.log("Flutter is ready");

            let target = document.querySelector("#flutter_target");
            // Download main.dart.js 
            _flutter.loader.loadEntrypoint({
                entryPointUrl : 'https://stlylisttest.web.app/main.dart.js',
                // entrypointUrl: "/flutter/main.dart.js",
                onEntrypointLoaded: async function(engineInitializer) {
                    let appRunner = await engineInitializer.initializeEngine({
                        //assetBase: "/flutter/",
                        assetBase: "https://stlylisttest.web.app/",
                        hostElement: target,
                    });
                    await appRunner.runApp();
                },
            });
        });
    </script>
```

When I try to run this, I get a natural error like I cannot see _flutter in the website inspection because this time I did not copy the build/web file to this project. If anyone can handle this and explain step by step, I would be very happy, thank you in advance.

### Purpose 
The purpose here is not to integrate into a flutter project, but to integrate into an html,css project and  I don't want to use the first project like any chrome extension

**Comment by darshankawar** [comment]
@volkaankarakus 
I think your question / issue is better suited for support channels like StackOverflow, so please ask the same there.
Closing for now, as it looks like you are asking for support on your case instead of filing a bug or feature request.
