### ISSUE TITLE
Why does Flutter have its own widget set rather than exposing native widgets?

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1440]
_From @Hixie on November 6, 2015 17:29_

_Copied from original issue: flutter/website#58_

**Comment by FlutterIssues** [comment]
_From @abarth on November 7, 2015 3:47_

I presume you're asking for this to be included in the FAQ?

**Comment by FlutterIssues** [comment]
_From @Hixie on November 7, 2015 3:54_

Right. It was a question asked frequently in recent comment threads.

**Comment by eseidelGoogle** [comment]
Hopefully this addresses this?
https://flutter.io/faq/#why-does-flutter-not-use-the-host-platforms-native-widgets
