### ISSUE TITLE
Pull swarming data from build proto instead of build.infra.swarming

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#144062]
LUCI team is deprecating `build.infra.swarming`, and any logics referencing that proto should be refactored to use build proto instead.

The migration will occur EoQ1 2024, and we should finish refactoring our codes before that.

Recipes:
- [x] https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/recipe_testing/test_api.py#104
- [x] https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/swarming_retry/api.py#321

Cocoon:
https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/model/luci/buildbucket.dart#L618
/cc @ricardoamador Will the priority be switched to the new build proto with your buildbucket v2 migration?

**Comment by ricardoamador** [comment]
Yes. That buildbucket.dart class will be removed and everything will be using the build bucket v2 protos.

**Comment by ricardoamador** [comment]
I need to look back through the issues as there are maybe 4-5 other issues that will be closed when buildbucket v2 is live.

**Comment by keyonghan** [comment]
https://crrev.com/c/5325604 to try adding test data api support for our use case. But chromium team is taking over to land a fix. Will wait for that before moving forward.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/55580 to sync to the top of recipes-py.

**Comment by keyonghan** [comment]
Seems the support in https://crrev.com/c/5325899 is not enough, we will need `infra.backend.task` support in the test data. We flutter side has a bunch logics to reference `infra.swarming.task_id`, which needs the test data support to pass our test train.

**Comment by keyonghan** [comment]
With https://crrev.com/c/5341803 from upstream, http://go/flutter-cl/55740 supports both logics during the migration.

Once LUCI finished migration, the remaining work here is clean up old logics.

**Comment by keyonghan** [comment]
http://go/flutter-cl/55740  caused https://github.com/flutter/flutter/issues/144587.
A reland happened via https://flutter-review.googlesource.com/c/recipes/+/55840.
Keep this bug open to track old logic clean up when LUCI finishes migration.

**Comment by keyonghan** [comment]
This is done with https://flutter-review.googlesource.com/c/recipes/+/57080
