### ISSUE TITLE
Should add dialog `barrierColor` into ThemeData

### ISSUE THREAD

**Issue by crizant** [flutter/flutter#144005]
### Use case

Currently, if we want to customize the backdrop color for dialogs or bottom sheets, we need to use the `barrierColor` property in the `showDialog` or `showModalBottomSheet`.
It is error-prone when we have to add it in every dialog and bottom sheet.,

### Proposal

We should add the `barrierColor` into `ThemeData`, and then apply it inside the `showDialog` function automatically.

**Comment by danagbemava-nc** [comment]
Hi @crizant, this has now been added to the `DialogTheme` in https://github.com/flutter/flutter/pull/142490. The original issue was https://github.com/flutter/flutter/issues/142489.

I'll be closing this since this feature has already been added. 

Thank you
