### ISSUE TITLE
Add a `--repeat` flag to `run_android_tests.dart` for flake checks

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144054]
Maybe we can delegate this down to `adb shell` or the Android test runner itself, that would be preferable.

**Comment by reidbaker** [comment]
I dont think adb has this built in. 
https://stackoverflow.com/questions/47828662/adb-shell-command-to-execute-repeatedly-every-x-interval

On my mac I use "watch" https://formulae.brew.sh/formula/watch

**Comment by matanlurey** [comment]
Hmm, maybe there is a way I could configure `AndroidJUnitRunner`:

https://github.com/flutter/engine/blob/bdfedde80b55606967af49cf46e05c45699df6f6/testing/scenario_app/android/app/src/androidTest/java/dev/flutter/TestRunner.java

**Comment by matanlurey** [comment]
Note I tried doing a naive version of this, and it's quite complicated:

- You'd want a single failure not to be eager (today if 1 out of 68 tests fail, the tool panics)
- You'd want to capture multiple processes (the tool assumes a single launched process)
- Screenshots have no understanding of comparison across runs, making golden tests less useful
