### ISSUE TITLE
Package not available (authorization failed) 

### ISSUE THREAD

**Issue by kpushkar10** [flutter/flutter#144082]
When I was running `flutter pub add google_fonts`, I encountered the following error

flutter pub get --no-example
Resolving dependencies...
Package not available (authorization failed).
exit code 69
![image](https://github.com/flutter/flutter/assets/78405381/ac771b11-c4e2-464f-996e-e610316f21cb)

I am unable to get any packages

**Comment by huycozy** [comment]
Hi @kpushkar10 
I'm unable to reproduce the issue. This looks similar to https://github.com/flutter/flutter/issues/129518. Do you use VPN on your machine? 

Could you share the output of the command with verbose (`flutter pub add google_fonts -v`)? Please also share output of `flutter doctor -v` as well. Thanks!
