### ISSUE TITLE
Upgrade Phase 4 for iOS 17

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#144021]
Blocked by:
- [x] https://github.com/flutter/flutter/issues/143003

----

Upgrade all remaining devicelab iOS devices to iOS 17:

- [x] [flutter-devicelab-mac-12](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-12)
- [x] [flutter-devicelab-mac-14](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-14)
- [x] [flutter-devicelab-mac-46](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-46)
- [x] [flutter-devicelab-mac-30](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-30)
- [x] [flutter-devicelab-mac-43](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-43)
- [x] [flutter-devicelab-mac-44](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-44)

---

**Please quarantine the bot before upgrading.**

Steps after upgraded to iOS 17 on iPhone devices.

* Open Xcode 15 from /opt/flutter/xcode/15a240d/XCode.app
* In the top bar, open Window > Device and Simulators
* The window that opens should show the connected device
* Accept the Trust dialog on the iPhone device
* If you get the dialog on the device twice, you may need to accept it once, disconnect, reconnect, and accept again.
* Wait for the yellow bar at the top of the Device and Simulators window to go away - It should take a minute or so to Copy cache symbols

Once all steps above are complete, the device can be taken out of quarantine.

**Comment by kentnguyen99** [comment]
@vashworth After upgrading iOS to version 17 on the phone device, machine could not pairing with iPhone device from Xcode App and got error that Xcode App need to be version 15.xx or more.  I don't see a "Update" button on Xcode App. Is there a way we can download Xcode App v15.3 from website and install manually?

**Comment by vashworth** [comment]
> @vashworth After upgrading iOS to version 17 on the phone device, machine could not pairing with iPhone device from Xcode App and got error that Xcode App need to be version 15.xx or more. I don't see a "Update" button on Xcode App. Is there a way we can download Xcode App v15.3 from website and install manually?

Did you open the Xcode app from `/opt/flutter/xcode/15a240d/XCode.app`?

**Comment by vashworth** [comment]
Verified all bots are working. Thanks!
