### ISSUE TITLE
Incompatible modules in windows

### ISSUE THREAD

**Issue by Mapashito1** [flutter/flutter#144007]
### Steps to reproduce

When you compile in windows, If you use differents modules but in this modules has same variable name, I think cmake mixs variables.

I've opened a case with more details 
https://github.com/ScerIO/packages.flutter/issues/490

### Expected results

If I set variable in cmakelist.txt, the variable must be isolated

### Actual results

When you launch a windows compile with a specific modules than shares variable name, the result will be indeterminate 

### Code sample

<details open><summary>Code sample</summary>

Only copy two modules than shares variable name in your pubspec.yaml and launch a windows compilation.

For example:
printing: ^5.11.1
pdfx: ^2.6.0
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Cmakelist.txt from pdfx module set PDFIUM_VERSION to 4634

![image](https://github.com/flutter/flutter/assets/79135697/f52d7bf6-9180-4c8b-8fc9-de4c463168ff)

Cmakelist.txt from printing module set PDFIUM_VERSION to 5200 but If I print value, It's 4634 when I compile it

![image](https://github.com/flutter/flutter/assets/79135697/aba6e55a-c62a-497e-a10e-a30f084ed224)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Versi¢n 10.0.22621.3155], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.1)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.86.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment]
That's how `CACHE` works in CMake; if the package authors don't want the variable to be global and this have the behavior described here, they didn't be using `CACHE`. If they do want to declare a global variable, it's up to them to pick something unique (e.g., starting with the package name).

Closing as this is up to the audits of packages to resolve, so you'll need to report it to them.
