### ISSUE TITLE
Flutter doesn't support Motorola Android 10

### ISSUE THREAD

**Issue by LJNeon** [flutter/flutter#144096]
### Steps to reproduce

1. Get a Motorola phone with Android 10.
2. Try to install an app that uses Flutter.

### Expected results

The app should install successfully once the unknown apks permission is granted.

### Actual results

The app isn't installed and leaves you with a vague failure message.

### Code sample

<details open><summary>Code sample</summary>
N/A
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20240224-192911](https://github.com/flutter/flutter/assets/23249107/679fd94d-ef82-42e2-8f9b-031b6ce0465b)

![Screenshot_20240224-193020](https://github.com/flutter/flutter/assets/23249107/750f6268-476c-4853-8c8b-83540614e403)

![Screenshot_20240224-193151](https://github.com/flutter/flutter/assets/23249107/cd906324-2698-4dd6-8c1d-ad71354ff3ae)

![Screenshot_20240224-193223](https://github.com/flutter/flutter/assets/23249107/48d9bb7a-2037-4973-8f32-8e2544ed5459)

![Screenshot_20240224-193401](https://github.com/flutter/flutter/assets/23249107/7837da5d-d2a8-4757-b3ed-8c62631bed7a)

![Screenshot_20240224-193438](https://github.com/flutter/flutter/assets/23249107/7dc94d4c-7667-4e0a-85fd-c9b113d13caa)

![Screenshot_20240224-193612](https://github.com/flutter/flutter/assets/23249107/a553b7ca-5f3d-4d5f-a9e7-9d5fa1955587)

![Screenshot_20240224-193649](https://github.com/flutter/flutter/assets/23249107/8ebaa544-dec2-4498-ae77-c11fcf34ed8a)

</details>

### Logs

<details open><summary>Logs</summary>
N/A
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>
N/A
</details>

**Comment by LJNeon** [comment]
To give further details that didn't fit into the issue template, I tried to install two apps that use flutter ([Obtainium](https://github.com/ImranR98/Obtainium) & [Aves Libre](https://github.com/deckerst/aves/tree/v1.10.5)) and then tried to install two apps that don't use flutter ([Aegis](https://github.com/beemdevelopment/Aegis) & [Another Widget](https://github.com/azuo/another-widget)) as a control. Only the apps that use flutter failed, as the screenshots above show.

**Comment by iapicca** [comment]
> 1. Get a Motorola phone with Android 10.

"a" motorola phone with android 10 seems a bit vague,
on what device you encountered the issue

> 2. Try to install an app that uses Flutter.
> [...] I tried to install two apps that use flutter ([Obtainium](https://github.com/ImranR98/Obtainium) & [Aves Libre](https://github.com/deckerst/aves/tree/v1.10.5))  [...]

maybe is not flutter's fault but those apps' fault
can you try installing [wonderous](https://flutter.gskinner.com/wonderous/)

**Comment by LJNeon** [comment]
Both of those successfully installed, so I went back and tried out every single APK until one worked. Apparently I was downloading the wrong APK (`app-arm64-v8a-release.apk`) and another one worked (`app-release.apk`). I am quite sure my CPU has the arm64 architecture (it's a Qualcomm Snapdragon 632) so I don't really understand why it didn't work, but either way it wasn't an issue with flutter.
