### ISSUE TITLE
Move Android-specific tooling for `scenario_app` into `tools/`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144051]
This would allow `scenario_app`'s Dart code to be 100% platform agnostic/only related to `dart:ui`.

Perhaps `run_android_tests` as a package/tool name is sufficient. I wonder if we could also de-duplicate some of the test runner code we have repository-wide, for example [`android_systrace_test.py`](https://github.com/flutter/engine/blob/main/testing/android_systrace_test.py).

Any thoughts @dnfield @gaaclarke?

**Comment by reidbaker** [comment]
Is this related to the `et` work.

**Comment by matanlurey** [comment]
Ah, good question. No. That being said, I've re-evaluated this and don't think it's very useful for the time being.

If we end up wanting _other_ test beds that boot emulators (/cc @chinmaygarde) we should definitely consider moving the test-agnostic pieces of the tool to somewhere common, but I guess that's orthogonal. Closing!
