### ISSUE TITLE
[flutter_tools] Deprecate renderFrameWithRasterStats feature

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#144191]
The statistics from this feature are not reliable enough to currently recommend it broadly for users, and it is unclear how to make it more reliable. In addition, support was never implemented for the Impeller backend. Thus, we should deprecate it.

**Comment by christopherfujino** [comment]
FYI @kenzieschmoll, please feel free to correct me if I've made any mistake, I based this on a conversation with Jonah.

**Comment by kenzieschmoll** [comment]
Is this feature completely broken for SKIA? In DevTools, the Raster stats feature is disabled if an app is running with Impeller, but the tool is enabled for SKIA.
