### ISSUE TITLE
Both ink wells react when they are nested inside each other

### ISSUE THREAD

**Issue by gnawf** [flutter/flutter#14417]
Internal: b/151678927

Pictured: two ink wells, one for the card, and one for the smaller rectangular widget at the center of the card. The smaller rectangular widget has been tapped. The current Flutter behavior is on pictured to the left, the ideal behavior is pictured to the right.

In Android, by default, ancestors do not respond/ripple when a descendant responds/ripples i.e. it follows the ideal behavior pictured to the right.

Reasoning: say the descendant is a button, it does not make sense for the ancestor to ripple as tapping the button will not activate the `onTap` for the ancestor.

<img src="https://user-images.githubusercontent.com/9077461/35674273-025e943e-07a9-11e8-80a0-df31f6367b02.png" width=240/> <img src="https://user-images.githubusercontent.com/9077461/35674276-03731c32-07a9-11e8-89e4-af0e62550d9b.png" width=240/>

## Steps to Reproduce

Run the sample code below, click the center of the card and two ripples will be generated for both ink response widgets. The ideal situation can be replicated by setting the ancestor `InkWell.onTap` to null, as annotated in the code.

```dart
import "package:flutter/material.dart";

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text("Bug"),
        ),
        body: new Card(
          child: new Container(
            height: 100.0,
            child: new InkWell(
              onTap: () => print("Set this onTap to null for ideal behavior"),
              child: new Center(
                child: new InkWell(
                  onTap: () {},
                  child: new Container(
                    width: 50.0,
                    height: 50.0,
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

## Logs

Running flutter run and flutter analyze did not output anything.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-NZ, channel unknown)
    • Flutter at /Users/gnawf/flutter
    • Framework revision 6a42ed3f55 (3 weeks ago), 2018-01-12 15:12:26 -0800
    • Engine revision 05fe72d068
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.28757928b47b192efcec082c78258102beb03f78

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /usr/local/opt/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk/
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Your Mac needs to enabled for developer mode before using Xcode for the first time.
      Run 'sudo DevToolsSecurity -enable' to enable developer mode.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.3.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[✓] Connected devices
    • iPhone 8 • 533B1ADF-56E5-4A63-9319-1F704E8845E0 • ios • iOS 11.2 (simulator)
```

**Comment by Hixie** [comment]
What's going on here is that both ink wells are fighting for the pointer in the arena, and during the fight they show their reactions. When one wins, the other will get canceled.

We don't have an easy way today for the outer InkWell to know that it's fighting with another InkWell for the same gesture.

**Comment by sir-boformer** [comment]
For me this is a common problem

**Comment by sir-boformer** [comment]
As a quick fix, set a `onHighlightChanged` listener on the inner `InkWell` that sets some kind of boolean value (`innerButtonPressed`) in the enclosing stateful widget.

set the `onPressed` listener of the outer `InkWell` to `null` while the boolean value is `true` to disable it while the inner `InkWell` is pressed.

**Comment by xckevin** [comment]
i final fix it  in this way:

```
InkWell(
    GestureDetector(
        excludeFromSemantics: true,
        child: xxx
    )
)
```

**Comment by sergeymild** [comment]
I have the same problem. Is it will be fixed?

**Comment by audkar** [comment]
This is very noticeable visual bug. Especially when bold/vibrant colors are used for applications theme.

**Comment by Hixie** [comment]
`excludeFromSemantics: true` shouldn't affect this (if it does, please file a bug), though it will hurt accessibility, so is highly discouraged.
The workaround suggested by @sir-boformer should work.

**Comment by sergeymild** [comment]
yes, it is works, but it still a workaround. What about fix it?

**Comment by Nico04** [comment]
Same for me, with an IconButton inside an InkWell...

**Comment by Hixie** [comment]
One way to solve this specifically for ink wells would be for an ink well to put an inherited widget in the tree to communicate to any nested ink wells.
Another way would be to bubble up a notification and listen for it. That's probably better as it would be easy to reuse.

**Comment by deadsoul44** [comment]
It has been two years...

**Comment by dkwingsmt** [comment]
What do you think if we limit one instance of the same class of gesture recognizer in the arena? In this way the child's recognizer will be added first, and the parent's will be rejected instantly, whose `didExceedDeadling` will be prevented. This method is also compatible with the current strategy, since there's only one victor anyway, and the same type of recognizer will always win or lose together, unless they do some tricky stuff.

**Comment by Hixie** [comment]
> unless they do some tricky stuff.

It doesn't have to be that tricky. For example, a gesture recognizer could be configurable. At some point we need to make a recognizer that's aware of the boundary of the render object that it's working with, so that taps can slop up to the edge of their button region. In that world, a tall rectangle that overlaps a wide rectangle would give the tall one the win if the user drags up and the wide one if they drag left, regardless of which one is the parent and which is the child.

**Comment by iKrupp** [comment]
I ran into this problem and it looks sad enough. You can take a workaround and push everything onto the stack, but it’s not very convenient

**Comment by vguzzi** [comment]
> I ran into this problem and it looks sad enough. You can take a workaround and push everything onto the stack, but it’s not very convenient

Can you clarify your workaround?

**Comment by mehmetf** [comment]
The `Stack` workaround falls short if there are other widgets that need to be included in the layout that receives the outer inkwell tap. For instance:

```dart
       Card(
          child: Stack(
            children: [
              Positioned.fill(
                child: InkWell(
                  onTap: () => null,
                ),
              ),
              Container(
                width: 240,
                height: 180,
                child: Column(
                  children: [
                    Text(
                      'Some text',
                      style: Theme.of(context).textTheme.headline3,
                    ),
                    InputChip(
                      onPressed: () => null,
                      label: const Text('Tap'),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
```

In this instance, we want the Inkwell at the bottom to be triggered when we click `Some text` whereas we don't want the Inkwell to be triggered when we click the InputChip.

We can't move `Some Text` out of the top stack layer since it needs to participate in the same layout as the InputChip.

The workaround posted for disabling the outer onTap handler would work but requires creation of a new pattern and thus a significant update to application code.

Any other ideas? I would love it if we had the opposite of `IgnorePointer` where the child widget can dictate that it is blocking every gesture from bubbling up.

**Comment by mehmetf** [comment]
This has become a critical issue for customer: money.

**Comment by Hixie** [comment]
@dkwingsmt based on the discussion above, the best way to solve this is probably to bubble up a notification from InkResponse and for InkResponse to listen for notifications from its children. If it gets one, it can know that it should just stay idle. Or something like that. There are other ideas earlier in this bug if that doesn't work.
