### ISSUE TITLE
`ImageReaderSurfaceProducer` renders incorrectly

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144199]
Caught by https://github.com/flutter/engine/pull/50993, which I am reverting.

I _think_ this code is intended to be virtually unused, though if an end-user tried it (it's available in `stable`) it would render incorrectly. Marking as a P1 because this will block @dnfield's work to enable Impeller on `scenario_app` (since we need `ImageReaderSurfaceProducer`).

See https://flutter-engine-gold.skia.org/search?crs=github&issue=50993&negative=true&patchsets=2&untriaged=false.

## ExternalTextureTests_testRotatedMediaSurface_180

<details>

<summary>Not rotated as expected</summary>

![image](https://github.com/flutter/flutter/assets/168174/355992c4-1f11-49a6-90f8-05125d4f0761)

</details>

Similar for:

- ExternalTextureTests_testRotatedMediaSurface_270
- ExternalTextureTests_testRotatedMediaSurface_90
- ExternalTextureTests_testCroppedRotatedMediaSurface_bottomLeft_90
- ExternalTextureTests_testCroppedMediaSurface_topRight
- ExternalTextureTests_testCroppedRotatedMediaSurface_bottomLeft_90
- ExternalTextureTests_testCroppedMediaSurface_bottomLeft

**Comment by matanlurey** [comment]
Oh and for clarification, I think `MediaSurface` is intended to be emulate the `video_player` plugin:

![Screenshot 2024-02-26 at 5 57 41 PM](https://github.com/flutter/flutter/assets/168174/1276a659-568d-401e-ab39-28e776efd883)

**Comment by chinmaygarde** [comment]
Took a cursory look a the implementation and it seems like `ImageSurfaceRenderer` and `MediaSurfaceRenderer` don't handle the same bundle extras. The former reads the "crop" which the latter ignores and the latter reads the "rotation" which the former ignores. Really not sure what the test is trying to do.

**Comment by matanlurey** [comment]
> Took a cursory look a the implementation and it seems like `ImageSurfaceRenderer` and `MediaSurfaceRenderer` don't handle the same bundle extras. The former reads the "crop" which the latter ignores and the latter reads the "rotation" which the former ignores. Really not sure what the test is trying to do.

I admit I haven't dove into the implementations on the test site, but they _do_ work on the Skia backend.

**Comment by chinmaygarde** [comment]
If the Skia backend goes down the ImageReader path, I observe the broken
behavior.

**Comment by matanlurey** [comment]
Hmm that's good to know! Ok so maybe this is a wild 🦆 chase and the implementation is flawed.

Let me work on the test fixtures and see if I can make them make sense.

/cc @johnmccutchan ^

**Comment by matanlurey** [comment]
Sorry I confused myself - @chinmaygarde you're right Skia + ImageReader branch is also broken, that's why https://github.com/flutter/engine/pull/50995 occurred. https://github.com/flutter/flutter/issues/144199 is borked on both Skia + Impeller when we use ImageReader, and this issue needs to get fixed (it's not a scenario_app test fixture bug, at least not AFAICT).

**Comment by matanlurey** [comment]
Duplicate of https://github.com/flutter/flutter/issues/144407, and we'll no longer be doing it.
