### ISSUE TITLE
Platform.script is returning a bad (non existent) file

### ISSUE THREAD

**Issue by busslina** [flutter/flutter#144168]
Migrated from [Dart repository](https://github.com/dart-lang/sdk/issues/55004) to Flutter repository.

### Steps to reproduce

```dart
static void testDir() {
    final scriptFile = File(Platform.script.path);

    debug('Script path: ${scriptFile.path}');
    debug('Exists: ${scriptFile.existsSync()}');
  }
```

### Expected results

```
/C:/Users/bussl/workspace/FLUTTER/website-manager/lib/main_windows.dart
```

### Actual results

```
/C:/Users/bussl/workspace/FLUTTER/website-manager/main.dart
```

### Screenshots or Video

[weird-script-file.webm](https://github.com/dart-lang/sdk/assets/73592852/2223cd0c-35a0-45ba-9a24-94d5dc8ff48c)

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Versi¢n 10.0.19045.4046], locale es-ES)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by huycozy** [comment]
I can see this issue on some platforms:

### macOS: 
```console
flutter: Script path: /Users/huynq/Library/Containers/DE235B62-7E44-4D1E-836A-2CD5B52258F4/Data/main.dart
flutter: Exists: false
```

### Android:
```console
I/flutter (28758): Script path: /main.dart
I/flutter (28758): Exists: false
```

But I see there is a similar issue at https://github.com/flutter/flutter/issues/137638. Closing this issue in favor of that one, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
