### ISSUE TITLE
[Impeller] Determine whether framebuffer fetch via subpasses will be supported in the GLES backend

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#144181]
The framebuffer fetch implementation was extended in https://github.com/flutter/engine/commit/f4fbabf1eb9f85289578a49e5373d3240fd6e77e and now relies on capabilities that are not supported in the Impeller OpenGL ES back end.

For example, running `RendererTest.CanSepiaToneWithSubpasses` fails on GLES because the resulting shader requires a `sampler2DMS` that is not supported on a `#version 100` shader.

If supporting this on GLES is not feasible, then we may need to change the capabilities to reflect that GLES does not match Vulkan/Metal's level of support for framebuffer fetch.

**Comment by jonahwilliams** [comment]
We don't need to support more than one input attachment, and we should read the capabilities check as designed for the entity renderer.

**Comment by chinmaygarde** [comment]
I've re-enabled the tests in the linked PR. Fetch using the extension on GLES is working fine.
