### ISSUE TITLE
[google_maps_flutter] Add AdvancedMarkerElement to resolve deprecation

### ISSUE THREAD

**Issue by darkfrog26** [flutter/flutter#144151]
### Use case

Getting this message when I build my project now:
```
As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. Please see https://developers.google.com/maps/deprecations for deprecation details.
```

### Proposal

Needs to be resolved in `google_maps`

**Comment by danagbemava-nc** [comment]
Hi @darkfrog26, what version of google_maps_flutter are you experiencing this with? And what platform(s) are you seeing this issue on?

**Comment by Niko-by** [comment]
I have the same. Flutter Web.

google_maps_flutter: ^2.6.0
google_maps_flutter_web: ^0.5.6+1

**Comment by Gustavoaz** [comment]
I have the same issue on flutter web

google_maps_flutter: ^2.6.0
google_maps_flutter_web: ^0.5.6+2

**Comment by Fakerinc** [comment]
same here

**Comment by NeoZ3p** [comment]
same here

**Comment by billybogz** [comment]
same here

**Comment by WieFel** [comment]
+1

**Comment by Imma76** [comment]
+1

**Comment by Sasha071201** [comment]
+1

**Comment by heberth2788** [comment]
Same here ! hahaha... Any solution ?

**Comment by ditman** [comment]
Duplicate of: https://github.com/flutter/flutter/issues/130472
