### ISSUE TITLE
Showing black screen when app reopen after minimised 

### ISSUE THREAD

**Issue by mhdshuhaib1704** [flutter/flutter#144133]
### Steps to reproduce

1. Open the application
2. Minimise app
3. Reopen after some time

### Expected results

Im expecting app need to view the UI screen instead of black screen

### Actual results

A black screen 

### Code sample

<details open><summary>Code sample</summary>

```dart
import android.view.View
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    override fun onStart() {
        super.onStart()
        window.decorView.visibility = View.VISIBLE
    }

    override fun onStop() {
        window.decorView.visibility = View.GONE
        super.onStop()
    }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.10.0, on macOS 12.6.6 21G646 darwin-arm64, locale en-GB)
    ! Flutter version 3.10.0 on channel unknown at /Users/odoxsofthub/Developer/flutter/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hello @mhdshuhaib1704.
Thanks for filing this.
I see you are on an older version of Flutter, please can you upgrade to the latest version `3.19.1` to verify this still reproduces on your end?
If it does, kindly provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you
