### ISSUE TITLE
googleSignInAuthentication.idToken is null

### ISSUE THREAD

**Issue by subhadiprudra** [flutter/flutter#144167]
### Steps to reproduce

 GoogleSignInAuthentication googleSignInAuthentication =
            await googleSignInAccount.authentication;
        code = googleSignInAuthentication.idToken;

### Actual results

In android after login I can see the email address but idToken is coming null. Please help me to fix it.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

subhadiprudra@Subhadips-MacBook-Air ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1 23B74 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] VS Code (version 1.87.0-insider)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!


```

</details>

**Comment by danagbemava-nc** [comment]
Hi @subhadiprudra, can you try https://github.com/flutter/flutter/issues/20903#issuecomment-1735878336 to see if it works for you?
