### ISSUE TITLE
Opening a flutter modal over a screen that contains an animated lottie makes the modal transparent. Flutter version 3.19.1

### ISSUE THREAD

**Issue by spiderion** [flutter/flutter#144189]
### Steps to reproduce

Create a page with a lottie
Open a modal on the top of that page
You will still be able to see the lottie animation in background as the modal looks trasparent

### Expected results

The modal should cover the widgets in the background

### Actual results

The modal is transparent over the lottie animation

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @spiderion, what platform(s) are you seeing this issue on? Was this an issue piror to flutter 3.19.1 or did it manifest on 3.19? 

Please also provide a complete minimal reproducible code sample so that we can investigate this issue. 

Thank you

**Comment by spiderion** [comment]
Hi @danagbemava-nc, I am only seeing this issue on IOS. No, I was not facing the issue on 3.16.9.
I don't know if can create a specific minimal code to reproduce it but please if you can't manage to reproduce I will try to make the effort.
I am now using a previous version of Flutter as this is a bug that I can't push live to my users.
Thanks.

**Comment by danagbemava-nc** [comment]
Hi @spiderion, using the lottie example app and the showDialog method, I can't seem to reproduce the issue. See the recording below. 

We would appreciate if you could provide a complete minimal reproducible code sample so that we can investigate this issue. 

Thank you

https://github.com/flutter/flutter/assets/88313112/d951c0ea-e023-4b69-acc3-88af2924f813


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeWidget(),
    );
  }
}

class HomeWidget extends StatelessWidget {
  const HomeWidget({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Lottie.network(
          'https://raw.githubusercontent.com/xvrh/lottie-flutter/master/example/assets/Mobilo/A.json',
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          showDialog<void>(
            context: context,
            builder: (BuildContext context) {
              return AlertDialog(
                title: const Text('Basic dialog title'),
                content: const Text(
                  'A dialog is a type of modal window that\n'
                  'appears in front of app content to\n'
                  'provide critical information, or prompt\n'
                  'for a decision to be made.',
                ),
                actions: <Widget>[
                  TextButton(
                    style: TextButton.styleFrom(
                      textStyle: Theme.of(context).textTheme.labelLarge,
                    ),
                    child: const Text('Disable'),
                    onPressed: () {
                      Navigator.of(context).pop();
                    },
                  ),
                  TextButton(
                    style: TextButton.styleFrom(
                      textStyle: Theme.of(context).textTheme.labelLarge,
                    ),
                    child: const Text('Enable'),
                    onPressed: () {
                      Navigator.of(context).pop();
                    },
                  ),
                ],
              );
            },
          );
        },
      ),
    );
  }
}
```
</details>

**Comment by spiderion** [comment]
Hi @danagbemava-nc , Thanks for the effort to try to reproduce the issue.
I was referring to a showModalBottomSheet 
I will try to create a code so you can reproduce asap. 
Thanks

**Comment by spiderion** [comment]
Hi Again, In the meantime that I  am creating the reproducible code I would like to show a video of the issue.

https://github.com/flutter/flutter/assets/36972396/89e61f34-55cf-4a0d-9efe-70c9827a7f8f

**Comment by spiderion** [comment]
Hi @danagbemava-nc  I can't manage to create a code to reproduce this issue. It happens in a specific page in my app after the upgrade. But I can't manage to extract the code in another section and reproduce the issue. The issue only happens there. If I manage to reproduce I will let you know.

**Comment by spiderion** [comment]
More details, 
The issue only happens when the lottie is wrapped by a Transform widget:

Transform(
                            alignment: Alignment.center,
                            transform: Matrix4.rotationY(math.pi),
                            child: Lottie.asset(
                              'assets/lottie/angel_shaded.json',
                            ),
                          )
                          
If I remove the transform the issue doesn't happen.
Can you check maybe there was a change in the transform that is causing the issue.
@danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @spiderion, can you provide the asset you're using? A complete sample would also help us. I added a transform to the code sample I shared earlier in https://github.com/flutter/flutter/issues/144189#issuecomment-1972604147 and also replaced the dialog with a bottom sheet but the issue does not reproduce. 

<details>
<summary>full code sample</summary>

```dart
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeWidget(),
    );
  }
}

class HomeWidget extends StatelessWidget {
  const HomeWidget({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Transform(
          transform: Matrix4.rotationY(math.pi),
          alignment: Alignment.center,
          child: Lottie.network(
            'https://raw.githubusercontent.com/xvrh/lottie-flutter/master/example/assets/Mobilo/A.json',
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          showModalBottomSheet<void>(
            context: context,
            builder: (BuildContext context) {
              return SizedBox(
                height: MediaQuery.sizeOf(context).height * 0.5,
                child: Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      const Text('Modal BottomSheet'),
                      ElevatedButton(
                        child: const Text('Close BottomSheet'),
                        onPressed: () => Navigator.pop(context),
                      ),
                    ],
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
```
</details>
