### ISSUE TITLE
`${FLUTTER_LOGS_DIR}/noop.txt`, does it have to exist?

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144153]
### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

See https://github.com/flutter/flutter/issues/144056.

**Comment by keyonghan** [comment]
I guess the file is necessary to create the folder: https://flutter-review.googlesource.com/c/recipes/+/9944/1..2/recipe_modules/logs_util/api.py
/cc @godofredoc

**Comment by godofredoc** [comment]
That is correct, the noop.txt file is uploaded to force the creation of the folder structure in GCS.
