### ISSUE TITLE
Getting platform exception [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null) E/flutter (28941): #0

### ISSUE THREAD

**Issue by mrazamerchant** [flutter/flutter#144228]
### Steps to reproduce

The Error i got on debug console :
```
D/FlutterGeolocator( 3804): Flutter engine connected. Connected engine count 1
E/flutter ( 3804): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
E/flutter ( 3804): #0 FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:248:7)
E/flutter ( 3804):
E/flutter ( 3804): https://github.com/firebase/flutterfire/pull/1 MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:89:25)
```

### Actual results

i have a project where i use to work on flutter 3.16.0 and its working fine but when i migrated my flutter from 3.16.0 to current latest version 3.19.1 and i got firebase exception.

https://github.com/firebase/flutterfire/assets/140117432/c1853a23-dd91-49cc-8201-07dfbc6a94c3
https://github.com/firebase/flutterfire/assets/140117432/704b77b9-5338-4ce0-bf81-61a402500461
https://github.com/firebase/flutterfire/assets/140117432/8778d6ff-c60c-4aa0-80d9-9a8c638a4e57
https://github.com/firebase/flutterfire/assets/140117432/4a118bcb-4ca8-4c82-861a-88f55607e9d0

I used official article to migrate flutter to 3.19.1.
https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

Remember my project running fine on 3.16.0
Please provide quick solution as i need to upgrade my project thanks in advance.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6.3 22G436 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] VS Code (version 1.81.0)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by stuartmorgan** [comment]
> E/flutter ( 3804): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
> E/flutter ( 3804): #0 FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:248:7)

This is `firebase_core` code that is returning an invalid value according to their own protocol definition; you'd need to [report this to the plugin's developers](https://github.com/firebase/flutterfire/issues) to investigate. If they determine as part of that investigation that the reason for the failure is a bug in 3.19 they can file an issue here with specifics about what the Flutter aspect of this is.

**Comment by mrazamerchant** [comment]
> > E/flutter ( 3804): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
> > E/flutter ( 3804): #0 FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:248:7)
> 
> This is `firebase_core` code that is returning an invalid value according to their own protocol definition; you'd need to [report this to the plugin's developers](https://github.com/firebase/flutterfire/issues) to investigate. If they determine as part of that investigation that the reason for the failure is a bug in 3.19 they can file an issue here with specifics about what the Flutter aspect of this is.

i have reported in flutter fire community i got this reply:
t might not necessarily be a flutterfire issue, but could be ripple effects of the migration.
See https://github.com/flutter/flutter/issues/135392 original flutter issue that implemented the changes and https://github.com/flutter/flutter/issues/135392#issuecomment-1872529798 for reference.

Also would like to confirm if you carefully followed all the steps to properly migrate, as it requires some changes to be at specific positions in respective files.
Also, if you could also try to check if the similar error occurs without using flutterfire plugins or if this is specific to flutterfire or not.

Im not able to find any solution yet.

**Comment by stuartmorgan** [comment]
> i have reported in flutter fire community i got this reply:
> t might not necessarily be a flutterfire issue, but could be ripple effects of the migration.

Please see my comment above for the process for determining whether this is a Flutter bug, and how it would be reported if so.

**Comment by mrazamerchant** [comment]
im not getting any solution regarding this issue if this issue is a from flutter it self or flutter fire.
