### ISSUE TITLE
Dialog barrierColor is not being set through the ColorScheme scrim property or any other property of ThemeData. 

### ISSUE THREAD

**Issue by ashndev** [flutter/flutter#144245]
### Steps to reproduce

**The Issue:**
The `ColorScheme` class contains a `scrim` property that is defined as "A color use to paint the scrim around of modal components." in the docs. That means that the color used here should be applied as the `barrierColor` for the dialogs as well as other modal components. However when I applied a red color to the `scrim` property nothing changed. After studying the Flutter SDK files I noticed that the `scrim` property of the `ColorScheme` doesn't seem to be used anywhere and for dialogs there is only a hardcoded fallback value of `Colors.black54` if you don't provide a `barrierColor` to the `showDialog` function. You can see that in one of the supplied screenshots. This is an issue because if no theme property is used to define that, my only option would be to manually set the `barrierColor` anywhere `showDialog` is used and do something similar for other modal components. So, I believe this is an error and it would be great to have it fixed. 

**How to reproduce:**
1. Create a minimalistic app with a button that opens a dialog and has the `ColorScheme` `scrim` property set to a color other than `Colors.black54` or simply use the code sample provided. 

### Expected results

The expected result is for the `barrierColor` of the dialog to be the `scrim` color set in the `ColorScheme`.

### Actual results

The actual result is that nothing changes and the `barrierColor` remains as `Colors.black54`. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          // Setting the scrim property based on the definition of scrim should
          // change the barrierColor of the dialog.
          scrim: Colors.red,
        ),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ElevatedButton(
            onPressed: () => showDialog(
                  context: context,
                  builder: (context) => const Dialog(
                    child: SizedBox(
                      width: 100,
                      height: 100,
                      child: Center(
                        child: Text(
                          'My Dialog',
                        ),
                      ),
                    ),
                  ),
                ),
            child: const Text('Open Dialog')),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1364" alt="Screenshot 2024-02-27 at 10 33 43 AM" src="https://github.com/flutter/flutter/assets/87834445/f0b65682-b3ae-4637-bade-c7e50258d21e">
<img width="1200" alt="Screenshot 2024-02-27 at 10 34 54 AM" src="https://github.com/flutter/flutter/assets/87834445/2a612983-c4ab-4b4f-9360-cba9f159a6ac">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.2, on macOS 13.6 22G120 darwin-arm64, locale en-US)
    • Flutter version 3.16.2 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (3 months ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ashley.novik/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (6 available)
    • iPhone SE (3rd generation) (mobile) • 913EF0ED-B81A-413E-8621-FCAA6E98BB28 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • iPhone 15 Pro Max (mobile)          • FB0D9C5A-1190-442A-AD7E-EB6CED4D6B4B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • iPad (10th generation) (mobile)     • 0351A487-E965-4DF5-AECC-32EF8B267FFC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • iPad mini (6th generation) (mobile) • 6F1B6816-E518-4AE4-8349-AC3A05D68E02 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@ashndev 
I guess instead of using `colorScheme: ColorScheme.fromSeed(` inside the `ThemeData`, using `DialogTheme` and then passing `barrierColor` gives the expected result as below:

<img width="385" alt="Screenshot 2024-02-28 at 1 40 37 PM" src="https://github.com/flutter/flutter/assets/67046386/f45c288a-1836-4a9e-8946-86f0327a3867">

```
theme: ThemeData(
        //
        dialogTheme: DialogTheme(
          barrierColor: Colors.green
        ),
        useMaterial3: true,
      ),
```

See if above helps to answer your issue ?

**Comment by ashndev** [comment]
Hello! Thanks for your response, but I checked before and just checked again and even in the latest stable version `DialogTheme` does not have a `barrierColor` parameter. What version are you using?

<img width="1140" alt="Screenshot 2024-02-28 at 3 24 58 AM" src="https://github.com/flutter/flutter/assets/87834445/d3ef6726-9e22-4c3a-b83c-c61c4c9cac9c">

**Comment by darshankawar** [comment]
> What version are you using?

I happened to be on latest master version and [this](https://github.com/flutter/flutter/pull/142490) seems to be a recent fix in it.

**Comment by ashndev** [comment]
> > What version are you using?
> 
> I happened to be on latest master version and [this](https://github.com/flutter/flutter/pull/142490) seems to be a recent fix in it.

Great, thank you so much! :)

**Comment by darshankawar** [comment]
Closing as resolved.
