### ISSUE TITLE
Migrate `src/third_party/perfetto` to `src/flutter/third_party`.

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144204]
Part of https://github.com/flutter/flutter/issues/67373.

If you think this will take longer than our check-in on March 11th, just LMK!

**Comment by cbracken** [comment]
Landed https://dart-review.googlesource.com/c/sdk/+/356622 in the Dart SDK which, once it rolls into the engine, will allow https://github.com/flutter/engine/pull/51272 to land.

**Comment by cbracken** [comment]
Landed https://dart-review.googlesource.com/c/sdk/+/356960 as a followup. Once this rolls into the engine, I'll rebase flutter/engine#51272.

**Comment by cbracken** [comment]
Fixed!
