### ISSUE TITLE
HapticFeedback not working on Android Samsung Galaxy A52s 5G, Android 14

### ISSUE THREAD

**Issue by FizbyteSoftware** [flutter/flutter#144226]
### Steps to reproduce

Add the following to a button on pressed, or a gesture detector on tap wrapping any element

```
HapticFeedback.heavyImpact(); //not working
HapticFeedback.mediumImpact(); //not working
HapticFeedback.lightImpact(); //not working
HapticFeedback.selectionClick(); //not working
HapticFeedback.vibrate(); // working
```

### Expected results

Should vibrate with different intensities 

### Actual results

Does not vibrate at all on the ones that don't work, vibrates on the last one

### Code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Centered Button Page'),
        ),
        body: CenterButtonPage(),
      ),
    );
  }
}

class CenterButtonPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: () {
         HapticFeedback.heavyImpact();
                            HapticFeedback.mediumImpact();
                            HapticFeedback.lightImpact();
                            HapticFeedback.selectionClick();
        },
        child: Text('Press Me'),
      ),
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Stefan@Stefans-Laptop ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
    • Flutter version 3.16.0 on channel stable at /Users/Stefan/Library/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (3 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/Stefan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] Connected device (4 available)
    • SM A528B (mobile)            • R5CT21Z80KR               • android-arm64  • Android 14 (API 34)
    • Teodorescu’s iPhone (mobile) • 00008101-0003681E1AC2001E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)              • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                 • chrome                    • web-javascript • Google Chrome 113.0.5672.126
    ! Error: Browsing on the local area network for Teodorescu’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

**Comment by golamsarwer97** [comment]
same issue

**Comment by stevethehu** [comment]
same behavior (only `HapticFeedback.vibrate()` works) on Samsung Galaxy A15 5G running Android 14

**Comment by golamsarwer97** [comment]
Glad to hear from you but it's not working for Samsung A13 device

**Comment by darshankawar** [comment]
@FizbyteSoftware 
I think this is similar to https://github.com/flutter/flutter/issues/73987 in which you can follow-up for further updates.
You may also share your findings in that issue for better tracking.
Closing this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.
