### ISSUE TITLE
`flutter_framework_uncompressed_bytes` increased 20 MB

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#144251]
Introduced in https://github.com/flutter/flutter/pull/143244

[skia perf](https://flutter-flutter-perf.skia.org/e/?keys=X4129c1b014a53ca2bc7747c174d61ea5&selected=commit%3D39549%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dflutter_framework_uncompressed_bytes%252Ctest%253Dhello_world_macos__compile%252C&xbaroffset=39548)

cc @vashworth @jmagman

**Comment by gaaclarke** [comment]
This also affected compilation time a bit: https://flutter-flutter-perf.skia.org/e/?begin=1708976718&end=1709065303&keys=X1c434d0ca69955d70c543e4d2492de4d&num_commits=50&request_type=1&xbaroffset=39549

**Comment by gaaclarke** [comment]
Also release size: https://flutter-flutter-perf.skia.org/e/?begin=1709023189&end=1709057888&keys=X90e89dfcb51e2d4b7c4f221e7aea0c21&num_commits=50&request_type=1&xbaroffset=39549

**Comment by vashworth** [comment]
PR has been reverted, thanks for the heads up.
