### ISSUE TITLE
Scrolling gets stuck in weird loop

### ISSUE THREAD

**Issue by singh-karan-7** [flutter/flutter#144299]
### Steps to reproduce

Create a ListView and Display a bunch of items. Integrate Firebase in to your projects. Use StreamBuilder on each item to show or hide items. Delete an item from another device or from firebase db directly. 

### Expected results

Scrolling ListView should work normally and take user to the top of ListView

### Actual results

This results in weird loop where scrolling ListView does not take you to top. It gets stuck at a position and keeps going back and forth. This happens on real device(iPhone) in Testflight/Production build. It does not occur on simulator or in debug mode.

### Code sample

<details open><summary>If item gets deleted, I am showing a SizedBox, otherwise, it shows the item.</summary>

```dart
ListView.builder(
  // primary: false,
  shrinkWrap: true,
  itemCount: upcomingEventsList?.length,
  keyboardDismissBehavior:
      ScrollViewKeyboardDismissBehavior.onDrag,
  itemBuilder: (context, listViewIndex) {
    var listViewEventsRecord =
        upcomingEventsList![listViewIndex];
    return StreamBuilder<DocumentSnapshot>(
        key: ValueKey(listViewEventsRecord.reference.id),
        stream: firestore
            .doc(listViewEventsRecord.reference.path)
            .snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasData && (!snapshot.data!.exists))
            return SizedBox.shrink();
          listViewEventsRecord = snapshot.hasData
              ? EventsRecord.fromSnapshot(snapshot.data!)
              : listViewEventsRecord;

          return FFAppState().isGridView
                  ? EventListBiggerWidget(
                      key: Key(
                        'Keygib_${listViewEventsRecord.reference.id}',
                      ),
                      event: listViewEventsRecord,
                    )
                  : Padding(
                      padding: const EdgeInsets.fromLTRB(
                          8, 0, 8, 0),
                      child: EventSmallListPublicWidget(
                        key: Key(
                          'Keylwy_${listViewEventsRecord.reference.id}',
                        ),
                        event: listViewEventsRecord,
                      ),
                    );
        });
  },
),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/12271071/deb5030d-2eac-4a3b-b82d-331da985f14d

</details>

### Logs

<details open><summary>No Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.13.7, on macOS 14.2.1 23C71 darwin-arm64,
    locale en-IN)
    ! Flutter version 3.13.7 on channel [user-branch] at
      /Users/jasminderpalsingh/Documents/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss
      this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.2)
[✓] Connected device (6 available)
    ! Error: Browsing on the local area network for Jasminder’s iPhone Old.
      Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for Karanveer’s iPhone. Ensure
      the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@singh-karan-7 Thanks for the report.
Firebase is third party package for Flutter. If you are able to replicate this locally without using Firebase, then we could take a look at it further for verification.



> This happens on real device(iPhone) in Testflight/Production build. It does not occur on simulator or in debug mode.

This probably indicates a glitch at server or firebase side instead of at client side, so I suggest you to reach out to [firebase support](https://firebase.google.com/support) for further resolution on it, because it could be occuring due to cache. 

Closing for now, as this doesn't seem to be related to flutter framework. If you disagree, write in comments and I'll reopen it.

**Comment by singh-karan-7** [comment]
How can another framework like firebase cause ListView to behave in that manner? The item actually gets disappeared from ListView, after it is deleted. So, SizedView does replace the item, but, it does not scroll when, we come back to the same position where the item was present.
