### ISSUE TITLE
[Impeller] mask blurs don't work for textures

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#144266]
## reproduction
```c++
TEST_P(AiksTest, GaussianBlurStyleInnerTexture) {
  Canvas canvas;
  canvas.Scale(GetContentScale());
  Paint paint;
  paint.color = Color::Green();
  paint.mask_blur_descriptor = Paint::MaskBlurDescriptor{
      .style = FilterContents::BlurStyle::kInner,
      .sigma = Sigma(30),
  };
  std::shared_ptr<Texture> boston = CreateTextureForFixture("boston.jpg");
  canvas.DrawImage(std::make_shared<Image>(boston), {200, 200}, paint);
  Paint red;
  red.color = Color::Red();
  canvas.DrawRect(Rect::MakeXYWH(0, 0, 200, 200), red);
  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```

## expected result

I expect the texture to have a blurry outline.

## observed result

The image just draws as normal.

**Comment by bdero** [comment]
We shouldn't use a Gaussian blur to handle mask blurring for anything drawn with rectangle/rrect/elliptical geometry regardless of the color source.

**Comment by gaaclarke** [comment]
> We shouldn't use a Gaussian blur to handle mask blurring for anything drawn with rectangle/rrect/elliptical geometry regardless of the color source.

I'll update the description to avoid talking about `GaussianBlurFilterContents`.

**Comment by gaaclarke** [comment]
Here is an example of how skia handles this: https://fiddle.skia.org/c/d0be824c0999691bb7e62c446f7db0ce

<img width="272" alt="Screenshot 2024-02-29 at 10 48 38 AM" src="https://github.com/flutter/flutter/assets/30870216/96c95c97-d22c-4778-b38d-1edff7f28aaf">

**Comment by gaaclarke** [comment]
notes from the chat:
```
bdero: BorderMaskBlurFilterContents was specifically made to be used for the DrawImageRect mask filter case long ago.
But today we should reuse the Aiks path I added later on that supports all of the color sources
```
