### ISSUE TITLE
[Flutter GPU] Create a simple package that demonstrates model rendering using Flutter GPU.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#144265]

**Comment by bdero** [comment]
This is underway at https://github.com/bdero/flutter_scene/issues/1.

**Comment by bdero** [comment]
Impeller Scene has been fully ported to Flutter Scene. It supports glTF binaries with PBR, translucency, and animation! This package will continue to evolve as we land features in Flutter GPU.
