### ISSUE TITLE
During archive process for ios the following exception occurs

### ISSUE THREAD

**Issue by sadaqatdev** [flutter/flutter#144215]
### Steps to reproduce

build flutter archive 

### Expected results

Unhandled exception:
Null check operator used on a null value
#0 Context.embedFlutterFrameworks (file:///Users/macbookpro/flutter/packages/flutter_tools/bin/xcode_backend.dart:235:68)
https://github.com/mogol/flutter_secure_storage/issues/1 Context.run (file:///Users/macbookpro/flutter/packages/flutter_tools/bin/xcode_backend.dart:59:9)
https://github.com/mogol/flutter_secure_storage/issues/2 main (file:///Users/macbookpro/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
https://github.com/mogol/flutter_secure_storage/issues/3 _delayEntrypointInvocation. (dart:isolate-patch/isolate_patch.dart:295:33)
https://github.com/mogol/flutter_secure_storage/pull/4 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Command PhaseScriptExecution failed with a nonzero exit code

### Actual results

make build

### Code sample

NA

### Screenshots or Video

NA

### Logs

NA

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.1.2 23B92 darwin-x64, locale
en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by huycozy** [comment]
Could you check [this](https://github.com/flutter/flutter/issues/138795#issuecomment-1821481564) to see if it helps to solve this error?
