### ISSUE TITLE
Add Container.clipBehavior to clip to the decoration

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14421]
At a glance, I'd expect DecoratedBox.decoration.borderRadius to RRect clip the DecoratedBox's child. But it doesn't. If it isn't meant to, clarify in documentation.

**Comment by Hixie** [comment]
It should... weird.

**Comment by xster** [comment]
```dart
return new MaterialApp(
  title: 'Flutter Demo',
  home: new Scaffold(
    body: new Center(
      child: new DecoratedBox(
        decoration: new BoxDecoration(
          color: Colors.blue,
          borderRadius: new BorderRadius.circular(30.0),
        ),
        child: new Container(
          width: 100.0,
          height: 300.0,
          color: Colors.red.withAlpha(80),
        ),
      ),
    ),
  ),
);
```
produces for me something like
![screen shot 2018-02-01 at 12 42 02 pm](https://user-images.githubusercontent.com/156888/35702211-5cb9d31e-074d-11e8-8c35-a1a5401d9288.png)

**Comment by alexwhiteside1** [comment]
Any Updates? I'm trying to use a DecoratedBox to clip (add Border Radius) to a LinearProgressIndicator to produce something like the following:
![screen shot 2018-02-27 at 10 39 52 pm](https://user-images.githubusercontent.com/5420059/36773575-302aec08-1c0f-11e8-98f0-0a2360e7ead7.png)

**Comment by szotp** [comment]
I have used ClipPath as a workaround:

```
class CornerRadiusClipper extends CustomClipper<Path> {
  final double radius;

  CornerRadiusClipper(this.radius);

  @override
  Path getClip(Size size) {
    final path = new Path();
    final rect = new Rect.fromLTRB(0.0, 0.0, size.width, size.height);
    path.addRRect(new RRect.fromRectAndRadius(rect, new Radius.circular(radius)));
    return path;
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) {
    return false;
  }
}
```

**Comment by Hixie** [comment]
(in that snippet, shouldReclip should return true if the radius changed)

**Comment by andreidiaconu** [comment]
I have also encountered this issue as well. Was about to open a new issue but found this one. Seems to still be reproducible on the latest master. Any updates 😬?

My code to reproduce:

```
class BorderRadiusBug extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Container(
      color: Colors.white,
      child: new Center(
        child: new Container(
          width: 100.0,
          height: 100.0,
          decoration: new BoxDecoration(
              borderRadius: new BorderRadius.circular(15.0),
              border: new Border.all(color: Colors.black)
          ),
          child: new Container(color: Colors.blue),
        ),
      ),
    );
  }
}
```

Uploaded it to my [repo for bugs](https://github.com/andreidiaconu/flutter-toimage-bugs/blob/master/lib/main.dart), if it helps with reproducing.

**Comment by Hixie** [comment]
Fixing this is easy, if anyone wants to submit a PR. The trick is to only add the clip if it is definitely needed. Maybe to have a flag that decides whether to clip or not.

**Comment by Hixie** [comment]
(clips are very expensive)

**Comment by nextfunc** [comment]
@Hixie @eseidel Is this really easy for my first contribution? :) 
I can try it if you say Yes!

**Comment by thphuc** [comment]
@Hixie @eseidelGoogle  Is this really easy for my first contribution? :)
I can try it if you say Yes!

**Comment by Hixie** [comment]
We're actually considering (as of today) changing how we do clips entirely, so let's leave this one aside for now.

**Comment by nirav4273** [comment]
@Hixie  Any update for above issue ?
i am facing same issue.
https://stackoverflow.com/questions/52148292/flutter-border-radius-not-apply-inside-container-widget

**Comment by GillesMontyne** [comment]
Found a solution using **PhysicalModel**
```
return new MaterialApp(
  title: 'Flutter Demo',
  home: new Scaffold(
    body: new Center(
      child: new PhysicalModel(
        color: Colors.transparent,
        borderRadius:  BorderRadius.circular(80.0),
        clipBehavior: Clip.antiAlias,
        child: LinearProgressIndicator(
          backgroundColor: Color.fromRGBO(209, 224, 224, 0.2),
            value: 0.5,
            valueColor: AlwaysStoppedAnimation(Colors.amber),
        ),
      ),
    ),
  ),
);
```
Which results into this: 

![image](https://user-images.githubusercontent.com/10937624/50607644-2c3eb300-0eca-11e9-8dd3-4a5f9c142c39.png)

**Comment by Hixie** [comment]
`DecoratedBox` shouldn't clip, it's the core widget that paints the decoration.
However, we should make `Container` take a `clipBehaviour` that clips to the decoration.
If anyone wants to do that, please feel free to submit a PR.

**Comment by Hixie** [comment]
(The documentation on DecoratedBox looks clear to me.)

**Comment by BataraSurya** [comment]
I noticed that putting a Widget that is supposed to clip it's child directly under a ListView will cause the clipping to fail. I got around this by wrapping the clipping widget with another Container widget. it worked for me.

**Comment by wilburt** [comment]
Any update on this?

**Comment by DJafari** [comment]
@wilburt you can wrap your widget with `ClipRRect` widget

```dart
ClipRRect(
	clipBehavior: Clip.antiAlias,
	borderRadius: BorderRadius.circular(5),
	child: ...
),
```

**Comment by viditsingh17** [comment]
Use the `clipBehaviou`r property inside the Container widget. Assign: `Clip.antiAlias` and it shout work.

**Comment by rus-rk9** [comment]
> @wilburt you can wrap your widget with `ClipRRect` widget
> 
> ```dart
> ClipRRect(
> 	clipBehavior: Clip.antiAlias,
> 	borderRadius: BorderRadius.circular(5),
> 	child: ...
> ),
> ```

It worked for me!)

**Comment by steeling** [comment]
Does this still not work?

From a dartpad:
```
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color:Colors.orange,
      child: Container(
              height: 100,
              width: 100,
              clipBehavior: Clip.antiAlias,
              // margin: EdgeInsets.symmetric(horizontal: 20),
              padding: EdgeInsets.symmetric(vertical: 12),
              alignment: Alignment.center,
              decoration: BoxDecoration(
                color: Colors.blue,
                borderRadius: BorderRadius.circular(20),
              ),
        ),
    );
  }
}
```

**Comment by rus-rk9** [comment]
I used to ClipRRect

**Comment by steeling** [comment]
This works when the background is not a material background I believe, but still I think this *should* work
