### ISSUE TITLE
Failed assertion: line 5200 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by kin-922** [flutter/flutter#144223]
### Steps to reproduce

<details>
<summary>sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:news_feed/screens/pages/head_line_page.dart';
import 'package:news_feed/screens/pages/news_list_page.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _currentPageIndex = 0;

  final _pages = [
    HomeScreen(),
    HeadLinePage(),
    NewsListPage(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: NavigationBar(
        onDestinationSelected: (int index) {
          setState(() {
            _currentPageIndex = index;
          });
        },
        indicatorColor: Colors.amber,
        selectedIndex: _currentPageIndex,
        destinations: const <Widget>[
          NavigationDestination(
            selectedIcon: Icon(Icons.home),
            icon: Icon(Icons.home_outlined),
            label: 'トップページ',
          ),
          NavigationDestination(
            icon: Badge(child: Icon(Icons.notifications_sharp)),
            label: 'ニュース一覧',
          ),
          NavigationDestination(
            icon: Badge(
              label: Text('2'),
              child: Icon(Icons.messenger_sharp),
            ),
            label: 'アプリについて',
          ),
        ],
      ),
      body: _pages[_currentPageIndex],
    );
  }
}
```
</details>

### Expected results

open the HomeScreen().

### Actual results

I have got the error message as blow.

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building NotificationListener<ScrollNotification>:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5200 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
```

### Code sample

<details open>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:news_feed/screens/pages/head_line_page.dart';
import 'package:news_feed/screens/pages/news_list_page.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _currentPageIndex = 0;

  final _pages = [
    HomeScreen(),
    HeadLinePage(),
    NewsListPage(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: NavigationBar(
        onDestinationSelected: (int index) {
          setState(() {
            _currentPageIndex = index;
          });
        },
        indicatorColor: Colors.amber,
        selectedIndex: _currentPageIndex,
        destinations: const <Widget>[
          NavigationDestination(
            selectedIcon: Icon(Icons.home),
            icon: Icon(Icons.home_outlined),
            label: 'トップページ',
          ),
          NavigationDestination(
            icon: Badge(child: Icon(Icons.notifications_sharp)),
            label: 'ニュース一覧',
          ),
          NavigationDestination(
            icon: Badge(
              label: Text('2'),
              child: Icon(Icons.messenger_sharp),
            ),
            label: 'アプリについて',
          ),
        ],
      ),
      body: _pages[_currentPageIndex],
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open>
<summary>flutter doctor -v</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.2.1 23C71 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.86.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @kin-922, your code sample is not complete. Please provide a complete minimal reproducible code sample without any third-party packages so that we can investigate this issue. 

Thank you

**Comment by kin-922** [comment]
**main.dart file**
import 'package:flutter/material.dart';
import 'package:news_feed/style/style.dart';
import 'screens/home_screen.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "NewsApp",
      theme: ThemeData(
        brightness: Brightness.dark,
        fontFamily: BoldFont,
        useMaterial3: true,
      ),
      home: HomeScreen(),
    );
  }
}

**home_screen.dart file**
import 'package:flutter/material.dart';
import 'package:news_feed/screens/pages/head_line_page.dart';
import 'package:news_feed/screens/pages/news_list_page.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _currentPageIndex = 0;

  final List<Widget> _pages = [
    HomeScreen(),
    HeadLinePage(),
    NewsListPage(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: NavigationBar(
        onDestinationSelected: (int index) {
          setState(() {
            _currentPageIndex = index;
          });
        },
        indicatorColor: Colors.amber,
        selectedIndex: _currentPageIndex,
        destinations: const <Widget>[
          NavigationDestination(
            selectedIcon: Icon(Icons.home),
            icon: Icon(Icons.home_outlined),
            label: 'トップページ',
          ),
          NavigationDestination(
            icon: Badge(child: Icon(Icons.notifications_sharp)),
            label: 'ニュース一覧',
          ),
          NavigationDestination(
            icon: Badge(
              label: Text('2'),
              child: Icon(Icons.messenger_sharp),
            ),
            label: 'アプリについて',
          ),
        ],
      ),
      body: _pages[_currentPageIndex],
    );
  }
}
**news_list_page.dart**
import 'package:flutter/material.dart';

class NewsListPage extends StatelessWidget {
  const NewsListPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(child: Scaffold(
      body:  const Padding(
        padding: EdgeInsets.all(8.0),
        child: Column(
          children: <Widget>[
            Card(
              child: ListTile(
                leading: Icon(Icons.notifications_sharp),
                title: Text('Notification 1'),
                subtitle: Text('This is a notification'),
              ),
            ),
            Card(
              child: ListTile(
                leading: Icon(Icons.notifications_sharp),
                title: Text('Notification 2'),
                subtitle: Text('This is a notification'),
              ),
            ),
          ],
        ),
      ),
    ));
  }
}
**head_line_page.dart**
import 'package:flutter/material.dart';

import '../../style/style.dart';

class HeadLinePage extends StatelessWidget {
  const HeadLinePage({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(child: Scaffold(
     body: Card(
        shadowColor: Colors.transparent,
        margin: const EdgeInsets.all(8.0),
        child: SizedBox.expand(
          child: Center(
            child: Text(
              'Home page',
              style: TextStyle(fontFamily: RegularFont),
              // theme.textTheme.titleLarge,
            ),
          ),
        ),
      ),
    ));
  }
}
**about_us_page.dart**

import 'package:flutter/material.dart';

class AboutUsPage extends StatefulWidget {
  const AboutUsPage({super.key});

  @override
  State<AboutUsPage> createState() => _AboutUsPageState();
}

class _AboutUsPageState extends State<AboutUsPage> {

  @override
  Widget build(BuildContext context) {
    return SafeArea(child: Scaffold(
    body:Container(
    child: Text("About Us"),
    ),
    ));
  }
}

Thank you.

**Comment by danagbemava-nc** [comment]
Your issue is that you've set the `HomeScreen` to be a child of itself.
