### ISSUE TITLE
When are there plans to support multi-window on the desktop?

### ISSUE THREAD

**Issue by zhulinghaizhoqiaodaima** [flutter/flutter#144282]
### Use case

When are there plans to support multi-window on the desktop?

### Proposal

When are there plans to support multi-window on the desktop?

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/30701

Please see also https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed
