### ISSUE TITLE
Add onHover and onFocusChange to OutlinedButton.icon constructor

### ISSUE THREAD

**Issue by yousefak007** [flutter/flutter#144256]
### Steps to reproduce

there is no onHover and onFocusChange function in OutlinedButton.icon

### Expected results

find onHover, onFocusChange

### Actual results

![image](https://github.com/flutter/flutter/assets/46021584/cd99c68c-2b72-42eb-9f81-66f420735265)

**Comment by piedcipher** [comment]
I would like to take this up! May be we can add it for ElevatedButton.icon, FilledButton.icon & TextButton.icon as well i.e. all ButtonStyleButtom subclasses.

**Comment by yousefak007** [comment]
even isSemanticButton, missing from TextButton.icon

**Comment by HansMuller** [comment]
Looks like an oversight. Should be an easy fix.

**Comment by piedcipher** [comment]
> I would like to take this up! May be we can add it for ElevatedButton.icon, FilledButton.icon & TextButton.icon as well i.e. all ButtonStyleButton subclasses.

For OutlinedButton.icon only these were missing, for others it's already there.

**Comment by piedcipher** [comment]
> even isSemanticButton, missing from TextButton.icon

This one is missing from FilledButton, ElevatedButton and OutlinedButton. Shall we do this? @HansMuller
