### ISSUE TITLE
add one switch to webview_flutter to control whether it is interactive or not

### ISSUE THREAD

**Issue by wanjm** [flutter/flutter#144289]
### Use case

when use WebView_flutter in web, we can't interact with the area of flutter that on top of webview, so we need to use PointerInterceptor  as talked in https://github.com/flutter/flutter/issues/142427#issuecomment-1965628862

but i think WebView_flutter should have a switch to control interactive it self, and when it is not interactive, engine can do a lot optimize, maybe there is no need to copy the picture of webview or pass use input to it;

### Proposal

PlatformView is very expressive, as it need to copy texture and react to user input; if one platform view is inactive, maybe it can be put on bottom or top of flutter to avoid copy, as multi-view is coming, this is more available. as webview_flutter is a special PlatfromView, and not always need to be interactive, so I suggest to add such switch, so that we can use webview_flutter more efficient;

**Comment by darshankawar** [comment]
@wanjm 
Can you provide an example (code sample) which shows current limitation and how would adding a switch would help to resolve it ?

**Comment by stuartmorgan** [comment]
> but i think WebView_flutter should have a switch to control interactive it self, and when it is not interactive, engine can do a lot optimize

This is not how the layering works; the engine does not know about individual plugins. There is no way for the engine to query a `webview_flutter`-specific setting.

If you are proposing a fundamentally new kind of platform view at the engine level, the next step would be a detailed [design document](https://github.com/flutter/flutter/wiki/Design-Documents) describing in detail how it would work and what the benefits would be. Adding a new kind of platform view would require substantial justification for the added complexity, so the discussion of advantages would need to be much more detailed and technical than the high-level discussion here. See below for some specific things the design document would need to address.

> maybe there is no need to copy the picture of webview

Platform views do not generally copy the display, nor does "non-interactive" imply "not displayed" or "not visually changing".

> or pass use input to it;

It's not clear to me what significant engine optimizations this would allow.

> maybe it can be put on bottom or top of flutter

Layering is primarily about visual presentation, not gesture handling, so as above it's not clear how "non-interactive" would allow for changing the way it is rendered.

**Comment by wanjm** [comment]
> @wanjm Can you provide an example (code sample) which shows current limitation and how would adding a switch would help to resolve it ?

one example i said in the issue
https://github.com/flutter/flutter/issues/140855#issuecomment-1899462721
