### ISSUE TITLE
[Flutter GPU] Make the C files not be next to the Dart sources to make it easier to copy as a package.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#144267]

**Comment by bdero** [comment]
Struggling to commit to another file layout for this. Eh, maybe it doesn't matter as much as I was thinking in the moment. It's trivial to eliminate the C files while copying into the engine artifacts if we want.

**Comment by bdero** [comment]
In the end I decided not to bother with this. Closing it out.
