### ISSUE TITLE
Selectable Region Widget - Right to Left Direction

### ISSUE THREAD

**Issue by Willyyyy9** [flutter/flutter#144271]
### Use case

I want to use Selectable Region Widget but with Right to Left Direction instead of the normal Left to Right

### Proposal

I want to use Selectable Region Widget but with Right to Left Direction instead of the normal Left to Right

**Comment by darshankawar** [comment]
@Willyyyy9 
Can you elaborate on your case as what exactly are you trying to achieve by providing a runnable code sample that shows current limitation with `SelectableRegion` and what's the expected functionality you are looking for ?

**Comment by 7ooda99** [comment]
we already render our widgets on the screen but the issue is to make the selection from right to left not from left to right.
good to keep in mind that we are using selection on containers not text.

https://github.com/flutter/flutter/assets/85562983/9ad1775f-ab95-4677-b4de-94cc4f1f8ba6

**Comment by 7ooda99** [comment]
i use the dispatchSelectionEvent from the selectable region 
init the dispatchSelectionEvent there are an enum class that contains events such as startEdgeUpdate, endEdgeUpdate, clear, selectAll, selectWord,((((( directionallyExtendSelection, granularlyExtendSelection )))).
i can not access the case of directionallyExtendSelection but i can access other methods 
so we do not know why is that

**Comment by 7ooda99** [comment]
this is the code were used the selectable adapter : 
`
return SelectionArea(

        child: Stack(
          // clipBehavior: Clip.antiAlias,
          // textDirection: TextDirection.rtl,
          // alignment: Alignment.topRight,
          children: [
            ...state.wordsInPage.map((e) {
              double widthScaleFactor = 794.r / width;
              double heightScaleFactor = 1123.r / hight;
              double scaledLeft = e.bbox.x1 * widthScaleFactor;
              double scaledTop = e.bbox.y1 * heightScaleFactor;
              // double scaledRight = e.words.last.bbox.x2 * widthScaleFactor;
              final double lineHeight =
                  convertToLogicalPixels(context, (e.bbox.y2 - e.bbox.y1));

              return Positioned(
                height: 20.h,
                top: scaledTop,
                left: scaledLeft,
                width: (e.bbox.x2.toDouble() - e.bbox.x1.toDouble()) /
                    (width / (794.r)),
                child: Align(
                  alignment: Alignment.centerRight,
                  child: MySelectableAdapter(
                    id: ",${e.id}",
                    child: Container(
                      color: e.isSelected
                          ? Colors.amber.withOpacity(0.5)
                          : Colors.transparent,
                    ),
                  ),
                ),
              );
            }),

          ],
        ),
      );
    },
  
);
`

**Comment by Osama0habib** [comment]
@darshankawar 
the above reply from @7ooda99  describe what we are looking for .... we are all working together on the same issue

**Comment by darshankawar** [comment]
@Osama0habib @7ooda99 Thanks for the update. As I understand correctly, you have localized text that is usually read and typed from right to left and you would like to have the feature to select the entire text in same way, ie, dragging the text from right to left but currently it seems to only allow to select entire text from left to right ?

Is this a correct interpretation of the issue you are reporting ?

Also, @7ooda99 Please provide us a runnable code sample without third party or custom code implementation, that we can simply copy paste and run to verify further.

**Comment by 7ooda99** [comment]
yes @darshankawar , but keep in mind that we are not dealing with texts. we are dealing with containers 
so what is making the issue complex is that we try to select containers and set the directions 
i can not give you small runnable code to test  you have to use "selectable adapter"
you can use this flutter command 
flutter create --sample=widgets.SelectableRegion.2 mysample
to test it well >> after install the project
inside the column make 3 rows .. each row contain 3 container (width: 60 , height: 60, color: Colors.yellow)
after setting this you can try to select from the first container as rtl and notice the behavior when the selection moves to the next line.
