### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.view.ResourceExtractor.waitForCompletion()' on a null object reference

### ISSUE THREAD

**Issue by mjfuentes** [flutter/flutter#14423]
## Steps to Reproduce

My application was running properly but it's not running anymore.
I checked and even after reverting all of my last changes it still doesn't work. BUT i tried creating a new app and it ran correctly.
Tried updating flutter with same results.

## Logs
```
Launching lib/main.dart on Moto G 5 Plus in debug mode...
Initializing gradle...                                0.5s
Resolving dependencies...                             0.8s
Running 'gradlew assembleDebug'...                    1.4s
Built build/app/outputs/apk/app-debug.apk (24.0MB).
E/FlutterMain( 1187): Flutter initialization failed.
E/FlutterMain( 1187): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.view.ResourceExtractor.waitForCompletion()' on a null object reference
E/FlutterMain( 1187): 	at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:173)
E/FlutterMain( 1187): 	at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:145)
E/FlutterMain( 1187): 	at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:81)
E/FlutterMain( 1187): 	at com.nedelu.juntadaflutter.MainActivity.onCreate(MainActivity.java:11)
E/FlutterMain( 1187): 	at android.app.Activity.performCreate(Activity.java:6672)
E/FlutterMain( 1187): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
E/FlutterMain( 1187): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
E/FlutterMain( 1187): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
E/FlutterMain( 1187): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/FlutterMain( 1187): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
E/FlutterMain( 1187): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterMain( 1187): 	at android.os.Looper.loop(Looper.java:154)
E/FlutterMain( 1187): 	at android.app.ActivityThread.main(ActivityThread.java:6123)
E/FlutterMain( 1187): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterMain( 1187): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
E/FlutterMain( 1187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```
## Flutter Doctor

[✓] Flutter (on Linux, locale en_AU.UTF-8, channel alpha)
    • Flutter version 0.0.21-pre.367 at /home/matias/workspace/flutter
    • Framework revision 26102c9120 (20 hours ago), 2018-02-01 10:27:55 -0800
    • Engine revision de34a3e272
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.7af4db0ea091dddca6b2da851e6dda8d7f9467e8

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/matias/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /home/matias/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/matias/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[✓] Connected devices
    • Moto G 5 Plus • ZY22454QPG • android-arm • Android 7.0 (API 24)

• No issues found!

**Comment by mjfuentes** [comment]
I checked and event reverting all of my last changes it still doesn't work. BUT i tried creating a new app and it ran correctly.

**Comment by najeira** [comment]
I have a same problem.

The following crash reports were recorded in Google Play Console:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2711)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2772)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1515)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:241)
  at android.app.ActivityThread.main (ActivityThread.java:6217)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)
Caused by: java.lang.RuntimeException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:207)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:145)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:81)
  at me.cartune.android.MainActivity.onCreate (MainActivity.java:28)
  at android.app.Activity.performCreate (Activity.java:6705)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1119)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2664)
Caused by: java.lang.NullPointerException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:173)
```

The app run with Flutter alpha 0.0.20.

**Comment by mjfuentes** [comment]
Fixed by adding Android SDK to the flutter android module dependencies

**Comment by alescdb** [comment]
@mjfuentes Can you elaborate on how you fixed it ?
I'm facing the same issue.
Thanks !

**Comment by jonasbark** [comment]
I "fixed" it by uninstalling the existing application

**Comment by xuehu54321** [comment]
Finally I found the real reason, FlutterMain.startInitialization() were called in io.flutter.app.FlutterApplication, so your Application class should extend FlutterApplication or call FlutterMain.startInitialization() in your Application class to initialize the flutter.

**Comment by CoderJerry** [comment]
This issue can also be solved by deleting "build" folder and reruning

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.

**Comment by leorachit** [comment]
Still facing the same problem.

**Comment by Anyoks** [comment]
Me too! same issue here

**Comment by mukendi** [comment]
I have the same problem,and i need your help
