### ISSUE TITLE
Inverted colors for images with Gray color model

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#14429]
## Steps to Reproduce
Consider this example:
```
new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Image.network(
                "https://storage.googleapis.com/flutter-test/greys_yf6ijb.jpg"),
            new Image.network(
                "https://storage.googleapis.com/flutter-test/greys.jpg"),
          ],
        ),
```
Both images are greyscale, but `greys.jpg` is encoded in YCbCr H2V2 and `greys_yf6ijb.jpg` is encoded in 8 bits grey.

As you can see in this screenshot, greys_yf6ijb.jpg shows up with inverted colors while greys.jpg does not.
![screenshot_1517534406](https://user-images.githubusercontent.com/311774/35712358-795f37ba-0776-11e8-8a7d-790a1a8e574c.png)

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale en-US, channel alpha-chq-candidate)
    • Flutter version 0.0.21-pre.6 at /Users/philipp/carnivore/flutter
    • Framework revision f985e8d248 (6 hours ago), 2018-02-01 11:28:28 -0800
    • Engine revision 8f2d72b183
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.7af4db0ea091dddca6b2da851e6dda8d7f9467e8

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/philipp/Library/Android/sdk
    • Android NDK at /Users/philipp/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0.beta.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by brianosman** [comment]
This was fixed in Skia, then rolled into flutter/engine by https://github.com/flutter/engine/pull/4911. Once that version of the engine is rolled out, the bug should be fixed.

**Comment by zoechi** [comment]
Did flutter/engine#4911 fix this for you?
