### ISSUE TITLE
[ios]device lab test yields exactly the same results in multiple runs

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#144284]
### Steps to reproduce

This is the command i run: 
```
# Under devicelab: 
../../bin/dart bin/run.dart -d 00008030-001A083911C3802E --local-engine=ios_profile_unopt --local-engine-host host_profile_unopt -t platform_views_scroll_perf_ios_ad_banners__timeline_summary
```

I have been getting exactly the same results after multiple runs: 

```
Task result:
{
  "success": true,
  "data": {
    "average_frame_build_time_millis": 0.6921784037558686,
    "90th_percentile_frame_build_time_millis": 1.249,
    "99th_percentile_frame_build_time_millis": 1.884,
    "worst_frame_build_time_millis": 2.286,
    "missed_frame_build_budget_count": 0,
    "average_frame_rasterizer_time_millis": 4.144610328638498,
    "stddev_frame_rasterizer_time_millis": 0.7606731909453592,
    "90th_percentile_frame_rasterizer_time_millis": 5.162,
    "99th_percentile_frame_rasterizer_time_millis": 7.014,
    "worst_frame_rasterizer_time_millis": 9.925,
    "missed_frame_rasterizer_budget_count": 0,
    "frame_count": 213,
    "frame_rasterizer_count": 213,
    "new_gen_gc_count": 6,
    "old_gen_gc_count": 0,

```

When I run it again, it successfully runs, but I always get the exactly the name numbers. 

I am not sure about the details of how the test is run, but it feels like the result is cached somewhere, and a new run fails to overwrite it. 

### Expected results

The result should be updated

### Actual results

The result is always the same

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jmagman** [comment]
@hellohuanlin we don't cache this anywhere in the test runner I don't think, are you still seeing this?

**Comment by hellohuanlin** [comment]
I am not seeing this lately.

**Comment by jmagman** [comment]
So when you run multiple times you get different numbers?  Can this be closed then?

**Comment by hellohuanlin** [comment]
Closing this since it's not happening again.
