### ISSUE TITLE
Should provide a way to show download progress notifications

### ISSUE THREAD

**Issue by welldone217** [flutter/flutter#14435]
```dart
//downloadfile
  Future _startDownLoad(String url,String filename) async {
    try {
      var response = await http.get(url+filename); 
      List<int> _bytes = response.bodyBytes; 
      //save dir
      String _downdir='/sdcard/apk/download/';
      new Directory(_downdir).create(recursive: true)
          .then((Directory directory) {
            String _downedfile= _downdir  + filename;
            new File(_downedfile).writeAsBytes(_bytes).then((File file) async {
            #   **//after download completely ，how to call the android installer**
            });
      });
    } on Exception catch (e) {
      // Anything else that is an exception
      print('some error: $e');
    } catch (e) {
      // No specified type, handles all
      print('any error: $e');
    }
  }
```

**Comment by welldone217** [comment]
by the way. i want show this download file in Notification too, there is any demo? thank replay ^^

**Comment by btastic** [comment]
I don't think there is a "native flutter" way of doing this. You'd have to implement your own flutter plugins which does something like discussed here: 
https://stackoverflow.com/questions/4967669/android-install-apk-programmatically

As for the download progress in the notification bar, there is a guide here: 
https://developer.android.com/training/notify-user/display-progress.html

Here is a guide on how to develop a flutter package: https://flutter.io/developing-packages/

**Comment by Hixie** [comment]
We probably don't want to provide a first-party plugin for installing APKs, but a plugin to show download progress would be nice.

**Comment by welldone217** [comment]
it sound nice ^^

**Comment by stuartmorgan** [comment]
Given that there are no votes for this in the years since it was filed, this isn't something we would write a first-party plugin for.
