### ISSUE TITLE
[Impeller] Android Stable

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#144398]
The plan for the Q3 stable release is to enable Impeller by default on Vulkan capable Android devices with a fallback to Skia/OpenGLES on devices that are not Vulkan capable. A `flutter` tool command line flag and `AndroidManifest.xml` flag will be availalbe for users to opt-out of Impeller.

- [x] https://github.com/flutter/flutter/issues/137108
- [x] https://github.com/flutter/flutter/issues/138236
- [x] https://github.com/flutter/flutter/issues/139702
- [x] https://github.com/flutter/flutter/issues/142659
- [x] https://github.com/flutter/flutter/issues/123671

**Comment by chinmaygarde** [comment]
As of today, the plugin migration is blocked on the 3.22 release going live.

**Comment by zanderso** [comment]
Impeller is now the default on master channel on Vulkan-enabled Android devices, which is what this issue covered, so I will go ahead and close this.
