### ISSUE TITLE
[Impeller] checkerboardoffscreenlayers may not be fully wired up for Impeller.

### ISSUE THREAD

**Issue by bytebai920** [flutter/flutter#144382]
### Steps to reproduce

MaterialApp(
      title: '',
      checkerboardOffscreenLayers: true,
      builder:
.....

when use  flutter 2.0.6 widget border color changed

but use flutter 3.16.5 widget border color has no change

### Expected results

flutter 3.16.5  can check offscreen 

### Actual results

flutter 3.16.5  widget no color changed 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @bytebai920 
I don't have a such old Flutter version to check this. Could you check on a newly created Flutter project (counter app) and share a screenshots for both versions (old and the latest stable 3.19.2)? Thanks!

**Comment by bytebai920** [comment]
https://github.com/flutter/flutter/assets/14013454/6d27ac25-4e43-41c5-be0d-f19726a9e5fc


https://github.com/flutter/flutter/assets/14013454/0ec47a51-89a5-44de-bc1d-cc52e6dcee81

Center(
          child: ClipRect(
        child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
            child: Container(
              width: 300,
              height: 300,
              color: Colors.red.withOpacity(0.6),
            )),
      )),
create  flutter projects for flutter2.0.6 and flutter3.19.3,  and enable offscreencheck 

aterialApp(
      checkerboardOffscreenLayers: true,
      title: 'Flutter Demo',

flutter 2.0.6 can check offscreen in first video,but 3.19.3 can not check offscreen
I have a question, BackdropFilter will not cause offscreen in flutter 3.19.3

**Comment by huycozy** [comment]
Thanks for the update. I can see the same result on Android, iOS and macOS.

<details>
<summary>Complete sample code</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      checkerboardRasterCacheImages: true,
      title: 'Flutter Demo',
      home: NewWidget(),
    ),
  );
}

class NewWidget extends StatefulWidget {
  const NewWidget({
    super.key,
  });

  @override
  State<NewWidget> createState() => _NewWidgetState();
}

class _NewWidgetState extends State<NewWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ClipRect(
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
            child: Container(
              width: 300,
              height: 300,
              color: Colors.red.withOpacity(0.6),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {});
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 hours ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.21.0-9.0.pre.33, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.21.0-9.0.pre.33 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dd865ce476 (2 hours ago), 2024-03-17 20:24:27 -0400
    • Engine revision 89c7759639
    • Dart version 3.4.0 (build 3.4.0-242.0.dev)
    • DevTools version 2.33.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by huycozy** [comment]
@bytebai920 Sorry, I mistyped `checkerboardOffscreenLayers` with `checkerboardRasterCacheImages`. I just updated my sample code above. I see `checkerboardOffscreenLayers` is working as expected on Flutter stable 3.19.3. Could you retry this with this sample code and confirm?

**Comment by bytebai920** [comment]
I try your sample code, and it's same as the second video, but I excepted it would be the first video, click the button, the container flash

**Comment by huycozy** [comment]
I do more tests on different platforms as demo below, the issue only happens on iOS app target whilst it works on Android and macOS apps.

<details>
<summary>Demo (Android, iOS, macOS)</summary>

| Android | iOS | macOS |
| --------------- | --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/203cdc1a-f8d0-4340-8498-bfad58847084"/> | <video src="https://github.com/flutter/flutter/assets/104349824/e3b02b2d-2a47-4a7a-9001-9c5b1b8b1c0b"/> | <video src="https://github.com/flutter/flutter/assets/104349824/d91a3834-bb89-4224-bbe2-d178d1825249"/> 

</details>


I also checked this on Web, nothing is rendered and there is a crash stack trace as below:

<details>
<summary>Output error (Web)</summary>

```console
A Dart VM Service on Chrome is available at: http://127.0.0.1:56609/6rXwtSTjOo8=
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during a scheduler callback:
UnimplementedError

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
lib/_engine/engine/canvaskit/layer_scene_builder.dart 47:5                   addPerformanceOverlay
packages/flutter/src/rendering/layer.dart 1067:12                            addToScene
packages/flutter/src/rendering/layer.dart 712:5                              [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart 1378:12                            addChildrenToScene
packages/flutter/src/rendering/layer.dart 1995:5                             addToScene
packages/flutter/src/rendering/layer.dart 1130:5                             buildScene
packages/flutter/src/rendering/view.dart 252:30                              compositeFrame
packages/flutter/src/rendering/binding.dart 587:19                           drawFrame
packages/flutter/src/widgets/binding.dart 991:13                             drawFrame
packages/flutter/src/rendering/binding.dart 448:5                            [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1386:7                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1311:9                           handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1034:7                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:11      internalCallback
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: UnimplementedError
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:56609/6rXwtSTjOo8=

```
</details>

The sample code and flutter doctor output can be found at https://github.com/flutter/flutter/issues/144382#issuecomment-2002886336.

**Comment by bytebai920** [comment]
well done, I only test on iOS with flutter 3.19.3 and hope it can check offscreen on iOS with next  flutter version

**Comment by jmagman** [comment]
Framework team, any idea why this would be different per platform?

**Comment by jonahwilliams** [comment]
checkerboard offscreen layers may not be hooked up for impeller, or the rendering may not be offscreen in this particular case. Needs investigation.

**Comment by gaaclarke** [comment]
There already is code here to render the checkerboard ( https://github.com/flutter/engine/blob/f56c20c6ac674ceb571c06ce420749626a7d1e73/impeller/entity/entity_pass.cc#L1013 ) the `EntityPass::SetEnableOffscreenCheckerboard` isn't getting called though.

**Comment by gaaclarke** [comment]
There is a test for rendering the checkerboard ( `CanRenderOffscreenCheckerboard` ): https://flutter-engine-gold.skia.org/search?corpus=flutter-engine&include_ignored=false&left_filter=name%3Dimpeller_Play_AiksTest_CanRenderOffscreenCheckerboard_Metal&max_rgba=0&min_rgba=0&negative=true&not_at_head=false&positive=true&reference_image_required=false&right_filter=&sort=descending&untriaged=true

It doesn't appear to render correctly despite the flag being correctly set and I can see it attempting to be rendered.

**Comment by goderbauer** [comment]
@Hixie recently removed the entry points to this in https://github.com/flutter/flutter/pull/147663 and https://github.com/flutter/engine/pull/52446. So, this issue can probably be closed?

**Comment by gaaclarke** [comment]
> @Hixie recently removed the entry points to this in #147663 and [flutter/engine#52446](https://github.com/flutter/engine/pull/52446). So, this issue can probably be closed?

Yea, if that's the case we can close this.

@bytebai920 if you care about this feature you should file an issue explaining your perspective.  There was a decision made that this feature wasn't going to be supported.  I'm uninformed about why.  You might be able to get similar insights by using a gpu frame debugger.
