### ISSUE TITLE
Scenario app `skia-gold` does not work, or does not work as expected

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144352]
**STATUS**: Known issues are WIP:
- [x] https://github.com/flutter/flutter/issues/144657
- [ ] https://github.com/flutter/flutter/issues/144407
- [x] https://github.com/flutter/flutter/issues/144365
- [x] https://github.com/flutter/flutter/issues/144232
- [x] https://github.com/flutter/flutter/issues/145058

---

While I'm filing this with `e: scenario-app` it's possible the scope is beyond `scenario_app`. We are likely "holding it wrong", but it's catastrophic the way it's currently configured - we either turn the tree red because we didn't actually authorize all the digests (example 1), or we straight up miss digests that show incorrect behavior (example 2).

/cc @zanderso @dnfield

---

## Example 1: https://github.com/flutter/engine/pull/51061 merged, and turned the tree red.

![image](https://github.com/flutter/flutter/assets/168174/5734ce8f-f246-4e14-876e-2a6a26e70afb)

Only a [single image came up in the PR](https://flutter-engine-gold.skia.org/search?crs=github&issue=51061&negative=true&patchsets=4&positive=true), which was approved.

When it landed [post-submit turned the tree red](https://github.com/flutter/engine/pull/51073):

```txt
Debug information for Gold --------------------------------
stdout: Given image with hash 31dd46a724903b2ba29d64e579a691f1 for test PlatformTextureUiTests_testPlatformViewRotate
Expectation for test: 668bcdeda2f38520c865e639f535b05e (positive)
Expectation for test: 9eb7578aac2db40027790c7f57a2663f (positive)
Expectation for test: 2d6d812504637cb9638d70595733fa0c (positive)
Expectation for test: bbd9733e90b1c0fbde2f7c1689e85f48 (positive)
Expectation for test: fbfc2e60b6b93e5e99659d2674867bb3 (positive)
Expectation for test: af46302575b693eb83c40d2bee719017 (positive)
Expectation for test: 33930e542bfc4c1296f3ad1ad6c49cd2 (positive)
Expectation for test: 3022c9919e2bdef020c73bd1acfd7534 (positive)
Expectation for test: 6bd005faf9dc5939147ef2807c987256 (positive)
Expectation for test: 7d873804f96940f215a7c883d3f8fa4e (positive)
Expectation for test: da554cb3ec3966b1f1bd9c6afb229a45 (positive)
Expectation for test: fd830630715ae54de49c1341e17ad852 (positive)
Expectation for test: 2674732f5e64ea5aafcbd6d7e735bf19 (positive)
Fetching most recent positive digest for trace with ID "331c528375c030eeda1a0d4da269182d".
No recent positive digests for trace with ID "331c528375c030eeda1a0d4da269182d". This probably means that the test was newly added.
Non-exact image comparison using algorithm "fuzzy" against most recent positive digest "".
Untriaged or negative image: https://flutter-engine-gold.skia.org/detail?grouping=name%3DPlatformTextureUiTests_testPlatformViewRotate%26source_type%3Dflutter-engine&digest=31dd46a724903b2ba29d64e579a691f1

stderr: Test: PlatformTextureUiTests_testPlatformViewRotate FAIL
```

This should ... just never happen?

## Example 2: https://github.com/flutter/engine/pull/50730 generated images do not show up.

In https://github.com/flutter/engine/pull/50730, @chinmaygarde fixed/completed a feature for Impeller Vulkan and external textures. Once again, Skia gold _did_ pop up and ask for triage:

![image](https://github.com/flutter/flutter/assets/168174/0eeb2d9f-cae8-4a30-ad8f-74c8bc20d47e)

... but [the images aren't related to the patch](https://flutter-engine-gold.skia.org/search?crs=github&issue=50730&negative=true&patchsets=1&positive=true). I instead went looking [directly in the logs](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2060935/overview):

![image](https://github.com/flutter/flutter/assets/168174/9e3daed9-b547-4b76-bdab-45273fa74a58)

... and pulled out the _real_ golden change, which shows a bug not even shown by Skia gold:

![image](https://github.com/flutter/flutter/assets/168174/18abd9ca-5e6e-4f55-bf55-5cc89157a35c)

**Comment by matanlurey** [comment]
Trying to debug on CI with https://github.com/flutter/engine/pull/51078.

**Comment by chinmaygarde** [comment]
Update: As of https://github.com/flutter/engine/pull/50730#issuecomment-1977556004, I see the _real™_ golden changes show up as untriaged digests!

**Comment by chinmaygarde** [comment]
An instance of change being caught in postsubmit that we know should have been caught in presubmit.

* At 12:42 PM on , we [landed a patch](https://flutter.googlesource.com/mirrors/engine/+/6594bca63f3ffda94806546ef1907a4228e8d7db) with [no known untriaged digests](https://flutter-engine-gold.skia.org/search?issue=50730&crs=github&patchsets=1&corpus=flutter-engine) in presubmit.
* That patch subsequently [broke the tree in postsubmit](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_android_emulator_tests/4986/overview).
* The failure was in the [Android Scenario App Integration Tests](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8754273224794153905/+/u/test:_Android_Scenario_App_Integration_Tests__Impeller_Vulkan_/stdout).
* This failure showed up as an untriaged digest. The [result was accepted as positive at 2:18 PM](https://flutter-engine-gold.skia.org/detail?grouping=name%3DExternalTextureTests_testCroppedMediaSurface_bottomLeft%26source_type%3Dflutter-engine&digest=04da8c4d6822a1a46192779b2da4d9f6).
    * Note: The rendering looks incorrect but that is a known issue that is orthogonal to the Gold oddity described here.
* Confusion ensues as to how this escaped presubmit.
* We attempt to pull the images as generated before being submitted to [Skia Gold using the instructions here](https://github.com/flutter/engine/blob/155525c726f541fcef6e7f4698ab2642fc039d82/testing/scenario_app/android/README.md#my-test-is-failing-on-ci).
* The image pulled is attached below.
* This was same image that was triaged as accepted in post-submit but was not marked as untriaged in presubmit.

<img width="169" alt="Screenshot 2024-03-05 at 2 59 57 PM" src="https://github.com/flutter/flutter/assets/44085/f534e1b1-8bbc-49ea-91ca-d3af761ae785">

**Comment by chinmaygarde** [comment]
Whoa, additional weirdness. The result [that was accepted as positive at 2:18 PM](https://flutter-engine-gold.skia.org/detail?grouping=name%3DExternalTextureTests_testCroppedMediaSurface_bottomLeft%26source_type%3Dflutter-engine&digest=04da8c4d6822a1a46192779b2da4d9f6) used to show up as a positive (there were 4 images) when searching for all positives by test `ExternalTextureTests_testCroppedMediaSurface_bottomLeft`. But when I checked it a few mins after writing my comment, the [newly positive image is missing from the list](https://flutter-engine-gold.skia.org/search?left_filter=name%3DExternalTextureTests_testCroppedMediaSurface_bottomLeft&positive=true&untriaged=false). Only three positives are listed, all by @matanlurey more than two weeks ago.

Its as if the new positive was accepted as being a positive (the first link), but not listed in the full list of all positives.

I'm so confused :/

**Comment by jonahwilliams** [comment]
It looks like the PR https://github.com/flutter/engine/pull/50892 added new golden tests, we triaged them (or @gaaclarke did), autosubmit landed. THen the shard started failing as Skia gold had no images that were even similar: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/282083/overview

I would have expected that if the test were flakey or something, that we would see diffs - but these had no closest positive/negative at all

**Comment by gaaclarke** [comment]
Oh interesting, https://github.com/flutter/engine/pull/50892 did add golden tests.  Our test for output files verifies that the files were generated.  The presubmit check for flutter gold failed though to block the presubmit checks until they were uploaded to gold.  Since there was no blockage and no message about new goldens, I didn't triage them as part of landing that PR.

Yet notice that the flutter gold presubmit check is green.

**Comment by goderbauer** [comment]
This also seems to happen on the framework side: https://github.com/flutter/flutter/pull/144978 had some gold failures on the web that were triaged during presubmit. On postsubmit, new failures appeared when running with Impeller.

**Comment by matanlurey** [comment]
Closing as "completeenough".
