### ISSUE TITLE
IconButton.constraints does not apply the default constraints

### ISSUE THREAD

**Issue by jezsung** [flutter/flutter#144388]
### Steps to reproduce

As in the [doc](https://api.flutter.dev/flutter/material/IconButton/constraints.html), `IconButton.constraints` is supposed to apply the `BoxConstraints` with the `minWidth` and `minHeight` set to the `kMinInteractiveDimension ` when the `IconButton.constraints` property is not specified. 

This behavior has always resulted in the `IconButton` size being 48 in width and 48 in height when the other properties are not specified.

**However, the default constraints is not applied in the Flutter SDK version 3.19.0 which resulted in the `IconButton` size being 40 in width and 40 in height.**

### Expected results

`IconButton size being 48 in width and 48 in height

### Actual results

IconButton size being 40 in width and 40 in height

### Code sample

<details open><summary>Code sample</summary>

```dart
IconButton(
    icon: const Icon(Icons.menu),
    onPressed: () {},
) // 40 in width, 40 in height
```

```dart
IconButton(
    icon: const Icon(Icons.menu),
    constraints: const BoxConstraints(
        minWidth: kMinInteractiveDimension,
        minHeight: kMinInteractiveDimension,
    ),
    onPressed: () {},
) // Specifying the constraints resolves the issue, results in 48 in width and 48 in height
```

Flutter SDK version 3.19.0, Material3 is enabled by default. 
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by opxdelwin** [comment]
Hey @jezsung, Thanks for filing this issue. This button behavior looks expected, as the guidelines mention it. For default implementation, Refer `Container Size` of m3. By applying constraints, I believe we're adjusting the interactable `Container Size` itself.

If you believe it's inaccurate, I'd be more than happy to dive into the codebase!

See more: https://m3.material.io/components/icon-buttons/specs#e8988ae0-50d6-4192-929e-c4558bcac4e1

**Comment by jezsung** [comment]
@opxdelwin Thanks for your response!

I still have some confusion about what default behavior is expected when no other properties are specified except for the required ones.

Currently, the below code creates an `IconButton` with the size of 40w, 40h.
```dart
// Size 40w, 40h
IconButton(
    icon: const Icon(Icons.menu),
    onPressed: () {},
)
```

But as the [doc](https://api.flutter.dev/flutter/material/IconButton/constraints.html) says, if the `constraints` property is unspecified, it should default to:
```dart
const BoxConstraints(
  minWidth: kMinInteractiveDimension,
  minHeight: kMinInteractiveDimension,
)
```

If you were to specifiy the `contraints` with the above `BoxConstraints`, the size becomes 48w, 48h:

```
// Size 48w, 48h
IconButton(
    icon: const Icon(Icons.menu),
    onPressed: () {},
    constraints: const BoxConstraints(
        minWidth: kMinInteractiveDimension,
        minHeight: kMinInteractiveDimension,
    ),
)
```
The applied `BoxConstraints` must be the default value when the `contraints` is unspecified. But the above two `IconButton`s results in different sizes. I think either the doc has to be updated or the code needs to be fixed.

**Comment by huycozy** [comment]
@jezsung I would like to confirm this again.

>Currently, the below code creates an IconButton with the size of 40w, 40h.

I think you mean the constraint, right? Because I can see the rendered size is 48.0 from Devtools:
![Screenshot 2024-03-01 at 14 46 23](https://github.com/flutter/flutter/assets/104349824/a3cbcf73-fd32-4b10-abfb-4f66a93217e3)

Whereas, its min size is 40.0 for BoxConstraints in the tree:
![Screenshot 2024-03-01 at 14 55 28](https://github.com/flutter/flutter/assets/104349824/cfe7fa55-db08-4343-9587-bd9d71ae3b20)

**Comment by jezsung** [comment]
@huycozy I found it was due to the theme configuration `materialTapTargetSize` set to `MaterialTapTargetSize.shrinkWrap`. Is it supposed to shrink the `IconButton`s size too?  I've been using this setup for a quite long I have just noticed this change.

**Comment by huycozy** [comment]
@jezsung On mobile platforms, it's `MaterialTapTargetSize.padded` which is corresponding to 48x48px:

https://github.com/flutter/flutter/blob/d3c274b25540de40e17693ce6800454b5f32ecb8/packages/flutter/lib/src/material/theme_data.dart#L382-L391

>Is it supposed to shrink the IconButtons size too?

The default IconButton style (with M3 enabled) is getting `tapTargetSize` from Theme settings currently:

https://github.com/flutter/flutter/blob/d3c274b25540de40e17693ce6800454b5f32ecb8/packages/flutter/lib/src/material/icon_button.dart#L1193

So the solution is applying a style for your specific IconButton, for eg:

```dart
IconButton(
	icon: const Icon(Icons.menu),
	onPressed: () {},
	style: const ButtonStyle(
		tapTargetSize: MaterialTapTargetSize.padded,
	),
)
```

Then the button will has 48x48 size as expected. 

I'm going to close this as solved with this solution. If you disagree, please write in the comments and I will reopen it. Thanks!
