### ISSUE TITLE
interactive examples, inside the documentation, takes long to run

### ISSUE THREAD

**Issue by tempral** [flutter/flutter#144311]
### Use case

for the most common widgets, in the documentation page that describe it, are present one or more dartpad snippets.
But often the preview takes a considerable amount of time to get ready, and even sometimes don't show at all

### Proposal

in my opinion, at the beginning, readers would like to see the preview of the snippet without make any changes, so could be faster to load a precompiled example, without the necessity to run it

Only later provide server resouces to compile the source code if the consultant modify it

**Comment by darshankawar** [comment]
@tempral 
You'll need to report this in dedicated repo: https://github.com/dart-lang/dart-pad/issues
I see a similar [issue](https://github.com/dart-lang/dart-pad/issues/2499) open already in it that you can check and refer further.
Closing from here.

**Comment by tempral** [comment]
Ok
