### ISSUE TITLE
Would like a way to get skia gold results without all tests passing.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#144347]
Perhaps some sort of additional label?

Context: https://github.com/flutter/engine/pull/50856 has a bug where the depth attachments were misconfigured. A single test failed (correctly) in the flutter tester unit tests.

As a result, the golden tests did not report status back. Instead of seeing 100s of golden diffs that show an obvious rendering problem, we saw a single failure that sort of looked like a flake.

**Comment by zanderso** [comment]
Is there a LUCI run that you can link to that shows the undesirable behavior?

**Comment by zanderso** [comment]
Oh! Sorry, I misunderstood. This isn't an issue of a single failing presubmit. The issue is that if any *other* presubmit check fails, then `flutter-gold` doesn't run at all. Is that right?

**Comment by jonahwilliams** [comment]
Right. The failure was a correct failure. However it would have been easier to understand the failure if gold had been allowed to report back, since that contained more obvious cases.

**Comment by jonahwilliams** [comment]
This is partially related to the fact that it is difficult / impossible to use gold locally, so we really need CI to be usable in scenarios where other tests are failing.

As an analogy, consider the problem if CI stopped after a single test failure.

**Comment by Piinks** [comment]
The flutter-gold check is only a gatekeeper, you can always see any images Gold received from a PR listed under changelists: https://flutter-gold.skia.org/changelists (framework) or https://flutter-engine-gold.skia.org/changelists (engine)

If Gold receives an image from a test, it'll be represented there. The flutter-gold check is just a lookup that sees if there are new images and prevents folks from landing a change without addressing them.

**Comment by jonahwilliams** [comment]
If we're running them away way, then can we make the link easier to find? Part of the problem here is expectations. Of course if we were thinking "ok this test might fail" then we could check the skia gold link. but if you're not anticipating those kinds of failures then hiding the gold results is doing more harm than good.

**Comment by jonahwilliams** [comment]
At any rate, it sounds like not reporting the gold report is a policy decision and not a technical limitation?

**Comment by Piinks** [comment]
> If we're running them away way, then can we make the link easier to find?

For sure! I don't think the intention was to hide anything. How can we best surface the link?

Should the bot leave a comment along the lines of "This PR will execute golden file tests, any and all images can be seen [here] when tests have completed." when a PR is first opened? WDYT?

We've always leaned towards less bot noise, since in the past we have gotten complaints. Happy to make this change pretty easily though!

**Comment by jonahwilliams** [comment]
Sounds like I can just do this, and there are no technical blockers.
