### ISSUE TITLE
BUG: Missing local_auth_ios when Using flutter SDK 3.16.8 and local_auth: 2.12.2

### ISSUE THREAD

**Issue by nokia6290** [flutter/flutter#144372]
### Steps to reproduce

Setup flutter SDK 3.16.8
local_auth: ^2.1.2

Try running iOS and it will have an error of:

(android is working)

### Expected results

Run as expected on iOS

### Actual results

<img width="1069" alt="Screenshot 2024-02-29 at 3 10 00 pm" src="https://github.com/flutter/flutter/assets/13733620/058a419d-51cd-41f8-9e88-910c6bbabe3d">

I read the github comments that the plugin local_auth internal Swift classes were recently renamed to local_auth_darwin, but it seems like there are issues between latest changes.

After downgrading to 3.16.2 flutter SDK - the ios build worked as expected, and then I could even upgrade flutter to 3.16.8 and the old cache was working.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1069" alt="Screenshot 2024-02-29 at 3 10 00 pm" src="https://github.com/flutter/flutter/assets/13733620/e81751dc-f272-43c3-87bd-2aeb083ccfdf">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.1 23B74 darwin-arm64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @nokia6290, this might be an issue with your cache. Do you experience this issue if you add the local_auth plugin to a new project?

**Comment by nokia6290** [comment]
It was a brand new project from customer repository - pulled down and had this error from first run.

So I doubt its related to cache directly.

**Comment by danagbemava-nc** [comment]
I just tested the local_auth example app and it run for me just fine. Can you try upgrading to the latest version of flutter to see if you still experience this issue? If you do, please provide a complete minimal reproducible code sample so that we can investigate this issue. 

Thank you
