### ISSUE TITLE
Not able to write a file,image,video on android.media ,  and uninstalling the application is not been clearing

### ISSUE THREAD

**Issue by engineer-ece** [flutter/flutter#144312]
### Use case

want to write all data in android.media.com.example.app than android.data.

### Proposal

Not able to write a file,image ,video on android.media , 
while installing is added to the android.data, but I need to install on the android.media for insert the file,
 and uninstalling the application is not been clearing

### Exception

The following PathNotFoundException was thrown resolving an image codec:
Cannot retrieve length of file, path = 'storage/emulated/0/Android/media/FrameX_28-02-24/com.fieldlytics.frame/images/47772/Store Front Photo_true_Photo$1_84_image.jpg' (OS Error: No such file or directory, errno = 2)

When the exception was thrown, this was the stack: 
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:389:7)
<asynchronous suspension>
#2      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1588:31)
<asynchronous suspension>
Path: storage/emulated/0/Android/media/FrameX_28-02-24/com.fieldlytics.frame/images/47772/Store Front Photo_true_Photo$1_84_image.jpg
====================================================================================================
I/TRuntime.CctTransportBackend(16945): Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog

**Comment by darshankawar** [comment]
> images/47772/Store Front Photo_true_Photo$1_84_image.jpg'

@engineer-ece I see that there's a space in the image file name. Try to remove space and run your scenario again to see if it works or not.
Also, your issue is better suited for support channels like StackOverflow so please ask the same there.
If you think there's a bug you found in the framework, use new issue template, fill out requested details so that we can properly analyze it.
Closing for now.
