### ISSUE TITLE
Flutter can't build on Trusty-based Ubuntu

### ISSUE THREAD

**Issue by ErikCorryGoogle** [flutter/flutter#14438]
Since the buildtools roll in 4e1c51cc29e99ca5b398801cf1a4be965da22d4b
there is a link error with the old version of libGL on Trusty incl. Goobuntu.

**Comment by jason-simmons** [comment]
If you need a workaround, comment out this line in build/config/compiler/BUILD.gn:
`ldflags += [ "-Wl,--fatal-warnings" ]`

**Comment by ErikCorryGoogle** [comment]
I upgraded now, but I don't think the workaround works.  This is an error, not a warning.

**Comment by tvolkert** [comment]
I'm seeing this even with an upgraded gLinux and even with the workaround applied:

```
/usr/local/google/home/tvolkert/project/flutter/engine/src/out/host_debug/../../buildtools/linux-x64/clang/bin/ld.lld: error: unable to find library -lGL
/usr/local/google/home/tvolkert/project/flutter/engine/src/out/host_debug/../../buildtools/linux-x64/clang/bin/ld.lld: error: unable to find library -lGLU
```

**Comment by tvolkert** [comment]
With help from @jason-simmons the following got my env set up correctly:

```
sudo apt-get remove tex-gyre
sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev
```
