### ISSUE TITLE
Basic text widgets treated as tappable on Flutter web running on Android w/ Talkback

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#144364]
Copied from internal bug b/326943762

Non-selectable text widgets are intermittently treated as tappable objects in Flutter Web loaded in a browser on Android. This is an accessibility bug because we're incorrectly indicating to the user which items are interactable and which aren't, which is confusing.

This is reproable (though intermittently) in the embedded Dart Pad in https://api.flutter.dev/flutter/widgets/Text-class.html

See repro example:
![8Kf6X6dVsc4FT73 (1)](https://github.com/flutter/flutter/assets/6869388/f29e9c11-87e6-4062-b6a5-88c1945557b0)

**Comment by danagbemava-nc** [comment]
Labeling this for further investigation. 

I was able to reproduce it once when I opened the api docs on the website on my mobile browser but after refreshing the page, I wasn't able to reproduce it again. I also deployed a website with the code sample from the embedded dartpad to firebase hosting but with that I was never able to reproduce it.

**Comment by ChristianEdwardPadilla** [comment]
Matching g3 priority.

**Comment by yjbanov** [comment]
I haven't made any progress on this.

**Comment by yjbanov** [comment]
Starting working on this.
