### ISSUE TITLE
Document the focus handling system

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14430]
`FocusScope`, `FocusScopeNode`, `FocusNode`, `FocusManager` are all named similarly and it's hard to figure out what does what and how to use them. 

Create a diagram illustrating their relationships or create a code example demonstrating how to do common tasks using them in concert.

**Comment by xster** [comment]
Would be nice to have a focus tree debug print mechanism like dumbing the widget tree as well

**Comment by zoechi** [comment]
Should this be moved to flutter/website?
It sounds like there are also framework/tooling parts. Should these be tackled first?
Should I copy it to flutter/website instead of moving?

**Comment by xster** [comment]
Also cc @HansMuller who's running into this right now. 

Let's leave it here for API docs for now.

**Comment by Piinks** [comment]
@gspencergoog added a whole bunch of docs and sample apps around these classes a few months ago. :)
If there is still work to be done here, feel free to reopen! :)
