### ISSUE TITLE
When status bar is hidden, app bar's height remains the same

### ISSUE THREAD

**Issue by deborah-ufw** [flutter/flutter#14432]
## Steps to Reproduce

In a view, status bar is hidden...

```
if (ChqMeasurements.isLandscapePhone(context)) {
      SystemChrome.setEnabledSystemUIOverlays([]);
    } else {
      SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
    }
```
However, the app bar's height does not change. App bar just has more space at the top. Material Widget AppBar does not recognize property "preferredSize", so it can't be manually adjusted with that.

Since the purpose of hiding status bar is usually to get more screen space, this seems like a bug.

**Comment by Hixie** [comment]
cc @cbracken who may have this still paged in and know what's up

**Comment by cbracken** [comment]
@deborah-ufw thanks for reporting this. To help figure out what’s going on, which version of iOS are you seeing this behaviour on, and which device model (or simulator)? The iOS APIs we use to determine status bar height are quite specific to the underlying version of iOS. Could you also include the output of `flutter doctor` — that’ll help narrow us reproduce this.

**Comment by deborah-ufw** [comment]
Hi Chris, it’s in Android.  Flutter doctor is all green checkmarks, but here’s the log…

Deborahs-MBP:chq_emulator deborah$ flutter doctor
[✓] Flutter (on Mac OS X 10.13.2 17C205, locale en-US, channel alpha-chq)
    • Flutter version 0.0.21-pre.7 at /Users/deborah/flutter
    • Framework revision d146556ebb (2 days ago), 2018-02-01 17:47:56 -0800
    • Engine revision 8f2d72b183
    • Tools Dart version 2.0.0-dev.20.0
    • Engine Dart version 2.0.0-edge.7af4db0ea091dddca6b2da851e6dda8d7f9467e8

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Deborah/Library/Android/sdk
    • Android NDK at /Users/Deborah/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/Deborah/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[✓] Connected devices
    • iPhone • b08050db65c1aecd9eda3ffc2bd8a89148c82a46 • ios • iOS 11.2.5

**Comment by netsmertia** [comment]
I have the same issue, Statusbar is hidden but space of status bar is not cleared. navbar looks bigger now.

**Comment by miguelcaravantes** [comment]
i have the same issue

**Comment by levrik** [comment]
Same also happens on Android

**Comment by Juhlinus** [comment]
I too have this issue.

**Comment by Hixie** [comment]
Does it fix itself if you rotate the phone? Does it fix itself if you do a hot reload?

**Comment by Juhlinus** [comment]
Yes, rotating the phone to landscape mode will fix the issue whilst being
in that mode. If rotating back to portrait mode then the issue persists.

**Comment by levrik** [comment]
@Hixie I have Android installed on an Raspberry Pi so I cannot rotate it. It doesn't fix itself on a hot reload.

**Comment by Hixie** [comment]
Sounds like we're not correctly updating the window metrics when the chrome style changes.

**Comment by abinvp** [comment]
I too have the same issue. Status bar is cleared but the space remains there.

**Comment by hassansaleh31** [comment]
Same here

**Comment by Vasanthkesavan** [comment]
Any work around to fix this?

**Comment by Rockvole** [comment]
The workaround to disable the status bar doesnt work at all on the Android Studio emulator Pixel C API 25.
Also, this is the only device I have available to meet the play store requirements for a 10" tablet screenshot.

**Comment by alisson226** [comment]
I'm having this issue too! Is there any workarounds?

**Comment by coletz** [comment]
I've had the same issue (only on android). A workaround is to put android itself in fullscreen mode, so add the following code to your MainActivity after the `super.onCreate`:
Kotlin:
```kotlin
window.setFlags(android.view.WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS, android.view.WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS)
```
Java:
```java
getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS, android.view.WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS)
```

**Comment by GaryQian** [comment]
This should be the same root issue as https://github.com/flutter/flutter/issues/18671

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/6282 fixes this problem for Android. A similar fix for iOS should exist and I will look into it.

**Comment by GaryQian** [comment]
I was informed that the iOS bug was fixed recently. Is anyone still having issues with the iOS top padding?

**Comment by dark-chocolate** [comment]
To all my friends, please upvote the issue instead of saying "Same here" so that Flutter team can put it on higher priority. Thank you :)

**Comment by dark-chocolate** [comment]
@zoechi Please open this issue cause it hasn't been solved.

**Comment by zoechi** [comment]
@dark-chocolate There was no response to https://github.com/flutter/flutter/issues/14432#issuecomment-426110227 that indicates there is still work to do. 
@GaryQian what do you think?

**Comment by GaryQian** [comment]
The fixes that were merged in resolves the issue in most cases. If there are any edge cases/other related bugs, please let us know.

**Comment by dark-chocolate** [comment]
@GaryQian  I am sorry but I am newbie to Github, I didn't get what you meant by merging. Please provide a link or code that helps in solving this issue. Thanks

**Comment by zoechi** [comment]
Merged means that a proposed change was accepted and added into the master branch of the source code.

![image](https://user-images.githubusercontent.com/405837/47636421-82a11580-db58-11e8-9065-ce8d8d0f2556.png)

See also https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by 1AlexFix1** [comment]
@GaryQian 

Good day! sorry for my English
See the files that best convey my thoughts on the current error.
Pay attention to the logs
The code I used to demonstrate here: https://flutter.io/cookbook/navigation/navigation-basics/

Video_1 shows how flutter works without SystemChrome.setEnabledSystemUIOverlays ([]);
![video_1_720](https://user-images.githubusercontent.com/44409006/47945527-ac20bf00-df13-11e8-869f-b9c593ce80d5.gif)

In video_2, note that when you enable full_screen after deploying an application from the tray, called function build for Widget only on the second screen (this is somehow related to navigation). Also note that when the application goes to the tray, the text inside moves down the top bar.
![video_2_720](https://user-images.githubusercontent.com/44409006/47945528-ac20bf00-df13-11e8-98a2-0cc1fdccf5fd.gif)

Video_3 describes how to enable full_screen android, but the bottom panel is not hidden! Although these methods work in the development area for Android, only the top pane is hidden. In addition, when the application is in the tray, the text transition is absent, and not as in Video_2d.
![video_3_720](https://user-images.githubusercontent.com/44409006/47945526-ac20bf00-df13-11e8-802f-1fa33e158221.gif)

I hope I helped with something.

**Comment by GaryQian** [comment]
So with `SystemChrome.setEnabledSystemUIOverlays(...)` you can actually specify that the bottom nav bar not be hidden. by passing in `[]`, you are saying that you want **all** UI elements to be hidden whenever possible. (see https://docs.flutter.io/flutter/services/SystemChrome/setEnabledSystemUIOverlays.html)

The part of the issue where the button shifts in position can be considered a real bug though. Since in preview mode, the screen size is different, it no longer satisfies the heuristic-based check (Android apparently does not support programmatic UI detection) that detects the navbar being hidden, so the UI adjusts itself to fit. I believe this should be filed as a separate bug though. If you want, you can file a github issue on it. I will take a look when I get a chance.

**Comment by 1AlexFix1** [comment]
Thanks, I also found another problem with the lower bar, I will describe everything in a separate topic.

**Comment by josvos** [comment]
Can this issue be re-opened?  I have an issue on Android that is probably the same.  The characteristiscs:

*  After doing `SystemChrome.setEnabledSystemUIOverlays([])`, the bottom bar disappears and the top (status) bar is also gone, but the *space* of (only) the top bar remains reserved (i.e. is black and not used by the app).

*  After hitting `r` in the console (hot reload) the top bar space is released and the screen looks as expected!  From then, switching between modes (enable/disable system bars) seems to work ok, also without further hot reloads.

*  So far I have only seen the problem in debug mode, not on release mode.

```
[✓] Flutter (Channel dev, v0.11.7, on Linux, locale en_US.UTF-8)
    • Flutter version 0.11.7 at /home/jos/flutter1/flutter
    • Framework revision 7a005e1dcd (21 hours ago), 2018-11-19 11:14:05 -0500
    • Engine revision 2e06da3df9
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/jos/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /home/jos/flutter1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.
```

**Comment by NikhilCodes** [comment]
```
Scaffold(
      resizeToAvoidBottomPadding: false,
```
solves this issue!
