### ISSUE TITLE
Support the gap property

### ISSUE THREAD

**Issue by dominictobias** [flutter/flutter#144310]
### Use case

The `gap` property is one of the greatest properties to be added to CSS in the last decade and goes hand-in-hand with flex layout.

Not having it is jarring to web developers, and solutions like SizeBox in between feels ugly, verbose, and primitive - the whole point of gap is that you don't have to check the index of your elements and add special handling:
- if it's the first element
- if it's the last element
- if it's the only element

Making the user do that whenever they use a Row or Column is messy, inelegant, and time consuming.

React native and any modern flex layout engine like Dioxus' Taffy or Lapce's Floem support the gap property:
https://reactnative.dev/docs/flexbox#row-gap-column-gap-and-gap
https://github.com/DioxusLabs/taffy/blob/main/examples/flexbox_gap.rs#L15
https://github.com/lapce/floem/blob/341afd255f98ca431e4f615864daa4dbcc057501/examples/widget-gallery/src/slider.rs#L31

### Proposal

Support the gap property

**Comment by sekoyo** [comment]
> This would solve it elegantly also I think: [letsar/gap#19](https://github.com/letsar/gap/pull/19)

Oh cool yes it would, I’ll track that PR thanks

**Comment by darshankawar** [comment]
Closing based on above comment.
