### ISSUE TITLE
impossible to produce Wasm-only Web build using Flutter tool

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#144389]
### Steps to reproduce

0. Get a main branch of Flutter
1. Build a Web application using `flutter build web --wasm`
2. Run it in the browser

### Expected results

Expect it to use Wasm version

### Actual results

Actually loads dart2js version

**Comment by darshankawar** [comment]
Was able to replicate the reported behavior.

**Comment by eyebrowsoffire** [comment]
The output of `flutter build web --wasm` is a dual-compiled build, and it requires use of the new bootstrapping APIs. Don't write your own bootstrapper please. See the docs here: https://docs.flutter.dev/platform-integration/web/wasm and here https://docs.flutter.dev/platform-integration/web/bootstrapping
