### ISSUE TITLE
Add a prefix to files output to `${FLUTTER_LOGS_DIR}`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144402]
I unfortunately misunderstood how `${FLUTTER_LOGS_DIR}` works, and have been overwriting my own outputs 😢:

1. Any task in the same builder writes to the same directory

    If `task A` writes `foo.txt`, and `task B` writes `foo.txt`, then `task A`'s `foo.txt` is silently overwritten.

2. Re-runs (i.e. due to failures or timeouts) have the same property

    If `task A (run 1)` fails, a successful `task A (run 1)` will overwrite the logs of the failed entry.

This is all made extra confusing by the fact the [UI shows multiple log uploads](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/617919/overview), as if they might be different:

<img width="442" alt="Screenshot 2024-02-29 at 9 10 17 AM" src="https://github.com/flutter/flutter/assets/168174/dd2dbca9-0440-4508-9990-7840999063c5">

Special thanks to @keyonghan for [explaining this all to me here on Discord](https://discord.com/channels/608014603317936148/1212801698305941524).

**Comment by jmagman** [comment]
If you do that generically in https://github.com/flutter/flutter/blob/ab4bf7c1c91533964ceb71c6506a31100981e238/dev/devicelab/lib/framework/host_agent.dart places that already add timestamps can be removed:
https://github.com/flutter/flutter/blob/ab4bf7c1c91533964ceb71c6506a31100981e238/dev/devicelab/lib/framework/ios.dart#L229

There are other spots we're likely overriding files: https://github.com/flutter/flutter/blob/ab4bf7c1c91533964ceb71c6506a31100981e238/dev/devicelab/lib/tasks/perf_tests.dart#L1053-L1055

**Comment by matanlurey** [comment]
To be clear this is in `flutter/engine` where we don't have access to `flutter/dev`.

**Comment by jmagman** [comment]
Oh, right, sorry for the noise 🙂

**Comment by matanlurey** [comment]
I appreciate your noise.
