### ISSUE TITLE
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed.

### ISSUE THREAD

**Issue by 540765** [flutter/flutter#144460]
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#1da73(physicalKey: PhysicalKeyboardKey#b9a3b(usbHidUsage: "0x0007001a", debugName: "Key W"), logicalKey: LogicalKeyboardKey#510a7(keyId: "0x00000077", keyLabel: "W", debugName: "Key W"), character: null, timeStamp: 2:25:36.443433)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

//=======================================================================================

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:954:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:214:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#8      _invoke2 (dart:ui/hooks.dart:183:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)

**Comment by huycozy** [comment]
Hi @540765 
Based on the stack trace, the error came from this assertion:

```dart
assert(_pressedKeys.containsKey(event.physicalKey),
          'A ${event.runtimeType} is dispatched, but the state shows that the physical '
          'key is not pressed. $common$event');
```

But we still need a reproduction case to replicate this issue, please provide the following information:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)

This could be similar to https://github.com/flutter/flutter/issues/125975
