### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'GoogleMaps/GoogleMaps.h' file not found

### ISSUE THREAD

**Issue by viodrz** [flutter/flutter#144462]
### Steps to reproduce

rm -rf Pods Podfile.lock
pod cache clean --all  
flutter pub cache clean

After upgrading Flutter to version 3.19.1 and google_maps_flutter: ^2.6.0, I keep getting the error 'Lexical or Preprocessor Issue (Xcode): 'GoogleMaps/GoogleMaps.h' file not found', whereas it was fine before.I have followed the steps above but still unsuccessful.  Is there any solution?

### Expected results

running on ios simulator

### Actual results

failed to running always getting error "Lexical or Preprocessor Issue (Xcode): 'GoogleMaps/GoogleMaps.h' file not found"

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="372" alt="Screenshot 2024-03-01 at 14 04 57" src="https://github.com/flutter/flutter/assets/11739087/06834433-1f5a-4dca-b0bc-aa513a131068">

<img width="262" alt="image" src="https://github.com/flutter/flutter/assets/11739087/112e3776-2366-404f-92a7-7002fc882efe">

<img width="1680" alt="image" src="https://github.com/flutter/flutter/assets/11739087/3681e7b8-aed1-47a9-adde-fb04917d97c3">

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Xcode build done.                                           34.9s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'GoogleMaps/GoogleMaps.h' file not found
/Users/.pub-cache/hosted/pub.dev/google_maps_flutter_ios-2.5.0/ios/Classes/GoogleMapPolylineController.h:5:8
GoogleMapPolylineController.h:5

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

Exited (1).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-ID)
    • Flutter version 3.19.1 on channel stable at /Users/violettasuryapratama/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (9 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/violettasuryapratama/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • iPhone 15 Pro Max (mobile) • 4A887649-A410-4905-9113-5C1FA4A8095C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 122.0.6261.69
    ! Error: Browsing on the local area network for IT’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Hi @viodrz 
I just upgraded the package to the latest version (`google_maps_flutter: ^2.6.0`, `google_maps_flutter_ios: ^2.5.0`) but can't see it on my end (on iPhone 15 Pro, iOS 17.0).

For the error showing on XCode, could you confirm you selected `Runner.xcworkspace` on `ios` module instead of `Runner.xcodeproj`? 

Could you provide the entire output of `flutter run -v` which may has some more info? Thank you!

**Comment by viodrz** [comment]
> Hi @viodrz I just upgraded the package to the latest version (`google_maps_flutter: ^2.6.0`, `google_maps_flutter_ios: ^2.5.0`) but can't see it on my end (on iPhone 15 Pro, iOS 17.0).
> 
> For the error showing on XCode, could you confirm you selected `Runner.xcworkspace` on `ios` module instead of `Runner.xcodeproj`?
> 
> Could you provide the entire output of `flutter run -v` which may has some more info? Thank you!

Answer:
Yes, I selected Runner.xcworkspace to running app, the result always error like this /Users/.pub-cache/hosted/pub.dev/google_maps_flutter_ios-2.5.0/ios/Classes/GoogleMapPolylineController.h:6:9 'GoogleMaps/GoogleMaps.h' file not found


this is result flutter run -v command: 
<img width="1214" alt="image" src="https://github.com/flutter/flutter/assets/11739087/279ed3b2-dc67-4e16-b881-837de46500be">

**Comment by viodrz** [comment]
this is pod file:
[Podfile.txt](https://github.com/flutter/flutter/files/14468108/Podfile.txt)

**Comment by huycozy** [comment]
I'm not sure if you solved the issue or not (issue is closed). Can you try adding maps plugin on a newly created Flutter project to see if there is the same error? 

If the issue still persists, please provide the entire output log of `flutter run -v` in text format instead of a screenshot for better readability and investigation; if the logs are too large to be uploaded to GitHub, you may upload them as a txt file or use online tools like https://pastebin.com/ to share it. Thank you!

**Comment by AhmadFayyas** [comment]
@huycozy facing the same issue on a brand new Flutter project. Here is the output of `flutter run -v`:
https://pastebin.com/eJ5aqFuE

The main error (Debug Console):
<img width="1372" alt="Screenshot 2024-03-13 at 3 25 04 AM" src="https://github.com/flutter/flutter/assets/15219320/3d0d114a-9853-41bc-a681-eafaf81e77ba">

Please advise.
