### ISSUE TITLE
EXCEPTION CAUGHT BY SCHEDULER LIBRARY

### ISSUE THREAD

**Issue by binkapS** [flutter/flutter#144471]
### Steps to reproduce

Navigate to a page

Using a PopScope widget Handle device Back gestures

When a user uses the back button
Show a A Dialog warning they will loose progress if they proceed

If they decide to still quite
Close the dialog and pop the page

Many of the issues i have seen were solved by call the pop as a postFrameworkCallback
I have even tried a Using a future with delay but i still get the same result

### Expected results

Pop The Dialog and Pop the page after that... The Dialog was to prevent user from closing the page without saving current progress

By the way below is the extension that handles the back(context.back());

void back({bool dialog = false}) => Navigator.of(this).pop(dialog);

### Actual results

When i click Yes and Execute 

 context.back();
                    WidgetsBinding.instance
                        .addPostFrameCallback((_) => context.back());

Both the dialog and page closes but Navigator throws an exception when i try to use it;
Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed
assertion: line 4821
                      pos 12: '!_debugLocked': is not true.

### Code sample

<details open><summary>Code sample</summary>

```dart
// By the way below is the extension that handles the back(context.back());
extension AppContext on BuildContext {

void back({bool dialog = false}) => Navigator.of(this).pop(dialog);
}

// Below is the Widget
class StudyQuestions extends StatelessWidget {
  const StudyQuestions({
    super.key,
    required this.controller,
  });

  final StudyQuestionsController controller;

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text(
          "${controller.course.name} ${controller.course.code}",
          style: const TextStyle(
            color: AppColors.primary,
          ),
        ),
      ),
      child: PopScope(
        canPop: false,
        onPopInvoked: (didPop) {
          if (didPop) {
            return;
          }
          showCupertinoDialog(
            barrierDismissible: true,
            useRootNavigator: false,
            context: context,
            builder: (context) => CupertinoAlertDialog(
              title: const Text(
                'Are sure you want quit?',
                style: TextStyle(
                  color: AppColors.primary,
                ),
              ),
              content: const Text(
                'You will loose your current progress',
                style: TextStyle(
                  color: AppColors.secondary,
                ),
              ),
              actions: [
                CupertinoDialogAction(
                  isDestructiveAction: true,
                  onPressed: () {
                    context.back();
                    WidgetsBinding.instance
                        .addPostFrameCallback((_) => context.back());
                  },
                  child: const Text(
                    'Yes',
                    style: TextStyle(
                      color: AppColors.danger,
                    ),
                  ),
                ),
                CupertinoDialogAction(
                  isDefaultAction: true,
                  onPressed: () {
                    context.back();
                  },
                  child: const Text(
                    'No',
                    style: TextStyle(
                      color: AppColors.active,
                    ),
                  ),
                ),
              ],
            ),
          );
        },
        child: Padding(
          padding: const EdgeInsets.all(10),
          child: Column(
            children: [
              SizedBox(
                width: (context.width * .45),
                child: SelectInputComponent(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 10,
                    vertical: 10,
                  ),
                  decoration: BoxDecoration(
                    color: AppColors.secondary.withOpacity(.75),
                    borderRadius: BorderRadius.circular(5),
                  ),
                  suffix: true,
                  style: const TextStyle(
                    color: AppColors.primary,
                    fontWeight: FontWeight.w400,
                    fontSize: 14,
                  ),
                  controller: controller.yearController,
                  placeholder: 'Course',
                  builder: (item) => Text(
                    "${item.name}",
                    style: const TextStyle(
                      color: AppColors.primary,
                      fontWeight: FontWeight.w400,
                      fontSize: 14,
                    ),
                  ),
                  toLabel: (item) => item.name.toString(),
                ),
              ),
              Expanded(
                child: SingleChildScrollView(),
              ),
              LoadingButton(
                onPressed: () {},
                controller: controller.buttonController,
                child: const Text(
                  'Submit',
                  style: TextStyle(
                    color: AppColors.background,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
A Dart VM Service on Infinix X669 is available at: http://127.0.0.1:38281/eKslAc4jHRk=/
The Flutter DevTools debugger and profiler on Infinix X669 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:38281/eKslAc4jHRk=/
I/gralloc4(18004): register: id=27a00004bb5
I/gralloc4(18004): register: id=27a00004bb6

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4821 pos 12: '!_debugLocked':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      NavigatorState._pushEntry (package:flutter/src/widgets/navigator.dart:4821:12)
#3      NavigatorState.push (package:flutter/src/widgets/navigator.dart:4778:5)
#4      showCupertinoDialog (package:flutter/src/cupertino/route.dart:1286:65)
#5      StudyQuestions.build.<anonymous closure> (package:edyfy/view/user/study/questions.dart:31:11)
#6      ModalRoute.onPopInvoked (package:flutter/src/widgets/routes.dart:1578:30)
#7      _RouteEntry.pop (package:flutter/src/widgets/navigator.dart:3116:11)
#8      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5290:13)
#9      AppContext.back (package:edyfy/extension/context.dart:18:58)
#10     StudyQuestions.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous
closure> (package:edyfy/view/user/study/questions.dart:54:62)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1322:11)
#13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#14     _invoke (dart:ui/hooks.dart:312:13)
#15     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#16     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on Ubuntu 22.04.4 LTS 6.5.0-18-generic, locale en_NG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
@binkapS Your example is a production sample code, there are some undefined classes. 

I use [PopScope](https://api.flutter.dev/flutter/widgets/PopScope-class.html)'s sample code but don't see the issue (checked on Android device with virtual back button). Please also use it and confirm. 

If the issue only occurs on your project, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

**Comment by binkapS** [comment]
```dart

// My Apologies But the Code below should reproduce the problem
// Copy and paste it in the main function 

import 'package:flutter/cupertino.dart';

void main() {
  runApp(const MainApp());
}

extension AppContext on BuildContext {
  void to(Widget page) => Navigator.of(this).push(
        CupertinoPageRoute(
          builder: (context) => page,
          fullscreenDialog: true,
        ),
      );

  void back({bool dialog = false}) => Navigator.of(this).pop(dialog);
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: CupertinoPageScaffold(
        child: Center(
          child: CupertinoButton(
            minSize: 0,
            color: CupertinoColors.activeBlue,
            padding: const EdgeInsets.all(15),
            child: const Text(
              'Navigate',
            ),
            onPressed: () => context.to(const StudyQuestions()),
          ),
        ),
      ),
    );
  }
}

class StudyQuestions extends StatelessWidget {
  const StudyQuestions({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text(
          "Page Title",
        ),
      ),
      child: SafeArea(
        child: PopScope(
          canPop: false,
          onPopInvoked: (didPop) {
            if (didPop) {
              return;
            }
            showCupertinoDialog(
              barrierDismissible: true,
              useRootNavigator: false,
              context: context,
              builder: (context) => CupertinoAlertDialog(
                title: const Text(
                  'Are sure you want quit?',
                ),
                content: const Text(
                  'You will loose your current progress',
                ),
                actions: [
                  CupertinoDialogAction(
                    isDestructiveAction: true,
                    onPressed: () {
                      context.back();
                      WidgetsBinding.instance
                          .addPostFrameCallback((_) => context.back());
                    },
                    child: const Text(
                      'Yes',
                    ),
                  ),
                  CupertinoDialogAction(
                    isDefaultAction: true,
                    onPressed: () {
                      context.back();
                    },
                    child: const Text(
                      'No',
                    ),
                  ),
                ],
              ),
            );
          },
          child: const Center(
            child: Text(
              'Some Text',
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by binkapS** [comment]
> 
> ```dart
> 
> // My Apologies But the Code below should reproduce the problem
> // Copy and paste it in the main function 
> 
> import 'package:flutter/cupertino.dart';
> 
> void main() {
>   runApp(const MainApp());
> }
> 
> extension AppContext on BuildContext {
>   void to(Widget page) => Navigator.of(this).push(
>         CupertinoPageRoute(
>           builder: (context) => page,
>           fullscreenDialog: true,
>         ),
>       );
> 
>   void back({bool dialog = false}) => Navigator.of(this).pop(dialog);
> }
> 
> class MainApp extends StatelessWidget {
>   const MainApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return CupertinoApp(
>       home: CupertinoPageScaffold(
>         child: Center(
>           child: CupertinoButton(
>             minSize: 0,
>             color: CupertinoColors.activeBlue,
>             padding: const EdgeInsets.all(15),
>             child: const Text(
>               'Navigate',
>             ),
>             onPressed: () => context.to(const StudyQuestions()),
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class StudyQuestions extends StatelessWidget {
>   const StudyQuestions({
>     super.key,
>   });
> 
>   @override
>   Widget build(BuildContext context) {
>     return CupertinoPageScaffold(
>       navigationBar: const CupertinoNavigationBar(
>         middle: Text(
>           "Page Title",
>         ),
>       ),
>       child: SafeArea(
>         child: PopScope(
>           canPop: false,
>           onPopInvoked: (didPop) {
>             if (didPop) {
>               return;
>             }
>             showCupertinoDialog(
>               barrierDismissible: true,
>               useRootNavigator: false,
>               context: context,
>               builder: (context) => CupertinoAlertDialog(
>                 title: const Text(
>                   'Are sure you want quit?',
>                 ),
>                 content: const Text(
>                   'You will loose your current progress',
>                 ),
>                 actions: [
>                   CupertinoDialogAction(
>                     isDestructiveAction: true,
>                     onPressed: () {
>                       context.back();
>                       WidgetsBinding.instance
>                           .addPostFrameCallback((_) => context.back());
>                     },
>                     child: const Text(
>                       'Yes',
>                     ),
>                   ),
>                   CupertinoDialogAction(
>                     isDefaultAction: true,
>                     onPressed: () {
>                       context.back();
>                     },
>                     child: const Text(
>                       'No',
>                     ),
>                   ),
>                 ],
>               ),
>             );
>           },
>           child: const Center(
>             child: Text(
>               'Some Text',
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> ```

**Comment by binkapS** [comment]
@huycozy I really appreciate you time, I figure out a workaround

Provide the Root Widget CupertinoApp with a GlobalKey<NavigatorState> Which i declared in a Singleton

Then use the key.currentContext for the navigation and it worked
My apologies if i wasted your time... But i really appreciate

**Comment by huycozy** [comment]
You are welcome. Glad you solved it.
