### ISSUE TITLE
[Impeller] The API should disallow creating separate depth and stencil attachments.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#144422]
This is only available when using extensions in Vulkan and it tricky to do in other APIs as well. We should not allow this usage.

**Comment by bdero** [comment]
FYI the depth and stencil is [combined](https://github.com/flutter/engine/blob/c0fe000f19d0d54775f12917e05a16ad330bcddb/lib/gpu/lib/src/render_pass.dart#L26-L46) in Flutter GPU.

Do any backends actually support having a depth and stencil attachments with separate textures? IIRC Metal throws a validation error when you do this, but maybe that's just for a subset of devices.

**Comment by chinmaygarde** [comment]
I don't think this is something we should support out of the box. Support is extremely spotty.
