### ISSUE TITLE
[Impeller] 7% `animated_advanced_blend_perf__timeline_summary`:`average_frame_build_time_millis` regression

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#144401]
introduced in https://github.com/flutter/engine/pull/50990

[skia perf](https://flutter-flutter-perf.skia.org/e/?keys=Xde34077be0c0ea195a5027b0f4d8c823&selected=commit%3D39590%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_build_time_millis%252Ctest%253Danimated_advanced_blend_perf__timeline_summary%252C&xbaroffset=39590)

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
I think this is a return to baseline, the raster times dramatically improved on that patch:

https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DPixel_7_Pro%26sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Danimated_advanced_blend_perf__timeline_summary&selected=commit%3D39590%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_frame_rasterizer_time_millis%252Ctest%253Danimated_advanced_blend_perf__timeline_summary%252C

I suspect a combination of the raster thread sleeping less and/or more frames being rendered
