### ISSUE TITLE
[Impeller] mask blur with gradient doesn't render correctly for inner/outer blur styles

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#144449]
## reproduction
```c++
TEST_P(AiksTest, GaussianBlurStyleInnerGradient) {
  Canvas canvas;
  canvas.Scale(GetContentScale());

  canvas.DrawPaint({.color = Color(0.1, 0.1, 0.1, 1.0)});

  Paint paint;
  paint.color = Color::Green();
  paint.mask_blur_descriptor = Paint::MaskBlurDescriptor{
      .style = FilterContents::BlurStyle::kInner,
      .sigma = Sigma(30),
  };

  std::vector<Color> colors = {Color{0.0, 0.7, 0.8, 1.0},
                               Color{0.0, 0.8, 0.7, 1.0}};
  std::vector<Scalar> stops = {0.0, 1.0};

  paint.color_source =
      ColorSource::MakeLinearGradient({0, 0}, {200, 200}, std::move(colors),
                                      std::move(stops), Entity::TileMode::kRepeat, {});

  canvas.DrawPath(PathBuilder()
                      .MoveTo({200, 200})
                      .LineTo({300, 400})
                      .LineTo({100, 400})
                      .Close()
                      .TakePath(),
                  paint);

  // Draw another thing to make sure the clip area is reset.
  Paint red;
  red.color = Color::Red();
  canvas.DrawRect(Rect::MakeXYWH(0, 0, 200, 200), red);

  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```

## observed output
<img width="1025" alt="Screenshot 2024-02-29 at 5 42 23 PM" src="https://github.com/flutter/flutter/assets/30870216/412c7014-b498-41d4-aedf-bdaf32f97320">

**Comment by jonahwilliams** [comment]
For gradients I'd suspect the problem is that we might be computing the start/end offsets incorrectly?

**Comment by jonahwilliams** [comment]
unless they work with normal blurs for some reason...

**Comment by bdero** [comment]
Nah there's a problem specific to the new blur styles being added in https://github.com/flutter/engine/pull/51018. This is how kNormal renders prior to the patch:

![image](https://github.com/flutter/flutter/assets/919017/effcdd3a-0919-4f3f-9d02-3024f3ee834a)

**Comment by gaaclarke** [comment]
> This is how kNormal renders prior to the patch:

clarification : it's also how it renders after the patch if you use BlurStyle::kNormal

**Comment by gaaclarke** [comment]
It looks like maybe just the x and y coordinates are 2x.  That little strip of blue may be the top of the triangle showing up.

**Comment by gaaclarke** [comment]
So the offset is coming because the `AnonymousContent`'s entity is getting set later on.  This can be fixed by multiplying the `shared_blur_entity`'s transform by the `AnonymousContent`'s entity transform when rendering.  That fixes the placement of the blur.  I haven't managed to get the clip to line up with the blur though.  In theory I should be able to transition the ClipContents to an Entity and set the proper transform on that entity.
