### ISSUE TITLE
[Android] Prompt when unable to install the APK due to conflicts

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#144417]
### Use case

When the APK fails to be installed on the target device, Flutter tools will try to uninstall without asking or waiting for inputs. This often leads to unexpected state/data loss to the developer. It would be fascinating to prompt before we perform the uninstall action.

### Proposal

This is how Android projects would prompt when meeting conflicts.
![image](https://github.com/flutter/flutter/assets/15884415/d1187ba5-fe68-4c9a-8c08-fffddaf7317e)

**Comment by danagbemava-nc** [comment]
There's an existing issue requesting this feature in https://github.com/flutter/flutter/issues/67404.

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you
