### ISSUE TITLE
[in_app_purchase]unsubscribe

### ISSUE THREAD

**Issue by tudosxxx** [flutter/flutter#144469]
### Use case

How do I cancel my subscription? I have a function to upgrade to a lifetime membership. But this lifetime SKU is consumable. When a user purchases a lifetime membership, the user's subscription needs to be canceled. How to implement this function

### Proposal

How do I cancel my subscription? I have a function to upgrade to a lifetime membership. But this lifetime SKU is consumable. When a user purchases a lifetime membership, the user's subscription needs to be canceled. How to implement this function

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/58834
