### ISSUE TITLE
[Impeller] unexpected change in `average_frame_rasterizer_time_millis`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#144406]
https://github.com/flutter/engine/pull/51071 has changed the [`average_frame_rasterizer_time_millis`](https://flutter-flutter-perf.skia.org/e/?keys=X1c47a2ac1a8bac8df39315d06c604ad8&selected=commit%3D39591%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C&xbaroffset=39591).  I think that is unexpected.  We shouldn't be changing out opengles benchmarks.

cc @jonahwilliams

**Comment by gaaclarke** [comment]
also there is a change here [skia perf](https://flutter-flutter-perf.skia.org/e/?keys=X6b57509ffbefd87ffbb913ed06482ee0&selected=commit%3D39591%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C&xbaroffset=39591)

**Comment by jonahwilliams** [comment]
The fallback broke these tests since they're not manually opted into GLES. I'm going to be fixing them today.
