### ISSUE TITLE
Local testing no longer works with Skia gold

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#144496]
I'm getting "No expectations provided by Skia Gold for test: widgets.widgets.magnifier.styled.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org/." on an existing test when running locally. This used to work, though.

According to @jason-simmons:

> This started with a recent change to add a host ABI label to the metadata in the Flutter Gold request (https://github.com/flutter/flutter/commit/4c0b5ccebc8a5cb9056f4f94ed2922b4d2176b59)
>
> The Skia Gold dashboard shows several approved goldens for `widgets.widgets.magnifier.styled` that are tagged with various platform ABIs
(https://flutter-gold.skia.org/search?corpus=flutter&include_ignored=false&left_filter=name%3Dwidgets.widgets.magnifier.styled&max_rgba=0&min_rgba=0&negative=true&not_at_head=false&positive=true&reference_image_required=false&right_filter=&sort=descending&untriaged=true)
>
> But the Gold "get latest digest" service is not returning anything for a query that includes the ABI.

**Comment by goderbauer** [comment]
I've been seeing this as well. @jonahwilliams since this seems to be related to your change in https://github.com/flutter/flutter/pull/143621 is there anything we need to do on the framework side to get this working again?

**Comment by jonahwilliams** [comment]
Well, if you don't want to tag with the host ABI, we don't have to do that. But then you'll need to keep the x64 macs around indefinitely to prevent pixel mismatches.

**Comment by Hixie** [comment]
I see this on Linux, FWIW.

**Comment by jonahwilliams** [comment]
Maybe Is this an issue with the gold query?

**Comment by goderbauer** [comment]
Should have mentioned: I am seeing this on macos_x64, which I think is also what we use when running on CI:

https://github.com/flutter/flutter/blob/1c7e6a401ed6426c17085c0592e1fb1130da311d/.ci.yaml#L3640-L3644

**Comment by Piinks** [comment]
This will be fixed by https://github.com/flutter/flutter/pull/148023
Follow up tracking on the skia bug and re-enabling the key in https://github.com/flutter/flutter/issues/148022
