### ISSUE TITLE
Laying out an empty paragraph produces a single line metric in the HTML renderer

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#144412]
For the CanvasKit renderer, laying out an empty paragraph and then calling `getLineMetrics` on that paragraph produces a zero-length list of line metrics. The HTML renderer is not consistent with this behavior. It instead produces a single line metric with zero-width. We should try to make this behavior consistent between the renderers.

**Comment by opxdelwin** [comment]
Hey @eyebrowsoffire, Thanks for raising an issue.
Could you please provide a [minimal reproducible code](https://stackoverflow.com/help/minimal-reproducible-example), along with output of `flutter doctor -v` for further investigation?

**Comment by LongCatIsLooong** [comment]
Duplicate of https://github.com/flutter/flutter/issues/143331?

**Comment by eyebrowsoffire** [comment]
@LongCatIsLooong ah, yep, definitely a duplicate. Thank you!
