### ISSUE TITLE
SelectableText  can select word by word instead  letter by letter 

### ISSUE THREAD

**Issue by vishalpatel1327** [flutter/flutter#144461]
### Use case

lots of time we need to select words instead of letters.
![image](https://github.com/flutter/flutter/assets/14329287/d869cadb-4873-487c-a9fc-31170bc3d224)

### Proposal

Looks like in some cases I need only word-by-word selection. and Restrict only letter selection.

something like that.
![image](https://github.com/flutter/flutter/assets/14329287/cfffff05-4bb3-40c1-a4fd-58a2943f674a)

**Comment by darshankawar** [comment]
@vishalpatel1327 
I think this is already working. 

<img width="385" alt="Screenshot 2024-03-01 at 3 35 29 PM" src="https://github.com/flutter/flutter/assets/67046386/e58b4006-fda8-412c-a217-400d867a56ee">


```
class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const SelectableText(
      'Hello! How are you?',
      textAlign: TextAlign.center,
      style: TextStyle(fontWeight: FontWeight.bold),
    );
  }
}
```

**Comment by vishalpatel1327** [comment]
but I want to restrict char/letter selection.

like i need user cant select "**he**","**hell**","**llo**" etc.. can only select "**hello**".

**Comment by Mairramer** [comment]
@vishalpatel1327 I think the title and description are reversed.

**Comment by vishalpatel1327** [comment]
@Mairramer   is there any solution that I restrict letter selection? and allow only word selection?.

**Comment by darshankawar** [comment]
@vishalpatel1327 
Can you take a look at [this](https://github.com/flutter/flutter/issues/137371#issuecomment-1852870165) and see if it helps in your use case ?

**Comment by vishalpatel1327** [comment]
@darshankawar I dont think it's available in the current Flutter version I have checked.

**Comment by Mairramer** [comment]
@vishalpatel1327 In this case, I'm saying that the use case and the proposal are reversed.
From what I understand, you want the first time, instead of `SelectableText` taking the entire word, it only takes the first letter?
Because you can select letter by letter, but currently it takes the first word first.

**Comment by darshankawar** [comment]
@vishalpatel1327 
What platform are you using ? (web or desktop) ?


> available in the current Flutter version I have checked.

This is available on latest stable version. You'll need to upgrade to it and try as mentioned in the link to see if it helps in your case or not.

**Comment by Ronakmewara** [comment]
> This is available on latest stable version. You'll need to upgrade to it and try as mentioned in the link to see if it helps in your case or not.

Even with the most latest version, I've encountered the same problem. It has a "SelectableText" class, but I'm experiencing trouble locating the correct Solution, and it doesn't seem to have one. 

Would you mind sharing, please? @darshankawar
