### ISSUE TITLE
Linux docs_publish shard is missing runs

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#144428]
### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

The tree is broken, and we are trying to determine the culprit. There have been 6 commits since the last green build on this shard, but none of the commits in between the tip of tree are running the test so it is hard to know what commit started this.

![image](https://github.com/flutter/flutter/assets/16964204/d052374b-5507-4ba0-a0f6-ce17cce3e0a0)

### Steps to reproduce

N/A

### Expected results

N/A

**Comment by Piinks** [comment]
More context: Some of the in between shards have been queueing for 160+ minutes.
This is one of the builds from the tip of tree https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20docs_publish/12502/overview

**Comment by keyonghan** [comment]
This is an intended behavior to avoid backfilling this target, avoiding doc pollution from an earlier commit.
