### ISSUE TITLE
Deprecate crop/rotation support for Android plugins, consider Dart alternative

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#144407]
The tests as written today are testing Android features and code paths that aren't consistently supported on Android and thus can't be used. Also of note, these functions are not used by our popular plugins. 

There are three paths currently tested today:

1. MediaRenderer (applies rotation) -> ImageRenderer (applies crop) -> SurfaceView [correctly handles crop and rotation]
2. MediaRenderer (applies rotation) -> ImageRenderer (applies crop) -> SurfaceProducer(ST-backed) [correctly handles crop and rotation]
3. MediaRenderer (applies rotation) -> ImageRenderer  (applies crop) -> SurfaceProducer(IR-backed) [does not handle crop or rotation]

Due to an oversight by Android, ImageReader backed surfaces do not respect metadata applied to the surface (rotation & crop). Rotation information is not available at all and crop information is corrupted by the ImageReader (only the width/height is propagated the origin offset is not).

Two action items:

- [ ] We need to replace the Android code with Dart based texture rotation and cropping.
- [ ] We need to make the SurfaceTexture backend ignore the crop and rotation metadata when we render so that it is consistent with ImageReader. We can/should probably make this behaviour SurfaceProducer specific so we don't break any legacy apps.

**Comment by matanlurey** [comment]
I am not currently working on this, but @johnmccutchan I know you had something WIP so I'll keep it assigned to you?

**Comment by johnmccutchan** [comment]
Yes, I'll get back to this soon. The action items I filed above are still the current status.

**Comment by matanlurey** [comment]
@johnmccutchan @jonahwilliams and I chatted about whether or not this should be a blocker for Impeller on Android (Vulkan edition). We decided that this is rather rare functionality, this would only block a user migrating to Impeller if and only if:

- They have a plugin that uses SurfaceTextures 
- That plugin migrates to SurfaceProducer

In other words, plugins could continue to just provide a SurfaceTexture API if they want native crop/rotation, of course that means the plugins would not be compatible with Android + Vulkan. We should have an answer for this eventually (including in docs) but it seems non-critical to have for the initial opt-out period and moving our own internal plugins (that don't use this feature) to SurfaceProducer (unless we find that we indeed are using this functionality, which is unlikely).

Let us know if you disagree strongly, and we can re-evaluate, but for now I'm removing as a blocker/moving to P2.

**Comment by johnmccutchan** [comment]
The crop/rotation parts of the scenario_app tests are actually testing _Android_ functionality and not Flutter functionality. 

The action items in my first comment still stand however I don't think they are priorities as I don't think any plugins are actually using this functionality in practice.

**Comment by matanlurey** [comment]
Removing `e: scenario-app` as this is no longer in scope for the e2e test suite.

**Comment by camsim99** [comment]
It actually looks like this does impact the camera_android_camerax package: https://github.com/flutter/flutter/issues/149294.

To fix it in the plugin right now, we'd need a way to known which path is being used because `Surface`s backed by `SurfaceTexture`s have the transformation information needed for CameraX to correctly rotate the camera preview, but others do not and require us to manually correct the rotation based on the device orientation, sensor orientation, and what camera is being used.

**Comment by chinmaygarde** [comment]
> we'd need a way to known which path is being used

AFAICT, we use SurfaceProducer on API levels 29 and above and SurfaceTexture on API levels 26 to 28.

**Comment by matanlurey** [comment]
Quick correction:

We _always_ use `SurfaceProducer`, and `SurfaceProducer` as an implementation detail uses a `SurfaceTexture` below API version 29.

**Comment by matanlurey** [comment]
Quick update: @chinmaygarde @camsim99 @jonahwilliams chatted about this offline.

We are going to handle the camera plugin by rotating the (internal) widget based on Android sensor data. We'll take the PR she produces and update the migration guide. After all the work is done and the plugins are working again, we'll _consider_ if having a higher-level API in the Android embedder is useful, and also how to handle SurfaceTexture (i.e. "make the SurfaceTexture backend ignore the crop and rotation metadata") as a _future_ change.
