### ISSUE TITLE
Dev branch "flutter create --template=package" is broken.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#14448]
From a clean repo synced to the 'dev' branch (e.g. 'git clone -b dev https://github.com/flutter/flutter.git'), if I do "flutter create --template=package foo", when it does "flutter packages get" in the foo directory, I get this message: "Invalid argument(s): Minimum version ("2.0.0-dev.20.0") must be less than maximum ("2.0.0-dev.16.0")."

And the command fails with about 50K of [stack trace](https://github.com/flutter/flutter/files/1691226/stack.txt)!

**Comment by gspencergoog** [comment]
The "plugin" and "app" creation templates seem to work fine.

**Comment by zoechi** [comment]
could this be related to #14426

**Comment by gspencergoog** [comment]
This appears to be fixed now.
