### ISSUE TITLE
showDatePicker TextField Validation Error

### ISSUE THREAD

**Issue by rohanjariwala03** [flutter/flutter#144478]
### Steps to reproduce

1. Add showDatePicker in your app.
2. Set `initialEntryMode: DatePickerEntryMode.calendar`
3. After opening click on `switch to input` icon on left bottom of dialog.
4. Enter any out of range date in that field and press ok. It will throw error
5. Then Try to add year like `21999999999` (11 digits).
6. It will throw null exception.

### Expected results

showDatePicker shouldn't throw null exception error and just display date is out of range.

### Actual results

Currently it's throwing null exception.

<img width="607" alt="image" src="https://github.com/flutter/flutter/assets/34390549/f3bb75f9-57d9-4101-b1b4-73eb93885e81">

<img width="1114" alt="image" src="https://github.com/flutter/flutter/assets/34390549/aa5be521-f307-4f71-84af-6a72aa2291a4">

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  Future<void> datePicker() async {
    await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now().subtract(const Duration(days: 365)),
      lastDate: DateTime(DateTime.now().year + 10),
      initialEntryMode: DatePickerEntryMode.calendar,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TextButton(
          onPressed: () async {
            await datePicker();
          },
          child: const Text('Date Time')),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/34390549/dce095bb-7681-4b9e-9248-a0aeac84f8e2

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

<img width="706" alt="image" src="https://github.com/flutter/flutter/assets/34390549/6ca6046f-7089-4dd2-96dc-dad2094274c5">

</details>

**Comment by darshankawar** [comment]
Thanks for the report @rohanjariwala03 
I tried the code sample and the year using latest master running on Android emulator with which I got expected result as below:

<img width="328" alt="Screenshot 2024-03-04 at 12 42 36 PM" src="https://github.com/flutter/flutter/assets/67046386/7a1dfc8d-a397-49ed-b54e-c3b02f931b82">

What flutter version and platform are you seeing this error on ?

**Comment by darshankawar** [comment]
Thanks for the update. I followed as above but was unable to replicate the error:


https://github.com/flutter/flutter/assets/67046386/6679f3bc-2bfb-4c11-95e0-0c7734577a4d


I verified on latest master and stable (3.19.2) versions.

**Comment by rohanjariwala03** [comment]
Still on my side I'm able to reproduce this issue. Can you share your code so I can check what I did wrong.

**Comment by darshankawar** [comment]
@rohanjariwala03 I used the same code you provided in original description.
