### ISSUE TITLE
Ensure framework post-render clean up does not regress render performance 

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#144445]
### Background

In a single-view world, the rasterization begins once the framework calls `FlutterView.render`. In a multi-view world, rasterization begins once the `onDrawFrame` callback exits. Thus, expensive work that happens after a `FlutterView.render` could cause end-to-end render performance to regress.

### Solution

1. Investigate whether work that happens after `FlutterView.render` is expensive.
2. If it expensive, consider adding an optimization where we begin rasterization once `FlutterView.render` has been called on all views. This depends on: https://github.com/flutter/flutter/issues/144444

**Comment by goderbauer** [comment]
Pulled some stats on this from a timeline trace of a benchmark run. Clean-up is mostly very fast, but worst case can go upto 3.7 ms.

<img width="887" alt="Screenshot 2024-02-29 at 3 54 10 PM" src="https://github.com/flutter/flutter/assets/1227763/13271ba2-77d7-489f-85a7-04491495eca1">

**Comment by goderbauer** [comment]
In addition to the clean-up there is also the postframe callback phase that happens as part of the drawFrame callback. It's pretty similar:

<img width="873" alt="Screenshot 2024-02-29 at 3 59 23 PM" src="https://github.com/flutter/flutter/assets/1227763/e8e0e87a-f42c-4eb2-a39e-725603802ce8">

**Comment by goderbauer** [comment]
This was done as part of https://github.com/flutter/engine/pull/51186.
