### ISSUE TITLE
Android14: Receiving `cancelled` result code upon eSIM installation.

### ISSUE THREAD

**Issue by Avinash01111992** [flutter/flutter#144476]
### Steps to reproduce

1. Open the Flutter app on any device running Android 14 or higher.
2. Navigate to the section of the app where the eSIM download functionality is available.
3. Tap on the "Download eSIM" button.
4. The app should take you to the device settings eSIM page to initiate the eSIM addition process.
5. Follow the prompts to complete the eSIM installation.
6. Upon successful eSIM installation, observe the result code received by the app.
7. Note that despite successful installation, the app consistently receives RESULT_CANCELED instead of RESULT_OK.
8. Repeat the process on a device running Android 13 or lower to verify that the issue does not occur on earlier versions.
9. Document the observed behavior and result codes on both Android 13 (or lower) and Android 14 (or higher) devices for comparison.
10. By following these steps, the issue with receiving incorrect result codes upon eSIM installation can be consistently reproduced and analyzed for further investigation and resolution.

### Expected results

On Android versions 13 or lower:

1. After completing the eSIM installation process, the Flutter app should receive a result code of RESULT_OK.
The app should successfully handle the RESULT_OK code and proceed with the intended functionality.
On Android versions 14 or higher:

2. After completing the eSIM installation process, the Flutter app should still receive a result code of RESULT_OK.
The app should successfully handle the RESULT_OK code and proceed with the intended functionality.
Regardless of the Android version:

3. Upon successful eSIM installation, the user should be seamlessly redirected back to the Flutter app.
The app should reflect the newly installed eSIM and allow the user to proceed with any relevant actions or features related to the eSIM functionality.

### Actual results

1. On Android versions 13 or lower:
   - After completing the eSIM installation process, the Flutter app successfully receives a result code of `RESULT_OK`.
   - The app handles the `RESULT_OK` code as expected and proceeds with the intended functionality without any issues.

2. On Android versions 14 or higher:
   - After completing the eSIM installation process, the Flutter app consistently receives a result code of `RESULT_CANCELED`.
   - Despite the successful installation of the eSIM, the app does not receive the expected `RESULT_OK` code.

3. Regardless of the Android version:
   - Upon successful eSIM installation, the user is redirected back to the Flutter app as expected.
   - However, due to the inconsistent result code (`RESULT_CANCELED` on Android 14 or higher), the app may not reflect the newly installed eSIM or allow the user to proceed with relevant actions related to eSIM functionality.

These actual results highlight the discrepancy between the expected behavior (receiving `RESULT_OK`) and the observed behavior (receiving `RESULT_CANCELED`) specifically on Android versions 14 or higher. This discrepancy is crucial to address to ensure the consistent and correct functioning of the Flutter app across different Android versions.

### Code sample

<details open><summary>Intent Creation: The code creates an intent to start the LPA (Logical Profile Assistant) activity for eSIM activation. This activity is typically built into the device's Settings app. The EuiccManager.ACTION_START_EUICC_ACTIVATION action is used to initiate the eSIM activation process.</summary>

```
private var lpaActivityIntent = Intent().apply {
    action = EuiccManager.ACTION_START_EUICC_ACTIVATION
    putExtra(EuiccManager.EXTRA_USE_QR_SCANNER, false)
}
mainActivity.startActivityForResult(lpaActivityIntent, ACTIVATE_ACTIVITY_CODE)
private fun onActivate(resultCode: Int) {
    // Handling different result codes
}

Platform Channel Communication: The result of the eSIM activation process will be communicated back to the Dart side (Flutter) using a platform channel. Depending on the result code received (RESULT_OK, RESULT_CANCELED, or others), appropriate callbacks will be invoked to communicate the result back to the Flutter side.

activateCallback?.invoke(Result.success(ActivateEsimReply(ServiceResult.OK)))

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@Avinash01111992 
Can you take a look at [this](https://pub.dev/packages/esim) package and see if it helps in your case or not ?

Also, is there a way for you to check how / what is the expected behavior on native Android ? That way we can narrow down the issue to be specific to Flutter.

**Comment by Avinash01111992** [comment]
Hello @darshankawar  , Thank you for your response , 

https://pub.dev/packages/esim this package , Its basically checking device is compatible with eSIM or not , Which is perfectly working fine for me.

what is the expected behavior on native Android : 
We should receive the Status as OK after Esim installtion.

Actual  behaviour 
Problem is only with Android 14 , eSim compatible checks works perfectly fine.

After eSim installation (Which is happening in the native settings screen of device  ) we receive the callback ,  Ok and Cancel, 

For Android 14 , I am always receiving Cancelled even though Esim successfully installed.

**Comment by darshankawar** [comment]
Thanks for the update. I currently don't have Android 14 device to properly verify it, but based on the report, I'll keep the issue open and label for team's input / tracking.

**Comment by reidbaker** [comment]
@Avinash01111992 can you please update the bug to include A) the logs from a failed attempt (bonus for logs of a successful attempt) B) the output of flutter doctor C) The code for the app under test so we can reproduce this issue locally. 

In general flutter does not normally modify the intent results so my gut is this is not something we have the ability to fix.
