### ISSUE TITLE
[Material3] Update documentation of `AlertDialog`'s default text styles when Material 3 is used

### ISSUE THREAD

**Issue by Nenuphar12** [flutter/flutter#144489]
### Steps to reproduce

1. Create a Flutter app with Material 3 enabled (default).
2. Add an `AlertDialog` to the app without specifying `titleTextStyle` and `contentTextStyle`.
3. Observe the style applied to the title text and the content text.
    - The `TextStyle` applied to the title text is `TextTheme.headlineSmall` of `ThemeData.textTheme`
    - The `TextStyle` applied to the content text is `TextTheme.bodyMedium` of `ThemeData.textTheme`

<details open><summary>Current Documentation</summary>

The current documentation for the properties `AlertDialog.titelTextStyle` and `AlertDialog.contentTextStyle` from [alert_dialog.dart](https://github.com/flutter/flutter/blob/7482962148/packages/flutter/lib/src/material/dialog.dart#L1138):

```dart
  /// Style for the text in the [title] of this [AlertDialog].
  ///
  /// If null, [DialogTheme.titleTextStyle] is used. If that's null, defaults to
  /// [TextTheme.titleLarge] of [ThemeData.textTheme].
  final TextStyle? titleTextStyle;

  /// Style for the text in the [content] of this [AlertDialog].
  ///
  /// If null, [DialogTheme.contentTextStyle] is used. If that's null, defaults
  /// to [TextTheme.titleMedium] of [ThemeData.textTheme].
  final TextStyle? contentTextStyle;
```

</details>

### Expected results

- The documentation of `AlertDialog.titleTextStyle` should clearly state that with Material 3 (useMaterial3: true), the default `titleTextStyle` of `AlertDialog` fall back to **`TextTheme.headlineSmall`** and not to `TextTheme.titleLarge`.
- The documentation of `AlertDialog.contentTextStyle` should clearly state that with Material 3 (useMaterial3: true), the default `contentTextStyle` of `AlertDialog` fall back to **`TextTheme.bodyMedium`** and not to `TextTheme.titleMedium`.

### Actual results

- The current documentation incorrectly suggests that `AlertDialog.titleTextStyle` defaults to `TextTheme.titleLarge`, causing confusion when styling dialogs in Material 3 apps.
- The current documentation incorrectly suggests that `AlertDialog.contentTextStyle` defaults to `TextTheme.titleMedium`, causing confusion when styling dialogs in Material 3 apps.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Documentation Issue Example',
      theme: ThemeData(
        textTheme: const TextTheme(
          // Text style used for the title of the [AlertDialog] according to
          // [AlertDialog.titleTextStyle] DOCUMENTATION.
          titleLarge: TextStyle(color: Colors.green),
          // Text style ACTUALLY USED for the title of the [AlertDialog] when
          // Material 3 is in use.
          headlineSmall: TextStyle(color: Colors.red),

          // Text style used for the content of the [AlertDialog] according to
          // [AlertDialog.contentTextStyle] DOCUMENTATION.
          titleMedium: TextStyle(color: Colors.green),
          // Text style ACTUALLY USED for the content of the [AlertDialog]
          // when Material 3 is in use.
          bodyMedium: TextStyle(color: Colors.red),
        ),
        useMaterial3: true,
      ),
      home: const AlertDialog(
        title: Text(
          'Title - should be green according to [AlertDialog.titleTextStyle] '
          'documentation',
        ),
        content: Text(
          'Content - should be green according to '
          '[AlertDialog.contentTextStyle] documentation.',
        ),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [version 10.0.22631.3155], locale fr-FR)
    • Flutter version 3.19.2 on channel stable at C:\Users\nenup\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (3 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\nenup\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.87.0)
    • VS Code at C:\Users\nenup\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22631.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.52

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by Nenuphar12** [comment]
I can try to write a pull request if you would like me to.

**Comment by darshankawar** [comment]
Thanks for the detailed report @Nenuphar12 
Since you are using `AlertDialog` and trying to pass `TextTheme` to it, can you instead try `DialogTheme` and check if using it, you get desired results ?

I tried something like below which led me to:

<img width="252" alt="Screenshot 2024-03-04 at 1 44 05 PM" src="https://github.com/flutter/flutter/assets/67046386/ad520869-d298-4807-be71-25492ab07606">

```
theme: ThemeData(
        dialogTheme: const DialogTheme(
          // Text style used for the title of the [AlertDialog] according to
          // [AlertDialog.titleTextStyle] DOCUMENTATION.
          titleTextStyle: TextStyle(color: Colors.green),
          // Text style ACTUALLY USED for the title of the [AlertDialog] when
          // Material 3 is in use.
          contentTextStyle: TextStyle(color: Colors.red),

```

You might need to explore it a bit more.

**Comment by Nenuphar12** [comment]
Hi @darshankawar,

Thank you for your suggestion, and indeed, using `DialogTheme` or specifying `headlineSmall` instead of `titleLarge` can achieve the desired style for the `AlertDialog`. However, my primary concern is the clarity of the `AlertDialog` documentation regarding default text styles when Material 3 is enabled.

The current documentation for `AlertDialog.titleTextStyle` only mentions `titleLarge` as the default, which led me to mistakenly attempt to modify `titleLarge` for global changes (I was trying to to change the style of all text using the same default `TextStyle` as `AlertDialog.title` for uniformity). It was only after inspecting the `AlertDialog` implementation that I realized `headlineSmall` is actually used by default in Material 3 contexts.

I believe updating the documentation to explicitly state that the default text style switches to `headlineSmall` with Material 3 enabled would prevent similar confusion.

For reference, the `AlertDialog.iconColor` documentation clearly indicates its dependency on `ThemeData.useMaterial3`:

```dart
  /// Color for the [Icon] in the [icon] of this [AlertDialog].
  ///
  /// If null, [DialogTheme.iconColor] is used. If that is null, defaults to
  /// color scheme's [ColorScheme.secondary] if [ThemeData.useMaterial3] is
  /// true, black otherwise.
  final Color? iconColor;
```

While the documentation of `AlertDialog.titleTextStyle` does not mention this dependency:

```dart
  /// Style for the text in the [title] of this [AlertDialog].
  ///
  /// If null, [DialogTheme.titleTextStyle] is used. If that's null, defaults to
  /// [TextTheme.titleLarge] of [ThemeData.textTheme].
  final TextStyle? titleTextStyle;
```

The documentation for `AlertDialog.contentTextStyle` similarly lacks details regarding its default behavior under Material 3.

**Comment by darshankawar** [comment]
Thanks for the update. 

> I can try to write a pull request if you would like me to.

You are welcome to do so.
