### ISSUE TITLE
Build third-party service mojoms in service-specific repos

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1445]
We are temporarily putting mojoms for third-party services in the main engine repo. Right now, when engine releases come out, the firebase-dart project needs to be updated to ensure that the mojoms and implementations stay in sync. I put instructions about this into https://github.com/flutter/engine/wiki/Release-process. We should be building self-contained jars + Dart wrappers that aren’t tied to a specific version of flutter_engine, but rather to a specific version of the third-party service. To do this we should have infrastructure for putting the mojoms and Dart wrappers in the same repo on GitHub and having travis build that builds the binary artifacts and uploads them to the cloud.

cc @abarth

**Comment by eseidelGoogle** [comment]
Presumably this is no longer an issue now that we're deprecating mojo-based plugins?

**Comment by collinjackson** [comment]
Agree
