### ISSUE TITLE
Display error when I set localization to 'Thailand' !

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#14451]
![2018-02-03 8 34 06](https://user-images.githubusercontent.com/13853/35767159-b9c9d10a-0921-11e8-879a-3645d2c46477.png)

But I could find these words in material_th.arb

{
  "scriptCategory": "tall",
  "timeOfDayFormat": "ah:mm",
  "openAppDrawerTooltip": "เปิดเมนูการนำทาง",
  "backButtonTooltip": "กลับ",
  "closeButtonTooltip": "ปิด",
  "deleteButtonTooltip": "ลบ",
  "nextMonthTooltip": "เดือนหน้า",
  "previousMonthTooltip": "เดือนที่แล้ว",
  "nextPageTooltip": "หน้าถัดไป",
  "previousPageTooltip": "หน้าก่อน",
  "showMenuTooltip": "แสดงเมนู",
  "aboutListTileTitle": "เกี่ยวกับ $applicationName",
  "licensesPageTitle": "ใบอนุญาต",
  "pageRowsInfoTitle": "$firstRow-$lastRow จาก $rowCount",
  "pageRowsInfoTitleApproximate": "$firstRow–$lastRow จากประมาณ $rowCount",
  "rowsPerPageTitle": "แถวต่อหน้า:",
  "tabLabel": "$tabIndex จาก $tabCount",
  "selectedRowCountTitleOne": "เลือกแล้ว 1 รายการ",
  "selectedRowCountTitleOther": "เลือกแล้ว $selectedRowCount รายการ",
  "cancelButtonLabel": "ยกเลิก",
  "closeButtonLabel": "ปิด",
  "continueButtonLabel": "ต่อไป",
  "copyButtonLabel": "คัดลอก",
  "cutButtonLabel": "ตัด",
  "okButtonLabel": "ตกลง",
  "pasteButtonLabel": "วาง",
  "selectAllButtonLabel": "เลือกทั้งหมด",
  "viewLicensesButtonLabel": "ดูใบอนุญาต",
  "anteMeridiemAbbreviation": "AM",
  "postMeridiemAbbreviation": "PM",
  "timePickerHourModeAnnouncement": "เลือกชั่วโมง",
  "timePickerMinuteModeAnnouncement": "เลือกนาที",
  "signedInLabel": "ลงทะเบียนเข้า",
  "hideAccountsLabel": "ซ่อนบัญชี",
  "showAccountsLabel": "แสดงบัญชี",
  "modalBarrierDismissLabel": "ยกเลิก"
}

**Comment by Hixie** [comment]
Can you paste the code you used for your `MaterialApp` and your call to `runApp`?

**Comment by realcarlos** [comment]
Thank you , finallly I found I have to add a line
'th',
 in packages/flutter_localizations/lib/src/materail_localizations.dart

**Comment by Hixie** [comment]
You shouldn't have to change that file, unless we have a bug in it. cc @HansMuller

**Comment by jason-simmons** [comment]
This can be reproduced by adding a `const Locale('th', 'TH')` to the `supportedLocales` list passed to the MaterialApp constructor in Gallery.

The Thai localization data isn't loading because _MaterialLocalizationsDelegate.isSupported() returns false unless "th" is added to the _supportedLanguages list.

**Comment by jason-simmons** [comment]
These language codes are listed in the comment at the top of material_localizations.dart but are not in the _supportedLanguages list:
  `['ko', 'nl', 'pl', 'th', 'tr']`

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/13621 added the 5 new locales @jason-simmons mentioned, which includes 'th', but inexplicably didn't update _MaterialLocalizationsDelegate._supportedLanguages. Sorry about that.

packages/flutter_localizations/test/translations_test does verify that translations exist for these languages but does not verify that `MaterialLocalizations.delegate.isSupported()` succeeds for all of them.

Fixing this now.
