### ISSUE TITLE
Bad image rendering on KYT31 and ZTE B2016

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#14459]
I received a report from some small users that the grid view is wrong. 

- KYT31 (Android 5.1)
- ZTE B2016 (Android 5.1.1)

<img src="https://user-images.githubusercontent.com/1098127/35796488-114acc70-0aa0-11e8-83a3-b8fedb9d353a.png" width="200" /> <img src="https://user-images.githubusercontent.com/1098127/35796487-1129da88-0aa0-11e8-98b1-63e4070c2df8.png" width="200" />

There is no problem for the majority of users. Also I can not reproduce it with my devices.

<img src="https://user-images.githubusercontent.com/1098127/35796666-9d8cfc8a-0aa0-11e8-8398-5f95ea72dd33.png" width="200" /> <img src="https://user-images.githubusercontent.com/1098127/35796667-9db3fba0-0aa0-11e8-877d-8f0dc2f127f7.png" width="200" />

Does anyone know of why this problem occurs and how to avoid it?

## Flutter Doctor

alpha 0.0.20

```
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale ja-JP, channel alpha)
    • Flutter at /Applications/flutter
    • Framework revision 8f65fec5f5 (5 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.1)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3942.31
```

**Comment by najeira** [comment]
It is unknown whether it is occurring in the current Flutter.

I will contact the user who reported this.

**Comment by cbracken** [comment]
@najeira do you know if this is still an issue.

/cc @brianosman in case this looks familiar

**Comment by brianosman** [comment]
I know we had several similar issues in the past, related to both our text and optimized multi-texture op. AFAIK, those have all been fixed, but I'd want confirmation.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
