### ISSUE TITLE
[DRAFT] Text selection overlaps in listview widgets 

### ISSUE THREAD

**Issue by zahidshaikh08** [flutter/flutter#144508]
### Steps to reproduce

Add a SelectableText() widget to a normal listview with a normal texts and select any word or anything.

Now that selection handle widgets appears and now if you scroll up or down you will see that instead of text selections scroll with listview viewport, it over laps any top or bottom widgets.

Attaching video and image of the same. 

### Expected results

The expected result for this is to selection handle should scroll within listview view port only and does not overlaps the other widgets 

### Actual results

The selection handles overlaps the top and bottom widgets. 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. SelectableText is using EditableText internally (same to TextField). There are similar issues at https://github.com/flutter/flutter/issues/59229, https://github.com/flutter/flutter/issues/13182. I will close this issue in favor of these issues. Please follow up on them for updates.
