### ISSUE TITLE
[CP] Hotfix fragment shaders fix into stable

### ISSUE THREAD

**Issue by renancaraujo** [flutter/flutter#144503]
### Issue Link

 https://github.com/flutter/flutter/issues/141296 https://github.com/flutter/flutter/issues/141838

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/49754

### Changelog Description

Fixes fragment shader loading on the web (cavaskit).

### Impacted Users

All Flutter devs using fragment shaders on Flutter web projects.

### Impact Description

A runtime crash.
Currently, there is a bug when loading shader data for fragment shaders in runtime ( https://github.com/flutter/flutter/issues/141296). This makes shader-based views no to render as a result of the crash. The app may get unresponsive. 

### Workaround

There is no workaround

### Risk

high

### Test Coverage

yes

### Validation Steps

Load a fragment shader on a flutter web project.

**Comment by CaseyHillers** [comment]
@renancaraujo before we can review this, we'll need a PR opened to the stable branch. Can you update your PR description with a PR pointing to flutter-3.19-candidate.1? Thanks!

**Comment by renancaraujo** [comment]
Sorry i am, not sure how to do this since the OG PR (https://github.com/flutter/engine/pull/49754) is on stable.

**Comment by itsjustkevin** [comment]
@renancaraujo we've written a [wiki entry](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process) on the cherry-pick process.  

If there is anything that is still confusing, please call it out so that we may make it more clear.

**Comment by troels** [comment]
Right now fragment shaders apparently doesn't work on flutter web in 3.19. Is there any chance this will get fixed in stable before 3.22?

**Comment by itsjustkevin** [comment]
@renancaraujo closing as there has been no movement on this cherry-pick issue.

@troels please feel free to open an issue for us to track.
