### ISSUE TITLE
Linux desktop frame rate isn't synced to display

### ISSUE THREAD

**Issue by nortio** [flutter/flutter#144534]
Issue #49757 was closed while not having a fix for Linux platforms. I did some [tests](https://github.com/flutter/flutter/issues/49757#issuecomment-1970025542) a few days ago and the problem is still there. I apologize for creating a new issue.

**Comment by huycozy** [comment]
Hi @nortio, I see your comment there, please follow up on it. I will raise that issue if it hasn't been reviewed yet. Closing this as a duplicate.
