### ISSUE TITLE
zsh: command not found: flutter

### ISSUE THREAD

**Issue by anmolgupta321** [flutter/flutter#144537]
All was working well for me, but for some reason i have to open .zshrc file, after that i tried the flutter pub get command or any other command, it threw the command not found error. Nothing has been changed in the .zshrc file nor any configuration has been changed.
Its weird. 
### Steps to reproduce

1. open the .zshrc file
2. close it 
3. try flutter pub get command

### Expected results

the command should run

### Actual results

zsh: command not found: flutter

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 flutter doctor -v
zsh: command not found: flutter
```

</details>

**Comment by danagbemava-nc** [comment]
You should check your path configuration. Since this happened after you made some modifications to your .zshrc file, this is not an issue with flutter but likely an issue with your environment. 

Closing from here as this is not a flutter issue. 

Thank you

**Comment by anmolgupta321** [comment]
no change is made in configuration.

**Comment by anmolgupta321** [comment]
please reopen

**Comment by anmolgupta321** [comment]
/Users/anmolgupta/.zshrc:7: no such file or directory: anmolgupta/Downloads/flutter/bin:/opt/homebrew/bin:/opt/homebrew/bin

**Comment by danagbemava-nc** [comment]
This is not a flutter issue, it is something local to your shell configuration. You will need to check your path variable. 

See https://stackoverflow.com/questions/58400500/after-upgrade-macos-terminal-showing-zsh-command-not-found-flutter
