### ISSUE TITLE
Set cacheExtentUp and cacheExtentDown in the ListView.

### ISSUE THREAD

**Issue by fyxtc** [flutter/flutter#144586]
### Use case

If I use dynamic height asynchronous loading of url images, I want to be able to scroll directly to the position of the nth image without having to preload the image above this position (because the user has already seen the image above it), but still have to preload the image below it. 

If the top image is preloaded, waiting for the asynchronous image to finish loading will cause the current position of the ListView to be offset

### Proposal

As mentioned above

**Comment by darshankawar** [comment]
> I want to be able to scroll directly to the position of the nth image without having to preload the image above this position (because the user has already seen the image above it), but still have to preload the image below it.

@fyxtc Can you check if https://api.flutter.dev/flutter/widgets/ScrollController/jumpTo.html helps to achieve your case ?
You can read https://medium.com/@linxunfeng/flutter-scrolling-to-a-specific-item-in-the-scrollview-b89d3f10eee0 for further reference and see if it helps or not.
