### ISSUE TITLE
[CP] Fix RPCError rendering frame with raster stats on Impeller backend

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#144565]
### Issue Link

https://github.com/flutter/flutter/issues/143010

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/144564

### Changelog Description

Fix tool crash when attempting to render frame with raster stats on an application with the Impeller backend.

### Impacted Users

Flutter developers attempting to render frame with raster stats on an application with the Impeller backend.

### Impact Description

In this case, the tool would crash.

### Workaround

Don't attempt to render a frame with raster stats.

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
@zanderso could you take a look at this cherry-pick request?

**Comment by zanderso** [comment]
CP lgtm
