### ISSUE TITLE
README at the root of the flutter repository contains dead links to images.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#144507]
As of https://github.com/flutter/flutter/commit/65cd84b58885fb78bd2d27f60fa7209bedf5be25, the README.md at the root of the repository contains images in the website repository that seem to have moved. These links are:

* https://github.com/flutter/website/blob/main/src/assets/images/docs/homepage/reflectly-hero-600px.png?raw=true
* https://github.com/flutter/website/blob/main/src/assets/images/docs/homepage/dart-diagram-small.png?raw=true

These images must be moved into the Flutter repository itself so changes in an unrelated repo don't cause dead links.
----------------------------
![Image With Dead Links](https://github.com/flutter/flutter/assets/44085/3a4931e0-83cb-4526-82f3-841eddb00012)

**Comment by goderbauer** [comment]
This has been fixed.
