### ISSUE TITLE
flutter doctor failed

### ISSUE THREAD

**Issue by ryanfang** [flutter/flutter#14455]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by ryanfang** [comment]
/Users/fangtao/Documents/FlutterWorkspace/flutter/bin/flutter --no-color doctor
Waiting for another flutter command to release the startup lock...
Downloading package sky_engine...(cached)
Downloading common tools...(cached)
Downloading darwin-x64 tools...(cached)
Downloading darwin-x64 tools...(cached)
Downloading android-arm-profile/darwin-x64 tools...
Downloading android-arm-release/darwin-x64 tools...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 49313
Crash report written to /Users/fangtao/Documents/FlutterWorkspace/flutter/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1

**Comment by jcollins-g** [comment]
@ryanfang This looks like the crash report sending is throwing because of a network error; flutter tool should be more graceful about that.  Can you post the contents of /Users/fangtao/Documents/FlutterWorkspace/flutter/flutter_02.log into the issue?

**Comment by h3clikejava** [comment]
@ryanfang I meet the same problem, did u find method can fix it?

**Comment by BondarenkoStas** [comment]
As there were no response and log given, I assume the error is stale. Please open a new issue if you encounter it, closing it.
