### ISSUE TITLE
Recipe crash marks a target with subbuild failures as infra failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#144587]
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20mac_host_engine/27584/overview

Apparently due to https://flutter.googlesource.com/recipes/+/7b9638ec88fb0b375a3b331aa36e86c99b5a42c0

Doesn't revert cleanly https://flutter-review.googlesource.com/c/recipes/+/55762

**Comment by zanderso** [comment]
cc @keyonghan

**Comment by zanderso** [comment]
Recipe revert landed. Dropping priority and assigning to @keyonghan

**Comment by keyonghan** [comment]
A reland with a fix has been submitted: https://flutter-review.googlesource.com/c/recipes/+/55840.
Closing.
