### ISSUE TITLE
[Impeller] 15% regression in `animated_advanced_blend_perf__timeline_summary`:`90th_percentile_frame_rasterizer_time_millis`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#144552]
introduced in https://github.com/flutter/engine/pull/51094

[skia perf](https://flutter-flutter-perf.skia.org/e/?keys=X9cd31aa58124557504737db0b7e5fef8&selected=commit%3D39603%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Danimated_advanced_blend_perf__timeline_summary%252C&xbaroffset=39603)

cc @jonahwilliams

**Comment by gaaclarke** [comment]
[another related regression](https://flutter-flutter-perf.skia.org/e/?keys=X8186a4cb66bffe29e0e2ecec8368608d&selected=commit%3D39603%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_gpu_frame_time%252Ctest%253Dnew_gallery_impeller__transition_perf%252C&xbaroffset=39604)

**Comment by jonahwilliams** [comment]
This had mixed results across the board:

https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DPixel_7_Pro%26sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Danimated_advanced_blend_perf__timeline_summary&selected=commit%3D39643%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_frame_rasterizer_time_millis%252Ctest%253Danimated_advanced_blend_perf__timeline_summary%252C

it looks like the worst times are more stable here.
