### ISSUE TITLE
NestedScrollView body hidden behind app bar

### ISSUE THREAD

**Issue by Extenda-TimRoberson** [flutter/flutter#144676]
### Steps to reproduce

1. Scroll on the CustomScrollView (body of NestedScrollView) in the direction of the app bar

### Expected results

Given that physics is BouncingScrollPhysics we expect the body of the NestedScrollView to bounce back to be below the app bar. or; Given that physhics is ClampingScrollPhysics we expect the body of the NestedScrollView to not be allowed to go behind the app bar

### Actual results

The body of the NestedScrollView is hidden behind the appbar and does not bounce back.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sliver MRE',
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (context, _) => [
            SliverAppBar(
              backgroundColor: Colors.white.withOpacity(0.8),
              pinned: true,
              title: const Text('appbar'),
            )
          ],
          body: Container(
            color: Colors.blue,
            child: CustomScrollView(
              slivers: [
                SliverToBoxAdapter(
                  child: Container(
                    color: Colors.red,
                    height: 50,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/111065088/94cdc7d8-4588-499e-8033-61656993f58d

</details>

### Logs

<details open><summary>Logs</summary>

[log.txt](https://github.com/flutter/flutter/files/14507336/log.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.19.2 on channel stable at /Users/revision/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (7 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/revision/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (5 available)
    • PS20J (mobile)              • 18261521400940                       • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 14 Pro Max (mobile)  • DADFA2E6-08B4-480F-B6F2-13A901182C41 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Extenda-TimRoberson 
Can you take a look at the official example and see if using it you get same behavior or not ?
The example uses tabbarview which seems to be a usual usage as mentioned:

`The most common use case for this widget is a scrollable view with a flexible [SliverAppBar](https://api.flutter.dev/flutter/material/SliverAppBar-class.html) containing a [TabBar](https://api.flutter.dev/flutter/material/TabBar-class.html) in the header (built by [headerSliverBuilder](https://api.flutter.dev/flutter/widgets/NestedScrollView/headerSliverBuilder.html), and with a [TabBarView](https://api.flutter.dev/flutter/material/TabBarView-class.html) in the [body](https://api.flutter.dev/flutter/widgets/NestedScrollView/body.html), such that the scrollable view's contents vary based on which tab is visible.`

**Comment by Extenda-TimRoberson** [comment]
Seems that I was missing the SliverOverlapInjector, after adding that it is working as expected.
