### ISSUE TITLE
Material Date Picker Displays Simplified Chinese Instead of Traditional Chinese in Flutter App

### ISSUE THREAD

**Issue by gutwenger** [flutter/flutter#144612]
### Steps to reproduce

1. Call the showDateRangePicker function with the desired BuildContext and Locale, specifying Traditional Chinese locale.
2. Observe the displayed date range picker.

### Expected results

The date range picker should display all text, including labels, buttons, and prompts, in Traditional Chinese language according to the specified `Locale`.

### Actual results

Despite providing the Traditional Chinese locale, the date range picker displays text in Simplified Chinese instead of Traditional Chinese. This inconsistency results in the user interface not aligning with the selected language preference, potentially causing confusion or misunderstanding for users expecting Traditional Chinese text.

Also there's no way to change of the text of `From Date` and `To Date`, otherwise, I can directly pass the i18n translation string into the widget as workaround.

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<DateTimeRange?> showCommonDateRangePicker({required BuildContext context, required Locale locale}) async {
  final result = await showDateRangePicker(
      context: context,
      locale: locale,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)));
  return result;
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="317" alt="image" src="https://github.com/flutter/flutter/assets/60968624/fae77f95-5950-4089-9583-89e06ec5df82">

The texts in the orange rectangle is in Simplified Chinese, not Traditional Chinese.
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```
console

[✓] Flutter (Channel stable, 3.16.5, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.16.5 on channel stable at /Users/fremont/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000
    • 

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone Fre (mobile) • 00008110-0016619834D1401E • ios            • iOS 17.0.1 21A340
    • macOS (desktop)     • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 104.0.5112.79

[✓] Network resources
    • All expected network resources are available.

``` 

</details>

**Comment by darshankawar** [comment]
Thanks for the report @gutwenger 
Can you provide us complete runnable code sample ? Also, please provide the expected result when using Simplified Chinese vs Traditional one so that we can get more idea.
