### ISSUE TITLE
[ci] Wait for test check-in in `release` action not working.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#144663]
It seems that the `Wait for test check-in` step of the `release` GH workflow is not waiting long enough for tests to be actually set up, failing and closing the tree.

As you can see here:

* https://github.com/flutter/packages/actions/runs/8166896062/job/22326405047

The action failed almost immediately, without waiting for the tests to be correctly setup:

```
Bundle complete! 6 Gemfile dependencies, 40 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Run ruby entrypoint.rb
  ruby entrypoint.rb
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ALLOWED_CONCLUSIONS: success,neutral
    IGNORE_CHECKS: 
    CHECK_NAME: Linux ci_yaml packages roller
    CHECK_REGEXP: 
    REF: 9b88dbc539927fa0f4c8ae9aa8792043ecd0beed
    REPO_TOKEN: ***
    VERBOSE: false
    WAIT_INTERVAL: 30
    RUNNING_WORKFLOW_NAME: 
    API_ENDPOINT: 
Checks running on ref:
Checks in_progress: release, Scorecards analysis
Checks after ignore checks filter:
Checks in_progress: release, Scorecards analysis
Checks after check_name filter:
Checks after Regexp filter:
The requested check was never run against this ref, exiting...
Error: Process completed with exit code 1.
```

* https://github.com/flutter/packages/blob/9b88dbc539927fa0f4c8ae9aa8792043ecd0beed/.github/workflows/release.yml#L46-L60

Is the `check-name` still valid?

**Comment by stuartmorgan** [comment]
I accidentally closed the original version of this, duping to that re-opened issue (https://github.com/flutter/flutter/issues/137299). There's more context there, and I'll add more info.

**Comment by ditman** [comment]
Ah @stuartmorgan, I didn't find the OG one in a cursory search, and didn't think to reopen the one where the check was added! Thanks for consolidating this.
