### ISSUE TITLE
iOS 16+ visible value returns false incorrectly for UI elements in appium inspector

### ISSUE THREAD

**Issue by Shailendra-3Frames** [flutter/flutter#144678]
### Steps to reproduce

1. Upload the iPA to SauceLabs
2. Choose iOS 16+ device and start the test
3. Inspect the elements
4. Check the visible flag in the DOM treean 

### Expected results

The visible property should be true for the visible elements in the widget tree when we inspect in SauceLabs inspector.

### Actual results

I am trying to inspect the Flutter app in SauceLabs but I am always getting a visible flag as false for a few elements even though it is visible. Due to this, all the automation scripts are stopped as the visible flag is false.

### Code sample

[
  {
    "label": "Application Summary",
    "key": "application_summary",
    "value": {
      "appStorageId": "2dc8bd24-b3bb-42de-8bde-18d3a5c887ae",
      "groupId": 16990913,
      "filename": "develop-testing.ipa",
      "name": "QA App™",
      "packageName": "com.myapp.name",
      "version": "974102200",
      "versionCode": null,
      "shortVersion": "2.1.1",
      "minSdkLevel": null,
      "targetSdkLevel": null,
      "minOsVersion": "13.0",
      "targetOsVersion": "16.1"
    }
  },
  {
    "label": "App",
    "key": "app",
    "value": null
  },
  {
    "label": "ID",
    "key": "id",
    "value": "e4d73fbfbd2f4df5a14e5609cf8b46d3"
  },
  {
    "label": "Passed",
    "key": "passed",
    "value": null
  },
  {
    "label": "Name",
    "key": "name",
    "value": "<your test name>"
  },
  {
    "label": "Build",
    "key": "build",
    "value": "<your build id>"
  },
  {
    "label": "Tags",
    "key": "tags",
    "value": []
  },
  {
    "label": "Browser",
    "key": "browser",
    "value": ""
  },
  {
    "label": "Browser version",
    "key": "browser_version",
    "value": ""
  },
  {
    "label": "Server OS",
    "key": "os",
    "value": "iOS"
  },
  {
    "label": "Automation backend",
    "key": "automation_backend",
    "value": "appium"
  },
  {
    "label": "Client",
    "key": "client",
    "value": "appium/9.1.0 (selenium/4.18.1 (java windows))"
  },
  {
    "label": "Owner",
    "key": "owner",
    "value": "VenkataKarodhi"
  },
  {
    "label": "Creation time",
    "key": "creation_time",
    "value": 1709626617290
  },
  {
    "label": "Start time",
    "key": "start_time",
    "value": 1709626644147
  },
  {
    "label": "End time",
    "key": "end_time",
    "value": 1709626880068
  },
  {
    "label": "Modification time",
    "key": "modification_time",
    "value": 1709626880068
  },
  {
    "label": "Wait time",
    "key": "wait_time"
  },
  {
    "label": "Error",
    "key": "error",
    "value": null
  },
  {
    "label": "Selenium version",
    "key": "selenium_version",
    "value": ""
  },
  {
    "label": "Proxied",
    "key": "proxied",
    "value": false
  },
  {
    "label": "Assigned tunnel id",
    "key": "assigned_tunnel_id",
    "value": null
  },
  {
    "label": "Base config",
    "key": "base_config",
    "value": {}
  },
  {
    "label": "Record screenshots",
    "key": "record_screenshots",
    "value": true
  },
  {
    "label": "Record video",
    "key": "record_video",
    "value": true
  },
  {
    "label": "Custom Data",
    "key": "custom-data",
    "value": {}
  },
  {
    "label": "Public",
    "key": "public",
    "value": "team"
  },
  {
    "label": "Manual",
    "key": "manual",
    "value": false
  },
  {
    "label": "Breakpointed",
    "key": "breakpointed",
    "value": null
  },
  {
    "label": "Screenshots",
    "key": "screenshots",
    "value": []
  },
  {
    "label": "Full Device Descriptor",
    "key": "full_device_descriptor",
    "value": {
      "abiType": "arm64",
      "apiLevel": 0,
      "cpuCores": 6,
      "cpuFrequency": 3230,
      "defaultOrientation": "PORTRAIT",
      "dpi": 460,
      "hasOnScreenButtons": true,
      "id": "iPhone_14_prolifics_us",
      "internalOrientation": "PORTRAIT",
      "internalStorageSize": 128000,
      "isArm": true,
      "isKeyGuardDisabled": false,
      "isPrivate": true,
      "isRooted": false,
      "isTablet": false,
      "manufacturer": [
        "Apple"
      ],
      "modelNumber": "iPhone14,7",
      "name": "iPhone 14",
      "os": "IOS",
      "osVersion": "16.0",
      "pixelsPerPoint": 3,
      "ramSize": 6144,
      "resolutionHeight": 2532,
      "resolutionWidth": 1170,
      "screenSize": 6.1,
      "sdCardSize": 0,
      "supportsAppiumWebAppTesting": true,
      "supportsGlobalProxy": false,
      "supportsMinicapSocketConnection": true,
      "supportsMockLocations": true,
      "cpuType": "ARM",
      "deviceFamily": "IPHONE",
      "dpiName": "xxhdpi",
      "isAlternativeIoEnabled": true,
      "supportsManualWebTesting": true,
      "supportsMultiTouch": true,
      "supportsXcuiTest": true
    }
  }
]

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="825" alt="Screenshot 2024-03-22 at 9 12 17 PM" src="https://github.com/flutter/flutter/assets/136445969/2a342180-e44e-44c0-af81-304752a44481">

</details>

### Logs

<details open><summary>Logs</summary>

```console
02:25:36 E Runner(AEPServices)[19113] <Error>: <private>
02:25:37 E Runner(libCoreFSCache.dylib)[19113] <Error>: fopen failed for data file: errno = 2 (No such file or directory)
02:25:37 E Runner(libCoreFSCache.dylib)[19113] <Error>: Errors found! Invalidating cache...
02:25:38 E Runner(libCoreFSCache.dylib)[19113] <Error>: fopen failed for data file: errno = 2 (No such file or directory)
02:25:38 E Runner(libCoreFSCache.dylib)[19113] <Error>: Errors found! Invalidating cache...
02:25:39 E Runner(libCoreFSCache.dylib)[19113] <Error>: fopen failed for data file: errno = 2 (No such file or directory)
02:25:39 E Runner(libCoreFSCache.dylib)[19113] <Error>: Errors found! Invalidating cache...
02:25:39 E Runner(libCoreFSCache.dylib)[19113] <Error>: fopen failed for data file: errno = 2 (No such file or directory)
02:25:39 E Runner(libCoreFSCache.dylib)[19113] <Error>: Errors found! Invalidating cache...
02:26:49 E Runner(AXRuntime)[19113] <Error>: Unknown client: Runner
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Shailendra-3Frames 
You are on very old version of stable, obsolete to be precise. You need to upgrade to latest and re-run your scenario.
Also, as you mentioned, iOS 16+, does it work properly for < 16 version ?
Moreover, SauceLabs is third party tool. You need to check with flutter inspector and see if it works or not.
Also, check https://github.com/flutter/flutter/issues/18060 issue which indicates flutter doesn't seem to properly support appium yet.
