### ISSUE TITLE
add documentation for how to use the Flutter Inspector

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#14464]
We should update flutter.io to include docs about how to start and use the Flutter Inspector. This could be as part of the existing https://flutter.io/using-ide/ page, or a new top-level page, similar to https://flutter.io/hot-reload/.

Potential topics to cover:
- how to access / open  it
- how to use it - use cases and larger features
- additional useful items, like toggling the fps display or platform rendering from the inspector toolbar

/cc @mit-mit @Sfshaza @jacob314

**Comment by devoncarew** [comment]
(see also https://github.com/flutter/flutter-intellij/issues/1718)

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1851](https://github.com/flutter/website/issues/1851) via [**ZenHub**](https://www.zenhub.com/)
