### ISSUE TITLE
AutofillGroup no longer fills relevant email/password with Flutter 3.19.2

### ISSUE THREAD

**Issue by diego-tread** [flutter/flutter#144695]
### Steps to reproduce

Apologies for not having a better code sample, but it requires registering a domain with an associated appID to function.

`AutofillGroup` in flutter 3.16.9 would give a prompt for password manager (1pass in this case), and once the password manager is unlocked, correctly suggest the autofill credentials specific to the app based on the registered domain hosted `.well-known/apple-app-site-association` file.

When making no changes to code, and only upgrading to flutter 3.19.2, `AutofillGroup` prompts for the password manager, but no longer attempts to autofill credentials specific to this app when unlocked. It instead gives a list of ALL the credentials stored in the password manager and requires you to search and select the correct credentials.

Please look at the screenshots for a before and after behavior difference, and please let me know if there is any other relevant information I can get to you, to help resolve this. If necessary, we would be open to pair with a flutter engineer if you are unable to repro this issue on your end.

### Expected results

Usage of password manager is suggested, and when opened, autofills with credentials registered with the associated domain.

### Actual results

Usage of password manager is suggested, but when opened, doesn't autofill with credentials registered with the associated domain. 

### Code sample

<details open><summary>Code sample</summary>

```dart
 return AutofillGroup(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          TreadTextField.email(
            controller: _emailController,
            labelText: l10n.email,
            enabled: !_sendingMagicLink && !_loggingIn,
            onChanged: (value) => setState(() {}),
          ),
          const SizedBox(height: 8),
          TreadTextField.password(
            controller: _passwordController,
            labelText: l10n.password,
            enabled: !_sendingMagicLink && !_loggingIn,
            onChanged: (value) => setState(() {}),
          ),
....

`TreadTextField` is `TextField` under the hood
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

| Flutter 3.16.9 | Flutter 3.19.2 |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/133052302/ea0d5285-af70-4bf2-bc16-21fb597a7e38"> | <img width="400" src="https://github.com/flutter/flutter/assets/133052302/c8eefd1c-67c5-4346-a495-341f5092bd86">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.2 23C64 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2 23C64 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @diego-tread 
Which iOS device are you checking on? (OS, model). I checked this with my device `iPhone 7, iOS 15.8` on both 3.19.2 and 3.16.9 but it always prompts password manager instead.

**Comment by diego-tread** [comment]
I'm using the iPhone 13 pro on 17.4 (21E219).

There is a bit of nuance to this issue. The password manager is prompted in both versions of flutter, but in 3.19.2, it doesn't know which password to use, while in 3.16.9 it does know. Take a look at my screenshots for reference.

I believe you must have this file setup on your website for this to work: `.../.well-known/apple-app-site-association`

**Comment by huycozy** [comment]
It could be an issue on `3.10.6` as well since I saw the same issue at https://github.com/flutter/flutter/issues/135948. He also uses a lower iOS version `iOS 15.7.7` (not sure if it's related). To ensure that this doesn't depend on a separate implementation on Dart side, could you try with this minimal sample code?

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AutofillPage extends StatefulWidget {
  const AutofillPage({Key? key}) : super(key: key);

  @override
  State<AutofillPage> createState() => _AutofillPageState();
}

class _AutofillPageState extends State<AutofillPage> {
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: AutofillGroup(
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                TextFormField(
                  decoration: const InputDecoration(labelText: 'Username'),
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Please enter username';
                    }
                    return null;
                  },
                  autofillHints: const [AutofillHints.username],
                ),
                TextFormField(
                  decoration: const InputDecoration(labelText: 'Password'),
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Please enter password';
                    }
                    return null;
                  },
                  obscureText: true,
                  autofillHints: const [AutofillHints.password],
                ),
                const SizedBox(height: 16),
                ElevatedButton(
                  onPressed: () {
                    final validated = _formKey.currentState!.validate();
                    if (!validated) return;

                    TextInput.finishAutofillContext();
                  },
                  child: const Text('Login'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by diego-tread** [comment]
Hello, looks like I'm seeing the same issue using your example. 3.16.9 works as expected and 3.19.2 still does not. Images for reference.

### **Flutter 3.16.9**
![flutter_3 16 9](https://github.com/flutter/flutter/assets/133052302/65018be1-f0ee-46dc-b72a-ff762b30ec96)

### **Flutter 3.19.2**
![flutter_3 19 2](https://github.com/flutter/flutter/assets/133052302/8806c8e1-52ca-4c15-9a56-b8db11340f81)

**Comment by huycozy** [comment]
Thanks for checking. I also check this on iPadOS 17.2 but there is also only Passwords button there (without suggesting an account). Perhaps my setup has something corrupted with Associated Domains. Despite that, since this is reproduced on your end with minimal sample code, I will label this to get more input from others.

**Comment by huycozy** [comment]
@diego-tread `Associated Domains` issue seems to be solved on my end. So I re-visited the Autofill issue but can't reproduce it on the latest Flutter stable channel 3.19.3. It works as expected on my device `iPhone 7, iOS 15.8`:

<details>
<summary>Demo</summary>


https://github.com/flutter/flutter/assets/104349824/7859acfa-82ab-4ee1-9caf-39d13e2368ce


</details>

**Comment by diego-tread** [comment]
Hello, I upgraded to Flutter 3.19.3 just now and tried again. Flutter 3.19.3 doesn't resolve the issue for me, and it's still only 3.16.9 that works as expected.

Any other ideas for things I can try, or things to give you to help triage?

**Comment by justinmc** [comment]
CC @LongCatIsLooong from triage.

**Comment by diego-tread** [comment]
Hello @justinmc | @LongCatIsLooong | @huycozy 
Is there anything else that I can provide to help triage this issue further and not let it become stale?
If you are unable to reproduce, I am more than happy to hop on a zoom call to pair.
Best

**Comment by MyBuzzTechnologies** [comment]
Any progress on these? Autofill has been broken for a while now, with lots of related bugs reports but nobody seems interested in fixing them. We've just had to roll back to 3.16.9 because of these issues which is real pain.

**Comment by DylanCross** [comment]
Same issue. Autofill was working fine 2 months ago. Now doesn't fill correctly on iOS. 

It has various odd behaviors. I've seen: 

1: Clicking suggestion fills both fields. TouchId check is given after already filled. 
2: Choosing saved cred from list > TouchId check is made. But fields are left blank. 

When fields are left blank, sometimes adding a character causes the fields to populate. But the typed character will be appended. Sort of as expected.

**Comment by xvrh** [comment]
@LongCatIsLooong this is indeed a duplicate but the other issue is locked. And for some reason the fix was never cherry picked to stable.

**Comment by LongCatIsLooong** [comment]
Ah the fix was reverted. Feel free to open a [new cherrypick request](https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-Cherrypick-Process.md) for the [reland](https://github.com/flutter/flutter/pull/148984/files)
