### ISSUE TITLE
Add Flutter SDK constraint to our plugins

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#14461]
Our plugins in [flutter/plugins](https://github.com/flutter/plugins/) have traditionally [not](https://github.com/flutter/plugins/blob/master/packages/local_auth/pubspec.yaml) stated a Flutter SDK constraint. Heading into beta, we should consider adding constraints.

**Comment by mit-mit** [comment]
cc @mravn-google I think we should do this for milestone 3. WDYT?

**Comment by mravn-google** [comment]
We'll do this once we have a first beta release out.

**Comment by mit-mit** [comment]
\o/
