### ISSUE TITLE
Android scenario app tests with platform views + rotations sometimes display different "gray" color

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144657]
[For example](https://flutter-engine-gold.skia.org/detail?grouping=name%3DPlatformTextureUiTests_testPlatformViewRotate%26source_type%3Dflutter-engine&digest=34d776183971490cc1846f8d4028b613):

![image](https://github.com/flutter/flutter/assets/168174/3158432a-503f-42bf-93f4-bc123a90c509)

I was hoping this would be resolved by https://github.com/flutter/engine/pull/51169, but it was not.

/cc @dnfield @jonahwilliams for any other ideas. A specific color to be set instead of relying on the default?

**Comment by matanlurey** [comment]
@gmackall I wonder if this is something you could potentially help with?

Other ideas welcome, but otherwise I might suggest just trying to set a specific color instead of using the default?

**Comment by jonahwilliams** [comment]
If this is due to an animation we can't control, like rotation, we could try forcing it to speed up with something like: https://www.androidpolice.com/2016/10/22/guide-set-custom-animation-speed-android-works-stock-devices/

**Comment by matanlurey** [comment]
Gray I'm not sure how you prefer to be tagged, I've assigned you but if it's not something you can take on reasonably soon please assign it back. Thanks!

**Comment by gmackall** [comment]
Thanks for the tag, I should be able to take a look tomorrow!

**Comment by matanlurey** [comment]
Bumping to P1, as @jason-simmons pointed out:

> There has been a recent increase in Skia Gold comparison failures in the linux_android_emulator_skia_tests builder.  6 out of the past 13 runs failed (https://ci.chromium.org/p/flutter/g/engine/console)

AFAICT this is the only test experiencing this problem (at least at this scale), and it seems entirely due to the "grey-ness" factor changing.

**Comment by gmackall** [comment]
Capturing discussion from @matanlurey offline that neither of us is sure where the grey box comes from in the first place, so that is the first thing I will try to figure out

**Comment by gmackall** [comment]
> Capturing discussion from @matanlurey offline that neither of us is sure where the grey box comes from in the first place, so that is the first thing I will try to figure out

Doesn't directly answer this, but there is a color change on the transition between tests that seems very likely to be the culprit here. Need to figure out if/why the screenshot could be happening before we finish the transition in our out of each case.

[device-2024-03-07-152047.webm](https://github.com/flutter/flutter/assets/34871572/a9b7a1f9-57ab-4eda-93e5-5ca70032cbef)

**Comment by gmackall** [comment]
Still trying to recreate this, ran the test 100 times with `seq 100 | xargs -I{} dart ./testing/scenario_app/bin/run_android_tests.dart --out-dir=../out/android_debug_unopt_arm64 --smoke-test=dev.flutter.scenariosui.PlatformTextureUiTests --logs-dir=/Users/mackall/Desktop/MultipleCases/logs_dir/run{}`

and compared the output images with imagemagick after combining the logs
`seq 100 | xargs -I{} magick compare -verbose -metric mae combined_logs/copy1.png combined_logs/copy{}.png diffs/diff{}rnd1.png`

and didn't find any differences (ex:) 
```
Image: combined_logs/copy5png
  Channel distortion: MAE
    red: 0 (0)
    green: 0 (0)
    blue: 0 (0)
    all: 0 (0)
```
I wasn't using the emulator pulled in by gclient though, I'm going to try the above again with the exact same emulator in case that makes a difference here

**Comment by gmackall** [comment]
Looks like there is a `--no-window-animation` flag we can pass, which gets rid of the opening and closing animations. But I still see a moment of different color at the end of tests.

**Comment by jonahwilliams** [comment]
Can we set all of the animation scale values from https://github.com/flutter/flutter/issues/144657#issuecomment-1980008823 down to zero in the run script?

**Comment by gmackall** [comment]
Ok I believe I've fixed this by setting the splash screen color to be transparent, see:
[Uploading translucentsplash.webm…]()

**Comment by jonahwilliams** [comment]
Woot!

**Comment by matanlurey** [comment]
> Ok I believe I've fixed this by setting the splash screen color to be transparent, see: [translucentsplash.webm](https://github.com/flutter/flutter/assets/34871572/8ab5d79f-0239-4bbd-8c57-80590ebbd9f3)

YESSSSSSSSSSS.
