### ISSUE TITLE
FlutterMacOS.xcframework does not get updated during build

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#144716]
When building local engine after changes `FlutterMacOS.framework` gets properly rebuilt, but `FlutterMacOS.xcframework` remains unchanged. This affects `flutter run --local-engine=...` for example.

```
> ls -l FlutterMacOS*

-rw-r--r--  1 Matej  staff  148 Mar  6 22:01 FlutterMacOS.stamp

FlutterMacOS.framework:
total 0
lrwxr-xr-x  1 Matej  staff   29 Mar  6 22:01 FlutterMacOS -> Versions/Current/FlutterMacOS
lrwxr-xr-x  1 Matej  staff   24 Mar  6 22:01 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 Matej  staff   24 Mar  6 22:01 Modules -> Versions/Current/Modules
lrwxr-xr-x  1 Matej  staff   26 Mar  6 22:01 Resources -> Versions/Current/Resources
drwxr-xr-x  4 Matej  staff  128 Mar  6 22:01 Versions

FlutterMacOS.xcframework:
total 8
-rw-r--r--  1 Matej  staff  741 Mar  6 11:24 Info.plist
drwxr-xr-x  3 Matej  staff   96 Mar  6 11:24 macos-arm64
````

All files inside FlutterMacOS.xcframework are from 11:24, while current build finished at 22:01.

**Comment by jmagman** [comment]
As a workaround until this is fixed, run `rm -rf out/host_debug_unopt_arm64/FlutterMacOS.xcframework` before `ninja` to force the xcframework to be recreated.
