### ISSUE TITLE
[video_player] Add `onScrubbingCallback` to `VideoProgressIndicator`

### ISSUE THREAD

**Issue by pedrolemoz** [flutter/flutter#144777]
### Use case

In the `VideoProgressIndicator` widget, is not possible to know when the user scrubbed to another position in the video. I need to send some information about the video status to an API, and I need a way to "listen" when the video position is changed by `VideoProgressIndicator`.

### Proposal

Add a callback named `onScrubbingCallback`, as a `void Function(Duration)?` to `VideoProgressIndicator`.

It could be as the following code:

```dart
VideoProgressIndicator(
  controller,
  allowScrubbing: true,
  onScrubbing: (Duration duration) {
    // Do something here
  },
)
```

**Comment by stuartmorgan** [comment]
> I need a way to "listen" when the video position is changed by `VideoProgressIndicator`

Could you elaborate on the use case here? Why do you need to know if the change came from a specific UI element, rather than monitoring the video itself for seek events?

**Comment by pedrolemoz** [comment]
Thank you for your response, @stuartmorgan.

I need to send some information about the video that is currently playing to an API, and this includes information about when the user transitions from one duration to another.

I haven't found a way to accomplish this in the current version of the package. Although I could use a listener in the controller, it would require a lot of verifications throughout the video's duration. For my use case, a callback within the `VideoProgressIndicator` seems like a simple and effective solution and is similar to the behavior of certain Flutter widgets.

**Comment by Dannyzheng831** [comment]
Hi, I also need somethings like onScrubbing...  Because I need always show video control layer when Scrubbing..  After finsh Scrubbing... my video control layer will auto hide..... thanks!

**Comment by stuartmorgan** [comment]
@Dannyzheng831 That seems like a different use case; presumably you would not want to auto-hide the UI if someone touched the scrub control and then left their finger sitting there for a long time without moving it, but that wouldn't send a callback for position changes.

**Comment by pedrolemoz** [comment]
> Could you elaborate on what verifications you are referring to?

@stuartmorgan yes, I can elaborate.

Consider this example:

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class ScrubbingCallBackExample extends StatefulWidget {
  final void Function(Duration duration) callback;

  const ScrubbingCallBackExample({super.key, required this.callback});

  @override
  State<ScrubbingCallBackExample> createState() =>
      _ScrubbingCallBackExampleState();
}

class _ScrubbingCallBackExampleState extends State<ScrubbingCallBackExample> {
  late VideoPlayerController _videoPlayerController;
  var _latestDuration = Duration.zero;

  void _videoPlayerControllerListener() {
    final currentDuration = _videoPlayerController.value.position;
    final difference =
        currentDuration.inMilliseconds - _latestDuration.inMilliseconds;

    if (difference > 1000) {
      widget.callback(currentDuration); // onScrubbingCallback?
    }

    _latestDuration = currentDuration;
  }

  @override
  void initState() {
    super.initState();
    // Init State implementation (setting up _videoPlayerController, for example)
    _videoPlayerController.addListener(_videoPlayerControllerListener);
  }

  @override
  void dispose() {
    _videoPlayerController.removeListener(_videoPlayerControllerListener);
    _videoPlayerController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // Widget goes here
    return const Placeholder();
  }
}
```

To achieve the same result as the proposed callback, I had to add a listener to `VideoPlayerController`, and also store the latest video duration in a variable inside `_ScrubbingCallBackExampleState`. Then, I can perform some verifications using the latest and current durations of the video, and figure out whether the user seeked to another duration. In my example, if the difference in milliseconds is greater than 1000, a callback function is executed.

This isn't optimal, since at every single change of VideoPlayerController value, my verification occurs. In fact, the value is changed at every event dispatched by the platform, as seen [here](https://github.com/flutter/packages/blob/main/packages/video_player/video_player/lib/video_player.dart#L439-L481).

This approach does work, but is prone to errors. It would be way easier if we had the proposed callback. There wouldn't be any verifications being performed at every 500 milliseconds, just a function being called when the user seeks to a new duration.

> So if someone were to seek some other way, would you want that information or not?

I didn't think about another way of seeking, but similarly, we can add an optional `onSeekCallback` to [`seekTo`](https://github.com/flutter/packages/blob/main/packages/video_player/video_player/lib/video_player.dart#L628-L639) function inside the `VideoPlayerController`, although I think this is another use case that may require another solution.

> I'm trying to understand whether this use is actually paired to the UI element, or whether you are just trying to add the listener there because it seems easiest.

While it's indeed the easiest solution, it seems better than implementing this manually, as shown above. We can use this callback in the `VideoPlayerController` or in `VideoProgressIndicator`, as I originally proposed. The goal is keep track of the user action. For my use case, I created a custom widget to act as my progress indicator that implements this callback. I want to bring this solution to the community, so I opened this issue and the pull request.

**Comment by stuartmorgan** [comment]
> similarly, we can add an optional `onSeekCallback` to [`seekTo`](https://github.com/flutter/packages/blob/main/packages/video_player/video_player/lib/video_player.dart#L628-L639) function inside the `VideoPlayerController`, although I think this is another use case that may require another solution

How is it a different use case? That's the core question I'm trying to understand; is the use case you want to solve such that you want a callback if *and only if* the seek was done with that one specific UI element, and not any other seek action? I.e., if there were an `onSeek` callback on `VideoPlayerController`, it would *not* address your use case?

> While it's indeed the easiest solution, it seems better than implementing this manually, as shown above.

Yes, but those aren't the only two options; it could, as you noted above, be added directly to the controller, which would make it usable in more situations.
