### ISSUE TITLE
Add `showModalBottomSheet` in `ScaffoldMessengerState`

### ISSUE THREAD

**Issue by lsaudon** [flutter/flutter#144767]
### Use case

I want to be able to display a modal anywhere in the application, inviting the user to update the application.

### Proposal

Adding [showModalBottomSheet](https://api.flutter.dev/flutter/material/showModalBottomSheet.html) or equivalent to [ScaffoldMessengerState](https://api.flutter.dev/flutter/material/ScaffoldMessengerState-class.html) would solve my problem, as it does for [showSnackBar](https://api.flutter.dev/flutter/material/ScaffoldMessengerState/showSnackBar.html) at present.

**Comment by darshankawar** [comment]
> I want to be able to display a modal anywhere in the application

@lsaudon `modalBottomSheet` is mostly located at the bottom of the screen per material design, so I am unsure if you want to use it at other location on the screen, this widget would be correct one or not or will be it suffice per UI guidelines.

Have you looked at `MaterialBanner` ?
