### ISSUE TITLE
[google_maps_flutter] [Proposal] Update to Google maps 18 SDK

### ISSUE THREAD

**Issue by ChristineWasike** [flutter/flutter#144760]
### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

No

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
name: maps_app_sdk_sample
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
     cached_network_image: ^3.3.1
     cupertino_icons: ^1.0.6
     google_maps_flutter: ^2.5.3
     flutter_cache_manager: ^3.3.1
     flutter_riverpod: ^2.4.10
     video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

### Steps to reproduce

I received an email from Google Maps Platform highlighting this:

> You may have projects using the legacy renderer that will be decommissioned by March 3, 2025. Apps built with the Maps SDK for Android will be automatically updated to the latest renderer beginning March 4, 2024.

I only have one app tied to this Google account, and it is a Flutter app using the `google_maps_flutter` package.

### Expected results

No email highlighting use of the legacy renderer.

### Actual results

I received an email from Google Maps Platform highlighting this:

> You may have projects using the legacy renderer that will be decommissioned by March 3, 2025. Apps built with the Maps SDK for Android will be automatically updated to the latest renderer beginning March 4, 2024.

### Email from Google Maps Platform
<details open><summary>Email details</summary>

This is only an email referencing the use of the Android SDK.

More from the email:

Hello Google Maps Platform Customer,
This is a follow up to the announcements sent in 2021 and 2022 regarding the new renderer for Maps SDK for Android. To provide an improved user experience and app performance, apps built with the Maps SDK for Android will be automatically updated to the [latest renderer](https://notifications.google.com/g/p/ANiao5qrEN9QixCwLlUa2HiB1QYQ9KxFxDpSYkS2ExcvkYAvBdTPlxaqCAOUrErIkeYjiFs39XYt1HKUKt2B0yR3Y4H7EhdyVjNMJ4T-X4lrB2uj8En1nTLnjbgrkMe4fdpVRcJufC9ZXGNrXpPBByLCQM0XK4nPHXILvCqzpdw9vQ0jeO3GkwWSK3Mcdue18jbiSf1KLey-0kSE521DugbiR_kXe2E0_a4CGCvJkOCVuDGtaKyDz7BQ6I6R2HYLJeC_Hw) beginning March 4, 2024. The legacy renderer is scheduled for decommissioning on March 3, 2025.

**What do I need to know?**
The new renderer was introduced in Maps SDK for Android version 18.0 in an opt-in manner. It is offered as a default starting on version 18.2, with an option to [specify the Legacy renderer (Renderer.LEGACY)](https://notifications.google.com/g/p/ANiao5rOCmi5EWXvEIF22wa9aH4W3Q_Crhyih74dRUxjPYES67QMMa3QwBAqbaGz8mE9KS45crR3FQTvTsSIwPOsKlAV3bVlZXqlKTnc7g3zNVmVWT-1_d9l9u2Ue0pyzMbBl4u4Cxt6G0NlZdCV7ErIIKwl0b1LCRTNgoczDr3-_F31rlCmFuAknT9uDWGmo5GL7IKwQatoHYcUv9CVsRgKt0ixKocA7InhWDueH_CWqM9ki8VyGsfbNPtJlP48hCpgVb47BgGPuy5H). Your app may be currently using the legacy renderer in two situations.
- Situation 1.If you use Maps SDK for Android version < 18, or 18.0-18.1 without opting in the new renderer: The automatic update to the latest renderer will be rolled out to the Android devices in a gradual ramp up mode and is expected to impact 100% of all [supported devices](https://notifications.google.com/g/p/ANiao5p3-faK-R4iY-be_RL9L6X-fS8nD7HA4nL3EUsGsCA61362SGJ23PkFesSskJ0eTZYv-nealHXVHImol-G_GLP7C-5cYyb-5tfrEmlL2T0m1Co-5kOCdc8hTy0ZMA2uTG9VOllAdxuAIY3KAg7apAaPLYzLe9YDqnaRAh6jvzv3co49gJryECyEtoY5mTs2RBiQYMcFusBIZ-1MWCHsK3qsCEESc_Ypa45-AQunq6FOXTk-BRh5lOdms2bS2aK56OMVL1W0njUdkyRPKbKw-iJqPg) by the end of 2024.
- Situation 2. If you specify the legacy renderer (on version 18.0 or later):
Your application will continue receiving the legacy renderer until March 2025. Starting in March 2025, you will get the new renderer even if you specify the Legacy renderer.
During the migration period, Google will continue to provide support and fixes to major bugs and outages on the legacy renderer. New features and improvements are only offered on the new renderer.
The new renderer is currently only available on Android phones. If your app is used on Wear OS or Android Go, the new renderer will be available in Google Play Services at a later time. Please follow the progress on this rollout by starring this [issue tracker entry](https://notifications.google.com/g/p/ANiao5rPMmWkdd1mhw-CGpQ6JikOiP1yBMtq5b4irWxXSOejuEDyfeJ_qkY_w3B-GTKfm0-gzxypDFoWc8-6lxuXxm7zbBn6udTM8ccqAcEcUKljBg4SNvYT00hMMQO9lhse4pqS3pB8HHHdsYSEUN38jsPus2i3tECshffd8KN_QqA3GvUz5eXJqHd_8I3b9ZHgoNV5BBhhcJirK07xzG3exUuTbZx3).

**What do I need to do?**
No action is recommended if your app already uses Maps SDK for Android v18.2.0 and does not specify a renderer during the initialization process.
Updating to the latest renderer in the Maps SDK for Android may introduce a slight change to the performance and behavior of the maps in your app. Google does not expect this to cause any operational issues.
We recommend that developers of mission-critical apps test their application with the new renderer ahead of the automatic update (happening in March 2024 or March 2025 depending on your situation above), in order to limit risks of potential issues. You can do this by [updating the dependencies](https://notifications.google.com/g/p/ANiao5o5mM5RnE9cE8HfVi4ntFJ0WXELNwv7VfSzi9eq5LswhJ3Nye9uv0uGtEf7t-8XZ_wATIaCfYtOEIXiPE32Z25raNdPhlnnmIFO5Rnom6MSupnq4TtyxVHLAH3bs-Dq4A8nMhTBtzKqBl3OyzxOFt_W3f6YmGcT-pOPrtBRH5VlJq-mJdiYyVeWFKzJa0hnIZUS5tpFCGUbIcdGmAJkvDhsBVrxZnw45s0y6GXKUcsCjS795ziFLbwY9c0XrgFhsrbkpZ2sbXju6Sym-YsME0Odmzk8) for your app to the Maps SDK for Android version 18.2.0 or later, without [specifying the Legacy renderer (Renderer.LEGACY)](https://notifications.google.com/g/p/ANiao5rOCmi5EWXvEIF22wa9aH4W3Q_Crhyih74dRUxjPYES67QMMa3QwBAqbaGz8mE9KS45crR3FQTvTsSIwPOsKlAV3bVlZXqlKTnc7g3zNVmVWT-1_d9l9u2Ue0pyzMbBl4u4Cxt6G0NlZdCV7ErIIKwl0b1LCRTNgoczDr3-_F31rlCmFuAknT9uDWGmo5GL7IKwQatoHYcUv9CVsRgKt0ixKocA7InhWDueH_CWqM9ki8VyGsfbNPtJlP48hCpgVb47BgGPuy5H).

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-KE)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
The plugin has been using 18 for several years, and 18.2 for over four months.

**Comment by ChristineWasike** [comment]
@stuartmorgan Should I ignore the email?

**Comment by stuartmorgan** [comment]
That email is about actions you can take at the level of your application; whether you ignore it or not it's up to you.

There's no work needed here in the plugin, which is why I closed the issue.
