### ISSUE TITLE
FrameTiming API is inaccurate for elapsed time

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#144782]
Here is an example "Flutter.Frame" event that is [sent](https://github.com/flutter/flutter/blob/2ea5ca0345039254d8eae559b07eb8e2f0b9941a/packages/flutter/lib/src/scheduler/binding.dart#L1348) with frame timing information.
`{number: 97, startTime: 693913220037, elapsed: 397728946779, build: 1644, raster: 6306, vsyncOverhead: 397728938765}`

The elapsed time is supposed to be in microseconds, but this would be 397728.946779 seconds. CC @dnfield 

```
Flutter 3.20.0-16.0.pre • channel [user-branch] • unknown source
Framework • revision 0d8eafb006 (8 days ago) • 2024-02-28 21:55:50 +0000
Engine • revision 455c814fe5
Tools • Dart 3.4.0 (build 3.4.0-186.0.dev) • DevTools 2.33.0-dev.11
```

I am debugging a Flutter app on macos desktop

**Comment by kenzieschmoll** [comment]
This does not reproduce on an iOS simulator. The elapsed time value for those events are in the normal range:
`{number: 52, startTime: 695234528651, elapsed: 4305, build: 2710, raster: 1355, vsyncOverhead: 184}`

**Comment by dnfield** [comment]
I think this is probably an issue in the vsync waiter implementation that macOS embedding is using. /cc @cbracken maybe?

**Comment by jonahwilliams** [comment]
FYI @knopp in case you are familiar with this code.

**Comment by knopp** [comment]
Your particular engine revision has CVDisplayLink based vsync waiter implementation that was reverted shortly after because it made assumption about the clock used in embedder, which has changed few days before it landed (from mach_absolute_time to CLOCK_MONOTONIC_RAW. This causes the broken frame timings.

You need to move to newer engine revision.

**Comment by gspencergoog** [comment]
It was re-relanded in https://github.com/flutter/engine/pull/51210

**Comment by gspencergoog** [comment]
> You will need to move to newer engine revision.

@kenzieschmoll Could you please try out the newest engine revision and see if it works now for you?

**Comment by kenzieschmoll** [comment]
With the latest flutter, the elapsed times look correct:
`{number: 25, startTime: 1309313793928, elapsed: 7772, build: 4580, raster: 2360, vsyncOverhead: 654}`
