### ISSUE TITLE
Label TextStyle in SnackBarAction

### ISSUE THREAD

**Issue by KunjKanani** [flutter/flutter#144769]
### Use case

I am using SnackBarAction. I want to change the label text style. Currently, It has only support for textcolor. I purpose to introduce TextStyle for labels.

### Proposal

```
SnackBarAction(
  label: 'Go To Cart',
  // labelStyle: Style Support
  onPressed: () {
  },
),
```

**Comment by darshankawar** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/46599
