### ISSUE TITLE
Upload packages iOS native test xcresult bundle on test failure

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#144795]
On native iOS Xcode build test failures upload the xcresult bundle to the logs location so we can open it in Xcode and see the screenshots, etc.  This is possible as of https://github.com/flutter/flutter/issues/121535.  

This is where it would be updated:
https://github.com/flutter/packages/blob/903f03add169c39d3f19bc70980af3f0862869a9/script/tool/lib/src/common/xcode.dart#L34-L56

Here is how it's done in the framework repo:
https://github.com/flutter/flutter/blob/874804e511109a4028fd9b874836e5f82fe44103/dev/devicelab/lib/framework/ios.dart#L194-L219

https://github.com/flutter/flutter/blob/874804e511109a4028fd9b874836e5f82fe44103/dev/devicelab/lib/framework/ios.dart#L226-L241

where `dumpDirectory` is `platform.environment['FLUTTER_LOGS_DIR']`
https://github.com/flutter/flutter/blob/36e09ff34355fba4602b62b9628e533836e0d494/dev/devicelab/lib/framework/host_agent.dart#L26-L28

This would particularly be helpful when tests are run in parallel because evidently it doesn't show the failures in stdout:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8754096679487031185/+/u/Run_package_tests/native_test/stdout

**Comment by jmagman** [comment]
@stuartmorgan I thought we had an issue for this but I can't find it.

**Comment by hellohuanlin** [comment]
random thought - maybe we can share some common infra for these 2 repos?
