### ISSUE TITLE
Firebase Auth 

### ISSUE THREAD

**Issue by Safiul-Lathif** [flutter/flutter#144750]
firebase  OTP is not working in android version 12 and below after uploading application into play store 
can some one help me to fix this issue
i am using  SDK version
SDK: ">=2.17.5 <4.0.0"

firebase_core: ^2.15.0
cloud_firestore: any
firebase_auth: ^4.7.2

**Comment by danagbemava-nc** [comment]
Firebase auth is not managed by the flutter team. Any issues you face using it should be reported on their repo. 

Closing from here as this is not a flutter issue. 

Please make sure you're facing this issue on the latest versions of the firebase libraries before you report the issue. 

Thank you
