### ISSUE TITLE
IOS auto scrolling issue with sliver app bar

### ISSUE THREAD

**Issue by Aadesh1803** [flutter/flutter#144762]
### Steps to reproduce

1. In the home screen you can see horizontal listview with week 0, week 1, week 2.
2. Click on any of the week little bit beside of that week or anywhere near to that week.
3. you will see that it is scrolling automatically. 
4. this behaviour is only in IOS. - debug mode or release mode. (In android it is working fine.)

https://github.com/flutter/flutter/assets/131435534/1513c2e6-a4b9-4912-97b3-e90da8b6b5dd

### Expected results

It should not scroll automatically becuase there is no any scrollcontroller used. why is it scrolling automatically by clicking on listview in IOS

### Actual results

I have added sliver app bar and below that sliver appbar there is tabbar view .
In second tab bar view i am having two listview.builder. one is horizontal and scond is vertical. when i am trying to click on horizontal listview.builder's any item. it is scrolling the whole screen automatically in IOS (Simulator and real device both). 

### Code sample

<details open><summary>Code sample</summary>

 [https://github.com/Aadesh1803/ios-demo](url)

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[

https://github.com/flutter/flutter/assets/131435534/43ed6619-538d-4beb-be0a-216839b77095

]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.13.6, on macOS 13.0 22A380 darwin-x64, locale en-IN)
    • Flutter version 3.13.6 on channel stable at /Users/imac/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 months ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.80.2)
    • VS Code at /Users/imac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Aadesh1803 
Please don't file multiple issues for same reason. You already filed this here https://github.com/flutter/flutter/issues/144672 for which we provided feedback on it.
Closing this issue.

**Comment by Aadesh1803** [comment]
@darshankawar , I have tested with flutter's latest stable version itself but it is not working. waiting for your positive reply.

**Comment by Aadesh1803** [comment]
Can someone help me out. i am facing this issue in IOS.
