### ISSUE TITLE
Migrate src/third_party/angle to src/flutter/third_party/angle

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#144786]
`build_overrides/angle.gni` and `build_overrides/build.gni` are the only two remaining references to Abseil in the buildroot (see: https://github.com/flutter/flutter/issues/144201) and the latter only in a comment.

Part of #67373.

**Comment by cbracken** [comment]
Completed in flutter/engine#51270.

**Comment by zanderso** [comment]
The autoroller config will need to be updated as well.

**Comment by cbracken** [comment]
Looks like this was fixed by @erock2112 in https://skia-review.googlesource.com/c/skia-autoroll-internal-config/+/824416.

Thanks Eric, and apologies for missing this step!
