### ISSUE TITLE
[Impeller] unexpected backdrop filter benchmark changes on StC flag flip.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#144748]
Raster went up, GPU go down!

I thought it was a bug caused by https://github.com/flutter/engine/pull/51118 , but reverting that has not moved the benchmarks.

Raster

https://flutter-flutter-perf.skia.org/e/?begin=1709695163&end=1709781563&queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dbackdrop_filter_perf_ios__timeline_summary&selected=commit%3D39677%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C

GPU

https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_gpu_frame_time%26sub_result%3D99th_percentile_gpu_frame_time%26sub_result%3Daverage_gpu_frame_time%26test%3Dbackdrop_filter_perf_ios__timeline_summary&selected=commit%3D39678%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_frame_time%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C

Probably needs some investigation to make sure everything is working as expected.

**Comment by jonahwilliams** [comment]
There were actually a few benchmarks that had raster time regressions, see also new gallery (ignore the spike, that was a revert)

https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DPixel_7_Pro%26sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dnew_gallery_impeller__transition_perf&selected=commit%3D39677%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C

Are we doing some extra work in the depth clips? It seems to be substantial

**Comment by jonahwilliams** [comment]
Looks like we're doing better:

https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dbackdrop_filter_perf_ios__timeline_summary&selected=commit%3D39720%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C

**Comment by bdero** [comment]
Yup yup, https://github.com/flutter/engine/pull/51259 indeed got rid of most of the clips.

But not sure why the GPU time benchmark dipped from this in the first place. 🤔  I wonder if there's an issue with the benchmark. Maybe missed frames aren't getting discounted when averaging (or are dropped frames getting otherwise counted as instantaneous)?
![image](https://github.com/flutter/flutter/assets/919017/c8917314-85f4-48cd-aaa4-8c81811284ac)

**Comment by jonahwilliams** [comment]
on mobile devices the answer is probably thermal throttling. i.e. before the GPU is continually busy, it clocks down to keep from overheating. After with the raster time regression, its getting long breaks and doesn't have to throttle down.

**Comment by jonahwilliams** [comment]
Closing as fixed!
