### ISSUE TITLE
[infra + release] Linux|Mac engine_release_builder failing on benchmark tests.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#144749]
Link to failing build: https://ci.chromium.org/p/dart-internal/builders/flutter/Linux%20engine_release_builder/848?

**Comment by godofredoc** [comment]
Benchmarks needs to be run separately and run only on main branch.

**Comment by godofredoc** [comment]
`testing/run_tests.py --variant host_release --type dart,dart-host,engine,benchmarks --engine-capture-core-dump` is still trying to run golden tests.

```
Test "toImage and toImageSync have identical contents": Passed
Test "Canvas.drawParagraph renders tab as space instead of tofu": Passed
Skia gold comparison failed: Exception: Skia Gold received an unapproved image in post-submit 
testing. Golden file images in flutter/engine are triaged 
in pre-submit during code review for the given PR.

Visit https://flutter-engine-gold.skia.org// to view and approve 
the image(s), or revert the associated change. For more 
information, visit the wiki: 
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold --------------------------------
stdout: Given image with hash 43af40a9baa67b933cde8f2dac7f28ac for test canvas_test_toImage
Expectation for test: 323eb39c89e02d74ef505504c53d5c06 (positive)
Expectation for test: 3f5895ca785071873070f39b6ee018d2 (positive)
Expectation for test: 43af40a9baa67b933cde8f2dac7f28ac (positive)
```

**Comment by godofredoc** [comment]
Link to failures on mac: https://ci.chromium.org/p/dart-internal/builders/flutter/Mac%20engine_release_builder/528

**Comment by zanderso** [comment]
Summarizing the conclusion of the discussion offline: We should try to unblock the release builders by ensuring that the `GOLDCTL` environment variable is not set.

**Comment by godofredoc** [comment]
CL to skip setting GOLDCTL: https://flutter-review.googlesource.com/c/recipes/+/55900

**Comment by goderbauer** [comment]
@godofredoc in critical triage we assigned this to you since it looks like you are working on this. Please re-assign if that's not accurate. Thank you.

**Comment by XilaiZhang** [comment]
From triage: this has been fixed
