### ISSUE TITLE
[go_router] [go_router_builder] How to use (or even possible?) TabBar with Bottom Navigation bar

### ISSUE THREAD

**Issue by ascentman** [flutter/flutter#144727]
I would like to have a link on `Phone tab` of `Feedback screen`. How to add this if I already have one shell router for bottom navigation. Reading a [(Nested Navigation doc)](https://docs.page/bizz84/go_router_archived/nested-navigation) I noticed TabBar with state preserving but I stuck on combining these 2 nested navigations.

```
final _shellNavigatorMainKey = GlobalKey<NavigatorState>(debugLabel: 'courses');
final _shellNavigatorFeedbackKey =
    GlobalKey<NavigatorState>(debugLabel: 'feedback');
final _shellNavigatorProfileKey =
    GlobalKey<NavigatorState>(debugLabel: 'profile');

@TypedStatefulShellRoute<ScaffoldShellRoute>(
  branches: [
    TypedStatefulShellBranch<MainBranch>(.....),
    TypedStatefulShellBranch<FeedbackBranch>(
      routes: [
        TypedGoRoute<FeedbackRoute>(
          path: FeedbackRoute.path,
            routes: [
             ???
          ],
        ),
      ],
    ),
    TypedStatefulShellBranch<ProfileBranch>(...),
  ],
)

class ScaffoldShellRoute extends StatefulShellRouteData {
  const ScaffoldShellRoute();

  static Widget $navigatorContainerBuilder(
    BuildContext context,
    StatefulNavigationShell navigationShell,
    List<Widget> children,
  ) {
    return children[navigationShell.currentIndex];
  }

  @override
  Widget builder(
    BuildContext context,
    GoRouterState state,
    StatefulNavigationShell navigationShell,
  ) {
    return ScaffoldWithBottomNavBar(
      navigationShell: navigationShell,
    );
  }
}

class FeedbackBranch extends StatefulShellBranchData {
  static final $navigatorKey = _shellNavigatorFeedbackKey;
}

@TypedGoRoute<FeedbackRoute>(path: FeedbackRoute.path)
class FeedbackRoute extends GoRouteData {
  static const path = '/feedback';

  @override
  Page<void> buildPage(BuildContext context, GoRouterState state) {
    return const NoTransitionPage(
      child: ChatScreen(),
    );
  }
}
```

![Simulator Screenshot - iPhone 15 Pro - 2024-03-06 at 23 41 30](https://github.com/flutter/flutter/assets/16058309/0d032e2c-e6f4-49ed-ac2d-bc1406549ea8)

**Comment by huycozy** [comment]
Hi @ascentman 
>I noticed TabBar with state preserving but I stuck on combining these 2 nested navigations.

Could you be more specific? What is the issue you have? If it's about synchronizing TabBar index with StatefulNavigationShell, you can check [custom_stateful_shell_route.dart](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/custom_stateful_shell_route.dart) for ideas. 

Otherwise, please help to make the issue more clear by clarifying all fields in the bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml). Thanks!

**Comment by ascentman** [comment]
@huycozy thanks for pointing me out this example with `custom_stateful_shell_route.dart`(https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/custom_stateful_shell_route.dart)`

This is exactly what I was looking for: 

> This example also demonstrates how build a nested shell with a custom
> // container for the branch Navigators (in this case a TabBarView).

I will look through this example
