### ISSUE TITLE
Update flutter-devicelab-mac-37 to macOS 13

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#144719]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

This host has been missed in the upgrade, please upgrade to macOS 13, similarly to all other devicelab hosts.

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
Upgrading MacOS 13.x onto mac-37 has been completed. Ticket is closed.
