### ISSUE TITLE
Flutter Google Map not showing country based content in IOS devices

### ISSUE THREAD

**Issue by nextsimo** [flutter/flutter#144773]
### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>
```lock
```
</details>

### Steps to reproduce

1. Start a Flutter application using the Google Maps package with a simple code example.
2. Notice that the Google Maps in the Flutter app displays the Western Sahara region, which is different from the official Google Maps that either omits this region or behaves differently on Android.

### Expected results

Google maps official app on Iphone :
![image](https://github.com/flutter/flutter/assets/41967952/01cb1c2a-ffe9-4c5a-9758-48c14733adba)

Same flutter code running on Android phone :

https://github.com/flutter/flutter/assets/41967952/71fe8899-d020-4148-93b1-07179cdb25d6

### Actual results

On Iphone IOS 17.1.2

https://github.com/flutter/flutter/assets/41967952/26468c5d-4ba9-4e54-85a8-cca94ba3f73a

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: MapSample()
      ),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller =
      Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(33.5731, -7.5898),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
    bearing: 192.8334901395799,
    target: LatLng(33.5731, -7.5898),
    tilt: 59.440717697143555,
    zoom: 19.151926040649414,
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        myLocationButtonEnabled: true,
        mapType: MapType.normal,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.startTop,
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    await controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-MA)
    • Flutter version 3.19.2 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (9 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/simo/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] VS Code (version 1.88.0-insider)
    • VS Code at /Applications/Visual Studio Code insider.app/Contents
    • Flutter extension version 3.85.20240301
```

</details>

**Comment by stuartmorgan** [comment]
Please see my question [here](https://github.com/flutter/flutter/issues/142908#issuecomment-1929961613) which was never answered in the original issue. The plugin does not control the behavior of the SDK, it only provides the ability to use it from Dart.

**Comment by nextsimo** [comment]
The functionality was previously working in an older version of Flutter, but I'm uncertain whether the issue stems from the Flutter SDK itself or the Google Maps SDK on iOS. This problem only emerged after I updated my Flutter app on iOS. Normally, the Google Maps SDK retrieves the region parameter from the client's location to display maps and political boundaries based on the user's location. However, this issue only occurs on real devices; when I run my app on an iOS simulator, it works perfectly. Please assist with this problem, as it is crucial for our clients, especially those in Morocco, to view the map correctly

**Comment by nextsimo** [comment]
ok thanks
