### ISSUE TITLE
EditableText widget not clears mask old values when using setter function

### ISSUE THREAD

**Issue by dipsy** [flutter/flutter#144896]
### Steps to reproduce

My flow is flutterflow.
1. I have some mask on TextField widget: `final phoneMask = MaskTextInputFormatter(mask: '+# (###) ###-##-##');`
2. I set initial value (or set value by action, it s no matter): `_model.phoneController?.text = '+1';`
3. In run mode (web or ios) I enter some text (for example 9( in phone field, but old value dont't saved, and I have only +9 in field.

### Expected results

+1 (9

### Actual results

+9

### Code sample

I cant create code example, because I use flutterflow. But I found problem with
package mask_text_input_formatter
It has `_resultTextArray` variable, which not updates when TextField controller sets new value by setter function.
package mask_text_input_formatter has special function `clear()` which is not used in editable_text.dart for delete old values.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![CleanShot 2024-03-10 at 11 41 46](https://github.com/flutter/flutter/assets/1336665/b8180d97-923b-4dc7-a062-837e9c70fc26)

</details>

### Logs

no errors in console

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale ru-RU)
    • Flutter version 3.19.3 on channel stable at /Users/dima/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (2 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone (Дмитрий) (mobile)  • 00008130-001A40C02491401C            • ios
      • iOS 17.4 21E219
    • iPhone 15 Pro Max (mobile) • D7D2D658-ED4A-40E0-B709-03B760DF3510 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64
      • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript
      • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
This seems like an issue with the `mask_text_input_formatter` package. Kindly file an issue on their repo so that it can be properly addressed. If you are redirected here, kindly provide a complete minimal reproducible flutter code sample without any third-party packages so that we can investigate this issue.

Thank you
