### ISSUE TITLE
"viewInsets.bottom" changes when TextFormField "isObscureText" changes

### ISSUE THREAD

**Issue by burekas7** [flutter/flutter#144897]
### Steps to reproduce

1. Create screen with SafeArea -> Scaffold -> SingleChildScrollView -> Column
2. In the Column add two TextFormFields.
    - Set the first one with `isObscureText: false`
    - Set the second one with `isObscureText: true`
3. Add additional child to the column: 
    - Padding with padding value = MediaQuery.of(context).viewInsets.bottom
    - I'm using it in order to push the widgets up when the keyboard is opened
4. When moving between the TextFields, there is kind of 'flickering' of the screen due to the changes in the  `viewInsets.bottom` value.

You can see in the results below how the value changes.

It's more noticeable and annoying with iPhone since the keyboard returns to the same size, 
compared to Pixel (Android) where the size just changes so it makes a bit of sense.

How can I avoid it?
Is it a bug?

---

### Expected results

When moving from `isObscureText: false` to `isObscureText: true`:

iPhone XR (iOS 17):
flutter: MediaQuery.of(context).viewInsets.bottom: 346.0
flutter: MediaQuery.of(context).viewInsets.bottom: 346.0

Pixel 4 (Android 13):
flutter: MediaQuery.of(context).viewInsets.bottom: 341.45454545454544
flutter: MediaQuery.of(context).viewInsets.bottom: 341.45454545454544

Samsung S8 (Android 9): (OK on both cases)
MediaQuery.of(context).viewInsets.bottom: 279.0
MediaQuery.of(context).viewInsets.bottom: 279.0

---

### Actual results

When moving from Username (`isObscureText: false`) to Password (`isObscureText: true`):

iPhone XR (iOS 17):
flutter: MediaQuery.of(context).viewInsets.bottom: 346.0
flutter: MediaQuery.of(context).viewInsets.bottom: 301.0000858306885
flutter: MediaQuery.of(context).viewInsets.bottom: 346.0

Pixel 4 (Android 13):
MediaQuery.of(context).viewInsets.bottom: 341.45454545454544
MediaQuery.of(context).viewInsets.bottom: 297.45454545454544

Samsung S8 (Android 9): (OK on both cases)
MediaQuery.of(context).viewInsets.bottom: 279.0
MediaQuery.of(context).viewInsets.bottom: 279.0

</details>

---

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Keyboard images:

- Username field: `isObscureText: false`
- Password field: `isObscureText: true`

iPhone XR (iOS 17):
<a href="https://postimg.cc/LgnQ1PVc" target="_blank"><img src="https://i.postimg.cc/LgnQ1PVc/temp-Imageli-Bf-WP.avif" alt="temp-Imageli-Bf-WP"/></a> <a href="https://postimg.cc/NKhCK52n" target="_blank"><img src="https://i.postimg.cc/NKhCK52n/temp-Image1-Yeb-Aj.avif" alt="temp-Image1-Yeb-Aj"/></a><br/><br/>

Pixel 4 (Android 13):
<a href="https://postimg.cc/4m3Hp5V7" target="_blank"><img src="https://i.postimg.cc/4m3Hp5V7/temp-Imageub2-Vf0.avif" alt="temp-Imageub2-Vf0"/></a> <a href="https://postimg.cc/qt2NpZVY" target="_blank"><img src="https://i.postimg.cc/qt2NpZVY/temp-Image-GPVqs-U.avif" alt="temp-Image-GPVqs-U"/></a><br/><br/>

Samsung S8 (Android 9): (OK on both cases)
<a href="https://postimg.cc/KKG6YRd2" target="_blank"><img src="https://i.postimg.cc/KKG6YRd2/temp-Image-Eu-ZRmq.avif" alt="temp-Image-Eu-ZRmq"/></a> <a href="https://postimg.cc/qhYSQQgJ" target="_blank"><img src="https://i.postimg.cc/qhYSQQgJ/temp-Images9xb-B0.avif" alt="temp-Images9xb-B0"/></a><br/><br/>

</details>

---

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-IL)
    • Flutter version 3.19.2 on channel stable at /Users/admin/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (12 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • SM G950F (mobile)     • ce031713eb0288210d        • android-arm64  • Android 9 (API 28)
    • iPhone (mobile) • 00008020-001059A91EE9002E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 122.0.6261.112
    ! Error: Browsing on the local area network for Dina's (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
I checked this on both Android and iOS but couldn't reproduce the issue with below minimal sample code. Please also try this sample code on your end and confirm. 

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    const MaterialApp(
      title: 'Flutter Demo',
      home: Home(),
    ),
  );
}

class Home extends StatelessWidget {
  const Home({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final padding = MediaQuery.of(context).viewInsets.bottom;
    return Scaffold(
      body: Center(
        child: SingleChildScrollView(
            child: Column(
          children: [
            TextFormField(obscureText: false),
            TextFormField(obscureText: true),
            Container(
              padding: EdgeInsets.only(bottom: padding),
              child: Text('padding: $padding', style: TextStyle(fontSize: 16)),
            ),
          ],
        )),
      ),
    );
  }
}

```
</details>

<details>
<summary>Demo (Pixel 7, Android 14 - issue is not reproduced)</summary>

https://github.com/flutter/flutter/assets/104349824/2652e49f-d593-428b-8fdf-ae23e571bd95

</details>
