### ISSUE TITLE
Allow AnimationController to make Animations

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#14482]
## The problem

One of the things we learned from last quarter's animation UX study is that participants had trouble wrapping their heads around the relationships between `AnimationController`, `Animation`, and `Tween`. They also felt the number of objects they needed to keep track of for a simple animation is overwhelming. The difficulty is partially related to the way the Controller-Animation relationship is declared in the current API. For example:

```dart
AnimationController controller = new AnimationController(); 
Animation<Color> colorAnimation = 
    new Tween<Color> (begin: Colors.red, end: Colors.blue).animate(controller);
```
In the above snippet, the chain of command is not obvious, since it was the Tween object that declared its controller rather than the other way around, leaving the impression that there are several independent objects the user needs to keep track of. Moreover, it's hard for the user to figure out what to do after creating the controller without making more trips to the documentation <sup>[1]</sup>.

## The proposal 

The main idea is to provide a way to discover APIs for building common animations by starting from an `AnimationController` object. The premise is that for the majority of users and especially new users, they don't need the full power and flexibility of the animation library to start building expressive animations. Thus, providing those users with a controller-centric view into the animation API makes building animations more tractable.

Specifically, I'd suggest adding a `makeAnimation(Animatable<T>)` method to AnimationController:

```dart
AnimationController controller = new AnimationController(); 
Animation<Color> colorAnimation = controller.makeAnimation(
    new Tween<Color> (begin: Colors.red, end: Colors.blue)
);
```
In addition, we should make this the recommended way to attach Animation objects to a controller in our sample code and tutorials, unless it is not sufficient for the specific use case. 

The method `makeAnimation` will be discoverable through autocomplete on the controller object. However, the discoverability of Tween is still questionable, since the autocomplete box is likely to suggest `Animatable` which is an abstract class. We can either make the DartDoc of `Animatable` more explicitly point to `Tween` and `CurveTween`, the two classes implementing `Animatable`, or make autocomplete smarter. 

## References
[1] For prior research on method placement's impact on API usability, see [Myers and Stylos (2006)](https://www.cs.cmu.edu/~NatProg/papers/Stylos2008APIObjectDesigns.pdf).

**Comment by Hixie** [comment]
How strongly are you attached to `makeAnimation`? The reason I ask is that `AnimationController` is itself an `Animation`, so it's not clear what it means exactly.

Maybe "drive"? `animation = controller.drive(tween);`

Unfortunately, `animate` and `chain` have conflicting meanings on `Animatable` already.

**Comment by InMatrix** [comment]
I had two goals in naming this method: 
1. Suggesting what the method returns
2. Avoiding confusion with `controller.forward()`

There was a participant who assumed `animate` would start the animation upon called and overlooked `forward`. The word `drive` can have the same issue, though it's probably better than `animate`. On the other hand, `drive` better explains the relationship between the controller and the resulting animation than `makeAnimation`. Okay, all things considered, I'm leaning towards `drive` now. 

PS: regarding your concern about an `Animation` making an `Animation`, I think "a controller of animations" is the primary identity of `AnimationController` we'd like users to remember. `Animation` is its secondary identity which we don't even talk very much in its docs: https://docs.flutter.io/flutter/animation/AnimationController-class.html

IMHO, the case where a controller is used as an animation, i.e., a property value is directly bound to `controller.value` instead of, say, `widthAnimation.value` should be considered a shortcut rather than the normal way we'd want to communicate the conceptual model of animations in Flutter.

**Comment by InMatrix** [comment]
Why is this bug getting the `prod:API break` label? The existing code should work as usual, unless we're considering deprecating `Animatable.animate()`.

**Comment by Hixie** [comment]
I'm looking at it in the scope of breaking API changes. It's true it might not be a breaking API change, in which case we should probably move it to M4.

**Comment by InMatrix** [comment]
Got it. The timing is up to you. One consideration is when @Sfshaza will have time to revisit the animation docs once the API change lands.

**Comment by diego-lipinski-de-castro** [comment]
Animations seems essential to provide a flowlessly user experience and interaction, and it's actually really hard and overhelming to build and understand, what are the times on this?

**Comment by Sfshaza** [comment]
@diego-lipinski-de-castro, we are sorry! This topic kept getting sidelines by other docs higher in the Q. But we have a writer working on them now and I hope they'll be released soon.

**Comment by Hixie** [comment]
Added Animation.drive()
