### ISSUE TITLE
about connected devices in flutter

### ISSUE THREAD

**Issue by Nada169701** [flutter/flutter#144807]
I have tried many times to find the location of the error, but still with the same information as below:
```
[☠] Connected device (the doctor check crashed)
     X Due to an error, the doctor's check was not complete. If the error message below is not helpful, please let us know
       about this issue at https://github.com/flutter/flutter/issues.
     X Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
       C:\Users\acer\AppData\Local\Android\Sdk\platform-tools\adb.exe
```
I've fixed it many times but I still check in the command prompt and the results are the same
please provide a solution, thank you.

**Comment by turinaf** [comment]
It was working fine the day before yesterday for me. I just tried to start my app today and couldn't connect to devices.  
I'm getting same error as @Nada169701 when I run `flutter doctor`, Android studio also says no connected devices.
What happened?

**Comment by turinaf** [comment]
That's strange because it was working the day before yesterday. Now I was able to configure it using `flutter config --android-studio-dir="C:\Program Files\Android\Android Studio1"`
And then restarting the my laptop.

**Comment by darshankawar** [comment]
@Nada169701 
Check [this](https://github.com/flutter/flutter/issues/142996#issuecomment-1932542584) and see if it helps to resolve your case or not.

**Comment by UbayGD** [comment]
Hi! I also have this problem. In my case, the combination is:

- Fedora 39
- Flutter 3.19.4
- Android SDK Build-Tools 35-rc2
- Android SDK Platform-Tools 35.0.1
- Pixel 6a with Android 14
