### ISSUE TITLE
[cross_file] Add `lengthSync` in XFile

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#144879]
### Use case

Like [`File.lengthSync`](https://api.flutter.dev/flutter/dart-io/File/lengthSync.html), a `lengthSync` function is needed to get file lenght with synchronously.

### Proposal

In some cases, we need to get file lenght with synchronously. This function is available in `File`, so I suggest adding it to `cross_file`.

**Comment by stuartmorgan** [comment]
We cannot reliably implement `XFile` data access synchronously in all implementations, so we will not be adding `*Sync` variants of APIs.

> This function is available in `File`, so I suggest adding it to `cross_file`.

`File` is a specific implementation where synchronous access can be guaranteed. Not everything that can be done in `File` can be done in `XFile`.
