### ISSUE TITLE
flutter-firebase codelab - Missing repository for imagepicker package

### ISSUE THREAD

**Issue by sadohert** [flutter/flutter#14487]
## Steps to Reproduce

* Following through the codelab to step 5 - Setting up Firebase Integration
* Project wouldn't build complaining:

`* What went wrong:
Could not determine the dependencies of task ':app:prepareDebugDependencies'.
> Could not resolve all task dependencies for configuration ':app:_debugApk'.
   > Could not find com.github.esafirm.android-image-picker:imagepicker:1.5.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.pom
         https://jcenter.bintray.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.aar
         https://maven.google.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.pom
         https://maven.google.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.aar
     Required by:
         project :app > project :image_picker`
* I went to the [imagepicker library](https://github.com/esafirm/android-image-picker) github and noticed in the "Download" section this snippet:

`allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}`
* After adding the jitpack.io repo my project would build

I think the codelab instructions need to be updated to include this step.  Or maybe I did something wrong in a previous step?

**Comment by fmatosqg** [comment]
I agree, that step needs to go in the codelab tutorial (or the tutorial sample code changed to include that line).

I applied your solution and it worked for me.

**Comment by Hixie** [comment]
cc @collinjackson @Sfshaza

**Comment by Sfshaza** [comment]
This codelab has been obsoleted. Closing.

**Comment by kroikie** [comment]
@sadohert

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/905. Any further collaboration will be done there.
