### ISSUE TITLE
[cross_file] Add `writeAsBytes` in XFile

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#144878]
### Use case

Like [`File.writeAsBytes`](https://api.flutter.dev/flutter/dart-io/File/writeAsBytes.html), a `writeAsBytes` function is needed to writeAsBytes a file and return an [`XFile`](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html).

### Proposal

n/a

**Comment by stuartmorgan** [comment]
> ### Use case
> Like [`File.writeAsBytes`](https://api.flutter.dev/flutter/dart-io/File/writeAsBytes.html), a `writeAsBytes` function is needed to writeAsBytes a file and return an [`XFile`](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html).

This is a proposal; what is the use case?

**Comment by mbfakourii** [comment]
> > ### Use case
> > Like [`File.writeAsBytes`](https://api.flutter.dev/flutter/dart-io/File/writeAsBytes.html), a `writeAsBytes` function is needed to writeAsBytes a file and return an [`XFile`](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html).
> 
> This is a proposal; what is the use case?

In some cases, we need to writeAsBytes a file. This function is available in File, so I suggest adding it to cross_file.

**Comment by stuartmorgan** [comment]
> In some cases, we need to `writeAsBytes` in file.

"Some cases" is not a use case. Please provide a specific use case.

The reason the proposal template starts with the "Use case" section is that concrete use cases are how we evaluate proposals. Per [our project documentation](https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues), proposals that only provide proposed solutions without describing the use case(s) they are intended to solve will be closed.
