### ISSUE TITLE
[Web] White line at screen bottom when resizing the window

### ISSUE THREAD

**Issue by RMotive** [flutter/flutter#144869]
### Steps to reproduce

On an empty application.

![image](https://github.com/flutter/flutter/assets/101542646/9d33d2a3-b4d1-4f8e-8536-ce43daca05b2)

### Expected results

Don't get that white line.

### Actual results

Getting a bothering white line x.x

### Code sample

```dart
void main() {
  usePathUrlStrategy();  
  runApp(
    const TWSAdministration(),
  );
}

class TWSAdministration extends StatelessWidget {
  const TWSAdministration({super.key});

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: Colors.red,
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration Expand to see the white line, in preview mode might not be visible</summary>

https://github.com/flutter/flutter/assets/101542646/96e92a45-9ef1-46d2-ba11-a3ca179bb573

</details>

### Logs

<details open><summary>Doctor</summary>

```console
```

</details>

### Flutter Doctor output

<details open><summary>Logs</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.4 23E214 darwin-arm64, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.87.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Reproduced this issue on the latest Flutter stable and master channel. 

- The issue occurs on Web but not on macOS app. It is not only on Canvaskit, but also on HTML renderer.
- This also appears on the previous stable release 3.16.9. 
- I also see the issue without using `usePathUrlStrategy`.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const TWSAdministration(),
  );
}

class TWSAdministration extends StatelessWidget {
  const TWSAdministration({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.red,
    );
  }
}
```
</details>

**Comment by Painwraith** [comment]
I doubt its of any help but I wanted to mention you can trigger this bug by expanding the webview vertically or horizontally.

**Comment by sabatage3** [comment]
I'm having the same issue, it makes my web app look very cheap :(, any solutions yet?

**Comment by jpears1** [comment]
I'm seeing the same thing.  It doesn't always happen, it seems to depend on the size of the browser window.  When it doesn't happen, then if I resize the window to be a little taller or shorter then the line usually appears.  Resize the window again to a different size, and sometimes the line disappears again.

I can make it **always** happen when I put the app/browser into fullscreen mode.

i.e., I have the app do a `html.document.documentElement?.requestFullscreen()`.

Then something as simple as the following causes the white line to always run along the entire bottom of the screen.

```
Scaffold(
  body: Container(
    color: Colors.black,
    child: Center( child: Text('hello world'),
)));
```

No issues when the app is built for mobile. (both android and iOS0

Flutter 3.19.5.

**Comment by jpears1** [comment]
I found an old build of our web app that was built back in November using flutter 3.13.9.  The problem does not exist in this build.

If I rebuild that same version of the web app with the version of flutter I have now (3.19.5), then the problem occurs.

**Comment by Hugtas** [comment]
Same issue here...
