### ISSUE TITLE
List pre-reqs up top in Getting Started

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#1448]
_From @sethladd on November 4, 2015 0:2_

e.g. do I need a phone? What kind, and version(s)? What OS and what version(s)? Any cables? Do I need other software like XCode?

maybe even show a picture to illustrate the setup.

_Copied from original issue: flutter/website#42_

**Comment by FlutterIssues** [comment]
_From @abarth on November 4, 2015 0:6_

Yeah, good point.  At this point you need an Android phone, a Mac or Linux host.  A USB cable to connect them.

**Comment by FlutterIssues** [comment]
_From @sethladd on November 4, 2015 0:15_

Happy to make the addition. Will send PR

**Comment by qchong** [comment]
Documented the system requirements and pre-reqs for iOS/Android setup in the [Flutter Setup](https://flutter.io/setup/) page. This replaces the old installation instructions on the Getting Started page. I've also added a link in the GS, pointing to the Setup page for installation instructions.

**Comment by qchong** [comment]
Marking as closed.
