### ISSUE TITLE
test_if is also skipping tests in presubmit

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#144840]
The presubmit run here https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/760676/overview

Did not include the `impeller-golden` tests that should haven only been filtered out on release branches: https://github.com/flutter/engine/blob/main/ci/builders/mac_host_engine.json#L205

**Comment by keyonghan** [comment]
The culprit is https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine_v2/builder.py#114, which checks the prod build case only.
https://flutter-review.googlesource.com/c/recipes/+/55922 to fix.

**Comment by keyonghan** [comment]
Fix landed. Please reopen if the issue persists.
