### ISSUE TITLE
run in iOS：report [AVCapturePhotoOutput capturePhotoWithSettings:delegate:] No active and enabled video connection

### ISSUE THREAD

**Issue by programer001** [flutter/flutter#144975]
### Steps to reproduce

I couldn't reproduce the problem manually and only caught it from the online log

### Expected results

Look at the log. There was an anomaly when the photo was taken

### Actual results

crash 

### Code sample

```
Future<void> _takePhoto() async {
    if (null == controller ||
        !controller!.value.isInitialized ||
        _status != TakePhotoStatus.taking) {
      return;
    }
    if (controller?.value.isTakingPicture ?? false) {
      // A capture is already pending, do nothing.
      return;
    }
    try {
      final file = await controller?.takePicture();
      setState(() {
        _curFile = file;
        _status = TakePhotoStatus.confirm;
      });
    } on CameraException catch (e) {
      debugPrint(e.toString());
    }
  }
```

### Logs

```
camera_avfoundation
-[FLTCam captureToFile:] + 468
4
camera_avfoundation
-[CameraPlugin handleMethodCallAsync:result:] + 2108
5
camera_avfoundation
__40-[CameraPlugin handleMethodCall:result:]_block_invoke + 68
```

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 14.0 23A344 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.87.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for null. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

**Comment by programer001** [comment]
i am looking forward to your reply.

**Comment by programer001** [comment]
As soon as I open the page before the camera shows
It can be reproduced by calling the photo directly

**Comment by programer001** [comment]
another problem,enter the camera page repeatedly,  throw exception:
A CameraController was used after being disposed.
Once you have called dispose() on a CameraController, it can no longer be used.

stack:
ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:382:27)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:530:5)
#4      CameraController._initializeWithDescription (package:ddmc_native_mix/src

**Comment by darshankawar** [comment]
@programer001 
You are on old version of stable. What's the plugin version you are using ?
I suggest to upgrade both (stable and plugin version) and run your scenario again to check if the reported behavior still occurs or not.

Also, the stacktrace you shared is not complete. Please provide complete stacktrace in properly formatted text so that we can properly analyze the issue.

**Comment by programer001** [comment]
The version of plugin I use is [0.10.5+9] . I can try to upgrade to the latest stable version and provide complete stacktrace to you.

**Comment by programer001** [comment]
now my flutter is stable  3.19.3, plugin version is 0.10.5+9. There is still this problem
complete stacktrace:

A CameraController was used after being disposed.
Once you have called dispose() on a CameraController, it can no longer be used.

#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:382:27)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:530:5)
#4      CameraController._initializeWithDescription (package:ddmc_native_mix/src/camera_src/camera_controller.dart:334:7)
<asynchronous suspension>
#5      _FDCCustomCameraState._initCamera (package:flutter_module/components/fdc_custom_camera.dart:125:7)
<asynchronous suspension>

Steps to reproduce:
Quick entry and exit page

show my code:
  @override
  void initState() {
    super.initState();
    _requestCameraPermission();
  }

  Future<void> _initCamera() async {
    try {
      _cameras = await availableCameras();
    } on CameraException catch (e) {
      debugPrint(e.description);
    }
    if (_cameras.isEmpty) {
      SchedulerBinding.instance.addPostFrameCallback((_) async {
        showInSnackBar('no camera found.');
      });
      return;
    }
    var description = _cameras.first;
    for (final camera in _cameras) {
      if (camera.lensDirection == CameraLensDirection.front) {
        description = camera;
        break;
      }
    }
    controller = CameraController(
      description,
      ResolutionPreset.medium,
      enableAudio: false,
    );
    try {
      await controller?.initialize();
      controller?.addListener(() {
        if (controller?.value.hasError ?? false) {
          showInSnackBar('Camera error ${controller?.value.errorDescription}');
        }
      });
      if (mounted && (controller?.value.isInitialized ?? false)) {
        setState(() {
          _status = TakePhotoStatus.taking;
        });
      }
    } on CameraException catch (e) {
      showInSnackBar(e.description ?? '');
    }
  }

**Comment by darshankawar** [comment]
@programer001 
The stacktrace looks similar to https://github.com/flutter/flutter/issues/126823 which was fixed recently that you can check and see if it helps in your case or not.

**Comment by programer001** [comment]
> @programer001 The stacktrace looks similar to #126823 which was fixed recently that you can check and see if it helps in your case or not.

This didn't help me in my case. It wasn't setDescription that happened, it happened when the widget was destroyed and then reentered. Problems with controller?.initialize()

**Comment by darshankawar** [comment]
@programer001 
What iOS device and OS version device does this occur on ? Are you able to replicate it locally ?

**Comment by programer001** [comment]
> @programer001 What iOS device and OS version device does this occur on ? Are you able to replicate it locally ?

iPhone 12	17.3.1 (21D61)
iPhone 15 Pro	17.2.1 (21C66)
iPhone 13	17.2.1 (21C66)

I can  replicate it locally.Repeated entry and exit of the page can be reproduced,
@override
void initState() {
  super.initState();
  _requestCameraPermission();
}

Future<void> _initCamera() async {
  try {
    _cameras = await availableCameras();
  } on CameraException catch (e) {
    debugPrint(e.description);
  }
  if (_cameras.isEmpty) {
    SchedulerBinding.instance.addPostFrameCallback((_) async {
      showInSnackBar('no camera found.');
    });
    return;
  }
  var description = _cameras.first;
  for (final camera in _cameras) {
    if (camera.lensDirection == CameraLensDirection.front) {
      description = camera;
      break;
    }
  }
  controller = CameraController(
    description,
    ResolutionPreset.medium,
    enableAudio: false,
  );
  try {
    await controller?.initialize();
    controller?.addListener(() {
      if (controller?.value.hasError ?? false) {
        showInSnackBar('Camera error ${controller?.value.errorDescription}');
      }
    });
    if (mounted && (controller?.value.isInitialized ?? false)) {
      setState(() {
        _status = TakePhotoStatus.taking;
      });
    }
  } on CameraException catch (e) {
    showInSnackBar(e.description ?? '');
  }
}

**Comment by darshankawar** [comment]
Thanks for the update. I tried to use above code snippet in the camera plugin example but there are compile errors, so please provide us complete runnable code sample (ex: main.dart) that we can simply copy paste and run at our end to verify this properly.

**Comment by programer001** [comment]
> Thanks for the update. I tried to use above code snippet in the camera plugin example but there are compile errors, so please provide us complete runnable code sample (ex: main.dart) that we can simply copy paste and run at our end to verify this properly.

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:permission_handler/permission_handler.dart';

///
class TestCamera extends StatefulWidget {
  ///init
  const TestCamera({super.key});

  @override
  State<TestCamera> createState() => _TestCameraState();
}

class _TestCameraState extends State<TestCamera> {

  CameraController? controller;
  List<CameraDescription> _cameras = <CameraDescription>[];
  bool _isShowingSnackBar = false;

  @override
  void initState() {
    super.initState();
    _requestCameraPermission();
  }

  void _requestCameraPermission() {
    Permission.camera.request().then((status) {
      if (status == PermissionStatus.granted) {
        // 已授权访问相机
        _initCamera();
        return;
      } else {
        // 用户拒绝授权，弹出提示
        showDialog<dynamic>(
          context: context,
          builder: (BuildContext context) => AlertDialog(
            title: const Text('相机权限未授权'),
            content: const Text('您需要允许应用程序访问相机才能使用此功能'),
            actions: <Widget>[
              ElevatedButton(
                onPressed: () {
                  Navigator.pop(context);
                  Navigator.pop(context);
                },
                child: const Text('确定'),
              ),
            ],
          ),
        );
      }
    });
  }

  Future<void> _initCamera() async {
    try {
      _cameras = await availableCameras();
    } on CameraException catch (e) {
      debugPrint(e.description);
    }
    if (_cameras.isEmpty) {
      SchedulerBinding.instance.addPostFrameCallback((_) async {
        showInSnackBar('no camera found.');
      });
      return;
    }
    var description = _cameras.first;
    for (final camera in _cameras) {
      if (camera.lensDirection == CameraLensDirection.front) {
        description = camera;
        break;
      }
    }
    controller = CameraController(
      description,
      ResolutionPreset.medium,
      enableAudio: false,
    );
    try {
      await controller?.initialize();
      controller?.addListener(() {
        if (controller?.value.hasError ?? false) {
          showInSnackBar('Camera error ${controller?.value.errorDescription}');
        }
      });
      if (mounted && (controller?.value.isInitialized ?? false)) {
        setState(() {
        });
      }
    } on CameraException catch (e) {
      showInSnackBar(e.description ?? '');
    }
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CameraPreview(controller!);
  }

  ///提示
  void showInSnackBar(String message) {
    if (_isShowingSnackBar) {
      return;
    }
    _isShowingSnackBar = true;
    ScaffoldMessenger.of(context)
        .showSnackBar(
      SnackBar(
        duration: const Duration(milliseconds: 500),
        content: SizedBox(height: 60, child: Center(child: Text(message))),
      ),
    )
        .closed
        .then((value) {
      _isShowingSnackBar = false;
    });
  }
}

**Comment by darshankawar** [comment]
@programer001 
As you are using permission_handler separately, it may be due to it. Check the camera readMe section for handling permissions and see if using it, you still get the same behavior or not.

https://pub.dev/packages/camera#handling-camera-access-permissions

**Comment by programer001** [comment]
> @programer001 As you are using permission_handler separately, it may be due to it. Check the camera readMe section for handling permissions and see if using it, you still get the same behavior or not without using `permission_handler`.
> 
> https://pub.dev/packages/camera#handling-camera-access-permissions

I don't think that's the problem. Moreover, without permission_handler, how do I prompt the user to open camera permissions?

**Comment by programer001** [comment]
> @programer001 As you are using permission_handler separately, it may be due to it. Check the camera readMe section for handling permissions and see if using it, you still get the same behavior or not without using `permission_handler`.
> 
> https://pub.dev/packages/camera#handling-camera-access-permissions

I have modified my code as follows. 
 Future<void> _initCamera() async {
    try {
      _cameras = await availableCameras();
    } on CameraException catch (e) {
      debugPrint(e.description);
    }
    if (_cameras.isEmpty) {
      SchedulerBinding.instance.addPostFrameCallback((_) async {
        showInSnackBar('未发现可用的相机.');
      });
      return;
    }
    var description = _cameras.first;
    for (final camera in _cameras) {
      if (camera.lensDirection == CameraLensDirection.front) {
        description = camera;
        break;
      }
    }
    controller = CameraController(
      description,
      ResolutionPreset.medium,
      enableAudio: false,
    );
    try {
      await controller?.initialize();
      controller?.addListener(() {
        if (controller?.value.hasError ?? false) {
          showInSnackBar('Camera error ${controller?.value.errorDescription}');
        }
      });
      if (mounted && (controller?.value.isInitialized ?? false)) {
        setState(() {
          _status = TakePhotoStatus.taking;
        });
      }
    } on CameraException catch (e) {
      switch (e.code) {
        case 'CameraAccessDenied':
        case 'CameraAccessDeniedWithoutPrompt':
          _showPermissionAlert();
          break;
        default:
          showInSnackBar('${e.code}\n${e.description}');
      }
    }
  }

The following error occurs when enter and exit the photo page repeatedly
FATAL EXCEPTION: pool-112-thread-1
                                                                                                    Process: com.ddmc.fdc.delivery, PID: 25399
                                                                                                    java.lang.IllegalArgumentException: No handler given, and current thread has no looper!
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.checkHandler(CameraDeviceImpl.java:2509)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.checkHandler(CameraDeviceImpl.java:2524)
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:290)
                                                                                                    	at io.flutter.plugins.camera.Camera.refreshPreviewCaptureSession(Camera.java:520)
                                                                                                    	at io.flutter.plugins.camera.Camera$2.onConfigured(Camera.java:451)
                                                                                                    	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
                                                                                                    	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:929)

**Comment by darshankawar** [comment]
@programer001 
Above log you shared seems to be for Android, so I used the code sample and ran on S10 and also on iPhone device and on both I didn't get the said exception, except below:

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building TestCamera(dirty, state: _TestCameraState#f7b64):
Null check operator used on a null value

The relevant error-causing widget was: 
  TestCamera TestCamera:file:///Users/dhs/Documents/NCFlutter/app_foo_stable/lib/main.dart:8:11
When the exception was thrown, this was the stack: 
#0      _TestCameraState.build (package:app_foo_stable/main.dart:111:36)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456:5)
...     Normal element mounting (220 frames)
#227    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#228    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#229    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905:32)
...     Normal element mounting (483 frames)
#712    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#713    Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
#714    _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:291:16)
#715    _RawViewElement.mount (package:flutter/src/widgets/view.dart:314:5)
...     Normal element mounting (7 frames)
#722    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#723    Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
#724    RootElement._rebuild (package:flutter/src/widgets/binding.dart:1354:16)
#725    RootElement.mount (package:flutter/src/widgets/binding.dart:1323:5)
#726    RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1276:18)
#727    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2844:19)
#728    RootWidget.attach (package:flutter/src/widgets/binding.dart:1275:13)
#729    WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1088:27)
#730    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1070:5)
#731    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1056:7)
#735    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
```

Also, in this issue thread, you reported various different issues, so please confirm and provide us which is the latest exception you are seeing using the code sample and running on which platform. Also, please let us know about the original issue you reported in issue description whether it still occurs or not, because I think this issue thread has become a bit messy.
