### ISSUE TITLE
[cross_file] Add example app

### ISSUE THREAD

**Issue by SoroushBeigi** [flutter/flutter#144914]
### Use case

When trying to use cross_file package, having no example led to confusion

### Proposal

Flutter does not provide any kind of example doc or app for the cross_file package. We should have a simple example app that demonstrates its functionality.

**Comment by SoroushBeigi** [comment]
after using the package for a while, I'm able to create an example app if it is needed. let me know if there are any guidelines I have to follow

**Comment by huycozy** [comment]
This is a known issue at https://github.com/flutter/flutter/issues/93073. Closing as a duplicate. You are welcome to contribute, please feel free to create an example for the package.
