### ISSUE TITLE
RTL and Script Unicode Font (ttf), and ligatures not supported

### ISSUE THREAD

**Issue by rabadiaanurag** [flutter/flutter#144917]
### Steps to reproduce

RTL and Script Unicode Font (ttf), and ligatures not supported.
Unicode Fonts gets Broken after generation of the PDF.

### Expected results

Please visit this issue.
https://github.com/DavBfr/dart_pdf/issues/198

### Actual results

Please visit this issue.
https://github.com/DavBfr/dart_pdf/issues/198

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
The issue linked above does not mention anything related to flutter. If you are facing an issue with flutter, kindly provide the relevant code without any third party packages so we can investigate this. If your issue is related to a third party package, kindly file the issue on their repo. 

Closing from here as there's no indication of a flutter issue here. 

Thank you

**Comment by rabadiaanurag** [comment]
its basic functionality which must be provided by the flutter language. its not required that all basic features will be provided by the package developers. its resposibility of the flutter language developer that the language must have some basic required features to be developed time to time.

**Comment by AkamBarznji** [comment]
Use Vazirmatn font will help you

https://fonts.google.com/specimen/Vazirmatn

**Comment by rabadiaanurag** [comment]
> Use Vazirmatn font will help you
> 
> https://fonts.google.com/specimen/Vazirmatn

its not working.
