### ISSUE TITLE
[plugin_platform_interface] In flutter plugin package, android lint is recursively being run on external dependencies 

### ISSUE THREAD

**Issue by prolificcoder** [flutter/flutter#144997]
### What package does this bug report belong to?

plugin_platform_interface

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
https://github.com/prolificcoder/demo_lint_bug/blob/main/example/pubspec.lock
```

</details>

### Steps to reproduce

Demo sample repo: https://github.com/prolificcoder/demo_lint_bug
1. flutter create --template=plugin --org com.mobile.prolificcoder --platforms=android,ios demo_lint_bug
2. cd demo_lint_bug
3. flutter pub get
4. cd example/android
5. gradle lint
6. succeeds
7. Add mparticle_flutter_sdk https://github.com/prolificcoder/demo_lint_bug/blob/main/pubspec.yaml#L13 in demo_lint_bug/pubspec.yaml which has lint issues in android folder
8. flutter pub get
9. cd example/android
10. gradle lint
11. fails
12. This continues to fail even if I try to exclude dependencies (https://github.com/prolificcoder/demo_lint_bug/blob/main/example/android/app/build.gradle#L63)) in lintOptions
	1. demo_lint_bug/example/android/app/build.gradle
	2. Any of the options i give in any of the build.gradle files aren't considered

### Expected results

gradle lint succeeds 
or there is a way to exclude dependencies lint from running

### Actual results

gradle lint fails because of the third party lint issues
[lint-results-debug.txt](https://github.com/flutter/flutter/files/14574953/lint-results-debug.txt)

### Logs

<details open><summary>Logs</summary>

```console
[lint-results-debug.txt](https://github.com/flutter/flutter/files/14574953/lint-results-debug.txt)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
`gradle lint` is a request to lint every subproject in your project. If you want to target a specific subproject [you need to specify that](https://stackoverflow.com/questions/16976214/gradle-build-only-one-module/16987319#16987319)

Closing as this is how Gradle works, and is unrelated to Flutter.



> ### What package does this bug report belong to?
> plugin_platform_interface

In the future, please do not use the template for reporting issues with *a specific package* to report issues that are unrelated to a specific package.

**Comment by prolificcoder** [comment]
@stuartmorgan thanks a lot for the quick response, chatgpt doesn't know everything after all :)
