### ISSUE TITLE
I tried to use charts flutter but he reported the following error.

### ISSUE THREAD

**Issue by meishiqi** [flutter/flutter#144906]
### Steps to reproduce

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: any
  charts_flutter_new: ^0.12.0

### Actual results

Because every version of charts_flutter_new depends on charts_common ^0.12.0 which depends on intl >=0.15.2 <0.18.0, every version of charts_flutter_new requires intl >=0.15.2 <0.18.0.
And because every version of flutter_localizations from sdk depends on intl 0.18.1, charts_flutter_new is incompatible with flutter_localizations from sdk.
So, because toolserver depends on both flutter_localizations from sdk and charts_flutter_new ^0.12.0, version solving failed.

### Flutter Doctor output

[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [版本 10.0.22631.3007], locale zh-CN)
    • Flutter version 3.19.3 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (3 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
    • Visual Studio at d:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34622.214
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.66

[√] Network resources
    • All expected network resources are available.

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the authors of the package. In this case, the package needs an update to be compatible with the version of dependencies it shared with the Flutter SDK.
