### ISSUE TITLE
`golden_tests_harvester` should panic if `!SkiaGoldClient.isAvailable`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144948]
See https://github.com/flutter/engine/pull/51325.

Before https://github.com/flutter/engine/pull/50844, when `golden_tests_harvester` was invoked in a release builder (i.e. where `isLuci` evaluates to true, but `SkiaGoldClient.isAvailable` evaluates to false), it would just ... party on, seemingly producing no errors. I'm not sure exactly how.

Personally, I don't think a tool should "pretend" to run as a silent behavior, that is, if it's invoked, it should run.

Ideas:
1. Embrace https://github.com/flutter/engine/pull/51325, and panic if executed without `GOLDCTL`. Probably tear-out the [`FakeSkiaGoldClient` stuff][1].
2. Add a flag (`--dry-run` or similar) that makes this explicit versus implicit. Even `--dry-run-if-gold-ctl-omitted` is better.
3. Embrace chaos and close this PR as WAI.

[1]: https://github.com/flutter/engine/blob/9abbc5e816004e38360cd9609b36cc6db2871623/tools/golden_tests_harvester/bin/golden_tests_harvester.dart#L87-L91

**Comment by gaaclarke** [comment]
I like the idea of making the noop explicit with `--dry-run`.  That mode was essential for local development.
