### ISSUE TITLE
After updating the Flutter. Flutter run Error reporting  Error (Xcode): Framework 'Flutter' not found

### ISSUE THREAD

**Issue by maxiu1006** [flutter/flutter#144925]
### Steps to reproduce

After updating the Flutter 3.19.2 • channel stable • https://github.com/flutter/flutter.git    flutter run

### Actual results

Error (Xcode): Framework 'Flutter' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           31.3s
Failed to build iOS app
Error (Xcode): Framework 'Flutter' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

**Comment by darshankawar** [comment]
@maxiu1006 
Can you run `flutter run -v` and provide the entire log here ? The log will be huge, so you can put that in a text file and share it here.
