### ISSUE TITLE
I want to retrieve HTML string data from a .txt file stored in my document directory path. When loading this data onto a WebView using InAppWebView, I need to specify the path to a .css file from my assets folder within the HTML string. Here's a sample code snippet for reference.

### ISSUE THREAD

**Issue by rudraraj3004** [flutter/flutter#144976]
// ignore_for_file: library_private_types_in_public_api

import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:velocity_x/velocity_x.dart';

class WebViewPage extends StatefulWidget {
  const WebViewPage({super.key});

  @override
  _WebViewPageState createState() => _WebViewPageState();
}

class _WebViewPageState extends State<WebViewPage> {
  InAppWebViewController? webView;
  late String htmlContent;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("InAppWebView"),
      ),
      body: InAppWebView(
        initialSettings: InAppWebViewSettings(
            javaScriptEnabled: true,
            allowsLinkPreview: true,
            initialScale: 100),
        initialData: InAppWebViewInitialData(
          data: htmlContent,
          mimeType: 'text/html',
          encoding: 'utf8',
        ),
        onWebViewCreated: (controller) {
          webView = controller;
        },
      ),
    );
  }

  Future<String> get _localPath async {
    final directory = await getApplicationDocumentsDirectory();
    return directory.path;
  }

  Future<File> get _localFile async {
    final path = await _localPath;
    return File('$path/login_form.txt');
  }

  Future<File> writeToFile(String data) async {
    final file = await _localFile;
    return file.writeAsString(data);
  }

  String getFileContent() {
    // Read the content of the .txt file
    // For simplicity, you can hardcode the HTML content here, or fetch it from an API or database
    return '''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Simple Login Form Example</title>
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Rubik:400,700'>
  <link rel="stylesheet" href="assets/www/styles/style.css">
</head>
<body>
<div class="login-form">
  <form id="loginForm">
    <h1>Login</h1>
    <div class="content">
      <div class="input-field">
        <input type="email" id="emailInput" placeholder="Email" autocomplete="nope">
      </div>
      <div class="input-field">
        <input type="password" id="passwordInput" placeholder="Password" autocomplete="new-password">
      </div>
      <a href="#" class="link">Forgot Your Password?</a>
    </div>
    <div class="action">
      <button type="button" id="registerButton">Register</button>
      <button type="button" id="signInButton">Sign in</button>
    </div>
  </form>
</div>
<script src="./script.js" class="registerButton"></script>
<script src="./script.js" class="signInButton"></script>
</body>
</html>
''';
  }

  @override
  void initState() {
    super.initState();
    // Write HTML data to .txt file
    writeToFile(getFileContent());
    Timer(const Duration(seconds: 1), () {
      readHtmlContentFromFile(context);
    });
  }

  Future<void> readHtmlContentFromFile(context) async {
    try {
      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/login_form.txt');
      htmlContent = await file.readAsString();
      final cssContentString = await DefaultAssetBundle.of(context)
          .loadString('assets/www/styles/style.css');
      final modifiedHtmlContent = htmlContent.replaceAll('./styles/style.css',
          'data:text/css;base64,${base64Encode(Uint8List.fromList(utf8.encode(cssContentString)))}');
      Vx.log(modifiedHtmlContent);
      setState(() {
        htmlContent = modifiedHtmlContent;
      }); // Trigger a rebuild to load the WebView
    } catch (e) {
      Vx.log("Error reading file: $e");
    }
  }
}

Thanks in advance

**Comment by jonahwilliams** [comment]
The flutter issue tracker is for filling bugs against the framework, engine, 1p packages, et cetera. This is not a help forum

**Comment by rudraraj3004** [comment]
> The flutter issue tracker is for filling bugs against the framework, engine, 1p packages, et cetera. This is not a help forum

Any help from your end. it would be appreciated
