### ISSUE TITLE
Document `debugShowCheckedModeBanner` more prominently

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#14495]
The slow mode banner creates issues with design reviews and in other situations because it is not sticky. It would be great if there was a global flutter configuration option to disable it for all projects if you prefer to never see it.

**Comment by Hixie** [comment]
The usual way is to do design reviews with release builds, or, if the design review is being done in with live editing, passing `debugShowCheckedModeBanner: false` to your `MaterialApp` widget (or making a custom widget that wraps `MaterialApp` and which you use instead); do either of those work for you?

**Comment by lukef** [comment]
The `debugShowCheckedModeBanner` works great. Didn't know about that one. Thanks!

**Comment by darshankawar** [comment]
Hi @lukef, since your issue seem to be resolved, I am going ahead and closing this as fixed.
If you disagree, write in comments and I'll reopen.
Thanks.
