### ISSUE TITLE
Problems encountered when using Flutter test -- coverage

### ISSUE THREAD

**Issue by qianzhi888** [flutter/flutter#144981]
Unit tests can be executed successfully, but errors will be reported when executing unit test coverage
This is the specific error message content
                                                                            
```console
  Shell subprocess crashed with segmentation fault.
  package:flutter_tools/src/test/flutter_tester_device.dart 240:73  FlutterTesterTestDevice.finished
  ===== asynchronous gap ===========================
  dart:async/future.dart 611:5                                      Future.any.onValue
```

This is my Flutter version
```console
Flutter 3.1.0 • channel unknown • unknown source
Framework • revision bcea432bce (1 year, 10 months ago) • 2022-05-26 09:05:34 -0700
Engine • revision 44e5b38ee8
Tools • Dart 2.18.0 (build 2.18.0-44.1.beta) • DevTools 2.12.2
```

This is the result of my execution of Flutter Doctor - v
```console
[✓] Flutter (Channel unknown, 3.1.0, on macOS 13.0.1 22A400 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.1.0 at /Users/programmer/flutter_mac/flutter
    • Upstream repository unknown
    • Framework revision bcea432bce (1 year, 10 months ago), 2022-05-26 09:05:34 -0700
    • Engine revision 44e5b38ee8
    • Dart version 2.18.0 (build 2.18.0-44.1.beta)
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/programmer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/programmer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2021.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio 2021.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • M2011K2C (mobile) • b88df1f4 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 122.0.6261.112

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
Please help me check if I have encountered such problems before. I request your help. Thank you

**Comment by huycozy** [comment]
Looking at the error message and the trace, this seems to be similar to https://github.com/flutter/flutter/issues/124145 but it's closed due to missing a reproduction case. And this could be similar to https://github.com/flutter/flutter/issues/106332 as well. Please check these issues to see if you are in the same context.

If your case is not the same, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thanks!

**Comment by qianzhi888** [comment]
Okay, thank you very much for your reply. Here is the test code from my end. You can replicate it on your end

void main() async {
  try {
    var logic = SelectBrandBusinessLogic();
    test('Obtain brand data', () async {
      var jsonStr = await getBrandInfo();
      List<dynamic> jsonList = json.decode(jsonStr);
      List<SelectBrandEntity> list = jsonList.map((json) => SelectBrandEntity.fromJson(json)).toList();
      expect(list.isNotEmpty, isTrue);
      logic.getProductBrandList(list);
      expect(logic.allBrandList.isNotEmpty, isTrue);
      // logic.allBrandList = list;
    });

    test('Search brand', () async{
      await logic.searchBrandOnChange('海');
      for (var value in logic.searchBrandList) {
        print('The search result is：${value.name}');
      }
      expect(logic.searchBrandList.isNotEmpty, isTrue);
    });


    test('Work order payment', () async {
      var entity = OrderPayEntity.fromJson(json.decode(await getPayInfo()));
      var logic = WaitUserPayBusinessLogic();
      await logic.getListPayMode(entity);
      expect(logic.showOtherPayMode, isTrue, reason: 'There are other payment methods available');
    });

  } catch (e) {
    print('Abnormal single test: ${e}');
  }
}

var popularBrandCount = 8;

Future<String> getBrandInfo() async {
  var path = 'test/select_brand/mock/BrandInfo.json';
  var jsonFile = File(path);
  var json = await jsonFile.readAsString();
  return json;
}


Future<String> getPayInfo() async {
  var path = 'test/select_brand/mock/PayData.json';
  var jsonFile = File(path);
  var json = await jsonFile.readAsString();
  return json;
}

This is reading local JSON data
[BrandInfo.json](https://github.com/flutter/flutter/files/14570840/BrandInfo.json)
[PayData.json](https://github.com/flutter/flutter/files/14570843/PayData.json)


class SelectBrandBusinessLogic { 
  List<SelectBrandEntity> brandList = [];
 
  List<SelectBrandEntity> popularBrand = [];
 
  List<SelectBrandEntity> allBrandList = [];
 
  List<SelectBrandEntity> searchBrandList = [];
 
  int popularBrandCount = 8;

  bool showClearButton = false;
  bool showCancelButton = false;
 
  Future<void> getProductBrandList(List<SelectBrandEntity> list) async {
    if (list.length > popularBrandCount) {
      popularBrand = list.sublist(0, popularBrandCount);
      brandList = list.sublist(popularBrandCount, list.length);
    } else {
      brandList = list;
    }
    allBrandList = list;
    _handleBrandList();
  }
 
  void _handleBrandList() {
    List<SelectBrandEntity> productBrandList = brandList;
    if (productBrandList.isEmpty) return;

    for (int i = 0, length = productBrandList.length; i < length; i++) {
      String tag = productBrandList[i].firstLetter ?? '';
      if (RegExp('[A-Z]').hasMatch(tag)) {
        productBrandList[i].tagIndex = tag;
      } else {
        productBrandList[i].tagIndex = '#';
      }
    }
    // A-Z sort.
    SuspensionUtil.sortListBySuspensionTag(productBrandList);

    // show sus tag.
    SuspensionUtil.setShowSuspensionStatus(productBrandList);

    // add header.
    if (popularBrand.isNotEmpty) {
      productBrandList.insert(0, SelectBrandEntity(name: 'header', tagIndex: '')); //index bar support local images.
    }
  }
 
  Future<void> searchBrandOnChange(String input) async {
    showClearButton = input.isNotEmpty;
    if (input.isBlank == true) return; 
    var start = input.substring(0, input.length - (input.length - 1));
    var end = '~';
    if (input.length > 1) {
      end = input.substring(input.length - 1, input.length);
    }
 
    List<SelectBrandEntity> list = [];
    for (var element in allBrandList) {
      if (element.name?.contains(start) == true && element.name?.contains(end) == true) {
        list.insert(0, element);
      } else {
        if (element.name?.contains(start) == true || element.name?.contains(end) == true) {
          list.add(element);
        }
      }
    }
    searchBrandList.clear();
    searchBrandList.addAll(list);
  }
}

class SelectBrandEntity extends ISuspensionBean {
  SelectBrandEntity({
    this.brandId,
    this.name,
    this.enname,
    this.firstLetter,
    this.type,
    this.sort,
    this.icon,
    this.status,
    this.tagIndex,
  });

  SelectBrandEntity.fromJson(dynamic json) {
    brandId = json['brandId'];
    name = json['name'];
    enname = json['enname'];
    firstLetter = json['firstLetter'];
    type = json['type'];
    sort = json['sort'];
    icon = json['icon'];
    status = json['status'];
  }

  int? brandId; 
  String? name; 
  String? enname; 
  String? firstLetter; 
  int? type;
  int? sort;
  String? icon;  
  int? status;
  String? tagIndex; 

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['brandId'] = brandId;
    map['name'] = name;
    map['enname'] = enname;
    map['firstLetter'] = firstLetter;
    map['type'] = type;
    map['sort'] = sort;
    map['icon'] = icon;
    map['status'] = status;
    return map;
  }

  @override
  String getSuspensionTag() => tagIndex??'';
}

abstract class ISuspensionBean {
  bool isShowSuspension = false;

  String getSuspensionTag(); //Suspension Tag
}

class WaitUserPayBusinessLogic {
  OrderPayEntity? payEntity;
 
  bool showOtherPayMode = false;
 
  ServWorkPayModeList? payModeEntity;
 
  List<OrderPayChannelList> payChannelList = [];
 
  PushMsgData pushMsgData = PushMsgData();
 
  ScanCodeUrlData scanCodeData = ScanCodeUrlData();
 
  List<PayProductList> payProductList = [];
 
  int currentPayProductIndex = 0;
 
  bool showQueryPayResultWidget = false;
 
  String remark = '';
 
  String payChannelName = '';
 
  int payChannelId = 0;
 
  Future<void> getListPayMode(OrderPayEntity value) async {
    payEntity = value; 
    int userPaymentIndex = payEntity?.servWorkPayModeList?.indexWhere((element) => element.payMode == CommonConstants.userPayment) ?? -1;
    if (userPaymentIndex == -1) return;
    payModeEntity = payEntity?.servWorkPayModeList?[userPaymentIndex];
 
    //   payProductList =   payModeEntity?.payProductList ?? []; 
    var arr = payModeEntity?.payProductList ?? [];
    payProductList = [
      ...arr.where((e) => (e.payProduct != CommonConstants.h5Pay && e.payProduct != CommonConstants.miniProgramPay)).toList(),
    ];
 
    remark = payProductList.first.remark ?? ''; 
    payChannelName = payProductList.first.payChannelList?.first.payChannelName ?? '';
    payChannelId = payProductList.first.payChannelList?.first.payChannelId ?? 0;
 
    PayProductList? scanCodePayProduct = payModeEntity?.payProductList?.firstWhere((element) => element.payProduct == CommonConstants.scanCodePay, orElse: () => PayProductList());
    payChannelList = scanCodePayProduct?.payChannelList ?? [];
 
    int firstIndex = payEntity?.servWorkPayModeList?.indexWhere((element) => element.payMode == CommonConstants.userPayment) ?? -1;
    showOtherPayMode = (firstIndex != -1) && (payEntity?.servWorkPayModeList?.length ?? 0) > 1;
  }
}

class WaitUserPayParameter {
  WaitUserPayParameter({
    required this.servOrderId,
    required this.servWorkId,
    required this.deliverModuleId,
    required this.extendData,
    required this.payAmount,
    required this.amountType,
  });

  WaitUserPayParameter.fromJson(dynamic json) {
    servOrderId = json['servOrderId'];
    servWorkId = json['servWorkId'];
    deliverModuleId = json['deliverModuleId'];
    extendData = json['extendData'];
    payAmount = int.tryParse(json['payAmount'] ?? '0') ?? 0;
    amountType = int.tryParse(json['amountType'] ?? '0') ?? 0;
  }

  String servOrderId = ''; 
  String servWorkId = ''; 
  String deliverModuleId = '';  
  String extendData = ''; 
  int payAmount = 0; 
  int amountType = 0; 

  Map<String, String> toJson() {
    final map = <String, String>{};
    map['servOrderId'] = servOrderId;
    map['servWorkId'] = servWorkId;
    map['deliverModuleId'] = deliverModuleId;
    map['extendData'] = extendData;
    map['payAmount'] = '$payAmount';
    map['amountType'] = '$amountType';
    return map;
  }
}
 
class ScanCodeUrlData {
  ScanCodeUrlData({
    this.qrCodeImgStatus,
    this.qrCode,
  });

  int? qrCodeImgStatus; 
  String? qrCode = ''; 

  ScanCodeUrlData.fromJson(dynamic json) {
    qrCodeImgStatus = json['qrCodeImgStatus'];
    qrCode = json['qrCode'];
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['qrCodeImgStatus'] = qrCodeImgStatus;
    map['qrCode'] = qrCode;
    return map;
  }
}
 
class SendPayMessageBody {
  SendPayMessageBody({
    this.servOrderId,
    this.servWorkId,
    this.payPlat,
    this.payEntry,
    this.amountType,
    this.payMode,
    this.payProduct,
    this.payChannelId,
    this.payTargetChannelId,
    this.amount,
    this.extendData,
  });

  SendPayMessageBody.fromJson(dynamic json) {
    servOrderId = json['servOrderId'];
    servWorkId = json['servWorkId'];
    payPlat = json['payPlat'];
    payEntry = json['payEntry'];
    amountType = json['amountType'];
    payMode = json['payMode'];
    payProduct = json['payProduct'];
    payChannelId = json['payChannelId'];
    payTargetChannelId = json['payTargetChannelId'];
    amount = json['amount'];
    extendData = json['extendData'];
  }

  String? servOrderId;
  String? servWorkId;
  int? payPlat;  
  int? payEntry; 
  int? amountType;  
  int? payMode;  
  int? payProduct;  
  int? payChannelId;  
  int? payTargetChannelId;  
  int? amount; 
  String? extendData; 

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['servOrderId'] = servOrderId;
    map['servWorkId'] = servWorkId;
    map['payPlat'] = payPlat;
    map['payEntry'] = payEntry;
    map['amountType'] = amountType;
    map['payMode'] = payMode;
    map['payProduct'] = payProduct;
    map['payChannelId'] = payChannelId;
    map['payTargetChannelId'] = payTargetChannelId;
    map['amount'] = amount;
    map['extendData'] = extendData;
    return map;
  }
}

 
class PushMsgData {
  PushMsgData({
    this.servOrderId,
    this.servWorkId,
    this.result,
    this.qrCode,
  });

  PushMsgData.fromJson(dynamic json) {
    servOrderId = json['servOrderId']?.toString() ?? '';
    servWorkId = json['servWorkId']?.toString() ?? '';
    result = json['result'];
    qrCode = json['qrCode'];
  }

  String? servOrderId;
  String? servWorkId;
  int? result; 
  String? qrCode; 

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['servOrderId'] = servOrderId;
    map['servWorkId'] = servWorkId;
    map['result'] = result;
    map['qrCode'] = qrCode;
    return map;
  }
}


class PayProductList {
  PayProductList({
    this.payProduct,
    this.payProductName,
    this.payChannelList,
    this.articleId,
    this.remark,
  });

  PayProductList.fromJson(dynamic json) {
    payProduct = json['payProduct'];
    payProductName = json['payProductName'];
    articleId = json['articleId'];
    remark = json['remark'];
    if (json['payChannelList'] != null) {
      payChannelList = [];
      json['payChannelList'].forEach((v) {
        payChannelList?.add(OrderPayChannelList.fromJson(v));
      });
    }
  }

  int? payProduct; 
  String? payProductName;  
  List<OrderPayChannelList>? payChannelList; 
  int? articleId; 
  String? remark;  

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['payProduct'] = payProduct;
    map['payProductName'] = payProductName;
    map['articleId'] = articleId;
    map['remark'] = remark;
    if (payChannelList != null) {
      map['payChannelList'] = payChannelList?.map((v) => v.toJson()).toList();
    }
    return map;
  }
}

class OrderPayChannelList {
  OrderPayChannelList({
    this.payChannelId,
    this.payChannelName,
    this.payTargetChannelId,
    this.isSelected = false,
  });

  OrderPayChannelList.fromJson(dynamic json) {
    payChannelId = json['payChannelId'];
    payChannelName = json['payChannelName'];
    payTargetChannelId = json['payTargetChannelId'];
  }

  int? payChannelId;  
  String? payChannelName;  
  int? payTargetChannelId; 
  bool isSelected = false;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['payChannelId'] = payChannelId;
    map['payChannelName'] = payChannelName;
    map['payTargetChannelId'] = payTargetChannelId;
    return map;
  }
}

Thank you again for your help, and I hope to receive a response as soon as possible

**Comment by huycozy** [comment]
Thanks for the update. But the sample code above still has some undefined classes: OrderPayEntity, SuspensionUtil, `isBlank` String extension?, ServWorkPayModeList, etc. Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thanks!

**Comment by qianzhi888** [comment]
Okay, thank you for your reply again. I will provide you with additional code content for these items

OrderPayEntity:
class OrderPayEntity {
  OrderPayEntity({this.servOrderId, this.servWorkId, this.payPlat, this.payEntry, this.amountType, this.completeThirdApp, this.needVerifyCode, this.servWorkPayModeList});

  OrderPayEntity.fromJson(dynamic json) {
    servOrderId = json['servOrderId']?.toString() ?? '';
    servWorkId = json['servWorkId']?.toString() ?? '';
    payPlat = json['payPlat'];
    payEntry = json['payEntry'];
    amountType = json['amountType'];
    completeThirdApp = json['completeThirdApp'];
    needVerifyCode = json['needVerifyCode'];
    if (json['servWorkPayModeList'] != null) {
      servWorkPayModeList = [];
      json['servWorkPayModeList'].forEach((v) {
        servWorkPayModeList?.add(ServWorkPayModeList.fromJson(v));
      });
    }
  }

  String? servOrderId; 
  String? servWorkId;  
  int? payPlat; 
  int? payEntry; 
  int? amountType;  
  int? completeThirdApp;  
  int? needVerifyCode;  
  List<ServWorkPayModeList>? servWorkPayModeList; 

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['servOrderId'] = servOrderId;
    map['servWorkId'] = servWorkId;
    map['payPlat'] = payPlat;
    map['payEntry'] = payEntry;
    map['amountType'] = amountType;
    map['completeThirdApp'] = completeThirdApp;
    map['needVerifyCode'] = needVerifyCode;
    if (servWorkPayModeList != null) {
      map['servWorkPayModeList'] = servWorkPayModeList?.map((v) => v.toJson()).toList();
    }
    return map;
  } 
}

class ServWorkPayModeList {
  ServWorkPayModeList({
    this.payMode,
    this.payModeName,
    this.payProductList,
  });

  ServWorkPayModeList.fromJson(dynamic json) {
    payMode = json['payMode'];
    payModeName = json['payModeName'];
    if (json['payProductList'] != null) {
      payProductList = [];
      json['payProductList'].forEach((v) {
        payProductList?.add(PayProductList.fromJson(v));
      });
    }
  }

  int? payMode;  
  String? payModeName;  
  List<PayProductList>? payProductList;  

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['payMode'] = payMode;
    map['payModeName'] = payModeName;
    if (payProductList != null) {
      map['payProductList'] = payProductList?.map((v) => v.toJson()).toList();
    }
    return map;
  }
}

class PayProductList {
  PayProductList({
    this.payProduct,
    this.payProductName,
    this.payChannelList,
    this.articleId,
    this.remark,
  });

  PayProductList.fromJson(dynamic json) {
    payProduct = json['payProduct'];
    payProductName = json['payProductName'];
    articleId = json['articleId'];
    remark = json['remark'];
    if (json['payChannelList'] != null) {
      payChannelList = [];
      json['payChannelList'].forEach((v) {
        payChannelList?.add(OrderPayChannelList.fromJson(v));
      });
    }
  }

  int? payProduct;  
  String? payProductName;  
  List<OrderPayChannelList>? payChannelList;  
  int? articleId; 
  String? remark; 

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['payProduct'] = payProduct;
    map['payProductName'] = payProductName;
    map['articleId'] = articleId;
    map['remark'] = remark;
    if (payChannelList != null) {
      map['payChannelList'] = payChannelList?.map((v) => v.toJson()).toList();
    }
    return map;
  }
}

class OrderPayChannelList {
  OrderPayChannelList({
    this.payChannelId,
    this.payChannelName,
    this.payTargetChannelId,
    this.isSelected = false,
  });

  OrderPayChannelList.fromJson(dynamic json) {
    payChannelId = json['payChannelId'];
    payChannelName = json['payChannelName'];
    payTargetChannelId = json['payTargetChannelId'];
  }

  int? payChannelId;  
  String? payChannelName; 
  int? payTargetChannelId;  
  bool isSelected = false;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['payChannelId'] = payChannelId;
    map['payChannelName'] = payChannelName;
    map['payTargetChannelId'] = payTargetChannelId;
    return map;
  }
}

Suspension Util
class SuspensionUtil {
  /// sort list by suspension tag.
  static void sortListBySuspensionTag(List<ISuspensionBean>? list) {
    if (list == null || list.isEmpty) return;
    list.sort((a, b) {
      if (a.getSuspensionTag() == '@' || b.getSuspensionTag() == '#') {
        return -1;
      } else if (a.getSuspensionTag() == '#' || b.getSuspensionTag() == '@') {
        return 1;
      } else {
        return a.getSuspensionTag().compareTo(b.getSuspensionTag());
      }
    });
  }

  /// get index data list by suspension tag.
  static List<String> getTagIndexList(List<ISuspensionBean>? list) {
    List<String> indexData = [];
    if (list != null && list.isNotEmpty) {
      String? tempTag;
      for (int i = 0, length = list.length; i < length; i++) {
        String tag = list[i].getSuspensionTag();
        if (tempTag != tag) {
          indexData.add(tag);
          tempTag = tag;
        }
      }
    }

    return indexData;
  }

  /// set show suspension status.
  static void setShowSuspensionStatus(List<ISuspensionBean>? list) {
    if (list == null || list.isEmpty) return;
    String? tempTag;
    for (int i = 0, length = list.length; i < length; i++) {
      String tag = list[i].getSuspensionTag();
      if (tempTag != tag) {
        tempTag = tag;
        list[i].isShowSuspension = true;
      } else {
        list[i].isShowSuspension = false;
      }
    }
  }
}

The isBlank method is a null operation on strings, which can be replaced with isEmpty

Thank you for your reply. I hope what I have provided can be helpful to you. Please reply as soon as possible

**Comment by huycozy** [comment]
Thanks but there is still missing `CommonConstants`. Could you please create an open-source project (GitHub) and push the sample code there? Please add license the code in the repository under some open-source license (e.g. MIT, Apache, BSD, GPL) so that we may look into it. This will be helpful for others may look into it easier for investigation further. Thank you!

**Comment by qianzhi888** [comment]
class CommonConstants{

  static const userPayment = 10;

  static const h5Pay = 3;


  static const miniProgramPay = 6;


  static const scanCodePay = 1;

}
Sorry to trouble you again, this is the constant used in CommonConstants in the code
Thank you very much for your reply

**Comment by qianzhi888** [comment]
Hello, I have put these unit test codes into a brand new project according to your requirements. It is possible to successfully execute unit test coverage, but in our daily development of large projects, errors always occur. The unit test code is the same. Why is this? I don't know why this is happening

This is the detailed error message when executing fltutor test -- coverage       
                                                                     
  Shell subprocess crashed with segmentation fault.
  package:flutter_tools/src/test/flutter_tester_device.dart 240:73  FlutterTesterTestDevice.finished
  ===== asynchronous gap ===========================
  dart:async/future.dart 611:5                                      Future.any.onValue

When executing the Flutter test separately, it can pass the execution
I hope you can help me. Thank you again

**Comment by huycozy** [comment]
Thanks for the update. When I run your tests, all of them are successful:

```console
➜  reproduce_issues_3 flutter test --coverage 
00:02 +1: Search brand                                                                                                                                                                                 
The search result is：海尔
The search result is：海信
The search result is：海瑞弗
The search result is：海普
00:03 +3: All tests passed!  
```

I think your case is similar to https://github.com/flutter/flutter/issues/124145 which is only reproducible with a large number of tests (500-600 tests) or a large project as you mentioned. 

You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a minimal sample code that can produce the issue. And please share it here when you have such an example. Thank you!

**Comment by pastre** [comment]
In our case, we had a `// coverage:ignore-start` without a `// coverage:ignore-end` which caused everything to hang. Removing it fixed the issue
