### ISSUE TITLE
ThemeData should initialize primaryColor to primarySwatch.primary

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#14498]
ThemeData should initialize its primaryColor to primarySwatch.primary.

Currently primarySwatch[500] is used unconditionally for Brightness.light themes. MaterialColor doesn't actually save the primaryColor's index, but that would be trivial.

cc @DaveShuckerow

**Comment by jonahwilliams** [comment]
Since `ColorSwatch` implements `Color` (specifically, the primary color) the only code change required is something like.

```dart
primaryColor ??= isDark ? Colors.grey[900] : primarySwatch; //primarySwatch[500]
```

**Comment by HansMuller** [comment]
The suggested change looks right to me.
