### ISSUE TITLE
[go_router] Support pushAndRemoveUntil

### ISSUE THREAD

**Issue by Jay-57blocks** [flutter/flutter#144924]
### Use case

There are currently four pages A, B, C, and D. How can I return directly from page D to page A with routing? Is there any way? I didn't find the implementation of pushAndRemoveUntil, which is very frustrating. Looking forward to your answer.

### Proposal

Navigator.of(context).pushNamedAndRemoveUntil('/LoginScreen', (Route<dynamic> route) => false);

**Comment by huycozy** [comment]
I can see this has been raised at https://github.com/flutter/flutter/issues/99112 but it's closed. Keeping this open as a new issue.

**Comment by ValentinVignal** [comment]
@Jay-57blocks In your case, if you need to replace the entire configuration, using a `.go` should work no?

```dart
GoRouter.of(context).go('/LoginScreen');
```


---

Also, if you want to preserve some routes, would a `popUntil()` works in your case?
If your history is something like `['/a', '/b', '/c', '/d']` and you want to pop until `'/b'`, maybe something like below would work? 

```dart
GoRouter.of(context).popUntil((route) => route.location == '/b');
```

**Comment by ValentinVignal** [comment]
> Thanks, I only found GoRouter.of(context).pop(), not the popUntil you mentioned

`pop` and `go` are already implemented. `popUntil` is not implemented yet. I made a PR to propose a possible implementation
https://github.com/flutter/flutter/issues/144924

**Comment by huycozy** [comment]
@ValentinVignal Per the last comment https://github.com/flutter/flutter/issues/99112#issuecomment-1658974503, `popUntil` is a separate issue at https://github.com/flutter/flutter/issues/131625. So you can link your PR to that one.

@Jay-57blocks Will `popUntil` fit your case or is `pushNamedAndRemoveUntil` still in your needs?

**Comment by ValentinVignal** [comment]
@huycozy thank you, I'll link my PR to the other issue. I think we can keep this issue as `pushNamedAndRemoveUntil` will ultimately be needed ?

**Comment by huycozy** [comment]
@ValentinVignal Thanks for the contribution. Yes, this is still open.

**Comment by thevivekvaghani** [comment]
> @ValentinVignal Per the last comment [#99112 (comment)](https://github.com/flutter/flutter/issues/99112#issuecomment-1658974503), `popUntil` is a separate issue at #131625. So you can link your PR to that one.
> 
> @Jay-57blocks Will `popUntil` fit your case or is `pushNamedAndRemoveUntil` still in your needs?

Yes, pushNamedAndRemoveUntil still needs.

**Comment by tasaddaq-hussain** [comment]
Hi am facing same problem with "go_router" about pushNamedAndRemoveUntil.
there is any solution ?
thanks!
