### ISSUE TITLE
[Cupertino]: Style of text in `CupertinoActionSheetAction` is different how origin `IOS` text style

### ISSUE THREAD

**Issue by ziqq** [flutter/flutter#144927]
### Steps to reproduce

Make `CupertinoActionSheet` with `CupertinoActionSheetAction`

### Expected results

<img width="375" alt="image" src="https://github.com/flutter/flutter/assets/20646071/2a6b1f98-78a1-4dbe-8da6-15c6f63a8d49">

### Actual results

<img width="375" alt="image" src="https://github.com/flutter/flutter/assets/20646071/a2146622-0054-4c19-88da-6de637088f76">

### Code sample

<details open><summary>Code sample</summary>

```dart
CupertinoActionSheetAction(
  isDestructiveAction: true,
  onPressed: () {
    Navigator.of(context, rootNavigator: true).pop();
  },
  child: Text(context.stringOf().actionRemoveClient),
)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3.1 23D60 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.0)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@ziqq 
There's a similar open issue describing your case https://github.com/flutter/flutter/issues/37086, so please follow-up in it for further updates. Closing this as a duplicate.
