### ISSUE TITLE
Problem when use Dragable inside gridview or listview

### ISSUE THREAD

**Issue by naneps** [flutter/flutter#144973]
### Steps to reproduce

I have a shopping cart feature where every item in the grid can be dragged into the shopping cart,

### Expected results

After dragging the widget you should be able to scroll straight away

### Actual results

But now after dragging the widget when I want to scroll the grid it doesn't take long to scroll, I have to click outside the grid first before I can scroll again

### Code sample

<details open><summary>Code sample</summary>

### this is item widget as dragable

```dart
class ItemWidget extends StatelessWidget {
  final ItemModel? item;
  RxBool? isSelected;
  final Function(CartItemModel?)? onAddToCart;
  ItemWidget({
    super.key,
    required this.item,
    this.onAddToCart,
    this.isSelected,
  });
  @override
  Widget build(BuildContext context) {
    return Draggable<CartItemModel>(
      onDraggableCanceled: (velocity, offset) {

      },
      ignoringFeedbackPointer: true,
      rootOverlay: true,
      feedback: Material(
       .............
      ),
      maxSimultaneousDrags: 2,
      childWhenDragging: Container(
          ......
      ),
      data: CartItemModel(
     .......
      ),
   ........
        
```
### this is list of item
```dart
GridView.builder(
              controller: controller.scrollController,
              padding: const EdgeInsets.all(10),
              shrinkWrap: true,
              itemCount: state.length,
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              .......
              ),
              itemBuilder: (context, index) {
                final item = state[index];
                return Obx(() {
                  return ItemWidget(
                .......
                  )
```
### this is drag target
``` dart
class CartItemsView extends GetView<CartItemController> {
  const CartItemsView({Key? key}) : super(key: key);
  @override
  get controller => Get.put(CartItemController());
  @override
  Widget build(BuildContext context) {
    return DragTarget<CartItemModel>(onAccept: (data) {
      controller.cartController.addCart(cartItem: data);
    }, builder: (context, candidateData, rejectedData) {
      return Obx(() {
        return SingleChildScrollView(
          child: Column(
            children: [
              const CartItemsWidget(),
              Visibility(
                visible: !controller
                        .cartController.cart.value.promoFreeItems!.isNotEmpty ||
                    controller
                        .cartController.cart.value.promoDiscounts!.isNotEmpty,
                child: const CartItemsPromoWidget(),
              ),
            ],
          ),
        );
      });
    });
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/72372613/bed0693c-6a23-4cf4-a3d7-069584def184

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS D:\projek\Yubi-POS-2> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.22631.3155], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
[√] VS Code (version 1.87.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Perhaps there is a conflict between gestures here. For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thank you!

**Comment by naneps** [comment]
> Perhaps there is a conflict between gestures here. For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thank you!

### Here is xample code representate this issue
```dart
import 'package:flutter/material.dart';
import 'package:gragable_widget/models/item_model.dart';

class ItemsView extends StatefulWidget {
  const ItemsView({super.key});

  @override
  State<ItemsView> createState() => _ItemsViewState();
}

class _ItemsViewState extends State<ItemsView> {
  final List<ItemModel> items = [
    ItemModel(id: 1, name: 'Item 1', price: '100'),
    ItemModel(id: 2, name: 'Item 2', price: '200'),
    ItemModel(id: 3, name: 'Item 3', price: '300'),
    ItemModel(id: 4, name: 'Item 4', price: '400'),
    ItemModel(id: 5, name: 'Item 5', price: '500'),
    ItemModel(id: 6, name: 'Item 6', price: '600'),
  ];
  List<ItemModel> selectedItems = [];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Items'),
      ),
      body: Column(
        children: [
          SizedBox(
            height: MediaQuery.of(context).size.height * 0.5,
            child: GridView.builder(
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
              ),
              itemCount: items.length,
              itemBuilder: (context, index) {
                return Draggable<ItemModel>(
                  data: items[index],
                  feedback: Card(
                    child: Column(
                      children: [
                        Text(items[index].name!),
                        Text(items[index].price!),
                      ],
                    ),
                  ),
                  child: Card(
                    child: Column(
                      children: [
                        Text(items[index].name!),
                        Text(items[index].price!),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
          const Divider(),
          const Text('Selected Items'),
          const Divider(),
          SizedBox(
            height: MediaQuery.of(context).size.height * 0.2,
            child: DragTarget<ItemModel>(
              onAccept: (ItemModel item) {
                setState(() {
                  selectedItems.add(item);
                });
              },
              builder: (context, candidateData, rejectedData) {
                return selectedItems.isEmpty
                    ? const Center(
                        child: Text('Drag items here'),
                      )
                    : ListView.builder(
                        scrollDirection: Axis.horizontal,
                        itemCount: selectedItems.length,
                        itemBuilder: (context, index) {
                          return Card(
                            child: Column(
                              children: [
                                Text(selectedItems[index].name!),
                                Text(selectedItems[index].price!),
                              ],
                            ),
                          );
                        },
                      );
              },
            ),
          )
        ],
      ),
    );
  }
}

```

**Comment by huycozy** [comment]
I tested the example and also watched your video again, it looks like you were using the mouse scroll instead of the swipe gesture (on a POS machine) at 0:16-0:18, right? Then, you used a swipe gesture on the draggable items, so you think there is a bug at 0:29-0:33. Here there is a difference between input actions.

I think this works as intended. It will always work with mouse scrolling (at whatever point the cursor is pointing to), and on gaps between draggable items with swipe gestures.

**Comment by naneps** [comment]
> I tested the example and also watched your video again, it looks like you were using the mouse scroll instead of the swipe gesture (on a POS machine) at 0:16-0:18, right? Then, you used a swipe gesture on the draggable items, so you think there is a bug at 0:29-0:33. Here there is a difference between input actions.
> 
> I think this works as intended. It will always work with mouse scrolling (at whatever point the cursor is pointing to), and on gaps between draggable items with swipe gestures.

indeed the video above uses an emulator, but I have tried it on a real device using a touch screen, after dragging an item then when I want to scroll the grid the item actually drags and the grid doesn't scroll, after tapping outside the grid it can be scrolled again
@huycozy

**Comment by huycozy** [comment]
How do you scroll the list? (with swipe gesture or using mouse?).

**Comment by naneps** [comment]
> How do you scroll the list? (with swipe gesture or using mouse?).

with gesture or mouse its same

**Comment by naneps** [comment]
Uploading IMG_6400.mov…

**Comment by naneps** [comment]
> > How do you scroll the list? (with swipe gesture or using mouse?).
> 
> with gesture or mouse its same
> 
>  IMG_6400.mov
@huycozy 
in this case, when scrolling after dragging an item, when scrolling over the item it cannot be scrolled

**Comment by huycozy** [comment]
Could you record a demo (video) of the first time when the scrolling works (haven't dragged any item yet)? The reason I ask this is because I have a little doubt that your pointer down / touch down position is different between tests. 

If you notice my demo video below: If I scroll the list with pointer down on an item, the item is always dragged. Meanwhile, if I scroll the list with pointer down on a space between items, the list is scrollable. These are the expected behaviors.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/12824b4d-3ce3-4834-8988-8cb3236e7e4a
</details>

**Comment by naneps** [comment]
> Could you record a demo (video) of the first time when the scrolling works (haven't dragged any item yet)? The reason I ask this is because I have a little doubt that your pointer down / touch down position is different between tests.
> 
> If you notice my demo video below: If I scroll the list with pointer down on an item, the item is always dragged. Meanwhile, if I scroll the list with pointer down on a space between items, the list is scrollable. These are the expected behaviors.
> 
> Demo
>  Screen.Recording.2024-03-14.at.10.59.43.mov

So, before dragging an item you can scroll normally even though the scroll position is above the item, after dragging the item the problem is that the scroll has to be between the item gaps. That will be a UX problem when users use it, is there a solution?

**Comment by huycozy** [comment]
>So, before dragging an item you can scroll normally even though the scroll position is above the item, after dragging the item the problem is that the scroll has to be between the item gaps.

It seems you haven't watched my demo, please check it again and notice the mouse position when dragging. In short, the list can't be scrolled by dragging on the item (even at the beginning). But if you put your finger/mouse down on the item gaps, the list is scrollable.

>That will be a UX problem when users use it, is there a solution?

(Just my suggestion for this case) you can implement your case with options below:
- Add a smaller button in the item corner. Users can only drag the item when holding that button. Similar to [ReorderableListView](https://api.flutter.dev/flutter/material/ReorderableListView-class.html)
- Use an additional flag, eg: `bool isDragging = false`. It is only `true` when dragging item with long press gesture. Once the dragging ends, reset the flag

cc @moffatman for any other ideas on this case
