### ISSUE TITLE
Creating New Flutter Project generates PRODUCT_BUNDLE_IDENTIFIER, applicationId and package names with app name duplicated

### ISSUE THREAD

**Issue by killermonk** [flutter/flutter#14493]
Pulling bug from original location in the google issue tracker: https://issuetracker.google.com/issues/72938960

## Steps to Reproduce

When creating a new Flutter project in the opening screen of Android Studio, for example `my_flutter_app`, the following identifiers are generated (see attached image `android_studio_flutter_project.jpg`):

```
PRODUCT_BUNDLE_IDENTIFIER = com.mycompany.my_flutter_app.myFlutterApp; (ios/Runner.xcodeproj/project.pbxproj)
package com.mycompany.myflutterapp.myflutterapp; (MainActivity.java)
applicationId "com.mycompany.myflutterapp.myflutterapp" (app/build.gradle)
package="com.mycompany.myflutterapp.myflutterapp"> (AndroidManifest.xml)
```

In IntelliJ IDEA CE, however (see attached image `intellij_idea_ce_flutter_project.jpg`): 

```
PRODUCT_BUNDLE_IDENTIFIER = com.mycompany.myFlutterApp; (ios/Runner.xcodeproj/project.pbxproj)
package com.mycompany.myflutterapp; (MainActivity.java)
applicationId "com.mycompany.myflutterapp" (app/build.gradle)
package="com.mycompany.myflutterapp"> (AndroidManifest.xml)
```

Also, `flutter create --org com.mycompany` works correctly.
```
Build: 3.0.1, AI-171.4443003, 201711091821, 
```
```
AI-171.4443003, JRE 1.8.0_152-release-915-b08x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1920x1080, 1920x1080, 1440x900; Retina 
```

**Comment by killermonk** [comment]
![intellij_idea_ce_flutter_project](https://user-images.githubusercontent.com/1088866/35869599-b2d58b12-0b1c-11e8-8500-2de9594c5e8a.jpg)
![android_studio_flutter_project](https://user-images.githubusercontent.com/1088866/35869591-ac4b333c-0b1c-11e8-8c81-2bcf34f0a27f.jpg)

**Comment by zoechi** [comment]
I can not reproduce

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
````
