### ISSUE TITLE
Switch rendering issues

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#145]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Aug 25, 2015 at 21:35 GMT_
_Originally opened as https://github.com/flutter/engine/issues/823_

----

These are particularly visible with examples/widgets/big_switch.dart:

- [x] Switch thumb doesn't support being dragged
- [x] The switch is not centered within the ink splash

**Comment by abarth** [comment]
I fixed both of these issues recently.
