### ISSUE TITLE
Slow launch time on Play Store's performance test phones

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14502]
![screen shot 2018-02-06 at 1 11 03 pm](https://user-images.githubusercontent.com/156888/35884332-34db5cf0-0b3f-11e8-94aa-4c15ef074738.png)

Slow launch time for some of these test phones. Moto G4, Huawei P9, even the Galaxy S7 Edge (Exynos) had 2s+ launch times. 

Video from Galaxy S7 https://streamable.com/4q6me

The memory consumption graph is interesting too in that our memory consumption is low while it's showing a white screen. 

See if it's reproducible. 

Seems like the Play Store's performance test is based on Firebase Test Lab aka Cloud Test Lab aka Appurify

**Comment by jason-simmons** [comment]
I saw a major increase in startup time in debug/JIT mode as of commit https://github.com/flutter/flutter/commit/85b5b88e0b66959982e2a073771bd49b25dd6641.  Looks like this is caused by https://github.com/dart-lang/sdk/issues/32024

However, I haven't noticed a difference in AOT/release startup time

**Comment by mraleph** [comment]
@jason-simmons that issue is only tracking Dart 2 (Kernelized) pipeline. Actual issue is likely this one dart-lang/sdk#32077 @jensjoha is gonna look at that.

**Comment by xster** [comment]
I got an Exynos J7. It definitely takes 3+s to launch the gallery app on it.

**Comment by mraleph** [comment]
@xster is it in debug or in release mode? can you pull a timeline using observatory to see the breakdown?

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/14504.  You can try instrumenting ResourceExtractor.extractResources to verify that this is the same issue.

**Comment by xster** [comment]
Do we have a way to keep the observatory/timeline accessible while tracing startup? 

`flutter run --profile --trace-startup` closes the runner and just dumps a summary. 

`flutter run --profile --trace-startup --resident` doesn't seem to do anything different

**Comment by szakarias** [comment]
Have you been able to verify whether this was related to #14504 ?

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by xster** [comment]
Looks more reasonable on the 1.0 release. 

<img width="965" alt="screen shot 2018-12-06 at 7 35 39 pm" src="https://user-images.githubusercontent.com/156888/49626328-32ef0e80-f98e-11e8-93cb-fa136a8d8b81.png">
