### ISSUE TITLE
Stocks example README for the intl files should also list Windows file paths

### ISSUE THREAD

**Issue by alan-knight** [flutter/flutter#14500]
## Steps to Reproduce

I had a bug filed against intl_translation where I think the issue is just that the user is running the command exactly as given, but on Windows, should be using \ for path separators. The README should probably make that clearer.

https://github.com/dart-lang/intl_translation/issues/21

**Comment by alan-knight** [comment]
@HansMuller

**Comment by alan-knight** [comment]
Also, Windows doesn't expand wildcards in argument parsing, so it needs to pass in all the files explicitly.

**Comment by zoechi** [comment]
I assume this is https://github.com/flutter/flutter/blob/master/examples/stocks/lib/i18n/regenerate.md
(linked to from https://github.com/flutter/flutter/tree/master/examples/stocks)

**Comment by markusaksli-nc** [comment]
Closing due to the stocks example being removed already.
