### ISSUE TITLE
Expose onTapOutside from SearchBar's TextField

### ISSUE THREAD

**Issue by aleripe** [flutter/flutter#145096]
### Use case

All the `TextField`s in my app are set to lose focus closing the keyboard when they're tapped outside. I can't do the same on `SearchBar` as the `onTapOutside` property of `TextField` class is not exposed.

### Proposal

Introduce `onTextOutside` parameter for `SearchBar` and `SearchAnchor` constructors.

**Comment by Sahil-kachhap** [comment]
@danagbemava-nc  I am interested in working on this issue, Can you please assign this work to me? I have signed the CLA and have also contributed to the dart-sdk repo earlier

**Comment by Sahil-kachhap** [comment]
> ### Use case
> All the `TextField`s in my app are set to lose focus closing the keyboard when they're tapped outside. I can't do the same on `SearchBar` as the `onTapOutside` property of `TextField` class is not exposed.
> 
> ### Proposal
> Introduce `onTextOutside` parameter for `SearchBar` and `SearchAnchor` constructors.

Do you have any other use cases (other than losing the focus) for which you want the `onTapOutside` parameter to be exposed by the Searchbar constructor? 
If you only want to unfocus it on being tapped outside, this can be implemented internally in the search bar class, and then there would be no need to expose the parameter.

**Comment by Sahil-kachhap** [comment]
https://github.com/flutter/flutter/assets/54017876/63dd2c88-260b-4a1d-b77c-6cd0142464d3

Here's a fix I have implemented @danagbemava-nc , Let me know if this looks good to go. 
And here's what I have done: I utilize the focusNode property of searchbar class and then I use it in onTapOutside property of underlying textfield.

```
onTapOutside: _focusNode.unfocus();
```

the change has been made [here](https://github.com/flutter/flutter/blob/985576dbfdff5e9321941d9f66cb33baed337346/packages/flutter/lib/src/material/search_anchor.dart#L1400) - just added a parameter: onTapOutside

**Comment by aleripe** [comment]
> > ### Use case
> > All the `TextField`s in my app are set to lose focus closing the keyboard when they're tapped outside. I can't do the same on `SearchBar` as the `onTapOutside` property of `TextField` class is not exposed.
> > ### Proposal
> > Introduce `onTextOutside` parameter for `SearchBar` and `SearchAnchor` constructors.
> 
> Do you have any other use cases (other than losing the focus) for which you want the `onTapOutside` parameter to be exposed by the Searchbar constructor? If you only want to unfocus it on being tapped outside, this can be implemented internally in the search bar class, and then there would be no need to expose the parameter.

I have no other use case at the moment, but I think it could be more useful to expose it rather than wrap it. But it's your choice!

**Comment by Sahil-kachhap** [comment]
Thanks @aleripe @CicciLeo for sharing this usecase, I will make the relevant changes in the PR based on your responses.
