### ISSUE TITLE
statusBarColor lost when switching between flutter and native

### ISSUE THREAD

**Issue by qeepcologne** [flutter/flutter#145076]
### Steps to reproduce

set Theme which changes statusBarColor

launch flutter from native view the first time: everything is ok
launch native view
launch flutter from native view second time: statusBarColor is not working anymore

(see demo app: launch flutter from mesage button and native from fire native,
used android emulator google pixel8 with default settings)
https://github.com/qeepcologne/flutter-testapp

### Expected results

statusBarColor uses the defined color from theme or AppBar 

### Actual results

statusBarColor is derived from the backgroundColor of the appBar.

### Code sample

```class DemoApp extends StatelessWidget {
  const DemoApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp.router(
      routerConfig: addRouter(),
      theme: Theme.of(context).copyWith(
          appBarTheme: Theme.of(context).appBarTheme.copyWith(
              backgroundColor: Colors.brown,
              systemOverlayStyle: const SystemUiOverlayStyle(statusBarColor: Colors.blue))));
}

```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on Ubuntu Noble Numbat (development branch) 6.8.0-11-generic, locale en_DE.UTF-8)
    • Flutter version 3.19.3 on channel stable at /home/bwahlen/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/bwahlen/android-sdk-linux
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/bwahlen/android-sdk-linux
    • Java binary at: /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /home/bwahlen/android-studio
    • Flutter plugin version 78.2.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "17.0.9" 2023-10-17

[✓] Connected device (3 available)
    • SM G398FN (mobile)           • R58N407FMZF   • android-arm64  • Android 11 (API 30)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 122.0.6261.128

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by qeepcologne** [comment]
![first](https://github.com/flutter/flutter/assets/21581993/818911ea-453a-4bef-bac5-7236e7d2ba6c)
![second](https://github.com/flutter/flutter/assets/21581993/e02a0c9a-8b38-4c76-8701-50dd238c8bd2)

**Comment by darshankawar** [comment]
@qeepcologne 
Looks like it is similar to https://github.com/flutter/flutter/issues/113595 and root-cause seems to be as explained here:
https://github.com/flutter/flutter/issues/113595#issuecomment-1295643949

**Comment by qeepcologne** [comment]
sounds understandable, but this bug is quite old and couln't find acceptable workaround there.

**Comment by darshankawar** [comment]
The linked issue is still open and root-cause is as mentioned in it, I suggest you to follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
