### ISSUE TITLE
Integration test- Issue with Keyboard backspace in textfield

### ISSUE THREAD

**Issue by rawlpcc** [flutter/flutter#145052]
### Steps to reproduce

In Flutter integration tests, when attempting to perform the user action of backspace on a virtual keyboard (such as on a mobile device), the functionality does not work. 

### Expected results

Entered text or characters will be removed

### Actual results

No action is done. Unresponsive. 

### Code sample

<details open><summary>Code sample</summary>

```dart
await tester.sendKeyEvent(LogicalKeyboardKey.backspace); 
```
OR
```
await tester.sendKeyDownEvent(LogicalKeyboardKey.backspace);
```
OR
```
await tester.sendKeyUpEvent(LogicalKeyboardKey.backspace);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screen35 PM](https://github.com/flutter/flutter/assets/158101297/ae7df21f-8647-48f5-b9f1-596b565279c2)

</details>

### Logs

<details open><summary>
</summary>

```console
[══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure was thrown while running async test
code:
Expected: <false>
  Actual: <true>

When the exception was thrown, this was the stack:
#0      fail (package:matcher/src/expect/expect.dart:149:31)
#1      _expect (package:matcher/src/expect/expect.dart:144:3)
#2      expect (package:matcher/src/expect/expect.dart:56:3)
#3      expect (package:flutter_test/src/widget_tester.dart:458:18)
]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary:
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.4 23E214 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] VS Code (version 1.60.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@rawlpcc 
This seems to be a limitation currently per https://github.com/flutter/flutter/issues/9383.
I think other actions like `done` seems to be supported but not backspace. 
Closing in favor of the linked issue.
