### ISSUE TITLE
Tutorial makes a toolbar without enough top padding

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1450]
Following the tutorial instructions at https://flutter.io/tutorial/#basic-widgets gives you a toolbar that looks like this:

![screen](https://cloud.githubusercontent.com/assets/394889/12661323/c537aa42-c5cd-11e5-85ae-5815c492f3cb.png)

**Comment by collinjackson** [comment]
This turned out to be a problem with the tutorial's custom toolbar, not Flutter itself.

**Comment by collinjackson** [comment]
We should update MyToolbar in the tutorial to 

import 'dart:ui' as ui;

and

const EdgeDims.only(left: 8.0, right: 8.0, top: ui.window.padding.top)

**Comment by abarth** [comment]
We can also use more of the real widgets in the tutorial.  Then they'll pad themselves automatically,.

**Comment by collinjackson** [comment]
Yeah, that happens later on in the tutorial, it's the intermediate steps that are confusing.

**Comment by sethladd** [comment]
We should fix this, but this isn't strictly a blocker for the hackathon. Instead of the tutorial, we will offer a Code Lab.

**Comment by Hixie** [comment]
This is obsolete now, right?
