### ISSUE TITLE
Googlers do not have access to add a reference to a cipd package by default

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#145038]
### Type of Request

bug

### Infrastructure Environment

Cocoon cipd self service

### What is happening?

[This part](https://github.com/flutter/cocoon/tree/main/cipd_packages#adding-a-reference-to-the-cipd-package) of the CIPD self service documentation suggests that Googlers have default access to add a reference to a cipd package. 

But when I run the command, in this case `cipd set-ref flutter/ktlint/linux-amd64 -ref version_1_1_1 -version cuHnxtuMe-YkvqnXhXeWPq3i_0TZv4ykCWmDQVxN7f8C`, I get the following (even after `cipd auth-login`)
```
 ! Failed to set ref: "user:***@google.com" has no required WRITER role in prefix "flutter/ktlint/linux-amd64", run `cipd auth-login` to login or relogin
Errors:
  flutter/ktlint/linux-amd64: "user:***@google.com" has no required WRITER role in prefix "flutter/ktlint/linux-amd64", run `cipd auth-login` to login or relogin.
```
(I've redacted my email)

### Steps to reproduce

See above

### Expected results

I expect to have the required permission

**Comment by keyonghan** [comment]
Googlers also need to request access to `flutter-gob-owners` group: go/flutter-aod#available-groups. I will update the cocoon doc.

**Comment by gmackall** [comment]
I created the request, and had it approved, but I still don't appear to have access (same command and result as above)

**Comment by gmackall** [comment]
Closing because it just took some time to propagate, but the command works now.
