### ISSUE TITLE
[Impeller] golden tests on ci are not running with impeller validations

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#145017]
Impeller validations are hidden in release builds, which is what is used for the golden image tests.

I suspect this is hiding the issue with https://github.com/flutter/flutter/issues/130633

We should have validations on for our golden tests.

Note: This is separate and different than vulkan validation layers.

**Comment by zanderso** [comment]
I put up https://github.com/flutter/engine/pull/51346, which could be starting point for this, but I'm not the right person to track down the issues and get it landed.

**Comment by jonahwilliams** [comment]
Lets dedupe this into the existing effort: https://github.com/flutter/flutter/issues/144967
