### ISSUE TITLE
Support customizing keyboard menu

### ISSUE THREAD

**Issue by LucasXu0** [flutter/flutter#145092]
### Use case

Hi, I'm currently working on developing an editor package and have encountered some challenges with implementing the following workflow:

- The user taps the edit area, causing the keyboard to appear.
- The user then taps a toolbar positioned above the keyboard, intending to open a menu.
- At this point, the keyboard is meant to close, and the menu should display.

**The transition between the closing of the keyboard and the display of the menu is not smooth.** This issue is evident in the provided video, where the animation appears jarring.

Current Layout Structure:

When the keyboard is open:
 Column
| 
| -- Editor Area
| -- Toolbar
| -- Keyboard

When the keyboard is closed and the menu is displayed:
Column
| 
| -- Editor Area
| -- Toolbar
| -- Menu

I am seeking advice or solutions to improve the animation transition, making the switch from keyboard display to menu display smoother. Any recommendations on alternative implementations or adjustments to the current approach that could enhance the user experience by providing a more fluid transition would be greatly appreciated.

https://github.com/flutter/flutter/assets/11863087/85f93c0d-e02f-4d60-8f55-409985393802

### Proposal

https://github.com/flutter/flutter/assets/11863087/626ac285-1a38-4e62-be86-fdd1ac8bcd05

**Comment by darshankawar** [comment]
@LucasXu0 
Can you check if your issue / case is same as https://github.com/flutter/flutter/issues/32583 ?

**Comment by LucasXu0** [comment]
Yes, exactly the same issue. I'll close this one.
