### ISSUE TITLE
IllegalStateException at io.flutter.view.FlutterMain.ensureInitializationComplete

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#14513]
## Steps to Reproduce

This crash was recorded by Google Play Console.

- Android: 7.0, 7.1
- Devices: Xperia X Compact, Xperia X Performance, Xperia XZ, Xperia XZs, Xperia Z5, Xperia Z5 Compact, Xperia Z5 Premium, AQUOS Xx 3, AQUOS ZETA, Galaxy S6 Edge, Galaxy S7 Edge, Galaxy S8, Galaxy S8+, Galaxy Feel, M3, P10 lite

I have not yet reproduced this.

## Logs

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2917)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2978)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1628)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6646)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
Caused by: java.lang.RuntimeException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:212)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:150)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:81)
  at me.cartune.android.MainActivity.onCreate (MainActivity.java:28)
  at android.app.Activity.performCreate (Activity.java:6912)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2870)
Caused by: java.lang.NullPointerException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:178)
```

## Flutter Doctor

dev 0.0.22

```
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale ja-JP, channel dev)
    • Flutter version 0.0.22 at /Applications/flutter
    • Framework revision 3001b3307d (7 days ago), 2018-01-30 11:37:15 -0800
    • Engine revision 8f2d72b183
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.7af4db0ea091dddca6b2da851e6dda8d7f9467e8

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30
```

alpha 0.0.20 has this too.

**Comment by najeira** [comment]
v0.2.1 has this too.

**Comment by najeira** [comment]
`FlutterMain.ensureInitializationComplete` raises `NullPointerException`.

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/FlutterMain.java#L196

```java
sResourceExtractor.waitForCompletion();
```

`sResourceExtractor` is null.

`sResourceExtractor` is initialized with the following flow: 
- FlutterApplication.onCreate
  - FlutterMain.startInitialization
    - FlutterMain.initResources

`FlutterMain.ensureInitializationComplete` is called with the following flow: 

- FlutterActivity.onCreate
  - FlutterActivityDelegate.onCreate
    - FlutterMain.ensureInitializationComplete

Always, Application.onCreate is called before Activity.onCreate, right?

I did not know why `sResourceExtractor` would be null.

This crashes happens sometimes, not always, so it may be a matter of timing.

**Comment by najeira** [comment]
v0.4.4 has this.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2796)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2867)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1570)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:156)
  at android.app.ActivityThread.main (ActivityThread.java:6595)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:942)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)
Caused by: java.lang.RuntimeException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:230)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:152)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:81)
  at me.cartune.android.MainActivity.onCreate (MainActivity.java:34)
  at android.app.Activity.performCreate (Activity.java:6910)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1123)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2749)
Caused by: java.lang.NullPointerException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:196)
```

**Comment by zoechi** [comment]
@cbracken

**Comment by jason-simmons** [comment]
Is there a possibility that ensureInitializationComplete() is being called before startInitialization()?

**Comment by timtraversy** [comment]
I just ran into a similar error while trying to run my flutter app in the Android Simulator.

```
09-20 14:56:37.249 5175-5175/edu.gwu.gwpal E/AndroidRuntime: FATAL EXCEPTION: main
    Process: edu.gwu.gwpal, PID: 5175
    java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.gwu.gwpal/edu.gwu.gwpal.MainActivity}: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:184)
        at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:152)
        at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:85)
        at edu.gwu.gwpal.MainActivity.onCreate(MainActivity.kt:10)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
```
It seems like` ensureInitializationComplete()` is being called before `startInitialization()` like you mentioned in your comment. Did anything come to light about this issue? Thanks!

**Comment by najeira** [comment]
v0.8.2

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2917)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2978)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1628)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6646)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:184)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:152)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:85)
  at me.cartune.android.MainActivity.onCreate (MainActivity.java:34)
  at android.app.Activity.performCreate (Activity.java:6912)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2870)
```

**Comment by timtraversy** [comment]
I ultimately solved this by moving all my dart files to a new flutter project, and it has worked on Android since then, but not sure why.

**Comment by awazgyawali** [comment]
Any update on this? I am receiving the same crash.

**Comment by matthew-carroll** [comment]
@awazgyawali Can you provide your flutter doctor output so that we can check your framework and engine versions?

**Comment by JaspervanRiet** [comment]
Started hitting this today. It was solved for me by rebooting my device. It first appeared after my `flutter run` seemingly got stuck on the installation of the apk and I had to cancel out (endless spinning). Logging output and `flutter doctor` below.

```
11-07 22:36:27.747 10403 10403 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.someapp.app/com.someapp.app.MainActivity}: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6944)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
11-07 22:36:27.747 10403 10403 E AndroidRuntime: Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:178)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:152)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:85)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at com.someapp.app.MainActivity.onCreate(MainActivity.java:10)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7174)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
11-07 22:36:27.747 10403 10403 E AndroidRuntime:        ... 9 more
```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.10.2, on Microsoft Windows [Version 10.0.17134.345], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[√] Android Studio (version 3.1)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = D:/Dev/Android\
    X Unable to find bundled Java version.
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.28.2)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

The first time I encountered this I was actually on v0.9.4. I cannot reproduce on my Ubuntu machine. Other attemps to fix it were:

- `flutter clean`
- Changing git branch, so very different code (I wanted to test this since I was working on Android PlatformViews)

**Comment by gary0707** [comment]
Hi, 
it's my second day with Dart & Flutter. I started to hit the same problem, with the same output in Android LogCat. I have noticed that the issue occurs when I try to run the app directly from Android Studio. When I click on the Android Launcher icon (in emulator) the app starts with no crash.

**Comment by zoechi** [comment]
Did Did flutter/engine#5614 fix this?

**Comment by ueabu** [comment]
I am having the same problem. I had been developing using VS code testing on an IOS emulator and when I tried running it on an Android emulator, I got the issues mentioned above. Has there been any fix/Solutions to it ?

**Comment by ueabu** [comment]
Update: I fixed the issue by adding one line to my main activity in android. It looks like this.
`
public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    FlutterMain.startInitialization(this); //Added line 
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
`

Hope this helps.

**Comment by nesger** [comment]
@ueabu yeah, I solve too.

**Comment by allanwolski** [comment]
Same problem of #24287

**Comment by caroline171** [comment]
Same problem on Ubuntu
app crashes

flutter doctor output :
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

```
Any help ?!

**Comment by maks** [comment]
The code generated by `flutter create` leaves a useful comment in Android Manifest that points out the need to call the init method:
```
<!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
```

**Comment by bhardwajsuresh** [comment]
I suddenly started getting this error "java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization" 

This guy ( http://pwu-developer.blogspot.com/2019/04/flutter-unable-to-start-activity.html ) says power off and then power on your physical device. I tried this workaround and it worked.

**Comment by PerLycke** [comment]
I think I got a similar report. A user downloaded our app from Play Store, and on launch it crashes.

His logcat shows this:

> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: FATAL EXCEPTION: main
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: Process: info.car.app, PID: 16179
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{info.car.app/info.car.app.MainActivity}: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at io.flutter.view.FlutterMain.ensureInitializationComplete(Unknown Source:372)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at io.flutter.app.FlutterActivityDelegate.onCreate(Unknown Source:47)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at io.flutter.app.FlutterActivity.onCreate(Unknown Source:5)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at info.car.app.MainActivity.onCreate(Unknown Source:0)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7149)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7140)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
> 05-06 13:59:38.062 16179 16179 E AndroidRuntime: 	... 11 more

**Comment by matthew-carroll** [comment]
Do you know which version of Flutter was running on the device the reported the crash?

**Comment by PerLycke** [comment]
> Do you know which version of Flutter was running on the device the reported the crash?

App was built on Flutter Dev channel, May 3. Device is an OnePlus 6T, latest software (Pie)

**Comment by PerLycke** [comment]
Ok I got another similar report now. @matthew-carroll or @zoechi is it worthless reporting while I'm using the dev channel? Or the opposite maybe? As if this bug is present in dev channel we don't want it in master, if it isn't there yet.

Every time this occurs, it renders the app completely useless for the user. A reboot helps, but it's not sustainable asking users to perform a reboot if it crashes on launch. Putting that kind of info out in advance is not very professional and imo bad for flutter rep.

I can't reproduce it, nor it didn't happen again for the affected users, which makes it hard to debug and hard to find a workaround, if there is any, on app-side. But if there is any help I can provide I'm happy to assist.

**Comment by matthew-carroll** [comment]
If you can provide specific Flutter build numbers for the app that fails then that might help us determine how wide spread the issue is. But giving a channel name probably won't help a lot on its own.

The master channel is upstream from dev, so if dev has a problem then master already has it.

As you mentioned, the issue here is that no one can seem to reproduce this bug. Until we can reproduce it, we can't really try to fix it.

**Comment by yuridiniz** [comment]
Some issues on stable channel (1.5.4)

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2907)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2986)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1641)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6694)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:769)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:191)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:155)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:89)
  at br.com.projectnetwork.onibus.MainActivity.onCreate (MainActivity.java:23)
  at android.app.Activity.performCreate (Activity.java:6984)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1235)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2860)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2986)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1641)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6694)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:769)
```

**Comment by yuridiniz** [comment]
> Update: I fixed the issue by adding one line to my main activity in android. It looks like this.
> 
> ```java
> public class MainActivity extends FlutterActivity {
> 
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     FlutterMain.startInitialization(this); //Added line 
>     super.onCreate(savedInstanceState);
>     GeneratedPluginRegistrant.registerWith(this);
>   }
> }
> ```
> 
> Hope this helps.

Did that correct the problem? can be used as a final solution?

**Comment by matthew-carroll** [comment]
`FlutterMain.startInitialization()` should already be running in your `Application` class. Did you extend `FlutterApplication`?

**Comment by yuridiniz** [comment]
I need to modify the onCreate method to disable hardware acceleration for some devices because of this problem [https://github.com/flutter/flutter/issues/32261](https://github.com/flutter/flutter/issues/32261) and this [https://github.com/flutter/flutter/issues/31580#issuecomment-489636521](https://github.com/flutter/flutter/issues/31580#issuecomment-489636521)

```java
public class MainActivity extends FlutterActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
   if(!needDisableHardwareAcceleration()) {
     getWindow().setFlags(
         WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
         WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);
   }

    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }

  private boolean needDisableHardwareAcceleration() {
    List<Devices> devices = Arrays.asList(
            new Devices("j7elte", Build.VERSION_CODES.M), //Dispositivo desligando
            new Devices("titan_udstv", Build.VERSION_CODES.M), // Dispositivo desligando
            new Devices("titan_umtsds", Build.VERSION_CODES.M) // Comportamento estranho
      );

    Devices currentDevice = new Devices(Build.DEVICE, Build.VERSION.SDK_INT);
    currentDevice.setProduct(Build.PRODUCT);

    for (Devices _device: devices) {
      if(_device.equals(currentDevice))
        return true;
    }

    return false;
  }
}
```

**Comment by dheerajbred** [comment]
I changed the theme in styles.xml and it worked for me

  `  <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">`

**Comment by waelalameen** [comment]
> Update: I fixed the issue by adding one line to my main activity in android. It looks like this.
> 
> ```java
> public class MainActivity extends FlutterActivity {
> 
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     FlutterMain.startInitialization(this); //Added line 
>     super.onCreate(savedInstanceState);
>     GeneratedPluginRegistrant.registerWith(this);
>   }
> }
> ```
> 
> Hope this helps.

Thank you so much, it's solved my problem.

**Comment by n-belokopytov** [comment]
Same issue here - on my Windows PC everything was compiling and running. On my Mac - started to crash on startup after seemingly hanging on `Installing APK...` phase. Rebooting the phone and Mac did not help.

@waelalameen what did you import for these lines to work? I have tried writing them and `FlutterMain` was not resolved.

**Comment by cubuspl42** [comment]
I followed @bhardwajsuresh suggestion and rebooted the phone. It worked...

**Comment by RexNexstream** [comment]
> Update: I fixed the issue by adding one line to my main activity in android. It looks like this.
> 
> ```java
> public class MainActivity extends FlutterActivity {
> 
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     FlutterMain.startInitialization(this); //Added line 
>     super.onCreate(savedInstanceState);
>     GeneratedPluginRegistrant.registerWith(this);
>   }
> }
> ```
> 
> Hope this helps.

Thank You . This solution work.

**Comment by AndroidNils** [comment]
> Update: I fixed the issue by adding one line to my main activity in android. It looks like this.
> 
> ```java
> public class MainActivity extends FlutterActivity {
> 
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     FlutterMain.startInitialization(this); //Added line 
>     super.onCreate(savedInstanceState);
>     GeneratedPluginRegistrant.registerWith(this);
>   }
> }
> ```
> 
> Hope this helps.

I added this line. But now i can not build my app anymore. I got this error:

> /Users/PATH-TO-MY-APP/MainActivity.java:11: error: cannot find symbol
    FlutterMain.startInitialization(this);
    ^
  symbol:   variable FlutterMain
  location: class MainActivity
1 error
Gradle task assembleDevelopmentDebug failed with exit code 1

Any solutions for this problem?

**Comment by najeira** [comment]
Information from a customer who had encountered this problem, it seems to disappear after deleting and reinstalling the app.

**Comment by najeira** [comment]
adding `FlutterMain.startInitialization` did not seems to work for our app. The customer says the app  freeze at startup.

**Comment by eseidelGoogle** [comment]
This is a pretty old issue and looks like it covers two separate cases:
1.  devs using (very old versions of) Flutter in an add-to-app context (custom embedding) and having cases where the initialization sequence doesn't go right.
2.  devs seeing cases where the default embeddings of Flutter would sometimes produce this error?

The first is presumably addressed by the re-write of the add-to-app embedding layer which happened late fall 2019 (note, there are no new comments since then).

The second is concerning, but also might have been addressed by the above.

I'm speculatively closing this.  Please feel empowered to comment/re-open, or better yet file a new bug using the latest Flutter stable.  We did a *ton* of work in this area of the codebase in the last 6 months which hopefully helped with this class of bugs?

Thanks!

**Comment by sudeshkumara** [comment]
Restart your device. It's worked for me.

**Comment by ShadyBoshra2012** [comment]
> 
> 
> Update: I fixed the issue by adding one line to my main activity in android. It looks like this.
> 
> ```java
> public class MainActivity extends FlutterActivity {
> 
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     FlutterMain.startInitialization(this); //Added line 
>     super.onCreate(savedInstanceState);
>     GeneratedPluginRegistrant.registerWith(this);
>   }
> }
> ```
> 
> Hope this helps.

This code is for Java, so for those who using Kotlin, you can use this code.

```kotlin
import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.view.FlutterMain

class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        FlutterMain.startInitialization(this)
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(FlutterEngine(this))
    }
}
```

Hope this works with anyone.

**Comment by ShadyBoshra2012** [comment]
> 
> 
> Update: I fixed the issue by adding one line to my main activity in android. It looks like this.
> 
> ```java
> public class MainActivity extends FlutterActivity {
> 
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     FlutterMain.startInitialization(this); //Added line 
>     super.onCreate(savedInstanceState);
>     GeneratedPluginRegistrant.registerWith(this);
>   }
> }
> ```
> 
> Hope this helps.

This code is for Java, so for those who using Kotlin, you can use this code.

```kotlin
import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.view.FlutterMain

class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        FlutterMain.startInitialization(this)
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(FlutterEngine(this)) // You may need to comment this line.
    }
}
```

Hope this works with anyone.

**Comment by signshah** [comment]
> Update: I fixed the issue by adding one line to my main activity in android. It looks like this.

hi,
Once I updated my **Flutter** to **1.22.2**, there is no onCreate method in **FlutterActivity** class. Also when I put the code (FlutterMain.startInitialization(this)) in the **configureFlutterEngine** method, it says **deprecated API usage**.

**Comment by rodriigovieira** [comment]
I'm facing the same scenario. I upgraded to the newest version and followed the migration guide to the MainActivity file, and there's nothing in the MainActivity class.
