### ISSUE TITLE
Prevent from tapjacking flutter

### ISSUE THREAD

**Issue by Avijaygovinda** [flutter/flutter#145151]
### Use case

anyone have any idea about how to prevent tapjacking in flutter, 

val view = findViewById<View>(android.R.id.content).rootView
view.filterTouchesWhenObscured = true

someone suggested this but nothing works

### Proposal

anyone have any idea about how to prevent tapjacking in flutter, 

val view = findViewById<View>(android.R.id.content).rootView
view.filterTouchesWhenObscured = true

someone suggested this but nothing works

**Comment by darshankawar** [comment]
@Avijaygovinda 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this seems to be more of a support question rather than a bug report or feature request.
