### ISSUE TITLE
Code Lab for Flutter + Firebase

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1451]
Something that can be self-paced, used at home, that teaches Flutter w/ Material Design and Firebase, for iOS and Android.

**Comment by eseidelGoogle** [comment]
My most recent understanding was the @qchong planned to own this?

**Comment by qchong** [comment]
Here are the docs for the Hackathon codelab:

+ [Staged version for dry-run](https://codelabs-preview.appspot.com/?file_id=1esS56X44Nfo5mfVHOkV9Xh5IWbOmfzS0CD59wnjquEc#0) (this is the link we'll share with codelab participants)
+ [Review copy] (https://docs.google.com/a/google.com/document/d/1esS56X44Nfo5mfVHOkV9Xh5IWbOmfzS0CD59wnjquEc/edit?usp=sharing)

**Comment by qchong** [comment]
Marking as closed.
