### ISSUE TITLE
Why Localization in Flutter is so complicated？

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#14518]
Even I defined a map like this : 

static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'title': 'Grab Merchant',
      'help': 'Help',
    },
    'ja': {
      'title': 'タイトル',
      'help': 'ヘルプ',
    },
  };

  String get title {
    return _localizedValues[locale.languageCode]['title'];
  }

  String get help {
    return _localizedValues[locale.languageCode]['help'];
  }

I have to use 'MyLocalizations.of(context).title' to display the localizated string . 

but when I want to define a list like this :

List<MenuItem> items = <MenuItem>[
  new MenuItem('help', MyLocalizations.of(context).help),
];

where can I get the 'context' ?

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
I apologize for not having responded this. Believe it or not, a glitch in my github configuration caused notifications to cease for a while and I overlooked quite a few issues.

FWIW (now): the localization's system complexity, particularly the `BuildContext` dependency you noted, is a result of the fact that app's aren't defined wrt a locale, widget subtrees are. Often they're the same thing, but in some cases part of an app will be within its own [Localizations](https://docs.flutter.io/flutter/widgets/Localizations-class.html).

**Comment by kinex** [comment]
This is a major issue also for me. The BuildContext dependency is very problematic. I need translated strings for example in my "view model" classes which do not have access to BuildContext. If I have understood correctly the BuildContext is needed only for that app can change its language in real-time if user modifies device language settings. In my opinion that is a completely useless feature especially considering the problems it causes to my app architecture. First of all 99% of users never change the device language, they have already selected the correct language when setting up their device. The rest 1% change the device language maybe once during the device lifetime. And most probably they do not have my app running when they do that. And if they have it running, they could just restart the app to active the new language settings.

So in my opinion dependency to BuildContext has been added completely unnecessarily and it is now a major issue. Dependecy to BuildContext should be replaced with "device language changed" callback and with an ability to restart the app.

For my app I have now only two bad options. I have to either refactor my view models classes (ported from C#)  heavily or write my own strings loading system.

**Comment by zoechi** [comment]
The build context is used so that different parts of the view can be configured with different languages.
The `intl` package used for translation doesn't depend on anything from Flutter.
You don't need to use any of that. It's just a generic solution that supports a broad range of requirements.

**Comment by kinex** [comment]
I have followed the guide [Internationalizing Flutter Apps](https://flutter.io/tutorials/internationalization) without thinking it too much. I think the guide tells you to use `DemoLocalizations.of(BuildContext)` whenever you need to access localizations. After a closer look at the sample codes I noticed there is a helper method `DemoLocalizations.load(Locale)` which can be used to load localizations without `BuildContext`. So this solves the problem for my app. Thanks.

**Comment by jjerome00** [comment]
If you are using IntelliJ (Android Studio), you can use the [Flutter i18n](https://github.com/long1eu/flutter_i18n) plugin.

**Comment by JannieT** [comment]
@kinex can you give an example/gist of how you can get to the translated string without using any context? I think this will help many people, like me and [others](https://stackoverflow.com/questions/51803755/getting-buildcontext-in-flutter-for-localization) for which this is a major issue.

**Comment by kinex** [comment]
@JannieT  Here is a sample based on my current implementation:
```
class Strings {
  Strings(Locale locale) : _localeName = locale.toString();

  final String _localeName;

  static Strings current;

  static Future<Strings> load(Locale locale) async {
    await initializeMessages(locale.toString());
    final result = Strings(locale);
    current = result;
    return result;
  }

  static Strings of(BuildContext context) {
    return Localizations.of<Strings>(context, Strings);
  }

  String get title {
    return Intl.message(
      'Hello World',
      name: 'title',
      desc: 'Title for the Demo application',
    );
  }
}

Future<Null> main() async {
  final Locale myLocale = Locale(Platform.localeName);
  await Strings.load(myLocale);
  runApp(MyApplication());
}
```
Now you can reference a string as follows:
`final title = Strings.current.title`

**Comment by JannieT** [comment]
@knex Thanks! Very clever!  Not sure how you implemented initializeMessages, but this method seems to bypass the use of a LocalizationsDelegate which then makes it difficult to manage which locales are allowed and when to reload etc. But very useful method to have in the tool belt.

**Comment by ayushin** [comment]
Here's another option to do it via flutter i18n plugin for IntelliJ

https://github.com/long1eu/flutter_i18n/pull/50

**Comment by itelixgithub** [comment]
@kinex could you, please give us a hint how you implemented initializeMessages ?
I'm also struggling with context-problem. Thank you in advance!

**Comment by ayushin** [comment]
If you build the latest flutter-i18n plugin from source you’d be able to use S.current.YourMessage everywhere in the project after importing import 'generated/i18n.dart';

Is that what you are asking?

Alex

**Comment by itelixgithub** [comment]
@ayushin yeah something like that. Will definitely check the plugin today, thanks! Context-less solution should by provided and documented by Flutter Team...

**Comment by ayushin** [comment]
Well, honestly in the end we had to share the context statically/globally anyway in order to be able to implement global error handling/messages. So then you could also use it for the internalisation.

One way or another you end up sharing the context (or the messages) via a static property of a class…

If you can find a more elegant solution - I’d be glad to hear about it

Alex

**Comment by tbvh** [comment]
If you follow the `Intl` example, it is already depending on a static property (i.e. `Intl.defaultLocale`) from the start.

So why do you need the ceremony of `DemoLocalizations.of(context).[..]` when the locale of Intl is global anyway? 

If I understand this correctlty, it makes not difference to call the methods that wrap `Intl.message` directly (such as `DemoLocalizations.title()`). And those methods can be static themselves, and you can even put them wherever you want (in the widget where they are used).

You only still need a LocalizationsDelegate (subtype) to listen to the load method to load the correct locale.

Am I seeing this correctly?

**Comment by KingWu** [comment]
A new approach of localization in Flutter

Wrote two plug-ins to simplify the process of localization

1. Prepare all strings in Airtable
2. Run lang_table to generate json files
3. Run gen_lang to generate i18n.dart and message_all.dart
4. Use i18n.dart for localization in coding

https://medium.com/@kingwu/a-new-approach-of-localization-in-flutter-e18bfb2b14ab

**Comment by parth22** [comment]
> @kinex can you give an example/gist of how you can get to the translated string without using any context? I think this will help many people, like me and [others](https://stackoverflow.com/questions/51803755/getting-buildcontext-in-flutter-for-localization) for which this is a major issue.



> If you are using IntelliJ (Android Studio), you can use the [Flutter i18n](https://github.com/long1eu/flutter_i18n) plugin.

can you guide me how to use this plugin in android studio version 3.4.0 because i got this error in my studio.
![image](https://user-images.githubusercontent.com/13308845/60179357-27383c00-983b-11e9-958b-b6bbd42cd7a6.png)

**Comment by ayushin** [comment]
Yes it looks like it needs to be ported to the newer IntelliJ but the original authors seem to be quite passive... any takers?
