### ISSUE TITLE
Flutter Web squeezed Text, worspacing not working, on some in app browsers (instagram, facebook)

### ISSUE THREAD

**Issue by guihackmann** [flutter/flutter#145140]
In Flutter Web apps, words get scrambled, with negative spaces between them, when running from an in-app browser, such as facebook and instagram browsers, from some android devices.

I`ve been living with this issue for over a year, and a good portion of my users complain about this. However, this problem is not easy to reproduce, as it only happens if all conditions below are met:

### Steps to reproduce

1) The web app has to be on HTLM renderer
2) Happens on many Android devices, but I can`t precise which ones - usually when the font size of the phone is at medium or higher
3) The link to the flutter web has to be opened in an in app browser (such as facebook, instagram or even in a webview of a flutter app itself)

I tested adding a high number for "wordspacing" in text widget, and it only adds spaces for normal browsers. For in-app browsers, wordspacing doesn`t seem to work at all.

### Expected results

Expeted result - the way it looks on a normal browser (Safari, Chrome)
![image](https://github.com/flutter/flutter/assets/62712660/4b74f2b4-02c1-4a59-a0ad-bfc18bda752e)

### Actual results

Actual result, when accessing the link on an in-app browser
![image](https://github.com/flutter/flutter/assets/62712660/d32d48ed-9557-4f60-a67e-028f40025657)

**Comment by darshankawar** [comment]
@guihackmann 
Can you provide `flutter doctor -v` and runnable reproducible code sample that shows the reported behavior ?
Also, device details that would be helpful.

**Comment by richardloxley** [comment]
I'm seeing the same problem reported by users.  As already reported: Flutter HTML renderer, only when viewed within the in-app browser on the Android Facebook app.

From the screenshots they've sent it looks like the browser is increasing the font size beyond that specified in the Flutter code, but each "chunk" of text (mostly each word it seems) is placed on the screen where it should be if the text was the correct size.  So it looks like the browser is overriding the font size but not the spacing.

Two examples from different users (grey boxes to hide my client's branding):

![1](https://github.com/flutter/flutter/assets/4620670/dbabd4cb-3458-49f3-8b59-97c8317a91e0)

![2](https://github.com/flutter/flutter/assets/4620670/f660160d-3e41-48de-a740-2be95fa8ff13)

My Flutter doctor output:

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-GB)
    • Flutter version 3.19.2 on channel stable at /Users/Richard/Projects/Third Party/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (3 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/Richard/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.59
    ! Error: Browsing on the local area network for Richard iPhone 14 Pro. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Richard iPad Pro. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

I can't yet provide a runnable reproducible code sample as I don't currently have access to an Android device to test on.  If I manage to get hold of one I'll see what I can do.
