### ISSUE TITLE
Provide call to close/abort native picker file explorer

### ISSUE THREAD

**Issue by jakusb** [flutter/flutter#145150]
### Use case

When Using ImagePicker in Web on a MacOS or Windows, it will launch the Gallery in the form of a file explorer
Normally one would select the intended image and clicks the 'Open' button.
Alternatively one could drag the image onto the ImagePicker widget to drag/drop the image. 
When this is done, the file explorer remains active. Not a problem, but would be nice to programmatically close the File Explorer window. Or to programmatically abort the ImagePicker action.

### Proposal

Add a call to complete/cancel or abort the action, so the File Explorer that is shown natively is closed.

**Comment by stuartmorgan** [comment]
> Alternatively one could drag the image onto the ImagePicker widget to drag/drop the image.

What widget are you referring to here?

> Add a call to complete/cancel or abort the action, so the File Explorer that is shown natively is closed.

I'm not clear from the description above of the use case what the goal here is. You want to be able to close the UI out from under the user while they are still interacting with it? What's the use case where this would be desirable?

**Comment by jakusb** [comment]
Code triggered onTap of widget:

                        final ImagePicker picker = ImagePicker();
                        final XFile? xFileImage = await picker.pickImage(source: ImageSource.gallery);

See attached video of use in Safari browser on MacOs
https://github.com/flutter/flutter/assets/9477833/2f2dca23-2303-4578-87c1-64caf150bb38

**Comment by huycozy** [comment]
@jakusb I think this is out of the plugin's scope as the native picker belongs to the system side. Please refer to this SO's answer. If you see an official API on web that supports this, please share it here. Thanks!
