### ISSUE TITLE
[CP] Revert stencil buffer record/replay.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#145184]
### Issue Link

https://github.com/flutter/flutter/issues/144211

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/51416

### Changelog Description

Reverts a clipping optimization that is broken when multiple clips are applied with a backdrop filter.

### Impacted Users

End customers using applications that have a backdrop filter and more than one clip.

### Impact Description

Rendering is incorrect.

### Workaround

Not really.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the added test.

**Comment by XilaiZhang** [comment]
would @zanderso be able to help evaluate this cherry pick request? thank you!

**Comment by zanderso** [comment]
revert cp lgtm
