### ISSUE TITLE
[CP] Prepare iOS device for build+test recipe

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#145115]
### Issue Link

https://github.com/flutter/flutter/issues/142917

### Target

stable

### PR Link

https://flutter-review.googlesource.com/c/recipes/+/56100

### Changelog Description

Fixes an infrastructure issue that prepares the iOS device for testing before running Mac_build_test tests.

### Impacted Users

Flutter Release Team

### Impact Description

Currently no impact since stable runs on iOS 16. This is added in preparation of allowing stable to use iOS 17 devices. Once iOS 17 devices are added, Mac_build_test test will fail when ran on an iOS 17 device without this fix.

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by XilaiZhang** [comment]
@Jasguerrero was this rolled in during last week's release?

**Comment by Jasguerrero** [comment]
This is a recipe change and it has already merged, last week we didn't have any non recipe CP/new dart hash

**Comment by XilaiZhang** [comment]
If I am understanding correctly, these ~5 recipe changes have merged onto release branches, but haven't been shipped out (therefore not been tested) through a release?

**Comment by Jasguerrero** [comment]
No, we haven't run a release on them yet
