### ISSUE TITLE
How to monitor incoming calls and alarm clock ringing?

### ISSUE THREAD

**Issue by giantss** [flutter/flutter#145193]
### Use case

Our project is an audio project, and there is a requirement that when a phone call comes in or the alarm clock rings, the audio being played in our app needs to be paused. I checked some information and found that some developers use `WidgetsBindingObserver ` `void didChangeAppLifecycleState` to monitor the life cycle. However, I have tested several models of iOS (iphone 15pro) android xiaomi 13, etc., and it will not trigger when a call comes in or the alarm clock rings. `AppLifecycleState.inactive` state.

### Proposal

My current flutter version is `v3.10.5`
I wonder if Flutter provides a more effective API to achieve the functions I want?

**Comment by darshankawar** [comment]
@giantss 
There are few community packages that you can try, one such is https://pub.dev/packages/phone_state and see if it helps to serve your case or not. You may check for similar package for alarm clock.

Also, This question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
