### ISSUE TITLE
Sanctions of Flutter on Iraninan Programmers

### ISSUE THREAD

**Issue by Rashcodeacademy** [flutter/flutter#145169]
Dear Google and Flutter Team,

We Iranian programmers deeply resent our government and its administration and strive hard to find a way to connect with the global community and make the world into a better place to live. However, we are severely censored under our government's censorship, facing slow internet speeds and lack of access to many popular websites. Nevertheless, it is disheartening to see that not only does our oppressive government censor us, but Google and Flutter have also imposed sanctions on us. Considering that government officials and friends can bypass Google's sanctions, and in this process, only true lovers of Google suffer, and those who love working for Google are deprived of their dream, please lift at least the sanctions on Iranian users regarding Flutter. 

Best regards, 

One of the lovers of Flutter and programming.

**Comment by iapicca** [comment]
> Google and Flutter have also imposed sanctions on us.

what sanctions?

**Comment by stuartmorgan** [comment]
> Flutter have also imposed sanctions on us

It is not clear from the report what exactly this is referring to; closing per https://github.com/flutter/flutter/wiki/Issue-hygiene#every-issue-should-be-actionable

If there are technical issues with using Flutter, please file a new issue with specific details, reproduction steps, and any relevant log messages.

**Comment by stuartmorgan** [comment]
> Dear Google and Flutter Team

Note for any future issues on this topic: this issue system is for Flutter, not Google. There is no way to communicate with "Google" via this issue tracker, only the Flutter team, so if you have concerns that are about Google more broadly you would need to find another feedback mechanism for that.

**Comment by moffatman** [comment]
Probably various blobs needed e.g. engine, fonts, tools are hosted on some google storage bucket which is blocked. Not sure if the instructions for China may be usable in Iran? https://docs.flutter.dev/community/china
