### ISSUE TITLE
Please set FLUTTER_FRAMEWORK_DIR to the directory containing Flutter.framework

### ISSUE THREAD

**Issue by peace2knowledge** [flutter/flutter#14516]
I want install dependency, ie: pod “BaiduMapKit” #百度地图SDK
show me the some error:
```
Please set FLUTTER_FRAMEWORK_DIR to the directory containing Flutter.framework

[!] Invalid `Podfile` file: Please set FLUTTER_FRAMEWORK_DIR to the directory containing Flutter.framework.

 #  from /Users/xxx/Desktop/code/xxx/ios/Podfile:5
 #  -------------------------------------------
 #  if ENV['FLUTTER_FRAMEWORK_DIR'] == nil
 >    abort('Please set FLUTTER_FRAMEWORK_DIR to the directory containing Flutter.framework')
 #  end
 #  -------------------------------------------

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
```
NEXT is my Podfile
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

if ENV['FLUTTER_FRAMEWORK_DIR'] == nil
  abort('Please set FLUTTER_FRAMEWORK_DIR to the directory containing Flutter.framework')
end

target 'Runner' do
  # Pods for Runner
  pod “BaiduMapKit” #百度地图SDK
  # Flutter Pods
  pod 'Flutter', :path => ENV['FLUTTER_FRAMEWORK_DIR']

  if File.exists? '../.flutter-plugins'
    flutter_root = File.expand_path('..')
    File.foreach('../.flutter-plugins') { |line|
      plugin = line.split(pattern='=')
      if plugin.length == 2
        name = plugin[0].strip()
        path = plugin[1].strip()
        resolved_path = File.expand_path("#{path}/ios", flutter_root)
        pod name, :path => resolved_path
      else
        puts "Invalid plugin specification: #{line}"
      end
    }
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by hdev0301** [comment]
- In bash_profile,
export FLUTTER_FRAMEWORK_DIR=<Flutter_To_Path>/flutter/bin/cache/artifacts/engine/ios
- source ~/.bash_profile
- In iOS folder,
pod install

**Comment by Hixie** [comment]
The error message seems to be pretty clear about what should be done here. I'm not really sure what we could do to improve this.

**Comment by Hixie** [comment]
cc @cbracken

**Comment by hdev0301** [comment]
OK, tell me what the issue is.

**Comment by mravn-google** [comment]
Please check the file `ios/Flutter/Generated.xcconfig`, generated by Flutter tooling when you do `flutter packages get`. That should define the property.

**Comment by peace2knowledge** [comment]
```
// This is a generated file; do not edit or check into version control.

FLUTTER_ROOT=/Users/mazilong/Desktop/code/flutter

FLUTTER_APPLICATION_PATH=/Users/mazilong/Desktop/code/xlzhaopin

FLUTTER_TARGET=/Users/mazilong/Desktop/code/xlzhaopin/lib/main.dart

FLUTTER_BUILD_MODE=debug

FLUTTER_BUILD_DIR=build

SYMROOT=${SOURCE_ROOT}/../build/ios

FLUTTER_FRAMEWORK_DIR=/Users/mazilong/Desktop/code/flutter/bin/cache/artifacts/engine/ios

```

**Comment by mravn-google** [comment]
@peace2knowledge OK, that looks correct. We need more details on your setup and steps then, including which version of Flutter you are using. Please include the output of `flutter doctor -v`.

I have attempted to reproduce the error following the steps below:
* `flutter create my_project`
* Add a Flutter plugin dependency to `my_project/pubspec.yaml`, arbitrarily choosing `path_provider`:
  ```yaml
  dependencies:
    path_provider:
    flutter:
      sdk: flutter
  ```
* Copy your `Podfile` from above into `my_project/ios/Podfile`
* `open -a Simulator`
* `flutter run`

This works fine. I get:
```
$ flutter run
Running "flutter packages get" in my_project...              0.8s
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                       1.7s
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    1.3s
 └─Compiling, linking and signing...                  5.7s
Xcode build done.                                            9.1s
Syncing files to device iPhone X...                          2.0s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
```
For reference, here is the output of `flutter doctor -v` on my system:
```
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.4.4 at /Users/mravn/github/flutter
    • Framework revision f9bb4289e9 (5 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Android NDK at /Users/mravn/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • iPhone X • FFA4A1BA-1F0C-4CAD-98CC-8C78178EA218 • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by peace2knowledge** [comment]
ok，this problem happen in four mouth ago, new project work well, Tanks @mravn-google

**Comment by mortenboye** [comment]
I'm currently experiencing the same, but the workaround from hdev0301 (Mar. 3rd) fixed it for me. 
This is my flutter doctor -v:

[✓] Flutter (Channel master, v0.5.5-pre.24, on Mac OS X 10.13.5 17F77, locale en-DK)
    • Flutter version 0.5.5-pre.24 at /Users/morten/Developer/flutter
    • Framework revision 020e0ef55c (14 hours ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/morten/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 5.1.1 (API 22) (emulator)
    • iPhone                    • f6ff499e93b18b2df8abc10992050193e4dd401d • ios         • iOS 11.3

! Doctor found issues in 1 category.

(I'm not using VSCode)
