### ISSUE TITLE
Display over other apps

### ISSUE THREAD

**Issue by WhiteDevil8821** [flutter/flutter#145207]
### Use case

We are developing an application in which we wanted to keep our app alive if it satisfy a certain condition.

### Proposal

Please provide a feature so that we can resolve this for ios/android app that if my specified condition is satisfied and the app goes in the background then it automatically become a small round popup on the screen which will keep the app running in background.

**Comment by darshankawar** [comment]
@WhiteDevil8821 
There are community packages that should help to resolve your case.

https://pub.dev/packages/flutter_overlay_apps
https://pub.dev/packages/flutter_overlay_window

Closing the issue.
