### ISSUE TITLE
I'm confuse after read https://futter.cn/docs/get-started/install, Why is there no unified dependency installation tool?

### ISSUE THREAD

**Issue by bmmpp** [flutter/flutter#145212]
### Steps to reproduce

refer to https://flutter.cn/docs/get-started/install, I'm confused. The cross-platform nature of flutter is very attractive to developers, but different platforms need to install different softwarelibraries, the flutter team recommends Visual Studio Code, but to develop windows programs, you must install Visual Studio 2022and to develop Android, you must install Android Studio
And the various dependency libraries, why the flutter extension can't mask these details.

### Actual results

We expect to have scaffolding or a plugin on any development tool to install these dependencies, which can be very complex, butthis will greatly reduce the time it takes to get started and eliminate the need for new installations
For example, on the Java platform, intellil idea is very popular. lf there is a plug-in that is directly installed in lntelli idea, you onlyneed to follow the steps ot the plug-in to complete the installation and settings, and you can develop Windows, macmobel andother platforms. program, it will be very friendly
I think most people are not willing to install too many dependencies manually,thanks !

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@bmmpp 
You'll need to report this in dedicated [repo](https://github.com/cfug/flutter.cn/issues/new?template=1_page_issue.yml&title=[%E9%A1%B5%E9%9D%A2%E9%97%AE%E9%A2%98]%20%27%E9%80%89%E6%8B%A9%E4%BD%A0%E7%9A%84%E5%BC%80%E5%8F%91%E5%B9%B3%E5%8F%B0%EF%BC%8C%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8%27&page-url=https://flutter.cn/docs/get-started/install/&page-source=https://github.com/cfug/flutter.cn/tree/main/src/get-started/install/index.md).

Closing from here, as this is related to flutter.cn website
