### ISSUE TITLE
BackDrop filter does not work Above google maps, on Web

### ISSUE THREAD

**Issue by PauloAlves311** [flutter/flutter#145218]
### Steps to reproduce

Using google_maps_flutter and BackDropFilter does not seem to blur on web, even though it works on ios and android.

On Web, the container does not blur the map:

Code:

```
Stack(children: [
GoogleMap(),
BackdropFilter( 
filter:ui.ImageFilter.blur(sigmaX: 6.0, sigmaY: 6.0),
child: Container(color: Colors.purple, width: 300)
)])
```

On Web, the container does not blur the map:
![filter](https://github.com/flutter/flutter/assets/40123939/f2963c34-12a4-4499-ad5e-a157bc8b4504)

On Android it does:
![filterAndroid](https://github.com/flutter/flutter/assets/40123939/2224ef2e-5b43-43d0-9ebf-9457582b3056)

**Comment by zopagaduanjr** [comment]
Should not be a Flutter issue. If your goal is to blur the map on both mobile and web, you can just remove the width value of your purple container so that the container will fit to the flutter app width.

```
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            const GoogleMap(initialCameraPosition: _kGooglePlex),
            BackdropFilter(
              filter: ui.ImageFilter.blur(sigmaX: 1, sigmaY: 1),
              child: Container(
                color: Colors.purple.withOpacity(0.2),
              ),
            ),
          ],
        ),
      ),
    );
```

**Comment by huycozy** [comment]
Thanks for the report! This is an underlying issue with platform views. And there is a known issue being tracked at https://github.com/flutter/flutter/issues/143747. Closing this issue as a duplicate, so please follow up on it for further updates.
