### ISSUE TITLE
AutomaticKeepAliveClientMixin.build registers keep alive but does not unregister

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#145291]
For some reason I assumed that calling `super.build()` with `AutomaticKeepAliveClientMixin` was enough to register and unregister keep alive, but it seems that for some reason it only registers the keep alive and does not unregister it:

https://github.com/flutter/flutter/blob/7c860ddf970575d4ca6dd0ccc4bd823613a16359/packages/flutter/lib/src/widgets/automatic_keep_alive.dart#L398-L406

This will never call `_releaseKeepAlive()`, in order to do that, an additional call to `updateKeepAlive()` is required, i.e.

```dart
class MyState extends State with with AutomaticKeepAliveClientMixin {

 @override
  bool get wantKeepAlive => _focusNode.hasFocus;

  @override
  Widget build(BuildContext context) {
    super.build(context); // This is required when when adding AutomaticKeepAliveClientMixin
    updateKeepAlive(); // Additionally this is necessary to unregister keep alive.
  }
}
```

Is this intended behavior? Seems like a bit of oversight. If we enforce `super.build()` call to update keep alive status, shouldn't that also unregister the keep alive?

**Comment by knopp** [comment]
@Hixie, the keep alive code seems to go way back, any insight of this?

**Comment by Hixie** [comment]
Per the documentation <https://main-api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html>:

> Then, whenever wantKeepAlive's value changes (or might change), the subclass should call updateKeepAlive.

**Comment by Hixie** [comment]
(Specifically, IIRC, one goal is that keepalive should be able to change without triggering a rebuild.)

**Comment by knopp** [comment]
That makes sense. Thanks.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/145297/files
