### ISSUE TITLE
After update to Flutter 0.0.23 

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#14524]
## Steps to Reproduce
```
 (add_tests) $ flutter run --release -d HT69V0203649
Initializing gradle...                                0.9s
Resolving dependencies...                             1.1s
Launching lib/main.dart on Pixel XL in release mode...
Running 'gradlew assembleRelease'...                      
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Cannot locate the genSnapshot executable

FAILURE: Build failed with an exception.

* Where:
Script '/Users/zoechi/flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 388

* What went wrong:
Execution failed for task ':app:flutterDependenciesRelease'.
> Process 'command '/Users/zoechi/flutter/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Gradle build failed: 1
```

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-AT, channel dev)
    • Flutter version 0.0.23 at /Users/zoechi/flutter/flutter
    • Framework revision 14309b9311 (21 hours ago), 2018-02-06 13:24:16 -0800
    • Engine revision 9bc2efdf47
    • Tools Dart version 2.0.0-dev.19.0
    • Engine Dart version 2.0.0-edge.ea91bc9888184d5a2fc309c36656fdd325ef503c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices
    • Pixel XL                  • HT69V0203649  • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.0.0 (API 26) (emulator)

• No issues found!

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by jason-simmons** [comment]
We haven't yet landed the tools for building 64-bit APKs on Mac or Windows.

For now, you can work around this by building a 32-bit APK with `flutter build apk` and then installing it manually.

**Comment by zoechi** [comment]
@jason-simmons why did the same command work with 0.0.23?

**Comment by jason-simmons** [comment]
We recently added initial work toward building APKs for Android ARM64 platforms.  Prior to this, all Android APKs built with Flutter were 32-bit.

`flutter run` is failing in your setup because it detects that the attached Android device is 64-bit, but it can't find the tools for building a 64-bit APK.

**Comment by zoechi** [comment]
Does this apply when I debug from IntelliJ?

Since this update, when I debug on the emulator all still works fine, but when I debug on my Pixel XL the app just crashes without any debug output about the crash (only a dialog on the phone noticing the app crashed)

**Comment by jason-simmons** [comment]
Yes - you will need to build the app as 32-bit when running on a Pixel until we roll out a Flutter engine that includes the necessary Dart VM fix.  (That's in progress now: https://github.com/flutter/flutter/pull/14538)

**Comment by zoechi** [comment]
Updating to
```
Flutter 0.1.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision ab4506cad2 (2 days ago) • 2018-02-09 12:21:43 -0800
Engine • revision 337764e4ed
Tools • Dart 2.0.0-dev.22.0
```
fixed it for me on my Pixel XL
