### ISSUE TITLE
It's hard to debug why a Skia Gold diff wasn't surfaced in pre-submit

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#145219]
There are a few possibilities to why `flutter/engine` post-submit is still broken by changes that should have come up in pre:

1. This is garden-variety flakiness, and is being misattributed to pull requests

   **UNLIKELY**: In the failure in question, there was a both a clear, and intentional change in digest output.

    <details>
        <summary>Click to expand details</summary>

    ![image](https://github.com/flutter/flutter/assets/168174/24ec693d-098e-4463-b5f2-eec4c332ffd9)

    ![image](https://github.com/flutter/flutter/assets/168174/2ce04c93-b488-48b1-9f75-515d77060866)

    ... to:
    
    ![image](https://github.com/flutter/flutter/assets/168174/0c449c69-39c2-4fb5-9af8-1fb5f65d6130)

    </details>

    TODO: _Nothing_. I can't see any work to be done here.

2. The test runner (in this case `scenario_app`) is not uploading the images properly or timely to Skia Gold

    **POSSIBLE, LEANING UNLIKELY**: There is fairly [extensive logging](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2125019/overview) proving the output of the runner.

    It _is_ possible that despite generating the image, the actual _upload_ is either failing, or not completing in time.

    TODO:
    - [x] Add more logging to `scenario_app` verifying that `addImg` calls are succeeding and uploading the image (done: https://github.com/flutter/engine/pull/51454).
    - [x] Modify `<SkiaGoldClient>.addImg` to report if "Untriaged image" is coming up in pre-submit (log only, no failure) (done: https://github.com/flutter/engine/pull/51455).

3. The client wrapper that uploads/tests codes in pre-submit unintentionally has diverged from post-submit or flutter/flutter

    **POSSIBLE**: I need to better understand the command-line arguments to `gold_ctl`.

    `flutter/engine` has a [fork of `SkiaGoldClient`](https://github.com/flutter/engine/blob/76f33eb0ecedee4182215923e5e3942a5dfbfcc2/testing/skia_gold_client/lib/skia_gold_client.dart#L247-L261), and our implementation is different than the [one in `flutter/flutter`](https://github.com/flutter/flutter/blob/master/packages/flutter_goldens/lib/skia_client.dart).

    It's possible that either support improved (but was not improved in our forked copy), mistakes were made etc.

    TODO:
    - [ ] Review and document the command-line arguments to `gold_ctl`
    - [ ] Review the implementation details of the `flutter/flutter` copy and `flutter/engine` fork and look for discrepancies

4. `✅  Flutter Gold` (the GitHub check) is either misbehaving (has a bug), or the server API result is stale/not fresh enough

    **POSSIBLE**: I know very little about this API or the integration.

    TODO:
    - [ ] Add logging for the "Flutter Gold" check that sticks around in the commit history/is more easily audit-able.

## Background

In the [latest example](https://flutter-engine-gold.skia.org/detail?grouping=name%3DExternalTextureTests_testCroppedRotatedMediaSurface_bottomLeft_90%26source_type%3Dflutter-engine&digest=1454761e1d7238019d9207192121ff2c), the `flutter/engine` tree turned 🔴 due to an untriaged golden file:

![image](https://github.com/flutter/flutter/assets/168174/912fe284-3891-4d39-a32a-3ff9351936e5)

The particular rendering issue (see below) is due to [YUV textures mis-rendering on Android emulators](https://github.com/flutter/flutter/issues/144838):

![image](https://github.com/flutter/flutter/assets/168174/c58fa908-f67a-4e4b-a213-194c131c3fe8)

In the [originating pull request](https://github.com/flutter/engine/pull/51433), all tests (including the "Flutter Gold") check were 🟢 . In fact, if you pull up the [execution logs](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2125019/overview), you'll see that the particular test (`testCroppedRotatedMediaSurface_bottomLeft` on Impeller/Vulkan) produced the image above, and should have triggered an untriaged digest:

![image](https://github.com/flutter/flutter/assets/168174/89ca6682-aa20-445c-a7f5-295d17c4c35f)

<details>

<summary>Full Image</summary>

![image](https://github.com/flutter/flutter/assets/168174/a9330224-a595-4685-98a9-de7644732cc0)

</details>

/cc @dnfield @jonahwilliams

**Comment by matanlurey** [comment]
Some notes from meeting with @mdebbar and @jonahwilliams:

- The fact there is `PS1 PS1 PS2 PS2` is not expected. You might see this pattern with rebase/force-push, but should not:

    ![Screenshot 2024-03-15 at 11 29 29 AM](https://github.com/flutter/flutter/assets/168174/d826abd4-f2a5-4102-901c-3dbac58d9f86)

    We looked at a [random other PR in `flutter/engine`](https://flutter-engine-gold.skia.org/search?issue=51334&crs=github&patchsets=11) and see similar duplicate uploading. I also see _some_ of these [in `flutter/flutter`](https://flutter-gold.skia.org/search?issue=141373&crs=github&patchsets=11) but a little less.

    AI: Might ask Kevin why a second patch-set was created, we didn't force-push/rebase.
    AI: Check other PRs that do similar things and see how many patch-sets are created (i.e. revert the PR).

- Not sure when the last time we updated `gold_ctl.py`; maybe we're using an old client?
- Some [documentation of flags](https://github.com/google/skia-buildbot/blob/main/gold-client/cmd/goldctl/cmd_imgtest.go#L142) are here.

**Comment by Piinks** [comment]
Existing logs for the flutter-gold check can be seen at this (internal only) [link](https://pantheon.corp.google.com/logs/query;query=SEARCH%2528%22%60push-gold%60%22%2529;cursorTimestamp=2024-03-18T19:57:18.007Z?project=flutter-dashboard).

They come from flutter/cocoon, so we can easily add more infos to the logs if needed.

**Comment by matanlurey** [comment]
Some mitigations were landed, so reducing to P2.

**Comment by matanlurey** [comment]
Closing as I don't intend to spend more time on this class of problem and there is nothing actionable to do.
