### ISSUE TITLE
iframe navigation on Android gets handled by main frame with `NavigationDecision.navigate`

### ISSUE THREAD

**Issue by petermnt** [flutter/flutter#145208]
### What package does this bug report belong to?

webview_flutter

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      sha256: "3e5f4e9d818086b0d01a66fb1ff9cc72ab0cc58c71980e3d3661c5685ea0efb0"
      url: "https://pub.dev"
    source: hosted
    version: "3.15.0"
```

</details>

### Steps to reproduce

1. Add `NavigationDeletage.onNavigationRequest` to the `Webview`
2. Go to a site which has an iframe that executes `data:text/html,<script>onresize=function(){parent.postMessage(0,'*')}<\/script>`

### Expected results

Iframe is allowed to load that content

### Actual results

The main frame loads this content, causing a white page.

**Comment by Aulig** [comment]
Experiencing this too. You can very easily reproduce it by executing this javascript, which leads to opening the iframe src in the main frame:

const iframe = document.createElement("IFRAME");
iframe.src = "data:text/html,%3Cdiv%20style%3D%22width%3A%20100%25%3Bheight%3A200px%3B%22%3E%3C%2Fdiv%3E";
document.body.appendChild(iframe);

**Comment by bparrishMines** [comment]
Fixed by https://github.com/flutter/packages/pull/6335
