### ISSUE TITLE
[Android] App has a black screen after being left in background

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#145289]
### Steps to reproduce

It appears you need Android 14 (e.g Samsung S22 Ultra), can not appear to repeat on Android 12. Haven't checked recently but probably okay on Android 13 as well... Have never seen on issue on iOS.

Have been able to repeat it with our Apps on stable 3.19.3 (and prior versions in 3.x) and the latest Google Earth and Wonderous apps.

1. Open your Flutter App
2. Change to another app or two
3. Turn off screen
4. Leave for 5 minutes
5. Turn on screen and try to select the App

### Expected results

App should show as normal and not as a Black screen. When you select the App twice it will open.

### Actual results

Screen is blank, until I select the App twice. Also can see flicker sometimes when looking at the list of open Apps.

### Code sample

This should be a simple repo: https://github.com/flutter/flutter/issues/143992

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

This is Google Earth, Wonderous and one our Flutter Apps all showing the Black screen
![telegram-cloud-photo-size-4-6032671559308656465-y](https://github.com/flutter/flutter/assets/81489824/b98d79a9-8b89-47f5-ba87-b74a20ca7c1f)

![telegram-cloud-photo-size-4-6032671559308656466-y](https://github.com/flutter/flutter/assets/81489824/14a65236-40fc-4db6-aa8d-ba79929859f0)

![telegram-cloud-photo-size-4-6032671559308656467-y](https://github.com/flutter/flutter/assets/81489824/65a1766f-ce7b-4826-a27e-1c0c34cf804d)

This is what I get when I select the App
![telegram-cloud-photo-size-4-6032671559308656468-y](https://github.com/flutter/flutter/assets/81489824/d4864c7c-ad0d-4fbf-baa9-ee4d4aa437f2)

![telegram-cloud-photo-size-4-6032671559308656469-y](https://github.com/flutter/flutter/assets/81489824/b6d5cd9d-e493-400d-8ae0-598c5953e31b)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.19.3 on channel stable at /users/omega/flutter
    ! Warning: `flutter` on your path resolves to /Users/omega/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /users/omega/flutter. Consider adding
      /users/omega/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/omega/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /users/omega/flutter. Consider adding
      /users/omega/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (2 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/omega/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (4th generation) (mobile) • F970649B-BBDA-4185-96C3-7274D42ED07D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report, @zambetpentru. I think you are hitting https://github.com/flutter/flutter/issues/139630 which pointed out the issue also occurs on Samsung device and Android 14. 

I will close this issue in favor of that one. So please follow up on it for updates.

**Comment by zambetpentru** [comment]
Looks like it thanks!
