### ISSUE TITLE
CustomPaint with large line coordinates incorrectly fills rather than strokes.

### ISSUE THREAD

**Issue by dantechguy** [flutter/flutter#145229]
### Steps to reproduce

See dartpad: https://dartpad.dev/?id=6f8912a9e4ad3c654a7a99a9960259de

### Expected results

It should just draw a couple lines. There are only stroke canvas commands there, and no fill commands. If you replace the `moveTo` coordinates to something smaller, then the bug goes away.

### Actual results

A large portion of the screen is filled.

### Code sample

<details open><summary>Code sample</summary>

```dart
final path = Path();
path.moveTo(-10000000, -75000);
path.lineTo(0, 0);
path.lineTo(10, 10);
path.close();
final paint = Paint()..color = Color(0xFFff0000)
  ..style = PaintingStyle.stroke
  ..strokeWidth = 2.0;
canvas.drawPath(path, paint); 
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="2056" alt="image" src="https://github.com/flutter/flutter/assets/30006489/add8957a-0421-40c5-abea-3f623f4ef3bd">

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale nb-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    ! CocoaPods 1.11.2 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.1)
[✓] VS Code (version 1.87.1)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for d4. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for d5. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by MuhammedOzdogan** [comment]
canvas.translate(size.width/2, size.height/2);
      canvas.clipRect(Rect.fromCenter(center: Offset.zero, width: size.width, height: size.height));
  
Above 2 lines looks suspicious to me, why do you need to clip it.

**Comment by dantechguy** [comment]
@MuhammedOzdogan The first to centre the drawing, the second to ensure you don't paint outside the CustomPaint boundary. I don't think they're the issue as if you replace them with just

```dart
canvas.clipRect(Rect.fromLTRB(0, 0, size.width, size.height));
```

then the issue is still present as you can see here: https://dartpad.dev/?id=f9747e80ec41f7eb755e7a3f9e93f579

**Comment by MuhammedOzdogan** [comment]
Here is a sample about drawing Path:
I only use `moveTo` method to specify starting point, or when I want to draw a new different path.

```dart
  void _drawLine(Canvas canvas, List<Offset> points) {
    final paint = Paint()
      ..color = Color(0xFFff0000)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 8.0;
    final path = Path();
    path.moveTo(points.first.dx, points.first.dy);
    for (var i = 1; i < points.length; i++) {
      path.lineTo(points[i].dx, points[i].dy);
    }
    canvas.drawPath(path, paint);
  }
```

https://dartpad.dev/?id=66311acd249e770fa6b39c4868332103

**Comment by darshankawar** [comment]
@dantechguy 
Check above and see if it helps in your case or not.

**Comment by dantechguy** [comment]
Hi @MuhammedOzdogan thanks for the response and I understand what you are saying. 

The way this came up was that I'm building a 3D renderer which renders by drawing whole triangles at a time. If a triangle lies outside of the camera's view frustum and it lies very close to the camera plane, its projection ends up with very large coordinates (as above). I had assumed that by using a `.clipRect` this would be okay, as it abides by the ["do not draw outside the canvas' bounds"](https://api.flutter.dev/flutter/widgets/CustomPaint-class.html#:~:text=(If%20the%20painters%20paint%20outside%20those%20bounds%2C%20there%20might%20be%20insufficient%20memory%20allocated%20to%20rasterize%20the%20painting%20commands%20and%20the%20resulting%20behavior%20is%20undefined.)%20To%20enforce%20painting%20within%20those%20bounds%2C%20consider%20wrapping%20this%20CustomPaint%20with%20a%20ClipRect%20widget.)

I have since then fixed the issue, but the reason I created this gh issue was that I thought this behaviour didn't make sense and was a bug. If this behaviour is as intended (as in, if you draw a line from super large coordinates then it fills a portion of the canvas instead), then perhaps the following would be helpful for future users?
- When building in debug mode, if this occurs, notify the user with a warning or error. Perhaps an `assert`ion can be used. I'm afraid I don't know the exact reproduction conditions though. My guess would be it's something complicated with the underlying skia/impeller rendering engine.
- On the `CustomPaint` / `Canvas` docs, explain this behaviour, or at least that the user shouldn't draw far out of the canvas, even while using a `clipRect` (as its suggested method to fix this).

**Comment by darshankawar** [comment]
> have since then fixed the issue, but the reason I created this gh issue was that I thought this behaviour didn't make sense and was a bug. If this behaviour is as intended (as in, if you draw a line from super large coordinates then it fills a portion of the canvas instead), then perhaps the following would be helpful for future users?
> 
> * When building in debug mode, if this occurs, notify the user with a warning or error. Perhaps an `assert`ion can be used. I'm afraid I don't know the exact reproduction conditions though. My guess would be it's something complicated with the underlying skia/impeller rendering engine.
> * On the `CustomPaint` / `Canvas` docs, explain this behaviour, or at least that the user shouldn't draw far out of the canvas, even while using a `clipRect` (as its suggested method to fix this).

Thanks for the update @dantechguy 
Since the original issue you reported has been resolved per your comment, for above findings you observed, I suggest you to file a new issue with relevant details so that we can address it properly and can be tracked separately.

I'll close this issue as solved per your comment. If you disagree, write in comments and I'll reopen it.

**Comment by dantechguy** [comment]
Hi @darshankawar, thanks for your reply. I'm a little confused - the point of this issue was to report the bug, so surely we should re-open this issue rather than having me make a new issue?

Or have I done something wrong here in the process of making this issue? Are bug reports done in another way?

**Comment by darshankawar** [comment]
@dantechguy 
Since the original issue you reported was resolved but in order to address the observations you listed, it is better to file a new issue so that it can tracked separately.
