### ISSUE TITLE
Arabic OTP sms not detected in iOS

### ISSUE THREAD

**Issue by tejasurve** [flutter/flutter#145257]
### Steps to reproduce

(Only for iOS)
1) Open My Etisalat Application (Change language to Arabic)
2)Goto EASE section
3)Login in with your number
4)OTP will be received in SMS but the Autosuggestion for OTP is not shown

Please note the My Etisalat is written in Native iOS and EASE is a Flutter SDK integrated into it.
It you change language of MyEtisalat app to english and try the same the it will work as iOS is detecting english sms otp

### Expected results

I must see the autoFill or AutoSuggestion box which will allow me to tap and paste otp directly 

### Actual results

No autofill or Autosuggestion shown when sms received in ARABIC.

### Code sample

can't share code

### Screenshots or Video

1) FOr Arabic Language (Not Working) sms received in Arabic
![image_123650291 (1)](https://github.com/flutter/flutter/assets/54415609/16ae92f4-f885-4b40-bc3d-9c1479497368)

2)For English Language (Working) sms received in english
![image_123650291](https://github.com/flutter/flutter/assets/54415609/1221f13e-8e72-465d-9a3f-8b0178a01620)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Flutter (Channel stable, 3.13.4, on macOS 13.3 22E252 darwin-arm64
    (Rosetta), locale en-IN)
    • Flutter version 3.13.4 on channel stable at /Users/tejassu/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.2/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/tejassu/flutter. Consider adding
      /Users/tejassu/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (6 months ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tejassu/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Users/tejassu/Downloads/Xcode 2.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

Unknown architecture undefined_arch, defaulting to arm64
Unknown architecture undefined_arch, defaulting to arm64
[✓] Connected device (4 available)            
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro (mobile)      • CFEE4CC6-C0E7-4354-889E-74954AA534C3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.3 22E252 darwin-arm64 (Rosetta)
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 122.0.6261.129
    ! Error: Browsing for Saurabh’s iPhone (CoreDevice)  on the local area
      network. Ensure that the device is booted, unlocked, and discoverable via
      Bluetooth and WiFi, or attached with a cable. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by moffatman** [comment]
This is not a Flutter issue. All Flutter does is tell iOS the current text field is "oneTimeCode" type. It's up to iOS to do the rest. But I can offer these links after some searching, you may need to adjust the content of your SMS in Arabic to get iOS to recognize it

- https://stackoverflow.com/questions/39631168/automatic-otp-verification-in-ios
- https://stackoverflow.com/questions/58499469/ios-otp-auto-suggestion-is-not-working-in-arabic

**Comment by huycozy** [comment]
@tejasurve Please check the comment above to see if you can solve the issue that way. Otherwise, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we can verify the issue properly.
