### ISSUE TITLE
Inconsistent mouse cursor behavior between Windows and web

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#145241]
### Use Case

On YouTube, you can move your mouse over a video that's playing, and after not moving the mouse for a few seconds, the cursor disappears.

Currently, this isn't possible to achieve in a Windows Flutter app.

<br>

### Steps to reproduce

Run the "Code sample" below.

### Expected results

The app should cause the mouse to blink on and off.

### Actual results

The mouse blinks correctly when running on the web.

On Windows, however, the mouse only blinks while it's moving: holding the cursor still will make it ignore any changes.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  void initState() {
    super.initState();
    Timer.periodic(
      const Duration(seconds: 1),
      (_) => setState(() {
        showCursor = !showCursor;
      }),
    );
  }

  bool showCursor = true;

  @override
  Widget build(BuildContext context) {
    final cursor = showCursor ? MouseCursor.defer : SystemMouseCursors.none;

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: MouseRegion(
          cursor: cursor,
          child: Container(color: Colors.blueGrey),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![mouse blinking](https://github.com/flutter/flutter/assets/10457200/e278b448-60da-4986-9d7d-ac07b47755d7)

(this does not happen when running a native Windows application)

</details>

**Comment by huycozy** [comment]
Thank you for the report! This looks similar to https://github.com/flutter/flutter/issues/124579. Please also share your example there. Closing this issue in favor of that one, so please follow up on it for further updates.
