### ISSUE TITLE
[docs] `flutter_adaptive_scaffold`'s link to design doc is broken

### ISSUE THREAD

**Issue by aatifsyed** [flutter/flutter#145292]
### What package does this bug report belong to?

flutter_adaptive_scaffold

### What target platforms are you seeing this bug on?

Web

### Have you already upgraded your packages?

Yes

### Steps to reproduce

The [link to the design doc](https://github.com/flutter/packages/blob/a757073ac4eaf05b7516d3d0488e5c98b221043f/packages/flutter_adaptive_scaffold/README.md?plain=1#L254), also on [`flutter_adaptive_scaffold's pub.dev page](https://pub.dev/packages/flutter_adaptive_scaffold) is [broken](https://docs.google.com/document/d/1qhrpTWYs5f67X8v32NCCNTRMIjSrVHuaMEFAul-Q_Ms/edit?usp=sharing):

> We're sorry. You can't access this item because it is in violation of our [Terms of Service](http://www.google.com/google-d-s/intl/en/terms.html).
>
> Find out more [about this topic at the Google Drive Help Center](https://support.google.com/drive/bin/answer.py?hl=en&answer=148505).

![image](https://github.com/flutter/flutter/assets/38045910/3be0ace1-0507-42b6-a319-3a5cdb2ae316)

### Expected results

Working links in user-facing documentation.

### Actual results

Linked docs are broken.

### Code sample

N/A

### Flutter Doctor output

N/A

**Comment by darshankawar** [comment]
The design doc link from this section https://pub.dev/packages/flutter_adaptive_scaffold#additional-information is broken.

**Comment by stuartmorgan** [comment]
I don't think the author of that document is active in the project any more, so there's no way to recover it; that section of the README will just need to be removed.
