### ISSUE TITLE
BoxDecoration doesn't have placeholder property

### ISSUE THREAD

**Issue by unaisshemim** [flutter/flutter#145205]
### Steps to reproduce

   decoration: BoxDecoration(
              image: DecorationImage(
                image: CachedNetworkImageProvider(tourData.tour[currentIndex]),// all are links
                fit: BoxFit.contain,
              ),
              color: Colors.grey,
            ),

### Expected results

it should have placeholder so when the image loads we can show picture

### Actual results

placeholder property is missing

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by unaisshemim** [comment]
Placeholder property is missing

**Comment by darshankawar** [comment]
@unaisshemim 
[This](https://github.com/Baseflow/flutter_cached_network_image/issues/177#issuecomment-764438406) solution should be helpful to resolve your issue.
Closing based on it.
