### ISSUE TITLE
Specific package for specific platform

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#145284]
### Use case

I want to use a specific package for a specific platform
For example, I should use the `media_kit` package only on the web and it should not be used in the build of the Android platform.

### Proposal

I suggest adding a possibility to use a specific package for a specific platform.

in such a way that that package is not considered in the build of other platforms.

**Comment by huycozy** [comment]
`media-kit` is a 3rd package. You should file an issue to package's developers for better support there: https://github.com/media-kit/media-kit/issues.

I will close this issue as it's not a Flutter framework or 1st party package issue. If you are supposed to change the request for [1st party packages](https://github.com/flutter/packages/tree/main/packages), please file another issue. Thanks!

**Comment by mbfakourii** [comment]
> `media-kit` is a 3rd package. You should file an issue to package's developers for better support there: https://github.com/media-kit/media-kit/issues.
> 
> I will close this issue as it's not a Flutter framework or 1st party package issue. If you are supposed to change the request for [1st party packages](https://github.com/flutter/packages/tree/main/packages), please file another issue. Thanks!

I did not mean only this package, this package was an example. I wanted it to be possible not to consider a series of packages in the build of different platforms.

**Comment by huycozy** [comment]
One proposal can not be applied to every or series of packages/plugins. It should be a specific proposal on one package/plugin only. Please also check [Federated plugins](https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins).

**Comment by mbfakourii** [comment]
> One proposal can not be applied to every or series of packages/plugins. It should be a specific proposal on one package/plugin only. Please also check [Federated plugins](https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins).

This is exactly my problem. I suggest adding such a possibility that the user can choose, not a specific package
