### ISSUE TITLE
The image for the indicator of the TabBar does not auto-adapt to different resolutions

### ISSUE THREAD

**Issue by gaojunming** [flutter/flutter#145204]
### Steps to reproduce

According to the documentation for resolution-aware assets (https://flutter.cn/docs/ui/assets/assets-and-images#resolution-aware), my project's asset directory structure is as follows:

assets/images/icon/indicator.png
assets/images/icon/2.0x/indicator.png
assets/images/icon/3.0x/indicator.png

When specifying the indicator of the TabBar to use an image, the image does not auto-adapt to different resolutions.

After tracing the source code of the TabBar, it was found that this is due to the fact that the ImageConfiguration constructed during the execution of _IndicatorPainter does not specify the devicePixelRatio.

### Expected results

The expected behavior is for the image to auto-adapt to different resolutions.

### Actual results

The image does not auto-adapt to different resolutions.

### Code sample

    TabBar(
                            indicator: BoxDecoration(image: DecorationImage(image: AssetImage("assets/images/icon/indicator.png"),alignment :Alignment.bottomCenter)),
                            tabs: <Widget>[
                              Tab(
                                text: "tab1",
                              ),
                              Tab(
                                text: "tab2",
                              ),
                              Tab(
                                text: "tab3",
                              ),
                            ],
                          ),

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.16.1, on Microsoft Windows [版本 10.0.19045.4170], locale zh-CN)
    • Flutter version 3.16.1 on channel stable at F:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (4 months ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at F:\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: F:\Android\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2)
    • Visual Studio at F:\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34018.315
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at F:\Android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • M2007J3SC (mobile) • 192.168.152.37:40853 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows              • windows-x64    • Microsoft Windows [版本 10.0.19045.4170]
    • Chrome (web)       • chrome               • web-javascript • Google Chrome 122.0.6261.113
    • Edge (web)         • edge                 • web-javascript • Microsoft Edge 122.0.2365.80

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment]
Thanks for the report. 

https://github.com/flutter/flutter/blob/985576dbfdff5e9321941d9f66cb33baed337346/packages/flutter/lib/src/material/tabs.dart#L562-L565

Checked on some devices, results looks the same
- Realme 6: 6.5 inches, 1080 x 2400 pixels, 20:9 ratio (~405 ppi density)
- Pixel 7: 6.3 inches, 1080 x 2400 pixels, 20:9 ratio (~416 ppi density)
- Galaxy Tab A7 Lite: 8.7 inches, 800 x 1340 pixels, 5:3 ratio (~179 ppi density)

<details>
<summary>Demo</summary>

- Realme 6:
![Screenshot 2024-03-15 at 19 08 55](https://github.com/flutter/flutter/assets/104349824/c27a122b-d61e-42a2-a5a9-c72fa46d51f7)
- Pixel 7:
![Screenshot 2024-03-15 at 19 11 48](https://github.com/flutter/flutter/assets/104349824/19f6fb4d-ca53-4ff6-8ae7-7b123ee3d608)
- Galaxy Tab A7 Lite:
![Screenshot 2024-03-15 at 19 15 16](https://github.com/flutter/flutter/assets/104349824/71a54bc3-29a8-4ba7-a959-d018c0feef81)

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 hours ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.21.0-7.0.pre.46, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.21.0-7.0.pre.46 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9b276be7fe (2 hours ago), 2024-03-14 21:46:36 -0400
    • Engine revision 995d8903e0
    • Dart version 3.4.0 (build 3.4.0-234.0.dev)
    • DevTools version 2.33.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D          • android-arm64  • Android 11 (API 30)
    • iPad (mobile)    • 00008103-000A1464346A201E • ios            • iOS 17.2 21C62
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>
