### ISSUE TITLE
Make BackgroundIsolateBinaryMessenger API consistent on web

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#145260]
### Use case

The `BackgroundIsolateBinaryMessenger` API requires an `ensureInitialized()` method call before its `instance` field can be used. Unfortunately the web implementation of the `BackgroundIsolateBinaryMessenger` does not have the `ensureInitialized()` method, to the compilation targeted for the web is failing at compile time with `Member not found: 'BackgroundIsolateBinaryMessenger.ensureInitialized'` error.

Currently we have to make own wrapper with platform-specific import to make this compile on web.

### Proposal

It would be really handy if `BackgroundIsolateBinaryMessenger` has consistent API between io and web implementations. It will be sufficient to have it `throw UnsupportedError('Isolates not supported on web.')`

**Comment by darshankawar** [comment]
@ekuleshov 
Please check [this](https://github.com/flutter/flutter/issues/136886#issuecomment-1781620302) and see if it helps in your case or not.

**Comment by ekuleshov** [comment]
> @ekuleshov Please check [this](https://github.com/flutter/flutter/issues/136886#issuecomment-1781620302) and see if it helps in your case or not.

Essentially that is the same issue looked from a different angle. But the solution I'm suggesting/requesting here is much simpler and does not require changes in the Dart compiler.

There is already conditional import in the Flutter's `package:flutter/services.dart` which imports one of:

* `_background_isolate_binary_messenger_io.dart`
* `_background_isolate_binary_messenger_web.dart`

However, due to the asymmetry of the web API (i.e. absence of the `ensureInitialized()` in the web-specific implementation), in order to use the web version adding `if(kIsWeb) ...` is not enough as noted in #136886

We have to make own wrapper with our own conditional import and implement own wrappers for `ensureInitialized()` for io and web.

If the Flutter's `_background_isolate_binary_messenger_web.dart` implementation simply had an `ensureInitialized()` method matching the io's API, all of that won't be necessary and we could simply use `if(kIsWeb) ...` instead of all those custom wrappers.

**Comment by darshankawar** [comment]
Thanks for the feedback.

**Comment by ditman** [comment]
I'll work on adding this method next, it'll `throw` _Unimplemented_.
