### ISSUE TITLE
[gen_l10n] Add an option to use custom number format for generated l10n files

### ISSUE THREAD

**Issue by lsaudon** [flutter/flutter#145202]
### Use case

Use a specific format for a specific message

### Proposal

Like isCustomDateFormat actual solution:

```json
{
  "helloWorld": "{max}",
  "@helloWorld": {
    "placeholders": {
      "max": {
        "type": "num",
        "format": "# ###",
        "isCustomNumberFormat": "true"
      }
    }
  }
}
```

**Comment by darshankawar** [comment]
@lsaudon 
Can you elaborate what exactly is your use case and proposal ?
Also, can you check https://github.com/flutter/flutter/issues/116716 to see if it resembles your case or not ?

**Comment by goderbauer** [comment]
Hey @lsaudon, could you add a little more details? Right now it is not clear to me what you're asking for. Maybe give an example of what you'd like to achieve?

**Comment by lsaudon** [comment]
For one message, I want a space separator for number.
```
The text must not exceed 1 000 characters.
Le texte ne doit pas dépasser 1 000 caractères.
El texto no debe superar los 1 000 caracteres.
```
