### ISSUE TITLE
Issue with TextField Line Spacing and Cursor Height in Flutter

### ISSUE THREAD

**Issue by tummyhuang** [flutter/flutter#145394]
### Steps to reproduce

Hello,

I am currently working on a Flutter project and trying to implement line spacing in a TextField by adjusting the height property in TextStyle. However, I've encountered an issue where, after setting the height, the cursor's height becomes abnormal.

Additionally, when I attempt to specify the cursorHeight to correct this, the cursor does not appear centered within the line.

I've been unable to find a solution that addresses both the line spacing and cursor height simultaneously. Any suggestions or workarounds to resolve this issue would be greatly appreciated.

Thank you.

### Expected results

My expected result is for the cursor to display normally.

### Actual results

| cursor's height becomes abnormal | cursor not centered |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/31909169/fcc7dc74-0aad-44b0-8dbc-75902d4cd4ca"> | <img width="400" src="https://github.com/flutter/flutter/assets/31909169/26560d77-fcb5-41c2-8b4e-8c629c40c60b">

### Code sample

<details open><summary>Code sample</summary>

```dart
TextField(
      style: TextStyle(
          fontSize: 20,
          textBaseline: TextBaseline.alphabetic,
          height: 3.5
      ),
      //cursorHeight: 20,
      decoration: InputDecoration(
          hintText: "Hello",
          filled: true,
          fillColor: Colors.yellow,
          // border: const OutlineInputBorder(borderSide: BorderSide.none),
          isCollapsed: true,
          isDense: true,
          counterText: '',
          contentPadding: EdgeInsets.all(0)
      ),
  )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel [user-branch], 3.13.1-0.0.pre.531, on macOS 14.1.1 23B81
    darwin-arm64, locale zh-Hans-CN)
```

</details>

**Comment by huycozy** [comment]
Hi @tummyhuang 
I checked this issue on Android using your sample code above but don't see the issue in your demo. 

![Screenshot 2024-03-20 at 13 11 01](https://github.com/flutter/flutter/assets/104349824/39471a0e-f704-41cf-89f5-40df80c32088)

I'm on the latest Flutter stable channel 3.19.3. I see you are using an old Flutter version. So please try upgrading your Flutter version and re-check this.

**Comment by tummyhuang** [comment]
There is still a problem.

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.19.0-5.0.pre.45, on macOS 14.1.1 23B81
    darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.

test code (only android):
[hellotextfield2.zip](https://github.com/flutter/flutter/files/14716943/hellotextfield2.zip)

**Comment by huycozy** [comment]
When I enable `cursorHeight`, I can see the issue. Meanwhile, it doesn't occur on Web:

| Web | Android |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/a950eb93-53cb-473f-9d78-78a37cc9a95d"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/61c5a333-cc2e-4ca5-8a82-efe1f771fbb4">

This reminds me of a similar issue at https://github.com/flutter/flutter/issues/143480. I will close this in favor of that one. So please follow it for updates. Thanks!
