### ISSUE TITLE
iOS17 TextField Flutter

### ISSUE THREAD

**Issue by WGuiGui** [flutter/flutter#145377]
### Steps to reproduce

When I use the native keyboard of my phone to input Chinese characters in the iOS17 system, the content in the input box can only display one or two characters

When I input English or numbers, there is no problem

After inputting some pinyin, I cleared the pinyin in TextField again and was able to input pinyin normally

### Expected results

I want to be able to input Chinese characters using the system keyboard at any time

### Actual results

I can only input English and numbers, not Chinese characters. Only when I delete all the characters in TextField can I re-enter Chinese characters

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by WGuiGui** [comment]
https://github.com/flutter/flutter/assets/17424844/b7cffc12-1ac6-4fc2-a76e-5cb565f1d74b


https://github.com/flutter/flutter/assets/17424844/1af8170d-ea52-4b2b-a7fe-84fe03e96e94

**Comment by darshankawar** [comment]
@WGuiGui 
Can you provide `flutter doctor -v` ?

**Comment by WGuiGui** [comment]
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1.2 23B92 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.3 on channel stable at /Users/ffwang/Desktop/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (12 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ffwang/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] VS Code (version 1.67.2)
    • VS Code at /Users/ffwang/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • 飞哥iPhone8P (mobile) • bff0cab886cf406fcb7dca63e0e7f79327f94cbb • ios            • iOS 15.5 19F77
    • 飞哥的iPhone (mobile)  • 00008030-000C65C01E46402E                • ios            • iOS 17.4 21E219
    • macOS (desktop)     • macos                                    • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)        • chrome                                   • web-javascript • Google Chrome 122.0.6261.129
    ! Error: Browsing on the local area network for LIAN的13PM. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[!] Network resources                   
    ✗ A network error occurred while checking "https://maven.google.com/": Operation timed out

! Doctor found issues in 1 category.

**Comment by WGuiGui** [comment]
Hello, I have re recorded two more videos

The first video is using iPhone 8P and iOS 15.5 system. Whether I use full keyboard Pinyin or Nine Palace Pinyin, I have no problem entering Chinese characters

The second video uses iPhone 11 and the system is iOS 17.4 (which was upgraded from iOS 17.3 yesterday). When using Nine Palace Pinyin to input Chinese characters, only the first two characters or one character can be entered; When using full keyboard Pinyin to input Chinese characters, I was able to input some at first, but as I continued to input, I found that the letters I had previously entered had disappeared

No problem on Android system

If it is related to the version of Flutter I am using, I will try uninstalling and reinstalling the latest version today to test this issue

thanks

**Comment by WGuiGui** [comment]
Uploading 王飞飞 2024-03-03 10.29.29.mp4…


Uploading 王飞飞 2024-03-03 10.29.22.mp4…

**Comment by WGuiGui** [comment]
https://github.com/flutter/flutter/assets/17424844/6543331c-8f78-41b0-8041-e541b7e7930e


https://github.com/flutter/flutter/assets/17424844/ef15f4de-efd5-4ea5-9fce-e0bde61c107e

**Comment by darshankawar** [comment]
Thanks for the update. We are still trying to replicate this on iOS 17 device. In order to properly replicate, the issue you are facing is that, using pinyin keyboard, you are not seeing the input being rendered in local language but still see English letters while using that keyboard, but once you delete / clear the input, then you are able to see the local text. Is this a correct interpretation of the issue you are facing ?

Also, please confirm the same by running your scenario on latest master as well to check if it persists or not.

**Comment by WGuiGui** [comment]
After upgrading both Flutter and Dart versions to the latest version today, TextField can now input text normally

The reason for not being able to input normally is probably due to the lower version of my Dart, which was upgraded from 3.1.3 to 3.3.1 today

There are currently no issues, thank you again

**Comment by darshankawar** [comment]
Closing as fixed.
