### ISSUE TITLE
Make sure focus works with text fields

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#145362]
> [!NOTE]  
> This issue is a **continuation of**:
> * https://github.com/flutter/flutter/issues/137443
> * https://github.com/flutter/flutter/issues/144235

Ensure that the new focus system works well with text fields. Users should be able to tab in and out of text fields as if they were using a normal web app.

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/engine/pull/51009
