### ISSUE TITLE
[engine] @jason-simmons: missing const qualifiers on struct Resource's constructor and member's data

### ISSUE THREAD

**Issue by CodeVisio** [flutter/flutter#145309]
### Steps to reproduce

Hi,

Shouldn't `template< typename T > struct Resource` inside impeller/renderer/command.h have `const` qualifier at line 41 and 54?

Private template function BindResource() (line 188) is called by public BindResource() methods and one of them has const std::shared_ptr as parameter.
I don't understand why clang doesn't flag the calls at lines 55 and 59 inside command.cc as ambiguos.

The second constructor of `template< typename T > struct Resource` was introduced by @jason-simmons

[[Impeller] Add a safe way for runtime effects to provide dynamically generated shader metadata (](https://github.com/flutter/engine/commit/d66ee331da1c6ad86fc342711eb8420244128d07)https://github.com/flutter/engine/pull/40992[)](https://github.com/flutter/engine/commit/d66ee331da1c6ad86fc342711eb8420244128d07)

Thanks

### Expected results

NA

### Actual results

NA

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @CodeVisio 
This seems to be a question rather than a bug report or feature request. Please see flutter's [community](https://flutter.dev/community) for resources (you may find Discord channel and ask the same question there. 

If you propose a change, please try to fill all information indicated in the issue template so that we can verify the issue properly. Thanks!

**Comment by CodeVisio** [comment]
@huycozy 

Thanks for your answer.
Please consider this issue closed.

Thanks
