### ISSUE TITLE
flutter doctor Unhandled exception: type 'Null' is not a subtype of type 'int' in type cast

### ISSUE THREAD

**Issue by Reinoal** [flutter/flutter#145310]
### Steps to reproduce

flutter doctor Unhandled exception: type 'Null' is not a subtype of type 'int' in type cast

### Expected results

flutter doctor Unhandled exception: type 'Null' is not a subtype of type 'int' in type cast

### Actual results

flutter doctor Unhandled exception: type 'Null' is not a subtype of type 'int' in type cast

### Code sample

flutter doctor Unhandled exception: type 'Null' is not a subtype of type 'int' in type cast

### Logs

#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:427:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:96:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#20     Future._completeError (dart:async/future_impl.dart:651:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

### Flutter Doctor output

#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:85:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:89:7)
#2      new Session (package:unified_analytics/src/session.dart:28:5)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:427:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:96:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#20     Future._completeError (dart:async/future_impl.dart:651:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

**Comment by Reinoal** [comment]
reinstall flutter sdk and dart sdk, reinstall vscode dosn't work

**Comment by Reinoal** [comment]
flutter sdk 3.19.3 viscose:1.87.2 (Universal)
Mac mini os:14.2.1 (23C71)

**Comment by Reinoal** [comment]
network error

**Comment by huycozy** [comment]
This is a known issue at https://github.com/flutter/flutter/issues/145201. It should be fixed on Flutter master channel. You can check the workaround at https://github.com/flutter/flutter/issues/145201#issuecomment-1999463478 as well. 

Closing this issue as a duplicate. If the issue persists on master channel, please write a comment at https://github.com/flutter/flutter/issues/145201. Thanks!

**Comment by trucuit** [comment]
same issue

**Comment by trucuit** [comment]
rm ~/.dart-tool/dart-flutter-telemetry-session.json
