### ISSUE TITLE
[camerax] ResolutionPreset.high has camera preview size set to 720x540 instead of 1280x720, unlike the camera_android plugin

### ISSUE THREAD

**Issue by kaciula** [flutter/flutter#145382]
### What package does this bug report belong to?

camera

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

 camera: 0.10.5+9
 camera_android_camerax: 0.5.0+36

### Steps to reproduce

Create a CameraController with ResolutionPreset.high

### Expected results

The camera preview size should be 1280 x 720. 

### Actual results

The camera preview size becomes 720 x 540. The camera_android plugin has the proper preview size of 1280 x 720 so it is possible to have this preview size on the device. For some reason, the cameraX plugin does not resolve to this resolution and aspect ratio. I know the resolution presets are targets and are not guaranteed. But if the camera_android plugin resolves to the correct resolution, cameraX should also be able to do this.

### Code sample

<details open><summary>Code sample</summary>

```dart
 _controller = CameraController(cameras[0], ResolutionPreset.high);
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.2.1 23C71 darwin-arm64, locale en-RO)
    • Flutter version 3.19.3 on channel stable at /Users/ka/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (11 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ka/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • BE2029 (mobile)                   • d49fd97d                                 • android-arm64  • Android 11 (API 30)
    • Catalin Morosan’s iPhone (mobile) • b4edf88c07bc09f8c4aa16ca492b0ddbbc369aa1 • ios            • iOS 15.8 19H370
    • macOS (desktop)                   • macos                                    • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                      • chrome                                   • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by kaciula** [comment]
After looking more into this, the reason the preview size isn't the correct one is because the camerax plugin does not set an explicit aspect ratio and thus it uses the default one from native side of 4:3.

I've modified the source code to explicitly set a 16:9 aspect ratio which seems to solve this. In order to have the exact behavior as the camera_android plugin, I think 16:9 should be set as the default aspect ratio.

```
static ResolutionSelector _createAttachedResolutionSelector(
      ResolutionStrategy resolutionStrategy) {
    return ResolutionSelector(
      resolutionStrategy: resolutionStrategy,
      aspectRatioStrategy: AspectRatioStrategy(
        preferredAspectRatio: AspectRatio.ratio16To9,
        fallbackRule: AspectRatioStrategy.fallbackRuleAuto,
      ),
    );
  }
  ```

**Comment by danagbemava-nc** [comment]
Hi @kaciula, this is a known issue which is being tracked in https://github.com/flutter/flutter/issues/144363. 

Kindly share your findings in the issue linked above. 

Closing from here as duplicate. 

Thank you
