### ISSUE TITLE
How to use flutter_service_worker.js in hostElement while the flutter app and the host's domains are different?

### ISSUE THREAD

**Issue by adar2378** [flutter/flutter#145314]
### Steps to reproduce

1. Host flutter web app to domain
2. Use that hosted flutter app as elementHost in another non-flutter html page in a different domain

### Expected results

flutter_service_worker.js loads without error

### Actual results

Exception while loading service worker: DOMException: Failed to register a ServiceWorker: The origin of the provided scriptURL ('[HOSTED_FLUTTER_APP_URL]') does not match the current origin ('[ANOTHER_HOSTED_HTML_PAGE]').

### Code sample

<details open><summary>Code sample</summary>

```JS
function launchFlutter() {
        _flutter.loader.loadEntrypoint({
          serviceWorker: {
            serviceWorkerUrl: "{{ flutter_url }}flutter_service_worker.js?v=",
            serviceWorkerVersion: serviceWorkerVersion,
          },
          entrypointUrl: "{{ flutter_url }}main.dart.js",
          onEntrypointLoaded: async (engineInitializer) => {
            const appRunner = await engineInitializer.initializeEngine({
              hostElement: document.querySelector("#flutter_target"),
              assetBase: "{{ flutter_url }}",
            });
            await appRunner.runApp();
            document.querySelector('.shimmer-container').style.display = 'none';
          },
        });
      }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.16.9, on macOS 14.2.1 23C71 darwin-arm64,
    locale en-BD)
    ! Flutter version 3.16.9 on channel [user-branch] at
      /Users/saifulislam/Development/flutter_sdk/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss
      this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.0)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @adar2378 
For us to further investigate this issue, could you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code? 
It would appreciated if you could add it to a GitHub repository so that we can easily pull and run the sample projects (please also add license the code in the repository under some open-source license (e.g. MIT, Apache, BSD, GPL) so that we may look into it). Thank you!

**Comment by adar2378** [comment]
@huycozy Sure I will do that. 

But I think it is not about code sample, it is about providing documentation on embedding element of flutter on how to use flutter_service_worker.js if the flutter app has a different domain and the host has a different domain. Because looks like due to browser restriction, flutter_service_worker.js must be in the same domain as the host. 

Also I could not find any example app for embedding element of Flutter web app in another web app/site.

**Comment by huycozy** [comment]
Thanks. Please share a sample code so that we can verify this properly.

Instead, if you think there should be an example in such case (different domains), please file a new issue (proposal template).

>Also I could not find any example app for embedding element of Flutter web app in another web app/site.

Please check this sample code to see if it's your need: https://github.com/flutter/samples/tree/main/web_embedding
