### ISSUE TITLE
Flutter Package google_sign_in shows the screen "Couldn't sign in" but no exception is thrown and there is no way to get out of the screen without quitting the app.

### ISSUE THREAD

**Issue by arc4randall** [flutter/flutter#145341]
### Steps to reproduce

1. Install google_sign_in ^6.2.1
2. Enter this code:

```dart
Future<void> _googleLogin() async {
    const webClientId = 'webclientId' // Enter the real web client id from cloud console

    final GoogleSignIn googleSignIn = GoogleSignIn(
      serverClientId: webClientId,
      scopes: [
        'email',
      ],
    );
    try {
      final googleUser = await googleSignIn.signIn();
      if (googleUser == null) {
        throw 'Google Sign In failed';
      }
      final googleAuth = await googleUser.authentication;
      final accessToken = googleAuth.accessToken;
      final idToken = googleAuth.idToken;

      if (accessToken == null) {
        throw 'No Access Token found.';
      }
      if (idToken == null) {
        throw 'No ID Token found.';
      }
  }
```

### Expected results

The googleSignIn.signIn(); method should either succeed or throw an error. Instead, the code is stuck on this method execution and the screen says "couldn't sign in" with no way to go back or debug.

### Actual results

<img width="469" alt="Screenshot 2024-03-18 at 12 56 37 PM" src="https://github.com/flutter/flutter/assets/7901383/3e6baa46-abd9-44b1-9ced-8cbe827015fc">

### Code sample

<details open><summary>Code sample</summary>

```dart
    final GoogleSignIn googleSignIn = GoogleSignIn(
      serverClientId: webClientId,
      scopes: [
        'email',
      ],
    );
    try {
      final googleUser = await googleSignIn.signIn();
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/7901383/3b9261ab-0db6-4e06-a552-8287733a182a

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] VS Code (version 1.88.0-insider)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by danagbemava-nc** [comment]
Hi @arc4randall, what platform(s) are you seeing this issue on? 

Have you completed the required setup for the platform? 

Does the serverClientId that you set actually belong to your backend server? Otherwise you should be setting the clientId instead.

**Comment by danagbemava-nc** [comment]
Hi @arc4randall, what platform(s) are you seeing this issue on? 

Have you completed the required setup for the platform? 

Does the serverClientId that you set actually belong to your backend server? Otherwise you should be setting the clientId instead.

**Comment by arc4randall** [comment]
I am running this on Android Emulator Pixel 8 running VanillaIceCream. I set the client ID from Google Cloud Console.

**Comment by danagbemava-nc** [comment]
Does the emulator you're using have google play support?
