### ISSUE TITLE
App Crashes : MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.dev/google_maps_android_4)

### ISSUE THREAD

**Issue by wasim954** [flutter/flutter#145307]
### Steps to reproduce

I am using google_maps_flutter: ^2.6.0 with Flutter 3.19.2
some time i am getting MissingPluginException exception 
MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.dev/google_maps_android_4)

### Expected results

App should not crashed

### Actual results

App is crashing

### Code sample

<details open><summary>Code sample</summary>

```dart
GoogleMap(
              mapType: MapType.normal,
              markers: Set.from(controller.liveMarkers),
              myLocationEnabled: false,
              myLocationButtonEnabled: false,
              onMapCreated: (GoogleMapController gMapController) {
                controller.liveMapController.complete(gMapController);
              },
              initialCameraPosition: CVLiveViewWidget._kGooglePlex,
            )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by wasim954** [comment]
Logs

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.dev/google_maps_android_4)
MethodChannel._invokeMethod (platform_channel.dart:332)

**Comment by huzaif-fahad** [comment]
@wasim954 Have you followed all the steps to configure the package and have you tried this fix https://stackoverflow.com/a/75719771 ? 
Also I don't think its an issue on the framework but rather the package itself.@wasim954, have you followed all the steps to configure the package? Also, have you tried this fix https://stackoverflow.com/a/75719771? I don't think it's an issue with the framework, rather it seems to be an issue with the package itself.

**Comment by darshankawar** [comment]
This seems to be similar to https://github.com/flutter/flutter/issues/43785 so please follow-up in it for further updates.
Closing as duplicate. You may share your findings in it for better tracking.

**Comment by wasim954** [comment]
@darshankawar 

do we have a solution for this issue?
