### ISSUE TITLE
how can I make a Row scrollable? I used the listView and the SingleChildScrollView widget to the row but it did not worked

### ISSUE THREAD

**Issue by himanshudave2212** [flutter/flutter#145378]
body: ListView(
          children: const [
            Row(
              children: [
                Text('Row 1'),
                Text('Row 2'),
                Text('Row 3'),
                Text('Row 4'),
                Text('Row 5'),
                Text('Row 6'),
                Text('Row 7),
                Text('Row 8'),
                Text('Row 9'),
                Text('Row 10'),
              ],
            ),
          ],
        ));
///////////////////////////////////////////////////////

body: const SingleChildScrollView(
        child: Row(
          children: [
            Text('Row 1'),
            Text('Row 2'),
            Text('Row 3'),
            Text('Row 4'),
            Text('Row 5'),
            Text('Row 6'),
            Text('Row 7'),
            Text('Row 8'),
            Text('Row 9'),
            Text('Row 10'),
          ],
        ),
      ),

**Comment by himanshudave2212** [comment]
@ebeem can you please help me out here!!!!!

**Comment by Trung15010802** [comment]
You should google " How to create horizontal ListView in Flutter?"
