### ISSUE TITLE
Firebase for Flutter/iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1453]
Let's use Firebase as an example of how to connect third-party service to Flutter!

- [x] Mojo implementation/binding for iOS
- [ ] flutter command-line tool makes it easy to integrate this service
- [ ] Docs
- [ ] Example

**Comment by sethladd** [comment]
cc @collinjackson for this tracking issue

**Comment by eseidelGoogle** [comment]
My understanding is @collinjackson is owning the service code portion of this.

**Comment by collinjackson** [comment]
Yep. Also, I'm making the basic Firechat example app work, code is here:
https://github.com/flutter/firechat-flutter

**Comment by collinjackson** [comment]
Chinmay is working on step 2 of this

**Comment by collinjackson** [comment]
Chinmay, what's the status of this? Let me know if I can help.

**Comment by chinmaygarde** [comment]
I have packaged the service into a pub package. Needs some support on the tooling front to integrate it with the application bundle. Working on that now.

**Comment by chinmaygarde** [comment]
This can be closed after https://github.com/flutter/engine/pull/2394 and https://github.com/flutter/flutter/pull/1835 and there is a roll

**Comment by chinmaygarde** [comment]
Third party packages have been patched: https://github.com/flutter/firechat-flutter/pull/10 and https://github.com/flutter/firebase-dart/pull/13

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1032. Any further collaboration will be done there.
