### ISSUE TITLE
How to click and drag point of polygon? 

### ISSUE THREAD

**Issue by alexlozdev** [flutter/flutter#145372]
### Use case

I want to click and drag points of polygon.
Is there any ways to do this?

### Proposal

[3.webm](https://github.com/flutter/flutter/assets/61686168/cb3225de-9c37-42e1-9ce6-575fb1b23494)

**Comment by darshankawar** [comment]
@alexlozdev 
Your question / issue is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a repo to track bug reports and feature requests.
