### ISSUE TITLE
Registering a custom web service worker in a Flutter web project triggers a MIME type issue

### ISSUE THREAD

**Issue by andynewman10** [flutter/flutter#145492]
**Describe the bug**

Registering a custom service worker for flutter web is not working as expected.

**To Reproduce**

1. create a flutter web-only application using `flutter create --platforms=web testapp`.
2. add `service_worker: ^0.3.0` in your `pubspec.yaml`
3. Edit your `main.dart` code this way:

```
// add the following line
import 'package:service_worker/window.dart' as sw;

void main() async {
  // add the following line
  await sw.register('sw.dart.js');
  ...
}
```
4. In your `web/` folder, add a `sw.dart` file and copy/paste the contents from the `sw.dart` file from the [example code](https://github.com/isoos/service_worker/blob/master/example/web/sw.dart).
5. Copy/paste the `build.yaml` file from the [example code](https://github.com/isoos/service_worker/blob/master/example/build.yaml).
6. Place a breakpoint on the line `await sw.register('sw.dart.js')` then launch a debug session by clicking on the `Debug` text above the `main` function.

More information in these [instructions](https://pub.dev/packages/service_worker), if needed.

**Expected behavior**

The service worker should be run appropriately. `sw.register` should not raise an exception.

**Actual behavior**

Executing the line `await sw.register('sw.dart.js')` raises the following exception:

```
Error: SecurityError: Failed to register a ServiceWorker for scope ('http://localhost:51279/')
with script ('http://localhost:51279/sw.dart.js'): The script has an unsupported MIME type (text/html)
...
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart
...
```

**Questions**

I know getting a service worker to work is going to be [tricky](https://github.com/flutter/flutter/issues/67625). Basically, Flutter uses a service worker itself (flutter_service_worker.js), and because of this, a web application using a custom service worker needs special consideration.

Immediately, my goal is to try to mitigate this issue: is there a way I can force `sw.dart.js` to be sent as `text/javascript`, for instance ?

**Please complete the following information:**

 - Operating System and version: Windows 11
 - VS Code version: 1.87.2
 - Dart extension version: 3.84.0
 - Dart/Flutter SDK version: 3.19.3
 - Target device (if the issue relates to Flutter debugging): web (Microsoft Edge)

**Comment by darshankawar** [comment]
@andynewman10 
Can you take a look at https://docs.flutter.dev/platform-integration/web/initialization and see if service-worker implementation mentioned in it helps in your case or not ?


> * Target device (if the issue relates to Flutter debugging): web (Microsoft Edge)

Can you also confirm if it occurs using chrome or is specific to Edge ?

**Comment by andynewman10** [comment]
@darshankawar It is not specific to Edge, Chrome and Edge are both affected.

**Comment by andynewman10** [comment]
I made some good progress:

1. when a URL is not found, the `index.html` is indeed returned (I read at multiple places that this behavior was observed by some users), and has an associated MIME type of `text/html`. That's the phenomenom I was observing: `sw.dart.js` was simply not found.
2. If I use @isoos 's and @kevmoo 's `service_worker/example` project, build it, and then copy the generated `sw.dart.js` files over to the `web` folder of my project, the `sw.dart.js` is correctly found when I debug my project, is correctly identified as `text/javascript`, and the exception disappears.
3. This means I only have a build issue: somehow, my `build.yaml` file does not compile my `sw.dart` file into a JS file just like the way this is successfully [performed](https://github.com/isoos/service_worker/blob/master/example/build.yaml) in `service_worker/example`.

**Comment by andynewman10** [comment]
In my pubspec.yaml, I have the following declarations:

```
dev_dependencies:
  build_runner:
  build_web_compilers:
```
Nevertheless, `sw.dart.js`:

- is not automatically generated when I enter my debug session. Is this supposed to be this way?
- if I manually launch the generation process using `flutter pub run build_runner build`, the file gets generated in `testapp/.dart_tool/build/generated/com_example_testapp/web`, not `testapp/web`. Why? Because of this, it is not served by the web server when launching a debug session.

**Comment by darshankawar** [comment]
Thanks for the update @andynewman10 


> * is not automatically generated when I enter my debug session. Is this supposed to be this way?

Have you checked with service worker package's owner about this to know whether it is something the package need to take care of ?


> 3\. This means I only have a build issue: somehow, my `build.yaml` file does not compile my `sw.dart` file into a JS file just like the way this is successfully [performed](https://github.com/isoos/service_worker/blob/master/example/build.yaml) in `service_worker/example`.

I suggest you raise this in package's repo to know if this need to be addressed in the package itself or in web framework here.
