### ISSUE TITLE
How do Open screen in new Tab in flutter web

### ISSUE THREAD

**Issue by ahmed-raza-92** [flutter/flutter#145451]
How Can I  Open the flutter screens in new tab on some action button click. 
I am struggling with this and tried a lot of solutions but none of them worked for me.

**Comment by YukiAttano** [comment]
Theoretically speaking exactly like you would in a native Web environment. 
You have to use deep links, for example with the GoRouter Package.
Then you can open your own page with the launch_url Package.

I am not sure how session data is handled. For example: Authorization might being lost between this two instances.

**Comment by ahmed-raza-92** [comment]
I tried working with that too. But After navigating to other screen it immediately navigates back to previous screen. This is what I was using before.

`        html.window.open('/#/external_screen',"_blank");
`

And Now I am using the deep linking. Both are producing the same results.

**Comment by darshankawar** [comment]
@ahmed-raza-92
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a support question rather than a bug report or feature request.
