### ISSUE TITLE
Impeller Image Decoder causing `EXC_BAD_ACCESS` for some production users

### ISSUE THREAD

**Issue by ggirotto** [flutter/flutter#145462]
### Steps to reproduce

This is tricky because I wasn't able to reproduce the issue yet. The most I can give is the stacktrace for the exceptions we have in production. Currently it only affected iOS users with the exception:

```
EXC_BAD_ACCESS
Exception 1, Code 1, Subcode 0 > Attempted to dereference null pointer.
```

And based on the stacktrace it seems something related with Impeller memory allocation. Here's the top the stacktrace crash:

<details>
<summary>Stacktrace</summary>

```
OS Version: iOS 17.3.1 (21D61)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: SEGV_NOOP
Crashed Thread: 10

Application Specific Information:
Exception 1, Code 1, Subcode 0 >
Attempted to dereference null pointer.

Thread 10 Crashed:
0   Flutter                         0x107645c10         flutter::ImpellerAllocator::allocPixelRef (image_decoder_impeller.cc:583)
1   Flutter                         0x107641c0c         [inlined] SkBitmap::tryAllocPixels (SkBitmap.cpp:217)
2   Flutter                         0x107641c0c         [inlined] flutter::ImageDecoderImpeller::DecompressTexture (image_decoder_impeller.cc:216)
3   Flutter                         0x107641c0c         [inlined] flutter::ImageDecoderImpeller::Decode::lambda::operator() (image_decoder_impeller.cc:514)
4   Flutter                         0x107641c0c         [inlined] std::_LIBCPP_ABI_NAMESPACE::__invoke[abi:v15000]<T> (invoke.h:403)
5   Flutter                         0x107641c0c         [inlined] std::_LIBCPP_ABI_NAMESPACE::__invoke_void_return_wrapper<T>::__call<T> (invoke.h:488)
6   Flutter                         0x107641c0c         [inlined] std::_LIBCPP_ABI_NAMESPACE::__function::__alloc_func<T>::operator()[abi:v15000] (function.h:185)
7   Flutter                         0x107641c0c         std::_LIBCPP_ABI_NAMESPACE::__function::__func<T>::operator() (function.h:359)
8   Flutter                         0x10739142c         [inlined] std::_LIBCPP_ABI_NAMESPACE::__function::__value_func<T>::operator()[abi:v15000] (function.h:512)
9   Flutter                         0x10739142c         [inlined] std::_LIBCPP_ABI_NAMESPACE::function<T>::operator() (function.h:1187)
10  Flutter                         0x10739142c         fml::ConcurrentMessageLoopDarwin::ExecuteTask (concurrent_message_loop_factory.mm:17)
11  Flutter                         0x10738ab50         [inlined] fml::ConcurrentMessageLoop::WorkerMain (concurrent_message_loop.cc:101)
12  Flutter                         0x10738ab50         [inlined] fml::ConcurrentMessageLoop::ConcurrentMessageLoop::lambda::operator() (concurrent_message_loop.cc:20)
13  Flutter                         0x10738ab50         [inlined] std::_LIBCPP_ABI_NAMESPACE::__invoke[abi:v15000]<T> (invoke.h:403)
14  Flutter                         0x10738ab50         [inlined] std::_LIBCPP_ABI_NAMESPACE::__thread_execute[abi:v15000]<T> (thread:284)
15  Flutter                         0x10738ab50         std::_LIBCPP_ABI_NAMESPACE::__thread_proxy[abi:v15000]<T> (thread:295)
16  libsystem_pthread.dylib         0x3ff0ee4d0         _pthread_start
```

</details>

Can it be related with https://github.com/flutter/flutter/issues/144565 which was fixed in the latest Flutter hot fix?

Full Stacktrace file:

[stacktrace.txt](https://github.com/flutter/flutter/files/14666157/stacktrace.txt)

### Expected results

The memory is successful allocated

### Actual results

Impeller crashes and the app as well

### Code sample

Not code sample because wasn't able to reproduce it locally yet.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

This issue is happening in production, not on my local machine. The Flutter version used to compile this production applications that are facing the crash is `3.19.2`

**Comment by danagbemava-nc** [comment]
Hi @ggirotto, I believe this may have been fixed by https://github.com/flutter/engine/pull/50787 and is similar to https://github.com/flutter/flutter/issues/138897

Would you be able to provide a minimal sample so that we can confirm this? 

Also, can we get the devices that have experienced the crash so far?

**Comment by ggirotto** [comment]
Hey @danagbemava-nc thanks for the quick response.

Unfortunately I don't know how to reproduce this issue, I just captured it from our crash tools. It seems similar to the issue you linked, which is already fixed in the engine main branch. Do you know what's the expected version that will include this fix?

About the devices we have:

- iPhone XR iOS 16.1.2
- iPhone SE 2nd Generation iOS 16.1.1
- iPhone SE 2nd Generation iOS 17.3.1
- iPhone XR iOS 17.3.1
- iPhone XR iOS 17.0.3
- iPhone XR iOS 16.1.1
- iPhone SE 2nd Generation iOS 16.6.1
- iPhone X iOS 16.7.5

**Comment by danagbemava-nc** [comment]
Hi @ggirotto, the tag seems to indicate that it was added in 3.20, which likely means it should be in beta at this point (beta is now 3.21) which likely means it might be in the next major stable version. 

Considering we don't have a way to reproduce the issue and there's a speculative fix, I'll be closing this issue for now. If you find a way to reproduce the issue, please let us know so that we can confirm whether or not this has really been fixed. 

Thank you
