### ISSUE TITLE
roll_dev.dart always makes dev channel match master ToT

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14540]
## Steps to Reproduce

```
git pull upstream master
git reset --hard <dev_commit_older_than_tot>
pushd dev/tools; pub get; popd
bin/cache/dart-sdk/bin/dart dev/tools/lib/roll_dev.dart --increment=z
```

Now look at https://github.com/flutter/flutter/releases, and you'll see that the most recent release, which you just created, is pointed to the most recent commit on master, **not** `<dev_commit_older_than_tot>`.

/cc @Hixie

**Comment by Hixie** [comment]
Apparently I forgot to update our instructions when I added --commit. I've updated them to say to run:

```
$ git fetch upstream
$ git checkout master
$ git reset --hard # careful, this will delete any local edits
$ git clean -xffd # careful, this will delete any files not in version control
$ git pull --rebase
$ flutter # downloads dart, needed below
$ pushd dev/tools; bin/cache/dart-sdk/bin/pub get; popd
$ bin/cache/dart-sdk/bin/dart dev/tools/lib/roll_dev.dart --increment=z --commit=<hash>
```

...but we really should just integrate this into our roll script.

**Comment by tvolkert** [comment]
Sounds good.  Closing.

**Comment by MichaelSowah** [comment]
has a new roll be done?

**Comment by tvolkert** [comment]
I've updated the `v0.0.23` and `v0.0.24` releases to reflect the versions that they were intended to be.  I didn't update `HEAD:dev` since it could cause confusion for those who are tracking the `dev` branch.

That leaves `HEAD:dev` having been rolled yes, but to a *slightly* newer commit than was intended.  The next roll will not have this problem.

**Comment by MichaelSowah** [comment]
@tvolkert can you please help me understand what you meant by " I didn't update HEAD:dev" and "That leaves HEAD:dev having been rolled yes, but to a slightly newer commit than was intended. The next roll will not have this problem."

**Comment by tvolkert** [comment]
`HEAD:dev` is the commit to which the "dev" branch points.  That pointer has been updated to point to https://github.com/flutter/flutter/commit/4ae1b5f41593f067d52f2ec239b87b00776bc4a8.  This means it's been rolled to something new (compared to what it was a day ago), but because of this issue, it was rolled to the wrong commit -- it was intended to be rolled to https://github.com/flutter/flutter/commit/788f01f90dfa49642188a65ecda708ac0f4071d7.  Practically speaking, this isn't a big deal.

Once we roll `v0.0.25`, `HEAD:dev` will be roll again, this time to the correct commit.

**Comment by MichaelSowah** [comment]
thanks
