### ISSUE TITLE
[go_router] Something is wrong with Go_Router 13.0.0 migration guide

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#145402]
### Steps to reproduce

Open
https://docs.google.com/document/d/1FRdW_p29zH0I3KEMQKW_QMMN7owiQ5Wx-PUhhZpehSg/edit

### Expected results

Consistent document

### Actual results

<img width="1233" alt="image" src="https://github.com/flutter/flutter/assets/6721286/605875d6-21e4-4abc-9018-7b0dce82a584">

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
The previous version's migration guides (12.0, 11.0) seems to be fine, but the latest one seems to be showing as mentioned above.

**Comment by mwoelk** [comment]
Simply looks like the google doc was shared as read/write instead of readonly

**Comment by mwoelk** [comment]
Simply looks like the google doc was shared as read/write instead of readonly and some people wreaked havoc on it 
Maybe @chunhtai as the author can re-upload and share with read-only permissions to fix it.

**Comment by chunhtai** [comment]
change to read-only
