### ISSUE TITLE
Glyph Atlas Padding Not Correctly Handled in `typographer_context_stb.cc`.

### ISSUE THREAD

**Issue by johnoneil** [flutter/flutter#145421]
### Steps to reproduce

This is more of an analytical code issue, but the issue is visible in generated glyph atlases using the `stb` implementation.

To reproduce:

1. Use the `stb` text atlas implementation.
2. In come situations characters will appear like they have their bottoms cut off.

Using `renderdoc` on the subsequent binary, one can see the Glyphs in the atlas are not laid out correctly in relation to the padding between glyphs.

### Expected results

Glyphs shouldn't be cut off along the bottom.

### Actual results

Glyphs sometimes cut off along their bottom.

### Code sample

I believe the issue is in the following section of code:

<details open><summary>Code sample</summary>

```dart
   if (!has_color || DISABLE_COLOR_FONT_SUPPORT) {
     stbtt_MakeGlyphBitmap(typeface_stb->GetFontInfo(), output,
                          location.size.width - kPadding,
                          location.size.height - kPadding,
                           bitmap->GetRowBytes(), scale_x, scale_y, glyph.index);
```

</details>

Note the `- kPadding`.

At this point, the `location` used is the entry describing the glyph in the atlas, but it does not include padding, so the subtraction of `kPadding` is not necessary.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Here's a screenshot of some text rendered with the incorrect code:
![Screenshot from 2024-03-19 11-16-01](https://github.com/flutter/flutter/assets/2950232/b6c3cfb6-2c0b-430a-b58e-fea4769493fe)

And a screenshot of some glyphs in the atlas via renderdoc. Note there is double the paddng between characters and some characters (like the "i") are clipped along one side.

![Screenshot from 2024-03-19 11-17-09](https://github.com/flutter/flutter/assets/2950232/14ca8f84-bf6c-4a2f-9ce8-f9173874ba53)

Correcting the code the text is improved (though in our case still not strictly correct)

![Screenshot from 2024-03-19 11-19-44](https://github.com/flutter/flutter/assets/2950232/2dc85902-6629-4a65-b2c6-891838ecbe61)

And lastly, examining the glyph atlas using `renderdoc` with a fix in place, the layout of glyphs is improved:
 
![Screenshot from 2024-03-19 11-10-54](https://github.com/flutter/flutter/assets/2950232/d9507529-2288-4780-b6b1-576c2f0b776f)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Keeping the issue open and labeling for team's input / tracking.

**Comment by johnoneil** [comment]
Thanks again for looking at this @darshankawar.

CC'ing @bdero and @chinmaygarde on this.

I provided some of the original `stb` support so I believe this silly discrepancy was just my fault.

I'm tracking one more bug in the same `typographer_context_stb.cc` related what seems like a bug in `stb` (the scaling it provides for glyphs appears to be wrong) but I may file that separately.

**Comment by johnoneil** [comment]
Oh right, I might just put op a fix for this in the next couple of days. It's super trivial and I believe well justified.

**Comment by johnoneil** [comment]
Fix merged so I believe this can be closed.
