### ISSUE TITLE
The flutter inspector shows nothing

### ISSUE THREAD

**Issue by Lonti6** [flutter/flutter#145461]
### Steps to reproduce

1) Run Applicatioin in Android Studio/Intellij idea/VS Code
2) Open Flutter Inspector(Widget Inspector in VS Code)

The inspector's window is empty and shows nothing
Android Studio/Intellij idea:
![image](https://github.com/flutter/flutter/assets/72629247/4a7f62e0-1fa9-41fc-92a0-29a998e9977b)

VS Code:
![image](https://github.com/flutter/flutter/assets/72629247/faceaf3f-8da8-426f-b07a-c123487eef3e)

The problem is observed not only on the Linux build, but also on android, web

### Actual results

The flutter inspector shows nothing in Android Studio, Intellij idea, VS Code

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on Linux Mint 21 5.15.0-71-generic, locale
    ru_RU.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[!] Android Studio (version 2023.1)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] VS Code (version 1.78.0)
[✓] Connected device (2 available)
[✓] Network resources


```

</details>

**Comment by darshankawar** [comment]
@Lonti6 
I verified on latest stable with Android Studio which shows inspector widget / details properly:

<img width="475" alt="Screenshot 2024-03-20 at 6 32 08 PM" src="https://github.com/flutter/flutter/assets/67046386/25a25a79-428a-4b07-82d7-33075ff3e81b">

<img width="491" alt="Screenshot 2024-03-20 at 6 31 11 PM" src="https://github.com/flutter/flutter/assets/67046386/79cef58b-879e-436e-b105-e49082aa2888">


You are on older version of stable. Please upgrade and try again. Most probably you are hitting https://github.com/flutter/devtools/issues/4388.

Closing from here.
