### ISSUE TITLE
Popscope doesn't work on flutter web 

### ISSUE THREAD

**Issue by eduardohr-muniz** [flutter/flutter#145440]
### Steps to reproduce

popScope in project Flutter web, click back 

### Expected results

I hope he respects popscope and doesn't return to the page

### Actual results

dont work

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output
❯ flutter doctor -v
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [versÆo 10.0.22631.3296], locale pt-BR)
    • Flutter version 3.19.3 on channel stable at C:\Users\eduar\.puro\envs\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (13 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\eduar\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\eduar\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\eduar\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34701.34
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\eduar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22631.3296]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
    • All expected network resources are available.

• No issues found!

</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@eduardohr-muniz 
Can you provide `flutter doctor -v` and a complete minimal but runnable code sample that shows actual behavior against expected you are looking for ?

**Comment by eduardohr-muniz** [comment]
Good morning, I'm sorry I forgot to add it.

consider done

**Comment by darshankawar** [comment]
> and a complete minimal but runnable code sample that shows actual behavior against expected you are looking for ?

And this as well.
