### ISSUE TITLE
[flutter_tools] flutter drive should expose --reporter and --file-reporter CLI options

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#145499]

**Comment by MarkOSullivan94** [comment]
Would really love this! 

We are currently making use of --file-reporter for our Dart backend tests and helps us generate a neat test report and to be able to add the same kind of results for the apps would be perfect

**Comment by christopherfujino** [comment]
I failed in my attempt to do this in https://github.com/flutter/flutter/pull/145502.

**Comment by matanlurey** [comment]
I synced with @christopherfujino - I'm pretty sure making this the _default_ is a breaking change (while `dart test/foo_test.dart` and `dart test test/foo_test.dart` are _similar_, they are not the _same_ - for example `dart test` no longer allows providing command-line arguments among other things).

I am going to take a shot at adding this behind a flag, i.e. `--use-pkg-test`. It will initially be hidden, and probably not advertised much as we might decide there is no path to enable this by default or the cost of having two runtime modes is too high.

**Comment by matanlurey** [comment]
Update: Apparently this _already works_, on accident. I'll document it for now.
