### ISSUE TITLE
[infra + release] since 03/18 12:00 Linux_android hot_mode_dev_cycle_linux__benchmark consistently fail 

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#145486]
the [target failed](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20hot_mode_dev_cycle_linux__benchmark/9216/overview) on release branch.

Looking through the [target history](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20hot_mode_dev_cycle_linux__benchmark), it seems like this target had been failing since 03/18.

Would be great if some infra expert could help take a look. Thank you!

**Comment by godofredoc** [comment]
The bot configuration the test was using was added for a manual test and was not supposed to block runs in presubmit.

**Comment by godofredoc** [comment]
The fix is to CP this change https://github.com/flutter/flutter/commit/71c1aba10bf2c0855b05ca7ac0253c460a1c35b6
