### ISSUE TITLE
Firebase for Flutter/Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1454]
Let's use Firebase as an example of how to connect third-party service to Flutter!

- [x] Mojo implementation/binding for Android
- [x] flutter command-line tool makes it easy to integrate this service
- [x] Docs
- [x] Example

**Comment by sethladd** [comment]
cc @collinjackson for this tracking issue

**Comment by abarth** [comment]
@collinjackson Is there more that needs to be done here that's blocking the hackathon dry run?

**Comment by collinjackson** [comment]
We don't have 100% API coverage yet, but everything called for in the codelab should work.

Docs are at https://www.dartdocs.org/documentation/firebase/latest/firebase/firebase-library.html

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1031. Any further collaboration will be done there.
