### ISSUE TITLE
Ability to take photos using volume buttons

### ISSUE THREAD

**Issue by LastxTemplar** [flutter/flutter#145526]
### Use case

By default, the camera on iOS and Android allow the user to take pictures by tapping the hardware volume buttons, it would be a good addition to have this feature implemented for this package too.

It is possible to easily add this feature by using onKey events and listen for the volume hardware button, but that only works for Android, as far as I am aware, iOS does not easily allow for overriding the hardware volume buttons, there are ways to listen to the volume changes but that still shows the volume change slider on the screen.

### Proposal

Other packages such as image_picker already support this feature, might be worth looking into how it was implemented there.

**Comment by stuartmorgan** [comment]
`camera` provides a programatic interface to camera functionality; implementing user-level affordances for triggering those API calls is the responsibility of plugin clients.

Closing as out of scope.
