### ISSUE TITLE
[google_sign_in] Change the name of the "Runner" app in the iOS dialog

### ISSUE THREAD

**Issue by rnaufal32** [flutter/flutter#145577]
Hi, I want to change the project name from "Runner" to my own project name. How can I do that?

![Simulator Screenshot - iPhone 15 Plus - 2024-03-22 at 07 46 43](https://github.com/flutter/flutter/assets/33546066/1fa37ecd-19ac-416e-af13-e0dd1c503bf0)

**Comment by darshankawar** [comment]
@rnaufal32 
Check https://github.com/flutter/flutter/issues/9767#issuecomment-1533771721 and https://github.com/flutter/flutter/issues/94250#issuecomment-982320278 and see if they help to answer your question.

Also, your question is better suited for support channels like StackOverflow, so please ask the same there or find any existing ones.
Closing from here.
