### ISSUE TITLE
[Proposal] Allow disabling the scaling animation of the FloatingActionButton

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#145585]
### Use case

Currently when the FloatingActionButton widget is added or removed from a Scaffold, it animates its transition.

We can control parts of this transition, using the `FloatingActionButtonAnimator`. By default this uses the scaling animator from the framework itself.

However, if I want to disable both the rotation and scaling animations with the following animator subclass:

```dart
class _NoAnimationFloatingActionButtonAnimator extends FloatingActionButtonAnimator {
  const _NoAnimationFloatingActionButtonAnimator();

  @override
  Offset getOffset({required Offset begin, required Offset end, required double progress}) {
    return end;
  }

  @override
  Animation<double> getRotationAnimation({required Animation<double> parent}) {
    return const AlwaysStoppedAnimation(1.0);
  }

  @override
  Animation<double> getScaleAnimation({required Animation<double> parent}) {
    return const AlwaysStoppedAnimation(1.0);
  }
}
```

and I pass an instance to the `floatingActionButtonAnimator` of a Scaffold, I still see a scale transition on the FAB.

### Proposal

Allow disabling both the scaling and rotation transition, using the aforementioned `FloatingActionButtonAnimator`, either through a subclass, or by providing a `FloatingActionButtonAnimator.noAnimation` constant.

**Comment by HansMuller** [comment]
@TahaTesser - Maybe this could be handled by giving FAB an AnimationStyle parameter?

**Comment by TahaTesser** [comment]
> @TahaTesser - Maybe this could be handled by giving FAB a pair of AnimationStyle parameters? Or maybe just a fix for the way FloatingActionButtonAnimator is handled is what's needed.

This would be for Scaffold. floatingActionButtonAnimator
I already have a fix, just need tests.

**Comment by TahaTesser** [comment]
floatingActionButtonAnimator is bit niche for AnimationStyle. Since this is implemented and handled by Scaffold.

**Comment by HansMuller** [comment]
I was trying to imply FAB.scaleAnimationStyle and FAB.rotationAnimationStyle. But I think you're right. The animations are a feature of the Scaffold, not FAB. Maybe we just have a bug here?

**Comment by TahaTesser** [comment]
Yep, the bug is default entrance and exit animation curves are hard coded
combined with custom AlwaysStopAnimation curve, as a result you still get defaults curves.

My fix will try to override the default entrance and exit animations so we could disable the entrance and exit animations entirely with new FabButtomAnimator.noAnimation
