### ISSUE TITLE
Showing error packages not found, even though they are added and working perfectly fine

### ISSUE THREAD

**Issue by iamzaidsoomro** [flutter/flutter#145518]
### Steps to reproduce

1. I was developing UI on my Flutter project, which worked perfectly fine. I closed my IDE (VS Code), and the next morning I opened my project it showed me Target URI doesn't exists (for dependencies only).
2. I ran flutter clean, flutter pub get, but it showed me the dependencies I haven't even used.
3. I tried gradlew clean, but it didn't help either
4. Actually my app is working perfectly fine, it is using the features provided by those packages as well (for example GetX routes), but still it is showing errors in the IDE (in both VS Code and Android Studio)

### Expected results

I want these false error indications to be removed.

### Actual results

It shows these errors, I am attaching the screenshot below

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1552" alt="Screenshot 2024-03-21 at 11 04 27 AM" src="https://github.com/flutter/flutter/assets/75375280/14a311a6-f785-4f38-9c88-38b837936aa9">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 11.7.10 20G1427 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @iamzaidsoomro, this seems like it might be a cache issue. Can you try clearing your IDE caches and maybe your flutter pub cache to see if you still experience this issue?

**Comment by iamzaidsoomro** [comment]
Hey, thanks for considering my issue. I am trying to run flutter pub get from the external terminal, still, it is still not getting the dependencies. I have tried in Android Studio, VS Code, cleared VS Code Cache, and cleaned the Flutter cache, but the same issue persists. What to do?

I have downloaded and setup the fresh copy of flutter as well.

**Comment by danagbemava-nc** [comment]
Can you check the directory your project is in to see if it is accessible to flutter and your current user?

**Comment by danagbemava-nc** [comment]
You might have to reach out to the maintainers of the plugins for IDEs for assistance with that since your code appears to be working as expected. 

The things I can think of that may influence this are your local cache and maybe the directory you've placed the project in. 

Do you still have this issue with a new project?

**Comment by iamzaidsoomro** [comment]
It is showing same error in all the IDEs, it must be an issue from Flutter side. I have upgraded my flutter just now with the latest stable version, still the issue persists.

**Comment by danagbemava-nc** [comment]
What version of flutter did you upgrade from? I have migrated projects from older versions of flutter to the latest stable and I haven't encountered this issue. 

Can you make sure you're using the latest version of your IDE plugins? You may also want to try restarting your machine so that any deep caches are cleared and try again to see if you still experience this issue.

**Comment by iamzaidsoomro** [comment]
I resolved my issue, there was some permission issues in Mac, it was unable to read from the pub-cache because it didn't had read/write permissions, so I ran this command:

`sudo chown -R $(whoami) /Users/zaidahmed/.pub-cache/ ` (replace zaidahmed with your username)
