### ISSUE TITLE
Passing  map style with weight or lightness, returns Google Map Style Error on Web

### ISSUE THREAD

**Issue by PauloAlves311** [flutter/flutter#145596]
### Steps to reproduce

Blank Project.
Flutter 3.19.3 
google_maps: ^7.1.0

```
> GoogleMap(
> style: GoogleMapStyle.darkMode2
> )
```

GoogleMapStyle.darkMode2:
`r'[{"featureType":"all","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"lightness":"100"}]},{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#643a8e"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#271437"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry","stylers":[{"saturation":"100"},{"lightness":"97"},{"gamma":"1.50"},{"weight":"3.38"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":17},{"weight":1.2}]},{"featureType":"administrative","elementType":"labels.text","stylers":[{"lightness":"14"},{"gamma":"1.77"},{"weight":"0.01"}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#2a0338"}]},{"featureType":"landscape","elementType":"geometry.fill","stylers":[{"visibility":"on"}]},{"featureType":"landscape","elementType":"geometry.stroke","stylers":[{"weight":"3.93"},{"lightness":"100"},{"hue":"#ff0000"},{"visibility":"on"}]},{"featureType":"landscape","elementType":"labels.text.fill","stylers":[{"weight":"2.61"},{"lightness":"100"}]},{"featureType":"landscape","elementType":"labels.text.stroke","stylers":[{"saturation":"-55"},{"lightness":"31"},{"gamma":"3.70"},{"weight":"3.89"},{"invert_lightness":true}]},{"featureType":"landscape.natural","elementType":"geometry","stylers":[{"lightness":"-35"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"lightness":"5"},{"color":"#271437"},{"visibility":"off"}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#71548f"},{"lightness":17},{"visibility":"on"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#311e44"},{"lightness":"14"},{"weight":"1.00"},{"gamma":"0.00"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#7243a0"},{"lightness":"-3"},{"weight":"1"},{"visibility":"on"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"visibility":"on"},{"color":"#7c5a9d"},{"weight":"1"}]},{"featureType":"road.local","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"weight":"1"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"lightness":19},{"hue":"#ff0000"}]},{"featureType":"transit","elementType":"geometry.fill","stylers":[{"color":"#2e226a"}]},{"featureType":"transit.line","elementType":"geometry.fill","stylers":[{"color":"#3b3364"}]},{"featureType":"transit.line","elementType":"geometry.stroke","stylers":[{"color":"#3b3364"}]},{"featureType":"transit.station","elementType":"geometry.fill","stylers":[{"lightness":"-6"}]},{"featureType":"transit.station.airport","elementType":"geometry.fill","stylers":[{"lightness":"13"},{"color":"#4225aa"}]},{"featureType":"transit.station.bus","elementType":"geometry","stylers":[{"lightness":"77"}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":"71"},{"gamma":"1.50"},{"saturation":"-13"},{"weight":"0.01"}]},{"featureType":"water","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#c3b7c9"}]}]',`
 

`Error "TypeError "100: type "String" is not a subtype of type 'num?' `

This relates to the first "lightness: 100" that appears. I can remove this first one, and the next one will show an error. All of them will complain about String not being num OR int.

For this style to work, I need to remove EVERY instances of the weight or lightness.

Works perfectly on https://mapstyle.withgoogle.com/

![mapStyle](https://github.com/flutter/flutter/assets/40123939/09147af6-2753-4f56-b2d2-0ed379921ff5)

**Comment by darshankawar** [comment]
@PauloAlves311 
Can you provide complete runnable reproducible code sample and platform on which you are seeing this error ?
I tried with plugin example but wasn't able to replicate.

**Comment by PauloAlves311** [comment]
@darshankawar I think I provided the minimum reproducible code. But I just noticed this is actually working on android and probably iOS too. 

I wasn't aware, before submitting this issue, but I can only reproduce this issue on the web, tested on Chrome and Edge

**Comment by darshankawar** [comment]
@PauloAlves311 Thanks for the update.
Check https://github.com/flutter/flutter/issues/129995 and https://github.com/flutter/flutter/issues/129995#issuecomment-1846482843 to see if it helps in your case or not.

**Comment by PauloAlves311** [comment]
@darshankawar Thank you for sharing, but it seems to be a different error, as the error there was showing "For Development Purposes Only" and that is when the API key is invalid. However in my case, I have billing enabled so it should work. Unless I need to allow map styles somewhere specifically?

But I dont think it has to do with the API but with the google_maps_flutter plug-in specifically, as it threw a red screen error, complaining about variable types num and int.

**Comment by darshankawar** [comment]
Thanks for the update. I tried using the style you provided in plugin example, replaced it with `night_mode.json` as being used in it which is being fetched in `maps_ui.dart` file as shown below:

https://github.com/flutter/packages/blob/main/packages/google_maps_flutter/google_maps_flutter/example/assets/night_mode.json

https://github.com/flutter/packages/blob/0f14d4f2105f5618a4fb61eb249f19d31ad611c1/packages/google_maps_flutter/google_maps_flutter/example/lib/map_ui.dart#L256

Please check the same at your end.

**Comment by PauloAlves311** [comment]
@darshankawar The night_mode.json that you provided does not seem to pass any weight or lightness parameters in the stylers, which is what seems to be causing my errors.

Can you try with the style I provided?

**Comment by darshankawar** [comment]
Thanks for the update @PauloAlves311 
Actually I had used your json inside `night_mode.json` that you can try and see if it helps or not.
