### ISSUE TITLE
Not's Returning Anything the loop

### ISSUE THREAD

**Issue by unaisshemim** [flutter/flutter#145591]
### Steps to reproduce

List<String>images=["img1","img2"]
Container(
                    width: 60,
                    height: 60,
                    decoration: BoxDecoration(
                      shape: BoxShape.rectangle,
                      borderRadius: BorderRadius.circular(6),
                      color: Colors.grey[200],
                      image: images.isNotEmpty
                          ? DecorationImage(
                              image: NetworkImage(images.first),
                              fit: BoxFit.cover,
                            )
                          : null,
                    )),

### Expected results

it should return all the images with container

### Actual results

it should return all images with container

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

List<String>images=["img1","img2"]
Container(
                    width: 60,
                    height: 60,
                    decoration: BoxDecoration(
                      shape: BoxShape.rectangle,
                      borderRadius: BorderRadius.circular(6),
                      color: Colors.grey[200],
                      image: images.isNotEmpty
                          ? DecorationImage(
                              image: NetworkImage(images.first),
                              fit: BoxFit.cover,
                            )
                          : null,
                    )),

**Comment by huycozy** [comment]
Hi @unaisshemim 
When opening an issue, please try to fill in the appropriate information in the fields indicated in the template so we can verify it correctly.

More specifically, please provide the following information:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Actual results
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)
