### ISSUE TITLE
Stderr inserted into `--file-report` file when using `flutter test`

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#145553]
Running `SHARD=framework_tests SUBSHARD=misc dart dev/bots/test.dart | tee output.txt` generates the following outputs:

[metrics.json](https://github.com/flutter/flutter/files/14705008/metrics.json)
[output.txt](https://github.com/flutter/flutter/files/14705010/output.txt)

There are two issues:
* Error messages from stderr are being added to the metrics.json file.
* Unicode characters are not being processed correctly.

**Comment by godofredoc** [comment]
@christopherfujino FYI

**Comment by godofredoc** [comment]
Took a look and this is an error in package:test. Whenever a print function is used within a test the printed string is added as as string of \u0000 characters to the report file.

**Comment by godofredoc** [comment]
@whesse do you know what is the best place to report this bug?

**Comment by whesse** [comment]
I would file an issue on the test package, at https://github.com/dart-lang/test.

**Comment by christopherfujino** [comment]
Closing this as it doesn't sound like a tool bug
