### ISSUE TITLE
Make const work with LayoutBuilder Widget

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#145537]
### Use case

I tried to use const with responsive widgets like using the `LayoutBuilder` widget or using if statement with `MediaQuery.of(context).size.width` but these const widgets still rebuild. I check it by using print in the `Widget build(BuildContext context)`
I think it is good to make const work for the responsive widget. Many widgets are used in many screen sizes.
For an example:
```
  @override
  Widget build(BuildContext context) {
    const testWidget = Test();
    return LayoutBuilder(builder: (context, constraints) {
      return constraints.maxWidth > 500 ? const Column(children: [testWidget]) : const Row(children: [testWidget]);
    });
```
```
class Test extends StatelessWidget {
  const Test({super.key});

  @override
  Widget build(BuildContext context) {
    print('rebuild');
    return const SizedBox();
  }
}
```
The console will print rebuild every time you change screen size between 500 units.

### Proposal

Make the `const` widget work with `LayoutBuilder` or other responsive widgets.

**Comment by goderbauer** [comment]
This all appears to be working as intended. A widget is only a configuration object that the framework inflates into an element to build the element tree. When you switch from <500 to >500 you are replacing the Row with a Column. For that, internally the framework tears down the element subtree rooted at the Row and builds a new element subtree rooted at a Column. As part of that, a new Element for the Test widget configuration is built. If you want to re-use the same Element, you need to manually move it from being a child of the Row to being a child of the Column. You can do that by giving the Test widget a GlobalKey [1].

[1] https://main-api.flutter.dev/flutter/widgets/GlobalKey-class.html
