### ISSUE TITLE
ui.Paragraph.getBoxesForRange returns List<dynamic> not List<TextBox>

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#14555]
Running flutter tests in `--preview-dart-2` mode reveals that `ui.Paragraph.getBoxesForRange` is not strong mode compliant: it is declared like this

```dart
  /// Returns a list of text boxes that enclose the given text range.
  List<TextBox> getBoxesForRange(int start, int end) native 'Paragraph_getRectsForRange';
```

but it produces `List<dynamic>` because binding layer does not know how produce `List<TextBox>`. 

In Dart 2 `List<dynamic>` is not subtype of `List<TextBox>`. Dart VM now has API that should allow binding layer to produce correctly typed list: `Dart_NewListOfType`.

`test/rendering/paragraph_test.dart` has 2 failing tests which reveal incorrect type of the list.

Tentatively assigning to @rmacnak-google who added the Dart VM API 

/cc @a-siva

**Comment by jason-simmons** [comment]
I have a prototype of this that extends Tonic's vector<T> converter to call type-specific Dart list constructor APIs.

**Comment by mraleph** [comment]
@jason-simmons Is there anything blocking landing of your prototype? Can we help somehow? 

We are going to start checking results of native functions to ensure soundness (https://dart-review.googlesource.com/c/sdk/+/40641) and these additional checks make us fail 300+ tests.

**Comment by jason-simmons** [comment]
I've been waiting for a version of Dart with this API to be rolled into Flutter and Fuchsia.  Looks like that has landed.
