### ISSUE TITLE
[flutter release] strategy on better ways to merge cherry pick PR

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#145557]
For the longest time I thought cherry pick author should be the one tuning the tests and merging the PR, but today I read https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process and realized that it says "The release engineering team will merge the cherry-pick pull request"

In this week's release https://github.com/flutter/flutter/issues/145184 and https://github.com/flutter/engine/pull/51425 were merged by me, and I had to rerun tests and stamp LGTM on one of them. However, I didn't realize https://github.com/flutter/flutter/pull/145181 was also left open as a cherry pick PR and not merged. 

Would it be possible to change the policy, so that PR authors are the one merging cherry pick PRs?

**Comment by itsjustkevin** [comment]
@XilaiZhang we have the automated cherry-pick action.  Wouldn’t we rather just write another action that adds the autosubmit label once the approved label is added?  This takes the burden off of both parties.

**Comment by XilaiZhang** [comment]
Yeah the 3 PRs aren't opened through the automated action because, one of them has a merge conflict, and the two others don't have a corresponding PR merged into main/master.

my understanding is that even if they are opened through automated cherry pick PR, if we submit based on approved status, then:
1. If author approves the bot PR, it can merge it without reviewer / TL approval
2. the tests could still be failing when approval is given, and autosubmit label would be removed.
if the cps are manually created, then it is also possible that:
3. approval is granted on cherry pick issue, but not granted on cherry pick PR. 

If we are okay with the risks, I think submitting based on approval would resolve 1 of the 3 PRs from this week. Are we good with accepting the risks (mostly the potential of skipping TL review?)

**Comment by XilaiZhang** [comment]
from triage: still better to leave to release engineer to merge. not release engineer's fault if pr missed cutoff due to failed tests. kevin will kindly help update the wiki page.
