### ISSUE TITLE
Url launcher | Apple privacy manifest for iOS 

### ISSUE THREAD

**Issue by DanielFrTB** [flutter/flutter#145525]
### Use case

Hey,

Just wanted to drop a quick note regarding url_launcher. I noticed that Apple recently published a list of requirements for third-party SDKs, and it seems like url_launcher_ios has already been updated to comply. Do you guys have any plans to do the same for url_launcher?

Thanks!

### Proposal

Comply with Apple new privacy requirements

**Comment by darshankawar** [comment]
@DanielFrTB 
I believe this is already fixed as part of https://github.com/flutter/flutter/issues/139759
Closing as this is fixed. If you disagree or think this is incorrect, write in comments and I'll reopen it.
