### ISSUE TITLE
Consider using `_bitfield_io.dart` instead of `_bitfield_web.dart` on dart2wasm

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#145540]
As of right now, the conditional import in `bitfield.dart` is based on `dart.library.js_util`, which evaluates to `true` on both JS and wasm backends. (See https://github.com/flutter/flutter/blob/5545c95df7a8ce4eaa03ce98b0d76d83aaf4ecf7/packages/flutter/lib/src/foundation/bitfield.dart#L6). However, the reason for the separate web implementation is for JS floating-point precision issues, which do not apply to wasm. We should consider using the `_bitfield_io.dart` implementation in dart2wasm, which basically means switching the conditional import to use something like `dart.library.html` or `dart.library.js` or something like that instead.

**Comment by kevmoo** [comment]
Maybe rename `_bitfield_web` to `_bitfield_js` or similar?

**Comment by jonahwilliams** [comment]
I wouldn't worry about it either way, these classes are completely unused and the ifdef only existed to get web compiling at all
