### ISSUE TITLE
camera: Android Only: CameraPreview "sometimes" displays landscape images when the screen is locked, and the user taps the "force-rotate" button while it is held in a portrait position

### ISSUE THREAD

**Issue by dw2kim** [flutter/flutter#145594]
### Steps to reproduce

1. Lock the screen
2. Toggle On the "Show Rotate Button on navigation bar" by holding auto rotate option in the quick settings panel
3. Now, run the example app for the `camera`
4. Make sure the Preview is displaying
5. Rotate the orientation
6. Tap the "Rotate" button on the navigation bar
7. Repeat 5-6 steps multiple times
8. Observe that the orientation of the Preview is not reflected sometimes.

### Expected results

The orientation of the Preview should be reflected. If the orientation of the phone was tilted to the Landscape, the "aspect" of the Preview screen should be in Landscape, and vice versa for the Portrait.

### Actual results

The orientation of the Preview is not reflected "sometimes" (quite often). If the orientation of the phone was tilted to the Landscape, the "aspect" of the Preview screen is sometimes in Portrait.

### Code sample

```
I used the Camera Plugin Example app to reproduce it.
```

### Screenshots or Video

<details open>
<summary>Video demonstration</summary>

https://github.com/flutter/flutter/assets/8919703/5c1577a3-f3bc-435e-9344-fc888d9de5ec

</details>

### Logs

<details open><summary>Logs</summary>

```console
Should be in the Video
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.3.1 23D60 darwin-arm64, locale
    en-CA)
    • Flutter version 3.13.9 on channel stable at
      /Users/daewon.kim/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (5 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/daewon.kim/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • Daewon iPhone (mobile) • 00008030-001465240160802E            • ios            • iOS 17.3.1 21D61
    • iPhone 15 (mobile)     • 4FBB2C90-238E-442B-A391-8F47F0952F3E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.3.1
      23D60 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      123.0.6312.58

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @dw2kim 
I followed the steps to replicate but was not able to see the reported behavior. I tried on Samsung S10 device running Android 12 version.
Can you provide the device details ? Also, the video you shared isn't playable.

**Comment by dw2kim** [comment]
Sure @darshankawar 

Here is the device details:
- product: Galaxy S21 5G
- model: SM-G991W
- Android 14

And here is the video recording again:

https://github.com/flutter/flutter/assets/8919703/94dac6f7-6a70-4f9f-beae-2cac775669d2

^ noticed that the first and the last rotation reproduced the bug.

**Comment by darshankawar** [comment]
> * Lock the screen
> * Toggle On the "Show Rotate Button on navigation bar" by holding auto rotate option in the quick settings panel

Thanks for the update. Are above steps related to the device itself ? I tried on S10, but not sure if I could see these settings on it.

**Comment by darshankawar** [comment]
Thanks for the update. Can you check if the same behavior occurs in native Android camera app using the rotate config you mentioned ?
