### ISSUE TITLE
iOS Crash with flutter version 3.19.2 

### ISSUE THREAD

**Issue by thomas4Bitcraft** [flutter/flutter#145593]
### Steps to reproduce

We were not able to reproduce it by now, but it affects around 15% of our users

### Expected results

No crash

### Actual results

Crash

### Code sample

<details open><summary>Code sample</summary>

```dart

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```
Crashed: com.apple.main-thread
0  Runner                         0x39de94 pb_enc_bool + 140 (pb_encode.c:140)
1  Runner                         0x39d6dc pb_encode + 544 (pb_encode.c:544)
2  Runner                         0xeda10 FIRSESEncodeProto + 60 (FIRSESNanoPBHelpers.m:60)
3  Runner                         0xf83f4 SessionStartEvent.transportBytes() + 155 (SessionStartEvent.swift:155)
4  Runner                         0xf867c @objc SessionStartEvent.transportBytes() + 4303111804 (<compiler-generated>:4303111804)
5  Runner                         0x13ca18 -[GDTCOREvent setDataObject:] + 101 (GDTCOREvent.m:101)
6  Runner                         0x13c8a8 -[GDTCOREvent copy] + 69 (GDTCOREvent.m:69)
7  Runner                         0x149104 -[GDTCORTransport sendEvent:onComplete:] + 89 (GDTCORTransport.m:89)
8  Runner                         0xf3e78 protocol witness for GoogleDataTransportProtocol.logGDTEvent(event:completion:) in conformance GDTCORTransport + 31 (GoogleDataTransport+GoogleDataTransportProtocol.swift:31)
9  Runner                         0xef550 EventGDTLogger.logEvent(event:completion:) + 52 (EventGDTLogger.swift:52)
10 Runner                         0xef5d4 protocol witness for EventGDTLoggerProtocol.logEvent(event:completion:) in conformance EventGDTLogger + 4303074772 (<compiler-generated>:4303074772)
11 Runner                         0xf656c closure #1 in SessionCoordinator.attemptLoggingSessionStart(event:callback:) + 47 (SessionCoordinator.swift:47)
12 Runner                         0xf676c closure #1 in SessionCoordinator.fillInFIID(event:callback:) + 77 (SessionCoordinator.swift:77)
13 Runner                         0xf4224 partial apply for closure #1 in FIRInstallations.installationID(completion:) + 30 (Installations+InstallationsProtocol.swift:30)
14 Runner                         0xf40e8 thunk for @escaping @callee_guaranteed (@guaranteed String?, @guaranteed Error?) -> () + 4303093992 (<compiler-generated>:4303093992)
15 Runner                         0xcd02c __49-[FIRInstallations installationIDWithCompletion:]_block_invoke + 201 (FIRInstallations.m:201)
16 Runner                         0x290f7c __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.18 + 273 (FBLPromise.m:273)
17 libdispatch.dylib              0x26a8 <redacted> + 32
18 libdispatch.dylib              0x4300 <redacted> + 20
19 libdispatch.dylib              0x129e0 <redacted> + 1056
20 libdispatch.dylib              0x125b0 _dispatch_main_queue_callback_4CF + 44
21 CoreFoundation                 0x36f9c <redacted> + 16
22 CoreFoundation                 0x33ca8 <redacted> + 1996
23 CoreFoundation                 0x333f8 CFRunLoopRunSpecific + 608
24 GraphicsServices               0x34f8 GSEventRunModal + 164
25 UIKitCore                      0x22c8a0 <redacted> + 888
26 UIKitCore                      0x22bedc UIApplicationMain + 340
27 Runner                         0xb8dc main + 8 (AppDelegate.swift:8)
28 ???                            0x1b54aedcc (Missing)
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.19.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7482962148 (3 weeks ago) • 2024-02-27 16:51:22 -0500
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
thomasbrandauer@Thomass-MBP-2 ios % cd ..
thomasbrandauer@Thomass-MBP-2 puls24-app % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.0 23A344 darwin-arm64, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by johnwiese-ms** [comment]
I am seeing the same thing. I can reproduce it on my own phone but I don't have the slightest idea how to fix it :(. 3000+ crashes in the last day.

**Comment by johnwiese-ms** [comment]
100% fails on my device (iPhone 12 Pro) every time:

<img width="781" alt="Screenshot 2024-03-24 at 10 24 34 AM" src="https://github.com/flutter/flutter/assets/54288891/920a0c3c-3fd6-4aaf-a746-0000cdd7ba3f">

**Comment by huycozy** [comment]
@thomas4Bitcraft Could you share the entire crash stack trace if any? There is not much Flutter trace that can help us investigate this further.

@johnwiese-ms Since you can reproduce the issue, could you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Also, please share the Flutter version you are seeing the issue on as well.

**Comment by johnwiese-ms** [comment]
Other info that may help.  Besides my phone I have confirmed issue on another iPhone 12 running iOS 17.4.1 and an iPhone 15 Pro Max.   The code does run fine on an iPhone 15 simulator running  17.4.

**Comment by johnwiese-ms** [comment]
Digging more into this I was told by a user that if they try running the app over and over it will start on occasion, which I have been able to also reproduce on my phone.

**Comment by thomas4Bitcraft** [comment]
@huycozy Unfortunately we can not reproduce it and only see the stacktrace in crashlytics , but we get a huge number of new errors since the update.

<img width="1268" alt="image" src="https://github.com/flutter/flutter/assets/44415527/77b26421-3452-409e-a92e-8d8992740cab">

**Comment by johnwiese-ms** [comment]
Same, already had almost 6k crashes in the last 3 days: 

![image](https://github.com/flutter/flutter/assets/54288891/909e052b-4cef-4f52-aa58-aec23027091f)

**Comment by johnwiese-ms** [comment]
for reference, before this release I was at ~97% crash-free users and 99+% crash-free sessions

**Comment by thomas4Bitcraft** [comment]
@johnwiese-ms Have you tried to update the flutter version to 3.19.4?

**Comment by johnwiese-ms** [comment]
I would like to, but despite the app being very popular (~80k users) it is still a "on my spare time" project and I started it way before null-safety and would need to spend some time changing things to get that working.  It's on my list, one of these days.

**Comment by thomas4Bitcraft** [comment]
@johnwiese-ms  I'll try that - but do not have a lot of hope this will change the current crash rate. Which flutter version are you using at the moment?

**Comment by thomas4Bitcraft** [comment]
@johnwiese-ms Just found this: https://github.com/firebase/firebase-ios-sdk/issues/12457

**Comment by johnwiese-ms** [comment]
3.7.12 right now.  Looks like I won't be able to update to the newer firebase packages without updating to the newer SDK. Trying the "revert xcode" option to see if that works for now to buy be some time.

**Comment by johnwiese-ms** [comment]
ok, reverting to xcode 15.2 worked for me. That will hold me over until I can update to the latest version of Flutter and the related Firebase packages.

**Comment by huycozy** [comment]
I'm not able to symbolize the crash trace above. Looking at https://github.com/firebase/firebase-ios-sdk/issues/12457 shared above, the stack trace seems to be similar. The last comment https://github.com/firebase/firebase-ios-sdk/issues/12457#issuecomment-2012356393 indicated that the issue could be solved on the new Firebase SDK version, see also flutterfire issue https://github.com/firebase/flutterfire/issues/12442. 

So you can try upgrading `firebase_core` as suggested at https://github.com/firebase/flutterfire/issues/12442#issuecomment-1983458392 to see if the crash still appears or not.

Otherwise, we need a more detailed log with Flutter trace to investigate this further.
