### ISSUE TITLE
Backing stores for multi-view partial repaint 

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#145522]
### Document Link

[https://flutter.dev/go/backing-stores-for-multi-view-partial-repaint](https://docs.google.com/document/d/1CPpA86BTF6JTvztmRWCeLGQoPEqX_msYMG6avdqhaFk/edit?usp=sharing)

### What problem are you solving?

Multi-view allows Flutter to display in multiple Flutter views or windows. Partial repaint allows Flutter to refresh only dirty parts of the content for a frame in order to reduce energy consumption. This article discusses a design that allows supporting partial repaint in a multi-view macOS app.

**Comment by jonahwilliams** [comment]
We don't support partial repaint on GLES or Vulkan. Only iOS mobile devices use partial repaint today (the other platform APIs are unreliable). FYI.

**Comment by dkwingsmt** [comment]
PR https://github.com/flutter/engine/pull/51722 implemented the feature to label backing stores with view IDs at creation, which is the goal of this design doc.

(It turns out that this not only helps partial repaint, but also the Windows embedder, which requires that surfaces are created associated with windows.)
