### ISSUE TITLE
Can't Develop for IOS after upgrading Flutter

### ISSUE THREAD

**Issue by harriscreativity** [flutter/flutter#14553]
IMAC Early 2009
OS X EL CAPTAIN
version: 10.11.6

[✓] Flutter (on Mac OS X 10.11.6 15G19009, locale en, channel alpha)
    • Flutter version 0.0.21 at /Users/dotcomholding/flutter
    • Framework revision 2e449f06f0 (10 days ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/dotcomholding/Library/Android/sdk
    • Android NDK at /Users/dotcomholding/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/dotcomholding/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    ✗ Flutter requires a minimum Xcode version of 9.0.0.
      Download the latest version or update via the Mac App Store.
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • HUAWEI VNS L31 • 4TE7N16615005417 • android-arm • Android 7.0 (API 24)

**Comment by xster** [comment]
cc @cbracken

**Comment by cbracken** [comment]
While there's no technical barrier to us continuing to support Xcode 8, supporting older toolchains do have a fairly high maintenance and support cost. As is, we support Xcode 9.0, 9.1, 9.2 and we continue to test upcoming Xcode betas. A lot changes between releases and each of these changes add a lot of conditional logic, unit tests, potential for bugs, and more work writing and testing for each bugfix and feature we implement.

While we don't officially support Xcode 8, it's entirely possible things still work. If you're feeling particularly daring, you could patch your own SDK to skip the version check. Keep in mind this'll likely result in git merge conflicts during updates.

**Comment by jeffhongxiao** [comment]
I changed the logic in the _checkXcodeVersion() method but still seeing the error.
is there some extra step for this trick to work?

Thanks

**Comment by cbracken** [comment]
@jeffhongxiao on first run, Flutter compiles a snapshot of the Dart code in `flutter_tools`. To cause it to be rebuilt from the latest code, you can `rm bin/cache/flutter_tools.snapshot`, then run flutter doctor.

**Comment by jeffhongxiao** [comment]
Chris, thanks for the reply. I ended up forcing to disable the check using this one-liner

-  bool get isInstalledAndMeetsVersionCheck => isInstalled && xcodeVersionSatisfactory;
+  bool get isInstalledAndMeetsVersionCheck => true || (isInstalled && xcodeVersionSatisfactory);

**Comment by cbracken** [comment]
Good to hear! Are things working alright for the most part?

**Comment by jeffhongxiao** [comment]
The button clicking app works in Simulator, so for that part, it works fine.

I'm still trying to make it work on my old iPhone4s, currently seeing an error:

    Try launching Xcode and selecting "Product > Run" to fix the problem:
      open ios/Runner.xcworkspace

looking at how to add an old SDK from [here](https://stackoverflow.com/a/39461859/3380951).

**Comment by cbracken** [comment]
Keep in mind that flutter does not yet support 32-bit armv7 iOS devices. For iOS, that means we support iPhone 5S and up running iOS 8 and later. 

flutter#2089 tracks armv7 support. 

It **is** possible to manually build an armv7 flutter binary, but it involves building the engine yourself, which definitely requires Xcode 9, which is required for us to support the iPhone X. Details at https://github.com/flutter/engine/wiki/iOS-Builds-Supporting-ARMv7.

**Comment by jeffhongxiao** [comment]
@cbracken thanks for the information. It saves me quite a bit time before i hit any wall. The only reason i am still holding on to the old iPhone 4S is that React Native still supports an [old version](https://github.com/facebook/react-native/issues/985) of ios. Will watch on #2089 for updates. thanks again

**Comment by zoechi** [comment]
@tejas786u I don't know what your comment is about. 
If you think there is a Flutter issue, please create a new issue with full information. This issue is long closed.

**Comment by Davisjy** [comment]
@tejas786u I also encountered this problem. How do you solve it?

**Comment by Ozory** [comment]
flutter run build resolved in my case

**Comment by gochev** [comment]
Sierra is no longer been able to use Flutter as well.
Keep in mind Sierra was the last version with Nvidia drivers, so many people are stuck with sierra.

I am getting 
Flutter requires a minimum Xcode version of 10.2.0 (which requires High Sierra with workaround)

I made the _checkXcodeVersion to always return true, but still same 
<img width="773" alt="Screen Shot 2020-02-06 at 5 08 28 PM" src="https://user-images.githubusercontent.com/5537142/73949623-52bbf280-4903-11ea-8803-0ea46babc5f0.png">

and yes I did rm bin/cache/flutter_tools.snapshot
is there check somewhere else as well ? I cant see it.

Thanks

**Comment by xster** [comment]
@gochev logistically it's hard for us to monitor closed bugs. Can you file a new bug specific to your issue?

**Comment by mcfriend99** [comment]
On the latest version of flutter, you can just modify the following line in `packages/flutter_tools/lib/src/macos/Xcode.dart`

```
- const int kXcodeRequiredVersionMajor = 11;
+ const int kXcodeRequiredVersionMajor = YOUR_MAJOR_VERSION_NUMBER;
```

For example if your Xcode is version 10.3.2, you want to change 11 to 10...

After this,

Run the following command from the root of your flutter installation as suggested by @cbracken 

```
rm bin/cache/flutter_tools.snapshot
```

Then run

```
flutter doctor
```

This will cause flutter_tools to be rebuilt.

You may want to restart your editor especially Android Studio to resent everything...

Voila. Hope it helps!

**Comment by samerkh** [comment]
> On the latest version of flutter, you can just modify the following line in `packages/flutter_tools/lib/src/macos/xcode.dart`
> 
> ```
> - const int kXcodeRequiredVersionMajor = 11;
> + const int kXcodeRequiredVersionMajor = YOUR_MAJOR_VERSION_NUMBER;
> ```
> 
> For example if your Xcode is version 10.3.2, you want to change 11 to 10...
> 
> After this,
> 
> Run the following command from the root of your flutter installation as suggested by @cbracken
> 
> ```
> rm bin/cache/flutter_tools.snapshot
> ```
> 
> Then run
> 
> ```
> flutter doctor
> ```
> 
> This will cause flutter_tools to be rebuilt.
> 
> You may want to restart your editor especially Android Studio to resent everything...
> 
> Voila. Hope it helps!

in my current flutter version (2.2.0) this has changed to 
```
Version get xcodeRequiredVersion => Version(12,0,1,text: '12.0.1');
```
flutter couldn't detect my iOS Simulator using ```flutter devices```, and I had to change it to
```
Version get xcodeRequiredVersion => Version(9,0,0,text: '9.0');
```
then rebuild ```flutter_tools``` and now it's working on my Xcode 9.4.1
thank you.

**Comment by TheColdVoid** [comment]
> On the latest version of flutter, you can just modify the following line in `packages/flutter_tools/lib/src/macos/xcode.dart`
> 
> ```
> - const int kXcodeRequiredVersionMajor = 11;
> + const int kXcodeRequiredVersionMajor = YOUR_MAJOR_VERSION_NUMBER;
> ```
> 
> For example if your Xcode is version 10.3.2, you want to change 11 to 10...
> 
> After this,
> 
> Run the following command from the root of your flutter installation as suggested by @cbracken
> 
> ```
> rm bin/cache/flutter_tools.snapshot
> ```
> 
> Then run
> 
> ```
> flutter doctor
> ```
> 
> This will cause flutter_tools to be rebuilt.
> 
> You may want to restart your editor especially Android Studio to resent everything...
> 
> Voila. Hope it helps!

It's work for me .Thanks
