### ISSUE TITLE
iOS Autofill Credential Provider Not Displayed Settings UI

### ISSUE THREAD

**Issue by Anish-T-GitHub** [flutter/flutter#145589]
### Steps to reproduce

Create Flutter Project
Add Autofill Credential Provider target 
Set the same app groups  main and target extension

But I created the same steps in native iOS project its working fine 

Flutter iOS apps not supporting autofill credential provider 

### Expected results

Autofill Credential Provider enabled application was displayed in Settings -> Passwords -> AutoFillPasswords Section

### Actual results

Actually I completed all steps 
but my app was not displayed in settings ui

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<img width="1460" alt="Screenshot 2024-03-22 at 6 04 23 PM" src="https://github.com/flutter/flutter/assets/135335285/90afb4bb-adf7-40b3-9bec-a68336cbb06d">
<img width="1196" alt="Screenshot 2024-03-22 at 6 04 34 PM" src="https://github.com/flutter/flutter/assets/135335285/b2cc6ad9-bcce-4d95-b1e2-cc497a0fa811">

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.77.3)
[✓] VS Code (version 1.74.0)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by huycozy** [comment]
Hi @Anish-T-GitHub 
I'm unsure which error you could have. Could you check https://github.com/flutter/flutter/issues/142136 and confirm if it assembles your case? May be also related: https://github.com/flutter/flutter/issues/135056

**Comment by Anish-T-GitHub** [comment]
I set the build phases below format and now it's working fine in AutoFillProvider Extension. Xcode 15 

<img width="1017" alt="Screenshot 2024-03-26 at 1 07 02 PM" src="https://github.com/flutter/flutter/assets/135335285/58dafe90-dfe6-4fb7-8c6e-b67097a15207">

**Comment by huycozy** [comment]
Looks like this is a duplicate of https://github.com/flutter/flutter/issues/135056.
