### ISSUE TITLE
Using a Backdrop Filter in the Flutter Gallery Example (0.0.24.1) is slow.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#14565]
This happens whenever there is a backdrop filter in effect. There are no other render target switches observed for any part of the scene.

![img_0075](https://user-images.githubusercontent.com/44085/35993655-d91de826-0cc2-11e8-99f9-5c05d9ac6dc5.PNG)

**Comment by brianosman** [comment]
Is this substantially slower than similar Android devices?

**Comment by chinmaygarde** [comment]
It is a bit better (though still not 60Hz) on the Nexus 5 which is usually less capable that the iPhone X.
![flutter_01](https://user-images.githubusercontent.com/44085/36118547-446dc006-0ff2-11e8-9e31-7738c417c319.png)

**Comment by brianosman** [comment]
Okay. Can you grab an SKP?

**Comment by chinmaygarde** [comment]
Sorry, I missed this message earlier today. The SKP is attached.
[flutter_01.skp.zip](https://github.com/flutter/flutter/files/1718317/flutter_01.skp.zip)

**Comment by brianosman** [comment]
Hmm. That SKP seems to be missing most of the content. I'm trying to reproduce the issue locally, but I don't recognize the screenshot from the gallery - do you have a modified version?

**Comment by chinmaygarde** [comment]
You can get to this scene by clicking the `Navigation` item in the `Cupertino Components` section on the main list view. I will attempt to see if I can get you a trace with more of the contents. Not sure how it can be missing from the SKP.

**Comment by brianosman** [comment]
Aha! Yeah, I just repro'd this on an iPad, and it's even worse than your device - I'm seeing almost 200 ms/frame, vs. about 20 ms/frame on a Nexus 6P. I'll investigate some more.

**Comment by cbracken** [comment]
Verified the fix -- hugely noticeable improvement! Thanks @brianosman

**Comment by sroddy** [comment]
@chinmaygarde We are using a backdrop filter to blur a full screen background image. we display a list view on top of it. scrolling is extremely laggy (<20fps) on a Nexus 5 even if the content behind the backdrop filter doesn't change at all.
