### ISSUE TITLE
[google_sign_in] Add toast when screen overlay makes sign-in dialog unresponsive

### ISSUE THREAD

**Issue by blobski** [flutter/flutter#145650]
### Use case

I am using Twilight app for Android (like f.lux on PC) which creates overlay to filter blue light.
It makes Google Sign-in dialog unresponsive.

### Proposal

In other apps (Twitch) I've seen a toast produced on unresponsive taps with warning about this issue.
![Untitled-1](https://github.com/flutter/flutter/assets/94862772/15dc2819-a81c-4623-80a0-2cab1ea51620)
Would be nice to include something like this in future releases.

**Comment by darshankawar** [comment]
@blobski 
The use case and proposal isn't clear to me. Can you provide real life example in which this case can occur ?

**Comment by blobski** [comment]
@darshankawar
When you try to Sign-In with Google and the standard Dialog asking you to Choose an account pops up it's completely unresponsive. You can't Choose account, Add another or even tap on Terms and conditions. There are no errors, log messages or anything. All you can do is tap back/outside to close Dialog.

In my case it's because I use this screen color filtering app, which purpose is to filter blue lights in the evening hours (for better sleep). This app creates system-wise screen overlay, and apparently this overlay is somehow drawing over Sign-in dialog making it unresponsive. There are probably other accessibility apps which can produce same behavior.

At first I thought it was a bug. But when another app (Twitch) proposed to install an update and In-App Update Dialog appeared (which is somewhat similar to Sign-in Dialog), I tapped Update button and nothing happened, BUT a toast with message appeared: "Looks like another app is blocking access to Google Play. Turn off any apps that might be drawing over the screen and try again". That's when I realized the problem with unresponsive Sign-in Dialog.

To observe unresponsive behavior install "Twilight: Blue light filter" app from Google Play, make sure the filter is On (you will see screen colors are a bit faded) and try to fresh Sign-in with Google (clear app data first) to see unresponsive Sign-in dialog.

**Comment by darshankawar** [comment]
Thanks for the update. Is there a way for you to check if the same behavior (overlap) occurs in native google sign-in window as well ? That way we would know if it is native related or specific to flutter's plugin.

**Comment by blobski** [comment]
It seems like it's a native issue indeed. I tested in Unity game - same result.

**Comment by darshankawar** [comment]
thanks for the update. This probably indicates native issue which need to be fixed in Android instead of in flutter which leverages native functionality. You'll probably need to report this in native repo.
Closing from here.
