### ISSUE TITLE
Native assets are not picked up during `flutter build`.

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#145638]
Seems like a regression in current main.

`flutter run -d macos` will try to build native assets.
`flutter build macos` will *not* try to build native assets

cc @dcharkes

**Comment by huycozy** [comment]
Hi @knopp, 
Could you share a sample code along with `flutter doctor -v` so I can try reproducing it on my end? Also, which Flutter version did it work on?

Maybe related issue: https://github.com/flutter/flutter/issues/129757 (Native assets support)

**Comment by knopp** [comment]
This is with recent main (638e47146d2eda8ab7f35d1329b0a66aeaa2f88c). Seems like a very recent regression. I assumed @dcharkes might now which recent changes could have caused this, if not I can do a bisect.

**Comment by dcharkes** [comment]
Thanks @knopp!

I landed a bunch of things last week, that haven't rolled into Flutter yet. I might have broken things. Working on a roll:

* https://github.com/flutter/flutter/pull/145612

**Comment by dcharkes** [comment]
@knopp I can't reproduce this locally. Can you try on the latest master if this still reproduces? Do you have a reproduction project somewhere?

`flutter create --template=package_ffi [...] && cd [...]/example && flutter build macos` and then running the executable works fine for me.

**Comment by knopp** [comment]
I can't reproduce this after https://github.com/flutter/flutter/pull/145612 anymore. Closing.
