### ISSUE TITLE
Semantics traversal order needs to be implemented on iOS engine.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#14570]
The Semantics traversal order API has been implemented in the framework and on Android, but the iOS engine work still needs to be completed.

The engine now receives, for each semantics node, a "`nextNodeId`" which is the next node in the traversal order.  On Android this calls [`setTraversalBefore`](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.html#setTraversalBefore(android.view.View)) to indicate the order, but on iOS there isn't a similar facility.

The place in the code that orders accessibility nodes is [here](https://github.com/flutter/engine/blob/c210d62a6c38df62c2f3b01053b50603f4fd74dd/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm#L431).  It currently orders them geometrically (upper left to lower right), but we don't want that (it doesn't respect directionality, or the custom ordering API in the framework).

In addition, it orders them only on the basis of ordering the children of each node, and not globally: the custom ordering is completely orthogonal to the widget hierarchy, and could order any semantics node after any other.

I think that an approach similar to the one given in [stackoverflow here](https://stackoverflow.com/questions/13279498/change-order-of-read-items-with-voiceover) is a possible solution, but I don't know enough iOS development to know for sure.

This is part of implementing #12187

**Comment by gspencergoog** [comment]
It seems like what you might want to do is to implement a top-level view that handles:

```objc
-(BOOL)isAccessibilityElement
-(NSInteger)accessibilityElementCount
-(id)accessibilityElementAtIndex:(NSInteger)index
-(NSInteger)indexOfAccessibilityElement:(id)element
-(void)didAddSubview:(UIView *)subview
-(void)willRemoveSubview:(UIView *)subview
```
And when it adds a subview, it traverses _all_ of the subviews, not just the immediate children, and order them by their `nextNodeId`.  You'd have to disable this API in the subviews, however, and I'm not sure if we'd get the right behavior then (or exactly how to do that).

And I may just be speaking gibberish. :-)

**Comment by Hixie** [comment]
@yjbanov I assigned this to you based on rumours that you wanted to fix this.

**Comment by yjbanov** [comment]
Sounds good, but heads up. I'm on vacation starting this Friday. Back Feb 27.
