### ISSUE TITLE
flutter run --preview-dart-2 leaves behind a large .dill file

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#14573]
When doing a flutter run with --preview-dart-2, a large dill file is generated in my project - `lib/main.dart.dill` - at around 15MB.

This is generated in the user's source dir; we should instead do something like create this in the `build/` dir in the project. This is where other temporary artifacts are created, like snapshots.

/cc @aam and @a-siva

**Comment by a-siva** [comment]
I also noticed that doing a 'flutter clean' does not delete this dill file, with the new feature of the incremental kernel file reading from a dill file we end up with the app not getting recompiled after a 'flutter clean' is done.

Moving it to the `build/` dir will solve this problem too.

**Comment by aam** [comment]
a11da23852b9d0171fc3144bd004985f864e61dc fixed this.
