### ISSUE TITLE
Flutter web build "canvaskit" directory contains something that is flagged by GitHub secret scanning

### ISSUE THREAD

**Issue by mkorbel1** [flutter/flutter#145796]
### Steps to reproduce

It appears that somewhat recently our flutter web-app build and CD flow is being flagged by secret scanning on GitHub.  Our workflow involves building a flutter web-app and then deploying it to a GitHub pages site via a GitHub action.

Actually, the command we're running is asking for the `html` renderer, but it's still generating a `canvaskit` directory anyways, which may be a separate issue, or not (maybe related to https://github.com/flutter/flutter/issues/96509?).  I haven't looked to closely into that aspect, but it makes it a little extra annoying since we're not even asking for canvaskit.

All the code to reproduce is available open-source on this repo:
https://github.com/intel/rohd-hcl

An example of a job failure is available here:
https://github.com/intel/rohd-hcl/actions/runs/8377624849/job/23126863666

The failing workflow is "Deploy ROHD-HCL Generator site" from https://github.com/intel/rohd-hcl/blob/main/.github/workflows/general.yml.
https://github.com/intel/rohd-hcl/blob/b593ec63966934398425490a2eb38aacefdb305d/.github/workflows/general.yml#L136-L165

The actual `flutter build` command comes from this script: https://github.com/intel/rohd-hcl/blob/main/tool/gh_actions/hcl_site_generation_build.sh

The actual command being run is:
```bash
flutter build web --profile --web-renderer html --base-href /rohd-hcl/confapp/
```

Running it locally will yield a canvaskit directory in the build output.  I can't tell if what's in there is actually a secret.

Regardless of whether or not this is a real secret exposure, it is a problem either way.
- If it's a real secret exposure, it should be fixed.
- If it's a false error, then this could presumably cause failures for everyone who is pushing a built `canvaskit` directory to a GitHub branch with secret scanning enabled.

Simple reproduction steps look roughly like this:
```
git clone https://github.com/intel/rohd-hcl.git
cd rohd-hcl/confapp
flutter build web --profile --web-renderer html --base-href /rohd-hcl/confapp/
ls build/web/canvaskit
```

The GitHub action that failed is using Flutter stable 3.16.3.

### Expected results

No secret scanning issues.

### Actual results

See example failing CD job here:
https://github.com/intel/rohd-hcl/actions/runs/8377624849/job/23126863666

Snippet from failure:
```
remote: error: GH013: Repository rule violations found for refs/heads/website.        
remote: Review all repository rules at http://github.com/intel/rohd-hcl/rules?ref=refs%2Fheads%2Fwebsite        
remote: 
remote: - GITHUB PUSH PROTECTION        
remote:   ——————————————————————————————————————————————————————        
remote:    Resolve the following secrets before pushing again.        
remote:           
remote:    (?) Learn how to resolve a blocked push        
remote:    https://docs.github.com/code-security/secret-scanning/pushing-a-branch-blocked-by-push-protection        
remote:           
remote:           
remote:   —— WorkOS Production API Key —————————————————————————        
remote:    locations:        
remote:      - commit: 0b124078f14404faeb1bdcc4f07d543a0b2448a0        
remote:        path: confapp/canvaskit/canvaskit.wasm:2[73](https://github.com/intel/rohd-hcl/actions/runs/8377624849/job/23126863666#step:5:74)40        
remote:      - commit: 0b1240[78](https://github.com/intel/rohd-hcl/actions/runs/8377624849/job/23126863666#step:5:79)f14404faeb1bdcc4f07d543a0b2448a0        
remote:        path: confapp/canvaskit/chromium/canvaskit.wasm:25561        
remote:      - commit: 0b124078f14404faeb1bdcc4f07d543a0b2448a0        
remote:        path: confapp/canvaskit/skwasm.wasm:15103        
remote:
```

### Code sample

<details open><summary>Code sample</summary>

```dart
// see https://github.com/intel/rohd-hcl
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

See https://github.com/intel/rohd-hcl/actions/runs/8377624849/job/23126863666

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Running locally:
```console
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22621.3296], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.7.3)
[!] Android Studio (not installed)
[√] VS Code (version 1.87.2)
[√] Proxy Configuration
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed bug report @mkorbel1 

> Actually, the command we're running is asking for the `html` renderer, but it's still generating a `canvaskit` directory anyways, which may be a separate issue, or not (maybe related to #96509?). I haven't looked to closely into that aspect, but it makes it a little extra annoying since we're not even asking for canvaskit.

You may want to check [this](https://github.com/flutter/flutter/issues/126738) issue for reference.



> Running it locally will yield a canvaskit directory in the build output. I can't tell if what's in there is actually a secret.

Check https://github.com/flutter/flutter/issues/126738#issuecomment-1553395668 which doesn't seem to indicate there won't be anything unusual / secret in the config or build.

**Comment by Ken-Andre** [comment]
Me too was recently affected first by the html renderer issue and secret scanning web/canvaskit/skwasm.wasm

**Comment by mkorbel1** [comment]
> You may want to check https://github.com/flutter/flutter/issues/126738 issue for reference.

Thanks, good to know it's a known issue up for discussion.

> Check https://github.com/flutter/flutter/issues/126738#issuecomment-1553395668 which doesn't seem to indicate there won't be anything unusual / secret in the config or build.

I wouldn't imagine there is *intentionally* a secret in that build output.  My suspicion is that there's something that _looks_ like a secret to GitHub secret scanning which is not actually a secret, in which case it would be nice if there were a way for Flutter to avoid making that happen (or add it to some GitHub database or something).  It's possible there's an _actual_ secret in there, but I don't know from where it could have come or how much it would matter.

I have a way of overriding the secret scanning in this repo, but this has now happened across two of our repositories, and the bigger concern is that if the "secret" signature changes slightly with each build/version, then every CD will fail.  It's also a pain to test this in CI because the build directory is not pushed to any other branches as part of the CI flows, and this only gets caught upon push.

**Comment by darshankawar** [comment]
Thanks for the update. It probably looks like a behavior with CICD as how the tool probably deals with the flutter web build, but I'll keep this issue open for team's input / tracking.

**Comment by mkorbel1** [comment]
It appears that GitHub secret scanning thinks `sk_LocalInvocationIndex` is a WorkOS API key, and that string shows up in the wasm files.  From https://workos.com/docs/reference, it looks like they may start their API keys with `sk_`.

**Comment by yjbanov** [comment]
My initial reaction: this is a bug in Github's secret scanner. There are no secrets in our web build artifacts. It would be unreasonable for us to rename variables to avoid it. Github should fix it, not Flutter.

But perhaps I'm missing something?

**Comment by mkorbel1** [comment]
I agree it's a bug on GItHub's side.  When I initially filed the issue, I didn't have enough information to identify whether it was a real secret or not.

One consideration is that many people may be affected by this in the Flutter developer community, so while it's not Flutter's "fault", it may be worth Flutter either (a) renaming a variable to avoid hitting GitHub's bug, or (b) flexing its influence to encourage GitHub to fix their bug promptly.

**Comment by yjbanov** [comment]
Is there a Github bug where we could chime in? I do not see a reasonable path for fixing this on our side. The `sk` naming convention comes from Skia, which is an upstream dependency used by countless amount of software, not just Flutter (Android, all Chromium-based browsers, Xamarin, etc). The `sk` prefix is used on numerous public classes, functions, and methods.

**Comment by yjbanov** [comment]
Closing as it's not actionable on the Flutter side. If someone can link to a Github discussion about this, I'm happy to chime in there. For that, let's create a new issue with a link to the discussion, and we'll prioritize that issue higher.
