### ISSUE TITLE
win-1 is in Quarantine state.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#145723]
### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

win-1 is in Quarantine state.
<img width="825" alt="Screenshot 2024-03-25 at 2 42 16 PM" src="https://github.com/flutter/flutter/assets/120754754/72191e35-ae1c-49de-b50e-efed7de83fc5">

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by keyonghan** [comment]
This is dup of https://github.com/flutter/flutter/issues/144776.
