### ISSUE TITLE
After apply the multiple solution I am unable to configure https://localhost

### ISSUE THREAD

**Issue by jaykumarvcx** [flutter/flutter#145756]
I have did multiple process to configure my flutter web from http://localhost to https://localhost.
Like I have created certificate as below process
openssl genrsa -out localhost.key 2048 to create private  key file

Generate certificate signing request (CSR)
openssl req -new -key localhost.key -out localhost.csr -subj "/CN=localhost"

Generate self-signed certificate using CSR and key
openssl x509 -req -days 365 -in localhost.csr -signkey localhost.key -out localhost.crt

I have added these .key and .csr file with creating a folder called cert and added the above created certificate.

then I have try with flutter run --web-launch-url=https://localhost:8444  no luck getting error as "https://localhost:8444" is not a valid HTTP URL.

I have created "serve.json" file as set-up like 
  {
    "request_handlers": [
      {
          "url_pattern": "/",
          "delegate": {
              "require_trusted_origin": false,
              "delegate_name": "flutter-tools/web-server",
              "secure": true,
              "web-port": 8444,
              "key_path": "/Users/jaykumar/Desktop/code/flutter_toolKit/enx_flutter_plugin_new/example/cert/localhost.key",
              "certificate_path": "/Users/jaykumar/Desktop/code/flutter_toolKit/enx_flutter_plugin_new/example/cert/localhost.crt"
         }
      }
    ]
  } and run the command  - as flutter run -d web-server --web-port 8444, it is still open the http://locallost:8444

Then I have tried wile creating "webdev.yaml" file with configuration

 serve:
    hostname: localhost
    port: 8444
    use_https: true
    certificate_path: cert/localhost.crt
    key_path: cert/localhost.key
    https_port: 8444 

and active the webdev with command  flutter pub global activate webdev
and run the command to open the chrome with https **"webdev serve"**
still it id going on 
[INFO] Checking for updates since last build completed, took 681ms
[INFO] Serving `web` on http://127.0.0.1:8080
[INFO] Running build completed, took 84ms
[INFO] Caching finalized dependency graph completed, took 149ms
[INFO] Succeeded after 237ms with 0 outputs (0 actions)
[INFO] ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

And no luck till day end. I need to open my localhost with https as secure service.
Any mistake I did or any lead will much much appreciate please.

**Comment by jaykumarvcx** [comment]
Dear Friends,

I need support please, As I have been struggling for a couple of days.
Please suggest the best way to configure the same.

I need to setup the secure service, please.

**Comment by darshankawar** [comment]
@jaykumarvcx 
Your issue / question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
