### ISSUE TITLE
I need limit drag & drop area. Can I set boundary for the ReorderableListView when I drag item?

### ISSUE THREAD

**Issue by illusionGeorge** [flutter/flutter#145745]
### Use case

set boundary for the ReorderableListView when I drag item

### Proposal

code samples

**Comment by darshankawar** [comment]
@illusionGeorge 
Looks like this is similar to https://github.com/flutter/flutter/issues/17238 in which you can follow-up for further updates.
Closing as duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by illusionGeorge** [comment]
I mean I use ReorderableListView , when I drag the item , the item can drag outside the screen . I mean whether the ReorderableListView can export api to limit the drag area . This https://github.com/flutter/flutter/issues/17238 is for the Draggable widget.

**Comment by illusionGeorge** [comment]
@darshankawar
