### ISSUE TITLE
Move Cupertino Navigation demo to Studies and create more fine grained per-widget demos

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#14571]
We'd love to put the Cupertino Navigation vignette up under Demos in the Gallery. It's a very good example of doing Cupertino/Apple design with Flutter.

**Comment by Hixie** [comment]
(Removing assignment since this is currently below the m3 critical threshold; we will assign bugs below the threshold once bugs above the threshold have been fixed.)

**Comment by xster** [comment]
I dragged mud on this a bit since I'd really like #4630 to be fixed before we put the spotlight on the demo. Since #4630 is non-trivial, I'll see if I can find a quicker fix first.

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by xster** [comment]
It is

**Comment by xster** [comment]
Split out:
- [ ] CupertinoTabScaffold with and without parallel navigation, navigate in tab vs in root navigator / above tab
- [ ] CupertinoNavigationBar, CupertinoSliverNavigationBar
- [ ] Nav bar title, back label, hero

**Comment by xster** [comment]
Closing this since we stopped using the gallery as a per component demo.
