### ISSUE TITLE
Assertion Error when using showDialog on Back Navigation

### ISSUE THREAD

**Issue by starbibek** [flutter/flutter#145769]
### Steps to reproduce

Navigate to a screen with a form.
Populate the form with some data.
Attempt to navigate back from the screen using the back button.
The confirmation dialog "Confirm Discard" should appear.
Click on the "Yes" button in the dialog.

### Expected results

The dialog should close, and the navigation should proceed without any errors.

### Actual results

After clicking on the "Yes" button in the dialog, an assertion error occurs.

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<bool> _onBackPressed(
  {required BuildContext context, required bool hasPopulatedData}) async {
  if (!hasPopulatedData) {
    return true; // Allow navigation if no data has been entered
  }

  final result = await showAdaptiveDialog(
    context: context,
    barrierDismissible: false, 
    builder: (context) => AlertDialog(
      title: const Text('Confirm Discard'),
      content: const Text(
          'You have entered data in the form. Are you sure you want to discard it and exit?'),
      actions: <Widget>[
        TextButton(
          onPressed: () =>
            Navigator.of(context).pop(true),
          child: const Text('Yes'),
        ),
        TextButton(
          onPressed: () =>
            Navigator.of(context).pop(false), // Pop with false to cancel
          child: const Text('No'),
        ),
      ],
    ),
  );

  return result ?? false; // Handle potential null return (e.g., dialog dismissed without button press)
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
```

![image](https://github.com/flutter/flutter/assets/36692434/606a0130-9ad8-4677-9af6-7a7e05b22705)

```
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@starbibek 
Can you provide a complete runnable but minimal reproducible code sample that we can directly copy paste and run that shows the assertion you are getting ?
Also, provide your `flutter doctor -v` and platform on which you are seeing the error.
