### ISSUE TITLE
`RenderFlex` should not use `defaultComputeDistanceToFirstActualBaseline` to calculate its baseline in `Axis.vertical`

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#145739]
`VerticalDirection.up`  reorders its children. **This will be a breaking change.**

```dart
  test('Vertical Flex Baseline', () {
    const BoxConstraints square = BoxConstraints.tightFor(width: 100.0, height: 100.0);
    final RenderConstrainedBox box1 = RenderConstrainedBox(
      additionalConstraints: square,
      child: RenderFlowBaselineTestBox()
        ..gridCount = 1
        ..baselinePlacer = (double height) => 10,
    );
    final RenderConstrainedBox box2 = RenderConstrainedBox(
      additionalConstraints: square,
      child: RenderFlowBaselineTestBox()
        ..gridCount = 1
        ..baselinePlacer = (double height) => 10,
    );
    final RenderFlex flex = RenderFlex(
      textDirection: TextDirection.ltr,
      children: <RenderBox>[box1, box2],
      direction: Axis.vertical,
    );
    layout(flex, phase: EnginePhase.paint);

    // We can't call the getDistanceToBaseline method directly. Check the dry
    // baseline instead, and in debug mode there are asserts that verify
    // the two methods return the same results.
    expect(flex.getDryBaseline(flex.constraints, TextBaseline.alphabetic), 10);

    flex.mainAxisAlignment = MainAxisAlignment.end;
    pumpFrame(phase: EnginePhase.paint);
    expect(flex.getDryBaseline(flex.constraints, TextBaseline.alphabetic), 410);

    flex.verticalDirection = VerticalDirection.up;
    pumpFrame(phase: EnginePhase.paint);
    expect(flex.getDryBaseline(flex.constraints, TextBaseline.alphabetic), 10);

    flex.mainAxisAlignment = MainAxisAlignment.start;
    pumpFrame(phase: EnginePhase.paint);
    expect(flex.getDryBaseline(flex.constraints, TextBaseline.alphabetic), 410);
  });
```

**Comment by huycozy** [comment]
Hi @LongCatIsLooong 
`RenderFlowBaselineTestBox` is not defined. Could you also share it?

**Comment by LongCatIsLooong** [comment]
@Hixie in a vertical `RenderFlex` with `VerticalDirection.up`, which child's baseline should be used? The [documentation of `computeDistanceToActualBaseline`](https://main-api.flutter.dev/flutter/rendering/RenderBox/computeDistanceToActualBaseline.html) says it

> Returns the distance from the y-coordinate of the position of the box to the y-coordinate of the first given baseline in the box's contents, if any, or null otherwise.

How do I interpret "the first given baseline" here? For multi-child containers, does it mean "the baseline with the smallest y-offset"?

**Comment by Hixie** [comment]
If I recall correctly, the "first child" is intended to be the first one in the child list (the one that `firstChild` points to).

**Comment by Hixie** [comment]
(It's definitely not automatically the one with the smallest y-offset, in fact that's often the wrong child (for example consider a stack). It's also not _always_ the first child that you want, for example a Material text field explicitly doesn't want to use the label for its baseline, since that moves around; it wants to use the user-editable text in the text field.)

**Comment by LongCatIsLooong** [comment]
Ah so if I have a column with `VerticalDirection.up`, the expected behavior is to use the bottom-most child with a baseline? 

> for example consider a stack

Stacks do use the highest baseline it seems:  https://api.flutter.dev/flutter/rendering/RenderStack/computeDistanceToActualBaseline.html

**Comment by LongCatIsLooong** [comment]
>  in fact that's often the wrong child

There doesn't seem to be a fast & easy remedy for that besides writing a custom RenderObject? Does it sound reasonable to introduce a ParentDataWidget to specify the baseline child then (I think we are allowed to have more than one `ParentDataWidget` on a render object now)?

**Comment by Hixie** [comment]
> Ah so if I have a column with `VerticalDirection.up`, the expected behavior is to use the bottom-most child with a baseline?

I mean honestly at this point given how much content exists that depends on this, I would say the _expected_ behaviour is probably whatever we do. If we change it, we're going to break people in really subtle ways.

> Stacks do use the highest baseline it seems: https://api.flutter.dev/flutter/rendering/RenderStack/computeDistanceToActualBaseline.html

Heh, figures. :-)

> There doesn't seem to be a fast & easy remedy for that besides writing a custom RenderObject?

The `IgnoreBaseline` widget is the usual remedy, but in general, writing a custom `RenderObject` is probably the way to go if you care about the layout and baseline positions and so on.


> Does it sound reasonable to introduce a ParentDataWidget to specify the baseline child then (I think we are allowed to have more than one `ParentDataWidget` on a render object now)?

I'm not sure what problem we're trying to solve here so it's hard for me to evaluate.

**Comment by LongCatIsLooong** [comment]
> The IgnoreBaseline widget is the usual remedy

Ah clever. Thanks I'll close this then.
