### ISSUE TITLE
Error when flutter upgrade or flutter channel modifies flutter.bat

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#14578]
On my Windows RS2 (v10.0.14393) machine, previously running the alpha channel, I attempted to switch to the beta channel. Error message as below...

```
[C:\Users\timsneath] flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], locale en-US, channel alpha)
    • Flutter version 0.0.21 at c:\git\flutter
    • Framework revision 2e449f06f0 (10 days ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\Users\timsneath\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)


[C:\Users\timsneath] flutter channel
Flutter channels:
* alpha
  beta
  dev
  master

[C:\Users\timsneath] flutter channel beta
Switching to flutter channel 'beta'...
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.
git: Switched to a new branch 'beta'
'ot_pathflutter_tools_dirscript_path"' is not recognized as an internal or external command,
operable program or batch file.
Downloading package sky_engine...                     0.5s
Downloading common tools...                           0.4s
Downloading windows-x64 tools...                      1.0s
Downloading windows-x64 tools...                      1.3s
Downloading android-arm-profile/windows-x64 tools... 3650.2s
Downloading android-arm-release/windows-x64 tools...  0.4s
Downloading android-x86 tools...                      0.7s
Downloading android-x64 tools...                      0.8s
Downloading android-arm tools...                      0.6s
Downloading android-arm-profile tools...              0.5s
Downloading android-arm-release tools...              0.5s
Switching to flutter channel 'beta'...
git: M  VERSION
git: Your branch is up to date with 'origin/beta'.
git: Already on 'beta'

[C:\Users\timsneath]
```

**Comment by goderbauer** [comment]
Ah yes! That issue comes up every 6 months or so. In fact, it comes up whenever we make changes to flutter.bat, which is the entry point to flutter on Windows. It has to do with how Windows executes bat files (see below). And I have not found a good way around this. Open to suggestions.

Here is what's happening:

The "flutter upgrade" (or the channel switch command) runs flutter.bat. While flutter.bat is running flutter (via git) updates the flutter.bat file on disk because it has changed upstream or in the other channel. Once that updating is complete, Windows continues executing flutter.bat at the same place/position it left before the file was updated. What Windows now reads from the file at that old position doesn't make any sense anymore (because it was changed) and Windows prints an error. Everything continues to work as usual after this.

Not sure how we can work around this. One suggestion has been to first execute a script that copies flutter.bat to a new location and then run it from that new location. That way, changes to flutter.bat would not effect the current execution. We run into the same problem whenever we'd have to update the copy script, though.

**Comment by goderbauer** [comment]
In other words: The command interpreter remembers the line position it's at in the batch file. If the batch file gets modified before the current position during execution strange things like the one you see happen.

**Comment by timsneath** [comment]
Thanks - that's a helpful update. 

I see that [Anaconda's package manager has a similar problem](https://github.com/conda/conda/issues/6968#issuecomment-371341034), although not quite so egregious. This is dangerous for us, because the command Flutter encounters at the index in the batch file could itself be a different executable on the user's path, as well as other unpredictable behavior that could occur by executing untested code. Given [how frequently `flutter.bat` is updated](https://github.com/flutter/flutter/commits/master/bin/flutter.bat), we should continue to investigate solutions.

**Comment by timsneath** [comment]
And just for others' benefit -- this issue isn't limited to switching channels: I hit it again today while running `flutter upgrade` on a machine that is on the master channel.

**Comment by goderbauer** [comment]
Sounds like the Anaconda people also don't really have a fix for this :(

**Comment by aam** [comment]
Should not the solution be - on launch of `flutter.bat` make a copy of it and have that copy running so if original `flutter.bat` is modified as part of `git pull` running copy is not affected? After `git pull` finishes, the copied script can confirm that it still the matches new pulled original and if it doesn't, then it relaunches `flutter.bat`(which should again make a copy and run that copy)

**Comment by goderbauer** [comment]
Yeah, that's one idea (see my comment above). We will run into the same problem whenever we have to modify the section that copies the script, though.

**Comment by aam** [comment]
Sorry missed your original proposal.

>  We will run into the same problem whenever we have to modify the section that copies the script, though.

Not sure I see the problem. Here is the sketch:

flutter.cmd
```
if "%~n0" == "flutter-copy" goto do-the-work
copy flutter.cmd flutter-copy.cmd
flutter-copy.cmd
echo "Note - not coming back here"

:do-the-work

echo "Do the work and exit"
```

**Comment by goderbauer** [comment]
@aam I forgot that executing a batch script from a batch script replaces the previous batch script... I am preparing a PR.

**Comment by goderbauer** [comment]
I had to roll the "fix" back because it was causing flakiness on the Windows Chromebot. I did some more research around this and I am actually prototyping one more idea... Stay tuned for that.

**Comment by MahdiGharooni** [comment]
I had problem when I wanted to switch between channels, and eventually I understood It was because pf **changes in Flutter SDK** directory. maybe my answer help you.

https://github.com/flutter/flutter/issues/44165#issuecomment-612614373
