### ISSUE TITLE
Enable customization of shape in NavigationDrawer

### ISSUE THREAD

**Issue by plammens** [flutter/flutter#145763]
### Use case

On large screens, my NavigationDrawer is fixed, always visible on the left side.
I would like it to look flush with the rest of the screen, so in particular I would like to remove the rounded corners that come as the default shape of the NavigationDrawer.

![image](https://github.com/flutter/flutter/assets/18049056/e12c9ecd-5b03-4361-9e69-4660a68cbfe3)

### Proposal

Make `NavigationDrawer` accept a `shape` parameter that is passed on to the underlying `Drawer` instance.

**Comment by amir-hossein-rajaezadeh** [comment]
Please provide code

**Comment by danagbemava-nc** [comment]
Hi @plammens, you can modify the underlying drawer using the DrawerTheme and it will be applied to the `NavigationDrawer`. Try the sample below to see if it suits your needs

<details>
<summary>sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.light(),
      home: const DrawerApp(),
    );
  }
}

class DrawerApp extends StatelessWidget {
  const DrawerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        ConstrainedBox(
          constraints: BoxConstraints.tight(const Size.fromWidth(300)),
          child: const DrawerTheme(
            data: DrawerThemeData(shape: RoundedRectangleBorder()),
            child: NavigationDrawer(children: []),
          ),
        ),
        Expanded(
          child: Scaffold(
            appBar: AppBar(
              backgroundColor: Theme.of(context).colorScheme.primary,
              title: const Text('AppBar'),
            ),
          ),
        )
      ],
    );
  }
}
```
</details>

**Comment by plammens** [comment]
Sorry, I missed that! That does it, thanks.
