### ISSUE TITLE
Add a verbose flag to `et` that dumps subprocess commands.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#145711]
Dump exactly what `et` is running for debugability purposes.

**Comment by gaaclarke** [comment]
Jason got around this with ps aux | egrep clang while et was executing.

**Comment by matanlurey** [comment]
John, you've been relieved. 

![f70af417-0e85-4382-a1a8-a8cc69173793_text](https://github.com/flutter/flutter/assets/168174/a5d4a060-0262-4454-8c3e-1d222a352b48)

**Comment by matanlurey** [comment]
Just a quick clarification, there _is_ a `verbose` option (at least at HEAD):

```sh
flutter % ./bin/et --help   
A command line tool for working on the Flutter Engine.

Usage: et <command> [arguments]

Global options:
-h, --help       Print this usage information.
-v, --verbose    Prints verbose output

Available commands:
  build    Builds the engine
  fetch    Download the Flutter engine's dependencies
  format   Formats files using standard formatters and styles.
  lint     Lint the engine repository.
  query    Provides information about build configurations and tests.
  run      Run a Flutter app with a local engine build.
  test     Runs a test target

Run "et help <command>" for more information about a command.
```

I am guessing this means "make verbose dump subprocess commands".

**Comment by gaaclarke** [comment]
I looked at `et build -h` and it doesn't list it.

For my purposes I needed to see the `clang` invocations so `build` has to forward the `--verbose` command to the ninja invocation.

**Comment by gaaclarke** [comment]
I guess `et build -h` does say "Run "et help" to see global options."

**Comment by matanlurey** [comment]
Yeah no worries, your request is super valid.

Off hand, do you have an example of a tool in the engine that does this the way you like I can emulate?

**Comment by gaaclarke** [comment]
I don't, I'd like it to behave just like `ninja --verbose` where there is no cursor moving in the terminal.  It just dumps everything linearly so that I can pipe it to another process for processing or write it to disk and examine it.  Maybe it needs to be a different flag if we want `--verbose` to mean it prints out the `ninja` command and `--ninja-verbose` means ninja prints out its compilation invocations?

**Comment by matanlurey** [comment]
So the original request was to basically log every call to `<ProcessRunner>.runProcess` which is trivial and I can have implemented in a few minutes and send out for review. It sounds like you _also_ want something like a more CI-oriented output mode (or something that doesn't use smarter output), is that right?

I might just do the former and file another issue for the latter if so.

**Comment by gaaclarke** [comment]
Yea, that sounds good.  Or just open my closed issue again since it sounds like this issue and that one are slightly different.  We can update that issue to be more precise.

**Comment by matanlurey** [comment]
Ok apparently verbose _was_ added and roughly does this:

```sh
et build
[2024-05-06T17:14:29.397][macos/host_debug: GN]: OK
[macos/host_debug: ninja] 0.5% (28/5952) CXX obj/flutter/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone.time_zone_info.o^C

matanl@matanl-macbookpro4 flutter % et build -v
[2024-05-06T17:14:34.738][macos/host_debug: GN]: STARTING: /Users/matanl/Developer/engine/src/flutter/tools/gn --runtime-mode debug --no-stripped --no-lto --xcode-symlinks --no-goma --no-rbe
[2024-05-06T17:14:35.273][macos/host_debug: GN]: OK
[2024-05-06T17:14:35.273][macos/host_debug: ninja]: STARTING: /Users/matanl/Developer/engine/src/flutter/third_party/ninja/ninja -C /Users/matanl/Developer/engine/src/out/host_debug
[macos/host_debug: ninja] 40.8% (2417/5924) CXX obj/flutter/third_party/dart/runtime/lib/libdart_lib_jit.object.o
```

The additional asks are around forwarding verbose to sub-processes and output modes.

I'll take Aaron's suggestion of closing this as complete and re-opening his issue, https://github.com/flutter/flutter/issues/147894.
