### ISSUE TITLE
Rendering issues with Impeller and canvas.drawVertices

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#145707]
### Steps to reproduce

1. Run the `sparkle_party` vignette in both Impeller and Legacy modes. The code is open-source and you can check it out here: https://github.com/gskinnerTeam/flutter_vignettes/tree/master/vignettes/sparkle_party

### Expected results

All particles should be sparkles

### Actual results

Some of the particles are rendering as squares.

Note: It seems to be a layering/overlap issue, when you get too many particles stacked on top of each other, squares begin appearing. So we can reproduce with a relatively low number of particles (100) that are large in size, or a high number of small particles.

### Code sample
The underlying rendering API used in this demo is an `ImageShader` + `drawVertices` API:
<details open><summary>Code sample</summary>

```dart
class ParticleFXPainter extends CustomPainter {
  ParticleFX fx;

  // ParticleFX is a ChangeNotifier, so we can use it as the repaint notifier.
  ParticleFXPainter({required this.fx}) : super(repaint: fx);

  @override
  void paint(Canvas canvas, Size size) {
    if (fx.vertices == null || fx.spriteSheet.image == null) {
      return;
    }
    Paint paint = Paint()
      ..shader = ImageShader(fx.spriteSheet.image!, TileMode.clamp, TileMode.clamp, Matrix4.identity().storage);
    canvas.drawVertices(fx.vertices!, BlendMode.dstIn, paint);
  }

  @override
  bool shouldRepaint(_) => true;
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Legacy
![image](https://github.com/gskinnerTeam/flutter_vignettes/assets/736973/5957f96c-d7fa-46e0-9386-f162a403b3d3)

https://github.com/gskinnerTeam/flutter_vignettes/assets/736973/42c8781e-7c74-41ce-ab28-7d4b74435e95

Impeller
![image](https://github.com/gskinnerTeam/flutter_vignettes/assets/736973/184cf2ab-8718-4c99-b4b8-82ff5579c8de)

https://github.com/gskinnerTeam/flutter_vignettes/assets/736973/7191cd44-168e-499c-8d43-4e5db9388716

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.19045.3693], locale en-US)
    • Flutter version 3.19.3 on channel stable at C:\_dev\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Shawn\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio3\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio3
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\Shawn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3693]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by jason-simmons** [comment]
This is due to the implementation of `VerticesContents::Render`.

The app is drawing a large number of overlapping partially transparent sprites using a `Vertices` with texture coordinates, colors, and the `dstIn` blend mode.

`VerticesContents::Render` creates a source `Contents` using the vertices, the texture, and the texture coordinates.  It then creates a destination `Contents` using the vertices and the colors.  Then it combines them with a `ColorFilterContents::MakeBlend`.

With this approach, the source and destination contents are flattened into textures that are then combined using the blend mode.  But if there are overlapping triangles in the vertices, then a source pixel from one triangle may be blended with a destination pixel from a different triangle that was painted on top of it later.  The resulting output will have the wrong color.

A simplified example:
```
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

ui.Image? circle;

void main() async {
  ui.PictureRecorder recorder = ui.PictureRecorder();
  Canvas canvas = Canvas(recorder);
  canvas.drawCircle(Offset(50, 50), 50, Paint()..color = Colors.white);
  ui.Picture picture = recorder.endRecording();
  circle = await picture.toImage(100, 100); 

  runApp(Center(child: CustomPaint(painter: TestPainter())));
}

class TestPainter extends CustomPainter {
  final ui.Vertices vertices = ui.Vertices(
    VertexMode.triangles,
    <Offset>[
      Offset(0, 0), Offset(0, 100), Offset(100, 100),
      Offset(20, 20), Offset(20, 120), Offset(120, 120),
    ],
    colors: [
      Colors.red, Colors.red, Colors.red,
      Colors.green, Colors.green, Colors.green,
    ],
    textureCoordinates: [
      Offset(0, 0), Offset(0, 100), Offset(100, 100),
      Offset(0, 0), Offset(0, 100), Offset(100, 100),
    ]
  );

  @override
  void paint(Canvas canvas, Size size) {
    Paint paint = Paint()
      ..shader = ImageShader(circle!, TileMode.clamp, TileMode.clamp, Matrix4.identity().storage);
    canvas.drawVertices(vertices, BlendMode.dstIn, paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
```

| Skia | Impeller |
| ----- | ----- |
| <img src="https://github.com/flutter/flutter/assets/14226037/e7004ad6-a664-410d-91cb-8566219323f7" width="100" height="100" /> | <img src="https://github.com/flutter/flutter/assets/14226037/8acee4df-6539-45bc-82b5-00a2acbcf68e" width="100" height="100" /> |

Skia appears to be blending each triangle's source and destination separately and then combining those results into the final image.

@jonahwilliams

**Comment by gaaclarke** [comment]
Here's the capture from jason's sample.

[sparkle.gputrace.zip](https://github.com/flutter/flutter/files/14796250/sparkle.gputrace.zip)

## src

<img width="200" alt="Screenshot 2024-03-28 at 3 44 02 PM" src="https://github.com/flutter/flutter/assets/30870216/249bee49-21e0-424d-ad42-b348c9df00ec">


## dst
<img width="200" alt="Screenshot 2024-03-28 at 3 43 25 PM" src="https://github.com/flutter/flutter/assets/30870216/9e222d57-b47d-45d2-9bc7-88bc7e4dce9e">

**Comment by gaaclarke** [comment]
Seems like the easiest fix would be the split up the triangles based on if they overlap and use our existing rendering paths.

So, drawing triangle((0,0), (1, 2), (2, 0)) and triangle((1,0), (2, 2), (3,0)) will result in 2 `VerticesContents`. Whereas drawing triangle((0,0), (1, 2), (2, 0)) and triangle((10,0), (11, 2), (12,0)) will still result in 1 `VerticesContents`.

So, just keep gobbling them up in the canvas while they don't overlap any existing triangles and poop out N contents.

**Comment by jonahwilliams** [comment]
Since we already have specialized shaders for blending textures and solid colors, my suggestion would be to extend this to allow the per vertex color to vary, then use them in place of a blend filter.

See also https://github.com/flutter/flutter/issues/131345

**Comment by gaaclarke** [comment]
> Since we already have specialized shaders for blending textures and solid colors, my suggestion would be to extend this to allow the per vertex color to vary, then use them in place of a blend filter.
> 
> See also #131345

Yea, that sounds ideal.  Nice if it can fix a bug and improve performance too.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/51778 fixes this for the pipeline blend modes. I'd already done this optimization for drawAtlas.
