### ISSUE TITLE
 Ability to exclude files/folders in `flutter_plugin_tools format`

### ISSUE THREAD

**Issue by timothy** [flutter/flutter#145857]
### Use case

I'm working within a Melos Mono-Repo workflow. When running `melos bootstrap`, it generates certain files. Our current `melos format` command (`dart pub global run flutter_plugin_tools format`) unintentionally formats these generated files.

While formatting itself isn't an issue, it triggers unnecessary Git commits due to the changes. Ideally, we'd commit the newly formatted code once and avoid these repetitive commits. However, the generated code will be regenerated without the formatting upon subsequent `melos bootstrap` calls, leading to a continuous cycle of formatting and committing. This creates unnecessary noise in the version control history.

### Proposal

I propose adding functionality to exclude specific files or folders during the `flutter_plugin_tools format` execution. This would allow us to maintain consistent formatting for the core codebase while excluding the dynamically generated files.

This feature would streamline the development process by reducing unnecessary Git commits and improving the clarity of our version control history.

**Comment by stuartmorgan** [comment]
The `flutter_plugin_tools` package was discontinued over a year ago, so any changes would need to be made in a fork.
