### ISSUE TITLE
Debug a Flutter app, via Atom, in iOS simulator

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1458]
A developer should be able to launch their Flutter app into the iOS simulator, and use Atom's debugger with the app.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by eseidelGoogle** [comment]
I spoke with @devoncarew just now and he mentioned this feature was at-risk for completion in time for the Hackathon.  It was not clear to me in our discussion what needed to be done for this feature.  My understanding is that the iOS simulator is very easy to connect to from outside (can open ports on the host, etc?), but I could be wrong.

@devoncarew can you point to code examples of how the debugger gets wired up for Android, etc?  I presume it's just a question of opening a connection to Observatory inside the simulator?  Is this just a question of whether `flutter start` on iOS knows how to respect the flags passed to the flutter engine? e.g.
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/device_ios.dart#L190
(If we don't already have an issue on file for that TODO we likely need one @chinmaygarde).

**Comment by eseidelGoogle** [comment]
@devoncarew just filed one for the simulator respecting start args: https://github.com/flutter/flutter/issues/1511

**Comment by devoncarew** [comment]
We need the simulator and ios devices to start the observatory listening on a port. The port should either be well-known, and/or the ios launches should use the `--debug-port` flag. Flutter's been using `8181`; the `--debug-port` flag allows multiple flutter apps to be runnable (and debuggable) at once.

**Comment by sethladd** [comment]
Thanks for checking into this! Looking forward to debugging with our iOS flow.

**Comment by chinmaygarde** [comment]
I am not sure what needs to be done here. Launching on the simulator automatically start the Dart Observatory. Since its the simulator (i.e, the host itself), you can access it any web browser at 8181. Is is just the plumbing of the `--debug-port` for multiple apps that is required? I can do that right away.

**Comment by chinmaygarde** [comment]
![screen shot 2016-02-08 at 12 43 04 pm 2](https://cloud.githubusercontent.com/assets/44085/12898432/883ea126-ce61-11e5-8320-96326cdef75f.png)

**Comment by devoncarew** [comment]
Yup, I didn't know that the observatory was already available w/ the simulator. Sounds like just `--debug-port` then.

**Comment by chinmaygarde** [comment]
All the same flags as Android are wired up and the tools forward the flags correctly. We might need an engine roll for the tools to see all the changes.

**Comment by sethladd** [comment]
yay! can't wait to try it :)
