### ISSUE TITLE
[CP] [canvaskit] Fall back to multi-context rendering on Firefox and Safari

### ISSUE THREAD

**Issue by bc-lee** [flutter/flutter#145864]
### Issue Link

https://github.com/flutter/flutter/issues/144731

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/51730

### Changelog Description

[canvaskit] Fall back to multi-context rendering on Firefox and Safari

### Impacted Users

Flutter web users using Firefox and Safari.

### Impact Description

Notably, Firefox users will see fewer errors and rendering issues.

### Workaround

Use the HTML renderer instead of the Canvaskit renderer.

### Risk

low

### Test Coverage

yes

### Validation Steps

After merging this change, the test code at the link below should work without any issues and console errors, especially on Firefox and Safari.
https://github.com/flutter/flutter/issues/144913#issuecomment-2001920017

**Comment by itsjustkevin** [comment]
@ditman can you take a look at this cherry-pick request?

**Comment by ditman** [comment]
@itsjustkevin just pinged the team, this is probably a fine CP, but I'm not a super expert on this /cc @yjbanov @harryterkelsen in case this needs to CP more!

**Comment by harryterkelsen** [comment]
Should be OK to cherry-pick this. LGTM

**Comment by zanderso** [comment]
CP *not* lgtm. The patch is quite large, the fix exists in multiple beta versions, and there is a workaround. We should not be cherry-picking this to stable so late in the cycle.

**Comment by dickermoshe** [comment]
Ouch
https://examples.flame-engine.org/#/Collision_Detection_Multiple_shapes
