### ISSUE TITLE
Image.network can't use short url ?

### ISSUE THREAD

**Issue by VincentChen1212** [flutter/flutter#145883]
### Steps to reproduce

```
class _VinHomePageState extends State<VinHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
      title: const Text(
        'Title',
        style: TextStyle(fontSize: 20, color: Colors.amber),
      ),,
    ),
    //body: Image.network('https://images.pexels.com/photos/208321/pexels-photo-208321.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'),);
    body: Image.network('https://reurl.cc/D4R4pR'),);
  }
}

```
When I use full url, the image is showed.
But use short url, it get exception
![截圖 2024-03-28 13 49 30](https://github.com/flutter/flutter/assets/51907583/150a6992-3c90-45fe-9e6a-3a1e70cf11b4)

Is this a bug? or something to setting?

Thanks

### Expected results

show

### Actual results

Exception

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by edeuss** [comment]
Because the url you're trying to use is a url redirect. You need to use the direct image url.

**Comment by darshankawar** [comment]
@VincentChen1212 
Check above solution. Also, it is better to ask such type of question / issue on support channels like Stackoverflow.
Closing from here.
