### ISSUE TITLE
Proactively show https://github.com/flutter/flutter/wiki/Using-Flutter-in-China in tools

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14587]
If the tools hit a SocketException with storage.googleapis.com, we should automatically suggest https://github.com/flutter/flutter/wiki/Using-Flutter-in-China to users.

**Comment by InMatrix** [comment]
Can the flutter tool look up country by IP address?

**Comment by xster** [comment]
We can have the tool bring in https://github.com/rikulo/geoip, or the easier way is probably to have a exception handle on the failure and show a message like `if you're in china, look at X`
