### ISSUE TITLE
After Updating flutter to 3.19.4, key pad is not opening on android 12

### ISSUE THREAD

**Issue by mrunal-atreya** [flutter/flutter#145845]
### Steps to reproduce

I am implementing application in flutter. Recently, I upgraded my Flutter to 3.19.4, and I am facing bug. like I am unable to open the keypad in my app. On other Android versions, it was working fine, but on Android 12, its not working. i created new project with flutter 3.19.4 and use Text Form Field, and it was working fine on that application

It is working only when I select the keypad icon on the bottom and change it to Google Voice Typing from Gboard.

I tried to add hardwareaccelerated=true in my manifest, but still its not working.

### Expected results

Keypad should display when clicked on the text field.

### Actual results

key pad not opening

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[
![Uploading android12_keypad.gif…]()
]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22631.3296], locale en-IN)
• Flutter version 3.19.4 on channel stable at C:\Users\AIPL_LP_18\Documents\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/68bfaea224880b488c617afe30ab12091ea8fa4e (7 days ago), 2024-03-20 15:36:31 -0700
• Engine revision a5c24f538d
• Dart version 3.3.2
• DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at C:\Users\AIPL_LP_18\AppData\Local\Android\sdk
• Platform android-34, build-tools 34.0.0
• Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
• Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2023.2)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.87.2)
• VS Code at C:\Users\AIPL_LP_18\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.84.0

[√] Connected device (3 available)
• sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)
• Chrome (web) • chrome • web-javascript • Google Chrome 123.0.6312.59
• Edge (web) • edge • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
• All expected network resources are available.

• No issues found!]
```

</details>

**Comment by huycozy** [comment]
Hi @mrunal-atreya 
It seems you have the issue in your production/complex code that we are unsure which could be the cause.

You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a minimal sample code that can produce the issue. And please share it here when you have such an example. Please also provide the output of `flutter doctor -v`. Thanks!

**Comment by mrunal-atreya** [comment]
hello @huycozy thanks for reply
This is what my flutter doctor gave me
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22631.3296], locale en-IN)
    • Flutter version 3.19.4 on channel stable at C:\Users\AIPL_LP_18\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (7 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\AIPL_LP_18\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\AIPL_LP_18\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 123.0.6312.59
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
    • All expected network resources are available.

• No issues found!

and this is my TextFormField code 

HoriVertiPadding(
                              verticalPadding: 2.h,
                            ),
                            MediaQuery(
                              data: MediaQuery.of(context).copyWith(
                                  textScaler: const TextScaler.linear(1.0)),
                              child: TextFormField(
                                controller: _usernameController,
                                 autofocus:true,
                                autovalidateMode:
                                    AutovalidateMode.onUserInteraction,
                                decoration: InputDecoration(
                                  contentPadding: EdgeInsets.symmetric(
                                      vertical:
                                          (screenWidth > 600) ? 1.5.h : 2.h,
                                      horizontal: 4.w),
                                  labelText: "Username",
                                  labelStyle: (screenWidth > 600)
                                      ? TabLabelTextStyleforLogin()
                                      : LabelTextStyleforLogin(),
                                  filled: true,
                                  fillColor: ColorConstants.white,
                                  border: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants.textFormBorder),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  errorBorder: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants
                                            .errorInputBorderColor),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  focusedErrorBorder: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants
                                            .errorInputBorderColor),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  errorStyle: (screenWidth > 600)
                                      ? TabErrorInputTextStyleforLogin()
                                      : ErrorInputTextStyleforLogin(),
                                ),
                                style: (screenWidth > 600)
                                    ? TabInputTextStyleforLogin()
                                    : InputTextStyleforLogin(),
                                inputFormatters: [
                                  FilteringTextInputFormatter.deny(
                                      RegExp(r"\s\b|\b\s")),
                                  FilteringTextInputFormatter.deny(
                                      RegExp(r'\s'))
                                ],
                                
                                validator: (value) {
                                  if (value!.isEmpty) {
                                    return "Enter username";
                                  }
                                  return null;
                                },
                                
                                onChanged: (value) {
                                  setState(() {
                                    errorMessage = null;
                                  });
                                },
                                
                              ),
                            ),
                            HoriVertiPadding(verticalPadding: 1.5.h),

**Comment by mrunal-atreya** [comment]
@huycozy 
this is my complete file 

                  `class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  GlobalKey<FormState> formkey = GlobalKey<FormState>();
  bool hidePassword = true;
  String initialCountry = "IN";
  String selectedCountryCode = "+91";
  final TextEditingController _mobileNumberController = TextEditingController();

  final TextEditingController _usernameController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();
  int selectedUserLoginType = 0;
  // LoginOption _loginOption = LoginOption.otp;

  String verificationId = '';

  UserRoleModel userRoleModel = UserRoleModel();
  int displayUpdateCount = 0;

  String? errorMessage;

  @override
  void initState() {
    super.initState();
    initializeFirebaseIntoApp();
    if (Platform.isIOS) {
      fetchUpdateAlertDisplayCount();
    }
  }

  fetchUpdateAlertDisplayCount() async {
    if (await MySharedPreferences().getIntValue(
            key: LocalStorageStringConstants().updateAlertDisplayCount) !=
        1) {
      // await checkAndUpdate(context);
    }
  }

  initializeFirebaseIntoApp() async {
    //await Firebase.initializeApp();
    userRoleModel = await _fetchUserRoles();
  }

  Future<UserRoleModel> _fetchUserRoles() async {
    try {
      var response = await ApiProvider().fetchRolesOfNtGuna(context: context);
      if (response != "") {
        var decodedJson = jsonDecode(response);
        userRoleModel = UserRoleModel.fromJson(decodedJson);
        if (Platform.isAndroid) {
          if (await MySharedPreferences().getIntValue(
                  key: LocalStorageStringConstants().updateAlertDisplayCount) !=
              1) {
            // await checkAndUpdate(context);
          }
        }
        setState(() {});
      }
    } catch (e) {
      print(e.toString());
    }
    return userRoleModel;
  }

  _loginUser(
      {required String mobileNumber,
      required LoginModelByMobileNumber loginModelByMobileNumber}) async {
    ProgressDialog progressDialog = ProgressDialog(context: context);
    try {
      progressDialog.show(msg: "Please wait..");
      FirebaseAuth auth = FirebaseAuth.instance;
      auth.verifyPhoneNumber(
        phoneNumber: mobileNumber,
        verificationCompleted: (AuthCredential authCredentials) {
          progressDialog.close();
        },
        verificationFailed: (FirebaseAuthException authException) {
          progressDialog.close();
          showDialog(
              context: context,
              builder: (_) => CustomAlertDialog(
                    title: authException.toString(),
                    showOkButton: true,
                    onOkButtonPressed: () => Navigator.pop(context),
                  ));
        },
        codeSent: (verificationId, forceResendingToken) {
          progressDialog.close();
          // customToastMessage(toastMessage: "Otp Sent..!!");
          Navigator.pushNamed(context, "/OtpVerificationScreen", arguments: {
            "loginUserDetails": loginModelByMobileNumber,
            "mobileNumber":
                "$selectedCountryCode ${_mobileNumberController.text.trim()}",
            "verificationId": verificationId,
            "resendToken": "$forceResendingToken",
            "isLoginFlow": true,
          });
        },
        timeout: const Duration(seconds: 8),
        codeAutoRetrievalTimeout: (verificationId) {
          progressDialog.close();
          verificationId = verificationId;
        },
      );
    } catch (e) {
      progressDialog.close();
      print(e.toString());
    }
  }

  @override
  Widget build(BuildContext context) {
    double screenWidth = MediaQuery.of(context).size.width;
    return Container(
      width: MediaQuery.of(context).size.width * 1.0,
      height: MediaQuery.of(context).size.height * 1.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0),
        image: DecorationImage(
          image: (screenWidth > 600)
              ? const AssetImage("assets/tablet/login_screen_bg.png")
              : const AssetImage("assets/logos/login_screen_bg.png"),
          fit: BoxFit.fill,
        ),
      ),
      child: SafeArea(
        child: PopScope(
          canPop: false,
          onPopInvoked: (didPop) async {
            showDialog(
                barrierDismissible: false,
                context: context,
                builder: (_) => CustomAlertDialog(
                      content: SizedBox(
                        width: 309.0,
                        height: 180.0,
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Center(
                              child: Image.asset(
                                'assets/logos/exit.gif',
                                width: 86.0,
                                height: 86.0,
                              ),
                            ),
                            const SizedBox(height: 8.0),
                            Text(
                              "Exit?",
                              style: (screenWidth > 600)
                                  ? TabPopupMainTextStyle()
                                  : PopupMainTextStyle(),
                              textAlign: TextAlign.center,
                              textScaler: const TextScaler.linear(1.0),
                            ),
                            const SizedBox(height: 8.0),
                            Text(
                              "Do you really want to exit the app?",
                              style: (screenWidth > 600)
                                  ? TabPopupSubTextStyle()
                                  : PopupSubTextStyle(),
                              textAlign: TextAlign.center,
                              textScaler: const TextScaler.linear(1.0),
                            ),
                            const SizedBox(height: 20.0),
                            Container(
                              height: 1,
                              color: Colors.grey, // Choose the color you desire
                              margin: EdgeInsets.symmetric(vertical: 1.h),
                            ),
                          ],
                        ),
                      ),
                      //title: "Do you really want to exit the app?",
                      showYesButton: true,
                      showNoButton: true,
                      onNoButtonPressed: () => Navigator.pop(context),
                      onYesButtonPressed: () {
                        SystemNavigator.pop();
                      },
                    ));
            return;
          },
          child: Scaffold(
            resizeToAvoidBottomInset: true,
            backgroundColor: Colors.transparent,
            body: Form(
              key: formkey,
              child: Padding(
                padding: EdgeInsets.only(top: (screenWidth > 600) ? 20.w : 12.h),
                child: ListView(
                  padding: EdgeInsets.symmetric(
                      vertical: 3.h,
                      horizontal: (screenWidth > 600) ? 18.w : 8.w),
                  children: [
                    Padding(
                      padding: EdgeInsets.symmetric(vertical: 1.5.h),
                      child: const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                      ),
                    ),
                    HoriVertiPadding(verticalPadding: 7.h),
                    Visibility(
                      child: SingleChildScrollView(
                        child: Column(
                          children: [
                            Visibility(
                              child: errorMessage != null
                                  ? Container(
                                      width: 89.w,
                                      decoration: BoxDecoration(
                                          color: const Color.fromARGB(
                                              255, 253, 241, 241),
                                          border: Border.all(
                                            width: 0.2.w,
                                            color: Colors.red,
                                          ),
                                          borderRadius:
                                              BorderRadius.circular(1.w)),
                                      child: Padding(
                                        padding:
                                            EdgeInsets.symmetric(vertical: 1.h),
                                        child: Row(
                                          mainAxisAlignment:
                                              MainAxisAlignment.start,
                                          children: [
                                            Padding(
                                              padding: EdgeInsets.only(
                                                  right: 5.w, left: 5.w),
                                              child: Icon(
                                                Icons.warning_rounded,
                                                size: (screenWidth > 600)
                                                    ? 18.sp
                                                    : 25.sp,
                                                color: Colors.red,
                                              ),
                                            ),
                                            Column(
                                              crossAxisAlignment:
                                                  CrossAxisAlignment.start,
                                              children: [
                                                Text(
                                                  "Invalid credentials",
                                                  style: (screenWidth > 600)
                                                      ? TabErrorTitleTextStyleforLogin()
                                                      : ErrorTitleTextStyleforLogin(),
                                                  textScaler:
                                                      const TextScaler.linear(
                                                          1.0),
                                                ),
                                                Text(
                                                  "Enter valid username or password",
                                                  style: (screenWidth > 600)
                                                      ? TabErrorSubTitleTextStyleforLogin()
                                                      : ErrorSubTitleTextStyleforLogin(),
                                                  textScaler:
                                                      const TextScaler.linear(
                                                          1.0),
                                                ),
                                              ],
                                            ),
                                          ],
                                        ),
                                      ),
                                    )
                                  : Container(),
                            ),
                            HoriVertiPadding(
                              verticalPadding: 2.h,
                            ),
                            MediaQuery(
                              data: MediaQuery.of(context).copyWith(
                                  textScaler: const TextScaler.linear(1.0)),
                              child: TextFormField(
                                controller: _usernameController,
                                 autofocus:true,
                                autovalidateMode:
                                    AutovalidateMode.onUserInteraction,
                                decoration: InputDecoration(
                                  contentPadding: EdgeInsets.symmetric(
                                      vertical:
                                          (screenWidth > 600) ? 1.5.h : 2.h,
                                      horizontal: 4.w),
                                  labelText: "Username",
                                  labelStyle: (screenWidth > 600)
                                      ? TabLabelTextStyleforLogin()
                                      : LabelTextStyleforLogin(),
                                  filled: true,
                                  fillColor: ColorConstants.white,
                                  border: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants.textFormBorder),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  errorBorder: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants
                                            .errorInputBorderColor),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  focusedErrorBorder: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants
                                            .errorInputBorderColor),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  errorStyle: (screenWidth > 600)
                                      ? TabErrorInputTextStyleforLogin()
                                      : ErrorInputTextStyleforLogin(),
                                ),
                                style: (screenWidth > 600)
                                    ? TabInputTextStyleforLogin()
                                    : InputTextStyleforLogin(),
                                inputFormatters: [
                                  FilteringTextInputFormatter.deny(
                                      RegExp(r"\s\b|\b\s")),
                                  FilteringTextInputFormatter.deny(
                                      RegExp(r'\s'))
                                ],
                                
                                validator: (value) {
                                  if (value!.isEmpty) {
                                    return "Enter username";
                                  }
                                  return null;
                                },
                                
                                onChanged: (value) {
                                  setState(() {
                                    errorMessage = null;
                                  });
                                },
                                
                              ),
                            ),
                            HoriVertiPadding(verticalPadding: 1.5.h),
                            MediaQuery(
                              data: MediaQuery.of(context).copyWith(
                                  textScaler: const TextScaler.linear(1.0)),
                              child: TextFormField(
                                controller: _passwordController,
                                obscureText: hidePassword,
                                autovalidateMode:
                                    AutovalidateMode.onUserInteraction,
                                style: (screenWidth > 600)
                                    ? TabInputTextStyleforLogin()
                                    : InputTextStyleforLogin(),
                                inputFormatters: [
                                  FilteringTextInputFormatter.deny(
                                      RegExp(r'\s'))
                                ],
                                decoration: InputDecoration(
                                  contentPadding: EdgeInsets.symmetric(
                                      vertical:
                                          (screenWidth > 600) ? 1.5.h : 2.h,
                                      horizontal: 4.w),
                                  labelText: "Password",
                                  labelStyle: (screenWidth > 600)
                                      ? TabLabelTextStyleforLogin()
                                      : LabelTextStyleforLogin(),
                                  filled: true,
                                  fillColor: ColorConstants.white,
                                  border: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants.textFormBorder),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  suffixIcon: !hidePassword
                                      ? IconButton(
                                          highlightColor: Colors.transparent,
                                          splashColor: Colors.transparent,
                                          focusColor: Colors.transparent,
                                          onPressed: () => setState(
                                            () => hidePassword = true,
                                          ),
                                          icon: const Icon(
                                              Icons.remove_red_eye_outlined,
                                              color: ColorConstants.textColor),
                                        )
                                      : IconButton(
                                          highlightColor: Colors.transparent,
                                          splashColor: Colors.transparent,
                                          focusColor: Colors.transparent,
                                          onPressed: () => setState(
                                              () => hidePassword = false),
                                          icon: const Icon(
                                              Icons.visibility_off_outlined,
                                              color: ColorConstants.textColor),
                                        ),
                                  errorBorder: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants
                                            .errorInputBorderColor),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  focusedErrorBorder: OutlineInputBorder(
                                    borderSide: const BorderSide(
                                        color: ColorConstants
                                            .errorInputBorderColor),
                                    borderRadius: BorderRadius.circular(1.w),
                                  ),
                                  errorStyle: (screenWidth > 600)
                                      ? TabErrorInputTextStyleforLogin()
                                      : ErrorInputTextStyleforLogin(),
                                ),
                                validator: (value) {
                                  if (value!.isEmpty) {
                                    return "Enter password";
                                  }
                                  return null;
                                },
                                onChanged: (value) {
                                  setState(() {
                                    errorMessage = null;
                                  });
                                },
                              ),
                            ),
                            HoriVertiPadding(
                                verticalPadding:
                                    (screenWidth > 600) ? 2.h : 3.h),
                          ],
                        ),
                      ),
                    ),
                    SizedBox(
                      height: (screenWidth > 600) ? 5.h : 6.h,
                      child: ButtonWidget(
                        buttonText: "Login",
                        fontSize: (screenWidth > 600) ? 8.sp : 12.sp,
                        onButtonPressed: () async {
                          try {
                            FocusScope.of(context).unfocus();
                            if (formkey.currentState!.validate()) {
                              var response = await ApiProvider().login(
                                  _usernameController.text,
                                  _passwordController.text,
                                  context);
                              if (response != null) {
                                if (response.toString() ==
                                        ('''{"status":0}{"status":401}''') ||
                                    response.toString() ==
                                        ('''{"status":101}{"status":401}''')) {
                                  setState(() {
                                    errorMessage =
                                        "Invalid username or password, try again";
                                  });
                                } else {
                                  setState(() {
                                    resetErrorMessage();
                                  });

                                  ///Adjustment to avoid 2nd object of json
                                  var replacedCharacterString = response
                                      .toString()
                                      .replaceAll("}{", "}}{");

                                  ///remove 2nd object from string
                                  var splitData = replacedCharacterString
                                      .toString()
                                      .split('''}{"background_color''').first;

                                  /// decode 1st object of response
                                  var data = json.decode(splitData);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants()
                                          .username,
                                      value: _usernameController.text);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants().userId,
                                      value: data['user_id']);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants()
                                          .fullName,
                                      value: data['fullname']);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants()
                                          .mobileNo,
                                      value: data['mobile_no']);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants()
                                          .username,
                                      value: data['user_name']);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants()
                                          .authToken,
                                      value: data['auth_token']);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants()
                                          .currentPassword,
                                      value: _passwordController.text);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants()
                                          .doctorProfilePicture,
                                      value: data['profile_picture']);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants()
                                          .reportDefaultLanguage,
                                      value: data['language_code_2']);
                                  await MySharedPreferences().setBoolValue(
                                      key: LocalStorageStringConstants()
                                          .isLoggedIn,
                                      value: true);
                                  await MySharedPreferences().setStringValue(
                                      key: LocalStorageStringConstants().roleId,
                                      value: data['role_id']);
                                  if (data['role_id'] == '1') {
                                  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging.instance;
                                  _firebaseMessaging.getToken().then((String? token) {
                                    if (token != null) {
                                      // Call the updateFCMtoken function to update the FCM token
                                      ApiProvider().updateFCMtoken(context: context, fcmToken: token).then((response) {
                                        if (response['status'] == 1) {
                                          // If the update was successful, fetch topics list
                                          Future fetchTopics = ApiProvider().fetchTopicsList(context: context);
                                          fetchTopics.then((topicsResponse) {
                                            List<dynamic> topics = topicsResponse['topics'];
                                            // Subscribe to each topic
                                            topics.forEach((topic) {
                                              _firebaseMessaging.subscribeToTopic(topic);
                                            });
                                             isNav = true;
                                            // Navigate to DashboardScreen
                                            Navigator.pushReplacementNamed(context, "/DashboardScreen");
                                          }).catchError((error) {
                                            // Handle error fetching topics
                                            print('Error fetching topics: $error');
                                          });
                                        } 
                                      }).catchError((error) {
                                        // Handle any errors that occur during the updateFCMtoken function call
                                        print('Error updating FCM token: $error');
                                      });
                                    }
                                  });
                                    // Navigator.pushReplacementNamed(
                                    //     context, "/DashboardScreen");
                                  } else if (data['role_id'] == '2') {
                                    Navigator.pushReplacementNamed(
                                        context, "/PatientsHomeScreen");
                                  }
                                }
                              }
                              // }
                            }
                          } catch (e) {
                            print(e.toString());
                          }
                        },
                      ),
                    ),
                    HoriVertiPadding(
                      verticalPadding: 3.h,
                    ),
                    Visibility(
                      child: Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10.w),
                        child: InkWell(
                          onLongPress: () {},
                          onDoubleTap: () {},
                          onHighlightChanged: (value) {},
                          onFocusChange: (value) {},
                          highlightColor: Colors.transparent,
                          focusColor: Colors.transparent,
                          splashColor: Colors.transparent,
                          child: Center(
                              child: Text(
                            "Forgot password?",
                            style: (screenWidth > 600)
                                ? TabSubTextStyleforLogin()
                                : SubTextStyleforLogin(),
                            textScaler: const TextScaler.linear(1.0),
                          )),
                          onTap: () {
                            Navigator.pushReplacementNamed(
                                context, "/ForgotPasswordScreen",
                                arguments: {'isDrawerMenu': false});
                          },
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 2.h,
                    ),
                    Row(
                      children: <Widget>[
                        Text(
                          "Don\'t have an account ?",
                          style: (screenWidth > 600)
                              ? TabSub2TextStyleforLogin()
                              : Sub2TextStyleforLogin(),
                          textScaler: const TextScaler.linear(1.0),
                        ),
                        SizedBox(
                          width: 2.w,
                        ),
                        InkWell(
                          child: Text(
                            'Sign up',
                            style: (screenWidth > 600)
                                ? TabSub5TextStyleforLogin()
                                : Sub5TextStyleforLogin(),
                            textScaler: const TextScaler.linear(1.0),
                          ),
                          onTap: () async {
                            Navigator.pushNamed(
                                context, "/SignUpOnboardingScreen");
                          },
                          onLongPress: () {},
                          onDoubleTap: () {},
                          onHighlightChanged: (value) {},
                          onFocusChange: (value) {},
                          highlightColor: Colors.transparent,
                          focusColor: Colors.transparent,
                          splashColor: Colors.transparent,
                        )
                      ],
                      mainAxisAlignment: MainAxisAlignment.center,
                    ),
                    HoriVertiPadding(
                        verticalPadding: (screenWidth > 600) ? 3.h : 5.h),
                    Divider(
                      color: Colors.grey,
                      thickness: 0.2.w,
                    ),
                    HoriVertiPadding(verticalPadding: 2.h),
                    Center(
                        child: Text(
                      "By continuing, you agree to our",
                      style: (screenWidth > 600)
                          ? TabSub3TextStyleforLogin()
                          : Sub3TextStyleforLogin(),
                      textScaler: const TextScaler.linear(1.0),
                    )),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        InkWell(
                          onLongPress: () {},
                          onDoubleTap: () {},
                          onHighlightChanged: (value) {},
                          onFocusChange: (value) {},
                          highlightColor: Colors.transparent,
                          focusColor: Colors.transparent,
                          splashColor: Colors.transparent,
                          child: Text(
                            "Terms and conditions",
                            style: (screenWidth > 600)
                                ? TabSub4TextStyleforLogin()
                                : Sub4TextStyleforLogin(),
                            textScaler: const TextScaler.linear(1.0),
                          ),
                          onTap: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => const WebViewScreen(
                                    appBarText: "Terms and conditions",
                                    webViewUrlString:
                                        "https://om/tc/"),
                              ),
                            );
                          },
                        ),
                        Padding(
                          padding: EdgeInsets.symmetric(
                              horizontal: 2.w, vertical: 0.5.h),
                          child: Text(
                            "|",
                            style: TextStyle(
                                fontSize: 10.sp,
                                color: ColorConstants.darkGrey),
                            textScaler: const TextScaler.linear(1.0),
                          ),
                        ),
                        InkWell(
                          onLongPress: () {},
                          onDoubleTap: () {},
                          onHighlightChanged: (value) {},
                          onFocusChange: (value) {},
                          highlightColor: Colors.transparent,
                          focusColor: Colors.transparent,
                          splashColor: Colors.transparent,
                          child: Text(
                            "Privacy policy",
                            style: (screenWidth > 600)
                                ? TabSub4TextStyleforLogin()
                                : Sub4TextStyleforLogin(),
                            textScaler: const TextScaler.linear(1.0),
                          ),
                          onTap: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => const WebViewScreen(
                                    appBarText: "Privacy policy",
                                    webViewUrlString:
                                        "https://www.y/"),
                              ),
                            );
                          },
                        ),
                      ],
                    )
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  void resetErrorMessage() {
    setState(() {
      errorMessage = null;
    });
  }
}`

**Comment by huycozy** [comment]
The sample code field is still empty, could you double check? 

>i created new project with flutter 3.19.4 and use Text Form Field, and it was working fine on that application

If so, you should check your code implementation as I suggested above to find the cause. It could come from 3rd package you use or login inside your code with TextField, etc..

**Comment by mrunal-atreya** [comment]
@huycozy I made a new project and copied and pasted the login screen for a sample, but in that project it worked fine. I mean the keypad visible on a new project.
so I don't understand what code sample I should provide you.

**Comment by huycozy** [comment]
So, it seems the issue can come from your implementation in the project or some plugins/packages you are using. Unfortunately, we can't assist with your project. You may take a look at your activity attributes in AndroidManifest.xml file (configChanges, windowSoftInputMode, etc) or implementation on your TextField.
