### ISSUE TITLE
[in_app_purchase]  How to Use Promotional Offers for iOS Subscriptions

### ISSUE THREAD

**Issue by xiaolongwuhpu** [flutter/flutter#145898]
### Description:
I'm trying to implement promotional offers for iOS subscriptions using the [in_app_purchase] library. For example: offering the first week for free or providing a discount for the first year. 
In my Android project, I've successfully implemented these offers using the following code:

```dart
 late PurchaseParam purchaseParam;
    if (Device.isAndroid) {
// Code snippet for implementing promotional offers in Android
// Different promotional offers have different ProductDetails, making it easy to implement them
      purchaseParam = GooglePlayPurchaseParam(productDetails: productDetails, changeSubscriptionParam: null);
    } else if(Device.isIOS) {
      purchaseParam = AppStorePurchaseParam(
        productDetails: productDetails,
        discount: SKPaymentDiscountWrapper(identifier: '', keyIdentifier: '', nonce: '', signature: "", timestamp: DateTime.now().millisecondsSinceEpoch),
      );
    }
    bool paySuccess = await _inAppPurchase.buyNonConsumable(purchaseParam: purchaseParam);
```
![screenshot-20240328-220405](https://github.com/flutter/flutter/assets/13296347/c72e53d0-450d-4019-bef2-32d097ac6495)

However, I'm unsure about how to achieve the same in iOS. Can someone please provide detailed guidance? I've gone through the documentation [here](https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_subscription_offers_in_your_app/) but couldn't grasp it entirely. Do we need our server to generate signatures for this?

Thank you for any assistance you can provide!
```dart
if(Device.isIOS) {
      purchaseParam = AppStorePurchaseParam(
        productDetails: productDetails,
        discount: SKPaymentDiscountWrapper(identifier: '', keyIdentifier: '', nonce: '', signature: "", timestamp: DateTime.now().millisecondsSinceEpoch),
      );
    }
```
Where can I obtain the parameters for this class SKPaymentDiscountWrapper, and how should I construct this object? Are there any alternative approaches to achieve this?

doc: https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/generating_a_signature_for_promotional_offers?language=objc

**Comment by huycozy** [comment]
Hi @xiaolongwuhpu 
The promotional offers request on iOS has been implemented by https://github.com/flutter/plugins/pull/4458 (issue https://github.com/flutter/flutter/issues/92231). 

It depends on your subscription type to be able to get offers, please check this answer for the detail: https://github.com/flutter/flutter/issues/92872#issuecomment-971649404. There is also outlined: you can find discount from `SKProductWrapper.discounts` or `SKPaymentWrapper.paymentDiscount`. I check this quickly with package example and see you may get it through `SKPaymentTransactionWrapper transaction`, for e.g: `transaction.payment.paymentDiscount`.

https://github.com/flutter/packages/blob/1f208aa26454fb4debdfd1ebed9ee0d918b93c9a/packages/in_app_purchase/in_app_purchase/example/lib/main.dart#L502

Also, this is more of a `how-to` question than a bug or feature request. I see there is a known issue asking the example for this: https://github.com/flutter/flutter/issues/51757. So I would suggest you ask the same there (if my suggest above doesn't work) that may help to raise the issue. I will go ahead and close this in favor of that one. Thanks!
