### ISSUE TITLE
[camera] Disposal of camera controller should set the controller to null

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#145844]
### Steps to reproduce

1. add 'camera' package dependency in pubspec.yaml
2. create a controller e.g. like so: 
```
CameraController? _controller = CameraController(
          firstCamera,
          ResolutionPreset.max,
        );
```
2. init the camera controller: `await _controller?.initialize();`
3. dispose the camera controller: `_controller?.dispose()`
4. `_controller` variable is still the same as before even though it was disposed

### Expected results

I expect the camera Controller being null after disposing it 

### Actual results

it's still the same even though it is disposed, so now I have to manually dispose it like so:

```
  Future disposeController() async {
    await _controller?.dispose().catchError((onError) => throw onError);
    _controller = null;
  }
 ```
 
 instead what I had before which was 1. more intuitive 2. simpler 3. and wouldn't not create unnecessary bugs like in my case:
 
 ```
   Future disposeController() async => await _controller?.dispose().catchError((onError) => throw onError);
  ```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2 23C64 darwin-arm64, locale en-US)
    • Flutter version 3.16.9 on channel stable at /Users/tomasbaran/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (9 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tomasbaran/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/tomasbaran/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • iPhone (mobile)      • 00008020-000415840E50003A • ios            • iOS 17.3.1 21D61
    • iPhone Mini (mobile) • 00008101-00126D543AA0001E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 123.0.6312.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
> wouldn't not create unnecessary bugs like in my case

Could you elaborate on which bug was created in your case? Per my understanding, `_controller` is a nullable variable of `CameraController`, you can set it to null manually, right?

**Comment by tomasbaran** [comment]
@huycozy Thanks for your comments. It's more of a suggestion and I'm not even sure whether it's a good idea. Just sharing my experience.

- Yes, I can set it to null manually. 

- I expected that disposing of the controller would also set it to null: maybe I was having a wrong expectation. So, that caused the bugs since the next time I was trying to access the controlled the disposed one was not a null but lived in a _controller variable.

- I fixed the bug by manually setting it to null. I was just trying to see whether it would not be a good idea to set it to null at disposal automatically. I'd love to your views on that.

**Comment by huycozy** [comment]
>to set it to null at disposal automatically

Hi. I think this is quite clear. The **`it`** here is your `CameraController` instance that should be handled at the level of your code. 

This doesn't seem to be an appropriate bug or feature request, so I'm going to close the issue. If you disagree, please write in the comments with more information and I will reopen it.
