### ISSUE TITLE
[flutter infra] assertion errors when scheduling builds

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#145869]
[build link](https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Mac%20engine_release_builder/553/overview)

This happens after the LUCI outage was resolved. would need this to pass to unblock the tests on new code signing certificate.

**Comment by XilaiZhang** [comment]
It was pointed out in [chat link](https://chat.google.com/room/AAAAQFWU2Go/nuEuMXaukYY) that cps such as https://flutter-review.googlesource.com/c/recipes/+/56680, https://flutter-review.googlesource.com/c/recipes/+/56681 are needed for the 18.18 candidate branch

**Comment by keyonghan** [comment]
I believe this has been fixed. Please reopen if anything else is still needed here.
