### ISSUE TITLE
„ "  double quotes in German language is not working properly 

### ISSUE THREAD

**Issue by pranavo72bex** [flutter/flutter#145806]
### Steps to reproduce

 ```
Text(
             "„JETZT ANRUFEN“",
              style: TextStyle(color: Colors.red, fontSize: 30),
         ),
```

### Expected results

„JETZT ANRUFEN“

### Actual results

![Screenshot 2024-03-27 at 13 27 29](https://github.com/flutter/flutter/assets/71395812/3280d0d4-3325-4993-a622-7735a59e0a80)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.87.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@pranavo72bex 
What platform are you seeing this behavior on ?
I tried the code using latest stable version running on Android which gave me expected result:

<img width="287" alt="Screenshot 2024-03-27 at 3 30 31 PM" src="https://github.com/flutter/flutter/assets/67046386/d228b04d-ddb7-462b-bb3d-fd072d4b69e4">

**Comment by pranavo72bex** [comment]
> @pranavo72bex What platform are you seeing this behavior on ? I tried the code using latest stable version running on Android which gave me expected result:
> 
> <img alt="Screenshot 2024-03-27 at 3 30 31 PM" width="287" src="https://private-user-images.githubusercontent.com/67046386/317216736-d228b04d-ddb7-462b-bb3d-fd072d4b69e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzU3MTIsIm5iZiI6MTcxMTUzNTQxMiwicGF0aCI6Ii82NzA0NjM4Ni8zMTcyMTY3MzYtZDIyOGIwNGQtZGRiNy00NjJiLWJiM2QtZmQwNzJkNGI2OWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEwMzAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZGM1ZWExYTlkYTk5YTVmYTE4NTc2NDBkZjBlODEzNDc2ZGJlYmExNzFmYmZmZTdiMjAxYjUzNjg1YzMwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXGBHoL9s1DMXlbtDH_xiOmBG5sqiEPjYHJXiJR5cH8">

![Screenshot 2024-03-27 at 16 33 06](https://github.com/flutter/flutter/assets/71395812/2f81a7be-43af-42dc-8b90-2d0a67874c31)

 Thank you for your quick response. yes you are right but it is not giving me expected result in my project. let me further investigate and let you know.
