### ISSUE TITLE
[Camera] Proper physical camera support on Android

### ISSUE THREAD

**Issue by kvanry** [flutter/flutter#145800]
### Use case

Camera2 allows selecting which physical cameras a developer would like to use. This currently isn't possible with Flutter and only allows logical camera ids to be used. We have an app that takes photos somewhat close, but bases capture on object detection and swapping cameras during this process actually shifts the relevant subject out of frame and causes lighting to change briefly.

### Proposal

Add support for physical camera ids in the flutter package.

**Comment by huycozy** [comment]
Adding Android documentation: https://developer.android.com/media/camera/camera2/multi-camera

**Comment by reidbaker** [comment]
I defer to @camsim99 but I believe this is actually counter to the goals of the camera plugin. Spefifically requesting physical camera is error prone to do in a reliable way across all devices and multiple os's. It sounds like this might be the core of your business and if that is the case I might recommend building a plugin that does what you need using the camera 2 apis or seeing if another plugin has the functionality you need.
