### ISSUE TITLE
Getting SMS autofil to work without appsignature and complicated requirements.

### ISSUE THREAD

**Issue by nicolasvahidzein** [flutter/flutter#145912]
### Steps to reproduce

So there is a package called sms_autofill that many people are using and praising but it doesn't sit well with me. On ios you do not need to do anything because the OS itself sees you are in a textfield and when the SMS comes in it offers the option below which is nice. It does not autofill it but fine. On Android that behavior does not exist so we must go the autofil route. However having to add a nasty signature and a # doesn't make sense and is ugly. Secondly major apps like whatsapp and other big names do not have to do that so there seems to be a double standard. How can i get to retrieve my SMS code with those requirements please? 

### Expected results

I should be able to retrieve my SMS code.

### Actual results

It is not working.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 3.16.0 on channel stable at C:\Flutter\live
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (4 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\SDK
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = C:\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio2\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\Nicolas Zein\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] VS Code (version 1.71.0-insider)
    • VS Code at C:\Users\Nicolas Zein\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • SM M305F (mobile) • 5200c783423086e7 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.10586]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 122.0.6261.131

[√] Network resources
    • All expected network resources are available.

**Comment by moffatman** [comment]
This is not any issue with Flutter, any app on Android has to work with these rules. Maybe you gave WhatsApp permission to READ_SMS for its messaging features... but that is not appropriate for general non-messaging apps.

**Comment by nicolasvahidzein** [comment]
I'm sure you've used whatsapp and they do not ask for that permission at any point. That's my argument. They have that permission out of the box.

**Comment by moffatman** [comment]
Ok please figure out how they do that. I've never used WhatsApp on Android, maybe they have a special deal. Do you have any more info? Screenshot of a text without the app hash signature that WhatsApp was able to see without permission?

Maybe they used this API?

https://developers.google.com/identity/sms-retriever/user-consent/overview

**Comment by nicolasvahidzein** [comment]
Your WhatsApp code: 270-792

You can also tap on this link to verify your phone: v.whatsapp.com/270792

Don't share this code with others

**Comment by nicolasvahidzein** [comment]
<#> Votre compte WhatsApp sera enregistré sur un nouvel appareil

Ne donnez ce code à personne

Votre code WhatsApp : 480-350

4sgLq1p5sV6

**Comment by nicolasvahidzein** [comment]
Tricky buggers. They adjust their message depending on the platform.

**Comment by moffatman** [comment]
Oh so the clean one is on iOS?

**Comment by nicolasvahidzein** [comment]
Yes sir. Thanks for your input it was precious in figuring this out.
