### ISSUE TITLE
Getting Started: download and setup everything in 5 steps or less

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1459]
Ensure that our initial download/setup process is fairly straightforward for a new user. Assume they don't have much installed on their system. Guide them through getting everything they need and installed and confirmed to be working.

At the end, the `flutter check` (#1466) command tells the user they are Green Good To Go.

(we're pretty close here, if not complete, this is to ensure we deliver this)

**Comment by eseidelGoogle** [comment]
Our documentation is currently at flutter.io/getting-started/ and is more than 5 steps.

**Comment by sethladd** [comment]
We might be able to download Dart SDK and set PATHs for our users. That can save two steps. Adding a `flutter check` type of command can also help eliminate manual checking that things are installed correctly.

**Comment by eseidelGoogle** [comment]
@abarth has a new getting-started in progress which is significantly shorter.  I suspect that work can close this.

**Comment by sethladd** [comment]
Lovely!
