### ISSUE TITLE
Show closing labels in dart source code not visible in Android Studio

### ISSUE THREAD

**Issue by raveesh-me** [flutter/flutter#14592]
## Steps to Reproduce
Install Android Studio
Install IntelliJ IDEA Community and Ultimate
Open a Flutter App

## The Problem
In Preferences -> Editor -> General -> Appearance
the "Show closing labels in dart source code" option is available in IntelliJ IDEA IDEs but not in android studio.

### IntelliJ IDEA, community, and Ultimate
![Option Available](https://files.gitter.im/flutter/flutter/44fi/image.png)

### Android Studio
![Option Not Available](https://files.gitter.im/flutter/flutter/jLfW/sad.png)

## Logs
N/A

## Flutter Doctor

[  +17 ms] [/Users/raveesh/MyCode/SDKs/Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [/Users/raveesh/MyCode/SDKs/Flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] alpha
[        ] [/Users/raveesh/MyCode/SDKs/Flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/raveesh/MyCode/SDKs/Flutter/] git log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 2e449f06f0a3be076e336ad6b30b0e9ec99dbdfe
[        ] [/Users/raveesh/MyCode/SDKs/Flutter/] git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 11 days ago
[        ] [/Users/raveesh/MyCode/SDKs/Flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +14 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.0.21-0-g2e449f06f
[ +181 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +64 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.0
[ +185 ms] [✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-IN, channel alpha)
[   +1 ms]     • Flutter version 0.0.21 at /Users/raveesh/MyCode/SDKs/Flutter
[        ]     • Framework revision 2e449f06f0 (11 days ago), 2018-01-29 14:26:51 -0800
[        ]     • Engine revision 6921873c71
[        ]     • Tools Dart version 2.0.0-dev.16.0
[        ]     • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a
[   +9 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +57 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.0
[ +107 ms] java -version
[  +91 ms] [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[        ]     • Android SDK at /Users/raveesh/Library/Android/sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-27, build-tools 27.0.3
[        ]     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
[ +163 ms] DevToolsSecurity -status
[  +56 ms] Developer mode is currently enabled.
[        ] python -c import six
[  +71 ms] idevice_id -h
[  +11 ms] idevice_id -h
[  +22 ms] idevice_id -l
[  +23 ms] ideviceinstaller -h
[   +9 ms] ios-deploy --version
[  +16 ms] ios-deploy --version
[  +18 ms] 1.9.2
[   +2 ms] ios-deploy --version
[  +15 ms] ios-deploy --version
[  +19 ms] 1.9.2
[   +2 ms] pod --version
[ +514 ms] pod --version
[ +483 ms] 1.3.1
[   +2 ms] pod --version
[ +479 ms] 1.3.1
[   +1 ms] [✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 9.2, Build version 9C40b
[        ]     • ios-deploy 1.9.2
[        ]     • CocoaPods version 1.3.1
[   +1 ms] [✓] Android Studio (version 3.0)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
[   +2 ms] /usr/bin/defaults read /Users/raveesh/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app/Contents/Info CFBundleShortVersionString
[  +65 ms] Exit code 0 from: /usr/bin/defaults read /Users/raveesh/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app/Contents/Info CFBundleShortVersionString
[        ] 2017.3.4
[  +86 ms] [✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[        ]     • Flutter plugin version 21.2.3
[        ]     • Dart plugin version 173.4548.30
[   +4 ms] /Users/raveesh/Library/Android/sdk/platform-tools/adb devices -l
[  +17 ms] Exit code 0 from: /Users/raveesh/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +5 ms] idevice_id -h
[  +21 ms] /usr/bin/xcrun simctl list --json devices
[ +134 ms] /Users/raveesh/Library/Android/sdk/platform-tools/adb devices -l
[  +19 ms] List of devices attached
[   +1 ms] [-] Connected devices
[        ]     • None
[  +17 ms] "flutter doctor" took 2,909ms.
[ +107 ms] ensureAnalyticsSent: 103ms
[   +4 ms] exiting with code 0

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by diliondani** [comment]
+1

**Comment by martiwi** [comment]
Would be indeed a really nice feature to have but I don't think this is the good place for such request, it has nothing to do with Flutter.
