### ISSUE TITLE
How can I change the Cursor Color of the Textfield independent of the Primary color

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#14598]
## Steps to Reproduce

The cursor seems to default to the primary color as well as the drag handles of a textfield.
The primary color is sometimes very hard to see above a white background and I would like to change it for certain themes. I could not find a theme setting to do so. 

## Flutter Doctor

C:\Pojects\lambDev\lookatmybaby_flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (on Microsoft Windows [Version 10.0.16299.214], locale en-US, channe
l dev)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Community Edition (version 2017.2)
[√] VS Code (version 1.20.0)
[√] Connected devices

• No issues found!

**Comment by dsteinkopf** [comment]
This solved the problem for me (see #10063): add `textSelectionColor: Colors.black` to the `ThemeData` when calling the constructor of `MaterialApp` at the very "top" of the app.

**Comment by Hixie** [comment]
@ride4sun Does @dsteinkopf's solution work for you?

**Comment by zoechi** [comment]
@Hixie thanks that's working.
#15571 is related.

**Comment by unnatishah96** [comment]
They have already provided cursorColor property in ThemeData

**Comment by hitenpannu** [comment]
new MaterialApp(
    title: "Rate your Colleagues",
    theme: ThemeData(
        cursorColor: Colors.red,
    home: SplashScreen(),
  )
This worked for me

**Comment by g-balas** [comment]
Does not seems to work on my iOS device, but is working on my Android.
Should it be working ?
Flutter version stable 1.2.1

**Comment by mono0926** [comment]
@g-balas 

This should work well.

```dart
MaterialApp(
  title: "Rate your Colleagues",
  theme: ThemeData(
    cupertinoOverrideTheme: CupertinoThemeData(
      primaryColor: Colors.red,
    ),
    cursorColor: Colors.red,
    home: SplashScreen(),
  );
```

**Comment by hadasacwebit** [comment]
TextFormField(
          cursorColor: Colors.yellow,
       
        )

**Comment by flutterq** [comment]
Step By Step Guide to [flutter textfield background color on focus](https://flutterq.com/wp-admin/post.php?post=247&action=edit)

**Comment by napoettker** [comment]
return MaterialApp(               
        theme: ThemeData(            
            textSelectionTheme: TextSelectionThemeData(
              cursorColor: Colors.orange
            ) 
        ),
