### ISSUE TITLE
Replace or mitigate "magic" (dynamic) handling of the default `Tween` constructor

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#145996]
### Use case

`Tween` is one of the few cases in the Flutter framework where we rely on dynamic calls, which in turn leads to a combination of confusing behavior (descriptive errors that are thrown in debug mode, but lazily upon `lerp`, and less-useful errors in release mode).

This is best understood by reading the long scary documentation on `Tween`:

```dart
/// ## Types with special considerations
///
/// Classes with [lerp] static methods typically have corresponding dedicated
/// [Tween] subclasses that call that method. For example, [ColorTween] uses
/// [Color.lerp] to implement the [ColorTween.lerp] method.
///
/// Types that define `+` and `-` operators to combine values (`T + T → T` and
/// `T - T → T`) and an `*` operator to scale by multiplying with a double (`T *
/// double → T`) can be directly used with `Tween<T>`.
///
/// This does not extend to any type with `+`, `-`, and `*` operators. In
/// particular, [int] does not satisfy this precise contract (`int * double`
/// actually returns [num], not [int]). There are therefore two specific classes
/// that can be used to interpolate integers:
///
///  * [IntTween], which is an approximation of a linear interpolation (using
///    [double.round]).
///  * [StepTween], which uses [double.floor] to ensure that the result is
///    never greater than it would be using if a `Tween<double>`.
///
/// The relevant operators on [Size] also don't fulfill this contract, so
/// [SizeTween] uses [Size.lerp].
///
/// In addition, some of the types that _do_ have suitable `+`, `-`, and `*`
/// operators still have dedicated [Tween] subclasses that perform the
/// interpolation in a more specialized manner. One such class is
/// [MaterialPointArcTween], which is mentioned above. The [AlignmentTween], and
/// [AlignmentGeometryTween], and [FractionalOffsetTween] are another group of
/// [Tween]s that use dedicated `lerp` methods instead of merely relying on the
/// operators (in particular, this allows them to handle null values in a more
/// useful manner).
```

There are a couple of problems:

1. For users profiling dynamic calls and optimizing size, `Tween.lerp` can't be (easily) removed. For 
example, here is Flutter retaining about an extra 30kb of code, because the compiler can't tell what types are being retained:

    ```txt
    Dynamic call to + (retaining ~14635 bytes) occurs in:
        package:flutter/src/animation/tween.dart::Tween.lerp
        package:intl/src/intl/number_format.dart::NumberFormat._formatFixed@5635441731

    Dynamic call to - (retaining ~12451 bytes) occurs in:
        package:flutter/src/animation/tween.dart::Tween.lerp
        package:intl/src/intl/number_format.dart::NumberFormat._formatFixed@5635441731

    Dynamic call to * (retaining ~6221 bytes) occurs in:
        package:flutter/src/animation/tween.dart::Tween.lerp
        package:intl/src/intl/number_format.dart::NumberFormat._formatFixed@5635441731
    ```

2. The failure mode is _lazy_, that is, if I create a `Tween` that has an invalid type, I only find out when `lerp` is invoked. You could imagine server-driven logic where something is rare, and being surprised by a `NoSuchMethodError` that only occurs in release mode.

```dart
// Contrived, but this (a) both passes static analysis and (b) does not produce an error.
Tween(start: 'foo', end: 'bar');
```

### Proposal

A few proposals, from "least disruptive" to "most disruptive":

1. Create the ~2 missing "base" Tweens (`NumTween`, `OffsetTween`), and provide users with an alternative to dynamic calls in the base framework. That is, if someone wanted to, they could completely avoid the default (`Tween.new`) constructor. This could be coupled with a lint (`avoid_tween_dynamic_constructor` or similar) for users that, like the aforementioned, care about avoiding dynamic calls.

2. Change the default constructor to _eagerly_ fail if lerping is impossible. That is:

    ```dart
    Tween({
      this.begin,
      this.end,
    }) {
      // Not exactly this, illustrative purposes only.
      assert(() {
        lerp(1);
        return true;
      });
    }
    ```

    This would not help in the case where the defaults are `null`. It would be a breaking change, but
    only in the rare case where the user was constructing a `Tween` that otherwise would never be able 
    to actually run.

3. Deprecate the default constructor, possibly again combined with lints/quick fixes:

    ```dart
    @Deprecated('Use specialized *Tween type instead')
    Tween({
      this.begin,
      this.end,
    })
    ```

**Comment by Hixie** [comment]
This is definitely one of the weaker parts of the API, for sure.

I wonder if it would make sense to remove the default implementation in `Tween<T>` and move it to a new subclass `AutoTween<T>` that does what `Tween<T>` does today. Combined with something like (2) above (the assert in the constructor), this would help explain why it doesn't automatically work with any type. That should be easy enough to autofix, since we can just turn any `Tween<T>()` constructor call into a call to `AutoTween<T>()` and as far as I can tell that would just work.

One possible concern is if anyone has subclassed `Tween` and still relies on the default behaviour. Maybe a compromise solution that mostly solves the confusion while being less disruptive is to introduce an `AutoTween<T>` class but leave the default behaviour in the `Tween<T>` class, and then deprecate the `Tween<T>` constructor. (This only works though if deprecating a superclass constructor only causes lint messages for direct calls, not those using `super` from subclasses. We'd have to check that.)

(I wouldn't want to entirely get rid of the dynamic ability because there's a surprising number of types where it does work fine as a default lerp.)

**Comment by matanlurey** [comment]
I could imagine `AutoTween` or `DynamicCallTween` being a reasonable alternative.

**Comment by Hixie** [comment]
Ah, I see why we don't yet have the assert suggested above. We can only do it once we have valid values for both `begin` and `end`, but we don't know when that is until we do the actual lerp, because another weirdness of this API is that the contract is that you can mutate the `begin` and `end` properties (which is IMHO the worst part of this API) and the values only have to be valid when you finally decide to actually apply the interpolation.

**Comment by Hixie** [comment]
(Making `begin` and `end` immutable would be an incredibly heavy lift that could not be automated, which is why we haven't done it.)

**Comment by Hixie** [comment]
Without the assert, I don't think `AutoTween` really works to reduce confusion. You just end up pushing the problem to another class. That's annoying. I wish we could require the `begin` and `end` arguments on `AutoTween`, and say that they have to be valid (so we can do the assert), but again that would mean we couldn't autofix existing code. :-/

**Comment by Hixie** [comment]
FWIW, I checked and the framework uses `Tween<double>`, `Tween<Offset>`, and many other "auto" Tween types pretty heavily, so the fraction of times where someone is using `Tween` at all but not using the default `Tween` logic is probably vanishingly small.

**Comment by matanlurey** [comment]
That also could mean that auto-migrating those to `AutoTween` or `NumTween` and `OffsetTween` more likely would be easy.

**Comment by Hixie** [comment]
We can certainly introduce a new class that does the same as `Tween`, but I don't see much benefit to that. It would have all the same problems as `Tween` today, with the added pain of having more API surface to explain (a whole new class). I think it would only make sense to do that if we found a way to also add the assert on construction, but with the mutable begin/end thing and the common pattern of creating the tween without a valid begin/end, I don't see how we can do that without a disproportionately disruptive non-autofixable change.

**Comment by matanlurey** [comment]
What about introducing `NumTween` and `OffsetTween` so users at least have the option of using them (potentially coupled with a lint down the line)?

**Comment by matanlurey** [comment]
As discussed both here and on Discord, it would be hard (TM) to make this API better, including fixes like making `begin` and `end` immutable. I philosophically think we've made the wrong decision to prioritize API stability over better APIs (especially compared with all of the kinds of breaking changes we routinely apply to the Dart language and Flutter ecosystem), but I concede that I'm one person and this isn't important enough to me to push harder.

Closed as not planned.
