### ISSUE TITLE
couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by yudehai0204** [flutter/flutter#145967]
### Steps to reproduce

device NX629 ,  if use flutterProjectStruct build to mobile , crash couldn't find "libflutter.so".
but use androidProject ,it's work.
I see .the different is the task 
flutterProject task name is  Gradle task 'assembleDebug'
androidProject task name is  (tasks: [:app:assembleDebug] i)

### Expected results

work normal.

### Actual results

crash couldn't find "libflutter.so"

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [版本 10.0.22631.3374], locale zh-CN)
    • Flutter version 3.19.4 on channel stable at E:\DevSDK\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (8 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\AndroidSDK\platform-tools
    • Java binary at: E:\DevSoft\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\MrYu\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at E:\DevSoft\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\WorkSpace\DevSoft\IntelliJ IDEA 2022.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[√] Connected device (5 available)
    • SM A136U1 (mobile) • R5CT60B8WML   • android-arm    • Android 13 (API 33)
    • NX629J (mobile)    • emulator-5554 • android-x64    • Android 9 (API 28)
    • Windows (desktop)  • windows       • windows-x64    • Microsoft Windows [版本 10.0.22631.3374]
    • Chrome (web)       • chrome        • web-javascript • Google Chrome 123.0.6312.59
    • Edge (web)         • edge          • web-javascript • Microsoft Edge 119.0.2151.97

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
@yudehai0204 
Can you provide complete error log in properly formatted text ?
Also, provide detailed steps to reproduce so that we can properly address the issue.

**Comment by LarssK-TS** [comment]
I received an Crashlytics Velocity Alert email from Firebase regarding an app I have had in production for several weeks without issue.

`Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.xxxxxx.mobile_app/com.xxxxxx.mobile_app.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxxxxx.mobile_app-1/base.apk", zip file "/data/app/com.xxxxxx.mobile_app-1/split_config.en.apk", zip file "/data/app/com.xxxxxx.mobile_app-1/split_config.hdpi.apk", zip file "/data/app/com.xxxxxx.mobile_app-1/split_config.x86.apk"],nativeLibraryDirectories=[/data/app/com.xxxxxx.mobile_app-1/lib/x86, /data/app/com.xxxxxx.mobile_app-1/base.apk!/lib/x86, /data/app/com.xxxxxx.mobile_app-1/split_config.en.apk!/lib/x86, /data/app/com.xxxxxx.mobile_app-1/split_config.hdpi.apk!/lib/x86, /data/app/com.xxxxxx.mobile_app-1/split_config.x86.apk!/lib/x86, /system/lib, /vendor/lib, /data/downloads, /data/priv-downloads]]] couldn't find "libflutter.so"
`
