### ISSUE TITLE
Stage changes to `flutter/packages` as a PR that migrates to `SurfaceProducer`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#145930]
... we'll actually land it after the next stable (~1 month), this lets us check that everything is working/tests are passing (on a PR branch, it won't get merged until we're ready).

**Comment by matanlurey** [comment]
Starting work on this now.

**Comment by matanlurey** [comment]
I'm trying to work on this, but am blocked by the fact I can't open the `android` sub-directories in `flutter/packages` in Android Studio. Given the types of changes I'll need to make, I really need working IntelliSense/auto-complete to make sense of the package.

**Comment by matanlurey** [comment]
Unblocked, @stuartmorgan [graciously helped me](https://discord.com/channels/608014603317936148/1225161984627048550). Thank you!

**Comment by matanlurey** [comment]
Re-assigning to @jonahwilliams as I go out of OOO for a couple of weeks:
- https://github.com/flutter/packages/pull/6456
- https://github.com/flutter/packages/pull/6461
- https://github.com/flutter/packages/pull/6462

**Comment by jonahwilliams** [comment]
Closing as fixed

**Comment by AlexV525** [comment]
Should this reopen? All changes are being reverted (or reverting).
