### ISSUE TITLE
Android Simulator opening properly but getting stuck on runnnig of my main dart file!!

### ISSUE THREAD

**Issue by GantaVenkataKousik** [flutter/flutter#145956]
### Steps to reproduce

help me to solve this problem as soon as possible!!!
![Screenshot 2024-03-29 083136](https://github.com/flutter/flutter/assets/108796323/0150a490-2890-4515-9e82-84b039b87687)
![Screenshot 2024-03-29 083212](https://github.com/flutter/flutter/assets/108796323/f46438ab-64ce-4562-bb06-db70730e05ab)

### Actual results

I specified the right path of simulator in **Environment variables of Advanced System Properties** and also in V**SCODE simulator path everything was fine upto now** . When I am opening the simuator it was opening but **when I tried to run my main dart file** it was opening flutter app in that android and **getting stuck there** .. **no output was showing up** . I am **suffering from this problem for the last two weeks** . I don't understand two weeks back everything was good .

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

I am not getting any output on running of this command.
Intial I am able to see some output but now  , there is no output .

**Comment by huycozy** [comment]
Hi @GantaVenkataKousik 
Looking at the screenshot above which shows your project code, it's hard to say which could be the cause of the issue. 

The goal of this Github repo is not to assist in personal code or the whole package/plugin project but to improve Flutter framework reporting bugs or feature requests. If you encounter behavior that you believe could be a Flutter framework bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 

You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a minimal sample code that can produce the issue. And please share it here when you have such an example.

>I am not getting any output on running of this command.

Does it hang or produce any error when running `flutter run -v` command?

**Comment by GantaVenkataKousik** [comment]
--->>That's the problem brother , I am not sharing my code I am trying to explain on execution it was running the main file , the flutter app is running in android studio and nothing showing up as shown in the snapshot . 

--->>Intially when I installed it was good , everything was great, but now I can't understand where was this problem is araising .  I wan't a solution to this!!!!

**Comment by huycozy** [comment]
>I am not sharing my code

Please take a look at my comment above, it's not recommended sharing production/your project code because it's hard to debug the issue. It would be ideal if you could dig down the issue (as I shared above) to get a minimal sample of code causing this.

Otherwise, please share the output of `flutter run -v` which may contain information (crash stack trace for e.g) to further investigate the issue.
