### ISSUE TITLE
Update M3 sliders to new style

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#145970]
M3 sliders have an [updated look](https://m3.material.io/components/sliders/overview)

![image](https://github.com/flutter/flutter/assets/6655696/f4314e3d-06ab-4787-b5c5-87aa743c666f)
![image](https://github.com/flutter/flutter/assets/6655696/11a56b4a-d2ed-48d5-ab82-166cf5148917)

We'll need to update at least:
- thumb shape
- slider track shape
- indicator shape

I already created the thumb and slider track shapes for an internal prototype, which can serve whoever wants to implement this as a starting point. LMK and I'll send you code.

<img width="709" alt="image" src="https://github.com/flutter/flutter/assets/6655696/bb0067fa-b37f-4cbb-80ee-9397e89c3933">

**Comment by huycozy** [comment]
Hi @guidezpl, I see there is already one issue for this at https://github.com/flutter/flutter/issues/141842. So, will that issue be an umbrella issue and consider this as a specific one for implementing shapes only?

**Comment by guidezpl** [comment]
All good, I'll transfer information over and we can close this one as a duplicate.
