### ISSUE TITLE
Would like an example of using C++ Gl with Flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14591]
This is a variation on https://github.com/flutter/flutter/issues/7053 (our second-most thumbs-up'd issue at time of writing).

I commonly get requests for OpenGL support, but I'm not sure if the requestors actually want Dart OpenGL bindings (i.e. https://github.com/google/dart-gl) or rather just a good example of sharing OpenGL code between iOS and Android with Flutter.

I outlined one possible solution in:
https://github.com/flutter/flutter/issues/179#issuecomment-362338703

And I think it would be very interesting to build an example of a spinning tea-pot from openGL integrated via shared c++ code on iOS and Android using our Texture api.  I'm curious to see if an example like that would solve the user journey users are asking about with "opengl support" or if we'll want to do something more.

Thoughts? @mjohnsullivan 

Please feel free to close if this is not a useful way to track this.

**Comment by eseidelGoogle** [comment]
https://twitter.com/PaulHMason/status/961863603807637505 would suggest that at least one developer is looking to use the Flutter toolchain with OpenGL/3d which this kind of example would not help with.

**Comment by matejthetree** [comment]
Can you check how this libraries are implemented. This is what a lot of people use on other multiplatform sdks.

https://github.com/Gamua/Starling-Framework
https://github.com/mono/CocosSharp
http://www.monogame.net

**Comment by FunMiles** [comment]
I could contribute to this. But there are three obstacle that I think of at first sight:

- There is no direct dart <> C++ interface in flutter. 
- The documentation for iOS FlutterTextureRegistry simply says 'Undocumented'

I have more Android experience than iOS, but the reason I am using Flutter now is to port my app to iOS so I am willing to tackle both.

**Comment by gedw99** [comment]
I have to embed a opengl 3d app inside a flutter "window".
The code is written in golang with a tiny bit in rust. The rust code does Ledge CRDT stuff like in the XI editor and hooks into the Fuchsia ledger.

So am just flagging this here to help with the flutter teams road mapping.

I think it's possible to do the text mapping but it's more like I need access to the FBO or framebuffer at the skia level via an official flutter API maybe 
A bit like what is happening with using SDL and flutter where the direct framebuffer is exposed 


The application is for a Medical system that allows doctors and orthapaedic specialists to review 3d models and practice surgery before the real surgery. It's also used as a teaching aid

**Comment by mogol** [comment]
There is example how to work with OpenGL on iOS & Android In Flutter via plugins 
https://github.com/mogol/opengl_texture_widget_example
In demo OpenGL is done with C and Java , but in real project I use shared C(also for medical app)
It unblocks development until “native” bindings/way would come.

**Comment by LarsDu** [comment]
mogol, do you know if native opengl bindings are planned?

**Comment by gedw99** [comment]
@mogol thanks. had a look at the code and it looks easy to add my stuff to it. What the perf like though ? sorry to ask but it looks like its just pumping a texture out of the opengl side to flutter. looks dam expensive....

**Comment by mogol** [comment]
@LarsDu I have no ideas,
@gedw99 Performance is good 60fps on my devices(Nexus6P, iPhoneX), no complains from mid-level android & iOS users, also I found no visible difference vs GLKView/GLSurfaceView implementation. For my case it's ideal, I built 3d model with Flutter "native" controls & gestures.

**Comment by greg825** [comment]
Both iOS (via ObjC and Swift) and Android (via Java and Kotlin) support native openGL bindings, so why not Flutter via Dart?

**Comment by markusaksli-nc** [comment]
@greg825 https://flutter.dev/docs/resources/faq#can-i-build-3d-opengl-apps-with-flutter

C/C++ Should be fine on all channels now (see https://flutter.dev/docs/development/platform-integration/c-interop) so there shouldn't be any blockers here anymore.

**Comment by jonahwilliams** [comment]
We don't have plans (as it should be obvious at this point) to directly expose native graphics bindings via flutter, but instead via better support for native interop via dart:ffi, which allows usages of all native libraries that Flutter/Dart do not wrap.
