### ISSUE TITLE
engine should pick up strong mode flag from snapshot and not as an activity flag

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#14594]
Currently strong mode is enabled in the engine using `strong` activity flag passed when Flutter tool starts the activity. However this does not work if you are starting an app directly (e.g. release apps) - if you close an app and then open it again directly on the phone (instead of using `flutter run`) the app would crash because strong mode is not enabled in the engine.

We need to embed this flag into snapshot for profile and release builds and/or Kernel binaries for debug build.

**Comment by mraleph** [comment]
This issue is also the reason why microbenchmarks started failing on iOS: we only wired arguments for engine on Android, not on iOS

see `startApp` implementations for [iOS devices](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L150) and [iOS simulator](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L294).

We can temporary make iOS microbenchmarks run again with `--preview-dart-2` if we fix those functions.

**Comment by a-siva** [comment]
Fixed by https://github.com/flutter/engine/pull/4683
