### ISSUE TITLE
Apple privacy manifest instruction for flutter iOS plugin 

### ISSUE THREAD

**Issue by DanielFrTB** [flutter/flutter#145902]
Hello everyone,

I'm an author of a Flutter package plugin, I'm looking for information regarding Apple's recent guidelines concerning signing and Privacy Manifests. Since we are using "Flutter" and "webview_flutter_wkwebview," which are listed by Apple, it's important for us to understand the requirements.

[According to Apple](https://developer.apple.com/support/third-party-SDK-requirements/):

"Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies."

Here are my questions:

1. Signing iOS Plugin: Is it mandatory for us to add signatures for our iOS plugin?
2. Privacy Manifests: Do we need to integrate Privacy Manifests into our iOS plugin?

If signing for our SDK is required, what is the best way converting our native plugin into an XCFramework?
I've found a discussion thread on Apple's forums that addresses [this issue: digital signature for `.framework` (not xcframework)](https://developer.apple.com/forums/thread/747807)

I've noticed some Flutter packages, like "flutter_background_fetch," have already convert into XCFramework: [flutter_background_fetch commit](https://github.com/transistorsoft/flutter_background_fetch/commit/f8d4622d2d8b9daecf554ddf2a01f78ae0ea25de).

Thanks for advance

**Comment by huycozy** [comment]
Hi @DanielFrTB 
This is a known issue being tracked at https://github.com/flutter/flutter/issues/131940. Closing this issue as a duplicate, so please follow up on it for further updates.
