### ISSUE TITLE
[go_router] [WEB] pathParameters not working with deeplink

### ISSUE THREAD

**Issue by Fraa-124** [flutter/flutter#145942]
### Steps to reproduce

``` dart
...,

GoRoute(
        path: '/tag/:param1',
        builder: (context, state) {
          final term = state.pathParameters['param1'].toString();
          return CustomPage();
        },
      ),
// this is not working neither, not a path param
   GoRoute(
        path: '/tag/demo',
        builder: (context, state) {
          return CustomPage();
        },
      )
...
```

Now in a browser, setting the url as https://example.com/tag/param1  or https://example.com/tag/demo 

``` bash
The requested route name was: "/tag/param1"
There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
```
``` bash
The requested route name was: "/tag/demo"
There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
```

### Expected results

The page is loaded despite the url has pathParams or not.

### Actual results

An error is presented.

``` bash
The requested route name was: "/tag/param1"
There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
```

Version 13.2.2

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
The requested route name was: "/tag/param1"
There was no corresponding route in the app, and therefore the initial route specified will be
ignored and "/" will be used instead.
```

</details>

**Comment by huycozy** [comment]
Hi @Fraa-124 
Could you share a complete & minimal sample code? And please also share the output of `flutter doctor -v`.

I checked this issue using [package sample code](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/named_routes.dart) but couldn't reproduce it. You can also try it and confirm if it works or not.

**Comment by Fraa-124** [comment]
You are right, thank you.
