### ISSUE TITLE
examples/widgets/card_collection.dart cards get too transparent too quickly when swiping out

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#146]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Aug 25, 2015 at 21:42 GMT_
_Originally opened as https://github.com/flutter/engine/issues/824_

----

When you swipe a card out in Swipe Away, it should remain opaque for most of the swipe, and only start vanishing in the last quarter or so. But instead it is almost completely gone by half way.

**Comment by Hixie** [comment]
Actually I'm not convinced this should ever go transparent. Material doesn't fade, it moves out of the way. Although notifications on Android do this, so we should probably support it. I'll file a new bug on that.
