### ISSUE TITLE
Snackbar not showing up

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#146058]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        floatingActionButton: FloatingActionButton(onPressed: () {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Hello World!'),
            ),
          );
        }),
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}
```

```console
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Xcode build done.                                           32.3s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Connecting to VM Service at ws://127.0.0.1:62360/LRFRjLAe18o=/ws
Reloaded 1 of 701 libraries in 200ms.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
No ScaffoldMessenger widget found.
MainApp widgets require a ScaffoldMessenger widget ancestor.
The specific widget that could not find a ScaffoldMessenger ancestor was: MainApp
The ancestors of this widget were:
    : MediaQuery
        MediaQueryData(size: Size(393.0, 852.0), devicePixelRatio: 3.0, textScaler: no scaling, platformBrightness: Brightness.light, padding: EdgeInsets(0.0, 59.0, 0.0, 34.0), viewPadding: EdgeInsets(0.0, 59.0, 0.0, 34.0), viewInsets: EdgeInsets.zero, systemGestureInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, onOffSwitchLabels: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional, gestureSettings: DeviceGestureSettings(touchSlop: null), displayFeatures: [])
    : _MediaQueryFromView
        state: _MediaQueryFromViewState#ce4c0
    : _PipelineOwnerScope
    : _ViewScope
    : _RawView-[_DeprecatedRawViewKey FlutterView#34634]
        renderObject: _ReusableRenderView#835c1
    ...
Typically, the ScaffoldMessenger widget is introduced by the MaterialApp at the top of your application widget tree.

When the exception was thrown, this was the stack:
#0      debugCheckHasScaffoldMessenger.<anonymous closure> (package:flutter/src/material/debug.dart:176:7)
#1      debugCheckHasScaffoldMessenger (package:flutter/src/material/debug.dart:187:4)
#2      ScaffoldMessenger.of (package:flutter/src/material/scaffold.dart:147:12)
#3      MainApp.build.<anonymous closure> (package:flutter_application_2/main.dart:15:29)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:670:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#22     _invoke1 (dart:ui/hooks.dart:328:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

Handler: "onTap"
Recognizer: TapGestureRecognizer#7e9c2
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(370.7, 794.3)
    finalLocalPosition: Offset(49.7, 48.3)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════
```

Flutter Doctor output:

```console                                                                                                                                                              
[✓] Flutter (Channel stable, 3.19.1, on macOS 13.0.1 22A400 darwin-arm64, locale en-IN)
    • Flutter version 3.19.1 on channel stable at /Users/faizal/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (6 weeks ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/faizal/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] VS Code (version 1.88.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.84.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Connected device exceeded maximum allowed duration of 0:04:30.000000
    • 

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment]
Hi @faisalansari0367 

Looks like you're calling `ScaffoldMessenger.of` in the same widget tree as the `Scaffold`.

As the error message says, you need `ScaffoldMessenger` to be an ancestor to call `ScaffoldMessenger.of` from the `BuildContext`
```console
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
No ScaffoldMessenger widget found.
MainApp widgets require a ScaffoldMessenger widget ancestor.
```

There are two ways you can fix your code.

1. Wrap `FloatingActionButton` with a `Builder` widget.
```dart
    return MaterialApp(
      home: Scaffold(
        floatingActionButton: Builder(
          builder: (context) {
            return FloatingActionButton(onPressed: () {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Hello World!'),
                ),
              );
            });
          }
        ),
        body: const Center(
          child: Text('Hello World!'),
        ),
      ),
    );
```


2. Create `Stateless` widget for the `FloatingActionButton`
```dart
    return const MaterialApp(
      home: Scaffold(
        floatingActionButton: FAB(),
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
```

```dart
class FAB extends StatelessWidget {
  const FAB({super.key});

  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(onPressed: () {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Hello World!'),
        ),
      );
    });
  }
}
````

This allows `ScaffoldMessenger.of` to access `ScaffoldMessenger` from the `Scaffold` widget.

**Comment by faisalansari0367** [comment]
I have created a class to show snackbar all over the application but everywhere I am invoking it's throwing this error

flutter: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4738:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4752:6)
#2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:4823:12)
#3      ScaffoldMessengerState._isRoot (package:flutter/src/material/scaffold.dart:239:52)
#4      ScaffoldMessengerState._updateScaffolds (package:flutter/src/material/scaffold.dart:229:11)
#5      ScaffoldMessengerState.showSnackBar (package:flutter/src/material/scaffold.dart:322:7)
#6      SnackbarService.showSnackbar (package:widgets/widgets<…>

**Comment by faisalansari0367** [comment]
This is my class
`
import 'package:flutter/material.dart';
import 'package:fp_assets/fp_assets.dart';
import 'package:fp_theme/fp_theme.dart';
import 'package:widgets/widgets.dart';

enum SnackbarType { success, error, info, warning }

class SnackbarService {
  static final SnackbarService _singleton = SnackbarService._internal();

  factory SnackbarService() {
    return _singleton;
  }

  SnackbarService._internal();
  
  static Future<void> showSnackbar(
    String message,
    BuildContext context,
    SnackbarType type, {
    Widget? trailing,
    bool showTypeTitle = false,
    void Function()? onSnackbarAction,
    String? actionLabel,
  }) async {
    final colors = <SnackbarType, FPColor>{
      SnackbarType.success: context.fpTheme.success,
      SnackbarType.error: context.fpTheme.error,
      SnackbarType.info: context.fpTheme.blue,
      SnackbarType.warning: context.fpTheme.warning,
    };
    final bool isDarkMode = Theme.of(context).brightness == Brightness.dark;

    ///For dark theme plusSix is too transparent
    final Color bgColor = isDarkMode ? colors[type]!.minusOne : colors[type]!.plusSix;
    final snackBar = SnackBar(
      duration: const Duration(seconds: 3),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
      padding: EdgeInsets.symmetric(vertical: 10.h, horizontal: 12.w),
      margin: EdgeInsets.symmetric(horizontal: 16.w, vertical: 10.h),
      backgroundColor: bgColor,
      elevation: 2,
      action: _buildAction(actionLabel: actionLabel, onSnackbarAction: onSnackbarAction),
      content: SnackbarMessage(
        type: type,
        msg: message,
        showTypeTitle: showTypeTitle,
      ),
    );

    final messenger = ScaffoldMessenger.of(context)..removeCurrentSnackBar();
    final controller = messenger.showSnackBar(snackBar);
    await controller.closed;
  }

  static SnackBarAction? _buildAction({
    String? actionLabel,
    void Function()? onSnackbarAction,
  }) {
    final bool hasAction = actionLabel != null && onSnackbarAction != null;
    if (!hasAction) return null;
    return SnackBarAction(
      label: actionLabel,
      onPressed: onSnackbarAction,
    );
  }
}

class SnackbarMessage extends StatelessWidget {
  const SnackbarMessage({
    super.key,
    this.title,
    this.msg,
    this.msgWidget,
    this.type = SnackbarType.info,
    this.showTypeTitle = false,
    this.iconSize,
    this.showBackground,
    this.alignTop = false,
  }) : assert(msg != null || msgWidget != null);

  final String? title;
  final String? msg;
  final Widget? msgWidget;
  final SnackbarType type;
  final bool showTypeTitle;
  final double? iconSize;
  final bool? showBackground;
  final bool? alignTop;

  @override
  Widget build(BuildContext context) {
    final bool isDarkMode = Theme.of(context).brightness == Brightness.dark;

    final colors = <SnackbarType, FPColor>{
      SnackbarType.success: context.fpTheme.success,
      SnackbarType.error: context.fpTheme.error,
      SnackbarType.info: context.fpTheme.blue,
      SnackbarType.warning: context.fpTheme.warning,
    };
    return Container(
      color: showBackground == true
          ? isDarkMode
              ? colors[type]!.zero.withOpacity(0.25)
              : colors[type]!.plusSix
          : Colors.transparent,
      padding: EdgeInsets.all(showBackground == true ? 12.r : 0),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: alignTop == true ? CrossAxisAlignment.start : CrossAxisAlignment.center,
        children: [
          _buildIcon(type),
          SizedBox(width: 10.w),
          Expanded(child: _buildMessage(context)),
        ],
      ),
    );
  }

  Widget _buildMessage(BuildContext context) {
    // final isDarkMode = context.theme.brightness == Brightness.dark;
    //final bool isDarkMode = Theme.of(context).brightness == Brightness.dark;
    //final textColor = !isDarkMode ? AppColors.fpLightBg.zero : AppColors.fpDarkBg.zero;
    final textColor = context.fpTheme.textColor.zero;
    late Widget message;
    if (msgWidget != null) {
      message = msgWidget!;
    } else {
      message = AutoSizeText(
        msg!,
        style: context.fpTheme.regular.minusTwo.copyWith(
          color: textColor,
        ),
      );
    }

    if (!showTypeTitle) {
      return message;
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title ?? type.name.toUpperCase(),
          style: context.fpTheme.medium.zero.copyWith(
            color: textColor,
          ),
        ),
        message
      ],
    );
  }

  SizedBox _buildIcon(SnackbarType type) {
    SvgGenImage widget = Assets.snackbar.success;
    switch (type) {
      case SnackbarType.success:
        widget = Assets.snackbar.success;
        break;
      case SnackbarType.error:
        widget = Assets.snackbar.error;
        break;
      case SnackbarType.info:
        widget = Assets.snackbar.info;
        break;
      case SnackbarType.warning:
        widget = Assets.snackbar.warning;
        break;
    }

    return SizedBox.square(
      dimension: iconSize ?? 24.r,
      child: widget.svg(
        fit: BoxFit.contain,
      ),
    );
  }
}
`

**Comment by faisalansari0367** [comment]
Even in this hierarchy I am unable to show the snackbar it is giving me the same error
<img width="1552" alt="Screenshot 2024-04-01 at 3 46 05 PM" src="https://github.com/flutter/flutter/assets/61263149/eb3355f5-6a5b-4971-9adb-e993deb0e344">

**Comment by TahaTesser** [comment]
This looks like like an with your code. Please tty Stackoverflow.
