### ISSUE TITLE
SingleChildScrollView stutter issue.

### ISSUE THREAD

**Issue by fritsvt** [flutter/flutter#146091]
### Steps to reproduce

I've previously raised this over at Riverpod but after digging into this deeper it seems like this is related to the `single_child_scroll_view` widget.

[Related issue with code sample](https://github.com/rrousselGit/riverpod/issues/3358)

I can see this was introduced in: 3f722c1442fa07e6afc2442853bc2a7813a3ba8c
Then reverted: 0cc2eff20463bacb76782f9401812f89a9d26bdb
And then added back: c3f45240618d7b693ed067cd1a7a3b288fdc7c6b

Why has it been added back after a revert that was probably done for a reason? For our case it's very clearly this offset correction logic that is preventing us from upgrading to the latest release. @xu-baolin / @Piinks  are you able to provide some more info on why it was added back without any additional changes?

I wasn't able to find it on the [breaking changes](https://docs.flutter.dev/release/breaking-changes) page 😅 

Related to: https://github.com/flutter/flutter/issues/145078

### Expected results

No stutters.

### Actual results

Stutter on refresh when the result gets updated.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() => runApp(ProviderScope(child: MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: ActivityView());
  }
}

class ActivityView extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final activity = ref.watch(activityProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('Pull to refresh')),
      body: RefreshIndicator(
        onRefresh: () async => await ref.refresh(activityProvider.future),
        child: SizedBox(
          height: double.infinity,
          width: double.infinity,
          child: SingleChildScrollView(
            physics: const AlwaysScrollableScrollPhysics(),
            child: Column(
              children: [
                switch (activity) {
                  AsyncValue<int>(:final valueOrNull?) =>
                      Text(valueOrNull.toString()),
                  AsyncValue(:final error?) => Text('Error: $error'),
                  _ => const CircularProgressIndicator(),
                },
              ],
            ),
          ),
        ),
      ),
    );
  }
}

final activityProvider = FutureProvider.autoDispose<int>((ref) async {
  await Future.delayed(const Duration(milliseconds: 50));

  return Random().nextInt(100) + 50;
});
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@fritsvt 
The code sample provided contains flutter_riverpod which is community package. Do you get the same stutter behavior without using that package ? If so, please provide us updated code sample without third party implementation.


> Related to: #145078

Can you also elaborate as how this behavior is different from the linked issue ?

**Comment by PurplePolyhedron** [comment]
> @fritsvt The code sample provided contains flutter_riverpod which is community package. Do you get the same stutter behavior without using that package ? If so, please provide us updated code sample without third party implementation.
> 
> > Related to: #145078
> 
> Can you also elaborate as how this behavior is different from the linked issue ?

I am able to reproduce the error without additional package. I believe it is the same issue as https://github.com/flutter/flutter/issues/145078 
```
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.purple),
        useMaterial3: true,
      ),
      home: ActivityView(),
    );
  }
}

class TextBody extends StatefulWidget {
  const TextBody({super.key});

  @override
  State<TextBody> createState() => _TextBodyState();
}

class _TextBodyState extends State<TextBody>
    with SingleTickerProviderStateMixin {
  late AnimationController controller;

  @override
  void initState() {
    super.initState();
    controller = AnimationController(
        duration: const Duration(hours: 1), vsync: this, upperBound: 3600)
      ..animateTo(3600, duration: const Duration(hours: 1));
  }

  String round(double value) {
    return '${value.ceil()}.${["0", "5"][(value * 2).ceil() % 2]} seconds';
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: AnimatedBuilder(
        animation: controller,
        builder: (context, child) {
          return Text(
            round(
              controller.value,
            ),
            style: TextStyle(fontSize: 30),
          );
        },
      ),
    );
  }
}

class ActivityView extends StatelessWidget {
  const ActivityView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Pull to refresh')),
      body: SizedBox(
        height: double.infinity,
        child: SingleChildScrollView(
            physics: const AlwaysScrollableScrollPhysics(), child: TextBody()),
      ),
    );
  }
}
```

**Comment by fritsvt** [comment]
Thanks @PurplePolyhedron for reproducing it without Riverpod!

**Comment by fritsvt** [comment]
Another code sample converting my original to show the issue without riverpod.

```
import 'dart:math';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: ActivityView());
  }
}

class ActivityView extends StatefulWidget {
  @override
  State<ActivityView> createState() => _ActivityViewState();
}

class _ActivityViewState extends State<ActivityView> {
  String name = "Pull me";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Pull to refresh')),
      body: RefreshIndicator(
        onRefresh: () async {
          // await Future.delayed(const Duration(seconds: 1));
          setState(() {
            name = "${Random().nextInt(100) + 50}";
          });
        },
        child: SizedBox(
          height: double.infinity,
          width: double.infinity,
          child: SingleChildScrollView(
            physics: const AlwaysScrollableScrollPhysics(),
            child: Column(
              children: [
                Text(name),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
Thanks for the update. I believe you are hitting https://github.com/flutter/flutter/issues/145078 as already mentioned and highlighted above, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
