### ISSUE TITLE
Unable to launch app on android device

### ISSUE THREAD

**Issue by Adam-Vandervorst** [flutter/flutter#14604]
## Steps to Reproduce

From both IDEA as CLI (Flutter/adb devices) the device is recognized correctly.
When I run it it seems to lose connection.
`adb not responding` is shown by the intellij-flutter output, please find below the flutter verbose output.

This may be more of a graphical issue with intellij-flutter, but for completeness:
When the adb server is manually killed `No devices found with name or id matching '6127002886'` is shown on run some of the times, 
```
Error retrieving device properties for ro.product.cpu.abi:
error: closed

Launching lib/main.dart on Pixel C in debug mode...
Initializing gradle...
Resolving dependencies...
Unexpected failure from adb: Invalid argument(s): The source must not be null
Error launching application on Pixel C.
```
other times.

## Related issues
https://github.com/flutter/flutter-intellij/issues/1097
https://github.com/flutter/flutter/issues/2167
## Logs

```
                   BUILD SUCCESSFUL
                   
                   Total time: 0.668 secs
[   +6 ms] /home/adamv/sdk-tools-linux-3859397/build-tools/27.0.3/aapt dump badging build/app/outputs/apk/app.apk
[   +7 ms] Exit code 0 from: /home/adamv/sdk-tools-linux-3859397/build-tools/27.0.3/aapt dump badging build/app/outputs/apk/app.apk
[        ] package: name='com.yourcompany.gapp' versionCode='1' versionName='1.0' platformBuildVersionName='7.1.1'
           sdkVersion:'16'
           targetSdkVersion:'25'
           uses-permission: name='android.permission.INTERNET'
           application-label:'g_app'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='g_app' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.yourcompany.gapp.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'arm64-v8a' 'x86' 'x86_64'
[   +4 ms] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb -s 6127002886 logcat -v time -t 1
[  +73 ms] Exit code 0 from: /home/adamv/sdk-tools-linux-3859397/platform-tools/adb -s 6127002886 logcat -v time -t 1
[        ] --------- beginning of main
           02-09 21:24:00.005 W/android.os.Debug(  373): failed to get memory consumption info: -1
[   +2 ms] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb -s 6127002886 logcat -v time
[ +242 ms] DependencyChecker: nothing is modified after 2018-02-09 20:55:52.772.
[   +2 ms] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb version
[  +10 ms] Android Debug Bridge version 1.0.39
           Version 0.0.1-4500957
           Installed as /home/adamv/sdk-tools-linux-3859397/platform-tools/adb
[   +1 ms] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb start-server
[   +6 ms] Building APK
[   +2 ms] Running 'gradlew assembleDebug'...
[   +1 ms] [android/] /home/adamv/IdeaProjects/G-mobile/android/gradlew -Ptarget=/home/adamv/IdeaProjects/G-mobile/lib/main.dart -Ptarget-platform=android-arm64 assembleDebug
[ +571 ms] NDK is missing a "platforms" directory.
[        ] If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/adamv/sdk-tools-linux-3859397/ndk-bundle.
[        ] If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
[  +24 ms] NDK is missing a "platforms" directory.
[        ] If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/adamv/sdk-tools-linux-3859397/ndk-bundle.
[        ] If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
[  +14 ms] Incremental java compilation is an incubating feature.
[ +106 ms] :app:flutterBuildX86Jar UP-TO-DATE
[        ] :app:preBuild UP-TO-DATE
...
[        ] :path_provider:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL
[        ] Total time: 0.912 secs
[ +413 ms] calculateSha: /home/adamv/IdeaProjects/G-mobile/build/app/outputs/apk/app.apk
[ +330 ms] Built build/app/outputs/apk/app-debug.apk (23.5MB).
[        ] /home/adamv/sdk-tools-linux-3859397/build-tools/27.0.3/aapt dump badging build/app/outputs/apk/app.apk
[   +4 ms] Exit code 0 from: /home/adamv/sdk-tools-linux-3859397/build-tools/27.0.3/aapt dump badging build/app/outputs/apk/app.apk
[        ] package: name='com.yourcompany.gapp' versionCode='1' versionName='1.0' platformBuildVersionName='7.1.1'
           sdkVersion:'16'
           targetSdkVersion:'25'
           uses-permission: name='android.permission.INTERNET'
           application-label:'g_app'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='g_app' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.yourcompany.gapp.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'arm64-v8a' 'x86' 'x86_64'
[        ] Stopping app 'app.apk' on Pixel C.
[        ] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb -s 6127002886 shell am force-stop com.yourcompany.gapp
[   +4 ms] error: device '6127002886' not found
[   +1 ms] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb -s 6127002886 shell pm list packages com.yourcompany.gapp
[   +5 ms] error: device '6127002886' not found
[   +1 ms] Exit code 1 from: /home/adamv/sdk-tools-linux-3859397/platform-tools/adb -s 6127002886 shell pm list packages com.yourcompany.gapp:
           error: device '6127002886' not found
[        ] Installing APK.
[   +1 ms] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb version
[   +3 ms] Android Debug Bridge version 1.0.39
           Version 0.0.1-4500957
           Installed as /home/adamv/sdk-tools-linux-3859397/platform-tools/adb
[        ] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb start-server
[   +5 ms] Installing build/app/outputs/apk/app.apk...
[        ] /home/adamv/sdk-tools-linux-3859397/platform-tools/adb -s 6127002886 install -r build/app/outputs/apk/app.apk
[+313341 ms] adb: error: failed to get feature set: device '6127002886' not found
                     
                     error: device '6127002886' not found
                     - waiting for device -
[   +2 ms] Error: ADB exited with exit code 255
[        ] adb: error: failed to get feature set: device '6127002886' not found
           
           error: device '6127002886' not found
           - waiting for device -
[        ] Warning: Failed to install APK.
[        ] Error launching application on Pixel C.
[  +24 ms] "flutter run" took 317,301ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:348)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:282)
<asynchronous suspension>
#3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:222)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:222)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#10     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#19     main (file:///home/adamv/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:276)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)


[ +216 ms] ensureAnalyticsSent: 211ms
[   +2 ms] exiting with code 2

```
Flutter Analyze returns clean
## Flutter Doctor
```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel dev)
    • Flutter version 0.0.25-pre.5 at /home/adamv/flutter
    • Framework revision 4ae1b5f415 (2 days ago), 2018-02-07 15:18:04 -0800
    • Engine revision 9bc2efdf47
    • Tools Dart version 2.0.0-dev.19.0
    • Engine Dart version 2.0.0-edge.ea91bc9888184d5a2fc309c36656fdd325ef503c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/adamv/sdk-tools-linux-3859397
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/adamv/sdk-tools-linux-3859397
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_144-b01)

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4127.31

[✓] Connected devices
    • Pixel C • 6127002886 • android-arm64 • Android 8.1.0 (API 27)

```

**Comment by cbracken** [comment]
Possibly related #14621

**Comment by Adam-Vandervorst** [comment]
This crash persist through recent updates, "losing connection" to the device after building the flutter app.

**Comment by dimger** [comment]
I had the same issue. In my case the problem was caused from a syntax error in pubspec.yaml

**Comment by jLynx** [comment]
Any update?

**Comment by lukaskotik** [comment]
The same issue for me. Any solution?

**Comment by Lhecks** [comment]
My device is connectedm but can't run the app

Launching lib\main.dart on MTN S630 in debug mode...
* Error running Gradle:
Exit code 1 from: C:\Users\Lhex\AndroidStudioProjects\flutter_gdg\android\gradlew.bat app:properties:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools:annotations:26.0.1.
     Required by:
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.databinding:compilerCommon:3.0.1
      > Could not resolve com.android.tools:annotations:26.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.0.1/annotations-26.0.1.pom'.
> Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.0.1/annotations-26.0.1.pom'.
               > dl.google.com
      > Could not resolve com.android.tools:annotations:26.0.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/annotations/26.0.1/annotations-26.0.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/annotations/26.0.1/annotations-26.0.1.pom'.
               > jcenter.bintray.com
   > Could not resolve com.android.tools:annotations:26.0.1.
     Required by:
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools.build:builder-model:3.0.1
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools:common:26.0.1
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools.analytics-library:shared:26.0.1
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools.analytics-library:tracker:26.0.1
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools:sdklib:26.0.1 > com.android.tools.layoutlib:layoutlib-api:26.0.1
      > Could not resolve com.android.tools:annotations:26.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.0.1/annotations-26.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.0.1/annotations-26.0.1.pom'.
          > dl.google.com
      > Could not resolve com.android.tools:annotations:26.0.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/annotations/26.0.1/annotations-26.0.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/annotations/26.0.1/annotations-26.0.1.pom'.
               > jcenter.bintray.com
   > Could not resolve commons-codec:commons-codec:1.6.
     Required by:
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools:sdklib:26.0.1 > org.apache.httpcomponents:httpclient:4.2.6
      > Could not resolve commons-codec:commons-codec:1.6.
         > Could not get resource 'https://jcenter.bintray.com/commons-codec/commons-codec/1.6/commons-codec-1.6.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/commons-codec/commons-codec/1.6/commons-codec-1.6.pom'.
               > jcenter.bintray.com
      > Could not resolve commons-codec:commons-codec:1.6.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom'.
  > Could not HEAD 'https://dl.google.com/dl/android/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom'.
               > dl.google.com
   > Could not resolve com.android.tools.external.com-intellij:intellij-core:26.0.1.
     Required by:
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.lint:lint:26.0.1 > com.android.tools.lint:lint-checks:26.0.1 > com.android.tools.lint:lint-api:26.0.1
      > Could not resolve com.android.tools.external.com-intellij:intellij-core:26.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.pom'.
               > dl.google.com
      > Could not resolve com.android.tools.external.com-intellij:intellij-core:26.0.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.pom'.
          > Could not GET 'https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.pom'.
               > jcenter.bintray.com
   > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
     Required by:
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.lint:lint:26.0.1 > com.android.tools.lint:lint-checks:26.0.1 > com.android.tools.lint:lint-api:26.0.1
      > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom'.
    > dl.google.com
      > Could not resolve com.android.tools.external.lombok:lombok-ast:0.2.3.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom'.
               > jcenter.bintray.com
   > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.1.3-2.
     Required by:
         project : > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.lint:lint:26.0.1 > com.android.tools.lint:lint-checks:26.0.1 > com.android.tools.lint:lint-api:26.0.1
      > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.1.3-2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-reflect/1.1.3-2/kotlin-reflect-1.1.3-2.pom'.
     > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-reflect/1.1.3-2/kotlin-reflect-1.1.3-2.pom'.
               > dl.google.com
      > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.1.3-2.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.1.3-2/kotlin-reflect-1.1.3-2.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.1.3-2/kotlin-reflect-1.1.3-2.pom'.
               > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

**Comment by zoechi** [comment]
@Lhecks that doesn't really look related to this issue.
It looks somewhat related to #23404 but it's still a bit different. I'd still suggest you check the discussion there and if this doesn't help create a new issue.

**Comment by zoechi** [comment]
I assume this issue is stale.

**Comment by jLynx** [comment]
@zoechi no this is not stale. My issue has not been resolved. I responded to your query and have had no response.
