### ISSUE TITLE
Request Focus within Webview

### ISSUE THREAD

**Issue by leeflix** [flutter/flutter#146050]
### Use case

We are using the webview_flutter package to show the mobile web application inside our desktop web application:

![image](https://github.com/flutter/flutter/assets/41200990/2f930d36-b28f-4db7-89d7-d42387be179a)

Problem is when we click the button in the corner to the bottom right to hide and show the webview again. There seems to focus on the textfield since there is a cursor but keyboard input is ignored. this is not the desired behaviour. trying to wrap the webview widget in a focusnode and requesting focus for the webview does not solve the problem.

### Proposal

Provide a way to give focus to the contents of the webview.

**Comment by darshankawar** [comment]
@leeflix 
Can you provide us a runnable complete reproducible code sample that shows the current behavior ?
