### ISSUE TITLE
Warning - Plugin Uses Deprecated API

### ISSUE THREAD

**Issue by malak4822** [flutter/flutter#146030]
After updating plugin to this version wihtin the build process I started to see this warning:

'''Note: /Users/malak/.pub-cache/hosted/pub.dev/firebase_app_check-0.2.1+19/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.'''

**Comment by danagbemava-nc** [comment]
This should be reported on the `flutterfire` repo. 

Closing from here. 

Thank you
