### ISSUE TITLE
[go_router] Deeplink to Root Route ('/') Not Recognized in Versions 13.2.0 and Above

### ISSUE THREAD

**Issue by kforjan** [flutter/flutter#146064]
### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Steps to reproduce

1. Setup deep linking as described in the [official Flutter documentation](https://docs.flutter.dev/ui/navigation/deep-linking)
2. Open a URL that points directly to the domain root (e.g., `www.example.com`) without any additional path

### Expected results

The app should open and the router should navigate to the `'/'` path.

### Actual results

App opens and an error page saying "GoException: no routes for location: https://www.example.com" is shown.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
 import 'package:go_router/go_router.dart';

 void main() => runApp(MaterialApp.router(routerConfig: router));

 /// This handles '/' and '/details'.
 final router = GoRouter(
   routes: [
     GoRoute(
       path: '/',
       builder: (_, __) => Scaffold(
         appBar: AppBar(title: const Text('Home Screen')),
       ),
       routes: [
         GoRoute(
           path: 'details',
           builder: (_, __) => Scaffold(
             appBar: AppBar(title: const Text('Details Screen')),
           ),
         ),
       ],
     ),
   ],
 );
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on Ubuntu 22.04.4 LTS 6.5.0-26-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Closing as duplicate.
