### ISSUE TITLE
Erroneous NumberFormat locale - pt_PT

### ISSUE THREAD

**Issue by rmpt** [flutter/flutter#146073]
### Steps to reproduce

Based on the example at https://api.flutter.dev/flutter/intl/NumberFormat/locale.html, create a NumberFormat with:
1. var formatter = NumberFormat.currency(locale: 'pt'); // or pt_PT and eu
2. formatter.format(3);
3. Result is `BRL 3,00` but should be `EUR 3,00`

### Expected results

`EUR 3,00`
The value should be formatted as EUR and not BRL. In Brasil the currency is BRL, but for pt_PT/european/native portuguese should be EUR.

### Actual results

`BRL 3,00`

### Code sample

<details open><summary>Code sample</summary>

```dart
var formatter = NumberFormat.currency(
    locale: 'pt_PT',
    decimalDigits: 2
);
formatter.format(3);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 12.7.4 21H1123 darwin-x64, locale pt-PT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2023.3.6)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @rmpt, the intl package lives in a different repository. Any issues you face using it should be reported on its repo https://github.com/dart-lang/i18n/issues

Closing from here as this is an issue with the intl package. 

Thank you
