### ISSUE TITLE
Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable

### ISSUE THREAD

**Issue by haochan9** [flutter/flutter#146029]
### Steps to reproduce

1. flutter doctor

### Actual results

Please help for this error I have changed everything from edit environment to reinstall

### Logs

flutter doctor

### Flutter Doctor output

```
PS D:\babiprojectflutter> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22621.3155], locale id-ID)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.87.2)
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: C:\Users\Lenovo Ideapad
      3\AppData\Local\Android\Sdk\platform-tools\adb.exe
[√] Network resources

! Doctor found issues in 2 categories.
```

**Comment by birmehto** [comment]
I thik this error relatted your window instll window environment tool 🔧

**Comment by haochan9** [comment]
> I thik this error relatted your window instll window environment tool 🔧

I've done everything in the environment. starting from adding the Environment variable filled with ADB.exe but still cannot

**Comment by danagbemava-nc** [comment]
This is an issue with how you have set your `ANDROID_HOME` environment variable. You should not point it to the `adb` executable which is what your flutter doctor shows above `C:\Users\Lenovo Ideapad 3\AppData\Local\Android\Sdk\platform-tools\adb.exe`

See https://www.programsbuzz.com/article/set-androidhome-environment-variable-windows-10 for how to set this up properly. 

Closing as this is an issue with your setup. 

Thank you

**Comment by haochan9** [comment]
> This is an issue with how you have set your `ANDROID_HOME` environment variable. You should not point it to the `adb` executable which is what your flutter doctor shows above `C:\Users\Lenovo Ideapad 3\AppData\Local\Android\Sdk\platform-tools\adb.exe`
> 
> See https://www.programsbuzz.com/article/set-androidhome-environment-variable-windows-10 for how to set this up properly.
> 
> Closing as this is an issue with your setup.
> 
> Thank you

ADB that has not been installed before has been installed but ADB is still Unable to run "adb", before thank you for the link
