### ISSUE TITLE
Expose CanvasKit.MakeImageFromCanvasImageSource as an alternative to createImageFromImageBitmap

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#146088]
### Use case

ImageBitmap is not always the most performant way to represent data. In the browser we can pass all sorts of things to createImageBitmap such as any MediaElement or a VideoFrame. At the moment there is not a good efficient pathway for doing this in flutter.

Resolves this problems mentioned in #144815 and #144591

### Proposal

```CanvasKit.MakeImageFromCanvasImageSource```

Should be exposed alongside createImageFromImageBitmap, perhaps with a signature such as:

```dart

ui.Image createImageFromCanvasImageSource(JSAny source)

```

**Comment by kevmoo** [comment]
Or, more likely `JSObject` – but I get your point!

**Comment by yjbanov** [comment]
Deduplicating into https://github.com/flutter/flutter/issues/144815
