### ISSUE TITLE
oknet chokes on binary charsets

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1461]
Try to render this image with Flutter on Android: 

http://media1.popsugar-assets.com/files/2014/04/04/782/n/1922398/0773bd5ca27dcc2d_thumb_temp_image345148311396632468.xxxlarge/i/Heath-Ledger-Pictures.jpg

--------- beginning of crash
E/AndroidRuntime( 9109): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime( 9109): Process: com.example.ffviewer, PID: 9109
E/AndroidRuntime( 9109): java.nio.charset.UnsupportedCharsetException: binary
E/AndroidRuntime( 9109): 	at java.nio.charset.Charset.forName(Charset.java:309)
E/AndroidRuntime( 9109): 	at com.squareup.okhttp.MediaType.charset(MediaType.java:97)
E/AndroidRuntime( 9109): 	at org.domokit.oknet.UrlLoaderImpl$StartRequestJob$1.onResponse(UrlLoaderImpl.java:251)
E/AndroidRuntime( 9109): 	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
E/AndroidRuntime( 9109): 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
E/AndroidRuntime( 9109): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 9109): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 9109): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  454):   Force finishing activity 1 com.example.ffviewer/org.domokit.sky.shell.SkyActivity
D/Atlas   (  454): Validating map...

**Comment by abarth** [comment]
We can try upgrading our oknet version.

**Comment by collinjackson** [comment]
Fixed in https://github.com/flutter/engine/commit/57b1785cd02c84e10fefaab67f06b9f7ea22c678
