### ISSUE TITLE
I want to play an audio from asset when receive firebase notification even app is in background or open

### ISSUE THREAD

**Issue by rohit0713** [flutter/flutter#146196]
### Steps to reproduce

import 'dart:io';

import 'package:c2b_vendor/providers/audio_manager.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:localstorage/localstorage.dart';

class NotificationServices {
  FirebaseMessaging messaging = FirebaseMessaging.instance;

  final FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  void requestNotificationPermission() async {
    NotificationSettings settings = await messaging.requestPermission(
      alert: true,
      announcement: true,
      badge: true,
      carPlay: true,
      criticalAlert: true,
      provisional: false,
      sound: true,
    );
    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
      print('user granted permission');
    } else if (settings.authorizationStatus ==
        AuthorizationStatus.provisional) {
      print('user granted provisional permission');
    } else {
      print('user denied permission');
    }
  }

  void initLocalNotifications(RemoteMessage message) async {
    var androidInitializationSettings =
        const AndroidInitializationSettings('@mipmap/ic_launcher');
    var iosInitializationSettings = const DarwinInitializationSettings();
    var initializationSetting = InitializationSettings(
        android: androidInitializationSettings, iOS: iosInitializationSettings);
    await _flutterLocalNotificationsPlugin.initialize(
      initializationSetting,
      onDidReceiveNotificationResponse: (payload) async {
        if (await logged()) {
          print(
              "=================Notification=====${message.notification!.title}");
        } else {
          handleMessage(message);
        }
      },
    );
  }

  void firebaseInit() async {
    FirebaseMessaging.onMessage.listen((message) {
      print(message.notification!.title.toString());
      print(message.notification!.body.toString());

      print(message.data.toString());
      final service = FlutterBackgroundService();
      service.configure(
          iosConfiguration: IosConfiguration(),
          androidConfiguration: AndroidConfiguration(
            onStart: (service) async {
              if (message.notification!.title!.contains("placed")) {
                AudioManager.play('sound_n_vendor-full.mp3');
              }
            },
            isForegroundMode: true,
          ));

      if (Platform.isIOS) {
        initLocalNotifications(message);
        forgroundMessage();
        if (message.notification!.title!.contains("Order ID")) {
          AudioManager.play('sound_n_vendor-full.mp3');
        }
      }

      if (Platform.isAndroid) {
        initLocalNotifications(message);
        showNotification(message);
        if (message.notification!.title!.contains("Order ID")) {
          print("=======Sound Play=======");
          try {
            AudioManager.play('sound_n_vendor-full.mp3');
          } catch (e) {
            print("===Exception=====$e");
          }
          // Timer? _timer;
          // // AudioManager.play('sound_n_vendor-full.mp3');
          // var pref = await SharedPreferences.getInstance();
          // // pref.reload();
          // pref.setBool('isAudioPlaying', true);
          // _timer = Timer.periodic(const Duration(seconds: 0), (timer) async {
          //   var pref = await SharedPreferences.getInstance();
          //   print("===AudioPlaying=====${pref.getBool('isAudioPlaying')}");
          //   if (pref.getBool('isAudioPlaying') == true) {
          //     AudioManager.play('sound_n_vendor-full.mp3');
          //   } else {
          //     AudioManager.stop();
          //     pref.setBool('isAudioPlaying', false);
          //     timer.cancel();
          //     _timer?.cancel();
          //   }
          // });
        }
      }
    });
    FirebaseMessaging.onBackgroundMessage((message) async {
      print("======Background Messaging==============");
      if (message.notification!.title!.contains("Order ID")) {
        AudioManager.play('sound_n_vendor-full.mp3');
      }
    });
  }

  Future<void> showNotification(RemoteMessage message) async {
    final Int64List vibrationPattern = Int64List(4);

    vibrationPattern[0] = 0;
    vibrationPattern[1] = 4000;
    vibrationPattern[2] = 4000;
    vibrationPattern[3] = 4000;
    AndroidNotificationChannel channel = AndroidNotificationChannel(
        message.notification!.android!.channelId.toString(),
        message.notification!.android!.channelId.toString(),
        importance: Importance.max,
        showBadge: true,
        playSound: true,
        vibrationPattern: vibrationPattern,
        enableVibration: true,
        sound: const RawResourceAndroidNotificationSound('jetsons_doorbell'));

    AndroidNotificationDetails androidNotificationDetails =
        AndroidNotificationDetails(
            channel.id.toString(), channel.name.toString(),
            channelDescription: 'your channel description',
            importance: Importance.high,
            priority: Priority.high,
            ticker: 'ticker');

    const DarwinNotificationDetails darwinNotificationDetails =
        DarwinNotificationDetails(
      presentSound: true,
      presentBadge: true,
      presentAlert: true,
    );

    NotificationDetails notificationDetails = NotificationDetails(
      android: androidNotificationDetails,
      iOS: darwinNotificationDetails,
    );

    Future.delayed(Duration.zero, () {
      _flutterLocalNotificationsPlugin.show(
        1,
        message.notification!.title.toString(),
        message.notification!.body.toString(),
        notificationDetails,
        payload: message.data['image'],
      );
    });
  }

  Future<String> getDeviceToken() async {
    String? token = await messaging.getToken();
    return token!;
  }

  void isTokenRefresh() {
    messaging.onTokenRefresh.listen((event) {
      event.toString();
      print('refresh');
    });
  }

  //handle tap on notification when app is in background or terminated
  Future<void> setupInteractMessage() async {
    // when app is terminated
    RemoteMessage? initialMessage =
        await FirebaseMessaging.instance.getInitialMessage();

    if (initialMessage != null) {
      handleMessage(initialMessage);
    }

    FirebaseMessaging.onMessageOpenedApp.listen((event) {
      handleMessage(event);
    });
  }

  Future<void> handleMessage(RemoteMessage message) async {
    print('handle message function');
    if (await logged()) {}
  }

  Future forgroundMessage() async {
    await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: true,
      badge: true,
      sound: true,
    );
  }

  Future<bool> logged() async {
    final LocalStorage userToken = LocalStorage('user_token');
    var token = userToken.getItem('token') ?? '';
    print('logged check ===');
    print('token======>$token');
    return Future.value(token.isNotEmpty);
  }

  backgroundMessageHandler(RemoteMessage message) {
    print("=====Receiving Message====");
    if (message.notification!.title!.contains("Order ID")) {
      AudioManager.play('sound_n_vendor-full.mp3');
    }
  }
}

import 'dart:async';
import 'dart:developer';

import 'package:c2b_vendor/firebase_options.dart';
import 'package:c2b_vendor/notification_service.dart';
import 'package:c2b_vendor/providers/all_add_ons_provider.dart';
import 'package:c2b_vendor/providers/chat_cart_provider.dart';
import 'package:c2b_vendor/providers/my_order_provider.dart';
import 'package:c2b_vendor/providers/payment_history.dart';
import 'package:c2b_vendor/providers/providers.dart';
import 'package:c2b_vendor/screen/account/service_plans/service_plan_provider.dart';
import 'package:c2b_vendor/screen/splash_Screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:localstorage/localstorage.dart';
import 'package:provider/provider.dart';
import 'package:workmanager/workmanager.dart';

final Workmanager workManager = Workmanager();

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Set the background messaging handler early on, as a named top-level function
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);

  var messaging = FirebaseMessaging.instance;
  // FCMMessaging.requestNotificationPermission(messaging);
  FirebaseMessaging.instance.getAPNSToken().then((token) {
    print("APN Token===$token");
  });
  messaging.getToken().then((token) async {
    log("Device Token==>$token");
    storeToken(token!);
  });

  runApp(const MyVendorApp());
}

// Function to store the fcm token in local storage
Future<void> storeToken(
  String fbToken,
) async {
  final localStorage = LocalStorage(
      'user_device_token'); // Replace with your desired storage key
  await localStorage.ready;
  localStorage.setItem('device_token', fbToken);
}

class MyVendorApp extends StatefulWidget {
  const MyVendorApp({super.key});

  @override
  State<MyVendorApp> createState() => _MyVendorAppState();
}

class _MyVendorAppState extends State<MyVendorApp> {
  var openOrderTab = false;
  NotificationServices notificationServices = NotificationServices();
  @override
  void initState() {
    notificationServices.requestNotificationPermission();
    notificationServices.forgroundMessage();
    notificationServices.firebaseInit();
    notificationServices.setupInteractMessage();
    notificationServices.getDeviceToken().then((value) {});
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => ProviderVendor()),
        ChangeNotifierProvider(create: (context) => PaymentHistory()),
        ChangeNotifierProvider(create: (context) => AllAddOnsProvider()),
        ChangeNotifierProvider(create: (context) => MyOrderProvider()),
        ChangeNotifierProvider(create: (context) => ChatCartProvider()),
        ChangeNotifierProvider(create: (context) => ServicePlanProvider()),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        home: SplashScreenPage(
            openOrderTab: openOrderTab), /*MyProfilePage(id: 1,)*/
      ),
    );
  }
}

### Actual results

Not getting audio sound when app is in background

### Flutter Doctor output

[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4170], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.87.2)
[√] Connected device (4 available)
[√] Network resources

**Comment by darshankawar** [comment]
@rohit0713 
Your question / issue is better suited for support channels like StackOverflow, so please ask the same there.
Clsoing from here.
