### ISSUE TITLE
AnnotatedRegion have an issue when systemNavigationBarColor has a value

### ISSUE THREAD

**Issue by AbdeMohlbi** [flutter/flutter#146197]
### Steps to reproduce

use the code given below and try to launch it.

### Expected results

statusBarIconBrightness  should follow the `Brightness` value provided and the `systemNavigationBarColor` has no affect on the `statusBarIconBrightness  `

### Actual results

the statusBarIconBrightness is set to `Brightness.dark`  but it is not in the ui 
when commenting the the `systemNavigationBarColor: Colors.black`line it works perfectly fine 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: AnnotatedRegion(
        value: const SystemUiOverlayStyle(
            statusBarColor: Color(0xffffdabe),
            statusBarIconBrightness: Brightness.dark,
            systemNavigationBarColor: Colors.black),
        child: Scaffold(
          appBar: AppBar(
            title: Text(''),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const Text(
                  'You have pushed the button this many times:',
                ),
              ],
            ),
          ),
          // This trailing comma makes auto-formatting nicer for build methods.
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

| | |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/116356835/af4c97a7-30a0-46c0-9fcd-faf3e198c8c2"> | <img width="400" src="https://github.com/flutter/flutter/assets/116356835/301b8c83-4df5-4d67-b8a9-80a6b0332b12">

### Logs

i'm using android 11 on a real device by the way 

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [version 10.0.19045.4239], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.2)
[√] Android Studio (version 2023.3)
[√] VS Code, 64-bit edition (version 1.87.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @AbdeMohlbi 
I'm checking this on my device `Realme 6, Android 11` but can't see the issue. Which device are you working on? Also, there is a device-specific issue with `Redmi Note 8` here that you can check and confirm if it's a similar one: https://github.com/flutter/flutter/issues/108855

**Comment by AbdeMohlbi** [comment]
> Hi @AbdeMohlbi 
> I'm checking this on my device `Realme 6, Android 11` but can't see the issue. Which device are you working on? Also, there is a device-specific issue with `Redmi Note 8` here that you can check and confirm if it's a similar one: https://github.com/flutter/flutter/issues/108855

I'm using `redmi note 9`
Have u tried to comment the line i mentioned and tried a hot reload or a hot restart ?

**Comment by AbdeMohlbi** [comment]
@huycozy Based on the issue u mentioned i think the java plugin that does the job has an issue with redmi devices only also i noticed a lot of issues with other things not working as expected on `redmi` devices

**Comment by huycozy** [comment]
>Have u tried to comment the line i mentioned and tried a hot reload or a hot restart ?

Yes, I did. The same result with or without `systemNavigationBarColor`:

<details>
<summary>Demo</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/504947bc-f02e-4b13-bfa1-12f987fd80d9">
</details>

I think this is a device-specific issue with SystemUiOverlayStyle on Redmi devices. I would suggest we centralize one issue at https://github.com/flutter/flutter/issues/108855. You can leave a comment there with this case which will help to diversify the problem. Closing this issue in favor of that one.
