### ISSUE TITLE
 Ensure you have network connectivity and then try again. RedirectException: Redirect loop detected

### ISSUE THREAD

**Issue by AlmostSir777** [flutter/flutter#146192]
### Steps to reproduce

when i checkout flutter to 2.10.5，has s problem，RedirectException: Redirect loop detected，i do not know how to fix it, i am fix one day 

### Actual results

$ flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading package sky_engine...                                  356ms
Downloading flutter_patched_sdk tools...                           534ms
Downloading flutter_patched_sdk_product tools...                   389ms
Downloading windows-x64 tools...                                    54ms
Downloading windows-x64 tools...                                    44ms
Failed to download https://storage.flutter-io.cn/flutter_infra_release/flutter/57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab/windows-x64/artifacts.zip. Ensure you have network connectivity and then try again.
RedirectException: Redirect loop detected

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
Hi @AlmostSir777 
Have you followed [Configuring Flutter to use a mirror site](https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site)?

If it can't make this work, please try upgrading to the latest Flutter stable version and retry (your current version is quite old)

**Comment by huycozy** [comment]
@AlmostSir777 This seems to be an issue with your network/connectivity. I would suggest you follow the guideline above or try switching to a better network. 

I'm going ahead and closing the issue. If you disagree, please write in the comments and I will reopen it.
