### ISSUE TITLE
[skwasm] Wonderous demo freezes when playing Youtube Video

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#146156]
Steps to Reproduce:

* Open: https://wonderous-kevmoo.web.app/#/home
* Scroll down in the Machu Picchu section
* Try to play the national geographic youtube video

Results:
Application freeze. The following dumps to console:
![image](https://github.com/flutter/flutter/assets/26911996/577f338f-b601-4687-85f5-88e9ac97c026)

Note: This seems to be skwasm specific, and doesn't reproduce on CanvasKit

**Comment by kevmoo** [comment]
@ditman ?

**Comment by eyebrowsoffire** [comment]
This is skwasm specific, so probably not actually directly related to renderer-agnostic platform view logic or anything like that

**Comment by ditman** [comment]
We don't even have a YouTube plugin or anything, it must be homebrew to Wonderous :P

**Comment by esDotDev** [comment]
fwiw, Wonderous is using the `youtube_player_iframe` pkg here
https://pub.dev/packages/youtube_player_iframe

**Comment by eyebrowsoffire** [comment]
I'm fairly certain this is fixed by this change here: https://github.com/flutter/engine/pull/51991

**Comment by kevmoo** [comment]
I'm watching the engine roll for https://github.com/flutter/engine/pull/51991 – once it's in the framework I'll rebuild so we can confirm!

**Comment by kevmoo** [comment]
Deployed with https://github.com/flutter/engine/pull/51991 
... and patched in https://github.com/sarbagyastha/youtube_player_flutter/pull/932 fixed things!
