### ISSUE TITLE
[camera_android_camerax] Adjustable camera flash intensity 

### ISSUE THREAD

**Issue by jamesstevensdev** [flutter/flutter#146103]
### Use case

Our company captures high-resolution eye images. While 4k resolution phones allow us to maintain a good distance from the subject's eye during capture, lower-end devices necessitate holding the phone closer for better data quality. However, this irritates the subject's eyes and washes out the images.

I have tried using third-party packages on pub.dev, but none work concurrently with the current camera implementation. This implementation is the closest I have found, but it does not work in sync with the camera package. Additionally, the developer is no longer active.

torch_light:
  git:
    url: https://github.com/svprdga/torch_light
    ref: feature/adjust_brightness_level

### Proposal

Add a call to the CameraController to set the flash/torch intensity.

PROPOSAL

await _controller!.setFlashMode(FlashMode.torch, intensity: 0.25);

-- OR --

await _controller!.setFlashIntensity(0.75);
await _controller!.setFlashMode(FlashMode.torch);

**Comment by huycozy** [comment]
Per https://source.android.com/docs/core/camera/torch-strength-control, this seems to be limited by Android API level:

"For devices running Android 13 or higher, the Android framework provides a multilevel control for torch strength. In Android 12 and lower, the framework allows only for turning the torch mode on or off...."

**Comment by gmackall** [comment]
From Android triage: Closing, as it looks like this isn't supported currently in CameraX, and the `camera_android_camerax` plugin will only support features that are officially supported by CameraX.

Here is a link to submit feature requests for CameraX https://b.corp.google.com/issues/new?component=618491&template=1257717. 

Please feel free to re-open this feature request if CameraX eventually adopts this feature.
