### ISSUE TITLE
I can't run Flutter Demo on Mac Os

### ISSUE THREAD

**Issue by stevenwsg** [flutter/flutter#146136]
### Steps to reproduce

1、In Mac os 14.4 , I use Android Studio create a flutter project only support mac os platform.
2、Run in Mac os.
3、Run failure

### Actual results

Downloading darwin-x64/FlutterMacOS.framework tools...
Downloading darwin-x64/FlutterMacOS.framework tools...
Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/e76c956498841e1ab458577d3892003e553e4f3c/darwin-x64/FlutterMacOS.framework.zip. Ensure you have network connectivity and then try again.
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = storage.googleapis.com, port = 49858

Actually, I use my chrome can download this zip form https://storage.googleapis.com/flutter_infra_release/flutter/e76c956498841e1ab458577d3892003e553e4f3c/darwin-x64/FlutterMacOS.framework.zip.

whats the problem. can you give me a solution?

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4 23E214 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by stevenwsg** [comment]
I solve  this problem by terminal 
flutter run -d macos

but come a new problem.


`
Launching lib/main.dart on macOS in debug mode...  
ProcessException: Process exited abnormally with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
  Command: xcrun xcodebuild -list -project Runner.xcodeproj
`

Does this mean i need install xcode?

**Comment by stevenwsg** [comment]
> Yes you need to install Xcode to build for mac including macOS SDK download

Thank you, I install Xcode, the problem solved

**Comment by moffatman** [comment]
Np
