### ISSUE TITLE
Error in EmojiPicker function

### ISSUE THREAD

**Issue by Praveenuhhuv** [flutter/flutter#146191]
### Steps to reproduce

I experiencing issues with the config parameter not supporting columns in the EmojiPicker widget.

### Expected results

running without error

### Actual results

[{
	"resource": "/C:/Users/dell/Desktop/pbc/pbc/lib/screens/Chat_Screen.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "undefined_named_parameter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_named_parameter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The named parameter 'columns' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'columns'.",
	"source": "dart",
	"startLineNumber": 85,
	"startColumn": 14,
	"endLineNumber": 85,
	"endColumn": 21
},{
	"resource": "/C:/Users/dell/Desktop/pbc/pbc/lib/screens/Chat_Screen.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "undefined_named_parameter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_named_parameter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The named parameter 'emojiSizeMax' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'emojiSizeMax'.",
	"source": "dart",
	"startLineNumber": 86,
	"startColumn": 14,
	"endLineNumber": 86,
	"endColumn": 26
}]

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
The flutter framework does not include an emoji picker out of the box. This seems like an issue with whatever package you are using for this purpose. You should report this on their repo so that it can be properly investigated. 

If you believe this is a flutter issue, kindly file a new issue and provide all the relevant information required to reproduce the issue. 

Closing from here. 

Thank you

**Comment by Praveenuhhuv** [comment]
i using this new version -emoji_picker_flutter: ^2.1.1
is config not provide columns property
