### ISSUE TITLE
Proposal to set boundary for the `ReorderableListView` when dragging item

### ISSUE THREAD

**Issue by illusionGeorge** [flutter/flutter#146112]
### Use case

ReorderableListView don't has API for limit drag area.
![Simulator Screen Recording - iPhone 15 Plus - 2024-04-02 at 13 13 21](https://github.com/flutter/flutter/assets/16495832/1ad7ca4e-cd47-41b8-86e0-723055e5848d)

### Proposal

ReorderableListView should provide api to limit drag area.

**Comment by illusionGeorge** [comment]
<img width="196" alt="image" src="https://github.com/flutter/flutter/assets/16495832/d187d6a7-3673-4f6e-a92e-f5280ef46033">

**Comment by darshankawar** [comment]
@illusionGeorge 
Can you check [this](https://stackoverflow.com/questions/75418523/setting-boundaries-to-reorderablelistview) and see if it helps in your case or not ?

**Comment by illusionGeorge** [comment]
I know https://stackoverflow.com/questions/75418523/setting-boundaries-to-reorderablelistview. And I tried this solution.but  it can't solve my problem.

**Comment by yiiim** [comment]
I think we need an API to limit the drag bounds, I'll work on that.

**Comment by illusionGeorge** [comment]
@yiiim I mean if this PR [https://github.com/flutter/flutter/pull/146182](url) merge success. Which flutter version will take effect in the future？

**Comment by yiiim** [comment]
> @yiiim I mean if this PR [https://github.com/flutter/flutter/pull/146182](url) merge success. Which flutter version will take effect in the future？

A stable version will be released every ~3 months, and there are also Hotfixes to the Stable Channel, refer to here: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

**Comment by illusionGeorge** [comment]
> > @yiiim I mean if this PR [https://github.com/flutter/flutter/pull/146182](url) merge success. Which flutter version will take effect in the future？
> 
> A stable version will be released every ~3 months, and there are also Hotfixes to the Stable Channel, refer to here: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

Thank you! But ehh... according to your estimate, when(month) will I be able to use it after all the procedures are completed?

**Comment by yiiim** [comment]
@illusionGeorge Hello, according to the PR review comments, adjustments may need to be made, which may take some time. I have made a temporary solution (the principle is to copy all the source code of ReorderableList. :-) ). Check here: https://github.com/yiiim/my_reorder_list.

**Comment by illusionGeorge** [comment]
@yiiim Great! Thank you for your help.

**Comment by illusionGeorge** [comment]
@yiiim ,hello,it seems that this PR [https://github.com/flutter/flutter/pull/146182](url) is still open.
