### ISSUE TITLE
need a funtion in  StatefulWidget  like initState()  but have  a context 

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#146101]
### Use case

flutter statefullwidget is great for state managment . statefullwidget  widget has two great feature  initState() and didChangeDependencies()  . but when we use statefullwidget  widget  with InheritedWidget we need    use  didChangeDependencies() for   get the data   from InheritedWidget  . but problem  is    didChangeDependencies()  call everytime when the data change .

### Proposal

```dart
class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {


  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

   @override
  void initStateWithContext() {
    super.initStateWithContext() ;
    //! same  as initState but have context so  can use context for get InheritedWidget data and call only once
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
  }
  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
```

**Comment by moffatman** [comment]
You can use InheritedWidget in initState(). Just don't register a dependency / listen to the model. e.g. `context.getInheritedWidgetOfExactType` instead of `dependOnInheritedWidgetOfExactType`.

**Comment by samithe7** [comment]
> You can use InheritedWidget in initState(). Just don't register a dependency / listen to the model. e.g. `context.getInheritedWidgetOfExactType` instead of `context.dependOnInheritedWidgetOfExactType`.

thanks
