### ISSUE TITLE
iOS Release Guide

### ISSUE THREAD

**Issue by arranf** [flutter/flutter#14629]
I've just followed the release guide for iOS as a 'fresh' iOS dev. Here are a couple of points that could use clarification

1) You recommend ticking Automatically manage signing but it appears this only works if you own an iOS device - (and it needs to be plugged in for this to work ?) It would be worth explaining how to create your own certificates and provisioning.

2) In Create a build archive the steps are laid out: Run `flutter build ios` and then do stuff in Xcode. This could use a little bit of explanation as my instinct is that after running `flutter build ios` it should be good to go but this section reads like this isn't the case. This bit is my biggest point of confusion.

3) Xcode has a number of warnings about certain Runner configuration - the guide doesn't mention whether this are normal I'm presuming it is but reassurance would be good!

**Comment by cbracken** [comment]
@arranf Thanks for the feedback! We'll look at clarifying the issues you raised in (1) and (2). For (3), we should update our Xcode templates for Xcode 9.2, which should eliminate the warnings. Some of the warnings (e.g., the one suggesting to enabled arm32 builds, which we don't currently support in an automated way) are definitely misleading.

/cc @xster

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1847](https://github.com/flutter/website/issues/1847) via [**ZenHub**](https://www.zenhub.com/)
