### ISSUE TITLE
Tab height is too small when text scale is increased

### ISSUE THREAD

**Issue by Zigotote** [flutter/flutter#146207]
### Steps to reproduce

Create a simple app with a TabBar. Run it on a mobile device and increase textScale to 200%.

### Expected results

TabBar height is increased to fit text height.

A quite similar issue exist but it's really old : https://github.com/flutter/flutter/issues/13322

### Actual results

TabBar height is fixed to 46px, so when the text is too big it is cut. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        initialIndex: 1,
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            title: const Text('TabBar Sample'),
            bottom: const TabBar(
              tabs: [Tab(text: "Tab 1"), Tab(text: "Tab 2")],
            ),
          ),
          body: const TabBarView(
            children: <Widget>[
              Center(child: Text("Page 1")),
              Center(child: Text("Page 2")),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

My app with default text scale (`MediaQuery.of(context).textScaler.scale(1)` is 1)
![Capture d’écran 2024-04-03 à 17 34 43](https://github.com/flutter/flutter/assets/34279302/287bf314-d311-4b3a-af76-6251d26e38a3)

My app with large text scale (`MediaQuery.of(context).textScaler.scale(1)` is 3)
![Capture d’écran 2024-04-03 à 17 36 34](https://github.com/flutter/flutter/assets/34279302/a087fb4e-26d1-49cf-ac8a-174ce8807771)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.4)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Thanks for the report, @Zigotote. But this is similar to https://github.com/flutter/flutter/issues/13322, we should centralize on one issue. Please also leave there a comment that will help to update the issue. Thanks!
