### ISSUE TITLE
Option + return shortkey not showing popup menu to wrap/remove widgets

### ISSUE THREAD

**Issue by iffraa** [flutter/flutter#146267]
## Steps to Reproduce

1) Click on any widget in code.
2) Click option + return.
3) Nothing shows up. Previously a popup menu to wrap/remove widgets would show up.

I searched about this issue. Quick assists powered by the Dart Analysis Server is already enabled. Im using MacBook.

## Version Info

[✓] Flutter (Channel stable, 3.19.5, on macOS 13.0 22A380 darwin-x64, locale en-US)
    • Flutter version 3.19.5 on channel stable at /Volumes/workspace/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (7 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/malhotra/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (3 available)            
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 123.0.6312.105

[✓] Network resources
    • All expected network resources are available.

**Comment by darshankawar** [comment]
@iffraa 
Do you mean the intellisense / automcomplate is not showing up ?
What IDE are you using in which you are seeing this ? VSCode or AS ?

**Comment by iffraa** [comment]
<img width="1440" alt="bug" src="https://github.com/flutter/flutter/assets/8538640/44331a0b-114f-42ca-9f06-37b174181072">
  
Im using Android Studio. I've added flutter doctor v output in my initial query. You can check that. 

While clicking on light bulb or using its respective shortkey, the popup menu to wrap/remove widgets is not showing up. I've attached image.

**Comment by darshankawar** [comment]
@iffraa 
This most probably looks like intellij - flutter plugin issue rather than framework / sdk level issue.
You'll need to report this in dedicated repo: https://github.com/flutter/flutter-intellij/issues
Closing from here.
