### ISSUE TITLE
"Try FaceID Again" Button Doesn't Do Anything

### ISSUE THREAD

**Issue by MatthewJones517** [flutter/flutter#146223]
### Steps to reproduce

1.) Using the local_auth package, trigger biometric login like so:

```dart
await _auth.authenticate(
        localizedReason: reason,
        options: AuthenticationOptions(
          biometricOnly: true,
          stickyAuth: true,
        ),
      )
```

Note that I'm intentionally not allowing passcode fallback. This is per the design specs.

2.) Attempt to log in with FaceID. 

3.) Fail with not matching face

4.) Get the "Face Not Recognized" dialogue box. Options are "Try FaceID Again" and "Cancel"

5.) Tap "Try FaceID Again"

6.) Nothing happens. 

I thought [98515](https://github.com/flutter/flutter/issues/98515) was related but the solution there was to allow for passcode fallback. I am purposefully disabling this. 

These steps were taken using the iOS Simulator. 

### Expected results

Face ID triggers again and allows the user to attempt re-authentication. 

### Actual results

Nothing happens. 

### Code sample

<details open><summary>Code sample</summary>

```dart
await _auth.authenticate(
        localizedReason: reason,
        options: AuthenticationOptions(
          biometricOnly: true,
          stickyAuth: true,
        ),
      )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by MatthewJones517** [comment]
This should be part of the local_auth package as opposed to the general Flutter project, but I wasn't sure how to specify that in GitHub.

**Comment by danagbemava-nc** [comment]
Hi @MatthewJones517, can you try this on a physical device and share your results? I tested on my iPhone XS and after clicking the "Try face ID" button, the icon lights up and starts scanning for my face again. See the recording below 


https://github.com/flutter/flutter/assets/88313112/fafd83d9-074d-491b-9c0b-9462a35364ee
