### ISSUE TITLE
Issue from website page Flutter Setup for macOS

### ISSUE THREAD

**Issue by adsouza** [flutter/flutter#14624]
From URL: https://flutter.io/setup_macos.md

In the "Set up the Android emulator" section step 2 says "Launch Android Studio>Tools>Android>AVD Manager" but there's no "Android" item in the Tools menu.
![screen shot 2018-02-10 at 10 29 44 am](https://user-images.githubusercontent.com/275832/36063633-5b8de19a-0e4d-11e8-962f-3e227c8eafdb.png)

**Comment by Sfshaza** [comment]
I searched for this problem and found it's a common android studio problem on the Mac:
https://stackoverflow.com/questions/40407124/android-studio-2-2-2-tools-android-menu-is-missing-in-mac-os-x

**Comment by mit-mit** [comment]
This is likely unrelated to the OS, but due to the fact that this menu is conditional and only shows up when an Android project is open. Try creating a new Android Project, and see if that makes it appear.

**Comment by mit-mit** [comment]
(https://github.com/flutter/flutter/issues/13379 tracks making this step easier)

**Comment by mit-mit** [comment]
@adsouza did my suggestion resolve this for you?

**Comment by adsouza** [comment]
Oh, sorry, I stopped trying to use Flutter a while ago already.
