### ISSUE TITLE
`macos_platform_tests` package build times out when built for all packages

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#146254]
macos_platform_tests is timing out when built for all packages.

Examples:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20macos_platform_tests%20master%20-%20packages/1662
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20macos_platform_tests%20master%20-%20packages/1659
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20macos_platform_tests%20master%20-%20packages/1657

Can [`macos_platform_tests`](https://github.com/flutter/packages/blob/0f14d4f2105f5618a4fb61eb249f19d31ad611c1/.ci/targets/macos_platform_tests.yaml) builder be broken apart?  The native tests alone are taking ~40 minutes.

**Comment by jmagman** [comment]
> The native tests alone are taking ~40 minutes.

Why are these tests taking so long?  There aren't that many macOS packages.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8752390746274227441/+/u/Run_package_tests/native_test/stdout

**Comment by jmagman** [comment]
The last test suite starts at 24 seconds:
```
 || Running for packages/in_app_purchase/in_app_purchase_storekit [@0:24]
```
and runs until 36 seconds, then gets stuck for 40 minutes:
![Screenshot 2024-04-03 at 8 23 44 PM](https://github.com/flutter/flutter/assets/682784/5881cac6-81b9-40bb-8326-8f2348074e26)

```
 Test case '-[PaymentQueueTest testStartObservingPaymentQueueShouldNotProcessTransactionsWhenCacheIsEmpty]' passed on 'My Mac - example (2
 ** BUILD INTERRUPTED **
```

Is this some form of https://github.com/flutter/flutter/issues/119750 again?

**Comment by stuartmorgan** [comment]
> > The native tests alone are taking ~40 minutes.
> 
> Why are these tests taking so long? There aren't that many macOS packages. It took 3:29.43 to run on my machine.

On the most recent all-packages run it took about a minute and a half for both `master` and `stable` runs, so maybe it's a flaky test hang rather than slowness.

**Comment by jmagman** [comment]
> On the most recent all-packages

Those are running fast on x64, right? So maybe confirms this is another hang issue on arm?

**Comment by stuartmorgan** [comment]
Sorry, by "all-packages run" I meant a run that had a repo-level change, such that every package's test ran. In particular, I looked at these:
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20macos_platform_tests%20master%20-%20packages/1700/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20macos_platform_tests%20stable%20-%20packages/1722/overview

**Comment by jmagman** [comment]
Hmm, looking again, they do always seem to get stuck on in_app_purchase tests.  Which made me think this could have been caused by https://github.com/flutter/packages/pull/6209 merged on March 5, but the first flake I see was on https://github.com/flutter/flutter/commit/2bb7d14d9202ec312d3efa42026be52d49b05c36 from January 20

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20macos_platform_tests%20master%20-%20packages/1415

Perhaps it's from a change made in flutter/packages#6032 around the pigeon work.

@LouiseHsu are you able to reproduce this flake locally, if you run the tests a bunch of times?
