### ISSUE TITLE
Add support for a single AppBar child

### ISSUE THREAD

**Issue by j4k0bk** [flutter/flutter#14626]
Could be usefull to be able to provide the AppBar and SliverAppBar with a single child which expands to fill the entire AppBar, thus rendering leading, title, actions (etc) redundant.

Usefull when for example the AppBar should contain a search field (or the like), but one still need the other features of the AppBar such as pinned, floating, elevation, bottom etc.

The current AppBar forces us to obey Material guidelines very strictly, and makes all pages look the same.

**Comment by Hixie** [comment]
I think you're describing PersistentSliverHeader, in the case of SliverAppBar.
I'm not sure what's left of AppBar if you just replace it with what you describe. That might just be Material.

**Comment by j4k0bk** [comment]
@Hixie A few examples:

- `bottom` with pinned/floating independent of the `AppBar` content (or child as i suggest) itself.
- Top padding, so content isn't placed below the status bar.
- elevation based on child scroll when using `NestedScrollView`

**Comment by Hixie** [comment]
The PersistentSliverHeader should be able to do the first and third of those very easily.
For the second, when you're not doing any scrolling, SafeArea should be able to do what you want.

**Comment by j4k0bk** [comment]
@Hixie Thanks for the response. I was not even aware `SafeArea` existed untill now. This request was definitely a convenience kind of thing. Closing it again.
