### ISSUE TITLE
[flutter release] new beta branch missing corresponding recipe branch

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#146222]
happened on the new beta branch flutter-3.22-candidate.0.

the recipe branch had to be manually created to unblock the release.

**Comment by XilaiZhang** [comment]
Kevin kindly helped with outputs from https://chat.google.com/room/AAAAc_4rqiI/L8lsxuhoYLc

The code logic related to recipe branch creation is [this one](https://source.corp.google.com/piper///depot/google3/mobile/flutter/tools/common/lib/flutter_client.dart;l=142;rcl=621625565)

**Comment by Jasguerrero** [comment]
Looking at the file this is intended behavior and retries are out the pictures, quoting the code comment ``` // 90%+ of the time the release infra isn't necessary, so don't block the roll on failures here.``` tl;dr we do not enforce the creation of recipes branches for the rolls, for this particular case the recipe branch creation returned an invalid token error, I will add better logging to inform the roller when this issue arises
