### ISSUE TITLE
CustomScrollView without scrolling, but with a ScrollController, does not fire ScrollNotification

### ISSUE THREAD

**Issue by j4k0bk** [flutter/flutter#14639]
When the slivers of a `CustomScrollView` does not exceed the available height (ie. no scrolling) AND there is a `ScrollController` attached to the `CustomScrollView`, then `ScrollNotification` is not fired.
This is a problem when for example `OverflowScrollNotification` is expected.

**Comment by Hixie** [comment]
This is working as intended; see https://docs.flutter.io/flutter/widgets/ScrollView/physics.html for instructions on overriding this default behaviour.
