### ISSUE TITLE
[camerax] orientation issue in landscape mode with camera_android_camerax while video recording

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#146395]
### Steps to reproduce

To verify if I can replace the `camera_android` with `camera_android_camerax` I took the federated plugin [example project](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) from the current head of the main branch of `packages` repo and added `camera_android_camerax` dependency as stated in the camerax plugin readme:

```
  camera_android_camerax:
    path: ../../camera_android_camerax
```

Then performed the following steps

* Build and launched this example on Samsung S23 Android phone
* Rotated phone to landscape (automatic screen rotation is enabled in the system settings)
* Tap any camera at the bottom. Then tap the "record video" icon button.
* Observe video flips to 90 degrees and then recorded file is also rotated at 90 degrees.
* Additionally the video has extension like .temp instead of .mp4

I don't observe the above behaviour after removing the `camera_android_camerax` dependency.

On a side note I see a lot of differences between examples located inside `camera`, `camera_android` and `camera_android_camerax`. Not sure why the first one is different, but shouldn't the latter two plugins have the same example code?

### Expected results

I'd expect `camera_android_camerax` to behave the same as `camera_android`

### Actual results

See above.

Also I see the following in the LogCat

```
22:51:18.322  E  Activity io.flutter.embedding.android.FlutterActivity has leaked IntentReceiver io.flutter.plugins.camerax.DeviceOrientationManager$1@4c198eb that was originally registered here. Are you missing a call to unregisterReceiver()?
                 android.app.IntentReceiverLeaked: Activity io.flutter.embedding.android.FlutterActivity has leaked IntentReceiver io.flutter.plugins.camerax.DeviceOrientationManager$1@4c198eb that was originally registered here. Are you missing a call to unregisterReceiver()?
                 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1980)
                 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1690)
                 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1901)
                 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
                 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
                 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                 	at io.flutter.plugins.camerax.DeviceOrientationManager.start(DeviceOrientationManager.java:74)
                 	at io.flutter.plugins.camerax.DeviceOrientationManagerHostApiImpl.startListeningForDeviceOrientationChange(DeviceOrientationManagerHostApiImpl.java:65)
                 	at io.flutter.plugins.camerax.GeneratedCameraXLibrary$DeviceOrientationManagerHostApi$-CC.lambda$setup$0(GeneratedCameraXLibrary.java:1512)
                 	at io.flutter.plugins.camerax.GeneratedCameraXLibrary$DeviceOrientationManagerHostApi$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)
                 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
                 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:230)
                 	at android.os.Looper.loop(Looper.java:319)
                 	at android.app.ActivityThread.main(ActivityThread.java:8919)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Code sample

See above

### Screenshots or Video

<details open>
<summary>Screenshot</summary>

![image](https://github.com/flutter/flutter/assets/440954/c22aedf1-eb25-4bd3-897b-56acbf4cfe47)

</details>

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 13.6.6 22G630 darwin-arm64, locale en-CA)
    • Flutter version 3.19.5 on channel stable at ***/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (10 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at ***/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /Applications/Android Studio Giraffe Canary.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.9-11255266)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode_15.2.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.5.1
    • Dart plugin version 241.15845

[✓] Connected device (3 available)
    • SM S916W (mobile) • R5CW51YL0NV • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.6.6 22G630 darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. I also can reproduce this issue using [camera_android_camerax sample code](https://github.com/flutter/packages/blob/caf48bc4cd97eec2a79200d80d8772e44944168a/packages/camera/camera_android_camerax/example/lib/main.dart) with my device `Realme 6, Android 11`.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (8 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.22.0-5.0.pre.55, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.0-5.0.pre.55 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ddf79b755d (5 hours ago), 2024-04-07 18:34:24 -0400
    • Engine revision c10e950c66
    • Dart version 3.5.0 (build 3.5.0-18.0.dev)
    • DevTools version 2.34.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D          • android-arm64  • Android 11 (API 30)
    • iPad (mobile)    • 00008103-000A1464346A201E • ios            • iOS 17.2 21C62
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by ekuleshov** [comment]
By the way, this statement in the [camerax plugin's readme](https://pub.dev/packages/camera_android_camerax) makes it look like the plugin is stable and could be taken as given. I made that mistake and then discovered that there several P1 and P2 issues. Perhaps the paragraph below should mention something about potential issues in the plugin at least until it completely replaces the currently endorsed Android implementation.

> Note: This implementation will become the default implementation of camera on Android by May 2024, so we strongly encourage you to opt into it by using [the instructions](https://pub.dev/packages/camera_android_camerax#usage) below. If any of [the limitations](https://pub.dev/packages/camera_android_camerax#limitations) prevent you from using camera_android_camerax or if you run into any problems, please report these issues under [flutter/flutter](https://github.com/flutter/flutter/issues/new/choose) with [camerax] in the title.

**Comment by mariamhas** [comment]
Thanks @ekuleshov for reporting this issue we will look into it. Regarding the readme and default status, we believe cameraX fixes many of the issues with the current camera implementation. We will be prioritizing the cameraX plugin version going forward and fixing any issues with it instead of the current camera Android implementation, so we would like folks to start using cameraX and filing issues to make it the best plugin possible :)


>I made that mistake and then discovered that there several P1 and P2 issues. 

I don't believe there are any open P1s for cameraX, but as for P2 those aren't critical for cameraX to be feature complete but is the default for any new bugs or ones we believe are important but not blocking/top priority. (see prioritization definitions here: https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities)

**Comment by camsim99** [comment]
This is actually the same as https://github.com/flutter/flutter/issues/137366, so I thought this issue was fixed. @johnmccutchan by chance was there an attempt to reland https://github.com/flutter/engine/pull/50158 or something similar that may be impacting `Texture`s used in Flutter?

**Comment by ekuleshov** [comment]
Not sure why that other issue was deprioritized. The above reproducible example is a showstopper issue, which currently makes camerax plugin not suitable in prod apps.

Additionally the difference in the file names between legacy Android and camerax makes it a not a drop-in one.

**Comment by camsim99** [comment]
Going to take a look at this for a few days to see if I can at least identify the cause here before camera_android_camerax becomes the default plugin implementation on Android.

My first thought was whether or not this is related to https://github.com/flutter/flutter/issues/144414. I can see that the preview flips when the `VideoCapture` use case is bound to the lifecycle of the `Activity`, although a quick test seems to prove this wrong.

I tried manually correcting the preview rotation by setting the target rotation and I see that I am able to change it (but not correct it to be facing up as we'd expect), so I wonder if this is related to https://github.com/flutter/flutter/issues/144414 still and we need to make another `ProcessCameraProvider` call to correct the rotation or if we need to do some sort of matrix transformation to correct the preview.

**Comment by camsim99** [comment]
I have confirmed that when only preview and video recording use cases (and optionally, the image capture use cases as well) are bound to the lifecycle **initially**, the preview does not become incorrectly rotated, so this is directly related to https://github.com/flutter/flutter/issues/144414 and the limitations noted in the [CameraX docs](https://developer.android.com/media/camera/camerax/architecture#combine-use-cases). Note that it does become incorrect when image analysis instead of image capture (or both, as this issue relates to) is bound to the lifecycle, likely due to the limitations of the device I'm testing on (Pixel 3A) based on that documentation.

I'll need to see if I can fix this issue by binding use cases as needed or unbinding use cases in another way when video captures starts and then determine how to convey the limitations of CameraX to users, since we cannot work around that.

**Comment by camsim99** [comment]
Confirmed that unbinding the restricted use case as noted in https://developer.android.com/media/camera/camerax/architecture#combine-use-cases fixes this issue. Planning to add logic to unbind use cases based on the CameraX limitations + a warning + notes in the README to fix this issue.
