### ISSUE TITLE
Trying to build for Android on a Mac fails without Xcode

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1463]
You shouldn't have to download Xcode and get set up for iOS support if you're only building for Android.

**Comment by eseidelGoogle** [comment]
Maybe?  Most developmenty things on Mac require XCode.  It's just how they partition the space of packages for the system.  'git' for example requires XCode (or did last time I checked).  Unclear how may (if any) of these typical development tools the Android SDK requires on Mac.

**Comment by sethladd** [comment]
You can install git with the many gigs of Xcode. We shouldn't force our developers to install xcode unless they are doing ios dev.

**Comment by eseidelGoogle** [comment]
Given that the primary value add of our project is about building for both, I don't think we should target this for the Hackathon.

**Comment by eseidelGoogle** [comment]
I think it would be good for us to have a nice error when XCode is not installed, and that seems relevant for the Hackathon.

**Comment by collinjackson** [comment]
It may be the same amount of work to show an error and just fix the bug, I think we just need to skip building for iOS if Xcode is missing instead erroring out and aborting the Android build.

**Comment by sethladd** [comment]
Let's not force a developer to opt-in to iOS (xcode) for the hackathon, or any time :)

**Comment by devoncarew** [comment]
This is fixed. You can develop for iOS now w/o the android SDK installed, and for android w/o xcode installed.

**Comment by sethladd** [comment]
Nice!
