### ISSUE TITLE
Mark ListItem as deprecated in documentation

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#14635]
I just spent a significant amount of time trying to figure out why `new ListItem(...` didn't work in my code; I was convinced it existed because some out-of-date documentation (top results from Google Search 😆) still points to it (https://www.dartdocs.org/documentation/flutter/0.0.8/material/ListItem-class.html - I didn't realize it was version 0.0.8), and Material Design references both List Item and List Tile (https://material.io/guidelines/components/lists.html#lists-specs).

Finally after searching for `ListItem` in the Github Issues I came across https://github.com/flutter/flutter/pull/8769 and it all makes sense now 🤦‍♀️  and realized I should be using ListTile!

Just wanted to illustrate the confusion/pain point - not sure how to alleviate it for future users. Maybe we could have a page in the docs that marks ListItem as deprecated, and redirects ListItem to ListTile?

**Comment by Hixie** [comment]
Yikes, that's loooooong obsolete. I'll see what we can do to take it down.

**Comment by HansMuller** [comment]
The first Google search result for Flutter ListItem now just points to flutter.io. Not super helpful but harmless.

I'm going to close this bug
