### ISSUE TITLE
Reimage mac-29

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#146349]
This is a request to re-image DeviceLab mac-29.
@kentnguyen99 Could you help with this and give it a high priority? Thanks!

/cc @godofredoc @yusuf-goog

**Comment by kentnguyen99** [comment]
Ok. Will do.

**Comment by kentnguyen99** [comment]
Re-image mac-29 has been completed. Machine is online and ready for service.

**Comment by keyonghan** [comment]
> Re-image mac-29 has been completed. Machine is online and ready for service.

The bot is quarantined due to:
```
Device doctor tool error: b'security: SecKeychainUnlock login.keychain: The specified keychain could not be found.\nls: /Users/swarming/Library/MobileDevice/Provisioning Profiles: No such file or directory\n'
```

**Comment by keyonghan** [comment]
Could you try: go/flutter-salt#provisioning-profile-not-found-on-mac-ios-machines

**Comment by kentnguyen99** [comment]
@keyonghan, Certificate has been added to system. Can you give another try?

**Comment by sealesj** [comment]
@kentnguyen99 is this issue still unresolved?

**Comment by keyonghan** [comment]
We need to re-install the [provisioning profile](http://g3doc/company/teams/flutter/infrastructure/devicelab/ios_device#add-device-to-app-developer-provisiong-file).

Note: you do not need to add the device to the provisioning file, but just running salt to re-install the file to the machine.

**Comment by keyonghan** [comment]
@kentnguyen99 have you installed xcode on the bot? Hopefully you have run through [all steps](https://g3doc.corp.google.com/company/teams/flutter/infrastructure/salt_stack.md?cl=head#provisioning-profile-not-found-on-mac-ios-machines) ?

**Comment by kentnguyen99** [comment]
Xcode App could not be installed due MaOS 14.xx or greater.  Can I upgrade MacOS 14.4.1 on mac-29?

**Comment by keyonghan** [comment]
No. Let's hold on the OS upgrade. All bots across our pools are with mac 13.

Could you give it a try installing a different [xcode version via chromium package](http://go/flutter-salt#install-xcode-and-enable-the-provisioning-profile-to-be-removed)?
```
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$HOME/depot_tools/cipd auth-login
PATH=$PATH:$HOME/depot_tools
sudo mkdir  -p /opt/flutter/xcode/15a24/
sudo $HOME/depot_tools/mac_toolchain install -kind ios -xcode-version 15a24 -output-dir /opt/flutter/xcode/15a24/XCode.app -cipd-package-prefix infra_internal/ios/xcode
sudo chown -R swarming /opt/flutter/xcode/15a24/
```

**Comment by keyonghan** [comment]
Could you try running the salt, to install code_signing specifically and paste the log here? I would expect the salt to copy the profile and install the certs.

**Comment by kentnguyen99** [comment]
Attached log of installing code_signing on mac-29.

flutter@flutter-devicelab-mac-29 Downloads % sudo salt-call state.apply flutter.code_signing                       
[WARNING ] /opt/salt/lib/python3.7/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

local:
----------
          ID: /opt/flutter/code_signing
    Function: file.recurse
      Result: True
     Comment: The directory /opt/flutter/code_signing is in the correct state
     Started: 14:04:21.460505
    Duration: 2479.907 ms
     Changes:   
----------
          ID: restore_keychain
    Function: cmd.run
        Name: cd /opt/flutter/code_signing
LOGIN_PASSWORD=dartydartdart ./nuke.sh
security create-keychain -p dartydartdart login.keychain
security set-keychain-settings -l -u -t 1800 login.keychain
LOGIN_PASSWORD=dartydartdart ./restore.sh

      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 14:04:23.941571
    Duration: 0.004 ms
     Changes:   
----------
          ID: restore_swarming_provisiong_profile
    Function: cmd.run
        Name: cd /opt/flutter/code_signing
./provisioning_profile.sh

      Result: True
     Comment: unless condition is true
     Started: 14:04:23.941644
    Duration: 1605.68 ms
     Changes:   
----------
          ID: /usr/local/bin/unlock_login_keychain.sh
    Function: file.managed
      Result: True
     Comment: File /usr/local/bin/unlock_login_keychain.sh is in the correct state
     Started: 14:04:25.547574
    Duration: 139.753 ms
     Changes:   

Summary for local
------------
Succeeded: 4
Failed:    0
------------
Total states run:     4
Total run time:   4.225 s

**Comment by keyonghan** [comment]
Could you try deleting `/opt/flutter/code_signing` to force a rerun?

**Comment by kentnguyen99** [comment]
flutter@flutter-devicelab-mac-29 flutter % sudo salt-call state.apply flutter.code_signing 
[WARNING ] /opt/salt/lib/python3.7/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

local:
----------
          ID: /opt/flutter/code_signing
    Function: file.recurse
      Result: True
     Comment: Recursively updated /opt/flutter/code_signing
     Started: 14:24:21.556109
    Duration: 2522.585 ms
     Changes:   
              ----------
              /opt/flutter/code_signing/development.mobileprovision:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
                  user:
                      swarming
              /opt/flutter/code_signing/development.p12:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
                  user:
                      swarming
              /opt/flutter/code_signing/files:
                  ----------
                  /opt/flutter/code_signing/files:
                      New Dir
              /opt/flutter/code_signing/files/unlock_login_keychain.sh:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
                  user:
                      swarming
              /opt/flutter/code_signing/init.sls:
                  ----------
                  diff:
                      New file
                  mode:
                      0644
                  user:
                      swarming
              /opt/flutter/code_signing/nuke.sh:
                  ----------
                  diff:
                      New file
                  mode:
                      0755
                  user:
                      swarming
              /opt/flutter/code_signing/provisioning_profile.sh:
                  ----------
                  diff:
                      New file
                  mode:
                      0755
                  user:
                      swarming
              /opt/flutter/code_signing/restore.sh:
                  ----------
                  diff:
                      New file
                  mode:
                      0755
                  user:
                      swarming
              /opt/flutter/code_signing/verify.sh:
                  ----------
                  diff:
                      New file
                  mode:
                      0755
                  user:
                      swarming
              /opt/flutter/code_signing/verify_mobileprovision.sh:
                  ----------
                  diff:
                      New file
                  mode:
                      0755
                  user:
                      swarming
----------
          ID: restore_keychain
    Function: cmd.run
        Name: cd /opt/flutter/code_signing
LOGIN_PASSWORD=dartydartdart ./nuke.sh
security create-keychain -p dartydartdart login.keychain
security set-keychain-settings -l -u -t 1800 login.keychain
LOGIN_PASSWORD=dartydartdart ./restore.sh

      Result: True
     Comment: Command "cd /opt/flutter/code_signing
              LOGIN_PASSWORD=dartydartdart ./nuke.sh
              security create-keychain -p dartydartdart login.keychain
              security set-keychain-settings -l -u -t 1800 login.keychain
              LOGIN_PASSWORD=dartydartdart ./restore.sh
              " run
     Started: 14:24:24.079710
    Duration: 538.427 ms
     Changes:   
              ----------
              pid:
                  5753
              retcode:
                  0
              stderr:
              stdout:
                  1 identity imported.
----------
          ID: restore_swarming_provisiong_profile
    Function: cmd.run
        Name: cd /opt/flutter/code_signing
./provisioning_profile.sh

      Result: True
     Comment: unless condition is true
     Started: 14:24:24.618381
    Duration: 1597.227 ms
     Changes:   
----------
          ID: /usr/local/bin/unlock_login_keychain.sh
    Function: file.managed
      Result: True
     Comment: File /usr/local/bin/unlock_login_keychain.sh is in the correct state
     Started: 14:24:26.215870
    Duration: 140.02 ms
     Changes:   

Summary for local
------------
Succeeded: 4 (changed=2)
Failed:    0
------------
Total states run:     4
Total run time:   4.798 s

**Comment by keyonghan** [comment]
Okay. It's back. Thanks @kentnguyen99 for your help.
Closing here.
