### ISSUE TITLE
Flutter doesn't recognize iOS device emulator and cocoapods

### ISSUE THREAD

**Issue by afijal** [flutter/flutter#14630]
## Steps to Reproduce
I use SIerra and that guide https://flutter.io/setup-macos/#ios-setup.
I'm trying to setup Flutter for the development and I've tried to launch a helloworld app first. So I've run flutter create helloworld, and then tried to run the app. Seems to work just fine on android emulator, but flutter cannot see running iOS device emulator.
Yeah, doctor says to install cocoapods, but I've done it already:

MacBook-Pro-Artur:helloworld koala888$ brew install cocoapods
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
urdfdom

Warning: cocoapods 1.4.0 is already installed

I've also run pod setup multiple times, but still, flutter doctor indicates that cocoapods are not installed, and my guess is that this can be a reason why flutter devices doesn't find my iphone X emulator.

Any ideas?

## Logs
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
No connected devices.

To run on a simulator, launch it first: open -a Simulator.app

If you expected your device to be detected, please run "flutter doctor" to diagnose
potential issues, or visit https://flutter.io/setup/ for troubleshooting tips.

## Flutter Doctor

 Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale pl, channel dev)
    • Flutter version 0.1.0 at /Users/koala888/flutter
    • Framework revision ab4506cad2 (2 days ago), 2018-02-09 12:21:43 -0800
    • Engine revision 337764e4ed
    • Tools Dart version 2.0.0-dev.22.0
    • Engine Dart version 2.0.0-edge.32396138ff733cbe8d9ac32178e6cffccdf80644

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/koala888/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by jsiedentop** [comment]
I've got the same Problem here. After a fresh install of macOS High Sierra I've setup the flutter environment. Flutter doctor always suggest me to install cocoapods, but it was already installed.
The ```pos setup``` command prints the following errors: 
```
/usr/local/bin/pod: /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/pod: line 2: /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod: Undefined error: 0
```
I found the same issue here: https://github.com/CocoaPods/CocoaPods/issues/6778
So the solution for my problem was to run ```sudo gem install cocoapods``` and ``` pod setup ```. @afijal, maybe it is also useful for you.

**Comment by gmalagutti** [comment]
I have the exact same problem and unfortunately sudo gem install cocoapods and pod setup did not help. Every time I run flutter doctor I get 
✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

**Comment by afijal** [comment]
Thank you @jsiedentop but I've resolved the issue simply by changing permissions for flutter directory and its contents so I don't have to run it with sudo

**Comment by gmalagutti** [comment]
Can you please help me (and possibly other users) and tell me how you reassigned the rights?

**Comment by afijal** [comment]
using chmod

**Comment by gmalagutti** [comment]
Is it asking too much what code was required? Full read/write access? read/execute? on the entire folder + subfolders?

**Comment by afijal** [comment]
i don't have an access atm to this machine but probably i was lazy and just chmod 777 -r everything

**Comment by gmalagutti** [comment]
OK, for everybody else this line solved the issue on my Mac, executed from the installation folder of flutter
sudo chmod -R 777 *

**Comment by cuichanghao** [comment]
Mac high sierra cannot install to /usr/bin you need below command to install /usr/local/bin

```
sudo gem install cocoapods -n /usr/local/bin
```

**Comment by rosanalee** [comment]
https://github.com/flutter/flutter/issues/41291#issuecomment-535117317

> No the OP, but having the same issue.
> Installing CoacoaPods 1.7.5 did the trick.
> 
> As per solution in #41253:
> `sudo gem uninstall cocoapods`
> `sudo gem install cocoapods -v 1.7.5`
> `pod setup`

**Comment by rohan20** [comment]
This occurs due to an issue with how xcode 11 is shipped on different MacOS versions. Read more here: https://stackoverflow.com/a/58226876/5066615

Worked for me.

**Comment by yuchar** [comment]
> I've got the same Problem here. After a fresh install of macOS High Sierra I've setup the flutter environment. Flutter doctor always suggest me to install cocoapods, but it was already installed.
> The `pos setup` command prints the following errors:
> 
> ```
> /usr/local/bin/pod: /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
> /usr/local/bin/pod: line 2: /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod: Undefined error: 0
> ```
> 
> I found the same issue here: [CocoaPods/CocoaPods#6778](https://github.com/CocoaPods/CocoaPods/issues/6778)
> So the solution for my problem was to run `sudo gem install cocoapods` and `pod setup`. @afijal, maybe it is also useful for you.

Thanks a lot. Solve my issues.
