### ISSUE TITLE
[google_map_flutter : 2.6.0] Disable marker movement animation in ios

### ISSUE THREAD

**Issue by behzad-tg** [flutter/flutter#146392]
in android we dont have any animation when we change the location of a marker but in ios we have and also we dont have any controll on it. i found some similar github issues([#129826](https://github.com/flutter/flutter/issues/129826))  that sended last year but still No solution provided.

**Comment by darshankawar** [comment]
@behzad-tg 
The linked / original issue is open and likely reason for it is as mentioned https://github.com/flutter/flutter/issues/129826#issuecomment-1644423838
So I suggest you to follow-up in it for further updates. Closing this as a duplicate.
