### ISSUE TITLE
Flutter Web  html.window.location issue

### ISSUE THREAD

**Issue by iKK001** [flutter/flutter#146340]
### Steps to reproduce

I am using Flutter Stripe for WEB and had it successfully run on Flutter 3.x - but now updating to Flutter 3.19.5 stable my application does not longer work.

I use the Flutter packages
`flutter_stripe: ^10.1.1`
`flutter_stripe_web: ^5.1.0`

My steps are:

1. I call Stripe Checkout Session URL by `html.window.location.href = checkoutSessionUrl`
2. the Stripe Purchase Popup opens 
3. I do my payment
4. then the successURL is called (or cancelURL depending on what the user does)
(the exact successURL = `'${html.window.location.origin}/#/payment_success_page'`)
6. the `onGenerateRoute` in my Flutter main is called correctly (with the correct route `/payment_success_page`)
7. from the given successURL, I extract the route and call the actual `PaymentSuccessPage` Widget

--> everything o.k. so far!

But now the problem:

8. when I enter the success_page route, the app freezes !
i.e. no success_page rendering at all. Tha App stalls !!!!!!!

It looks to me as if the Fluter WEB takes FOREVER to render. It freezes instead of rendering the successURL-`html.window.location` !

The big question is why does the very same code no longer work after the flutter-update ?????

 

### Expected results

The expected result should be a normal render of the `success_page` route as it did before the Flutter update.

### Actual results

The false result is a Screen-freeeze of my Web application !

### Code sample

Here is my `success_page` route Page

Important information:

The callback `if (snapshot.data == "success") {...}` is called.

BUT THE `return Container(..)` is never rendered !!!!!!!!!!!!!!!!!!!!!!!!!!!!

The scren freezes.

Before Flutter version 3.19.5, the identical code would render the Container perfectly fine !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:teddy_flutter/api_calls/payments_api.dart';
import 'package:teddy_flutter/main.dart';
import 'package:universal_html/html.dart' as html;

class PaymentSuccessPage extends StatefulWidget {
  final String checkoutSessionIdAndMode;
  const PaymentSuccessPage({
    super.key,
    required this.checkoutSessionIdAndMode,
  });

  @override
  State<PaymentSuccessPage> createState() => _PaymentSuccessPage();
}

class _PaymentSuccessPage extends State<PaymentSuccessPage> {
  String checkoutSessionId = "";
  String mode = "";
  @override
  void initState() {
    checkoutSessionId = widget.checkoutSessionIdAndMode.split("&mode=")[0];
    mode = widget.checkoutSessionIdAndMode.split("&mode=")[1];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    if (kIsWeb) {
      html.window.localStorage
          .update('successFlag', (value) => 'false', ifAbsent: () => 'false');
      html.window.localStorage.remove('successFlag');
      html.window.localStorage.remove('cancelFlag');
      html.window.location.hash = '';
    }
    return MyScaffold(
      context: context,
      route: '/payment_success_page',
      body: FutureBuilder<String>(
        future: PaymentsAPI.finishPayment(checkoutSessionId, mode),
        builder: (context, AsyncSnapshot<String> snapshot) {
          if (snapshot.hasData) {
            if (snapshot.data == "success") {
              return Container(
                alignment: Alignment.topLeft,
                padding: const EdgeInsets.all(20),
                child: const SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Image(
                        image: AssetImage('assets/images/logo.png'),
                        height: 200,
                        width: 200,
                      ),
                      Text("Payment Success Page"),
                    ],
                  ),
                ),
              );
            } else {
              return Container(
                color: Colors.red,
                alignment: Alignment.topLeft,
                padding: const EdgeInsets.all(20),
                child: const SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Image(
                        image: AssetImage('assets/images/logo.png'),
                        height: 200,
                        width: 200,
                      ),
                      Text("Payment Failed !"),
                    ],
                  ),
                ),
              );
            }
          } else {
            return const Center(
              child: CircularProgressIndicator(),
            );
          }
        },
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
no screenshots available
</details>

### Logs

<details open><summary>Logs</summary>

```console
no logs since scereen-freeze
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4 23E214 darwin-arm64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

I suspect that Futter WEB somehow stalls when a `html.window.location` assignment is made. But the question is WHY ????

**Comment by iKK001** [comment]
Never mind - it was all my mistake !!! I am sorry about any confusion it might have caused.

The reason why the html.window.location would not work was that I am using flutter_native_splash in my main.dart. And in case the payment-API has finished and the flutter App has returned to the successURL, I HAD FORGOTTON TO ADD FlutterNativeSplash.remove(); method. (i.e. it had perfectly worked - but the Splashscreen kept beeing shown and I assumed the app had freezed).

Again, I am sorry for any confusion. This ticket can be closed.

**Comment by darshankawar** [comment]
Closing based on above comment.
