### ISSUE TITLE
[image_picker] pickMedia() not picking either image/video in android 14

### ISSUE THREAD

**Issue by SannyRai** [flutter/flutter#146323]
### Steps to reproduce
image_picker: 1.0.7
use pickMedia to pick any image/video

### Expected results

should pick the selected media file

### Actual results

returning null

### Code sample

<details open><summary>Code sample</summary>

```dart
final resultFile = await ImagePicker().pickMedia();
// print(resultFile) => null
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @SannyRai, what device are you seeing this issue on? I tested on my Pixel 7 running android 14 and it works as expected. See the recording below. 

Do you get the same issue with the plugin example app? Do you get any errors or is null all you see? 

Please also provide the output of `flutter doctor -v`

https://github.com/flutter/flutter/assets/88313112/636046e7-544f-428f-b911-0416c60efc06


Thank you

**Comment by SannyRai** [comment]
Hi @danagbemava-nc. It appeared to be mistake in my side. I had launchMode to be 'singleInstance'. Before pickMedia() was implemented, I had this thing in my manifest file. So didn't see in the readme. However pickMedia did work in some devices despite having same launchMode configuration and not working in some, I thought it could be problem in android version 14 since I had complain in few devices like pixel 8 and redmi 12  but now it is confirmed there is no such problem.
Thanks!
