### ISSUE TITLE
Flutter Web does not render after calling html.window.location.href

### ISSUE THREAD

**Issue by iKK001** [flutter/flutter#146351]
### Steps to reproduce

Using Flutter v3.19.5,

In my Flutter WEB App I have to navigate to a `html.window.location.href` (due to some payment-API). And when I try to return to my actual Flutter App and render the successURL screen, it just does not work.

The API call works fine. And its `successUrl` is called.

I end up with a localhost that looks like this:

`http://localhost:61344/#/principles_main`

And 

Inside my `onGenerateRoute` I can set my App path by observing the #-route of this successURL.

I then try to replace the `html.window.location.href` again to show a success-page as such:

```
html.window.location.hash = '/principles_main';
html.window.location.reload();
return const PrincipleMain();
```

After this, I end up with an local URL that looks like this:

`http://localhost:61344/#/principles_main`

But this does not do anything! The App freezes ! No error message at all.

And worst of all: the intended `PrincipleMain` widget is not shown !

In addition, I am using the `FlutterWebPluginWeb` as such:

```
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

class FlutterWebPluginWeb {
  static void resetRoute() {
    if (kIsWeb) {
      setUrlStrategy(null);
    }
  }
}
```

What can I do to make the Flutter WEB App come back to rendering normal pages after the successURL html.window.location.href navigation ?????????

### Expected results

I expect flutter to render a Widget after calling 

```
html.window.location.hash = '/principles_main';
html.window.location.reload();
return const PrincipleMain();
```

(preferably even without the `.reload()` !

### Actual results

App freeze since Flutter stable v3.19.5

### Code sample

<details open><summary>Code sample</summary>

```dart
see above
```

</details>

### Screenshots or Video

<details open>
no screenshots
</details>

### Logs

<details open><summary>Logs</summary>

```console
no logs (Flutter WEB App actually freeezes)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4 23E214 darwin-arm64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by iKK001** [comment]
An observation: the reload() only works if I set the html.window.location.hash = ''. And it only does it after about 15 seconds !!!!! (i.e. Flutter WEB is awfully slow when reloading a page). I am completely clueless why Flutter v3.19.5 does not allow reloads of other hash-locations ????

**Comment by huycozy** [comment]
Closing based on above comment.
