### ISSUE TITLE
Widgets are looking buggy on Web

### ISSUE THREAD

**Issue by geronimol** [flutter/flutter#146314]
This started to happen some weeks ago. It is hard to reproduce for `TextField`, but you can see it clearly in the video for the `CircularProgressIndicator`. Tried changing `useMaterial3` but didn't work.

### Steps to reproduce

1. Create a new Flutter Project
2. Run for web

### Expected results

Widgets like `CircularProgressIndicator` and `TextField`(Or `TextFormField`, not sure) looking normal.

### Actual results

Every x seconds the widgets look buggy, like they are growing or having zoom on them.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: false,
      ),
      home: const Scaffold(
        body: Column(
          children: [
            Center(child: CircularProgressIndicator()),
            Center(child: CircularProgressIndicator()),
            Center(child: CircularProgressIndicator()),
            Center(child: CircularProgressIndicator()),
            TextField(
              decoration: InputDecoration(
                border: OutlineInputBorder(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/56521222/d84c948f-04ab-41a5-8416-f891e9f94bff

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 13.6.4 22G513 darwin-x64, locale es-419)
    • Flutter version 3.19.5 on channel stable at /usr/local/Caskroom/flutter/3.19.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (8 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gero/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Volumes/Latest/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.6.4 22G513 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by geronimol** [comment]
Tried running  `brew upgrade flutter` and `dart pub cache clean`, but didn't fix.

**Comment by danagbemava-nc** [comment]
Hi @geronimol, do you see this in every project? Did you start seeing this after you upgraded flutter? If so, which version were you on? 

Do you see any errors in your browser console? 

Does this happen with the html renderer as well

**Comment by geronimol** [comment]
@danagbemava-nc Yes, I see this in every project, that is why I created a new one to reproduce. I started seeing this some weeks ago, also before upgrading. I wasn't paying much attention to this until I saw the `TextField` buggy(hard to reproduce).

I don't see any errors in the console.

It doesn't seem to be happening with the html renderer. Only with canvaskit.

**Comment by danagbemava-nc** [comment]
Hi @geronimol, how long does it take for you to see this issue? Do you see it immediately you launch the app or do you have to leave the app open for a few minutes? I am testing on my m1 Mac but I can't seem to reproduce this at the moment. Any more information you can provide will be helpful

**Comment by geronimol** [comment]
@danagbemava-nc Sometimes it takes a few seconds, and sometimes can take more than a minute to be clearly visible like in the video.

It seems like it's only happening in debug mode for Chrome browser. It isn't happening on MacOS or iPhone simulator. I will try to make a clean install as soon as I can.

**Comment by geronimol** [comment]
The issue persists after a clean install. So I don't know what is happening.

**Comment by danagbemava-nc** [comment]
Hi @geronimol, are you only seeing this in the chrome browser? 

Just curious, are you using a secondary monitor with your device and is it on the secondary monitor you see this?

**Comment by geronimol** [comment]
@danagbemava-nc Yes, that is happening only in the Chrome browser. 
Yes, I am using a secondary monitor and using the OCLP for my macbook. Do you think that is related?

I just tried running the app in the primary monitor without connecting the secondary, and seems to work fine.

**Comment by danagbemava-nc** [comment]
Hi @geronimol, now that you mention OCLP, we've had an issue with it before (although this was on macOS desktop). See https://github.com/flutter/flutter/issues/137859


> I started seeing this some weeks ago, also before upgrading.

Coming back to your comment in https://github.com/flutter/flutter/issues/146314#issuecomment-2039829531

Did you upgrade your version of macOS during this time? 


> Yes, I am using a secondary monitor

What monitor are you using? Can you check https://github.com/flutter/flutter/issues/113583 & https://github.com/flutter/flutter/issues/89605 to see if they are similar to your case?

**Comment by geronimol** [comment]
Thanks for your help @danagbemava-nc 

I think this problem is related to the OCLP patches, because I recently migrated to macOS Ventura. So I will close this issue, since it is not worth spending time on this.

> What monitor are you using? Can you check https://github.com/flutter/flutter/issues/113583 & https://github.com/flutter/flutter/issues/89605 to see if they are similar to your case?

I couldn't reproduce the first issue, but the second one is something that I have been experiencing for a while on my Samsung SyncMaster P2370(23"). I thought the problem was my monitor.

**Comment by geronimol** [comment]
Thanks for your help @danagbemava-nc

I think this problem is related to the OCLP patches, because I recently migrated to macOS Ventura. So I will close this issue, since it is not worth spending time on this.

What monitor are you using? Can you check https://github.com/flutter/flutter/issues/113583 & https://github.com/flutter/flutter/issues/89605 to see if they are similar to your case?

I couldn't reproduce the first issue, but the second one is something that I have been experiencing for a while on my Samsung SyncMaster P2370(23"). I thought the problem was my monitor.
