### ISSUE TITLE
Material consumes ScrollNotification

### ISSUE THREAD

**Issue by j4k0bk** [flutter/flutter#14631]
Having a `Material` in between a scrolling widget and a `NotificationListener<ScrollNotification>` blocks the `NotificationListener` from receiving the notification.

**Comment by Hixie** [comment]
We should let the notifications bubble through, or, at a minimum, if that's too much of a breaking change, mention this in the docs.

**Comment by pedromassangocode** [comment]
Hi @j4k0bk 
Are you still facing this issue?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
