### ISSUE TITLE
Crash when building flutter app in debug mode with macros

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#146451]
1. Check out https://github.com/jakemac53/macros_example/tree/flutter-app at commit https://github.com/jakemac53/macros_example/commit/7c0034cd7020df1bbf4308395f42bd62996a0e0d
2. Run `flutter run -d linux --enable-experiment=macros`
3. Observe the following crash:
```
Unhandled exception:
FileSystemException(uri=dart-macro+file:///Users/goderbauer/dev/macros_example/lib/main.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34)
#1      asFileUri (package:vm/kernel_front_end.dart:752)
#2      writeDepfile (package:vm/kernel_front_end.dart:892)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:680)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#5      main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
```

Running the app in release mode (`flutter run -d linux --enable-experiment=macros --release`) works totally fine, so this could be an issue with the kernel transformer that runs in debug mode?

**Comment by goderbauer** [comment]
cc @jakemac53 Is there a hot list for macro-related issues?

I am also not sure if this is an issue with the Dart packages mentioned in the stack trace above or with how the flutter tool holds them.

**Comment by jakemac53** [comment]
We have the [feature-macros](https://github.com/dart-lang/sdk/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-macros) label, in the SDK repo, and also a [github project](https://github.com/orgs/dart-lang/projects/70) which collects those and the ones from dart-lang/language.

I am not sure if a project can collect issues from multiple organizations, but if so we could add a similar label in flutter and make them be associated with that project also.

**Comment by jakemac53** [comment]
It looks like projects can track things across orgs, so I set up a workflow to track anything with the label `a: macros` - assuming this would be created here :). Let me know if you want to do a different label.

**Comment by goderbauer** [comment]
Added the label. Looks like it worked and the item go added to the project. Thank you!

**Comment by davidmorgan** [comment]
This was fixed, but I don't  have access to close it, @goderbauer could you please do so? :)

**Comment by goderbauer** [comment]
Thanks for the fix!
