### ISSUE TITLE
Cannot flutter run on iOS

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#14640]
This is on a brand new macOS machine I just configured.

## Steps to Reproduce

* `flutter create test01`
* `cd test01`
* `flutter run`

=>

```
Launching lib/main.dart on iPhone 8 Plus in debug mode...
Running Xcode clean...                                0.8s
Running Xcode build...                                3.7s
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
Error launching application on iPhone 8 Plus.
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-US, channel master)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.20.0)
[✓] Connected devices

• No issues found!
```

flutter devices:
```
1 connected device:

iPhone 8 Plus • D771CE75-5FC6-49EB-8E70-A7C0D77F25F3 • ios • iOS 11.2 (simulator)
```

**Comment by mit-mit** [comment]
Opening `ios` in xCode and running from there works as expected.

**Comment by mit-mit** [comment]
cc @cbracken @xster

**Comment by mravn-google** [comment]
Closed per #14641

**Comment by Jaydip2711** [comment]
I setup flutter in my mac but when I run hello_word project in my xcode at a time some error like "/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
" occures

**Comment by owenmech** [comment]
Can we address this issue? ^

**Comment by mravn-google** [comment]
@Jaydip2711 @owenmech Please open new issues instead of commenting on old ones. Please also include information to help reproduce/debug the issue, such as the output of `flutter doctor -v`. Thanks.
