### ISSUE TITLE
HapticFeedback.selectionClick nore

### ISSUE THREAD

**Issue by gaoxuefeng** [flutter/flutter#146433]
### Steps to reproduce

1. start recording;
2. scroll  CupertinoPicker -> THapticFeedback.selectionClick() not work;
3. stop recording;
4.  scroll  CupertinoPicker -> THapticFeedback.selectionClick() work

### Expected results

THapticFeedback.selectionClick() work when recording?

### Actual results

THapticFeedback.selectionClick() not work at all when recording;
when stop recording ,it work

### Code sample

<details open><summary>Code sample</summary>

                       CupertinoPicker(
                                selectionOverlay: const Center(),
                                scrollController: controller.leftController.value,
                                itemExtent: 45,
                                onSelectedItemChanged: (index) {
                                
                                },
                                children: List.generate(controller.rxLeftList.length, (index) {
                                  var item = controller.rxLeftList[index];
                                  var showText = item.name;
                                  return SizedBox(
                                    height: 45,
                                    width: double.infinity,
                                    child: Center(
                                      child: Text(
                                        showText ?? "",
                                        style: TabUtil.getTextStyle(),
                                      ),
                                    ),
                                  );
                                }),
                              ),

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.2 23C64 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

</details>

**Comment by huycozy** [comment]
Hi @gaoxuefeng 
Which platform are you checking on? Please also provide the device info as well (OS, model)

I checked this issue on iOS, using my device `iPhone 7, iOS 15.8` with [CupertinoPicker example](https://api.flutter.dev/flutter/cupertino/CupertinoPicker-class.html) but still can feel `vibrate` while recording the app. You can also try this sample code to see if the result is different or not.
