### ISSUE TITLE
Port this to Windows

### ISSUE THREAD

**Issue by dominictoutant** [flutter/flutter#146410]
https://github.com/flutter/flutter/blob/d6f6748f58f6a3a5f47ead2b9a7a5ebb24fe9b4c/dev/bots/analyze.dart#L1643

**Comment by danagbemava-nc** [comment]
Hi @dominictoutant , 

When filing an issue, it is important that you provide all the required information in the template. 

The link you provided doesn't seem to exist.

I'm going to close this issue because there isn't enough information here. 

Thank you
