### ISSUE TITLE
Flutter Web Styles Break on Facebook in-App Browser (Google Pixel 6, Android 14)

### ISSUE THREAD

**Issue by stefanhk31** [flutter/flutter#146473]
### Steps to reproduce

1. Create and deploy a Flutter web app
2. Open a link to the deployed app inside Facebook

### Expected results

Page displays normally, like it does in Android chrome:

<img width="400" src="https://github.com/flutter/flutter/assets/42074868/759dd31c-36d1-45c0-99b9-18c89f3dd254">

### Actual results

Page has theme overridden, text size increased, and text squeezed together:

<img width="400" src="https://github.com/flutter/flutter/assets/42074868/6dc218c7-dae5-4d1f-acac-9f9443c99355">

### Code sample

<details open><summary>Github Repo</summary>

Source code for this page can be found [here](https://github.com/stefanhk31/fb_in_app_bug_repro).

Not sure if you can run an in-app browser locally, but this is just a brand-new, out-of-the-box Flutter app with the issue. 

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4.1 23E224 darwin-arm64, locale
    en-US)
    • Flutter version 3.19.4 on channel stable at
      /Users/stefanhk/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (3 weeks ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/stefanhk/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/stefanhk/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.88.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4.1 23E224
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @stefanhk31 
>Open a link to the deployed app inside Facebook

Is there any simpler way to reproduce the issue or does the issue only occur in this scenario? If the issue only appears in Facebook app, could you check if it also occurs with non-Flutter web?

I tried embedding the Flutter web to a `webview_flutter` but couldn't see the issue.

**Comment by stefanhk31** [comment]
It only seems to occur in in-app browsers. There was a similar issue a few
months ago that others reported this in Instagram as well:
https://github.com/flutter/flutter/issues/145140

And I just verified that in-app browser looks fine on non Flutter web apps.

**Comment by huycozy** [comment]
I also tried opening a deployed Flutter web via Facebook app (paste web address in the post's comments and open it) but the text is rendered normally as I can see. I also open your web but the issue doesn't occur there.

<details>
<summary>Demo</summary>

| My site | Your site |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/4f3692c9-3762-4996-acc2-614d4d7dd11b"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/b9bed35a-647b-4107-bea7-3bee7ed084b8">

</details>

It seems you open Web from Messenger, right? I tried the same but the issue also doesn't appear. Maybe some specific Facebook app settings cause this, so you should check again to see if can find one.

**Comment by stefanhk31** [comment]
I opened your repro link and reproduced the issue.

![Screenshot_20240410-073144](https://github.com/flutter/flutter/assets/42074868/26401c00-8ebb-4c7d-8288-55286f42efe4)

What device/OS are you testing on?

**Comment by huycozy** [comment]
I’m using Pixel 7, Android 14
