### ISSUE TITLE
Request for a secure storage bucket for logs

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#146471]
As part of: https://github.com/flutter/flutter/issues/146104, I need to investigate why our new certificate is failing on release CI (technically it is being imported into the keychain but considered valid).

In order to investigate further, I would like to log information about the certificate authorities that are installed on the bots. To do this, I would like to have a cloud storage bucket that is:

1. writeable from dart-internal-flutter-engine bots
2. not readable by regular user accounts
3. readable via a temporary request

**Comment by godofredoc** [comment]
Closing as completed.
