### ISSUE TITLE
[Impeller] Statically assert that the pipeline stages have compatible interfaces.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#146452]
When creating a pipeline builder, there is no checking to see if the stages of the pipeline are actually compatible. The error will only become apparent if the pipeline is used in a command dispatch and validation layers are enabled.

This is easy to do at build time as the `PipelineBuilder` template parameters `VertexShader` and `FragmentShader`s have `kAllShaderStageInputs` and `kAllShaderStageOutputs` constexpr members can be statically asserted to be equal.

**Comment by gaaclarke** [comment]
@chinmaygarde I looked at this briefly and not all vertex shaders specify stage outputs.  Do you know what's up with that?

Here's the one I saw that don't have any:
- CheckerboardVertexShader
- ClipVertexShader

**Comment by chinmaygarde** [comment]
Its fine for vert stages to not have outputs to frag stages. But if they do, the frag stages must accept those inputs.

**Comment by chinmaygarde** [comment]
Ah, so you don't even have the kAllShaderStageOutputs as a constexpr variable in the header right? I suppose we can insert an empty one to make it easier to test.

**Comment by gaaclarke** [comment]
Okay, I think I have it hooked up.  What would you like to consider incompatible interfaces?  `input.bit_width != output.bit_width`?

**Comment by chinmaygarde** [comment]
Just `ShaderStageIOSlot::==`. Everything needs to be identical right?

**Comment by chinmaygarde** [comment]
We can put the static assert in the `name.vert.cc` file so its compile time checked just once.
