### ISSUE TITLE
Implementing native view on iOS make app crash with using the Impeller rendering backend 

### ISSUE THREAD

**Issue by nicolarigoni** [flutter/flutter#146496]
### Steps to reproduce

Implement the native platform view as documentation 

### Expected results

Running the app with Xcode all works fine when run the app from Android Studio the app crashes at start with error:

[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.

Already tried to disable when running and altro in the plist 

### Actual results

[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.

Commenting out the registrar in the AppDelegate the app not crash

### Code sample

<details open><summary>Code sample</summary>

```dart
class QuikLook extends StatelessWidget {
  final String filePath;

  const QuikLook({
    Key? key,
    required this.filePath,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // This is used in the platform side to register the view.
    const String viewType = 'QuickLook';
    // Pass parameters to the platform side.
    final Map<String, dynamic> creationParams = {'filePath': filePath};

    return UiKitView(
      viewType: viewType,
      layoutDirection: TextDirection.ltr,
      creationParams: creationParams,
      creationParamsCodec: const StandardMessageCodec(),
    );
  }
}
```

```swift
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        
        weak var registrar = self.registrar(forPlugin: "QuickLook")
        
        let factory = FLNativeViewFactory(messenger: registrar!.messenger())
        self.registrar(forPlugin: "QuickLook")!.register(
            factory,
            withId: "QuickLook")
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}

class FLNativeViewFactory: NSObject, FlutterPlatformViewFactory {
    private var messenger: FlutterBinaryMessenger
    
    init(messenger: FlutterBinaryMessenger) {
        self.messenger = messenger
        super.init()
    }
    
    func create(
        withFrame frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?
    ) -> FlutterPlatformView {
        return FLNativeView(
            frame: frame,
            viewIdentifier: viewId,
            arguments: args,
            binaryMessenger: messenger)
    }
    
    /// Implementing this method is only necessary when the `arguments` in `createWithFrame` is not `nil`.
    public func createArgsCodec() -> FlutterMessageCodec & NSObjectProtocol {
        return FlutterStandardMessageCodec.sharedInstance()
    }
}

class FLNativeView: NSObject, FlutterPlatformView {
    private var _view: UIView
    
    init(
        frame: CGRect,
        viewIdentifier viewId: Int64,
        arguments args: Any?,
        binaryMessenger messenger: FlutterBinaryMessenger?
    ) {
        _view = UIView()
        super.init()
        // iOS views can be created here
        
        createNativeView(view: _view, args: args)
    }
    
    func view() -> UIView {
        return _view
    }
    
    func createNativeView(view _view: UIView, args: Any?){
        let argumentsDictionary = args as? Dictionary<String, Any>
        let fileName = argumentsDictionary?["filePath"] as? String
        _view.backgroundColor = UIColor.blue
        let nativeLabel = UILabel()
        if let fileName = argumentsDictionary?["filePath"] as? String {
            nativeLabel.text = "Native text from iOS \(fileName)"
        } else {
            nativeLabel.text = "Native text from iOS"
        }
        nativeLabel.textColor = UIColor.white
        nativeLabel.textAlignment = .center
        nativeLabel.frame = CGRect(x: 0, y: 0, width: 180, height: 48.0)
        _view.addSubview(nativeLabel)
    }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
[✓] VS Code (version 1.86.2)
[✓] Connected device (9 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @nicolarigoni 
I tried above code sample with and without Impeller which gave me below error:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: QuickLook'
terminating with uncaught exception of type NSException
CoreSimulator 783.5 - Device: iPhone 13 Pro Max (640AC26E-2012-4D9F-965A-20029B7408C4) - Runtime: iOS 15.2 (19C51) - DeviceType: iPhone 13 Pro Max

```

The code sample looks for a filepath which I am not sure which one to use, so for demo I used a sample file and used it's path to make the code run but it lead me to above error. 
If this doesn't represent your case, please provide the filepath you are passing and the entire crash log for further verification of the issue.

**Comment by nicolarigoni** [comment]
Thanks for the test @darshankawar the file path is not a must component as you can see for now I use it only to check that args are correctly passed. 

I don't have logs it crashes with that error that I posted in the issue, because if running from Xcode all works fine the view is shown with also the path that for now is a string that not post to any file. 

the problem is running the app from Android Studio make it crashes on start

**Comment by darshankawar** [comment]
> running the app from Android Studio make it crashes on start

Thanks for the update. Can you try running in verbose mode (`flutter run -v`) and check if that log shows any error entries that'll be helpful to debug this further ?

**Comment by nicolarigoni** [comment]
@darshankawar  I have tried to run in -v mode but nothing more than the error 

The app has Benn launched but quit immediately and the Mac shows the alert 

Runner quit unexpectedly.
 
and in the console the same error is shown 
this is also some part of the log when the app is launched 
[   +5 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch 2968FFB4-44D7-4634-B052-D048C23EC147 net.madeinapp.moosaicof --enable-dart-profiling --enable-checked-mode --verify-entry-points
[ +505 ms] net.madeinapp.moosaicof: 7857
[        ] Waiting for VM Service port to be available...
[+2167 ms] [ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
[  +79 ms] VM Service URL on device: http://127.0.0.1:50663/r5Hjpyc5Iuc=/
[   +3 ms] Caching compiled dill
[ +115 ms] Connecting to service protocol: http://127.0.0.1:50663/r5Hjpyc5Iuc=/
[   +5 ms] Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 50664
[        ] This was attempt #1. Will retry in 0:00:00.100000.
[ +103 ms] Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 50665
[        ] This was attempt #2. Will retry in 0:00:00.200000.
[ +203 ms] Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 50666
[        ] This was attempt #3. Will retry in 0:00:00.400000.
[ +403 ms] Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 50667
[        ] This was attempt #4. Will retry in 0:00:00.800000.
[ +803 ms] Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 50668
[        ] This was attempt #5. Will retry in 0:00:01.600000.

**Comment by nicolarigoni** [comment]
@darshankawar  I have noticed if I launch the app also without the native view implementation the error: 

[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.

is shown anywhere. So I think that this is not the error that make the app crashes. But with native view I don't have any log at this point.

**Comment by darshankawar** [comment]
> [ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.

This log was fixed as part of https://github.com/flutter/engine/pull/50448 which I don't think is in stable yet. Can you switch to latest master and re-run your scenario to check if the log and crash still persists or not ?

**Comment by nicolarigoni** [comment]
@darshankawar can you explain how can I switch to latest master? Thanks

**Comment by darshankawar** [comment]
> switch to latest master

```
flutter channel master
flutter upgrade
```

**Comment by nicolarigoni** [comment]
@darshankawar I have switched to master 

```
Flutter is already up to date on channel master
Flutter 3.22.0-8.0.pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision 557fbf5167 (4 minutes ago) • 2024-04-11 14:46:13 +0100
Engine • revision d8560d495d
Tools • Dart 3.5.0 (build 3.5.0-47.0.dev) • DevTools 2.34.1
```
but unfortunately the behavior is always the same. The app crash at start. The only this that changed is that the error:
```
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
```
is not shows anymore but no more logs.

```
[   +7 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch 2968FFB4-44D7-4634-B052-D048C23EC147 net.madeinapp.moosaicof --enable-dart-profiling --enable-checked-mode --verify-entry-points
[ +570 ms] net.madeinapp.moosaicof: 41696
[        ] Waiting for VM Service port to be available...
[ +965 ms] VM Service URL on device: http://127.0.0.1:65157/CUL56Cd_WFo=/
[   +4 ms] Caching compiled dill
[ +109 ms] Connecting to service protocol: http://127.0.0.1:65157/CUL56Cd_WFo=/
[   +8 ms] Exception attempting to connect to the VM Service: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 65158
```

**Comment by darshankawar** [comment]
Thanks for the update. Can you provide us demo repo that we can clone and run locally to verify this further ?

**Comment by nicolarigoni** [comment]
@darshankawar  yes of course this is a new empty project with only the native view implementation. The behavior is the same. Crash at start with no logs. 

https://github.com/nicolarigoni/flutter-test

If you can have a look, it really important for me and my company to figure out what is happening. Thanks

**Comment by darshankawar** [comment]
Thanks for the repro @nicolarigoni 
I am hitting [this](https://github.com/flutter/flutter/issues/118055) issue while trying to run the repo so can't properly verify the issue at my end.
But, are you using iOS 17 version or any lesser ?
Maybe you are hitting below issues:

https://github.com/flutter/flutter/issues/130623
https://github.com/flutter/flutter/issues/122698

**Comment by nicolarigoni** [comment]
@darshankawar I'm using iOS 17 and testing on Simulator with Xcode 15.0. I made a test to clone my repo on a different Mac to make a test. But the only issue that I facing is this:

```
Swift Compiler Error (Xcode): Cannot find 'FLNativeViewFactory' in scope
```

What I looking for is a class inside:

```
FLNativeView.swift
```
that is not found even if it is inside le Runner but Xcode not find it, if you open Xcode and re-add it you can compile the app and try to run it. Even on a different Mac with Xcode 15.3 and simulator with iOS 17.4 the problem is always the same.

**Comment by darshankawar** [comment]
I am unable to replicate the reported behavior using the details and code sample provided, but based on the report, I will keep the issue open and label for team's input / attention.

**Comment by nicolarigoni** [comment]
@darshankawar Thanks. It seams impossible that is not replicable even tested on another mach with all fresh install and same behavior. Hope in some support on this

**Comment by jmagman** [comment]
Sorry for the confusion with the `Using the Impeller rendering backend.` error, but that's NOT an error and likely not related to your crash.
This issue isn't actionable without an actual crash backtrace or message or _something_.  Please reproduce the crash, and attach the crash log.  This used to be visible in the `flutter run` output but the way Flutter connections to physical devices recently changed to make this harder to find.
You can find it 
Xcode > Window > Devices and Simulators > your phone > Open Recent Logs
find the crash corresponding to the timestamp when your app crashed, and attach it here.

**Comment by nicolarigoni** [comment]
Hi, @jmagman thanks for support. Yes with this method I can see that the problem I think is here:
```
*** Assertion failure in -[FlutterEngine registrarForPlugin:], FlutterEngine.mm:1327
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate plugin key: QuickLook'
*** First throw call stack:
(0x1d37e1e88 0x1ccb938d8 0x1ce181b4c 0x105c8531c 0x1023f0488 0x1023f08a4 0x1d5cef888 0x1d5ceefac 0x1d5cedf88 0x1d5cedbd4 0x1d5a33600 0x1d5d75918 0x1d5c25fa4 0x1d5c25dcc 0x1d5c2597c 0x1d5c25848 0x1d6307fa8 0x1d63a0f98 0x1d5ad1958 0x1d5f447a8 0x1d5ba40b8 0x1d5ba3f28 0x1d5ba347c 0x1d5ba3208 0x1e93f1500 0x1e943051c 0x1e93f5294 0x1e9430154 0x1dadadfdc 0x1dadb1a5c 0x1e93ff3b0 0x1e93fef4c 0x1e940172c 0x1d38adf54 0x1d38ba32c 0x1d383e210 0x1d3853ba8 0x1d3858ed4 0x20c2b5368 0x1d5d373d0 0x1d5d37034 0x1023f0a1c 0x1f1eb0960)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x000000020fb22200 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x20fb22200 <+8>:  b.lo   0x20fb22220               ; <+40>
    0x20fb22204 <+12>: pacibsp 
    0x20fb22208 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x20fb2220c <+20>: mov    x29, sp
Target 0: (Runner) stopped.
```

So I try to change the plugin name in AppDelegate to this: 
```swift
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        
        weak var registrar = self.registrar(forPlugin: "QuickLookPlugin")
        
        let factory = FLNativeViewFactory(messenger: registrar!.messenger())
        self.registrar(forPlugin: "QuickLookPlugin")!.register(
            factory,
            withId: "QuickLook")
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}
```

but the exception is always the same duplicate key QuickLookPlugin. I don't know how to solve this

**Comment by nicolarigoni** [comment]
@jmagman @darshankawar It seams that I make ti work the problem was in the AppDelegate that the two registration mast have two different name even if I don't understand why two registration and what they do. 

```swift
 weak var registrar = self.registrar(forPlugin: "QuickLookPlugin")
        
        let factory = FLNativeViewFactory(messenger: registrar!.messenger())
        self.registrar(forPlugin: "QuickLook")!.register(
            factory,
            withId: "MooPreviewerViewType")
```

**Comment by gaaclarke** [comment]
OP found the source of their problem, they were registering duplicate plugins.  Closing.
