### ISSUE TITLE
Flutter icons don't show after deploying on Vercel or Aws Amplify

### ISSUE THREAD

**Issue by The-RootCause** [flutter/flutter#146425]
### Solutions already test and not working

Adding MaterialIcons-Regular.ttf to web/assets/font and FontManifest.json to web/assets. Not working.
Different version of flutter (Master, Beta) both the same issue. 

### Steps to reproduce

1. flutter build web --web-renderer canvaskit --release --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true --no-tree-shake-icons
2. Deploy on Vercel or amplify

### Expected results

Flutter icons showing as expected

### Actual results

Flutter icons unrecognized 

### Code sample

flutter build web --web-renderer canvaskit --release --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true --no-tree-shake-icons

### Screenshots or Video

![Screenshot 2024-04-08 at 15 53 42](https://github.com/flutter/flutter/assets/142636323/d40d4ceb-e18d-4232-91f3-9d0a64cefb74)

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-FR)
• Flutter version 3.19.5 on channel stable at /Users/amine/dev/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 300451a (9 days ago), 2024-03-27 21:54:07 -0500
• Engine revision e76c956498
• Dart version 3.3.3
• DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at /Users/amine/Library/Android/sdk
• Platform android-34, build-tools 34.0.0
• Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
• Xcode at /Applications/Xcode-beta.app/Contents/Developer
• Build 15C5028h
• CocoaPods version 1.15.2

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
• Android Studio at /Applications/Android Studio Preview.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
✗ Unable to determine Android Studio version.
• Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
• IntelliJ at /Applications/IntelliJ IDEA.app
• Flutter plugin version 78.5.1
• Dart plugin version 241.14768

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
• IntelliJ at /Users/amine/Applications/IntelliJ IDEA Ultimate.app
• Flutter plugin version 78.5.1
• Dart plugin version 241.14768

[✓] VS Code (version 1.87.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.86.0-insider)
• VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
• Flutter extension version 3.79.20231130

[✓] Connected device (3 available)
• iPad Pro (12.9-inch) (6th generation) (mobile) • 1248A3EA-3818-49B9-BC9D-6A59E5A05C56 • ios • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
• macOS (desktop) • macos • darwin-arm64 • macOS 14.4.1 23E224 darwin-arm64
• Chrome (web) • chrome • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
• All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by danagbemava-nc** [comment]
Hi @The-RootCause, do the icons load for you at a point and stop loading after you publish an update? 

Have you tried disabling caching on the cdn to see if it works? Does this work for you on firebase hosting? 

Can you also take a look at https://github.com/flutter/flutter/issues/136585 & https://github.com/flutter/flutter/issues/130000 to see if they are similar to your case?

**Comment by The-RootCause** [comment]
Hi @danagbemava-nc  none of the above worked, purged the cache on CDN level it didn't work. 
I didn't try Firebase hosting
Thank you

**Comment by danagbemava-nc** [comment]
@The-RootCause, I'm curious, can you try firebase hosting to see if this issue also reproduces there as well? While this issue has come several times, we often are not able to reproduce it ourselves which makes it a bit difficult to investigate and fix. 

If you do face this issue on firebase-hosting as well, can you please provide a complete minimal reproducible code sample so that we can investigate this? 

Thank you
