### ISSUE TITLE
`ImageReaderSurfaceProducer` interacts poorly with (some) plugins due to `ensureRunningOnMainThread`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#146465]
Some plugins may execute their Android code on another thread, i.e. not the main thread.

As a result, `ImageReaderSurfaceProducer` will fail at runtime, because some methods, like `FlutterJNI.scheduleFrame`, "must be executed on the main thread". This is blocking the migration of the `camera` plugin to `SurfaceProducer` (https://github.com/flutter/packages/pull/6461). There is an [example failure on Firebase Test Lab](https://firebase.corp.google.com/project/flutter-infra-staging/testlab/histories/bh.f0c4b6b33369b76c/matrices/8172926375172309006/executions/bs.a65d3ab83fef0d25), though, sort of scarily, nowhere else (maybe this is a good candidate test for `scenario_app`).

Possible options:

- This check is out of date, and we could remove it (would have to be thoroughly tested)
- We need to make sure tasks are posted in the UI thread, instead of the current thread/handler

/cc @jonahwilliams @johnmccutchan @gmackall

**Comment by jonahwilliams** [comment]
We should have some sort of "runNowOrPostTask" function that checks the current thread and either immediately executes the function or posts it to the correct thread. We may need to cherry pick this fix to unblock the impeller release in Q3

**Comment by matanlurey** [comment]
Jonah and I will take a look at this today.
