### ISSUE TITLE
endDrawer is difficult to trigger when iPhone X notch is present (landscape mode)

### ISSUE THREAD

**Issue by deborah-ufw** [flutter/flutter#14649]
## Steps to Reproduce

in iPhone X with an app with an endDrawer on the left side...

- turn the phone into landscape mode
- attempt to open the left drawer by swiping from the left

User has to swipe above or below the notch - can no longer just swipe left.

It seems like the swipe area to trigger the drawer needs to stick out past the notch, instead of being flush to the phone's left edge.

Are there any recommended solutions or adjustments for this yet?

**Comment by Hixie** [comment]
We should totally just make the edge-swipe detector wide enough to cover a pixel or two after the notch.

**Comment by xster** [comment]
actually this applies to cupertino page routes' back swipe too
