### ISSUE TITLE
consider what happens when running out of disk space downloading artifacts

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1464]
@abarth wanted me to file a bug for this

**Comment by Hixie** [comment]
cc @jcollins-g (FYI; not anything we're concerned about on the short term)

**Comment by khalithartmann** [comment]
Hello you awesome people!
I just created a Let's Flutter Berlin group on Facebook to bring flutter developers in Berlin together to discuss problems, share ideas and create beautiful things together. If you live in Berlin, it would be awesome if you could join the group 😊! If you don't live in Berlin, feel free to join too! Im grateful for each and every supporter.  

Let's Flutter Berlin: https://www.facebook.com/groups/276520973054067/about/
Sorry for spamming.

**Comment by jonahwilliams** [comment]
I don't think this is something the flutter_tool can or should worry about. Most operating systems have plenty of warnings/tools built in to deal with this situation
