### ISSUE TITLE
App developed with Flutter does not respond to any tap events after sudden crash and restart on iOS 17.1.1

### ISSUE THREAD

**Issue by wxjrkm520** [flutter/flutter#146484]
### Steps to reproduce

Description:

On iOS 17.1.1, an app developed with Flutter does not respond to any tap events after a sudden crash and restart.

Steps to reproduce:

Open the app on iOS 17.1.1.
Perform certain actions (these actions are unknown) that lead to the app crashing.
Restart the app. The app does not respond to any tap events.

### Expected results

The expected result is for the app to respond to tap events normally. However, the actual result is that after a crash and restart, the app does not respond to any tap events. All other functionalities are fine, but it's not possible to tap any buttons or icons. Only after restarting the phone, the app starts responding to tap events again.

### Actual results

The expected result is for the app to respond to tap events normally. However, the actual result is that after a crash and restart, the app does not respond to any tap events. All other functionalities are fine, but it's not possible to tap any buttons or icons. Only after restarting the phone, the app starts responding to tap events again.

### Code sample

only in ios 17.1.1 crashed
I have monitored the memory and there are no leaks.

### Screenshots or Video

https://github.com/flutter/flutter/assets/49952604/29f27a2d-1ad6-47af-b056-1cd8381230d1

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.19.5 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (12 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/a1234/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.88.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • iPhone乞丐版 (mobile)         • 00008101-0016342C1E87001E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 Pro Max (mobile) • 78411A1F-0012-4D49-8B64-208B2EFBBBC1 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

**Comment by huycozy** [comment]
Hi @wxjrkm520 
For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 

You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a minimal sample code that can produce the issue. And please share it here when you have such an example. Thanks!
