### ISSUE TITLE
Google maps integration test error (minSdkVersion)

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#146547]
### Testing With Android Studio JellyFish RC1 - Flutter Master (3.19.5)
1. Clone the Packages repository from: [GitHub - flutter/packages: A collection of useful packages maintained by the Flutter team](https://github.com/flutter/packages) 

2. Navigate to the cloned repository in the terminal:  `cd packages/google_maps_flutter/google_maps_flutter`
3. Execute the following command to run the integration tests: `flutter test integration_test -d <PUT_YOUR_ANDROID_SIMULATOR_ID> >> logs.txt`

### Expected results

Should execute without errors in Channel stable (version 3.19.5).

### Actual results

```console
┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────────┐
│ The plugin google_maps_flutter_android requires a higher Android SDK version.                    │
│ Fix this issue by adding the following to the file                                               │
│ /Users/qa/Documents/packages/packages/google_maps_flutter/google_maps_flutter/example/android/ap │
│ p/build.gradle:                                                                                  │
│ android {                                                                                        │
│   defaultConfig {                                                                                │
│     minSdkVersion 20                                                                             │
│   }                                                                                              │
│ }                                                                                                │
│                                                                                                  │
│ Following this change, your app will not be available to users running Android SDKs below 20.    │
│ Consider searching for a version of this plugin that supports these lower versions of the        │
│ Android SDK instead.                                                                             │
│ For more information, see:                                                                       │
│ https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration             │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>
[google_maps_flutter_google_maps_flutter_example-logs.txt](https://github.com/flutter/flutter/files/14926915/google_maps_flutter_google_maps_flutter_example-logs.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4 23E214 darwin-arm64, locale en-UY)
    • Flutter version 3.19.5 on channel stable at /Users/qa/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (12 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/qa/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
[✓] VS Code (version 1.87.2)
    • VS Code at /Users/qa/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0
[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 15 Pro (mobile)      • B2A329B0-EF53-4161-BC16-BE1654208FC4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 123.0.6312.107
[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by keodoff** [comment]
In `android/app/build.gradle` change on `minSdkVersion 20`

**Comment by naveenpardeep** [comment]
please upgrade your minSdkVersion as mentioned in the logs

**Comment by rzambroni** [comment]
Hi, yes, that works of course (21 and above).. but was wondering if the default minsdk of the test should be upgraded as well.

**Comment by gmackall** [comment]
I'm not able to reproduce this, likely because the example app in question
https://github.com/flutter/packages/blob/d4cd4f00254b2fdb50767c837ecd27bcbac488cd/packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle#L33
already has minSdkVersion set to 20.

Is your packages repo out of date? Can you post the full contents of 
`/Users/qa/Documents/packages/packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle`

**Comment by rzambroni** [comment]
> I'm not able to reproduce this, likely because the example app in question https://github.com/flutter/packages/blob/d4cd4f00254b2fdb50767c837ecd27bcbac488cd/packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle#L33 already has minSdkVersion set to 20.
> 
> Is your packages repo out of date? Can you post the full contents of `/Users/qa/Documents/packages/packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle`

Mine is also using minSdkVersion = 20, But it could be that we are using different simulators.

**Comment by gmackall** [comment]
> > I'm not able to reproduce this, likely because the example app in question https://github.com/flutter/packages/blob/d4cd4f00254b2fdb50767c837ecd27bcbac488cd/packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle#L33 already has minSdkVersion set to 20.
> > Is your packages repo out of date? Can you post the full contents of `/Users/qa/Documents/packages/packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle`
> 
> Mine is also using minSdkVersion = 20, But it could be that we are using different simulators.

Can you pipe both stdout and stderr to log? 
i.e. `flutter test integration_test -d <PUT_YOUR_ANDROID_SIMULATOR_ID> &>> logs.txt`. I suspect there is more to the logs, which is missing.

**Comment by gmackall** [comment]
Hmm I think I can see what might have happened - did you test this on master, and then on stable? I see you mention both master and stable in the issue description.

If you did, the changes from https://github.com/flutter/flutter/pull/142267 are in master, so you would have had your minSdkVersion in `/Users/qa/Documents/packages/packages/google_maps_flutter/google_maps_flutter/example/android/app/build.gradle` auto-upgraded from `20` to `flutter.minSdkVersion`, which on master would have been 21.

And then if you downgraded to `stable` to test after that, `flutter.minSdkVersion` would have become `19`, which would have caused this error. Are you certain you don't have any unstaged changes in the packages repo, indicating this auto-upgrade happened? And if you don't, is it still reproducible?

**Comment by rzambroni** [comment]
Hey @gmackall, good catch! you are right about that. Sorry for making you lose time on this. Closing the issue.
