### ISSUE TITLE
Workaround not followable for flutter 3.19

### ISSUE THREAD

**Issue by atharvsharma1998** [flutter/flutter#146562]
Im having an issue with a library. I found the solution by @gaaclarke however, there wasn't any file generated_main.dart ```./.dart_tool/flutter_build/generated_main.dart``` and there have been changes in the compile.dart. or am I missing something? 
 flutter doctor
 ```
 [✓] Flutter (Channel stable, 3.19.3, on macOS 13.5 22G74 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources
• No issues found!
 ```
 my logs:
 ```
 E/flutter (31544): [ERROR:flutter/runtime/dart_isolate.cc(677)] Could not resolve main entrypoint function.
E/flutter (31544): [ERROR:flutter/runtime/dart_isolate.cc(168)] Could not run the run main Dart entrypoint.
E/flutter (31544): [ERROR:flutter/runtime/runtime_controller.cc(462)] Could not create root isolate.
E/flutter (31544): [ERROR:flutter/shell/common/shell.cc(669)] Could not launch engine with configuration.
 ```
              Here is a workaround if this is blocking you (still trying to figure out a fix):

## Step 1
Apply the following patch to flutter:
```diff
--- a/packages/flutter_tools/lib/src/compile.dart
+++ b/packages/flutter_tools/lib/src/compile.dart
@@ -261,7 +261,9 @@ class KernelCompiler {
       // This is contained in the file `generated_main.dart` under `.dart_tools/flutter_build/`.
       final File newMainDart = buildDir.parent.childFile('generated_main.dart');
       if (newMainDart.existsSync()) {
-        mainUri = newMainDart.path;
+        print('before: $mainUri');
+        // mainUri = newMainDart.path;
+        print('after: $mainUri');
       }
     }
```

This will stop the plugin registrant from being included in your binary.

## Step 2 

Execute `flutter run` to make sure that `./.dart_tool/flutter_build/generated_main.dart` is generated.

## Step 3

Copy the `_PluginRegistrant` class from `./.dart_tool/flutter_build/generated_main.dart` into your `lib/main.dart`.   There is no need to call it, the engine will find it and execute it for you.  If you change your dependencies you will have to repeat this step.

_Originally posted by @gaaclarke in https://github.com/flutter/flutter/issues/91841#issuecomment-1006026551_

**Comment by darshankawar** [comment]
@atharvsharma1998 
Please don't use comments from other issues to open new issue. Try to use new issue template and fill out requested details so that we'll have enough info to work with.

The workaround you mentioned was for that issue applicable until it was fixed. So now I think you don't need to look for workaround. Please provide complete runnable reproducible code sample that we can directly copy paste and run along with current vs expected behavior you are looking for.

**Comment by atharvsharma1998** [comment]
Thanks the issue was fixed. It was caused due to another library
