### ISSUE TITLE
Android mobile version 14 supports chapters(Nothing Phone 1 Android 14), but below 14 versions are not supported (Realme Narzo Android 13).(Flutter version 3.19)

### ISSUE THREAD

**Issue by prabavgts** [flutter/flutter#146560]
### Steps to reproduce

Play Vimeo video on 14 version and  below 14 version mobiles. Below 14 version doesn't support package chapters on mobiles.

### Expected results

i want breaks in progress bar example like below
![Screenshot_20240409-123059](https://github.com/flutter/flutter/assets/67138992/9dacd544-2c6f-4b1d-8cc3-9f7f0a17a4fa)

### Actual results

but below 14 version doesnt support like below
![Screenshot_20240409-122917](https://github.com/flutter/flutter/assets/67138992/9c15236a-e49a-4b04-88eb-d0f02b5b499e)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![Screenshot_20240409-123059](https://github.com/flutter/flutter/assets/67138992/cf142420-a88f-4588-83d9-9951c2cd0d71)
![Screenshot_20240409-122917](https://github.com/flutter/flutter/assets/67138992/8186bc5b-5d01-480f-b1b0-829db895937c)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.19.4, on macOS 13.3.1 22E261 darwin-arm64 (Rosetta), locale en-IN)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Applications/user_installed/flutter. Consider adding
      /Applications/user_installed/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
vgts@Praba-MacBook-Pro-2 untitled3 % flutter doctor -v)
zsh: parse error near `)'
vgts@Praba-MacBook-Pro-2 untitled3 % flutter doctor -v 
[!] Flutter (Channel stable, 3.19.4, on macOS 13.3.1 22E261 darwin-arm64 (Rosetta), locale en-IN)
    • Flutter version 3.19.4 on channel stable at /Applications/user_installed/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Applications/user_installed/flutter. Consider adding
      /Applications/user_installed/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (3 weeks ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vgts/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (4 available)
    • RMX3571 (mobile) • 7TRK8DKZFETSIFAM                                   • android-arm64  • Android 13 (API 33)
    • RMX3571 (mobile) • adb-7TRK8DKZFETSIFAM-2JBriQ._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos                                              • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64 (Rosetta)
    • Chrome (web)     • chrome                                             • web-javascript • Google Chrome 123.0.6312.107

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by darshankawar** [comment]
@prabavgts 
Are you talking about native Android video player running on OS 14 version that supports the progress bar breaks ? And not Android versions less than 14 ?
Or are you reporting this for flutter's video_player plugin running on OS 14 versus less than OS 14 ?

**Comment by darshankawar** [comment]
@prabavgts 
Have you already checked the same with native Android webview on 14 and less than 14 version to see if it properly works on it and it is only occuring in flutter's webview ?

**Comment by prabavgts** [comment]
Yes I have already checked.
Other WebView packages do not support Chapters on all Android versions.
But luckily webview_flutter: ^4.4.2 supports the chapters but it works only in 14 version.Below 14 versions don't support
I checked the 13 and 12 versions @darshankawar

**Comment by darshankawar** [comment]
Thanks for the update. 

> but it works only in 14 version.Below 14 versions don't support
> I checked the 13 and 12 versions

Maybe this is Android 14's feature and may not be available on lesser versions. Can you check the Android 14 release notes wherein you can find about the it.

**Comment by prabavgts** [comment]
14 release does not mention the feature. Can you help me with that? @darshankawar

**Comment by darshankawar** [comment]
https://support.google.com/youtube/answer/12825599?hl=en&co=GENIE.Platform%3DAndroid you can check.
I think the equivalent would be `seekTo` feature via video player's controller but I don't think this is Flutter specific or actionable from Flutter. 
Closing for now. If you disagree, write in comments and I'll reopen it.
