### ISSUE TITLE
Allow overriding `Widget.canUpdate` behavior

### ISSUE THREAD

**Issue by mateusfccp** [flutter/flutter#146504]
### Use case

There are cases where you may want to override the behavior of `Widget.canUpdate`.

I encountered this scenario while developing an API where I had two widgets, let's call them `A` and `B`, both of which shared the same state. My objective was to ensure that when replacing one widget with the other within the widget tree, the state would persist and trigger the `didUpdateWidget` method. This already happens when the widget has the same `runtimeType`, but as `A` and `B` had different `runtimeType`s `didUpdateWidget` wouldn't trigger.

The easiest way to do this would be overriding the `Widget.canUpdate` behavior, but it is a static method, so there's no way to do it.

So, instead, I made a workaround with the `==` operator on `Type` that allowed be to introduce this behavior:

```dart
@immutable
final class _SharedType implements Type {
  const _SharedType(this.baseType, this.otherType);

  final Type baseType;
  final Type otherType;

  @override
  bool operator ==(Object other) {
    if (other == baseType || other == otherType) {
      return true;
    } else if (other is _SharedType) {
      return baseType == other.baseType || //
          otherType == other.baseType ||
          baseType == other.otherType ||
          otherType == other.otherType;
    } else {
      return false;
    }
  }

  @override
  int get hashCode => Object.hash(baseType, otherType);
}

final class A extends StatefulWidget {
  // ...

  @override
  Type get runtimeType => const _SharedType(A, B);
}

final class B extends StatefulWidget {
  // ...

  @override
  Type get runtimeType => const _SharedType(B, A);
}
```

As you can see, this is a hacky solution and inherently unsafe, but served well for my use-case.

### Proposal

We should have a way to override the `Widget.canUpdate` behavior.

For instance, it could be a dynamic method on `Widget` that would default to:
```dart
bool canBeUpdatedWith(Widget newWidget) {
  return runtimeType == newWidget.runtimeType
      && key == newWidget.key;
}
```

Then, for backward compatibility, we redefine `Widget.canUpdate`:
```dart
static bool canUpdate(Widget oldWidget, Widget newWidget) {
  return oldWidget.canBeUpdatedWith(newWidget);
}
```

With this approach, I would be able to redefine my implementation in a non-hacky (or less hacky) way:
```dart
// class _SharedType is not necessary anymore

final class A extends StatefulWidget {
  // ...

  @override
  bool canBeUpdatedWith(Widget newWidget) {
    return (newWidget is B || runtimeType == newWidget.runtimeType)
        && key == newWidget.key;
  }
}

final class B extends StatefulWidget {
  // ...

  @override
  bool canBeUpdatedWith(Widget newWidget) {
    return (newWidget is A || runtimeType == newWidget.runtimeType)
        && key == newWidget.key;
  }
}
```

**Comment by goderbauer** [comment]
> My objective was to ensure that when replacing one widget with the other within the widget tree, the state would persist and trigger the didUpdateWidget method.

Can you describe what use case this would enable? Or what problem you were solving that lead you to this solution?

**Comment by mateusfccp** [comment]
> Can you describe what use case this would enable? Or what problem you were solving that lead you to this solution?

It's nothing more than an API choice.

For instance, let's consider a stateful box widget that may be open or closed.

We can do it this way:

```dart
final class Box extends StatefulWidget {
  const Box(this.open);

  final bool open;

  @override
  State<Box> createState => _BoxState();
}

final class _BoxState extends State<Box> {
  @override
  void didUpdateWidget() {
    super.didUpdateWidget();
    // Handle changes in open parameter
  }

  // ...
}
```

This way, if I ever change the `open` parameter, the state will handle it and do something.

Now, I may want to remove this parameter in favor of a more semantic API. I can do this easily with named constructors:

```dart
final class Box extends StatefulWidget {
  const Box.open() : open = true;

  const Box.close() : open = false;

  final bool open;

  @override
  State<Box> createState => _BoxState();
}

final class _BoxState extends State<Box> {
  @override
  void didUpdateWidget() {
    super.didUpdateWidget();
    // Handle changes in open parameter
  }

  // ...
}
```

This way, I may, instead of changing a parameter explicitly, change the constructor entirely in the widget tree, and the behavior will be exactly the same.

However, in my case, my client explicitly required that instead of using named parameter like the example above, we used different class names, like `OpenBox` and `ClosedBox`. The behavior is exactly the same and the API is very similar, but as we have to use this naming scheme, I had to create two different widgets sharing the same state.

So, like I said, it's purely "aesthetics", the only reason we had to do this way was because our client required the API to be this way.

**Comment by goderbauer** [comment]
I am going to close this as we are unlikly to implement this. As you already said, there are many other ways to achieve the behavior you want and allowing this doesn't add anything new while making the system more complex to reason about. This is also against some other design choices that Flutter has made (i.e. a State class is tied to a single widget class)

**Comment by mateusfccp** [comment]
> As you already said, there are many other ways to achieve the behavior you want […]

Sure, but in my case I didn't even have the choice to do the "Flutter way", as it was a requirement given by my client.

In this case, we can either have a "more proper" way of doing it or resort to hack the `runtimeType` of objects, which, in my opinion, is way worse.

> […] allowing this doesn't add anything new while making the system more complex to reason about.

Could you elaborate on how doing this would make the system more complex to reason about? The behavior will be, by default, exactly the same, and 99% of people using Flutter won't ever need to deal with this edge-case, so they won't ever need to reason about this.

But for the 1% that may have to deal with this edge-cases, we will provide them with a tool to avoid having hacky and way unsafer solutions.

> This is also against some other design choices that Flutter has made (i.e. a State class is tied to a single widget class)

Well, I can't argue about it, as it is an arbitrary decision.
