### ISSUE TITLE
[two_dimensional_scrollables] Request for pinned table's right columns

### ISSUE THREAD

**Issue by thanhdatvo** [flutter/flutter#146542]
### Use case

Currently, the table widget in two_dimension_scrollable only allow to pin left columns

### Proposal

The table widget in two_dimension_scrollable should also allow to pin right columns

**Comment by huycozy** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133238 with detailed information, please follow up on it for further updates.
