### ISSUE TITLE
[skwasm] Platform view starts off to the side of the screen in Wasm (but not JS)

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#146539]
Reproduction
1. load a wonderous
2. scroll down to a video element
3. hit the play button

https://wonderous-kevmoo.web.app/#/home

![image](https://github.com/flutter/flutter/assets/17034/9df7c499-d8cc-420c-a813-e990e414f722)

https://wonderous-kevmoo.web.app/?force_canvaskit=true#/home

![image](https://github.com/flutter/flutter/assets/17034/bb553d2a-a91f-4cfc-9f37-64de2f3750dc)

Wasm - the video iframe thing is off to the side, but fine in JS

Resizing the wasm version seems to fix things!

**Comment by Rexios80** [comment]
Has a better workaround been found besides delaying the rendering of PlatformViews?

**Comment by eyebrowsoffire** [comment]
I believe this should be fixed with recent changes to platform view stuff with Skwasm. @kevmoo can you confirm?

**Comment by eyebrowsoffire** [comment]
Confirmed this is fixed in the latest flutter master

**Comment by kevmoo** [comment]
Specifically

```
Flutter 3.24.0-1.0.pre.301 • channel master • git@github.com:flutter/flutter.git
Framework • revision 112e4087e8 (3 days ago) • 2024-07-27 04:55:49 +0900
Engine • revision e28f8755e2
Tools • Dart 3.6.0 (build 3.6.0-85.0.dev) • DevTools 2.37.1
```
