### ISSUE TITLE
[in_app_purchase] [android] Problem upgrading to Android 34

### ISSUE THREAD

**Issue by adriancsbna** [flutter/flutter#146687]
### Steps to reproduce

1. Create a Flutter Project
2. Set compileSdkVersion 34 and targetSdkVersion 34 in Android project.
3. Execute InAppPurchase.instance.isAvailable();
4. The error appears

### Expected results

The expected result is a Bool indicating availability or not.

### Actual results

I get the following exception:
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### Code sample

 InAppPurchase.instance.isAvailable();

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale
    es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.0)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @adriancsbna, I checked this using [package example](https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example) but couldn't see the issue. What is the `in_app_purchase_android` version in your `pubspec.lock` file?

**Comment by adriancsbna** [comment]
Hi @huycozy . Sure, I'll write it down here.

in_app_purchase:
    dependency: "direct main"
    description:
      name: in_app_purchase
      sha256: def70fbaa2a274f4d835677459f6f7afc5469de912438f86076e51cbd4cbd5b4
      url: "https://pub.dev"
    source: hosted
    version: "3.1.13"
  in_app_purchase_android:
    dependency: transitive
    description:
      name: in_app_purchase_android
      sha256: "8caffed71ea381e8b2cecda8a945019a46fe6f6e24ea079def17a68a74778f37"
      url: "https://pub.dev"
    source: hosted
    version: "0.3.0+4"

**Comment by huycozy** [comment]
Thanks. I see you are using an old version of `in_app_purchase_android`. Please upgrade it to the latest one to see if the issue persists or not. The latest version is `in_app_purchase_android: ^0.3.3+1`.

**Comment by adriancsbna** [comment]
Hi @huycozy . It worked correctly when I updated it. 
I am surprised that it does not update that dependency when updating the in_app_purchase plugin. 
Best regards and thanks.
