### ISSUE TITLE
Flutter tool to validate/check local environment is correct

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1466]
This is a request for a command, potentially added to the `flutter` tool, to validate a user's configuration. This tool can check various environment variables, installed tools, configured dependencies, and tell the developer if A) everything is green good to go or B) something is wrong that may impact their dev experience.

Bonus: the tool should suggest ways to fix identified problems. Perhaps by providing a link to more information.

Inspired by `brew doctor`, but this proposal is for a tool that can be run at the end of the Getting Started process. The term "doctor" seems like "something that is run when you suspect something is wrong". Instead we want "something that is run to reaffirm that you are good to go". Think of it like preventative medicine.

Things the tool can check:

* dart sdk is downloaded and is at the correct location
* android sdk is correct, with the correct version
* xcode is correct, with version
* if atom is installed, the flutter plugin is installed
* the flutter sdk itself is fully installed

**Comment by sethladd** [comment]
cc @chinmaygarde @devoncarew who had ideas for this.

**Comment by eseidelGoogle** [comment]
Are either @devoncarew or @chinmaygarde owning this, or is this up for grabs?

**Comment by devoncarew** [comment]
Up for grabs for my part. It would be great to have this command, and some re-usable logic, so that other commands can make use of some or all of the checks (`create` perhaps).

**Comment by devoncarew** [comment]
We have `flutter doctor` now; it implements some of the above checks. We could add some additional info about what versions of things are installed, checks for Atom, and validate the flutter sdk itself.

**Comment by abarth** [comment]
IMHO, we should close this bug now that we have `flutter doctor` and open more specific bugs for more specific feature requests.
