### ISSUE TITLE
Able to access complete Shared Preference values in iOS flutter application.

### ISSUE THREAD

**Issue by GDEVENDRAK** [flutter/flutter#146678]
### Steps to reproduce

I submitted mobile application to VAPT testing. In VAPT testing the team able to view all the shared preference values in
ios plist cat <packagename>.plist.

### Expected results

User should not be accessible to shared preference values. ?

Attached Screenshot shared by team
![Screenshot 2024-04-12 132604](https://github.com/flutter/flutter/assets/4927052/5c22d4c8-3ddf-4f07-803e-10c1c8d0e343)

### Actual results

Able to access Shared Preference values

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
> User should not be accessible to shared preference values.

Is there something in the package description or README that led to this expectation? We try to be very clear about the storage mechanics on each platform in the README.
