### ISSUE TITLE
☂️ Android 15 Edge to Edge support 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#146657]
Goal: 
* Determine behavior of edge to edge in flutter apps including gaps with safe area, insets etc. Link issues to this bug. 
* Design doc (if required) 
* Determine what docs/codelabs will be need to be updated 
* Update templates to be edge to edge ready (if required) 
* Fix any issues discovered in investigation
* Update docs/codelabs

**Comment by camsim99** [comment]
Oops I forgot this issue existed :( I fleshed this out more in https://github.com/flutter/flutter/issues/150374 so closing this as a duplicate.
