### ISSUE TITLE
If I am playing audio when receiving background notification and opening app by clicking on notification in that case if I am stopping notification then it is not working.

### ISSUE THREAD

**Issue by rohit0713** [flutter/flutter#146680]
### Steps to reproduce

flutter run

### Actual results

If I am playing audio when receiving background notification and opening app by clicking on notification in that case if I am stopping notification then it is not working.

### Logs

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';
AudioManager audioManager = AudioManager();
class AudioManager extends ChangeNotifier {
  static final AudioPlayer _audioPlayer = AudioPlayer(playerId: '1');
  static final AudioManager _instance = AudioManager._internal();

  AudioManager._internal();

  factory AudioManager() {
    return _instance;
  }

  void play(String src) async {
    await _audioPlayer.play(
      AssetSource(src),
    );
    notifyListeners();
  }

  void stop() async {
    print("Stop Clicked====${_audioPlayer.playerId}");

    _audioPlayer.pause();
    _audioPlayer.stop();
    _audioPlayer.release();

    notifyListeners();
    print("Audio stopped");
  }
}

@pragma('vm:entry-point')
Future<void> _handleBackgroundMessage(RemoteMessage message) async {
  print("========");

  await temp(message);
}

Future<void> temp(RemoteMessage message) async {
  String channelId = "message",
      channelName = "message",
      channelDesc = "message";
  AndroidNotificationDetails androidNotificationDetails =
      AndroidNotificationDetails(
    channelId,
    channelName,
    channelDescription: channelDesc,
    channelAction: AndroidNotificationChannelAction.createIfNotExists,
    importance: Importance.max,
    priority: Priority.max,
    enableLights: true,
    visibility: NotificationVisibility.public,
    playSound: true,
    sound: const RawResourceAndroidNotificationSound('c2b_notif'),
  );
  // ! IosNotificationDetails
  DarwinNotificationDetails iosNotificationDetails =
      const DarwinNotificationDetails(
    presentSound: true,
    presentBadge: true,
    presentAlert: true,
    threadIdentifier: 'thread_id',
  );
  if (message.data['title']!.toString().toLowerCase().contains("placed")) {
    audioManager.play('sound_n_vendor-full.mp3');
  }
  NotificationDetails notificationDetails = NotificationDetails(
      android: androidNotificationDetails, iOS: iosNotificationDetails);
  await flutterLocalNotificationsPlugin.show(
    notificationCount,
    message.data['title'],
    message.data['body'],
    notificationDetails,
  );

  notificationCount++;
}

ElevatedButton(
                        style: ButtonStyle(
                          backgroundColor: MaterialStateProperty.all(
                            !isSelected(data.orderDetails ?? [])
                                ? Colors.red
                                : const Color.fromRGBO(48, 209, 88, 1),
                          ),
                        ),
                        onPressed: () async {
                          audioManager.stop();

                  
                        },
                        child: provider.loader
                            ? const SizedBox(
                                height: 30,
                                width: 30,
                                child: CircularProgressIndicator(
                                  color: Colors.white,
                                ),
                              )
                            : appText(
                                title: !isSelected(data.orderDetails ?? [])
                                    ? 'Reject'
                                    : 'Accept',
                                fontSize: 14,
                                fontWeight: FontWeight.bold,
                                color: Colors.white,
                              ),
                      );

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4291], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.88.0)
[√] Connected device (5 available)
[√] Network resources

**Comment by darshankawar** [comment]
@rohit0713 
Your issue / question is better suited for support channels like StackOverflow so please ask the same there.
Closing from here as this doesn't seem to be sdk specific issue as it involves third party code implementation.
