### ISSUE TITLE
☂️ Freeform mode in Android 15

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#146659]
Goals: 
* Investigate https://github.com/flutter/flutter/issues/146658
* Fix https://github.com/flutter/flutter/issues/146658 
* Identify gaps/issues that currently exist with Flutter apps being used in any size window on tablets
* Implementation on design doc/gaps beyond AGSA issue
* Template updates to make "flutter create" apps freeform ready

**Comment by reidbaker** [comment]
While doing this work we discovered we needed to build the engine against the beta version of android 15. 
That has been uploaded under tag [version:35betav1](https://chrome-infra-packages.appspot.com/p/flutter/android/sdk/all/linux-amd64/+/version:35betav1).

**Comment by sfshaza2** [comment]
@reidbaker, will this require docs for the Q3 release?

**Comment by reidbaker** [comment]
Do we have a doc I can read with our expectations on what we usually document

**Comment by reidbaker** [comment]
To enable this feature 
In android developer settings select "Enable freeform windows" then reboot the device. 
Then build and run a flutter app, 
in task switcher on the device long press on the icon of the app, 
then select "freeform".

**Comment by reidbaker** [comment]
Template does not need to be update to support freeform. MaterialApp has safe area usage and I confirmed that flutter apps behave the same as regular apps (chrome).

**Comment by reidbaker** [comment]
Left to do before closing this issue, run through an internal CUJ checklist on a pixel tablet or some other tablet with windowing enables with flutter create or wonderous. 
go/flutter-android-freeform-cuj-checklist

**Comment by reidbaker** [comment]
Complete
