### ISSUE TITLE
google maps web support to package js 0.7.1

### ISSUE THREAD

**Issue by JgomesAT** [flutter/flutter#146683]
### Use case

We have some conflicts with libraries of use of package js the major part of libraries are updated to use js 0.7 but Google maps uses 0.6 is it possible to update to version 0.7.1?

### Proposal

update this libraries

**Comment by huycozy** [comment]
Hi @JgomesAT 
>but Google maps uses 0.6

Could you please elaborate on this? Please share an example and also error output that you see conflicts.

**Comment by JgomesAT** [comment]
Libraries like firebase, g_recaptcha_v3, for preparing for a future build to WSAM are updating the library of js by now I'm using the dependency_overrides in web to compile the project

Resolving dependencies...
Because no versions of g_recaptcha_v3 match >0.0.6 <0.1.0 and g_recaptcha_v3 0.0.6 depends on js ^0.7.0, g_recaptcha_v3 ^0.0.6 requires js ^0.7.0.
Because google_maps 7.1.0 depends on js ^0.6.3 and no versions of google_maps match >7.1.0 <8.0.0, google_maps ^7.1.0 requires js ^0.6.3.

**Comment by huycozy** [comment]
You are using [google_maps](https://pub.dev/packages/google_maps) which is a different package than [google_maps_flutter](https://pub.dev/packages/google_maps_flutter). You should report the issue to [google_maps repository](https://github.com/a14n/dart-google-maps/issues) for better support there. 

Closing this as it's not an issue with `google_maps_flutter` package.
