### ISSUE TITLE
[web]: webapp unable to launch without internet access at least one time

### ISSUE THREAD

**Issue by guitarpicva** [flutter/flutter#146756]
Firefox latest on Win 11 latest.

Deploying webapp to nginx server (Ubuntu 22) and connecting directly via Ethernet with static IP addressing on both systems.  Both server and PC are air-gapped from the internet.

Open address of webapp (192.168.0.224) and the favicon.ico shows on the Firefox tab, but the webapp never loads.

Connect the calling PC to the internet via WiFi and reload the page and the webapp loads properly.  

Close the WiFi connection and the webapp continues to function normally.

Reboot the calling PC and the webapp continues to function normally.

Delete cookie/data from dart.dev in Firefox and the webapp FAILS to load.

Repeat WiFi connection and the webapp functions normally again.

**Comment by guitarpicva** [comment]
Browswer network trace indicates calls to www.gstatic.com for retrieving canvaskit.js and canvaskit.wasm modules as well as to fonts.gstatic.com.  The build/web has both canvaskit.js and canvaskit.wasm modules as part of the deployment.

A documented deployment method is suggested for a deployment that obviates the need for internet sourcing of these (or any such) items.

**Comment by huycozy** [comment]
Hi @guitarpicva 
>Delete cookie/data from dart.dev in Firefox and the webapp FAILS to load.

This is strange because dart.dev is different from your web app. Is this a prerequisite to reproduce the issue? I'm quite confused about the pattern to reproduce this issue. Please try to observe to see if you can replicate it consistently and see if it has any pattern. 

Also, please check if the issue occurs on a newly created Flutter project. And please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by guitarpicva** [comment]
You are correct, and I found that rather strange as well. I CANNOT reproduce the dart.dev cache symptom (in fact, that cache never shows back up), but first I tried deleting the flutter.dev cache and it had no effect, so then I deleted dart.dev cache and it then failed to load. The magic downloads get put "somewhere" that is not documented and so it's a bit difficult to trace.

The goal set here is to be able to deploy an air-gapped web application, so we have to have all assets in hand, obviously. I cannot find any documentation to lead one to such an answer, so if we go down this road, then we will have to manually download and deploy any required resources and hope we didn't miss any. Plus this means we will likely have to amend the javascript which I find dangerous. Not knowing where to put everything once gathered is another question.

My feedback was to prompt perhaps some documentation about the PWA efforts that may lead to more in-depth understanding of the deployment structure.

--
Mitch, AB4MW

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by huycozy** [comment]
Thanks for the update but it's still not clear how your web is failed to load. It would be helpful if you could share the error/warning log. Please also provide the output of `flutter doctor -v`.

Based on what you described, please check https://github.com/flutter/flutter/issues/121743 and https://github.com/flutter/flutter/issues/60069 to see if the information there is helpful.

**Comment by guitarpicva** [comment]
Interesting switch "--pwa-strategy=offline-first". I haven't found documentation for anything to do with pwa, but that gave me a clue to look at the help for flutter build web.

I will give this a go and see how it behaves.

Thank you so much for taking the time to pitch in!

Mitch

--
Mitch, AB4MW

Sent with [Proton Mail](https://proton.me/) secure email.
