### ISSUE TITLE
Incorect error message when building for MacOS, iOS is mentionned

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#146744]
### Steps to reproduce

```$ flutter build macos
...
Error: The pod "Firebase/Analytics" required by the plugin "firebase_analytics" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "firebase_analytics", or contact the plugin's developers for assistance.
Error running pod install
```
The error message is incorrect MacOS is not iOS.

### Expected results

```
Error: The pod "Firebase/Analytics" required by the plugin "firebase_analytics" requires a higher minimum **MacOS** deployment version than the plugin's reported minimum version.
To build, remove the plugin "firebase_analytics", or contact the plugin's developers for assistance.
Error running pod install
```

### Actual results

```

Error: The pod "Firebase/Analytics" required by the plugin "firebase_analytics" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "firebase_analytics", or contact the plugin's developers for assistance.
Error running pod install
```

### Code sample

<details open><summary>Code sample</summary>

```dart
no code
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @stephane-archer,

Please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you

**Comment by stephane-archer** [comment]
deleting Pods and pod.lock solves the issue on my side but your error message is wrong, search for "requires a higher minimum iOS deployment version than the plugin's" in your codebase to find the issue and make a platform-dependent string.

**Comment by stephane-archer** [comment]
maybe look at `
packages/flutter_tools/test/general.shard/macos/cocoapods_test.dart` line 505 ?

**Comment by stuartmorgan** [comment]
This was a mistake in https://github.com/flutter/flutter/pull/138097, I adjusted two of the error messages to handle this correctly, but missed the third one.
