### ISSUE TITLE
[A11y][Android] Badge bubble does not scale with text font size

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#146777]
b/317118086
### Steps to reproduce

1. Run https://github.com/flutter/flutter/tree/master/dev/a11y_assessments
2. In the list press badge
3. go to setting -> accessibility -> font size, and increase font size
4. The text in the bubble increase in size, but not the bubble it self
![image](https://github.com/flutter/flutter/assets/47866232/e546621f-7718-4d97-9c35-d175647b0e23)

### Actual results

The bubble should also increase in size

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by chunhtai** [comment]
Hi @TahaTesser sorry I forgot to assign myself, but I was already working on this issue. Is it ok if I take over?

**Comment by TahaTesser** [comment]
@chunhtai of course, you can take it! 

And welcome back!
