### ISSUE TITLE
ThemeData Color rendering discrepancy

### ISSUE THREAD

**Issue by MrPiou94** [flutter/flutter#146762]
### Steps to reproduce

https://docs.flutter.dev/cookbook/design/themes
1. Go to the page and run "Try an interactive example".
2. Set the button color using "color: Color(0xff00acaf)".
3. Use the color picker.
4. See the difference: 0xff00acaf ==> #4DA9AD.

### Expected results

The color difference prevents a strict rendering of the company's color theme.

### Actual results

The colors are not respected.

### Code sample
```dart
       Center(
        child: Container(
          padding: const EdgeInsets.symmetric(
            horizontal: 12,
            vertical: 12,
          ),
          color: Color(0xff00acaf),
          child: Text(
            'Text with a background color',
            style: Theme.of(context).textTheme.bodyMedium!.copyWith(
                  color: Theme.of(context).colorScheme.onPrimary,
                ),
          ),
        ),
      ),
```

### Screenshots or Video

![Diff](https://github.com/flutter/flutter/assets/19947603/3568837c-9ca3-4439-b995-5588a006c036)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by MrPiou94** [comment]
![Diff](https://github.com/flutter/flutter/assets/19947603/b8d8a01e-1d32-407d-ad08-b74ddfde98e3)

**Comment by moffatman** [comment]
Looks like your display/color picker uses Display P3 color space and your input colour is in sRGB. But it is the same colour. Set your monitor to sRGB, and it will show the same values, it does for me.

**Comment by MrPiou94** [comment]
Thank you for the response,
Here is additional information, this is on the same screen. I am getting different results for the same color code and we can see that the colors are actually different.

![diff2](https://github.com/flutter/flutter/assets/19947603/6ddd1299-9e28-4090-a589-65ca5133591d)

**Comment by moffatman** [comment]
Your colour picker is showing the P3 color space color.  When you enter it as a sRGB colorspace color, the color will be different, yes. You should use a color picker which shows you the sRGB color if you want to render that colour with flutter, which uses sRGB color space. It will make your life a lot easier than being confused and having to convert colour spaces.

<img width="680" alt="image" src="https://github.com/flutter/flutter/assets/789275/92d0ae95-9c59-49bf-aff0-77d84994e9e8">

If you want to render the green shown on the left, use the sRGB color `#41E100`

Flutter always takes `Color()` as sRGB. There is a ticket open to allow users to specify colors in P3 space, but it hasn't been done yet. https://github.com/flutter/flutter/issues/127855

**Comment by MrPiou94** [comment]
It was the color picker that wasn't in the right color space. I found another one. It's the first time I have to adhere to an exact color code. Thank you for the information, it was very helpful!

**Comment by MrPiou94** [comment]
close
