### ISSUE TITLE
Support accessibility for tristate checkboxes

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#14677]
Currently a11y treats tristate checkboxes as if they're ordinary checkboxes. The null (indeterminate) value is treated as if it were true.

HTML supports indeterminate checkboxes.

cc @goderbauer 

See https://github.com/flutter/flutter/pull/14611

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/18297
