### ISSUE TITLE
After flutter is installed, first Hello World running on Android in 10 sec

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1467]
Assuming the developer has their device plugged in, and developer mode enabled, the developer should be able to create the starter app and run it on their Android phone within 10 seconds.

**Comment by eseidelGoogle** [comment]
The steps for this are documented at https://flutter.io/getting-started/. It's not clear which exactly we're testing for the 10s metric.

Presumably
```
flutter create my_app
cd my_app
flutter start
```
Correct?

**Comment by sethladd** [comment]
Yup! Assume Flutter is installed correctly, the device is setup correctly.

**Comment by Hixie** [comment]
Pretty sure we can do this now. Please file a more specific bug if you aren't happy with our first-hello-world dev performance. :-)
