### ISSUE TITLE
Add "EdgeInsets? margin" to  ButtonStyle

### ISSUE THREAD

**Issue by LinHaoLove** [flutter/flutter#146796]
### Use case

In some cases, I need the desktop and mobile to have the same button layout.
The Button style is now available in different styles for different platforms. And the only option.

### Proposal

Add "EdgeInsets? margin" to  ButtonStyle.
If margin==null, the existing style is used.
If margin! =null, I want to be able to achieve the desired style.
Thank you very much.

**Comment by huycozy** [comment]
Hi @LinHaoLove 
I wonder how the margin works inside ButtonStyle. Could you please be more specific? 

ButtonStyle includes visual properties for the button such as color, textStyle or padding between the button's boundary and its child. The properties apply inside the button. Meanwhile, margin as I understand it is the distance between the button and the ancestor widget.

**Comment by LinHaoLove** [comment]
> Hi @LinHaoLove I wonder how the margin works inside ButtonStyle. Could you please be more specific?
> 
> ButtonStyle includes visual properties for the button such as color, textStyle or padding between the button's boundary and its child. The properties apply inside the button. Meanwhile, margin as I understand it is the distance between the button and the ancestor widget.

For example, when multiple buttons are placed in a Row or Column.
And "mainAxisAlignment: MainAxisAlignment.start,", 
The spacing between buttons will vary on different platforms.
I hope that sometimes they are the same on different platforms. And the spacing can be set, I cannot modify the spacing between them now.
Now I have customized a button to solve this problem, but my coding skills are not very good.

**Comment by Piinks** [comment]
@LinHaoLove can you share an example of what you are specifically trying to achieve with ButtonStyle?
Some sample code would be very helpful to identify the issue here.

> For example, when multiple buttons are placed in a Row or Column.

ButtonStyle only applies to one button, it does not apply to multiple buttons or how they are positioned in relation to each other.

**Comment by Piinks** [comment]
Thanks for extracting this! This is something that should be handled with the Padding widget, or in a Row/Column I've seen folks use a SizedBox for spacing as well. We typically do not enumerate padding properties on widgets, since we have a Padding widget!

Thanks for clarifying the issue.

**Comment by LinHaoLove** [comment]
> Thanks for extracting this! This is something that should be handled with the Padding widget, or in a Row/Column I've seen folks use a SizedBox for spacing as well. We typically do not enumerate padding properties on widgets, since we have a Padding widget!
> 
> Thanks for clarifying the issue.

Hi，
Based on the current state, there will be different padding on different platforms.
SizedBox or Padding will increase their spacing on top of the existing spacing. And it won't keep their spacing the same.
So，we need to first unify their existing spacing by a optional way .
