### ISSUE TITLE
[video_player] add useful events similar to html5 video element

### ISSUE THREAD

**Issue by moham96** [flutter/flutter#146746]
### Use case

I'm developing an app that streams videos through  HLS, but due to how the videos are streamed (loaded from torrent) there is a wait between playing/seeking to position and actually playing the video, especially on slow connections, which makes events like  [loadedmetadata](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadedmetadata_event) and [stalled](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/stalled_event) very useful 

### Proposal

I'm proposing to expose some new events taken from html5 video element events like `stalled`, `loadedmetadata` and `loadeddata` , the newly provided APIs can take any form (callbacks or events).

[full list of html5 events](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement#events)

**Comment by stuartmorgan** [comment]
That's a long list, and some appear to correspond to things we already have. Could you provide a specific list of events that you want and aren't supported, and what the use cases for them are?

**Comment by moham96** [comment]
> That's a long list, and some appear to correspond to things we already have. Could you provide a specific list of events that you want and aren't supported, and what the use cases for them are?

Well, for me at least these events will be very useful:

- loadstart
- durationchange
- loadedmetadata
- loadeddata
- progress
- canplay
- canplaythrough
- stalled

and if i have to strip the list even further then i would prioritize:
- loadedmetadata
- stalled

**Comment by stuartmorgan** [comment]
Please provide detailed explanations of the use cases you are trying to address; without that it's not clear what functionality is being requested. For instance, the web implementation of `video_player` already listens to about half of the things on your list and uses them for the higher-level event stream the plugin already provides, so it's not clear what specifically you are trying to do that you can't currently do.
