### ISSUE TITLE
[image_picker] image_picker: ^1.0.7 image revert issue in IOS.

### ISSUE THREAD

**Issue by ItsArsalanAziz** [flutter/flutter#146752]
### Steps to reproduce

1. get the image from library/gallery or capture it from camera(only front camera)
2. select and show it
3. all images are inverted like a mirror in IOS devices only are inverted

### Expected results

The image must be the same as placed in the gallery or captured by camera using the front camera.

### Actual results

Images are inverted in IOS when choosing from library/gallery using ImagePicker().pickImage(ImageSource.gallery) or captured by camera using ImagePicker().pickImage(ImageSource.camera).

### Code sample
ImagePicker().pickImage(source:text == StringConstants.loadFromLibrary ? ImageSource.gallery : ImageSource.camera).then((value) async {
if (value != null) {
List imageBytes = File(value.path).readAsBytesSync();
String _base64Image = base64Encode(imageBytes);
}
}).onError((err, stackTrace) {
debugPrint(err.toString());
});

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
• Flutter version 3.16.7 on channel stable at D:\dev\projects\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/ef1af02aead6fe2414f3aafa5a61087b610e1332 (3 months ago), 2024-01-11 15:19:26 -0600
• Engine revision 4a585b7929
• Dart version 3.2.4
• DevTools version 2.28.5

Note: the bug is only generating in case of front camera images that are placed in gallery or captured from camera.

**Comment by danagbemava-nc** [comment]
Please do not file multiple issues for the same bug. 

Closing this in favor of https://github.com/flutter/flutter/issues/146751
