### ISSUE TITLE
How to use the model attribute in pubspec.yaml

### ISSUE THREAD

**Issue by LanSeLianMa** [flutter/flutter#146713]
Please tell me how to use the model attribute in pubspec.yaml. Is there any relevant documentation? I want to develop into modules. I don’t know about this model attribute. Can you provide help?

<img width="727" alt="截屏2024-04-13 13 47 42" src="https://github.com/flutter/flutter/assets/45938601/cd82401a-61cc-42fa-bb0f-267cacb3eab7">

**Comment by LanSeLianMa** [comment]
This document also does not introduce the model attribute.

https://dart.dev/tools/pub/pubspec

**Comment by AbdeMohlbi** [comment]
@LanSeLianMa 
where did do u find this model attribute when creating a new flutter project it is missing and it's true that it is missing from the internet also no one knows about it beacuse when searching ur issue appeared as the first search result

**Comment by LanSeLianMa** [comment]
What I discovered by accident was that I was curious about this module attribute and how to use it.

https://github.com/flutter/samples/blob/main/add_to_app/android_view/flutter_module_using_plugin/pubspec.yaml

**Comment by AbdeMohlbi** [comment]
i see ,it looks like it has something to do with module packaging

**Comment by AbdeMohlbi** [comment]
@LanSeLianMa 
after some reasearch here is what i've found i hope it helps:
```This section in the pubspec.yaml file of a Flutter project is used to define the configuration for embedding your Flutter project as a module within a native host app. Here's what each field means:

androidX: This boolean field indicates whether your Flutter project uses AndroidX libraries. AndroidX is the new package structure introduced by Google to make it easier to include new features and maintain compatibility across different versions of Android. Set this to true if your project is using AndroidX, and false if not.

androidPackage: This field specifies the package name for the Android side of your Flutter module. It follows the typical Java package naming convention in reverse domain notation. For example, dev.flutter.example.flutter_module_using_plugin.

iosBundleIdentifier: Similar to the androidPackage, this field specifies the bundle identifier for the iOS side of your Flutter module. It's typically in reverse domain notation, but without the additional package structure levels. For example, dev.flutter.example.flutterModuleUsingPlugin.

These identifiers are important for maintaining consistency and compatibility when adding or modifying assets and plugins within your Flutter project. They ensure that the tooling can correctly integrate your Flutter module into the native host application. However, note that these identifiers don't have any direct impact on the identifiers of your native host application itself, which may have independent or different identifiers.```

**Comment by LanSeLianMa** [comment]
Can Flutter be developed in modules, and each module can run independently, just like Android’s native module development method?

**Comment by AbdeMohlbi** [comment]
u mean smth like packages that already exist ?

**Comment by LanSeLianMa** [comment]
Yes, want them to have reference dependencies

<img width="437" alt="截屏2024-04-14 00 20 51" src="https://github.com/flutter/flutter/assets/45938601/a866f394-8072-49fe-a2aa-8a1861d95b40">

**Comment by LanSeLianMa** [comment]
Thanks, I really need relevant reference examples.

**Comment by AbdeMohlbi** [comment]
@LanSeLianMa 
sorry for taking so much time
run:`flutter create modular_flutter_app`
run:`mkdir product_catalog &&  mkdir shopping_cart`
run :`cd product_catalog
flutter create --template=package .
cd ../shopping_cart
flutter create --template=package .
`
 pubspec.yaml file section :
```
dependencies:
  flutter:
    sdk: flutter
  product_catalog:
    path: ./product_catalog
  shopping_cart:
    path: ./shopping_cart
```
flutter code : 
```dart
import 'package:flutter/material.dart';
import 'package:product_catalog/catalog_screen.dart';
import 'package:shopping_cart/cart_screen.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Modular Flutter App'),
        ),
        body: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => CatalogScreen()),
                );
              },
              child: Text('Open Product Catalog'),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => CartScreen()),
                );
              },
              child: Text('Open Shopping Cart'),
            ),
          ],
        ),
      ),
    );
  }
}
```
 CatalogScreen and CartScreen are inside this two packages (i don't know where are the exact files currently tbh )
(u can define logic to communicate with native api for exemple i have recently run into perfmonace issue when trying to parse a large json file so i decided to use go for this and reduce the loading time .)
for more info hit : [flutter docs about that](https://docs.flutter.dev/packages-and-plugins/developing-packages)
i hope this help

**Comment by LanSeLianMa** [comment]
Thanks, I'll try it

**Comment by AbdeMohlbi** [comment]
> Yes, want them to have reference dependencies
> 
> <img alt="截屏2024-04-14 00 20 51" width="437" src="https://private-user-images.githubusercontent.com/45938601/322218174-a866f394-8072-49fe-a2aa-8a1861d95b40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjU2NjAsIm5iZiI6MTcxMzAyNTM2MCwicGF0aCI6Ii80NTkzODYwMS8zMjIyMTgxNzQtYTg2NmYzOTQtODA3Mi00OWZlLWEyYWEtOGExODYxZDk1YjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE2MjI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNGVmYjI2ZjczYzJiYjA2Yjc4MWIwMTZiNWM0YjUxMjhmNmE0MzcwM2JlY2Y0MjZiZjZmYThjNWM5M2Q4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dKv7mviL-_nbn1FUC09CBHSsA_RplPEuJRiw1U7A3Fk">

i think u have to think in a differnt way bacause this appraoch is not for flutter projects u must use packages to devide the work into sections and treat each section alone ,smth like : home component , models component .. each component  will be inside a package (if ur project is that big to make sepearte components ) and models component that will contain all components .. 
note that the code given is the max simple so it's just to understand the idea only

**Comment by darshankawar** [comment]
@LanSeLianMa 
I think it is better to ask about it in flutter's discord help channel. 
I'll close it from here as this is more of a `how to` question with support comments thread instead of a bug report of feature request. If you disagree, write in comments and I'll reopen it.
