### ISSUE TITLE
packages/google_sign_in_web

### ISSUE THREAD

**Issue by AndreVicencio** [flutter/flutter#146731]
<img width="864" alt="image" src="https://github.com/flutter/flutter/assets/93562366/c82626e4-7c32-4d15-8d9f-9e15db2308a2">
The example usage is unrelated to google_sign_in_web. 

New to the package, and there's no way right now for me to find an example on how to use it.

**Comment by bartekpacia** [comment]
Refer to README of [`google_sign_in`](https://pub.dev/packages/google_sign_in) instead. `google_sign_in_web`, [`google_sign_in_android`](https://pub.dev/packages/google_sign_in_android) etc. are not meant for public use (according to my knowledge).

**Comment by opxdelwin** [comment]
Test example is available in other file in the repo, [button_tester.dart](https://github.com/flutter/packages/blob/main/packages/google_sign_in/google_sign_in_web/example/lib/button_tester.dart) . I wonder why the package is unlisted... Is it being worked on?

**Comment by huycozy** [comment]
@AndreVicencio As @bartekpacia mentioned above, you can use google_sign_in [example](https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in/example/) instead.  Let's check to see if it meets your expectation.

>I wonder why the package is unlisted

@opxdelwin I'm not sure if it's the state before or just updated recently, but it's just a configuration on the package's Admin page.
