### ISSUE TITLE
[CP] [canvaskit] Fall back to multi-context rendering on Firefox and Safari

### ISSUE THREAD

**Issue by harryterkelsen** [flutter/flutter#146787]
### Issue Link

https://github.com/flutter/flutter/issues/145563

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/52141

### Changelog Description

Performance regression in CanvasKit on Firefox and Safari

### Impacted Users

Flutter Web users

### Impact Description

Severe fps drop on Firefox and Safari

### Workaround

Use the HTML renderer (not recommended due to lack of feature support)

### Risk

low

### Test Coverage

yes

### Validation Steps

Run an app in Firefox and verify that there is no significant jank

**Comment by yjbanov** [comment]
LGTM!

**Comment by yjbanov** [comment]
Oh, this is not a PR. Carry on then!
