### ISSUE TITLE
App is not working in Android version 14 

### ISSUE THREAD

**Issue by webaddicted** [flutter/flutter#146769]
### Steps to reproduce

When i setup click photo then camera screen is open after clicking on capture button nothing happend on my android 14 version device.
Also i am not able to back from camera screen. camera screen not allow to go back on previous screen

### Expected results

on Android 14 devices we can open camera and capture image.

### Actual results

When i setup click photo then camera screen is open after clicking on capture button nothing happend on my android 14 version device.
Also i am not able to back from camera screen. camera screen not allow to go back on previous screen

### Code sample

<details open><summary>Code sample</summary>

```dart
  try {
    var image = await ImagePicker.platform
        .pickImage(source: imageType);
 } catch (error) {
    print("error11111: $error");
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
D/BLASTBufferQueue(28224): [SurfaceView[com.microprixs.parkvuevender/com.microprixs.parkvuevender.MainActivity]#1](f:0,a:1) destructor()
D/BufferQueueConsumer(28224): [SurfaceView[com.microprixs.parkvuevender/com.microprixs.parkvuevender.MainActivity]#1(BLAST Consumer)1](id:6e4000000001,api:0,p:-1,c:28224) disconnect
D/BLASTBufferQueue(28224): [VRI[MainActivity]#0](f:0,a:1) destructor()
D/BufferQueueConsumer(28224): [VRI[MainActivity]#0(BLAST Consumer)0](id:6e4000000000,api:0,p:-1,c:28224) disconnect


Phenotype API error. Event: # fgou@4b23fb6b, EventCode: COMMIT_CONFIG [CONTEXT service_id=51 ]
                                                                                                    csuj: 29501: Stale snapshot for com.google.android.libraries.performance.primes#com.google.android.googlequicksearchbox(change count changed - expected 36  but was 35)
                                                                                                    	at cswh.b(:com.google.android.gms@241017038@24.10.17 (190400-617915183):1660)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
mac@MACs-iMac parkvuepartner % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @webaddicted, what device(s) are you seeing this issue on? 

What version of `image_picker` & `image_picker_android` are you using? 

I tested the plugin example app on my Pixel 7 running android 14 and it works as expected. See the recording below

Can you try the plugin example app to see if it works for you?

https://github.com/flutter/flutter/assets/88313112/78654726-16ed-4159-82b5-0387e9e5875f

**Comment by webaddicted** [comment]
Hi @danagbemava-nc I have Vivo T2x 5G phone and I am using image_picker: ^1.1.0. and i am not using image_picker_android in my project.
It is mandatory to use image_picker_android in our project with image_picker:^1.1.0
Please. check video app is stuck after click on capture

I am write only one line of code in take photo that is
var image = await ImagePicker.platform
        .pickImage(source: imageType);

I also try
var image = await ImagePicker().pickImage(source: imageType, preferredCameraDevice: CameraDevice.rear);

but same behavior for both.

1) Is it mandatory to add image_picker & image_picker_android both plugin in project?
2) If yes, then what we have to do in case of web and iOS ?

If you have any github sample code please share 

PFA video
https://github.com/flutter/flutter/assets/38448422/19dedf22-6848-4c3f-b515-73c980cb1861

**Comment by danagbemava-nc** [comment]
> Is it mandatory to add image_picker & image_picker_android both plugin in project?

`image_picker_android` is a dependency of `image_picker`, it is added to your project automatically when you add `image_picker`. You can find the version in your `pubspec.lock` or by running `flutter pub deps `


Are you only getting this behaviour on the `Vivo T2x` phone? 

Please also share the full output of `flutter run -v` if you see any errors when you try to capture the image with the camera. 

Also, can you share the content of your `AndroidManifest.xml`? Please anonymise all sensitive data before you share the content of the file.

**Comment by webaddicted** [comment]
I don't have any other device and try to test same build on my friend device redme he is also facing crash on his device.

All Other question answer is available in video
So please go through video please resolve this asap.


https://github.com/flutter/flutter/assets/38448422/a6864e7b-a550-4a43-9dcd-60e16676e506

**Comment by danagbemava-nc** [comment]
Please share the content requested in text format instead of a video. 

Thank you

**Comment by webaddicted** [comment]
@danagbemava-nc  Please check all screeshot.

<img width="1369" alt="Screenshot 2024-04-19 at 11 22 10 PM" src="https://github.com/flutter/flutter/assets/38448422/5a3b9342-fea2-45e6-af3e-52a98dd06912">
I 
<img width="1369" alt="Screenshot 2024-04-19 at 11 23 04 PM" src="https://github.com/flutter/flutter/assets/38448422/5f63e89e-06cb-474b-aea4-ffa3792d3e21">
<img width="1369" alt="Screenshot 2024-04-19 at 11 23 33 PM" src="https://github.com/flutter/flutter/assets/38448422/5596b349-61a2-446f-99ec-fd602a7ba322">
<img width="1369" alt="Screenshot 2024-04-19 at 11 24 10 PM" src="https://github.com/flutter/flutter/assets/38448422/036d2209-6fc4-4b7a-bde1-9f59fb35581c">
<img width="1637" alt="Screenshot 2024-04-19 at 11 38 33 PM" src="https://github.com/flutter/flutter/assets/38448422/34944f19-d51c-4b8a-8033-0844330ac759">
<img width="1637" alt="Screenshot 2024-04-19 at 11 43 33 PM" src="https://github.com/flutter/flutter/assets/38448422/64a8524d-f957-4a70-a1a5-43346e15a531">
<img width="1637" alt="Screenshot 2024-04-19 at 11 43 46 PM" src="https://github.com/flutter/flutter/assets/38448422/731321b7-678d-4af6-9c03-d44382f0e7d3">


<img width="1369" alt="Screenshot 2024-04-19 at 11 21 50 PM" src="https://github.com/flutter/flutter/assets/38448422/97bb29d3-76bd-4c8c-bbf8-f168a6142bf5">

**Comment by danagbemava-nc** [comment]
Hi @webaddicted, is there any reason why you're using `ImagePicker.platform.pickImage` instead of `ImagePicker().pickImage`? 

Also, if you set `android:enableOnBackInvokedCallback` to false, do you still have this issue? 

PS: In the future, do not share screenshots of text blocks. Please provide the text in plain text. Screenshots are not searchable and they make it difficult to find references to similar issues. 

Thank you

**Comment by webaddicted** [comment]
Hi @danagbemava-nc  you you see in screenshot i tried multiplay way at my end. *Marta Kya nahi Karta* thats why I tried ImagePicker.platform.pickImage and  ImagePicker().pickImage? way.

I already tried by removing android:enableOnBackInvokedCallback this.
But this is also not help me.
Please let me know anything else you need from my end.

**Comment by danagbemava-nc** [comment]
Hi @webaddicted, please provide a complete minimal reproducible code sample in a repo that we can clone so that we can properly investigate this. 

Thank you
