### ISSUE TITLE
i have an error when i run flutter doctor 

### ISSUE THREAD

**Issue by dandash** [flutter/flutter#146783]
### Steps to reproduce

when i run flutter doctor in the first time after installation i got this error
![Screenshot 2024-04-15 232519](https://github.com/flutter/flutter/assets/6941447/995fdf06-4865-4d34-9ea2-cddd99d3fef4)

### Actual results

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Connected device exceeded maximum allowed duration of 0:04:30.000000

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Connected device exceeded maximum allowed duration of 0:04:30.000000

**Comment by darshankawar** [comment]
@dandash 
Based on the error, it seems similar to https://github.com/flutter/flutter/issues/125488 so please follow-up in it for further updates. 
Closing as duplicate.
