### ISSUE TITLE
flutter_markdown weird image behavior

### ISSUE THREAD

**Issue by WossomGonzo** [flutter/flutter#146874]
### Steps to reproduce

Create a simple flutter app and add a `MarkdownBody` in it. In the data add some data, then an image, then some more data.

You will see that the text after the image will move at the next line.

### Expected results

Hello world [image]
Hello world [image] Hello world Hello world Hello world Hello world Hello world Hello world

### Actual results

![Screenshot_1713345715](https://github.com/flutter/flutter/assets/87129717/3bc09148-e6b4-48b4-be99-5db5e70197b7)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _incrementCounter() {
  }

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            MarkdownBody(
              data: "Hello world ![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/BuckNicks.PNG/167px-BuckNicks.PNG#20x20) Hello world"),
            MarkdownBody(
              data: "Hello world ![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/BuckNicks.PNG/167px-BuckNicks.PNG#20x20) Hello world Hello world Hello world Hello world Hello world Hello world Hello world Hello world"),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@WossomGonzo 
Can you try something like below and check if it helps to align the text properly ?

```
styleSheet:
      MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
    textAlign: WrapAlignment.center,
  ),
```

**Comment by WossomGonzo** [comment]
I checked and nope. It is centered, but still the text is below the image. Did you try it and worked?

> @WossomGonzo Can you try something like below and check if it helps to align the text properly ?
> 
> ```
> styleSheet:
>       MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
>     textAlign: WrapAlignment.center,
>   ),
> ```

**Comment by darshankawar** [comment]
> Did you try it and worked?

Thanks for checking. No, it was same result as you shared, but I think it. should be doable with little more exploration. Can you take a look at [this](https://github.com/flutter/flutter/issues/123195) and see if it helps further in your case or not ?

**Comment by WossomGonzo** [comment]
> > Did you try it and worked?
> 
> Thanks for checking. No, it was same result as you shared, but I think it. should be doable with little more exploration. Can you take a look at [this](https://github.com/flutter/flutter/issues/123195) and see if it helps further in your case or not ?

I followed the instructions and it does work! I have created an `ImageBuilder` with a `RichText` and the result is an inline image! 

Thanks.

Is this still an issue, right?

**Comment by WossomGonzo** [comment]
> Good to know it helped you to resolve your case.
> 
> > Is this still an issue, right?
> 
> Most likely, but seems we can club it with #123195. Since your original issue seem to be resolved, is it ok to close this and you can follow-up in the linked issue for further updates ?

Yes! please go ahead and close this ticket.

Thanks!
