### ISSUE TITLE
Text: Enable making only specific parts of text selectable

### ISSUE THREAD

**Issue by delthas** [flutter/flutter#146850]
### Use case

I am writing an IRC app in Flutter. Each message is formatted like:

> **myusername** i truly enjoy eating cheese. camembert is
> one of my favorites. *[20:32:00]*

I'd like to make it easier for users to select just the message part (making the username and date parts not selectable). I can't just have several Text and have one of them be selectable and the other disabled, like in the doc example https://api.flutter.dev/flutter/widgets/Text-class.html , because the different text elements have to be part of the same paragraph (so neither a row or column works, this really has to be part of the same Text.rich).

### Proposal

The equivalent on the Web would be this:

![Taskmgr_2024-04-17_00-08-44](https://github.com/flutter/flutter/assets/1863865/0d65f2b4-fea9-4721-9764-e2cb7f865cf8)

https://codepen.io/f05221da/pen/ExJeded (just styling the `Not Selectable` spans with `user-select: none`).

A new field in TextStyle, or TextSpan, or a new InlineSpan subclass that would wrap a child InlineSpan and disable selection in its subtree would all work for me.

Right now I see no way of doing this, either through SelectableText (what I'm using at the moment) or Text.rich + SelectionArea.

**Comment by Renzo-Olivares** [comment]
Hi @delthas, thanks for reporting this issue. This behavior should be possible in a single `Text.rich` with `WidgetSpan`s and using `SelectionContainer.disabled` see the sample code below. 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const SelectionContainerDisabledExampleApp());

class SelectionContainerDisabledExampleApp extends StatelessWidget {
  const SelectionContainerDisabledExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('SelectionContainer.disabled Sample')),
        body: const Center(
          child: SelectionArea(
            child: Text.rich(
              TextSpan(
                children: <InlineSpan>[
                  WidgetSpan(
                    child: SelectionContainer.disabled(
                      child: Text('Not selectable'),
                    ),
                  ),
                  TextSpan(text: ' selectable'),
                  TextSpan(text: ' also selectable'),
                  WidgetSpan(
                    child: SelectionContainer.disabled(
                      child: Text('Not selectable'),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by delthas** [comment]
Very nice! I didn't know about WidgetSpan.

Tested your solution on my end, it's working like a charm. Thanks!
