### ISSUE TITLE
[local_auth] Cannot attempt biometric after only registered with facial recognition for Huawei device

### ISSUE THREAD

**Issue by tommylung** [flutter/flutter#146866]
### Steps to reproduce

1. Huawei device only registered with Face Recognition biometric authentication method.
2. Using the `local_auth` package and call the function
   ``` dart
   LocalAuthentication().getAvailableBiometrics();
   ```
3. The result returned `[]`.
4. Attempt biometric authentication.
   ``` dart
   isAuthenticated = await auth.authenticate(
      localizedReason:
          'Scan your fingerprint (or face or whatever) to authenticate',
      options: const AuthenticationOptions(
        stickyAuth: true,
        biometricOnly: true,
      ),
    );
   ```
5. "Biometric required" dialog showed.
   <img src="https://github.com/flutter/flutter/assets/14847957/0eb8eedf-5478-45ff-84cb-11b0c5767296" alt="Screenshot_20240417_152205" width="200"/>

It works with Android device but not for the Huawei Device.
It works with registered Fingerprint ID.

Huawei Device information:
- model: FOA-AL00
- version: HarmonyOS 4.0.0
- build: .apk

### Expected results

After calling `LocalAuthentication().getAvailableBiometrics()`, it will return not `[]`.
After calling `auth.authenticate()`, the package will trigger the Face Recognition with Huawei device.

### Actual results

Returned `[]` after calling `LocalAuthentication().getAvailableBiometrics()`.
Cannot attempt face recognition and showed "Biometric required" dialog after calling `auth.authenticate()`.

### Code sample

<details open><summary>Code sample to get available biometrics</summary>

```dart
LocalAuthentication().getAvailableBiometrics();
```

</details>

<details open><summary>Code sample to attempt biometric authentication</summary>

```dart
isAuthenticated = await auth.authenticate(
  localizedReason:
      'Scan your fingerprint (or face or whatever) to authenticate',
  options: const AuthenticationOptions(
    stickyAuth: true,
    biometricOnly: true,
  ),
);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img src="https://github.com/flutter/flutter/assets/14847957/0eb8eedf-5478-45ff-84cb-11b0c5767296" alt="Screenshot_20240417_152205" width="200"/>

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4 23E214 darwin-arm64, locale en-GB)
    • Flutter version 3.19.5 on channel stable at /Users/<user>/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/<user>/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2023.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • FOA AL00 (mobile)       • <serial number>          • android-arm64 • Android 12 (API 31)
    • iPhone (mobile) • <serial number> • ios           • iOS 17.4.1 21E236
    • iPhone (mobile)    • <serial number> • ios           • iOS 17.4.1 21E236

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @tommylung 
I don't have a Huawei device to check this but I notice the message on the dialog from your screenshot. Could you confirm `face recognition` has been added in device's Setting?

Also, which `local_auth` package version are you using?

**Comment by tommylung** [comment]
Hi @huycozy ,
Thanks for your reply.

I confirmed the Face Recognition has been added in the device's settings.
<img src="https://github.com/flutter/flutter/assets/14847957/44c2700b-75b5-43ee-b85a-1b8ae4bbe07e" alt="Screenshot_20240417_180020" width="200"/>

I'm using the latest version (v2.2.0 ) of `local_auth` package.

**Comment by tommylung** [comment]
This is a table for Huawei device situation for attempt biometric.
| Only Fingerprint ID registered | Only Face Recognition registered | Both of Fingerprint ID and Face Recognition registered  | 
|---|---|---|
| :white_check_mark: Success | :x: Failed | :white_check_mark: Success |

**Comment by stuartmorgan** [comment]
This is a known issue with certain devices; it's tracked in https://github.com/flutter/flutter/issues/117309
