### ISSUE TITLE
[in_app_purchase] queryProductDetails returns empty product list

### ISSUE THREAD

**Issue by ChurikiTenna** [flutter/flutter#146875]
### Steps to reproduce

I created multiple base plans, and tried to get the items with `queryProductDetails`.
However, it returns empty list, and no errors.

```
var ids = ['old','mimamori-public','mimamori-hidden']
debugPrint("queryProductDetails from ${ids}");
    final productDetailResponse =
        await InAppPurchase.instance.queryProductDetails(ids.toSet());
    debugPrint("productDetails ${productDetailResponse.productDetails.length}");
    debugPrint("pdr.error ${productDetailResponse.error}");
```

I've tried with 'com.appname.mimamori', 'com.appname.mimamori.old' and such, but nothing worked. (Actually have no idea which one should supposed to be the identifiers, item id? or id for the base plan?)

I have products in google play console as below.
<img width="554" alt="スクリーンショット 2024-04-17 18 20 46" src="https://github.com/flutter/flutter/assets/52132649/475bcb8e-2b4b-4e0a-a2c3-b6140baf8a47">

Also, updated appbundle to google play console, and published open test version yesterday.

What else should I do??

### Expected results

Return 3 base plans.

### Actual results

I/flutter (12677): queryProductDetails from (old, mimamori-public, mimamori-hidden)
I/flutter (12677): productDetails 0
I/flutter (12677): pdr.error null

### Code sample

<details open><summary>Code sample</summary>

```dart
var ids = ['old','mimamori-public','mimamori-hidden']
debugPrint("queryProductDetails from ${ids}");
    final productDetailResponse =
        await InAppPurchase.instance.queryProductDetails(ids.toSet());
    debugPrint("productDetails ${productDetailResponse.productDetails.length}");
    debugPrint("pdr.error ${productDetailResponse.error}");
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/flutter (12677): queryProductDetails from (old, mimamori-public, mimamori-hidden)
I/flutter (12677): productDetails 0
I/flutter (12677): pdr.error null
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
    • Flutter version 3.19.2 on channel stable at /Users/tenna/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (7 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tenna/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (6 available)
    • SCG08 (mobile)            • RFCR71VND0N                              • android-arm64  • Android 13 (API 33)
    • Tenna’s iPhone11 (mobile) • 00008030-0012304A01D3402E                • ios            • iOS 17.4.1 21E236
    • tenna’s iphone15 (mobile) • 00008120-00120DDA1E10A01E                • ios            • iOS 17.4.1 21E236
    • Tenna’s iPad (mobile)     • d1802c9bcfe7b9b836383ca90361f9c15180f21e • ios            • iOS 17.4.1 21E236
    • macOS (desktop)           • macos                                    • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 123.0.6312.124
    ! Error: Browsing on the local area network for Tenna’s iPad (2). Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @ChurikiTenna 
Which target platform are you seeing the issue? I checked this again with my own setup but couldn't see the issue, all products (subscriptions & in-app products) are counted correctly. 

Could you try with [package example](https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example) to see if the issue persists? If it does, maybe the issue belongs to your test account (Gmail) on your test device. Please make sure it has been added to tester list on the console dashboard.

**Comment by ChurikiTenna** [comment]
Thank you for the quick reply @huycozy !

I am testing with Android (Galaxy A32). 
It works fine with iOS.

My gmail account is added as a tester.

Additional note: queryProductDetails  was working fine with the old subscription plan (I have now disabled, because I wanted change the subscription duration). After I added new base plans, queryProductDetails stopped working.

I tried to test the example project, but I got this error.

![Screenshot_20240417_194128_Google Play Store](https://github.com/flutter/flutter/assets/52132649/ed1a74ad-6f05-4401-afbb-c23e8fa59dbc)

**Comment by huycozy** [comment]
Could you share the kind of those products above? Are they subscriptions or in-app products?

>I tried to test the example project, but I got this error.

It seems to be just a warning of Google Play Protect for app having a low targetSdkVersion, you can ignore it since it's not related to this issue here. You may continue by tapping on `More details`.
