### ISSUE TITLE
Sample code for AppBar.actions not formatted correctly

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#14687]
## Steps to Reproduce

Go to https://docs.flutter.io/flutter/material/AppBar/actions.html

The sample code doesn't have the correct indentations (see the screenshot below):

![image](https://user-images.githubusercontent.com/348942/36183673-383fdbbe-10e4-11e8-9ffe-40b0b6ecee10.png)

In addition, it would be helpful to have a "Sample code" header above the code to match the "Implementation" header below.

**Comment by Hixie** [comment]
cc @jcollins-g

**Comment by jonahwilliams** [comment]
This appears to be fixed (see https://docs.flutter.io/flutter/material/AppBar/actions.html) can it be closed?

**Comment by InMatrix** [comment]
Sure. Closed!
