### ISSUE TITLE
[macOS] Assertion and crash with magic mouse

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#146893]
```
[FATAL:flutter/lib/ui/window/pointer_data_packet_converter.cc(249)] Check failed: state.is_pan_zoom_active. 
./packages/superlist/run.sh: line 91: 85179 Abort trap: 6           $TARGET_DIR/Superlist.app/Contents/MacOS/superlist
```

Steps to reproduce:
1. Start scrolling with magic mouse
2. While holding the finger on the mouse switch between windows (cmd + tab)
3. Release mouse from mouse

Possibly related to https://github.com/flutter/engine/pull/49424

**Comment by knopp** [comment]
I think the assertion was there for debugging purposes, but I think engine is compiled with assertions in Release mode (I don't see `NS_BLOCK_ASSERTIONS` being defined anywhere). @cbracken, @moffatman 

Also there is another issue where scrolling with magic mouse sometimes just gets stuck, I'm still figuring out what's going on.

**Comment by moffatman** [comment]
Are you on master engine with my change above?
The assertion shows a problem in the state machine. It shouldn't be ignored. But the framework will correct for it by synthesizing the proper panzoomstart event. I thought assertions were intended to be only on in debug mode.

**Comment by knopp** [comment]
Yes, this is on current master. 

> I thought assertions were intended to be only on in debug mode.

That'd be reasonable assumptions, except `NSAssert` seems to be opt-out, and needs `NS_BLOCK_ASSERTIONS` defined which doesn't seem to be the case during release engine build.

**Comment by knopp** [comment]
@moffatman, there is also an assumption in framework that a single pointer `PointerPanZoomUpdateEvent` should always be delivered to same hit test target, but with magic mouse you can move the cursor between scroll views while fingers is on the mouse (same pointer).

**Comment by knopp** [comment]
@moffatman what happens here is that with magic mouse, while the scroll wheel event is active, there is a `MouseExited` event which triggers call to `GestureReset()`. After that when scroll wheel event ends the assertion is triggered because `GestureRest()` did set `flutter_state_is_pan_zoom_started` to false.

With magic mouse, unlike the trackpad, the scroll events and movement events are independent and the state machine should probably reflect that.

**Comment by knopp** [comment]
Can you think of any potential side effects of not calling `GestureReset` from `Reset()`?

**Comment by moffatman** [comment]
Good catch, I agree with the solution, I don't think there will be any side effect
