### ISSUE TITLE
Flutter release candidate branch postsubmit tasks not updating in dashboard

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#146839]
### Type of Request

bug

### Infrastructure Environment

Cocoon scheduler, Firestore/Datastore

### What is happening?

Tasks for the commit '40f3a79429d8e48c67b7e209b0705956d2380404' are not being updated in the dashboard. It appears that the commit and the tasks were not saved correctly in the datastore and cocoon is unable to update them.

Here is one example:
![image](https://github.com/flutter/flutter/assets/32242716/2eff6279-654c-4237-9d1a-36df731f1215)

### Steps to reproduce

NA

### Expected results

I expect to see the tasks updated successfully in the dashboard.

**Comment by keyonghan** [comment]
A new cocoon version was pushed. It caused errors when writing data to Firestore. 
https://github.com/flutter/cocoon/pull/3635/files#diff-bb6959c7655c2a5b97a3f09154743dd42d0c9167cb7643bbe51fbeffca9a96e6R268 is the culprit.

Traffics have been switched to an earlier version, and hanging tasks have been reovered.
