### ISSUE TITLE
Impeller rendering engine causing rendering issues on iOS simulators

### ISSUE THREAD

**Issue by savvaschar** [flutter/flutter#146883]
### Steps to reproduce

I have a rather large flutter app so I cannot provide a step by step guide. Hence, I created a new project using "flutter create bug" and simply pressed the button to increase the counter in the sample app. My setup is on a MacBook Pro (macOS Sonoma Version 14.4.1 (23E224)), flutter version 3.86.0 and dart version 3.86.0.

My issue, as you can see from the attached video, is solely with iPhone/iPad simulators where strange artefacts (different coloured shapes that distort the UI) appear as soon as I start using the app. In my personal app the issue happens more evidently and the more I navigate around and the app starts loading and fetching data the more intense these artefacts get until the app becomes completely unresponsive and the UI goes black. At this point I have to kill the app from VS Code or Xcode (depends on from where I build it each time, I tried both ways and form the terminal). For the bug app, the issue is still evident but not as much.

For my app, I tested on at least these simulators: iPhone 15 Pro Max & iPhone 15 Pro with iOS 17.4 and iOS 17.2, iPhone 15 iOS 17.2, iPhone 14 Pro iOS 16.4, iPad Pro 6th generation iOS 17.4 and all of them exhibit this issue.

However, if run the app as follows the issue disappears: flutter run --no-enable-impeller

### Expected results

Both my app and the bug sample app should run smoothly on iOS simulators without any artefacts showing up in the UI.

### Actual results

As shown in the attached video artefacts show up in the UI, and for my case in my own app the issue is a lot worse the more I navigate and finally the app becomes unresponsive.

### Code sample

<details open><summary>Code sample</summary>
I ran the following command and simply pressed the button several times. Although for my app since its more complex the distortion happens a lot more and finally the app becomes unresponsive.
```
flutter create bug
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

https://github.com/flutter/flutter/assets/13361878/6a2629e5-119c-4123-b3a8-0ad2945f5c55

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.21.0-1.0.pre.2, on macOS 14.4.1 23E224 darwin-x64, locale en-CY)
    • Flutter version 3.21.0-1.0.pre.2 on channel beta at /User/***/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c398442c35 (5 weeks ago), 2024-03-12 22:26:24 -0700
    • Engine revision 0d4f78c952
    • Dart version 3.4.0 (build 3.4.0-190.1.beta)
    • DevTools version 2.33.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/***/Library/Android/sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • iPad Pro (12.9-inch) (6th generation) (mobile) • 19C44241-CCF7-4226-AA74-1838581FCAAF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                                • macos                                • darwin-x64     • macOS 14.4.1 23E224 darwin-x64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 124.0.6367.61
    ! Error: Browsing on the local area network for *** iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac. The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

**Comment by darshankawar** [comment]
> ```
> Channel beta, 3.21.0-1.0.pre.2
> ```

@savvaschar You are on not latest beta. Please try by upgrading this version to latest and run again, or by switching to latest master or stable to check if it persists or not. 
Also, is the behavior only occuring on ipad simulators or phone simulators / physical devices / ipads as well ?

**Comment by savvaschar** [comment]
@darshankawar thank you for pointing that out, I switched to stable channel and did a flutter upgrade, now everything works as intended!

My issue for the channel beta I was in happened for both iPhone and iPad simulators for iOS 17.4, 17.2 and 16.4.

**Comment by darshankawar** [comment]
> I switched to stable channel and did a flutter upgrade, now everything works as intended!

Thanks for confirming. Since it works on latest stable which is cut from latest beta version itself, I'll close this as resolved. If you upgrade your beta to latest and run your scenario again, it should also work as expected. 
If you disagree or see this issue on latest beta also, write in comments and I'll reopen it.
