### ISSUE TITLE
Add more Mac/pixel testbed to prod pool

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#146846]
Seems we have only one testbed: https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&f=device_type%3APixel%207%20Pro&f=os%3AMac&k=os&s=id

This breaks the tree when the bot is off, and we should add more capacity.

This caused framework tree red:
<img width="320" alt="Screenshot 2024-04-16 at 2 29 06 PM" src="https://github.com/flutter/flutter/assets/54558023/b8fac005-e74f-4121-a481-974641049706">
<img width="799" alt="Screenshot 2024-04-16 at 2 29 58 PM" src="https://github.com/flutter/flutter/assets/54558023/2bf84c40-ddec-4290-846a-99c5aae86709">

**Comment by yusuf-goog** [comment]
mac-22 has been moved and brought online. Tree is unblocked. Reducing priority. Will add additional testbeds of this combination to prod shortly.

**Comment by zanderso** [comment]
We no longer have any Mac/pixel tests.
