### ISSUE TITLE
After flutter is installed, first Hello World running on XCode simulator in 15 sec

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1468]
Assuming the developer has XCode downloaded, and their simulator turned on, the developer should be able to create the starter app and run it on their iOS simulator within 10 seconds.

**Comment by eseidelGoogle** [comment]
The steps for this are documented at https://flutter.io/getting-started/.  It's not clear which exactly we're testing for the 10s metric.

Presumably ```
flutter create my_app
cd my_app
flutter ios --init
open -a Simulator
flutter start
```

Correct?

**Comment by sethladd** [comment]
Yup! 10 seconds may not be achievable because there's a network download in the flow. The goal is to set a goal and measure it. Maybe it's 15 seconds for iOS.

**Comment by chinmaygarde** [comment]
Its currently at 17.5 seconds. https://gist.github.com/chinmaygarde/a732a31f86aeee91fdaa

Breakdown:
* 7 seconds for init + pub get
* 4 seconds for the download (on a super speedy connection admittedly)
* 4 seconds for a cold boot of the simulator
* Rest is `simctl` is doing its thing and the time to first frame from launch.

**Comment by eseidelGoogle** [comment]
Thank you for measuring @chinmaygarde!

**Comment by sethladd** [comment]
nice! Will bump to 15 sec.

**Comment by chinmaygarde** [comment]
May I close this issue?

**Comment by eseidelGoogle** [comment]
Current timing is 20-21s on my macbook pro.  Much of that is pub get. :(

https://gist.github.com/eseidelGoogle/86d7e966c921a94e45f2

**Comment by eseidelGoogle** [comment]
I notice that we download the XCodeProject.zip every time.  That seems silly, we treat it as an artifact and use flutter cache.  This would also allow users to work with flutter on a plane.

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/8937

**Comment by Hixie** [comment]
Our first-hello-world performance is gated by much more serious problems like "downloading xcode" so I don't think this is a metric we should particular worry about at this time.
