### ISSUE TITLE
Transition flutter frontend_server to use supported front_end api

### ISSUE THREAD

**Issue by aam** [flutter/flutter#14699]
https://github.com/flutter/engine/blob/master/frontend_server/lib/server.dart#L17
uses internal Dart front_end classes, it should be transitioned to use supported public api:

```
import 'package:front_end/src/api_prototype/compiler_options.dart';
import 'package:front_end/src/api_prototype/file_system.dart' show FileSystemEntity;
```

@peter-ahe-google

**Comment by Hixie** [comment]
@aam I assume this is still relevant?

**Comment by aam** [comment]
I think we can close this one since all code that relied on private imports was moved into dart sdk vm/frontend_server.dart.
