### ISSUE TITLE
connectToService() doesn't close the pipe when we have no embedder

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1469]
LocalServiceProvider's connectToService() (in mojo's application_connection.dart) closes the pipe if it can't provide the service. I assume from this that the semantics of connectToService should be to close the pipe on failure. However, Flutter's shell.dart's connectToService doesn't do anything to the proxy to put it in a failure state in the edge case of there being no shell and no embedder.

cc @zra.

**Comment by abarth** [comment]
connectToService isn't a thing anymore.
