### ISSUE TITLE
Hi all, there is an error when you want to get a photo from the gallery.

### ISSUE THREAD

**Issue by pavlod116** [flutter/flutter#146950]
### Steps to reproduce

When I wrote the full code it works, but it writes an error that the plugin itself did not connect to the project, but when I added the keys to Info.plist all fixed.

### Expected results

Write what you need to add rights to Info.plist 

<key>NSCameraUsageDescription</key>
    <string>Для сделать фото и видео</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Для выбора изображений из галереи</string>

### Actual results

<key>NSCameraUsageDescription</key>
    <string>Для сделать фото и видео</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Для выбора изображений из галереи</string>

### Code sample

<details open><summary>Code sample</summary>

```dart
<key>NSCameraUsageDescription</key>
    <string>Для сделать фото и видео</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>Для выбора изображений из галереи</string>
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by moffatman** [comment]
So what do you want flutter to change?

**Comment by danagbemava-nc** [comment]
The developer is responsible for making sure their project has the required permissions for the app to function properly. 

You should make sure you check the documentation of any plugins you use to see if any special permissions are required for using it. 

Closing as there isn't anything for us to do here.

Thank you
