### ISSUE TITLE
[file_selector] Add Swift Package Manager compatibility to file_selector_ios and file_selector_macos

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#146903]
Prerequisites:
- [x] https://github.com/flutter/flutter/pull/146256
- [x] https://github.com/flutter/flutter/issues/146901

---

Follow ["Converting an existing Objective-C Flutter Plugin to a Swift Package" instructions](https://github.com/flutter/flutter/pull/146256#issuecomment-2038565077) to make `file_selector_ios` plugin compatible with Swift Package Manager and CocoaPods.

To validate all is working, run the following commands
```bash
// Disable swift package manager
flutter config --no-enable-swift-package-manager

// Build example with CocoaPods
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --ios --packages=file_selector_ios

// Build example with swift package manager
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --ios --swift-package-manager --packages=file_selector_ios

// Run native tests
dart run script/tool/bin/flutter_plugin_tools.dart native-test --ios --packages=file_selector_ios
```

Follow ["Converting an existing Swift Flutter Plugin to a Swift Package" instructions](https://github.com/flutter/flutter/pull/146256#issuecomment-2038565077) to make `file_selector_macos` plugin compatible with Swift Package Manager and CocoaPods.

To validate all is working, run the following commands
```bash
// Disable swift package manager
flutter config --no-enable-swift-package-manager

// Build example with CocoaPods
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --macos --packages=file_selector_macos

// Build example with swift package manager
dart run script/tool/bin/flutter_plugin_tools.dart build-examples --macos --swift-package-manager --packages=file_selector_macos

// Run native tests
dart run script/tool/bin/flutter_plugin_tools.dart native-test --macos --packages=file_selector_macos
```

**Comment by stuartmorgan** [comment]
iOS support was reverted in https://github.com/flutter/packages/pull/6740
