### ISSUE TITLE
unwanted ellipsis for action bar title in Persian

### ISSUE THREAD

**Issue by mneckoee** [flutter/flutter#14695]
Hi, thanks for awsome Flutter.
I set the title of scaffold actionbar to a Persian word and get an unwanted ellipsis, I don't want title to get ellipsised . 
I set this : 'لغت نامه' 
but get this: 'ت نامه...'
![screenshot unwanted ellipsis](https://user-images.githubusercontent.com/16606340/36196750-f02570c0-1186-11e8-93ab-d190e56101e3.png)

**Comment by mneckoee** [comment]
https://stackoverflow.com/questions/48782439/flutter-unwanted-ellipsis-in-scaffold-actionbar-title-persian-word

**Comment by Hixie** [comment]
We totally fixed this recently. Please try again! Let us know (file a new bug) if it is still broken.
