### ISSUE TITLE
Expected Timeline  to release a google_sign_in version that Support Apple App Privacy Manifest  ?

### ISSUE THREAD

**Issue by Abdeltwab** [flutter/flutter#146984]
## Context 

Apple required App Privacy manifests  for third-party SDKs.   

### References
https://developer.apple.com/app-store/user-privacy-and-data-use/
https://developer.apple.com/support/third-party-SDK-requirements/

It's already done [here](https://github.com/flutter/packages/pull/6404) by the team 

## Request 
when we can expect a new version https://pub.dev/packages/google_sign_in/versions  with these updates ?
any expected timeline ?

**Comment by danagbemava-nc** [comment]
The change does not need to be added to `google_sign_in` itself. Once it has been added to `google_sign_in_ios` you should have it in your project. You should run `flutter pub upgrade` to make sure you're running the latest version of the plugin. 

If you are facing any issues related to App privacy manifest, please file a new issue and provide the relevant details. See also https://github.com/flutter/flutter/issues/131940#issuecomment-2006965339

Closing from here. 

Thank you
