### ISSUE TITLE
Purchase subscribed items issue

### ISSUE THREAD

**Issue by tangshilin888** [flutter/flutter#146974]
### Steps to reproduce

IOS click to purchase subscribed items, a subscribed pop-up window will pop up, click OK, and the callback method will go to purchased instead of error

### Expected results

IOS click to purchase subscribed items, a subscribed pop-up window will pop up, click OK, the callback method will go to error, and inform us that the item has been subscribed

### Actual results

IOS click to purchase subscribed items, a subscribed pop-up window will pop up, click OK, and the callback method will go to purchased instead of error

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@tangshilin888 
Please provide a complete runnable reproducible code sample along with `flutter doctor -v` and including current vs expected behavior upon running the code sample.
