### ISSUE TITLE
Add '/' and '*' operators to `Duration`

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#146997]
### Use case

When dealing with `Duration` it would be great if we could divide or multiply them by a factor:
```
delay: kLongPressTimeout / 2,
The operator '/' isn't defined for the type 'Duration'.
```

### Proposal

support operator '/' and '*'

**Comment by stephane-archer** [comment]
Sorry I never used `~/` before, I did not think about it. 
Suggesting in VSCode if `/` operator does not exit but `~/` does would be great.
I'm not sure if it's the right repo to make this suggestion :)

**Comment by darshankawar** [comment]
@stephane-archer The correct repo would be https://github.com/dart-lang/sdk/issues.
Closing from here.
