### ISSUE TITLE
Or something looks wrong: When OverflowBox is used inside a ScrollView and the view is of scrollable length the OverflowBox would not extend to screen width. Works fine when the view is not of scrollable length. 

### ISSUE THREAD

**Issue by ignicubeLaeeq** [flutter/flutter#147055]
### Steps to reproduce

1. Create a simple flutter scaffold application. 
2. Add Column to the body. 
3. Wrap Column with SingleChildScrollView and Padding.
4. Add following overflow box to children of Column: 
```        
Center(
          child: Container(
            height: 200,
            width: 100,
            color: Colors.red.shade100,
            child: OverflowBox(
              maxWidth: MediaQuery.of(context).size.width,
              minHeight: 100,
              maxHeight: 150,
              child: Container(
                color: Colors.amber,
                height: 100,
              ),
            ),
          ),
        ),
```
This should render fine with amber box going to the edges of the screen. 

6. Add Container to column with enough height that scroll is activated. 

The yellow box no longer extends to the edge of the screen and is cropped by the padding. 

### Expected results

The overflow box should extend to the edge of the screen even if the view is scrollabale.

### Actual results

OverflowBox not going to the edge of the screen horizontally when view is of enough height that it can scroll. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Flutter Demo',
    theme: ThemeData(
      colorScheme: ColorScheme.fromSeed(seedColor: Colors.red),
      useMaterial3: true,
    ),
    debugShowCheckedModeBanner: false,
    home: const MyHomePage(),
  ));
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('Home page'),
        centerTitle: true,
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: SingleChildScrollView(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Center(
                  child: Container(
                    height: 200,
                    width: 100,
                    color: Colors.red.shade100,
                    child: OverflowBox(
                      maxWidth: MediaQuery.of(context).size.width,
                      minHeight: 100,
                      maxHeight: 150,
                      child: Container(
                        color: Colors.amber,
                        height: 100,
                      ),
                    ),
                  ),
                ),
                // SizedBox(
                //   height: MediaQuery.of(context).size.height,
                // ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

| variant1 | variant2 |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/111270323/5af7e244-b0d7-4ea8-8a3f-f42fe4d45742"> | <img width="400" src="https://github.com/flutter/flutter/assets/111270323/704a9140-8829-4a21-9318-9f6bcd04dd31">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @ignicubeLaeeq 
The default clipBehavior in SingleChildScrollView is `Clip.hardEdge` which enables clipping. This will be fixed by using `Clip.none` instead.

I will close the issue as solved. If it doesn't fit your case, please write in comments and I will re-open this and take another look! Thank you!
