### ISSUE TITLE
flutter tool downloading Dart SDK twice

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14700]
```
$ flutter precache
$ diff -rq bin/cache/artifacts/engine/<platform>/dart-sdk bin/cache/dart-sdk
```

After #14610, those two SDKs are identical, yet we're still making the user download them both.  That's ~116M of unnecessary download.

/cc @aam

**Comment by devoncarew** [comment]
IDEs use the `bin/cache/dart-sdk` path; we'll need that to continue existing (or a migration plan for the IDE plugins).

**Comment by aam** [comment]
The migration plan forward would be to use `bin/cache/artifacts/engine/<linux-x64|darwin-x64|windows-x64>/dart-sdk` instead of `bin/cache/dart-sdk`. Would that present a problem for IDE?

**Comment by tvolkert** [comment]
Alternatively, we could potentially explore symlinks, but I'm not sure whether whether we're ok with only supporting more recent versions of Windows that supports symlinks... Maybe we already do?
  @goderbauer

**Comment by devoncarew** [comment]
Symlinks (or copying files on platforms w/o useable symlinks) would work.

> The migration plan forward would be to use bin/cache/artifacts/engine/<linux-x64|darwin-x64|windows-x64>/dart-sdk

I'd have a preference for a path that clients could use that didn't need to have detailed knowledge about how to construct the path (that wasn't different per OS and rely on the correct OS ids).

`bin/cache/dart-sdk` is really pretty good from that perspective :) Keeping it would be great.

In any case, heads up that tools are relying on the current path, and we'd want to have a migration plan and timeframe if we do decide to change.

**Comment by tvolkert** [comment]
Copying could work.  The motivation for this bug is only to avoid a large download for the user.

**Comment by aam** [comment]
I understand that introducing platform-sniffing code adds complexity into the tool, but creating symlinks or copying dart sdk puts increased cognitive load on the users(why there are two copies, if we end up copying which one is master, etc).

**Comment by aam** [comment]
Of course we might have no choice but symlink/copy in case there is architectural problem with using platform-specific paths(like dependency_overrides section in flutter_tools/pubspec.yaml)

**Comment by tvolkert** [comment]
This could be a horrible idea, but another solution would be to have shell scripts that live in `bin/cache/dart-sdk` that call out to the platform-specific delegates.
