### ISSUE TITLE
Add dart executable gn rule for engine tests

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#147013]
Currently many tests in the engine are run via Python scripts. Instead, tests written in Dart should be generated using a gn target just like we do with tests written in C++ or Objective-C.

Output could either be a dart native binary or a shell script (Mac, linux) or ps1/bat (Windows) that invokes the standalone binary on the input Dart files.

**Comment by matanlurey** [comment]
I am going to take over this issue after talking with @cbracken.

He has something working here: https://github.com/flutter/engine/pull/52241.

Something we'd want to consider is `deps` tracking (as-per @zanderso's comment: https://github.com/flutter/engine/pull/52241#discussion_r1575461664).
