### ISSUE TITLE
--enable-software-rendering on Android yields black screen

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14709]
```
# With an Android emulator running
$ cd examples hello_world
$ flutter run --enable-software-rendering
```

That yields an all-black screen.  Same happens with any Flutter app.

/cc @chinmaygarde @brianosman

**Comment by chinmaygarde** [comment]
I don’t think this is Skia related. I’ll take a look.

**Comment by jason-simmons** [comment]
Traced this to https://github.com/google/skia/commit/d4746984e51e18ba3d2e52e96305d72d0fd84c31

The SkImageInfoIsValidCommon does not accept Flutter's use of kPremul_SkAlphaType with kRGB_565_SkColorType

**Comment by brianosman** [comment]
Ooh. Is there a good reason to use 565 in SW mode? I'd assume you want kN32

**Comment by jason-simmons** [comment]
This is a default format chosen by Android for SurfaceView/SurfaceHolder.  It's probably helpful for performance, especially since software rendering is most likely to be used within an emulator.

**Comment by chinmaygarde** [comment]
Yeah, I just picked the 16bpp format thinking it was good enough for emulators and seemed to be supported by Skia. I must admit I did not compare performance with `kN32`. We could just switch.

**Comment by chinmaygarde** [comment]
We definitely should not be specifying `kPremul_SkAlphaType` though.
