### ISSUE TITLE
PlatformExceptions related to wakelock_platform_interface were thrown while just initiating a new Flutter project

### ISSUE THREAD

**Issue by loveoverflowdev** [flutter/flutter#147027]
### Steps to reproduce

+ flutter_version: 3.19.6 • channel stable
+ real_device: Samsung Galaxy A50
+ project: just initiating (counter app)
+ android enviroment: flutter doctor executed with no issues

### Expected results

No platform exception was thrown

### Actual results

Once every few seconds, a PlatformException related to wakelock_platform_interface were thrown

![image](https://github.com/flutter/flutter/assets/113291130/dba44e7e-e0f6-4cac-a915-a96191f817f7)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by loveoverflowdev** [comment]
Dear @danagbemava-nc,
Thank for your response.
Besides, your Pixel device is real device or virtual machine ?

This is the additional description as you mentioned above:

```
Dart SDK 3.3.4
Flutter SDK 3.19.6
ccwakelock 1.0.0+1
|-- cupertino_icons 1.0.8
|-- flutter 0.0.0
|   |-- characters 1.3.0
|   |-- collection 1.18.0
|   |-- material_color_utilities 0.8.0
|   |   '-- collection...
|   |-- meta 1.11.0
|   |-- sky_engine 0.0.99
|   '-- vector_math 2.1.4
|-- flutter_lints 2.0.3
|   '-- lints 2.1.1
'-- flutter_test 0.0.0
    |-- async 2.11.0
    |   |-- collection...
    |   '-- meta...
    |-- boolean_selector 2.1.1
    |   |-- source_span...
    |   '-- string_scanner...
    |-- clock 1.1.1
    |-- fake_async 1.3.1
    |   |-- clock...
    |   '-- collection...
    |-- leak_tracker 10.0.0
    |   |-- clock...
    |   |-- collection...
    |   |-- meta...
    |   |-- path...
    |   '-- vm_service...
    |-- leak_tracker_flutter_testing 2.0.1
    |   |-- flutter...
    |   |-- leak_tracker...
    |   |-- leak_tracker_testing...
    |   |-- matcher...
    |   '-- meta...
    |-- leak_tracker_testing 2.0.1
    |   |-- leak_tracker...
    |   |-- matcher...
    |   '-- meta...
    |-- matcher 0.12.16+1
    |   |-- async...
    |   |-- meta...
    |   |-- stack_trace...
    |   |-- term_glyph...
    |   '-- test_api...
    |-- path 1.9.0
    |-- source_span 1.10.0
    |   |-- collection...
    |   |-- path...
    |   '-- term_glyph...
    |-- stack_trace 1.11.1
    |   '-- path...
    |-- stream_channel 2.1.2
    |   '-- async...
    |-- string_scanner 1.2.0
    |   '-- source_span...
    |-- term_glyph 1.2.1
    |-- test_api 0.6.1
    |   |-- async...
    |   |-- boolean_selector...
    |   |-- collection...
    |   |-- meta...
    |   |-- source_span...
    |   |-- stack_trace...
    |   |-- stream_channel...
    |   |-- string_scanner...
    |   '-- term_glyph...
    |-- vm_service 13.0.0
    |-- characters...
    |-- collection...
    |-- flutter...
    |-- material_color_utilities...
    |-- meta...
    '-- vector_math...
```

**Comment by danagbemava-nc** [comment]
Hi @loveoverflowdev, my Pixel 7 is a physical device. 

Did you start experiencing this issue in a different project before you tried a new flutter project? If so, did that project or any of its dependencies depend on the wakelock plugin?

**Comment by loveoverflowdev** [comment]
> Did you start experiencing this issue in a different project before you tried a new flutter project? If so, did that project or any of its dependencies depend on the wakelock plugin?

Yeah I ever did.

One year ago, I did add the pub wakelock to my project and met that issue.

But when I run other projects which are unrelated to any wakelock features, but on the same real device, I still witnessed those warning logs I mentioned above.

**Comment by huycozy** [comment]
@loveoverflowdev I tried to simulate this issue by following steps but couldn't see the error:

1. Add `wakelock ` to a new Flutter project then run it -> No issue here
2. Create a new Flutter project without adding any dependency then run it -> No issue as well

Do you still experience this issue on every new Flutter project? What is the current `wakelock` version? 

I also checked this on Pixel 7 device. Could you try this on another device if you have?
