### ISSUE TITLE
Unpack cached code on Android to the getCodeCacheDir() directory, rather than the user data directory

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#14704]
This is hello_world example installed via

`flutter run --release`

on a Pixel 2.

![image](https://user-images.githubusercontent.com/6687929/36215029-c6d99510-115f-11e8-9c34-f7aeaf19ac66.png)

Data portion takes 13.5 megabytes.

![image](https://user-images.githubusercontent.com/6687929/36215044-d50dd286-115f-11e8-8641-67c7bc29c2e7.png)

It can be erased but it regenerates when the apps runs.

Compare that to the basic calculator app that takes an order of magnitude less space:

![image](https://user-images.githubusercontent.com/6687929/36215112-087ceb3e-1160-11e8-8ebd-6dae675cb44a.png)

**Comment by rmacnak-google** [comment]
The "user data" is probably the FLX being unzipped. https://github.com/flutter/flutter/issues/9900

**Comment by tvolkert** [comment]
We no longer create FLX files (though some code still exists to handle them).  @szakarias

**Comment by szakarias** [comment]
I'll take a look at this.

**Comment by gabrc52** [comment]
On iOS it's about twice that size.

**Comment by szakarias** [comment]
I installed hello_world on a Nexus 5 and it takes a little less than 25 MB of space both in a Flutter version still using the FLX and in the current version where the FLX is removed. Here the user data is about 11 MB and it's not related to the FLX (or the files that used to be in it).  Are you still getting > 30 MB and could you perhaps show me the contents of the APK?

**Comment by Hixie** [comment]
@szakarias: @jason-simmons was telling me in the triage meeting that apparently this could be us extracting files from the APK into user data space, and that this might no longer be necessary? I'll let you and Jason chat about this further. :-)

**Comment by mehmetf** [comment]
I just installed it on a Sony Xperia phone and it is taking 30.9M of space. 12.5 being user data. 18.31 being the app. Here's the contents and the relative sizes of the apk (in KB) when unzipped. I ran this using `flutter run --release`.

```
8	./res/mipmap-xxxhdpi-v4
8	./res/mipmap-hdpi-v4
8	./res/mipmap-xhdpi-v4
8	./res/mipmap-mdpi-v4
8	./res/mipmap-xxhdpi-v4
40	./res
24	./META-INF
19576	./lib/arm64-v8a
19576	./lib
264	./assets/flutter_assets/fonts
2072	./assets/flutter_assets
26328	./assets
46280	.
```

**Comment by Hixie** [comment]
Can you dump the app's user data as well? What's there?

**Comment by mehmetf** [comment]
@szakarias Not sure how to dump the user data of an app. Phone is not rooted; is there a standard way of doing that?

**Comment by mehmetf** [comment]
OK I tried building a debuggable app so I can inspect the contents of user data. If I do that the user data size drops to 8M (but the app size inflates to 45M). Data dump:

```
.:
total 24
drwxrwx--x 3 u0_a191 u0_a191       4096 2018-03-07 12:06 app_flutter
drwxrws--x 2 u0_a191 u0_a191_cache 4096 2018-03-07 08:20 cache
drwxrws--x 2 u0_a191 u0_a191_cache 4096 2018-03-07 08:20 code_cache

./app_flutter:
total 6496
drwx------ 2 u0_a191 u0_a191    4096 2018-03-07 12:06 flutter_assets
-rw------- 1 u0_a191 u0_a191 6635168 2018-03-07 12:06 icudtl.dat
-rw------- 1 u0_a191 u0_a191       0 2018-03-07 12:06 res_timestamp-1-1520453204622

./app_flutter/flutter_assets:
total 1392
-rw------- 1 u0_a191 u0_a191 1420745 2018-03-07 12:06 snapshot_blob.bin

./cache:
total 0

./code_cache:
total 0
```

**Comment by Hixie** [comment]
Interesting. That sounds consistent with what @jason-simmons was saying. @szakarias, does your recent work mean that we can consume files straight out of the APK these days? Or does uncompressing them still give us a substantial benefit?

**Comment by szakarias** [comment]
I believe this is not a regression. 

We extract the following files from the APK:  ```icudtl.dat, isolate_snapshot_data, isolate_snapshot_instr, vm_snapshot_data, assets/vm_snapshot_instr``` which we also did when we had FLX (the files were not inside the FLX). These files account for the size of the user data. And in general all the binaries in the APK are bigger in the 64 bit version. 

My recent change allows us to read the files in the flutter_assets directory straight out of the APK, that is all the fonts and user-defined assets.

I am removing myself from this issue since it is not related to the FLX removal.

**Comment by Hixie** [comment]
Looks like we're supposed to be putting those files in the directory returned by `getCodeCacheDir` (which I assume would be the `code_cache` directory in the listing above). This wouldn't count against our storage and would not be automatically backed up, which the current files probably are...

**Comment by MichaelSowah** [comment]
very interested in this as I think it will help improve the apk size...

**Comment by zoechi** [comment]
@Hixie What category does this issue belong (tool, engine, ...)?
Is this issue still relevant?

**Comment by eseidelGoogle** [comment]
I believe this would be an engine change.  It's likely very simple to do.

This is likely the line to change:
https://github.com/flutter/engine/blob/70a1106b509ea3f34febca59967ed7a76c05ce33/shell/platform/android/io/flutter/view/FlutterMain.java#L217

Although @chinmaygarde also notes deeper in the engine code that he'd liek to change how path look ups work.  This would probably easy for @jason-simmons to change if needed.

**Comment by matthew-carroll** [comment]
I tried building a new app in release mode with the regular cache dir and then the code cache dir and these are screenshots of the memory results:

Regular Cache:
![android_app_release_regular_cache_dir](https://user-images.githubusercontent.com/7259036/55844132-bcefe500-5af0-11e9-967d-7b172513c2d3.png)

Code Cache:
![android_app_release_code_cache_dir](https://user-images.githubusercontent.com/7259036/55844138-c0836c00-5af0-11e9-80af-45ab06bcb29d.png)

Are these the expected results @Hixie

**Comment by matthew-carroll** [comment]
Also CC @jason-simmons in case you're interested in these numbers.
