### ISSUE TITLE
Clicking in a DropdownMenu causes an assertion

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#147077]
I haven't tried to reproduce this in a test, but FWIW, on macOS, when I click on text in a DropdownMenu (i.e. drop down the menu, select something, then click on the now-visible text in the field), I get:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 3347 pos 14: 'renderer.parent != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:45:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3347:14)
#3      ScrollPosition.ensureVisible (package:flutter/src/widgets/scroll_position.dart:796:28)
#4      ScrollableState._performEnsureVisible (package:flutter/src/widgets/scrollable.dart:1028:55)
#5      Scrollable.ensureVisible (package:flutter/src/widgets/scrollable.dart:475:45)
#6      _DropdownMenuState.scrollToHighlight.<anonymous closure> (package:flutter/src/material/dropdown_menu.dart:527:20)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1326:11)
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#10     _invoke (dart:ui/hooks.dart:312:13)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#12     _drawFrame (dart:ui/hooks.dart:283:31)
```

Doesn't seem to be breaking any functionality, but again, I haven't looked at this closely.

**Comment by Hixie** [comment]
It's problematic in tests, because it causes the test to fail when you try to do something like:
```
    await tester.enterText(find.byType(DropdownMenu<Team>), '63593');
```

**Comment by huycozy** [comment]
Hi @Hixie 
I checked this using [DropdownMenu example](https://api.flutter.dev/flutter/material/DropdownMenu-class.html) but couldn't reproduce the issue.

I looked at the stack trace and see it seems to be similar to a case at https://github.com/flutter/flutter/issues/146764 which was reported recently. Could you check if it's also your case? (embed DropdownMenu inside two SingleChildScrollView)

**Comment by Hixie** [comment]
Ah, yes, my drop-downs are in multiple scroll views (vertical and horizontal).

**Comment by Hixie** [comment]
Yeah that's the same bug. Closing as duplicate.
