### ISSUE TITLE
flutter tool's host Dart SDK could be trimmed down

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14701]
```
$ find bin/cache/dart-sdk/lib -mindepth 1 -maxdepth 1 -type d|cut -d/ -f5|sort
_http
_internal
analysis_server
analyzer
async
cli
collection
convert
core
developer
front_end
html
internal
io
isolate
kernel
math
mirrors
profiler
typed_data
```

At the very least, we don't need `front_end`, `html`, and `mirrors`.  Since we're now building our own host SDK from the Flutter engine, we could build a custom host SDK that doesn't contain these libraries.  The more we trip this host SDK down, the less our developers have to download.

@aam, thoughts?

**Comment by aam** [comment]
Sure, makes sense. I don't know off top of my head whether build rules are flexible enough to do it easily.

**Comment by tvolkert** [comment]
@a-siva who's the resident expert on the SDK build rules?

**Comment by zanderso** [comment]
The build rules for assembling the Dart SDK are here: https://github.com/dart-lang/sdk/blob/master/sdk/BUILD.gn

Flutter is currently building Dart's "platform" SDK, which (should) exclude anything only needed for web development. I believe Flutter's use of the analyzer may require `front_end` to be present, and it is certainly legal for command-line programs to use `mirrors`, but I don't remember why `html` is there. It's possible that it could be safely removed.

More generally, we don't have an easy way to do a lot of customization here, so I think looking for savings elsewhere could make sense.

**Comment by a-siva** [comment]
'html' was included because the google3 folks wanted to run programs that included 'dart:html' with the caveat that if the program executed any of the native stuff from dart:html it would report errors. Keerti might be able to give more details, she is requesting for this feature to be present in the new FE too.

**Comment by tvolkert** [comment]
@keertip, don't the google programs that require `dart:html` run using the stock Google SDK (not the Flutter-vended one)?

**Comment by keertip** [comment]
Yes, they run using the google stock SDK, not with the Flutter vended one.

**Comment by cbracken** [comment]
@tvolkert is this a strategy we're still pursuing? If so, definitely worth discussing this with @mit-mit as I believe that trimming down the internal Dart SDK used by the tool goes in the opposite direction of some product proposals. 

Speaking purely from the engineering perspective, I think it's a worthwhile goal to minimise the differences between the stock SDK and the one we use (at least during the _build_ phase) for risk reduction (we don't independently test our Dart SDK as a full SDK; building something as close as possible helps with _some_ forms of risk) as well as maintenance. 

What tools we bundle and support as part of the internal SDK should involve discussion with product though. I should note that I believe we can definitely make a decision on this issue without necessarily making the product/engineering call to officially support our internal SDK as a full SDK.

**Comment by tvolkert** [comment]
Since this was created, this has become a much less cut-and-dry discussion, which is best had not in a bug.  I'm closing.
