### ISSUE TITLE
Dashboard shows test as in process when it has already passed

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#147033]
### Type of Request

bug

### Infrastructure Environment

Flutter build dashboard (packages)

### What is happening?

After a few retries, a test has now passed, but is still yellow on the board. This is actively blocking the tree.

### Steps to reproduce

Step 1: Repeatedly fail and retry test

### Expected results

Test should show as passing, but shows as in process.

**Comment by keyonghan** [comment]
This is a dup of https://github.com/flutter/flutter/issues/147007.

Please try **avoiding** the GitHub UI `Re-run`, which is missing some logics to handle `retry` logics. Please use [the internal API](http://go/flutter-luci-playbook#manually-trigger-a-post-submit-build)  instead to kick a manual post-submit retry.

I manually reset the tree status, and it is open now.

**Comment by tarrinneal** [comment]
I think there may be another bug with the dashboard, when I click on any test on the current build, it opens a new page that doesn't have the rerun option on it. Clicking on any older tests opens the normal menu with the re-run button.

**Comment by stuartmorgan** [comment]
Yes, that's https://github.com/flutter/flutter/issues/145849
