### ISSUE TITLE
local_auth plugin throws MissingPluginException for some Android users when prompting for auth on app launch/resume

### ISSUE THREAD

**Issue by parkgrrr** [flutter/flutter#147199]
### Steps to reproduce

Note: I am unable to reproduce this issue locally, but have thousands of crashlytics logs from users.

1. Create a flutter screen
2. Add WidgetsBinding.instance.addPostFrameCallback and launch local_auth in the callback. This can be done in a stateful widget, or using a ChangeNotifierProvider
3. execute a local_auth package method to run when a user launches the app.

### Expected results

The plugin should be available to query data from the native android side of the plugin.

### Actual results

Many users are logging `io.flutter.plugins.firebase.crashlytics.FlutterError - MissingPluginException(No implementation found for method isDeviceSupported on channel plugins.flutter.io/local_auth_android). Error thrown null.` but it is difficult to reproduce. about 50% or users say they are in the background state according to crashlytics

It appears to be a race condition due to the method channel not being ready yet. I thought `WidgetsBinding.instance.addPostFrameCallback` would be a safe enough callback to launch auth.  For now I have added a delay and that appears to have helped the issue, but is there a better callback I can wait for, or way to know that the method channel is ready?

### Code sample

<details open><summary>Code sample</summary>

```dart

class ExampleScreen
  const ExampleScreen() : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<ExampleScreenVM>(
        create: (context) {

          final vm = ExampleScreenVM.buildVM();
          //this waits to load the welcome screen before pushing token login
          WidgetsBinding.instance.addPostFrameCallback(
          //local_auth is called from VM
                  (_) => vm.authenticateWithToken());
          return vm;
        },
        builder: (context, _) {
          return Consumer<ExampleScreenVM>(
            builder: (context, vm, _) {
 ...
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
io.flutter.plugins.firebase.crashlytics.FlutterError - MissingPluginException(No implementation found for method isDeviceSupported on channel plugins.flutter.io/local_auth_android). Error thrown null.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.88.1)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @parkgrrr, it appears you're using an older version of flutter & `local_auth` (the minimum flutter version for the latest version is 3.16) can you try upgrading to the latest versions of flutter & `local_auth` to see if you still experience this issue? 

If you do, would it be possible to provide a minimal reproducible code sample so that we can properly investigate this?

**Comment by parkgrrr** [comment]
Yes I am. I am on local_auth 2.18 as well. It is a complex project with lots of dependencies so unfortunately Flutter upgrades aren't trivial but our team is in the process. I am also unable to reproduce it myself, and am debugging through crashlytics logs.

In the meantime, is there anything I'm doing wrong in terms of using a callback other than `WidgetsBinding.instance.addPostFrameCallback` ? I'm just not sure if there is another callback that will ensure the plugin is ready and listening.

**Comment by danagbemava-nc** [comment]
What method from the `local_auth` plugin do you call in `vm.authenticateWithToken()`?

**Comment by parkgrrr** [comment]
The first call is `isDeviceSupported()` but also `stopAuthentication()` and `authenticate()`

I am still rolling out a fix, but it appears that adding a 100ms delay after `WidgetsBinding.instance.addPostFrameCallback` has solved the issue for the most part. If there is a bette callback that would be ideal though.

**Comment by danagbemava-nc** [comment]
Hmm, it appears that the plugins may not be available for a brief moment when resuming from background. What devices are experiencing this issue? It would help if we had a minimal sample so that we could properly investigate this. 

Thank you

**Comment by parkgrrr** [comment]
It happens on Samsung, Motorola, Google, and Oneplus devices. From Android 8 to 14. I also agree that the plugin isn't available for a moment, the 100 ms delay seems to have mostly fixed the issue.  If I am able to reproduce it I will let you know, but for now I have been unsuccessful.

**Comment by danagbemava-nc** [comment]
Hi @parkgrrr, that comment is from 2020, so it's likely it was using a very old version of flutter. Have you been able to create a minimal reproducible code sample that would help us properly investigate this?
