### ISSUE TITLE
SVG rendering issues after flutter upgrade from 3.7

### ISSUE THREAD

**Issue by ristiisa** [flutter/flutter#147139]
### Steps to reproduce

After updating flutter from 3.7 to 3.19 stroke of this SVG file seems to be behaving in an weird way.

### Expected results

<img width="124" alt="image" src="https://github.com/dnfield/flutter_svg/assets/514571/48a7b6f8-bbc1-4861-b70e-e5a5b1adf1db">

### Actual results

<img width="139" alt="image" src="https://github.com/dnfield/flutter_svg/assets/514571/5a1d6f81-119f-46ba-909a-893f55706c9e">

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) => Scaffold(body: Center(child: SvgPicture.asset("image.svg", width: 100)));
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Original SVG file.

![image](https://github.com/dnfield/flutter_svg/assets/514571/05bc418f-1770-4b54-b3fd-3d14e3697f85)

</details>

### Logs

<details open><summary>Logs</summary>

```console
n/a
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale en-GB)
    • Flutter version 3.19.3 on channel stable at /Users/user/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • iPhone 15 Pro (mobile) • A34BE4F3-C4CA-4D58-9542-F55D87BEC5F1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 124.0.6367.60

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by jonahwilliams** [comment]
I suspect this is a similar issue to https://github.com/flutter/flutter/issues/146648 , we may have some problems with repeated close/moveTos.

**Comment by jonahwilliams** [comment]
Current rendering at ToT is slightly better, but the outline is missing a wedge.

![flutter_05](https://github.com/flutter/flutter/assets/8975114/831a547e-68fe-4165-aa8b-25daa1bb9601)

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/flutter/engine/commit/2dde7adbda8a9e28b77d4eb830073672e110c6bf

**Comment by jason-simmons** [comment]
Simplified example:

```
<svg fill="none" height="35" width="30">
   <path
     d="m 24.75,12.5937 C 18.7176,23.0962 16.3242,25.4644 15,26.7132 13.6759,25.4644 11.2824,23.0962 9.18215,20.4356"
     stroke="#0000ff"
     stroke-width="3" />
</svg>
```

| Before https://github.com/flutter/engine/commit/2dde7adbda8a9e28b77d4eb830073672e110c6bf | With https://github.com/flutter/engine/commit/2dde7adbda8a9e28b77d4eb830073672e110c6bf |
| ----- | ----- |
| ![old_crop](https://github.com/flutter/flutter/assets/14226037/a3af5b3a-b96a-4fe7-9639-4fec04a7fa9d) | ![new_crop](https://github.com/flutter/flutter/assets/14226037/3783825c-3843-4858-9325-58bbed8dc8c1) |

**Comment by jonahwilliams** [comment]
Is the failure case here that the additional condition added in https://github.com/flutter/engine/commit/2dde7adbda8a9e28b77d4eb830073672e110c6bf should only apply on the first point of a contour?

**Comment by jason-simmons** [comment]
One thing I noticed is that `AddVerticesForCurveComponent` is adding some vertices using the recomputed offset instead of the original offset.

(see https://github.com/flutter/engine/blob/bd9ef6a3868b784be7ce5847aaf535f81eaa63ed/impeller/entity/geometry/stroke_path_geometry.cc#L235, which happens after `offset` has been updated by the `ComputeOffset` call)

Is that working as intended?

If I patch that to use `previous_offset` then it fixes the issue seen in https://github.com/flutter/flutter/issues/147139#issuecomment-2083260635.  But it introduces another tiny artifact next to the red marker.

![bug_147139_artifact](https://github.com/flutter/flutter/assets/14226037/def1705c-6f9e-4f7d-9a69-3b1538ecd7aa)

**Comment by bdero** [comment]
This join issue is reproducing in several playgrounds, including `GradientStrokesRenderCorrectly/Metal`:

<img width="449" alt="image" src="https://github.com/flutter/flutter/assets/919017/b7d628b0-8b18-439b-bb58-058a8b5ec0af">

**Comment by bdero** [comment]
Yes, what @jason-simmons pointed out is indeed the problem. The last two points of the contour are using the wrong offset. 
<img width="322" alt="image" src="https://github.com/flutter/flutter/assets/919017/611b6167-a0c5-446a-a8cf-5bd85bb63ecc">

**Comment by bdero** [comment]
Eh, I thought about this harder and we don't really need to.
