### ISSUE TITLE
TextField InputDecorator shouldn't show the character counter in dense mode

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#14716]
This is a regression in the material TextField's InputDecorator: when it's in dense mode (isDense:true on the input decoration), it shouldn't show the character counter.  Or, if it does, then it should include the character counter in its calculation of height.

Right now the character counter is drawing outside of the widget bounds if isDense is true and maxLength is set.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
Oops. I will fix that.

**Comment by lucyhoang** [comment]
Hi, which version has this fixing.
I am using flutter v0.8.2 and see that character counter still show

**Comment by HansMuller** [comment]
This bug remains open because it has not been fixed.  It looks like https://github.com/flutter/flutter/pull/19798 was intended to fix it, but that PR was closed without an explanation.  @jonahwilliams ?

**Comment by jonahwilliams** [comment]
I believe there was some ambiguity over whether we should show the helper/error text as well. Since they exist at roughly the same vertical offset as the counter it would keep the height the same if they were present

**Comment by willlarche** [comment]
Dense layout guidance is a long-term WIP. We want to get it right before sharing.

**Comment by justinmc** [comment]
This seems to be more or less fixed.  The character count is included in the height of the widget now, so wrapping a dense input in a (red) container looks like this:

![flutter_03](https://user-images.githubusercontent.com/389558/54843952-dee50d00-4c92-11e9-9f33-116254e8f585.png)

I'm still wondering what the Material spec has to say about this, though.  Looking at the [part about dense text fields](https://material.io/design/components/text-fields.html#filled-text-field) (scroll down a bit), I see that they can have helper text below them.  That makes me think that they should have character counts too, even though I don't explicitly see one with a limited length.

I opened a [YAQS question](https://yaqs.googleplex.com/eng/q/6566708359462912) that isn't getting much love, but if someone replies with something different than our current behavior then I'll reopen this and fix it.

**Comment by marcglasberg** [comment]
@justinmc So you cannot remove the counter in dense mode? I'd say most of the time you want to limit the number or chars but not show a counter. There should be a flag for showing/hiding the counter, independent of dense mode or not.

**Comment by justinmc** [comment]
You can hide the counter by returning null from buildCounter:

```dart
TextFormField(
  maxLength: 10,
  buildCounter: (BuildContext context, { int currentLength, int maxLength, bool isFocused }) => null,
)
```

You could also pass an empty string to `counterText` in `InputDecoration`.  Either one works whether it's dense or not.

**Comment by justinmc** [comment]
I got confirmation that dense mode should not omit any features, so this seems to be confirmed correct as it is with the height fixes.

**Comment by srburton** [comment]
**My solution** 

Limiting a typing to just 3 characters, in a clean way and without code to make it more readable, more testing with content Padding among others and it worked


```` dart

TextField(
	inputFormatters: [
		LengthLimitingTextInputFormatter(13),
	],
	decoration: InputDecoration(
		isDense: true
	)
)

````
