### ISSUE TITLE
Failed to run Flutter Gallery on iOS Simulator

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#14718]
This issue seemed to be only affecting Flutter Gallery on my Google Corp Mac. 

## Steps to Reproduce
```
$ flutter run
Running "flutter packages get" in flutter_gallery... 1.3s\
Launching lib/main.dart on iPhone SE in debug mode...
Running Xcode clean...                               0.8s-
Running Xcode build...                               1.3s-
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
Could not build the application for the simulator.
Error launching application on iPhone SE.
```

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.
```
$ flutter doctor -v
[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-US, channel master)
    • Flutter version 0.1.2-pre.17 at /Users/taodong/Code/flutter_repos/flutter
    • Framework revision 59fe5d0f46 (45 minutes ago), 2018-02-14 15:25:12 -0800
    • Engine revision f8778fce17
    • Tools Dart version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c
    • Engine Dart version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c

-
```

The process hung at this point. 

I fixed the problem by opening Xcode and let it install "additional components". It would've been helpful if `flutter doctor` could tell me what I need to do.

**Comment by InMatrix** [comment]
Correction: Installing additional components from Xcode didn't really fix the problem. I still can't run Flutter Gallery. I'll investigate more.

**Comment by rdsarna** [comment]
@InMatrix Were you able to run the gallery app on iOS simulator? I'm facing a similar problem in running the "platform_view" example app on an iOS simulator.

**Comment by InMatrix** [comment]
I was able to run the gallery app on iOS simulator. I can no longer reproduce the problem after reinstalling Flutter. @rdsarna I encourage you to open a new issue and provide relevant logs for the problem you ran into. I'll close this issue for now.
