### ISSUE TITLE
After upgrade Xcode15 and i had a problem that "prod.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources"."

### ISSUE THREAD

**Issue by bluexuchun** [flutter/flutter#147150]
### Steps to reproduce

upgrade xcode15
repodinstall

### Actual results

<img width="307" alt="image" src="https://github.com/flutter/flutter/assets/22693912/dd638e4f-aae9-4baa-b389-f241896a271d">

### Logs

prod.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 14.1.1 23B81 darwin-x64, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[!] Android Studio (version 2022.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.88.1)
[!] Connected device
    ! No devices available

**Comment by huycozy** [comment]
Hi @bluexuchun 
Please check answers from [this](https://stackoverflow.com/questions/65434877/flutter-runner-app-info-plist-does-not-exist-the-flutter-thin-binary-build-p) to see if any helps.

If the error persists, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so we may verify this properly.

**Comment by bluexuchun** [comment]
> Hi @bluexuchun Please check answers from [this](https://stackoverflow.com/questions/65434877/flutter-runner-app-info-plist-does-not-exist-the-flutter-thin-binary-build-p) to see if any helps.
> 
> If the error persists, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so we may verify this properly.

Thank you.
It solved my problem!
