### ISSUE TITLE
Can't swipe from a PopupMenuButton to easily select an item

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#14710]
## Steps to Reproduce

1. Add a PopupMenuButton.
2. Long press and swipe.
3. A tooltip will be shown instead of opening the menu like it does with native widgets.

**Comment by cbracken** [comment]
Thanks for reporting. Verified this locally with a Flutter app and an OEM android widget.

/cc @Hixie @HansMuller

**Comment by HansMuller** [comment]
Sadly, this probably has been around for a while.  It was also reported here: https://github.com/flutter/flutter/issues/5064

It's not clear how to relay the press-drag-release gesture from the PopupMenuButton to the menu.  I believe that in X11 one can use XGrabPointer() to grab the rest of a press-drag-release gesture away from the current gesture handler. Perhaps we need something similar in Flutter.

**Comment by gabrc52** [comment]
Closing as it's a duplicate issue
