### ISSUE TITLE
TextFormField becomes unresponsive after Navigator.push

### ISSUE THREAD

**Issue by vongrad** [flutter/flutter#147113]
### Steps to reproduce

TextFormField is not able to receive focus when it is within a page that gets pushed using `Navigator.of(context).push`. On the other hand, if the new page is pushed using `Navigator.of(context).pushReplacement`, it receives focus and the user can input text. This happens specifically on simulator iPhone SE (3rd generation) with iOS 17.2 and probably other devices, although not tested. On the other hand, it works on simulator iPhone 15 Pro with iOS 17.2.

1. Create iOS simulator running iPhone SE (3rd generation) with iOS 17.2 
2. Run the provided sample code
3. Click on `Go to page 2` button
4. Click inside the `TextFormField`

### Expected results

After clicking into the `TextFormField`, it receives focus and the user can input text into it.

### Actual results

The `TextFormField` is unable to receive focus and becomes unresponsive.
On the other hand, if the new page is pushed using `Navigator.of(context).pushReplacement`, everything works as expected.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextButton(
                onPressed: () {
                  Navigator.of(context)
                      .push(MaterialPageRoute(builder: (context) => Page2()));
                },
                child: Text('Go to page 2'))
          ],
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [TextFormField()],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/3223913/2c6b0974-d962-4071-aa63-ae96648c3549

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.3 23D56 darwin-arm64, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by storm265** [comment]
On top bar tap` I/O `-> `Keyboard` -> and uncheck `Connect Hardware Keyboard`

**Comment by huycozy** [comment]
@vongrad I checked the issue using the same simulator but couldn't see the issue. Maybe this is just a simulator setting as @storm265 shared above, so please check it to see if it works for you.

**Comment by vongrad** [comment]
@huycozy @storm265 That fixed it, thank you!
