### ISSUE TITLE
Build a widget again & again if use ModalRoute.of(context) and open or close a Dialog or Dropdown on Web.

### ISSUE THREAD

**Issue by harismairaj** [flutter/flutter#147167]
### Steps to reproduce

1. Click on a button to open a dialog.
2. Dismiss a dialog by clicking outside or press ESC key.

### Expected results

Shouldn't build a widget again and again on open or close a dialog / dropdown.

### Actual results

Every time when dialog modal or dropdown open or close widget build function fires.
It wasn't happening in v3.13.9 on web.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) => const MaterialApp(home: TestWidget());
}

class TestWidget extends StatelessWidget {
  const TestWidget({super.key});

  @override
  Widget build(BuildContext context) {
    ModalRoute.of(context); // It will never build again and again if we comment it.
    print("build");
    return Center(
      child: MaterialButton(
        onPressed: () {
          showDialog(
            context: context,
            builder: (context) {
              return const AlertDialog(
                content: Center(child: Text("child")),
              );
            },
          );
        },
        child: const Text("Button"),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[screen-recorder-mon-apr-22-2024-20-40-38.webm](https://github.com/flutter/flutter/assets/14214435/70daa278-6868-46a2-83e1-08636ccb951c)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.88.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @harismairaj, this is similar to a case at https://github.com/flutter/flutter/issues/143709. And it seems the current behavior is correct, please see https://github.com/flutter/flutter/issues/143709#issuecomment-2004965978 for more details.

Closing this as a duplicate.

**Comment by harismairaj** [comment]
Thanks [CoderBuck](https://github.com/CoderBuck) to provide some workaround on this issue.

Below is the temporary solution for this issue.
https://github.com/flutter/flutter/pull/145389#issuecomment-2056036841

I think this should be tackle by flutter team.

**Comment by huycozy** [comment]
You can also check these comments for more information: https://github.com/flutter/flutter/issues/146132#issuecomment-2060056302 and https://github.com/flutter/flutter/issues/146132#issuecomment-2061699746
