### ISSUE TITLE
Icon missing from fonts

### ISSUE THREAD

**Issue by Caio-Tenca** [flutter/flutter#147145]
### Steps to reproduce

When I Google "material icons", I get this site, which contains the icon I need:
https://fonts.google.com/icons?icon.query=psychiatry

But when I navigate through the icons help page for flutter (https://api.flutter.dev/flutter/material/Icons-class.html) I get the exact same URL but without the icon I need.

 - Navigate to https://material.io/resources/icons from the Icons page
 - Type in "psychiatry" and see no icon appears

Is there a way to get the full set of icons that are available from a natural navigation to font.google.com/icons in Flutter?

Flutter doctor run:
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.5)
[√] Android Studio (version 2022.1)
[√] Connected device (3 available)
[√] Network resources

### Expected results

All icons on fonts.google.com/icons are available in Flutter.

### Actual results

Some icons are missing, which matches what happens when getting to fonts.google.com/icons through https://material.io/resources/icons

**Comment by danagbemava-nc** [comment]
What you're seeing is a material symbol, which is slightly different from the icons we have in flutter. Support for that is being tracked in https://github.com/flutter/flutter/issues/102560. 

Kindly follow up in the original issue for updates. 

Closing from here. 

Thank you
