### ISSUE TITLE
Video Buffering/downloading percentage

### ISSUE THREAD

**Issue by anamalihassan** [flutter/flutter#147170]
### Use case

I came across a requirement for media loading app to show download/buffering percentage while the video is loading. It is common to have internet problems in the subway and in remote areas of different countries where the connection is poor. The video loading can take longer. It would be great to show the percentage.  

### Proposal

Return download/buffering video value.

**Comment by stuartmorgan** [comment]
Could you elaborate more on your use case, and what parts of it `the existing `buffered` value](https://github.com/flutter/packages/blob/7f14b8a5404e687a8faec7ac0c7aa1a67f3fc628/packages/video_player/video_player/lib/video_player.dart#L92-L93) does not address?
