### ISSUE TITLE
Flutter unexpected behavior after logout and login again

### ISSUE THREAD

**Issue by Schokiii93** [flutter/flutter#147151]
### Steps to reproduce

Hello guys,

I am facing some issues in my flutter project. I use firebase for login and get the following unexpected behavior:

1. Login with a user -> right after login the user is redirected to the main screen
2. I logout again
3. I login with another user (not the same user as in step 1) -> I expect the user to be redirected to the main screen again
4. But: The login screen is still visible
5. I refresh the app
6. The main screen is visible

The case that the login screen is still visible after login with another account is not the expected behavior. This only happens if I was logged in with another account right bevor the login.

### Expected results

Every time a user uses the login they should be redirected to the main screen.

### Actual results

The user remains on the login screen and after refreshing the app they see the main screen. This only happens if someone (another user) was logged in right bevor the user loggs in.

I know this should not happen in reality because nobody loggs in with another account but I am very confused about why this happens.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:davkursmanager/providers/userdata_provider.dart';
import 'package:davkursmanager/screens/events/event_details.dart';
import 'package:davkursmanager/screens/login/login_screen.dart';
import 'package:davkursmanager/screens/mainscreen/main_screen.dart';
import 'package:davkursmanager/screens/mainscreen/not_activated.dart';
import 'package:davkursmanager/theme.dart';
import 'package:davkursmanager/widgets/constants/loading.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'firebase_options.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await dotenv.load();

  await FirebaseAppCheck.instance.activate(
    androidProvider: AndroidProvider.debug,
  );

  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [Locale('de', 'DE')],
      debugShowCheckedModeBanner: false,
      title: 'testapp',
      theme: getThemeData(),
    );
  }
}

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

/// The route configuration.
final GoRouter _router = GoRouter(
  navigatorKey: navigatorKey,
  initialLocation: '/',
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return StreamBuilder(
          stream: FirebaseAuth.instance.authStateChanges(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return Loading();
            }
            if (snapshot.hasData) {
              return Consumer(
                builder: (BuildContext context, WidgetRef ref, Widget? child) {
                  final userProfileAsync = ref.watch(userProfileProvider);
                  return userProfileAsync.when(
                    data: (userData) {
                      if (userData != null) {
                        //check if user has already been activated
                        bool accountActivated = userData.accountActivated;
                        return accountActivated
                            ? const MainScreen()
                            : const AccountNotActivatedScreen();
                      } else {
                        //other events
                        return Center(
                          child: Loading(),
                        );
                      }
                    },
                    loading: () => Scaffold(body: Loading()),
                    error: (error, stackTrace) {
                      return const Text(
                          'Fehler beim Abrufen der Benutzerdaten');
                    },
                  );
                },
              );
            } else {
              return const LoginScreen();
            }
          },
        );
      },
    ),
  ],
);

``` 

This is my provider I use for user data. Maybe there is something wrong?
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:davkursmanager/models/user/user.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

//provider to get profile data
//stream provider gets data every time the profile is loaded
final userProfileProvider = StreamProvider.autoDispose<UserData?>((ref) {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  final currentUser = _auth.currentUser;
  if (currentUser != null) {
    final userDocRef = _firestore.collection('users').doc(currentUser.uid);

    return userDocRef.snapshots().map((snapshot) {
      if (snapshot.exists) {
        final userData = snapshot.data();
        return UserData(
          userData?['email'],
          userData?['firstName'],
          userData?['lastName'],
          userData?['membershipNumber'],
          userData?['accountActivated'],
          userData?['isAdmin'],
        );
      } else {
        return null;
      }
    });
  }

  return Stream.value(null);
});

``` 

This is the method I use for login:
```dart
Future signInWithEmailAndPassword(
      BuildContext context, String email, String password) async {
    try {
      UserCredential result = await _auth.signInWithEmailAndPassword(
          email: email, password: password);
      User? user = result.user;
      return _userFromFirebaseUser(user);
    } on FirebaseAuthException catch (e) {
      if (context.mounted) {
        if (e.code == "wrong-password") {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text("Falsches Passwort"),
              duration: Duration(seconds: 7),
            ),
          );
        } else if (e.code == "user-not-found") {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text("Benutzer nicht gefunden"),
              duration: Duration(seconds: 7),
            ),
          );
        } else if (e.code == "invalid-credential") {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text("Bitte überprüfe deine Zugangsdaten"),
              duration: Duration(seconds: 7),
            ),
          );
        } else {
          //all other errors
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text("Ein unerwarteter Fehler ist aufgetreten"),
              duration: Duration(seconds: 7),
            ),
          );
        }
      }
    } catch (e) {
      rethrow;
    }
  }
``` 
</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F5059e darwin-arm64, locale
    de-DE)
    • Flutter version 3.19.6 on channel stable at /Users/dennisforster/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (vor 5 Tagen), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dennisforster/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 13 (API 33) (emulator)
    • iPhone von Dennis (mobile)  • 00008130-000109243A51001C • ios            • iOS
      17.4.1 21E236
    • macOS (desktop)             • macos                     • darwin-arm64   •
      macOS 14.5 23F5059e darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 124.0.6367.61

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
@Schokiii93 
Your issue is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this doesn't seem to be a framework bug, but implementation issue and support question.
