### ISSUE TITLE
Wrong link in flutter codelab first

### ISSUE THREAD

**Issue by junjieyuan** [flutter/flutter#147110]
### Steps to reproduce

1. Open [Flutter Codelab First (Chinese: 构建您的第一个 Flutter 应用)](https://codelabs.developers.google.com/codelabs/flutter-codelab-first?hl=zh-cn#8), please choose Chinese in language selector.
2. Click link in "查看[此高级版本](https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8)的同一应用的代码，了解如何添加动画列表、渐变、淡出淡入效果等。", dartpad show "page not found" and "GoException: no routes for location: /e7076b40fb17a0fa899f9f7a154a02e8".

### Expected results

Open dartpad and show code.

### Actual results

Dartpad show "page not found" cause by wrong link in flutter codelabs.

The dartpad link in "查看[此高级版本](https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8)的同一应用的代码，了解如何添加动画列表、渐变、淡出淡入效果等。" should be changed to ```https://dartpad.dev/?id=e7076b40fb17a0fa899f9f7a154a02e8```.

### Code sample

N/A

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Screencast: Flutter Codelabs wrong link](https://github.com/flutter/flutter/assets/40716445/a9738867-358c-4e67-987f-280e9409dc57)

</details>

### Logs

N/A

### Flutter Doctor output

N/A

**Comment by huycozy** [comment]
Thanks for your report. 

cc: @domesticmouse

**Comment by domesticmouse** [comment]
Googlers: cl/628733325

**Comment by domesticmouse** [comment]
Fix landed
