### ISSUE TITLE
Compress video must be optional  on ios

### ISSUE THREAD

**Issue by joshua750** [flutter/flutter#147225]
### Use case
I am creating video trimming application in which  user can pick video and trim inside my app

### Proposal

I am picking video from gallery  on ios  they automatically  compress the video before picking please make this feature as optional or add disable or enable capability inside it.

**Comment by huycozy** [comment]
I guess this proposal is for [image_picker](https://pub.dev/packages/image_picker), right? If so, there is already an issue for that at https://github.com/flutter/flutter/issues/24954.

I will go ahead and mark this as a duplicate. Please follow up on that issue for updates.
