### ISSUE TITLE
flutter doctor starts, hangs up and never finishes

### ISSUE THREAD

**Issue by aam** [flutter/flutter#14725]
Symptoms:
```
─➤  bin/flutter doctor -v                                                                                                       130 ↵

[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-US, channel master)
    • Flutter version 0.0.25-pre.89 at $FH/flutter
    • Framework revision c0c6c60b8f (7 minutes ago), 2018-02-15 07:29:42 -0800
    • Engine revision f8778fce17
    • Dart version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c

-^C
```
Somehow `runDetachedWithIO` never completes, doesn't get to line  https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart#L189 to send 'n' to the stdin for sdkmanager in response to the prompt "review licenses that have not been accepted":

```
╰─➤  $HOME/Library/Android/sdk/tools/bin/sdkmanager --licenses                                                              
Warning: File /Users/aam/.android/repositories.cfg could not be loaded.         
4 of 6 SDK package licenses not accepted. 100% Computing updates...             
Review licenses that have not been accepted (y/N)?  
```

**Comment by jcollins-g** [comment]
This is "fixed" in #14727 and I'll try to avoid reproducing it.

@aam, if you can run `/usr/libexec/java_home ; echo $?` on the system where flutter doctor hung, this will help me determine if this is something new, or the same as : https://github.com/flutter/flutter/pull/14535#issuecomment-365891126.

Also if you can let me know how long you waited for it that'd help.

**Comment by jcollins-g** [comment]
worked with @aam offline, this is a separate issue from the prompting.

**Comment by jcollins-g** [comment]
This is closed due to the previous revert.  Will track not reintroducing it in #13584.

**Comment by livroandroid** [comment]
My flutter doctor never ends...  It stays like this for hours:

"Doctor summary (to see all details, run flutter doctor -v):"

**Comment by zoechi** [comment]
@livroandroid have you tried `flutter doctor -v`?

**Comment by CetinBasoz** [comment]
I tried, it was working well before with no error\warnings, now after upgrading on May 29th, 2019,  it hangs out there. Neither summary nor -v do something.

**Comment by pratiksanglikar** [comment]
I faced the same issue as @livroandroid . The issue is persistent when I issue the command `flutter doctor -v`.
I'm on MacOS.

**Comment by cianiandreadev** [comment]
Same issue here. MacOS CI system. Get stuck and seems to eat my RAM.

**Comment by SufianBabri** [comment]
I'm on Debian Buster. This happened to me after I ran `git pull` on my flutter SDK folder.
I had to run `flutter precache` before I could successfully run `flutter doctor`.

@cianiandreadev

**Comment by robsonsobral** [comment]
Same issue here, but on Windows. To run `flutter precache` seems to work. Thank you, @SufianBabri .

**Comment by yashank09** [comment]
Hello, I'm facing a similar issue where all my requirements get checked, however I get stuck after `VS Code` check. Same results with `flutter doctor -v`. I'm currently on the latest beta version, running the latest linux.

**Comment by zzterrozz** [comment]
> Hello, I'm facing a similar issue where all my requirements get checked, however I get stuck after `VS Code` check. Same results with `flutter doctor -v`. I'm currently on the latest beta version, running the latest linux.

Same issue here, did you find a solution ?

**Comment by yashank09** [comment]
> > Hello, I'm facing a similar issue where all my requirements get checked, however I get stuck after `VS Code` check. Same results with `flutter doctor -v`. I'm currently on the latest beta version, running the latest linux.
> 
> Same issue here, did you find a solution ?

I actually have switched to the stable version instead, but even Beta worked using @SufianBabri 's comment to run `flutter precache`

**Comment by AkechiShiro** [comment]
Facing the same issue, @SufianBabri comment did work for me, but I had to run `flutter precache` twice for some obscure reason.

**Comment by hicnar** [comment]
Still here @jcollins-g 
![Screenshot 2021-06-19 at 20 25 21](https://user-images.githubusercontent.com/1816194/122653470-8edca580-d13c-11eb-8a0d-6b55e2269286.png)
