### ISSUE TITLE
IOS app crashing, EXC_BAD_ACCESS KERN_INVALID_ADDRESS/ CoreFoundation ___CFXRegistrationPost_block_invoke + 88

### ISSUE THREAD

**Issue by junaidens** [flutter/flutter#147238]
### Steps to reproduce

I am trying to install the flutter IOS from app store, it is crashing when opens the app. 
OS is 17.4.2 with different IOS devices.

### Expected results

App will not crash.

### Actual results

App crashing when installing from app store.

### Code sample
pubspec.ymal file
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  http: ^0.13.0
  shared_preferences: ^2.0.12
  auto_size_text: any
  url_launcher:
  provider: ^6.0.2
  flutter_html: ^2.2.1
  encrypt: ^5.0.1
  universal_platform: any
  stacked: ^2.2.7+1
  carousel_slider: any
  firebase_core: ^2.19.0
  firebase_messaging:
  flutter_local_notifications: "9.2.0"
  firebase_analytics: ^5.0.11
  firebase_crashlytics:
  firebase_remote_config:
  get: ^4.6.1
  local_auth:
  device_info:
  step_progress_indicator: any
  percent_indicator: any
  gallery_saver:
  permission_handler: any
  contacts_service: ^0.6.3
  flutter_sticky_header: any
  focus_detector: any
  path_provider:
  share_plus:
  scrollable_positioned_list: ^0.2.3
  pdf: ^3.6.4
  hijri: ^3.0.0
  pdfx:
  flutter_inappwebview: "6.0.0"
  connectivity:
  qr_flutter: ^4.0.0
  flutter_slidable: ^1.2.0
  scroll_snap_list: ^0.8.4
  clipboard: ^0.1.2+8
  recase: ^4.0.0
  flutter_spinkit: ^5.1.0
  phone_number:
  iban: ^1.0.1
  flutter_jailbreak_detection: "1.8.0"
  location:
    path: ./packages/location
  geolocator: 9.0.0
  app_settings: ^4.2.0
  check_vpn_connection: ^0.0.1
  package_info_plus:
  barcode_scan2: ^4.2.4
  sms_autofill: ^2.2.0
  gif:
  open_filex:
  flutter_windowmanager: ^0.2.0
  external_app_launcher:
  file: ^6.1.4
  win32: ^2.3.6
  easy_stepper:
  in_app_review: ^2.0.6
  shimmer:
  word_generator: ^0.4.3
  dotted_border: ^2.0.0+1
  flutter_secure_storage:
  pointycastle:
  flutter_svg:
  google_maps_flutter: ^2.3.0
  flutter_xlider: ^3.5.0

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @junaidens 
Does the crash occur if you run the project in `release` mode? If it does, please share the entire output of `flutter run --release -v` that may contain stack trace to investigate this further.

And please also share the Flutter version you are using (`flutter doctor -v`). Thanks!

**Comment by junaidens** [comment]
**Here's the crash logs from firebase** 
Crashed: com.apple.main-thread
0  Flutter                        0x3070c (Missing UUID )
1  Flutter                        0x305e8 (Missing UUID )
2  CoreFoundation                 0x2f7a8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
3  CoreFoundation                 0x2f170 ___CFXRegistrationPost_block_invoke + 88
4  CoreFoundation                 0x2f0b8 _CFXRegistrationPost + 440
5  CoreFoundation                 0x2e608 _CFXNotificationPost + 728
6  Foundation                     0x29f10 -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
7  UIKitCore                      0x2fa3d4 -[UIInputWindowController postNotificationName:userInfo:] + 468
8  UIKitCore                      0x336d5c __68-[UIInputWindowController postValidatedStartNotifications:withInfo:]_block_invoke + 1160
9  UIKitCore                      0x3368b0 -[UIInputWindowController postValidatedStartNotifications:withInfo:] + 228
10 UIKitCore                      0x3367a8 -[UIInputWindowController postStartNotifications:withInfo:] + 72
11 UIKitCore                      0xc03b8c __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.510 + 580
12 UIKitCore                      0x3526e8 -[UIInputViewAnimationStyle launchAnimation:afterStarted:completion:forHost:fromCurrentPosition:] + 368
13 UIKitCore                      0xc04e6c __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.538 + 56
14 UIKitCore                      0x2cd1c0 -[UIInputWindowController chainPlacementsIfNecessaryFrom:toPlacement:transition:completion:] + 684
15 UIKitCore                      0x2cb548 -[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:] + 3116
16 UIKitCore                      0x2ca5bc -[UIInputWindowController setInputViewSet:] + 1636
17 UIKitCore                      0x2c9f2c -[UIInputWindowController performOperations:withAnimationStyle:] + 68
18 UIKitCore                      0xffde8 -[UIKeyboardSceneDelegate setKeyWindowSceneInputViews:animationStyle:] + 2772
19 UIKitCore                      0xff2d0 -[UIKeyboardSceneDelegate setInputViews:animationStyle:] + 136
20 UIKitCore                      0xff21c -[UIKeyboardSceneDelegate setInputViews:animated:] + 76
21 UIKitCore                      0x136218 -[UIKeyboardSceneDelegate setInputViews:] + 56
22 UIKitCore                      0x8c9a64 __102-[UIKeyboardSceneDelegate _reloadInputViewsForKeyWindowSceneResponder:force:fromBecomeFirstResponder:]_block_invoke.502 + 28
23 UIKitCore                      0x1879ec -[UIKeyboardSceneDelegate _reloadInputViewsForKeyWindowSceneResponder:force:fromBecomeFirstResponder:] + 6204
24 UIKitCore                      0x186170 -[UIKeyboardSceneDelegate _reloadInputViewsForResponder:force:fromBecomeFirstResponder:] + 88
25 UIKitCore                      0x17d2e8 -[UIResponder _finishResignFirstResponderFromBecomeFirstResponder:] + 328
26 UIKitCore                      0x17c874 -[UIResponder resignFirstResponder] + 108
27 WebKit                         0xc8a7d0 <redacted> + 120
28 UIKitCore                      0x7f720 __UIViewWillBeRemovedFromSuperview + 180
29 UIKitCore                      0x7f438 -[UIView(Hierarchy) removeFromSuperview] + 112
30 WebKit                         0x4e27e8 <redacted> + 52
31 flutter_inappwebview           0x43e48 $s20flutter_inappwebview12InAppWebViewC7disposeyyF + 2544
32 flutter_inappwebview           0x10284 $s20flutter_inappwebview24FlutterWebViewControllerC7disposeyyF + 156
33 flutter_inappwebview           0x10400 $s20flutter_inappwebview24FlutterWebViewControllerCfDTo + 152
34 Flutter                        0x1d570 (Missing UUID)
35 Flutter                        0x18524 (Missing UUID)
36 Flutter                        0x114fc (Missing UUID)
37 CoreFoundation                 0x2f7a8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
38 CoreFoundation                 0x2f170 ___CFXRegistrationPost_block_invoke + 88
39 CoreFoundation                 0x2f0b8 _CFXRegistrationPost + 440
40 CoreFoundation                 0x2e608 _CFXNotificationPost + 728
41 Foundation                     0x29f10 -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
42 UIKitCore                      0xe35420 -[UIApplication _terminateWithStatus:] + 232
43 UIKitCore                      0x13934c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 112
44 UIKitCore                      0x60b348 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 164
45 UIKitCore                      0xe30044 -[UIApplication workspaceShouldExit:withTransitionContext:] + 164
46 FrontBoardServices             0x48e64 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 72
47 FrontBoardServices             0xe10c -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 168
48 FrontBoardServices             0x48e04 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 128
49 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
50 libdispatch.dylib              0x786c _dispatch_block_invoke_direct + 288
51 FrontBoardServices             0xa490 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 52
52 FrontBoardServices             0xa410 -[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible] + 240
53 FrontBoardServices             0xa2e8 -[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource] + 28
54 CoreFoundation                 0x3762c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
55 CoreFoundation                 0x368a8 __CFRunLoopDoSource0 + 176
56 CoreFoundation                 0x350b8 __CFRunLoopDoSources0 + 340
57 CoreFoundation                 0x33d88 __CFRunLoopRun + 828
58 CoreFoundation                 0x33968 CFRunLoopRunSpecific + 608
59 GraphicsServices               0x34e0 GSEventRunModal + 164
60 UIKitCore                      0x22aedc -[UIApplication _run] + 888
61 UIKitCore                      0x22a518 UIApplicationMain + 340
62 Runner                         0x19050 main + 11 (AppDelegate.swift:11)
63 ???                            0x1b1e0ed84 (Missing)

**Comment by junaidens** [comment]
Thanks for the response @huycozy, but we are not able too upgrade the flutter version

**Comment by huycozy** [comment]
Or you only need to cherry-pick the commit on https://github.com/flutter/engine/pull/43463 and then rebuild engine to see if it works.

**Comment by abeeriqbal** [comment]
> Or you only need to cherry-pick the commit on [flutter/engine#43463](https://github.com/flutter/engine/pull/43463) and then rebuild engine to see if it works.

Can you please share commit id for cherry pick

**Comment by huycozy** [comment]
Here you are https://github.com/flutter/engine/commit/cf67f834cf16089d45be2341e5198af9da5adc5f

**Comment by abeeriqbal** [comment]
I am not sure how to use that. We are using Flutter https://github.com/flutter/flutter but you are mentioning flutter engine that is different repo. Can you please guide me

**Comment by huycozy** [comment]
You can check Flutter wiki docs here to get started: 
- https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
- https://github.com/flutter/flutter/wiki/Compiling-the-engine

_Or you can read articles here that I noted it from my own experiences: [Getting Started (Part I)](https://huynq.dev/compiling-flutter-engine-locally-part-i) and [Apply a fixed commit (Part II)](https://huynq.dev/compiling-flutter-engine-locally-part-ii)_
