### ISSUE TITLE
[Impeller] Support impeller::MipFilter::kBase for sampling from the base mip level.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#147259]
`SkMipmapMode::kNone` is denotes sampling from the base mip level. Impeller today can either sample from the nearest or use trilinear filtering. To support what Skia does, Impeller must add a new mip filter mode for sampling from the base.

In terms of implementation, Metal supports this via `MTLSamplerMipFilterNotMipmapped` and Vulkan supports this via `VkSamplerCreateInfo::maxLod` set to 0.

**Comment by chinmaygarde** [comment]
Apparently, even Metal has [`[MTLSamplerDescriptor lodMaxClamp]`](https://developer.apple.com/documentation/metal/mtlsamplerdescriptor?language=objc). So the same technique can be used in both backends.

**Comment by matanlurey** [comment]
I am going to take a shot at fixing/implementing this after a little debrief from @jonahwilliams.

Breadcrumbs:
- https://api.flutter.dev/flutter/widgets/Image/Image.html
- https://api.flutter.dev/flutter/dart-ui/FilterQuality.html
- https://github.com/flutter/engine/pull/40491

For transparency, I'm OOO Th-Fr and most of Monday, but I'll try to get out an early PR and/or updates on this bug.

**Comment by matanlurey** [comment]
I'm finally back after a few weeks of totally unconnected PTO and sick-time, and everything else is cleared off my plate. I plan to pick this up starting tomorrow morning.

**Comment by matanlurey** [comment]
I spent most of the this afternoon restoring my ability to compile the engine after the RBE transition.

As a starting point, so I can iterate/observe how this works, I'm planning to add the following tests:

```dart
// testing/dart/image_filter_test.dart

group('ImageFilter|FilterQuality', () async {
  final ImageComparer comparer = await ImageComparer.create();

  Future<Image> makeImage(FilterQuality quality) async {
    final PictureRecorder recorder = PictureRecorder();
    final Canvas recorderCanvas = Canvas(recorder);
    recorderCanvas.drawRect(const Rect.fromLTRB(1.0, 1.0, 2.0, 2.0), Paint()
      ..color = green
      ..imageFilter = makeBlur(1.0, 1.0, TileMode.decal)
      ..filterQuality = quality
    );
    final Picture picture = recorder.endRecording();
    return picture.toImage(3, 3);
  }

  test('FilterQuality.low', () async {
    final Image image = await makeImage(FilterQuality.low);
    await comparer.addGoldenImage(image, 'FilterQuality.low');
  });

  test('FilterQuality.medium', () async {
    final Image image = await makeImage(FilterQuality.medium);
    await comparer.addGoldenImage(image, 'FilterQuality.medium');
  });

  test('FilterQuality.high', () async {
    final Image image = await makeImage(FilterQuality.high);
    await comparer.addGoldenImage(image, 'FilterQuality.high');
  });

  test('FilterQuality.none', () async {
    final Image image = await makeImage(FilterQuality.none);
    await comparer.addGoldenImage(image, 'FilterQuality.none');
  });
});
```

I might need to play around a bit with the generated picture & sizing to see the filter quality, but as a starting point.

**Comment by matanlurey** [comment]
Initial golden-file test landed (^), I'll work on the actual Impeller implementation next.
