### ISSUE TITLE
ios Widget Extension GeneratedPluginRegistrant Use of undeclared identifier ''

### ISSUE THREAD

**Issue by gangstarmn** [flutter/flutter#147278]
### Steps to reproduce

Add Widget Extension on ios app
add mobile_scanner,  app_links etc on pubspec.yaml

### Actual results

![Screenshot 2024-04-24 at 10 25 27](https://github.com/flutter/flutter/assets/2180684/c9993b9a-5429-45f2-90b0-541a1feb784e)

I'm trying to ios Widget Extension on my application but getting this error

I think it's maybe **GeneratedPluginRegistrant.h** imported in my extension target and  using 
  mobile_scanner,  app_links etc. Because the are using UIKit and ios Widget extension did't allow to use UIKit and and camera

Can anyone solve this issue? Let me know

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-MN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment]
Hi @gangstarmn 
What kind of extension did you add? 

I tried adding `AutoFill Credential Provider` and two packages above (only adding and not implementing any functions) but couldn't see the issue:

```
mobile_scanner: ^5.0.1
app_links: ^4.0.1
```

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 

Also, please provide the error log in text format instead of a screenshot for better readability and investigation, thanks!

**Comment by gangstarmn** [comment]
I'm using 

```
  app_links: ^4.0.1
  mobile_scanner: ^4.0.1
```


i've pushed test code in [https://github.com/gangstarmn/widget_test](url). 

i've just added Widget extension target. 
**Runner** target is working ok.
But try to run Widget extension target(in my case **MYWidgetExtension** not in **Runner** target)  i've got error 

> Use of undeclared identifier 'MobileScannerPlugin'
> 
> /Library/Developer/Xcode/DerivedData/Runner-fpqcflxdhvsyapcyaezyzuaakegp/Build/Products/Debug-iphonesimulator/mobile_scanner/mobile_scanner.framework/Headers/mobile_scanner-Swift.h:364:2 Unsupported Swift architecture

**Comment by huycozy** [comment]
When I ran your sample code, I got another error (similar to 2nd error at https://developer.apple.com/forums/thread/704269). 

>Use of undeclared identifier 'MobileScannerPlugin'
/Library/Developer/Xcode/DerivedData/Runner-fpqcflxdhvsyapcyaezyzuaakegp/Build/Products/Debug-iphonesimulator/mobile_scanner/mobile_scanner.framework/Headers/mobile_scanner-Swift.h:364:2 Unsupported Swift architecture

Is there only MobileScannerPlugin's error? If so, you should report this to its developer for better support there or ask the same on support channel like Stackoverflow. 

If you believe this is a Flutter framework bug, you should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, and isolating the issue into a minimal sample code that can produce the issue. And please share it here when you have such an example. Thanks!
