### ISSUE TITLE
[two_dimensional_scrollables] Support to freeze headers and columns.

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#147304]
https://github.com/flutter/flutter/assets/61263149/386c4ab1-907a-41e6-a98f-249d2dabb5fb

Is it possible to achieve this using using **two_dimensional_scrollables?** I tried but was not able to achieve it.
Also is there a way to achieve  

<img width="327" alt="Screenshot 2024-04-24 at 8 19 10 PM" src="https://github.com/flutter/flutter/assets/61263149/38d5cc52-4cf5-4659-a66e-77e727574111">

This UI with a 2d scrollable table. and the **Spot Price** element should stick to the top and bottom of the scrollable viewport as per the user scroll direction.

Thanks in advance.

**Comment by darshankawar** [comment]
@faisalansari0367 
Have you looked at `pinnedRowCount` and `pinnedColumnCount` ?
Take a look at below example and see if it helps in your case or not:

```
body: TableView.builder(
        verticalDetails: const ScrollableDetails.vertical(reverse: true),
        horizontalDetails: const ScrollableDetails.horizontal(reverse: true),
        cellBuilder: (context, vicinity) => Container(
          margin: const EdgeInsets.all(4),
          color: Colors.grey,
        ),
        diagonalDragBehavior: DiagonalDragBehavior.free,
        pinnedRowCount: 1,
        pinnedColumnCount: 1,
        columnCount: 100,
        columnBuilder: (int column) =>
            const TableSpan(extent: FixedTableSpanExtent(64)),
        rowCount: 100,
        rowBuilder: (int row) =>
            const TableSpan(extent: FixedTableSpanExtent(64)),
      ),
```

**Comment by faisalansari0367** [comment]
> @faisalansari0367 Have you looked at `pinnedRowCount` and `pinnedColumnCount` ? Take a look at below example and see if it helps in your case or not:
> 
> ```
> body: TableView.builder(
>         verticalDetails: const ScrollableDetails.vertical(reverse: true),
>         horizontalDetails: const ScrollableDetails.horizontal(reverse: true),
>         cellBuilder: (context, vicinity) => Container(
>           margin: const EdgeInsets.all(4),
>           color: Colors.grey,
>         ),
>         diagonalDragBehavior: DiagonalDragBehavior.free,
>         pinnedRowCount: 1,
>         pinnedColumnCount: 1,
>         columnCount: 100,
>         columnBuilder: (int column) =>
>             const TableSpan(extent: FixedTableSpanExtent(64)),
>         rowCount: 100,
>         rowBuilder: (int row) =>
>             const TableSpan(extent: FixedTableSpanExtent(64)),
>       ),
> ```

Thanks @darshankawar for the response. I will give it a try and let you know if it works for me.

Thanks

**Comment by faisalansari0367** [comment]
Hey @darshankawar 
Got your help before, appreciated! However, now I'm stuck on implementing scroll to index functionality. Tried multiple approaches but no luck.

Hey @Piinks, any thoughts on this? How can we achieve scroll to index?

Also, need advice on:

- Inserting a widget like spot price (check screenshot).
- Making it stick to top/bottom when scrolling in Tableview.builder.

I created a RenderObject ([edge_detector](https://gist.github.com/faisalansari0367/e3df3d7f492bcc06650380e57c0f2046)) to detect if element is at the top of bottom of the viewport edge with the help of scrollPosition. Works, but misses values during fast scrolls with table view builder vertical scroll controller.

Can both scenarios be achieved? Thanks in advance!

**Comment by darshankawar** [comment]
@faisalansari0367 
Does your original 

> now I'm stuck on implementing scroll to index functionality. Tried multiple approaches but no luck.

Most probably you are hitting https://github.com/flutter/flutter/issues/81005 that you can check and follow-up in.


> Also, need advice on:
> 
> * Inserting a widget like spot price (check screenshot).
> * Making it stick to top/bottom when scrolling in Tableview.builder.

You may ask the same in support channels like StackOverflow, as this github is to track feature requests and bugs and not for guidance on code implementation.
