### ISSUE TITLE
Integration test timeout on headless android emulator

### ISSUE THREAD

**Issue by sthai256** [flutter/flutter#14732]
## Steps to Reproduce

1. Create a headless android emulator
2. Create the flutter sample project
3. Create a simple integration test to tap the plus button 4 or so times
4. Run flutter drive.
5. Times out upon the second tap.
Expected: integration should pass as running this exact same test on a non-headless emulator works perfectly fine.

## Logs

Using device Android SDK built for x86.
Starting application: test_driver/simple.dart
Initializing gradle...                                0.7s
Resolving dependencies...                             0.6s
Installing build/app/outputs/apk/app.apk...           3.2s
Running 'gradlew assembleDebug'...                    1.1s
Built build/app/outputs/apk/debug/app-debug.apk (24.6MB).
I/flutter ( 6838): Observatory listening on http://127.0.0.1:42659/
I/FlutterActivityDelegate( 6838): onResume setting current activity to this
00:00 +0: groupTest (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:8118/
[trace] FlutterDriver: Looking for the isolate
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: groupTest test tap
tap 1
tap 2
00:06 +0 -1: groupTest test tap [E]
  DriverError: Error in Flutter application: Timeout while executing tap: TimeoutException after 0:00:05.000000: Future not completed
  #0      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:168)
  <asynchronous suspension>
  #1      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:370)
  <asynchronous suspension>
  #2      _runExtension (dart:developer-patch/dart:developer/developer.dart:85)
  
  Original error: null
  Original stack trace:
  null
      
  package:flutter_driver/src/driver/driver.dart 342:7           FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                                _Completer.completeError
  package:flutter_driver/src/driver/driver.dart                 FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40               _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart 319:68          FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 368:11          FlutterDriver.tap
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:flutter_driver/src/driver/driver.dart 367:73          FlutterDriver.tap
  test_driver/simple_test.dart 28:22                            main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40               _asyncThenWrapperHelper
  test_driver/simple_test.dart 23:31                            main.<fn>.<fn>
  package:test/src/backend/declarer.dart 161:27                 Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 40               _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart 159:70                 Declarer.test.<fn>.<fn>.<fn>
  package:test/src/backend/invoker.dart 250:15                  Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 247:23                  Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 247:5                   Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 159:33                 Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/declarer.dart 158:13                 Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/declarer.dart 143:66                 Declarer.test.<fn>
  package:test/src/backend/invoker.dart 404:25                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 403:31                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                    new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21               Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 367           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 401           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 164        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                      new Timer
  dart:async/timer.dart 87                                      Timer.run
  dart:async/future.dart 172                                    new Future
  package:test/src/backend/invoker.dart 403:15                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 390:27                  Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 390:9                   Invoker._onRun.<fn>.<fn>
  package:test/src/backend/invoker.dart 444:15                  Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 389:7                   Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test/src/backend/invoker.dart 388:11                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31      _LiveTest.run
  dart:async/future.dart 200                                    new Future.microtask.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/timer_impl.dart 376           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 401           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 164        _RawReceivePortImpl._handleMessage
  
00:06 +0 -1: groupTest (tearDownAll)
00:06 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:376)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:401)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
Stopping application instance.
Driver tests failed: 255

**Comment by blackmenthor** [comment]
I've come to this problem too, and i fix it with adding timeout params to the tap method.

Hope it helps somebody in the future

**Comment by mmcc007** [comment]
Same as @blackmenthor for me. The default timeout is 5 seconds, I upped it to 20. Here is an example on travis of several apps running on both a headless simulator (on osx) and emulator (on linux) (though the emulator is an older version): 
https://travis-ci.org/brianegan/flutter_architecture_samples/builds/440338478

**Comment by yjbanov** [comment]
It sounds like the headless emulator is simply slow? 5 seconds is quite a long timeout for a tap. I wonder if in headless mode our threads are throttled by the system. Ironically I'd love to _see_ what the UI is doing in headless mode.

**Comment by mmcc007** [comment]
TD;LR when running headless run flutter driver on osx using Xcode simulator.

Haven't quite figured out all that's going on yet with android emulators. It's a bit of a poor fit for running headless in the cloud as far as I can tell. But still possible to get something working if ur ok with running slowly on older emulators.

When Google dropped support for ARM emulators for x86 emulators (which require hardware acceleration) emulators ran a lot faster. 

But travis does not support hardware acceleration (as most cloud vendors don't for that matter). And AFAIK travis does not provide a GPU (as with most cloud vendors).

Now I assume headless means running in the cloud as you cannot see the graphics. AFAIK, I don't think there is an actual headless mode for emulator to run locally.

When running an android emulator on travis (on linux or osx) there is no hardware acceleration or GPU. So u have to use an (older) ARM emulator and tell the emulator to run the graphics in software (using QEMU which runs in user space). This runs a lot slower and requires adding timeouts. Running locally with hardware acceleration and a GPU does not require timeouts. 

Ironically running the flutter driver on osx using the Xcode simulator does not require adding timeouts (at least for the tests I've run). Even though it too is not using hardware acceleration or a GPU. I imagine the Xcode simulator takes care of all this automatically. So the short answer is when running on cloud run flutter driver on osx using the Xcode simulator. It's much easier to configure and run.

**Comment by yjbanov** [comment]
Thanks for the detailed write-up. If this is the world we'll be living in for quite a while, then I guess our timeout should be adjustable. Right now they are [constants](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver/driver.dart#L65). 

We could introduce a global timeout multiplier that you could configure for your test. Would something like this help?

**Comment by mmcc007** [comment]
Yep that would help. Currently have to add a timeout to each call to the emulator/simulator so a global way to do that would make a lot of sense.

**Comment by yjbanov** [comment]
I'll send a PR shortly.

**Comment by yjbanov** [comment]
PR is out for review https://github.com/flutter/flutter/pull/24066
