### ISSUE TITLE
 flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());

### ISSUE THREAD

**Issue by Ashish1-Sharma** [flutter/flutter#147364]
I continuously working on this error to solve it. I don't know why it occurs . pls help me to resolve it

**Comment by darshankawar** [comment]
@Ashish1-Sharma 
Your question / issue is more suited for support channels like StackOverflow.
If you think this is a bug in framework, please use issue template, fill out requested details so that we can properly address it.
Closing for now due to lack of details.
