### ISSUE TITLE
Package file has no versions that match 2.3.5 derived from

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#14736]
C:\Windows\System32>flutter upgrade
Updating flutter tool...
Package file has no versions that match 2.3.5 derived from:
- flutter_tools depends on version 2.3.5
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

**Comment by aam** [comment]
Can you paste your `flutter doctor -v` output?
Can you paste your `flutter upgrade -v` output?
Can you try `flutter update-packages` and see if that helps?

This might be related to flutter tools switching to engine's version of dart (https://github.com/flutter/flutter/pull/14610).

**Comment by tvolkert** [comment]
It's probably related to the fact that file 2.3.5 has an invalid dart sdk constraint of:

    '>=1.19.0 <2.0.0-dev.infinity'

https://github.com/google/file.dart/blob/2.3.5/pubspec.yaml

2.3.6 was published explicitly to fix this.

**Comment by Hixie** [comment]
@MichaelSowah What does `git log -1` output? And `git branch`, for that matter.

**Comment by MichaelSowah** [comment]
D:\flutter>git log -1
commit b3e4976ca20dc878bd8a484b877b66351bed86e4 (HEAD -> master, origin/master, origin/HEAD)
Author: Mikkel Nygaard Ravn <mravn@google.com>
Date:   Thu Feb 15 22:17:12 2018 +0100

    Move plugin injection to just after pub get (#14560)

**Comment by katelynwang** [comment]
I have similar problem saying below


Package async has no versions that match 2.0.4 derived from:
- flutter_gallery depends on version 2.0.4
- pub itself depends on version >=1.8.0 <3.0.0
pub get failed (1)

**Comment by najeira** [comment]
After switching Flutter from the new version to old 0.0.20, I encountered this problem too.
I executed `rm -rf /path/to/flutter/bin/cache/`, after that `flutter doctor` works.

**Comment by MichaelSowah** [comment]
I think I can close this issue since the recent updates fixed and there are other fixes in the thread as well. Feel free to reopen if you think otherwise
