### ISSUE TITLE
ScrollView.keyboardDismissBehavior doesn't unfocus the keyboard properly

### ISSUE THREAD

**Issue by Daus123** [flutter/flutter#147396]
### Steps to reproduce

步骤:
Put keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag in a SingleChildScrollView, which has TextField among the children.
Tap on the TextField to focus on it.
Dismiss the keyboard by scrolling the page
Navigator.push 'page B'
then pop 'page A'
Find TextField auto focus. keyboard auto show

likeness : https://github.com/flutter/flutter/issues/103544

### Expected results

When I return to page A, the keyboard should not spring up

https://github.com/flutter/flutter/assets/13214559/2042a52e-4952-4c69-a79e-9fae60b1e811

### Actual results

Keyboard auto show

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Daus123** [comment]
flutter appears after being upgraded from 3.7.12 to 3.19.1,

**Comment by huycozy** [comment]
Thanks for the report! 

This is a known issue being tracked at https://github.com/flutter/flutter/issues/124778. Closing this issue as a duplicate, so please follow up on it for further updates.
