### ISSUE TITLE
The platform channel doc doesn't match the plugin template created by the IDE

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#14739]
## Steps to Reproduce

When I created a plugin project using Android Studio's project wizard, the resulting code is quite different from starting from a default Flutter project used in [the platform channel doc](https://flutter.io/platform-channels/). As someone who's learning to write a plugin for the first-time, I felt the doc was less useful when I started my flow from the plugin template offered by the IDE. Can we update the doc to reflect the plugin authoring flow in the IDE? Since Android Studio is necessary to write Android-side of things, it seems that starting from a CLI-based flow is not really useful.

Cc: @mit-mit

**Comment by mit-mit** [comment]
The platform channel docs were written with the assumption that the channel code is being added to an app, not a plugin, see 'Step 1: Create a new app project':
https://flutter.io/platform-channels/#example-project

The docs for creating a plugin are:
https://flutter.io/developing-packages/

But I agree that this is getting confusing, and would benefit from being cleaned up. I personally unfortunately do not have bandwidth for this at the moment.

**Comment by InMatrix** [comment]
I see. Related to this, [the plugin doc](https://flutter.io/developing-packages/#step-2d-connect-the-api-and-the-platform-code) refers to the platform channels doc for adding platform specific code:

![image](https://user-images.githubusercontent.com/348942/36347079-f99884f2-1402-11e8-8724-3f9fb6a896dd.png)

Yet, the platform channels doc starts from an app template instead of a plugin template.

**Comment by Sfshaza** [comment]
@InMatrix, can we close this?

**Comment by InMatrix** [comment]
I think the confusion still exists. The main problem here is that the Plugins doc sends the user to the Platform Channels doc at Step 2d, where the user will have created the plugin template already. But the example in Platform Channels doc has a quite different boilerplate, so the user needs to figure out how to proceed on their own.

**Comment by Sfshaza** [comment]
Yup, needs to be fixed.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1913](https://github.com/flutter/website/issues/1913) via [**ZenHub**](https://www.zenhub.com/)
