### ISSUE TITLE
My flutter + firebase site does not come up even after deployment

### ISSUE THREAD

**Issue by EUmoye** [flutter/flutter#147331]
### Steps to reproduce

1. I followed the instructions here: https://firebase.google.com/docs/hosting/quickstart
2. flutter build web
3. firebase deploy
I am trying to deploy my flutter app that uses firebase as the backend on the web. 

### Actual results

It is just a blank page
![image](https://github.com/flutter/flutter/assets/137492898/97b34ee9-c4a4-40f0-8546-d1e4b37ba30a)

My inspector tools shows this
![image](https://github.com/flutter/flutter/assets/137492898/dad47258-83a0-494f-bbdf-8573dbe4abd1)

The code at index.html line 136

```html

<script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
   line 137 ->   _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
```

### Logs

<details open>
<summary>Logs</summary>
When I init. firebase hosting, a public/ directory was created for me. I replaced the contents of index.html in public with mine below

```html

<!-- Paste your logs here -->

<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="web">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="name">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>studybuddy</title>
  <link rel="manifest" href="manifest.json">

  <script>
    // The value below is injected by flutter build, do not touch.
    const serviceWorkerVersion = null;
  </script>
  <!-- This script adds the flutter initialization JS code -->
  <script src="flutter.js" defer></script>
</head>
<body>
<script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>
</html>

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
No related issues when running flutter doctor
<!-- Paste your output here -->

```
![image](https://github.com/flutter/flutter/assets/137492898/abe9c799-ee5c-4dd2-861c-2644daffe570)

</details>

**Comment by EUmoye** [comment]
I guess my confusion is, what do I pass into the base href path?
` 
-->
 This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="web">

`

**Comment by danagbemava-nc** [comment]
Hi @EUmoye, copying the `index.html` file alone won't be enough for your application run. Can you try following the setup in https://appcircle.io/blog/deploy-a-flutter-web-app-to-firebase to see if it helps?

**Comment by EUmoye** [comment]
Hi all thank you. The problem has been fixed. I simply needed to deploy the hosting from the web folder generated by build when I run `flutter build web`

I did this by moving to the web folder and running `firebase deploy --only hosting`
