### ISSUE TITLE
Loading Issue 

### ISSUE THREAD

**Issue by cleansterhq** [flutter/flutter#147321]
### Steps to reproduce

Go to Cleanster.com 
Click on "Book Cleaning"
It takes 30 second to load 
Why is this ?

### Expected results

Should be fast

### Actual results

30 to 45 seconds to load

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by moffatman** [comment]
Seems to be slow hosting. E.g. it took 2.5 seconds to transfer the 1.7MB main.dart.js

**Comment by darshankawar** [comment]
@cleansterhq 
Is the app built in flutter ? 
Also check above comment about slow hosting if that's the case with you.

**Comment by cleansterhq** [comment]
Yes it is built in Flutter + Dart . We use firebase to host.

**Comment by cleansterhq** [comment]
This is pulling from Firebase Hosting and there is no where to change the speed of firebase hosting . Can you please look into this closely :) 
@moffatman @darshankawar

**Comment by darshankawar** [comment]
@cleansterhq 
Does the slow hosting speed occurs only after deploying ? or locally as well in release mode ?

**Comment by cleansterhq** [comment]
@darshankawar only after deploying. We tested in incognito, and it seems to run a bit faster. However, it may have something to do with caching

We don't have a way to flush caching in Firebase hosting.

**Comment by AndrewBrook-Google** [comment]
The load time of main.dart.js is a bit slow but it doesn't seem to explain the many-seconds delays the customer is reporting.  

There seems to be something timing out, according to this console error message: 
<img width="786" alt="Screenshot 2024-04-26 at 13 15 24" src="https://github.com/flutter/flutter/assets/122319669/eea59f14-5ecf-4d3a-83bc-5603ca52df72">

**Comment by AndrewBrook-Google** [comment]
(but note - I am not a web app or Flutter developer so I could be totally wrong!)

**Comment by darshankawar** [comment]
@cleansterhq if it is specific to firebase hosting, this isn't the correct repo to report slow hosting speed. You may want to check https://firebase.google.com/docs/hosting or reach out to firebase support for further resolution on cache clearing on it.

**Comment by cleansterhq** [comment]
We are testing AppCheck . Looks like Flutter for Web reCaptcha v3 is required. Since we enabled it without connecting reCaptcha

**Comment by darshankawar** [comment]
That will fall into flutterfire territory @cleansterhq . You may want to look at https://github.com/firebase/flutterfire/issues

**Comment by cleansterhq** [comment]
Finally I found that "Attestation check for Topics" is not related to AppCheck. This is part of experimental Topics API feature, and this is all about advertising. I have installed some configuration to Firebase Hosting that should disable it but no effect.
AppCheck is added to Web and Mac apps. I little sense in it though because it is not supported for Windows. So, we can use it in monitoring mode only.

**Comment by cleansterhq** [comment]
@darshankawar looks like this is a well know issue for flutter web .

We are going to try this two:

https://stackoverflow.com/questions/78145531/optimizing-flutter-web-app-initial-load-times

https://www.dhiwise.com/post/improve-flutter-app-performance-with-optimization-strategies

**Comment by cleansterhq** [comment]
We will just have to use a loading image just to keep user engaged @darshankawar @moffatman cc @AndrewBrook-Google

**Comment by darshankawar** [comment]
@cleansterhq 
Is there a way for you to provide a reproducible code sample that shows the loading issue ?
Also, please check below issues for further reference and see if it resembles your case or not:

https://github.com/flutter/flutter/issues/127704
https://github.com/flutter/flutter/issues/118115
https://github.com/flutter/flutter/issues/102828
https://github.com/flutter/flutter/issues/79706
