### ISSUE TITLE
Monorepo tests failing because of artifact upload path change

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#147360]
The monorepo tests running on https://ci.chromium.org/p/dart/g/monorepo/console are failing because of the change in engine artifact paths created by https://flutter-review.googlesource.com/c/recipes/+/57140

The artifacts are uploaded to 
 gs://flutter_archives_v2/monorepo/8749704910664154849/flutter_infra_release/flutter/b402730cd910b9b4102dfe71fa29232fade714be/dart-sdk-linux-x64.zip

but engine_v2/tester.py recipe is trying to download from
gs://flutter_archives_v2/monorepo/flutter_infra_release/flutter/b402730cd910b9b4102dfe71fa29232fade714be/dart-sdk-linux-x64.zip

The tester.py recipe or the recipe module it calls to provide the path needs to be fixed, or perhaps the proper build_id is not being passed as an input property to the test builds.

**Comment by aam** [comment]
cc @zanderso

**Comment by zanderso** [comment]
Given the circumstances, would reverting https://flutter-review.googlesource.com/c/recipes/+/57140 get us back to a known good state?

**Comment by aam** [comment]
Would it be sufficient to revert just that cl or some other infra changes have to be reverted as well?
Currently only dart->flutter monorepo seems to be broken as a result of that change, which has clear but limited impact: specifically, there is no warning to dart commits breaking dart->flutter rolls. The dart->flutter rolls seems to be running fine.

**Comment by aam** [comment]
https://flutter-review.googlesource.com/c/recipes/+/57300 with proposed fix

**Comment by aam** [comment]
also https://flutter-review.googlesource.com/c/recipes/+/57320 seems to have fixed the problem
