### ISSUE TITLE
flutter has been upgraded to flicker in some places

### ISSUE THREAD

**Issue by zouwang123** [flutter/flutter#147352]
### Steps to reproduce

 Use the PopupMenuButton and click

### Expected results

Parts of it will flicker

### Actual results

No error reported,I can't figure out why,help me

### Code sample

<details open><summary>Code sample</summary>

```dart

PopupMenuButton<String>(
  child: ..., 
  onSelected: (String value) {
    setState(() {
    });
  },
  itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
    const PopupMenuItem<String>(
      value: 'item1',
      child: Text('Item 1'),
    ),
    const PopupMenuItem<String>(
      value: 'item2',
      child: Text('Item 2'),
    ),
  ],
)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/67139083/760cf7c2-c195-4233-9479-116594ca7d0d

https://github.com/flutter/flutter/assets/67139083/d10419a3-953e-473f-9ce5-413b02a7f3d2

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jonahwilliams** [comment]
You have checkerboard offscreen images/repaint borders turned on in devtools

**Comment by zouwang123** [comment]
> You have checkerboard offscreen images/repaint borders turned on in devtools

sorry,I don't know how to modify it.I used the plugin but I didn't make any other changes.

**Comment by zouwang123** [comment]
I konw that ,checkerboardOffscreenLayers:false is OK
