### ISSUE TITLE
devicelab mac-17,19,38 are dead

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#147340]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

please check on mac-17,19,38 which are showing up as dead bots

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
All three machines are up and running fine, I can login remotely all three machines from my end. All three machines must out of sync with Salt master, run command "salt-call state.apply" to re-sync with Salt master. Can you check again from your end?

**Comment by yusuf-goog** [comment]
verified they are running now.
