### ISSUE TITLE
Minor Improvement (but with minor effort) - AspectRatio Widget default ratio

### ISSUE THREAD

**Issue by iOSonntag** [flutter/flutter#147344]
### Use case

The AspectRatio Widget does not come with a default value. That means everytime you have to enter a `aspectRatio`. That is totally fine, but it turns out that (at least for me) the aspect ratio `1.0` is the most used one (square dimensions). I suggest assigning the default value of `1.0` to the property so that you not always have to write the property in the coding workflow.

### Proposal

So my proposal would be to change the following:
```dart
/// Creates a widget with a specific aspect ratio.
///
/// The [aspectRatio] argument must be a finite number greater than zero.
const AspectRatio({
  super.key,
  required this.aspectRatio,
  super.child,
}) : assert(aspectRatio > 0.0);
```

to:

```dart
/// Creates a widget with a specific aspect ratio.
///
/// The [aspectRatio] argument must be a finite number greater than zero.
const AspectRatio({
  super.key,
  this.aspectRatio = 1.0
  super.child,
}) : assert(aspectRatio > 0.0);
```

**Comment by iapicca** [comment]
@darshankawar 
what happen if I set `aspectRatio ` to -1, I suspect that `assert` is there for a reason

**Comment by goderbauer** [comment]
I am not convinced that 1 is the ideal default value here.

**Comment by iOSonntag** [comment]
Why is that @goderbauer ? Even if there would be a default value that fits even better (which we don't know), having any default value is still better than having no default value.

That is because in a tiny percentage (let's say 5%) the chosen default value fits just perfect, and developers who code a lot will certainly remember the default value and know when not to use the aspectRatio.

And furthermore I think even if 4/3 or 16/9 would be a more often chosen default value, 1.0 is still the best option as it pushes no opinion on aspect ratio in general. It's just a square
