### ISSUE TITLE
 Linter rule to catch type information loss in generic state class definitions

### ISSUE THREAD

**Issue by Tomburgs** [flutter/flutter#147369]
### Use case

It would be beneficial to have a linter feature that catches errors related to the loss of type information in generic class definitions, especially in the context of Flutter's Stateful Widgets. This issue often arises when the state class does not properly specify the generic type on the `State` class, leading to potential type safety issues at run time.

----

For example, the following code would cause a runtime error when using the `onTap` method. Something along the lines of `type '(MyConcreteTypeImplementation) => void' is not a subtype of type '(dynamic) => void'`.
```dart
class MyGenericWidget<T> extends StatefulWidget {
  final T item;
  final void Function(T) onTap;

  // Imagine a constructor here

  @override
  _MyGenericWidgetState createState() => _MyGenericWidgetState<T>();
}

class _MyGenericWidgetState<T> extends State<MyGenericWidget> {
  // Imagine there is a widget here that calls the onTap with a generic type T.
}
```
This is because when declaring the `_MyGenericWidgetState` the generic `T` is not passed to `MyGenericWidget`.
In the given example, it would have to be declared as:
```dart
class _MyGenericWidgetState<T> extends State<MyGenericWidget<T>>
```
In my opinion this is extremely easy to overlook and can cause a lot of confusion, especially to newer flutter developers who have not ran into this exact issue before.

----

**Related issues:**
  - https://github.com/flutter/flutter/issues/40825
  - https://github.com/flutter/flutter/issues/110718

### Proposal

I think a linter rule would be a good solution. Even something as case-specific as the `MyStatefulWidget` class accepts a generic, therefore when extending `State` and passing the `MyStatefulWidget` (`State<MyStatefulWidget>`), the generic values for `MyStatefulWidget` must also be passed (`State<MyStatefulWidget<T>>`).

**Comment by bartekpacia** [comment]
I think this issue belongs to https://github.com/dart-lang/linter

**Comment by darshankawar** [comment]
@Tomburgs 
This would belong to the repo mentioned above. `flutter_lints` is a plugin to enable existing lints but since you are looking to actually add a new linter rule, it need to be implemented in dart first.
Closing from here.
