### ISSUE TITLE
sentry assert exception with --preview-dart-2

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#14747]
## Logs
```
[+178403 ms] E/flutter ( 3901): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter ( 3901): 'package:sentry/sentry.dart': error: line 70 pos 12: file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/sentry-0.0.6/lib/sentry.dart:70:12: Error: A value of type '() → dart.core::bool' can't be assigned to a variable of type 'dart.core::bool'.
[        ] E/flutter ( 3901): Try changing the type of the left hand side, or casting the right hand side to 'dart.core::bool'.
[        ] E/flutter ( 3901):     assert(() {
[        ] E/flutter ( 3901):            ^
[        ] E/flutter ( 3901):     assert(() {
[        ] E/flutter ( 3901):            ^
```

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-AT, channel dev)
    • Flutter version 0.1.2 at /Users/zoechi/flutter/flutter
    • Framework revision 8a65872ef9 (2 days ago), 2018-02-13 23:32:28 -0800
    • Engine revision 05c5f817eb
    • Tools Dart version 2.0.0-dev.22.0
    • Engine Dart version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

Works fine without `--preview-dart-2`

This has no urgency for me. I was just trying`--preview-dart-2`

**Comment by a14n** [comment]
fixed by flutter/sentry#6
