### ISSUE TITLE
Automatic proxy detection and authentication on Windows

### ISSUE THREAD

**Issue by giregk** [flutter/flutter#147405]
### Use case

I'm using Flutter to write an app for all platforms (except web). My users are company employees, so most of them actually use Windows and operate in corporate networks with proxies.

Flutter only detects environment variables but that's not how corporate proxies are configured on Windows. Requesting the user to setup an environment variable or inputing the proxy config manually is not an acceptable user experience (most of those corporate users have no idea what a proxy is and would panic if they had to configure something technical, even with a good documentation).

First of all, I didn't imagine for a second that Flutter would not handle proxies out of the box, so I was very frustrated when I discovered I had to find a way by myself. For the record, I migrated my app from react-native and never had to think about proxies with React-Native. I do love Flutter, but I really don't understand this choice to not handle proxies in Flutter. The vast majority of Flutter developers if not all would want it to be handled automatically.

Second, when I went looking for solutions, I found no plugin that would handle proxies correctly for windows. There is platform_proxy (https://pub.dev/packages/platform_proxy) that can detect the proxy configuration but it's not production ready. So I implemented my own custom native plugin for windows to detect proxies automatically (close to what platform_proxy did) and it works for unauthenticated proxies. However, in corporate environments, proxies require authentication from users (that's handled automatically of course). It may exist, but I didn't find a way to automatically fetch the proxy authentication credentials for the current user.

The only way that works well in corporate environments is simply to use the native WinHttp api to send requests. That handles proxies and authentication automatically for different kinds of configurations. I could not find a plugin that implemented native WinHttp requests on pub.dev.

For other developers, while this issue is not resolved, here is my code : https://github.com/UpSignOn/windows-proxy-wip

### Proposal

Flutter should work on handling automatic proxy detection and authenticated proxies out of the box. My problem is for now only on Windows, but I think it is similar for other platforms.

This should ideally require no additional package.

At the very least, the documentation (https://docs.flutter.dev/data-and-backend/networking) should be updated to mention this issue clearly and provide guidance on the solution.

**Comment by darshankawar** [comment]
Thanks for the detailed report @giregk 
Can you check below issues and see if they resemble your case or not ?


https://github.com/flutter/flutter/issues/26359
https://github.com/flutter/flutter/issues/10903
https://github.com/dart-lang/http/issues/953

**Comment by giregk** [comment]
Thank you @darshankawar for your feedback
[#26359](https://github.com/flutter/flutter/issues/26359) is the general same issue (but the suggested solution does not mention that juste detecting the proxy config is not enough, we also need automatic authentication with corporate proxies)
[#10903](https://github.com/flutter/flutter/issues/10903) is something different (dev only issue)
[dart-lang/http#953](https://github.com/dart-lang/http/issues/953) is indeed the same issue but again, does not point out that we need automatic proxy authentication too.

**Comment by darshankawar** [comment]
> [dart-lang/http#953](https://github.com/dart-lang/http/issues/953) is indeed the same issue but again, does not point out that we need automatic proxy authentication too.

Thanks for the update. I suggest you to follow-up in it for further updates and also share your findings in it for better tracking, as that issue is in different repo and is specific to http package.
