### ISSUE TITLE
video_player: VideoPlayerController.value.size.height should be an int

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#147475]
### Use case

```
VideoPlayerController controller = VideoPlayerController.file(myFile);
await controller.initialize();
print(controller.value.size.height);
print(controller.value.size.width);
```
height and width are double, are you aware of any floating point number resolution? I think int would be more appropriate.

### Proposal

move to the right type

**Comment by darshankawar** [comment]
@stephane-archer 
Both, `height` and `width` are implemented as `double`:

<img width="432" alt="Screenshot 2024-04-29 at 4 02 38 PM" src="https://github.com/flutter/flutter/assets/67046386/9e8aafb6-bd09-4ae0-96c7-5096c2a5b604">

These properties are then being used in `AspectRatio` as below:

<img width="653" alt="Screenshot 2024-04-29 at 4 02 59 PM" src="https://github.com/flutter/flutter/assets/67046386/90b4b97a-a235-4757-b7c8-bc537df2d25d">

Probably returning `double ` is more safe than returning these property values as int.

**Comment by stephane-archer** [comment]
@darshankawar `width` and `height` are video resolution. the typical values would be 1920 and 1080 respectively. I don't think videos with 0,5 pixels exist. The associated `AspectRatio` would be 16:9. here it makes sense to use a `double` for this value but it's not because to calculate an `AspectRatio` you need a floating point division that `width` and `height` should be defined as `double`

**Comment by stuartmorgan** [comment]
> height and width are double, are you aware of any floating point number resolution?

AVPlayer returns video sizes using doubles (`CGSize`), so using an int would potentially destroy information from the platform level. Given that, plus the fact that altering the type now would be a breaking change, we will be keeping `double` as the type. Clients can always round if they are not concerned about potential loss of precision if there are cases where AVPlayer returns non-integer values.

**Comment by stephane-archer** [comment]
@stuartmorgan Do you have any idea why AVPlayer would return video sizes using doubles? Do I miss something?
