### ISSUE TITLE
[webview_flutter] After repeatedly switching the background foreground in a short period of time, the update of html will be delayed, and sometimes it will be stuck. The html interface will not be updated until some other actions on the interface must be triggered.

### ISSUE THREAD

**Issue by BigPlayerT** [flutter/flutter#147489]
### Steps to reproduce

1、Create an application introduction using webview_flutter;
2、Configure a page with slightly complex interactions，
3、Switch the application repeatedly in the foreground and background in a short time, or repeatedly switch to other apps, and then return to your own app.
4、Carry out relevant operations on the web page。

### Expected results

The interface is updated according to the js operation.

### Actual results

If the interface update fails, actions such as sliding or input box focus must be triggered before the interface can be updated.

The sliding response of the interface is delayed.

### Code sample

1

### Screenshots or Video

·1

### Logs

1

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.5, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.5 on channel stable at /Users/yunpang/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (4 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/yunpang/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • YAL AL00 (mobile) • STS0219711000547          • android-arm64  • Android 10 (API 29)
    • 测试12 (mobile)     • 00008101-00050D600ED8001E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)   • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 124.0.6367.92
    ! Error: Browsing on the local area network for Huanyu的 iPhone 14 Pro Max. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Huanyu的Apple Watch S8. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by OnClickListener2048** [comment]
有录屏吗

**Comment by BigPlayerT** [comment]
以下是我在实际开发中的录屏，成功复现了这个问题。
https://github.com/flutter/flutter/assets/68584496/899c7bb1-3dea-4d17-999b-5e7294ef0864

**Comment by BigPlayerT** [comment]
> 有录屏吗

以下是我在实际开发中的录屏，成功复现了这个问题。
https://github.com/flutter/flutter/assets/68584496/899c7bb1-3dea-4d17-999b-5e7294ef0864

**Comment by BigPlayerT** [comment]
> > 有录屏吗
> 
> 以下是我在实际开发中的录屏，成功复现了这个问题。 https://github.com/flutter/flutter/assets/68584496/899c7bb1-3dea-4d17-999b-5e7294ef0864

刚开始的一段是能够正常响应的，在频繁切换前后台后，应用的DOM树更新就需要类似滑动或者输入框聚焦等操作后才能够成功更新

**Comment by BigPlayerT** [comment]
目前我的解决方法是监听应用前后台前后台切换，在切入后台时移除掉WebViewWidget，在切入前台后添加WebViewWidget。

**Comment by OnClickListener2048** [comment]
你这个页面是h5吗 我们这边目前已知发现的是 回到app后发现h5页面的按钮的点击识别区域上移了

**Comment by BigPlayerT** [comment]
> 你这个页面是h5吗 我们这边目前已知发现的是 回到app后发现h5页面的按钮的点击识别区域上移了

是h5，视频中在切换应用时我把视频放大了点。
你可以看我视频靠后部分，我点击按钮切换时，DOM并没有立即响应更新，直到我进行了滑动或点击了另一个按钮

**Comment by huycozy** [comment]
Hi @BigPlayerT 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code; and share a recorded video demo would also be helpful.  

_And please [consider posting issues in English](https://github.com/flutter/flutter/wiki/Issue-hygiene#consider-posting-issues-in-english) so that others can also look into. Thanks!_

**Comment by BigPlayerT** [comment]
> Hi @BigPlayerT Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code; and share a recorded video demo would also be helpful.
> 
> _And please [consider posting issues in English](https://github.com/flutter/flutter/wiki/Issue-hygiene#consider-posting-issues-in-english) so that others can also look into. Thanks!_

[example.zip](https://github.com/flutter/flutter/files/15157964/example.zip)
上面是我写的一个复现用例，其中包括我在复现时所用到的h5代码。（This is a reproduction use case I wrote, which includes the h5 code I used in the reproduction.）

https://github.com/flutter/flutter/assets/68584496/a166b951-268d-4221-ae35-75e93bbaffe5

这个视频是对应的复现操作，在前几次点击时，界面正常更新了，而在频繁进行前后台切换后，H5界面的更新必须伴随滑动或输入框的聚焦操作之后。（This video is a corresponding reproduction operation. The interface was updated normally during the first few clicks, but after frequent front-end and back-end switching, the update of the H5 interface must be accompanied by sliding or focusing operations in the input box.）
Sorry, my English is very poor.

**Comment by danagbemava-nc** [comment]
Hi @BigPlayerT , what version of `webview_flutter` are you using? What version of `android` is your device running? Can you also try upgrading to the latest version of flutter stable to see if you still experience this issue?

**Comment by BigPlayerT** [comment]
> Hi @BigPlayerT , what version of `webview_flutter` are you using? What version of `android` is your device running? Can you also try upgrading to the latest version of flutter stable to see if you still experience this issue?
webView_flutter's version is 4.5.0;
android's version is 10.

**Comment by huycozy** [comment]
@BigPlayerT This doesn't seem to be related to HTML page content as you shared in sample code above as I can see it on a other web like github.com or google.com. I checked this and observed this behavior:

The web loaded in `webview_flutter` can be interacted normally if I switch to only one app. Once I switch to two apps or more, the web becomes frozen and can't interact with any elements. 

Also, the issue only appears on Android but not on iOS. Verifying with the latest package version `webview_flutter: ^4.7.0`, `webview_flutter_android: ^3.16.1`.

<details>
<summary>Demo</summary>

| OP's sample (pure HTML page) | github.com site |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/19814a36-6776-43c9-9cfb-94d1e275163f"/> | <video src="https://github.com/flutter/flutter/assets/104349824/182925d4-9aed-445d-8742-408ef05634f5"/>
</details> 

Could you retry and confirm this is the issue you are reporting?

**Comment by OnClickListener2048** [comment]
Think this is the same problem with #146499

**Comment by huycozy** [comment]
Oh yes, thanks for linking the issue @OnClickListener2048. I re-checked this on Flutter master channel (my current is 3.22.0-23.0.pre.43), the issue disappeared. I'm using Pixel 7 Android 14. 

@BigPlayerT Could you confirm this on Flutter master channel with your Android 10 device?
