### ISSUE TITLE
log is defined in math and developer packages and has a completely different purpose, we should avoid name collision in the standard library when it make sense

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#147474]
### Use case

log is defined in math and developer packages and has a completely different purpose. not the best development experience.
let's say you have:
```
import developer;

foo() {
int i = 0;
log(i)
}
```

then you need the math package for `bar`, you see the collision and do change your import too 
`import developer as developer; import math` then you add `developer.` when the compiler is complaining
you add up with the following code
```
import developer as developer;

foo() {
int i = 0;
log(i) // BOOM!
}

bar() {
// my math function
}
```

### Proposal

I think the standard library should avoid collision as much as possible. `devLog` could be an acceptable name
the math library and the need to log thing is quite commun

**Comment by danagbemava-nc** [comment]
This should be reported on the dart-lang/sdk repository as the libraries reference are from the dart sdk.

On a side note, I believe this is the reason aliases can be assigned in to imports. This will happen several times with different libraries serving different purposes using the same names that might have different meanings. This isn't necessarily a bad thing. 

Closing from here as this is not a flutter issue. 

Thank you

**Comment by stephane-archer** [comment]
https://github.com/dart-lang/sdk/issues/55590
