### ISSUE TITLE
Solve #138131

### ISSUE THREAD

**Issue by A111one** [flutter/flutter#147490]
#138131

_Originally posted by @A111one in https://github.com/flutter/flutter/pull/147464#pullrequestreview-2026970539_

**Comment by bartekpacia** [comment]
Please review https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md. This issue is not useful because it doesn't follow any of [the templates](https://github.com/flutter/flutter/issues/new/choose).

**Comment by A111one** [comment]
@exts @LuxuryImportGlow
