### ISSUE TITLE
App crashed when flutter call "ClipboardData? data = await Clipboard.getData('text/plain');"

### ISSUE THREAD

**Issue by heijianye** [flutter/flutter#147406]
### Steps to reproduce

1.With Huawei nova 10, Android 12, open album and open a video and select "more"-> "copy to clipboard"

2.Open a flutter app, and call "ClipboardData? data = await Clipboard.getData('text/plain');" in the app.

3.App crashed.

### Expected results

APP run normally

### Actual results

App crashed，with following crash info:
javastacktrace:
java.lang.OutOfMemoryError:Failedtoallocatea537001992byteallocationwith25133056freebytesand238MBuntilOOM,targetfootprint311605016,growthlimit536870912
atjava.util.Arrays.copyOf(Arrays.java:3257)
atjava.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
atjava.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
atjava.lang.StringBuilder.append(StringBuilder.java:191)
atandroid.content.ClipData$Item.coerceToText(ClipData.java:381)
atio.flutter.plugin.platform.PlatformPlugin.getClipboardData(PlatformPlugin.java:338)
atio.flutter.plugin.platform.PlatformPlugin.access$700(PlatformPlugin.java:28)
atio.flutter.plugin.platform.PlatformPlugin$1.getClipboardData(PlatformPlugin.java:107)
atio.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:141)
atio.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
atio.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
atio.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
atandroid.os.MessageQueue.nativePollOnce(NativeMethod)
atandroid.os.MessageQueue.next(MessageQueue.java:363)
atandroid.os.Looper.loop(Looper.java:176)
atandroid.app.ActivityThread.main(ActivityThread.java:8673)
atjava.lang.reflect.Method.invoke(NativeMethod)
atcom.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
atcom.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

### Code sample

<details open><summary>Code sample</summary>

```dart
ClipboardData? data = await Clipboard.getData('text/plain');
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![img_v3_02aa_df70fc5d-7c56-46d8-8afc-ac88f41cae6g](https://github.com/flutter/flutter/assets/13232266/2bb0d9a8-5215-4320-af2b-3681db53bfdc)

</details>

### Logs

<details open><summary>Logs</summary>

```console
javastacktrace:
java.lang.OutOfMemoryError:Failedtoallocatea537001992byteallocationwith25133056freebytesand238MBuntilOOM,targetfootprint311605016,growthlimit536870912
atjava.util.Arrays.copyOf(Arrays.java:3257)
atjava.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
atjava.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
atjava.lang.StringBuilder.append(StringBuilder.java:191)
atandroid.content.ClipData$Item.coerceToText(ClipData.java:381)
atio.flutter.plugin.platform.PlatformPlugin.getClipboardData(PlatformPlugin.java:338)
atio.flutter.plugin.platform.PlatformPlugin.access$700(PlatformPlugin.java:28)
atio.flutter.plugin.platform.PlatformPlugin$1.getClipboardData(PlatformPlugin.java:107)
atio.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:141)
atio.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
atio.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
atio.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
atandroid.os.MessageQueue.nativePollOnce(NativeMethod)
atandroid.os.MessageQueue.next(MessageQueue.java:363)
atandroid.os.Looper.loop(Looper.java:176)
atandroid.app.ActivityThread.main(ActivityThread.java:8673)
atjava.lang.reflect.Method.invoke(NativeMethod)
atcom.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
atcom.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
/Users/heijianye/flutter3/flutter_3.19.3/flutter/bin/flutter doctor --verbose
[!] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.19.3 on channel stable at /Users/heijianye/flutter3/flutter_3.19.3/flutter
    ! Warning: `flutter` on your path resolves to /Users/heijianye/flutter_flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/heijianye/flutter3/flutter_3.19.3/flutter. Consider adding /Users/heijianye/flutter3/flutter_3.19.3/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/heijianye/flutter_flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/heijianye/flutter3/flutter_3.19.3/flutter. Consider adding /Users/heijianye/flutter3/flutter_3.19.3/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (7 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/heijianye/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/heijianye/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.87.0)
    • VS Code at /Users/heijianye/files/压缩包和安装包/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.3.1 23D60 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
Process finished with exit code 0
```

</details>

**Comment by heijianye** [comment]
I only find the feature of "copy video into ClipboardData" on huawei cellphone.

**Comment by huycozy** [comment]
Hi @heijianye 
It seems that feature is only available on Huawei phone, right? I couldn't see it on my devices (Realme 6, Pixel 7). 

Also, I think the format `text/plain` doesn't seem to be appropriate in this case since you are copying a video, but not a text. Per [Copy and paste](https://developer.android.com/develop/ui/views/touch-and-input/copy-paste), clip object can take one of three forms: Text, URI and Intent. You may need to try debugging the format you received from your media to see which format should be used.
