### ISSUE TITLE
coco pods installation problem

### ISSUE THREAD

**Issue by Deemazm** [flutter/flutter#147477]
### Steps to reproduce

when I tape flutter doctor in the terminal it doesn't flow well

### Actual results

when I tape flutter doctor in the terminal it says that coco pods not installed and iOS is missing

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.9, on macOS 14.4.1 23E224 darwin-x64, locale
    en-SA)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    ✗ Unable to get list of installed Simulator runtimes.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
[✓] VS Code (version 1.86.0)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by thejitenpatel** [comment]
@Deemazm which System are you using?

**Comment by danagbemava-nc** [comment]
@Deemazm, please make sure you have `Xcode` installed. Please also make sure you install cocoapods. You can find steps on how to complete the setup in https://docs.flutter.dev/get-started/install/macos/mobile-ios. 

Check the `installing cocoapods` section for how to install cocoapods and you should try installing some simulators in xcode if you already have it installed. 

Thank you
