### ISSUE TITLE
Proposal: add more details to message shown when the tool exits because it's unable to run adb

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#147436]
Occasionally, the Flutter daemon hosted by Visual Studio code on my machine will terminate unexpectedly. The last log message will look something like this:

```
[{"event":"daemon.logMessage","params":{"level":"error","message":"Unable to run \"adb\", check your Android SDK installation and ANDROID_HOME environment variable: /Users/andrewkolos/Library/Android/sdk/platform-tools/adb"}}]
```

From the fact that this only happens occasionally (1-3 times a week despite working on the flutter/flutter repo full-time), and the fact that I can normally invoke `adb` from my terminal just fine, I conclude that the reason for this crash is not something trivial (i.e. `adb` is not installed.) I think we should augment this crash message to include more useful information so that this can be investigated further.

Relevant code:

https://github.com/flutter/flutter/blob/26e379e0fcd93981572d48d5b695ed6fa6279061/packages/flutter_tools/lib/src/android/android_device_discovery.dart#L64-L86

I propose we augment the `throwToolExit` call to include the exception's message.

**Comment by guidezpl** [comment]
Ah I see you're also affected, https://github.com/flutter/flutter/issues/125971

**Comment by andrewkolos** [comment]
> Ah I see you're also affected, #125971

Oh cool, I'll close this as a duplicate of #125971
