### ISSUE TITLE
How Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by cavator** [flutter/flutter#147414]
### Steps to reproduce

i only see people posting errors that show up this code, but i never se no one talking how to  Recompile with -Xlint, i did not found anything useful on google. so how?

### Expected results

.

### Actual results

.

### Code sample

.

### Screenshots or Video

.

### Logs

.

### Flutter Doctor output

.

**Comment by bartekpacia** [comment]
Good question! I also sometimes wondered how to see what the deprecations actually are, but never bothered to do it. But this issue motivated me to check it :)


**Gradle Kotlin DSL**

Add the following code to `android/build.gradle`:

```groovy
subprojects.forEach { project ->
    logger.quiet("Updating settings for project ${project}")
    project.tasks.withType(JavaCompile>) {
        options.compilerArgs += ['-Xlint:deprecation']
    }
}
```
```

```kotlin
subprojects.forEach { project ->
    logger.quiet("Updating settings for project ${project}")
    project.tasks.withType<JavaCompile> {
        options.compilerArgs.addAll(listOf("-Xlint:deprecation"))
    }
}
```

Then `./gradlew clean` and `./gradlew :app:assembleDebug`. Let me know if it helps!
