### ISSUE TITLE
Only Id Token is null while signing via Android , IOS is working fine.

### ISSUE THREAD

**Issue by thufail14** [flutter/flutter#147494]
### Steps to reproduce

1. Click on the sign in button via an android phone.
2. Returning only ID token as null.

### Expected results

1. Need to return the ID Token 

### Actual results

1. Returning the ID Token as null.

### Code sample

<details open><summary>Code sample</summary>

  Future<void> handleSignIn() async {
    try {
      _googleSignIn.disconnect();

      final GoogleSignInAccount? account = await _googleSignIn.signIn();

      bool isAuthorized = account != null;

      log('onCurrentUserChanged....... $account');

      if (isAuthorized) {
        log('onCurrentUserChanged isAuthorized ${account.id} ${account.email}');

        GoogleSignInAuthentication googleSignInAuthentication =
            await account.authentication;

        // Access token
        String? accessToken = googleSignInAuthentication.accessToken;
        log('Access Token: $accessToken');

        // You can also get the ID token
        String? idToken = googleSignInAuthentication.idToken;
        log('ID Token: $idToken');
      } 
    } catch (error) {
      log('handleSignIn Error: $error');
    }
  }

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @thufail14, can you try https://github.com/flutter/flutter/issues/20903#issuecomment-1735878336 to see if it works for you? If it does not, can you share how you setup your project for google sign in?
