### ISSUE TITLE
video_player: Please add support for Windows

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#147518]
### Use case

I actually only need there lines to work not the full package
```
    VideoPlayerController controller = VideoPlayerController.file(file);
    await controller.initialize();
    var height = controller.value.size.height;
    var width = controller.value.size.width;
```

### Proposal

can you implement a really basic version for Windows?

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/37673
