### ISSUE TITLE
TextFormField inputFormatters causing lag and missing input

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#14756]
Using the _UsNumberTextInputFormatter found here: https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart

If I try to type in a phone number at a casual pace, I hear the native keyboard's "click" sound, but the number occasionally fails to register in the field.

Tested this on a Samsung S6 and Note 4.

**Comment by zoechi** [comment]
@pauldemarco are you still seeing this?

**Comment by jeffwoooo** [comment]
i'm seeing this issue.

TextFormField is ignoring key input just after formatter(or in TextEditController's listener) set new text editing value. (no lag or missing character if formatter returns same text. only when text changes.)


and my 'flutter doctor -v'.

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale ko-KR)
    • Flutter version 1.2.1 at /Users/jeff/dev/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jeff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

**Comment by wagner1343** [comment]
Same here, "fixed" it by making `EditableTextState._updateRemoteEditingValueIfNeeded()` to never update remote editing value at all. I dont know what side effects it may have, but so far so good.

**Comment by LegionTesta** [comment]
> Same here, "fixed" it by making `EditableTextState._updateRemoteEditingValueIfNeeded()` to never update remote editing value at all. I dont know what side effects it may have, but so far so good.
> My guess is that `TextInputConnection.setEditingState` eventually called by `EditableTextState._updateRemoteEditingValueIfNeeded()` may block input temporarily when formatters make text changes

I had the same issue. This worked for me, thanks.

**Comment by xster** [comment]
@GaryQian while you're going through the formatters and the editing connection, worth considering this case as well.

**Comment by darshankawar** [comment]
Hi @pauldemarco,
Can you please confirm if you still experience this issue on latest Flutter version (eg: dev, master) ?
Thanks.

**Comment by fmiyahira** [comment]
Same here...
