### ISSUE TITLE
DropdownMenu navigation is incorrect

### ISSUE THREAD

**Issue by ansolantz** [flutter/flutter#147573]
### Steps to reproduce

Navigating to the Dropdown menu is not working in an intuitive way. You can test this in two ways:

1.) With a virtual keyboard that has a next action. When you leave the previous TexField, there is no indication that you have reached the DropdownMenu. If you press space on the keyboard here, it selects the first item in the list which is invisible.

2.) If you use tab navigation. When leaving the previous focus node, there is again no indication that you have entered the DropdownMenu. The focus is currently on the first item in the item list that is invisible. In order to get the the InputField, you need to tab through all items in the list without seeing them, then you finally reach the input field.

In the attached video, you can see the difference between the previous `DropdownButton` and the newer `DropdownMenu`. When navigating to the DropdownButton, it is highlighted and you expand it with space. When leaving the DropdownButton for the DropdownMenu, we have no way of telling that we are currently on that widget. Pressing space will select the first item in the list without us really knowing why.

I think that if we tab to a DropdownMenu it should obtain focus in the InputField. Then you see where you are located and you can choose to either input text or tab once more to the arrow to expand the dropdown. As it is now, there is no way to know where we are when this widget gets focus which is making it hard to use and confusing for accessibility purposes.

### Expected results

When tabbing to a DropdownMenu it should obtain focus in the InputField and the DropdownMenu should be highlighted.

### Actual results

DropdownMenu is not highlighted and you can't see where you are tabbing.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
void main() {
  runApp(const DropdownMenuExample());
}
enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Orange', Colors.orange),
  grey('Grey', Colors.grey);
  const ColorLabel(this.label, this.color);
  final String label;
  final Color color;
}
class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});
  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}
class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController colorController = TextEditingController();
  ColorLabel? selectedColor;
  String _selectedItem = "Item 1";
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        body: SafeArea(
          child: ListView(
            children: <Widget>[
              TextField(textInputAction: TextInputAction.next),
              TextField(textInputAction: TextInputAction.next),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 20),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    DropdownButton<String>(
                      value: _selectedItem,
                      onChanged: (final newValue) {
                        setState(() {
                          _selectedItem = newValue!;
                        });
                      },
                      items: <String>[
                        'Item 1',
                        'Item 2',
                        'Item 3',
                        'Item 4',
                        'Item 5'
                      ].map<DropdownMenuItem<String>>((String value) {
                        return DropdownMenuItem<String>(
                          value: value,
                          child: Text(value),
                        );
                      }).toList(),
                    ),
                    DropdownMenu<ColorLabel>(
                      initialSelection: ColorLabel.green,
                      controller: colorController,
                      requestFocusOnTap: true,
                      label: const Text('Color'),
                      onSelected: (ColorLabel? color) {
                        setState(() {
                          selectedColor = color;
                        });
                      },
                      dropdownMenuEntries: ColorLabel.values
                          .map<DropdownMenuEntry<ColorLabel>>(
                              (ColorLabel color) {
                        return DropdownMenuEntry<ColorLabel>(
                          value: color,
                          label: color.label,
                          enabled: color.label != 'Grey',
                          style: MenuItemButton.styleFrom(
                            foregroundColor: color.color,
                          ),
                        );
                      }).toList(),
                    ),
                    //const SizedBox(height: 710),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/48385990/e63704bf-59e6-484b-8059-2736022c24dc

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by Ut321** [comment]
Right , I am also facing same issue in this .

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/131120. Closing this issue as a duplicate, so please follow up on it for further updates.
