### ISSUE TITLE
'Adding WebView to your Flutter app' https://api.ipify.org/?format=json don't work

### ISSUE THREAD

**Issue by BreathingCapybara** [flutter/flutter#147562]
### Steps to reproduce

https://codelabs.developers.google.com/codelabs/flutter-webview?hl=en#9

### Expected results

https://api.ipify.org/?format=json

### Actual results

https://api64.ipify.org/?format=json

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@BreathingCapybara 
I followed the codelab running on Android emulator and selected `look up ip address` which printed the ip address properly in snackbar.

Are you getting any error while doing so ?

**Comment by BreathingCapybara** [comment]
I tried 'https://api64.ipify.org/?format=json' and success. But codelab text 'https://api.ipify.org/?format=json' doesn't work

**Comment by darshankawar** [comment]
For me it worked as-is, so maybe it could be a config or platform on which you are running.
Will close it since it works with the stated link at your end. If you disagree, write in comments and I'll reopen it.
