### ISSUE TITLE
Inconsistent text field and button heights between web and mobile

### ISSUE THREAD

**Issue by ashndev** [flutter/flutter#147524]
### Steps to reproduce

1. Create a simple Flutter application. 
2. Add a text field with an outlined border so it can be easier to see the text field height.
3. Add an elevated button with some text.
4. Run the app on mobile and web and compare the heights of the text field and button.

### Expected results

I expect the button and text field to have the same height on web and mobile. 

### Actual results

In reality the buttons and text fields have a noticeably smaller height on web as compared to mobile.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(10.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const TextField(
                decoration: InputDecoration(
                  labelText: 'This is a text field',
                  border: OutlineInputBorder(),
                  isDense: true,
                  contentPadding: EdgeInsets.all(10.0),
                ),
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {},
                child: const Text('This is a button'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1662" alt="Screenshot 2024-04-29 at 8 12 58 AM" src="https://github.com/flutter/flutter/assets/87834445/37b8445e-7490-419f-bc13-79f2e3d8d7b9">
<img width="1634" alt="Screenshot 2024-04-29 at 8 42 12 AM" src="https://github.com/flutter/flutter/assets/87834445/47b69d16-2b8f-4c33-bf49-70137e317ccc">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 13.6 22G120 darwin-arm64, locale en-US)
    • Flutter version 3.19.5 on channel stable at /Users/ashley.novik/Documents/devkit/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (5 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ashley.novik/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 15 Pro Max (mobile)  • FB0D9C5A-1190-442A-AD7E-EB6CED4D6B4B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 124.0.6367.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ashndev, I believe this is due the differences between the visual densities of the platforms. See https://api.flutter.dev/flutter/material/VisualDensity-class.html. Regarding the buttons, can you try https://github.com/flutter/flutter/issues/143643#issuecomment-1951417350 to see if it helps?

**Comment by MMSTechnology2024** [comment]
@ashndev , i think The issue of different heights for widgets like buttons and text fields on mobile and web in Flutter occurs because of platform differences, density variations, default styling, and layout constraints. To fix it, you need to explicitly set the sizes of your widgets to ensure consistent appearance across platforms.

here's the sample code:
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(10.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                height: 56.0, // Adjust the height of the container to match the height of the text field
                child: const TextField(
                  decoration: InputDecoration(
                    labelText: 'This is a text field',
                    border: OutlineInputBorder(),
                    isDense: true,
                    contentPadding: EdgeInsets.all(10.0),
                  ),
                ),
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {},
                style: ElevatedButton.styleFrom(
                  minimumSize: const Size(double.infinity, 56.0), // Set minimumSize to match the height of the text field
                ),
                child: const Text('This is a button'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
Explanation of the code:

I wrapped the TextField inside a Container widget and set its height to 56.0 pixels. This ensures that the text field has a fixed height.
For the ElevatedButton, I used the minimumSize property to specify the minimum size of the button. I set its height to 56.0 pixels to match the height of the text field.
Now both the text field and the button will have the same height on both mobile and web.

Hope this will help you.

**Comment by ashndev** [comment]
> Hi @ashndev, I believe this is due the differences between the visual densities of the platforms. See https://api.flutter.dev/flutter/material/VisualDensity-class.html. Regarding the buttons, can you try [#143643 (comment)](https://github.com/flutter/flutter/issues/143643#issuecomment-1951417350) to see if it helps?

Thank you so much! Setting the visual density resolved this. :)

**Comment by ashndev** [comment]
> @ashndev , i think The issue of different heights for widgets like buttons and text fields on mobile and web in Flutter occurs because of platform differences, density variations, default styling, and layout constraints. To fix it, you need to explicitly set the sizes of your widgets to ensure consistent appearance across platforms.
> 
> here's the sample code: import 'package:flutter/material.dart';
> 
> void main() { runApp(const MainApp()); }
> 
> class MainApp extends StatelessWidget { const MainApp({Key? key}) : super(key: key);
> 
> @OverRide Widget build(BuildContext context) { return const MaterialApp( home: HomePage(), ); } }
> 
> class HomePage extends StatelessWidget { const HomePage({Key? key}) : super(key: key);
> 
> @OverRide Widget build(BuildContext context) { return Scaffold( body: Center( child: Padding( padding: const EdgeInsets.all(10.0), child: Column( mainAxisAlignment: MainAxisAlignment.center, children: [ Container( height: 56.0, // Adjust the height of the container to match the height of the text field child: const TextField( decoration: InputDecoration( labelText: 'This is a text field', border: OutlineInputBorder(), isDense: true, contentPadding: EdgeInsets.all(10.0), ), ), ), const SizedBox(height: 20), ElevatedButton( onPressed: () {}, style: ElevatedButton.styleFrom( minimumSize: const Size(double.infinity, 56.0), // Set minimumSize to match the height of the text field ), child: const Text('This is a button'), ), ], ), ), ), ); } } Explanation of the code:
> 
> I wrapped the TextField inside a Container widget and set its height to 56.0 pixels. This ensures that the text field has a fixed height. For the ElevatedButton, I used the minimumSize property to specify the minimum size of the button. I set its height to 56.0 pixels to match the height of the text field. Now both the text field and the button will have the same height on both mobile and web.
> 
> Hope this will help you.

Thanks for your feedback. The issue was in fact due to the varying densities. Also, I'd like to note that wrapping a text field in a container with a set height produced undesirable outcomes such as incorrect input size, content padding and in other cases it can also cut off the helper, counter and error text.

**Comment by danagbemava-nc** [comment]
> > Hi @ashndev, I believe this is due the differences between the visual densities of the platforms. See [api.flutter.dev/flutter/material/VisualDensity-class.html](https://api.flutter.dev/flutter/material/VisualDensity-class.html). Regarding the buttons, can you try [#143643 (comment)](https://github.com/flutter/flutter/issues/143643#issuecomment-1951417350) to see if it helps?
> 
> Thank you so much! Setting the visual density to standard resolved this for me. :)


Great, glad this has been resolved. 

Closing this as solved.
