### ISSUE TITLE
When I run app in my android tv v.11 the media work perfectly 8 or 10 times and then it stop working the resume playback it don’t work anymore the app it’s low sometimes. but it work in mobile device

### ISSUE THREAD

**Issue by Raydden** [flutter/flutter#147500]
hi I have an android tv app When I run it in my android tv v.11 the media work perfectly 8 or 10 times and then it stop working or it crash but it work perfectly  in mobile device can someone help with this issue - I think its from garbage or plug-in. thanks

**Comment by darshankawar** [comment]
@Raydden 
Your issue is more suited for support channels like Stackoverflow, so please ask the same there.
If you think this is an issue / bug in framework, please use new issue template, fill out requested details so that we can properly address the issue.
Closing for now due to lack of details.

**Comment by Raydden** [comment]
I think the flutter app isn't support low ram memory I tried some test with different url I add some url with low resolution and the media work more than 8 times this app work perfectly in mobile device also in emul it work perfectly so the problem this flutter app didn't support low ram this is what I think after all of test if there si any modification to solve this please share it thanks for advance - my android tv run with android v11 & 1Go RAM IF I should share screen recorde about for any info to help
