### ISSUE TITLE
[CP] Workaround HardwareRenderer breakage in Android 14

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#147578]
### Issue Link

https://github.com/flutter/flutter/issues/146499

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/52370

### Changelog Description

Workaround for Android Platform views not displaying after background + trimMemory on android 14.

### Impacted Users

Flutter Android developers who use platform views 

### Impact Description

Apps using platform views when backgrounded and under memory pressure (trimMemory) the platform views fail to render more frames.

### Workaround

No work around other than to update the engine. 

### Risk

medium

### Test Coverage

no

### Validation Steps

* Launch app with platform view on an Android 14 host device. 
* Background the app and either open the camera or run `adb shell am send-trim-memory <APP PACKAGE> BACKGROUND`
* Re launch the app 
* Notice platform views are not getting new frames but are still interactable.

**Comment by itsjustkevin** [comment]
@johnmccutchan for review

**Comment by reidbaker** [comment]
The underlying code has changed too much to land this into 3.19.
