### ISSUE TITLE
flutter layout exception

### ISSUE THREAD

**Issue by pickalex** [flutter/flutter#147570]
### Steps to reproduce

as show the code

### Expected results

The outer container has a height of 0, but the icons inside the stack are displayed, while the text is not displayed.

### Actual results

not display

### Code sample

<details open><summary>Code sample</summary>

```
void main(){
  runApp(MaterialApp(home: Home(),)) ;
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('主页')),
      body:Center(
        child: Container(
          height: 0,
          child: Stack(
            children: [

              Positioned( left: 10 , right: 30,top: 0,bottom: 0, child: Text('hello')) ,
              Positioned( left: 40 ,  right: 0,top: 0,bottom: 0, child: Container(
                color: Colors.green,
                width: 29,
                child: Icon(CupertinoIcons.chevron_up ,size: 16,),
              ) )
            ],
          ),
        ),
      ),
     
    ) ;
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
![image](https://github.com/flutter/flutter/assets/8968504/a0667bbb-2ffe-453e-b063-3144227bfe27)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3527], locale zh-CN)
    ! Warning: `flutter` on your path resolves to D:\flutter_windows_3.7.12-stable\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at
      D:\flutter_windows_3.16.5-stable\flutter. Consider adding D:\flutter_windows_3.16.5-stable\flutter\bin to the front of your path.
    ! Warning: `dart` on your path resolves to D:\flutter_windows_3.7.12-stable\flutter\bin\dart, which is not inside your current Flutter SDK checkout at
      D:\flutter_windows_3.16.5-stable\flutter. Consider adding D:\flutter_windows_3.16.5-stable\flutter\bin to the front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.88.1)
[√] VS Code, 64-bit edition (version 1.86.1)
[√] Connected device (4 available)
[√] Network resources

</details>

**Comment by darshankawar** [comment]
@pickalex 
This seems to be more due to code implementation rather than a bug in framework.
You are passing Container height as 0 and hardcoding Positioned values. 
If you comment out height, it gives below:

<img width="199" alt="Screenshot 2024-04-30 at 5 50 58 PM" src="https://github.com/flutter/flutter/assets/67046386/807e1b4c-4064-4f96-be67-10b274d23044">

So you'll need to properly implement your use case or ask the same in support channels like StackOverflow.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by pickalex** [comment]
which i means parent constraints tight for height 0 , but child icon can dispaly  why? ,is  this right ,i dont know?
