### ISSUE TITLE
Crash on Pixel 7 in impeller opengles backend after engine roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#147503]
On the roll https://github.com/flutter/flutter/pull/147495, there are crashes in the impeller opengles backend like the following in framework CI

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20new_gallery_opengles_impeller__transition_perf/2417/overview

Not clear if there are crashes in other backends as well since several tests were not run due to https://github.com/flutter/flutter/issues/147387.

I've reverted the roll and stopped the engine -> framework roll.

**Comment by jonahwilliams** [comment]
Fix needs to roll into frame work, but should be finished building. Closing for now.
