### ISSUE TITLE
issue with local auth in flutter

### ISSUE THREAD

**Issue by ammarbhatkar** [flutter/flutter#147561]
hello , iam usin local auth to enable biometric lock in my flutter apk but it only works for fingerprint in my android apk , i tried with example code given my by them still only works for fingerprint but if i have only face enrolled it prompts the dialog of no biometric enrolled my android version is 11 

what is wrong with it ?

**Comment by darshankawar** [comment]
@ammarbhatkar 
What does `getAvailableBiometrics()` return in your case ? Empty list ?
Also, you may be hitting https://github.com/flutter/flutter/issues/107210 and also note below:

Details of specific biometric methods are managed by the OS+device; the plugin can't control the specific method using the available OS APIs.

**Comment by ammarbhatkar** [comment]
It returns null .. even if the device only supports facelock and not fingerprint

**Comment by darshankawar** [comment]
I think you are hitting https://github.com/flutter/flutter/issues/117309 so please follow-up in it for further updates.
Closing as duplicate.
