### ISSUE TITLE
Codelabs - Building an animated responsive app layout with Material 3 - Changing the language changes the code

### ISSUE THREAD

**Issue by carretto** [flutter/flutter#147588]
### Steps to reproduce

In the codelabs https://codelabs.developers.google.com/codelabs/flutter-animated-responsive-layout#3 change to
https://codelabs.developers.google.com/codelabs/flutter-animated-responsive-layout?hl=pt-br#3

### Expected results

The expected result to facilitate the implementation of the project is that the guidelines are translated, but the code remains the same.

### Actual results

When the language is changed from English to Brazilian Portuguese, the example code is changed to a broken version.

![image](https://github.com/flutter/flutter/assets/1786588/bf509aa6-25b9-4c86-a2d4-3ff806243a64)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. cc @domesticmouse

**Comment by domesticmouse** [comment]
Please use the English version. I don't have the translation budget to keep the alternate languages up to date.

**Comment by domesticmouse** [comment]
@carretto Is this still an issue post I/O update?

**Comment by carretto** [comment]
@domesticmouse I did a test today, and the problem persists. The code presented in lib/widgets/email_list_view.dart is the same for the codelab configured in English (original) and Deutsch. However, there are some lines altered for other languages such as Spanish, Brazilian Portuguese, French, and Indonesian.

**Comment by domesticmouse** [comment]
I'll delete the languages that haven't been updated.

**Comment by domesticmouse** [comment]
Out of date translations dropped. Thank you!
