### ISSUE TITLE
[iOS] App crashes on start with following error "/Runner.app/Frameworks/shared_preferences_foundation.framework/shared_preferences_foundation (built for iOS 17.0 which is newer than running OS)"

### ISSUE THREAD

**Issue by takla21** [flutter/flutter#147672]
### Steps to reproduce

1. Start a new project
2. Install `shared_preference`
3. Deploy on an iphone with IOS 16

### Expected results

I would assume the app should not crash on iPhone with iOS 12+

### Actual results

The app crashes on start (debug & release) when on Iphone 16 and lower.

### Code sample

I've created a sample app here: https://github.com/takla21/sharedprefios16

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on {iphone name} in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: {project ID}
Xcode build done.                                           15.6s
(lldb) dyld[7114]: Symbol not found: _swift_getTypeByMangledNameInContext2
  Referenced from: <ED67EF14-8C14-3302-B592-4978879B10B9> /private/var/containers/Bundle/Application/{app_ID}/Runner.app/Frameworks/shared_preferences_foundation.framework/shared_preferences_foundation (built for iOS 17.0 which is newer than running OS)
  Expected in:     <A4BFC1B8-03AE-323B-A302-D8832F75642A> /usr/lib/swift/libswiftCore.dylib
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001bdd4dfcc dyld`__abort_with_payload + 8
dyld`:
->  0x1bdd4dfcc <+8>:  b.lo   0x1bdd4dfec               ; <+40>
    0x1bdd4dfd0 <+12>: pacibsp
    0x1bdd4dfd4 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1bdd4dfd8 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Error launching application on {iphone name}.
 
 
Exited (1).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-CA)
    • Flutter version 3.19.2 on channel stable at /Users/kevintakla/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (9 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
 
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
 
 
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0
 
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
 
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
 
[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0
 
[✓] Connected device (3 available)
    • iPhone 15 (mobile) • 836D1D07-C36D-406E-86C4-48F095697B05 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 90.0.4430.212
 
[✓] Network resources
    • All expected network resources are available.
 
! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @takla21 
I checked this issue on my device `iPhone 7, iOS 15.8` but the crash didn't occur (using your sample project and also my test project).  I'm on the latest Flutter stable channel 3.19.6. Could you share the entire output of `flutter run -v`?

**Comment by takla21** [comment]
Here you go @huycozy

[run.txt](https://github.com/flutter/flutter/files/15189750/run.txt)

Executed on my Iphone SE 2020 iOS 16.5

**Comment by huycozy** [comment]
Thanks for providing it. I see the error as above, but can't see any other clues. I also asked my colleague check this on his M1 host machine with iOS 17.4.1 device but the issue also didn't occur. I will label this issue for other's input.

**Comment by jmagman** [comment]
You explicitly set your version to 17.0:
https://github.com/takla21/sharedprefios16/blob/0525f66118ca7e5f008ccdf3b05e26fe35914ade/ios/Runner.xcodeproj/project.pbxproj#L457
and in other places, 15.0:
https://github.com/takla21/sharedprefios16/blob/0525f66118ca7e5f008ccdf3b05e26fe35914ade/ios/Runner.xcodeproj/project.pbxproj#L666

`flutter create` sets the minimum to 12.0:
https://github.com/flutter/flutter/blob/5bac0de9e37f82f4bcd9c33ab4d3d0a9ce8a91ee/packages/flutter_tools/templates/app_shared/ios-swift.tmpl/Runner.xcodeproj/project.pbxproj.tmpl#L365

You should figure out what version you actually want to target, and then either follow the [instructions](https://docs.flutter.dev/deployment/ios#review-xcode-project-settings) under  **iOS Deployment Target**, and be consistent.
