### ISSUE TITLE
The `flutter update-packages --force-upgrade` command fails and it can't find `_macros` package

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#147656]
## Description

If you run `flutter update-packages --force-upgrade`, it will crash silently before completing, and the pubspec.yaml files it leaves modified will not work in a subsequent call to `flutter update-packages` because the `_macros` package is private and only part of the SDK, and not published, yet it gets pulled in as part of an added dependency of the analyzer package, since it depends on the public pre-release version of the `macros` package.

**Comment by christopherfujino** [comment]
FYI there's a tracking issue for the failing silently. If you run `flutter update-packages --force-upgrade` you should see pub solve errors.
