### ISSUE TITLE
Apple Finance Kit

### ISSUE THREAD

**Issue by aayushchhabra1999** [flutter/flutter#147615]
### Use case

Building Financial Applications that consume Apple Wallet and Apple Cash needs access to Apple Finance Kit.

### Proposal

Apple recently released a new API - FinanceKit for ios 17.3+
https://developer.apple.com/documentation/financekit

Since very recent, the support for this is not in Flutter yet. Should this be added as part of the standard packages Flutter supports?

https://docs.flutter.dev/platform-integration/ios/apple-frameworks

**Comment by jmagman** [comment]
Thanks for the issue!  This isn't something we would build a first-party plugin for, and it would be best implemented by the community: https://docs.flutter.dev/packages-and-plugins/developing-packages

Closing as out of scope for the Flutter team.
