### ISSUE TITLE
[CP] Widgets not resizing (disappear) with browser zoom in / out on Web

### ISSUE THREAD

**Issue by slavap** [flutter/flutter#147617]
### Steps to reproduce

This is a continuation of the previous https://github.com/flutter/flutter/issues/129182
I don't know any meaningful way to convince the engine developers to cherry-pick the fix into 3.19 Flutter version.
It is impossible to wait any longer, this bug has already been present for about a year!

@ditman @yjbanov 
Please cherry-pick it to 3.19, it is impossible to wait any longer, I understand you hate to deal with html renderer, but we need this fix to solve the problem with existing and working applications.

### Expected results

Must be cherry picked.

### Actual results

No fix for the very long time.

### Code sample

See https://github.com/flutter/flutter/issues/129182

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19045.4291], locale en-US)
    • Flutter version 3.19.6 on channel stable at c:\Programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (13 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\slavap\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = c:\Programs\chrome-debug.bat

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.88.1)
    • VS Code at C:\Users\slavap\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.86.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4291]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.60
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by huycozy** [comment]
Hi @slavap, next time you can use the [cherry-pick template](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&projects=&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E) instead.

Since https://github.com/flutter/flutter/issues/129182 has been fixed, I will mark this as a cherry-pick request.

**Comment by slavap** [comment]
@huycozy thanks!

**Comment by itsjustkevin** [comment]
With the release of 3.22, we are not longer taking cherry-picks for 3.19.

**Comment by slavap** [comment]
@itsjustkevin wonderful strategy 👎  just wait for next release - and no need to cherry pick anything. 3.19 is stable, but 3.22 will take at least a month to become stable enough, but you just force us to upgrade right away, nice.

**Comment by itsjustkevin** [comment]
@slavap I understand your frustration, however we only provide hotfixes to the latest stable.  Please see https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md
