### ISSUE TITLE
Kernel snapshot input dependency tracking not working

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#147643]
Haven't bisected this, but https://github.com/flutter/flutter/pull/147158 seems like the suspect.

Steps to reproduce:

```
flutter create -e test_1
cd test_1
flutter run -d macos
```
quit the application, modify the dart file

```
flutter run -d macos
```
Second run will not reflect modifications. 

I'm guessing the problem is that after change the dart inputs are written into `kernel_snapshot_program.stamp`, while `kernel_snapshot.stamp` is empty, which causes the `KernelSnapshot` target (and thus the dependencies) skipped.

/cc @dcharkes, @christopherfujino

**Comment by dcharkes** [comment]
Thanks for the report @knopp!

Fix underway:

* https://github.com/flutter/flutter/pull/147709
