### ISSUE TITLE
vended dart sdk is not well formed

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#14761]
It looks like the dart sdk currently vended in the flutter sdk is not well formed from the POV of the `dart:` libraries. We no longer ship `dart:js` (and other) libraries in the `dart-sdk/lib/` directory, however, these libraries are still referenced from:

```
dart-sdk/lib/_internal/libraries.dart
dart-sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart
```

The analyzer in particular uses the libraries.dart file(s) as the source of record for what `dart:` libs are available, and doesn't like having a library referenced from that file which does not actually exist on disk.

cc'ing @aam, @tvolkert, @zanderso, who may be familiar with the change to pair down the dart: libraries.

**Comment by tvolkert** [comment]
How does this manifest to the user?

**Comment by devoncarew** [comment]
They don't see an analysis issue for referencing an import that doesn't exist (`Target of URI doesn't exist: 'dart:foo'.`. And, trying to jump to declaration on those import doesn't do anywhere (the analysis server doesn't return a result for the jump to decl call, and may by throwing an exception oder the covers).

But in any case, the analyzer (and other dart tools) use the libraries.dart files as the system of record for which dart: libraries the sdk has - the file really should be correct.

**Comment by tvolkert** [comment]
It should definitely be fixed - I'm just trying to determine if the impact on the user is serious enough that this should hold up a dev release and thus be labelled as "TODAY".  wdyt?

**Comment by devoncarew** [comment]
It'll impact users trying to do both flutter and non-flutter development. I think it's more of a correctness issue, were users will see some side effects, but no hard showstoppers.

We may want to have a separate conversation about how users would do both web and flutter development in the same project now. Previously they could use the flutter vended dart sdk for analysis. After this change - and without any further work on our part - they'll need to have the two types of projects loaded in separate IDE projects.

**Comment by tvolkert** [comment]
I think supporting web development from Flutter's Dart SDK is an explicit non-goal.  One of the things we're trying to optimize for is minimizing download times for the user to speed up the first-hour development experience (https://github.com/flutter/flutter/issues/14701 covers removing the web parts of the SDK to speed up this download time).

That said, do we have any way of knowing metrics on how our users are using the Dart SDKs from Flutter?

**Comment by devoncarew** [comment]
> I think supporting web development from Flutter's Dart SDK is an explicit non-goal.

Perhaps not directly, but in the past we have spent time making it easier to work across both web and flutter projects; specifically, making it possible to load both types of projects - and presumably shared code - in one IntelliJ window and having things just work. We may want to make sure we're making this change for product reasons and not in order to save some small d/l size.

> minimizing download times for the user to speed up the first-hour 

The web dart: libraries take perhaps 2-3MB uncompressed. This is in comparison to the several ~1 GB dependencies we have (xcode, android studio, cocoa pods, the engine artifacts, ...).

> That said, do we have any way of knowing metrics on how our users are using the Dart SDKs from Flutter?

Not that I'm aware of. Using flutter's version of the sdk is an easy way to keep your dart sdk up to date, and using it had been to-date the only way to do both web and flutter development from the same sdk.

**Comment by aam** [comment]
Looking at [libraries.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart) it seems that quite a few libraries there specifically marked as having `platforms: DART2JS_PLATFORM`. Given that, not sure why [same, single] libraries.dart included in Flutter engine dart sdk is not well formed. Would not 
 having that attribute provide enough information for analyzer to know which libraries makes sense in what(Flutter/web) context?

**Comment by zoechi** [comment]
In my setup I have a Flutter project and a shared project (later to be shared with a Angular web app) in the same IntelliJ window.
For running tests I already have to switch the Dart SDK in the settings between Flutter and shared 
otherwise I get an error.

**Comment by tvolkert** [comment]
> In the past we have spent time making it easier to work across both web and flutter projects; specifically, making it possible to load both types of projects - and presumably shared code - in one IntelliJ window and having things just work. We may want to make sure we're making this change for product reasons and not in order to save some small d/l size.

Making it easier for users to work across both platforms is a definite win.  I should have pointed out earlier, however, that it's not just download size that's driving my pushback.  Since the Dart SDK that's vended by Flutter is used to analyze Flutter apps, we want to make sure it matches the behavior of the runtime in the Flutter engine.  For example, it should recognize that it's an error for a Flutter app to import `dart:html`.  Conversely, it shouldn't allow an Angular app to import `dart:ui`.  Supporting both platforms in one SDK is very challenging to get right (we're running into that within Google, and we're far from having gotten it right).

> It sounds like we should build the platform SDK with a libraries.dart file that accurately reflects which libraries are supported by the platform SDK. That is, it wouldn't need entries for dart:js etc..

+1

**Comment by johnpryan** [comment]
The workaround for is was to switch to the "official" Dart SDK in IntelliJ, but any time Flutter is enabled for a project, it stomps over whatever Dart SDK was selected by the user: https://youtrack.jetbrains.com/issue/WEB-31595?query=created%20by:%20me

**Comment by johnpryan** [comment]
A small update on this: as a workaround to this; our team has resorted to copying the official dart SDK into the flutter repository, but this isn't working any more because Flutter enforces the Dart SDK snapshot version.  Here's what we are seeing:

```
compiler message: Wrong full snapshot version, expected 'c43eada86a2f4834d028602dc4840e01' found 'd72bf5003e5924b61a7943f58e7b6814'
```

So now there's some pain points around switching between Dart SDKs.

Is there a better way to edit multiple Dart projects (as modules) in the same intellij project using both the "official" Dart SDK and the flutter-provided SDK?

**Comment by devoncarew** [comment]
> Is there a better way to edit multiple Dart projects (as modules) in the same intellij project using both the "official" Dart SDK and the flutter-provided SDK?

I don't know of one unfortunately, but if you experiment and find one, I'm happy to help document that on flutter.io and elsewhere, and / or help make tooling changes to better support working on both types of projects.

**Comment by cbracken** [comment]
@jonahwilliams @yjbanov I'm assuming that the JS side of this is resolved? 

The Dart SDK we embed in Flutter's cache still has some significant differences from the standalone Dart (e.g. https://github.com/flutter/flutter/issues/18134, https://github.com/flutter/flutter/issues/43968).  That said, we have never advertised the Dart SDK built into Flutter as being a full Dart SDK that you could use for non-Flutter development, and in fact have gone to great lengths to abstract it away by having the flutter tool wrap the underlying pub or dartanalyzer, etc. commands. This has never been an officially-supported configuration — it’s embedded in a cache directory within the Flutter SDK and we’ve certainly tweaked and adjusted the contents multiple times over the years. I don’t think this is a policy we want to change. Instead we should be recommending that users who want to do server-side or web dev grab the official Dart SDK and ensuring IDE tooling handles this correctly.

I *do* think it's useful from a tooling/technical debt perspective to keep our internal Dart SDK as consistent as we can with the official Dart SDK, so I think it's work tracking individual issues.

@devoncarew aside from the JS support issues (which I suspect are now resolved @jonahwilliams and @yjbanov should be able to confirm) and the above two issues, can you file individual issues for specific things that need fixing?

**Comment by jonahwilliams** [comment]
The dart sdk needs to be well-formed because it is used by the flutter tool to build itself. Its possible we could remove that requirement by pre-building the flutter_tool on CI, but that itself is a whole can of worms.

As far as I know, this is the case today. The addition of JavaScript interop libraries was required in the sky_engine package that the analyzer uses to determine the set of dart libraries available to flutter applications.

**Comment by devoncarew** [comment]
I think we've added back in all the web related libraries and tooling at this point - the `libraries.dart` file is (I assume) now correct again.

**Comment by Hixie** [comment]
> The web dart: libraries take perhaps 2-3MB uncompressed. This is in comparison to the several ~1 GB dependencies we have (xcode, android studio, cocoa pods, the engine artifacts, ...).

FWIW, we are working to reduce those dependencies (e.g. finding a way to not required Xcode and Android Studio out of the box). When measuring binary size impact we should work from a baseline that excludes those artifacts.

**Comment by markusaksli-nc** [comment]
From the last few comments, I'm going to assume it's safe to close this.
