### ISSUE TITLE
[in_app_purchase] Return current subscription information

### ISSUE THREAD

**Issue by abbasihamed** [flutter/flutter#147633]
[in_app_purchase] I bought a subscription with sandbox on ios and now I want to know what my current subscription is when I open the app again. How can I do this?

await InAppPurchase.instance.restorePurchases(); 
I used it but it doesn't return anything for me and the stream doesn't change

**Comment by huycozy** [comment]
Hi @abbasihamed 
This is a known issue being tracked at https://github.com/flutter/flutter/issues/109523. Closing this issue as a duplicate, so please follow up on it for further updates.
