### ISSUE TITLE
Option to break on handled exceptions in Flutter framework

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1476]
_From @sethladd on January 12, 2016 17:5_

Was: https://github.com/dart-atom/dartlang/issues/630

Flutter handles most (all?) exceptions thrown from user code. This is usually pretty great, except when I'm debugging. I want my app to stop at the point of the exception, so I can work on fixing it.

Normally, the editor can break on unhandled exceptions. But for handled exceptions, we might need to do something "Flutter aware".

_Copied from original issue: flutter/atom-flutter#31_

**Comment by Hixie** [comment]
We could create a `debugBreakOnException` boolean in some low-level file and then have the various exception-catching methods call:
```dart
debugger(when: debugBreakOnExceptions);
```

**Comment by Hixie** [comment]
(and expose `debugBreakOnExceptions` as an extension that Atom can set)

**Comment by eseidelGoogle** [comment]
I'm not sure what this asking for.  @devoncarew added the ability to have Atom break on all exceptions, did that solve this?

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#462
