### ISSUE TITLE
flutter-devicelab-mac-3 is quarantined `Not enough free disk space on /. 204739.1mib < 204800.0mib`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#147676]
### Type of Request

infra task

### Infrastructure Environment

Devicelab bot

### What is happening?

Bot is currently quarantined 
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-3

**Comment by jmagman** [comment]
@kentnguyen99 are you able to vnc in and see what's filling up the machine?

**Comment by kentnguyen99** [comment]
Removing old directory to free up disk space, it is fine now.

**Comment by jmagman** [comment]
@kentnguyen99 what directory was removed? Do you know what was in it?

**Comment by kentnguyen99** [comment]
Directories have not been touched for year under /opt/flutter/xcode.

**Comment by jmagman** [comment]
Is that the Xcode cache? It needs to be manually cleaned up?

**Comment by kentnguyen99** [comment]
Not sure what is use for, it's usually occupy a lot of disk space so I just remove oldest directory that not been touched for while.
