### ISSUE TITLE
[web] Cannot use `renderer` run-time configuration in new `load` API.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#147610]
### Steps to reproduce

1. Create a demo Flutter app using the latest bootstrap, using the following `flutter_bootstrap.js`
   ```js
   {{flutter_js}}
   {{flutter_build_config}}
   
   _flutter.loader.load({
     config: {
       renderer: 'canvaskit',
     },
   });
   ```
2. Attempt to `flutter run`
3. Observe the following error in the browser:
   ```
   Uncaught (in promise) FlutterLoader could not find a build compatible with configuration and environment.
   ```

### Expected results

I'd expect the app to run.

### Actual results

It seems that when not specifying a `--web-renderer` in the command-line, the `flutter_build_config` variable does **not** populate information for the `html` or `canvaskit` renderers, only `auto`; making the `renderer` run-time JS Parameter useless.

### Code sample

(Included above)

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

This reproduces in the latest `master`, and probably has always reproduced since we introduced the new `load` API.

**Comment by ditman** [comment]
After talking to @eyebrowsoffire, two things:

1. If we're going to always "force" the `canvaskit` renderer, it's better to just build with `--web-renderer canvaskit` rather than relying on the run-time option.
2. [This code](https://github.com/flutter/engine/blob/main/lib/web_ui/flutter_js/src/loader.js#L94-L94) may need to be smarter if we want to support `auto` properly in the `flutter_build_config` variable.

**Comment by eyebrowsoffire** [comment]
Fixed in https://github.com/flutter/engine/pull/53231/files
