### ISSUE TITLE
Inconsistent Height Rendering for Korean Letters in Text Widgets

### ISSUE THREAD

**Issue by njovy** [flutter/flutter#147659]
The rendering height of text in Text widgets changes when a Korean string contains a space. This inconsistency causes the text baseline to vary within a Row widget, affecting UI alignment. The issue occurs on both iOS and Android platforms, indicating a problem with the text rendering engine in Flutter.

### Steps to reproduce

1. Create a new Flutter project.
2. In the main widget, add a Row widget.
3. Inside the Row, place two Text widgets with the same TextStyle.
4. Set the text of the first widget to a Korean string without spaces (e.g., "안녕하세요").
5. Set the text of the second widget to a Korean string with spaces (e.g., "안녕 하세요").

### Expected results

Both Text widgets should have the same baseline and the rendered height should be consistent between texts with and without spaces.

### Actual results

The Text widget containing a space shows a slightly different height and baseline, causing misalignment compared to the Text widget without a space.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  Widget buildRow(double size) {
    final style = TextStyle(
      fontSize: size,
    );
    return Row(
      children: [
        Text(
          "ㅋ",
          style: style,
        ),
        Text(
          "ㅋ ㅋ",
          style: style,
        ),
        Text(
          "ㅋ",
          style: style,
        ),
        Text(
          "H",
          style: style,
        ),
        Text(
          "H H",
          style: style,
        ),
        Text(
          "H",
          style: style,
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Inconsistent Height issue demo'),
        ),
        body: ListView(
          children: List.generate(100, (index) => buildRow(index + 10)),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20240502_033641](https://github.com/flutter/flutter/assets/1792070/c05c16b1-7438-4d54-9660-374705d02066)
![Screenshot_20240502_033713](https://github.com/flutter/flutter/assets/1792070/f8694003-ee98-4289-abfb-405cbe355e36)
![Simulator Screenshot - iPhone 14 Pro - 2024-05-02 at 03 50 22](https://github.com/flutter/flutter/assets/1792070/05d49e4c-0dcc-43e2-972e-9992b56795a4)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.5 22G74 darwin-x64, locale en-KR)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    ! CocoaPods 1.11.3 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment]
Hi @njovy 
This is similar to https://github.com/flutter/flutter/issues/120862 and it can be solved if we add these properties to Row:

```dart
crossAxisAlignment: CrossAxisAlignment.baseline,
textBaseline: TextBaseline.alphabetic,
```


![Screenshot 2024-05-02 at 16 45 06](https://github.com/flutter/flutter/assets/104349824/bfc753b8-62fa-47ea-ba99-181f0d822648)

Closing as solved.
