### ISSUE TITLE
[Web] Support for vertical writing mode

### ISSUE THREAD

**Issue by natsuk4ze** [flutter/flutter#147728]
### [Modern browsers now support CSS vertical text input mode](https://coliss.com/articles/build-websites/operation/css/css-vertical-writing-mode-for-form.html)

Vertical writing is a common format in some parts of Asia, such as Japan, China and Korea. In Japan, for example, essentially all novels are published in vertical writing. Therefore, a vertical text editor has long been desired in the writers' community, but was very challenging due to CSS and browser issues.
Now, with Flutter web's support for this, a vertical text editor can be developed as desired by the writer's community.

The article above is in Japanese, but the HTML and CSS code should be helpful.

- [writing-mode: Vertically-oriented form controls](https://caniuse.com/mdn-css_properties_writing-mode_vertical_oriented_form_controls)
- [Saferi: Implementing Vertical Form Controls](https://webkit.org/blog/15190/implementing-vertical-form-controls/)
- [chrome: CSS vertical writing mode for form control elements ](https://developer.chrome.com/blog/vertical-form-controls)

### Proposal

https://github.com/flutter/flutter/assets/50433979/bf45c0e9-7ac9-4636-8493-464d971adaa9

**Comment by danagbemava-nc** [comment]
Closing this based on the comments below 
https://github.com/flutter/flutter/issues/14262#issuecomment-394897142
https://github.com/flutter/flutter/issues/15710#issuecomment-470418200

You can try this package to see if it suits your need https://pub.dev/packages/mongol but based on the comments above, it will require too much re-working of the framework for this to be considered. 

Thank you
