### ISSUE TITLE
[impeller] gpu benchmark probes have been accidentally disabled

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#147723]
https://github.com/flutter/engine/pull/52087 has caused some performance probes to drop to zero.

examples:
- 99th_percentile_gpu_frame_time
- worst_gpu_frame_time
- 90th_percentile_gpu_frame_time

<img width="1091" alt="Screenshot 2024-05-02 at 9 02 49 AM" src="https://github.com/flutter/flutter/assets/30870216/4303bf27-cac7-401c-9e6b-e039fbe9615f">

cc @chinmaygarde 

## skia perf

https://flutter-flutter-perf.skia.org/e/?begin=1713375187&end=1714657908&keys=Xdab252144b6c666305544d303f8161ea&requestType=0&selected=commit%3D40587%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-A025V%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_gpu_frame_time%252Ctest%253Danimated_blur_backdrop_filter_perf__timeline_summary%252C&xbaroffset=40591

**Comment by gaaclarke** [comment]
Also cc @jonahwilliams since I think he was the one that originally implemented those gpu probes.

**Comment by chinmaygarde** [comment]
Ah, I see what I missed. There are calls to the tracer deep in the KHR impl that I missed https://github.com/flutter/engine/blob/df2efe7f3896eda012000a8d08de461f4c4641ed/impeller/renderer/backend/vulkan/swapchain/khr/khr_swapchain_impl_vk.cc#L366. Will need to make that abstract and shared across impls.
