### ISSUE TITLE
et: can't authenticate

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#147739]
I'm unable to authenticate to perform RBE builds.

Things I've tried to address it:
1) restarted the computer
1) gcert

## log
```
$ cipd auth-login
$ gcloud init --project flutter-rbe-prod
$ ./flutter/bin/et build -c host_debug_unopt_arm64
[2024-05-02T12:51:01.591][macos/host_debug_unopt_arm64: GN]: OK
[2024-05-02 12:51:02.164921][macos/host_debug_unopt_arm64: RBE startup]: FAILED
COMMAND:
/Users/aaclarke/dev/engine/src/flutter/buildtools/mac-arm64/reclient/bootstrap --re_proxy=/Users/aaclarke/dev/engine/src/flutter/buildtools/mac-arm64/reclient/reproxy --automatic_auth=true --cfg=/Users/aaclarke/dev/engine/src/flutter/build/rbe/reclient-mac.cfg
STDOUT:

STDERR:
F0502 12:51:02.123954   13919 main.go:366] Failed to initialize credentials: failed to retrieve adc credentials: could not find Application Default Credentials: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information. Please check authentication options under go/reclient-internal-readme for more details or try running without --automatic_auth
```

cc @zanderso

**Comment by gaaclarke** [comment]
I tried replacing `'--automatic_auth` with `--use_google_prod_creds ` and `--use_gcloud_creds`.  Neither worked.

**Comment by zanderso** [comment]
We may be holding this wrong for local dev builds. Docs here go/rbe/dev/x/reclientoptions#authentication-mechanisms.

**Comment by gaaclarke** [comment]
I went through the documentation on my linux machine and it prompted me to run `gcert` then executed just fine.  Besides the different OS, on linux I was using the gcloud executable that comes from DEPS, on macos I already had it installed.

**Comment by gaaclarke** [comment]
On my mac I tried switching my PATH to point to the `gcloud` from DEPS and it still has the authentication problem.

**Comment by gaaclarke** [comment]
Fixed it, I had to run `gcloud auth application-default login` in order to setup the `Application Default Credentials`.  I didn't need that on linux, but needed it on mac.
