### ISSUE TITLE
 Problem with users paying via combini (Japan)

### ISSUE THREAD

**Issue by ZeroToNine09** [flutter/flutter#147779]
### Steps to reproduce

I have a problem with users paying via combini (Japan).
Those who pay via combini will then be automatically refunded by Google Play.
It seems that after changing the payment status to PurchaseStatus.purchased, it does not run to the logic of unlock feature.

I tested with the case slow test card according to the link below.
https://developer.android.com/google/play/billing/test#pending-purchases
And see the processing working normally.

I think the behavior of paying via combini is similar to slow test card.

### Expected results

After changing the payment status to PurchaseStatus.purchased, it should run to the logic of unlock feature.

### Actual results

It seems that after changing the payment status to PurchaseStatus.purchased, it does not run to the logic of unlock feature.

### Code sample

  ```
final Stream purchaseUpdated = InAppPurchase.instance.purchaseStream;
  _subscription = purchaseUpdated.listen((purchaseDetailsList) {
      purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {
        if (purchaseDetails.status == PurchaseStatus.pending) {
          // Update UI and return
          return;
        }

        if (purchaseDetails.status == PurchaseStatus.purchased || purchaseDetails.status == PurchaseStatus.restored) {
          // Handle receipt and unlock feature

          if (purchaseDetails.pendingCompletePurchase) {
            await InAppPurchase.instance.completePurchase(purchaseDetails);
          }
          return;
        }

          // Handle for others PurchaseStatus
    }, onDone: () {
      _subscription.cancel();
    }, onError: (error) {
        // Handle error
      }
    });
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @ZeroToNine09 
As my understanding, combini is a convenience store and assume that they support Google Play purchase on POS machine that runs Android OS, correct?

Could you check this on Android mobile device to see any different results? 

For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Also, please provide the version of package you are using. Thanks!
