### ISSUE TITLE
[Impeller] 60% regression in platform view `99th_percentile_frame_rasterizer_time_millis`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#147721]
Seen as a result of https://github.com/flutter/engine/pull/52087, which also [reduced the average raster time](https://github.com/flutter/engine/pull/52087#issuecomment-2090811311).

cc @chinmaygarde

<img width="841" alt="Screenshot 2024-05-02 at 8 50 41 AM" src="https://github.com/flutter/flutter/assets/30870216/1eb1614d-c954-4807-be0a-c40b7833790b">

## skiaperf
https://flutter-flutter-perf.skia.org/e/?keys=X8e0f283bd245579f658fe8ba511be98c&selected=commit%3D40591%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-A025V%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dplatform_views_scroll_perf_impeller__timeline_summary%252C&xbaroffset=40591

**Comment by chinmaygarde** [comment]
This may be related to the pending sema count being too low. The thing @jonahwilliams has a patch out for. Commuting ATM but can take a look soon.

**Comment by gaaclarke** [comment]
Here are some other benchmarks that were also negatively impacted, same sorts of thing, worst frame and 90th percentile:

https://flutter-flutter-perf.skia.org/e/?begin=1714584557&end=1714609103&keys=X2c8a2b0e7b78379b8c90932639e44938&num_commits=50&request_type=1&xbaroffset=40591

**Comment by gaaclarke** [comment]
Here's another that measure missed vsyncs:
https://flutter-flutter-perf.skia.org/e/?keys=Xbfa02752ec0e9e7569132e83baea9ae6&selected=commit%3D40592%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-A025V%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_vsync_transitions_missed%252Ctest%253Danimated_blur_backdrop_filter_perf__timeline_summary%252C&xbaroffset=40592

**Comment by jonahwilliams** [comment]
Its worth looking at all of the frame percentiles for this benchmark

![image](https://github.com/flutter/flutter/assets/8975114/7308b7df-3cce-4aac-a603-8b62449e0c7a)

The split here is odd. it looks like the average frame finishes much faster while the worst frames get much slower due to waiting on the semaphore. We should see if this device does better with backpressure enabled, or if we need to adjust semaphore and swapchain image counts.

**Comment by jonahwilliams** [comment]
Closing as we backed out the change and the benchmark has recovered.
