### ISSUE TITLE
[go_router] make the RouteMatch available in builder functions

### ISSUE THREAD

**Issue by quaaantumdev** [flutter/flutter#147716]
### Use case

Anytime somebody stacks two routes on top of each other, there is NO WAY no to understand which one "you" are on the stack when building the widget.

The issue in the implementation is, that ```_CustomNavigatorState``` converts the ```RouteMatch``` to a ```GoRouteState``` without exposing the ```RouteMatch``` itself to the ```route.pageBuilder``` or ```route.builder```. The ```GoRouter.of(context).routerDelegate.currentConfiguration``` carries the updated stack already, but there is no way to identify which one we're building there.

One may choose to do some (dirty) kind of matching based on the parameters, but this is obviously prone to errors.

Is there any reason, the ```RouteMatch``` is not exposed? It seems necessary to understand the current structure.

### Proposal

Inside ```_CustomNavigatorState```, forward the ```RouteMatch``` as a paramter to the ```route.builder``` and ```route.pageBuilder```. Or probably even better, make the match available via the already provided ```GoRouterState``` object. I just forked it and did exactly that, here is the commit: https://github.com/quaaantum/packages/commit/2933bdcc80557c8eafea42e505dd66e2a3b8934c

(I did not format the code in my commit to make the changes as simple as possible)

**Comment by patrikbadanjak** [comment]
Say I'm on _/bookings/12345_ in my app and then navigate to _/bookings/54321_, would your fix help me detect that the previous route was /12345 inside the pageBuilder?

**Comment by chunhtai** [comment]
Can you talk about more What information in the RouteMatch is not exposed in the pageBuilder and what are the use cases that require these information?
