### ISSUE TITLE
SegmentedButton: Proposal to modify / update redundant usage of `if` statement implementation

### ISSUE THREAD

**Issue by YukiAttano** [flutter/flutter#147781]
### Use case

The _SegmentedButtonDefaultsM3 class in segmented_button.dart has a style getter that constructs a ButtonStyle object that has multiple if statements that do nothing.
As you can see in the screenshot, they all return the same value as if they wouldn't be used.

![grafik](https://github.com/flutter/flutter/assets/85680862/54bd0c7e-28c4-4e97-a799-e1b950778638)

P.S: sorry if this in the wrong section.

### Proposal

As this code is autogenerated, it might exist more locations like this.

**Comment by FusoraTech** [comment]
Sadly, as you noticed, it can't be manually adjusted, the script at dev/tools/gen_defaults/bin/gen_defaults.dart should be modified to be smart enough to omit such kind of redundancy.

A better result for [this segment of code](https://github.com/flutter/flutter/blob/b8abc106892173c0246dd143bbe555bdb98596e6/packages/flutter/lib/src/material/segmented_button.dart#L999) could be:

```dart
  @override ButtonStyle? get style {
    return ButtonStyle(
      textStyle: MaterialStatePropertyAll<TextStyle?>(Theme.of(context).textTheme.labelLarge),
      backgroundColor: MaterialStateProperty.resolveWith((Set<MaterialState> states) {
        // if (states.contains(MaterialState.disabled)) {
        //   return null;
        // }
        if (states.contains(MaterialState.selected)) {
          return _colors.secondaryContainer;
        }
        return null;
      }),
      foregroundColor: MaterialStateProperty.resolveWith((Set<MaterialState> states) {
        if (states.contains(MaterialState.disabled)) {
          return _colors.onSurface.withOpacity(0.38);
        }
        if (states.contains(MaterialState.selected)) {
          // if (states.contains(MaterialState.pressed)) {
          //   return _colors.onSecondaryContainer;
          // }
          // if (states.contains(MaterialState.hovered)) {
          //   return _colors.onSecondaryContainer;
          // }
          // if (states.contains(MaterialState.focused)) {
          //   return _colors.onSecondaryContainer;
          // }
          return _colors.onSecondaryContainer;
        } else {
          // if (states.contains(MaterialState.pressed)) {
          //   return _colors.onSurface;
          // }
          // if (states.contains(MaterialState.hovered)) {
          //   return _colors.onSurface;
          // }
          // if (states.contains(MaterialState.focused)) {
          //   return _colors.onSurface;
          // }
          return _colors.onSurface;
        }
      }),
```

**Comment by TahaTesser** [comment]
Hi @YukiAttano 
As @FusoraTech mentioned, this is generated  from code. 

While the values night look similar, the tokens used to generate these values are quite different. This will surely, regardless of the value, we're generating colors specified in the specs. This is important if the token value database is updated the generated code will not fail.

https://github.com/flutter/flutter/blob/f94b1e1fc80aff996460354c0d43dfedd0372230/dev/tools/gen_defaults/lib/segmented_button_template.dart#L83-L106


I believe this is working as design. please refer to the gen_defaults for more details on the token and their values.
