### ISSUE TITLE
Sensor_plus package add to macOs.

### ISSUE THREAD

**Issue by Vinesh0187** [flutter/flutter#147705]
### Use case

Our team was developing an fitness app where , we want to track the user's steps so we used sensor_plus package but it was not allowing to use on macOs.

### Proposal

Our team was developing an fitness app where , we want to track the user's steps so we used sensor_plus package but it was not allowing to use on macOs.

**Comment by danagbemava-nc** [comment]
`sensors_plus` is not maintained by the flutter team but the flutter community instead. This issue should be reported on their repo https://github.com/fluttercommunity/plus_plugins/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc. 

Closing from here. 

Thank you
