### ISSUE TITLE
et: debug symbols have incorrect paths

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#147750]
The paths in the debug symbols for `et` builds are not valid which makes debugging them difficult.  I don't know of a workaround yet.

platform: macos
type: cppdbg
MIMode: lldb

## steps to reproduce
1) build `impeller_unittests` with `et`
1) in vscode set a symbolic breakpoint
1) execute `impeller_unittests` in the vscode debugger
1) when the breakpoint is hit, notice that the stacktrace has the correct symbols, but clicking on the stack frames does not jump to the proper file.  The path is something like `b/f/w/flutter/impeller/aiks/canvas.cc`, not a valid path.

## screenshot
<img width="1188" alt="Screenshot 2024-05-02 at 3 01 35 PM" src="https://github.com/flutter/flutter/assets/30870216/732a39be-f317-4963-8ce6-999cd1e41c72">

cc @chinmaygarde @zanderso

**Comment by jason-simmons** [comment]
I was able to get this to work on Linux with this setup:

* build a `host_debug_unopt` build using RBE with`et`
  * (added the `host_debug_unopt` config in https://github.com/flutter/engine/commit/ce644e74128a9b4df0a64b4d13ecc7efe13d743e)
* created a `src/flutter/.vscode/launch.json` file containing:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "TestLaunch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/../out/host_debug_unopt/exe.unstripped/impeller_unittests",
            "cwd": "${workspaceFolder}/../out/host_debug_unopt"
       }
    ]
}
```
* Open the `src/flutter` folder in VSCode and click "Run/Start Debugging" in VSCode to launch the executable under gdb

The object files built with RBE did contain symbols where the source file paths started with the `/b/f/w/set_by_reclient` prefix.

But VSCode did trigger on breakpoints set in the editor.  And it was able to open the correct source files and lines when clicking on frames in the stack trace.

**Comment by jonahwilliams** [comment]
We're not sure how to fix this, gdb can handle this though.

Canonicalize working dir = true might be related. Should these paths be relative?

**Comment by zanderso** [comment]
We need to add this stuff from the Dart build to the Flutter build: https://github.com/dart-lang/sdk/blob/main/build/config/gcc/BUILD.gn#L51

**Comment by gaaclarke** [comment]
I figured out how one can verify if the paths are correct (or incorrect in this case, see /b/w/f/ paths below):
```
lldb out/host_debug_unopt_arm64/impeller_unittests
(lldb) image lookup -vn impeller::Canvas::Save
2 matches found in /Users/aaclarke/dev/engine/src/out/host_debug_unopt_arm64/impeller_unittests:
        Address: impeller_unittests[0x00000001034d74b0] (impeller_unittests.__TEXT.__text + 55402976)
        Summary: impeller_unittests`impeller::Canvas::Save(bool, unsigned int, impeller::BlendMode, std::_fl::shared_ptr<impeller::ImageFilter> const&) at canvas.cc:222
         Module: file = "/Users/aaclarke/dev/engine/src/out/host_debug_unopt_arm64/impeller_unittests", arch = "arm64"
    CompileUnit: id = {0x00000000}, file = "/b/f/w/flutter/impeller/aiks/canvas.cc", language = "<not loaded>"
       Function: id = {0x7fc000ee8a5}, name = "impeller::Canvas::Save(bool, unsigned int, impeller::BlendMode, std::_fl::shared_ptr<impeller::ImageFilter> const&)", mangled = "_ZN8impeller6Canvas4SaveEbjNS_9BlendModeERKNSt3_fl10shared_ptrINS_11ImageFilterEEE", range = [0x00000001034d74b0-0x00000001034d7780)
       FuncType: id = {0x7fc000ee8a5}, byte-size = 0, decl = canvas.h:213, compiler_type = "void (_Bool, uint32_t, enum impeller::BlendMode, const class std::shared_ptr<class impeller::ImageFilter> &)"
         Blocks: id = {0x7fc000ee8a5}, range = [0x1034d74b0-0x1034d7780)
      LineEntry: [0x00000001034d74b0-0x00000001034d74f4): /b/f/w/flutter/impeller/aiks/canvas.cc:222
         Symbol: id = {0x000acf25}, range = [0x00000001034d74b0-0x00000001034d7780), name="impeller::Canvas::Save(bool, unsigned int, impeller::BlendMode, std::_fl::shared_ptr<impeller::ImageFilter> const&)", mangled="_ZN8impeller6Canvas4SaveEbjNS_9BlendModeERKNSt3_fl10shared_ptrINS_11ImageFilterEEE"
       Variable: id = {0x7fc000ee922}, name = "this", type = "impeller::Canvas *", valid ranges = <block>, location = DW_OP_breg31 WSP+152, decl = 
       Variable: id = {0x7fc000ee930}, name = "create_subpass", type = "bool", valid ranges = <block>, location = DW_OP_breg31 WSP+151, decl = canvas.cc:219
       Variable: id = {0x7fc000ee93f}, name = "total_content_depth", type = "uint32_t", valid ranges = <block>, location = DW_OP_breg31 WSP+144, decl = canvas.cc:220
       Variable: id = {0x7fc000ee94e}, name = "blend_mode", type = "BlendMode", valid ranges = <block>, location = DW_OP_breg31 WSP+143, decl = canvas.cc:221
       Variable: id = {0x7fc000ee95d}, name = "backdrop_filter", type = "const std::_fl::shared_ptr<impeller::ImageFilter> &", valid ranges = <block>, location = DW_OP_breg31 WSP+128, decl = canvas.cc:222
       Variable: id = {0x7fc000ee96c}, name = "entry", type = "CanvasStackEntry", valid ranges = <block>, location = DW_OP_fbreg -136, decl = canvas.cc:223
        Address: impeller_unittests[0x00000001034d7414] (impeller_unittests.__TEXT.__text + 55402820)
        Summary: impeller_unittests`impeller::Canvas::Save(unsigned int) at canvas.cc:184
         Module: file = "/Users/aaclarke/dev/engine/src/out/host_debug_unopt_arm64/impeller_unittests", arch = "arm64"
    CompileUnit: id = {0x00000000}, file = "/b/f/w/flutter/impeller/aiks/canvas.cc", language = "c++14"
       Function: id = {0x7fc000efdbc}, name = "impeller::Canvas::Save(unsigned int)", mangled = "_ZN8impeller6Canvas4SaveEj", range = [0x00000001034d7414-0x00000001034d74b0)
       FuncType: id = {0x7fc000efdbc}, byte-size = 0, decl = canvas.h:79, compiler_type = "void (uint32_t)"
         Blocks: id = {0x7fc000efdbc}, range = [0x1034d7414-0x1034d74b0)
      LineEntry: [0x00000001034d7414-0x00000001034d7440): /b/f/w/flutter/impeller/aiks/canvas.cc:184
         Symbol: id = {0x000acec5}, range = [0x00000001034d7414-0x00000001034d74b0), name="impeller::Canvas::Save(unsigned int)", mangled="_ZN8impeller6Canvas4SaveEj"
       Variable: id = {0x7fc000efdd6}, name = "this", type = "impeller::Canvas *", valid ranges = <block>, location = DW_OP_breg31 WSP+32, decl = 
       Variable: id = {0x7fc000efde3}, name = "total_content_depth", type = "uint32_t", valid ranges = <block>, location = DW_OP_breg31 WSP+28, decl = canvas.cc:184
```

**Comment by chinmaygarde** [comment]
On Android, I am seeing the following prefix on all paths which is messing some backtrace parsing tools: `/b/f/w/set_by_reclient/a/../../flutter/fml/logging.cc`. I don't know where the `set_by_reclient/a` is coming from but I don't see that on macOS.

**Comment by gaaclarke** [comment]
@chinmaygarde With Zach's PR, if I use dsymutil to extract the .dSYM files, then use dwarfdump to look at the dSYM files I get something like this:
```
impeller_unittests.dSYM/Contents/Resources/DWARF/impeller_unittests:    file format Mach-O arm64

.debug_info contents:
0x00000000: Compile Unit: length = 0x0003c0eb, format = DWARF32, version = 0x0004, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0003c0ef)

0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("Fuchsia clang version 18.0.0 (https://llvm.googlesource.com/llvm-project 725656bdd885483c39f482a01ea25d67acf39c46)")
              DW_AT_language    (DW_LANG_C_plus_plus_14)
              DW_AT_name        ("../../flutter/impeller/base/base_unittests.cc")
              DW_AT_LLVM_sysroot        ("../../flutter/prebuilts/SDKs/MacOSX14.4.sdk")
              DW_AT_APPLE_sdk   ("MacOSX14.4.sdk")
              DW_AT_stmt_list   (0x00000000)
              DW_AT_comp_dir    ("/b/f/w/set_by_reclient/a")
              DW_AT_low_pc      (0x00000001000012d0)
              DW_AT_ranges      (0x00000b70
                 [0x00000001000012d0, 0x0000000100030774))
```

`DW_AT_name` seems right.  The `DW_AT_comp_dir` is wrong when considering the comment in Zach's PR.  There is the path you were looking for.

**Comment by gaaclarke** [comment]
Oh, but look `path.join(DW_AT_comp_dir, DW_AT_name)` gives us `/b/f/w/flutter/impeller/base/base_unittests.cc`, which matches what I'm seeing in `lldb`.  It just seems like if we can get that flag setting `DW_AT_comp_dir` we should be good.  `et` doesn't let you debug what is getting sent to the compiler which makes it hard to know what's happening (https://github.com/flutter/flutter/issues/147894).

**Comment by zanderso** [comment]
There's a problem with following the approach from the Dart build that I linked in https://github.com/flutter/flutter/issues/147750#issuecomment-2096632542.

That approach only works if the build is entirely local *or* entirely remote. For better or worse, the most efficient execution strategy for RBE, esp. from a slower network connection, is to use a remote-with-local-fallback or a racing strategy. In those strategies, the successful compilation could be either the result of a local compilation or a remote compilation. There are flags to `rewrapper` to supply a local wrapper script and a remote wrapper script. I think we'll have to use those wrapper script options to supply the correct `-fdebug-prefix-map` flag.

**Comment by zanderso** [comment]
@gaaclarke As far as I can tell, https://github.com/flutter/engine/pull/52632 should address this issue with the limitation that the debug info doesn't have absolute paths anymore. Could you verify that that's also what you're seeing after pulling up to tip-of-tree? Thanks!

**Comment by gaaclarke** [comment]
I verified that it worked with my old VSCode debugger flow.  The source remap wasn't required.  Awesome, thanks @zanderso.
