### ISSUE TITLE
[web] integration_test and driver tests are flaky in CanvasKit + debug mode

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#147731]
`integration_test` and `flutter drive` tests are flaky when running with `--web-renderer=canvaskit --debug`.

This is because there's an incompatibility between CanvasKit's and DDC's module loading systems. Both use requireJS, but there's a race that doesn't resolve cleanly.

Work is already underway on the Dart SDK side: https://github.com/dart-lang/sdk/issues/55429.

This issue is for tracking the Flutter-side changes.

This issue will supersede https://github.com/flutter/flutter/issues/146189. The P0 will be solved by temporarily turning off `--debug` mode test shards.

**Comment by eyebrowsoffire** [comment]
https://github.com/flutter/engine/pull/52023 landed, which I am fairly confident will eliminate the flakiness of these tests. Once they roll into the engine, I will look into re-enabling the debug integration tests.
