### ISSUE TITLE
[two_dimensional_scrollables] TableView can't scroll horizontally if rows fit on screen but columns don't.

### ISSUE THREAD

**Issue by isenbj** [flutter/flutter#147730]
### Steps to reproduce

1) Open this dartpad https://dartpad.dev/?id=4424936c57ed13093eb389123383e894
2) Set the maxYIndex to be something that fits fully on the screen so that vertical scrolling is not necessary.
3) Leave maxXIndex to be something that does not fit the screen so that horizontal scrolling is necessary to see all the columns.
4) Observe that you cannot drag to see all of the columns.
5) Observe that you can resize the screen so that the rows fall out of view and you need to vertical scroll to see them. Suddenly horizontal scrolling is enabled as well.

Note: I am using the given dartpad example here to demonstrate the issue. My personal issue is through using the TableView.builder, however the issue is the same.

Also:
I believe this issue was closed prematurely which is my same problem: https://github.com/flutter/flutter/issues/135384

The linked issue where it was claimed to be a duplicate is not related.

### Expected results

To be able to horizontal scroll when there are more columns than fit on screen, but the rows do fit.

### Actual results

Scrolling is not possible so a user cannot see all the columns.

### Code sample

<details open><summary>Code sample</summary>

https://dartpad.dev/?id=4424936c57ed13093eb389123383e894

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/49786150/07497e70-ab64-495a-856c-324794a7ea6d

</details>

### Logs

<details open><summary>Logs</summary>

Not needed

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Not needed

</details>

**Comment by darshankawar** [comment]
Thanks for the report @isenbj 
You'll be happy to know that the expected behavior works on latest master version, as shown below:


https://github.com/flutter/flutter/assets/67046386/2eb0d6d4-02b3-4bc8-afb5-c943028be8a1

The one where it doesn't work must be on stable. You may switch to master and re-run your scenario to confirm at your end as well.

**Comment by isenbj** [comment]
I can confirm it works on master for the example. I can't run master on my app though due to several dependency breaks with removal of different theming options (body1 -> bodyLarge for example). I can just use DiagonalDragBehavior.none rather than .free for now though.

**Comment by darshankawar** [comment]
Thanks for the update. Since it works on master, it is considered to be fixed and per our triage policy, will close as resolved.
