### ISSUE TITLE
Breakpoints skipped in unit tests when awaiting certain async calls

### ISSUE THREAD

**Issue by dastbayoo** [flutter/flutter#147790]
### Steps to reproduce

I was trying to debug a test and couldn't manage to get any of my breakpoints to pause so that I could investigate the local values or to debug the expect statements step by step. I boiled it down to a minimal scenario (see also code below).

1. Create class A with a dependency B, where A and B have async methods.
2. Create a test class for A and a mock for B, injecting B into A
3. In a test method, await the call to A's method and add breakpoints in that test method. Also add breakpoints within A.
4. Debug the test.

I am aware of #98446, which looks similar but my issue is that the dependency is required and breakpoints inside the tested code _do_ hit while some breakpoints _within_ my test method are missed.

I was coming from a Mocktail setup but with the inspiration of the minimal example in #98446 I managed to reproduce it without this dependency. 

### Expected results

All the breakpoints are hit and execution pauses for each of them.

### Actual results

The first breakpoint that hits is the one within A.

### Code sample

<details open><summary>Code sample</summary>
uut.dart

```dart
class Dependency {
  Future<void> foo() async {
    print('baz');
  }
}

class UUT {
  Dependency dependency;
  UUT(this.dependency);

  Future<void> bar() async {
    print("");
  }
}
```

uut_test.dart
```dart
import 'package:flutter_test/flutter_test.dart';
class Mock { Future<void> foo() async {} }
class DepMock extends Mock implements Dependency {}

void main() {
  late DepMock depMock;
  group('UUT', () {
    setUpAll(() {
      depMock = DepMock();
    });

    test('should print foo', () async {
      await UUT(depMock).bar();
      expect(true, true);
    });
  });
}

```

</details>
I experimented with some variations, some of which make a difference, some don't:

1. It doesn't matter if I use setUp or setUpAll
2. It doesn't matter if I remove the group
3. If I remove the `late` keyword and initialize the DepMock immediately, yet still assign it in the set it up again, the issue is gone!
4. If I make UUT not call dependency.bar(), and UUT.bar() is a synchronous void method, the issue is the same. It makes no difference if I then also remove the async keyword for the test.
5. If I inject "DepMock()" or "Dependency()", the issue is gone (probably related to the observation in 3)
6. If I split the test into 
 ```dart
var uut = UUT(depMock);
await uut.bar();
expect(true,true);
```
then my breakpoint misses the assignment but hits the ```await uut.bar()```.

Tested with Android Studio and Visual Studio code, to rule out an IDE issue. Also I enabled breaking on all thrown exceptions to ensure I'm not missing caught exception within the framework.

### Screenshots or Video

<details open>
<summary>The "expect" breakpoint hits, the one above is missed</summary>
```

![grafik](https://github.com/flutter/flutter/assets/43368060/fc603226-c24d-4ad1-b406-2bef045fb098)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.19045.4291], locale de-DE)
    • Flutter version 3.19.3 on channel stable at C:\Users\<username>\AppData\Local\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (8 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\<username>\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.34)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34601.136
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code, 64-bit edition (version 1.88.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4291]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.62
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.67

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @dastbayoo 
I think this would belong to dart-lang [repo](https://github.com/dart-lang/sdk/issues) since async and late keywords come from there. Also, the fact that the code doesn't contain flutter implementation but using dart code, it is replicable, I suggest you to open this in dedicated repo.
If you get directed here claiming this is flutter framework / tool issue, write in comments and I'll reopen it.

**Comment by dastbayoo** [comment]
Fair point. I thought it might be related to flutter_test but it actually also behaves the same with dart's test package. 👍
