### ISSUE TITLE
Unsolved Reference When Editing Flutter Plugin Androd Native Code

### ISSUE THREAD

**Issue by fadlurahmanfdev** [flutter/flutter#147826]
### Steps to reproduce

1. create flutter plugin project
`flutter create --template=plugin --platforms=android example_flutter_plugin`
2. open native code in Android studio
`${home}/example_flutter_plugin/android/build.gradle`

### Actual results

Unsolved reference FlutterPlugin, io, etc

<img width="862" alt="image" src="https://github.com/flutter/flutter/assets/164602276/9c809cec-1f3a-4158-95b7-ed9829e346ef">

### Logs

I alread follow step in this section https://docs.flutter.dev/packages-and-plugins/developing-packages#step-2b-add-android-platform-code-kt-java, but still I got error plugin

### Flutter Doctor output

`[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-ID)
    • Flutter version 3.19.5 on channel stable at /Users/taufikfadlurahmanfajari/fvm/versions/3.19.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (5 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/taufikfadlurahmanfajari/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (4 available)
    • SM G973F (mobile)                    • RR8M20LAB5L               • android-arm64  • Android 12 (API 31)
    • Taufik Fadlurahman’s iPhone (mobile) • 00008110-00124CA40230A01E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                      • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                         • chrome                    • web-javascript • Google Chrome 124.0.6367.119
    ! Error: Browsing on the local area network for Taufik’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
`

**Comment by fadlurahmanfdev** [comment]
there is duplicate issue here https://github.com/flutter/flutter/issues/115811, but in my computer, it cannot resolved

**Comment by stuartmorgan** [comment]
Please see https://github.com/flutter/flutter/issues/115811#issuecomment-1323366326. As noted in section 2b of the documentation you linked to, editing the native code of a plugin should be done in the example app project.
