### ISSUE TITLE
Web semantics picks up clicks instead of letting Flutter handle them (?)

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#147881]
Original comment by @ditman on https://github.com/flutter/flutter/issues/145849#issuecomment-2026518939:

> I've checked this a little bit and the problem seems to be that the semantics system is picking up clicks on that first row (in my mac it's 2 rows, it seems), instead of letting flutter handle them. We must not be computing the semantic target correctly on the clicks there (the underlying element seems to be correctly sized and positioned, though!) (??)
> 
> One potential workaround is to comment this out:
> 
> * https://github.com/flutter/cocoon/blob/7a67a76fd71d13fe9356e70b5501006371c514d7/dashboard/lib/main.dart#L71
> 
> But I think @yjbanov is going to be interested in this issue!

I am going to remove the line(s):

```dart
// Enable extensions like Vimium to traverse the dashboard
SemanticsBinding.instance.ensureSemantics();
```

... but I still wanted something the web team could track, as this seems like a fairly serious bug?

**Comment by yjbanov** [comment]
Deduplicating into https://github.com/flutter/flutter/issues/143164 and https://github.com/flutter/flutter/issues/146291
