### ISSUE TITLE
Flutter is developed in modules, and each module can run independently

### ISSUE THREAD

**Issue by LanSeLianMa** [flutter/flutter#147847]
### Document Link

https://github.com/LanSeLianMa/flutter_module_develop

### What problem are you solving?

I implemented module development by using Flutter's named routing method, and each module can run independently. My demo includes Provider.

1. Create a new empty folder
2. Create Flutter project module
3. Set the startup entrance for each Flutter project module
4. Associate them in pubspec.yaml

Step illustration:

1. Create a new empty folder

<img width="147" alt="01" src="https://github.com/flutter/flutter/assets/45938601/453ec244-053c-48eb-9f54-5eb3e4f7ed18">

2. Create Flutter project module

<img width="805" alt="02" src="https://github.com/flutter/flutter/assets/45938601/cbaffed4-1d84-4775-ba0c-61fdb9d0c7de">
<img width="802" alt="03" src="https://github.com/flutter/flutter/assets/45938601/0f66e6df-d5dd-42de-8c91-dfa81769e023">
<img width="802" alt="04" src="https://github.com/flutter/flutter/assets/45938601/2a2c9dd5-9d5d-4679-9697-c88572633d03">
<img width="802" alt="05" src="https://github.com/flutter/flutter/assets/45938601/85ccbe5d-77aa-4e8d-858c-a940515ca3be">
<img width="802" alt="06" src="https://github.com/flutter/flutter/assets/45938601/798c6e73-4bcf-48de-9874-4c248e2b9461">
<img width="766" alt="07" src="https://github.com/flutter/flutter/assets/45938601/e4a89371-f364-4275-a03d-4d2b554a9b3e">

3. Set the startup entrance for each Flutter project module

<img width="1339" alt="08" src="https://github.com/flutter/flutter/assets/45938601/8c3b523f-8822-47e3-a25b-b363484405c5">
<img width="1037" alt="09" src="https://github.com/flutter/flutter/assets/45938601/b11b0347-030d-4d8b-aaa8-4c64c26eb369">
<img width="1037" alt="10" src="https://github.com/flutter/flutter/assets/45938601/ffd7be12-e286-45de-a018-e17272f6aad2">
<img width="1037" alt="11" src="https://github.com/flutter/flutter/assets/45938601/cbf9e332-242e-44ec-9b01-03bd007b745c">

I will omit showing other module creation processes here because they are all the same.
<img width="1037" alt="12" src="https://github.com/flutter/flutter/assets/45938601/60776a66-7921-4de8-a485-0733866b8821">

4. Associate them in pubspec.yaml

4.1 common module adds dependencies
<img width="553" alt="13" src="https://github.com/flutter/flutter/assets/45938601/33fa74b3-ea85-436a-95a6-e02164f6c0e0">

4.2 home, order, personal modules pubspec.yaml dependencies common module
<img width="394" alt="14" src="https://github.com/flutter/flutter/assets/45938601/ad7b85cc-c24e-4be4-b765-e5f07718e35b">

4.3 the app module depends on the home, order, and personal modules
<img width="553" alt="15" src="https://github.com/flutter/flutter/assets/45938601/601a3ce1-fd82-4a98-b2e4-2c92c8334f08">

5. dependence mind map
<img width="564" alt="16" src="https://github.com/flutter/flutter/assets/45938601/41618d2c-0d6d-4916-8e31-d65e2f259eea">

6. final effect
![demo](https://github.com/flutter/flutter/assets/45938601/38119d66-d23c-488d-9a66-c6b22a6bd6e8)

demo link
https://github.com/LanSeLianMa/flutter_module_develop

I would like to ask if this Flutter development method can be formally applied in actual projects?

**Comment by AbdeMohlbi** [comment]
I think it would be helpful to explain when and how to use this by providing a use case. Imo, one of the tricky things about Flutter modules is that when your UI has multiple parts and you're using bloc or provider, each part ends up doing the same thing. So, if you update one part, it could mess up the whole project because you can't rely on two different versions of the same package

**Comment by AbdeMohlbi** [comment]
I think it would be helpful to explain when and how to use this by providing a use case. Imo, one of the tricky things about Flutter modules is that when your UI has multiple parts and you're using bloc or provider, each part ends up doing the same thing. So, if you update one part, it could mess up the whole project because you can't rely on two different versions of the same package

**Comment by LanSeLianMa** [comment]
I tried pictures and fonts, but they all failed. By default, it reads the package path of the startup module, which is com.example.app. I used the package attribute to make changes, but they all failed. Why is this? Is there any solution?

<img width="702" alt="17" src="https://github.com/flutter/flutter/assets/45938601/38d625ac-2ed8-4f0d-8c15-51b6df441cdd">
<img width="702" alt="18" src="https://github.com/flutter/flutter/assets/45938601/482b6c08-96c5-4bff-b5c3-c707991fd5e2">
<img width="589" alt="19" src="https://github.com/flutter/flutter/assets/45938601/932dfe72-7fc9-4585-ad90-7190fc4dc3c9">
<img width="467" alt="20" src="https://github.com/flutter/flutter/assets/45938601/7c41bcd4-cb8e-45c0-8618-ccf6e28948f9">

**Comment by indeedshaw** [comment]
Can it be understood that these modules are currently just plugins and not real modules?

**Comment by LanSeLianMa** [comment]
It is a real module and can be started independently, similar to Android native sub-module development.

**Comment by AbdeMohlbi** [comment]
> It is a real module and can be started independently, similar to Android native sub-module development.

Tbh he is right what we have here is a mix between the two kinda modules shaped inside a plugin

**Comment by LanSeLianMa** [comment]
> I think it would be helpful to explain when and how to use this by providing a use case. Imo, one of the tricky things about Flutter modules is that when your UI has multiple parts and you're using bloc or provider, each part ends up doing the same thing. So, if you update one part, it could mess up the whole project because you can't rely on two different versions of the same package Also imagine having to deal with gradle configuration for each one of ur modules when there is a breaking change like what happend in 3.16 Also i see a the bundle got 2.5 times bigger i don't think this is a good thing Maybee there is somewhere to fit just i don't see it

What does this bundle refer to? I created a new Flutter project. The packaged volume is 17.4MB, while the packaged volume of the multi-module Flutter project is 17.9MB. This volume should be acceptable, and there is no 2.5 times the volume.

<img width="601" alt="21" src="https://github.com/flutter/flutter/assets/45938601/6edb882a-d631-4428-89e0-26886b8b5d8b">
<img width="604" alt="22" src="https://github.com/flutter/flutter/assets/45938601/3ae22e76-dac4-41f8-bfdf-8cb31f0803e5">

**Comment by AbdeMohlbi** [comment]
See the project size in ur disk

**Comment by darshankawar** [comment]
Removing `design doc` label as it doesn't seem to be applicable here.

**Comment by AbdeMohlbi** [comment]
@LanSeLianMa 
Also is it possible to share variables between modules back and forth

**Comment by LanSeLianMa** [comment]
As long as it is added in the common module, other modules can access it, but the compiler will not prompt you. You need to import the package manually. However, when importing the package, the compiler will prompt you.

**Comment by AbdeMohlbi** [comment]
Hmmm Intersseting
 maybe a use case i can think about is to store some logic inside a seperate module not a ui component then it can be helpfull something like hashing or parsing 
What do u think?

**Comment by darshankawar** [comment]
> ask if this Flutter development method can be formally applied in actual projects?

@LanSeLianMa Can you elaborate when you say to formally apply in actual projects ? Are you proposing to add this as an option in the sdk itself ? By the looks of it and your findings so far, it seems there are lot of open end cases that you'll need to cover, consider and test before presenting the idea.

**Comment by LanSeLianMa** [comment]
> > 请问这种Flutter开发方式可以正式应用到实际项目中吗？
> 
> @LanSeLianMa您说要正式应用到实际项目中，能详细说明一下吗？您是否建议将其添加为 sdk 本身的选项？从它的外观和您迄今为止的发现来看，在提出这个想法之前，您似乎需要主题、考虑和测试许多开放式案例。
> 
> 另外，请检查[这](https://github.com/flutter/flutter/issues/39707)是否与您的情况相似。

No need to add it to the SDK, I just want to ask if this development method is feasible

**Comment by LanSeLianMa** [comment]
> @LanSeLianMa 嗯， 也许我能想到一个简单的逻辑存储在单独的模块而不是 ui 组件中，那么它可能会有帮助，例如散列或解析， 你觉得怎么样？

In fact, it is just to make the project structure clearer. The remaining problem is how to access local files across modules.

**Comment by darshankawar** [comment]
@LanSeLianMa 
I think this is better to be asked on discord channel for the feasibility rather than asking it here, because it doesn't seem to be a bug report or a feature request but a question whether this approach is feasible or not.

**Comment by LanSeLianMa** [comment]
Okay, do you have any recommendations for relevant platforms?

**Comment by LanSeLianMa** [comment]
Communities with more active official attention can also be used

**Comment by darshankawar** [comment]
@LanSeLianMa 
You may post the same in flutter's discord channels as mentioned [here](https://github.com/flutter/flutter/wiki/Design-Documents#soliciting-feedback).

**Comment by LanSeLianMa** [comment]
I choose Twitter

**Comment by LanSeLianMa** [comment]
This channel https://twitter.com/r_FlutterDev

**Comment by FusoraTech** [comment]
Discord: https://github.com/flutter/flutter/wiki/Chat

**Comment by LanSeLianMa** [comment]
OK, I have successfully entered the Flutter community channel

<img width="1271" alt="截屏2024-05-07 22 40 46" src="https://github.com/flutter/flutter/assets/45938601/1193897a-9909-4e8a-89ca-3675daef5532">

**Comment by darshankawar** [comment]
Closing from here as you can track and follow-up in other platforms to get feedback your on idea.
