### ISSUE TITLE
Directly access and communicate with printers on the Windows

### ISSUE THREAD

**Issue by overseasotc** [flutter/flutter#147811]
### Use case

Customizable Print Settings:
Duplex Printing: Support for double-sided printing.
Multiple Pages Per Sheet: Ability to print multiple pages on a single sheet (e.g., 2-up, 4-up).
Multiple Copies: Option to print multiple copies of a document.
Page Range Selection: Allow users to specify a range of pages to print.
Paper Size and Orientation: Support for different paper sizes and orientations.
Print Quality: Options to control print quality or resolution.

### Proposal

this could be provided by Flutter directly, or can it be provided
by a package on pub.dev

**Comment by darshankawar** [comment]
@overseasotc 
Check [this](https://github.com/flutter/flutter/issues/15457) issue and underlying comments along with [resolution](https://github.com/flutter/flutter/issues/15457#issuecomment-1262789659) from the team.
Closing based on it.
