### ISSUE TITLE
[flutter_markdown]  H1 not display correctly 

### ISSUE THREAD

**Issue by josermarinr** [flutter/flutter#147836]
### Steps to reproduce

Install flutter_markdown in your project
Use an # Heading level 1
the display is not the correctly

### Expected results

The size will be more highest than heading level 2

### Actual results

the size is more lowest than heading 6

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @josermarinr 
I checked this issue using [this example](https://github.com/flutter/packages/blob/main/packages/flutter_markdown/example/lib/demos/basic_markdown_demo.dart) on package examples but it rendered as expected, see demo on Web:

![Screenshot 2024-05-06 at 15 57 07](https://github.com/flutter/flutter/assets/104349824/b1bdcf79-4d4e-4a7b-aef8-e9ed0d6636c3)

What is your package version? Please also try that example and confirm.

**Comment by josermarinr** [comment]
Thank you @huycozy you are right I have the version   
`flutter_markdown: ^0.6.18+3`
