### ISSUE TITLE
[cocoon] Broken builds navigate to builders, not the broken build

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#147877]
## description
I've noticed that when clicking on broken builds in cocoon it will frequently jump to the builders website instead of displaying the popup that will allow you to navigate to the actual error.

## workaround
I found that resizing the web browser window will sometimes allow you to get the popup behavior if you are getting the "navigate to builders" behavior.

## screenshot
![builders](https://github.com/flutter/flutter/assets/30870216/7ed273ca-fa66-4784-90cd-61b2f4c83b38)

**Comment by gaaclarke** [comment]
Another clue is that the "navigate to builders" behavior is the one you should get when clicking on a columns header.  The erroneous "navigate to builders" may only happen on failures that are in the first couple of rows of a column.

**Comment by stuartmorgan** [comment]
This looks like https://github.com/flutter/flutter/issues/145849, but one row further down than usual.
