### ISSUE TITLE
[et] Forward `--verbose` to `ninja`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#147894]
With ninja you can use `--verbose` to debug the compiler invocations.  `et` doesn't have this option which made it impossible to verify that https://github.com/flutter/buildroot/pull/852 is sending the proper commands to the compiler.

**Comment by gaaclarke** [comment]
Jason got around this with `ps aux | egrep clang` while `et` was executing.

**Comment by matanlurey** [comment]
Great idea but duplicate of https://github.com/flutter/flutter/issues/145711 🖖🏼

**Comment by matanlurey** [comment]
See https://github.com/flutter/flutter/issues/145711#issuecomment-2097115956, but basically to make debugging easier, we should consider either forwarding `--verbose` to ninja (imply `ninja --verbose`), or add a flag that does that.
