### ISSUE TITLE
flutter-devicelab-mac-14 is quarantined: No device is available

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#147887]
Device healthcheck failed: attached_device: No device is available;

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-14

**Comment by jmagman** [comment]
@kentnguyen99 are you already aware of this one? Any idea why the device isn't available?

**Comment by kentnguyen99** [comment]
The external connection has been restored, phone device is connecting now.  Mac-14 is on monitoring website, please  let me know when it happens again.
