### ISSUE TITLE
Hindi font height is not same in all platform

### ISSUE THREAD

**Issue by MominRaza** [flutter/flutter#147829]
### Steps to reproduce

Write Hindi devanagari text in Text widget

### Expected results

Same height in all platforms

### Actual results

For English in Android, Windows and Web height is 20.
For Hindi in Web and Android Height is 21 and in Windows height is 21.

### Code sample

<details open><summary>Code sample</summary>

```dart
Column(
  mainAxisAlignment: MainAxisAlignment.center,
  children: [
    const Text('kIsWeb: $kIsWeb'),
    Text('$defaultTargetPlatform'),
    const SizedBox(
      height: 20,
      child: Column(children: [
        Text('हिंदी फ़ॉन्ट की ऊंचाई सभी प्लेटफ़ॉर्म पर समान नहीं है।')
      ]),
    ),
    const SizedBox(
      height: 20,
      child: Column(children: [
        Text('Hindi font height is not the same on all platforms.')
      ]),
    ),
  ],
)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Android
![image](https://github.com/flutter/flutter/assets/42776853/725a61c9-e122-4812-86db-94c9447ec08f)

Windows
![image](https://github.com/flutter/flutter/assets/42776853/fd2e53fa-309c-4702-a35d-2bfee7f1fd0a)

Web
![image](https://github.com/flutter/flutter/assets/42776853/1240eb00-215c-4a82-81c0-e26662fab3b6)

</details>

**Comment by nate-thegrate** [comment]
Flutter doesn't come with any pre-packaged font families; so they'll be different depending on the platform.

You can add a font as an asset in your **pubspec.yaml**, and then it can be used in every situation. More info here: https://docs.flutter.dev/cookbook/design/fonts

I think this might be working as intended, but if you're using a font from a local asset and you still see the same problem, let me know.
