### ISSUE TITLE
Add a child driven focus requesting mechanism

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14792]
Currently, focus nodes are top-down. Ancestors must grant focus up until a widget's parent and a focus scope node can only request focus from its parent focus scope node but not from ancestors past its parent. 

Create a mechanism where `setFirstFocus` requests can be bubbled up the tree while each ancestor can still enforce not granting focus to children that are offstage, behind modal overlays etc.

**Comment by goderbauer** [comment]
Do you have a use case in mind for this?

**Comment by xster** [comment]
More or less that merged PR and the root bug #12397. 

TextFields can request focus from its parent form. But if everything is a bit deeper inside multiple tabs, then the tab host must manually assign focus to each tab as tabs switch. Would be nice for arbitrary ancestors to let focus default granted to whomever requests it.

**Comment by xster** [comment]
cc @HansMuller, we just talked about it.

**Comment by zoechi** [comment]
Is #12339, #26810 caused by this?

**Comment by xster** [comment]
Looking over them quickly, yes.
