### ISSUE TITLE
Flutter web pattern-matching crash

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#147956]
This Flutter app runs fine on Windows:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: HomePage(),
  ));
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    Widget sameName() => const Icon(Icons.favorite, color: Colors.cyan);

    if (sameName() case final sameName) {
      return sameName;
    }
  }
}
```

but Flutter web apparently doesn't like how the function and the matched value have the same name:

```
NoSuchMethodError: tried to call a non-function: 'sameName'
```

<br>

A lack of static analysis warnings made it significantly more difficult to figure out what the problem was.

**Comment by kevmoo** [comment]
Guessing this is JS compiler bug. @sigmundch ?

**Comment by sigmundch** [comment]
Thank you so much for reporting the issue @nate-thegrate!

@kevmoo indeed! This was an issue in the lowering from the CFE affecting the web compilers (see https://github.com/dart-lang/sdk/issues/54559). A fix landed in https://github.com/dart-lang/sdk/commit/70d3adade20205a073b30967f1018e6fcf8de17e, which will be part of the upcoming release (it is already in the main, dev, and beta releases of Dart 3.4.0, so it's only a short time away until this reaches the stable channel).
