### ISSUE TITLE
support changing textAlign of TextField in DropdownMenu

### ISSUE THREAD

**Issue by angelocordero** [flutter/flutter#147991]
### Use case

`DropdownMenu` is a replacement to `DropdownButton` and `DropdownButtonFormField`. However, `DropdownButtonFormField` allows changing the `textAlign` property which we can't do in `DropdownMenu`.

### Proposal

Expose the `TextField.textAlign` property to `DropdownMenu`. It would be a trivial change to the code, and I could submit a PR unless there is a reason that this parameter should not be exposed.

**Comment by darshankawar** [comment]
> I could submit a PR unless there is a reason that this parameter should not be exposed

@angelocordero Feel free to file PR for this change. The reviewers can give feedback if this can be implemented or not.

**Comment by piedcipher** [comment]
Issue is fixed via #148074. Closing!
