### ISSUE TITLE
tap on DropdownMenu couldn't trigger onTapOutside event of TextField

### ISSUE THREAD

**Issue by guanggenzhang** [flutter/flutter#147969]
### Steps to reproduce

1. run the sample code
2. tap on TextField
3. tap on DropdownButton
4. tap on TextField again
5. tap on DropdownMenu

### Expected results

onTapOutside print at step3 and step5

### Actual results

onTapOutside only print at step3

### Code sample

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const TestApp());
}

class TestApp extends StatelessWidget {
  const TestApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: "Test",
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  const TestPage({
    super.key,
  });

  @override
  State createState() => _TestPageState();
}

class _TestPageState extends SafeState<TestPage> {
  final textEditingController = TextEditingController();

  @override
  void initState() {
    super.initState();
    textEditingController.text = 'TextField';
  }

  @override
  void dispose() {
    textEditingController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Test"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(
              controller: textEditingController,
              onTapOutside: (event){
                print('onTapOutside');
              },
            ),
            DropdownButton<String>(
              underline: const SizedBox(),
              hint: const Text('DropdownButton'),
              items: ['ITEM1', 'ITEM2'].map((item) {
                return DropdownMenuItem<String>(
                  value: item,
                  child: Text(item),
                );
              }).toList(),
              onChanged: (String? value) {},
            ),
            DropdownMenu<String>(
              enableSearch: false,
              expandedInsets: EdgeInsets.zero,
              label: const Text('DropdownMenu'),
              dropdownMenuEntries: ['ITEM1', 'ITEM2'].map((item) {
                return DropdownMenuEntry(
                  value: item,
                  label: item,
                );
              }).toList(),
            ),
          ],
        ),
      ),
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-CN)
    • Flutter version 3.19.6 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/guzh/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 79.0.3
    • Dart plugin version 241.15989.9

**Comment by huycozy** [comment]
Thanks for filing the issue. DropdownMenu uses TextField internally. I see there's an open issue addressing a similar case at https://github.com/flutter/flutter/issues/127597.

Closing this issue as a duplicate, so please follow up on it for further updates. Thank you!
