### ISSUE TITLE
Please update breaking changes policy to explain the user journey

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14791]
@kevmoo was just asking me for clarity on Flutter's breaking changes policy to understand better "why".

We discussed for a while, and I realized that probably some of that belongs in:
https://flutter.io/design-principles/#handling-breaking-changes

The gist of the user journey is:
1.  You have a project which uses Flutter.
2.  You try to `flutter upgrade`
3.  Stuff goes wrong.  You go looking at flutter-dev as per our https://flutter.io/upgrading/
4.  The flutter-dev post announcing the breaking change helps you get back on your feet.

I told him my TL;DR for these things is "We're sorry we're breaking you, this is why (cost/benefit). Here's how to fix things (links at least).  Please file issues."

Thoughts @Hixie?

**Comment by Hixie** [comment]
I don't really understand the request. The policy is the steps we carry out when we have a breaking change to report; the user journey seems like a step before that, separate from the actual concrete steps?

**Comment by eseidelGoogle** [comment]
Yeah, my goal was less around "concrete steps" and more around explaining the "why" of why we do breaking change announcements to new community/team members.  What prompted this was @kevmoo asking me for more background on breaking change announcements and so instead of just giving it to him, I attempted to file a bug so we could record it for others coming new to the team/open source.

Happy to just close and move on if in reading https://flutter.io/design-principles/#handling-breaking-changes you or others don't feel there is anything more worth explaining.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1990](https://github.com/flutter/website/issues/1990) via [**ZenHub**](https://www.zenhub.com/)
