### ISSUE TITLE
Chinese Characters display abnormal in xiaomi

### ISSUE THREAD

**Issue by xbzzoo** [flutter/flutter#147978]
### Steps to reproduce

![image](https://github.com/flutter/flutter/assets/49771082/386541a3-ae73-452d-83ff-407d810910d6)

### Expected results

like this，“北” is abnormal

### Actual results

like this，“北” is abnormal

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![image](https://github.com/flutter/flutter/assets/49771082/ad262d16-7ef7-4628-87dd-ee23994c9dd6)
![20240508215205](https://github.com/flutter/flutter/assets/49771082/1461c4ba-5cfc-42e8-9126-71d747cf0cd5)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by zhxst** [comment]
It seems like you use Traditional Chinese font.
Just change the font or change system language to Simplified Chinese.

**Comment by Sunyangl** [comment]
> It seems like you use Traditional Chinese font. Just change the font or change system language to Simplified Chinese.

The font currently in use is from Xiaomi phones, named MiSans.And the text displayed by this font should not look like this.And t
![Uploading 20240509100937.jpg…]()
he language setting of the phone is Simplified Chinese.

**Comment by Sunyangl** [comment]
![20240509101003](https://github.com/flutter/flutter/assets/49771082/e706d723-01a6-4954-9da6-d1d0cdb101eb)

**Comment by Sunyangl** [comment]
`Text('北京',style: TextStyle( fontSize: 30),)`

**Comment by huycozy** [comment]
@Sunyangl Please try to provide all appropriate information indicated in the template so that we can address the issue properly.

More specifically, please provide the additional information:
- The output of `flutter doctor -v`
- Expected results
- Device info (model, OS version)

Thanks!

**Comment by wuweijian1997** [comment]
这是你手机的字体问题吧.或者你可以设置fontFamily 试试

**Comment by Sunyangl** [comment]
> 这是你手机的字体问题吧.或者你可以设置fontFamily 试试

手机设置的字体不应该展示这个样子，感觉应该是在加载系统字体时没有找到

**Comment by Sunyangl** [comment]
> @Sunyangl Please try to provide all appropriate information indicated in the template so that we can address the issue properly.
> 
> 
> 
> More specifically, please provide the additional information:
> 
> - The output of `flutter doctor -v`
> 
> - Expected results
> 
> - Device info (model, OS version)
> 
> 
> 
> Thanks!
> 
> 

It's useless, as soon as I provide the information, you'll definitely ask me to upgrade flutter or others

**Comment by Sunyangl** [comment]
> @Sunyangl Please try to provide all appropriate information indicated in the template so that we can address the issue properly.
> 
> 
> 
> More specifically, please provide the additional information:
> 
> - The output of `flutter doctor -v`
> 
> - Expected results
> 
> - Device info (model, OS version)
> 
> 
> 
> Thanks!
> 
> 

like this，it is right![image](https://github.com/flutter/flutter/assets/49771082/fed3100c-5f05-4d39-8633-4c56cf278d67)

**Comment by Sunyangl** [comment]
> @Sunyangl Please try to provide all appropriate information indicated in the template so that we can address the issue properly.
> 
> 
> 
> More specifically, please provide the additional information:
> 
> - The output of `flutter doctor -v`
> 
> - Expected results
> 
> - Device info (model, OS version)
> 
> 
> 
> Thanks!
> 
> 

deviceinfo

xiaomi 14
![image](https://github.com/flutter/flutter/assets/49771082/0f4d85d0-771b-4ede-ba3a-ce44d18adee9)

**Comment by danagbemava-nc** [comment]
Hi @xbzzoo, @zhxst , can you provide the output of `flutter doctor -v`? Also, do you only experience this with the `MiSans` system font or are all system fonts affected?

**Comment by xbzzoo** [comment]
>  system 

only xiaomi phone， maybe other font also diplay error

**Comment by danagbemava-nc** [comment]
Hi @xbzzoo, please provide the output of `flutter doctor -v`. I do not have a xiaomi device to check this but when I used the `MiSans` font on my Pixel 7, the character looks like it is supposed to. See the screenshot below 

<img src="https://github.com/flutter/flutter/assets/88313112/f6c30c46-c8a9-410d-adb3-5924108126a2" width="300"/>
