### ISSUE TITLE
PopScope returns a black screen when using Navigator.pop method

### ISSUE THREAD

**Issue by mohammadaminiaf** [flutter/flutter#147919]
### Steps to reproduce

1. I use PopScope widget to stop closing the app the first time you click back button and only close the app if you tab back button twice in less than 2 minutes. It used to work fine when I used WillPopScope but it's deprecated since Flutter 3.12.0.

### Expected results

I have set the canPop property to false so that the user cannot pop out of the screen and instead when they click twice on the back button I use Navigator.pop(context) to close the screen.

### Actual results

But whenever user clicks the button twice instead of getting out of the app, the user is navigated to a black screen.

### Code sample

<details open><summary>Code for PopScope Widget</summary>

```dart
PopScope(
      canPop: false,
      onPopInvoked: shouldPopScreen,
      child: Scaffold(
            // rest of the code
       )
);
```

<details open><summary>Code for shouldPopScreen() method</summary>

```dart
void shouldPopScreen(bool didPop) async {
    if (didPop) {
      // If back button was allowed
      return;
    }

    // If back button was not allowed
    DateTime now = DateTime.now();
    const maxDuration = Duration(seconds: 2);
    bool isWarning =
        lastPressed == null || now.difference(lastPressed!) > maxDuration;

    if (didPop) return;

    if (isWarning) {
      lastPressed = DateTime.now();
      final snackBar = SnackBar(
        content: Text(
          AppLocalizations.of(context)!.closeSnackBarMessage,
        ),
        duration: maxDuration,
      );

      ScaffoldMessenger.of(context)
        ..removeCurrentSnackBar()
        ..showSnackBar(snackBar);

      return;
    }

    Navigator.pop(context);
    Navigator.pop(context);
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20240507-151954_Planner](https://github.com/flutter/flutter/assets/132151000/d14871d8-6126-4012-afae-0efe9bc3f78c)

</details>

### Logs

<details open><summary>Logs</summary>

```console
D/ViewRootImpl@b112bba[MainActivity](11982): ViewPostIme key 0
D/ViewRootImpl@b112bba[MainActivity](11982): ViewPostIme key 1
D/ViewRootImpl@b112bba[MainActivity](11982): ViewPostIme key 0
D/ViewRootImpl@b112bba[MainActivity](11982): ViewPostIme key 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.18363.1256],
    locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its
      default components
[!] Android Studio (not installed)
[√] VS Code (version 1.89.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by moffatman** [comment]
To pop the app use `SystemNavigator.pop()`

**Comment by mohammadaminiaf** [comment]
> To pop the app use `SystemNavigator.pop()`

Wow! your solution really did the job.
Although I had to use 2 `SystemNavigator.pop()` together becuase using 1 would still show blank screen.

And in case you are wondering what if you use 2 `Navigator.pop(context)` together, it will give you an error.

**Comment by darshankawar** [comment]
@mohammadaminiaf Is there a reason for reopening issue or your issue isn't resolved ?
