### ISSUE TITLE
Regression in build time esp. on Windows

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#147982]
SkiaPerf is reporting a large regression in build time especially on Windows (~10s regression in flutter gallery rebuild time).

https://flutter-flutter-perf.skia.org/e/?keys=Xcbc472045b37ed00829c701563079f1c&selected=commit%3D40691%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dwin%252Csub_result%253Ddebug_compile_after_edit_millis%252Ctest%253Dflutter_gallery_win__compile%252C&xbaroffset=40691

The regression appears to be due to the change here https://github.com/flutter/flutter/pull/147709. Assigning to @dcharkes to investigate.

**Comment by dcharkes** [comment]
Thanks for the report @zanderso!

Looking at the performance graph, it seems that the performance regression is the inverse of the performance gains by the PR that broke the dependency tracking landed on April 25th https://github.com/flutter/flutter/pull/147158 (and made builds faster but broken).
