### ISSUE TITLE
Wrong language order in PlatformDispatcher.instance.locales when first language isn't available as system language on android

### ISSUE THREAD

**Issue by jmguazzo** [flutter/flutter#147933]
### Steps to reproduce

1. Set "Walser" as preferred language on android. This language is "Not available as system language" and android shows the message "This language can't be used as a system language, but you've let apps and websites know you prefer this language"
2. Print the locales from ```PlatformDispatcher.instance.locales```, en_US is the first and wae_CH is the second.

@

### Expected results

I expect the locales order to be ```["wae_CH","en_US"]``` because that's how I configured my device.

### Actual results

The locales are in the order ```["en_US","wae_CH"]``` even though I set _Walser_ (wae_CH) as the first language on android.

This problem is also present with _Wolof_ (wo_SN) that is also "Not available as system language".

The order is correct when the first language I choose is a language that can be used as system language like _French Canada_ (fr_CA) or _Nederlands België_ (nl_BE).

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Locales list',
      home: Scaffold(
        body: Center(
          child: Text(PlatformDispatcher.instance.locales.join(', ')),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [version 10.0.22631.3447], locale fr-CA)
    • Flutter version 3.19.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\jmg\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code, 64-bit edition (version 1.89.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [version 10.0.22631.3447]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 124.0.6367.119
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 124.0.2478.80

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jmguazzo, this is not a flutter issue. That is how the data is returned from android. The locale data that is sent by android doesn't indicate to flutter whether it is available as a system language or not and flutter just iterates over the locales that retrieved from the device and sends that over from the android side. 

See the engine code where this happens. 

https://github.com/flutter/engine/blob/071014f31c6b8c169f8e793444d600b3b40efd4f/shell/platform/android/io/flutter/plugin/localization/LocalizationPlugin.java#L163-L176

I created a kotlin sample based on the engine code and the result is the same. See the screenshots below. 

I'll be closing this since it seems like android is favouring the default system locale over the locale which is not available as a system language. 


Thank you

```kotlin
package com.example.locale

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.TextView

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val textView = findViewById<TextView>(R.id.textView)

        val localesList = applicationContext.resources.configuration.locales

        val size = localesList.size()

        var locales = ""

        for (i in 0..<size) {
            locales += "${localesList.get(i).language}-${localesList.get(i).country}\n"
        }

        textView.text = locales.split("\n").joinToString(",")
    }
}
```

| flutter | native android |
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/88313112/af163b7d-5163-4468-8e17-ea8bc7a771a8" /> | <img src="https://github.com/flutter/flutter/assets/88313112/e48d945a-92d5-47e9-b6d4-6c1247af053a" /> |
