### ISSUE TITLE
[et] Allow disabling the "cute" output mode, so folks can `grep` the logs

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#147903]
Forked from https://github.com/flutter/flutter/issues/145711#issuecomment-2097115956.

It should be reasonable to do something like:

```sh
et build --verbose | grep <something>
```

We could make this yet-another flag, i.e. `--no-animations`, but I think verbose implying it is also fine?

Wdut?

/cc @gaaclarke

**Comment by gaaclarke** [comment]
Oh man, well tools like `ag` will change their output format when they detect they are being piped to another process.  `git` uses the flag `--porcelain` to indicate output that is verbose and meant to be parsed by another tool.

I think making `--verbose` imply that is fine and I don't recommend those other approaches.

**Comment by chinmaygarde** [comment]
Ah, I just filed https://github.com/flutter/flutter/issues/147936 which is a duplicate. We need to check that stdout is a terminal type and disable the pretty printing. It is also ok to allow manually disabling pretty printing to terminal types too.

**Comment by chinmaygarde** [comment]
As an aside, we need to go a bit out our way to fool Xcode since it pretends to be a terminal but can't handle being a terminal quite right. [GN does this detection](https://gn.googlesource.com/gn/+/refs/heads/main/src/util/test/gn_test.cc#156).

**Comment by chinmaygarde** [comment]
https://api.dart.dev/stable/3.3.4/dart-io/Stdout/hasTerminal.html may be what we need (and the one for stderr).

**Comment by matanlurey** [comment]
**Update**: We [do _some_ checks for `hasTerminal` and `supportsAnsiEscapes`](https://github.com/search?q=repo%3Aflutter%2Fengine+%2FhasTerminal%7CsupportsAnsiEscapes%2F+path%3Atools%2Fengine_tool&type=code), but it sounds like those are either insufficient, or give false-positives.

**Comment by matanlurey** [comment]
When I do:

```sh
flutter % et build -v | grep supportsAnsiEscapes
supportsAnsiEscapes: false | hasTerminal: false
```

... it appears detection does work, so I'm assuming we're not guarding something we should be.

**Comment by matanlurey** [comment]
The fix is as simple as:
```diff
diff --git a/tools/engine_tool/lib/src/logger.dart b/tools/engine_tool/lib/src/logger.dart
index 28bd847885..8b4565d94b 100644
--- a/tools/engine_tool/lib/src/logger.dart
+++ b/tools/engine_tool/lib/src/logger.dart
@@ -169,6 +169,8 @@ class Logger {
   /// and emits a carriage return.
   void clearLine() {
     if (!io.stdout.hasTerminal || _test) {
+      // Just emit a newline in tests or when not connected to a terminal.
+      _ioSinkWrite(io.stdout, '\n');
       return;
     }
```
However, it is next to impossible to test because the Logger does a bunch of things with global state.

I'm going to provide a bit more TLC to `logger.dart` and then land the fix.
