### ISSUE TITLE
examples/widgets/pageable_list.dart fails when list has only one or two items

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#148]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Aug 25, 2015 at 21:59 GMT_
_Originally opened as https://github.com/flutter/engine/issues/828_

----

**Comment by HansMuller** [comment]
This has been fixed.
