### ISSUE TITLE
RBE `ios_debug` doesn't have consistently working debug symbols in xcode

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#148093]
## description
The debugging symbols don't seem to be consistent across TU's.  I built `ios_debug` which execution about 100:1 local to remote.  It seems like maybe the remote machines don't have the same debug setup.

@zanderso I know we landed some changed to try to address this.  I think this may be after those landed?  Also, I was previously using VSCode.  I'm not sure if xcode requires something different.

related issue: https://github.com/flutter/flutter/issues/147750

## screenshot
![debugsymbolsofff](https://github.com/flutter/flutter/assets/30870216/1cb50b49-67b9-4ec6-aeb8-71577f6c513f)

## seen on
c674206209422dd45601be238e1c9610e27ef49a

## seen
Clicking through the stackframes in xcode sometimes shows the source code, sometimes it doesn't.

## expected
I expected clicking all the stackframes should show the code in xcode.

## steps to reproduce
1) Build `ios_debug`
2) Launch a flutter app with that local engine in xcode
3) Set a symbolic breakpoint in flutter::DisplayList::Build

The files that don't have proper symbols are possibly random.

## artifacts
libFlutter.dylib - https://drive.google.com/file/d/12D3vkKzTcxyZ1ige3tAf2ESjazKmAA_J/view?usp=sharing

**Comment by gaaclarke** [comment]
# Workaround
You can remap the debugger symbols with the following command:
```
(lldb) settings set target.source-map "flutter/" "/Users/aaclarke/dev/engine/src/flutter/"
```

Xcode won't pick up the change until you advance the PC, so you need to issue a command like 'n' to get it to refresh.

**Comment by chinmaygarde** [comment]
I've documented this workaround in the [debugging guide](https://github.com/flutter/engine/blob/67b69c76160c9d7e05a83da60b332a06a371ba50/docs/Debugging-the-engine.md#googlers-using-rbe).

**Comment by gaaclarke** [comment]
I'm going to close this.  If you use `//engine.workspace` I've built in the necessary tools to symbolicate RBE builds correctly.  The workaround is listed above too.
