### ISSUE TITLE
Implement dependabot `groups` in packages repo

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#148098]
Dependabot now supports `groups` to update multiple packages in the same PR.
https://github.com/flutter/packages/blob/main/.github/dependabot.yml

[Grouped version updates for Dependabot are generally available](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/
)
[Docs for `groups`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)

Ideally it would mean all the, say, gradle updates could happen in 1 PR, instead of 1 PR per package:
https://github.com/flutter/packages/pull/6661
https://github.com/flutter/packages/pull/6662
https://github.com/flutter/packages/pull/6663
https://github.com/flutter/packages/pull/6665
https://github.com/flutter/packages/pull/6667
https://github.com/flutter/packages/pull/6669

This would reduce the number of incoming commits to the packages repo, and reduce the review burden for keeping dependencies up-to-date.

**Comment by jmagman** [comment]
This will probably be easier for the packages repo when `multi-directory` becomes stable:
https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/

**Comment by jmagman** [comment]
cc @stuartmorgan

**Comment by reidbaker** [comment]
FWIW I think Gradle updates can be batched as can Kotlin updates. 
AGP updates require manual effort most of the time so while I would like to say they cant be batched the reality is it doesnt matter because we will have to manually update everything anyway. 
I dont think we have dependabot setup for android versions but compileSdkVersion could likely also be batched. 

@gmackall

**Comment by jmagman** [comment]
https://github.com/flutter/packages/pull/8329 bumped `androidx.annotation:annotation` across three packages
