### ISSUE TITLE
Check to see if there are any flutter widgets' use cases that only run on apps, not on the web

### ISSUE THREAD

**Issue by ZhuChanJuan** [flutter/flutter#148039]
Recently i downloaded one project names "automated_tests", i run one test case with command but returns error which means the dart library is't available on the chrome platform.
[flutter_gold_test.txt](https://github.com/flutter/flutter/files/15258838/flutter_gold_test.txt)

`**flutter run flutter_test/flutter_gold_test.dart -d chrome**
Launching flutter_test/flutter_gold_test.dart on Chrome in debug mode...
../../../flutter/packages/flutter_goldens/lib/skia_client.dart:6:8: Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' show Abi;
       ^
Context: The unavailable library 'dart:ffi' is imported through these packages:

    flutter_gold_test.dart => package:flutter_goldens => dart:ffi

Detailed import paths for (some of) the these imports:

    web_entrypoint.dart => flutter_gold_test.dart => package:flutter_goldens/flutter_goldens.dart => package:flutter_goldens/skia_client.dart => dart:ffi

../../../flutter/packages/flutter_goldens/lib/flutter_goldens.dart:472:75: Error: Type 'LocalComparisonOutput' not found.
class FlutterLocalFileComparator extends FlutterGoldenFileComparator with LocalComparisonOutput {
                                                                          ^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter_goldens/lib/skia_client.dart:56:5: Error: Type 'Abi' not found.
    Abi? abi,
    ^^^
../../../flutter/packages/flutter_goldens/lib/skia_client.dart:87:9: Error: Type 'Abi' not found.
  final Abi abi;
        ^^^
../../../flutter/packages/flutter_goldens/lib/flutter_goldens.dart:472:7: Error: The type 'LocalComparisonOutput' can't be mixed in.
class FlutterLocalFileComparator extends FlutterGoldenFileComparator with LocalComparisonOutput {
      ^
../../../flutter/packages/flutter_goldens/lib/flutter_goldens.dart:174:68: Error: The getter 'basedir' isn't defined for the class 'LocalFileComparator'.
 - 'LocalFileComparator' is from 'package:flutter_test/src/_goldens_web.dart' ('../../../flutter/packages/flutter_test/lib/src/_goldens_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'basedir'.
    final Directory testDirectory = fs.directory(defaultComparator.basedir);
                                                                   ^^^^^^^
../../../flutter/packages/flutter_goldens/lib/flutter_goldens.dart:419:43: Error: The getter 'basedir' isn't defined for the class 'LocalFileComparator'.
 - 'LocalFileComparator' is from 'package:flutter_test/src/_goldens_web.dart' ('../../../flutter/packages/flutter_test/lib/src/_goldens_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'basedir'.
    final Uri basedir = defaultComparator.basedir;
                                          ^^^^^^^
../../../flutter/packages/flutter_goldens/lib/flutter_goldens.dart:572:32: Error: The method 'generateFailureOutput' isn't defined for the class 'FlutterLocalFileComparator'.
 - 'FlutterLocalFileComparator' is from 'package:flutter_goldens/flutter_goldens.dart' ('../../../flutter/packages/flutter_goldens/lib/flutter_goldens.dart').
Try correcting the name to the name of an existing method, or defining a method named 'generateFailureOutput'.
    final String error = await generateFailureOutput(result, golden, basedir);
                               ^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter_goldens/lib/skia_client.dart:56:5: Error: 'Abi' isn't a type.
    Abi? abi,
    ^^^
../../../flutter/packages/flutter_goldens/lib/skia_client.dart:60:21: Error: Undefined name 'Abi'.
       abi = abi ?? Abi.current();
                    ^^^
../../../flutter/packages/flutter_goldens/lib/skia_client.dart:87:9: Error: 'Abi' isn't a type.
  final Abi abi;
        ^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling org-dartlang-app:/flutter_gold_test.dart, which contains the type: InvalidType(<invalid>).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3236)
#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3197)
#2      ProgramCompiler._emitCast (package:dev_compiler/src/kernel/compiler.dart:6813)
#3      ProgramCompiler.visitAsExpression (package:dev_compiler/src/kernel/compiler.dart:6807)
#4      AsExpression.accept (package:kernel/ast.dart:7667)
#5      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3944)
#6      ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:4631)
#7      ReturnStatement.accept (package:kernel/ast.dart:10206)
#8      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3853)
#9      ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3886)
#10     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3592)
#11     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2565)
#12     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3629)
#13     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3588)
#14     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3397)
#15     ProgramCompiler._emitMethodDeclaration.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2130)
#16     ProgramCompiler._withMethodDeclarationContext (package:dev_compiler/src/kernel/compiler.dart:3656)
#17     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:2129)
#18     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2063)
#19     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:905)
#20     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:819)
#21     List.forEach (dart:core-patch/growable_array.dart:416)
#22     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:757)
#23     List.forEach (dart:core-patch/growable_array.dart:416)
#24     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)
#25     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
#26     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:801)
<asynchronous suspension>
#27     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:661)
<asynchronous suspension>
#28     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1311)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Chrome...              3.6s
Failed to compile application.`

**Comment by ZhuChanJuan** [comment]
If this scenario does exists, then may i know what kind of widget can't be run on web browser ? 
Since our project use flutter, i need write and execute test cases on web browser.
Once some widgets can't support chrome platform, does that means they can't be tested by flutter native testing framework ?

**Comment by dcharkes** [comment]
@ZhuChanJuan `dart:ffi` is not supported on the browser. Dart FFI calls into C code, which is available on native platforms as a dynamic library or linked into the flutter app when the native build is performed by xcodebuild/msbuild/cmake.

In the context of Flutter plugins/packages, a different implementation can be provided by the plugin author for native and for web. For example https://pub.dev/packages/shared_preferences uses https://pub.dev/packages/path_provider_windows which uses `dart:ffi` on Windows, but for the web `shared_preferences` uses a different implementation that doesn't use `dart:ffi`.

I am not familiar with https://github.com/flutter/flutter/blob/master/dev/automated_tests/flutter_test/flutter_gold_test.dart. My hunch is that this some different type of setup, not a flutter plugin. Maybe someone else can comment on how those tests are set up. But I don't believe these tests are representative for normal Flutter plugin or app development.

Is your question specifically about this test? Or about Flutter apps and packages in general?

**Comment by ZhuChanJuan** [comment]
thanks for your comment @dcharkes 
Actually my question is about flutter apps and packages in general, not specifically about this file ~

**Comment by dcharkes** [comment]
You can see for every plugin/package on dart.dev whether web is support yes or no.

* Web supported: https://pub.dev/packages/shared_preferences
* Web not supported: https://pub.dev/packages/path_provider

If you stick to using plugins/packages that has web-support, you should be able to run tests with  `-d chrome`. 👌

**Comment by dcharkes** [comment]
> oh i see, if the package has "WEB" flag, then that means the widget is web-support and could run on MacOS Chrome browser. please correct me if i'm wrong @dcharkes ~

Yep, correct!

**Comment by ZhuChanJuan** [comment]
thanks so much ~
but can i make sure whether other web browser like Edge or firefox is supported by related commands , for those web-supported widgets ?
since i have tried quite many commands to run flutter test cases on MacOS Edge (and i also need to see the UI while case running), but they all failed.

**Comment by dcharkes** [comment]
```
flutter create my_app
cd my_app
flutter run -d chrome
```

**Comment by ZhuChanJuan** [comment]
yes yes, i also tried this before and it works well on Chrome browser ~
but the problem is we can't switch to other web browser by commands

**Comment by dcharkes** [comment]
Okay, I have no idea about that. Someone more familiar with flutter for web can maybe answer that.

**Comment by darshankawar** [comment]
@ZhuChanJuan I think you have already filed an [issue](https://github.com/flutter/flutter/issues/147965) which has been triaged. You'll need to follow-up in it for further updates.
Is there anything different or separate from that issue, which you are asking here ? Seems from above conversation that most of your questions were answered by Daco.

**Comment by ZhuChanJuan** [comment]
yes yes, main questions are answered by @dcharkes already.
thanks so so much ~
