### ISSUE TITLE
Prevent multiple clicks

### ISSUE THREAD

**Issue by cnkygmr** [flutter/flutter#148049]
### Use case

For all onpress and ontap functions, I want to determine how long it takes to press again, so that it does not press continuously.

For example, I want it to not press again before 2 seconds.

### Proposal

```
TextButton(
  style: TextButton.styleFrom(
    primary: Colors.blue,
  ),
  onPressed: () { },
  onPressInt : 2000, // Like that maybe
  child: Text('TextButton'),
)
```

Something like this or something different that makes more sense

**Comment by darshankawar** [comment]
@cnkygmr 
There's a community package that you can try which probably resolves your use case. https://pub.dev/packages/tap_debouncer

Also check [this](https://thekoolsk.medium.com/how-to-prevent-multiple-clicks-in-flutter-fbc71a562b2c) article and see if it helps further or not.

**Comment by cnkygmr** [comment]
@darshankawar  very good thank you

**Comment by darshankawar** [comment]
Closing, as info provided in earlier comment should help to achieve the use case.
