### ISSUE TITLE
I'm forgetting to opt-in to dart 2 in my various tools

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#14806]
User problem: I forget to always add the opt-in flag for Dart 2 when running CLI tools. And, I might set it once in one tool and forget to set it again in another tool.

Strawman suggestion: let me set the flag _once_ and then TADA all my tools use it. For example, some sort of `.flutterrc` file , which CLI, Android Studio, VS Code, and others can read.

**Comment by sethladd** [comment]
cc @DanTup , too

and cc @mraleph

**Comment by xster** [comment]
Perhaps .flutter_settings via `flutter config`?

**Comment by sethladd** [comment]
sure, whatever canonical single-source config exists.

**Comment by bwilkerson** [comment]
For the command-line analyzer and the analysis server, that's the `analysis_options.yaml` file. Just add `enablePreviewDart2: true` to the `language:` section.

**Comment by mit-mit** [comment]
Our main editors (Android Studio, IntelliJ, VS Code) will have a single, sticky setting you toggle once. This is going out later this week. Details will be listed on https://github.com/flutter/flutter/wiki/Trying-the-preview-of-Dart-2-in-Flutter

**Comment by DanTup** [comment]
> VS Code will have a single, sticky setting you toggle once

VSCode lets you set settings at user/workspace/workspaceFolder level so you're free to opt-in on some projects and not others. You need to add to "User Settings" if you want it to apply globally (this is likely the settings most people open when they're configuring things).

The setting in VS Code applies to both the analyzer and launching the app. Are there other things that Flutter devs (using VS Code) would run that require this flag (eg. from the terminal)?

**Comment by mit-mit** [comment]
I'm not convinced this is worth the effort. The duration of time where this flag will be needed will be short, and outside of the terminal we have fairly permanent means of setting this flag. 

On the terminal this is also potentially dangerous to default in some non-transparent means. We don't want to risk developers doing a release build (`build apk`/`build ios`) to go the app stores, and unknowingly push something using preview without them being very aware of the risk involved in that.

**Comment by sethladd** [comment]
Thanks for the analysis.
