### ISSUE TITLE
After the Flutter sdk version was upgraded from 3.13.4 to 3.19.6, the Flutter SDK occasionally crashed after the screen froze on iOS 17.

### ISSUE THREAD

**Issue by wahkim** [flutter/flutter#148032]
### Steps to reproduce

After the Flutter sdk version was upgraded from 3.13.4 to 3.19.6, the Flutter SDK occasionally crashed after the screen froze on iOS 17. Because it's a customer's phone, we can't grab any logs, not even on bugly. The problem cannot be repeated. Is there any vulnerability in the new sdk?

### Expected results

normal 

### Actual results

Stuck on the home page

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

flutter doctor -v
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6.1 22G313 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.19.6 on channel stable at /Users/xxx/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by huycozy** [comment]
Hi @wahkim 
Without the crash log or more information, we are unfortunately not sure what the cause of this is. One hint for this is to collect the affected device info (OS, model) and try to reproduce it on your end with the same device. Once you can reproduce the crash, please share the stack trace here which may help us investigate it further. Thanks!

**Comment by huycozy** [comment]
Without additional information, we are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away. Thanks!
