### ISSUE TITLE
Add a `flutter downgrade` command

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14801]
#### Use case <span>#</span>1:

User A runs `flutter upgrade` only to discover that one of the breaking changes in our Changelog is going to be too much work for them to fix in their app right now.  They plan to update their app accordingly in a few weeks after their upcoming app release, but in the meantime, they wish to go back to the previous version of Flutter.

#### Use case <span>#</span>2:

User B runs `flutter upgrade` and begins coding against the updated Flutter SDK.  In so doing, they discover a regression in Flutter that blocks them from making progress in their app.  User B files the regression as an issue in our GitHut repo, and we acknowledge that the regression is serious enough to mark that build as a [bad build](https://github.com/flutter/flutter/wiki/Bad-Builds).  User B, satisfied with their participation in the community, now wishes to go back to the previous Flutter version while the issue gets fixed and a new release gets published so that they're no longer blocked.

#### Proposed solution

I propose we add a `flutter downgrade` command.  It would behave as follows:

* On the `master` channel, it would be unsupported (it would print a message to that effect and do nothing).
* On the `dev` or `beta` channels (or the `release` channel once that exists), it would check out the version that had been published to their channel prior to the user's current version.

This will require the tool to be able to know what the previous version is.  For the `dev` channel, it's just the previous tagged version.  For the `beta` and `release` channels, we'll need a way to figure out the appropriate version.  One possible way is to add an extra marker tag to a commit whenever it's released to the more stable channels...

**Comment by tvolkert** [comment]
See also: https://github.com/flutter/flutter/issues/14230

**Comment by tvolkert** [comment]
@pedia I'm curious what your objection to this is.

**Comment by pedia** [comment]
@tvolkert Use git to downgrade is easier.

**Comment by tvolkert** [comment]
Yeah, I think this can be solved with a hidden --version argument.  Closing this one.  Thanks!
