### ISSUE TITLE
Ink item in ListView in Column bug

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#14800]
## Steps to Reproduce

Scroll down the ListView with the code below. The 2nd ListView item will be covered up by 1st ListView items.

![](https://i.imgur.com/7CYxjzF.jpg)

```dart
import 'package:flutter/material.dart';

class TheList extends StatefulWidget {
  TheList({
    this.scrollDirection: Axis.vertical,
  });

  final Axis scrollDirection;
  _TheListState createState() => new _TheListState();
}

class _TheListState extends State<TheList> {
  int itemCount;

  @override
  initState() {
    super.initState();
    itemCount = 10;
  }

  Widget build(BuildContext context) {
    return new ListView.builder(
        scrollDirection: widget.scrollDirection,
        itemCount: itemCount,
        itemBuilder: (BuildContext context, int index) {
          return new InkWell(
            onTap: () {},
            child: new Ink(
              height: widget.scrollDirection == Axis.horizontal ? null : 100.0,
              width: widget.scrollDirection == Axis.horizontal ? 50.0 : null,
              decoration: new BoxDecoration(
                  color: Colors.grey, border: new Border.all()),
              child: new Center(
                child: new Text("$index"),
              ),
            ),
          );
        });
  }
}

class TheApp extends StatelessWidget {
  Widget build(BuildContext context) {
    // return new TheList(
    //   scrollDirection: Axis.vertical,
    // );
    return new Column(
      children: <Widget>[
        new Container(
          height: 100.0,
          child: new TheList(
            scrollDirection: Axis.horizontal,
          ),
        ),
        new Container(
          height: MediaQuery.of(context).size.height - 200,
          child: new TheList(
            scrollDirection: Axis.vertical,
          ),
        ),
      ],
    );
  }
}

void main() => runApp(
      new MaterialApp(
        home: new Scaffold(
          appBar: new AppBar(title: const Text("Ink Bug"), elevation: 0.0),
          body: new TheApp(),
        ),
      ),
    );
```

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-HK, channel master)
    • Flutter version 0.1.3-pre.44 at /Users/odd/wa/flutter/flutter
    • Framework revision dcfac974be (25 hours ago), 2018-02-20 12:39:38 +0800
    • Engine revision e5b72e5f87
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/odd/Library/Android/sdk
    • Android NDK at /Users/odd/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.8.2

[✓] Connected devices
    • iPhone 6s • 28B00868-73F6-4816-8451-FCFF1DD1E855 • ios • iOS 11.2 (simulator)

• No issues found!

**Comment by pedia** [comment]
Ink is transparent. Maybe not a bug.

**Comment by MagTuxGit** [comment]
Don't use decoration on Ink in ListView.
Workaround:
```
Container(
   decoration: ..., 
   child: Material(
      child: Ink(...)
   )
)
```
