### ISSUE TITLE
Allow flutter binary cache to exist outside of the flutter root.

### ISSUE THREAD

**Issue by dvtkrlbs** [flutter/flutter#148055]
The installation path of my flutter is immutable and flutter tries to use the binary cache location on ios builds. Normally I would just symlink this path however this cache location is sometimes referred as a relative path in the flutter source code [link](https://github.com/search?q=repo%3Aflutter%2Fflutter+%27..%27&type=code&p=1) [link](https://github.com/search?q=repo%3Aflutter%2Fflutter+%27bin%27+%27cache%27&type=code). My suggestion is to have an environment variable to override this cache location or make it symlink friendly.

Relevant issue [link](https://github.com/NixOS/nixpkgs/issues/243448)

**Comment by huycozy** [comment]
Hi @dvtkrlbs, I see there is an issue https://github.com/flutter/flutter/issues/105257 that may be similar to this, could you take a look and confirm? If they are, we can deduplicate this and centralize these on https://github.com/flutter/flutter/issues/105257.

**Comment by dvtkrlbs** [comment]
yes i  think you can merge with that
