### ISSUE TITLE
Migrate devicelab from A02s's and MotoG4's to Mokey's

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#148085]
1. Move hosts that currently have A02s and MotoG4 attached from prod to staging.
    1. Send PSA about reduced capacity.
    1. Move half from prod to staging.
    1. Edit .ci.yaml to add `bringup: true`.
    1. Move the other half from prod to staging.
1. Replace A02s's and MotoG4's on those hosts with Mokeys
    1. Ask Kent to do it by filing GitHub issues and emailing.
1. Switch tests from running on A02s's and MotoG4s to running on Mokey's.
    1. All in one go.
1. Move hosts with Mokey's from staging to prod.
    1. Move half of hosts with Mokeys from staging to prod
    1. Edit the .ci.yaml to remove `bringup: true` from the tests on Mokey
    1. Move the rest of the hosts with Mokeys from staging to prod
    1. Send PSA that migration is complete.
 
Yusuf wrote up this doc to describe where we'd like to get to for how devices are allocated in the lab across pools and devices: go/flutter-devicelab-testbed-matrix

Current allocation between try, staging, and prod pools can be queried in https://chromium-swarm.appspot.com/botlist.

We can move hosts between staging and prod by editing:
https://chrome-internal.googlesource.com/infradata/config/+/refs/heads/main/configs/chromium-swarm/starlark/bots/flutter.star. There are extra steps that I don't know to check in extra files that are generated from the .star files.

Kent: nguyenkent@

**Comment by zanderso** [comment]
Marking `team-infra`, but this will get sorted out between me, @jonahwilliams, and @kentnguyen99

**Comment by kentnguyen99** [comment]
@zanderso, Please let me know when your teams ready to switch the phone devices from A02s and MotoG4s to new Mokey's phone device.  And also, which phone model to switch out first, A02s or MotoG4s?

**Comment by jonahwilliams** [comment]
Sounds like we have 20 devices so far. I think the sticky note on my desk claims we'll need 3X devices, so I'll flash the rest next week.

**Comment by jonahwilliams** [comment]
@zanderso the box next to your desk is full of all of the flashed mokey devices that are ready for the devicelab

**Comment by kentnguyen99** [comment]
@jonahwilliams Just want to make correction.  There are 18 Mokey devices in the Devicelab, one device won't charge and other device different model was missed up in the pile.

**Comment by zanderso** [comment]
After https://github.com/flutter/flutter/pull/149567, one test is failing consistently on the mokey https://github.com/flutter/flutter/issues/149666

**Comment by zanderso** [comment]
All Moto G4s have been removed from the lab. This is done!
