### ISSUE TITLE
[native_assets] There's two errors thrown by Xcode 15.3 when submitting Flutter apps built with `native_assets` to the App Store.

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#148044]
There's two errors thrown by Xcode 15.3 when submitting Flutter apps built with `native_assets` to the App Store.

First is:

```
 This bundle is invalid. The bundle at path Payload/Runner.app/Frameworks/sherpa_onnx_dart.framework has an invalid CFBundleIdentifier 'io.flutter.flutter.native_assets.sherpa_onnx_dart' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'io.flutter.flutter.native\\u005fassets.sherpa\\u005fonnx\\u005fdart' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot.
```

[Per the Apple reference, underscores can't be used in CFBundleIdentifier](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier), so perhaps we could replace [hyphens with underscores here](https://github.com/flutter/flutter/blob/607a3dad768d326fb9fb1ac24e6a2fc92303a6ab/packages/flutter_tools/lib/src/isolated/native_assets/macos/native_assets_host.dart#L34), e.g.
```
<key>CFBundleIdentifier</key>
<string>io.flutter.flutter.native-assets.${name.replaceAll("_", "-")}</string>
```

The second issue is similar, the generated `Info.plist` does not contain an entry for `MinimumOSVersion`, so trying to publish via XCode will throw the following error:

```
Asset validation failed. Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle Runner.app/Frameworks/sherpa-onnx-dart.framework is required.
```

Workaround is to add the following to `native_assets_host.dart`

```
  <key>MinimumOSVersion</key>
  <string>13.0</string>
```

I haven't submitted a PR because I suspect there's a broader fix to the `native_assets` framework build process to consume some user-specified configuration ([e.g. this may be contemplated by this issue here](https://github.com/flutter/flutter/issues/140966).

_Originally posted by @nmfisher in https://github.com/flutter/flutter/issues/129757#issuecomment-2102290794_

**Comment by dcharkes** [comment]
Thanks for the report @nmfisher!

> There's two errors thrown by Xcode 15.3 when submitting Flutter apps built with `native_assets` to the App Store.
> 
> First is:
> 
> ```
>  This bundle is invalid. The bundle at path Payload/Runner.app/Frameworks/sherpa_onnx_dart.framework has an invalid CFBundleIdentifier 'io.flutter.flutter.native_assets.sherpa_onnx_dart' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'io.flutter.flutter.native\\u005fassets.sherpa\\u005fonnx\\u005fdart' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot.
> ```
> 
> [Per the Apple reference, underscores can't be used in CFBundleIdentifier](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier), so perhaps we could replace [hyphens with underscores here](https://github.com/flutter/flutter/blob/607a3dad768d326fb9fb1ac24e6a2fc92303a6ab/packages/flutter_tools/lib/src/isolated/native_assets/macos/native_assets_host.dart#L34), e.g.
> 
> ```
> <key>CFBundleIdentifier</key>
> <string>io.flutter.flutter.native-assets.${name.replaceAll("_", "-")}</string>
> ```

I am not sure if the CFBundleIdentifier must be in some way identical to the framework name. If yes, then we should do the search-replace in the code modified in https://github.com/flutter/flutter/pull/144568. Also that PR shows where test cases can be added.

https://github.com/flutter/flutter/blob/607a3dad768d326fb9fb1ac24e6a2fc92303a6ab/packages/flutter_tools/lib/src/isolated/native_assets/macos/native_assets_host.dart#L183

If the CFBundleIdentifier does not have to be equal to the framework name, we don't have to, but we should possibly still take care of when the rename happens that there are no duplicates.

> The second issue is similar, the generated `Info.plist` does not contain an entry for `MinimumOSVersion`, so trying to publish via XCode will throw the following error:
> 
> ```
> Asset validation failed. Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle Runner.app/Frameworks/sherpa-onnx-dart.framework is required.
> ```
> 
> Workaround is to add the following to `native_assets_host.dart`
> 
> ```
>   <key>MinimumOSVersion</key>
>   <string>13.0</string>
> ```
> 
> I haven't submitted a PR because I suspect there's a broader fix to the `native_assets` framework build process to consume some user-specified configuration ([e.g. this may be contemplated by this issue here](https://github.com/flutter/flutter/issues/140966).

I think this value should come from Flutter, not from the `build.dart` hook output.

Reasoning: We have `targetAndroidNdkApi` as a parameter in `BuildConfig`, and the `build.dart` hook should fail if it cannot produce a dylib with that android NDK API version. I think we should have a similar pattern for the minimum iOS SDK version. The minimum iOS SDK version should be part of the `BuildConfig` and the `build.dart` should fail if it cannot produce a dylib for that version. Flutter Tools needs to pass the minimum iOS SDK version in a similar fashion to how it does it for Android:

https://github.com/flutter/flutter/blob/607a3dad768d326fb9fb1ac24e6a2fc92303a6ab/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart#L63

https://github.com/flutter/flutter/blob/607a3dad768d326fb9fb1ac24e6a2fc92303a6ab/packages/flutter_tools/lib/src/build_system/targets/native_assets.dart#L315-L316

For passing `minimumIOSVersion` in `BuildConfig` we'll need to do upstream changes in https://github.com/dart-lang/native.

Passing the minimumIOSVersion into the `Info.plist` can already be done in a PR.

Happy to receive PRs for this @nmfisher!

**Comment by knopp** [comment]
@dcharkes, this should be fixed via https://github.com/flutter/flutter/pull/148504/files#diff-e8e2113fdaf6679f3610d7eaaa5e5bb4753b732e0a263cd7f0a233a1e32f18ef

**Comment by dcharkes** [comment]
Yes, the minimum deployment target is tracked in https://github.com/dart-lang/native/issues/1133.

Thanks @knopp!
