### ISSUE TITLE
Autosubmit bot is not merging PRs

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#148092]
### Type of Request

bug

### Infrastructure Environment

Cocoon autosubmit bot

### What is happening?

40 minutes ago this PR was the autosubmit label: https://github.com/flutter/flutter/pull/146806
3 hours ago the last PR was autosubmitted https://github.com/flutter/flutter/pull/148070

Also, the fluttergithubbot account has stopped approving PRs.

The tree is green

**Comment by jmagman** [comment]
Auto-approval of PRs generated by the auto-rollers also appears to be failing, which is also a cocoon service.

cc @christopherfujino @stuartmorgan if there are any clues in the cocoon logs

**Comment by stuartmorgan** [comment]
We've tracked down some server logs that suggest that [this code](https://github.com/flutter/cocoon/blob/3467e1ea599543411747e0a937759c41e62a91cf/auto_submit/lib/service/config.dart#L191-L196) isn't finding an installation ID, so we're working on deploying more logging so we can see what the response looks like. @jason-simmons tried the same query locally and didn't see anything with `flutter` as the owner, which would certainly explain it, but we don't know why that would be true yet.

**Comment by stuartmorgan** [comment]
The issue was with pagination of the response. Fix incoming.
