### ISSUE TITLE
image_picker does not return information after selecting an image on Xiaomi Poco F4 GT phone

### ISSUE THREAD

**Issue by mujia521** [flutter/flutter#148047]
### Steps to reproduce

flutter version1.22.4
image_picker: ^0.6.7+22
Phone model：POCO F4 GT(MIUI Global 14.0.5)
                   XQ-DC72 Android v14
截图
![图片_34_11](https://github.com/flutter/flutter/assets/52438101/fbdcde02-9d75-462d-a8c0-5e1de57970cd)

Question video
https://github.com/flutter/flutter/assets/52438101/f6a0eb03-1ca9-4bb3-a14d-6a40ad8a0fd1

### Expected results

The selected image should be returned normally.

### Actual results

Can't get data

### Code sample

<details open><summary>Code sample</summary>

```dart

File _image;
    final picker = ImagePicker();
    final pickedFile = await picker.getImage(source: type == 0 ? ImageSource.camera : ImageSource.gallery);
    // pickedFile是null

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 14.3.1 23D60 darwin-x64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[!] Android Studio (version 2021.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
[!] Proxy Configuration
    ! NO_PROXY is not set
 
[✓] Connected device (1 available)            

! Doctor found issues in 2 categories.


```

</details>

**Comment by wuweijian1997** [comment]
有报错日志吗?catchError 试一下?

**Comment by darshankawar** [comment]
@mujia521  You are on obsolete version of the framework. Also plugin version you are using is not latest. 
Please upgrade to latest and re-run your scenario to check if the reported behavior still exist or not.
Also, Please use English when filing issue for better readability.
Closing for now, as the version you are on is very old.
