### ISSUE TITLE
type inference failure

### ISSUE THREAD

**Issue by graemep-nz** [flutter/flutter#148009]
### Steps to reproduce

The typecast shouldn't be needed in the code below

```dart
typedef saveObjectListFirestoreDoc = Future<bool> Function<T extends HasTimeDateID>(
      {required String docName, required ObjectListFirestoreDoc<T> objectListDoc, bool isNew});

Future<bool> saveUserEventBookingDoc(
    {required String docName, required ObjectListFirestoreDoc<UserEventBookingItem> objectListDoc,
      required bool isNew}) async {
  return true;
}

saveObjectListFirestoreDoc fred = saveUserEventBookingDoc as saveObjectListFirestoreDoc; 

class ObjectListFirestoreDoc<T> {}

class UserEventBookingItem extends HasTimeDateID {
}

class HasTimeDateID{}

```

### Expected results

should compile without typecast

### Actual results

Dart gives an error without the typecast
"A value of type 'Future<bool> Function({required String docName, required bool isNew, required ObjectListFirestoreDoc<UserEventBookingItem> objectListDoc})' can't be assigned to a variable of type 'Future<bool> Function<T extends HasTimeDateID>({required String docName, required bool isNew, required ObjectListFirestoreDoc<T> objectListDoc})'."

### Code sample

see above

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version
    10.0.22631.3527], locale en-NZ)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.0)
[√] Android Studio (version 2023.3)
[√] Connected device (3 available)
[√] Network resources

```

</details>

**Comment by moffatman** [comment]
It's a real error. Since `saveObjectListFirestoreDoc` is a raw generic type. Someone could call `fred(HasTimeDateID())` later. And it would crash because the function doesn't accept it, only the subclass `UserEventBookingItem`.

Also your typedef has no `required on parameter `bool isNew`.

Improved version, I moved the `<T>` constraint to the left of the equals sign in typedef and specified it on `fred`. In addition to fixing the `isNew` mismatch:

```dart
typedef saveObjectListFirestoreDoc<T extends HasTimeDateID> = Future<bool> Function(
      {required String docName, required ObjectListFirestoreDoc<T> objectListDoc, required bool isNew});

Future<bool> saveUserEventBookingDoc(
    {required String docName, required ObjectListFirestoreDoc<UserEventBookingItem> objectListDoc,
      required bool isNew}) async {
  return true;
}

saveObjectListFirestoreDoc<UserEventBookingItem> fred = saveUserEventBookingDoc;

class ObjectListFirestoreDoc<T> {}

class UserEventBookingItem extends HasTimeDateID {
}

class HasTimeDateID{}
```
