### ISSUE TITLE
Flutter Animate Assertion Error

### ISSUE THREAD

**Issue by opensourcepj** [flutter/flutter#148132]
### Steps to reproduce

curve parameter of curve animation set to 
                Interval((1 / count) * 0, 1.0, curve: Curves.fastOutSlowIn)
where in error count = 0

### Expected results

improved error description

### Actual results

```
When the exception was thrown, this was the stack:
#2      Interval.transformInternal
(package:flutter/src/animation/curves.dart:175:12)
#3      ParametricCurve.transform
(package:flutter/src/animation/curves.dart:40:12)
#4      Curve.transform (package:flutter/src/animation/curves.dart:94:18)
#5      CurvedAnimation.value
(package:flutter/src/animation/animations.dart:464:24)
#6      Animatable.evaluate (package:flutter/src/animation/tween.dart:68:66)
#7      _AnimatedEvaluation.value
(package:flutter/src/animation/tween.dart:114:31)
#8      RenderAnimatedOpacityMixin._updateOpacity
(package:flutter/src/rendering/proxy_box.dart:1052:51)
#9      AnimationLocalListenersMixin.notifyListeners
(package:flutter/src/animation/listener_helpers.dart:161:19)
#10     AnimationController._tick
(package:flutter/src/animation/animation_controller.dart:865:5)
#11     Ticker._tick (package:flutter/src/scheduler/ticker.dart:258:12)
#12     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1386:15)
#13     SchedulerBinding.handleBeginFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:1233:11)
#14     _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:633:13)
#15     SchedulerBinding.handleBeginFrame
(package:flutter/src/scheduler/binding.dart:1231:17)
#16     SchedulerBinding._handleBeginFrame
(package:flutter/src/scheduler/binding.dart:1148:5)
#17     _invoke1 (dart:ui/hooks.dart:328:13)
#18     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:361:5)
#19     _beginFrame (dart:ui/hooks.dart:272:31)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@opensourcepj 
Please provide complete reproducible code sample (ex: main.dart) along with `flutter doctor -v` so that we can properly address the issue.

**Comment by opensourcepj** [comment]
Tween<double>(begin: 0.0, end: 1.0).animate(
              CurvedAnimation(
                  parent: animationController!,
                  curve: Interval((1 / count) * 0, 1.0,
                      curve: Curves.fastOutSlowIn)))

@darshankawar The error was caused by count being equal to 0 in the above tween.

**Comment by darshankawar** [comment]
@opensourcepj 
I tried to come up with a runnable code sample including your code snippet but not able to replicate the error you reported. Please try to provide us complete code and also provide on which flutter version are you seeing this behavior.

ex: https://github.com/flutter/website/blob/main/examples/animation/animate5/lib/main.dart
