### ISSUE TITLE
%5Btool_crash%5D RPCError

### ISSUE THREAD

**Issue by srbshameer098** [flutter/flutter#148168]
%23%23 Command%0A%60%60%60%0Aflutter run%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0ARPCError%0A%60%60%6

**Comment by danagbemava-nc** [comment]
Closing this since the logs aren't clear. 

In the future, please provide the full message from the crash log or click the link in the crash log to file the issue. 

Thank you
