### ISSUE TITLE
CLI - Xcode Not Update the app's build and version numbers

### ISSUE THREAD

**Issue by mirkomartino** [flutter/flutter#148130]
### Steps to reproduce

1. Creating a new project 
2. flutter build ipa --build-name 1.0.0 --build-number 2

### Expected results

I expect that command to update my Xcode project with the specified version.
![Senza nome](https://github.com/flutter/flutter/assets/84982500/e770ccb3-1dc7-47ba-8b0d-8688a0c3ac62)
![Senza nomeee](https://github.com/flutter/flutter/assets/84982500/d2b5eb73-2817-4a41-9602-891498b93ec3)

### Actual results

I'm always shown the major version of when the project is created.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1.1 23B81 darwin-arm64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.70.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @mirkomartino 
Can you try by updating `CFBundleShortVersionString` and `CFBundleVersion` to see if it helps to get expected result you are looking for ?
