### ISSUE TITLE
Flutter should use a separate package for clang-format

### ISSUE THREAD

**Issue by bc-lee** [flutter/flutter#148144]
# Proposal

As I understand it, Flutter downloads a prebuilt LLVM toolchain from a CIPD package built by the Fuchsia team [1]. This ensures a consistent toolchain across various platforms for a wide range of users.

Since LLVM is complex and large, updating to the Tip-of-Tree (ToT) toolchain can be beneficial when encountering an LLVM toolchain bug. Google invests heavily in LLVM, and the Chromium Toolchain team (please fix the name if it's wrong) dedicates significant effort to improving it. This is why autorolling LLVM is a good idea, and Flutter already implements it.

However, autorolling LLVM has some drawbacks. The current issue concerns clang-format.

## Challenges with Autorolling clang-format

Clang-format, part of the LLVM toolchain, is used by Flutter for source code formatting. When Flutter updates the LLVM toolchain, clang-format is updated as well. While this seems positive, it has a downside. Updating clang-format also updates the formatting rules, potentially causing issues.

Before continuing, let's explore how formatting rules are managed in various projects:

- Format All Source Code with the Latest Formatter: This approach updates the source code whenever the formatter is updated. While it ensures consistent formatting across the project, even minor formatter updates can introduce numerous changes.
- Format Only Changed Code Sections: Here, each commit is formatted with the formatter available at the commit time. This maintains consistency within each commit but can lead to inconsistencies across the project. This approach is widely used, with many projects utilizing tools derived from `clang-format-diff.py`.

## Flutter's Current Approach and Its Drawbacks

It appears Flutter utilizes the first approach. Updating the LLVM toolchain updates the formatting rules, which is positive but can introduce formatting rule changes. The current CI configuration likely rejects these changes, requiring manual intervention.

Clang-format is a mature and stable tool, so requiring frequent updates isn't necessary unless a major bug (like crashing) is encountered. The benefits of updating clang-format rarely outweigh the drawbacks. While performance improvements might be possible, they don't justify the disruption caused by frequent updates, in my opinion.

## Proposed Solution: Separate Package for clang-format

Therefore, I propose using a separate package for clang-format. Fortunately, Chromium's infrastructure can be leveraged again. Chromium stores the clang-format binary in GCS and fetches it using depot-tools, already used by Flutter. This integration would be straightforward since Flutter already uses depot-tools.

However, there's a limitation: reduced platform support. Currently, Chromium only provides prebuilt clang-format binaries in GCS for linux-x86_64, mac-x86_64, mac-arm64, and win-x86_64 platforms [2]. This means other platforms like linux-arm_64 wouldn't be supported initially.

Despite this limitation, I believe it's manageable. Most C++ contributors likely use linux-x86_64, mac-arm64, or win-x86_64, which are already supported. Those requiring clang-format on unsupported platforms can install it manually through their distribution's package manager or build it from source.

I believe this change would minimize the impact of clang-format updates, improve project stability, and facilitate smoother autorolling of the LLVM toolchain.

[1] https://github.com/flutter/engine/blob/c30e90ded5c1fbf112b547e03c3df46c0781b941/DEPS#L842
[2] https://source.chromium.org/chromium/chromium/src/+/main:DEPS;drc=db8a828b447b430a63b69a59438997c115eb7807;l=646

**Comment by jonahwilliams** [comment]
We do not intend to separate out clang-format from the rest of the clang toolchain packages in the near term. We're currently in the process of rolling clang forward.
