### ISSUE TITLE
 Not compatible：generate_multiple_pod_projects => true

### ISSUE THREAD

**Issue by 295060456** [flutter/flutter#148179]
### Steps to reproduce

If I add this sentence to the pod file in the ios folder in my Flutter project:
install! 'cocoapods',
:generate_multiple_pod_projects => true,
The project cannot be compiled and Flutter cannot be found. What should I do at this time?

Everything else is normal! ! !

### Actual results

![image](https://github.com/flutter/flutter/assets/13795605/495f948b-83a4-4e71-b1ed-c803601e1305)

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@295060456 
I think your issue / question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
