### ISSUE TITLE
RelativeRect.fromLTRB() bottom value has no effect

### ISSUE THREAD

**Issue by Rafapeerez** [flutter/flutter#148174]
### Steps to reproduce

CustomElevatedButton(
                icon: Icons.more_vert,
                onPressed: () {
                  showMenu(
                    context: context,
                    position: const RelativeRect.fromLTRB(double.infinity, double.infinity, 20, 20),
                    items: const [
                      PopupMenuItem<String>(
                        value: 'Añadir',
                        child: Text('Añadir'),
                      ),
                      PopupMenuItem<String>(
                        value: 'Filtrar',
                        child: Text('Filtrar'),
                      ),
                    ],
                    elevation: 8.0,
                  ).then((choice) {
                    if (choice != null) {
                      if (choice == 'Añadir') {
                        showDialogMethod();
                      } else if (choice == 'Filtrar') {
                      }
                    }
                  });
                },
              )

### Expected results

It should separate menu 20 from bottom, as happens with menu 20 from right but it has no effect

### Actual results

The menu is at the bottom right, separated 20 from the right but stuck below

### Code sample

CustomElevatedButton(
                icon: Icons.more_vert,
                onPressed: () {
                  showMenu(
                    context: context,
                    position: const RelativeRect.fromLTRB(double.infinity, double.infinity, 20, 20),
                    items: const [
                      PopupMenuItem<String>(
                        value: 'Añadir',
                        child: Text('Añadir'),
                      ),
                      PopupMenuItem<String>(
                        value: 'Filtrar',
                        child: Text('Filtrar'),
                      ),
                    ],
                    elevation: 8.0,
                  ).then((choice) {
                    if (choice != null) {
                      if (choice == 'Añadir') {
                        showDialogMethod();
                      } else if (choice == 'Filtrar') {
                      }
                    }
                  });
                },
              )

### Flutter Doctor output

-

**Comment by Titanantony** [comment]
_It looks like you're trying to position a PopupMenu in Flutter using showMenu with a RelativeRect. However, the positioning you've described might not work as expected because RelativeRect.fromLTRB sets the left, top, right, and bottom offsets of the rectangle relative to the parent widget's edges, but it doesn't take into account the menu's size.

To achieve the desired separation from the bottom right corner, you can calculate the position dynamically based on the menu's size. Here's an updated version of your code that should position the menu 20 units from the bottom and right edges:_


CustomElevatedButton(
  icon: Icons.more_vert,
  onPressed: () {
    final RenderBox button = context.findRenderObject() as RenderBox;
    final Offset buttonPosition = button.localToGlobal(Offset.zero);

    final double screenHeight = MediaQuery.of(context).size.height;
    final double screenWidth = MediaQuery.of(context).size.width;

    final double dx = screenWidth - buttonPosition.dx - 20;
    final double dy = screenHeight - buttonPosition.dy - 20;

    showMenu(
      context: context,
      position: RelativeRect.fromLTRB(dx, dy, 0, 0),
      items: const [
        PopupMenuItem(
          value: 'Añadir',
          child: Text('Añadir'),
        ),
        PopupMenuItem(
          value: 'Filtrar',
          child: Text('Filtrar'),
        ),
      ],
      elevation: 8.0,
    ).then((choice) {
      if (choice != null) {
        if (choice == 'Añadir') {
          showDialogMethod();
        } else if (choice == 'Filtrar') {
          // Handle 'Filtrar' choice
        }
      }
    });
  },
)
This code calculates the position of the button relative to the screen and then adjusts the menu's position accordingly to ensure it is 20 units from the bottom and right edges.





``

**Comment by Rafapeerez** [comment]
You're right!! The menu have been placed 20 units from the bottom edges. The 20 units of the right edge have not worked in this way, what I have done is to collect both options for it to work correctly: 
CustomElevatedButton(
                icon: Icons.more_vert,
                onPressed: () {
                  final RenderBox button = context.findRenderObject() as RenderBox;
                  final Offset buttonPosition = button.localToGlobal(Offset.zero);

                  final double screenHeight = MediaQuery.of(context).size.height;
                  final double screenWidth = MediaQuery.of(context).size.width;

                  final double dx = screenWidth - buttonPosition.dx;
                  final double dy = screenHeight - buttonPosition.dy - 150;

                  showMenu(
                    context: context,
                    position: RelativeRect.fromLTRB(dx, dy, 20, 0),
                    items: const [
                      PopupMenuItem(
                        value: 'Añadir',
                        child: Text('Añadir'),
                      ),
                      PopupMenuItem(
                        value: 'Filtrar',
                        child: Text('Filtrar'),
                      ),
                    ],
                    elevation: 8.0,
                  ).then((choice) {
                    if (choice != null) {
                      if (choice == 'Añadir') {
                        showDialogMethod();
                      } else if (choice == 'Filtrar') {
                        // Handle 'Filtrar' choice
                      }
                    }
                  });
                },
              )
Thank you very much!!!!

**Comment by danagbemava-nc** [comment]
Hi @Rafapeerez, has your issue been resolved?
