### ISSUE TITLE
Flutter run problem 

### ISSUE THREAD

**Issue by Michel20033** [flutter/flutter#148190]
My flutter app runs only for the first time in chrome, but when i try to run it again, it doesn't and shows this error in terminal 

The Flutter CLI developer tool uses Google Analytics to report usage and diagnostic
data along with package dependencies, and crash reporting to send basic crash
reports. This data is used to help improve the Dart platform, Flutter framework,
and related tools.

Telemetry is not sent on the very first run. To disable reporting of telemetry,
run this terminal command:

**Comment by darshankawar** [comment]
@Michel20033 Can you provide `flutter doctor -v` ?

> Telemetry is not sent on the very first run. To disable reporting of telemetry,
> run this terminal command:

This seems to be incomplete. Can you provide complete log ?

**Comment by Michel20033** [comment]
@darshankawar 
![Uploading 20240513_175035.jpg…]

**Comment by Michel20033** [comment]
![Uploading 20240513_175035.jpg…]()
@darshankawar

**Comment by Michel20033** [comment]
![github](https://github.com/flutter/flutter/assets/169605870/6feba294-a1e0-4ed1-a54e-5f42afecf763)
i hope you reply today because i have a test tomorrow

**Comment by darshankawar** [comment]
Can you try running `dart --disable-analytics` and then your web app to see if it helps ?
