### ISSUE TITLE
[go_router] DEBUG CONSOLE does not log/print all the routes

### ISSUE THREAD

**Issue by hashirshoaeb** [flutter/flutter#148111]
Because go_router is using developer.log internally for logging all route. And developer.log cannot print long strings. instead it collapses the string by adding `...` in between. 

Related issue: https://github.com/flutter/flutter/issues/47913

### Resulting output
 
![Screenshot 2024-05-10 at 10 34 20 AM](https://github.com/flutter/flutter/assets/35165481/abe39986-696b-4010-a5d8-e733f56f1c53)

### Expected output: 
![Screenshot 2024-05-10 at 10 34 56 AM](https://github.com/flutter/flutter/assets/35165481/e039d65d-b3af-4877-bb20-74ef048c11a5)

### Flutter doctor
<details>
<summary> output </summary>

```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-PK)
    • Flutter version 3.19.6 on channel stable at /Users/hashirshoaeb/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/hashirshoaeb/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0
```

</details>

**Comment by hashirshoaeb** [comment]
Solution can be this:
```diff
- log(debugKnownRoutes());
+ debugKnownRoutes().split('\n').forEach(log);
```

**Comment by darshankawar** [comment]
@hashirshoaeb 
Is this occuring for you in web platform only ? If so, you are probably hitting https://github.com/flutter/flutter/issues/126771 that you can check and follow-up in for further updates. You can also check [this](https://github.com/flutter/flutter/issues/120382) issue for related case.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by hashirshoaeb** [comment]
yes it is web only. Thanks!
