### ISSUE TITLE
flutter tool support release/debug switch for Fastlane

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#14817]
## Steps to Reproduce

I publish/test App with Fastlane now. It's very useful.
But sometimes Fastlane failed with:

```
[14:30:19]: ▸ flutter build ios --release
[14:30:19]: ▸ then re-run Archive from Xcode.
[14:30:19]: ▸ =========================
[14:30:19]: ▸ Command /bin/sh failed with exit code 255
```

Add a command switch between with debug and release may be helpful and graceful.

**Comment by pedia** [comment]
@cbracken  With [gym](https://docs.fastlane.tools/actions/gym/), switch between Debug/Release is not must.

**Comment by xster** [comment]
We're trying to integrate more tightly with Fastlane in the future but for the moment, there's still a few more steps needed before getting everything to work by just invoking gym. For instance, a number of plugin hook-up is done still in the `flutter` command line tool. 

In the meantime, the solution is to `flutter build ios [--release]` first and then invoke your lane.

**Comment by pedia** [comment]
OK
