### ISSUE TITLE
Flutter with Golang instead of Dart

### ISSUE THREAD

**Issue by kokizzu** [flutter/flutter#14816]
It would be really nice if there is Flutter but with [Go](https://golang.org) programming language, since Golang is somewhat simpler language in my opinion.

**Comment by cbracken** [comment]
Flutter is tightly tied to Dart, whose VM is key to the current development experience with hot reload. While there are are benefits to a lot of other languages, the project is focused on building a great developer experience based on Dart, and we're unlikely to have the resources to support other languages well.

**Comment by Hixie** [comment]
The bigger problem is that Go doesn't have classes or generics, and Flutter's entire design is based around clever use of class hierarchies, explicitly typed objects, and generics. It's basically a framework designed in a way that depends on all the things Go doesn't do. :-)

Having said that, we would be very happy to see people develop similar frameworks in other languages. If you found a good way to reimplement Flutter in Go, we would be interested in being involved at a high level in coordinating designs and sharing experiences. If anyone is interested in doing this and would like to talk about it, please don't hesitate to reach out to me by e-mail: ian@hixie.ch

**Comment by gedw99** [comment]
It was tried with the shiny project, which was a Google project..remember it ?

**Comment by hzmnet** [comment]
dart syntax is hard to read and study. so if dart using the same syntax like go will be good.

**Comment by apspark** [comment]
> dart syntax is hard to read and study. so if dart using the same syntax like go will be good.

Let's introduce Dart transpilers :)))

**Comment by divan** [comment]
I just posted an article exploring (as a thought experiment) Flutter in Go, may be relevant to this thread.
https://divan.github.io/posts/flutter_go/

**Comment by StevenZack** [comment]
I got one thought: create a code converter, we can convert Go code into Dart code for Flutter. 
(Just like Gopherjs)

**Comment by zoechi** [comment]
Better just use Dart and https://github.com/dart-lang/sdk/issues/34452 which is currently being worked on to call out to Go (or whatever) code.

**Comment by Gee5ive** [comment]
@StevenZack I think the problem would be the lack of generics in Go, Dart makes really heavy use of generics. The other way around might be easier, compiling Dart to go and being able to tap into the go ecosystem that way, would make writing Dart code on the server a lot more feasible.

**Comment by james-lawrence** [comment]
@Gee5ive generics wouldn't be an actual issue in practice. interfaces in golang handle the majority of what dart uses generics for. there are a few places where polymorphic parameters and functions would come into play. but that is likely going to appear in future versions of go.

**Comment by hzmnet** [comment]
anyway, the widgets tree is the big problem for flutter. I think nobody like it!
the best is to use a template like HTML to render the UI. 
example: Polymer, VUE ...

**Comment by james-lawrence** [comment]
.... what do you think the DOM is? its the same thing as a widget tree.... only it requires parsing to generate the tree whereas flutter doesn't.

**Comment by hzmnet** [comment]
> .... what do you think the DOM is? its the same thing as a widget tree.... only it requires parsing to generate the tree whereas flutter doesn't.

HTML template,XML template != DOM
using a template you dont need to write children and event and style and so on...
<header id="aa">
     <Text id="bb"> <Text>
</header>

type(
    Header struct()   // auto binding all style,attributes,event of header tag
    Text struct() // auto binding all style,attributes,event of header Text
)

in another xxxx.go/xxx.dart file

func init(){
  //register element to render
   register("herder",Header)
}
// init the element
func(self *Header)init(){
              self.Id:="aa"
              self.style:=...
}

**Comment by kokizzu** [comment]
out of topic tho, but i prefer real language code than markup language

**Comment by james-lawrence** [comment]
@hzmnet 

> HTML template,XML template != DOM


I never said they were the same. My point was in order to render HTML it gets parsed into an object tree (the dom), which is then manipulated by a programming language (usually javascript). this is exactly why flutter is doing except you don't need to convert templates to the object tree first.

> using a template you dont need to write children and event and style and so on...

not sure what your point you're trying to convey. you absolutely need to specify children, events, styles in HTML. parsers won't automagically insert elements that were not specified.

**Comment by iPR0D1G1** [comment]
bb

**Comment by elbashery** [comment]
This project is promising
https://www.youtube.com/watch?v=9D6eWP4peYM&t=212s

**Comment by vstyler96** [comment]
> dart syntax is hard to read and study. so if dart using the same syntax like go will be good.

I disagree with you, dart is very useful, and easy to learn when you read the docs, but, i agree with the possibility of interop with golang as they have with C++
