### ISSUE TITLE
didn't get permission request in android 11 & lower 

### ISSUE THREAD

**Issue by 22kuldeepsingh** [flutter/flutter#148250]
didn't get any solution yet, i have 
android sdk 33,
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
android:requestLegacyExternalStorage="true"

**Comment by darshankawar** [comment]
@22kuldeepsingh 
Check https://developer.android.com/about/versions/11/privacy/permissions and see if it helps in answering your issue / question.

**Comment by 22kuldeepsingh** [comment]
i found the exact solution,Thanks for the revert.

**Comment by darshankawar** [comment]
Closing as resolved.
