### ISSUE TITLE
[Icons] Add `More` adaptive icon to `PlatformAdaptiveIcons`.

### ISSUE THREAD

**Issue by MacDeveloper1** [flutter/flutter#148212]
### Use case

I need to use the adaptive `more` icon which is 3 points vertically in Android and 3 points horizontally in iOS,MacOS.

### Proposal

Add a row into `PlatformAdaptiveIcons`.
```dart
IconData get more => !_isCupertino() ? Icons.more_vert : Icons.more_horiz;
```

**Comment by victorsanni** [comment]
I might be misunderstanding your request @MacDeveloper1, but this might already exist in `material/icons.dart`:

https://github.com/flutter/flutter/blob/ffae7c60c21020a188d8e8732743346affaf33a8/packages/flutter/lib/src/material/icons.dart#L71

**Comment by MacDeveloper1** [comment]
@victorsanni oops. Thanks! :)
