### ISSUE TITLE
Need an official GitHub Action for setting up Flutter SDK env and publish a Flutter package onto pub.dev.

### ISSUE THREAD

**Issue by aprosail** [flutter/flutter#148296]
### Use case

To reuse when publishing a flutter package onto pub.dev.

### Proposal

A reusable and officially maintained GitHub Action template: Just like [the Dart official setup action](https://github.com/dart-lang/setup-dart) and its [template yaml file for publishing](https://github.com/dart-lang/setup-dart/blob/main/.github/workflows/publish.yml). There is also [a third party one](https://github.com/flutter-actions/setup-flutter), but it doesn't compatible when publishing packages.

**Comment by darshankawar** [comment]
@aprosail 
I am not sure if this use case is applicable in flutter repo. You'll probably need to raise this in github actions repo: https://github.com/actions/runner/issues or follow-up in https://github.com/dart-lang/setup-dart/issues/68

Closing from here.
