### ISSUE TITLE
[rfw] Remove use of `ButtonBar`

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#148220]
```
   info • lib/src/flutter/material_widgets.dart:25:9 • 'ButtonBar' is deprecated and shouldn't be used. Use OverflowBar instead. This feature
          was deprecated after v3.21.0-10.0.pre. Try replacing the use of the deprecated member with the replacement. •
          deprecated_member_use
   info • lib/src/flutter/material_widgets.dart:59:13 • 'ButtonBar' is deprecated and shouldn't be used. Use OverflowBar instead. This feature
          was deprecated after v3.21.0-10.0.pre. Try replacing the use of the deprecated member with the replacement. •
          deprecated_member_use
   info • lib/src/flutter/material_widgets.dart:60:62 • 'ButtonBar' is deprecated and shouldn't be used. Use OverflowBar instead. This feature
          was deprecated after v3.21.0-10.0.pre. Try replacing the use of the deprecated member with the replacement. •
          deprecated_member_use
   info • lib/src/flutter/material_widgets.dart:62:13 • 'ButtonBar' is deprecated and shouldn't be used. Use OverflowBar instead. This feature
          was deprecated after v3.21.0-10.0.pre. Try replacing the use of the deprecated member with the replacement. •
          deprecated_member_use
   info • lib/src/flutter/material_widgets.dart:63:50 • 'ButtonBar' is deprecated and shouldn't be used. Use OverflowBar instead. This feature
          was deprecated after v3.21.0-10.0.pre. Try replacing the use of the deprecated member with the replacement. •
          deprecated_member_use
```

**Comment by Hixie** [comment]
I'm not sure what the context is here.

**Comment by stuartmorgan** [comment]
There isn't much context to provide; since https://github.com/flutter/flutter/issues/143312 the people who deprecated APIs are no longer responsible for following up on addressing their uses in Flutter-team-owned code, so for flutter/packages we instituted a routine sweep by gardeners to ensure they don't explode later. This came up in that sweep.

If you mean context on why `ButtonBar` was deprecated, I don't have any (one of the downsides of the new process).

**Comment by stuartmorgan** [comment]
> At a minimum, they would need to do so before removing the deprecated features at the end of the deprecation cycle.

As I raised during discussions around the policy change after it was made, waiting until the end of the deprecation cycle to remove deprecated code from published packages *dramatically* worsens the experience of clients, because it maximizes the number of people whose builds will be broken when updating Flutter.

It's one of the many cases where trying to apply a policy designed for flutter/engine and flutter/flutter to flutter/packages works very poorly.

**Comment by Hixie** [comment]
I mean, there was no meaningful discussion around that policy change, so, yeah.
I agree it makes things dramatically worse in certain cases.
It should probably be reverted and then actually discussed properly, with an actual design doc, etc.

**Comment by stuartmorgan** [comment]
Regardless of overall policy: this issue tracks a specific piece of known technical debt that now exists in `rfw`, and I was CC'ing you since my understanding is that you wanted to be CC'd on `rfw` issues not because I expect you to necessarily fix it. (The old policy would have resulted in a similar issue, just filed by the person doing the deprecation.)

**Comment by Hixie** [comment]
Totally, yeah, sorry if I implied otherwise.
