### ISSUE TITLE
Google refresh token

### ISSUE THREAD

**Issue by Roopa-21** [flutter/flutter#148284]
### Use case

Solution for getting refresh tokens after logging in with Google.
Currently, there is no refreshToken returned so not able to fetch refreshToken and generate new accessToken.
A new access token is generated only if the user logs out or logs in again with Google which is not convenient for the user.

### Proposal

This can be a new feature of the present package

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/45847. 

Kindly subscribe to the original issue for updates.

Thank you
