### ISSUE TITLE
CustomOneChildLayout or CustomMultiChildLayout should be renamed.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1482]
One -> Many
Single -> Multi

Single feels natural having used Multi. But One does not.

If we prefer One then Multi could be called Many.

Maybe those mappings are unique to my brain - if so feel free to close this.

**Comment by apwilson** [comment]
Though, in defence on my drain mappings.  The first line of the comments fot CustomOneChildLayout is:
```dart
/// Defers the layout of its single child to a delegate.
```

**Comment by abarth** [comment]
CustomSingleChildLayout makes sense to me.
