### ISSUE TITLE
Support listing and launching emulators through flutter tools

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#14822]
To support https://github.com/Dart-Code/Dart-Code/issues/490 I'm going to look at adding support for listing/launching emulators (and eventually creation).

@devoncarew Do we want this in the cli as well as daemon (eg. something like `flutter emulator list`, `flutter emulator launch xxx`)?

**Comment by mit-mit** [comment]
+1 for adding this to the flutter tool

**Comment by mit-mit** [comment]
maybe integrate into the existing `flutter devices` command?

**Comment by mit-mit** [comment]
Hi @DanTup any news on this?

**Comment by DanTup** [comment]
This was completed a while ago (https://github.com/flutter/flutter/pull/17466).
