### ISSUE TITLE
Animated Images "Example Code" just hangs on spinner in Gallery example app

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#14820]
Using current master (b6d8615aed8062e6e9d3dff7d340edf2982c4847) if I launch the Gallery app and go to "Animated Media" and then click on the "Example Code" icon on the top right, I just get a spinner - it never seems to finish loading (it doesn't break into the debugger or output anything to the console).

(This is not specific to `--preview-dart-2`, happens without it too)

**Comment by cbracken** [comment]
@DanTup -- @xster and I aren't able to repro this, do you have more details that might help with a repro?

**Comment by DanTup** [comment]
Hmm, strange. I'm on Windows 10, running on a Moto X Play which is Android 6.0.1 (yeah, I know.. blame Moto!). Running from VS Code (so via `flutter run --machine` etc., though hopefully that doesn't matter).

I'll try debugging the code a little on Monday to see what's going on.

**Comment by DanTup** [comment]
I modified the sample code to have some `print`s:
```dart
void didChangeDependencies() {
    print("Fetching sample code:");
    print(widget.exampleCodeTag);
    getExampleCode(widget.exampleCodeTag, DefaultAssetBundle.of(context))
        .then<Null>((String code) {
      if (mounted) {
        setState(() {
          print("Got sample code:");
          print(code);
          _exampleCode = code;
        });
      }
    });
    super.didChangeDependencies();
  }
```

And the output I get is this:

```text
I/flutter ( 8195): Fetching sample code:
I/flutter ( 8195): animated_image
I/flutter ( 8195): Got sample code:
I/flutter ( 8195): null
```

I tried searching for `animated_image` across the code but can't see where this is supposed to be defined for the bundle. Any ideas?

**Comment by DanTup** [comment]
Oh, I'm gonna guess this is a Windows issue!

![windows](https://user-images.githubusercontent.com/1078012/36661727-07a0d9d2-1ad4-11e8-9377-3b720d166537.png)

**Comment by DanTup** [comment]
I've sent a PR that fixes this - lmk if it's ok if you want changes: #14878
