### ISSUE TITLE
Target aot_android_asset_bundle failed: IconTreeShakerException: Font subsetting failed with exit code 255

### ISSUE THREAD

**Issue by aniealss** [flutter/flutter#148200]
### Steps to reproduce

flutter build appbundle --flavor xxx

### Expected results

build success

### Actual results

Target aot_android_asset_bundle failed: IconTreeShakerException: Font subsetting failed with exit code 255.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1.1 23B81 darwin-arm64)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by aniealss** [comment]
When I build Android flavor, Target aot_android_asset_bundle failed: IconTreeShakerException: Font subsetting failed with exit code 255 is reported.

**Comment by darshankawar** [comment]
@aniealss 
Can you provide us reproducible code sample or a demo repo that we can clone and verify this further ?

**Comment by aniealss** [comment]
Oh, sorry! I tested it today and there is no problem again.
