### ISSUE TITLE
MacOS: Codemagic - The installer package includes files that are only readable by the root user (3.22.0)

### ISSUE THREAD

**Issue by AndreiMisiukevich** [flutter/flutter#148354]
### Steps to reproduce

Regression: https://github.com/flutter/flutter/issues/132725

Follow https://docs.flutter.dev/deployment/macos#create-a-build-archive-with-codemagic-cli-tools up to and including app-store-connect publish --path "$PACKAGE_NAME"

### Expected results

Publishing to the App Store works

### Actual results

2024-05-14 21:01:55.328 *** Error: ERROR: [ContentDelivery.Uploader] Asset validation failed (90255) The installer package includes files that are only readable by the root user. This will prevent verification of the application's code signature when your app is run. Ensure that non-root users can read the files in your app.

### Code sample

I haven't been able to reproduce this since to get to the point of publishing to the App Store, you need to set up all of the certificates etc. I'm guessing this occurs in a blank Flutter project though.

I can confirm, however, that reverting to Flutter 3.19.6 doesn't have this issue.

Also, I've tested on master channel - it does not work too.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```
== Use Xcode 15.3 ==
> sudo xcode-select --switch /Applications/Xcode-15.3.app/Contents/Developer
Xcode 15.3
Build version 15E204a

== Use default version of CocoaPods ==
> gem list '^cocoapods$' --no-verbose
cocoapods (1.14.2)

== Use Java version 11 ==
> java -version
openjdk version "11.0.21" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu11.68+17-CA (build 11.0.21+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.68+17-CA (build 11.0.21+9-LTS, mixed mode)

== Codemagic CLI tools ==
> codemagic-cli-tools version
codemagic-cli-tools 0.51.0
```

```
== Use Flutter channel stable ==
> curl --fail --show-error --silent --output flutter_macos_arm64_3.19.6-stable.zip --connect-timeout 10.00 --max-time 120.00 https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.19.6-stable.zip

> 7z -bd x flutter_macos_arm64_3.19.6-stable.zip

7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs LE)

Scanning the drive for archives:
1 file, 1169959256 bytes (1116 MiB)

Extracting archive: flutter_macos_arm64_3.19.6-stable.zip
--
Path = flutter_macos_arm64_3.19.6-stable.zip
Type = zip
Physical Size = 1169959256

Everything is Ok

Folders: 2795
Files: 10321
Size:       2650462486
Compressed: 1169959256

Flutter 3.19.6 • Dart 3.3.4
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel master, 3.22.0-33.0.pre.20, on macOS 14.3.1 23D60 darwin-arm64, locale en-US)
    • Flutter version 3.22.0-33.0.pre.20 on channel master at /Users/builder/programs/flutter_3_16_7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4a1e3eaaa2 (26 minutes ago), 2024-05-14 15:58:18 -0500
    • Engine revision ae9ff69a08
    • Dart version 3.5.0 (build 3.5.0-153.0.dev)
    • DevTools version 2.36.0-dev.5

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 123.0.6312.58

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by gvsakhil** [comment]
I am facing the same issue after upgrading to 3.22.0 in CodeMagic

**Comment by darshankawar** [comment]
@AndreiMisiukevich Thanks for the bug report.
I am trying to get this to replicate using CodeMagic, as locally, using XCode, I saw no issues. Meanwhile, have you already checked if [this](https://github.com/orgs/codemagic-ci-cd/discussions/1498#discussioncomment-5381028) could be of help ?

**Comment by gvsakhil** [comment]
@darshankawar I tried that solution already. Codemagic is working fine with that solution but Apple rejects app with the same issue...

**Comment by AndreiMisiukevich** [comment]
@darshankawar I tried that workaround, but got the build error

```

Building macOS application...                                   
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:0000FE00-343A79319AA17942, name:My Mac }
{ platform:macOS, arch:x86_64, id:0000FE00-343A79319AA17942, name:My Mac }
chmod: //Contents/Frameworks/App.framework/Versions/A/Resources/flutter_assets/shaders/ink_sparkle.frag: No such file or directory
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **
```

**Comment by AndreiMisiukevich** [comment]
@darshankawar, I confirm that I am getting the same error message from Apple as @gvsakhil said.
I guess this trick can help to work around the issue, though. But it's probably related to a different file (files) than those listed in that ticket.

**Comment by cody-fjorge** [comment]
Also having the same issue with a 3.22 upgrade in codemagic deployments. MacOS builds work fine, app store publishing fails with the following error:

*** Error: ERROR: [ContentDelivery.Uploader] Asset validation failed (90255) The installer package includes files that are only readable by the root user. This will prevent verification of the application's code signature when your app is run. Ensure that non-root users can read the files in your app.
2024-05-15 16:42:02.370  INFO: [ContentDelivery.Uploader] 
=============
UPLOAD FAILED with 1 error.
=============
{
  "tool-version": "7.006.15006",
  "tool-path": "/Applications/Xcode-15.2.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework",
  "os-version": "14.2.1",
  "product-errors": [
    {
      "message": "Asset validation failed",
      "userInfo": {
        "NSUnderlyingError": "Error Domain=IrisAPI Code=-19241 \"Asset validation failed\" UserInfo={status=409, detail=The installer package includes files that are only readable by the root user. This will prevent verification of the application's code signature when your app is run. Ensure that non-root users can read the files in your app., code=STATE_ERROR.VALIDATION_ERROR.90255, title=Asset validation failed, NSLocalizedFailureReason=The installer package includes files that are only readable by the root user. This will prevent verification of the application's code signature when your app is run. Ensure that non-root users can read the files in your app., NSLocalizedDescription=Asset validation failed}",
        "NSLocalizedDescription": "Asset validation failed",
        "iris-code": "STATE_ERROR.VALIDATION_ERROR.90255",
        "NSLocalizedFailureReason": "The installer package includes files that are only readable by the root user. This will prevent verification of the application's code signature when your app is run. Ensure that non-root users can read the files in your app."
      },
      "code": 90255
    }
  ]
}

**Comment by darshankawar** [comment]
Thanks for the update. It'll take a bit time to verify this using CodeMagic but meantime, based on the reports, I'll keep the issue open and label for team's attention, as this seems to be a potential regression.

/cc @gspencergoog

**Comment by jmagman** [comment]
The macOS framework is now distributed as a xcframeork https://github.com/flutter/flutter/pull/143244

The difference I can spot is:

**3.22**
```
bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.xcframework/macos-arm64_x86_64:
total
drwx------ FlutterMacOS.framework
```
**3.19.6**
```
bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework
drwxr-xr-x FlutterMacOS.framework
```

Interestingly, when I `flutter build macos --release` I see the same permissions in the app build directory `build/macos/Build/Products/Release/test_create.app/Contents/Frameworks/`
But when I archive and look in the Frameworks directory, the permissions on both versions are `drwxr-xr-x FlutterMacOS.framework`

@AndreiMisiukevich  if you run this command and try again, does it work?
```
chmod 755 bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework
```

**Comment by vashworth** [comment]
If https://github.com/flutter/flutter/issues/148354#issuecomment-2115972770 is the issue, fixing it should hypothetically also fix issue https://github.com/flutter/flutter/issues/147142.

There was a [PR](https://github.com/flutter/flutter/pull/147144) out for it, but it needs tests. Also, may make more sense to fix via the engine rather than the tool.

**Comment by AndreiMisiukevich** [comment]
@jmagman I tried that but got the following error

```
Running pod install...                                              4.7s
Building macOS application...                                   
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:0000FE00-343A79319AA17942, name:My Mac }
{ platform:macOS, arch:x86_64, id:0000FE00-343A79319AA17942, name:My Mac }
chmod: bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework: No such file or directory
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **
```

**Comment by AndreiMisiukevich** [comment]
I see what problem is
Here is the corrected command

```
chmod 755 $FLUTTER_ROOT/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework
```

**Comment by jmagman** [comment]
> I tried to add this script to xCode post-build actions, also I tried to run this script on codemagic post-build step. The result is the same.

Can you try running it once from your Flutter repo (sorry I should have said that), then remove your Xcode build action and other changes you made, `flutter clean`, and then try again?

**Comment by AndreiMisiukevich** [comment]
> > I tried to add this script to xCode post-build actions, also I tried to run this script on codemagic post-build step. The result is the same.
> 
> Can you try running it once from your Flutter repo (sorry I should have said that), then remove your Xcode build action and other changes you made, `flutter clean`, and then try again?

Sure, I can try it again. But unfortunately I am not entirely sure what exactly I should do. Could you please guide me?

I am trying to make it working through my Codemagic pipeline. I don't use dependency caching, so I believe nothing should be cached.

So far I tried to embed `chmod 755 $FLUTTER_ROOT/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework` this script into post-build actions of xCode project and post-build actions in codemagic. It didn't fail during the build phase, it means the file was located successfully.

**Comment by jmagman** [comment]
If you need to run it post-build it would be something like:
```
chmod 755  ${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FlutterMacOS.framework
```

**Comment by AndreiMisiukevich** [comment]
✅ It works. Thanks a lot ✅ 

Putting the following script into "Pre-Build Script" step made the trick

```
chmod 755 $FLUTTER_ROOT/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework
```

<img width="1267" alt="image" src="https://github.com/flutter/flutter/assets/10124814/c5c2ca02-5b22-4aa0-a321-84227519942c">

**Comment by jmagman** [comment]
The fix for this will be hotfixed into the next stable https://github.com/flutter/flutter/pull/148717.  In the meantime, you can work around this by putting this script into your pre-build:
```
chmod 755 $FLUTTER_ROOT/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework
```
Thank you @AndreiMisiukevich for helping us track this down!

**Comment by adil192** [comment]
Seems like this was left out of the [changelog](https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md) for v3.22.1 but my workflows are working now :)

**Comment by nilsreichardt** [comment]
> Seems like this was left out of the [changelog](https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md) for v3.22.1 but my workflows are working now :)

There is an open PR to fix this :+1:

* https://github.com/flutter/flutter/pull/148999
