### ISSUE TITLE
[DOCS]: The example in the documentation reports an error when running.

### ISSUE THREAD

**Issue by kjxbyz** [flutter/flutter#148305]
### Steps to reproduce

The example in the documentation reports an error when running.

https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html

![2024-05-14 17 47 01](https://github.com/flutter/flutter/assets/47768002/979014e2-8d26-4e76-9ef3-5047dbb60efe)

### Expected results

The examples in the documentation work fine.

### Actual results

This is just a placeholder.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
This appears to be fixed on https://main-api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html but will need to be fixed for https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html

Error from the docs below

```
color_scheme.dart' ('/opt/flutter/packages/flutter/lib/src/material/color_scheme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'surfaceContainerHighest'.
              color: colorScheme.surfaceContainerHighest,
                                 ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by goderbauer** [comment]
This appears to be fixed? I am no longer seeing the error.
