### ISSUE TITLE
fading_edge_scrollview scrollcontroller can't assign pageviewcontroller plz check your new update flutter 3.22 version

### ISSUE THREAD

**Issue by this-sunil** [flutter/flutter#148385]
### Steps to reproduce

fading_edge_scrollview
scrollcontroller can't assign pageviewcontroller plz check your new update flutter 3.22 version

### Expected results

fading_edge_scrollview
scrollcontroller can't assign pageviewcontroller plz check your new update flutter 3.22 version

### Actual results

fading_edge_scrollview
scrollcontroller can't assign pageviewcontroller plz check your new update flutter 3.22 version

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```fading_edge_scrollview
scrollcontroller can't assign pageviewcontroller plz check your new update flutter 3.22 version

</details>


### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@this-sunil 
Please elaborate and provide relevant details such as reproducible code sample, actual vs expected result using latest stable version (3.22.0) and previous version wherein you see it was working properly so that we can properly address the issue.

**Comment by this-sunil** [comment]
First you download latest 3.22 version and then run your project this bug can show on debug console Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't this issue can't solve what you use in flutter SDK involve this this dependencies bug will raise again and again

**Comment by darshankawar** [comment]
Please provide us a complete runnable reproducible code sample that shows the reported error.

**Comment by dinhtrung3008** [comment]
I am also encountering a similar error as the author of the post


[
![Screenshot 2024-05-18 at 20 24 13](https://github.com/flutter/flutter/assets/73328070/0b93dad4-3ca0-44e3-96a9-fcac93402e2b)
](url)
