### ISSUE TITLE
share package crashes on iOS (iPad)

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#14834]
## Steps to Reproduce

I'm using the share package. When trying to share something on iOS (iPad), I get this:

`Feb 22 19:21:59 iPad Runner(CoreFoundation)[6473] <Notice>: *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIActivityViewController (<UIActivityViewController: 0x11a814c00>). In its current trait environment, the modalPresentationStyle of a UIActivityViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'`

If I use split screen (with a more iPhone-like aspect ratio), it works fine.

**Comment by cbracken** [comment]
@gabrc52 thanks for reporting!

/cc @xster

**Comment by xster** [comment]
The iOS native code needs to set activityViewController.popoverPresentationController for iPads. Fix in progress.
