### ISSUE TITLE
Audit for deprecated_member_use in flutter, engine and packages

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#148361]
After completing https://github.com/flutter/flutter/issues/143312, we committed to checking in on our deprecated member usage every other quarter to migrate or file and issue to schedule work that is needed.

This issue is tracking that work for q2-24.

**Comment by stuartmorgan** [comment]
For flutter/packages the list is [here](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+deprecated+api%22); we have a process to update it regularly.

**Comment by Piinks** [comment]
That's great! Thanks for sharing!
