### ISSUE TITLE
I am Flutter sdk version 3.19.6 and this error display

### ISSUE THREAD

**Issue by jivaraj123** [flutter/flutter#148308]
### Steps to reproduce

 Error: A value of type 'ValueListenable<bool>' can't be assigned to a variable of type 'ValueNotifier<bool>'.

### Actual results

../../../.pub-cache/hosted/pub.dev/simple_animations-4.2.0/lib/anicoto/animation_mixin.dart:139:56: Error: A value of type 'ValueListenable<bool>' can't be assigned to a variable of type 'ValueNotifier<bool>'.
 - 'ValueListenable' is from 'package:flutter/src/foundation/change_notifier.dart' ('../../../FlutterSDk/flutter_linux_3.19.6-stable/flutter/packages/flutter/lib/src/foundation/change_notifier.dart').
 - 'ValueNotifier' is from 'package:flutter/src/foundation/change_notifier.dart' ('../../../FlutterSDk/flutter_linux_3.19.6-stable/flutter/packages/flutter/lib/src/foundation/change_notifier.dart').
    final ValueNotifier<bool> newNotifier = TickerMode.getNotifier(context);

### Logs

../../../.pub-cache/hosted/pub.dev/simple_animations-4.2.0/lib/anicoto/animation_mixin.dart:139:56: Error: A value of type 'ValueListenable<bool>' can't be assigned to a variable of type 'ValueNotifier<bool>'.
 - 'ValueListenable' is from 'package:flutter/src/foundation/change_notifier.dart' ('../../../FlutterSDk/flutter_linux_3.19.6-stable/flutter/packages/flutter/lib/src/foundation/change_notifier.dart').
 - 'ValueNotifier' is from 'package:flutter/src/foundation/change_notifier.dart' ('../../../FlutterSDk/flutter_linux_3.19.6-stable/flutter/packages/flutter/lib/src/foundation/change_notifier.dart').
    final ValueNotifier<bool> newNotifier = TickerMode.getNotifier(context);

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on Ubuntu 22.04.4 LTS 6.5.0-28-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from
      https://www.freedesktop.org/wiki/Software/pkg-config/
[✓] Android Studio (version 2022.3)
[!] Android Studio (version 2021.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.89.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.

**Comment by stuartmorgan** [comment]
> ../../../.pub-cache/hosted/pub.dev/simple_animations-4.2.0

Issues with third-party packages need to be reported to the developers of those packages.

Closing as the error is not in code controlled by the Flutter team.
