### ISSUE TITLE
Flutter Web Build times too slow, hangs at a certain point.

### ISSUE THREAD

**Issue by nialljawad96** [flutter/flutter#148309]
### Steps to reproduce

1. Unable to reproduce on a newly made Flutter Project. 

### Expected results

Flutter build web used to execute fairly quickly (under a minute). Now it takes 20 minutes if not longer.

I am using this command:
flutter build web --web-renderer canvaskit --release 

### Actual results

Using --verbose, it hangs on the following point:

```
[   +9 ms] web_entrypoint: Complete
[        ] dart2js: Starting due to {}
[   +7 ms] executing:mypath/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev mypath/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=mypath/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f6344b75dcf861d8bf1f1322780b8811f982e31a/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true --native-null-assertions
--no-source-maps -o mypath/project/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/app.dill --packages=.dart_tool/package_config.json --cfe-only
mypath/project/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/main.dart
[+65152 ms] Compiled 72,847,773 input bytes (64,335,062 characters source) to 74,774,040 kernel bytes in 64.7 seconds using 1257.250 MB of memory
                     Dart file .dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/main.dart compiled to dill: .dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/app.dill.
[        ] executing: mypath/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev mypath/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/mypath/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f6344b75dcf861d8bf1f1322780b8811f982e31a/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true --native-null-assertions
--no-source-maps -O4 -o mypath/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/main.dart.js
mypath/project/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/app.dill

```

Any suggestions as to how to stop this from happening?

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4 23E214 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2023.3.5)
[✓] VS Code (version 1.89.0)

**Comment by darshankawar** [comment]
> Flutter build web used to execute fairly quickly (under a minute). Now it takes 20 minutes if not longer.

@nialljawad96 Do you know in which version it used to execute quickly and whether it is taking long time in latest version only (3.22.0) ?



> flutter build web --web-renderer canvaskit --release

I think by default it will build for canvaskit, so can you try `flutter build web --release` and check if it still hangs or goes further ?

**Comment by nialljawad96** [comment]
@darshankawar Thanks for you reply. I know for a fact it used to be extremely quick (less than a minute) using 3.16.4 and below. However, I have other Flutter Web projects that use 3.22.0 and they compile quickly (less than a minute). I've tried with just:

`
flutter build web --release --verbose
`

But it's still slow (>20 minutes). Here is the rest of the output, when it eventually completes 20 minutes later:

`
mypath/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/main.dart
[+61646 ms] Compiled 72,543,562 input bytes (64,031,593 characters source) to 74,433,656 kernel bytes in 61.2 seconds using 1233.043 MB of memory
                     Dart file .dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/main.dart compiled to dill: .dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/app.dill.
[        ] executing: mypath/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev mypath/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/Users/nj/Development/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f6344b75dcf861d8bf1f1322780b8811f982e31a/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true --native-null-assertions
--no-source-maps -O4 -o mypath/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/main.dart.js
mypath/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/app.dill
[+1309547 ms] ../flutter/packages/flutter/lib/src/widgets/widget_inspector.dart:290:11:
                       Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
                       Consider removing this 'noSuchMethod' implementation.
                         dynamic noSuchMethod(Invocation invocation) {
                                 ^
                       Compiled 91,412,504 input bytes (8,517,245 characters source) to 8,740,830 characters JavaScript in 1309 seconds using 1799.672 MB of memory
[ +127 ms] dart2js: Complete
`

Is there a way to see more detailed logs about where it taking a long time? I'm assuming this has something to do with dart2js? I know that you guys have been doing a lot of stuff around WASM and js interop so just worried something here is causing the issue. If so, is there a way to see which files/lines are being compiled?

**Comment by mokamhawy** [comment]
Me too using:
new Flutter update 3.22
windows desktop 

But it's still slow (>20 minutes)

**Comment by darshankawar** [comment]
Thanks for the update @nialljawad96 @mokamhawy Is there a way for you to provide a reproducible code sample that shows this slow build time ? That'll help to properly address and make the issue actionable.

**Comment by mokamhawy** [comment]
> Me too using: new Flutter update 3.22 windows desktop
> 
> But it's still slow (>20 minutes) [previous flutter version was NOT like that]

My issue was resolved. It was NOT related to Flutter/Dart.
I just removed some unused flutter packages.

**Comment by nialljawad96** [comment]
@darshankawar I can't isolate it from my project. Are you able to provide any information on the following:

Is there a way to see more detailed logs about where it taking a long time? I'm assuming this has something to do with dart2js? I know that you guys have been doing a lot of stuff around WASM and js interop so just worried something here is causing the issue. If so, is there a way to see which files/lines are being compiled?

**Comment by darshankawar** [comment]
@nialljawad96 
Can you check https://docs.flutter.dev/tools/devtools/performance and see if using it, you are able to find more insights ?
