### ISSUE TITLE
[A11y] TextField should adapt to hint text sizes

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#148353]
b/317131589

### Steps to reproduce

run app and activate the textfield

### Expected results

According to internal guideline the the hint text can't be ellipisized when font size increases. 

The material guideline suggest no ellipsis and no multiline
https://m3.material.io/components/text-fields/guidelines.

The native android expands the text field size to accommodate long string
![image](https://github.com/flutter/flutter/assets/47866232/dee802d1-bd24-4e17-b0f7-24052e098212)

Since we can't control how long the text developer can put into the hint text, I think we should follow native android to make it multi line and expand the textfield size.

### Actual results

![image](https://github.com/flutter/flutter/assets/47866232/48469d44-518f-4f49-b6ab-49d1ec9cf386)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: HomePage(),
  ));
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Home")),
      body: Center(
        child: Column(
          children: [
            TextField(
              decoration: const InputDecoration(
                labelText: 'Email',
                suffixText: '@gmail.com',
                hintText: 'Enter your email.... Please, I really need it',
              ),
              controller: TextEditingController(text: 'abc'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

```

</details>

**Comment by justinmc** [comment]
Related: https://github.com/flutter/flutter/issues/46182
