### ISSUE TITLE
Support google maps web to wasm

### ISSUE THREAD

**Issue by JgomesAT** [flutter/flutter#148384]
### Steps to reproduce

Build to WASM version

### Expected results

build succesfully

### Actual results

../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:26:8: Error: Dart library 'dart:web_gl' is not available on
this platform.
import 'dart:web_gl' show RenderingContext;
       ^
Context: The unavailable library 'dart:web_gl' is imported through these packages:

    web_plugin_registrant.dart => package:google_maps_flutter_web => package:google_maps => dart:web_gl

../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:977:12: Error: Type 'RenderingContext' not found.
  external RenderingContext? get gl;
           ^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:979:19: Error: Type 'RenderingContext' not found.
  external set gl(RenderingContext? value);
                  ^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:991:12: Error: Type 'RenderingContext' not found.
  external RenderingContext? get gl;
           ^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:993:19: Error: Type 'RenderingContext' not found.
  external set gl(RenderingContext? value);

**Comment by mraleph** [comment]
Naturally you should file this bug against the package itself, not Flutter. 

The package repository is https://github.com/a14n/dart-google-maps (which you can see on https://pub.dev/packages/google_maps)
