### ISSUE TITLE
flutter 3.22.0 - color: Theme.of(context).backgroundColor, is causing issue

### ISSUE THREAD

**Issue by Faiz-rhm** [flutter/flutter#148376]
Launching lib/main.dart on SM A525F in debug mode...
../../../.pub-cache/hosted/pub.dev/skeletons-0.0.3/lib/src/widgets.dart:56:42: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../../flutterSDK/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.
                color: Theme.of(context).backgroundColor,
                                         ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/skeletons-0.0.3/lib/src/widgets.dart:100:46: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../../flutterSDK/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.
                    color: Theme.of(context).backgroundColor,
                                             ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/faizrhm/flutterSDK/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by fernan542** [comment]
Hello @Faiz-rhm.
Can you attach your `flutter doctor -v` results too?
Does this error also occur to newly created flutter project?

**Comment by Faiz-rhm** [comment]
this issue occurred in the old project.

flutter doctor -v
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-x64, locale en-AF)
    • Flutter version 3.22.0 on channel stable at /Users/faizrhm/flutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/faizrhm/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Users/faizrhm/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • SM A525F (mobile) • R58R32R0XMY • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 14.4.1 23E224 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 124.0.6367.207

[✓] Network resources
    • All expected network resources are available.

**Comment by navaronbracke** [comment]
This is intentional. `backgroundColor` was deprecated before and is now removed per https://docs.flutter.dev/release/breaking-changes/3-19-deprecations#themedata

Since the error seems to point to the `skeletons` package on Pub.dev, please reach out to the package maintainer.
They will have to support Flutter 3.22

**Comment by Faiz-rhm** [comment]
That caused the issue, thanks.
