### ISSUE TITLE
Flutter not generating android manifest files on fresh install

### ISSUE THREAD

**Issue by GreenMohawk** [flutter/flutter#148372]
### Steps to reproduce

1. install Flutter 3.22.0 on Pop!_OS 22.04
2. Install Android SDK 34.0.0
3. Create new directory and run "Flutter Create" or "Flutter Create NAME --platforms=android"
4. Open either Android Studio or VSCode to run an android emulator
5. Run the "Flutter Run" command in the root source of the project through either VSCode or Android Studio.

### Actual results

Whenever creating a new flutter project I am completely unable to generate any android dependencies, including the android manifest, etc. The only thing generated appears to be the empty folders and a few gradle files.

### Logs

<details open>
<summary>Logs</summary>

```console

$ flutter create bugtest --platforms=android
Creating project bugtest...
Resolving dependencies in `bugtest`... (1.7s)
Downloading packages... 
Got dependencies in `bugtest`.
Wrote 15 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider:
https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd bugtest
  $ flutter run

Your application code is in bugtest/lib/main.dart.

#I then open the project inside of android studio to have an emulator for the run instance

$ flutter run
Build failed due to use of deleted Android v1 embedding.

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on Pop!_OS 22.04 LTS
    6.8.0-76060800daily20240311-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
[✓] Connected device (1 available)
    ! Device emulator-5554 is offline.
[✓] Network resources

! Doctor found issues in 1 category.


```

</details>

**Comment by danagbemava-nc** [comment]
Hi @GreenMohawk, how did you setup flutter? What root directory are you creating the project in? Were you using a different version of flutter prior to 3.22.0 and did this happen with that version? 

Are you able to run on either linux desktop or chrome?

**Comment by danagbemava-nc** [comment]
Hi @GreenMohawk, please also share full output of `flutter create -v` & `flutter run -v`.

The output may be huge so kindly put it into a .txt or .log file and attach it here. 

If you attached it with the email, it did not make it to github

**Comment by GreenMohawk** [comment]
Hello @danagbemava-nc, here are the outputs for the commands you requested. 
[flutter_create_v.md](https://github.com/flutter/flutter/files/15342091/flutter_create_v.md)
[flutter_run_v.md](https://github.com/flutter/flutter/files/15342092/flutter_run_v.md)

**Comment by danagbemava-nc** [comment]
Hi @GreenMohawk, please provide the output of `flutter config --list`

**Comment by GreenMohawk** [comment]
Thanks for the responses and help in this situation @danagbemava-nc. Here is the output for that command. I additionally tried to enable android, then do a clean, create and run, with the same output of "Build failed due to use of deleted Android v1 embedding." . 

`flutter config --list
All Settings:
  enable-web: (Not set)
  enable-linux-desktop: (Not set)
  enable-macos-desktop: (Not set)
  enable-windows-desktop: (Not set)
  enable-android: (Not set)
  enable-ios: (Not set)
  enable-fuchsia: (Not set) (Unavailable)
  enable-custom-devices: (Not set)
  cli-animations: (Not set)
  enable-native-assets: (Not set) (Unavailable)
  enable-flutter-preview: (Not set) (Unavailable)
`

**Comment by danagbemava-nc** [comment]
Hi @GreenMohawk, can you share the directory structure for the project you created? I created a new flutter project with just android as the target and when I removed the android folder and tried to run on an android device I got the error below (which makes sense because the android directory is missing). However, since your project doesn't seem to be generating the android directory, it should not be complaining about the v1 embedding 

```
Launching lib/main.dart on Pixel 7 in debug mode...
AndroidManifest.xml could not be found.
Please check /Users/nexus/projects/h/android/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```
