### ISSUE TITLE
The host view controller is (null) 引起crash

### ISSUE THREAD

**Issue by jihengcong** [flutter/flutter#148313]
### Steps to reproduce

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The application must have a host view since the keyboard client must be part of the responder chain to function. The host view controller is (null)'
*** First throw call stack:
(
0 CoreFoundation 0x0000000111bce8ab __exceptionPreprocess + 242
1 libobjc.A.dylib 0x0000000117010ba3 objc_exception_throw + 48
2 Foundation 0x0000000114d330cc _userInfoForFileAndLine + 0
3 Flutter 0x0000000117129a25 -[FlutterTextInputPlugin hostView] + 125
4 Flutter 0x000000011712a04a -[FlutterTextInputPlugin addToInputParentViewIfNeeded:] + 80
5 Flutter 0x0000000117129989 -[FlutterTextInputPlugin getOrCreateAutofillableView:isPasswordAutofill:] + 136
6 Flutter 0x0000000117129587 -[FlutterTextInputPlugin updateAndShowAutofillViews:focusedField:isPasswordRelated:] + 132
7 Flutter 0x0000000117129116 -[FlutterTextInputPlugin setTextInputClient:withConfiguration:] + 176
8 Flutter 0x000000011712875d -[FlutterTextInputPlugin handleMethodCall:result:] + 259
9 Flutter 0x0000000117702231 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
10 Flutter 0x0000000117140df2 ___ZN7flutter25PlatformMessageHandlerIos21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE_block_invoke + 86
11 libdispatch.dylib 0x000000011ca8bd18 _dispatch_call_block_and_release + 12
12 libdispatch.dylib 0x000000011ca8cf5b _dispatch_client_callout + 8
13 libdispatch.dylib 0x000000011ca9dd55 _dispatch_main_queue_drain + 1463
14 libdispatch.dylib 0x000000011ca9d790 _dispatch_main_queue_callback_4CF + 31
15 CoreFoundation 0x0000000111b2db1f CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9
16 CoreFoundation 0x0000000111b28436 __CFRunLoopRun + 2482
17 CoreFoundation 0x0000000111b276a7 CFRunLoopRunSpecific + 560
18 GraphicsServices 0x0000000121ef828a GSEventRunModal + 139
19 UIKitCore 0x000000012bad9ad3 -[UIApplication _run] + 994
20 UIKitCore 0x000000012bade9ef UIApplicationMain + 123
21 Demo 0x00000001051d51a8 main + 104
22 dyld 0x00000001108ba2bf start_sim + 10
23 ??? 0x00000002084dc52e 0x0 + 8729249070
24 ??? 0x0000000000000003 0x0 + 3
)

### Expected results

期望正常运行，不闪退

### Actual results

正常打开flutter页面

### Code sample

[✓] Flutter (Channel stable, 3.0.5, on macOS 13.6 22G120 darwin-arm, locale
    zh-Hans-CN)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.0.5, on macOS 13.6 22G120 darwin-arm, locale
    zh-Hans-CN)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by danagbemava-nc** [comment]
This has been fixed byhttps://github.com/flutter/engine/pull/39768. 

You are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.22). I'll be closing this since it has already been fixed. If you still experience this after upgrading to stable 3.22, kindly leave a comment below and I will reopen this. 

Thank you
