### ISSUE TITLE
`et` design issues are preventing more uniform behavior around commands

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#148444]
As seen on https://github.com/flutter/flutter/issues/148442, I accidentally removed special handling (specific to `build_command.dart`) that creates a missing `../out/{outDir}` based on the selected build (i.e. `-c host_debug_unopt_arm64` or similar), which I'll restore as part of https://github.com/flutter/flutter/issues/148442.

One thing I noticed is we special cased this for `et build`, that is, it _doesn't_ work this way for `et query`, `et test`, and other commands that invoke `gn` (and never did, i.e. I didn't break _all_ the commands, just _one_ 😋 ). I was looking into solving this holistically, and ran into a number of design issues:

- Each command that has a similar preamble that is not shared:

  ```dart
  @override
  Future<int> run() async {
    final String configName = argResults![configFlag] as String;
    final bool useRbe = argResults![rbeFlag] as bool;
    if (useRbe && !environment.hasRbeConfigInTree()) {
      environment.logger.error('RBE was requested but no RBE config was found');
      return 1;
    }
    final String demangledName = demangleConfigName(environment, configName);
    final Build? build =
        builds.where((Build build) => build.name == demangledName).firstOrNull;
    if (build == null) {
      environment.logger.error('Could not find config $configName');
      return 1;
    }
  ```

  That itself is a not a problem, but it means adding uniform behavior for commands requires extra caution (that we didn't do).

- The inner-workings of `et` use divergent terminology and code-paths:

  For example, `build_command`, `query_command`, and `test_command` need to invoke `gn desc` in order to discover which
  targets exist based on a target pattern (i.e. `//flutter/impeller/...` resolves to `[{...}, {...}, ...]`), but then defer to another tool in another package (`engine_build_configs`) which _again_ has knowledge of running tools like `gn`.

  It looks like goal of `engine_build_configs` (which, confusingly to me, is _not_ limited to configs, that is it has extensive knowledge of running processes like `ninja`, `gn`, and even `run_tests.py`) is partially in conflict with that of `et` - if it's meant to be used _only_ by `et`, I think it would be better to merge all of the runner code _into_ `et`.

  The README.md of the package reads: 

  > This package contains libraries and example code for working with the engine_v2 build config json files

  I wonder if this just grew organically, or it needs an update - I'm having a hard time understanding. My preference is that unless there is a reason to have two tools that understand our build infrastructure, that we have all runner-specific code in one place.

Anyway, just filing this for 🍿 chatter from the contributors, I don't know what to make/to do at the moment.

**Comment by zanderso** [comment]
`engine_build_configs` is scoped to implementing the `engine_v2` configs (parsing them and running them). It is used by `et` as well as various checks that the json files are well-formatted. `et` needs to run `gn` in ways that go beyond what is needed to implement the `engine_v2` configs, e.g. `gn desc` isn't part of or needed by the build config format.

My preference is to keep the packages separate so that code unrelated to implementing the `engine_v2` configs doesn't leak into `engine_build_configs`. For example, I'm guessing from this issue that the thought is that everything that can run `gn` should just all go in one place. I think a refactor like that would violate the abstraction that we currently have. I'm actually a little baffled that this is controversial/confusing since this separation seems pretty natural to me.

**Comment by matanlurey** [comment]
Okay that's starting to make more sense to me, apologies, I had stepped away after the initial implementation and I didn't understand (until literally right now) why there were multiple libraries invoking `gn`.

I totally agree with the goal of `engine_v2` configs being separate, I guess my assumption was that it worked like this:
```mermaid
sequenceDiagram
  participant et
  participant engine_build_configs
  participant external
  et->>engine_build_configs: ask for instructions for a given build
  engine_build_configs->>external: read and parse JSON
  engine_build_configs->>et: return instructions for build
  et-->>external: query for targets (if necessary)
  et->>external: run builds/tests
```

So I was surprised to see `et` mostly handled just user input, and the bulk of the actual operations were in another package.

It does complicate things slightly from my perspective, for example, _both_ make process invocations (`gn`, `ninja`, etc), which makes things like writing tests more difficult because it becomes hard to understand what processes will be run or what test logs to expect, given they can come from multiple locations.

To be clear, I don't think we need to change anything drastic (maybe I just check this diagram into `DESIGN.md` or something), it was just surprising to me given how I thought `et` worked and what I thought (based on the name) `engine_build_configs` did.

**Comment by zanderso** [comment]
> It does complicate things slightly from my perspective, for example, both make process invocations

The build config runner has a dry run mode which emits events but doesn't actually run any processes. Not sure if that helps the tests you have in mind, though.

**Comment by matanlurey** [comment]
@zanderso Slept on it and coming back with a more concrete task this design complicates.

One of things I _want_ to be able to do, but can't find an easy way to do, is to understand different types of erroneous output of `gn`, i.e. yesterday's https://github.com/flutter/flutter/issues/148431 from @gaaclarke. It would be great if `et` could recognize `WARNING at build arg file (use "gn args <out_dir>" to edit)` and prompt the user to reset their `out_dir`, but I'd have to add that logic both in `et` _and_ `engine_build_configs`.

Alternatively, I could move all calls of `gn` into `engine_build_configs`, but as you already alluded to, that probably doesn't make sense - `gn desc` is an operation that makes no sense in the context of build configs. A third option might be to create `tools/pkg/gn` but I was really trying to avoid creating more packages that are used by ~1 tool.
