### ISSUE TITLE
[Impeller] Vulkan validation layers are (still) crashing Android emulators.

### ISSUE THREAD

**Issue by matvuric** [flutter/flutter#148481]
### Steps to reproduce

1. Run the project with an argument "--enable-impeller".

### Expected results

App is running on the emulator

### Actual results

After running the project my screen is locked and doesn't react on any input actions. Computer is still running, but doesn't show anything new.

### Code sample

<details open><summary>Code sample</summary>

```dart
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
√ Built build\app\outputs\flutter-apk\app-dev-profile.apk (93.4MB)
[IMPORTANT:flutter/shell/platform/android_context_vulkan_impeller.cc(67)] Using the Impeller rendering backend (Vulkan).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4170], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @matvuric, did this happen prior to flutter 3.22? 
Does this happen with the counter app?

What gpu is your device using?

**Comment by jonahwilliams** [comment]
Which Android emulator version and API level are you using? I would recommend updating to the very latest AVD that you can.

**Comment by matvuric** [comment]
@jonahwilliams, I've tried pixel 3a and pixel 8 pro. API 34 x86_64

**Comment by jonahwilliams** [comment]
The device skin doesn't matter, its the AVD version. Can you try updating to latest and/or listing the AVD version you have installed?

**Comment by matvuric** [comment]
@jonahwilliams I have Android 14.0 API 34 x86_64 and installed Android VanillaIceCream x86_64. With the last one I have no problem with GPU, but emulator is crashing.
`
Launching lib\main.dart on sdk gphone16k x86 64 in debug mode...
Running Gradle task 'assembleDebug'...                             16,7s
√ Built build\app\outputs\flutter-apk\app-debug.apk
Installing build\app\outputs\flutter-apk\app-debug.apk...          434ms
I/flutter ( 4662): [IMPORTANT:flutter/shell/platform/android/android_context_vulkan_impeller.cc(67)] Using the Impeller rendering backend (Vulkan).
Error connecting to the service protocol: failed to connect to http://127.0.0.1:52232/rzqyY807_Lo=/
`

**Comment by ciriousjoker** [comment]
App crashes for us as well.
- Everything is running fine when running the app in Flutter 3.22.0 without Impeller
- Enabling Impeller makes it so not just the app crashes on launch, but the entire emulator

Unless you want me to update to API level 35, I already have the latest version of the latest production Android version.
![CleanShot 2024-05-16 at 21 40 18@2x](https://github.com/flutter/flutter/assets/16866223/2dfb2554-92f3-4079-b118-1a2e86776bf3)

I'm running this on a 2022 m2 mac mini.

**Comment by jonahwilliams** [comment]
The emulator version is the important part, not the API level or phone form factor. You can look up the emulator version with:

```
$ANDROID_HOME/sdk/emulator/emulator --version
```

**Comment by danagbemava-nc** [comment]
@ciriousjoker @matvuric please run the command in https://github.com/flutter/flutter/issues/148481#issuecomment-2116099731 and provide the output. 

Thank you

**Comment by matvuric** [comment]
'''
INFO    | Storing crashdata in: C:\Users\matvuric\AppData\Local\Temp\\AndroidEmulator\emu-crash-34.1.20.db, detection is enabled for process: 7556
INFO    | Android emulator version 34.1.20.0 (build_id 11610631) (CL:N/A)
ERROR   | No AVD specified. Use '@foo' or '-avd foo' to launch a virtual device named 'foo'
'''

**Comment by jonahwilliams** [comment]
Thanks! This is unfortunate. We suspect the crash is related to vulkan validation layers being enabled by default for debugging, and while we've reached out to the Android emulator team about this several times they've been unable to fix it.

On the current master channel, we've disabled the validation layers and intend to keep them opt in, so you might be able to try there to see if it works. Otherwise, if you choose an ABI that we support profile/release builds for (x86_64, arm32, arm64), running in a profile build will disable validation layers.

**Comment by jonahwilliams** [comment]
We're going to cherry pick a change to turn off validation layers on 3.22, that should work around this problem

**Comment by jonahwilliams** [comment]
CP request and PR opened.

**Comment by jonahwilliams** [comment]
I believe the latest flutter hotfix should have resolved this issue. if not, please comment on this bug or file a new issue.
