### ISSUE TITLE
Tooltip getTransformTo assertion failed when in OverlayPortal.targetsRootOverlay

### ISSUE THREAD

**Issue by Andrflor** [flutter/flutter#148410]
### Steps to reproduce

create a OverlayPortal.targetsRootOverlay widget with a Tooltip inside

### Expected results

Tooltip should display on hover

### Actual results

No tooltip assertion failed renderer.parent != null

 _buildTooltipOverlay fails on
  box.localToGlobal because
   getTransformTo assetion
   assert(renderer.parent != null) fails

Workaround
Add Overlay in the Tooltip hierarchy
Or use OverlayPortal instead of OverlayPortal.targetsRootOverlay

### Code sample

<details open><summary>Code sample</summary>

```dart
       OverlayPortal.targetsRootOverlay(
        controller: OverlayPortalController(),
        overlayChildBuilder: (_) => Tooltip(message: 'Some msg', child: anyChild),
        child: anyChildAgain,
        )
```

</details>

### Flutter Doctor output

NA

**Comment by danagbemava-nc** [comment]
Hi @Andrflor, 

Please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you
