### ISSUE TITLE
flutter build rules need to add a dependency on frontend

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#14847]
## Steps to Reproduce

Build a flutter application using --preview-dart-2 with an older version of flutter.
Then update to the latest version of flutter and perform a hot reload.
Possibly incompatible `dill` files will be used resulting in surprising crashes.

See [https://github.com/flutter/flutter-intellij/issues/1809](https://github.com/flutter/flutter-intellij/issues/1809) showing one such crash.

Fix @aam suggests:
Add dependency for kernel artifacts on frontend_server.dart.snapshot

**Comment by zoechi** [comment]
I assume this one is stale.
