### ISSUE TITLE
Unexpected top padding in ListView put inside scaffold with no appBar

### ISSUE THREAD

**Issue by radzish** [flutter/flutter#14842]
If you put `ListView` somewhere inside `Scaffold` having no `appBar`, `ListView` has top padding. There is no padding if `appBar` is present. There is no padding if you specify `EdgeInsets.zero` padding for `ListView` explicitly. See following code snipped for example   

```dart
...
    return new MaterialApp(
      home: new Scaffold(
//        appBar: new AppBar(
//          title: new Text("test"),
//        ),
        body: new Column(
          children: <Widget>[
            new Container(
              child: new Center(
                  child: new Text("some top widget")
              ),
              decoration: new BoxDecoration(
                color: Colors.red,
              ),
              height: 100.0,
            ),
            new Expanded(
              child: new ListView(
                children: items,
//                padding: EdgeInsets.zero, // explicit padding as a workaround
              ),
            ),
          ],
        ),
      ),
    );
...
```
See screenshot:

![bug](https://user-images.githubusercontent.com/5489307/36594127-91e3270c-18a5-11e8-8805-5278006da5bd.png)

## Flutter Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.20.1)
[✓] Connected devices
```

**Comment by itsJoKr** [comment]
Just had this problem, top SliverPadding is set to 20.0. Looking at docs I see:

/// By default, [ListView] will automatically pad the list's scrollable
/// extremities to avoid partial obstructions indicated by [MediaQuery]'s
/// padding. To avoid this behavior, override with a zero [padding] property.

**Comment by radzish** [comment]
Well, as long as this is documented I will close the issue

**Comment by Hixie** [comment]
I'm not sure it's well-documented yet. If you can't find it in the documentation, please don't hesitate to reopen.

**Comment by sergiandreplace** [comment]
I had this same issue and after some search this is the only exact answer I've found. Maybe is worth to create a short entry on documentation about window measurement and specific cases

**Comment by Jasonthefirst** [comment]
Found this topic because I thought this is maybe a bug or I did oversee something. So maybe some more info is needed. (I would prefer a method to turn this off inside the listview, too. This would be easier.)

**Comment by d-silveira** [comment]
I am using the ListView.builder and wrapping it with MediaQuery.removePadding( context, removeTop: true, ... didn't produce any change, I'm still getting SliverPadding(0.0, 24.0, 0.0, 0.0)

Am I doing somthing wrong?

**Comment by tiagosito** [comment]
I did not find it in the documentation, is it there?

**Comment by dimrsilva** [comment]
https://api.flutter.dev/flutter/widgets/ListView-class.html

The docs now have a comment about this behavior:
> By default, ListView will automatically pad the list's scrollable extremities to avoid partial obstructions indicated by MediaQuery's padding. To avoid this behavior, override with a zero padding property.

I think it can be closed.

**Comment by jigarpatel17** [comment]
> Yeah this is intentional. If you put a widget before the `ListView`, you should wrap the `ListView` with a `MediaQuery.removePadding` widget (with `removeTop: true`).

This solution is amazing. Thank you so much.

**Comment by blokberg** [comment]
> Yeah this is intentional. If you put a widget before the `ListView`, you should wrap the `ListView` with a `MediaQuery.removePadding` widget (with `removeTop: true`).

Thank you very much!
This code is solved my problem:
```
Widget _myListView(){
  return MediaQuery.removePadding(
    context: context,
    removeTop: true,
    child: ListView.builder(
     .......
    )
  );
}
```

**Comment by j3g** [comment]
I do not feel the documentation is helpful. I would be lost without an example line of code.
I did this to remove all padding. Then pad each of your rows using container widget. I'm not an expert at all so please advise.
`padding: const EdgeInsets.all(0.0)`

**Comment by UttamPanchasara** [comment]
We can also fix this by wrapping whole Scaffold body part in **SafeArea** if there is no Appbar in your screen.

```
return Scaffold(
      body: SafeArea(
        child: Container(
          child: ListView.builder(
          .......
          );
        ),
      ),
    );
```

**Comment by awafL** [comment]
The solution that worked for me was to set the ListView padding to zero as here
`
              child: ListView.builder(
                padding: EdgeInsets.zero,
                itemBuilder: (context, index) {
                  return Card(...);
                },
              ),
`

Most likely this is not the most recommended way, but since I can define the size of the ListView through its parent that is a Container, and the Card() widget has its own defined size. One of most likely many solutions for this problem. Felt like sharing it as none of the options above suited my situation.

**Comment by douglasrosa0110** [comment]
> Yeah this is intentional. If you put a widget before the `ListView`, you should wrap the `ListView` with a `MediaQuery.removePadding` widget (with `removeTop: true`).

Tks a lot! **This applies too when we need to present one scaffold into other scaffold**

**Comment by hovanhung98hust** [comment]
> Just had this problem, top `SliverPadding` is set to `20.0` by default. Looking at docs I see:
> 
> ```
> /// By default, [ListView] will automatically pad the list's scrollable
> /// extremities to avoid partial obstructions indicated by [MediaQuery]'s
> /// padding. To avoid this behavior, override with a zero [padding] property.
> ```

thanks, this work for me

**Comment by inoas** [comment]
This was really unexpected.

**Comment by Hixie** [comment]
Once you know about SafeArea it makes more sense. The problem is that in trying to make SafeArea work automatically without having to think about it, we also require that in cases where you do things it can't handle you have to handle it. I don't think we have a good solution to this other than improving the docs. If this is still confusing then we should add another section to the "troubleshooting" part of the Scaffold docs. Please do file a new bug if you'd like us to do that.

**Comment by nox-machina** [comment]
> Yeah this is intentional. If you put a widget before the `ListView`, you should wrap the `ListView` with a `MediaQuery.removePadding` widget (with `removeTop: true`).

Well that was a life saver, thanks.

**Comment by kamleshwebtech** [comment]
> Yeah this is intentional. If you put a widget before the `ListView`, you should wrap the `ListView` with a `MediaQuery.removePadding` widget (with `removeTop: true`).

This solution helped me and removed my top space of GridView.builder widget:

```
Container(
            child: MediaQuery.removePadding(
              removeTop: true,
              context: context,
              child: GridView.builder(
```

Happy to get your help. Thanks dear.
