### ISSUE TITLE
[iOS] BoxShadow flickers when scrolling

### ISSUE THREAD

**Issue by koodimetsa** [flutter/flutter#148412]
### Steps to reproduce

1. Put a Container with BoxShadow inside SingleChildScrollView.
2. Make content large enough to scroll.
3. When scrolling, BoxShadow flickers.

### Expected results

BoxShadow should have steady color without changes.

### Actual results

BoxShadow flickers quite a lot.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    const dimension = 300.0;

    return MaterialApp(
      home: Scaffold(
        body: SingleChildScrollView(
            child: Column(
          children: [
            const SizedBox(height: 200),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  height: dimension,
                  width: dimension,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(dimension / 2),
                    boxShadow: const [
                      BoxShadow(
                        color: Color.fromRGBO(15, 119, 109, 0.3),
                        spreadRadius: 0,
                        blurRadius: 20,
                        offset: Offset(0, 2), /
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 1500),
          ],
        )),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/flutter/flutter/assets/9356589/e68726ed-e7c6-40e6-94c6-ca310d0d2b7c)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Stable
```console
Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.0 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
```

Master
```console
Flutter (Channel master, 3.22.0-35.0.pre.10, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.0-35.0.pre.10 on channel master at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ddd6c86950 (12 hours ago), 2024-05-14 22:00:17 -0400
    • Engine revision d35a1a603c
    • Dart version 3.5.0 (build 3.5.0-154.0.dev)
    • DevTools version 2.36.0-dev.5
```

</details>

**Comment by koodimetsa** [comment]
Similar issue was reported, but closed because things worked on master. Tested and this issue on both master and stable.
https://github.com/flutter/flutter/issues/135844

**Comment by jonahwilliams** [comment]
Lets check partial repaint, otherwise its probably related to the blur re-write.

**Comment by jason-simmons** [comment]
This is not related to partial repaint.

This issue happens when the app is run with a large radius for the `BorderRadius.circular`.  If it exceeds a threshold, then when `_BoxDecorationPainter` calls `canvas.drawRRect` it will go through Impeller's `Canvas::DrawOval`/`Canvas::DrawCircle` code path.

One factor contributing to the flickering is that `Canvas::DrawOval`/`Canvas::DrawCircle` sometimes uses `Canvas::AttemptDrawBlurredRRect`.  The blur renders inconsistently depending on whether the input content was generated by `Canvas::AttemptDrawBlurredRRect` or the standard method.

**Comment by jason-simmons** [comment]
There also seems to be an issue involving generation of mipmaps for the blur filter input snapshot on Vulkan.

This app renders correctly on Android/Vulkan with these changes:
* disable use of `Canvas::AttemptDrawBlurredRRect`
* patch `CreateSampler` in `sampler_vk.cc` to use the default zero value for `sampler_info.maxLod`
  * or set `GaussianBlurFilterContents::kBlurFilterRequiredMipCount` to 1

@gaaclarke

**Comment by jonahwilliams** [comment]
Setting VK_LOD_CLAMP_NONE would disable mipmapping. its possible we have a bug in mip generation. Its very manual in Vulkan.

(See also: https://github.com/flutter/engine/pull/51761, https://github.com/flutter/engine/pull/51749)

**Comment by jonahwilliams** [comment]
Found a problem with the barriers on Vulkan. In terms of the flickering, there is a rounding issue in the Skia logic for isSimple that we depend on. 

D/skia    (18362): SkRect::MakeLTRB(74, 179.666672f, 374, 479.666656f);
D/skia    (18362): const SkPoint corners[] = {
D/skia    (18362):     { 150, 149.999969f },
D/skia    (18362):     { 150, 150 },
D/skia    (18362):     { 150, 149.999969f },
D/skia    (18362):     { 150, 150 },
D/skia    (18362): };

This rrect is bouncing between this and 150 everywhere. I might just add our own check in.
