### ISSUE TITLE
flutter build aot --preview-dart-2 does not compute dependencies correctly

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#14844]
Dependencies file generated by the `gen_snapshot` would be empty for `--preview-dart-2` mode because `gen_snapshot` does not load any source code itself.

Instead we need to extend front-end server to collect and generate dependencies.

**Comment by aam** [comment]
`build/aot/snapshot.d` that defines dependencies for 'app.dill` is produced by the frontend compiler as part of `build aot --preview-dart-2`.

That file is being overwritten by `gen_snapshot` though

**Comment by zoechi** [comment]
Is this still relevant?

**Comment by mraleph** [comment]
I think this is obsolete.
