### ISSUE TITLE
Too long app package name causes black screen problem

### ISSUE THREAD

**Issue by devyueyue** [flutter/flutter#148458]
### Use case

Use the camera to take photos normally

### Proposal

When the applicationId exceeds 64 or 128 characters, the screen will go black when opening the camera.

For example：
applicationId "com.china.yunnan.kunming.xizang.lasa.zhejiang.hangzhou.bingjiang.guangdong.course"

**Comment by devyueyue** [comment]
Currently, it is found that Android devices, Xiaomi or Oppo mobile phones have black screen problems.

**Comment by danagbemava-nc** [comment]
Hi @devyueyue, which plugin are you experiencing this issue with? What version of the plugin are you using? 

Please also provide the output of `flutter doctor -v`.

Thank you
