### ISSUE TITLE
Is there a way to make the version and build number in `macos/Runner.xcworkspace` automatically match the version and build number from `pubspec.yaml`?

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#148407]
### Use case

Is there a way to make the version and build number in `macos/Runner.xcworkspace` automatically match the version and build number from `pubspec.yaml`?

### Proposal

Is there a way to make the version and build number in `macos/Runner.xcworkspace` automatically match the version and build number from `pubspec.yaml`?

**Comment by darshankawar** [comment]
@stephane-archer 
The version and build seems to be fetched from info.plist file currently, but not sure if that is related to pubspec.yaml or from local.properties file wherein `flutter.versionName` and `versionCode` are being passed that you can check and confirm ?

**Comment by stephane-archer** [comment]
from what I can observe if you leave the version and build number blank in `macos/Runner.xcworkspace`, the `pubspec.yaml` version and build number are used.
