### ISSUE TITLE
`flutter analyze --flutter-repo` broken locally

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#148436]
At tip of tree, I cannot run the analysis script. There are conflicts between `flutter/dev/snippets/.packages` and `flutter/packages/flutter_tools/.packages`.

I've tried a bunch of things to resolve this:
- `flutter update-packages`
- `flutter update-packages --force-upgrade`
- `flutter clean` and then the above again
- Checked out a new branch, tried above again
- Nuked my `.pub-cache`, tried above again

Here is an example of one of the conflicts:

```
Package "webkit_inspection_protocol" has conflicts:
  1 source wants "/Users/katelovett/.pub-cache/hosted/pub.dartlang.org/webkit_inspection_protocol-1.0.0/lib":
    /Users/katelovett/_github/flutter/dev/snippets/.packages
  1 source wants "/Users/katelovett/.pub-cache/hosted/pub.dartlang.org/webkit_inspection_protocol-1.0.1/lib":
    /Users/katelovett/_github/flutter/packages/flutter_tools/.packages
```

**Comment by Piinks** [comment]
Might be related to
- https://github.com/flutter/flutter/pull/147893
- https://github.com/flutter/flutter/pull/147690

@gspencergoog what do you think?

**Comment by gspencergoog** [comment]
Are you still having problems?  I can run `flutter analyze --flutter-repo` at head with no problem.

**Comment by Piinks** [comment]
I am, it must be my own sad state of affairs. I'll update this issue if I figure it out, in case anyone else runs into it.

**Comment by christopherfujino** [comment]
Closing this as currently unactionable, feel free to re-open if you have either repro steps or some further clues we can use to troubleshoot.
