### ISSUE TITLE
Flutter Assertion Error

### ISSUE THREAD

**Issue by opensourcepj** [flutter/flutter#148413]
### Steps to reproduce

render object as follows
  creator: Stack ← ValueListenableBuilder<bool> ← Stack ← CoolSwiper ← Padding ←
  MediaQuery ← Padding
    ← SafeArea ← Container ← Column ← Padding ← Container ← ⋯
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=339.4, 0.0<=h<=Infinity)
  size: MISSING
  alignment: AlignmentDirectional.topStart
  textDirection: ltr
  fit: loose

### Expected results

assertion explained

### Actual results

The following assertion was thrown during performLayout():
'package:flutter/src/rendering/stack.dart': Failed assertion: line 600 pos 12:
'size.isFinite': is
not true.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@opensourcepj 
Please try to provide a reproducible code sample that triggers the reported error. Without code sample, we won't be able to make the issue actionable.
