### ISSUE TITLE
Pick Video from camera in Android Tablet

### ISSUE THREAD

**Issue by m-hamza-tanbits** [flutter/flutter#148464]
### Steps to reproduce

i am using image_picker for pick video from camera 
Its working on mobile 
while on android tablet 
when i  create a video from and pick in app 
the file size is 0.
image path is printing in local cache but when i save this video the video save as a file in 0 Byte.

               

### Expected results

file need to shown that i have created from camera

### Actual results

created file show

### Code sample

<details open><summary>Code sample</summary>

  ```
 final  result = await picker.pickVideo(source: image_picker.ImageSource.camera);
                    Uint8List datList=await result.readAsBytes();
                    log("file length  ${datList.length}"); **print 0**
```
                    if i print result.path 
                    the result print
                    /storage/emulated/0/Movies/123 (2).mp4 to content://media/external_primary/video/media/1000000226
                    while i am saving this file the file save as 0 byte.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="384" alt="image" src="https://github.com/flutter/flutter/assets/153491287/91a70360-016d-4ac1-8721-9298648e1c24">
</details>

### Logs

<details open><summary>Logs</summary>

[log] data List data List 0
I/flutter ( 9733): result video path Instance of 'XFile'
D/MediaScannerConnection( 9733): Scanned /storage/emulated/0/Movies/123 (2).mp4 to content://media/external_primary/video/media/1000000226

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

no

</details>

**Comment by darshankawar** [comment]
Thanks for the report @m-hamza-tanbits 
Can you provide flutter version on which you are seeing this error ?
Also, please provide complete runnable reproducible code sample along with plugin version.

**Comment by m-hamza-tanbits** [comment]
Flutter (Channel stable, **3.19.6**, on macOS 14.4.1 23E224 darwin-x64, locale en-PK)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
**I am using physical device Android tablet version 12** 

Code 
import 'package:image_picker/image_picker.dart' as image_picker;
final image_picker.ImagePicker picker = image_picker.ImagePicker();
final image_picker.XFile? result = await picker.pickVideo(source: image_picker.ImageSource.camera);
the result print
log(result.path);
     response: /storage/emulated/0/Movies/123 (2).mp4 to content://media/external_primary/video/media/1000000226
     when i am saving this file in gallery or showing in video player its not wokring error video cant play because file size is 0 byte.
![image](https://github.com/flutter/flutter/assets/153491287/6d4d1bf2-9271-4e00-a342-4180e4566bda)
                Error: while i am saving this file the file save as 0 byte.
                **Note: its working on android phone** 
                **Error occur on tablet.**

**Comment by adnan-haider007** [comment]
@darshankawar any updates? i am also facing this issue in my android tablet.

**Comment by darshankawar** [comment]
@m-hamza-tanbits Although I don't have physical Android tablet to verify this, but I'll try it on tablet emulator to see if I am able to replicate it or not, but meantime, can you try using the plugin example on same device and check if using it, you still get same behavior or not ?

Since it is specific to Tablet, can you also check if there's any setting that could be leading the file size to zero ?
If you try with native Android app, is it possible to check if using it, you also get same behavior or not ?

**Comment by m-hamza-tanbits** [comment]
- i have already used plugin example 
- it working on both Android, IOS mobile 
- its also working on IOS tablet 
- the issue raise only on android tablet.
- Tablet version is 12 
- flutter version that i am using is 3.19.6 and package is image_picker: ^1.1.1.

**Comment by Hamza117411** [comment]
@darshankawar Any update on it?

**Comment by huycozy** [comment]
@m-hamza-tanbits I checked this issue using [image_picker example](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) on my Android tablet device `Galaxy Tab A7 Lite (Android 14)` but the video is returned with non-zero size and can be played as expected; I checked this on both cases on the example app: `Take a Video` and `Pick Video from gallery`.

Could you share your device info (OS, model)? Please also observe the output log to see if there is any error/warning when running plugin example app.
