### ISSUE TITLE
Support Full Keyboard Access on iOS for keyboard navigation events

### ISSUE THREAD

**Issue by LHaanappel** [flutter/flutter#148409]
Copy of issue  #76497 by @hkwinslow which was closed.

### Steps to reproduce

1. Connect iPhone to an external keyboard via bluetooth
2. Run/open an iOS flutter app (on a physical device)
3. Try to navigate the app using only an external keyboard

### Expected results

- Able to access & interact with all input elements (text fields, buttons, checkboxes, etc.) by making use of keys such as tab, up, down, space, enter, etc.

### Actual results

- I tried using the 1Keyboard app to use my Mac keyboard through bluetooth, and I also bought a bluetooth keyboard to try. Both yielded same result.
- There is one workaround I have found but it only applies to text fields. That is to set autofocus to true and then adding this code to the text field: `textInputAction: TextInputAction.next, onEditingComplete: () => FocusScope.of(context).nextFocus()`,  But, I would expect it to work out of the box and for any type of input element. Also this requires autofocus to be set to true which is not ideal in many cases.
- I have tried using a small sample app I've built, as well as the Flutter Catalog app which I read should have this support.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

![image](https://github.com/flutter/flutter/assets/71488688/8cb8b906-942e-40ee-95d9-e573c735838f)

</details>

**Comment by danagbemava-nc** [comment]
Hi @LHaanappel, thanks for filing this, https://github.com/flutter/flutter/issues/76497 has been re-opened. Please feel free to share any additional information you can in there. 

Closing this in favor of the original issue. 

Thank you
