### ISSUE TITLE
Xcode: need to select device to create provisioning profile

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#14841]
Feedback from developer:

https://flutter.io/setup-macos/#ios-setup dosen't tell you that you need to select your device in the upper right corner of xcode to create a provisioning profile for it.

/cc @cbracken @xster

**Comment by xster** [comment]
As of ~a week ago, it shouldn't be needed anymore on master. The command line flutter tool should be able to create provisioning profiles for you (you still need to sign in in xcode etc).

**Comment by xster** [comment]
caveat, we're very unlikely to have a nicer solution using Google certs (can give more details offline)

**Comment by Sfshaza** [comment]
It *seems* like this bug can be closed, as per @Xster's comments. Please re-open and clarify if I've read that wrong.
