### ISSUE TITLE
Add migration guide and callback-hooks for onDestroy/onResume w/ SurfaceProducer

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [flutter/flutter#148417]
### Use case

i am migrating https://github.com/media-kit/media-kit/pull/824 from SurfaceTextureEntry to SurfaceProducer,

but i was unable to find setOnFrameAvailableListener method anywhere, will it be added in a future release or there is a workaround?

### Proposal

adding setOnFrameAvailableListener to SurfaceProducer

**Comment by darshankawar** [comment]
@abdelaziz-mahdy 
Can you check if your use case resembles https://github.com/flutter/flutter/issues/139702 ?

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy Can you check if your use case resembles #139702 ?


Since the package is a video player, if a change is needed in the `video_player` package, it will likely be needed in our package as well.

Regarding the issue that mentioned, the following part has been checked as done:
```
1. Add a new API, (create|register)Surface, which delegates (internally) to SurfaceTexture or ImageReader
```
So, the interface should be complete. However, when I checked [this documentation](https://docs.flutter.dev/release/breaking-changes/android-surface-plugins), it mentioned that the interface should have the same methods but is missing the `setOnFrameAvailableListener` function. This has blocked my migration to the new `SurfaceProducer`.

**Comment by matanlurey** [comment]
@abdelaziz-mahdy This callback no longer exists, as surface producers won't produce a `surfaceTexture()` on modern Android devices running Impeller. As an example, our own `video_player` plugin never used this callback, and doesn't need it to migrate: https://github.com/flutter/packages/pull/6456/files.

If you do need something, `Surface` doesn't directly offer a frame-available listener, you could look into using [`Choreographer`](https://developer.android.com/reference/android/view/Choreographer) to schedule draws synchronized with the display refresh rate:
```java
Choreographer choreographer = Choreographer.getInstance();
Object lock = new Object(); // Shared lock for synchronization

choreographer.postFrameCallback(new Choreographer.FrameCallback() {
    @Override
    public void doFrame(long frameTimeNanos) {
        synchronized (lock) {
            try {
                // ...
            } finally {
                choreographer.postFrameCallback(this); 
            }
        }
    }
});
```

... or something like [`SurfaceHolder`](https://developer.android.com/reference/android/view/SurfaceHolder):
```java
surfaceHolder.addCallback(new SurfaceHolder.Callback() {
    @Override
    public void surfaceCreated(SurfaceHolder holder) { }

    @Override
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
        synchronized (lock) {
            // ...
        }
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) { }
});
```

To be clear, these are all Android-specific APIs and I'd recommend you follow Android best practices - we just simply can't provide an API that doesn't exist (i.e. on `Surface`), and `SurfaceTexture` is a legacy element in Android that doesn't work in Vulkan/Impeller.

/cc @johnmccutchan @jonahwilliams - I'd be open to adding something like this to the article.

**Comment by abdelaziz-mahdy** [comment]
@matanlurey thank you for the explanation, I will try your suggested workarounds, hopefully it works correctly in our case.

**Comment by abdelaziz-mahdy** [comment]
i tested migrating our code to use `choreographer` without surface producer and it worked correctly 

but when i migrated to `SurfaceProducer` sometimes it does and sometimes it doesnt 

branch migrated to `choreographer`
https://github.com/abdelaziz-mahdy/media_kit/tree/test

branch migrated to `choreographer` and `SurfaceProducer`
https://github.com/abdelaziz-mahdy/media_kit/tree/test-with-impller

to avoid duplication this is the problems i am having https://github.com/media-kit/media-kit/pull/824#issuecomment-2119203789

summary of the problems it doesnt happen in all cases so i dont think its a problem with mpv it self: 
* video render as a flicker of colors
* video scale is wrong
* i get `java.lang.IllegalStateException: Surface has already been released.` but `branch migrated to choreographer alone` it never happens

**Comment by jonahwilliams** [comment]
I took a quick look at the patch, I suspect there are more updates  required to the createSurface method. Essentially for the surface producer API you want to let the producer manage the lifecycle and not otherwise cache the Surface entry. At a minimum, you're probably double releasing the Surface, which is the cause of the "Surface has already been released." errors.

You will also need to make sure that you don't retain the Surface through onPause/onResume as the system may destroy the backing image readers.

**Comment by abdelaziz-mahdy** [comment]
> I took a quick look at the patch, I suspect there are more updates required to the createSurface method. Essentially for the surface producer API you want to let the producer manage the lifecycle and not otherwise cache the Surface entry. At a minimum, you're probably double releasing the Surface, which is the cause of the "Surface has already been released." errors.
> 
> You will also need to make sure that you don't retain the Surface through onPause/onResume as the system may destroy the backing image readers.

any package that i can take a reference specially for the onPause/onResume part ? 
i was able to fix `Surface has already been released.` in this branch https://github.com/abdelaziz-mahdy/media_kit/tree/new-test-for-impller
but the problems of 

* the first video render as a flicker of colors
* black screen instead of rendering (cant figure out if its a problem with my side or from the SurfaceProducer so i will try the video player branch)

* video scale is wrong(this is gone, or much less) so lets ignore it for now

**Comment by jonahwilliams** [comment]
The reason for needing the onPause/onResume hook is to work around an Android 14 bug, but we're considering backing that change out. Will update once we know what we're doing.

If you're interested in lifecycle hooks, the video_player update added some

**Comment by matanlurey** [comment]
First PR is out: https://github.com/flutter/engine/pull/53280.

Assuming it gets approved, lands, and is not reverted, it will take a few days to be available in the `master` branch. We'll start using it in the `packages/video_player/video_player_android` and provide an updated migration guide as part of this work.
