### ISSUE TITLE
New flutter `doctor` parameters

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#148473]
### Use case

Often when changing channels or upgrading flutter I run into difficulties because flutter has locked files, which causes the channel change to fail or upgrade to stop. Using `flutter upgrade --force` parameter does not help either in theese circumstances.

Of all things, I had an conversation with Google Gemini (!) about the issue, and she (i prefer to believe it is a she) suggested theese two flutter doctor commands as described in next section

### Proposal

This was the suggestion from Google Gemini:
"
Sure, here are the suggestions that I would make to the Flutter team:

New `flutter doctor` parameters:

- `flutter doctor --show-file-locks`: This parameter would display a list of any files that are currently locked by Flutter processes. This would be helpful for diagnosing and resolving issues with locked files.

- `flutter doctor --unlock-files`: This parameter would attempt to unlock any files that are currently locked by Flutter processes. This would be a convenient way to resolve issues with locked files without having to restart your computer or manually kill Flutter processes.

Additional suggestions:

- Improve the error message that is displayed when a channel change or upgrade fails due to locked files. The current error message is not very helpful and does not provide any guidance on how to resolve the issue.

- Add documentation to the Flutter website about how to deal with locked files when upgrading or changing channels.

I believe that these suggestions would improve the Flutter development experience and make it easier for developers to diagnose and resolve issues with locked files.

I will pass these suggestions along to the Flutter team and encourage you to do the same. The more feedback that the Flutter team receives from developers, the better the SDK can become.
"

![image](https://github.com/flutter/flutter/assets/11217296/f8cc4211-0cac-4329-b357-a058dacf46a6)

So if it didn't arrive to you (I am not sure she can take contact by email, teams or whatever) I am posting her answer here anyway !

**Comment by stuartmorgan** [comment]
> because flutter has locked files

Can you be specific about what you mean by this? What files are locked, and how did you determine that Flutter itself locked them?

**Comment by RoarGronmo** [comment]
Well, I think I have mentioned the source error before (https://github.com/flutter/flutter/issues/147357) (whenever I have changed channels or done any upgrades) when using console (and has my Flutter project open in Android Studio IDE at the same time) I get this recursive error message: 

```
PS C:\FlutterProjects\mPortal> flutter channel
Flutter channels:
  master (latest development branch, for contributors)
  main (latest development branch, follows master channel)
* beta (updated monthly, recommended for experienced users)
  stable (updated quarterly, for new users and for production app releases)
PS C:\FlutterProjects\mPortal> flutter upgrade
Flutter is already up to date on channel beta
Flutter 3.22.0-0.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 87b652410d (3 weeks ago) • 2024-04-23 21:41:18 -0500
Engine • revision b4bfd45986
Tools • Dart 3.4.0 (build 3.4.0-282.3.beta) • DevTools 2.34.3
PS C:\FlutterProjects\mPortal> flutter channel stable
Switching to flutter channel 'stable'...

Upgrading engine...
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine e76c956498841e1ab458577d3892003e553e4f3c...
Rename-Item: C:\Flutter\flutter\bin\internal\update_dart_sdk.ps1:59
Line |
  59 |          Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The process cannot access the file because it is being used by another
     | process.
Error: Unable to update Dart SDK. Retrying... 
ERROR: Input redirection is not supported, exiting the process immediately.
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine e76c956498841e1ab458577d3892003e553e4f3c...
Rename-Item: C:\Flutter\flutter\bin\internal\update_dart_sdk.ps1:59
Line |
  59 |          Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The process cannot access the file because it is being used by another
     | process.
Error: Unable to update Dart SDK. Retrying... 
ERROR: Input redirection is not supported, exiting the process immediately.
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine e76c956498841e1ab458577d3892003e553e4f3c...
Rename-Item: C:\Flutter\flutter\bin\internal\update_dart_sdk.ps1:59
Line |
  59 |          Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The process cannot access the file because it is being used by another
     | process.
Error: Unable to update Dart SDK. Retrying... 
ERROR: Input redirection is not supported, exiting the process immediately.
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine e76c956498841e1ab458577d3892003e553e4f3c...
Rename-Item: C:\Flutter\flutter\bin\internal\update_dart_sdk.ps1:59
Line |
  59 |          Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The process cannot access the file because it is being used by another
     | process.
Rename-Item: C:\Flutter\flutter\bin\internal\update_dart_sdk.ps1:59
Line |
  59 |          Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The process cannot access the file because it is being used by another
     | process.
Error: Unable to update Dart SDK. Retrying...
ERROR: Input redirection is not supported, exiting the process immediately.
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine e76c956498841e1ab458577d3892003e553e4f3c...
Terminate batch job (Y/N)? y
PS C:\FlutterProjects\mPortal>
```
I like to believe that it is either Flutter (any processes) or the Flutter Plugin in AS which holds (locks) files in this directory so it/they cannot be renamed (or moved) as it wants. 

Earlier today I ran into this problem again (needed to change channels) and got so stuck, that I even turned to AI (Gemini) and described the problem for her, and she just suggested to reinstall flutter, since I couldn't let out of the problem even after a restart of my system. Then in a "conversation" with here she suggested theese two methods shown above (frankly I was stunned of her creativity...), just to determine if the files are locked by Flutter (or maybe even the Flutte Plugin) somehow and also a tool to just "unlock" them, so you can do an upgrade smoothly without any problems.

Later today I have successfully managed to do a channel shift without the locking problem, - BUT you need to restart your system and NOT start any Android Studio, just a powershell, manage to the directory where flutte is installed and do the `flutter channel <new-channel>` and thereafter do the `flutter upgrade` command there. Done so, manage to where your project is sited and do necessary `flutter pub` commands and `dart` commands to resync. 

Anyway - credit to Gemini for the suggestion - and maybe it will be handy. This problem above has been here for at least a year...

**Comment by stuartmorgan** [comment]
> I like to believe that it is either Flutter (any processes) or the Flutter Plugin in AS which holds (locks) files in this directory so it/they cannot be renamed (or moved) as it wants.

Windows does not allow moving or deleting files that are currently open in another process. That's not a Flutter behavior, it's a Windows behavior.

> and also a tool to just "unlock" them

How would that work? Is the suggestion here that `flutter upgrade` force-kill every process on the system that has any files in the Flutter SDK directory open? That would be incredibly disruptive, and has a very high potential of leading to data loss.

> Anyway - credit to Gemini for the suggestion - and maybe it will be handy. This problem above has been here for at least a year...

It is very easy for an LLM to generate a line of text suggesting a theoretical tool; that's not going to change the fact that the Flutter team cannot fundamentally alter the way Windows works.

**Comment by RoarGronmo** [comment]
No, I am not asking for killing each process windows has in its lock, but rather tell wich crucial files flutter processes and flutter plugins have in lock, and maybe a simple tool to release them. If not, there should be check on the files which are to be moved or changed, and bail out before any destructive peocesses are begun.

Maybe the simpler solution would be to just tell the user to please quit Android Studio, start powershell and do the channel change or upgrade there, and even more profound, restart your system an do the upgrade/channel change in powershell before AS is started, if the flutter plugin is to blaim for the file lock.

**Comment by stuartmorgan** [comment]
> and maybe a simple tool to release them

If not by killing processes, how would such a tool work?

**Comment by RoarGronmo** [comment]
> > and maybe a simple tool to release them
> 
> If not by killing processes, how would such a tool work?

Just list the processes that Flutter or Flutter plugin owns, and a tool to unlock those. How, I dont know.

**Comment by christopherfujino** [comment]
Thank you for filing this, but this does not sound actionable, so I am closing this.
