### ISSUE TITLE
Unable to gclient sync flutter/engine

### ISSUE THREAD

**Issue by xqwzts** [flutter/flutter#14857]
Following the instructions to pull the engine from the [contributing docs](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#getting-the-code-and-configuring-your-environment) and calling `gclient sync`

Results in:

>  ~/d/engine  gclient sync                                                                         22.1s
[P21879 01:25:10.523 remote.go:125 W] cipd: connectivity error (Get https://chrome-infra-packages.appspot.com/_ah/api/repo/v1/instance/resolve?package_name=infra%2Ftools%2Fcipd%2Flinux-amd64&version=git_revision%3Ae1abc57be62d198b5c2f487bfb2fa2d2eb0e867c: dial tcp: lookup chrome-infra-packages.appspot.com on 127.0.1.1:53: read udp 127.0.0.1:56170->127.0.1.1:53: read: connection refused)
[P21879 01:25:10.523 remote.go:125 W] cipd: retrying request to https://chrome-infra-packages.appspot.com/_ah/api/repo/v1/instance/resolve?package_name=infra%2Ftools%2Fcipd%2Flinux-amd64&version=git_revision%3Ae1abc57be62d198b5c2f487bfb2fa2d2eb0e867c
[P21879 01:25:12.524 remote.go:125 W] cipd: connectivity error (Get https://chrome-infra-packages.appspot.com/_ah/api/repo/v1/instance/resolve?package_name=infra%2Ftools%2Fcipd%2Flinux-amd64&version=git_revision%3Ae1abc57be62d198b5c2f487bfb2fa2d2eb0e867c: dial tcp: lookup chrome-infra-packages.appspot.com on 127.0.1.1:53: read udp 127.0.0.1:33567->127.0.1.1:53: read: connection refused)
[P21879 01:25:12.524 remote.go:125 W] cipd: retrying request to https://chrome-infra-packages.appspot.com/_ah/api/repo/v1/instance/resolve?package_name=infra%2Ftools%2Fcipd%2Flinux-amd64&version=git_revision%3Ae1abc57be62d198b5c2f487bfb2fa2d2eb0e867c
[P21879 01:25:14.525 remote.go:125 W] cipd: connectivity error (Get https://chrome-infra-packages.appspot.com/_ah/api/repo/v1/instance/resolve?package_name=infra%2Ftools%2Fcipd%2Flinux-amd64&version=git_revision%3Ae1abc57be62d198b5c2f487bfb2fa2d2eb0e867c: dial tcp: lookup chrome-infra-packages.appspot.com on 127.0.1.1:53: read udp 127.0.0.1:35862->127.0.1.1:53: read: connection refused)
[P21879 01:25:14.525 remote.go:125 W] cipd: retrying request to https://chrome-infra-packages.appspot.com/_ah/api/repo/v1/instance/resolve?package_name=infra%2Ftools%2Fcipd%2Flinux-amd64&version=git_revision%3Ae1abc57be62d198b5c2f487bfb2fa2d2eb0e867c
[P21879 01:25:16.526 remote.go:125 W] cipd: connectivity error (Get https://chrome-infra-packages.appspot.com/_ah/api/repo/v1/instance/resolve?package_name=infra%2Ftools%2Fcipd%2Flinux-amd64&version=git_revision%3Ae1abc57be62d198b5c2f487bfb2fa2d2eb0e867c: dial tcp: lookup chrome-infra-packages.appspot.com on 127.0.1.1:53: read udp 127.0.0.1:49316->127.0.1.1:53: read: connection refused)

[This goes on and on, just pasting a snippet]

The links in question seems to open fine in a browser, so I feel like this has something to do with the ports?

**Comment by xqwzts** [comment]
FWIW this was caused by a misconfigured dnsmasq :|

**Comment by mgielda** [comment]
Hi @xqwzts, we're having the same problem - could you by any chance mention how you solved this? Thanks!

**Comment by xqwzts** [comment]
Hi @mgielda - I'm on Ubuntu 17.10 and was running into this issue: https://askubuntu.com/a/967341

Solved by 
- setting a static DNS in `/etc/systemd/resolved.conf`
- changing the symlink as suggested in that answer:
```
$ sudo rm /etc/resolv.conf
$ sudo ln -s /run/resolvconf/resolv.conf /etc/resolv.conf
$ systemctl restart resolvconf
```

Hope that helps!

**Comment by mgielda** [comment]
Thanks! I think that was it.
