### ISSUE TITLE
`flutter update-packages` can fail silently

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#148569]
There are probably other instances where this happens, but this is how I am able to consistently reproduce it:

1) Clone flutter from a fork (it's important that it's cloned from a fork because those are missing tags): `git clone git@github.com:goderbauer/flutter.git`
2) Run `./bin/flutter update-packages` inside the cloned repository:
```
$./bin/flutter update-packages
Downloading Darwin arm64 Dart SDK from Flutter engine bf1c6da0dd31273405ae4107ba7225238686140b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  201M  100  201M    0     0  16.3M      0  0:00:12  0:00:12 --:--:-- 26.2M
Building flutter tool...
Resolving dependencies... 
Downloading packages... 
Got dependencies.
Downloading Material fonts...                                      804ms
Downloading Gradle Wrapper...                                      117ms
Downloading package sky_engine...                                  245ms
Downloading flutter_patched_sdk tools...                           321ms
Downloading flutter_patched_sdk_product tools...                   360ms
Downloading darwin-arm64 tools...                                1,253ms
Downloading libimobiledevice...                                    125ms
Downloading usbmuxd...                                             107ms
Downloading libplist...                                            111ms
Downloading openssl...                                             182ms
Downloading ios-deploy...                                          144ms
Downloading darwin-arm64/font-subset tools...                      341ms
```
3) There's no indication in the output that something has failed, one has to inspect the error code to learn that the command in fact failed silently.

**Expectation:** It prints a clear error describing the failure so it is impossible to miss that something has gone wrong.

Currently, to learn about the real failure, one has to run the command with `-v`:

```
                    ERR : The current Flutter SDK version is 0.0.0-unknown.
                        | 
                        | Because flutter_update_packages depends on webview_flutter_wkwebview >=2.0.14 which requires Flutter SDK version >=2.5.0, version solving failed.
```

Speculatively, the problem of failing silently could be related to this TODO:

https://github.com/flutter/flutter/blob/3695802295777e67af8c5f29c97b68877df29492/packages/flutter_tools/lib/src/commands/update_packages.dart#L527

cc @christopherfujino

**Comment by andrewkolos** [comment]
Unassigned myself as I will be working on higher priority items for the next _N_ weeks. The fix is to not call `throwToolExit` with a `null` message, as we do here:

https://github.com/flutter/flutter/blob/66367dd888458d94a3bd1ffd712c4cb473dc5f69/packages/flutter_tools/lib/src/dart/pub.dart#L447

But, it's non obvious what the message should be.

**Comment by christopherfujino** [comment]
> Unassigned myself as I will be working on higher priority items for the next _N_ weeks. The fix is to not call `throwToolExit` with a `null` message, as we do here:
> 
> https://github.com/flutter/flutter/blob/66367dd888458d94a3bd1ffd712c4cb473dc5f69/packages/flutter_tools/lib/src/dart/pub.dart#L447
> 
> But, it's non obvious what the message should be.

I think we should capture the stdout/stderr from pub, and then surface it here.

**Comment by christopherfujino** [comment]
> > Unassigned myself as I will be working on higher priority items for the next _N_ weeks. The fix is to not call `throwToolExit` with a `null` message, as we do here:
> > https://github.com/flutter/flutter/blob/66367dd888458d94a3bd1ffd712c4cb473dc5f69/packages/flutter_tools/lib/src/dart/pub.dart#L447
> > 
> > But, it's non obvious what the message should be.
> 
> I think we should capture the stdout/stderr from pub, and then surface it here.

Ahh, ok, I missed that this is in the pub library...

**Comment by matanlurey** [comment]
I've also run into this :(

**Comment by matanlurey** [comment]
If anyone is interested in reproducing this bug without forking the repository, apply this diff:

```diff
diff --git a/packages/flutter_tools/lib/src/version.dart b/packages/flutter_tools/lib/src/version.dart
index cbef04a989..926bd62552 100644
--- a/packages/flutter_tools/lib/src/version.dart
+++ b/packages/flutter_tools/lib/src/version.dart
@@ -138,13 +138,7 @@ abstract class FlutterVersion {
     required FileSystem fs,
     bool fetchTags = false,
   }) {
-    final GitTagVersion gitTagVersion = GitTagVersion.determine(
-      globals.processUtils,
-      globals.platform,
-      gitRef: frameworkRevision,
-      workingDirectory: flutterRoot,
-      fetchTags: fetchTags,
-    );
+    final GitTagVersion gitTagVersion = GitTagVersion.unknown();
     final String frameworkVersion = gitTagVersion.frameworkVersionFor(frameworkRevision);
     return _FlutterVersionGit._(
       clock: clock,
```

Then remember to `rm bin/cache/flutter_tools.snapshot`.
