### ISSUE TITLE
Remove use of modulemaps in flutter/packages when using SwiftPM

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#148572]
### Use case

To support both CocoaPods and Swift Package Manager, dynamic and static linking, two different modulemaps are needed.

### CocoaPods modulemap
CocoaPods seems to require the modulemap be a `framework` module and doesn't use relative paths.

For example, 
```ruby
framework module plugin_name_ios {
  umbrella header "plugin_name_ios-umbrella.h"

  export *
  module * { export * }

  explicit module Test {
    header "PublicHeader_Test.h"
    header "OtherPublicHeader_Test.h"
  }
}

```

### SwiftPM modulemap
SwiftPM requires the modulemap to be [named `module.modulemap` and be located within the `include` directory](https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets). It also doesn't seem to work if defined as a `framework` module and uses relative paths.

For example,
```diff
- framework module plugin_name_ios {
+ module plugin_name_ios {

explicit module Test {
-    header "PublicHeader_Test.h"
+    header "plugin_name_ios/OtherPublicHeader_Test.h"
```

### The problem
The problem is that when you have two modulemaps (most likely also because one is named `module.modulemap`, which is the [implicit modulemap file](https://clang.llvm.org/docs/Modules.html#command-line-parameters)), this can cause issues:
* https://github.com/flutter/flutter/issues/148307
* https://gist.github.com/loic-sharma/27bd8e3ea0d9ab16cd4b8de03918ec4d

### Proposal

It's been pretty difficult to figure out a way to support both CocoaPods and SwiftPM modulemaps. As a result, we're leaning towards eliminating modulemaps in SwiftPM.

---

Instead of using a modulemap and umbrella header for the SwiftPM integration of plugins, we simply allow all public headers to be available via `@import plugin_name_ios`.

```diff
@import plugin_name_ios;
- @import plugin_name_ios.Test;
```

The headers are already public and could be imported individually (like `#import <plugin_name_ios/PublicHeader_Test.h>`), so making them available through the module isn't much worse.

Modulemap and umbrella header should be excluded from SwiftPM target:
```diff
        .target(
            name: "plugin_name_ios",
            dependencies: [],
+           exclude: ["cocoapods_plugin_name_ios.modulemap", "plugin_name_ios-umbrella.h"],
```

Unit tests can also be kept compatible with both CocoaPods and SwiftPM with something like:
```objc
#if __has_include(<plugin_name_ios/plugin_name_ios-umbrella.h>)
  @import plugin_name_ios.Test;
#endif
```

#### Prototype
 https://github.com/flutter/packages/compare/main...vashworth:packages:camera_avfoundation_remove_swiftpm_modulemap

#### Re-adding SwiftPM `.modulemap`s

Once the ecosystem has migrated to SwiftPM, we will remove support for CocoaPods. At this point, we should consider re-adding `module.modulemap`s to the plugins' SwiftPM integration. This step might not be necessary as we plan to rewrite plugins in Swift.

**Comment by vashworth** [comment]
fyi @jmagman @stuartmorgan 

@loic-sharma and I like this approach and are planning to move forward with it. If users want to use modulemaps with SwiftPM, we plan to point them to SwiftPM's documentation about it: https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets

**Comment by loic-sharma** [comment]
> If users want to use modulemaps with SwiftPM, we plan to point them to SwiftPM's documentation about it: https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets

I created an experiment that allows for custom module maps with SwiftPM: https://github.com/flutter/packages/compare/main...loic-sharma:flutter-packages:spm_camera_separate_public_file_symlinks

This works by creating separate header directories for CocoaPods (`/cocoapods_headers`) and Swift Package Manager (`/include`). To minimize duplication, the CocoaPods header files are symlinks back to the header files in the Swift Package Manager header directory. Some drawbacks to this approach:

1. Pigeon generates implementation files that use relative `#import` paths. This isn't compatible with this approach as the relative path to the header files changes depending on whether you're using CocoaPods or Swift Package Manager. Today, you need to edit the code generated by Pigeon to use non-relative imports like `#import <my_plugin/MyHeader.h>`.
2. You need to remember to update symlinks if you add/move/delete header files. If we were to use this approach in the `flutter/packages` repo, we'd likely want tooling/tests to verify CocoaPods/SwiftPM header files are in sync.

**Comment by jmagman** [comment]
In the tests:
```swift
@import camera_avfoundation;
@import camera_avfoundation_test;
```
If we were only in SwiftPM world, could we normally `#import` the test headers directly?  Or was there some problem with the hmap?

**Comment by vashworth** [comment]
> In the tests:
> 
> ```swift
> @import camera_avfoundation;
> @import camera_avfoundation_test;
> ```
> 
> If we were only in SwiftPM world, could we normally `#import` the test headers directly? Or was there some problem with the hmap?

We could do imports directly.

That actually makes me realize, we can simplify this even further. Since all the headers are public and we're not using a custom umbrella header and modulemap, we don't need to do a separate target or import separate headers. All the headers should be available via the `@import camera_avfoundation;` since it's no longer limited by the umbrella header
