### ISSUE TITLE
new gallery benchmark throwing late initialization and potentially other errors

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#148548]
Search for LateInitializationError in:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8747679430480882145/+/u/run_new_gallery__transition_perf/stdout

and

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8747679038401611905/+/u/run_new_gallery_ios__transition_perf/stdout

Tagging @jonahwilliams first to ask if this is something to worry about, or something benign that wouldn't affect performance/correctness.

**Comment by jonahwilliams** [comment]
not good!

**Comment by zanderso** [comment]
It looks like this was probably introduced by https://github.com/flutter/flutter/pull/147793.

**Comment by nate-thegrate** [comment]
Thanks for catching this!

**Comment by zanderso** [comment]
This no longer happens after the revert. Closing.
