### ISSUE TITLE
Grey screen Errors in Release Mode

### ISSUE THREAD

**Issue by fluttyCat** [flutter/flutter#148541]
### Steps to reproduce

When I build the app with my laptop, something strange happens
When I switch between the app pages, the error "Controller not found" appears randomly
and the error says it is OBX widget that causing this.either loses the controller or does not register it at all when navigating between pages. but in other laptops everything is fine and the APK works correctly.

### Expected results

I want to know how to fix this difference between different builds on different laptops

### Actual results

The APK should work fine no Mather which laptop or system made it

### Code sample

return AppScaffold(child:Obx(() => Container(
...

...
));

### Flutter Doctor output

[!] Flutter (Channel [user-branch], 3.13.7, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    ! Flutter version 3.13.7 on channel [user-branch] at /Users/-----/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 2f708eb839 (7 months ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/-----/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.209
    ! Error: Browsing on the local area network for -----. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for -----. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for -----. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

**Comment by danagbemava-nc** [comment]
You are using getx/get which is a third party package. If you are getting `controller not found` issues, this is likely an issue with the package. You should report this on their repo so it can be properly investigated. 

Closing from here. 

Thank you

**Comment by fluttyCat** [comment]
Thank you so much
