### ISSUE TITLE
Proposal for command line that shows packages that create dependency constraints incompatible with newer package

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#148671]
### Use case

When updating packages the suggested command doesn't make sense and results in a bad developer experience.
```
flutter pub upgrade --major-versions
Resolving dependencies... (2.6s)
Downloading packages...
  leak_tracker 10.0.4 (10.0.5 available)
  leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.12.0 (1.15.0 available)
  test_api 0.7.0 (0.7.1 available)
  vm_service 14.2.1 (14.2.2 available)
No dependencies changed.
6 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

No changes to pubspec.yaml!
❯ flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.
all dependencies are up-to-date.
```

### Proposal

The suggested command should highlight packages that create outdated dependency constraints:
```
6 packages have newer versions incompatible with dependency constraints.
```
What package is responsible for that?

**Comment by darshankawar** [comment]
@stephane-archer 
Can you check if your case resembles [this](https://github.com/flutter/flutter/issues/91416) or not ?

**Comment by stephane-archer** [comment]
@darshankawar This is not about showing discontinued packages, it's about recommending a command line that shows packages that create dependency constraints incompatible with newer package

**Comment by gnprice** [comment]
Here's the issue for this feature request in the `pub` tracker:
* https://github.com/dart-lang/pub/issues/3545

I agree it would be a useful feature. There's also a tip at https://github.com/dart-lang/pub/issues/3545#issuecomment-1233985491 about how you can get that information today (add a newer version in `pubspec.yaml` and rerun `flutter pub get`).

---

Meanwhile the reason `flutter pub outdated` doesn't say much is that the affected dependencies are indirect dependencies (which after all is why they weren't upgraded). You can find more with `flutter pub outdated --transitive`.

Coincidentally there's an issue just yesterday about that:
* https://github.com/dart-lang/pub/issues/4273

Even with `--transitive` the information printed doesn't answer your original question, though.

---

In this specific example, I think the answer to "what package is responsible for that" is Flutter itself — those all look like packages that the Flutter SDK pins versions of. So the way to upgrade them is to upgrade to the latest Flutter from main.

**Comment by andrewkolos** [comment]
Hello and thanks for contributing this issue. I was going to say that this should instead be tracked in the pub repo, but it looks like that's already the case (thanks for the fantastic research @gnprice). Because of this, I'll be closing this issue now. Please reopen if I misunderstood.
