### ISSUE TITLE
After converting “かっこ” to parentheses （） in the predictive conversion, pressing the Move button in the sentence returns the status before the predictive conversion.

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#148674]
### Steps to reproduce

1. input かっこ in japanese
2. Select （） from the predictive conversion
3. Press the button to move the cursor forward.

### Expected results

the text should be （） and the cursor should be inside the （）

### Actual results

the text is かっこ

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class SamplePage extends StatefulWidget {

  SamplePage(): super();

  @override
  SamplePageState createState() => SamplePageState();
}

class SamplePageState extends State<SamplePage> with WidgetsBindingObserver {
  final TextEditingController _controller = TextEditingController();
  final FocusNode _focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextFormField(
          controller: _controller,
          focusNode: _focusNode,
          onChanged: (String value) {
            setState(() { });
          },
        ),
      )
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/7422251/cc5a8f8e-3b0b-4334-b3d6-171983f22923

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3593], locale ja-JP)
    • Flutter version 3.19.6 on channel stable at C:\Users\81708\Desktop\develop\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (5 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\81708\AppData\Local\Android\sdk
    • Platform android-34, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\81708\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3593]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 125.0.6422.60
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 125.0.2535.51

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by hatano0x06** [comment]
This is not a problem I found, but a problem my app users found
I could not find the same problem on my test device, but it may be a problem with a specific device.

Here is the user's device information
deviceName:SC-53B
osVersion:34

**Comment by hatano0x06** [comment]
Also, as a funny behavior in this video, if you convert the “かっこ” to () in the first place, the cursor should be in the middle of the ()
I'm wondering if this is a similar problem, so I'll report it as well.

**Comment by huycozy** [comment]
Hi @hatano0x06 
I checked this on my device Pixel 7 Android 14 but couldn't see the issue on both Flutter 3.19.6 and 3.22.0. `かっこ` turns to `()` and the cursor is in the middle of `()` as desired.

<details>
<summary>Demo issue is not reproducible</summary>

https://github.com/flutter/flutter/assets/104349824/e875744e-dc97-47d5-bad6-bd9cbbf52c8a

</details>

Maybe this is a device-specific issue and it looks like a Samsung device ([Galaxy A52 5G SC-53B](https://www.docomo.ne.jp/support/product/sc53b/spec.html)). I found an issue at https://github.com/flutter/flutter/issues/120351 that is somewhat similar to this. Even though it's not exactly the same, I see it occurs on the same text `かっこ` and it doesn't turn to an expected text when adding a line break; and it happens on Samsung device too.

It could be the same cause, so I'm going to centralize this to that one. Please follow up on it and also leave your case there that may help to raise the issue. Thanks!
