### ISSUE TITLE
flutter shell script should handle the inability to write to the file system when getting Dart

### ISSUE THREAD

**Issue by chandramouli16** [flutter/flutter#14862]
mkdir error permission denied while running flutter doctor cmd

**Comment by cbracken** [comment]
@chandramouli16 thanks for reporting! Would you mind including the full output of `flutter doctor --verbose`?

**Comment by jeppeskovbakke** [comment]
I get what I think must be the same error:
mkdir: /.../.../flutter/bin/cache: Permission denied
works when running as root, but there's a warning strongly recommending not doing so.

**Comment by Hixie** [comment]
Looks like this must be happening in the shell script itself. Maybe the file system is read-only.

**Comment by cbracken** [comment]
If you run `ls -al bin/cache` on your flutter/bin/cache directory, it should have `rwx` permissions for the user. Specifically you should see something like:
```
drwxr-xr-x  14 myusername  mygroup      448 23 May 19:13 ./
```

If you see something more like `dr-xr-xr-x`, try `chmod u+w bin/cache` and see if that helps.

**Comment by eseidelGoogle** [comment]
This would need to be resolved for things like https://github.com/flutter/flutter/issues/14050.

**Comment by eseidelGoogle** [comment]
I suspect this bug won't ever be solved.  However, Flutter should probably support configuring its cache location.  It needs a writable cache.  But it doesn't necessary need one in the same location which it currently uses (as such a location would be incompatible with things like homebrew were we to ever do such).

My temptation is to close this in favor of fixing larger bugs like https://github.com/flutter/flutter/issues/14050.  Let me know if you disagree.

Thanks for reaching out!
