### ISSUE TITLE
The `target` field in `FlutterOpenGLFramebuffer` is misleading

### ISSUE THREAD

**Issue by hasali19** [flutter/flutter#148637]
The [`target`](https://github.com/flutter/engine/blob/426dbb125861a757ff50c640d107df9f0524e0d6/shell/platform/embedder/embedder.h#L388-L391) field of `FlutterOpenGLFramebuffer` in the embedder API is poorly named and incorrectly documented. Looking at the code [here](https://github.com/flutter/engine/blob/426dbb125861a757ff50c640d107df9f0524e0d6/shell/platform/embedder/embedder.cc#L792), it is actually used to represent a format rather than target.

**Comment by jonahwilliams** [comment]
oops
