### ISSUE TITLE
How to ship a Flutter MacOS App Notarize using the command line?

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#148669]
### Steps to reproduce

How to ship a Flutter MacOS App Notarize using the command line?
Here is what I currently do:
```
flutter clean; flutter build macos;
```
I have now a Flutter MacOS App in `build/macos/Build/Products/Release/`
but it's not notarized.

To do that, I open the Xcode project `macos/Runner.xcworkspace`, create an archive, and then select Distribute App > Direct distribution.

I wait for Xcode to get the green light from Apple Notarize servers then export the app so I can distribute it.

as you can see it's a manual process and I would like to be able to do the same thing using a script.

How to achieve this?

### Expected results

up

### Actual results

up

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by kjxbyz** [comment]
I've implemented it, you're welcome,

The build target is in `dmg` format and the certificate type is `Developer ID Application`
https://github.com/picguard/picguard/actions/workflows/test-macos-dmg.yml

The build target is in `pkg` format and the certificate types is `Developer ID Application` and `Developer ID Installer`
https://github.com/picguard/picguard/actions/workflows/test-macos-pkg.yml

The build target is in `pkg` format, distributed to mac app store, and the certificate types are `Mac App Distribution` and `Mac Installer Distribution`
https://github.com/picguard/picguard/actions/workflows/test-macos-pkg-appstore.yml

The build target is in `zip` format and the certificate type is `Developer ID Application`
https://github.com/picguard/picguard/actions/workflows/test-macos-zip.yml

**Comment by darshankawar** [comment]
@stephane-archer 
Please check above and see if it helps to answer your case.
Also check https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

**Comment by stephane-archer** [comment]
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow?language=objc

**Comment by darshankawar** [comment]
Does that link answer / resolve your issue ?

**Comment by stuartmorgan** [comment]
Closing, as this is out of scope for Flutter. Nothing about the process of notarizing an application is Flutter-specific; anyone is welcome to write, or find and use, any automation tools intended for post-build steps.
