### ISSUE TITLE
[Android]: Clipboard and keyboard closes while trying to paste text in textfield using S-Shoin keyboard.

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#148675]
### Steps to reproduce

1. copy some text
2. tap textformfeild
3. tap clipboard icon

### Expected results

the clipboard should be open

### Actual results

the clipboard is close

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class SamplePage extends StatefulWidget {

  SamplePage(): super();

  @override
  SamplePageState createState() => SamplePageState();
}

class SamplePageState extends State<SamplePage> with WidgetsBindingObserver {
  final TextEditingController _controller = TextEditingController();
  final FocusNode _focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextFormField(
          controller: _controller,
          focusNode: _focusNode,
          onChanged: (String value) {
            setState(() { });
          },
        ),
      )
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/7422251/c2525348-1734-44f3-bb8d-7d6d9a888029

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3593], locale ja-JP)
    • Flutter version 3.19.6 on channel stable at C:\Users\81708\Desktop\develop\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (5 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\81708\AppData\Local\Android\sdk
    • Platform android-34, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\81708\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3593]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 125.0.6422.60
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 125.0.2535.51

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by hatano0x06** [comment]
This is not a problem I found, but a problem my app users found
I could not find the same problem on my test device, but it may be a problem with a specific device.

Here is the user's device information
deviceName:SH-02M
osVersion:30

**Comment by darshankawar** [comment]
@hatano0x06 
Since this seems to be device specific, can you ask the user if the behavior occurs consistently ? Is there any log that is generated when the behavior occurs ? You may also ask them if the same occurs with native Android app or not to check if this is specific to Flutter or not.

**Comment by hatano0x06** [comment]
@darshankawar 
This behavior has always happened consistently, even after rebooting the device.

There are no logs, etc.
Maybe there are logs in Crashlytics, but they are so numerous that it is difficult to find this bug in them.

Other apps (probably native apps) are working fine, and this is only happening with this app.

**Comment by darshankawar** [comment]
I tried the given code using latest stable, on S10 device in which the clipboard copy paste works as expected.
@hatano0x06 Can you try to find out if there's any setting in the device itself which could be preventing clipboard to not work properly ?

**Comment by hatano0x06** [comment]
@darshankawar 
I asked the users.
As soon as I hear back from them, I will list them here

As for the device, could you please try with the AQUOS sense3 SH-02 series (SH-02M for the latest device)?

**Comment by darshankawar** [comment]
> AQUOS sense3 SH-02 series (SH-02M for the latest device)?

https://ola.tech/en/product/sharp-aquos-sense-3-shv45-sh02m-64gb-silver/ 

Sorry but I don't have this device to verify on.

**Comment by hatano0x06** [comment]
When we asked the user, he said he was using the keyboard app that comes standard with the device
Perhaps, you are using this keyboard app
https://play.google.com/store/apps/details?id=jp.co.sharp.android.iwnnime.ml&hl=ja&gl=US

**Comment by darshankawar** [comment]
@hatano0x06 
The keyboard seem to be specific for Sharp devices as mentioned below:

<img width="287" alt="Screenshot 2024-05-27 at 10 58 25 AM" src="https://github.com/flutter/flutter/assets/67046386/51075682-961d-4c30-8687-716d532c87ea">

So I can't verify this on my S10 device. Is there a way to confirm if the issue occurs using other Japanese keyboards that we can try ?

**Comment by darshankawar** [comment]
Thanks for coming up with repro code, but I tried it on S10 and also with Japanese keyboard but was unable to replicate the reported error. Since this seems to be related to specific keyboard + device, I'll keep the issue open for team's tracking.

**Comment by hatano0x06** [comment]
Since it is in Japanese, I think there are some points that are difficult to understand, so I filmed a video
This video shows how the problem occurs after the keyboard application is enabled.

Please follow the same steps and see if you can reproduce the problem!

https://github.com/flutter/flutter/assets/7422251/78c52d55-245a-4bb1-83a0-3baa190862ab

**Comment by justinmc** [comment]
Looks like from your code in https://github.com/flutter/flutter/issues/148675#issuecomment-2132996780 you are changing the focus in response to didChangeAppLifecycle, which seems to be the source of the behavior. Can you find another way to accomplish what you want? It seems like there is no bug in Flutter if I understand correctly.
