### ISSUE TITLE
flutter doctor -v  [Bad state: Future already completed]

### ISSUE THREAD

**Issue by wanghang199112** [flutter/flutter#14866]
**$ flutter doctor -v
Building flutter tool...
Unhandled exception:
```
Bad state: Future already completed**
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39)
#1      _NativeSocket.connect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:494)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:802)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:809)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:830)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```

**Comment by wanghang199112** [comment]
bogon:flutter wanghang$ flutter doctor
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.3M  100 43.3M    0     0  7489k      0  0:00:05  0:00:05 --:--:-- 9223k
Building flutter tool...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39)
#1      _NativeSocket.connect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:494)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:802)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:809)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:830)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...

**Comment by taojoe** [comment]
@wanghang199112 , If you are in China, you need to make sure your network can connect flutter resources directly. 

简单来说，需要翻墙

**Comment by InMatrix** [comment]
@wanghang199112 If you are using Flutter in China, please try the instructions here: https://github.com/flutter/flutter/wiki/Using-Flutter-in-China 

Let us know if that works for you.

**Comment by zoechi** [comment]
dup of #15014 ?

**Comment by CatchZeng** [comment]
https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

It also does not work.

**Comment by zoechi** [comment]
Probably a duplicate of #15014

Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by armarti** [comment]
still happening

**Comment by armarti** [comment]
Switching from DNS-over-HTTPS to unencrypted DNS fixed this for me.

**Comment by bianxiang** [comment]
I connected to VPN，but it also show "Bad state: Future already completed"!
![image](https://user-images.githubusercontent.com/16380379/66464152-02499b00-eab1-11e9-8958-61b449751ec0.png)
![image](https://user-images.githubusercontent.com/16380379/66464359-68362280-eab1-11e9-8e33-07295f708c2a.png)

**Comment by ScholarChild** [comment]
@bianxiang same problem with me before. you may change the protocol from 'OpenWeb' to 'StealthVPN' , and choose node which one with star ( such as, USA - Los Angeles 1).

![截屏2019-11-04下午5 42 57](https://user-images.githubusercontent.com/15724787/68111785-ebb92700-ff2a-11e9-8020-5f221c120e0d.png)

**Comment by lidongyx** [comment]
> @bianxiang same problem with me before. you may change the protocol from 'OpenWeb' to 'StealthVPN' , and choose node which one with star ( such as, USA - Los Angeles 1).
> 
> ![截屏2019-11-04下午5 42 57](https://user-images.githubusercontent.com/15724787/68111785-ebb92700-ff2a-11e9-8020-5f221c120e0d.png)

soo greaaaaaat!!!!
