### ISSUE TITLE
Able to access the history of the draw commands in Canvas

### ISSUE THREAD

**Issue by mimbrown** [flutter/flutter#148631]
### Use case

I would like to write a custom class which implements `Canvas` so that I can experiment with writing a Widget -> SVG converter. But the Flutter classes don't seem to give me the necessary information I would have expected to have in order to do this. For example, when implementing `drawPath`, the passed `Path` does not seem to support actually accessing the history of the commands (`lineTo`, `moveTo`, etc) used to define the path. Similarly the `Paragraph` passed to `drawParagraph` doesn't expose the actual text itself (that I can tell), which I would need.

### Proposal

I see in the source that the `Path` and `Paragraph` classes are wrappers around native implementations. Could these and other `dart:ui` types expose, in the wrapper and its implementations, the information necessary to actually do something meaningful in pure Dart? My use case is generating SVG I'm sure there are others.

For example, something like `getSegments()` on the `Path` class that outputs an array of the commands given to define the path would enable what I'm trying to do. I don't know all that would be required in which classes, so I don't know how big of an ask this is. But the main ask is, please expose what is necessary for custom implementations to do meaningful things.

**Comment by huycozy** [comment]
>the passed Path does not seem to support actually accessing the history of the commands (lineTo, moveTo, etc) used to define the path.

>Similarly the Paragraph passed to drawParagraph doesn't expose the actual text itself (that I can tell), which I would need.

Could you please be more specific by giving an example of these expectations?

**Comment by mimbrown** [comment]
@huycozy sure. For example, a Widget's painter might do something like this:

```dart
final path = Path();
path.moveTo(0, 0);
path.lineTo(5, 5);
canvas.drawPath(path, paint);
```

In my custom Canvas implementation, I need to know what commands were called (in this case, a `moveTo` followed by a `lineTo`). So I implement `drawPath`:

```dart
class MyCanvas implements Canvas {
  @override
  void drawPath(Path path, Paint paint) {
    // `path` was called with `moveTo(0, 0)` and `lineTo(5, 5)`, but I can't extract that information

    // I would like to do something like this (`getCommands` doesn't exist)
    for (const command of path.getCommands()) {
      // do something with command
      switch (command) {
        case MoveTo(:x, :y): {
          // build svg
        }
      }
    }
  }
}
```

**Comment by huycozy** [comment]
Thanks for clarifying it. Marking this as a feature request.

**Comment by mimbrown** [comment]
@huycozy that's just one example of what I feel is missing. Another would be accessing the sets of styled "runs" of text from the `Paragraph` class passed to `drawParagraph`.

The basic problem statement is, the classes passed to the various `draw*` commands in the `Canvas` class don't seem like they were designed to be useful outside of their native implementations. There's no particular reason for this that I can think of except that it just hasn't been done yet.

**Comment by jonahwilliams** [comment]
We're not going to add the functionality to introspect over all canvas operations. I would suggest writing shim classes that intercept the path/canvas ops you care about and then implementing your own recorder in Dart.

**Comment by mimbrown** [comment]
@jonahwilliams I'm a bit confused because your suggestion is exactly what I'm trying to do but can't because of how it works under the hood. I'm trying to write my own canvas recorder. As far as I know, I can't override how the dart `Path` class in `dart:ui` works, so I can't do anything about how it gets instantiated/written to. But it's genuinely surprising to me that, when I implement my own `drawPath` class on my custom canvas, I get a `Path` object that's practically useless. I can't "draw" it because it exposes none of the actual path information. It's all obfuscated in the native implementation.
