### ISSUE TITLE
Remove export of `hashValues` and `hashList` from `basic_types.dart`/`dart:ui`

### ISSUE THREAD

**Issue by parlough** [flutter/flutter#148690]
These APIs have been deprecated since Flutter 3.3, and therefore have passed their EOL. They have been superseded by static methods on `Object`: https://api.dart.dev/stable/3.4.0/dart-core/Object-class.html#static-methods

Once removed from the framework, their implementations can be removed from the engine.

**Comment by danagbemava-nc** [comment]
https://github.com/flutter/flutter/blob/d02292dbc40952a59dd1231ca2fb5ca86b39344c/packages/flutter/lib/src/painting/basic_types.dart#L50-L51

**Comment by goderbauer** [comment]
We will clean this up as part of https://github.com/flutter/flutter/issues/148361.

**Comment by ueman** [comment]
This seems to be done via https://github.com/flutter/flutter/pull/151677 and https://github.com/flutter/flutter/issues/151679
