### ISSUE TITLE
rror: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't.

### ISSUE THREAD

**Issue by devsigofficial** [flutter/flutter#148638]
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

../../../.pub-cache/hosted/pub.dev/fading_edge_scrollview-3.0.0/lib/src/fading_edge_scrollview.dart:116:31: Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't.
 - 'PageController' is from 'package:flutter/src/widgets/page_view.dart' ('../../../Library/Android/flutter/packages/flutter/lib/src/widgets/page_view.dart').
 - 'ScrollController' is from 'package:flutter/src/widgets/scroll_controller.dart' ('../../../Library/Android/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart').
      scrollController: child.controller,
                              ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/bholendraofficial/Library/Android/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1629

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/bholendraofficial/Library/Android/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 12s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by stuartmorgan** [comment]
> ../../../.pub-cache/hosted/pub.dev/fading_edge_scrollview-3.0.0

Issues in third-party packages need to be reported to the developers of the package.

Closing as this is not code that is part of the Flutter project.

**Comment by solugezero** [comment]
> dependency_overrides: fading_edge_scrollview: ^4.1.1

It helped! Thanks a lot!

**Comment by kishor-parmar-np** [comment]
> > dependency_overrides: fading_edge_scrollview: ^4.1.1
> 
> It helped! Thanks a lot!

It helped for me also, 
Thanks a lot!!!

**Comment by back3213** [comment]
> dependency_overrides : fading_edge_scrollview : ^ 4.1.1
It helped! Thanks a lot!

**Comment by rafidgotit** [comment]
> dependency_overrides: fading_edge_scrollview: ^4.1.1

Worked for me as well. Thanks a lot my brother from another mother 🥳

**Comment by dhiren-basra** [comment]
> dependency_overrides: fading_edge_scrollview: ^4.1.1

it works, thanks.

**Comment by KD-Dhiren** [comment]
> dependency_overrides: fading_edge_scrollview: ^4.1.1
it works, thanks.

**Comment by omarmaamoun179** [comment]
thank you alot

> dependency_overrides: fading_edge_scrollview: ^4.1.1
