### ISSUE TITLE
There is no suitable package for NFC Host card emulation in flutter.Is there any please reply me with information ?

### ISSUE THREAD

**Issue by MtoagF** [flutter/flutter#148666]
### Use case

I want to create a Flutter app for nfc hce but cannot find any sulution.

### Proposal

Please Create a new package for card emulation using nfc.

**Comment by danagbemava-nc** [comment]
Please feel free to check other community channels for assistance on this. There appears to be an existing package on pub.dev. See https://pub.dev/packages/nfc_host_card_emulation

Closing from here. 

Thank you
