### ISSUE TITLE
CupertinoPageRoute/Transition triggered by swipe back using magic keyboard trackpad

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#148609]
### Use case

Swipe back to close a page on iPhone/iPad works flawlessly, however it does not seem to be triggered via the trackpad on a Magic Keyboard (or other iPad accessory keyboards).

### Proposal

Ideally, swiping left or right on the accessory keyboard's trackpad would trigger the CupertinoPageRoute/Transition just as if the screen was directly swiped

**Comment by intelryzen** [comment]
It seems to work well in Flutter master version (3.22.0-36.0.pre.48).

**Comment by darshankawar** [comment]
@mark8044 Check above comment and see if it helps in your case or not.

**Comment by mark8044** [comment]
@darshankawar Hi for me it does not seem to work.  It will actually swipe forward and back on the listview that's on the screen (revealing some actions I have setup when you swipe left-right on the listview), but it will not actually try to close the window

@intelryzen Is there any special setup or coding you did to get the keyboard trackpad to behave that way for you?

**Comment by darshankawar** [comment]
@mark8044 Thanks for the feedback. Can you provide us a minimal reproducible code sample that shows the current behavior you are reporting ?

**Comment by mark8044** [comment]
@darshankawar Hi, Im not sure what code to post here, because the functionally would be baked into the CupertinoPageRoute/Transition, meaning the end user would not have to do anything (same as with making a screen swipe back/closed).

However, maybe there is something simple I can implement to make this work as @intelryzen seems to say it works for him.  I'll await and see if he has tips/pointers

Thanks much

**Comment by darshankawar** [comment]
@intelryzen Can you provide here the implementation that shows the use case works ?
