### ISSUE TITLE
[webview_flutter_web] JS interop and package:web migration

### ISSUE THREAD

**Issue by shrijanRegmi** [flutter/flutter#148680]
### Use case

The package [webview_flutter_web](https://pub.dev/packages/webview_flutter_web) package is holding us back in using WASM for our application.

### Proposal

I would like to request the migration of [webview_flutter_web](https://pub.dev/packages/webview_flutter_web) to JS interop and package:web as soon as possible, so that we can start using WASM.

**Comment by cedvdb** [comment]
duplicate

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139749
