### ISSUE TITLE
sentry support release(version of App)

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#14860]
Sentry worked fine for me. Thanks to the dev team.

We never know which version the exception was sent by.
Support release(version) may be helpful.

Document:
https://sentry.io/offer/offer/settings/release-tracking/

**Comment by NemOry** [comment]
I highly need this as well...... This is the only thing missing right now and it would be perfect

**Comment by zoechi** [comment]
@NemOry you can follow #4547
https://github.com/flutter/plugins/blob/master/packages/package_info/lib/package_info.dart might also do what you want.

**Comment by NemOry** [comment]
@zoechi thanks a lot. I have that package and use that too. But where in my sentry code would be proper to put it? Can you please give an example?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
