### ISSUE TITLE
 Missing class android.window.BackEvent

### ISSUE THREAD

**Issue by danedyy** [flutter/flutter#148695]
### Steps to reproduce

  webview_flutter: ^4.7.0
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (5 available)
[✓] Network resources

### Actual results

ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/user/Documents/work/project/build/flutter_inappwebview_android/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class android.window.BackEvent (referenced from: void io.flutter.embedding.android.FlutterActivity.startBackGesture(android.window.BackEvent) and 3 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_inappwebview_android:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (5 available)
[✓] Network resources

</details>

**Comment by matiskiba** [comment]
I'm experiencing the same with flutter_inappwebview 6.0.0
seems like the flutter upgrade I've performed caused it

**Comment by huycozy** [comment]
@danedyy @matiskiba The issue with `flutter_inappwebview` should be reported to [its repository](https://github.com/pichillilorenzo/flutter_inappwebview) for better support there. I see there is already an issue at https://github.com/pichillilorenzo/flutter_inappwebview/issues/2139.

Closing this as it's not an issue with 1st party package.
