### ISSUE TITLE
Error due to dependency mismatching after upgrading Flutter to 3.22

### ISSUE THREAD

**Issue by Julio-sudo** [flutter/flutter#148608]
### Steps to reproduce

Until this morning, I was running on Flutter 3.19 I decided to upgrade to 3.22 So I opened my terminal and run `flutter upgrade`. The download of the new version have been launched and has ended without any connexion problem. Since that, I suddenly face an error about depency mismatching. The error says 

_Resolving dependencies... (5.6s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions, version solving failed.
You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)_

I'm on Ubuntu 22.04 and I'm on the stable flutter channel.

### Actual results

I check in my pubsec.yaml files but any of them have the `mime` as dependency. Then I tried to do `flutter clean` but any `flutter` or `dart` command I launch gives either 

- Waiting for another flutter command to release the startup lock...
or

- Building flutter tool...
Resolving dependencies... (5.0s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions, version solving failed.
You can try the following suggestion to make the pubspec resolve:
 Consider downgrading your constraint on mime: dart pub add mime:^1.0.4

Here is a screensot of the output of `flutter doctor -v` 

![image](https://github.com/flutter/flutter/assets/59259697/244b4037-ba72-49b7-9130-69f188da5266)

Here is a notification I get from my Android Studio after I launched it
![Capture d’écran du 2024-05-18 15-30-48](https://github.com/flutter/flutter/assets/59259697/e5225dbd-4cb9-4bdd-a4f5-8342601d07bd)

The depency with mime seems clearly to be the cause of the issue. The problem is that I don't know how to deal with it. 

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

 Building flutter tool...
Resolving dependencies... (7.7s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Resolving dependencies... (8.0s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Resolving dependencies... (8.8s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
Resolving dependencies... (6.6s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)
Resolving dependencies... (5.1s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)
Resolving dependencies... (5.1s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
Resolving dependencies... (5.2s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)
Resolving dependencies... (5.2s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (2 tries left)
Resolving dependencies... (5.4s)
Because flutter_tools depends on mime 1.0.5 which doesn't match any versions,
  version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mime: dart pub add mime:^1.0.4
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (1 tries left)
Command 'pub upgrade' still failed after 10 tries, giving up.
 

```

</details>

**Comment by huycozy** [comment]
Hi @Julio-sudo 
>I check in my pubsec.yaml files but any of them have the mime as dependency.

Could you share mime version you are using? I added `mime: ^1.0.5` but couldn't see this issue. Could you also check if this issue appears on a new Flutter project?
