### ISSUE TITLE
Some special characters are not displayed after impeller is turned on on iOS

### ISSUE THREAD

**Issue by liulianshanzhu** [flutter/flutter#148663]
### Steps to reproduce

1.Upgrade flutter version 3.19.0 to version 3.22.0
2.Turn on impeller rendering on ios
3.Display some special characters in text, such as 🇭​​🇦​​🇲​🇺​​🇩​​🇦​

### Expected results

Expected to be able to display all characters on iOS phones

### Actual results

None of these characters are displayed

### Code sample

<details open><summary>Code sample</summary>

```dart
 Text('🇺🇩🇦𝄞⃝🇩ᬼ')
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.22.0, on macOS 14.1 23B2073 darwin-arm64)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Network resources

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @liulianshanzhu, can you share screenshots of what the text is supposed to look like? What did it look like on 3.19.0 and what does it look like on 3.22.0?
