### ISSUE TITLE
TextField highlight color changed to purple after updating flutter to 3.22.0

### ISSUE THREAD

**Issue by appDevel1234** [flutter/flutter#148644]
Hi! Today I updated flutter from 3.13.7 to 3.22.0 (stable channel). Since then the highlight color and the color of the two pins in `TextField` widget changed to purple on Android and iOS:

![TextField](https://github.com/flutter/flutter/assets/155992687/6bfa6d9a-8f7e-4a09-b554-597e61983d98)

I already tried some solutions from StackOverflow to change the color, but none of these were working. If I'm setting `useMaterial3` to `false`, then the color changed to the blue from old flutter version. How can I change the color to another color then purple?

```
MaterialApp(
   // ...
      theme: ThemeData(
        useMaterial3: false,
        // ...
      ),
  // ...
);
```

Thanks in advance! :)

**Comment by navaronbracke** [comment]
See https://api.flutter.dev/flutter/material/TextSelectionTheme-class.html :)

**Comment by appDevel1234** [comment]
Thanks for your quick response! :) Okay, this really helped me to solve the problem. 

But it is important to read the documentation for the `selectionHandleColor` parameter in `TextSelectionThemeData`: **For iOS it is necessary to define the color for the two selector pins via `CupertinoThemeData.primaryColor`**. So the following code solved my problem:

```
MaterialApp(
   theme: ThemeData(
      cupertinoOverrideTheme: const CupertinoThemeData().copyWith(primaryColor: Colors.blue),
      textSelectionTheme: TextSelectionThemeData(
         cursorColor: Colors.blue,
         selectionHandleColor: Colors.blue,
         selectionColor: Colors.blue,
        ),
      // ...
   ),
   //...
);
```
