### ISSUE TITLE
Can we use Flutter for PWA (Progressive Web App) ?

### ISSUE THREAD

**Issue by HeratPatel** [flutter/flutter#14868]
My Question is can we use Flutter for Mobile Web development ?

**Comment by rmtmckenzie** [comment]
https://flutter.io/faq/#does-flutter-run-on-the-web

**Comment by rmtmckenzie** [comment]
You can split out any business logic type operations into pure-dart libraries and then use AngularDart for the web side of things, importing the relevant libraries to both flutter and AngularDart.

**Comment by mikelward** [comment]
There was a great talk about this at DartConf: https://youtu.be/PLHln7wHgPE

**Comment by MentalGear** [comment]
A native "deploy to web" function would be much appreciated, and would open flutter to the huge community of web developers & users. A must have !

**Comment by bockoblur** [comment]
Absolutely. +1

**Comment by Hixie** [comment]
This is not something we are intending to implement any time soon.

**Comment by timahrentlov** [comment]
It should be possible to bundle a flutter app in an web assembly. Flutter brings it’s own UI, so there should be a natural fit.

**Comment by RainingNight** [comment]
We very need a web version of Flutter.

**Comment by prijindal** [comment]
Even some framework or something as simple as a ui library to help with angulardart(for web) + flutter(for mobile) would be a huge step

**Comment by nhugodot** [comment]
Pardon my mistake if any, I'm not a dev. But as far as I understand the web and OS's UI architectures, Web (HTML, DOM) and OS's UI (say, QT, GTK, ...) "rendering" systems are totally different paradigms, making it hard, if not impossible, to make a Web AND real OS (Windows, Android, iOS, whatever...) universal framework.
That's why Flutter can't be used to Web. Logic and graphic elements, "widgets", are all-in-one objects while the Web layers view (HTML, CSS) and logic (JS).

Still, Facebook did a great job with React and its virtual DOM, and we can share up to 93% of the code between a ReactJS (Web) and ReactNative (Android, iOS) code... Ok, one of the main discussed difference between React and Flutter is this exact point: where React separate view and logic, Flutter mix them. React is a hybrid framework coming from the Web paradigm, and succeeded to manage native UI elements with ReactNative library... Flutter adopted a totally different way of doing the thing, coming from the OS paradigm, and like Qt or GTK, comes with its full set of UI elements. Right?

Now what? If React succeeded to make Web UI architecture work with native OS components, would it be really impossible to make the other way around, Flutter control a kind of virtual DOM and Web'HTML/CSS??? After React "Native", a Flutter "Web" or "DOM"?

Actually, there's an experimental project trying to do it: https://github.com/yjbanov/butterfly

**Comment by sudhirj** [comment]
A Flutter Web UI would no more use HTML/DOM than the iOS version uses UIKit or the Android version the SDK view - they don't. Flutter on WASM would likely bypass HTML and render straight to a Canvas.

**Comment by rrousselGit** [comment]
Dart to webasm is not a thing. https://groups.google.com/a/dartlang.org/forum/#!topic/misc/szGdXdLrZM8%5B126-150%5D
And dart2js would cause performances problem.

This could be fine is somehow browsers integrated a dartVM natively. But chrome team refused, so I doubt others will. 

____

I think overall the best solution is splitting your app into packages that don't depend on the OS. And use AngularDart+Flutter altogether.



You may also want to use dart2js interop for things like VUE or React.

**Comment by gedw99** [comment]
The Skia team have Pathkit ( which is the Flutter Compositor) working on the web now.

The skia WASM code:
https://github.com/google/skia/tree/master/experimental/pathkit

The flutter engine referencing it :)
https://github.com/flutter/engine/blob/master/ci/licenses_golden/licenses_skia#L1602
https://github.com/flutter/engine/tree/master/flow



SO there is a good chance that Flutter for Web rendering to canvas ( not html DOM) will happen ?

**Comment by doertli** [comment]
React Native Web is doing well in this area (universal code base for web, native apps, VR apps, desktop apps). Would be fantastic for Flutter to be able to 'target' different platforms also. Next step up in developer super powers.

**Comment by C-Alexander** [comment]
I doubt the flutter team would blow up a project by others to get this working, but Flutter for mobile already has tons of improvements yet to be made, I'm not sure if expanding to the web (which already has a huge amount of options), while certainly possible (albeit obviously a *lot* of work) is something we should be wishing them to take on right now..

**Comment by qazn123** [comment]
Since Flutter is built based on the Materials Design concepts (MDC), I would think there should be a separate framework decided to building Web app using MDC. I recently looked and it looks like there's already support in Materials Design for web development.

**Comment by thosakwe** [comment]
I don't think it will really be "so easy" to port Flutter to the Web. I think it will be better for all users if the team continues to focus primarily on mobile. Porting Flutter to the Web not only requires porting a Dart VM to WebAssembly (or AOT, both of which are gonna be complex). And then add to that the expectation of hot reloading, etc. that people will for sure have.

If the community really wants it, though, then I don't see why not to just try and do it ourselves.

Let me just put this out there - I tried to port to the standalone Dart VM to WebAssembly, using Emscripten, and all I can say is that there are many more moving parts than I had imagined. It won't be easy.

**Comment by Gee5ive** [comment]
We really don’t need an exact “flutter on the web” what would be really cool though is simple api compatibility between a dart web framework and flutter.

**Comment by rrousselGit** [comment]
@Gee5ive That's BLoC architecture.

**Comment by Gee5ive** [comment]
@rrousselGit I mean the actual widget api.

**Comment by jodinathan** [comment]
I understand you.
My projects, VM and web, are sharing lots of libs.
Would be insanely nice to share designing libs between flutter and web.

Jonathan Rezende

**Comment by Gee5ive** [comment]
@jodinathan 

Yup, I think https://workiva.github.io/over_react/ would be the best starting point for something like this. Would be a huge undertaking and require lots of community effort though. Would be really worth it for the dart ecosystem in the long run though.

**Comment by edunuzzi** [comment]
It seems that they recently announced [Hummingbird](https://medium.com/flutter-io/hummingbird-building-flutter-for-the-web-e687c2a023a8), which should enable running Flutter on the web.

**Comment by ORESoftware** [comment]
This makes me wonder about the architecture of the web itself. Today we create SPAs and trick the system with hashes `#` in the URL or other tricks like that.  Why can't a server send an executable file which runs in the browser*? Just like with Java Applets. Except now with Web Assembly you don't need to embed a JVM in the browser or other runtime in the browser? Alternatively, the executable that the server sends could be precompiled based on what browser you are using?

*The browser is a nice sandbox for such an executable file to run in, so security is taken care of.

**Comment by michaellee8** [comment]
@Hixie Are there any progress or ETA for Hummingbird. The project seems so good but it seems that it never went public.

**Comment by chenzhekl** [comment]
It's announced at Google I/O 2019 https://flutter.dev/web

**Comment by gladimdim** [comment]
You can use it on latest flutter master branch:

```
flutter channel master
flutter upgrade
flutter doctor
flutter create .
flutter run -d chrome
```

It will generate all projects and run the Flutter Web Application. the service worker is auto generated with a list of all resources to be cached.

**Comment by ansarizafar** [comment]
@gladimdim Its not working on latest master branch. I am getting following errors.

![image](https://user-images.githubusercontent.com/5788284/73368382-a9f20f80-42d2-11ea-8ad2-f119d7efb5cc.png)
