### ISSUE TITLE
App get stuck on splash screen after downloading it from Google Play Store

### ISSUE THREAD

**Issue by lakshydeep-14** [flutter/flutter#148642]
### Steps to reproduce

1. download it from playstore
2. open the app
3. it will get stuck on splash screen

### Expected results

App must run properly and must go beyond splash screen.

### Actual results

Stuck on splash screen.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Lakshydeep’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Lakshydeep Vikram’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!]
```

</details>

**Comment by hls-app** [comment]
Try `flutter run -v`

**Comment by lakshydeep-14** [comment]
> Try `flutter run -v`

Everything is working fine.
Many users are facing issue after downloading app from Google Play Store.

What might be the problem?

**Comment by darshankawar** [comment]
@lakshydeep-14 
There could be many reasons as why the app is stuck on splash screen. For example, check following:

- Database integration if you are using it in your app.
- apk or bundle is signed properly with all requirements.
- Third party integration is correctly implemented.

Without any error or log that points to framework, we can't properly address the issue. Also check in support channels like Stackoverflow to get more idea or reference.

**Comment by lakshydeep-14** [comment]
I had used these below package:
advanced_rich_text: ^0.0.1+1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cool_alert: ^2.0.1
  cupertino_icons: ^1.0.2
  date_picker_plus: ^3.0.2
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.7
  expandable: ^5.0.1
  file: ^7.0.0
  file_picker: ^6.1.1
  file_saver: ^0.2.12
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cached_pdfview: ^0.4.2
  flutter_expandable_table: ^2.0.0
  flutter_secure_storage: ^9.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.14.11
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.6
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  gradient_borders: ^1.0.0
  image_picker: ^1.0.7
  in_app_review: ^2.0.8
  injectable: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  keyboard_actions: ^4.2.0
  loading_animation_widget: ^1.2.0+4
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
  mobile_scanner: ^4.0.0
  nepali_date_picker: ^6.0.0
  nepali_english_calendar: ^1.0.1+1
  nepali_utils: ^3.0.4
  new_version_plus: ^0.0.11
  onesignal_flutter: ^3.0.0
  package_info_plus: null
  path_provider: ^2.0.11
  percent_indicator: ^4.2.3
  permission_handler: ^11.1.0
  photo_view: ^0.14.0
  popup_banner: ^1.0.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.12
  shimmer: ^3.0.0
  simple_gradient_text: ^1.3.0
  table_calendar: ^3.0.5
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.3
  webview_flutter_android: ^3.13.2
  webview_flutter_wkwebview: ^3.10.1


why my app is stucking on splash screen after updating it from playstore?

**Comment by darshankawar** [comment]
@lakshydeep-14 
As mentioned earlier, you'll need to isolate the code implementation to see what could be causing the reported error. We can't tell or analyze based on the details you provided. You are using lot of third party packages, so check if their implementation could be conflicting with manifest file settings you have.
