### ISSUE TITLE
FileSystemException: Failed to decode data using encoding 'utf-8', path = '/Users/rajkumar/.dart-tool/dart-flutter-telemetry.log'

### ISSUE THREAD

**Issue by Rajkumar07793** [flutter/flutter#148602]
### Steps to reproduce

```
Unhandled exception:
**FileSystemException: Failed to decode data using encoding 'utf-8', path = '/Users/rajkumar/.dart-tool/dart-flutter-telemetry.log'**
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      LogHandler.save (package:unified_analytics/src/log_handler.dart:272:27)
#5      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:608:17)
#6      _handleToolError (package:flutter_tools/runner.dart:190:23)
#7      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#8      _rootRunBinary (dart:async/zone.dart:1423:47)
#9      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#10     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#11     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#12     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#13     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#14     Future._completeError (dart:async/future_impl.dart:651:5)
#15     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#16     _rootRun (dart:async/zone.dart:1399:13)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

### Expected results

When I want to run cmd "flutter doctor" it should give flutter doctor log but not supporting any of the commands

### Actual results

I'm getting this below error

```
FileSystemException: Failed to decode data using encoding 'utf-8', path = '/Users/rajkumar/.dart-tool/dart-flutter-telemetry.log'
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      LogHandler.save (package:unified_analytics/src/log_handler.dart:272:27)
#5      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:608:17)
#6      _handleToolError (package:flutter_tools/runner.dart:190:23)
#7      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#8      _rootRunBinary (dart:async/zone.dart:1423:47)
#9      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#10     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#11     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#12     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#13     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#14     Future._completeError (dart:async/future_impl.dart:651:5)
#15     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#16     _rootRun (dart:async/zone.dart:1399:13)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1440" alt="Screenshot 2024-05-18 at 2 03 17 PM" src="https://github.com/flutter/flutter/assets/31760975/283b3a7d-129c-4f2d-84ed-9828bcd24db6">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

rajkumar@RAJKUMARs-MacBook-Pro ~ % flutter doctor 


```
Unhandled exception:
FileSystemException: Failed to decode data using encoding 'utf-8', path = '/Users/rajkumar/.dart-tool/dart-flutter-telemetry.log'
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      LogHandler.save (package:unified_analytics/src/log_handler.dart:272:27)
#5      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:608:17)
#6      _handleToolError (package:flutter_tools/runner.dart:190:23)
#7      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#8      _rootRunBinary (dart:async/zone.dart:1423:47)
#9      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#10     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#11     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#12     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#13     Future._propagateToListeners (dart:async/future_impl.dart:788:16)
#14     Future._completeError (dart:async/future_impl.dart:651:5)
#15     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:737:7)
#16     _rootRun (dart:async/zone.dart:1399:13)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```

</details>

**Comment by darshankawar** [comment]
@Rajkumar07793 
Are you getting this error everytime you try to run any flutter command ? What flutter version are you on ?

**Comment by Rajkumar07793** [comment]
I'm using flutter version 3.19.6 but i solved this error by deleting 
.pub-cache
.dart-tool

**Comment by darshankawar** [comment]
Closing as resolved.
