### ISSUE TITLE
Pod Install Is Not Working 

### ISSUE THREAD

**Issue by SakhileMamba** [flutter/flutter#148605]
### Steps to reproduce

I have set up my project to use Firebase but whenever I try to install the pods for the iOS app to use Firebase, I get errors.

### Actual results

sakhile@Sakhiles-Mini ios % pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
Downloading dependencies
Installing BoringSSL-GRPC (0.0.32)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/ym/xd8dj0mj1wx2hf6_5j36lnh00000gn/T/d20240518-83716-81segq --template=

Cloning into '/var/folders/ym/xd8dj0mj1wx2hf6_5j36lnh00000gn/T/d20240518-83716-81segq'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 14690 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

sakhile@Sakhiles-Mini ios % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64 (Rosetta), locale en-SZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by Bestfootballer** [comment]
Hi @SakhileMamba I reproduced steps you described, but everything worked fine for me.
Maybe it was a network error in your case.
Did you try to delete **Pods folder** and **Podfile.lock** and rerun <b>pod install</b>

Try to execute these commands: `flutter clean; flutter pub get; cd ios; rm -rf Pods/ Podfile.lock; pod install`

- `flutter clean`: clean build folder
- `flutter pub get`: download Flutter packages;
- `cd ios`: switch to ios directory
- `rm -rf Pods/ Podfile.lock`: delete cached/installed Pods
- `pod install`: reinstall pods

**Comment by SakhileMamba** [comment]
Hi @Bestfootballer, I have been trying your suggestions for weeks now. I can normally download large files from my internet connection without any interruptions but for some reason, this just doesn't work for me. My internet speed averages 1.9 Mbps.

Flutter works if I don't have any pod dependencies in my project.

**Comment by Bestfootballer** [comment]
@SakhileMamba did you tried to switch to another network and retry to install?

**Comment by SakhileMamba** [comment]
@Bestfootballer 
• I tried to update/reinstall the Cocoapods package.

Let me attempt the other ideas.

**Comment by darshankawar** [comment]
@SakhileMamba 
This isn't an issue with flutter framework but with grpc dependency being used by firebase plugins. Check StackOverflow for solutions or see https://github.com/firebase/flutterfire/issues/12660

Closing from here.
