### ISSUE TITLE
[google_maps_flutter_web] Support WASM compilation

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#148624]
### Use case

Support Flutter web WASM compilation

### Proposal

Migrate to the new web packages

Related issues:
- https://github.com/a14n/dart-google-maps/issues/130
- https://github.com/a14n/dart-google-maps/issues/125

**Comment by Rexios80** [comment]
I see this comment mentioning possibly existing work on this?
https://github.com/a14n/dart-js-wrapping/pull/27#issuecomment-2110520194

Is there an existing issue for this?

**Comment by OlegShNayax** [comment]
Any updates?
