### ISSUE TITLE
App gray mode

### ISSUE THREAD

**Issue by illusionGeorge** [flutter/flutter#148732]
### Use case

we should add app global decolorization like gray mode.
I  use ColorFiltered/ShaderMask in root widget.But it will affect my native 3rd map sdk  render.

<img src="https://github.com/flutter/flutter/assets/16495832/a72f1277-6012-4ec3-9c35-f4f18d59b8cb" width="250px"/>

and when render h5 page , it will different between iOS & android.

<img src="https://github.com/flutter/flutter/assets/16495832/b3dd66aa-3a02-4cb3-8289-a94f7c97c287" width="250px"/>|<img src="https://github.com/flutter/flutter/assets/16495832/7fa52357-7766-446f-8dbb-5feb4a5df71e" width="250px"/>

### Proposal

code sample

**Comment by darshankawar** [comment]
@illusionGeorge 
Can you elaborate on your use case as what exactly are you trying to achieve ? Curious to know if this feature is already available in native ?

**Comment by darshankawar** [comment]
> I just find ColorFiltered can let my app into gray mode . If my app include native view or H5 view. Under this gray mode will affect native render & H5 render . How can I solve this issue?

Please provide runnable reproducible code sample that shows the issue you are facing. Also, StackOverflow would be a better platform to ask for solution in code implementation.

**Comment by illusionGeorge** [comment]
`ColorFiltered(
        colorFilter: ColorFilter.mode(Colors.grey, BlendMode.saturation),
        child: widgetTree,
);`
I use ColorFiltered warp my widget in my RootWidget. 
But native map view render in my child view.
And H5 view also render in my child view.

**Comment by darshankawar** [comment]
I think you are hitting https://github.com/flutter/flutter/issues/39270 so please follow-up in it for further updates.
Closing this as a duplicate.
