### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by mehmet4kif** [flutter/flutter#148761]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:177:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:902:19)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#10     FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:716:16)
<asynchronous suspension>
#11     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:1274:18)
<asynchronous suspension>
#12     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:321:11)
<asynchronous suspension>
#13     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.0, on Ubuntu 22.04.4 LTS 6.5.0-35-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.22.0 on channel stable at /home/meakay/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5dcb86f68f (12 days ago), 2024-05-09 07:39:20 -0500
    [32m•[39m Engine revision f6344b75dc
    [32m•[39m Dart version 3.4.0
    [32m•[39m DevTools version 2.34.3

[31m[✗][39m Android toolchain - develop for Android devices
    [32m•[39m Android SDK at /usr/lib/android-sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 10.0.0-4ubuntu1
    [32m•[39m cmake version 3.16.3
    [32m•[39m ninja version 1.10.0
    [32m•[39m pkg-config version 0.29.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.89.1)
    [32m•[39m VS Code at /snap/code/current/usr/share/code
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-35-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.118

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ba393198430278b6595976de84fe170f553cc728

**Comment by LimaneGaya** [comment]
> flutter run
Was it on a new project?
Did it work before?

**Comment by mehmet4kif** [comment]
> > flutter run
> 
> Was it on a new project?
> Did it work before? 

No, it is not a new project. I downloaded the license with sdkmanager and also i ran flutter create . command because it does not work on Android.

**Comment by LimaneGaya** [comment]
> No, it is not a new project. I downloaded the license with sdkmanager and also i ran flutter create . command because it does not work on Android.

I assume it works on local machine with the command `flutter run -d linux` ?

> �[31m✗�[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`

I would guess it does not work on android because cmdline-tools is missing and needs to be installed or it's not setup correctly.
Android sdk needs to follow this folder structure
In the directory `/usr/lib/android-sdk` make sure it's as follows:
> tools
>> bin 
>> lib

Then go to `/usr/lib/android-sdk/tools/bin` and run  `./sdkmanager --install "cmdline-tools;latest`

**Comment by LimaneGaya** [comment]
> No, it is not a new project. I downloaded the license with sdkmanager and also i ran flutter create . command because it does not work on Android.

I assume it works on local machine with the command `flutter run -d linux` ?

> �[31m✗�[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`

I would guess it does not work on android because cmdline-tools is missing and needs to be installed or it's not setup correctly.
Android sdk needs to follow this folder structure
In the directory `/usr/lib/android-sdk` make sure it's as follows:
> cmdline-tools
>>latest
>>> bin 
>>> lib

then retry and let me know if it works

**Comment by LorenzoRogai** [comment]
seems a github issue https://github.com/orgs/community/discussions/125085

**Comment by huycozy** [comment]
@mehmet4kif Can you check https://github.com/flutter/flutter/issues/141238#issuecomment-1894841881 to see if it assembles your case?
