### ISSUE TITLE
Support Tibetan Script in CanvasKit/Skwasm

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#148797]
We need to add `Noto Serif Tibetan` (https://fonts.google.com/noto/specimen/Noto+Serif+Tibetan) to our fallback fonts to support Tibetan script.

**Comment by ditman** [comment]
There's this issue in "noto" asking for a "sans-serif" version of Tibetan (which is probably why we never added it to our list originally!)

* https://github.com/notofonts/tibetan/issues/10

I'm unsure how jarring would it be to a reader to see the mix of serif with our other sans-serif default (but it's definitely better than showing tofu boxes!)

**Comment by yjbanov** [comment]
Probably serif is better than nothing.
