### ISSUE TITLE
Version 3.22.0 does not support Windows 7

### ISSUE THREAD

**Issue by zengjianxiong** [flutter/flutter#148743]
### Steps to reproduce

Using 3.19.6 can be opened normally on win7, but upgrading to 3.22.0 can't. It feels like the problem is similar to this [#130554].
![微信截图_20240521144113](https://github.com/flutter/flutter/assets/13110953/ec11d4a9-2f4f-4bb4-b824-d70cd599032e)
![微信截图_20240521145310](https://github.com/flutter/flutter/assets/13110953/f6566514-2b0a-4515-b7ee-0f54c2257b67)

### Expected results

Version 3.22.0 does not support Windows 7

### Actual results

Version 3.22.0 does not support Windows 7

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by fanchou** [comment]
3.19.6 is the last release that supports Win7.
