### ISSUE TITLE
[local_auth] isDeviceSupported() behavior not clear

### ISSUE THREAD

**Issue by d3im** [flutter/flutter#148751]
### Steps to reproduce

1. disable screen lock & biometrics in Android Emulator
2. run basic init code with local_auth
3. get isDeviceSupported()

### Expected results

is device supported? I suppose it should return true.

When I enable screen lock it returns true.

### Actual results

false

### Code sample

<details open><summary>Code sample</summary>

```dart
late LocalAuthentication auth;
late List<BiometricType> availableBiometrics;
late int maxAuthLevel;

Future<int> getMaxAuth() async {
  auth = LocalAuthentication();
  availableBiometrics = await auth.getAvailableBiometrics();
  debugPrint("Biometrics Types: ${availableBiometrics.toString()}");
  if (await auth.isDeviceSupported()) {
    debugPrint("auth.isDeviceSupported()");
    if (await auth.canCheckBiometrics) {
      debugPrint("auth.canCheckBiometrics");
      return 2;
    }
    return 1;
  }
  return 0;
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on Gentoo Linux 6.8.4-gentoo-rt11-systemd, locale cs_CZ.UTF-8)
    • Flutter version 3.22.0 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (12 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/deim/android/android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/deim/android/android
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.5
    • cmake version 3.29.3
    • ninja version 1.11.1
    • pkg-config version 2.2.0

[✓] Android Studio (version 2023.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 78.2.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Gentoo Linux 6.8.4-gentoo-rt11-systemd

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @d3im, what is `local_auth_android: ^1.0.38` version you are using? (you should get it from `pubspec.lock`). I checked the issue using [package example](https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth/example) but it works as expected. You can also try this sample code and confirm the result.

**Comment by d3im** [comment]
local_auth_android version is 1.0.38
I tried example as suggested and result (after clicked all buttons) follows:
![Screenshot_20240522_151147](https://github.com/flutter/flutter/assets/17542229/d27e7e16-1d06-4fb4-a76e-e9bb7ccb26c3)
Could this problem be caused by modified default settings in flutter?
I have this as default in /opt/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy
```config
...
    public final int compileSdkVersion = 34
    public  final int minSdkVersion = 21
    public final int targetSdkVersion = 34
    public final String ndkVersion = "25.1.8937393"
...
```

**Comment by huycozy** [comment]
>Could this problem be caused by modified default settings in flutter?

Does the issue persist if you keep those settings as default on the package's example?

And what is your Android device info (OS, model)? May be similar or related to https://github.com/flutter/flutter/issues/147453 which happens on Android 10.

**Comment by d3im** [comment]
Default settings gives the exactly same results.
It's Android Emulator - Pixel 7 Pro API 34 Android 14.0 Kernel version: 6.1.23

**Comment by huycozy** [comment]
Checking this on my device Pixel 7, Android 14, it also works as expected. 

<details>
<summary>Demo</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/88c1ae02-8a41-4530-a81b-ca4f64b7464d">
</details>

I also tried on an Android 11 emulator and saw the expected result as well. My Android 14 emulator is frozen so I couldn't check this now (maybe later). Meanwhile, could you check this on physical devices or lower Android API emulators?

**Comment by d3im** [comment]
Just a thought . I see specific difference in Your example: You have enrolled biometrics as seen in screenshot.
When I enroll some biometrics or enable screen lock (any - pin/gesture/...) the device returns it is supported.
Please try to temporarily disable all biometrics and screen locks, would it return device is supported then?

**Comment by huycozy** [comment]
When disabling screen locks, it returns as unsupported which means there is no device credential on the device. It reflects as documented:

>   /// Returns true if device is capable of checking biometrics or is able to
  /// fail over to device credentials.

Does it make sense?

**Comment by d3im** [comment]
OK so it does something different, just inconvenience.

I just want to get maximum supported on mobile phone so when nothing is enabled I will just check auth.canCheckBiometrics which seem return if biometrics could be used or not even if they're not enrolled.

I will assume mobile device always support PIN/Gesture/...

The one more problem rises:

Dialogs

The plugin provides default dialogs for the following cases:

    Passcode/PIN/Pattern Not Set: The user has not yet configured a passcode on iOS or PIN/pattern on Android.
    Biometrics Not Enrolled: The user has not enrolled any biometrics on the device.

If a user does not have the necessary authentication enrolled when authenticate is called, they will be given the option to enroll at that point, or cancel authentication.

If you don't want to use the default dialogs, set the useErrorDialogs option to false to have authenticate immediately return an error in those cases.

When I call:
```dart
await auth.authenticate(
            localizedReason: "[Try Auth Reason]",
            options: AuthenticationOptions(
                stickyAuth: true, biometricOnly: widget.order > 1))
```

with no local auth (PIN/Gesture/Biometrics) I get:
```Unhandled Exception: PlatformException(NotAvailable, Security credentials not available., null, null)```

not dialog to enroll Biometrics or Gesture.

**Comment by huycozy** [comment]
>I just want to get maximum supported on mobile phone so when nothing is enabled I will just check auth.canCheckBiometrics which seem return if biometrics could be used or not even if they're not enrolled.

`canCheckBiometrics` checks if biometric hardware is supported or not, see:

```java
public @NonNull Boolean deviceCanSupportBiometrics() {
  return hasBiometricHardware();
}
...
private boolean hasBiometricHardware() {
  if (biometricManager == null) return false;
  return biometricManager.canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_WEAK)
      != BiometricManager.BIOMETRIC_ERROR_NO_HARDWARE;
}
```

You can check its test cases here: [LocalAuthTest.java#L227-L254](https://github.com/flutter/packages/blob/200e3c6cb35111479870397b131d5341676446e7/packages/local_auth/local_auth_android/android/src/test/java/io/flutter/plugins/localauth/LocalAuthTest.java#L227-L254) as examples to see which case it will return true/false.

>not dialog to enroll Biometrics or Gesture.

There is an open issue for this at https://github.com/flutter/flutter/issues/96646. Please follow it for updates.

Closing the original issue as explained above. If you disagree, please write in the comments.
