### ISSUE TITLE
Crash when running flutter on Windows 7 x64 Russian

### ISSUE THREAD

**Issue by scheglov** [flutter/flutter#14877]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

I run `flutter doctor`, with `-v` or without it - it crashes.
Maybe because of Russian locale in my Windows 7?

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

[flutter_01.log](https://github.com/flutter/flutter/files/1757423/flutter_01.log)

**Comment by scheglov** [comment]
I found the reason for the crash.
It happens when `git` is actually `git.bat` installed as `msysgit`.

```
C:\dart\flutter>git log -n 1 --pretty=format:%ad --date=iso

ad

C:\dart\flutter>where git
C:\Utils\git.bat
C:\Utils\msysgit\bin\git.exe
C:\Utils\depot_tools\git.bat
C:\Program Files\Git\cmd\git.exe

C:\dart\flutter>type c:\utils\git.bat
@echo off
call "%~dp0\msysgit\git-cmd.bat" %*

C:\dart\flutter>C:\Utils\msysgit\bin\git.exe log -n 1 --pretty=format:%ad --date=iso

2018-04-03 10:59:12 -0700

C:\dart\flutter>C:\Utils\git.bat log -n 1 --pretty=format:%ad --date=iso

ad
```

**Comment by csells** [comment]
@scheglov would you have expected flutter to work under these circumstances? or to produce a more helpful error message?

**Comment by scheglov** [comment]
If there are different, incompatible implementations of `git` on Windows, it might be useful to detect them. Or validate that the format of data returned from `git` matches expectations and ask the user to check that `git` is this or that supported. Crash is never a good option.

Honestly, I don't know if this issue is any frequent, I might be about the only one unlucky to have some older / strange version of `git`.

**Comment by csells** [comment]
Then I'll close and if someone has this same issue again, they can re-open.
