### ISSUE TITLE
Linux app zoom error on TextField and Switch button

### ISSUE THREAD

**Issue by SerdarYildiz06** [flutter/flutter#148755]
### Steps to reproduce

I am using the latest version of Flutter, 3.22.0. In the Flutter Linux application, it zooms ridiculously when you hover over the text fields and switch buttons. I did not have such a problem in previous versions.

### Expected results

Since there is no zoom in the components I hover over,

### Actual results

When I hover over the relevant component, it zooms and focuses, I cannot turn off the zoom.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

https://github.com/flutter/flutter/assets/72278145/836edd39-3466-467f-9f5b-2a9215a22b75

For the detail video send me email to serdaryildizdev@gmail.com

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.0)
    • VS Code at /Users/serdaryildiz/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 124.0.6367.208
    ! Error: Browsing on the local area network for Serdar iPhone’u. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
serdaryildiz@Serdars-MBP .pub-cache % clear

serdaryildiz@Serdars-MBP .pub-cache % flutter doctor -v
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-TR)
    • Flutter version 3.22.0 on channel stable at /Users/serdaryildiz/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (12 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/serdaryildiz/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.0)
    • VS Code at /Users/serdaryildiz/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 124.0.6367.208
    ! Error: Browsing on the local area network for Serdar iPhone’u. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by SerdarYildiz06** [comment]
I made useMaterial3 to false it fixed my problem. My theme config like was that.
<img width="559" alt="Screenshot 2024-05-21 at 14 52 34" src="https://github.com/flutter/flutter/assets/72278145/cb1f453f-2bd4-49cf-a54c-bdd07d86fa84">

**Comment by huycozy** [comment]
From your demo, looks like it's a production app. I would suggest you narrow the issue down by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a minimal sample code that can produce the issue. And please share it here when you have such an example. Thanks!

**Comment by SerdarYildiz06** [comment]
I removed relative package error still same it continue
<img width="662" alt="Screenshot 2024-05-21 at 15 51 37" src="https://github.com/flutter/flutter/assets/72278145/3acbf90f-24c7-4280-98bb-426c81d484fc">

**Comment by LimaneGaya** [comment]
@SerdarYildiz06 Could you please provide a sample code that reproduce the issue like: 
```dart 
import 'package:flutter/material.dart';

void main() => runApp(const MainApp());


class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        //Your Code,
      ),
    );
  }
}
```
Also it's easier to test if you copy past your code instead of screenshot, thank you.

**Comment by huycozy** [comment]
@SerdarYildiz06 Please help to provide a minimal sample code in a code block as @LimaneGaya suggested instead of a screenshot ([Creating and highlighting code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)). And also try to strip out implementation code which is not related to reproduce the issue. Thanks!

**Comment by SerdarYildiz06** [comment]
`import 'package:fernuszkitapx/app/logic/settings_logic.dart';
import 'package:fernuszkitapx/kxk/common/app_scroll_behavior.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:get_it_mixin/get_it_mixin.dart';
import 'package:fernuszkitapx/main.dart';

class AppScaffold extends StatelessWidget with GetItMixin {
  AppScaffold({Key? key, required this.child}) : super(key: key);
  final Widget? child;

  @override
  Widget build(BuildContext context) {
    Animate.defaultDuration = stylesLogic.times.fast;
    final customCardTheme = CardTheme(
      color: Colors.blue, // Set the background color of the card
      elevation: 4, // Set the elevation (shadow) of the card
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10), // Set the border radius
        side: BorderSide(
          color: Colors.red, // Set the border color
          width: 1.0, // Set the border width
        ),
      ),
    );

    return ValueListenableBuilder<String?>(
      valueListenable: settingsLogic.currentThemeMode,
      builder: (_, mode, __) {
        return Stack(
          children: [
            Theme(
              data:
                  settingsLogic.currentThemeMode.value == SettingThemeMode.light
                      ? ThemeData(
                          colorScheme: stylesLogic.colors.lightScheme,
                          brightness: Brightness.light,
                          useMaterial3: true,
                          visualDensity: VisualDensity.standard,
                          platform: defaultTargetPlatform)
                      : ThemeData(
                          colorScheme: stylesLogic.colors.darkScheme,
                          brightness: Brightness.dark,
                          useMaterial3: true,
                          visualDensity: VisualDensity.standard,
                          platform: defaultTargetPlatform),

              // Provide a default texts style to allow Hero's to render text properly
              child: DefaultTextStyle(
                // Use a custom scroll behavior across entire app
                style: const TextStyle(),
                child: ScrollConfiguration(
                  behavior: AppScrollBehavior(),
                  child: child!,
                ),
              ),
            ),
          ],
        );
      },
    );
  }
}
`
`
import 'package:fernuszkitapx/kxk/common/platform_info.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

/// Add mouse drag on desktop for easier responsive testing
class AppScrollBehavior extends ScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices {
    return Set.from(super.dragDevices)..add(PointerDeviceKind.mouse);
  }

  @override
  ScrollPhysics getScrollPhysics(BuildContext context) => const BouncingScrollPhysics();

  @override
  Widget buildScrollbar(BuildContext context, Widget child, ScrollableDetails details) {
    return RawScrollbar(
        thickness: 8,
        radius: const Radius.circular(4),
        thumbColor: Colors.grey,
        controller: details.controller,
        thumbVisibility: PlatformInfo.isDesktop,
        child: child
    );
  }
}
`

**Comment by SerdarYildiz06** [comment]
`class AppScaffold extends StatelessWidget with GetItMixin {
  AppScaffold({Key? key, required this.child}) : super(key: key);
  final Widget? child;

  @override
  Widget build(BuildContext context) {
    Animate.defaultDuration = stylesLogic.times.fast;
    final customCardTheme = CardTheme(
      color: Colors.blue, // Set the background color of the card
      elevation: 4, // Set the elevation (shadow) of the card
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10), // Set the border radius
        side: BorderSide(
          color: Colors.red, // Set the border color
          width: 1.0, // Set the border width
        ),
      ),
    );

    return ValueListenableBuilder<String?>(
      valueListenable: settingsLogic.currentThemeMode,
      builder: (_, mode, __) {
        return Stack(
          children: [
            Theme(
              data:
                  settingsLogic.currentThemeMode.value == SettingThemeMode.light
                      ? ThemeData(
                          colorScheme: stylesLogic.colors.lightScheme,
                          brightness: Brightness.light,
                          useMaterial3: true,
                          visualDensity: VisualDensity.standard,
                          platform: defaultTargetPlatform)
                      : ThemeData(
                          colorScheme: stylesLogic.colors.darkScheme,
                          brightness: Brightness.dark,
                          useMaterial3: true,
                          visualDensity: VisualDensity.standard,
                          platform: defaultTargetPlatform),

              // Provide a default texts style to allow Hero's to render text properly
              child: DefaultTextStyle(
                // Use a custom scroll behavior across entire app
                style: const TextStyle(),
                child: ScrollConfiguration(
                  behavior: AppScrollBehavior(),
                  child: child!,
                ),
              ),
            ),
          ],
        );
      },
    );
  }
}
`
`class AppScrollBehavior extends ScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices {
    return Set.from(super.dragDevices)..add(PointerDeviceKind.mouse);
  }

  @override
  ScrollPhysics getScrollPhysics(BuildContext context) => const BouncingScrollPhysics();

  @override
  Widget buildScrollbar(BuildContext context, Widget child, ScrollableDetails details) {
    return RawScrollbar(
        thickness: 8,
        radius: const Radius.circular(4),
        thumbColor: Colors.grey,
        controller: details.controller,
        thumbVisibility: PlatformInfo.isDesktop,
        child: child
    );
  }
}
`

**Comment by SerdarYildiz06** [comment]
```
  class AppScaffold extends StatelessWidget with GetItMixin {
  AppScaffold({Key? key, required this.child}) : super(key: key);
  final Widget? child;

  @override
  Widget build(BuildContext context) {
    Animate.defaultDuration = stylesLogic.times.fast;
    final customCardTheme = CardTheme(
      color: Colors.blue, // Set the background color of the card
      elevation: 4, // Set the elevation (shadow) of the card
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10), // Set the border radius
        side: BorderSide(
          color: Colors.red, // Set the border color
          width: 1.0, // Set the border width
        ),
      ),
    );

    return ValueListenableBuilder<String?>(
      valueListenable: settingsLogic.currentThemeMode,
      builder: (_, mode, __) {
        return Stack(
          children: [
            Theme(
              data:
                  settingsLogic.currentThemeMode.value == SettingThemeMode.light
                      ? ThemeData(
                          colorScheme: stylesLogic.colors.lightScheme,
                          brightness: Brightness.light,
                          useMaterial3: true,
                          visualDensity: VisualDensity.standard,
                          platform: defaultTargetPlatform)
                      : ThemeData(
                          colorScheme: stylesLogic.colors.darkScheme,
                          brightness: Brightness.dark,
                          useMaterial3: true,
                          visualDensity: VisualDensity.standard,
                          platform: defaultTargetPlatform),

              // Provide a default texts style to allow Hero's to render text properly
              child: DefaultTextStyle(
                // Use a custom scroll behavior across entire app
                style: const TextStyle(),
                child: ScrollConfiguration(
                  behavior: AppScrollBehavior(),
                  child: child!,
                ),
              ),
            ),
          ],
        );
      },
    );
  }
}

```
```
class AppScrollBehavior extends ScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices {
    return Set.from(super.dragDevices)..add(PointerDeviceKind.mouse);
  }

  @override
  ScrollPhysics getScrollPhysics(BuildContext context) => const BouncingScrollPhysics();

  @override
  Widget buildScrollbar(BuildContext context, Widget child, ScrollableDetails details) {
    return RawScrollbar(
        thickness: 8,
        radius: const Radius.circular(4),
        thumbColor: Colors.grey,
        controller: details.controller,
        thumbVisibility: PlatformInfo.isDesktop,
        child: child
    );
  }
}
```

**Comment by huycozy** [comment]
@SerdarYildiz06 Your snippet code above is an incomplete example and uses 3rd package. Please look at [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
