### ISSUE TITLE
I would like clarification on material 3 support in flutter

### ISSUE THREAD

**Issue by EmmanuelGbafore** [flutter/flutter#148706]
### Clarification Needed on `Material3` Support in Flutter

**Description:**
Hello Flutter team,

I hope you are fine. I am doing a project where I want to implement the new `Material3` design system using Flutter. I have read through the documentation and the recent release notes, but I am still unclear on a few points regarding `Material3` support:

1. **How to properly enable `Material3` in a Flutter app**: Are there specific configurations or settings required to switch to `Material3`?
2. **Compatibility with existing `Material` widgets**: Will existing `Material` widgets automatically adopt the new `Material3` styles, or are there new widgets specifically designed for `Material3`?
3. **Performance implications**: Are there any known performance implications or best practices when using `Material3`?

**Context:**
Here is the context of what I am trying to achieve:
- I am developing a new app and would like to ensure it follows the latest design guidelines provided by Material3.
- Below is a sample code snippet where I attempt to enable Material3:
  ```dart
  import 'package:flutter/material.dart';

  void main() {
    runApp(MyApp());
  }

  class MyApp extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
      return MaterialApp(
        theme: ThemeData(
          useMaterial3: true, // Enabling Material3
        ),
        home: Scaffold(
          appBar: AppBar(
            title: Text('Material3 App'),
          ),
          body: Center(
            child: Text('Hello, Material3!'),
          ),
        ),
      );
    }
  }

Additional Information:

Flutter Version: 3.3.10
Platform: Android
Any clarification or guidance on these points would be greatly appreciated. Thank you for your time and assistance.

Best regards,
Emmanuel Gbafore

**Comment by MominRaza** [comment]
> 1. **How to properly enable `Material3` in a Flutter app**: Are there specific configurations or settings required to switch to `Material3`?

No extra configurations required, Material3 is enabled by default in flutter 3.16 and above.

> 2\. **Compatibility with existing `Material` widgets**: Will existing `Material` widgets automatically adopt the new `Material3` styles, or are there new widgets specifically designed for `Material3`?

Most of the existing widget will adopt automatically except `BottomNavigationBar` which is replaced by `NavigationBar`.

> 3\. **Performance implications**: Are there any known performance implications or best practices when using `Material3`?

No

**Comment by EmmanuelGbafore** [comment]
Thanks a lot for those clarifications.

**Comment by cedvdb** [comment]
You can close the issue

**Comment by danagbemava-nc** [comment]
Closing this since it appears to be resolved.
