### ISSUE TITLE
Errors loading assets with spaces in their names

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#14870]
If I have spaces in my asset filenames, they fail to load at runtime (works fine without the spaces):

<img width="1084" alt="screen shot 2018-02-25 at 11 55 10" src="https://user-images.githubusercontent.com/1078012/36641152-e479c43e-1a22-11e8-9e33-40f555cb763b.png">

Asset can be seen in the tree on the left, pubspec in the top pane and the error in the bottom pane.

**Comment by tvolkert** [comment]
Deferring to @szakarias

**Comment by DanTup** [comment]
Thanks, fix works fine!
