### ISSUE TITLE
Feature Request : Ability to set default value in shared_preferences 

### ISSUE THREAD

**Issue by Purus** [flutter/flutter#14872]
This is not an Issue. This is a feature request.

In the shared_preferences plugin, it would be good to have the feature to set default value if the value is not found in storage. This could be useful for keys which are created at run time.

For Example:

`prefs.getBool("has-seen-welcome" , false)`

**Comment by gabrc52** [comment]
You could use `prefs.getBool(“has-seen-welcome”) ?? false`

**Comment by Purus** [comment]
Great. Thanks for the tip.
