### ISSUE TITLE
Flutter should log errors in vkCreateInstance

### ISSUE THREAD

**Issue by jbauman42** [flutter/flutter#148707]
### Use case

As a Fuchsia developer, it's useful to get Vulkan loader error logs when vkCreateInstance fails. Currently no logging options are enabled for the Vulkan Loader, so all logs from the loader are dropped.

### Proposal

The call to vkCreateInstance should chain a VkDebugReportCallbackCreateInfoEXT struct. This would allow flutter to capture all the debug logs from the loader. If vkCreateInstance returned an error, these logs could be logged by the engine. This would give us information to debug failures, but would prevent cluttering the log on success.

**Comment by huycozy** [comment]
This issue looks similar to your old issue at https://github.com/flutter/flutter/issues/82928, can you take a look again on it and confirm?
