### ISSUE TITLE
[Impeller][regression] image.toByteData fails to convert raster image to PNG.

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#148851]
### Steps to reproduce

Run full sample code below.

Basically, when trying to take a widget screenshot with usual snippet, the `image.toByteData` fails. Issue occurs on iOS Impeller. No issue on iOS skia and on android. It is a regression coz we use this code inside our app and it has always worked since lately.
```
   final boundary = screenshotKey.currentContext?.findRenderObject() as RenderRepaintBoundary;
   var image = await boundary.toImage(pixelRatio: 3);
   var byteData = await image.toByteData(format: ImageByteFormat.png);
```

### Expected results

No error.

### Actual results

[ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
  super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      showPerformanceOverlay: true,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),

    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  final screenshotKey = GlobalKey();

  Future<Uint8List> takeScreenshot({
    int width = 350,
    int height = 350
  }) async {
    // Wait a bit so the tree is mounted
    await Future.delayed(const Duration(milliseconds: 20), () {});
    final boundary = screenshotKey.currentContext?.findRenderObject() as RenderRepaintBoundary;
    var image = await boundary.toImage(pixelRatio: 3);
    print('DBUG: image.toByteData fails on iOS');
    var byteData = await image.toByteData(format: ImageByteFormat.png);
    print('DBUG: This log is never printed on iOS');
    Uint8List pngBytes = byteData!.buffer.asUint8List();
    return pngBytes;
  }

  @override
  Widget build(BuildContext context) {
    takeScreenshot();
    return MaterialApp(
      title: 'Impeller Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Impeller Demo'),
        ),
        body: Center(
            child: RepaintBoundary(
              key: screenshotKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Expanded(
                      child: Container(
                          color: Colors.black45
                    )
                 ),
              ],
            ),
          ),
        )
      ),
    );
  }
}









```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.22.0-42.0.pre.6, on macOS 14.2.1 23C71 darwin-arm64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)

```

</details>

**Comment by delfme** [comment]
@darshankawar I can't say. It might have been passed a few months since last time we checked that code, coz it belong to just one screen of our app. But we know for sure that we tested it on master and was working time ago. 

Is there any other code to achieve the same result that we can use as a temporary workaround?

**Comment by darshankawar** [comment]
Thanks for the update, but I can't seem to replicate the reported error you mentioned, so I am not clear as what exactly is the workaround you are looking for. I also see blank screen upon running the code. Can you provide us a screenshot of what it rendered on screen when the code worked as compared to latest behavior ?

**Comment by delfme** [comment]
@darshankawar this is the log you should see when no bug.
print('DBUG: This log is never printed on iOS');
The first print is just to explain what is the line that causes the bug.
So basically we have 2 logs, one before and one after  
`var byteData = await image.toByteData(format: ImageByteFormat.png);`
If second log is not printed, it means that image.toByteData fails.


Here is a new sample  code which uses only one log, if log doesn't print it means image.toByteData fails.
It works on iOS Skia and android, it fails on iOS Impeller.

```
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
  super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      showPerformanceOverlay: true,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),

    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  final screenshotKey = GlobalKey();

  Future<Uint8List> takeScreenshot({
    int width = 350,
    int height = 350
  }) async {
    // Wait a bit so the tree is mounted
    await Future.delayed(const Duration(milliseconds: 20), () {});
    final boundary = screenshotKey.currentContext?.findRenderObject() as RenderRepaintBoundary;
    var image = await boundary.toImage(pixelRatio: 3);
    // NOTE: image.toByteData fails on iOS Impeller and works on iOS skia and android.
    var byteData = await image.toByteData(format: ImageByteFormat.png);
    print('DBUG: This log is never printed on iOS');
    Uint8List pngBytes = byteData!.buffer.asUint8List();
    return pngBytes;
  }

  @override
  Widget build(BuildContext context) {
    takeScreenshot();
    return MaterialApp(
      title: 'Impeller Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Impeller Demo'),
        ),
        body: Center(
            child: RepaintBoundary(
              key: screenshotKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Expanded(
                      child: Container(
                          color: Colors.black45
                    )
                 ),
              ],
            ),
          ),
        )
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
Thanks for the details. I tried the same using latest stable 3.22.1 with and without Impeller and I get following for both:

```
3.22.1 : impeller : flutter: DBUG: This log is never printed on iOS

3.22.1 : skia : 2024-05-24 11:14:20.795744+0530 Runner[2620:67385] flutter: DBUG: This log is never printed on iOS
```

If I understand your description correctly, since the log is printing, indicating the `image.toByteData` is working ?

**Comment by delfme** [comment]
Yes. So we are correct saying this is a regression. If you try with Impeller using master you won't see the log, which means a failure on `image.toByteData` . I can't say when Impeller stopped to work on this.

**Comment by karanSman** [comment]
did you find any way to resolve this  i want to take screenshot of image in png format
 DrawableRoot svgDrawableRoot =
            await svg.fromSvgString(feed.svgContent!, 'key');
        // Parse the SVG file as XML
        XmlDocument document = XmlDocument.parse(feed.svgContent!);

        // Getting size of SVG
        final svgElement = document.findElements('svg').first;
        final svgWidth = double.parse(svgElement.getAttribute('width')!);
        final svgHeight = double.parse(svgElement.getAttribute('height')!);
        // toPicture() and toImage() don't seem to be pixel ratio aware, so we calculate the actual sizes here
        double devicePixelRatio = MediaQuery.of(Get.context!).devicePixelRatio;

        double width = svgHeight * devicePixelRatio;
        double height = svgWidth * devicePixelRatio;

        // Convert to ui.Picture
        final picture = svgDrawableRoot.toPicture(size: Size(width, height));

        // Convert to ui.Image. toImage() takes width and height as parameters
        // you need to find the best size to suit your needs and take into account the screen DPI
        final image = await picture.toImage(width.toInt(), height.toInt());
        ByteData? bytes = await image.toByteData(format: ImageByteFormat.png);
        this is my code if you guys have any idea plz suggest it is not working on ios getting error
        
        ###  **Could not convert raster image to PNG.**

**Comment by delfme** [comment]
@karanSman nope, but it is a regression. It works on stable 3.22.1, issue occurs on master only.
@darshankawar can we have someone look at it? We cannot use latest stable at moment. A fix might not require much time.

**Comment by karanSman** [comment]
it is causing issues to svg also my svgs are not rendered completely some elements are not visible,..
 previously it was working..

**Comment by delfme** [comment]
@darshankawar I confirm we have no issue on channel stable. Just tried. It is a regression on channel master, Impeller iOS only.

**Comment by darshankawar** [comment]
@delfme Thanks for the update and your patience while we try to figure this out.

On latest master with and without Impeller, I get below which seems to be same log:

```
master : impeller : 2024-05-27 11:20:39.843232+0530 Runner[4197:48600] flutter: DBUG: This log is never printed on iOS Impeller master channel, which means image.toByteData failure



master : w/o impeller : 

2024-05-27 11:21:33.986829+0530 Runner[4456:50583] flutter: DBUG: This log is never printed on iOS Impeller master channel, which means image.toByteData failure
```

I ran this on `Channel master, 3.23.0-8.0.pre.8`

**Comment by delfme** [comment]
@darshankawar I tested again today and bug is still there on master 3.23.0-9.0.pre.3
Flutter (Channel master, 3.23.0-9.0.pre.3)

flutter: DBUG: image.toByteData fails on iOS
[ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.

**Comment by delfme** [comment]
Tested on iphone 13 pro  iOS 17.4.1

**Comment by darshankawar** [comment]
> [ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.

I do not get this error upon running in iOS 15.3 simulator with latest master. I get below:

`2024-05-29 12:00:58.457589+0530 Runner[6010:51491] flutter: DBUG: This log is never printed on iOS Impeller master channel, which means image.toByteData failure`


Based on the report, I'll keep the issue open for team's input / tracking.

**Comment by delfme** [comment]
Tested on iphone 13 pro iOS 17.4.1 on real device. Dont know if it works on emulator or older ios versions.

**Comment by Schefferbird** [comment]
I still got this on Flutter 3.23.0-12.0.pre on iOS 14 Pro real device (17.4.1)

**Comment by jonahwilliams** [comment]
@gaaclarke we seem to be missing encoding logic for the BGRX format. I thought you wired that up in Skia?

**Comment by gaaclarke** [comment]
> @gaaclarke we seem to be missing encoding logic for the BGRX format. I thought you wired that up in Skia?

I did, it happened as part of https://github.com/flutter/flutter/issues/145933.  The Skia CL is at https://skia-review.googlesource.com/c/skia/+/836617.  The integration test that was blocked by that CL is at https://github.com/flutter/flutter/pull/126715/files

We'll have to run it through the debugger but it might be running through a different skia path than the one we tested.

**Comment by jonahwilliams** [comment]
in src/encode/SkPngEncoderImpl.cpp, it looks like the format returns nullptr from the encoder?

**Comment by gaaclarke** [comment]
Ahh yea, PNG being a different flow rings a bell.  With BGR10_XR I had to come back and do PNG support in a different PR too: https://github.com/google/skia/commit/b9d709e63e7fcd837f694299c9fd05ed5f747f58

**Comment by gaaclarke** [comment]
The fix is coming, in the meantime the workaround is to remove wide gamut from the image before encoding it to a PNG.  It's outlined here: https://github.com/flutter/flutter/issues/133942#issuecomment-1708894579

**Comment by zhangwen0510** [comment]
Great, I encountered this problem a few days ago, waiting for a fix

**Comment by adampei** [comment]
I encountered this issue too, today

**Comment by zhangwen0510** [comment]
https://github.com/flutter/flutter/issues/149946 What is causing this error？

**Comment by ZhangLiuCheng** [comment]
RenderRepaintBoundary? boundary = globalKey.currentContext?.findRenderObject() as RenderRepaintBoundary;
  ui.Image image = await boundary.toImage(pixelRatio: 2);
  ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);

The generated image still has issues.

![WechatIMG3046](https://github.com/flutter/flutter/assets/6800810/d3ca0d06-ee86-466b-9979-81f2d6263bf6)

Flutter (Channel master, 3.23.0-13.0.pre.189, on macOS 14.4 23E214 darwin-arm64 (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.23.0-13.0.pre.189 on channel master at /Users/zhangliucheng/Documents/software/flutter-stable-arm64
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 14df7be3f9 (15 hours ago), 2024-06-11 11:14:54 -0400
    • Engine revision 1cdbebee19
    • Dart version 3.5.0 (build 3.5.0-236.0.dev)
    • DevTools version 2.36.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
