### ISSUE TITLE
Hovering stylus

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#148810]
### Use case

Hovering with a stylus should produce the same visual effect as hovering with a mouse. The gif below shows what hovering some buttons looks like on native Android. By hovering I mean not actually making contact with the screen.

![stylus_hover](https://github.com/flutter/flutter/assets/389558/88e5a715-7439-49c3-a839-adf894f5c28f)

### Proposal

Flutter should also show hover effects for a hovering stylus.

The code that handles this for most Material widgets is here [in ink_well.dart](https://github.com/flutter/flutter/blob/357bd6574971af634066d9ff9c1fc1320edf71f7/packages/flutter/lib/src/material/ink_well.dart#L1321-L1322). However, MouseRegion seems to not call onEnter or onExit for a hovering stylus, though it does call onHover, interestingly!

If MouseRegion called onEnter and onExit for stylus input, then this issue would be solved. @dkwingsmt Do you know why this is, or if there is another way to listen for a hovering stylus's exit? I saw a related comment from you: https://github.com/flutter/flutter/issues/36085#issuecomment-514730261

If that can't be solved, then we could work around it. We could use onHover and a timeout, for example. Or maybe we could use PointerRouter, as suggested [on StackOverflow](https://stackoverflow.com/questions/63024698/can-flutter-detect-a-hovering-stylus).

<details>

<summary>Repro app showing only onHover works</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Demo'),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 74.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              // Works for hover, not for enter/exit.
              Listener(
                onPointerHover: (PointerHoverEvent event) {
                  print('justin Listener onPointerHover ${event.kind}');
                },
                child: Container(width: 100, height: 100, color: Colors.red),
              ),
              // Also works for hover but not for enter/exit.
              MouseRegion(
                onEnter: (PointerEnterEvent event) {
                  print('justin MouseRegion onEnter ${event.kind}');
                },
                onExit: (PointerExitEvent event) {
                  print('justin MouseRegion oneEit ${event.kind}');
                },
                onHover: (PointerHoverEvent event) {
                  print('justin MouseRegion hover ${event.kind}');
                },
                child: Container(width: 100, height: 100, color: Colors.blue),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by dkwingsmt** [comment]
I think it's simply oversight, since we did not consider stylus hovering when designing enter/leave events. Can you think of any reasons we should not treat stylus hovers the same as mouse hovers in all cases?

**Comment by justinmc** [comment]
I can't, let's do it? https://github.com/flutter/flutter/pull/149006
