### ISSUE TITLE
[video_player] Video is not visible - but sound works

### ISSUE THREAD

**Issue by jakobr-google** [flutter/flutter#14880]
_From @CrazyStaff on February 24, 2018 18:25_

URL: https://pub.dartlang.org/packages/video_player

I have the issue that the video is not visible. However i can hear the sound.
Perhaps the height is zero? This video is running and also visible on my smartphone HTC 10, 
but when I use the android simulator with different sizes it doesnt work - only the sound is working.
I tested the simulator with different Android SDK 7.0 and less.

**Here is the log file** 
I dont know what the info warning means. 
```
D/NetworkSecurityConfig( 9393): No Network Security Config specified, using platform default
D/MediaPlayer( 9393): setSubtitleAnchor in MediaPlayer
D/MediaPlayer( 9393): setSubtitleAnchor in MediaPlayer
I/flutter ( 9393): height: 360.0 ## own test about height of video
I/flutter ( 9393): height: 360.0 ## own test about height of video
W/MediaPlayer( 9393): **info/warning (703, 0)**
W/MediaPlayer( 9393): info/warning (701, 0)
W/MediaPlayer( 9393): info/warning (703, 0)
W/MediaPlayer( 9393): info/warning (702, 0)
W/MediaPlayer( 9393): info/warning (703, 0)
W/MediaPlayer( 9393): info/warning (701, 0)
D/        ( 9393): HostConnection::get() New Host Connection established 0x8c770f00, tid 9487
W/MediaPlayer( 9393): info/warning (703, 0)
W/MediaPlayer( 9393): info/warning (702, 0)
```
_Copied from original issue: dart-lang/pub-dartlang-dart#1022_

**Comment by jakobr-google** [comment]
This repo is for the pub site itself. Please file issues with packages on the package's repo - in this case, flutter/plugins. I'll move this one.

**Comment by fuzzybinary** [comment]
I'm actually getting the same issue on the iOS simulator. I pulled down the video player because I'm developing a plugin that uses the TextureRegistry and it appears copyPixelBuffer is never getting called even when a frame is available.

Flutter doctor:

> Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision b397406561 (4 weeks ago) • 2018-04-19 23:36:15 -0700
> Engine • revision 09d05a3891
> Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357
> 
> Running flutter doctor...
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E202, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
> [✓] Android Studio (version 3.0)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] IntelliJ IDEA Community Edition (version 2017.2.3)
> [✓] VS Code (version 1.22.2)
> [✓] Connected devices (1 available)

**Comment by FaisalAbid** [comment]
I think this is a limitation of the simulator

**Comment by lucyhoang** [comment]
Oh, I tested on Android simulator, the video is visible, but the sound doesn't work. Do you have any idea?

**Comment by jagadish906** [comment]
I have problem with video but sound is working and video is not displaying

**Comment by Jorgezz** [comment]
> I have problem with video but sound is working and video is not displaying
The same issue, as my app 's player inherited from ijkplayer, I have set a series settings like : 
    player.shouldDisplayInternal = NO;
when player plays, I set 'player.videoDataBlock = ^(CVPixelBufferRef pixelBuffer, int rotation) ', and make textureFrameAvailable excute in main thread, and in function: (CVPixelBufferRef)copyPixelBuffer, I logged pixcel buffer address is ok, but there is no any video graph displayed.

**Comment by cbracken** [comment]
Closing this issue. For issues with video/sound in the emulator, see #14647.

If you're having issues where you're getting sound but no video on physical devices, we'd appreciate someone to file a new bug with a reduced repro that will allow us to diagnose what's going on. If you do, it would be fantastic to link back to this issue to help with background and to lead others to the new bug.

 As-is, we don't have enough information to fix this bug so we are reluctantly closing this.

**Comment by duranapdan** [comment]
**
@cbracken I have the same problem samsung J5 prime phone android 6
I would appreciate if you help.
Is the problem in the plugin?
  video_player: ^ 0.10.11 + 2
  camera: ^ 0.5.7 + 3
  path_provider: ^ 1.6.11

**


class VideoOynaticiPage extends StatefulWidget {
  final String videoPath;
  const VideoOynaticiPage({Key key, this.videoPath}) : super(key: key);

  @override
  _VideoOynaticiPageState createState() => _VideoOynaticiPageState(videoPath);
}

class _VideoOynaticiPageState extends State<VideoOynaticiPage> {
  String videoPath;
  VoidCallback listener;
  VideoPlayerController playerController;
  _VideoOynaticiPageState(this.videoPath);

  @override
  @override
  void initState() {
    super.initState();
    playVideo();
  }

  void playVideo() {
    if (playerController == null) {
      playerController = VideoPlayerController.file(File(videoPath))
        ..addListener(listener)
        ..setLooping(true)
        ..initialize()
        ..play();
    } else {
      if (playerController.value.isPlaying) {
        playerController.pause();
      } else {
        playerController.initialize();
        playerController.play();
      }
    }
  }

  @override
  void deactivate() {
    if (playerController != null) {
      playerController.setVolume(0.0);
      playerController.removeListener(listener);
    }
    super.deactivate();
  }

  @override
  void dispose() {
    if (playerController != null) playerController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        fit: StackFit.expand,
        children: <Widget>[
          Positioned.fill(
            left: 10,
            right: 10,
            child: Container(
              child: (playerController != null
                  ? VideoPlayer(
                      playerController,
                    )
                  : Container()),
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          /*
          Navigator.of(context, rootNavigator: true).push(
            MaterialPageRoute(
              builder: (context) => VideoSettingsPage(
                videoPath: videoPath,
              ),
            ),
          );*/
        },
        child: Icon(
          Icons.done,
          size: 20,
        ),
        backgroundColor: Colors.blue,
      ),
    );
  }
}

**Comment by duranapdan** [comment]
> Bu sorun kapatılıyor. Emülatördeki video / ses ile ilgili sorunlar için, bkz. [# 14647](https://github.com/flutter/flutter/issues/14647) .
> 
> Ses aldığınız yerlerde sorun yaşıyorsanız, ancak fiziksel cihazlarda video yoksa, neler olup bittiğini teşhis etmemizi sağlayacak, sınırlı bir repro ile yeni bir hata bildirmesi için birini takdir ediyoruz. Bunu yaparsanız, arka plana yardımcı olmak ve diğerlerini yeni hataya yönlendirmek için bu konuya geri dönmek harika olurdu.
> 
> Olduğu gibi, bu hatayı düzeltmek için yeterli bilgimiz yok, bu yüzden bunu isteksizce kapatıyoruz.

**Comment by duranapdan** [comment]
> Bu sorun kapatılıyor. Emülatördeki video / ses ile ilgili sorunlar için, bkz. [# 14647](https://github.com/flutter/flutter/issues/14647) .
> 
> Ses aldığınız yerlerde sorun yaşıyorsanız, ancak fiziksel cihazlarda video yoksa, neler olup bittiğini teşhis etmemizi sağlayacak, sınırlı bir repro ile yeni bir hata bildirmesi için birini takdir ediyoruz. Bunu yaparsanız, arka plana yardımcı olmak ve diğerlerini yeni hataya yönlendirmek için bu konuya geri dönmek harika olurdu.
> 
> Olduğu gibi, bu hatayı düzeltmek için yeterli bilgimiz yok, bu yüzden bunu isteksizce kapatıyoruz.

@cbracken I have the same problem samsung J5 prime phone android 6
Can't you find a plan for this, urgent ???

video_player: ^ 0.10.11 + 2
camera: ^ 0.5.7 + 3
path_provider: ^ 1.6.11

**

class VideoOynaticiPage extends StatefulWidget {
final String videoPath;
const VideoOynaticiPage({Key key, this.videoPath}) : super(key: key);

@override
_VideoOynaticiPageState createState() => _VideoOynaticiPageState(videoPath);
}

class _VideoOynaticiPageState extends State {
String videoPath;
VoidCallback listener;
VideoPlayerController playerController;
_VideoOynaticiPageState(this.videoPath);

@override
@override
void initState() {
super.initState();
playVideo();
}

void playVideo() {
if (playerController == null) {
playerController = VideoPlayerController.file(File(videoPath))
..addListener(listener)
..setLooping(true)
..initialize()
..play();
} else {
if (playerController.value.isPlaying) {
playerController.pause();
} else {
playerController.initialize();
playerController.play();
}
}
}

@override
void deactivate() {
if (playerController != null) {
playerController.setVolume(0.0);
playerController.removeListener(listener);
}
super.deactivate();
}

@override
void dispose() {
if (playerController != null) playerController.dispose();
super.dispose();
}

@override
Widget build(BuildContext context) {
return Scaffold(
body: Stack(
fit: StackFit.expand,
children: [
Positioned.fill(
left: 10,
right: 10,
child: Container(
child: (playerController != null
? VideoPlayer(
playerController,
)
: Container()),
),
),
],
),
floatingActionButton: FloatingActionButton(
onPressed: () {
/*
Navigator.of(context, rootNavigator: true).push(
MaterialPageRoute(
builder: (context) => VideoSettingsPage(
videoPath: videoPath,
),
),
);*/
},
child: Icon(
Icons.done,
size: 20,
),
backgroundColor: Colors.blue,
),
);
}
}

**Comment by cbracken** [comment]
Hi @duranapdan -- since this issue is closed (see the [note](https://github.com/flutter/flutter/issues/14880#issuecomment-573244500) above), would you mind filing a [new issue](https://github.com/flutter/flutter/issues/new/choose) that describes your case, including repro instructions? This will help us better identify the bug you're hitting and track the solution. Please link back to this bug from the new bug to help others better locate the issue affecting them.

**Comment by MAXIMIVANCHUKMOBYRIX** [comment]
> Closing this issue. For issues with video/sound in the emulator, see #14647.
> 
> If you're having issues where you're getting sound but no video on physical devices, we'd appreciate someone to file a new bug with a reduced repro that will allow us to diagnose what's going on. If you do, it would be fantastic to link back to this issue to help with background and to lead others to the new bug.
> 
> As-is, we don't have enough information to fix this bug so we are reluctantly closing this.



> Closing this issue. For issues with video/sound in the emulator, see #14647.
> 
> If you're having issues where you're getting sound but no video on physical devices, we'd appreciate someone to file a new bug with a reduced repro that will allow us to diagnose what's going on. If you do, it would be fantastic to link back to this issue to help with background and to lead others to the new bug.
> 
> As-is, we don't have enough information to fix this bug so we are reluctantly closing this.

Hi, this bug is appeared again. In my app i have video feed, which used VideoPlayerController.network(link). Bug appear, when i fast scroll and sound is playing, but video not showing. Video length less than 15 seconds.
Get this error 

[ServicesDaemonManager] interruptionHandler is called. -[FontServicesDaemonManager connection]_block_invoke
