### ISSUE TITLE
Website should remember editor selection across pages

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#14888]
Split from https://github.com/flutter/website/pull/800, since there are multiple pages that have a tabbed interface to selector your editor, it'd be good if this persisted locally so as you moved around the site it would keep your preferred editor selected.

**Comment by mit-mit** [comment]
Thanks @DanTup, if you have ideas for how to do this (+ your idea for selecting a tab with the Uri), feel free to send PRs!

**Comment by DanTup** [comment]
I think it'd be very simple to stash the selector editor into localStorage and tweak the PR I sent that uses the url hash to fall back to localStorage if that's not set. I can update the PR and re-target it here (I previously sent it to your fork) if you want.

**Comment by mit-mit** [comment]
Yes, please

**Comment by DanTup** [comment]
I've opened https://github.com/flutter/website/pull/831 and staged at https://dantup-flutter-staging.firebaseapp.com/
