### ISSUE TITLE
Shebang line in Flutter script causes issues on macOS Monterey

### ISSUE THREAD

**Issue by masekere** [flutter/flutter#148817]
# Description
When installing and using the Flutter SDK on macOS Monterey, I encountered an issue where the shebang line in the Flutter script (#!/usr/bin/env bash) caused problems. Changing it to #!/bin/bash resolved the issue. This problem can affect users who have bash located in a different path or have env misconfigured.

# Steps to Reproduce:
1. Clone the Flutter SDK repository:
```bash
git clone https://github.com/flutter/flutter.git -b stable ~/development/flutter
```

2. Add Flutter to PATH:
```bash
export PATH="$PATH:~/development/flutter/bin"
```

3. Run `flutter doctor` or any other Flutter command.

# Expected Behavior:
The Flutter command should execute without any issues.

# Actual Behavior:
The Flutter command fails to execute, and only outputs `./flutter`.

# Workaround:
1. **Workaround 1**:Changing the shebang line in all the Flutter scripts from #!/usr/bin/env bash to #!/bin/bash resolves the issue:
```bash
sed -i '' '1s|.*|#!/bin/bash|' ~/development/flutter/bin/flutter
```

2. ***Workaround 2*: Adding `bash` to the `PATH` in the shell configuration file (~/.zshrc or ~/.bash_profile).
```bash
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/local/bin:$PATH"
```
# Suggested Solution:
Modify the shebang line in the Flutter script to ensure compatibility across different environments or provide documentation to help users resolve this issue.

# Additional Information:
- macOS Version: Monterey
- Flutter Version: 3.22.0

# Sample Installation Script:
Here's a sample script that includes the workaround for this issue:

```bash
#!/bin/bash

FLUTTER_PATH="$HOME/development/flutter"

modify_shebang() {
  if head -n 1 "$FLUTTER_PATH/bin/flutter" | grep -q "#!/usr/bin/env bash"; then
    echo "Modifying shebang line in Flutter script..."
    sed -i '' '1s|.*|#!/bin/bash|' "$FLUTTER_PATH/bin/flutter"
  fi
}

if [ -d "$FLUTTER_PATH" ]; then
  echo "Flutter SDK is already installed at $FLUTTER_PATH"
  modify_shebang
else
  echo "Cloning Flutter SDK..."
  git clone https://github.com/flutter/flutter.git -b stable "$FLUTTER_PATH"
  modify_shebang
  echo "Flutter SDK installed at $FLUTTER_PATH"
fi

SHELL_RC_FILE="$HOME/.zshrc"
if ! grep -q 'export PATH="$PATH:$HOME/development/flutter/bin"' "$SHELL_RC_FILE"; then
  echo 'export PATH="$PATH:$HOME/development/flutter/bin"' >> "$SHELL_RC_FILE"
  source "$SHELL_RC_FILE"
  echo "Flutter added to PATH in $SHELL_RC_FILE"
fi

flutter doctor

echo "Flutter installation script completed."
```

**Comment by darshankawar** [comment]
Thanks for the report @masekere 
I am on macOS Monterey and have installed flutter by following the steps you mentioned, but didn't get any errors and able to run all flutter commands properly.


> The Flutter command fails to execute, and only outputs `./flutter`.

Do you get any error or log that we can take a look ?

**Comment by masekere** [comment]
Thanks for the response.

I did not get any error log since the program fails by not running everything in the script. However, if `bash` is added to the environment, the script executes without failure.

I had to add `bash` to my environment by running the following command:
```bash
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/local/bin:$PATH"
```

This resolved the issue for me.

Do you have any suggestions for making this solution more permanent, or any other recommendations?

Thank you for your help!

**Comment by darshankawar** [comment]
Thanks for the feedback @masekere 
According to the documentation, `zsh` is the default shell for macOS supporting Catalina and above. Maybe check https://github.com/flutter/flutter/issues/122148 and see if it resembles your case and solving it would also resolve your issue as well.
