### ISSUE TITLE
Upgrade 1 arm64 and 1 x86 devicelab staging bots to macOS 14.5

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#148859]
### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

Upgrade the following devices to macOS 14.5

- [x] [flutter-devicelab-mac-5](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-5) (arm64)
- [x] [flutter-devicelab-mac-26](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-26) (x86)

### Additional Instructions

Also, please ensure the following after each upgrade:

Delete any directories within `/opt/flutter/xcode` if applicable.

Also verify `/opt/flutter/xcode` is owned by swarming user.

Run `DevToolsSecurity` - should get response "Developer mode is already enabled."
If you don't get the message, run `sudo /usr/sbin/DevToolsSecurity -enable` to enable.

**Comment by kentnguyen99** [comment]
Upgrading MacOS 14.5 on both mac-5 & mac-26 have been completed.  Will you check and test from your end? Thanks.

**Comment by vashworth** [comment]
I confirmed these are working.
