### ISSUE TITLE
Google Sign In iOS Error

### ISSUE THREAD

**Issue by baris-semerci** [flutter/flutter#148866]
### What package does this bug report belong to?

google_sign_in

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. Try to build app on ios simulator

### Expected results

Build successfull

### Actual results

Error: The pod "AppAuth" required by the plugin "google_sign_in_ios" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "google_sign_in_ios", or contact the plugin's developers for assistance.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Error: The pod "AppAuth" required by the plugin "google_sign_in_ios" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "google_sign_in_ios", or contact the plugin's developers for assistance.```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by LeoBlackCat** [comment]
I have the same issue when building for iOS

**Comment by baris-semerci** [comment]
> I have the same issue when building for iOS

I updated my MacOS, XCode and Cocoapods and then it disappeared.
