### ISSUE TITLE
Linux web_long_running_tests_2_5 is flaky

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#148811]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_2_5

```
Bad state: StreamSink is closed
#0      _StreamSinkImpl.add (dart:_http/http_impl.dart:912:7)
#1      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1222:11)
#2      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1785:22)
#3      VmService._call (package:vm_service/src/vm_service.dart:1787:8)
#4      VmService.streamListen (package:vm_service/src/vm_service.dart:1710:7)
#5      FlutterVmService.findExtensionIsolate (package:flutter_tools/src/vmservice.dart:982:21)
#6      FlutterResidentDevtoolsHandler._waitForExtensionsForDevice (package:flutter_tools/src/resident_devtools_handler.dart:234:38)
#7      FlutterResidentDevtoolsHandler._devicesWithExtensions (package:flutter_tools/src/resident_devtools_handler.dart:226:59)
#8      FlutterResidentDevtoolsHandler.serveAndAnnounceDevTools.callServiceExtensions (package:flutter_tools/src/resident_devtools_handler.dart:126:63)
#9      FlutterResidentDevtoolsHandler.serveAndAnnounceDevTools (package:flutter_tools/src/resident_devtools_handler.dart:140:13)
<asynchronous suspension>
```

last failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_2_5/16556/overview

**Comment by zanderso** [comment]
Moving this shard to bringup: https://github.com/flutter/flutter/pull/148854.

**Comment by loic-sharma** [comment]
This also affects shard `Linux web_long_running_tests_5_5`, 11 of the last 100 runs failed:

1. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/16874/overview
2. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/16861/overview
3. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/16853/overview
4. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/16845/overview
5. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/16835/overview

**Comment by eyebrowsoffire** [comment]
I have a potential fix out here: https://dart-review.googlesource.com/c/sdk/+/367821

**Comment by eyebrowsoffire** [comment]
This shard is no longer flaking as before. I am unmarking this as flaky in this PR: https://github.com/flutter/flutter/pull/150785

**Comment by eyebrowsoffire** [comment]
Unmarked as flaky. Closing
