### ISSUE TITLE
[codelab] Please fix a mistake, "the the".

### ISSUE THREAD

**Issue by qt-luigi** [flutter/flutter#14882]
I tried this codelab. I found a mistake, "the the".
I could not find this site source code on this GitHub repository.
Please fix from "the the" to "the".

Position: 7. Animate your app -> Specify an animation controller -> The fourth row from the bottom.
Now sentence: ... to slow down the the animation effect ... 
Fix sentence: ... to slow down the animation effect ...

**Comment by mit-mit** [comment]
I searched a bit and could not find it. The source code is here; any chance you could send a small PR. https://github.com/flutter/website

**Comment by qt-luigi** [comment]
Hello, mit-mit.
Does codelab page's source code exist in flutter/website ?
I could not find it in flutter/website, too.
If you find or know where is this page source code, Please teach me. I send PR.
I found "the the" that I read https://codelabs.developers.google.com/codelabs/flutter/index.html#6 .

**Comment by qt-luigi** [comment]
My saying "source code" is "document file". If I confused you, I apologize.

**Comment by mit-mit** [comment]
Oh, sorry. Yes, the codelabs are based on a different infrastructure so we unfortunately do not have the source for them in github.

**Comment by qt-luigi** [comment]
Thanks for adding the codelab label!

**Comment by Sfshaza** [comment]
Thanks for reporting this, @qt-luigi! The codelabs on codelabs.developer.com are published in a different location than the Flutter docs, and this is the best place to report any issues. I've fixed the text and re-published. It should go live soon!

**Comment by qt-luigi** [comment]
Thanks for fixing me, Sfshaza! I checked the fixed page. This issue is very small. mit-mit labeled it, Sfshaza fixed it. Thank you both!
