### ISSUE TITLE
SDK for iOS v9.0.0 no longer supports the OpenGL renderer and the setMetalRendererEnabled

### ISSUE THREAD

**Issue by dinalmmf** [flutter/flutter#148821]
### Use case

**Google has sent a email for this issue, below is the email:**

Hello Google Maps Platform Customer,

Following Apple’s discontinuation of OpenGL support with [iOS 12 in 2018](https://notifications.google.com/g/p/ANiao5pSpCRCagNHYrOs7W999rY8wnUbupiACT0eC6j9ADpDR9KCZ6eh_PrXyQO4PJOGJRv8OTnj5a5Hxnxm__7DY7Nb3cR4JgMnYJW6i7dNiL50_RcvhSvcC-xVrE1ZTnofd7SiCqN4x7sQD-ehz29rDY24Az8WN6ZUd7UvBYdAYdfupxGYuf4ovnZNMS_Dd6a0sU-2lBGbifLokAJ0fAIURgdZQGXz9oql4JrNtFLxG381Juy4PCu0aRus6ZVaEHfq5wWgaIB-ayPK2fEMEPwXZp_Ptw7juYLoWbc), the Maps SDK for iOS v9.0.0 no longer supports the OpenGL renderer and the setMetalRendererEnabled boolean. This functionality will be fully removed in the major SDK version scheduled for release in the second quarter of 2025.

The minimum version of the Maps SDK for iOS that supports the Metal renderer is v5.2.0, and the Metal renderer has been default since Maps SDK for iOS [v8.0.0](https://notifications.google.com/g/p/ANiao5qf8c3IOkVhFnVrCCy46_iieDTFx7pY6vXgrSUVRwFyJUDVWTVy3r5nEXxv8o2ASv_rCon-bcgjDuaPf0h1a3uCxHNG0W_pGRqHhDs6E14OKAZUXTXd21z3d24RoM0kkYHAWxKlvANWN8Q3M7Fnvfehumi9OkkW-zl0oV6-i0dGvOTRKr2kEWF4csXzbNk68JgeFy_B0SZJVINDlP0d_o7yU8YRm1KVcxZwu9tFarohuVMfSQuEdxgw-Qjv-4MYKDOEX4HlDXzXuqNaRszF0tk).

You own a project used by the bundle IDs below that loads OpenGL-rendered maps more than 5% of the time:

com.app.myapp

What you need to know
The rendering of 3D graphics in the Maps SDK for iOS leverages 3D capabilities from the host operating system. The Metal renderer uses the rendering foundation supported by Apple and has seen successful user adoption. It also provides an improved user experience, and receives updates and bug fixes.

What you need to do
It is recommended to use the Metal renderer (default) and stop using the setMetalRendererEnabled boolean.

Please review the SDK version you are using to make necessary adjustments:

To continue using the OpenGL renderer, specify the Maps SDK for iOS version 9 or earlier in your dependencies and set the [setMetalRendererEnabled](https://notifications.google.com/g/p/ANiao5ozKDsTH0DyD0EOOWkNoLN5IVLbpAEcX8Rg0rk4ixn3CODhn8i4orKeAWBKunCNerfgAm3_Fa-ABaR04yCRtKS1PUTQ4Qv7ClBwByxsJ6AiXCM1yTVYkM7Yx9ZxCIT3jEJUzvmMen0eJ37C-svs7NuYrT3LiciJS5785bYu_lo3soHIM0rdscsCbnKgNWAXYcc3lKaV29skkO6YcMFyB5aYI2sH2oWO9DhCoSSxR6N6WASoXZAwpa0bobEdgqXJwmeWY1iv6kunONL8NaY17tXM9NQS_u5nRExPqLo3wgxetOBJbGu0BlDflsIo07jqQa7hJfwsKSA) boolean to No.
If you are ready to use the Metal renderer for maps, specify Maps SDK for iOS version 8 or later in your dependencies and delete the [setMetalRendererEnabled](https://notifications.google.com/g/p/ANiao5ozKDsTH0DyD0EOOWkNoLN5IVLbpAEcX8Rg0rk4ixn3CODhn8i4orKeAWBKunCNerfgAm3_Fa-ABaR04yCRtKS1PUTQ4Qv7ClBwByxsJ6AiXCM1yTVYkM7Yx9ZxCIT3jEJUzvmMen0eJ37C-svs7NuYrT3LiciJS5785bYu_lo3soHIM0rdscsCbnKgNWAXYcc3lKaV29skkO6YcMFyB5aYI2sH2oWO9DhCoSSxR6N6WASoXZAwpa0bobEdgqXJwmeWY1iv6kunONL8NaY17tXM9NQS_u5nRExPqLo3wgxetOBJbGu0BlDflsIo07jqQa7hJfwsKSA) boolean since the default is “YES”. This boolean will be unsupported in the major version that will be released in the second quarter of 2025.
No action is required if [setMetalRendererEnabled](https://notifications.google.com/g/p/ANiao5ozKDsTH0DyD0EOOWkNoLN5IVLbpAEcX8Rg0rk4ixn3CODhn8i4orKeAWBKunCNerfgAm3_Fa-ABaR04yCRtKS1PUTQ4Qv7ClBwByxsJ6AiXCM1yTVYkM7Yx9ZxCIT3jEJUzvmMen0eJ37C-svs7NuYrT3LiciJS5785bYu_lo3soHIM0rdscsCbnKgNWAXYcc3lKaV29skkO6YcMFyB5aYI2sH2oWO9DhCoSSxR6N6WASoXZAwpa0bobEdgqXJwmeWY1iv6kunONL8NaY17tXM9NQS_u5nRExPqLo3wgxetOBJbGu0BlDflsIo07jqQa7hJfwsKSA) is not present in your codebase.
While the two renderers are at full parity with each other, the exact rendered pixels could reflect some differences between OpenGL and Metal. Please review your application to verify that it still looks as expected once moving off of OpenGL.

Note that if you specify a version of the Maps SDK for iOS that is greater than 12 months old, it falls outside the [SDK support](https://notifications.google.com/g/p/ANiao5o8NF7_gpjJec233jqsUoQygWzbvfCJMJnQpunfgLSwMhSm-DUvbiOk33xEEEvn7P-lHANwSUyzXNb6IAjrX_pZJt8gyoSXQdyvr-s-r-hlIgseB2nQUtEkTXAiHhiyiHa_ViO3AT2mJC5myyVEUmhbc2tdtRdUF_R67IzvAJRD6gO__sVP7pWvRHWIykFG3jzKZxVZSub-rhPaAsfvLBqjsv0lBbzNHuJ8xPFpnOiLWnf9tKR3PgBY) window for backwards-compatible fixes.

We understand that these changes might require you to make some adjustments. We're committed to working closely with you to ensure a smooth transition. If you have questions or need assistance, please contact [Google Maps Platform Support](https://notifications.google.com/g/p/ANiao5rJbJVYrMh3pgJK20gm0tmYuvepunFVtgu1pfUCCSb9Zw8ShaWlX-CNwSBAfslg4tqJfpvwgxpZHZhp7qlH_xGK4S3cBhTbGPGDQVIdwy2Z8buuvx-ra4DmZQeUJ0iPK_bWY3HuQUQcWJfRsZfDZK3JwyqN5h1294pa9HJ_WhHJxmXYGup8Aai6dW9pWb8GRRd43sYOiaLUdATKjd21oO1UbaZb4QiaP2EuYqLF1h905CyRuWQ0N6YFewK9pUkv7HLMnMdIKY8I).

Thanks for choosing Google Maps Platform.

### Proposal

It is recommended to use the Metal renderer (default) and stop using the setMetalRendererEnabled boolean.

**Comment by JgomesAT** [comment]
I've received the same email, how can I proceed?

**Comment by dinalmmf** [comment]
@huycozy 

google_maps_flutter version - google_maps_flutter
GoogleMaps version in podfile.lock - GoogleMaps (8.4.0)

I am not using `setMetalRendererEnabled` explicitly but when i installed `google_maps_flutter` in Flutter project and search for **setMetalRendererEnabled** globally it shows below results may be due to that Google sends this mail because it found this code using **setMetalRendererEnabled**

<summary>
</summary>
![Screenshot 2024-05-22 at 3 50 25 PM](https://github.com/flutter/flutter/assets/166010825/730349cd-de05-4551-972d-60ad0d70b4ca)

**Comment by JgomesAT** [comment]
google_maps_flutter version - google_maps_flutter: ^2.6.1
GoogleMaps version in podfile.lock - GoogleMaps (8.4.0)

in my case I don't find any place this setMetalRendererEnabled on my code,  maybe it is because some users have  an old version of my app

**Comment by zhoulijun12315** [comment]
I got the same message from google map.  

`google_maps_flutter: ^2.6.1`  in pubspec.yaml

Current GoogleMaps version in Podfile.lock, and can't find  `setMetalRendererEnabled `

```
  - GoogleMaps (8.4.0):
    - GoogleMaps/Maps (= 8.4.0)
  - GoogleMaps/Base (8.4.0)
  - GoogleMaps/Maps (8.4.0):
    - GoogleMaps/Base
```

**Comment by huycozy** [comment]
Thank you all for the info. I will label this for team's input.

**Comment by stuartmorgan** [comment]
> I am not using `setMetalRendererEnabled` explicitly but when i installed `google_maps_flutter` in Flutter project and search for **setMetalRendererEnabled** globally it shows below results may be due to that Google sends this mail because it found this code using **setMetalRendererEnabled**

That code is demo code that's not part of the plugin, so would not be part of your application.

The most likely explanation for this email is that you were previously shipping a version of the app that used an older version of `google_maps_flutter`, which used pre-8.0 versions of the Google Maps SDK; if you are now using the current version, then the part of the email listing cases where it does not apply should apply to you.

If anyone sees this in an app that has not shipped an app using a version of `google_maps_flutter_ios` older than `2.6.0` please let us know.

**Comment by jmagman** [comment]
> If anyone sees this in an app that has not shipped an app using a version of `google_maps_flutter_ios` older than `2.6.0` please let us know.

I'm going to close this since I don't think there's anything actionable here.  If anyone sees this on `google_maps_flutter_ios` older than 2.6 please open a new issue to let us know what you're seeing.  Thank you!
