### ISSUE TITLE
UI Elements Missing in Release Mode but Present in Debug Mode

### ISSUE THREAD

**Issue by isshort** [flutter/flutter#148823]
### Steps to reproduce

I've created a new Flutter project. When I run the app in debug mode, the UI looks good, and all components, including the floating action button and the app bar title, are displayed correctly. However, when I run the app in release mode, the floating action button and app bar title are missing. Additionally, if I delete the app completely from my device and then run it first in release mode, it displays correctly, but switching back to debug mode results in incorrect visibility of these elements.

### Expected results

The UI should display all components correctly in both debug and release modes consistently.

### Actual results

  
   - Debug Mode:
        UI elements are correctly displayed.
   - Release Mode:
               Floating action button and app bar title are missing unless the app is run in release mode first after a complete uninstall.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Without debug mode</summary>

![Screenshot_1716361306](https://github.com/flutter/flutter/assets/37234355/3db2b51a-46e1-4f1d-bec7-c22f5330de13)

<summary>In debug mode</summary>

 
![Screenshot_1716361456](https://github.com/flutter/flutter/assets/37234355/23676407-8dc2-4304-a7e2-7fbe7865c67c)

<summary>Device Info</summary>

![image](https://github.com/flutter/flutter/assets/37234355/53fb33f6-9a7a-4305-8923-1bdaff15c1a4)

</details>

### Logs

<details open><summary>logs</summary>

```console
 
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 [√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19043.867], locale en-US)
    • Flutter version 3.22.0 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (13 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\PC\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 124.0.6367.208

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@isshort 
I tried the sample code in release mode running on Android emulator (api 33) using latest stable which rendered all elements properly as below:

<img width="287" alt="Screenshot 2024-05-22 at 3 52 06 PM" src="https://github.com/flutter/flutter/assets/67046386/00be3352-0d2b-443e-9cab-24f204c7e0d1">


> ```
> emulator-5554 • android-x86
> ```

The emulator you are running is x86 for which running in release mode is probably not supported. Can you try on any other emulator and also on physical device to check if you still get same behavior or not ?

**Comment by mzisshort** [comment]
Hi @darshankawar,
Thanks for your response.
I've tried running the app in another emulator as well. The issue occurs when I first run it in release mode, it works normally. However, after quitting and rerunning it in debug mode, it doesn't work correctly. If I clear the cache or delete the app from the device and then run it first in debug mode, it works normally again. But if I rerun it in release mode after that, it doesn't work.

Any insights on what might be causing this issue would be greatly appreciated.

**Comment by isshort** [comment]
Hi @darshankawar,
Thanks for your response.
I've tried running the app in another emulator as well. The issue occurs when I first run it in release mode, it works normally. However, after quitting and rerunning it in debug mode, it doesn't work correctly. If I clear the cache or delete the app from the device and then run it first in debug mode, it works normally again. But if I rerun it in release mode after that, it doesn't work.

Any insights on what might be causing this issue would be greatly appreciated.

**Comment by darshankawar** [comment]
Can't say what exactly could be causing the rendering issue, but seems like Android emulator specific issue. Can you switch to latest master and re-run your scenario to check if it still persists in it as well or not ?

`flutter channel master`
`flutter upgrade`

**Comment by isshort** [comment]
I've already tried that, but the problem still exists. However, I found a solution that worked for me: [this comment on GitHub](https://github.com/flutter/flutter/issues/146890#issuecomment-2123136901) fixed my issue.

**Comment by darshankawar** [comment]
Closing as resolved.
