### ISSUE TITLE
flutter 3.22.0 text theme error

### ISSUE THREAD

**Issue by Lukaalishi** [flutter/flutter#148822]
.pub-cache/hosted/pub.dev/country_pickers-2.0.0/lib/utils/my_alert_dialog.dart:107:46: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
          style: Theme.of(context).textTheme.headline6!

**Comment by justprodev** [comment]
Hi,

headline6 -> titleLarge

for more info:

https://docs.google.com/spreadsheets/d/1x_UJ7GiB61ByBo6cPLm_JfLrgFqAfkQo7pPK_lHvsUo/edit?pli=1#gid=0
