### ISSUE TITLE
Delay in Child Widget Taps Due to GestureDetector's onDoubleTap Recognizer

### ISSUE THREAD

**Issue by icnahom** [flutter/flutter#148945]
### Steps to reproduce

1. Open the provided Dartpad code sample.
2. Tap on the `More icon` (3 dots) inside the Red box.
3. Tap on the `More icon` (3 dots) inside the Blue box.
4. Observe the speed difference to open Menu between the two.

### Expected results

The child widget should capture the tap event, and display the menu quicker.

### Actual results

The child widget is not capturing the tap event immediately, and causes delay. 

Normally, child widgets would capture their `onTap` even if they are wrapped by another `GestureDetector`. But when the parent widget has an `onDoupbleTap` callback it causes delay in the child `onTap` callback.

### Code sample

<details open><summary>Code sample</summary>

https://dartpad.dev/?id=8a5ae7f568feb1475f036926a345a341

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/60504285/68e250aa-f592-452c-9e75-9c72a1ed96ff)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22635.2700], locale en-US)
    • Flutter version 3.16.3 on channel stable at C:\Users\Nahom\Dev\flutter_windows_3.16.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (6 months ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Nahom\Dev\android_sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\Nahom\Dev\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at C:\Users\Nahom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22635.2700]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.60
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.97

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @icnahom 
There's a similar issue open describing your case https://github.com/flutter/flutter/issues/106170 in which you can follow-up for further updates. There are some workarounds mentioned in underlying comments that you can check to see if they help in your case or not.

**Comment by icnahom** [comment]
This issues is more about nested `GestureDetector`'s, that the child `GestureDetector`'s `onTap` should fire despite the delay on the parent `GestureDetector`'s `onDoubleTap`.

**Comment by darshankawar** [comment]
> But when the parent widget has an `onDoupbleTap` callback it causes delay in the child `onTap` callback.

It seem to be explained [here](https://github.com/flutter/flutter/issues/67255#issuecomment-1196053169) as the reason for it ?

**Comment by icnahom** [comment]
@goderbauer  I see you've closed this issues #67255 for working as expected, but the delay leaves a false impression that flutter is slow framework (when it's not).

**Comment by darshankawar** [comment]
Keeping this issue open for team's input / feedback on behavior reported.

**Comment by goderbauer** [comment]
The statement at https://github.com/flutter/flutter/issues/67255#issuecomment-1196053169 is still correct. As configured in this example we have to wait and see if there is another tap in order to disambiguate tap from double tap. If you don't care about this, you could react to `onTapDown` which will fire right away without delay.
