### ISSUE TITLE
`flutter channel <foo>` doesn't fetch updated branches first

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14893]
https://github.com/flutter/flutter/blob/eaa9b47a4ac278a9439468911d2c361a472b114b/packages/flutter_tools/lib/src/commands/channel.dart#L103

We should be running `git fetch` before checking out the branch.  Otherwise, a user on the "dev" channel who tries to switch to the "beta" channel will get switched to whatever "beta" pointed to when the user last ran `flutter upgrade`.

**Comment by tvolkert** [comment]
This is exacerbated by the fact that our "beta" branch _was_ pointing to 8f65fec5f5f7d7afbb0965f4a44bdb330a28fb19, and if the user gets checked out to that revision, then tries to run `flutter upgrade`, they run into this error:

```
$ flutter upgrade
Upgrading Flutter from <redacted>/project/flutter/flutter...
Updating 8f65fec5f..f914e701c
 dev/devicelab/images/agent-statuses.png            |  Bin 0 -> 18399 bytes
 dev/devicelab/images/broken-test.png               |  Bin 30426 -> 69897 bytes
 dev/devicelab/images/legend.png                    |  Bin 0 -> 48845 bytes
 .../fastlane/metadata/android/en-US/video.txt      |    0
 .../AppIcon.appiconset/Icon-App-1024x1024@1x.png   |  Bin 0 -> 11112 bytes
 packages/flutter/test/service_extensions_test_file |  Bin 0 -> 5 bytes
 ...mage.dart => obscured_animated_image_test.dart} |    0
 .../AppIcon.appiconset/Icon-App-1024x1024@1x.png   |  Bin 0 -> 11112 bytes
 .../test/data/asset_test/font/.dartignore          |    0
 1017 files changed, 80058 insertions(+), 11431 deletions(-)

Upgrading engine...
Building flutter tool...
Incompatible version constraints on async:
- flutter_tools depends on version 2.0.4
- pub itself depends on version >=1.8.0 <2.0.0
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```

**Comment by tvolkert** [comment]
Observations:

1. This will only affect existing users who don't `flutter upgrade` before switching to the beta channel.
2. Most of our existing users (who're on the "dev" and "master" channels) will likely just stay on their dev or master channel anyway.
3. the commit that fixes this issue won't be picked up by users unless they upgrade, in which case they'll also pick up the updated branch pointer.

That all adds up to just telling existing users that they should run `flutter upgrade` first.

**Comment by mit-mit** [comment]
Are we putting the upgrade steps somewhere? I think cc @filiph was going to update the `git clone` instruction. Maybe put the upgrade steps on a wiki, or something?

**Comment by tvolkert** [comment]
FYI, anyone that gets stuck in a bad state because of this can get unstuck (and onto the right beta release) by doing the following:

```
$ git checkout dev
$ flutter upgrade
$ flutter channel beta
```

**Comment by tvolkert** [comment]
An even simpler way to get unstuck:

```
# From the base directory of the Flutter GitHub clone
$ rm -rf bin/cache
```

**Comment by tvolkert** [comment]
> Are we putting the upgrade steps somewhere?

https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
