### ISSUE TITLE
Listen events from flutter webview to flutter mobile app

### ISSUE THREAD

**Issue by Vigneshkumar-CM** [flutter/flutter#148933]
### Steps to reproduce

In flutter app, I loaded single page webview that page developed by flutter. while clicking button from flutter webview, it should call flutter mobile app code

### Expected results

I expecting listen events from flutter webview to flutter dart code

### Actual results

can't call flutter app code from flutter webview

### Code sample

-

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
@Vigneshkumar-CM In case you think it's a bug of Flutter framework or [webview_flutter](https://pub.dev/packages/webview_flutter) package, please try to provide all information indicated in the template so that we can address the issue properly. More specifically, please provide the following information:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- The version of `webview_flutter`
- Which environment did this issue happen in?

If this is a how-to question, please check https://stackoverflow.com/questions/63205537/how-to-listen-to-events-in-flutter-webview to see if answers there can help.

**Comment by Vigneshkumar-CM** [comment]
Thank you for your quick response. I used "InAppWebView" widget for load webview in flutter

`InAppWebView(
          initialUrlRequest:
              URLRequest(url: WebUri('flutter-web-url')),
          onWebViewCreated: (controller) async {
            webViewController = controller;
          },
          onConsoleMessage: (controller, consoleMessage) {},
        ),`

**InAppWebView version**: 6.0.0

**Output of flutter doctor**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on Ubuntu 20.04.6 LTS 5.15.0-107-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2023.2)
[✓] Connected device (3 available)
[✓] Network resources


I need to listen or call from flutter webview to flutter mobile app. That webview has to load flutter website.

**Comment by huycozy** [comment]
`flutter_inappwebview` is not maintained by Flutter repository, it's a 3rd party package. Please open an issue on its repository for better support there: https://github.com/pichillilorenzo/flutter_inappwebview/issues. 

Closing as this is not an issue with Flutter framework or 1st party package.
