### ISSUE TITLE
Flutter seems to require `new` for widgets that have a builder property

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#14899]
I am running Flutter with the --preview-dart-2 flag. 

I have a Navigator, whose code looks like this:
```
    Navigator.of(context).push(MaterialPageRoute<Null>(
      builder: (BuildContext context) {
        return Container();
    ));
```
This throws a warning that the function type BuildContext -> dynamic is not of type BuildContext -> Widget. When I add a `new` to the `MaterialPageRoute` widget, the error disappears. I.e. as below:
```
    Navigator.of(context).push(new MaterialPageRoute<Null>(
      builder: (BuildContext context) {
        return Container();
    ));
```
I noticed the same with the LayoutBuilder widget, where I get the warning unless I put `new` in front of LayoutBuilder.
```
final conversionScreen = LayoutBuilder(
     builder: (BuildContext context, BoxConstraints  constraints) {
        return Container();
     });
```

**Comment by brianegan** [comment]
I saw this as well! My problem came when trying to use the `StreamBuilder` class.

**Comment by mraleph** [comment]
Reduced and filed upstream against Dart dart-lang/sdk#32342

**Comment by mraleph** [comment]
Thank you for the report @maryx!

**Comment by devoncarew** [comment]
@mraleph, thanks for reducing! /cc @bwilkerson; closing in favor of dart-lang/sdk#32342
