### ISSUE TITLE
webview_flutter: loadHtmlString Unable to correctly parse image address

### ISSUE THREAD

**Issue by qiuweilu** [flutter/flutter#148925]
### Steps to reproduce

loadHtmlString(htmlData, baseUrl: 'http://45.32.88.175:8686');
print(htmlData);

can show image
img src="https://www.mlito.com/wp-content/uploads/2018/03/bf478dbc95-768x1152.jpg"  data-mce-src="https://www.mlito.com/wp-content/uploads/2018/03/bf478dbc95-768x1152.jpg"
can't show image
img src="http://45.32.88.175:8686/upload/202405/23/75FF1B117A2B4887910110F0D2F9F6A1.jpg"  data-mce-src="../upload/202405/23/75FF1B117A2B4887910110F0D2F9F6A1.jpg"

<img width="195" alt="微信图片_20240523111332" src="https://github.com/flutter/flutter/assets/58357633/268800de-f095-406c-a1c4-7e758130bf97">

### Expected results

show correct
img src="http://45.32.88.175:8686/upload/202405/23/75FF1B117A2B4887910110F0D2F9F6A1.jpg"  data-mce-src="../upload/202405/23/75FF1B117A2B4887910110F0D2F9F6A1.jpg"

### Actual results

show error
img src="http://45.32.88.175:8686/upload/202405/23/75FF1B117A2B4887910110F0D2F9F6A1.jpg"  data-mce-src="../upload/202405/23/75FF1B117A2B4887910110F0D2F9F6A1.jpg"

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@qiuweilu 
Your issue is not clear to me. Please provide clear reproducible code sample along with actual vs expected behavior in properly formatted text so that we can properly address the issue.

**Comment by darshankawar** [comment]
@qiuweilu 
Please check plugin [example](https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter/example) and see if using it you still get same behavior or not.
