### ISSUE TITLE
Should provide a sample code demonstrating how to use the sensor service

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#149]
<a href="https://github.com/henrichen"><img src="https://avatars.githubusercontent.com/u/785068?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [henrichen](https://github.com/henrichen)**
_Thursday Aug 27, 2015 at 05:26 GMT_
_Originally opened as https://github.com/flutter/engine/issues/883_

---

By Adam Barth:

> ...Sensors are available via the sensor service:
> 
> https://github.com/domokit/sky_engine/blob/master/mojo/services/sensors/public/interfaces/sensors.mojom

**Comment by sethladd** [comment]
I checked our API docs, and I didn't see a mention of Sensor.

What's a good way we can generate docs for all our services?
