### ISSUE TITLE
Input: Deleting text doesn't always start deleting straight away

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1490]

**Comment by abarth** [comment]
Not sure what the exact repro steps where.  I had added some arabic text to the address_box example and put tried deleting from the end.

**Comment by eseidelGoogle** [comment]
@mpcomplete is working on text and would know.

**Comment by mpcomplete** [comment]
Not sure.. I've noticed that hitting `space` doesn't immediately display the space visually, even though it's there. If you hit `backspace`, it will delete the invisible space. Maybe related?

**Comment by sethladd** [comment]
I can't repro this on iOS or Android. Backspace seems to do the right thing in a normal amount of time.

(one thing we don't seem to do is the "delete a whole word" when you hold down the backspace key. but I can file that as a separate issue.)

I tried to test with arabic text. I copied some arabic text, and tried to paste it into our text field. After I pasted it, nothing appeared. (again, probably a separate bug)

I'm inclined to close out this issue, but please do reopen with repro steps if you run across this again. Thanks!
