### ISSUE TITLE
Engine roll to the framework failing on macros package version issue

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#149093]
Since https://github.com/flutter/flutter/pull/149072

```
Because no versions of macros match >=0.1.0-main.0 <0.1.0-main.0 and macros >=0.1.0-main.0 <0.1.0-main.1 depends on _macros 0.1.0 from sdk, macros >=0.1.0-main.0 <0.1.0-main.1 requires _macros 0.1.0 from sdk.
And because no versions of _macros from sdk match 0.1.0, macros >=0.1.0-main.0 <0.1.0-main.1 is forbidden.
And because macros >=0.1.0-main.1 <0.1.0-main.2 depends on _macros 0.1.1 from sdk which doesn't match any versions, macros >=0.1.0-main.0 <0.1.0-main.2 is forbidden.
And because macros >=0.1.0-main.2 <0.1.0-main.3 depends on _macros 0.1.2 from sdk which doesn't match any versions, macros >=0.1.0-main.0 <0.1.0-main.3 is forbidden.
And because macros >=0.1.0-main.3 <0.1.0-main.4 depends on _macros 0.1.3 from sdk which doesn't match any versions, macros >=0.1.0-main.0 <0.1.0-main.4 is forbidden.
And because macros >=0.1.0-main.4 <0.1.0-main.5 depends on _macros 0.1.4 from sdk which doesn't match any versions, macros >=0.1.0-main.0 <0.1.0-main.5 is forbidden.
And because macros >=0.1.0-main.5 <0.1.0-main.6 depends on _macros 0.1.5 from sdk which doesn't match any versions, macros >=0.1.0-main.0 <0.1.0-main.6 is forbidden.
And because analyzer >=6.5.0 depends on macros >=0.1.0-main.0 <0.1.1 and macros >=0.1.0-main.6 depends on _macros 0.1.6 from sdk, analyzer >=6.5.0 requires _macros 0.1.6 from sdk.
So, because no versions of _macros from sdk match 0.1.6 and flutter_tools depends on analyzer 6.5.0, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

**Comment by zanderso** [comment]
Previously: https://github.com/flutter/flutter/issues/148004

cc @christopherfujino @jakemac53 @scheglov @gspencergoog

Handling this by reverting the Dart SDK and stopping Dart -> Engine rolls so that the Engine -> Framework rolls do not remain blocked over the whole long weekend.

**Comment by zanderso** [comment]
From @jakemac53 over chat:

> You will need the next version of analyzer (6.5.1, to be published soon)

**Comment by jakemac53** [comment]
Correct, for the next engine -> flutter roll to succeed (once it includes https://github.com/dart-lang/sdk/commit/77490aacc7de1fdc960418d3f84f08c753ec35e3), there will need to be an atomic roll of analyzer from `6.5.0` to `6.5.1`.

We would not need an atomic update here if we can instead do a version constraint such as `>=6.5.0 <6.5.2` on the analyzer in flutter/flutter packages.

The reason for this is analyzer implements APIs which come from an SDK vendored package (package:_macros ultimately), and a new method was added to a class that the analyzer implements. It has dependency constraints to guarantee compatibility, but since it is pinned the version has to be explicitly updated when the Dart SDK is updated.

**Comment by scheglov** [comment]
Published https://pub.dev/packages/analyzer/versions/6.5.1

**Comment by goderbauer** [comment]
(triage) @eyebrowsoffire I believe you're the engine sheriff. Could you bump the version of the analyzer to 6.5.1 with the next engine roll?

**Comment by zanderso** [comment]
Dart with the breaking change has to be rolled into the engine first, then the analyzer version bump has to land in a manual roll at the same time as rolling the engine with the new Dart version.

**Comment by eyebrowsoffire** [comment]
I'm on it. We had other breakages blocking the roll yesterday, but I think we should be able to get this through today.

**Comment by jakemac53** [comment]
Note that there was an accidental change that landed in that version, which requires another breaking change to roll back, so this will happen again soon.... apologies.

I could likely land things today, if you want to wait a bit longer and do a single roll.

**Comment by zanderso** [comment]
In https://github.com/flutter/flutter/pull/149263, rolling the framework packages forward to pick up the new analyzer has also brought in what look like new versions of plugins for some integration tests which are now failing on CI, as in:

https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20build_tests_1_4/7440/overview

We should decouple the plugin updates from the analyzer package updates.

**Comment by a-siva** [comment]
Can this issue be closed ? 
Improvements to the process of making changes  package:macros is being tracked in https://github.com/dart-lang/sdk/issues/55870

**Comment by jonahwilliams** [comment]
This particular issue has been fixed, though the roll is blocked for new reasons.

**Comment by a-siva** [comment]
> This particular issue has been fixed, though the roll is blocked for new reasons.

I presume you are referring to the dart2wasm compilation errors issues, it being tracked in https://github.com/flutter/flutter/issues/149600
