### ISSUE TITLE
[Camera]Hopefully the camera package will add frame processing. For example, I want to use iOS CoreImage to process frames.

### ISSUE THREAD

**Issue by llli0v0** [flutter/flutter#149014]
### Use case

I want to process frame in real time. 

### Proposal

I've been looking around a lot and there doesn't seem to be any such feature yet. Hopefully, you'll consider adding this feature.

Thank you flutter team.

**Comment by huycozy** [comment]
Hi @llli0v0, 
Please tell us the problem you are running into that led to you wanting a new feature. And please precisely describe what you would like `camera` package to be able to do for that. It would be helpful if you give an example you found as well.
