### ISSUE TITLE
Provide colSpan rowSpan functionality for tables

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#149015]
### Use case

How can I have a colspan in the Table Widget ?

Mean:
|--------|--------|
|..col1..|..col2.|
|--------|--------|
|.........col3........|
|--------|--------|

Thank you.

### Proposal

Provide colSpan rowSpan functionality for tables

**Comment by darshankawar** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/21594
