### ISSUE TITLE
when I run: flutter test --coverage some test error but run : flutter test all test passed

### ISSUE THREAD

**Issue by sqiao3-ford** [flutter/flutter#149024]
### Steps to reproduce

The project has approximately two thousand test files
when I run flutter test  all test passed but when i want to  see coverage run flutter test --coverage some test files  error:
```
unhandled error during finalization of test:
xx_order_page_test.dart
TestDeviceException(Shell subprocess crashed with segmentation fault.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:246:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:228:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:509:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:565:11)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#5      _FlutterPlatformStreamSinkWrapper.close.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:675:7)
<asynchronous suspension>


```

### Expected results

when run flutter test --coverage. all test passed

### Actual results

some test files failed but error  but run flutter test. all passed

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.19.5 on channel stable at
      /Users/sqiao3/FlutterSDK/flutter-3.19.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (8 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sqiao3/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/sqiao3/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4.1 23E224
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.77

[!] Network resources
    ✗ A network error occurred while checking "https://pub.flutter-io.cn":
      Connection reset by peer

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@sqiao3-ford 
Most probably [this](https://github.com/flutter/flutter/issues/142810#issuecomment-1952931753) is a solution that you can check and see if it helps to resolve in your case or not.
Closing based on that comment since it worked. If not, write in comments and I'll reopen it.

**Comment by sqiao3-ford** [comment]
> @sqiao3-ford Most probably [this](https://github.com/flutter/flutter/issues/142810#issuecomment-1952931753) is a solution that you can check and see if it helps to resolve in your case or not. Closing based on that comment since it worked. If not, write in comments and I'll reopen it.

thank you for your reply, i try but it not work .my test is too much .i delete some it still run failed

**Comment by sqiao3-ford** [comment]
> > @sqiao3-ford Most probably [this](https://github.com/flutter/flutter/issues/142810#issuecomment-1952931753) is a solution that you can check and see if it helps to resolve in your case or not. Closing based on that comment since it worked. If not, write in comments and I'll reopen it.
> 
> thank you for your reply, i try but it not work .my test is too much .i delete some it still run failed

i fixed it use a shell

#!/bin/bash

# 定义项目根目录和覆盖率文件目录
PROJECT_ROOT=$(pwd)
COVERAGE_DIR="${PROJECT_ROOT}/coverage"

# 创建覆盖率文件目录
mkdir -p "${COVERAGE_DIR}"

# 定义模块目录数组
MODULES=("module1" "module2" "module3")

# 循环运行每个模块的测试并生成覆盖率文件
for MODULE in "${MODULES[@]}"
do
    cd "${PROJECT_ROOT}/test/${MODULE}"
    flutter test --coverage
    cp coverage/lcov.info "${COVERAGE_DIR}/${MODULE}.lcov.info"
done

# 合并覆盖率文件
cd "${COVERAGE_DIR}"
lcov -a [module1.lcov.info](https://module1.lcov.info/) -a [module2.lcov.info](https://module2.lcov.info/) -a [module3.lcov.info](https://module3.lcov.info/) -o [merged.lcov.info](https://merged.lcov.info/)

# 生成 HTML 覆盖率报告
genhtml [merged.lcov.info](https://merged.lcov.info/) -o coverage_report

echo "覆盖率报告已生成在 ${COVERAGE_DIR}/coverage_report"
