### ISSUE TITLE
Provide an empty status placeholder for the table

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#149016]
### Use case

![image](https://github.com/flutter/flutter/assets/122137647/b1624444-1e1c-4199-aa10-c1e332770593)

### Proposal

Provide an empty status placeholder for the table

**Comment by huycozy** [comment]
Hi @laterdayi, there are several table widgets in Flutter (Table, DataTable, PaginatedDataTable..). Which widget are you proposing the feature to? Can you also share an example of how you are trying to achieve this?

**Comment by laterdayi** [comment]
Hi @huycozy  Thank you for your help, I hope to be able to achieve this effect, if there is no data when I can display the table header and a temporary no data

![image](https://github.com/flutter/flutter/assets/122137647/b63ab037-fb77-45ca-97ed-ab5e97304ba0)

**Comment by huycozy** [comment]
Duplicate of new one https://github.com/flutter/flutter/issues/149079 with a request on a specific Widget.
