### ISSUE TITLE
flutter doctor no work............

### ISSUE THREAD

**Issue by EliProject** [flutter/flutter#149019]
### Steps to reproduce

As problem
[Failed running flutter doctor after upgrading to the latest SDK version #143696](https://github.com/flutter/flutter/issues/143696)
[flutter doctor output nothing #144014](https://github.com/flutter/flutter/issues/144014)
[flutter doctor -v Error #148941](https://github.com/flutter/flutter/issues/148941)

but final no idea to solve it.
I have the same probolem,
how to solve it ？

### Expected results

solve the problem

### Actual results

no idea to sovle

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@EliProject 
The original issue is still open so you will need to have a bit of patience until team's input on further resolution. I'll ping concerned team member for attention.
Closing as duplicate.
