### ISSUE TITLE
The latest version of the camera plugin cannot find the camera list, using CameraX，提示 Camera LensFacing verification failed, existing cameras

### ISSUE THREAD

**Issue by ocean6666z** [flutter/flutter#149069]
### Steps to reproduce

1、Recently using the camera plugin
2、Obtaining camera found that the camera is empty

### Expected results

Returning to my current two USB cameras

### Actual results

Not a single one。
Prompt error：
D/CameraRepository( 8346): Added camera: 123
I/Camera2CameraInfo( 8346): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL
D/CameraRepository( 8346): Added camera: 125
I/Camera2CameraInfo( 8346): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL
D/CameraValidator( 8346): Verifying camera lens facing on rk3568_r68p, lensFacingInteger: null
E/CameraValidator( 8346): Camera LensFacing verification failed, existing cameras: [Camera@d9a566[id=123], Camera@3abaff9[id=125]]
E/CameraX ( 8346): The device might underreport the amount of the cameras. Finish the initialize task since we are already reaching the maximum number of retries.

### Code sample

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  _cameras = await availableCameras();
  runApp(const CameraApp());
}

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

I/CameraManagerGlobal( 8346): Connecting to camera service
D/CameraRepository( 8346): Added camera: 123
I/Camera2CameraInfo( 8346): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL
D/CameraRepository( 8346): Added camera: 125
I/Camera2CameraInfo( 8346): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL
D/CameraValidator( 8346): Verifying camera lens facing on rk3568_r68p, lensFacingInteger: null
E/CameraValidator( 8346): Camera LensFacing verification failed, existing cameras: [Camera@7e8ceb8[id=123], Camera@5571493[id=125]]
W/CameraX ( 8346): Retry init. Start time 1960407 current time 1960576
W/CameraX ( 8346): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 8346): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
W/CameraX ( 8346): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:334)
W/CameraX ( 8346): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
W/CameraX ( 8346): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/CameraX ( 8346): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/CameraX ( 8346): 	at java.lang.Thread.run(Thread.java:923)
W/CameraX ( 8346): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 8346): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:94)
W/CameraX ( 8346): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:83)

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.6, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.6 on channel stable at /Users/zhanghaiyang/Desktop/project/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (5 周前), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhanghaiyang/Library/Android/sdk
    • Platform android-34, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • P1 (mobile)     • adb-R68NS033470026-rXWdfe._adb-tls-connect._tcp. • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos                                            • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome                                           • web-javascript • Google Chrome 125.0.6422.77

**Comment by huycozy** [comment]
>Returning to my current two USB cameras

Hi @ocean6666z, what device are you testing on? (model name, OS version). Are you using the latest package version `camera_android_camerax: ^0.6.5+2`? Could you try running [package example](https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax/example) and confirm if the issue persists?

**Comment by ocean6666z** [comment]
The device used is P1 (mobile) • adb-R68NS033470026 rXWdfe_ Adb tls connect. _tcp. • Android arm64 • Android 11 (API 30)

**Comment by ocean6666z** [comment]
Running in the demo has the same issue as not being able to find the camera. The cameras are all USB external, but they perform normally in Android 7.0 @huycozy

**Comment by yx-design** [comment]
I also encountered this problem, USB external, how to deal with it?

**Comment by huycozy** [comment]
I found a similar issue at https://github.com/flutter/flutter/issues/42413. This is unsupported yet, so I will close this as a duplicate, please follow up on it for updates. Thanks!

**Comment by hxmeie** [comment]
The v0.11.0 version I used encountered the same problem. After I added the following code, it can be used normally.
<img width="1601" alt="iShot_2024-05-28_14 00 25" src="https://github.com/flutter/flutter/assets/16347352/fa79d94c-84f2-430b-8778-a17b60f64d54">

**Comment by hxmeie** [comment]
> I also encountered this problem, USB external, how to deal with it? <img alt="image" width="1243" src="https://private-user-images.githubusercontent.com/164110522/334045662-eb167906-2ba8-4684-acc8-041d7648f56d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzY4NDUsIm5iZiI6MTcxNjg3NjU0NSwicGF0aCI6Ii8xNjQxMTA1MjIvMzM0MDQ1NjYyLWViMTY3OTA2LTJiYTgtNDY4NC1hY2M4LTA0MWQ3NjQ4ZjU2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNjA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmU0MzA0ZTQ2NTJkMTgxYzNjMGY3MDRmMWY0ZWRkMDVmNDM5NWMwY2Y0NzljODRkZGUyN2M5MzliZGMyMDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Ac_E0RtJrykrrf9VM3zZy3irvGT6Mz-xln5BJMxY1k">



> I also encountered this problem, USB external, how to deal with it? <img alt="image" width="1243" src="https://private-user-images.githubusercontent.com/164110522/334045662-eb167906-2ba8-4684-acc8-041d7648f56d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzY4NDUsIm5iZiI6MTcxNjg3NjU0NSwicGF0aCI6Ii8xNjQxMTA1MjIvMzM0MDQ1NjYyLWViMTY3OTA2LTJiYTgtNDY4NC1hY2M4LTA0MWQ3NjQ4ZjU2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNjA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmU0MzA0ZTQ2NTJkMTgxYzNjMGY3MDRmMWY0ZWRkMDVmNDM5NWMwY2Y0NzljODRkZGUyN2M5MzliZGMyMDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Ac_E0RtJrykrrf9VM3zZy3irvGT6Mz-xln5BJMxY1k">

**Comment by yx-design** [comment]
No need for camera plug-in, write a function to operate the camera directly on the native side through Camerax, and call it on the flutter side

> > I also encountered this problem, USB external, how to deal with it? <img alt="image" width="1243" src="https://private-user-images.githubusercontent.com/164110522/334045662-eb167906-2ba8-4684-acc8-041d7648f56d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzY4NDUsIm5iZiI6MTcxNjg3NjU0NSwicGF0aCI6Ii8xNjQxMTA1MjIvMzM0MDQ1NjYyLWViMTY3OTA2LTJiYTgtNDY4NC1hY2M4LTA0MWQ3NjQ4ZjU2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNjA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmU0MzA0ZTQ2NTJkMTgxYzNjMGY3MDRmMWY0ZWRkMDVmNDM5NWMwY2Y0NzljODRkZGUyN2M5MzliZGMyMDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Ac_E0RtJrykrrf9VM3zZy3irvGT6Mz-xln5BJMxY1k">
> 
> It was solved after modifying the source code

No need for camera plug-in, write a function to operate the camera directly on the native side through Camerax, and call it on the flutter side
