### ISSUE TITLE
Broken link from website page "Making HTTP Networking Requests in Flutter"

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#14902]
From URL: https://flutter.io/networking/
File: networking.md
Destination URL: https://httpbin.com/

The site httpbin.com appears to be down for me. This was the case yesterday and it's the case today as well.

**Comment by Sfshaza** [comment]
Just checked again and it's still down.

**Comment by Sfshaza** [comment]
This page has been absorbed into /cookbook and this bug has been fixed.
