### ISSUE TITLE
[infra] iPhone 11 is not available

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#149058]
### Type of Request

bug

### Infrastructure Environment

Device Lab

### What is happening?

Tree has gone red a few times in the last hour due to the failure below.

```
Infra Failure: Step('Prepare iOS device.Dismiss iOS dialogs.Run app to dismiss dialogs') (retcode: 70)
```

```
iPhone 11, error:iPhone 11 is not available because it is unpaired Pair with the device in the Xcode Devices Window, and respond to any pairing prompts on the device. }
```

Examples:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20platform_views_scroll_perf_non_intersecting_impeller_ios__timeline_summary/8501/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20complex_layout_ios__start_up/17170/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64_ios%20hello_world_ios__compile/12973/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64_ios%20flutter_gallery_ios__compile/12937/overview

**Comment by kentnguyen99** [comment]
@jmagman Problems has been resolved and fixed. Can you give another try?

**Comment by Renzo-Olivares** [comment]
Closing this because I'm no longer observing the infra failure and the tree is stable.
