### ISSUE TITLE
cannot resolve class 'StreamTransformerBase' from 'SingleSubscriptionTransformer'

### ISSUE THREAD

**Issue by ybmeng** [flutter/flutter#14909]
## Steps to Reproduce
Follow steps through fresh installation and follow instructions in video: https://www.youtube.com/watch?v=iflV0D0d1zQ

## Flutter doctor -v
[✓] Flutter (Channel dev, v0.1.6, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.6 at /Users/ybmeng/code/flutter
    • Framework revision 1f3eb5034f (3 days ago), 2018-02-23 18:35:40 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/ybmeng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • Nexus 5X • 00bc4f89b18a4daf • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

## Issue
At the `http call to retrieve places` step of the video, this is the outcome:
$ dart lib/places.dart --verbose
'package:async/src/single_subscription_transformer.dart': malformed type: line 16 pos 51: cannot resolve class 'StreamTransformerBase' from 'SingleSubscriptionTransformer'
class SingleSubscriptionTransformer<S, T> extends StreamTransformerBase<S, T> {

**Comment by ybmeng** [comment]
I installed dart via homebrew, and it looks like the issue is in the homebrew distribution of dart. I built it from https://github.com/dart-lang/sdk/wiki/Building and it worked.

**Comment by dipockdas** [comment]
I had this issue - but resolved it without having to rebuild the SDK.  In my case I found that running dart lib/places.dart it was using the Dart SDK installed for regular web development. 
Flutter ships with it's own version of Dart.  When I changed the command to point to the Flutter version of Dart (located under flutter/bin/cache) - I was able to execute the command successfully. 
Example: 
~/github/flutter/bin/cache/dart-sdk/bin/dart lib/places.dart

**Comment by saltypoison** [comment]
If anyone else stumbles across this, I had the same thing being caused by funky imports.  I had the same .dart being imported twice, with slightly different syntax, which was the root cause of this error for me.

**Comment by SGuzel** [comment]
It was the same scenario for me. I have installed the stable version and it did not worked. 
Using the Dart VM version: 2.0.0-dev.50.0 on Windows for 64 Bit works now so far. This is the precompiled version for windows.

**Comment by hongsw** [comment]
`brew uninstall dart
brew install dart --devel`
In my case, I installed it again and solved it.

**Comment by SebSob** [comment]
@hongsw worked for me aswell!
