### ISSUE TITLE
Cannot run gallery on Android in beta

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#14912]
## Steps to Reproduce

1. `cd ~/tmp`
1. `git clone -b beta https://github.com/flutter/flutter.git`
1. `cd ~/tmp/examples/flutter_gallery/`
1. `~/tmp/flutter/bin/flutter build apk`

=>

```
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: /Users/mit/tmp/flutter/examples/flutter_gallery/android/gradlew app:properties:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mit/tmp/flutter/examples/flutter_gallery/android/app/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':app'.
> 3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Please review your Gradle project setup in the android/ folder.
```

**Comment by tvolkert** [comment]
Removing TODAY label since this shouldn't block internal rolls (it's already fixed at tip-of-tree).  I'm working on pushing a new beta release.

**Comment by xster** [comment]
+1 for pushing 0.1.5 to beta if it's ready

**Comment by xster** [comment]
Added 0.0.23-0.1.4 to https://github.com/flutter/flutter/wiki/Bad-Builds

**Comment by tvolkert** [comment]
v0.1.5 has been pushed to beta.
