### ISSUE TITLE
Get document from Cloud Firestore in Flutter

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#14919]
I was playing around with Firestore and Flutter and tried to extract a single doument value as a string from the Firestore database. 

`Firestore.instance.collection('channels').document('567890').get().toString()` didn't work, and just returned the value "Instance of '_Future' ". Is there already a solution available for the latest version of the cloud_firestore plugin and if so, how would I have to modify my code in order to query the document value as a string?

**Comment by rmtmckenzie** [comment]
As per the source code [here](https://github.com/flutter/plugins/blob/dacb895b17f478092e2a476fe04176f8bffe3897/packages/cloud_firestore/lib/src/document_reference.dart#L51), document.get() returns a Future not a String. This is because it is an async operation (as could be expected if firestore has to get the value from the cloud).

I recommend taking a look at the [dart documentation](https://www.dartlang.org/tutorials/language/futures) for Async and await. Your code should look like:
```dart
Firestore.instance.collection('channels').document('567890').get().then((string) {
  ... do whatever you need to do
}));
```
or within an async function
```dart
Future function() async {
  String result = await Firestore.instance.collection('channels').document('567890').get();
  ... do whatever.
}
```
Note that if you're calling this from within initState, you can't make it async as it seems to cause problems. Instead make an async function that you call from initState.

Also, you'd probably get quicker responses about this type of thing (i.e. not an actual bug with flutter but rather a problem you're having) from stackoverflow, the realtime chat channel, or the google group mailing list. See [here](https://flutter.io/support/) for links.

**Comment by cbracken** [comment]
@rmtmckenzie 's got it! Thanks!

**Comment by stemuk** [comment]
@rmtmckenzie Thanks a lot for your in-depth explanation!

**Comment by rmtmckenzie** [comment]
@stemuk Ah sorry, missed that. 
To extract values, you can either use something like `documentSnapshot['channelName']` or `documentSnapshot.data['channelName']`. Although not required, it's probably advisable to check the type of the value you're pulling out of the snapshot.

Something like 
```dart
Future<String> getChannelName() async {
  DocumentSnapshot snapshot= await Firestore.instance.collection('channels').document('567890').
  var channelName = snapshot['channelName'];
  if (channelName is String) {
    return channelName;
  } else {
    throw ......
  } 
}
```
or
```dart
Firestore.instance.collection('channels').document('567890').get().then((docSnap) {
  var channelName = snapshot['channelName'];
  assert(channelName is String);
  return channelName;
}));
```

**Comment by stemuk** [comment]
Thank you very much for the added explanation @rmtmckenzie , this really helped a lot!

**Comment by RamSamarthPaliwal** [comment]
Thank you very much, you saved me a fortune.!!!!!

**Comment by Sreejith93** [comment]
> @stemuk Ah sorry, missed that.
> To extract values, you can either use something like `documentSnapshot['channelName']` or `documentSnapshot.data['channelName']`. See [the docs](https://www.dartdocs.org/documentation/firebase_firestore/0.0.1%2B1/firebase_firestore/DocumentSnapshot-class.html). Although not required, it's probably advisable to check the type of the value you're pulling out of the snapshot.
> 
> FYI - in lots of these sorts of situations the quickest way to figure out what's going on is to just click on the type (i.e. DocumentSnapshot, assuming you're using intellij although I'm pretty sure VS code will do the same) and look at the source code - you'll find that most flutter/dart source is fairly simple & self-explanatory, and it'll help you learn how things are done in dart 😃.
> 
> Something like
> 
> ```dart
> Future<String> getChannelName() async {
>   DocumentSnapshot snapshot= await Firestore.instance.collection('channels').document('567890').
>   var channelName = snapshot['channelName'];
>   if (channelName is String) {
>     return channelName;
>   } else {
>     throw ......
>   } 
> }
> ```
> 
> or (assertions only run in debug builds so if you're reasonably confident that channelName will always be a string but still want that extra bit of security this is a good way to do things).
> 
> ```dart
> Firestore.instance.collection('channels').document('567890').get().then((docSnap) {
>   var channelName = snapshot['channelName'];
>   assert(channelName is String);
>   return channelName;
> }));
> ```

i got the data but i want pass the data into static const String url ="here";

here it is code


import 'dart:convert';
import 'package:http/http.dart' as http;
import './models/movie.dart';
import 'models/movies.dart';
import 'package:cloud_firestore/cloud_firestore.dart';



class Services {
  
  
  static const String url = 'i want to pass the $link here';
  static Future<Movies> getMovies()  async {
    
     Firestore.instance.collection('postman').document('FnlnlkEbBWGKo2SX1Fc8').get()
      .then((DocumentSnapshot ds) {
      var link = ds['link_data'];
      assert(link is String);
      print("link value: $link");
      return link ;
      });
     
    try {
            final response = await http.get(url);
      if (200 == response.statusCode) {
        return parseMovies(response.body);
      } else {
        return Movies();
      }
    } catch (e) {
      print('Error ${e.toString()}');
      return Movies();
    }
  }
  static Movies parseMovies(String responseBody) {
    final parsed = json.decode(responseBody).cast<Map<String, dynamic>>();
    List<Movie> movies = parsed.map<Movie>((json) => Movie.fromJson(json)).toList();
    Movies u = Movies();
    u.movies = movies;
    return u;
  }
}
