### ISSUE TITLE
Impossible to add XCFramework to flutter ios plugin

### ISSUE THREAD

**Issue by buehler** [flutter/flutter#149168]
### Steps to reproduce

Hi there,

I try to create a flutter ios plugin that ships with the PDFium binary inside. I tried multiple approaches now, and it seems to be impossible to get flutter and xcode to get the framework along with the plugin. I googled and tried for multiple days now and there is no real documentation (other than hello world examples) that show how to add external dependencies to ios plugins.

I tried with static libs, but then, the simulator is not supported.
I tried with xcframeworks, but then, xcode build does not find my framework.

I do not know how to proceed, it just seems impossible.

So:

1. Create the flutter plugin with platform ios
2. Download the pdfium framework from https://github.com/paulocoutinhox/pdfium-lib/releases/download/6276/ios.tgz
3. Extract the ios.tgz and find the .xcframework folder there
4. Copy the framework folder into the plugins /ios folder
5. Configure podspec with 
```
  s.vendored_frameworks = 'pdfium.xcframework'
  s.preserve_paths = 'pdfium.xcframework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework pdfium' }
  s.libraries = ['c++', 'z']
```
6. Try to run the project
7. Find an error "Error (Xcode): Framework 'pdfium' not found"

### Expected results

I expect that xcode takes the framework, since it is specified and links it to the plugin lib. I also found resources on how to configure the podspec to configure striping for non-global symbols only. But I'm not even there :)

### Actual results

The above mentioned error. No chance on running the project on the simulator or any real device so far.

### Code sample

None. There is no code in the plugin, just an external ref.

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running Xcode build...                                                  
Xcode build done.                                           12.7s
Failed to build iOS app
Error (Xcode): Framework 'pdfium' not found


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale en-CH)
    • Flutter version 3.22.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.16.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (3 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Users/xxx/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/xxx/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile)      • D608EF19-9F30-49DD-8931-D701418E9762 • ios          •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 14.5
      23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 14.5
      23F79 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @buehler, I see there's an open issue addressing the case you described at https://github.com/flutter/flutter/issues/86275. It's still open.

Closing this issue as a duplicate, so please follow up on it for further updates.

**Comment by buehler** [comment]
Hey @huycozy 

Thank you! Will follow the new issue then.
