### ISSUE TITLE
time picker dialog has scroll bar

### ISSUE THREAD

**Issue by adityasethipsi** [flutter/flutter#149154]
### Use case

I'm using flutter's showTimePicker method to show a time picker dialog to user. 

### Proposal

I'm using flutter's showTimePicker method to show a time picker dialog to user. In input text field, it shows scroll bar which is of now use. It should be visible based on a flag if needed in any use case or else can't it be removed.?

**Comment by adityasethipsi** [comment]
![image](https://github.com/flutter/flutter/assets/74599855/7a6c40d7-28bc-4f0f-8795-0a3af3dbd583)

**Comment by huycozy** [comment]
>It should be visible based on a flag if needed in any use case or else can't it be removed.?

Hi @adityasethipsi, could you be more specific on this? Please provide a minimal sample code that produces the case you have the issue (scrollbar is visible?) and Flutter version you are using as well. Thanks!

**Comment by adityasethipsi** [comment]
@huycozy I've already provide you with code sample

**Comment by huycozy** [comment]
Your sample code above is not minimal and also uses 3rd party package. I use a minimal sample code below and don't see the issue as your screenshot:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () {
            showTimePicker(
              initialEntryMode: TimePickerEntryMode.input,
              initialTime: TimeOfDay.now(),
              context: context,
            );
          },
          child: const Text('Show'),
        ),
      ),
    );
  }
}

```
</details>


<details>
<summary>Demo</summary>

![Screenshot 2024-06-19 at 11 55 26](https://github.com/flutter/flutter/assets/104349824/200f12b7-c16e-45b5-baef-1fffc2a0d0d4)

</details>

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample in [Quoting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

Also, you are using an old Flutter version. Please try upgrading to the latest stable version (3.22.2) to see if the results has changed or not.
