### ISSUE TITLE
[pigeon] C++ generated code doesn't handle null arguments of custom class type

### ISSUE THREAD

**Issue by russellwheatley** [flutter/flutter#149174]
### Steps to reproduce

I have a [reproduction repo here](https://github.com/russellwheatley/pigeon_bug_windows/tree/master).

Code uses url launcher windows package. I essentially updated the messages/pigeon.dart and regenerated the code. 

[This is the update](https://github.com/russellwheatley/pigeon_bug_windows/blob/master/pigeons/messages.dart#L14-L24)

In a nutshell, if an arg is nullable, and `null` is passed, it will crash the app. Here is where it [crashes in the code](https://github.com/russellwheatley/pigeon_bug_windows/blob/master/windows/messages.g.cpp#L110). Essentially, when it tries to parse the nullable value.

I have instructions in the README of the reproduction repo, but here they are for completeness:

1. Run `flutter build windows --debug` in `example/`
2. Open app on Visual Studio by opening the solution in `example/build/windows/x64/runner/runner.sln`
3. Put two break points on [these lines](https://github.com/russellwheatley/pigeon_bug_windows/blob/master/windows/messages.g.cpp#L110-L111). Note that it gets to the first line but will crash before getting to the second line.

This issue was found when implementing this feature on FlutterFire: https://github.com/firebase/flutterfire/pull/12825/files#diff-ad8aa9e593097c77254420c5c93cccbba4478ba947392296a18cceddc6068d85R4028-R4037

### Expected results

Not to crash when passing `null` as nullable argument.

### Actual results

Crashes in Pigeon generated [code on this line](https://github.com/russellwheatley/pigeon_bug_windows/blob/master/windows/messages.g.cpp#L110)

### Code sample

<details open><summary>Code sample</summary>

https://github.com/russellwheatley/pigeon_bug_windows/blob/master/README.md
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/16018629/779fd264-5a8e-4e00-8617-260d121a1e2a)

</details>

### Logs

<details open><summary>Logs</summary>

None.

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3593], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[!] Android Studio (not installed)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by stuartmorgan** [comment]
I thought we had tests covering every arg type both nullable and non-nullable, but it looks like we missed null custom class top-level arguments somehow.

I'll see if the custom codec PR fixes this; if so we can just track adding an integration test for this here.

**Comment by stuartmorgan** [comment]
> I'll see if the custom codec PR fixes this

It doesn't. I'll look at fixing this once the custom codec changes land.

In the short term, a workaround would be to wrap the nullable class in a non-nullable class whose only field is the nullable class.

**Comment by stuartmorgan** [comment]
I have a trivial fix, which I can land once custom codecs land.

**Comment by russellwheatley** [comment]
Thank you for the quick turn around, @stuartmorgan. I look forward to its release 🙏
