### ISSUE TITLE
Can't interact with app build for integration testing

### ISSUE THREAD

**Issue by saikrishna321** [flutter/flutter#149108]
### Use case

I have assemble a android app with integration test file. When I invoke the app on the device, i'm unable to manually interact with it. 

Is there a way to manually interact with the instrumented app? 

Command used to Build the app: ``./gradlew app:assembleDebug -Ptarget=/Users/xxx/Documents/git/personal/flutter-learnings/counter_app/integration_test/appium_server.dart``

### Proposal

I would like to interact with the integration debug app.

**Comment by bartekpacia** [comment]
Try setting [`TestWidgetsFlutterBinding.shouldPropagateDevicePointerEvents`](https://api.flutter.dev/flutter/flutter_test/TestWidgetsFlutterBinding/shouldPropagateDevicePointerEvents.html) to true

**Comment by huycozy** [comment]
@bartekpacia Thanks for pointing this out. Just found it's mentioned here https://github.com/flutter/flutter/issues/103288#issuecomment-1812710859 as well :D. 

@saikrishna321 There is already a detailed proposal at https://github.com/flutter/flutter/issues/103288. You can follow it for updates and also try enabling the flag as @bartekpacia mentioned above to see if it helps. 

Closing this as a duplicate.

**Comment by saikrishna321** [comment]
@bartekpacia @huycozy Thanks for quick response. I did try and doesn't work. Below is the code. Am I missing something?



```
void main() {
  final IntegrationTestWidgetsFlutterBinding binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  binding.shouldPropagateDevicePointerEvents = true;
  WidgetsFlutterBinding.ensureInitialized();
  testWidgets('Should be able to login and navigate to home screen',
      (WidgetTester tester) async {
    app.main();
    await tester.pumpAndSettle();
    expect(find.byType(MaterialApp), findsOneWidget);
  });
}
```

**Comment by bartekpacia** [comment]
You can also try setting `pointerEventSource` ([example](https://github.com/leancodepl/patrol/blob/1106243f6915c4c7eefacb1776f27316d079e476/packages/patrol/lib/src/binding.dart#L168-L180))
