### ISSUE TITLE
Session not created ('Chrome For Testing' browser)

### ISSUE THREAD

**Issue by smcke** [flutter/flutter#149171]
### Steps to reproduce

1. Install CfT (Chrome for Testing) browser at  "C:\chrome-win64\chrome"  & install corresponding chromedriver at "C:\chromedriver-win64\chromedriver"
2. Run  $env:CHROME_EXECUTABLE = "C:\chrome-win64\chrome" 
3. Now run Flutter drive command with test files

### Expected results

Expected CfT browser to be launched without errors

### Actual results

CfT browser launches and test starts to run but then flutter crashes. From the logs it seems like the correct chromedriver is used but flutter is matching it against my original (non CfT) Chrome browser and getting a mismatch in the versions.

### Code sample

<details open><summary>Code sample</summary>

```flutter drive --driver=..\..\test_driver\integration_test.dart --target=..\..\integration_test\test.dart -d chrome --web-port=8080
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
SessionNotCreatedException (33): session not created: This version of ChromeDriver only supports Chrome version 122
Current browser version is 125.0.6422.77 with binary path C:\Users\Steven.McKenna\AppData\Local\Google\Chrome\Application\chrome.exe
  (Driver info: chromedriver=122.0.6261.111 (9d4c1072da62b411b351a38b9ed6214ab236aa7b-refs/branch-heads/6261@{#1015}),platform=Windows NT 10.0.22631 x86_64)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.22631.3593], locale en-GB)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.32)
[!] Android Studio (not installed)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@smcke 
As the error indicates, you will need to be on chrome version 122 or higher in order for chromedriver to work.
Also, you are on obsolete version of stable. You also need to upgrade it to latest version and upgrade your setup to latest for your case to run properly.

Closing for now.

**Comment by smcke** [comment]
@darshankawar the error shows that I am on version 125 of Chrome (although Flutter is mistakenly referencing my standard Chrome Browser version) but I set the CHROME_EXECUTABLE to point to my CfT browser which is version 122 and exactly matches the chromedriver being used. Can you tell me where I can see what versions of Flutter are obsolete?

**Comment by smcke** [comment]
@darshankawar I know you were referring to that but I wanted to see confirmation that this version is "obsolete" as it will strengthen my case for us to upgrade. The Flutter console told me to raise this bug, but it seems our only route is to upgrade Flutter and hope it's fixed.

**Comment by darshankawar** [comment]
Looks like it is similar to https://github.com/flutter/flutter/issues/141010 that you can check and share your findings in, for better tracking.
