### ISSUE TITLE
Rendering characters not within regular character set results in oversized glyphs

### ISSUE THREAD

**Issue by tmbenhura** [flutter/flutter#14915]
## Steps to Reproduce
Create a Text widget with string containing ●

`new Text('●●●●●',)
`

This occurs when using the **master** branch, this problem does **NOT** occur on the current v0.1.6 dev branch.

## Flutter Doctor
```
[√] Flutter (Channel master, v0.1.7-pre.5, on Microsoft Windows [Version 10.0.15063], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Community Edition (version 2017.2)
[√] Connected devices (1 available)
```

**Comment by jason-simmons** [comment]
We are in the process of rolling out a new text rendering engine that replaces the original Blink-based text renderer.  The new renderer uses different rules for choosing fallback fonts when the primary font does not cover a character.

If you need control over font selection, apply a TextStyle that explicitly specifies the font family.

**Comment by tmbenhura** [comment]
I'd assume that the font covers the character, since I'm using the default engine font.

**Comment by GaryQian** [comment]
We have since completely switched text backends. Please let us know if you are still seeing this. If not, this issue should auto close.

**Comment by tmbenhura** [comment]
It is not rendering correctly, thank you.
