### ISSUE TITLE
Stuck cannot download flutter engine

### ISSUE THREAD

**Issue by fahmifan** [flutter/flutter#14910]
I have cloned the flutter repo following the installation guide for windows. After running flutter doctor it stucked in. 
```
> flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
```

**Comment by cbracken** [comment]
Two questions:
1. Does running again solve the issue for you?
2. Do you see a download progress bar showing at the top of your terminal?

**Comment by Norbert515** [comment]
After having this issue https://github.com/flutter/flutter/issues/14515, I deleted the flutter folder and re-cloned it. When I run any flutter command, it gets stuck. Running again does not resolve the issue, and I see no download progress, in fact, the terminal process is completely idle.

**Comment by fahmifan** [comment]
Yesterday I tried clone the repo again and run flutter doctor and it worked, both on my windows 10 & Ubuntu.

**Comment by 554512097** [comment]
i have same problem

**Comment by Norbert515** [comment]
I fixed the issue by installing a Windows 10 update. Honestly no idea what the problem was.

**Comment by Hixie** [comment]
If you are still seeing this, two questions:
1. Are you using the "Charles Web Debugging Proxy" ?
2. Do you still see the problem if you install flutter but instead of using "beta" you use "master"?

**Comment by 554512097** [comment]
I have opened my proxy,but it faild

**Comment by mahdiutshob** [comment]
I have a same **Problem**

**Comment by f0rx** [comment]
Any fix yet on this issue?
