### ISSUE TITLE
Determining graphical capabilities, or number of GPUs

### ISSUE THREAD

**Issue by tmbenhura** [flutter/flutter#14917]
Is it possible to determine graphical capabilities, and if power saving is enabled for a device? Especially for those of us that develop apps for emerging markets.

This allows for performance responsive animations, either at engine level or at programming level.

Possibly Media query, for example:

`MediaQuery.of(context).graphics`

returning a GraphicsLevel enum none, low, high, extreme

**Comment by rmtmckenzie** [comment]
I don't know that there's even an Android api for that - if there is though, that's something you could conceivably write a plugin/methodchannels for yourself. I'll let someone from the flutter team respond as to whether they have any interest in that.

For the record though, I've thrown some fairly complex animations (i.e. many rotating lines with an animated blur filter while pages flipping) at a moderately low-powered device (for nowadays anyways - alcatel idol X) and it responded a whole lot better than some of the animations I've done with android previously, so are you sure this is significant issue? If you are seeing major performance issues (in release mode!) then you should probably raise that as a bug and let the flutter guys look at it or change your animations to be a little less intensive.

Your other option would be to use the [deviceInfo plugin](https://github.com/flutter/plugins/tree/master/packages/device_info) and make decisions based on android version or something. See [here](https://www.dartdocs.org/documentation/device_info/0.1.1/device_info/AndroidDeviceInfo-class.html) for the list of information you can get about an android device.

**Comment by cbracken** [comment]
As @rmtmckenzie a plugin is exactly what you'd want to implement for this sort of thing.
