### ISSUE TITLE
[url_launcher] token header not working on Android

### ISSUE THREAD

**Issue by faFrafa** [flutter/flutter#149175]
### What package does this bug report belong to?

url_launcher

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
```

</details>

### Steps to reproduce

Using the code from url_launcher example and replace _launchInWebView with the following code (to include headers with a valid JWT):

  ```
Future<void> _launchInWebView(Uri url) async {
    try {
      await launchUrl(url, mode: LaunchMode.inAppWebView,
          webViewConfiguration: WebViewConfiguration(
              headers: {
                "content-type": "application/json",
                "Authentication": "Bearer $token" // token stores the JWT received from the initial SSO 
              }
          ));
    } on Exception catch (e) {
      if (kDebugMode) print(e.toString());
    }
  }
```

### Expected results

My app provides a login to an SSO provider and stores the associated JWT. Each time it needs to open a url as LaunchMode.inAppWebView, that requires this JWT, it passes the needed headers in a WebViewConfiguration.

The url should open directly without re-asking to login, which is the case for the Flutter Web version.
But for Android and iOS this doesn't work. The SSO login page shows up again.

The url should be opened directly as a logged in user (skipping the login page), because the launch call included the JWT.
This happens only in the Flutter web version, but it's not the case for Android simulator/device and iOS simulator (didn't test on iOS device).

### Actual results

The url webview page opens showing the login page, ignoring the JWT sent via the headers.

### Code sample

<details open><summary>url_launcher and replacing following function</summary>

```dart
Future<void> _launchInWebView(Uri url) async {
    try {
      await launchUrl(url, mode: LaunchMode.inAppWebView,
          webViewConfiguration: WebViewConfiguration(
              headers: {
                "content-type": "application/json",
                "Authentication": "Bearer $token" // token stores the JWT received from the initial SSO 
              }
          ));
    } on Exception catch (e) {
      if (kDebugMode) print(e.toString());
    }
  }
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @faFrafa 
Do you get any logs while it redirects to login screen ?

**Comment by darshankawar** [comment]
@faFrafa 
Since you are passing `headers`, I think it only works for Android and not iOS. I remember reading it in package's documentation if I am not mistaken (ex: launch method) . Is it possible for you to try using [query strings](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/passing-information-through-query-strings/) instead and see if it helps in your case ?

**Comment by faFrafa** [comment]
Are you sure JWT can be sent as a query? JWT standard doesn't strictly require the 'Authentication' header with value 'Bearer token_value'?

BTW, if you say that headers work for Android, the issue is also with Android (both simulator and device).

**Comment by darshankawar** [comment]
Thanks for the update. I'll keep the issue open and label for team's input on reported behavior.

**Comment by stuartmorgan** [comment]
This is not supported on iOS; it should work on Android, so redirecting for investigation at the Android implementation level.

**Comment by reidbaker** [comment]
Is this a regression? if so what version worked before? 

The answers will help whoever goes to fix this issue.
