### ISSUE TITLE
Don't overwrite the icon theme in CupertinoButton

### ISSUE THREAD

**Issue by ricardoboss** [flutter/flutter#149172]
### Use case

I have a widget that shows a row of buttons and I want to apply an `IconTheme` to them for setting their size.

Currently, I have to set the size for each icon within each button individually, because the `CupertinoButton` widget overwrites any `IconTheme` provided above it in the tree.

### Proposal

I'd like to propose that the `build` method in `_CupertinoButtonState` uses `IconTheme.of(context).copyWith(color: foregroundColor)` to set the theme instead of just `IconTheme(color: foregroundColor)`.

This way, it sets the correct color but also incorporates any parent styles.

**Comment by ricardoboss** [comment]
@darshankawar @Piinks Is the proposal alright with you? Can I try take a stab at implementing this?

**Comment by darshankawar** [comment]
@ricardoboss Feel free to raise a PR. The team can give feedback if any while reviewing it.
