### ISSUE TITLE
Failed to launches my Flutter WASM compiled web app (WebAssembly.compileStreaming() Compiling function failed

### ISSUE THREAD

**Issue by flrnsbt** [flutter/flutter#149128]
### Steps to reproduce

flutter run -d chrome --debug --wasm with 3.23.0-6.0.pre

### Expected results

App to launches

### Actual results

```console
CompileError: WebAssembly.compileStreaming(): Compiling function #12911:"Something.refresh" failed: ref.eq[0] expected either eqref or (ref null shared eq), found i32.const of type i32 @+4979240
```

### Code sample

<details open><summary>Code sample</summary>
I have an abstract class similar to this:

```dart
abstract class Something{

void refresh({bool forceFromServer = false, bool flushData = true}) {
    assert(event != null, 'You tried to refresh, but the last event is null');
   /// some code
  }
}
```

This class is extended in several parts of my application, and I have a mixin that changes the method signature, to add an optional third parameter. I thought the reason might be this, because it seems to be the only error I get, and the only part where I do such a thing. But after removing my mixin, the error was still there.

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
florian@ubuntuflorian:~/flutter$ flutter doctor -v
[!] Flutter (Channel [user-branch], 3.23.0-7.0.pre, on Ubuntu 23.10 6.5.0-35-generic, locale en_US.UTF-8)
    ! Flutter version 3.23.0-7.0.pre on channel [user-branch] at /home/florian/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 734d243bc8 (3 days ago), 2024-05-25 05:38:08 +0800
    • Engine revision b5e98f9b8d
    • Dart version 3.5.0 (build 3.5.0-189.0.dev)
    • DevTools version 2.36.0-dev.10
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/florian/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/florian/Android/Sdk
    • Java binary at: /home/florian/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (version unknown)
    • Android Studio at /home/florian/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.89.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-35-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.```

</details>

**Comment by mraleph** [comment]
cc @osa1 @mkustermann

**Comment by flrnsbt** [comment]
My app starts properly with a build on stable. Except that I get a JavascriptError. I wanted to debug it with flutter run, but the wasm compilation never worked.

**Comment by osa1** [comment]
Is is possible for you to share a full repro? It's OK if it's large as long as it reproduces the issue.

**Comment by flrnsbt** [comment]
Unfortunately I can't share any code, but I will try to isolate it, when I have more time.

**Comment by dhruvpatidar359** [comment]
https://github.com/dart-lang/sdk/issues/55872  I am getting the same issue . Everything is attached with this (Also consist of Repo link)

**Comment by mkustermann** [comment]
> Steps to reproduce
> ```
> flutter run -d chrome --debug --wasm with 3.23.0-6.0.pre
> ```

This doesn't work - as one can only use `--wasm` in `flutter build`. For me running the above returns in this error
```
Could not find an option named "wasm".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

Are you sure you got this error by running `flutter run -d chrome --debug --wasm`?

> ```
> WebAssembly.compileStreaming(): Compiling function #12911:"Something.refresh" failed:
>     ref.eq[0] expected either eqref or (ref null shared eq), found i32.const of type i32 @+4979240
> ```

There's clearly some invalid wasm being generated. It's somewhat surprising given that `flutter build --wasm` normally runs a wasm2wasm optimizer which should complain about such type errors at compile-time.

Can we get access to the generated `.wasm` file (ideally compiled with `flutter build web --wasm -O1`)?


> This class is extended in several parts of my application, and I have a mixin that changes the method signature, to add an optional third parameter. I thought the reason might be this, because it seems to be the only error I get, and the only part where I do such a thing. But after removing my mixin, the error was still there.
> 
> Unfortunately I can't share any code, but I will try to isolate it, when I have more time.

I tried certain code with overriding methods and adding optional parameters, but was unable to trigger any such issue. I think we need a reproduction for it or at least more information (e.g. the function body and class hierarchies)

@flrnsbt If you can provide us with a reproduction we'd be very happy to investigate.
