### ISSUE TITLE
3.22.1 does not support win7

### ISSUE THREAD

**Issue by yiky84119** [flutter/flutter#149124]
### Steps to reproduce
flutter_windows.dll depends GetHostNameW 
无法定位程序输入点 GetHostNameW 于动态链接库 WS2_32.dll 上。 

### Expected results

support win7

### Actual results

not support win7

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![image](https://github.com/flutter/flutter/assets/3356845/ab484d14-1cad-43f2-8011-f48de34ef54a)
![image](https://github.com/flutter/flutter/assets/3356845/fdcbe539-ce43-4ebd-aa53-29342d38b08b)

### Logs

<details open><summary>Logs</summary>

```console
PS C:\Users\nevol\StudioProjects\untitled> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [版本 10.0.22631.3593], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.7)
[√] Android Studio (version 2023.3)
[√] IntelliJ IDEA Ultimate Edition (version 2024.1)
[√] Connected device (4 available)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by LimaneGaya** [comment]
@yiky84119  Flutter dropped support for windows 8 and 7 with [release 3.19](https://medium.com/flutter/whats-new-in-flutter-3-19-58b1aae242d2), see [current supported platforms](https://docs.flutter.dev/reference/supported-platforms).

**Comment by bartekpacia** [comment]
see https://github.com/flutter/flutter/issues/149124#issuecomment-2133101178
