### ISSUE TITLE
[CP] Refactor route focus node creation

### ISSUE THREAD

**Issue by techouse** [flutter/flutter#149178]
### Issue Link

https://github.com/flutter/flutter/issues/148867

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/149378

### Changelog Description

Refactor route focus node creation

### Impacted Users

iOS users on Flutter stable 3.22.0 and 3.22.1

### Impact Description

Unable to focus on TextField or open the keyboard again after side pop from another screen on iOS.

### Workaround

Stay on 3.19.6 or use tags 3.22.0-19.0.pre and above

### Risk

low

### Test Coverage

yes

### Validation Steps

- #### Flutter stable 3.22.0, 3.22.1; tag 3.22.0-18.0.pre and below
  - run an app with a TextField on iOS
  - tap into TextField
  - keyboard opens
  - navigate to a separate screen
  - swipe back (this is important)
  - tap into TextField
  - keyboard does not open
- #### Flutter tag 3.22.0-19.0.pre and above
  - run an app with a TextField on iOS
  - tap into TextField
  - keyboard opens
  - navigate to a separate screen
  - swipe back (this is important)
  - tap into TextField
  - keyboard opens

**Comment by jmagman** [comment]
@justinmc @chunhtai I'm not sure if this is the right thing to cherry-pick, or instead it should be to fix forward to https://github.com/flutter/flutter/pull/147607.  Could you take a look at the regression and test it out?

**Comment by justinmc** [comment]
It looks like the actual PR that we would cherry pick is https://github.com/flutter/flutter/pull/147607, is that right @chunhtai?  Also, are we sure that that is what fixes https://github.com/flutter/flutter/issues/148573 @techouse?

**Comment by chunhtai** [comment]
> It looks like the actual PR that we would cherry pick is https://github.com/flutter/flutter/pull/147607

I think in order to cherry pick the reapply, you will need to cherry pick the revert first right?

it seems like the release only contains the problematic popscope commit but not the revert and reland? if so we can either cherry pick the revert or both the revert and reland, I am fine with either one.

**Comment by chunhtai** [comment]
actually it may be better to cherry pick both because the breaking change is already out with the problematic popscope commit, we don't want them to do it twice

**Comment by techouse** [comment]
> Also, are we sure that that is what fixes https://github.com/flutter/flutter/issues/148573 (and/or https://github.com/flutter/flutter/issues/148867) @techouse?

As stated above in https://github.com/flutter/flutter/issues/149178#issuecomment-2135340355, I tested with 11 versions, including one before and one after the fix. If you want I can do some additional testing, but it seems more than likely that this is the fix/cause.

**Comment by chunhtai** [comment]
I am new to the process, may I know which branch I should create the cherry pick against?

**Comment by chunhtai** [comment]
actually this looks weird, the stable doesn't have the popscope change, something else is at play.

**Comment by chunhtai** [comment]
This should be the commit that fixes the issue
https://github.com/flutter/flutter/pull/147390

can you verify? if it indeed is, we should change the this issue title and description

cc @gspencergoog

**Comment by techouse** [comment]
> This should be the commit that fixes the issue #147390
> 
> can you verify? if it indeed is, we should change the this issue title and description
> 
> cc @gspencergoog

@chunhtai You're right! It does look like https://github.com/flutter/flutter/pull/147390 is the **real** fix. I somehow I compared it in reverse, https://github.com/flutter/flutter/compare/3.22.0-19.0.pre...3.22.0-18.0.pre instead of https://github.com/flutter/flutter/compare/3.22.0-18.0.pre...3.22.0-19.0.pre 🤦 and the sheer quantity of `PopScope`s got me.

I'll change the CP description now.

**Comment by gspencergoog** [comment]
Yes, I consider this low risk.  The `ListenableBuilder` part doesn't change functionality at all, and the `withExternalFocusNode` part is the bug fix, and has very similar functionality to the original code, but will not overwrite the `skipTraversal` and other attributes of the node when they are out of sync with the Focus widget. The effect of the change should be local to this widget and its `FocusScopeNode`.

**Comment by JosephNK** [comment]
This issue seems to require a hotfix. It is a big problem that text fields do not work properly in released apps.

**Comment by lukemmtt** [comment]
This issue should be closed; the hotfix is live in Flutter 3.22.2 
- https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md#3222-june-06-2024

Thank you @techouse and all others who helped troubleshoot and fix this! 🚀
