### ISSUE TITLE
ccache support is gone in the latest version of Buildroot.

### ISSUE THREAD

**Issue by bc-lee** [flutter/flutter#149100]
### Proposal

ccache support was removed in Buildroot: https://github.com/flutter/buildroot/pull/858

For Googlers, goma or the RBE can be used for remote compilation & caching. However, as a non-google employee, I don't have access to those services. Instead, I've used ccache to speed up my builds for various projects, including Flutter.

Reintroducing ccache support in the build process would be straightforward and wouldn't break existing functionality.

**Comment by jonahwilliams** [comment]
We didn't know that the ccache support actually worked.

**Comment by bc-lee** [comment]
Actually, it worked until recently. Could you review my changes to see if the RBE workflow still functions as expected?
