### ISSUE TITLE
[google_maps_flutter] setMapStyle should not be deprecated

### ISSUE THREAD

**Issue by ozzy1873** [flutter/flutter#149109]
### Use case

I need to be able to change map styles dynamically without recreating the GoogleMap widget.

### Proposal

It is OK to keep the new GoogleMap style property, but do not deprecate the existing setMapStyle method.

**Comment by stuartmorgan** [comment]
> I need to be able to change map styles dynamically without recreating the GoogleMap widget.

Why do you need this? Please describe the use case itself, not the proposed solution. Recreating widgets is the standard way to change properties in Flutter.

**Comment by ozzy1873** [comment]
I refactored to use only the new style property.
