### ISSUE TITLE
[website/Cookbook] A code of "Complete Example" look the same

### ISSUE THREAD

**Issue by qt-luigi** [flutter/flutter#14914]
A code of "Complete Example" on both "Basic List" and "Create a horizontal list" look the same to me.

"Basic List": https://flutter.io/cookbook/lists/basic-list/
"Create a horizontal list": https://flutter.io/cookbook/lists/horizontal-list/

I think that "Create a horizontal list" mistaken an inner code of ListView.
I think that a correct ListView code is above of same page...What do you think?

**Comment by brianegan** [comment]
Oh dang, I did mess that up! I'll fix it up.

**Comment by qt-luigi** [comment]
Hello brianegan, I am happy that I could help you! Please fix it.

**Comment by brianegan** [comment]
Fixed by https://github.com/flutter/website/pull/822

**Comment by qt-luigi** [comment]
Thanks for fixing me! I will close this issue when your PR is merged.

**Comment by brianegan** [comment]
Sounds good, I'll ping you on this thread when it's merged up!

**Comment by cbracken** [comment]
Awesome - thanks for the PR @brianegan !

**Comment by qt-luigi** [comment]
Hi, @brianegan ! I checked that this issue merged to the Flutter Cookbook page! This issue close. Thank you!
