### ISSUE TITLE
Make flutter tool alert the user when an upgrade is available

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14920]
For users who're on the `beta` channel, (or in the future, `release`), we should consider making the flutter tool automatically notify the user that a newer version is available and point them toward `flutter upgrade`.

**Comment by tvolkert** [comment]
Note that this means we should also _stop_ notifying the user to upgrade purely based on how old their current release is.  This already breaks down in beta, and it'll break down horribly when we get to 1.0.

**Comment by DanTup** [comment]
I think to implement this now that #18016 is merged, all we need to do is reduce the minimum period for checking updates. Currently it waits until you're 30(?) days old, then checks the remote for your branch and shows the warning. If we reduced that period to just a few days, then people will get relatively-timely update notifications?

**Comment by DanTup** [comment]
Actually, we might want to do more... If we reduce the update check to after 7 days and then fail to get updates (eg. network issue), they might see the prompt much sooner. So we may want two periods:

1. How often to check for updates
2. How old the version has to be before we warn the user *if we can't verify whether there's a new version*

**Comment by tvolkert** [comment]
@DanTup that SGTM

**Comment by Hixie** [comment]
@DanTup please assign bugs to yourself when you're working on them, thanks!
