### ISSUE TITLE
[PAGE ISSUE]: 'Manage plugins and dependencies in add-to-app'

### ISSUE THREAD

**Issue by Ottovonbismark1** [flutter/flutter#149243]
### Page URL

https://docs.flutter.dev/add-to-app/android/plugin-setup/

### Page source

https://github.com/flutter/website/tree/main/src/content/add-to-app/android/plugin-setup.md

### Describe the problem

in this page it descripes the dependencies section existing in the <project>/android/build.gradle inside buildscripts
but that section does no longer exist it's moved to settings.gradle ? i guess i don't understand yet and am stock at this problem how to add what used to be added to that section now ???

### Expected fix

it should be fixed by providing the way of how to add things that are used to be added to <project>/android/build.gradle  
buildscripts{dependencies:{}} section that is no longer exist 

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
@Ottovonbismark1 Perhaps this is related to breaking change [Deprecated imperative apply of Flutter's Gradle plugins](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply) that you can check to see if it helps.
