### ISSUE TITLE
Shared preferences plugin crashes when using --preview-dart-2

### ISSUE THREAD

**Issue by alextekartik** [flutter/flutter#14921]
## Steps to Reproduce

Open the project https://github.com/flutter/plugins/tree/master/packages/shared_preferences

Ubuntu 16.04, Dart beta 2.0.0-dev27

## Logs

Run your application with `flutter run` and attach all the log output.

```
No errors, application works fine
```

Run `flutter analyze` and attach any output of that command also.

```
No issues found!
```

Run your application with `flutter run --preview-dart-2` and attach all the log output.

```
I/flutter ( 5976): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5976): The following assertion was thrown building FutureBuilder<SharedPreferences>(dirty, state:
I/flutter ( 5976): _FutureBuilderState<SharedPreferences>#a5895):
I/flutter ( 5976): type '_InternalLinkedHashMap' is not a subtype of type 'Map<String, Object>' where
I/flutter ( 5976):   _InternalLinkedHashMap is from dart:collection
I/flutter ( 5976):   Map is from dart:core
I/flutter ( 5976):   String is from dart:core
I/flutter ( 5976):   Object is from dart:core
I/flutter ( 5976): 
```

Run `flutter analyze --preview-dart-2` and attach any output of that command also.

```
No issues found!
```

## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel beta)
    • Flutter version 0.1.4 at /media/ssd/dev_tool/flutter
    • Framework revision f914e701c5 (8 days ago), 2018-02-19 21:12:17 +0000
    • Engine revision 13cf22c284
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /opt/apps/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /opt/apps/android-sdk-linux
    • Java binary at: /opt/app/android-studio-3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/app/android-studio-3
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/apps2/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[!] IntelliJ IDEA Ultimate Edition (version 2016.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.1.2
    • Dart plugin version 173.4548.30

[!] IntelliJ IDEA Community Edition (version 2016.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 163.13137
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[!] IntelliJ IDEA Community Edition (version 2016.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 162.2485
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[!] VS Code (version 1.20.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 4 categories.
```

**Comment by mraleph** [comment]
Thanks for the report! https://github.com/flutter/plugins/pull/392 should fix it. It also explains why this particular issue is happening. 

Channels don't preserve type arguments, so if you send `Map<String, dynamic>` across the channel you still get `Map<dynamic, dynamic>` on the receiving side. 

In Dart 1 `dynamic` was a treated as a so called *bottom type*, that is a type that is a subtype of anything else, so `Map<dynamic, dynamic>` is a subtype of `Map<String, dynamic>` so an assignment like 

```dart
Map<String, dynamic> foo = new Map<dynamic, dynamic>{};
```

would succeed in Dart 1. 

In Dart 2 `dynamic` is no longer a bottom type - which means `Map<dynamic, dynamic>` is not a subtype of `Map<String, dynamic>`. Ultimately it means that assignment like the one above would fail in runtime with an error.

Hope this explanation helps!

**Comment by alextekartik** [comment]
Thanks for the explanation. I had to make some weird wrapping to convert a plugin `List<Map<String, dynamic>>` in my own plugin. I would expect that other plugins might break too, especially when expecting complex object.

**Comment by rfuhrer** [comment]
Is there a reason that these errors aren't found at compilation time instead of runtime?  Seems like the goal of strong typing was to find bugs, but now I just have an app that is more likely to blow up at runtime than it was before due to type checking rather than actual type errors.

**Comment by mraleph** [comment]
> I had to make some weird wrapping

@alextekartik is your plugin open-source? can you point me to the weird wrapping you had to make? we are trying to gauge if platform channels APIs should be amended to try and preserve type arguments for containers like `List` and `Map` given changes in Dart 2 semantics. Also it is important to evaluate if core library is helpful enough to make conversions simple (/fyi @leafpetersen) 

> Is there a reason that these errors aren't found at compilation time instead of runtime?

@rfuhrer assigning expression of type `Map<dynamic, dynamic>` to a variable of type `Map<String, dymamic>` is an *implicit downcast*, those are not reported as errors unless you tell analyzer to do so, e.g. by adding `implicit-casts: false` to your `analysis_options.yaml`:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

*Implicit casts* exist to ease mixing static and dynamic code, and also ease migration from less static world to a more static world. It can very well be that we need to tighten up the rules for implicit casts in the future to catch this sort of problems early. Maybe we can tighten rules locally for specific functions (e.g. message channels are known problematic in Flutter). 

@leafpetersen might be able to provide more information here.

**Comment by alextekartik** [comment]
@mraleph Yes my plugin is sqflite. Here https://github.com/tekartik/sqflite/blob/master/lib/src/sqflite_impl.dart#L22-L33 you can see where I had to create a `Rows` class to map a native `List` map to a `List<Map<String, dynamic>` only for dart2

**Comment by rfuhrer** [comment]
@mraleph Thanks for the info.  I'm still kind of confused, so implicit casts exist to ease mixing static and dynamic code, but then it still blows up at runtime anyways? Or it only blows up in certain cases and that's maybe where you can look at improving the analyzer?

Just based on how trying out the dart 2 preview went for me, maybe this `analyzer: strong-mode: implicit-casts: false` setting should be in the https://github.com/flutter/flutter/wiki/Trying-the-preview-of-Dart-2-in-Flutter or https://www.dartlang.org/dart-2#testing page.  

Here's an emoji based re-enactment of my experience
"Try out Dart 2! It's got all this cool stuff!" - 🤔 
"you can run this analyzer to tell what you need to update" - 🙂 
"dart-code already supports it, just add this setting" - 😃 
"run with `--preview-dart-2` and you're done!" - 😄 
"Also, the sqflite library is going to crash with runtime errors" - 😑 
"@alextekartik : I fixed it!" - 🎉 😄 🎉 
"Also your own code is going to crash with runtime errors that we aren't showing you in the analyzer" - 😞

**Comment by mraleph** [comment]
@rfuhrer It is true that some valid Dart 1 code is gonna throw a runtime error in Dart 2 mode. I would expect this to be happening mostly around things like containers (where you were using `List<dynamic>` as if it was a `List<int>` without any _static_ guarantees) and functions (where you used to pass `(int) => ...` to places that expect `(dynamic) => ... `). Previous things worked, but could have failed at runtime at any time - if you made a mistake somewhere. Now Dart 2 actually forces you to guarantee these things or refuses to access the code. This is needed to tighten type system making it sound.

I will leave it to @leafpetersen (who is co-leading Dart Language Design) to explain why this was necessary.

Keep in mind that analyzer in general can't predict whether some cast succeeds of fails, e.g. this is perfectly valid code:

```dart 
// Somewhere deep in framework implementation
Map<dynamic, dynamic> makeItRain() {
  return new Random().nextBool() ? new Map<String, dynamic>() : new Map<int, dynamic>();
}

// Your code.
final Map<String, dynamic> map = makeItRain();
```

Analyzer at most can tell you that you need to cast result of `makeItRain()` explicitly (if you forbid implicit downcasts via analyzer options), but it might still fail in runtime.

**Comment by leafpetersen** [comment]
The Dart 2 type system tries to accommodate existing Dart 1 code as much as possible: hence covariant generics, implicit downcasts, etc.  To still allow us to have the property that we want (that is, that if something has static type `int`, we know that any value that we get at that program location will in fact be an `int` (or `null`, *sigh*)), this means runtime checks.

You can move more of them to compile time using `implicit-casts:false`.  You can also experiment with `implicit-dynamic:false`, but many people currently find this too noisy, and we will probably iterate on that.

Some resources:
https://www.dartlang.org/guides/language/sound-faq
https://www.dartlang.org/guides/language/sound-dart
https://www.dartlang.org/guides/language/sound-problems
https://www.dartlang.org/dart-2

**Comment by rfuhrer** [comment]
As a C# guy who moved to Typescript/Angular a few years ago, I'm all about the type safety.  I'm a big fan of you guys moving in that direction.

When I look at your example code, I think the analyzer should really be raining on the makeItRain parade as you are doing an unsafe cast. Dealing with android/ios/whatever 3rd party libraries and services, you definitely need some way to cast a dynamic down to what you know it actually is, but I think that should be explicit.  Those I expect to blow up at runtime if you're wrong in your explicit cast.  

If the "implicit-casts:false" option causes the analyzer to behave this way then I'd argue it should be on by default in dart 2, otherwise you're just going to confuse new dart users as they write code and don't get any help from the analyzer until their app blows up in their face.

If would be cool to steal from Typescript and have "multiple types" possible like this:
```dart
Map<dynamic, dynamic> makeItRain() {
  return new Random().nextBool() ? new Map<String, dynamic>() : new Map<int, dynamic>();
}
(Map<String, dynamic> | Map<int, dynamic>) makeItRain2() {
  return new Random().nextBool() ? new Map<String, dynamic>() : new Map<int, dynamic>();
}

// Your code.
final Map<String, dynamic> map1 = makeItRain(); //analyzer: error
final Map<String, dynamic> map2 = makeItRain() as Map<String,dynamic>; //analyzer: safe, runtime: sketchy

final Map<dynamic, dynamic> map3 = makeItRain2(); //analyzer: safe, runtime: safe
final Map<int, dynamic> map4 = makeItRain2(); //analyzer: safe, runtime: sketchy
final Map<String, dynamic> map5 = makeItRain2(); //analyzer: safe, runtime: sketchy
final Map<bool, dynamic> map6 = makeItRain2(); //analyzer: error, bool isn't in return list
```
Maybe I'm just too used to TypeScript and the way it's type safety works, but that's what makes the most sense to me.  Anything sketchy gets brought up to the user immediately and if you need to do that operation, you can explicitly set what's allowed (multiple return types) or what you're forcing to happen (explicit cast)

**Comment by leafpetersen** [comment]
Thanks for the feedback.  There is a lot of active discussion about how best to meet our users needs, and speculation only gets us so far.

There's an active feature request around implicit casts in the language here: https://github.com/dart-lang/sdk/issues/31410 , feel free to chime in.

Union types as in your Typescript example are something we've had a lot of requests for and would like to look at.
