### ISSUE TITLE
[camera_android_camerax] Camera preview is rotated on the supported Impeller version

### ISSUE THREAD

**Issue by xuegao-tzx** [flutter/flutter#149294]
### What package does this bug report belong to?

camera

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
camera_android_camerax 0.6.5+4
```

</details>

### Steps to reproduce

1. In the version camera_android_camerax 0.6.5+4 after [this commit](https://github.com/flutter/packages/commit/47d5eb2073907b90189255407fd94845abca1ae5#diff-d182c787391fc4e780731ebf796baf49787b178db1a82fc12224dd48fb4488bf), the preview camera screen is displayed abnormally, and the up, down, left, and right movement directions are also abnormal. This version will display abnormally regardless of whether io.flutter.embedding.android.EnableImpeller is set to true.
2. Test device: Google Android 15 AP31.240426.023 and HuaWei Android12.0 API31

### Expected results

This is the original normal screenshot:

<img width="400" src="https://github.com/flutter/flutter/assets/86029709/952f9ab2-7c4d-4cfa-a762-14ce6d300577">

This is the original normal screen recording:

https://github.com/flutter/flutter/assets/86029709/8546eb56-81ad-411f-8b5c-4f35d4fb3429

### Actual results

This is the current abnormal screenshot:

<img width="400" src="https://github.com/flutter/flutter/assets/86029709/2b1bdf09-8efa-40f3-ad5a-2090322db895">

This is the current abnormal screen recording:

https://github.com/flutter/flutter/assets/86029709/29e2006b-2853-4b2a-b90d-9c302e9f86ff

### Code sample

<details open><summary>Code sample</summary>

```dart
if (isCameraReady)
          SizedBox(
            width: cameraMaxSize,
            height: cameraMaxSize,
            child: ClipRRect(
              child: OverflowBox(
                child: FittedBox(
                  fit: BoxFit.cover,
                  child: SizedBox(
                    width: cameraMaxSize,
                    child: CameraPreview(
                      controller!
                    ),
                  ),
                ),
              ),
            ),
          ),
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/86029709/9397d560-44bb-4bad-9f8c-785ff772b4d8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.22.1 on channel beta at /opt/homebrew/Caskroom/flutter/3.10.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (7 天前), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xuegao/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/xuegao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio
      Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome
      Canary

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
    • IntelliJ at /Users/xuegao/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.90.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.89.20240501

[✓] Connected device (6 available)
    • ALN AL10 (mobile)               • 23F0213C21011631                                 •
      android-arm64  • Android 12 (API 31)
    • Pixel 7 Pro (mobile)            • 192.168.2.104:38723                              •
      android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                                            •
      darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                            •
      darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                                           •
      web-javascript • Google Chrome 127.0.6508.0 canary

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. Reproduced this issue using [camera_android_camerax's example](https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax/example). The camera preview is rotated 90 degree.

<details open>
<summary>Demo</summary>

| latest version 0.6.5+4 ❗ | previous version 0.6.5+3 ✅ |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/7e8287ad-909f-49c0-8ad5-afc58edf07d9"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/df7f4f7e-4084-4fd1-a305-0433664ebc0a">


✅: No Issue ❗: Issue reproduced

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (11 hours ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.19, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.19 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c787dc99bd (45 minutes ago), 2024-05-29 22:28:10 -0400
    • Engine revision 4adf453b6d
    • Dart version 3.5.0 (build 3.5.0-203.0.dev)
    • DevTools version 2.36.0-dev.10
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.113

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by rusudinu** [comment]
happens to me aswell

**Comment by sgoossens** [comment]
+1 moving from camera_android_camerax: 0.6.5+3 -> camera_android_camerax: 0.6.5+4 reproduces the issue for me as well.  In my case, the package seemed to have been pulled in by camera: 0.11.0+1

**Comment by jonahwilliams** [comment]
Revert is https://github.com/flutter/packages/pull/6838

**Comment by jonahwilliams** [comment]
I bumped the version so it should autopublish as well.

**Comment by matanlurey** [comment]
Oof, thanks for catching and iterating on this.
Is there anything else to be done? 
(I was loosely following elsewhere we think it's just the rotation logic being different?)

**Comment by camsim99** [comment]
@matanlurey Yeah looks like we need to fix the natural orientation of the preview with the change. We'll also need to fix https://github.com/flutter/flutter/issues/149177 in the process.

**Comment by shohan20** [comment]
Could you please provide an update on this issue? It's critical for our current project. If possible, could you please share an eta? Thank you.

**Comment by reidbaker** [comment]
https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed 

If you would like to have this issue fixed sooner you are welcome to submit a patch. See our contribution guide here https://github.com/flutter/flutter/blob/main/CONTRIBUTING.md

**Comment by GorinMaxim** [comment]
any news? We also faced this problem

**Comment by reidbaker** [comment]
@GorinMaxim there is an open pull request to fix the issue https://github.com/flutter/packages/pull/6856

**Comment by GorinMaxim** [comment]
it might be useful 

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-RU)
    • Flutter version 3.22.2 on channel stable at /Users/maximgorin/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/maximgorin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)            
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 15 Pro (Maxim) (mobile)  • 00008130-001E709626F0001C • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for iPhone XS Max (Maxim). Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!



I also noticed that version 0.10.6 works well with flutter 3.16.9, but rotated at flutter 3.22.2

**Comment by AlexV525** [comment]
@camsim99 Are you planning to land a similar approach for `camera_android`? See https://github.com/flutter/flutter/issues/150549

**Comment by reidbaker** [comment]
@AlexV525 https://github.com/flutter/flutter/issues/150549#issuecomment-2203989033

**Comment by AlexV525** [comment]
> @AlexV525 [#150549 (comment)](https://github.com/flutter/flutter/issues/150549#issuecomment-2203989033)

Sorry, so you are talking about that you don't want to reland https://github.com/flutter/packages/pull/6461 for `camera_android` but you already reland https://github.com/flutter/packages/pull/7044 for `camera_android_camerax`? 0.10.9+6 fixes that issue because I reverted https://github.com/flutter/packages/pull/6461 and that request has never been brought to the implementation again. Now it seems nobody cares and trying to avoid landing it because I've tried my best to tell everyone that the issue has not been really fixed.

**Comment by stuartmorgan** [comment]
@AlexV525 The situation has been pretty complex, with PRs being landed and reverted across several plugins and the repro cases being different as to whether they are about impeller or non-impeller codepaths, and all of that being conflated into a small number of issues.

Filing a new issue clearly describing the *current* state of the issue, with *current* repro steps (as well as links to relevant context) would be much more productive—and much more consistent with our code of conduct—than attributing bad intent to other project members.
