### ISSUE TITLE
[local_auth] Get supported biometric authentication types for the device even if the method is not enrolled

### ISSUE THREAD

**Issue by datngquoc** [flutter/flutter#149296]
### Use case

In my case, I want to alert User enroll their biometric on their devices, but I can't check which type of biometric that device supports if they haven't enrolled.

There is only 'getAvailableBiometric' method in this plugin.

### Proposal

I hope you guys will provide a method that help us to get supported biometric of device. Thank you!

**Comment by darshankawar** [comment]
@datngquoc See https://pub.dev/packages/local_auth#device-capabilities and check if it helps in your case or not.
