### ISSUE TITLE
[Game] New Crossword template

### ISSUE THREAD

**Issue by zoeyfan** [flutter/flutter#149286]

**Comment by domesticmouse** [comment]
How about the solution for [Build a word puzzle with Flutter](https://codelabs.developers.google.com/codelabs/flutter-word-puzzle?hl=en#0) as a [sample in the `flutter/games`](https://github.com/flutter/games/tree/main/samples) repo?

**Comment by zoeyfan** [comment]
Yes, that's what I am referring to.

**Comment by sfshaza2** [comment]
Can this issue be closed? I added this codelab to our Q2 2024 release. Do we need more docs about it on docs.flutter.dev?

**Comment by domesticmouse** [comment]
This is a different requirement. This is waiting on me making changes to a flutter/games PR before landing it.
