### ISSUE TITLE
Text is not centered in TextField 

### ISSUE THREAD

**Issue by tummyhuang** [flutter/flutter#149227]
### Steps to reproduce

see #131047

I've encountered a similar issue and I need to use cursorWidth. Could you please guide me on how to proceed?

### Expected results

The expectation is to align the experience with WebView, where the text is centered, rather than both the text and the cursor being centered together.

<img width="46" alt="image" src="https://github.com/flutter/flutter/assets/31909169/337641e4-7a41-478b-8116-9fed5639f793">

### Actual results

<img width="266" alt="image" src="https://github.com/flutter/flutter/assets/31909169/0b31d17e-7901-40f1-932b-c6602c2f760f">

### Code sample

            Container(
                alignment: Alignment.center,
                color: Colors.red,
                height: 50,
                width: 41,
                child: TextField(
                  key: textFieldKey,
                  keyboardType: TextInputType.multiline,
                  cursorWidth: 2,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    leadingDistribution: TextLeadingDistribution.even,
                    fontSize: 14,
                    height: 1,
                      fontWeight: FontWeight.w300,
                    textBaseline: TextBaseline.alphabetic,
                    // height: 3.5
                  ),
                  // cursorHeight: 20,
                  decoration: InputDecoration(
                      hintText: "3",
                      filled: true,
                      fillColor: Colors.yellow,
                      border: const OutlineInputBorder(borderSide: BorderSide.none),
                      isCollapsed: true,
                      isDense: true,
                      // counterText: '',
                      contentPadding: EdgeInsets.all(0)
                  ),
                )
            )

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

3.13

**Comment by darshankawar** [comment]
@tummyhuang I think your question / issue is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here. If you disagree or think this is a bug in framework, write in comments and I'll reopen it.

**Comment by tummyhuang** [comment]
I apologize if my previous description was not very clear. This is not so much an issue with the syntax, but rather seems to be a problem with the underlying rendering. My concern is that when I set the text in TextField to be centered, the entire text is centered, as shown with the '3' in the webview in the above image. However, in Flutter, the '3' and the cursor are centered together. If the cursor is not displayed, the '3' appears to be slightly off-center.

@darshankawar

**Comment by darshankawar** [comment]
@tummyhuang Thanks for feedback. Can you upgrade to latest stable and re-run your scenario to check if the behavior still persists or not ? If still yes, please provide us complete runnable code sample (ex: main.dart) along with current vs expected behavior.

**Comment by tummyhuang** [comment]
The latest version still has this issue.
[main.dart.zip](https://github.com/user-attachments/files/15509578/main.dart.zip)

flutte doctor:
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.23.0-13.0.pre.49, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
[✓] VS Code (version 1.87.0)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 4 categories.

<img width="387" alt="image" src="https://github.com/flutter/flutter/assets/31909169/de37fe92-491d-41c9-9253-ad454395c3e8">

the cursor is not displayed：
<img width="378" alt="image" src="https://github.com/flutter/flutter/assets/31909169/c7295565-c7cd-4e3f-bec8-e1993990307a">

**Comment by darshankawar** [comment]
I see below upon running the provided code with latest stable:

<img width="98" alt="Screenshot 2024-06-03 at 11 16 48 AM" src="https://github.com/flutter/flutter/assets/67046386/1f2c2ea6-70aa-4df6-9a46-9328ea353081">
