### ISSUE TITLE
[Impeller] The 2-pass Gaussian Blur and the RRect blur deviate significantly.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#149276]
See the video in https://github.com/flutter/flutter/issues/148412 for an example of flipping back and forth between the 2-pass Gaussian blur and the RRect fast path:

[[Upload media here]](https://github.com/flutter/flutter/assets/9356589/e68726ed-e7c6-40e6-94c6-ca310d0d2b7c)

There's quite an extreme difference between the two blur paths. In this example, the apparent standard deviation of one appears to be more than twice the other. This will continue causing issues for users because the RRect fast path is an opportunistic optimization and _not_ a discrete path exposed to Flutter.

There is one correct solution for rendering a Gaussian blur with any given shape and sigma. It's perfectly okay if we slightly deviate from Skia in our blur's appearance, but our multiple blur paths should at least look remotely similar.

**Comment by bdero** [comment]
Also, if we don't attempt to make our Blur's behavior approximate a _correct_ Gaussian blur at least in terms of apparent sigma, then we're not basing our measurements in reality and it's easy to risk biasing our apparent sigma to drift smaller over time.

Faster falloff means we get away with a smaller radius, which can result in significantly less fragment load, even for small adjustments.

Perhaps the material widgets won't respond to these changes as quickly, but users will certainly respond to this by adjusting the blur sigma up.

**Comment by gaaclarke** [comment]
The current behavior for the gaussian blur was tweaked to match skia behavior in https://github.com/flutter/engine/pull/47405.  I know we say we don't need to be pixel perfect with skia, but we need to be close so that impeller is as expressive as skia is.  Here is the bug that that change fixed: https://github.com/flutter/flutter/issues/127770

All that is to say I think the gaussian blur should be the reference for the rrect_blur.  Ideally we refactor this so that they are sharing math so editing one updates the other.

**Comment by gaaclarke** [comment]
Came up with a golden test for this that demonstrates the problem as well:
```c++
TEST_P(DlGoldenTest, GaussianVsRRectBlur) {
  Point content_scale = GetContentScale();
  auto draw = [content_scale](DlCanvas* canvas,
                              const std::vector<sk_sp<DlImage>>& images) {
    canvas->Transform2DAffine(content_scale.x, 0, 0, 0, content_scale.y, 0);
    canvas->DrawPaint(DlPaint().setColor(DlColor(0xff112233)));
    DlPaint paint;
    paint.setColor(DlColor(0xfffef7ff));
    //
    auto blur_filter_10 = std::make_shared<flutter::DlBlurMaskFilter>(
        flutter::DlBlurStyle::kNormal, 10);
    paint.setMaskFilter(blur_filter_10);
    SkRRect rrect;
    rrect.setNinePatch(SkRect::MakeXYWH(100, 50, 200, 200), 10, 10, 10, 10);
    canvas->DrawRRect(rrect, paint);
    rrect.setNinePatch(SkRect::MakeXYWH(400, 50, 200, 200), 9, 10, 10, 10);
    canvas->DrawRRect(rrect, paint);
    //
    auto blur_filter_30 = std::make_shared<flutter::DlBlurMaskFilter>(
        flutter::DlBlurStyle::kNormal, 30);
    paint.setMaskFilter(blur_filter_30);
    rrect.setNinePatch(SkRect::MakeXYWH(100, 400, 200, 200), 10, 10, 10, 10);
    canvas->DrawRRect(rrect, paint);
    rrect.setNinePatch(SkRect::MakeXYWH(400, 400, 200, 200), 9, 10, 10, 10);
    canvas->DrawRRect(rrect, paint);
  };

  DisplayListBuilder builder;
  std::vector<sk_sp<DlImage>> images;
  draw(&builder, images);

  ASSERT_TRUE(OpenPlaygroundHere(builder.Build()));
}
```

<img width="745" alt="Screenshot 2024-05-30 at 11 16 22 AM" src="https://github.com/flutter/flutter/assets/30870216/8b834124-2a78-4c69-98af-faa784bf58bf">
