### ISSUE TITLE
Get Started flow broken when JavaScript turned off

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#14922]
From URL: https://flutter.io/get-started/editor

The new startup flow won't let you choose an alternative when your JavaScript is turned off. JavaScript is turned off for about 2% of browsers (not sure what the stats are for developers, I would say higher than average).

If we choose to act on this, one solution is to show both versions by default and let JavaScript hide the ones that aren't applicable on page load. Another solution is to show the rest of the options with `<noscript>`. It can be very ugly, just show the content.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1853](https://github.com/flutter/website/issues/1853) via [**ZenHub**](https://www.zenhub.com/)
