### ISSUE TITLE
I18n docs look complicated

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#14926]
Developer feedback from Hackathon:

https://flutter.io/tutorials/internationalization/ looks scary and complicated compared to the Android flow, maybe needs a shorter summary on top? Put example of how to get a localized screen front and center? (instead of sending devs to the the sample to see usage)

**Comment by goderbauer** [comment]
@zochi I think this one should go into the flutter/website repo?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2132](https://github.com/flutter/website/issues/2132) via [**ZenHub**](https://www.zenhub.com/)
