### ISSUE TITLE
[Mac-14] `xcode analyze` fails on image_picker_macos

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#149266]
```
/Volumes/Work/s/w/ir/x/w/packages/packages/image_picker/image_picker_macos/example/macos/Flutter/GeneratedPluginRegistrant.swift:8:8: error: compiling for macOS 10.14, but module 'file_selector_macos' has a minimum deployment target of macOS 12.3: /Users/chrome-bot/Library/Developer/Xcode/DerivedData/Runner-dnklcmfvdiqkdtbzxvpldmyfphfm/Build/Products/Debug/file_selector_macos.swiftmodule/arm64-apple-macos.swiftmodule
 import file_selector_macos
        ^
```

https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac_arm64%20macos_platform_tests%20stable%20-%20packages/2/overview

**Comment by stuartmorgan** [comment]
> module 'file_selector_macos' has a minimum deployment target of macOS 12.3

No idea where it's getting this; it definitely supports 10.14.

**Comment by jmagman** [comment]
Is it possible the Swift module cache in DerivedData isn't being deleted between runs?  Maybe `--macos-min-version=12.3` is getting cached:
https://github.com/flutter/packages/blob/a5dd3140f1b076a0ad9297db649687bee7b77010/.ci/targets/macos_platform_tests.yaml#L18
