### ISSUE TITLE
Can't use shadow build with `led` in staging pool for some engine tests

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#149341]
### Type of Request

bug

### Infrastructure Environment

Recipes/LUCI

### What is happening?

Recipes will crash when running some engine tests with `led`

```
File "/Volumes/Work/s/w/ir/kitchen-checkout/flutter/recipe_modules/archives/api.py", line 231, in engine_v2_gcs_paths
     gcs_bucket, bucket_postfix = LUCI_TO_GCS_PREFIX.get(bucket_plus_realm)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: cannot unpack non-iterable NoneType object
```

https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20Production%20Engine%20Drone/1/overview
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20Production%20Engine%20Drone/4/overview
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20Production%20Engine%20Drone/7/overview
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20Production%20Engine%20Drone/9/overview

**Comment by vashworth** [comment]
CL out to fix: https://flutter-review.googlesource.com/c/recipes/+/57840

**Comment by christopherfujino** [comment]
Per [go/luci-how-to-led#new-trigger-a-real-buildbucket-build-using-led](http://goto.google.com/luci-how-to-led#new-trigger-a-real-buildbucket-build-using-led):

> Buildbucket uses a system called 'shadow buckets' to allow one bucket with permissive access to act as a 'shadow' of a less-permissive bucket when running ad-hoc jobs

**Comment by vashworth** [comment]
CL landed. Closing.
