### ISSUE TITLE
[google_sign_in]PlatformException(exception, No virtual method bindService(Landroid/content/ComponentName;Landroid/content/ServiceConnection;Ljava/lang/String;Ljava/util/concurrent/Executor;

### ISSUE THREAD

**Issue by rinku-dhiman-travel-union** [flutter/flutter#149397]
### Steps to reproduce

When trying to use the sign-in method, I encountered an issue

### Expected results

Want a successful login via Google Sign-In.

### Actual results

Getting PlatformException as result

### Code sample

```
  final account = await GoogleSignIn().signIn();
      final googleKey = await account!.authentication;

      final request = GoogleSignInRequest(
          idToken: googleKey.idToken, accessToken: googleKey.accessToken);

```
### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

`PlatformException(exception, No virtual method bindService(Landroid/content/ComponentName;Landroid/content/ServiceConnection;Ljava/lang/String;Ljava/util/concurrent/Executor;)Z in class Lcom/google/android/gms/common/internal/GmsClientSupervisor; or its super classes (declaration of 'com.google.android.gms.common.internal.GmsClientSupervisor' appears in /data/app/~~eyT2KbwCb-XXtzrsIdckpg==/com.sales.track-MnlH8Uy33iRnZBmCIgNVCA==/base.apk!classes7.dex), null, null)`

### Flutter Doctor output

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[!]Flutter (Channel stable, 3.13.8, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Android Studio (version 2023.1)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by darshankawar** [comment]
@rinku-dhiman-travel-union Looks like some external dependency could be causing it. Can you use the [plugin example](https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in/example) and see if running it, you still get same error or not ? If not, try to check your code implementation and imports with the plugin example.
Also, upgrade your version to latest stable and re-run to check if it helps further or not.
