### ISSUE TITLE
Setting avoid_print: error in our analysis_options.yaml file will only generate an error. It won't prevent app running. I need app not run. I don't know this possible or not if possible give me solution. 

### ISSUE THREAD

**Issue by vijaymsc** [flutter/flutter#149301]
### What package does this bug report belong to?

flutter_lints

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

</details>

### Steps to reproduce

main.dart

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(  const myApp());
}

class myApp extends StatelessWidget {
  const myApp({super.key});
//final data = '';
  @override
  Widget build(BuildContext context) {
    print('jerkn');
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              print('Button Pressed');
            },
            child: const Text('Press me'),
          ),
        ),
      ),
    );
  }
}
```

analysis_options.yaml

```yaml
include: package:lint/analysis_options.yaml

# Not happy with the default? Customize the rules depending on your needs.
# Here are some examples:
analyzer:

  errors:
    avoid_print: error

linter:
  rules:
    
    avoid_print: true
```
### Expected results

expected result is  if I set any flutter_lint rule error app will not run

### Actual results

now set lint error it show error but app run 

### Code sample

<details open><summary>Code sample</summary>

```dart
main.dart
import 'package:flutter/material.dart';

void main() {
  runApp(  const myApp());
}

class myApp extends StatelessWidget {
  const myApp({super.key});
//final data = '';
  @override
  Widget build(BuildContext context) {
    print('jerkn');
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              print('Button Pressed');
            },
            child: const Text('Press me'),
          ),
        ),
      ),
    );
  }
}

analysis_options.yaml

include: package:lint/analysis_options.yaml

# Not happy with the default? Customize the rules depending on your needs.
# Here are some examples:
analyzer:

  errors:
    avoid_print: error

linter:
  rules:
    
    avoid_print: true
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.4170], locale en-IN)
PS D:\vijay\print_check> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.4170], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.81.1)                                                                             
[√] Connected device (3 available)                                                                       
[√] Network resources    
```

</details>

**Comment by huycozy** [comment]
When you set `avoid_print: error`, do you see the error dialog like this? Is this an expectation?

![Screenshot 2024-05-30 at 17 01 49](https://github.com/flutter/flutter/assets/104349824/71bc4091-99ee-4f51-91ad-50edaab60f84)

**Comment by huycozy** [comment]
@vijaymsc If you want to do this on releasing with your CI, please check [this](https://stackoverflow.com/a/71661795/5921933) (executing `flutter analyze --no-fatal-infos --no-fatal-warnings` on your CI)

My guess is that VSCode runs `flutter analyze` under the hood while Android Studio doesn't. Perhaps @DanTup can help to explain this in detail?

@vijaymsc I want to make this more clearly before bringing this up further. What is your expectation? Do you expect a similar error dialog to appear on Android Studio (as on VSCode above) or an ability to prevent app building/running with `flutter run/build` commands as well?
If it's the first one, it might be best suited to report on [flutter-intellij](https://github.com/flutter/flutter-intellij/issues) repo. But if you expect this to work with Flutter tools (run/build commands), I think this could be out of `flutter_lints` package scope and it's more like a Flutter tools feature request.

**Comment by vijaymsc** [comment]
If I set a lint error in analysis_options.yaml file  , the Flutter app may not run. Is this possible?
@huycozy

**Comment by huycozy** [comment]
>the Flutter app may not run. Is this possible?

I don't see a way to make it possible now. At least, I see a warning dialog on VSCode even though I'm not sure if it's your expectation. 

If you think this is a feature request, please help to clarify questions from my [above comment](https://github.com/flutter/flutter/issues/149301#issuecomment-2141261404). Thanks!

**Comment by DanTup** [comment]
> My guess is that VSCode runs flutter analyze under the hood while Android Studio doesn't. Perhaps @DanTup can help to explain this in detail?

Both IDEs use the same analysis, but the behaviour of detecting when there are errors when you try to launch an app and prompting you is implemented in the IDE itself (since it handles the launching of a debug session). As a result, there might be some differences in how this is implemented between them. I think filing in flutter/flutter-intellij is the right thing to do here as it sounds like this may be a bug there (I see https://github.com/flutter/flutter-intellij/issues/7475 has been opened).

**Comment by DanTup** [comment]
> My goal is, If I set a lint error in analysis_options.yaml file , the Flutter app may not run. Is this possible?

I think having IntelliJ prompt like VS Code does is possible. I'm less sure you could make `flutter run` also reject launching the app in this case, because I don't _think_ it runs the linter at all.

**Comment by huycozy** [comment]
@DanTup Thank you for your input. 

@vijaymsc You should wait `flutter-intellij` team to confirm if there is a bug on Android Studio IDE or not. In case you think this should be an ability with Flutter tools as well, please file a separate issue for it. 

I think the expectation (`prevent app running`) is out of the `flutter_lints` package scope so I will go ahead and close this. If you disagree, please write in the comments and I will reopen it.
