### ISSUE TITLE
[pigeon] [Mac-14] runPigeonIntegrationTests timeout in CI on macOS 14

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#149329]
### What package does this bug report belong to?

pigeon

### What target platforms are you seeing this bug on?

macOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

```
led get-builder "luci.flutter.staging:Mac_arm64 custom_package_tests master" | led edit -d os=Mac-14 | led edit -pa git_ref="refs/pull/6827/head" | led edit -pa git_url="https://github.com/flutter/packages"
```

### Expected results

Expect tests to pass

### Actual results

When running CI tests on Mac-14, seems like tests that use `runPigeonIntegrationTests` time out:
- [packages/pigeon/platform_tests/alternate_language_test_plugin/example/integration_test/test.dart](https://github.com/flutter/packages/blob/main/packages/pigeon/platform_tests/alternate_language_test_plugin/example/integration_test/test.dart#L9)
- [packages/pigeon/platform_tests/test_plugin/example/integration_test/test.dart](https://github.com/flutter/packages/blob/main/packages/pigeon/platform_tests/test_plugin/example/integration_test/test.dart#L9)

```
loading /Volumes/Work/s/w/ir/x/w/packages/packages/pigeon/platform_tests/test_plugin/example/integration_test/test.dart [E]                                                               
   TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
   package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
   dart:async/zone.dart 1391:47                      _rootRun
   dart:async/zone.dart 1301:19                      _CustomZone.run
   package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
   package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
   dart:async/zone.dart 1399:13                      _rootRun
   dart:async/zone.dart 1301:19                      _CustomZone.run
   package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
   dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
   dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
   dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
   dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePort._handleMessage
```

Examples: 
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac_arm64%20custom_package_tests%20stable/2/overview
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac_arm64%20custom_package_tests%20master/3/overview

### Code sample

Use pigeon example integration tests

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by tarrinneal** [comment]
@stuartmorgan Any insights on this?

**Comment by stuartmorgan** [comment]
Nothing offhand. It looks like maybe the macOS app is never starting? Hard to tell from just the logs though; this may be a remote-into-a-machine-and-watch situation if we can't repro locally.

**Comment by vashworth** [comment]
If it's starting a macOS app, then it's likely same issue as https://github.com/flutter/flutter/issues/149268 and https://github.com/flutter/flutter/issues/149264.

**Comment by vashworth** [comment]
Confirmed fixed by https://ci.chromium.org/b/8745950155299703601.
