### ISSUE TITLE
Add Flutter and Dart logos to all major icon sets (e.g., Font Awesome)

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#149388]
### Use case

I'm assembling guide/documentation websites for all of the Flutter Bounty Hunter packages. Some of them are Flutter packages, others are Dart packages. On these websites, I link to Pub, but the Pub button feels out of place because its missing a logo, which other social buttons have:

<img width="980" alt="Screenshot 2024-05-30 at 11 45 57 PM" src="https://github.com/flutter/flutter/assets/7259036/7b44a6f8-dac1-4b9d-ba71-4f19c5ee08df">

### Proposal

Flutter and Dart should take advantage of the branding and marketing opportunity of submitting their logos to all the major icon sets. For example, Font Awesome has an entire section filled with "brands": https://fontawesome.com/search?o=r&f=brands

<img width="1257" alt="Screenshot 2024-05-30 at 11 47 09 PM" src="https://github.com/flutter/flutter/assets/7259036/3d974f03-4e6b-4e38-9efb-5c8004636a75">

**Comment by matthew-carroll** [comment]
CC @craiglabenz @kevmoo @sethladd for marketing and community purposes.

**Comment by kevmoo** [comment]
Go for it!

**Comment by mit-mit** [comment]
Thanks for the suggestion @matthew-carroll. Do you have a list of what the most used icon sets are?

**Comment by matthew-carroll** [comment]
@mit-mit the only one I know for sure is heavily used is Font Awesome.

That said, if you search Pub, you'll find a number of packages that make various icon sets available to Flutter developers by packaging those icon fonts into Flutter packages. I would recommend checking which Pub icon sets are popular.

**Comment by sethladd** [comment]
+1 for Font Awesome.

**Comment by sethladd** [comment]
If anyone wants to add the logos to Font Awesome (or others), looks like you can find the SVGs here: https://flutter.dev/brand

**Comment by matthew-carroll** [comment]
But make sure they work for monochrome in various colors and shades.

**Comment by mit-mit** [comment]
Closing for now. If there are other key font sets to update, please file a new issue.

**Comment by matthew-carroll** [comment]
@mit-mit this issue was filed for the Dart logo, not the Flutter logo.
