### ISSUE TITLE
`flutter build ipa` fails: Command line name "app-store" is deprecated. Use "app-store-connect"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#149369]
```
Command line name "app-store" is deprecated. Use "app-store-connect"
```
```
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -exportArchive -allowProvisioningDeviceRegistration -allowProvisioningUpdates -archivePath
/Users/myuser/Documents/build/ios/archive/Runner.xcarchive -exportPath
/Users/myuser/Documents/build/ios/ipa -exportOptionsPlist
/var/folders/61/j5p5_mf17zq5lhj_dzm15s6h0000gn/T/flutter_tools.8J75rW/flutter_build_ios.TnrnSn/ExportOptions.plist
[+3686 ms] 2024-05-31 09:54:13.239 xcodebuild[19083:304649] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path
"/var/folders/61/j5p5_mf17zq5lhj_dzm15s6h0000gn/T/Runner_2024-05-31_09-54-13.239.xcdistributionlogs".
                    2024-05-31 09:54:13.343 xcodebuild[19083:304649] [MT] IDEDistribution: Command line name "app-store" is deprecated. Use "app-store-connect"
                    instead.
[        ] Building App Store IPA... (completed in 3.7s)
[        ] Encountered error while creating the IPA:
[        ] Try distributing the app in Xcode: "open /Users/weilunchen/Documents/build/ios/archive/Runner.xcarchive"
[        ] "flutter ipa" took 48,621ms.
[ +215 ms] ensureAnalyticsSent: 213ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

_Originally posted by @MarcusWlc92 in https://github.com/flutter/flutter/issues/106612#issuecomment-2141017794_

**Comment by jmagman** [comment]
On Xcode 15.4 `xcodebuild --help` says the options are `app-store-connect`, not `app-store`. `ad-hoc` has changed to `release-testing`, and `development` has changed to `debugging`.

> Available options: app-store-connect, release-testing, enterprise, debugging, developer-id, mac-application, validation, and package. The list of options varies based on the type of archive. Defaults to debugging. Additional options include app-store (deprecated: use app-store-connect), ad-hoc (deprecated: use release-testing), and development (deprecated: use debugging).

https://github.com/flutter/flutter/blob/a1423723fff778e5c02770d915837838cf19e08b/packages/flutter_tools/lib/src/commands/build_ios.dart#L106-L107

This change appears to have happened in Xcode 14.3. Xcode 14.2 says the old methods:
> Available options: app-store, validation, ad-hoc, package, enterprise, development, developer-id, and mac-application. The list of options varies based on the type of archive. Defaults to development.

**Comment by jmagman** [comment]
Absolutely inevitable: 
> There are so many options when you export an archive that would have to be exposed in that command just to pipe 1:1 into `xcodebuild`/`exportOptionsPlist`. You pretty much need an entire UI wizard flow in the CLA to make it manageable, which Xcode already has (and keeps updated with new App Store requirements). So either we build an identical wizard flow, or we expose all the below flags, and if you can successfully use them, then congrats! you are an Xcode guru and are probably already using `xcodebuild` directly.

https://github.com/flutter/flutter/issues/13065#issuecomment-698651179

**Comment by jmagman** [comment]
1. Add the new options to the `addOption` "allowed" list.
2. Check the current version of Xcode via `Xcode.currentVersion`
3. If on < Xcode 14.3, if the export method is `app-store` or `app-store-connect`, use deprecated `app-store` in the plist.  If it's `ad-hoc` or `release-testing`, use deprecated `ad-hoc`, etc.
4. If on >= Xcode 14.3, the same, but use the new, un-deprecated variants.
5. Add tests and update existing ones.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/150407 is about to land, @szechyjs @saumon or anyone else subscribed to this issue: once it does land (or if you want to patch it in now) can you give it a try and let us know if it unblocks submission?

**Comment by LouiseHsu** [comment]
@szechyjs @saumon https://github.com/flutter/flutter/pull/150407 Has landed - let me know if this fixes the issue for you.

**Comment by szechyjs** [comment]
Seems to be working now
