### ISSUE TITLE
How to deploy a flutter app using flavor with xcode cloud?

### ISSUE THREAD

**Issue by neonlee** [flutter/flutter#149317]
### Type of Request

bug

### Infrastructure Environment

Xcode cloud with gitlab

### What is happening?

Hello, I have an application with Flutter using flavors, and I would like to deploy it via Gitlab with xcode cloud, but when building the application using xcode cloud it gives me the problem below.

![image](https://github.com/flutter/flutter/assets/37202080/b62f86b6-dd2a-445a-aa02-15c7910d9014)

Is there any way to build my application with flavors through xcode cloud and deploy it to apple stores?

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I hope to be able to deploy it to the apple store with xcode cloud
I use flutter for my flavored application

**Comment by darshankawar** [comment]
@neonlee 
Can you provide us the complete error log in properly formatted text ?
Also, check https://docs.flutter.dev/deployment/cd#xcode-cloud and see if it helps further or not.
