### ISSUE TITLE
Issue from website page Upgrading Flutter - change dev to beta?

### ISSUE THREAD

**Issue by boustrophedon** [flutter/flutter#14930]
From URL: https://flutter.io/upgrading.md

Should this page be updated to use the beta branch instead of dev?

**Comment by cbracken** [comment]
Thanks for filing -- yes, it absolutely should!

Updated URL: https://flutter.io/upgrading/

/cc @mjohnsullivan @filiph

**Comment by filiph** [comment]
Aaah, how did I miss this? Thanks for reporting, @boustrophedon. 

@goderbauer, thanks for the quick fix.
