### ISSUE TITLE
Kotlin Gradule plugin upgrade instruction is out of date

### ISSUE THREAD

**Issue by rewired-gh** [flutter/flutter#149310]
The current instruction is as follow:

https://github.com/flutter/flutter/blob/6a0e0bfdc5f86c84b3499dfb0943418588f3b6c0/packages/flutter_tools/lib/src/android/gradle_errors.dart#L448-L454

Which is not correct. The correct way to upgrade Kotlin Gradle plugin is modify the `settings.gradle` file instead of `build.grade`. And change the line similar to `id "org.jetbrains.kotlin.android" version "2.0.0" apply false`. Then `flutter clean` should be run to take effects.

Reference: https://stackoverflow.com/questions/78115995/hoe-to-fix-gradle-error-in-flutter-project

**Comment by huycozy** [comment]
Hi @rewired-gh 
>The correct way to upgrade Kotlin Gradle plugin is modify the settings.gradle file instead of build.grade

How is this incorrect? It's clearly suggested for project created before and after 3.19. 

>And change the line similar to id "org.jetbrains.kotlin.android" version "2.0.0" apply false. Then flutter clean should be run to take effects.

Are you proposing to upgrade `org.jetbrains.kotlin.android` version to the latest `2.0.0` in the project skeleton, right? I'm not sure I can get what "`Then flutter clean should be run to take effects`" means, could you be more specific?

**Comment by rewired-gh** [comment]
> Hi @rewired-gh
> 
> > The correct way to upgrade Kotlin Gradle plugin is modify the settings.gradle file instead of build.grade
> 
> How is this incorrect? It's clearly suggested for project created before and after 3.19.
> 
> > And change the line similar to id "org.jetbrains.kotlin.android" version "2.0.0" apply false. Then flutter clean should be run to take effects.
> 
> Are you proposing to upgrade `org.jetbrains.kotlin.android` version to the latest `2.0.0` in the project skeleton, right? I'm not sure I can get what "`Then flutter clean should be run to take effects`" means, could you be more specific?

No, it is just an example.

**Comment by huycozy** [comment]
If you propose upgrading `org.jetbrains.kotlin.android` version in Flutter project template, please file a separate issue (proposal). Closing this issue as the instruction is correct.
