### ISSUE TITLE
RichText is not following Android system font size

### ISSUE THREAD

**Issue by jpwoodbu** [flutter/flutter#149346]
### Steps to reproduce

1. Create a RichText widget setting its style using the context.
2. Increase the Android Font Size setting higher than the second lowest position.

### Expected results

The RichText widget should scale with the Android Font Size setting.

### Actual results

The RichText widget ignores the Android Font Size setting.

### Code sample

https://dartpad.dev/?id=8f5b3747bed1ae85aab9d1e60fcae836

### Screenshots or Video

<details open>
<summary>As the system font size is changed, the Text widget scales but the RichText widget does not</summary>

![image](https://github.com/flutter/flutter/assets/494346/806fa970-7a8f-4c3b-a263-d5cba3e3237d)
![image](https://github.com/flutter/flutter/assets/494346/fee4c980-3c74-4cb9-aeec-e8c9fe893179)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.22.1, on Ubuntu 22.04.4 LTS 6.5.0-35-generic, locale en_US.UTF-8)
    • Flutter version 3.22.1 on channel stable at /home/jpwoodbu/fvm/versions/3.22.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (8 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/jpwoodbu/Android/Sdk/
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/jpwoodbu/android/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.3)
    • Android Studio at /home/jpwoodbu/android/android-studio
    • Flutter plugin version 79.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • Pixel 8a (mobile) • 10.0.2.64:34853 • android-arm64  • Android 14 (API 34)
    • Linux (desktop)   • linux           • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-35-generic
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 125.0.6422.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
Use Text.rich instead. RichText is incorrectly named and should be called something like RawText, it very intentionally does not use any inherited widgets to establish things like text size.

**Comment by jpwoodbu** [comment]
Thank you! That did indeed fix the issue in my app.

Out curiosity, I went looking to see how `RichText` could be configured so it would scale text with the system font size settings. For anyone also curious about that, I discovered `TextScaler`. It looks like passing `MediaQuery.of(context).textScaler` to the `textScaler` parameter of `RichText` is how to do that. @jonahwilliams, please correct me if I'm wrong.

**Comment by jonahwilliams** [comment]
Or you just use Text.rich, which does that for you :)

**Comment by clragon** [comment]
This is a problem that I unconciously had for a long time. 

`RichText`s naming is depective, because one might wrongfully assume that it works like a `Text` widget.
It would be great if we could do something about this some day. Maybe we could deprecate the `RichText` name and point to `Text.rich` and the new name for the current `RichText`, whatever that may be. `RawText` as you suggested sounds fine.

**Comment by jpwoodbu** [comment]
Finding and watching the "Widget of the Week" video links to from
https://api.flutter.dev/flutter/widgets/RichText-class.html had me
confident that using `RichText` directly was the right thing to do. I just
noticed that that YT video is from 4 years ago. Perhaps that's before
`Text.rich` was introduced.

**Comment by darshankawar** [comment]
Based on https://github.com/flutter/flutter/issues/149346#issuecomment-2140915567, I'll close this as resolved.
