### ISSUE TITLE
[shared_preferences] add setStringIterable 

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#149460]
### Use case

in `package:shared_preferences/shared_preferences.dart`
```
Future<bool> setStringList(String key, List<String> value)
``` 
takes a `List<String>` as value.
can you add:
```
Future<bool> setStringIterable(String key, Iterable<String> value)
``` 
so the API is more generic and I don't need to convert to List because of this function?

### Proposal

up

**Comment by stuartmorgan** [comment]
Both the platform channel step and the actual storage step require a list, so there is no possibility of any performance improvement by using `Iterable`. `List` correctly expresses the required type.



> ### Proposal
> up

In the future please don't put the proposal in the "use case" section. The reason that section exists is because it's important for us to understand the use case driving a proposal. Proposals without use cases are unlikely to advance through the process.

**Comment by stephane-archer** [comment]
@stuartmorgan Could you clarify why a `List` is required over an `Iterable`? What constraint has a `List` that is necessary here? I'm probably missing something here.

@stuartmorgan Explaining something in your head to someone else in a clear and concise way is hard enough, I struggle with the sections and forcing some kind of structure. I'm not sure anyone wins here doing this. But I guess I will try harder.

**Comment by stuartmorgan** [comment]
> @stuartmorgan Could you clarify why a `List` is required over an `Iterable`?

Sorry, I don't understand the question. The plugin can't pass an `Iterable` to underlying code that requires a `List` for the same reason that you can't pass an `Iterable` to `setStringList`; I'm not what clarification you are looking for here.

If you have questions about the details of the plugin implementation, the easiest thing is going to be to look at the source.

**Comment by stephane-archer** [comment]
@stuartmorgan I was probably not clear, is there any valid reason why the underlying code requires a List over an Iterable? I don't see any.

**Comment by stuartmorgan** [comment]
If you have questions about the design of the storage systems wrapped by `shared_preferences`, you would need to ask the developers of those APIs: the Android team, Apple, and the authors of the JSON spec.

**Comment by stephane-archer** [comment]
@stuartmorgan  let's try one last time with a question, What property has a List in Dart that is not offered by an Iterable in Dart that makes it impossible to be compatible with "the JSON spec"? 

the Android team, Apple, and the authors of the JSON spec do not write their API for Dart so it's not because that asks for a list that an iterable in Dart is not compatible with the API. Or is there something I don't understand about the iterable type in Dart?

**Comment by stuartmorgan** [comment]
I'm still not sure what you are asking.

If you believe that I am incorrect and that `shared_preferences` can take an `Iterable` and serialize it directly to the underlying data storage APIs, please feel free to submit a PR that does so.
