### ISSUE TITLE
Flutter Extension did NOT install Dart Extension

### ISSUE THREAD

**Issue by dkermit** [flutter/flutter#149477]
### Steps to reproduce

Running macOS Monterey 12.7.5 on iMac (Retina 5K, 27-inch, Late 2015): 2024.6.1 4:00am PST.  This bug did not occur 2-5 days ago on M1 Mac  running Sonoma 14.5 nor yesterday using Windows OS, nor was it repeatable by uninstalling Flutter and Dart extensions and then reinstalling Flutter extension (see below.)

Installed Flutter Extension from within VS Code v3.90.0 
Restarted VS Code
Opened Command Palette (shift Cmd P) and typed Flutter 
No options were displayed
Downloaded and installed flutter SDK manually (see https://docs.flutter.dev/get-started/install/macos/desktop?tab=vscode) 
Created a flutter project from Terminal in VS Code - switched back and forth between dev and stable channel (based on ALotLikeEs answer at https://stackoverflow.com/questions/56522065/flutter-new-web-project-not-showing-in-visual-studio-command-palette#:~:text=I%20had%20the%20same%20problem,a%20folder%20solved%20my%20problem.)
Used Open Folder in VSCode to open new flutter project
unable to Run and Debug (Shift Cmd D) - (was prompted by something that led me to type Dart into Extensions: Marketplace)
Searched for Dart in Extension: Marketplace and selected it - it was NOT installed. 
Installed Dart - was able to run flutter project and Command Palette displayed flutter options

UNABLE TO REPEAT BUG

Uninstalled Flutter and Dart extensions
Installed Flutter extension - as before from within VS Code: THIS TIME Dart extension was also installed and everything worked as expected.
Uninstalled Flutter and Dart extension: could still run project (browser opened after Debug Console listed downloading Darwin-X86 tools

### Actual results

Flutter extension did not install Dart extension: Only on 9 year old Mac, worked as expected this past week on both M1 MacBook Air running Sonoma 14.5 as well as a couple PCs running latest Windows OS, and only the first time (see below.)

Installed Flutter extension: Dart extension NOT installed
Installed Dart extension
Ran project
Uninstalled Flutter and Dart extensions
Reinstalled Flutter extension: Dart extension installed

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

issue occurred prior to installing flutter SDK

```

</details>

**Comment by darshankawar** [comment]
@dkermit 
Can you check [this](https://stackoverflow.com/questions/74361802/flutter-and-dart-extensions-appear-to-be-broken-on-vscode) and see if it helps in your case or not ?
