### ISSUE TITLE
BillingResponse.developerError and Invalid sku type Error Android

### ISSUE THREAD

**Issue by cnkygmr** [flutter/flutter#149402]
### Steps to reproduce

Active in app purchase example
https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example

### Expected results

According to the new version, sku type is not included in the subscription

### Actual results

BillingClient: Error consuming purchase with token. Response code: 5
source: google_play
message: BillingResponse.developerError
details: Invalid sku type.
code: consume_purchase_failed

### Code sample

Active in app purchase example
https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@cnkygmr 
Can you provide us complete error log ?
Also, is it replicable by running locally in debug mode ?

**Comment by cnkygmr** [comment]
@darshankawar 

queryPurchasesAsync() is not have offlical example still have old queryProductDetails()

**Comment by darshankawar** [comment]
@cnkygmr 
Can you check [this](https://stackoverflow.com/questions/72908194/how-to-get-user-purchases-from-play-store-in-flutter) and see if it helps in your case or not ?

**Comment by cnkygmr** [comment]
@darshankawar 

Nope,  i need GooglePlayProductDetails for productType but standart example has ProductDetails when i use queryProductDetails().

So ProductDetails not have productType.

**Comment by cnkygmr** [comment]
@darshankawar 

What I want to know is what should I do with the current official example? Invalid SKU type. To avoid getting the error?

**Comment by cnkygmr** [comment]
@darshankawar 

I tried such a way, but it still gave the same error.

```
purchaseParam = GooglePlayPurchaseParam(
       productDetails: productDetails as GooglePlayProductDetails,  // like that
);
```

**Comment by cnkygmr** [comment]
@darshankawar 

I made a ridiculous mistake, I used buyConsumable for subscription.

**Comment by darshankawar** [comment]
Does that mean the reported behavior isn't a bug in plugin ?
