### ISSUE TITLE
Golden file tests don't work locally

### ISSUE THREAD

**Issue by victorsanni** [flutter/flutter#149435]
### Steps to reproduce

Run `flutter test` in `packages/flutter`

### Expected results

Golden file tests should have some functionality.

### Actual results

I get the message: 

```
No expectations provided by Skia Gold for test: cupertino.switch.tap.off.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org.
```

Equivalent of #144496.

### Code sample

None

### Screenshots or Video

None

### Logs

```
flutter test /Users/victorsanni/development/flutter/packages/flutter/test/cupertino/switch_test.dart
```

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.22.0-14.0.pre.48, on macOS 14.5 23F79 darwin-arm64, locale en)
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by Piinks** [comment]
@victorsanni are you on a mac running these tests? I think so?

I cannot reproduce this on my own mac at tip of tree, so I am wondering what might be different between our machines. The machine details are used to grab the image, so if your machine details are different from any CI machine we run these tests on, it may be why no image is being found.

When you have a chance, can you add a print statement here and let me know what is output when you run the test? These are the keys that are used to look up and image for the given machine.

https://github.com/flutter/flutter/blob/6193615f90a800ff5623373137bd88ea67d5a1d2/packages/flutter_goldens/lib/skia_client.dart#L577-L591

Right after this, add `print(parameters)`, and run the test again.

For me, it's
```
{Abi: macos_x64, CI: luci, Platform: macos, name: cupertino.switch.tap.off, source_type: flutter}
```

**Comment by victorsanni** [comment]
@Piinks I'm on a mac.

`{Abi: macos_arm64, CI: luci, Platform: macos, name: cupertino.switch.tap.off, source_type: flutter}`

**Comment by Piinks** [comment]
Oh I see. `macos_x64` versus `macos_arm64`. Can you comment out the abi key in `parameters`? It should get the right image then.

The abi key seems kind of brittle, we disabled it in the other issue briefly. Maybe just for local testing we can exclude the abi key. Since our CI does not cover every possible value, some machine won't be able to test locally otherwise. @jonahwilliams do you have any thoughts?

**Comment by victorsanni** [comment]
It works now, Thanks for the help!

**Comment by jonahwilliams** [comment]
I thought the ABI keys were removed from the client?

**Comment by Piinks** [comment]
They were, then we added them back when we found out what the issue was (at that time, we learned keys needed to be sorted alphabetically for proper look up on gold's end).

**Comment by huycozy** [comment]
I can not reproduce this issue on master channel `3.23.0-13.0.pre.69`. I see https://github.com/flutter/flutter/commit/00f40667c16ae3f7cf0c567fe4a43c0a59046951 doesn't contain the version @victorsanni using. 

@victorsanni Could you try upgrading to the latest master? As I see the fix on that commit temporarily commented out the Abi key (as @Piinks suggested above)

**Comment by victorsanni** [comment]
I've upgraded but my `skia_client.dart` doesn't have the `abi` key commented out:

```
[✓] Flutter (Channel master, 3.23.0-13.0.pre.75, on macOS 14.5 23F79 darwin-arm64, locale en)
    • Flutter version 3.23.0-13.0.pre.75 on channel master at /Users/victorsanni/development/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 0e7295fd18 (46 minutes ago), 2024-06-03 22:41:36 +0530
    • Engine revision ea72558be7
    • Dart version 3.5.0 (build 3.5.0-214.0.dev)
    • DevTools version 2.36.0
```

```dart
  String getTraceID(String testName) {
    final String? webRenderer = _webRendererValue;
    final Map<String, Object?> parameters = <String, Object?>{
      if (_isBrowserTest)
        'Browser' : _browserKey,
      'Abi': '$abi',
      'CI' : 'luci',
      'Platform' : platform.operatingSystem,
      if (webRenderer != null)
        'WebRenderer' : webRenderer,
      if (_isImpeller)
        'impeller': 'swiftshader',
      'name' : testName,
      'source_type' : 'flutter',
    };
```

**Comment by huycozy** [comment]
I see, the change is then reverted via https://github.com/flutter/flutter/pull/148072. 

On my machine, Abi is `macos_x64` so I couldn't reproduce this. Labeling this issue for `macos_arm64` case.

**Comment by jonahwilliams** [comment]
SGTM
