### ISSUE TITLE
Flutter doctor lists VS Code twice if you have 32bit + 64bit

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#14949]
In the non-verbose mode of `flutter doctor` you may see VS Code listed twice if you have 32bit + 64bit. I think it's fine to be listed twice, but in the non-verbose mode you can't tell why it's there twice (in verbose mode it's more obvious as we show the path).

![image 1](https://user-images.githubusercontent.com/1078012/36776548-20facff6-1c5e-11e8-973e-f3805f6221d5.png)

We can add ` (32 bit)` or ` (64 bit)` to the end, but maybe we should only do this if both are present so that it's less noisy for the people with only one?

@mit-mit @devoncarew lmk what you think (I'm happy to do it)

**Comment by mit-mit** [comment]
This is our diagnostics tool, so the more info, the better! I'd just change the headings to something like `VS Code, 64-bit edition`

**Comment by DanTup** [comment]
I've opened https://github.com/flutter/flutter/pull/15018
