### ISSUE TITLE
Crash when clicck 'View Licenses' in About Dialog.

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#14947]
Here is my code:
```
Drawer getNavDrawer(BuildContext context) {
    var headerChild = new DrawerHeader(child: new Text("Header"));
    var aboutChild = new AboutListTile(
        child: new Text("About"),
        applicationName: "Application Name",
        applicationVersion: "v1.0.0",
        applicationIcon: new Icon(Icons.adb),
        icon: new Icon(Icons.info));


    var myNavChildren = [
      headerChild,
      aboutChild
    ];

    ListView listView = new ListView(children: myNavChildren);

    return new Drawer(
      child: listView,
    );
  }
```

the log: 

```
[+1497 ms] F/libc    (32236): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 32728 (ui_thread)
[+1138 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///data/data/com.xxx/cache/food-max-mobileMJRVHV/xxx/)
[        ] _deleteDevFS: {fsName: food-max-mobile}
[   +5 ms] DevFS: Deleting filesystem on the device (file:///data/data/com.xxx/cache/food-max-mobileMJRVHV/xxx/)
[        ] _deleteDevFS: {fsName: food-max-mobile}
[ +257 ms] TimeoutException after 0:00:00.250000: Future not completed
[{"event":"app.stop","params":{"appId":"fb3b39be-8b0f-4d59-92b6-4d8b950db836"}}]
[  +51 ms] "flutter run" took 119,177ms.
[   +5 ms] TimeoutException after 0:00:00.250000: Future not completed
[{"id":0,"result":true}]
```

**Comment by cbracken** [comment]
@realcarlos is this always reproducible, or do the licenses sometimes appear?

/cc @jason-simmons this looks similar to #7314, except not on startup.

**Comment by realcarlos** [comment]
@cbracken yes, every time

**Comment by realcarlos** [comment]
@cbracken ,please help , we want to release an app with Drawer, so we need to add this License Dialog.

**Comment by Hixie** [comment]
@realcarlos If you have the time, it would be useful if you could try the following to help us narrow it down:

* Does it crash if you do it on a different device?
* Does it crash in release mode as well?
* Does it crash if you remove the arguments to AboutListTile?
* Can you run `adb logcat`, then include the full crash log here? (`adb logcat` will include more information than just `flutter run` or `flutter logs`)
* Does it crash if you create a new app with `flutter create` and add an AboutListTile to the body of that app?

**Comment by realcarlos** [comment]
Yes ,I tested with different devices:

 OPPO A1601 -- Android. 5.1 crashed everytime
HTC -- Android 7.0 crashed some time
Genymotion -- Galaxy S8 7.0  crashed everytime

**Comment by realcarlos** [comment]
OK ,I found it works ok if I uncheck the 'Run application with --preview-dart-2' in the setting of IntelliJ

**Comment by Hixie** [comment]
Ah, thanks.

cc @aam @a-siva

**Comment by Hesamedin** [comment]
@realcarlos, would you please tell me how did you do that?
My app crashes a similar way when I click on the button. Thanks.
