### ISSUE TITLE
[Mac-14] Impeller-golden for host_release fails on macOS 14

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#149416]
We're getting ready to upgrade our CI to macOS 14, but `Impeller-golden for host_release` continuously fails when ran on a Mac-14 staging bot.

```
Running command "/Volumes/Work/s/w/ir/cache/builder/src/out/ci/mac_release_arm64/dart-sdk/bin/dart --disable-dart-dev bin/golden_tests_harvester.dart /Volumes/Work/s/w/ir/x/t/impeller_goldenb6wwwz8g"
 Failed to add image to Skia Gold: Error when running Skia Gold: /Volumes/Work/s/w/ir/cache/gold/goldctl imgtest add --work-dir /Volumes/Work/s/w/ir/x/t/impeller_goldenb6wwwz8g/temp --test-name impeller_Play_AiksTest_CanDrawPerspectiveTransformWithClips_Metal --png-file /Volumes/Work/s/w/ir/x/t/impeller_goldenb6wwwz8g/impeller_Play_AiksTest_CanDrawPerspectiveTransformWithClips_Metal.png --passfail --add-test-optional-key image_matching_algorithm:fuzzy --add-test-optional-key fuzzy_max_different_pixels:7864 --add-test-optional-key fuzzy_pixel_delta_threshold:8
 Skia Gold received an unapproved image in post-submit
 testing. Golden file images in flutter/engine are triaged
 in pre-submit during code review for the given PR.
 Visit https://flutter-engine-gold.skia.org/ to view and approve
 the image(s), or revert the associated change. For more
 information, visit the wiki:
 https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter
 stdout: Given image with hash de921969baa2d9717030338ca621acee for test impeller_Play_AiksTest_CanDrawPerspectiveTransformWithClips_Metal
 Expectation for test: 34b6d09b8f69f6e98001c212a8505aae (positive)
 Expectation for test: 6d37d54bf99c4c61df64497f318622d1 (positive)
 Fetching most recent positive digest for trace with ID "ea8697f805ff2d58b9e4c29be6b24923".
 Non-exact image comparison using algorithm "fuzzy" against most recent positive digest "6d37d54bf99c4c61df64497f318622d1".
 Untriaged or negative image: https://flutter-engine-gold.skia.org//detail?grouping=name%3Dimpeller_Play_AiksTest_CanDrawPerspectiveTransformWithClips_Metal%26source_type%3Dflutter-engine&digest=de921969baa2d9717030338ca621acee
 stderr: Test: impeller_Play_AiksTest_CanDrawPerspectiveTransformWithClips_Metal FAIL
 Unhandled exception:
 Failed comparison: impeller_Play_AiksTest_CanDrawPerspectiveTransformWithClips_Metal.png
 #0      harvest.<anonymous closure> (package:golden_tests_harvester/golden_tests_harvester.dart:178:7)
 #1      _FutureListener.handleError (dart:async/future_impl.dart:181:22)
 #2      Future._propagateToListeners.handleError (dart:async/future_impl.dart:873:47)
 #3      Future._propagateToListeners (dart:async/future_impl.dart:894:13)
 #4      Future._completeError (dart:async/future_impl.dart:674:5)
 <asynchronous suspension>
 ```
 
https://ci.chromium.org/b/8746478703122747313
https://ci.chromium.org/b/8746413109650410993

Perhaps the [image](https://flutter-engine-gold.skia.org/detail?grouping=name%3Dimpeller_Play_AiksTest_CanDrawPerspectiveTransformWithClips_Metal%26source_type%3Dflutter-engine&digest=de921969baa2d9717030338ca621acee) just needs to be approved? From what I can tell, the difference is undistinguishable

**Comment by jonahwilliams** [comment]
How are we doing this migration? I would expect that changing the OS version would change goldens? Feel free to loop anyone from impeller/engine into this.

**Comment by jonahwilliams** [comment]
We can just approve these images if they're small too? Is that the only diff?

**Comment by vashworth** [comment]
The plan is to allow tests to run on Mac-13 or 14 and then upgrade 50% of the fleet: https://github.com/flutter/flutter/issues/148870

I've been running each test manually on a experimental Mac-14 bot via `led` to validate tests pass before we make the upgrade: https://github.com/flutter/flutter/issues/148877

This is the only engine test that has failed and that is the only diff

**Comment by jonahwilliams** [comment]
Do you want me to approve it? Or you can - I trust you. its fine to just go ahead and approve very small % diffs.

**Comment by vashworth** [comment]
> Do you want me to approve it? Or you can - I trust you. its fine to just go ahead and approve very small % diffs.

Okay good to know, I'll go ahead and approve it and verify it fixes. Thanks!

**Comment by vashworth** [comment]
Verified that approving the golden diff fixed: https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20Production%20Engine%20Drone/67/overview
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20Production%20Engine%20Drone/68/overview
