### ISSUE TITLE
Adjusting the height of TextStyle for the whole app

### ISSUE THREAD

**Issue by jehadhmoudah** [flutter/flutter#149476]
### Use case

When using some Arabic fonts, sometimes the characters from one line clash with those of the previous or the next line.

Here's an example of the problem caused by some Arabic fonts:
```dart
Text(
  'ولما كان تناسي حقوق الإنسان وازدراؤها قد أفضيا إلى أعمال همجية',
  style: Theme.of(context).textTheme.headlineMedium?.copyWith(
        fontFamily: GoogleFonts.cairo().fontFamily,
      ),
  textAlign: TextAlign.center,
),
```
<img src="https://github.com/flutter/flutter/assets/114701208/ed6f89cc-7fae-4a1f-9254-38a232a2c217" width="auto" height="200">

It must be noted that this problem also appears when using other textThemes not just headlineMedium.

Here's how it should look like (added height: 1.6 in TextStyle):
```dart
Text(
  'ولما كان تناسي حقوق الإنسان وازدراؤها قد أفضيا إلى أعمال همجية',
  style: Theme.of(context).textTheme.headlineMedium?.copyWith(
        fontFamily: GoogleFonts.cairo().fontFamily,
        height: 1.6,
      ),
  textAlign: TextAlign.center,
),
```
<img src="https://github.com/flutter/flutter/assets/114701208/3103097c-29e5-415c-9f82-ba4bbe2f0d9d" width="auto" height="200">

Here's the same text but using different Arabic fonts:
<img src="https://github.com/flutter/flutter/assets/114701208/91fd9bc8-c04e-47df-b85c-aff0d488029c" width="auto" height="700">

### Proposal

It would be convenient if the default height value of TextStyle could be adjusted from ThemeData for the whole app.

**Comment by huycozy** [comment]
You can definitely do this as follows:

```dart
theme: ThemeData(
  textTheme: const TextTheme(
    headlineMedium: TextStyle(height: 1.6),
  ),
),
```

Closing the issue as solved. Please write in comments in case I missed something about this proposal. Thanks!

**Comment by jehadhmoudah** [comment]
Yes, that should do, but you'll have to do this for the rest of the typography, I don't mind that, but this wouldn't apply for Text widgets using custom TextStyle classes and not typography from Theme.of(context).textTheme

**Comment by huycozy** [comment]
>but this wouldn't apply for Text widgets using custom TextStyle classes and not typography from Theme.of(context).textTheme

Can you give an example of this issue? I checked this with sample code below but it works as expected:

<img width="500" src="https://github.com/flutter/flutter/assets/104349824/994247db-722e-4edf-85d5-e0cf173e8017">

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        textTheme: const TextTheme(
          headlineMedium: TextStyle(height: 1.6, color: Colors.blueAccent),
        ),
      ),
      home: const MainApp(),
    ),
  );
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Hello, World!', style: Theme.of(context).textTheme.headlineMedium),
            const Text('Hello, World!', style: TextStyle(height: 5.6, color: Colors.lightGreen)),
          ],
        ),
      ),
    );
  }
}

```
</details>

**Comment by jehadhmoudah** [comment]
> You can definitely do this as follows:
> 
> ```dart
> theme: ThemeData(
>   textTheme: const TextTheme(
>     headlineMedium: TextStyle(height: 1.6),
>   ),
> ),
> ```
> 
> Closing the issue as solved. Please write in comments in case I missed something about this proposal. Thanks!

I apologize for the late response and the confusion on my end, this has fixed the issue, Thanks @huycozy !.
