### ISSUE TITLE
Font scaled with Transform.scale has unwanted antialiasing effect

### ISSUE THREAD

**Issue by sma** [flutter/flutter#149472]
### Steps to reproduce

The following images shows 1) the system font, 2) the same font with twice the size, 3) the same font with `textScaler` to double the size, 4) the same font wrapped in `Transform.scale` with `scale 1`, 5) the same font wrapped in `Transform.scale` and `scale: 2`. Observe the vertical antialiasing effect on the last line which I expect to look exactly like the other scaled versions.

I get the same effect both on macOS and with the Chrome browser (on macOS):

<img width="309" alt="image" src="https://github.com/flutter/flutter/assets/14989/fa0b8eb6-a1b3-4372-a235-607d7e6875ad">
<img width="287" alt="image" src="https://github.com/flutter/flutter/assets/14989/7babcfb7-cba8-41d6-8f99-6698dcdd0e63">

It gets more obvious if I stroke the font.

<img width="308" alt="image" src="https://github.com/flutter/flutter/assets/14989/bf708dda-00da-47d5-b46e-03bb4989b560">

I noticed this when I tried to render a pixel font.

I explicitly set the `filterQuality` to `none`, so I'd expect no filtering, even if canvas kit renders the smaller font into a texture and then scales that texture. For comparison, here is a pixel font, I rendered myself by drawing tiny rectangles, again wrapped in a `Transform.scale` widget without filtering:
<img width="205" alt="image" src="https://github.com/flutter/flutter/assets/14989/f739252e-9860-4985-a784-b6d12707daa4">

Unfortunately, the TTF font I found on the internet, that is supposed to be that famous font, doesn't 100% fit, so even the normal version looks a bit distorted. Still, the additional (unwanted) antialiasing effect is still visible:
<img width="353" alt="image" src="https://github.com/flutter/flutter/assets/14989/bb7aa7ee-081b-43ab-ac6a-4a921e06469e">

### Expected results

I expect the `Transform` widget to not add antialiasing.

### Actual results

It gets antialiased.

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    const t = 'Häljo, Qoryd!';
    final s = TextStyle(
        fontSize: 24,
        foreground: Paint()
          ..style = PaintingStyle.stroke // or fill
          ..color = Colors.black);
    return MaterialApp(
      home: Scaffold(
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(t, style: s),
            Text(t, style: s.apply(fontSizeFactor: 2)),
            Text(t, style: s, textScaler: TextScaler.linear(2)),
            Transform.scale(
              scale: 1,
              filterQuality: FilterQuality.none,
              alignment: Alignment.topLeft,
              child: Text(t, style: s),
            ),
            Transform.scale(
              scale: 2,
              filterQuality: FilterQuality.none,
              alignment: Alignment.topLeft,
              child: Text(t, style: s),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 flutter doctor -v
[✓] Flutter (Channel master, 3.23.0-13.0.pre.50, on macOS 14.5 23F79 darwin-x64, locale de-DE)
    • Flutter version 3.23.0-13.0.pre.50 on channel master at /Users/sma/Work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc30104be0 (24 hours ago), 2024-05-31 03:45:23 -0400
    • Engine revision df719e66bd
    • Dart version 3.5.0 (build 3.5.0-203.0.dev)
    • DevTools version 2.36.0-dev.10

[✓] Connected device (2 available)
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 14.5 23F79
      darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome
      125.0.6422.114
```

</details>

**Comment by jonahwilliams** [comment]
Can you explain a bit why its not working as intended? Using FilterQuality with a scale of 2x, will render the text at its original size to an offscreen, then sretch it out 2x when its composited into the parent. That will always introduce aliased edges.

> I explicitly set the filterQuality to none, so I'd expect no filtering

Unfortunately the names of the FilterQuality enum were poorly chosen. none means nearest neightbor filtering. There are some example images on the docs page: https://api.flutter.dev/flutter/dart-ui/FilterQuality.html

**Comment by sma** [comment]
Well, I think, I was under the wrong impression, that the font I used didn't have any antialiasing, but under closer inspection, it seems, it already has, and the scaling just amplifies it. Bad eyesight, I guess.

I zoomed into a "normal" word
<img width="259" alt="image" src="https://github.com/flutter/flutter/assets/14989/b45d967b-014e-407c-acca-cb4c89f3e009">
And the up-scaled version only has antialiasing where the source had it. Looking at "p" and "u", it looks fine.
<img width="497" alt="image" src="https://github.com/flutter/flutter/assets/14989/94c26f06-83f5-43aa-bca7-c249e1f0c1cf">
So my issue is probably that Skia (I tried macOS and Chrome) cannot render text without antialiasing… but that's not this bug report and not something, you can fix. I just found a cool tool, and I think [this fiddle](https://fiddle.skia.org/c/bd4ecf558acc1d29296e0c1a6e960a61) demonstrates that setting the `SkPaint`'s antialiasing value has no effect on text rendering. 

I also tried to set it on the `Paint` like so:
```dart
        foreground: Paint()
          ..isAntiAlias = false
          ..style = PaintingStyle.fill
          ..color = Colors.black);
``` 
but this has no effect.
