### ISSUE TITLE
flutter upgrade 

### ISSUE THREAD

**Issue by MarkBurt** [flutter/flutter#149469]
### Steps to reproduce

flutter upgrade 

### Actual results

Downloading Darwin arm64 Dart SDK from Flutter engine 55eae6864b296dd9f43b2cc7577ec256e5c32a8d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    345      0 --:--:-- --:--:-- --:--:--   344
[/Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip or
        /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip.zip, and cannot find /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip.ZIP, period.

### Logs

Downloading Darwin arm64 Dart SDK from Flutter engine 55eae6864b296dd9f43b2cc7577ec256e5c32a8d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    306      0 --:--:-- --:--:-- --:--:--   306
[/Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip or
        /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip.zip, and cannot find /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip.ZIP, period.

### Flutter Doctor output

markburt@MarkBurtdeMacBook-Pro ~ % flutter doctor -v
Downloading Darwin arm64 Dart SDK from Flutter engine 55eae6864b296dd9f43b2cc7577ec256e5c32a8d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    306      0 --:--:-- --:--:-- --:--:--   306
[/Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip or
        /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip.zip, and cannot find /Library/flutter/bin/cache/dart-sdk-darwin-arm64.zip.ZIP, period.

**Comment by huycozy** [comment]
Hi @MarkBurt 
I see this issue could be caused by some reasons. For instances:

- Due to environment variable settings: https://github.com/flutter/flutter/issues/54175#issuecomment-610213239
- Due to the downloaded file was incomplete: https://github.com/flutter/flutter/issues/99890#issuecomment-1068623077

So, I would suggest you check those comments to see if they work for you. Also, there's a similar open issue describing your case https://github.com/flutter/flutter/issues/66243.
