### ISSUE TITLE
[split_config.arm64_v8a.apk!libflutter.so] issue i tried to solve it but still showing error

### ISSUE THREAD

**Issue by MoeezChohan1089** [flutter/flutter#149441]
Dear sir,
I am facing this issue many times after solving this issue but still showing same error how i can solve this issue
![Screenshot 2024-06-01 002146](https://github.com/flutter/flutter/assets/87126520/13686ca1-559c-4b13-94bd-4eda8890613c)

i checked your message that you are saying that after adding ndk will be solve this issue but i add it many times and still showing error

![Screenshot 2024-06-01 002516](https://github.com/flutter/flutter/assets/87126520/37f13fc9-c14c-49da-9257-79f28d3f2a62)

**Comment by darshankawar** [comment]
@MoeezChohan1089 
Please provide the entire crash log in properly formatted text along with flutter version on which you are seeing this error.
