### ISSUE TITLE
White color appearing on resizing map height

### ISSUE THREAD

**Issue by Athulprakash02** [flutter/flutter#149470]
### Steps to reproduce

1. wrap the map in a container and wrap with stack
2. add a sliding sheet in the same stack
3. adjust the height of the map as we slide the sliding sheet
Initial height of the map is 75% of the screen and slider is 25% of the screen. 
Slider can extent upto 50% of the screen height.

### Expected results

 when the slider goes up map's height decreases and when slider goes down it increases smoothly without any flickers or rendering issues

### Actual results

When the slider goes up a white color is showing on the top of the map and when the slider goes down the white color is showing at the bottom of the screen as the height of the map is getting adjsuted

### Code sample

<details open><summary>Code sample</summary>

```dart
Scaffold(
  body: SafeArea(
      child: Obx(
        () => Stack(
          children: [
            Container(
              height: _controller.mapHeight.value,
              child: Stack(
                children: [
                  GoogleMap(
                    // mapType: MapType.normal,
                    myLocationEnabled: true,
                    // trafficEnabled: true,
                    initialCameraPosition: CameraPosition(
                      target: _controller.currentLocation.value,
                      zoom: 12,
                    ),
                   
                  ),
                  Stack(
                    children: List.generate(
                        _controller.markerWidgets.length, (index) {
                      if (index >=
                          _controller.screenCoordinates.length)
                        return Container(
                        );
                      Offset offset =
                          _controller.screenCoordinates[index];
                      print("dxxx"+offset.dx.toString());
                      print("dyyy"+offset.dy.toString());
                      return Positioned(
                        left: offset.dx,
                        top: offset.dy,
                        child: _controller.markerWidgets[index],
                      );
                    }),
                  )
                ],
              ),
            ),
            Positioned(
                top: _controller.mapHeight / 2 - size.height * .03,
                left: size.width / 2 - size.width * .03,
                child: Visibility(
                    visible: _controller.mapMoving.value,
                    child: Image.asset(
                      'assets/images/drag_pin_green.png',
                      height: size.width * .065,
                      width: size.width * .06,
                    ))),
            Positioned(
                top: 15,
                left: 0,
                right: 0,
                child: PickupSelectionPartWidget(
                    controller: _controller, size: size)),
            Positioned(
              top: 80,
              right: 20,
              child: IconButton(
                onPressed: () {
                  _controller.goToMyLocation();
                },
                icon: Icon(
                  Icons.my_location,
                  color: AppColors.blackOrWhite(context),
                ),
              ),
            ),
            if (_controller.showDestinationBottomSheet.value)
              destinationBottomSheet(size, context),
          
          ],
        ),
      )),
)


 SlidingSheet destinationBottomSheet(Size size, BuildContext context) {
    return SlidingSheet(
      listener: (state) {
        print(state.progress);
        print(_controller.mapHeight);
        // _controller.sheetHeight.value = 1 - state.extent;
        _controller.mapHeight.value =
            size.height * 1 - state.extent;
        _controller.gotoCenterPoint();
        if (_controller.polylineCoordinates.isNotEmpty) {
          _controller.showCompleteRoute();
        }
      },
      // backdropColor: AppColors.invertedBlackOrWhite(context),
      color: AppColors.invertedBlackOrWhite(context),
      elevation: 8,
      cornerRadius: 16,
      snapSpec: const SnapSpec(
        initialSnap: 1,

     
        snap: true,
      
        snappings: [
          0.25,
          0.5,
        ],
      
        positioning: SnapPositioning.relativeToAvailableSpace,
      ),
  
      body: const Center(
        child: Text(''),
      ),
      headerBuilder: (context, state) {
        return DestinationSelectionPartWidget(
            controller: _controller, size: size);
      },
      builder: (context, state) {
     

        return RecentLocationSelectWidget(size: size);

      
      },
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/121153441/5a8faa8d-7c8d-487d-bdb7-77c1a6d39025

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.2 23C64 darwin-arm64, locale en-IN)
    • Flutter version 3.19.5 on channel stable at /Users/technoviaonedi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (9 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/technoviaonedi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Users/technoviaonedi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • D63DB457-C794-426E-842A-748F89D6BA7A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 125.0.6422.113

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Athulprakash02 In order to properly address the issue, please provide us minimal but complete reproducible code without third party package implementation. I see that you seem to be using getx package. Try to use only google_maps_flutter package implementation and see if it still replicates the reported behavior. If yes, provide updated code sample.

**Comment by Athulprakash02** [comment]
@darshankawar Here is the updated code without getx.

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:wtf_sliding_sheet/wtf_sliding_sheet.dart';

class MapScreen extends StatefulWidget {
  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  double mapHeight =double.maxFinite;
  LatLng currentLocation = LatLng(37.77483, -122.41942); //Example location
  bool showDestinationBottomSheet = true;


  

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    

    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            Container(
              height: mapHeight,
              child: Stack(
                children: [
                  GoogleMap(
                    myLocationEnabled: true,
                    initialCameraPosition: CameraPosition(
                      target: currentLocation,
                      zoom: 12,
                    ),
                  ),
                  
                ],
              ),
            ),
          
            
            if (showDestinationBottomSheet)
              destinationBottomSheet(size, context),
          ],
        ),
      ),
    );
  }

  SlidingSheet destinationBottomSheet(Size size, BuildContext context) {
    return SlidingSheet(
      listener: (state) {
        setState(() {
          mapHeight = size.height * (1 - state.extent);
     
        });
      },
      color: Colors.black,
      elevation: 8,
      cornerRadius: 16,
      snapSpec: const SnapSpec(
        initialSnap: 1,
        snap: true,
        snappings: [0.25, 0.5],
        positioning: SnapPositioning.relativeToAvailableSpace,
      ),
      body: const Center(
        child: Text(''),
      ),
      headerBuilder: (context, state) {
        return Container(height: 50,color: Colors.red,);
      },
      builder: (context, state) {
        return Container(height: 300,color: Colors.red,);
      },
    );
  }
}


packages used - google_maps_flutter, wtf_sliding_sheet

**Comment by Athulprakash02** [comment]
@darshankawar  Here is the updated code without getx.
`import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:wtf_sliding_sheet/wtf_sliding_sheet.dart';

class MapScreen extends StatefulWidget {
  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  double mapHeight =double.maxFinite;
  LatLng currentLocation = LatLng(37.77483, -122.41942); //Example location
  bool showDestinationBottomSheet = true;


  

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    

    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            Container(
              height: mapHeight,
              child: Stack(
                children: [
                  GoogleMap(
                    myLocationEnabled: true,
                    initialCameraPosition: CameraPosition(
                      target: currentLocation,
                      zoom: 12,
                    ),
                  ),
                  
                ],
              ),
            ),
          
            
            if (showDestinationBottomSheet)
              destinationBottomSheet(size, context),
          ],
        ),
      ),
    );
  }

  SlidingSheet destinationBottomSheet(Size size, BuildContext context) {
    return SlidingSheet(
      listener: (state) {
        setState(() {
          mapHeight = size.height * (1 - state.extent);
     
        });
      },
      color: Colors.black,
      elevation: 8,
      cornerRadius: 16,
      snapSpec: const SnapSpec(
        initialSnap: 1,
        snap: true,
        snappings: [0.25, 0.5],
        positioning: SnapPositioning.relativeToAvailableSpace,
      ),
      body: const Center(
        child: Text(''),
      ),
      headerBuilder: (context, state) {
        return Container(height: 50,color: Colors.red,);
      },
      builder: (context, state) {
        return Container(height: 300,color: Colors.red,);
      },
    );
  }
}



`
packages used - google_maps_flutter, wtf_sliding_sheet

**Comment by darshankawar** [comment]
> wtf_sliding_sheet

This is still a third party package. Please only provide us reproducible code without third party implementation so as to narrow down the issue with framework or `google_maps_flutter` package or not.

**Comment by Athulprakash02** [comment]
Here is the updated code. I removed the sliding sheet and added buttons to change the size of the map, So it will change the map height to a fixed size and will not adjust dynamically.

```
class MapScreen extends StatefulWidget {
   @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  double mapHeight = double.maxFinite;
  LatLng currentLocation = LatLng(37.77483, -122.41942);
  bool showDestinationBottomSheet = true;

   @override
   Widget build(BuildContext context) {
     Size size = MediaQuery.of(context).size;

    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            Container(
              height: mapHeight,
              child: Stack(
                children: [
                  GoogleMap(
                    mapType: MapType.hybrid,
                    myLocationEnabled: true,
                    initialCameraPosition: CameraPosition(
                      target: currentLocation,
                      zoom: 12,
                    ),
                  ),
                ],
              ),
            ),

            Align(
              alignment: Alignment.bottomCenter,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                      onPressed: () {
                        mapHeight = size.height * .4;
                        setState(() {});
                      },
                      child: Text('Reduce Size')),
                  ElevatedButton(
                      onPressed: () {
                        setState(() {
                          mapHeight = size.height * .7;
                        });
                      },
                      child: Text('Increase Size'))
                ],
              ),
            )
            
          ],
        ),
      ),
    );
   }
}
```

**Comment by darshankawar** [comment]
Thanks for the updated code. I used it using latest stable version and ran it with Android device in which I didn't observe the reported behavior. Are you seeing the behavior on ios or android ?


https://github.com/flutter/flutter/assets/67046386/bd1def8b-d73a-4dda-b02c-c3a84c81df66



<details>
<summary> code </summary>

```

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(MaterialApp(
    home: MapScreen(),
  ));
}

class MapScreen extends StatefulWidget {
  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  double mapHeight = double.maxFinite;
  LatLng currentLocation = LatLng(37.77483, -122.41942);
  bool showDestinationBottomSheet = true;

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;

    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            Container(
              height: mapHeight,
              child: Stack(
                children: [
                  GoogleMap(
                    mapType: MapType.hybrid,
                    myLocationEnabled: true,
                    initialCameraPosition: CameraPosition(
                      target: currentLocation,
                      zoom: 12,
                    ),
                  ),
                ],
              ),
            ),

            Align(
              alignment: Alignment.bottomCenter,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                      onPressed: () {
                        mapHeight = size.height * .4;
                        setState(() {});
                      },
                      child: Text('Reduce Size')),
                  ElevatedButton(
                      onPressed: () {
                        setState(() {
                          mapHeight = size.height * .7;
                        });
                      },
                      child: Text('Increase Size'))
                ],
              ),
            )

          ],
        ),
      ),
    );
  }
}


```

</details>

**Comment by Athulprakash02** [comment]
Thank you for your response. Yes it works fine on android devices. The issue exists only on IOS. Sorry I missed to mention it earlier.

**Comment by darshankawar** [comment]
You are likely hitting https://github.com/flutter/flutter/issues/106335, in which you can follow-up for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
