### ISSUE TITLE
Dart 2 conversion tool or best documentation

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#14944]
With the impending release of a version of Flutter that utilizes Dart 2 it might be a good idea to have a tool that does a conversion or a document describing how you can do a conversion. I know most (all?) changes won't be breaking, but it would be nice to get switched over for code cleanliness and to avoid a legacy.

**Comment by zoechi** [comment]
There is https://github.com/dart-lang/sdk/tree/master/pkg/dartfix

`dartfmt` provides some fixes as well.

``` $ dartfmt -h
Idiomatically formats Dart source code.

Usage:   dartfmt [options...] [files or directories...]
...

Non-whitespace fixes (off by default):
    --fix                            Apply all style fixes.
    --fix-named-default-separator    Use "=" as the separator before named parameter default values.
    --fix-optional-const             Remove "const" keyword inside constant context.
    --fix-optional-new               Remove "new" keyword.
    --fix-doc-comments               Use triple slash for documentation comments.
```

I wouldn't expect any more action here.
Please reopen if you think otherwise.
