### ISSUE TITLE
Flutter Mac App Crashes on Intel CPU Macs When Using Impeller

### ISSUE THREAD

**Issue by yaminet1024** [flutter/flutter#149538]
### Steps to reproduce

flutter create flutter_example
flutter run --enable-impeller -d macos

### Expected results

Run flutter app not crash

### Actual results

crash

```
Crashed Thread:        6  io.flutter.raster

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [95445]

VM Region Info: 0 is not in any region.  Bytes before following region: 4421623808
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1078ca000-1078d2000    [   32K] r-x/r-x SM=COW  ...r_new_example
      
      Thread 6 Crashed:: io.flutter.raster
0   libsystem_platform.dylib      	    0x7ff81a2dba86 _platform_memmove$VARIANT$Haswell + 198
1   FlutterMacOS                  	       0x10acf5ee4 impeller::HostBuffer::EmplaceInternal(void const*, unsigned long) + 260
2   FlutterMacOS                  	       0x10acf5d58 impeller::HostBuffer::Emplace(void const*, unsigned long, unsigned long) + 136
3   FlutterMacOS                  	       0x10b30efd9 impeller::ContentContext::ContentContext(std::_fl::shared_ptr<impeller::Context>, std::_fl::shared_ptr<impeller::TypographerContext>, std::_fl::shared_ptr<impeller::RenderTargetAllocator>) + 3225
4   FlutterMacOS                  	       0x10b2ee1f0 std::_fl::__unique_if<impeller::ContentContext>::__unique_single std::_fl::make_unique[abi:v15000]<impeller::ContentContext, std::_fl::shared_ptr<impeller::Context>&, std::_fl::shared_ptr<impeller::TypographerContext>, std::_fl::shared_ptr<impeller::RenderTargetAllocator>>(std::_fl::shared_ptr<impeller::Context>&, std::_fl::shared_ptr<impeller::TypographerContext>&&, std::_fl::shared_ptr<impeller::RenderTargetAllocator>&&) + 128
5   FlutterMacOS                  	       0x10b2ee0c7 impeller::AiksContext::AiksContext(std::_fl::shared_ptr<impeller::Context>, std::_fl::shared_ptr<impeller::TypographerContext>, std::_fl::optional<std::_fl::shared_ptr<impeller::RenderTargetAllocator>>) + 151
6   FlutterMacOS                  	       0x10b4ac379 std::_fl::__shared_ptr_emplace<impeller::AiksContext, std::_fl::allocator<impeller::AiksContext>>::__shared_ptr_emplace[abi:v15000]<std::_fl::shared_ptr<impeller::Context> const, std::_fl::shared_ptr<impeller::TypographerContext>>(std::_fl::allocator<impeller::AiksContext>, std::_fl::shared_ptr<impeller::Context> const&&, std::_fl::shared_ptr<impeller::TypographerContext>&&) + 105
7   FlutterMacOS                  	       0x10b4aa692 flutter::GPUSurfaceMetalImpeller::GPUSurfaceMetalImpeller(flutter::GPUSurfaceMetalDelegate*, std::_fl::shared_ptr<impeller::Context> const&, bool) + 450
8   FlutterMacOS                  	       0x10b4db8f0 flutter::EmbedderSurfaceMetalImpeller::CreateGPUSurface() + 96
9   FlutterMacOS                  	       0x10b4d8281 flutter::PlatformViewEmbedder::CreateRenderingSurface() + 49
10  FlutterMacOS                  	       0x10b3c2ccb std::_fl::__function::__func<flutter::PlatformView::NotifyCreated()::$_0, std::_fl::allocator<flutter::PlatformView::NotifyCreated()::$_0>, void ()>::operator()() + 43
11  FlutterMacOS                  	       0x10ac277da fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 266
12  FlutterMacOS                  	       0x10ac302ec fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 44
```

### Code sample

flutter create flutter_example

### Logs

HostBuffer::EmplaceInternal memmove crash
<img width="980" alt="企业微信截图_d96c9eb6-7bf8-4bc5-ba08-4161ab155925" src="https://github.com/flutter/flutter/assets/23304639/945aa430-c9b1-4480-8387-89dc9c6946e6">

storage_mode_ is MTLStorageModeManaged
<img width="820" alt="企业微信截图_6b821fd4-75ed-45d7-86f1-96798ca084bd" src="https://github.com/flutter/flutter/assets/23304639/c76a11ea-a17d-4c05-94c0-156c74ccadfc">

### Flutter Doctor output

```
[!] Flutter (Channel [user-branch], 3.22.1, on macOS 13.6.1 22G313 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.22.1 on channel [user-branch] at /Users/yami/fvm/versions/stable
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[!] Network resources
    ✗ A cryptographic error occurred while checking "https://cocoapods.org/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your computer.

! Doctor found issues in 3 categories.
```

**Comment by darshankawar** [comment]
@yaminet1024 
I have intel mac machine (running Monterey version 12.2.1) and created a new flutter project in latest stable which didn't trigger any crash. The macOS app compiled and built properly as below:

<img width="998" alt="Screenshot 2024-06-03 at 3 37 45 PM" src="https://github.com/flutter/flutter/assets/67046386/d5720c48-7725-4a40-9f2c-76f3ddf10a7d">

I see that your flutter doctor version shows you are on unknown channel. Can you switch to stable properly and check again ?
Also, do you get the crash everytime you try to run / create new flutter project or existing one ?

**Comment by yaminet1024** [comment]
> @yaminet1024 I have intel mac machine (running Monterey version 12.2.1) and created a new flutter project in latest stable which didn't trigger any crash. The macOS app compiled and built properly as below:
> 
> <img alt="Screenshot 2024-06-03 at 3 37 45 PM" width="998" src="https://private-user-images.githubusercontent.com/67046386/336030318-d5720c48-7725-4a40-9f2c-76f3ddf10a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTEyODcsIm5iZiI6MTcxNzQxMDk4NywicGF0aCI6Ii82NzA0NjM4Ni8zMzYwMzAzMTgtZDU3MjBjNDgtNzcyNS00YTQwLTlmMmMtNzZmM2RkZjEwYTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEwMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTIyZGY0MTc1ZjhiMDM3ZTU1MGVlZjdhZGY0MmE4MmNlZmMxYjFiZDU4N2RjOWU4ZjI1MWM5ZDI2Y2RhZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-1uC2HTuYLfvc_NdHga7dcnb6w-CufyBMyq6oppeGc0">
> I see that your flutter doctor version shows you are on unknown channel. Can you switch to stable properly and check again ? Also, do you get the crash everytime you try to run / create new flutter project or existing one ?

hi，thanks,I manually switched to the 3.22.1 tag, so it shows as "unknown channel." I believe it is the same as the stable channel. I have tried both the stable and master channels, and I experience the same crash every time on this machine. It seems that this issue can only be reproduced on certain specific machine models.

**Comment by darshankawar** [comment]
> certain specific machine models.

Can you provide macOS details as below:

<img width="587" alt="Screenshot 2024-06-04 at 11 15 19 AM" src="https://github.com/flutter/flutter/assets/67046386/e7ca55a8-d0a4-47d1-9c5a-ce6e13247a30">
