### ISSUE TITLE
Flutter doctor not running on Windows CMD 

### ISSUE THREAD

**Issue by toufikImk** [flutter/flutter#14950]
I intended to set up flutter for my Windows desktop so i followed the steps as explained in the flutter website, but when running 

> flutter doctor 
i get this error 
 **The Flutter directory is not a clone of the GitHub project**

**Comment by raditha** [comment]
What is the directory name of the flutter sdk which you have pointed your environment variable?

**Comment by tvolkert** [comment]
This is in the tool bootstrap:

https://github.com/flutter/flutter/blob/621a963e8b495c5f39e0df3e6d918184c8ade917/bin/flutter.bat#L40

**Comment by renasti** [comment]
Only install by line code git hub this problem solved.
