### ISSUE TITLE
unable to 'pub upgrade' flutter tool

### ISSUE THREAD

**Issue by dhiraj7072** [flutter/flutter#14959]
unable to 'pub upgrade' flutter tool try everything but don't fix it this error please help me I am exited to develop apps in flutter after reinstall my system but this cant fix

**Comment by cbracken** [comment]
@dhiraj7072 can you provide more details?
1. The output of `flutter doctor --verbose`
1. The output of the command you ran, ideally with the `--verbose` option specified.

**Comment by dhiraj7072** [comment]
same output ..unable to pub upgrade flutter tool

**Comment by dhiraj7072** [comment]
any solution for this..?

**Comment by dhiraj7072** [comment]
i tried everything reinstalling windows 10 reinstalling flutter ..but same error i am facing unable to pub upgrade .@cbracken

**Comment by dhiraj7072** [comment]
@cbracken  i am using windows 10 pro

**Comment by InMatrix** [comment]
@dhiraj7072 In case you're using Flutter in China, please follow these instructions: https://github.com/flutter/flutter/wiki/Using-Flutter-in-China 

Please let us know if it's helpful.

**Comment by dhiraj7072** [comment]
![capture](https://user-images.githubusercontent.com/17934296/36832802-0646bb0c-1d53-11e8-8d35-da538b8942da.PNG)

**Comment by dhiraj7072** [comment]
@InMatrix  same issue

**Comment by dhiraj7072** [comment]
@InMatrix  any solution ..?

**Comment by DanTup** [comment]
I had a self-inflicted similar issue. I had deleted some stuff out of the cache folder (trying to test something) but must've left enough that flutter through it had local tools that it didn't. Nuking my bin folder then doing a git reset to get back the repository version of the bin folder fixed it.

**Comment by dhiraj7072** [comment]
really ... that's great ..@DanTup can you explain in detail ..like how to git reset to get back the repository version of the bin folder ..whats command you used...thanks DanTup

**Comment by DanTup** [comment]
I deleted the whole `bin` folder and then ran `git reset --hard` (be careful where you run this!) to get my working copy back to how it was in the repository (this re-created the bin folder and the `flutter`/`flutter.bat` inside it.

**Comment by dhiraj7072** [comment]
![capture2](https://user-images.githubusercontent.com/17934296/36853201-d3314232-1d93-11e8-8095-4b1ff693c89d.PNG)

**Comment by dhiraj7072** [comment]
@DanTup  deleted bin folder and than run git reset --hard in flutter folder it goes a error that HEAD is now at eaa9848fd Improve error message for missing 32-bit libstc++ (#15004)

**Comment by dhiraj7072** [comment]
@DanTup bin folder is recreated but when i ran flutter doctor command same error unable to pub upgrade flutter tools

**Comment by DanTup** [comment]
@dhiraj7072 The message you got from `git reset` is normal, not an error - the word error is just in the commit message :)

If that didn't fix it, then it's probably not a result of your bin folder being in the same state mine was :(

**Comment by dhiraj7072** [comment]
@DanTup  any solution for this..?

**Comment by DanTup** [comment]
@dhiraj7072 I'm afraid I don't know much about how this works, however I had a look inside the `flutter.bat` file and it seems this is the loop it's stuck in:

```text
      :retry_pub_upgrade
      CALL "%pub%" upgrade --verbosity=error --no-packages-dir
      IF "%ERRORLEVEL%" NEQ "0" (
        ECHO Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
        timeout /t 5 /nobreak
        GOTO :retry_pub_upgrade
      )
```

And the paths are set like this:

```
FOR %%i IN ("%~dp0..") DO SET FLUTTER_ROOT=%%~fi
SET cache_dir=%FLUTTER_ROOT%\bin\cache
SET dart_sdk_path=%cache_dir%\dart-sdk
SET pub=%dart_sdk_path%\bin\pub.bat
```

So, first thing I would try is running the pub command manually like this:

```
cd packages\flutter_tools
..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --no-packages-dir
```

This will put you into the `flutter_tools` folder (which is where that script runs pub) and then runs pub (but without `--verbosity=error` which means it won't hide warnings and other user messages).

Hopefully that'll give more useful output!

**Comment by goderbauer** [comment]
Can you run the following in your command line and post the output?

```
cd packages\flutter_tools
..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --verbose
```

**Comment by dhiraj7072** [comment]
@goderbauer  The system cannot find the path specified.

**Comment by goderbauer** [comment]
When are you seeing that? After the first or second command?

Does `bin\cache\dart-sdk\bin\pub.bat` exist inside your flutter checkout?

**Comment by dhiraj7072** [comment]
@goderbauer 

Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Dhiraj>cd flutter\flutter\packages\flutter_tools

C:\Users\Dhiraj\flutter\flutter\packages\flutter_tools>..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --verbose
FINE: Pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
IO  : Spawning "cmd /c ver" in C:\Users\Dhiraj\flutter\flutter\packages\flutter_tools\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.10240]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - coverage 0.10.0 from hosted (coverage)
    | - test 0.12.30+4 from hosted (test)
    | - file 2.3.6 from hosted (file)
    | - mustache 1.0.0 from hosted (mustache)
    | - meta 1.1.2 from hosted (meta)
    | - web_socket_channel 1.0.7 from hosted (web_socket_channel)
    | - http 0.11.3+16 from hosted (http)
    | - xml 2.6.0 from hosted (xml)
    | - json_rpc_2 2.0.7 from hosted (json_rpc_2)
    | - stream_channel 1.6.3 from hosted (stream_channel)
    | - process 2.0.7 from hosted (process)
    | - vm_service_client 0.2.4+1 from hosted (vm_service_client)
    | - front_end any from hosted (front_end)
    | - linter 0.1.43 from hosted (linter)
    | - quiver 0.28.0 from hosted (quiver)
    | - args 1.3.0 from hosted (args)
    | - package_config 1.0.3 from hosted (package_config)
    | - crypto 2.0.2+1 from hosted (crypto)
    | - platform 2.1.2 from hosted (platform)
    | - plugin 0.2.0+2 from hosted (plugin)
    | - stack_trace 1.9.1 from hosted (stack_trace)
    | - usage 3.3.0 from hosted (usage)
    | - intl 0.15.2 from hosted (intl)
    | - archive 1.0.33 from hosted (archive)
    | - cli_util 0.1.2+1 from hosted (cli_util)
    | - json_schema 1.0.8 from hosted (json_schema)
    | - yaml 2.1.13 from hosted (yaml)
    | - analyzer any from hosted (analyzer)
IO  : Get versions from https://pub.dartlang.org/api/packages/coverage.
IO  : HTTP GET https://pub.dartlang.org/api/packages/coverage
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: upgrade
    | X-Pub-Session-ID: 1FE0AFC7-BD89-4465-8FD3-5E99DFA8B892
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0

C:\Users\Dhiraj\flutter\flutter\packages\flutter_tools>

**Comment by dhiraj7072** [comment]
@goderbauer 

C:\Users\Dhiraj>cd flutter\flutter\packages\flutter_tools

C:\Users\Dhiraj\flutter\flutter\packages\flutter_tools>..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --verbose
FINE: Pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
IO  : Spawning "cmd /c ver" in C:\Users\Dhiraj\flutter\flutter\packages\flutter_tools\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.10240]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - coverage 0.10.0 from hosted (coverage)
    | - test 0.12.30+4 from hosted (test)
    | - file 2.3.6 from hosted (file)
    | - mustache 1.0.0 from hosted (mustache)
    | - meta 1.1.2 from hosted (meta)
    | - web_socket_channel 1.0.7 from hosted (web_socket_channel)
    | - http 0.11.3+16 from hosted (http)
    | - xml 2.6.0 from hosted (xml)
    | - json_rpc_2 2.0.7 from hosted (json_rpc_2)
    | - stream_channel 1.6.3 from hosted (stream_channel)
    | - process 2.0.7 from hosted (process)
    | - vm_service_client 0.2.4+1 from hosted (vm_service_client)
    | - front_end any from hosted (front_end)
    | - linter 0.1.43 from hosted (linter)
    | - quiver 0.28.0 from hosted (quiver)
    | - args 1.3.0 from hosted (args)
    | - package_config 1.0.3 from hosted (package_config)
    | - crypto 2.0.2+1 from hosted (crypto)
    | - platform 2.1.2 from hosted (platform)
    | - plugin 0.2.0+2 from hosted (plugin)
    | - stack_trace 1.9.1 from hosted (stack_trace)
    | - usage 3.3.0 from hosted (usage)
    | - intl 0.15.2 from hosted (intl)
    | - archive 1.0.33 from hosted (archive)
    | - cli_util 0.1.2+1 from hosted (cli_util)
    | - json_schema 1.0.8 from hosted (json_schema)
    | - yaml 2.1.13 from hosted (yaml)
    | - analyzer any from hosted (analyzer)
IO  : Get versions from https://pub.dartlang.org/api/packages/coverage.
IO  : HTTP GET https://pub.dartlang.org/api/packages/coverage
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: upgrade
    | X-Pub-Session-ID: 6C35AA63-5CE0-46A1-B2E2-C5316F496652
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0

C:\Users\Dhiraj\flutter\flutter\packages\flutter_tools>flutter doctoor
Updating flutter tool...
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 0 seconds, press CTRL+C to quit ...

**Comment by dhiraj7072** [comment]
@goderbauer any solution for this..?

**Comment by goderbauer** [comment]
@munificent Any idea why pub just terminates in the log above half-way through `pub upgrade`?

**Comment by dhiraj7072** [comment]
@goderbauer  i tried everything reinstalling my windows 10 reinstalling flutter , git..but nothing work ..tried since 3 days please help me

**Comment by luccasclezar** [comment]
I'm having exactly the same issue, `flutter doctor` simply exits after this:

```
IO  : Get versions from https://pub.dartlang.org/api/packages/coverage.
IO  : HTTP GET https://pub.dartlang.org/api/packages/coverage
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: upgrade
    | X-Pub-Session-ID: 5D9B849A-B2E2-4086-B264-2DBA12ACCE3D
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
```

**Comment by mraleph** [comment]
We can try to debug it using observatory. @dhiraj7072 @luccasclezar can you try this in the command line, assuming that  `%FLUTTER_DIR%` is a directory where you installed Flutter?

```
cd %FLUTTER_DIR%\packages\flutter_tools
set DART_VM_OPTIONS=--observe --pause-isolates-on-start
..\..\bin\cache\dart-sdk\bin\pub.dart upgrade --verbose
```

You should be able to see something like this on the command line:

```
vm-service: isolate(480220066) 'pub.dart.snapshot:main()' has no debugger attached and is paused at start.  Connect to Observatory to debug.
Observatory listening on http://127.0.0.1:8181/
```

Then in the browser (e.g. Chrome) navigate to `http://127.0.0.1:8181/`. 

You should see a page like this:

![screen-1](https://user-images.githubusercontent.com/131846/36913929-c2596468-1e4b-11e8-9814-568ccf2437b7.png)

Click on the *debug*. You should get into the debugger:

![screen-2](https://user-images.githubusercontent.com/131846/36913961-ed4ba9ba-1e4b-11e8-835c-75a8aa10ee8d.png)

Here please type `break exit`, press ENTER, then when you see `Future breakpoint 1 added`, type `break flushThenExit` and press ENTER again (breakpoint setting might take a few seconds because optimized code is being discarded).

![screen shot 2018-03-02 at 7 01 03 pm](https://user-images.githubusercontent.com/131846/36914059-3ee1f2a2-1e4c-11e8-9cc9-bcfec48cdca7.png)

Then type `continue` and press ENTER. The `pub` should start running. At some point it will hit `exit` breakpoint and stop. 

Screenshot that for us, it will look something like this:

![screen shot 2018-03-02 at 7 03 57 pm](https://user-images.githubusercontent.com/131846/36914123-7f5704c6-1e4c-11e8-95e7-6839c0c3ba92.png)

If the pub exits without hitting the breakpoint we would like to know that too. 

Thanks! 

I am around on Gitter if you would like me to guide you through this interactively.

**Comment by mraleph** [comment]
Actually ignore my last comment. Instead first try this in command line @luccasclezar 

```
set DART_VM_OPTIONS=--idle_timeout_micros=200000000
flutter doctor
```

**Comment by NathanaelA** [comment]
For others who are running into a similar issue of it looping -- Another reason has already been fixed on master a couple days ago.   

Assuming `%flutter%` is your path to flutter:
If you have a `dart-sdk`  in the `%flutter%/$cachePath` then the download was fine, but the extraction was not.  To easily recover from this state manually move the `dart-sdk` folder from the `%flutter%/$cachePath` to `%flutter%/bin/cache/dart-sdk`  and then run `flutter upgrade` again.

**Comment by Hixie** [comment]
Can anyone who is still seeing please try to download Flutter again but instead of writing "beta", write "master" when doing the git clone, and see if the problem still happens?

If it does not then I am confident that this is resolved and the fix will be included in the next beta in a few weeks, and we can close this bug. If it still happens, though, we'll need to figure out why and fix it.

**Comment by luccasclezar** [comment]
I can confirm this issue only happens in beta. This is my output when using the master branch:

```
PS C:\> git clone -b beta https://github.com/flutter/flutter.git
Cloning into 'flutter'...
PS C:\> git clone -b master https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Counting objects: 114257, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 114257 (delta 0), reused 1 (delta 0), pack-reused 114254
Receiving objects: 100% (114257/114257), 34.29 MiB | 973.00 KiB/s, done.
Resolving deltas: 100% (85406/85406), done.
Checking out files: 100% (2433/2433), done.
PS C:\> flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 97b22348c8d5cba471418dc94f9e384e384e796f...
Unzipping Dart SDK...
Updating flutter tool...
Downloading Material fonts...                                3,6s
Downloading package sky_engine...                            2,5s
Downloading common tools...                                  3,3s
Downloading windows-x64 tools...                             8,8s
Downloading android-arm-profile/windows-x64 tools...         2,4s
Downloading android-arm-release/windows-x64 tools...         2,3s
Downloading android-arm64-profile/windows-x64 tools...       3,9s
Downloading android-arm64-release/windows-x64 tools...       3,8s
Downloading android-x86 tools...                             7,6s
Downloading android-x64 tools...                             7,4s
Downloading android-arm tools...                             4,8s
Downloading android-arm-profile tools...                     4,0s
Downloading android-arm-release tools...                     3,7s
Downloading android-arm64 tools...                           6,8s
Downloading android-arm64-profile tools...                   4,0s
Downloading android-arm64-release tools...                   6,6s
Downloading Gradle Wrapper...                                0,8s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.1.8-pre.38, on Microsoft Windows [versÃ£o 10.0.16299.248], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.0)
[√] VS Code, 64-bit edition (version 1.20.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
PS C:\>
```

**Comment by Hixie** [comment]
Great! I'm going to close this for now since we believe we've resolved it. The fix will be published to the beta branch with the next beta roll in a few weeks.

**Comment by heath3n** [comment]
This is happening for me on `master`.  I've deleted the entire Flutter directory and re-cloned from GitHub:

```
C:\Development>flutter doctor -v
Checking Dart SDK version...
Flutter requires PowerShell 5.0 or newer.
See https://flutter.io/docs/get-started/install/windows for more.
Building flutter tool...
Running pub upgrade...
The system cannot find the path specified.
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries
 left)

Waiting for 2 seconds, press CTRL+C to quit ...
```

**Comment by zoechi** [comment]
@heath3n probably a network issue

**Comment by DanTup** [comment]
> Flutter requires PowerShell 5.0 or newer.

I think this is your problem. The update script quits after printing that message:

https://github.com/flutter/flutter/blob/e99c881f8d0e63042af6e2a3f6182c3ca6967442/bin/internal/update_dart_sdk.ps1#L30-L32

Which means it doesn't download the SDK, which means there will be no `pub.bat`.

What OS are you on? Can you upgrade to PowerShell 5.0?

**Comment by heath3n** [comment]
Upgrading solved it (I'm on Windows 8.1 but have not touched PowerShell since I got this machine five years ago). I was just a bit confused as I have been using Flutter since August without issue and when trying to switch from `dev` to `master` got some issues that prompted me to reinstall, at which point I started getting this issue. Thanks for opening that issue to make the message clearer.

**Comment by DanTup** [comment]
Seems like it was documented that PoSh 5 was required some time ago (#917) but only recently was the install script made to check (#27596). Glad you're sorted now!

**Comment by Fortune-Muhumuza** [comment]
Running flutter doctor from the flutter console itself worked for me

**Comment by cumanbacafypdoang240** [comment]
> @dhiraj7072 I'm afraid I don't know much about how this works, however I had a look inside the `flutter.bat` file and it seems this is the loop it's stuck in:
> 
> ```text
>       :retry_pub_upgrade
>       CALL "%pub%" upgrade --verbosity=error --no-packages-dir
>       IF "%ERRORLEVEL%" NEQ "0" (
>         ECHO Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
>         timeout /t 5 /nobreak
>         GOTO :retry_pub_upgrade
>       )
> ```
> 
> And the paths are set like this:
> 
> ```
> FOR %%i IN ("%~dp0..") DO SET FLUTTER_ROOT=%%~fi
> SET cache_dir=%FLUTTER_ROOT%\bin\cache
> SET dart_sdk_path=%cache_dir%\dart-sdk
> SET pub=%dart_sdk_path%\bin\pub.bat
> ```
> 
> So, first thing I would try is running the pub command manually like this:
> 
> ```
> cd packages\flutter_tools
> ..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --no-packages-dir
> ```
> 
> This will put you into the `flutter_tools` folder (which is where that script runs pub) and then runs pub (but without `--verbosity=error` which means it won't hide warnings and other user messages).
> 
> Hopefully that'll give more useful output!

I went through the same thing and always spam cmd.exe

I'm using Google Translate
