### ISSUE TITLE
Black Screen and Navigation Errors After Adding Product in Flutter App

### ISSUE THREAD

**Issue by protheeuz** [flutter/flutter#149581]
**Expected Behavior**
After successfully adding a product, the user should be navigated back to the previous screen (dashboard or product list) with a confirmation message indicating the product was added.

**Actual Behavior**
After successfully adding a product, the screen turns black. Additionally, upon refreshing, the app displays the following error:
`════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#85e6a](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope], state: NavigatorState#8259d(tickers: tracking 0 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5339 pos 12: '_history.isNotEmpty': is not true.
navigator.dart:5339
`

**Flutter Doctor**
`[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22631.3593], locale en-ID)
    • Flutter version 2.5.3 at C:\Users\iqbal\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 years, 8 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\iqbal\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\iqbal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • CPH1909 (mobile) • OZUSOBVSL7KNRKON • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 125.0.6422.78
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 125.0.2535.79

• No issues found!`

**Additional Information**
Flutter version: `2.5.3`
Platform: `Android`

Thank you for your assistance in resolving this issue.

**Comment by darshankawar** [comment]
@protheeuz 
You are on very old version of stable and your issue is better suited for support channels like stackoverflow.
Closing from here, as this is more of a code assistance issue rather than bug.
