### ISSUE TITLE
Cannot execute flutter commands if the flutter sdk directory folder name starts with !

### ISSUE THREAD

**Issue by raditha** [flutter/flutter#14951]
## Steps to Reproduce
Set the Environment variable for flutter sdk path from a directory name starting with "!" and run the command "flutter doctor"

**Comment by cbracken** [comment]
@raditha thanks for reporting! Would you mind including the output you get in this scenario? It would be useful to know what OS you're running on as well.

**Comment by Hixie** [comment]
The following seemed to work fine for me on Linux:

```bash
mkdir bug14951; cd bug14951
curl https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v0.4.4-beta.tar.xz | tar xJ
mv 'flutter' '!flutter'
cd '!flutter'
bin/flutter doctor
```

Please let us know if this still occurs for you. For now I will close this issue since we don't have enough information to act on. If you do still see this please file a new bug with as much information as you can provide. Thanks!
