### ISSUE TITLE
[in_app_purchase] queryProductDetails returns empty product list on android

### ISSUE THREAD

**Issue by giantss** [flutter/flutter#149582]
### Steps to reproduce

I used the third-party plugin `flutter_inapp_purchase: ^5.4.2` before, and Apple and Google internal purchase subscriptions have been connected and are now online. This plugin seems to be no longer maintained, and I plan to migrate to the official plugin `in_app_purchase` recently.
However, when debugging the plugin, I found that the original product id was used to obtain an empty list on Android.（Product details can be obtained normally on ios.）

I can confirm that these product IDs are valid and can be paid normally in the `flutter_inapp_purchase`  plugin.

I don't understand why this doesn't happen, or is there something else I need to configure?

Steps:
1. Copy the complete demo code into my project.
2. Modify the code like this.
```
const List<String> _kProductIds = <String>[
  'hsk_91', // consumable1
  'hsk_92', // consumable2
  'hsk_93' // subscription
  // _kConsumableId,
  // _kUpgradeId,
  // _kSilverSubscriptionId,
  // _kGoldSubscriptionId,
];

```
3. Put a breakpoint on the following line and run.
```
final ProductDetailsResponse productDetailResponse = await _inAppPurchase.queryProductDetails(_kProductIds.toSet());
```

### Expected results

queryProductDetails returns no empty product list.

### Actual results

queryProductDetails returns empty product list.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1280" alt="image" src="https://github.com/flutter/flutter/assets/13778798/68c95604-bc6b-47e0-9e16-81dcddf275b1">
<img width="663" alt="image" src="https://github.com/flutter/flutter/assets/13778798/a82e3f04-d4f5-4fa1-8ace-53c8a2ccd2d6">

<img width="526" alt="image" src="https://github.com/flutter/flutter/assets/13778798/74eb9975-e771-4758-8eb0-a244c37dfebc">
 
![image](https://github.com/flutter/flutter/assets/13778798/af079b37-54b9-44f8-a8c1-a2a53248fc24)

![image](https://github.com/flutter/flutter/assets/13778798/67a2c235-800d-4453-a03e-eb73fa3777b7)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.19.5 on channel stable at /Users/zhongpeng/file/env/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (10 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhongpeng/Library/Android/sdk
    • Platform android-34, build-tools 30.0.3
    • ANDROID_HOME = /Users/zhongpeng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (3 available)
    • SM G9860 (mobile) • R5CNA066R2E • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 14.4.1 23E224 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 125.0.6422.114
    ! Error: Browsing on the local area network for 测试SE. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Wennie. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by awais019** [comment]
Have to signed baking and purchase agreement on appstoreconnect?

**Comment by giantss** [comment]
@awais019   Hello, I don't quite understand what you mean, could you describe it in more detail?

**Comment by awais019** [comment]
You need to sign agreement on app store connect to use in app purchases

**Comment by giantss** [comment]
Yes, it is necessary. @awais019

**Comment by awais019** [comment]
I'm also facing an error while implementing buy non consumable, Execution stops at retrieve receipt data, and app crashes before buying. Do you know how can I solve it

**Comment by darshankawar** [comment]
@giantss 
Can you provide a minimal reproducible code sample that shows the reported behavior ?

**Comment by giantss** [comment]
[my_new_app.zip](https://github.com/user-attachments/files/15541399/my_new_app.zip)
@darshankawar

**Comment by darshankawar** [comment]
@giantss 
I suggest you to go through Flutter's package implementation https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example and also https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#0 to see if there's anything missing from code implementation point of view in your setup.

**Comment by giantss** [comment]
Thank you for the information you provided. I have checked it and have not found any missing parts. When I use the `flutter_inapp_purchase: ^5.4.2` plugin, everything works perfectly. According to my reproduction steps, I copied the code in the demo to my project and only changed `_kProductIds` to the valid product id configured by my Google backend. Why can't I get it with just this one change? The environment is exactly the same.

**Comment by giantss** [comment]
I found a clue. When the product list is returned empty, the console will output two identical logs. But I don't know how to solve it?
<img width="970" alt="image" src="https://github.com/flutter/flutter/assets/13778798/cbccd2e0-547f-4839-9a79-4b7f9057eaaf">
@darshankawar

**Comment by darshankawar** [comment]
The log says `getSkuDetails() failed for queryProductDetailsAsync()`. Check the response code which is 3 and see what it represents. You may check below links for further reference:

https://stackoverflow.com/questions/55742321/billingclient-getskudetails-failed-response-code-6

https://www.reddit.com/r/androiddev/comments/120mgbc/handling_inapp_subscriptions_status/

**Comment by giantss** [comment]
> 日志显示`getSkuDetails() failed for queryProductDetailsAsync()`。检查响应代码 3，看看它代表什么。您可以查看以下链接以获取进一步参考：
> 
> https://stackoverflow.com/questions/55742321/billingclient-getskudetails-failed-response-code-6
> 
> https://www.reddit.com/r/androiddev/comments/120mgbc/handling_inapp_subscriptions_status/

Thanks for your reply, but I still have no progress on this problem on Android.

**Comment by giantss** [comment]
`6. Build a signed apk. flutter build apk will work for this, the gradle files in this project have been configured to sign even debug builds.`

`7. Upload the signed APK from step 6 to the PDC, and publish that to the alpha test channel. Add your test account as an approved tester. The BillingClient APIs won't work unless the app has been fully published to the alpha channel and is being used by an authorized test account. See [here](https://support.google.com/googleplay/android-developer/answer/3131213) for more info.`

Are these two steps necessary?  My situation is a little different. I am replacing the plugin instead of using it for the first time, so the product IDs are also created in advance (the ones that are being used online).
@darshankawar
