### ISSUE TITLE
Google maven repository is old in flutter.gradle

### ISSUE THREAD

**Issue by tohosokawa** [flutter/flutter#14954]
https://github.com/flutter/flutter/blob/6993b203c05477fec537f566be7ff7fbf072d33b/packages/flutter_tools/gradle/flutter.gradle#L23

This repository URL returns 301 Moved Permanently.

And redirect location is "https://dl.google.com/dl/android/maven2/index.html"

Now, the generated build.gradle by Android studio use `google()`, like following.

build.gradle
``` 
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}
```

https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/RepositoryHandler.java#L225

Is there any reason for this? Could you update this maven repository URL?

Because I ran into the following build error.
And the easiest solution I have found is using `google()`.

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve com.android.tools.build:gradle:3.0.1.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve com.android.tools.build:gradle:3.0.1.
         > Could not get resource 'https://maven.google.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
            > Could not HEAD 'https://maven.google.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by mravn-google** [comment]
Thanks for making us aware of this!

The reason for not using `google()` is to have Flutter tooling backwards compatible with Flutter projects created before we switched from Gradle 3.x to Gradle 4.x.

I'll update the URL.

**Comment by tohosokawa** [comment]
Thanks for your quick answer and fix.
