### ISSUE TITLE
[CP] Fix TwoDimensionalViewport's keep alive child not always removed (when no longer should be kept alive)

### ISSUE THREAD

**Issue by gawi151** [flutter/flutter#149588]
### Issue Link

https://github.com/flutter/flutter/issues/138977

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/149639

### Changelog Description

Fix of TwoDimentionalViewport's child rendering crash when using keep alive widgets (e.g InkWell).

### Impacted Users

Apps using TwoDimentionalViewport with Material components on desktop/web. Especially users of https://pub.dev/packages/two_dimensional_scrollables .

### Impact Description

Crash when rendering children in TwoDimentionalViewport. Cells stop to render.

### Workaround

Stay on Flutter 3.13 or don't use Material Ink splash related components in 2D viewport.

### Risk

low

### Test Coverage

yes

### Validation Steps

https://github.com/flutter/flutter/issues/138977 issue has reproducible code

**Comment by itsjustkevin** [comment]
@gawi151, please provide a link to the cherry-pick from main to the stable branch and update the `Pr Link`, before review.

**Comment by gawi151** [comment]
> @gawi151, please provide a link to the cherry-pick from main to the stable branch and update the `Pr Link`, before review.

Oh sorry about that. Yeah I do it asap.

**Comment by gawi151** [comment]
@itsjustkevin I created a CP PR and linked it here in the issue.

**Comment by itsjustkevin** [comment]
This cherry-pick seems to be failing tests on the candidate branch. 

@Piinks, could you take a Quick Look?

**Comment by Piinks** [comment]
The failures all appear to be infrastructure errors. I'll see if I can kick the tests
