### ISSUE TITLE
takePicture() CameraException.code: cannotCreateFile only on Release Build

### ISSUE THREAD

**Issue by EntwicklungPS** [flutter/flutter#149654]
### What package does this bug report belong to?

camera

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.2"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.1"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.9.0"
  audioplayers:
    dependency: "direct main"
    description:
      name: audioplayers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.1.0"
  audioplayers_android:
    dependency: transitive
    description:
      name: audioplayers_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  audioplayers_darwin:
    dependency: transitive
    description:
      name: audioplayers_darwin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.1.0"
  audioplayers_linux:
    dependency: transitive
    description:
      name: audioplayers_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  audioplayers_platform_interface:
    dependency: transitive
    description:
      name: audioplayers_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.1"
  audioplayers_web:
    dependency: transitive
    description:
      name: audioplayers_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  audioplayers_windows:
    dependency: transitive
    description:
      name: audioplayers_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  battery_plus:
    dependency: "direct main"
    description:
      name: battery_plus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.2"
  battery_plus_linux:
    dependency: transitive
    description:
      name: battery_plus_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  battery_plus_macos:
    dependency: transitive
    description:
      name: battery_plus_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  battery_plus_platform_interface:
    dependency: transitive
    description:
      name: battery_plus_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.2"
  battery_plus_web:
    dependency: transitive
    description:
      name: battery_plus_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  battery_plus_windows:
    dependency: transitive
    description:
      name: battery_plus_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  camera:
    dependency: "direct main"
    description:
      name: camera
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.8+1"
  camera_android:
    dependency: transitive
    description:
      name: camera_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.8+3"
  camera_avfoundation:
    dependency: transitive
    description:
      name: camera_avfoundation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.13+3"
  camera_platform_interface:
    dependency: transitive
    description:
      name: camera_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.5.1"
  camera_web:
    dependency: transitive
    description:
      name: camera_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1+6"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  chewie:
    dependency: transitive
    description:
      name: chewie
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.0"
  chewie_audio:
    dependency: transitive
    description:
      name: chewie_audio
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.0"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.5"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.16.0"
  connectivity_plus:
    dependency: "direct main"
    description:
      name: connectivity_plus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.9"
  connectivity_plus_linux:
    dependency: transitive
    description:
      name: connectivity_plus_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  connectivity_plus_macos:
    dependency: transitive
    description:
      name: connectivity_plus_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.6"
  connectivity_plus_platform_interface:
    dependency: transitive
    description:
      name: connectivity_plus_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.4"
  connectivity_plus_web:
    dependency: transitive
    description:
      name: connectivity_plus_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.5"
  connectivity_plus_windows:
    dependency: transitive
    description:
      name: connectivity_plus_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.2"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  cross_file:
    dependency: transitive
    description:
      name: cross_file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.3+4"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.2"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  dbus:
    dependency: transitive
    description:
      name: dbus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.3"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  ffi:
    dependency: transitive
    description:
      name: ffi
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.4"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_html:
    dependency: "direct main"
    description:
      name: flutter_html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  flutter_launcher_icons:
    dependency: "direct dev"
    description:
      name: flutter_launcher_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.0"
  flutter_layout_grid:
    dependency: transitive
    description:
      name: flutter_layout_grid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.6"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  flutter_math_fork:
    dependency: transitive
    description:
      name: flutter_math_fork
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.0"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.15"
  flutter_svg:
    dependency: transitive
    description:
      name: flutter_svg
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.23.0+1"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.3"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.5"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.2"
  image:
    dependency: transitive
    description:
      name: image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.3"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.4"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.8.0"
  lints:
    dependency: transitive
    description:
      name: lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.12"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.5"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  network_info_plus:
    dependency: "direct main"
    description:
      name: network_info_plus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.5"
  network_info_plus_platform_interface:
    dependency: transitive
    description:
      name: network_info_plus_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  nm:
    dependency: transitive
    description:
      name: nm
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.0"
  numerus:
    dependency: transitive
    description:
      name: numerus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  package_info_plus:
    dependency: "direct main"
    description:
      name: package_info_plus
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.2"
  package_info_plus_linux:
    dependency: transitive
    description:
      name: package_info_plus_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  package_info_plus_macos:
    dependency: transitive
    description:
      name: package_info_plus_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  package_info_plus_platform_interface:
    dependency: transitive
    description:
      name: package_info_plus_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  package_info_plus_web:
    dependency: transitive
    description:
      name: package_info_plus_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.6"
  package_info_plus_windows:
    dependency: transitive
    description:
      name: package_info_plus_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.2"
  path_drawing:
    dependency: transitive
    description:
      name: path_drawing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1+1"
  path_parsing:
    dependency: transitive
    description:
      name: path_parsing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1"
  path_provider:
    dependency: transitive
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.15"
  path_provider_android:
    dependency: transitive
    description:
      name: path_provider_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  path_provider_foundation:
    dependency: transitive
    description:
      name: path_provider_foundation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.7"
  permission_handler:
    dependency: "direct main"
    description:
      name: permission_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.3.0"
  permission_handler_platform_interface:
    dependency: transitive
    description:
      name: permission_handler_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.12.0"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.0"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  pointycastle:
    dependency: transitive
    description:
      name: pointycastle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.7.3"
  provider:
    dependency: transitive
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.2"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.1"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  synchronized:
    dependency: transitive
    description:
      name: synchronized
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.12"
  tuple:
    dependency: transitive
    description:
      name: tuple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.2"
  universal_html:
    dependency: "direct main"
    description:
      name: universal_html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.2"
  universal_io:
    dependency: transitive
    description:
      name: universal_io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  upower:
    dependency: transitive
    description:
      name: upower
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.0"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.7"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  vibration:
    dependency: "direct main"
    description:
      name: vibration
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.7"
  video_player:
    dependency: transitive
    description:
      name: video_player
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.7.0"
  video_player_android:
    dependency: transitive
    description:
      name: video_player_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.9"
  video_player_avfoundation:
    dependency: transitive
    description:
      name: video_player_avfoundation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.9"
  video_player_platform_interface:
    dependency: transitive
    description:
      name: video_player_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.2.0"
  video_player_web:
    dependency: transitive
    description:
      name: video_player_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.16"
  wakelock:
    dependency: transitive
    description:
      name: wakelock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.2"
  wakelock_macos:
    dependency: transitive
    description:
      name: wakelock_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0"
  wakelock_platform_interface:
    dependency: transitive
    description:
      name: wakelock_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0"
  wakelock_web:
    dependency: transitive
    description:
      name: wakelock_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0"
  wakelock_windows:
    dependency: transitive
    description:
      name: wakelock_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.0"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.10.4"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.5"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.9.5"
  win32:
    dependency: transitive
    description:
      name: win32
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.6.1"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.4.1"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
sdks:
  dart: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

</details>

### Steps to reproduce

Certainly! Here is an improved version of your error report in English:

---

**Error Report:**

While testing the app with a Remote Debugger on an Android 11 device:

- The camera preview and the `takePicture()` function work as expected.
- I receive the XFile reference, and I can preview the image and send it via a REST request.

However, when creating a release build with `flutter build apk` and manually installing the APK on the same device:

- The camera preview works fine.
- When the `takePicture()` function is called, it throws a `CameraException` with the following details:
  - **Code:** cannotCreateFile
  - **Description:** No such file or directory

### Expected results

getting an XFile reference

### Actual results

Throwing CameraException with 
Code: cannotCreatefile 
Description: No such file or directory

### Code sample

<details open><summary>Code sample from Widget</summary>

```
      onTap: () async {
      if (_image != null) {
        _image = null;
        _controller.resumePreview();
      }
      else {
        late XFile image;
        try{

          if (!await Permission.storage.request().isGranted) {
            throw Exception('Storage permission not granted');
          }


         image = await _controller.takePicture( );

         try {
           _image = image.path;
           _controller.pausePreview();
         }
         on Exception catch(e1) {
           _error="Path error:" + e1.toString();
           print(e1);

         }
        }
      on CameraException catch (e2) {
        _error= 'Error: ${e2.code}\n${e2.description}'; // this exception is thrown
        setState(() {});
      return null;
      }
        on Exception catch(e) {
          _error=e.toString() ;
             print(e);

          }




      }

      setState(() {});
    })),
```

</details>

<details open><summary>Code sample from Camerawrapperclass</summary>

```
import 'dart:convert';
import 'dart:io';
import 'package:camera/camera.dart';
//import 'package:permission_handler/permission_handler.dart';


class CameraApi {


// Get a specific camera from the list of available cameras.
  late CameraDescription firstCamera;

  CameraController? c;
  late Future<void> initializeControllerFuture;
  late bool hasPermission;
  late String permissionError;
  CameraApi() {
    initCamera();
  }

  Future<void> initCamera() async {
    await checkPermissions();
    await createDirectory();
    List<CameraDescription> cameras = await availableCameras();
    firstCamera = cameras.first;

  }

  CameraController InitController() {
    if (c == null) {
      c = CameraController(firstCamera, ResolutionPreset.medium);

      initializeControllerFuture = c!.initialize();
    }
    return c!;
  }

  CameraController getController() {
    InitController();
    return c!;
  }

  void clearcontroler() async {
    if (c != null) {
      if (c!.value.isStreamingImages) {
        await c!.stopImageStream();
      }
      c!.dispose();
      c=null;
    }
  }

  Future<void> createDirectory() async {
    try {
      const directory = '/storage/emulated/0/images';
      final newDir = Directory(directory);
      // Create the directory if it doesn't exist
      if (await newDir.exists()) {
        print('Directory already exists');
      } else {
        await newDir.create(recursive: true);
        print('Directory created successfully');
      }
    } catch (e) {
      print('Error creating directory: $e');
    }
  }

  Future<void> checkPermissions() async {
    hasPermission=true;
    permissionError="";
     bool camerapermission =await Permission.camera.request().isGranted;
     bool datapermission = await Permission.storage.request().isGranted;
     datapermission = await Permission.accessMediaLocation .request().isGranted;
     datapermission = await Permission.mediaLibrary .request().isGranted;
     hasPermission=camerapermission && datapermission;
     if ( !camerapermission) permissionError +="Keine Berechtigung für die Kamera. ";
     if ( !datapermission) permissionError +="Keine Berechtigung auf Medien. ";
  }


}


CameraApi camera=new CameraApi();
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2846], locale de-DE)
    • Flutter version 3.3.10 on channel stable at C:\Workspaceneu\GitRepo\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (1 year, 6 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\and.moeller\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: C:\Program Files\Java\jdk-17\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.79.2)
    • VS Code at C:\Users\and.moeller\AppData\Local\Programs\Microsoft VS Code
[√] Connected device (4 available)
    • BTA700 (mobile)   • adb-13A700G5R220326-vxjwwz._adb-tls-connect._tcp • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows                                          • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)      • chrome                                           • web-javascript • Google Chrome 125.0.6422.141
    • Edge (web)        • edge                                             • web-javascript • Microsoft Edge 125.0.2535.79

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by darshankawar** [comment]
@EntwicklungPS 
I see that you are not on latest stable version. Please upgrade to latest and also use latest plugin version, re-run your scenario and check if the reported behavior still persists or not.

**Comment by EntwicklungPS** [comment]
I have tested the project with the latest version (0.11.0+1). However, the behavior in the release version remains the same, except that now the access permission dialog appears before the exception.

**Comment by darshankawar** [comment]
> I have tested the project with the latest version (0.11.0+1).

By upgrading to latest version, I meant upgrading the stable version you are on too. You seem to be on 3.3.10 which is old, so try upgrading to latest stable and re-run your scenario to check if the exception persists or not.

`flutter upgrade`

**Comment by EntwicklungPS** [comment]
> By upgrading to latest version, I meant upgrading the stable version you are on too. You seem to be on 3.3.10 which is old, so try upgrading to latest stable and re-run your scenario to check if the exception persists or not.
I have Updated my Project to Flutter 3.22.2 and Dart 3.4.3, All direct dependencies all up-to-date.
Still the same Exception.

The device Android version is the Build version RKQ1.210924.001.02.04.02

**Comment by darshankawar** [comment]
I am unable to replicate the error running on S10 in release mode. Can you try on any other device to check if you still get same behavior or not ?
