### ISSUE TITLE
How can I install flutter on Windows 7 in China?

### ISSUE THREAD

**Issue by hphpwj** [flutter/flutter#14968]
I have failed to install flutter with beta version on Windows 7 in China, help!

**Comment by hphpwj** [comment]
I have already set two environment variables, PUB_HOSTED_URL and FLUTTER_STORAGE_BASE_URL.
and 'git clone -b beta https://github.com/flutter/flutter.git' is OK.
but 'flutter doctor' failed.

the log is:
D:\flutter\flutter>flutter doctor
Updating flutter tool...
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 0 seconds, press CTRL+C to quit ...
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 3 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? y

and the environment variables is added:
D:\flutter\flutter>echo %FLUTTER_STORAGE_BASE_URL%
https://storage.flutter-io.cn

D:\flutter\flutter>echo %PUB_HOSTED_URL%
https://pub.flutter-io.cn

**Comment by Haskell2015** [comment]
Just follow the tips in [https://github.com/flutter/flutter/wiki/Using-Flutter-in-China](url).  
But the example code works only in MacOS and Linux ,so in Windows System,U should try it as as bellow:  
![kpb02ual dj942 n 3tggvu](https://user-images.githubusercontent.com/16132141/36830008-a642130a-1d5c-11e8-8d2d-5e6e793a60d5.png)

**Comment by hphpwj** [comment]
@Haskell2015 
when I remove all the files, The recent twice log is:

D:\flutter\flutter>REM The following IF conditions are all linked with a logical
 OR. However,

D:\flutter\flutter>REM there is no OR operator in batch and a GOTO construct is
used as replacement.

D:\flutter\flutter>IF NOT EXIST "D:\flutter\flutter\bin\cache\engine-dart-sdk.st
amp" GOTO do_sdk_update_and_snapshot

D:\flutter\flutter>ECHO Checking Dart SDK version...
Checking Dart SDK version...

D:\flutter\flutter>CALL PowerShell.exe -ExecutionPolicy Bypass -Command "& 'D:\f
lutter\flutter/bin/internal/update_dart_sdk.ps1'"
拒绝访问。

D:\flutter\flutter>IF "1" NEQ "0" (
ECHO Error: Unable to update Dart SDK. Retrying...
 timeout /t 5 /nobreak
 GOTO :do_sdk_update_and_snapshot
)
Error: Unable to update Dart SDK. Retrying...

等待 2 秒，按 CTRL+C 退出 ...

**Comment by hphpwj** [comment]
when I close my antiVirus, access PowerShell is denied.
and now the log is:
PS D:\flutter\flutter> flutter doctor

D:\flutter\flutter>REM Copyright 2017 The Chromium Authors. All rights reserved.

D:\flutter\flutter>REM Use of this source code is governed by a BSD-style license that can be

D:\flutter\flutter>REM found in the LICENSE file.

D:\flutter\flutter>REM ---------------------------------- NOTE ----------------------------------

D:\flutter\flutter>REM

D:\flutter\flutter>REM Please keep the logic in this file consistent with the logic in the

D:\flutter\flutter>REM `flutter` script in the same directory to ensure that Flutter continues to

D:\flutter\flutter>REM work across all platforms!

D:\flutter\flutter>REM

D:\flutter\flutter>REM --------------------------------------------------------------------------

D:\flutter\flutter>SETLOCAL ENABLEDELAYEDEXPANSION

D:\flutter\flutter>FOR %i IN ("D:\flutter\flutter\bin\..") DO SET FLUTTER_ROOT=%~fi

D:\flutter\flutter>SET FLUTTER_ROOT=D:\flutter\flutter

D:\flutter\flutter>SET flutter_tools_dir=D:\flutter\flutter\packages\flutter_tools

D:\flutter\flutter>SET cache_dir=D:\flutter\flutter\bin\cache

D:\flutter\flutter>SET snapshot_path=D:\flutter\flutter\bin\cache\flutter_tools.snapshot

D:\flutter\flutter>SET stamp_path=D:\flutter\flutter\bin\cache\flutter_tools.stamp

D:\flutter\flutter>SET script_path=D:\flutter\flutter\packages\flutter_tools\bin\flutter_tools.dart

D:\flutter\flutter>SET dart_sdk_path=D:\flutter\flutter\bin\cache\dart-sdk

D:\flutter\flutter>SET engine_stamp=D:\flutter\flutter\bin\cache\engine-dart-sdk.stamp

D:\flutter\flutter>SET engine_version_path=D:\flutter\flutter\bin\internal\engine.version

D:\flutter\flutter>SET pub_cache_path=D:\flutter\flutter\.pub-cache

D:\flutter\flutter>SET dart=D:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe

D:\flutter\flutter>SET pub=D:\flutter\flutter\bin\cache\dart-sdk\bin\pub.bat

D:\flutter\flutter>REM If available, add location of bundled mingit to PATH

D:\flutter\flutter>SET mingit_path=D:\flutter\flutter\bin\mingit\cmd

D:\flutter\flutter>IF EXIST "D:\flutter\flutter\bin\mingit\cmd" SET PATH=%SystemRoot%\system32\WindowsPowerShell\v1.0\;C
:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows
;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Administrator\.dnx\bin;C:\Program Files\M
icrosoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL S
erver\120\Tools\Binn\;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Program Files\Java\jdk1.8.0_144\jre\bin;D:\qampp\Data_li
b\perl\bin;D:\qampp\apache\bin;D:\qampp\php;D:\qampp\svnserver\Subversion\bin;D:\qampp\mysql\bin;C:\ProgramData\chocolat
ey\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;D:\Users\Administrator\AppData\Local\Android\sdk\tools;D:\Users
\Administrator\AppData\Local\Android\sdk\platform-tools;C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Sc
ripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python36\;C:\Users\Administrator\AppData\Roaming\npm;C:\Prog
ram Files\Sublime Text 3;D:\Program Files\Microsoft VS Code\bin;D:\flutter\flutter\bin;D:\flutter\flutter\bin\mingit\cmd


D:\flutter\flutter>REM Test if Git is available on the Host

D:\flutter\flutter>where /q git   || ECHO Error: Unable to find git in your PATH.   && EXIT /B 1

D:\flutter\flutter>REM  Test if the flutter directory is a git clone, otherwise git rev-parse HEAD would fail

D:\flutter\flutter>IF NOT EXIST "D:\flutter\flutter\.git" (
ECHO Error: The Flutter directory is not a clone of the GitHub project.
 EXIT /B 1
)

D:\flutter\flutter>REM Ensure that bin/cache exists.

D:\flutter\flutter>IF NOT EXIST "D:\flutter\flutter\bin\cache" MKDIR "D:\flutter\flutter\bin\cache"

D:\flutter\flutter>REM To debug the tool, you can uncomment the following lines to enable checked mode and set an observ
atory port:

D:\flutter\flutter>REM SET FLUTTER_TOOL_ARGS="--checked "

D:\flutter\flutter>REM SET FLUTTER_TOOL_ARGS=" --observe=65432"

D:\flutter\flutter>(
REM "3" is now stderr because of "2>NUL".
 CALL :subroutine doctor   2>&3 9>"D:\flutter\flutter\bin\cache\flutter.bat.lock"  || GOTO acquire_lock
) 2>NUL

D:\flutter\flutter>PUSHD "D:\flutter\flutter"

D:\flutter\flutter>FOR /F %r IN ('git rev-parse HEAD') DO SET revision=%r

D:\flutter\flutter>SET revision=3ea4d06340a97a1e9d7cae97567c64e0569dcaa2

D:\flutter\flutter>POPD

D:\flutter\flutter>REM The following IF conditions are all linked with a logical OR. However,

D:\flutter\flutter>REM there is no OR operator in batch and a GOTO construct is used as replacement.

D:\flutter\flutter>IF NOT EXIST "D:\flutter\flutter\bin\cache\engine-dart-sdk.stamp" GOTO do_sdk_update_and_snapshot

D:\flutter\flutter>SET /P dart_required_version= 0<"D:\flutter\flutter\bin\internal\engine.version"

D:\flutter\flutter>SET /P dart_installed_version= 0<"D:\flutter\flutter\bin\cache\engine-dart-sdk.stamp"

D:\flutter\flutter>IF !dart_required_version! NEQ !dart_installed_version! GOTO do_sdk_update_and_snapshot

D:\flutter\flutter>IF NOT EXIST "D:\flutter\flutter\bin\cache\flutter_tools.snapshot" GOTO do_snapshot

D:\flutter\flutter>IF EXIST "D:\flutter\flutter\version" DEL "D:\flutter\flutter\version"

D:\flutter\flutter>ECHO:  1>"D:\flutter\flutter\bin\cache\.dartignore"

D:\flutter\flutter>ECHO Updating flutter tool...
Updating flutter tool...

D:\flutter\flutter>PUSHD "D:\flutter\flutter\packages\flutter_tools"

D:\flutter\flutter\packages\flutter_tools>REM Makes changes to PUB_ENVIRONMENT only visible to commands within SETLOCAL/
ENDLOCAL

D:\flutter\flutter\packages\flutter_tools>SETLOCAL

D:\flutter\flutter\packages\flutter_tools>IF "" == "true" GOTO on_bot

D:\flutter\flutter\packages\flutter_tools>IF "" == "true" GOTO on_bot

D:\flutter\flutter\packages\flutter_tools>IF "" == "true" GOTO on_bot

D:\flutter\flutter\packages\flutter_tools>IF "" == "1" GOTO on_bot

D:\flutter\flutter\packages\flutter_tools>IF "" == "true" GOTO on_bot

D:\flutter\flutter\packages\flutter_tools>IF "" == "true" GOTO on_bot

D:\flutter\flutter\packages\flutter_tools>GOTO not_on_bot

D:\flutter\flutter\packages\flutter_tools>SET PUB_ENVIRONMENT=:flutter_install

D:\flutter\flutter\packages\flutter_tools>IF "" == "" (IF EXIST "D:\flutter\flutter\.pub-cache" SET PUB_CACHE=D:\flutter
\flutter\.pub-cache )

D:\flutter\flutter\packages\flutter_tools>CALL "D:\flutter\flutter\bin\cache\dart-sdk\bin\pub.bat" upgrade --verbosity=e
rror --no-packages-dir
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 3 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? y

**Comment by goderbauer** [comment]
Looks like something is failing with `pub upgrade`. Can you run the following in your command prompt and let me know what the output is?

```
cd D:\flutter\flutter\packages\flutter_tools
pub upgrade --verbose
```

**Comment by hphpwj** [comment]
@goderbauer 

the output is:
D:\flutter\flutter\packages\flutter_tools>..\..\bin\cache\dart-sdk\bin\pub.bat u
pgrade --verbose
FINE: Pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
IO  : Spawning "cmd /c ver" in D:\flutter\flutter\packages\flutter_tools\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 6.1.7601]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - coverage 0.10.0 from hosted (coverage)
    | - test 0.12.30+3 from hosted (test)
    | - file 2.3.6 from hosted (file)
    | - mustache 1.0.0 from hosted (mustache)
    | - meta 1.1.2 from hosted (meta)
    | - web_socket_channel 1.0.7 from hosted (web_socket_channel)
    | - http 0.11.3+16 from hosted (http)
    | - xml 2.6.0 from hosted (xml)
    | - json_rpc_2 2.0.7 from hosted (json_rpc_2)
    | - stream_channel 1.6.3 from hosted (stream_channel)
    | - process 2.0.7 from hosted (process)
    | - vm_service_client 0.2.4+1 from hosted (vm_service_client)
    | - front_end any from hosted (front_end)
    | - linter 0.1.43 from hosted (linter)
    | - quiver 0.28.0 from hosted (quiver)
    | - args 1.3.0 from hosted (args)
    | - package_config 1.0.3 from hosted (package_config)
    | - crypto 2.0.2+1 from hosted (crypto)
    | - platform 2.1.2 from hosted (platform)
    | - plugin 0.2.0+2 from hosted (plugin)
    | - stack_trace 1.9.1 from hosted (stack_trace)
    | - usage 3.3.0 from hosted (usage)
    | - intl 0.15.2 from hosted (intl)
    | - archive 1.0.33 from hosted (archive)
    | - cli_util 0.1.2+1 from hosted (cli_util)
    | - json_schema 1.0.8 from hosted (json_schema)
    | - yaml 2.1.13 from hosted (yaml)
    | - analyzer any from hosted (analyzer)
IO  : Get versions from https://pub.flutter-io.cn/api/packages/coverage.
IO  : HTTP GET https://pub.flutter-io.cn/api/packages/coverage
    | Accept: application/vnd.pub.v2+json
    | user-agent: Dart pub 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0

D:\flutter\flutter\packages\flutter_tools>

**Comment by Hixie** [comment]
Does it work if you try again but instead of "beta" you say "master"?
If so, then the issue is one we fixed recently and it will be published to the beta branch with the next beta roll in a few weeks.

**Comment by hphpwj** [comment]
@Hixie 
thanks, after use 'git clone -b master https://github.com/flutter/flutter.git', and 'flutter doctor' is OK!
