### ISSUE TITLE
[Impeller] column of material renders slight gap when there should be none

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#149689]
spawned from https://github.com/flutter/flutter/issues/149474

Notice that items 1 and 2 have a slight gap between them, items 2 and 3 do not.  It is my understanding the the correct rendering has no gap between any items.

Seen at 3dd40156afb6f878597d7018ea769b752ca5b115 with iphone se 2022.

## images

![IMG_7010](https://github.com/flutter/flutter/assets/30870216/3e4225f9-ba0c-47c0-bf80-7a67c6c96a3b)

## reproduction

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text("Impeller"),
      ),
      body: Center(
        child: IntrinsicWidth(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Material(
                color: Theme.of(context).colorScheme.onSecondary,
                elevation: 5,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.circular(25),
                  topRight: Radius.circular(25),
                ),
                child: const Padding(
                  padding: EdgeInsets.all(16.0),
                  child: Text("Top"),
                ),
              ),
              Material(
                color: Theme.of(context).colorScheme.onSecondary,
                elevation: 5,
                // borderRadius: BorderRadius.circular(25),
                child: const Padding(
                  padding: EdgeInsets.all(16.0),
                  child: Text("Middle"),
                ),
              ),
              Material(
                color: Theme.of(context).colorScheme.onSecondary,
                elevation: 5,
                borderRadius: const BorderRadius.only(
                  topLeft: Radius.zero,
                  bottomLeft: Radius.circular(25),
                  topRight: Radius.zero,
                  bottomRight: Radius.circular(25),
                ),
                child: const Padding(
                  padding: EdgeInsets.all(16.0),
                  child: Text("Bottom"),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by jonahwilliams** [comment]
Is the gap an intentional gap or is it an AA conflation artifact?

**Comment by jonahwilliams** [comment]
(because unless there is a drawLine in there, this is WAI)

**Comment by AbdeMohlbi** [comment]
Has anyone noticed that the debug banner label text color is slightly different, or is it something intended?

**Comment by gaaclarke** [comment]
> Is the gap an intentional gap or is it an AA conflation artifact?

My understanding by reading through the `Column` documentation is that there should be no gap between the items because of `mainAxisAlignment: MainAxisAlignment.center,`.  The problem is that impeller draws a slight gap between the 2 top items and no gap between the bottom 2.

I would say that skia is wrong to put any gap.  So the problem isn't so much that impeller doesn't match skia so much as it doesn't match itself.

If someone wants a line they can always draw one, if they don't want a line it doesn't seem like they can reliably get that.

**Comment by jonahwilliams** [comment]
Skia is the one that has the AA conflation artifact, not Impeller?

**Comment by gaaclarke** [comment]
> Skia is the one that has the AA conflation artifact, not Impeller?

Yep, it's worse in Skia.  We still have it in impeller.  I've changed the bug description and title to match this.

**Comment by jonahwilliams** [comment]
I see if the the updated the screenshots, not in the old one. If the rect's of item 1 and item 2 exactly line up then its a bug that there is a line there. But if there is a gap, then its a framework layout bug.

**Comment by gaaclarke** [comment]
> Has anyone noticed that the debug banner label text color is slightly different, or is it something intended?

Yep, differences like that don't reach the bar of a bug per se.  If you find a difference in text that is erroneous you should file a bug.  In this case the presence of a line or not I felt violated the intention of the reproduction code.

**Comment by jonahwilliams** [comment]
But this isn't necessarily an impeller bug. If the layout has subpixel gaps then it has subpixel gaps.

**Comment by gaaclarke** [comment]
> But this isn't necessarily an impeller bug. If the layout has subpixel gaps then it has subpixel gaps.

I was able to verify there should be no gaps with the following prints:

```diff
--- a/impeller/aiks/canvas.cc
+++ b/impeller/aiks/canvas.cc
@@ -346,6 +346,8 @@ void Canvas::DrawPath(const Path& path, const Paint& paint) {
   entity.SetBlendMode(paint.blend_mode);
   entity.SetContents(CreatePathContentsWithFilters(paint, path));
 
+  FML_LOG(ERROR) << "DrawPath: " << *entity.GetCoverage();
+
   AddRenderEntityToCurrentPass(std::move(entity));
 }
 
@@ -508,6 +510,8 @@ void Canvas::DrawRect(const Rect& rect, const Paint& paint) {
   entity.SetContents(
       CreateContentsForGeometryWithFilters(paint, Geometry::MakeRect(rect)));
 
+  FML_LOG(ERROR) << "DrawRect: " << *entity.GetCoverage();
+
   AddRenderEntityToCurrentPass(std::move(entity));
 }
 
@@ -540,6 +544,7 @@ void Canvas::DrawOval(const Rect& rect, const Paint& paint) {
 void Canvas::DrawRRect(const Rect& rect,
                        const Size& corner_radii,
                        const Paint& paint) {
+  FML_LOG(ERROR) << rect;
   if (AttemptDrawBlurredRRect(rect, corner_radii, paint)) {
     return;
   }
@@ -552,6 +557,7 @@ void Canvas::DrawRRect(const Rect& rect,
         paint, Geometry::MakeRoundRect(rect, corner_radii)));
 
     AddRenderEntityToCurrentPass(std::move(entity));
+    FML_LOG(ERROR) << "DrawRRect: " << *entity.GetCoverage();
     return;
   }
```

output:
```
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((0, 0), (750, 1334))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((271.505, 575), (206.99, 148))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((293.505, 587), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((293.505, 691), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((271.505, 783), (206.99, 148))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((293.505, 795), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((0, 0), (750, 152))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((636.863, -16.9706), (130.108, 130.108))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((0, 0), (750, 1334))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((271.505, 575), (206.99, 148))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((293.505, 587), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((293.505, 691), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((271.505, 783), (206.99, 148))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((293.505, 795), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((0, 0), (750, 152))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((636.863, -16.9706), (130.108, 130.108))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((0, 0), (750, 1334))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((271.505, 575), (206.99, 148))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((293.505, 587), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((293.505, 691), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((271.505, 783), (206.99, 148))
[ERROR:flutter/impeller/aiks/canvas.cc(349)] DrawPath: ((293.505, 795), (162.99, 104))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((0, 0), (750, 152))
[ERROR:flutter/impeller/aiks/canvas.cc(513)] DrawRect: ((636.863, -16.9706), (130.108, 130.108))
```

Notice that `587+104 = 691` and `691 + 104 = 795`.

**Comment by jonahwilliams** [comment]
Nice!  A resonable next step would be to take a frame capture and inspect the geometry. We should be able to see which pixels are getting covered. 

I wonder if the fully transformed path could end up with a gap somehow?

**Comment by gaaclarke** [comment]
Here are the geometries.  It looks like they meet at `y=307.5`.
## top
<img width="813" alt="Screenshot 2024-06-04 at 3 46 29 PM" src="https://github.com/flutter/flutter/assets/30870216/e9e29678-713d-4afe-ae77-a65194868f8a">

## middle
<img width="818" alt="Screenshot 2024-06-04 at 3 46 40 PM" src="https://github.com/flutter/flutter/assets/30870216/139bb779-a04f-45b2-b7d9-b7ea8dc0128e">

**Comment by gaaclarke** [comment]
I'm working from my home monitor today and I can't really see the line in the screenshot on this monitor.  I zoomed in and checked out the border between the widgets and there doesn't appear to be a line being rendered.  However despite them both being drawn as the same color at the framework level, they are being rendered as different color whites.

![borderquestion](https://github.com/flutter/flutter/assets/30870216/acc5110a-e298-4b5c-99dd-3cec3b5233e9)

If I use the digital color meter on the screenshot I see different results.  There is clearly a line of a different color and both widgets are full white:

![borderyea](https://github.com/flutter/flutter/assets/30870216/d5ae9472-8d1d-4d79-b699-d2cc9fcac78a)

I'm not sure what to make of all of that.  Here is the gpu trace for the record:

[column3materials.gputrace.zip](https://github.com/user-attachments/files/15594886/column3materials.gputrace.zip)

**Comment by jonahwilliams** [comment]
Are the shapes drawn via the convex path or via StC? It could be a discontinuity in the depth or stencil buffer instead, that would be the other attachments in that view.

**Comment by jonahwilliams** [comment]
Oh wait, i got it

**Comment by jonahwilliams** [comment]
This is with a change to the rrect blur to always render solid red. I bet this is an RRect blur artifact?

![flutter_05](https://github.com/flutter/flutter/assets/8975114/d9016ca6-2fbf-4d5d-846d-8cfd8b62228b)

**Comment by gaaclarke** [comment]
Yea, I think you're right.  Here is that draw in the frame debugger:
![overlapblur](https://github.com/flutter/flutter/assets/30870216/1c12f878-1e79-4a82-b6a3-01616649d706)

**Comment by gaaclarke** [comment]
If we ever fix https://github.com/flutter/flutter/issues/149757 it will probably make this show up more pronounced.

**Comment by jonahwilliams** [comment]
What does a skia frame capture look like here? Is this a clipping bug? A positioning bug? Maybe the reect should be over the whole thing?

**Comment by gaaclarke** [comment]
Here's skia's render.  I can't see it on this monitor but there is a line between all the widgets and according to the digital meter it is darker than impellers (probably as a result of https://github.com/flutter/flutter/issues/149757)

![skia_shadow](https://github.com/flutter/flutter/assets/30870216/9bf8e559-4569-4f0d-8a91-d380c7306223)

**Comment by gaaclarke** [comment]
Do you want to mark this as WAI?  We know what is causing it.  I think one could make the argument that all shadow renders should happen below the widgets, **but** that isn't how Skia rendered them.  If we address https://github.com/flutter/flutter/issues/149757 the results will end up looking more like skia.

**Comment by jonahwilliams** [comment]
Is the skia shadow from the rrect blur or from conflation artifacts?

**Comment by gaaclarke** [comment]
> https://github.com/flutter/flutter/issues/149689#issuecomment-2150755793

It looks like it's the same issue with the overdraw in skia.

![skiaborder](https://github.com/flutter/flutter/assets/30870216/e6d83cb2-1416-4168-b713-53cc1600d160)

**Comment by gaaclarke** [comment]
I'm closing this because:
1) The difference between the border for the top 2 items and the bottom 2 items is accounted for in https://github.com/flutter/flutter/issues/149757
1) If someone ever wanted this lines to not appear, the proper way would be to apply a clip.  So this shouldn't ever be a problem for anyone in practice.
