### ISSUE TITLE
Unable to prevent iOS edge swipe gesture when swiping in a ScrollView

### ISSUE THREAD

**Issue by chickenblood** [flutter/flutter#149664]
Thanks for your input @moffatman.
Per your last comment @chickenblood, I think it's safe to close this issue as solved.
Closing from here, if you disagree, please comment and I'll reopen this.
Thank you!

_Originally posted by @dam-ease in https://github.com/flutter/flutter/issues/143715#issuecomment-1955976301_

Unfortunately it turns out that this is still an issue. If you edge-swipe before the scrollview has finished settling from a previous swipe, or even by just doing a fast-swipe from the edge, the issue reproduces.

**Comment by moffatman** [comment]
Can you show in video, thx

**Comment by darshankawar** [comment]
@chickenblood 
Please don't use comment from other issues to file a new issue, as it seems incomplete and we have to look into the related issue for context.

I tried the code sample provided in linked issue and ran it using iphone device with latest stable but I am not sure if I was correctly able to replicate the reported behavior.

https://github.com/flutter/flutter/assets/67046386/a1a675a8-1ff9-442d-bf0a-d6ba32edc045

while sliding from right to left and before scroll completes, I tried to swipe back from left edge which sometimes did navigate to previous screen, if that's the behavior you are reporting.
