### ISSUE TITLE
[flutter_tools] broken pipe during `flutter debug_adapter`

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#149688]
This is one of the top crashers in Flutter's 3.22.* stable releases. For example:

In version `stable/3.22.1`
With command `flutter debug_adapter` on macOS (but it happens also on Linux & Windows)

```
FileSystemException: writeFrom failed, path = '' (OS Error: Broken pipe, errno = 32)
at _checkForErrorResponse(common.dart:55)
at _RandomAccessFile.writeFrom.<anonymous closure>(file_impl.dart:885)
at _rootRunUnary(zone.dart:1407)
at _CustomZone.runUnary(zone.dart:1308)
at <asynchronous gap>(async)
at _FileStreamConsumer.addStream.<anonymous closure>.<anonymous closure>.<anonymous closure>(file_impl.dart:218)
at <asynchronous gap>(async)
```

There is some helpful context in the umbrella issue https://github.com/flutter/flutter/issues/137184, including input from dantup & bkonyi. Likely the process in question is this one, which we actually spawn from the flutter tool: https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/lib/src/debug_adapters/flutter_base_adapter.dart#L130

I think wrapping all writes to that process around https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/process.dart#L247 should fix this.

**Comment by christopherfujino** [comment]
@andrewkolos was this fixed or is this still around but just dwarfed by other issues in crash reporting?

**Comment by andrewkolos** [comment]
> @andrewkolos was this fixed or is this still around but just dwarfed by other issues in crash reporting?

IIRC I landed some changes that may have reduced the presence of this, but it's definitely still around.

**Comment by christopherfujino** [comment]
> > @andrewkolos was this fixed or is this still around but just dwarfed by other issues in crash reporting?
> 
> IIRC I landed some changes that may have reduced the presence of this, but it's definitely still around.

FWIW it looks like this callsite does not trap exceptions: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/flutter_base_adapter.dart#L142

I'm going to remove CoderDrake's assignment, and we can discuss priority in next week's meeting.

**Comment by andrewkolos** [comment]
As far as I can tell, this possible cause of this crash should be fixed. The only write to a process started by `FlutterBaseDebugAdapter.launchAsProcess` is https://github.com/flutter/flutter/blob/3f038aea0bbcee98cd741930436545c013b06b3f/packages/flutter_tools/lib/src/debug_adapters/flutter_adapter.dart#L354

Closing as fixed by https://github.com/flutter/flutter/issues/149688.
