### ISSUE TITLE
[Impeller] LinearGradient no longer fills in all the way

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#149690]
### Steps to reproduce

@jonahwilliams 

Something has just changed, I believe it has to do with a recent PR. https://github.com/flutter/engine/pull/53166 with LinearGradient.  I don't know if the change is intended or not.  If this is on purpose please feel free to close this issue as the fix for me is quite simple

In the past the following code would result in a linear gradient as follows:
![Screen Shot 2024-06-04 at 2 10 23 PM](https://github.com/flutter/flutter/assets/87546778/c8ab82ba-5077-460c-b4d2-8b309871d125)

(ignore the bricks, that's an image in the background)

```
decoration: BoxDecoration(
                                      gradient: LinearGradient(
                                        begin: Alignment.topCenter,
                                        end:const Alignment(0,0.85),
                                        colors: [
                                               Color1.withOpacity(0)
                                               Color1
                                        ],
                                      )),
```

Now as of today, it looks like this:

![Screen Shot 2024-06-04 at 2 09 42 PM](https://github.com/flutter/flutter/assets/87546778/55f24996-243f-449d-bede-21d0409c55a4)

The change if you notice is that the gradient is now transparent after the gradient ends

The fix is easy, I just now add stops and have it end all the way at the bottom of my box:

```
decoration: BoxDecoration(
                                      gradient: LinearGradient(
                                        begin: Alignment.topCenter,
                                        end: Alignment.bottomCenter, ///<-- fix is to have gradient go all the way to the bottom
                                        stops: const [0, 0.85],  ///<---- fix is to add stops to keep the gradient end point where I wanted it
                                        colors: [
                                               Color1.withOpacity(0)
                                               Color1
                                        ],
                                      )),
```

### Expected results

Fidelity with the way LinearGradient was handled before the change, unless the old way was incorrect and this new way is the intended way it should work, in that case please close this issue

### Actual results

As above

### Code sample

As above

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Framework • revision c77c0cf0bc (5 hours ago) • 2024-06-04 11:40:20 -0400
Engine • revision e211c43f3d
Tools • Dart 3.5.0 (build 3.5.0-219.0.dev) • DevTools 2.36.0

```

</details>

**Comment by jonahwilliams** [comment]
This was fixed in https://github.com/flutter/engine/pull/53195

**Comment by mark8044** [comment]
> This was fixed in [flutter/engine#53195](https://github.com/flutter/engine/pull/53195)

Got it, it probably has not made it to the master branch yet, I will keep an eye out and close this once its it looks fixed on my eye 👍 

Thanks much

**Comment by jonahwilliams** [comment]
Should be fixed on latest ToT.

**Comment by mark8044** [comment]
Can confirm, everything looks fixed.  Thanks!

**Comment by jonahwilliams** [comment]
No prob. Thank you for the quick bug report, it helps us do a better job!
