### ISSUE TITLE
[Impeller] Support Variable Rate Shading in the HAL.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#149607]
Similar to MSAA where the fragment shader is run once per fragment and that value broadcast to all the samples covered by that fragment, Variable Rate Shading runs a fragment shader once per tile of fragments (2x2, 4x4, and even rectangular tiles like 2x1) before broadcasting that value to all fragments within that tile (which is then subsequently broadcast to the samples within that fragment if MSAA is enabled).

This technique is useful when we are going to run the fragment shader to create details that are subsequently going to be destroyed. Like when applying blurs.

Variable Rate Rasterization seems to be supported on all iOS devices in Apple A13 (in the iPhone 11) and above. On Android, two similar Vulkan extensions are [`VK_KHR_fragment_shading_rate`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_fragment_shading_rate.html) and [`VK_EXT_fragment_density_map`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_fragment_density_map.html). For Impellers use case, the two Vulkan extensions seem identical and they seem to be supported on ~45% of Vulkan 1.1 capable Android devices. Happily, there is a great overlap between devices that support these extensions and also devices that support higher refresh rates. This is presumably because the higher refresh rate devices are marketed as “gaming” phones with refresh rates as high as 144Hz. So phones that support these extensions also have more demanding workloads.

For Impeller, the use-case is very simple as there is no need to figure out rasterization rates for different parts of the scene. Instead, a uniform rasterization rate can be applied to entire render passes. For this reason, in the HAL, `impeller::RenderTarget::SetRasterizationRate(Rect rate);` seems like an API with the right tradeoffs in terms of usability and ease of implementation.

Setting a rasterization rate of `Rect::MakeWH(0.5f, 0.f5)` would mean rasterizing **at least** at half-rate along each axis.

In the implementation, APIs like Vulkan support either pipeline or rate-map specified rasterization rates. In the former, the pipeline descriptor specifies the rate. In the latter, the rates are specified based on the values encoded in a map. While the former sounds appealing from the perspective of ease of implementation, it increases the pipeline variant load. So implicitly created rate maps seem like the way to go.

This should give us some much needed performance headroom on high refresh-rate and/or high pixel-density devices.

For Impeller's current use-case, this should be sufficient. But it should be possible to augment this API further by specifying a texture as the rate map directly. But I can’t think of a use-case we’d need this much more complicated (to implement) API for.

Recommended watches: https://www.youtube.com/watch?v=_p236TqUuDU and https://developer.nvidia.com/video/GDC-19/ADAPTIVE_SHADING.

**Comment by jonahwilliams** [comment]
@chinmaygarde says to close this!
