### ISSUE TITLE
Unable to build application if a plugin depends on an .AAR

### ISSUE THREAD

**Issue by jonas-zebari** [flutter/flutter#149679]
### Steps to reproduce

First attempt
1. Create a Flutter plugin project
2. Create a Flutter app project
3. In the Android side of the plugin, add a /libs folder and place the .AAR in it
4. Go to `File > Project Structure`
5. On the `Dependencies` tab, find your plugin under `Modules` and select it
6. Under `Declared Dependencies` click the `+` and select `JAR/AAR Dependency`
7. Paste the path to your AAR which should be `libs/name-of-file.AAR`
8. Click `OK` all the way down
9. Now in your Flutter **application**, add the plugin as a local dependency:
```
flutter_plugin_name:
  path: '../flutter_plugin_name'
```
10. Run `flutter pub get` and then `flutter run` (make sure to select an Android target)
This results in the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':chainway_flutter_plugin:bundleDebugAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':chainway_flutter_plugin:bundleDebugAar'
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :chainway_flutter_plugin project caused this error: path/to/aar/in/plugin
```
This error clearly explains that what we're trying to do is not allowed for a specific reason. After learning this I moved on to another attempt where I added the AAR as a dependency of a new Android module and then had the plugin module depend on that module, instead of depending on the AAR directly:

Second Attempt

11. Open `File > Project Structure` once again
12. In the `Dependencies` tab click the `+` under `Modules` this time
13. In the dialog that opens, select `Java or Kotlin Library` and provide the values you want for the name and package (I selected Groovy DSL here for consistency)
14. For whatever reason, after adding a module, my Gradle Sync would always fail. To fix this I navigated to the **plugin** module's `build.gradle` and added `repositories { mavenCentral() }` at the top inside `buildscript {}` (not sure why this is necessary)
15. Inside the new module, I then deleted all of the unneccessary stuff that was created
    1.  The entire `src` dir
    2.  The `.gitignore`
    3.  The **contents** of the `build.gradle` file
16. Then I copied the AAR into the newly created module's dir
17. Once again, navigate to `File > Project Structure` and select the new module within the `Dependencies` tab
18. Under `Declared Dependencies` and with the new module selected, once again click `+` and provide the path to the AAR (which should just be the filename at this point) via `implementation` and click `OK`
19. Still on the `Project Structure` dialog, now select the `plugin_module` and click `+` under Declared Dependencies` but select `Module Dependency` instead
20. Check the newly created module that contains the AAR in the dialog and change `implementation` to `api` in the bottom dropdown menu
21. Click `OK` all the way down and sync Gradle

At this point, when working inside the plugin or the plugin's example project, we have access to the code provided by the AAR and can use it directly within the FlutterPlugin/MethodCallHandler Kotlin class.

However, the issue arises when I try to build/run the Flutter app created in step #2. If the Flutter app includes the plugin in its pubspec.yaml file I cannot build or run the app on Android.

### Expected results

Since the `plugin_with_aar/example/android` application can use and run the module + AAR, my impression is that any Flutter app that can run on Android and includes the plugin as a pubspec.yaml dependency should also be able to build, run, and use the Android plugin code built with the AAR's functionality.

### Actual results

A Flutter app that depends on a plugin which uses an AAR will not build or run on Android.

The error I get is:
```
Build file '.../plugin_with_aar/android/build.gradle' line: 71

A problem occurred evaluating project ':plugin_with_aar'.
> Project with path ':aar-module-name' could not be found in project ':plugin_with_aar'.
```

Based on my research this is an issue that many people building Android + Flutter plugins have faced in the past. Some of the threads about this issue even span from early 2019 to 2023 with no definite solution or official response/guidelines. 

In my opinion, needing to use the functionality an AAR provides within a Flutter plugin is logically and observably common pattern that many Flutter devs have not been able to completely solve.

### Code sample

[Link to minimum code samples (plugin and app projects)](https://github.com/jonas-zebari/aar_issue)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Jonas.Zebari’s iPhone. Ensure the device is unlocked and attached with
      a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@jonas-zebari 
Thanks for the detailed report. Check https://github.com/flutter/flutter/issues/28195 and https://github.com/flutter/flutter/issues/28195#issuecomment-1686952301 to see if it helps in your case or not.

**Comment by darshankawar** [comment]
Thanks for the update. Based on the duplicateRunnable issue you mentioned, it seems you are most probably hitting https://github.com/flutter/flutter/issues/117359 in which you can follow-up for further updates.

Also, check below for further reference:

https://github.com/flutter/flutter/issues/130545
https://github.com/flutter/flutter/issues/125062

Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
