### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by aqsa968** [flutter/flutter#149653]
%23%23 Command%0A%60%60%60%0Aflutter run -d chrome --web-browser-flag --disable-web-security%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0AFileSystemException%3A Cannot open file%2C OS Error%3A No such file or directory%2C errno %3D 2%0A%60%60%60%0A%230      _File.throwIfError %28dart%3Aio%2Ffile_impl.dart%3A629%3A7%29%0A%231      _File.openSync %28dart%3Aio%2Ffile_impl.dart%3A473%3A5%29%0A%232      _File.readAsBytesSync %28dart%3Aio%2Ffile_impl.dart%3A533%3A18%29%0A%233      ForwardingFile.readAsBytesSync %28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file.dart%3A91%3A43%29%0A%234      ForwardingFile.readAsBytesSync %28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file.dart%3A91%3A43%29%0A%235      WebDevFS.update %28package%3Aflutter_tools%2Fsrc%2Fisolated%2Fdevfs_web.dart%3A839%3A57%29%0A%236      ResidentWebRunner._updateDevFS %28package%3Aflutter_tools%2Fsrc%2Fisolated%2Fresident_web_runner.dart%3A487%3A56%29%0A%3Casynchronous suspension%3E%0A%237      ResidentWebRunner.run.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Fisolated%2Fresident_web_runner.dart%3A284%3A41%29%0A%3Casynchronous suspension%3E%0A%238      asyncGuard.%3Canonymous closure%3E %28package%3Aflutter_tools%2Fsrc%2Fbase%2Fasync_guard.dart%3A111%3A24%29%0A%3Casynchronous suspension%3E%0A%60%60%60%0A%60%60%60%0A%1B%5B33m%5B%21%5D%1B%5B39m Flutter %28Channel unknown%2C 3.7.7%2C on macOS 14.5 23F79 darwin-arm64 %28Rosetta%29%2C locale en-AS%29%0A    %1B%5B33m%21%1B%5B39m Flutter version 3.7.7 on channel unknown at %2FUsers%2Faqsafolder%2FDocuments%2Fflutter%0A      Currently on an unknown channel. Run %60flutter channel%60 to switch to an official channel.%0A      If that doesn%27t fix the issue%2C reinstall Flutter by following instructions at https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall.%0A    %1B%5B33m%21%1B%5B39m Unknown upstream repository.%0A      Reinstall Flutter by following instructions at https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall.%0A    %1B%5B32m%E2%80%A2%1B%5B39m Framework revision 2ad6cd72c0 %281 year%2C 3 months ago%29%2C 2023-03-08 09%3A41%3A59 -0800%0A    %1B%5B32m%E2%80%A2%1B%5B39m Engine revision 1837b5be5f%0A    %1B%5B32m%E2%80%A2%1B%5B39m Dart version 2.19.4%0A    %1B%5B32m%E2%80%A2%1B%5B39m DevTools version 2.20.1%0A    %1B%5B32m%E2%80%A2%1B%5B39m If those were intentional%2C you can disregard the above warnings%3B however it is recommended to use %22git%22 directly to perform update checks and upgrades.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Android toolchain - develop for Android devices %28Android SDK version 34.0.0%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Android SDK at %2FUsers%2Faqsafolder%2FLibrary%2FAndroid%2Fsdk%0A    %1B%5B32m%E2%80%A2%1B%5B39m Platform android-34%2C build-tools 34.0.0%0A    %1B%5B32m%E2%80%A2%1B%5B39m Java binary at%3A %2FApplications%2FAndroid Studio.app%2FContents%2Fjre%2FContents%2FHome%2Fbin%2Fjava%0A    %1B%5B32m%E2%80%A2%1B%5B39m Java version OpenJDK Runtime Environment %28build 17.0.7%2B0-17.0.7b1000.6-10550314%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m All Android licenses accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Xcode - develop for iOS and macOS %28Xcode 15.3%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Xcode at %2FApplications%2FXcode.app%2FContents%2FDeveloper%0A    %1B%5B32m%E2%80%A2%1B%

**Comment by huycozy** [comment]
Decoded result (use https://www.url-encode-decode.com/)


## Command
```
flutter run -d chrome --web-browser-flag --disable-web-security
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0 _File.throwIfError (dart:io/file_impl.dart:629:7)
#1 _File.openSync (dart:io/file_impl.dart:473:5)
#2 _File.readAsBytesSync (dart:io/file_impl.dart:533:18)
#3 ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#4 ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#5 WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:839:57)
#6 ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:487:56)
<asynchronous suspension>
#7 ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:284:41)
<asynchronous suspension>
#8 asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel unknown, 3.7.7, on macOS 14.5 23F79 darwin-arm64 (Rosetta), locale en-AS)
 [33m![39m Flutter version 3.7.7 on channel unknown at /Users/aqsafolder/Documents/flutter
 Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
 If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
 [33m![39m Unknown upstream repository.
 Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
 [32m•[39m Framework revision 2ad6cd7 (1 year, 3 months ago), 2023-03-08 09:41:59 -0800
 [32m•[39m Engine revision 1837b5be5f
 [32m•[39m Dart version 2.19.4
 [32m•[39m DevTools version 2.20.1
 [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
 [32m•[39m Android SDK at /Users/aqsafolder/Library/Android/sdk
 [32m•[39m Platform android-34, build-tools 34.0.0
 [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
 [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
 [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.3)
 [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
 [32m•%

**Comment by huycozy** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/91559
