### ISSUE TITLE
VSCode editor showing Could not find a Flutter SDK. Please ensure flutter is installed and in your PATH (you may need to restart).

### ISSUE THREAD

**Issue by ajaybeniwal** [flutter/flutter#14965]
## Steps to Reproduce

I am trying to run flutter from VSCode and I have installed flutter using the installation step and I can see the Flutter SDK in my path but visual studio says Flutter SDK not found

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by devoncarew** [comment]
Hi @ajaybeniwal, thanks for the feedback! Can you re-file your issue over at https://github.com/Dart-Code/Dart-Code/issues? Thanks!

**Comment by DanTup** [comment]
@ajaybeniwal This has come up quite a bit and usually is one of the following:

1. PATH is not updated properly (eg. on Windows sometimes it seems to require a reboot for Code launched from Explorer to get the updated PATH)
2. PATH being set in a way that doesn't get passed to Code (eg. some custom shells seem to handle path differently)

If you're on Windows, I suggest trying a reboot. Otherwise, try launching code from the terminal immediately after confirming flutter is on `PATH`.

You can set the `dart.flutterSdkPath` setting in Code to tell it where your SDK is if you can't fix it another way, but it'd be best to have it detected from path.

If you still have issues, please file a bug at the address Devon gave above and/or grab me in [Dart Code Gitter](https://gitter.im/dart-code/Dart-Code). Thanks!

**Comment by DanTup** [comment]
For anyone still having path issues, please try [v2.10.0 Beta 1 of Dart Code](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.10.0-beta.1) and it should now allow you to easily select the SDK folder from the error message.

**Comment by eddyekofo94** [comment]
@DanTup Helped, thank you

**Comment by DanTup** [comment]
@eddyekofo94 Great! You don't need to use the beta above as that functionality shipped since.

If you have any further problems, feel free to raise issues at https://github.com/Dart-Code/Dart-Code

**Comment by senthilamul** [comment]
Hi Friend  i have small confuse i m web developer i want to like become App Developer.
So i am decided to Learn flutter whether its help for my life????
Please Any one give suggestion.

Thanks

**Comment by baruma** [comment]
@senthilamul iOS, Android for native app development.  Flutter for something more react like.

**Comment by owolabiezekiel** [comment]
@senthilamul you can always switch from web to mobile development anytime with flutter but I would have preferred you have prior experience with mobile programming either with Android or iOS so that your transition to Flutter can be smoother but all the same, you can go ahead in your journey

**Comment by liepaja** [comment]
Delete Cache folder under flutter/bin

**Comment by sculptorNET** [comment]
Simply open [Environment Variables](https://www.youtube.com/watch?v=bEroNNzqlF4v), add new **PATH** where your flutter package is.

For example: C:\dart\flutter\bin

Restart visual studio code, open CMD and type 

> flutter
That will check for all files and download some if missing.
Reboot your PC and try creating new project using Visual Studio Code.

**Comment by diamond95** [comment]
Simply open [Environment Variables](https://www.youtube.com/watch?v=bEroNNzqlF4v), add new **PATH** where your flutter package is.

For example: C:\dart\flutter\bin

Restart visual studio code, open CMD and type 

> flutter

That will check for all files and download some if missing.
Reboot your PC and try creating new project using Visual Studio Code.

**Comment by ThePhoenixRisen** [comment]
> 
> 
> @ajaybeniwal This has come up quite a bit and usually is one of the following:
> 
>     1. PATH is not updated properly (eg. on Windows sometimes it seems to require a reboot for Code launched from Explorer to get the updated PATH)
> 
>     2. PATH being set in a way that doesn't get passed to Code (eg. some custom shells seem to handle path differently)
> 
> 
> If you're on Windows, I suggest trying a reboot. Otherwise, try launching code from the terminal immediately after confirming flutter is on `PATH`.
> 
> You can set the `dart.flutterSdkPath` setting in Code to tell it where your SDK is if you can't fix it another way, but it'd be best to have it detected from path.
> 
> If you still have issues, please file a bug at the address Devon gave above and/or grab me in [Dart Code Gitter](https://gitter.im/dart-code/Dart-Code). Thanks!

Rebooting computer helped remove that message for me
