### ISSUE TITLE
[Impeller] IPOrderedDither8x8 only supported on GLSL ES 3.00 and above.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#149633]
This isn't currently a problem because we don't use it on GLES. As a fix, we should move the LUT computation to the CPU and do a texture lookup in the shader, similar to what graphite does:

https://github.com/google/skia/blob/main/src/gpu/DitherUtils.cpp#L74-L92

https://github.com/google/skia/blob/main/src/sksl/sksl_graphite_frag.sksl#L443-L453

**Comment by jonahwilliams** [comment]
Unfortunately its not just the mod operator:

ERROR: 0:19: '^' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '&' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '<<' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '&' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '<<' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '|' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '&' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '<<' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '|' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '&' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '<<' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '|' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '&' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '>>' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '|' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '&' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '>>' : bit-wise operator supported in GLSL ES 3.00 and above only
ERROR: 0:20: '|' : bit-wise operator supported in GLSL ES 3.00 and above only

**Comment by chinmaygarde** [comment]
I don't think we should do anything to support `IPOrderedDither8x8` on OpenGL ES. Instead, we can do a non-shader based dither via `glEnable(GL_DITHER)` just before the gradient draw and then disable it after.

**Comment by jonahwilliams** [comment]
I think we should just skip dithering on this backend instead.
