### ISSUE TITLE
[CP] relax conditions for SkRRect.isSimple conversion

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#149704]
### Issue Link

flutter/flutter#148412

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/53208

### Changelog Description

* Fixes potential flickering when translating a blurred rounded rectangle.

### Impacted Users

Impeller / iOS

### Impact Description

Incorrect rendering / flickering in certain applications.

### Workaround

Use Skia

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached tests.

**Comment by zanderso** [comment]
cp lgtm

**Comment by itsjustkevin** [comment]
https://github.com/flutter/engine/pull/53208 merged.
