### ISSUE TITLE
`flutter upgrade` should take a hidden --version argument

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14970]
Our [release process](https://github.com/flutter/flutter/wiki/Release-process) says that when pushing a beta build, you should ensure that the build "can be successfully upgraded to from an earlier dev build (via 'flutter upgrade')".

The problem with this is that if you're upgrading from (e.g.) `v0.0.20` to `v0.1.4`, but the most recent dev build is `v0.1.6`, then there's no way to tell whether an upgrade will work, because just running `flutter upgrade` will upgrade to `v0.1.6` (not to `v0.1.4`, as you'd like).

If we had a `--version` argument, it would allow us to test this better.  The trick is that we have no way of knowing whether the version they specify was ever a release on their channel.  And what if they just specify a git hash?  Do either of those matter?

We _could_ even allow an older version to be specified, effectively allowing them to downgrade in case of a regression... This could supersede #14801

**Comment by tvolkert** [comment]
@jonahwilliams is this still relevant?

**Comment by jonahwilliams** [comment]
I accomplished testing of upgrade/downgrade differently, using a hidden command to apply the upgrade to a different flutter checkout. This gives us pretty OK coverage for an integration test

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/upgrade.dart#L39

Closing as resolved.
