### ISSUE TITLE
[CP]  Fix stroke curves. 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#149701]
### Issue Link

https://github.com/flutter/flutter/issues/147139

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/53206

### Changelog Description

* Fixes a rendering bug present in certain stroked paths.

### Impacted Users

Impeller / iOS

### Impact Description

Certain paths will render incorrectly

### Workaround

Disable impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached tests.

**Comment by zanderso** [comment]
cp lgtm

**Comment by itsjustkevin** [comment]
https://github.com/flutter/engine/pull/53206
