### ISSUE TITLE
> > i have same problem too for http library. I already added permission to the manifest file but it's not working in release

### ISSUE THREAD

**Issue by mrtenkorang** [flutter/flutter#149733]
> > i have same problem too for http library. I already added permission to the manifest file but it's not working in release
> 
> > i have same problem too for http library. I already added permission to the manifest file but it's not working in release apk.
> 
> Are you using http or https links??

The Problem was in my release AndroidManifest.xml file but i solved, thanks.

_Originally posted by @gurkanucar in https://github.com/flutter/flutter/issues/31019#issuecomment-888126315_
            

Please what did you do to solve it?

**Comment by darshankawar** [comment]
@mrtenkorang 
Please don't use issue comments from other issues to file a new issue. Please use new issue template and fill out requested details if you think you have encountered a bug. Else you can raise this in support channels like StackOverflow.
Closing.
