### ISSUE TITLE
Touch input has unpredictable tap detection

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#1497]
Details and repro case will come later. But I wanted to report this now. (I'm on the latest Flutter engine 87, but this also happened on sky engine 75 as well.)

I noticed that taps are occasionally ignored in my app.

My situation is:
- Large container has a tap target on the full container
- A button is inside the container (another tap/press target)
- The button is not always present.

In my app, 4 people take turns playing cards. After each card is played, they tap the large container to reveal their cards. After all 4 cards are revealed, the "Take" button appears to tell the trick winner to take the trick.

Everything works fine up to there.

After the trick-taking tap, the next card played has issues being revealed:
- The first tap (on the container) is ignored.
- The next tap succeeds.

This makes me think that Flutter has a bug where:
- If a tap target is removed, the remaining tap targets will not be able to detect taps normally.

It may also be that:
- The first "missed" tap fixes the problem.
- The bug generalizes to all gestures.

For now, my app is fine since I can fake the "Take" button with a similarly-styled container, but it would be nice to fix this behavior. (For my app, the large container's onTap handler does the same thing as the button's onPressed would have.)

As mentioned, I'll try to make a simpler test case later.

**Comment by abarth** [comment]
Are you running Flutter inside of MojoShell?

**Comment by abarth** [comment]
Also, what host platform are you using?

**Comment by afandria** [comment]
Yes, Flutter inside of Mojo Shell. The app was running on a Nexus 9.

**Comment by afandria** [comment]
This also happens on Nexus 6 and with normal Flutter (`flutter start`).

Here's an easier reproduction case. I have a blue background that is tappable. When you tap the body, the tap counter increments and prints out `Body Tap`. (Run `adb logcat` output to see these printouts.)

When an even number of taps have occurred, a button with the text `Yes Tap` will show up. Tapping this prints out `Button Tap` and increments the tap counter. When an odd number show up, then `No Tap` text will show up instead. (This simulates adding and removing of tap targets.)

Behavior:
* Tapping the body repeatedly works just fine, even though the button is added and removed
* Tapping the button makes it disappear and the next tap is completely ignored.

In `lib/main.dart`
```
import 'package:flutter/material.dart';

class TempComponent extends StatefulComponent {
  TempComponentState createState() => new TempComponentState();
}

class TempComponentState extends State<TempComponent> {
  int numTapped = 0;

  Widget _buildBody() {
    List<Widget> children = new List<Widget>();
    if (numTapped % 2 == 0) {
      children = [
        new FlatButton(
          child: new Text("Yes Tap"),
          color: Colors.green[500],
          onPressed: () {
            print("Button Tap");
            setState(() { numTapped++; });
          })
      ];
    } else {
      children = [
        new Text("No Tap")
      ];
    }

    return new GestureDetector(
      onTap: () {
        print("Body Tap");
        setState(() { numTapped++; });
      },
      child: new Container(
        decoration: new BoxDecoration(backgroundColor: Colors.blue[500]),
        child: new Column(children: children))
    );
  }

  Widget build(BuildContext context) {
    return new Scaffold(
      key: new GlobalObjectKey("scaffold"),
      toolBar: new ToolBar(
          center: new Text('Croupier')),
      body: new Material(child: _buildBody()));
  }
}

void main() {
  runApp(new MaterialApp(
    title: 'My app',
    routes: <String, RouteBuilder>{
      '/': (RouteArguments args) => new TempComponent()
    }
  ));
}
```

Perhaps the real behavior is:
* If a tap target was tapped, and the handler makes that target disappear, then the next tap will be ignored.

**Comment by mpcomplete** [comment]
@HansMuller , this is ancient, but is it related to your work to fix Missing Taps?

**Comment by abarth** [comment]
Mojo shell isn't a thing anymore.
