### ISSUE TITLE
Flutter Navigation Drawer takes Full screen  with a specific title

### ISSUE THREAD

**Issue by KirubaKaran2001** [flutter/flutter#149794]
### Steps to reproduce

Open A Drawer with more than two expansion tile it take the whole screen black with the title of nav bar,it happens after upgrrading flutter v3.22.1

### Expected results

Navigation bar  should function Properly 

### Actual results

It make the whole screen balck 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![image](https://github.com/flutter/flutter/assets/113582050/e6cf8147-f3b7-478d-b420-b9735d0eea2b)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on Ubuntu 24.04 LTS 6.8.0-31-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by mr-durjoy** [comment]
give me code will be fixed it

**Comment by KirubaKaran2001** [comment]
Actualy i found issue but i cannot able to fix it . I ma using Expansion
Tile in Navigation bar when it touches the end of the screen it show screen
which i posted the image

**Comment by mr-durjoy** [comment]
If you give me a sample I will try to fix it

**Comment by arhamsc** [comment]
Please share the code sample or a gist, its probably you allowing the drawer to use entire width, it can be easily restricted easily by wrapping it in a `SizedBox()` and providing a width, and relative width if you are using `flutter_screenutils` package.

**Comment by huycozy** [comment]
@KirubaKaran2001 For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thanks!

**Comment by mr-durjoy** [comment]
@huycozy  close the issue man
