### ISSUE TITLE
Allow passing null `onValueChanged` to `CupertinoSegmentedControl`, treating it to mean that the value is read-only

### ISSUE THREAD

**Issue by triallax** [flutter/flutter#149755]
### Use case

I would like to have a segmented control widget that can be read-only (i.e. whose value cannot be modified by the user). This can currently be done by passing a lambda that does nothing to `onValueChanged`, but even then the segmented control choices have the `button` semantic annotation set to true, which is not ideal.

### Proposal

Allow passing a value of `null` for `onValueChanged` to the `CupertinoSegmentedControl` constructor, in which case the control would be read-only. And perhaps also add some color parameters that are used when the control is in the read-only state?

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/52105. Closing this issue as a duplicate, so please follow up on it for further updates.

**Comment by triallax** [comment]
Oops, apologies for the duplicate.
