### ISSUE TITLE
Accessibility Docs

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14973]
I think our only docs on accessibility are here:
https://flutter.io/widgets/accessibility/

We presumably will want a doc sometime in the medium term about making ones Flutter app awesomely accessible.

FYI @goderbauer

**Comment by zoechi** [comment]
There is https://flutter.io/docs/development/accessibility-and-localization/accessibility

**Comment by zoechi** [comment]
Some additional information about how to implement Semantics in custom components would be interesting.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2081](https://github.com/flutter/website/issues/2081) via [**ZenHub**](https://www.zenhub.com/)
