### ISSUE TITLE
[CP] Fix segfault when tessellating empty convex polygons

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#149745]
### Issue Link

flutter/flutter#149309

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/53212

### Changelog Description

* Fix Impeller segfault when tessellating empty convex polygons

### Impacted Users

Impeller on iOS

### Impact Description

Native crash, segfault

### Workaround

Use Skia

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached unit tests.

**Comment by zanderso** [comment]
cp lgtm

**Comment by itsjustkevin** [comment]
https://github.com/flutter/engine/pull/53212
