### ISSUE TITLE
[CP] Fixes Intel Simulator rendering bug

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#149700]
### Issue Link

https://github.com/flutter/flutter/issues/148660

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/53205

### Changelog Description

* Fix rendering bug on Intel MacOS iOS simulators.

### Impacted Users

Developers targeting iOS simulators on older intel macs

### Impact Description

* Fixes rendering corruption when running on Intel mac simulators.

### Workaround

Disable impeller.

### Risk

low

### Test Coverage

no

### Validation Steps

Manually verified by running on Intel mac.

**Comment by zanderso** [comment]
cp lgtm

**Comment by itsjustkevin** [comment]
https://github.com/flutter/engine/pull/53205 merged.

**Comment by aikins01** [comment]
🥳🥳🥳
