### ISSUE TITLE
How to zoom the page for flutter web

### ISSUE THREAD

**Issue by GaoXing0608** [flutter/flutter#149788]
### Steps to reproduce

The flutter web could not zoom by ctrl + mouse scroll

### Actual results

coult zoom the page view by ctrl + mouse scroll

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by mr-durjoy** [comment]
try this bro

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ZoomPage(),
    );
  }
}

class ZoomPage extends StatefulWidget {
  @override
  _ZoomPageState createState() => _ZoomPageState();
}

class _ZoomPageState extends State<ZoomPage> {
  double _zoomLevel = 1.0;

  void _zoomIn() => setState(() => _zoomLevel += 0.1);
  void _zoomOut() => setState(() => _zoomLevel -= 0.1);
  void _resetZoom() => setState(() => _zoomLevel = 1.0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Flutter Web Zoom')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Transform.scale(
              scale: _zoomLevel,
              child: Container(
                width: 300,
                height: 300,
                color: Colors.blue,
                child: Center(
                  child: Text(
                    'Zoom: ${_zoomLevel.toStringAsFixed(1)}',
                    style: TextStyle(color: Colors.white, fontSize: 20),
                  ),
                ),
              ),
            ),
            SizedBox(height: 20),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                ElevatedButton(onPressed: _zoomIn, child: Text('Zoom In')),
                SizedBox(width: 10),
                ElevatedButton(onPressed: _zoomOut, child: Text('Zoom Out')),
                SizedBox(width: 10),
                ElevatedButton(onPressed: _resetZoom, child: Text('Reset')),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by huycozy** [comment]
@GaoXing0608 This is a known issue being tracked at https://github.com/flutter/flutter/issues/129933. Closing this issue as a duplicate, so please follow up on it for further updates.
