### ISSUE TITLE
Does flutter engine have plans to stop supporting opengl+skia and only use impeller+vulkan? 

### ISSUE THREAD

**Issue by imaginegit** [flutter/flutter#149783]
### Use case

Does flutter engine have plans to stop supporting opengl+skia and only use impeller+vulkan?

### Proposal

 Currently, our tests think that the performance of impeller+vulkan is not good enough. If there is a plan, we would like to know the official time to assess the impact

**Comment by jonahwilliams** [comment]
Yes, we will eventually stop supporting Skia on mobile platforms. The timeframe is likely more than a year, but it will happen. Part of that consideration is specific, actionable feedback (aka bugs) regarding performance and fidelity.

So if you have cases where Impeller is performing poorly, we'd love to get bug reports or example apps that we can work on.

**Comment by jonahwilliams** [comment]
Though we will have an Impeller OpenGL backend, as some % of Android devices we support are not Vulkan capable.
