### ISSUE TITLE
[path_provider] (mac) getApplicationDocumentsDirectory tests hanging/failing.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#149713]
The following packages:

*  path_provider/path_provider
*  path_provider/path_provider_foundation

Seem to be failing the `getApplicationDocumentsDirectory` integration test in MacOS with either a timeout or the following exception:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following PathAccessException was thrown running a test:
Directory listing failed, path = '/Users/chrome-bot/Documents/' (OS Error: Operation not permitted,
errno = 1)

When the exception was thrown, this was the stack:
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:228:5)
#2      _verifySampleFile (file:///Volumes/Work/s/w/ir/x/w/packages/packages/path_provider/path_provider_foundation/example/integration_test/path_provider_test.dart:81:20)
#3      main.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/packages/packages/path_provider/path_provider_foundation/example/integration_test/path_provider_test.dart:23:5)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  getApplicationDocumentsDirectory
════════════════════════════════════════════════════════════════════════════════════════════════════

00:16 +1 -1: getApplicationDocumentsDirectory [E]                                                                                                                                                      
  Test failed. See exception logs above.
  The test description was: getApplicationDocumentsDirectory
  

To run this test again: /Volumes/Work/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test /Volumes/Work/s/w/ir/x/w/packages/packages/path_provider/path_provider_foundation/example/integration_test/path_provider_test.dart -p vm --plain-name 'getApplicationDocumentsDirectory'
```

This has prevented the [roll to b50eb9](https://github.com/flutter/packages/pull/6867) roll to land. See:

* [Timeout build](https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20macos_platform_tests%20master%20-%20packages/13642/overview), [another one](https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20macos_platform_tests%20master%20-%20packages/13646/overview)
* [Exception build](https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20macos_platform_tests%20master%20-%20packages/13645/overview)

**Comment by ditman** [comment]
Maybe related? https://github.com/flutter/flutter/pull/149618 /cc @vashworth?

**Comment by stuartmorgan** [comment]
I believe disabling the sandbox changes the behavior of getting the documents directory from getting an app-specific directory to getting ~/Documents, and the latter is probably popping up a dialog to allow access.

We can do [this](https://github.com/flutter/packages/blob/84fd510de8147dc8ffd10af14802e01ea759cae0/packages/path_provider/path_provider_foundation/example/integration_test/path_provider_test.dart#L47-L49) on macOS in both packages.

**Comment by vashworth** [comment]
I confirmed @stuartmorgan's hypothesis, disabling sandboxing does change the directory.

With sandboxing enabled, the path is `/Users/username/Library/Containers/dev.flutter.plugins.pathProviderExample/Data/Documents`. With sandboxing disabled, the path is `/Users/username/Documents`, which requires additional permissions to access.

I'll go ahead and fix based on stuart's recommendation

**Comment by ditman** [comment]
Thanks for fixing this so quickly! The roller is rollin' normally again!
