### ISSUE TITLE
Web: Incorrect opening and closing of the keyboard in the web application

### ISSUE THREAD

**Issue by internetova** [flutter/flutter#149732]
### Steps to reproduce

To launch an application with the ability to test its operation on real mobile devices on the web, you need to follow the following steps:

1. Make sure that your device and your computer are on the same local network
2. Get the local IP address of your computer:
```sh
ipconfig getifaddr en0
```
3. Run the command:
```sh
flutter round web-server --web-port 8080 --web-hostname <your.ip.address.from.the past.step>
```
4. The application is now available from the browser of your mobile device at the address `<your.ip.address.from.the past.step>:8080`
5. Tap in the text field and then remove the focus. Repeat several times.

### Expected results

Opening and closing the keyboard works correctly

### Actual results

When opened, additional space may appear between the keyboard and the text field.

When hiding the keyboard, some of the content may temporarily overlap.

When hiding the keyboard, the background of the splash screen may flash.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: ListView(
        physics: const ClampingScrollPhysics(),
        padding: const EdgeInsets.symmetric(horizontal: 24),
        children: const <Widget>[
          SizedBox(height: 20),
          FlutterLogo(size: 240),
          SizedBox(height: 40),
          TextField(
            decoration: InputDecoration(
              hintText: 'Tap here',
            ),
          ),
          SizedBox(height: 20),
          Text(
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
          SizedBox(height: 20),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="246" alt="keyboard_android_web_app_bug" src="https://github.com/flutter/flutter/assets/39735343/6d79d29f-37ee-4a0b-b8c2-26290d4e6b11">

https://github.com/flutter/flutter/assets/39735343/8b1d0e74-069a-4faf-84e3-7eb29553908b

https://github.com/flutter/flutter/assets/39735343/7c0d9449-b26e-4052-805b-bf1190d3db66

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed bug report @internetova.
There's already a similar issue open describing your case, https://github.com/flutter/flutter/issues/124205. Please follow-up in it for further updates. Closing this as a duplicate.
