### ISSUE TITLE
Doctor for project setup

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14974]
`flutter doctor` currently checks the user's environment setup, but it doesn't perform checks on their project (i.e. the directory created by `flutter create`).

It'd be good if we gave users a way to check "is my project in a healthy state?".  Things this might check:

- [ ] Are the Gradle files up to date?
- [ ] Are the Xcode project files up to date?
- [ ] Are there any errors in my pubspec.yaml?
    - For example, the user should be depending on `flutter_test: sdk: flutter`, not `test` directly (or at least not without depending on `flutter_test`)

**Comment by zoechi** [comment]
Similar to #12983

**Comment by xster** [comment]
I'm gonna merge it into #12983
