### ISSUE TITLE
"Static" versioning in flutter web

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#149725]
### Use case

This underlying problem for my suggestion is in theese links:
https://github.com/flutter/flutter/issues/104509
https://github.com/fluttercommunity/plus_plugins/issues/2675

When working with scenarios in Flutter web where we need to address the current version which is cached in the users browser, we do not have any easy way to get that version. The tool package_info_plus may give is a version, but that one is bound to the `/version.json` on the web site's server, not the actual version of the cached code on the users browser.

### Proposal

It would have been VERY convenient to have access to the `pubspec.yaml`  version string during build, so you could address that version as "staticVersion" or " cachedVersion" during run-time. This would make version-checking very easy, and you could address proper ways to refresh your page, either automatically or suggested actions for the user, when the page version on server changes.

My suggestion is to have a global variable i.e. like `String cachedVersion` and `Int cachedBuild` int the form "x.y.z+build" and *build*, which is populated during build time from the values which are presended in the version parameter in `pubspec.yaml`.

Theese values should be incorporated in the code, so it shouldn't be taken from `\version.json` in the same way as `package_info_plus` does, which now follows the version presented on the server, not currently cached in the browser.

**Comment by adriank** [comment]
```dart
Stream<bool> isAppUpdateAvailable() async* {
final currentAppVersion = Version.parse((await PackageInfo.fromPlatform()).version);
  yield false;
  while (true) {
    await Future.delayed(const Duration(minutes: 5));
    final versionJson = (await get(
      Uri.parse('https://example.com/version.json?cachebuster=${DateTime.now().millisecondsSinceEpoch}'),
    ))
        .body;
    final newestVersion = Version.parse((jsonDecode(versionJson) as Map)['version']);
    if (newestVersion > currentAppVersion) {
      yield true;
    }
  }
}
```

**Comment by RoarGronmo** [comment]
> ```dart
> Stream<bool> isAppUpdateAvailable() async* {
> final currentAppVersion = Version.parse((await PackageInfo.fromPlatform()).version);
> yield false;
> while (true) {
>   await Future.delayed(const Duration(minutes: 5));
>   final versionJson = (await get(
>     Uri.parse('https://example.com/version.json?cachebuster=${DateTime.now().millisecondsSinceEpoch}'),
>   ))
>       .body;
>   final newestVersion = Version.parse((jsonDecode(versionJson) as Map)['version']);
>   if (newestVersion > currentAppVersion) {
>     yield true;
>   }
> }
> }
> ```

Are you sure that `currentAppVersion` is the one which are for the cached part in the browser, since `package_info_plus` uses the `/version.json` file from the web site ? How can we can be sure that that also are cached along with rest of the web page ?

**Comment by adriank** [comment]
Just trust me. It works in production for half a year right now.

**Comment by darshankawar** [comment]
@RoarGronmo Can you check if [this](https://github.com/flutter/flutter/issues/55967) is something related / useful with your use case and proposal ?

**Comment by RoarGronmo** [comment]
> @RoarGronmo Can you check if [this](https://github.com/flutter/flutter/issues/55967) is something related / useful with your use case and proposal ?

A little off my topic, but anyway, the main problem is to catch that the server has been updated with contents which differs from that what is currently cached in the users web-browser (`pubspec.yaml` version has changed).  Mostly to comply with a such situation is to hit "Ctrl+F5" and the browser contents are reloaded. In a Flutter perspective (and may be in a WASM perspective) this could be crucial to keep what is expected to happen in the browser vs what is published at the server-side (different versions).

From my perspective, the most neat way to do this will be to incorporate the version in the code, so it is easy to compare the version which is sited (un-cached) on the web site ('\version.json') and the version which are currently cached in the browser.

If the worker in the future is loading parts of the web-page "pagewise" it needs to keep one part in the browser persistent (containing the cached version level), until all the "pages" are refreshed from the server. You need a "lowest" version number, to trigger a "need to update" scenario then.

You "could" link that to the Scaffold in Flutter, but not all uses a Scaffold to build an app around, and that Scaffold could (in theory) be a page in an paginated scenario, and there keep the cached version information.

I don't know the underlying structures of how Flutter would paginate this scenario.

**Comment by yjbanov** [comment]
Sounds like this should be a constant that can be read using some core `dart:*` library, which can then be used to either embed in your own Dart code, or in a tool that outputs `version.json` or whatever makes sense for the app.

**Comment by biggs0125** [comment]
This seems like a feature request for the Dart language as a whole. A library like this would likely be included on all platforms, not just the web. I'd recommend filing a feature request in the [Dart SDK repo](https://github.com/dart-lang/sdk/issues/new/choose) for the core library folks to take a look at.
