### ISSUE TITLE
Determine why #53072 broke post-submit (after passing pre-submit)

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#149742]
Original PR: https://github.com/flutter/engine/pull/53072.

See revert: https://github.com/flutter/engine/pull/53220.

/cc @cbracken @jason-simmons

**Comment by hellohuanlin** [comment]
Likely a race condition with the ARC migration work. 
```
FlutterPlatformViews_Internal.mm:277:10: error: ARC forbids explicit message send of 'dealloc'
  277 |   [super dealloc];
      |    ~~~~~ ^
```

I doubt if it's even possible to avoid this kind of race condition, because presubmit runs on a un-rebased branch. Between presubmit and postsubmit runs, there can always be a commit that gets merged to main.
