### ISSUE TITLE
[CP] Round out subpass coverage.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#149702]
### Issue Link

flutter/flutter#146967

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/53207

### Changelog Description

* Corrects coverage computation that result in distored pixels in Impeller targets

### Impacted Users

Impeller iOS

### Impact Description

Visual artifacts.

### Workaround

Disable impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached unit tests

**Comment by bbjay** [comment]
This would also bring a fix for https://github.com/flutter/flutter/issues/148588 which is tagged as regression.

**Comment by zanderso** [comment]
cp lgtm

**Comment by itsjustkevin** [comment]
https://github.com/flutter/engine/pull/53207 merged
