### ISSUE TITLE
Flutter Inspector : Add way to stop automatic opening

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#14984]
In Android Studio 3.0.1 when you start an app in the emulator for the first time, or when you uninstall the app and run it again - the flutter inspector pops open in the editor. 
This can get irritating after a while if you need to uninstall a few times or you are trying on different emulators for example since it will pop open every time.

Its good to let people know the inspector is there, but it shouldn't be like a pushy salesman :)

An option to disable this popping-up action would be good.

**Comment by devoncarew** [comment]
There is an option :) In the Preferences dialog, in Languages & Frameworks > Flutter.

**Comment by mikewillems** [comment]
For those finding this in 2020, the setting has now changed from within Flutter to within Dart: 
`dart.openDevTools`
Just modify the dart JSON or search for "Open Dev Tools" in user settings.
