### ISSUE TITLE
[web] Find an ergonomic solution for CORS images for CanvasKit and Skwasm

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#149843]
As of today (and we should read it as "for the foreseeable future"), CORS images cannot be rendered into WebGL/WebGPU canvases. However, there are plenty of use-cases where apps need to be able to display CORS images in their apps.

Our current solution is as follows:

- [Educate](https://docs.flutter.dev/platform-integration/web/web-images) everyone about CORS.
- Ask developers to use platform views when CORS image support is needed (there is also at least [one package](https://pub.dev/packages/show_network_image) that removes the toil of platform views).

Based on the feedback given in https://github.com/flutter/flutter/issues/145954, this solution continues to be unergonomic for users, to a point that they are willing to use the less feature-rich HTML renderer instead of CanvasKit or Skwasm.

This feature request is to improve the ergonomics of using CORS images in Flutter web apps. Ideally we can make `Image.network` work out of the box. However, a separate widget, or a well-supported package, would also be acceptable.

**Comment by Swiftaxe** [comment]
I suggest making Image.network load the image in the background in the HTML context (the WebGL canvas is running in an HTML context).

By using document.createElement in javascript to create an <img> element and setting the crossOrigin attribute on it, we can load the image into memory behind the scene. Then we load the image onto the canvas from memory without tainting the canvas.

The user experience would be to use Image.network as with other images, and it just works. Enabling CORS on the server will always be required of course.

My knowledge of Flutter Web is limited as of now, but I could present a more concrete solution if I could discuss this with some people well-versed in the Flutter web code and architecture.

Any thoughts on this @yjbanov?


_See the following references on CORS images and canvas:_
[Allowing cross-origin use of images and canvas (MDN)](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)
[Using Cross-domain images in WebGL and Chrome 13 (Chromium Blog)](https://blog.chromium.org/2011/07/using-cross-domain-images-in-webgl-and.html)

**Comment by Swiftaxe** [comment]
> Using Cross-domain images in WebGL and Chrome 13 (Chromium Blog)

After doing some research, I think this could be done in the NetworkImage._loadAsync method in _network_image_web.dart.

**Comment by harryterkelsen** [comment]
@Swiftaxe if the server hosting the image supports CORS, then we are already able to access the bytes of the image and create a texture for the image and upload it to WebGL. The problem arises when the server _doesn't_ support CORS. In that case, we cannot access the bytes or put the image in a canvas without tainting it. In that case, we must display the image using an `<img>` tag in a platform view. I am working on just this solution now.
