### ISSUE TITLE
[WEB] [flutter_service_worker] Fails to register if called from multiple subdomain

### ISSUE THREAD

**Issue by RajeevRetire100** [flutter/flutter#149878]
### Steps to reproduce

So my flutter mobile web can be accessed with two URLs.

https://my.thetruefin.com/nps (flutter service worker fails to register)

https://m.thetruefin.com/nps (Registers properly)

I am using flutter 3.22.1 with Bootstrap Web initialization

**USECASE**
Client will only use my.thetruefin.com and based on useragent we internally send it to m.thetruefin.com (flutter) and w.thetruefin.com(react)

### Expected results

service worker should be able to register

### Actual results

<img width="1614" alt="Screenshot 2024-06-07 at 1 04 08 PM" src="https://github.com/flutter/flutter/assets/154118003/84674dd8-8ed4-45fb-a6fb-99a27445d2ba">
<img width="1417" alt="Screenshot 2024-06-07 at 12 55 04 PM" src="https://github.com/flutter/flutter/assets/154118003/877014d7-7b5d-4fc6-8754-cbaec82e09a2">

### Code sample

<details open><summary>Code sample</summary>

```html
<!DOCTYPE html>
<html>

<head>
  <!--
      If you are serving your web app in a path other than the root, change the
      href value below to reflect the base path you are serving from.

      The path provided below has to start and end with a slash "/" in order for
      it to work correctly.

      For more details:
      * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

      This is a placeholder for base href that will be replaced by the value of
      the `--base-href` argument provided to `flutter build`.
    -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="TrueFin: Empowering India's Retirement Readiness with NPS, Mutual Funds, and more.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="retire100">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/svg+xml" href="favicon.svg">

  <title>TrueFin</title>
  <link rel="manifest" href="manifest.json">

  <style>
    .loading {
      display: flex;
      justify-content: center;
      align-items: center;
      margin: 0;
      position: absolute;
      top: 50%;
      left: 50%;
      -ms-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);
    }

    .loader {
      border: 16px solid #f3f3f3;
      border-radius: 50%;
      border: 8px solid;
      border-top: 8px solid #7375FD;
      border-right: 8px solid white;
      border-bottom: 8px solid #7375FD;
      border-left: 8px solid white;
      width: 60px;
      height: 60px;
      -webkit-animation: spin 2s linear infinite;
      animation: spin 2s linear infinite;
    }

    @-webkit-keyframes spin {
      0% {
        -webkit-transform: rotate(0deg);
      }

      100% {
        -webkit-transform: rotate(360deg);
      }
    }

    @keyframes spin {
      0% {
        transform: rotate(0deg);
      }

      100% {
        transform: rotate(360deg);
      }
    }
  </style>
</head>

<body>

<script src="flutter_bootstrap.js" async></script>

  <div class="loading">
    <div class="loader"></div>
  </div>


<!-- razorpay checkout lib -->
   <script src="https://checkout.razorpay.com/v1/checkout.js"></script>


</body>

</html>
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (2 weeks ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3
rajeevjaiswal@LT-46847 ~ % 
rajeevjaiswal@LT-46847 ~ % flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for HeatoN. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources


```

</details>

**Comment by huycozy** [comment]
Hi @RajeevRetire100 
Does this happen locally or only in production? Can you check if this issue is reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

**Comment by RajeevRetire100** [comment]
> Hi @RajeevRetire100 Does this happen locally or only in production? Can you check if this issue is reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

How can I check with 2 subdomains locally? Currently, it happens in hosted website

**Comment by huycozy** [comment]
You can try [this way](https://stackoverflow.com/a/38912011/5921933) to set up sub-domains in localhost. Please try on a skeleton Flutter project to see if you can reproduce the issue or not.
