### ISSUE TITLE
Firestore plugin collection() vs getCollection()

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#14982]
Most Firestore libs use the same method names for getting collections and documents as you traverse down the tree:

```dart
Firestore.instance.collection('versions').doc('v1').collection('users').doc()...
```

Current API is:
```dart
Firestore.instance.collection('versions').doc('v1').getCollection('users').doc()...
```

I propose renaming getCollection() to collection() in DocumentReference.

**Comment by kroikie** [comment]
@pauldemarco

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/900. Any further collaboration will be done there.
