### ISSUE TITLE
Upgrade 50% of macOS bots to macOS 14

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#149853]
### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

Upgrade the following devices to macOS 14.5

Staging pool

- [x] [flutter-devicelab-mac-37](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-37) (moto g arm64)
- [x] [flutter-devicelab-mac-4](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-4) (ios arm64)
- [x] [flutter-devicelab-mac-5](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-5) (ios arm64)
- [x] [flutter-devicelab-mac-11](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-11) (ios arm64)
- [x] [flutter-devicelab-mac-39](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-39) (ios arm64)
- [x] [flutter-devicelab-mac-10](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-10) (ios x86)
- [x] [flutter-devicelab-mac-23](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-23) (ios x86)
- [x] [flutter-devicelab-mac-26](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-26) (ios x86)

Prod pool

- [x] [flutter-devicelab-mac-40](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-40) (ios arm64)
- [x] [flutter-devicelab-mac-41](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-41) (ios arm64)
- [x] [flutter-devicelab-mac-2](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-2) (ios x86)
- [x] [flutter-devicelab-mac-3](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-3) (ios x86)
- [x] [flutter-devicelab-mac-6](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-6) (ios x86)
- [x] [flutter-devicelab-mac-7](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-7) (ios x86)
- [x] [flutter-devicelab-mac-8](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-8) (ios x86)
- [x] [flutter-devicelab-mac-9](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-9) (ios x86)
- [x] [flutter-devicelab-mac-35](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-35) (moto g arm64)
- [x] [flutter-devicelab-mac-20](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-20) (moto g x86)
- [x] [flutter-devicelab-mac-18](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-18) (pixel 7 x86)

Try pool

- [x] [flutter-devicelab-mac-46](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-46) (ios arm64)
- [x] [flutter-devicelab-mac-14](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-14) (ios x86)

### Additional Instructions

Please quarantine bot before upgrading.

Also, please ensure the following after each upgrade:

Delete any directories within `/opt/flutter/xcode` if applicable.

Also verify `/opt/flutter/xcode` is owned by swarming user.

Run `DevToolsSecurity` - should get response "Developer mode is already enabled."
If you don't get the message, run `sudo /usr/sbin/DevToolsSecurity -enable` to enable.

**Comment by kentnguyen99** [comment]
Will start upgrading macOS 14.5 first thing tomorrow morning on Staging pool per Victoria.

**Comment by vashworth** [comment]
Verified all bots are working. Thanks @kentnguyen99!
