### ISSUE TITLE
[google_maps_flutter] Update iOS GoogleMaps dependency to support 9.0

### ISSUE THREAD

**Issue by Samo8** [flutter/flutter#149873]
### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

Hello everybody,

as there was [version 9.0 of GoogleMaps for iOS released](https://developers.google.com/maps/documentation/ios-sdk/release-notes), please update the dependency for google_maps_flutter_ios, as the newest version contains Privacy manifest.

After that there should probably be some cleaning of Privacy manifest in google_maps_flutter_ios package.

Thank you.

### Steps to reproduce

1. go to google_maps_flutter_ios.podspec in google_maps_flutter_ios package
2. update GoogleMaps version constraint to include version 9.0

### Expected results

GoogleMaps iOS dependency is 9.0
Cleanup Privacy manifest in google_maps_flutter_ios

### Actual results

GoogleMaps iOS dependency is below 9.0
Privacy manifest in google_maps_flutter_ios has privacy reasons isnetad of GoogleMaps iOS SDK.

### Code sample

```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'google_maps_flutter_ios'
  s.version          = '0.0.1'
  s.summary          = 'Google Maps for Flutter'
  s.description      = <<-DESC
A Flutter plugin that provides a Google Maps widget.
Downloaded by pub (not CocoaPods).
                       DESC
  s.homepage         = 'https://github.com/flutter/packages'
  s.license          = { :type => 'BSD', :file => '../LICENSE' }
  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :http => 'https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/ios' }
  s.documentation_url = 'https://pub.dev/packages/google_maps_flutter_ios'
  s.source_files = 'Classes/**/*.{h,m}'
  s.public_header_files = 'Classes/**/*.h'
  s.module_map = 'Classes/google_maps_flutter_ios.modulemap'
  s.dependency 'Flutter'
  # Allow any version up to the next breaking change after the latest version that
  # has been confirmed to be compatible via an example in examples/. See discussion
  # in https://github.com/flutter/flutter/issues/86820 for why this should be as
  # broad as possible.
  # Versions earlier than 8.4 can't be supported because that's the first version
  # that supports privacy manifests.
  s.dependency 'GoogleMaps', '>= 8.4', '< 9.0'
  s.static_framework = true
  s.platform = :ios, '14.0'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  s.resource_bundles = {'google_maps_flutter_ios_privacy' => ['Resources/PrivacyInfo.xcprivacy']}
end
```

### Flutter Doctor output

There is no need of Flutter doctor output

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/146838 tracks cleaning up the privacy manifest when we drop support for 8.4, but since that would remove iOS 14 support we don't currently plan to do that. Adjusting title to have this track expanding the range to include 9.0.
