### ISSUE TITLE
[web][breaking] Change `--web-renderer` default from `auto` to `canvaskit`

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#149826]
## Summary
The `--web-renderer` CLI argument's default value is changing from `auto` to `canvaskit`.

## Background
The `CanvasKit` renderer has come a long way since the early days of Flutter Web. Many bugs have been fixed, and the size has been reasonably decreased. We now consider the `CanvasKit` renderer mature enough to be the default renderer for Flutter Web. 

## Migration guide
We recommend using the `canvaskit` renderer, and that's why we are making it the default. But if you have a need for the `auto` renderer, then you need to explicitly pass it as a CLI argument (please give us feedback on why you need `auto` or `html` renderers [here](https://github.com/flutter/flutter/issues/145954)).

Command before migration:
```
flutter run -d chrome
```
Command after migration:
```
flutter run -d chrome --web-renderer=auto
```

**Comment by RoarGronmo** [comment]
From which version will it apply ?

**Comment by RoarGronmo** [comment]
Will you update the documentation [here](https://docs.flutter.dev/platform-integration/web/renderers) also ?

**Comment by mdebbar** [comment]
> From which version will it apply ?

The change hasn't landed yet, so I can't tell for sure.

> Will you update the documentation [here](https://docs.flutter.dev/platform-integration/web/renderers) also ?

Yes, that documentation is changing here: https://github.com/flutter/website/pull/10722

**Comment by kevmoo** [comment]
Announcement email: https://groups.google.com/g/flutter-announce/c/78pys2K3VGE
