### ISSUE TITLE
iOS PlatformView using UIGraphicsImageRenderer and TextureLayer

### ISSUE THREAD

**Issue by ajihyf** [flutter/flutter#149814]
### Use case

Use iOS PlatformView without the layering and threading complexities.

### Proposal

The Android platform view offers an effective approach known as [Texture-Layer-Hybrid-Composition](https://github.com/flutter/flutter/blob/master/docs/platforms/android/Texture-Layer-Hybrid-Composition.md). Similarly, iOS provides a comparable functionality with [UIGraphicsImageRenderer](https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer?language=objc), which can render a UIView into a UIImage, subsequently transformable into a metal texture. I wonder if it's possible to employ the same concept used in Android to implement the iOS platform view?

**Comment by darshankawar** [comment]
@ajihyf Check if [this](https://github.com/flutter/flutter/issues/143389) resembles your case or not.

**Comment by ajihyf** [comment]
@darshankawar It looks like the issue is related to rendering FlutterView to UIImage. I'm wondering if it's possible to render platform views to UIImage and composite them within the Flutter pipeline.

Thanks in advance for any insights!

**Comment by hellohuanlin** [comment]
I doubt this is viable on iOS. For example, most ads sdks monitors that the banner view is presented unobstructed on screen as it is, to be registered as a valid impression for fraud detection purpose. Rendering it to UIImage would hide the actual banner. 

Feel free to come up with a proposal though.

**Comment by loic-sharma** [comment]
See this Discord conversation: https://discord.com/channels/608014603317936148/846507953959862273/1250008362310045787

> cbracken — 06/14/2024 9:29 AM
> With the UIGraphicsImageRenderer approach, among other things I’d be concerned about things like whether that would work with DRM’ed video for example. My guess would be no, but it’s just a guess.

> matt_kn — 06/14/2024 9:32 AM
> UIGraphicsImageRenderer might be useful for snapshot of UIViews, but unlikely good solution would interactive views.
> And I'd bet my dinner DRM video would just leave a black background.

**Comment by ajihyf** [comment]
> See this Discord conversation: https://discord.com/channels/608014603317936148/846507953959862273/1250008362310045787
> 
> > cbracken — 06/14/2024 9:29 AM
> > With the UIGraphicsImageRenderer approach, among other things I’d be concerned about things like whether that would work with DRM’ed video for example. My guess would be no, but it’s just a guess.
> 
> > matt_kn — 06/14/2024 9:32 AM
> > UIGraphicsImageRenderer might be useful for snapshot of UIViews, but unlikely good solution would interactive views.
> > And I'd bet my dinner DRM video would just leave a black background.

Thank you for your response. I will try to look into the implementation and provide feedback if possible.

**Comment by hellohuanlin** [comment]
Discussed with @jonahwilliams about this today (correct me if any mistakes) - Android was able to do this by somehow relaying touch interactions from the texture to the actual platform view. 

On iOS, however, it is not possible (except via private API) to mimic user touch interaction on a view. So this isn't a viable solution.

**Comment by XuanTung95** [comment]
Hi @hellohuanlin,
For those plugins like vlc_player, camera.. which need no touch event, can they achieve better performance than HC mode using this?

**Comment by jonahwilliams** [comment]
For those cases you would use the flutter texture registry and not a platform view

**Comment by hellohuanlin** [comment]
> Hi @hellohuanlin, For those plugins like vlc_player, camera.. which need no touch event, can they achieve better performance than HC mode using this?

FYI there is a discussion on using platform views for video player: https://github.com/flutter/flutter/issues/86613.
