### ISSUE TITLE
Pull to Refresh is too slow and too long travel 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#14981]
I was trying the Flutter Gallery App and comparing its Pull to Refresh with other apps (like Gmail), I can clearly see that Flutter's Pull to Refresh needs to be pulled for a much longer distance and once activated the spinning animation is slower than the native one.

I suggest you make it like the original, since long dragging distances and slow animations reflect on poor user experience.

**Comment by feinstein** [comment]
Those things are hard to compare, but I also believe the thickness of the spinning circle is thinner.

**Comment by feinstein** [comment]
One more thing (this might be a bug on the Gallery App and not the widget itself), the widget locks if it's spinning and you change to another app, like Chrome and then you go back to the gallery app.

**Comment by TahaTesser** [comment]
Hi @feinstein 
Is this issue still valid?
Thank you

**Comment by feinstein** [comment]
@TahaTesser Looking at the Facebook App as a reference for the Native behavior and the Flutter Gallery App for the Flutter behavior, then yes, it's still valid.

**Comment by xster** [comment]
I'm assuming you meant material design on Android based on your description?

**Comment by feinstein** [comment]
Yes, that's correct. Just compare it with the Gmail App on Android and you will see they don't match.

**Comment by lazylazyllama** [comment]
This should now be fixed on master branch as #69783 landed a few hours ago. :)

**Comment by feinstein** [comment]
Thanks.

At first I thought someone at Google would just take a look at the original Java source code of the native pull to refresh and copy the parameters, didn't think it would take almost 3 years to fix tbh. Not complaining, just a bit surprised.

**Comment by YeungKC** [comment]
This issue has been fixed, I will close this issue and if there are any objections raised, I will restore it.
