### ISSUE TITLE
Twitter share character limit issue, Unable to post tweet.

### ISSUE THREAD

**Issue by ucpritam** [flutter/flutter#149808]
### Steps to reproduce

1. Use appinio_social_share: ^0.3.1
2. Pass some text to appinioSocialShare.iOS.shareToTwitter().
3. Post icon is disabled and twitter character limit is showing in negative.

### Expected results

I should be able to post tweet as my character limit is under 280 characters.

### Actual results

I am not able to post tweet.

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<void> shareToTwitter({
  required String message,
  String imageUrl = '',
}) async {
  AppinioSocialShare appinioSocialShare = AppinioSocialShare();

  if (imageUrl.isNotEmpty) {
    var rng = Random();
    Directory tempDir = await getTemporaryDirectory();
    String tempPath = tempDir.path;
    File file = File('$tempPath${rng.nextInt(100)}.png');

    http.Response response = await http.get(Uri.parse(imageUrl));
    await file.writeAsBytes(response.bodyBytes);

    await appinioSocialShare.iOS.shareToTwitter(
      message,
      file.path,
    );
  } else {
    await appinioSocialShare.iOS.shareToTwitter(message, '');
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2024-05-23 at 15 11 02](https://github.com/flutter/flutter/assets/54333597/890b357c-0d52-4bb4-a090-4eb7d10a90a3)
![Screenshot 2024-05-23 at 15 23 17](https://github.com/flutter/flutter/assets/54333597/c6518a05-104a-4c97-8627-49e4938e8140)

</details>

### Logs

<details open><summary>Logs</summary>

```console
N/A
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.89.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
`appinio_social_share` is a 3rd package, you should file an issue to its developers for better support. Closing as this is not a Flutter framework bug.
