### ISSUE TITLE
[New Feature]Click on the widget to jump to the corresponding line of code in the IDE

### ISSUE THREAD

**Issue by rs5173** [flutter/flutter#149950]
### Use case

I'm often bothered by this problem, if there are too many widgets in a page, when I intend to modify one of them, I need to go to their location in the code first, so I was wondering if I can implement this amazing feature, when I click on the corresponding widgets directly in the app, the IDE will automatically find the corresponding code for me and jump to the corresponding line, similar to the like the preview function in Jetapck Compose.

### Proposal

null

**Comment by syedaniq** [comment]
You can achieve that by using the "select widget mode" in the widget inspector
See https://docs.flutter.dev/tools/devtools/inspector#use-the-layout-explorer

**Comment by darshankawar** [comment]
@rs5173 Check if above helps to resolve your use case.
