### ISSUE TITLE
Error starting debug session in Xcode: Timed out waiting for CONFIGURATION_BUILD_DIR to update

### ISSUE THREAD

**Issue by BenjiFarquhar** [flutter/flutter#149955]
Repost of two duplicate issues that were unresolved:

#144218 
#138473

The gist is that the debug session never starts when the app was run from Vs Code/Android Studio, as it is waiting for CONFIGURATION_BUILD_DIR to update indefinitely. I believe this is an XCode 15 with ios 17 physical devices issue, that only happens when started from Android Studio/Vs code in debug mode, that only happens on some projects. 

I have a 100,000 line build log: [flutter_build_log.txt](https://github.com/user-attachments/files/15844735/flutter_build_log.txt)

- In debug mode, it runs fine on simulators but not on my physical iOS 17 device (when started from VS Code/AS). 
- In debug mode, it runs fine on physical iOS 16 devices according to #144218 (when started from VS Code/AS). I don't have one though. 
- In debug mode, it runs fine on my iOS 17 physical device when started from Xcode. 
- In release mode, it runs fine on my physical iOS 17 (when started from VS Code/AS). 

There is a log for:

`[+1999 ms] stderr: Current CONFIGURATION_BUILD_DIR: build/Debug-iphoneos while expecting /Users/benjaminfarquhar/dev/vepo_front_end/build/ios/iphoneos`

But I think it's a red herring as I hardcoded it in a user defined variable in xcode and the message went away but the overall error log posted in the below log with `Timed out waiting for CONFIGURATION_BUILD_DIR to update.` remained the same.

### Expected results

App runs

### Actual results

`Error starting debug session in Xcode: Timed out waiting for CONFIGURATION_BUILD_DIR to update.`

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main_development.dart on Benji’s iPhone 13 mini in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 5256E329AM
Xcode build done.                                           20.8s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Xcode is taking longer than expected to start debugging the app. Ensure the project is opened in Xcode.
Error starting debug session in Xcode: Timed out waiting for CONFIGURATION_BUILD_DIR to update.
Could not run build/ios/iphoneos/Runner.app on 00008110-001119123C7B801E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Benji’s iPhone 13 mini.

Exited (1).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.22.2 on channel stable at /Users/benjaminfarquhar/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/benjaminfarquhar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/benjaminfarquhar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)
    • Benji’s iPhone 13 mini (mobile) • 00008110-001119123C7B801E            • ios            • iOS 17.5.1 21F90
    • iPhone 15 (mobile)              • A0430331-7604-491A-85BC-8BAD2C0F78A9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@BenjiFarquhar 
Can you provide the verbose log by running `flutter run -v` and provide it a text file ?

**Comment by BenjiFarquhar** [comment]
@darshankawar Thanks for taking a look. Here it is. 

[flutter_build_log.txt](https://github.com/user-attachments/files/15844733/flutter_build_log.txt)

**Comment by darshankawar** [comment]
Thanks for the log. I will reopen https://github.com/flutter/flutter/issues/144218 so that  we can track it better in one issue.
I am closing this as duplicate and will add the verbose build log in linked issue for team's reference.
