### ISSUE TITLE
Analysis options bugged after upgrading from 3.22.0-0.2.pre to 3.23.0-0.1.pre

### ISSUE THREAD

**Issue by cabaucom376** [flutter/flutter#149981]
### Steps to reproduce

For the last 6 moths I have been using [this guide](https://rydmike.com/blog_flutter_linting.html) to essentially include [all linter rules](https://dart.dev/tools/linter-rules/all) and then override the conflicts and tune the rules to my taste. I have made this simple little setup into a package that I host on a private GitHub repo and just update the all_linter_rules.yaml file whenever new rules are added, as well as make sure all conflicts are resolved. With the 3.23 beta I am encountering a new error even though my overall methods have remained consistent.

I am now getting warnings about conflicting linter rules in my `all_linter_rules.yaml` file even though conflicts are properly overridden and the `included_file_warning: ignore` analyzer error is properly set. The weird part is that when I reference my custom analysis packages' `analysis_options.yaml` locally the errors are not present. Only when referencing the `analysis_options.yaml` using a package import, from git hosted or local path, do these warnings appear.

1. [nv_analysis package files](https://gist.github.com/cabaucom376/1aef168d8cc4bd54517d38e73b7e9da1)

2. Project files

pubspec.yaml:
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  nv_analysis:
    git:
      url: git@github.com:Novoid-LLC/nv_flutter_analysis.git
      ref: master
```
analysis_options.yaml:
```yaml
include: package:nv_analysis/analysis_options.yaml # local barrel import of file removes warnings
analyzer:
  plugins:
    - custom_lint
```

3. Warnings:
```
Warning in the included options file /Users/$User/.pub-cache/git/nv_flutter_analysis-b80a6a1f77bd738d967c1ff52af94e50788bb94f/lib/all_lint_rules.yaml(1497..1529): The rule 'avoid_types_on_closure_parameters' is incompatible with the rule 'always_specify_types'.dart(included_file_warning)
Warning in the included options file /Users/$User/.pub-cache/git/nv_flutter_analysis-b80a6a1f77bd738d967c1ff52af94e50788bb94f/lib/all_lint_rules.yaml(3522..3546): The rule 'omit_local_variable_types' is incompatible with the rule 'always_specify_types'.dart(included_file_warning)
Warning in the included options file /Users/$User/.pub-cache/git/nv_flutter_analysis-b80a6a1f77bd738d967c1ff52af94e50788bb94f/lib/all_lint_rules.yaml(4302..4324): The rule 'prefer_final_parameters' is incompatible with the rule 'avoid_final_parameters'.dart(included_file_warning)
Warning in the included options file /Users/$User/.pub-cache/git/nv_flutter_analysis-b80a6a1f77bd738d967c1ff52af94e50788bb94f/lib/all_lint_rules.yaml(4906..4928): The rule 'prefer_relative_imports' is incompatible with the rule 'always_use_package_imports'.dart(included_file_warning)
Warning in the included options file /Users/$User/.pub-cache/git/nv_flutter_analysis-b80a6a1f77bd738d967c1ff52af94e50788bb94f/lib/all_lint_rules.yaml(4936..4955): The rule 'prefer_single_quotes' is incompatible with the rule 'prefer_double_quotes'.dart(included_file_warning)
Warning in the included options file /Users/$User/.pub-cache/git/nv_flutter_analysis-b80a6a1f77bd738d967c1ff52af94e50788bb94f/lib/all_lint_rules.yaml(5799..5815): The rule 'unnecessary_final' is incompatible with the rule 'prefer_final_locals'.dart(included_file_warning)
```

### Expected results

The expected results is that I should be able to `include: package:nv_analysis/analysis_options.yaml` and not receive conflicts from the `all_lint_rules.yaml` file since they have been resolved using overrides and even supposedly silenced using `included_file_warning: ignore`.

### Actual results

My best guess of what is actually happening is for some reason the `included_file_warning: ignore` is not being applied to subsequent inclusions in yaml files. This is resulting in linter rules showing up as conflicts. Interestingly this is only reproducible when importing as a package.

### Code sample

Attempt to import this [analysis package](https://gist.github.com/cabaucom376/1aef168d8cc4bd54517d38e73b7e9da1) in your projects analysis_options.yaml:
```yaml
include: package:nv_analysis/analysis_options.yaml
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by shpiaadev** [comment]
why does the latest flutter have so many bugs? what's wrong with team flutter/dart?

**Comment by darshankawar** [comment]
@cabaucom376 Most probably you'll need to report this in dedicated repo: https://github.com/dart-lang/linter/issues.
Closing from here. If you think this is incorrect, write in comments and I'll reopen it.
