### ISSUE TITLE
code 'childParentData.layoutOffset != childParentData._paintExtent' is always true

### ISSUE THREAD

**Issue by leegean** [flutter/flutter#149907]
1.find file two_dimensional_viewport.dart.
2.go to the method updateChildPaintData of RenderTwoDimensionalViewport.
3.find code snippet bellow.it's about line 1473.
`childParentData.layoutOffset != childParentData._paintExtent`

**Comment by darshankawar** [comment]
@leegean 
Please provide complete runnable reproducible code sample, complete error log in formatted text along with flutter doctor -v

**Comment by leegean** [comment]
They are all different types with different '==' operator,one is Offset and other is Size.

**Comment by darshankawar** [comment]
> Please provide complete runnable reproducible code sample

**Comment by leegean** [comment]
```
import 'package:flutter/cupertino.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('description', () {
    var t = TwoDimensionalViewportParentData();
    t.layoutOffset = const Offset(1, 1);
    Size? _paintExtent = const Size(1, 1);
    assert(t.layoutOffset != _paintExtent);
  });
}
```

**Comment by darshankawar** [comment]
Running above code with latest stable shows me below:

```
I/flutter ( 7739): 00:00 +0: description
I/flutter ( 7739): 00:00 +1: All tests passed!
Application finished.
```
