### ISSUE TITLE
Document how to receive page load eventsd

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#14996]
In short looking for iOS equivalents for the below events 

override func loadView() 
override func viewWillAppear(animated: Bool) 
override func viewWillDisappear(animated: Bool)

**Comment by najeira** [comment]
Yes, you can observe those events. See https://docs.flutter.io/flutter/widgets/RouteObserver-class.html

**Comment by cbracken** [comment]
@manujbahl where could we have put this information to make it easier to find? (Where did you look but not find the docs @najeira points to?)

**Comment by manujbahl** [comment]
somewhere here ..
https://flutter.io/routing-and-navigation/ or even a section in https://docs.flutter.io/flutter/widgets/Navigator-class.html

I was also not thorough enough to quite look at all the class methods. Was hoping to find at least some info on the class description itself. Doesn't show up on google searches as well.

**Comment by cbracken** [comment]
Thanks! Very useful!

**Comment by manujbahl** [comment]
Is there anything ay the widget level as well?
Something similar to the viewWillAppear in iOS where the only the Page coming into focus gets the notification.

**Comment by najeira** [comment]
[State.initState](https://docs.flutter.io/flutter/widgets/State/initState.html) is that.

**Comment by getSwiftly** [comment]
I am also searching for the methods that act like "func viewWillAppear(animated: Bool) and func viewWillDisappear(animated: Bool)" but for some reason State.initState is not it as it doesn't run again once the widget has been created. I am using a CupertinoTabBar so that doesn't recreate the already created view. Help needed.

**Comment by najeira** [comment]
Use https://docs.flutter.io/flutter/widgets/RouteObserver-class.html and https://docs.flutter.io/flutter/widgets/RouteAware-class.html .

**Comment by getSwiftly** [comment]
didPush() is not called when changing Tab page from 2 to 1 again. Therefore state is not refreshed. Anything else that can help?

**Comment by najeira** [comment]
I missed the explanation that you use BottomNavigation.

You can set CupertinoTabBar.onTap to handle tap events. In other words, you can handle according to the selected tab.

**Comment by lukepighetti** [comment]
The only examples I've found require you to pass a routeObserver from your main.dart file all the way through to your pages. I am calling my navigation at the widget level so I can pass parameters to my pages. These two methods are conflicting when you want to push parameters to pages and be able to listen for page events. Is there a method I should be using instead?

**Comment by getSwiftly** [comment]
I figured out that using the bottom tab bar you can make a global state object that you want to refresh from other tabs. That works and for the Navigator push and pop the didPush() or didPopNext() methods with RouteAware works perfectly. Thanks all.

**Comment by getSwiftly** [comment]
the solution by @najeira worked for me. Thanks and here is the method that you can use for onTap on BottomNavBar:
`tabBar: new CupertinoTabBar(
        onTap: (i){
          if(i == 0)
          {
            homePageState.loadData();
          }
        },
        items: <BottomNavigationBarItem> [
          new BottomNavigationBarItem(backgroundColor: Colors.white, icon: new Image.asset('images/overview.png', height: tabBarIconSize, width: tabBarIconSize), title: Text("OVERVIEW")),
          new BottomNavigationBarItem(backgroundColor: Colors.white, icon: new Image.asset('images/settings.png', height: tabBarIconSize, width: tabBarIconSize), title: Text("SETTINGS")),
        ],
      ),`

**Comment by Daibaku0615** [comment]
@getSwiftly Can you share more code how you did that?

**Comment by getSwiftly** [comment]
> the solution by @najeira worked for me. Thanks and here is the method that you can use for onTap on BottomNavBar:
> 
> ```dart
> tabBar: new CupertinoTabBar(
>         onTap: (i){
>           if(i == 0)
>           {
>             homePageState.loadData();
>           }
>         },
>         items: <BottomNavigationBarItem> [
>           new BottomNavigationBarItem(backgroundColor: Colors.white, icon: new Image.asset('images/overview.png', height: tabBarIconSize, width: tabBarIconSize), title: Text("OVERVIEW")),
>           new BottomNavigationBarItem(backgroundColor: Colors.white, icon: new Image.asset('images/settings.png', height: tabBarIconSize, width: tabBarIconSize), title: Text("SETTINGS")),
>         ],
>       ),
> ```

I used this code in my CupertinoTabBar class and file. With this you can call a function on any state handler that you have globally accessible. To create a global state handler, use the following code snippet.

In your constants file which has to be included in the file where you want to use the homePageState:

`//GLOBAL STATES
MyHomePageState homePageState = new MyHomePageState();`

Then, in the file where your HomePage class and its state class are present, initialize the homePageState using the following line in the HomePageClass:
`class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, BuildContext ctxt}) : super(key: key);

  @override
  MyHomePageState createState() => homePageState;
}`

In your state class, make the function you want to run via the CupertinoTabBar selected method as in the quoted code. The method I created to run every time page 1 is selected is _homePageState.loadData()_.

**Comment by chunhtai** [comment]
It seems like the original issue is no longer related to route and i am not sure what documentation we can provide, closing this issue
