### ISSUE TITLE
Static analysis error on hot reload of package:flutter 

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#14997]
## Steps to Reproduce

`flutter run --preview-dart-2`

Make any tiny tweak to `widget_inspector.dart` or any other file in package:flutter

Trigger hot reload

See the static analysis errors:

```
[ +832 ms] compiler message: file:///usr/local/google/home/jacobr/git/flutter/3/flutter/packages/flutter/lib/src/widgets/overlay.dart: Error: The parameter 'value' of the method '_RenderTheatre::child' has type #lib1::RenderStack, which does not match the corresponding type in the overridden method (#lib2::RenderBox).
[        ] compiler message: Change to a supertype of #lib2::RenderBox (or, for a covariant parameter, a subtype).
[        ] compiler message: file:///usr/local/google/home/jacobr/git/flutter/3/flutter/packages/flutter/l
ib/src/rendering/object.dart: Context: This is the overriden method ('child').

```
These errors do not show up on the first load, only on hot reload.
I suspect they may be mixin related based on the parameters being defined by mixins of the class.
The error is not fatal and the app appears to run fine.

**Comment by cbracken** [comment]
@jacob314 is this now fixed after yesterday's roll?

**Comment by a-siva** [comment]
https://github.com/flutter/flutter/pull/15049 addresses the issue.
