### ISSUE TITLE
[google_maps_flutter] ClipRRect around a blur creates rectangular clip on top of a map

### ISSUE THREAD

**Issue by Hari-07** [flutter/flutter#149990]
### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. Paste the below button over a google map instance (Couldn't get google map in dartpad unfortunately)
2. When the overlay shows up, the corners are still blurred (Not getting rounded by the clip)
3. The same doesn't happen without a map as can be seen in this dartpad
 
https://dartpad.dev/?id=c570d447aae63fc7ede991da8139a1f6

### Expected results

Expect the blur to have rounded rect shape over the map.

The really weird part is that it doesn't fail to clip completely, only the rounded portion isn't getting clipped. And that too the color inside the overlay is getting rounded by the clip correctly, its only the blur layer that's getting effected. 

### Actual results

The blur has rectangular clip

### Code sample

<details open><summary>Code sample</summary>

```dart
GestureDetector(
                  // onTap: centerMap,
                  onTap: () {
                    Navigator.of(context).push(
                      // MaterialPageRoute(
                      //   barrierDismissible: true,
                      //   builder: (context) => const SecondPage(),
                      // ),
                      PageRouteBuilder(
                        opaque: false, // set to false
                        pageBuilder: (_, __, ___) {
                          return Center(
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(50),
                              child: BackdropFilter(
                                filter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
                                child: Container(
                                  color: Colors.white10,
                                  height: 200,
                                  width: 200,
                                  // color: Colors.red,
                                ),
                              ),
                            ),
                          );
                        },
                        barrierDismissible: true,
                      ),
                    );
                  },
                  child: Container(
                    padding: const EdgeInsets.all(8),
                    color: Colors.blue,
                    child: const Text('Show Overlay'),
                  ),
                ),
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

Bugged-Clipping over a google map
<img width="291" alt="image" src="https://github.com/flutter/flutter/assets/22373191/2a7f5366-af65-4de5-a714-1c1ee6ffde4e">

Correct-Clipping over a regular widget (See dartpad for code)
<img width="312" alt="image" src="https://github.com/flutter/flutter/assets/22373191/f243d099-6a1d-4b35-af6a-9620794ca35d">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Hari-07 
Looks like it is not specific to maps, but platform-views on ios in general, as you can check https://github.com/flutter/flutter/issues/115926#issuecomment-1329603325 and most probably hitting the same issue.

**Comment by Hari-07** [comment]
Does seem related, I verified that without a platform view it works fine. Although that comment says clipping isn't supported at all, which isn't the behaviour Im seeing . Not sure if things changed between then and now. I'm on flutter 3.22.

If clipping as a whole wasn't supported the whole screen would get blurred , which means somewhere we're just passing the rect instead of the radius.

**Comment by darshankawar** [comment]
Thanks for the insights @Hari-07 
Would be good to share these findings in the linked issue for better tracking. I still feel it is related to the underlying platform view and isn't specific to google_maps_flutter package which leans me towards closing this in favor of the linked issue.

**Comment by Hari-07** [comment]
Yeah you can go ahead and close this issue as a duplicate. Will put a comment in the linked issue

**Comment by darshankawar** [comment]
Closing as duplicate.
