### ISSUE TITLE
[dart2wasm] iFrame locks position on transition into view

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#149909]
Original [issue](https://github.com/dart-lang/sdk/issues/55942) filed on the Dart SDK repo - creating this issue to transfer to the Flutter Web team. From discussion on the original issue, it appears this may be the result of https://github.com/flutter/flutter/issues/133466.

**Copied from original issue:**

In DevTools, we use iFrames for a couple of features:
1) The embedded Perfetto trace viewer on the Performance page
2) DevTools extensions

In both cases, the iFrame is transitioned into view by a Flutter tab view. Upon selecting the "Timeline Events" tab on the Performance page or upon selecting a top level tab for a DevTools extension, the iFrame locks its position before fully transitioning into view:
![Screenshot 2024-06-05 at 9 56 17 AM](https://github.com/dart-lang/sdk/assets/43759233/9a1e3a6a-0408-406c-b97a-75aeaa565411)
![Screenshot 2024-06-05 at 9 55 52 AM](https://github.com/dart-lang/sdk/assets/43759233/d3ec0495-d3ea-4d6b-85de-021cfa89737d)

Requirements:
- Pull the latest code from the flutter/devtools master branch
- Pull the latest code from the Dart SDK (or patch [this change](https://dart-review.googlesource.com/c/sdk/+/369100) if it has not landed yet.)
- Set up your DevTools environment so that
  - You have access to the `devtools_tool` executable - [docs](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#set-up-your-devtools-environment)
  - You have the LOCAL_DART_SDK environment variable set - [docs](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#frontend--devtools-server)

Repro steps:
1. Build DevTools from source with wasm: `devtools_tool serve --wasm`. If you want to build with `--no-strip-wasm`, add the flag [here](https://github.com/flutter/devtools/blob/master/tool/lib/commands/build.dart#L103) before serving DevTools.
2. Run the Flutter gallery app (this app depends on `package:provider`, which has a DevTools extension)
3. Copy the VM service URI from the Flutter gallery app and connect it to the DevTools instance you just served with wasm.
4. Navigate to either the Performance screen > Timeline Events OR to the top level Provider screen tab (should be present as long as you are running flutter gallery) to observe the incorrect iFrame position.

If this does not repro on the first try, refresh the DevTools window in the browser and try again.

**Comment by darshankawar** [comment]
> Requirements:
> 
> * Pull the latest code from the flutter/devtools master branch
> * Pull the latest code from the Dart SDK (or patch [this change](https://dart-review.googlesource.com/c/sdk/+/369100) if it has not landed yet.)
> * Set up your DevTools environment so that
>   
>   * You have access to the `devtools_tool` executable - [docs](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#set-up-your-devtools-environment)
>   * You have the LOCAL_DART_SDK environment variable set - [docs](https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#frontend--devtools-server)
> 
> Repro steps:
> 
> 1. Build DevTools from source with wasm: `devtools_tool serve --wasm`. If you want to build with `--no-strip-wasm`, add the flag [here](https://github.com/flutter/devtools/blob/master/tool/lib/commands/build.dart#L103) before serving DevTools.
> 2. Run the Flutter gallery app (this app depends on `package:provider`, which has a DevTools extension)
> 3. Copy the VM service URI from the Flutter gallery app and connect it to the DevTools instance you just served with wasm.
> 4. Navigate to either the Performance screen > Timeline Events OR to the top level Provider screen tab (should be present as long as you are running flutter gallery) to observe the incorrect iFrame position.
> 
> If this does not repro on the first try, refresh the DevTools window in the browser and try again.

I will try to follow these steps and see if I can replicate it or not. Currently, based on the report, labeling for team's attention.

**Comment by eyebrowsoffire** [comment]
I think this should be resolved after https://github.com/flutter/flutter/issues/152139. @kenzieschmoll can you confirm?

**Comment by kenzieschmoll** [comment]
Confirmed this is resolved on

```
Flutter 3.24.0-1.0.pre.441 • channel master • git@github.com:flutter/flutter.git
Framework • revision 0e720e84a4 (2 days ago) • 2024-08-05 14:56:14 +0100
Engine • revision 0aac603420
Tools • Dart 3.6.0 (build 3.6.0-114.0.dev) • DevTools 2.38.0
```

**Comment by darshankawar** [comment]
Closing as resolved.
