### ISSUE TITLE
RFW golden-file test is/was blocking engine->framework roll

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#149934]
The [engine roll into the framework](https://github.com/flutter/flutter/pull/149914) is [failing](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8745769638558462033/+/u/run_test.dart_for_customer_testing_shard_and_subshard_None/stdout) due to a golden-file test in `package:rfw`:

> ```
>  00:16 +123 -1: /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.HWFIUQ/tests/packages/rfw/test/material_widgets_test.dart: Implement Material properties
> | 00:16 +123 -1: /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.HWFIUQ/tests/packages/rfw/test/material_widgets_test.dart: Implement Material properties
> | ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
> | The following assertion was thrown while running async test code:
> | Golden "goldens/material_test.material_properties.png": Pixel test failed, 0.00%, 2px diff detected.
> | Failure feedback can be found at
> | /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.HWFIUQ/tests/packages/rfw/test/failures
> |
> | When the exception was thrown, this was the stack:
> | #0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:106:5)
> | <asynchronous suspension>
> | #1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
> | <asynchronous suspension>
> | <asynchronous suspension>
> | #3      _expect.<anonymous closure> (package:matcher/src/expect/expect.dart:123:26)
> | <asynchronous suspension>
> | <asynchronous suspension>
> | #5      expectLater.<anonymous closure> (package:flutter_test/src/widget_tester.dart:512:24)
> | <asynchronous suspension>
> | #6      main.<anonymous closure> (file:///b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.HWFIUQ/tests/packages/rfw/test/material_widgets_test.dart:566:5)
> | <asynchronous suspension>
> | #7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
> | <asynchronous suspension>
> | #8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025:5)
> | <asynchronous suspension>
> | <asynchronous suspension>
> | (elided 3 frames from dart:async and package:stack_trace)
> |
> | The exception was caught asynchronously.
> | ════════════════════════════════════════════════════════════════════════════════════════════════════
> |
> | 00:16 +123 -2: /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.HWFIUQ/tests/packages/rfw/test/material_widgets_test.dart: Implement Material properties [E]
> |   Test failed. See exception logs above.
> |   The test description was: Implement Material properties
> ```

The breakage is due to a [Skia bug fix](https://skia.googlesource.com/skia.git/+/b7f51dfcc34200c92786e04e08b6255ce7dccaf4%5E%21/#F0) that was [rolled into the engine](https://github.com/flutter/engine/pull/53275). It's a _good_ change (fixes a bug), and it should not be blocking our rollers.

I am going to temporarily bump the thresh-hold from 0% to >0%

This issue is to track if `package:rfw` owners want to reduce the thresh-hold after it lands, disable the test, change the test parameters, etc, and can be closed if no action is needed.

**Comment by matanlurey** [comment]
Apparently there is no easy way to change per-test thresholds so I'll disable the test instead.

**Comment by stuartmorgan** [comment]
Re-enabling customer-testing tests should be tracked at the framework level, so adjusting teams accordingly; the fact that this happens to be a test from flutter/packages is a coincidence.
