### ISSUE TITLE
macOS Sonoma app always logs "WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application."

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#150062]
Running app always shows "Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:."
```
flutter run -d macos
...
Building macOS application...
✓ Built build/macos/Build/Products/Debug/test_create.app
Syncing files to device macOS...                                    39ms
...
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:55998/3j3JH_UMKmA=/
2024-06-11 12:50:54.702 test_create[25161:2066612] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
```

**Comment by sqlwatchmen** [comment]
I also see this message. I was able to get rid of the message by updating my macos/Runner/AppDelegate.swift file to include:
```swift
override func applicationSupportsSecureRestorableState(_ app: NSApplication) -> Bool {
    return true
}
```

with the full file being: 

```swift
import Cocoa
import FlutterMacOS

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    return true
  }

  override func applicationSupportsSecureRestorableState(_ app: NSApplication) -> Bool {
    return true
  }
}
```

but I'm not sure if this is the correct way to address this issue or if it has other implications that I am not aware of. 

My mac info:
![Screenshot 2024-07-01 at 10 42 18 AM](https://github.com/flutter/flutter/assets/169178412/ae532598-81df-4d95-850d-8a907451aa1d)

**Comment by jmagman** [comment]
I _think_ it should be safe to implement this the way @sqlwatchmen says, we aren't doing anything unsafe restoring state? @cbracken any idea why that wouldn't be true?

This would involve adding the method to the `create` template:
https://github.com/flutter/flutter/blob/a3c7094d7ddae7ff49c56dd4f32dc458d10e4342/packages/flutter_tools/templates/app_shared/macos.tmpl/Runner/AppDelegate.swift#L8

and also an automigration similar to:
https://github.com/flutter/flutter/blob/a3c7094d7ddae7ff49c56dd4f32dc458d10e4342/packages/flutter_tools/lib/src/macos/migrations/nsapplicationmain_deprecation_migration.dart

**Comment by cbracken** [comment]
@jmagman I can't think of any reason why we shouldn't go ahead and make that change. We're adding it to the template, so in the end it's end-user code, so developers always have the option of altering/removing it if it doesn't work for their usecase. This method has been included in Apple's AppKit app template since Xcode 13.2.

I've drafted a PR here: https://github.com/flutter/flutter/pull/151605

**Comment by jmagman** [comment]
> and also an automigration similar to:
> https://github.com/flutter/flutter/blob/a3c7094d7ddae7ff49c56dd4f32dc458d10e4342/packages/flutter_tools/lib/src/macos/migrations/nsapplicationmain_deprecation_migration.dart

@cbracken is there any reason not to also add a migration to add the func if it's not present?  Or do you think "removing it if it doesn't work for their usecase" is common enough that we shouldn't assume?

**Comment by cbracken** [comment]
Ah missed that comment but yeah an automigration seems pretty reasonable here. I strongly doubt that a ton of Flutter apps are using serialisation incompatible with NSSecureCoding; in all likelihood all their serialisation is Flutter-based. Will do.

**Comment by cbracken** [comment]
Alright - patch updated with a migrator.

**Comment by cbracken** [comment]
Landed and should be resolved on `master` branch.
