### ISSUE TITLE
[Material 3] IconButton should support statesController as well

### ISSUE THREAD

**Issue by Knupper** [flutter/flutter#150086]
### Use case

For TextButton/ElevatedButton/OutlineButton it is possible to give a own instance of a WidgetlStatesController / _MaterialStatesController_ into it. For a IconButton we have no such possibility, it always creates a own one in `_SelectableIconButtonState`. 

### Proposal

A IconButton has the same interface as the other M3 Buttons.

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/139372
