### ISSUE TITLE
TabBar overflow behaviour

### ISSUE THREAD

**Issue by Pebkac03** [flutter/flutter#150043]
### Use case

There are few alternatives for handling longer tabbars. Currently only isScrollable: true is the only solution for handling any length.

### Proposal

I propose two additional ways to handle this. Either having the TabBar wrap to the next line on overflow or having a button with a drop-down menu for all tabs that do not fit on the far right of the TabBar.

Either this could be implemented with Boolean properties similar to isScrollable only allowing one of them to be true or with a new property: tabBarOverflowBehaviour of type TabBarOverflowBehaviour.

This seems to me to be small enough of a change to be considered being added to native flutter.

**Comment by huycozy** [comment]
I see there's an open issue addressing this at https://github.com/flutter/flutter/issues/128148. Closing this issue as a duplicate, so please follow up on it for further updates. Thank you!
