### ISSUE TITLE
The codelab for Dart keeps going to step 9 in the flutter codelab

### ISSUE THREAD

**Issue by paulzazzarino** [flutter/flutter#150036]
When launching the codelab for Dart it keeps going to step 9 in the flutter codelab

**Comment by darshankawar** [comment]
@paulzazzarino 
Can you share codelab link ?

**Comment by paulzazzarino** [comment]
Tried under chrome and edge, same results.Enter this then attempt option four, goes to step 9.https://developers.google.com/learn/pathways/intro-to-flutter#codelab-/codelabs/from-java-to-dartSent via BV9800 Android Pie.On Jun 11, 2024 07:05, darshankawar ***@***.***> wrote:
@paulzazzarino
Can you share codelab link ?

**Comment by darshankawar** [comment]
This seems to be expected, but if you still have any issues, you will need to report this in dedicated issue tracker:

<img width="1317" alt="Screenshot 2024-06-12 at 11 26 35 AM" src="https://github.com/flutter/flutter/assets/67046386/2a95dc95-e4d1-4d46-895a-5ae5cc3bb0a6">

Closing from here.

**Comment by paulzazzarino** [comment]
Report to where ?One can not even access the dart class.Sent via BV9800 Android Pie.On Jun 12, 2024 01:57, darshankawar ***@***.***> wrote:
This seems to be expected, but if you still have any issues, you will need to report this in dedicated issue tracker:
Screenshot.2024-06-12.at.11.26.35.AM.png (view on web)
Closing from here.
