### ISSUE TITLE
Rename `AnimatedAlign`

### ISSUE THREAD

**Issue by caseycrogers** [flutter/flutter#150006]
### Use case

`AnimatedAlign.heightFactor` (and `widthFactor`) are incredibly useful for animating a widget out of the way in a row or list or similar where you want the adjacent elements to take up the space being made by the exiting widget. However, the name of the widget doesn't suggest that it provides this functionality at all so most Flutter developers don't know about this extremely useful feature for a common use case.

We had a similar problem with `AnimatedBuilder`-it was a tremendously useful widget but had a name that suggested it was more niche than it was. One example where a Senior Flutter engineer only just now discovered `AnimatedAlign`'s collapsing functionality:
https://twitter.com/luke_pighetti/status/1799545434987180514

### Proposal

Have a widget with an intuitive name that exposes a `width`/`heightFactor`. Maybe the name could be `AnimatedCollapse` or `AnimatedFractionallySizedBox`?

This could be achieved by:
1. Renaming `AnimatedAlign`
2. Creating a new widget and pulling `width`/`heightFactor` out of `AnimatedAlign` so `AnimatedAlign` does what it says on the tin (animate aligns with no width/height factor)
3. Having this new widget and `AnimatedAlign` and have them both do the same thing, keeping `AnimatedAlign` around just for legacy reasons like we do with `AnimatedBuilder`

To me option 1 feels by far the cleanest. `AnimatedAlign` is so under-discovered that it'd probably affect very few existing Flutter projects.

**Comment by kishansr1** [comment]
Hey @caseycrogers, If i am not wrong then `AnimatedFractionallySizedBox` already exist.
CC @goderbauer

**Comment by caseycrogers** [comment]
> Hey @caseycrogers, If i am not wrong then `AnimatedFractionallySizedBox` already exist. CC @goderbauer

Oh cool thanks this is exactly what I want, idk how I missed it!
