### ISSUE TITLE
Plugin 'Dart' (version '232.10286') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is AI-233.14808.21 Plugin 'Flutter' (version '78.2.2') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is AI-233.14808.21

### ISSUE THREAD

**Issue by Bhoomikaa11** [flutter/flutter#150042]

**Comment by LimaneGaya** [comment]
@Bhoomikaa11 I think you need to update your dart and flutter plugin.

**Comment by huycozy** [comment]
@Bhoomikaa11 Looks like you are seeing this on Android Studio with Dart and Flutter plugins. If so, it's more fit to be reported on https://github.com/flutter/flutter-intellij/issues. You can consider upgrading plugins as mentioned above first. 

Closing as this doesn't seem to be a Flutter framework issue. If you disagree, please provide all information indicated in issue template and I will reopen this.
