### ISSUE TITLE
[Question] Is there a programmatic way to deobfuscate other than using `flutter symbolize`?

### ISSUE THREAD

**Issue by shengzhou1216** [flutter/flutter#150080]
Hello,

I am currently using the `flutter symbolize` tool to deobfuscate obfuscated stack traces. This is very helpful for debugging and troubleshooting. However, I would like to know if there are any other programmatic methods to deobfuscate stack traces?

For example, are there any APIs or libraries that can be called in code to achieve deobfuscation? This would help automate the deobfuscation process on the server side without relying on the command-line tool.

Thank you very much!

**Comment by darshankawar** [comment]
@shengzhou1216 
This seems similar to https://github.com/flutter/flutter/issues/114669 in which you can follow-up for further updates.
Also check below documentation for further reference:

https://github.com/flutter/flutter/blob/master/docs/engine/Crashes.md#symbolicating-stack-traces-for-engine-crashes

https://github.com/dart-lang/dart_ci/blob/main/github-label-notifier/symbolizer/README.md#using-this-locally

If above don't help much, then it is better to ask this question in flutter's discord to get quick response, as this is more of a question than a bug report or feature request. 

Closing from here. If you disagree, write in comments and I'll reopen it.
