### ISSUE TITLE
"command 'flutter.createProject' not found" in VS Code after following Getting Started guide

### ISSUE THREAD

**Issue by gustavost26** [flutter/flutter#150013]
### Steps to reproduce

Prompt VS Code to install Flutter

Launch VS Code.

To open the Command Palette, press Command + Shift + P.

In the Command Palette, type flutter.

Select Flutter: New Project.

VS Code prompts you to locate the Flutter SDK on your computer.

If you have the Flutter SDK installed, click Locate SDK.

If you do not have the Flutter SDK installed, click Download SDK.

This option sends you the Flutter install page if you have not installed Git as directed in the [development tools prerequisites]

When prompted Which Flutter template?, ignore it. Press Esc. You can create a test project after checking your development setup.

I followed the same steps as the flutter tutorial: https://docs.flutter.dev/get-started/install/macos/mobile-ios?tab=vscode

I'm having the following errors:

<img width="292" alt="Captura de ecrã 2024-06-10, às 19 34 16" src="https://github.com/flutter/flutter/assets/1749769/3ffa1417-472a-4456-9b2e-4c32926e5baf">
<img width="375" alt="Captura de ecrã 2024-06-10, às 19 34 32" src="https://github.com/flutter/flutter/assets/1749769/a0be8dc7-d450-4587-a4b0-31f0c7046794">

I'm using VS Code 1.90

### Actual results

I have already applied the settings from the flutter tutorial and I am getting errors when running it. I have tried several solutions that I found on the internet but none of them solved the problem.

Error: 

Command 'Flutter: New Project' resulted in an error
command 'flutter.createProject' not found

zsh: command not found: flutter

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
Hi @gustavost26 
Have you completed steps at [Download the Flutter SDK](https://docs.flutter.dev/get-started/install/macos/mobile-ios?tab=vscode#download-the-flutter-sdk)? If you did, can provide the output of `flutter doctor -v` on Terminal window?
