### ISSUE TITLE
Mac mac_host_engine sub builds may timeout when also installing Xcode

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#150011]
It seems that sub builds of Mac mac_host_engine have a time limit of 1 hour, however, the builds tend to take ~45 minutes. When it runs on a newly upgrade Mac-14 host, it may timeout if Xcode is also being re-installed, which will push the time it takes over an hour.

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20mac_host_engine/10985/infra

**Comment by vashworth** [comment]
CL to allow build configs in engine to set a timeout: https://flutter-review.googlesource.com/c/recipes/+/57980

build config would look like this:

```diff
{
    "builds": [
        {
            "name": "ci/mac_debug_arm64",
            ...
            "properties": {
                "$flutter/osx_sdk": {
                    "sdk_version": "15a240d",
                    "cleanup_cache": true
                }
            },
            ...
+           "timeout": 10
        },
        ....
```

**Comment by jmagman** [comment]
> CL to allow build configs in engine to set a timeout: https://flutter-review.googlesource.com/c/recipes/+/57980

cc @cbracken https://github.com/flutter/engine/pull/52913
