### ISSUE TITLE
[adaptive_scaffold] Navigation_Rail and Navigation_Bar have forced outside padding when using Adaptive_Scaffold constructor.

### ISSUE THREAD

**Issue by DylanCross** [flutter/flutter#150058]
### Steps to reproduce

Create an AdaptiveScaffold with a NavRail or NavBar. Set the background color of the NaveBar to something other than the app's background color. This can be done with ThemeData.navigationRailTheme.

The source of the padding is a default parameter in the standardNavigationRail function for "padding". 

```
static Builder standardNavigationRail({   
   ... 
       EdgeInsetsGeometry padding = const EdgeInsets.all(8.0),
   ...
  }) {...}
  
```
  
  This default is used when called in the SLotLayout for both the medium and large breakpoints when using the Adaptive Scaffold class. 

### Expected results

The NavBar / NavRail should extend to edges of page. There should not be space outside of the NavBar / NavRail. 

Alternative, user should be able to specify default navbar padding as a parameter to AddaptiveScaffold. 

### Actual results

8.0 pixels of padding is added and cannot be overridden. 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>
Note: the red area the the background of the NavBar. The white around is forced padding. 

![paddingloc](https://github.com/flutter/flutter/assets/103907711/486e336f-1edd-4768-ba5a-fd489bc70e6e)
![padding](https://github.com/flutter/flutter/assets/103907711/72c03db7-11d1-4d62-b136-74717f98620f)

</summary>

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @DylanCross 
I checked this with package sample code [main.dart](https://github.com/flutter/packages/blob/main/packages/flutter_adaptive_scaffold/example/lib/main.dart) but I can see the overrided `padding` works as expected. 

Can you retry with this sample code and confirm? If the issue only appears on your code, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex code.
