### ISSUE TITLE
[image_picker_for_web] Wasm compatibility

### ISSUE THREAD

**Issue by nietsmmar** [flutter/flutter#150032]
### Steps to reproduce

run `flutter build web --wasm`

### Expected results

App builds

### Actual results

App does not build.

```
Context: The unavailable library 'dart:html' is imported through these packages:

    web_plugin_registrant.dart => package:image_picker_for_web => dart:html
```

### Code sample

`flutter run web --wasm`

### Logs

```
Context: The unavailable library 'dart:html' is imported through these packages:

    web_plugin_registrant.dart => package:image_picker_for_web => dart:html
```

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on Manjaro Linux 6.1.92-1-MANJARO, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by mkustermann** [comment]
The `package:image_picker_for_web` was migrated to new JS interop which works on wasm (see https://github.com/flutter/packages/pull/5799). Could it be that you are on an old version of `package:image_picker_for_web`?

**Comment by huycozy** [comment]
@nietsmmar As mentioned above, `image_picker_for_web` is supported for wasm since `3.0.3` (see https://pub.dev/packages/image_picker_for_web/changelog#303). Can you check your current version of `image_picker_for_web` from `pubspec.lock` file?

**Comment by nietsmmar** [comment]
@huycozy oh yes, somehow my upgrade did not go through and I was still on `3.0.2` sorry!
