### ISSUE TITLE
Flutter build dashboard not showing most recent commit

### ISSUE THREAD

**Issue by yaakovschectman** [flutter/flutter#150065]
The flutter build dashboard currently only goes up to commit https://github.com/flutter/flutter/commit/aad70e5cdb8e8cdba025cb10f496bc2f170131a3, while the most recent commit as of now is 14df7be3f9471a97f34e4601fb7710850373ac3b, which is already over 4 hours old.

**Comment by yaakovschectman** [comment]
cc @christopherfujino

**Comment by stuartmorgan** [comment]
Closing as this seems to be resolved now; it's showing the most recent commit, and also the one that was missing.

**Comment by christopherfujino** [comment]
For future archaeologists, authenticated users with the build dashboard can refresh github commits via the settings menu
