### ISSUE TITLE
Broken links, typos, and inconsistent formatting in Style Guide for Flutter Repo

### ISSUE THREAD

**Issue by swrenn** [flutter/flutter#150164]
### Broken Links

Many links in the Style Guide take the form `url[label]` rather than `[label](url)`, so they do not render as links.

### Typos

There are a few typos and grammar issues. For example, the Guide says `You can also use "See also" links, is in:`. Here, `is in` should be `as in` or left out.

### Inconsistent Formatting

Lines are broken sometimes around 80 characters, sometimes around 120, and sometimes not at all.

**Comment by danagbemava-nc** [comment]
Hi @swrenn, it appears that this or some portion of this may have been resolved by https://github.com/flutter/flutter/pull/150071

Can you confirm this?

**Comment by swrenn** [comment]
Hi @danagbemava-nc. Yes, #150071 fixes the links. The typos and formatting remain. I updated my PR to resolve the merge conflicts from #150071.
