### ISSUE TITLE
Support multiple FlutterSurfaceViews per FlutterView on Android

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#150122]
Our new platform views plan for Android requires that we have multiple FlutterSurfaceViews per FlutterView.

Today the engine uses a `FlutterImageView` to layer flutter and native content, our new approach requires that we have a layer of SurfaceViews which necessitates multiple `FlutterSurfaceView`s.

The simple change of using a `FlutterSurfaceView` instead of a `FlutterImageView` fails because *hand wavy* some initialization code doesn't run for the second `FlutterSurfaceView`.

**Comment by johnmccutchan** [comment]
I do, let me clean it up and get it into a state where you can easily reproduce the issue here.

**Comment by jonahwilliams** [comment]
Using an overlay surface view will cause all ads to trigger as occluded, since occlusuon is based on layout bounds and not opacity. We'll need to use a SurfaceControl instead. I'll track this work in a new issue.
