### ISSUE TITLE
Flutter support armebi?

### ISSUE THREAD

**Issue by xiang23** [flutter/flutter#15016]
In the release apk only include armebi-v7a

**Comment by cbracken** [comment]
Can you provide a bit more detail?

Flutter also includes support for arm64. You can try with:
```
flutter build apk --release --target-platform android-arm64
```

Does that answer your question?

**Comment by xiang23** [comment]
For some reasons, our project required an armebi native binary . Do you have any idea？

**Comment by rmtmckenzie** [comment]
If your issue is that a library you're depending on comes with armeabi and that's being picked up to run by default (and then it crashes because flutter armeabi isn't found), see #14231 for a possible solution.

**Comment by cbracken** [comment]
Apologies for misunderstanding the original question. As mentioned, we currently support armeabi-v7a and armeabi-v8a on Android but we don't currently have plans to support armeabi, which was deprecated in Android 4.1 and removed in Android 4.2 (Jellybean).

That said, the [engine](https://github.com/flutter/engine) is open-source, so you could try building it yourself. Instructions for building can be found in [CONTRIBUTING.md](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md) in the engine repo.

**Comment by JackCho** [comment]
@cbracken I find the default `--android-cpu` arg is `arm`, but the output is `armeabi-v7a`. 
I don't follow the compile args
![17_40_48__03_15_2018](https://user-images.githubusercontent.com/3806682/37455529-41d0c0de-2878-11e8-95d9-fc48db27150e.jpg)

**Comment by cbracken** [comment]
@JackCho `arm` in this context refers to armeabi-v7a. For armeabi-v8a, pass `--android-cpu=arm64`.

**Comment by mimers** [comment]
@cbracken  Is there a simple way to build flutter/engine with armeabi? changing gn args or something without replacing tons of args in *.ninja?

**Comment by charleybin** [comment]
wanna know how to build flutter/engine with armeabi not armeabi-v7a.

**Comment by southpeak** [comment]
It is difficult to build flutter/engine to support armeabi, because there are some dependent libraries that only support armeabi-v7a, such as vulcan. I had tried to do that but failed.

**Comment by alexandranb** [comment]
Hi,

I don't really understand some things related to the newest Google Play Developer policy regarding the 64-bit requirement. Do we need to update anything in our projects to be compliant? If anyone could help me understand I would be deeply appreciative. 

Thank you
