### ISSUE TITLE
How to Run a Flutter App on Windows Preinstallation Environment (WinPE)?

### ISSUE THREAD

**Issue by Thiru-01** [flutter/flutter#150100]
I'm trying to run a Flutter app on a Windows Preinstallation Environment (WinPE). WinPE is a lightweight version of Windows used for deploying PCs, workstations, and servers, or for troubleshooting an operating system while it's offline.

I've successfully developed and tested my Flutter app on Windows 10, but I'm encountering difficulties when trying to execute the same app (exe) in the WinPE environment. And it doesn't show any error messages too.

**Comment by darshankawar** [comment]
Windows Preinstallation Environment (WinPE) seems to be an altogether a separate OS, so I don't think there's an official support by Flutter for it yet. Also, looking at the official docs of the OS, https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-intro?view=windows-11, its purpose is to install, deploy, and repair Windows desktop editions, Windows Server, and other Windows operating systems indicating very limited usage.

You can refer https://www.reddit.com/r/FlutterDev/comments/18r3sg2/can_flutter_run_in_winpe/

I am going ahead and closing.

**Comment by Thiru-01** [comment]
Thanks for your answer. I have a requirement to create an application in WinPE. Since I am good at Flutter, I would like to create that app in Flutter, but I haven't found any valid answer. Anyway, thanks for your time.
