### ISSUE TITLE
Navigator pop() and push() will cause initState and dispose not called in order.

### ISSUE THREAD

**Issue by jerrywell** [flutter/flutter#15012]
## Steps to Reproduce

running following code and do following steps.

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new TestWidget(),
  ));
}

class TestWidget extends StatefulWidget {

  @override
  State<StatefulWidget> createState() {
    return new TestWidgetState();
  }
}

class TestWidgetState extends State<TestWidget> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Test'),
      ),
      body: new Center(
        child: new GestureDetector(
          onTap: pushTWidget,
          child: new Text('push TWidget 1'),
        )
      ),
    );
  }

  void pushTWidget() {
    Navigator.push(context, new MaterialPageRoute(builder: (BuildContext context) {
      return new Scaffold(
        appBar: new AppBar(
          title: new Text('Test for TWidget 1'),
        ),
        body: new Center(
          child: new TWidget(),
        ),
      );
    }));
  }
}

class TWidget extends StatefulWidget {
  TWidget({Key key}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return new TWidgetState();
  }
}

class TWidgetState extends State<TWidget> {
  @override
  Widget build(BuildContext context) {
    return new Center(
      child: new GestureDetector(
        onTap: () {
          Navigator.pop(context);
          Navigator.push(context, new MaterialPageRoute(builder: (BuildContext context) {
            return new Scaffold(
              appBar: new AppBar(
                title: new Text('Test for TWidget 2'),
              ),
              body: new TWidget(),
            );
          }));
        },
        child: new Text('pop TWidget1 and push TWidget 2'),
      ),
    );
  }

  @override
  void initState() {
    print('init state: $this');
    super.initState();
  }

  @override
  void dispose() {
    print('dispose: $this');
    super.dispose();
  }

  @override
  void didUpdateWidget(TWidget oldWidget) {
    print('didUpdateWidget: $this');
    super.didUpdateWidget(oldWidget);
  }


```

1. press "push TWidget 1"
2. press "pop TWidget 1 and push TWidget 2"

you will see the following lifecycle printed

```
I/flutter (21731): init state: TWidgetState#02291(lifecycle state: created)
I/flutter (21731): didUpdateWidget: TWidgetState#02291
I/flutter (21731): init state: TWidgetState#ad83f(lifecycle state: created)
I/flutter (21731): didUpdateWidget: TWidgetState#02291
I/flutter (21731): didUpdateWidget: TWidgetState#ad83f
I/flutter (21731): dispose: TWidgetState#02291
```

the state 02291 is disposed after the new one ad83f, but the expected result should be 02291 initState => 02291 dispose => ad83f init. We ran into this issue for:

1. because our app bind/unbind event to model on the initState and dispose. we will trigger a scrollTo event for this to do animation if given widget provides scroll index. if so, at this time, the AnimationController will get current position and calculate what distance we need to move. Unfortunately, the position getter will finally fails the fetch at the line because there are two list view used it:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_controller.dart#L112

2. our model will depend on initState and dispose to start() and stop() collaboration event.

if the state is initState1 => dispose1 => initState2. the lifecycle will be symmetric and won't encounter those issues. does this a bug? or i should use in other expected way? thanks.

## Logs

```
I/flutter (21731): init state: TWidgetState#02291(lifecycle state: created)
I/flutter (21731): didUpdateWidget: TWidgetState#02291
I/flutter (21731): init state: TWidgetState#ad83f(lifecycle state: created)
I/flutter (21731): didUpdateWidget: TWidgetState#02291
I/flutter (21731): didUpdateWidget: TWidgetState#ad83f
I/flutter (21731): dispose: TWidgetState#02291
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.1.8-pre.21, on Mac OS X 10.12.6 16G29, locale en-TW)
    • Flutter version 0.1.8-pre.21 at /Users/jerry/Documents/project/flutter
    • Framework revision eaa9848fd4 (5 hours ago), 2018-02-28 17:53:38 -0800
    • Engine revision 6607231638
    • Dart version 2.0.0-dev.31.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/jerry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.0.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (2 available)
    • SM G930F                  • ce01171121b67a1a02 • android-arm64 • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5554      • android-x86   • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by Hixie** [comment]
the old widget gets disposed once its hiding animation completes; this will happen after the new widget is starting to animate in, since they animate in and out at the same time.

**Comment by jerrywell** [comment]
@Hixie, thanks so much for this reply. I have roughly trace the code in framework.dart. but it seems no public(appropriate) lifecycle that can represents the similar order for initState => dispose => iniState. is there any way/timing we can get the similar lifecycle for the needing like above post? thanks again. :)

**Comment by Hixie** [comment]
What we normally do is make sure all our objects support being listened to multiple times. That way it doesn't matter if there are briefly multiple clients.

**Comment by jerrywell** [comment]
Thanks @Hixie. my conclusion is:

Design for model binding should make sure the model can be listened to many times, and be countable. we can bind it in initState, unbind it in dispose, and start/stop the model operation when binding exists and without any listener. Make sure you do not emit any event when binding (e.g. Fire event in initState). Because of the initState/dispose of a state is executing, the event will cause other listeners to receive the event and update the state, while the context scope is locked.

this conclusion may be helpful for the one seeing this issue.

**Comment by Levi-Lesches** [comment]
Sorry to prod a dead issue, but I seem to have a similar issue. I have two pages, the home and the login page. The login page has the responsibility of first logging the user out (disposing of data models), and the home page needs to remove itself as a listener before the user goes to other pages. So something like this: 

```dart
class HomePageModel with ChangeNotifier {
  final DataModel data;

  void init() {
    data.addListener(notifyListeners);
  }

  @override
  void dispose() {
    data.removeListener(notifyListeners);  // CAUSING ERRORS
    super.dispose();
  }
}
```

```dart
class LoginPageState extends State<LoginPage> {
  final DataModel data;

  @override
  void initState() {
    data.dispose();  // purges user data
    super.initState();
  }
  
  // build function here
}
```

For me, the problem is that when taking the user from `HomePage` to `LoginPage`, `LoginPageState.initState` runs before `HomeModel.dispose`, meaning that the `DataModel` is disposed _before_ `HomeModel` has a chance to remove its listeners. Since it tries to do so after the model has already been disposed, it causes errors. How do I get around this?
