### ISSUE TITLE
Text shadows now appear broken on iOS

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#150114]
### Steps to reproduce

@gaaclarke 
@flar 
@jonahwilliams 

Hi I noticed you were all recently working on blurs.  I just upgraded flutter master channel to `fdb74fd3e7` and noticed text shadows are very different on iOS and thinking it might be related to blurs, or at the least this triggers a thought on what change happened.  

With this current change, text shadows look very different between iOS and Android, and downright strange on iOS.

I can't unfortunately show a comparison snapshot since Im seeing it on the two physical devices side by side.  Even looking at the shadow by itself on iOS it can look downright crazy (like tiger stripes) with some of my text shadows (previously very elegant shadows).

I did include a simple widget which if you run on iOS and Android and put the two devices next to each other the difference will be quite obvious

PS, for whatever reason the problem seem even more magnified when using different fonts.  In my case, if you use **Inter** font its gets really crazy.  I left it commented out in the same code incase you have that font and want to try it

### Expected results

Text shadows should look similar between iOS and Android and ideally the way they used to be

### Actual results

Different text shadows appearance on IOS from Android

### Code sample

<details open><summary>Code sample</summary>

```dart
class TestViewShadows extends ConsumerWidget {
  const TestViewShadows(
      { super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {


    return Card(
      elevation: 0,
      color: Colors.transparent,
      margin: EdgeInsets.zero,
      child: Stack(
        alignment: Alignment.center,
        children: [
          Container(color: Colors.white,width: double.infinity,height: double.infinity,),
            //Image.network('https://picsum.photos/800/300'),
          Align(alignment: Alignment.centerLeft,
              child: Padding(
                padding: const EdgeInsets.fromLTRB(4.0, 0, 0, 0),
                child:
                Container(
                  padding: const EdgeInsets.fromLTRB(14, 8, 14, 8),
                  child:
                    const Text('Crazy shadows',
                      style:
                      TextStyle(
                          ///fontFamily: "Inter", <--- Try uncommenting this to see it get even worse
                          fontWeight: FontWeight.w700,
                          fontSize: 34,
                          color: Colors.white,
                          letterSpacing: -1,
                              shadows: <Shadow>[
                                Shadow(
                                  offset: Offset(1.0, 1.0),
                                  blurRadius: 23.0,
                                  color: Color.fromARGB(255, 0, 0, 0),
                                ),
                                Shadow(
                                  offset: Offset(1.0, 1.0),
                                  blurRadius: 2.0,
                                  color: Color.fromRGBO(0, 0, 0, 0),
                                ),
                              ],

                      ),)

                ),
              )
          )
        ],
      ),
    );
  }

}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.23.0-13.0.pre.197 • channel master • https://github.com/flutter/flutter.git
Framework • revision fdb74fd3e7 (6 hours ago) • 2024-06-12 10:47:07 +0200
Engine • revision c7fcbfce60
Tools • Dart 3.5.0 (build 3.5.0-250.0.dev) • DevTools 2.36.0
```

</details>

**Comment by gaaclarke** [comment]
Can you please provide a complete code reproduction?  Also a screenshot would be helpful.

**Comment by gaaclarke** [comment]
Is this what you are seeing?
## impeller
![IMG_7035](https://github.com/flutter/flutter/assets/30870216/053489e0-5533-4b18-b34b-d34f55e1e239)

## skia
![IMG_7036](https://github.com/flutter/flutter/assets/30870216/d78395cf-fbe4-4742-82ed-7751f7ec6d52)

**Comment by mark8044** [comment]
@gaaclarke Very similar but not quite, mine looks like this with the code I have in my original post (might be different shadow setting then you have).  

The difference is very stark when comparing the same exact code between iOS and Android, and iOS on master branch from yesterday compared to today (latest commit)

iOS - `Flutter 3.23.0-13.0.pre.199` - `Engine • revision c7fcbfce60` - `Framework • revision 4afadeae3e`
Using 'Inter' font and using the shadows listed above
![Screen Shot 2024-06-12 at 9 17 03 AM](https://github.com/flutter/flutter/assets/87546778/6b7eab7e-0a85-4480-a937-8572666e78f7)

I did `flutter downgrade` to goto an earlier version to show what it used to look like, it has taken me far down to a much earlier version unfortunately, but this is just to show the difference.  On this earlier version iOS and Android look very similar

iOS - `Flutter 3.22.0-42.0.pre` - `Engine • revision c89defa558` - `Framework • revision e5217b670b`
Using 'Inter' font and using the shadows listed above
![Screen Shot 2024-06-12 at 9 25 34 AM](https://github.com/flutter/flutter/assets/87546778/637cb77f-941f-40bd-85c6-909747485b40)

**Comment by gaaclarke** [comment]
I verified that this regressed as a result of https://github.com/flutter/engine/pull/53261.  I'm not sure if this use case has no golden coverage or if this is high dpi related which might not have good coverage in the golden test runner.

**Comment by mark8044** [comment]
@gaaclarke 

Ok I worked backwards and did a git checkout on hash `966d2b92236b8d284db86b5e99e156e3f53e7bd3` 
which gives me:
```
Flutter 3.23.0-13.0.pre.190 • channel [user-branch] • unknown source
Framework • revision 966d2b9223 (12 hours ago) • 2024-06-11 22:07:23 -0700
Engine • revision 1cdbebee19
Tools • Dart 3.5.0 (build 3.5.0-236.0.dev) • DevTools 2.36.0

```

In that build its way better, but weirdly still not the same as the 3.22 screen shot:

![Screen Shot 2024-06-12 at 9 46 49 AM](https://github.com/flutter/flutter/assets/87546778/d88aa6e8-f3a5-4a0b-ae81-434f85543960)

But this is still more then acceptable.

So it looks like there might be more then one change contributing or multiple iterations of code change which this kind of blur has gone through? But the change after that most recent build is what is most noticeable :

I hope thats somehow helpful

PS.  Im happy to test this code out on other version hashes if it helps in any way

**Comment by gaaclarke** [comment]
Hmm, before we even blur the text used for generating looks a bit off (The letters are jumbled and cropped at the top).  I'm not sure if this is expected:
<img width="690" alt="Screenshot 2024-06-12 at 9 55 41 AM" src="https://github.com/flutter/flutter/assets/30870216/dd77ad6e-a2b9-4bad-8beb-f1bdcf28de18">

**Comment by gaaclarke** [comment]
Here is the input of the gaussian blur with that PR reverted:

<img width="676" alt="Screenshot 2024-06-12 at 10 56 43 AM" src="https://github.com/flutter/flutter/assets/30870216/283c4921-8037-40af-b4cd-4872a9db3802">

Notice that after that PR the input to the gaussian blur is 1/2 the size.  That means we didn't account for high dpi correctly (we are missing the 2x effect transform).

**Comment by gaaclarke** [comment]
I'm not quite sure how the PR that changed the gaussian blur is effecting the input to the gaussian blur.  It may be the use of the filter's coverage before sending the input to the blur.

**Comment by gaaclarke** [comment]
The following patch fixes the text shadow issue, but then regresses the behavior for the `GaussianVsRRect` tests:
```diff
--- a/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
+++ b/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
@@ -417,11 +417,11 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
   }
 
   Entity snapshot_entity = entity.Clone();
-  snapshot_entity.SetTransform(Matrix());
+  snapshot_entity.SetTransform(Matrix::MakeScale({2, 2, 1}));
   std::optional<Rect> source_expanded_coverage_hint;
   if (expanded_coverage_hint.has_value()) {
     source_expanded_coverage_hint =
-        expanded_coverage_hint->TransformBounds(entity.GetTransform().Invert());
+        expanded_coverage_hint->TransformBounds(Matrix::MakeScale({2, 2, 1}) * entity.GetTransform().Invert());
   }
 
   std::optional<Snapshot> input_snapshot =
@@ -563,8 +563,10 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
 
   Entity blur_output_entity = Entity::FromSnapshot(
       Snapshot{.texture = pass3_out.value().GetRenderTargetTexture(),
-               .transform = entity.GetTransform() * input_snapshot->transform *
-                            padding_snapshot_adjustment *
+               .transform = entity.GetTransform() *             //
+                            Matrix::MakeScale({0.5, 0.5, 1}) *  //
+                            input_snapshot->transform *         //
+                            padding_snapshot_adjustment *       //
                             Matrix::MakeScale(1 / effective_scalar),
                .sampler_descriptor = sampler_desc,
                .opacity = input_snapshot->opacity},
```
<img width="627" alt="Screenshot 2024-06-12 at 1 42 47 PM" src="https://github.com/flutter/flutter/assets/30870216/fd6908a3-a17b-4341-a737-6ddf161a6432">

**Comment by gaaclarke** [comment]
This patch fixes it, but it has the 2x dpi scalar hardcoded.  I don't think there is a way we can query the dpi in impeller, looking into it.

```diff
--- a/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
+++ b/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
@@ -390,7 +390,7 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
     return std::nullopt;
   }
 
-  Vector2 scaled_sigma = (effect_transform.Basis() *
+  Vector2 scaled_sigma = (effect_transform.Basis() * Matrix::MakeScale({2, 2, 1}) *
                           Vector2(ScaleSigma(sigma_x_), ScaleSigma(sigma_y_)))
                              .Abs();
   scaled_sigma.x = std::min(scaled_sigma.x, kMaxSigma);
@@ -417,11 +417,11 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
   }
 
   Entity snapshot_entity = entity.Clone();
-  snapshot_entity.SetTransform(Matrix());
+  snapshot_entity.SetTransform(Matrix::MakeScale({2, 2, 1}));
   std::optional<Rect> source_expanded_coverage_hint;
   if (expanded_coverage_hint.has_value()) {
     source_expanded_coverage_hint =
-        expanded_coverage_hint->TransformBounds(entity.GetTransform().Invert());
+        expanded_coverage_hint->TransformBounds(Matrix::MakeScale({2, 2, 1}) * entity.GetTransform().Invert());
   }
 
   std::optional<Snapshot> input_snapshot =
@@ -563,8 +563,10 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
 
   Entity blur_output_entity = Entity::FromSnapshot(
       Snapshot{.texture = pass3_out.value().GetRenderTargetTexture(),
-               .transform = entity.GetTransform() * input_snapshot->transform *
-                            padding_snapshot_adjustment *
+               .transform = entity.GetTransform() *             //
+                            Matrix::MakeScale({0.5, 0.5, 1}) *  //
+                            input_snapshot->transform *         //
+                            padding_snapshot_adjustment *       //
                             Matrix::MakeScale(1 / effective_scalar),
                .sampler_descriptor = sampler_desc,
                .opacity = input_snapshot->opacity},
```

**Comment by gaaclarke** [comment]
The following patch is a more appropriate fix in that it doesn't rely on some magic number.  It however breaks the GaussianVsRRectBlur tests.  If you comment out the line below it fixes those test, but breaks the text shadow (but also looks incorrect when scaling the object).  I suspect this has to do with scaling the content but not scaling the size of a pixel?

I verified also that using the dpi scalar for the "source space" won't work when scaling text.

```diff
--- a/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
+++ b/impeller/entity/contents/filters/gaussian_blur_filter_contents.cc
@@ -379,6 +379,14 @@ std::optional<Rect> GaussianBlurFilterContents::GetFilterCoverage(
   return expanded_source_coverage.TransformBounds(entity.GetTransform());
 }
 
+namespace {
+Vector2 ExtractScale(const Matrix& matrix) {
+  Vector2 entity_scale_x = matrix * Vector2(1.0, 0.0);
+  Vector2 entity_scale_y = matrix * Vector2(0.0, 1.0);
+  return Vector2(entity_scale_x.GetLength(), entity_scale_y.GetLength());
+}
+}  // namespace
+
 std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
     const FilterInput::Vector& inputs,
     const ContentContext& renderer,
@@ -390,7 +398,14 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
     return std::nullopt;
   }
 
+  const Vector2 source_space_scalar =
+      ExtractScale(entity.GetTransform().Basis());
+
   Vector2 scaled_sigma = (effect_transform.Basis() *
+                          // Uncomment the following line to break the text
+                          // shadows, but fix GaussianVsRRectBlur tests.
+                          // Matrix::MakeScale({source_space_scalar.x,
+                          // source_space_scalar.y, 1}) *  //
                           Vector2(ScaleSigma(sigma_x_), ScaleSigma(sigma_y_)))
                              .Abs();
   scaled_sigma.x = std::min(scaled_sigma.x, kMaxSigma);
@@ -417,11 +432,13 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
   }
 
   Entity snapshot_entity = entity.Clone();
-  snapshot_entity.SetTransform(Matrix());
+  snapshot_entity.SetTransform(
+      Matrix::MakeScale({source_space_scalar.x, source_space_scalar.y, 1}));
   std::optional<Rect> source_expanded_coverage_hint;
   if (expanded_coverage_hint.has_value()) {
-    source_expanded_coverage_hint =
-        expanded_coverage_hint->TransformBounds(entity.GetTransform().Invert());
+    source_expanded_coverage_hint = expanded_coverage_hint->TransformBounds(
+        Matrix::MakeScale({source_space_scalar.x, source_space_scalar.y, 1}) *
+        entity.GetTransform().Invert());
   }
 
   std::optional<Snapshot> input_snapshot =
@@ -436,7 +453,10 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
     Entity result =
         Entity::FromSnapshot(input_snapshot.value(),
                              entity.GetBlendMode());  // No blur to render.
-    result.SetTransform(entity.GetTransform() * input_snapshot->transform);
+    result.SetTransform(entity.GetTransform() *
+                        Matrix::MakeScale({1.f / source_space_scalar.x,
+                                           1.f / source_space_scalar.y, 1}) *
+                        input_snapshot->transform);
     return result;
   }
 
@@ -562,12 +582,16 @@ std::optional<Entity> GaussianBlurFilterContents::RenderFilter(
       MinMagFilter::kLinear, SamplerAddressMode::kClampToEdge);
 
   Entity blur_output_entity = Entity::FromSnapshot(
-      Snapshot{.texture = pass3_out.value().GetRenderTargetTexture(),
-               .transform = entity.GetTransform() * input_snapshot->transform *
-                            padding_snapshot_adjustment *
-                            Matrix::MakeScale(1 / effective_scalar),
-               .sampler_descriptor = sampler_desc,
-               .opacity = input_snapshot->opacity},
+      Snapshot{
+          .texture = pass3_out.value().GetRenderTargetTexture(),
+          .transform = entity.GetTransform() *  //
+                       Matrix::MakeScale({1.f / source_space_scalar.x,
+                                          1.f / source_space_scalar.y, 1}) *  //
+                       input_snapshot->transform *                            //
+                       padding_snapshot_adjustment *                          //
+                       Matrix::MakeScale(1 / effective_scalar),
+          .sampler_descriptor = sampler_desc,
+          .opacity = input_snapshot->opacity},
       entity.GetBlendMode());
```
