### ISSUE TITLE
Exhausted heap space, trying to allocate 9301736656 bytes.

### ISSUE THREAD

**Issue by nada13ahmed** [flutter/flutter#150137]
### Steps to reproduce

عند run project or flutter clean or flutter pub get or flutter up grade 

### Expected results

من المفترض ان command line ينفذ كما هو مطلوب

### Actual results

Exhausted heap space, trying to allocate 9301736656 bytes.
Exhausted heap space, trying to allocate 9301736656 bytes.

Exhausted heap space, trying to allocate 9301736656 bytes.

Exhausted heap space, trying to allocate 9301736656 bytes.
Unhandled exception:
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'C:\Users\Sroor For Laptop\AppData\Roaming\.dart-tool\dart-flutter-telemetry.log'
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      LogHandler.save (package:unified_analytics/src/log_handler.dart:285:27)
#5      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:622:17)
#6      _handleToolError (package:flutter_tools/runner.dart:201:23)
#7      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:153:13)
#8      _rootRunBinary (dart:async/zone.dart:1423:47)
#9      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#10     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1798:18)
#11     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#12     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#13     Future._propagateToListeners (dart:async/future_impl.dart:797:16)
#14     Future._completeError (dart:async/future_impl.dart:660:5)
#15     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:746:7)
#16     _rootRun (dart:async/zone.dart:1399:13)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#25     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

### Code sample

C:\src\flutter\bin\flutter.bat --no-color upgrade
Exhausted heap space, trying to allocate 9301736656 bytes.
Exhausted heap space, trying to allocate 9301736656 bytes.

Exhausted heap space, trying to allocate 9301736656 bytes.

Exhausted heap space, trying to allocate 9301736656 bytes.
Unhandled exception:
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'C:\Users\Sroor For Laptop\AppData\Roaming\.dart-tool\dart-flutter-telemetry.log'
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      LogHandler.save (package:unified_analytics/src/log_handler.dart:285:27)
#5      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:622:17)
#6      _handleToolError (package:flutter_tools/runner.dart:201:23)
#7      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:153:13)
#8      _rootRunBinary (dart:async/zone.dart:1423:47)
#9      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#10     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1798:18)
#11     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#12     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#13     Future._propagateToListeners (dart:async/future_impl.dart:797:16)
#14     Future._completeError (dart:async/future_impl.dart:660:5)
#15     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:746:7)
#16     _rootRun (dart:async/zone.dart:1399:13)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

flutter doctor -v

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Exhausted heap space, trying to allocate 9301736656 bytes.
Exhausted heap space, trying to allocate 9301736656 bytes.

Exhausted heap space, trying to allocate 9301736656 bytes.

Exhausted heap space, trying to allocate 9301736656 bytes.
Unhandled exception:
FileSystemException: Failed to decode data using encoding 'utf-8', path = 'C:\Users\Sroor For Laptop\AppData\Roaming\.dart-tool\dart-flutter-telemetry.log'
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#3      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:107:16)
#4      LogHandler.save (package:unified_analytics/src/log_handler.dart:285:27)
#5      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:622:17)
#6      _handleToolError (package:flutter_tools/runner.dart:201:23)
#7      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:153:13)
#8      _rootRunBinary (dart:async/zone.dart:1423:47)
#9      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#10     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1798:18)
#11     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#12     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#13     Future._propagateToListeners (dart:async/future_impl.dart:797:16)
#14     Future._completeError (dart:async/future_impl.dart:660:5)
#15     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:746:7)
#16     _rootRun (dart:async/zone.dart:1399:13)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#25     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by christopherfujino** [comment]
@andrewkolos we should take a look at this one

**Comment by andrewkolos** [comment]
This issue will be discussed in person next week, but here is some info for future reference:

The current flutter stable (5.22.2) depends on version 5.8.8+1 of unified_analytics[^1]. [The relevant code](https://github.com/dart-lang/tools/blob/unified_analytics-v5.8.8/pkgs/unified_analytics/lib/src/log_handler.dart#L280-L299). The crash happens at L285:

```dart
    var records = logFile.readAsLinesSync();
```
Given that this read tried to allocate >9GB, I assume then that this log file somehow reached ~9GB in size. This is surprising, because we limit the number of event payloads we keep saved to `kLogFileLength` (2000). From here, I hypothesize that one or more payloads that got logged were _massive_.

This almost certainly means that we have a bug somewhere (either in unified_analytics, but more likely the flutter tool). I can't imagine any legitimate reason for a payload being somewhere between somewhere between 9GB/2000=4.5MB and 9GB in size. **Another reason this is troubling is that we are potentially wasting a significant amount of the user's network bandwidth[^2].**

Focusing back on the issue on allocating 9GB. I/@christopherfujino  see two ways forward:

1. Patch unified_analtyics (v5 and v6) to stop this logging completely.
2. Rework the troublesome code to more robustly guard against massive payloads. Just as one example, instead of constraining the file using number of payloads logged, we could discard any payload (new or existing) that exceeds 1kB. In this case I would also recommend patching this code to catch and discard any `FileSystemException` encountered—the risk of such an exception is completely opaque to callers, and logging these payloads is not important enough to warrant crashing callers. This was already patched into v6 with 6.1.1, but we should probably do this for v5 as well and get this hotfixed into the stable flutter release.

[^1]: https://github.com/flutter/flutter/blob/27dfff1c8601594113540034e08a47d7488b37f7/packages/flutter_tools/pubspec.yaml#L55

[^2]: Maybe we should file another issue on this? Either the tool should add guards that make sure we aren't sending massive payloads, or we could make the `Analytics` class (from unified_analtyics) configurable with a means to guard against this. Opinions, @christopherfujino ?

**Comment by andrewkolos** [comment]
> 2\. Maybe we should file another issue on this? Either the tool should add guards that make sure we aren't sending massive payloads, or we could make the `Analytics` class (from unified_analtyics) configurable with a means to guard against this. Opinions, @christopherfujino ? [↩](#user-content-fnref-2-b1f2b6ccbad6f75eb3c740015c390d17)

I talked with @christopherfujino briefly (this is still going to be discussed more next week). He agreed that we should do _something_ about sending massive payloads. Perhaps we should still send these (to avoid events "disappearing" in a confusing way), but we should send a separate analytics event when this happens. We can then then triage these events independently. It's also entirely possible that we can already query our analytics directly for massive payloads and troubleshoot from there, but this is something we would need to investigate.

**Comment by christopherfujino** [comment]
This was fixed upstream in: https://github.com/dart-lang/tools/pull/277

Rolled to the Flutter SDK on the master channel in https://github.com/flutter/flutter/pull/150827/files#diff-a3d4dfa7e9543c501bc1aee57d5502b657d6f5469c09fb42b8c9d516ec53df66R55
