### ISSUE TITLE
[gen-l10n] Arb file placeholders types & format not taken into account for generated files

### ISSUE THREAD

**Issue by Schtroumphy** [flutter/flutter#150105]
### Steps to reproduce

1. Configure l10n by adding packages
2. Create arb file with  a key having placeholders with a formatted DateTime 
3. Check the l10n.dart file generated

### Expected results

Has this generated file for Flutter 3.13.5 with intl v0.18.0 : 
<img width="617" alt="image" src="https://github.com/flutter/flutter/assets/42738178/a0845e2b-a0e3-4c2c-8ef9-eb545ed15b61">

### Actual results

The result with Flutter 3.22.2 and intl v0.19.0 : 
<img width="457" alt="image" src="https://github.com/flutter/flutter/assets/42738178/67884a71-d86c-4cf7-a55b-95466c945c8a">

### Code sample

<details open><summary>Code sample</summary>

```arb
"lastSynchronization": "Last sync: {date} at {time}",
"@lastSynchronization": {
    "placeholders": {
        "date": {
            "type": "DateTime",
            "format": "yMd"
        },
        "time": {
            "type": "DateTime",
            "format": "Hms"
        }
    }
},
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
$ dart run lokalise_flutter_sdk:gen-lok-l10n
Building package executable... 
Built lokalise_flutter_sdk:gen-lok-l10n.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4 23E214 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @Schtroumphy 
My `intl` version is the same but I see a different output:

```dart
@override
String lastSynchronization({required DateTime date, required DateTime time}) {
  final intl.DateFormat dateDateFormat = intl.DateFormat.yMd(localeName);
  final String dateString = dateDateFormat.format(date);
  final intl.DateFormat timeDateFormat = intl.DateFormat.Hms(localeName);
  final String timeString = timeDateFormat.format(time);

  return 'Last sync: $dateString at $timeString';
}
```

I only use `flutter gen-l10n` as usual. I'm unsure how your CLI `lokalise_flutter_sdk:gen-lok-l10n` works. Can you try `flutter gen-l10n` to see if it works?

**Comment by Schtroumphy** [comment]
Yeah ! I tried with `flutter gen-l10n` too and i have the same problem :/

**Comment by huycozy** [comment]
Could you please share a minimal sample project in a GitHub repository, so I can clone and try on my end? (please add license the code in the repository under some open-source license (e.g. MIT, Apache, BSD, GPL) so that we may look into it, thanks)

**Comment by Schtroumphy** [comment]
You can fin a sample project there with just the initialization of localisation : https://github.com/Schtroumphy/issue_intl

**Comment by Schtroumphy** [comment]
> Could you please share a minimal sample project in a GitHub repository, so I can clone and try on my end? (please add license the code in the repository under some open-source license (e.g. MIT, Apache, BSD, GPL) so that we may look into it, thanks)


You can fin a sample project there with just the initialization of localisation : https://github.com/Schtroumphy/issue_intl

**Comment by huycozy** [comment]
I see you have this on `pubspec.yaml`:

```yaml
flutter_intl:
  enabled: true
```

This seems to cause an error when generating strings with a file `intl_en.arb` with `{}` only:

```console
Multiple arb files with the same 'en' locale detected. 
Ensure that there is exactly one arb file for each locale.
```

Not sure where you get this but it doesn't exist in Flutter docs: https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization

After I remove `flutter_intl` from `pubspec.yaml` file, I can generate strings as expected. 

Another issue on your sample project is that: your placeholders string doesn't match your string message, for eg:

```arb
"fromStartYMMD": "From {date}",
"@fromRouteStart": {
  "placeholders": {
    "date": {
      "format": "yMMMd",
      "type": "DateTime"
    }
  }
}
```

`fromStartYMMD` is different than `fromRouteStart`. That's the reason why your generated parameter type is `Object`. 

After modifying it, I see the generated method is correct with `DateTime` type on parameter:

```dart
@override
String fromStartYMMD({required DateTime date}) {
  final intl.DateFormat dateDateFormat = intl.DateFormat.yMMMd(localeName);
  final String dateString = dateDateFormat.format(date);

  return 'From $dateString';
}
```

Since this is an implementation issue, I will close this as solved. If you still think this is a Flutter bug, please write in comments.
