### ISSUE TITLE
Video Player progress downloading (download only part of the video provided in the network which is enough to play a few seconds from it). while playing these seconds I want to initialize the rest of the video 

### ISSUE THREAD

**Issue by Manhal1994** [flutter/flutter#150172]
### Use case

I have a ListView with video players. I want to have a better user experience and less delay time when I do not have to download the entire video only the initialized part. Currently, the initialize method is void (videoPlayerController!.initialize()) and returns no data.

### Proposal

`Future<Uint8List> initialize(){ // -------------- }
`

**Comment by darshankawar** [comment]
@Manhal1994 
See if [this](https://github.com/flutter/flutter/issues/126760) helps in your case or not. 

https://github.com/flutter/flutter/issues/126760#issuecomment-1643407157
