### ISSUE TITLE
Adapt flutter tools to handle pub workspaces:

### ISSUE THREAD

**Issue by sigurdm** [flutter/flutter#150196]
With introduction of pub workspaces https://github.com/dart-lang/pub/issues/4127
[flutter.dev/go/pub-workspace](http://flutter.dev/go/pub-workspace)

One known issue is that .package_config is not always located relative to the apps pubspec.yaml, but can be located in a parent directory:

https://github.com/flutter/flutter/blob/7b6d667701e38c1d9d700e2bcc29bc7a06598c59/packages/flutter_tools/lib/src/dart/pub.dart#L653

**Comment by xvrh** [comment]
Hi, I'm trying the pub workspace feature in the flutter beta channel. It's working great. 

But I'm blocked with this error in one of my tool:
`pub did not create .dart_tools/package_config.json file`

Any workaround?

**Comment by pattobrien** [comment]
> Hi, I'm trying the pub workspace feature in the flutter beta channel. It's working great.
> 
> But I'm blocked with this error in one of my tool: `pub did not create .dart_tools/package_config.json file`
> 
> Any workaround?

Do you know which tool is causing the error? 

If it's build/build_runner, there's an issue that should be fixed in the next release (see: https://github.com/dart-lang/build/issues/3726#issuecomment-2250883531).

**Comment by xvrh** [comment]
@pattobrien it's simply `flutter pub get` and `flutter build web` when I run the command in a sub directory.

The full error message is: `LocalDirectory: '/Users/xavier/projects/xxx': pub did not create .dart_tools/package_config.json file.`

**Comment by sigurdm** [comment]
No workaround currently - the attached PR is supposed to fix this. You could try checking it out. There are still a few tests failing - but it should mostly be working
