### ISSUE TITLE
can't run the app

### ISSUE THREAD

**Issue by mazab99** [flutter/flutter#150106]
```
"ar": 4 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
"ar": 4 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Note: /Users/mahmoudazab/.pub-cache/hosted/pub.dev/flutter_windowmanager-0.2.0/android/src/main/java/io/adaptant/labs/flutter_windowmanager/FlutterWindowManagerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/mahmoudazab/.pub-cache/hosted/pub.dev/uni_links2-0.6.0+2/android/src/main/java/name/avioli/unilinks/UniLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/mahmoudazab/.pub-cache/hosted/pub.dev/vibration-1.9.0/android/src/main/java/com/benjaminabel/vibration/VibrationPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /Users/mahmoudazab/.gradle/caches/transforms-3/250072cd9c4bf7fcb8d10d924776994b/transformed/jetified-kotlin-stdlib-1.9.24.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/mahmoudazab/.gradle/caches/transforms-3/250072cd9c4bf7fcb8d10d924776994b/transformed/jetified-kotlin-stdlib-1.9.24.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
e: /Users/mahmoudazab/.gradle/caches/transforms-3/250072cd9c4bf7fcb8d10d924776994b/transformed/jetified-kotlin-stdlib-1.9.24.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 22s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /Volumes/D/Programming/My Work/Flutter Apps/HighQ Apps/1 - Clean                    │
│ Arch/jalisa_user/android/build.gradle:                                                     │
│ ext.kotlin_version = '<latest-version>'                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────┘
Error: Gradle task assembleDebug failed with exit code 1
```

**Comment by mazab99** [comment]
name: jalisa_user
description: "Jalisa user"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  flutter_app_badger: ^1.5.0
  flutter_timezone: ^1.0.8
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  map_location_picker: ^1.2.8+3
  flutter_polyline_points: ^2.0.0
  flutter_windowmanager: ^0.2.0
  uni_links2: ^0.6.0+2


  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  dio: ^5.4.3+1
  http: ^1.2.1
  http_parser: ^4.0.2
  equatable: ^2.0.5
  get_it: ^7.7.0
  dartz: ^0.10.1
  collection: ^1.18.0
  path: ^1.9.0
  rxdart: ^0.27.7
  path_provider: ^2.1.3

  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  image: ^4.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  file_picker: ^8.0.5


  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.6
  stream_transform: ^2.1.0


  animate_do: ^3.3.4
  flutter_animate: ^4.5.0
  flutter_active_loaders: ^7.4.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11


  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0
  fluttertoast: ^8.2.6
  expansion_widget: ^0.1.0
  flutter_widget_from_html: ^0.15.1


  android_id: ^0.4.0
  layout: ^1.0.5
  amplitude_flutter: ^3.16.2

  overlay_support: ^2.1.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.2
  x_validation: ^3.2.0
  cron: ^0.6.0
  vibration: ^1.9.0
  pdf: ^3.10.8
  screenshot: ^3.0.0


  intl_phone_field: ^3.2.0
  high_q_paginated_drop_down: ^2.0.2
  dotted_border: ^2.1.0














flutter_native_splash:
  image: assets/images/base/splash_screen.png
  background_image: assets/images/base/splash_back.png
  image_dark: assets/images/base/splash_screen.png
  background_image_dark: assets/images/base/splash_back.png
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.2.0
  build_runner: ^2.4.11



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/base/app_store_4.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/
    - assets/images/base/
    - assets/images/test/
    - assets/lottie/
    - assets/maps/google_maps_mode.json



  fonts:
    - family: TajawalBlack900
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          style: normal
          weight: 900

    - family: TajawalBold700
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
          style: normal
          weight: 700

    - family: TajawalExtraBold800
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          style: normal
          weight: 800

    - family: TajawalExtraLight200
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          style: normal
          weight: 200

    - family: TajawalLight300
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
          style: normal
          weight: 300

    - family: TajawalMedium500
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
          style: normal
          weight: 500

    - family: TajawalRegular400
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          style: normal
          weight: 400

    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

**Comment by mazab99** [comment]
buildscript {
    ext.kotlin_version = '1.9.24'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by mazab99** [comment]
plugins {
    id "com.android.application"
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
    // START: FlutterFire Configuration
    id 'com.google.gms.google-services'
    // END: FlutterFire Configuration
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "sfhdsjhfgjdgfjf"
    compileSdkVersion 34
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "sshgfhgfhghgfhr"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:33.1.0')
    implementation 'com.android.support:multidex:1.0.3'
}

**Comment by danagbemava-nc** [comment]
Hi @mazab99, you appear to be the using the imperative gradle syntax, can you upgrade to the declarative syntax by following  https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply to see if it helps?

PS: in the future, kindly fill the template provided instead of leaving several different comments.

**Comment by mazab99** [comment]
@danagbemava-nc 
still same issue

it was  works before 1 hour , suddenly I can't run it

**Comment by danagbemava-nc** [comment]
Hi @mazab99, did you make any modifications prior to you experiencing the issue? Please also share the full output of `flutter run -v`. The output may be huge so kindly put it into a .txt file and attach it here. Please also share the output of `flutter doctor -v`

Thank you
