### ISSUE TITLE
Issue from website page Flutter for React Native Developers

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#15013]
From URL: https://flutter.io/flutter-for-react-native.md

On my mobile (Moto X Play, Android 6.0.1, Chrome) the left edge of the page is offscreen and I can scroll to the side to get to it:

![screenshot_20180301-072355](https://user-images.githubusercontent.com/1078012/36831977-afce4bb8-1d21-11e8-8105-acba688ecbde.png)

**Comment by cbracken** [comment]
Closing as dupe of #15005
