### ISSUE TITLE
When writing Flutter code in VSCode, there is no automatic indentation when breaking lines within the brackets {}

### ISSUE THREAD

**Issue by 826327700** [flutter/flutter#150158]
### Steps to reproduce

vscode v1.90.0
dart extension v3.90.0
flutter extension v3.90.0

### Actual results

flutter:

https://github.com/flutter/flutter/assets/23014381/b11e6667-dd67-4f9e-88ea-a352db93b0d4

javascript:

https://github.com/flutter/flutter/assets/23014381/2e2e55c3-6797-484d-ab38-2a664d10cb7f

This is really frustrating and significantly affects my coding efficiency. Can anyone tell me how to solve this problem?

### Flutter Doctor output

flutter doctor -v
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 14.4.1 23E224 darwin-arm64,
    locale zh-Hans-CN)
    • Flutter version 3.23.0-0.1.pre on channel beta at /Users/xiaobaozi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (7 days ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/xiaobaozi/Library/Android/sdk
      but Android SDK not found at this location.

[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To update CocoaPods, see
      https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)            
    • iPhone 15 Pro (mobile)          • 95377193-8FAB-4A6D-8C21-59346014C776 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   •
      macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         •
      macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript •
      Google Chrome 125.0.6422.144
    ! Error: Browsing on the local area network for 小包子的iPhone. Ensure the device is unlocked
      and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

**Comment by danagbemava-nc** [comment]
Any issues you face using the vscode extension should be reported on its repo. https://github.com/Dart-Code/Dart-Code/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Closing from here. 

Please check for duplicates before you file an issue on the repo. 

Thank you
