### ISSUE TITLE
number keyboard doesn't work in TextField after update flutter to 3.22

### ISSUE THREAD

**Issue by rafaelbenedetti1** [flutter/flutter#150191]
### Steps to reproduce

1. Create a new flutter project using v3.22
2. Create a Simple TextField
3. Try digit a number using number keyboard (numpad)
4. The keys which contains arrow (four, six, eight, two) isn't working and moves cursor

### Expected results

I want to digit numbers using numpad

### Actual results

When i try digit a four, six, eight, four and two, this keys moves cursor in a textfield,

### Code sample

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(),
        ),
      ),
    );
  }
}

### Screenshots or Video

https://github.com/flutter/flutter/assets/86314804/6da6b318-72ad-4229-a683-dd589ed3b365

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run
flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on
    Linux Mint 19.3 5.4.0-150-generic,
    locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices
    (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1.)
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by LimaneGaya** [comment]
This should have been fixed with #148988

**Comment by huycozy** [comment]
This is similar to https://github.com/flutter/flutter/issues/148447 and should be fixed on master channel (see https://github.com/flutter/flutter/pull/148988). You can switch to master channel and retry:

```
flutter channel master
flutter upgrade
```

I will close this as fixed. If you still experience this on master channel, please write in comments and I will reopen this.

**Comment by rafaelbenedetti1** [comment]
Ok, Thank you @huycozy
