### ISSUE TITLE
[rfw] It's possible to copy to clipboard using rfw?

### ISSUE THREAD

**Issue by johandavidcm** [flutter/flutter#150146]
### Use case

HI!

I have this code snippet in a `.rfwtxt` file, and I would like to be able to copy a string to the clipboard when I tap the button. Is it possible to do this using the rfw package?

I'm using 

Flutter: 3.22.2
rfw: ^1.0.29

### Proposal

```
ElevatedButton(
  child: Text(text: 'Copy to clipboard'),
  onPressed: event "copy_to_clipboard" { },
)
```

**Comment by huycozy** [comment]
Have you tried implementing it? Does it have any errors? Can you share a complete sample code with error stack trace if any?

**Comment by johandavidcm** [comment]
Yes it works using the param value `onEvent` on RemoteWidget class, but I have other question, I don't know if can u help here o should I create another issue, the question is: Can I modify the background color on ElevatedButton from `createMaterialWidgets`

I have this:
```

ElevatedButton(
  style: {
    backgroundColor: 0xFF34007F
  },
  child: Text(text: 'Copy to clipboard'),
  onPressed: event "copy_to_clipboard" { },
)
```

But I would like to modify the background color but when I tried using the style property has no effect on component and has no errors

**Comment by huycozy** [comment]
>But I would like to modify the background color but when I tried using the style property has no effect on component and has no errors

This looks like a feature request as I see `ElevatedButton` hasn't passed `style` attribute yet: https://github.com/flutter/packages/blob/dd04ab1c75cdd376312eb11a31c52273d918dbe0/packages/rfw/lib/src/flutter/material_widgets.dart#L305-L314

Please open a new issue for that.

Since the original issue is solved, I will close this.
