### ISSUE TITLE
[iOS][camera]Rare PlatformException Occurs When Closing Modal Before Camera Initialization Completes

### ISSUE THREAD

**Issue by kiga-9071** [flutter/flutter#150163]
### Steps to reproduce

1. Launch a modal to embed the camera preview.
2. Start the camera initialization process when the modal is displayed.
3. Close the modal while the camera preview is still showing a black screen.

### Expected results

PlatformException should no longer occur.

### Actual results

- PlatformException occurs when the dispose process of the camera controller is called twice in quick succession.
- It is not possible to catch the exception that occurs during the dispose process.
- It occurs only on iOS, with a frequency of approximately once every 30 attempts.
- This has not occurred in Androd.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
15:41:56.336610+0900 flutter: LogLevel.ALL 2024-05-14 15:41:56.335531 [isolate_instructions: 106af2340, vm_instructions: 106ae8000] PlatformException(error, No active stream to cancel, null, null) Flutter Runner
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4.1 23E224 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for iPhone 12mini. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @kiga-9071 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thanks!

**Comment by kiga-9071** [comment]
@huycozy 
I'm getting ready, so please wait. I'm sorry.
