### ISSUE TITLE
[in_app_purchase]  how to get the subscription price that subscribed by user.

### ISSUE THREAD

**Issue by sumitagadhvi** [flutter/flutter#150165]
### Use case

I have implemented [in_app _purchase](https://pub.dev/packages/in_app_purchase) in my Flutter app with an auto-renewable subscription priced at 199. Some users have purchased this plan. After that, I changed the price of the plan to 250. I have display the price directly from Play Store or App Store's purchase details. Now, even for users who purchased the plan at the previous price, it is displaying the current price. I want to show the price at which the user have purchased the plan.

### Proposal

`_productsShow[index].price`
with the help of this code i am showing the price.

**Comment by darshankawar** [comment]
@sumitagadhvi 
Your case seems to be similar to https://github.com/flutter/flutter/issues/139718. Most likely you will need to check if the data is coming from the store or not. If not, then it won't be actionable from plugin's side. If indeed from plugin side, then it will be worth looking into the plugin code. 

I'll close this as a duplicate. You may share your findings in that issue for better tracking. If you disagree, write in comments and I'll reopen it.
