### ISSUE TITLE
Image picker tests `testPickingFromGallery`, `testPickingWithContraintsFromGallery`, and `testSelectingFromGallery` failed on iOS 18 beta 1

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#150220]
### Steps to reproduce

*Steps to Reproduce:

1. Install XCode 16.0 Beta 1 and iOS 18.0 Simulator.
2. Clone the Flutter packages repository: git clone https://github.com/flutter/packages
3. Open the example iOS directory on XCode: packages/image_picker/image_picker_ios/example/ios
4. Select Flutter master version (3.23.0-13.0.pre.188) or stable (3.22.2)
5. Run the tests using the XCode test view and selecting some simulator with iOS 18.0

![image](https://github.com/flutter/flutter/assets/54465214/b5530255-dcde-4163-97f7-0c2135706cc6)

### Expected results

The mentioned tests were previously succeeding. Please note that we are currently testing with Xcode 16 Beta 1, which includes the iOS 18 simulator, and this might be breaking the tests.

### Actual results

The following test case fails: 

![image](https://github.com/flutter/flutter/assets/54465214/b5530255-dcde-4163-97f7-0c2135706cc6)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
testPickingFromGallery: failed - Failed due to not able to find an image with 30 seconds
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-UY)
    • Flutter version 3.22.2 on channel stable at /Users/qa/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
    • Android SDK at /Users/qa/Library/Android/sdk
    • Platform android-34, build-tools 35.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.87.2)
    • VS Code at /Users/qa/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0
```

</details>

**Comment by jmagman** [comment]
I was able to reproduce this, here's the xcresult (larger than GitHub's 25MB upload limit): https://drive.google.com/file/d/1Jf_XBCF1Rx7iqA16ZaIqvktplFtot1Bh/view?usp=sharing

@rzambroni these reports would be most helpful if the detailed test failures/screenshots/device recordings are included.

Unfortunately I don't know how to export the Test Report in Xcode's UI, but from the command line you can run this (swap `iPhone 15 Pro` with whatever simulator you're using:

```
$ cd packages/image_picker/image_picker_ios/example/
$ flutter build ios --config-only
$ xcodebuild test -workspace ios/Runner.xcworkspace -scheme Runner -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' -resultBundlePath test/
```
And then you can zip up `test.xcresult` and attach to the issues.

**Comment by jmagman** [comment]
Looks like the app hierarchy for the picker changed, will need to update the expectations.
