### ISSUE TITLE
Add support for pre-publish hooks for publishing first party Flutter packages

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#150210]
**Background**
A DevTools extension for `package:shared_preferences` is being added in https://github.com/flutter/packages/pull/6749. The pre-built Flutter web assets of this DevTools extension must be included in the `shared_preferences` package prior to publishing. However, [we do not want](https://github.com/flutter/packages/pull/6749#discussion_r1608428247) an uncontrolled machine to build the extension and check in the output, which means [we need a way](https://github.com/flutter/packages/pull/6749#issuecomment-2122973326) for this to be done on a controlled machine as a pre-publish step.

**Feature request**
Add support for a pre-publish hook so that we can support use cases like the one described above. Upon publishing the `shared_preferences` package, the pre-publish hook would run and build the `shared_preferences` DevTools extension when needed.

@stuartmorgan please feel free to add any context I may have missed or add suggestions on how you believe this should be implemented.

**Comment by stuartmorgan** [comment]
@jonasfj FYI, related to our discussion earlier today about extension builds. I'm curious what you think the right long-term solution to this problem is from a supply chain validation standpoint is. I'm moving forward with this for now since "build on CI" > "build on random individual's machine", but ideally we'll want a good solution for this longer term (not just for this package, but for the ecosystem as a whole).

**Comment by jonasfj** [comment]
Long term I think the right solution is: https://github.com/dart-lang/pub/issues/4058

Maybe not doing all of them, but perhaps `dart pub publish` should invoke `hook/publish.dart` before publishing.

From SLSA perspective, it might limit the levels attainable. There is probably more stuff we need to understand.

-------------

Currently, I have packages where I use `tool/publish.dart` to publish, and then this script wraps `dart pub publish`.

I also have packages where I exclusively use automated publishing, and where I configure Github Actions to run a command prior to publishing. I'm guess that's kind of what you're doing in https://github.com/flutter/packages/pull/7156
