### ISSUE TITLE
[android][platform view]investigate whether android has similar performance issue due to 1 px overlay

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#150211]
Follow up from the presentation: we should investigate if the same applies to Android, since we are seeing pretty big perf improvement on iOS with this fix. (Corresponding iOS ticket: https://github.com/flutter/flutter/issues/143420)

Not sure about web though, since web doesn't share the same engine, but may worth checking if the same applies to web. 

cc @yjbanov @reidbaker

**Comment by jonahwilliams** [comment]
RIght now we're mostly using texture layer hybrid composition. This is rendered via Flutter's engine, so there are no computed overlays.

We may switch rendering strategies that would make this an issue in the future.

**Comment by gmackall** [comment]
From Android triage: Are you confident enough that we can close this bug? Also cc @johnmccutchan because you are working on a new platform view implementation

**Comment by hellohuanlin** [comment]
Discussed with @jonahwilliams today - for now this is not an issue because android use hybrid composition. But it could be an issue when android switch to something similar to iOS. I think it's fair to close it for now and re-open if needed.
