### ISSUE TITLE
Add a link URI property to SemanticsProperties

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#150263]
At the moment, semantics nodes can be links using the [`SemanticsProperties.link`](https://api.flutter.dev/flutter/semantics/SemanticsProperties/link.html) property. But there's no way to specify the URI of the link.

Let's add a new `SemanticsProperties.linkUri` property of type `Uri`.

**Comment by jonahwilliams** [comment]
Consider just using a string if you don't want the validation.
