### ISSUE TITLE
[Impeller] disrespecting the ctm in mask blurs results in different results depending on dpi

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#150272]
## reproduction
See `DlGoldenTest.TextBlurMaskFilterDisrespectCTM` introduced in https://github.com/flutter/engine/pull/53377

### high dpi (2x)
<img width="779" alt="Screenshot 2024-06-14 at 9 17 24 AM" src="https://github.com/flutter/flutter/assets/30870216/fc28491b-f862-4b3b-aff5-82ed780de9a8">

### low dpi (1x)
<img width="916" alt="Screenshot 2024-06-14 at 10 40 10 AM" src="https://github.com/flutter/flutter/assets/30870216/54d9880e-f92c-4bc0-8234-265035a54457">
 dpi (1x)

## expected results
I'd expect the results to render the same regardless of dpi.  I think that means disrespecting the ctm should take into effect the content scalar.

## flutter reproduction code

Alternatively, run this code on iPhone Xs and iPhone SE and compare results.

<details>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Transform.scale(
              scale: 1.0,
              child: const Text(
                'Crazy shadows',
                style: TextStyle(
                  fontFamily: "Inter",
                  fontWeight: FontWeight.w700,
                  fontSize: 34,
                  color: Colors.white,
                  letterSpacing: -1,
                  shadows: <Shadow>[
                    Shadow(
                      offset: Offset(1.0, 1.0),
                      blurRadius: 23.0,
                      color: Color.fromARGB(255, 234, 25, 25),
                    ),
                    Shadow(
                      offset: Offset(1.0, 1.0),
                      blurRadius: 2.0,
                      color: Color.fromRGBO(0, 0, 0, 0),
                    ),
                  ],
                ),
              ),
            ),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

cc @bdero

**Comment by bdero** [comment]
Is this reproducible in a Flutter app?

When writing the `respect_ctm` solution, I tried dragging the window between my low DPI monitor and retina display on macOS and the blur looked the same.
My assumption is that either SkParagraph or something in the Flutter Framework is scaling up the blur sigma based on the DPI before it gets pushed to the DisplayList.

**Comment by gaaclarke** [comment]
> Is this reproducible in a Flutter app?

I expect it will be a problem when executing on iOS devices that have scalars bigger than 2x.  The results won't look the same across devices.  I don't think 1x will ever show up on any of the devices we ship for though.

**Comment by gaaclarke** [comment]
It looks fine on the simulator.  I'm not sure why this would be different for the golden tests, but it seems like thats the case.

| 2x | 3x |
|--|--|
| <img width="441" alt="Screenshot 2024-06-14 at 2 27 02 PM" src="https://github.com/flutter/flutter/assets/30870216/85f492be-2acd-4c92-9fbe-e6e4331d9847"> | <img width="442" alt="Screenshot 2024-06-14 at 2 25 52 PM" src="https://github.com/flutter/flutter/assets/30870216/5c29e4f3-41f7-4cec-8a12-d713a79c0f50">|

**Comment by bdero** [comment]
So the whole "shadow" drawing thing is a material design-ism that has a complicated mapping to blurs. Path "shadows" are drawn with the DisplayList via `drawShadow`, which takes a device pixel ratio as a parameter that we ourselves apply -- I added a conversion utility in Impeller's DL dispatcher that does what Skia's internal utility does for the penumbra.

However, Skia has no such utility for the drawText case. It's computing the correct mask blur for the shadow penumbra somewhere else in the codebase and pushing it to DisplayList as a mask blur with `respect_ctm` disabled.

I'm looking into this at the moment so we can hopefully document it better. The device pixel ratio comes from the embedder via engine window metrics.

**Comment by gaaclarke** [comment]
Actually, if you zoom in you can clearly see a difference.  2x on the left, 3x on the right.  So that matches the same sort of behavior we are seeing at 1x on the golden tests.

<img width="865" alt="Screenshot 2024-06-14 at 2 47 14 PM" src="https://github.com/flutter/flutter/assets/30870216/380fdcad-7597-40a2-b8e2-9dd3d23903fd">

**Comment by gaaclarke** [comment]
I double checked the behavior of skia and it exhibits the same behavior:

<img width="1066" alt="Screenshot 2024-06-14 at 3 13 26 PM" src="https://github.com/flutter/flutter/assets/30870216/f4e3c471-68d2-4600-8b54-18369a1b406e">

**Comment by bdero** [comment]
Nice findings. I followed the shadows from when they're recorded on the Dart up to where SkParagraph creates the Mask blur and didn't find any DPR. Also verified the actual Sigma I'm receiving isn't changing between my displays.

I think we should consider this a bug in `DisplayListParagraphBuilder::drawTextShadow`. It chooses to set `respect_ctm=false` but it isn't computing the material design shadow penumbra correctly (which takes the DPR as a parameter elsewhere).

* [`DisplayListParagraphBuilder::drawTextShadow`](https://github.com/flutter/engine/blob/7f8033ffa7211e951ed69dc572796c44e9263fbe/third_party/txt/src/skia/paragraph_skia.cc#L122-L125) (drawing text shadows wrong)
* [`DlDispatcherBase::drawShadow`](https://github.com/flutter/engine/blob/e059e42031dc2410456b3f39c5118b13878311cd/impeller/display_list/dl_dispatcher.cc#L1144-L1148) (drawing path shadows right -- note that the DPR is multiplied into `occluder_z` here)

**Comment by bdero** [comment]
I looked into this further, and given that `drawTextShadow` is setting `respect_ctm=false` and there isn't anything else in the codebase scaling up/down text shadow properties based on the CTM, I think _all_ scaling is getting completely ignored, not just the DPR.

And so I'm pretty sure this is the same issue as: https://github.com/flutter/flutter/issues/123596
And the `respect_ctm` puzzle is already covered by this issue: https://github.com/flutter/flutter/issues/115112

Going to close this out and consolidate discussion on the other issues covering this.
