### ISSUE TITLE
The iOS App crashes after entering the foreground card screen from the background

### ISSUE THREAD

**Issue by wahkim** [flutter/flutter#150244]
### Steps to reproduce

Background to foreground

### Expected results

Normal start

### Actual results

Crash after stuck screen

### Code sample

<details open><summary>Code sample</summary>

Crash logs caught by the tool:
![5555](https://github.com/flutter/flutter/assets/33590201/3f3d5000-7a01-4c0d-a494-a53b13bb1570)

```dart


#0 Thread
NotSmoothFrameException
There are some notsmooth frames in the main thread
解析原始
0
libsystem_kernel.dylib
_semaphore_wait_trap + 8

4
UIKitCore
-[_UIConcretePasteboard string] + 92
5
Flutter
0x0000000104a04000 + 140952
6
Flutter
0x0000000104a04000 + 137348
7
Flutter
InternalFlutterGpu_Texture_AsImage + 6316
8
Flutter
0x0000000104a04000 + 277816
9
libdispatch.dylib
__dispatch_call_block_and_release + 32

18
UIKitCore
_UIApplicationMain + 340
19
Runner
0x0000000100ca0000 + 95368
20
dyld
0x00000001c227d000 + 249420
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 13.6.1 22G313 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (3 available)
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @wahkim, what device(s) are you seeing this issue on? What version of iOS are they running? Are you able to reproduce the issue locally? 

Can you provide a complete minimal reproducible code sample so that we can properly investigate this issue? 

Thank you

**Comment by danagbemava-nc** [comment]
Hi @wahkim, do you perform any computations when the app goes into the background? When it occurs, is the app running any computation before the app is backgrounded?

**Comment by wahkim** [comment]
> Hi @wahkim, do you perform any computations when the app goes into the background? When it occurs, is the app running any heavy computation before the app is backgrounded?

While retreating into the background, I performed database update operations and maintained the webSocket heartbeat.
After re-entering the foreground, the database update operation is also performed, and the persistent connection is re-established if the webSocket is disconnected.

**Comment by danagbemava-nc** [comment]
Hi @wahkim, are these operations "heavy" operations, i.e, are they resource intensive operations? Do they block the main thread? In the times that this occurred, do you know if the app was in a long usage session and heavy on resource consumption?
