### ISSUE TITLE
Credentials auto-fill doesn't work when tapping the hint button on iOS keyboard, but works from passwords popup

### ISSUE THREAD

**Issue by tbuczkowski** [flutter/flutter#150252]
### Steps to reproduce

1. Create a login form contained within the `AutofillGroup` widget, where both email and password TextFields have proper `autofillHints` set.
2. Create proper webcredentials setup in Xcode and host the `apple-app-site-association` on your domain.
3. Launch the app and use the form - the "save credentials" system popup appears correctly.
4. Use the form again, an auto-fill hint should appear over the keyboard.
5. Tap the hint - nothing happens.
6. Tap the key button next to the hint, and pick a credential from the saved passwords popup.
7. The form populates correctly.

### Expected results

The form should populate both when tapping the over-the-keyboard hint as well as from the passwords popup.

### Actual results

Please refer to the video below.

This bug must have been introduced somewhere between the 3.19.2 and 3.22.2 versions of Flutter, because it only started appearing in my project after I upgraded Flutter. iOS version: 17.5.1

### Code sample

<details open><summary>Code sample</summary>

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/95422352/f892a13a-eaaf-472f-b139-9f8c66da8f82

</details>

### Logs

<details open><summary>Logs</summary>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (6 available)            
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @tbuczkowski 
Can you check if [this](https://github.com/flutter/flutter/issues/148475) issue resembles your case or not ?

**Comment by tbuczkowski** [comment]
Yes, that seems to be the case - I somehow missed that one. I'm closing this issue then.
