### ISSUE TITLE
Unit of measurement in flutter

### ISSUE THREAD

**Issue by gesho** [flutter/flutter#150259]
### Steps to reproduce

run MediaQuery on Android and iOS devices

### Expected results

expected `160 dp = 1 inch` uniformly accross devices and resolution

### Actual results

against Android (Pixel 7 emu) `160 dp = 1 inch`
against iOS `132 dp = 1 inch`

tested on 
iPad sim 10th gen [specs](https://www.apple.com/ipad-10.9/specs/) (2360 x 1640, 264ppi, 8.93 x 6.21 inch) and
 iPad Pro 1st gen hardware in debug mode

given iPad ppi 264, `devicePixelRatio = 2` results in  `132 dp = 1 inch`

### Code sample

<details open><summary>Code sample</summary>

```dart
MediaQuery.of(context)
print($query)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![dpi](https://github.com/flutter/flutter/assets/5515956/473c199c-42d6-4aa9-b94f-e9e38a7410f4)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.90.1)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for RoadRunner’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @gesho 
Please check this old issue https://github.com/flutter/flutter/issues/25833 and maybe this as well https://github.com/flutter/flutter/issues/32115 to see if they help in your case or not.

**Comment by gesho** [comment]
@darshankawar thx for responding, however I believe prev issues and present one are different. 

present issues is about:
- flutter measurements not translating into same physical length on Android vs iOS
- current documentation 
  - not defining flutter unit of measurement
  - guarantee the same physical rendering across platforms

**Comment by darshankawar** [comment]
Thanks for the update. Keeping the issue open and labeling for team's tracking / attention.

**Comment by goderbauer** [comment]
@gesho Could you clarify what this issue is about? Where are you getting the `dp` measurement from? As far as I know, Flutter doesn't expose that.

The best definition we have on logical and physical pixel is on https://main-api.flutter.dev/flutter/dart-ui/FlutterView/devicePixelRatio.html.

**Comment by gesho** [comment]
@goderbauer 
on iPad pro 1st gen, with [specs](https://support.apple.com/en-us/111974), `2388 x 1668` with ppi `264`
MediaQuery reports:
`1194 x 834`, dpRatio `2.0`
that's `132 dp = 1 inch`

on pixel 7 emulator resolution `2400 x 1080` ppi `416`
MediaQuery reports
`890.28 x 411.42`, dpRatio `2.625`
that's just about `160 dp = 1 inch` (consistent with Material docs [definition](https://m2.material.io/design/layout/pixel-density.html#pixel-density-on-android) of density independent pixels)

on Samsung note 8 with [spec](https://www.samsung.com/us/business/support/owners/product/galaxy-note8-sprint/) running under various resolutions, eg under `2960 x 1440` ppi `521`
MediaQuery reports 
`797.71 x 411.42` dpRatio `3.5`
that (calculated from ppi or width, height is a bit off) is `148 dp = 1 inch`

say `SizedBox 200 x 200` on iPad pro 1st gen ends up a little over 1.5 inch, whereas on Samsung Galaxy Note 8 it's about 1 5/16 inch. they are not the same physical size. 

is this variable (160/148/132) dp to inch ratio an expected behavior?

**Comment by goderbauer** [comment]
We just pass on the values we get from the underlying OS/hardware. So, I think from Flutter's perspective this is all expected.
