### ISSUE TITLE
Fresh Install - flutter has exited unexpectedly - Run the app section of Getting Started: Test Drive

### ISSUE THREAD

**Issue by FallenArchangel** [flutter/flutter#15025]
## Steps to Reproduce

This is a fresh install of both Android Studio and Flutter on a Debian Stretch system.  While on the getting started page (https://flutter.io/get-started/test-drive/) I am unable to run the initially loaded app. (I've not changed any code."

Log attached
[flutter_04.log](https://github.com/flutter/flutter/files/1771902/flutter_04.log)

## Logs

```
Launching lib/main.dart on ad0b1603986a5d3aed in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...

Oops; flutter has exited unexpectedly.
Crash report written to /root/AndroidStudioProjects/myapp/flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.
```

* Where:
Script '/root/android-studio/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 421

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '/root/android-studio/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle build failed: 1

## Flutter Doctor
```
root@Wyvern:~/AndroidStudioProjects/myapp# flutter doctor -v
[!] Flutter (Channel beta, v0.1.5, on Linux, locale en_US.UTF-8)
    • Flutter version 0.1.5 at /root/android-studio/flutter
    • Framework revision 3ea4d06340 (7 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /root/Android/Sdk
    • Android NDK at /root/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /root/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /root/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices (1 available)
    • ad0b1603986a5d3aed • ad0b1603986a5d3aed • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

**Comment by mit-mit** [comment]
Extract from log file:

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target /root/AndroidStudioProjects/myapp/lib/main.dart --output-file /root/AndroidStudioProjects/myapp/build/app/intermediates/flutter/debug/app.flx --snapshot /root/AndroidStudioProjects/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin --depfile /root/AndroidStudioProjects/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --working-dir /root/AndroidStudioProjects/myapp/build/app/intermediates/flutter/debug/flutter_assets

## exception

ProcessException: ProcessException: No such file or directory
  Command: /root/android-studio/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot --await_is_keyword --causal_async_stacks --vm_snapshot_data=/root/android-studio/flutter/bin/cache/artifacts/engine/linux-x64/vm_isolate_snapshot.bin --isolate_snapshot_data=/root/android-studio/flutter/bin/cache/artifacts/engine/linux-x64/isolate_snapshot.bin --packages=/root/AndroidStudioProjects/myapp/.packages --dependencies=/root/AndroidStudioProjects/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --print_snapshot_sizes --snapshot_kind=script --script_snapshot=/root/AndroidStudioProjects/myapp/build/app/intermediates/flutter/debug/snapshot_blob.bin --enable-mirrors=false /root/AndroidStudioProjects/myapp/lib/main.dart

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:126)
<asynchronous suspension>
```

**Comment by mit-mit** [comment]
@FallenArchangel can you check if you might have the issue mentioned in https://github.com/flutter/flutter/issues/6207#issuecomment-369221550 as hinted by the warning shown in your doctor output?

**Comment by cbracken** [comment]
The new instructions added in #15004 may also help
```
On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
On Fedora: dnf install libstdc++.i686
On Arch: pacman -S lib32-libstdc++5
```

**Comment by cbracken** [comment]
Closing as fixed by #15004

**Comment by mohasu1992** [comment]
~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel beta, v0.1.5, on Linux, locale en_US.utf8)
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.


for  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel beta, v0.1.5, on Linux, locale en_US.utf8)
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
for  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel beta, v0.1.5, on Linux, locale en_US.utf8)
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
for solus 3.99

**Comment by mohasu1992** [comment]
~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel beta, v0.1.5, on Linux, locale en_US.utf8)
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
for SOLUS 3.99
