### ISSUE TITLE
[WASM] Flutter web throwing memory access out of bound error

### ISSUE THREAD

**Issue by AbhishekDoshi26** [flutter/flutter#150270]
### Steps to reproduce

This bug is random. However, I was able to sometimes reproduce it when I have a carousel and I spend some time swiping on it.

### Expected results

No errors should be there.

### Actual results

Getting the following error:
```
main.dart.js:3304 Uncaught RuntimeError: memory access out of bounds
at canvaskit.wasm:0x3abfc
at canvaskit.wasm:0x29150
at Tb.save (canvaskit.js:115:52)
at Gv.d6 (main.dart.js:26771:53)
at B_.j6 (main.dart.js:26595:3)
at KO.jU (main.dart.js:26486:28)
at a1L.$0 (main.dart.js:26727:18)
at Object.axo (main.dart.js:1160:18)
at a1I.aj5 (main.dart.js:26715:3)
at main.dart.js:27070:27
```

After getting error, the web app gets stuck. Can't even refresh the web app and then after closing the tab and if I reopen, it never loads and gets the same error.

### Code sample

Don't really have a code sample as it's completely random.
A similar issue is reported https://github.com/flutter/flutter/issues/150193

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.22.1 on channel stable at /Users/abhishekdoshi/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/abhishekdoshi/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0-rc1
    • Java binary at: /usr/bin/java
    ✗ Could not determine java version
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.61

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Hi @AbhishekDoshi26 
I see the error is not the same between yours and the given one at https://github.com/flutter/flutter/issues/150193. Instead, it looks similar to https://github.com/flutter/flutter/issues/150119 where I also see your comment there. 

Do you also use [webview_flutter_web](https://pub.dev/packages/webview_flutter_web) in your app? And does this issue only occur when building web with `wasm`? 

It would be more helpful if you can provide a sample code so that we can investigate it further.

**Comment by AbhishekDoshi26** [comment]
Hey @huycozy !

I don’t use webview in the project. And yes, this is mainly for flutter web after I build and deploy using firebase hosting.

**Comment by huycozy** [comment]
Thanks for the update but we still need a sample code to bring this forward. Otherwise, we can close this and follow https://github.com/flutter/flutter/issues/150119 as the error there is quite similar to this.
