### ISSUE TITLE
Chinese Pinyin input Enter event can not be detected

### ISSUE THREAD

**Issue by lucasjinreal** [flutter/flutter#150301]
### Steps to reproduce

In Chinese Pinyin Input：

<img width="171" alt="image" src="https://github.com/flutter/flutter/assets/21303438/c232413b-e548-4b07-85b9-31f0213aabc7">

It has 2 different Enter event：

One is input Chinese 输入中文输入 then send, this can be detect with KeyEvent

```
if (event.physicalKey == PhysicalKeyboardKey.enter &&
                !HardwareKeyboard.instance.physicalKeysPressed.any(
                  (el) => <PhysicalKeyboardKey>{
                    PhysicalKeyboardKey.shiftLeft,
                    PhysicalKeyboardKey.shiftRight,
                  }.contains(el),
                )) {
              if (event is KeyDownEvent) {
                _handleSendPressed();
              }
              return KeyEventResult.handled;
```

But here is another Enter event, which is using Pinyin input English, liruthisis 
<img width="143" alt="image" src="https://github.com/flutter/flutter/assets/21303438/9e8ec113-cec5-4e8a-95e9-e877fd3179df">

This Enter should enter the text directly, but now there is noway to distinguish them.

I want don't call `_handleSendPressed()` in the second situion, but now, it always all call it.

This should be distinguished.

### Expected results

efr

### Actual results

ferg

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
ferf

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
ve

**Comment by darshankawar** [comment]
@lucasjinreal 
Can you provide `flutter doctor -v` ? 
What platform are you seeing this behavior on ? Desktop, web ?


> But here is another Enter event, which is using Pinyin input English, liruthisis <img alt="image" width="143" src="https://private-user-images.githubusercontent.com/21303438/339970495-9e8ec113-cec5-4e8a-95e9-e877fd3179df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTI5NTgsIm5iZiI6MTcxODYxMjY1OCwicGF0aCI6Ii8yMTMwMzQzOC8zMzk5NzA0OTUtOWU4ZWMxMTMtY2VjNS00ZThhLTk1ZTktZTg3N2ZkMzE3OWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA4MjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZjdjODM5NWQ5Mjg2OGY1NDA4NGU5YjZjNWYwOTUzNzBhMDkwYzkyNjRjNzc0OTQ3YzhjYzIwZTIyZDczYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36lMQULUGisLHQtiSyLg6eht-KpCV9xMyGhJlpkArU4">
> 
> This Enter should enter the text directly, but now there is noway to distinguish them.
> 
> I want don't call `_handleSendPressed()` in the second situion, but now, it always all call it.
> 
> This should be distinguished.

How can we trigger this `Enter` event ? Can you provide exact steps that we need to follow to recreate this ?
