### ISSUE TITLE
admin folder are listed with `Directory.list()` but `Directory.existsSync` return false on them

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#150345]
### Steps to reproduce

On Windows directories that require admin privilege to be accessed are listed with `Directory.list()` but `Directory.existsSync` return false on them

### Expected results

it's not because it's an admin folder that it doesn't exist. you can not list it and then say it doesn't exist.

### Actual results

admin folder are listed but  `Directory.existsSync` return false on them

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4529], locale fr-FR)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
[!] Android Studio (not installed)
[✓] VS Code (version 1.90.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @stephane-archer, can you share a sample code with a specific path of directory and result confirmation?

**Comment by stephane-archer** [comment]
Hi @huycozy I discovered this issue running code in my `AppData` directory on Windows.

something like:
```
var d = Directory(C:\Users\steph\AppData);
var stream = d.list(recursive:true);
var stangeFile = stream.where((e) { return e.existSync();});
```
should reveal the issue. 
I think the `C:\Windows` would reveal the same issue if you haven't clicked the first time you accessed it to give yourself permission to see the content of this folder.

Basically, when I got the issue I checked the folder, and the Windows GUI (explorer) asked me if I wanted to get access, I said yes then the error disappeared. It's linked to Windows permission

**Comment by huycozy** [comment]
Thanks for the update. I add print like this and see `true` on every file.

```dart
var stream = d.list(recursive: true);
var stangeFile = stream.where((e) {
  final isExist = e.existsSync();
  print('$isExist - ${e.path}');
  return isExist;
});
stangeFile.forEach((e) {
  print(e.path);
});
```

```console
true - C:\Users\ADMIN\AppData\Local\Android Open Source Project\Emulator\QtWebEngine\Default\Origin Bound Certs-journal
C:\Users\ADMIN\AppData\Local\Android Open Source Project\Emulator\QtWebEngine\Default\Origin Bound Certs-journal
true - C:\Users\ADMIN\AppData\Local\Android Open Source Project\Emulator\QtWebEngine\Default\TransportSecurity
C:\Users\ADMIN\AppData\Local\Android Open Source Project\Emulator\QtWebEngine\Default\TransportSecurity
true - C:\Users\ADMIN\AppData\Local\Android Open Source Project\Emulator\QtWebEngine\Default\Visited Links
C:\Users\ADMIN\AppData\Local\Android Open Source Project\Emulator\QtWebEngine\Default\Visited Links
...
```

This needs to be investigated further and I think it's best suited to address on https://github.com/dart-lang/sdk since API is used on `dart:io` package. 

Closing this issue. If you disagree, please write in the comments and I will reopen it.

**Comment by stephane-archer** [comment]
@stephane-archer It would have been more appropriate to transfer the issue to the appropriate repo if you could have done that

**Comment by huycozy** [comment]
[dart-lang/sdk](https://github.com/dart-lang/sdk) is not available in `transfer issue` target as I can see.
