### ISSUE TITLE
HtmlView does not handling overflow styling properly

### ISSUE THREAD

**Issue by waymorphood** [flutter/flutter#150383]
### Steps to reproduce

I found this in flutterflow. They said it is a Flutter bug. Please see here: https://github.com/FlutterFlow/flutterflow-issues/issues/3138

### Expected results

styling HtmlView. The overflow handling of FlutterFlow is cumbersome. Based on characters is not acceptable for web apps. I am trying to use HtmlView with proper overflow CSS and it does not behave like proper browser does.

### Actual results

![Screenshot 2024-06-14 at 13 03 04](https://github.com/flutter/flutter/assets/59782695/3a79fc11-eef1-4854-aae4-2ce88c3c8752)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![Screenshot 2024-06-14 at 13 03 47](https://github.com/flutter/flutter/assets/59782695/1f572484-dfdb-4989-9891-b57b2699697d)
![Screenshot 2024-06-14 at 13 03 04](https://github.com/flutter/flutter/assets/59782695/7906111b-59d3-4725-bc10-608a29a95a92)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@waymorphood 
Can you provide us `flutter doctor -v` , a minimal reproducible code sample and platform in which you are seeing the reported behavior ?
