### ISSUE TITLE
How to get the list of assets in a directory?

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#150341]
### Use case

Hi, I have a few things I want to include as assets but their numbers can vary so in `pubspec.yaml`
```
assets:
 - assets/myData/
```

but I think there is no way to know at runtime what is in `assets/myData/`
I want to be able to do:
```
 
  // List of files in the asset directory
  final assetFiles = rootBundle.getAssetsNames("assets/myData/")

  for (var file in assetFiles) {
    // Load the file from the asset
    final byteData = await rootBundle.load(file);
    ....
}
```

### Proposal

add a way to get the name of the asset files under a specific directory like
```
  final assetFiles = rootBundle.getAssetsNames("assets/myData/")
```

**Comment by darshankawar** [comment]
@stephane-archer Most likely your issue is same as https://github.com/flutter/flutter/issues/137043 that you can check and confirm.

**Comment by stephane-archer** [comment]
@darshankawar It's similar but there is no mention of:
```
DefaultAssetBundle.of(context).findAssetsByFolderName("foo/");
```
So quite similar needs but not exactly the same.
How should we proceed?

**Comment by darshankawar** [comment]
Can you check if https://api.flutter.dev/flutter/services/AssetManifest/listAssets.html helps ?

**Comment by stephane-archer** [comment]
I think this would help yes, I can then filter the list with an operation on String. 
`List<String>.where(...)`

**Comment by darshankawar** [comment]
Good to know. I'll close this for now. If you disagree, write in comments and I'll reopen it.
