### ISSUE TITLE
Error Messages Not Displayed Properly in Flutter Web (Issue Present in Both 3.10.6 and 3.22.2)

### ISSUE THREAD

**Issue by KaushikGupta007** [flutter/flutter#150352]
### Steps to reproduce

1. Run Code Sample provided in flutter Web and Android
2. Click Button to trigger Error
3. Check for error logs

**Description :**
I am experiencing an issue where error messages are no longer displayed properly in Flutter Web. Initially, the error messages were displayed correctly while working with Flutter version 3.10.6. However, they suddenly stopped displaying without any changes to the code. I upgraded to the latest version 3.22.2, but the issue persists. The error messages still display correctly on Android.

### Expected results

Error messages should be displayed correctly in the web version of the app, as they were initially in Flutter version 3.10.6.

### Actual results

Error messages are displayed differently in the web version of the app in both Flutter version 3.10.6 and 3.22.2. The issue does not affect the Android version where error messages are displayed correctly.

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<void> main() async {
  runApp(MaterialApp(
    initialRoute: "/",
    routes: {
      "/": (context) => const Home(),
    },
  ));
}

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {

  String? nullableString;

  void _triggerError() {
    // This will cause a "Null check operator used on a null value" error
    String nonNullableString = nullableString!;
    print(nonNullableString);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Null Check Error Demo'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: _triggerError,
          child: const Text('Trigger Error'),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

**Android**
```console
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _HomeState._triggerError (package:design_studio/main_billdesk.dart:61:46)
#1      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171:21)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#5      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:696:9)
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#19     _invoke1 (dart:ui/hooks.dart:328:13)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#8cc5e
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(203.9, 454.6)
  finalLocalPosition: Offset(84.0, 28.7)
  button: 1
  sent tap down
```
**Web**
```console
The following TypeErrorImpl was thrown while handling a gesture:
Unexpected null value.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 586:18  nullCheck
packages/design_studio/main_billdesk.dart 61:46                                   [_triggerError]
packages/flutter/src/material/ink_well.dart 1171:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 344:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 696:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:7                            [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7           forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 495:5                                  handleEvent
packages/flutter/src/gestures/binding.dart 475:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 425:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 420:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1419:5                                invoke1
lib/_engine/engine/platform_dispatcher.dart 333:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30                                    [_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7                                     onPointerData
lib/_engine/engine/pointer_binding.dart 1001:20                                   <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 531:9                                     loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
Handler: "onTap"
Recognizer: TapGestureRecognizer#d525f
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(930.0, 504.0)
  finalLocalPosition: Offset(33.3, 19.5)
  button: 1
  sent tap down

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

**3.10.6**
```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.3593], locale en-IN)
    • Flutter version 3.10.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (11 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.9.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34616.47
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
[√] Connected device (4 available)
    • CPH2467 (mobile)  • 1a715d74 • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.3593]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 126.0.6478.61
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 126.0.2592.56

[√] Network resources
    • All expected network resources are available.

• No issues found!

```
**3.22.2**
```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22621.3593], locale en-IN)
    • Flutter version 3.22.2 on channel stable at C:\Users\Admin\fvm\versions\3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (12 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34616.47
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (4 available)
    • CPH2467 (mobile)  • 1a715d74 • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.3593]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 126.0.6478.61
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 126.0.2592.56

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@KaushikGupta007 
What's the expected console log or behavior are you looking for in web ? The way currently web shows the exception seems to be in sync with android, for example:



> ```
> [_triggerError]
> packages/flutter/src/material/ink_well.dart 1171:21                               handleTap
> packages/flutter/src/gestures/recognizer.dart 344:24                              invokeCallback
> packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
> packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
> packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
> packages/flutter/src/gestures/recognizer.dart 696:9                               handleEvent
> packages/flutter/src/gestures/pointer_router.dart 98:7                            [_dispatch]
> packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
> dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7           forEach
> packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
> ```

The class names are same as thrown in android if you look closely.

**Comment by suranjum** [comment]
I recently updated to 3.22.2, since then i stopped getting details of any error. Just shows 'Error'.
![Screenshot 2024-07-08 131544](https://github.com/flutter/flutter/assets/65178054/54087614-7f58-4e78-80ec-0dc0a929707b)

**Comment by KaushikGupta007** [comment]
Facing similar issue

> I recently updated to 3.22.2, since then i stopped getting details of any error. Just shows 'Error'. ![Screenshot 2024-07-08 131544](https://private-user-images.githubusercontent.com/65178054/346472839-54087614-7f58-4e78-80ec-0dc0a929707b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUyMTMsIm5iZiI6MTcyMDQyNDkxMywicGF0aCI6Ii82NTE3ODA1NC8zNDY0NzI4MzktNTQwODc2MTQtN2Y1OC00ZTc4LTgwZWMtMGRjMGE5Mjk3MDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA3NDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MzMxNWY5NGMzODUzZjYzNWM0YzlhMzQ0YTg1ODk3MzE0Yzc1Y2ZlNzQ2MjdjODYwNGI2MzAyZTJiOWU4MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oMTYy80rg8pFYq_LtcC24t17IKITWhs_-d6q89hjrk4)

**Comment by darshankawar** [comment]
I get below in latest stable version:

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown while handling a gesture:
Unexpected null value.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 586:18  nullCheck

```

**Comment by tolotrasamuel** [comment]
> I recently updated to 3.22.2, since then i stopped getting details of any error. Just shows 'Error'. ![Screenshot 2024-07-08 131544](https://private-user-images.githubusercontent.com/65178054/346472839-54087614-7f58-4e78-80ec-0dc0a929707b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzE5ODMsIm5iZiI6MTcyMTMzMTY4MywicGF0aCI6Ii82NTE3ODA1NC8zNDY0NzI4MzktNTQwODc2MTQtN2Y1OC00ZTc4LTgwZWMtMGRjMGE5Mjk3MDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDE5NDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZjFjNTA2MTFkOGE4NTlhOTdhZGYxZmM3NWZmOGQ5NDVhMjcwZWY4M2JlYzIyNzdiZTYxYWJjYmZiYzYwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PIAkGszP-GbPywwkpGn9qtdnDLkWJ8ZT9VIGgroste8)

Yes, I got the same . Sadly, that's what we get for upgrading. As a Flutter rule of thumb, there is a new instability for every new stable released.

**Comment by KaushikGupta007** [comment]
> > I recently updated to 3.22.2, since then i stopped getting details of any error. Just shows 'Error'. ![Screenshot 2024-07-08 131544](https://private-user-images.githubusercontent.com/65178054/346472839-54087614-7f58-4e78-80ec-0dc0a929707b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzE5ODMsIm5iZiI6MTcyMTMzMTY4MywicGF0aCI6Ii82NTE3ODA1NC8zNDY0NzI4MzktNTQwODc2MTQtN2Y1OC00ZTc4LTgwZWMtMGRjMGE5Mjk3MDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDE5NDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZjFjNTA2MTFkOGE4NTlhOTdhZGYxZmM3NWZmOGQ5NDVhMjcwZWY4M2JlYzIyNzdiZTYxYWJjYmZiYzYwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PIAkGszP-GbPywwkpGn9qtdnDLkWJ8ZT9VIGgroste8)
> 
> Yes, I got the same . Sadly, that's what we get for upgrading. As a Flutter rule of thumb, there is a new instability for every new stable released.
> 
> Tried also 3.16.9 and 3.19.3.

It still shows Error in console while running on web but displays proper messages while running on Android

**Comment by darshankawar** [comment]
I get below running on latest stable (3.22.3) and on master:

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown while handling a gesture:
Unexpected null value.

When the exception was thrown, this was the stack:

```

Not the only term `Error`, so I guess the exception we are seeing now as above is expected ?

**Comment by arv-aks** [comment]
The errors are different because of the way Flutter handles exceptions and stack traces across different platforms (Android and Web). The underlying issue, however, is the same: a null check operator (!) is being used on a null value.

**Comment by darshankawar** [comment]
Thanks for the update. Based on the report, behavior, I'll keep the issue open for team's attention / tracking.

**Comment by axoroll7** [comment]
What is the current workaround ?

**Comment by KaushikGupta007** [comment]
What I do is run the app on Android or iOS to get proper error message. But it would be good if this issue is fixed.

**Comment by axoroll7** [comment]
> What I do is run the app on Android or iOS to get proper error message. But it would be good if this issue is fixed.

In my situation, I don't know what to do: On android, this line `await launchUrl(Uri.parse(link.url));` doesn't throw, but it does on web, and I don't know why.

**Comment by KaushikGupta007** [comment]
>>  What I do is run the app on Android or iOS to get proper error message. But it would be good if this issue is fixed.
> 
> In my situation, I don't know what to do: On android, this line `await launchUrl(Uri.parse(link.url));` doesn't throw, but it does on web, and I don't know why. Should I use an old flutter version ? Which one ?

 I don't this this will solve with version change because I have tried in older versions.

**Comment by axoroll7** [comment]
I found a little workaround. If I wrap my exception in a try/catch to print the exception, I can see the exception.
This code print a generic error :
```
throw Exception('test');
```
This one, not :
```
try{
  throw Exception('test');
} catch(ex){
  print(ex);
}
```

@suranjum said we can see this :
```
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
packages/XXX.dart XXX:XXX                                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
```
I want to add, often, I see this, just before or just after :
```
ChromeProxyService: Failed to evaluate expression '': InvalidInputError: .
```
Maybe someone can find a better workaround, with a hook to the exception handler ??

**Comment by axoroll7** [comment]
I found a better workaround, to print the string representation, but not the true stack trace unfortunately.
```dart
Future<void> main() async {
  await runZonedGuarded<Future<void>>(
    main2,
    (Object error, StackTrace stackTrace) {
      if(kDebugMode){
        print(error);
        print(stackTrace);
      }
    },
  );
}
```
The initial `main` function, has been renamed to `main2`.

**Comment by axoroll7** [comment]
> I'm a little confused. The original report and repro does not seem to contain the issue. There are bits and piece in the comments indicating that there is an issue in some situations. Could someone please provide a full repro case that reproduces the issue, showing just `Error` and nothing else?

@yjbanov

In a button onclick callback :

```dart
throw Exception('test');
```
