### ISSUE TITLE
 Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

### ISSUE THREAD

**Issue by HanJiuYuan** [flutter/flutter#150329]
### Steps to reproduce

1. In the production environment, start flutter.
2. Build with any iOS device.

### Expected results

Build succeded

### Actual results

Launching lib/main.dart on iPhone Xs Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           19.6s
Failed to build iOS app
Error (Xcode): Build input file cannot be found: '/Users/flutterteamotto/StudioProjects/flutter_leisurely_travel/ios/Runner/AppDelegate.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

Could not build the application for the simulator.
Error launching application on iPhone Xs Max.

### Code sample
n/a

### Screenshots or Video

![23531718594909_ pic](https://github.com/flutter/flutter/assets/68726726/da9a79a4-ff9a-4613-b904-064b013b26ef)

### Logs
n/a

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.2 23C64 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.6 on channel stable at /Users/flutterteamotto/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (9 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/flutterteamotto/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/flutterteamotto/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.0)
    • VS Code at /Users/flutterteamotto/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)            
    • iPhone Xs Max (mobile) • CDC21327-C258-4B2D-8950-D9864798F582 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 126.0.6478.61
    ! Device emulator-5554 is offline.

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @HanJiuYuan, does the `AppDelegate.swift` exist in your `/Users/flutterteamotto/StudioProjects/flutter_leisurely_travel/ios/Runner/` directory? If not, can you try recreating it and running your project again?

**Comment by HanJiuYuan** [comment]
> 你好@HanJiuYuan，`AppDelegate.swift`您的目录中是否存在`/Users/flutterteamotto/StudioProjects/flutter_leisurely_travel/ios/Runner/`？如果不存在，您可以尝试重新创建它并再次运行您的项目吗？

![image](https://github.com/flutter/flutter/assets/68726726/50c4639c-93d3-46df-88c1-7a7ef2d61e3d)
Hello, it exists.

**Comment by danagbemava-nc** [comment]
Hi @HanJiuYuan, your screenshot does not show the `AppDelegate.swift` file. You should check your git history to see if it wasn't accidentally deleted. If it was accidentally deleted, you should restore it. 

These are the items in your `Runner` directory from the screenshot you shared above.

- Assets.xcassets
- Base.Iproj
- GeneratedPluginRegistrant.h
- GeneratedPluginRegistrant.m
- Info.plist
- Runner-Bridging-Header.h

**Comment by HanJiuYuan** [comment]
> 你好@HanJiuYuan，您的屏幕截图没有显示该`AppDelegate.swift`文件。您应该检查您的 git 历史记录，看看它是否被意外删除。如果它被意外删除，您应该恢复它。
> 
> `Runner`这些是您上面分享的屏幕截图中的目录中的项目。
> 
> * 资产.xcassets
> * 基础项目
> * 生成的插件注册器.h
> * 生成的插件注册器.m
> * 信息列表
> * Runner-Bridging-Header.h

But when I re-run it on a different computer, it works.

**Comment by danagbemava-nc** [comment]
On that computer, do you have the `AppDelegate.swift` file? Have you checked your local git history to see if you haven't deleted the file?
