### ISSUE TITLE
BackgroundBlendMode not working with `Gradient` if stacked on a `VideoPlayerWidget` on Android

### ISSUE THREAD

**Issue by cscipher** [flutter/flutter#150336]
### Steps to reproduce

1. Container with gradient and blendMode properties in the BoxDecoration
2. Stacking this Container on a VideoPlayerView

### Expected results

The GradientContainer should blend according to the given config.

### Actual results

blendMode property is not working on android platform, but still works for iOS.

### Code sample

<details open><summary>Dartpad Code Sample</summary>

https://dartpad.dev/?id=c89a9037ababa70d6f9b6dc882201036

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/57137427/a37874d5-1ccf-4281-806b-60f1990d0bb9

https://github.com/flutter/flutter/assets/57137427/ab899e87-df3b-4302-afa1-6e71c411695e

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```
Logs N/A as tested on dartpad
```

</details>

**Comment by huycozy** [comment]
Hi @cscipher 
Which Android device are you checking on? (OS, model)

I checked this on my device Pixel 7, Android 14 but the gradient is rendered as expected (I'm also on Flutter stable 3.22.2) 

<details>
<summary>Demo</summary>

![Screenshot 2024-06-17 at 18 32 03](https://github.com/flutter/flutter/assets/104349824/cd7496c3-1084-4f0b-b645-8692c20b8ce4)
</details>

Also, can you check what is your current `video_player_android` version? (the latest is `video_player_android: ^2.5.0`)

**Comment by cscipher** [comment]
hey @huycozy , I tested it on Pixel 5A and it wasn't working as expected.
I'm also on latest Flutter version `3.22.2`and `video_player` package

**Comment by huycozy** [comment]
Can you confirm you checked `video_player_android` version from `pubspec.lock` file? What is OS version of your Pixel 5? (so I can check it from my end with emulators)
