### ISSUE TITLE
Hope to support the loongarch64 architecture soon

### ISSUE THREAD

**Issue by ToKingl** [flutter/flutter#150390]
### Steps to reproduce

I would like to ask when flutter can support loongarch64 architecture?

### Actual results

loongarch64 architecture not supported

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
Hi @ToKingl 
Per https://www.kernel.org/doc/html/v6.4/loongarch/introduction.html:

> LoongArch is a new RISC ISA, which is a bit like MIPS or RISC-V. There are currently 3 variants: a reduced 32-bit version (LA32R), a standard 32-bit version (LA32S) and a 64-bit version (LA64). 

I see there's an open issue that requests support for Linux RISC-V at https://github.com/flutter/flutter/issues/99963. I will close this in favor of that one, so please follow up on it for further updates. Thanks!
