### ISSUE TITLE
restorePurchases does not expose error details

### ISSUE THREAD

**Issue by jd-bus** [flutter/flutter#150323]
### What package does this bug report belong to?

in_app_purchase

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
  in_app_purchase:
    dependency: "direct main"
    description:
      name: in_app_purchase
      sha256: "960f26a08d9351fb8f89f08901f8a829d41b04d45a694b8f776121d9e41dcad6"
      url: "https://pub.dev"
    source: hosted
    version: "3.2.0"
  in_app_purchase_android:
    dependency: transitive
    description:
      name: in_app_purchase_android
      sha256: b18871cffd4ec8911171864bfc0060c983be96215080a0847c29ef9147f439ef
      url: "https://pub.dev"
    source: hosted
    version: "0.3.6+1"
  in_app_purchase_platform_interface:
    dependency: transitive
    description:
      name: in_app_purchase_platform_interface
      sha256: "1d353d38251da5b9fea6635c0ebfc6bb17a2d28d0e86ea5e083bf64244f1fb4c"
      url: "https://pub.dev"
    source: hosted
    version: "1.4.0"
  in_app_purchase_storekit:
    dependency: transitive
    description:
      name: in_app_purchase_storekit
      sha256: "3eea5e173fca0a59ab2fcec5201bea14bb808dfad01004d2b1d7bfdb9244c5e6"
      url: "https://pub.dev"
    source: hosted
    version: "0.3.16"
```

</details>

### Steps to reproduce

If you call restorePurchases and get any error and catch it, there will be nothing in the logs other than `FlutterError - Instance of 'SKError'`

### Expected results

I would expect applicable error classes such as `IAPError` or `InAppPurchaseException` that would expose the code and details.  That way, debugging would be possible.

### Actual results

I just get the following: `FlutterError - Instance of 'SKError'`

However SKError is not defined anywhere in in_app_purchase.  Therefore I cannot cast the error or get any further details from that.

### Code sample

<details open><summary>Code sample</summary>

```dart
final InAppPurchase _iap = InAppPurchase.instance;
bool _available = await _iap.isAvailable();
if (_available) {
  try {
    await _iap.restorePurchases();
  } catch (e, s) {
    FirebaseCrashlytics.instance.recordError(e, s, fatal: false);
  }
}
```

</details>

### Logs

<details open><summary>Logs</summary>

This is how it shows in Firebase Crashlytics:
```console
flutter_error_exception	Instance of 'SKError'
```
No further details are available.
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/jd-bus/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (11 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. This seems to be similar to https://github.com/flutter/flutter/issues/140225 which once fixed, should be resolved for your case as well. So I suggest you to follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by jd-bus** [comment]
I appreciate the quick response and agree that this would be covered by the proposed fixes in #140225.

If you don't mind, I'm still stuck on what I can do in the meantime.  With respect to restorePurchases, #140225 reads "and on iOS it can throw an SKError."
But I haven't been able to catch SKError because it doesn't seem to be exposed to Dart.   Is there _any_ way, even if convoluted, that I can get at the details of the error that my users are facing, short of waiting for #140225?

Thanks!

**Comment by darshankawar** [comment]
Thanks for the feedback. 



> Is there _any_ way, even if convoluted, that I can get at the details of the error that my users are facing, short of waiting for #140225?

I am not sure if currently it is possible. You may check https://developer.apple.com/documentation/storekit/skerror and also below related issues which indicates the error handling need to be implemented for the package still:

https://github.com/flutter/flutter/issues/85104
https://github.com/flutter/flutter/issues/39119

**Comment by jd-bus** [comment]
ok thanks
