### ISSUE TITLE
NumberPicker error "type 'ScrollController' is not a subtype of type 'InfiniteScrollController' in type cast" in "Row"

### ISSUE THREAD

**Issue by ZaqueuDias** [flutter/flutter#150311]
### Steps to reproduce

Hello, is everything ok?
I'm facing an issue with the NumberPicker widget, specifically its infiniteLoop parameter. The infiniteLoop parameter requires the bool type to allow NumberPicker to have infinite scrolling, but whenever the program is run by placing this parameter, the error "type 'ScrollController' is not a subtype of type 'InfiniteScrollController' in type cast" is returned.

![Captura de Tela (710)](https://github.com/flutter/flutter/assets/171173595/5cfe5634-5520-4f8c-af30-09d8fd3cf55a)

![Captura de Tela (713)](https://github.com/flutter/flutter/assets/171173595/eaa17463-51a8-452c-b7e5-23a84624be00)

### Expected results

![WoCX6](https://github.com/flutter/flutter/assets/171173595/22ff20ae-0c4c-4412-bbcd-bf504c3c8c5e)

### Actual results

![Captura de Tela (711)](https://github.com/flutter/flutter/assets/171173595/09d0d358-0e7a-4e76-91d0-0aa32c7b2146)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
`numberpicker` is a third-party package. Any issues you face using it should be reported on their repo. Closing from here.  https://github.com/MarcinusX/NumberPicker/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc


Thank you
