### ISSUE TITLE
Finish migrating the Play Store's io.flutter.gallery to io.flutter.demo.gallery

### ISSUE THREAD

**Issue by tenhobi** [flutter/flutter#15034]
On my 18:9 phone (Xiaomi Redmi 5 plus) there is a black gap around the Flutter Galery app. I do not know if this is a issue related to Flutter or Android config files, but I rather report it here:

![28512271_1612179045533129_1415121403_n](https://user-images.githubusercontent.com/5287596/36870279-d50729f4-1d9e-11e8-9226-29951bfc592a.png)

![28755164_1612181412199559_450223850_o](https://user-images.githubusercontent.com/5287596/36870349-180e86fc-1d9f-11e8-8886-63aeb4d9fdd4.png)

**Comment by cbracken** [comment]
For whoever looks into this: my initial guess was that this may have something to do with how we compute `window.viewInsets` (in `onApplyWindowInsets` and `fitSystemWindows` in `FlutterView.java`). But it actually looks like the padding is correct here under the assumption that the status bar should be translucent. 

What appears to be wrong is that the status bar is opaque black instead. I'm not super-familiar on the Android side, but there's some information here:
http://blog.raffaeu.com/archive/2015/04/11/android-and-the-transparent-status-bar.aspx

@jason-simmons is likely familiar with the APIs here.

**Comment by cbracken** [comment]
@tenhobi do you run into the same issue if you create a new project with `flutter create` then run that on your device?

**Comment by tenhobi** [comment]
Hmm, if I run a project from `flutter create`, it all seems just fine.

![28535974_1612590815491952_2048349266_n](https://user-images.githubusercontent.com/5287596/36891459-048140da-1e02-11e8-97b1-60baad9b94c2.png)

![28642859_1612600168824350_940770691_o](https://user-images.githubusercontent.com/5287596/36892073-ef44ad04-1e03-11e8-9cd7-567c8e2276a1.png)

I have this Flutter settings:

```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.248], locale cs-CZ, channel dev)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)                                                                                                                                                                                          [√] VS Code (version 1.20.1)
[√] Connected devices
```

**Comment by cbracken** [comment]
@tenhobi thank you for confirming.

Sounds like the issue is specific to the gallery app's configuration. I'll take a look at the Android side diffs between our project template and the gallery.

Just to confirm -- I'm assuming you were running the gallery with no local modifications?

**Comment by tenhobi** [comment]
@cbracken Yes, no local modifications, the gallery was run from Google Play.

**Comment by cbracken** [comment]
Oh interesting! One more question (if you don't mind). 

If you run the version from gallery directly (from the SDK dir, `cd examples\flutter_gallery` then `flutter run`, does it look okay there?

Thanks for the additional info, this is really helpful in narrowing down the root cause.

**Comment by tenhobi** [comment]
It seems it works fine when it is run from locale source.

![19251240_1612956282122072_1929641400_n](https://user-images.githubusercontent.com/5287596/36910772-f2b645f4-1e41-11e8-9fd2-142e45485d83.png)
![28767778_1612956202122080_2069245289_o](https://user-images.githubusercontent.com/5287596/36910774-f375b024-1e41-11e8-8dac-b353fcefa94d.png)

**Comment by cbracken** [comment]
Thanks again for confirming! We’ll take a look at our Play Store release tooling.

**Comment by xster** [comment]
Gradle might be doing some extra work based on the currently connected phone. @tenhobi, just out of curiosity, if you built `flutter build apk` in the gallery example and then `flutter install`ed that apk, would it have the same issue?

**Comment by tenhobi** [comment]
@xster it's still OK with using those commands. I.e. only the Google play version is broken.

**Comment by xster** [comment]
I know what the issue is :)

We're in the process of moving the app from  https://play.google.com/store/apps/details?id=io.flutter.gallery to https://play.google.com/store/apps/details?id=io.flutter.demo.gallery. 

https://play.google.com/store/apps/details?id=io.flutter.gallery is a fairly old version. I think you should no longer experience the issue on the newer version of the gallery.

**Comment by tenhobi** [comment]
@xster this gallery app version (`io.flutter.demo.gallery`) seems to work. :-) 👍

**Comment by cbracken** [comment]
@xster is there anything blocking us from taking the old version off the store?

**Comment by xster** [comment]
Ummmm, typed a response and forgot to press send :S

We direct linked the old gallery in some articles. Removing it would 404 right now. I changed the description to the new url. Going to let it soak for a week before removing.

**Comment by cbracken** [comment]
Are we good to drop the old URL now?

**Comment by xster** [comment]
Removed today
