### ISSUE TITLE
`SliverLayoutDimensions` hash code doesn't include all properties.

### ISSUE THREAD

**Issue by PurplePolyhedron** [flutter/flutter#150305]
### Steps to reproduce

See framework code for `SliverLayoutDimensions.hashCode`

### Expected results

hashCode should include all properties

### Actual results

hashCode doesn't include `crossAxisExtent`, and uses `viewportMainAxisExtent` twice.

### Code sample

the framework code is [link](https://github.com/flutter/flutter/blob/5187cab7bdd434ca74abb45895d17e9fa553678a/packages/flutter/lib/src/rendering/sliver.dart#L83)
```
@override
  int get hashCode => Object.hash(
    scrollOffset,
    precedingScrollExtent,
    viewportMainAxisExtent,
    viewportMainAxisExtent
);
```

### Flutter Doctor output

```
[✓] Flutter (Channel master, 3.23.0-13.0.pre.242, on macOS 14.4.1 23E224 darwin-arm64, locale en-AU)
    • Flutter version 3.23.0-13.0.pre.242 on channel master at /Users/mainj/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5187cab7bd (13 hours ago), 2024-06-14 23:35:34 -0400
    • Engine revision 9779c273aa
    • Dart version 3.5.0 (build 3.5.0-266.0.dev)
    • DevTools version 2.36.0
```

**Comment by goderbauer** [comment]
Fixed in https://github.com/flutter/flutter/pull/150306.
