### ISSUE TITLE
No animation when I use pushNamedAndRemoveUntil 

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#15030]
A have this series of screens A->B->C. When I'm in C I want to push D and clear the stack bellow until A so I can have A->D. I use pushNamedAndRemoveUntil for this and it works perfectly but it doesn't animate the transition from C to D, it just changes.

![ezgif-2-76796c815c](https://user-images.githubusercontent.com/9283414/36869002-d49a78fa-1da2-11e8-9ae5-e54c81c42afc.gif)

**Comment by long1eu** [comment]
is there a way to speed this up?

**Comment by qwilbird** [comment]
@zoechi Hi, do you know when this is going to be solved?

**Comment by long1eu** [comment]
This issue could be fixed if https://github.com/flutter/flutter/pull/15764 would be merged. Still I don't think it works as intended since all push methods convey the animation along with the page change. Still look like you(@zoechi) feel the same since your added the framework label.

**Comment by Hixie** [comment]
Weird, I wonder why this doesn't work.

**Comment by goderbauer** [comment]
Dupe of https://github.com/flutter/flutter/issues/25080.

**Comment by long1eu** [comment]
How is this a dup if is early than 25080, like way earlier?? :))

**Comment by goderbauer** [comment]
The other one has more information (it includes a runnable code sample for example). Therefore I picked it as the canonical candidate for this bug.
