### ISSUE TITLE
Allow build configurations not named "Debug" for Swift Package Manager compatibility

### ISSUE THREAD

**Issue by importRyan** [flutter/flutter#150457]
### Use case

Flutter asserts Flavors be [prefixed with Debug](https://docs.flutter.dev/deployment/flavors). An xcconfig can also explicitly include `FLUTTER_BUILD_MODE=debug`.

However, while Xcode compiles and runs a debug Build Configuration without this prefix (e.g., named "Internal"), VSCode will refuse.

This appears to preclude usage Swift Package Manager in a Flutter project using Firebase. (I'm hoping to be wrong and have missed [prior issues](https://github.com/flutter/flutter/issues/125351) with resolutions.) Swift Package Manager has a known idiosyncrasy of ignoring the EXCLUDED_ARCHS of DEBUG builds (e.g., arm64 so Firebase will compile for Simulator). To avoid triggering this behavior, the Build Configuration must not case insensitively contain "debug" or "development" (e.g., "Internal" will restore SPM's obedience).

Flutter build error in VSCode (yet Xcode will run this)
```
The Xcode project defines build configurations: Internal, Release, Profile
Flutter expects a build configuration named Debug or similar.
Open Xcode to fix the problem:
  open ios/Runner.xcworkspace
1. Click on "Runner" in the project navigator.
2. Ensure the Runner PROJECT is selected, not the Runner TARGET.
3. Click the Editor->Add Configuration->Duplicate "Debug" Configuration.

   If this option is disabled, it is likely you have the target selected instead
   of the project; see:
   https://stackoverflow.com/questions/19842746/adding-a-build-configuration-in-xcode

   If you have created a completely custom set of build configurations,
   you can set the FLUTTER_BUILD_MODE=debug
   in the .xcconfig file for that configuration and run from Xcode.

4. If you are not using completely custom build configurations, name the newly created configuration debug.
Could not build the application for the simulator.
```

### Proposal

Allow building debug Flavors without the literal "Debug" prefix.

**Comment by huycozy** [comment]
This looks similar to https://github.com/flutter/flutter/issues/65458 (the target is not the same, though). Could you take a look and confirm if it also assembles this case?

**Comment by importRyan** [comment]
> This looks similar to https://github.com/flutter/flutter/issues/65458. Could you take a look and confirm if it also assembles this case?

Yep, same ask! In this case prompted by the loss of a swift package manager due to humorous loggerheads on "Debug" string parsing.

**Comment by huycozy** [comment]
Thanks for confirming that. Closing this issue in favor of that one. You can also leave your case on that issue in comments which will help to diversify the problem.
