### ISSUE TITLE
Document how to create a custom Navigator in the Navigator docs

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#15040]
How do i nest navigators in flutter. Instead of using he MaterialApp  navigator, I want to create a new navigator in one of the screens and use it for navigations.

I created a new navigator in a screen.
```
    var nav1 = new Navigator(
      onGenerateRoute: MyApp._getRoute,
    );

```
Now I want to navigate to a different screen as a part of button click. The push named takes the BuildContext, so I guess I have to connect this new navigator to the context so it does not use the Material app navigator.

```
                    new RaisedButton(
                      onPressed:(){
                        Navigator.pushNamed(context, "/screen3");
                      },
                      child: new Text("Go to Screen 3"),
```
  
OR

```
                    new RaisedButton(
                      onPressed:(){
                        Navigator.of(context).pushNamed("/screen3");
                      },
                      child: new Text("Go to Screen 3"),
```

**Comment by xster** [comment]
Taking this as a need to clarify the docs to add a tip to use a `Builder` to get a new BuildContext between the Navigator construction and the Navigator.of getting

**Comment by manujbahl** [comment]
Thanks ... A sample would also be helpful

**Comment by manujbahl** [comment]
Hey Guys,  When is the next milestone due? I am currently blocked by this. If this is just a documentation issue, can you please just provide me with guidance on how to do this.

Here is the code for the screen I want to add a navigator to.
See where I want to push the route for Screen2 to the new navigator (nav1) stack instead of the rootnavigator stack.  
Navigator.of(CONTEXT FOR nav1).pushNamed("/screen2");

```
class DetailsScreen extends StatefulWidget {
  @override
  Widget build(BuildContext context) {
    var nav1 = new Navigator(
      onGenerateRoute: MyApp._getRoute,
    );

    return new Scaffold( // 1
      appBar: new AppBar(
        title: new Text("Details Screen"), // screen title
      ),
      body: new StoreConnector<dynamic, Map>(
              converter: (store) => (store.state['1']),
              builder: (context, jsonNodeData) => new Center(
                child: new Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    new RaisedButton(
                      onPressed:(){
                        Navigator.of(CONTEXT FOR nav1).pushNamed("/screen2");
                      },
                      child: new Text("Go to Screen 2"),
                    )
                  ]
                )
              )
        )
        );
  }
}
```

**Comment by xster** [comment]
Oh I see. I'm not super familiar with how the redux package is structured. I'd print `context` inside the `onPressed` to see where the context you're getting is from. 

If it's giving you the wrong one, you can perhaps wrap the StoreConnector with a `Builder` where you'd know it's the context inside the Navigator. Don't shadow the `context` instance from that `Builder` and refer to it in the `Navigator.of`

**Comment by manujbahl** [comment]
I don't think my question has any bearing on the redux or storeconnector. The code could just be as below and I would still want to find a way to figure out how to associate the new Navigator to the context so that the route is push to nav1 instead of the rootnavigator.

```
class DetailsScreen extends StatefulWidget {
  @override
  Widget build(BuildContext context) {
    var nav1 = new Navigator(
      onGenerateRoute: MyApp._getRoute,
    );

    return new Scaffold( // 1
      appBar: new AppBar(
        title: new Text("Details Screen"), // screen title
      ),
      body: new Center(
                child: new Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    new RaisedButton(
                      onPressed:(){
                        Navigator.of(nav1).pushNamed("/screen2");
                      },
                      child: new Text("Go to Screen 2"),
                    )
                  ]
                )
              )
        );
  }
}
```

**Comment by xster** [comment]
I brought up StoreConnector because it shadows the `context` variable initially given by the `build` method of `DetailsScreen` and I don't know how it's provided. 

In your reduced example, if you put `context` in Navigator.of, it's using the context of where the DetailsScreen is inserted in the widget tree, which is before you built a new Navigator. To get the `context` in the widget tree below the Navigator, insert a https://docs.flutter.io/flutter/widgets/Builder-class.html widget like I was saying anywhere between the Navigator and the RaisedButton.

**Comment by manujbahl** [comment]
OK .. will try. SO just creating a new navigator is enough. It does not need to be made a child or parent of any widget ? Is there anything to connect the builder and the navigator

**Comment by manujbahl** [comment]
Below is what I did but it still does not call _getRoute2 from nav1 navigator.
I am sure I am missing something obvious. 

```
class DetailsScreen extends StatefulWidget {
    DetailsScreenState createState() => new DetailsScreenState();
}

class DetailsScreenState extends State<DetailsScreen> {
  @override
  Widget build(BuildContext context) {
    var nav1 = new Navigator(
      onGenerateRoute: MyApp._getRoute2
    );

    return new Builder(
      builder: (context) => new Scaffold(
          appBar: new AppBar(
            title: new Text("Screen 2"),
          ),
          body:  new Center(
              child: new Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  new Text("Screen 2"),
                  new RaisedButton(
                    onPressed:(){
                      Navigator.of(context).pop();
                    },
                    child: new Text("Back"),
                  ),
                  new RaisedButton(
                    onPressed:(){
                      Navigator.of(context).pushNamed("/screen3");
                    },
                    child: new Text("Go to Screen 3"),
                  ),
                ]
              )
            )
          
        )
    );
  }
}

```

**Comment by manujbahl** [comment]
Any ideas on how to place the widget under the new navigator in the tree?

**Comment by Hixie** [comment]
It's not clear to me where you're putting the "nav1" navigator. For example in the last snippet of code, you create the widget, but then you don't seem to use it.

**Comment by manujbahl** [comment]
That's exactly what I'm unclear about. How to use nav1 widget so that in the RaisedButton onPressed, the Navigator.of returns nav1 instead of the MaterialApp's navigator

**Comment by Hixie** [comment]
Navigator is a widget. If you want to use a widget, you have to return it somewhere in the build method.

**Comment by manujbahl** [comment]
Right .. but the Navigator widget does not have a child property. I can't seem to figure out how to wrap the builder or any other widget inside it. Is there a code sample anywhere?

**Comment by Hixie** [comment]
The Navigator's purpose is to show different routes. If you want your own Navigator you can provide an `onGenerateRoute` handler for the Navigator. See for example how CupertinoTabView does it: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/tab_view.dart

**Comment by manujbahl** [comment]
OK .. figured it out now. I was missing the fact that the we have to return the nav widget instead of Screen1 and Screen 1 needs to be set at the default "/" route.

Suggestion for documentation. In the Navigator class it would be helpful to write something like this.

Create a custom navigator widget and set the default route "/" in the OnGenerateRoute method for the navigator.  Sample Code

```
class ProfileNavigator extends StatelessWidget {
    Widget build(BuildContext context) {
      return new Navigator(
        onGenerateRoute: getProfileRoutes
      );
  }

  static var profileRoutes = <String, WidgetBuilder> {
    '/': (BuildContext context) => new About(),
    '/friends': (BuildContext context) => new Friends(),
    '/activity': (BuildContext context) => new Activity(),
  };
  
  static Route<BuildContext> getProfileRoutes(RouteSettings settings) {
    var builder = profileRoutes[settings.name];
    if(builder != null) {
        return new MaterialPageRoute(
            settings: settings,
            builder: builder,
        );
    }
    return null;
  }
}
```

**Comment by ayham95** [comment]
I've made a simple package that would help with creating nested navigators 
[Custom-navigator](https://pub.dev/packages/custom_navigator/versions/0.1.1)
