### ISSUE TITLE
Stack does not fully cover underneath widget.

### ISSUE THREAD

**Issue by MyisCARRY** [flutter/flutter#150439]
### Steps to reproduce

1. https://dartpad.dev/?null_safety=true
2. Paste code
3. Run

### Expected results

We can't see green line at the bottom of stack - it is fully covered by red.

### Actual results

Red does not fully cover underneath widget and we can see 1 pixel green line.
It is on dart pad but happened to me also on mobile.
When I set `top: 0` instead of `top: 200` I don't get this green line.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Center(
          child: SizedBox(
            width: 400,
            height: 400,
            child: ClipRRect(
              borderRadius: BorderRadius.all(Radius.circular(20)),
              child: Stack(
                children: [
                  Positioned.fill(
                    child: ColoredBox(color: Colors.green),
                  ),
                  Positioned(
                    top: 200,
                    bottom: 0,
                    left: 0,
                    right: 0,
                    child: ColoredBox(color: Colors.red),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Whole square
![Screenshot 2024-06-18 at 17 36 28](https://github.com/flutter/flutter/assets/26718209/9e3a7fc0-4ef1-44af-938f-bc308214e68c)

Close up
<img width="649" alt="Screenshot 2024-06-18 at 17 37 03" src="https://github.com/flutter/flutter/assets/26718209/789d2130-21ba-4c2e-a74a-2c1e517106b0">

</details>

### Logs

<details open><summary>Logs</summary>

```console
No logs
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
It is dart pad example
```

</details>

**Comment by darshankawar** [comment]
@MyisCARRY 


> ### Expected results
> We can't see green line at the bottom of stack - it is fully covered by red.
> 
> ### Actual results
> Red does not fully cover underneath widget and we can see 1 pixel green line.

Can you elaborate how to get to the actual behavior you are seeing ? I ran the code and zoomed in which shows me below:

<img width="1242" alt="Screenshot 2024-06-19 at 1 11 36 PM" src="https://github.com/flutter/flutter/assets/67046386/c3684a92-0058-4273-bda3-eb149d6e9e8b">

But I am not sure if this is correct interpretation of the issue.

**Comment by MyisCARRY** [comment]
@darshankawar Make your square smaller than whole screen

**Comment by darshankawar** [comment]
Sorry I don't completely understand. Please provide us a short video so that it'll be clear.
