### ISSUE TITLE
[quick_actions_ios] Xcode 16 beta 1: extension declares a conformance of imported type 'FlutterError' to imported protocols 'Error', 'Sendable'

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#150448]
"extension declares a conformance of imported type 'FlutterError' to imported protocols 'Error', 'Sendable'; this will not behave correctly if the owners of 'Flutter' introduce this conformance in the future"

```
- WARN  | xcodebuild:  packages/quick_actions/quick_actions_ios/ios/quick_actions_ios/Sources/quick_actions_ios/messages.g.swift:17:1: warning: extension declares a conformance of imported type 'FlutterError' to imported protocols 'Error', 'Sendable'; this will not behave correctly if the owners of 'Flutter' introduce this conformance in the future

- NOTE  | [iOS] xcodebuild:  | |- warning: extension declares a conformance of imported type 'FlutterError' to imported protocols 'Error', 'Sendable'; this will not behave correctly if the owners of 'Flutter' introduce this conformance in the future
- NOTE  | [iOS] xcodebuild:  | `- note: add '@retroactive' to silence this warning
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8744774106861819249/+/u/Run_package_tests/validate_iOS_and_macOS_podspecs/stdout

https://github.com/flutter/packages/blob/937038cd033d2c468f871a338ec893343a09ca04/packages/quick_actions/quick_actions_ios/ios/quick_actions_ios/Sources/quick_actions_ios/messages.g.swift#L17

[Swift Warning for Retroactive Conformances of External Types](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md)

Similar to https://github.com/flutter/flutter/issues/150391 though I'm not sure why it's a warning in this mode instead of an error.

**Comment by jmagman** [comment]
@tarrinneal do you know how this `extension` code is generated? I'm not spotting it in pigeon
https://github.com/flutter/packages/blob/937038cd033d2c468f871a338ec893343a09ca04/packages/quick_actions/quick_actions_ios/ios/quick_actions_ios/Sources/quick_actions_ios/messages.g.swift#L17
```swift
extension FlutterError: Error {}
```
In Xcode 16.0 beta 1 it seems to want this to be ["fully qualified" ](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md#source-compatibility):
```swift
extension FlutterError: Swift.Error {}
```
The implication is that generated pigeon Swift files with this pattern will generate a compilation warning.

**Comment by LouiseHsu** [comment]
@hellohuanlin

**Comment by jmagman** [comment]
> That line has changed, but the current version of it is here: https://github.com/flutter/packages/blob/937038cd033d2c468f871a338ec893343a09ca04/packages/pigeon/lib/swift_generator.dart#L842

You're saying the `extension` code isn't generated any more by pigeon? Does that mean I should just regenerate the code for this particular plugin?

**Comment by stuartmorgan** [comment]
It was never generated by Pigeon, it was something we recommended people do at the plugin level in Swift plugins in older versions of Pigeon. I can fix this in the plugin.

**Comment by jmagman** [comment]
> It was never generated by Pigeon, it was something we recommended people do at the plugin level in Swift plugins in older versions of Pigeon. I can fix this in the plugin.

So this wasn't "Autogenerated from Pigeon (v12.0.1), do not edit directly."? It was edited?

**Comment by tarrinneal** [comment]
That extension did use to exist, but we've since switched to using our own `PigeonError` instead. I'm not sure if that class needs the new code (probably does)

**Comment by tarrinneal** [comment]
you can see the old recommendations here packages/pigeon/example/README.md (this is the pr that added the new error class)

**Comment by jmagman** [comment]
I see, thanks for the clarification. I thought this code was autogenerated so required a pigeon update.

**Comment by stuartmorgan** [comment]
It should have been added in the code that used it rather than the generated file. We might have thought we were going to add it to the generator at that point?

But it turns out we aren't even using `FlutterError` in that plugin, so I'm not sure why it ended up in the PR at all 🤷🏻

**Comment by jmagman** [comment]
Thank you @stuartmorgan and @tarrinneal!
