### ISSUE TITLE
Expose MakeLazyImageFromTextureSource in dart:ui_web

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#150479]
### Use case

React Native Skia is using this API for video rendering on web, which results in binding the video element straight to the WebGL texture. Flutter web should do the same to accelerate video rendering into a texture.

### Proposal

Add MakeLazyImageFromTextureSource to ui_web. Would be superior to current available path #144591 and allow improvements to:

https://github.com/flutter/packages/pull/6286

**Comment by jezell** [comment]
For reference, here's the react native skia code which is used by their video player impl:

https://github.com/Shopify/react-native-skia/blob/main/package/src/skia/web/JsiSkImageFactory.ts#L56

They take advantage of a few other apis like:

MakeImageFromCanvasImageSource (#146088)

Which could also be useful.

```js

 MakeImageFromNativeBuffer(
    buffer: NativeBuffer,
    surface?: JsiSkSurface,
    image?: JsiSkImage
  ) {
    if (!isNativeBufferWeb(buffer)) {
      throw new Error("Invalid NativeBuffer");
    }
    if (!surface) {
      let img: Image;
      if (
        buffer instanceof HTMLImageElement ||
        buffer instanceof HTMLVideoElement ||
        buffer instanceof ImageBitmap
      ) {
        img = this.CanvasKit.MakeLazyImageFromTextureSource(buffer);
      } else if (buffer instanceof CanvasKitWebGLBuffer) {
        img = (
          buffer as CanvasKitWebGLBuffer as CanvasKitWebGLBufferImpl
        ).toImage();
      } else {
        img = this.CanvasKit.MakeImageFromCanvasImageSource(buffer);
      }
      return new JsiSkImage(this.CanvasKit, img);
    } else if (!image) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const img = (surface as any).makeImageFromTextureSource(buffer) as Image;
      return new JsiSkImage(this.CanvasKit, img);
    } else {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const img = (surface as any).updateTextureFromSource(
        image,
        buffer
      ) as Image;
      return new JsiSkImage(this.CanvasKit, img);
    }
  }
  ```

**Comment by jezell** [comment]
makeImageFromTextureSource / updateTextureFromSource here could be useful for #119649

**Comment by kevmoo** [comment]
Is this a PR you'd like to try @jezell ?

**Comment by jezell** [comment]
@kevmoo definitely can put one together if there is interest. Have it working locally already for canvaskit renderer.

**Comment by kevmoo** [comment]
@jezell – let me chat w/ the web team here. If you think the effort is more than a few hours, hold off until I get confirmation we have a good path here. Don't want anyone wasting time...

**Comment by jezell** [comment]
@kevmoo I already did the work locally, so not wasting much time to put together a PR :)
