### ISSUE TITLE
Wiki still references '--no-checked' mode

### ISSUE THREAD

**Issue by xqwzts** [flutter/flutter#15043]
https://github.com/flutter/flutter/wiki/Making-animated-GIFs-of-Flutter-apps

> Make sure to launch the app using --no-checked for faster performance.

Should probably be

> Make sure to launch the app using `flutter run --release` for faster performance.

[We can't submit PRs to the wiki]

**Comment by cbracken** [comment]
@xqwzts thanks for the issue! Done!

**Comment by xqwzts** [comment]
Thanks for the quick fix!
