### ISSUE TITLE
FlutterUndoManagerPlugin is not released causes the crash (when not initializing FlutterEngine in global scope)

### ISSUE THREAD

**Issue by dullgrass** [flutter/flutter#150408]
### Steps to reproduce

1. Enter the Flutter page,
2. manipulate the TextView, perform copy and paste operations, generate undo actions, 
3. exit the Flutter page, and then perform a three-finger slide to undo

### Expected results

not crash

### Actual results

crash，The root cause is that the FlutterUndoManagerPlugin is not released, while the FlutterEngine has already been released. Attempting to send a message to an object that has been released leads to a crash. In this scenario, the question is whether the FlutterUndoManagerDelegate within FlutterUndoManagerPlugin can be marked with weak.

### Code sample

```
@implementation [FlutterUndoManagerPlugin](https://api.flutter.dev/ios-embedder/interface_flutter_undo_manager_plugin.html) {
   id<FlutterUndoManagerDelegate> _undoManagerDelegate;
 }
  
 - (instancetype)initWithDelegate:(id<[FlutterUndoManagerDelegate](https://api.flutter.dev/ios-embedder/protocol_flutter_undo_manager_delegate-p.html)>)undoManagerDelegate {
   self = [super init];
  
   if (self) {
     // `_undoManagerDelegate` is a weak reference because it should retain FlutterUndoManagerPlugin.
     _undoManagerDelegate = undoManagerDelegate;
   }
  
   return self;
 }
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

none

**Comment by dullgrass** [comment]
![1718703139514](https://github.com/flutter/flutter/assets/6779357/f495cec7-6bbb-4903-8ee7-02f134a640e9)

**Comment by huycozy** [comment]
Hi @dullgrass 
It looks like you are on an [add-to-app](https://docs.flutter.dev/add-to-app) scenario, right? 

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample and the output of `flutter doctor -v` as well. Thanks!

**Comment by dullgrass** [comment]
[
[TestProject.zip](https://github.com/user-attachments/files/15887509/TestProject.zip)
](url)
this is the crash video

**Comment by dullgrass** [comment]
https://github.com/flutter/flutter/assets/6779357/6e69d48d-ec7d-4ca0-8ecc-15594f323f99

**Comment by dullgrass** [comment]
(base) ➜  my_flutter flutter doctor -v
[!] Flutter (Channel [user-branch], 3.13.9, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.13.9 on channel [user-branch] at /Users/wucuiping7/Desktop/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision d211f42860 (8 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wucuiping7/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (7 available)
    • iPhone 13 (mobile)                  • 00008110-00167C3621E2801E            • ios            • iOS 16.0 20A362
    • iPhone SE (3rd generation) (mobile) • 61441392-4FA3-440D-9D52-4CBBAAF60A88 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • iPhone 15 (mobile)                  • A03BDBD6-66DF-4F96-9C85-0E8DD7D38DF3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • iPhone 15 Pro (mobile)              • F40D3CD6-8621-48A0-B275-5089A1D0DF41 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • iPhone 15 Pro Max (mobile)          • 2C1C02E4-B64F-420D-A325-D62CACE75A66 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 126.0.6478.62
    ! Error: Browsing on the local area network for feng’s iPhone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for 大彪的IPM. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for yanming的iPhone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Looks like the sample code is incomplete. When I click on `Push to flutter` button, new screen is empty:

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/d48e7fe7-3064-4d3c-8d4b-6105d2ad093a
</details>

Also, I guess you embedded Flutter module using framework method, right? Since it's not CocoaPods method with flutter module project, I can't check if it works on the latest Flutter version or not (your current Flutter version is quite old), so please try upgrading your Flutter SDK to the latest stable 3.22.2 to see if the result has changed.

**Comment by dullgrass** [comment]
> ME1718764966248.mp4
Can you create a demo based on the video above? I don't have the latest version of Flutter, and from what I have seen, there seems to be an issue with the latest code. The FlutterUndoManagerPlugin's undomanagerdelegate gets released, but it's not set to  nil.https://api.flutter.dev/ios-embedder/_flutter_undo_manager_plugin_8mm_source.html  @huycozy

**Comment by dullgrass** [comment]
@implementation JMFlutterEngine

- (void)dealloc {
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        [[self valueForKey:@"undoManagerPlugin"] setValue:nil forKey:@"undoManagerDelegate"];
    });
}

@end
I have fix it ，by set nil like this，but not safe，so ，can you fix in flutter,I think add __weak maybe ok @huycozy 
@implementation FlutterUndoManagerPlugin {
__weak id _undoManagerDelegate;
}

**Comment by dongfeng52** [comment]
@huycozy    
I have recreated the demo project using the latest version of Flutter, but the crash issue still persists. Due to project size issues, I uploaded it to GitHub. You can download and try to reproduce this issue

https://github.com/dongfeng52/TestFlutter.git 
Xcode：15
Flutter：3.22.2

**Comment by huycozy** [comment]
I also tried with my sample project using CocoaPods and frameworks methods but couldn't reproduce the crash. 

https://github.com/huycozy/Flutter-iOS-native-Add-to-app-optionA/tree/undo-plugin-150408
https://github.com/huycozy/Flutter-iOS-native-Add-to-app-optionB/tree/undo-plugin-150408

@dullgrass @dongfeng52 Can you try with my sample code to see if the issue occurs on your side? 

https://github.com/flutter/flutter/assets/104349824/5adc7808-9dbe-48be-92c6-91331af7d0a0

**Comment by dongfeng52** [comment]
@huycozy  Comparing the diffs 
the differences are as follows
` @IBAction func openFlutterVC(_ sender: Any) {
        let flutterEngine = FlutterEngine(name: "my flutter engine")
        flutterEngine.run();
        GeneratedPluginRegistrant.register(with: flutterEngine);
        let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
        self.navigationController?.pushViewController(flutterViewController, animated: true)
        
//        if let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine {
//            let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)
//            self.navigationController?.pushViewController(flutterViewController, animated: true)
//            print("done")
//        }
    }`
You have used a global engine that will run throughout the entire lifecycle of the app.
If create a new engine every time you load the Flutter page. Repeat the above steps will trigger this issue.

**Comment by huycozy** [comment]
I see. I can reproduce the crash when initializing Flutter engine inside the method which is to transit to FlutterViewController.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (31 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.278, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.278 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c631d0855b (2 hours ago), 2024-06-19 20:29:41 -0400
    • Engine revision f9c497f178
    • Dart version 3.5.0 (build 3.5.0-281.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 126.0.6478.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by jmagman** [comment]
This changed in https://github.com/flutter/engine/pull/52234 but it looks like it's still happening on the master channel.  We should add an integration test for the full lifecycle.

**Comment by jmagman** [comment]
> the question is whether the FlutterUndoManagerDelegate within FlutterUndoManagerPlugin can be marked with weak.

Actually the delegate was already weak (the code you posted was MRC code and you can see it wasn't retained).  I migrated it to ARC in https://github.com/flutter/engine/pull/52234 and it's now explicitly weak, but I can still reproduce this.

The problem is that at the point of dealloc `_undoManagerDelegate.undoManager` is nil, which means it doesn't actually call `-removeAllActionsWithTarget`.
https://github.com/flutter/engine/blob/4bb4c1c2b5a60bb42ecdfde57ff98f001cea1f64/shell/platform/darwin/ios/framework/Source/FlutterUndoManagerPlugin.mm#L31

**Comment by jmagman** [comment]
Have a fix out at https://github.com/flutter/engine/pull/53553.  Thank you so much @huycozy and @dullgrass for figuring out the repro steps!
