### ISSUE TITLE
Multiple device debugging like native android

### ISSUE THREAD

**Issue by dipakravalVH** [flutter/flutter#150427]
### Use case

Please look on Multiple device debugging like native android

### Proposal

Please look on Multiple device debugging like native android

**Comment by danagbemava-nc** [comment]
Hi @dipakravalVH, at present you can run your app on multiple devices using the `flutter run -d all` command. You can also launch various instances of the app on the devices you want to test on. There's an issue to allow fine-grained control over the devices you want to run on. See https://github.com/flutter/flutter/issues/35733

Is there anything in particular you're requesting here? This is possible at present in flutter
