### ISSUE TITLE
Possibility to arrange SegmentedButton vertically

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#150416]
### Use case

I see that SegmentedButton are only ment to be horizontal, but we often see the need to arrange them vertically.
An example below (snipped from an android/kotlin app):
![image](https://github.com/flutter/flutter/assets/11217296/ae611a4a-9e2e-4801-94f9-70dd99ab99e9)

### Proposal

Please add a `direction` parameter in SegmentedButton, which turns the direction of the layout.
...such as this one, actually suggested from Gemini:

```
import 'package:flutter/material.dart';

// ...

SegmentedButton<int>(
  style: ButtonStyle(
    // Customize the button style for verticalorientation
    padding: MaterialStateProperty.all(EdgeInsets.symmetric(vertical: 12.0, horizontal: 8.0)),
    textStyle: MaterialStateProperty.all(TextStyle(fontSize: 16.0)),
    // Add more styling as needed
  ),
  segments: const <ButtonSegment<int>>[
    ButtonSegment<int>(value: 0, label: Text('Option 1')),
    ButtonSegment<int>(value: 1, label: Text('Option 2')),
    ButtonSegment<int>(value: 2, label: Text('Option 3')),
    // Add more segments as needed
  ],
  selected: <int>{0}, // Set initial selection
  onSelectionChanged: (Set<int> newSelection) {
    // Handle selection changes
    print('Selected segment: ${newSelection.first}');
  },
  direction: Axis.vertical, // Set the direction to vertical
)
```
![image](https://github.com/flutter/flutter/assets/11217296/2fde00e5-6e56-4824-95a1-fc81ac3006cf)

the call has been forwarded...

**Comment by huycozy** [comment]
In case we add support for this, there should be design spec accordingly, but it doesn't exist on M3 design as I can see: https://m3.material.io/components/segmented-buttons/specs.

Instead, I see [ToggleButtons](https://api.flutter.dev/flutter/material/ToggleButtons-class.html) has `direction` that you can try to see if it fits your case or not.

**Comment by RoarGronmo** [comment]
Could the suggestion be forwarded to the Material team then ?

**Comment by RoarGronmo** [comment]
ToggleButton is m2, cant see it is mentioned in m3. We are trying to
implement m3 in our projects from now on.

tir. 18. juni 2024, 13:41 skrev Huy ***@***.***>:

**Comment by TahaTesser** [comment]
This sounds reasonable. M3 SegmentedButton supports vertical orientation

| Preview | 
| --------------- | 
| <img src="https://github.com/flutter/flutter/assets/48603081/9a99c298-2f09-4551-b64f-531f2d7555eb" height="450" />	|

**Comment by abdalmonem** [comment]
Please assign me to this.
I already started working on.
