### ISSUE TITLE
ReferenceError: `Can't find variable: WebAssembly` and `Can't find variable: _flutter`

### ISSUE THREAD

**Issue by hpelitebook745G2** [flutter/flutter#150510]
### Steps to reproduce

1. Run `flutter create test`
   1.1. As of this writing, the `pubspec.yaml` has this version:
```
environment:
  sdk: '>=3.4.0 <4.0.0'
```
2. Run `flutter run -d chrome`
3. It will open Chrome browser with random port, i.e., `http://localhost:65194`
4. Copy and paste it on Safari
5. Error:
```
ReferenceError: Can't find variable: WebAssembly
```

In my not so old project's `pubspec.yaml`:
```
environment:
  sdk: ">=3.2.4 <4.0.0"
```
And the errors are:
```
ReferenceError: Can't find variable: WebAssembly
Unhandled Promise Rejection: ReferenceError: Can't find variable: _flutter
```

Safari version: `Version 17.5 (19618.2.12.11.6)`
MacOS version: `Sonoma 14.5`

### Expected results

It should run in Safari

### Actual results

The Flutter web app is not running in Safari regardless if `web-renderer` is `canvaskit` or `html`

### Code sample

<details open><summary>Code sample</summary>

```dart
No change in the code at all
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1176" alt="Screenshot 2024-06-19 at 10 53 55 PM" src="https://github.com/flutter/flutter/assets/27658429/a72765a0-9ec0-45ee-857c-d5cef480e207">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-SG)
    • Flutter version 3.22.2 on channel stable at /Users/test/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/test/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/test/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/test/Android
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79
      darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome
      126.0.6478.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by brainwo** [comment]
Safari (Webkit) has yet support WasmGC specification.

Check [this site](https://webassembly.org/features/), on "Garbage collection" feature.

**Comment by hpelitebook745G2** [comment]
I didn't run `flutter build web --wasm` so I'm curious why running the debug mode using `flutter run -d chrome` would cause this issue in the first place.

Also, according to the [warning in Flutter official documentation](https://docs.flutter.dev/platform-integration/web/wasm#chrome-119-or-later):

> Flutter compiled to Wasm can't run on the iOS version of any browser. All browsers on iOS are required to use WebKit, and can't use their own browser engine.

However the release build of my web app works fine in my iOS browsers. Only the debug mode of the web app has this error in Safari.

**Comment by huycozy** [comment]
@hpelitebook745G2 I couldn't reproduce this issue on my macOS 14.1 which has Safari Version 17.1 (19616.2.9.11.7). Could this occur due to cache issue somehow? Did you build with wasm before?

**Comment by hpelitebook745G2** [comment]
I believe I have, how do I confirm this and "clear" it @huycozy ?

**Comment by huycozy** [comment]
You can try on a newly created Flutter project to see if the issue also appears there or not

**Comment by hpelitebook745G2** [comment]
Actually this is a newly created Flutter project. I asked my colleague to create a new one but this error doesn't occur to him. So I'm wondering if this more of a global Flutter misconfiguration and not a project-specific.

**Comment by huycozy** [comment]
Below are steps I tried but couldn't reproduce the issue:

1. Build web with wasm: `flutter build web --wasm`
2. Run project with chrome: `flutter run -d chrome`. Then I have a web with a random port: http://localhost:59067/
3. Open http://localhost:59067/ in Safari browser

I would recommend you observe to see if there is a pattern to reproduce the issue and please share when you found it.

**Comment by Ashutosh-777** [comment]
Hey I need some help I have same error as you faced https://github.com/facebook/react-native/issues/32387#issue-1023040846
can you help tp fix this
