### ISSUE TITLE
Website deployment is broken

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#15057]
## Steps to Reproduce

We can no longer deploy changes to the website. Looks like it started happening at some point in the last 24 hours.
https://travis-ci.org/flutter/website/builds/348141735

```
Deploying to Firebase.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
...
⚠  Your CLI authentication needs to be updated to take advantage of new features.
⚠  Please run firebase login --reauth
Error: An unexpected error has occurred.
The command "./tool/travis.sh" exited with 2.
Done. Your build exited with 1.
```

**Comment by mit-mit** [comment]
cc @mjohnsullivan @filiph

**Comment by filiph** [comment]
I don't actually have access to the Firebase Hosting project, so I can't do `firebase login --reauth`. Who does? 

Once we find someone, it should be quite easy to ask them to run it, then provide us with a token which we then put to the Travis project settings.

**Comment by tvolkert** [comment]
Any update on this?

**Comment by mit-mit** [comment]
cc @sethladd who may have the 'keys' required for this

**Comment by tvolkert** [comment]
Technically, TODAY issues should block releases.  Since this doesn't block releases and it's now 13 days old, I'm removing the TODAY label.

**Comment by mit-mit** [comment]
The builds were broken when I filed this (nothing would deploy). @filiph did you fix it?

**Comment by filiph** [comment]
Yes. Sorry, I thought I updated  _some_ issue when I did, but evidently not this one.
