### ISSUE TITLE
[in_app_purchase][iOS] Not found ids

### ISSUE THREAD

**Issue by lugael** [flutter/flutter#150529]
### Steps to reproduce

 `Create model: PlanInformationEntity monthPlan = PlanInformationEntity(planId: 8, planName: 'Pacote Mensal', planStoreId: 'Product_id', planValue: 'R\$29,90');`

  ```
Future<bool> checkIfProductsactivated() async {
    final ProductDetailsResponse response = await inAppPurchase.queryProductDetails({
      monthPlan.planStoreId,
    });
    if (response.notFoundIDs.isNotEmpty) {
      return false;
    }
    products = response.productDetails.map((product) => PurchasableProduct(product)).toList();
    return true;
  }
```
  
  Even though the status of the product is ready for sale, it says it can't find the ID, the connection to the store returns true.

### Expected results

For a while now it has been finding the product, and nothing has been changed in the code, only the version of the package has been updated

### Actual results

Not found ids

### Code sample

<details open><summary>Code sample</summary>

```dart
Create model: PlanInformationEntity monthPlan = PlanInformationEntity(planId: 8, planName: 'Pacote Mensal', planStoreId: 'Product_id', planValue: 'R\$29,90');


  Future<bool> checkIfProductsactivated() async {
    final ProductDetailsResponse response = await inAppPurchase.queryProductDetails({
      monthPlan.planStoreId,
    });
    if (response.notFoundIDs.isNotEmpty) {
      return false;
    }
    products = response.productDetails.map((product) => PurchasableProduct(product)).toList();
    return true;
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.3.1 23D60 darwin-arm64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.90.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@lugael 
Is this occuring locally in debug mode or in TestFlight / app store version of your app ?
Can you provide the log that shows no ids found ?


> only the version of the package has been updated

Are you now on latest version of the package ? If so, check the changelog as there have been some updates made from iOS point of view: https://pub.dev/packages/in_app_purchase/changelog#320

If this is occuring in TestFlight only, then check if you have accepted to become a tester for CLOSED TRACK AND INTERNAL TRACK if it applies in your case or not.
