### ISSUE TITLE
[Windows] Flutter does not render any GUI and shows black window instead

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#150546]
3 years ago i created this issue: https://github.com/flutter/flutter/issues/89583. It was only relevant for Windows 7/8 users. However, since the last flutter stable update, i can see that this problem is present on Windows 10/11 users. 

UI Is not rendered, however, all the buttons are clickable (cursor changes when you hover button's location and if you add some winapi messagebox, it appears on the screen).

I have no idea how to debug this since this issue is present on small amount of PCs and i myself do not face this problem. **Any ideas on debugging on PC without flutter?** 

![image](https://github.com/flutter/flutter/assets/63228361/8cdf9b96-dd76-4b13-a38e-965a59caa909)

I tried to fix this with d3dcompiler_47.dll (that helped on Windows 7), but it does not help anymore.

![image](https://github.com/flutter/flutter/assets/63228361/2e3866cb-4fff-47f3-aa68-adf2b3fc83f9)
![image](https://github.com/flutter/flutter/assets/63228361/7a82eba5-50b3-42b8-8673-c895fdfd564b)
![image](https://github.com/flutter/flutter/assets/63228361/a8016320-7a2c-4051-bb8e-87dbb5dbcce9)
![image](https://github.com/flutter/flutter/assets/63228361/55c7e925-7678-42ba-960a-fcfb6f820f03)

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}

```

**Comment by huycozy** [comment]
>So i managed to download flutter to that PC and here is flutter run --verbose result:

What is Flutter version you installed on that machine? Can you share the output of `flutter doctor -v`?

Also, can you check hardware information of that device? (processor, graphics card) and also some experimental settings for  monitor/display as well.

**Comment by kirill-21** [comment]
> > So i managed to download flutter to that PC and here is flutter run --verbose result:
> 
> What is Flutter version you installed on that machine? Can you share the output of `flutter doctor -v`?
> 
> Also, can you check hardware information of that device? (processor, graphics card) and also some experimental settings for monitor/display as well.

The latest stable version from website, as for hardware, I sent it in the initial message inside the screenshots

**Comment by huycozy** [comment]
I can't reproduce this on my Windows 10 machine. Will label this for other's insights.

**Comment by D-extremity** [comment]
Replace your `void main()` code with below code
```
void main() async {

  await windowManager.ensureInitialized();

  WindowOptions windowOptions = const WindowOptions(
    maximumSize: Size(400, 500),
    minimumSize: Size(400, 500),
    size: Size(400, 500),
    center: true,
    backgroundColor: Colors.blue,
    skipTaskbar: false,
    titleBarStyle: TitleBarStyle.normal,
  );
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });

```

**Comment by kirill-21** [comment]
You sure this is native Flutter code? 
![image](https://github.com/flutter/flutter/assets/63228361/b3e22c9e-bc47-4103-80d2-df0989508668)


> Replace your `void main()` code with below code
> 
> ```
> void main() async {
> 
>   await windowManager.ensureInitialized();
> 
>   windowManager.waitUntilReadyToShow(windowOptions, () async {
>     await windowManager.show();
>     await windowManager.focus();
>   });
> }
> ```

**Comment by D-extremity** [comment]
> You sure this is native Flutter code? If this is a package, why would i add a package to my project? ![image](https://private-user-images.githubusercontent.com/63228361/341761399-b3e22c9e-bc47-4103-80d2-df0989508668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzM4MDQsIm5iZiI6MTcxODk3MzUwNCwicGF0aCI6Ii82MzIyODM2MS8zNDE3NjEzOTktYjNlMjJjOWUtYmM0Ny00MTAzLTgwZDItZGYwOTg5NTA4NjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEyMzgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODM4NGZlZDNiODNmNTcxNzdhYzc2MWFjZTQ3OTIzNTJhZTEzNjkyNDlmOGUxMGE1ZDJjMTY4YWY5ZDJhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usMgGrdCj8CzHrgNsXWWZZhmaAXpjwWSgbl9HYJLpRI)
> 
> > Replace your `void main()` code with below code
> > ```
> > void main() async {
> > 
> >   await windowManager.ensureInitialized();
> > 
> >   windowManager.waitUntilReadyToShow(windowOptions, () async {
> >     await windowManager.show();
> >     await windowManager.focus();
> >   });
> > }
> > ```

add https://pub.dev/packages/window_manager

**Comment by kirill-21** [comment]
> > You sure this is native Flutter code? If this is a package, why would i add a package to my project? ![image](https://private-user-images.githubusercontent.com/63228361/341761399-b3e22c9e-bc47-4103-80d2-df0989508668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzM4MDQsIm5iZiI6MTcxODk3MzUwNCwicGF0aCI6Ii82MzIyODM2MS8zNDE3NjEzOTktYjNlMjJjOWUtYmM0Ny00MTAzLTgwZDItZGYwOTg5NTA4NjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEyMzgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODM4NGZlZDNiODNmNTcxNzdhYzc2MWFjZTQ3OTIzNTJhZTEzNjkyNDlmOGUxMGE1ZDJjMTY4YWY5ZDJhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usMgGrdCj8CzHrgNsXWWZZhmaAXpjwWSgbl9HYJLpRI)
> > > Replace your `void main()` code with below code
> > > ```
> > > void main() async {
> > > 
> > >   await windowManager.ensureInitialized();
> > > 
> > >   windowManager.waitUntilReadyToShow(windowOptions, () async {
> > >     await windowManager.show();
> > >     await windowManager.focus();
> > >   });
> > > }
> > > ```
> 
> add https://pub.dev/packages/window_manager

I don't think i need some package, there is some problem inside the SDK that we need to debug deeper and fix it

**Comment by D-extremity** [comment]
> > > You sure this is native Flutter code? If this is a package, why would i add a package to my project? ![image](https://private-user-images.githubusercontent.com/63228361/341761399-b3e22c9e-bc47-4103-80d2-df0989508668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzM4MDQsIm5iZiI6MTcxODk3MzUwNCwicGF0aCI6Ii82MzIyODM2MS8zNDE3NjEzOTktYjNlMjJjOWUtYmM0Ny00MTAzLTgwZDItZGYwOTg5NTA4NjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEyMzgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODM4NGZlZDNiODNmNTcxNzdhYzc2MWFjZTQ3OTIzNTJhZTEzNjkyNDlmOGUxMGE1ZDJjMTY4YWY5ZDJhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usMgGrdCj8CzHrgNsXWWZZhmaAXpjwWSgbl9HYJLpRI)
> > > > Replace your `void main()` code with below code
> > > > ```
> > > > void main() async {
> > > > 
> > > >   await windowManager.ensureInitialized();
> > > > 
> > > >   windowManager.waitUntilReadyToShow(windowOptions, () async {
> > > >     await windowManager.show();
> > > >     await windowManager.focus();
> > > >   });
> > > > }
> > > > ```
> > 
> > 
> > add https://pub.dev/packages/window_manager
> 
> I don't think i need some package, there is some problem inside the SDK that we need to debug deeper and fix it

Sample code you have provided is working fine on my system and recently i have made windows app using flutter which is working fine on 600+ systems .

Try  adding `WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();`

though it might be an issue, team will look after it :)

**Comment by kirill-21** [comment]
> > > > You sure this is native Flutter code? If this is a package, why would i add a package to my project? ![image](https://private-user-images.githubusercontent.com/63228361/341761399-b3e22c9e-bc47-4103-80d2-df0989508668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzM4MDQsIm5iZiI6MTcxODk3MzUwNCwicGF0aCI6Ii82MzIyODM2MS8zNDE3NjEzOTktYjNlMjJjOWUtYmM0Ny00MTAzLTgwZDItZGYwOTg5NTA4NjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEyMzgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODM4NGZlZDNiODNmNTcxNzdhYzc2MWFjZTQ3OTIzNTJhZTEzNjkyNDlmOGUxMGE1ZDJjMTY4YWY5ZDJhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.usMgGrdCj8CzHrgNsXWWZZhmaAXpjwWSgbl9HYJLpRI)
> > > > > Replace your `void main()` code with below code
> > > > > ```
> > > > > void main() async {
> > > > > 
> > > > >   await windowManager.ensureInitialized();
> > > > > 
> > > > >   windowManager.waitUntilReadyToShow(windowOptions, () async {
> > > > >     await windowManager.show();
> > > > >     await windowManager.focus();
> > > > >   });
> > > > > }
> > > > > ```
> > > 
> > > 
> > > add https://pub.dev/packages/window_manager
> > 
> > 
> > I don't think i need some package, there is some problem inside the SDK that we need to debug deeper and fix it
> 
> Sample code you have provided is working fine on my system and recently i have made windows app using flutter which is working fine on 600+ systems .
> 
> Try adding `WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();`
> 
> though it might be an issue, team will look after it :)

I have an with ~40000 daily users, for major amount of users the app is working, but not for everyone. Please, do not reply with such advices. I already reported the error from the console

**Comment by RafaelTadeuSilva** [comment]
Hi, I have the same problem.
3.19 works in all machines, but in 3.22.2, a few Windows PCs show black screen, just as shown in the screenshots already posted.
I don't have many clients, but it's happening in 4 machines of different clientes with different windows version.
Right now I will try downgrading back to 3.19.

**Comment by RafaelTadeuSilva** [comment]
I have tested after the downgrade and worked. I created a basic flutter counter project on 3.22.2 stable and I has the same black screen error on the same machines.

**Comment by AlejandroGrana** [comment]
What i see in common, is "old/limited hardware".
Apparently, it could be related to the lack of Vulkan support in the hardware, i'm not sure.
In my case, it works with "not too old 2016" hardware RX 380, but doesn't in an old Nvidia FX 1800.
I have not been able to find some "clear" information about the graphics API requirements (my fail probably) in the docs, but, in the README of the Impeller engine, there are references to Vulkan/Open GL ES 2.0.

**Comment by mohammadjalalis** [comment]
Hi,
It is related to the old PCs. (Core 2 due CPUs).
Several clients reported this problem. 
This problem has occured since version 3.22 .
![Screenshot (26)](https://github.com/flutter/flutter/assets/32570964/0d876aaf-7e79-40dc-a7af-1e752a83a73c)

**Comment by ChetSocio** [comment]
Hello guys, yes, the latest flutter version 3.22 throws 
`Flutter run by flutter_windows_3.22.6-stable but show Fatal GL Error GL_INVALID_VALUE(1281) `
on low end pcs (tried on core 2 duo pcs ) so this version not an optimal choice for desktop development future. I checked and 3.19 is the last version that works fine for windows development now but for how long? Core 2 duo holds strong market globally and still the common choice. In the name of improvement, the flutter team just thrown a blocking update and that makes impossible to support low end devices. Hope they will soon solve it.

**Comment by ChetSocio** [comment]
> Same problem here. We released a Windows app version 4 hours ago, upgrading flutter version from 3.19.6 to 3.22.2, and 5 end users already contacted us about these black screen problems, all of them using old cpus (Pentium P6100, Core 2 Duo).

Don't use 3.22, 3.19 is good enough for now. Maybe they will solve this problem in next releases. Otherwise its best to migrate to other framework for desktop development due to lack of support in flutter for old devices.  Sadly flutter team doesnot consider this issue as serious as this github issue contains more complaints than any responsible reply from team .

**Comment by jonahwilliams** [comment]
If you are experiencing this issue and can easily reproduce it locally, could you try the 3.24 beta. This contains a fix for windows rendering with the software backend. I do not know if that will fix this problem but it will help us narrow down the issue if you report back success/failure.

**Comment by AlejandroGrana** [comment]
In my case, same  GL_INVALID_VALUE error with 3.24.0-0.1.pre.   
It would be useful to know the hardware requirements to run the Inpeller engine on PC.   
Graphic hardware: Nvidia FX1800 (no opencl, directml, cuda or vulkan, only opengl 3.3) with latest drivers available 342.01.   
   
[FATAL:..\flutter/impeller/renderer/backend/gles/proc_table_gles.h(39)] Fatal GL Error GL_INVALID_VALUE(1281) encountered on call to glTexImage2D

**Comment by jonahwilliams** [comment]
> It would be useful to know the hardware requirements to run the Inpeller engine on PC.

There are no requirements at this point because Impeller is not available on windows.

**Comment by AlejandroGrana** [comment]
Ups, my fault, sorry.   
I think its actually some confusing.   
Maybe, something was broken at some point.   
   
[Issue Fix Windows support](https://github.com/orgs/flutter/projects/21/views/1?pane=issue&itemId=49860788)  

Actually, I'm not very positive if the GL error is related to the black screen.   
My knowledge about the rendering engine is none, so, I will stop adding noise.   
Debug it is too complicated for me.   
Let me know if I can test it in any other way to add more info to the developers.   
Thank you.

**Comment by loic-sharma** [comment]
Hello everyone, could you try running these counter apps and telling us if they are still affected by the problem?

Name | Test app | Notes 
-- | -- | --
`no_compositor` | [Download](https://github.com/user-attachments/files/16419762/no_compositor.zip) | This rolls back rendering changes we did for multi-window and platform views. If this reproduces the issue, the rendering changes we did is the problem.<br/><br/>Engine fork: https://github.com/loic-sharma/flutter-engine/tree/issue_150546_no_compositor
`force_software` | [Download](https://github.com/user-attachments/files/16419771/force_software.zip) | This forces the app to use the software backend. If this reproduces the issue, the software backend is the problem.<br/><br/>Engine fork: https://github.com/loic-sharma/flutter-engine/tree/issue_150546_software_backend

Thank you for the help, we very much appreciate it!

**Comment by AlejandroGrana** [comment]
Hi!!   
Both apps work correctly.   
Thank you.

**Comment by JiaoLiu** [comment]
> Hello everyone, could you try running these counter apps and telling us if they are still affected by the problem?
> 
> Name	Test app	Notes
> `no_compositor`	[Download](https://github.com/user-attachments/files/16419805/no_compositor.zip)	This rolls back rendering changes we did for multi-window and platform views. If this fixes the issue, the rendering changes we did is the problem.
> 
> Engine fork: https://github.com/loic-sharma/flutter-engine/tree/issue_150546_no_compositor
> `force_software`	[Download](https://github.com/user-attachments/files/16419798/force_software.zip)	This forces the app to use the software backend. If this reproduces the issue, the software backend is the problem.
> 
> Engine fork: https://github.com/loic-sharma/flutter-engine/tree/issue_150546_software_backend
> Thank you for the help, we very much appreciate it!

no_compositor not working, force_software works when GPU is not functioning.
![4921722304137_ pic](https://github.com/user-attachments/assets/47cd0c8d-06f1-4707-bbb0-1b966670a624)
![4931722304182_ pic](https://github.com/user-attachments/assets/cc766fee-e9ea-45eb-a150-13e9ad3d9ef7)

**Comment by yaminet1024** [comment]
Hi, everyone, I have changed GL_RGBA8 to GL_RGBA in [flutter/engine/shell/platform/windows/compositor_opengl.cc#L61C8-L61C18](https://github.com/flutter/engine/blob/d637a5b31fa1b95d6f76593aefc33d08ac4646af/shell/platform/windows/compositor_opengl.cc#L61C8-L61C18). This change helped resolve the issue for me. You can run this counter app to test if the problem is resolved:

http://dldir1.qq.com/wework/work_weixin/test/counter.zip

**Comment by loic-sharma** [comment]
@AlejandroGrana and @JiaoLiu could you try both the `baseline` and `rgba_internal_format` variants [above](https://github.com/flutter/flutter/issues/150546#issuecomment-2257132661) and let me know the results?

**Comment by AlejandroGrana** [comment]
Hi.   
   
The baseline shows a black window.   
The rgba_internal_format works normally.   
GL_INVALID_VALUE error is not reported on any variant.   
   
Thanks!!

**Comment by JiaoLiu** [comment]
> Hi, everyone, I have changed GL_RGBA8 to GL_RGBA in [flutter/engine/shell/platform/windows/compositor_opengl.cc#L61C8-L61C18](https://github.com/flutter/engine/blob/d637a5b31fa1b95d6f76593aefc33d08ac4646af/shell/platform/windows/compositor_opengl.cc#L61C8-L61C18). This change helped resolve the issue for me. You can run this counter app to test if the problem is resolved:
> 
> http://dldir1.qq.com/wework/work_weixin/test/counter.zip

http://dldir1.qq.com/wework/work_weixin/test/counter.zip  still blank screen.
![WX20240731-110709@2x](https://github.com/user-attachments/assets/0faa9779-6ca7-4d69-b6d5-3b6327abd362)

**Comment by yaminet1024** [comment]
> > Hi, everyone, I have changed GL_RGBA8 to GL_RGBA in [flutter/engine/shell/platform/windows/compositor_opengl.cc#L61C8-L61C18](https://github.com/flutter/engine/blob/d637a5b31fa1b95d6f76593aefc33d08ac4646af/shell/platform/windows/compositor_opengl.cc#L61C8-L61C18). This change helped resolve the issue for me. You can run this counter app to test if the problem is resolved:
> > http://dldir1.qq.com/wework/work_weixin/test/counter.zip
> 
> http://dldir1.qq.com/wework/work_weixin/test/counter.zip still blank screen. ![WX20240731-110709@2x](https://private-user-images.githubusercontent.com/4370982/353677032-0faa9779-6ca7-4d69-b6d5-3b6327abd362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTgwNDAsIm5iZiI6MTcyMjM5Nzc0MCwicGF0aCI6Ii80MzcwOTgyLzM1MzY3NzAzMi0wZmFhOTc3OS02Y2E3LTRkNjktYjZkNS0zYjYzMjdhYmQzNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMDM0OTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg0YTVkZGYwNTUwZmY3NTkyZGQ3NzliNjBjYmZmOTRmNzc4NTY3NmMxZjQzZGQ3NzM4NzBhMTczNmI4ODkwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T_F58nWQxlDJGviu48BA217bPTQ2JlMPhDeY-Hri_Gw)

It seems this is not the same issue as we encountered; we are getting a blank window.

**Comment by JemmyWang94** [comment]
I also encountered the same problem. The system is Windows Enterprise Edition, kernel 19045.4651 operating system kernel. 3.19.6 is fine, but 3.22.3 appears for a while. The window background color is specified through WindowOptions of WindowManager. After starting the project, the window with the set background color is displayed for a while and then crashes.
await windowManager.ensureInitialized();

WindowOptions windowOptions = const WindowOptions(
center: true,
backgroundColor: Colors.black,
skipTaskbar: false,
titleBarStyle: TitleBarStyle.hidden,
);
await windowManager.waitUntilReadyToShow(windowOptions, () async {
await windowManager.show();
await windowManager.focus();
});
The error message is the same:
[FATAL:..\flutter/impeller/renderer/backend/gles/proc_table_gles.h(39)] Fatal GL Error GL_INVALID_VALUE(1281) encountered on call to glTexImage2D
Lost connection to device.
Perhaps you can try to download the same system operation.

**Comment by JemmyWang94** [comment]
> Hello everyone, could you try running these counter apps and telling us if they are still affected by the problem?
> 
> Name	Test app	Notes
> `baseline`	[Download](https://github.com/user-attachments/files/16432828/baseline.zip)	This is a recent engine commit that the other variants are built on. This should reproduce the issue.
> 
> Engine commit: [flutter/engine@6613428](https://github.com/flutter/engine/commit/66134286d6a4ed397785c84cf4e0f72b8886788f)
> `no_compositor`	[Download](https://github.com/user-attachments/files/16419805/no_compositor.zip)	This rolls back rendering changes we did for multi-window and platform views. If this fixes the issue, the rendering changes we did is the problem.
> 
> Engine fork: https://github.com/loic-sharma/flutter-engine/tree/issue_150546_no_compositor
> `force_software`	[Download](https://github.com/user-attachments/files/16419798/force_software.zip)	This forces the app to use the software backend. If this reproduces the issue, the software backend is the problem.
> 
> Engine fork: https://github.com/loic-sharma/flutter-engine/tree/issue_150546_software_backend
> `rgba_internal_format`	[Download](https://github.com/user-attachments/files/16432988/rgba_internal_format.zip)	This loosens the texture format requirements and increases the number of devices Flutter Windows is compatible with. Kudos to @yaminet1024 for the [suggestion](https://github.com/flutter/flutter/issues/150546#issuecomment-2257786250).
> 
> Engine fork: https://github.com/loic-sharma/flutter-engine/tree/issue_150546_rgba_internal_format
> Thank you for the help, we very much appreciate it!

I tried running these projects, and after running baseLine, it showed a black background and the title bar displayed normally without crashing. The other three are running normally.

**Comment by loic-sharma** [comment]
Hello everyone, I'd like to test a new potential fix. Could you [download](https://github.com/user-attachments/files/16473925/bgra_format.zip) this app and tell me if it works as expected?

If this fix works for everyone, I'll land it! cc @kirill-21 @RafaelTadeuSilva @olerhan @AlejandroGrana 
@yaminet1024 @JemmyWang94

**Comment by kirill-21** [comment]
> Hello everyone, I'd like to test a new potential fix. Could you [download](https://github.com/user-attachments/files/16473925/bgra_format.zip) this app and tell me if it works as expected?
> 
> If this fix works for everyone, I'll land it! cc @kirill-21 @RafaelTadeuSilva @olerhan @AlejandroGrana @yaminet1024 @JemmyWang94

Working, great!

**Comment by RafaelTadeuSilva** [comment]
> Hello everyone, I'd like to test a new potential fix. Could you [download](https://github.com/user-attachments/files/16473925/bgra_format.zip) this app and tell me if it works as expected?
> 
> If this fix works for everyone, I'll land it! cc @kirill-21 @RafaelTadeuSilva @olerhan @AlejandroGrana @yaminet1024 @JemmyWang94

Sorry about the delay, we have to test it on our client's computer.
This worked, the other fixes we couldn't test yet.

**Comment by AlejandroGrana** [comment]
> Hello everyone, I'd like to test a new potential fix. Could you [download](https://github.com/user-attachments/files/16473925/bgra_format.zip) this app and tell me if it works as expected?
> 
> If this fix works for everyone, I'll land it! cc @kirill-21 @RafaelTadeuSilva @olerhan @AlejandroGrana @yaminet1024 @JemmyWang94

It works for me!!
Thank you!!

**Comment by loic-sharma** [comment]
Thanks everyone, I really appreciate all the help 💙

**Comment by JemmyWang94** [comment]
> Hello everyone, I'd like to test a new potential fix. Could you [download](https://github.com/user-attachments/files/16473925/bgra_format.zip) this app and tell me if it works as expected?
> 
> If this fix works for everyone, I'll land it! cc @kirill-21 @RafaelTadeuSilva @olerhan @AlejandroGrana @yaminet1024 @JemmyWang94

It runs well.

**Comment by kirill-21** [comment]
> Thanks everyone, I really appreciate all the help 💙

When will it be merged into the stable sdk?

**Comment by pankaj-nikam** [comment]
I thought today's release would have the fix however it is not; it will be nice to know the timeline for the same.

Thanks.

**Comment by JusticeWay** [comment]
> Hello everyone, I'd like to test a new potential fix. Could you [download](https://github.com/user-attachments/files/16473925/bgra_format.zip) this app and tell me if it works as expected?
> 
> If this fix works for everyone, I'll land it! cc @kirill-21 @RafaelTadeuSilva @olerhan @AlejandroGrana @yaminet1024 @JemmyWang94

Work

**Comment by JiaoLiu** [comment]
> Hello everyone, I'd like to test a new potential fix. Could you [download](https://github.com/user-attachments/files/16473925/bgra_format.zip) this app and tell me if it works as expected?
> 
> If this fix works for everyone, I'll land it! cc @kirill-21 @RafaelTadeuSilva @olerhan @AlejandroGrana @yaminet1024 @JemmyWang94

still blank screen when gpu is disabled.

**Comment by kirill-21** [comment]
Waiting for this to be merged into the stable sdk

**Comment by loic-sharma** [comment]
This fix will be included in the next stable release. Thanks everyone for the help!

**Comment by kirill-21** [comment]
> This fix will be included in an upcoming stable release. Thanks everyone for the help!

Is there any info when this stable release will be published?

**Comment by thanhle7** [comment]
> > This fix will be included in an upcoming stable release. Thanks everyone for the help!
> 
> Is there any info when this stable release will be published? Everyone is waiting for it) Btw can this already by used on beta/dev/master?

I am second for this. I have some PCs yet using core 2 duo.

**Comment by thanhle7** [comment]
While waiting for the updated release on the issue, my temporary solution is to disable NVIDIA display adapter.

**Comment by kirill-21** [comment]
If anybody wants to build app with 3.24 flutter version and with fix for this issue, then type this:
```
flutter channel flutter-3.24-candidate.0
flutter upgrade
```
and build your project with fixed engine version! (Until stable is released)

**Comment by loic-sharma** [comment]
Hello everyone, the [Flutter 3.24.1 stable release](https://github.com/flutter/flutter/blob/stable/CHANGELOG.md#3241) has the fix! Please [upgrade to the latest Flutter SDK](https://docs.flutter.dev/release/upgrade) to get the fix!

**Comment by Cannon99** [comment]
Flutter v3.24.1 resolve the issue!

**Comment by thanhle7** [comment]
> Flutter v3.24.1 resolved the issue!

Confirmed :)

**Comment by olerhan** [comment]
I am sorry to late. I have upgraded Flutter to v3.24.2 from v3.19. The problem has resolved on my old windows PC. Thank you!

**Comment by pedroaraujofrontsys** [comment]
I have upgraded to Flutter v3.24.2 to. The problem has solved on my PC.
Thank!
