### ISSUE TITLE
Build error in `sync_switch.cc` on Clang-16 with GCC 14 stdlib.

### ISSUE THREAD

**Issue by johnoneil** [flutter/flutter#150515]
### Steps to reproduce

This is reproducible on certain setups building with `Clang++-16` using GCC 14 C++ stdlib backend.

For example:

```
clang++-16 -v
Debian clang version 16.0.6 (20)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/14
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/14
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

Building in this configuration results in error:

```
/usr/bin/clang++-16 -DIMPELLER_DEBUG=1 -DIMPELLER_ENABLE_3D=1 -I/mnt/sda/code/display-safety/crates/impeller-rs/impeller-cmake -I/mnt/sda/code/display-safety/crates/impeller-rs/impeller-cmake/third_party/abseil-cpp -I/mnt/sda/code/display-safety/crates/impeller-rs/impeller-cmake/third_party -g -std=gnu++20 -MD -MT CMakeFiles/fml.dir/third_party/flutter/fml/synchronization/sync_switch.cc.o -MF CMakeFiles/fml.dir/third_party/flutter/fml/synchronization/sync_switch.cc.o.d -o CMakeFiles/fml.dir/third_party/flutter/fml/synchronization/sync_switch.cc.o -c /mnt/sda/code/display-safety/crates/impeller-rs/impeller-cmake/third_party/flutter/fml/synchronization/sync_switch.cc
  /mnt/sda/code/display-safety/crates/impeller-rs/impeller-cmake/third_party/flutter/fml/synchronization/sync_switch.cc:48:7: error: no matching function for call to 'find'
    if (std::find(observers_.begin(), observers_.end(), observer) ==
        ^~~~~~~~~
  /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/streambuf_iterator.h:435:5: note: candidate template ignored: could not match 'istreambuf_iterator' against '__normal_iterator'
      find(istreambuf_iterator<_CharT> __first,
      ^
  /mnt/sda/code/display-safety/crates/impeller-rs/impeller-cmake/third_party/flutter/fml/synchronization/sync_switch.cc:56:52: error: too many arguments to function call, expected single argument '__filename', have 3 arguments
    observers_.erase(std::remove(observers_.begin(), observers_.end(), observer),
                     ~~~~~~~~~~~                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/stdio.h:152:12: note: 'remove' declared here
  extern int remove (const char *__filename) __THROW;
             ^
  2 errors generated.
```

As `sync_switch.cc` refers to functions defined in `<algorithm>` I think the header should be present on all platforms.

### Expected results

Build should complete without error.

### Actual results

Error quoted above.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @johnoneil 
Can you share steps to reproduce the error? [`clang++` is used by default](https://github.com/flutter/flutter/blob/64dd1ca9bc32fbc767a3f63e4c9c5ae2fc355380/packages/flutter_tools/lib/src/linux/build_linux.dart#L169C15-L169C22), I wonder how you build app with a specific clang version? Is there only one version on your system?

What is your Flutter version? (please provide the output of `flutter doctor -v`) 

And please provide the output of `flutter run -v` as well, thanks! (If the log is too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it)
