### ISSUE TITLE
Can not preview and search icon on new page of `Updating-Material-Design-Fonts-&-Icons.md` after wiki migration

### ISSUE THREAD

**Issue by zengfanfan** [flutter/flutter#150595]
### Steps to reproduce

visit https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons

### Expected results

a site show up, where i can search and preview icons.

### Actual results

nop, nothing! 
i am sure i can do it someday ago.

### Code sample

> unnecessary

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/8079595/c122ebe1-cc70-4462-a486-562c3a875dfc)

</details>

### Logs

<details open><summary>Logs</summary>

> unnecessary

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

> unnecessary

</details>

**Comment by huycozy** [comment]
I've never visited that wiki page so I'm not sure what it looked like before. I also have no idea which team can take on this issue, adding `will need additional triage` label.

**Comment by goderbauer** [comment]
Are you maybe looking for https://api.flutter.dev/flutter/material/Icons-class.html? It has a list of all the icons with a preview. As far as I know this information was never in the wiki.

**Comment by zengfanfan** [comment]
sorry, my bad.
It's here: https://material.io/resources/icons
