### ISSUE TITLE
flutter_plugin_android_lifecycle NOT COMPATIBLE WITH ANDROID GRADLE PLUGIN 8.5.0 

### ISSUE THREAD

**Issue by SANJISH-KUMAR** [flutter/flutter#150512]
My flutter app , is able to build an apk and run on the emulator successfully but gives errors while building(./gradlew clean build)
 eg flutter_plugin_android_lifecycle plugin NOT COMPATIBLE WITH ANDROID GRADLE PLUGIN 8.5.0. I am using version 2.0.20 which is the latest version

**Comment by darshankawar** [comment]
@SANJISH-KUMAR 
Please provide complete error log in properly formatted text along with `flutter doctor -v` and your gradle wrapper version.
Does this error occur only in your own project or if you create a new flutter project and try to build an apk throws same error ?
