### ISSUE TITLE
Some doc comments refer to unknown, or out of scope, code identifiers.

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#150562]
Here's the main list. Some just need to use backticks instead of square brackets. Some should just not have square brackets. Some are typos. Some need broader textual refactoring:

- [x] * `DragGestureRecognizer.onCancel` - property referencing `allowedButtonsFilter`.
- [x] * `DragGestureRecognizer.onDown` - property referencing `allowedButtonsFilter`.
- [x] * `DragGestureRecognizer.onEnd` - property referencing `allowedButtonsFilter`.
- [x] * `DragGestureRecognizer.onStart` - property referencing `allowedButtonsFilter`.
- [x] * `DragGestureRecognizer.onUpdate` - property referencing `allowedButtonsFilter`.
- [x] * `DoubleTapGestureRecognizer.onDoubleTap` - property referencing `allowedButtonsFilter`.
- [x] * `DoubleTapGestureRecognizer.onDoubleTapCancel` - property referencing referencing `allowedButtonsFilter`.
- [x] * `DoubleTapGestureRecognizer.onDoubleTapDown` - property referencing `allowedButtonsFilter`.
- [x] * `TapGestureRecognizer` - class referencing `allowedButtonsFilter`.
- [x] * `Badge.backgroundColor` - property referencing `ColorScheme.errorColor`.
- [x] * `ButtonThemeData.padding` - property referencing `button`.
- [x] * `ButtonThemeData.shape` - property referencing `button`.
- [x] * `InkSparkle` - class referencing `containedInkWell`.
- [x] * `InkSparkle` - class referencing `rectCallback`.
- [x] * `InkSparkle.splashFactory` - static const field referencing `turbulenceSeed`.
- [x] * `InkSparkle.constantTurbulenceSeedSplashFactory` - static const field referencing `turbulenceSeed`.
- [x] * `Switch.adaptive` - constructor referencing `ThemeData.adaptations`.
- [x] * `TextButton.defaultStyleOf` - method referencing `padding`.
- [x] * `Adaptation.adapt` - method referencing `ThemeData.adaptations`.
- [x] * `UndoManager` - Class referencing `canRedo`.
- [x] * `UndoManager` - Class referencing `canUndo`.
- [x] * `ContextMenuController.markNeedsBuild` - method referencing `contextMenuBuilder`.
- [x] * `SliverFadeTransition` - class referencing `sliver`.

And some just refer to not-properly-prefixed elements. These can be updated with a prefix:

- [x] * `ImageInfo.clone` - method referencing `Image.clone`.
- [x] * `ImageInfo.isCloneOf` - method referencing `Image.isCloneOf`.
- [x] * `RawImage` - class referencing `Image.dispose`.
- [x] * `RawImage.image` - property referencing `Image.dispose`.

And some just refer to not-imported elements. These can be updated with `@docImport`:

- [x] * `DiagnosticsNode.toTimelineArguments` - method referencing `Timeline.startSync`.
- [x] * `compute` - top-level function referencing `Isolate.run`.

**Comment by srawlins** [comment]
CC @goderbauer

**Comment by goderbauer** [comment]
I am so excited! Turned the top-level comment into a checklist so we can keep track of what has been fixed. Do you want help with any of these?

**Comment by goderbauer** [comment]
Oh, looks like you already fixed them all in https://github.com/flutter/flutter/pull/150540. Thank you! Can we close this issue then or is there more to do?

**Comment by srawlins** [comment]
Haha you read my mind. I was also going to turn it into a checklist. I think there is more work to be done:

* [ ] DragGestureRecognizer.onCancel - property referencing allowedButtonsFilter.
* [ ] DragGestureRecognizer.onDown - property referencing allowedButtonsFilter.
* [ ] DragGestureRecognizer.onEnd - property referencing allowedButtonsFilter.
* [ ] DragGestureRecognizer.onStart - property referencing allowedButtonsFilter.
* [ ] DragGestureRecognizer.onUpdate - property referencing allowedButtonsFilter.
* [ ] DoubleTapGestureRecognizer.onDoubleTap - property referencing allowedButtonsFilter.
* [ ] DoubleTapGestureRecognizer.onDoubleTapCancel - property referencing referencing allowedButtonsFilter.
* [ ] DoubleTapGestureRecognizer.onDoubleTapDown - property referencing allowedButtonsFilter.
* [ ] TapGestureRecognizer - class referencing allowedButtonsFilter.
* [ ] InkSparkle - class referencing containedInkWell.
* [ ] InkSparkle - class referencing rectCallback.
* [ ] InkSparkle.splashFactory - static const field referencing turbulenceSeed.
* [ ] InkSparkle.constantTurbulenceSeedSplashFactory - static const field referencing turbulenceSeed.
* [ ] Switch.adaptive - constructor referencing ThemeData.adaptations.
* [ ] TextButton.defaultStyleOf - method referencing padding.
* [ ] Adaptation.adapt - method referencing ThemeData.adaptations.
* [ ] UndoManager - Class referencing canRedo.
* [ ] UndoManager - Class referencing canUndo.
* [ ] ContextMenuController.markNeedsBuild - method referencing contextMenuBuilder.

For all of these, I just changed `[foo]` into `` `foo` ``, so they're no-op improvements as far as the rendered HTML. I think many of them refer to parameters on other methods, like a class comment refering to a parameter on a constructor. I couldn't really say, which is why I landed the no-op fixes.

**Comment by goderbauer** [comment]
Ah, Ok, I am fixing those (where it made sense) in https://github.com/flutter/flutter/pull/150734. Some actually need to be in `. I'll mark that PR as fixing this bug then.
