### ISSUE TITLE
Shadow clipped when using a DropDownButton (samsung sm-t231)

### ISSUE THREAD

**Issue by FOGOK** [flutter/flutter#15056]
Hi !
I found ugly shadow in listview
![screenshot_2018-03-02-11-38-42](https://user-images.githubusercontent.com/22121579/36890488-22d6e5dc-1e0f-11e8-9057-eae90bc96256.png)

samsung sm-t231
android 4.4.2

**Comment by Hixie** [comment]
cc @brianosman

**Comment by chinmaygarde** [comment]
@Hixie: Have we confirmed this is a skia issue?

**Comment by zoechi** [comment]
@FOGOK is this still an issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
