### ISSUE TITLE
Flutter Drive Doesn't Shut Down After Finishing All Tests on Web - Major issue for Github Action Workflow

### ISSUE THREAD

**Issue by SinaSeylani** [flutter/flutter#150538]
### Description:
I'm experiencing an issue with flutter drive when running integration tests on the web. According to the documentation, "By default, flutter drive stops the application after tests are finished." However, this behavior is not occurring in my case. After all tests have passed, the browser remains open and does not shut down automatically.

### Steps to reproduce

Run integration tests using flutter drive on the web:

`flutter drive --driver=test_driver/integration_test.dart --target=integration_test/your_test_file.dart -d chrome --web-port=4200`

Observe that after all tests have completed, the Chrome browser remains open and does not shut down.

### Workarounds:
Currently, I have to manually close the browser after the tests complete. This is not ideal for CI/CD pipelines where automation is critical.

**This behavior is causing issues in GitHub workflows as the workflow keeps running indefinitely even though the tests are finished, impacting CI/CD pipelines.**

### Expected results

The Chrome browser should automatically shut down after all tests have completed, as stated in the documentation.

### Actual results

The Chrome browser remains open after all tests have passed, requiring manual intervention to close it.

**This behavior is causing issues in GitHub workflows as the workflow keeps running indefinitely even though the tests are finished, impacting CI/CD pipelines.**

### Code sample

`flutter drive --driver=test_driver/integration_test.dart --target=integration_test/your_test_file.dart -d chrome --web-port=4200`

I even tried this, but it didn't work:

`flutter drive --driver=test_driver/integration_test.dart --target=integration_test/magic_link_test.dart -d chrome --web-port 4200 --no-keep-app-running`

### Logs

No specific error logs are generated. The tests pass, but the browser remains open.

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.1 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at 
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

**Comment by SinaSeylani** [comment]
Hi,
yes, I'm using `setUpAll()`.
yes, the same issue occur while running the tests locally. I'm using mac 

even with most simple code, the same issue is happening: 

```
// integration_test/sample_test.dart

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('simple math test', () {
    expect(2 + 2, equals(4));
  });
}

```
Test's are passing, but the browser remains open and does not shut down automatically. 

Terminal:

```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/sample_test.dart -d chrome --web-port 4200

Resolving dependencies... 
Downloading packages... 
  _fe_analyzer_shared 67.0.0 (72.0.0 available)
  analyzer 6.4.1 (6.7.0 available)
  collection 1.18.0 (1.19.0 available)
  flutter_lints 3.0.2 (4.0.0 available)
  http 0.13.6 (1.2.1 available)
  http_parser 4.0.2 (4.1.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.4 (10.0.5 available)
  leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
  lints 3.0.0 (4.0.0 available)
  material_color_utilities 0.8.0 (0.12.0 available)
  meta 1.12.0 (1.15.0 available)
  platform 3.1.4 (3.1.5 available)
  test_api 0.7.0 (0.7.2 available)
  vm_service 14.2.1 (14.2.4 available)
Got dependencies!
15 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching integration_test/sample_test.dart on Chrome in debug mode...
Warning: In index.html:37: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
This app is linked to the debug service: ws://127.0.0.1:60771/Si3sXykXl9w=/ws
Debug service listening on ws://127.0.0.1:60771/Si3sXykXl9w=/ws
00:00 +0: simple math test
00:00 +1: All tests passed!
```

**Comment by huycozy** [comment]
@SinaSeylani I tried with test below and see chrome instance can be shut down as expected, there is ending message: `Application finished.`:

```console
00:00 +0: end-to-end test tap on the floating action button, verify counter
00:01 +1: (tearDownAll)
00:01 +2: All tests passed!
All tests passed.
Application finished.
``` 

I'm using ChromeDriver 125.0.6422.78, what is yours? 

Also, can you try with the default sample code below? (`main_counter.dart` is counter app created on skeleton Flutter project)

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:reproduce_issues_3/main_counter.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('tap on the floating action button, verify counter',
            (tester) async {
          app.main();
          await tester.pumpAndSettle();

          // Verify the counter starts at 0.
          expect(find.text('0'), findsOneWidget);

          // Finds the floating action button to tap on.
          final Finder fab = find.byTooltip('Increment');

          // Emulate a tap on the floating action button.
          await tester.tap(fab);

          // Trigger a frame.
          await tester.pumpAndSettle();

          // Verify the counter increments by 1.
          expect(find.text('1'), findsOneWidget);
        });
  });
}
```
</details>
