### ISSUE TITLE
Unable to locate CameraPlugin.h in camera

### ISSUE THREAD

**Issue by pearatme** [flutter/flutter#15050]
In reference to the camera plugin [here](https://github.com/flutter/plugins/tree/master/packages/camera)

## Steps to Reproduce
For me,

1. Make an app
2. Get the camera package
3. Import package:camera/camera.dart

## Logs

Android SDK built for x86 • emulator-5554                            • android-x86 • Android 8.1.0 (API 27) (emulator)
Joe’s iPhone              • 12bd1a65da8516e2414d685901b4c79c34dde2ae • ios         • iOS 11.2.6

When running flutter run -d 12bd1a65da8516e2414d685901b4c79c34dde2ae

Running Xcode clean...                                1.3s
Starting Xcode build...                                   
 ├─Building Dart code...                       1.4s
 ├─Assembling Flutter resources...             2.5s
 └─Compiling, linking and signing...           2.4s
Xcode build done                                      8.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/joseph/AndroidStudioProjects/science_fair_app/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'camera/CameraPlugin.h' file not found
    #import <camera/CameraPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.

Android devices work

Running `flutter analyze` 
Analyzing /Users/joseph/AndroidStudioProjects/science_fair_app...
No issues found!
Ran in 7.1s

## Flutter Doctor

[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.2 17C88, locale en-US)
    • Flutter version 0.1.5 at /Users/joseph/Library/Flutter/flutter
    • Framework revision 3ea4d06340 (7 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/joseph/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4127.31

[✓] Connected devices (2 available)

**Comment by pearatme** [comment]
This is a duplicate instance of #9694
Removing use_frameworks! from ios/Podfile. Then running a pod update, might resolve it

**Comment by mposada** [comment]
I Removed use_frameworks! from ios/Podfile. Then ran a pod update & pod install, but the error is still there: 

> GeneratedPluginRegistrant.m:6:9: fatal error: 'camera/CameraPlugin.h' file not found

**Comment by ollydixon** [comment]
I'm also facing the same issue, `camera: ^0.5.4+2`.
Removing use_frameworks causes other packages to error..

**Comment by vijayawoshe** [comment]
I am facing the same

**Comment by jamesdevries** [comment]
anyone has a fix?

**Comment by hagen00** [comment]
https://github.com/flutter/flutter/issues/32910 details what finally fixed it for me.

**Comment by andrejvnior** [comment]
I am having the same issue. 

/ios/Runner/GeneratedPluginRegistrant.m:10:9: Module 'camera' not found

I tried everything but nothing. Can somebody help me, please?

**Comment by adarshraghav** [comment]
Okay. I always had this problem. The fix that worked for me was:
1. open up a new flutter project from scratch (don't remove any of the same code or change it yet)
2. In pubspec.yaml, under dependencies mention camera
3. run the app without debugging. (please run the flutter pub get command on terminal)
4. Boom! now you have the import and now you make any number of changes
