### ISSUE TITLE
Gradient `withOpacity` method

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#150501]
### Use case

Hey.

I want to display a disabled container with gradient which has certain level of opacity.
For now I have to apply `Opacity` widget which is not the top most performer.

### Proposal

I would like to add `withOpacity` method to generate the same gradient but with opacity applied to each color in gradient.
Any cons on adding this method?(If no I could make a PR)

**Comment by darshankawar** [comment]
Thanks for the report @vasilich6107 
Can you provide us a minimal code sample that shows current behavior and with your proposed method, how would it help to achieve expected behavior ?

**Comment by darshankawar** [comment]
> colors: [
>                     Colors.black,
>                     Colors.white,
>                   ],

Here, can you try by passing `withOpacity` for each color ? something like:

```
Colors.black.withOpacity(0),
Colors.white.withOpacity(0),
```

You may want to pass exact opacity value.

**Comment by jonahwilliams** [comment]
RE: https://github.com/flutter/flutter/issues/150501#issuecomment-2178646034

Opacity of 0 has no cost, we just drop the operations from rendering.

**Comment by jonahwilliams** [comment]
Makes sense!
