### ISSUE TITLE
how to dynamic upgrade flutter code if we don't release new version

### ISSUE THREAD

**Issue by xiepengchong** [flutter/flutter#15058]
Hello

 React Native can update *.js file online,
 so can flutter update the code without release new version?

 I remember before flutter version has the file of *.flx in asset,
 but this version remove it,so where is the dart code in the apk

**Comment by lostaloneesk** [comment]
no way

**Comment by xiepengchong** [comment]
so flutter's design don't support dynamic upgrade,right?

**Comment by xiepengchong** [comment]
@lostaloneesk 
so the flutter's design don's support to update the code dynimic,right?

**Comment by lostaloneesk** [comment]
@xiepengchong yes

**Comment by Hixie** [comment]
We don't currently support this. Apple disallow this kind of update for anything except JavaScript, on iOS.
