### ISSUE TITLE
It turns out that the problem was that I didn't put the assets file in the pubspec.yaml

### ISSUE THREAD

**Issue by pagebook1** [flutter/flutter#150683]
It turns out that the problem was that I didn't put the assets file in the pubspec.yaml
```
  assets:
    # Add assets from the images directory to the application.
    - assets/
    - images/
```
These two lines were missing
```
  assets:
...
    - assets/mapStyle.txt
    - assets/mapStyleDark.txt
```

Anyway the odd thing is that this wasn't a problem when I ran the application locally, but only when I ran the released version with flutter build web. 

In my opinion this behavioural mismatch is a bug anyway

_Originally posted by @MaurizioSodano in https://github.com/flutter/flutter/issues/112800#issuecomment-1268209967_

**Comment by pagebook1** [comment]
This method didn't work for me. My flutter web works locally but not in the firebase hosting. It also works in other hosting platform.

[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
    • Flutter version 3.22.1 on channel stable at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (5 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Kevin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.90.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.68

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
> but not in the firebase hosting. It also works in other hosting platform.

@pagebook1 This seems to be specific to firebase hosting so you will need to reach out to dedicated repo. Since it works locally but not after deploying, then could be an issue from firebase hosting side. 
Based on it, I'll close this. If you disagree or get directed here, write in comments and I'll reopen it.
