### ISSUE TITLE
HarmonyOS next

### ISSUE THREAD

**Issue by hasanm08** [flutter/flutter#150657]
In Huawei road map
There is a new platform and os that doesn't support Android apps
Does flutter have any plans to add this platform?

**Comment by huycozy** [comment]
Flutter has no plan for this currently, you can check https://gitee.com/openharmony-sig/flutter_flutter to see if it helps. Please also see suggestion on https://github.com/flutter/flutter/issues/150536#issuecomment-2179766074. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/38437
