### ISSUE TITLE
Incorrect reference in the instructions

### ISSUE THREAD

**Issue by marchampson** [flutter/flutter#15067]
## Steps to Reproduce

https://codelabs.developers.google.com/codelabs/flutter-firebase/#5

You can find the reverse URL of your client id in your **Info.plist** file. Copy the value of the REVERSED_CLIENT_ID string and paste to add it to CFBundleURLSchemes. This URL type handles the callback when a user logs into your app.

The reverse URL can be found in the GoogleService-Info.plist - and needs to go into the Info.plist.

Thanks

**Comment by Sfshaza** [comment]
This refers to an obsolete codelab. It has been replaced (at the same URL) with a Baby Name Vote Flutter+Firebase codelab.

Closing.
