### ISSUE TITLE
[camera_web package] Width of Platform View type: [plugins.flutter.io/camera_1] may not be set. Defaulting to `width: 100%`.

### ISSUE THREAD

**Issue by pogorv12** [flutter/flutter#150699]
### Steps to reproduce

There was a change in flutter related to using HTML slots to render platform views in the web with makes obligatory to setup platform view width and height.  
[https://docs.flutter.dev/release/breaking-changes/platform-views-using-html-slots-web](https://docs.flutter.dev/release/breaking-changes/platform-views-using-html-slots-web)

I ask you to update camera_web package to comply with that change to prevent warning reporting.

### Expected results

No warning 

### Actual results

Warning is shown

Width of Platform View type: [plugins.flutter.io/camera_1] may not be set. Defaulting to    
`width: 100%`.

### Code sample

<details open><summary>Code sample</summary>

To fix the issue two lines of code should be added to camera.dart file of the package around line 171

```dart
 divElement = html.DivElement()
    // - edit start 
      ..style.width = '100%'
      ..style.height = '100%'
    // - edit end
      ..style.setProperty('object-fit', 'cover')
      ..append(videoElement);

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @pogorv12 
The doc does say about fixing the warning as below:

<img width="915" alt="Screenshot 2024-06-25 at 2 18 40 PM" src="https://github.com/flutter/flutter/assets/67046386/1702254d-cd97-41c2-bb2b-a111adb0ec0e">

Are you asking anything different from above ?

**Comment by pogorv12** [comment]
Yes. I'm asking to implement this in camera_web 0.3.3 package and later to prevent warning generation.

I miss this information in the description. Sorry for that.

**Comment by kevmoo** [comment]
CC @ditman

**Comment by ditman** [comment]
We'll fix this after (or at the same time) as the package:web migration of the package :)

**Comment by EchoEllet** [comment]
Seem to be fixed ([width and height properties are set](https://github.com/flutter/packages/blob/048ae847ae73fc75c0fb812afbdd5fd9a6ca104b/packages/camera/camera_web/lib/src/camera.dart#L175-L176)).
