### ISSUE TITLE
Unable to Launch Microsoft Edge for Flutter

### ISSUE THREAD

**Issue by oirivaldo** [flutter/flutter#150662]
### Steps to reproduce

Corpo do problema:

Descrição:
Ao tentar depurar um aplicativo Flutter no Microsoft Edge através do Android Studio, encontrei dificuldades para iniciar o navegador. O Android Studio exibe repetidamente a seguinte mensagem de erro:

```console
Launching lib\main.dart on Edge in debug mode...
Waiting for connection from debug service on Edge...
Warning: In index.html:37: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:46: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
Failed to launch browser after 3 tries. Command used to launch it: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --user-data-dir=C:\Users\oiriv\AppData\Local\Temp\flutter_tools.21a779f5\flutter_tools_chrome_device.b492c5af --remote-debugging-port=64648 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:64572
Finished with error: Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.
```
Passos para reproduzir:

1. Abra o Android Studio.
2. Selecione um dispositivo de depuração configurado para Microsoft Edge.
3. Tente iniciar a depuração de um aplicativo Flutter.

### Expected results

Comportamento esperado:
O Microsoft Edge deve ser iniciado corretamente para permitir a depuração do aplicativo Flutter.

### Actual results

Comportamento observado:
O Android Studio não conseguiu iniciar o Microsoft Edge após várias tentativas, resultando em falha na depuração.

Soluções tentadas sem sucesso:

Verificar atualizações do Microsoft Edge.
Reiniciar o Android Studio.
Verificar configurações de segurança do navegador.
Observações adicionais:
Este problema não ocorre ao depurar no Google Chrome ou em outros navegadores compatíveis com o Flutter.

Por favor, considere investigar este problema para melhorar a compatibilidade do Android Studio com o Microsoft Edge para desenvolvimento Flutter.

### Code sample

<details open><summary>Code sample</summary>

```dart
[QUALQUER CÓDIGO DÁ ERRO]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [versÆo 10.0.19045.4529], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Ferramentas de Build do Visual Studio 2019 16.11.7)
[!] Android Studio (version 2022.3)
    X Unable to find bundled Java version.
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.76.0)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.

**Comment by huycozy** [comment]
English version: (please consider [describing the issue in English](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#consider-posting-issues-in-english))

### Steps to reproduce

When trying to debug a Flutter app on Microsoft Edge through Android Studio, I encountered difficulties launching the browser. Android Studio repeatedly displays the following error message:

1. Open Android Studio.
2. Select a debug device configured for Microsoft Edge.
3. Try starting debugging a Flutter app.

### Expected results
Microsoft Edge must launch correctly to allow debugging of the Flutter application.

### Actual results
Android Studio was unable to launch Microsoft Edge after several attempts, resulting in debugging failure.

Solutions tried without success:

Check for Microsoft Edge updates.
Restart Android Studio.
Check browser security settings.
Additional observations:
This issue does not occur when debugging in Google Chrome or other Flutter-compatible browsers.

Please consider investigating this issue to improve Android Studio compatibility with Microsoft Edge for Flutter development.

**Comment by huycozy** [comment]
Hi @oirivaldo, can you check if the issue appears on VSCode as well? If the issue only appears on Android Studio, it will be more suitable to file an issue on https://github.com/flutter/flutter-intellij repository for better support there.
