### ISSUE TITLE
flutter 3.22: linux gl texture crashes

### ISSUE THREAD

**Issue by wang-bin** [flutter/flutter#150668]
### Steps to reproduce

It's found in video players when some animation starts, for example [fvp](https://github.com/wang-bin/fvp/issues/100) and [media-kit](https://github.com/media-kit/media-kit/issues/852). I also create a [simple example to reproduce the bug](https://github.com/wang-bin/flutter_linux_texture). no crash in flutter <= 3.19.

### Expected results

no crash

### Actual results

crash after a few seconds

### Code sample

https://github.com/wang-bin/flutter_linux_texture

<details open><summary>Code sample</summary>

```c++
static gboolean fl_render_texture_gl_populate(FlTextureGL *texture,
                                              uint32_t *target, uint32_t *name,
                                              uint32_t *width, uint32_t *height,
                                              GError **error) {
  if (!flutter_texture_populate(texture, target, name, width, height)) {
    *error =
        g_error_new_literal(g_quark_from_static_string("gl_widget_flutter"), 0,
                            "populate texture failed");
    return false;
  } else {
 //  required to reproduce the bug
    fl_texture_registrar_mark_texture_frame_available(flutter_texture_registrar,
                                                    (FlTexture *)fl_texture);
    return true;
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by wang-bin** [comment]
master channel works

**Comment by huycozy** [comment]
Thanks for confirming that. Closing this as fixed on master channel.
