### ISSUE TITLE
Incomplete editor setup instructions

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#15066]
I followed the instructions for configuring Flutter for VS Code. After installing the dart plugin. I open Command Palette and typed "doctor" and nothing comes up.

**Comment by timmar219** [comment]
Same. Also VSCode can't detect either Flutter SDK or Dart SDK.

**Comment by mostafabahri** [comment]
@azamsharp the commands won't show up unless you already have a Flutter project created.   
 Just create the project with command line, `flutter create flutter_app` then open it with Code.

**Comment by azamsharp** [comment]
Yup! I will come back to this framework in a year. 2000 issues reported is kinda abnormal for any framework.

**Comment by azamsharp** [comment]
@mostafabahri ReadMe and docs needs to be updated. :(

**Comment by mostafabahri** [comment]
@azamsharp did it work for you?

**Comment by azamsharp** [comment]
It says installing and launching for the last 5 min... let's wait.. more.

**Comment by mostafabahri** [comment]
@azamsharp give it a try with Android Studio, the plugin is fantastic!

**Comment by azamsharp** [comment]
How do I run on iOS Simulator? It detects all my devices but Simulator does not have any id associated with it.

**Comment by Hixie** [comment]
cc @DanTup

**Comment by DanTup** [comment]
@azamsharp 

> After installing the dart plugin. I open Command Palette and typed "doctor" and nothing comes up.

As mentioned by @mostafabahri, the flutter commands are context-specific. We generally only show flutter commands when a flutter project is open. An exception is `Flutter: New Project` which always appears.

@timmar219 

> Same. Also VSCode can't detect either Flutter SDK or Dart SDK.

We search a bunch of places for these for the most common issue here has been that the `PATH` variable Code gets is stale. Usually this happens for people on Windows where updating `PATH` doesn't seem to correctly apply until they reboot.

Can you try rebooting and let me know if you still have issues? If so, can you confirm your platform and also try loading code directly from the terminal after confirming that running `flutter doctor` works.

I'm often available in [Gitter Chat](https://gitter.im/dart-code/Dart-Code) during UK daylight hours so if you still have issues shout in there and if I'm around we can troubleshoot.

**Comment by DanTup** [comment]
@azamsharp 

> ReadMe and docs needs to be updated. :(

Can you clarify which part of the docs you think need updating?

**Comment by DanTup** [comment]
Btw, if you're unable to get flutter in your PATH you can set the `dart.flutterSdkPath` setting in VS Code to point at the SDK.

**Comment by DanTup** [comment]
Oh, I see the docs issue now. [This page](https://flutter.io/get-started/editor/) makes it seem like `flutter doctor` is always there.

@mit-mit @devoncarew `New Project` is currently the only command visible outside of having a Flutter project loaded (since we don't want to pollute the command palette without knowing whether the user is interested in Flutter or even has an SDK - we haven't run any code at this point because the extension isn't activated).

Possible options:

1. We enable this command always
2. We remove this section from the docs and assume the user ran it as part of the previous step
3. We tweak it to say to run `flutter doctor` from the terminal

Lmk if you have a preference (if we choose to do 1 we could always do temporarily until the next update).

**Comment by timmar219** [comment]
>We search a bunch of places for these for the most common issue here has been that the PATH variable Code gets is stale. Usually this happens for people on Windows where updating PATH doesn't seem to correctly apply until they reboot.

>Can you try rebooting and let me know if you still have issues? If so, can you confirm your platform and also try loading code directly from the terminal after confirming that running flutter doctor works.

I tried rebooting after updating the PATH, but it did not take. Then I renamed the flutter folder to Flutter and the PATH to match, restarted my computer, opened VS Code, and had no problems creating a new Flutter app.

@DanTup Thanks for your help.

**Comment by DanTup** [comment]
> I tried rebooting after updating the PATH, but it did not take. Then I renamed the flutter folder to Flutter and the PATH to match, restarted my computer, opened VS Code, and had no problems creating a new Flutter app.

I'm not quite sure what you meant here - what was the folder and path like when it failed to work? If you can repro, I'd love to see if I could improve this.

**Comment by timmar219** [comment]
> I'm not quite sure what you meant here - what was the folder and path like when it failed to work? If you can repro, I'd love to see if I could improve this.

I followed the instructions on flutter.io to set up. Downloaded the Flutter directory using the GitHub for windows into a folder under my `C:/users/[user name]` named "flutter". Then I went under control panel and created `PATH` as `flutter/bin`. Then I ran `flutter doctor` in Command Prompt which finished the setup. Yet after I restarted my computer and opened VS Code with the Dart Code extension installed, VS Code could not detect either the Flutter or Dart SDK. I tried reinstalling everything, but it did not work. I tried changing `PATH` to the flutter bin's exact file address `C:/users/[user name]/flutter/bin` but that didn't work either. Then I heard about changing the flutter folder's lower case "f" to uppercase. I tried it both on the folder and in `PATH`, restarted my computer, open VS Code, and had no problems creating a new flutter app.

**Comment by DanTup** [comment]
>  I tried changing `PATH` to the flutter bin's exact file address `C:/users/[user name]/flutter/bin`

That's what you should have done; adding just `flutter/bin` wouldn't work (I think the highlighting on the docs is slightly confusing, but it does say "If the entry does exist, append the full path to `flutter\bin`").

If your notes are accurate, then I don't think changing the case affected anything - I think after you'd changed your PATH to have the full path (instead of `flutter/bin`) if you had restarted, it would've been fixed. I don't believe changing the casing fixed it, but rather the next reboot you did.

**Comment by DanTup** [comment]
For anyone still having path issues, please try [v2.10.0 Beta 1 of Dart Code](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.10.0-beta.1) and it should now allow you to easily select the SDK folder from the error message.

Also, in this version `Flutter Doctor` will appear in the palette even without a Flutter project open, which better matches the docs issue in the initial post (@mit-mit I think that resolves this case without needing to change any docs - when v2.10 ships at least).

**Comment by DanTup** [comment]
Closing this as the original issue (instructions saying Doctor is available always and it wasn't) has been resolved in v2.10 of Dart code.

If anyone is still having issues in Dart Code, please [raise a case in the Dart Code repo](https://github.com/Dart-Code/Dart-Code/issues/new) with details and we'll investigate.

**Comment by DoctaCloak** [comment]
If you want to run this on your iOS device I personally recommend going with the terminal setup.

However, don't forget to open your project in xcode and sign the application.  If you fail to do that then poof, everything will start to crash and burn.

Good luck and let me know if you're still having trouble.

**Comment by DanTup** [comment]
> If you want to run this on your iOS device I personally recommend going with the terminal setup.

I'm not sure of the reason for this recommendation but if you're having things not working properly from the editors, please do raise issues so we can address them. There's no reason running from the editors should be a worse experience than the terminal (but there are definite advantages, like the debugger integration, hot-reload-on-save, etc.).
