### ISSUE TITLE
[Go Router] Control state of some branches in StatefulShellRoute  

### ISSUE THREAD

**Issue by giordy16** [flutter/flutter#150673]
### Use case

In my app I have followed this guide to built my nested routing: https://codewithandrea.com/articles/flutter-bottom-navigation-bar-nested-routes-gorouter/.

In my app I have 3 tabs, where on the first I do some functions, and in the other 2 I show some data that depends on the one of the first tab, but since I am using `StatefulShellRoute.indexedStack`, the state is not updated, so the widget is not updated.

### Proposal

Would be nice to have a flag in the StatefulShellBranch where I can control if the state should be kept or not, because for example in my app i am fine state the state is kept on the first tab, but I would like to rebuilt the other 2 tabs every time I navigate to them. 

If that's not possible, how can I archive this behavior?

**Comment by mark8044** [comment]
I always took it to mean that a `Stateful`ShellRoute should preserve state by definition.  Could a `ShellRoute` (without the stateful) do what you want?

**Comment by huycozy** [comment]
@giordy16 This is similar to a known issue being tracked at https://github.com/flutter/flutter/issues/142258. Closing this issue as a duplicate, so please follow up on it for further updates.
