### ISSUE TITLE
[android_alarm_manager_plus] Calling `AndroidAlarmManager.initialize()` causes multiple calls to `onAttachedToEngine` in other plugins

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#150674]
### Steps to reproduce

1. Create a plugin with an example
2. Add `android_alarm_manager_plus` to the example
3. Call `AndroidAlarmManager.initialize()`
4. See that `onAttachedToEngine` is called multiple times in your plugin

### Expected results

The `onAttachedToEngine` method is called once and only once

### Actual results

The `onAttachedToEngine` method is called many times

### Code sample

https://github.com/Rexios80/multiple_attach_test

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale
    en-US)
    • Flutter version 3.22.2 on channel stable at
      /Users/rexios/fvm/versions/3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rexios/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio
      Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)
    • SM G975U1 (mobile)              • R58M36QDM2Y               •
      android-arm64  • Android 12 (API 31)
    • Aaron’s iPhone (mobile)         • 00008130-001C35CE3A20001C • ios
      • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 125.0.6422.142
    ! Error: Browsing on the local area network for Raj's Apple Vision Pro.
      Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac. (code -27)
    ! Error: Browsing on the local area network for Joe’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by Rexios80** [comment]
Related: https://github.com/flutter/flutter/issues/69721

**Comment by stuartmorgan** [comment]
Why do you believe this is a bug? `android_alarm_manager_plus` creates an engine instance, so it's not clear to me why receiving attach calls would be unexpected.

**Comment by Rexios80** [comment]
The method channel listener is getting overwritten and I don't think the code generated by `flutter create --template plugin` handles this. Is there documentation somewhere with how to deal with this?

**Comment by Rexios80** [comment]
Actually that was a bad description of the problem sorry. The issue is the native code is losing communication with the dart code. Now that I thought about it more it might be because of the Polar SDK expecting to only be initialized once. I'll have to check when I get back to work on Tuesday. Thanks for the quick response and sorry if this was obvious.

**Comment by stuartmorgan** [comment]
> I don't think the code generated by `flutter create --template plugin` handles this.

What part of the plugin template does not handle multiple engine/plugin instance pairs? There are no singletons in the template-created code that I am aware of.

> Is there documentation somewhere with how to deal with this?

I'm not sure from the issue description what to document exactly. We could add a small section somewhere saying not to assume that the plugin instance is a singleton due to multi-engine scenarios, if that would be helpful.

**Comment by Rexios80** [comment]
This is definitely caused by the Polar SDK being a singleton. Working on resolving that.

Maybe documentation is necessary to say that `onAttachedToEngine` can be called multiple times?

Here's what caused the confusion:
- I wrongly assumed there was only ever supposed to be one engine running. Thus `onAttachedToEngine` should only be called once. Maybe this is because I have an iOS first mindset where the app is either alive or dead with no headless states.
- [This issue](https://github.com/flutter/flutter/issues/69721) describes the same issue I was having with no resolution
- [This code](https://github.com/fluttercommunity/plus_plugins/blob/13b5c54b4f199cb082daffc480445beac6b3856f/packages/android_alarm_manager_plus/android/src/main/java/dev/fluttercommunity/plus/androidalarmmanager/AndroidAlarmManagerPlugin.java#L55) in `android_alarm_manager_plus` and similar code in other plugins. Although I see now that it makes sense for `android_alarm_manager_plus` to have this so it doesn't re-initialize itself in the engine it creates.

**Comment by stuartmorgan** [comment]
> * Maybe this is because I have an iOS-first mindset where the app is either alive or dead with no headless states.

It is entirely possible for an iOS Flutter app to have multiple engine instances running. All platform support creation of engine instances.

I've filed https://github.com/flutter/flutter/issues/150855 to track adding documentation. Closing as this is behaving correctly.
