### ISSUE TITLE
laravel as backend api and flutter web didn't work well on ubuntu server nginx 

### ISSUE THREAD

**Issue by ThwinHAung** [flutter/flutter#150677]
flutter work fine on domain. they both work in locally when run flutter at chrome and laravel php aritsan but now I got theses 
I already did cors in both laravel and config but still these error I wanna know it is laravel working correctly but an error from cors or laravel actually didn't work?

Any help appreciate!!;

error`[Error] Origin https://www.championmaung.com is not allowed by Access-Control-Allow-Origin. Status code: 200
[Error] XMLHttpRequest cannot load https://championmaung.com/api/login due to access control checks.
[Error] 
	aPW (main.dart.js:7427)
	aPX (main.dart.js:7528)
	$0 (main.dart.js:44020)
	aWN (main.dart.js:6675)
	aX_ (main.dart.js:6677)
	$1 (main.dart.js:43375)
[Error] Failed to load resource: Origin https://www.championmaung.com is not allowed by Access-Control-Allow-Origin. Status code: 200 (login, line 0)`

here is the configuration

`server {
    if ($host = www.championmaung.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = championmaung.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name championmaung.com www.championmaung.com;

    return 301 https://$host$request_uri;

}

server {
    listen [::]:443 ssl;
    server_name championmaung.com www.championmaung.com;
    ssl_certificate /etc/letsencrypt/live/championmaung.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/championmaung.com/privkey.pem; # managed by Certbot

    root /var/www/html/web;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 = /index.html;

    location ~ /\. {
        deny all;
    }
    location ^~ /api {

        alias /var/www/html/laravel_for_football/public;
        try_files $uri $uri/ /index.php?$query_string;

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE,  OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Max-Age' 86400;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization';
            add_header 'Access-Control-Max-Age' 86400;
            return 204;
        }
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            include fastcgi_params;
        }
        location ~ /\.ht{
            deny all;
        }
    }

}`

another test in root 

`root@srv543846:/etc/nginx/sites-enabled# curl -X POST https://championmaung.com/api/login \
-H "Content-Type: application/json" \
-d '{"username": "Allfather47", "password": "********"}' \
-i
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 24 Jun 2024 03:45:24 GMT
Content-Type: text/html
Content-Length: 1205
Last-Modified: Sun, 23 Jun 2024 10:37:15 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "6677fadb-4b5"
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Permitted-Cross-Domain-Policies: master-only
Referrer-Policy: same-origin
Accept-Ranges: bytes

<!DOCTYPE html>
<html>
<head>
  
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="champions">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>champions</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <script src="flutter_bootstrap.js" async></script>
</body>
</html>
`

**Comment by cedvdb** [comment]
What does flutter have to do with this ?

**Comment by ThwinHAung** [comment]
flutter web is serve as frontend and it work correctly I can open domain and see ui

**Comment by darshankawar** [comment]
@ThwinHAung 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
