### ISSUE TITLE
Impeller opt-outs via manifest files are no longer reported to GA4

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#150630]
https://github.com/flutter/flutter/pull/135193 added analytics when `build ios` or `build ipa` was used, but Impeller was not:

```xml
<dict>
  <key>FLTEnableImpeller</key>
  <false/>
</dict>
```

The [Android side of the work](https://github.com/flutter/flutter/issues/132712) (since Impeller is not yet on by default) is still incomplete.

Unfortunately, it appears that even the iOS side of things no longer works as a result of the GA3->4 migration, as they were never migrated to the new tooling. This bug tracks figuring out (1) what needs to be done in order to use the new tooling, (2) doing it. It's a **launch blocker for Impeller on Android**.

It's possible this is not a high priority, if so I'll let the folks below decide that (we did think it was a priority for iOS, fwiw).

/cc @sethladd @mariamhas @jtmcdole @chinmaygarde  @jonahwilliams

**Comment by christopherfujino** [comment]
> Unfortunately, it appears that even the iOS side of things no longer works as a result of the GA3->4 migration, as they were never migrated to the new tooling.

Aren't we sending the ios-side info to GA4 here? https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_ios.dart#L788

**Comment by jonahwilliams** [comment]
Oh! I missed that, thanks @christopherfujino
