### ISSUE TITLE
What is the right way to execute bundled binaries on MacOS with sandbox enable?

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#150694]
### Steps to reproduce

What is the right way to execute bundled binaries on MacOS?
This code works perfectly with `<key>com.apple.security.app-sandbox</key>
    <false/>`: 
```
final Directory dir = await getTemporaryDirectory();
final binaryPath = '${dir.path}/MyCliTool';

final ByteData binaryBytes = await rootBundle.load('bin_assets/MyCliTool');
await File(binaryPath).writeAsBytes(binaryBytes.buffer.asUint8List(), flush: true);
// Make the binary file executable (for Unix-like systems)
await Process.run('chmod', ['+x', binaryPath]);
// Run the binary
ProcessResult result = await Process.run(binaryPath, ['arg1', 'arg2']);
```
but as soon as I enable the sandbox I get the following exception:
```
Exception has occurred.
ProcessException (ProcessException: Operation not permitted
```
Sandbox is necessary to publish on the AppStore so how can I make it work?

### Expected results

I should be able to run bundled binaries in a sandbox environement

### Actual results

```
Exception has occurred.
ProcessException (ProcessException: Operation not permitted
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-GB)
    • Flutter version 3.22.2 on channel stable at /Users/fractale/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fractale/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 126.0.6478.63

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by stuartmorgan** [comment]
Closing, as this is out of scope for Flutter; the macOS sandbox does not allow you to create and run arbitrary executables on the fly. Questions about how the macOS sandbox works in general would need to be directed to Apple support forums or general macOS programming resources.

**Comment by stephane-archer** [comment]
@stuartmorgan would it be possible to make this binary accessible from the macOS sandbox?
If not, How can I run C++ code from a Flutter app? I'm maybe using the wrong approach here.

From my understanding, MacOS is one of the platforms Flutter is supporting and I'm currently asking how to do things using Dart code, so I'm not sure why it would be out of scope...

**Comment by stuartmorgan** [comment]
> @stuartmorgan would it be possible to make this binary accessible from the macOS sandbox?

Please see my comment above for questions about the macOS sandbox itself.

> If not, How can I run C++ code from a Flutter app? I'm maybe using the wrong approach here.

There are a variety of ways of running C++ code in a Flutter app, including plugins and FFI. https://flutter.dev/community#community-grid lists a number of resources for asking high level how-to questions about Flutter development.

> From my understanding, MacOS is one of the platforms Flutter is supporting and I'm currently asking how to do things using Dart code, so I'm not sure why it would be out of scope...

Your use of Dart and Flutter are unrelated to the issue you reported; if you wrote essentially the same code in Swift in a non-Flutter app, it wouldn't work either.
