### ISSUE TITLE
TextPainter getFullHeightForCaret returns confusing values with nested TextSpans

### ISSUE THREAD

**Issue by tdenniston** [flutter/flutter#150638]
### Steps to reproduce

Paste the following code snippet into dartpad.dev, main channel (Dart SDK 3.5.0-266.0.dev and Flutter SDK 3.23.0-13.0.pre.242):
```dart
import 'package:flutter/painting.dart';

void main() {
  final painter = TextPainter(
    text: TextSpan(text: 'M', style: TextStyle(fontSize: 128), children: [
      TextSpan(text: 'M', style: TextStyle(fontSize: 32)),
      TextSpan(text: 'M', style: TextStyle(fontSize: 64)),
    ]),
    textDirection: TextDirection.ltr,
  );
  painter.layout();
  print(painter.getFullHeightForCaret(TextPosition(offset: 0), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 1), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 2), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 3), Rect.zero));
}
```

Click Run. Observe the printed output:
```
150
150
150
150
```

### Expected results

I expected to see the caret height change according to the style of the span "owning" the text position. For example, I might expect values more like:

```
150
150
37.5
75
```

because these correspond to the font size of the span directly preceding the offset. I think there could be a debate about whether the painter should look to the upstream or downstream span to retrieve the style, but either way I would not expect the caret height to be the same at all positions in this example.

### Actual results

Caret height reported as the same value, 150, for each offset in the text painter.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/painting.dart';

void main() {
  final painter = TextPainter(
    text: TextSpan(text: 'M', style: TextStyle(fontSize: 128), children: [
      TextSpan(text: 'M', style: TextStyle(fontSize: 32)),
      TextSpan(text: 'M', style: TextStyle(fontSize: 64)),
    ]),
    textDirection: TextDirection.ltr,
  );
  painter.layout();
  print(painter.getFullHeightForCaret(TextPosition(offset: 0), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 1), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 2), Rect.zero));
  print(painter.getFullHeightForCaret(TextPosition(offset: 3), Rect.zero));
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Visual aid, the code snippet drawing to a canvas:

![image](https://github.com/flutter/flutter/assets/934815/b8060576-5246-4c37-8120-97d5f0d51213)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

n/a, test on dartpad.dev

</details>

**Comment by tdenniston** [comment]
It looks like https://github.com/flutter/flutter/pull/143954 changed the implementation to use the text style of the painter's root span, rather than making a call to `_computeCaretMetrics` which appears to form the upstream/downstream search.

Link to PR and diff: https://github.com/flutter/flutter/pull/143954/files#diff-8869f4e2a7291974a4badaa8af9df4e31da61cba8a0beb83948a258486166fdcL1451-R1383

**Comment by goderbauer** [comment]
cc @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
```dart
TextSpan(text: 'M', style: TextStyle(fontSize: 128), children: [
  TextSpan(text: 'M', style: TextStyle(fontSize: 32)),
  TextSpan(text: 'M', style: TextStyle(fontSize: 64)),
  ]
```
looks like if strut is disabled the method should return the height of the run instead of using the height of the template.

**Comment by angelosilvestre** [comment]
Since this methods is producing incorrect results, shouldn't the PR be reverted until a fix is provided?
