### ISSUE TITLE
Flutter's CPU usage is too high when developing desktop applications on Linux systems and running the application

### ISSUE THREAD

**Issue by Nankarina** [flutter/flutter#150680]
### Steps to reproduce

Flutter's CPU usage is too high when developing desktop applications on Linux systems and running the application,
when using the application, the CPU usage rate can reach over 100%

### Code sample

```
class ListText extends StatefulWidget {
  const ListText({super.key});

  @override
  State<ListText> createState() => _ExampleAppState();
}

class _ExampleAppState extends State<ListText> {
  Axis direction = Axis.horizontal;

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

### What target platforms are you seeing this bug on?

Linux

### OS/Browser name and version | Device information

platform:Linux
flutter version: Channel stable, 3.7.11
Dart SDK version: 2.19.6 (stable)

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.7.11, on CentOS Linux 7
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.0)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
[√] VS Code (version 1.70.0)
[√] Connected device (2 available)
[√] Network resources

**Comment by darshankawar** [comment]
@Nankarina 
I see that you are on old version of framework. Please upgrade to latest stable and re-run your scenario to check if the cpu usage issue still persists or not.

**Comment by Nankarina** [comment]
> @Nankarina I see that you are on old version of framework. Please upgrade to latest stable and re-run your scenario to check if the cpu usage issue still persists or not.
I update to the latest version，the problem still exist

**Comment by darshankawar** [comment]
@Nankarina 
Are you running in debug mode or in profile / release mode ? Can you provide the cpu usage when the app in desktop mode runs in profile and / or in release mode ?

**Comment by Nankarina** [comment]
![cpu](https://github.com/flutter/flutter/assets/31237251/6acae799-fd61-4614-ae51-7360b941cb5d)


> @Nankarina Are you running in debug mode or in profile / release mode ? Can you provide the cpu usage when the app in desktop mode runs in profile and / or in release mode ?

Running in the debug mode,the picture is running in release mode,I see the CPU usage rate is similar.
![cpu](https://github.com/flutter/flutter/assets/31237251/e867b94f-dd6c-4bba-bc49-67cfaae2bb2f)

**Comment by Nankarina** [comment]
> @Nankarina Are you running in debug mode or in profile / release mode ? Can you provide the cpu usage when the app in desktop mode runs in profile and / or in release mode ?
Running in the debug mode,the picture is running in release mode,I see the CPU usage rate is similar.
![cpu](https://github.com/flutter/flutter/assets/31237251/92d0134c-d1b7-4dc2-b0b0-c22c576e77ab)

**Comment by darshankawar** [comment]
Looks similar to https://github.com/flutter/flutter/issues/101591. You can check if https://github.com/flutter/flutter/issues/101591#issuecomment-1379445216 helps in your case or not.
