### ISSUE TITLE
FormatException: FormatException: Bad UTF-8 encoding 0xeb (at offset 63)

### ISSUE THREAD

**Issue by tochanenko** [flutter/flutter#15060]
## Steps to Reproduce

1) Create new Flutter project
2) Run/Debug it

## Logs
```
`flutter run`
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0,9s
Resolving dependencies...                             1,4s
Running 'gradlew assembleDebug'...

Oops; flutter has exited unexpectedly.
Crash report written to D:\WorkSpace\Java\untitled5\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.


Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 78796ddf395440a5)
Crash report written to D:\WorkSpace\Java\untitled5\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

`flutter analyze`
Analyzing D:\WorkSpace\Java\untitled5...
No issues found!
Ran in 9.2s
```
flutter_0x.log:
[flutter_01.log](https://github.com/flutter/flutter/files/1774639/flutter_01.log)
[flutter_02.log](https://github.com/flutter/flutter/files/1774637/flutter_02.log)
[flutter_03.log](https://github.com/flutter/flutter/files/1774638/flutter_03.log)

## Flutter Doctor
```
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale ru-RU)
    • Flutter version 0.1.5 at C:\Users\Владислав\flutter
    • Framework revision 3ea4d06340 (8 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at D:\Android\Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.9.2

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by Hixie** [comment]
Do you by any chance have any files with names that are not UTF-8-clean?

**Comment by tochanenko** [comment]
@Hixie I don't think so. Unless Flutter or Android Studio has its difficulties with Russian symbols. My user folder is "Владислав". Could it be the problem? Should I just install Flutter to another path, such as "C:\Flutter"?

**Comment by Hixie** [comment]
Can you run the command with `-v`? As in, `flutter run -v`, and then paste the output here.

**Comment by tochanenko** [comment]
@Hixie 
[  +38 ms] [C:\Users\Владислав\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +101 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] [C:\Users\Владислав\flutter\] git rev-parse --abbrev-ref HEAD
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [C:\Users\Владислав\flutter\] git ls-remote --get-url origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\Users\Владислав\flutter\] git log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3ea4d06340a97a1e9d7cae97567c64e0569dcaa2
[        ] [C:\Users\Владислав\flutter\] git log -n 1 --pretty=format:%ar
[  +63 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 9 days ago
[   +1 ms] [C:\Users\Владислав\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +63 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.1.5-0-g3ea4d0634
[ +310 ms] D:\Android\SDK\platform-tools\adb devices -l
[  +42 ms] Exit code 0 from: D:\Android\SDK\platform-tools\adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[ +256 ms] D:\Android\SDK\platform-tools\adb -s emulator-5554 shell getprop
[  +70 ms] ro.hardware = ranchu
[ +839 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +9 ms] Initializing gradle...
[   +1 ms] Using gradle from D:\WorkSpace\Android\flutter_app2\android\gradlew.bat.
[ +112 ms] D:\WorkSpace\Android\flutter_app2\android\gradlew.bat -v
[ +791 ms]
                   ------------------------------------------------------------
                   Gradle 4.1
                   ------------------------------------------------------------

                   Build time:   2017-08-07 14:38:48 UTC
                   Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

                   Groovy:       2.4.11
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                   OS:           Windows 10 10.0 amd64
[   +3 ms] Resolving dependencies...
[        ] [android\] D:\WorkSpace\Android\flutter_app2\android\gradlew.bat app:properties
[+1421 ms] :app:properties

                   ------------------------------------------------------------
                   Project :app
                   ------------------------------------------------------------

                   allprojects: [project ':app']
                   android: com.android.build.gradle.AppExtension_Decorated@475ac740
                   androidDependencies: task ':app:androidDependencies'
                   ant: org.gradle.api.internal.project.DefaultAntBuilder@556ccb1a
                   antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@16c94f46
                   archivesBaseName: app
                   artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@6c1e7a7a
                   asDynamicObject: DynamicObject for project ':app'
                   assemble: task ':app:assemble'
                   assembleAndroidTest: task ':app:assembleAndroidTest'
                   assembleDebug: task ':app:assembleDebug'
                   assembleDebugAndroidTest: task ':app:assembleDebugAndroidTest'
                   assembleDebugUnitTest: task ':app:assembleDebugUnitTest'
                   assembleProfile: task ':app:assembleProfile'
                   assembleProfileUnitTest: task ':app:assembleProfileUnitTest'
                   assembleRelease: task ':app:assembleRelease'
                   assembleReleaseUnitTest: task ':app:assembleReleaseUnitTest'
                   baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@7defc07e
                   buildDependents: task ':app:buildDependents'
                   buildDir: D:\WorkSpace\Android\flutter_app2\build\app
                   buildFile: D:\WorkSpace\Android\flutter_app2\android\app\build.gradle
                   buildNeeded: task ':app:buildNeeded'
                   buildOutputs: BaseVariantOutput container
                   buildScriptSource: org.gradle.groovy.scripts.UriScriptSource@4e68e0c2
                   buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@12873536
                   bundleAppClassesDebug: task ':app:bundleAppClassesDebug'
                   bundleAppClassesDebugAndroidTest: task ':app:bundleAppClassesDebugAndroidTest'
                   bundleAppClassesDebugUnitTest: task ':app:bundleAppClassesDebugUnitTest'
                   bundleAppClassesProfile: task ':app:bundleAppClassesProfile'
                   bundleAppClassesProfileUnitTest: task ':app:bundleAppClassesProfileUnitTest'
                   bundleAppClassesRelease: task ':app:bundleAppClassesRelease'
                   bundleAppClassesReleaseUnitTest: task ':app:bundleAppClassesReleaseUnitTest'
                   check: task ':app:check'
                   checkDebugManifest: task ':app:checkDebugManifest'
                   checkProfileManifest: task ':app:checkProfileManifest'
                   checkReleaseManifest: task ':app:checkReleaseManifest'
                   childProjects: {}
                   class: class org.gradle.api.internal.project.DefaultProject_Decorated
                   classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@d5540b6
                   cleanBuildCache: task ':app:cleanBuildCache'
                   compileDebugAidl: task ':app:compileDebugAidl'
                   compileDebugAndroidTestAidl: task ':app:compileDebugAndroidTestAidl'
                   compileDebugAndroidTestJavaWithJavac: task ':app:compileDebugAndroidTestJavaWithJavac'
                   compileDebugAndroidTestNdk: task ':app:compileDebugAndroidTestNdk'
                   compileDebugAndroidTestRenderscript: task ':app:compileDebugAndroidTestRenderscript'
                   compileDebugAndroidTestShaders: task ':app:compileDebugAndroidTestShaders'
                   compileDebugAndroidTestSources: task ':app:compileDebugAndroidTestSources'
                   compileDebugJavaWithJavac: task ':app:compileDebugJavaWithJavac'
                   compileDebugNdk: task ':app:compileDebugNdk'
                   compileDebugRenderscript: task ':app:compileDebugRenderscript'
                   compileDebugShaders: task ':app:compileDebugShaders'
                   compileDebugSources: task ':app:compileDebugSources'
                   compileDebugUnitTestJavaWithJavac: task ':app:compileDebugUnitTestJavaWithJavac'
                   compileDebugUnitTestSources: task ':app:compileDebugUnitTestSources'
                   compileLint: task ':app:compileLint'
                   compileProfileAidl: task ':app:compileProfileAidl'
                   compileProfileJavaWithJavac: task ':app:compileProfileJavaWithJavac'
                   compileProfileNdk: task ':app:compileProfileNdk'
                   compileProfileRenderscript: task ':app:compileProfileRenderscript'
                   compileProfileShaders: task ':app:compileProfileShaders'
                   compileProfileSources: task ':app:compileProfileSources'
                   compileProfileUnitTestJavaWithJavac: task ':app:compileProfileUnitTestJavaWithJavac'
                   compileProfileUnitTestSources: task ':app:compileProfileUnitTestSources'
                   compileReleaseAidl: task ':app:compileReleaseAidl'
                   compileReleaseJavaWithJavac: task ':app:compileReleaseJavaWithJavac'
                   compileReleaseNdk: task ':app:compileReleaseNdk'
                   compileReleaseRenderscript: task ':app:compileReleaseRenderscript'
                   compileReleaseShaders: task ':app:compileReleaseShaders'
                   compileReleaseSources: task ':app:compileReleaseSources'
                   compileReleaseUnitTestJavaWithJavac: task ':app:compileReleaseUnitTestJavaWithJavac'
                   compileReleaseUnitTestSources: task ':app:compileReleaseUnitTestSources'
                   components: SoftwareComponentInternal set
                   configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@eba8d52
                   configurationTargetIdentifier: org.gradle.configuration.ConfigurationTargetIdentifier$1@75d02b7
                   configurations: configuration container
                   connectedAndroidTest: task ':app:connectedAndroidTest'
                   connectedCheck: task ':app:connectedCheck'
                   connectedDebugAndroidTest: task ':app:connectedDebugAndroidTest'
                   consumeConfigAttr: task ':app:consumeConfigAttr'
                   convention: org.gradle.api.internal.plugins.DefaultConvention@2cd8a9ef
                   copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
                   copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
                   copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
                   createDebugCompatibleScreenManifests: task ':app:createDebugCompatibleScreenManifests'
                   createProfileCompatibleScreenManifests: task ':app:createProfileCompatibleScreenManifests'
                   createReleaseCompatibleScreenManifests: task ':app:createReleaseCompatibleScreenManifests'
                   defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@baf1c32
                   defaultTasks: []
                   deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@5125c008
                   dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@3e822821
                   depth: 1
                   description: null
                   deviceAndroidTest: task ':app:deviceAndroidTest'
                   deviceCheck: task ':app:deviceCheck'
                   displayName: project ':app'
                   distsDir: D:\WorkSpace\Android\flutter_app2\build\app\distributions
                   distsDirName: distributions
                   docsDir: D:\WorkSpace\Android\flutter_app2\build\app\docs
                   docsDirName: docs
                   ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@577c69cf
                   extensions: org.gradle.api.internal.plugins.DefaultConvention@2cd8a9ef
                   extractProguardFiles: task ':app:extractProguardFiles'
                   fileOperations: org.gradle.api.internal.file.DefaultFileOperations@24c1a19e
                   fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@5b1b108e
                   flutter: FlutterExtension_Decorated@74f7f8ec
                   flutterBuildDebug: task ':app:flutterBuildDebug'
                   flutterBuildProfile: task ':app:flutterBuildProfile'
                   flutterBuildRelease: task ':app:flutterBuildRelease'
                   flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
                   flutterDependenciesDebug: task ':app:flutterDependenciesDebug'
                   flutterDependenciesProfile: task ':app:flutterDependenciesProfile'
                   flutterDependenciesRelease: task ':app:flutterDependenciesRelease'
                   generateDebugAndroidTestAssets: task ':app:generateDebugAndroidTestAssets'
                   generateDebugAndroidTestBuildConfig: task ':app:generateDebugAndroidTestBuildConfig'
                   generateDebugAndroidTestResValues: task ':app:generateDebugAndroidTestResValues'
                   generateDebugAndroidTestResources: task ':app:generateDebugAndroidTestResources'
                   generateDebugAndroidTestSources: task ':app:generateDebugAndroidTestSources'
                   generateDebugAssets: task ':app:generateDebugAssets'
                   generateDebugBuildConfig: task ':app:generateDebugBuildConfig'
                   generateDebugResValues: task ':app:generateDebugResValues'
                   generateDebugResources: task ':app:generateDebugResources'
                   generateDebugSources: task ':app:generateDebugSources'
                   generateProfileAssets: task ':app:generateProfileAssets'
                   generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
                   generateProfileResValues: task ':app:generateProfileResValues'
                   generateProfileResources: task ':app:generateProfileResources'
                   generateProfileSources: task ':app:generateProfileSources'
                   generateReleaseAssets: task ':app:generateReleaseAssets'
                   generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
                   generateReleaseResValues: task ':app:generateReleaseResValues'
                   generateReleaseResources: task ':app:generateReleaseResources'
                   generateReleaseSources: task ':app:generateReleaseSources'
                   gradle: build 'android'
                   group: android
                   identityPath: :app
                   inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@4071d5ac
                   installDebug: task ':app:installDebug'
                   installDebugAndroidTest: task ':app:installDebugAndroidTest'
                   installProfile: task ':app:installProfile'
                   installRelease: task ':app:installRelease'
                   javaPreCompileDebug: task ':app:javaPreCompileDebug'
                   javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
                   javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
                   javaPreCompileProfile: task ':app:javaPreCompileProfile'
                   javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
                   javaPreCompileRelease: task ':app:javaPreCompileRelease'
                   javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
                   layout: org.gradle.api.internal.file.DefaultProjectLayout@6915516d
                   libsDir: D:\WorkSpace\Android\flutter_app2\build\app\libs
                   libsDirName: libs
                   lint: task ':app:lint'
                   lintDebug: task ':app:lintDebug'
                   lintProfile: task ':app:lintProfile'
                   lintRelease: task ':app:lintRelease'
                   lintVitalRelease: task ':app:lintVitalRelease'
                   logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@547cce82
                   logging: org.gradle.internal.logging.services.DefaultLoggingManager@6a09a3a1
                   mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
                   mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
                   mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
                   mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
                   mergeDebugAssets: task ':app:mergeDebugAssets'
                   mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
                   mergeDebugResources: task ':app:mergeDebugResources'
                   mergeDebugShaders: task ':app:mergeDebugShaders'
                   mergeProfileAssets: task ':app:mergeProfileAssets'
                   mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
                   mergeProfileResources: task ':app:mergeProfileResources'
                   mergeProfileShaders: task ':app:mergeProfileShaders'
                   mergeReleaseAssets: task ':app:mergeReleaseAssets'
                   mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
                   mergeReleaseResources: task ':app:mergeReleaseResources'
                   mergeReleaseShaders: task ':app:mergeReleaseShaders'
                   mockableAndroidJar: task ':app:mockableAndroidJar'
                   modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@21f21694
                   modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@6a881462
                   module: org.gradle.api.internal.artifacts.ProjectBackedModule@61255f5d
                   name: app
                   normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@6f607bb3
                   objects: org.gradle.api.internal.model.DefaultObjectFactory@4786427b
                   org.gradle.jvmargs: -Xmx1536M
                   packageDebug: task ':app:packageDebug'
                   packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
                   packageProfile: task ':app:packageProfile'
                   packageRelease: task ':app:packageRelease'
                   parent: root project 'android'
                   parentIdentifier: root project 'android'
                   path: :app
                   platformAttrExtractor: task ':app:platformAttrExtractor'
                   pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@2c3dd10b
                   plugins: [org.gradle.api.plugins.HelpTasksPlugin@6f89a0d5, com.android.build.gradle.api.AndroidBasePlugin@229073e3, org.gradle.language.base.plugins.LifecycleBasePlugin@51559190, org.gradle.api.plugins.BasePlugin@21b5ab6a, org.gradle.api.plug
ins.ReportingBasePlugin@519058bb, org.gradle.platform.base.plugins.ComponentBasePlugin@18f70ccc, org.gradle.language.base.plugins.LanguageBasePlugin@4bf1dae9, org.gradle.platform.base.plugins.BinaryBasePlugin@3d258ca6, org.gradle.api.plugins.JavaBasePlugin@38f9
a209, com.android.build.gradle.internal.coverage.JacocoPlugin@48c77dc3, com.android.build.gradle.AppPlugin@10cec323, FlutterPlugin@227486f5]
                   preBuild: task ':app:preBuild'
                   preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
                   preDebugBuild: task ':app:preDebugBuild'
                   preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
                   preProfileBuild: task ':app:preProfileBuild'
                   preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
                   preReleaseBuild: task ':app:preReleaseBuild'
                   preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
                   prepareLintJar: task ':app:prepareLintJar'
                   processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
                   processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
                   processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
                   processDebugJavaRes: task ':app:processDebugJavaRes'
                   processDebugManifest: task ':app:processDebugManifest'
                   processDebugResources: task ':app:processDebugResources'
                   processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
                   processOperations: org.gradle.api.internal.file.DefaultFileOperations@24c1a19e
                   processProfileJavaRes: task ':app:processProfileJavaRes'
                   processProfileManifest: task ':app:processProfileManifest'
                   processProfileResources: task ':app:processProfileResources'
                   processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
                   processReleaseJavaRes: task ':app:processReleaseJavaRes'
                   processReleaseManifest: task ':app:processReleaseManifest'
                   processReleaseResources: task ':app:processReleaseResources'
                   processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
                   project: project ':app'
                   projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@b8e7b86
                   projectDir: D:\WorkSpace\Android\flutter_app2\android\app
                   projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
                   projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@3a798ad5
                   projectPath: :app
                   projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@56a8c3ca
                   properties: {...}
                   providers: org.gradle.api.internal.provider.DefaultProviderFactory@120daa20
                   reporting: org.gradle.api.reporting.ReportingExtension_Decorated@145fe59d
                   reportsDir: D:\WorkSpace\Android\flutter_app2\build\app\reports
                   repositories: repository container
                   resolveConfigAttr: task ':app:resolveConfigAttr'
                   resources: org.gradle.api.internal.resources.DefaultResourceHandler@6c75eedb
                   rootDir: D:\WorkSpace\Android\flutter_app2\android
                   rootProject: root project 'android'
                   scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@1a2cfea2
                   scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@a0ac8be
                   serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@6112b76f
                   services: ProjectScopeServices
                   signingReport: task ':app:signingReport'
                   sourceCompatibility: 1.8
                   sourceSets: SourceSet container
                   splitsDiscoveryTaskDebug: task ':app:splitsDiscoveryTaskDebug'
                   splitsDiscoveryTaskDebugAndroidTest: task ':app:splitsDiscoveryTaskDebugAndroidTest'
                   splitsDiscoveryTaskProfile: task ':app:splitsDiscoveryTaskProfile'
                   splitsDiscoveryTaskRelease: task ':app:splitsDiscoveryTaskRelease'
                   standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@6a09a3a1
                   state: project state 'EXECUTED'
                   status: integration
                   subprojects: []
                   targetCompatibility: 1.8
                   tasks: task set
                   test: task ':app:test'
                   testDebugUnitTest: task ':app:testDebugUnitTest'
                   testProfileUnitTest: task ':app:testProfileUnitTest'
                   testReleaseUnitTest: task ':app:testReleaseUnitTest'
                   testReportDir: D:\WorkSpace\Android\flutter_app2\build\app\reports\tests
                   testReportDirName: tests
                   testResultsDir: D:\WorkSpace\Android\flutter_app2\build\app\test-results
                   testResultsDirName: test-results
                   transformClassesWithDexBuilderForDebug: task ':app:transformClassesWithDexBuilderForDebug'
                   transformClassesWithDexBuilderForDebugAndroidTest: task ':app:transformClassesWithDexBuilderForDebugAndroidTest'
                   transformClassesWithDexBuilderForProfile: task ':app:transformClassesWithDexBuilderForProfile'
                   transformClassesWithPreDexForRelease: task ':app:transformClassesWithPreDexForRelease'
                   transformDexArchiveWithDexMergerForDebug: task ':app:transformDexArchiveWithDexMergerForDebug'
                   transformDexArchiveWithDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithDexMergerForDebugAndroidTest'
                   transformDexArchiveWithDexMergerForProfile: task ':app:transformDexArchiveWithDexMergerForProfile'
                   transformDexArchiveWithExternalLibsDexMergerForDebug: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'
                   transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'
                   transformDexArchiveWithExternalLibsDexMergerForProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForProfile'
                   transformDexWithDexForRelease: task ':app:transformDexWithDexForRelease'
                   transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
                   transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
                   transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
                   transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
                   transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
                   transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
                   transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
                   transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
                   transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
                   transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
                   transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
                   uninstallAll: task ':app:uninstallAll'
                   uninstallDebug: task ':app:uninstallDebug'
                   uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
                   uninstallProfile: task ':app:uninstallProfile'
                   uninstallRelease: task ':app:uninstallRelease'
                   validateSigningDebug: task ':app:validateSigningDebug'
                   validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
                   validateSigningProfile: task ':app:validateSigningProfile'
                   validateSigningRelease: task ':app:validateSigningRelease'
                   version: unspecified
                   writeDebugApplicationId: task ':app:writeDebugApplicationId'
                   writeProfileApplicationId: task ':app:writeProfileApplicationId'
                   writeReleaseApplicationId: task ':app:writeReleaseApplicationId'

                   BUILD SUCCESSFUL in 1s
                   1 actionable task: 1 executed
[  +63 ms] D:\Android\SDK\platform-tools\adb -s emulator-5554 logcat -v time -t 1
[  +57 ms] Exit code 0 from: D:\Android\SDK\platform-tools\adb -s emulator-5554 logcat -v time -t 1
[        ] --------- beginning of main
           03-03 10:32:11.862 I/MicroDetectionWorker( 2439): #onError(false)
[   +2 ms] D:\Android\SDK\platform-tools\adb -s emulator-5554 logcat -v time
[   +8 ms] D:\Android\SDK\platform-tools\adb version
[  +76 ms] Android Debug Bridge version 1.0.39
           Version 0.0.1-4500957
           Installed as D:\Android\SDK\platform-tools\adb.EXE
[   +6 ms] D:\Android\SDK\platform-tools\adb start-server
[  +60 ms] Building APK
[   +6 ms] Running 'gradlew assembleDebug'...
[   +2 ms] [android\] D:\WorkSpace\Android\flutter_app2\android\gradlew.bat -Ptarget=D:\WorkSpace\Android\flutter_app2\lib/main.dart assembleDebug
[+1374 ms] :app:preBuild UP-TO-DATE
[  +17 ms] :app:preDebugBuild UP-TO-DATE
[        ] :app:compileDebugAidl UP-TO-DATE
[   +9 ms] :app:compileDebugRenderscript UP-TO-DATE
[   +9 ms] :app:flutterBuildX86Jar UP-TO-DATE
[        ] :app:checkDebugManifest UP-TO-DATE
[   +9 ms] :app:generateDebugBuildConfig UP-TO-DATE
[        ] :app:prepareLintJar UP-TO-DATE
[        ] :app:cleanMergeDebugAssets UP-TO-DATE
[+2010 ms] Oops; flutter has exited unexpectedly.
[ +845 ms] Crash report written to D:\WorkSpace\Android\flutter_app2\flutter_03.log;
[        ] please let us know at https://github.com/flutter/flutter/issues.
[  +30 ms] :app:flutterDependenciesDebug FAILED
[   +8 ms] 9 actionable tasks: 1 executed, 8 up-to-date
[ +435 ms] "flutter run" took 8 769ms.

Oops; flutter has exited unexpectedly.
[  +19 ms] Sending crash report to Google.
[ +941 ms] Crash report sent (report ID: 5cf63e4505b767b6)
Crash report written to D:\WorkSpace\Android\flutter_app2\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
[ +406 ms] ensureAnalyticsSent: 0ms
[   +1 ms] exiting with code 1

[flutter_03.log](https://github.com/flutter/flutter/files/1777382/flutter_03.log)
[flutter_04.log](https://github.com/flutter/flutter/files/1777383/flutter_04.log)

**Comment by tochanenko** [comment]
Wow! Amazing! Reinstalled flutter from "C:\Users\Владислав\" folder into "D:\Android". Now everything is fine

**Comment by Hixie** [comment]
Weird.

My guess is that if you install into "C:\Users\Владислав" again now it should work. We did a bunch of work to make non-UTF-8 file names work better recently. If you run into any problems please do let us know by filing a new bug.
