### ISSUE TITLE
Issue from website page Developing Flutter apps in an IDE

### ISSUE THREAD

**Issue by Arezohayeman** [flutter/flutter#15065]
From URL: https://flutter.io/using-ide.md

**Comment by Arezohayeman** [comment]
2,324

**Comment by RedBrogdon** [comment]
@Arezohayeman, are you looking for instructions on how to set up an IDE with Flutter? If so, you can find them here:

https://flutter.io/get-started/editor/

**Comment by Hixie** [comment]
@Arezohayeman It's not clear what you are asking here, can you elaborate?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
