### ISSUE TITLE
Multiple Audio Track support in video

### ISSUE THREAD

**Issue by The-Shahin** [flutter/flutter#150684]
### Use case

I am writing to request a new feature for the video_player library: support for multiple audio tracks.

Feature Request: Multiple Audio Track Support
Use Case
I am developing an application that streams multimedia content to users. The content includes movies and shows available in multiple languages, as well as versions with director’s commentary. Currently, the video_player library does not support switching between these audio tracks, which limits the experience for users who wish to select their preferred audio track.

Problem Description
The inability to switch audio tracks within the video_player library has led to a suboptimal user experience. Users are unable to select their preferred language or listen to additional audio content such as commentary tracks. This is especially problematic for multilingual audiences and users who enjoy additional content.

Alternative Solutions
I have considered the following alternatives:

Using Other Libraries: I researched other video player libraries on pub.dev/flutter but found that they either lack stability or do not fully integrate with my existing application.
Custom Implementation: Implementing a custom solution to handle multiple audio tracks. However, this approach is complex and time-consuming, and it would be more efficient if the feature were natively supported by the video_player library.
Proposed Solution
I propose adding functionality to the video_player library that allows for:

Detection of Multiple Audio Tracks: Automatically detect and list all available audio tracks in the media file.
Easy Track Switching: Provide a user-friendly interface for users to switch between audio tracks.
API for Developers: Allow developers to switch tracks programmatically through the API.
This feature would greatly enhance the usability and flexibility of the video_player library.

Thank you for considering this request.

### Proposal

https://pub.dev/packages/flutter_vlc_player

**Comment by orgnu** [comment]
This feature request addresses a crucial need in multimedia streaming applications. Currently, the lack of support for switching audio tracks within the video_player library limits user experience, particularly for audiences consuming content in multiple languages or seeking additional commentary tracks. While exploring alternative solutions, such as other libraries on pub.dev/flutter or custom implementations, none seem as efficient or integrated as native support within video_player. Adding functionality to detect and switch between multiple audio tracks would significantly enhance flexibility and usability, making it easier for developers to manage diverse content types seamlessly. I strongly support this proposal and hope it will be prioritized for implementation.
