### ISSUE TITLE
Not displaying the full title when using a gradient for the app bar

### ISSUE THREAD

**Issue by msusviela** [flutter/flutter#150632]
### Steps to reproduce

1. Create an App
2. Set the AppBar title like this:
`  title: GradientText(
            'A test with a long name QA1169Test',
            style: FlutterFlowTheme.of(context).headlineMedium.override(
                  fontFamily: 'Outfit',
                  color: Colors.white,
                  fontSize: 22.0,
                  letterSpacing: 0.0,
                ),
            colors: [
              FlutterFlowTheme.of(context).primary,
              FlutterFlowTheme.of(context).secondary
            ],
            gradientDirection: GradientDirection.ltr,
            gradientType: GradientType.linear,
          ),`

3. it's happening on web

### Expected results

I expect to get the full text, as here but with the corresponding gradient:
![image](https://github.com/flutter/flutter/assets/107059597/7abafa9d-aad5-454f-b189-3987bd255039)

### Actual results

![image](https://github.com/flutter/flutter/assets/107059597/ae7236d7-1b8a-45bd-b81e-70acdcfe240e)

### Code sample

<details open><summary>Code sample</summary>

```dart
  title: GradientText(
            'A test with a long name QA1169Test',
            style: FlutterFlowTheme.of(context).headlineMedium.override(
                  fontFamily: 'Outfit',
                  color: Colors.white,
                  fontSize: 22.0,
                  letterSpacing: 0.0,
                ),
            colors: [
              FlutterFlowTheme.of(context).primary,
              FlutterFlowTheme.of(context).secondary
            ],
            gradientDirection: GradientDirection.ltr,
            gradientType: GradientType.linear,
          ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/107059597/b4d7975e-9697-4c1c-9d64-82b802abd21a)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.4, on macOS 13.0.1 22A400 darwin-arm64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.90.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
What is GradientText?

**Comment by huycozy** [comment]
@msusviela Are you using a 3rd party package for `GradientText` or your defined class? Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party packages or complex production code. Thanks!
