### ISSUE TITLE
Fix Linux numpad shortcuts on web

### ISSUE THREAD

**Issue by m3c-fnicola** [flutter/flutter#150724]
### Issue Link

https://github.com/flutter/flutter/issues/148447

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/150723

### Changelog Description

Fixes an issue on Web+Linux that prevents users from inputting data using the numpad.

### Impacted Users

Users that use Flutter web apps on a Linux machine

### Impact Description

Numpad keys are ignored on web apps running on Linux.

### Workaround

Before running the app, ensure "num lock" key is disabled. When the web app is running, enable the numpad and it will work normally.

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
https://github.com/flutter/flutter/pull/150723 merged
