### ISSUE TITLE
flutter run doesn't work after upgrading to beta-1

### ISSUE THREAD

**Issue by arnoldparge** [flutter/flutter#15074]
## Steps to Reproduce

I wanted to upgrade Flutter from alpha to beta. So, I simply ran `flutter upgrade` . Then I checked version by `flutter --version` and it said alpha. I ran `flutter run --verbose` and it got stuck as below. I removed flutter completely and reinstalled it by `git clone -b beta https://github.com/flutter/flutter.git`  I ran `flutter run --verbose` and the result is same, gets stuck as below. 

## flutter run --verbose

C:\Users\PARGE\IdeaProjects\sample>flutter run --verbose
[  +49 ms] [C:\Users\PARGE\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +91 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[   +1 ms] [C:\Users\PARGE\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[        ] [C:\Users\PARGE\flutter\flutter\] git ls-remote --get-url origin
[  +48 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] [C:\Users\PARGE\flutter\flutter\] git log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +3 ms] 3ea4d06340a97a1e9d7cae97567c64e0569dcaa2
[        ] [C:\Users\PARGE\flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +54 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 8 days ago
[   +1 ms] [C:\Users\PARGE\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +65 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.1.5-0-g3ea4d0634
[ +486 ms] C:\Program Files (x86)\Android\android-sdk\platform-tools\adb devices -l
[  +32 ms] Exit code 0 from: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb devices -l
[   +1 ms] List of devices attached
           33a398b8               device product:tissot model:Mi_A1 device:tissot_sprout
[ +302 ms] C:\Program Files (x86)\Android\android-sdk\platform-tools\adb -s 33a398b8 shell getprop
[ +159 ms] ro.hardware = qcom
[+1165 ms] Launching lib/main.dart on Mi A1 in debug mode...
[  +27 ms] Initializing gradle...
[   +2 ms] Using gradle from C:\Users\PARGE\IdeaProjects\sample\android\gradlew.bat.
[ +115 ms] C:\Users\PARGE\IdeaProjects\sample\android\gradlew.bat -v

## Flutter Doctor

C:\Users\PARGE\IdeaProjects\sample>flutter doctor -v
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.15063], locale en-IN)
    • Flutter version 0.1.5 at C:\Users\PARGE\flutter\flutter
    • Framework revision 3ea4d06340 (8 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[√] VS Code (version 1.20.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.9.2

[√] Connected devices (1 available)
    • Mi A1 • 33a398b8 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by arnoldparge** [comment]
Solved it!! I deleted android and ios folder from the project. Then being inside the project folder I ran `flutter create .`

And it did the trick

**Comment by Hixie** [comment]
Weird.
