### ISSUE TITLE
No way to center hint text in an EditText that is text align centered.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#15079]
I created an EditText that was centered but the hint text was left aligned with no way to change it.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by aubykhan** [comment]
@Hixie do you have any workaround while this issue is being fixed?

**Comment by MichaelSowah** [comment]
@Hixie @HansMuller whats the status on this as this is causing big problems for TextFormField and almost a blocker. still working to find a way which is proven futile so far...is there any work araound

**Comment by zoechi** [comment]
similar to #16366

**Comment by khanghyxda** [comment]
Number field should be align right, currently can only be left.
