### ISSUE TITLE
Security Vulnerability issues 

### ISSUE THREAD

**Issue by devsideal** [flutter/flutter#150767]
### Steps to reproduce

Use any security testing tool.

### Expected results

Should not have any Vulnerability issue.

### Actual results

Showing three Vulnerability issue

### Code sample

<details open><summary>Code sample</summary>

I'm working on a flutter Android/iOS App that is almost completed and i have fixed many security issues, 
But when the security testing team is testing the app the report is showing below three security issues:

1. Usage of CBC with PKCS5/PKCS7 Padding in Android Application 
2. Use of Weak Hashing Algorithm [SHA-1] - mobile app
3. Usage of MD5 Algorithm in Android Application 

I'm unable to indentify from which package these issues are getting, my pybspec.yml file contains below packages: 

```dart
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  pin_code_fields: ^8.0.1
  cached_network_image:
  image_picker: ^1.1.2
  loader_overlay: ^4.0.0
  device_info_plus: ^10.1.0
  android_id: ^0.4.0
  another_flushbar: ^1.12.30
  fluttertoast: ^8.2.6
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  dio_cache_interceptor_hive_store: ^3.2.2
  shared_preferences: ^2.2.3
  dio_cache_interceptor: ^3.5.0
  cupertino_tabbar: ^2.0.0
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1
  status_view: ^0.0.2
  google_maps_flutter: ^2.7.0
  flutter_staggered_grid_view: ^0.7.0
  camera: ^0.11.0+1
  custom_sliding_segmented_control: ^1.8.3
  flutter_calendar_carousel: ^2.4.3
  firebase_auth: ^5.1.0
  intl_phone_field: ^3.2.0
  pin_code_text_field: ^1.8.0
  flutter_share: ^2.0.0
  file_picker: ^5.2.3
  app_settings: ^5.1.1
  flutter_image_compress: ^2.3.0
  shimmer: ^3.0.0
  flutter_html: 3.0.0-beta.1
  fbroadcast: ^2.0.0
  flutter_video_info:
  flutter_google_places_hoc081098: ^2.0.0
  jiffy: ^5.0.0
  cloud_firestore: ^5.0.1
  ntp: ^2.0.0
  swipe_to: ^1.0.6
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.12
  firebase_storage: ^12.0.1
  video_thumbnail: ^0.5.3
  scroll_to_index: ^3.0.1
  grouped_list: ^5.1.2
  firebase_messaging: ^15.0.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  custom_map_markers: ^0.0.2+1
  flutter_polyline_points: ^2.0.0
  image: ^3.0.2
  photo_view: ^0.15.0
  hl_image_picker: ^1.2.12
  perfect_freehand: ^1.0.4
  align_positioned: ^4.0.1
  animated_text_kit: ^4.2.2
  flutter_screenutil: ^5.9.3
  image_gallery_saver: ^2.0.3
  video_player: ^2.6.0
  gradient_borders: ^1.0.1
  flutter_local_notifications: ^16.3.0
  flutter_background_service: ^5.0.5
  mime: ^1.0.5
  easy_image_viewer: ^1.5.0
  flutter_cache_manager: ^3.3.2
  cached_video_player_fork: ^2.1.1
  flutter_inappwebview: ^6.0.0
  uni_links: ^0.5.1
  firebase_dynamic_links: ^5.5.1
  bottom_picker: ^2.8.0
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (3 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

</details>

**Comment by danagbemava-nc** [comment]
Your issue is likely caused by some of the third party packages you use. I see a similar report of this issue in https://github.com/mogol/flutter_secure_storage/issues/694

You might want to try scanning the default flutter app to see if you still get these issues. If you do, then that is something we can address, otherwise there's not much for the flutter team to do. 

Given that your issue is likely caused by third-party packages, I will be closing this. If this does happen with the counter app, kindly leave a comment below and I will reopen this. Thank you
