### ISSUE TITLE
flutter web at nginx ubuntu server on root domain but returning If you are serving your web app in a path other than the root, change the href value below to reflect the base path you are serving from.

### ISSUE THREAD

**Issue by ThwinHAung** [flutter/flutter#150768]
`<!DOCTYPE html>`
`<html>`

`<head>`
`    <!--`
`If you are serving your web app in a path other than the root, change the`
`    href value below to reflect the base path you are serving from.`

`    The path provided below has to start and end with a slash "/" in order for`
`    it to work correctly.`
`    For more details:`
`    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base`
`    This is a placeholder for base href that will be replaced by the value of`
`    the --base-href argument provided to flutter build.`
`  -->`
`    <base href="/">`
`    <meta charset="UTF-8">`
`    <meta content="IE=Edge" http-equiv="X-UA-Compatible">`
`    <meta name="description" content="A new Flutter project.">`
`    <!-- iOS meta tags & icons -->`
`    <meta name="apple-mobile-web-app-capable" content="yes">`
`    <meta name="apple-mobile-web-app-status-bar-style" content="black">`
`    <meta name="apple-mobile-web-app-title" content="champions">`
`    <link rel="apple-touch-icon" href="icons/Icon-192.png">`
`    <!-- Favicon -->`
`    <link rel="icon" type="image/png" href="favicon.png" />`
`    <title>champions</title>`
`    <link rel="manifest" href="manifest.json">`
`</head>`
`<body>`
`    <script src="flutter_bootstrap.js" async></script>`
`</body>`
`</html>`

**Comment by ThwinHAung** [comment]
this is the configuration 
`server {
    listen 80;
    listen [::]:80;
    server_name championmaung.com www.championmaung.com;

    # Redirect all HTTP requests to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name championmaung.com www.championmaung.com;

    ssl_certificate /etc/letsencrypt/live/championmaung.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/championmaung.com/privkey.pem; # managed by Certbot
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_prefer_server_ciphers on;

    root /var/www/html/web;
    index index.html;

    # Serve Flutter web application
    location / {
        try_files $uri $uri/ /index.html;
        error_page 405 =200 $uri;
    }

    # Handle API requests
    location ^~ /api {
        alias /var/www/html/laravel_for_football/public;
        try_files $uri $uri/ @laravelapi;

        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            include fastcgi_params;
        }

        location ~ /\.ht {
            deny all;
        }
    }

    location @laravelapi {
        rewrite /api/(.*)$ /index.php?$1 last;
    }   

    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }

    # Custom error page for 404
    error_page 404 = /index.html;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
}

`

**Comment by darshankawar** [comment]
@ThwinHAung 
I am not sure why are you filing similar issues again, as we had mentioned in previous ones to raise this in StackOverflow.
Please check below issues to see if they help in your case or not:


https://github.com/flutter/flutter/issues/68686
https://github.com/flutter/flutter/issues/143054
https://stackoverflow.com/questions/67918435/flutter-web-app-in-a-subfolder-just-returns-to-the-root-page

Closing from here.
