### ISSUE TITLE
[Impeller] inline the second blur pass into the parent render pass.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#150720]
Right now, the second pass of the blur is rendered into a texture and then that texture is composited onto the entity pass that consumes the blur. By adjusting the positioning UVs, we could actually perform the second pass of the blur in the entity pass without another intermediary texture. This will reduce memory usage, as well as reduce the overhead of texture fill operations: https://github.com/flutter/flutter/issues/142154 .We've done similar things for other filters, for example see: https://github.com/flutter/engine/pull/40973

![image](https://github.com/flutter/flutter/assets/8975114/514321ec-8ded-46f0-9d36-3cda27864d08)

FYI @gaaclarke

**Comment by gaaclarke** [comment]
Here is a CPU profile of that benchmark.  CPU usage is >80% and 20% of that time is in creating render passes so eliminating render passes sounds promising.
<img width="884" alt="Screenshot 2024-06-26 at 3 45 07 PM" src="https://github.com/flutter/flutter/assets/30870216/b5bc6e75-e8b7-4be0-ad9d-820856345263">

**Comment by gaaclarke** [comment]
As a hack I disabled the second render pass and that gets us to 60fps on my phone.  Since we aren't GPU bound I think that's a fair approximation of this change.

**Comment by jonahwilliams** [comment]
Its not clear to me if we're CPU or GPU bound on iOS. Its possible there are some odd backpressure mechanisms in the Metal API. But on Vulkan devices we are absolutely bound by GPU.

**Comment by gaaclarke** [comment]
> Its not clear to me if we're CPU or GPU bound on iOS. Its possible there are some odd backpressure mechanisms in the Metal API. But on Vulkan devices we are absolutely bound by GPU

I have local changes right now or I'd show you but if you choose that screen on Xcode that shows the dial it has a bar graph of cpu vs gpu.  In that breakdown it is attributing almost everything to the cpu, not the gpu.
here
<img width="818" alt="Screenshot 2024-06-27 at 10 55 07 AM" src="https://github.com/flutter/flutter/assets/30870216/c56a748a-982c-440f-a28b-758ba9185c1d">

**Comment by gaaclarke** [comment]
I think that is mostly driver work also there are allocations and bzero/memset calls associated with creating a render pass.
