### ISSUE TITLE
interactive_media_ads README links to unrelated, "unverified uploader" pub package

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#150719]
The interactive_media_ads [README](https://github.com/flutter/packages/blob/b4d79b56305321d3e730766dd1d45bcc34441fd3/packages/interactive_media_ads/README.md?plain=1#L5) points to the unrelated https://pub.dev/packages/interactive_media_ads even though that package is unpublished.

cc @bparrishMines

**Comment by stuartmorgan** [comment]
That's the right package, I just hadn't transferred ownership from the role account to the verified publisher (a manual step for every new package). The publisher has been fixed now.

**Comment by stuartmorgan** [comment]
I was looking at the link rather than the SVG source URL; re-opening.
