### ISSUE TITLE
multiple `ColorScheme` seed colors

### ISSUE THREAD

**Issue by hugetiny** [flutter/flutter#150751]
### Use case

ColorScheme.fromSeed only got one source color to configure.
I think that's not enough,and hard to generate a beautiful looking theme

### Proposal

due to https://material-foundation.github.io/material-theme-builder/
I think flutter should provide a new way to configure with **6** core colors ,its a better way to generate better good looking themes

```
ColorScheme.fromCoreColors{
primary,
secondary,
tertiary，
error,
neutral,
neutralVariant
}
```

**Comment by darshankawar** [comment]
@hugetiny 
Can you check below and see if they help to address your case or not ?


https://github.com/flutter/flutter/issues/148359
https://github.com/flutter/flutter/pull/148916

**Comment by hugetiny** [comment]
> @hugetiny Can you check below and see if they help to address your case or not ?
> 
> #148359 #148916

DynamicSchemeVariant is not defined in 3.22.1
Althought the DynamicSchemeVariant  is in Flutter docs 
https://docs.flutter.dev/release/breaking-changes/new-color-scheme-roles

**Comment by darshankawar** [comment]
> DynamicSchemeVariant is not defined in 3.22.1
> Although the DynamicSchemeVariant is in Flutter docs

Most probably this is fixed as part of https://github.com/flutter/flutter/issues/148359 that you can check and confirm.

**Comment by nate-thegrate** [comment]
I believe that @hugetiny's original comment refers to the fact that [Material Theme Builder](https://material-foundation.github.io/material-theme-builder/) enables adjusting part of the color scheme (e.g. the Tertiary roles) without affecting other categories, whereas the Flutter framework currently does not have this option.

![color roles](https://github.com/user-attachments/assets/999c468b-cee0-4104-97bb-a92251da16a6)

I'd be interested in looking into this more and exploring possible solutions 👍

**Comment by nate-thegrate** [comment]
I recently discovered that the features requested here are available in the [flex_seed_scheme](https://pub.dev/packages/flex_seed_scheme) package.

It would probably be good to integrate this into the core Material library at some point, but for now, that package is a perfectly viable solution.
