### ISSUE TITLE
Add type checking to generics.

### ISSUE THREAD

**Issue by 07ami** [flutter/flutter#150846]
### Use case

I want to determine the type of a generic, but methods like T==List cannot meet my needs.
Because T may be either a List<String>or a List<int>, the method of T==List cannot be used to determine the type of T.
I used another method to determine the type of T, but I hope to have a simple way like T==List to determine the type of T.
Here is my partial code

`  AcadsocResponse.fromJson(dynamic json, {T Function(dynamic)? fromJson}) {
    // final defaultBody = T == List ? (json['Body'] ?? []) : (json['Body'] ?? {});
    final defaultBody =
        checkTIsList() ? (json['Body'] ?? []) : (json['Body'] ?? {});
    body = fromJson != null ? fromJson(defaultBody) : defaultBody;
    errorCode = json['ErrorCode'] ?? -1;
    msg = json['Msg'] ?? '';
    isSuccess = json['IsSuccess'] ?? false;
  }
  bool checkTIsList() {
    final arr = T.toString().split("<");
    if (arr.firstOrNull == 'List') {
      return true;
    }
    return false;
  }`

### Proposal

I want to determine the type of a generic, but methods like T==List cannot meet my needs.
Because T may be either a List<String>or a List<int>, the method of T==List cannot be used to determine the type of T.
I used another method to determine the type of T, but I hope to have a simple way like T==List to determine the type of T.
Here is my partial code

**Comment by danagbemava-nc** [comment]
Type-checking is a language feature and as such this would need to be reported on the dart-lang/sdk repository. 

Closing from here. Please check for duplicates before filing the issue. 

Thank you
