### ISSUE TITLE
https://cs.opensource.google/ does not seem to have the flutter/engine repo indexed

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#150866]
Here is a link in which I search for the string "web" in the engine repo, and it has no results: https://cs.opensource.google/search?q=web&ss=flutter%2Fengine

This is obviously incorrect. It appears that I can't get any search results for the engine repo at all for any search query, which leads me to believe it is not being properly indexed.

**Comment by christopherfujino** [comment]
I think this service has been deprecated, so I am closing this as inactionable. Feel free to re-open if you think I am mistaken and that there is a way forward for us to get this working (without maintaining open source code search ourselves).
