### ISSUE TITLE
Allow passing different entrypoints other than 'main'

### ISSUE THREAD

**Issue by bittuahlawat** [flutter/flutter#15089]
## Steps to Reproduce

Create two entry points in a new flutter project: `main` and `main2`.  Displaying `main2` is not possible, because `FlutterViewController` always points to the `main` entry point.

Even though `FlutterDartProject` allows you to the pass other entry points using this function:

```
- (void)launchInEngine:(shell::Engine*)engine
        withEntrypoint:(NSString*)entrypoint
        embedderVMType:(VMType)embedderVMType
                result:(LaunchResult)result
```

`FlutterViewController` calls this other method instead:

```
- (void)launchInEngine:(shell::Engine*)engine
        embedderVMType:(VMType)embedderVMType
                result:(LaunchResult)result
```

which in turn calls the first one with a hardcoded `main` as the entryPoint.

```
 switch (_vmTypeRequirement) {
    case VMTypeInterpreter:
      [self runFromSourceInEngine:engine withEntrypoint:@"main" result:result];
      return;
    case VMTypePrecompilation:
      [self runFromPrecompiledSourceInEngine:engine withEntrypoint:@"main" result:result];
      return;
    case VMTypeInvalid:
      break;
  }

```

We need ability to pass in the entry point via `FlutterViewController` rather than it selecting one on its own in order to embed multiple flutter views in the app.

**Comment by tvolkert** [comment]
This is possible now in the new Android embedding.  @gaaclarke do you know if it's possible in the iOS embedding?

**Comment by gaaclarke** [comment]
Yep, possible in iOS: https://github.com/flutter/engine/blob/5ef2c7968c7215acaffddd008a8ccabeb7cb6706/shell/platform/darwin/ios/framework/Headers/FlutterEngine.h#L145

**Comment by tvolkert** [comment]
Cool - I'm going to close this as fixed, then.
