### ISSUE TITLE
Cpp Crash happened in my emulator

### ISSUE THREAD

**Issue by lukelai18** [flutter/flutter#150830]
### Steps to reproduce

**Try to build the flutter, here is the command I use:**

```
flutter build hap --target-platform ohos-arm64 --release --local-engine=/Users/bingcha/PackageBox/flutter_flutter/engine/src/out/ohos_release_arm64    -v
```

**This is the error message:**

https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+ProcessException%3A+Failed+to+find+%22%2FUsers%2Fbingcha%2FDevEcoStudi
oProjects%2Fflutter_test_project2%2Fohos%2Fhvigorw%22+in+the+search+path.+Command%3A+%2FUsers%2Fbingcha%2FDevEcoStudioProjects%2Fflutter_te
st_project2%2Fohos%2Fhvigorw%2C+OS+error+code%3A+0&body=%23%23+Command%0A%60%60%60%0Aflutter+build+hap+--target-platform+ohos-arm64+--relea
se+--local-engine%3D%2FUsers%2Fbingcha%2FPackageBox%2Fsrc%2Fout%2Fohos_debug_unopt_arm64+-v%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.
+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AProcessException%3A+Failed+to+find+%22%2FUsers%2Fbingcha%2FDevEcoStudioProjects%2Fflutter_test_pr
oject2%2Fohos%2Fhvigorw%22+in+the+search+path.+Command%3A+%2FUsers%2Fbingcha%2FDevEcoStudioProjects%2Fflutter_test_project2%2Fohos%2Fhvigor
w%2C+OS+error+code%3A+0%0A%60%60%60%0A%230++++++LocalProcessManager.start+%28package%3Aprocess%2Fsrc%2Finterface%2Flocal_process_manager.da
rt%3A56%3A7%29%0A%231++++++ErrorHandlingProcessManager.start.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handli
ng_io.dart%3A696%3A24%29%0A%232++++++_run+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A568%3A20%29%0A%233++++++ErrorH
andlingProcessManager.start+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A695%3A12%29%0A%234++++++hvigorwTask+%28packa
ge%3Aflutter_tools%2Fsrc%2Fohos%2Fhvigor.dart%3A295%3A28%29%0A%235++++++assembleHap+%28package%3Aflutter_tools%2Fsrc%2Fohos%2Fhvigor.dart%3
A326%3A10%29%0A%3Casynchronous+suspension%3E%0A%236++++++OhosHvigorBuilder.buildHap+%28package%3Aflutter_tools%2Fsrc%2Fohos%2Fhvigor.dart%3
A724%3A28%29%0A%3Casynchronous+suspension%3E%0A%237++++++BuildHapCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fbuild_hap
.dart%3A69%3A5%29%0A%3Casynchronous+suspension%3E%0A%238++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2
Frunner%2Fflutter_command.dart%3A1257%3A27%29%0A%3Casynchronous+suspension%3E%0A%239++++++AppContext.run.%3Canonymous+closure%3E+%28package
%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2310+++++CommandRunner.runCommand+%28package%
3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous+suspension%3E%0A%2311+++++FlutterCommandRunner.runCommand.%3Canonymous+closure
%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A283%3A9%29%0A%3Casynchronous+suspension%3E%0A%2312+++++AppCon
text.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%23
13+++++FlutterCommandRunner.runCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A229%3A5%29%0A%3Casynchrono
us+suspension%3E%0A%2314+++++run.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Frunner.dart%3A64%3A9%29%0A%3C
asynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%1B%5B33m%5B%21%5D%1B%5B39m+Flutter+%28Channel+master%2C+3.7.12-ohos%2C+on+macOS+14.4.
1+23E224+darwin-arm64%2C+locale+zh-Hans-US%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.7.12-ohos+on+channel+master+at+%2FUsers%2
Fbingcha%2FPackageBox%2Fflutter_flutter%0A++++%1B%5B33m%21%1B%5B39m+Upstream+repository+https%3A%2F%2Fgitee.com%2Fopenharmony-sig%2Fflutter
_flutter.git+is+not+a+standard+remote.%0A++++++Set+environment+variable+%22FLUTTER_GIT_URL%22+to+https%3A%2F%2Fgitee.com%2Fopenharmony-sig%
2Fflutter_flutter.git+to+dismiss+this+error.%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Framework+revision+baa9b985d4+%286+weeks+ago%29%2C+2024-05-1
7+06%3A19%3A35+%2B0000%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+1a65d409c7%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+2.19.6%0
A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.20.1%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Pub+download+mirror+https%3A%2F%2Fpub.flutter-io
.cn%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+download+mirror+https%3A%2F%2Fstorage.flutter-io.cn%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+If+thos
e+were+intentional%2C+you+can+disregard+the+above+warnings%3B+however+it+is+recommended+to+use+%22git%22+directly+to+perform+update%0A+++++
+checks+and+upgrades.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+HarmonyOS+toolchain+-+develop+for+HarmonyOS+devices%0A++++%1B%5B32m%E2%80%A2%1
B%5B39m+OpenHarmony+Sdk+location%3A+%2FUsers%2Fbingcha%2FDownloads%2Fdevecostudio-mac-arm-5.0.3.200%2Fsdk%2FM1SDK%2C+available+api+versions
+has%0A++++++%5BHarmonyOS-NEXT-DB1%2C+HarmonyOS-NEXT-DP2%5D%0A%0A%1B%5B31m%5B%E2%9C%97%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+
devices%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Unable+to+locate+Android+SDK.%0A++++++Install+Android+Studio+from%3A+https%3A%2F%2Fdeveloper.andr
oid.com%2Fstudio%2Findex.html%0A++++++On+first+launch+it+will+assist+you+in+installing+the+Android+SDK+components.%0A++++++%28or+visit+http
s%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall%2Fmacos%23android-setup+for+detailed+instructions%29.%0A++++++If+the+Android+SDK+has+b
een+installed+to+a+custom+location%2C+please+use%0A++++++%60flutter+config+--android-sdk%60+to+update+to+that+location.%0A%0A%0A%1B%5B31m%5
B%E2%9C%97%5D%1B%5B39m+Xcode+-+develop+for+iOS+and+macOS%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Xcode+installation+is+incomplete%3B+a+full+insta
llation+is+necessary+for+iOS+development.%0A++++++Download+at%3A+https%3A%2F%2Fdeveloper.apple.com%2Fxcode%2Fdownload%2F%0A++++++Or+install
+Xcode+via+the+App+Store.%0A++++++Once+installed%2C+run%3A%0A++++++++sudo+xcode-select+--switch+%2FApplications%2FXcode.app%2FContents%2FDe
veloper%0A++++++++sudo+xcodebuild+-runFirstLaunch%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+CocoaPods+not+installed.%0A++++++++CocoaPods+is+used+to
+retrieve+the+iOS+and+macOS+platform+side%27s+plugin+code+that+responds+to+your+plugin+usage+on+the+Dart+side.%0A++++++++Without+CocoaPods%
2C+plugins+will+not+work+on+iOS+or+macOS.%0A++++++++For+more+info%2C+see+https%3A%2F%2Fflutter.dev%2Fplatform-plugins%0A++++++To+install+se
e+https%3A%2F%2Fguides.cocoapods.org%2Fusing%2Fgetting-started.html%23installation+for+instructions.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m
+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+%2FApplications%2FGoogle+Chrome.app%2FContents%2FMacOS%2FGoogle+C
hrome%0A%0A%1B%5B33m%5B%21%5D%1B%5B39m+Android+Studio+%28not+installed%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+not+found%3B+dow
nload+from+https%3A%2F%2Fdeveloper.android.com%2Fstudio%2Findex.html%0A++++++%28or+visit+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Fi
nstall%2Fmacos%23android-setup+for+detailed+instructions%29.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.90.0%29%0A++++%1B%
5B32m%E2%80%A2%1B%5B39m+VS+Code+at+%2FApplications%2FVisual+Studio+Code.app%2FContents%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+
can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3DDart-Code.flutter%0A%0A%1B%5B
32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%284+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+000000000000000000000000121601ad+%28mobile
%29+%E2%80%A2+000000000000000000000000121601ad+%E2%80%A2+ohos-arm64+++++%E2%80%A2+Ohos+OpenHarmony-4.1.7.5+%28API+11%29%0A++++%1B%5B32m%E2%
80%A2%1B%5B39m+127.0.0.1%3A5555+%28mobile%29+++++++++++++++++++%E2%80%A2+127.0.0.1%3A5555+++++++++++++++++++%E2%80%A2+ohos-arm64+++++%E2%80
%A2+Ohos+OpenHarmony-5.0.0.25+%28API+12%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+macOS+%28desktop%29+++++++++++++++++++++++++++%E2%80%A2+macos+
+++++++++++++++++++++++++++%E2%80%A2+darwin-arm64+++%E2%80%A2+macOS+14.4.1+23E224+darwin-arm64%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28
web%29++++++++++++++++++++++++++++++%E2%80%A2+chrome+++++++++++++++++++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+126.0.6478.
115%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+HTTP+Host+Availability%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+required+HTTP+hosts+are+available%0
A%0A%1B%5B33m%21%1B%5B39m+Doctor+found+issues+in+4+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3
A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2
A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%
3A+dev%0A%2A%2ACreation+framework+version%2A%2A%3A+0d31f3638319e904863ba00994751fa81c94116c%0A%0A&labels=tool%2Csevere%3A+crash

### Expected results

Build success, but it failed.

### Actual results

Build failed. No sure what contained in the flutter engine package, it asks me to find a hvigorw file, but it doesn't exist in my PC.

```
 [        ] Oops; flutter has exited unexpectedly: "ProcessException: Failed to find
           "/Users/bingcha/DevEcoStudioProjects/flutter_test_project2/ohos/hvigorw" in the search path.
             Command: /Users/bingcha/DevEcoStudioProjects/flutter_test_project2/ohos/hvigorw ".
```

### Code sample

```dart
// Just the simplist flutter sample
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

 flutter_test_project2 flutter doctor -v

```
[!] Flutter (Channel master, 3.7.12-ohos, on macOS 14.4.1 23E224 darwin-arm64, locale zh-Hans-US)
    • Flutter version 3.7.12-ohos on channel master at /Users/bingcha/PackageBox/flutter_flutter
    ! Upstream repository https://gitee.com/openharmony-sig/flutter_flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://gitee.com/openharmony-sig/flutter_flutter.git to dismiss this error.
    • Framework revision baa9b985d4 (6 weeks ago), 2024-05-17 06:19:35 +0000
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

[✓] HarmonyOS toolchain - develop for HarmonyOS devices
    • OpenHarmony Sdk location: /Users/bingcha/Downloads/devecostudio-mac-arm-5.0.3.200/sdk/M1SDK, available api versions has
      [HarmonyOS-NEXT-DB1, HarmonyOS-NEXT-DP2]

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • 000000000000000000000000121601ad (mobile) • 000000000000000000000000121601ad • ohos-arm64     • Ohos OpenHarmony-4.1.7.5 (API 11)
    • 127.0.0.1:5555 (mobile)                   • 127.0.0.1:5555                   • ohos-arm64     • Ohos OpenHarmony-5.0.0.25 (API 12)
    • macOS (desktop)                           • macos                            • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                              • chrome                           • web-javascript • Google Chrome 126.0.6478.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 4 categories.
```

**Comment by danagbemava-nc** [comment]
You are using the open-harmony fork of flutter as such this issue should be reported on their repo. The file the build is complaining about is from the open harmony fork and not flutter itself. https://gitee.com/openharmony-sig/flutter_flutter/issues

Closing from here. 

Thank you

**Comment by cs453146042** [comment]
我也遇到了相同的问题 请问这个问题是否解决了呢
