### ISSUE TITLE
When stopping on the webview page, switching to another application and then coming back, the display is blank.

### ISSUE THREAD

**Issue by StanleyCocos** [flutter/flutter#150833]
### Steps to reproduce

1. Start the application and stay on the webview page
2. Go to the background and start other applications
3. Back to my app again

### Expected results

A blank appears, specifically the webView widget is missing.
It may be related to the device. I am using SM-S9110. I have not found this problem on other devices.

### Actual results

Stop on the webview page and start other applications

### Code sample

No changes, I just ran the demo

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/22318878/f90f4284-4255-4802-bdf7-80aeb00fe665

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    ! CocoaPods 1.11.2 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (2 available)            

[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @StanleyCocos, this should be fixed in the latest version of flutter stable (3.22.2). Can you upgrade to this version to see if you still experience this issue?

**Comment by danagbemava-nc** [comment]
Thanks for confirming the fix. 

See https://github.com/flutter/flutter/issues/146499 for details. 

Closing as this has been fixed on the latest stable version. 

Thank you
