### ISSUE TITLE
Pin transitive deps for production dependencies, not just dev dependencies

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15080]
Context is in the full discussion of https://github.com/flutter/flutter/issues/14992

We currently [pin our transitive dependencies to specific versions](https://github.com/flutter/flutter/blob/bcdbed962802d29da0cc405473a5a93bf77f17a0/packages/flutter/pubspec.yaml#L22) to ensure hermeticity in our pub package versions.  However, we only do so in the `dev_dependencies` section of our `pubspec.yaml` files.  We should do so in our main `dependencies` section as well.

**Comment by jonahwilliams** [comment]
#15416 will simplify the dependencies of the package:flutter. flutter_driver and flutter_test can be updated as well.

@tvolkert Do we pin the transitive deps in `flutter create` templates currently?

**Comment by jonahwilliams** [comment]
Ahh, we don't currently.  These should probably start out with correctly pinned dev and production deps too
