### ISSUE TITLE
ios-deploy 1.9.2 is installed but required

### ISSUE THREAD

**Issue by TorzuoliH** [flutter/flutter#15082]
## Steps to Reproduce

When running `flutter doctor` command, I got some warnings, especially one about my ios-deploy version that is not updated.

```
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ ios-deploy out of date (1.9.2 is required). To upgrade:
        brew upgrade ios-deploy
```

But when running the upgrade: `Error: ios-deploy 1.9.2 already installed`.

## Logs

No need.

## Flutter Doctor

```
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.4 17E160e, locale fr-FR)
    • Flutter version 0.1.5 at /Users/Hugo/flutter
    • Framework revision 3ea4d06340 (8 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9Q117m
    • ios-deploy 1.9.1
    ✗ ios-deploy out of date (1.9.2 is required). To upgrade:
        brew upgrade ios-deploy
    • CocoaPods version 1.4.0

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.2

[!] Connected devices
    ! No devices available

! Doctor found issues in 4 categories.
```

Paste the output of running `flutter doctor -v` here.

I'm using Xcode 9.3 on macOS 10.13.4.

**Comment by Hixie** [comment]
cc @xster @cbracken

**Comment by cbracken** [comment]
@TorzuoliH Thanks for reporting this.

Based on the doctor output (`• ios-deploy 1.9.1`), It looks like you have version 1.9.1 installed. It sounds like running `brew upgrade ios-deploy` isn't working. 

To resolve this, can you run the following commands and log the output here?
1. `brew --version`
1. `brew info ios-deploy`
1. `brew update` (older versions of homebrew require this)
1. `brew upgrade ios-deploy` (I assume this may give the same error as before)
1. `brew info ios-deploy` (again, just so we can see if it's now 1.9.2)
1. `brew upgrade` (if the above upgrade didn't get ios-deploy up to date, hopefully this did)

If you're still seeing the doctor error after the above, can you try this and paste the output?
`brew reinstall ios-deploy`

**Comment by UltimoTG** [comment]
I'm using Xcode 9.2 on macOS 10.13.3.

I was getting the same error. I ran `brew reinstall ios-deploy` which displayed the following:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/ios-deploy
Target /usr/local/bin/ios-deploy
already exists. You may want to remove it:
  rm '/usr/local/bin/ios-deploy'

To force the link and overwrite all conflicting files:
  brew link --overwrite ios-deploy

To list all files that would be deleted:
  brew link --overwrite --dry-run ios-deploy
```

Then, once I ran `brew link --overwrite ios-deploy` the error disappeared when running `flutter doctor`

**Comment by TorzuoliH** [comment]
Hello guys, sorry, haven't time to test with your instructions.

Thanks @UltimoTG, I will do the same on my side and confirm that it's well working :)

**Comment by TorzuoliH** [comment]
@cbracken 

1. `Homebrew 1.5.7`

2. `ios-deploy: stable 1.9.2 (bottled), HEAD`

3. Done

4. Same error

5. `ios-deploy: stable 1.9.2 (bottled), HEAD`

6. Still got the error when `flutter doctor`

By doing `brew reinstall ios-deploy` I got error too, so I tried `brew link --overwrite ios-deploy` and it worked!

Output: `Linking /usr/local/Cellar/ios-deploy/1.9.2... 3 symlinks created`

Thanks to @UltimoTG 😄

**Comment by androidheight** [comment]
@UltimoTG  I followed all the mentioned steps but i found that some of the developer might not given allowed for the developer mode so below is the command which i used to resolve the issue.

`        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
`

> 
> Abhisheks-MBP:~ minduses$ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-IN)
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
> [✓] Android Studio (version 3.1)
> [✓] Connected devices (1 available)

Hope it might help . others.

**Comment by gautamkishore** [comment]
Thanks @androidheight . At last, your stuff worked.

**Comment by qifali** [comment]
I face the same problem to , but my problem is i forgot i'm already install ios-deploy before through nodejs npm, so ,,,, I'm very confuse get the error below
```
 • ios-deploy 1.8.6
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
```
solution is just uninstall it by 
`npm uninstall -g ios-deploy`

hope it helps ...

**Comment by wanghuajian620** [comment]
解决方案：
npm uninstall -g  ios-deploy
忘记自己之前安装过，所以执行这条命令即可，取消全局安装

**Comment by ajonno** [comment]
I've tried all the above with no success. not the greatest of onboarding experiences for Flutter so far.. :-(

i know my iOS and Android native environments are fine as I develop in them all the time.

➜ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.30.1)
[✓] Connected device (1 available)

➜ brew upgrade ios-deploy
Error: ios-deploy 1.9.4 already installed

**Comment by zoechi** [comment]
@ajonno did you try https://github.com/flutter/flutter/issues/15082#issuecomment-370883723 ?

**Comment by asgeo1** [comment]
If it helps anyone, I too was having this issue, but the steps above weren't helping so found a different solution:

I had an issue where I had the 1.9.2 version of `ios-deploy` installed via npm (`/Users/asgeo1/.node/bin/ios-deploy`) and this was taking precedence in my $PATH, so the 1.9.4 version from homebrew was not being found.

I'm not sure why I had the npm version installed, or if it's different from the homebrew version...  So I just uninstalled the npm version (`npm uninstall ios-deploy -g`) and it's working now.

**Comment by f-hermes** [comment]
Thanks @asgeo1! I had the same issue and your solution worked for me.

**Comment by xzwgithub** [comment]
run:

npm uninstall -g ios-deploy

display:

dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
Abort trap: 6

how to solve it ?

**Comment by leopic** [comment]
In my case I couldn't remove the package using `npm uninstall` for whatever reason, so I located the package:
`$: identify ios-deploy`
And then forcefully removed it
`$: rm -rf ~/.npm-packages/lib/node_modules/ios-deploy/`
It was finally gone by then, I re-installed it using homebrew and it worked like a charm.

Using Mojave
