### ISSUE TITLE
Fail if `--rbe` is provided explicitly but RBE can't be used

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#150884]
Related issue: https://github.com/flutter/flutter/issues/150881

## observed behavior
If you have the wrong macos sdk installed, rbe builds will fallback to local builds.

## expected behavior
I expect the build to fail with a note of mixmatched macos sdks.

**Comment by matanlurey** [comment]
I'm confused what the expectation is here - it might be valid to have multiple MacOS SDKs installed or switch between them. Fallback to local builds if RBE cache is not available makes sense generally. What is the expectation?

**Comment by gaaclarke** [comment]
I'd like the behavior where we get RBE or fail.  That way I don't have to discover the hard way that things are broken after potentially wasting a lot of time.  Maybe we could make the fallback work in the absence of `--rbe` or `--no-rbe`.  But if someone explicitly specifies `--rbe` it's RBE or fail.

**Comment by matanlurey** [comment]
@gaaclarke Want to take a shot at implementing this one?

**Comment by gaaclarke** [comment]
I'm in the middle of some heavy graphics stuff, after that I'm open to it.

**Comment by matanlurey** [comment]
I ended up doing this on accident in another refactor.

We will now have `--build-strategy=remote`, which _only_ uses RBE Builds.
