### ISSUE TITLE
Logging output crosstalk on iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15086]
On a physical device, install the production Hamilton app from the app store (the app prints to console even in production). 

Open the Hamilton app. Then `flutter run` the Gallery app from the flutter repo. 

Log outputs from the Hamilton app will appear in the console while the Gallery app is building and after it's running if you put the Hamilton app back to the foreground. 

cc @cbracken for knowledge on log output.

**Comment by Hixie** [comment]
Yeah, we just output output from all flutter apps, because IIRC we don't know the pid of the process we care about.

cc @tvolkert

**Comment by tvolkert** [comment]
@cbracken has since re-worked the device log code, but I think @Hixie is right

**Comment by cbracken** [comment]
That is correct. We’re still filtering by app name/tag IIRC.

**Comment by jmagman** [comment]
On iOS 13 the logs come from the connected VM service.  I don't think we'll fix this for <iOS 13.
@xster can we close this?

**Comment by xster** [comment]
SG
