### ISSUE TITLE
MissingPluginException when adding FlutterViewController manually

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#15085]
Platform: iOS
Flutter: master

I'm embedding a `FlutterViewController` into a `UITabBarController` and I'm getting the following exception (for firebase_auth plugin):

```
Unhandled exception:
MissingPluginException(No implementation found for method startListeningAuthState on channel plugins.flutter.io/firebase_auth)
```

`GeneratedPluginRegistrant.register(with: self)` is being called in the AppDelegate.

**Comment by xster** [comment]
cc @mravn-google for help with the plugins. 

Sounds like the pods are correctly installed. Do we support plugin registration in swift projects? From a brief look, seems like the tool's plugins.dart is writing objective-c code.

**Comment by lukef** [comment]
I've added the generated objective-c code and i've got a bridging header. That part all seems to be running but for whatever reason it's not making it over to the Dart side of things.

**Comment by lukef** [comment]
Related (?) you seemingly cannot use the `use_frameworks!` option in the Podfile when you're using plugins either. If you do that then the header files for the plugins will not be found during the build. The, current, best approach is to use the bridging header instead. I'm not sure if that's documented anywhere (or intended) but it definitely _seems_ to be the case after many hours of trying to make the other way work.

**Comment by najeira** [comment]
By default, Flutter plug-in mechanism expects `rootViewController` is `FlutterViewController`.

See: [FlutterAppDelegate.mm#L215](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm#L215)

If you set `UITabBarController` to `rootViewController`, you should override `rootFlutterViewController`, `binaryMessenger` and `textures`.

**Comment by lukef** [comment]
Thanks! I have to admit I was pretty fried on Friday following a big code conversion so I definitely missed this. It's exactly what I needed. Thanks again!

**Comment by xster** [comment]
Seems like this is resolved. I'll close this bug.
