### ISSUE TITLE
iOS crash when converting `ui.Image` to PNG: image_encoding.cc: Could not convert raster image to PNG

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#150904]
### Steps to reproduce

On iOS 17.5 and using the latest Flutter beta channel, I get the following crash when trying to convert an image to PNG: 

```
[ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.
```

The image is this one (download the large size, 1920x1283):

https://www.pexels.com/photo/man-wearing-eyeglasses-and-brown-jacket-842811/

I load the image as a `ui.Image`, then I use this code to convert the `ui.Image` to PNG:

```dart
Future<File> writeImageToTempPngFile(ui.Image image) async {
  if (tempDir == null) {
    throw 'Could not get temp dir';
  }
  final bytes = await image.toByteData(format: ui.ImageByteFormat.png);  // CRASHES HERE
  if (bytes == null) {
    throw 'Could not convert image format';
  }
  final tempFile = File('${tempDir?.path}/${randomIdentifier()}.png');
  await tempFile.writeAsBytes(bytes.buffer.asUint8List());
  return tempFile;
}
```

The crash seem similar to this (now fixed) Impeller issue with wide gamut images (although the image above is just an sRGB JPEG image): https://github.com/flutter/flutter/issues/133942

The fix suggested for that issue also works here -- the following code does not crash, and successfully converts the image:

```dart
Future<File> writeImageToTempPngFile(ui.Image image) async {
  if (tempDir == null) {
    throw 'Could not get temp dir';
  }
  final bytes = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
  if (bytes == null) {
    throw 'Could not convert image format';
  }
  Completer<ByteData?> completer = Completer();
  ui.decodeImageFromPixels(
    Uint8List.view(bytes.buffer),
    image.width,
    image.height,
    ui.PixelFormat.rgba8888,
    (result) async {
      completer.complete(
        await result.toByteData(format: ui.ImageByteFormat.png),
      );
    },
  );
  final bytesPng = await completer.future;
  if (bytesPng == null) {
    throw 'Could not convert image to PNG';
  }
  final tempFile = File('${tempDir?.path}/${randomIdentifier()}.png');
  await tempFile.writeAsBytes(bytesPng.buffer.asUint8List());
  return tempFile;
}
```

### Expected results

The app should not crash.

### Actual results

The app crashes.

### Code sample

See above

### Screenshots or Video

N/A

### Logs

The only log entry is the error given above.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 14.5 23F79 darwin-x64, locale en-US)
    • Flutter version 3.23.0-0.1.pre on channel beta at /Users/luke/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (3 weeks ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/luke/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.91.20240529

[✓] Connected device (3 available)            
    • iPhone SE (2nd generation) (mobile) • 00008030-000C38343C23402E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                     • macos                     • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)                        • chrome                    • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
The error looks similar to one reported at https://github.com/flutter/flutter/issues/148851 which is fixed and landed on master channel. 

However, I also checked this issue on beta channel (same version as yours) but couldn't reproduce it using the complete sample code below. The image can be written as expected without crashing. Can you try and confirm? 

<details>
<summary>Sample code</summary>

```dart
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: const Center(
        child: Text('Show'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showImage,
        child: const Icon(Icons.image),
      ),
    );
  }

  Future<ui.Image> loadImageFromAsset(String assetName) async {
    var buffer = await ImmutableBuffer.fromAsset(assetName);
    var codec = await ui.instantiateImageCodecFromBuffer(buffer);
    var frame = await codec.getNextFrame();
    return frame.image;
  }

  Future<void> _showImage() async {
    final image = await loadImageFromAsset('assets/pexels-olly-842811.jpg');
    final file = await writeImageToTempPngFile(image);
    print('File: ${file.path}');
  }

  Future<File> writeImageToTempPngFile(ui.Image image) async {
    final Directory tempDir = await getTemporaryDirectory();
    final bytes = await image.toByteData(format: ui.ImageByteFormat.png); // CRASHES HERE
    if (bytes == null) {
      throw 'Could not convert image format';
    }
    final tempFile = File('${tempDir.path}/abc.png');
    await tempFile.writeAsBytes(bytes.buffer.asUint8List());
    return tempFile;
  }
}

```
</details>

**Comment by lukehutch** [comment]
@huycozy Thanks for trying to reproduce this. Sorry, I forgot there is one other conversion step that was not in the code I showed (so I can't reproduce with your code either).

Please try this minimal reproducer (which does crash on my system):

https://github.com/lukehutch/flutter_png_crash

**Comment by lukehutch** [comment]
In general, can you please add some print statements to the C++ code when the `Could not convert raster image to PNG` message is displayed, explaining exactly why the image can't be converted? This could save everybody a lot of time in the future, since there have been at least two different instances of these bugs now (maybe three).

**Comment by huycozy** [comment]
Thanks for providing sample code (it contains 3rd packages, though). I have downloaded new XCode version to get iOS 17.5 (emulator) but still can't reproduce the crash.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/a727959d-e483-4a6a-8104-550d62c56039
</details>

The image is cropped and written as expected. Can you retry your sample code and provide the entire crash stack trace if any?

**Comment by lukehutch** [comment]
> (it contains 3rd packages, though)

Yes, I had to do that to get this as close as possible to my actual crashing app, so that it would actually crash... I'm sure the example code could be further minimized, but I don't have a lot of time to go through the exact codepath that the cropper takes.

@huycozy There is no stack trace -- it dies immediately at

```
[ERROR:flutter/lib/ui/painting/image_encoding.cc(215)] Could not convert raster image to PNG.
```

In the Xcode debugger, the debug view stops in the assembly code view, and I can't see an actual usable stacktrace anywhere. Is there a way to get `lldb` to print stacktraces for all threads? (In gdb, it is `thread apply all bt`.)

**Comment by huycozy** [comment]
Thanks. My last question: Can you try switching to Flutter master channel and retry? I see the error is exactly similar to https://github.com/flutter/flutter/issues/148851 and it's fixed recently (only available on master channel). It would be appreciated if you could try running sample code at https://github.com/flutter/flutter/issues/148851#issue-2310317810 as well.

**Comment by lukehutch** [comment]
@huycozy This is not a wide-gamut image, it is just a regular sRGB 888 image. So that particular fix should not address this issue, if the crash in the other bug was caused by wide gamut images.

However, I can confirm that after switching to master, I can no longer reproduce the crash. So I guess the wide gamut fix must have fixed whatever else was going on for my usecase.

My usecase was definitely comparable to the code in the comment you linked. I can confirm that that code crashes in the same way as my code when using the Flutter beta channel, but not when using the master channel.

So thanks! I'll close this as fixed.

**Comment by huycozy** [comment]
Thank you for confirming that.
