### ISSUE TITLE
double values ​​multiplied by 100 does not correctly calculate

### ISSUE THREAD

**Issue by Anullos** [flutter/flutter#150921]
### Steps to reproduce

4.63 * 100 = 463
4.64 * 100 = 463.99999994
3.15 * 100 = 315
5.64 * 100 = 564
4.65 * 100 = 465.00000006

### Expected results

4.63 * 100 = 463
4.64 * 100 = 464
3.15 * 100 = 315
5.64 * 100 = 564
4.65 * 100 = 465

### Actual results

4.63 * 100 = 463
4.64 * 100 = 463.99999994
3.15 * 100 = 315
5.64 * 100 = 564
4.65 * 100 = 465.00000006

### Code sample

<details open><summary>Code sample</summary>

```dart
const test = 4.64 * 100;
print('test: $test');
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
This is not a bug, it is correct to within the precision of a double.  Dart doubles are represented using the IEEE 754 standard and this is the standard behaviour. 

You can find out more about how numbers work in dart in https://dart.dev/guides/language/numbers. You can also read on the standard here https://en.wikipedia.org/wiki/IEEE_754

PS: You'd get the same thing in Java and a few other languages that use the IEEE 754 standard. 

PPS: This is a language issue and not a flutter issue. Next time, please file issues like this on the dart-lang repo. 

Thank you
