### ISSUE TITLE
iOS crash When MetalCaptureEnabled is true

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#150926]
### Steps to reproduce

I am using Flutter in a game app, and the game is based on the Unity engine.
In the Info.plist file, set MetalCaptureEnabled to true，
WhenI navigate to a FlutterViewController , the app consistently crashes, particularly on devices running iOS 14.x OS.

### Expected results

NO crash

### Actual results

Crash

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```
Exception Type:  SIGSEGV(SEGV_ACCERR)
Exception Subtype: KERN_INVALID_ADDRESS at 000000000000000000
Triggered by Thread:  81 io.worker.3


libMTLCapture.dylib 0x00000001258cc68c   GTMTLGuestAppClient_initGlobalTransportWithHostURL + 264340
libMTLCapture.dylib 0x00000001258cc630  GTMTLGuestAppClient_initGlobalTransportWithHostURL + 264248
libMTLCapture.dylib 0x00000001258105a0  0x0000000125800000 + 66976
libMTLCapture.dylib 0x000000012581011c  0x0000000125800000 + 65820
libMTLCapture.dylib 0x00000001258100b8  0x0000000125800000 + 65720
libMTLCapture.dylib 0x0000000125882d88  GTMTLGuestAppClient_getUnsupportedFenumInfo + 136084

Flutter 0x000000011186660c impeller::RenderPassMTL::EncodeCommands(std::_fl::shared_ptr<impeller::Allocator> const&, id<MTLRenderCommandEncoder>) const (../../flutter/impeller/renderer/backend/metal/render_pass_mtl.mm:497)

Flutter 0x000000011185cc18 std::_fl::__function::__func<fml::internal::CopyableLambda<impeller::CommandBufferMTL::EncodeAndSubmit(std::_fl::shared_ptr<impeller::RenderPass> const&)::$_0>, std::_fl::allocator<fml::internal::CopyableLambda<impeller::CommandBufferMTL::EncodeAndSubmit(std::_fl::shared_ptr<impeller::RenderPass> const&)::$_0> >, void ()>::operator()() (../../flutter/impeller/renderer/backend/metal/command_buffer_mtl.mm:229)

Flutter 0x000000011161d018 fml::ConcurrentMessageLoopDarwin::ExecuteTask(std::_fl::function<void()> const&) (../../flutter/fml/platform/darwin/concurrent_message_loop_factory.mm:18)


Flutter0x0000000111616cfc
__thread_proxy<std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct> >, (lambda at ../../flutter/fml/concurrent_message_loop.cc:17:27)> > (../../third_party/libcxx/include/vector:1372)
1

libsystem_pthread.dylib
0x00000001f33f39a4
_pthread_start + 148

```
### Flutter Doctor output

```
[!] Flutter (Channel [user-branch], 3.19.6, on macOS 14.3 23D56 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.19.6 on channel [user-branch] at /Users/chengjian/soft/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 54e66469a9 (2 个月前), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades
```

**Comment by cj3479** [comment]
@darshankawar can you help to handle the issue?

**Comment by cj3479** [comment]
@jonahwilliams @gaaclarke can you help to handle the issue?

**Comment by darshankawar** [comment]
> @jonahwilliams @gaaclarke can you help to handle the issue?

@cj3479 Please don't randomly tag team members for attention. All the incoming issues go through a triage process.

**Comment by darshankawar** [comment]
> I am using Flutter in a game app, and the game is based on the Unity engine.
> In the Info.plist file, set MetalCaptureEnabled to true，
> WhenI navigate to a FlutterViewController , the app consistently crashes,

Can you provide us a repo that we can clone and verify this further ?

Also, check if by enabling [this](https://github.com/flutter/flutter/issues/140901#issue-2064491503) setting, is there any difference you observe or not.

**Comment by cj3479** [comment]
> > I am using Flutter in a game app, and the game is based on the Unity engine.
> > In the Info.plist file, set MetalCaptureEnabled to true，
> > WhenI navigate to a FlutterViewController , the app consistently crashes,
> 
> Can you provide us a repo that we can clone and verify this further ?
> 
> Also, check if by enabling [this](https://github.com/flutter/flutter/issues/140901#issue-2064491503) setting, is there any difference you observe or not.

Sorry I cannot provide the code, It is confidential，You can embed  a flutter view controller into in a game app that is based on the Unity engine,


Additional, I have enabled [this](https://github.com/flutter/flutter/issues/140901#issue-2064491503) setting, but it still crash

**Comment by darshankawar** [comment]
> You can embed a flutter view controller into in a game app that is based on the Unity engine,

I don't have much exposure using unity engine, so it'll take time to come up with one. If you upgrade to latest stable and re-run your scenario, can you check if it still crashes or not ?

**Comment by cj3479** [comment]
> > You can embed a flutter view controller into in a game app that is based on the Unity engine,
> 
> I don't have much exposure using unity engine, so it'll take time to come up with one. If you upgrade to latest stable and re-run your scenario, can you check if it still crashes or not ?

Yes. I upgrade to latest stable which is 3.22.2 and It still crash

**Comment by huycozy** [comment]
@cj3479 Similar to https://github.com/flutter/flutter/issues/150929#issuecomment-2224715020, it would be helpful if you could provide a complete sample code so that we can look into it easily. Thanks!
