### ISSUE TITLE
iOS crash When UIAccessibility

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#150929]
### Steps to reproduce

 Flutter in a game app, and the game is based on the Unity engine.
Some users have these crash, The stack information is as follows because it's an online crash, I don't know how to reproduce it

### Expected results

no_crash

### Actual results

crash

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```console
Exception Type: SIGBUS(BUS_ADRALN)

Triggered by Thread: 0

libobjc.A.dylib      0x0000000180191260      objc_retain + 16
UIAccessibility     0x000000018d2666a4    -[NSObject(UIAccessibilityAutomation) _accessibilityUserTestingParent] + 96
UIAccessibility     0x000000018d236f98     -[NSObject(AXPrivCategory) _iosAccessibilityAttributeValue:] + 2960
UIAccessibility     0x000000018d267f4c      _accessibilityAttributesForObject + 384
UIAccessibility     0x000000018d267718     -[NSObject(UIAccessibilityAutomation) _accessibilityUserTestingSnapshotDescendantsWithAttributes:maxDepth:maxChildren:maxArrayCount:honorsModalViews:] + 848

UIAccessibility   0x000000018d269240  
-[NSObject(UIAccessibilityAutomation)_accessibilityUserTestingSnapshotWithOptions:] + 1092

UIAccessibility    0x000000018d2356f0
-[NSObject(AXPrivCategory) _iosAccessibilityAttributeValue:forParameter:] + 11452

UIKit            0x00000001b61870bc
-[UIApplicationAccessibility _iosAccessibilityAttributeValue:forParameter:] + 276

UIAccessibility     0x000000018d2117a4
_copyParameterizedAttributeValueCallback + 404

AXRuntime        0x000000018c1a17b8
___AXXMIGCopyParameterizedAttributeValue_block_invoke + 60

AXRuntime       0x000000018c1a10c0    _handleNonMainThreadCallback + 60

AXRuntime       0x000000018c1a165c   _AXXMIGCopyParameterizedAttributeValue + 320

AXRuntime       0x000000018c1e0fb8    _XCopyParameterizedAttributeValue + 372

AXRuntime       0x000000018c1b0d10    mshMIGPerform + 248

CoreFoundationn  0x0000000180350a40
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56

CoreFoundation     0x000000018034fe74   __CFRunLoopDoSource1 + 568

CoreFoundation      0x000000018034a10c       __CFRunLoopRun + 2296

CoreFoundation      0x0000000180349308      CFRunLoopRunSpecific + 572

GraphicsServices     0x000000018bf025ec     GSEventRunModal + 160

UIKitCore                 0x0000000184d3b4e0    -[UIApplication _run] + 992

UIKitCore     0x0000000184d3ffc0    UIApplicationMain + 112
```

### Flutter Doctor output

```console
[!] Flutter (Channel [user-branch], 3.19.6, on macOS 14.3 23D56 darwin-x64, locale zh-Hans-CN)
! Flutter version 3.19.6 on channel [user-branch] at /Users/chengjian/soft/flutter
Currently on an unknown channel. Run flutter channel to switch to an official channel.
If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
! Upstream repository unknown source is not a standard remote.
Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
• Framework revision https://github.com/flutter/flutter/commit/54e66469a933b60ddf175f858f82eaeb97e48c8d (2 个月前), 2024-04-17 13:08:03 -0700
• Engine revision c4cd48e186
• Dart version 3.3.4
• DevTools version 2.31.1
• If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades
```

**Comment by cj3479** [comment]
@darshankawar can you help to handle the issue?

**Comment by cj3479** [comment]
@jonahwilliams @gaaclarke can you help to handle the issue?

**Comment by huycozy** [comment]
Hi @cj3479 
Please don't randomly tag team members. 

>Flutter in a game app, and the game is based on the Unity engine.

Could you be more specific? Are you embedding a Flutter app into Unity game project?

Regarding the given crash trace above, I see there are only iOS native traces and missed Flutter trace so I'm unsure if it's caused from Flutter, Unity or native SDK. Please provide a complete crash stack trace if you have one. It will be useful if you can provide a minimal sample code that can produce the crash.

Also, you are using an old Flutter version, please try upgrading/switching to the latest stable version (3.22.2) and retry.

**Comment by cj3479** [comment]
> Hi @cj3479 Please don't randomly tag team members.
> 
> > Flutter in a game app, and the game is based on the Unity engine.
> 
> Could you be more specific? Are you embedding a Flutter app into Unity game project?
> 
> Regarding the given crash trace above, I see there are only iOS native traces and missed Flutter trace so I'm unsure if it's caused from Flutter, Unity or native SDK. Please provide a complete crash stack trace if you have one. It will be useful if you can provide a minimal sample code that can produce the crash.
> 
> Also, you are using an old Flutter version, please try upgrading/switching to the latest stable version (3.22.2) and retry.

Yes,I am embedding a Flutter app into Unity game project

I  try the latest stable version (3.22.2)  and it still appears

**Comment by huycozy** [comment]
Thanks for the update. Can you share how you embed Flutter into Unity? Please try to provide a minimal sample code so that we can reproduce and investigate this further. 

Also, please provide the entire crash stack trace if any. Thanks!

**Comment by cj3479** [comment]
> Thanks for the update. Can you share how you embed Flutter into Unity? Please try to provide a minimal sample code so that we can reproduce and investigate this further.
> 
> Also, please provide the entire crash stack trace if any. Thanks!

You can try this https://blog.codemagic.io/how-to-embed-an-android-unity-game-in-a-flutter-app/

**Comment by huycozy** [comment]
That article is for Android only. So I check [flutter_unity_widget](https://pub.dev/packages/flutter_unity_widget) instead but it seems the package's example is incomplete for iOS as I don't see `ios/UnityLibrary`. I also don't have Unity on my machine and it will take time to do this from the beginning, so it would be helpful if you could pre-build Unity module (Unity exporting) and please share a complete sample code (a zip file or a GitHub repository with its license) so that we can look into it easily?
