### ISSUE TITLE
[ios]Add sample project for "Add To (SwiftUI) App"

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#150944]
The sample project repo (https://github.com/flutter/samples/tree/main/add_to_app) only contains examples to add flutter to UIKit app. We should add SwiftUI example too. 

CC @loic-sharma

**Comment by hellohuanlin** [comment]
This is to add the sample project in the repo (rather than a doc update). I am reopening this.

**Comment by loic-sharma** [comment]
@hellohuanlin I'll let you create the sample project, but I'd be happy to test things like sample instructions to see if they make sense from a newbie's perspective :)
