### ISSUE TITLE
`runWithClient` passed http Client factory is ignored by Flutter's NetworkImage

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#150941]
### Steps to reproduce

as already reported here https://github.com/dart-lang/http/issues/828#issuecomment-2183303271

Even if you try to use the new native httpClients and use `runWithClient` as described here https://pub.dev/documentation/http/latest/http/runWithClient.html which has even an extra Flutter section users have no idea that the SDK's NetworkImage image provider will ignore the created ClientFactory. 

### Expected results

NetworkImage should use http.Client instead of HttpClient. Even better would be if it would get an additional parameter to provide the Client.

At least the docs of `runWithClient` and/or `NetworkImage` should mention this

### Actual results

an internal httpClient implementation is used:
![341865661-a16d6216-3548-4640-beb3-1ce3d259a7b3](https://github.com/flutter/flutter/assets/16635729/460deea6-9127-4846-a4c6-4d156fc1fc5b)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4529], locale de-DE)
    • Flutter version 3.22.0 on channel stable at C:\Users\escam\fvm\versions\3.22.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (7 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.90.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4529]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.126
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.68

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by darshankawar** [comment]
> the docs of `runWithClient`

This most probably is answered by https://github.com/dart-lang/http/pull/1248



> Even better would be if it would get an additional parameter to provide the Client.



> and/or `NetworkImage` should mention this

Keeping open for above two points from NetworkImage point of view.

**Comment by escamoteur** [comment]
@darshankawar unfortunately the linked issue is only on the source docs of `runWithClients` and doesn't address the issue with Flutter in any way yet

**Comment by ueman** [comment]
You could use https://pub.dev/packages/http_image_provider as described in the this example https://github.com/dart-lang/http/blob/321362a99eeffbf83e22e5cbaa5d8356c50f73ee/pkgs/flutter_http_example/lib/main.dart#L140

**Comment by escamoteur** [comment]
@ueman I know that this is a way to solve the problem, however this doesn't change the fact that according to the docs the whole app should use the Client that is returned by the clientFactory which isn't the case.

On a side node, I find it unfortunate, that your package has no linked/accessible github repository especially as it is used in an official example.

**Comment by brianquinlan** [comment]
I think that we can close the issue here - the `runWithClient` documentation has been fixed and this isn't a Flutter issue in any case.

**Comment by escamoteur** [comment]
@brianquinlan sorry but I have to disagree neither does the change by @natebosch in the API docs mention anything about the implication on NetworkImages in flutter despite the docs discussing the use with Flutter, nor is the issue the NetworkImage ignores the runWithClient addressed. Especially the latter is a Flutter issue. cc @kevmoo

**Comment by escamoteur** [comment]
I now wrote a blog post on the whole topic 

https://blog.burkharts.net/everything-you-always-wanted-to-know-about-httpclients
