### ISSUE TITLE
Material buttons need a refactoring

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15091]
Right now we have half a dozen button classes and a bunch of ways to configure them in Theme, ButtonTheme, and so on.

It seems like we should be able to get down to a single button class of any importance, configured by objects that describe the state of the button when enabled, disabled, pressed, etc, and have the button figure out the animations in between. RaisedButton, FlatButton, and OutlineButton would then just be wrappers around this that pass in some pre-determined defaults.

**Comment by TahaTesser** [comment]
Related to [#54776](https://github.com/flutter/flutter/issues/54776)

**Comment by HansMuller** [comment]
Closing this issue per #54776 et al.
