### ISSUE TITLE
`compute()` doesn't use an isolate in debug mode 

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#150938]
### Steps to reproduce

While doing some tests with the `compute()` function I put a breakpoint inside the function that is passed to compute expecting to see a second call stack when the breakpoint was hit as I have seen when using normal isolates.

Instead I stumbled upon an additional stack frame that I did not expect that pointed to this function:

```dart
Future<R> _testCompute<Q, R>(
    foundation.ComputeCallback<Q, R> callback, Q message,
    {String? debugLabel}) {
  if (foundation.kDebugMode) {
    final Type? bindingType = foundation.BindingBase.debugBindingType();
    if (bindingType.toString() == 'AutomatedTestWidgetsFlutterBinding') {}
  }
  final FutureOr<R> result = callback(message);
  if (result is Future<R>) {
    return result;
  }
  return foundation.SynchronousFuture<R>(result);
}

/// A compute implementation that does not spawn isolates in tests.
const foundation.ComputeImpl compute =
    (foundation.kDebugMode || foundation.kIsWeb)
        ? _testCompute
        : foundation.compute;
```

I understand that this might be necessary for tests. However if tests behave differently from the normal app in its timing this too can be problematic.
But it surely shouldn't do this when running a normal app in debug mode or at least if should be controllable by the developer.

### Expected results

Use an isolate in debug too

### Actual results

see above

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4529], locale de-DE)
    • Flutter version 3.22.0 on channel stable at C:\Users\escam\fvm\versions\3.22.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (7 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.90.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4529]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.126
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.68

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by huycozy** [comment]
Hi @escamoteur 
Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that illustrates this issue? Thanks!

**Comment by escamoteur** [comment]
@huycozy I don't think that an example will be of any real help here :-) anyone of the flutter team knowing the inner workings of `compute` will know what this is about.  The code piece above is from the Flutter framework

**Comment by huycozy** [comment]
Could you please share the link to source code above? I tried to find but couldn't see it in the current Flutter stable version 3.22.2.

**Comment by escamoteur** [comment]
Hi @huycozy I'm sorry, I just checked again and this part is only used inside the flutter_svg package, so this isn't a problem of Flutter as such.
However, @dnfield it would have been less confusing if the function defined here:

![image](https://github.com/flutter/flutter/assets/16635729/e672c9fc-0e75-474e-81d5-cd4788ea2713)
would have been named differently e.g. `computeInRelease` .
