### ISSUE TITLE
Proposal to implement pattern matching throughout the repo

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#150942]
It's fun to [turn switch statements into switch expressions](https://github.com/flutter/flutter/issues/136139), but there are other interesting ways that pattern-matching can make things more concise & readable.

#### example (widget_inspector.dart):

```dart
// before
final Object? object = toObject(id);
if (object is Element) {
  final RenderObject? renderObject = object.renderObject;
  if (renderObject is RenderFlex) {
    renderObject.mainAxisAlignment = mainAxisAlignment;
  }
}


// after
if (toObject(id) case Element(:final RenderFlex renderObject)) {
  renderObject.mainAxisAlignment = mainAxisAlignment;
}
```

**Comment by goderbauer** [comment]
It's not so clear to me if pattern matching is always a clear win in terms of readability. I've heard that concern from others as well and I am trying to get them to voice their opinion on this issue as well. Let's get some input from the team and community on this before we move forward with this and apply this to the entire repository. Maybe also gather some feedback from the Discord channels?

**Comment by nate-thegrate** [comment]
> Let's get some input from the team and community on this before we move forward with this and apply this to the entire repository. Maybe also gather some feedback from the Discord channels?

Sounds good! I posted a design doc issue for this today (and shared it [on Discord](https://discord.com/channels/608014603317936148/608018585025118217/1266069187940450348) as well). I'm very happy about the feedback it's received so far!

- https://github.com/flutter/flutter/issues/152313
