### ISSUE TITLE
Texture Widget crashed on receiving new frame

### ISSUE THREAD

**Issue by Athvaith2828** [flutter/flutter#150977]
### Steps to reproduce

1. Execute the example of this plugin [https://pub.dev/packages/flutter_gstreamer_player](url)  for linux platform by altering gstreamer command to open front camera (gstreamer works fine while executing in terminla).
2. The app crashes after starting the camera (while receiving the frame)., saying Lost connection to device.
3. Platform Ubuntu 22.02

### Expected results

MethodChannel that starts the gstreamer pipeline and marks the frame available in texture registry. The texture widget which takes the textureId to render the frame continuously in screen.

### Actual results

I have checked the whole native code that sets the texture registry on frame available. The texture widget crashes the application saying **Lost connection to device**.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @Athvaith2828 
`flutter_gstreamer_player` is a 3rd party plugin so you should open an issue to its [repository](https://github.com/hpdragon1618/flutter_gstreamer_player) for better support. Closing this as it's not an issue with Flutter or 1st party packages.
