### ISSUE TITLE
[ios]Make "add to SwiftUI app" doc up to date with iOS 18

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#150945]
The "Add to (SwiftUI) app" doc is outdated. For example, iOS 17 introduced macros which makes things like `@EnvironmentObject` outdated (we didn't update it last year). There may be other updates needed for iOS 18. 

Page: https://docs.flutter.dev/add-to-app/ios/add-flutter-screen/
Page source: https://github.com/flutter/website/tree/main/src/add-to-app/ios/add-flutter-screen.md

CC @loic-sharma

**Comment by jmagman** [comment]
@hellohuanlin can you refile this with the website issue tracker https://github.com/flutter/website/issues/new/choose?
I would transfer it but we should use the preferred template.

**Comment by hellohuanlin** [comment]
Closing for https://github.com/flutter/website/issues/10904
