### ISSUE TITLE
Failed assertion: line 2165 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by nissaba** [flutter/flutter#150930]
### Steps to reproduce

I can not create a base sample, I do not have time for this. THe compile 'Android Studio requested that I open a bug report. so I open this bug report .

the is the page code that as created the problem

```
class AntPlusScannerView extends ConsumerWidget {
  const AntPlusScannerView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return PlatformScaffold(
      appBar: PlatformAppBar(
        title: Text(AppLocalizations.of(context).powerMeterSelectionTitle),
      ),
      body: Column(
        children: [
          Text(AppLocalizations.of(context).powerMeterSelectionInstruction),
          const SizedBox(
            height: 40,
            child: Placeholder(),
          ),
          ListView.builder(
              itemCount: ref.watch(antSensorScannerProvider).length,
              prototypeItem: ListTile(
                title: Text('${ref.read(antSensorScannerProvider).first}'),
              ),
              itemBuilder: (ctx, idx) =>
                  itemBuilder('${ref.read(antSensorScannerProvider)[idx]}')),
        ],
      ),
    );
  }

  Widget? itemBuilder(String n) {
    return ListTile(
      title: Text(n),
    );
  }
}
```

### Expected results

Expecte UI to show, but its a blank screen

### Actual results

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performResize():
Vertical viewport was given unbounded height.

Viewports expand in the scrolling direction to fill their container. In this case, a vertical viewport was given an unlimited amount of vertical space in which to expand. This situation typically happens when a scrollable widget is nested inside another scrollable widget.

If this widget is always nested in a scrollable widget there is no need to use a viewport because there will always be enough vertical space for the children. In this case, consider using a Column or Wrap instead. Otherwise, consider using a CustomScrollView to concatenate arbitrary slivers into a single scrollable.

The relevant error-causing widget was: 
  ListView ListView:file:///Users/pascalebeaulac/Argon%20Projects/notio-flutter-app/lib/views/ant_plus_views/ant_plus_scanner_view.dart:24:20
When the exception was thrown, this was the stack: 
#0      debugCheckHasBoundedAxis.<anonymous closure> (package:flutter/src/rendering/debug.dart:337:13)
#1      debugCheckHasBoundedAxis (package:flutter/src/rendering/debug.dart:396:4)
#2      RenderViewport.computeDryLayout (package:flutter/src/rendering/viewport.dart:1384:12)
#3      RenderBox.performResize (package:flutter/src/rendering/box.dart:2667:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2556:9)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#22     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#23     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:815:43)
#24     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:885:32)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#26     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#27     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
#28     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#29     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#34     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#54     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3710:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#58     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:974:13)
#59     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1288:9)
#60     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416:7)
#61     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
#62     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
#63     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:23)
#64     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138:13)
#65     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#66     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#67     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#68     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#69     _invoke (dart:ui/hooks.dart:312:13)
#70     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#71     _drawFrame (dart:ui/hooks.dart:283:31)
The following RenderObject was being processed when the exception was fired: RenderViewport#9ad46 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...  size: MISSING
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#3d1f2(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#50c3a, ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#9ad46 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  size: MISSING
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#3d1f2(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#50c3a, ScrollDirection.idle)
  anchor: 0.0
...  center child: RenderSliverPadding#ce2b7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 0.0)
...    constraints: MISSING
...    geometry: null
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: _RenderSliverPrototypeExtentList#f7e29 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: paintOffset=Offset(0.0, 0.0)
...      constraints: MISSING
...      geometry: null
...      no children current live
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderViewport#9ad46 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  ListView ListView:file:///Users/pascalebeaulac/Argon%20Projects/notio-flutter-app/lib/views/ant_plus_views/ant_plus_scanner_view.dart:24:20
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2165:12)
#3      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1401:39)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#22     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#23     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:815:43)
#24     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:885:32)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#26     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#27     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
#28     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#29     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#34     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#54     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3710:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#58     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:974:13)
#59     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1288:9)
#60     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416:7)
#61     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
#62     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
#63     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:23)
#64     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138:13)
#65     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#66     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#67     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#68     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#69     _invoke (dart:ui/hooks.dart:312:13)
#70     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#71     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderViewport#9ad46 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...  size: MISSING
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#3d1f2(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#50c3a, ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#9ad46 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  size: MISSING
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#3d1f2(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#50c3a, ScrollDirection.idle)
  anchor: 0.0
...  center child: RenderSliverPadding#ce2b7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 0.0)
...    constraints: MISSING
...    geometry: null
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: _RenderSliverPrototypeExtentList#f7e29 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: paintOffset=Offset(0.0, 0.0)
...      constraints: MISSING
...      geometry: null
...      no children current live
====================================================================================================

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Basic press run in android studio

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 % flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on macOS 15.0 24A5279h darwin-arm64, locale en-CA)
    • Flutter version 3.22.2 on channel stable at /Users/pascalebeaulac/flutter_dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/pascalebeaulac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • Pixel 6 (mobile)                • 21121FDF600B9F            • android-arm64  • Android 14 (API 34)
    • iPhone (mobile)                 • 00008120-000C38580270201E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A5279h darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A5279h darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for Vincent. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPad de Pascale (4). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
You have put a ListView in a `Column` without setting a bounded height for it so it can't be painted. You should either wrap the listview with an `Expanded` or  a `SizedBox` or a `ConstrainedBox` to set a bounded height for it. 

Closing from here as this is an issue with your code. 

Thank you
