### ISSUE TITLE
Easier padding for scrolling widgets

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#150924]
### Use case

Sometimes when you have a `ListView` you want it to be padded inside your screen but only at the sides and over the first item and under the last one.

For this, today we need to have something like:

```dart
CustomScrollView(
  slivers: [
    SliverPadding(
      padding: const EdgeInsets.all(12),
      sliver: SliverList(
        delegate: SliverChildBuilderDelegate(
          childCount: items.length,
          (context, index) {
            //Widget
          },
        ),
      ),
    ),
  ],
)
```

Or even do some weird layout calculations increasing the number of `childCount` by two and testing if it is the first or last one to display something like a `SizedBox`.

### Proposal

I'd like to propose an additional parameter to all intrinsic scrolling widgets like `SingleChildScrollView` or similar, or even a wrapping _box widget_ that abstracts the `SliverPadding`.

Because if we add `Padding` around a list, the bottom, for example, will always be far from the bottom of the page whereas we would only want this after the last item.

**Comment by Piinks** [comment]
Hi @FMorschel this is already supported by ListView.padding and GridView.padding. For SingleChildScrollView, there are no slivers, and there is just one child, so the same effect can be realized like this (pseudo):

```dart
SingleChildScrollView(
  child: Padding(
    padding: ...
    child: ...
  )
)
```

**Comment by FMorschel** [comment]
Hi! Thank you for the response. I completely missed `ListView.padding` and `GridView.padding`. Thanks for the tip on how to work with `SingleChildScrollView`. I guess that does make more sense than wrapping _it_ with `Padding`.

Since this is already easy enough to do, I'll go ahead and close this. Again, sorry for missing those properties on `ListView` and `GridView`.
