### ISSUE TITLE
Devicelab memory usage probes aren't working on iOS

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#150936]
## broken probes
- `average_memory_usage`
- `90th_percentile_memory_usage`
- `99th_percentile_memory_usage`

## reproduction steps
1) Checkout flutter/flutter@0198afa1a4407e6b16ac0e57f6f23adc4e05b706
1) Modify `dev/benchmarks/macrobenchmarks/ios/Runner.xcodeproj` to show the graphics overlay (`showGraphicsOverview`)
1) Run the `backdrop_filter_perf_ios__timeline_summary` benchmark
1) Look at the overlay and notice that the memory usage is around 400MB
1) Wait for the results to be printed to the console, notice that it reports something around 200MB
1) Checkout flutter/flutter@def5a38e02fbec5a1737a83775ffefcc7f98eea9
1) Run the test again
1) Notice that the overlay now reports usage is around 200MB but the report printed to the console still lists the same result from above.

## screenshots
<img src="https://github.com/flutter/flutter/assets/30870216/539ce2e0-3342-4bfa-916c-846aa96c9353" width=320>
<img src="https://github.com/flutter/flutter/assets/30870216/cabcd4e2-b0d2-41ee-8c54-a04afc3635d1" width=320>

**Comment by jonahwilliams** [comment]
they're not implemented for iOS, but we should!

**Comment by gaaclarke** [comment]
> they're not implemented for iOS, but we should!

The memory probes are implemented, they are the ones listed in the description, but they give bogus results.  I think you are talking about tracking gpu memory.
