### ISSUE TITLE
ScrollDirection and BlockDirection confusion

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#151]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Aug 27, 2015 at 17:12 GMT_
_Originally opened as https://github.com/flutter/engine/issues/888_

----

Right now scrollables use ScrollDirection and they're backed by render objects that use BlockDirection. However, that means ScrollDirection.both has no good mapping.

We should clean this up. I think we should probably still have two enums, one with "horizontal" and "vertical" and one with "horizontal", "vertical", and "both", but we should not split it across Block vs Scroll, instead of should split it according to who supports "both" and who doesn't.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Tuesday Sep 15, 2015 at 17:58 GMT_

----

Briefly looked at this with @collinjackson. Scrollable right now asserts that you don't use "both". RenderViewport supports "both", nobody else seems to. We probably want a Widget to wrap RenderViewport with fling gesture support that does both, but other than that we should probably not have any use of the enum with "both".

**Comment by abarth** [comment]
Happy to fix this issue, but I'm not clear what we want.  Here's a guess:

 - Scrollable should use an enum with just two values (horizontal and vertical)
 - Scrollable and RenderBlock should use the same enum
 - Viewport should use a different enum with three values

Questions:

 - ScrollDirection is a nice name that makes sense for Scrollable.  Should we use that name for RenderBlock too even though RenderBlocks aren't necessarily related to scrolling?
 - What should we call the enum with three values (horizontal, vertical, both) that Viewport uses?

**Comment by Hixie** [comment]
`Axis`and `MultiAxis`?

**Comment by Hixie** [comment]
Should we still merge ScrollDirection and BlockDirection into a single enum?

**Comment by abarth** [comment]
Sorry, didn't mean to close this issue.  Yes, we still need to delete BlockDirection.

**Comment by Hixie** [comment]
Looking at https://github.com/abarth/flutter/commit/4246237b693f50268b93708379740b2facd78a2f (from PR #1074), I really think we should just use "Axis" as the enum name.

**Comment by abarth** [comment]
Makes sense.

**Comment by Hixie** [comment]
Oh GitHub, you mean well...
