### ISSUE TITLE
Issue from website page JSON and serialization

### ISSUE THREAD

**Issue by zskpaco** [flutter/flutter#15104]
code
![image](https://user-images.githubusercontent.com/34360271/36932966-5dff3f8a-1f0c-11e8-974b-7f2a13dd2814.png)

after generation
![image](https://user-images.githubusercontent.com/34360271/36932981-85b1d542-1f0c-11e8-8e5a-3a7146e568ec.png)

...How to solve?

**Comment by roughike** [comment]
All of your model classes are missing the appropriate mixins.

[The article mentions](https://flutter.io/json/#creating-model-classes-the-json_serializable-way) this:

> Every json_serializable class must have the serializer mixin. 
> It makes the generated toJson() method to be usable for the class. 
> The mixin's name follows the source class, in this case, User.

So, you can resolve those errors by adding `with _$<CLASSNAME>SerializerMixin` to your classes.

Something like this:

```dart
@JsonSerializable()
class Person extends Object with _$PersonSerializerMixin {
  ...
}

@JsonSerializable(includeIfNull: false)
class Order extends Object with _$OrderSerializerMixin {
  ...
}
```

**Comment by Richardpaco-zhang** [comment]
It cannot firgue out the types of List<Order>.And even after adding Mixin behind Class can not revolve this problem.

**Comment by Richardpaco-zhang** [comment]
It cannot firgue out the types of List<Order>.And even after adding Mixin behind Class can not revolve this problem.

**Comment by Hixie** [comment]
I recommend filing this with the json_serializable project; Flutter is a separate project and while we certainly appreciate json_serializable we aren't responsible for it.

See: https://pub.dartlang.org/packages/json_serializable
