### ISSUE TITLE
not show Flutter: Run Flutter Doctor in VS Code

### ISSUE THREAD

**Issue by shinriyo** [flutter/flutter#15107]
## Steps to Reproduce

I just did about the document, https://flutter.io/get-started/editor/

```
Invoke View>Command Palette…
Type ‘doctor’, and select the ‘Flutter: Run Flutter Doctor’ action
Review the output in the ‘OUTPUT’ pane for any issues
```

I invoked `View>Command Palette…`.
I typed `doctor` but nothing shown.

or you mean. package?

## Logs

<img width="563" alt="screen shot 2018-03-03 at 23 25 32" src="https://user-images.githubusercontent.com/396927/36935362-6a04ba84-1f3a-11e8-9def-e22a595494c5.png">
<img width="281" alt="screen shot 2018-03-03 at 23 26 53" src="https://user-images.githubusercontent.com/396927/36935363-6a380920-1f3a-11e8-8c00-11b31569250e.png">

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```
flutter doctor -v         2.2m  Sat Mar  3 23:23:51 2018
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-JP)
    • Flutter version 0.1.5 at /Users/shinriyo/development/flutter_apps/flutter
    • Framework revision 3ea4d06340 (9 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/shinriyo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.2

[✓] Connected devices (1 available)
    • iPhone X • 050B1A66-7F4E-439B-AA7B-082B195DE48F • ios • iOS 11.2 (simulator)

• No issues found!
```

**Comment by humayuntanwar** [comment]
try typing .. flutter
![flutter](https://user-images.githubusercontent.com/26435693/36935460-cc0d06bc-1f19-11e8-9449-4a2f79da4a7e.png)

**Comment by sabdar18** [comment]
install this plugin and vs code extensions 

https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

then reload the vs code editor 

then you will be to find out the flutter commands

**Comment by DanTup** [comment]
I think this is a dupe of #15066.

The docs suggest that `Flutter Doctor` in the command palette after installing, but it's actually only visible with a Flutter project open. I've proposed some suggestions on #15066 to improve this.

For now, just run `flutter doctor` from a terminal (even the one built in to Code), or run the `Flutter: New Project` command (which does appear in the command palette even without a Flutter project open) to start a project.

**Comment by shinriyo** [comment]
@humayuntanwar 
@sabdar18 
@DanTup 

Thank you for replying.
I had already dart code plugin. because of I read the document.
However, before I knew it, it was appeared.
<img width="525" alt="screen shot 2018-03-04 at 1 12 15" src="https://user-images.githubusercontent.com/396927/36939877-f03fca94-1f7b-11e8-891f-eff13316ed9a.png">

**Comment by DanTup** [comment]
@shinriyo In v2.9 the command only appears when you have a Flutter project open. In v2.10 (there's a beta available on GitHub) the command will always appear which should remove the confusion.

Thanks for the report!

**Comment by mteruya** [comment]
I went through the same problem, after restarting the computer everything worked.
