### ISSUE TITLE
What is the reason for not releasing a new version for almost a month?

### ISSUE THREAD

**Issue by bing127** [flutter/flutter#151079]
### Use case

What is the reason for not releasing a new version for almost a month?

### Proposal

What is the reason for not releasing a new version for almost a month?

**Comment by danagbemava-nc** [comment]
You can find out about our latest releases, release process and other information from the links below. 

The flutter discord would be a better place to ask this question. 

Closing from here. 

Thank you 

https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md#flutter-322-changes
https://github.com/flutter/flutter/blob/master/docs/releases/Release-process.md
https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-build-release-channels.md
https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-Cherrypick-Process.md
