### ISSUE TITLE
☂️: 1P rendering plugins should use the suggested migration path

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#151018]
An umbrella bug, because there are so many other threads and requirements for fully landing this feature. 

**Should have**: If these are not ready, Impeller _can_ ship, but our 1P plugins will not reflect best practices:
- [x] The new `SurfaceProducer.setCallback` API is documented as [part of the migration guide](https://docs.flutter.dev/release/breaking-changes/android-surface-plugins)
   Tracking: https://github.com/flutter/flutter/issues/148417
- [x] Once the _new_ stable release is out (~mid to late August), publish new versions of both plugins
    Tracking: https://github.com/flutter/flutter/issues/139702

**Best effort**: We should try to do as many of these as possible, but they are not release blockers:

- [ ] Once the _new_ stable release is out (~mid to late August), publish new versions of `camera_android`
- [ ] Reach out the top X external plugins (i.e. on Github) and notify them about the new API, suggest PRs if possible[^1]

[^1]: I.e. both time and licensing constraints

---

/cc @reidbaker @stuartmorgan @jonahwilliams @chinmaygarde @johnmccutchan.

**Comment by chinmaygarde** [comment]
EOW Update: The unknowns with texture trampolining were figured out and the patch that implements this is ready for review in https://github.com/flutter/engine/pull/53966.

Once that patch lands, Impeller should support existing and migrated plugins out of the box. 

Migrating plugins is still the right thing to do from a future proofing perspective but it can continue orthogonal to the Impeller on-by-default effort.

**Comment by chinmaygarde** [comment]
Now that https://github.com/flutter/engine/pull/53966 has landed, Impeller will support all plugins out of the box with a recommendation (but not requirement) that they use the new API.

Should we reword this issue now? OTOH, if the migration tasks are adequately tracked in https://github.com/flutter/flutter/issues/139702, then we can close this.

I have removed this issue from the Impeller on Android milestone.

**Comment by matanlurey** [comment]
It is a bit tricky, because your new feature won't go out until the _next_ stable release.

**Comment by chinmaygarde** [comment]
Impeller on-by-default won't be on stable till the next stable release either. Because we have already missing the branch cut for the previous release.

> If these are not ready, Impeller cannot ship.

This statement no longer holds and we are tracking the migration separately. So I guess I was wondering what the remaining action item here is.

**Comment by matanlurey** [comment]
I've modified both the issue description and priority to reflect it, is it clear now?

**Comment by matanlurey** [comment]
As of today, all the rendering plugins are migrated to the new API.

Since we don't need to make changes to legacy plugins anymore, I'm marking this issue resolved!
