### ISSUE TITLE
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds..

### ISSUE THREAD

**Issue by hitswa** [flutter/flutter#15101]
**Note:** I know this issue already exists in raised issue but I found it unresolved. Please don't close it as I included troubleshooting suggested by other threads too along with all outputs and snapshots. so its not a duplicate issue.

I am using Windows 8.1 64bit
having 7z and git installed on my system
environment set properly

![4](https://user-images.githubusercontent.com/4740668/36932355-bfd62a08-1eed-11e8-9faa-2e7954c4db54.png)

![5](https://user-images.githubusercontent.com/4740668/36932370-f0b3a768-1eed-11e8-9fb1-169a55692704.png)

As per [getting started instructions to install flutter on windows](https://flutter.io/setup-windows/), I cloned flutter using the following command in _c:\android_ directory and get a _c:\android\flutter_ directory

`git clone -b beta https://github.com/flutter/flutter.git`

set environment `c:\android\flutter\bin`

then I make a folder on the desktop called test and open PowerShell and CD to that folder and run following command

`flutter doctor`

It says `Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...` repeatedly as following

![2](https://user-images.githubusercontent.com/4740668/36932408-71111e7c-1eee-11e8-9c4a-d4437e465db3.png)
```
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
Unzipping Dart SDK...
Updating flutter tool...
The system cannot find the path specified.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 0 seconds, press CTRL+C to quit ...
The system cannot find the path specified.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
```

I searched on google leading different issue pages and forums to resolve the issue. tried deleting cache directory and repeating `flutter doctor` command also didn't find any _$cachePath_ folder anywhere in my system.

tries a solution suggested on the issue [#12666](https://github.com/flutter/flutter/issues/12666) to `cd into flutter\packages\flutter_tools` and in there execute `..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --verbosity=error --no-packages-dir`

but I guess it didn't work as there is nothing in my _C:\android\flutter\bin\cache\dart-sdk_ directory and gives following errors

![6](https://user-images.githubusercontent.com/4740668/36932379-19c2af0a-1eee-11e8-8314-7f1e34cf9bac.png)

```
..\..\bin\cache\dart-sdk\bin\pub.bat : The term '..\..\bin\cache\dart-sdk\bin\pub.bat' is not recognized as the name
of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:1
+ ..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --verbosity=error --no-p ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\bin\cache\dart-sdk\bin\pub.bat:String) [], CommandNotFoundExcepti
   on
    + FullyQualifiedErrorId : CommandNotFoundException
```
![3](https://user-images.githubusercontent.com/4740668/36932382-2afa18a8-1eee-11e8-995c-dc62ccebd22a.png)

I tried to manually download dart-sdk and extract it inside _C:\android\flutter\bin\cache\dart-sdk_ directory but it starts giving dependency error as following

```
Updating flutter tool...
Incompatible version constraints on async:
- flutter_tools depends on version 2.0.4
- pub itself depends on version >=1.8.0 <2.0.0
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 0 seconds, press CTRL+C to quit ...
^CTerminate batch job (Y/N)? y
```

I tried uninstalling and re-installing everything again but nothing works.

I noticed on executing `flutter doctor` command I do see a **dart-sdk-windows-x64.zip** file get downloaded inside _flutter\bin\cache_ directory but it gets deletes itself soon after downloading and didn't get extracted.

![1](https://user-images.githubusercontent.com/4740668/36932388-3daca8bc-1eee-11e8-8895-f72158d96d88.png)

**Results of `flutter run`, `flutter analyze` and `flutter doctor -v` are same**

```
Updating flutter tool...
The system cannot find the path specified.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 3 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? y
```

**in case dart-sdk added manually following are the outputs of all the above commands i.e. `flutter run`, `flutter analyze` and `flutter doctor -v`**

```
Updating flutter tool...
Incompatible version constraints on async:
- flutter_tools depends on version 2.0.4
- pub itself depends on version >=1.8.0 <2.0.0
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Waiting for 0 seconds, press CTRL+C to quit ...
^CTerminate batch job (Y/N)?
```

Do anyone find any prominent solution to this issue? If yes please share it.

**Comment by hitswa** [comment]
Oooh man 

I found a [dart-sdk-windows-x64.zip](https://storage.googleapis.com/flutter_infra/flutter/97b22348c8d5cba471418dc94f9e384e384e796f/dart-sdk-windows-x64.zip) download link in #15061 

and extracted it in the dart-sdk directory and it seems that it worked but no. It's showing some issues as shown in the following snapshot.

![untitled](https://user-images.githubusercontent.com/4740668/36932610-44b3ee24-1ef1-11e8-8c42-497df5851fce.png)

I guess its unable to find Android SDK toolchain, studio and IntelliJ or CS code. however, everything is already installed in my system and environment is also already exists.

Well trying to resolve the issue and keep posting updates.

**Comment by zoechi** [comment]
dup of #15014 ?

**Comment by shashank-shinde** [comment]
Hey @hitswa, I'm facing same issue. How you solved it?

**Comment by hitswa** [comment]
Yah, I have solved this, Sry I forget to update the thread and yes I also forget what exactly I did to make it work... I believe I installed flutter and dart plugins in Android Studio and that fixed the problem. My Android studio is working fine for flutter applications...

Don't worry I have a habit to make notes of everything I do... So I will update this thread as soon as I find my notes. Because this is an unresolved issue in most of the threads even today. So it's very important to share how I fixed that. I will do that shortly

**Comment by zoechi** [comment]
Sorry, space in username is not covered by the linked comment. 
#18938 is about space in user name.

**Comment by zoechi** [comment]
This appears to be solved.

**Comment by tarisham** [comment]
hi
go to the bios and change vm (Virtual machine) from disable to enable. you want to run emulator so its Necessary.
