### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'. > Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by joejills** [flutter/flutter#151071]
I have spent 2 days trying to solve a problem I have with the Quizzler app. It doesn't matter what I try I get the following message when I run it. 

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1629

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

**Comment by danagbemava-nc** [comment]
Hi @joejills, please provide the output of `flutter doctor -v` along with the full output of `flutter run -v`. 

The output of `flutter run -v` is likely to be huge so kindly put it into a .txt file an attach it here. 

Thank you
