### ISSUE TITLE
gradle initializing taking forever

### ISSUE THREAD

**Issue by humayuntanwar** [flutter/flutter#15106]
just started the working with flutter
i just made my first app , and i have been trying to run it on my android 7.0 device

here is doctor:
![doc](https://user-images.githubusercontent.com/26435693/36934929-9ec9329a-1f12-11e8-8973-420e69a46f93.png)

![error](https://user-images.githubusercontent.com/26435693/36934936-b41623e2-1f12-11e8-89bc-068a312970f3.png)

first i thought its because its downloading gradle.
so i downloaded gradle 4.0.1 
and changed gradle path for flutter using : 
flutter config --gradle-dir /..
which worked
but still its been hour its stuck on initializing gradle.

**Comment by Cyan101** [comment]
same, anyone got a fix?

**Comment by dennisohere** [comment]
I have got the same problem too. searched and re-searched, but can't find a solution. any help will be greatly appreciated and welcomed.

**Comment by MarcBruins** [comment]
Got the same on MacOS with VScode and Android studio. VSCode doesn't give any other info then "Initiliazing gradle". Android studio prints the following after a few minutes:

Finished with error: Exit code 1 from: /Users/x/Projects/hello_world/android/gradlew -v:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/x/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Android studio 3.0.1
Flutter plugin 22.2.1
Flutter v0.1.5
Dart 2.0.0-edge.0d5

**Comment by andrisetyoo** [comment]
MacOS, Android Studio 3.0.1
- Try to install gradle manually (https://services.gradle.org/distributions/gradle-4.6-bin.zip), and unzip it
- Open <path_to_flutter_app>/android/gradlew
- Find: CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar 
and replace with: CLASSPATH=<path_to_downloaded_gardle>/gradle-4.6/lib/gradle-launcher-4.6.jar
- Find: exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
and replace with: exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.launcher.GradleMain "$@"
- flutter run

**Comment by humayuntanwar** [comment]
@andrisetyoo  
i cant find the
 exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
 in graddlew
any help?

**Comment by andrisetyoo** [comment]
For Windows:
**Find:** set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
**Replace:** set CLASSPATH=<path_to_downloaded_gardle>\gradle-4.6\lib\gradle-launcher-4.6.jar

**Find:** "%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS%
**Replace:** "%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.launcher.GradleMain %CMD_LINE_ARGS%

How about this?

**Comment by humayuntanwar** [comment]
@andrisetyoo thanks alot brother! worked like a charm!

**Comment by andrisetyoo** [comment]
@humayuntanwar you're welcome :)

**Comment by baj9032** [comment]
@andrisetyoo : After followed your windows suggestion I got an exception.see issue https://github.com/flutter/flutter/issues/15897.

**Comment by riftninja** [comment]
Apparently it seems gradle is being downloaded
For windows users:

- go to %USER_HOME%\.gradle\wrapper\dists delete the version based on the gradle-wrapper.properties in your project (for me it was gradle-4.1-all folder).
- Invalidate Caches / Restart Android studio, then run the project

It would seem to be stuck at 'Initializing gradle' but from the here '%USER_HOME%\.gradle\wrapper\dists' you'd notice it recreated the deleted folder and starts to download the gradle distribution.

Be patient and let it finish.

**Comment by doanhai** [comment]
@andrisetyoo thanks you bro !

**Comment by arnold-parge** [comment]
**I had same problem** flutter could not access the file from `.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1-all.zip`.
I tried following:
`sudo chmod 777 gradle-4.1-all.zip`
and **it worked**..

**Comment by TheDarkKnight2018** [comment]
can anyone help me I'm running android studio 3.1 in windows 10 and I'm using Flutter, the thing is I'm having a problem with the gradle , the program couldn't download it i have tried to reinstall the program to many times and tried to download the gradle so many  times when  i press run in android studio it always stuck in initializing gradle and i always check the file where it should be downloaded and nothing happened, please help me solving this issue cauze it's been almost tow weeks and I'm really frustrated , to help you understand more i will post those two pictures 





![untitled](https://user-images.githubusercontent.com/41855243/43364675-95f1b2b2-9327-11e8-84e8-c6888713194b.jpg)
![untitled2](https://user-images.githubusercontent.com/41855243/43364676-96664f96-9327-11e8-97a0-8c24c3c242fe.jpg)

**Comment by Super-Boom** [comment]
I had same problem in mac os. 
1, move out the gradle-wrapper.jar and gradle-wrapper.properties  to trash
2,flutter run (it will output error)
3, remove gradle-wrapper.jar and gradle-wrapper.properties to gradle/wrapper 
4,flutter run 
it sound stupid but it work (I hope this can help you), 额，sorry ,my english is not good, hope you can understand :)

**Comment by NouraAbdelnoor** [comment]
how can i find CLASSPATH ?!
WHERE PLEASE SUPPORT YOUR ANSWER WITH SCREEN SHOT

**Comment by NouraAbdelnoor** [comment]
@andrisetyoo  please where can i find CLASSPATH ! provide me a screen shot

**Comment by kahlflekzy** [comment]
After applying the replacements above, when i run flutter run -v it runs then hangs with the output below
C:\Users\User\Downloads\Compressed\download\flutter_app>flutter run -v
[ +156 ms] [C:\Users\User\Desktop\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +222 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[   +1 ms] [C:\Users\User\Desktop\flutter\] git rev-parse --abbrev-ref HEAD
[ +118 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +1 ms] [C:\Users\User\Desktop\flutter\] git ls-remote --get-url origin
[ +101 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\Users\User\Desktop\flutter\] git log -n 1 --pretty=format:%H
[ +100 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[   +1 ms] [C:\Users\User\Desktop\flutter\] git log -n 1 --pretty=format:%ar
[ +115 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[   +2 ms] [C:\Users\User\Desktop\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +106 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.1-0-gc7ea3ca
[ +673 ms] C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +37 ms] Exit code 0 from: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
[ +612 ms] C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell getprop
[ +128 ms] ro.hardware = ranchu
[  +68 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[+1870 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +22 ms] Initializing gradle...
[   +3 ms] Using gradle from C:\Users\User\Downloads\Compressed\download\flutter_app\android\gradlew.bat.
[ +159 ms] C:\Users\User\Downloads\Compressed\download\flutter_app\android\gradlew.bat -v
[+1516 ms]
           ------------------------------------------------------------
           Gradle 4.10-20180720094237+0000
           ------------------------------------------------------------

           Build time:   2018-07-20 09:42:37 UTC
           Revision:     df35f7df349a7e1ab912a3af7f657f8f92eb7fca

           Kotlin DSL:   0.18.4
           Kotlin:       1.2.41
           Groovy:       2.4.12
           Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
           JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
           OS:           Windows 10 10.0 amd64
[   +5 ms] Resolving dependencies...
[  +13 ms] [android\] C:\Users\User\Downloads\Compressed\download\flutter_app\android\gradlew.bat app:properties

it just hangs here

**Comment by GitHub27** [comment]
> how can i find CLASSPATH ?!
> WHERE PLEASE SUPPORT YOUR ANSWER WITH SCREEN SHOT

You can find it  in <project_path>/android/gradlew.bat

**Comment by saidihasan** [comment]
i think this problem occur because gradle downloaded slowly, even you have normal internet connection.
thant my opinion

**Comment by zoechi** [comment]
@lukeron see also https://github.com/flutter/flutter/issues/24884 (currently it's `4.10.2`)

**Comment by KipchirchirIan** [comment]
Had the same problem on Android Studio v3.2.1[Ubuntu 16.04]. What worked for me(after a lucky guess) was, I opened the android module on Android studio i.e. Right click on the android module -> open Android module in Android studio. Gradle syncing started, after it completed I went back to the Flutter app and run it  again. That's all!

**Comment by ssor** [comment]
I solve this problem!!!! 

under flutter  project, the  file of  **android/gradle/wrapper/gradle-wrapper.properties**  indicates the version of gradle.

for exmaple, mine is **distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip**, so in my home **~/.gradle/wrapper/dists**, there should be a dir called **radle-4.10.2-all**, and under this dir, xxxxx/gradle-4.10.2-all.zip.part  and xxxxx/gradle-4.10.2-all.zip.lck,  NOTICE, here should have **gradle-4.10.2-all.zip**, if there is no such file, download it

**Comment by naychrist** [comment]
I already had `gradle-4.10.2` in the correct location on OSX as per last couple comments but still have this issue. Was hoping to try specify a local install of gradle instead but all documentation I can find of this online points at Android Studio preferences that seem to no longer be accessible. iOS simulator is working fine but really need to get android up as well.

**Comment by ibrahemid** [comment]
> step 1 : 


make sure you have correctly installed gradle by locating the zip file inside  `.grade/dist`

**or**


 more simpler way is by running `choco install gradle ` for windows or `brew install gradle` for mac
(choco is package manager for Windows `https://chocolatey.org/` ) 


>  step 2


in  `yourFlutterAppDir/android/gradle/wrapper/gradle-wrapper.properties` file 
change the `distributionUrl `to `https\://services.gradle.org/distributions/gradle-YOUR_LOCAL_VERSION-all.zip`
mine is 
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.0-all.zip
`

if you got 
`Cannot lock task history cache (APP_NAME\android\.gradle\5.0\taskHistory) as it has already been locked by this process.`

you may need to clear the cache by removing the `\.gradle\caches folder`

-For Windows it's under `C:\Users\YOUR_USER_NAME\.gradle\caches`

-For Mac OSX it's ~/.gradle/caches
 execute the following command:
`find ~/.gradle -type f -name "*.lock" | while read f; do rm $f; done
`
after clearing the cache , run the app again and be patient 

end result 💯 
https://imgur.com/a/n59nXur 
:trollface:

**Comment by Kakashi74** [comment]
how i can solve it for ubuntu !

**Comment by Kakashi74** [comment]
> MacOS, Android Studio 3.0.1
> 
> * Try to install gradle manually (https://services.gradle.org/distributions/gradle-4.6-bin.zip), and unzip it
> * Open `<path_to_flutter_app>/android/gradlew`
> * Find: `CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar`
>   and replace with: `CLASSPATH=<path_to_downloaded_gardle>/gradle-4.6/lib/gradle-launcher-4.6.jar`
> * Find: `exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"`
>   and replace with: `exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.launcher.GradleMain "$@"`
> * `flutter run`

error !
==> Finished with error: ProcessException: Process "/home/ahmed/IdeaProjects/demos/android/gradlew" exited abnormally:
Error: Could not find or load main class org.gradle.launcher.GradleMain
  Command: /home/ahmed/IdeaProjects/demos/android/gradlew -v

**Comment by kangwang1988** [comment]
@Kakashi74 

Generally, in a flutter generated flutter_project/android/gradlew 
It should be like below:
```
#!/usr/bin/env bash

##############################################################################
##
##  Gradle start up script for UN*X
##
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn ( ) {
    echo "$*"
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
esac

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
``` 
the gradle-wrapper.jar is expected to create by "flutter create project".
If the `gradle-wrapper.jar` is missing, 
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

Related to : https://github.com/flutter/flutter/pull/26069

**Comment by Kakashi74** [comment]
I solve it for ubuntu 
-----------------------------
1- Install Gradle Build Tool On ubunto 
https://websiteforstudents.com/how-to-install-gradle-build-tool-on-ubuntu-16-04-18-04-18-10/  

2- `copy & paste on terminal  
sudo apt install default-jdk git curl libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386

**Comment by PascalProgrammingX** [comment]
> Yes

Goto Android Studio - File - Other Setting - Defaukt Project Structure
Uncheck use Embeded JDk
Below, set your JDK path.
Found in Program files - Java - Jdk.

**Comment by shiguiyou** [comment]
just change the number of 4.6 (example:distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip)
to the number you have run successfully android app once!

**Comment by PattaraponLertratananont** [comment]
> Got the same on MacOS with VScode and Android studio. VSCode doesn't give any other info then "Initiliazing gradle". Android studio prints the following after a few minutes:
> 
> ```
> Finished with error: Exit code 1 from: /Users/x/Projects/hello_world/android/gradlew -v:
> Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/x/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1-all.zip
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
> 	at org.gradle.wrapper.Install.createDist(Install.java:48)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> ```
> 
> Android studio 3.0.1
> Flutter plugin 22.2.1
> Flutter v0.1.5
> Dart 2.0.0-edge.0d5
> Gradle 4.1

it work for me

**Comment by Amrhalawani** [comment]
> ### **Solved Initializing gradle problem**
> The problem is that when first time we are trying to run our flutter project it does not have the required flutter gradle file. The required file size that gradle downloads is about 300-400MB that's why it takes so much time. Following are the steps:
> 
> 1. Run your project by clicking on the 'Run' button or flutter run in the command terminal
> 2. Then go to the place where your **.gradle** file is located (usually it is in the C:\Users<User Name>).  In the **.gradle** folder there is file name as **wrapper** in this there is **dists** folder. In **dists** folder there is gradle folder which is being downloaded.
> 3. wait till the gradle file is being downloaded and after sometime your project would compile.

its working thaaaaaanks

**Comment by DENGGE** [comment]
Maybe because of the proxy: don't choose **Automatic proxy configuration URL** or use **Manual proxy configuration**, and don't forget enter `https://www.google.com` in **Check connection** to verify.

**Comment by maheshmnj** [comment]
> I solve this problem!!!!
> 
> under flutter project, the file of `android/gradle/wrapper/gradle-wrapper.properties` indicates the version of gradle.
> 
> for exmaple, mine is `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`, so in my home `~/.gradle/wrapper/dists`, there should be a dir called `radle-4.10.2-all`, and under this dir, `xxxxx/gradle-4.10.2-all.zip.part` and `xxxxx/gradle-4.10.2-all.zip.lck`, NOTICE, here should have `gradle-4.10.2-all.zip`, if there is no such file, download it

This helped me I just dropped the gradle zip file in distributions which was missing

**Comment by grufelous** [comment]
@maheshmnj That works well. 
This problem arises when the `gradle` is either corrupt or missing from the local folders. In my case, it was corrupt - simply deleting the earlier `gradle` distribution and replacing it with the (latest) downloaded version solves the issue.

**Comment by OmkarKillarikar** [comment]
**Sometimes it downloads the gradle under the hood** saying "Initializing gradle". To make sure, go to the path where gradle is stored and **verify if size increases after some period of time**, if it does, be patient and **let it download the missing gradle distribution**.

**Comment by larryq** [comment]
Just want to lend my experience to this.  I was having this same trouble (gradle taking forever) on a flutter project I had cloned from github.  Given that I have built and run numerous flutter projects on my machine at this point, I was puzzled.

Turns out, this particular project was using an older version of gradle than I had on my machine.  I verified this by looking at the `~/android/gradle/wrapper/gradle-wrapper.properties` config file in this project.  It had listed `distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip` in there.  

I checked my gradle distribution folder at `c:\users\<my name>\.gradle\wrapper\dists` and saw a newly-dated folder for `gradle-4.1-all`

What was happening was the flutter project was downloading / installing this version of gradle while I was on a less-than-speedy internet connection.  When I checked, the folder was at 70mb in size, while my other three gradle folders were in the 300mb range.  So I stopped the build process, changed the distributionUrl property in my grade-wrapper.json file to a version I already had installed, and things went fine from there.  

I'm sure it would have also worked eventually if I had waited out the download of gradle 4.1.

**Comment by enasellithy** [comment]
i have same problem 
android studio 3.4
flutter channel master v v1.6.1-pre.36
ubuntu 19.04
Android SDK version 27.0.0
Flutter plugin version 35.3.1

**Comment by enasellithy** [comment]
i have same problem 
android studio 3.4
flutter channel master v v1.6.1-pre.36
ubuntu 19.04
Android SDK version 27.0.0
Flutter plugin version 35.3.1

> distributionUrl=https\://services.gradle.org/distributions/gradle-4.5.1-all.zip

i changed distributionUrl but still stuck

**Comment by rsonghao** [comment]
> ### **Solved Initializing gradle problem**
> The problem is that when first time we are trying to run our flutter project it does not have the required flutter gradle file. The required file size that gradle downloads is about 300-400MB that's why it takes so much time. Following are the steps:
> 
> 1. Run your project by clicking on the 'Run' button or flutter run in the command terminal
> 2. Then go to the place where your **.gradle** file is located (usually it is in the C:\Users<User Name>).  In the **.gradle** folder there is file name as **wrapper** in this there is **dists** folder. In **dists** folder there is gradle folder which is being downloaded.
> 3. wait till the gradle file is being downloaded and after sometime your project would compile.

It works!!!! Thank you very much!!!!!

**Comment by gazialankus** [comment]
This happened to me because the download failed when I had horrible internet connection and it would not work no matter how long I waited after I got better internet. I had to delete the `.gradle\wrapper\dists\gradle-4.1-all` to fix this.

**Comment by azax25547** [comment]
> I faced the same issue, but fixed when I changed gradle.properties from
> `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`
> to
> `distributionUrl=https\://services.gradle.org/distributions/gradle-4.5.1-all.zip`

Thanks for your idea. I saw in the .gradle/wrapper/dist directory and then changed to the latest gradle version and it worked

**Comment by sssalib42** [comment]
Close VS Code
Open VS Code
and it will work as expected!

**Comment by MoshDev** [comment]
I found it was because of slow internet connection, when i connected to a good speed internet and restarted Android Studio it did work well.

**Comment by GottfriedCP** [comment]
@andrisetyoo so I need to apply your [solution](https://github.com/flutter/flutter/issues/15106#issuecomment-541001598) each time I create new Flutter project, really? 
I have been trying to run the sample app from [flutter codelab](https://flutter.dev/docs/get-started/codelab) for hours.. no luck even though `flutter doctor` gave no error. 
Flutter 1.9.1 / Dart 2.5... more than one year later and still stuck.

**Comment by MohammedGhazy** [comment]
> For Windows:
> **Find:** `set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar`
> **Replace:** `set CLASSPATH=<path_to_downloaded_gardle>\gradle-4.6\lib\gradle-launcher-4.6.jar`
> 
> **Find:** `"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS%`
> **Replace:** `"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.launcher.GradleMain %CMD_LINE_ARGS%`
> 
> How about this?

where i found this?

**Comment by DaleSmith** [comment]
> Apparently it seems gradle is being downloaded
> For windows users:
> 
> * go to `%USER_HOME%\.gradle\wrapper\dists` delete the version based on the `gradle-wrapper.properties` in your project (for me it was `gradle-4.1-all` folder).
> * Invalidate Caches / Restart Android studio, then run the project
> 
> It would seem to be stuck at 'Initializing gradle' but from the here `'%USER_HOME%\.gradle\wrapper\dists'` you'd notice it recreated the deleted folder and starts to download the gradle distribution.
> 
> Be patient and let it finish.

![image](https://user-images.githubusercontent.com/19299704/72032846-99e6a180-32cb-11ea-8092-0db2ac756c18.png)
As is shown is the picture, I have various versions of gradle. Which version should I delete? Or should I just delete them all?

**Comment by gazialankus** [comment]
It will re-download if you delete them, so you can feel free do delete them all. Deleting the one that is actually being used should be sufficient, though.

**Comment by DanzTim** [comment]
My fix on Windows:
I went to `<user>\.gradle\wrapper\dists` and noticed that I have two versions of gradle, `gradle-4.10.2-all` and `gradle-5.4.1-all` and I noticed that 4.10.2 does not have the <gradle version>.-all.zip file but the 5.4.1 has, so in `android\gradle\wrapper\gradle-wrapper.properties` I changed `distributionUrl ` to 5.4.1, before it was 4.10.2

**Comment by Lucianoonaicul** [comment]
In my case my Internet connection was intermittent so the download of the zip file in /home/<my_user>/.gradle/wrapper/dists/gradle-5.6.2-all/9st6wgf78h16so49nn74lgtbb/ was stopping and getting locked. I deleted the content of "/home/<my_user>/.gradle/wrapper/dists/gradle-5.6.2-all/9st6wgf78h16so49nn74lgtbb/" and started my flutter app again and it worked.

**Comment by mahimakaushik-oss** [comment]
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download builder-3.5.0.jar (com.android.tools.build:builder:3.5.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.5.0/builder-3.5.0.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.5.0/builder-3.5.0.jar'.
            > Connect to dl.google.com:443 [dl.google.com/172.217.166.238] failed: Connection timed out: connect
   > Could not download kotlin-compiler-embeddable-1.3.50.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.50/kotlin-compiler-embeddable-1.3.50.jar'.
         > Read timed out
   > Could not download fastutil-7.2.0.jar (it.unimi.dsi:fastutil:7.2.0)
      > Could not get resource 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
            > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 16s


hello this is mahima. i am getting this error when i installed 6.7.1 gradle . can anyone guide me what to do next to resolve this......

**Comment by radikris** [comment]
> Apparently it seems gradle is being downloaded
> For windows users:
> 
> * go to `%USER_HOME%\.gradle\wrapper\dists` delete the version based on the `gradle-wrapper.properties` in your project (for me it was `gradle-4.1-all` folder).
> * Invalidate Caches / Restart Android studio, then run the project
> 
> It would seem to be stuck at 'Initializing gradle' but from the here `'%USER_HOME%\.gradle\wrapper\dists'` you'd notice it recreated the deleted folder and starts to download the gradle distribution.
> 
> Be patient and let it finish.

can you tell me, about what time should I expect till it will be downloaded?
