### ISSUE TITLE
Allow flutter tool to be given the project directory on the command line

### ISSUE THREAD

**Issue by Phrohdoh** [flutter/flutter#15109]
The title is a bit vague intentionally because I'm not sure which approach is more reasonable for Flutter (that is, if this is something desired at all).

The two approaches I have in mind are:

- `--manifest-path /path/to/some/pubspec.yaml`
- `--project /path/to/directory/containing/a/pubspec`

Of course the option names are subject to bikeshedding.

The idea here is to allow more flexible project layout and make it easier to manage/run/etc flutter projects in a different directory.

For example I just about always have the following structure:

```
.
├── README.md
├── docs
└── src
    ├── android
    ├── build
    ├── ios
    ├── lib
    ├── pubspec.lock
    ├── pubspec.yaml
    ├── test
    ├── myapp.iml
    └── myapp_android.iml
```

Which means I either end up writing a `Makefile` that invokes `flutter` in the `src` directory or I find myself constantly doing `(cd src ; flutter ...)` from the root.

---

**Edit**: Added a missing word.

**Comment by Phrohdoh** [comment]
I left out example `flutter` invocations.

```sh
$ pwd
/path/to/myapp

$ flutter run --manifest-path src/pubspec.yaml

# Let's pretend I have another flutter app somewhere else...
# From the same directory as above:
$ flutter run --manifest-path ../my-other-app/src/pubspec.yaml
```

Of course if we were to implement `--project` those invocations would be similar.

```
$ flutter run --project ../my-other-app/src/
```

Having to specify `src` is a bit unflattering IMO (but the choice to move what `flutter create` scaffolds out into a `src` dir was my own) and makes me wish `flutter` put the source in a `src` directory for me and had a top-level manifest.

**Comment by Hixie** [comment]
I believe actually that the `--packages` argument may be what you want here.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by luori-mvp77** [comment]
@Phrohdoh  Did you implemented this feature? I also want to specify the project path when execute command flutter run.

**Comment by JayDew** [comment]
Yes, I would also like to automate the testing of multiple flutter applications and I would really need to be able to specify an entry point via the command line (instead of actually cd -ing into the directory)
