### ISSUE TITLE
Can't load the images

### ISSUE THREAD

**Issue by EmelDroid** [flutter/flutter#151063]
### Steps to reproduce

when choosing the tab with the workouts lists with different cards and images it start giving this error

### Expected results

seeing the cards with images

### Actual results

exception throwing

### Code sample

<details open><summary>Code sample</summary>

import 'package:flutter/material.dart';
import '../widgets/section_title.dart';
import '../widgets/horizontal_workout_list.dart';
import '../widgets/workout_card.dart';

class WorkoutsList extends StatelessWidget {
  const WorkoutsList({super.key});

  @override
  Widget build(BuildContext context) {
    final List<Map<String, String>> newWorkoutsData = [
      {
        'title': 'Lower body burnout',
        'subtitle': 'Intense lower body workout',
        'image': 'images/login_background_2.jpg',
      },
      {
        'title': 'Upper body strength',
        'subtitle': 'Build upper body strength',
        'image': 'images/login_background_2.jpg',
      },
      {
        'title': 'Full body cardio',
        'subtitle': 'High-intensity cardio workout',
        'image': 'images/login_background_2.jpg',
      },
      {
        'title': 'Yoga for flexibility',
        'subtitle': 'Improve your flexibility',
        'image': 'assets/images/login_background_2.jpg',
      },
      {
        'title': 'Core workout',
        'subtitle': 'Strengthen your core muscles',
        'image': 'assets/images/login_background_2.jpg',
      },
    ];

    final List<Map<String, String>> topPicksData = [
      {
        'title': 'Morning Yoga',
        'subtitle': 'Start your day with yoga',
        'image': 'images/mail_image.png',
      },
      {
        'title': 'Evening Cardio',
        'subtitle': 'End your day with cardio',
        'image': 'images/mail_image.png',
      },
      {
        'title': 'Pilates',
        'subtitle': 'Strengthen your body with Pilates',
        'image': 'aimages/mail_image.png',
      },
      {
        'title': 'HIIT',
        'subtitle': 'High-Intensity Interval Training',
        'image': 'images/mail_image.png',
      },
      {
        'title': 'Meditation',
        'subtitle': 'Relax your mind and body',
        'image': 'images/mail_image.png',
      },
    ];

    final List<Map<String, String>> collectionsData = [
      {
        'title': 'Strength Collection',
        'subtitle': 'All about building strength',
        'image': 'images/workouts/workout1.jpg',
      },
      {
        'title': 'Cardio Collection',
        'subtitle': 'Cardio workouts for everyone',
        'image': 'images/workouts/workout2.jpg',
      },
      {
        'title': 'Flexibility Collection',
        'subtitle': 'Improve your flexibility',
        'image': 'images/workouts/workout3.jpg',
      },
      {
        'title': 'Core Collection',
        'subtitle': 'Strengthen your core',
        'image': 'images/workouts/workout4.jpg',
      },
      {
        'title': 'Balance Collection',
        'subtitle': 'Workouts to improve balance',
        'image': 'images/workouts/workout5.jpg',
      },
    ];

    final List<WorkoutCard> newWorkouts = newWorkoutsData.map((data) {
      return WorkoutCard(
        title: data['title']!,
        subtitle: data['subtitle']!,
        image: data['image']!,
      );
    }).toList();

    final List<WorkoutCard> topPicks = topPicksData.map((data) {
      return WorkoutCard(
        title: data['title']!,
        subtitle: data['subtitle']!,
        image: data['image']!,
      );
    }).toList();

    final List<WorkoutCard> collections = collectionsData.map((data) {
      return WorkoutCard(
        title: data['title']!,
        subtitle: data['subtitle']!,
        image: data['image']!,
      );
    }).toList();

    return ListView(
      children: [
        const SectionTitle(title: 'New Workouts'),
        HorizontalWorkoutList(cards: newWorkouts),
        const SectionTitle(title: 'Top Picks for You'),
        HorizontalWorkoutList(cards: topPicks),
        const SectionTitle(title: 'Collections', showViewAll: true),
        HorizontalWorkoutList(cards: collections),
      ],
    );
  }
}
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
/Users/.../Downloads/development/flutter/bin/flutter doctor --verbose
[!] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en)
    • Flutter version 3.22.2 on channel stable at /Users/.../Downloads/development/flutter
    ! The flutter binary is not on your path. Consider adding /Users/.../Downloads/development/flutter/bin to your path.
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.4.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/..../Downloads/development/flutter. Consider adding /Users/..../Downloads/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
Process finished with exit code 0
</details>

**Comment by LimaneGaya** [comment]
@EmelDroid Can you share the logs so we can see what the error is?

**Comment by droiden87** [comment]
Sorry I can't I changed most of the stuff so you can close this issue if it appears again will reopen

**Comment by danagbemava-nc** [comment]
Closing this based on https://github.com/flutter/flutter/issues/151063#issuecomment-2198585530
