### ISSUE TITLE
[Windows] Implement  getExternalStorageDirectories()

### ISSUE THREAD

**Issue by squarebrakets** [flutter/flutter#151059]
### Use case

Manage users drives from a flutter app. 

### Proposal

According to [path_provider] package comments only android can support retrieving external storage directories. Trying to use it on windows causes Unimplemented() Exception

I have added it on  [#7018](https://github.com/flutter/packages/pull/7018)

**Comment by stuartmorgan** [comment]
> ### Use case
> According to [path_provider] package comments only android can support retrieving external storage directories. Trying to use it on windows causes Unimplemented() Exception

This is a description of the current state of the package, not a use case. What is the high-level goal you are trying to accomplish?
