### ISSUE TITLE
Linux applications show black screen at start-up in debug mode

### ISSUE THREAD

**Issue by spydon** [flutter/flutter#151098]
### Steps to reproduce

Run any application (the counter example for example) in debug mode.

### Expected results

No black screens and no flickering in debug mode.

### Actual results

It will show a black screen at start-up and if you do some very wild scrolling it will also flicker with black.
It is present in any version >3.22.0, in 3.18.x and lower it works fine.

### Code sample

<details open><summary>Code sample</summary>

```dart
flutter create . && flutter run
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/744771/0c24a746-a8c0-4232-be4d-c9781cf5af08

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on Ubuntu 24.04 LTS 6.8.0-36-generic,
    locale en_US.UTF-8)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @spydon, what was the behaviour prior to stable 3.22.0? When I ran the app on 3.19.6, I saw a grey screen, is that what you were expecting?

**Comment by spydon** [comment]
> Hi @spydon, what was the behaviour prior to stable 3.22.0? When I ran the app on 3.19.6, I saw a grey screen, is that what you were expecting?
> 
> [Screencast from 07-02-2024 07:17:00 AM.webm](https://github.com/flutter/flutter/assets/88313112/94185ac5-f5db-4769-b31e-edc82df61d3d)

Yes exactly, since that is the background color of the GTK window.

**Comment by danagbemava-nc** [comment]
Thanks for the update. 

Labeling this for further investigation.

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.22.2, on Ubuntu 22.04.4 LTS 6.5.0-41-generic, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at /home/daniel/fvm/versions/stable
    ! Warning: `dart` on your path resolves to /home/linuxbrew/.linuxbrew/Cellar/dart/3.2.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /home/daniel/fvm/versions/stable. Consider adding /home/daniel/fvm/versions/stable/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/daniel/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/daniel/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/daniel/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.91

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
```
[!] Flutter (Channel master, 3.23.0-14.0.pre.117, on Ubuntu 22.04.4 LTS 6.5.0-41-generic, locale en_US.UTF-8)
    • Flutter version 3.23.0-14.0.pre.117 on channel master at /home/daniel/fvm/versions/master
    ! Warning: `dart` on your path resolves to /home/linuxbrew/.linuxbrew/Cellar/dart/3.2.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /home/daniel/fvm/versions/master. Consider adding /home/daniel/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f20962672e (4 hours ago), 2024-07-02 22:59:23 -0400
    • Engine revision c5c0c54d6d
    • Dart version 3.5.0 (build 3.5.0-323.0.dev)
    • DevTools version 2.37.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/daniel/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/daniel/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/daniel/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.91

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by spydon** [comment]
I think this might be a duplicate of https://github.com/flutter/flutter/issues/151098, so linux should be added as a platform there.

**Comment by Feichtmeier** [comment]
It is also happening on MacOs

https://github.com/flutter/flutter/assets/15329494/53a19dae-e532-4c6d-a385-c68e5627b726

and also in AOT mode. M series macbooks are just too fast to see it in release mode, but it is happening

https://github.com/flutter/flutter/assets/15329494/c6ccbd47-b057-46b2-b8f2-2d285bc1bc3c

**Comment by robert-ancell** [comment]
Due to the [rendering changes in preparation for GTK4](https://github.com/flutter/flutter/issues/41980) the background has changed to black (as set in the OpenGL code). This matches the MacOS behaviour. The background shows when the first frame is not received from Flutter in time (most visible in debug mode). The GTK background is less jarring, but it's a similar issue. It's not clear the correct way of handling this, but we have these options:
- Supporting rendering the GTK background, which may not be simple anymore.
- [Allowing the background color to be set] (https://github.com/flutter/flutter/issues/149920).
- [Allowing the app to set the splash screen](https://github.com/flutter/flutter/issues/41980).
- Hiding the window until the first frame is received.

**Comment by robert-ancell** [comment]
See also the similar [MacOS issue](https://github.com/flutter/flutter/issues/142916).

**Comment by robert-ancell** [comment]
Upon discussion with a colleague it might be that we're setting the clear color to (0,0,0,1) instead of (0,0,0,0) - I'll test this.

**Comment by robert-ancell** [comment]
Hmm, no. It doesn't seem to help using a different clear color (or omitting it entirely).

**Comment by Hixie** [comment]
An empty flutter app is expected to render a black window, but a Flutter app should not render anything until it gets its first frame from the Dart code, so there shouldn't be any black flicker if the Dart code paints something other than black.

The fix is probably to delay the creation of the window until we have pixels to draw?

**Comment by Hixie** [comment]
> What applications do require the background to be permanently black?

The simplest example of such an app is literally our simplest example:
   https://github.com/flutter/flutter/blob/master/examples/layers/raw/hello_world.dart

Another would be the game I'm working on right now, which broke when we regressed this recently (that's how I noticed).

> Ideally the flutter part in the background wouldn't show at all that is true, however when parts of the last layer of your window need a transparent effect, they get mixed into the black which is really looking "bad" / "ugly"

Certainly we should support transparency as well, on platforms that support it. We should expose an API to do that (e.g. on `SceneBuilder`, or `FlutterView.render`, or similar, which would then be exposed in the framework).

**Comment by Feichtmeier** [comment]
> > What applications do require the background to be permanently black?
> 
> The simplest example of such an app is literally our simplest example: https://github.com/flutter/flutter/blob/master/examples/layers/raw/hello_world.dart
> 
> Another would be the game I'm working on right now, which broke when we regressed this recently (that's how I noticed).
> 
> > Ideally the flutter part in the background wouldn't show at all that is true, however when parts of the last layer of your window need a transparent effect, they get mixed into the black which is really looking "bad" / "ugly"
> 
> Certainly we should support transparency as well, on platforms that support it. We should expose an API to do that (e.g. on `SceneBuilder`, or `FlutterView.render`, or similar, which would then be exposed in the framework).

Apps using transparency on blank flutter window could wrap themself inside a light / dark material/scaffold to prevent the black window. On the other side, apps you descripe could wrap themself inside a black material / scaffold, or am I misunderstanding something here? If I am not, the not-default-to-black-window approach has the advantage currently that there is no black frame showing up when the app starts (this also happens in AOT mode, not only in debug mode like the ticket opening post describes)

**Comment by Hixie** [comment]
The black frame showing up is a bug (it would be a white frame if we defaulted to white, or a transparent frame if we defaulted to transparent). That's a separate bug from what the default color is.

The default color is black because it's always been black and we need to be consistent across our platforms otherwise people will have a harder time porting apps between platforms.

To [reiterate](https://github.com/flutter/flutter/issues/151098#issuecomment-2254294503) my point from above, an _empty_ flutter app is expected to render a black window, but a Flutter app should not render _anything_ until it gets its first frame from the Dart code, so there shouldn't be any black flicker if the Dart code paints something other than black. The fix is probably to delay the creation of the window until we have pixels to draw.

**Comment by robert-ancell** [comment]
I think the solution to this ties in with the multi-window support. In the Linux embedder we currently create a view, which creates an engine. So the view is visible before we get the first frame. In the multi-window world we instead create an engine, which creates new views as requested by Flutter. With this architecture we can delay the view until the first frame is received.

**Comment by dpedrinha** [comment]
I'm not sure it's the same problem and I've not tested on linux, but my app is stuck in a black screen, right after startup, on some Android devices and emulators running Android API 33.

I just updated Android Studio and flutter master channel, created a new app, didn't change anything, and got the same error on an emulator running Android API 33.

Here's the debug log:

 `Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...
I/flutter ( 4143): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(133)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not allocate device memory for external image : ErrorOutOfDeviceMemory
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2337)
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(133)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not allocate device memory for external image : ErrorOutOfDeviceMemory
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2337)
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(133)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not allocate device memory for external image : ErrorOutOfDeviceMemory
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2337)
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(133)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not allocate device memory for external image : ErrorOutOfDeviceMemory
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2337)
Debug service listening on ws://127.0.0.1:37835/YGxMgVO70vw=/ws
Syncing files to device sdk gphone64 x86 64...
I/silia.aaflutter( 4143): Compiler allocated 4533KB to compile void android.view.ViewRootImpl.performTraversals()
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(111)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 4143): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(111)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 4143): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
E/flutter ( 4143): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(111)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 4143): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
W/Parcel  ( 4143): Expecting binder but got null!
D/ProfileInstaller( 4143): Installing profile for com.xxxxx.aaflutter`

Here's the flutter doctor:

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.26.0-1.0.pre.280, on Linux Mint 21.3 6.8.0-45-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.`

**Comment by spydon** [comment]
@dpedrinha Your issue is not related, the issue I reported was specifically only on Linux.

**Comment by dpedrinha** [comment]
> @dpedrinha Your issue is not related, the issue I reported was specifically only on Linux.

Have you tested it on Android?

**Comment by spydon** [comment]
> But if you didn't test it on other OSs, then it might be related. It's on top of flutter after all.

The issue was specifically in the Linux code (as can be seen in the merged PR), any potential Android issues are unrelated to this.
