### ISSUE TITLE
[Macros] Waiting on support for MemberDeclarationBuilder.typesOf(ClassDeclaration.library)

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#151017]
I know dart macros is not yet finished nor is it stable, however i'm wondering when this specific feature will be implemented: 

`MemberDeclarationBuilder.typesOf(ClassDeclaration.library)`

Also, im not sure where to track the progress on macros, is there a better place to check the progress on this specific feature? Should this be filed on the dart issue tracker? Any info would be helpful, thanks!

**Comment by darshankawar** [comment]
> Should this be filed on the dart issue tracker?

Yes, https://github.com/dart-lang/language/issues.

Closing from here.
