### ISSUE TITLE
Go Router: Widget is rebuilding when pressed back button while dropdown field is opened

### ISSUE THREAD

**Issue by MuhammadSaad420** [flutter/flutter#151096]
### Steps to reproduce

I know that upon pressing back button our widget will rebuild again and pop the screen. But when any dropdown widget is opened by the user, upon pressing back button, the widget is rebuilding. 

### Expected results

The dropdown field should be closed instead of rebuilding of the widget/screen.

### Actual results

The widget is rebuilding, which is resulting in resetting the state of the widget.

**Comment by darshankawar** [comment]
@MuhammadSaad420 
Can you provide complete runnable reproducible code sample (ex: main.dart) without third party implementation along with platform in which you are seeing this behavior ? Also provide `flutter doctor -v` and plugin version.

**Comment by MuhammadSaad420** [comment]
There is no specific code that is causing the issues. The only code that i can provide is drop down widget

```
class DropDownFieldWithTitle extends StatelessWidget {
  DropDownFieldWithTitle({
    super.key,
    required this.dropDownList,
    this.title,
    this.focusNode,
    this.onChanged,
    this.titleIcon,
    this.initialValue,
    this.validator,
  });

  final String? title;
  final List<String> dropDownList;
  final FocusNode? focusNode;
  final Function(String?)? onChanged;
  final IconData? titleIcon;
  final String? initialValue;
  String? Function(String?)? validator;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        if (title != null)
          Column(
            children: [
              Row(
                children: [
                  Flexible(
                    child: Text(
                      title!,
                      style: Theme.of(context)
                          .textTheme
                          .bodyMedium!
                          .copyWith(fontSize: 14),
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                  const Gap(2),
                  titleIcon != null
                      ? IconWidget(
                          icon: titleIcon!,
                          color: colorPrimary,
                          size: 14,
                        )
                      : const SizedBox.shrink()
                ],
              ),
              const Gap(13),
            ],
          ),
        DropdownButtonFormField<String>(
          key: key,
          decoration: const InputDecoration(
            contentPadding: EdgeInsets.symmetric(
              vertical: 13.5,
              horizontal: 10,
            ),
          ),
          isExpanded: true,
          focusNode: focusNode,
          icon: const IconWidget(
            icon: Icons.keyboard_arrow_down_outlined,
            color: colorGrey200,
          ),
          value: initialValue,
          hint: Text(loc.select_an_option),
          validator: validator,
          items: dropDownList
              .map<DropdownMenuItem<String>>(
                (String value) => DropdownMenuItem<String>(
                  value: value,
                  child: Text(
                    value,
                    style: Theme.of(context)
                        .textTheme
                        .bodyLarge!
                        .copyWith(color: colorBlack),
                  ),
                ),
              )
              .toList(),
          onChanged: onChanged,
        ),
      ],
    );
  }
}
```

**Platform:** Android Only


**Flutter Doctor:**

[✓] Flutter (Channel stable, 3.19.2, on macOS 14.2 23C64 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.90.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by darshankawar** [comment]
You are most likely hitting https://github.com/flutter/flutter/issues/99577 for which the response from team is as below:

https://github.com/flutter/flutter/issues/99577#issuecomment-1588228542
https://github.com/flutter/flutter/issues/99577#issuecomment-1589588241

Closing as duplicate.
