### ISSUE TITLE
How can I got a gen_snapshot_arm64 that can run on windows for ios-release

### ISSUE THREAD

**Issue by lilili87222** [flutter/flutter#151077]
### Use case

I found this file in windows is a mac binary
D:/Downloads/fluttersdk/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64
How can I get a file that can run on windows?

### Proposal

I think this file would be the same as android tools that can run on mac and windows

**Comment by jonahwilliams** [comment]
There is no build of gen_snapshot for windows hosts.

**Comment by lilili87222** [comment]
How to build gen_snapshot for windows hosts?

**Comment by stuartmorgan** [comment]
Could you describe your case? What you've put under "use case" in the report is just a question, so it's not clear what you are actually trying to accomplish.

**Comment by lilili87222** [comment]
I want to generate .s for ios on windows or linux

**Comment by stuartmorgan** [comment]
iOS builds on Windows or Linux hosts isn't a use case we support, so you would need to fork the engine and adjust its build scripts in order to do that.
