### ISSUE TITLE
[go_router] Pushing route on TypedStatefulShellBranch and then popping it leads to crash for 14.x.x

### ISSUE THREAD

**Issue by orkun1675** [flutter/flutter#151080]
### Steps to reproduce

1. Navigate to a TypedStatefulShellBranch
2. Push a regular route using the `MyRoute().push(context)` syntax
3. Within this new screen call `GoRouter.of(context).canPop()` which returns `true`
4. Now attempt `GoRouter.of(context).pop()`

Using:
* go_router: 14.2.0
* go_router_builder: 2.7.0

Downgrading to `go_router: 13.2.5` fixes the issue!

**I'm sorry I don't have the time to create a minimal reproducible sample right now, but hope to add one soon. If there are others encoutering this issue please chime in.**

### Expected results

The page is popped and we return to shell route.

### Actual results

App becomes unresponsive and crashes.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/flutter ( 5214): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 5214): Bad state: Future already completed
I/flutter ( 5214): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
I/flutter ( 5214): #1      ImperativeRouteMatch.complete (package:go_router/src/match.dart:455:15)
I/flutter ( 5214): #2      GoRouterDelegate._completeRouteMatch (package:go_router/src/delegate.dart:161:14)
I/flutter ( 5214): #3      GoRouterDelegate._handlePopPageWithRouteMatch.<anonymous closure> (package:go_router/src/delegate.dart:149:9)
I/flutter ( 5214): <asynchronous suspension>

<above log repeats hundreds of times, as if in an infinete loop>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/orkun/git/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/orkun/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
------

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by orkun1675** [comment]
After examining the logs again I've now come to believe that the route is attempted to be popped infinite times but never actually is.

**Comment by orkun1675** [comment]
The caused by a PopScope wiget that makes an internal call to save data to storage before calling `GoRouter.of(context).pop()`. The widget started being re-notified during the `pop` call, thus creating an infinite loop.

This behaviour (`GoRouter.of(context).pop()` notifying PopScope widgets) seems to be added in go_router v14 thus causing the breakage.

I was able to fix this quickly after realizing what was going on.

Maybe we can educate go_router users of this behaviour in the [14.0.0 migration notes](https://docs.google.com/document/d/1Z6RYo7rGIdtryvQvAntekF53zoz4iy4XvIamBxRWa4Y/edit?resourcekey=0-CH_yB7ur4gLvSuqPtB5bZA)?

**Comment by darshankawar** [comment]
Thanks for the detailed report and identifying, resolving the issue @orkun1675 

> I was able to fix this quickly after realizing what was going on.
> 
> Maybe we can educate go_router users of this behaviour in the [14.0.0 migration notes](https://docs.google.com/document/d/1Z6RYo7rGIdtryvQvAntekF53zoz4iy4XvIamBxRWa4Y/edit?resourcekey=0-CH_yB7ur4gLvSuqPtB5bZA)?

It'll be good if you could open a new documentation issue for this so that we can track it properly.
I'll close this issue as resolved.
