### ISSUE TITLE
[CP-Stable] Update dependency on package:unified_analytics from 5.8.8+1 to 5.8.8+2

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#151047]
### Issue Link

https://github.com/flutter/flutter/issues/150137

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/151046

### Changelog Description

Fixes issue where a log file would grow to an unreasonable size.

### Impacted Users

All flutter devs.

### Impact Description

This would waste a significant amount of storage on developer's machines. It could also result in out-of-memory errors and crashes due to FileSystemExceptions.

### Workaround

Manually delete the `.dart-tool\dart-flutter-telemetry.log` file every so often.

### Risk

low

### Test Coverage

yes

### Validation Steps

With telemetry enabled on your local Flutter installation:

* Replace your .dart-tool\dart-flutter-telemetry.log file with a large file. You can do this on Linux/macOS with `dd if=/dev/zero of=output.dat  bs=1m  count=30`
* Run the flutter tool (e.g. run `flutter build` inside of a project). This should send an analytics event.
* Check your dart-flutter-telemetry.log file. It should now be much smaller.

**Comment by zanderso** [comment]
cp lgtm

**Comment by itsjustkevin** [comment]
https://github.com/flutter/flutter/pull/151046 merged
