### ISSUE TITLE
EXC_BAD_ACCESS fatal crash on iOS 17 in 'path_provider_foundation'

### ISSUE THREAD

**Issue by JaffaKetchup** [flutter/flutter#151072]
### What package does this bug report belong to?

path_provider

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

pubspec.lock (please note that this is a reproduction on my machine, not from the original reporter (see below)): https://pastebin.com/1vejE0p3

### Steps to reproduce

This report is based on a report to a library I own: https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/159. Therefore, some information is limited as a 3rd party suffered the issue. I am providing as much information as possible, please let me know if more is required.

The issues seems to occur due to 'path_provider_foundation', however, the location where the bug apparently triggers does not use 'path_provider' at that point - instead, the method is using the [ObjectBox library](https://pub.dev/packages/objectbox).

I do not have an iOS device to reproduce the issue myself, and I cannot reproduce it on other platforms.

The full iOS platform crash log is included below.

The last breakpoint hit appears to suggest the following code triggers the issue - note that this is not an MRE and is heavily context dependent and uses ObjectBox - and so probably isn't that helpful, but included for continuity:

<details><summary>Code Sample A</summary>

```dart
Future<int> deleteTiles({
    required Query<ObjectBoxStore> storesQuery,
    required Query<ObjectBoxTile> tilesQuery,
  }) async {
    final stores = root.box<ObjectBoxStore>();
    final tiles = root.box<ObjectBoxTile>();

    bool hadTilesToUpdate = false;
    int rootDeltaSize = 0;
    final tilesToRemove = <int>[];
    final storesToUpdate = <String, ObjectBoxStore>{};

    final queriedStores = storesQuery.property(ObjectBoxStore_.name).find();
    if (queriedStores.isEmpty) return 0;

    // For each store, remove it from the tile if requested
    // For each store & if removed, update that store's stats
    await for (final tile in tilesQuery.stream()) { // APPEARS TO CRASH HERE
      tile.stores.removeWhere((store) {
        if (!queriedStores.contains(store.name)) return false;

        storesToUpdate[store.name] = (storesToUpdate[store.name] ?? store)
          ..length -= 1
          ..size -= tile.bytes.lengthInBytes;

        return true;
      });

      if (tile.stores.isNotEmpty) {
        tile.stores.applyToDb(mode: PutMode.update);
        hadTilesToUpdate = true;
        continue;
      }

      rootDeltaSize -= tile.bytes.lengthInBytes;
      tilesToRemove.add(tile.id);
    }

    if (!hadTilesToUpdate && tilesToRemove.isEmpty) return 0;

    root.runInTransaction(
      TxMode.write,
      () {
        tilesToRemove.forEach(tiles.remove);

        updateRootStatistics(
          deltaLength: -tilesToRemove.length,
          deltaSize: rootDeltaSize,
        );

        stores.putMany(
          storesToUpdate.values.toList(),
          mode: PutMode.update,
        );
      },
    );

    return tilesToRemove.length;
  }
```

</details>

This code is inside an isolate, and is called also from within the same isolate, with the following arguments:

<details><summary>Code Sample B</summary>

```dart
// This code is held within a switch statement executed by listening to a `RecievePort`

final String storeName = '<argument>';

final tiles = root.box<ObjectBoxTile>();
final stores = root.box<ObjectBoxStore>();

final storeQuery = stores.query(ObjectBoxStore_.name.equals(storeName)).build();
final store = storeQuery.findUnique() ?? (throw StoreNotExists(storeName: storeName));

final tilesQuery = (tiles.query()
        ..linkMany(
          ObjectBoxTile_.stores,
          ObjectBoxStore_.name.equals(storeName),
        ))
      .build();

deleteTiles(storesQuery: storeQuery, tilesQuery: tilesQuery).then((_) {
	// likely irrelevant, but effectively signals to the 'parent' 'main thread' isolate that the operation is complete
});
```

</details>

Therefore, my immediate suspicions are these - although I have no real idea:

* some sort of malfunctioning of 'path_provider' within an isolate
* some bad/unintended interaction in memory between 'path_provider' and ObjectBox somehow

I assume the issue occurs in 'path_provider' because that's what the crash logs mention. However, both 'path_provider' and ObjectBox have had similar issues in the past: https://github.com/flutter/flutter/issues/135921 (although it's very unclear here what the actual issue was, this feels like they could be the same issue) & https://github.com/objectbox/objectbox-dart/issues/379.

### Expected results

No error should occur. The operation should complete successfully.

### Actual results

The application fatally crashes with the exception shown in the logs below.

### Code sample

As I cannot reproduce the issue myself, I cannot provide an MRE without flutter_map_tile_caching.

However, the original reporter provided an MRE that uses the flutter_map_tile_caching dependency: https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/159#issuecomment-2195800441. It may be that more specific circumstances are required.

I can try to provide more information if possible, but given that I don't think I can reproduce this bug as it is, that's difficult.

The log below is produced on FMTC's example application.

### Logs

Basic error snippet: `DartWorker (177): EXC_BAD_ACCESS (code=1, address=0x12ab68010)`
iOS Platform Log: https://pastebin.com/qQCwULRb

### Flutter Doctor output

I'm unable to provide the exact output (this was not included in the original error issue), but these things are known:

* Device version (real/virtual unknown): iOS 17
* Flutter 3.22

**Comment by stuartmorgan** [comment]
There's no substantive logic in `path_provider_foundation`'s registration; for this crash to have happened, something earlier—almost certainly some other plugin's registration—has corrupted memory. Without a repro case, there's no way to isolate what plugin that is. If the original reporter can reproduce this specific crash, they can try removing other third-party plugins until the app launches normally.

(FYI, the answer to [this question](https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/159#issuecomment-2196934043) in the original report cannot be right; the crash log provided here is from app startup. Dart code was not yet executing when this crash log was generated.)

Closing as there's nothing actionable for `path_provider` here.
