### ISSUE TITLE
App inexplicably limited to 60Hz

### ISSUE THREAD

**Issue by Theaninova** [flutter/flutter#151067]
### Steps to reproduce

1. Create a minimal Flutter app with `flutter create sample_app`
2. Enable "show refresh rate" in the system settings
3. Run the app using `flutter run`, `flutter run --release` or `flutter run --enable-impeller` (all the same)
4. App is locked to 60Hz

**App can be forced into 120Hz**

This is not just an issue with the overlay, the app actually runs at 120FPS/Hz and feels noticeably smoother.

1. Open the app (60Hz)
2. Split screen with another app (i.e. settings). both now run at 120Hz
3. Dismiss the other app, the Flutter app now runs at 120Hz
4. Perform an action that hides the app (i.e lock screen, go to home screen, switch to another app)
5. Bring the app in the foreground, app now runs at 60Hz again

**Additional notes**

* The developer option "Force peak refresh rate" has no effect
* Selecting "Dynamic" or "High" as a refresh rate setting has no effect
* All Flutter apps I tested have this issue, none of the other apps I use do.
* Enabling impeller has no effect
* Switching between release, debug or profile has no effect

### Code sample

Problem appears with a minimal project (`flutter create app`)

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

Android 14 (Nothing OS 2.5.6), Nothing Phone (2a)

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Logs

<details open><summary>Logs</summary>

Running the app produces no additional logs.

The app can be force to run in 120Hz by going into split screen with another app

```console
A Dart VM Service on A142 is available at: http://127.0.0.1:42691/aqAxZyw81OU=/
The Flutter DevTools debugger and profiler on A142 is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:42691/aqAxZyw81OU=/
D/BLASTBufferQueue(31519): [SurfaceView[com.example.test_flutter/com.example.test_flutter.MainActivity]#1](f:0,a:2) destructor()
D/BufferQueueConsumer(31519): [SurfaceView[com.example.test_flutter/com.example.test_flutter.MainActivity]#1(BLAST Consumer)1](id:7b1f00000001,api:0,p:-1,c:31519) disconnect
D/BLASTBufferQueue(31519): [VRI[MainActivity]#0](f:0,a:1) destructor()
D/BufferQueueConsumer(31519): [VRI[MainActivity]#0(BLAST Consumer)0](id:7b1f00000000,api:0,p:-1,c:31519) disconnect
D/BufferQueueConsumer(31519): [](id:7b1f00000002,api:0,p:-1,c:31519) connect: controlledByApp=false
D/NtViewRootImpl(31519): mPopUpViewOffsets: offset=(0.0, 0.0), scale=(1.0, 1.0)
E/OpenGLRenderer(31519): Unable to match the desired swap behavior.
D/BufferQueueConsumer(31519): [](id:7b1f00000003,api:0,p:-1,c:31519) connect: controlledByApp=false
I/SurfaceView(31519): surfaceview vote min fps
D/BLASTBufferQueue(31519): [VRI[MainActivity]#2](f:0,a:1) acquireNextBufferLocked size=1084x1193 mFrameNumber=1 applyTransaction=true mTimestamp=883666893973516(auto) mPendingTransactions.size=0 graphicBufferId=135373074202627 transform=0
D/BLASTBufferQueue(31519): [SurfaceView[com.example.test_flutter/com.example.test_flutter.MainActivity]#3](f:0,a:1) acquireNextBufferLocked size=1084x1193 mFrameNumber=1 applyTransaction=true mTimestamp=883666936186439(auto) mPendingTransactions.size=0 graphicBufferId=135373074202628 transform=0
D/NtViewRootImpl(31519): mPopUpViewOffsets: offset=(0.0, 0.0), scale=(1.0, 1.0)
E/OpenGLRenderer(31519): Unable to match the desired swap behavior.
D/BLASTBufferQueue(31519): [VRI[MainActivity]#2](f:0,a:2) producer disconnected before acquireNextBufferLocked
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on NixOS 24.11 (Vicuna) 6.9.4, locale en_GB.UTF-8)
    • Flutter version 3.22.2 on channel stable at
      /nix/store/f53nadh5zgmpgsqqbsgx97wgpkm619jj-flutter-wrapped-3.22.2-sdk-links
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision nixpkgs000 (), 1970-01-01 00:00:00
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /nix/store/h5ab2igy330swi862wj099dkbbvlxixj-androidsdk/libexec/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT =
      /nix/store/h5ab2igy330swi862wj099dkbbvlxixj-androidsdk/libexec/android-sdk
    • Java binary at:
      /nix/store/23852pv6rvc8gj1x95m691qn8bz5l8r5-openjdk-17.0.11+9/lib/openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+9-nixos)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.29.3
    • ninja version 1.12.1
    • pkg-config version 0.29.2

[!] Android Studio (version 2023.3)
    • Android Studio at
      /nix/store/naki4kxxhrn2vn9xxiiknf1hymqxyz93-android-studio-stable-2023.3.1.19-unwrapped
    • Flutter plugin version 80.0.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • A142 (mobile)   • 192.168.0.37:45179 • android-arm64 • Android 14 (API 34)
    • Linux (desktop) • linux              • linux-x64     • NixOS 24.11 (Vicuna) 6.9.4

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by jonahwilliams** [comment]
I don't have a clue why this might be happening in this particular case, but in the past we have found instances of phone's limiting frame rate based on allowlists / heruistics or requiring an additional opt in frm  (https://github.com/flutter/flutter/issues/35162). Since the Flutter engine is using the recommended vsync waiter API from Android (https://developer.android.com/ndk/reference/group/choreographer) , we will generally always consume frames as fast as they are given.

**Comment by huycozy** [comment]
@Theaninova I don't have a 120Hz device but I can see this issue on 90Hz device (Pixel 7, Android 14 by enabling `Smooth display` on Display settings). On a newly create Flutter sample, it's initially displaying 90Hz then fall back to 60Hz. Once I interact within app (press FAB button so example), it turns into 90Hz. The same results as yours when switching to another app and back.

As Jonah linked an issue above, can you check https://github.com/flutter/flutter/issues/35162#issuecomment-609000841 if the given package can help on this?
