### ISSUE TITLE
flutter.bat'' finished with non-zero exit value -1073741795

### ISSUE THREAD

**Issue by dhiraj7072** [flutter/flutter#15119]
Launching lib\main.dart on Lenovo A7000 a in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Failed to run the Flutter compiler. Exit code: -1073741795

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Dhiraj\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 421

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command 'C:\Users\Dhiraj\flutter\bin\flutter.bat'' finished with non-zero exit value -1073741795

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Finished with error: Gradle build failed: 1

I reinstalling flutter 2 to 3 time but i am facing same error

**Comment by DanTup** [comment]
Could you try this to see if it gives more information?

> Run with `--stacktrace` option to get the stack trace. Run with `--info` or `--debug` option to get more log output.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
