### ISSUE TITLE
Unable to run flutter from Android Studio- Entry point isn't within current project

### ISSUE THREAD

**Issue by Sahas** [flutter/flutter#15111]
I created a new project using flutter, added english_words package as mentioned in the quick app guide. As the package contents were not reflecting, I restarted the Android Studio. Before restarting, the flutter run was working properly. After restart, I'm facing the below issue.

![image](https://user-images.githubusercontent.com/1641300/36938181-11fbdb10-1f44-11e8-9586-ebe4b6ca816b.png)

**Comment by Hixie** [comment]
cc @devoncarew IDE bug

**Comment by devoncarew** [comment]
This issue was moved to flutter/flutter-intellij#2307
