### ISSUE TITLE
Not possible to run some android tests in presubmit even when modifying ci.yaml 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#151114]
### Type of Request

bug

### Infrastructure Environment

https://github.com/flutter/flutter/pull/150808#issuecomment-2192287709
"Looks like we can't force the tests to run in pre-submit, ex:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux_mokey%20new_gallery_impeller__transition_perf/1/overview"

### What is happening?

When trying to verify the new gallery app tests pass after they failed in post submit even modifying the ci.yaml didnt let the android team confirm the tests would pass because there were no available bots in the presubmt pool that has the hardware requirements to run those tests. 

See https://github.com/flutter/flutter/pull/150808/commits/f5b88978818e50a5f8a7cdf8bb4b369e6f29e641 for the ci.yaml changes. 

### Expected results

It should be possible to run all android post submit tests in presubmit with some level of effort.

**Comment by reidbaker** [comment]
FWIW you can run that test locally just not against presubmit hardware.

**Comment by zanderso** [comment]
After https://github.com/flutter/flutter/issues/148085 is completed, we can evaluate whether we have capacity to shift a few mokey and/or pixel devices to the try pool in the devicelab.

**Comment by christopherfujino** [comment]
Prior art (but closed):

- https://github.com/flutter/flutter/issues/138430
- https://github.com/flutter/flutter/issues/111418

**Comment by matanlurey** [comment]
I am taking this on with the help of @christopherfujino and @loic-sharma.

**Comment by matanlurey** [comment]
This is still waiting for deivces to be hooked up (I think?)

**Comment by zanderso** [comment]
> This is still waiting for deivces to be hooked up (I think?)

Correct.

**Comment by matanlurey** [comment]
I believe this is done!
