### ISSUE TITLE
Ability to set flakiness threshold on a per-task/test in `ci.yaml`

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#151195]
Summary:

* #150838 is flaky by nature; it's an emulator test.
* It is still important to run as its the only end-to-end test for external textures.
* it's expensive to run some tests on devices.
* we really want this to be a smoke test

Suggestion:

Add `flakiness_threshold` as optional to ci.yaml and check it here:
https://github.com/flutter/cocoon/blob/b20de7e2b65d5dd61618f0f4303c5b19eb541266/app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart#L101-L104

Then we can tune our pain-threshold for specific tests.

**Comment by christopherfujino** [comment]
This seems reasonable
