### ISSUE TITLE
Change language of Gradle scripts in templates from Groovy to Kotlin

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#151166]
### Use case

Since 3.22, Flutter supports writing Gradle buildscripts in Kotlin, in addition to Groovy.

Using Kotlin instead of Groovy in Gradle buildscripts has many advantages and has been recommended by Gradle since April 2023 ([link](https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds)).

I think it makes sense to make Kotlin the default language, to bring those advantages to every Flutter developer, many of whom are understandably not experts in Gradle, Groovy, and their quirks.

### Proposal

Scope:
1. Change the language of files in Gradle templates from Groovy to Kotlin
2. Revise existing documentation on [flutter/website](https://github.com/flutter/website) to make sure it works equally well for both Groovy and Kotlin templates.

As for bullet point (2), it's worth noting that in many cases, Kotlin syntax in Gradle is a subset of Groovy syntax, so we in many cases we can just show Kotlin syntax and it'll work the same in Groovy, e.g.:

**Example 1**

This works only in Groovy:

```groovy
dependencies {
    implementation "com.example:my-artifact:1.2.3"
}
```

but the following works both in Groovy and in Kotlin:

```groovy
dependencies {
    implementation("com.example:my-artifact:1.2.3")
}
```

**Example 2**

This works only in Groovy:

```groovy
android {
    namespace "pl.baftek.discoverrudy"
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget "11"
    }

    defaultConfig {
        applicationId "pl.baftek.discoverrudy"
        minSdk 23
        targetSdk 34
        versionCode flutter.versionCode()
        versionName flutter.versionName()
    }
}
```

but this works in both:

```kotlin
android {
    namespace = "pl.baftek.discoverrudy"
    compileSdk = 34

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }

    defaultConfig {
        applicationId = "pl.baftek.discoverrudy"
        minSdk = 23
        targetSdk = 34
        versionCode = flutter.versionCode()
        versionName = flutter.versionName()
    }
}
```

---

**Alternatively**, we might decide to provide users with a switch when calling `flutter create`, e.g. `flutter create --android-build-language kotlin` and `flutter create --android-build-language groovy`.

### See also

https://github.com/flutter/flutter/issues/148586

**Comment by stuartmorgan** [comment]
> **Alternatively**, we might decide to provide users with a switch when calling `flutter create`, e.g. `flutter create --android-build-language kotlin` and `flutter create --android-build-language groovy`.

Template combinatorics are very painful for us to maintain. Is there a compelling need to support Groovy in the template?

**Comment by bartekpacia** [comment]
> Is there a compelling need to support Groovy in the template?

I don't think so.

> Template combinatorics are very painful for us to maintain.

I agree with this and would also prefer not to have to support both Groovy and Kotlin

**Comment by reidbaker** [comment]
Removed team tool because I think this has to happen by the android team with tooling support given the expertise required.

**Comment by bartekpacia** [comment]
@reidbaker I think you misunderstood the issue; I might've not explained it well enough, sorry.

The scope is to only change the language of Gradle files in brand new app, created with `flutter create`, from Groovy (`build.gradle`) to Kotlin (`build.gradle.kts`)

> We have done some prework to handle this situation including adding a kotlin linter.

I don't see how it's related to this – but I guess you mean we added linter to check the Flutter Gradle Plugin itself.

**Comment by reidbaker** [comment]
It would only have been related if this bug was tracking migrating the tooling we write in the flutter-tool to kotlin. Which is what I thought this bug was about.

**Comment by reidbaker** [comment]
@gmackall FYI Bartek is starting this work.

**Comment by danagbemava-nc** [comment]
Reopening this since the initial PR was reverted
