### ISSUE TITLE
CupertinoTabController documentation has a broken example

### ISSUE THREAD

**Issue by MitchellGoodwin** [flutter/flutter#151194]
<img width="1244" alt="Screenshot 2024-07-02 at 1 32 49 PM" src="https://github.com/flutter/flutter/assets/58190796/c5d54b46-faba-45e5-8afd-ccff2c69b271">

Doesn't show anything for the example. Looks like it just needs to be made a dartpad.

**Comment by RamonFarizel** [comment]
Hi Folks, I have created a PR fixing it.
Let me know If I'm missing something. 
It is my first time contributing to Flutter.
