### ISSUE TITLE
Jank in dismissal Animation in Android 

### ISSUE THREAD

**Issue by ajaybeniwal** [flutter/flutter#15116]
## Steps to Reproduce

I followed the sample app mentioned in the Write your first app steps , When i open the recently saved page it opens as usual but when the page is dismissed using back button it shows kind of Jank and animation does not feel smooth like native android app

**Comment by SKLn-Rad** [comment]
Glad I'm not the only one seeing this as I'm desperate to demo this as a solution to my agency.

Any update on this?

**Comment by xster** [comment]
You may be already doing it but please remember to run it in release mode (`flutter run --release`) as the debug mode performance is not representative of what your users will ultimately see.

**Comment by ajaybeniwal** [comment]
Even in release mode I see some jank in dismissal it does not feel as smooth as native dismissal

**Comment by Herohtar** [comment]
I think this is related to https://github.com/flutter/flutter/issues/15294

**Comment by zoechi** [comment]
The linked issue #13736 (#15294 is marked as dup of #13736) is fixed. 
Is this issue still relevant?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
