### ISSUE TITLE
Keyboard overlaps alertdialog

### ISSUE THREAD

**Issue by BarbaricGamester** [flutter/flutter#15123]
When I open the keyboard in an alertdialog the keyboard overlaps the dialog which is pretty inconvenient as the user can't even see what he is typing.

**Comment by fractalemagic** [comment]
Dupe of #7032, there's a fix in there aswell. Just note the last comment about using `mediaQuery.viewInsets` rather than `mediaQuery.padding`.

**Comment by Hixie** [comment]
Closing as duplicate.
