### ISSUE TITLE
DecorationImage add cacheWidth and cacheHeight parameter

### ISSUE THREAD

**Issue by hello-coder-xu** [flutter/flutter#151229]
### Use case

 when i check highlight oversized images,found `DecorationImage`  may be throw assert
```dart 
════════ Exception caught by painting library ══════════════════════════════════
The following message was thrown while painting an image:
Image https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg has a display size of 525×262 but a decode size of 520×521, which uses an additional 693KB (assuming a device pixel ratio of 2.625).

Consider resizing the asset ahead of time, supplying a cacheWidth parameter of 525, a cacheHeight parameter of 262, or using a ResizeImage.
════════════════════════════════════════════════════════════════════════════════
```

example:
``` dart
Container(
      width: 200,
      height: 100,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: NetworkImage('https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg'),
        ),
      ),
      child: const Text(
        'Image Demo',
        style: TextStyle(color: Colors.white),
      ),
    )
```

### Proposal

use this fix

Wrap `ImageProvider` with `ResizeImage.resizeIfNeeded`

```
Container(
      width: 200,
      height: 100,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        image: DecorationImage(
          // image: NetworkImage('https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg'),
          image: ResizeImage.resizeIfNeeded(
            200,
            100,
            const NetworkImage('https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg'),
          ),
        ),
      ),
      child: const Text(
        'Image Demo',
        style: TextStyle(color: Colors.white),
      ),
    )
```

hope
add `cacheHeight` and `cacheWidth`  in `DecorationImage`

**I don't know if this is necessary, if it is possible I can raise a PR**

**Comment by hello-coder-xu** [comment]
I have checked the `image`  and learned that `cacheWidth` and `cacheHeight` can be set in the image

However, In my actual work, I need to use `DecorationImage` in the `container` to set the image as the background display. The `image` property of `DecorationImage` needs to provide `ImageProvider`,  image is a` widget`. 

If the image actually displayed is larger than the size of the control, an assertion will be thrown

**Comment by darshankawar** [comment]
> an assertion will be thrown

Can you provide the complete assertion log ?

> I need to use `DecorationImage` in the `container` to set the image as the background display. The `image` property of `DecorationImage` needs to provide `ImageProvider`, image is a` widget`.

You can check in support channels like StackOverflow, if there's an already workable solution for this case.
