### ISSUE TITLE
Issue from website page Create a horizontal list

### ISSUE THREAD

**Issue by DreaddCZ** [flutter/flutter#15127]
From URL: https://flutter.io/cookbook/lists/horizontal-list.md

The "Complete example" does not have the horizontal scrolling inside. It is probably copied from another article.

**Comment by jordyvandomselaar** [comment]
The url you've provided gives back a 404.

**Comment by brianegan** [comment]
Thanks for the report! This is a dupe of https://github.com/flutter/flutter/issues/14914 and fixed by https://github.com/flutter/website/pull/822. I'm bugging some peeps for more reviews!

**Comment by brianegan** [comment]
Maintainers: This is now fixed on the website. Please close!
