### ISSUE TITLE
[Windows] After opening the application for a period of time, Flutter does not render any GUI, but instead displays a semi transparent window

### ISSUE THREAD

**Issue by LambGe** [flutter/flutter#151209]
### Steps to reproduce

After using it for a period of time, perhaps for an hour or more, the GUI will no longer display and become a semi transparent form, but the Flutter program is still running, except that the GUI is missing.
This bug only appeared on the computers of a few of my important clients.

### Expected results

Can operate normally and continuously.

### Actual results

![image](https://github.com/flutter/flutter/assets/119394755/33e74112-7c1d-431e-9471-fffa7a790967)

### Code sample

<details open><summary>Code sample</summary>

```C++
const wchar_t* WindowClassRegistrar::GetWindowClass() {
  if (!class_registered_) {
    WNDCLASS window_class{};
    window_class.hCursor = LoadCursor(nullptr, IDC_ARROW);
    window_class.lpszClassName = kWindowClassName;
    window_class.style = CS_HREDRAW | CS_VREDRAW;
    window_class.cbClsExtra = 0;
    window_class.cbWndExtra = 0;
    window_class.hInstance = GetModuleHandle(nullptr);
    window_class.hIcon =
        LoadIcon(window_class.hInstance, MAKEINTRESOURCE(IDI_APP_ICON));
        //(HICON)LoadImage(window_class.hInstance, MAKEINTRESOURCE(IDI_APP_ICON), IMAGE_ICON, 0, 0, LR_DEFAULTSIZE);
    window_class.hbrBackground = CreateSolidBrush(RGB(17, 17, 17));
    window_class.lpszMenuName = nullptr;
    window_class.lpfnWndProc = Win32Window::WndProc;
    RegisterClass(&window_class);
    class_registered_ = true;
  }
  return kWindowClassName;
}

bool Win32Window::Create(const std::wstring& title,
                                const Point& origin,
                                const Size& size) {
  Destroy();

  const wchar_t* window_class =
      WindowClassRegistrar::GetInstance()->GetWindowClass();

  double scale_factor = GetWindowScaleFactor();
  HWND window = CreateWindow(
      window_class, title.c_str(), WS_OVERLAPPEDWINDOW,
      Scale(origin.x, scale_factor), Scale(origin.y, scale_factor),
      Scale(size.width, scale_factor), Scale(size.height, scale_factor),
      nullptr, nullptr, GetModuleHandle(nullptr), this);

  if (!window) {
    return false;
  }
  UINT dpi = FlutterDesktopGetDpiForHWND(window);
  std::stringstream ss;
  ss << "Gets the DPI for window:" << dpi << ", scale factor:" << scale_factor << ".";
  std::cout << ss.str() << std::endl;

  UpdateTheme(window);

//  RegisterHotKey(window, VK_ESCAPE, 0, VK_ESCAPE);

  return OnCreate();
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![image](https://github.com/flutter/flutter/assets/119394755/d9aaf7de-0c71-4701-99bd-f3dfb0eef9c8)

### Logs

<details open><summary>Logs</summary>

```console
When this bug occurs, there are no exceptions or error outputs. And FlutterError.onError and runZonedGuarded and PlatformDispatcher.instance.onError do not catch anything.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [版本 10.0.22631.3737], locale zh-CN)
    • Flutter version 3.22.1 on channel stable at D:\dev\flutterSdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (6 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.0 Preview 1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.11.34929.205
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.90.2)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.81

[!] Network resources
    X A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到


! Doctor found issues in 1 category.

</details>
```

**Comment by huycozy** [comment]
@LambGe Could you point out what you modified the native code from the default one on a newly created project? Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Thanks!

**Comment by LambGe** [comment]
@huycozy 
I have packaged the modified files into a zip file, please take a look.
Below, I will list a few key points that I believe are:
1. The system topBar is hidden through the following code
2. Windows 10 Pro for Workstations 10.0 (Build 22621), this is the computer configuration of one of my problematic clients.
thank you.
![c534e19c1f273438c79f0c7de817b078](https://github.com/flutter/flutter/assets/119394755/585d0670-b8b0-410f-9b7a-dbdb0da0c39d)
![321947664047833e824efcd353d32f2e](https://github.com/flutter/flutter/assets/119394755/76759fa2-11ee-4a98-bf9f-160d2926ded9)

**Comment by LambGe** [comment]
The program is running normally without any abnormal output, only the GUI is missing. So, based on the analysis of these phenomena, it is speculated that FlutterView is hidden, and it may be necessary to re execute this code, but the timing of execution is unknown, for reference only. 
thank you.
![a47cd293e6e04a0932ccde786265bed1](https://github.com/flutter/flutter/assets/119394755/fd5ef49e-cf84-4b77-85b4-fb2e52ed42ac)

**Comment by huycozy** [comment]
Looks like you are using a 3rd party plugin, right? What is that plugin? Does the issue persist if you remove that plugin from project? 

Also, since you have modified native code with many files there, it would be more convenient to create a minimal and complete sample project on an opensource repository (GitHub for example) and please point out what you modified in `Steps to reproduce`  so that others can look into more easily. Thanks!

**Comment by LambGe** [comment]
Yes, introduce the window_manager third-party library for window management.

**Comment by huycozy** [comment]
I would suggest you open an issue on [window_manager](https://github.com/leanflutter/window_manager) repository for better support there first. Once the issue is confirmed that there is something wrong within Flutter framework/engine code, please come back and provide more information so we can investigate further.

**Comment by LambGe** [comment]
Thank you. Let's replace the window_manager first and discuss further if there are any issues.

**Comment by LambGe** [comment]
We have removed the window_manager third-party library and all related code, but this issue still exists. Please help us.

**Comment by LambGe** [comment]
Discovered a phenomenon for reference only.
1. When FlutterView disappears, calling the setState method in MyApp will crash.
2. When FlutterView to disappear, calling the setState of HomeWidget (the homepage under MyApp) will not crash at this time.
This bug has been appearing on an important client's computer**(Windows 10 Pro for Workstations 10.0 (Build 22621)**), please help me.

**Comment by huycozy** [comment]
There is only actual result ("_GUI will no longer display and become a semi transparent form_") but missing additional information (crash/warning logs if any, a complete sample code), we are unfortunately not sure how to solve this. 

Since you still can replicate this issue on your engineering team machine, I would suggest you narrow it down to see if there is any pattern to replicate it. And same as above, please provide a minimal and complete sample code so that we can look into.

**Comment by LambGe** [comment]
Dell Precision Tower 3431
![image](https://github.com/flutter/flutter/assets/119394755/bbf28f0f-71c2-4d78-a749-5080a6ea26e9)
![image](https://github.com/flutter/flutter/assets/119394755/d2001baf-de20-4197-8716-8dfad8250699)
![image](https://github.com/flutter/flutter/assets/119394755/f1b768fd-ec5f-4fe6-8c0b-55b59c70707b)
![image](https://github.com/flutter/flutter/assets/119394755/90c8fc9f-3ce5-4ece-9655-881aa09e6ace)
![image](https://github.com/flutter/flutter/assets/119394755/49fef6fc-2f51-4faa-8026-36b42c8738aa)
This is the customer's computer configuration. Please help us.

**Comment by LambGe** [comment]
In these days, we will provide a minimum and complete sample code for testing. Because this bug only occurs on this client's computer, it may be difficult to cooperate with our testing, but we will do our best to find them to cooperate. Thanks.
