### ISSUE TITLE
Deprecate `inactiveColor` property of `CupertinoCheckbox`

### ISSUE THREAD

**Issue by victorsanni** [flutter/flutter#151252]
### Use case

Since the inactive color of a `CupertinoCheckbox` can be configured by `fillColor` in inactive states, it makes no sense for this parameter to exist.

See conversation https://github.com/flutter/flutter/pull/148804#discussion_r1643437483 for more details.

https://github.com/flutter/flutter/pull/148804

### Proposal

Deprecate `inactiveColor`.

**Comment by rkishan516** [comment]
Hey @victorsanni, I have added fill color in `CupertinoCheckbox`. Once this PR is merged, I can go ahead and remove `inactiveColor`. If it sounds okay ?

**Comment by victorsanni** [comment]
Hi @rkishan516. Thanks for the linked PR. I do have a [PR](https://github.com/flutter/flutter/pull/151441) out that adds `fillColor` and associated tests in `CupertinoCheckbox` within the context of a myriad of fidelity updates.

**Comment by rkishan516** [comment]
Hey @victorsanni, Sure.
