### ISSUE TITLE
Request for left-aligned floating Action Button 

### ISSUE THREAD

**Issue by HungryAdi** [flutter/flutter#15122]
## Request

In making a demo app to get a grasp of Flutter, I wanted to add an additional action button on the opposite side of the screen (Floating Action Buttons are placed at the bottom right). I request the support for a button to be situated on the bottom left (inline with the right button).

**Comment by Ashad98** [comment]
I am Also facing the same problem.
i cannot create a floating action button on bottom left side.

**Comment by zoechi** [comment]
What does this mean exactly

> (inline with the right button). 

Did you check https://docs.flutter.io/flutter/material/Scaffold/floatingActionButtonLocation.html

With a custom https://github.com/flutter/flutter/blob/cb3df70da67bd5213ce81913e0e530fabe8d70e1/packages/flutter/lib/src/material/floating_action_button_location.dart#L120-L155 you should be able to specify the position.

**Comment by Ashad98** [comment]
i was also facing the same problem but i figured out a solution.

this is the code

`import 'package:flutter/material.dart';

class Inbox extends StatelessWidget{
  @override
    Widget build(BuildContext context) {
      return new MaterialApp(
        home: new _InboxHome(),
      );
    }
}

class _InboxHome extends StatefulWidget{
  @override
  State createState() => new InboxHomeState();
}

class InboxHomeState extends State<_InboxHome>{
  @override
    Widget build(BuildContext context) {
      return new Scaffold(
        appBar: new AppBar(
          title: new Text("Inbox"),
        ),
        drawer: new Drawer(),
        floatingActionButton: new Row(
          children: <Widget>[
            new Padding(
              padding: new EdgeInsets.symmetric(
                horizontal: 15.0,
              ),
            ),
            new FloatingActionButton(
              child: new Icon(Icons.remove),
            ),
            new Padding(
              padding: new EdgeInsets.symmetric(
                horizontal: 134.0,
              ),
            ),
            new FloatingActionButton(
              child: new Icon(Icons.add),
            ),
          ],
        ),
      );
    }
}`

**Comment by Ashad98** [comment]
i was also facing the same problem try this code

`import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget{
  @override
    Widget build(BuildContext context) {
      return new MaterialApp(
        home: new _InboxHome(),
      );
    }
}

class _InboxHome extends StatefulWidget{
  @override
  State createState() => new InboxHomeState();
}

class InboxHomeState extends State<_InboxHome>{
  @override
    Widget build(BuildContext context) {
      return new Scaffold(
        appBar: new AppBar(
          title: new Text("Inbox"),
        ),
        drawer: new Drawer(),
        floatingActionButton: new Row(
          children: <Widget>[
            new Padding(
              padding: new EdgeInsets.symmetric(
                horizontal: 15.0,
              ),
            ),
            new FloatingActionButton(
              child: new Icon(Icons.remove),
            ),
            new Padding(
              padding: new EdgeInsets.symmetric(
                horizontal: 134.0,
              ),
            ),
            new FloatingActionButton(
              child: new Icon(Icons.add),
            ),
          ],
        ),
      );
    }
}`

**Comment by zoechi** [comment]
@Ashad98 please edit your comment and wrap code in ```

**Comment by Ashad98** [comment]
Thank You for editing my code

**Comment by ThinkDigitalRepair** [comment]
I would like this built in as well, it only makes sense to have the third option.

**Comment by ThinkDigitalRepair** [comment]
Agreed

**Comment by Arno-Z** [comment]
Bumping this one. In my opinion apps should consider left and right-hand holding positions for users, where a startFloat or startDocked would allow users to use left thumb to access the button (based on app preferences, since the orientation cannot be sensed). 

I am aware this is not fully in line with Material design ;)

**Comment by zoechi** [comment]
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by ariG23498** [comment]
Making a floating action button go left is only possible if we use a row widget at the end with fabs as children, but we need to assign the `mainAxisAlignment: MainAxisAlignment.spaceBetween` between a fab and a padding

**Comment by psyanite** [comment]
I'd like to implement a FAB on the left that acts like a "go back" button on my app :) thank you contributors!!!

**Comment by leapit** [comment]
> i was also facing the same problem try this code
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(new MyApp());
> 
> class MyApp extends StatelessWidget{
>   @override
>     Widget build(BuildContext context) {
>       return new MaterialApp(
>         home: new _InboxHome(),
>       );
>     }
> }
> 
> class _InboxHome extends StatefulWidget{
>   @override
>   State createState() => new InboxHomeState();
> }
> 
> class InboxHomeState extends State<_InboxHome>{
>   @override
>     Widget build(BuildContext context) {
>       return new Scaffold(
>         appBar: new AppBar(
>           title: new Text("Inbox"),
>         ),
>         drawer: new Drawer(),
>         floatingActionButton: new Row(
>           children: <Widget>[
>             new Padding(
>               padding: new EdgeInsets.symmetric(
>                 horizontal: 15.0,
>               ),
>             ),
>             new FloatingActionButton(
>               child: new Icon(Icons.remove),
>             ),
>             new Padding(
>               padding: new EdgeInsets.symmetric(
>                 horizontal: 134.0,
>               ),
>             ),
>             new FloatingActionButton(
>               child: new Icon(Icons.add),
>             ),
>           ],
>         ),
>       );
>     }
> }
> ```

Use Expanded between two button seems better

```

floatingActionButton: new Padding(
        padding: const EdgeInsets.symmetric(horizontal: 0.0, vertical: 0.0),
        child: new Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            new Padding(
              padding: new EdgeInsets.symmetric(
                horizontal: 15.0,
              ),
            ),
            FloatingActionButton(
              child: new Icon(Icons.remove),
            ),
            new Expanded(
              child: new Text(""),
            ),
            FloatingActionButton(
              child: new Icon(Icons.add),
            ),
          ],
        ),
      ),
```

**Comment by PrakashJagan** [comment]
You can use padding only for left alignment

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  void _decrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter--;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: Padding(
        padding: const EdgeInsets.only(left: 30.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            FloatingActionButton(
//            onPressed: () {},
              onPressed: _incrementCounter,
              child: Icon(Icons.add),
            ),
            FloatingActionButton(
              onPressed: _decrementCounter,
              child: Icon(Icons.remove),
            )
          ],
        ),
      ),
      /*floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.*/
    );
  }
}

**Comment by PrakashJagan** [comment]
You can use padding only for left alignment

*class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  void _decrementCounter() {
    setState(() {
      _counter--;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: Padding(
        padding: const EdgeInsets.only(left: 30.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            FloatingActionButton(
              onPressed: _incrementCounter,
              child: Icon(Icons.add),
            ),
            FloatingActionButton(
              onPressed: _decrementCounter,
              child: Icon(Icons.remove),
            )
          ],
        ),
      ),
    );
  }
}*

**Comment by PrakashJagan** [comment]
You can use padding only for left alignment

```class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  void _decrementCounter() {
    setState(() {
      _counter--;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: Padding(
        padding: const EdgeInsets.only(left: 30.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            FloatingActionButton(
              onPressed: _incrementCounter,
              child: Icon(Icons.add),
            ),
            FloatingActionButton(
              onPressed: _decrementCounter,
              child: Icon(Icons.remove),
            )
          ],
        ),
      ),
    );
  }
}```

**Comment by PrakashJagan** [comment]
You can use padding only for left alignment like this...

```class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  void _decrementCounter() {
    setState(() {
      _counter--;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: Padding(
        padding: const EdgeInsets.only(left: 30.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            FloatingActionButton(
              onPressed: _incrementCounter,
              child: Icon(Icons.add),
            ),
            FloatingActionButton(
              onPressed: _decrementCounter,
              child: Icon(Icons.remove),
            )
          ],
        ),
      ),
    );
  }
}

**Comment by hasen6** [comment]
I have to agree, it is pretty weird and seems unfinished. `FloatingActionButtonLocation` allows positioning in the top left or right, but only the bottom right? Surely an oversight and not intentional...?

**Comment by dieudv** [comment]
FloatingActionButtonLocation.startUp and FloatingActionButtonLocation.endTop are currently align vertically center and it's misleading, I think instead should push it upwards.

**Comment by patelkrunal78** [comment]
Try wrapping it in a Center widget or use a crossAxisAlignment of CrossAxisAlignment.center on your Column.

You should pick one part of your Column to be wrapped in a Flexible that will collapse to avoid overflow, or replace some or all of it with a ListView so users can scroll to see the parts that are hidden.

https://icetutor.com/question/flutter-floatingactionbutton-in-the-center

**Comment by im-amir** [comment]
Still, there is no solution. Please, resolve this issue

**Comment by pennzht** [comment]
I am working on this.

**Comment by pennzht** [comment]
The PR https://github.com/flutter/flutter/pull/51465 is merged.
You can now set the `floatingActionButtonLocation` of your `Scaffold` to `FloatingActionButtonLocation.startFloat` to create a FAB in the lower-left corner of the scaffold.

We did not implement support for *multiple* FABs on the same scaffold, as this is against Material guidelines.
