### ISSUE TITLE
Debugging with breakpoints has become significantly more difficult

### ISSUE THREAD

**Issue by HaydenHMSD** [flutter/flutter#151225]
### Steps to reproduce

1. Set a breakpoint
2. Run the code
3. Hit the breakpoint
4. Attempt to do any normal debugging action - remove it, edit code to quickly fix it

### Expected results

I should be able to disable the break point if I'm no longer interested
If I see what needs to be changed I should be able to change it

### Actual results

the file is readonly and I can't remove the break point
I have to hunt for the file to be able to do anything
This takes around 5 seconds to do something that should be done in 0.2 seconds
This level on anti-optimisation is infuriating.
I don't want to have to disable ALL breakpoints when I just want to remove one and keep the others.
I don't want to have to hunt for a file just to change a value.
The read only file is _NEVER_ next to the file where the breakpoint was hit, so hunting is _ALWAYS_ necessary.
5 seconds to find a file may not sound like a lot to most people, but to people like me who notice small jumps in time differences it means a lot and it induces rage.

### Code sample

<details open><summary>Code sample</summary>

```dart
Widget build(BuildlContext context) {
    print('building');
    return Container();
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 13.6 22G120 darwin-x64, locale en-AU)
    • Flutter version 3.22.1 on channel stable at /Users/haydenyoung/DevTools/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (6 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/haydenyoung/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • iPhone 15 (mobile)           • F1E5B2D7-721E-4903-A6A8-19923CA92B03 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 13.6 22G120 darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for iPhone de Zyme. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
@HaydenHMSD 
I tried using debugger and breakpoints in a sample app and was able to use it without any highlighted issues you reported. Can you provide a short video of the behavior you are seeing ?  Are you using VSCode or AS as your IDE ?

**Comment by HaydenHMSD** [comment]
@darshankawar 
Hi, thanks for your reply!

I am using Android Studio as my IDE

I've attached two screenshots to hopefully help. It's a little harder to do a video at the point in time.

In this screenshot at the top I am in the profile_scene.dart file, three files to the left is the lib/../profile_scene.dart file.
The former is what I get when I hit the break point. The latter is the file that has the breakpoint.
<img width="707" alt="Screenshot 2024-07-03 at 14 09 16" src="https://github.com/flutter/flutter/assets/87422242/2753db79-1fb4-4a42-ad13-9b05cbbdd57f">

In this screenshot I have gone to the lib/../profile_scene.dart, here you can see the breakpoint that I _did_ set.
<img width="709" alt="Screenshot 2024-07-03 at 14 11 29" src="https://github.com/flutter/flutter/assets/87422242/ebe07f43-3416-4029-b3bc-4209a1b99159">

let me know if a video will illustrate this better and I'll film it when I get the chance to

**Comment by darshankawar** [comment]
Are you using uptodate flutter plugin for AS ?

**Comment by HaydenHMSD** [comment]
@darshankawar oh updating that worked. Wow, how embarrassing! 😅
