### ISSUE TITLE
Input box assignment paste display incomplete

### ISSUE THREAD

**Issue by dullgrass** [flutter/flutter#151211]
### Steps to reproduce

1. Create an input box
2. Enter a piece of text
3. Copy and paste - the display is incomplete

### Expected results

Copy and paste display complete 

### Actual results

Copy and paste - the display is incomplete

### Code sample

This can be reproduced with any version of Flutter

### Screenshots or Video

![键盘](https://github.com/flutter/flutter/assets/6779357/adcb7032-dd33-4044-9e82-5fd6663864e4)

### Flutter Doctor output

This can be reproduced with any version of Flutter

**Comment by danagbemava-nc** [comment]
There's a general issue tracking fidelity of the toolbar options on all supported flutter platforms in https://github.com/flutter/flutter/issues/107578. Kindly follow that issue for updates. 

Closing as duplicate. 

Thank you
