### ISSUE TITLE
Flutter IPA build in debug mode crashes

### ISSUE THREAD

**Issue by saikrishna321** [flutter/flutter#151236]
### Steps to reproduce

Build the Flutter app for real device iOS in debug mode. 

Command used 
```
flutter build ipa --debug --export-options-plist=/Documents/ExportOptions.plist  /Downloads/git/appium-flutter-server/demo-app/integration_test/appium.dart
```

This generates an IPA in development mode. 

Installed the APP on real device and we see the app crashes with the below error 

```
{"msg":"Jul  3 17:53:59 God- Runner(Flutter)[66186] \u003cNotice\u003e: Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode.\n\nTo launch in debug mode in iOS 14+, run flutter run from Flutter tools, run from an IDE with a Flutter IDE plugin or run the iOS project from Xcode.\nAlternatively profile and release mode apps can be launched from the home screen."}
```

Why we want to build the IPA in debug mode and not release mode?

When we build the app in Release we are unable to use bySemanticsLabel to run integration tests. 

In debug app it works fine. 

If we are missing anything please guide us.

### Expected results

Should be able to run the Archived Debug IPA in real device.

### Actual results

App crashes on real device.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
❯ flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.3)
[✓] VS Code (version 1.89.1)
[✓] VS Code (version 1.74.0)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @saikrishna321, as stated in the error message, this is a limitation that was introduced in iOS 14. There's not much we can do without the xcode tooling. See https://github.com/flutter/flutter/issues/60657#issuecomment-688478590 & https://github.com/flutter/flutter/issues/60657#issue-648616477 for a detailed explanation. 

I would recommend you file an issue that you are having with the integration tests with detailed steps to reproduce so that it can be properly addressed. 

Closing from here. 

Thank you

**Comment by saikrishna321** [comment]
@danagbemava-nc Thank you so much for looking into the issue and for quick response. 

I have raised https://github.com/flutter/flutter/issues/151238 for integration test.
