### ISSUE TITLE
add support to ios device for `flutter start` args

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1512]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/device_ios.dart#L190

`checked`, `mainPath`, `clearLogs`, `route`

**Comment by chinmaygarde** [comment]
Specifying the `mainPath` on iOS is a bit problematic since the precompiler needs to be run from a separate location. I have wired in the rest of the flags.
