### ISSUE TITLE
The framework should track which view has focus and notify changes to the engine

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#151251]
### Use case

Autofocus annotations in widgets should cause the platform focus to move to right view if needed

### Proposal

The framework should track which view has focus (if any) and as soon as it changes it should call `PlatformDispatcher.requestViewFocusChange` with the proper configuration so that the engine can react accordingly.

**Comment by ditman** [comment]
@tugorez is this the same as:

* https://github.com/flutter/flutter/issues/144235

?
