### ISSUE TITLE
InkWell onLongPress not respecting HapticFeedback conditional

### ISSUE THREAD

**Issue by corepuncher** [flutter/flutter#151260]
### Steps to reproduce

1) Make an InkWell widget.
2) Add an "onLongPress".
3) Inside onLongPress, add a condition that is always false, and inside it, put HapticFeedback.lightImpact();

### Expected results

If the condition is false, the HapticFeedback should not occur.

### Actual results

The haptic feedback occurs no matter what the conditional.

The workaround is to use a GestureDetector if you can.

### Code sample

<details open><summary>Code sample</summary>

```dart
                        InkWell(
                              onTap: () {
                                doSomething;
                              },
                              onLongPress: () {
                                if (0 > 1) {
                                  HapticFeedback.lightImpact();
                                  setState(() {
                                    doSomethingElse;
                                  });
                                }
                              }, ...```

**Comment by lxhlzyh** [comment]
Set enableFeedback to false.
`InkWell(enableFeedback: false,)`

**Comment by corepuncher** [comment]
That was the solve, thanks!  It is not apparent why a condition would be ignored, so must be something going on in the background I had no earthly idea about.
