### ISSUE TITLE
[google_maps_flutter] Flutter add-to-app module freeze on iOS.

### ISSUE THREAD

**Issue by Tauheed** [flutter/flutter#151232]
### Steps to reproduce

I am working on a iOS native application which has a bottom tabbar (iOS Tabbar) with 5 different screens.
2 of them are initiated as flutter add-to-app  modules using pod.
Both modules have different flutter engines.
In one module I have a GoogleMap using package (Link: https://pub.dev/packages/google_maps_flutter). 
And in another one a simple UI.
Both modules are working fine when I open individually from the tabbar. But the problem is when I switch between the modules then, the module which has the simple UI freezes.
Surprisingly If I remove google map from first module then both modules work fine.
If I hide bottom tabbar again both modules work fine.
The problem is occurring because of GoogleMap with native iOS bottom Tabbar only. I have tried replacing the GoogleMap widget with Apple map widget as well, result is the same.
Using Google Map package (version: 2.5.3):  https://pub.dev/packages/google_maps_flutter
Flutter: Stable channel (version:  3.16.0)
  
I even tried both latest flutter channel and GoogleMap() package but freeze issue still exists.

### Expected results

Should not freeze.

### Actual results

Getting freeze.

### Code sample

GoogleMap(
    initialCameraPosition: _mapCameraPosition(),
    mapType: MapType.none,
)

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter Doctor: 
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.16.0, on macOS 14.3.1 23D60 darwin-x64, locale en-IN)
    ! Flutter version 3.16.0 on channel [user-branch] at /Users/tauheed/TA-Developer/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.61.0)
[✓] Connected device (3 available)            
    ! Error: Browsing on the local area network for Tauheed iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

**Comment by Tauheed** [comment]
flutter doctor -v: 
[!] Flutter (Channel [user-branch], 3.16.0, on macOS 14.3.1 23D60 darwin-x64, locale en-IN)
    ! Flutter version 3.16.0 on channel [user-branch] at /Users/tauheed/TA-Developer/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision db7ef5bf9f (8 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tauheed/Library/Android/sdk
    • Platform android-34, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.61.0)
    • VS Code at /Users/tauheed/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone_TA (mobile)         • 00008101-001A71D21144001E            • ios            • iOS 16.6 20G75
    • iPhone 15 Pro Max (mobile) • 0530AFB1-042C-4AD0-9413-62B00A95DFB9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 14.3.1 23D60 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for Farheen’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Hi @Tauheed, this looks similar to a case described at https://github.com/flutter/flutter/issues/136192 which is an issue with platformviews in general. I will close this in favor of that one so please follow that issue for updates. Thanks!

**Comment by Tauheed** [comment]
@huycozy The ticket you shared as duplicated also does not have any solution and its open from last 1 year approx.
Do you guys have any timeline to resolve the issue. Its a major blocker.

**Comment by huycozy** [comment]
@Tauheed That issue has been prioritized with p2 which means the team agrees that it is important to work on. Please see [Priorities](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#priorities).
