### ISSUE TITLE
Hot reload loses device connection on Windows

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#15120]
```
Master: commit = fbf68bbc6daa7a4f0b6f7b738b0134a318c4974b
[√] Flutter (Channel master, v0.0.0-unknown, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
[√] VS Code (version 1.20.1)
[√] Connected devices (1 available)
```

After starting a Flutter app either via an IDE or via `flutter run`, Flutter will lose the connection to the Android Emulator when attempting a hot reload or a full restart with an error message similar to:

```
Initializing hot reload... 
D/ (18113): HostConnection::get() New Host Connection established 0xa4623ac0, tid 18134 Lost connection to device.
```
Restarting the device doesn't help.

/cc @devoncarew

**Comment by DanTup** [comment]
There are quite a few issues about crashes and disconnects during hot reloads, but I think mostly only see them through the IDE and it's fine from the CLI. Some possibly related cases:

https://github.com/flutter/flutter/issues/14945
https://github.com/flutter/flutter-intellij/issues/1809
https://github.com/flutter/flutter/issues/14847
https://github.com/flutter/flutter/issues/14633
https://github.com/flutter/flutter/issues/14312

**Comment by lukef** [comment]
I'm seeing this crash in the CLI also unfortunately.

**Comment by DanTup** [comment]
Maybe this?

https://github.com/flutter/flutter/issues/14945#issuecomment-370973017

Seems like maybe Windows path issues (slashes) causing problems.

**Comment by zarub2k** [comment]
I am also facing a similar problem regularly

Initializing hot reload...
D/ (11339): HostConnection::get() New Host Connection established 0x9b7e4a80, tid 11362
Lost connection to device.

Is there any workaround to resolve this? This is completely blocking my productivity.

**Comment by grindvoll** [comment]
#14945 has just been closed (and the fix is merged to master). I think it should resolve this issue as well.

**Comment by zarub2k** [comment]
I am using beta channel for now. Will the fix be available in beta? I am very bored by this problem right now.

**Comment by yfer** [comment]
Had this issue in beta, can confirm it's gone in master.

@zarub2k You can do "flutter channel master" and "flutter packages upgrade" and change back when current master will be merged to current beta.

**Comment by devoncarew** [comment]
Closing as fixed (and a dup of https://github.com/flutter/flutter/issues/14945).
