### ISSUE TITLE
`GoogleMap` widget needs an `onError` parameter

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#151395]
### Steps to reproduce

The `GoogleMap` widget in Flutter does not report errors back to Dart, it only logs them to logcat in native code, then (sometimes) proceeds to display a very low-res map in the place of the expected map.

```
E/Google Android Maps SDK(16056): Authorization failure.  Please see https://developers.google.com/maps/documentation/android-sdk/start for how to correctly set up the map.
E/Google Android Maps SDK(16056): In the Google Developer Console (https://console.developers.google.com)
E/Google Android Maps SDK(16056): Ensure that the "Maps SDK for Android" is enabled.
E/Google Android Maps SDK(16056): Ensure that the following Android Key exists:
E/Google Android Maps SDK(16056): 	API Key: <redacted>
E/Google Android Maps SDK(16056): 	Android Application (<cert_fingerprint>;<package_name>): <redacted>
```

![image](https://github.com/flutter/flutter/assets/811305/b982f0b0-99b5-4db0-886a-df46c815c76b)

There needs to be a way for Flutter code to be notified if the Maps API key and SHA-1 signature don't match, or if the API key is invalid, or if a quota is exceeded, etc.

Currently there is an `onMapCreated` method that calls a callback with a `GoogleMapController` argument. However, that call is always made even if there is an API error. Additionally, there may be further errors after the map is successfully created, e.g. if a quota or rate limit is exceeded.

### Expected results

The `GoogleMap` widget should accept an `onError` argument that is called when any error occurs.

### Actual results

Dart code is never notified if there is an error generated in the native code backing the `GoogleMap` widget.

This means that apps may break in an unfixable way. For example, my app is supposed to prevent a user from creating an event until they have chosen a location on the map for their event. Currently the user may be prevented from creating their event at all, because they may not be able to choose a location on the map due to an API error. And my app has no way of knowing that it has become impossible for the user to create their event.

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on Fedora Linux 40 (Workstation Edition) 6.8.10-300.fc40.x86_64, locale en_US.utf8)
    • Flutter version 3.23.0-0.1.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (5 weeks ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.6 (Fedora 18.1.6-3.fc40)
    • cmake version 3.28.2
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[✓] Android Studio (version 2023.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 79.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.93.20240702

[✓] VS Code (version 1.90.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.91.20240529

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora Linux 40 (Workstation Edition) 6.8.10-300.fc40.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 125.0.6422.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
> or if the API key is invalid,

I think currently it does throw this error.

For rest of the issue description, I will treat this as a proposal to add `onError` to `GoogleMap` widget.

**Comment by stuartmorgan** [comment]
> The `GoogleMap` widget in Flutter does not report errors back to Dart, it only logs them to logcat in native code, then (sometimes) proceeds to display a very low-res map in the place of the expected map.

The logging reported here comes from within the Google Maps SDK, not the plugin code.

> The `GoogleMap` widget should accept an `onError` argument that is called when any error occurs.

There is no corresponding API in the Google Maps SDK for Android, so there is no way to implement this proposal; in general this:

> ### Actual results
> Dart code is never notified if there is an error generated in the native code backing the `GoogleMap` widget.

is true of the native plugin code as well, meaning there is nothing to pass to Dart.

Closing as there is no way to implement this request using the Google Maps SDK. You would need to file a Google Maps SDK for Android feature request for changes to its API surface to pass these errors to clients rather than just logging them.
