### ISSUE TITLE
On impeller, the vertices API is off by 1 pixel when using fragment shaders and `textureCoordinates`

### ISSUE THREAD

**Issue by renancaraujo** [flutter/flutter#151355]
### Steps to reproduce

Given any project, in the stable channel: 

- use draw vertices to paint some triangles using a `Paint` object as texture with a fragment shader.
- if you specify `textureCoordinates`, the bottom and right edges will be off by 1 pixel.

### Expected results

To have the proper pixels painted.

### Actual results

Pixels painted are removed by 1 pixel in the left and bottom edges. See screenshots and code sample below.

### Code sample

<details open><summary>Code sample</summary>

For example, given that we are painting in a canvas region of size 100x100.
If we divide the canavs region by 4 quadrants and paint the following vertices:

```dart

// Two triangles covering the top left quadrant of the region
final vertices1 = Float32List.fromList([
  0.0, 0.0,
  50.0, 0.0,
  50.0, 50.0,
  0.0, 0.0,
  0.0, 50.0,
  50.0, 50.0,
]);

canvas.drawVertices(
  Vertices.raw(
    VertexMode.triangles,
    vertices1,
    textureCoordinates: Float32List.fromList(vertices1),
  ),
  BlendMode.srcOver,
  Paint()..shader = shader, // any fragment shader
);

// Two triangles covering the top right quadrant of the region
final vertices2 = Float32List.fromList([
  50.0, 0.0,
  100.0, 0.0,
  100.0, 50.0,
  50.0, 0.0,
  50.0, 50.0,
  100.0, 50.0,
]);

canvas.drawVertices(
  Vertices.raw(
    VertexMode.triangles,
    vertices2,
    textureCoordinates: Float32List.fromList(vertices2),
  ),
  BlendMode.srcOver,
  Paint()..shader = shader, // any fragment shader
);

// Two triangles covering the bottom left quadrant of the region
final vertices3 = Float32List.fromList([
  0.0, 50.0,
  50.0 50.0,
  50.0, 100.0,
  0.0, 50.0,
  0.0, 100.0,
  50.0, 100.0,
]);

canvas.drawVertices(
  Vertices.raw(
    VertexMode.triangles,
    vertices3,
    textureCoordinates: Float32List.fromList(vertices3),
  ),
  BlendMode.srcOver,
  Paint()..shader = shader, // any fragment shader
);

// Two triangles covering the bottom right quadrant of the region
final vertices4 = Float32List.fromList([
  50.0, 50.0,
  100.0, 50.0,
  100.0, 100.0,
  50.0, 50.0,
  50.0, 100.0,
  100.0, 100.0,
]);

canvas.drawVertices(
  Vertices.raw(
    VertexMode.triangles,
    vertices4,
    textureCoordinates: Float32List.fromList(vertices4),
  ),
  BlendMode.srcOver,
  Paint()..shader = shader, // any fragment shader
);

```

</details>

## Reproducible sample

Ive created a reproducible sample here: https://github.com/renancaraujo/impeller_drawvertices_issue

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration (impeller)</summary>

The gaps observed when running with impeller on macos with pixel ratio of 1:

![Screenshot 2024-07-05 at 22 45 24](https://github.com/flutter/flutter/assets/6718144/20e80560-bb82-43d5-8d74-7d94ef0eb727)

</details>

<details open>
<summary>Screenshots / Video demonstration (skia)</summary>

The gap is not observed when running with skia in the same environment:
![Screenshot 2024-07-05 at 22 45 52](https://github.com/flutter/flutter/assets/6718144/8b130e68-e479-4e8b-9a2e-1f8f8ea0a9fe)

</details>

### Logs

<details open><summary>Logs</summary>

Logs are irrelevant

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64,
    locale en-REDACTED)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version REDACTED)
[✓] VS Code (version REDACTED)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by renancaraujo** [comment]
This was also observed when running with impeller on:
- ios 18 simulator device
- ios 17.5 real device

**Comment by renancaraujo** [comment]
In the main and beta channels it is even worse, all the other quadrants disappear:

![Screenshot 2024-07-05 at 22 57 29](https://github.com/flutter/flutter/assets/6718144/ca84ac09-9dc6-42dd-95e4-6aaf6895e9b6)

**Comment by jonahwilliams** [comment]
Not sure about the beta/master channel bug, but that should be easy to bisect. As far as the gap goes, what is suspect is happening is that we're not being consistent with rounding when applying the dpr

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/blob/main/impeller/aiks/canvas.cc#L999

I think the problem is going to be here: we need to absorb the transform and account for the round out that needs to happen for the render to texture

**Comment by renancaraujo** [comment]
We dont have the 1pixel gap anymore, thank you so much!

**Comment by renancaraujo** [comment]
> In the main and beta channels it is even worse, all the other quadrants disappear:
> 
> ![Screenshot 2024-07-05 at 22 57 29](https://private-user-images.githubusercontent.com/6718144/346230684-ca84ac09-9dc6-42dd-95e4-6aaf6895e9b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjY1MDgsIm5iZiI6MTcyMDU2NjIwOCwicGF0aCI6Ii82NzE4MTQ0LzM0NjIzMDY4NC1jYTg0YWMwOS05ZGM2LTQyZGQtOTVlNC02YWFmNjg5NWU5YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMjMwMzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg2ZTc4ZTJjNzdmZmEwZjlmNjJmOWZkMWQwYzU3MjY0YzAyNWE3NmNiZTMwNzJjMmYzNmY2ZjE4MzQwNTg2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UxXMDASTywQ_eOMLb4ibOAGZ3pK7MNX59n4tdi2fi04)


This one can be worked around by resetting uniforms on every shader call, or using multiple shader instances
