### ISSUE TITLE
Widgets suddenly stopped responding to touch input, except app bar back button

### ISSUE THREAD

**Issue by nsreenath** [flutter/flutter#15131]
While going through Flutter Gallery app in Android, I found that the touch stopped working on a screen for some time, as shown in the GIF video below. The back button on the app bar worked, and when the same screen is relaunched, the issue is gone. The phone is Moto G4 Plus running Android 7.0. Not sure if it phone issue or app issue or Flutter's issue. The app bar back button worked, so I am confused. Check the GIF video below: Note that the issue was there even before I started screen video recording.

![touch not working for sometime](https://user-images.githubusercontent.com/3154529/36946665-17eccd8e-1fe6-11e8-9938-a916c999428c.gif)

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by pratikg-cuelogic** [comment]
I am facing the same problem. Suddenly the app stops working - Nothing is happing on touch events. Don't have logs as of now. We will share it soon.

**Comment by TahaTesser** [comment]
Hi @nsreenath 
This issue isn't reproducible using  https://github.com/flutter/gallery 

If you're still experiencing this problem on new gallery, please create a new issue and provide the information
required in the template.
Thank you
