### ISSUE TITLE
[camera_avfoundation] AVAssetWriter::startWriting should not be called inside didOutputSampleBuffer

### ISSUE THREAD

**Issue by misos1** [flutter/flutter#151319]
### Steps to reproduce

1. run code sample
2. record some motion
3. stop recording
4. observe big lag at beginning

Video player here is used only to show the resulting video.

### Expected results

No big lag at the beginning.

### Actual results

Big lag at beginning of video. `AVAssetWriter::startWriting` can take a considerable amount of time to execute, like even 300 ms on a tested device. When first frame arrives `startWriting` is called in `didOutputSampleBuffer` and during those 300 ms are skipped some upcoming frames then after it finally writes the first frame and `didOutputSampleBuffer` returns can arrive more frames and video continues, this causes that big lag at beginning of video. In the attached video is shown the recorded video in loop and it plays 3x. This big lag completely disappears when `startWriting` is moved into `startVideoRecordingWithCompletion` for example.

### Code sample

<details open><summary>Code sample</summary>

```dart
import "dart:io";
import "package:flutter/material.dart";
import "package:camera/camera.dart";
import "package:video_player/video_player.dart";

void main()
{
	runApp(const MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatefulWidget
{
	const MyHomePage({super.key});
	@override State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
{
	bool loading = true;
	bool recording = false;
	late CameraController camera_cont;
	String? file;

	@override void initState()
	{
		super.initState();
		init_camera();
	}

	init_camera() async
	{
		final cameras = await availableCameras();
		camera_cont = CameraController(cameras.firstWhere((camera) => camera.lensDirection == CameraLensDirection.back), ResolutionPreset.ultraHigh, enableAudio: false);
		await camera_cont.initialize();
		setState(() => loading = false);
		await camera_cont.prepareForVideoRecording();
	}

	void record() async
	{
		await camera_cont.startVideoRecording();
		setState(() => recording = true);
	}

	void stop() async
	{
		final f = await camera_cont.stopVideoRecording();
		setState(() => file = f.path);
	}

	@override Widget build(BuildContext context)
	{
		if(loading)return const Center(child: CircularProgressIndicator());
		if(file != null)return VideoPlayer(VideoPlayerController.file(File(file!))..initialize()..setLooping(true)..play());
		return Stack(
			alignment: Alignment.bottomLeft,
			children: [
				Stack(
					alignment: Alignment.bottomCenter,
					children: [
						CameraPreview(camera_cont),
						if(recording)FilledButton(onPressed: stop, child: const Text("Stop"))
						else FilledButton(onPressed: record, child: const Text("Record")),
					],
				),
			],
		);
	}
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/30872003/947f160d-6ae7-4e16-9913-bf35fd2624e3

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64)
```

</details>

**Comment by huycozy** [comment]
Hi @misos1, I tried this on my end but couldn't see the lag as your demo. I see an issue at https://github.com/flutter/flutter/issues/90600 that seems to be similar, can you check and confirm?

**Comment by misos1** [comment]
@huycozy Tested device was iphone 7 plus, it may be smaller and less noticeable on newer devices, also if you run it in release it may be less noticeable, on my device it is smaller than 300 ms in release but still enough to drop few frames which can be seen especially well on movement like in attached video, can you try in debug if you did not to have it more pronounced (and also post your video)? #90600 looks like combination of this and #57831 although it was "reduced" to just duplicate of #57831 in comments and although this and #90600 may be similar we do not know whether they have the same or different cause, and if it is the same then this issue explains why the problem happens.

**Comment by huycozy** [comment]
I see. Here is the recorded video on my iPhone 7 device running in debug mode (also on Flutter 3.22.2 and camera_avfoundation: 0.9.16). It's more obvious when comparing with device camera. In the first frame of video recorded by Flutter, it seems to be stalled.

<details>
<summary>Demo video (device camera and Flutter camera)</summary>

| Flutter camera | Device camera |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/af5e7981-60e5-4e3a-bfbc-fa0fee0e1e67"/> | <video src="https://github.com/flutter/flutter/assets/104349824/5799bf88-24b9-4513-ae87-0c1237ce2a00"/>

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>
