### ISSUE TITLE
flutter start with ios simulator pauses for a long time

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1513]
The good news: my flutter app was deployed onto my simulator! :)

However, the tool was paused for a long time, without a spinner or other UI indication that something was happening. I almost Control-C killed it.

```
~/flutter/testme $ flutter start
Downloading darwin-x64 artifacts from the cloud, one moment please...
Downloading android-arm artifacts from the cloud, one moment please...
Downloading https://storage.googleapis.com/mojo_infra/flutter/7bce54b79ef9ee57999cc8e258d664a88723d56d/darwin-x64/artifacts.zip.
Downloading https://storage.googleapis.com/mojo_infra/flutter/7bce54b79ef9ee57999cc8e258d664a88723d56d/android-arm/artifacts.zip.
Starting lib/main.dart on iPhone 6s...
#### <=== right here, the tool just sat doing nothing for 10-12 seconds
io.flutter.runner.Runner: 46136
```

Could we display a "I'm doing something, chill out" spinner here? I've seen other console apps do `- / | \ -` animation, signaling "something is happening".

Thanks!

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/dev/update_packages.dart takes a "print what I'm doing; print how long it took" pattern to get around this.  Perhaps something similar we could follow with slow actions in the flutter tool?

**Comment by eseidelGoogle** [comment]
Is this still an issue @tvolkert or should we close?

**Comment by chinmaygarde** [comment]
iOS simulator pause times should be extremely short now. There is no precomp step.
