### ISSUE TITLE
Add support for inverting a CircularNotchedRectangle to be drawn on the bottom of a path

### ISSUE THREAD

**Issue by arbaker2** [flutter/flutter#151381]
### Use case

Currently the CircluarNotchedRectangle class only supports drawing a circular notch on the top of a path, mainly for use in a BottomAppBar. This is a nice design feature and adding support for drawing this notch on the bottom of the path would allow for its use in more situations with more widgets.

### Proposal

My proposal would be to allow for an optional argument in order to invert the CircularNotchedRectangle when calling the [getOuterPath] method on the object.

```
const CircularNotchedRectangle shape = CircularNotchedRectangle();
const Rect host = Rect.fromLTRB(0.0, 100.0, 300.0, 300.0);
const Rect guest = Rect.fromLTRB(190.0, 295.0, 210.0, 315.0);

final Path path = shape.getOuterPath(host, guest, inverted: true);
```

This would allow the [getOutterPath] method to keep the same default behavior while also allowing the notch to be drawn inverted as shown in the screenshot below.

![Simulator Screenshot - iPhone 15 - 2024-07-07 at 11 46 12](https://github.com/flutter/flutter/assets/71237742/cac3fbb6-9e54-4122-81c2-5d6a595acab7)

**Comment by huycozy** [comment]
Thanks for your proposal. But there is already one similar issue for this at https://github.com/flutter/flutter/issues/49973. Since that issue got more attention I will close this in favor of that one. Please also link your PR to that issue.
