### ISSUE TITLE
I am createing GNav() widget that moves between screens and it shows me this error 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5207 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true. and this my code

### ISSUE THREAD

**Issue by MohammedRedha126** [flutter/flutter#151379]
### Steps to reproduce

the error masseg tells me that the error is scaffold()
this is my code :
import 'package:flutter/material.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/favorite.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/home_screen.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/more_options.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/search.dart';
import 'package:google_nav_bar/google_nav_bar.dart';

class BottomNavBarScreen extends StatefulWidget {
  const BottomNavBarScreen({super.key});

  @override
  State<BottomNavBarScreen> createState() {
    return _BottomNavBarScreenState();
  }
}

class _BottomNavBarScreenState extends State<BottomNavBarScreen> {
  int _screenIndex = 0;
  static const List<Widget> _screens = <Widget>[
    HomeScreen(),
    Search(),
    Favorite(),
    MoreOptions(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
          body: _screens.elementAt(_screenIndex),
        
      
      bottomNavigationBar: Center(
        child: GNav(
          tabs: const [
                GButton(icon: Icons.home, text:'Home'),
                GButton(icon: Icons.search, text:'Search'),
                GButton(icon: Icons.favorite, text:'Favorite'),
                GButton(icon: Icons.more_horiz, text:'More Option'),
          ],
          selectedIndex: _screenIndex,
          onTabChange: (index){
            setState(() {
              _screenIndex = index;
            });
          },
        ),
      ),
    );
  }
}

### Expected results

my code should navigate throw diffrint widgets from the navigation bar

### Actual results

this is the error message

'package:flutter/src/widgets/framework.dart': Failed assertion: line 5207 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    Scaffold Scaffold:file:///C:/Users/User/Desktop/flutterProject/go_gas/lib/Screens/Bottom%20Navigation%20Bar/bottom_nav_bar.dart:28:12
    
    Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5207 pos 16: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was:

### Code sample

<details open><summary>Code sample</summary>

import 'package:flutter/material.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/favorite.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/home_screen.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/more_options.dart';
import 'package:go_gas/Screens/Bottom%20Navigation%20Bar/search.dart';
import 'package:google_nav_bar/google_nav_bar.dart';

class BottomNavBarScreen extends StatefulWidget {
  const BottomNavBarScreen({super.key});

  @override
  State<BottomNavBarScreen> createState() {
    return _BottomNavBarScreenState();
  }
}

class _BottomNavBarScreenState extends State<BottomNavBarScreen> {
  int _screenIndex = 0;
  static const List<Widget> _screens = <Widget>[
    HomeScreen(),
    Search(),
    Favorite(),
    MoreOptions(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
          body: _screens.elementAt(_screenIndex),
        
      
      bottomNavigationBar: Center(
        child: GNav(
          tabs: const [
                GButton(icon: Icons.home, text:'Home'),
                GButton(icon: Icons.search, text:'Search'),
                GButton(icon: Icons.favorite, text:'Favorite'),
                GButton(icon: Icons.more_horiz, text:'More Option'),
          ],
          selectedIndex: _screenIndex,
          onTabChange: (index){
            setState(() {
              _screenIndex = index;
            });
          },
        ),
      ),
    );
  }
}

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[![image](https://github.com/flutter/flutter/assets/15
![image](https://github.com/flutter/flutter/assets/152763896/dcb21a2d-c6e6-4e23-b9ee-485be8c4e95e)
![Screenshot_3](https://github.com/flutter/flutter/assets/152763896/7c0c1446-e8a0-4e50-aeb3-eadc7ca08972)
![Screenshot_1](https://github.com/flutter/flutter/assets/152763896/e471e535-f596-4dc8-a399-dc281335551b)
2763896/447cfdde-d2eb-493a-9073-bef2aa596f0f)]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
![image](https://github.com/flutter/flutter/assets/152763896/1bd1f1de-9b1c-40c7-b464-023d55dcedae)

```

</details>

**Comment by iapicca** [comment]
maybe try without [google_nav_bar](https://pub.dev/packages/google_nav_bar)
or open an issue [here](https://github.com/sooxt98/google_nav_bar/issues)

**Comment by danagbemava-nc** [comment]
This is likely an issue with your code. You may be referencing your `BottomNavBarScreen` incorrectly. 

Given the lack of a fully runnable code sample and the fact that this could also be an issue with the third-party package you're using, I'll be closing this issue. 

Please file a new issue and provide a complete runnable code sample without any third-party packages so that it can be properly investigated. 

Thank you
