### ISSUE TITLE
Flutter requires Android/Adb even if the project doesn't require it

### ISSUE THREAD

**Issue by cdprete** [flutter/flutter#151339]
### Steps to reproduce

Hello.
I'm trying to write an application in Flutter for Web and Windows, but I can't get any "device" (browsers or Windows itself) attached to it.

`flutter doctor` complains about `adb` and indeed I can't install the Android SDK on my company laptop.
Is there a way to work without it?

### Expected results

Flutter should work even if the Android SDK is not installed if the project doesn't build for Android.

### Actual results

See the flutter doctor output.

### Code sample

<details open><summary>Code sample</summary>

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4529], locale en-CH)
    • Flutter version 3.22.2 on channel stable at C:\Develop\Programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\tk35c\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:/Develop/Programs/Zulu/zulu-21\bin\java
    • Java version OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019
    • Visual Studio Enterprise 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Develop\Programs\ideaIU-2023.1.4.win
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at C:\Develop\Programs\ideaIU-2024.1.1.win
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17502

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: C:\Users\tk35c\AppData\Local\Android\Sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:547:36)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
      <asynchronous suspension>
      #4      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:217:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:741:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:618:5)
      <asynchronous suspension>


[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by cdprete** [comment]
I managed to make it work with `flutter config --android-sdk "<path-to-your-android-sdk-path>"` and moving the Android SDK in a folder where we have execute rights.

**Comment by danagbemava-nc** [comment]
Hi @cdprete, if you enter the `flutter devices` command, what do you see? 

>  but I can't get any "device" (browsers or Windows itself) attached to it.

I'm not sure I follow, do you get any errors when you try to run on either of these platforms? Can you share them if so?

**Comment by cdprete** [comment]
> Hi @cdprete, if you enter the `flutter devices` command, what do you see?
> 
> > but I can't get any "device" (browsers or Windows itself) attached to it.
> 
> I'm not sure I follow, do you get any errors when you try to run on either of these platforms? Can you share them if so?

Hi.
I'll have to revert https://github.com/flutter/flutter/issues/151339#issuecomment-2210596494 to test it and provide the output.

With
> I can't get any "device" (browsers or Windows itself) attached to it.

I was meaning the dropdown showing the connected devices in IntelliJ (with the Flutter plugin installed, of course).
Moreover, without the fix reported above, on every startup IntelliJ was as well showing a warning saying something like "The adb daemon terminated" (the same in https://github.com/flutter/flutter/issues/126727 basically).
In general, I think Flutter should not need adb when Android is not a target.

**Comment by danagbemava-nc** [comment]
> I was meaning the dropdown showing the connected devices in IntelliJ (with the Flutter plugin installed, of course).

What version of intellij are you using and are you using the latest version of the flutter intellij plugin? 

> In general, I think Flutter should not need adb when Android is not a target.

The flutter doctor output is independent of what the targets of the project is. It just checks if you have the configuration required to run on all supported platforms, if needed.

**Comment by cdprete** [comment]
> What version of intellij are you using and are you using the latest version of the flutter intellij plugin?
I'm using IDEA Ultimate 2024.1.1 241.15989.150 with the latest version of the Flutter plugin.

> The flutter doctor output is independent of what the targets of the project is. It just checks if you have the configuration required to run on all supported platforms, if needed.
I was not referring only to the output of `flutter doctor`. More in general, it looks to me that Flutter itself needs to be able to run `adb` to create the devices where to run the code, even if Android is not a target to begin with.

**Comment by danagbemava-nc** [comment]
> I was not referring only to the output of flutter doctor. More in general, it looks to me that Flutter itself needs to be able to run adb to create the devices where to run the code, even if Android is not a target to begin with.

Hi @cdprete, it appears that the devices output is also independent of the project configuration. 
This is from the output of `flutter help`. 

>   devices           List all connected devices.

**Comment by cdprete** [comment]
>  This is from the output of `flutter help`.
> 
> > devices           List all connected devices.

What should this answer mean? I won't be expecting that `flutter help` would be leaking internals by saying that `adb` is run to list the available devices. :D

**Comment by cdprete** [comment]
Hi @danagbemava-nc.

Although https://github.com/flutter/flutter/issues/72101 looks similar, my point here is:

1. it doesn't work even when present in the default location if there are some permission constraints
2. it should not be needed in the first place if we're not targeting Android

**Comment by danagbemava-nc** [comment]
Hi @cdprete, I'm not sure how the IDE plugins handle display the available devices. From what I know, that is dependent on the plugins themselves. 

Could you try with vscode to see if you got the same issue? 

Did you get the correct devices when you run flutter run?

**Comment by cdprete** [comment]
Hi @danagbemava-nc 

> I'm not sure how the IDE plugins handle display the available devices. From what I know, that is dependent on the plugins themselves

I've to assume so, because once I've fixed the issue with the path/permissions as described in the previous comments, that part started to work as well as expected.

> Could you try with vscode to see if you got the same issue?

I don't see why I should. The issue I've is with IntelliJ IDEA and I don't use VSCode to develop (I don't even know if my company supports it in the software center so that I could install it).

> Did you get the correct devices when you run flutter run?

I didn't try to run the application directly over the CLI, to be honest, so I can't answer to this right now.

**Comment by danagbemava-nc** [comment]
> The issue I've is with IntelliJ IDEA and I don't use VSCode to develop (I don't even know if my company supports it in the software center so that I could install it).

If the issue is specific to intellij IDEA then it will have to be moved to a different tracker because it is managed to a different team but if it is not, then that means there's something in the flutter tooling itself that will need to be fixed

**Comment by cdprete** [comment]
> > The issue I've is with IntelliJ IDEA and I don't use VSCode to develop (I don't even know if my company supports it in the software center so that I could install it).
> 
> If the issue is specific to intellij IDEA then it will have to be moved to a different tracker because it is managed to a different team but if it is not, then that means there's something in the flutter tooling itself that will need to be fixed

Fair enough. I'll check in my company software repository VS Code is available and, if it's so, I'll give it a try.
