### ISSUE TITLE
Please provide API for fetching Google Maps key from AndroidManifest.xml / AppDelegate

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#151392]
### Use case

To use the `GoogleMap` widget in Flutter, you have to specify the Google Maps key in `AndroidManifest.xml` on Android, or the `AppDelegate` on iOS:

https://pub.dev/packages/google_maps_flutter

However, if you also want to use other APIs, such as the Google Places API or the Timezone API, there is no way (that I know of) to fetch that API key in Dart code -- therefore, you have to include your API key in your Dart source too (this is the third place you need to include the key), so that you can provide the key to the other Maps APIs that you need to use.

This violates DRY (Don't Repeat Yourself). The key should only have to be specified in one place.

### Proposal

Actually, I would prefer for the API key to be specified in Dart, and passed in to the native libraries as necessary. That will mean that you don't have to mess with Android or iOS files at all, you can just work in pure Dart -- and again, it would reduce the additional duplication of having to specify the key once for Android and once for Dart.

However, since I expect that that change won't happen, I propose adding an API to the `google_maps_flutter` library to fetch the key from the Android or iOS native configuration. That way the key can be fetched and passed in to additional APIs as necessary, without specifying it an additional time in Dart.

**Comment by darshankawar** [comment]
@lukehutch There's already a similar open [proposal](https://github.com/flutter/flutter/issues/51433) describing your case. 
Please follow-up in it for further updates. Closing this as a duplicate.
