### ISSUE TITLE
Virustotal reporting malware in precompiled dart-sdk

### ISSUE THREAD

**Issue by jj-tarun** [flutter/flutter#151330]
Hi, 

I recently downloaded the flutter-sdk

and I am seeing the following on scanning at virustotal.com for the file: flutter/bin/cache/dart-sdk/bin/dart

Kingsoft: Script.Ks.Malware.19237

**Comment by danagbemava-nc** [comment]
This is likely a false positive can you share the results of the scan and what exactly you submitted to virustotal for the scan?

**Comment by jj-tarun** [comment]
Here is the report: https://www.virustotal.com/gui/file/9bf1ce077567dc52769a3cea1711dd444e034bda2c348b47b1ca6cbdc581849b/detection

I don't have knowledge on security. As I observed it, I preferred to report it.

**Comment by azkadev** [comment]
Flutter was developed by Google, Google, a large technology company, it is impossible to create a virus.

BTW, as long as I've been using Flutter on my computer, I've never lost data/had an error/hack like that

**Comment by danagbemava-nc** [comment]
Hi @jj-tarun, what file did you submit to virus total?

**Comment by jj-tarun** [comment]
Hi @danagbemava-nc 
Here is the file details:
flutter/bin/cache/dart-sdk/bin/dart

**Comment by iapicca** [comment]
<img width="786" alt="Screenshot 2024-07-08 at 17 22 11" src="https://github.com/flutter/flutter/assets/45637986/176ae8e7-5f63-42ea-a892-c683210ee53b">
<img width="774" alt="Screenshot 2024-07-08 at 17 22 03" src="https://github.com/flutter/flutter/assets/45637986/3436e1a6-ae7a-4337-b36b-cd5b2fe094d7">

I tried their [website](https://www.virustotal.com/gui/home/upload), seems like dart is flagged by [Kingsoft](https://en.wikipedia.org/wiki/Kingsoft) as malware

**Comment by danagbemava-nc** [comment]
Hi @jj-tarun, please report this to virustotal, it is likely this hasn't been reported to kingsoft yet. All other vendors that can scan the file do not report any malware in the exe, this likely means they haven't been informed of this yet. 

Also, which version of the flutter sdk did you download?

**Comment by jj-tarun** [comment]
I downloaded 3.22.2.
I didn't find a platform to report it.

**Comment by darshankawar** [comment]
@jj-tarun 
You will need to report this in anti-virus vendor. 
https://github.com/VirusTotal

Closing from here.
