### ISSUE TITLE
TextField Cursor position moved incorrectly 

### ISSUE THREAD

**Issue by feimenggo** [flutter/flutter#151337]
### Steps to reproduce

1. Execute flutter run on the code sample.
2. Enter a blank character.
3. Press the right arrow key at the end.

### Expected results

The cursor position is shown at the end.

### Actual results

The cursor will move to the left.

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final controller = TextEditingController(text: '　');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(controller: controller),
          ],
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/12608693/3e7350f8-2732-4406-bda2-625891812908

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by darshankawar** [comment]
@feimenggo What input language are you using ?


> The cursor position is shown at the end.
> 
> ### Actual results
> The cursor will move to the left.

I didn't complete understand what exactly is the current behavior and expected. Can you elaborate ?
Also, is this only occuring in desktop ? or in web and mobile as well ?

**Comment by darshankawar** [comment]
I tried the code sample in Android emulator with latest master version and see below:


https://github.com/flutter/flutter/assets/67046386/a8cb7685-53a8-49f2-b36c-700e5c54f558

The cursor seems to move properly with right and left arrow key.

**Comment by darshankawar** [comment]
Thanks for the update. Since it works properly in master, I will close this as fixed. New stable release will most probably have the fix that you can watch out for.
