### ISSUE TITLE
Creating a custom renderer

### ISSUE THREAD

**Issue by jordyvandomselaar** [flutter/flutter#15133]
I'd like to try and create my own renderer for different platforms as to support more platforms. Could anyone guide me as to where to start? I imagine Flutter builds some kind of component tree, can I use that to render my own stuff?

**Comment by Hixie** [comment]
I'm not really sure what you're asking. If you're asking how to port the Flutter engine to other platforms, please see https://github.com/flutter/engine/wiki/Custom-Flutter-Engine-Embedders.
