### ISSUE TITLE
【xcode15 ios】Undefined symbols for architecture arm64 Symbol

### ISSUE THREAD

**Issue by ArthurHsing** [flutter/flutter#151304]
### Steps to reproduce

1. This is an old project, and the dependencies may not have been updated for about 3 years. My **flutter version is 2.10**, and I **can compile the project normally in the xcode14 environment**. But the Apple App Store now requires that it must be compiled in the xcode15 environment before it can be put on the app store.
2. After **I switched to the xcode15 environment**, I modified `platform :ios, '12.0'` in the podfile, and then set `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'` in the post install hook to meet the minimum compilation version requirement.
3. Then, in order to deal with the error of **duplicate symbols**, I set `OTHER_LDFLAGS="$(inherited) -ld_classic -ObjC"`.
Then a new problem appeared.
<img width="1511" alt="image" src="https://github.com/flutter/flutter/assets/42834985/e68ab62d-7e34-4001-aeef-8bc17a18aaf4">

I learned that **GeneratedPluginRegistrant** is a file automatically generated by flutter for registering plugins, and **AutoorientationPlugin is a class in the dependencies I installed**. At first I thought it was a problem with the auto_orientation plugin (version 2.0.2), so I deleted auto_orientation, and then the second plugin registered in **GeneratedPluginRegistrant** had a problem again, that is, the class symbol of the second plugin could not be found.

### Actual results

The compilation fails, and then when linking, a symbol cannot be found in the GeneratedPluginRegistrant file.

I am not very familiar with flutter and ios development, and I want to know what the problem is.

### Logs

<details open>
<summary>Logs</summary>

```console

▸ Compiling FlutterPreview.m
▸ Compiling FLTPreviewFlutterPlugin.m
▸ Compiling AppDelegate.m
▸ Linking Runner
⚠️  ld: object file (/Volumes/data/workspace/ProjectName/build/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProducts
Path/Release-iphoneos/libPods-Runner.a(Pods-Runner-dummy.o)) was built for newer iOS version (12.0) than being linked (9.0)
⚠️  ld: Could not find or use auto-linked framework 'CoreAudioTypes'
❌  Undefined symbols for architecture arm64
> Symbol: _OBJC_CLASS_$_AutoOrientationPlugin
> Referenced from: objc-class-ref in GeneratedPluginRegistrant-763e1c85ddd7b72ffdc8ccee0b1796ac.o
❌  ld: symbol(s) not found for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 2.10.5, on macOS 13.6.6 22G630 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/xxx/fvm/versions/2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 years, 3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 31.0.0
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Users/xxx/Library/Java/JavaVirtualMachines/corretto-11.0.23/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-11.0.23.9.1 (build 11.0.23+9-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 126.0.6478.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available


```

</details>

**Comment by darshankawar** [comment]
@ArthurHsing 
It may be specific to Xcode 15 version you are using. The error is pointing to framework `CoreAudioTypes`.
Check if https://github.com/stripe/stripe-react-native/issues/1532#issuecomment-1962207723 helps in your case or not.

**Comment by ArthurHsing** [comment]
> @ArthurHsing It may be specific to Xcode 15 version you are using. The error is pointing to framework `CoreAudioTypes`. Check if [stripe/stripe-react-native#1532 (comment)](https://github.com/stripe/stripe-react-native/issues/1532#issuecomment-1962207723) helps in your case or not.

That's just a warning, I think it could be ignored. 

Is this related to the flutter version, or the version of the dependency? Is it that the auto_orientation2.0.2 version does not support arm64?

**Comment by BenjiFarquhar** [comment]
I have this error after updating google_maps_flutter

**Comment by darshankawar** [comment]
> Is it that the auto_orientation2.0.2 version does not support arm64?

It is third party package, so you will need to check that with plugin's owner. Also, since you are on very old stable version and using latest xcode, there may be conflicts with the config as well. So I suggest you to upgrade to latest stable, upgrade all your plugins to latest and re-run to see if you see get same behavior or not. Another option is to remove external dependencies one by one and check which one could be causing it and then you will probably need to report it in dedicated repo.

**Comment by ArthurHsing** [comment]
https://stackoverflow.com/questions/77139621/xcode-15-undefined-symbols-linker-command-failed-with-exit-code-1-use-v-to-s
This method solved it. The reason why it didn't work before was because I added other linker flags settings in the 'xcodebuild archive' build command, which then overwrote my settings in Xcode.
