### ISSUE TITLE
iOS pickImage from camera returning null instead of file  path url.

### ISSUE THREAD

**Issue by sspogra** [flutter/flutter#151334]
### Steps to reproduce

Capture the image from camera and before capture increase the brightness of camera.

### Expected results

Image should be captured and return file path url.

### Actual results

Image captured but file path url is null

### Code sample

static final _imagePicker = ImagePicker();

 var file = await _imagePicker.pickImage(source: ImageSource.camera);
 var path = file.path

### Screenshots or Video

<img width="400" alt="image" src="https://github.com/flutter/flutter/assets/49437548/e9018e48-101f-4e2f-bb0a-264dbb2b5723">

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @sspogra, what iPhone device are you using and what version of iOS is it running? 

What version of `image_picker` & `image_picker_ios` are you using? 

Does this only happen when you increase the brightness? 

I tested with the plugin example app and even after increasing the brightness, the file path was correctly returned.

**Comment by sspogra** [comment]
Hi @danagbemava-nc I am using iPhone 15 having iOS 17.5.1.
image_picker: ^1.1.2 , image_picker_ios 0.8.12

Yes it happened only when I increased the brightness of camera.

**Comment by danagbemava-nc** [comment]
Hi @sspogra, are you only seeing this on the iPhone 15? 

Do you also have this issue with the plugin example app?

**Comment by RohitSadioura** [comment]
Hi @danagbemava-nc  i am also facing this issue . plugin example is working correct .
