### ISSUE TITLE
XML tag for widget

### ISSUE THREAD

**Issue by andyyapwl** [flutter/flutter#151305]
### Use case

Currently flutter is the only framework that is using json-like for widget interface code structure which I find abit less user-friendly than xml e.g. react and html.

### Proposal

Would be a lot better if flutter also provide xml as alternative for widget ui code structure like those in react or html which is much more readable.

**Comment by danagbemava-nc** [comment]
This has come up several times before, a few of those instances are https://github.com/flutter/flutter/issues/15922 and 
https://github.com/flutter/flutter/issues/101063

See https://github.com/flutter/flutter/issues/11609#issuecomment-409440643 for why this is currently not in an acceptable state. I'll be closing this based on the comment shared. 

If you are able to provide the information required in maybe a design doc, please file a new issue and do so. 

Closing for now. 

Thank you
