### ISSUE TITLE
How to make an exception in the router for not saving state?

### ISSUE THREAD

**Issue by leonidtimo17** [flutter/flutter#151394]
I have a problem. The problem is that I cannot make an exception for one branch so that it does not save state. I use gorouter and did it via StatefulShellRoute.indexedStack. The page itself that I go to is the cart and it is in the nested navigation. Is there a way to throw an exception for not saving the state of a branch?

At first I tried to make it so that when the cart branch was indexed, it could be restarted via push, but this caused conflicts with other branches. Then I tried to update the state of the page inside the cart, but it also didn’t work out that way. The cart is not dynamically updated, since it takes data from the site's api and sends data to the api, and listening to and initializing it every time is too much of a load. It would be better if it restarted the page or did not save the branch state.

**Comment by huycozy** [comment]
>The problem is that I cannot make an exception for one branch so that it does not save state.

This looks similar to https://github.com/flutter/flutter/issues/142258. Closing this in favor of that one, please follow it for updates.

**Comment by leonidtimo17** [comment]
@huycozy When will they add the ability to reset branch state? To avoid making such crutches.

**Comment by huycozy** [comment]
>When will they add the ability to reset branch state?

It's another issue at https://github.com/flutter/flutter/issues/142867, please follow it as well.

**Comment by leonidtimo17** [comment]
Thank you!
