### ISSUE TITLE
BUG: Scrollbar always uses MediaQuery.paddingOf as padding

### ISSUE THREAD

**Issue by twinstar6980** [flutter/flutter#151343]
### Use case

Scrollbar uses MediaQuery.paddingOf as the padding of scrollbarPainter to avoid the influence of system ui overlay on the scrolling area.

However, this behavior is sometimes not what users expect. For example, my app has a content area and a BottomAppBar. There is a vertical scrolling area in the content area. At this time, the scrollbar should not add padding. As shown in the figure:

<img width="322" alt="a1" src="https://github.com/flutter/flutter/assets/37923060/febcffa5-cefc-474e-8da5-790b8bbe1765">

I modified the function `updateScrollbarPainter` in my local file `flutter/lib/src/material/scrollbar.dart`:

```dart
@override
void updateScrollbarPainter() {
scrollbarPainter
// ......
..minLength = _scrollbarTheme.minThumbLength ?? _kScrollbarMinLength
..padding = MediaQuery.paddingOf(context) // !!!! REMOVE THIS LINE !!!!
..scrollbarOrientation = widget.scrollbarOrientation
..ignorePointer = !enableGestures;
}
```

After the modification, the Scrollbar no longer automatically adds padding, which is what I expected.

<img width="322" alt="a2" src="https://github.com/flutter/flutter/assets/37923060/c038ae85-ffc3-456f-b120-9336a2633263">

But padding is required for the scrolling area that extends to the system ui overlay:

<img width="322" alt="b" src="https://github.com/flutter/flutter/assets/37923060/e9523913-1fb6-46b2-910c-d79eac1327f7">

### Proposal

Should a padding property be added to the Scrollbar to support user-defined padding (instead of always using MediaQuery.paddingOf as padding)?
I found a related [issue](https://github.com/flutter/flutter/issues/25524), but it is no longer active.

**Comment by moffatman** [comment]
Please put a code example reproducing the problem. The best practice here is to create a child MediaQuery with padding removed if you consume the padding. Rather than hacking around by removing/overriding padding in certain places.
