### ISSUE TITLE
ADB exited with exit code 1

### ISSUE THREAD

**Issue by androidq** [flutter/flutter#151336]
### Steps to reproduce

installing apk 

### Actual results

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on PJG110 in debug mode...
Running Gradle task 'assembleDebug'...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
√ Built build\app\outputs\flutter-apk\app-debug.apk
Installing build\app\outputs\flutter-apk\app-debug.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\Administrator\Desktop\project\flutter\fe_emi\emi\build\app\outputs\flutter-apk\app-debug.apk:
Error launching application on PJG110.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
Hi @androidq 
When opening an issue, please try to provide all information indicated in the template so that we can address the issue properly.

For this issue, please confirm and provide the following information:
- This could be a device's issue, you can check [this](https://stackoverflow.com/questions/72491506/performing-streamed-install-adb-failed-to-install-install-failed-insufficient) to see if it helps.
- Does this issue occur on a simple Flutter project? (counter app for example)
- The output of `flutter run -v`. The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it.
- The output of `flutter doctor -v`

**Comment by mainjzb** [comment]
> Does this issue occur on a simple Flutter project? (counter app for example)

yes, I create new flutter project get this error.

<details>

<summary>flutter doctor -v</summary>

```console

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22621.3880], locale en-US)
    • Flutter version 3.22.3 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (6 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\mainj\AppData\Local\Android\sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.7.0 Preview 1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Professional 2022 version 17.7.33711.374
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.91.1)
    • VS Code at C:\Users\mainj\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[✓] VS Code (version 1.92.0-insider)
    • VS Code at C:\Users\mainj\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)
    • RMX1931 (mobile)  • 7440f0e0 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.3880]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 126.0.6478.128
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 126.0.2592.113

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>
