### ISSUE TITLE
Issue from website page Flutter for React Native Developers

### ISSUE THREAD

**Issue by jaxondu** [flutter/flutter#15139]
There is no left padding/margin of page when view on Safari and Chrome on iOS.

**Comment by jordyvandomselaar** [comment]
This has nothing to do with react native as far as I can see?

**Comment by jaxondu** [comment]
The issue is logged via the "File Issue" link on the page https://flutter.io/flutter-for-react-native

When you view the page on mobile browser on iOS, also on Chrome Android, the left side of the page is being "cut off" slightly.

**Comment by jordyvandomselaar** [comment]
Ah, I mis interpreted the title, my apologies!
