### ISSUE TITLE
About 3DFBX format model presentation problem

### ISSUE THREAD

**Issue by dongminfei** [flutter/flutter#151329]
### Use case

There is no solution to display 3DFBX model in pub.dev/flutter. How can I display this FBX format 3D model?

### Proposal

Does Flutter plan to directly support 3DFBX rendering effects, and if so, when?

**Comment by darshankawar** [comment]
@dongminfei 
I found https://github.com/klaszlo8207/Flutter-FBX-3D-Viewer/tree/master?tab=readme-ov-file that you can check to see if it helps to solve your use case or not.


> Does Flutter plan to directly support 3DFBX rendering effects, and if so, when?

I don't think there will be out-of-box support by the framework. Not everything can be included in the framework hence there are community packages such as above. 

With no scope for such use case is likely feasible by framework, I'll close this. If you disagree, write in comments and I'll reopen it.
