### ISSUE TITLE
run flutter doctor to curl: (35) Server aborted the SSL handshake

### ISSUE THREAD

**Issue by DyncLang** [flutter/flutter#15145]
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:54 --:--:--     0
curl: (35) Server aborted the SSL handshake

**Comment by DanTup** [comment]
@DyncLang I believe there are some extra things you need to do for this to work in China, please check out this wiki page:

https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

Please let us know if it solves the issue.

**Comment by zoechi** [comment]
@DyncLang is this still an issue?
