### ISSUE TITLE
[integration_test] Enable assertions when running with `--wasm`

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#151426]
### Use case

Testing

### Proposal

Pass the flag to enable assertions when running `flutter drive --wasm`

Similar issue that was already resolved for the `test` package: https://github.com/dart-lang/test/issues/2240

**Comment by andrewkolos** [comment]
fyi @eyebrowsoffire

**Comment by Rexios80** [comment]
I see this line:

https://github.com/flutter/flutter/blob/8c17a747c979818ce79dbaeaa64880e3d6d4b025/packages/flutter_tools/lib/src/test/web_test_compiler.dart#L239

Is this not where web integration tests get compiled or is this flag just not working?

**Comment by eyebrowsoffire** [comment]
> I see this line:
> 
> https://github.com/flutter/flutter/blob/8c17a747c979818ce79dbaeaa64880e3d6d4b025/packages/flutter_tools/lib/src/test/web_test_compiler.dart#L239
> 
> Is this not where web integration tests get compiled or is this flag just not working?

To answer your question, `web_test_compiler.dart` is used only in `fluttter test`. `flutter drive` and `flutter run` go through a different code path.

**Comment by eyebrowsoffire** [comment]
Fixed with https://github.com/flutter/flutter/issues/148850

**Comment by kevmoo** [comment]
@Rexios80 – can you confirm this is fixed and close if you're happy?

**Comment by Rexios80** [comment]
This appears to be working with both `flutter run` and `flutter drive`
