### ISSUE TITLE
name = 'io.flutter.1.io', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by bemily-ys** [flutter/flutter#151451]
### Steps to reproduce

1. A crash occurs when calling the readAsBytesSync method of a heif file.

### Expected results

No Crash

### Actual results

The crash is happening randomly.

TestDevice : iPhone 11, iPhone12, iPhone 12 Pro Max

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
<img width="808" alt="스크린샷 2024-07-09 오후 1 46 42" src="https://github.com/flutter/flutter/assets/168389470/edd46144-d19b-4820-85c6-b290baa5d9f8">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Unknown process name] CGSImageDataLock: Cannot allocate memory
* thread #11, name = 'io.flutter.1.io', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010ac59c5c Flutter`SkData::PrivateNewWithCopy(void const*, unsigned long) + 56
Flutter`SkData::PrivateNewWithCopy:
->  0x10ac59c5c <+56>: str    w9, [x0], #0x28
    0x10ac59c60 <+60>: stp    xzr, xzr, [x8, #0x8]
    0x10ac59c64 <+64>: stp    x0, x19, [x8, #0x18]
    0x10ac59c68 <+68>: str    x8, [x21]
Target 0: (Runner) stopped.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale ko-KR)
    • Flutter version 3.22.2 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
```

</details>

**Comment by mraleph** [comment]
This is out of memory situation. `malloc` returned `NULL`. Your application is running out of memory, possibly due to leaks or not releasing memory timely.
