### ISSUE TITLE
Make `DragGestureRecognizer` abstract methods public

### ISSUE THREAD

**Issue by angelosilvestre** [flutter/flutter#151446]
### Use case

`DragGestureRecognizer` relies on abstract methods that `VerticalDragGestureRecognizer`, `HorizontalDragGestureRecognizer` and `PanGestureRecognizer` implement.

Such methods include `_considerFling`,  `_hasSufficientGlobalDistanceToAccept`, among others.

Since these methods are private, developers can't extend `DragGestureRecognizer` to create their own recognizers. For example, a developer might want to modify the distance required to accept the gesture. Currently, developers need to copy the whole `DragGestureRecognizer` to modify that.

### Proposal

Make the abstract methods public. Also, provide public getters to the private members that the subclasses access, like `_finalPosition` and `_globalDistanceMoved`.

**Comment by matthew-carroll** [comment]
To demonstrate value, here's what we had to do in `super_editor` to work around these private methods: https://github.com/superlistapp/super_editor/pull/2155
