### ISSUE TITLE
Get all childs and change

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#151407]
### Use case

It is not possible to access child widgets through the parent with `key` and `GlobalKey`.

### Proposal

I want to get and change child widgets with a `key` that I gave to a parent widget.

For example, suppose there is a text in the Container. I want to change the text by getting the widget through the Container.

Sample code (This is a Pseudocode of the feature that is needed):
```dart
GlobalKey parentKey=GlobalKey();

Container(
  key: parentKey,
  child: Column(
    children: [
      Text("Test"),
      TextButton(onPressed: () {}, child: Text("Click"))
    ],
  ),
);


(parentKey.getChild[0][0] as Text).data="Test 2";
```

**Comment by moffatman** [comment]
Not how flutter works

**Comment by mbfakourii** [comment]
> Not how flutter works, you are thinking imperatively. If you can rephrase your problem at a higher level, maybe I can suggest some way forward.
> 
> https://docs.flutter.dev/get-started/flutter-for/declarative

There must be a way to solve this issue. In some cases, injecting a new value is very necessary.

For example, let's assume that we have several widgets and a parent contains them, and we want to update some items of these child widgets with the parent's key.

**Comment by darshankawar** [comment]
@mbfakourii 
Are you trying to update all child widgets state on parent's setState ?
Maybe take a look at below links to see if they help in your case or not:

https://api.flutter.dev/flutter/widgets/Element/updateChildren.html
https://stackoverflow.com/questions/71433122/flutter-update-child-state-from-parent

**Comment by moffatman** [comment]
You should just rebuild the parent and return a new list of children

**Comment by moffatman** [comment]
Maybe a real code example will make it clearer. You really can't mutate the Widget tree as you are thinking. Need to present a new tree with each build.

**Comment by moffatman** [comment]
Since Flutter has actually three different trees. Widget/Element/RenderObject (https://www.youtube.com/watch?v=zmbmrw07qBc), mutating the tree imperatively makes no sense. In fact all Widgets are really supposed to be final/const classes. Where values never change. There isn't even `Text.data` to modify, it is read-only!

Instead I'm happy to help you solve the problem you have. Maybe the most helpful solution is that the Parent widget (with the GlobalKey) should rebuild itself with different children depending on the state. Not mutate the old children.

**Comment by mbfakourii** [comment]
> Instead I'm happy to help you solve the problem you have. Maybe the most helpful solution is that the Parent widget (with the GlobalKey) should rebuild itself with different children depending on the state. Not mutate the old children.

The issue here is that I don't know about parent's children! I have to have them to be able to change!

**Comment by darshankawar** [comment]
See if https://api.flutter.dev/flutter/widgets/ImplicitlyAnimatedWidgetState/didUpdateWidget.html would help. Also, not sure if you had chance to look at earlier links shared above. 

@moffatman I am short of ideas on how to further help in this issue.

**Comment by mbfakourii** [comment]
> See if https://api.flutter.dev/flutter/widgets/ImplicitlyAnimatedWidgetState/didUpdateWidget.html would help. Also, not sure if you had chance to look at earlier links shared above.

I checked this item and I don't think it will help the problem

**Comment by moffatman** [comment]
I should probably just close this issue. This feature will **never** be added. But I will keep answering to try to help you understand. 

Only the parent should have control over its children. Maybe it can give up a little of that control with public methods in the `State`. Again please provide a real example of where you are trying to do this, and I can help to understand the "Flutter way" of doing it.

**Comment by darshankawar** [comment]
Maybe continuing the discussion in discord would be better, as here, the issue will be open without any labels.

**Comment by moffatman** [comment]
Yes @mbfakourii please feel free we can discuss it in flutter discord
