### ISSUE TITLE
FutureBuilder.wait() - Wait for child's futures to complete

### ISSUE THREAD

**Issue by moshe5745** [flutter/flutter#151496]
### Use case

Skeleton in parent widget that waits for all widgets to load so it can hide the skeleton and show children widgets at once.

### Proposal

FutureBuilder that can wait for children to complete their futures.
```
FutureBuilder.wait(
   child: Column(
      children: [
         FirstChildWithFutuerBuilderInside(),
         SecondChildWithFutuerBuilderInside(),
         ...
         LastChildWithFutuerBuilderInside(),
      ])
)
```

Dev experience: Better widget encapsulation so we would not have to use state management for this.

**Comment by darshankawar** [comment]
@moshe5745 Can you check if your use case is similar / resembles https://github.com/flutter/flutter/issues/87399 or not ?

**Comment by moshe5745** [comment]
> @moshe5745 Can you check if your use case is similar / resembles #87399 or not ?

Actually, it does. I struggling with the same problem. I don't want to use STM package, maximum Provider when its really needed.

Futures are great. But it is messing the widgets. All the UI/Buisnes logic salat.
I am not loving his proposal. 

But I think the general issue is very very real. And if a good solution is introduced it will make a big impact on flutter.

**Comment by darshankawar** [comment]
Thanks for the update. I suggest you to follow-up in that issue for better tracking. You may share your findings / proposal in that issue. Will close this in favor of it. If you disagree, write in comments and I'll reopen to track separately.
