### ISSUE TITLE
[Impeller] Wire up support in OpenGL for KHR_blend_equation_advanced.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#151497]
[`KHR_blend_equation_advanced`](https://registry.khronos.org/OpenGL/extensions/KHR/KHR_blend_equation_advanced.txt), needed for fast advanced blends is available on more ([> 50%](https://opengles.gpuinfo.org/listextensions.php)) of devices per GPUInfo.

<img width="900" alt="Screenshot 2024-07-09 at 3 34 12 PM" src="https://github.com/flutter/flutter/assets/44085/d7f3b62e-dfad-4f78-81f9-83867cb08a32">

We already wire up support for [`GL_EXT_shader_framebuffer_fetch`](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_shader_framebuffer_fetch.txt) in OpenGL but support for that is lower at [~30%](https://opengles.gpuinfo.org/listextensions.php).

<img width="910" alt="Screenshot 2024-07-09 at 3 36 50 PM" src="https://github.com/flutter/flutter/assets/44085/e8d195fa-5a9c-4451-86cf-baba9ae475a6">

Importantly, Skia also wires it up. So Impeller doing that will match Skias level of support.

Forked from the umbrella issue for fast advanced blends via extensions as described in https://github.com/flutter/flutter/issues/120223.

**Comment by jonahwilliams** [comment]
IMO if we do this then we should do the Vulkan equivalent. Its theoretically faster too, since we don't need to do a render to texture.

**Comment by jonahwilliams** [comment]
Actually, the reason we can't easily do this is that it requires decorating shaders with metadata that isn't supported in the GLSL language version we target.

**Comment by jonahwilliams** [comment]
Closing for now, but unless we build a shader compiler pipeline for newer GL ES versions we cannot use this feature.
