### ISSUE TITLE
Engine to framework roll blocked on skwasm test failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#151473]
Starting with the roll attempt in https://github.com/flutter/flutter/pull/151434, the engine to framework roll is failing on skwasm tests.

That Engine to Framework roll contains the Dart to Engine roll https://dart.googlesource.com/sdk.git/+log/ffc8bb004a64..1679aba20a03, which appears to contain several possibly related commits from @osa1 and @mkustermann. cc @eyebrowsoffire

**Comment by jason-simmons** [comment]
Bisected this to https://dart.googlesource.com/sdk/+/dc2d5b539eb4f99f66a4257378e1ad6c81085956

@mkustermann

**Comment by goderbauer** [comment]
(triage) @bdero I assigned this to you since you seemed to be working on it.

**Comment by bdero** [comment]
The engine roll is unblocked after the revert, so this is all set.

Siva landed a couple of Dart reverts which will allow us to unblock the Dart roller.

**Comment by mkustermann** [comment]
Thanks for letting me know & reverting. I'll have a look at the root cause of this.

**Comment by mkustermann** [comment]
Just a heads up: I've identified the cause of the issue and therefore relanded the changes with a fix.
