### ISSUE TITLE
Migrate half of linux Moto G4 device lab bots to have Mokeys attached instead

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#151593]
The following devicelab bots currently have Moto G4's attached. The Moto G4's should be swapped out for Mokey devices.
* [ ] flutter-devicelab-linux-3
* [ ] flutter-devicelab-linux-4
* [ ] flutter-devicelab-linux-9
* [ ] flutter-devicelab-linux-10
* [ ] flutter-devicelab-linux-11
* [ ] flutter-devicelab-linux-13

Also, I see that `flutter-devicelab-linux-5` is currently quarantined. If it no longer needs to be quarantined, then it's Moto G4 can also be replaced with a mokey.

This is the next step of https://github.com/flutter/flutter/issues/148085.

cc @christopherfujino

**Comment by kentnguyen99** [comment]
@zanderso Swapping out old G4 and then replacing with Mokey phones have been completed.

**Comment by zanderso** [comment]
Thanks!
