### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY 

### ISSUE THREAD

**Issue by hoc081098** [flutter/flutter#15150]
I/flutter ( 9744): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9744): The following assertion was thrown building _ModalScopeStatus(active):
I/flutter ( 9744): type '() => void' is not a subtype of type '(dynamic) => dynamic' of 'f'

**Comment by Hixie** [comment]
Without more information there's not much we can do with this bug report, I'm afraid.
Please don't hesitate to file a new bug if you can provide us with detailed information, such as the code that caused the error and a full log.

**Comment by zoechi** [comment]
@lichentao that looks like your Tab widget is calling `length` on what it expects to be a list or string but is `null`.
