### ISSUE TITLE
Splash screen do some task before going to application for Android

### ISSUE THREAD

**Issue by geetves** [flutter/flutter#15151]
Hi, I am learning to use flutter. I have one query. I have to load my local sqlite database from assets folder to the device folder. So, I want to perform this task during the first time app installs in the splash screen. Is there any way I can do this?

Thanks,

**Comment by Hixie** [comment]
You can do whatever you want in the `main` method of your application. The splash screen will stay up until you call `runApp`. Is there somewhere we should document this to make it more obvious?

**Comment by zoechi** [comment]
Seems to be solved by @Hixie's comment above
