### ISSUE TITLE
mac-10 and mac-23 devicelab error: "iPhone 11 is not available because it is unpaired Pair with the device in the Xcode Devices Window, and respond to any pairing prompts on the device."

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#151592]
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios%20platform_views_scroll_perf_bottom_ad_banner__timeline_summary/76/infra

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8742729113299342273/+/u/Prepare_iOS_device/Dismiss_iOS_dialogs/Run_app_to_dismiss_dialogs/stdout

```
 	Ineligible destinations for the "infra-dialog" scheme:
 		{ platform:iOS, arch:arm64e, id:00008030-000E4C9E226B402E, name:iPhone 11, error:iPhone 11 is not available because it is unpaired Pair with the device in the Xcode Devices Window, and respond to any pairing prompts on the device. }
```
@kentnguyen99 can you take a look?

**Comment by jmagman** [comment]
[mac-23](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-23) is hitting the same:
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios%20platform_views_scroll_perf_bottom_ad_banner__timeline_summary/2/infra

**Comment by kentnguyen99** [comment]
@jmagman Can you give another try?  It should be working now.

**Comment by jmagman** [comment]
@kentnguyen99 also seeing on mac-26, could you check that one as well?

**Comment by kentnguyen99** [comment]
mac-26 is good now. Can you check again from your end?

**Comment by jmagman** [comment]
I see mac-10 again? 
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios%20platform_views_scroll_perf_bottom_ad_banner__timeline_summary/92/infra

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8742678619901646033/+/u/Prepare_iOS_device/Dismiss_iOS_dialogs/Run_app_to_dismiss_dialogs/stdout

**Comment by kentnguyen99** [comment]
Mac-10's phone is back online, it needs to hit "Trust" on the phone.

**Comment by jmagman** [comment]
Thank you!
