### ISSUE TITLE
[3.22.2][stable] Current included Dart SDK breaks pub.dev proxying due to security advisories

### ISSUE THREAD

**Issue by thomas-stockx** [flutter/flutter#151583]
Hi,

The current stable Flutter version includes Dart 3.4.3, which currently breaks artifactory proxying.
As such, we are unable to update from Flutter 3.19.x to 3.22.x as `flutter pub` is broken due as we use an artifact proxy.

```
Building flutter tool...
Resolving dependencies...
Downloading packages...
HTTP error 404 Not Found
package:pub/src/http.dart 412:7                                 Throwing.throwIfNotOk
package:pub/src/http.dart 434:16                                RequestSending.fetch
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 580:28                       HostedSource._fetchAdvisories.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 361:58                                retryForHttp.<fn>.<fn>
===== asynchronous gap ===========================
package:pool/pool.dart 127:14                                   Pool.withResource
===== asynchronous gap ===========================
package:pub/src/http.dart 361:17                                retryForHttp.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 749:14                               retry
===== asynchronous gap ===========================
package:pub/src/http.dart 360:10                                retryForHttp
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 575:16                       HostedSource._fetchAdvisories.<fn>
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 127:12               withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 573:18                       HostedSource._fetchAdvisories
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 779:9                        HostedSource._getAdvisories
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1066:24                      HostedSource.getAdvisoriesForPackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 414:26                       SolveReport._reportPackage
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 218:18                       SolveReport._reportChanges
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 73:21                        SolveReport.show
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 568:5                           Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 166:5                      UpgradeCommand._runUpgrade
===== asynchronous gap ===========================
package:pub/src/command/upgrade.dart 141:7                      UpgradeCommand.runProtected
===== asynchronous gap ===========================
package:pub/src/command.dart 196:7                              PubCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 212:13                         CommandRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 232:18                             DartdevRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 46:16                              runDartdev
===== asynchronous gap ===========================
/Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 13:5  main
This is an unexpected error. 
```

This is fixed in Dart 3.4.4: https://github.com/dart-lang/pub/pull/4275

Can we get a 3.22.3 release with a Dart SDK bump? I assume we don't want the current stable to have breaking issues.

Thanks!

**Comment by darshankawar** [comment]
> Can we get a 3.22.3 release with a Dart SDK bump? I assume we don't want the current stable to have breaking issues.

@thomas-stockx Maybe you can raise cherry-pick request using the [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&projects=&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E) for team to review and decide.

**Comment by thomas-stockx** [comment]
Hi @darshankawar,

I'd love to but I have no idea what the process is to update the included Dart SDK in Flutter.

According to [this comment](https://github.com/flutter/flutter/issues/97640#issuecomment-1027830974), it's not trivial, so I just wanted to flag this for the team as I don't know how to proceed.

**Comment by darshankawar** [comment]
I will keep the issue open for team's input on this.

/cc @stuartmorgan for thoughts.

**Comment by stuartmorgan** [comment]
> I'd love to but I have no idea what the process is to update the included Dart SDK in Flutter.
> 
> According to [this comment](https://github.com/flutter/flutter/issues/97640#issuecomment-1027830974), it's not trivial

That comment is about what would be involved if an end-user of Flutter wanted to try to combine wildly different versions of Dart and Flutter after the fact, not about the normal process of Dart updates.

@itsjustkevin Is picking up the latest Dart stable bugfix release a standard part of the process when cutting a Flutter stable bugfix release, or do we need an issue tracking it?

**Comment by itsjustkevin** [comment]
@stuartmorgan Flutter releases pick up the latest Dart stable releases.  The current release being built includes Dart 3.4.4.

**Comment by stuartmorgan** [comment]
That's what I thought, thanks for confirming!

**Comment by thomas-stockx** [comment]
Is there currently a bugfix release planned for Flutter 3.22.x? It seems there's nothing to be done in the flutter repo to resolve this issue, as it will be resolved automatically with a new Flutter stable release.

Thanks for looking into this so quickly!

**Comment by christopherfujino** [comment]
> Is there currently a bugfix release planned for Flutter 3.22.x? It seems there's nothing to be done in the flutter repo to resolve this issue, as it will be resolved automatically with a new Flutter stable release.
> 
> Thanks for looking into this so quickly!

The next Flutter SDK release will be include Dart 3.4.4 and will come out imminently (this is what I'm currently working on)
