### ISSUE TITLE
URL Truncation When Saving Flutter Web App to Home Screen

### ISSUE THREAD

**Issue by 0x456d7265** [flutter/flutter#151552]
### Description
I am experiencing an issue with my Flutter Web application when saving it to my phone's home screen. Normally, websites save with their full URL, but my Flutter app only saves the base URL.

### Steps to reproduce

1- Open the Flutter Web app at https://pwatest-11e46.web.app/custom/46784/24478
2- Save the app to the home screen. (iOS, Android or Web via Chrome)

### Expected results

The URL should be saved as https://pwatest-11e46.web.app/custom/46784/24478

### Actual results

The URL is saved as https://pwatest-11e46.web.app/ truncating the custom path and ID.

## Additional Information
I have tried using both the go_router package and named routes, but the issue persists.
I am also using URL strategies in my main.dart file as shown below.

```dart
void main() {
  usePathUrlStrategy();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'PWA Test',
      routerConfig: appRouter, // Check down below
    );
  }
}
```

```dart
final GoRouter appRouter = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const HomeScreen(),
    ),
    GoRoute(
      path: '/custom/:someID/:anotherID',
      builder: (context, state) {
        final String someID = state.pathParameters['someID'] ?? 'empty';
        final String anotherID = state.pathParameters['anotherID'] ?? 'empty';

        return ExampleScreen(
          someID: someID,
          anotherID: anotherID,
        );
      },
    ),
  ],
);
```

**Comment by Epiwish** [comment]
> @Epiwish The provided url isn't working for me. If you try to create a new Flutter project, run it as pwa and try to save it to home screen, does it still gives same behavior ?

Hey,

I have created a new Flutter project and deployed it to a hosting. It still gives the same behavior. Also, I've updated the links. Can you check from there?

**Comment by darshankawar** [comment]
> The URL is saved as https://pwatest-11e46.web.app/ truncating the custom path and ID.

Where do you see that it is saved as above ?
I accessed the url in mobile web (chrome), saved it to home screen via installation and shortcut, and it was saved as `pwa_test`.

**Comment by Epiwish** [comment]
> > The URL is saved as https://pwatest-11e46.web.app/ truncating the custom path and ID.
> 
> Where do you see that it is saved as above ? I accessed the url in mobile web (chrome), saved it to home screen via installation and shortcut, and it was saved as `pwa_test`.

Yes, it will be saved as `pwa_test`. All websites behave like this. However, opening the `pwa_test` will start from the base URL instead of the full URL. Some websites can start from the URL that is saved in the first place. That's the difference.

**Comment by darshankawar** [comment]
Have you already checked the url being passed in index.html for base href ?

**Comment by Epiwish** [comment]
> Have you already checked the url being passed in index.html for base href ?

Hey,

I've checked the `index.html ` file, and my base href is set to `<base href="/">.`

Also, I've checked in Chrome DevTools, and it always shows `<base href="/">` even when I'm at this link: https://pwatest-11e46.web.app/custom/46784/24478.

Should I make any further changes to my index.html? Here is my full code:

```html
<!DOCTYPE html>
<html>
<head>
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="customer">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>customer</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <script src="flutter_bootstrap.js" async></script>
</body>
</html>
```

**Comment by darshankawar** [comment]
> ```
> <base href="/">
> ```

Can you try to pass the subpath as well here ,ie something like `<base href="/foo/">` and check if it helps ?

**Comment by Epiwish** [comment]
I've tried updating my base href to something like this `<base href ="/custom/>`  After making that change, I could not run the app. Any change to the base href other than `<base href ="/">` or `<base href="$FLUTTER_BASE_HREF">` causes the application to fail to open.

Additionally, I've noticed some logs on the Chrome console after changing the base href to a custom path. Here they are:

```
Uncaught SyntaxError: Unexpected token '<' (at flutter_bootstrap.js:1:1)
Manifest: Line: 1, column: 1, Syntax error. 
```

**Comment by darshankawar** [comment]
> Additionally, I've noticed some logs on the Chrome console after changing the base href to a custom path. Here they are:
> 
> ```
> Uncaught SyntaxError: Unexpected token '<' (at flutter_bootstrap.js:1:1)
> ```

Try by upgrading chrome browser on your phone to latest as this error indicates browser is not able to understand JavaScript newer syntax.

**Comment by Epiwish** [comment]
I've tested this on Chrome's Windows, Mac, and iOS versions. All are up to date. Still shows the same console log when changing the base href rather than `<base href ="/">`

**Comment by darshankawar** [comment]
Thanks for the update. Keeping the issue open and labeling for team's tracking.

**Comment by yjbanov** [comment]
```
Uncaught SyntaxError: Unexpected token '<' (at flutter_bootstrap.js:1:1)
Manifest: Line: 1, column: 1, Syntax error. 
```

This is likely happening because after changing the `base href` you are fetching `flutter_bootstrap.js` from a wrong location, and the server is serving a "404 page not found" HTML page. Then the browser is trying parse that HTML page as JavaScript and fails.

I looks like "Save the app to the home screen" functionality only saves the base URL. I'm not sure why browsers do that, but if they do, it means that if you want your app to live on a sub-path, you need to put all the resources relative to that sub-path, and then set the `base href` to the sub-path as well.

**Comment by yjbanov** [comment]
I don't think there's much we can do in Flutter itself. This is more of a hosting/server configuration, and placement of app assets. So I'm tempted to close this issue. @0x456d7265 Do you have any suggestions for what we can do on the Flutter side?
