### ISSUE TITLE
make sure that application is recompiled when .packages changes

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#15157]
It seems that `.packages` is not considered an input file for the build process currently, which means that applications don't always get recompiled or reloaded after people run `flutter packages upgrade`.

We need to make sure that both AOT builds and hot reload take `.packages` into account.

**Comment by aam** [comment]
Aren't all package dependencies that are controlled by `.packages` being explicitly listed in the dependency `.d` file as dart sources?

**Comment by mraleph** [comment]
@aam imagine that user compiles his app with library X version 0.1, his `.d` file contains `X:file:///.../0.1/lib/src`, then user runs `flutter packages upgrade`, which pulls new version of the dependency. Now his `.packages` file contains `X:file:///.../0.2/lib/src`. Notice that none of the files (except `.packages`) have changed. Yet compilation result should change.

**Comment by aam** [comment]
Okay, good point, thanks, @mraleph.

@peter-ahe-google, what do you think would be the best way for frontend to communicate path to `.packages` file back to frontend users that frontend used?

**Comment by peter-ahe-google** [comment]
Good point!
As a short-term solution, let's add a dummy entry for the .packages file to the source map.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/41302
