### ISSUE TITLE
[Dart] Regex with unicode and curly braces does not match correctly.

### ISSUE THREAD

**Issue by ernestrlee** [flutter/flutter#151580]
### Steps to reproduce

Run the following code:
String clearBullets(String s) => s.replaceAll(RegExp(r"[\u{2022}\u2023\u25E6\u2043\u2218\u2219▢]"), "");
print(clearBullets("multiple •‣◦⁃∘∙▢ again •‣◦⁃∘∙▢"));

Note the curly braces around 2022.

### Expected results

According to some documentation, it should not matter if curly braces are used or not.

### Actual results

output is: "mltiple • again •"  For some reason the letter "u" is removed.

### Code sample

<details open><summary>Code sample</summary>

```dart
String clearBullets(String s) => s.replaceAll(RegExp(r"[\u{2022}\u2023\u25E6\u2043\u2218\u2219▢]"), "");
print(clearBullets("multiple •‣◦⁃∘∙▢ again •‣◦⁃∘∙▢"));
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
n/a
```

</details>

**Comment by danagbemava-nc** [comment]
Regex are a language feature, as such this should be reported on https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc.

Kindly check for duplicates before you file the issue. 

Closing from here. 

Thank you
