### ISSUE TITLE
'image_picker/ImagePickerPlugin.h' file not found

### ISSUE THREAD

**Issue by PaulLuv** [flutter/flutter#15152]
My ide is AndroidStudio, and I can run other flutter app on iPhoneX.

It is runing ok for Android but not for the iPhoneX.

The error is 

`flutter_app/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: `

`'image_picker/ImagePickerPlugin.h' file not found  `

  `  #import <image_picker/ImagePickerPlugin.h>  `
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
![image](https://user-images.githubusercontent.com/19700658/36962192-82b324f8-2089-11e8-8f51-8406a893975a.png)

**Comment by marchampson** [comment]
Hi PaulLuv,

I'm running a similar setup and had the same error. I opened Runner.xcworkspace in xcode and sure enough, image_picker/ImagePickerPlugin.h didn't exist, in fact, image_picker didn't. 

So here's the steps I ended up taking to get it to work:

1) For me, to even get to this point, I had to create a new Flutter project using obj-c rather then Swift as the iOS option.

2) Closed IntelliJ, I believe it's similar to Android Studio in that any change I was making from the command line were being overwritten while the project was open.

2) With Xcode also closed, open up a terminal and run `$ pod install` from the ios directory of your project. That should download the image_picker library

```
➜  ios pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `Pods/.symlinks/flutter/ios`
Fetching podspec for `image_picker` from `Pods/.symlinks/plugins/image_picker-0.2.1/ios`
Downloading dependencies
Installing Flutter (1.0.0)
Installing image_picker (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```

Then from the same directory in terminal, open and run the project via xcode:

`$ open Runner.xcworkspace`

Once you've run it successfully in Xcode, you should be able to go back into Android Studio and run in the simulator (or on your device) and take advantage of hot reload again.

Hope that helps.
Marc

**Comment by jerrywell** [comment]
Hi @marchampson
I just found other issue has same case and solved by the workaround without changing the language to Objective-C. see there https://github.com/flutter/flutter/issues/15335.

**Comment by marchampson** [comment]
Thanks @jerrywell - I have a Swift+Flutter project too and copied and pasted Header directory from obj-c version and it does work. Would be nice to get this working out of the box. Cheers.

**Comment by mravn-google** [comment]
Please see https://github.com/flutter/flutter/issues/16036#issuecomment-380712094 for how to resolve this.
