### ISSUE TITLE
ListView.builder requires the use of the "new" keyword in certain cases.

### ISSUE THREAD

**Issue by tensor-programming** [flutter/flutter#15153]
## Steps to Reproduce
Create a ListView builder inside of a widget and give it a anonymous function for its itembuilder.  

For example:  ```itemBuilder: (BuildContext context, int index) {}```

When you attempt to declare the return type for this anonymous function using the dart-2 preview, both VS code and Intellij complain that it can't infer the return type without the use of a `new` keyword.

```
(BuildContext context, int index) {
     return Container();
}
```  

the code above is not valid according to the text editors.  The error displayed is this:

```
The function expression type '(BuildContext, int) → dynamic' isn't of type '(BuildContext, int) → Widget'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s).
```

```
(BuildContext context, int index) {
     return new Container();
}
```  
The code above this is valid however. 

Adding a `new` keyword is fixes this.  Also, creating a named function that returns a widget also fixes this.  Considering the new convention of not using the new/const keywords in most of Flutter, it seems a bit weird that there is no consistency in this case.

**Comment by zoechi** [comment]
might be a dup of #32342

**Comment by tensor-programming** [comment]
Oh right, should have checked the Dart sdk issues for dups.
