### ISSUE TITLE
Add spacing between `MenuAnchor` and `dropdownMenuEntries` in `DropdownMenu`

### ISSUE THREAD

**Issue by jasonkang14** [flutter/flutter#151524]
### Use case

I am trying to build an interface like the attached image using `DropdownMenu` where there is space between `MenuAnchor` and `dropdownMenuEntries`.

<img width="319" alt="Screenshot 2024-07-10 at 4 12 05 PM" src="https://github.com/flutter/flutter/assets/45306565/6224fd9e-491e-4d02-92b2-b58a75bde0b2">

### Proposal

Would you guys be open to accepting a pull request if i were to add an optional property called `spacing` to `DropdownMenu` and add a `SizedBox` to add a margin between `MenuAnchor` and `dropdownMenuEntries`? I think it would look something like below

```dart
return _DropdownMenuBody(
          width: widget.width,
          children: <Widget>[
            textField,
            SizedBox(height: spacing),
            for (final Widget item in _initialMenu!) item,
            trailingButton,
            leadingButton,
          ],
        );
```

**Comment by nate-thegrate** [comment]
Sounds good! Go ahead and make the PR; you can @ me in the description and I'll have a look 🙂
