### ISSUE TITLE
[integration_test] `flutter drive --wasm` does not report results even though tests completed

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#151561]
### Steps to reproduce

Run web integration tests with `flutter drive --wasm` on flutter master channel

### Expected results

Results are reported

### Actual results

- Results are not reported
- The command hangs forever
- Results can be seen in the Chrome dev tools. The tests do actually complete.

### Code sample

Use any of the official flutter packages that have been migrated to support WASM and have web integration tests

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.24.0-1.0.pre.104, on macOS 14.5 23F79
    darwin-arm64, locale en-US)
    ! Flutter version 3.24.0-1.0.pre.104 on channel [user-branch] at
      /Users/rexios/repos/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/setup.
    ! Upstream repository git@github.com:Rexios80/flutter.git is not a standard
      remote.
      Set environment variable "FLUTTER_GIT_URL" to
      git@github.com:Rexios80/flutter.git to dismiss this error.
    • Framework revision 7a2290c559 (60 minutes ago), 2024-07-10 15:16:33 -0400
    • Engine revision 1c23c8f640
    • Dart version 3.6.0 (build 3.6.0-22.0.dev)
    • DevTools version 2.37.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rexios/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio
      Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             •
      android-arm64  • Android 14 (API 34) (emulator)
    • Aaron’s iPhone (mobile)         • 00008130-001C35CE3A20001C • ios
      • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for Raj's Apple Vision Pro.
      Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac. (code -27)
    ! Error: Browsing on the local area network for Joe’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
> Use any of the official flutter packages that have been migrated to support WASM and have web integration tests

@Rexios80 I tried with `video_player` and `camera` and tried running with wasm enabled but it is giving me below error:

`Could not find an option named "wasm".`

Can you provide an example with which it works ?

**Comment by Rexios80** [comment]
I forgot to mention you have to be on master channel

**Comment by darshankawar** [comment]
Thanks for the tip. Switched to latest master and then trying to run integration_test from video_player or camera gives me `unable to find `main_test.dart` file. Please share the plugin you are using to run the scenario.

**Comment by Rexios80** [comment]
Welp it looks like maybe none of the integration test projects in the `packages` repo actually support compiling to WASM on the main branch. I'll create issues for that. If you want to see this issue in action right now checkout [this PR](https://github.com/flutter/packages/pull/7077) and run the following commands:

```console
cd packages/google_maps_flutter/google_maps_flutter_web/example
flutter drive -d chrome --web-port 7357 --wasm --driver test_driver/integration_test.dart --target integration_test/projection_test.dart
```

**Comment by Rexios80** [comment]
To clarify the integration tests actually _do_ compile to WASM, but the `index.html` files are out of date

**Comment by Rexios80** [comment]
I created https://github.com/flutter/flutter/issues/151663 to track this

**Comment by darshankawar** [comment]
> test driver sometimes saying all tests were successful when they were clearly not by looking at the Chrome dev console

This could be https://github.com/flutter/flutter/issues/129041

**Comment by darshankawar** [comment]
> checkout [this PR](https://github.com/flutter/packages/pull/7077) and run the following commands:
> 
> ```
> cd packages/google_maps_flutter/google_maps_flutter_web/example
> flutter drive -d chrome --web-port 7357 --wasm --driver test_driver/integration_test.dart --target integration_test/projection_test.dart
> ```

Following this, I observed the similar behavior as reported.

**Comment by Rexios80** [comment]
This appears to have been caused by issues driving examples that use `flutter_bootstrap.js` rather than an issue with running tests compiled to WASM. See https://github.com/flutter/packages/pull/7115#issuecomment-2229569641 for details.

**Comment by Rexios80** [comment]
Note that there are still some issues with test result reporting, but I believe those are different enough to get their own tickets
