### ISSUE TITLE
Error: Unable to load asset 

### ISSUE THREAD

**Issue by nate587** [flutter/flutter#151501]
### Steps to reproduce

1.) Create new project with exactly the same code and files
2.) flutter pub add provider 
3.) flutter pub add audioplayers
4.) Run app on andriod emulator
5.) Press on a music tile and navigate to songpage.

### Expected results

The song in lib/music is supposed to play.

**My Repository:** https://github.com/nate587/music_issue

### Actual results

The song is not playing and im getting the following error:

Playing: lib/music/remix.mp3
E/flutter ( 4806): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/lib/music/remix.mp3".
E/flutter ( 4806): The asset does not exist or has empty data.

### Code sample

**My Repository:** https://github.com/nate587/music_issue

### Screenshots or Video

**My Repository:** https://github.com/nate587/music_issue

### Logs

**My Repository:** https://github.com/nate587/music_issue

### Flutter Doctor output

**My Repository:** https://github.com/nate587/music_issue

**Comment by darshankawar** [comment]
@nate587 
You are using third party packages and the error seems to be pointing to audio_players:
```

E/flutter (31739): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/lib/music/remix.mp3".
E/flutter (31739): The asset does not exist or has empty data.
E/flutter (31739): #0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:324:9)
E/flutter (31739): <asynchronous suspension>
E/flutter (31739): #1      AudioCache.fetchToMemory (package:audioplayers/src/audio_cache.dart:99:22)
E/flutter (31739): <asynchronous suspension>
E/flutter (31739): #2      AudioCache.load (package:audioplayers/src/audio_cache.dart:130:31)
E/flutter (31739): <asynchronous suspension>
E/flutter (31739): #3      AudioCache.loadPath (package:audioplayers/src/audio_cache.dart:139:26)
E/flutter (31739): <asynchronous suspension>
E/flutter (31739): #4      AudioPlayer.setSourceAsset (package:audioplayers/src/audioplayer.dart:421:23)
E/flutter (31739): <asynchronous suspension>
E/flutter (31739): #5      AudioPlayer.setSource (package:audioplayers/src/audioplayer.dart:348:5)
E/flutter (31739): <asynchronous suspension>
E/flutter (31739): #6      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:214:5)
E/flutter (31739): <asynchronous suspension>
E/flutter (31739): #7      PlaylistProvider.play (package:music_player/models/playlist_provider.dart:48:5)
E/flutter (31739): <asynchronous suspension>
E/flutter (31739): 

```

This mostly looks like code implementation issue or package issue that you need to report in dedicated repo.
Closing from here.
