### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by BhadrakshB** [flutter/flutter#151634]
## Command
```
flutter run -d chrome --web-renderer html
```

## Steps to Reproduce
1. I am running this project on flutter web. It's a very simple project for my org that uses firebase.

## Logs
FormatException
```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905
