### ISSUE TITLE
Xcode build failure after adding FlutterFire to project

### ISSUE THREAD

**Issue by theEpicality** [flutter/flutter#15168]
## Steps to Reproduce

Not entirely sure what steps are _necessary_ to reproduce this issue because I seem to be the only one having it. I'll go ahead and share what _appears_ to be the cause.

**1.** Add `firebase_database: ^0.3.6` and/or `firebase_core: ^0.0.7` to the pubspec.yaml file
**2.** Use the `flutter run` command in the Terminal with a Simulator

The app runs perfectly on Android and successfully connects to a Firebase Database but when building for iOS, it gives the following error:
`/Users/nathanbird/AndroidStudioProjects/wersafety/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_core/FirebaseCorePlugin.h' file not found`

I opened the GeneratedPluginRegistrant.m file and Xcode is giving a similar error:

!['firebase_core/FirebaseCorePlugin.h' file not found](https://i.imgur.com/aS01lFD.png "'firebase_core/FirebaseCorePlugin.h' file not found")

If I remove the dependencies from the pubspec.yaml file, the errors disappear on the next build.

## Logs

    Failed to build iOS app
    Error output from Xcode build:
    ↳
        ** BUILD FAILED **
    
    Xcode's output:
    ↳
    === BUILD TARGET firebase_database OF PROJECT Pods WITH CONFIGURATION Debug ===
    ld: warning: -undefined dynamic_lookup is deprecated on iOS
    
    === BUILD TARGET firebase_database OF PROJECT Pods WITH CONFIGURATION Debug ===
    ld: warning: -undefined dynamic_lookup is deprecated on iOS
    
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/nathanbird/AndroidStudioProjects/wersafety/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_core/FirebaseCorePlugin.h' file not found
    #import <firebase_core/FirebaseCorePlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel dev)
    • Flutter version 0.1.4 at /Users/nathanbird/flutter
    • Framework revision f914e701c5 (2 weeks ago), 2018-02-19 21:12:17 +0000
    • Engine revision 13cf22c284
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/nathanbird/Library/Android/sdk
    • Android NDK at /Users/nathanbird/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] VS Code (version 1.19.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices
    • Nexus 6P      • 84B7N16804000234                         • android-arm64 • Android 8.1.0 (API 27)
    • iPhone 8 Plus • 25E17EA3-F66F-4BE9-A1E1-49C4FEFE03D8     • ios           • iOS 11.2 (simulator)

**Comment by abogdanovich1** [comment]
Not sure if the same error, I'll open another ticket if it is not related, but I get this output after adding firebase_auth >=0.4.5

Xcode's output:
↳
    === BUILD TARGET firebase_database OF PROJECT Pods WITH CONFIGURATION Debug ===
    ld: warning: -undefined dynamic_lookup is deprecated on iOS
    === BUILD TARGET google_sign_in OF PROJECT Pods WITH CONFIGURATION Debug ===
    ld: warning: -undefined dynamic_lookup is deprecated on iOS
    ld: warning: -undefined dynamic_lookup is deprecated on iOS
    ld: warning: -undefined dynamic_lookup is deprecated on iOS
    === BUILD TARGET google_sign_in OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/abogdanovich/.pub-cache/hosted/pub.dartlang.org/google_sign_in-2.1.2/ios/Classes/GoogleSignInPlugin.m:111:41: warning: 'UIApplicationOpenURLOptionsSourceApplicationKey' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      NSString *sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/abogdanovich/Desktop/SeniorProject/artist_connect_flutter/ios/Pods/Target Support Files/google_sign_in/google_sign_in-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:534:51: note: 'UIApplicationOpenURLOptionsSourceApplicationKey' has been explicitly marked partial here
    UIKIT_EXTERN UIApplicationOpenURLOptionsKey const UIApplicationOpenURLOptionsSourceApplicationKey NS_AVAILABLE_IOS(9_0);   // value is an NSString containing the bundle ID of the originating application
                                                      ^
    /Users/abogdanovich/.pub-cache/hosted/pub.dartlang.org/google_sign_in-2.1.2/ios/Classes/GoogleSignInPlugin.m:111:41: note: enclose 'UIApplicationOpenURLOptionsSourceApplicationKey' in an @available check to silence this warning
      NSString *sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/abogdanovich/.pub-cache/hosted/pub.dartlang.org/google_sign_in-2.1.2/ios/Classes/GoogleSignInPlugin.m:112:27: warning: 'UIApplicationOpenURLOptionsAnnotationKey' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      id annotation = options[UIApplicationOpenURLOptionsAnnotationKey];
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/abogdanovich/Desktop/SeniorProject/artist_connect_flutter/ios/Pods/Target Support Files/google_sign_in/google_sign_in-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:535:51: note: 'UIApplicationOpenURLOptionsAnnotationKey' has been explicitly marked partial here
    UIKIT_EXTERN UIApplicationOpenURLOptionsKey const UIApplicationOpenURLOptionsAnnotationKey NS_AVAILABLE_IOS(9_0);   // value is a property-list typed object corresponding to what the originating application passed in UIDocumentInteractionController's annotation property
                                                      ^
    /Users/abogdanovich/.pub-cache/hosted/pub.dartlang.org/google_sign_in-2.1.2/ios/Classes/GoogleSignInPlugin.m:112:27: note: enclose 'UIApplicationOpenURLOptionsAnnotationKey' in an @available check to silence this warning
      id annotation = options[UIApplicationOpenURLOptionsAnnotationKey];
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    === BUILD TARGET google_sign_in OF PROJECT Pods WITH CONFIGURATION Debug ===
    ld: warning: -undefined dynamic_lookup is deprecated on iOS
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/abogdanovich/Desktop/SeniorProject/artist_connect_flutter/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_auth/FirebaseAuthPlugin.h' file not found
    #import <firebase_auth/FirebaseAuthPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.

Error launching application on iPhone.

Here's my flutter doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.2 17C88, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] Connected devices (2 available)

• No issues found!

**Comment by theEpicality** [comment]
@abogdanovich1 Yep, I think it's the same problem

**Comment by csga5000** [comment]
As I reported here: https://github.com/flutter/flutter/issues/15335#issuecomment-371898231
I'm also having this issue with any package.  I'll try @abogdanovich1 's workaround

**Comment by Stroi** [comment]
While doing the "Firebase-Flutter" tutorial I followed the steps to import the Firebase. When I run the app, I got the "'FirebaseAnalyticsPlugin.h' file not found" error. So I tried to use this workaround and it worked for the Analytics. When I fixed Analytics a got same error with FirebaseDatabase. I did the same thing as before but it didn't work. >> I'm getting "FirebaseDatabasePlugin.h not found".
Here is where I put the header files:
![screen shot 2018-03-10 at 14 10 53](https://user-images.githubusercontent.com/24395847/37242624-17c8b648-246d-11e8-9b50-688d20386115.png)

Any ideas why it works for one but not for the other ?

**Comment by abogdanovich1** [comment]
Hmm, that’s weird.
Yeah it seems like this isn’t just a few people having this issue, I wonder if the devs are gonna get around to fixing this anytime soon. Kinda annoying having a cross platform framework only compile to one set of devices hahah

**Comment by csga5000** [comment]
@stroi You're running in debug mode for the simulator?  If you want to run on a device 
you have to fix the non simulator folder.  You could try my added fix as well, for xcode, see if you can build through that.

@abogdanovich1 flutters been pretty painless, for me they've done a great job, but it does seem Android dev is a little more stable than iOS.  To be fair iOS dev is usually less stable anyway and it's incredible what they've got done. For me it works fine unless it's a swift project ("flutter create -i swift proj_name") so it seems like a bug they just missed that only applies to a small subset of people.  That's fair for a beta product, and I'm sure they'll fix it

**Comment by abogdanovich1** [comment]
Yeah I can’t really complain too much. It’s working for me now without issues for about 4 days and I’m that time I’ve made about 50% of my app, in 1/5 the code it took to complete my app in Swift 😅
This is already a great product, can’t wait till it’s stable!

**Comment by theEpicality** [comment]
Great news! @zoechi pointed out that there's been a commit to make plugins work in Swift. (See [here](https://github.com/flutter/flutter/pull/15437/files#diff-519f1341a7393048261b00690f7c2c0e)) I did as recommended and it fixed everything. [StackOverflow question](https://stackoverflow.com/a/49274856/5900511)

**Comment by Stoneman790** [comment]
For me no plugins work after adding dependencies to the pubspec.yaml file.  When I run the app on iOS device or simulator in  debug, I get errors like this. fatal error: 'firebase_auth/FirebaseAuthPlugin.h' file not found.  I have tried all of the suggestions and workarounds with no success.

**Comment by Stoneman790** [comment]
What solved it for me was to:
1. uninstall cocoapods version 1.5.0, 
2. delete the podfile lock file,
3. delete the Pod Folder,
4. and the install cocoapods 1.4.0.  
5. Then 'flutter run' (from the command line).

There are plenty of guides on how to do the cocoapod stuff, so I won't post them here.

No more missing header file errors!  Now I'm running into web socket issues.  Sometimes it works, sometimes not.

**Comment by fmatosqg** [comment]
See fix on https://github.com/flutter/flutter/pull/16273

**Comment by ramah** [comment]
Hi  This is an information. If you have trouble with iOS + firebase_auth 0.5.9 add to your podfile this line according to this link https://github.com/invertase/react-native-firebase/issues/1061  : 

pod 'Firebase/Core', '~> 4.13.0'.

**Comment by lukepighetti** [comment]
I followed the directions provided by Flutter documentation and Firebase documentation and I am running into this error 

```
** BUILD FAILED **
Xcode's output:
↳
While building module 'Flutter' imported from /Users/lukepighetti/code/when-coin/when_coin/ios/Runner/GeneratedPluginRegistrant.h:8:
In file included from <module-includes>:1:
In file included from /Users/lukepighetti/code/when-coin/when_coin/ios/Flutter/Flutter.framework/Headers/Flutter.h:37:
In file included from /Users/lukepighetti/code/when-coin/when_coin/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
/Users/lukepighetti/code/when-coin/when_coin/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:140:58: warning: this block declaration is not a prototype [-Wstrict-prototypes]
completionHandler:(nonnull void (^)())completionHandler;
^
void
1 warning generated.
/Users/lukepighetti/code/when-coin/when_coin/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_core/FirebaseCorePlugin.h' file not found
#import <firebase_core/FirebaseCorePlugin.h>
```

Kinda sad when I'm used to "npm install firebase". Anyone have any ideas?

**Comment by lukepighetti** [comment]
I tried downgrading to CocoaPods 1.4.0 and I'm having the same problem.

**Comment by marticols** [comment]
Hi guys,

Copy the header file form ios/.symlinks/plugins/PLUGIN_NAME/ios/Classes/PLUGIN_NAME.h to ios/Pods/Headers/PLUGIN_NAME/PLUGIN_NAME.h.

**Comment by ChristBKK** [comment]
I still have this problem

**Comment by salmaanahmed** [comment]
Isn't this problem resolved yet?

**Comment by MarcelEdward** [comment]
Getting the headers error sometimes ... rebuild most of the time makes it go away

**Comment by luigifaticoso** [comment]
I'm having this problem too

**Comment by timbergus** [comment]
> What solved it for me was to:
> 
> 1. uninstall cocoapods version 1.5.0,
> 2. delete the podfile lock file,
> 3. delete the Pod Folder,
> 4. and the install cocoapods 1.4.0.
> 5. Then 'flutter run' (from the command line).
> 
> There are plenty of guides on how to do the cocoapod stuff, so I won't post them here.
> 
> No more missing header file errors! Now I'm running into web socket issues. Sometimes it works, sometimes not.

Not working for me. I have cleaned all multiple times. I have downgraded cocoa pods, and I'm still having the same error with firebase_auth missing headers :(

Right now I'm only developing using the Android simulator because iOS is dead.

And if I use the latest [template](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/cocoapods/Podfile-swift) from Flutter for Podfile, I have this error.

![Screenshot 2019-04-03 at 18 16 09](https://user-images.githubusercontent.com/1750734/55495202-ace18c80-563c-11e9-88f1-e43014cce278.png)

And stays there forever and ever.

**Comment by neelu004** [comment]
Hi, I am adding the dependency of shared_preference and it is working fine when I am running my project on android using windows but when I am using Mac(Xcode) it is giving me error as ld: warning: directory not found for option '-L/Users/ghanshyam/Development/Android/Workspace/my_app/build/ios/Debug-iphoneos/shared_preferences'
ld: library not found for -lshared_preferences
clang: error: linker command failed with exit code 1 (use -v to see invocation)
I had tried using the following methods but that doesn't works for me. They are:-
pod install
pod upgrade
flutter clean
flutter packages get
flutter packages upgrade
flutter run using command it is working fine but works on simulator still could not run on my real iPhone device using the same command.
also when I am using flutter build ios, this will creates the Runner.app but how can I install this Runner.app on my iPhone device.
Please suggest some solution for the same.
Thanks!

**Comment by johnvarg** [comment]
After several trial and error here is what I find 
a) repro steps to break 
b) steps to clean and fix

**Comment by ojordann** [comment]
Updating `cocoapods` to the latest version, `sudo gem install cocoapods` and running `pod repo update` worked for me.

**Comment by sof9816** [comment]
> What solved it for me was to:
> 
>     1. uninstall cocoapods version 1.5.0,
> 
>     2. delete the podfile lock file,
> 
>     3. delete the Pod Folder,
> 
>     4. and the install cocoapods 1.4.0.
> 
>     5. Then 'flutter run' (from the command line).
> 
> 
> There are plenty of guides on how to do the cocoapod stuff, so I won't post them here.
> 
> No more missing header file errors! Now I'm running into web socket issues. Sometimes it works, sometimes not.

I read the comments and yours was little bit helpful, when  you mentioned the pod i remembered to install the pods again, and i did and it all worked just fine .

**Comment by raghaaavvvv** [comment]
It works!
i just copied Podfileobjc
(https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/cocoapods) 
to my projects iOS/Podfile
Thanks a lot :)

**Comment by kutran** [comment]
> It works!
> i just copied Podfileobjc
> (https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/cocoapods)
> to my projects iOS/Podfile
> Thanks a lot :)

This works!  How does this work?  I am assuming that the script parses the yaml file and extract the projects, then add them to the Pod?

**Comment by cyrsis** [comment]
Try to set the deployment target to iOS 9 or later.

Worked for me

**Comment by pridemusvaire** [comment]
> > It works!
> > i just copied Podfileobjc
> > (https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/cocoapods)
> > to my projects iOS/Podfile
> > Thanks a lot :)
> 
> This works! How does this work? I am assuming that the script parses the yaml file and extract the projects, then add them to the Pod?

Worked for me, thanks

**Comment by daniele777** [comment]
== Building for iOS ==


== /usr/local/bin/flutter build ios --debug --no-codesign ==

Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.corte.takeaway for device (ios)...

Running pod install...                                          
    2.0s
Running Xcode build...                                          

Xcode build done.                                           45.3s

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/builder/clone/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'firebase_auth' not found
    @import firebase_auth;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.
    /Users/builder/clone/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'firebase_auth' not found
    @import firebase_auth;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Encountered error while building for device.


Guys i have this error with codemagic...

**Comment by daniele777** [comment]
C:\Users\Dani\Documents\lacortetakeaway\ios>pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

[!] The Podfile does not contain any dependencies.

[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

C:\Users\Dani\Documents\lacortetakeaway\ios>
