### ISSUE TITLE
Keyboard does not hide after confirming the entered text in DropdownMenu

### ISSUE THREAD

**Issue by krzysiekj94** [flutter/flutter#151657]
### Use case

In my mobile application I'm using **DropdownMenu** widget - see below.. 
![image](https://github.com/user-attachments/assets/95389e78-a7c6-477c-b590-05b96020edf6)

The problem I have is that after I click the confirm button, the keyboard is not hidding... 
I was looking for various options - one of them was to fork the existing code and make the **onSubmitted** method **_public_**.
In the onSubmitted callback I can now provide a code that will close the keyboard by using the Focus mechanism - see below:

![image](https://github.com/user-attachments/assets/6e5743f7-8ffd-42cf-87e3-2200a4d5422a)

I use Flutter in version 3.22.2. For now, I would like this code to be in the main Flutter repository so that I won't make additional fork in my code. If you need more explanations, please write to me.

### Proposal

1. Adding an additional callback at the DropDownMenu class level

`lib\in_dropdown_menu\dropdown_menu.dart`

`final void Function(String)? onSubmitted;`

2. Extension of the TextField text field with the **onSubmitted** method set externally via callback.

```
final Widget textField = TextField(
          key: _anchorKey,
          **onSubmitted: widget.onSubmitted,**
```
          .....

**Comment by darshankawar** [comment]
@krzysiekj94 
Check [this](https://stackoverflow.com/questions/76871751/how-to-hide-keyboard-in-flutter-dropdownmenu#:~:text=Determine%20if%20the%20dropdown%20button,%5B...%5D&text=That%20does%20not%20hide%20the,Setting%20requestFocusOnTap%20to%20false%20does.) and see if it helps in your case or not.

**Comment by krzysiekj94** [comment]
> @krzysiekj94 Check [this](https://stackoverflow.com/questions/76871751/how-to-hide-keyboard-in-flutter-dropdownmenu#:~:text=Determine%20if%20the%20dropdown%20button,%5B...%5D&text=That%20does%20not%20hide%20the,Setting%20requestFocusOnTap%20to%20false%20does.) and see if it helps in your case or not.

Hello.. Unfortunalety your workaround doesn't work for me. After set requestFocusOnTap keyboard is not visible..
My expectation is open keyboard when i tap/click on the text field and i want to be able to write some text.. and only if I click in submit button on keyboard i want to close this dialog.. therefore i proposed the onSubmitted function as above.. See my fork implementation:

`child: INDropdownMenu(
                enableFilter: true,
                dropdownMenuEntries: timeTrackingInformationTextList,
                controller: textController,
                inputDecorationTheme: const InputDecorationTheme(
                  border: UnderlineInputBorder(
                    borderRadius: BorderRadius.zero,
                  ),
                ),
                requestFocusOnTap: false,
                trailingIcon: Icon(
                  Icons.keyboard_arrow_down,
                  color: getIt<ThemeManager>().isDarkModeActive()
                      ? ThemeColors.inWhite
                      : ThemeColors.inBlue,
                  size: 36,
                ),
                textStyle: const TextStyle(
                  fontSize: 16,
                ),
                menuStyle: MenuStyle(
                  shape: const WidgetStatePropertyAll(
                    RoundedRectangleBorder(),
                  ),
                  backgroundColor: WidgetStateProperty.all(
                    getIt<ThemeManager>().isDarkModeActive()
                        ? ThemeColors.inDarkerGrey55
                        : ThemeColors.inWhite,
                  ),
                ),
                expandedInsets: EdgeInsets.zero,
                menuHeight: 200,
                width: 350,
                onSelected: (timeTrackingTextValue) {
                  setState(() {
                    field.didChange(
                      timeTrackingTextValue,
                    );
                  });
                },
                onSubmitted: (value) {
                  textController.text = value;
                  FocusScope.of(context).unfocus();
                },
              ),`

**Comment by darshankawar** [comment]
@krzysiekj94 
Please provide complete but minimal reproducible code sample (ex: main.dart) without third party implementation and custom implementations, that we can directly use which shows current behavior.
