### ISSUE TITLE
flutter fails if libreadline.6.dylib absent on system

### ISSUE THREAD

**Issue by andyhawkes** [flutter/flutter#15165]
## Steps to Reproduce

1. Clone git repo following the instructions at https://flutter.io/setup-macos/
2. Add flutter to $PATH
3. Run `flutter doctor`

## Logs

```
$ flutter run
Building flutter tool...
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/bash
  Reason: image not found
/Users/andy.hawkes/code/tools/flutter/bin/flutter: line 36: 45359 Trace/BPT trap: 5       "$PUB" upgrade --verbosity=error --no-packages-dir
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```

## Flutter Doctor

```
$ flutter doctor -v
Building flutter tool...
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/bash
  Reason: image not found
/Users/andy.hawkes/code/tools/flutter/bin/flutter: line 36: 45407 Trace/BPT trap: 5       "$PUB" upgrade --verbosity=error --no-packages-dir
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```

This happens with both the `beta` and `master` branches.

**Comment by Hixie** [comment]
cc @cbracken

**Comment by cbracken** [comment]
@andyhawkes It looks like what's failing is a custom installation of bash on your system -- notice the error message that it's bash that's trying to load libReadline, not Flutter. Flutter *does* invoke bash, but I suspect what you're seeing is homebrew#5799.

The solution posted there is `brew upgrade bash`. Does that help?

**Comment by andyhawkes** [comment]
Perfect - thanks!
I knew it would be something simple, and probably something that I did in the background absolutely ages ago on a completely unrelated project!
