### ISSUE TITLE
How to handle bakc and foward button on flutter web

### ISSUE THREAD

**Issue by Guilherme-ctrl** [flutter/flutter#151697]
So i started a flutter web project, and im thinking about tha back and foward browser button. How can i block from the user? or else it will be able to go back and foward from a login screen without credentials, is flutter web ready for a project?

**Comment by FusoraTech** [comment]
Hi, First read this: https://github.com/flutter/flutter/blob/master/docs/README.md

Then I must say that this space isn't the appropriate place for doubts and chatting, just to report issues and participate on issues related subjects. For chatting with other developers I suggest the FlutterDev's [Discord](https://discord.com/invite/N7Yshp4) or [Reddit](https://www.reddit.com/r/FlutterDev/)

**Comment by darshankawar** [comment]
Please open such issues in support channels like StackOverflow.
Closing from here.
