### ISSUE TITLE
"EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000015df9500" with 3 different logs objc_retain,objc_msgSend and objc_retain_x0

### ISSUE THREAD

**Issue by dev3-tech** [flutter/flutter#151630]
### Steps to reproduce

run given sample code in ios device.
open youtube website
go to background state
leave your device until it locks automatically
as device locks it immediately throws exception in xcode

[inappwebview.zip](https://github.com/user-attachments/files/16188577/inappwebview.zip)

mostly it happens to me when i use app lifecycle observer and push to other screen when app goes to background state and then device locks.

### Expected results

it should work normally without throwing exception and display the page from where user leave the app in background.

### Actual results

it throws exception and restarts app from splash screen automatically in released app and freezes in debug mode.

### Code sample

[inappwebview.zip](https://github.com/user-attachments/files/16188643/inappwebview.zip)

### Logs

there are 3 different crashes

----------------------------------1---------------------------------------
```console
Crashed: com.apple.main-thread
0 libobjc.A.dylib 0x3120 objc_retain + 16
1 UIAccessibility 0x35f1c -[NSObject(AXPrivCategory) accessibilityEnumerateAncestorsUsingBlock:] + 112
2 UIKit 0x48860 + 176
3 libdispatch.dylib 0x63094 _dispatch_call_block_and_release + 24
4 libdispatch.dylib 0x64094 _dispatch_client_callout + 16
5 libdispatch.dylib 0x10d44 _dispatch_main_queue_drain + 928
6 libdispatch.dylib 0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp + 36
7 CoreFoundation 0x4e014 + 12
8 CoreFoundation 0xb4f8 + 2544
9 CoreFoundation 0x1e174 CFRunLoopRunSpecific + 572
10 GraphicsServices 0x1988 GSEventRunModal + 160
11 UIKitCore 0x4e5a88 + 1080
12 UIKitCore 0x27ef78 UIApplicationMain + 336
13 MyApp 0x8050 main + 7 (main.m:7)
14 ??? 0x1012204d0 (Missing)
```

-----------------------------------2--------------------------------------

```console
Crashed: com.apple.main-thread
0 libobjc.A.dylib 0x3478 objc_retain_x0 + 16
1 libobjc.A.dylib 0x3478 objc_retain + 16
2 UIAccessibility 0x60a14 -[NSObject(AXPrivCategory) _accessibilityRemoteParent] + 136
3 UIAccessibility 0x4d82c -[NSObject(AXPrivCategory) _iosAccessibilityAttributeValue:] + 31104
4 UIAccessibility 0x8c970 -[AXRemoteElement(UIAccessibility) _iosAccessibilityAttributeValue:] + 1304
5 UIAccessibility 0xa888 _accessibilityAttributeValueDispatch + 76
6 UIAccessibility 0x5c50 _copyAttributeValueCallback + 680
7 AXRuntime 0x10030 ___AXXMIGCopyAttributeValue_block_invoke + 80
8 AXRuntime 0xffc4 _handleNonMainThreadCallback + 448
9 AXRuntime 0xfba4 _AXXMIGCopyAttributeValue + 532
10 AXRuntime 0x7cbbc _XCopyAttributeValue + 536
11 AXRuntime 0x2c394 mshMIGPerform + 1116
12 CoreFoundation 0x8ffa0 CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION + 56
13 CoreFoundation 0x91bb4 __CFRunLoopDoSource1 + 512
14 CoreFoundation 0x75744 __CFRunLoopRun + 2332
15 CoreFoundation 0x79d20 CFRunLoopRunSpecific + 584
16 GraphicsServices 0x1998 GSEventRunModal + 160
17 UIKitCore 0x371448 -[UIApplication _run] + 868
18 UIKitCore 0x3710c0 UIApplicationMain + 312
19 MyApp 0x8050 main + 7 (main.m:7)
20 ??? 0x1ac57c344 (Missing)
```
-----------------------------------3--------------------------------------

```console
Crashed: com.apple.main-thread
0 libobjc.A.dylib 0x20f8 objc_msgSend + 24
1 UIAccessibility 0x381e0 -[NSObject(AXPrivCategory) _accessibilityFindAncestor:startWithSelf:findTopmostAncestor:] + 92
2 UIAccessibility 0x37d30 -[NSObject(AXPrivCategory) _accessibilityAncestorIsKindOf:] + 112
3 UIKit 0xca070 -[UIViewAccessibility _accessibilityFKAShouldBeProcessed] + 196
4 CoreFoundation 0xa5558 NSARRAY_IS_CALLING_OUT_TO_A_BOOL_BLOCK + 24
5 CoreFoundation 0xa616c __NSArrayGetIndexesPassingTest + 488
6 AXCoreUtilities 0x7084 -[NSArray(AXExtras) ax_filteredArrayUsingBlock:] + 32
7 UIKit 0xc9ee4 -[UIViewAccessibility _childFocusRegionsInRect:inCoordinateSpace:] + 1768
8 UIKitCore 0x10f63c0 -[UIView _searchForFocusRegionsInContext:] + 892
9 UIKitCore 0x64ee78 -[_UIFocusMapSnapshot addRegionsInContainer:] + 196
10 UIKitCore 0x64f010 -[_UIFocusMapSnapshot addRegionsInContainers:] + 200
11 UIKitCore 0x10f63e4 -[UIView _searchForFocusRegionsInContext:] + 928
12 UIKitCore 0x64ee78 -[_UIFocusMapSnapshot addRegionsInContainer:] + 196
13 UIKitCore 0x64e690 -[_UIFocusMapSnapshot _capture] + 284
14 UIKitCore 0x64dd68 -[_UIFocusMapSnapshot _initWithSnapshotter:mapArea:searchArea:] + 496
15 UIKitCore 0x64fc80 -[_UIFocusMapSnapshotter captureSnapshot] + 224
16 UIKitCore 0x6452d0 -[_UIFocusMap _defaultFocusItemInEnvironment:limitScopeUsingFocusPreferences:] + 236
17 UIKitCore 0x61a45c -[_UIFocusEnvironmentPreferenceEnumerationContext _inferPreferencesForEnvironment:] + 156
18 UIKitCore 0x619ff4 -[_UIFocusEnvironmentPreferenceEnumerationContext _resolvePreferredFocusEnvironments] + 132
19 UIKitCore 0x619f2c -[_UIFocusEnvironmentPreferenceEnumerationContext prefersNothingFocused] + 44
20 UIKitCore 0x61ace8 _enumeratePreferredFocusEnvironments + 192
21 UIKitCore 0x61ae0c _enumeratePreferredFocusEnvironments + 484
22 UIKitCore 0x61ae0c _enumeratePreferredFocusEnvironments + 484
23 UIKitCore 0x61ab40 -[_UIFocusEnvironmentPreferenceEnumerator enumeratePreferencesForEnvironment:usingBlock:] + 204
24 UIKitCore 0x61b484 -[_UIDeepestPreferredEnvironmentSearch deepestPreferredFocusableItemForEnvironment:withRequest:] + 720
25 UIKitCore 0x6632cc -[UIFocusUpdateContext _updateDestinationItemIfNeeded] + 236
26 UIKitCore 0x663074 -[UIFocusUpdateContext _destinationItemInfo] + 32
27 UIKitCore 0x662f28 -[UIFocusUpdateContext nextFocusedItem] + 28
28 UIKitCore 0x662668 -[UIFocusUpdateContext _validate] + 112
29 UIKitCore 0x6625d0 -[UIFocusUpdateContext _isValidInFocusSystem:] + 128
30 UIKitCore 0x651e24 -[UIFocusSystem _updateFocusWithContext:report:] + 148
31 UIKitCore 0x653498 -[UIFocusSystem _updateFocusImmediatelyWithContext:] + 104
32 UIKitCore 0x65546c _UIAXAssignFocusToItemWithOptions + 252
33 UIKit 0xb9c1c __88-[UITextInputUIResponderAccessibility _axDrawFocusRingAroundFirstResponderAndMoveFocus:]_block_invoke + 36
34 libdispatch.dylib 0x224c _dispatch_call_block_and_release + 32
35 libdispatch.dylib 0x3db0 _dispatch_client_callout + 20
36 libdispatch.dylib 0x117ac _dispatch_main_queue_callback_4CF + 836
37 CoreFoundation 0xa111c CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 16
38 CoreFoundation 0x9b120 __CFRunLoopRun + 2508
39 CoreFoundation 0x9a21c CFRunLoopRunSpecific + 600
40 GraphicsServices 0x3784 GSEventRunModal + 164
41 UIKitCore 0xbc8fe0 -[UIApplication _run] + 1072
42 UIKitCore 0xbce854 UIApplicationMain + 168
43 MyApp 0x8050 main + 7 (main.m:7)
44 libdyld.dylib 0x16b0 start + 4
```

### Flutter Doctor output

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6 22G120 darwin-x64, locale en-IN)
• Flutter version 3.19.6 on channel stable at /Applications/development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
• Engine revision c4cd48e186
• Dart version 3.3.4
• DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at /Users/mac007/Library/Android/sdk
• Platform android-34, build-tools 34.0.0
• ANDROID_HOME = /Users/mac007/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 15A240d
• CocoaPods version 1.15.2

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.74.3)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.60.0

[✓] Connected device (2 available)
• macOS (desktop) • macos • darwin-x64 • macOS 13.6 22G120 darwin-x64
• Chrome (web) • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] Network resources
• All expected network resources are available.
```

**Comment by huycozy** [comment]
I see there are only native traces above but no Flutter trace. Also, your sample code is using [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) which is a 3rd party package, can you try replacing it with [webview_flutter](https://pub.dev/packages/webview_flutter) to see if the crash occurs or not?

**Comment by dev3-tech** [comment]
When i remove App lifecycle observer completely in sample code then its working fine and in my live app there are more than 15 3rd party packages but this crash occurring in too many user's device and its occurring anywhere in app but in my device it is regenerated only in web browser so i provided that sample code.

**Comment by huycozy** [comment]
I just looked into your code, the error possibly comes from your code in `AppLifecycleState.paused` callback, but may not relate to webview plugin. Can you try to narrow it down and confirm?

**Comment by Reprevise** [comment]
I can only reproduce this on iOS 17.5. On iOS 17.3, it doesn't happen. (I don't have access to a iOS device on 17.4) I get the crash a second after I close an interstitial ad. I'm on Flutter 3.22.2.

**Comment by dev3-tech** [comment]
in my project, when user goes to background i navigate user to lock screen for security and when user come back to app then i display app open ad and after closing ad user will see lock screen and user can enter app again by valid password in lock screen.
when i removed navigate to lock screen in AppLifecycleState.paused it works fine.

**Comment by huycozy** [comment]
I tried commenting out these lines of code inside `AppLifecycleState.paused` callback and still see the app is terminated as well. And the same result on a simpler app with Text only (without implementing app lifecycle listener).

Result: 

```console
Xcode build done.                                           27.7s
Connecting to VM Service at ws://127.0.0.1:53853/QFf1_6K_7bk=/ws
Lost connection to device.

Exited
```

But I couldn't get the crash trace as reported. Can you share how does it come? Is it printed out in the output console or from XCode? And can you also try on a newly created Flutter project to confirm if you see the same crash trace?

**Comment by dev3-tech** [comment]
it only shows in xcode and when this exception occurs, app got freeze.
![Screenshot 2024-07-15 at 2 54 34 PM](https://github.com/user-attachments/assets/be911140-1ee0-4cb9-83a0-ff1dc020f987)

**Comment by huycozy** [comment]
So, are you running app from XCode but not with Flutter command or VSCode/Android Studio? I tried running app from XCode but couldn't see the crash. It navigates to a new screen after I bring it back to the foreground. 

I see you are using an old Flutter version, can you try upgrading to the latest stable 3.22.2 and confirm if the crash persists or not? And please provide device info as well (OS, model) Thanks!

**Comment by dev3-tech** [comment]
i just replaced "push to new screen" in paused lifecycle with "overlayentry" and issue is solved.
e.g. 
Navigator.of(context).push(
            MaterialPageRoute(
              fullscreenDialog: true,
              builder: (_) {
                return LockScreen();
              },
            ),
          );

replaced with 

  navigatorKey.currentState?.overlay?.insert(OverlayEntry(
    builder: (_) => LockScreen(isResumed: true),
  ););

**Comment by huycozy** [comment]
Glad you found a workaround, but if you persist with this bug report. Please help to clarify the issue by checking these (as I can't reproduce the crash with the given stack trace on my end):

- Does the issue occur without using `flutter_inappwebview` or `webview_flutter` package? (to narrow the scope of issue down into a minimal sample code). If the issue can be reproduced without any packages, it's likely an issue with Navigator instead. 
- Does the issue only occur on iOS or also occurs on Android platform as well?

**Comment by dev3-tech** [comment]
as i added firebase_crashlytics in my app, this issue is occuring in ios 65% with flutter_inappwebview and 35% at other places. but i tested in 5 to 6 ios devices and last i found this exception in my device when i use inappwebview after 8 to 10 days by continuous testing for whole day. i also tried to regenerate to other place in my app where crashlytics logs shows last screen but it never regenerated.

so i think this is random crash for ios devices.
I think there are 3 possibilities.
1.  issue in third party library.
2. issue in flutter app lifecycle.
3. issue in flutter navigator when used in app lifecycle callback.

this issue found in ios and i never check with android.

this is the app and you can try crash steps in your device.
https://apps.apple.com/us/app/calculator-lock-secure-vault/id6446200267

**Comment by danagbemava-nc** [comment]
Hi @dev3-tech, curious, what version(s) of iOS are you seeing this crash on? Also, you may want to report this issue on the inappwebview plugin repository, since a majority of your crashes appear to be coming from that side.

**Comment by dev3-tech** [comment]
Devices:
iPhone 13, iPhone 11, iPhone 6s, iPhone 7, iPhone 11 Pro Max, iPhone XS, iPhone 8, iPhone 14, iPhone 15 Pro Max, iPhone XR, iPhone 15, iPhone 12, iPhone 7 Plus, iPhone 13 Pro Max, iPhone 6s Plus, iPhone 15 Plus, iPhone 12 Pro Max

os versions:
17.5.1 ,17.4.1 ,14.6.0 ,15.8.2 ,14.3.0 ,17.2.1 ,14.7.1 ,14.4.1 ,17.3.1 ,14.8.1 ,18.0.0 ,17.3.0 ,16.6.0 ,15.8.0 ,15.0.1 ,15.7.2 ,14.5.0 ,14.4.0 ,13.5.1 ,17.5.0 ,16.7.0 ,16.4.1 ,15.7.6 ,15.6.1 ,14.4.2 ,17.0.2 ,16.6.1 ,16.5.1 ,15.8.1 ,15.7.9 ,15.7.8 ,15.7.0 ,15.0.2 ,14.1.0 ,12.5.7 ,12.5.5 ,12.5.1

i regenerated issue in my iphone 11 with os 17.4.1.
 
i already reported this issue on flutter_inappwebview plugin repository but i didn't get any response yet.

**Comment by danagbemava-nc** [comment]
Hi @dev3-tech, I can't seem to reproduce this on my iPhone XS running iOS 17.5.1. Does it always crash immediately for you? Have you already upgraded to stable 3.22.2 and tried again to see if you still experience this issue?

**Comment by dev3-tech** [comment]
i already tried all version from 3.19.0 to 3.22.2 but still got this crash.

**Comment by huycozy** [comment]
@dev3-tech Since the crash happens randomly and with a third-party dependency (flutter_inappwebview) and there is also no Flutter trace for us to investigate this issue, I would suggest:
- Elevating the issue you reported on `flutter_inappwebview` repository and waiting for their feedback
- Since you can see this crash on your side, let's try replacing `flutter_inappwebview` with `webview_flutter` to see if the same crash occurs or not. If it also occurs, please try to get the complete crash stack trace (include Flutter trace) and share it here.

**Comment by dev3-tech** [comment]
ok. i'm waiting for feedback from flutter_inappwebview.
