### ISSUE TITLE
Dependency on an initialized instance of a MojoShell on the embedder breaks iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1516]
Just tried the latest game with the latest flutter engine. Got this error right after the game attempted to start. All I see on my ipod touch is a white screen.

![screen shot 2016-02-01 at 4 45 36 pm](https://cloud.githubusercontent.com/assets/5479/12736236/591e9472-c903-11e5-9d24-5fe5b7692fe2.png)

```
~/Code/game[master] $ flutter --version
Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: 3094348ad436fa4b7323a8afb4022867ad7fbe62 (37 minutes ago)
engine revision : 7bce54b79ef9ee57999cc8e258d664a88723d56d
```

**Comment by sethladd** [comment]
cc @vlidholt

**Comment by chinmaygarde** [comment]
What does `flutter logs` say right before it crashes?

**Comment by sethladd** [comment]
I'm running the game via xcode with the "play" button. Where can I see the logs? Or, should I also run `flutter logs` right after I press "play" ?

**Comment by eseidelGoogle** [comment]
Would be useful if we had `flutter version` or some command dump more information about the attached devices.  @devoncarew.  In this case, I'm asking myself what version of iPod Touch this is, and is it 32-bit, for example.  Filed https://github.com/flutter/flutter/issues/1519

**Comment by eseidelGoogle** [comment]
I wonder if we should distribute Debug versions of the engine.  It should be trivial to do that (particularly on our sparkely-new, totally-vaporware-but-definitely-not-overhyped infrastructure. :p) from a bot perspective, would just require some plumbing on the flutter tool side.

**Comment by chinmaygarde** [comment]
> I wonder if we should distribute Debug versions of the engine. It should be trivial to do that (particularly on our sparkely-new, totally-vaporware-but-definitely-not-overhyped infrastructure. :p) from a bot perspective, would just require some plumbing on the flutter tool side.

I will stop stripping the release the binary so we can get better stack traces for now

**Comment by sethladd** [comment]
This was an engine/mojo issue, yes? From another email:

"The recent Mojo SDK roll seems to have added a dependency on an initialized instance of a MojoShell on the embedder.  The MojoShell is only available on Android."

**Comment by chinmaygarde** [comment]
Yes. I am investigating this now

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/game/pull/49

**Comment by sethladd** [comment]
Thanks!!
