### ISSUE TITLE
Wrong code given

### ISSUE THREAD

**Issue by kpldvnpne** [flutter/flutter#15163]
Go to <a href="https://flutter.io/cookbook/lists/horizontal-list/">Create a horizontal list</a>

Under the 'Complete Example', code is same as that for <a href="https://flutter.io/cookbook/lists/basic-list/">Create a basic list</a>, but should have been updated for Horizontal List.

It's not a major issue, and I don't think anybody would ever be fooled by it. But it is still an error, and should be fixed.

P.S. I don't know it this is the right repo for posting errors like this.

**Comment by DanTup** [comment]
(cc @brianegan)

**Comment by brianegan** [comment]
Thanks! Must have missed this one, but the issue was fixed a while back.
