### ISSUE TITLE
Post-submits for Flutter Stable 3.22.3 engine commit initially ran with main branch recipes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#151695]
For the engine PR: https://github.com/flutter/engine/pull/53686

...in post-submit, the top-level `Linux engine_release_builder` build: https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20engine_release_builder/973/infra

...ran with the main branch recipe bundle, and thus excluded this fix: https://flutter-review.googlesource.com/c/recipes/+/58340
https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20Production%20Engine%20Drone/37641/infra

...and thus scheduled this sub-build with the default 1 hr timeout: https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20Production%20Engine%20Drone/37641/infra

...causing it to timeout, because of https://github.com/flutter/flutter/issues/151249

**Comment by jason-simmons** [comment]
The top-level build is run using the `release/release_builder` recipe.

(see https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/release/release_builder.py)

The top-level LUCI job obtains the source for the `release/release_builder` recipe from the `main` branch of `flutter.googlesource.com/recipes` (even if the job will be building a release from different branch).

The `RunSteps` logic in `release_builder.py` schedules steps based on the `ci.yaml` file.  If the target in `ci.yaml` contains a `timeout` field, then `_schedule_with_bb` in `recipe_modules/shard_util/api.py` will use that timeout as the number of minutes for the child Buildbucket task.

(see https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/shard_util/api.py#403)

The top-level job's `ci.yaml` can be seen at:
https://logs.chromium.org/logs/dart-internal/buildbucket/cr-buildbucket/8742580605321219345/+/u/read_ci_yaml/yaml

The `linux_fuchsia` target in `ci.yaml` specifies `timeout: 60`.  So the `linux_fuchsia` job stopped waiting for its children after 60 minutes.

**Comment by christopherfujino** [comment]
closing as WAI (at least for now)
