### ISSUE TITLE
Flutter : Test Drive

### ISSUE THREAD

**Issue by vrajjshah** [flutter/flutter#15167]
## Steps to Reproduce

while running the app in android studio I get this - 
Launching lib\main.dart on Nexus 6P in debug mode...
Initializing gradle...
Resolving dependencies...
Finished with error: 

* Error running Gradle:
Unable to download needed Android SDK components, as the following licenses have not been accepted:
Android SDK Build-Tools 26.0.2

To resolve this, please run the following command in a Terminal:
flutter doctor --android-licenses

after I run this comman in terminal -

C:\Users\vrajs>flutter doctor --android-licenses
sdkmanager --version failed: 1
## Logs

C:\Users\vrajs\AndroidStudioProjects\mind_spark>flutter analyze
Analyzing C:\Users\vrajs\AndroidStudioProjects\mind_spark...
No issues found!
Ran in 8.9s

## Flutter Doctor
C:\Users\vrajs>flutter doctor -v
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
    • Flutter version 0.1.5 at C:\Vraj\GitTrial\flutter
    • Framework revision 3ea4d06340 (11 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\vrajs\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • Nexus 6P • 8XV7N16128002032 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by biklas7** [comment]
Do you have Android SDK Build-Tools 26.0.2 installed?

**Comment by vrajjshah** [comment]
Thanks. It was not installed( different version was). Issue is solved

**Comment by DanTup** [comment]
> Do you have Android SDK Build-Tools 26.0.2 installed?

@mit-mit @devoncarew Is something missing from `doctor` here? Seems to suggest android toolchain is good, but the error from Gradle and the response suggest that it was not?

**Comment by mit-mit** [comment]
It's hard for doctor to check for that: The particular version of Build Tools to use is *project* specific based on what is stated in the gradle build file.
