### ISSUE TITLE
Build all examples on Travis & AppVeyor

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15164]
One of the the things that bit us during the beta 1 launch was not having Travis and AppVeyor build the gallery on the dev branch.  This has since been fixed for the gallery on Travis, but in order to ensure that all of our examples build in all environments, it'd be good to wire up builds of all examples on both Travis and AppVeyor.

/cc @mit-mit

**Comment by digiter** [comment]
Triage: we don't use Travis and AppVeyor anymore.
