### ISSUE TITLE
[ios]Make "Flutter for SwiftUI developers" up to date with iOS 18

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#151797]
Website: https://docs.flutter.dev/get-started/flutter-for/swiftui-devs

it was still iOS 16 when we wrote it. The SwiftUI part is 2 years outdated. 

Similar to https://github.com/flutter/flutter/issues/150945

**Comment by jmagman** [comment]
@hellohuanlin can you refile this with the website issue tracker https://github.com/flutter/website/issues/new/choose?
I would transfer it but we should use the preferred template.

**Comment by hellohuanlin** [comment]
Closed for https://github.com/flutter/website/issues/10902
