### ISSUE TITLE
Selecting an option in Autocomplete should not set the display string

### ISSUE THREAD

**Issue by vsaase** [flutter/flutter#151732]
https://github.com/flutter/flutter/blob/82b63ff27d7a15581837c84ca9304d3023934545/packages/flutter/lib/src/widgets/autocomplete.dart#L385

I understand the displayStringForOption function to only be for displaying the options, not modifying the option when setting the field value.

**Comment by darshankawar** [comment]
Thanks for the report @vsaase 
Can you please elaborate by providing current behavior as compared to expected ? A code snippet would also be useful highlighting current behavior.
