### ISSUE TITLE
What is hitting 'GET /flutter_service_worker.js'?

### ISSUE THREAD

**Issue by gmlewis** [flutter/flutter#151719]
I'm doing Chrome web development with WebGPU and am running a Python3 dev server like this and I get the following messages:

```bash
$ flutter doctor -v
-bash: flutter: command not found
$ python3 -m http.server 8080
::1 - - [13/Jul/2024 15:38:10] code 404, message File not found
::1 - - [13/Jul/2024 15:38:10] "GET /flutter_service_worker.js?v=2180655971 HTTP/1.1" 404 -
::1 - - [13/Jul/2024 15:43:40] code 404, message File not found
::1 - - [13/Jul/2024 15:43:40] "GET /flutter_service_worker.js?v=2180655971 HTTP/1.1" 404 -
::1 - - [13/Jul/2024 15:49:10] code 404, message File not found
::1 - - [13/Jul/2024 15:49:10] "GET /flutter_service_worker.js?v=2180655971 HTTP/1.1" 404 -
```

I'm not currently using Flutter and it is not installed on my system.

The development I'm doing has nothing to do with Flutter, yet these requests keep hitting my dev server.
Any ideas what might be hitting this endpoint?
`ps ux | grep flutter` shows nothing.

This is a Mac M2 Max running Sonoma 14.4.1.
Thank you!

**Comment by jonahwilliams** [comment]
Just a guess, you ran/installed a flutter web app service worker on localhost. You're serving a different app, but since the service worker is installed on localhost it still tries to activate. The fix is to go into the service worker menu and uninstall

**Comment by gmlewis** [comment]
Thank you, @jonahwilliams !  That was it!

For those who find this issue in the future:
* open up your Chrome DevTools
* click on "Application"
* click on "Service workers"
* find the service workers you wish to unregister, and click "unregister" for each one.

![application-service-workers-2024-07-13_22-16-17](https://github.com/user-attachments/assets/c96233df-28bc-48cd-8b04-c6a11126987b)

Closing as resolved.
