### ISSUE TITLE
plugin_test_ios flaky in try pool but not in prod pool

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#151772]
Lots of timeouts in the try pool: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20plugin_test_ios?limit=200

But the prod pool looks fine: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20plugin_test_ios

**Comment by jmagman** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/150642#issuecomment-2228950616.
