### ISSUE TITLE
[dart2wasm] `PointerInterceptor` widget does not behave as intended

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#151793]
When a widget, like a dialog for example, is wrapped in a `PointerInterceptor` widget from `package:pointer_interceptor`, clicks to   this `PointerInterceptor` should not be swallowed by the `HtmlElementView`s underneath. This is WAI on dart2js but not on dart2wasm.

CC @eyebrowsoffire

**Comment by eyebrowsoffire** [comment]
I think this should be resolved after https://github.com/flutter/flutter/issues/152139. @kenzieschmoll can you confirm?

**Comment by kenzieschmoll** [comment]
Confirmed this is resolved on

```
Flutter 3.24.0-1.0.pre.441 • channel master • git@github.com:flutter/flutter.git
Framework • revision 0e720e84a4 (2 days ago) • 2024-08-05 14:56:14 +0100
Engine • revision 0aac603420
Tools • Dart 3.6.0 (build 3.6.0-114.0.dev) • DevTools 2.38.0
```
