### ISSUE TITLE
the more info about measure text

### ISSUE THREAD

**Issue by SpringSea28** [flutter/flutter#151701]
### Use case

I would like to know the width and height of "aaaaa" in the following picture, excluding the blank areas above and below.
![微信截图_20240713135454](https://github.com/user-attachments/assets/f29ddf5f-30cf-47b1-908c-b9766e1b3c77)
![微信截图_20240713135506](https://github.com/user-attachments/assets/ab4dd3cb-21f2-4ab2-a815-79f464cfb8a9)

I need to achieve the effect below, so that the blue box just includes the “aaaaa” text part, with no blank space above and below.
![微信图片_20240713135515](https://github.com/user-attachments/assets/4fb7fe9b-de26-44c8-a4a8-10014789fba3)

### Proposal

Skia has an API for measuring text, which can obtain the width and height information of text excluding the upper and lower blank areas. Can the upper layer of Flutter provide a corresponding API?
![微信图片_20240713140427](https://github.com/user-attachments/assets/52e9e575-abec-4361-a3af-429bb33cf255)

**Comment by huycozy** [comment]
Hi @SpringSea28, this is similar to the request you asked at https://github.com/flutter/flutter/issues/150971 so I will close this in favor of that one. The team already looked at that issue so please be patient and follow it for updates. Thank you!
