### ISSUE TITLE
The description of WidgetStateColor is mixed into the WidgetStateTextStyle document.

### ISSUE THREAD

**Issue by croro613** [flutter/flutter#151710]
It appears that a part of the WidgetStateColor description has been copied and pasted into the WidgetStateTextStyle description by mistake.

In the following document, for example, it says "~~~ to resolve the `color` in the given states.", but It should actually be "~~~ to resolve the `text style` in the given states."
![スクリーンショット 2024-07-13 20 52 14](https://github.com/user-attachments/assets/1a9b8299-f40a-44c2-b5a3-f8987bc47297)
https://api.flutter.dev/flutter/widgets/WidgetStateTextStyle-class.html

**Comment by croro613** [comment]
If it's okay, I'd like to fix this. This would be my first contribution.

**Comment by danagbemava-nc** [comment]
Hi @croro613, contributions are always welcome. Please make sure to read our contributing guide https://github.com/flutter/flutter/blob/main/CONTRIBUTING.md
