### ISSUE TITLE
`local_auth` plugin having crash in Xiaomi Redmi note 5

### ISSUE THREAD

**Issue by lokesh-univest** [flutter/flutter#151747]
### Steps to reproduce

When in am calling `await localAuthentication.authenticate(` function it's crash in above device. And this device support biometric local auth. Device android version is 8.1.0

### Expected results

Working fine in all devices.

### Actual results

`local_auth` plugin having crash in Xiaomi Redmi note 5

### Code sample

<details open><summary>I am using following code for local auth</summary>

```dart
authenticated = await localAuthentication.authenticate(
        localizedReason: 'Univest',
        options: const AuthenticationOptions(
          sensitiveTransaction: true,
          useErrorDialogs: true,
          stickyAuth: true,
        ),
      );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @lokesh-univest, I don't have such a device so I can't check this on my end. For others to investigate this later, can you provide the following info?

- Please provide the crash stack trace
 - What is the current package version of `local_auth`? (you can check it from `pubspec.lock` file since it's the fetched version the app is using)
 - Can you confirm this with [package example](https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth/example)? (to make sure the crash is not affected by other factors like 3rd party package integration or user's code implementation, etc)

**Comment by lokesh-univest** [comment]
1. I am not able to get crash stack trace because it's come in one of my users mobile.
2. I am using local_auth: ^2.2.0
3. Code which i am using in my app:

```
enum LocalAuthSupportState {
  unknown,
  supported,
  unsupported,
}

class LocalAuthHelper {
  LocalAuthentication localAuthentication = LocalAuthentication();
  LocalAuthSupportState supportState = LocalAuthSupportState.unknown;

  Future<void> deviceSupportLocalAuth() async {
    bool supportStateStatus = await localAuthentication.isDeviceSupported();
    supportState = supportStateStatus
        ? LocalAuthSupportState.supported
        : LocalAuthSupportState.unsupported;
    print("LOCAL_AUTH -> $supportState");
  }

  Future<bool> authenticate() async {
    bool authenticated = false;
    try {
      authenticated = await localAuthentication.authenticate(
        localizedReason: '--',
        options: const AuthenticationOptions(
          sensitiveTransaction: true,
          useErrorDialogs: true,
          stickyAuth: true,
        ),
      );
      print("LOCAL_AUTH -> authenticated $authenticated");
      return authenticated;
    } on PlatformException catch (e) {
      print("LOCAL_AUTH -> Error in local auth authenticate -> $e");
      cancelAuthentication();
    }
    print("LOCAL_AUTH -> authenticated $authenticated");
    return authenticated;
  }

  Future<void> cancelAuthentication() async {
    await localAuthentication.stopAuthentication();
  }
}
```

**Comment by huycozy** [comment]
Without error stack trace, we are not sure where the issue comes from in the package code. You should try to ask user to provide it or replicate it on your side that would be helpful in debugging the issue.
