### ISSUE TITLE
[webview_flutter] Alert of website is not showing on IOS

### ISSUE THREAD

**Issue by sagarappscrip** [flutter/flutter#151753]
### What package does this bug report belong to?

webview_flutter

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

Alert of website is not showing in IOS webview. In android it is working.

Note - 

1. Run the given code 
2. Click on the menu button on top left corner
3. CLick to EVENTS option available there
4. In android you will see aalert pop up.
5. In IOS it is not working.

### Expected results

![WhatsApp Image 2024-07-15 at 6 22 32 PM](https://github.com/user-attachments/assets/081a2731-d0fd-4f4f-bd0d-bffab648fb79)

### Actual results

In IOS the alert pop up is not coming.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late WebViewController controller;

  @override
  void initState() {
    super.initState();
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..enableZoom(true)
      ..loadRequest(
        Uri.parse(
            'https://ccapp.foretees.com/v5/demolarry_dining_m64/Dining_slot_v2?action=new&dc=06c55217740584a22bf0d7a5a5ea69fd91c5a5bb5cf7211f90f87f03dec6825c&mid=1478&cid=270'),
      );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: Text(
          widget.title,
          style: TextStyle(color: Colors.white),
        ),
      ),
      body: WebViewWidget(
        controller: controller,
      ),
    );
  }
}

```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @sagarappscrip 

>CLick to EVENTS option available there

Can you share the script runs when clicking on this option? Does it call `alert` function? If so, it's implemented here at https://github.com/flutter/packages/pull/5670. We need to find out what web code is not running beneath.

You can also try to simulate this with a simpler case where you host the web containing that script (the part of clicking Events option only) and open it on iOS's Safari browser to see if it works.

**Comment by sagarappscrip** [comment]
@huycozy 
Currently I don't have the scripts running behind.
And In Safari, It is working fine. 
Any solutions to make it work??

**Comment by huycozy** [comment]
I tried loading your page with a simple iOS SwiftUI code as below and see the alert is not displayed as well:

<details>
<summary>Sample code (iOS SwiftUI)</summary>

```swift
import SwiftUI
import WebKit

struct ContentView: View {
    var body: some View {
        WebView()
    }
}

struct WebView: UIViewRepresentable {
    let webView: WKWebView
    
    init() {
        webView = WKWebView(frame: .zero)
      
    }
    
    func makeUIView(context: Context) -> WKWebView {
        return webView
    }
    func updateUIView(_ uiView: WKWebView, context: Context) {
        webView.load(URLRequest(url: URL(string: "https://ccapp.foretees.com/v5/demolarry_dining_m64/Dining_slot_v2?action=new&dc=06c55217740584a22bf0d7a5a5ea69fd91c5a5bb5cf7211f90f87f03dec6825c&mid=1478&cid=270")!))
    }
}
```
</details>

But I see there are some hacky solutions with WKWebView's delegate at [this SO thread](https://stackoverflow.com/questions/34185339/wkwebview-javascript-confirm-and-alert-not-working/34759503#34759503) that may work (I haven't tried it, so you can try implementing to see if one of those answers can work or not).

For Flutter webview package side, I confirm that the alert is not displayed on iOS platform. Keeping this issue open for other's input. The current package version: `webview_flutter: ^4.8.0`, `webview_flutter_wkwebview: ^3.14.0`. 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by stuartmorgan** [comment]
> And In Safari, It is working fine.

WKWebView and Safari don't have the same behaviors; WKWebView does not include built-in support for `alert`. If you want to show alerts in your application, you need to use `PlatformWebViewController.setOnJavaScriptAlertDialog` to add your own handler, and display the alert accordingly.

Closing as this is a difference in platform webview behaviors, rather than a bug, and we expose the API necessary for handling alert.

**Comment by sagarappscrip** [comment]
@stuartmorgan I don,t want to add the alert from flutter side. It is already there in the website. So how to do it.

**Comment by stuartmorgan** [comment]
> I don,t want to add the alert from flutter side. It is already there in the website.

I think you are conflating the call to the JS `alert` function with the actual creation and display of UI. A website calling `alert` does not itself display anything, it is just requesting that the user agent do so.

In this context, the UA is the combination of WKWebView and your application. Apple chose not to handle `alert` in WKWebView by displaying UI, and instead to provide hooks to the client application to handle `alert` calls using the method of their choice. `webview_flutter` wraps that API surface, allowing you to receive the delegation in Dart code and handle it however you want, just as a non-Flutter app using WKWebView would.

> So how to do it.

Please see my previous comment.

**Comment by stuartmorgan** [comment]
Sorry, that's the wrong layer's API; you would call `WebViewController.setOnJavaScriptAlertDialog`. (I've fixed my earlier comment to avoid confusing others who may find this thread.)

**Comment by sagarappscrip** [comment]
Thanks. I got it but what should I pass in this function to access the web alert dialog. How to force the web to show the alert??

**Comment by stuartmorgan** [comment]
I'm not sure what you mean by "the web alert dialog". If a web site were showing its own dialog via HTML, it wouldn't be calling `alert`.

When you are using, e.g., Safari, the dialog you see when a web page calls `alert` is created and displayed by Safari, not by "the web". If you want to display a dialog in your app when a site calls `alert`, you need to create and display a dialog in the handler function you set.
