### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by vyaspm91** [flutter/flutter#151877]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --flavor prod_app --debug --dart-define=flutter.inspector.structuredErrors=true lib/prod_main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 14.4.1 23E224 darwin-x64, locale en-IN)
    • Flutter version 2.10.5 at /Users/pratikmvyas/fvm/versions/2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 years, 3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/pratikmvyas/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/local/Cellar/openjdk@11/11.0.20/libexec/openjdk.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 11.0.20+0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 126.0.6478.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.86.0+434
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
android_intent_plus-3.1.9
app_settings-4.1.6
appcheck-1.0.6
bluetooth_enable-0.1.1
bonsoir-1.0.1+2
cloud_firestore_web-2.8.10
connectivity_plus-2.3.9
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.6
connectivity_plus_web-1.2.5
connectivity_plus_windows-1.2.2
device_info_plus-4.0.0
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
esp_blufi
esp_provisioning-1.0.0+6
firebase_core-1.24.0
firebase_core_web-1.7.3
firebase_crashlytics-2.9.0
firebase_dynamic_links-4.3.5
firebase_messaging-13.1.0
firebase_messaging_web-3.2.0
flutter_ble_lib-2.3.2
flutter_email_sender-6.0.1
flutter_exit_app-1.1.2
flutter_image_compress-1.1.3
flutter_inappwebview-5.6.0+2
flutter_mdns_plugin-0.0.3
flutter_native_timezone-2.0.0
flutter_nsd-1.4.0
flutter_plugin_android_lifecycle-2.0.7
fluttertoast-8.2.2
image_picker-0.8.6+1
image_picker_android-0.8.5+5
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+6
image_picker_web-2.1.1
in_app_purchase-3.1.1
in_app_purchase_android-0.2.3+9
in_app_purchase_storekit-0.3.4+1
location-4.4.0
location_web-3.1.1
network_info_plus-2.3.2
network_info_plus_linux-1.1.2
network_info_plus_macos-1.3.0
network_info_plus_web-1.0.1
network_info_plus_windows-1.0.2
nsd-1.5.6
nsd_android-1.2.2
nsd_ios-1.0.3
nsd_macos-1.0.3
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-1.0.5
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.7
path_provider_windows-2.0.7
pdf_viewer_plugin-2.0.1
permission_handler-8.3.0
qr_code_scanner-0.7.0
share_plus-4.5.3
share_plus_linux-3.0.1
share_plus_macos-3.0.1
share_plus_web-3.1.0
share_plus_windows-3.0.1
shared_preferences-2.0.17
shared_preferences_android-2.0.15
shared_preferences_foundation-2.1.2
shared_preferences_linux-2.1.3
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.3
smart_auth-1.1.1
sqflite-2.0.2+1
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.1.8
url_launcher_android-6.0.23
url_launcher_ios-6.0.18
url_launcher_linux-3.0.2
url_launcher_macos-3.0.2
url_launcher_web-2.0.14
url_launcher_windows-3.0.2
video_player-2.5.1
video_player_android-2.3.10
video_player_avfoundation-2.3.8
video_player_web-2.0.13
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.8.0
webview_flutter_android-2.8.14
webview_flutter_wkwebview-2.7.5

**Comment by danagbemava-nc** [comment]
Hi @vyaspm91,
You are on very old version of the framework. The reported issue is already fixed on recent versions, so please upgrade to latest stable and run your scenario again which shouldn't throw the tool crash.
Closing, as this is already fixed.
