### ISSUE TITLE
share button appears when double tap on the screen

### ISSUE THREAD

**Issue by Noa3ka** [flutter/flutter#151865]
### Steps to reproduce

1. run the attached code on mobile-web platform (currently using safari)
2. double tap any where on the screen and leave the finger pressed 

### Expected results

do nothing

### Actual results

magnifying glass activated
share button appears in the left corner of the screen
unable to dismiss the share button

<img src="https://github.com/user-attachments/assets/96b43523-dd65-4cda-8f7e-d71b02b71fae" width="300"/>

### Code sample

<details open>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final TextEditingController _controller = TextEditingController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Container(
          width: 200,
          height: 200,
          color: Colors.amber,
        )
      ),
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
This is not specific to flutter. I tested a blank html page in safari and the same behaviour was observed. This is likely a safari issue. With chrome on iOS you get a create link button. Firefox focus does not show anything. I observed the same behaviour from the flutter apps in these browsers with the blank html page (i,e flutter and the html page shared the same behaviour). 

As this happens with a blank HTML page, this can be classified as browser behaviour as opposed to a bug in flutter. As such I'll be closing this issue. Thank you

The html code used is pasted below in case you want to try this for yourself. 

<video src="https://github.com/user-attachments/assets/4bc0c935-cd12-40e3-a916-6bc6394c19dd" />


<img src="https://github.com/user-attachments/assets/3bc5cbfe-0e5e-46f8-adc6-5aaaae10b8d1" width="300"/>

<details>
<summary>html code</summary>

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
    </head>

    <style>
        body {
            background-color: #f0f0f0;
        }

        .container {
            width: 100;
            height: 100;
            display: block;
            color: red;
        }
    </style>
    <body>

        <div class="container">
            <div></div>
        </div>
    </body>
</html>
```
</details>
