### ISSUE TITLE
Screen reader is ignoring the obscured property. 

### ISSUE THREAD

**Issue by azizChebbi** [flutter/flutter#151817]
### Steps to reproduce

look to the code example.

### Expected results

when using screen reader, the password field shouldn't be read outloud as the obscured field is true.

### Actual results

Obscured is getting ignored by screen readers.

### Code sample

```
Widget textFieldSemantics({bool isDate = false}) {
    String? value = (isDate && this.value != null)
        ? formatDateToNaturalLanguage(this.value!)
        : (isPassword == true ? '' : this.value);
    return Semantics(
      textField: true,
      readOnly: isDisabled,
      obscured: isPassword,
      multiline: isArea,
      maxValueLength: maxLength,
      label: getLabel(),
      value: value,
      textDirection: ui.TextDirection.ltr,
      sortKey: sortKey,
      child: child,
    );
  }``
```

### Flutter Doctor output

[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880], locale en-GB)
    • Flutter version 3.22.2 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\mohamedaziz.chebbi\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\mohamedaziz.chebbi\AppData\Local\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34723.18
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\mohamedaziz.chebbi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (4 available)
    • M2101K7AG (mobile) • 331187f2 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 126.0.2592.102

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by azizChebbi** [comment]
the platform for this is mobile.
when it get to the password field, even with `obscured: true`, it reads the value property passed to the Semantic Widget, which should be hidden from screen readers.

**Comment by darshankawar** [comment]
@azizChebbi 
With below code sample, running on Android S10+ device, with talkback ON, it reads the textfield which is obscured, as:

```
home: Scaffold(
          body: Center(
              child: Semantics(
                textField: true,
                obscured: true,
                child: TextField(
                  obscureText: true,
                ),
              )
          )
      ),
```

`password, 4 characters, edit box`

What's the behavior in your case using above code ?

**Comment by azizChebbi** [comment]
thank you @darshankawar for being helpful.
this is the actual code I'm using:
```
Widget textFieldSemantics({bool isDate = false}) {
    String? value = (isDate && this.value != null)
        ? formatDateToNaturalLanguage(this.value!)
        : this.value;
    return Semantics(
      textField: true,
      readOnly: isDisabled,
      obscured: isPassword,
      multiline: isArea,
      maxValueLength: maxLength,
      label: getLabel(),
      value: value,
      textDirection: ui.TextDirection.ltr,
      sortKey: sortKey,
      child: child,
    );
  }
```

the thing is that the `value` property is getting read by screen reader, but it shouldn't because `obscure:true` (in case of password field).

**Comment by darshankawar** [comment]
I tried but can't seem to replicate with it. What device are you seeing this on ?
