### ISSUE TITLE
Feature: flutter_secure_storage

### ISSUE THREAD

**Issue by frankteller-de** [flutter/flutter#151825]
### Use case

No access to the data in the secure key value storage.

[Message: The specified item already exists in the keychain, IOS](https://github.com/mogol/flutter_secure_storage/issues/711)

### Proposal

flutter_secure_storage is an essential security feature of flutter. In the current version, serious errors can occur which lead to high user losses. 

My question would be whether this package should be included in flutter so that more people can keep an eye on the code.

**Comment by stuartmorgan** [comment]
> ### Use case
> No access to the data in the secure key value storage.
> 
> [Message: The specified item already exists in the keychain, IOS](https://github.com/mogol/flutter_secure_storage/issues/711)

This appears to be a description of a bug in third-party package; a use case would be a high-level description of something that you are trying to accomplish in an application. In the future please provide an actual use case when filing a proposal.

> My question would be whether this package should be included in flutter so that more people can keep an eye on the code.

You've linked to a package that is open source; anyone can read all the code already, and based on the discussion there it appears that at number of people are doing so, as well as providing PRs. If the Flutter team were to fork that plugin, thus splitting the user base, the result would be fewer people looking at, and contributing to, each individual fork.

Closing, as we have no plans to add a first-party plugin that covers the same use case as `flutter_secure_storage`:
- Having the Flutter team maintain all popular packages is infeasible, and there is nothing about secure storage that involves specific Flutter team expertise.
- Competing with an established, actively maintained plugin duplicates effort that can be better spent on existing first-party packages, and undermines the goal of creating a thriving package ecosystem.
