### ISSUE TITLE
Can not render text behind a container in a ListView.

### ISSUE THREAD

**Issue by PangPangPangPangPang** [flutter/flutter#15189]
## Steps to Reproduce
![image](https://user-images.githubusercontent.com/8207475/37011201-027f1f70-212a-11e8-9a69-60d88c6bc988.png)
It seems render correctly if text write before the red container.
 
![image](https://user-images.githubusercontent.com/8207475/37011238-3b8f1e32-212a-11e8-81cd-256c11cba38c.png)
But if the text write behind the red container, all the blue container dismiss.

**Comment by PangPangPangPangPang** [comment]
The bug dismiss if I remove the transition animition of this page.
![image](https://user-images.githubusercontent.com/8207475/37012697-eea4663e-2130-11e8-9a63-ea90cefb899b.png)

**Comment by Hixie** [comment]
Can you provide the source code of a short application that demonstrates this problem?
I don't understand exactly what you mean.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
