### ISSUE TITLE
DropdownMenu is showing black background when first opened on Linux (only on latest stable, in master it has been fixed it seems)

### ISSUE THREAD

**Issue by katronic-applications** [flutter/flutter#151893]
### Steps to reproduce

1. Open flutter project on linux
2. Click on DropdownMenu
3. Black square appears where you should see the options to choose from, it goes away once you hover over it

### Expected results

No black background

### Actual results

black background appears

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
Here is a photo, so you can see the problem:

https://github.com/user-attachments/assets/178c27a9-21a4-4fed-9912-bc2e091ecbcc

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@katronic-applications 
Can you provide a runnable code sample that shows the black background ?
I tried with official example running on desktop but it didn't replicate.
Also, if it doesn't replicate in master, then it is probably fixed and will be available in next stable release.

**Comment by katronic-applications** [comment]
I tried to reproduce it, but couldn't. I was thinking it had maybe something to do with the splash screen add on, or the dark theme. 
In the process of testing this, I upgraded flutter to 3.22.3 from 3.22.2 on the stable channel and this fixed it!

**Comment by darshankawar** [comment]
Closing as fixed.
