### ISSUE TITLE
Latin and cyrillic letters not showing in Http response body

### ISSUE THREAD

**Issue by Pyotex** [flutter/flutter#15186]
I have a backend that stores some locations. When i call a POST request
the json should look like this:
`{"location":"Karađorđeva 45"}`
But instead it looks like this:
`{"location":"KaraÄorÄeva 45"}`

I tried setting the encoding parameter multiple times, but that didn't help.
`var response = await http.post(
      Uri.encodeFull(Registry.BASE_URL + "/places/get-all-places/"),
      encoding: Encoding.getByName("utf-8"),
      headers: {
        "Accept": "application/json"
      }
    );`

I'm sure that I'm missing something. How can I fix this?
Thanks in advance!

**Comment by zoechi** [comment]
Using an UTF8 decoder like shown in https://stackoverflow.com/questions/27808848/retrieving-the-response-body-from-an-httpclientresponse might help

**Comment by Pyotex** [comment]
That worked, thank you so much!

**Comment by fmaylinch** [comment]
I also found this: https://stackoverflow.com/a/51370010/1121497

Use `json.decode(utf8.decode(r.bodyBytes))` instead of just `json.decode(r.body)`.

**Comment by Joluall** [comment]
You save my day bro
