### ISSUE TITLE
Inconsistent string interpolation in dart runtime with RTL languages

### ISSUE THREAD

**Issue by moshe5745** [flutter/flutter#151814]
### Steps to reproduce

```
void main() {
  // The bug
  var rtlLetter = "א";
  var enLetter = "A";
  var number = 1;

  var value1 = "${rtlLetter} - ${enLetter}";
  var value2 = "${rtlLetter} - ${number}"; 
  var value3 = "${number} - ${rtlLetter}";  //  <<< --- SAME RESULT EVEN IF CHANGE THE ORDER

  print(value1);  // א - A
  print(value2);  // א - 1      <<< ---------   HERE IS THE PROBLEM
  print(value3);  // א - 1      <<< ---------   SAME RESULT

  print("---------------------------------------");
  // Correct behavior with ltr language

  value1 = "${enLetter} - ${enLetter}";
  value2 = "${enLetter} - ${number}";

  print(value1);
  print(value2);
}

```

### Expected results

  print(value1);  // א - A
  print(value2);  // א - 1
  print(value2);  // א  and then 1

### Actual results

  print(value1);  // א - A
  print(value2);  // א - 1      <<< ---------   HERE IS THE PROBLEM
  print(value3);  // א - 1      <<< ---------   SAME RESULT

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.3 23D56 darwin-arm64, locale en-IL)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by darshankawar** [comment]
@moshe5745 
This is more suited in dart-lang repo, so please file the same there https://github.com/dart-lang/sdk/issues
Closing from here.
