### ISSUE TITLE
Flutter Style guide is buried in a strange place

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1518]
https://github.com/flutter/engine/blob/master/sky/specs/style-guide.md

Probably belongs in flutter/flutter/docs?

@Hixie

**Comment by Hixie** [comment]
Sure.

**Comment by Hixie** [comment]
Or the wiki. Or the website.

**Comment by qchong** [comment]
Fixed by Hixie@ in [PR #177](https://github.com/flutter/website/pull/177).

**Comment by qchong** [comment]
Marking as closed.
