### ISSUE TITLE
 After adding(or uploading) images, can't view selected images in gallery

### ISSUE THREAD

**Issue by Nandhini-GA** [flutter/flutter#151811]
### Steps to reproduce

I want to deselect images if I selected more than 4 images, here i can't go back gallery 

```
List<XFile?> imageFiles =  await picker.pickMultiImage();

if(imageFiles.length <= 4) {
  ///successfully uploaded images
} else{
  ///go back to gallery to deselect images until <= 4
}
```

### Expected results

 I want to go back to gallery to deselect selected images

### Actual results

currently i can't go back to gallery and can't see selected images

### Code sample

<details open><summary>Code sample</summary>

```dart

List<XFile?> imageFiles =  await picker.pickMultiImage();

if(imageFiles.length <= 4) {
  ///successfully uploaded images
} else{
  ///go back to gallery to deselect images until <= 4
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by darshankawar** [comment]
@Nandhini-GA 
You are on old version of stable and your question / issue is better suited for support channels like StackOverflow, so please ask the same there.
