### ISSUE TITLE
DropdownMenu menu doesn't follow widget

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#151856]
If you put a DropdownMenu in a scrollable, then cause the DropdownMenu widget to show its menu and then scroll the scrollable (e.g. using a trackpad), the menu doesn't follow the widget. It should use a LeaderLayer/FollowerLayer to follow the text field the same way the text field toolbar does.

(Testing on main, 3.24.0-1.0.pre.104, on macOS 14.2.1 23C71 darwin-arm64.)

**Comment by bleroux** [comment]
Reopening because https://github.com/flutter/flutter/pull/154667 was partially reverted.
See https://github.com/flutter/flutter/pull/158930 for details about the revert.
Marking this issue as P1 because will actively work on a fix.
