### ISSUE TITLE
The iOS TextField component cannot respond to the bug

### ISSUE THREAD

**Issue by mochen1995** [flutter/flutter#151943]
### Steps to reproduce

1. Implement a TextField component.
2. Run the project and enter a line of text in the TextField.
3. Double-click to select the text, and select multiple texts. Then click another area. Repeat the verification to reproduce.

### Expected results

TextField can respond normally

### Actual results

TextField component cannot respond

https://github.com/user-attachments/assets/25170e41-137d-40ac-9ab9-47db00378674

### Code sample

TextField( )

### Screenshots or Video

https://github.com/user-attachments/assets/52af059a-0ca7-4ef1-85a8-228af4687067

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.24.0-1.0.pre.133, on macOS 14.4.1 23E224
darwin-arm64, locale zh-Hans-CN)
! Warning: flutter on your path resolves to
/Users/mochen/Downloads/flutter2.0/bin/flutter, which is not inside your
current Flutter SDK checkout at
/Users/mochen/Downloads/fluttermaster/flutter. Consider adding
/Users/mochen/Downloads/fluttermaster/flutter/bin to the front of your
path.
! Warning: dart on your path resolves to
/Users/mochen/Downloads/flutter2.0/bin/dart, which is not inside your
current Flutter SDK checkout at
/Users/mochen/Downloads/fluttermaster/flutter. Consider adding
/Users/mochen/Downloads/fluttermaster/flutter/bin to the front of your
path.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
! Some Android licenses not accepted. To resolve this, run: flutter doctor
--android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] VS Code (version 1.66.0)
[✓] Connected device (5 available)
[✓] Network resources
```

</details>

**Comment by mochen1995** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.24.0-1.0.pre.133, on macOS 14.4.1 23E224
    darwin-arm64, locale zh-Hans-CN)
    ! Warning: `flutter` on your path resolves to
      /Users/mochen/Downloads/flutter2.0/bin/flutter, which is not inside your
      current Flutter SDK checkout at
      /Users/mochen/Downloads/fluttermaster/flutter. Consider adding
      /Users/mochen/Downloads/fluttermaster/flutter/bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to
      /Users/mochen/Downloads/flutter2.0/bin/dart, which is not inside your
      current Flutter SDK checkout at
      /Users/mochen/Downloads/fluttermaster/flutter. Consider adding
      /Users/mochen/Downloads/fluttermaster/flutter/bin to the front of your
      path.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] VS Code (version 1.66.0)
[✓] Connected device (5 available)
[✓] Network resources

**Comment by mochen1995** [comment]
doctor in comment

**Comment by mochen1995** [comment]
doctor in comment

**Comment by danagbemava-nc** [comment]
Hi @mochen1995, how many times do you repeat the process for the textfied to stop responding? 
Does this only happen with CJK characters? 
Do you get any errors in xcode that you can share with us? 
What version of iOS are you using?

**Comment by mochen1995** [comment]
> 你好@mochen1995，您重复该过程多少次，textfied 才会停止响应？ 这只发生在 CJK 字符上吗？ 您在 xcode 中遇到任何可以与我们分享的错误吗？ 您使用的是哪个版本的 iOS？

The number of times is not fixed. Sometimes after selecting the text for the first time, it will not respond. Sometimes you need to repeat it several times.
Not only CJK characters, I also use English characters and double-click to select text, and it will not respond.

I have verified that both 16.7.8 and 17.5.1 have issues with the iOS system version.

error info
```
When the exception was thrown, this was the stack: 
#2      BaseTapAndDragGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap_and_drag.dart:1017:14)
#3      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:169:27)
#4      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:505:20)
#5      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481:22)
#6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
#7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426:7)
#8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389:5)
#9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336:7)
#10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305:9)
#11     _invoke1 (dart:ui/hooks.dart:328:13)
#12     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#13     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
Event: PointerUpEvent#c1163(position: Offset(203.7, 315.0))
  position: Offset(203.7, 315.0)
Target: <WidgetsFlutterBinding>
```

**Comment by danagbemava-nc** [comment]
Hi @mochen1995, are you only experiencing this on iOS? I just tested on master `3.24.0-1.0.pre.197` but I can't seem to reproduce the issue. Can you upgrade to the latest master version to see if you still experience this issue?

**Comment by mochen1995** [comment]
> 你好@mochen1995，您只在 iOS 上遇到此问题吗？我刚刚在 master 上测试过`3.24.0-1.0.pre.197`，但似乎无法重现此问题。您可以升级到最新的 master 版本，看看是否仍会遇到此问题吗？

Thank you very much. I tested it with the latest master version 3.24.0-1.0.pre.197 and there is no such problem.
