### ISSUE TITLE
how listview gridview load more data!

### ISSUE THREAD

**Issue by sparksisnotspark** [flutter/flutter#15195]
How ListView and GridView load more dada!

**Comment by zoechi** [comment]
What I did is using `ListView.builder()` with a size bigger than the available items.
If `ListView.builder()` requests an item for an index that is not loaded, I return a dummy item that shows a loading spinner and invoke a request to the database. When the response from the database arrives I re-render (call `setState()`) and when `ListView.builder()` requests the index again, I can instead return an actual item because now it is available.
You can use a ScrollController with `ListView.builder()` to figure out scroll position, but here you also need the size of the list. I haven't tried to get that yet myself.

**Comment by AppleEducate** [comment]
I am very much interested in this. There is not much documentation on how to do this with loading data from a server.  All the tutorials talk about loading objects that are created.

**Comment by zoechi** [comment]
summon @brianegan

**Comment by brianegan** [comment]
Thanks for the feedback, everyone! I'll add this to my list of Recipes :) Please vote for this issue on the list here: https://github.com/flutter/flutter/issues/15297#issuecomment-377540849

The more thumbs I get, the higher priority it becomes!

**Comment by robinthomas** [comment]
I was able to get it to work, not a perfect method but it works, if it helps someone to perfect it...

you can get the initial idea from this page https://stackoverflow.com/questions/49508322/flutter-listview-lazy-loading, just like @zoechi had explained

extending the idea...

I receive the json data from a rest service with 20 rows, and i request the next (and the rest) page(s) with an offset of 19.

in the ListView.builder i check whether its the last item and if it is, i render a CircularProgressIndicator() instead, as i offset by 19 (one less that the page size), i get the last item i skipped rendering on the previous request as the next requests first item, and so on. 

Yes there is a data overhead, still trying to figure how to avoid it...

**Comment by zoechi** [comment]
@wilburt I'd say none of them. Either use `initState` or some user action like scroll or tap.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by AppleEducate** [comment]
I like to call my load more function on the ‘itemBuilder’ when the ‘index == items.length - 1’

Works for both gridview and list view!

**Comment by gratefulgirl** [comment]
Hi there
I don't know how to create a list view that loads a page at a time

**Comment by AppleEducate** [comment]
@gratefulgirl I created a plugin that is a paged list view for mobile and paged data table for tablets. Check it out and see if it can do what you need

**Comment by gratefulgirl** [comment]
Thanks . Who are you by the way 😏

**Comment by patelkrunal78** [comment]
Especially when the ListView has scrolled to the bottom, it still calls the scrollListener a couple of times. The better approach is to combine Notification Listener with Remi’s approach. Here is my solution:

https://icetutor.com/question/flutter-listview-lazy-loading

**Comment by gratefulgirl** [comment]
wow, nice....
