### ISSUE TITLE
Highlight the selected page in the navigation bar

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15191]
Hard to get the context and realize where I am without a selected visual cue.

![screen shot 2018-03-05 at 8 21 58 pm](https://user-images.githubusercontent.com/156888/37014267-5415349e-20b4-11e8-99fc-5ddbcc9d25f8.png)

**Comment by zoechi** [comment]
This seems to be fixed 
![image](https://user-images.githubusercontent.com/405837/49445559-7c92fa00-f7d2-11e8-818f-17d20f4cea42.png)
