### ISSUE TITLE
Document that showDialog creates now context and that setState on the calling widget therefore won't affect the dialog

### ISSUE THREAD

**Issue by rfuhrer** [flutter/flutter#15194]
If you try to have any sort of control in a SimpleDialog, it can't be updated using SetState().  This means it's impossible to have a DropdownButton in a dialog that actually updates when you select something. calling SetState() will update the page in the background instead of the SimpleDialog that is on the top of the screen.

I was just creating a simple "Add Dialog" where you'd pick the type of thing you were adding from a dropdown.  Looking at the material spec it seems like maybe I should be using a "Scrollable Content" style of dialog instead.  But it still seems odd you can't use a dropdown menu in a dialog at all.

## Steps to Reproduce
```dart
String _selected;

Widget _buildDialog() {
  return new SimpleDialog(
    title: new Text("New Dialog"),
    children: <Widget>[
      new Container(
          padding: const EdgeInsets.all(10.0),
          child: new DropdownButton<int>(
            hint: const Text("Pick a thing"),
            value: _selectedId,
            onChanged: (String value) {
              setState(() {
                _selected = value;
              });
            },
            items: <String>['One', 'Two', 'Free', 'Four'].map((String value) {
              return new DropdownMenuItem<String>(
                value: value,
                child: new Text(value),
              );
            }).toList(),
          )),
    ],
  );
}

@override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          title: const Text("Test"),
        ),
        body: new ListView(padding: const EdgeInsets.all(32.0), children: [
          new Container(
              padding: const EdgeInsets.all(10.0),
              child: new DropdownButton<int>(
                hint: const Text("Pick a thing"),
                value: _selectedId,
                onChanged: (String value) {
                  setState(() {
                    _selected = value;
                  });
                },
                items: <String>['One', 'Two', 'Free', 'Four'].map((String value) {
                  return new DropdownMenuItem<String>(
                    value: value,
                    child: new Text(value),
                  );
                }).toList(),
              )),
        ]),
        floatingActionButton: new FloatingActionButton(
                child: new Icon(Icons.add),
                tooltip: "New Dialog",
                onPressed: () {
                  showDialog(context: context, child: _buildDialog());
                },
              ));
  }
```
Click the FAB button and then change the selection in the dropdown.  The background one will update but not the foreground one.

## Logs

Nothing in the logs

## Flutter Doctor
[√] Flutter (Channel master, v0.1.8-pre.31, on Microsoft Windows [Version 10.0.17025.1000], locale en-US)
    • Flutter version 0.1.8-pre.31 at C:\git\flutter
    • Framework revision a1d2443e7b (4 days ago), 2018-03-01 16:25:21 -0800
    • Engine revision 269bab73b6
    • Dart version 2.0.0-dev.31.0.flutter-1aaebedd70

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Rory\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code, 64-bit edition (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.9.2

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by rfuhrer** [comment]
I realized I was using the master branch of Flutter from trying to help with the `--preview-dart-2` hot-reload crash, so I switched back to the dev channel and dart 1.  Issue is still present

**Comment by jonahwilliams** [comment]
Hi @rfuhrer,  It looks like there are a few typos in your code - when I fix them the widget works as you said it should.

Specifically:
  * Your bottom `build()` method is referencing the field `_selectedId`, but the field is actually called `_selected`.
  * Should be DropdownButton\<String\> and not DropdownButton\<int\>.

I put the fixed code in a gist below:

https://gist.github.com/jonahwilliams/aa1e111650f5ce39ba75d8a3edfed217

If you fix these issues and the problem persists please let me know.
<img width="411" alt="screen shot 2018-03-06 at 4 26 20 am" src="https://user-images.githubusercontent.com/8975114/37032350-0e3d8474-20f7-11e8-9a2b-2bd9ebde1d4c.png">

<img width="404" alt="screen shot 2018-03-06 at 4 26 31 am" src="https://user-images.githubusercontent.com/8975114/37032411-49155248-20f7-11e8-889a-3317b0aa969e.png">

<img width="403" alt="screen shot 2018-03-06 at 4 26 38 am" src="https://user-images.githubusercontent.com/8975114/37032357-11c2f2c8-20f7-11e8-9282-811ec3048c8f.png">

**Comment by rfuhrer** [comment]
Ahh sorry. My actual code was more complicated so I tried to just boil it down to the bare essentials inside GitHub instead of in the IDE.

The problem isn't that the dropdown doesn't work, the problem is it doesn't work inside the simple dialog. Hit the FAB to open a dialog that has the same dropdown in it and then try to change that dropdown. The dropdown in the background should update but the one in the foreground will stay blank or whatever you selected before opening the dialog

**Comment by rfuhrer** [comment]
You can put a breakpoint inside the `_buildDialog()` method and it will never get it except for when it's first built.  So `SetState()` doesn't seem to trigger a rebuild of any dialogs, and maybe that makes sense.  But maybe we need a `SetDialogState()` method or something to tell it to rebuild this pop-over

**Comment by jonahwilliams** [comment]
Okay, I see what you mean. See this example code for the solution:
https://gist.github.com/jonahwilliams/25fa99b6b73fdcbd58ac85585343bbd0

I'm not very familiar with simple dialog, but you are right that setState in your widget doesn't cause the dialog widget to be rebuilt.  The solution is to make your dialog a StatefulWidget, and pass it a callback to update the parent state.

**Comment by rfuhrer** [comment]
Looks like simply making the dialog be constructed inside a separate stateful widget is enough to get it working the way I was hoping.  In my real code I didn't actually have an identical dropdown in the main view and inside the dialog, I just stumbled upon that when I copy/pasted my dropdown outside if the dialog to make sure I wasn't just screwing up the setup of the dropdown.  That's where I noticed that changing the drop down in the dialog would cause the one in the main view to update and not the one in the dialog.
Here's a more realistic version of what I was trying to do that actually works: https://gist.github.com/rfuhrer/85f2c66ff82e9a8037c0d8e3f6b38526

For anyone else who stumbles upon this, here's what's happening:
1. `SetState()` will rebuild the view of whatever stateful widget "owns" that function
2. If you follow the example in https://docs.flutter.io/flutter/material/SimpleDialog-class.html then you're not creating a separate state for that dialog.  This means if you do try to change something (and call `SetState()`) in the dialog after it's been rendered, it will actually update the state of the parent since that's the stateful widget that "owns" `SetState()`, even if you call `SetState()` inside a callback in the `SimpleDialog`
3. By creating a new `StatefulWidget` that builds your `SimpleDialog`, you're now giving it it's own `SetState()` that will cause the Dialog to be rebuilt rather than the parent `StatefulWidget`.

I'm not sure if maybe something can be done to the documentation to alert the noobs like myself that calling `showDialog()` doesn't magically create state, or if maybe issues like this popping up in google searches is enough. It all makes sense to me now, but at the time I just could not figure what I was doing wrong and there wasn't many examples of showing anything in a dialog more than a simple yes/no button.

Feel free to close this issue unless you want to use it to track some updates.

**Comment by Hixie** [comment]
Adding more documentation to this effect seems reasonable.

**Comment by jonahwilliams** [comment]
Fixed by #15303

**Comment by pablote** [comment]
I've just run into this issue and I'm not sure exactly how to solve it. The documentation for `showDialog` says:

``` Use a StatefulBuilder or a custom StatefulWidget if the dialog needs to update dynamically.```

Is there any example how `StatefulBuilder` supposed to be used? I haven't seen any. This is what I tried, it didn't change anything, probably doesn't make sense:

```
showDialog(
      context: context,
      builder: (ctx) {
        return StatefulBuilder(
          builder: (ctx, setState) {
            return DocumentDialog(
              document: doc,
              onFav: handleDocumentFavPressed,
              onClose: () => Navigator.of(context).pop(),
            );
          },
        );
      },
    );
```

**Comment by netsmertia** [comment]
setState on parent does not update the dialog. I am trying to implement video_player and the full screen player will be inside a custom dialog. When the video is loading the thumbnail is shown inside a rotated widget in a dialog to mimic full screen on landscape The video size is calculated after video initialised and if it is found that video is actually a vertical video (should be played in portrait) the rotation and new video size for vertical video is used through setState but the dialog is not updating and video was played in size of thumbnail and portrait.

**Comment by emuthomi** [comment]
> setState on parent does not update the dialog. I am trying to implement video_player and the full screen player will be inside a custom dialog. When the video is loading the thumbnail is shown inside a rotated widget in a dialog to mimic full screen on landscape The video size is calculated after video initialised and if it is found that video is actually a vertical video (should be played in portrait) the rotation and new video size for vertical video is used through setState but the dialog is not updating and video was played in size of thumbnail and portrait.

I had a similar issue but mine had to do with a list of checkboxes not being checked on tapping. After scouring StackOverflow looking for solutions I landed here and then got the StatefulBuilder idea. I solved it by wrapping the returned widget in a ```StatefulBuilder```:


```dart
class _SamplePageState extends State<SamplePage> {

  List<int> selectedOptions = [];

  @override
  void initState() {
    super.initState();
  }
  Future _showOptions() async {
    //List<int> selectedOptions = [];
    await showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        // here we use a nested StatefulWidget builder so that the dialog can 
        // micromanage it's own state
        return StatefulBuilder(
          builder: (context, setState) {
            return FutureBuilder <OptionsList>(
              future: fetchOptions(), // the list of options to choose from is called from a remote API
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  var items = snapshot.data.items;
                  List <Widget> options = [];
                  items.forEach((item){
                    CheckboxListTile option = CheckboxListTile(
                      value: selectedOptions.contains(item.id),
                      title: Text(item.title),
                      onChanged: (value) {
                        setState((){
                          if(value){
                            selectedOptions.add(item.id);
                          }else{
                            selectedOptions.remove(item.id);
                          }
                          print(selectedOptions);
                        });
                      },
                    );
                    options.add(option);
                  }); //endforEach
                  return new SimpleDialog(
                    title: new Text('Select Some Options'),
                    children: options,
                  );
                } 
                else if (snapshot.hasError) {
                  return Text("${snapshot.error}");
                }
                // show spinner while future is fetching data
                return Dialog(
                  child: new Center(
                    widthFactor: 10.0,
                    heightFactor: 10.0,
                    child: new SizedBox(
                      width: 20.0,
                      height: 20.0,
                      child: const CircularProgressIndicator(
                        value: null,
                        strokeWidth: 2.0,
                      ),
                    ),
                  ),
                );
              },
            );
          },
        );
        
      }
    );
  }
  @override
  Widget build (BuildContext context) {
    return new Scaffold(
      // more code here
    );
  }
}
```

I hope you can get some ideas from that snippet on how to go about solving your problem.

**Comment by itsgauravjain22** [comment]
> > setState on parent does not update the dialog. I am trying to implement video_player and the full screen player will be inside a custom dialog. When the video is loading the thumbnail is shown inside a rotated widget in a dialog to mimic full screen on landscape The video size is calculated after video initialised and if it is found that video is actually a vertical video (should be played in portrait) the rotation and new video size for vertical video is used through setState but the dialog is not updating and video was played in size of thumbnail and portrait.
> 
> I had a similar issue but mine had to do with a list of checkboxes not being checked on tapping. After scouring StackOverflow looking for solutions I landed here and then got the StatefulBuilder idea. I solved it by wrapping the returned widget in a `StatefulBuilder`:
> 
> ```dart
> class _SamplePageState extends State<SamplePage> {
> 
>   List<int> selectedOptions = [];
> 
>   @override
>   void initState() {
>     super.initState();
>   }
>   Future _showOptions() async {
>     //List<int> selectedOptions = [];
>     await showDialog(
>       context: context,
>       barrierDismissible: false,
>       builder: (BuildContext context) {
>         // here we use a nested StatefulWidget builder so that the dialog can 
>         // micromanage it's own state
>         return StatefulBuilder(
>           builder: (context, setState) {
>             return FutureBuilder <OptionsList>(
>               future: fetchOptions(), // the list of options to choose from is called from a remote API
>               builder: (context, snapshot) {
>                 if (snapshot.hasData) {
>                   var items = snapshot.data.items;
>                   List <Widget> options = [];
>                   items.forEach((item){
>                     CheckboxListTile option = CheckboxListTile(
>                       value: selectedOptions.contains(item.id),
>                       title: Text(item.title),
>                       onChanged: (value) {
>                         setState((){
>                           if(value){
>                             selectedOptions.add(item.id);
>                           }else{
>                             selectedOptions.remove(item.id);
>                           }
>                           print(selectedOptions);
>                         });
>                       },
>                     );
>                     options.add(option);
>                   }); //endforEach
>                   return new SimpleDialog(
>                     title: new Text('Select Some Options'),
>                     children: options,
>                   );
>                 } 
>                 else if (snapshot.hasError) {
>                   return Text("${snapshot.error}");
>                 }
>                 // show spinner while future is fetching data
>                 return Dialog(
>                   child: new Center(
>                     widthFactor: 10.0,
>                     heightFactor: 10.0,
>                     child: new SizedBox(
>                       width: 20.0,
>                       height: 20.0,
>                       child: const CircularProgressIndicator(
>                         value: null,
>                         strokeWidth: 2.0,
>                       ),
>                     ),
>                   ),
>                 );
>               },
>             );
>           },
>         );
>         
>       }
>     );
>   }
>   @override
>   Widget build (BuildContext context) {
>     return new Scaffold(
>       // more code here
>     );
>   }
> }
> ```
> 
> I hope you can get some ideas from that snippet on how to go about solving your problem.

@emuthomi Could you share fetchOptions () implementation. Does it uses setState inside?
I want to display such complex alert with network fetched options but can't find a way to setState rebuilding the alert again from fetchOptions().

I have asked the question on [stackoverflow](https://stackoverflow.com/questions/61041632/how-to-implement-a-network-data-fetch-and-then-display-in-checkbox-in-alert-insi)

**Comment by emuthomi** [comment]
> @emuthomi Could you share fetchOptions () implementation. Does it uses setState inside?
> I want to display such complex alert with network fetched options but can't find a way to setState rebuilding the alert again from fetchOptions().
> 
> I have asked the question on [stackoverflow](https://stackoverflow.com/questions/61041632/how-to-implement-a-network-data-fetch-and-then-display-in-checkbox-in-alert-insi)

It is just a simple Future

```
Future<OptionsList> fetchOptions() async {
  var url = API_URL + '/services';
  final response = await http.get(url);
  if (response.statusCode == 200) {
    return OptionsList.fromJson(json.decode(response.body));
  }
  else {
    return new OptionsList();
  }
}
