### ISSUE TITLE
Create a new Flutter project offline

### ISSUE THREAD

**Issue by Josemboa** [flutter/flutter#15199]
I would like to be able to create a new Flutter project offline, without Internet access. So, every time I create a new project it would be able to run **flutter packages get** locally and not try to access [http://pub.dartlang.org](http://pub.dartlang.org).

![image](https://user-images.githubusercontent.com/5972884/37031175-795d2152-2146-11e8-89ee-71ddf84cb9d1.png)

**Comment by ninetian** [comment]
this look like your local DNS problem
try ping pub.dartlang.org domain
or change you local DNS to 8.8.8.8  try again.

**Comment by Josemboa** [comment]
When I'm online I'm able to create a new project and ping to pub.dartlang.org. I was just asking for a way to create a project without Internet access, as it is possible with React Native, for example.

**Comment by xqwzts** [comment]
There is an `--offline` flag that you can pass to `flutter create`:

>     --[no-]offline             When "flutter packages get" is run by the create command, this indicates whether to run it in offline mode or not. In offline mode, it will need to have all dependencies already available in the pub cache to succeed.

**Comment by Josemboa** [comment]
Thank you. It works using --offline.

**Comment by jgadjetx** [comment]
Simple English please

**Comment by Aceix** [comment]
@jgadjeitx it means run flutter create passing offline argument this way
'''flutter create xxx --offline'''

**Comment by Choons** [comment]
flutter create --offline no longer seems to work (Feb. 15, 2021)

**Comment by benjaminjacobreji** [comment]
The create project offline option in Android Studio hangs when enabled. 
Creating a project without it checked, works normally as expected. 

Using Flutter master channel

Output of 'flutter doctor -v'

❯ flutter doctor -v
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on Linux, locale en_US.UTF-8)
    • Flutter version 1.27.0-5.0.pre.94 at /home/asleepyguy/SDK/flutter
    • Framework revision 5642bed237 (4 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/asleepyguy/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/asleepyguy/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/asleepyguy/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/asleepyguy/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
