### ISSUE TITLE
TextFormField getting disabled after taping multiple time out of the Textformfield

### ISSUE THREAD

**Issue by prakash-android-concetto** [flutter/flutter#151955]
### Steps to reproduce

1. click inside textformfield
2. now tap multiple time out side of textformfield in screen

now you will not able to again edit in textformfield it seems its disabled

### Expected results

it should allow me to enter text in textform field

### Actual results

its seems like disabled and not allow me to editing textformfield

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by prakash-android-concetto** [comment]
got solution simply upgrade flutter to Flutter 3.22.3.

**Comment by danagbemava-nc** [comment]
Closing this based on https://github.com/flutter/flutter/issues/151955#issuecomment-2236373033
