### ISSUE TITLE
timeline trace flow not match between VsyncFireCallback and PipelineItem

### ISSUE THREAD

**Issue by didi11641** [flutter/flutter#151913]
![image](https://github.com/user-attachments/assets/97088daa-5900-49ba-8d8d-9afb5f899995)
I found there's big gap between `VsyncFireCallback` and `PipelineItem`, so I investigate into flutter-engine, and find that their flow id is generated independently:

``` C++
// vsync_waiter.cc
const uint64_t flow_identifier = fml::tracing::TraceNonce();

// pipeline.h
    return ProducerContinuation{
        std::bind(&Pipeline::ProducerCommit, this, std::placeholders::_1,
                  std::placeholders::_2),  // continuation
        GetNextPipelineTraceID()};         // trace id
```

It's weired...

**Comment by darshankawar** [comment]
Thanks for the report. Keeping it open and labeling for team's tracking.

**Comment by jonahwilliams** [comment]
We don't think these flow ids are mean't to be connected. What problem is this divergence causing for you?

**Comment by didi11641** [comment]
> We don't think these flow ids are mean't to be connected. What problem is this divergence causing for you?

Ah..  okay..  I'm just curious about why there are arrow lines between these 3 steps.  So flow ids can be removed?

**Comment by jonahwilliams** [comment]
I .. don't know. Perhaps a quirk of the trace viewer?
