### ISSUE TITLE
unavailable MainAxisAlignment

### ISSUE THREAD

**Issue by Dssssds** [flutter/flutter#151906]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/f6132fff-ddab-4e84-9755-83cf793f5ed8)

### Actual results

![image](https://github.com/user-attachments/assets/4aaa68bf-956b-47cb-aa12-289dfa1fe7e9)

### Logs

![image](https://github.com/user-attachments/assets/9fd5d422-8295-4a37-a862-4c2691231d3a)

### Flutter Doctor output

![image](https://github.com/user-attachments/assets/7ed8e5ff-58c8-4979-b0c5-4bbca23ac20d)

**Comment by danagbemava-nc** [comment]
When filing an issue, please provide some context and some information so that it can be properly addressed. 

Closing from here as there's no acionable information in this issue. 

Thank you
