### ISSUE TITLE
[CanvasKit] Flutter Web Build Crashes on iOS Browsers When Loading Large Images

### ISSUE THREAD

**Issue by akshaySavanoor** [flutter/flutter#151933]
### Steps to reproduce

1. Create a Flutter web application using CanvasKit for rendering.
Attempt to load and render an image larger than 1MB(Regarding exact image size I'm not sure but it works fine with some image size of KB) .
2. Open the application on an iOS device using Safari, Chrome, or Firefox.
3. Observe the crash.
4. It works totally fine we create web build using html just fails for canvaskit since we need canvaskit for displaying some image mask we can't switch to html. 

flutter run -d chrome --web-renderer html - **works**
flutter build web --web-renderer canvaskit - **fails**

### Expected results

The image should render without causing the application to crash.

### Actual results

The application crashes when attempting to render images on iOS web browsers. We tried various methods including CachedNetworkImage, Image.network, Image.asset, NetworkImage, and loading images via HTTP and HTMLImage. Below are our observations:

Image.asset: Fails on iOS web. Works on Android web, but the image doesn't load unless cacheWidth is added, then it loads.
Image.network: Fails on iOS web. Works on Android web, but the image doesn't load unless cacheWidth is added, then it loads.
CachedNetworkImage: Fails on iOS web. Works on Android web.
NetworkImage: Fails on iOS web. Works on Android web with heavy lag.
HTMLImage: Fails on iOS web. Works on Android web.
Loading from Hive: Fails on iOS web. Works on Android web.

Note: "Fails" means that in more than 80% of cases, the image fails to load. Sometimes, it displays the error builder instead.

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter CanvasKit Image Crash Demo',
      home: ImageScreen(),
    );
  }
}

class ImageScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('CanvasKit Image'),
      ),
      body: ListView(
        children: [
          // Load image from assets
          Image.asset('assets/large_image.jpg'),

          // Load image from network
          Image.network('https://example.com/large_image.jpg'),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880], locale en-IN)
    • Flutter version 3.22.2 on channel stable at C:\Users\akshays\Downloads\flutter_windows_3.19.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\akshays\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at C:\Users\akshays\AppData\Local\Programs\IntelliJ IDEA Community Edition
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.90.2)
    • VS Code at C:\Users\akshays\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.102

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by akshaySavanoor** [comment]
I found similar reports, but none of them had solutions. In most cases, they switched to the HTML renderer using the command

**flutter run -d chrome --web-renderer html**

However, in our case, we need CanvasKit to render some masked images, so we are left with no other options. One important thing to note is that it works fine on Android, iOS, Android web, and macOS (tested in Chrome and Safari). The issue occurs only on iOS web (tested in Safari, Chrome, and Firefox; it fails in all).

**Comment by danagbemava-nc** [comment]
Hi @akshaySavanoor, please provide some sample images that we can use to verify this issue. 

Also, do you get any errors that you can share with us?

**Comment by akshaySavanoor** [comment]
We tried it again, this time using multiple images instead of just one. Sometimes it works, sometimes it fails. What we observed is that it fails for large images, specifically on iOS web browsers. Sometimes it reloads the page again. Here is the error message we received for some images,
![error_image](https://github.com/user-attachments/assets/462dc465-2a20-4b2c-aa9a-632453552eae)
![crash_image](https://github.com/user-attachments/assets/288f5420-d8f4-4ceb-a513-e58bb4cd483d)

 along with a test image that you can use
![canvas_test_image1](https://github.com/user-attachments/assets/b818b3cf-8fd2-463a-b36b-974f64442773)

**Comment by akshaySavanoor** [comment]
Hey, note that the error we provided above occurred while loading images from the network. There are no CORS-related issues; the testing image above was not from our API, simply large in size. We are facing crashes due to these large images. Unfortunately, I can't provide exact images from our image APIs, but we tested by downloading similar large images into our assets, and the result was the same — the application crashes

**Comment by danagbemava-nc** [comment]
Hi @akshaySavanoor, I justed tested with the image you provided in https://github.com/flutter/flutter/issues/151933#issuecomment-2236322826 with stable 3.22.3 on an iPhone running iOS 17.5.1 and the image rendered properly. See the screenshot below. Can you upgrade to stable 3.22.3 to see if you still experience this issue? I built the app with `flutter build web --release --web-renderer canvaskit` and served the built file with `python3 -m http.server` and then run it on my iPhone

<img src="https://github.com/user-attachments/assets/2d755ca5-40bc-498d-94de-205b413c707b" width="300"/>

**Comment by akshaySavanoor** [comment]
Hey @danagbemava-nc  thank you for your time, I just tested the stable version 3.22.3, and the issue remains the same. We also tried compressing our API image to kilobytes, but we're still facing the same issue on iPhone browsers. When we tested with assets, it worked, so I'm still unable to pinpoint the exact issue. It works perfectly fine on Android web, Windows web, and Mac web, but it crashes on iOS web even after implementing error handling for the image. This is very confusing. Moreover, this issue only occurs when we render on CanvasKit, it works fine in HTML. Additionally, the image I provided is not from our API; we use images from Strapi.

**Comment by danagbemava-nc** [comment]
Hi @akshaySavanoor, we will need an image that reproduces the issue so that we can properly investigate this issue. 

Thank you

**Comment by akshaySavanoor** [comment]
I think it's an issue related to our image, so I'm going to close this issue. Thank you for your response.

**Comment by derekvawdrey** [comment]
I am also having this exact issue. Canvaskit crashes quite readily when I load about 3-4 images using any of the above strategies. Deploying using HTML fixes the issue, but canvaskit (Only on mobile browsers) literally hogs up all the resources the phone has available, and then crashes the website.

`class ShopCard extends StatelessWidget {
  final ProStore item;
  final Function(ProStore)? onSelect;

  ShopCard({Key? key, required this.item, this.onSelect})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildImage(),
        ],
      ),
    );
  }

  Widget _buildImage() {
    return AspectRatio(
      aspectRatio: 16 / 9,
      child: item.primaryPhotoUrl.isNotEmpty &&
              item.primaryPhotoUrl.startsWith("http")
          ? CachedNetworkImage(
              imageUrl: item.primaryPhotoUrl,
              fit: BoxFit.cover,
              placeholder: (context, url) =>
                  const Center(child: CircularProgressIndicator()),
              errorWidget: (context, url, error) => const Icon(Icons.error),
              memCacheWidth: 300,
              memCacheHeight: 169,
            )
          : const Icon(Icons.store, size: 64, color: Colors.grey),
    );
  }`

Below are images that are pulled.

![pro_users_NP3ok2uLligCPSrsJ8TbWyPra0q2_stores_qUbEybBNFy3SBC9yFNt5_e511fb5f-0200-4291-91cd-0f9b645f9abf_original](https://github.com/user-attachments/assets/39f77cee-268b-433b-af3e-e93c902ffde9)

![pro_users_Fxbp77XMb6YbWEIJpTPoT4vuabx2_stores_XlmDIEPeSoutPDGezvgL_528f6623-86b6-4cda-91fb-f3472e5d30fc_original](https://github.com/user-attachments/assets/67d65f9f-4820-4a87-9845-6bc9db3dd12b)

https://images.pexels.com/photos/128756/pexels-photo-128756.jpeg

**Comment by danagbemava-nc** [comment]
Hi @derekvawdrey, can you provide a complete runnable code sample that reproduces the issue?

**Comment by AkshaySavanoorCC** [comment]
@derekvawdrey , we faced the exact same issue. What we did was use [Cloudinary](https://cloudinary.com/users/login) as a proxy. We sent our API image to Cloudinary and then used it from there. This allowed us to optimize the image while fetching it from Cloudinary, and we could also change the image format. Our initial image was in JPEG format, and we converted it to PNG while fetching.

You need two packages for that:

cloudinary_flutter: ^1.3.0
cloudinary_url_gen: ^1.5.0
Fetching from Cloudinary:
`CldImageWidget(
  placeholder: (context, message) {
    return const LoadingScreen();
  },
  publicId: imagePublicId,
  fit: BoxFit.cover,
  transformation: Transformation()
    ..delivery(Delivery.format(Format.png)),
) you can do more customization.
`

Cloudinary upload API: https://api.cloudinary.com/v1_1/your_cloud_name/image/upload

`final params = {
  'public_id': Utility.extractFileName(imageUrl),
  'timestamp': timestamp,
};

final signature = generateSignature(apiSecret, params);

final requestBody = {
  'file': imageUrl,
  'api_key': apiKey,
  'timestamp': timestamp,
  'signature': signature,
  'public_id': publicId,
};

String generateSignature(String apiSecret, Map<String, String> params) {
  final sortedKeys = params.keys.toList()..sort();
  final paramString = sortedKeys.map((key) => '$key=${params[key]}').join('&');
  final stringToSign = '$paramString$apiSecret';
  final bytes = utf8.encode(stringToSign);
  return sha256.convert(bytes).toString();
}

String generateCurrentTimestamp() {
  return (DateTime.now().millisecondsSinceEpoch ~/ 1000).toString();
}
`
You can see more in their documentation. This method worked for us.

**Comment by AkshaySavanoorCC** [comment]
@derekvawdrey  You can also try the ImageNetwork package in case of CORS errors; this will solve the issue. Note that cachedNetwork doesn’t work on the web, but it doesn’t cause any problems either.

You can also try using Image.network with cachedWidth or cachedHeight; sometimes this works. If you don’t have any issues while downloading images, you could also try using floor or hive to locally store your images and then display them to the user (first load from the API to hive, then display from hive).

Based on your problem, I think Image.network with cachedWidth will solve your issue:

`cachedWidth: (width * MediaQuery.of(context).devicePixelRatio).round()`

**Comment by AkshaySavanoorCC** [comment]
Also, try [flexi_ui](https://pub.dev/packages/flexi_ui) for creating responsive designs easily for all screens.
