### ISSUE TITLE
PopScope not work 

### ISSUE THREAD

**Issue by survildhaduk-easternts** [flutter/flutter#151966]
### Steps to reproduce

version 12 popscope working but latest veriosn issue not working

### Expected results

version 12 popscope working but latest veriosn issue not working

### Actual results

version 12 popscope working but latest veriosn issue not working

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by storm265** [comment]
Please add your code

**Comment by darshankawar** [comment]
@survildhaduk-easternts 
Please provide proper details as requested. Without it, we won't be able to address it.
Closing due to lack of details.
