### ISSUE TITLE
Flutter not recognizing Simulator

### ISSUE THREAD

**Issue by jimist** [flutter/flutter#15193]
Hi guys,

I tried to connect flutter to another simulator (nox), but it's not even recognizing it.
I put the doctor respond below;

`
C:\Users\Jimist>flutter doctor -v
[√] Flutter (Channel master, v0.1.8-pre.44, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
    • Flutter version 0.1.8-pre.44 at D:\Projects\flutter\flutter
    • Framework revision c885015934 (33 hours ago), 2018-03-04 12:15:22 -0800
    • Engine revision 97b22348c8
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Softwares\Android\Android-SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Softwares\Android\Android-SDK
    • Java binary at: D:\Softwares\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    X Android license status unknown.

[√] Android Studio (version 3.0)
    • Android Studio at D:\Softwares\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.3
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4301.22

[√] VS Code, 32-bit edition (version 1.20.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.9.2

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
`

**Comment by Chidaverz** [comment]
@jimist You need to connect adb server to Nox App first `adb connect 127.0.0.1:62001`
and then check if your Nox App has been listed by adb server using `adb devices -l`

**Comment by hagemaruf** [comment]
hi @jimist 

I have same problem with you and I solve it by install Google USB Driver.
You can check here [https://flutter.dev/docs/get-started/install/windows](https://flutter.dev/docs/get-started/install/windows
).
Hope it can help you.

**Comment by shehry3894** [comment]
if `adb devices` is not showing any devices then try connecting the device manually by the following command
`adb connect 127.0.0.1:62001`

**Comment by Aung-Thiha112** [comment]
I do not also have the access to run the emulator in vs code using flutter. what am I missing?

**Comment by abdulpiksi** [comment]
just rename nox_adb.exe and run again nox player, then `adb connect 127.0.0.1:62001` run flutter doctor and flutter devices
