### ISSUE TITLE
Could we add Indonesia language into Localization.dart in the Beta channel?

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15192]
Hi ,now our app need to support Indonesian bahasa , but I found there is no material_id.arb file in the flutter_localizations folder ,

By the way , could you add Thai and Indonesia Bahasa in the  flutter/packages/flutter_localizations/lib/src/material_localizations.dart ?

I want to commit my code, but no access right .
Thank you so much .

**Comment by Hixie** [comment]
We don't yet support those languages, but if you want to support them you can implement the MaterialLocalizations and WidgetLocalizations interfaces yourself and provide them to the MaterialApp constructor.

**Comment by realcarlos** [comment]
No ,I mean there is a material_th.arb file in package/flutter_localization/lib/src/L10n folder ,but did't turn on in the material_localization.dart file , so that the DatePicker and other widget can not display Thailand.


class _MaterialLocalizationsDelegate extends LocalizationsDelegate<MaterialLocalizations> {
  const _MaterialLocalizationsDelegate();

  static const List<String> _supportedLanguages = const <String>[
    'ar', // Arabic
    'de', // German
    'en', // English
    'es', // Spanish
    'fa', // Farsi
    'fr', // French
    'he', // Hebrew
    'it', // Italian
    'ja', // Japanese
    'ps', // Pashto
    'pt', // Portugese
    'ro', // Romanian
    'ru', // Russian
    'ur', // Urdu
    'th', // Thai    <------- need to add
    'id', // Indonesia <------- need to add
    'zh', // Simplified Chinese
  ];

  @override
  bool isSupported(Locale locale) => _supportedLanguages.contains(locale.languageCode);

  @override
  Future<MaterialLocalizations> load(Locale locale) => GlobalMaterialLocalizations.load(locale);

  @override
  bool shouldReload(_MaterialLocalizationsDelegate old) => false;
}

**Comment by realcarlos** [comment]
same as [https://github.com/flutter/flutter/issues/14451](url)

**Comment by realcarlos** [comment]
![2018-03-07 12 40 40](https://user-images.githubusercontent.com/13853/37073981-2080ae54-2205-11e8-99dd-f8f40bb017bc.png)

this is the screenshot of the drawer in my app ,when I set language to Thai

**Comment by realcarlos** [comment]
In my app ,I have add these: 

      supportedLocales: [
        const Locale('en', 'US'),
        const Locale('th', 'TH'),
        const Locale('id', 'ID'),
      ],

but it doesn't work until I modified the material_localization.dart file

**Comment by Hixie** [comment]
Oh, I see. cc @HansMuller

**Comment by HansMuller** [comment]
Support for Thai will be fixed when https://github.com/flutter/flutter/pull/15260 lands.

I have requested Indonesian (language code 'id') translations. It will take a few weeks for them to roll through the system.
