### ISSUE TITLE
the doctor check crashed

### ISSUE THREAD

**Issue by vishal915523** [flutter/flutter#151982]
### Steps to reproduce

the doctor check did not complete. If the error message below is not helpful

### Actual results

Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 )  is removed from the PATH environment variable. Ensure that this is present and then try again after restarting the terminal and/or IDE.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
This looks like you have forgotten this part: [Update your path](https://docs.flutter.dev/get-started/install/windows#update-your-path). Please follow step-by-step there to see if it helps. You can also check this SO thread as well: [stackoverflow.com/questions/49609889/flutter-doctor-doesnt-work-on-neither-command-prompt-or-powershell-window](https://stackoverflow.com/questions/49609889/flutter-doctor-doesnt-work-on-neither-command-prompt-or-powershell-window)

Your question is best suited for support channels like StackOverflow, so please ask the same there for solution if any. Closing for now. If there isn't any solution that can apply to the issue, please write in comments with more information and I will re-open issue for further support. Thanks!
