### ISSUE TITLE
flutter listen always loads the main view (navigator should save state)

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#152]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Friday Aug 28, 2015 at 00:08 GMT_
_Originally opened as https://github.com/flutter/engine/issues/909_

----

At least in debug mode I want navigator to serialize its state to memory or disk so that when listen pokes SkyShell to reload it reloads in the same navigation state as before.

@iansf @collinjackson

**Comment by FlutterIssues** [comment]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Friday Aug 28, 2015 at 00:08 GMT_

----

https://github.com/domokit/sky_engine/issues/907 covers scroll behavior

**Comment by Hixie** [comment]
With https://github.com/flutter/flutter/pull/1037 you can at least pass a default route now, so if you're working on a particular screen you can start it on that screen.

**Comment by danrubel** [comment]
Subsumed by https://github.com/flutter/flutter/issues/6199 and the fact that [`flutter run` is now hot](https://github.com/flutter/flutter/issues/5280).
