### ISSUE TITLE
[CP] Fix TextPainter's caret position calculation for text containing full-width spaces

### ISSUE THREAD

**Issue by yqritc** [flutter/flutter#152016]
### Issue Link

https://github.com/flutter/flutter/issues/149099

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/152021

### Changelog Description

Fix the logic for caret position calculation when full-width spaces are present in the text

### Impacted Users

end-customers

### Impact Description

The cursor does not move when entering full-width spaces

### Workaround

none

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Enter full-width spaces in TextFormField
2. This fix works if the cursor position changed

**Comment by itsjustkevin** [comment]
@yqritc please follow the cherry-pick instructions by opening a cherry-pick to the stable branch and updating the pr link in this issue before it can be accepted into the queue.

**Comment by yqritc** [comment]
@itsjustkevin sorry, I updated the pr link

**Comment by itsjustkevin** [comment]
@yqritc beta is the current priority, your request has not been forgotten.

**Comment by yqritc** [comment]
closed this issue since the fix is included into 3.24.0
