### ISSUE TITLE
Dart on web:  The integer negative zero formats as "-0.0"

### ISSUE THREAD

**Issue by zathras** [flutter/flutter#152008]
### Steps to reproduce

Use "flutter run" to run the four-line program provided below in Chrome, and observe that the `int` formats as "-0.0".

### Expected results

```
A Dart VM Service on Chrome is available at: http://127.0.0.1:59786/bfAu4QGpcN4=
 The int "-0" formats like this:  0
```

### Actual results

```
A Dart VM Service on Chrome is available at: http://127.0.0.1:59786/bfAu4QGpcN4=
 The int "-0" formats like this:  -0.0
```

### Code sample

<details open><summary>Code sample</summary>
`cat lib/main.dart`

```dart
void main() {
  int i = -0;
  print(' The int "-0" formats like this:  $i');
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@zathras 
You will need to report this in dart-lang repo: https://github.com/dart-lang/sdk/issues
