### ISSUE TITLE
Suggest: TextEditingController's buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing})  return InlineSpan

### ISSUE THREAD

**Issue by zhouzhuo810** [flutter/flutter#152066]
### Use case

I want add WidgetSpan into TextFiled

```
class RichTextController extends TextEditingController {
 @override
  TextSpan buildTextSpan({
    required BuildContext context,
    TextStyle? style,
    required bool withComposing,
  }) {
     //todo
  }
}
```

But `buildTextSpan` return `TextSpan` , if change `TextSpan` to `InlineSpan`, It should be better.

### Proposal

I want add WidgetSpan into TextFiled

```
class RichTextController extends TextEditingController {
 @override
  TextSpan buildTextSpan({
    required BuildContext context,
    TextStyle? style,
    required bool withComposing,
  }) {
     //todo
  }
}
```

But `buildTextSpan` return `TextSpan` , if change `TextSpan` to `InlineSpan`, It should be better.

**Comment by hawkkiller** [comment]
TextSpan accepts children and they can be of type InlineSpan.

**Comment by zhouzhuo810** [comment]
> TextSpan accepts children and they can be of type InlineSpan.

Thanks，but i meet a new question,  `WidgetSpan` can not expand the line height of `TextField` , like this:

<img width="275" alt="image" src="https://github.com/user-attachments/assets/e1723bad-3bad-413a-856a-365c593464ca">

**Comment by Dabbit-Chan** [comment]
> > TextSpan accepts children and they can be of type InlineSpan.
> 
> Thanks，but i meet a new question, `WidgetSpan` can not expand the line height of `TextField` , like this:
> 
> <img alt="image" width="275" src="https://private-user-images.githubusercontent.com/15272555/350696775-e1723bad-3bad-413a-856a-365c593464ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzEzNTIsIm5iZiI6MTcyMTYzMTA1MiwicGF0aCI6Ii8xNTI3MjU1NS8zNTA2OTY3NzUtZTE3MjNiYWQtM2JhZC00MTNhLTg1NmEtMzY1YzU5MzQ2NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2NTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MzQwNDJhOWIyODM5OWIzNGM0OGNkMzIwZmVhYTlmNjg5YTc3YzAwNzRiMmQyZTk4MTExYzcwNmY1ZDkwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TimihoOufGTMWSa7pfh6drJEDzLWnKOYH-FVANqQzJQ">

Maybe you could take a look at this package: [extended_text_field](https://github.com/fluttercandies/extended_text_field)

**Comment by zhouzhuo810** [comment]
> > > TextSpan accepts children and they can be of type InlineSpan.
> > 
> > 
> > Thanks，but i meet a new question, `WidgetSpan` can not expand the line height of `TextField` , like this:
> > <img alt="image" width="275" src="https://private-user-images.githubusercontent.com/15272555/350696775-e1723bad-3bad-413a-856a-365c593464ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzEzNTIsIm5iZiI6MTcyMTYzMTA1MiwicGF0aCI6Ii8xNTI3MjU1NS8zNTA2OTY3NzUtZTE3MjNiYWQtM2JhZC00MTNhLTg1NmEtMzY1YzU5MzQ2NGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2NTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MzQwNDJhOWIyODM5OWIzNGM0OGNkMzIwZmVhYTlmNjg5YTc3YzAwNzRiMmQyZTk4MTExYzcwNmY1ZDkwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TimihoOufGTMWSa7pfh6drJEDzLWnKOYH-FVANqQzJQ">
> 
> Perhaps you could have a look at this package: [extended_text_field](https://github.com/fluttercandies/extended_text_field)

thanks, I am testing this code

**Comment by darshankawar** [comment]
@zhouzhuo810 
Perhaps you are hitting https://github.com/flutter/flutter/issues/90355 that you can check and follow-up in.
Closing as duplicate.
