### ISSUE TITLE
A _TypeError occurs (specifically, 'Null' is not a subtype of type TYPE) when attempting to remove the navigation history and navigate back to '/'.

### ISSUE THREAD

**Issue by iSaqibShafique** [flutter/flutter#152078]
### Steps to reproduce

1 - Used GoRouter.of(context).pushNamed() to navigate to a page and pop all previous pages.
2 - Used context.go() to make sure to remove the navigation history.
3 - Used context.go() to navigate to "/"

* Problem *
* Error - _TypeError (type 'Null' is not a subtype of type 'Goal').

### Expected results

Refresh the goRouter when I want to go to "/"

### Actual results

Null error occurred.

### Code sample

Got error in this section

  ```

GoRoute(
          path: whenGoalSaved,
          name: AppRoute.whenGoalSaved.name,
          builder: (context, state) {
            Map<String, dynamic>? data = state.extra is Map<String, dynamic>
                ? state.extra as Map<String, dynamic>
                : null;
            String id =
                data != null && data.containsKey("id") ? data["id"] : "";
            Goal goal = data != null && data.containsKey("goal")
                ? data["goal"]
                : Goal(
                    uid: "uid",
                    createdAt: 0,
                    domain: "domain",
                    startDate: 0,
                    endDate: 0,
                    role: "role",
                    goal: "goal",
                    results: "results",
                    description: "description",
                    id: "id",
                    completed: false);
            return WhenGoalSaved(
              goal: goal,
              id: id,
            );
          },
        )

```

### Screenshots or Video

* Screenshot *

<img width="1310" alt="Screenshot 2024-07-21 at 12 54 13 PM" src="https://github.com/user-attachments/assets/749fe01e-629e-4ba2-bf6f-87a1759e06c8">

### Logs

```
═══════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building Builder(dirty):
type 'Null' is not a subtype of type 'Goal'

The relevant error-causing widget was:
    MediaQuery MediaQuery:file:///Users/saqibshafique/Desktop/Flutter%20Projects/pink_elephants_coaching/lib/core/app.dart:141:18

When the exception was thrown, this was the stack:
#0      AppRoutes.router.<anonymous closure> (package:pink_elephants_coaching/common/routes/app_routes.dart:161:27)
app_routes.dart:161
#1      _CustomNavigatorState._buildPageForGoRoute.<anonymous closure> (package:go_router/src/builder.dart:257:21)
builder.dart:257
#2      Builder.build (package:flutter/src/widgets/basic.dart:7698:48)
basic.dart:7698
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550:49)
framework.dart:5550
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
framework.dart:5480

```

### Flutter Doctor output

✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-x64, locale
    en-PK)
    • Flutter version 3.19.6 on channel stable at
      /Users/saqibshafique/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/saqibshafique/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (2 available)
    • mini (mobile)   • FDE62D40-B2E5-406E-A456-89D5D08349F8 • ios        •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop) • macos                                • darwin-x64 •
      macOS 14.5 23F79 darwin-x64
    ! Error: Browsing on the local area network for iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@iSaqibShafique 
Please provide us complete but [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without third party implementation that still triggers the reported error.
