### ISSUE TITLE
[CP] [web] Set touch-action:none in embedded views. 

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#152047]
### Issue Link

https://github.com/flutter/engine/pull/53647

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/54007

### Changelog Description

Applies touch-action:none in embedded views, so Flutter can handle all touch events without interference from the browser. (The previous fix broke certain a11y taps).

### Impacted Users

Flutter web mobile users with semantics enabled.

### Impact Description

When semantics are enabled, tapping on the label of a checkbox in a mobile browser won't togle the checkbox. It's also harder for screen reader users to access those component+label "merged" widgets.

### Workaround

No, because the old solution was intercepting some pointer events that turns out were needed in certain cases.

### Risk

low

### Test Coverage

yes

### Validation Steps

It's been validated in the original PR, but a way of validating is by running the app listed here:

* https://github.com/flutter/flutter/issues/130950#issue-1812857359

Deploying it somewhere and attempting to click in the "A checkbox" label, with chrome in "responsive mode, with taps enable". Before the fix, the click won't do anything. After the fix, the click will toggle the checkbox.

/cc @yjbanov

**Comment by itsjustkevin** [comment]
@yjbanov please review.

**Comment by yjbanov** [comment]
LGTM!

**Comment by yjbanov** [comment]
Should I add the `cp: approved` label?

**Comment by itsjustkevin** [comment]
@yjbanov this one missed the cut, but please add the label so it can land on the first hotfix.  The change will need to be rebased against stable.

**Comment by ditman** [comment]
@itsjustkevin what's the branch I need to rebase the PR agains? I'm going to be OOO in a week, and wanted to leave this wrapped up (or in auto-pilot)

**Comment by itsjustkevin** [comment]
@ditman from your side you “shouldn’t” have to do anything.  The branch will be the same, if anything I will just need to “update branch” from the PR UI.

**Comment by ditman** [comment]
Sweet @itsjustkevin! Do ping me if you want me to tread any water to get this landed!

**Comment by kevmoo** [comment]
https://github.com/flutter/engine/pull/53647#issuecomment-2276392032 – ugh. Need to figure out where to target this.
