### ISSUE TITLE
Rendering issue when compiling with --wasm

### ISSUE THREAD

**Issue by dxvid-pts** [flutter/flutter#152029]
### Steps to reproduce

I am using the [syncfusion_gauges](https://pub.dev/packages/syncfusion_flutter_gauges) package to render the circular "chart" shown in the screenshots (version 26.1.42). Since it is an issue with flutter I am posting it here and not on the library's GitHub. When compling via --wasm the widget looks completely different.

### Expected results (CanvasKit)

<img width="102" alt="Screenshot 2024-07-19 at 14 54 13" src="https://github.com/user-attachments/assets/9860954b-9732-47de-b02e-6704b1a42099">

### Actual results (WASM + skwasm)

<img width="105" alt="Screenshot 2024-07-19 at 14 54 23" src="https://github.com/user-attachments/assets/ae5c78ae-56f5-4ce7-a4ec-431a0c7ee337">

### Code sample

<details open><summary>Code sample</summary>

```dart
SizedBox(
      height: 90,
      width: 90,
      child: SfRadialGauge(
        axes: <RadialAxis>[
          RadialAxis(
            minimum: 0,
            maximum: 100,
            showLabels: false,
            showTicks: false,
            startAngle: 270,
            endAngle: 270,
            annotations: <GaugeAnnotation>[
              GaugeAnnotation(
                  positionFactor: 0.05,
                  angle: 90,
                  widget: Text("27%"))
            ],
            //grey part
            axisLineStyle: AxisLineStyle(
              thickness: 0.04,
              color: Colors.black.withOpacity(0.15),
              thicknessUnit: GaugeSizeUnit.factor,
            ),
            pointers: <GaugePointer>[
              //colored part
              RangePointer(
                  value: courseProgressPercentage * 100,
                  width: 0.08,
                  sizeUnit: GaugeSizeUnit.factor,
                  cornerStyle: CornerStyle.startCurve,
                  gradient: SweepGradient(colors: <Color>[
                    Theme.of(context).colorScheme.primary.withOpacity(0.66),
                    Theme.of(context).colorScheme.primary
                  ], stops: const <double>[
                    0.25,
                    0.75
                  ])),
              //dot
              MarkerPointer(
                value: courseProgressPercentage * 100,
                markerType: MarkerType.circle,
                markerWidth: 13,
                markerHeight: 13,
                color: Theme.of(context).colorScheme.primary,
              )
            ],
          ),
        ],
      ),
    )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.24.0-1.0.pre.197, on macOS 14.5 23F79
    darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @dxvid-pts

>Since it is an issue with flutter I am posting it here and not on the library's GitHub

If the issue occurs with a 3rd party dependency, it's better to report to its developer first to verify the issue initially. Or you should narrow the sample code down into a simpler one (reduce it by removing unrelated components) to reproduce the issue. Please see https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#provide-reduced-test-cases.

**Comment by dxvid-pts** [comment]
I understand. Unfortunately I don't now the underlying code and don't have the time to investigate deeper.

In case there is interest to investigate, I reported full reproducable steps in the 3rd party's repo: https://github.com/syncfusion/flutter-widgets/issues/1986

Here is an interactive demo: https://temp-github-issue.pages.dev/
Works with Firefox/Safari (non-wasm).
Does not work with Chrome (wasm)

Only reproducable on the latest master.

**Comment by darshankawar** [comment]
@dxvid-pts 
Although it looks like a wasm rendering issue on chrome but currently it seems to be replicable with third party package. For us to make it actionable, would be good if we get a code sample out of the box.



> Only reproducable on the latest master.

wasm is currently only available on master.

**Comment by jason-simmons** [comment]
Reproduced this.  When this happens the app does not render as expected and logs a `Null check operator used on a null value` exception.

This behavior started with https://dart.googlesource.com/sdk/+/dd89732126f5777c946ffbefe584e0011cbdffad

@mkustermann

**Comment by mkustermann** [comment]
@jason-simmons Thanks for narrowing it down to a dart2wasm issue and even identify the commit!

I can confirm this is a bug, it doesn't happen in `-O0` mode but in the default `-O4` mode. The CL dropped implicit type checks on setters in `-O4` (which is correct) - though it turns out the code that generates the type check didn't only do that but also have a side-effect. This missing side-effect caused the issue.

 => Uploaded [cl/378800](https://dart-review.googlesource.com/c/sdk/+/378800)

**Comment by mkustermann** [comment]
The issue should be fixed on `main` and I've filed a cherry-pick request for the upcoming dart stable in https://github.com/dart-lang/sdk/issues/56374.

**Comment by dxvid-pts** [comment]
This works now on the latest master, great work!
