### ISSUE TITLE
Lexical or Preprocessor Issue 

### ISSUE THREAD

**Issue by Apliarte** [flutter/flutter#152068]
### Steps to reproduce

 flutter build ios

### Expected results

 flutter build ios ok

### Actual results

Lexical or Preprocessor Issue (Xcode): 'absl/base/config.h' file not found

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

Building com.apliarte.calcaapp for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 4VDPE23FDA
Running pod install...                                             59,8s
Running Xcode build...                                                  
Xcode build done.                                           22,6s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'absl/base/config.h' file not found
/Users/franciscomateomarquez/apps/calca_app/ios/Pods/abseil/absl/debugging/internal/demangle.h:18:9

[Paste your logs here]
```

</details>


### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale es)
    • Flutter version 3.22.3 on channel stable at /Users/franciscomateomarquez/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/franciscomateomarquez/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.93.20240702

[✓] Connected device (4 available)
    • iPad de Francisco (mobile)      • 21f7b82581be030f05da6ed220d5f9ca9fcd8634 • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                                    • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                                   • web-javascript • Google Chrome 126.0.6478.183
    ! Error: Browsing on the local area network for iPhone Apli 15 Plus. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by Apliarte** [comment]
Hello Flutter Community,

I'm encountering a build issue when trying to compile my Flutter application for iOS. The process fails during the Xcode build phase with a Lexical or Preprocessor Issue, specifically stating that the 'absl/base/config.h' file cannot be found. This issue arises after running `pod install`, which completes successfully, and during the automatic signing process for device deployment using a specified development team in the Xcode project.

Here are the relevant details of the build process:

- **Command Attempted**: Building com.apliarte.calcaapp for device (ios-release)
- **Development Team Specified in Xcode**: 4VDPE23FDA
- **Pod Install Duration**: 59.8 seconds
- **Xcode Build Duration**: 22.6 seconds
- **Error Message**: Failed to build iOS app. Lexical or Preprocessor Issue (Xcode): 'absl/base/config.h' file not found in `/Users/franciscomateomarquez/apps/calca_app/ios/Pods/abseil/absl/debugging/internal/demangle.h:18:9`

I have already tried cleaning the build folder and re-running `flutter pub get` followed by `pod install`, but the issue persists. The Flutter environment is set up correctly, and the iOS deployment target is set to iOS 13.0 in the Podfile.

Any insights or suggestions on how to resolve this issue would be greatly appreciated. Thank you in advance for your help!

Best regards,
Francisco Mateo Marquez

**Comment by darshankawar** [comment]
@Apliarte 
I am not sure if this is flutter specific. Check below links to see if they help resolving the issue.

https://github.com/grpc/grpc/issues/24366
https://stackoverflow.com/questions/63084845/absl-base-config-h-file-not-found
https://deku.posstree.com/en/flutter/error/lexical_or_preprocessor_file_not_found/

I also suggest you to file such issues in support channels like StackOverflow. Closing for now. If you disagree, write in comments and I'll reopen it.

**Comment by eunyeonggeum** [comment]
@Apliarte
is solved??
I have same problem :(
