### ISSUE TITLE
Flutter GPU has analysis errors that probably (?) were just hidden before

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#152002]
In https://github.com/flutter/engine/pull/53997, I'm moving more packages to the engine workspace pattern.

As part of that, `lib/gpu/**` starts [triggering analysis errors](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8742039653438280161/+/u/test:_analyze_dart_ui/stdout) that @jonahwilliams and I believe were always there:

```txt
Analyzing gpu...

  error - lib/src/buffer.dart:40:33 - Mixin can only be applied to class. - mixin_with_non_class_superclass
  error - lib/src/buffer.dart:88:17 - Only classes extending NativeFieldWrapperClass1 can be passed as Pointer. Pass as Handle instead. - ffi_native_only_classes_extending_nativefieldwrapperclass1_can_be_pointer
  error - lib/src/buffer.dart:88:17 - The type 'Bool Function(Pointer<Void>, Int, Int)' must be a subtype of 'bool Function(GpuContext, int, int)' for 'Native'. Try changing one or both of the type arguments. - must_be_a_subtype
  error - lib/src/buffer.dart:94:17 - Only classes extending NativeFieldWrapperClass1 can be passed as Pointer. Pass as Handle instead. - ffi_native_only_classes_extending_nativefieldwrapperclass1_can_be_pointer
  error - lib/src/buffer.dart:94:17 - The type 'Bool Function(Pointer<Void>, Handle)' must be a subtype of 'bool Function(GpuC
```

I am going to add an `exclude: ...` in the root `analysis_options.yaml` with a TODO to revisit this.

**Comment by bdero** [comment]
> I am going to add an exclude: ... in the root analysis_options.yaml with a TODO to revisit this.

This sounds good to me for unblocking. Let's assigned this to me and I can clean it up while doing the? I can clean it up while doing the refactors for https://github.com/flutter/flutter/issues/150953?

**Comment by jonahwilliams** [comment]
I found that I can make the errors go away by removing the dependency on sky_engine. The problem that fixes is that dart:nativewrappers library not being resolved.

No idea why that works.

**Comment by matanlurey** [comment]
This has all been since fixed, let's close it up.
