### ISSUE TITLE
How to solve the problem of blank map in dark mode?

### ISSUE THREAD

**Issue by QiuGangGit** [flutter/flutter#152096]
The loading tiles in dark mode are white, they should be black. I checked google maps and set dark mode to normal. Is there any setting for this flutter? I see that the json of the style does not set the tile background. I think this problem started in 2020 and there is no plan in the past four years.

**Comment by darshankawar** [comment]
@QiuGangGit 
When you file an issue, please try to use new issue template, fill out requested details along with code sample so that we can properly address the issue.
Closing due to lack of details.
