### ISSUE TITLE
App Crashes while using iphone mirroring in MacOS sequoia and ios 18, both on beta

### ISSUE THREAD

**Issue by AshishAcharya083** [flutter/flutter#152014]
### Steps to reproduce

1. Run the flutter app
2. Close iphone and start mirroing
3. After 1 or 2 minutes app crashes with following error message: 
Lost connection to device.
```
Failed to send request: {"jsonrpc":"2.0","id":"241","method":"getMemoryUsage","params":{"isolateId":"isolates/3432196114671855"}}
Error executing osascript: -2

the Dart compiler exited unexpectedly.

```
### Expected results

Expected result: App expected to work normally

### Actual results

Actual results: App Crashes with: 

```
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"241","method":"getMemoryUsage","params":{"isolateId":"isolates/3432196114671855"}}
Error executing osascript: -2

the Dart compiler exited unexpectedly.
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 15.0 24A5289h darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

```

</details>

**Comment by darshankawar** [comment]
@AshishAcharya083 


> 1. Run the flutter app

Does this crash occur with Flutter's counter app as well or only with your current app ?
