### ISSUE TITLE
flutter license script needs to be updated to pick up googletest license

### ISSUE THREAD

**Issue by aam** [flutter/flutter#15204]
From https://travis-ci.org/flutter/engine/builds/349851127?utm_source=github_status&utm_medium=notification:

```
Collecting licenses for third_party
      4226 of 9419 ████░░░░░░ 45% (0 missing licenses)  ../../../third_party/googletest/googletest/CHANGES           error searching for copyright in: ../../../third_party/googletest/BUILD.bazel
unmatched potential copyright and license statements; first twenty lines:
----8<----
# Copyright 2017 Google Inc.
# All Rights Reserved.
#
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#     * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
----8<----
```

**Comment by aam** [comment]
cc @Hixie

**Comment by aam** [comment]
I believe this should have been addressed as part of gtest->googletest PR https://github.com/flutter/engine/pull/4728.

**Comment by Hixie** [comment]
I don't understand why this wasn't caught by the pre-commit test. Was it a collision of two PRs each of which was fine on its own but not together?

**Comment by aam** [comment]
My theory is that license hash key was updated without making updates to the script/license file. I later hit it when the hash had to be updated again, so script executed for my update again produced same error.

**Comment by Hixie** [comment]
But how was the hash updated if the script doesn't run?

**Comment by aam** [comment]
Why the script was not run? It was run locally(again it's my hypothesis), that produced new hash,  updated license files as well as the warning. Warning was ignored, everything else was committed.

**Comment by Hixie** [comment]
This is resolved now I assume?

**Comment by aam** [comment]
Yep, closing
