### ISSUE TITLE
[windows] The windows app is random freezing in Windows 11

### ISSUE THREAD

**Issue by tanweilong** [flutter/flutter#152065]
### Steps to reproduce

We have a Kiosk app that running in windows 11 that has some video and images slideshow on it. The app is running ok at first. But after a while, sometimes hours, sometimes days, the app will just freeze there without any responding. I can see the app it's still able to response to user touch as we have play some click sound when the user pressing on the app. It's just that the screen does not response or move to the next screen after user pressing.

<details>

We have found that every time when the app got freezed. The Windows Event Viewer will catched `Display` event (with EventId = 4101).

<summary>Event 4101</summary>

```
Display driver igfx stopped responding and has successfully recovered
```

</details>

We also decided to downgrade back to use windows 10. So far we are still in the monitoring phase, to make sure the freeze issue it's forever gone. So far compared to windows 11, the windows 10 seems to be not having the random freeze issue. How can we resolve this issue in windows 11?

### Expected results

Make sure the app does not have the random freeze issue.

### Actual results

Windows 11 having random freeze issue

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![2](https://github.com/user-attachments/assets/36c971e2-b468-44bb-9970-08a35b6508e7)
![1](https://github.com/user-attachments/assets/5d2a7f99-a68e-4fe2-9e45-b73a99e24fb9)

</details>

### Flutter Doctor output

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19045.4651], locale en-MY)
    • Flutter version 3.19.6 on channel stable at C:\Users\User\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.20)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32929.386
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.128
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.113

[√] Network resources
    • All expected network resources are available.

•⁠  ⁠No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @tanweilong, does the machine go to sleep with the app running? Can you also take a look at https://github.com/flutter/flutter/issues/124194 to see if any of the comments matches your experience? It may be that this is an issue with intel graphics card as this happens with games like overwatch. See the link in https://github.com/flutter/flutter/issues/124194#issuecomment-2177995466

**Comment by tanweilong** [comment]
Hi @danagbemava-nc, the machine didn't go into sleep mode. It's always on with never sleep configured in Windows setting. Yes I think it's slightly similar to the case #124194. But the problem it's that I am facing this random freeze issue on Windows 11. But in Windows 10 so far no random freeze issues.

My video player is using
media_kit: ^1.1.10+1

And image is using
extended_image: ^8.2.1

Not sure is it cause by those library. Please advice on how I can more accurately identity the main issue that cause the random freeze. Since it's random freeze, I have trouble to identify the root cause of it. I only can see the event viewer captured EventId 4101 error and it might be the root cause but I am not too sure. Because whenever the freeze happens, I can see my application is still working fine based on Task Manager. (There is no "Not responding" appear on my application)

I also implemented error capture analytic using Sentry. But it didn't capture any error, so I assume this is caused by other factors.

**Comment by danagbemava-nc** [comment]
Hi @tanweilong, was this on only the device with the intel graphics driver? Are videos/slideshows constantly playing? Are you switching between different instances of your video player to load images? How do you implement the slideshows/video playing?

**Comment by tanweilong** [comment]
Hi, I will provide a demo projects shortly

**Comment by JiaoLiu** [comment]
I encountered the same issue while using remote software to connect to a Windows laptop. Even though the power settings are configured to prevent sleep mode or shutdown when the lid is closed, the display does not render. However, once I open the laptop, the display works fine. This issue may be due to the GPU not functioning when the laptop lid is closed.

**Comment by danagbemava-nc** [comment]
@JiaoLiu, I think yours might more resemble https://github.com/flutter/flutter/issues/124194

**Comment by Arvinth-Krishna** [comment]
@danagbemava-nc  is there any fix, I recently started getting this issue randomly.

![image](https://github.com/user-attachments/assets/1448c45f-7d8a-4c47-81e0-4b0087247704)

![image](https://github.com/user-attachments/assets/12cf8f6d-9718-4b98-8306-c98f822053e2)
