### ISSUE TITLE
Looks like impeller do not work as a expected;

### ISSUE THREAD

**Issue by Timur-hub21** [flutter/flutter#152028]
### Steps to reproduce

MacBook Pro 2020, Intel 5.
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale ru-BY)
    • Flutter version 3.22.2 on channel stable at /Users/e/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

### Expected results

Default scrolls

### Actual results

Unknown bug using impeller while scrolling or navigating.

### Code sample

no code example just run on impeller on ios simulators

### Screenshots or Video

https://github.com/user-attachments/assets/ea228503-f8b9-423c-a91c-7b29ec836d3c

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/e/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.91.1)
    • VS Code at /Users/e/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)
    • Timur’s iPhone (mobile) • 00008101-001C24C81440001E            • ios            • iOS 17.5.1 21F90
    • iPhone 15 Pro (mobile)  • F910194E-B4C8-4C49-B427-8B14F11AE6D4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 126.0.6478.183

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": Connection refused

**Comment by danagbemava-nc** [comment]
Hi @Timur-hub21, this was reported in https://github.com/flutter/flutter/issues/148660 and has since been fixed. The fix for this should be available in stable 3.22.3 which was released a couple of days ago, see https://github.com/flutter/flutter/issues/148660#issuecomment-2237193254. Kindly upgrade to the new version of flutter stable. 

I'll be closing this since it has already been fixed in the latest hotfix to flutter. If you still experience this on stable 3.22.3, kindly leave a comment below and I will reopen this. 

Thank you
