### ISSUE TITLE
When you scroll a list of images in a ListView one way and then back to the beginning there's a flash of white as it nears the start of the list.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#15218]

**Comment by Hixie** [comment]
Can you provide code to reproduce this? We had this bug a while back but I thought we'd fixed it.

**Comment by xster** [comment]
Is this still reproducible after syncing past #14789?

**Comment by xster** [comment]
Based on the symptoms, I'm fairly confident that it was solved. Closing.
