### ISSUE TITLE
High usage of User Data on Android

### ISSUE THREAD

**Issue by simonesestito** [flutter/flutter#15215]
I've just tried Flutter, but I noticed that the app on Android uses almost 14MB of user data.

**How to reproduce** 

```
flutter create demo1
cd demo1
flutter build apk --release
```
And install the app-release apk.
When you will open the app, 14MB of User Data will be used.

**Tested on** 

Nexus 5X
Android 8.1.0
Latest Flutter version (installed yesterday)

![](https://i.imgur.com/csYSa8w.png)

**Comment by Hixie** [comment]
cc @szakarias

**Comment by szakarias** [comment]
Duplicate of #14704
