### ISSUE TITLE
[Docs] Hotfixes-to-the-Stable-Channel.md

### ISSUE THREAD

**Issue by AlexDochioiu** [flutter/flutter#152162]
### Steps to reproduce

The hotfixes document seems to have been deleted? It was really useful to see what's changed.

https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md

### Expected results

.

### Actual results

.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by balu-vadivel** [comment]
Yes, its gone. I'm also looking for this

**Comment by danagbemava-nc** [comment]
Hi @AlexDochioiu @balu-vadivel, this now lives in https://github.com/flutter/flutter/blob/master/CHANGELOG.md 

The change was made in https://github.com/flutter/flutter/pull/151931.

Sorry for any inconvenience. 

cc @itsjustkevin on whether we need to announce this in some way since people may not be aware of this change yet

**Comment by deandreamatias** [comment]
> Hi @AlexDochioiu @balu-vadivel, this now lives in https://github.com/flutter/flutter/blob/master/CHANGELOG.md
> 
> The change was made in #151931.
> 
> Sorry for any inconvenience.
> 
> cc @itsjustkevin on whether we need to announce this in some way since people may not be aware of this change yet

I think that nice thing to do is change the url here: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

**Comment by cezaryjk** [comment]
Hi, 
Also link in paragraph 
_

> "Note
> For information about bug-fix releases, check out [Hotfixes to the Stable Channel](https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md) on the Flutter wiki."

_ 
on 
https://docs.flutter.dev/release/release-notes 
should be updated.

**Comment by AlexDochioiu** [comment]
In the past, I've seen some page left behind with a Note that the content was moved to another page (and the page link). I think that would be a better approach at least for a while.

**Comment by itsjustkevin** [comment]
> cc @itsjustkevin on whether we need to announce this in some way since people may not be aware of this change yet

@danagbemava-nc comms are currently being generated.

> https://docs.flutter.dev/release/release-notes should be updated.

@cezaryjk done in https://github.com/flutter/website/pull/10939.

> I think that nice thing to do is change the url here: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel.

@deandreamatias Done.

@AlexDochioiu thanks for opening up this issue, if you come across anymore related issues, feel free to tag me.

**Comment by feinstein** [comment]
@itsjustkevin it's broken here https://docs.flutter.dev/release/release-notes/release-notes-3.22.0

**Comment by itsjustkevin** [comment]
> @itsjustkevin it's broken here https://docs.flutter.dev/release/release-notes/release-notes-3.22.0

Thank you!  Addressed in https://github.com/flutter/website/pull/10946.

**Comment by deandreamatias** [comment]
I think that can close this issue

**Comment by danagbemava-nc** [comment]
Closing this since it appears all pending issues have been resolved. If anyone notices there's anything we missed, kindly leave a comment below and I will reopen this. 

Thank you
