### ISSUE TITLE
[camera] On ios taking a picture on front camera is mirrored to the shown preview, but recording a video is not mirrored.

### ISSUE THREAD

**Issue by arthurpuha** [flutter/flutter#152105]
### Steps to reproduce

1. Look at preview
2. Take photo
3. See that taken photo is mirrored
4. Come back to preview
5. Record video
6. See that recorded video is not mirrored

### Expected results

1. Either mirror both video or photo as on android - or dont mirror both.

### Actual results

Photo is mirrored, but video is not

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@arthurpuha 
Can you provide reproducible code sample that shows the reported behavior ?
Also, provide camera plugin version and iOS version and device details in which you are seeing the behavior.

**Comment by arthurpuha** [comment]
Hello, so its latest camera plugin - 0.11.0+1, camera_avfoundation - 0.9.16. I am testing on Iphone X with iOS version - 16.7.8. 
Code to reproduce:

import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

late List<CameraDescription> _cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  _cameras = await availableCameras();
  runApp(MaterialApp(home: const CameraApp()));
}

/// CameraApp is the Main Application.
class CameraApp extends StatefulWidget {
  /// Default Constructor
  const CameraApp({super.key});

  @override
  State<CameraApp> createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  late CameraController controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(_cameras[0], ResolutionPreset.max);
    controller.initialize().then((_) {
      controller.setDescription(_cameras.firstWhere(
          (descr) => descr.lensDirection == CameraLensDirection.front));
      if (!mounted) {
        return;
      }
      setState(() {});
    });
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  Future<void> _takePhoto(BuildContext context) async {
    final navigator = Navigator.of(context);

    final photoFile = await controller.takePicture();

    navigator.push(
      MaterialPageRoute<Widget>(
        builder: (ctx) => ImageView(
          file: File(photoFile.path),
        ),
      ),
    );
  }

  Future<void> _recordVideo(BuildContext context) async {
    final navigator = Navigator.of(context);

    await controller.startVideoRecording();

    await Future.delayed(Duration(seconds: 4));
    final videoFile = await controller.stopVideoRecording();
    navigator.push(
      MaterialPageRoute(
        builder: (ctx) => VideoView(
          videoFile: File(videoFile.path),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    if (!controller.value.isInitialized) {
      return Container();
    }
    return Scaffold(
      appBar: AppBar(),
      body: CameraPreview(controller),
      floatingActionButton: Row(
        children: [
          FloatingActionButton(
            onPressed: () => _takePhoto(context),
            child: Icon(Icons.camera),
          ),
          FloatingActionButton(
            onPressed: () => _recordVideo(context),
            child: Icon(Icons.video_call),
          ),
        ],
      ),
    );
  }
}

class ImageView extends StatelessWidget {
  const ImageView({required this.file, super.key});

  final File file;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(child: Image.file(file)),
    );
  }
}

class VideoView extends StatefulWidget {
  const VideoView({required this.videoFile, super.key});

  final File videoFile;

  @override
  State<VideoView> createState() => _VideoViewState();
}

class _VideoViewState extends State<VideoView> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.file(widget.videoFile)
      ..initialize().then((_) {
        _controller.setLooping(true);
        _controller.play();
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: _controller.value.isInitialized
          ? Center(
              child: AspectRatio(
                aspectRatio: _controller.value.aspectRatio,
                child: VideoPlayer(_controller),
              ),
            )
          : Container(),
    );
  }
}

**Comment by darshankawar** [comment]
Thanks for the update. Upon running the code, I see that it uses front camera, ie, selfie mode in which the picture is mirrored but video is played properly. That indicates, you are hitting https://github.com/flutter/flutter/issues/27650, so please follow-up in it for further updates.
Closing this as a duplicate.
