### ISSUE TITLE
[impeller] create automated test for catching blur shimmering

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#152195]
On multiple occasions that we've edited the blur code that passes golden tests but when using the blur we find that there is shimmering when animating aspects of the blur (example: https://github.com/flutter/engine/pull/53760#issuecomment-2246328197).  "Shimmering" here is defined as large differences in the blurred content for the same input pixels considering small changes to the blurs other parameters.

Examples from the past:
1) Slowly sweeping the sigma value
1) Moving the clip rect around for a backdrop filter

These regressions are bad enough to merit reverting PRs so we should have an automated test that will block them to avoid having to be reverted later.

I propose the automated test will sweep through all the values of sigma and perform a [RMSE](https://en.wikipedia.org/wiki/Root_mean_square_deviation) comparison between the outputs of different values of sigma.

```rust
let mut left : Image = CalculateBlur(sigma: 0.0)
for sigma in range(0.1, 700, step: 0.1) {
  let right : Image = CalculateBlur(sigma: sigma);
  let error : f64 = RMSE(left, right);
  expect(error < MAX_ALLOWED_ERROR);
  left = right;
}
```

**Comment by jonahwilliams** [comment]
If it works, this seems like a good idea.
