### ISSUE TITLE
Flutter engine presubmit `Linux linux_web_engine` fails with `code = InvalidArgument desc = build.summary_markdown: too big to accept (6555 > 4000 bytes)`

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#152177]
PR:
https://github.com/flutter/engine/pull/53574

Build:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_web_engine/24770/infra

Failing backend task:
https://chromium-swarm.appspot.com/task?id=6af4ed1fa3106110&o=true&w=true

Error:
```
[E2024-07-22T14:42:15.462956-07:00 14289 0 annotate.go:273] original error: rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (6555 > 4000 bytes)
```

**Comment by christopherfujino** [comment]
I previously encountered this during a stable release: https://github.com/flutter/flutter/issues/151247

I will apply the workaround there on the main branch...

**Comment by christopherfujino** [comment]
Put out https://flutter-review.googlesource.com/c/recipes/+/58620

**Comment by christopherfujino** [comment]
closed with https://flutter-review.googlesource.com/c/recipes/+/58620
