### ISSUE TITLE
[IOS]How to make my own flutter package support ios arm64 architecture?

### ISSUE THREAD

**Issue by ArthurHsing** [flutter/flutter#152150]
### Steps to reproduce

I installed a flutter dependency package developed by ourselves in my project, and the iOS native part is written in Objective-C source code, which contains .m and .h files. When compiling the iOS app, an error message appears: "Undefined symbols for architecture arm64". After consulting the relevant flutter documentation, I learned that it is probably because my flutter dependency package does not support the arm64 architecture (it may also be other reasons). So what should I do now?

Document Links：
https://docs.flutter.dev/add-to-app/ios/project-setup#mitigate-known-issue-with-apple-silicon-macs

### Actual results

I tried to exclude the arm64 architecture according to the documentation, but it still reports this error. 

### Logs

<details open>
<summary>Logs</summary>

```console

❌  Undefined symbols for architecture arm64
> Symbol: _OBJC_CLASS_$_BuglyCrashPlugin
> Referenced from: objc-class-ref in MPGDTAction.o
❌  ld: symbol(s) not found for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 2.10.5, on macOS 14.3.1 23D60 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.5 at /Volumes/data/workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 years, 3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bkdevops/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/bkdevops/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.15.2
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

```

</details>

**Comment by ArthurHsing** [comment]
Is it caused by the flutter version? My current flutter version is 2.10.5 for mac, and I saw from another issue that flutter 2.10.5 for mac does not support arm64. Is this the reason? But some of my dependencies are in the form of xcframework, and then there will be errors like undefined symsbols for arm64.

https://github.com/flutter/flutter/issues/100638#issuecomment-1076937915

**Comment by NeariX67** [comment]
Any reason you are using this 27 month old version?

**Comment by ArthurHsing** [comment]
> Any reason you are using this 27 month old version?

This is an old project that I just took over. Due to some issues, it must be re-released, but the Apple App Store requires building based on the xcode15 build environment (no errors will be reported when building with xcode14), and then the current problem occurs. 

If I can confirm that it is a problem with the flutter version, I will upgrade it; but upgrading flutter may bring many other dependency-related issues (such as version incompatibility, API changes), so I want to confirm what the problem is first.

**Comment by ArthurHsing** [comment]
I found the location of the compiled MPGDTAction.o file, and then checked the contents of MPGDTAction.d in the same directory. It contains the header file of BuglyCrashPlugin, the path is
`./ios/Pods/Headers/Public/bugly_crash/BuglyCrashPlugin.h`
Then I went to find the location of the implementation file of BuglyCrashPlugin, the path is
`./build/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64`,

Is there an error in the import path of BuglyCrashPlugin? I wonder if the header file of BuglyCrashPlugin and its implementation file .o are in two different directories, so is it not recognized?

In addition, I did not find any content about BuglyCrashPlugin or bugly_crash in the `./ios/Pods` directory (maybe it is not a framework?)

**Comment by darshankawar** [comment]
@ArthurHsing 
You will need to upgrade your setup to have latest stable, latest xcode version so that it uses latest and greatest config to run the app.
BuglyCrashPlugin is third party, so you will need to report this in dedicated repo to check if it supports arm64 arch or not.
Upon upgrading, you might see other conflicts that you will need to resolve by upgrading pods and to check if the reported issue still persist or not.

**Comment by ArthurHsing** [comment]
> @ArthurHsing You will need to upgrade your setup to have latest stable, latest xcode version so that it uses latest and greatest config to run the app. BuglyCrashPlugin is third party, so you will need to report this in dedicated repo to check if it supports arm64 arch or not. Upon upgrading, you might see other conflicts that you will need to resolve by upgrading pods and to check if the reported issue still persist or not.

I think directly upgrading the setup is a large amount of work and may not solve the problem. I have hardly found any evidence on the Internet that this problem is caused by the flutter version.

**Comment by ArthurHsing** [comment]
I have now found another possible cause of the problem: I opened the .xcworkspace file through Xcode, and then selected the Pods project in it. 
Then I found that the options like Architectures, BaseSDK, and Supported Platforms in the Architectures of the Buid Settings were all adapted for Mac, not iOS. 

This seems a bit strange, but the .xcworkspace file seems to be automatically generated by flutter or cocoapods? Is there a way to change the configuration in the figure below through code?
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/cf955814-2a07-4bf8-a1ec-2ed2bc4e8ca8">

**Comment by darshankawar** [comment]
Most likely you will need to raise this in apple forum. See https://developer.apple.com/documentation/xcode/configuring-the-build-settings-of-a-target

**Comment by ArthurHsing** [comment]
https://stackoverflow.com/questions/77139621/xcode-15-undefined-symbols-linker-command-failed-with-exit-code-1-use-v-to-s
This method solved it. The reason why it didn't work before was because I added other linker flags settings in the 'xcodebuild archive' build command, which then overwrote my settings in Xcode.
