### ISSUE TITLE
[webview_flutter_android]  onNavigationRequest dosn't callback on Android on some url

### ISSUE THREAD

**Issue by lwj1994** [flutter/flutter#152168]
### Steps to reproduce

flutter_webview 4.8.0

### Expected results

call onNavigationRequest on Android

### Actual results

not call onNavigationRequest on Android

### Code sample

```
final delegate = NavigationDelegate(
      onProgress: (p) {
        debugPrint("onProgress $p");
      },
      onUrlChange: (url) {},
      onPageStarted: (url) {
        debugPrint("_onPageStarted $url");
      },
      onPageFinished: (url) {
        debugPrint("onPageFinished $url");
      },
      onWebResourceError: (WebResourceError error) {},
      onNavigationRequest: (NavigationRequest request) {
        print("onNavigationRequest callback");
        return NavigationDecision.navigate;
      },
    );
    _controller.setNavigationDelegate(delegate);
    _controller.loadRequest(Uri.parse("https://events.linjieapp.com/?project=linjie_bluelock"));
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale
    en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.88.1)

**Comment by danagbemava-nc** [comment]
Hi @lwj1994, I just tested the plugin example app and the callback is called when I attempt to navigate. Please provide a complete minimal reproducible code sample with detailed steps to reproduce so that we can properly investigate this issue. 

Thank you

**Comment by lwj1994** [comment]
@danagbemava-nc the case is on 'https://events.linjieapp.com/?project=linjie_bluelock'
```dart
final delegate = NavigationDelegate(
      onProgress: (p) {
        debugPrint("onProgress $p");
      },
      onUrlChange: (url) {},
      onPageStarted: (url) {
        debugPrint("_onPageStarted $url");
      },
      onPageFinished: (url) {
        debugPrint("onPageFinished $url");
      },
      onWebResourceError: (WebResourceError error) {},
      onNavigationRequest: (NavigationRequest request) {
        print("onNavigationRequest callback");
        return NavigationDecision.navigate;
      },
    );
    _controller.setNavigationDelegate(delegate);
    _controller.loadRequest(Uri.parse("https://events.linjieapp.com/?project=linjie_bluelock"));
```


hi i found url `https://events.linjieapp.com/?project=linjie_bluelock` is not work on Android. but it is ok on iOS

**Comment by danagbemava-nc** [comment]
Hi @lwj1994, according to the documentation, this seems to be working as expected. You haven't performed any navigation in the webview so there isn't anything for onNavigationRequest to report back. iOS & android do behave differently in how they handle the interactions in the webview tho. See https://github.com/flutter/flutter/issues/47218 https://pub.dev/documentation/webview_flutter/latest/webview_flutter/NavigationDelegate/onNavigationRequest.html

**Comment by lwj1994** [comment]
@danagbemava-nc no，if replace 'http://google.com' is ok  
and performed new Navigation is not work.
