### ISSUE TITLE
Keypad covers text field on Android version 10

### ISSUE THREAD

**Issue by kyeongrokKwak** [flutter/flutter#152155]
### Use case

I am currently developing my app with flutter and my test device for android is "model SM N960N" which is Android 10 version.
First of all, I have already set "**resizeToAvoidBottomInset: true**" to push Textfield when keypad comes out.
 Issue : When tap the TextField and keypad is come out, the keypad cover the TextField.
I have tested not only iOS(my cell phone) but also another android device which is latest version of Android. Except my test device, all the latest versions of device are worked I mean, when tap the TextField area and keypad is come out, TextField is pushed as I expected.

### Proposal

What I want is that TextField has to be pushed when keypad is come out. 
I mean the keypad should not be covered TextField area.

Please reply on my own e-mail

kyeongrok9@gmail.com

**Comment by darshankawar** [comment]
@kyeongrokKwak 
If it is only occuring on said device, then the behavior could be device specific. Can you provide a short video of the behavior ?
I tried on S10+ running Android 12 which works properly. Also, provide device details / config.
