### ISSUE TITLE
RenderBox not laid out

### ISSUE THREAD

**Issue by Ayush2006128** [flutter/flutter#152107]
My app requires functionality of uploading images so i am building a custom widget for that
but this is happening
<img width="400" alt="Screenshot 2024-07-22 203209" src="https://github.com/user-attachments/assets/c58530ef-fbd4-4f4d-9dd5-e600488231b8">

Here is my code for that widget

[https://github.com/Ayush2006128/ai_teacher/blob/main/lib/widgets/prompt_image_container.dart]()

**Comment by darshankawar** [comment]
@Ayush2006128 
Your question / issue is better suited for support channels like StackOverflow, as it looks like a code implementation issue rather than bug.

Closing from here.
