### ISSUE TITLE
flutter.io's "Flutter is now in Beta!   Learn More ." results in white text on offwhite background

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#15216]
If your browser window is sufficiently wide the Flutter is now in beta text is not on top of the blue triangle and is thus hard to read.

**Comment by Hixie** [comment]
cc @filiph

**Comment by filiph** [comment]
Thanks for filing this. I remember I only tested this on as wide a window as I could get on my workstation before we launched.

@apwilson, could you please provide me with the resolution at which you're experiencing the issue?

**Comment by apwilson** [comment]
I believe its 2560x1600

**Comment by Hixie** [comment]
You can probably reproduce it on a lower-res screen by zooming out.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1848](https://github.com/flutter/website/issues/1848) via [**ZenHub**](https://www.zenhub.com/)
