### ISSUE TITLE
ffi not properly decoding Pointer<Char>

### ISSUE THREAD

**Issue by scottandrewzip** [flutter/flutter#152256]
### Steps to reproduce

I trying to use libiMobileDevice using ffi. However it is having trouble with a structure that is passed into the callback. The structure is defined in C as:

```
typedef struct {
	enum idevice_event_type event; /**< The event type. */
	const char *udid; /**< The device unique id. */
	enum idevice_connection_type conn_type; /**< The connection type. */
} idevice_event_t;
```

when i run ffigen i get the following: 

```
final class idevice_event_t extends ffi.Struct {
  /// < The event type.
  @ffi.UnsignedInt()
  external int event;

  /// < The device unique id.
  external ffi.Pointer<ffi.Char> udid;

  /// < The connection type.
  @ffi.UnsignedInt()
  external int conn_type;
}
```

My callback looks like so:

```
  void onDeviceChanged(Pointer<idevice_event_t> device, Pointer<Void> data) {
    idevice_event_t event = device.ref;

    var value = event.udid.cast<Utf8>().toDartString();

    log(value);
  }
```

### Expected results

I would expect it to derefernce the string properly.

### Actual results

The problem is that the `toDartString` fails with missing delimiter. When i poke around a bit the codeUnits are not characters but the address of the string (can verify this by looking at the same code in C in a memory viewer).  Pointer<Pointer<Char>> doesn't work either. How can i properly decode the string. One more hint in the memory viewer the string is not right after the `event` int. What is after it is a pointer address.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dcharkes** [comment]
> When i poke around a bit the codeUnits are not characters but the address of the string

Then I would have expected:

```c
const char **udid;
```

And FFIgen would have generated:

```dart
external ffi.Pointer<ffi.Pointer<ffi.Char>> udid;
```

You can try to verify this by modifying the code to be `ffi.Pointer<ffi.Pointer<ffi.Char>>` and doing `.value.toDartString()`.

Side question: Are you sure your string is UTF-8 encoded? You might simply have an ascii string.
Another side question: I don't know what UDID is, but if it's fixed length it might also not be 0 terminated.

**Comment by scottandrewzip** [comment]
I am sure the sting is null terminated and well formed (looked at the memory in XCode). The string is 0 terminated and is all ascii encoded.. I looked at everything in C using Xcode and the memory viewer.

**Comment by scottandrewzip** [comment]
Using  the pointer to pointer gives an invalid address for the value.. 

```
Pointer (Pointer: address=0xb9401fe8b9001fe0)
address = -5098039693786734624
hashCode = 742544397
```

Thats not working either. Of course trying to convert to UTF8 fails.. I have to do a `value.cast<Utf8>` to be able to create dart string.

**Comment by moffatman** [comment]
Hmmm native callback. How are you dealing with threads here?

**Comment by dcharkes** [comment]
> Hmmm native callback. How are you dealing with threads here?

If you're using `NativeCallable.listener` you need to pass ownership of the pointer to Dart. If the caller from C++ frees the string upon returning, the Dart callback hasn't been run yet (it's queued in the microtask queue, like all async code).

If you're on the Dart thread you can use `NativeCallable.isolateLocal`.

We don't have support for arbitrary thread blocking callbacks yet (https://github.com/dart-lang/sdk/issues/54554).

**Comment by scottandrewzip** [comment]
if I use isolateLocal then i get an error that we can't run callbacks outside the isolate. So basically i need to write some wrappers around the code.

**Comment by darshankawar** [comment]
@dcharkes Should this issue move to dart-lang ?

**Comment by dcharkes** [comment]
> if I use isolateLocal then i get an error that we can't run callbacks outside the isolate. So basically i need to write some wrappers around the code.

👍  Yes, rewriting the code to copy the string and pass ownership to Dart.

cc @liamappelbe another use case of where `NativeCallable.blocking` would be very nice to have (https://github.com/dart-lang/sdk/issues/54554).

> @dcharkes Should this issue move to dart-lang ?

I think this issue can be closed.

@scottandrewzip please let me know if you're still facing issues after passing ownership a copy of the string to Dart.
