### ISSUE TITLE
SKPriceLocaleMessage can get null countryCode

### ISSUE THREAD

**Issue by Glydric** [flutter/flutter#152242]
### Steps to reproduce

I build an app for ios (an android but the bug refers to ios) and connected everything to apple connect and xcode storekit config file, now when I try to run queryProductDetails() with the productID it gets the reply from apple storekit, but have the field that will go into countryCode in the function SkPriceLocaleMessage.decode(Object result) in file messages.g.dart as null, this will lead to an error and everything fails

### Expected results

to get the ProductDetails

### Actual results

This is an output of the readvalue(buffer) added into adValueOfType (line 542) same file 
`[sub_name, Premium Sub, no ADS, [€, EUR, null], 12345678, 4.99, [1, 2], null, []]`

### Code sample

<details open><summary>Code sample</summary>

```dart

  // The in-app-purchase instance
final InAppPurchase _iAP = InAppPurchase.instance;
  if (Platform.isIOS) {
    _iAP
        .getPlatformAddition<InAppPurchaseStoreKitPlatformAddition>()
        .setDelegate(null);
  }
  final Stream<List<PurchaseDetails>> purchaseStream = _iAP.purchaseStream;

  _subscription = purchaseStream.listen(
    _onPurchaseUpdated,
    onError: (e) => {print(e)},
  );
  final bool available = await _iAP.isAvailable();
  if (!available) {
    print("Product not available");
    return;
  }

  final ProductDetailsResponse response = await _iAP.queryProductDetails({
    productId,
  });

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console                                                                                      
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[!] Android Studio (not installed)
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@Glydric 
Check if below issues help in your case or not:

https://github.com/flutter/flutter/issues/147230
https://github.com/flutter/flutter/issues/141627

**Comment by Glydric** [comment]
For me the fix was to downgrade to a previous version as reported by https://github.com/flutter/flutter/issues/147565#issuecomment-2085155152

**Comment by darshankawar** [comment]
Ok, so looks like you are hitting https://github.com/flutter/flutter/issues/147565 ? If so, you can follow-up in it for further updates.
