### ISSUE TITLE
[in_app_purchase] Can't retrieve and purchase a subscription

### ISSUE THREAD

**Issue by VDNgo-Powergate** [flutter/flutter#152228]
I've set up and created a subscription but I can't retrieve any of the subscriptions when querying for product details. But when I use the product's id the query is successful. Can anyone help and explain to me?

**My expected:**  _Can purchase subscription_
**Version:** in_app_purchase: ^3.2.0
```

> My code

final String _kLifetimeSubscriptionId = 'l0420239999'; // subscription's id
final String _kLifetimeSubscriptionId = 'l04202399'; // product's id

final ProductDetailsResponse productDetailResponse = await _inAppPurchase.queryProductDetails({_kLifetimeSubscriptionId,}.toSet());
```

> Setup subscriptions

![image](https://github.com/user-attachments/assets/5af3857c-dcea-4061-855d-61c547d39f15)

> Setup in-app products

![image](https://github.com/user-attachments/assets/698b56f3-f608-42a0-bd01-f9e01ea4ca67)

**Comment by darshankawar** [comment]
@VDNgo-Powergate 
Your question / issue is better suited for support channels like StackOverflow, so please raise it there.
Closing from here, as this seems more of code assistance report than a bug.
