### ISSUE TITLE
Various tweaks for Swift Package Manager migration docs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#152276]
After a walkthrough, we found this list of tweaks we can make to the SPM migration docs

* [x] update the SPM docs to teach them how to not download artifacts when switching channel (since they are going to run upgrade next anyway)
* [x] for comments in the Package.swift file, which themselves are instructions, split out the sub-steps (remove platforms you don’t support, update the target and library names.)
* [x] for comments in the Package.swift file, _consider_ Update the source code to fail to compile when someone needs to update the code inside.
    * Consider using [compiler diagnostic directives](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0196-diagnostic-directives.md) like `#warning("TODO: hello world")` 
* [ ] make it more obvious to change macos and ios. for example, call out the "choose your target" instruction very explicitly in its own paragraph/note/block/thing. And, trying an explicit `<<ios|macos>>` placeholder
    * [ ] https://github.com/flutter/website/issues/10974 
* [x] Step 13.2, Question: clarify "the example app" as "the plugin's example app"
* [x] Step 13.2 , Question: hint that running the example app will migrate the project to SPM
* [x] 13.3 , add explicit instructions to cd into the right directory
* [x] Update the plugin migration docs to explain you shouldn’t check-in the modifications Flutter does to your project to add SPM integration.

**Comment by sethladd** [comment]
cc @loic-sharma

**Comment by loic-sharma** [comment]
With the exception of the `choose your target` feedback (which has been moved to https://github.com/flutter/website/issues/10974), all items are addressed. Closing!

**Comment by sethladd** [comment]
Thanks so much!!
