### ISSUE TITLE
Change log does not exist

### ISSUE THREAD

**Issue by han1548772930** [flutter/flutter#152201]
### Type of Request

bug

### Infrastructure Environment

https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md

### What is happening?

Change log does not exist

### Steps to reproduce

https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md

**Comment by mafanwei** [comment]
yes

**Comment by han1548772930** [comment]
#152162
