### ISSUE TITLE
License Declaration for CocoaPods

### ISSUE THREAD

**Issue by dominicmh** [flutter/flutter#152232]
### Steps to reproduce

* See Podspec file: https://github.com/CocoaPods/Specs/blob/master/Specs/c/0/4/Flutter/3.13.0/Flutter.podspec.json
* See Pod page, where no license is listed: https://cocoapods.org/pods/Flutter

### Expected results

Flutter's license for its Pod (CocoaPods) is properly declared as "BSD-3-Clause" in Podspec.
This helps automation tools parse the license under use. As a result, policies can be defined or licenses reported.

### Actual results

The declared license is "BSD", which doesn't uniquely identify a license.

### Code sample

<details open><summary>Code sample</summary>
As an example, SBOM generation using [cyclonedx-cocoapods](https://github.com/CycloneDX/cyclonedx-cocoapods):

```bash
gem install cyclonedx-cocoapods
cyclonedx-cocoapods -p .
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Keeping the issue open and labeling for team's tracking, as, [this](https://github.com/flutter/flutter/issues/126225#issuecomment-1540463308) comment shows the scope of work being done by Flutter team on this pod.

**Comment by jmagman** [comment]
This sounds like an issue with CocoaPods since the published podspec is correct.  Possibly related to https://github.com/CocoaPods/cocoapods.org/issues/422 since they also weren't able to match the README either.
