### ISSUE TITLE
Delete hard-coded AVD_CIPD_IDENTIFIER from recipes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#152265]
In Flutter's LUCI recipes, we hard-code the constant `AVD_CIPD_IDENTIFIER`, which maps to a CIPD instance ([src](https://flutter.googlesource.com/recipes/+/7e578fd215541e4b8336a8e96a2859bca089b939/recipe_modules/android_virtual_device/api.py#9)).

This constant is only referenced once, as the fallback to getting the environment variable `'AVD_CIPD_VERSION'` ([src](https://flutter.googlesource.com/recipes/+/7e578fd215541e4b8336a8e96a2859bca089b939/recipe_modules/android_virtual_device/api.py#66)).

This environment gets set by the `avd_cipd_version()` method of the flutter_deps recipe module, based on the version in the .ci.yaml entry's "version" key: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/flutter_deps/api.py#150

Which is set for flutter/flutter in the .ci.yaml: https://github.com/flutter/flutter/blob/06e915f86907b96fd3483130bdc9ad895732a571/.ci.yaml#L51

Thus, I don't think we ever use this hard-coded version. Also, if for some reason we did NOT read the `avd_cipd_version` from the .ci.yaml, rather than defaulting to some hard-coded version in the recipes, we should infra failure instead so that we can fix the .ci.yaml config.

**Comment by camsim99** [comment]
Completed by https://flutter-review.googlesource.com/c/recipes/+/58740.

Note that this was a direct consequence of https://github.com/flutter/flutter/issues/142261, so `AVD_CIPD_IDENTIFIER` was going unused for a couple of months.
