### ISSUE TITLE
 Execution failed for task ':app:minifyReleaseWithR8' while running flutter build apk #99479 

### ISSUE THREAD

**Issue by samgetbitmoney** [flutter/flutter#152208]
### Steps to reproduce

I'm trying to create a build for a Flutter Android application, but everytime I run flutter build apk --release I got this build failed with exception error.

I already have updated the SDK to version 24 and change the gradle.properties file to add r8 = true, but nothing changes. There's another thing, I can build my app using flutter build apk --debug it's the only way, but trust me or not, the APK size it's greater than 400mb (around 455mb)There's literally 1 mb of assets inside the assets folder and a couple libs inside the yaml.

### Expected results

I need to build the apk

### Actual results

Execution failed for task ':app:minifyReleaseWithR8'
A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

[android build gadle.txt](https://github.com/user-attachments/files/16358575/android.build.gadle.txt)
[App Build gradle.txt](https://github.com/user-attachments/files/16358577/App.Build.gradle.txt)
[Pubspec.yaml.txt](https://github.com/user-attachments/files/16358578/Pubspec.yaml.txt)
[verbose.txt](https://github.com/user-attachments/files/16358580/verbose.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4651], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2022.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@samgetbitmoney 
Looking at your pubspec.yaml file, you are using lot of dependencies, so could be that, you will need to upgrade each of them to the latest and then see if it helps to resolve or not, because I am guessing the error could be related with one of the dependencies not uptodate, so you will need to remove or upgrade them one by one and check which one could be causing it. You will also need to upgrade  to newer version of the Kotlin Gradle plugin.

It is unlikely to be a framework issue.

**Comment by samgetbitmoney** [comment]
Sure let me check

**Comment by samgetbitmoney** [comment]
@darshankawar  i removed some unused dependencies.....  issue was with the flutter segments package

**Comment by darshankawar** [comment]
Good to know. Closing as resolved.
