### ISSUE TITLE
Gallery crashes when turning on VoiceOver on TextField screen

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#15224]
Navigate to the TextField demo and turn on VoiceOver, the app consistently crashes when doing that.

No crash when VoiceOver is turned on on any other screen.

This is in the current beta build from TestFlight (v0.1.8 (1)).

/cc @yjbanov

**Comment by yjbanov** [comment]
Tried it on an iPhone 6 and an iPhone X just now. This does not seem to be reproducible any more. Closing.
