### ISSUE TITLE
我在项目中集成getx插件，在使用其中get方法请求时，后台正对url进行校验时报错，发现在uri在再用replace方法时针对value为""时拼接的url存在问题

### ISSUE THREAD

**Issue by WeJeson** [flutter/flutter#152244]
getx:4.6.5
入参参数：{notaryId: , roleId: 4339ea21-b76e-479a-9d0f-26cee2a5b48b}
发送的get请求URL地址：https://xxxxx.com:9000/user-api/cgz/user/getUserInfo?notaryId&roleId=4339ea21-b76e-479a-9d0f-26cee2a5b48b
java后台通过String lowerValue = URLDecoder.decode(value, enc: "UTF-8").toLowercase()校验失败
同样的方式使用Android发送get请求的url地址为https://xxxxx.com:9000/user-api/cgz/user/getUserInfo?notaryId=&roleId=4339ea21-b76e-479a-9d0f-26cee2a5b48b
java后台通过String lowerValue = URLDecoder.decode(value, enc: "UTF-8").toLowercase()校验通过
通过跟踪源码uri.dart时发现如下
![image](https://github.com/user-attachments/assets/156205a8-7d34-4680-8c5d-dae9c585eb37)
希望有所帮助

**Comment by darshankawar** [comment]
Closing as this seems to be related to getx package which is third party. Please report in dedicated repo.
Also, as a note, when opening an issue, please use English so that it will help us to read the issue properly.
