### ISSUE TITLE
Errors with file GeneratedPluginRegistrant.java

### ISSUE THREAD

**Issue by KingdomVietNam** [flutter/flutter#152296]
1.  I have tried to add plugin maplibregl, but in file "**GeneratedPluginRegistrant.java"** everything imports to file errors. This image errors below:
![image](https://github.com/user-attachments/assets/dd82ec88-2ca3-4a05-aca4-5d9082f04fb8)

2. If I removed the plugin in file "**GeneratedPluginRegistrant.java**," the project still built and ran tested, but the plugin added is not working. So this is an issue or I missed something.
Please review and check it. If you have any questions and need more information, please comment below.

3 . File pubspec.yaml 

```yaml
name: xxx
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  socket_io_client: ^2.0.3+1
  http: ^1.2.2
  get: ^4.6.6
  nb_utils: ^6.1.3
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.1
  flutter_inappwebview: ^6.0.0
  maplibre_gl_platform_interface: ^0.20.0
  maplibre_gl_web: ^0.20.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  awesome_dialog: ^3.2.1
  google_fonts: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  qr_code_scanner: ^1.0.1
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  maplibre_gl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/area/
  plugin:
    platforms:
      android:
        package: org.maplibre.maplibregl
        pluginClass: MapLibreMapsPlugin
      ios:
        pluginClass: MapLibreMapsPlugin
      web:
        default_package: maplibre_gl_web
platforms:
  android:
  ios:
  web:
```

### Actual results

```
Running Gradle task 'assembleDebug'...                          
\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:25: error: package org.maplibre.maplibregl does not exist
      flutterEngine.getPlugins().add(new org.maplibre.maplibregl.MapLibreMapsPlugin());
                                                                ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

### Logs

This Log errors : 

![image](https://github.com/user-attachments/assets/6ff42152-bab7-4e96-985e-2b26cae74daf)

```
--------------------
Running Gradle task 'assembleDebug'...                          
\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:25: error: package org.maplibre.maplibregl does not exist
      flutterEngine.getPlugins().add(new org.maplibre.maplibregl.MapLibreMapsPlugin());
                                                                ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

### Flutter Doctor output

![image](https://github.com/user-attachments/assets/f6ac2c5a-d5aa-4c8c-af83-acbf62a5c6ad)

**Comment by vishalrao8** [comment]
_You are not supposed to modify or delete generated code. It will have unexpected behaviour._

Either there's some configuration issue or the issue is false positive. Try `flutter clean`, `flutter pub get` and restart Android studio with invalidate cache and restart option.

**Comment by danagbemava-nc** [comment]
As noted above, you should not touch the generated files. 

Why do you have this in your pubspec.yaml along with the `maplibre_gl` libraries? 

```
 plugin:
    platforms:
      android:
        package: org.maplibre.maplibregl
        pluginClass: MapLibreMapsPlugin
      ios:
        pluginClass: MapLibreMapsPlugin
      web:
        default_package: maplibre_gl_web
platforms:
  android:
  ios:
  web:
```

**Comment by KingdomVietNam** [comment]
> As noted above, you should not touch the generated files.
> 
> Why do you have this in your pubspec.yaml along with the `maplibre_gl` libraries?
> 
> ```
>  plugin:
>     platforms:
>       android:
>         package: org.maplibre.maplibregl
>         pluginClass: MapLibreMapsPlugin
>       ios:
>         pluginClass: MapLibreMapsPlugin
>       web:
>         default_package: maplibre_gl_web
> platforms:
>   android:
>   ios:
>   web:
> ```

 I fixed the error with the file,thank
