### ISSUE TITLE
When one side of the image has more than 16384 pixels, the size obtained by the `instantiateImageCodec` function is incorrect

### ISSUE THREAD

**Issue by KunMengcode** [flutter/flutter#152309]
### Steps to reproduce

Using code examples, try selecting an image with a size of 16384 ± 1，The output size of the image with a size of 16385 is 16384

### Expected results

I think this may be related to webp, as the two numbers are almost identical.
WebP is bitstream-compatible with VP8 and uses 14 bits for width and height. The maximum pixel dimensions of a WebP image is 16383 x 16383.

### Actual results

When I choose an image with dimensions<=16384x16384, it is the correct image.bidth and image.Height.
Once one side is greater than 16384, it will output unreasonable results.

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Image Resolution Example'),
        ),
        body: Center(
          child: ImageResolutionWidget(),
        ),
      ),
    );
  }
}

class ImageResolutionWidget extends StatefulWidget {
  @override
  _ImageResolutionWidgetState createState() => _ImageResolutionWidgetState();
}

class _ImageResolutionWidgetState extends State<ImageResolutionWidget> {
  Future<ui.Image>? _imageFuture;

  void _pickImage() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.image,
    );

    if (result != null) {
      File file = File(result.files.single.path!);
      Uint8List bytes = await file.readAsBytes();
      setState(() {
        _imageFuture = _getImageResolution(bytes);
      });
    }
  }

  Future<ui.Image> _getImageResolution(Uint8List bytes) async {
    ui.Codec codec = await ui.instantiateImageCodec(bytes);
    ui.FrameInfo frameInfo = await codec.getNextFrame();
    return frameInfo.image;
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        ElevatedButton(
          onPressed: _pickImage,
          child: Text('Pick Image'),
        ),
        SizedBox(height: 20),
        FutureBuilder<ui.Image>(
          future: _imageFuture,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              if (snapshot.hasError) {
                return Text('Error: ${snapshot.error}');
              }
              if (snapshot.hasData) {
                ui.Image image = snapshot.data!;
                return Text('Image resolution: ${image.width} x ${image.height}');
              }
            }
            return CircularProgressIndicator();
          },
        ),
      ],
    );
  }
}
```
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  opencv_dart: ^1.1.0+1
  photo_view: ^0.15.0
  file_picker: ^8.0.6
  image: ^4.2.0
  http: ^1.2.2
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @KunMengcode 
Can you provide `flutter doctor -v`. What platform are you seeing this behavior on ?
When you say the size is incorrect, do you have any logs or actual results to show it ?
Also, do you have the test image that we can use ?

**Comment by KunMengcode** [comment]
run `flutter doctor -v`
[✓] Flutter (Channel stable, 3.22.3, on Microsoft Windows [版本 10.0.19045.4651], locale zh-CN)
    • Flutter version 3.22.3 on channel stable at D:\SDK\flutter_windows_3.22.3-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (9 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • Pub download mirror https://pub-web.flutter-io.cn/
    • Flutter download mirror https://storage.flutter-io.cn/

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Android\SDK
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.3)
    • Android Studio at C:\Users\fanqi\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.4651]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.113

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

I am using Windows
![16384^2](https://github.com/user-attachments/assets/02a081ba-6554-4afe-a37f-a2f2acde7476)
![16385^2](https://github.com/user-attachments/assets/1ddeecd5-a07c-4249-868d-5dcf1f1f1e1a)
![16383^2](https://github.com/user-attachments/assets/79ab5c89-73ff-4ff8-b68d-dbd8794394fd)
![20240726145542387](https://github.com/user-attachments/assets/34723e2b-e4be-4ff8-8d1a-625e55101683)

**Comment by darshankawar** [comment]
Thanks for the update. I see that you are using third party package implementations in your code. Is the behavior replicable still without any of that code ? If so, try to provide us updated code sample.

**Comment by KunMengcode** [comment]
Even without third-party code, it can still be reproduced, the key is that 
```dart
ui.Codec codec = await ui.instantiateImageCodec(bytes);
ui.FrameInfo frameInfo = await codec.getNextFrame();
```

**Comment by KunMengcode** [comment]
This is a minimal example, and the result is output on the console
```dart
import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'dart:io';

void main() {
  _loadImage();

  runApp(MaterialApp());
}

void _loadImage() async {
  File file = File('E:/untitled/lib/20240726145542387.png');
  var bytes = await file.readAsBytes();
  ui.Codec codec = await ui.instantiateImageCodec(bytes);
  ui.FrameInfo frameInfo = await codec.getNextFrame();
  int imageW = frameInfo.image.width;
  int imageH = frameInfo.image.height;
  print('Image resolution: $imageW x $imageH');
  return ;
}
```

**Comment by darshankawar** [comment]
Thanks for the update. Keeping the issue open and labeling for team's tracking.

**Comment by jonahwilliams** [comment]
This is working as expected. If the image size exceeds the maximum size for your particular device, it will be scaled down to fit.
