### ISSUE TITLE
Can we add a Flutter module to an existing Android Studio project?

### ISSUE THREAD

**Issue by vinhha96** [flutter/flutter#15234]
I have been reading about Flutter for a while now, and I want to convert parts of my app to learn more. I have an existing Android project written in Java/Kotlin. Is it possible to add a new Flutter module to the existing app?

**Comment by eseidelGoogle** [comment]
Yes.  It's possible today, but it's just not yet well supported/documented.
https://github.com/flutter/flutter/issues/14821 is a bug tracking making this easier.
