### ISSUE TITLE
A way to run fake Flutter other than `flutter test` 

### ISSUE THREAD

**Issue by normidar** [flutter/flutter#152350]
### Use case

generate widget image on command line.

### Proposal

Like:

```
flutter fake run image_generator.dart
```

**Comment by danagbemava-nc** [comment]
Hi @normidar, please provide a detailed proposal for your use case and how it can be solved so that this can be properly addressed. 

Thank you

**Comment by normidar** [comment]
@danagbemava-nc 
Thanks for your comment.

I'm creating a tool to generate picture of widgets on command line, now I am using flutter test + screenshot plugin to simulate the environment of flutter, and take pictures on the simulated environment, in this case I used flutter test command, but I am not testing anything.

**Comment by danagbemava-nc** [comment]
Hi @normidar, I'm still not clear on what you would like the flutter tool to do here. Can you explain a bit more? Is this similar to https://github.com/flutter/flutter/issues/32164?

**Comment by normidar** [comment]
@danagbemava-nc
Thank you for your comment.

My goal is to simulate Flutter on the command line without a UI. While I can use flutter_test, it's not specifically designed for this use case. I'm looking for a solution that better fits my needs of generating widget images programmatically without a graphical interface.

**Comment by darshankawar** [comment]
> 'm looking for a solution that better fits my needs of generating widget images programmatically without a graphical interface.

Have you looked at pub.dev to check if any community package already offers this feature ? The proposal sounds infeasible for sdk to provide. You may also ask the same on support channels like stackoverflow or Flutter's reddit help page.
