### ISSUE TITLE
Proposal: revert `DropdownMenu` default search prioritising current selection 

### ISSUE THREAD

**Issue by PurplePolyhedron** [flutter/flutter#152380]
### Use case

In (https://github.com/flutter/flutter/pull/147294) I added logic in the default search function in `DropdownMenu` that skips the search if the current selection is a match. It was a side effect of fixing keyboard navigation issue (https://github.com/flutter/flutter/issues/147253).

However this approach doesn't fix the keyboard navigation issue with custom `searchCallback`(see https://github.com/flutter/flutter/issues/152375), and "prioritising current selection" is ambiguous with a  custom `searchCallback`, so it would be tricky to make `searchCallback` have the same behaviour with the default search.

### Proposal

I found another approach that temporarily disable search during keyboard navigation(https://github.com/flutter/flutter/pull/152378), I think it would be a good idea to revert the search function behaviour back to before where it is agnostic about the current selection.

The change hasn't made into stable yet, and I think the reverting the search function behaviour would not be noticable in most cases.

**Comment by nate-thegrate** [comment]
Sounds good!

Since we can discuss the problem in #152375 and talk about the solution in #152378, I'll go ahead and close this issue if that's cool with you.
