### ISSUE TITLE
The Chinese input method on the Web platform cannot follow the cursor。

### ISSUE THREAD

**Issue by maoyuliuxin** [flutter/flutter#152362]
### Steps to reproduce

The Chinese input method on the Web platform cannot follow the cursor。
widget is TextFormField。

### Expected results

The Chinese input method appears under the cursor

### Actual results

The location of Chinese input method can not be predicted
![image](https://github.com/user-attachments/assets/baa6a6eb-6179-4e0e-b147-f92418631b36)

### Code sample

```
import 'package:flutter/material.dart';
import 'package:kflutter_note/config/test/global_static.dart';
import 'package:kflutter_note/config/test/test_static_variable.dart';

class pageA extends StatefulWidget{
  pageAState createState() => new pageAState();
}


class pageAState extends State<pageA> {
  var controller =  TextEditingController();
  var founce = FocusNode();

  @override
  Widget build(BuildContext context) {
    print("testFlag @ pageA: ${founce.parent}" );
    return Center(
      child: Container(
        height: 500,
        width: 500,
        decoration: BoxDecoration(color: Colors.blueGrey),
        child: TextFormField(

          showCursor: true,
          cursorRadius: Radius.circular(15),
          cursorHeight: 30,
          focusNode: founce,
          maxLines: 20,
          decoration: const InputDecoration(
            border: UnderlineInputBorder(),
            labelText: 'Enter your username',
          ),
        ),

        // child: EditableText(
        //   minLines: 1,
        //   maxLines: 50,
        //
        //   style: TextStyle(fontSize: 16.0, color: Colors.black),
        //   backgroundCursorColor: Colors.blue,
        //   cursorColor: Colors.red,
        //   cursorWidth: 2.0,
        //   cursorRadius: Radius.circular(2.0),
        //
        //   onSelectionChanged: (selection, cause) {
        //     // Handle selection changed
        //   },
        //   cursorOpacityAnimates: true,
        //   onChanged: (text) {
        //     print('Text changed to: $text  ${controller.selection}');
        //   }, controller: controller, focusNode: FocusNode(),
        // )
      ),
    );
  }
}
```

### Screenshots or Video

![image](https://github.com/user-attachments/assets/3e915e95-ed27-458f-bcc8-5e27d3a2a01b)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [版本 10.0.22631.3880], locale zh-CN)
    • Flutter version 3.19.5 on channel stable at D:\Android\Flutter\sdk\v3195\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 months ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
```

**Comment by darshankawar** [comment]
@maoyuliuxin 
I am unable to replicate the behavior you are seeing. Can you upgrade to latest stable, re-run your scenario to check if it still persists or not ?
If yes, provide complete but minimal reproducible code sample, steps to take to properly replicate that shows the reported behavior.

**Comment by maoyuliuxin** [comment]
Here's my code。Need to use Chinese input method, my input method is Sogou

`import 'package:flutter/material.dart';


void main() {
  // create();
  // BoxEntity(0, "1111");
  runApp(const MyApp());
}

// late var db = MyDatabase();
// void test()async{
//
//   // var todo =await  db.addTodo(const TodosCompanion( title: Value("ssss"), content: Value("eeee")));
//   // print("shen : todo = ${todo}");
//   // for (int i = 0; i < 1000; i++) {
//   //   await db.addT(CategoriesCompanion( description: Value("111$i"), owner: Value(todo)));
//   //   await db.addT(CategoriesCompanion( description:Value("111$i"), owner: Value(todo)));
//   //   await db.addT(CategoriesCompanion(description: Value("111$i"), owner: Value(todo)));
//   // }
//
//
//   print("shen : todo = finish");
//  await db.limitTodos("ssss");
// }

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  var key = GlobalKey();

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  const Text(
                    'You have pushed the button this many times:',
                  ),
                  Text(
                    '$_counter',
                  ),
                ],
              ),
              TextField(
                key: key,
                enabled: true,
                // expands: true,
                // textAlign: TextAlign.justify,
                // textAlignVertical:TextAlignVertical.bottom,
                cursorOpacityAnimates: true,
                maxLines: 20,
                // maxLines: null,
                keyboardType: TextInputType.multiline,

                // decoration: const InputDecoration(
                //   border: UnderlineInputBorder(),
                //   labelText: 'Enter your username',
                // ),
              )
            ]
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by maoyuliuxin** [comment]
Here's my code。Need to use Chinese input method, my input method is Sogou

`class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  var key = GlobalKey();

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  const Text(
                    'You have pushed the button this many times:',
                  ),
                  Text(
                    '$_counter',
                  ),
                ],
              ),
              TextField(
                key: key,
                enabled: true,
                // expands: true,
                // textAlign: TextAlign.justify,
                // textAlignVertical:TextAlignVertical.bottom,
                cursorOpacityAnimates: true,
                maxLines: 20,
                // maxLines: null,
                keyboardType: TextInputType.multiline,

                // decoration: const InputDecoration(
                //   border: UnderlineInputBorder(),
                //   labelText: 'Enter your username',
                // ),
              )
            ]
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by maoyuliuxin** [comment]
The project flutter version is 3.22.3
![image](https://github.com/user-attachments/assets/57508d14-f336-4f99-abfc-ce7ea548a2ab)

**Comment by darshankawar** [comment]
Please check if below issues resemble your case or not:

https://github.com/flutter/flutter/issues/126329
https://github.com/flutter/flutter/issues/79933

**Comment by maoyuliuxin** [comment]
My situation is similar to #79933, but my scenario is multi-line input and the platform is web。
--web-renderer html

**Comment by maoyuliuxin** [comment]
I found that my problem was consistent with #133900, but I didn't find out how to solve it. Try typing a few more lines and then go back to the beginning

**Comment by darshankawar** [comment]
Mostly it is similar to https://github.com/flutter/flutter/issues/128323, although it is reported for windows, but affects web too. Can you try your scenario on windows and check if you still get same behavior ? If so, then we can follow-up in linked issues.

**Comment by maoyuliuxin** [comment]
I tried using setComposingRect for TextInputConnection, but I found that this approach did not work on the Web。
Can you provide a method to control the location of the ime input method selection bar on the web？
Thank

**Comment by darshankawar** [comment]
Check below links to see if they help in your case or not:

https://github.com/flutter/flutter/issues/149979
https://github.com/flutter/flutter/issues/140728
https://github.com/flutter/flutter/issues/140728#issuecomment-1887652724

**Comment by maoyuliuxin** [comment]
You can close this issue, I went to the segmentation by TextInputConnection setEditableSizeAndTransform forced edit box. I have to say that writing the Web with Flutter is a terrible experience, and dart2js is terrible for complex scenes。

**Comment by darshankawar** [comment]
> I have to say that writing the Web with Flutter is a terrible experience, and dart2js is terrible for complex scenes。

If you have a proposal to make this feature more developer friendly, feel free to file a proposal that we can address separately.
Closing based on above comment.
