### ISSUE TITLE
[tool_crash] _TypeError: (#0      BuildIOSArchiveCommand._parseImageAssetContentsJson (package:flutter_tools/src/commands/build_ios.dart:188:26))

### ISSUE THREAD

**Issue by WaleedAlrashed** [flutter/flutter#152363]
## Context:
Building a signed ios release from Codemagic CI/CD

Flutter version: 3.22.3

## Command
```
flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
```

## Steps to Reproduce
1. ... Start an ipa build on codemagic

## Logs
_TypeError: (#0      BuildIOSArchiveCommand._parseImageAssetContentsJson (package:flutter_tools/src/commands/build_ios.dart:188:26))
```
#0      BuildIOSArchiveCommand._parseImageAssetContentsJson (package:flutter_tools/src/commands/build_ios.dart:188:26)
#1      BuildIOSArchiveCommand._validateIconAssetsAfterArchive (package:flutter_tools/src/commands/build_ios.dart:315:60)
<asynchronous suspension>
#2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:435:7)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Flutter version 3.22.3 on channel stable at /Users/builder/programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (9 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode-15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 124.0.6367.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 7.7.7+7031
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
app_tracking_transparency-2.0.5
audio_session-0.1.19
awesome_notifications-0.9.3+1
device_info_plus-10.1.0
firebase_analytics-11.2.0
firebase_analytics_web-0.5.9
firebase_auth-5.1.2
firebase_auth_web-5.12.4
firebase_core-3.2.0
firebase_core_web-2.17.3
firebase_dynamic_links-6.0.3
firebase_messaging-15.0.3
firebase_messaging_web-3.8.11
flutter_checkout_payment-9f4842d63d853cae1f038d204ff3e52d247d8e0b
flutter_credit_card-4.0.1
flutter_inappwebview-5.8.0
flutter_local_notifications-17.2.1+1
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
google_sign_in-6.2.1
google_sign_in_android-6.1.23
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4
in_app_review-2.0.9
just_audio-0.9.38
just_audio_web-0.4.11
package_info_plus-4.2.0
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
pay-2.0.0
pay_android-2.0.0
pay_ios-1.0.11
permission_handler-11.3.1
permission_handler_android-12.0.6
permission_handler_apple-9.4.4
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
sentry_flutter-8.5.0
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sign_in_with_apple-6.1.1
sign_in_with_apple_web-2.1.0
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.2
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1
video_player-2.8.6
video_player_android-2.4.14
video_player_avfoundation-2.6.1
video_player_web-2.3.0
wakelock_plus-1.2.1
webview_flutter-4.8.0
webview_flutter_android-3.16.2
webview_flutter_wkwebview-3.13.1

**Comment by darshankawar** [comment]
@WaleedAlrashed 
Does the directory get generated at `build/ios/ipa/ ` path ?
If you run the said command locally, do you still get same exception ?
