### ISSUE TITLE
Text has no automatic change

### ISSUE THREAD

**Issue by zhangruiyu** [flutter/flutter#15238]
![image](https://user-images.githubusercontent.com/10591822/37086739-437a0f8a-2233-11e8-8ab7-b537a5f9f12c.png)
![image](https://user-images.githubusercontent.com/10591822/37086773-57aead12-2233-11e8-9e06-86494a9ada22.png)
![image](https://user-images.githubusercontent.com/10591822/37086782-5ec52f22-2233-11e8-8638-0612cb9e80d0.png)

**Comment by Hixie** [comment]
Is the problem that we are not automatically wrapping on commas?
