### ISSUE TITLE
I can't run Flutter project that I create on my machine

### ISSUE THREAD

**Issue by anirugu** [flutter/flutter#15235]
I started with fresh android studio installation which I grab from android's official site. Installed the sdk which android studio does itself.

now when I run the project it's giving.

* Error running Gradle:
Unable to download needed Android SDK components, as the following licenses have not been accepted:
Android SDK Build-Tools 26.0.2

To resolve this, please run the following command in a Terminal:
flutter doctor --android-licenses

when I run flutter doctor --android-licenses in same directory where my app is, I get this error.

sdkmanager --version failed: 1

Please tell me what is wrong here. how I can accept license if this doesn't work through this command.

**Comment by zoechi** [comment]
might be a dup of #14942

**Comment by MohamedAbdelrahim** [comment]
> I started with fresh android studio installation which I grab from android's official site. Installed the sdk which android studio does itself.
> 
> now when I run the project it's giving.
> 
> * Error running Gradle:
>   Unable to download needed Android SDK components, as the following licenses have not been accepted:
>   Android SDK Build-Tools 26.0.2
> 
> To resolve this, please run the following command in a Terminal:
> flutter doctor --android-licenses
> 
> when I run flutter doctor --android-licenses in same directory where my app is, I get this error.
> 
> sdkmanager --version failed: 1
> 
> Please tell me what is wrong here. how I can accept license if this doesn't work through this command.

Thx it really run
