### ISSUE TITLE
Ability to configure WiFi setting and connect and disconnect from WiFi

### ISSUE THREAD

**Issue by yhua537** [flutter/flutter#15231]
This is a new feature request related to connectivity plugin.  

Currently, flutter don't have ability to change WiFi configuration and inability to control device to disconnect from current WiFi and connect to WiFi that user selected/configure in the application. This is useful in applications require reliable initial setup for device like google chromecast/home and other embedded device. Smart config is one of the option but it is currently not very reliable and heavily impact by the environment even in native android/ios. 

I am considering migrate my current application to flutter but this is main feature currently blocking me. Thanks in advance.

**Comment by tristan2468** [comment]
I would like this feature too, for an IoT product that I am working on.

**Comment by nk36** [comment]
I think every person who want to do an IoT product need that.. 
We need that for our project.. but for now, we starting with Bluetooth :/

**Comment by zoechi** [comment]
You can make native platform features available to Dart yourself by building a plugin https://flutter.io/platform-channels/

**Comment by yhua537** [comment]
Hi @zoechi, yes, I am aware that option but I am not an ios developer and don't have the environment to test with. While it is not essential for many web based application development, it is important feature for IoT product as @tristan2468 and @nk36 pointed out, It is also useful for company to provide inhouse free WiFi for their visitor with registered accounts. It will be nice if it is supported by official plugins. 

Maybe I will give a go & see if I can contribute later.

**Comment by nk36** [comment]
Hi,

For information, I was thinking to create a plugin and I am on the edge to have something working!
Like @yhua537, I am not an iOS developer and do not have the environment to test with (android user)!
So, I am going to buy an iPhone in order to test my plugin which is working for Android only right now :)

Stay tuned!

**Comment by alternadom** [comment]
I don't know much about licences.. why can't you use this ?
I will work on that subject and stay open for changing the licence!

**Comment by tristan2468** [comment]
GPL requires the application linking to it to be GPL also.
For my use (proprietary app) this is not possible, so BSD, MIT or Apache licenses are preferred.
Of course, it is entirely up to you which licence you wish to use.

**Comment by alternadom** [comment]
Ok, thanks for your advice! I hope you will contribute to the project @tristan2468 :)
I change to MIT licence so..

**Comment by yhua537** [comment]
Thanks @alternadom , that save me time from creating my own plugin, I will test and contribute to yours instead.

**Comment by fukemy** [comment]
100000+ like and heart to you @alternadom. Love u so much, but im not gay

**Comment by THEJDEEP1** [comment]
Im trying to connect to wifi network which does not have password or any security. what params should I send in password field as I have send '' empty string but it does not connect. and no errors also. when I try to connect to a network which has security  is working fine.

**Comment by robauer** [comment]
string ssid = "someSSID";
string password = "";

This always works for me...

**Comment by csells** [comment]
@yhua537 does the https://github.com/alternadom/WiFiFlutter project solve this problem for you?
