### ISSUE TITLE
The size of the emoji in the input box is inconsistent with the size after sending. The emoji in the input box is too small

### ISSUE THREAD

**Issue by yixiu1043** [flutter/flutter#152360]
### Use case

The size of the emoji entered in the input box is inconsistent with the size after sending. 
The emoji in the input box is too small.

see screenshot below：

![IMG_0289](https://github.com/user-attachments/assets/e4608df2-f77a-4647-bd06-4c3220096562)

### Proposal

The size of the emoji entered in the input box should be the same as the size after sending.

**Comment by darshankawar** [comment]
@yixiu1043 
Most likely you are hitting https://github.com/flutter/flutter/issues/28894, so please follow-up in it for further updates.
Closing as duplicate.
