### ISSUE TITLE
Add soft keyboard listener

### ISSUE THREAD

**Issue by thewh1teagle** [flutter/flutter#152334]
### Use case

I would like to get soft keyboard events. just like rawKeyboardListener but for soft on screen keyborards.

### Proposal

Related: https://github.com/flutter/flutter/issues/86560 https://github.com/flutter/flutter/issues/84925#issuecomment-865107014

The threads are locked, but it's incorrect that it's impossible. it's actually possible.

```dart
// Open the keyboard from anywhere by using SystemChannels.textInput.invokeMethod("TextInput.show");

class SoftKeyboardListener extends StatefulWidget {
  const SoftKeyboardListener({super.key});

  @override
  State<SoftKeyboardListener> createState() => _SoftKeyboardListenerState();
}

class _SoftKeyboardListenerState extends State<SoftKeyboardListener> {
  final FocusNode _focusNode = FocusNode();

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  KeyEventResult _handleKeyEvent(FocusNode node, KeyEvent event) {
    var label = event.logicalKey.keyLabel;
    print("key press ${label}");
    return KeyEventResult.ignored;
  }

  @override
  Widget build(BuildContext context) {
    FocusScope.of(context).requestFocus(_focusNode);
    return Focus(
      focusNode: _focusNode,
      onKeyEvent: _handleKeyEvent,
      child: Container(),
    );
  }
}
```

**Comment by LongCatIsLooong** [comment]
On screen keyboards generally do not produce key events like hardware keyboards (with a few exceptions like the Android `InputConnection.sendKeyEvent` API), the text usually come in a different form.

See: https://developer.android.com/reference/android/view/inputmethod/InputConnection#commitText(java.lang.CharSequence,%20int,%20android.view.inputmethod.TextAttribute).

You could use the [TextInput](https://main-api.flutter.dev/flutter/services/TextInput-class.html) class to interact with the system text input service.
