### ISSUE TITLE
Crashes when deployed on webserver

### ISSUE THREAD

**Issue by BakeerAHere** [flutter/flutter#152439]
### Steps to reproduce

I am having the below invoice viewer widget. it accepts any pdf document in bytes. when I run this code on my development PC it is working fine on chrome. but when I upload it to my webserver it crashes

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:printing/printing.dart';
import 'package:pdf/widgets.dart' as pw;

class InvoiceViewer extends StatelessWidget {
  InvoiceViewer(
      {super.key, required this.pdfDocument, required this.invoiceId});

  final pw.Document pdfDocument;
  final String invoiceId;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Invoice Preview'),
      ),
      body: PdfPreview(
        canChangePageFormat: false, // Disable format change
        canChangeOrientation: false, // Disable orientation change
        allowSharing: true,
        canDebug: false, // Disable debug mode
        onError: (context, error) {
          return Center(child: Text(error.toString()));
        },
        //canChangeZoom: true, // Enable zoom functionality
        onPrinted: Navigator.of(context).pop,
        onShared: Navigator.of(context).pop,
        pdfFileName: invoiceId,
        build: (format) => pdfDocument.save(),
        // actions: [
        //   IconButton(
        //     icon: Icon(Icons.download),
        //     onPressed: () async {
        //       // Trigger the PDF download
        //       await Printing.layoutPdf(
        //         onLayout: (PdfPageFormat format) async => pdfDocument.save(),
        //       );
        //     },
        //   )
        // ],
      ),
    );
  }
}
```
</details>

### Expected results

Render pdf review and show the pdf.

### Actual results

Widget just show loading and I am getting the below error from browser console

```
Uncaught TypeError: Cannot read properties of undefined (reading 'amd')
    at main.dart.js:112746:5
    at aGb.a (main.dart.js:6656:63)
    at aGb.$2 (main.dart.js:48672:14)
    at aFn.$1 (main.dart.js:48666:21)
    at aCY.aAH (main.dart.js:49589:34)
    at aCY.yR (main.dart.js:49592:13)
    at azc.$0 (main.dart.js:49099:11)
    at Object.zY (main.dart.js:6786:40)
    at ap.pD (main.dart.js:49034:3)
    at az5.$0 (main.dart.js:49070:13)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3672], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @BakeerAHere, we will need a complete minimal reproducible code sample to properly address this. You might also want to run your app in `profile` mode so that you can get a non-minified error message.
