### ISSUE TITLE
Tutorial how to test with firebase

### ISSUE THREAD

**Issue by Panthro** [flutter/flutter#15245]
Hi this is a feature request not an issue.

Right now the Widget test secion of https://flutter.io/testing/ is kinda poor and does not give developers better examples of how to "mock" integration services.

Being firebase one of the most used altogether with flutter it would be nice to have a Firebase testing related tutorial/sample.

I know this is kind of testing101 with dart, but must of us (this is my personal belief) are coming to flutter  without any dart knowledge.

A clear example of this (and what I'm currently battling) is how to test components that rely on `FirebaseAnimatedList`

(Sorry if the issue does not follow the guidelines, I looked for feature requests and couldnt find)

**Comment by escamoteur** [comment]
I completely agree.  I'm just faced with the challenge how to write a test for a package that uses FireStore. I have no idea how this could be done as it has to run on the device as far as I can imagine.

**Comment by zoechi** [comment]
I think #16186 would make that easier.

**Comment by escamoteur** [comment]
Main point is how you can test a service that needs your Apps fingerprint?

**Comment by zoechi** [comment]
Currently I think you need to intercept the PlatformChannel and respond to messages, which needs a lot of knowledge of the internal working of the Firebase plugins and is IMHO not viable especially for such complex plugins. With #16186 there could be mocking on a much higher level API.

**Comment by escamoteur** [comment]
Mocking for unit tests is one thing. But I also would like to be able to write a test that interacts with a real database

**Comment by Panthro** [comment]
What I'm doing in my tests is mocking the firebase interfaces, but it requires a lot of effort to generated the expected resources.

The mocks are here:
https://github.com/CrochetLand/app/blob/develop/test/mocks.dart

**Comment by zoechi** [comment]
@escamoteur 

> that interacts with a real database

for this you need to run the test on a device or emulator. (`flutter run` or `flutter drive`)

**Comment by Panthro** [comment]
What I have done in my project is to have 2 databases (int, prod), where all the tests and stuff I run against int and the application runs against the other.

 - **int** => I have scripts that changes the google json to the INT database and run the `flutter drive`
 - **prod** => is the default one, so basically any `flutter run|build` would use this one.

**Comment by Panthro** [comment]
@escamoteur nope, I have 2 databases in firebase, and I change my `json` file before build accordingly to which flavor I'm building.

**Comment by Panthro** [comment]
to clear up my setup:

- Unit Tests with `flutter test`: I used the mocks file mentioned above
- Integration tests with `flutter drive`: I have a script that changes the firebase json file before executing the tests
- Production: is the default one, that runs in my CI with the prod database json file.

**Comment by lukepighetti** [comment]
@Panthro are you switching between Firebase projects by swapping out `google-services.json` / `GoogleService-Info.plist` or do you just switch between databases on the project? I'm trying to figure out the best way to do test/production switching with Firebase

**Comment by Panthro** [comment]
@lukepighetti yeah, that's what I'm doing right now.

I have a script that switches the files before the build based on what type of build I'm doing.

**Comment by ozanturksever** [comment]
i exported [mock_cloud_firestore](https://pub.dartlang.org/packages/mock_cloud_firestore), from our private project. It is very alpha but i will be updating it to suit my needs.

**Comment by escamoteur** [comment]
@ozanturksever This is awesome, many thanks for sharing!!

**Comment by daviidmorales** [comment]
I would like to share you how I'm test my documentSnapshots and get a feedback about, because i dont know if it is a good way.

First I create a DocumentSnapshotMock with a constructor with the data that can chage and it overwrite the default values
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:mockito/mockito.dart';

class DocumentSnapshotMock extends Mock implements DocumentSnapshot {
  final String documentID;
  final Map<String, dynamic> data;

  DocumentSnapshotMock(this.documentID, this.data);
}
```
and I create a new `DocumentSnapshotMock()` with the data that i need
```dart
test('documentSnapshot', () {
      final data = {"email": "email"};
      //apply the DocumentSnapshotMock with my mock values
      final documentSnapshotMock = DocumentSnapshotMock("uid", data);

      expect(data['email'], documentSnapshotMock.data['email']);
      expect("uid", documentSnapshotMock.data['email']);
});
```

**Comment by mayurdhurpate** [comment]
I wanted to write some end to end tests for our Flutter app and faced a lot of difficulties is just getting past the Firebase Auth with Google Sign In. Couldn't understand how to mock the library modules and functions calling external services. Shared some details regarding my issue here: https://stackoverflow.com/questions/56054288/how-to-mock-bypass-external-dependencies-and-workflows-in-flutter-integration-te/58206901#58206901

**Comment by lukepighetti** [comment]
@mayurdhurpate I think you've just run into the cost/benefit curve on testing. Generally speaking I don't write e2e tests because there's a large portion of code that is already under test that is outside my project. In your example with `firebase_auth`, Firebase has test coverage for the backend, iOS and Android packages, as well as some on Flutter package. So for me, the better option is to feed your app an AuthService service that can be mocked. That way you aren't e2e through a codebase you don't have control over.

**Comment by lukepighetti** [comment]
This is how I usually do it.

```dart
import "package:firebase_auth/firebase_auth.dart";

/// The interface that any AuthService needs to implement
abstract class AuthService {
  Stream<User> get currentUser;
}

/// A production implementation of AuthService
class ProductionAuthService implements AuthService {
  FirebaseAuth get _auth => FirebaseAuth.instance;

  Stream<User> get currentUser =>
      _auth.onAuthStateChanged.map((u) => User.fromFirebaseUser(u));
}

/// A fake implementation of AuthServices
class FakeAuthService implements AuthService {
  Stream<User> get currentUser => Stream.fromIterable([User.fake()]);
}

/// A user model that can be fake or from a Firebase user
class User {
  User.fake()
      : name = "John Doe",
        avatar = "https://api.adorable.io/avatars/128/johndoe.png";

  User.fromFirebaseUser(FirebaseUser u)
      : name = u.displayName,
        avatar = u.photoUrl;

  final String name;
  final String avatar;
}

/// Services that can be easily switched between fake and production
class Services {
  Services.production() : auth = ProductionAuthService();
  Services.fake() : auth = FakeAuthService();

  final AuthService auth;
}
```

**Comment by escamoteur** [comment]
Still an easy way to write integration tests with Flutter test and Firebase would be nice.
I m not sure if you can initialize all Firebase libs from code without a google.json file. If that would be possible for all integration to be done tests would be easy.
The mocking is nice but to test performance, latencies etc you need access to the real backend

**Comment by lukepighetti** [comment]
Here's another example, this is kinda like how Uber RIBs work, but super dumbed down. Only posting this because I was just sitting here thinking about it. Not really too specific to this issue and I probably shouldn't even post it here............

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';

import 'package:flutter/widgets.dart';

/// Some random services as an example

class AuthService {
  Stream<bool> get isLoggedIn =>
      FirebaseAuth.instance.onAuthStateChanged.map((u) => u != null);
}

class PopularHashtagService {
  Stream<List<String>> get popular => FirebaseDatabase.instance
      .reference()
      .child("/hashtags")
      .onValue
      .map((v) => v.snapshot.value.keys);
}

class LikesService {
  Stream<int> likes(String id) => FirebaseDatabase.instance
      .reference()
      .child("/likes/$id")
      .onValue
      .map((v) => v.snapshot.value);
}

class Services implements LoginScreenServices {
  final auth = AuthService();
  final tags = PopularHashtagService();
  final likes = LikesService();
}

/*
 * Login Screen defines a small subsection of services
 */

abstract class LoginScreenServices {
  AuthService get auth;
  PopularHashtagService get tags;
}

/*
 * Which are easy to fake for a specific test
 */
class FakeLoginScreenServices
    implements LoginScreenServices, AuthService, PopularHashtagService {
  @override
  Stream<bool> get isLoggedIn => Stream.fromIterable([true]);

  @override
  Stream<List<String>> get popular => Stream.fromIterable([
        ["flutter", "dart", "foo", "bar"]
      ]);

  @override
  AuthService get auth => this;

  @override
  PopularHashtagService get tags => this;
}

/*
 * And login screen doesn't know the difference
 */
class LoginScreen extends StatelessWidget {
  LoginScreen(this.services);

  final LoginScreenServices services;

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<bool>(
      stream: services.auth.isLoggedIn,
      builder: (context, snap) {
        /// Loading
        if (snap.hasData == false)
          return Center(
            child: CircularProgressIndicator(),
          );

        /// Logged out
        if (snap.data == false)
          return Center(
            child: Text("You gotta login!"),
          );

        /// Logged in
        else
          return Column(
            children: <Widget>[
              Text("Welcome! Here are some popular tags."),
              StreamBuilder<List<String>>(
                stream: services.tags.popular,
                builder: (context, snap) {
                  /// Loading
                  if (snap.hasData == false) return Text("Loading tags...");

                  /// No tags
                  if (snap.data.isEmpty)
                    return Text("Nothing is popular right now!");

                  /// Got tags
                  else
                    return Row(
                      children: <Widget>[
                        ...snap.data.map((tag) => Text(tag)),
                      ],
                    );
                },
              )
            ],
          );
      },
    );
  }
}
```

**Comment by davidcv5** [comment]
@lukaspili thanks for your examples, they are indeed helpful. Have another question about **Updates**, how would you do a unit test for the following scenario.

Have a TODO App and want to change a Task status to done. So you basically would have a "todo_service", or "storage_service" with a simple method like this 


Future toggleTask(Task task) {
  var ref = _db.collection('tasks').document(task.id);
  ref.updateData({'done': !task.done};
}
At this point, the task is already updated, but without actually doing task.done = !task.done directly on the task, the update depends on Firestore. You could spin up the firestore-emulator I guess, but I wonder how would a real test for this look like?

**Comment by escamoteur** [comment]
I just opened this issue here. https://github.com/FirebaseExtended/flutterfire/issues/265 If this is possible integrationtests will be easy

**Comment by lukepighetti** [comment]
In that case I would argue that the code is clear enough that you don’t need test coverage for the actual database update. What you’d benefit from is test coverage of your Flutter UI/app itself. Mock those methods and fire up a segment of your app and start driving it with the test framework.

I have done e2e as you allude to by having a scratch firebase project and having tests that fire off the writes and then methods to read the results. But it can get super flakey

**Comment by kroikie** [comment]
@Panthro

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/896. Any further collaboration will be done there.
