### ISSUE TITLE
Parallel builds using RBE are buggy.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#152458]
When building multiple engine variants in different terminal tabs, or via GNU parallel, starting the second build cancels the first due to a reclient error.

```
reclient[d852f840-2d1a-4bd5-906e-453d4f63040a]: LocalErrorResultStatus: context canceled
```

**Comment by chinmaygarde** [comment]
The error in the first ongoing build seems to happen if the second build is faster to finish. Perhaps the RBE proxy is being torn down and it is some sort of global?

**Comment by jonahwilliams** [comment]
From discussion in triage, this can't be supported with reclient /RBE in the near future.
