### ISSUE TITLE
Add opportunity to change CupertinoTextField suffix alignment

### ISSUE THREAD

**Issue by ziqq** [flutter/flutter#152482]
### Use case

```dart
CupertinoTextField(
  readOnly: true,
  padding: EdgeInsets.symmetric(
    horizontal: 16,
    vertical: 16 / 2,
  ),
  minLines: 1,
  maxLines: 50,
  placeholder: 'Placeholder',
  suffix: Padding(
    padding: EdgeInsets.only(right: 16),
    child: DecoratedBox(
      decoration: BoxDecoration(
        color: CupertinoDynamicColor.resolve(
          CupertinoColors.systemBlue,
          context,
        ),
        borderRadius: const BorderRadius.all(Radius.circular(30)),
      ),
      child: Padding(
        padding: EdgeInsets.symmetric(
          horizontal: 16 / 2,
          vertical: 10 / 2,
        ),
        child: Text(
          'NEW',
          style: Theme.of(context).textTheme.labelSmall?.copyWith(
            color: CupertinoColors.white,
            fontWeight: FontWeight.w600,
            fontSize: 12,
            height: 1,
          ),
        ),
      ),
    ),
  ),
)
```

<img width="364" alt="image" src="https://github.com/user-attachments/assets/6cb3ecc3-9f15-4058-86e5-2a982e577cd5">

### Proposal

Change align suffix on top.

Add one property to 

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/b67e27fb-dbc1-40fd-9c4a-b80bf20c3f43">

**Comment by justinmc** [comment]
I tried to come up with a workaround but maybe it's not possible... This doesn't quite work:

```dart
            CupertinoTextField(
              suffix: Expanded(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: <Widget>[
                    Container(
                      width: 12.0,
                      height: 12.0,
                      color: Colors.red,
                    ),
                  ],
                ),
              ),
            ),
```

I agree that it should be possible to align this, but I'm not sure what the best way is to do that.

**Comment by ziqq** [comment]
Hello @justinmc, It's not right way. Need add suffixAlignment property to change align of suffix.

**Comment by justinmc** [comment]
Does this problem also exist for TextFIeld?

**Comment by ziqq** [comment]
> Does this problem also exist for TextFIeld?

Hello @justinmc, I haven't checked this point, the current issue with only CupertinoTextField.

**Comment by justinmc** [comment]
Would you mind checking if you have a chance? Though I guess your PR can merge on its own without TextField support even if it is necessary in TextField.
