### ISSUE TITLE
[tool][web] Consider setting `COEP` header to `credentialless`

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#152411]
While running `flutter drive` tests during the migration of the Google Maps Flutter web plugin, we encountered that certain requests from the Maps JS SDK are [blocked with the following error](https://github.com/flutter/packages/pull/7077#issuecomment-2252676213):

```
Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep - StaticMapService.GetMapImage:1
```

When reading some more about the error, one of the recommendations is to use `COEP: credentialless` instead of `require-corp`:

* https://developer.chrome.com/blog/coep-credentialless-origin-trial#credentialless_to_the_rescue

Currently Flutter is doing `require-corp`. Should we switch the tooling to the new value?

**Comment by johnpryan** [comment]
https://github.com/flutter/flutter/pull/152413 is working for me

**Comment by ditman** [comment]
The change has landed, closing!
