### ISSUE TITLE
[iOS]How to solve the problem:System gesture gate timed out. 

### ISSUE THREAD

**Issue by cc673459362** [flutter/flutter#152462]
### Steps to reproduce

1. a scrollview with scrollbar.
2. show the vertical scrollbar at the right edge of the iphone.
3. <img width="723" alt="image" src="https://github.com/user-attachments/assets/536546a5-8a4b-41bb-a593-1e21ffaa5aa3">
longpress the scrollbar to drag it.

### Expected results

When I set the duration in 100ms, it's ok in iphone6s with iOS 15. However, it will trigger :
<0x107b0e0e0> Gesture: System gesture gate timed out.
<0x107b0ff00> Touch: System gesture gate timed out.
in iphone13pm with iOS 17.
And I have to longpress more than 1s before I can drag the scrollbar.

### Actual results

<0x107b0e0e0> Gesture: System gesture gate timed out.
<0x107b0ff00> Touch: System gesture gate timed out.
in iphone13pm with iOS 17.
And I have to longpress more than 1s before I can drag the scrollbar.

### Code sample

<details open><summary>Code sample</summary>

```dart
@override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Scrollbar(
          thumbVisibility: true,
          trackVisibility: true,
          thickness:20,
          child: ListView.builder(
            itemCount: 100,
            itemBuilder: (context, index) {
              return ListTile(
                title: Text('Item $index'),
              );
            },
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
<0x103914090> Touch: System gesture gate timed out.
<0x103913060> Gesture: System gesture gate timed out.
flutter: _ThumbPressGestureRecognizer!! duration:0:00:00.100000 kind:PointerDeviceKind.touch
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@cc673459362 
What version of Flutter are you on ? Are you using Impeller ? If so, if you disable it and re-run your scenario, does it still occur ?
See https://github.com/flutter/flutter/issues/124056 for reference.
