### ISSUE TITLE
getter headline5 issue

### ISSUE THREAD

**Issue by alpha9779** [flutter/flutter#152450]
actually i'm using serverpod and flutter . But when i tries to run it shows me the error like this
" Error: The getter 'headline5' isn't defined for the class 'TextTheme'.'TextTheme' is from 'package:flutter/src/material/text_theme.dart'"
in serverpod there is no error. And

 flutter doctor output is like this
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3958], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2023.1)
[√] Android Studio (version 2024.1)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources
• No issues found!

Help me to resolve this!!

**Comment by iapicca** [comment]
`headline5` is deprecated, use `headline` instead
https://github.com/flutter/flutter/commit/79a43be22abeed2e184beb5009bd506bd47fb436#diff-3fc83a1fd3402b44f7cf1fb24fb544bdb5ba923f0db4547f2561263a2c8873b7

**Comment by alpha9779** [comment]
Thank you mate . It helped me!!

**Comment by danagbemava-nc** [comment]
Closing this as solved based on https://github.com/flutter/flutter/issues/152450#issuecomment-2254595344
