### ISSUE TITLE
Web App stuck on Splash on FB messenger's web view

### ISSUE THREAD

**Issue by naveensinghk** [flutter/flutter#152419]
I've deployed a Beta App developed using Flutter Web. The app uses GoRouter for Navigation, Native splash etc. Working fine when accessed via Chrome etc. When the link is shared via fb messenger (mobile) (fb webview), it seems to be stuck on Splash Screen forever and only works when the link is opened via Chrome or other browser using the options menu.

I understand fb messenger adds a "/fbclid=..." to the link when the user clicks on it, not sure how, but GoRouter seems to manage it well, at least on desktop / mobile browser.

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
✓ Flutter (Channel stable, 3.22.3, on Ubuntu 22.04.3 LTS 5.15.0-102-lowlatency, locale en_NZ.UTF-8)
✓ Chrome - develop for the web
✓ Linux toolchain - develop for Linux desktop
✓ Android Studio (version 2021.3)
✓ VS Code (version 1.84.2)
✓ Connected device (2 available)
✓ Network resources
I've also removed the splash using FlutterNativeSplash remove;

before the router widget and after:

WidgetsFlutterBinding.ensureInitialized

**Comment by darshankawar** [comment]
@naveensinghk 
Please provide us a minimal but runnable reproducible code sample that will show the reported behavior.
