### ISSUE TITLE
Replace some phones attached to mac hosts with mokey's

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#152406]
The hosts below currently have non-mokey devices attached. They should be replaced with mokey devices. 

flutter-devicelab-mac-13 - Pixel 7 Pro - staging
flutter-devicelab-mac-17 - Moto G4 - try
flutter-devicelab-mac-19 - Pixel 7 Pro - try
flutter-devicelab-mac-33 - Moto G4 - staging
flutter-devicelab-mac-34 - Moto G4 - staging
flutter-devicelab-mac-37 - Moto G4 - staging

**Comment by zanderso** [comment]
Part of https://github.com/flutter/flutter/issues/148085

**Comment by kentnguyen99** [comment]
Hi Zach,
Swapping out existing phone with new Mokey phones are done. However; All Bots are in "Quarantined" state on monitoring website.  Are these phones compatible with Mac mini?
<img width="1070" alt="Screenshot 2024-07-26 at 4 47 28 PM" src="https://github.com/user-attachments/assets/bb694418-a455-4217-bb72-10d68380a812">

**Comment by zanderso** [comment]
Are there any dialogs visible on the phones? Is it possible to log into one of the macs either locally or remotely to see if any additional configuration is needed on the hosts?

**Comment by zanderso** [comment]
I think I found the issue. The fix in https://github.com/flutter/flutter/issues/147322 was not added to the script for mac in https://chrome-internal.googlesource.com/infradata/config/+/refs/heads/main/configs/chromium-swarm/scripts/flutter_mac_android.py#67.

**Comment by zanderso** [comment]
Fix in https://chrome-internal-review.googlesource.com/c/infradata/config/+/7528219

**Comment by kentnguyen99** [comment]
All new Mokey phones are online and ready for service. All issues have been resolved and fixed, "USB File Transfer" need to enable in system configuration.

**Comment by zanderso** [comment]
We should start to see some jobs run on the mokeys someone later today following https://github.com/flutter/flutter/pull/152499.

**Comment by zanderso** [comment]
These appear to be working.
