### ISSUE TITLE
HarmonyOS support

### ISSUE THREAD

**Issue by enrique12344321** [flutter/flutter#152463]
### Steps to reproduce

1. The HarmonyOS version of Flutter has been released recently. https://gitee.com/openharmony-sig/flutter_flutter
2. Harmony Engine for flutter. https://gitee.com/openharmony-sig/flutter_engine
3. I have created a project for ohos but I do not know how to run it on my harmony simulator.
4.  I have followed the steps in README and successfully created a project. However, when I type 'flutter run' , the project wasn't able to be runned on my Harmony simulator. **
![FlutterIssues20240729105224](https://github.com/user-attachments/assets/7b4cbf9f-c22d-4d01-8180-a591a2a4e9cf)
![FlutterIssues20240729105540](https://github.com/user-attachments/assets/6d51630a-7f9f-4dde-b80e-19c8156427fb)
Exception: Failed to get the hap file:
E:\flutterHarmony\project\test\ohos\./entry\build\default\outputs\default\entry-default-signed.hap**
 If I try 'flutter run ' using '--local-engine', it seems that the [flutter.har] file is missing.  
5. Could you please help me with this issue.
![FlutterIssues20240729105659](https://github.com/user-attachments/assets/f9ccf13b-88d9-4a8c-9424-6e728d63b88d)
![FlutterIssues20240729105718](https://github.com/user-attachments/assets/c4672d5c-3b97-4b44-9606-26a3ab0c00cf)
![FlutterIssues20240729105736](https://github.com/user-attachments/assets/0de511a7-204b-49f2-811b-e88eda98f2f8)

### Actual results

The HarmonyOS version of Flutter has been released recently.[]( https://gitee.com/openharmony-sig/flutter_flutter) And I have followed the steps in README and successfully created a project. However, when I type 'flutter run' , the project wasn't able to be runned on my Harmony simulator.  If I try 'flutter run ' using '--local-engine', it seems that the [flutter.har] file is missing.  I will be appreciated if you could help me with this issue.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by enrique12344321** [comment]
https://gitee.com/openharmony-sig/flutter_flutter
https://gitee.com/openharmony-sig/flutter_engine

**Comment by danagbemava-nc** [comment]
Kindly file an issue over here https://gitee.com/openharmony-sig/flutter_flutter/issues

The `openHarmony` fork of flutter is not maintained by the flutter team. 

Closing from here. 

Thank you
