### ISSUE TITLE
> Yes, this workaround increases letter spacing so it is not suitable for us. I just found another workaround which I not see in this thread:

### ISSUE THREAD

**Issue by deltoro05** [flutter/flutter#152483]
This URL https://unicode-table.com/ has changed to https://symbl.cc/

            > Yes, this workaround increases letter spacing so it is not suitable for us. I just found another workaround which I not see in this thread:
> 
> ```dart
>  text.replaceAll(' ', '\u{000A0}')
> ```
> 
> We started to use it and it seems that it "just works" for all our use cases. It just replaces all spaces in text with Unicode [No-Break Space](https://unicode-table.com/en/00A0/) character.
> 
> Hope it may help someone :)

@roman-petrov that's a good fix. If you make one more modification it also replaces hyphens with non-breaking hyphens:

```dart
'UFC 284 - Makhachev vs Volkanovski'
    .characters
    .replaceAll(Characters(' '), Characters('\u{00A0}'))
    .replaceAll(Characters('-'), Characters('\u{2011}'))
    .toString()
```

Without the second `replaceAll` the text looks like this:

"UFC 284 -..."

Instead of this:

"UFC 284 - Makhachev vs V..."

_Originally posted by @anthonymoretti in https://github.com/flutter/flutter/issues/18761#issuecomment-1415091689_

**Comment by darshankawar** [comment]
@deltoro05 
Please don't use comments from other issues to file a new issue. The linked issue is very old. Please use new issue template, fill out requested details so that we can properly address the issue.
Closing for now due to lack of details.
