### ISSUE TITLE
Issue from website page Get Started: Configure Editor

### ISSUE THREAD

**Issue by LU-Mobile** [flutter/flutter#15243]
From URL: https://flutter.io/get-started/editor.md

On Mac Sierra, after installing dart code and restarting VSC, search for doctor doesn't find any commands.

**Comment by Hixie** [comment]
cc @Sfshaza

**Comment by Sfshaza** [comment]
I haven't used VSC much. @mjohnsullivan, could you weigh in?

**Comment by DanTup** [comment]
In the first implementation, the Doctor command only appeared if you had a Flutter project open. It was fixed in https://github.com/Dart-Code/Dart-Code/issues/643 a few days before this was open (but not released until after).
