### ISSUE TITLE
`flutter create` warning regarding Java compatibility needs a bit of cleanup for consistency

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#152460]
I ran `flutter create` and got:
```
$ flutter create skiazoom
Creating project skiazoom...
Resolving dependencies in `skiazoom`...
Downloading packages...
Got dependencies in `skiazoom`.
Wrote 129 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd skiazoom
  $ flutter run

Your application code is in skiazoom/lib/main.dart.

The configured version of Java detected may conflict with the Android Gradle Plugin (AGP) version in your new Flutter app.

[RECOMMENDED] If so, to keep the default AGP version 8.1.0, make
sure to download a compatible Java version
(Java 17 <= compatible Java version < Java 21).
You may configure this compatible Java version by running:
`flutter config --jdk-dir=<JDK_DIRECTORY>`
Note that this is a global configuration for Flutter.


Alternatively, to continue using your configured Java version, update the AGP
version specified in the following files to a compatible AGP
version (minimum compatible AGP version: 7.0) as necessary:
    -  /home/ianh/dev/skiazoom/android/build.gradle

See
https://developer.android.com/build/releases/gradle-plugin for details on
compatible Java/AGP versions.
```

Some things we could improve:

* The wrapping is inconsistent throughout. Lines within paragraphs should all be roughly the same length, and paragraphs should have a blank line between them. ("See" on its own line, 

* We don't generally do `[RECOMMENDED]`, that's not normal English grammar. Just use a normal English sentence like "The recommended action is..." or whatever. 

* We use inconsistent style regarding how to execute commands. The top part uses indented paragraphs with `$ cd bla` whereas the recommended section uses backticks on an unindented line in a paragraph.

* "Note that" is redundant text and our style guide says to just not have it.

* There's one paragraph that ends with an indented line with hyphens as a bullet and two spaces. This is unusual for our output in the tool as well.

**Comment by Hixie** [comment]
Also, interestingly, `flutter doctor` isn't reporting this as an issue.

**Comment by shashwatpathak98** [comment]
Hi @andrewkolos @darshankawar linked a PR above which should fix this issue. Please let me know if you have any feedback/suggestion. :)
