### ISSUE TITLE
Flutter web on download without file dialog freezes in chromium based browsers

### ISSUE THREAD

**Issue by atreptow** [flutter/flutter#152544]
### Steps to reproduce

1. Open a flutter web app that offers downloading a file from a remote
2. Make sure your browser directly downloads to your download folder and does not open a file dialog
3. Trigger the download

Used versions:
flutter 3.22.2 on dart 3.4.3
chrome 127.0.6533.72 (but was also reproducable with 126 and 125)

### Expected results

The download starts and you can continue to use the app while the download runs in the background.

### Actual results

The webapp freezes for quite some time. The time seems not related to the time the download takes. The freeze can be unblocked by removing focus from the current browser window (e.g. click into dev tools) or resizing the view.
Without unblocking it might take a few minutes until the app unfreezes.

### Code sample

https://dartpad.dev/?id=3d77b2fb211cfec9dca72766404aa480

### Flutter Doctor output

$ flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on Ubuntu 22.04.4 LTS 6.5.0-1025-oem, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at ~/fvm/versions/3.22.2
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 761747bfc5 (8 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from https://www.freedesktop.org/wiki/Software/pkg-config/

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.4 LTS 6.5.0-1025-oem
    • Chrome (web)    • chrome • web-javascript • Chromium 126.0.6478.182 snap

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

**Comment by danagbemava-nc** [comment]
This was initially reported in https://github.com/flutter/flutter/issues/149417 and has since been fixed by https://github.com/flutter/flutter/issues/150636. A cherrypick request has been filed in https://github.com/flutter/flutter/issues/152303, hopefully it gets added to the current stable. 

Closing as this has already been fixed. 

Thank you
