### ISSUE TITLE
build apk

### ISSUE THREAD

**Issue by androidq** [flutter/flutter#152534]
### Steps to reproduce

1、pubspec.yaml version: 1.0.1+2
2、flutter build apk --target-platform android-arm --split-per-abi

### Expected results

Version name: 1.0.1
Version number: 2

### Actual results

Version name: 1.0.1
Version number: 1002

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by androidq** [comment]
![a8af15665a7d1b9c25ec277e50d5024](https://github.com/user-attachments/assets/e599de84-d861-4274-b72d-c83cebfe3067)

**Comment by hellojukay** [comment]
作为一个中国人，我也看不懂你的 issue 要表达什么

**Comment by androidq** [comment]
> 作为一个中国人，我也看不懂你的问题要表达什么
使用 flutter build apk --target-platform android-arm --split-per-abi 打包后
versionCode 打包应该是2 ,实际的结果却是1002

**Comment by hellojukay** [comment]
> > 作为一个中国人，我也看不懂你的问题要表达什么
> > 使用 flutter build apk --target-platform android-arm --split-per-abi 打包后
> > versionCode 打包应该是2 ,实际的结果却是1002

试试全局搜索一下 1002 这个是在哪里配置的

**Comment by androidq** [comment]
> > > 作为一个中国人，我也看不懂你的问题要表达什么
> > > 使用 flutter build apk --target-platform android-arm --split-per-abi 但压缩后
> > > 版本代码 压缩应该是 2 ，实际的结果是 1002
> 
> 尝试全局搜索一下 1002 这个是在哪里配置的
肯定是没有配置，都是在pubspec.yaml中的version: 1.0.1+2 定义。

**Comment by darshankawar** [comment]
@androidq 
Please try to post in English for better readability.
You seem to be hitting https://github.com/flutter/flutter/issues/133770 in which you can follow-up for further updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
