### ISSUE TITLE
Flutter first codelabs : dead link on french page

### ISSUE THREAD

**Issue by Azel-ytof** [flutter/flutter#152558]
### Steps to reproduce

Hi,

Just go on flutter first codelabs page[first codelabs page](https://codelabs.developers.google.com/codelabs/flutter-codelab-first)
Go to the last step (the 9), and at the end there is a link "version avancée" which give an error.

### Expected results

Same as the english page : https://dartpad.dev/?id=e7076b40fb17a0fa899f9f7a154a02e8

### Actual results

https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8

### Code sample

No code because it is website

### Flutter Doctor output

No doctor because it is website

**Comment by raywick** [comment]
The same happens in the Spanish version of this page.
![image](https://github.com/user-attachments/assets/b00ae0a6-876d-4755-88d1-1eb1be75a55a)

**Comment by domesticmouse** [comment]
This should be fixed in the next five minutes or so. Please ping this thread if it still reproduces as broken.
