### ISSUE TITLE
`flutter run` can fail the first time when trying to set up gradle

### ISSUE THREAD

**Issue by kriuz** [flutter/flutter#15253]
## Steps to Reproduce
- Have `JAVA_HOME` set by an `export` command in a  `.bashrc`, `.zshrc` file or something of the like and run `flutter run`
- This can fail and show some misleading errors like
  - cannot get `https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom`
  - or `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException`

## Work-around
Looks like `flutter run` can't find the path to java, running `JAVA_HOME=<java path> flutter run` solves the problem and it's not needed in subsequent runs.

**Comment by yonlau** [comment]
Encounter same issue here! Any solution ?

**Comment by zoechi** [comment]
You need to create a new shell window for the changes to take effect or perhaps restart the system for the changes to take effect.
This is not really a Flutter issue.
