### ISSUE TITLE
flutter - url_launcher wont work when app downloeded from store

### ISSUE THREAD

**Issue by zifnap** [flutter/flutter#152574]
### Steps to reproduce

Here's my code using url_launcher:

```

```
In my case:

### Expected results

expect to open links even in launched mode of app

### Actual results

The updated function works well in release and debug modes but does not work when the app is downloaded from the store (both iOS and Android). Because there are no errors in debug and release modes, I can't test the issue directly. I can only upload a new version to the store, hoping it will work. If anyone knows a solution, please share it. Otherwise, I might have to revert to using the deprecated function again.

### Code sample

<details open><summary>Code sample</summary>

```dart

void _handleLinkTap() async {
    String? url = widget.snap["pageUrlMap"][widget.snap["uuids"][_selectedImageIndex]];
    if (url != null) {
      Uri uri = Uri.parse(url);
      try {
        await launchUrl(uri);
      } catch (e) {
        // Error handling: open in web browser if the app cannot handle the URL
        if (url.startsWith('http://') || url.startsWith('https://')) {
          await launchUrl(Uri.parse(url));
        } else {
          await launchUrl(Uri.parse('http://$url'));
        }
      }
    }
  }
```

This code works fine in both debug and release modes on my device. However, after publishing my app update to the store, I realized that the links won't open when the app is downloaded from the store (on both iOS and Android).

Here's my previous code, which worked fine even in the downloaded version of the app:

```

// Deprecated
/*void _handleLinkTap() async {
    String? url = widget.snap["pageUrlMap"][widget.snap["uuids"][_selectedImageIndex]];
    if (url != null) {
      Uri uri = Uri.parse(url);
      try {
        await launchUrl(uri);
      } catch (e) {
     // Error handling: open in web browser if the app cannot handle the URL
        if (url.startsWith('http://') || url.startsWith('https://')) {
          await launch(url);
        } else {
          await launch('http://$url');
        }
      }
    }
  }*/
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
> ```dart
> String? url = widget.snap["pageUrlMap"][widget.snap["uuids"][_selectedImageIndex]];
> ```

We cannot investigate without a reproducible test case, and this code isn't usable without code you have not provided. You'll need to provide an actual string value here that we can look at.

However, there are some red flags in your code:
> ```dart
>         // Error handling: open in web browser if the app cannot handle the URL
>         if (url.startsWith('http://') || url.startsWith('https://')) {
>           await launchUrl(Uri.parse(url));
> ```

You are not passing `LaunchMode.externalApplication`, so the code does not match the comment. (It is in fact exactly the same call that was made in the `try` that this is the `catch` for, so it will fail if the `try` failed.)

> ```dart
>         } else {
>           await launchUrl(Uri.parse('http://$url'));
>         }
> ```

`launchUrl` requires a valid absolute URL, and a valid absolute URL must have a scheme. Either you are passing invalid input into `launchUrl` in the try, because there is no scheme, or you are passing invalid input here because you are constructing a URL with two schemes. You should be ensuring that you pass valid input *before* calling `launchUrl`, not passing in known-bad values and then catching the resulting error.

**Comment by zifnap** [comment]
The URL entered by users can be any URL, such as a specific YouTube link (e.g., https://www.youtube.com/watch?......) or a general link like https://www.instagram.com/. The URL is retrieved from widget.snap["pageUrlMap"][widget.snap["uuids"][_selectedImageIndex]] in our code. This structure stores different URLs that users might enter or share.

Error Handling and LaunchMode:

"I tried to address the red flag points with the code below. I plan to test it on the App Store and Play Store, but the main concern here is: if my code is flawed, why does it work in debug and release mode but not when launched from the store?

Here is my updated code. If there are no additional flags or issues, I will proceed with testing it."


```
void _handleLinkTap() async {
  String? url = widget.snap["pageUrlMap"][widget.snap["uuids"][_selectedImageIndex]];
  if (url != null) {
    try {
      // Check if the URL is valid and has a scheme
      Uri uri = Uri.parse(url);
      if (uri.scheme.isEmpty) {
        // If no scheme, assume http by default
        uri = Uri.parse('http://$url');
      }

      // Try to open in-app if possible
      bool launched = await launchUrl(uri, mode: LaunchMode.externalApplication);
      if (!launched) {
        // Fallback to opening in external browser if in-app fails
        if (url.startsWith('http://') || url.startsWith('https://')) {
          await launchUrl(uri, mode: LaunchMode.externalApplication);
        } else {
          await launchUrl(Uri.parse('http://$url'), mode: LaunchMode.externalApplication);
        }
      }
    } catch (e) {
      // Handle errors and provide fallback
      print('Error: $e');
      if (url.startsWith('http://') || url.startsWith('https://')) {
        await launchUrl(Uri.parse(url), mode: LaunchMode.externalApplication);
      } else {
        await launchUrl(Uri.parse('http://$url'), mode: LaunchMode.externalApplication);
      }
    }
  }
}
```

**Comment by darshankawar** [comment]
@zifnap 
For iOS : `externalApplication` and for Android : `externalNonBrowserApplication` likely should help.
