### ISSUE TITLE
image_picker pickMultiImage option not working on android 10 and below

### ISSUE THREAD

**Issue by Nandhini-GA** [flutter/flutter#152554]
### Steps to reproduce

multi image picker option working only on android version 11 and above 

### Expected results

how to make this functionality working on android 10 and below

### Actual results

pickMultiImage option not working on android version 10 and below

### Code sample

```
final  images = await ImagePicker().pickMultiImage(
 limit:4,
  imageQuality: 70,
  maxHeight: 1920,
  maxWidth: 1920,
);
```

### Flutter Doctor output

Flutter version 3.22.3 on channel stable

**Comment by danagbemava-nc** [comment]
Hi @Nandhini-GA, can you explain what you mean by not working? Are you getting an error? Are you not able to select multiple items? What devices have you tested on and what version of `image_picker` & `image_picker_android` are you using?

**Comment by Nandhini-GA** [comment]
device is Redmi Note 7 pro/10 and also checked android 9 and 10 emulators
Using latest version of plugin image_picker_android: ^0.8.12+10

**Comment by danagbemava-nc** [comment]
Hi @Nandhini-GA, can you try enabling the photoPicker to see if that works? See https://pub.dev/packages/image_picker_android#photo-picker

If using the photopicker doesn't work, then it is likely the system photopicker on those devices do not support it.

**Comment by Nandhini-GA** [comment]
i already added these lines

```
final ImagePickerPlatform imagePickerImplementation =
        ImagePickerPlatform.instance;
    if (imagePickerImplementation is ImagePickerAndroid) {
      imagePickerImplementation.useAndroidPhotoPicker = true;
    }
```

**Comment by danagbemava-nc** [comment]
Hi @Nandhini-GA, then it may be that the standard image picker on those devices do not support the feature. Are you able to select multiple images as expected with any of the apps on your devices using the standard image_picker?
