### ISSUE TITLE
flutter->packages roller blocked on `google_maps_flutter_android` regression due to enabling Impeller

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#152691]
The flutter/flutter->flutter/packages roller is a few days behind, due to a persistent regression that was not immediately obvious because of the macOS host infra flake causing most rolls to fail without manual effort recently. I've been bisecting the failure, and have narrowed it down to
~https://github.com/flutter/flutter/compare/f817e51a3a34...a7bd806fc7f3~
~as a definite window, and almost certainly (pending finalization of that roll)~
~https://github.com/flutter/flutter/compare/e2e43987c4fb...a7bd806fc7f3~

~The latter window is one added test, some Skia rolls, and very notably https://github.com/flutter/engine/pull/54156 which enabled Impeller by default for Android.~
[Edited now that I've narrowed from a window to an exact commit]
[this commit](https://github.com/flutter/flutter/pull/152464), which only contains https://github.com/flutter/engine/pull/54156, which enabled Impeller by default for Android. (https://github.com/flutter/packages/pull/7284 is the PR that confirms this: a flutter/packages roll that only rolls that one commit, and introduces the crash.

Here's an example failure run: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8740895214831365361/+/u/Run_package_tests/Firebase_Test_Lab/stdout
There's a ton in that logging, but if you search for "Application crashed" and look at the FTL link there, it goes to the failure.

An example failure output:
```
Build fingerprint: 'google/panther/panther:13/TQ3A.230605.012/10204971:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2024-07-31 06:04:29.386233348-0700
Process uptime: 3s
Cmdline: io.flutter.plugins.googlemapsexample
pid: 20262, tid: 20262, name: oglemapsexample  >>> io.flutter.plugins.googlemapsexample <<<
uid: 10261
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1699)] Check failed: fml::jni::CheckException(env). '
    x0  0000000000000000  x1  0000000000004f26  x2  0000000000000006  x3  0000007fc414fc70
    x4  6d602e6c716e6573  x5  6d602e6c716e6573  x6  6d602e6c716e6573  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007d625469e0  x10 0000000000000001  x11 0000007d62588370
    x12 000000000000065c  x13 000000000000007e  x14 0000007fc414eb40  x15 000000079e8e5c5d
    x16 0000007d625f5d50  x17 0000007d625d0eb0  x18 0000007d6676a000  x19 0000000000004f26
    x20 0000000000004f26  x21 00000000ffffffff  x22 b400007b65031f50  x23 0000007b15089b38
    x24 0000000000000000  x25 0000000000000920  x26 0000000000000000  x27 0000007fc414ff68
    x28 00000000000000e9  x29 0000007fc414fcf0
    lr  0000007d625781c8  sp  0000007fc414fc50  pc  0000007d625781f4  pst 0000000000001000
backtrace:
      #00 pc 00000000000531f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: dc4001c2ef2dfc23467040797a96840c)
      #01 pc 0000000001cedf9c  /data/app/~~ea2V_pYwTb455BI-pIrB8g==/io.flutter.plugins.googlemapsexample-
```

I'm going to do more spot checking of failed rolls, but it looks like this is happening in either all or almost all of the roll PRs since that point.

So there are two serious problems here:
- the roller is blocked (which we could work around by disabling all `google_maps_flutter` tests for now, but...)
- `google_maps_flutter` seems to have very persistent crashing issues under Impeller.

**Comment by stuartmorgan** [comment]
I've finished a manual audit. For context, the Android `google_maps_flutter` integration tests run twice, once with the legacy renderer and once with the latest renderer (these are Google Maps renderers, not a Flutter-level concept). When running FTL tests, the flutter/packages tooling has one built-in retry, so a good run would have two cycles of FTL tests, and a bad one can have up to four.
- There have been 16 attempted rolls since the problem started.
- Every one of them has at least one instance of this failure.
- The large majority of them have four instances: two tries for each render mode.
- A few have only two instances, with one render mode passing, and the other failing.

So it's not a 100% crash rate on the integration tests, but it's very very close.

**Comment by stuartmorgan** [comment]
I should also mention that I've ruled out OOB breakage from a server-side Google Maps change—which would otherwise be a very plausible cause of new crashes based on our previous experience—because I've been able to land manual rolls that bisected the original bad roll, and those have been fine up until the hash range identified above.

**Comment by stuartmorgan** [comment]
I'm about to land a change that switches the example app that's crashing from HC mode to TLHC mode. Anyone investigating this issue should check out flutter/packages at 945f5141bdbd032396831389ab9664e8317e5e98 or earlier to continue to have the configuration that was encountering the problem.

(I'll update here once I see whether rolls succeed once that lands.)

**Comment by stuartmorgan** [comment]
> (I'll update here once I see whether rolls succeed once that lands.)

It didn't; https://github.com/flutter/packages/pull/7286, which is a roll started after the switch, still crashes. So either the crash is in an integration test that's forcing HC, or a variant of the crash happens in TLHC mode. (I'm not on corp so I can't see the full logs to see if the underlying exception location has changed.)

**Comment by jason-simmons** [comment]
This is happening because of a race between platform view composition and disposal.

Can reproduce it by running `flutter test integration_test/latest_renderer_test.dart` in https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter_android/example

When this happens the `PlatformViewsController` receives a call to `dispose` for a view before the rasterizer calls `AndroidExternalViewEmbedder::SubmitFlutterView` for that same view.  `SubmitFlutterView` makes a JNI call to `PlatformViewsController.onDisplayPlatformView` and `initializePlatformViewIfNeeded`, which sees that the platform view ID no longer exists and throws the exception seen in the FTL logs.

Both the `dispose` and `SubmitFlutterView` calls happen on the platform thread.  But the set of platform view IDs referenced in the scene is gathered on the UI thread.  So those view IDs could become invalid by the time the rasterizer invokes `SubmitFlutterView`.

This does not appear to be specifically related to Impeller.  But enabling Impeller apparently changes the timing so that this race is much more likely to occur.

**Comment by stuartmorgan** [comment]
Retitling since disabling impeller in that plugin's example app was enough to unblock the roller. We're still blocked from running those tests with impeller though.
