### ISSUE TITLE
Can Impeller be disabled by default?

### ISSUE THREAD

**Issue by ac169** [flutter/flutter#152653]
### Use case

```
Failed to send request: {"jsonrpc":"2.0","id":"26","method":"getMemoryUsage","params":{"isolateId":"isolates/430315217091623"}}
Exception: Unable to terminate com.***.*** on DEC7A7D2-0B3F-......:
ProcessException: Process exited abnormally:

  Command: xcrun simctl terminate DEC7A7D2-0B3F-...... com.***.***
the Dart compiler exited unexpectedly.
```

### Proposal

There are two solutions according to the reference document

1.Add startup parameters: --no-enable-impeller

2.Modify the Info.plist file

```
<key>FLTEnableImpeller</key>
<false/>
```
This modification can indeed solve the problem, but I personally think it would be a bit cumbersome to modify it every time I create a new project. Is there any way to do it once and for all? For example: Are there any global configuration parameters?

In addition, will this problem only appear on the IOS simulator or will it also appear on real machines with lower system versions? If Impeller is disabled in Info.plist, will it affect the performance of the release version of the application on the real machine?

Modify the Info.plist file

```
<key>FLTEnableImpeller</key>
<false/>
```

**Comment by jonahwilliams** [comment]
There is no supported method to globally disable Impeller, and we plan to remove the Skia backed from iOS builds later this year. 

I don't know what the issue you're facing is though, so I can't give you any guidance on a workaround.

**Comment by ac169** [comment]
> Skia

after removing Skia, will the Impeller be optimized for the above error when running on the simulator? Or now the new version has fixed the problem, currently my flutter version is 3.16.x

**Comment by jonahwilliams** [comment]
You haven't posted any information that would allow us to diagnose an error.

**Comment by ac169** [comment]
```
Failed to send request: {"jsonrpc":"2.0","id":"26","method":"getMemoryUsage","params":{"isolateId":"isolates/430315217091623"}}
Exception: Unable to terminate com.***.*** on DEC7A7D2-0B3F-......:
ProcessException: Process exited abnormally:

  Command: xcrun simctl terminate DEC7A7D2-0B3F-...... com.***.***
the Dart compiler exited unexpectedly.
```

i wrote about the problem and the current solution in the first paragraph

**Comment by jonahwilliams** [comment]
Those are just logs indiciating that the app exited. Please look at the issue template for examples of the information we'd need to diagnose a problem.

**Comment by ac169** [comment]
If you must submit information according to the template to solve I think it is better to forget it! Because this problem is easy to repeat and not only I have encountered, because the solution of shutting down the impeller is provided by another user! I just think it's a hassle to make changes every time I create a new project!

**Comment by jonahwilliams** [comment]
Happy Coding!
