### ISSUE TITLE
flutter news template

### ISSUE THREAD

**Issue by 12234e** [flutter/flutter#152609]
### Steps to reproduce

I am facing issue when I run flutter news template in vs code, it showing something error in buil.gradle version

### Expected results

I am facing issue when I run flutter news template in vs code, it showing something error in buil.gradle version

### Actual results

I am facing issue when I run flutter news template in vs code, it showing something error in buil.gradle version

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @12234e, what errors are you getting? Have you completed the setup stated in the documentation, including the firebase setup? 

PS: In the future, please provide the relevant information required to reproduce the issue so that it can be properly investigated.

Thank you

**Comment by 12234e** [comment]
I need only the flutter news template setup tutorial with firebase, I have searched on google but I didn't find any tutorial

**Comment by 12234e** [comment]
Launching lib/main/main_production.dart on sdk gphone64 x86 64 in debug mode...
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply


Warning: The plugin android_intent_plus requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin firebase_analytics requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin firebase_auth requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin firebase_core requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin firebase_crashlytics requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin firebase_dynamic_links requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin firebase_messaging requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin flutter_secure_storage requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin google_sign_in_android requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin in_app_purchase_android requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin path_provider_android requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin share_plus requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin shared_preferences_android requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin sign_in_with_apple requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin sqflite requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin url_launcher_android requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin video_player_android requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
Warning: The plugin webview_flutter_android requires Android SDK version 34 or higher.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to D:\dev\daily_globe\android\app\build.gradle:
android {
  compileSdkVersion 34
  ...
}

**Comment by jaypal1046** [comment]
Hey @12234e,

please go to this path: android\app\build.gradle
check that your compileSdkVersion is 34

**Comment by 12234e** [comment]
I did fix it but the error is not fixed yet, error coming one after one,
its very hard to undrestand

**Comment by jaypal1046** [comment]
Hi @12234e ,
 For the warning go to Android Studio -> Settings  ->SDK Manager -> SDK Platform and download 34 or the latest SDK

**Comment by danagbemava-nc** [comment]
Hi @12234e, what error do you get after updating the compileSdkVersion? You can find the instructions to setup firebase in your news app over here https://flutter.github.io/news_toolkit/project_configuration/firebase
