### ISSUE TITLE
You can provide your own HttpClient now.

### ISSUE THREAD

**Issue by xAffan** [flutter/flutter#152670]
You can provide your own HttpClient now.

_Originally posted by @Hixie in https://github.com/flutter/flutter/issues/4162#issuecomment-337391447_
            Any doocumentation? How?

**Comment by danagbemava-nc** [comment]
Please do not file issues with comments from closed issues. File issues with the issue templates and provide detailed information as to what you want to achieve. 

Closing as there isn't much information provided. 

Thank you
