### ISSUE TITLE
[packages] Migrate to applying Gradle plugins with the declarative plugins block

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#152656]
When running `google_maps_flutter` example on Android:

```console
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply
```

We first need to determine which plugin examples need this, and then update them all

### List of sample apps

([how it was obtained](https://github.com/flutter/flutter/issues/152656#issuecomment-2379369995))

- [x] flutter_plugin_android_lifecycle/example/android
- [x] path_provider/path_provider/example/android
- [x] path_provider/path_provider_android/example/android
- [x] two_dimensional_scrollables/example/android
- [x] webview_flutter/webview_flutter/example/android
- [x] webview_flutter/webview_flutter_android/example/android
- [x] file_selector/file_selector/example/android
- [x] file_selector/file_selector_android/example/android
- [x] google_sign_in/google_sign_in/example/android
- [x] google_sign_in/google_sign_in_android/example/android
- [x] pigeon/platform_tests/test_plugin/example/android
- [x] pigeon/platform_tests/alternate_language_test_plugin/example/android
- [x] pigeon/example/android
- [x] interactive_media_ads/example/android
- [x] flutter_adaptive_scaffold/example/android
- [x] palette_generator/example/android
- [x] camera/camera/example/android
- [x] camera/camera_android/example/android
- [x] camera/camera_android_camerax/example/android
- [x] local_auth/local_auth_android/example/android
- [x] local_auth/local_auth/example/android
- [x] video_player/video_player_android/example/android
- [x] video_player/video_player/example/android
- [x] url_launcher/url_launcher_android/example/android
- [x] url_launcher/url_launcher/example/android
- [x] google_maps_flutter/google_maps_flutter/example/android
- [x] google_maps_flutter/google_maps_flutter_android/example/android
- [x] in_app_purchase/in_app_purchase_android/example/android
- [x] in_app_purchase/in_app_purchase/example/android
- [x] image_picker/image_picker/example/android
- [x] image_picker/image_picker_android/example/android
- [x] go_router/example/android
- [x] extension_google_sign_in_as_googleapis_auth/example/android
- [x] flutter_markdown/example/android
- [x] quick_actions/quick_actions_android/example/android
- [x] quick_actions/quick_actions/example/android
- [x] shared_preferences/shared_preferences/example/android
- [x] shared_preferences/shared_preferences_android/example/android
- [x] animations/example/android
- [x] espresso/example/android
- [x] flutter_image/example/android
- [x] packages/rfw/example/local/android
- [x] packages/rfw/example/hello/android
- [x] packages/rfw/example/remote/android
- [x] third_party/packages/flutter_svg/example/android

**Comment by reidbaker** [comment]
cc: @bartekpacia FYI 

Android team needs to migrate example apps. Not on the the plan for 2024Q3.

**Comment by camsim99** [comment]
Migration guide: https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

**Comment by bartekpacia** [comment]
@camsim99 I am willing to get started on this. If there's no onoe assigned rn, can I assign myself?

**Comment by reidbaker** [comment]
@bartekpacia we were looking for good onboarding tasks for our new teammate @jesswrd. So yes, feel free to coordinate in this bug what packages you will take but the bigger help would be as a reviewer for @jesswrd.

**Comment by bartekpacia** [comment]
Sure, gotcha!

I ran this command in root of the `flutter/packages` repo to get the list of sample apps found in there:

```
find . -type f -path "*/example/android/build.gradle" -exec dirname {} \; | xargs -L 1 -I{} printf '[ ]: %s X' {} | tr 'X' '\n'
```

<details><summary>Output</summary>

```
[ ]: ./packages/flutter_plugin_android_lifecycle/example/android
[ ]: ./packages/path_provider/path_provider/example/android
[ ]: ./packages/path_provider/path_provider_android/example/android
[ ]: ./packages/two_dimensional_scrollables/example/android
[ ]: ./packages/webview_flutter/webview_flutter/example/android
[ ]: ./packages/webview_flutter/webview_flutter_android/example/android
[ ]: ./packages/file_selector/file_selector/example/android
[ ]: ./packages/file_selector/file_selector_android/example/android
[ ]: ./packages/google_sign_in/google_sign_in/example/android
[ ]: ./packages/google_sign_in/google_sign_in_android/example/android
[ ]: ./packages/pigeon/platform_tests/test_plugin/example/android
[ ]: ./packages/pigeon/platform_tests/alternate_language_test_plugin/example/android
[ ]: ./packages/interactive_media_ads/example/android
[ ]: ./packages/flutter_adaptive_scaffold/example/android
[ ]: ./packages/palette_generator/example/android
[ ]: ./packages/camera/camera/example/android
[ ]: ./packages/camera/camera_android/example/android
[ ]: ./packages/camera/camera_android_camerax/example/android
[ ]: ./packages/local_auth/local_auth_android/example/android
[ ]: ./packages/local_auth/local_auth/example/android
[ ]: ./packages/platform/example/android
[ ]: ./packages/video_player/video_player_android/example/android
[ ]: ./packages/video_player/video_player/example/android
[ ]: ./packages/url_launcher/url_launcher_android/example/android
[ ]: ./packages/url_launcher/url_launcher/example/android
[ ]: ./packages/dynamic_layouts/example/android
[ ]: ./packages/google_maps_flutter/google_maps_flutter/example/android
[ ]: ./packages/google_maps_flutter/google_maps_flutter_android/example/android
[ ]: ./packages/in_app_purchase/in_app_purchase_android/example/android
[ ]: ./packages/in_app_purchase/in_app_purchase/example/android
[ ]: ./packages/image_picker/image_picker/example/android
[ ]: ./packages/image_picker/image_picker_android/example/android
[ ]: ./packages/go_router/example/android
[ ]: ./packages/extension_google_sign_in_as_googleapis_auth/example/android
[ ]: ./packages/flutter_markdown/example/android
[ ]: ./packages/quick_actions/quick_actions_android/example/android
[ ]: ./packages/quick_actions/quick_actions/example/android
[ ]: ./packages/shared_preferences/shared_preferences/example/android
[ ]: ./packages/shared_preferences/shared_preferences_android/example/android
[ ]: ./packages/animations/example/android
[ ]: ./packages/espresso/example/android
[ ]: ./packages/flutter_image/example/android
```

</details>

**Comment by bartekpacia** [comment]
Also (just an idea) while we're at it, maybe (a subset of) the example apps could be converted to Gradle KTS?

**Comment by reidbaker** [comment]
In general we try to keep the packages as consistent as possible for easy of maintainability. 
That said https://github.com/flutter/packages/blob/0321757447bfba7705429f371b2e5b3a6930d559/packages/pigeon/example/app/android/app/build.gradle is a good conversion candidate since that example app is for the kotlin build version of pigeon.

**Comment by AbdeMohlbi** [comment]
I'd like to take 
shared_preferences/shared_preferences_android/example/android and update of it's possible?

**Comment by jesswrd** [comment]
Removed `platform/example/android` and `dynamic_layouts/example/android` as they have been moved to a new location or deleted. Added  a few outstanding example plugin apps to migration checklist, including `rfw` and `third_party` .

**Comment by jmagman** [comment]
Does the all packages test project also need to be updated? https://github.com/flutter/packages/blob/3515abab07d0bb2441277f43c2411c9b5e4ecf94/.ci/legacy_project/all_packages/android/settings.gradle#L11

I noticed it here https://github.com/flutter/packages/pull/8328
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8728179667738494273/+/u/Run_package_tests/build_all_packages_for_Android_-_legacy_version/stdout

**Comment by bartekpacia** [comment]
as far as I know – yes, because we need to remove support for the "old way" of applying Flutter Gradle Plugin to rewrite it to Kotlin – which is the team's aim for 2025 – again, AFAIK :)
