### ISSUE TITLE
Framework 'XXX' not found

### ISSUE THREAD

**Issue by no-chili** [flutter/flutter#152678]
### Steps to reproduce

I have removed the plugins that are no longer in use, but during build or debug, it still prompts that these Frameworks are needed, as if the references in the project were not deleted. I’ve tried modifying the Other Linker Flags in Xcode, but when I run flutter build ipa again, they are regenerated. Can someone help me find out the cause?
On Android it’s fine, only iOS has the issue.

### Actual results

Unable to build successfully.

### Logs

```
Error (Xcode): Framework 'TLPhotoPicker' not found


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Encountered error while archiving for device.
```

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.90.2)
[✓] Connected device (5 available)            
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by amorenew** [comment]
Did you try `flutter clean`?

**Comment by no-chili** [comment]
Yes, I also tried deleting the Pod file, Podfile.lock, .symlinks, Runner.xcworkspace, and any other cache interference I could think of. but The issue still persists.@amorenew

**Comment by huycozy** [comment]
@no-chili Are you using [hl_image_picker](https://pub.dev/packages/hl_image_picker)? Does the issue only happen if you add that plugin to the project? Please provide the output of `flutter run -v`.

**Comment by no-chili** [comment]
I am no longer using it and have deleted the relevant code, but when I remove it from pubspec.yaml, the project cannot run. I have to add it back to work normally. The same error occurs when removing other unused plugins, so it should not be an issue with a specific package. Below is my Podfile and the running log.

<details>
<summary>Podfile</summary>

```
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
    end
    if target.name == "geolocator_apple"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'BYPASS_PERMISSION_LOCATION_ALWAYS=1']
      end
    end
  end
end

```
</details>

[flutter_run_log.txt](https://github.com/user-attachments/files/16467107/flutter_run_log.txt)

**Comment by huycozy** [comment]
>The same error occurs when removing other unused plugins, so it should not be an issue with a specific package.

It looks like an issue with specific configurations. Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that I can try running it on my end to reproduce the issue?
