### ISSUE TITLE
Custom http client for networkimage

### ISSUE THREAD

**Issue by xAffan** [flutter/flutter#152682]
### Use case

use proxy / auth headers

### Proposal

NetworkImage.httpclient = ...

**Comment by mansourzaki** [comment]
Hi @xAffan 
That would be a great feature.
Regarding auth Headers I guess NetworkImage already has a headers property and there you can add your auth header,
you can check this link out https://api.flutter.dev/flutter/painting/NetworkImage/headers.html
I found something may be similar for your needs now 
https://github.com/flutter/flutter/issues/150941#issuecomment-2197152865

**Comment by xAffan** [comment]
> Hi @xAffan 
> That would be a great feature.
> Regarding auth Headers I guess NetworkImage already has a headers property and there you can add your auth header,
> you can check this link out https://api.flutter.dev/flutter/painting/NetworkImage/headers.html
> I found something may be similar for your needs now 
> https://github.com/flutter/flutter/issues/150941#issuecomment-2197152865
> 
> 

I really appreciate it. That really works for my needs.

**Comment by huycozy** [comment]
Closing this as the solution has been provided above.
