### ISSUE TITLE
[Impeller] AHB to KHR swapchain fallback causes flicker in the Android Google Maps example app.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#152698]
And likely others.

We should figure out why the fallback happens because the experience falling back isn't good.

**Comment by chinmaygarde** [comment]
cc @jonahwilliams for thoughts on if we understand why this happens.

**Comment by jonahwilliams** [comment]
This is: https://github.com/flutter/flutter/issues/152263
