### ISSUE TITLE
Drawer Header Color Issues

### ISSUE THREAD

**Issue by ChAraya** [flutter/flutter#15271]
## Steps to Reproduce

I'm doing an App for an University in Chile (Universidad Catolica del Norte) with flutter everything is fine but when it comes to the Drawer i'm having some issues with the color on the top of the DrawerHeader

I tested in iOS and Android emulator as well on my Own Device and is the same problem

here some pics (that white bar doesn't have to be there, must be the same bluish color)

![captura de pantalla 2018-03-07 a la s 21 00 51](https://user-images.githubusercontent.com/19436477/37125930-715b3266-224d-11e8-86a6-6eb04c4b1d37.png)

I don't have any erro beside the color rendering in the header.

i just follow the standar Drawer example in flutter gallery and is the same result but in the example works just fine i don't know why

Regards!

The code:

```
@override
  Widget build(BuildContext context) {
   final double systemTopPadding = MediaQuery.of(context).padding.top;
    return new DrawerHeader(
      decoration: widget.decoration ?? new BoxDecoration(
        color: new Color.fromRGBO(36, 65, 91, 1.0),
      ),
      margin: widget.margin,
      padding: const EdgeInsetsDirectional.only(top: 16.0, start: 16.0),
      child: new SafeArea(
        bottom: false,
        child: new Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            new Expanded(
              child: new Padding(
                padding: const EdgeInsetsDirectional.only(end: 16.0),
                child: new _AccountPictures(
                  currentAccountPicture: widget.currentAccountPicture,
                  otherAccountsPictures: widget.otherAccountsPictures,
                ),
              )
            ),
            new _AccountDetails(
              accountName: widget.accountName,
              accountEmail: widget.accountEmail,
              isOpen: _isOpen,
              onTap: widget.onDetailsPressed == null ? null : _handleDetailsPressed,
            ),
          ],
        ),
      ),
    );
  }
```

**Comment by Hixie** [comment]
Try removing the padding you set on the DrawerHeader:
```
      padding: const EdgeInsetsDirectional.only(top: 16.0, start: 16.0),
```

**Comment by ChAraya** [comment]
@Hixie nothing happend u.u still that grey bar there

**Comment by ChAraya** [comment]
@Hixie i fix it! using

new MediaQuery.removePadding(
            context: context,
            // DrawerHeader consumes top MediaQuery padding.
            removeTop: true,

Thanks anyway!
