### ISSUE TITLE
cmd getting crashed after using command flutter doctor or create

### ISSUE THREAD

**Issue by AdreshSingh** [flutter/flutter#152788]
### Steps to reproduce

I am using window 10 as OS and recently installed Flutter. It was working fine but now after reinstallation, Flutter not working.
It only shows:  Unable to locate git in your Path

I have applied lots of method that were on other platforms and also on flutter GitHub previously issue.

i have added every env variables, which you can see:
![image](https://github.com/user-attachments/assets/a7d82cdf-8ecf-434c-849f-5a96d60323fc)

I am able to check that variable working fine but the error still going on.
![cmd_report](https://github.com/user-attachments/assets/4980caff-42a7-4b27-a719-dfa8e19f61aa)

the error can only be seen on PowerShell as cmd gets crashed after any flutter command.

![image](https://github.com/user-attachments/assets/45117b24-c4eb-48a4-8500-dc610b2fc34c)

### Actual results

![image](https://github.com/user-attachments/assets/be1565f9-2826-42dc-b1b5-caa94f24b17f)

i have tried lots of step but only one error is mentioned,

### Logs

<details open>
<summary>Logs</summary>

```console

PS C:\Users\dell> flutter -v                                                                                            
Error: Unable to find git in your PATH.                                                                  

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@AdreshSingh 
Can you check if while installing repo, it is marked as unsafe ? If so, you may be hitting https://github.com/flutter/flutter/issues/123161

**Comment by AdreshSingh** [comment]
No sir, i tried by copying a running flutter but it still crashing and also fired git's safe directory command

**Comment by huycozy** [comment]
>also fired git's safe directory command

@AdreshSingh Can you share the command you tried? Is it like this? (see [this](https://stackoverflow.com/a/75511498/5921933))

```
git config --global --add safe.directory C:/tools/flutter-base-dir
```

**Comment by AdreshSingh** [comment]
Sir, the problem resolved as it was not problem from flutter repo or installation of flutter procedure.

**what i tried:**

1. I tried by completely copying working directory of flutter from another computer to mine, but failed it's same error.
2. After that I again completely removed flutter directory as well as Git installation.
3. After searching more, found choco installation method and also git installation to install flutter , but sadly failed,
4. Then after i finally used most common & safest method i,e, VS code flutter installation, that's where i found proper error message which error in Git user config itself, in my case, 
the error was noted : **fatal error bad boolean**
the line
**autocrlf="*"**
i simply removed this line, now ERROR solved.

Happy Coding.😊

**Comment by darshankawar** [comment]
Closing as resolved.
