### ISSUE TITLE
The logs uploader module is not enable for the `flutter_drone` recipe

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#152775]
@jason-simmons:

> The recipe library that uploads logs set both `FLUTTER_LOGS_DIR` and `FLUTTER_TEST_OUTPUTS_DIR` to the same path
(see https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/logs_util/api.py#27)
>
> So tools should be able to use either one.  (I don't know why both of these variables exist given that they appear to be  identical)
>
> AFAICT the `flutter_drone` recipe used to run the test linked above is not using the log upload library.  The recipe itself would need to be modified in order to get that functionality.

That's unfortunate, as `flutter_drone` is [used over 100+ times](https://github.com/flutter/flutter/blob/master/.ci.yaml).

**Comment by christopherfujino** [comment]
> That's unfortunate, as `flutter_drone` is [used over 100+ times](https://github.com/flutter/flutter/blob/master/.ci.yaml).

I would happily review a recipes CL for this. See go/flutter-luci-recipes for the documentation on how to contribute to the recipes.

**Comment by matanlurey** [comment]
> > That's unfortunate, as `flutter_drone` is [used over 100+ times](https://github.com/flutter/flutter/blob/master/.ci.yaml).
> 
> I would happily review a recipes CL for this. See go/flutter-luci-recipes for the documentation on how to contribute to the recipes.

🫡 . I'll put this on my background list of tasks for next week.

**Comment by matanlurey** [comment]
Appears to have stuck this time as https://flutter-review.googlesource.com/c/recipes/+/59349.
