### ISSUE TITLE
Disconnect MotoG4 devices from all linux hosts

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#152774]
The MotoG4 devices attached to the following hosts can be disconnected. They can be replaced with the mokey devices.

flutter-devicelab-linux-2
flutter-devicelab-linux-14
flutter-devicelab-linux-15
flutter-devicelab-linux-21
flutter-devicelab-linux-22
flutter-devicelab-linux-23
flutter-devicelab-linux-24
flutter-devicelab-linux-25

If there are MotoG4s connected to linux hosts not listed above, then they can also be removed.

**Comment by kentnguyen99** [comment]
Replacing old Moto G4 phones with new Mokey phones are done, all new phone devices are online and ready for services.

**Comment by zanderso** [comment]
Part of https://github.com/flutter/flutter/issues/148085. This is done.
