### ISSUE TITLE
Issue from website page Get Started: Install on macOS

### ISSUE THREAD

**Issue by mgrider** [flutter/flutter#15275]
## Documentation is unreadable in iOS safari

See attached screenshot. 
![23fdb387-699c-472d-b903-6cbe9720d87a](https://user-images.githubusercontent.com/604867/37129496-dab4697a-2244-11e8-9fd2-195c2f1e0083.png)

From URL: https://flutter.io/get-started/setup_macos.md

**Comment by Hixie** [comment]
Fixed!
