### ISSUE TITLE
Cannot call http get throw exception in android 23 x86

### ISSUE THREAD

**Issue by 54lazycat** [flutter/flutter#15276]
## Steps to Reproduce
I am invoke follower function.in iOS is work fun.But in android 23 x86 monitor throw an exception.
```
get() async {
    var httpClient = new HttpClient();
    var request = await httpClient.getUrl(new Uri.http('127.0.0.1:5000', '/ysf'));
    var response = await request.close();
    var responseBody = await response.transform(UTF8.decoder).join();
    Map data = JSON.decode(responseBody);
    debugPrint(data.toString());
  }
```

## Logs

SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 36323

**Comment by jaumard** [comment]
With last version I have the same: 

```
05-16 12:08:32.861 2073-2584/? D/SntpClient: request time failed: java.net.SocketTimeoutException: Receive timed out
05-16 12:08:33.350 6830-7373/? I/flutter: Error SocketException: OS Error: Connection refused, errno = 111, address = jsonplaceholder.typicode.com, port = 44982
```
And it's not for localhost URL, just a regular one that is working when used under the browser.

**Comment by zoechi** [comment]
Why do you expect that to work?
What app is listening on `:5000`?
https://stackoverflow.com/questions/49855754/unable-to-make-calls-to-localhost-using-flutter-random-port-being-assigned-to-h might be related.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
