### ISSUE TITLE
Request framework to access dart https key chain manager in Android or iOS native language 

### ISSUE THREAD

**Issue by yjiang-c** [flutter/flutter#152781]
### Use case

Flutter is based on dart, which has it own https key chain manager SecurityContext. Through SecurityContext, developers could customize different https options like trust CA, client certificate etc. but lots of flutter packages do not use SecurityContext. For example video_player package uses platform native key chain manager and there is no way customize https options. For example, it is impossible to set trust CA for self signed server certificate or add client certificate. Flutter packages should use SecurityContext for any https connection 

### Proposal

It is better to provide framework to let flutter packages access SecurityContext key chain manager on Android and iOS programming languages. For an example, a SecurityContext delivered to flutter package in dart can be accessed in native Android or iOS programming languages. In this way, flutter plugin developers can use consistent https key chain manager in dart.

**Comment by a-siva** [comment]
@goderbauer not sure what is expected from the Dart team here as the Security context is available to Flutter packages, the issue here seems to be how to make that available to the plugin code.

**Comment by yjiang-c** [comment]
Yes, I think so. As I know, SecurityContext is implemented by C++ through OpenSSL APIs. There is no way for Flutter plugins implemented in platform native languages to access SecurityContext implementation.

**Comment by stuartmorgan** [comment]
Could you provide more detail about what exactly you are trying to accomplish? Is the goal for application developers to be able to mirror `SecurityContext` information into native network stacks, so that plugins that use native networking will use the same configuration?

> Is it possible to provide APIs in android or iOS native packages?

An example of what the API you are looking for and how you might use it (even if pseudo-code) would be helpful in understanding the exact request.

**Comment by yjiang-c** [comment]
As I understand, SecurityContext is used only by Dart http client. I am not sure whether there is way for platform native http client to use SecurityContext even if we provide platform native implementation of SecurityContext. For example, on Android, lots of plugins use OKHttp, which can use either Android native key chain manger or require raw certificate or private key bytes.  Providing implementation of SecurityContext seems useless. 

The perfect solution is to provide dart http client and SecurityContext implementation in platform native stack, which are mapped to Dart layer instances. In plugins implementation, it can pass instances of http client and SecurityContext to platform native stack for http/https connection.

Currently, lots of plugins passes URL to native stack and then uses OKHttp for http connection. SecurityContext is total ignored. Maybe we can let plugins pass dart http client (which has been initialised with URL and SecurityContext) to native stack to achieve the same http client in native stack as in Dart layer.

**Comment by stuartmorgan** [comment]
That's still a high-level enough description that I'm still not sure, concretely, what the proposal is here. What does this:
> it can pass instances of http client and SecurityContext to platform native stack for http/https connection.

mean in practice? Could you provide a specific, concrete use case, and what the API you are proposing would look like and how it would be used to achieve it?

> Maybe we can let plugins pass dart http client (which has been initialised with URL and SecurityContext) to native stack to achieve the same http client in native stack as in Dart layer.

Same here. What is a concrete example of what what you would pass and an API you would use it with?
