### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by MIT2010** [flutter/flutter#152726]
## Command
```
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9101/ --target D:\Flutter Mobile Project\digister\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[✓] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.22.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (2 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\FX505G\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\FX505G\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\FX505G\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34221.43
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.91.1)
    • VS Code at C:\Users\FX505G\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • 23049PCD8G (mobile)        • fed1063f      • android-arm64  • Android 14 (API 34)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 127.0.6533.89
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 124.0.2478.80

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.12+10002
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: efbf63d9c66b9f6ec30e9ad4611189aa80003d31
### Plugins
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_core-3.3.0
firebase_core_web-2.17.4
firebase_messaging-15.0.4
firebase_messaging_web-3.8.12
flutter_local_notifications-17.2.1+2
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.21
flutter_vlc_player-7.4.2
geocoding-3.0.0
geocoding_android-3.3.1
geocoding_ios-3.0.1
geolocator-12.0.0
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.0.0
geolocator_windows-0.2.3
image_picker-1.1.2
image_picker_android-0.8.12+10
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-8.0.1
path_provider-2.1.4
path_provider_android-2.2.9
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
url_launcher-6.3.0
url_launcher_android-6.3.8
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.2
url_launcher_windows-3.1.2

**Comment by mansourzaki** [comment]
Hi @MIT2010

The Exception logs and steps to reproduce are empty can you please recheck that for a better understanding of the issue

**Comment by MIT2010** [comment]
Hi @mansourzaki, sorry I don't actually know what the problem is. I tried to run the app from an android simulator and this error suddenly appear. I never use simulator for developing a flutter app before, but now it works totally fine. Guess this is a case close. Thank you.
