### ISSUE TITLE
[shared_preferences] add option to SharedPreferencesWithCache to cache only some keys in-memory and store all keys in local and in memory cache use for only some determinate keys.

### ISSUE THREAD

**Issue by Mohammadfazel03** [flutter/flutter#152737]
### Use case

i use SharedPreferences to save my data and my access token. i want a feature to determinate only access token be cached in memory (becuase in any request dont hit local storage) and the other keys save in local storage and dont cache because some of them is useless and heavy.

### Proposal

change  allowList parameter in SharedPreferencesWithCacheOptions, if we set allowList, only that keys cached in memory. and also change  _isValidKey function, if the key is not in allowList dont raise exception and hit the local storage and set or get data from storage and if key exist in allowList return data from memory cache.

**Comment by stuartmorgan** [comment]
The purpose of the cache is to allow the `get*` calls to be synchronous; any values that aren't cached in Dart require async access, and thus the API surface of `SharedPreferencesWithCache` isn't suitable for accessing them.

If you have some values that you don't want cached, you would need to use an instance of `SharedPreferencesAsync` for those.

Closing as infeasible.
