### ISSUE TITLE
Codelab on how to set up CI/CD using GitHub Actions, without using fastlane.

### ISSUE THREAD

**Issue by mafreud** [flutter/flutter#152740]
### Use case

Currently, there is no documentation for GitHub Actions without using fastlane in the CI/CD documentation. Since not everyone is using fastlane, how about explaining how to set up CI/CD with GitHub Actions without fastlane?

Also, it might be a good idea to compile this method into a Codelab, and then reference that link from the Flutter docs. I'd like to hear your opinions on this.

### Proposal

- write docs about how to setup CI/CD with GitHub Actions
- write codelab about how to setup CI/CD with GitHub Actions

**Comment by kjxbyz** [comment]
I'm glad this was helpful to you. 👉 https://github.com/flutter/flutter/issues/148669#issuecomment-2120730106

**Comment by darshankawar** [comment]
Thanks for the report @mafreud 


> * write docs about how to setup CI/CD with GitHub Actions

Assuming this is without using fastlane, it would need to be reported in flutter website repo https://github.com/flutter/website/issues



> * write codelab about how to setup CI/CD with GitHub Actions

This can live in this repo. I will update the issue title to depict same.

**Comment by domesticmouse** [comment]
Reviewed, not a priority.
