### ISSUE TITLE
IDE Functionality: Remove Widget also in list Widgets

### ISSUE THREAD

**Issue by JulianHock** [flutter/flutter#152760]
### Use case

Sometimes I want to remove a Widget from a list like in a Column or Row. I have to delete it manually, which is quite complicated if it´s a bigger one and wastes time. 

### Proposal

In single nested Widgets I have the possibility to use the suggestions to delete this Widget like when you have a Container in a Container. I would love to have this feature also for deleting single Widgets in list Widgets like Column or Row.
<img width="266" alt="image" src="https://github.com/user-attachments/assets/c7b54138-ebb2-4d56-9e3c-d303f63b1811">
<img width="248" alt="image" src="https://github.com/user-attachments/assets/387567ec-3fa8-4e49-9065-87fe3338862e">

**Comment by darshankawar** [comment]
@JulianHock 
Depending on which IDE you are using, you will need to report this in dedicated repo:

Flutter intellij: https://github.com/flutter/flutter-intellij/issues
vscode : https://github.com/Dart-Code/Dart-Code/issues

Closing from here.
