### ISSUE TITLE
[macOS 15 beta] Multiple dart exec windows popup when running a dart command and more when running flutter app

### ISSUE THREAD

**Issue by darrcb** [flutter/flutter#152723]
### Steps to reproduce

Execute a dart command or run a flutter app

### Expected results

No dart exec windows popup

### Actual results

Dart exec windows popup on my dock when running dart command and flutter app
![CleanShot 2024-08-02 at 09 29 52@2x](https://github.com/user-attachments/assets/efe63ea9-e74e-48d3-b1d6-d8bd10a2c6e7)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![CleanShot 2024-08-02 at 09 31 37](https://github.com/user-attachments/assets/aa7a8d5d-fbee-4cb5-8882-15abd836765e)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 15.0 24A5298h darwin-arm64, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Darrell’s iPad. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @darrcb, are you executing flutter commands from the default Terminal on macOS? If so, can you share the configuration on this screen? (Go to `Terminal` > `Settings...` > `Profiles` > `Shell`)

<img width="600" src="https://github.com/user-attachments/assets/572dc3f8-6b58-48f5-8b14-fa1046ca3bc5">

Also, does this occur on non-Flutter commands?

**Comment by darrcb** [comment]
Hi @huycozy, it is not limited to dart/flutter commands executed from the terminal. Whenever I run a Flutter app from VSCode, multiple dart exec windows appear.

Here is the configuration for my terminal.
![CleanShot 2024-08-02 at 19 05 04@2x](https://github.com/user-attachments/assets/044101ad-c595-4449-8fd9-b6d0d9e95ce5)


Additionally, when I right-click on the exec window, the menu looks like this.
![CleanShot 2024-08-02 at 19 06 20@2x](https://github.com/user-attachments/assets/b36ec242-b7cd-4374-9bf1-a596b5ae9fe0)

**Comment by huycozy** [comment]
Looks like you are on [macOS 15 beta 4 (24A5298h)](https://developer.apple.com/news/releases/?id=07232024j). I don't have such a version to test right now. The issue doesn't happen on my machine with `macOS 14.6`. 

Did the issue occur before you upgraded to this macOS version? (to confirm if this is an OS-specific issue or not)

**Comment by huycozy** [comment]
This seems to happen on `macOS 15.1 24B5009l` after user updated to macOS15 beta (https://github.com/flutter/flutter/issues/152853). Labeling this for team's attention.

**Comment by darrcb** [comment]
Yes @huycozy, I am currently on a beta of MacOS - 24B5009l. I did not experience this prior to the update.

**Comment by darrcb** [comment]
Yes @huycozy, I am currently on a beta of MacOS - 24B5009l. I did not experience this prior to the update.

**Comment by jmagman** [comment]
@cbracken mentioned "it might be that we should be adding an Info.plist with LSBackgroundOnly set to 1"

**Comment by christopherfujino** [comment]
> @cbracken mentioned "it might be that we should be adding an Info.plist with [LSBackgroundOnly](https://developer.apple.com/documentation/bundleresources/information_property_list/lsbackgroundonly) set to 1"

Add an Info.plist to what "app"? The tool?

**Comment by jmagman** [comment]
> Add an Info.plist to what "app"? The tool?

I'm guessing an Info.plist embedded in the dart and dartaotruntime etc executable.  However it was a stray comment, he didn't confirm this would fix the issue.

cc @aam is there already a dart issue tracking this?

**Comment by aam** [comment]
@jmagman  wrote

> cc @aam is there already a dart issue tracking this?

I don't think so.

**Comment by jmagman** [comment]
> Not sure how easy is to get beta on corp mac.

It's possible, I don't recommend it though for obvious reasons.  I suggest whoever is investigating it to expense a non-corp Mac.  Feel free to DM me for details about that.

**Comment by aam** [comment]
Looks like dart's process name setting logic has this strange side effect starting with mac os 15.
https://dart-review.googlesource.com/c/sdk/+/379142 with the fix for now.

cc @rmacnak-google

**Comment by cbracken** [comment]
Latest Sequoia beta was released yesterday (developer)/today (public). I'll update and see if I still see this. If it's still appearing though, we should probably file a Radar to at least see if this is expected.

**Comment by cbracken** [comment]
As of Sequoia public beta 3 (24A5309e), I am no longer seeing this behaviour.

**Comment by jmagman** [comment]
> As of macOS 15 (Sequoia) public beta 3 (24A5309e), I am no longer seeing this behaviour.

You mean this should be closed because it's not happening on beta 3? Or it's not happening on top of https://dart-review.googlesource.com/c/sdk/+/379142 ?

**Comment by cbracken** [comment]
> You mean this should be closed because it's not happening on beta 3? Or it's not happening on top of https://dart-review.googlesource.com/c/sdk/+/379142 ?

The former. This is no longer happening at tip-of-tree with no patches applied.

Probably safe to close, though based on our experience with text field clipping last year, you never know if it'll need to be re-opened in a couple weeks when the next beta rolls out 😉.

**Comment by darrcb** [comment]
There are currently no updates for Mac OS 15.1 beta. But yeah, will probably go away [or not] when the next beta comes out. 😄

**Comment by cbracken** [comment]
Let us know if you still see it on the next 15.1 beta. I've kept my machine on the 15.0 public beta track for now. Since it's my primary personal machine I'm not sure I'm daring enough to switch it over to developer betas. 😅

**Comment by christopherfujino** [comment]
> > You mean this should be closed because it's not happening on beta 3? Or it's not happening on top of https://dart-review.googlesource.com/c/sdk/+/379142 ?
> 
> The former. This is no longer happening at tip-of-tree with no patches applied.
> 
> Probably safe to close, though based on our experience with text field clipping last year, you never know if it'll need to be re-opened in a couple weeks when the next beta rolls out 😉.

Since https://dart-review.googlesource.com/c/sdk/+/379142 landed, are you sure it hadn't rolled to the framework commit you tried it on?

**Comment by jmagman** [comment]
It's also being reverted: https://dart-review.googlesource.com/c/sdk/+/379340

**Comment by christopherfujino** [comment]
> It's also being reverted: https://dart-review.googlesource.com/c/sdk/+/379340

I know, I just wanted to verify that the reason this no longer appears on tip of tree is because the regression is not present in beta 3, rather than because that tip of tree commit happened to have had Alex's fix rolled in, and once the revert rolls this will have regressed again.

**Comment by darrcb** [comment]
**UPDATE**: Updated to MacOS 15.1 Beta 2. The issue seems to be fixed now. No exec windows pop up when running flutter or dart. 👍🏽
![CleanShot 2024-08-13 at 08 00 57@2x](https://github.com/user-attachments/assets/1edb3003-40ed-4bf8-9a99-a09f1108325c)

![CleanShot 2024-08-13 at 07 58 16@2x](https://github.com/user-attachments/assets/4987ff20-76ac-464d-ab92-652852834d74)
