### ISSUE TITLE
Flutter native driver Android test has at least 1 flake related to VM service (?)

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#152769]
See [test log](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android_emu%20flutter_driver_android_test/26/overview), but tl;dr:

```txt
00:00 [32m+0[0m: (setUpAll)[0m
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:46399/ymJxvA92rfE=/
VMServiceFlutterDriver: Isolate found with number: 7208191671426927
00:00 [32m+0[0m[31m -1[0m: (setUpAll) [1m[31m[E][0m[0m
  getIsolate: (-32000) Service connection disposed

00:00 [32m+0[0m[31m -1[0m: (tearDownAll)[0m
00:00 [32m+0[0m[31m -2[0m: (tearDownAll) [1m[31m[E][0m[0m
  LateInitializationError: Local 'nativeDriver' has not been initialized.
  dart:_internal              LateError._throwLocalNotInitialized
  test_driver/main_test.dart  _main.<fn>

00:00 [32m+0[0m[31m -2[0m: [31mSome tests failed.[0m

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
```

This test is super simple:
```dart
Future<void> _main() async {
  // To generate golden files locally, uncomment the following line.
  // autoUpdateGoldenFiles = true;

  late FlutterDriver flutterDriver;
  late NativeDriver nativeDriver;

  setUpAll(() async {
    flutterDriver = await FlutterDriver.connect();
    nativeDriver = await AndroidNativeDriver.connect();
  });

  tearDownAll(() async {
    await nativeDriver.close();
    await flutterDriver.close();
  });

  test('should screenshot and match a full-screen blue rectangle', () async {
    await flutterDriver.waitFor(find.byType('DecoratedBox'));
    await expectLater(
      nativeDriver.screenshot(),
      matchesGoldenFile('android_driver_test.BlueRectangle.png'),
    );
  }, timeout: Timeout.none);
}
```

I am investigating if exceptions are being swallowed.

**Comment by matanlurey** [comment]
No, if the health check fails, the failure looks like this:
```txt
00:00 +0 -1: (setUpAll) [E]
  DriverError: Flutter application health check failed.

  package:flutter_driver/src/driver/vmservice_driver.dart 253:7  VMServiceFlutterDriver.connect
  ===== asynchronous gap ===========================
  test_driver/main_test.dart 27:21 
```

**Comment by matanlurey** [comment]
**Update**: I looked at this for a couple of hours with @jonahwilliams and I have made no real progress, other than it appears the emulator periodically crashes after application startup. I can only reproduce this on CI, and not consistently (for example, https://github.com/flutter/flutter/pull/153207 is a patch that runs the test 20 times on presubmit, and can *usually* fail at least once).

Next step is I might need to port over the native crash logic from `scenario_app`, i.e.:

```dart
await step('Symbolize stack traces', () async {
  final ProcessResult result = await pm.run(
    <String>[
      ndkStack,
      '-sym',
      outDir.path,
      '-dump',
      logcatPath,
    ],
  );
  if (result.exitCode != 0) {
    panic(<String>['Failed to symbolize stack traces']);
  }
});
```

Barring that, we might need to accept that, just like every other emulator test (it's _not_ unique to this test, for example [see this `android_views` failure](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android_emu%20android%20views/2826/overview)), we will randomly crash some percentage of the time. I am running out of tools - maybe I could SSH into a machine and run the tests locally?

/cc @johnmccutchan for visibility
/cc @zanderso or @jason-simmons in case there are any other Android emulator debugging ideas.

**Comment by johnmccutchan** [comment]
Some questions:

1. Who internally can we talk about emulator crashes? We need to be able to root cause this issue and there must be people who can help.
2. Does google3 experience this crash rate? how do they handle it?
3. Could this be something like an OOM killer kicking in on CI?

**Comment by matanlurey** [comment]
Thanks @johnmccutchan! Replies inline.

> Some questions:
> 
> 1. Who internally can we talk about emulator crashes? We need to be able to root cause this issue and there must be people who can help.

+1. I want to at least get the [native stack dump](https://github.com/flutter/flutter/pull/153207) before going that route.

> 2. Does google3 experience this crash rate? how do they handle it?

I am not aware this happens, or if it does, I'm not sure it does.

I can't even reproduce it locally (running on a loop).

> 3. Could this be something like an OOM killer kicking in on CI?

@jonahwilliams's theory was an OOM actually, maybe the native stack will show that?

---

@zanderso is [looking into a workaround here](https://github.com/flutter/flutter/pull/153190), as apparently this is impacting @camsim99's work as well.

**Comment by zanderso** [comment]
These are running on `n1-standard-8` instances, which have 30GB of memory according to https://cloud.google.com/compute/docs/general-purpose-machines#n1_machine_types, so that should be plenty? What's the footprint of the emulator running locally?

**Comment by zanderso** [comment]
I might have misunderstood (3). Is the suggestion that the memory size specified for the emulated device is too small? If we determine somewhat conclusively that it is too small, we could figure out how to make it bigger. Right now, it looks like the emulator is configured to have 2GB. `meminfo` dump is at the bottom of:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8739753058565394657/+/u/start_avd/avd_setup/avd_setup.sh/stdout

**Comment by matanlurey** [comment]
> I might have misunderstood (3). Is the suggestion that the memory size specified for the emulated device is too small? If we determine that it is too small, we could figure out how to make it bigger. Right now, it looks like the emulator is configured to have 2GB. `meminfo` dump is at the bottom of:
> 
> https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8739753058565394657/+/u/start_avd/avd_setup/avd_setup.sh/stdout

We don't have any evidence of that (yet).

I am going to try adding usage of [`ndk-stack`](https://developer.android.com/ndk/guides/ndk-stack) on CI to see if it pulls up anything interesting.

**Comment by matanlurey** [comment]
A few ideas to try after lunch: `Storing crashdata in: /tmp/android-unknown/emu-crash-34.2.14.db`

**Comment by matanlurey** [comment]
Looks reasonably stable: 
![image](https://github.com/user-attachments/assets/427720f2-e575-4fec-a6f1-56e6297f7c17)

The one crash appears to be a Gradle failure/flake:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android_emu_34%20flutter_driver_android_test/99/overview
