### ISSUE TITLE
[tool] Generated `.gitignore` for template `package` should include `.flutter-plugins` files

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#152793]
Adding a flutter plugin as a dependency to a package generates these files. The non-package template `.gitignore` contains these.

**Comment by Rexios80** [comment]
Is a package not supposed to depend on plugins? Does depending on plugins make a package a plugin as well?

**Comment by andrewkolos** [comment]
> Is a package not supposed to depend on plugins? Does depending on plugins make a package a plugin as well?

cc @stuartmorgan, who I believe knows more about plugins than me

**Comment by stuartmorgan** [comment]
It looks like it was removed from both in https://github.com/flutter/flutter/pull/88991#discussion_r697577690 based on my question there; I thought this file was app-level only. If it's made in the top-level folder as well that part of the change was wrong, and it should just be re-added.
