### ISSUE TITLE
ListTile Leading Height Constraint Issue

### ISSUE THREAD

**Issue by ilap** [flutter/flutter#152757]
The current implementation of the `ListTile` in Flutter constrains the height of the `leading` widget to a maximum of 56px. 
This constraint does not align with the Material Design spec and guidelines, which permit a height of up to 64px for video and for image thumbnails.

- Current implementation of the `ListTile` leading height constraint can be found [here](https://github.com/flutter/flutter/blob/40e3f78a0b824e19adba73d7a58ffa33b46df0cf/packages/flutter/lib/src/material/list_tile.dart#L1344).
- Material Design guidelines for list components can be found [here](https://m3.material.io/components/lists/specs#888e18b6-581d-43a5-a878-1920a136358a).

**Comment by darshankawar** [comment]
This looks similar to https://github.com/flutter/flutter/issues/98178 for which you can follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
