### ISSUE TITLE
Assertion child!.hasSize is not true

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#152835]
### Steps to reproduce

This is the code causing the issue:

The error is thrown when I call _showConfirmDeleteDialog, which had been working before I refactoed the PhotoCrud into its own widget.

I've created a branch with the code at the point in time that caused this issue.

https://github.com/bsutton/hmb/tree/flutter-framework-bug

This is way too deep in my code base to extract a small demonstration particularly when the dialog was previously working.

task/photo_crud.dart

```
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:future_builder_ex/future_builder_ex.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import 'package:june/june.dart';
import 'package:path_provider/path_provider.dart';

import '../../dao/dao_photo.dart';
import '../../dao/dao_task.dart';
import '../../entity/photo.dart';
import '../../entity/task.dart';
import '../../widgets/photo_gallery.dart';

class PhotoCrud extends StatefulWidget {
  const PhotoCrud({required this.controller, super.key});

  final PhotoController controller;

  @override
  State<PhotoCrud> createState() => _PhotoCrudState();
}

class _PhotoCrudState extends State<PhotoCrud> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    if (widget.controller._task == null) {
      return const Center(child: Text('To Add a Photo - Save the Task First'));
    }
    // Display photos and allow adding comments and deletion
    else {
      return JuneBuilder(PhotoLoader.new,
          builder: (context) => FutureBuilderEx(
              // ignore: discarded_futures
              future: widget.controller.photos,
              builder: (context, photos) => Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      _buildAddButton(widget.controller._task, photos),
                      _buildPhotoCRUD(photos),
                    ],
                  )));
    }
  }

  /// Build the take photo button
  Widget _buildAddButton(Task? task, List<Photo>? photos) => IconButton(
        icon: const Icon(Icons.camera_alt),
        onPressed: () async {
          final photoFile = await takePhoto();
          if (photoFile != null) {
            // Insert the photo metadata into the database
            final newPhoto = Photo.forInsert(
              taskId: task!.id,
              filePath: photoFile.path,
              comment: '',
            );
            await widget.controller.addPhoto(newPhoto);
          }
        },
      );

  /// Build the photo CRUD
  Widget _buildPhotoCRUD(List<Photo>? photos) => Column(
        mainAxisSize: MainAxisSize.min,
        children: photos!
            .map((photo) => Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    _showPhoto(photo),
                    _buildCommentField(photo),
                    _buildDeleteButton(photo),
                  ],
                ))
            .toList(),
      );

  /// Display the photo with a 'Icon in the corner
  /// which when tapped will show the full screen photo
  /// with zoom/pan ability.
  Stack _showPhoto(Photo photo) => Stack(
        children: [
          Image.file(File(photo.filePath)),
          Positioned(
            right: 0,
            child: GestureDetector(
              // Show full screen photo when tapped
              onTap: () async {
                final task = await DaoTask().getById(photo.taskId);
                if (mounted) {
                  await _showFullScreenPhoto(
                      context, photo.filePath, task!.name, photo.comment);
                }
              },
              child: Container(
                color: Colors.black.withOpacity(0.5),
                padding: const EdgeInsets.all(8),
                child: const Icon(
                  Icons.fullscreen,
                  color: Colors.white,
                ),
              ),
            ),
          ),
        ],
      );

  IconButton _buildDeleteButton(Photo photo) => IconButton(
        icon: const Icon(Icons.delete),
        onPressed: () async {
          await _showConfirmDeleteDialog(context, photo);
          PhotoGallery.notify();
        },
      );

  Widget _buildCommentField(Photo photo) {
    final commentControlller = widget.controller.commentController(photo);
    return TextField(
      controller: commentControlller,
      decoration: const InputDecoration(labelText: 'Comment'),
      maxLines: null, // Allows the field to grow as needed
      onChanged: (value) {
        // Update comment immediately when text changes
        photo.comment = value;
      },
    );
  }

  Future<void> _showConfirmDeleteDialog(
          BuildContext context, Photo photo) async =>
      showDialog<void>(
        context: context,
        builder: (context) => AlertDialog(
          title: const Text('Delete Photo'),
          content: const ListBody(
            children: <Widget>[
              // Image.file(File(photo.filePath),
              //     width: 100, height: 100), // Thumbnail of the photo
              // if (photo.comment.isNotEmpty) Text(photo.comment),
              // const SizedBox(height: 10),
              Text('Are you sure you want to delete this photo?'),
            ],
          ),
          actions: <Widget>[
            TextButton(
              child: const Text('Cancel'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
            TextButton(
              child: const Text('Delete'),
              onPressed: () async {
                await widget.controller.deletePhoto(photo);
                if (context.mounted) {
                  Navigator.of(context).pop();
                }
              },
            ),
          ],
        ),
      );

  Future<void> _showFullScreenPhoto(BuildContext context, String imagePath,
      String taskName, String comment) async {
    await context.push('/photo_viewer', extra: {
      'imagePath': imagePath,
      'taskName': taskName,
      'comment': comment,
    });
  }

  Future<File?> takePhoto() async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: ImageSource.camera);
    if (pickedFile == null) {
      return null;
    }

    final appDir = await getApplicationDocumentsDirectory();
    final fileName = pickedFile.path.split('/').last;
    final savedImage =
        await File(pickedFile.path).copy('${appDir.path}/$fileName');

    return savedImage;
  }
}

class PhotoLoader extends JuneState {}

class PhotoController {
  PhotoController({required Task? task}) : _task = task {
    unawaited(_loadPhotos());
  }

  Task? _task;
  final List<Photo> _photos = [];

  Task? get task => _task;

  set task(Task? task) {
    _task = task;
    June.getState(PhotoLoader.new).setState();
  }

  Future<List<Photo>> get photos async {
    await _completer.future;
    return _photos;
  }

  final Completer<void> _completer = Completer<void>();

  // List to hold comment controllers for each photo
  final List<TextEditingController> _commentControllers = [];

  Future<void> _loadPhotos() async {
    if (_task == null) {
      _completer.complete();
      return;
    }
    _photos.addAll(await DaoPhoto().getByTask(_task!.id));

    // Initialize comment controllers if not already initialized
    if (_commentControllers.isEmpty) {
      for (final photo in _photos) {
        final controller = TextEditingController(text: photo.comment);

        _commentControllers.add(controller);
      }
    }
    _completer.complete();
  }

  /// Save comments explicitly when saving the task
  Future<void> save() async {
    await _completer.future;
    for (var i = 0; i < _commentControllers.length; i++) {
      final photo = _photos[i]..comment = _commentControllers[i].text;
      await DaoPhoto().update(photo);
    }
    PhotoGallery.notify();
  }

  void dispose() {
    for (final controller in _commentControllers) {
      controller.dispose();
    }
  }

  TextEditingController commentController(Photo photo) =>
      _commentControllers[_photos.indexOf(photo)];

  Future<void> addPhoto(Photo newPhoto) async {
    await DaoPhoto().insert(newPhoto);

    _photos.add(newPhoto);
    _commentControllers.add(TextEditingController());
    _refresh();
  }

  Future<void> deletePhoto(Photo photo) async {
    // Delete the photo from the database and the disk
    await DaoPhoto().delete(photo.id);
    await File(photo.filePath).delete();

    _refresh();
  }

  void _refresh() {
    June.getState(PhotoLoader.new).setState();
    PhotoGallery.notify();
  }
}
```

### Expected results

The delete confirm dialog should be displayed.

### Actual results

Reloaded 7 of 5106 libraries in 993ms.
E/OpenGLRenderer( 6415): Unable to match the desired swap behavior.
D/TrafficStats( 6415): tagSocket(130) with statsTag=0xffffffff, statsUid=-1

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderListBody#6b706 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    AlertDialog AlertDialog:file:///home/bsutton/git/hmb/lib/crud/task/photo_crud.dart:140:31

When the exception was thrown, this was the stack:
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2165:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:65)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#5      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#7      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#8      RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:847:45)
#9      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:885:32)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#11     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#12     RenderIntrinsicWidth._computeSize (package:flutter/src/rendering/proxy_box.dart:712:25)
#13     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:729:12)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#20     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#23     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#25     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:280:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#27     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:456:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#29     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#31     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#33     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#48     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3712:13)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#52     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:974:13)
#53     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1288:9)
#54     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416:7)
#55     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
#56     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
#57     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:23)
#58     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138:13)
#59     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#60     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#61     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#62     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#63     _invoke (dart:ui/hooks.dart:312:13)
#64     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#65     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)

The following RenderObject was being processed when the exception was fired: RenderSemanticsAnnotations#f1e7c relayoutBoundary=up9 NEEDS-PAINT
    parentData: offset=Offset(19.2, 16.0) (can use size)
    constraints: BoxConstraints(w=274.3, 0.0<=h<=557.3)
    semantic boundary
    size: MISSING
    child: RenderListBody#6b706 relayoutBoundary=up10 NEEDS-PAINT
        parentData: <none> (can use size)
        constraints: BoxConstraints(w=274.3, 0.0<=h<=557.3)
        size: MISSING
        axisDirection: down
        child 1: RenderSemanticsAnnotations#8990d NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0)
            constraints: MISSING
            size: MISSING
            child: RenderImage#e2e2b NEEDS-LAYOUT NEEDS-PAINT
                parentData: <none>
                constraints: MISSING
                size: MISSING
                image: [3024×4032]
                width: 100.0
                height: 100.0
                alignment: Alignment.center
                invertColors: false
                filterQuality: low
        child 2: RenderParagraph#28426 NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0)
            constraints: MISSING
            size: MISSING
            textAlign: start
            textDirection: ltr
            softWrap: wrapping at box width
            overflow: clip
            textScaler: linear (1.3x)
            locale: en_US
            maxLines: unlimited
            text: TextSpan
                debugLabel: (englishLike bodyMedium 2021).merge((blackMountainView bodyMedium).apply)
                inherit: false
                color: Color(0xff1d1b20)
                family: Roboto
                size: 14.0
                weight: 400
                letterSpacing: 0.3
                baseline: alphabetic
                height: 1.4x
                leadingDistribution: even
                decoration: Color(0xff1d1b20) TextDecoration.none
                "tissues"
        child 3: RenderConstrainedBox#72fb3 NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0)
            constraints: MISSING
            size: MISSING
            additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=10.0)
        child 4: RenderParagraph#f47eb NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0)
            constraints: MISSING
            size: MISSING
            textAlign: start
            textDirection: ltr
            softWrap: wrapping at box width
            overflow: clip
            textScaler: linear (1.3x)
            locale: en_US
            maxLines: unlimited
            text: TextSpan
                debugLabel: (englishLike bodyMedium 2021).merge((blackMountainView bodyMedium).apply)
                inherit: false
                color: Color(0xff1d1b20)
                family: Roboto
                size: 14.0
                weight: 400
                letterSpacing: 0.3
                baseline: alphabetic
                height: 1.4x
                leadingDistribution: even
                decoration: Color(0xff1d1b20) TextDecoration.none
                "Are you sure you want to delete this photo?"
RenderObject: RenderSemanticsAnnotations#f1e7c relayoutBoundary=up9 NEEDS-PAINT
    parentData: offset=Offset(19.2, 16.0) (can use size)
    constraints: BoxConstraints(w=274.3, 0.0<=h<=557.3)
    semantic boundary
    size: MISSING
    child: RenderListBody#6b706 relayoutBoundary=up10 NEEDS-PAINT
        parentData: <none> (can use size)
        constraints: BoxConstraints(w=274.3, 0.0<=h<=557.3)
        size: MISSING
        axisDirection: down
        child 1: RenderSemanticsAnnotations#8990d NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0)
            constraints: MISSING
            size: MISSING
            child: RenderImage#e2e2b NEEDS-LAYOUT NEEDS-PAINT
                parentData: <none>
                constraints: MISSING
                size: MISSING
                image: [3024×4032]
                width: 100.0
                height: 100.0
                alignment: Alignment.center
                invertColors: false
                filterQuality: low
        child 2: RenderParagraph#28426 NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0)
            constraints: MISSING
            size: MISSING
            textAlign: start
            textDirection: ltr
            softWrap: wrapping at box width
            overflow: clip
            textScaler: linear (1.3x)
            locale: en_US
            maxLines: unlimited
            text: TextSpan
                debugLabel: (englishLike bodyMedium 2021).merge((blackMountainView bodyMedium).apply)
                inherit: false
                color: Color(0xff1d1b20)
                family: Roboto
                size: 14.0
                weight: 400
                letterSpacing: 0.3
                baseline: alphabetic
                height: 1.4x
                leadingDistribution: even
                decoration: Color(0xff1d1b20) TextDecoration.none
                "tissues"
        child 3: RenderConstrainedBox#72fb3 NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0)
            constraints: MISSING
            size: MISSING
            additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=10.0)
        child 4: RenderParagraph#f47eb NEEDS-LAYOUT NEEDS-PAINT
            parentData: offset=Offset(0.0, 0.0)
            constraints: MISSING
            size: MISSING
            textAlign: start
            textDirection: ltr
            softWrap: wrapping at box width
            overflow: clip
            textScaler: linear (1.3x)
            locale: en_US
            maxLines: unlimited
            text: TextSpan
                debugLabel: (englishLike bodyMedium 2021).merge((blackMountainView bodyMedium).apply)
                inherit: false
                color: Color(0xff1d1b20)
                family: Roboto
                size: 14.0
                weight: 400
                letterSpacing: 0.3
                baseline: alphabetic
                height: 1.4x
                leadingDistribution: even
                decoration: Color(0xff1d1b20) TextDecoration.none
                "Are you sure you want to delete this photo?"
════════════════════════════════════════════════════════════════════════════════
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderPadding#ac110 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFlex#9cb66 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Updated layout information required for RenderSemanticsAnnotations#8990d NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 3651 pos 12: '!_needsLayout'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderPhysicalShape#f1869 relayoutBoundary=up2
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: _RenderInkFeatures#0f75e relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderListBody must have unlimited space along its main axis.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderCustomPaint#ea34f relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#f1e7c relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#8e348 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 345 pos 12: 'child!.hasSize': is not true.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderIntrinsicWidth#f968d relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderPhysicalShape#f1869 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 6415): tagSocket(119) with statsTag=0xffffffff, statsUid=-1

### Code sample

As above

### Screenshots or Video

The screen goes a little dark as you would expect when you display a modal dialog.

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on Ubuntu 22.04.4 LTS 6.5.0-44-generic, locale en_AU.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ android-studio-dir = /home/bsutton/Android/Sdk
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by SuicaLondon** [comment]
This error was caused by the `ListBody`, It will be expanded natively on the main axis. If you want to render multiple widgets here, please try to write `Row` or `Column` with constraints.

**Comment by bsutton** [comment]
Hadn't even noticed the ListBody - chat gpt generate the code.

Changing to a Column fixed the issue - thanks.
