### ISSUE TITLE
`flutter run` hangs on "Resolving dependencies"

### ISSUE THREAD

**Issue by ameenvga** [flutter/flutter#15289]
## Steps to Reproduce
Created a new flutter project. Then `flutter-run` from the command prompt,.The process hangs on 'Resolving dependencies'..

 `--verbose` log information

`[  +36 ms] [C:\Program Files\Git\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [C:\Program Files\Git\flutter\] git rev-parse --abbrev-ref HEAD
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [C:\Program Files\Git\flutter\] git ls-remote --get-url origin
[  +19 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\Program Files\Git\flutter\] git log -n 1 --pretty=format:%H
[  +18 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3ea4d06340a97a1e9d7cae97567c64e0569dcaa2
[        ] [C:\Program Files\Git\flutter\] git log -n 1 --pretty=format:%ar
[  +19 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[        ] [C:\Program Files\Git\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +18 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.1.5-0-g3ea4d0634
[ +165 ms] C:/Users/Edit/AppData/Local/Android/sdk\platform-tools\adb devices -l
[  +10 ms] Exit code 0 from: C:/Users/Edit/AppData/Local/Android/sdk\platform-tools\adb devices -l
[        ] List of devices attached
           11160ba35ee21603       device product:nobleltejv model:SM_N920C device:noblelte transport_id:2
[ +172 ms] C:/Users/Edit/AppData/Local/Android/sdk\platform-tools\adb -s 11160ba35ee21603 shell getprop
[ +157 ms] ro.hardware = samsungexynos7420
[{"event":"app.start","params":{"appId":"42e08c76-f4a6-4475-816d-77f92fe4a097","deviceId":"11160ba35ee21603","directory":"E:\\MyFolder\\Personal_Projects\\flutter_projects","supportsRestart":true}}]
[ +646 ms] Launching lib\main.dart on SM N920C in debug mode...
Initializing gradle...
[{"event":"app.progress","params":{"appId":"42e08c76-f4a6-4475-816d-77f92fe4a097","id":"0","progressId":null,"message":"Initializing gradle..."}}]
[   +7 ms] Using gradle from E:\MyFolder\Personal_Projects\flutter_projects\android\gradlew.bat.
[  +72 ms] E:\MyFolder\Personal_Projects\flutter_projects\android\gradlew.bat -v
[ +538 ms] 
           ------------------------------------------------------------
           Gradle 4.1
           ------------------------------------------------------------
           
           Build time:   2017-08-07 14:38:48 UTC
           Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2
           
           Groovy:       2.4.11
           Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
           JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
           OS:           Windows 7 6.1 amd64
[{"event":"app.progress","params":{"appId":"42e08c76-f4a6-4475-816d-77f92fe4a097","id":"0","progressId":null,"finished":true}}]
Resolving dependencies...
[{"event":"app.progress","params":{"appId":"42e08c76-f4a6-4475-816d-77f92fe4a097","id":"1","progressId":null,"message":"Resolving dependencies..."}}]
[   +2 ms] [android\] E:\MyFolder\Personal_Projects\flutter_projects\android\gradlew.bat app:properties
`

## Logs

 `flutter run`
Launching lib/main.dart on SM N920C in debug mode
Initializing gradle...
Resolving dependencies...

`flutter analyze`
No issues found!
Ran in 5.3s

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.
`[ΓêÜ] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 6.1.7601], lo
cale en-IN)
    ΓÇó Flutter version 0.1.5 at C:\Program Files\Git\flutter
    ΓÇó Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    ΓÇó Engine revision ead227f118
    ΓÇó Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[ΓêÜ] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ΓÇó Android SDK at C:\Users\Edit\AppData\Local\Android\sdk
    ΓÇó Android NDK location not configured (optional; useful for native profili
ng support)
    ΓÇó Platform android-27, build-tools 27.0.3
    ΓÇó ANDROID_HOME = C:\Users\Edit\AppData\Local\Android\sdk
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b0
1)

[ΓêÜ] Android Studio (version 3.0)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b0
1)

[ΓêÜ] IntelliJ IDEA Community Edition (version 2017.3)
    ΓÇó Flutter plugin version 22.2.2
    ΓÇó Dart plugin version 173.4548.30

[ΓêÜ] Connected devices (1 available)
    ΓÇó SM N920C ΓÇó 11160ba35ee21603 ΓÇó android-arm64 ΓÇó Android 7.0 (API 24)

ΓÇó No issues found!`

Tried different solutions from other github responses.  Spent three days on it. I cannot run the app anyway.

**Comment by decker502** [comment]
I got the same problem. sovled it with:
Replace `classpath 'com.android.tools.build:gradle:2.x.x'` to `classpath 'com.android.tools.build:gradle:3.0.1'` in `$project/android/build.gradle.`

I hope that can help u.

**Comment by ameenvga** [comment]
It is already 3.0.1 in my build.gradle file

**Comment by zdhruvit** [comment]
solved it with:
In `$project$\android\gradle\wrapper\gradle-wrapper.properties`
replace 
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip`
with
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

As 
```
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 4.4. Current version is 4.1. If using the gradle wrapper, try editing the distributionUrl in `D:\AeonCoup\trading\android\gradle\wrapper\gradle-wrapper.properties` to gradle-4.4-all.zip

```

**Comment by ameenvga** [comment]
I have solved it myself. What you have to do is just 'WAIT'. When it says 'Initializing gradle' or 'resolving dependencies'...etc it means that, it is downloading many files from the internet. If you disconnect your internet connection, you can see all those links of files in the error report. So what you need is a better internet connection to download them, otherwise, it will take a long time. Also, you need to accept the android licenses if you haven't accepted them before.

**Comment by zxb5102** [comment]
i find these https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

**Comment by apurvthakkar99** [comment]
When App hangs on this stage it needs to just run APPLICATION_PATH/android/gradlew file. You can know resolving dependency hangs when system tries to download some files or sdk. You can just wait there or download it manually from SDK manager.

**Comment by dzuerst** [comment]
i fix with restart my vsCode
Close VSCode and run it again.
