### ISSUE TITLE
What PATENTS mean?

### ISSUE THREAD

**Issue by erlangp** [flutter/flutter#15285]
What PATENTS mean? link: https://github.com/flutter/flutter/blob/master/PATENTS

**Comment by sillsm** [comment]
Hi erlangp,

It means Google is letting you use any patents it might have related to flutter, when you use flutter.
If you sue us for patent infringement over flutter, we can stop letting you use flutter.

If you need more help understanding the language, please contact a local lawyer.

Best,
Max for Google OSPO

**Comment by erlangp** [comment]
is Flutter BSD license? @sillsm

**Comment by Hixie** [comment]
The Flutter framework (the Dart code) is licensed under a BSD variant.
The Flutter engine uses open source code with a variety of licenses, you can see the full details here: 
https://github.com/flutter/engine/tree/master/travis/licenses_golden

I recommend contacting a local lawyer if you need advice on this matter. Thanks.
