### ISSUE TITLE
Update Documentation to Reflect `MaterialStateProperty` Deprecation

### ISSUE THREAD

**Issue by taham8875** [flutter/flutter#152864]
### Use case

**Description:**

The `MaterialStateProperty` typedef has been deprecated in favor of `WidgetStateProperty` as indicated in the documentation:

```
@Deprecated('Use WidgetStateProperty instead. Moved to the Widgets layer to make code available outside of Material. This feature was deprecated after v3.19.0-0.3.pre.')
```

However, it appears that the official Flutter documentation and examples have not been updated to reflect this change. The current usage of `MaterialStateProperty` in the documentation leads to warnings and potential confusion for developers.

**Steps to Reproduce:**

1. Visit [Checkbox class documentation](https://api.flutter.dev/flutter/material/Checkbox-class.html)
2. Observe the deprecation warnings.

![image](https://github.com/user-attachments/assets/72c4f5f7-55ef-44f0-a44b-0bca86f49a5e)

**Additional Context:**
The deprecation notice states: 
```
'MaterialStateProperty' is deprecated and shouldn't be used. Use 'WidgetStateProperty' instead. Moved to the Widgets layer to make code available outside of Material. This feature was deprecated after v3.19.0-0.3.pre.
```

This change aims to make the property available outside of Material, ensuring more versatile and reusable code.

Updating the documentation to reflect these changes will help developers adhere to the latest best practices and avoid deprecated features.

**Environment:**
- Flutter version: v3.19.0-0.3.pre and above

Thank you for your attention to this matter.

### Proposal

**Expected Behavior:**
The documentation should be updated to use `WidgetStateProperty` instead of `MaterialStateProperty`.

**Comment by RamonFarizel** [comment]
I guess this was already done by this PR.
https://github.com/flutter/flutter/pull/151374

**Comment by taham8875** [comment]
> I guess this was already done by this PR.
https://github.com/flutter/flutter/pull/151374

Nope, visit [https://api.flutter.dev/flutter/material/Checkbox-class.html](https://api.flutter.dev/flutter/material/Checkbox-class.html)

**Comment by goderbauer** [comment]
This is fixed on master: https://main-api.flutter.dev/flutter/material/Checkbox-class.html. The stable API docs at https://api.flutter.dev/flutter/material/Checkbox-class.html will see this change when a new stable version of Flutter is released.
