### ISSUE TITLE
Fatal Exception: FlutterError Bad state: Future already completed

### ISSUE THREAD

**Issue by dev3-tech** [flutter/flutter#152852]
### Steps to reproduce

it is generate randomly in basic video_player implementation code

### Expected results

no error

### Actual results

```
 Fatal Exception: FlutterError
0  ???                            0x0 _AsyncCompleter.complete (dart:async)
1  ???                            0x0 VideoPlayerController.initialize.eventListener + 468 (video_player.dart:468)
```
        

### Code sample

it is generate randomly in basic video_player implementation code

### Logs

```
 Fatal Exception: FlutterError
0  ???                            0x0 _AsyncCompleter.complete (dart:async)
1  ???                            0x0 VideoPlayerController.initialize.eventListener + 468 (video_player.dart:468)
```
        

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6 22G120 darwin-x64, locale en-IN)
• Flutter version 3.19.6 on channel stable at /Applications/development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
• Engine revision c4cd48e186
• Dart version 3.3.4
• DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at /Users/mac007/Library/Android/sdk
• Platform android-34, build-tools 34.0.0
• ANDROID_HOME = /Users/mac007/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 15A240d
• CocoaPods version 1.15.2

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.74.3)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.60.0

[✓] Connected device (2 available)
• macOS (desktop) • macos • darwin-x64 • macOS 13.6 22G120 darwin-x64
• Chrome (web) • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] Network resources
• All expected network resources are available.
```

**Comment by darshankawar** [comment]
@dev3-tech 
Can you provide entire stacktrace ? 
Is it occuring in debug mode locally or in production ?


> it is generate randomly in basic video_player implementation code

Can you upgrade to latest stable and use latest plugin version to see if you still get same behavior or not ?

**Comment by dev3-tech** [comment]
provided log is entire stacktrace and it is occuring in production.

**Comment by darshankawar** [comment]
What other plugins are you using in your app ? Can you provide `pubspec.yaml` ? Could be that implementation of other dependencies could also trigger the error you are seeing. Try to narrow down or provide replication pattern because the provided stacktrace is not conclusive.

**Comment by dev3-tech** [comment]
path: ^1.9.0
  path_provider: ^2.1.4
  external_path: ^1.0.3
  permission_handler: ^11.3.1
  photo_manager: 3.0.0
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  video_thumbnail: ^0.5.3
  video_player: ^2.9.1
  chewie: ^1.8.3
  marquee: ^2.2.3
  on_audio_query: ^2.9.0
  audioplayers: ^6.0.0
  disk_space: ^0.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  dropdown_button2: ^2.3.9
  firebase_core: 2.32.0
  firebase_core_platform_interface: 5.0.0
  firebase_analytics: 10.10.7
  firebase_crashlytics: 3.5.7
  firebase_performance: 0.9.4+7
  firebase_remote_config: 4.4.7
  firebase_in_app_messaging: 0.7.5+7
  firebase_messaging: 14.9.4
  flutter_local_notifications: ^17.2.2

  google_mobile_ads: ^5.1.0
  camera: 0.10.6
  lottie: ^3.1.2
  in_app_review: ^2.0.9
  upgrader: ^10.3.0
  flutter_inappwebview: ^6.0.0
  dio: ^5.6.0
  flutter_dynamic_icon: ^2.1.0
  share_plus: ^10.0.0
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.0.2
  network_info_plus: ^6.0.1
  sensors_plus: ^6.0.1
  proximity_sensor: 1.3.1
  flip_card: ^0.7.0
  mask_text_input_formatter: ^2.9.0
  screen_protector: ^1.4.2
  tutorial_coach_mark: ^1.2.11
  purchases_flutter: 6.29.2
  font_awesome_flutter: ^10.7.0
  wakelock_plus: ^1.2.8
  flutter_image_compress: ^2.3.0
  vibration: ^1.9.0
  flutter_app_badger: ^1.5.0
  mime: ^1.0.5
  provider: ^6.1.2
  audio_waveforms: ^1.0.5
  html: ^0.15.4
  pie_chart: ^5.4.0
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.6
  file_picker: 8.0.5
  icloud_storage: ^2.2.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_nearby_connections: ^1.1.2
  location: 6.0.2
  file_saver: ^0.2.13

**Comment by darshankawar** [comment]
These are all third party packages, so you will need to narrow down the code to reproducible sample to see which one could be causing it.

**Comment by agufagit** [comment]
I'm getting this exception also, here is my full stacktrace
```
[log] PlatformDispatcher.instance.onError: Bad state: Future already completed, #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
      #1      VideoPlayerController.initialize.eventListener (package:video_player/video_player.dart:468:33)
video_player.dart:468
      #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
zone.dart:1594
      #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
stream_impl.dart:365
      #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
stream_impl.dart:297
      #5      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
stream_pipe.dart:123
      #6      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
stream_pipe.dart:218
      #7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
stream_pipe.dart:153
      #8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
zone.dart:1594
      #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
stream_impl.dart:365
      #10     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
stream_impl.dart:541
      #11     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
stream_impl.dart:646
      #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
stream_impl.dart:617
      #13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
schedule_microtask.dart:40
      #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
schedule_microtask.dart:49
```

a simple check on line 468 of video_player.dart should fix this, as completer can be completed by error messages before this call:
```dart
if (!initializingCompleter.isCompleted()) {
  initializingCompleter.complete(null);
}
```
