### ISSUE TITLE
Intercepting links from the browser to open my app

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#15287]
On stackoverflow i saw this:
[https://stackoverflow.com/questions/1609573/intercepting-links-from-the-browser-to-open-my-android-app](https://stackoverflow.com/questions/1609573/intercepting-links-from-the-browser-to-open-my-android-app)

I can write the part of manifest file also in flutter:

```
<intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="http"
                  android:host="flickr.com"
                  android:pathPrefix="/photos/" />
            <data android:scheme="http"
                  android:host="www.flickr.com"
                  android:pathPrefix="/photos/" />
        </intent-filter>

```

But how i can write the activity part with dart/flutter for get params?

```
final Intent intent = getIntent();
    final String action = intent.getAction();

    if (Intent.ACTION_VIEW.equals(action)) {
        final List<String> segments = intent.getData().getPathSegments();
        if (segments.size() > 1) {
            mUsername = segments.get(1);
        }
    }
```

Is there anything similar to do it in ios?

Thanks

**Comment by durduliu2009** [comment]
@romaluca you closed this issue but you didn't provide us a solution or result ? Have you succeeded ? If yes how ? Can you give us a link ? Many thanks in advance

**Comment by pedromorgan** [comment]
Yea I want to know "solution" also...
