### ISSUE TITLE
Google maps camera position is moved after widget built

### ISSUE THREAD

**Issue by kandangit** [flutter/flutter#152805]
### Steps to reproduce

1.- I navigate from a screen to a second screen with a GoogleMap
2.- That Google Map has an initialCameraPosition and displays correctly in the position
3.- Navigate back to the previous page and edit coordinates (Lat, Long) in a string variable
4.- Navigate again to the scond screen with a GoogleMap. This time with the new initialCameraPosition with the new coordinates
5.- Now the GoogleMap widget is centered at the previous location.

If i go back and navigate again to the map screen, the position is correct.
I have logs that confirm that the initialCameraPosition given to GoogleMap is correct (not a bug on my code), but the initialCameraPosition seems "cached"

### Expected results

I expect the camera to be in the point given by the initialCameraPosition property

### Actual results

When I navigate to a screen with a GoogleMap widget the initialCameraPosition is picked correctly

If I edit that initial position and navigate again to the same screen with the GoogleMap, the map is not moved to the new initialCameraPosition. Instead, it is on the previous one.

I have confirmed with logs that the position i give to GoogleMap is the correct one, just seem not to move there.

### Code sample

<details open><summary>This is how I build the GoogleMap widget</summary>

```dart
builder: (context, state) {
if (state.mapaInfo.state == LoadedTypeState.loading ||
    state.mapaInfo.state == LoadedTypeState.pending) {
  if (state.mapaInfo.state == LoadedTypeState.loading) {}
  return const LoadingIndicatorWidget();
} else {
  MapaInfo mapaInfo = state.mapaInfo.data!;
  Set<Marker> markers = <Marker>{};
  Marker marker = Marker(
      markerId: MarkerId(
          'geo-location-mapa-${DateTime.timestamp().toString()}'),
      position: mapaInfo.posicionInicial);
  markers.add(marker);
  return GoogleMap(
    myLocationButtonEnabled: true,
    myLocationEnabled: true,
    markers: markers,
    initialCameraPosition:
        CameraPosition(target: mapaInfo.posicionInicial, zoom: 16),
    onMapCreated: (GoogleMapController controller) {
      _controller = controller;
    },
    onCameraMove: (position) {
      currentLatLong= position.target;
    },
  );
}
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Versi¢n 10.0.19045.4651], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.4)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 4.2)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] VS Code (version 1.92.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @kandangit, what platform(s) are you experiencing this issue on? Please provide the version of `google_maps_flutter` you're using. 

Please also provide a complete minimal reproducible code sample `without any third-party packages` so that we can properly investigate this issue. 

Thank you

**Comment by kandangit** [comment]
Hi @danagbemava-nc 

I use 2.7.0

I will work on creating a sample app to see if i can reproduce it there. Thank you.

**Comment by kandangit** [comment]
Can't reproduce this in a sample app without third-party packages.

Looking at my code seems it has to do with using BlocConsumer (Bloc framework). When the builder executes the second time, the camera is not "moved" with the second build.
Placed some logs, making sure the CameraPosition target it correct , but it seems the camera position is set on the first build (first call to the builder's method of the Bloc Consumer)

Workaround in my case is:

- use a boolean variable initialized to false.
- The first time the onCameraMove is called, move it to the initial position given also to "initialCameraPosition":


        onCameraMove: (position) {
          currentLatLong = position.target;
          if (!init) {
            init = true;
            gotoInitialPosition();
          }
        },
