### ISSUE TITLE
[pigeon] Support enum's raw value custom type.

### ISSUE THREAD

**Issue by wamynobe** [flutter/flutter#152807]
### Use case

I'm currently using enum like this in messages.dart file
```dart
enum MyEnum {
  firstEnum,
  secondEnum;
}
```
and then pigeon helped me generate Swift and Kotlin code
```swift
enum MyEnum: Int {
  case firstEnum = 0
  case secondEnum = 1
}
```
It will be int type ( or maybe by default ) for both Swift and Kotlin

### Proposal

it would be great if Pigeon could somehow change the data type of the raw value (only supporting primitive data types is fine)
For example :
```swift
enum MyEnum: String {
  case firstEnum = "firstEnum"
  case secondEnum = "secondEnum"
}
```

**Comment by stuartmorgan** [comment]
Could you describe the use case? What's written in the "use case" above is just a description of the current behavior, than than problem that you are trying to solve.

Given that not all languages supported by Pigeon support complex enums, and the support that exists varies within those, a concrete example of a real use case would be helpful in understanding the scope of the request.
