### ISSUE TITLE
Impeller engine is worse than skia in flutter android

### ISSUE THREAD

**Issue by akhamesaumet** [flutter/flutter#152834]
### Steps to reproduce

upgrade flutter to latest version, then in terminal run flutter run --enable-impeller
![Screenshot from 2024-08-04 14-52-50](https://github.com/user-attachments/assets/450b6c62-b4c1-4e9c-b49f-8888669205d6)

### Code sample

Skia:
![Screenshot from 2024-08-04 14-33-50](https://github.com/user-attachments/assets/95c4eea4-2a04-464e-83df-3372e4e712ad)
Impeller:
![Screenshot from 2024-08-04 15-00-03](https://github.com/user-attachments/assets/b1d8aae5-04c8-45c6-99fa-a72f6fc96e92)

### Performance profiling on master channel

- [x] The issue still persists on the master channel

### Timeline Traces

<details open><summary>Timeline Traces JSON</summary>

```json
[Paste the Timeline Traces here]
```

</details>

### Video demonstration

<details open>
<summary>Video demonstration</summary>

[Upload media here]

</details>

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

null

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Is the problem only reproducible with Impeller?

Yes

### Flutter Doctor output

<details open><summary>Doctor output</summary>
[✓] Flutter (Channel stable, 3.22.3, on Ubuntu 22.04.2 LTS 5.14.0-1048-oem, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2023.3)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] Connected device (3 available)
[✓] Network resources
</details>

**Comment by jonahwilliams** [comment]
Can you share a sample project or some examples code that demonstrates the problem? Also please specify what kind of android device you are running on

**Comment by rehamalraee24** [comment]
@jonahwilliams  hello, thanks for your response, 
what should a sample project show? because ours is very large. 
we tried on both real and emulator

**Comment by akhamesaumet** [comment]
`import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'dart:async';
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  Timer? _timer;
  @override
  void initState() {
    super.initState();
    _startTimer();
  }
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
  void _startTimer() {
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      setState(() {
        _counter++;
      });
    });
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CarouselSlider(
              options: CarouselOptions(height: 200.0, autoPlay: true),
              items: [1, 2, 3, 4, 5].map((i) {
                return Builder(
                  builder: (BuildContext context) {
                    return Container(
                      width: MediaQuery.of(context).size.width,
                      margin: const EdgeInsets.symmetric(horizontal: 5.0),
                      decoration: const BoxDecoration(
                        color: Colors.amber,
                      ),
                      child: Center(
                        child: Text(
                          'Banner $i',
                          style: const TextStyle(fontSize: 16.0),
                        ),
                      ),
                    );
                  },
                );
              }).toList(),
            ),
            const Text(
              'You have to go the next page to catch the issue',
            ),
            ElevatedButton(
                onPressed: () {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) => const SecondPage()));
                },
                child: const Text("Go To next Page")),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text("Second Page"),
      ),
    );
  }
}
`

**Comment by darshankawar** [comment]
@akhamesaumet 
https://pub.dev/packages/carousel_slider is a third party package. Please try to keep out external dependencies and see if you still get same reported behavior or not. If so, provide updated code. 

> Also please specify what kind of android device you are running on

Please provide these details as well.

**Comment by akhamesaumet** [comment]
Thank you for your response, here is an example without third party package and still the same behavior occurs.
`import 'package:flutter/material.dart';
import 'dart:async';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  Timer? _timer;
  int _currentPage = 0;
  final PageController _pageController = PageController(initialPage: 0);

  @override
  void initState() {
    super.initState();
    _startTimer();
  }

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  void _startTimer() {
    _timer = Timer.periodic(const Duration(seconds: 2), (timer) {
      setState(() {
        _currentPage = (_currentPage + 1) % 5; // Looping through the 5 items
        _pageController.animateToPage(
          _currentPage,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
        );
      });
    });
  }

  @override
  void dispose() {
    _timer?.cancel();
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SizedBox(
              height: 200.0,
              child: PageView.builder(
                controller: _pageController,
                itemCount: 5,
                itemBuilder: (context, index) {
                  return Container(
                    margin: const EdgeInsets.symmetric(horizontal: 5.0),
                    decoration: const BoxDecoration(
                      color: Colors.amber,
                    ),
                    child: Center(
                      child: Text(
                        'Banner ${index + 1}',
                        style: const TextStyle(fontSize: 16.0),
                      ),
                    ),
                  );
                },
              ),
            ),
            const Text(
              'You have to go to the next page to catch the issue',
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const SecondPage(),
                  ),
                );
              },
              child: const Text("Go To Next Page"),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text("Second Page"),
      ),
    );
  }
}
`

**Comment by darshankawar** [comment]
Although I don't have a physical Android device for now, but I tried on Pixel emulator with which running above code show below:

<img width="1200" alt="Screenshot 2024-08-13 at 11 24 02 AM" src="https://github.com/user-attachments/assets/3f4b26de-56f6-48c5-9a8c-b710d7780802">

But this is in debug mode. Can you check in profile mode and running the app with physical device instead of in emulator ?
The performance in emulator may vary as compared to physical device and may not represent actual performance.
