### ISSUE TITLE
Text rendering issue on MacOS

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#15283]
Per discussion in the mailing list here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/flutter-desktop-embedding-dev/LxEV_9WZcKM/fgsQIKWRAAAJ

Text rendering on MacOS looks far from perfect, as seen on this screenshot:
![image](https://camo.githubusercontent.com/d7464fa5ee74aad3fd7eea5299c81ee0363067d8/68747470733a2f2f7777772e657665726e6f74652e636f6d2f73686172642f73312f73682f63303366303736352d613632362d343939362d613065642d3866396166313834333338642f343737646137323031653766623163362f7265732f39616536616538662d326136652d346235662d383366352d3931316430376533383138312f736b697463682e706e673f726573697a65536d616c6c2677696474683d363430)

Taken from example app created by @rxlabz using https://github.com/google/flutter-desktop-embedding

cc @chinmaygarde @stuartmorgan

**Comment by chinmaygarde** [comment]
Update: I was able to reproduce this issue in the Mac embedder. Doesn't seem to be related to the offscreen rendering or the raster cache as I had initially suspected. Will keep investigating in the morning.

**Comment by chinmaygarde** [comment]
This seems to happen on the mobile shells as well. @cbracken just showed this to me on his iPhone X.

**Comment by pulyaevskiy** [comment]
Not sure if there is any remaining work left, but after latest PR in desktop embedding repo which fixes device pixel ratio rendering looks much better:

![image](https://user-images.githubusercontent.com/441756/38337414-fca23aea-3819-11e8-80d0-771fa404aa8f.png)

**Comment by zoechi** [comment]
I'm going to close. 
Probably better to create new issues when concrete problems emerge.
