### ISSUE TITLE
[Impeller] rrect blur has weird artifacts sometimes

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#152887]
## reproduction
```c++
TEST_P(DlGoldenTest, LargeDownscaleRrect) {
  impeller::Point content_scale = GetContentScale();
  auto draw = [&](DlCanvas* canvas, const std::vector<sk_sp<DlImage>>& images) {
    canvas->Scale(content_scale.x, content_scale.y);
    DlPaint paint;
    paint.setColor(DlColor::kYellow());
    paint.setMaskFilter(
        DlBlurMaskFilter::Make(DlBlurStyle::kNormal, /*sigma=*/10));
    canvas->DrawCircle(SkPoint::Make(0, 0), 500, paint);
  };

  DisplayListBuilder builder;
  draw(&builder, /*images=*/{});

  ASSERT_TRUE(OpenPlaygroundHere(builder.Build()));
}
```
## observed output
<img width="1026" alt="Screenshot 2024-08-05 at 1 16 14 PM" src="https://github.com/user-attachments/assets/ed4ed7c2-392a-4edb-89d9-07d697c99213">

**Comment by jonahwilliams** [comment]
@gaaclarke what is the scaling factor here? Does this look weird at regular scales, or is this a "galaxy" scale issue?

**Comment by gaaclarke** [comment]
> @gaaclarke what is the scaling factor here? Does this look weird at regular scales, or is this a "galaxy" scale issue?

The scaling factor isn't big, it would just be the 2x from `content_scale.x`.

**Comment by gaaclarke** [comment]
@flar have you seen this before?  Any theories?

**Comment by flar** [comment]
I remember having seen banding like that. When I looked at the math of the fast blurs I believed that it was due to the way the minimal number of bands being averaged were chosen.

I don't think the squircle solutions suffer from this effect because they provide a more continuous answer.

**Comment by gaaclarke** [comment]
fixed in https://github.com/flutter/engine/pull/55604
