### ISSUE TITLE
How to build bin/flutter from flutter framework source

### ISSUE THREAD

**Issue by imaginegit** [flutter/flutter#152823]
### Steps to reproduce

1. I have download flutter framework source from https://github.com/flutter/flutter， there is a default program here: bin/flutter
2. then I add some debug info to flutter framework source
3. How can I build and update the bin/flutter 
I think after I build and update the bin/flutter, the app build by the new program will print my debug info, Am I right？

### Actual results

I don't know how to build and update bin/flutter

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/blob/master/docs/tool/README.md#making-changes-to-the-flutter-tool for information about making changes to the source.
