### ISSUE TITLE
Input from barcode scanner

### ISSUE THREAD

**Issue by mark-amaray** [flutter/flutter#15291]
I have a Unitech EA600 android device with an integrated barcode scanner.

The scanner is configured to emulate a keyboard (can emulate either software or hardware keyboards)

I have created both TextField and EditibleText widgets, neither of which will capture the input from the scanner. 

Whenever I scan a barcode with the app running, i get the following three lines in my debug window:
D/ViewRootImpl(30020): set decode data to edittext
D/ViewRootImpl(30020): mInput1
D/ViewRootImpl(30020): mInput

This suggests that the app is "noticing" the input but is not doing anything with it.

Does anyone have any idea how i can capture that input and process it?

Thank you.

**Comment by zoechi** [comment]
My guess is that this is because of #11177

**Comment by mark-amaray** [comment]
is there a known workaround? 

I am developing an app to manage inventory in our store room, everything is barcoded so this needs to work.

This is my first dart/flutter app, so i am learning as i go.

Thank you.

**Comment by Hixie** [comment]
We added support for hardware keyboard recently which should have fixed this. Please let us know (file a new bug) if it doesn't work!

**Comment by mhsnprvr** [comment]
> is there a known workaround?
> 
> I am developing an app to manage inventory in our store room, everything is barcoded so this needs to work.
> 
> This is my first dart/flutter app, so i am learning as i go.
> 
> Thank you.

i have exact same problem,did you find any solution?

**Comment by Dea10** [comment]
> I have a Unitech EA600 android device with an integrated barcode scanner.
> 
> The scanner is configured to emulate a keyboard (can emulate either software or hardware keyboards)
> 
> I have created both TextField and EditibleText widgets, neither of which will capture the input from the scanner.
> 
> Whenever I scan a barcode with the app running, i get the following three lines in my debug window:
> D/ViewRootImpl(30020): set decode data to edittext
> D/ViewRootImpl(30020): mInput1
> D/ViewRootImpl(30020): mInput
> 
> This suggests that the app is "noticing" the input but is not doing anything with it.
> 
> Does anyone have any idea how i can capture that input and process it?
> 
> Thank you.

got the same problem
