### ISSUE TITLE
Urgent Flutter 3.24.1 Cherry picks for web

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#152953]
We have several things we want to track for the first CP. Rolling them all up here.

- [x] https://github.com/flutter/engine/pull/53718
  - Also https://github.com/flutter/flutter/issues/152844
  - CP request - https://github.com/flutter/engine/pull/54446
- [x] https://github.com/flutter/engine/pull/54007
  - CP request issue: https://github.com/flutter/flutter/issues/152047
- [x] https://github.com/dart-lang/sdk/issues/56374
- [x] https://github.com/dart-lang/sdk/issues/56423 (source maps)
  - [x] https://github.com/flutter/flutter/issues/153308
  - [x] https://github.com/flutter/flutter/pull/153310
- [x] https://github.com/dart-lang/sdk/issues/56440

**Comment by itsjustkevin** [comment]
As this is a tracking issue and not a cherry-pick, I am removing the "cp: review" label to cleanup the dashboard.

**Comment by franboladoruiz** [comment]
Any ETA when 3.24.1 will be released? (#145410 is quite critical)
Thanks for your work 🙂

**Comment by Terranic** [comment]
When can we expect a release of these "urgent" Cherry picks? 
Wondering as there are some production gating issues for Flutter Web.

**Comment by kevmoo** [comment]
@Terranic – we've had a few bumps. Being careful to make sure everything is working great. Thanks for your patience!

**Comment by kevmoo** [comment]
Getting close! https://github.com/flutter/flutter/pull/153772

**Comment by kevmoo** [comment]
3.24.1 has landed. Please update your releases and let us know if there are other issues! 🙏 

Thanks for your patience.

**Comment by hawkewebtpa** [comment]
As I originally posted, we upgraded from 3.19.5 to 3.24.0 (also tried with 3.22.3 but had same problem), and now upgraded to 3.24.1. Tried dart pub cache clean, flutter clean, flutter pub get, flutter build web.
Still have the same error (and page sits and spins forever waiting to load with no other error messages):
Uncaught TypeError: Cannot read properties of undefined (reading 'load') for index.html
    at (index):206:30

For the line:
"_flutter.FlutterLoader.load({"

Page will load normally if revert that line back to:
"_flutter.loader.loadEntrypoint({"
But then of course get the deprecation warning:
"Warning: In index.html:206: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead. See
https://docs.flutter.dev/platform-integration/web/initialization for more details."

The upgrade worked for the {{flutter_service_worker_version}} upgrade, but still broken for the FlutterLoader.load.

Any additional suggestions what I can try on our end to address this? Anything else you need from me to help track this down? Should I create this as a new ticket issue?

Here is the whole script snippet for the web/index.html template (any syntax or other issues that might be contributing this perhaps?):

<script>
    function delay(time) {
      return new Promise(resolve => setTimeout(resolve, time));
    }

    window.addEventListener('load', function (ev) {
      // Download main.dart.js      
      _flutter.FlutterLoader.load({
        serviceWorker: {
          serviceWorkerVersion: '{{flutter_service_worker_version}}',
        },
        onEntrypointLoaded: function (engineInitializer) {
          var loaderContent = document.querySelector('#loader-content');

          engineInitializer.initializeEngine().then(async function (appRunner) {
            loaderContent.style.opacity = "0";
            await delay(400);
            await appRunner.runApp();
          });
        }
      });
    });
  </script>



 flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at /Users/User/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/User/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/User/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/User/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (2 available)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by hawkewebtpa** [comment]
Went ahead and created new ticket: https://github.com/flutter/flutter/issues/153941

**Comment by pedromassango** [comment]
@kevmoo could we cherripick this one:
https://github.com/flutter/flutter/issues/147050

**Comment by kevmoo** [comment]
@pedromassango – it's here – just need you to fill out some details, please!

**Comment by ditman** [comment]
Thanks for landing these CPs people! 🙏
