### ISSUE TITLE
Closing/Not closing on selected DropdownMenu

### ISSUE THREAD

**Issue by AlessandroDeStefano** [flutter/flutter#152933]
### Use case

If I'm not mistaken, there is currently no way to prevent a `DropdownMenu` from closing when a user selects an item. 

I'm using `DropdownMenu` to implement a multi-select dropdown with a search feature, incorporating `Checkbox` widgets for multi-selection. For my use case, the desired behavior is for the menu to remain open when an item is selected, allowing users to toggle the checkbox by clicking on the row itself, not just on the checkbox.

In my opinion, this new behavior for the dropdown menu could be useful in cases where each menu item has a state that can be changed upon selection.

There are some packages on pub.dev that implement a multi-select dropdown with search, though they offer limited customizability. However, I haven't found a straightforward way to achieve the same functionality using Flutter Widgets without creating a custom dropdown.

I found that using `DropdownMenu` to achieve the desired behavior is relatively easy. The only feature I'm missing is the ability to keep the `MenuItemButton` open when a user selects an item.

I've attached a video demonstrating the current behavior: the dropdown menu closes automatically when an item is selected.

https://github.com/user-attachments/assets/5db30aa8-f800-4f80-86f9-d546f6c27d9d

### Proposal

`DropdownMenu` internally uses `MenuItemButton`, which has a `closeOnActivate` property that can be utilized to achieve the desired behavior. Here's a possible solution:

- Add an additional parameter to the `DropdownMenu` constructor: `final bool closeOnSelected`, which defaults to `true`.
- When `DropdownMenu` builds the buttons (in the `_buildButtons` method), pass the `closeOnSelected` property to the `closeOnActivate` parameter of the `MenuItemButton` constructor.

Below is an extract from the `_buildButtons` method, adding the mentioned property:
```dart
final Widget  menuItemButton = MenuItemButton(
  key: enableScrollToHighlight ? buttonItemKeys[i] : null,
  style: effectiveStyle,
  leadingIcon: entry.leadingIcon,
  trailingIcon: entry.trailingIcon,
  onPressed: entry.enabled
    ? () {
        _textEditingController.value = TextEditingValue(
          text: entry.label,
          selection: TextSelection.collapsed(offset: entry.label.length),
        );
        currentHighlight = widget.enableSearch ? i : null;
        widget.onSelected?.call(entry.value);
      }
    : null,
  requestFocusOnHover: false,
  // *************
  closeOnActivate: widget.closeOnSelected,
  // *************
  child: label,
);
```

I've attached a video demonstrating the behavior after implementing the provided solution.

https://github.com/user-attachments/assets/66bccb91-83db-4193-a2f6-b5f901ceea2a

**Comment by PurplePolyhedron** [comment]
You can use something that absorbs gesture in the `DropdownMenuEntry.labelWidget` to stop the selecting gesture being picked up by MenuItemButton.

```
import 'package:flutter/material.dart';

void main() {
  runApp(const DropdownMenuExample());
}

enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Orange', Colors.orange),
  grey('Grey', Colors.grey);

  const ColorLabel(this.label, this.color);

  final String label;
  final Color color;
}

class DropdownMenuExample extends StatelessWidget {
  const DropdownMenuExample({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 20),
                child: DropdownMenu<ColorLabel>(
                  label: Text(key: key, 'Color'),
                  menuStyle: MenuStyle(
                    padding: WidgetStatePropertyAll(EdgeInsets.all(0)),
                  ),
                  width: 200.0,
                  dropdownMenuEntries: ColorLabel.values
                      .map<DropdownMenuEntry<ColorLabel>>((ColorLabel color) {
                    return DropdownMenuEntry<ColorLabel>(
                      value: color,
                      label: color.label,
                      labelWidget: GestureDetector(
                        onTap: () {},
                        onDoubleTap: () {},
                        child: AbsorbPointer(
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(color.label),
                                Checkbox(value: false, onChanged: (_) {})
                              ],
                            ),
                          ),
                        ),
                      ),
                      style: MenuItemButton.styleFrom(
                        foregroundColor: color.color,
                      ),
                    );
                  }).toList(),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
Note: You need to provide a width to the `DropdownMenu` in stable, due to a bug(may be https://github.com/flutter/flutter/issues/147173) regarding item width, but it is fixed in main/beta.

**Comment by huycozy** [comment]
@AlessandroDeStefano You can try the solution above to see if it works for your case. And I see this is similar to an open proposal at https://github.com/flutter/flutter/issues/139269. Closing this to concentrate on that one. So please follow it and you can also share your thoughts there which will help to consolidate the issue. Thanks!

**Comment by AlessandroDeStefano** [comment]
@PurplePolyhedron Thank you for the solution! Unfortunately the `Stack` does not occupy the whole `DropdownMenuEntry`, and it is even more obvious if the `DropdownMenu` has a leading or a trailing icon; I didn't manage to fix that.

@huycozy Thank you for the answer, I will follow the issue you mentioned.
