### ISSUE TITLE
[google_maps_android] Update robolectric tests to run against minSdk version instead of sdk and lower that sdk version to the oldest supported. 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#152931]
Robolectric has the ability to run tests against multiple variations of android. It appears that for most of our testing we use `@Config(sdk = Build.VERSION_CODES.X)` which runs the tests against one android version. Roboletric also supports minSdk which will use the value as a min and run for all following version codes. 
In addition it appear that maps set the SDK to android "P" when the underlying maps sdk supports back to 21. 

Convert all robolectric tests in google_maps_android to use minSdk and set the minSdk to the lowest value possible. Document the work arounds or things you learned so that when we do this change to other platforms it goes smoother. 

Related comment thread: https://github.com/flutter/packages/pull/7313#issuecomment-2270038753

Documentation also says it supports android api 20 and above which is incorrect given the min version of android flutter supports is api 21. https://pub.dev/packages/google_maps_flutter

**Comment by yaakovschectman** [comment]
Update on progress: Lowering `minSdk` in ConvertTest.java to `LOLLIPOP` (21) results in each test of that file throwing OOM. Each test on each individual SDK (i.e. `ConvertTest.testName[X]`) succeeds, but the overall test (`ConvertTest.testName`) throws the error.

Increasing Xmx in https://github.com/flutter/packages/blob/main/packages/google_maps_flutter/google_maps_flutter_android/example/android/gradle.properties up to even my system's max of 64G does not resolve this, neither does adding an Xms.

Adding a trivial test in the file that merely asserts a number is equal to itself and running only that individual test still OOMs in the same way. Commenting out the `Before` and `After` methods still OOMs. Removing all mocked fields at the class level and only running that trivial test that does not explicitly utilize any mocks or resources still OOMs.

My only thought is that some dependency may be leaking memory.
