### ISSUE TITLE
Confusion using FlutterAnimatedList.query

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#15299]
https://twitter.com/KyleTheCoder/status/971805177115303937

> for dynamic @Firebase queries you have to initialize the appropriate state before attempting to use it in the FirebaseAnimatedList query property and pass it through the ctor; otherwise, there doesn't seem to be an async place you can await a call to get a value before it calls Build on your widget

Not sure if a doc update is needed?  @collinjackson

**Comment by kroikie** [comment]
@eseidelGoogle

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/894. Any further collaboration will be done there.
