### ISSUE TITLE
Unable to pub upgrade flutter tool. Retrying in five seconds...

### ISSUE THREAD

**Issue by lakexyde** [flutter/flutter#15292]
I just can't seem to get flutter run on my machine. I know this issue is all over the places but I still haven't found any solutions.

I followed all instructions and installed/uninstalled several times but still the same problem.

It appears dart-sdk downloaded successfully but I can't run `flutter doctor` without getting that.
I am running  Windows10.
![flutter](https://user-images.githubusercontent.com/20032543/37151773-3a656c7e-22d7-11e8-8dc4-f13a03ebe57b.PNG)
Please help...

**Comment by lakexyde** [comment]
Thanks @abhijit-kar.  I did that with two directories c:/flutter and c:/android/flutter but still the same problem.  However it appeared that problem has something  to do with the beta version.  Worked fine with master version.

**Comment by abhijit-kar** [comment]
@lakexyde did it go smooth, through and through, because I have hit a wall.

Upgrade fails at 

```
[!] VS Code (version 1.20.1)
CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
CreateProcessW failed 193
```

Can you tell me the command to install the master version, may be that will solve the problem?

**Comment by lakexyde** [comment]
Here it is. 
```git clone -b beta https://github.com/flutter/flutter.git```

**Comment by zoechi** [comment]
dup of #15014 ?

**Comment by Hixie** [comment]
@lakexyde Is this working these days? We had a bunch of bugs with symptoms like this around the time you were trying but I think those are mostly resolved now.
