### ISSUE TITLE
[Impeller] Everything is green on some Android devices

### ISSUE THREAD

**Issue by armandsLa** [flutter/flutter#152998]
### Steps to reproduce

	1.	Turn on Impeller for Android.
	2.	Have a screen with Lottie animation - this might be optional.

We recently launched an update with Impeller enabled for Android, and some of our users reported that the screen is completely green. We were unable to reproduce this issue, but from the screenshots they sent, we know that this happens when there is a Lottie animation in the background. However, we are not sure if Lottie is causing this.

Devices that have these issues: Vivo V2111; Tecno TECNO SPARK 10.

### Expected results

Everything to be rendered normally

### Actual results

Everything is green:

![1000074742](https://github.com/user-attachments/assets/215c833a-e4af-43ac-b2ab-1eccf96b1301)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @armandsLa, this was initially reported in https://github.com/flutter/flutter/issues/143573 and has since been fixed. The fix is available in the latest stable.

If you're not using stable 3.24.0 (which was released yesterday), can you upgrade to the latest version of flutter stable to see if your users still experience this issue?

**Comment by jonahwilliams** [comment]
We found another issue of this and landed a fix in https://github.com/flutter/engine/pull/54406 . That will not be on the latest stable, but should be on master and the upcoming 3.25 beta. Closing as fixed
