### ISSUE TITLE
`flutter analyze` in website build script failing (after something changed in flutter engine or sdk?)

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#15293]
The flutter/website build is broken on Travis. It looks to be broken by something external (the change that triggered the build is a single character change in the website repo). The build clones the latest `flutter/flutter` `master` code and runs `flutter analyze` on some code.

The last working build was after [this commit](https://github.com/flutter/website/commit/b3a32da3e9e37ec5576147301f734aa0c5f67f57) (to website) and analyzed fine:

```text
Using Dart version:
Dart VM version: 2.0.0-dev.32.0.flutter-ee15c8eb68 (Thu Mar 1 22:39:39 2018 +0000) on "linux_x64"
Running "flutter packages get" in website...
Run flutter packages get on _includes/code/animation/animate1
Running "flutter packages get" in animate1...
Run flutter analyze on _includes/code/animation/animate1
Analyzing /home/travis/build/flutter/website/_includes/code/animation/animate1/main.dart...
No issues found!
Ran in 6.0s
```

Then when [this commit](https://github.com/flutter/website/commit/c81b7c2c5fc674f94c518153e2f2d8d9d86c1454) (to website) was pushed and flutter cloned for its build, it failed with:

```text
Using Dart version:
Dart VM version: 2.0.0-dev.33.0.flutter-b5b8080b2c (Tue Mar 6 14:14:54 2018 +0000) on "linux_x64"
Running "flutter packages get" in website...
Run flutter packages get on _includes/code/animation/animate1
Running "flutter packages get" in animate1...
Run flutter analyze on _includes/code/animation/animate1
Analyzing /home/travis/build/flutter/website/_includes/code/animation/animate1/main.dart...
No dart files found at: /home/travis/build/flutter/website/_includes/code/animation/animate1/main.dart
(Ran in 0.3s)
The command "./tool/travis.sh" exited with 3.
```

**Comment by xqwzts** [comment]
Switching flutter to the beta channel works fine, I'm going to jump through flutter checkouts to try and pin the exact version that broke.

**Comment by DanTup** [comment]
Check out `git bisect`. You give it a good and bad revision and a command it can run (which will pass/fail - like the build script) and it'll find it for you :)

**Comment by xqwzts** [comment]
Thanks for `bisect` tip @DanTup .

It points to the engine roll on #15213 as the bad commit:

> 85412d8b7cbcf92f12d63e68afbf2841586e398a is the first bad commit
commit 85412d8b7cbcf92f12d63e68afbf2841586e398a
Author: Jason Simmons <jason-simmons@users.noreply.github.com>
Date:   Tue Mar 6 14:06:36 2018 -0800
>
>    Roll engine to 24cf8ebd8621713a6936df783dad5019f52bc85e (#15213)

**Comment by DanTup** [comment]
No great surprise it was an engine roll:. Diffs are here:

https://github.com/flutter/engine/compare/a00f8e8bc0f3d08ec0c0ca24b01226441bcaf03a...24cf8ebd8621713a6936df783dad5019f52bc85e

Those diffs also include an SDK roll from ee15c8eb689791f6777eb3f6b0a1e9c58ff0671b to b5b8080b2cfb1e4943a19787ee96548a4a604f7b. Diffs are here:

https://github.com/dart-lang/sdk/compare/ee15c8eb689791f6777eb3f6b0a1e9c58ff0671b...b5b8080b2cfb1e4943a19787ee96548a4a604f7b

So, something in one of the changesets from those two compares likely broke it ;-)

**Comment by filiph** [comment]
I'm going to change flutter/website to use beta channel (for now, at least)

**Comment by filiph** [comment]
This is done now: https://github.com/flutter/website/pull/872

**Comment by DanTup** [comment]
This is broken again, presumably because beta has now updated to the version that causes this failure.
