### ISSUE TITLE
[google_maps_flutter_android] Convert <Polygon, Polyline> to Pigeon

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#152926]
Child task of https://github.com/flutter/flutter/issues/117907 

Example pull request https://github.com/flutter/packages/pull/7207 
Inital code pointer
https://github.com/flutter/packages/blob/82e8d1eecb4518a28083d7c10bd677d06574f9e6/packages/google_maps_flutter/google_maps_flutter_android/pigeons/messages.dart#L33-L121

**Comment by stuartmorgan** [comment]
Was a follow-up issue ever filed for the sub-fields of Polyline that weren't converted (pattern, start/endCap) in the initial conversion?

**Comment by yaakovschectman** [comment]
@stuartmorgan Seems not. I'll get those up today.
