### ISSUE TITLE
[in_app_purchase] How to reliably obtain results of user billing operations

### ISSUE THREAD

**Issue by fushihara** [flutter/flutter#152999]
I have a question about in_app_purchase.

in_app_purchase is the earliest time after the application is launched.
InAppPurchase.instance.purchaseStream.listen() at the earliest possible time after the app is launched to prepare for billing events.
In fact, if you look at the android and iOS documentation, it is included in the specification that the OS will suddenly throw a transaction even if the user does not operate the app while it is running, such as when a subscription is renewed or there are outstanding purchases.

Under the above assumptions, the user performs an app purchase operation and executes the following process.
InAppPurchase.instance.buyConsumable(purchaseParam: purchaseParam);
After this process, the result of whether the user pressed OK for billing, Cancel, or chose to pay later is passed via purchaseStream.

However, as mentioned above, the purchaseStream may suddenly throw an event by the OS.
How can I distinguish that the event passed to purchaseStream is tied to the user's buyConsumable or buyNonConsumable?

I found a web page that describes how to distinguish by product ID, but I don't think it is sufficient because of the possibility of duplication.

**Comment by darshankawar** [comment]
@fushihara 
Ideally this question is best placed for support channels like StackOverflow, as this is more of a `how to` question rather than a bug report, feature request or documentation update. 
Check https://github.com/flutter/flutter/issues/94011 to see if it helps in your case or not.
