### ISSUE TITLE
iOS App Freeze for ~0.5 second on Swipe Back Gesture

### ISSUE THREAD

**Issue by SmallTownRiver** [flutter/flutter#153015]
#48225 

Please pay attention to this issue

Please，Please，Please

**Comment by danagbemava-nc** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/48225

Please do not file issues like this. Instead you should upvote the original issue. Creating issues like this are not productive. 

Thank you

**Comment by SmallTownRiver** [comment]
> Closing this in favor of #48225
> 
> Please do not file issues like this. Instead you should upvote the original issue. Creating issues like this are not productive.
> 
> Thank you

Sorry

But I noticed that this problem has existed for many years, which will directly lead us to give up using flutter. This problem is very serious. I don’t want my App to have such serious defects when it is born. My boss and I cannot accept this situation. This is more serious than any other problem.

Because this problem has not been solved, we have to consider choosing other platforms, which is a fatal blow to a team.

Clicking the list and returning is a very basic operation, very basic (emphasis), I can’t imagine how the users of those flutter applications that have been launched will view the developers.

Please pay attention to this issue
