### ISSUE TITLE
[QUESTION]: Inline all JavaScript and Assets Into a Single HTML Document for a Flutter Web Build

### ISSUE THREAD

**Issue by caleb-at-pieces** [flutter/flutter#153046]
I am attempting to ship a flutter build within my Obsidian plugin. There are a few unique constraints to this kind of deployment:

1. The entire plugin must be shipped within a single main.js file
2. It is not possible to load local resources into an iframe

Essentially the solution that I'm looking for, is to be able to append all javascript and assets that are required to run the application into a single HTML document, this way I can inline this HTML document into my main.js Obsidian plugin bundle, then I can make this html string the contents of an iframe that I create via something like `iframe.srcdoc = htmlContents;`

I've taken a look here: https://docs.flutter.dev/platform-integration/web/initialization and I see that I can create a custom `flutter_bootstrap.js` file as well as inline it into the HTML via the `{{flutter_bootstrap_js}}` flag. The main things that are blocking me right now are on how to inline the `main.dart.js` file into the HTML document, as well as all of the assets that get shipped with the build.

Appreciate any answers or discussion on this!

**Comment by darshankawar** [comment]
> The main things that are blocking me right now are on how to inline the `main.dart.js` file into the HTML document, as well as all of the assets that get shipped with the build.

Keeping the issue open and labeling for team's input on this.

**Comment by yjbanov** [comment]
Our recommended solution is to take the output of `flutter build web` and then use another tool/script that post-processes the output in whatever way is appropriate for your use-case. However, if there's something specific that Flutter does that prevents this please file an issue specifically for that part, and we'll take a look.
