### ISSUE TITLE
Replace Android phones attached to mac hosts with mokeys

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#153061]
The phones attached to these mac hosts should be replaced by mokeys.

flutter-devicelab-mac-18
flutter-devicelab-mac-20
flutter-devicelab-mac-21
flutter-devicelab-mac-22
flutter-devicelab-mac-31
flutter-devicelab-mac-35
flutter-devicelab-mac-36

The Pixel 7 Pros attached to 18 and 22 should be retained to re-attach in the future. The Moto G4s can be discarded.

**Comment by kentnguyen99** [comment]
Swapping the existing phone devices with new Mokey phones are done.  

Will you take a look of mac-32, it's still attaching old Moto G4 phone device. Should mac-32 swapping new phone as well?

**Comment by zanderso** [comment]
The devices appear to be successfully running tests, so I'll close this.
