### ISSUE TITLE
Unable to Run after upgrading flutter to version 3.24 for Android on Windows 11

### ISSUE THREAD

**Issue by asafgo** [flutter/flutter#153001]
### Steps to reproduce

1. upgrade flutter to 3.24
2. open flutter project in vs code
3. run command: flutter pub upgrade
4. Run -> Start Debugging

### Actual results

/C:/Users/yyyy/AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'.
      UnmodifiableUint8ListView(Uint8List(0));

Target kernel_snapshot_program failed: Exception

P.S.
Works without any problem when downgrading back to 3.22.3

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3958], locale he-IL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.10.5)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.92.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

**Comment by Akmalismail** [comment]
[This](https://github.com/jonataslaw/get_cli/issues/263#issue-2365926859) might be related.

I tried the steps [here](https://github.com/jonataslaw/get_cli/issues/263#issuecomment-2213076840) and its fixed

**Comment by asafgo** [comment]
Version 3.24 is stable release?

**Comment by danagbemava-nc** [comment]
Hi @asafgo, 3.24 is the newest stable version. What you're facing is likely an issue with your local pub cache. 

Can you try clearing your pub cache and then running your project again to see if you still experience this issue? You can clear your pub cache by running `flutter pub cache clean`. 

Please also make sure you the packages you are using are compatible with the latest version of flutter and dart.

Thank you

**Comment by asafgo** [comment]
I have already tried `flutter pub cache clean` but it does not working.
How can I check if packages I am using are compatible with version 3.24 as I have tried to run `flutter build apk --debug --verbose` but no error from any package.

**Comment by ffamar** [comment]
I have the same issue after upgrading Flutter to 3.24.0. I tried to clear the pub cache, but the error persists.

```
../../../../.pub-cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'.
      UnmodifiableUint8ListView(Uint8List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:7:7: Error: Method not found: 'UnmodifiableUint32ListView'.
      UnmodifiableUint32ListView(Uint32List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:9:7: Error: Method not found: 'UnmodifiableInt32ListView'.
      UnmodifiableInt32ListView(Int32List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception
```

**Comment by psd24** [comment]
I have the same error with version 3.24.0.

I have installed version 3.22.3 and it works fine.

I don't know what the problem could be.

**Comment by piddval** [comment]
flutter doctor -v
PS C:\Users\piddv\source\repos\prl_chcklst_23> flutter doctor -v
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Versi¢n 10.0.19045.4651], locale es-ES)
    • Flutter version 3.24.0 on channel stable at C:\Users\piddv\flutter\flutter_windows_3.3.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (8 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\piddv\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\Users\piddv\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version unknown)
    • VS Code at C:\Users\piddv\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0
    X Unable to determine VS Code version.

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.4651]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.89
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 127.0.2651.86

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by adonisRodxander** [comment]
Same problem

**Comment by MelihCevhertas** [comment]
Same problem , not any version downgrade solve this issue

**Comment by adonisRodxander** [comment]
This works for me:
1- `flutter pub cache clean`
2- `flutter pub get`
3- `flutter pub upgrade`

**Comment by piddval** [comment]
The error I receive is:
```

```
../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'.
      UnmodifiableUint8ListView(Uint8List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:7:7: Error: Method not found: 'UnmodifiableUint32ListView'.
      UnmodifiableUint32ListView(Uint32List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:9:7: Error: Method not found: 'UnmodifiableInt32ListView'.
      UnmodifiableInt32ListView(Int32List(0));
```
I have checked the dependencies in my project and the package that seems to depend explicetly on archive 3.4.9 is Excel:

> flutter pub deps
Dart SDK 3.5.0
Flutter SDK 3.24.0
[...]
-- equatable 2.0.5
|   |-- collection...
|   '-- meta...
**|-- excel 4.0.3
|   |-- archive 3.4.9**
|   |   |-- pointycastle 3.9.1
|   |   |   |-- collection...
|   |   |   |-- convert...
|   |   |   '-- js...
```
 In file bzip2.dart in the newest version 3.6.1 the reference to Unmodifiable32List has dissapeared

import 'dart:typed_data';

class BZip2 {
  static final Uint8List emptyUint8List = Uint8List(0);
  static final Uint32List emptyUint32List = Uint32List(0);
  static final Int32List emptyInt32List = Int32List(0);

So it seems that the problem in my case is caused by Excel package (https://github.com/justkawal/excel/) depending on  an old version of archive

**Comment by sajidshaikh20** [comment]
I've have same issue
follow this step
flutter pub cache clean
flutter channel stable
flutter pub get
so problem has resolved

**Comment by MelihCevhertas** [comment]
> The error I receive is:
> 
> ```
> 
> ```
> 
> ../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'. UnmodifiableUint8ListView(Uint8List(0)); ^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:7:7: Error: Method not found: 'UnmodifiableUint32ListView'. UnmodifiableUint32ListView(Uint32List(0)); ^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:9:7: Error: Method not found: 'UnmodifiableInt32ListView'. UnmodifiableInt32ListView(Int32List(0));
> 
> ```
> I have checked the dependencies in my project and the package that seems to depend explicetly on archive 3.4.9 is Excel:
> 
> > flutter pub deps
> Dart SDK 3.5.0
> Flutter SDK 3.24.0
> [...]
> -- equatable 2.0.5
> |   |-- collection...
> |   '-- meta...
> **|-- excel 4.0.3
> |   |-- archive 3.4.9**
> |   |   |-- pointycastle 3.9.1
> |   |   |   |-- collection...
> |   |   |   |-- convert...
> |   |   |   '-- js...
> ```
> 
> In file bzip2.dart in the newest version 3.6.1 the reference to Unmodifiable32List has dissapeared
> 
> import 'dart:typed_data';
> 
> class BZip2 { static final Uint8List emptyUint8List = Uint8List(0); static final Uint32List emptyUint32List = Uint32List(0); static final Int32List emptyInt32List = Int32List(0);
> 
> So it seems that the problem in my case is caused by Excel package (https://github.com/justkawal/excel/) depending on an old version of archive

I have the same issue about this package. It must be updated to 3.6.1

**Comment by asafgo** [comment]
> > The error I receive is:
> > ```
> > 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'. UnmodifiableUint8ListView(Uint8List(0)); ^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:7:7: Error: Method not found: 'UnmodifiableUint32ListView'. UnmodifiableUint32ListView(Uint32List(0)); ^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../../AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:9:7: Error: Method not found: 'UnmodifiableInt32ListView'. UnmodifiableInt32ListView(Int32List(0));
> > ```
> > I have checked the dependencies in my project and the package that seems to depend explicetly on archive 3.4.9 is Excel:
> > 
> > > flutter pub deps
> > Dart SDK 3.5.0
> > Flutter SDK 3.24.0
> > [...]
> > -- equatable 2.0.5
> > |   |-- collection...
> > |   '-- meta...
> > **|-- excel 4.0.3
> > |   |-- archive 3.4.9**
> > |   |   |-- pointycastle 3.9.1
> > |   |   |   |-- collection...
> > |   |   |   |-- convert...
> > |   |   |   '-- js...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In file bzip2.dart in the newest version 3.6.1 the reference to Unmodifiable32List has dissapeared
> > import 'dart:typed_data';
> > class BZip2 { static final Uint8List emptyUint8List = Uint8List(0); static final Uint32List emptyUint32List = Uint32List(0); static final Int32List emptyInt32List = Int32List(0);
> > So it seems that the problem in my case is caused by Excel package (https://github.com/justkawal/excel/) depending on an old version of archive
> 
> I have the same issue about this package. It must be updated to 3.6.1

I can confirm that in my code excel 4.0.3 is using archive 3.4.9 that cause the problem.

**Comment by ffamar** [comment]
In my case, the issue is caused by the pdf package that includes archive 3.4.10.

```
├── pdf 3.11.0
│   ├── archive 3.4.10
│   │   ├── pointycastle 3.7.4
│   │   │   ├── collection...
│   │   │   ├── convert...
│   │   │   └── js...
│   │   ├── crypto...
│   │   └── path...
│   ├── barcode 2.2.6
│   │   ├── qr 3.0.1
│   │   │   └── meta...
│   │   └── meta...
│   ├── bidi 2.0.10
│   ├── image 4.1.7
│   │   ├── archive...
│   │   ├── meta...
│   │   └── xml...
│   ├── path_parsing 1.0.1
│   │   ├── meta...
│   │   └── vector_math...
│   ├── xml 6.5.0
│   │   ├── petitparser 6.0.2
│   │   │   └── meta...
│   │   ├── collection...
│   │   └── meta...
│   ├── crypto...
│   ├── meta...
│   └── vector_math...
```

**Comment by asafgo** [comment]
What is working for me, after upgrading to flutter 3.24 is to open `pubspec.yaml` and downgrade excel package to 4.0.2 like so `excel: ^4.0.2` and then add archive 3.6.1 like so `archive: ^3.6.1` and save the file so it will update the packages as needed.

Hopefully, `https://github.com/justkawal/excel` will update excel package to use  archive 3.6.1.

**Comment by MelihCevhertas** [comment]
I solved the issue with these ; 
excel: ^4.0.2
archive: ^3.6.1
And then 
dart pub upgrade --major-versions archive

**Comment by paulobreim** [comment]
This is an error that appeared now with the new version.
Flutter (Channel stable, 3.24.0)
Dart SDK version: 3.5.0 (stable)
This afternoon I compiled my program without any problems. At the end of the day I updated Flutter and Dart and this error started to appear without me having changed anything.
There is nothing to be done, they will have to release a version that corrects this because the error is in their native libs.

**Comment by darshankawar** [comment]
Based on above comments, it seems to be an issue with third party package `excel` which needs to update its dependencies to latest so as to be compatible with Flutter's 3.24.0 version.
I will close as it seems to be resolved per OP's comment: https://github.com/flutter/flutter/issues/153001#issuecomment-2273774139

Also, track the main issue in dedicated repo: https://github.com/flutter/flutter/issues/153001#issuecomment-2273774139

**Comment by RyanTempdrop** [comment]
I think it is more widespread than excel, since I do not use excel

Hw to identify which if any third party is cusing the issue

**Comment by asafgo** [comment]
You can run `flutter pub deps` and you will see which packages using `archive `

**Comment by RyanTempdrop** [comment]
> You can run `flutter pub deps` and you will see which packages using `archive `

The only package I have using archive is lottie 3.1.2 , and it is using archive 3.6.1

Could it mean that Archive is not causing this?

**Comment by incrediblezayed** [comment]
Add this to your pubspec.yaml, it'll work

```yaml
dependency_overrides:
  archive: ^3.6.1
```

**Comment by paulobreim** [comment]
Just do it to fix.
flutter pub upgrade --major-versions

**Comment by kuanyi0226** [comment]
thank u so much, this works for me!

```yaml
dependency_overrides:
  archive: ^3.6.1
```

**Comment by Belveloper** [comment]
for my case i managed to fix this by 
1. upgrade to 3.24
2. update syncfusion package (syncfusion_flutter_sliders package)
3. flutter pub add win32 (i'm not using this package at all but this fixed the UnmodifiableUint8ListView bug i think you can remove it after you successfully run your project )
4. flutter channel stable
5. flutter pub upgrade --major-versions
6. fix some code errors (some code deprecations )
7. run

**Comment by Belveloper** [comment]
@paulobreim yes this is the key to fix the win32 (UnmodifiableUint8ListView) bug
