### ISSUE TITLE
Firebase tutorial suggests outdated packages, which do not compile

### ISSUE THREAD

**Issue by robertflesch** [flutter/flutter#15309]
On this page
https://codelabs.developers.google.com/codelabs/flutter-firebase/#4

The pubspec.yaml tells you to use
image_picker: 0.1.1                                             # new
google_sign_in: 0.3.1                                           # new
firebase_analytics: 0.0.4                                       # new
firebase_auth: 0.2.0                                            # new
firebase_database: 0.0.12                                       # new
firebase_storage: 0.0.5                                         # new

which are old, and will not compile, even after two days of trying....

updating them to
  image_picker: 0.2.1                                             # new
  google_sign_in: 2.1.2                                           # new
  firebase_analytics: 0.2.3                                       # new
  firebase_auth: 0.4.7                                            # new
  firebase_database: 0.3.6                                     # new
  firebase_storage: 0.1.4                                         # new

would not cause new users who dont know better to get frustrated.

**Comment by zoechi** [comment]
try running 
```
flutter update-packages --force-upgrade
```
to get `pubspec.yaml` updated

**Comment by robertflesch** [comment]
That may indeed work, but for new users it is not a good solution. Or at least that should be suggested as part of the tutorial, since it will always be behind.

**Comment by tluckett77** [comment]
I'm also stuck in the time-warp of trying to get the right combination of dependencies correct using the aforementioned codelabs as a starting point. 

With this flutter version:
> Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision 5a58b36e36 (3 weeks ago) • 2018-03-13 13:20:13 -0700
> Engine • revision e61bb9ac3a
> Tools • Dart 2.0.0-dev.35.flutter-290c576264 

This will compile
```
  firebase_core: ^0.1.0
  google_sign_in: "^3.0.0"
  firebase_auth: "^0.5.3"
  firebase_analytics: "^0.3.0"
```

But when adding firebase_database, and running get packages. This fails...
```
  firebase_core: ^0.1.0
  google_sign_in: "^3.0.0"
  firebase_auth: "^0.5.3"
  firebase_analytics: "^0.3.0"
  firebase_database: "^0.4.1" # New
```
with the following output (event though 0.4.1 is the latest pub version):
> Package firebase_database has no versions that match >=0.4.1 <0.5.0 derived from:
> - myApp depends on version ^0.4.1
> pub get failed (1)

Then with a lower version of firebase_database...
```
  firebase_core: ^0.1.0
  google_sign_in: "^3.0.0"
  firebase_auth: "^0.5.3"
  firebase_analytics: "^0.3.0"
  firebase_database: ">=0.1.0" // Will pull firebase_database-0.1.4
```
the app simply will not compile and throws the following error. 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> > com.android.build.api.transform.TransformException: Error while generating the main dex list.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 9s

I've run  `flutter update-packages --force-upgrade` to no avail and tried several suggestions from other answers given by @mravn-google and @eseidelGoogle in similar issues but not getting very far.

Any suggestions on how to best handle these conflicting/incompatible plugins?
Is there a chart or page that has information of known working working dependencies for flutter and firebase?

**Comment by mravn-google** [comment]
`firebase_database` has a `firebase_core` dependency, `^0.0.1`, which is inconsistent with your `^0.1.0` requirement. That appears to be a mistake in `firebase_database` which we'll fix asap. In the meantime you can add a dependency override such as the following to your `pubspec.yaml`:

```yaml
dependency_overrides:
  firebase_core: '0.1.2'
```

**Comment by mravn-google** [comment]
(An alternative is to change or remove your own `firebase_core` dependency declaration, letting `firebase_database` decide on an older version)

**Comment by mravn-google** [comment]
The following dependencies should now play nicely together:
```yaml
  firebase_core: ^0.1.0
  google_sign_in: "^3.0.0"
  firebase_auth: "^0.5.3"
  firebase_analytics: "^0.3.0"
  firebase_database: "^0.4.2"
```

**Comment by Hixie** [comment]
cc @Sfshaza

**Comment by Sfshaza** [comment]
This codelab has been obsoleted and replaced by a new Firebase + Flutter codelab (same URL).

Closing

**Comment by kroikie** [comment]
@robertflesch

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/893. Any further collaboration will be done there.
