### ISSUE TITLE
Switch and SwitchListTile missing 'enabled' propriety

### ISSUE THREAD

**Issue by rares45** [flutter/flutter#153018]
### Use case

The Material 3 Guidelines specify a disabled switch state, but the flutter implementation seems to miss it. Affected is also SwitchListTile and SwitchListTile.adaptive.

### Proposal

Implement the disabled state for switches

**Comment by danagbemava-nc** [comment]
Hi @rares45, to disable a switch, you can set the `onChanged` property to null. Are you facing any issues with this implementation?

**Comment by rares45** [comment]
No, good to know. Sorry for not reading with attention the docs.
