### ISSUE TITLE
Firebase Auth Plugin Register

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [flutter/flutter#15308]
Is firebase auth plugin literally just logging in or there are create account options? I cant see docs about this

**Comment by paratout** [comment]
I believe you have to make the view for it, this is the handler :
https://github.com/flutter/plugins/blob/970b69f1f28775277b830fa0e8b953d69bce4d88/packages/firebase_auth/lib/firebase_auth.dart#L144

**Comment by diego-lipinski-de-castro** [comment]
Yeah, it works, I'm blind lol
