### ISSUE TITLE
Icons do not fill their width completely while IconImages do

### ISSUE THREAD

**Issue by KevinCCucumber** [flutter/flutter#153050]
### Steps to reproduce

Create an IconImage that is cropped to its content like so:

<img width="325" alt="image" src="https://github.com/user-attachments/assets/52e927d5-d008-4a00-8d32-4cbeae6e86d1">

### Expected results

The Icon is filling its size to the max

### Actual results

The Icon has a slight offset:
<img width="325" alt="image" src="https://github.com/user-attachments/assets/bf723010-8af6-4b82-96eb-1de2c275807c">

While the imageIcon is filling itself perfectly:
<img width="89" alt="image" src="https://github.com/user-attachments/assets/8a16328f-fb62-4f6b-b07e-878b6f1cdad3">

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @KevinCCucumber 
Please provide a minimal sample code (and image assets corresponding to your demo above) that illustrates the issue. And please provide output of `flutter doctor -v` as well. Thanks!
