### ISSUE TITLE
CarouselView weighted method not defined - Uncontained Model Unavailable in Flutter 3.24

### ISSUE THREAD

**Issue by Tchano-Py** [flutter/flutter#153002]
### Steps to reproduce

Please tell us exactly how to reproduce the problem you are running into.

1. Create a new Flutter project using the command flutter create bug.
2. Replace the content of the main.dart file with the following code:
```dart
import 'package:flutter/material.dart';

class MyCarousel extends StatefulWidget {
  const MyCarousel({super.key});

  @override
  State<MyCarousel> createState() => _MyCarouselState();
}

class _MyCarouselState extends State<MyCarousel> {
  final images = List.generate(
    5,
    (index) => Hero(
      tag: 'image-$index',
      child: Image.asset('assets/image/image-$index.jpg'),
    ),
  );

  @override
  Widget build(BuildContext context) {
    return ConstrainedBox(
      constraints: BoxConstraints(
        maxWidth: MediaQuery.of(context).size.width - 20,
        maxHeight: 250,
      ),
      child: CarouselView.weighted(
        flexWeights: [8, 4, 2],
        itemSnapping: true,
        children: images,
      ),
    );
  }
}
```
3. Run the application on an emulator or physical device.

### Expected results

The CarouselView widget should support the weighted method to adjust the weights of items within the carousel, allowing for flexible control over the display of items.

### Actual results

When attempting to compile the code, the following error occurs:

```rust
The method 'weighted' isn't defined for the type 'CarouselView'.
Try correcting the name to the name of an existing method, or defining a method named 'weighted'.
```
The `CarouselView` does not recognize the weighted method, making it impossible to use the `Uncontained` model.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class MyCarousel extends StatefulWidget {
  const MyCarousel({super.key});

  @override
  State<MyCarousel> createState() => _MyCarouselState();
}

class _MyCarouselState extends State<MyCarousel> {
  final images = List.generate(
    5,
    (index) => Hero(
      tag: 'image-$index',
      child: Image.asset('assets/image/image-$index.jpg'),
    ),
  );

  @override
  Widget build(BuildContext context) {
    return ConstrainedBox(
      constraints: BoxConstraints(
        maxWidth: MediaQuery.of(context).size.width - 20,
        maxHeight: 250,
      ),
      child: CarouselView.weighted(
        flexWeights: [8, 4, 2],
        itemSnapping: true,
        children: images,
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
C:\Users\####>flutter doctor -v
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [versÆo 10.0.22631.3958], locale pt-PT)
    • Flutter version 3.24.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (8 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
```

</details>

**Comment by darshankawar** [comment]
> ```dart
> CarouselView.weighted
> ```

This is currently available on Master channel only. See https://main-api.flutter.dev/flutter/material/CarouselView-class.html

Closing for now.

**Comment by torindev** [comment]
> > ```dart
> > CarouselView.weighted
> > ```
> 
> This is currently available on Master channel only. See https://main-api.flutter.dev/flutter/material/CarouselView-class.html
> 
> Closing for now.

I don't understand why it works like that. **CarouselView** was presented like a part of last flutter sdk update (3.24.0). Also **CarouselView.weighted** method available in documentation here https://main-api.flutter.dev/flutter/material/CarouselView-class.html... for what reason? to be unavailable in Stable channel?
