### ISSUE TITLE
[tool] When shutting down browser, SocketException: The remote computer refused the network connection.  (OS Error: The remote computer refused the network connection. , errno = 1225), address = localhost, port = 59203

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#153064]
This is occurring with frightening frequency in 3.24.0 (63.69% of crashes as of 8/7/24).

Looks like the crash happens here when we try to ask Chrome/Chromium to close:

https://github.com/flutter/flutter/blob/9afd397cd4b996b896cc49fa21d57b60aff6bf70/packages/flutter_tools/lib/src/web/chrome.dart#L510-L511

Command: `flutter run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9100/ --target {path to project directory}\lib\main.dart`

Stack trace:
```
SocketException: The remote computer refused the network connection.
 (OS Error: The remote computer refused the network connection.
, errno = 1225), address = localhost, port = 59203
at _NativeSocket.startConnect(socket_patch.dart:721)
at _RawSocket.startConnect(socket_patch.dart:1920)
at RawSocket.startConnect(socket_patch.dart:27)
at Socket._startConnect(socket_patch.dart:2144)
at Socket.startConnect(socket.dart:825)
at _ConnectionTarget.connect(http_impl.dart:2491)
at _HttpClient._getConnection.connect(http_impl.dart:2930)
at _HttpClient._getConnection(http_impl.dart:2935)
at _HttpClient._openUrl(http_impl.dart:2790)
at _HttpClient.getUrl(http_impl.dart:2632)
at ChromeConnection.getUrl(webkit_inspection_protocol.dart:108)
at ChromeConnection.getTabs(webkit_inspection_protocol.dart:53)
at ChromeConnection.getTab(webkit_inspection_protocol.dart:90)
at Chromium.close(chrome.dart:510)
at ChromiumDevice.stopApp(web_device.dart:164)
at ResidentWebRunner._cleanup(resident_web_runner.dart:203)
at <asynchronous gap>(async)
at ResidentWebRunner.cleanupAtFinish(resident_web_runner.dart:191)
at <asynchronous gap>(async)
at ResidentRunner.waitForAppToFinish(resident_runner.dart:1482)
at <asynchronous gap>(async)
at RunCommand.runCommand(run.dart:788)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1408)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:212)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:420)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:364)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:130)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at main(executable.dart:93)
at <asynchronous gap>(async)
```

**Comment by m3c-fnicola** [comment]
I'm experiencing the same issue, with a similar stack trace.

<details>

```
SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 44452
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22)
#4      Socket.startConnect (dart:io/socket.dart:825:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2632:48)
#10     ChromeConnection.getUrl (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:108:33)
#11     ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:53:26)
#12     ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:90:31)
<asynchronous suspension>
#13     Chromium.close (package:flutter_tools/src/web/chrome.dart:510:30)
<asynchronous suspension>
#14     ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:164:5)
<asynchronous suspension>
#15     ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:203:5)
<asynchronous suspension>
#16     ResidentWebRunner._cleanupAndExit (package:flutter_tools/src/isolated/resident_web_runner.dart:217:5)
<asynchronous suspension>
#17     Future._propagateToListeners.handleWhenCompleteCallback.<anonymous closure> (dart:async/future_impl.dart:854:56)
<asynchronous suspension>
```

</details>

Also, when starting a debug session on VSCode, a Chrome window opens and shows the notification "Flutter: Waiting for connection from debug service on Chrome..." but never completes. When reloading the page on Chrome (F5), the app starts running. I believe this might be related.

**Comment by huycozy** [comment]
This seems to have appeared before with command `flutter debug_adapter`: https://github.com/flutter/flutter/issues/145019

**Comment by andrewkolos** [comment]
https://github.com/flutter/flutter/pull/150645 changed the way the tool tries to shut down Chromium to make it reliable (in terms of actually shutting down chromium), which made it to 3.24.0.

https://github.com/flutter/flutter/pull/151197 wrapped this in a try-catch to handle any SocketException thrown (presumably because Chromium was already shut down). However, this did not make it to 3.24.0. I am attempting to cherry-pick this to stable.

**Comment by andrewkolos** [comment]
This should be fixed when https://github.com/flutter/flutter/pull/153294 makes it to the next hotfix stable release.

**Comment by andrewkolos** [comment]
This appears to still being reported on 3.24.1. The next steps here are to 
1. double-verify that the fix made it 3.24.1
2. reread the fix to see if we can divine why the fix was not sufficient
3. ask users from duplicate issues if they have a way to reliably repro this
4. try fixing this again

**Comment by andrewkolos** [comment]
For anyone reading this that is experiencing this crash, could you tell us what you are doing/seeing when this crash happens? Is it when quitting out of `flutter run` (or stopping debugging through VSCode)?

We need to be able to reproduce this crash to be able to verify that a fix works, and I have not yet found a way to repro this myself.

**Comment by andrewkolos** [comment]
> This appears to still be happening on 3.24.1.

I failed to notice this initially, but on 3.24.1 this happens with a different message: `SocketException: Connection attempt cancelled, host: localhost, port: 62946`.

**Comment by andrewkolos** [comment]
Double checking the fix (https://github.com/flutter/flutter/pull/153294), it should have worked. Check this out (from current stable):

https://github.com/flutter/flutter/blob/cb28dec614e481c5ebde52b545118202200c5d4c/packages/flutter_tools/lib/src/web/chrome.dart#L511-L517

We catch `SocketException`, so either

1) This `SocketException` and the one we are seeing in crash reporting are different types (which I highly doubt—we are catching `SocketException` from `dart:io`, and the thrower also appears to be from `dart:io`). Or,
2) This is some asynchronous funniness going on here (perhaps the exception is being thrown with a manually-provided stack trace, but such exception is thrown asynchronously?).

I'm tempted to use [the tool's `asyncGuard` mechanism](https://github.com/flutter/flutter/blob/9fd9f042fc43dea418dc00d60ad3532faa603b50/packages/flutter_tools/lib/src/base/async_guard.dart#L81) to be sure we protect against 2).

My current plan is to wait another day and see if any users have found a consistent repro for this. Otherwise, I will use `asyncGuard` and throw this into the hotfix and hope this actually fixes the issue.

**Comment by andrewkolos** [comment]
@brianquinlan for Dart expertise. Would you be able to take a quick peek at this to try to figure out why this isn't being caught (see code snippet from my previous comment)? Navigating through the call stack, I don't see anything in the call stack between `at Chromium.close(chrome.dart:512)` (flutter tool) and `at ChromeConnection.getUrl(webkit_inspection_protocol.dart:108)` (package:webkit_inspection_protocol) that would result in this exception escaping the try-catch. I'm starting to wonder if this is an issue in the `dart:io` http library.

**Comment by andrewkolos** [comment]
Filed https://github.com/dart-lang/sdk/issues/56566.

**Comment by andrewkolos** [comment]
The fix here might be modify expand https://github.com/flutter/flutter/pull/153978/files to also catch `SocketException`. We can fix this on master, but I do not plan to cherry-pick this to stable until we are more confident in what the root cause of this issue is (i.e. we have a repro).

**Comment by andrewkolos** [comment]
Reposting this since it got buried:

> For anyone reading this that is experiencing this crash, could you tell us what you are doing/seeing when this crash happens? Is it when quitting out of `flutter run` (or stopping debugging through VSCode)?
> 
> We need to be able to reproduce this crash to be able to verify that a fix works, and I have not yet found a way to repro this myself.

**Comment by andrewkolos** [comment]
I found (an inorganic) way to reproduce this.

1. Checkout the stable branch of flutter/flutter (3.24.1, hash 5874a72aa4c779a02553007c47dacbefba2374dc).
2. Apply the following diff to your clone of flutter using `git apply`:

```diff
diff --git a/packages/flutter_tools/lib/src/web/chrome.dart b/packages/flutter_tools/lib/src/web/chrome.dart
index 996d79c468..bb993fce4e 100644
--- a/packages/flutter_tools/lib/src/web/chrome.dart
+++ b/packages/flutter_tools/lib/src/web/chrome.dart
@@ -504,6 +504,11 @@ class Chromium {
       _chromiumLauncher.currentCompleter = Completer<Chromium>();
     }
 
+    // Repro: simulate the browser closing before we can try to more cleanly
+    // shut it down using package:webkit_inspection_protocol below.
+    ProcessSignal.sigterm.kill(_process);
+    await Future<void>.delayed(const Duration(seconds: 1));
+
     // Send a command to shut down the browser cleanly.
     Duration sigtermDelay = Duration.zero;
     if (_hasValidChromeConnection) {

```
3. Clean out the cached compilation of the flutter tool: `rm -rf bin/cache/flutter_tools*` (from the root directory of your flutter clone)
4. Create a new Flutter web project: `flutter create -e socket_exception --platforms=web`
5. Run the app in browser using VSCode: open the lib/main.dart file and press F5, select the browser as your device
6. After the app has finished starting up, stop the app (e.g. using the Stop button or Shift+F5)
7. After a second, you should see the SocketException reported in the log output.

Interestingly, if you wrap the `chromeConnection.getTab` with `asyncGuard`, clean out the tool cache, `flutter clean` your app, and run again, this won't repro. Here's the diff to apply for testing that:

```diff
diff --git a/packages/flutter_tools/lib/src/web/chrome.dart b/packages/flutter_tools/lib/src/web/chrome.dart
index bb993fce4e..e6ed2a1701 100644
--- a/packages/flutter_tools/lib/src/web/chrome.dart
+++ b/packages/flutter_tools/lib/src/web/chrome.dart
@@ -8,6 +8,7 @@ import 'package:meta/meta.dart';
 import 'package:process/process.dart';
 import 'package:webkit_inspection_protocol/webkit_inspection_protocol.dart';
 
+import '../base/async_guard.dart';
 import '../base/common.dart';
 import '../base/file_system.dart';
 import '../base/io.dart';
@@ -514,8 +515,8 @@ class Chromium {
     if (_hasValidChromeConnection) {
       ChromeTab? tab;
       try {
-        tab = await chromeConnection.getTab(
-            (_) => true, retryFor: const Duration(seconds: 1));
+        tab = await asyncGuard(() => chromeConnection.getTab(
+            (_) => true, retryFor: const Duration(seconds: 1)));
       } on SocketException {
         // Chrome is not responding to the debug protocol and probably has
         // already been closed.
```

I will update https://github.com/dart-lang/sdk/issues/56566 accordingly.

**Comment by brianquinlan** [comment]
If `asyncGuard` fixes the issue then you should definitely go with that!

**Comment by andrewkolos** [comment]
> If `asyncGuard` fixes the issue then you should definitely go with that!

Yep! I just wanted to confirm this was the case, as it makes the case for cherry-picking such a change much stronger.

**Comment by andrewkolos** [comment]
The cherry-pick appears to have worked. This no longer appears in 3.24.3.
