### ISSUE TITLE
AppBar.leading BackButton issue in RTL, flutter version 3.24.0

### ISSUE THREAD

**Issue by erabti** [flutter/flutter#153084]
### Steps to reproduce

1. Run the code sample (RTL mode), I did test an ios simulator, iPhone 15 Plus.

This happens whether you put an explicit BackButton, or use an implied (default) one.

### Expected results

The back button should change the direction for RTL, and should be padded from the right edge.

### Actual results

The button is not padded and seems to be out of bounds of screen a bit, and the direction is not changed.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Directionality(
        textDirection: TextDirection.rtl,
        child: Scaffold(
          appBar: AppBar(
            leading: const BackButton(),
          ),
        ),
      ),
    ),
  );
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/c324815d-19a1-47c0-ab10-a2118d5a8252)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-LY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
[✓] VS Code (version 1.91.1)
```

</details>

**Comment by darshankawar** [comment]
@erabti 
This seems to be working as expected in latest master version, as shown below:

<img width="364" alt="Screenshot 2024-08-08 at 5 28 17 PM" src="https://github.com/user-attachments/assets/9a6a4baf-3110-4616-a5e5-a36875db8283">

You can switch to it and confirm at your end. Since it works well in master, I will close this as fixed.

**Comment by erabti** [comment]
@darshankawar this is a breaking change, is there a plan to include this in a hotfix for the stable version?

**Comment by darshankawar** [comment]
Hot-fix request is open already : https://github.com/flutter/flutter/issues/153037
