### ISSUE TITLE
Inconsistent Text Ranges between TextInputConnection and RichText Rendering

### ISSUE THREAD

**Issue by maoyuliuxin** [flutter/flutter#153071]
### Steps to reproduce

When using TextInputConnection, it was discovered that the calculated text range is inconsistent with the range rendered by RichText. The input cursor of TextInputConnection is smaller than that displayed by RichText, which causes the IME input to not align with the cursor. This issue was observed on August 8th, 2024 (Thursday).

### Expected results

When using TextInputConnection, the expected behavior is that the cursor position should be consistent with that in RichText.

### Actual results

When using TextInputConnection, it was discovered that the calculated text range is inconsistent with the range rendered by RichText. The input cursor of TextInputConnection is smaller than that displayed by RichText, which causes the IME input to not align with the cursor. 

### Code sample

TextInputConnection与Text

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [版本 10.0.22631.3880], locale zh-CN)
    • Flutter version 3.22.3 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

**Comment by darshankawar** [comment]
@maoyuliuxin 
Please provide complete reproducible code sample along with current behavior versus expected result you are looking for.
