### ISSUE TITLE
Random crashes when turning VOiceOver on/off

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#15304]
While the app is running I am seeing random crashes when turning VoiceOver on/off. There doesn't seem to be a pattern. Sometimes it crashes, other times it doesn't :(

/cc @yjbanov

**Comment by yjbanov** [comment]
Yep, I can reproduce this on any screen. I'll take a look.

**Comment by yjbanov** [comment]
Reassigning to @chinmaygarde who is about to send a PR for this.

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/engine/pull/4761
