### ISSUE TITLE
Unable to Split Localization .arb Files into Multiple Categories

### ISSUE THREAD

**Issue by wshehab99** [flutter/flutter#153087]
### Use case

In the current app development process, we are unable to split our localization .arb files into multiple files for better categorization, such as separating error messages, general messages, and other text strings. This limitation hinders our ability to maintain a well-organized and scalable localization structure.

### Proposal

- Enable the inclusion of multiple .arb files with the same suffix (e.g., *_en.arb).
- Introduce wildcard patterns in the template-arb-file parameter (e.g., template-arb-file: "*_en.arb") to include all matching .arb files.

The relevant changes could be made [here](https://github.com/flutter/flutter/blob/f3717d70d7d2660ed830835c8ee33a01af71ce08/packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart#L532)

**Comment by darshankawar** [comment]
Looks like similar to https://github.com/flutter/flutter/issues/107157, so please follow-up in it for further updates.
Closing as duplicate.
