### ISSUE TITLE
[CP] Fix incorrect padding in drawVertices with texture coordinates

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#153038]
### Issue Link

https://github.com/flutter/flutter/issues/151355

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/54399

### Changelog Description

* Fix incorrect padding in Canvas.drawVertices when using texture coordinates

### Impacted Users

Impeller iOS/Android using mesh gradient package

### Impact Description

Rendering has incorrect single pixel padding

### Workaround

Use Skia

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached tests

**Comment by zanderso** [comment]
cp lgtm
