### ISSUE TITLE
When I run flutter doctor these errors occurs 

### ISSUE THREAD

**Issue by WaqasAhmed001** [flutter/flutter#153019]
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Error: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 )
      is removed from the PATH environment variable. Ensure that this is present and then try again after restarting the
      terminal and/or IDE.
[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "powershell" in the search path.
        Command: powershell

**Comment by danagbemava-nc** [comment]
Hi, Thanks for filing this issue.
From the error message:

```
Error: Cannot find the executable for where. This can happen if the System32 folder (e.g.
C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try
again after restarting the terminal and/or IDE.
```

Kindly ensure you follow the exact step-by-step process in setting up flutter on your system. More specifically to update your PATH, see [docs.flutter.dev/get-started/install/windows#update-your-path](https://docs.flutter.dev/get-started/install/windows#update-your-path)

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
