### ISSUE TITLE
[Impeller] Gather detailed memory statistics via service protocol when running Vulkan.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#153062]
Its possible to get detailed memory statistics of a running application when using Vulkan and have them be [visualized offline](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/tools/GpuMemDumpVis/README.md).

The process of gathering the data is rather clumsy today as the engine needs to be patched to dump the JSON to logs and then get that scraped for visualization.

Create a service protocol extension to get detailed allocator information at at given point in time.

**Comment by jonahwilliams** [comment]
Closing as we already have some statistics and the vma data is not useful without more tagging.
