### ISSUE TITLE
When CircularProgressIndicator's value is null, it paints nothing instead of displaying a loading spinner

### ISSUE THREAD

**Issue by paolosoares** [flutter/flutter#15315]
Running this app:

    runApp(
      new MaterialApp(
        home: new Scaffold(
          body: new Center(
            child: new CircularProgressIndicator(),
          ),
        ),
      ),
    );

I expected to see a circular spinner on the center of the screen, since [CircularProgressIndicator's documentation says:](https://docs.flutter.io/flutter/material/CircularProgressIndicator-class.html)

> Indeterminate. Indeterminate progress indicators do not have a specific value at each point in time and instead indicate that progress is being made without indicating how much progress remains. To create an indeterminate progress indicator, use a null value.

However, all I see is a blank screen.

Looking at [_CircularProgressIndicatorPainter](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/progress_indicator.dart), I see that it doesn't do any special handling for "value == null" besides changing the stroke cap, possibly to not paint a dot:

    @override
    void paint(Canvas canvas, Size size) {
      final Paint paint = new Paint()
        ..color = valueColor
        ..strokeWidth = strokeWidth
        ..style = PaintingStyle.stroke;

      if (value == null) // Indeterminate
        paint.strokeCap = StrokeCap.square;

      canvas.drawArc(Offset.zero & size, arcStart, arcSweep, false, paint);
    }

**Comment by paolosoares** [comment]
Actually, I've just found out that it behaves just fine on other clients. I'm trying to track down what's different on my setup.

**Comment by tvolkert** [comment]
We use a null value in the gallery, and it correctly spins:

https://github.com/flutter/flutter/blob/d996ab921c25cb4bbfa32b179bf32ab1e6353c22/examples/flutter_gallery/lib/demo/material/progress_indicator_demo.dart#L76

Could it be that no animations are running in your case?  Maybe you need a vsync?

@HansMuller

**Comment by paolosoares** [comment]
Found it: I didn't enable OpenGL when starting the emulator.
