### ISSUE TITLE
Colors.grey.withOpacity function disappeared after upgrade 3.24 

### ISSUE THREAD

**Issue by b3lon9** [flutter/flutter#153128]
### Steps to reproduce

`color: Colors.grey.withOpacity(0.9)` code..
I don't know which replace it

### Expected results

wish have .withOpacity function

### Actual results

not work

### Code sample

<details open><summary>Code</summary>

```dart
 hintStyle: TextStyle(
        color: Colors.grey.withOpacity(0.9),
        fontSize: 16.0,
      ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by mansourzaki** [comment]
Hi @b3lon9 sorry for having this issue but it seems to be working on 3.24 stable channel

can you please share the output of Flutter doctor and tell us on which channel you are facing this issue.

**Comment by danagbemava-nc** [comment]
Hi @b3lon9, as noted above, Colors.grey.withOpacity still works on the latest version of flutter. Can you provide a complete example that reproduces the issue?

**Comment by b3lon9** [comment]
> Hi @b3lon9, sorry for having this issue but it seems to be working on 3.24 stable channel
> 
> can you please share the output of Flutter doctor and tell us on which channel you are facing this issue.

**Comment by b3lon9** [comment]
@mansourzaki today night I will reply flutter-doctor contents.
now I check 3.24 SDK in window os that is really fine.
Color.grey.opacity(0.9) not work issue occured from mac os.
maybe it might be fine.. don't worry too much about it.
Im sorry comment too late.
