### ISSUE TITLE
TextField Weird behavior on flutter web android Keyboard

### ISSUE THREAD

**Issue by libeuk** [flutter/flutter#153151]
### Steps to reproduce

1.It's a Flutter web app
2.Issue only exists in Flutter multilane textfield
<img width="345" alt="Screenshot 2024-08-09 at 10 04 38" src="https://github.com/user-attachments/assets/d116ee1a-fb1b-403a-be29-1d99195db3e8">
3.Rendering issue on android browser.
4. Lot's of Space/Gap between Keyboard and textfield + Weird behaviour of Cursor only on android browser.

### Expected results

Cusror should displayed on the same line.

### Actual results

Cursor starts to appear to second line when typing starts .

### Code sample

<details open><summary>Code sample</summary>

```dart
TextField(
        decoration: InputDecoration(
          border: OutlineInputBorder(),
          labelText: 'Enter your text here',
        ),
        keyboardType: TextInputType.multiline,
        maxLines: 10,
        maxLength: 800,
        minLines: null,
      )
```

</details>

### Screenshots or Video

[Screen_recording_20240809_100411.webm](https://github.com/user-attachments/assets/612f57b4-b000-4a84-8382-afd3612433ea)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @libeuk 
This reminds me of a similar issue at https://github.com/flutter/flutter/issues/148271 but I don't see you input CJK characters from your video. Not sure if you have specific settings for your keyboard, can you recheck and confirm?

**Comment by libeuk** [comment]
@huycozy I have tested on multiple android browsers. but the result is still same. There is no CJK characters used.

**Comment by huycozy** [comment]
I tried again with English keyboard but couldn't see the issue. 

![Screenshot 2024-08-12 at 11 58 26](https://github.com/user-attachments/assets/e711238a-4e5d-466c-b54d-01e8d835c6dd)

I'm on the latest Flutter stable release 3.24.0, can you try upgrade Flutter SDK and retry?

**Comment by toco1001** [comment]
I encountered the same issue in Flutter versions 3.22.0 and 3.24.0 when typing multi-byte text (Japanese), but it doesn't happen when typing in English.

**Comment by huycozy** [comment]
@toco1001 Please follow https://github.com/flutter/flutter/issues/148271.

**Comment by parancode** [comment]
Don't you modify 'Web renderer' because it's going to be discarded?
Is 3.19.6 the best version of a project with 'Web renderer'?

**Comment by parancode** [comment]
> '웹 렌더러'는 폐기되므로 수정하지 않습니까?
> 3.19.6이 '웹 렌더러'프로젝트의 최고의 버전입니까'?

**Comment by parancode** [comment]
> @toco1001 Please follow #148271.

Don't you modify 'Web renderer' because it's going to be discarded?
Is 3.19.6 the best version of a project with 'Web renderer'?

**Comment by libeuk** [comment]
> I encountered the same issue in Flutter versions 3.22.0 and 3.24.0 when typing multi-byte text (Japanese), but it doesn't happen when typing in English.
> 
> Doctor summary (to see all details, run flutter doctor -v): [!] Flutter (Channel [user-branch], 3.22.2, on macOS 13.5 22G74 darwin-arm64, locale en-JP) [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3) [✓] Xcode - develop for iOS and macOS (Xcode 15.2) [✓] Chrome - develop for the web [✓] Android Studio (version 2022.3) [✓] VS Code (version 1.92.2) [✓] Connected device (5 available) [✓] Network resources



> I tried again with English keyboard but couldn't see the issue.
> 
> ![Screenshot 2024-08-12 at 11 58 26](https://private-user-images.githubusercontent.com/104349824/356938779-e711238a-4e5d-466c-b54d-01e8d835c6dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTU4NTMsIm5iZiI6MTcyNDA1NTU1MywicGF0aCI6Ii8xMDQzNDk4MjQvMzU2OTM4Nzc5LWU3MTEyMzhhLTRlNWQtNDY2Yy1iNTRkLTAxZThkODM1YzZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwODE5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmY5MjFhYTFlNmExNWM4OTcwN2Q2ZTRhZDUwYmQ5MDE4Y2FkYjZiNGQ0ZDU5NzUwM2JjNjM0Y2JhYjlkNDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cr7VqRJKY4WDxLPJS3fVHO4wdKmwuO9XSLDc9xlAulg)
> 
> I'm on the latest Flutter stable release 3.24.0, can you try upgrade Flutter SDK and retry?


unfortunately i cannot upgrade the flutter  version now. Some of my libraries are are yet to upgrade to the latest versions.

**Comment by huycozy** [comment]
>unfortunately i cannot upgrade the flutter version now. Some of my libraries are are yet to upgrade to the latest versions.

Please check on a simple sample code only. It should have only one TextField as provided sample code.

**Comment by parancode** [comment]
> > unfortunately i cannot upgrade the flutter version now. Some of my libraries are are yet to upgrade to the latest versions.
> 
> Please check on a simple sample code only. It should have only one TextField as provided sample code. If you want to setup multiple Flutter SDKs, please check [this](https://stackoverflow.com/questions/55783494/how-can-i-use-two-versions-of-flutter-on-the-same-device-for-different-projects).

This is what happens when you use the web-render option in Flutter 3.22 and later versions. (Canvaskit is normal)

Also, I use a Korean-enabled keyboard.
It doesn't happen when it's an English keyboard
It is believed to occur in Korean or other languages.

**Comment by kkruel8100** [comment]
This is occurring on an in English keyboard on Android device.
Samsung Tab Active 5
Flutter version 3.22.2
Note: I have found some Android devices where it functions as normal. For example, Active 3 behaves normally. But Active 5 does not.
So this does occur on English keyboard.
Getting similar behavior that is displayed in video.
