### ISSUE TITLE
ClipOval and ColorFiltered with ColorFilter.mode not working with Impeller in iOS simulator with Flutter 3.24.0

### ISSUE THREAD

**Issue by DFelten** [flutter/flutter#153146]
### Steps to reproduce

1. Use Flutter 3.24.0
2. Enable Impeller 
3. Create ClipOval with ColorFiltered widget and a child (or run the example)

-> ClipOval is not working with ColorFiltered.

4. disable Impeller via Info.plist

```
<key>FLTEnableImpeller</key>
<false/>
```

-> ClipOval is working with ColorFiltered.

It seems that the bug only appears in the simulator. On my real device it seems to work. We've tested it on several MacBooks.

Example repository for the impeller bug: https://github.com/DFelten/flutter_impeller_asset_bug

### Expected results

Content within ClipOval is clipped (round).

### Actual results

Content within ClipOval is not clipped and a square.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Impeller iOS Asset Bug',
      theme: ThemeData(
        scaffoldBackgroundColor: Colors.red,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    final colorFilter = ColorFilter.mode(Colors.grey, BlendMode.color);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Impeller iOS Asset Bug'),
      ),
      body: Center(
        child: Column(
          children: [
            ClipOval(
              child: ColorFiltered(
                colorFilter: colorFilter,
                child: Container(
                  color: Colors.green,
                  height: 200,
                  width: 200,
                ),
              ),
            ),
            const Padding(padding: EdgeInsets.all(12.0)),
            ClipOval(
              child: ColorFiltered(
                colorFilter: colorFilter,
                child: Image.asset('assets/guest_avatar_logo.png'),
              ),
            ),
            const Padding(padding: EdgeInsets.all(12.0)),
            ClipOval(
              child: ColorFiltered(
                colorFilter: colorFilter,
                child: Image.network(
                    'https://www.dealdoktor.de/app/uploads/2024/07/Bosch_Professinal_Uni-300x300.png'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>With Impeller enabled</summary>

![Simulator Screenshot - iPhone 15 Pro - 2024-08-09 at 09 25 36](https://github.com/user-attachments/assets/a440613a-8fee-4a49-97fc-90347940cd2e)

</details>

<details open>
<summary>With Impeller disabled</summary>

![Simulator Screenshot - iPhone 15 Pro - 2024-08-09 at 09 24 14](https://github.com/user-attachments/assets/f63daf96-1f21-4e15-aeef-1c80bb5193ad)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] VS Code (version 1.90.1)
[✓] VS Code (version 1.93.0-insider)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for Apple Watch von Daniel. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @DFelten,
This seems to be similar to https://github.com/flutter/flutter/issues/153118#issuecomment-2277542828:

<details>
<summary>Screenshot</summary>

<img width="400" src="https://github.com/user-attachments/assets/23c8c7ad-72d1-47cf-b61e-65d7db8f49bf">

</details>

Please try switching to master channel and confirm.

**Comment by DFelten** [comment]
Yes, on the master branch it seems to work on the simulator.

![Simulator Screenshot - iPhone 15 Pro - 2024-08-09 at 11 51 29](https://github.com/user-attachments/assets/82f62781-2f03-405a-bd43-f9b719da42af)

**Comment by huycozy** [comment]
Thanks for confirming this. Closing as fixed.

**Comment by huycozy** [comment]
I reopened https://github.com/flutter/flutter/issues/153118 for team's attention. I think that and this issue has the same cause, so please follow it for updates. Thanks!
