### ISSUE TITLE
Just tried the flutter_gallery example, not working out of the box

### ISSUE THREAD

**Issue by mrbm** [flutter/flutter#15318]
## Steps to Reproduce

set up the most recent flutter_gallery demo, run the commend:

flutter package get

## Logs

/Users/noname/android-sdks/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in flutter_gallery...
Package collection has no versions that match 1.14.5 derived from:
- async 2.0.4 depends on version ^1.5.0
- barback 0.15.2+14 depends on version ^1.5.0
- boolean_selector 1.0.3 depends on version ^1.5.0
- crypto 2.0.2+1 depends on version ^1.0.0
- flutter 0.0.0 depends on version 1.14.5
- flutter_gallery depends on version 1.14.6
pub get failed (1)
Process finished with exit code 1

## Flutter Doctor

/Users/noname/android-sdks/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio
[✓] Android Studio (version 3.0)
[✓] Android Studio
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0

**Comment by mrbm** [comment]
and never mind. I was running flutter from the beta and not the master and flutter didn't like that which confused me...so disregard. I love flutter!

**Comment by shunmugam303** [comment]
It is working, on the master flutter
