### ISSUE TITLE
Change in dart:io writeln behavior causing engine -> framework roll failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#153163]
Starting with https://github.com/flutter/flutter/pull/153148, which contains only the Dart -> Engine roll with commits: https://dart.googlesource.com/sdk.git/+log/9222e4c96f4d..1cc09f3f3642, the engine is failing to roll to the framework. The failures are in Flutter CLI tests that check strings emitted on streams match expected values as in:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8740097201632391153/+/u/run_test.dart_for_tool_tests_shard_and_subshard_general/stdout

It looks like the change that led to this was: https://dart.googlesource.com/sdk.git/+/e8c035308bec001af477d644f3a5c396dedc94ff

cc @a-siva.

I think we could probably just update the string expectations of the tests in the framework.

**Comment by aam** [comment]
The fix for the test have landed https://github.com/flutter/flutter/pull/153147

**Comment by zanderso** [comment]
I'm seeing some more instances like here https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_tests_commands/38940/overview, so we may have to chase this a bit further.
