### ISSUE TITLE
Replace some Moto G4's attached to windows hosts with mokey's

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#153127]
The Moto G4 devices attached to windows hosts in staging are currently unused by any test, and we can safely replace them with mokey devices. These hosts are:

flutter-win-5
flutter-win-6

**Comment by kentnguyen99** [comment]
Swapping Moto G4 phone devices with new Mokey phones are done. All new phone devices are online and ready for service.

**Comment by zanderso** [comment]
This was for https://github.com/flutter/flutter/issues/148085, and is completed.
