### ISSUE TITLE
Error: The getter 'button' isn't defined for the class 'TextTheme' 

### ISSUE THREAD

**Issue by xinnian25** [flutter/flutter#153135]
run flutter build apk 
Report an error 
How to solve it?

`Task :app:compileFlutterBuildDebug
../../../.pub-cache/hosted/pub.flutter-io.cn/pin_code_fields-7.4.0/lib/src/pin_code_fields.dart:669:56: Error: The getter 'button' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'button'.
                    color: Theme.of(context).textTheme.button!.color,
                                                       ^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/pin_code_fields-7.4.0/lib/src/pin_code_fields.dart:679:60: Error: The getter 'button' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'button'.
                        color: Theme.of(context).textTheme.button!.color,

Caused by: org.gradle.process.internal.ExecException: Process 'command '/Users/guanglong/flutter/bin/flutter'' finished with non-zero exit value 1`

**Comment by gillycodes** [comment]
@xinnian25 Pls how did you solve this Error: The getter 'button' isn't defined for the class 'TextTheme'.
