### ISSUE TITLE
[Impeller] Add FAQ entries.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#153120]
From @sethladd, for https://github.com/flutter/engine/blob/c25cf09d6dd891ad80f9434d5d800cc1049ef8bf/impeller/docs/faq.md

* Why did the Flutter team build Impeller?
* What makes Impeller different, compared to Skia, for Flutter?
* Describe Impeller in a Tweet.

**Comment by sethladd** [comment]
Thanks @chinmaygarde for the updates!
