### ISSUE TITLE
Some matrices decomposed incorrectly, causing slight tilt on Fuchsia

### ISSUE THREAD

**Issue by mikejurka** [flutter/flutter#15319]
## Steps to Reproduce

Run Fuchsia (topaz or vendor/google flavor) on a Pixelbook.

It's extremely subtle but the entire UI is slightly rotated.
If I manually set the pixel ratio to 2.f, I don't see the issue. However the default pixel ratio on this device that we use is 1.7734....

It seems that we're taking a SkMatrix which already has its decomposition information, converting into a SkMatrix44, and then decomposing. Why don't we preserve the information in the original matrix?

Here is some logging I added:

[00358.069] 05754.06061> [INFO:scene_update_context.cc(262)] SceneUpdateContext::Transform: Matrix [  1.7734   0.0000   0.0000]‌[  0.0000   1.7734   0.0000]‌[  0.0000   0.0000   1.0000] has a z rotation of 0.000172633

You can add this to scene_update_context.cc:260

    SkString s;
    transform.toString(&s);
    FXL_LOG(INFO) << "SceneUpdateContext::Transform: Matrix "
                  << std::string(s.c_str()) << " has a z rotation of "
                  << decomposition.rotation().fData[2];

**Comment by tvolkert** [comment]
@chinmaygarde thoughts?

**Comment by Hixie** [comment]
Does this happen on other platforms too, or just fuchsia? Is it just a matter of the device pixel ratio on that device being unusually awkward?

**Comment by mikejurka** [comment]
I think the latter. It works fine with other ratios (e.g. 2.f)

**Comment by Hixie** [comment]
We do not consider this an especially high priority given the workaround, but we hope to work on this once our current fires have been put out.

**Comment by Hixie** [comment]
We continue to be aware of this issue but not work on it. This is on our radar for when the higher priority issues are resolved. Please let us know if this rises in priority. Thanks.

**Comment by Hixie** [comment]
This is unlikely to be worked on in the next month. It continues to be on our radar. Thank you for your patience.

**Comment by Hixie** [comment]
We briefly looked at this recently but did not find a conclusive cause.
This continues to be on our radar but not something we are likely to get to in the coming month.

**Comment by Hixie** [comment]
@mikejurka @tvolkert Is this still a blocker?

**Comment by tvolkert** [comment]
I defer to @mikejurka

**Comment by mikejurka** [comment]
Yes, still continues to render UI incorrectly on Fuchsia and is a blocker.

**Comment by Hixie** [comment]
Have you tried using a slightly different pixel ratio?

**Comment by mikejurka** [comment]
When I tried with a ratio of 2.0 it worked fine; I haven't tried using one that's an epsilon away.

The pixel ratio isn't a hardcoded value, however; it's calculated at run-time using a formula that takes the physical parameters (dimensions, pixel density, distance of the user from display) of the device as an input.

**Comment by GaryQian** [comment]
A (very sketchy) workaround that seems to temporarily resolve the issue is just to explicitly set the z rotation to 0 whenever the z rotation is exactly 0.00017263349f. This seems to work on all scales > 0.000245.

In the meantime, I will attempt to find a more legitimate fix.

**Comment by mikejurka** [comment]
thank you!

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/commit/c765bee59d88f50f443639ef30f28b8878b58efb

**Comment by cbracken** [comment]
@GaryQian is there a Skia tracking bug for the normalise issue so that when it's fixed we can revert back to their implementation?
