### ISSUE TITLE
GPU access using engine built with `--disable-desktop-embeddings`

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#153196]
### Steps to reproduce

@bdero 

1. switch to main channel
2. Build flutter engine (main) using `--runtime-mode=debug --embedder-for-target --enable-fontconfig --disable-desktop-embeddings --no-build-embedder-examples --enable-impeller-3d --no-lto --no-goma --no-rbe --no-stripped --no-enable-unittests`
3. Follow steps in this article to create and run app: https://medium.com/flutter/getting-started-with-flutter-gpu-f33d497b7c11

### Expected results

Expect symbols to be exported by engine build

### Actual results

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following ArgumentError was thrown during paint():
Invalid argument(s): Couldn't resolve native function 'InternalFlutterGpu_Context_InitializeDefault'
in 'package:flutter_gpu/gpu.dart' : No asset with id 'package:flutter_gpu/gpu.dart' found. No
available native assets. Attempted to fallback to process lookup.
.desktop-homescreen/lib/libflutter_engine.so: undefined symbol:
InternalFlutterGpu_Context_InitializeDefault.
```
Indicates the build is not exporting the symbols even though
```
#define FLUTTER_GPU_EXPORT __attribute__((visibility("default")))
...
FLUTTER_GPU_EXPORT
extern Dart_Handle InternalFlutterGpu_Context_InitializeDefault(
    Dart_Handle wrapper);
```
flutter_test is correctly exporting the GPU symbols.

I'm using this to list symbols
```
nm -S flutter_tester  | c++filt |grep InternalFlutterGpu
nm -S libflutter_engine.so  | c++filt |grep InternalFlutterGpu
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jonahwilliams** [comment]
Closing as I believe this was fixed in https://github.com/flutter/engine/pull/54662
