### ISSUE TITLE
[shared_preferences] Remove legacy testing section from README

### ISSUE THREAD

**Issue by Huluk** [flutter/flutter#153108]
### What package does this bug report belong to?

shared_preferences

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

The documentation says that it is recommended to use `SharedPreferencesWithCache` or `SharedPreferencesAsync`, but all example tests, documentation, and API references do not provide information on how to use these APIs in tests. Tests do not pass by default, or with the old setup for `SharedPreferences`.

### Expected results

Testing is documented or works out of the box.

### Actual results

No testing documentation is available and UI tests fail with the following error:
`Bad state: The SharedPreferencesAsyncPlatform instance must be set.`

### Code sample

<details open><summary>Old test setup:</summary>

```dart
    SharedPreferences.setMockInitialValues({});
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-CH)
    • Flutter version 3.22.3 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.13.8/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (vor 3 Wochen), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huluk/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huluk/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64 •
      Android 14 (API 34) (emulator)
    • iPh12mH (mobile)                • 00008101-000E031E1190001E • ios           • iOS
      17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64  • macOS
      14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin        • macOS
      14.4.1 23E224 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
This is being tracked in https://github.com/flutter/flutter/issues/150732, so please follow-up in it for further updates.
Closing this as a duplicate.

**Comment by muzzah** [comment]
Im not sure why this was closed @darshankawar as calling ```SharedPreferences.setMockInitialValues({});``` does not fix the issue mentioned here. This is not a migration issue. 

I am currently calling ```SharedPreferencesWithCache.create(cacheOptions: const SharedPreferencesWithCacheOptions());``` and then calling ```SharedPreferences.setMockInitialValues({});``` but the error mentioned above is still happening.

**Comment by muzzah** [comment]
As a workaround I added the following for my tests during initialisation

```
import 'package:shared_preferences_platform_interface/shared_preferences_async_platform_interface.dart';
import 'package:shared_preferences_platform_interface/in_memory_shared_preferences_async.dart';

 SharedPreferencesAsyncPlatform.instance = InMemorySharedPreferencesAsync.empty();
```

**Comment by Huluk** [comment]
Agreed, I don't have trouble migrating. I have a working setup with `SharedPreferencesWithCache` in prod.

However, I can no longer run any tests because `SharedPreferences.setMockInitialValues({});` only works for the old `SharedPreferences` API. All the example tests and test documentation use this old API. There is no documented setup for testing code using the new API.

**Comment by muzzah** [comment]
@Huluk As mentioned above you can manually set the missing in memory instance to have an inmemory shared preferences during tests which should resolve the issue until the dev team fix this.

**Comment by Huluk** [comment]
Thank you @muzzah! That works, thank you! I was initially confused that `SharedPreferencesWithCache` would take up the Async in memory instance, but they seem to collaborate well. I assume the cached version is internally backed by the async one? I added `shared_preferences_platform_interface` as a dev dependency only, since it's only needed for testing.

@darshankawar The solution by @muzzah would be only a workaround for testing interfaces without extra dependencies. Documentation is needed in any case.

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening and labeling for team's tracking.

**Comment by stuartmorgan-g** [comment]
We should remove https://pub.dev/packages/shared_preferences#testing since it's only applicable to the legacy version.

We don't plan to maintain custom docs for testing this plugin; https://docs.flutter.dev/testing/plugins-in-tests explains how to handle plugins in general. `shared_preferences` is not unique in testing strategy. In particular:

> ### Expected results
> Testing is documented or works out of the box.

is not true for any plugin, essentially.

([This comment above](https://github.com/flutter/flutter/issues/153108#issuecomment-2278456305) corresponds to the third method on that page.)

**Comment by Huluk** [comment]
That makes sense! I think it would still be a good idea to replace the test in the example project with one using the new API.
