### ISSUE TITLE
[shared_perferences] `getStringList` in new APIs doesn't work correctly on Windows/Linux

### ISSUE THREAD

**Issue by paulober** [flutter/flutter#153106]
### Steps to reproduce

Use `getStringList` with `SharedPreferencesAsync` on Windowx 64.

A workaround would be to use the legacy API again :)
```dart
final prefs = await SharedPreferences.getInstance();
summaryList = prefs.getStringList(settingsKey) ?? [];
```

### Expected results

It works.

### Actual results

Type Error:
```
type 'List<dynamic>' is not a subtype of type 'List<String>?' in type cast
```

### Code sample

<details open><summary>Code sample</summary>

```dart
static Future<List<Summary>> loadSummaries() async {
    final prefs = SharedPreferencesAsync();
    try {
      final summaryList = await prefs.getStringList('summaryList') ?? [];

      return summaryList.map((jsonString) {
        final jsonMap = jsonDecode(jsonString);
        return Summary.fromJson(jsonMap);
      }).toList();
    } catch (e) {
      if (e is TypeError) {
        debugPrint("[Summary] SummaryList is corrupted: $e");
      }
      return [];
    }
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3958], locale de-DE)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
```

</details>

**Comment by stuartmorgan** [comment]
From offline discussion: this is basically the same problem (caused by the same bad logic in my review) as https://github.com/flutter/flutter/issues/152607, but in new code at the platform implementation level.
