### ISSUE TITLE
Sample flutter app does not display properly in pixel 2 API 25 emulator

### ISSUE THREAD

**Issue by pkreddy04** [flutter/flutter#15313]
## Steps to Reproduce

- Installed Flutter by following the steps
- Used Android studio IDE
- Built and ran the app on the Android emulator (pixel 2 API 25)
- **See issue with app not being displayed properly in the emulator** (When i used a note 4 android 6.1 phone, there was no issue with the app display)

## Logs

Run your application with `flutter run` and attach all the log output.
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk (24.6MB).

Run `flutter analyze` and attach any output of that command also.
Analyzing C:\pkr\test\Android\flutter_app...
No issues found!
Ran in 7.3s

## Flutter Doctor

[ΓêÜ] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 6.3.9600], locale en-US)
    ΓÇó Flutter version 0.1.5 at C:\pkr\Tech\Flutter\flutter
    ΓÇó Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    ΓÇó Engine revision ead227f118
    ΓÇó Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[ΓêÜ] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    ΓÇó Android SDK at C:\Users\preddy\AppData\Local\Android\sdk
    ΓÇó Android NDK at C:\Users\preddy\AppData\Local\Android\sdk\ndk-bundle
    ΓÇó Platform android-27, build-tools 26.0.2
    ΓÇó ANDROID_HOME = C:\Users\preddy\AppData\Local\Android\sdk
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[ΓêÜ] Android Studio (version 3.0)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] VS Code (version 1.21.0)
    ΓÇó VS Code at C:\Program Files (x86)\Microsoft VS Code
    ΓÇó Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[ΓêÜ] Connected devices (1 available)
    ΓÇó Android SDK built for x86 ΓÇó emulator-5554 ΓÇó android-x86 ΓÇó Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.

**Comment by chinmaygarde** [comment]
I believe this is due to OpenGL emulation issues on the AVD. You can try switching to software rendering using `flutter run --enable-software-rendering`. Filed https://github.com/flutter/flutter/issues/15451 to consider making this the default.

**Comment by pkreddy04** [comment]
Thanks, now the app is displayed in the emulator with no issues
