### ISSUE TITLE
Video Duration Limit of Video Recording Ignored on Android 11 with Image Picker Plugin

### ISSUE THREAD

**Issue by wsharif92** [flutter/flutter#153144]
### Steps to reproduce

1. Initialize the Image Picker plugin in a Flutter project.
2. Set the maxDuration parameter for video recording to 15 seconds.
3. Deploy the app on an Android 11 device.
4. Start recording a video using the Image Picker.
5. Observe the behavior when the recording reaches 15 seconds.

### Expected results

The video recording should automatically stop at 15 seconds, as specified by the maxDuration parameter.

### Actual results

The video recording continues indefinitely beyond the 15-second limit on Android 11 devices, not respecting the maxDuration parameter. This issue is not present on iOS devices and Android 13, where recording stops correctly at 15 seconds.

### Code sample

final pickedFile = await ImagePicker().pickVideo(
          source: ImageSource.camera, maxDuration:  Duration(seconds: 14));

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.22.2 on channel stable at /Users/wakassharif/Developer/flutter310
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (9 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wakassharif/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/wakassharif/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/wakassharif/Library/Android/sdk/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ android-studio-dir = /Users/wakassharif/Library/Android/sdk
    ✗ Android Studio not found at /Users/wakassharif/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

**Comment by darshankawar** [comment]
@wsharif92 Even though I don't have physical device with Android 11 version, but I tried by creating emulator of same configuration, ran image_picker plugin example which has set duration of 10 seconds. I selected `ImageSource.camera` with which the video recording lasted for set duration as expected. See below which shows the video I recorded which stopped at 10 seconds.


https://github.com/user-attachments/assets/ed7c3fcb-d328-43f8-9764-f130efe5d61f

Can you check if there's any device setting that could be leading to the behavior since you said it only occurs in Android 11 ?

There's a similar issue open but for `ImageSource.gallery` : https://github.com/flutter/flutter/issues/83630

**Comment by stuartmorgan** [comment]
Also, what is the exact device that you are testing with? The behavior of the video picker intent handler (including whether it honors this option) is entirely controlled by the application handling the intent. So for instance, a device with a non-standard OEM picker intent handler may not choose to support the limit.
