### ISSUE TITLE
Replace Moto G4's attached to Windows prod hosts with mokey's

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#153197]
The Moto G4's attached to the following hosts can be replaced with mokey's

flutter-win-1
flutter-win-2
flutter-win-3
flutter-win-4

The Moto G4's can then be discarded.

**Comment by kentnguyen99** [comment]
Swapping out old Moto G4 phone devices with new Mokey phones are done. All new phone devices are online and ready for service.

**Comment by zanderso** [comment]
The new phones are successfully running tests. Closing.

**Comment by zanderso** [comment]
This was for https://github.com/flutter/flutter/issues/148085
