### ISSUE TITLE
How to modify the language for suggest created a strong password on iOS

### ISSUE THREAD

**Issue by lidong-jimi** [flutter/flutter#153263]
### Steps to reproduce

The current mobile phone system is in Japanese.
When registering and calling TextInput.finishAutofillContext(), an English suggestion pops up to generate a strong password prompt.
But when logging in, a Japanese password saving prompt will pop up.
Can we also change the prompt for strong passwords to Japanese？

### Actual results

<img width="215" alt="register" src="https://github.com/user-attachments/assets/061ab21f-0de6-4ca0-bb9f-212f29dc6925">
<img width="291" alt="login" src="https://github.com/user-attachments/assets/57cd9ac4-ba51-4480-9eae-fb56a1287071">

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.2 23C64 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.24.0 on channel stable at
      /Users/apple/Library/Flutter/flutter_3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (13 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-34, build-tools 35.0.0
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • iPhone 15 (mobile)              • B4C452ED-AD9A-4F12-9D45-009334CC99B5 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • iPhone 15 Pro Max (mobile)      • 770ED060-AFCE-4CE5-A128-F94205178663 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @lidong-jimi 
This sounds like an interesting scenario. Can you check how the behavior is in native iOS ? Whether the strong password dialog is shown in Japanese or in locale ?

**Comment by lidong-jimi** [comment]
@darshankawar 
Thanks for your reply.
Has anyone else encountered such a situation before？
![image](https://github.com/user-attachments/assets/e645f80d-43de-4c2c-b844-8aa48a7ae287)

**Comment by darshankawar** [comment]
I think the dialog you are getting in English about strong password created, comes from iCloud keychain:

https://support.apple.com/en-us/109016

Do you have that setting enabled in your phone ? If so, if you disable it, can you check if it helps in your case or not ?

**Comment by lidong-jimi** [comment]
@darshankawar 
If cloud keychain is turned off, the prompt to create a strong password will not pop up.

**Comment by lidong-jimi** [comment]
@darshankawar 
Adding localization in iOS can solve this problem. thank you.

**Comment by lidong-jimi** [comment]
@darshankawar 
Could you solve this problem #116889

**Comment by darshankawar** [comment]
> Adding localization in iOS can solve this problem. thank you.

Good to know. Will close this as resolved.

> Could you solve this problem #116889

Please follow-up in that issue. It is prioritized as P2 so will be fixed accordingly.
