### ISSUE TITLE
Since Flutter 3.24, application does not build and run integration tests on MacOS

### ISSUE THREAD

**Issue by AndreasMaita** [flutter/flutter#153268]
### Steps to reproduce

1. create a dummy project
2. add below to dev_dependencies.
``` 
integration_test:
   sdk: flutter
```
3. create a file ```application_test.dart``` under a folder ```integration_test``` with the following contents:
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:integration_test_example/main.dart';

void main () {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group("end-to-end test", () {
    testWidgets("tap on the floating action button, verify counter", (tester) async {
      await tester.pumpWidget(const MyApp());
      // Verify the counter starts at 0.
      expect(find.text('0'), findsOneWidget);

      // Finds the floating action button to tap on.
      final fab = find.byKey(const ValueKey('increment'));

      // Emulate a tap on the floating action button.
      await tester.tap(fab);

      // Trigger a frame.
      await tester.pumpAndSettle();

      // Verify the counter increments by 1.
      expect(find.text('1'), findsOneWidget);
    });
  });
}
```

4. run the tests.

## Background Information
What i have found out, is that even when starting the application main.dart, i get this error:

```Launching lib/main.dart on macOS in debug mode...
Building macOS application...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006021-001C71C82243C01E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006021-001C71C82243C01E, name:My Mac }
building file list ... done
deleting App.framework/Versions/A/_CodeSignature/CodeResources
deleting App.framework/Versions/A/_CodeSignature/
App.framework/Versions/A/
App.framework/Versions/A/App

sent 17470 bytes  received 48 bytes  35036.00 bytes/sec
total size is 50571904  speedup is 2886.85
building file list ... done
FlutterMacOS.framework/Versions/A/
FlutterMacOS.framework/Versions/A/FlutterMacOS
FlutterMacOS.framework/Versions/A/_CodeSignature/CodeResources

sent 52269084 bytes  received 70 bytes  104538308.00 bytes/sec
total size is 53041798  speedup is 1.01
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/App.framework/App: replacing existing signature
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/App.framework/App: signed bundle with Mach-O thin (arm64) [io.flutter.flutter.app]
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: replacing existing signature
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: signed bundle with Mach-O universal (arm64) [io.flutter.flutter-macos]
building file list ... done

sent 73 bytes  received 20 bytes  62.00 bytes/sec
total size is 0  speedup is 0.00
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/*.framework: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Error: Build process failed
```

a quick google search, brought me to some checkboxes in XCode:
![image](https://github.com/user-attachments/assets/d6d1cd88-f3a4-4e11-b961-d16beeea51a3)

When these 2 checkboxes are active, the application builds without problems. However, the integration tests still dont run, but just start the application without actually running the tests.

### Expected results

It is expected, that the integration tests start running and assert my ```expect(find.text('1'), findsOneWidget);```for example.

### Actual results

When the Checkboxes are set (as described in background information) the tests just start the application without acutally running the tests.

When the Checkboxes are not set, the tests fail to run with the following message, and gets stuck:
![image](https://github.com/user-attachments/assets/4e33244d-e8ae-4b9d-8837-3ddc1ce83f6d)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] IntelliJ IDEA Community Edition (version 2023.3.2)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by AndreasMaita** [comment]
@darshankawar thank you so much for your quick response. This issue was fixed by updating XCode to the newest version. Again thank you for your support, im going to close this issue for now

**Comment by AndreasMaita** [comment]
Dear @darshankawar,

Unfortunately, the issue was not entirely solved by upgrading XCode. I still have the follwing Issue when running my application (see steps to reproduce above):
```
Launching lib/main.dart on macOS in debug mode...
Running pod install...
Building macOS application...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006021-001C71C82243C01E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006021-001C71C82243C01E, name:My Mac }
building file list ... done
deleting App.framework/Versions/A/_CodeSignature/CodeResources
deleting App.framework/Versions/A/_CodeSignature/
App.framework/Versions/A/
App.framework/Versions/A/App
App.framework/Versions/A/Resources/Info.plist
App.framework/Versions/A/Resources/flutter_assets/AssetManifest.bin
App.framework/Versions/A/Resources/flutter_assets/AssetManifest.json
App.framework/Versions/A/Resources/flutter_assets/FontManifest.json
App.framework/Versions/A/Resources/flutter_assets/NOTICES.Z
App.framework/Versions/A/Resources/flutter_assets/kernel_blob.bin
App.framework/Versions/A/Resources/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
App.framework/Versions/A/Resources/flutter_assets/shaders/
App.framework/Versions/A/Resources/flutter_assets/shaders/ink_sparkle.frag

sent 38401556 bytes  received 230 bytes  76803572.00 bytes/sec
total size is 50571936  speedup is 1.32
building file list ... done
FlutterMacOS.framework/Versions/A/
FlutterMacOS.framework/Versions/A/FlutterMacOS
FlutterMacOS.framework/Versions/A/_CodeSignature/CodeResources

sent 52269084 bytes  received 70 bytes  104538308.00 bytes/sec
total size is 53041798  speedup is 1.01
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/App.framework/App: replacing existing signature
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/App.framework/App: signed bundle with Mach-O thin (arm64) [io.flutter.flutter.app]
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: replacing existing signature
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: signed bundle with Mach-O universal (arm64) [io.flutter.flutter-macos]
building file list ... done

sent 73 bytes  received 20 bytes  186.00 bytes/sec
total size is 0  speedup is 0.00
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/*.framework: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Error: Build process failed
```

it looks like this issue is related to these Release Notes -> https://github.com/flutter/flutter/pull/148580
 -> https://github.com/flutter/flutter/pull/148580
 -> https://github.com/flutter/engine/pull/52930
 -> https://github.com/flutter/engine/pull/52961

**Comment by AndreasMaita** [comment]
The permissions for these folders are as follows:
![image](https://github.com/user-attachments/assets/4b7a9aea-4617-4b43-9aa8-54b896aa6c21)

I changed the permissions with this command:
```sudo chmod -R 777 /Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app```

now when i try to run the application i get:
![image](https://github.com/user-attachments/assets/10bb9e83-77f3-4dc1-b64c-d5ed2683883e)

which is again under the above folder that was originally not permitted to read.

It looks like the permissions are not set correctly be the linked issues.

**Comment by darshankawar** [comment]
Thanks for the update. I followed the steps and ran on my macOS machine with which I didn't get the observed behavior, the test runs (but fails) but didn't throw the build errors:

<details>
<summary> console log </summary>

```

dhs@Dhss-MacBook-Pro integration_dummy % flutter test integration_test/integration_test.dart
Connected devices:
macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
Chrome (web)    • chrome • web-javascript • Google Chrome 127.0.6533.120

No wireless devices were found.

[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (or "q" to quit): 1
00:04 +0: loading /Users/dhs/Documents/NCFlutter/integration_dummy/integration_test/integration_test.dart                                                                  R00:05 +0: loading /Users/dhs/Documents/NCFlutter/integration_dummy/integration_test/integration_test.dart                                                           1,355ms
00:07 +0: loading /Users/dhs/Documents/NCFlutter/integration_dummy/integration_test/integration_test.dart                                                                  B00:39 +0: loading /Users/dhs/Documents/NCFlutter/integration_dummy/integration_test/integration_test.dart                                                                  
✓ Built build/storybook/macos/Build/Products/Debug/integration_dummy.app
00:43 +0: end-to-end test tap on the floating action button, verify counter                                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "Found 0 widgets with key [<'increment'>]: []" (used in a call to "tap()") could not find
any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1892:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1792:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:1040:18)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/integration_dummy/integration_test/integration_test.dart:19:20)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  tap on the floating action button, verify counter
════════════════════════════════════════════════════════════════════════════════════════════════════
00:43 +0 -1: end-to-end test tap on the floating action button, verify counter [E]                                                                                         
  Test failed. See exception logs above.
  The test description was: tap on the floating action button, verify counter
  

To run this test again: /Users/dhs/documents/fluttersdk/flutter/bin/cache/dart-sdk/bin/dart test /Users/dhs/Documents/NCFlutter/integration_dummy/integration_test/integration_test.dart -p vm --plain-name 'end-to-end test tap on the floating action button, verify counter'
00:43 +0 -1: Some tests failed.                                                                                                                                            
dhs@Dhss-MacBook-Pro integration_dummy % 

```

</details>


I am on Intel mac. Can you provide your macOS details. Are there any external permissions such as keychain access which could be preventing it ?

**Comment by mono0926** [comment]
In my case, the issue was resolved by running `flutter clean`.

**Comment by AndreasMaita** [comment]
> Thanks for the update. I followed the steps and ran on my macOS machine with which I didn't get the observed behavior, the test runs (but fails) but didn't throw the build errors:
> 
>  console log
> I am on Intel mac. Can you provide your macOS details. Are there any external permissions such as keychain access which could be preventing it ?

I run on a MacOS m2 silicon. I don’t have any keychain access settings set. Unfortunately, this issue persists even after running flutter clean.

what version of Xcode are you running?

**Comment by huycozy** [comment]
>which is again under the above folder that was originally not permitted to read.

@AndreasMaita Does the test run well after granting the right permissions? I'm using macOS 14.6 and XCode 15.4, on Flutter 3.24.0 but the test can run normally.

**Comment by AndreasMaita** [comment]
Hi @huycozy, im also using MacoOS 14.6 and XCode 15.4 and flutter 3.24.0.

No, unfortunately after giving the right permissions manually, get the following 
![image](https://github.com/user-attachments/assets/3b132f3c-1dc5-4f57-8e4c-e1f0731c4c5a)

Unfortunately it does not affect only the tests, but the building of the application itself. Are there some relevant XCode Settings that i need to put right?

**Comment by huycozy** [comment]
Regarding the XCode setting on Run script, did you modify it? Because of I see it's different than my setting here (it's default Flutter project):

![Screenshot 2024-08-20 at 10 48 48](https://github.com/user-attachments/assets/6200b7eb-0a2e-4c27-a2cb-e536fb209025)

Please retry on a newly created Flutter project and confirm.

**Comment by AndreasMaita** [comment]
I have used set the XCode Run Script settings to default, which now allows the application to start at least. However the integration_tests halt, waiting forever while showing the following error:
<img width="1701" alt="image" src="https://github.com/user-attachments/assets/076c67bf-d454-4a4a-a0da-d810e4d0a02f">

I tested it in a newly created Flutter project.

**Comment by huycozy** [comment]
Is that all the error? Can you please provide the entire error output if any? Please provide the output in text format instead of a screenshot for better readability and investigation, see [avoid posting screenshots of text](https://github.com/flutter/flutter/wiki/Issue-hygiene#avoid-posting-screenshots-of-text).

**Comment by AndreasMaita** [comment]
unfortunately this is all i get. as you can see from the screenshot, the Running tests... is still spinning, still waiting to do something.

only when interrupting the test, i get the following output:
/Users/amaita/fvm/versions/stable/bin/flutter --no-color test --machine --start-paused -d macos integration_test/application_test.dart
Testing started at 12:02 ...
Building macOS application...                                   
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006021-001C71C82243C01E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006021-001C71C82243C01E, name:My Mac }
building file list ... done
deleting App.framework/Versions/A/_CodeSignature/CodeResources
deleting App.framework/Versions/A/_CodeSignature/
App.framework/Versions/A/
App.framework/Versions/A/App
App.framework/Versions/A/Resources/Info.plist
App.framework/Versions/A/Resources/flutter_assets/AssetManifest.bin
App.framework/Versions/A/Resources/flutter_assets/AssetManifest.json
App.framework/Versions/A/Resources/flutter_assets/FontManifest.json
App.framework/Versions/A/Resources/flutter_assets/NOTICES.Z
App.framework/Versions/A/Resources/flutter_assets/kernel_blob.bin
App.framework/Versions/A/Resources/flutter_assets/shaders/
App.framework/Versions/A/Resources/flutter_assets/shaders/ink_sparkle.frag

sent 42238146 bytes  received 208 bytes  84476708.00 bytes/sec
total size is 54665728  speedup is 1.29
building file list ... done
FlutterMacOS.framework/Versions/A/
FlutterMacOS.framework/Versions/A/FlutterMacOS
FlutterMacOS.framework/Versions/A/_CodeSignature/CodeResources

sent 52269084 bytes  received 70 bytes  104538308.00 bytes/sec
total size is 53041798  speedup is 1.01
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/App.framework/App: replacing existing signature
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/App.framework/App: signed bundle with Mach-O thin (arm64) [io.flutter.flutter.app]
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: replacing existing signature
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: signed bundle with Mach-O universal (arm64) [io.flutter.flutter-macos]
building file list ... done
./

sent 79 bytes  received 26 bytes  210.00 bytes/sec
total size is 0  speedup is 0.00
/Users/amaita/Workspace/private/integration_test_example/build/macos/Build/Products/Debug/integration_test_example.app/Contents/Frameworks/*.framework: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

package:flutter_tools/src/base/common.dart 10:3                    throwToolExit
package:flutter_tools/src/macos/build_macos.dart 200:5             buildMacOS
===== asynchronous gap ===========================
package:flutter_tools/src/macos/macos_device.dart 75:5             MacOSDevice.buildForDevice
===== asynchronous gap ===========================
package:flutter_tools/src/desktop_device.dart 121:7                DesktopDevice.startApp
===== asynchronous gap ===========================
package:flutter_tools/src/test/integration_test_device.dart 55:39  IntegrationTestTestDevice.start

Error: Build process failed

**Comment by huycozy** [comment]
Thanks for your update. I will label this issue for the insights from others.

**Comment by huycozy** [comment]
@AndreasMaita Per discussion at a similar issue https://github.com/flutter/flutter/issues/153842, looks like this is fixed on Flutter beta/master channel, see https://github.com/flutter/flutter/issues/153842#issuecomment-2303653053. Can you try switching to beta/master and retry?

**Comment by AndreasMaita** [comment]
Dear @huycozy, by changing the flutter channel to beta, i could not reproduce my issue again!

Thank you so much for your investigative help. I will close this issue. Any Clue on when the fix will be oficially released?

**Comment by huycozy** [comment]
@AndreasMaita Thank you for confirming this. Please follow the CP link above, it could be released on the next stable. Closing this as fixed on beta channel.
