### ISSUE TITLE
Navigating from A to B (which has a nav bar) - HOW? (Typed-routing)

### ISSUE THREAD

**Issue by renanboni** [flutter/flutter#153204]
Hi there, hope you are all doing well.

My app has a simple requirement: a login screen and a main screen with a bottom nav bar, there is a button in the login screen that sends me to the main screen. (
I wanted to make it with type-safe routes so if someone could please shed some light I'd be extremely grateful.) 

I researched this A LOT on the internet and couldn't find one single example of this use case - _on the other hand, the documentation covers the super complex use case of navigating from A to B but wait - passing a string! yay!_ 

Thanks a lot for reading it through.

**Comment by brainwo** [comment]
Hi, this is issue page of Flutter, here we report issues related to the Flutter SDK, Flutter official packages, and Flutter's website. This isn't a good place for discussion as you may have noticed when you create a new issue here.

![image](https://github.com/user-attachments/assets/6732ad61-d678-4d0c-9c5d-e40cbe770544)

For a question like this, it's better to ask in one of our community communication channel. We are on Reddit, Discord, Stackoverflow, and many more. Please check https://flutter.dev/community and join the community you prefer. Cheers.

(Disclaimer, I'm not working on Flutter, I'm just a community member who is active in contributing to this community, this is just a friendly notice)

**Comment by darshankawar** [comment]
@renanboni 
Please ask support questions on StackOverflow or Flutter's reddit help page.
