### ISSUE TITLE
After upgrading to 3.24.0 the android release build is broken on several packages giving the error "AAPT: error: resource android:attr/lStar not found."

### ISSUE THREAD

**Issue by dickverweij** [flutter/flutter#153281]
## Latest update

We believe the correct solution is for plugins to update their compileSdk version, and for apps to pull in these changes from pub, but also there is a workaround in https://github.com/flutter/flutter/issues/153281#issuecomment-2292201697.

### Steps to reproduce

1. create a flutter test application
2. add a dependency to an affected package.
3. run flutter build apk

packages affected so far:

[mixpanel_flutter](https://pub.dev/packages/mixpanel_flutter)
[charset_converter](https://pub.dev/packages/charset_converter)
[image_gallery_saver](https://pub.dev/packages/image_gallery_saver)
[airplane_mode_checker](https://pub.dev/packages/airplane_mode_checker)
[fk_user_agent](https://pub.dev/packages/fk_user_agent)
[livekit_client](https://pub.dev/packages/livekit_client)
[flutter_barcode_scanner](https://pub.dev/packages/flutter_barcode_scanner)

### Expected results

compile a release version of the app

### Actual results

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mixpanel_flutter:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\dvy\source\repos\tst\build\mixpanel_flutter\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.

### Code sample

<details open><summary>Code sample</summary>

flutter create tst<br/>
flutter pub add mixpanel_flutter<br/>
flutter build apk<br/>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS C:\Users\dvy\source\repos\tst> flutter doctor -v
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3880], locale nl-NL)
    • Flutter version 3.24.0 on channel stable at C:\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (13 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\dvy\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = C:\Users\dvy\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio2\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.10.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.10.35027.167
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.92.0)
    • VS Code at C:\Users\dvy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] VS Code, 64-bit edition (version unknown)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.94.0
    X Unable to determine VS Code version.

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.89
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 127.0.2651.98

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by moffatman** [comment]
To fix each package, they can update to `compileSdkVersion 34`. But I would be interested if there is some fix to flutter itself so that old patches can be used without forking.

**Comment by darshankawar** [comment]
Although I do see the same error upon adding mixpanel_flutter plugin, I came across [this](https://github.com/mixpanel/mixpanel-flutter/issues/152) issue from that repo which may be a part of solution.
@moffatman what do you think ? And curious to know what potential fix would from Flutter side for such issues ?

**Comment by rafampessoa** [comment]
Same here

**Comment by moffatman** [comment]
I got no idea not an Android engineer just giving a solution I found worked

**Comment by jpolstre** [comment]
Is there any news? Or For now, all that remains is to downgrade to Flutter 3.22.3, as many packages are becoming obsolete.

**Comment by darshankawar** [comment]
I think the solution is to upgrade individual / listed packages to compileSdkVersion to 34, as mentioned in one of the impacted packages : https://github.com/pr0gramista/charset_converter/issues/40#issuecomment-2282932050

**Comment by dickverweij** [comment]
Yeah sure, but what if the package is no longer maintained. We use a lot of those packages, and forking everyone of them is a hassle. (and de-forking them if they have upgraded their compileSdkVersion)  . 

Also the error **stops** the build process. if you found one "obsolete" package, forked it and fixed the compileSdkVersion you must run "flutter build apk" again to find the next one. This fixes it for all packages.

**Comment by Aziz-T** [comment]
It's related to the compileSdkVersion and targetSdkVersion of the plugins. When I found the source files of the plugins and made the compileSdkVersion and targetSdkVersion the same as my project's, the problem was solved. It is not a very healthy method, but it can be done temporarily to build an apk.

![src](https://github.com/user-attachments/assets/2d5a1aad-8098-43c7-be8b-eb80f55ef7fb)

**Comment by dummest** [comment]
> This seems to work on my build.
> 
> Adding a second "subprojects block" (inserted before the existing, so we won't get the 'Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.' error)
> 
> ![image](https://private-user-images.githubusercontent.com/8133838/357690042-fc81800a-3ba7-4b58-a47f-bd0bf4faa78f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjEyNTgsIm5iZiI6MTcyMzYyMDk1OCwicGF0aCI6Ii84MTMzODM4LzM1NzY5MDA0Mi1mYzgxODAwYS0zYmE3LTRiNTgtYTQ3Zi1iZDBiZjRmYWE3OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMDczNTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU5MDc0NGU3NmQ3NTA3OTFlYzNkNTI4YzI0MDRiZDNmMGE5MjVhM2MyNDE5NmU1NDcwYmM4Zjk2ZjkwYTIwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7yzoCB8_a2JMUUvQuw53o1HotPCyD276nGbpAAWh6Fo)

this comment saved me. thx
but i'm not sure why this happened.
Is this a bug? or is this some kind of 'update' and we should be bypass like this after version 3.24.0?

**Comment by dickverweij** [comment]
> > This seems to work on my build.
> > Adding a second "subprojects block" (inserted before the existing, so we won't get the 'Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.' error)
> > ![image](https://private-user-images.githubusercontent.com/8133838/357690042-fc81800a-3ba7-4b58-a47f-bd0bf4faa78f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjEyNTgsIm5iZiI6MTcyMzYyMDk1OCwicGF0aCI6Ii84MTMzODM4LzM1NzY5MDA0Mi1mYzgxODAwYS0zYmE3LTRiNTgtYTQ3Zi1iZDBiZjRmYWE3OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMDczNTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU5MDc0NGU3NmQ3NTA3OTFlYzNkNTI4YzI0MDRiZDNmMGE5MjVhM2MyNDE5NmU1NDcwYmM4Zjk2ZjkwYTIwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7yzoCB8_a2JMUUvQuw53o1HotPCyD276nGbpAAWh6Fo)
> 
> this comment saved me. thx but i'm not sure why this happened. Is this a bug? or is this some kind of 'update' and we should be bypass like this after version 3.24.0?

Perhaps it  has something to do that api level 34 is now [mandatory](https://developer.android.com/google/play/requirements/target-sdk) for play releases? 
Also an incentive to only use "newer" packages..

**Comment by marcusee** [comment]
I upgraded cupertino_icons to the latest version and it works now hope this helps someone.

**Comment by darshankawar** [comment]
Based on the report, I will keep this open and label for team's attention / tracking.

**Comment by pasBone** [comment]
I encountered the same problem, I don’t know how to solve it, I am very anxious

**Comment by yvbbrjdr** [comment]
I downgraded Flutter to 3.22.3 and it seems to work.

**Comment by dickverweij** [comment]
> I encountered the same problem, I don’t know how to solve it, I am very anxious

This should work. place it above your existing subprojects entry 

``
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34                
            }
        }
    }
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}
``

**Comment by gmackall** [comment]
It looks like this was likely due to the [upgrade to AndroidX dependencies](https://github.com/flutter/engine/pull/53592), it seems like newer versions of these libraries [require compileSdk 31+](https://issuetracker.google.com/issues/199180389#comment3)

**Comment by gmackall** [comment]
Dynamically modifying the `compileSdk` versions of plugins is dangerous. We believe the correct solution is for plugins to update their `compileSdk` version, and for apps to pull in these changes from pub.

That said, if you are looking for a workaround now, similar to the one posted by @dickverweij in [this comment](https://github.com/flutter/flutter/issues/153281#issuecomment-2291115797), we'd suggest replacing your subprojects block in your `<project_root>/android/build.gradle` with something along the lines of:
```
subprojects {
    afterEvaluate { project ->
        if (project.extensions.findByName("android") != null) {
            Integer pluginCompileSdk = project.android.compileSdk
            if (pluginCompileSdk != null && pluginCompileSdk < 31) {
                project.logger.error(
                        "Warning: Overriding compileSdk version in Flutter plugin: "
                                + project.name
                                + " from "
                                + pluginCompileSdk
                                + " to 31 (to work around https://issuetracker.google.com/issues/199180389)."
                                + "\nIf there is not a new version of " + project.name + ", consider filing an issue against "
                                + project.name
                                + " to increase their compileSdk to the latest (otherwise try updating to the latest version)."
                )
                project.android {
                    compileSdk 31
                }
            }
        }
    }
    
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}
```

The benefits being:
- It bumps the compileSdk of the plugins the smallest amount to resolve the issue we see here.
- It doesn't affect plugins that don't need changes.
- It prints the plugins that are affected (otherwise this is hard to debug).
- It verifies all values/extensions exist before referencing them, and only requires one subprojects block.

**Comment by dickverweij** [comment]
Thanks @gmackall , this is great! The only thing you need it to place it in a seperate subprojects . Otherwise you get this error:

`Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.`

like this:

```
subprojects {
.... your workaround script
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

```
and now we get nicely all the outdated packages in our project.. THANKS!

```
Warning: Overriding compileSdk version in Flutter plugin: dual_screen from 30 to 31 (to work around https://issuetracker.google.com/issues/199180389).
If there is not a new version of dual_screen, consider filing an issue against dual_screen to increase their compileSdk to the latest (otherwise try updating to the latest version).
Warning: Overriding compileSdk version in Flutter plugin: fk_user_agent from 30 to 31 (to work around https://issuetracker.google.com/issues/199180389).
If there is not a new version of fk_user_agent, consider filing an issue against fk_user_agent to increase their compileSdk to the latest (otherwise try updating to the latest version).
Warning: Overriding compileSdk version in Flutter plugin: mixpanel_flutter from 30 to 31 (to work around https://issuetracker.google.com/issues/199180389).
If there is not a new version of mixpanel_flutter, consider filing an issue against mixpanel_flutter to increase their compileSdk to the latest (otherwise try updating to the latest version).



```

**Comment by reidbaker** [comment]
> project.evaluationDependsOn(":app")

In our reproduction (gray and I paired on this) we found that the only requirement was that the `afterEvaluate` block needed to be before `project.evaluationDependsOn(":app")`
