### ISSUE TITLE
Checking for asset existence at runtime?

### ISSUE THREAD

**Issue by sameer** [flutter/flutter#15325]
Is there any way to check whether an asset exists at runtime?

I have some NetworkImages that take some time to load. I want to use placeholder image assets,**if they exist**, to show a low-res version until the NetworkImage is loaded. I can do this without the exists part using a FadeInImage.

I've been toying around with variations on this:
```dart
Future<bool> assetExists(String asset) {
  // Ok to load it, because it will be cached and is guaranteed to be used later anyways
  return rootBundle.load(asset).then((_) => true).catchError(() => false);
}
```
But catchError doesn't seem to catch the FlutterError thrown by the root asset bundle when the asset DNE.

Is there something I'm missing? Would I have to write a custom asset bundle class to get this kind of functionality?

**Comment by Hixie** [comment]
Our solution here should probably be similar to our solution for https://github.com/flutter/flutter/issues/14089.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/9676.

**Comment by jonahwilliams** [comment]
This could potentially be addressed by the changes in https://github.com/flutter/flutter/pull/17614.

**Comment by zoechi** [comment]
@Hixie I'm wondering why the `p: framework` label is applied here. Is this a mistake or do I miss something?

**Comment by Hixie** [comment]
@zoechi I messed up, meant to add `framework`. oops!

**Comment by andrewkolos** [comment]
Closing as fixed by https://github.com/flutter/flutter/commit/2b8f2d05045590cd4aeb9f02c67baaa69db35e5e. The [`AssetManifest`](https://api.flutter.dev/flutter/services/AssetManifest-class.html) class provides the means to list assets from an `AssetBundle` (though I can't help but feel that this API is not as discoverable as `AssetBundle`).
