### ISSUE TITLE
Installed flutter using git,did set path variables and installed plugins in android studio. But when I start a new project it never ends. Its building symbols forever. 

### ISSUE THREAD

**Issue by srujangeek** [flutter/flutter#15328]
It says in the messages

"C:program files\flutter\bin\flutter.bat" --no-color create --template app --description "A new flutter application."  --org com.your company flutter_appgh

**Comment by FelschR** [comment]
Having the same problem here. Also in Android Studio.

**Comment by srujangeek** [comment]
After a lot of stumbling I got it right. First of all delete your previous cloned flutter files and install git in your user folder. Like C:\users\username\

Clone flutter in your git directory,set the path C:\users\username\git\flutter\bin

Now use the command flutter doctor If you have android studio and intellij IDE, install flutter plugins in both of them and now create a new project.

You are all set to go

**Comment by simonunger** [comment]
My guess was it was launching a command line task, and the command line task didn't have sufficient permission to make changes to the system.

To fix it, I quit Android Studio and then restarted as an Administrator (Right Click on Icon > More > Run as Administrator).  The create project function then worked first time for me.

**Comment by zoechi** [comment]
@simonunger You shouldn't need that. If you need to run as an Administrator there is either something wrong with your setup or with Flutter.

**Comment by phtwo** [comment]
@simonunger  Run as Administrator, and it's work.

**Comment by zoechi** [comment]
@srujangeek can this issue be closed?
