### ISSUE TITLE
Assets/ should include all subfolders

### ISSUE THREAD

**Issue by Eglusaxie** [flutter/flutter#153212]
### Use case

The thing is, I have been learning to develop applications using Flutter recently, using the recommended VSCode and debugging on the Windows platform. Everything went smoothly until I encountered this problem: my VSCode kept reminding me that the assets folder did not exist.
![image](https://github.com/user-attachments/assets/b4bfebce-d93e-4ad6-9216-73b1e94664b1)
And then I kept trying to create the directory or fix the path to the directory.
Of course, it is useless.
Then I searched online for solutions.
I wasted a lot of time, but in the end, I finally realized where the problem lies.
“Assets/” does not include subfolders? Why is that?
And this warning prompt is very misleading, my path and folder are undoubtedly correct.
Moreover, it's not even empty inside, it contains multiple subfolders.
This makes me feel absurd and frustrated, and I hope you will consider this issue.

### Proposal

Perhaps we can consider doing an path matching like : “assets/**”

**Comment by iapicca** [comment]
I'm not sure I'm hitting the same issue @Eglusaxie is describing
but this used to work

### step to reproduce

- `flutter create --platform web issue_153212`
- `cd issue_153212/`
- `mkdir -p assets/text && echo hello >> assets/text/hello.txt`
- copy `main.dart` and `pubspec.yaml` as below
- `flutter run -d chrome`

### logs

```console
flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...              8.0s
This app is linked to the debug service: ws://127.0.0.1:55051/9yYI-GrQiWA=/ws
Debug service listening on ws://127.0.0.1:55051/9yYI-GrQiWA=/ws

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

A Dart VM Service on Chrome is available at: http://127.0.0.1:55051/9yYI-GrQiWA=
Error while trying to load an asset: Flutter Web engine failed to fetch "assets/assets/text/hello.txt". HTTP request succeeded, but the server responded with HTTP status 404.
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:55051/9yYI-GrQiWA=
Error: Unable to load asset: "assets/text/hello.txt".
The asset does not exist or has empty data.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
packages/flutter/src/services/asset_bundle.dart 327:9                        <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 163:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 861:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 890:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 666:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 736:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

Application finished.
```


<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final text = await rootBundle.loadString('assets/text/hello.txt');
  // ignore: avoid_print
  print(text);
  runApp(
    MaterialApp(
      home: Material(
        child: Center(
          child: Text(
            text,
          ),
        ),
      ),
    ),
  );
}

```
</details>


<details>
  <summary>pubspec</summary>
  
```yaml
name: issue_153212
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

```

</details>


<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (11 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by Eglusaxie** [comment]
![image](https://github.com/user-attachments/assets/3e7bb595-80d1-4f0d-8a60-4887d8f06b82)
![image](https://github.com/user-attachments/assets/20264c89-7101-4eb4-b85b-79879e69fb44)
I also tried it and the results were different from yours.
Your results do not seem to match the description in the document.
https://docs.flutter.dev/ui/assets/assets-and-images#specifying-assets
![image](https://github.com/user-attachments/assets/99d69d85-f20f-473a-af7a-8391e108fa92)

**Comment by Eglusaxie** [comment]
If the normal situation is as described in the document, then I don't think it's reasonable. This means that developers need to configure every single subfolder separately, which is very cumbersome and error prone.
In fact, there is a package specifically for this.
https://pub.dev/packages/asset_fill
pub points：160.

**Comment by Eglusaxie** [comment]
> I cannot reproduce the issue
> 
> ```yaml
> flutter:
>   uses-material-design: true
>   assets:
>     - assets/
> ```
> 
> seems to include the sub-folder as well
> 
> ### to reproduce
> * `flutter create --platform web issue_153212`
> * `cd issue_153212/`
> * `mkdir -p assets/text && echo hello >> assets/text/hello.txt`
> * copy `main.dart` and `pubspec.yaml` as below
> * `flutter run -d chrome`
> 
> code sample
> pubspec
> doctor

Oh, I'm sorry, I just didn't successfully execute the create folder command, I didn't pay attention to that. After I manually created the folder, the program worked properly.
![image](https://github.com/user-attachments/assets/bf301fb4-2d86-466d-b811-0c83ff7ea0d3)
Great, now I have even more questions.

**Comment by Eglusaxie** [comment]
> I cannot reproduce the issue
> 
> ```yaml
> flutter:
>   uses-material-design: true
>   assets:
>     - assets/
> ```
> 
> seems to include the sub-folder as well
> 
> ### to reproduce
> * `flutter create --platform web issue_153212`
> * `cd issue_153212/`
> * `mkdir -p assets/text && echo hello >> assets/text/hello.txt`
> * copy `main.dart` and `pubspec.yaml` as below
> * `flutter run -d chrome`
> 
> code sample
> pubspec
> doctor
![image](https://github.com/user-attachments/assets/1dc25cc3-1aa7-4cb7-8cae-5c359d0a3cf6)
When I ran it in Chrome using the command line, my results were consistent with yours, but when I executed it on the Windows platform using VSCode, the problem reappeared.

**Comment by Eglusaxie** [comment]
This issue seems unrelated to VSCode. I just used VSCode to debug in Chrome, and the result also includes subfolders.

**Comment by Eglusaxie** [comment]
I thought this was a feature of Flutter, but it seems like a bug.

**Comment by darshankawar** [comment]
@Eglusaxie 
You need to provide the complete path of the assets. In your case based on the screenshot provided [above](https://github.com/flutter/flutter/issues/153212#issuecomment-2282238948), try with `assets/text/hello.txt`.
Also make sure the filename syntax is correct.
Check https://github.com/dnfield/flutter_svg/issues/974 for reference.

**Comment by iapicca** [comment]
> @Eglusaxie You need to provide the complete path of the assets. In your case based on the screenshot provided [above](https://github.com/flutter/flutter/issues/153212#issuecomment-2282238948), try with `assets/text/hello.txt`. [...]

[yes and no](https://github.com/flutter/flutter/issues/67655), just keep in mind what is running as `--release` and what not

**Comment by Eglusaxie** [comment]
> @Eglusaxie You need to provide the complete path of the assets. In your case based on the screenshot provided [above](https://github.com/flutter/flutter/issues/153212#issuecomment-2282238948), try with `assets/text/hello.txt`. Also make sure the filename syntax is correct. Check [dnfield/flutter_svg#974](https://github.com/dnfield/flutter_svg/issues/974) for reference.

![image](https://github.com/user-attachments/assets/20b2cf1e-d24a-493d-a853-79f93451bb70)

**Comment by darshankawar** [comment]
@Eglusaxie 
As mentioned in the rootBundle [documentation](https://api.flutter.dev/flutter/services/rootBundle.html), try following to see if it helps in your case or not:

<img width="943" alt="Screenshot 2024-08-13 at 11 40 42 AM" src="https://github.com/user-attachments/assets/0ed3bcf6-163f-4d0e-9abb-6bcfadfe3ddf">

**Comment by Eglusaxie** [comment]
> @Eglusaxie As mentioned in the rootBundle [documentation](https://api.flutter.dev/flutter/services/rootBundle.html), try following to see if it helps in your case or not:
> 
> <img alt="Screenshot 2024-08-13 at 11 40 42 AM" width="943" src="https://private-user-images.githubusercontent.com/67046386/357294372-0ed3bcf6-163f-4d0e-9abb-6bcfadfe3ddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzYzNDAsIm5iZiI6MTcyMzUzNjA0MCwicGF0aCI6Ii82NzA0NjM4Ni8zNTcyOTQzNzItMGVkM2JjZjYtMTYzZi00ZDBlLTlhYmItNmJjZmFkZmUzZGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4MDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjN2M2NTU4YTUyNDEyOGVjNWRlODFkZTI0YWZjZTMyYzYxZDY3ODBiMGRlNzQ0ZmZiZDg0ZjVhNDgyNzZiNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l8U7nor_6FnWfWkqF87V7xDS8C3uRxtH5_AsiXn4gGw">

Thank you for your help. Actually, my issue is not very serious because my project is small, and for now, I can simply list all the subfolders in the pubspec file.

This issue was originally a feature request, but later I realized the situation might be different from what I initially thought.

What should I do now? Should I go ahead and close this issue?

**Comment by darshankawar** [comment]
If you are satisfied with the solution and it is acceptable, I will close this as resolved. If you face similar issue again, feel free to file a new issue with relevant details so that we can address it accordingly.
