### ISSUE TITLE
[Web] "Flutter run" throws various exceptions but "Flutter run -profile" doesnt

### ISSUE THREAD

**Issue by JustAdreamerFL** [flutter/flutter#153279]
### Steps to reproduce

Upgraded from Flutter 3.22 to 3.24
Now sometimes when I run a new or old project (also when I run the default project) in web it throws exceptions like this:
(first run)
<img width="603" alt="Screenshot 2024-08-12 at 15 00 51" src="https://github.com/user-attachments/assets/7a7a33d5-0c8a-4cae-a273-94d2acd79a50">
(i changed nothing in code, literally stopped debug session and run it again, different exception)
<img width="494" alt="Screenshot 2024-08-12 at 15 01 32" src="https://github.com/user-attachments/assets/799726da-df00-4d3a-b54e-bbcab34dea29">
(third run with steps as in second run)
<img width="477" alt="Screenshot 2024-08-12 at 15 05 29" src="https://github.com/user-attachments/assets/92d0e9a5-4c76-4042-b41d-59c6d5011f6e">

🤷‍♂️

I have noticed that for a flutter run -profile it builds and works as usual.
I haven’t tried other arguments.

### Expected results

App should build and work.
Example photo:
(runed with --profile argument)
<img width="544" alt="Screenshot 2024-08-12 at 15 25 20" src="https://github.com/user-attachments/assets/61558405-adf6-44f6-83b7-c4061ddcb200">

### Actual results

throwing exceptions 

### Code sample

<details open><summary>Code sample</summary>

```dart
code
```

</details>

### Logs

<details open><summary>Logs</summary>
(Rare run when it worked without --profile!)

[Good run.txt](https://github.com/user-attachments/files/16582878/Good.run.txt)

(the not so lucky run)
[Bad run.txt](https://github.com/user-attachments/files/16582863/Bad.run.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-SK)
    • Flutter version 3.24.0 on channel stable at /Users/slavo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (13 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/slavo/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @JustAdreamerFL 

This is a known issue at https://github.com/flutter/flutter/issues/145410. It should be fixed on Flutter master channel. You can follow https://github.com/flutter/flutter/issues/152953 for further updates.

Closing this issue as a duplicate.
