### ISSUE TITLE
[version 3.24] checkerboardOffscreenLayers not working in 3.24, which was working in version 3.22.x

### ISSUE THREAD

**Issue by Gilianp** [flutter/flutter#153227]
### Steps to reproduce

```
MaterialApp(    
      checkerboardOffscreenLayers: true
 );

```

### Expected results

Turns on checkerboarding of layers rendered to offscreen bitmaps.

### Actual results

Nothing happens

### Code sample

```
MaterialApp(    
      checkerboardOffscreenLayers: true
 );

```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @Gilianp, do you mean the hintColor is not applied to TextField when you declared it in ThemeData like this, correct?

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      checkerboardOffscreenLayers: true,
      home: MyApp(),
      theme: ThemeData(
        hintColor: Colors.red,
      ),
    ),
  );
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          decoration: InputDecoration(
            hintText: 'Enter your name',
          ),
        ),
      ),
    );
  }
}

```
</details>

If so, it's https://github.com/flutter/flutter/issues/153219 which is filed recently.

**Comment by Gilianp** [comment]
> Hi @Gilianp, do you mean the hintColor is not applied to TextField when you declared it in ThemeData like this, correct?
> 
> Sample code
> If so, it's #153219 which is filed recently.

Sorry for my lack of attention, I fixed the title. It was about the debug functionality "checkerboardOffscreenLayers" which is not working in flutter 3.24. It does not display the rectangles indicating operations with "saveLayer"

**Comment by huycozy** [comment]
I found that `checkerboardOffscreenLayers` flag has been removed by https://github.com/flutter/engine/pull/52446. Please check https://github.com/flutter/flutter/issues/144382#issuecomment-2091084950 and https://github.com/flutter/engine/blob/main/impeller/docs/read_frame_captures.md to see if one of those can work for you.

**Comment by Gilianp** [comment]
Thank you. Maybe this will work for the purpose, but it requires a learning curve, while the old "checkerboardOffscreenLayers" option quickly solved the problem. But I understand that debugging GPU frames is a much more robust solution.

> I found that `checkerboardOffscreenLayers` flag has been removed by [flutter/engine#52446](https://github.com/flutter/engine/pull/52446). Please check [#144382 (comment)](https://github.com/flutter/flutter/issues/144382#issuecomment-2091084950) and https://github.com/flutter/engine/blob/main/impeller/docs/read_frame_captures.md to see if it works for you.

**Comment by huycozy** [comment]
In case you want to bring `checkerboardOffscreenLayers` flag back, please file a [new proposal](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=3_feature_request.yml) with your perspective. 

I'm going ahead and closing this issue as referenced above. Thanks!
