### ISSUE TITLE
with web view_flutter package fido webauthn flow is not working 

### ISSUE THREAD

**Issue by chunsfire** [flutter/flutter#153269]
Is there a limitation with webview_flutter package that it doesn't support fido webauthn flow be it registration or authentication?
I tried this on android & iOS both, but it says "User agent is not supported" error while checking windows.publicCredentials check.

**Comment by danagbemava-nc** [comment]
This is not an issue with the webview plugin but an implementation of the spec. See https://fidoalliance.org/fido2-2/fido2-web-authentication-webauthn/#support-for-fido2-webauthn-and-ctap and https://stackoverflow.com/questions/56258147/android-webview-support-webauthn

Closing from here as this is not a flutter issue. 

Thank you
