### ISSUE TITLE
[`Slider`] Inactive/unselected stop indicator color is incorrect in the `gen_defaults` tokens.

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#153271]
### Steps to reproduce

New `Slider` design uses stop indicator color and size for the tick marks in the discrete `Slider`. However, the new tokens use same color for the active and inactive stop indicator.

https://github.com/flutter/flutter/blob/9b8470197f4205d05d8507850b65e6d9f2fda105/dev/tools/gen_defaults/data/slider.json#L39-L40

If we apply this as is then we'll get inactive tick marks with the same color as inactive track color thus rendering them invisible.

### Incorrect
```dart
Color? get inactiveTickMarkColor => _colors.secondaryContainer;
```
<img width="869" alt="Screenshot 2024-08-12 at 14 19 59" src="https://github.com/user-attachments/assets/5e843e36-cd7a-4108-89b4-f346d6ad8e6b">

### Corrected
```dart
Color? get inactiveTickMarkColor => _colors.primary;
```
<img width="869" alt="Screenshot 2024-08-12 at 14 25 55" src="https://github.com/user-attachments/assets/7d7f3fdf-3fd6-425d-85bf-a51f40528d4a">

This also seems incorrect in the [web specs](https://m3.material.io/components/sliders/specs)

<img width="987" alt="image" src="https://github.com/user-attachments/assets/95ff5134-2b61-4777-8293-9b0fe8137b8a">

### Expected results

Correct token

### Actual results

Incorrect token

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  double _value = 5.0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Slider(
          value: _value,
          divisions: 10,
          // ignore: avoid_redundant_argument_values
          min: 0,
          max: 10,
          onChanged: (double value) {
            setState(() {
              _value = value;
            });
          },
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

~

**Comment by TahaTesser** [comment]
cc: @QuncCccccc

**Comment by QuncCccccc** [comment]
Ah just double checked the internal specs, it seems also incorrect. Let me ask! Thanks for catching this!

**Comment by QuncCccccc** [comment]
I just reported this issue and they will work on the fix! At the same time, we can use hard-coded values to replace tokens. Here's some information that I got from material team: "The active stop-indicator color should be on-primary; the inactive stop-indicator color should be on-secondary-container. Do not switch the track colors and use them as the stop indicator. There's no contrast guaranteed between primary and secondaryContainer. There will be a11y issue in medium or high contrast modes." So if the track color is XXX, we probably should use on-XXX color roles for the stop indicators.

**Comment by TahaTesser** [comment]
That makes sense, I'll use the onSecondaryContainer color. Thank you!
