### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by ninjaassassin1947** [flutter/flutter#153284]
### Steps to reproduce

Create a New Flutter Project:

Run flutter create my_project.
Navigate to the project directory using cd my_project.
Add Dependencies:

Open pubspec.yaml.
`dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.3
`   
then setup routes in main.dart
![main_file_dart](https://github.com/user-attachments/assets/a5948437-b343-4ab0-9ca7-191f70a53aa2)
then set routing in login and signup pages

### Actual results

ACTUALLY I AM FACING A PROBLEM AFTER I ADDED GO_ROUTER TO MY APPLICATIONS  , I REVIEWED MY CODE TO SEE IF THERE IS SOME TYPOS IN ROUTE I  CREATED BUT I DONOT SEE ANY PROBLEM. HERE IS MY MAIN.DART AND SOME OTHER FILES.
![Screenshot 2024-08-12 191537](https://github.com/user-attachments/assets/f072af1f-aa2f-4270-8755-aa8da1cd1315)
![main_file_dart](https://github.com/user-attachments/assets/fa0081e1-59b2-4235-a9cb-d001f7df7658)
![error](https://github.com/user-attachments/assets/a33776d4-df36-44bd-816c-812d699e8b4a)

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- PDoctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = F:\emulator\commandlinetool
      but Android SDK not found at this location.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (not installed)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 3 categories.-->

```

</details>

**Comment by darshankawar** [comment]
> flutter provider: ^6.1.2

@ninjaassassin1947 This is a third party package. Does it throw same error without this package usage ? If so, provide complete runnable reproducible code sample without third party implementation and in properly formatted text instead of in screenshot.



> ACTUALLY I AM FACING A PROBLEM AFTER

Please do not comment in caps.
