### ISSUE TITLE
How to read the iOS project's appName, BundleID, and app version number in flutter 🦄 ？

### ISSUE THREAD

**Issue by Jinxiansen** [flutter/flutter#15329]
As described above .

> English is not my native language; please excuse typing errors.

**Comment by xster** [comment]
https://pub.dartlang.org/packages/package_info should satisfy your needs. 

Feel free to send us a PR to also expose `CFBundleName` via package_info if needed :)

**Comment by Jinxiansen** [comment]
😄 Okey ! thanks ! 👍🏿👍🏿👍🏿
