### ISSUE TITLE
Black border appears in Windows window layering penetration

### ISSUE THREAD

**Issue by huddhudd** [flutter/flutter#153218]
### Steps to reproduce

  HWND hwnd = window.GetHandle();
  
  LONG ex_style = GetWindowLong(hwnd, GWL_EXSTYLE);
  SetWindowLong(hwnd, GWL_EXSTYLE, ex_style | WS_EX_LAYERED);
  
  SetLayeredWindowAttributes(hwnd, 0, 0, LWA_COLORKEY);

### Expected results

![image](https://github.com/user-attachments/assets/f6a55d65-442f-4510-8910-620239f07447)

### Actual results

![image](https://github.com/user-attachments/assets/db6a6071-e78d-4ce1-baeb-1d957b742406)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@huddhudd 
Please provide complete runnable reproducible code sample (ex: main.dart) along with `flutter doctor -v` to properly address the issue.

Also, can you elaborate what do you mean by window layering penetration ?

**Comment by huddhudd** [comment]
```
  HWND hwnd = window.GetHandle();
 
  LONG ex_style = GetWindowLong(hwnd, GWL_EXSTYLE);
  SetWindowLong(hwnd, GWL_EXSTYLE, ex_style | WS_EX_LAYERED);
 
  SetLayeredWindowAttributes(hwnd, 0, 0, LWA_COLORKEY);
```


  SetWindowLong(hwnd, GWL_EXSTYLE, ex_style | WS_EX_LAYERED);  
  Deleting this code is good

**Comment by darshankawar** [comment]
@huddhudd 
What Flutter version are you on ?
Is there a way to provide replicable code that shows the issue ?
