### ISSUE TITLE
Make flutter/dart able to "observe" changes in variables + properties

### ISSUE THREAD

**Issue by turbobuilt** [flutter/flutter#153253]
### Use case

In Vue.js you can just do:

```javascript
var user = reactive({
   name: "bob"
})
```
Then you can do 
```
{{ user.name }}
<input v-model="user.name" />
```
and it will update automatically.

React/Flutter type of applications require tons more work.  Plus in vue you can do this to check if the user changes
```javascript
watch(() => user.id, (newVal, oldVal) => { /* do something */ })
```
But in flutter you can't just watch it that way.

In order to implement this, vue uses Proxies.  So it can detect if you change or update a key on a variable.

I think that dart should be modified to support this use case so that we can watch for changes. Then this would make flutter really easy.  We could design really cool state management things.

So really it seems this is a dart feature. But I'm not an expert, and I think that maybe you all could figure out another way to do it?

It's just having to call setState every time is "old school" lol :) so I'd like to get something that can handle it automatically!

i noticed this: https://github.com/lukehutch/flutter_reactive_value

but you have to keep doing .value, and that's not as good because it doesn't do "deep" watch.

You all are awesome!

### Proposal

You should be able to do this:

```dart
var user = reactive(User(name: "bob"))
```

Then:

```dart
watch(() => user.name, (newVal, oldVal) {
  // every time it changes, you can update state, etc. here.
})
```

I think that adding this feature would be good, because it is a state-agnostic way of watching changes that could allow for a ton of "vue-like" state management systems that would reduce complexity.

Note, this must be able to "deep" observe too, otherwise it won't work as well.

**Comment by iapicca** [comment]
something like this?
https://pub.dev/packages/signals

**Comment by turbobuilt** [comment]
Yes that’s awesome, but on my first look, it only supports individual values. But what if you want it for a whole object?Like watching user.id to test when the user changes?Sent from my iPhoneOn Aug 12, 2024, at 1:53 PM, Francesco Iapicca ***@***.***> wrote:﻿
something like this?
https://pub.dev/packages/signals

**Comment by darshankawar** [comment]
@turbobuilt 
Please file this in dedicated repo : https://github.com/dart-lang/sdk/issues
Closing from here.
