### ISSUE TITLE
Clustering of Circles

### ISSUE THREAD

**Issue by ShaunAtSense** [flutter/flutter#153239]
### Use case

We use Circles and Markers combined to display a radius specific to a marker. However, we are unable to hide Circles for these Markers when markers are clustered using the new Cluster Manager.

### Proposal

Please could you allow Circles a property of ClusterManagerId that will enable the circle to be clustered alongside with the Marker if clustered.

**Comment by stuartmorgan** [comment]
`google_maps_flutter` is a wrapper around the existing Google Maps SDK on each supported platform; it only provides access to functionality those SDKs provide. Cluster managers in the SDK only support makers, not other object types, so this can't be implemented in the plugin. You'd need to file this feature request against the Google Maps SDKs themselves.
