### ISSUE TITLE
[Feature requests]: Why not enable GitHub discussions?

### ISSUE THREAD

**Issue by kjxbyz** [flutter/flutter#153246]
### Use case

1. Asking questions in discord is easily covered by the following questions and is difficult to be seen.
2. The reply level is not obvious, and I need to read every reply, which is a waste of time.

### Proposal

GitHub discussions need to be enabled

**Comment by brainwo** [comment]
I don't think this idea will attract contributors that much. Flutter has a massive amount users, it's too much for any team to handle the growing amount of questions. And as a GitHub Discussion user myself, I never have witnessed any GitHub Discussion attract visitor to visit the site often, it's mostly for used by maintainer of a repository to communicate.

If you referring to "Flutter Dev" Discord server, as a regular in that server, I should say we layout the server that way to balance between contributors and participants. We have fiddled around with this idea previously, but it didn't work and we ended up never adopt it widescale.

The hacker Flutter Discord server (where team members are communicating; one with Dash as its profile picture) has enabled a forum feature from Discord, but from my perspective as an observer, it attracts less new contributors and around the same amount if not more questions are lying there unanswered.

Not to mention if you have a question that needs extra attention from people and not expecting an immediate response, you should be using Stackoverflow or r/FlutterHelp on Reddit.

While I know having a preferred option is much better, I don't think and I don't see how Discord can be a platform to expect such attention on.

For what it worth, we have small GitHub Discussion community on GitHub Community Discussion:
https://github.com/orgs/community/discussions?discussions_q=label%3A%22Programming+Help%22+flutter

**Comment by iapicca** [comment]
dupe
https://github.com/flutter/flutter/issues/72013

I agree with @kjxbyz for what is worth

**Comment by darshankawar** [comment]
Based on https://github.com/flutter/flutter/issues/60696 and underlying comments from team member (Hixie) who moderates Flutter github, I'll close this as not feasible. @kjxbyz You may raise this in Flutter discord to gauge views from concerned team members to check if there's any change in their decision. Based on it, we can reopen it.
