### ISSUE TITLE
Strange Behavior of Navigation

### ISSUE THREAD

**Issue by ahmeddarafat** [flutter/flutter#153260]
### Steps to reproduce

- I'm trying to redirect to login when the user's token is expired with the Navigator key and pushNamedAndRemoveUntil method

### Expected results

- back to login correctly

### Actual results

- back to login if the navigation stack is
bottom -> home 
- back to blank page if the navigation stack is
bottom->  home - any page
as though the navigator works well in pop but it doesn't work in push

### Code sample

<details open><summary>Code sample</summary>

```dart
// method in api_service file
  void _redirectToLogin(ErrorInterceptorHandler handler, DioException error) {
    navigatorKey.currentState!.pushNamedAndRemoveUntil(
      AppRoutes.login,
      (route) => false,
    );
    handler.reject(error);
  }

// app file
final navigatorKey = GlobalKey<NavigatorState>();

MaterialApp(
   navigatorKey: navigatorKey,
   onGenerateRoute: RouteGenerate().getRoute,
   home: const WelcomePage(),
)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@ahmeddarafat 
Please provide [complete runnable and reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) (without third party package implementation) that we can directly use to verify the reported behavior.
