### ISSUE TITLE
Navigation Exception in showModalBottomSheet.(No GoRouter found in context)

### ISSUE THREAD

**Issue by moin-nimblechapps** [flutter/flutter#153264]
### Steps to reproduce

I’m encountering an exception when attempting to navigate to a details screen from a showModalBottomSheet using the go_router package. The specific error message is:

'package:go_router/src/router.dart': Failed assertion: line 507 pos 12: 'inherited != null': No GoRouter found in context.

The context is being passed from the initState method of main.dart, and this function is executed within WidgetsBinding.instance.addPostFrameCallback. Below is a snippet of the code where the issue arises:

-> The issue occurs when invoking Updatebottomsheet.UpdateBottomSheetModal(context) from within checkNewUpdate.
-> The context is passed from initState and is used in asynchronous methods.
-> The error indicates that GoRouter is not found in the context at the time of navigation.

I would appreciate any guidance or suggestions on how to resolve this issue. Thank you!

### Expected results

Please navigate to the details.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-12 at 13 32 42](https://github.com/user-attachments/assets/5ad0e22f-31f3-424f-8b8c-58712d41e2e2)

### Actual results

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-12 at 13 40 45](https://github.com/user-attachments/assets/4412b85c-91b2-4b3d-9bbf-814902fc00eb)

### Code sample

<details open><summary>Code sample</summary>

```dart
@override
void initState() {
  WidgetsBinding.instance.addObserver(this);
  initializeFirebaseAndNotifications(context);
  print("context before>>> $context");
  WidgetsBinding.instance.addPostFrameCallback((_) {
    print("context after>>> $context");
    if (this.context.mounted) {
      handleAppVersion();
      checkNewUpdate(this.context);
    }
  });
  super.initState();
} 

void handleAppVersion() async {
  try {
    final status = await PackageInfo.fromPlatform();
    setState(() {
      checkLocalAppVersion = status.version;
    });
    // Provider.of<Bottomsheetprovider>(context, listen: false).showBottomSheet(context);
  } on Exception catch (e) {
    print("handleAppVersion error>> ${e.toString()}");
  }
}

void checkNewUpdate(BuildContext context) async {
  print("checkNewUpdate context >>> $context");
  try {
    final storeVersion =
        Provider.of<Updatebottomsheetprovider>(context, listen: false);
    final checkNewupdate = await AppVersionUpdate.checkForUpdates(
        appleId: appleId, playStoreId: playStoreId, country: "IN");
    if (checkNewupdate != null) {
      setState(() {
        checkLiveAppVersion = checkNewupdate.storeVersion;
      });
      if (checkLocalAppVersion != checkLiveAppVersion) {
        storeVersion.saveAppVersion(
            checkLocalAppVersion, checkLiveAppVersion);
        if (context.mounted) {
          Updatebottomsheet.UpdateBottomSheetModal(context);
        }
      }
    } else {
      print("No update information available.");
    }
  } catch (e) {
    print("Error checking for updates: $e");
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-12 at 13 32 42](https://github.com/user-attachments/assets/e7d9c9bc-7d9d-4723-9568-d121275cc466)

</details>

### Logs

<details open><summary>Logs</summary>

```console
 context error>>> 'package:go_router/src/router.dart': Failed assertion: line 507 pos 12: 'inherited != null': No GoRouter found in context
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /Users/moin/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (10 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/moin/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • 15BA36C7-0DE9-416F-A6CE-A239BE0B6FFA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.100
    ! Error: Browsing on the local area network for iPhone 13 pro max. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone 13. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone X. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</details>

**Comment by darshankawar** [comment]
@moin-nimblechapps 
Looks like this can be asked in support channels like StackOverflow, as it could be related to code implementation rather than bug in framework or plugin.
If possible, provide [complete minimal but reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without third party package implementation so that we can address it properly.
