### ISSUE TITLE
Flutter web not dual compiling on ios browsers

### ISSUE THREAD

**Issue by samumzizi** [flutter/flutter#153234]
### Steps to reproduce

1. Create flutter web app
2. Build release & deploy release `flutter build web --web-renderer canvaskit --release` or `flutter build web --wasm --release`
3. Open url on ios browser

### Expected results

Since wasm gc is not supported on ios browsers, js canvaskit should load and be used instead, but that's not the case.
Works just fine on android and desktop browsers.

### Actual results

Just a blank screen.

### Code sample

<details open><summary>Code sample</summary>

```dart
flutter build web --web-renderer canvaskit --release
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.92.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @samumzizi 
To load Skwasm the browser must support all these features: https://github.com/flutter/engine/blob/71dfa104e02cef3b8877171cff985c0d164800f0/lib/web_ui/flutter_js/src/loader.js#L80
Can you check if ios browsers support these or not ? If not, then the reported behavior would be expected as of now.

**Comment by samumzizi** [comment]
Thanks @darshankawar. The code you provided ` && browserEnvironment.supportsWasmGC` indicates that the browser must support wasm gc, something ios browsers don't support (I think you already knew this). Nevertheless, per the flutter wasm docs [https://docs.flutter.dev/platform-integration/web/wasm](url) it clearly states, "
Even with the --wasm flag, flutter build web will still compile the application to JavaScript. If WasmGC support is not detected at runtime, the JavaScript output is used so the application will continue to work across browsers.
>. So even if the ios browser doesn't support wasm gc, it should still **dual compile** to javascript as well, making flutter web work across the majority of browsers, including ios, hence this bug report.

**Comment by kevmoo** [comment]
Yes see https://flutter.dev/wasm – dual compile IS happening, it's just not loading wasm.

**Comment by samumzizi** [comment]
@kevmoo, it’s not loading JavaScript either. That’s the bug in reference. Thanks

**Comment by kevmoo** [comment]
VERY weird!

**Comment by kevmoo** [comment]
Are you able to enable developer inspector on the iOS device to get console details?

**Comment by samumzizi** [comment]
> Are you able to enable developer inspector on the iOS device to get console details?

Now that I've enabled developer inspector, this is what I see in the ios console:

[Debug] Installing/Activating first service worker. (flutter_bootstrap.js, line 3)
[Debug] Activated new service worker. (flutter_bootstrap.js, line 3)
[Debug] Injecting <script> tag. Using callback. (flutter_bootstrap.js, line 1)
[Log] main loaded (main.dart.js, line 51329)
[Debug] Initializing Firebase firebase_core (welcome, line 2)
[Debug] Initializing Firebase firebase_firestore (welcome, line 2)
[Debug] Initializing Firebase firebase_functions (welcome, line 2)
[Debug] Initializing Firebase firebase_analytics (welcome, line 2)
[Debug] Initializing Firebase firebase_app_check (welcome, line 2)
[Debug] Initializing Firebase firebase_auth (welcome, line 2)
[Debug] Initializing Firebase firebase_messaging (welcome, line 2)
[Debug] Initializing Firebase firebase_remote_config (welcome, line 2)
[Debug] Initializing Firebase firebase_storage (welcome, line 2)
[Error] 
	cId (main.dart.js:6444)
	np (main.dart.js:6592)
	$0 (main.dart.js:63034)
	cU_ (main.dart.js:5273)
	cUv (main.dart.js:5275)
	$1 (main.dart.js:61867)
	
I'm starting to think perhaps its a firebase issue?
But the flutter web app loads just fine MacOS browsers...

**Comment by kevmoo** [comment]
try adding `--source-maps` to see if you get a more helpful stack trace?

**Comment by samumzizi** [comment]
> try adding `--source-maps` to see if you get a more helpful stack trace?

Thanks for that recommendation. It turned out to be due to the firebase messaging library (which is compatible with web but breaking on ios web?). So I just went ahead and commented it out for the web app. Let's close this.

**Comment by darshankawar** [comment]
Closing as resolved based on above comment.
