### ISSUE TITLE
Compile to a WASM web app & a blue outline appears around web googleMap Widget

### ISSUE THREAD

**Issue by Sam-Guru-In-Training** [flutter/flutter#153305]
### Steps to reproduce

1. Compile to WASM
2. Upload
3. Clear browser cache
4. Observe a strange blue outline around Map's widget 

### Expected results

The map should display without a blue outline

### Actual results

Map has a blue outline
![Screenshot_love_edinburgh](https://github.com/user-attachments/assets/30d90903-a0a4-46aa-ac12-14b5558c35f4)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@Sam-Guru-In-Training 
I think it maybe coming from maps api itself as mentioned here https://mapsplatform.google.com/resources/blog/improved-accessibility-maps-javascript-api/ that you can take a look and check if it helps in your case or not.

**Comment by Sam-Guru-In-Training** [comment]
From the videos on that website it would appear that activating the keyboard shortcut setting causes a blue outline. How do I deactivate this on map load in Flutter?

**Comment by darshankawar** [comment]
Does it help by Unchecking "Enable Full Keyboard Access" in System Preferences > Accessibility > Keyboard > Navigation

**Comment by Sam-Guru-In-Training** [comment]
I've done some more experimenting and it happens when you zoom in. When the
map is first loaded there's no blue widget outline.

I can't find the setting you're talking about. I have Android 13 I think.
Pixel 4.

**Comment by darshankawar** [comment]
Maybe this need to be reported here https://issuetracker.google.com/issues/318559142. See another similar issue https://issuetracker.google.com/issues/182937497
