### ISSUE TITLE
Remove FLX related code paths once all Fuchsia's apps are off FLX 

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter#15338]
FLX is not included on Android or iOS, but the Flutter tooling still builds the FLX for Fuchsia.

**Comment by tvolkert** [comment]
Per @zanderso:

> FLX was removed from Fuchsia in https://fuchsia.googlesource.com/topaz/+/2db4848213ccae204e8059f045e78151813d3d7b.

We have a green light to remove all FLX code paths.

**Comment by szakarias** [comment]
Done in #16416
