### ISSUE TITLE
NoSuchMethodError in WindowMetricsCalculator when generating an APK in Flutter 3.13.0 or later

### ISSUE THREAD

**Issue by KevinVegaRem** [flutter/flutter#153389]
### Steps to reproduce

1. Create a Flutter module project with version 3.13.0 or later.
2. Generate an AAR from the Flutter project.
3. Import the AAR into an Android Studio module project.
4. Generate an APK from the Android application project.
5. Run the application on a device or emulator.

### Expected results

The application should run without errors related to missing methods in WindowMetricsCalculator.

### Actual results

The application crashes on launch with a NoSuchMethodError in the WindowMetricsCalculator class.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Description:
When generating an AAR from a Flutter module (using the add-to-app feature) 
and incorporating it into an Android Studio module, an issue arises when this module is further
 integrated into an Android application project. Specifically, a NoSuchMethodError related to the 
WindowMetricsCalculator class from the androidx.window.layout library occurs immediately upon
 invoking the Flutter activity. This error only manifests when building the APK, whether in
debug or release mode, using Flutter version 3.13.0 or later. The project functions correctly when using Flutter version 3.10.6.]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[https://drive.google.com/file/d/1KTFHfvzgHX9hJoDyMf1G2pJ8hUv1Ko2k/view?usp=share_link](https://drive.google.com/file/d/1KTFHfvzgHX9hJoDyMf1G2pJ8hUv1Ko2k/view?usp=share_link)]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[FATAL EXCEPTION: main
Process: tools.rem.nativapp, PID: 1018
java.lang.NoSuchMethodError: No static method getOrCreate()Landroidx/window/layout/WindowMetricsCalculator; in class Landroidx/window/layout/WindowMetricsCalculator; or its super classes (declaration of 'androidx.window.layout.WindowMetricsCalculator' appears in /data/app/~~wzjAw1PZkgvak0Q-9PIVFA==/tools.rem.nativapp-MSDe9brCAY_hLyRzt5qJRA==/base.apk)
	at io.flutter.util.ViewUtils.calculateMaximumDisplayMetrics(ViewUtils.java:32)
	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:391)
	at io.flutter.embedding.engine.FlutterEngineGroup.createEngine(FlutterEngineGroup.java:206)
	at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:158)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setUpFlutterEngine(FlutterActivityAndFragmentDelegate.java:332)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:194)
	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:638)
	at android.app.Activity.performCreate(Activity.java:8523)
	at android.app.Activity.performCreate(Activity.java:8487)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.92.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
kevinvega.rem@MacBook-Air-de-Kevin workflows % flutter doctor -v
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale es-419)
    • Flutter version 3.22.3 on channel stable at /Users/kevinvega.rem/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (4 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kevinvega.rem/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/kevinvega.rem/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • M2101K6G (mobile)               • 67053dd8                  • android-arm64  • Android 13 (API 33)
    • iPhone K3vin (mobile)           • 00008030-00015DA80C60C02E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.]
```

</details>

**Comment by huycozy** [comment]
Hi @KevinVegaRem 
I checked this using a complete sample code at [Flutter-add-to-app-Android-native-sample/tree/aar-only](https://github.com/huycozy/Flutter-add-to-app-Android-native-sample/tree/aar-only) but couldn't see the error when running app on device. I'm on the latest Flutter stable 3.24.0.

Please try this sample code. If the sample code needs to update something, please clarify.

**Comment by KevinVegaRem** [comment]
Hello @huycozy , I tested the project you mentioned, and it doesn't show any errors, although it's not exactly the scenario I use. To reproduce the problem, follow these steps:

Create a Flutter module to generate the AAR.
Then, create an Android module and integrate the Flutter module into it.
In the Android module project, generate an AAR using the command ./gradlew assembleRelease.
Finally, in a new Android application project, I integrate the AAR from the Android module using Artifact Registry for its download.
The error occurs when I generate the APK in this application project.

**Comment by huycozy** [comment]
>Then, create an Android module and integrate the Flutter module into it.

Does the `Android module` here mean [Android library](https://developer.android.com/studio/projects/android-library)? If so, this doesn't seem to be supported currently, please check https://github.com/flutter/flutter/issues/95345. So I would suggest we concentrate on that issue for better tracking. If you persist with this issue as a separate one, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thank you!

**Comment by KevinVegaRem** [comment]
I was missing the FlutterEngineApplication class 

`import android.app.Application
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.FlutterEngineCache
import io.flutter.embedding.engine.dart.DartExecutor

class FlutterEngineApplication : Application() {
    lateinit var flutterEngine : FlutterEngine

    override fun onCreate() {
        super.onCreate()

        // Instantiate a FlutterEngine.
        flutterEngine = FlutterEngine(this)

        // Start executing Dart code to pre-warm the FlutterEngine.
        flutterEngine.dartExecutor.executeDartEntrypoint(
            DartExecutor.DartEntrypoint.createDefault()
        )

        // Cache the FlutterEngine to be used by FlutterActivity.
        FlutterEngineCache
            .getInstance()
            .put("workflows_engine", flutterEngine)
    }
}`
and the activity that invokes the FlutterEngine. I have added the following code:

`@Override
    public FlutterEngine provideFlutterEngine(@NonNull Context context) {
        return FlutterEngineCache.getInstance().get("workflows_engine");
    }` and add this in manifest: <application
        android:name="tools.rem.workflows.FlutterEngineApplication"

**Comment by huycozy** [comment]
>Does the Android module here mean [Android library](https://developer.android.com/studio/projects/android-library)? If so, this doesn't seem to be supported currently, please check https://github.com/flutter/flutter/issues/95345.

Can you please confirm this?

**Comment by KevinVegaRem** [comment]
Yes is a android library: I was able to package the Flutter AAR inside another AAR from an Android library module and generate the final AAR that is integrated into a native Android application.

**Comment by huycozy** [comment]
It doesn't seem to be supported yet so I will close this in favor of https://github.com/flutter/flutter/issues/95345. It would be useful if you could share your progress on that issue. Thanks!
