### ISSUE TITLE
open MyFlutterActivity very slow

### ISSUE THREAD

**Issue by laibinCN** [flutter/flutter#15334]
I modified the example\platform_view project.
My app has two activity, the first CountActivity ,it inherits AppCompatActivity.The second MainActivity , It inherits FlutterActivity.
When you start CountActivity by default, when you click on the button in the screen and execute the returnToFlutterView method,

>   private void returnToFlutterView() {
    Intent flutterIntent = new Intent(this, MainActivity.class);
    startActivity(flutterIntent);
  }

The whole process is very slow.It takes 2 seconds to see the FlutterView.

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="io.flutter.examples.platform_view">

    
    <uses-permission android:name="android.permission.INTERNET" />

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:icon="@mipmap/ic_launcher"
        android:label="platform_view">
        <activity
            android:name="io.flutter.examples.platform_view.MainActivity"
            android:launchMode="singleTop"
            android:theme="@android:style/Theme.Black.NoTitleBar"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
        </activity>
        <activity
            android:name="io.flutter.examples.platform_view.CountActivity"
            android:parentActivityName="io.flutter.examples.platform_view.MainActivity"
            android:theme="@style/Theme.AppCompat.NoActionBar"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`
## Logs

this execute "startActivity(flutterIntent); " adb log.
`
I/Timeline(20021): Timeline: Activity_launch_request time:263388343 intent:Intent { cmp=io.flutter.examples.platform_view/.MainActivity }
I/FlutterActivityDelegate(20021): onResume setting current activity to this
D/OpenGLRenderer(20021): endAllActiveAnimators on 0x7f91755400 (RippleDrawable) with handle 0x7f76413000
I/Timeline(20021): Timeline: Activity_launch_request time:263407568 intent:Intent { cmp=io.flutter.examples.platform_view/.MainActivity }
I/FlutterActivityDelegate(20021): onResume setting current activity to this
D/OpenGLRenderer(20021): endAllActiveAnimators on 0x7f91755400 (RippleDrawable) with handle 0x7f764130e0
`

**Comment by Raymond69** [comment]
I have the same issue ..

Moreover, the intent extras are not passed to MainActivity

**Comment by Raymond69** [comment]
Any news ?

**Comment by laibinCN** [comment]
please flutter run --rlease

**Comment by Raymond69** [comment]
@laibinCN thank you!

Did you try to create other Flutter views and switch to them from CountActivity ?
