### ISSUE TITLE
Proposal to add iconAlignment to ButtonStyle

### ISSUE THREAD

**Issue by kay4ik** [flutter/flutter#153350]
### Use case

With the ```Button.icon()``` constructor we have the possibility to set the icon at the start or end of the Button with iconAlignment.

It should also be possible to set the iconAlignment inside the ThemeData for the whole app. That way we only have to set the iconAlignment once.

### Proposal

Example with TextButton.icon():

```dart
ThemeData(
  textButtonTheme: TextButtonThemeData(
    style: ButtonStyle(
      iconAlignment: IconAlignment.end,
//    [...]
    ),
  ),
);
```

By adding the property to the ButtonStyle class we can use it on all buttons. I think that is a huge benefit for everyone using this Feature!

**Comment by TahaTesser** [comment]
cc: @piedcipher

**Comment by piedcipher** [comment]
If this change is implemented, it needs to be done for Elevated, Filled and Outlined buttons as well.

But I've a query. ButtonStyle is being used for Buttons other than ElevatedButton, OutlinedButton, FilledButton and TextButton. So is it fine to add it in ButtonStyle?

**Comment by TahaTesser** [comment]
> So is it fine to add it in ButtonStyle?

Yes, `ButtonStyle` already has other icon related parameters such as `iconColor` and `iconSize`.

**Comment by piedcipher** [comment]
No I'm not working on it. Feel free to pick up
