### ISSUE TITLE
Google Maps rendering glitches caused by Engine change

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#153335]
Google3 app "Money" has reported a regression in Google Maps rendering behavior which they have narrowed down to Engine roll commit https://github.com/flutter/flutter/commit/9b0dc2ba36d4f3579bcca926af51bdf630702abe. The most likely actual Engine commit is https://github.com/flutter/engine/pull/54231.

When navigating to and from a screen with a GoogleMap embedded in it, there are glitches where parts of the non-Map screen start flashing and getting stuck.

See videos on internal bug b/359381093 for more information.

Minimal repro app:
<details>
<summary>Minimal repro
</summary>

Note: You need to set up a GoogleMaps API key to actually make this work.

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: false),
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _pushAnotherPage() {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => Scaffold(
          body: Container(
            height: double.infinity,
            width: double.infinity,
            color: Colors.red,
            child: Center(child: Text('Another page')),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: GoogleMap(
          initialCameraPosition: CameraPosition(
            target: LatLng(1.3521, 103.8198),
            zoom: 16,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _pushAnotherPage,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

This is a serious regression in a launched product, so we'd want to get a fix or rollback in ASAP and probably cherry-pick it into this app's next release.

**Comment by huycozy** [comment]
From primary triage: I checked this using Pixel 7, Android 14, on Flutter master channel `3.24.0-1.0.pre.559` (in profile mode) but couldn't see the issue as described. I didn't see any jank from Devtools as well. 

<details>
<summary>Demo video</summary>

https://github.com/user-attachments/assets/33a85b3d-e310-4b9c-a70d-005db92e63fe
</details>

Based on the commit above, forwarding this to engine team for insights.

**Comment by zanderso** [comment]
Revert landed at https://github.com/flutter/engine/commit/4246f1536c5d98c01326fa890384384c88c98aeb, removing priority to trigger re-triage.

**Comment by knopp** [comment]
@huycozy, this is only reproducible on iOS. Looking into this now.

**Comment by knopp** [comment]
I can reproduce this with impeller. I don't think it's limited to skia. I think the transition from disabled partial repaint to enabled needs some work.

**Comment by jacobsimionato** [comment]
Just to confirm: We're confident this issue only affects iOS, right? We're confident it doesn't affect Android? Just asking so I can keep our internal Google customers updated :-D.

**Comment by jacobsimionato** [comment]
Also, thank you very much for the swift rollback! Much appreciated.

**Comment by zanderso** [comment]
> Just to confirm: We're confident this issue only affects iOS, right? We're confident it doesn't affect Android? Just asking so I can keep our internal Google customers updated :-D.

Yes, only iOS is affected. Partial repaint optimizations are not implemented on Android.
