### ISSUE TITLE
App wont launch when using Impeller on Intel Mac

### ISSUE THREAD

**Issue by chaeMil** [flutter/flutter#153371]
### Steps to reproduce

1. Enable Impeller
2. Launch app in debug mode on Intel Mac

### Expected results

App should launch

### Actual results

App crashes

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

Basic flutter template creatd with `flutter create bug` and just enabled Impeller for mac by adding

```
<key>FLTEnableImpeller</key>
    <true/>
```

to `Info.plist`

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Building macOS application...                                           
✓ Built build/macos/Build/Products/Debug/bug.app
[IMPORTANT:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(66)] Using the Skia rendering backend (Metal).
[IMPORTANT:flutter/shell/platform/embedder/embedder_surface_metal_impeller.mm(55)] Using the Impeller rendering backend (Metal).
Failed to foreground app; open returned 1
Syncing files to device macOS...                                    81ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on macOS is available at: http://127.0.0.1:55017/SwWSfHsFC7k=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9106?uri=http://127.0.0.1:55017/SwWSfHsFC7k=/
Lost connection to device.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.6)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @chaeMil 
I am on Intel Mac too, with following config, but I didn't experience the crash you reported. 

<img width="351" alt="Screenshot 2024-08-14 at 12 53 04 PM" src="https://github.com/user-attachments/assets/6790e392-cc0f-4353-86ce-917e4df0c28d">

```
dhs@Dhss-MacBook-Pro impeller_test % flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
✓ Built build/storybook/macos/Build/Products/Debug/impeller_test.app
[IMPORTANT:flutter/shell/platform/embedder/embedder_surface_metal_impeller.mm(55)] Using the Impeller rendering backend (Metal).
Syncing files to device macOS...                                    82ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on macOS is available at: http://127.0.0.1:56947/P1DhMZV9AII=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:56947/P1DhMZV9AII=/

```


> ```
> [IMPORTANT:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(66)] Using the Skia rendering backend (Metal).
`Failed to foreground app; open returned 1`
> ```

You seem to get this additional log which I didn't get in my console. Is it not showing you the counter app UI at all or just crashes ? Can you provide a short video ?

**Comment by chaeMil** [comment]
I think video is not necessary the main window of the app never shows up. But in previous version of Flutter it worked but there was [this](https://github.com/flutter/flutter/issues/134399) problem. 

![image](https://github.com/user-attachments/assets/c02ad84f-8807-4afb-a882-83e473a87d2d)

**Comment by darshankawar** [comment]
@chaeMil 
We also tried on latest Intel config `macOS Sonoma 14.6 (23G80)` with which we were able to run the app properly without reported behavior.
Can you provide us a repo that we can clone to verify this further ?
