### ISSUE TITLE
Build fail using swift based flutter project with firebase_messaging 

### ISSUE THREAD

**Issue by jerrywell** [flutter/flutter#15335]
## Steps to Reproduce

1. create a new flutter project by intelliJ and choose Swift as iOS language.
2. add ```firebase_messaging: any``` into pubspec.yaml
3. build on simulator with debug mode, you will see following error message.

```
Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    PATH_FOR_FLUTTER_PROJECT/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_messaging/FirebaseMessagingPlugin.h' file not found
    #import <firebase_messaging/FirebaseMessagingPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

If we choose the Objective-C based project, it works fine.

## Logs

```
Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    PATH_FOR_FLUTTER_PROJECT/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_messaging/FirebaseMessagingPlugin.h' file not found
    #import <firebase_messaging/FirebaseMessagingPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.2.1-pre.42, on Mac OS X 10.12.6 16G29, locale en-TW)
    • Flutter version 0.2.1-pre.42 at /Users/jerry/Documents/project/flutter
    • Framework revision 2890e18bcb (9 hours ago), 2018-03-08 16:02:21 -0800
    • Engine revision 24cf8ebd86
    • Dart version 2.0.0-dev.33.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/jerry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (3 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86   • Android 8.0.0 (API 26) (emulator)
    • SM G930F                  • ce01171121b67a1a02                   • android-arm64 • Android 7.0 (API 24)
    • iPhone X                  • 94158934-6313-4593-921E-D4437A7BBF71 • ios           • iOS 11.2 (simulator)

• No issues found!
```

this may be related to https://github.com/flutter/flutter/issues/15152.

**Comment by jerrywell** [comment]
https://github.com/flutter/flutter/issues/15168#issuecomment-371344401
this workaround works for me. The issue seems not picked up by the issue reviewer because it was opened 4 days ago. I will keep this issue opened to highlight it.

**Comment by csga5000** [comment]
Similar error with path_provider or sqflite.

Steps to reproduce:
`flutter create -i swift test_proj
cd test_proj
(add a package, ex 'path_provider: any' to pubspec.yaml)
flutter run`

Xcode's output:
`    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/chaseanderson/dev/test_swift/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'path_provider/PathProviderPlugin.h' file not found
    #import <path_provider/PathProviderPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.
`

**Comment by jerrywell** [comment]
Fixed by https://github.com/flutter/flutter/pull/15437

**Comment by vascoV** [comment]
@jerrywell Hey I am facing the same problem, unfortunately, the plugins are not installed properly, I have tried all the workarounds mentioned above but nothing works though :/
<img width="1276" alt="screen shot 2018-04-03 at 5 48 52 pm" src="https://user-images.githubusercontent.com/15817701/38256749-b0714ff6-3767-11e8-977b-6d6a86dea2ee.png">

**Comment by csga5000** [comment]
If you correctly did the work around I did, that error should go away.  Since the file isn't there, you add it in.  Another thing you could do us update flutter, and recreate your project.  Then copy pubspec, and lib/ and anything else, and see if that works. (You created your project with -i swift, right?)

**Comment by vascoV** [comment]
@csga5000 Hey, No I did create a flutter project through the Android Studio and disable the swift support, copy paste all my dart files into the lib/ directory, on Android phones runs OK, then I switch to the ios folder into the flutter project and ran the `pub install` in order to install the firebase and all the packages added to the `pubspec`, It says that the packages are installed but I am still getting the error

**Comment by jerrywell** [comment]
i usually use `flutter packages upgrade` for flutter project since i ran into a problem before. not sure if it's ok to use `pub install` now.

**Comment by vascoV** [comment]
@jerrywell Yeas `flutter package upgrade` makes sense but sometimes is not working correctly and you need manually install the packages on using `pod install` for IOS
Thaks for mentioning tho!

**Comment by Winghin2517** [comment]
@vascoV  is correct. Run a pod install in your ios folder for your flutter app and the issue will be resolved.

**Comment by midastouch365** [comment]
<img width="1012" alt="Screen Shot 2019-05-27 at 8 12 09 PM" src="https://user-images.githubusercontent.com/42994762/58444048-ca225c80-80bb-11e9-9b1c-56371a505355.png">

**Comment by midastouch365** [comment]
I have the same error too. How do I fix this? Somebody help, this is really urgent!

**Comment by Carrie999** [comment]
![image](https://user-images.githubusercontent.com/26757216/70602708-f81e5700-1c2f-11ea-91a5-2c044a530b07.png)
