### ISSUE TITLE
[Android 15][http]SocketException: Connection timed out (OS Error: Connection timed out, errno = 110)

### ISSUE THREAD

**Issue by aaluyi** [flutter/flutter#153343]
### Issue:
`2024-08-13T16:14:21.838249 - [ERROR] [NET] NoNetworkError - ClientException with SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address =xxx.com.cn, port = 56160, uri=https://xxx/v1/enrollment/upload-img on Request: POST https://xxx/enrollment/upload-img  CorrelationId: a259e1f3-a541-416d-9097-4c34d7a640e0`

### Description:
Recently, I am doing Flutter compatibility verification on Android 15(<15 is OK), I have this issue with http:v1.2.2, my flutter version is 3.19.5, my scenario is upload image, it occurs problem sometimes.
I have looked for many similiar issues in StackOverflow/[Github Flutter Repo](https://github.com/flutter/flutter)/[Github Http Repo](https://github.com/dart-lang/http/tree/master/pkgs/http), however, no solution to this issue.
Is there more infomation about this issue, can someone help me, thanks a lot?

**Comment by darshankawar** [comment]
@aaluyi 
You will most probably need to report this in dedicated repo. See another similar issue for your reference: https://github.com/dart-lang/http/issues/551
Closing from here. 
Also check https://stackoverflow.com/questions/60155822/i-flutter-30720-socketexception-os-error-connection-timed-out-errno-110

**Comment by aaluyi** [comment]
It has nothing to do with the http network library, but with the flutter library image_picker that I use. I just changed the image library. As for why image_picker's image selection affects the network, it is still under investigation.

**Comment by darshankawar** [comment]
> but with the flutter library image_picker that I use. I just changed the image library

Please provide us complete reproducible code sample without third party package implementations, steps to replicate so that we can properly address the issue.
