### ISSUE TITLE
handler for HardwareKeyboard is called only when digit keys are typed but not when alpha keys or punctuation keys are typed

### ISSUE THREAD

**Issue by lucas-almeida026** [flutter/flutter#153309]
### Steps to reproduce

1. create a project using flutterflow & install flutter locally
2. create a custom widget template
3. download the code
4. edit the code to finish the component (see at code sample)
5. use the component in some already existing page
6. search for local devices `flutter devices`
7. copy the device id you want use
8. run the app on local device `flutter run -d <device-id>`

also make sure to:
1. under `./lib/custom_code/widgets` update the file `index.dart` to export the component `export 'input_test.dart' show InputTest;`
2. on the page you want to use the custom widget import it using `import '/custom_code/widgets/index.dart' as custom_widgets;`
3. use the component as `custom_widgets.InputTest(/*props*/)`

### Expected results

when pressing the "a" key on the android keyboard, I expect to see the message "event from hardware, key: a" at the console.

when pressing the "4" key on the android keyboard, I expect to see the message "event from hardware, key: a" at the console.

### Actual results

when pressing the "4" key on the android keyboard, the message "event from hardware, key: a" DOES appear at the console.

when pressing the "a" key on the android keyboard, the message "event from hardware, key: a" DOES NOT appear at the console.

### Code sample

<details open><summary>Code sample</summary>

```dart
input_text.dart
import '/backend/schema/structs/index.dart';
import '/backend/schema/enums/enums.dart';
import '/actions/actions.dart' as action_blocks;
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class InputTest extends StatefulWidget {
  const InputTest({
    super.key,
    this.width,
    this.height,
  });

  final double? width;
  final double? height;
  @override
  _InputTestState createState() => _InputTestState();
}

class _InputTestState extends State<InputTest> {
  
  final FocusNode focusNode = FocusNode();
  @override
  void initState() {
    HardwareKeyboard.instance.addHandler((event) {
      print("event from hardware, key: ${event.logicalKey.keyLabel}");
      return false;
    });
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return TextField(
      focusNode: focusNode,
      autofocus: true,
      decoration: InputDecoration(
        hintText: 'Press any key...',
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs after pressing the keys "a" and "4" one after the other repeatedly</summary>

```console
I/flutter ( 6524): new event
I/flutter ( 6524): Key down: 4
I/flutter ( 6524): event from hardware, key: 4
I/flutter ( 6524): new event
I/flutter ( 6524): Key up: 4
I/flutter ( 6524): event from hardware, key: 4
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output (Using the  moto g 9 play device)</summary>

```console
[Paste your output here]
```
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4651], locale pt-BR)
    • Flutter version 3.24.0 on channel stable at C:\Users\Usuario\.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (13 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Usuario\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35122.118
    • Windows 10 SDK version 10.0.22621.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development   
      with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.92.1)
    • VS Code at C:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (4 available)
    • moto g 9 play (mobile) • 0069453354 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows    • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 127.0.6533.100
    • Edge (web)             • edge       • web-javascript • Microsoft Edge 127.0.2651.98

[√] Network resources
    • All expected network resources are available.
</details>

**Comment by huycozy** [comment]
Hi @lucas-almeida026 
This is similar to an issue being tracked at https://github.com/flutter/flutter/issues/142820. Closing this issue as a duplicate.
