### ISSUE TITLE
[shared_preferences] Consider allowing access to SharedPreferences in the new API

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#153300]
Based on discussion in https://github.com/flutter/flutter/issues/153293 there is a thorny use case we didn't consider in switching the backend from `SharedPreferences` to `DataStore` on Android: some external systems that app developers don't control (a notable example from that issue is GDPR consent data [docs](https://developers.google.com/admob/android/privacy/gdpr#how_to_read_consent_choices), [more docs](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#what-is-the-cmp-in-app-internal-structure-for-the-defined-api)) write important information directly to `SharedPreferences`.

Supporting the legacy API forever is not ideal, especially given issues like https://github.com/flutter/flutter/issues/151036 that make use cases like this one troublesome with the legacy API. We could consider making the backing store a configuration option on Android. That would mean fully supporting both systems indefinitely though, even though for most use cases the docs seem to strongly discourage use of `SharedPrefences`.

Another option would be an alternate API—probably just exposed as a sidecar in `shared_preferences_android` rather than plumbed through to the app-facing package—that provides async-only, read-only access to `SharedPreferences` for this specific use case.

The Android team should weigh in here on how we want to support this. Also /cc @tarrinneal.

**Comment by large** [comment]
Maybe this case is in the same alley https://github.com/flutter/flutter/issues/14337 ?

**Comment by stuartmorgan** [comment]
Supporting two preference stores is a lot more complicated than just allowing control of the store name unfortunately.

**Comment by reidbaker** [comment]
@tarrinneal I think we talked about this in a Ecosystem sync and your opinion was that we should let the android implementation pick which of "datastore" and "sharedPreferences" to use. 

Is this something that should be done by the android team still?

**Comment by tarrinneal** [comment]
> @tarrinneal I think we talked about this in a Ecosystem sync and your opinion was that we should let the android implementation pick which of "datastore" and "sharedPreferences" to use.
> 
> Is this something that should be done by the android team still?

It's probably easier for me to do it, depends on the urgency for you. I (probably) won't have time this quarter.

**Comment by gmackall** [comment]
From Android triage: Reassigning to ecosystem team for now based on @tarrinneal's comment
