### ISSUE TITLE
Flutter Linux ARM64 download not available

### ISSUE THREAD

**Issue by ScorpiosCrux** [flutter/flutter#153378]
### Steps to reproduce

The SDK archive https://docs.flutter.dev/release/archive does not contain any ARM64 downloadable tars for Flutter Linux.

It seems like it's not possible to compile from x86 to ARM64, thus Flutter would have to be installed on Linux ARM64 for it to be compiled.

### Actual results

N/A

### Logs

N/A

### Flutter Doctor output

N/A

**Comment by christopherfujino** [comment]
Are you asking for support for cross compile, or for a pre-built archive for the native arm64 build to be available on the website (these are two different requests)?

Currently, the only way to do linux arm64 development with flutter to is to clone the repo from a linux arm64 host device.

**Comment by ScorpiosCrux** [comment]
I was asking for a pre-built archive for the native arm64 build, kind of like the dart archives.

It would be nice to have support for cross compilation, but it seems like that isn't planned in another issue.

> Currently, the only way to do linux arm64 development with flutter to is to clone the repo from a linux arm64 host device.

Perfect, thank you, I'll try this out but it would be nice to have it downloadable (if possible)

**Comment by darshankawar** [comment]
> it would be nice to have it downloadable (if possible)

I think you can follow-up about this here https://github.com/flutter/flutter/issues/114349
Closing in favor of it.
