### ISSUE TITLE
Performance Regression with ColorFiltered on Flutter 3.24.0

### ISSUE THREAD

**Issue by hadysata** [flutter/flutter#153314]
### Steps to reproduce

1. **Create a new Flutter project**.

2. **Run the attached code on Flutter 3.24.0**.

3. **Tap on the red square** within the app to trigger an animation:
   - This will rotate the square while applying a `ColorFiltered` widget.

4. **Monitor performance using Flutter's DevTools**:
   - Open the performance tab and observe the frame times and any jank indicators during the animation.

5. **Compare with Flutter 3.22.3**:
   - Switch to Flutter 3.22.3.
   - Run the same project and repeat the steps above.

6. **Observe the differences** in performance, particularly noting any jank or frame drops in the 3.24.0 version.

### Expected results

The animation involving the `ColorFiltered` widget should run smoothly without any noticeable jank or performance degradation in Flutter 3.24.0, just as it does in Flutter 3.22.3. The performance tab in Flutter's DevTools should not show any red jank frames, indicating that the frames are being rendered efficiently, regardless of the Flutter version.

### Actual results

In Flutter 3.24.0, the animation involving the `ColorFiltered` widget causes significant jank, which is reflected in the performance tab of Flutter's DevTools as red jank frames. This issue is not present in Flutter 3.22.3, where the same code runs smoothly without any performance problems. The regression appears to be specific to version 3.24.0, suggesting a potential issue with how `ColorFiltered` is being handled in this version.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  double turns = 0.0;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: GestureDetector(
        onTap: () {
          setState(() {
            turns = 1.0;
          });
        },
        child: AnimatedRotation(
          turns: turns,
          duration: const Duration(seconds: 4),
          child: ColorFiltered(
            colorFilter: const ColorFilter.mode(Colors.grey, BlendMode.modulate),
            child: Container(
              width: 400,
              height: 400,
              color: Colors.red,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

**Results of Running with Profile Mode on Android Emulator**

| Flutter Version | With `ColorFiltered` | Without `ColorFiltered` |
|-----------------|----------------------|-------------------------|
| **3.22.3**      | <img width="709" alt="3 22 3 - With ColorFiltered" src="https://github.com/user-attachments/assets/dabc56b2-e9c8-445f-bc41-83d698eaf9f0"> | <img width="682" alt="3 22 3 - No ColorFiltered" src="https://github.com/user-attachments/assets/7ebcef98-3488-4d86-b73e-b650505ce79b"> |
| **3.24.0**      | <img width="682" alt="3 24 0 - With ColorFiltered" src="https://github.com/user-attachments/assets/2b7e80a2-7045-4243-9536-19535498a1a2">   | <img width="682" alt="3 24 0 - No ColorFiltered" src="https://github.com/user-attachments/assets/711af7e9-a5ab-40b3-8d7a-f2c86bc48ab0"> |

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale
    en-SA)
    • Flutter version 3.24.0 on channel stable at
      /Users/Hadi/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (13 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/Hadi/Library/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/Hadi/Library/Android/Sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] VS Code (version 1.86.2)
    • VS Code at /Users/Hadi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554             •
      android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                      • macos                     •
      darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop)      • mac-designed-for-ipad     • darwin
      • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                         • chrome                    •
      web-javascript • Google Chrome 127.0.6533.99

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
Does this only reproduce on an Android emulator?

**Comment by huycozy** [comment]
@hadysata Could you confirm this on an Android physical device to see if it's different? I checked this on my device `Pixel 7, Android 14` (physical device), but I saw the opposite result:


| 3.24.0 | 3.22.3 |
| --------------- | --------------- |
<video src="https://github.com/user-attachments/assets/852491cb-2b97-426e-932c-38cbe1f03ab0"/> | <video src="https://github.com/user-attachments/assets/478d1970-2b1e-4102-b5a5-d58788e56ff7"/>

On 3.24.0, I saw there are some rasters and no jank. On 3.22.3, some janks appear.
