### ISSUE TITLE
[3.24 compilation issue] The markNeedsBuild method isn't defined for the RenderConstraintedLayoutBuilder class

### ISSUE THREAD

**Issue by natrayansf** [flutter/flutter#153339]
### Steps to reproduce

In our custom widgets, we used the RenderConstrainedLayoutBuilder class and invoked the markNeedsBuild method to update the layout dynamically based on the provided constraints. This ensured the widget rebuilt whenever its size constraints changed.

However, with the 3.24 release, we encountered a compilation issue because the markNeedsBuild method was removed from the RenderConstrainedLayoutBuilder class, **as introduced in this [commit](https://github.com/flutter/flutter/pull/149303)**. 

### Expected results

Advise on alternative methods to manage layout updates following removing markNeedsBuild in RenderConstrainedLayoutBuilder. 

We also used the rebuildIfNecessary method to resolve this, but the expected build is not being triggered as intended. We also tried element.markNeedsBuild instead of renderObject.markNeedsBuild. 

### Actual results

The markNeedsBuild method isn't defined for the RenderConstraintedLayoutBuilder class. 

![image](https://github.com/user-attachments/assets/4f638806-cd80-4915-b939-d7191839213b)

### Code sample

<details open><summary>Code sample</summary>

```dart
final RenderObjectElement? element = _key.currentContext as RenderObjectElement?;
if (element != null && element.mounted && element.renderObject.attached) {
      final RenderObject? renderObject = element.findRenderObject();
      if (renderObject != null && renderObject.attached && renderObject is RenderConstrainedLayoutBuilder) {
            renderObject.markNeedsBuild();
      }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/4f638806-cd80-4915-b939-d7191839213b)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS D:\1. Feature\framework_mark_needs_build> flutter doctor -v
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)     
    • Flutter version 3.24.0 on channel stable at D:\Applications\flutter_windows_3.22.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)    
    • Android SDK at C:\Users\NatrayanRamalingamNa.AzureAD\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.92.1)
    • VS Code at C:\Users\NatrayanRamalingamNa.AzureAD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.100
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.98

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS D:\1. Feature\framework_mark_needs_build>   
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report and identifying the root-cause.



> we encountered a compilation issue because the markNeedsBuild method was removed from the RenderConstrainedLayoutBuilder class, **as introduced in this [commit](https://github.com/flutter/flutter/pull/149303)**.

Based on this, I will label this bug and as regression for team's tracking.

/cc @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
Sorry for the breakage. 

>  invoked the markNeedsBuild method to update the layout dynamically based on the provided constraints
It sounds like `markNeedsLayout` should work? Given `rebuildIfNecessary()` is already in `performLayout`.

It seems you're doing something similar to `LayoutBuilder`. I'm curious what the use case is, does the layout builder widget not work for your use case?

**Comment by natrayansf** [comment]
Hi @LongCatIsLooong, 

We've created a custom render object in Flutter to demonstrate handling dynamic updates within a widget's rendering lifecycle. By overriding/invoking the markNeedsBuild method in the custom render object, we programmatically update properties like text, color, and drawing behavior directly during the rendering phase. This approach allows real-time updates to the visual output without relying on external state management, enabling precise control over how and when the UI is redrawn. 

**Custom sample:** [mark_needs_build.zip](https://github.com/user-attachments/files/16610966/mark_needs_build.zip)

Regards,
Natrayan

**Comment by LongCatIsLooong** [comment]
The code doesn't seem to register any layout callbacks so I don't see the need to use `RenderConstrainedLayoutBuilder`. Using a regular render object should work.
