### ISSUE TITLE
Flutter issue

### ISSUE THREAD

**Issue by minhajazeem91** [flutter/flutter#153390]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/3d5f1aa9-f7e9-441d-a3f0-a4c2c43bcd53)

### Expected results

Login Screen

### Actual results

https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+RPCError&body=%23%23+Command%0A%60%60%60sh%0Aflutter+run%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A
2.+...%0A3.+...%0A%0A%23%23+Logs%0ARPCError%0A%60%60%60console%0A%230++++++VmService._call+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A1774%3A7%29%0A%231++++++VmService.callS
erviceExtension+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A1726%3A14%29%0A%232++++++VmService.callMethod+%28package%3Avm_service%2Fsrc%2Fvm_service.dart%3A1717%3A12%29%0A%23
3++++++FlutterVmService.callMethodWrapper+%28package%3Aflutter_tools%2Fsrc%2Fvmservice.dart%3A501%3A28%29%0A%234++++++FlutterVmService.getFlutterViews+%28package%3Aflutter_tools%2F
src%2Fvmservice.dart%3A913%3A51%29%0A%235++++++HotRunner.attach+%28package%3Aflutter_tools%2Fsrc%2Frun_hot.dart%3A304%3A63%29%0A%3Casynchronous+suspension%3E%0A%236++++++RunCommand
.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Frun.dart%3A867%3A27%29%0A%3Casynchronous+suspension%3E%0A%237++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3
Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1408%3A27%29%0A%3Casynchronous+suspension%3E%0A%238++++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2F
src%2Fbase%2Fcontext.dart%3A153%3A19%29%0A%3Casynchronous+suspension%3E%0A%239++++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A212%3A13%29%0A%3Casynchronous
+suspension%3E%0A%2310+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A420%3A9%29%0A%3Casynchr
onous+suspension%3E%0A%2311+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A153%3A19%29%0A%3Casynchronous+suspension%3E%0A%2312+
++++FlutterCommandRunner.runCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A364%3A5%29%0A%3Casynchronous+suspension%3E%0A%2313+++++run.%3Canonymou
s+closure%3E.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Frunner.dart%3A130%3A9%29%0A%3Casynchronous+suspension%3E%0A%2314+++++AppContext.run.%3Canonymous+closure%3E+%28pac
kage%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A153%3A19%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60console%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel
+stable%2C+3.24.0%2C+on+Microsoft+Windows+%5BVersion+10.0.19045.4651%5D%2C+locale+en-US%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.24.0+on+channel+stable+at+C%3A%5Csrc%
5Cflutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Framework+revision+80c2e84975+%28
2+weeks+ago%29%2C+2024-07-30+23%3A06%3A49+%2B0700%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+b8800d88be%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+3.5.0%0A++++%1B%5B32m%
E2%80%A2%1B%5B39m+DevTools+version+2.37.2%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Windows+Version+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%1B%5B32m%5B%E2%9C%
93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+35.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+C%3A%5CUsers%5Cuser%5CAppData%5CLoc
al%5CAndroid%5Csdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platform+android-35%2C+build-tools+35.0.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5C
Android+Studio%5Cjbr%5Cbin%5Cjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.11%2B0--11852314%29%0D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+
All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrom
e%5CApplication%5Cchrome.exe%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Visual+Studio+-+develop+Windows+apps+%28Visual+Studio+Community+2022+17.10.5%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39
m+Visual+Studio+at+C%3A%5CProgram+Files%5CMicrosoft+Visual+Studio%5C2022%5CCommunity%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+Community+2022+version+17.10.35122.118%0A++++%1
B%5B32m%E2%80%A2%1B%5B39m+Windows+10+SDK+version+10.0.22621.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2024.1%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+S
ins.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.11%2B0--11852314%29%0D%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.92.1%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+C%3A%5CUsers%5Cuser%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3DDart-Code.flutter%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%284+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+sdk+gphone16k+x86+64+%28mobile%29+%E2%80%A2+emulator-5554+%E2%80%A2+android-x64++++%E2%80%A2+Android+15+%28API+35%29+%28emulator%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+%28desktop%29+++++++++++++%E2%80%A2+windows+++++++%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.19045.4651%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29++++++++++++++++++%E2%80%A2+chrome++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+127.0.6533.100%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Edge+%28web%29++++++++++++++++++++%E2%80%A2+edge++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+127.0.2651.86%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Network+resources%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+expected+network+resources+are+available.%0A%0A%1B%5B32m%E2%80%A2%1B%5B39m+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+2524052335ec76bb03e04ede244b071f1b86d190%0A%23%23%23+Plugins%0Apath_provider-2.0.15%0Apath_provider_android-2.2.10%0Apath_provider_foundation-2.4.0%0Apath_provider_linux-2.2.1%0Apath_provider_windows-2.0.7%0A%0A&labels=tool%2Csevere%3A+crash

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:ecommerce_store_horizon/app/modules/splash/bindings/splash_binding.dart';
import 'package:ecommerce_store_horizon/app/modules/splash/views/splash_view.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'app/DI_bindings/bindings.dart';
import 'app/routes/app_pages.dart';
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Get.put(ControllerBinding());
  runApp( MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});
  final ThemeData lightTheme = ThemeData.light();
  final ThemeData darkTheme = ThemeData.dark();

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(360, 690),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (context, child) {
        return GetMaterialApp(
          initialRoute: Routes.SPLASH,
          getPages: AppPages.routes,
          navigatorKey: Get.key,
          initialBinding: Get.put(SplashBinding()),
          title: "E-Commerce App",
          debugShowCheckedModeBanner: true,
          // You can use the library anywhere in the app even in theme
          theme: lightTheme,
          darkTheme: darkTheme,
          home: WillPopScope(
              onWillPop: () async {
                // Handle back button press globally
                // Add your desired behavior here
                Get.back();
                return true;
              },
              child: const SplashView()),

        );
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

.
![image](https://github.com/user-attachments/assets/3ca3a8c3-0916-4a0f-b8e3-5e675831f723)

</details>
.

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS F:\Mobile Applications\faida_bazaar_app> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@minhajazeem91 
This seems to be a tool crash issue resulting in `RPCError`. But you need to provide us proper steps to replicate that shows the error.
Also, the code sample you shared is not minimal and contains third party packages. I suggest to narrow down code by removing all third party implementations and then try to see if you still get same error not. If so, please file new issue with relevant details and not just paste the error link which is not readable. If you click on that link, it will direct you to file an issue with proper content.
Closing for now.
