### ISSUE TITLE
[Impeller] switch all scaling computations to use maxBasisXY instead of determinant.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#153451]
Otherwise we will not accurately capture scales that are < 1.

See discussion in https://github.com/flutter/engine/pull/54368#discussion_r1710031044

> I think so. Determinant of 2D matrices is the area of the (transformed) unit square which is pretty much the same thing, but it combines them geometrically so 2x in one direction balances 0.5 in the other. But matrix is a 3D thing so it becomes volume of the unit cube which might not be what we want. Or maybe it's OK since the volume of the cube is the area of the square times the height which is 1.0 - but still it will combine scales between the directions which is not what we want.

> So, I think MaxBasisXY is a better value to use.

> Really in all of these cases we should be doing separated 2D measurements rather than using the "max" or determinant. We should independently clamp each dimension separately.

**Comment by gaaclarke** [comment]
I don't see anyone else using the determinant for scaling similarly to the way we are doing it in the linked PR.  I suspect this issue was made as a TODO from the linked PR but it actually got done before the PR landed?

```
flutter aaclarke$ ag GetDeterminant
impeller/entity/contents/filters/local_matrix_filter_contents.cc
26:  if (matrix.GetDeterminant() == 0.0) {

impeller/entity/contents/filters/matrix_filter_contents.cc
117:  if (transform.GetDeterminant() == 0.0) {

impeller/geometry/matrix.h
296:  Scalar GetDeterminant() const;

impeller/geometry/matrix.cc
162:Scalar Matrix::GetDeterminant() const {
236:  if (perpectiveMatrix.GetDeterminant() == 0.0) {

impeller/geometry/geometry_unittests.cc
123:  ASSERT_EQ(matrix.GetDeterminant(), -1889);

display_list/utils/dl_matrix_clip_tracker.h
56:  bool is_matrix_invertable() const { return matrix_.GetDeterminant() != 0.0f; }

display_list/benchmarking/dl_transform_benchmarks.cc
460:    return transform.impeller_matrix.GetDeterminant() != 0.0f;

third_party/tinygltf/examples/common/imgui/ImGuizmo.cpp
249:      float GetDeterminant() const
344:         det = GetDeterminant();
```
