### ISSUE TITLE
Customize datePicker

### ISSUE THREAD

**Issue by deckvv** [flutter/flutter#153441]
### Use case

Hello!

Why are there so few options for customizing the widget datePicker? 

### Proposal

I want to centered ok/cancel buttons, but i cant find how to do this. If you now how to make it, I will be very grateful.

**Comment by darshankawar** [comment]
@deckvv 


> I want to centered ok/cancel buttons,

These are based on standard material design guidelines. 

> but i cant find how to do this. If you now how to make it, I will be very grateful.

You may ask this in support channels like StackOverflow to see if there's a workaround or a solution to achieve this.

**Comment by deckvv** [comment]
Thanks , I'll look for a way out
