### ISSUE TITLE
Select text and then drag on another text. Then I can't edit any more.

### ISSUE THREAD

**Issue by PhongNgo1776** [flutter/flutter#153489]
### Steps to reproduce

1. I paste a long text into the Text FIeld, 
2. Then double tap on 1 word to select text
3. Then I tap and drag on another place on the text
4. Select another text

### Expected results

I can edit: write text or delete text on text field.

### Actual results

Exception appeare and the pointer is lost. I can edit: write text or delete text on text field.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

https://github.com/user-attachments/assets/d75a2027-681a-4a70-a554-9a71cf7eedb3

![Screenshot 2024-08-15 at 12 50 12 PM](https://github.com/user-attachments/assets/78260d97-5fb4-4a0f-8431-da05e24b12f3)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
![Screenshot 2024-08-15 at 12 50 12 PM](https://github.com/user-attachments/assets/b3cbb41e-da3d-43e3-9c4b-19f459e7dff6)
<img width="660" alt="image" src="https://github.com/user-attachments/assets/8ae62ce6-af31-4c74-8797-d655747a181a">

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Thank you for the report! 

There is already a similar issue at https://github.com/flutter/flutter/issues/153458. The issue seems to be fixed on master so you can try switching to master channel and retry. 

Closing this issue as a duplicate, so please follow up on #153458 for further updates.
