### ISSUE TITLE
Analyzer incorrectly flags unused final field as uninitialized?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#153411]
In the engine -> framework roll at https://github.com/flutter/flutter/pull/153410, containing the Dart -> engine roll https://github.com/flutter/engine/pull/54541, containing commits https://dart.googlesource.com/sdk.git/+log/44635f897535..733062367c2e, it looks like the uninitialized final field error might be incorrect?

This commit looks related: https://dart.googlesource.com/sdk.git/+/c1976b097d1f85fe2c8fa4cab1d0d51cc7e92b42 cc @srawlins 

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8739656817167901393/+/u/run_test.dart_for_customer_testing_shard_and_subshard_None/stdout

https://github.com/superlistapp/super_editor/blob/bcba72823a3c21336960f0ac40a73d68d9034623/super_editor/lib/src/super_reader/super_reader.dart#L617

Reverting the Dart -> Engine roll here: https://github.com/flutter/engine/pull/54552

**Comment by srawlins** [comment]
That looks right. https://dart.googlesource.com/sdk.git/+/c1976b097d1f85fe2c8fa4cab1d0d51cc7e92b42 changes `unused_element` to `unused_element_parameter`. Since the `// ignore:` no longer applies, I believe the CI task has a `dart fix` step which now removes the unused parameter. Removing the unused parameter leaves the field now uninitialized.

**Comment by srawlins** [comment]
Sent a PR to super_editor, https://github.com/superlistapp/super_editor/pull/2239. But I imagine we need to revert https://dart.googlesource.com/sdk.git/+/c1976b097d1f85fe2c8fa4cab1d0d51cc7e92b42 as well.

**Comment by mkustermann** [comment]
> Sent a PR to super_editor, https://github.com/superlistapp/super_editor/pull/2239. But I imagine we need to revert https://dart.googlesource.com/sdk.git/+/c1976b097d1f85fe2c8fa4cab1d0d51cc7e92b42 as well.

Reverted in dart-lang/sdk@b888da751ed8f2174d2ef5bd50eacabb24979745

**Comment by a-siva** [comment]
Since the CL has been reverted, can this issue be closed ?

**Comment by zanderso** [comment]
Yes.
