### ISSUE TITLE
DropdownButton with long list scroll to end of list

### ISSUE THREAD

**Issue by alescdb** [flutter/flutter#15346]
## Steps to Reproduce
```
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new DropdownButton<int>(
        items: new List<DropdownMenuItem<int>>.generate(
          50,
          (int index) => new DropdownMenuItem<int>(
                value: index,
                child: new Text(index.toString()),
              ),
        ),
        onChanged: (int value) {},
      ),
    );
  }
```
## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [version 10.0.16299.248], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
[√] VS Code (version 1.20.1)
[√] Connected devices (1 available)

• No issues found!
```

![output](https://user-images.githubusercontent.com/5646825/37221089-fd093354-23c8-11e8-8725-ce4f43db2e94.gif)

**Comment by alescdb** [comment]
It might not be clear on my gif, but when you click/tap to open the DropdownButton, the list scrolls by "itself" to the last item.

**Comment by gerryhigh** [comment]
@mjohnsullivan Just wanted to tag you in this. I showed you this at IO18 and you said you'd triage it. Thanks

**Comment by alikopasa** [comment]
@alescdb did you solve this problem?

**Comment by alescdb** [comment]
@alikopasa as a temporary fix, I made a copy of the DropdownButton source (linked below) file in my project and I comment out the code pointed by @gerryhigh : 

```
    if (scrollController == null) {
      double scrollOffset = 0.0;
      /*
      if (preferredMenuHeight > maxMenuHeight)
        scrollOffset = selectedItemOffset - (buttonTop - menuTop);
      */
      scrollController = new ScrollController(initialScrollOffset: scrollOffset);
    }
```
Import the new file : 

```
import 'mydropdown.dart' as MyDropdown;
```

And changed the code to look something like this : 

```
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new MyDropdown.DropdownButton(
        items: new List<MyDropdown.DropdownMenuItem<int>>.generate(
          50,
          (int index) => new MyDropdown.DropdownMenuItem<int>(
                value: index,
                child: new Text(index.toString()),
              ),
        ),
        onChanged: (int value) {},
      ),
    );
  }
```
And it works :-) 

[mydropdown.zip](https://github.com/flutter/flutter/files/2058676/mydropdown.zip)

**Comment by paolosoares** [comment]
customer:mulligan has been hit by this as well

**Comment by zoechi** [comment]
@HansMuller

**Comment by ibhavikmakwana** [comment]
Facing the same problem

**Comment by vail130** [comment]
Any updates here? I'm facing the same issue.

**Comment by niceguy1** [comment]
same proble for me

**Comment by niceguy1** [comment]
same problem for me, notice that this bug exist in the flutter gallery app too

**Comment by niceguy1** [comment]
@alescdb the hack works but now its starts with the beginning of the list with each tap, it should start with the last parameter
i dont know how to do that

**Comment by LucasParsy** [comment]
I customized alescdb 's solution, instead of commenting all the part, I just removed the substraction at the ```scrollOffset``` calculation, and now the list scrolls to it's last chosen parameter.
@niceguy1 , this may be what you are looking for.

The scroll prioritizes the bottom element. It means that if you have a list of 50 items, and you choose the 2nd one, you will have the 2nd as a first element shown, and you will have to scroll up to see the first one.   

```dart
    if (scrollController == null) {
      double scrollOffset = 0.0;
      if (preferredMenuHeight > maxMenuHeight)
        scrollOffset = selectedItemOffset;  // - (buttonTop - menuTop);
      scrollController = new ScrollController(initialScrollOffset: scrollOffset);
    }
```

**Comment by LucasParsy** [comment]
if you're dropdown maniac, you can also put the selected choice in the middle,
by changing the ```selectedItemOffset``` declaration  in ```buildPage``` (line 317)

doing this:
```dart
    final double selectedItemOffset = math.max((selectedIndex - 5), 0) * _kMenuItemHeight + kMaterialListPadding.top;
```

will show 5 entries before the selected one, most likely showing the selected item in the middle of the list.
Of course, the effect can have a different effect depending  where you place your dropdown, the size of your list elements, maybe the device...
So it may not be a good idea to go this far in dropdown customization.

**Comment by niceguy1** [comment]
thanks @LucasParsy I'll check it out !!!
looks like exactly what I needed :))

**Comment by easazade** [comment]
this fix is ugly. problem still exists. this issue should be open
