### ISSUE TITLE
Flutter web release mode got this error when performing "signInWithPopup" (from firebase_auth & google_sign_in) : "UnImplementedError: signInWithPopup is only supported on web based platforms Flutter" 

### ISSUE THREAD

**Issue by jonathandarwin** [flutter/flutter#153409]
### Steps to reproduce

Flutter web release mode got this error when performing "signInWithPopup" (from firebase_auth & google_sign_in) : "UnImplementedError: signInWithPopup is only supported on web based platforms Flutter" 

And here are some facts that i found:
- It works fine in debug & profile mode
- I have another project with the same config & it works just fine somehow (fyi the sign in part is copy-pasted from this project)
- All authorized domain have been registered in both gcp & firebase auth console

### Expected results

Google sign-in popup should be shown in release mode

### Actual results

Google sign-in popup is not shown in release mode

### Code sample

<details open><summary>Code sample</summary>

```dart
FirebaseAuth auth = FirebaseAuth.instance;

if(kIsWeb) {
  GoogleAuthProvider authProvider = GoogleAuthProvider();
  authProvider.setCustomParameters({
    "prompt" : "select_account"
  });
  
  try {
    final UserCredential userCredential = await auth.signInWithPopup(authProvider);
    UserCredential? user = userCredential.user;
  } catch (e) {

  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.3 23D56 darwin-arm64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ Unable to get list of installed Simulator runtimes.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (4 available)            
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Since you are using `signInWithPopup` from [firebase_auth](https://pub.dev/packages/firebase_auth), please open an issue in the dedicated repository for better support: https://github.com/firebase/flutterfire/issues

Closing this as it's not a Flutter 1st party package issue.
