### ISSUE TITLE
Flutter upgrade issue (report ID: 4bdb170508c951a2)

### ISSUE THREAD

**Issue by Jacko1972** [flutter/flutter#15342]
## Steps to Reproduce

Ran flutter upgrade from Command Line

### **OUTPUT FROM CLI**
Last login: Fri Mar  9 16:02:34 on console
You have mail.
-----s-iMac:~ ----------$ flutter upgrade
Upgrading Flutter from /Users/----------/flutter...
Transitioning from 'alpha' to 'dev'...
git: Switched to a new branch 'dev'
git: Branch dev set up to track remote branch dev from origin.
From https://github.com/flutter/flutter
   3b8450340..f8ac23cd8  dev        -> origin/dev
   621a963e8..046c6d5f7  master     -> origin/master
 * [new tag]             v0.1.8     -> v0.1.8
 * [new tag]             v0.2.0     -> v0.2.0
 * [new tag]             v0.1.9     -> v0.1.9
Updating 3b8450340..f8ac23cd8
 103 files changed, 4054 insertions(+), 934 deletions(-)

Upgrading engine...
Downloading Dart SDK from Flutter engine a00f8e8bc0f3d08ec0c0ca24b01226441bcaf03a...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 43.5M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  7 43.5M    7 3278k    0     0  2015k      0  0:00:22  0:00:01  0:00:21 2014k
 15 43.5M   15 6958k    0     0  2650k      0  0:00:16  0:00:02  0:00:14 2649k
 24 43.5M   24 10.5M    0     0  2972k      0  0:00:15  0:00:03  0:00:12 2971k
 32 43.5M   32 13.9M    0     0  3091k      0  0:00:14  0:00:04  0:00:10 3091k
 40 43.5M   40 17.7M    0     0  3224k      0  0:00:13  0:00:05  0:00:08 3640k
 49 43.5M   49 21.4M    0     0  3314k      0  0:00:13  0:00:06  0:00:07 3737k
 57 43.5M   57 25.2M    0     0  3384k      0  0:00:13  0:00:07  0:00:06 3770k
 65 43.5M   65 28.7M    0     0  3409k      0  0:00:13  0:00:08  0:00:05 3727k
 74 43.5M   74 32.4M    0     0  3451k      0  0:00:12  0:00:09  0:00:03 3784k
 82 43.5M   82 35.9M    0     0  3461k      0  0:00:12  0:00:10  0:00:02 3728k
 88 43.5M   88 38.4M    0     0  3391k      0  0:00:13  0:00:11  0:00:02 3494k
 96 43.5M   96 42.1M    0     0  3421k      0  0:00:13  0:00:12  0:00:01 3478k
100 43.5M  100 43.5M    0     0  3420k      0  0:00:13  0:00:13 --:--:-- 3440k
Building flutter tool...
Downloading package sky_engine...

Flutter 0.0.22-pre.1 • channel alpha • https://github.com/flutter/flutter.git
Framework • revision 553fc4264e (8 days ago) • 2018-03-05 23:27:57 +0100
Engine • revision a00f8e8bc0
Tools • Dart 2.0.0-dev.16.0

Running flutter doctor...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 4bdb170508c951a2)
Crash report written to /Users/----------/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
-----s-iMac:~ ----------$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.2.0, on Mac OS X 10.13.3 17D102, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
-----s-iMac:~ ----------$ flutter doctor --android-licenses
3 of 6 SDK package licenses not accepted. 100% Computing updates...             
Review licenses that have not been accepted (y/N)? y

### **LICENCE OUTPUT REMOVED...**

All SDK package licenses accepted

-----s-iMac:~ ----------$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.2.0, on Mac OS X 10.13.3 17D102, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

### **RUNNING FLUTTER DOCTOR -V**

-----s-iMac:~ ----------$ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.0, on Mac OS X 10.13.3 17D102, locale en-GB)
    • Flutter version 0.2.0 at /Users/----------/flutter
    • Framework revision f8ac23cd86 (4 days ago), 2018-03-05 23:27:57 +0100
    • Engine revision a00f8e8bc0
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/----------/bin/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.3
    • ANDROID_HOME = /Users/----------/bin/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • IntelliJ at /Users/----------/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

### **GENERATED CRASH LOG**
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter upgrade

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/----------/flutter/bin/cache/artifacts/engine/darwin-x64/dart-sdk/bin/dart.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      Cache.engineDartVersion (package:flutter_tools/src/cache.dart:139)
#3      FlutterVersion.engineDartVersion (package:flutter_tools/src/version.dart:86)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:215)
<asynchronous suspension>
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:106)
<asynchronous suspension>
#6      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:80)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:219)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#24     main (file:///Users/----------/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for /Users/----------/flutter/bin/cache/artifacts/engine/darwin-x64/dart-sdk/bin/dart.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      Cache.engineDartVersion (package:flutter_tools/src/cache.dart:139)
#3      FlutterVersion.engineDartVersion (package:flutter_tools/src/version.dart:86)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:215)
<asynchronous suspension>
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:106)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:236)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:236)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:211)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:166)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:93)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#25     main (file:///Users/----------/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

### **END OF CRASH LOG...**

-----s-iMac:~ ----------$ flutter analyze -v
```
[  +17 ms] [/Users/----------/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] [/Users/----------/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[        ] [/Users/----------/flutter/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/----------/flutter/] git log -n 1 --pretty=format:%H
[ +141 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] f8ac23cd8646538634f63032df4bfaf3b597007d
[        ] [/Users/----------/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 days ago
[   +1 ms] [/Users/----------/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +488 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.2.0-0-gf8ac23cd8
[+1726 ms] /Users/----------/flutter/bin/cache/dart-sdk/bin/dartanalyzer /Users/----------
[ +224 ms] Analyzing /Users/----------...
[+1239326 ms] Unhandled exception:
[        ] FileSystemException: Directory listing failed, path = '/Users/----------/Library/Saved Application State/com.bitrock.appinstaller.savedState' (OS Error: Permission denied, errno = 13)
[        ] #0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:34)
[        ] #1      _Directory.listSync (dart:io/directory_impl.dart:214)
[        ] #2      Driver._collectFiles (package:analyzer_cli/src/driver.dart:605)
[        ] #3      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:314)
[        ] <asynchronous suspension>
[        ] #4      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:228)
[        ] <asynchronous suspension>
[        ] #5      Driver.start (package:analyzer_cli/src/driver.dart:197)
[        ] <asynchronous suspension>
[        ] #6      main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analyzer_cli/bin/analyzer.dart:13)
[        ] <asynchronous suspension>
[        ] #7      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
[        ] #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
[  +84 ms] "flutter analyze" took 1,241,207ms.
(Ran in 1239.6s)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:132)
<asynchronous suspension>
#2      AnalyzeCommand.runCommand (package:flutter_tools/src/commands/analyze.dart:70)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      new Future.sync (dart:async/future.dart:222)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#11     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#20     main (file:///Users/----------/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


[ +242 ms] ensureAnalyticsSent: 237ms
[   +2 ms] exiting with code 255
```

**Comment by zoechi** [comment]
I think that is the version that caused update issues for many.
I'd suggest you purge the Flutter installation and `git clone` it again.

**Comment by Jacko1972** [comment]
Upgrading Flutter from /Users/---/flutter...
From https://github.com/flutter/flutter
   f8ac23cd8..74ed6a1d9  dev        -> origin/dev
   ded390510..340c68038  master     -> origin/master
 * [new branch]          revert-15525-killermonk-dev -> origin/revert-15525-killermonk-dev
 * [new tag]             v0.2.1     -> v0.2.1
Updating f8ac23cd8..74ed6a1d9
 202 files changed, 1875 insertions(+), 770 deletions(-)

Upgrading engine...
Downloading Dart SDK from Flutter engine 24cf8ebd8621713a6936df783dad5019f52bc85e...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 43.6M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  3 43.6M    3 1422k    0     0  1093k      0  0:00:40  0:00:01  0:00:39 1093k
  8 43.6M    8 3790k    0     0  1649k      0  0:00:27  0:00:02  0:00:25 1649k
 14 43.6M   14 6558k    0     0  1985k      0  0:00:22  0:00:03  0:00:19 1985k
 20 43.6M   20 9150k    0     0  2126k      0  0:00:21  0:00:04  0:00:17 2126k
 26 43.6M   26 11.7M    0     0  2269k      0  0:00:19  0:00:05  0:00:14 2650k
 31 43.6M   31 13.9M    0     0  2261k      0  0:00:19  0:00:06  0:00:13 2565k
 39 43.6M   39 17.0M    0     0  2396k      0  0:00:18  0:00:07  0:00:11 2739k
 46 43.6M   46 20.1M    0     0  2490k      0  0:00:17  0:00:08  0:00:09 2823k
 53 43.6M   53 23.3M    0     0  2572k      0  0:00:17  0:00:09  0:00:08 2956k
 60 43.6M   60 26.4M    0     0  2628k      0  0:00:17  0:00:10  0:00:07 3009k
 67 43.6M   67 29.5M    0     0  2676k      0  0:00:16  0:00:11  0:00:05 3198k
 74 43.6M   74 32.4M    0     0  2699k      0  0:00:16  0:00:12  0:00:04 3142k
 81 43.6M   81 35.4M    0     0  2727k      0  0:00:16  0:00:13  0:00:03 3120k
 87 43.6M   87 38.1M    0     0  2732k      0  0:00:16  0:00:14  0:00:02 3031k
 92 43.6M   92 40.4M    0     0  2709k      0  0:00:16  0:00:15  0:00:01 2875k
 99 43.6M   99 43.4M    0     0  2729k      0  0:00:16  0:00:16 --:--:-- 2849k
100 43.6M  100 43.6M    0     0  2726k      0  0:00:16  0:00:16 --:--:-- 2807k
Building flutter tool...
Downloading package sky_engine...

Flutter 0.2.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision f8ac23cd86 (11 days ago) • 2018-03-14 16:13:12 -0700
Engine • revision 24cf8ebd86
Tools • Dart 2.0.0-dev.32.0.flutter-ee15c8eb68

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.2.2-pre.2, on Mac OS X 10.13.3 17D102, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

Seems to be upgrading ok now
