### ISSUE TITLE
Link issue on web with semantic

### ISSUE THREAD

**Issue by msutharworkspace** [flutter/flutter#153428]
### Steps to reproduce

1. Add **RendererBinding.instance.ensureSemantics();**
2. Add anylin in MarkdownBody widget.

```dart
 const MarkdownBody(
    data: 'https://pub.dev/packages/flutter_markdown/versions',
  )
```
3. Observe the issue:

> <a **href="#"** id="flt-semantic-node-7" aria-label="https://pub.dev/packages/flutter_markdown/versions" flt-tappable="" style="display: block; position: absolute; width: 355px; height: 26px; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, -4, -3); pointer-events: all;"></a>

### Expected results

><a **href="https://pub.dev/packages/flutter_markdown/versions"** id="flt-semantic-node-7" aria-label="https://pub.dev/packages/flutter_markdown/versions" flt-tappable="" style="display: block; position: absolute; width: 355px; height: 26px; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, -4, -3); pointer-events: all;"></a>

It should add actual link in href attribute instead for #.

### Actual results

<img width="1534" alt="Screenshot 2024-08-14 at 6 02 06 AM" src="https://github.com/user-attachments/assets/a85eb2c5-77e9-4313-9d71-fe12c7ff418f">

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  RendererBinding.instance.ensureSemantics();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: const MarkdownBody(
        data: 'https://pub.dev/packages/flutter_markdown/versions',
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @msutharworkspace 
I'm using the latest package version `flutter_markdown: ^0.7.3+1` and Flutter master channel `3.24.0-1.0.pre.575` but I see the HTML `a` tag is not similar to your actual result above:

```html
<a id="flt-semantic-node-5" flt-tappable="" style="display: block; position: absolute; overflow: visible; width: 355px; height: 26px; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, -4, -3); pointer-events: all;">https://pub.dev/packages/flutter_markdown/versions</a>
```

What is your package and Flutter versions? Can you update the the latest and confirm?

**Comment by msutharworkspace** [comment]
Flutter version: 3.19.6
flutter_markdown: ^0.7.0

@huycozy

**Comment by huycozy** [comment]
Can you please try upgrading Flutter and confirm this? I think semantics have been changed on new Flutter version. And if the result is similar to mine above, does it work for you?

**Comment by msutharworkspace** [comment]
Ok Thanks i will check.
