### ISSUE TITLE
AnimatedList with stream data

### ISSUE THREAD

**Issue by lucasjinreal** [flutter/flutter#153440]
### Use case

As this issue talks: https://github.com/flutter/flutter/issues/26708

it was closed, but AnimatedList nowday tooooo cubersome to dealing with stream data.

### Proposal

A simplified AnimatedList widget would be helpful

**Comment by darshankawar** [comment]
@lucasjinreal 
There's a community package that offers this feature https://pub.dev/packages/animated_stream_list_nullsafety/versions that you can check and see if it helps to achieve your use case or not.

**Comment by lucasjinreal** [comment]
This lib is not maintain any longer, in fact, there many such request lib but none of them maintrained any more.

In such case, why not flutter consider provide an official one

**Comment by darshankawar** [comment]
See if https://github.com/flutter/flutter/issues/128241 issue is similar / resembles your case or not.
