### ISSUE TITLE
JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by ynskhrmn0** [flutter/flutter#153493]
### Steps to reproduce

Hello, im using Manjaro operating system on my computer. İm new in Linux. I wanted to use flutter (vs code) to develop a mobile app. 

### Actual results

I did everything for installation on Flutter Installation Docs with no issue. But when i try to run an example code, i get the output below.

```
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...

ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-21-openjdk/

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Error: Gradle task assembleDebug failed with exit code 1

Exited (1).
```

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

``Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on Freedesktop SDK 23.08 (Flatpak runtime) 6.9.12-1-MANJARO, locale tr_TR.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ✗ Cannot execute /usr/lib/jvm/java-21-openjdk/bin/java to determine the version
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 4 categories.
```

</details>

**Comment by darshankawar** [comment]
> [!] Android Studio (not installed)

@ynskhrmn0 Your flutter doctor says AS is not installed. Please provide us `flutter doctor -v` and make sure AS is properly installed. Your AS version assumes your Java JDK version. Given your logs, the JAVA_HOME that sdkmanager is finding  doesn't look like one that points to a Java installation that comes bundled with Android Studio.

**Comment by ynskhrmn0** [comment]
> > [!] Android Studio (not installed)
> 
> @ynskhrmn0 Your flutter doctor says AS is not installed. Please provide us `flutter doctor -v` and make sure AS is properly installed. Your AS version assumes your Java JDK version. Given your logs, the JAVA_HOME that sdkmanager is finding doesn't look like one that points to a Java installation that comes bundled with Android Studio.

Im sure my AS is installed. But flutter doctor didn't see my AS. You think the versions are not compatible? Sorry for my bad english.

**Comment by darshankawar** [comment]
Looks like it is a config issue at your end or maybe the setup didn't properly install. Please follow https://flutter-ko.dev/get-started/install/linux
