### ISSUE TITLE
Issue from website page Fetch data from the internet

### ISSUE THREAD

**Issue by mrbm** [flutter/flutter#15341]
From URL: https://flutter.io/cookbook/networking/fetch-data.md

Would be great for newbies of how to access this data...how does one call Future...for newbies its not fully clear how to use this.

**Comment by brianegan** [comment]
Hah, dang it! Originally had that in there and took it out. I'll add it back in :)

**Comment by brianegan** [comment]
Fixed as part of https://github.com/flutter/website/pull/884
