### ISSUE TITLE
`flutter test` does not produce colorized output correctly

### ISSUE THREAD

**Issue by PIG208** [flutter/flutter#153483]
### Steps to reproduce

1. Install tmux and launch it: `tmux -c bash`
2. Go to a flutter project that contains some tests
3. Run `flutter test`
4. Run `dart test`

### Expected results

The output from both `flutter test` and `dart test` should be colorized.

### Actual results

Only the output from `dart test` is colorized. (`dart test` might fail or do not work, but the point is `dart test` produces colorized output.)

After preliminary debugging session shows that you can get colorized output from tmux with the config `set -g default-terminal "screen-256color"`. This sets the environment variable `TERM` to `screen-256color`. Before, it was `tmux-256color`, which did not work for `flutter test`, but worked for `dart test`.

### Code sample

<details open><summary>Code sample</summary>

This behavior is not specific to the test code being run. But rather the terminal used to run `flutter test`.

The codebase being tested in the screenshots is https://github.com/zulip/zulip-flutter.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

- `flutter test`
![image](https://github.com/user-attachments/assets/3c8f65d5-ceb8-44bd-8d19-4547e39b2ede)

- `dart test` _(ignore the errors)_
![image](https://github.com/user-attachments/assets/0e5e7df6-d5bb-4d5d-bafe-a0e2ae28f8f0)

</details>

### Logs

<details open><summary>Logs</summary>

```console
$ echo $TERM
tmux-256color
$ flutter test
... (see screenshots) ...
$ dart test
... (see screenshots) ...
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel main, 3.24.0-1.0.pre.575, on Debian GNU/Linux 12 (bookworm) 6.1.0-23-amd64, locale en_US.UTF-8)
    • Flutter version 3.24.0-1.0.pre.575 on channel main at /home/zixuan/.local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 593729165d (27 hours ago), 2024-08-14 09:13:34 +0800
    • Engine revision 019f9e3f07
    • Dart version 3.6.0 (build 3.6.0-146.0.dev)
    • DevTools version 2.38.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/zixuan/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/zixuan/.local/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/zixuan/.local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.94.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 12 (bookworm) 6.1.0-23-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 127.0.6533.72

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. 

> After preliminary debugging session shows that you can get colorized output from tmux with the config `set -g default-terminal "screen-256color"`. This sets the environment variable `TERM` to `screen-256color`. Before, it was `tmux-256color`, which did not work for `flutter test`, but worked for `dart test`.

This seems similar to https://github.com/flutter/flutter/issues/142861



> 3\. Run `flutter test`

Is this only specific to `flutter test` or with other flutter commands as well ? such as `flutter doctor` as linked above ?

**Comment by darshankawar** [comment]
Ok, let's follow-up in the linked issue for further updates. 
Closing this in favor of https://github.com/flutter/flutter/issues/142861. If you disagree, write in comments and I'll reopen it.
