### ISSUE TITLE
Documentation broken for all Flutter packages on dartdocs.org

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#15354]
None of the documentation referenced from pub.dartlang.org works for packages labeled as `Flutter` only (they seem to work if they also have the `Web` label). Running dartdoc locally for the repository works.

To reproduce, go to a package and click the Documentation link. For example:
https://pub.dartlang.org/packages/url_launcher or
https://pub.dartlang.org/packages/spritewidget

Both have Dartdoc formatted comments.
Error messages here:
https://www.dartdocs.org/documentation/url_lancher/0.4.2+2/log.txt
https://www.dartdocs.org/documentation/spritewidget/0.9.13/log.txt

**Comment by zoechi** [comment]
I believe this is a dup of dart-lang/pub-dartlang-dart#958

**Comment by Hixie** [comment]
This seems to work now (at least for spritewidget).
