### ISSUE TITLE
TextField: Selection of text content not possible under certain circumstances on IOS (Regression 3.24)

### ISSUE THREAD

**Issue by 2S-Software** [flutter/flutter#153545]
### Steps to reproduce

1. Enter Text like 'MyText' in a TextField on iOS (Android, Windows has no issues)
2. Select the whole word 'MyText' (double tap)

![36547289-22AB-4D31-B5F4-39B59E20B679_1_201_a](https://github.com/user-attachments/assets/f21ad04f-51da-45bc-90a5-3e990b15f4b7)

4. Now reduce the selection two some characters

![110A05B3-82FF-4640-A92E-B506D0FC0ABA_1_201_a](https://github.com/user-attachments/assets/82c5c9e8-5289-4eee-b228-334fd212faaa)

5. Set the cursor to the end of the text

![71173975-8EF9-4764-83A0-0F21A2C98DE1_1_201_a](https://github.com/user-attachments/assets/86b3df95-17cc-4a4f-9384-2e23d2803d8c)

7. From now on, no more selections can be made in the textfield. 
For example, try to select the last 3 chars in this textfield.

### Expected results

Selections in TextField should always be possible

### Actual results

After the above steps, no more content can be selected in the TextField.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _controller = TextEditingController(text: 'MyText');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              controller: _controller,
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-x64, locale de-CH)
    • Flutter version 3.24.0 on channel stable at /Users/stefan/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/stefan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • iPhone von Stefan (mobile) • 00008030-000454903EF8802E • ios        • iOS 17.5.1 21F90
    • macOS (desktop)            • macos                     • darwin-x64 • macOS 14.5 23F79 darwin-x64
    ! Error: Browsing on the local area network for iPad von Stefan. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @2S-Software 
This seems to be similar to https://github.com/flutter/flutter/issues/151943 which was confirmed as fixed on master. So can you switch to latest master and re-run your scenario to confirm ?

`flutter channel master`
`flutter upgrade`

**Comment by 2S-Software** [comment]
Thanks for your fast answer. I checked my example on the latest master channel. 

But the issue still exists on the master channel. This is therefore a different bug.

By the way, the issue is also present in the productive Google Ads app (built with Flutter) in the search field, for example.

**Comment by huycozy** [comment]
@2S-Software I checked this on `Channel master, 3.24.0-1.0.pre.623` but didn't see the issue as reported. I still can select text again after moving cursor to the end, please watch my demo video.

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/a986b7a0-36c2-439f-8aac-cdbd26fd0cd3

</details>

Can you please provide the output of `flutter doctor` after switching channels? Do you see any exception from the output console when the issue occurs on master?

**Comment by 2S-Software** [comment]
Sorry, I don't know what I did wrong before. But now it works with master 3.24.0-1.0.pre.624 in my simulator and on my test device. Thank you very much for your work!

So I close this issue.
