### ISSUE TITLE
Tooltip is not shown consistently on entire IconButton

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#153544]
### Steps to reproduce

1. Add a tooltip message to IconButton using the `tooltip` property
2. Hover over the IconButton with the mouse
3. Observe that the tooltip is only shown when directly hovering the icon, not the entire tap area

### Expected results

The tooltip to be always visible when on any clickable area of the icon button.

### Actual results

The tooltip only shows when hovering the icon/content.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(colorSchemeSeed: Colors.blue),
      home: Scaffold(
        body: Center(
          child: IconButton.filled(
            icon: Icon(Icons.add),
            onPressed: () {},
            tooltip: "Tooltip",
          ),
        ),
      ),
    ),
  );
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<table>
<tr>
<td>

![image](https://github.com/user-attachments/assets/b35ef8c9-415f-45b9-9f84-d56524c32143)

</td>

<td>

![image](https://github.com/user-attachments/assets/cd19021c-51be-48a4-bef7-7fed84c0d23b)

</td>
</tr>
</table>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.24.0-1.0.pre.575, on Void Linux 6.6.46_1, locale en_US.UTF-8)
    • Flutter version 3.24.0-1.0.pre.575 on channel master at $HOME/.local/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 593729165d (2 days ago), 2024-08-14 09:13:34 +0800
    • Engine revision 019f9e3f07
    • Dart version 3.6.0 (build 3.6.0-146.0.dev)
    • DevTools version 2.38.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at $HOME/.local/lib/android-sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: $HOME/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.30.1
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2024.1)
    • Android Studio at $HOME/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2024.1)
    • IntelliJ at $HOME/.local/share/JetBrains/Toolbox/apps/intellij-idea-community-edition
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Void Linux 6.6.46_1
    • Chrome (web)    • chrome • web-javascript • Chromium 127.0.6533.72

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @Craftplacer 
I checked this issue on some platforms (macOS, Web, Linux) but I saw tooltip still shows when I hover over entire IconButton:

![Screenshot 2024-08-16 at 17 14 22](https://github.com/user-attachments/assets/b4cb741e-9ddb-4df5-858b-ed8d35cb564a)

Are you seeing this error on Linux or Web app target? Does this issue appear on previous Flutter versions?

**Comment by huycozy** [comment]
I can see the tooltip still shows in non-Icon area but it is inconsistent as it disappears suddenly. However, if I hover over Icon area, the tooltip persists. I enabled Devtools Overlay guideline to see it more clearly.

https://github.com/user-attachments/assets/fde40a95-c574-441d-87f8-2e2c3fa92caf

Reproduced this on: `Channel master, 3.24.0-1.0.pre.623`
