### ISSUE TITLE
Gallery App has Buttons

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1535]
- [x] Drop down
- [x] Flat
- [x] Raised
- [x] Floating Action Button

**Comment by sethladd** [comment]
Drop down exists, in its own section. Probably want to put that in a Buttons section with the rest of the buttons.

**Comment by HansMuller** [comment]
All but toggle buttons were added in https://github.com/flutter/flutter/pull/1703

**Comment by mpcomplete** [comment]
By "Toggle" buttons, are you referring to [switches](https://www.google.com/design/spec/components/selection-controls.html#selection-controls-switch), buttons that can [toggle](https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html&active=paper-button) their `raised` state, or [grouped toggle buttons](https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons)? I'm looking for examples of the latter and coming up short. Angular and polymer don't have a dedicated widget for them, and I can't find an app that uses them.

**Comment by HansMuller** [comment]
The mobile version of Google docs uses toggle button groups when the keyboard is up.

![screen](https://cloud.githubusercontent.com/assets/1377460/13832426/579853fa-eb99-11e5-9e95-ab0c48d6be37.png)

**Comment by sethladd** [comment]
Also, toggle buttons are spec'ed here: https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons

**Comment by sethladd** [comment]
Added the Floating Action Button transitions (from https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions)

**Comment by sethladd** [comment]
Buttons are in! (modulo toggle buttons: https://github.com/flutter/flutter/issues/3959)

See https://github.com/flutter/flutter/issues/3960 for fancy FAB transitions.
