### ISSUE TITLE
Color space documentation

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#153517]
(related: #55092)

<br>

According to [flutter.dev/go/wide-gamut-framework](https://flutter.dev/go/wide-gamut-framework), Flutter currently supports the Display P3 color space for images, but not for widgets.

I went to [wide-gamut.com](https://www.wide-gamut.com/test) and found 2 images:

_sRGB_
![sRGB](https://www.wide-gamut.com/assets/test/rgb-sRGB.jpg)

_Display P3_
![Display P3](https://www.wide-gamut.com/assets/test/rgb-DisplayP3.jpg)

I took a look at these images using Google Chrome on Windows:
- They look exactly the same on my [desktop monitor](https://www.lg.com/us/monitors/lg-32ul500-w-4k-uhd-monitor).
- But on my [OLED laptop](https://www.asus.com/laptops/for-home/zenbook/zenbook-flip-13-ux363-11th-gen-intel/) screen, the Display P3 image has more vibrant colors.

<br>

# Flutter (Windows) does not use sRGB

I decided to test out Flutter's current color gamut.

1. Created a [very simple app](https://dartpad.dev/?id=a26066110b05642ae0cc9e2b94f16abb)
2. Ran it on Windows using the OLED laptop
3. Moved it to overlap the [wide-gamut.com](https://www.wide-gamut.com/test) page and took a screenshot
4. used Photoshop[^1] to add color codes to the image

<br>

Here's the result:
![color space test](https://github.com/user-attachments/assets/504845a8-d8c9-4425-b5b0-b7e0879bf53f)

<br>

It turns out that the `Color` class doesn't use sRGB—it takes advantage of my full OLED gamut! I also discovered that when an image has an sRGB annotation, Google Chrome will change a vibrant red `#FF0000` to a more dull color `#E93323` to match the standard RGB gamut, but Flutter will not.

Hopefully the [color gamut design doc](https://flutter.dev/go/wide-gamut-framework) (and perhaps also the [`Color`](https://api.flutter.dev/flutter/dart-ui/Color-class.html) class documentation) can be updated to reflect this information.

[^1]: I used [Photopea](https://www.photopea.com/), a less-expensive Photoshop clone, to make the above image 🙂

**Comment by jonahwilliams** [comment]
The color class does use sRGB, especially on non-Impeller platforms where there is no wide gamut support.

**Comment by nate-thegrate** [comment]
> The color class does use sRGB, especially on non-Impeller platforms where there is no wide gamut support.

@jonahwilliams thanks for making that distinction. I ran [the same app](https://dartpad.dev/?id=a26066110b05642ae0cc9e2b94f16abb) on web, and the Flutter widgets were changed to use `#E93323` (the dull sRGB color).

**Comment by jonahwilliams** [comment]
Impeller can support either sRGB or extended sRGB. iOS platforms use extended sRGB by default with Impeller. Whereas on Android and others regular sRGB is used. I'm not sure how you're testing Impeller on desktop platforms though, it is only supported on iOS/Android currently.

**Comment by nate-thegrate** [comment]
Oh dang—all this time I thought the Windows platform used impeller, my bad 😅

<br>

Regardless, it seems like
> The color class uses sRGB on non-Impeller platforms where there is no wide gamut support

implies that the color class does not always use sRGB.

**Comment by jonahwilliams** [comment]
> implies that the color class often does not use sRGB.

I'm not sure what you mean. The dart:ui Color class is sRGB. Even if the output surface is extended sRGB, its still just sRGB

**Comment by nate-thegrate** [comment]
| Input color: #FF0000 | LCD screen (sRGB gamut) | OLED screen (infinite contrast ratio) |
|---|---|---|
| JPEG tagged as sRGB | `#FF000000` | `#E93323` (color is adjusted to sRGB gamut) |
| JPEG tagged as Display P3 | `#FF000000` | `#FE000000` (nearly identical to the input) |
| Flutter widget (Windows) | `#FF000000` | `#FF000000` |
| Flutter widget (Web) | `#FF000000` | `#E93323` (color adjusted to sRGB gamut) |

I wish I understood more about this behavior.

**Comment by jonahwilliams** [comment]
Is your monitor doing some additional post processing that the screen capture tool is picking up?

**Comment by nate-thegrate** [comment]
A Display P3 JPEG shows up slightly differently based on whether it's viewed from within Photopea, Google Chrome, or Flutter.

This would imply that the post-processing is being done by the application displaying the image, rather than the monitor itself.

**Comment by jonahwilliams** [comment]
It doesn't really imply that at all, because those applications may support different surface color spaces. While Flutter will use sRGB, Chrome or Photopea might be using different color spaces et cetera.

**Comment by nate-thegrate** [comment]
> Flutter will use sRGB

I think it's more accurate to say that Flutter *might* use sRGB, since the color is adjusted to the sRGB gamut in a Flutter web app, but not in a Flutter Windows app.

**Comment by jonahwilliams** [comment]
I think you'd need to be more specific about what "use" means here. The dart:ui Color class is absolutely positively sRGB right now. The color space of the onscreen surface is not documented, but may be sRGB or extended sRGB. I don't really know why the colors you're getting look the way they do on windows.

Its possible there is a bug/misconfiguration.

**Comment by nate-thegrate** [comment]
Sounds good to me.

It's tricky to talk about color spaces, since often there are multiple differences between them:
1. The convention for storing color values (e.g. 6-digit hex codes or floating point values)
2. The output contrast ratio

You're absolutely right that with regards to number 1, Flutter is using the sRGB convention.
On the other hand, [the issue that talks about 25% more colors](https://github.com/flutter/flutter/issues/55092) has a focus on number 2, which according to my recent findings is inconsistent across Flutter platforms.

Luckily, the current plan of the [design doc](https://flutter.dev/go/wide-gamut-framework) is to use `double` values for A / R / G / B, which I believe to be an excellent future-proof solution 👍

**Comment by jonahwilliams** [comment]
That change will give Color objects an explicit color space parameter: all existing colors will be sRGB.

The bit depth of the components is not directly related to color spaces. display p3 can also be encoded in a 32 bit format.

**Comment by nate-thegrate** [comment]
If the explicit goal of the current `Color` class is for output colors to fit within the sRGB gamut, then I believe what you said earlier about a bug/misconfiguration is correct, since the Flutter Windows platform is showing colors outside that range.

As an app developer, I'm personally a huge fan of that misconfiguration: ideally, I'd like a `Color` class that perfectly maps to the device's output, rather than being unnecessarily narrow (less vibrant colors) or too wide (where some colors are "clipped", resulting in ugly photos/gradients).
That being said, there is value to giving an image a consistent appearance across all devices, and being able to match image colors in the app.

**Comment by nate-thegrate** [comment]
Based on information that @jonahwilliams shared, it looks like what I've observed is not intended behavior that we would want to document.

**Comment by jonahwilliams** [comment]
I think we do need a way to document and query what the onscreen surface color is, as this will impact what, say, a shader will output. Maybe on window?

**Comment by nate-thegrate** [comment]
Yeah, it looks like [`window`](https://api.flutter.dev/flutter/dart-ui/window.html) is deprecated, but something like that would be great to have!
