### ISSUE TITLE
Can't play drm video in ios, it appears try playing video in safari

### ISSUE THREAD

**Issue by Sayed-Shalan** [flutter/flutter#153535]
### Steps to reproduce

This is the url
https://player.vdocipher.com/v2/?otp=20160313versASE323JUpwnPCbLxJRPo6zVMsLpUds1iJwh4wPkmg8LzvEitnvSx&playbackInfo=eyJ2aWRlb0lkIjoiMGI1MTRkM2E4MzI0ZGFlZjgzM2UyZDJlMWQ1ODE4ZjgifQ==

### Expected results

Video played successfully in webview 

### Actual results

It says try playing video in safari browser

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
This is a limitation of webviews in iOS in general and not an issue with webview flutter. You can try playing the video in other webview test applications on the the appstore and you will get the same issue. 

Closing from here as this is not a flutter issue. 

Thank you
