### ISSUE TITLE
[Impeller] GLES only rendering bug when switching to DL provided depth values.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#153504]
The test is impeller_Play_AiksTest_CanRenderDifferenceClips_OpenGLES . It looks like the entities after the clip restore don't have the right value? Not sure.

![image](https://github.com/user-attachments/assets/ea334eda-083f-4f5e-903e-b3b49554e9ae)

**Comment by jonahwilliams** [comment]
@chinmaygarde might be something to do with the depth clamp or depth clamp values.

We could be missing some sort of normalization.

**Comment by jonahwilliams** [comment]
I've confirmed that this only happens with path draws, and not with rectangular draws. I suspect a problem in StC interaction with depth clips.

**Comment by chinmaygarde** [comment]
We might be investigating the same issue https://github.com/flutter/flutter/issues/157885. I'm trying to compare the Metal commands emitted by Angle and our Metal backend directly to see where the mismatch is. The issue does reproduce.

**Comment by jonahwilliams** [comment]
I think its something dumb: https://github.com/flutter/engine/pull/56310#issuecomment-2452332699

**Comment by jonahwilliams** [comment]
right now if I save clip draw restore draw I can observe that clip 1 and draw 1 end up with the same depth value. i don't know why this works in metal/vulkan and not GL...

**Comment by chinmaygarde** [comment]
> i don't know why this works in metal/vulkan and not GL...

Yeah, that's the worrying bit. I double checked all the enum values. Getting a bit stuck with Xcode not telling me [the depth stencil states](https://discord.com/channels/608014603317936148/1173336353187041380/1301682923925405850).

**Comment by jonahwilliams** [comment]
Looks like we use a depth compare of Greater by default: https://github.com/flutter/engine/blob/main/impeller/entity/contents/contents.cc#L29

**Comment by jonahwilliams** [comment]
If I change this to GreaterEqual, then it also works as expected.

**Comment by chinmaygarde** [comment]
Yeah, but that doesn't explain the difference between GL and Metal though. Even when GL is emulated on top of Metal.

**Comment by jonahwilliams** [comment]
Yeah it seems like GL is behaving correctly here while the other backends are actually buggy...

**Comment by jonahwilliams** [comment]
Might just be this increment is wrong: https://github.com/flutter/engine/pull/56310/files#diff-c41a103205badb3983d3910f4b740ea44d91007045ce7b552010db3b506ccc0fR23

**Comment by chinmaygarde** [comment]
This "fixes" it.

<img width="1449" alt="Screenshot 2024-11-01 at 11 56 43 AM" src="https://github.com/user-attachments/assets/bbbe3822-f27e-4cee-a9fd-acbd6ca218a2">

**Comment by chinmaygarde** [comment]
I should say, it fixes my test case, it breaks the `CanRenderDifferenceClips` case.

**Comment by jonahwilliams** [comment]
@chinmaygarde can you confirm if https://github.com/flutter/engine/pull/56310 fixes your bug too?

**Comment by chinmaygarde** [comment]
Yes it does.

<img width="1136" alt="Screenshot 2024-11-01 at 12 29 08 PM 1" src="https://github.com/user-attachments/assets/a6426b8e-c929-43df-b3b8-c3536bff2a12">

The test case:
```c++
TEST_P(AiksTest, GithubIssue157885) {
#if FML_OS_MACOSX
  if (GetBackend() == PlaygroundBackend::kVulkan) {
    GTEST_SKIP() << "Unsupported on Molten due to usage of triangle fans.";
  }
#endif  // FML_OS_MACOSX
  DisplayListBuilder builder;

  DlPaint paint;
  DlColor clear_color(1.0, 0.5, 0.5, 0.5, DlColorSpace::kSRGB);
  paint.setColor(clear_color);
  builder.DrawPaint(paint);

  DlMatrix identity = {
      1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
      0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0,
  };
  builder.Save();
  builder.Transform(identity);

  DlRect frame = DlRect::MakeLTRB(1.0, 1.0, 1278.0, 763.0);
  DlColor white(1.0, 1.0, 1.0, 1.0, DlColorSpace::kSRGB);
  paint.setColor(white);
  builder.DrawRect(frame, paint);

  builder.Save();
  builder.ClipRect(frame, DlCanvas::ClipOp::kIntersect);

  DlMatrix rect_xform = {
      0.8241262, 0.56640625, 0.0, 0.0, -0.56640625, 0.8241262, 0.0, 0.0,
      0.0,       0.0,        1.0, 0.0, 271.1137,    489.4733,  0.0, 1.0,
  };
  builder.Save();
  builder.Transform(rect_xform);

  DlRect rect = DlRect::MakeLTRB(0.0, 0.0, 100.0, 100.0);
  DlColor bluish(1.0, 0.184, 0.501, 0.929, DlColorSpace::kSRGB);
  paint.setColor(bluish);
  DlRoundRect rrect = DlRoundRect::MakeRectRadius(rect, 18.0);
  builder.DrawRoundRect(rrect, paint);

  builder.Save();
  builder.ClipRect(rect, DlCanvas::ClipOp::kIntersect);
  builder.Restore();

  builder.Restore();

  DlMatrix path_xform = {
      1.0, 0.0, 0.0, 0.0, 0.0,   1.0,   0.0, 0.0,
      0.0, 0.0, 1.0, 0.0, 675.0, 279.5, 0.0, 1.0,
  };
  builder.Save();
  builder.Transform(path_xform);

  SkPath path;
  path.moveTo(87.5, 349.5);
  path.lineTo(25.0, 29.5);
  path.lineTo(150.0, 118.0);
  path.lineTo(25.0, 118.0);
  path.lineTo(150.0, 29.5);
  path.close();

  DlColor fill_color(1.0, 1.0, 0.0, 0.0, DlColorSpace::kSRGB);
  DlColor stroke_color(1.0, 0.0, 0.0, 0.0, DlColorSpace::kSRGB);
  paint.setColor(fill_color);
  paint.setDrawStyle(DlDrawStyle::kFill);
  builder.DrawPath(DlPath(path), paint);

  paint.setColor(stroke_color);
  paint.setStrokeWidth(2.0);
  paint.setDrawStyle(DlDrawStyle::kStroke);
  builder.DrawPath(path, paint);

  builder.Restore();
  builder.Restore();
  builder.Restore();

  ASSERT_TRUE(OpenPlaygroundHere(builder.Build()));
}

```

**Comment by chinmaygarde** [comment]
I labeled the depth stencil states and verified the enums. I don't think its anything to do with how we configure GL state. Shader precision perhaps?

**Comment by jonahwilliams** [comment]
ghosts in the machine

**Comment by chinmaygarde** [comment]
I attempted to debug the vertices and the effective shaders are the same. Only OpenGL has an additional transformation to the z to make the coordinate systems line up.

<img width="1896" alt="Screenshot 2024-11-01 at 12 46 29 PM" src="https://github.com/user-attachments/assets/b8c2613d-311d-4b4a-a302-ed540229fc12">
