### ISSUE TITLE
IMGEGLImage is not consistent

### ISSUE THREAD

**Issue by nagamanikandank** [flutter/flutter#153508]
### Issue
I am using WebRTC to get a remote video stream to show on my Flutter Android App.

I am able to test the remote video stream successfully on Google Chrome using simple Websocket+RTCPeerConnection HTML code.

I have issue displaying the same video in Android App (written in Flutter)
In Flutter (Android App) I am able to open the Websocket to the remote server, establish RTCPeerConnection and  RTCPeerConnection's onTrack Call back function successfully receives a stream which is instance of 'MediaStreamNative'

However, when I try to display the Widget (code shown below) I am getting below error  and I see just black screen on my Android app 

### Error
`E/IMGSRV  (18872): :4586: IsTextureConsistent: IMGEGLImage is not consistent
`

### Widget + Dart Code:

```
OrientationBuilder(builder: (context, orientation) {
              return Container(
                child: Stack(children: <Widget>[
                  Positioned(
                      left: 0.0,
                      right: 0.0,
                      top: 0.0,
                      bottom: 0.0,
                      child: Container(
                        margin: const EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                        width: 1280,
                        height: 768,
                        decoration: const BoxDecoration(color: Colors.black54),
                        child: RTCVideoView(_remoteRenderer),
                      )),
                ]),
              );
            })

RTCPeerConnection? pcOne = await createPeerConnection({'bundlePolicy': bundlePolicy});
RTCVideoRenderer _remoteRenderer = RTCVideoRenderer()
...
...
...
pcOne.onTrack = (evt) {
if (evt.track.kind == 'video') {
print(evt.streams[0].toString());  //I can see "Instance of 'MediaStreamNative' "  as output of this line.
setState(() {
        _remoteRenderer.srcObject = evt.streams[0];
})
}
}
```

### Expected results

I expect the video to be displayed in Android app just like it gets displayed on HTML in a web browser

### Error
`E/IMGSRV  (18872): :4586: IsTextureConsistent: IMGEGLImage is not consistent
`

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.10.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include
      these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.1)
[√] Connected device (4 available)
[√] Network resources
```

**Comment by darshankawar** [comment]
@nagamanikandank 
The issue could likely be with RTCVideoView that comes from webrtc package you might be using. So try to reach out to the package you are using for webrtc. If not, please provide us a complete runnable and reproducible code sample (ex: main.dart) that shows the reported behavior.

**Comment by nagamanikandank** [comment]
@darshankawar  , irrespective of this error, I am getting good streaming now. The error was in the data type of the "answer" object I was sending to the remote server. You can consider this issue closed for now
