### ISSUE TITLE
How do I know if the face or fingerprint authentication has changed? Is there any monitoring of face or fingerprint changes?

### ISSUE THREAD

**Issue by huangsir0** [flutter/flutter#153539]
### Steps to reproduce

How do I know if the face or fingerprint authentication has changed? Is there any monitoring of face or fingerprint changes?

### Actual results

How do I know if the face or fingerprint authentication has changed? Is there any monitoring of face or fingerprint changes?

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

How do I know if the face or fingerprint authentication has changed? Is there any monitoring of face or fingerprint changes?

**Comment by danagbemava-nc** [comment]
This is out of scope of the `local_auth` plugin. See https://github.com/flutter/flutter/issues/88848#issuecomment-906724327

Closing from here
