### ISSUE TITLE
CupertinoDatePicker ignoring the parameter 'showDayOfWeek'

### ISSUE THREAD

**Issue by Pachebel** [flutter/flutter#153576]
### Steps to reproduce

1. Create a new flutter project
2. Paste the code above
3. Run project

Code:
```Dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: Scaffold(
          appBar: AppBar(),
          body: Center(
              child: SizedBox(
            height: 200,
            child: CupertinoDatePicker(
              showDayOfWeek: false,
              onDateTimeChanged: (DateTime newDateTime) {},
            ),
          )),
        ));
  }
}

```

### Expected results

As "showDayOfWeek" is false by default, we are expecting to **not** see the day of week in the DatePicker, right?

### Actual results

Even if we declare the 'showDayOfWeek' value as false, when using the mode CupertinoDatePickerMode.dateAndTime (the default mode), the days of week still shows in the screen as you can see below:
![Captura de tela 2024-08-16 130052](https://github.com/user-attachments/assets/2fa7ccf0-4b99-4733-9c5e-5143bcbf3da9)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: Scaffold(
          appBar: AppBar(),
          body: Center(
              child: SizedBox(
            height: 200,
            child: CupertinoDatePicker(
              mode: CupertinoDatePickerMode.dateAndTime,
              onDateTimeChanged: (DateTime newDateTime) {},
            ),
          )),
        ));
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Captura de tela 2024-08-16 130052](https://github.com/user-attachments/assets/bddc63d4-5659-4ef3-972b-7060010a5b73)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [versao 10.0.22631.4037], locale pt-BR)
    • Flutter version 3.24.0 on channel stable at C:\Users\joao\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\joao\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35027.167
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] Connected device (4 available)
    • Pixel 7 Pro (mobile) • 192.168.13.101:5555 • android-x64    • Android 13 (API 33)
    • Windows (desktop)    • windows             • windows-x64    • Microsoft Windows [versao 10.0.22631.4037]
    • Chrome (web)         • chrome              • web-javascript • Google Chrome 127.0.6533.120
    • Edge (web)           • edge                • web-javascript • Microsoft Edge 127.0.2651.98

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by victorsanni** [comment]
`showDayOfWeek` only works in `CupertinoDatePickerMode.date`. The default mode is `CupertinoDatePickerMode.dateAndTime`. There are two ways I see to address this issue:

1. Make it clear in the documentation that `showDayOfWeek` only works in `CupertinoDatePickerMode.date`.
2. Make `CupertinoDatePickerMode.dateAndTime` respect `showDayOfWeek`. But that will be breaking unless `showDayOfWeek` is set to true by default, which will also be breaking.

**Comment by Pachebel** [comment]
I totally agree.

Updating the docs is the fast and easy way, but I think that changing the widget is the best since it promoves a better flexibility of his use.

Also, I'm very open to contribute to the project

**Comment by victorsanni** [comment]
> Also, I'm very open to contribute to the project

A good first step would be to explore if it's possible to make `CupertinoDatePickerMode.dateAndTime` respect `showDayOfWeek`. Depending on how that goes, as well as on further discussion with the team/users, we can decide if/how to move forward.

**Comment by danagbemava-nc** [comment]
Labeling based on https://github.com/flutter/flutter/issues/153576#issuecomment-2294852955. 

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/deanli/dev/stable
    ! The flutter binary is not on your path. Consider adding /Users/deanli/dev/stable/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/deanli/dev/stable/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```

```
[!] Flutter (Channel master, 3.24.0-1.0.pre.624, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.0-1.0.pre.624 on channel master at /Users/deanli/dev/master
    ! The flutter binary is not on your path. Consider adding /Users/deanli/dev/master/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/deanli/dev/master/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 777e90a983 (3 hours ago), 2024-08-19 01:23:24 -0400
    • Engine revision c28282d39f
    • Dart version 3.6.0 (build 3.6.0-149.3.beta)
    • DevTools version 2.38.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```

</details>

**Comment by Piinks** [comment]
Maybe we can add an assert to let folks know in an error message that `showDayOfWeek` only works in `CupertinoDatePickerMode.date`?

**Comment by victorsanni** [comment]
> Maybe we can add an assert to let folks know in an error message that `showDayOfWeek` only works in `CupertinoDatePickerMode.date`?

Bumping on this, @Pachebel, if you'd like to work on it, you could put in an assert and update the documentation as needed.

**Comment by sikandarSukuk** [comment]
@Pachebel are you working on this?

**Comment by Sikandar4747** [comment]
@Pachebel are you working on this?

**Comment by Pachebel** [comment]
> @Pachebel are you working on this?

I'm starting, just passing through a turbulent week

**Comment by Pachebel** [comment]
I saw that in `_buildMediumDatePicker`, inside `CupertinoDatePicker` class, we have the following code:

```dart
/// this widget builds the date text from the widget, something like Wed Sep 27
 final String dateText = rangeStart == DateTime(now.year, now.month, now.day)
            ? localizations.todayLabel
            : localizations.datePickerMediumDate(rangeStart);

          return itemPositioningBuilder(
            context,
            Text(dateText, style: _themeTextStyle(context)),
          );
```

To remove the weekDay from it, we need to change how `datePickerMediumDate` behave, so, I though on adding an optional field named `useWeekday`. That way, we don't have any breaking changes, as the default function already uses it:


```dart
  @override
  String datePickerMediumDate(DateTime date,[bool useWeekday = true]) {
    return useWeekday
        ? '${_shortWeekdays[date.weekday - DateTime.monday]} '
        '${_shortMonths[date.month - DateTime.january]} '
        '${date.day.toString().padRight(2)}'
        :
    '${_shortWeekdays[date.weekday - DateTime.monday]} '
      '${_shortMonths[date.month - DateTime.january]}';
  }
```
After those changes, I got an error. I forgot that `datePickerMediumDate` overrides from flutter_localizations package.

On my analysis, to solve this issue, we need to change a field from flutter_localizations, and maybe the PR will come out of scope, so, by now, I'm only adding one assert just as @Piinks purposed, ok team?

**Comment by Pachebel** [comment]
Actually, I think that there will be breaking changes in any way... The `CupertinoDatePicker` uses `showDayOfWeek` as false by default, but in the `CupertinoDatePickerMode.dateAndTime`, even if it is false, we still see the weekdays in UI, so... I'm kinda lost here right now. Maybe we have to change the value to true, but as I said, we will break the code.

I want to fix it entirely, but it will take some time and we need to make changes in flutter_localizations. Can I make those changes, team?

**Comment by victorsanni** [comment]
> Actually, I think that there will be breaking changes in any way... The `CupertinoDatePicker` uses `showDayOfWeek` as false by default, but in the `CupertinoDatePickerMode.dateAndTime`, even if it is false, we still see the weekdays in UI, so... I'm kinda lost here right now. Maybe we have to change the value to true, but as I said, we will break the code.
> 
> I want to fix it entirely, but it will take some time and we need to make changes in flutter_localizations. Can I make those changes, team?

As mentioned already, for now, the asserts and documentation change will be enough. For further changes, feel free to open a PR for review.

**Comment by victorsanni** [comment]
Fixed by https://github.com/flutter/flutter/pull/155260
