### ISSUE TITLE
Connected device (the doctor check crashed)

### ISSUE THREAD

**Issue by AJRafallo** [flutter/flutter#153696]
### Steps to reproduce

everytime i install android studio it says Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: but I when I check it it is correctly placed and in env variable.

### Actual results

 Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about
      this issue at https://github.com/flutter/flutter/issues.
    X Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      C:\......
      Error details: Process exited abnormally with exit code 259:

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about
      this issue at https://github.com/flutter/flutter/issues.
    X Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      C:\Users\ajraf\AppData\Local\Android\Sdk\platform-tools\adb.exe
      Error details: Process exited abnormally with exit code 259:

[√] Network resources

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Please check https://github.com/flutter/flutter/issues/72101#issuecomment-2213125884 to see if the solution can work for you in Windows.
