### ISSUE TITLE
Android Unable to show clipboard menu such as copy or paste in webview

### ISSUE THREAD

**Issue by AravindhKnightDev** [flutter/flutter#153676]
### Steps to reproduce

![Screenshot 2024-08-19 at 12 28 00 PM](https://github.com/user-attachments/assets/e8f8d8a3-b0a7-4a66-a7b0-21b193058419)

https://github.com/user-attachments/assets/ccab6cae-d235-4214-b62e-1ef17cfb7517

Flutter 3.24.0 
Dart 3.5.0 

clipboard menu works on iOS but not working on android.

### Actual results

The clipboard menu works on iOS but not working on android.

### Code sample

<details open><summary>Code sample</summary>

```dart
class PaymentScreenBody extends StatelessWidget {
  const PaymentScreenBody({super.key});

  @override
  Widget build(BuildContext context) {
    final PaymentSubscribeViewModel viewModel =
        ViewModel.watch<PaymentSubscribeViewModel>(context);
    return WebViewWidget(
        controller: viewModel.webController
          ..setJavaScriptMode(JavaScriptMode.unrestricted)
          ..setBackgroundColor(const Color(0x00000000))
          ..setNavigationDelegate(
            NavigationDelegate(
              onPageStarted: (String url) {},
              onPageFinished: (String url) {
                viewModel.paymentRedirection(url);
              },
              onHttpError: (HttpResponseError error) {},
              onWebResourceError: (WebResourceError error) {},
              onNavigationRequest: (NavigationRequest request) {
                return NavigationDecision.navigate;
              },
            ),
          )
          ..loadRequest(Uri.parse(viewModel.paymentUrl.toString())));
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[https://github.com/user-attachments/assets/ccab6cae-d235-4214-b62e-1ef17cfb7517]
</details>

### Logs

<details open><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
```

</details>

**Comment by huycozy** [comment]
Hi @AravindhKnightDev 
Which `webview_flutter` version are you using? Please share the correct demo screenshot as I see you provided iOS screenshot but you mentioned the issue occurs on Android.

I checked this issue using below minimal sample code on Android but the clipboard menu is showing as desired:

<details>
<summary>Demo</summary>

<img width="400" src="https://github.com/user-attachments/assets/4660dbd9-2e1c-4628-b1c2-ed282609e747">
</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(const MaterialApp(home: WebViewExample()));

class WebViewExample extends StatefulWidget {
  const WebViewExample({super.key});

  @override
  State<WebViewExample> createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  late final WebViewController controller;

  @override
  void initState() {
    super.initState();
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
        ),
      )
      ..loadRequest(Uri.parse('https://flutter.dev/'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter Simple Example')),
      body: WebViewWidget(controller: controller),
    );
  }
}

```
</details>

Please try this sample code on your end and confirm.

**Comment by AravindhKnightDev** [comment]
> Hi @huycozy
I'm using webview_flutter: ^4.8.0. 
As you mentioned, the clipboard menu appears for text but is not working for images. 
Can you try it on any images?
I have already provided a screenshot and video for reference.

To test the issue with images, you can use the following demo sandbox link:
https://demo.juz4x.com/hitpay/pay.php

**Comment by huycozy** [comment]
The link you provided above requires input sensitive info so I use this link with a direct image instead: https://github.com/marketplace/models.

Can you please confirm if it works on Android native example or other Android apps? I checked this on Android pure WebView below but the clipboard also doesn't show up as well:

```xml
<WebView
    android:id="@+id/webView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
```

```kotlin
binding.webView.loadUrl("https://github.com/marketplace/models")
```

That means this seems to be infeasible on Android as my understanding.
