### ISSUE TITLE
[shared_preferences] Please add `SharedPreferencesAsync.get` method

### ISSUE THREAD

**Issue by hoc081098** [flutter/flutter#153630]
### Use case

Add `SharedPreferencesAsync.get` method, it is similar to [SharedPreferencesWithCache.get](https://pub.dev/documentation/shared_preferences/2.3.2/shared_preferences/SharedPreferencesWithCache/get.html)

### Proposal

```
// Reads a value of any type from the SharedPreferencesWithCache.
get(String key) → Future<Object?>
```

**Comment by stuartmorgan** [comment]
> ### Use case
> Add `SharedPreferencesAsync.get` method, it is similar to [SharedPreferencesWithCache.get](https://pub.dev/documentation/shared_preferences/2.3.2/shared_preferences/SharedPreferencesWithCache/get.html)

This is a proposal, not a use case. What's the use case you have for arbitrary reads?

This is already possible via `(await getAll({key}))[key]`, so unless there's a common use case for needing to read arbitrary values, it's not necessarily something we would expand the API surface just to make slightly more convenient.

**Comment by hoc081098** [comment]
I have used `(await getAll({key}))[key]` but I think reading a single key is more performant than reading all keys

**Comment by stuartmorgan** [comment]
> I have used `(await getAll({key}))[key]` but I think reading a single key is more performant than reading all keys

Could you provide traces with numbers for the performance analysis you did? If enumerating keys in native code has appreciable performance impact, that's something that can be addressed in the implementation (by explicitly enumerating the `allowList` instead), without needing API changes.

**Comment by hoc081098** [comment]
Thanks, using `getAll(allowList: { key })[key]` is good enough 👍.
So I close this issue.
