### ISSUE TITLE
Where and should a common `TestProcessManager` live?

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#153602]
The [`process`](https://pub.dev/packages/process) package is heavily used in the Flutter source trees:

- `flutter/engine`: [~30 files](https://github.com/search?q=repo%3Aflutter%2Fengine%20%22package%3Aprocess%22&type=code)
- `flutter/packages`: [~22 files](https://github.com/search?q=repo%3Aflutter%2Fpackages+%22package%3Aprocess%22&type=code)
- `flutter/flutter`: [~127 files](https://github.com/search?q=repo%3Aflutter%2Fflutter+%22package%3Aprocess%22&type=code)

However, in https://github.com/google/process.dart/pull/47, @jonahwilliams and @tvolkert ripped out the record and replay functionality as [sic] unused (see https://github.com/flutter/flutter/issues/136221 as well). As _not_ a direct result, there are now many 1-off fake and mock implementations of `ProcessManager`:

- [`FakeProcessManager` in the engine](https://github.com/search?q=repo%3Aflutter%2Fpackages+%22package%3Aprocess%22&type=code)
- At least [10+ implementations across `org: flutter`](https://github.com/search?q=org%3Aflutter+%22implements+ProcessManager%22&type=code)

Some of these implementations are [very simple fakes](https://github.com/flutter/flutter/blob/8817d45220d582a0e56dea5119153c10a00d6d3e/dev/devicelab/test/running_processes_test.dart#L88). Others, including both the one in the [engine](https://github.com/search?q=repo%3Aflutter%2Fpackages+%22package%3Aprocess%22&type=code), in [`flutter_tools`](https://github.com/flutter/flutter/blob/8817d45220d582a0e56dea5119153c10a00d6d3e/packages/flutter_tools/test/src/fake_process_manager.dart#L241), in [cocoon](https://github.com/flutter/cocoon/blob/d849b14bab90e0f90e2f7667e37c9f9a5696b918/cipd_packages/codesign/test/src/fake_process_manager.dart#L194), in [`assets-for-api-docs`](https://github.com/flutter/assets-for-api-docs/blob/6baeff6d12034aa922060f4723aaee29fc5217e4/bin/test/fake_process_manager.dart#L28) are complex and full-featured.

Sometimes the lack of a good implementation has even led to more technical debt; for example the `flutter_tools` implementation doesn't support a way to capture `inheritedStdio`, which led one contributor to add a very complex additional code path [all over `flutter_tool`](https://github.com/search?q=repo%3Aflutter%2Fflutter%20%22Pub.test%22&type=code) just to [support capturing it](https://github.com/flutter/flutter/blob/8817d45220d582a0e56dea5119153c10a00d6d3e/packages/flutter_tools/lib/src/dart/pub.dart#L360-L396) for some tests.

I could imagine 3 possible outcomes here:

1. We do nothing, this is the status quo and we think it's good/worth keeping around due to cost.
2. We add a canonical implementation to `package:process`, i.e. `TestProcessManager`.

    This has the potentially highest cost to maintain an interface with external usage, but also it is not
    like this implementation changes much.

3. We at least share one within `flutter/flutter`, and if the engine is merged in, it can be shared as well.

Thoughts?

**Comment by stuartmorgan** [comment]
> 2\. We add a canonical implementation to `package:process`, i.e. `TestProcessManager`.
>     This has the potentially highest cost to maintain an interface with external usage, but also it is not
>     like this implementation changes much.

I am generally not in favor of making test implementations part of packages. The problem isn't so much that we need to update the test version when the real version changes (although there is some cost to that), it's that different people want different functionality for their specific test usage, so now we're fielding and triaging bug reports and feature requests for a whole new API surface.

So between 2 and 3 I would strongly prefer 3, because 3 has an exceptionally clear scope: it must meet exactly our needs, and nothing else.

**Comment by jonahwilliams** [comment]
I think that very simple fakes should be left as is. Having multiple fakes sharing the same behavior to capture inheritstdio sounds like a good case for refactoring. For the code you linked though I would have preferred that we not have changed the real implementation to support this capture and instead writen an integration/end to end style test instead.

So I think 1 is the most appealing option to me.

**Comment by matanlurey** [comment]
Seems like there is a reasonable consensus against more test fakes we support for others, so I'll close this as not planned.
