### ISSUE TITLE
Linux Web Framework Tests failing on 3.24 stable engine PR, checking out ToT framework

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#153612]
For the PR: https://github.com/flutter/engine/pull/54585
The `Linux Web Framework Tests` target: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Web%20Framework%20tests/42212/infra

We're seeing failures like:

```
[  +13 ms] /b/s/w/ir/x/w/recipe_cleanup/builder/src/flutter/prebuilts/linux-x64/dart-sdk/bin/dartaotruntime --disable-dart-dev /b/s/w/ir/x/w/recipe_cleanup/builder/src/flutter/prebuilts/linux-x64/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root /b/s/w/ir/x/w/recipe_cleanup/builder/src/out/wasm_release/flutter_web_sdk/ --incremental --target=dartdevc --experimental-emit-debug-metadata -DDART_HHH_BOT=false -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false --output-dill /b/s/w/ir/x/t/flutter_tools.VFUPHJ/flutter_test.DJAWJL/out --packages /b/s/w/ir/x/w/flutter/packages/flutter/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /b/s/w/ir/x/w/flutter/packages/flutter/test --filesystem-root /b/s/w/ir/x/t/flutter_tools.VFUPHJ/flutter_test.DJAWJL/ --filesystem-scheme org-dartlang-app --initialize-from-dill build/45d48c4c9128ad4b2557fab909a9764a.cache.dill.track.dill --platform file:///b/s/w/ir/x/w/recipe_cleanup/builder/src/out/wasm_release/flutter_web_sdk/kernel/ddc_outline_sound.dill --verbosity=error --sound-null-safety
[  +12 ms] <- compile org-dartlang-app:///main.dart
[ +197 ms] org-dartlang-app:///main.dart:1:1: Error: The specified language version is too high. The highest supported language version is 3.5.
[   +1 ms] // @dart = 3.6
[        ] ^^^^^^^^^^^^^^
[+7539 ms] lib/src/semantics/semantics.dart:2925:7: Error: No named parameter with the name 'linkUrl'.
[        ]       linkUrl: data.linkUrl?.toString() ?? '',
[        ]       ^^^^^^^
[+20745 ms] "flutter test" took 34,565ms.
[   +4 ms] Failed to compile
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      WebTestCompiler._compileJS (package:flutter_tools/src/test/web_test_compiler.dart:194:7)
           <asynchronous suspension>
           #2      _FlutterTestRunnerImpl.runTests (package:flutter_tools/src/test/runner.dart:181:34)
           <asynchronous suspension>
           #3      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:596:16)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1432:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
```

In the build: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2601086/infra

Notice at step 3.3 ([log](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8739404792380105345/+/u/Checkout_flutter_flutter/git_checkout/stdout)), we checked out framework commit https://github.com/flutter/flutter/commit/9473c8b5d1, which is on the master branch, and not the 3.24 framework branch.

**Comment by christopherfujino** [comment]
I believe the engine/web_engine_framework.py recipe used to directly run tests, and has logic to check out the correct version of flutter/flutter: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/web_engine_framework.py#95

However, this appears to be the wrong commit.

**Comment by zanderso** [comment]
In some sense `Linux Web Framework Tests` presubs are a convenience to help the web team catch changes to the web engine in engine presubmit that will cause a roll of flutter/engine to flutter/flutter to fail. For the release, if that convenience isn't needed, these same tests will run when the release engine rolls to the release framework. I'm wondering if these tests are even intended to run on release branches? In the `.ci.yaml` it says:

```
    enabled_branches:
      - main
```

See https://github.com/flutter/engine/blob/main/.ci.yaml#L344

**Comment by christopherfujino** [comment]
> In some sense `Linux Web Framework Tests` presubs are a convenience to help the web team catch changes to the web engine in engine presubmit that will cause a roll of flutter/engine to flutter/flutter to fail. For the release, if that convenience isn't needed, these same tests will run when the release engine rolls to the release framework. I'm wondering if these tests are even intended to run on release branches? In the `.ci.yaml` it says:
> 
> ```
>     enabled_branches:
>       - main
> ```
> 
> See https://github.com/flutter/engine/blob/main/.ci.yaml#L344

Ahh, thanks for finding this. Ok, looks like infra is broken and this should have never ran on a release branch, let me just skip the target.

**Comment by christopherfujino** [comment]
Actually, I remember now that I initially opened the PR against `main`, and then changed the merge target. I bet somehow cocoon got confused, or didn't properly update it on the merge target changed event.

**Comment by christopherfujino** [comment]
PR merged, this issue tracks ensuring this never happens again: https://github.com/flutter/flutter/issues/153717
