### ISSUE TITLE
Flutter web usePathUrlStrategy bug, loading infinite

### ISSUE THREAD

**Issue by eduardohr-muniz** [flutter/flutter#153688]
### Steps to reproduce

Go directly to http://localhost:58703/user/user_name/Jhon

It won't work.

Comment out the usePathUrlStrategy(); and everything will work normally

A point of attention to reproduce the same error when reaching the url by f5 on the page or by entering the browser url to reload

### Expected results

That the application is using usePathUrlStrategy() http://localhost:58703/user/user_name/Jhon

### Actual results

The Application simply keeps loading infinitely

### Code sample

<details open><summary>Code sample</summary>

```link
https://github.com/eduardohr-muniz/go_router_poc
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/1097e412-9f35-4ad6-9ab8-30428de4c68b)

![image](https://github.com/user-attachments/assets/fad9a535-f688-4197-af9f-72b5984509cb)

</details>
https://github.com/eduardohr-muniz/go_router_poc

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment]
This is a known issue being tracked at https://github.com/flutter/flutter/issues/152995. It's fixed on Flutter master channel.

Closing this issue as a duplicate, so please follow up on it for further updates.
