### ISSUE TITLE
In mobile web browser, context menu doesn't work

### ISSUE THREAD

**Issue by OlehSv** [flutter/flutter#153613]
### Steps to reproduce

Launch sample code in web on mobile device. I tried iPhone + Safari. It is not possible to invoke browser menu by any gesture (long press, double click).

I tried to use `await BrowserContextMenu.disableContextMenu();`, but not native flutter context menu doesn't support "past" button in web. After press on it nothing happens.

I can reproduce bug only in 3.24.0. 3.22.3 shows browser context menu, but it has different problem - it shows both context menus (flutter and browser) in the same time.

### Expected results

After long press I am expecting to see context menu

### Actual results

Nothing

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() async {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    ),
  );
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPad (Лиля). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @OlehSv, I see the context menu (paste option) showing on Flutter master channel `3.24.0-1.0.pre.623`. Can you switch to master and confirm this?

**Comment by OlehSv** [comment]
@huycozy Yes, it is working in master. Stable and beta both have the issue. Is it possible to cherry-pick fix to stable branch?

**Comment by huycozy** [comment]
>Is it possible to cherry-pick fix to stable branch?

I am unsure which PR has been landed on master channel. If you can find it (doing git bisect to find a good commit between master and stable), you can file a [CP request](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&projects=&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E).

Since this is fixed on master channel, I will mark this as fixed. Thanks for confirming!
