### ISSUE TITLE
google_sign_in doesn't show account photo

### ISSUE THREAD

**Issue by Herohtar** [flutter/flutter#15366]
## Steps to Reproduce

I'm using [google_sign_in](https://github.com/flutter/plugins/tree/master/packages/google_sign_in) in my project and the dialog it produces to select accounts doesn't show their profile images. I've tried building the example project from the plugin repository, but the results are the same:

![flutter](https://user-images.githubusercontent.com/10427164/37237052-06a152ec-23d4-11e8-8859-526a2e743b55.png)

It has the account emails offset as if there should be something to the left of them, or some sort of additional infomation/decoration, but there isn't.

## Flutter Doctor

```
flutter doctor -v
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
    • Flutter version 0.1.5 at C:\Users\Caleb\Google Drive\Android\flutter
    • Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Caleb\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.21.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] Connected devices (1 available)
    • Pixel 2 XL • 709KPNY0046767 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
@Herohtar 
I checked with current google_sign_in: ^4.1.4 and example from https://pub.dev/packages/google_sign_in#-example-tab-
Issue seems to be fixed, closing.
If you disagree please write in the comments and I will reopen it.
Thank you
