### ISSUE TITLE
[shared_preferences] Execution failed for task ':shared_preferences_android:compileDebugKotlin'.

### ISSUE THREAD

**Issue by esaiamuthan** [flutter/flutter#153686]
### Steps to reproduce

1. Updated the gradle version to 8.5.0 
2. After add shared_peferences library am afcing this issue

### * What went wrong:
Execution failed for task ':shared_preferences_android:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
  

### Actual results

**Issue should be resolved if i use latest version of shared_preferences**

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by bartekpacia** [comment]
Add the following to `app/build.gradle`:

```kotlin
compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

kotlinOptions {
    jvmTarget = "1.8"
}
```
