### ISSUE TITLE
Scorecard failing in flutter/packages: 401 Bad Credentials

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#153626]
### Type of Request

bug

### Infrastructure Environment

Scorecards analysis GitHub action

### What is happening?

It's failing with an auth error, which in turn blocks all of our auto-release automation that publishes updated packages.

Example failure: https://github.com/flutter/packages/actions/runs/10426979973/job/28882198803

```
Error: scorecard.Run: repo unreachable: GET https://api.github.com/repos/flutter/packages: 401 Bad credentials []
2024/08/16 23:21:51 error during command execution: scorecard.Run: repo unreachable: GET https://api.github.com/repos/flutter/packages: 401 Bad credentials []
```

### Steps to reproduce

Step 1: Land anything in flutter/packages
Step 2: See scorecard action fail
Step 3: See release action fail because scorecard failed

### Expected results

I believe this just means the credentials have expired and need to be rotated.

**Comment by stuartmorgan** [comment]
(If we don't know how to update these credentials quickly, it looks like someone with Admin permissions on flutter/packages could temporarily disable this workflow from the Actions tab.)

**Comment by christopherfujino** [comment]
> (If we don't know how to update these credentials quickly, it looks like someone with Admin permissions on flutter/packages could temporarily disable this workflow from the Actions tab.)

I'm gonna disable the workflow to unblock packages. It's unclear to me whether it's worth rotating these credentials.
