### ISSUE TITLE
 Flutter (the doctor check crashed)   FormatException: Missing extension byte (at offset 3)

### ISSUE THREAD

**Issue by zhaomn33** [flutter/flutter#153744]
### Steps to reproduce

flutter docker 失败

### Expected results

 Flutter (the doctor check crashed)   FormatException: Missing extension byte (at offset 3)

### Actual results

[flutter_01.log](https://github.com/user-attachments/files/16669664/flutter_01.log)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
There is an issue at https://github.com/flutter/flutter/issues/147937 that reported `FormatException: Missing extension byte` as well. Closing this in favor of that one.
