### ISSUE TITLE
Dart -> Engine roll failing

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#153715]
On dart2wasm compilation failures as in https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2605416/overview

https://github.com/flutter/engine/pull/54618

Commits in the roll: https://dart.googlesource.com/sdk.git/+log/c5264a1bd1d2..e2818c08c193

cc'ing folks who have dart2wasm related commits in that roll: @mkustermann @sigmundch @osa1

**Comment by jtmcdole** [comment]
I believe we shouldn't be including the bootstrapping code and should just import `test` to use main().  @yjbanov ?

**Comment by aam** [comment]
Given the error
```
../../../../../../../../../.pub-cache/hosted/pub.dev/js-0.6.4/lib/js.dart:8:1: Error: Dart library 'dart:js' is not available on this platform.
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
Context: The unavailable library 'dart:js' is imported through these packages:

    app_lifecycle_state_test.dart => package:test => package:js => dart:js

Detailed import paths for (some of) the these imports:

    app_lifecycle_state_test.dart => package:test/bootstrap/browser.dart => package:test/src/bootstrap/browser.dart => package:test/src/runner/browser/post_message_channel.dart => package:test/src/runner/browser/dom.dart => package:js/js.dart => dart:js

```
I believe https://dart.googlesource.com/sdk.git/+/e8a049fd8e3736bad7d4a457fded5e5a224f8c30 is the culprit

cc @sigmundch

**Comment by aam** [comment]
ah, revert https://dart-review.googlesource.com/c/sdk/+/381305 is ready to land

**Comment by jason-simmons** [comment]
https://github.com/flutter/engine/pull/54629 is pending, which will upgrade the `js` package used by `lib/web_ui` to avoid bringing in the dependency on `dart:js`

**Comment by sigmundch** [comment]
Correct, we hope we can roll forward with the version bump, but if that is not sufficient, we can land the revert.

**Comment by sigmundch** [comment]
https://github.com/flutter/engine/pull/54629 landed. Please let us know if that fully resolved the issue.

**Comment by a-siva** [comment]
The roll of Dart landed in Flutter here https://github.com/flutter/engine/pull/54649.

Closing this issue.
