### ISSUE TITLE
OPPO privacy compliance testing rejected

### ISSUE THREAD

**Issue by icc-tips** [flutter/flutter#153749]
### Steps to reproduce

```console
1.2 APP 以个人信息处理规则弹窗等形式向用户明示个人信息处理的目的、方式和范围，未经
用户同意，存在收集 IMEI、IMSI、设备 MAC 地址、SUPI、SUCI、软件安装列表、位置、联系
人、通话记录、日历、短信、本机 电话号码、图片、音视频等个人信息。
检测结果：不通过
检测详情：(1)APP未经同意，存在收集个人信息的行为
2024-08-20 09:58:34.912 -> 读取已安装的应用
2024-08-20 10:00:17.581 -> 弹出隐私政策
Intent { act=android.intent.action.PROCESS_TEXT typ=text/plain }
at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser()
a t
android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.jav
a:914)
at io.flutter.plugin.text.ProcessTextPlugin.cacheResolveInfos(ProcessTextPlugin.java:118)
at io.flutter.plugin.text.ProcessTextPlugin.queryTextActions(ProcessTextPlugin.java:52)
a t
io.flutter.embedding.engine.systemchannels.ProcessTextChannel$1.onMethodCall(ProcessTextC
hannel.java:63)
a t
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.
java:267)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$ioflutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown
Source:12)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6554)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
改进建议：建议在用户同意隐私政策之后，APP开始收集用户个人信息。
证据截图：(无)
```

### Expected results

I like to be able to access Oppo's privacy compliance policy

### Actual results

OPPO privacy compliance testing rejected

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
English version (using https://translate.google.com):

```console
1.2 The APP clearly informs users of the purpose, method and scope of personal information processing in the form of pop-up windows of personal information processing rules, and collects personal information such as IMEI, IMSI, device MAC address, SUPI, SUCI, software installation list, location, contacts, call records, calendar, text messages, local phone number, pictures, audio and video without the user's consent.
Test result: Failed
Test details: (1) The APP collects personal information without consent
2024-08-20 09:58:34.912 -> Read installed applications
2024-08-20 10:00:17.581 -> Pop-up privacy policy

Intent { act=android.intent.action.PROCESS_TEXT typ=text/plain }
at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser()
a t
android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.jav
a:914)
at io.flutter.plugin.text.ProcessTextPlugin.cacheResolveInfos(ProcessTextPlugin.java:118)
at io.flutter.plugin.text.ProcessTextPlugin.queryTextActions(ProcessTextPlugin.java:52)
a t
io.flutter.embedding.engine.systemchannels.ProcessTextChannel$1.onMethodCall(ProcessTextC
hannel.java:63)
a t
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.
java:267)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io�flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown
Source:12)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6554)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

Improvement suggestions: It is recommended that the APP start collecting user personal information after the user agrees to the privacy policy.
Evidence screenshots: (none)
```

**Comment by huycozy** [comment]
Hi @icc-tips 
Are you frequently reading the clipboard content when using TextField widget on your app?

**Comment by huycozy** [comment]
Hi @icc-tips
Are you frequently reading the clipboard content when using TextField widget on your app? (May be similar to https://github.com/flutter/flutter/issues/101196)

Please consider posting issue in English that will help people can assist better. Thanks!

**Comment by bleroux** [comment]
@icc-tips @NeverOvO Can you share you android manifest file?

**Comment by NeverOvO** [comment]
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.NFC"/>

    <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE "/>
    <uses-permission android:name="com.hihonor.android.launcher.permission.CHANGE_BADGE" />
    <uses-permission android:name="com.vivo.notification.permission.BADGE_ICON" />

    <application
        tools:replace="android:label"
        android:label="XXXXX"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        android:requestLegacyExternalStorage="true">
        <activity
            android:name=".MainActivity"
            android:icon="@mipmap/ic_launcher"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:networkSecurityConfig="@xml/network_security_config"
            android:requestLegacyExternalStorage="true"
            android:screenOrientation="portrait"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            tools:ignore="Instantiatable">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        
        
        
        <service android:name=".common.UserService"
            android:enabled="true"
            android:exported="false"
            android:process=":pushcore">
            <intent-filter>
                <action android:name="cn.jiguang.user.service.action" />
            </intent-filter>
        </service>

        <service android:name=".jpush.PushMessageService"
            android:exported="false">
            <intent-filter>
                <action android:name="cn.jpush.android.intent.SERVICE_MESSAGE" />
                <category android:name="${applicationId}"></category>
            </intent-filter>
        </service>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

`

**Comment by bleroux** [comment]
Thanks :pray: 

Can you test if adding the following section at the end of your manifest file fixes the issue?

```xml
      ...
    </application>
    <!-- Required to query activities that can process text, see:
         https://developer.android.com/training/package-visibility and
         https://developer.android.com/reference/android/content/Intent#ACTION_PROCESS_TEXT.

         In particular, this is used by the Flutter engine in io.flutter.plugin.text.ProcessTextPlugin. -->
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>
```

**Comment by NeverOvO** [comment]
1.  违规收集个人信息
1.2
 
APP 以个人信息处理规则弹窗等形式向用户明示个人信息处理的目的、方式和范围，未经用户同意，存在收集 IMEI、IMSI、设备 MAC 地址、SUPI、SUCI、软件安装列表、位置、联系人、通话记录、日历、短信、本机 电话号码、图片、音视频等个人信息
检测详情：
APP未经同意，存在收集个人信息的行为  (详情)
2024-08-27 14:31:25 启动APP，开始检测
2024-08-27 14:31:28 读取已安装的应用
2024-08-27 14:33:14 APP启动完毕
改进建议：
建议在用户同意隐私政策之后，APP开始收集用户个人信息。

添加如图代码后，进行上传检测，反馈依然相同
After adding the code as shown in the picture, perform upload detection and the feedback remains the same

<img width="950" alt="截屏2024-08-27 14 41 07" src="https://github.com/user-attachments/assets/168aefe0-4fbd-417a-8ddb-c972a860d226">
