### ISSUE TITLE
curl: (3) Illegal characters found in URL from flutter doctor

### ISSUE THREAD

**Issue by YuyaAbo** [flutter/flutter#15379]
`flutter doctor -v`

```bash
$ flutter doctor -v
...nloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a
curl: (3) Illegal characters found in URL
```

what should I do?

**Comment by shaohui93** [comment]
I also have this problem. Can you tell me in detail how you solved it?

**Comment by pablonicoli** [comment]
have the same problem.
Couldn't solve it

**Comment by mattiagalati** [comment]
could also be solved with
`dos2unix /{flutter path}/flutter/bin/internal/engine.version`

**Comment by magnuswikhog** [comment]
> could also be solved with
> `dos2unix /{flutter path}/flutter/bin/internal/engine.version`

Just to be clear, for others who encounter this error for example when running `flutter upgrade`: 
1. First check where flutter is installed, using 
    which flutter
which will give you for example
    /Users/Donald/development/flutter/bin/flutter

2. Then run 
    dos2unix /Users/Donald/development/flutter/bin/internal/engine.version

Note that `which flutter` gives you the entire path to the `flutter` command - you want to exclude the last `/flutter` part from the path you supply to `dos2unix`.

**Comment by sky-48** [comment]
If you don't have `dos2unix` installed, simply open the `.../flutter/bin/internal/engine.version` file with any Text Editor and remove the second line. It should be an one-line file. By removing the second line (should be a blank line), it won't have any line-breaks that caused the issue.
