### ISSUE TITLE
About iOS 18 iPhone Mirroring

### ISSUE THREAD

**Issue by rs5173** [flutter/flutter#153738]
### Steps to reproduce

I tested Wonderous in an iPhone mirror and found the following issues:

1. Cannot use trackpad gestures to scroll through lists, while native apps can scroll through lists with two fingers

2. The default theme color of the input method candidate is white, causing the selected option to appear blank (I guess it may be because the font and background color are both white)

### Expected results

1，Scrolling lists with trackpad gestures
2，Like other native applications, the input method and candidate words are displayed and used normally

### Actual results

1. Cannot use trackpad gestures to scroll through lists, while native apps can scroll through lists with two fingers

2. The default theme color of the input method candidate is white, causing the selected option to appear blank (I guess it may be because the font and background color are both white)

### Code sample

Just run Wonderous app

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 15.0 24A5320a darwin-arm64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3.2)
[✓] VS Code (version 1.92.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (5 available)
[✓] Network resources
```

</details>

**Comment by rs5173** [comment]
There may be other issues, I haven't done a thorough test, and the iPhone mirroring feature is still in beta.

**Comment by rs5173** [comment]
There is also a gesture to return to the previous page. In the original app, you can slide two fingers to return to the previous page, but it does not work in the Flutter app.

**Comment by danagbemava-nc** [comment]
Hi @rs5173, I don't have the macOS beta or the iOS beta, does this happen with the master channel as well?

**Comment by danagbemava-nc** [comment]
cc @jmagman

**Comment by loic-sharma** [comment]
Thanks for reporting this! I've moved all the relevant information into this issue for tracking purposes: https://github.com/flutter/flutter/issues/152711

Feel free to add more details there as needed!

**Comment by Lev09** [comment]
Scrolling doesn't work in the Flutter app, except in sections with a WebView, in case anyone was wondering.

**Comment by jmagman** [comment]
That's tracked in https://github.com/flutter/flutter/issues/153897
