### ISSUE TITLE
Unable to pub upgrade the flutter tools in windows 10

### ISSUE THREAD

**Issue by kawinm** [flutter/flutter#15374]
I have cloned the flutter repository as per the docs.

And I have set the Path variable to flutter\bin\ folder.

But after I have run flutter doctor, I experience this: 

Waiting for 5 seconds, press CTRL+C to quit ...
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

It is running for infinite times and nothing else.

**Comment by abhijit-kar** [comment]
kawinm, clone the flutter repo to a path without space, and it works.

e.g. **C:\flutteris** better than _C:\Users\Abhijit Kar\flutter_

**Comment by kawinm** [comment]
I did the same, I cloned it to D:\flutter directory, But still I'm facing this issue.

**Comment by kawinm** [comment]
Worked perfectly with the master branch.
Below is the command:
git clone -b master https://github.com/flutter/flutter.git
