### ISSUE TITLE
Material TimePicker time display is chopped off

### ISSUE THREAD

**Issue by eganaj** [flutter/flutter#153782]
### Steps to reproduce

A simple use of the showTimePicker widget.

### Expected results

A full display of the time

### Actual results

The time display is a little chopped off as shown in the image attached
![Screenshot 2024-08-20 at 19 11 54](https://github.com/user-attachments/assets/ef8f4bdb-ad7b-4c18-9461-890bb80b060a)

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<void> _selectTime(BuildContext context, {int idx = 0}) async {
    final TimeOfDay? pickedTime = await showTimePicker(
      context: context,
      initialTime: TimeOfDay(hour: 12, minute: 30),
      builder: (BuildContext context, Widget? child) {
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(alwaysUse24HourFormat: true),
          child: child!,
        );
      },
    );
    if (pickedTime != null) {
      if (idx == 0) {
        _startTime = pickedTime;
      } else {
        _endTime = pickedTime;
      }

      debugPrint("Start: $_startTime");

      _controller.validateData(
          startDate: _startDate,
          endDate: _endDate,
          startTime: _startTime,
          endTime: _endTime);

      setState(() {});
    }
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![Screenshot 2024-08-20 at 19 11 54](https://github.com/user-attachments/assets/7a22ca31-27f5-40e6-808e-0d9b39c9d95b)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.1.2 23B92 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by aljibbs** [comment]
I'm having a similar problem.

**Comment by danagbemava-nc** [comment]
Hi @eganaj, are you using large fonts or a similar setting on your device? It looks ok with the normal font. See the screenshot below

<img src="https://github.com/user-attachments/assets/2311e6b3-4d41-4869-a19a-e2873acaaa5c" width="300"/>

**Comment by aljibbs** [comment]
I have specific font sizes setup in my theme. I'll be glad if you can specify the exact text style that affects texts on this widget or the best way to customize the text style on this widget. Thanks.

**Comment by eganaj** [comment]
Hi @danagbemava-nc 
I have specific font sizes setup in my theme. I'll be glad if you can specify the exact text style that affects texts on this widget or the best way to customize the text style on this widget. Thanks.
