### ISSUE TITLE
[iOS] Trackpad scroll gestures are not handled, impacts new macOS Sequoia iPhone Mirroring feature

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#153897]
The iOS embedder should correctly handle trackpad scroll gestures. 

This has the knock-on effect that trackpad scroll gestures do not work in Flutter apps when used via [iPhone Mirroring](https://github.com/flutter/flutter/issues/152711) in macOS Sequoia/iOS 18.

### Repro steps
1. Create an iOS app with a scroll view.
2. Launch on an iPad with a trackpad paired (e.g. Magic Keyboard)
3. Use a two-finger swipe gesture to scroll.

Expected behaviour: the [primary](https://api.flutter.dev/flutter/widgets/ScrollView/primary.html) scroll view scrolls.

Actual behaviour: the scroll gesture is ignored.

### Flutter doctor
```
[!] Flutter (Channel main, 3.25.0-1.0.pre.78, on macOS 14.6.1 23G93 darwin-arm64, locale ja-JP)
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/setup.
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone15. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 3 categories.
```

**Comment by cbracken** [comment]
@Piinks there'll be embedder work for this that we can probably crib from the macOS embedder, but are there places in the framework that scope trackpad behaviour to desktop/web?

**Comment by Piinks** [comment]
I don't think there is a specific trackpad issue, AFAIK trackpad support was completed a good while ago. Has there been a regression?

> desktop/web

There is an issue for trackpad that is specific to web. We cannot tell the difference between mouse wheels and trackpads on web, that issue is https://github.com/flutter/flutter/issues/139990

**Comment by loic-sharma** [comment]
cc @moffatman who's worked in this area and might have ideas

**Comment by moffatman** [comment]
Not updating to beta versions, will check it when stables go out. Next week afaik?

**Comment by moffatman** [comment]
But trackpad scroll gestures *are* handled on stable iPadOS and existing iOSOnMac runtime.... does iPadOS 18 break it??

**Comment by bernaferrari** [comment]
Stable is out, I can't test but saw people reporting this already.

**Comment by Ssiswent** [comment]
> Stable is out, I can't test but saw people reporting this already.稳定版已经发布，我无法测试，但已经看到有人报告了这一点。

Yes and I'm using stable version of MacOS 15, still can't scroll with iPhone Mirroring.

**Comment by incrediblezayed** [comment]
Damn, we have this issue open

**Comment by moffatman** [comment]
Just updated weirdly one gesture does work with trackpad in my app. but most doesn't....

**Comment by moffatman** [comment]
Ok found the issue will prepare the fix

**Comment by WelliRigo** [comment]
Is there a way to detect iPhone mirroring is in use?
