### ISSUE TITLE
Cupertinocontextmenu add previewBuilder

### ISSUE THREAD

**Issue by sudhar08** [flutter/flutter#153819]
### Use case

**Cupertinocontextmenu add previewBuilder**
In older version of Flutter has the Beautiful Feature in the cupertinocontexmenu there is option called previewbuilder. In Later version that has been removed from the flutter I don't
I request anyone can implement the feature again in the cupertino Libary .
The previewBuilder was very use when you  want show any other in the preview.

### Proposal

**For ref Flutter 3.19.0**

**Comment by danagbemava-nc** [comment]
Hi @sudhar08, it isn't exactly clear what you're reporting in this issue. `previewBuilder` was replaced with `builder`. Is there something previewBuilder did that builder doesn't do? It would help if you could provide a code sample that showcases what you want to achieve and what you have tried along with screenshots. 

Thank you
