### ISSUE TITLE
Update codesign tests

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#153853]
Flutter engine post-submit tests run multiple test to verify that we sign expected binaries.   However, one of our tests [run_verify_binaries_codesigned_tests.dart](https://github.com/flutter/flutter/commit/448a116b82a6df0be7d038ad9857799b7cdd5a47#diff-c4f14df15b97cc187c3b0fefc56e12c9498186ab2880fbb02e13568454e90e1b) may need to be updated as the tests may be redundant. 

CC: @christopherfujino for further context

**Comment by christopherfujino** [comment]
I'm closing this in favor of an umbrella issue: https://github.com/flutter/flutter/issues/153614
