### ISSUE TITLE
flutter apk third party support probably fragile

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#1538]
The current way to link third party services in with 'flutter apk' might be fragile. We're compiling a pre-build skyshell.dex.jar with the dex.jars provided by the third party. That means the third party service (e.g. GCM) depends on the same mojo version that was linked into skyshell.dex.jar.

I need to figure out how to allow the third party .jar to link in its own version of mojo, etc.

**Comment by mit-mit** [comment]
Closing; we updated the hello_services build in https://github.com/flutter/flutter/pull/7606, and that will be applied to the standard app template per https://github.com/flutter/flutter/issues/4796.
