### ISSUE TITLE
Impeller rendering Jittery text on ios

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#153809]
### Steps to reproduce

Jittery text widget when using Impeller on IOS
using go_router back gesture you Chinese text will be Jittery text. 
related bugs https://github.com/flutter/flutter/issues/149652
i am not sure if you can  see it, but "Please observe the first screen. When you use the back gesture, pay attention to the text shaking."

https://github.com/user-attachments/assets/1fdb46e1-0cec-44f0-9909-1ee3ae293e00

i am using 3.24.0 and go_router: ^14.2.6

### Expected results

 "Please observe the first screen. When you use the back gesture, pay attention to the text shaking."

### Actual results

avoid Jittery glyphs while back gesture end

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by virskor** [comment]
Sometimes the text shake is more pronounced than what is shown in the screen recording.

**Comment by jonahwilliams** [comment]
Looks like a dupe of https://github.com/flutter/flutter/issues/149652 . Unless you suspect this is a different issue or have a new repro I'd suggest closing this one

**Comment by virskor** [comment]
I think this bug is different with that one, because i am not using any animation on Text widget, but it still render a jittery text. not graphics.

**Comment by danagbemava-nc** [comment]
Hi @virskor, please provide a complete minimal reproducible code sample so that we can properly investigate this issue. 

Thank you

**Comment by virskor** [comment]
i am sorry i can not post all my code, but you can using go_router example and using Chinese on text widget. 
and i am using a custom text widget blow, using chinese and `textBaseline: TextBaseline.ideographic,`

you can see that when back gesture dectected, all the Text widget is shaking on the screen on attachement vedio. 

```dart
import 'package:flutter/material.dart';
import 'package:meili/utils/global.dart';

class MeiliText extends StatelessWidget {
  const MeiliText(
    this.text, {
    super.key,
    this.style,
    this.color,
    this.isPrimary = false,
    this.isGrey = false,
    this.isBold = false,
    this.isTiny = false,
    this.isLarge = false,
    this.isSmall = false,
    this.isHeadline = false,
    this.textAlign,
    this.overflow = TextOverflow.clip,
    this.maxLines,
    this.fontSize,
    this.fontWeight,
    this.fontFamily,
    this.textScaler,
  });

  /// 默认字符
  final String text;

  /// 样式
  final TextStyle? style;

  /// 使用primaryColor渲染
  final bool isPrimary;

  /// 是否是灰色
  final bool isGrey;

  /// 是否是小号字体
  final bool isSmall;

  /// 是否是超小号字体
  final bool isTiny;

  /// 是否是大号字体
  final bool isLarge;

  /// 是否是headline
  final bool isHeadline;

  /// 是否是粗体
  final bool isBold;

  /// 传入自定义颜色
  final Color? color;

  /// 文字对齐
  final TextAlign? textAlign;

  /// 文字超出
  final TextOverflow? overflow;

  /// 最大显示行数
  final int? maxLines;

  /// 指定文字大小
  final double? fontSize;

  /// 字体名
  final String? fontFamily;

  // 粗细
  final FontWeight? fontWeight;

  // textScaler
  final TextScaler? textScaler;

  @override
  Widget build(BuildContext context) {
    /// 颜色
    Color? resetColor = color;
    if (isGrey) {
      resetColor = Global.greyTextColorLight;
    } else if (isPrimary) {
      resetColor = Global.primaryColor;
    }

    /// 字体大小
    FontWeight? resetFontWeight = fontWeight;
    if (isBold) {
      resetFontWeight = FontWeight.bold;
    }

    /// 重置自豪
    double? resetFontSize = fontSize;
    if (isSmall) {
      resetFontSize = Global.fontSizeSmall;
    } else if (isTiny) {
      resetFontSize = Global.fontSizeTiny;
    } else if (isLarge) {
      resetFontSize = Global.fontSizeLarge;
    } else if (isHeadline) {
      resetFontSize = Theme.of(context).textTheme.headlineSmall!.fontSize;
    }

    /// 字体样式
    final TextStyle renderTextStyle = style ??
        DefaultTextStyle.of(context).style.copyWith(
              fontFamily: fontFamily,
              textBaseline: TextBaseline.ideographic,
              fontFamilyFallback: Global.fontFamilyFallback,
              color: resetColor,
              fontSize: resetFontSize,
              fontWeight: resetFontWeight,
            );

    return Text(
      text,
      textAlign: textAlign,
      overflow: overflow,
      style: renderTextStyle,
      maxLines: maxLines,
      textScaler: textScaler,
    );
  }
}
```

https://github.com/user-attachments/assets/924e93e1-24c7-4521-8fd5-efd55fe5f591

**Comment by virskor** [comment]
Almost all my application developed by Flutter will have this issue，only IOS and MacOS， especially on route change.

**Comment by danagbemava-nc** [comment]
Hi @virskor, the code sample doesn't have you to be your application code. See https://stackoverflow.com/help/minimal-reproducible-example for what constitutes a minimal sample. 

Thank you

**Comment by virskor** [comment]
duplicated of https://github.com/flutter/flutter/issues/149652

**Comment by virskor** [comment]
@danagbemava-nc found this issue https://github.com/flutter/flutter/issues/140475 it's same

**Comment by virskor** [comment]
https://github.com/flutter/flutter/issues/153996
