### ISSUE TITLE
Support loading fonts at runtime

### ISSUE THREAD

**Issue by nsreenath** [flutter/flutter#15386]
Need API equivalent to Android's  [Typeface.createFromFile()](https://developer.android.com/reference/android/graphics/Typeface.html#createFromFile(java.io.File))
so that app can download fonts at runtime and use it as a `fontFamily` in `TextStyle`

**Comment by nsreenath** [comment]
@jason-simmons How can we do this ?

**Comment by manujbahl** [comment]
Does anyone have a possible workaround to load attf from the network dynamically?

**Comment by nsreenath** [comment]
@cbracken Any workaround other than specifying custom fonts in pubspec at build time ?

**Comment by srix55** [comment]
Same as #17910

**Comment by xster** [comment]
The duped issue is closed.
