### ISSUE TITLE
[web]: Pass in flavor in webframeworks deploy

### ISSUE THREAD

**Issue by zh4ngx** [flutter/flutter#153807]
Describe your issue and include the command you're running (see below), flutter_web version 3.22.2, browser version chrome 127.0.6533.99 

Commands:

`firebase experiments:enable webframeworks`
`firebase init hosting`
`firebase deploy --only hosting`
OR `firebase serve --only hosting`

then point hosting to my existing flutter web app
Inside the app, I am using `appFlavor` for dev and prod environments / firebase projects.
I am able to get this working correctly using `flutter run web --flavor dev` and `flutter build web --dart-define FLUTTER_APP_FLAVOR=prod`

However, when using web frameworks and calling `firebase deploy ...` or `firebase serve ...`, it calls `flutter build web` with no arguments and effectively overwrites.

 Can flavor or (at least additional args) be passed into `firebase deploy` and `firebase serve`?
Another related question - does `firebase serve` build a debug version rather than release?

**Comment by danagbemava-nc** [comment]
This is an issue with the Firebase CLI tool. You will need to file an issue on their repo so that this can be properly addressed. 

Closing from here. 

Thank you

**Comment by zh4ngx** [comment]
Yes, sorry put this in the wrong project
