### ISSUE TITLE
[Impeller] Prepare a null GPU backend.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#153883]
Some tests in Google3 run on simulators that still don't have access to Metal. These tests cannot opt into Impeller till the simulators are updated. Per internal conversations, it is fine to accept updated goldens but not break these tests.

To unblock Slimpeller, there are two options, either keep the Skia backend around for these tests, or prepare a null backend that doesn't render anything and accept the updated goldens (if any). This issue tracks the latter solution as the team really wants to start shedding the legacy code ASAP.

**Comment by chinmaygarde** [comment]
Filing a followup from the conversations today in the weekly. cc @jonahwilliams @zanderso @jtmcdole

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/54694 is the prototype. I'm sure this isn't sufficient, while testing on my device works fine, I also have metal access.

@chinmaygarde any easy way I can get a metal-less environment to kick the tires on this?

**Comment by matanlurey** [comment]
Github actions CI?

**Comment by jonahwilliams** [comment]
I think github actions is fixed now and supports passthrough?

**Comment by chinmaygarde** [comment]
I can't think of a way of configuring an environment to be Metal-less. The the actions runners have access to Metal at least since version 13. Maybe older? But I don't know if these will be supported. Instead, how about adding a hook to simulate failure to create a system default device? https://github.com/flutter/engine/pull/54694#pullrequestreview-2255251500
