### ISSUE TITLE
install flutter for windows  link on website 

### ISSUE THREAD

**Issue by eomer** [flutter/flutter#15384]
hello, i faced yesterday with big problem, trying install flutter for windows for the first time, with git command on the install flutter website.
this git command take the beta version. this beta version can't install correctly, due to problem in the script flutter\bin\internal\update_dart_sdk.ps1 . 
the line 52 contain invalid parameters: 
& 7z x $dartSdkZip -o"$cachePath" -bd | Out-Null 
that must be, as in master branch 
& 7z x $dartSdkZip "-o$cachePath" -bd | Out-Null 
second, why to set beta branch by defaut for donwloading flutter ? 
give the choice will be better , master, alpha, beta..

**Comment by eomer** [comment]
i tested the change from 
`& 7z x $dartSdkZip -o"$cachePath" -bd | Out-Null`
that must be, as in master branch
`& 7z x $dartSdkZip "-o$cachePath" -bd | Out-Null` 

before call to flutter doctor.
all works perfectly.. anyone can do the change.?

**Comment by Hixie** [comment]
We've since released a beta that fixes this, so hopefully this is resolved now.

Regarding the default, we want to make it easy for people new to the platform to get our most tested version. Of course, you can easily switch branches using `flutter channel` whenever you like.
