### ISSUE TITLE
TextField starts with maxLines if it is set to anything other than null.

### ISSUE THREAD

**Issue by QoLTech** [flutter/flutter#15388]
Setting `maxLines` allows as many lines up to that number, but it also initially starts with that many lines. So, setting `maxLines` to `5` starts with `5` lines, instead of `1`. Is this intended and how can I work around this?

Setting `maxLines` to null starts it at 1 line, but expands infinitely.

**Comment by QoLTech** [comment]
Is there any update on this? Any work around even?

This is a blocker for me.

**Comment by tobire** [comment]
Any updates on this? Would really look forward to seeing a fix for it.

**Comment by wwwdata** [comment]
I also had this problem what worked for me was setting the `maxLines: null` and wrapping the `TextField` inside a `Container` that has a `BoxConstraints.loose(Size.fromHeight(100.0))` to limit the height of the container box. This has the desired effect that the box grows with the content and has a max height.

But it would be really nice if this gets fixed soon :)

**Comment by d-silveira** [comment]
I believe that logically, is makes sense that the textField occupies the space of the maxLines, what seems to me to be missing, since some people need it is a flag similar to the Column's ``MainAxisSize.min and ``MainAxisSize.max`` as I stated in [https://github.com/flutter/flutter/issues/18825](this other issue regarding the counter logical behaviour of the maxLines=null case)

**Comment by szotp** [comment]
Anyone knows how to force TextField to have minimum height? Constraints do not work because they just expand something else.

**Comment by nelsonnwezeaku** [comment]
Until a better solution is available I use this:

`Container(
      color: Colors.white,
      constraints: BoxConstraints(
          maxHeight: 144.0,
          maxWidth: _screenWidth(),
          minHeight: 48.0,
          minWidth: _screenWidth()),
      padding: EdgeInsets.only(left: 16.0, right: 16.0, top: 8.0, bottom: 4.0),
      child: TextField(
        maxLines: null,
        keyboardType: TextInputType.multiline,
        decoration: InputDecoration.collapsed(
          hintText: "Write a comment",
        ),
      ),
    )`

The initial height is constrained by the BoxConstraints minHeight parameter, and setting maxLines = null has the effect that the Container grows until constrained by the maxHeight parameter.

This can be wrapped in a ScrollBar widget to get a scrollbar.

**Comment by nelsonnwezeaku** [comment]
Until a better solution is available, this is a workaround:
 


The initial height is constrained by the BoxConstraints minHeight parameter, and setting maxLines = null has the effect that the Container grows until constrained by the maxHeight parameter.
```dart
return Container(
      color: Colors.white,
      constraints: BoxConstraints(
          maxHeight: 144.0,
          maxWidth: _screenWidth(),
          minHeight: 48.0,
          minWidth: _screenWidth()),
      padding: EdgeInsets.only(left: 16.0, right: 16.0, top: 8.0, bottom: 4.0),
      child: TextField(
        maxLines: null,
        keyboardType: TextInputType.multiline,
        decoration: InputDecoration.collapsed(
          hintText: "Write a comment",
        ),
      ),
    );

```
This can be wrapped in a ScrollBar widget to get a scrollbar.

**Comment by justinmc** [comment]
@QoLTech and anyone else interested in this thread, I've put together a proposal for some changes to TextField to make these sorts of things much more easy to do.  I know this is an old issue, but if anyone has any feedback on whether this solves their problem, please take a look!  https://github.com/flutter/flutter/pull/27205

**Comment by justinmc** [comment]
Closing this with https://github.com/flutter/flutter/pull/27205.

With that PR, you can now make a text field that grows from 1 line up to `maxLines` like this for example:
```dart
TextField(
  minLines: 1,
  maxLines: 4,
)
```

**Comment by patelkrunal78** [comment]
There’s no notion of “Starts from max/min size”.

The thing is, ContrainedBox only add constraints to it’s child. But in the end, it doesn’t pick a size.

If you want your child to hit minSize, then they have to not expend. Which translate into not having a width/height of double.INFINITY. Fact is that double.INFINITY is the default value of many widgets, including Container.

On the other hand, some widgets such as DecoratedBox have a default size of 0. Which means that this code :

Find Code At [Here](https://icetutor.com/question/flutter-correct-way-to-create-a-box-that-starts-at-minheight-grows-to-maxheight)

**Comment by justinmc** [comment]
@patelkrunal78 I think TextField does allow that kind of growing behavior, if I understand you correctly.  Are you saying that you need the same sort of behavior for ConstrainedBox?
