### ISSUE TITLE
path_provider requires Flutter SDK version >=0.1.4 <2.0.0 but the current SDK is 0.0.0-unknown.

### ISSUE THREAD

**Issue by fmatuszewski** [flutter/flutter#15385]
## Steps to Reproduce

add dependency in pubspec.yaml for path_provider
dependencies:
  path_provider:
    path: ../plugins/packages/path_provider
  flutter:
    sdk: flutter
and execute 
flutter packages get

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

/usr/local/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in mobile_client...
Package path_provider requires Flutter SDK version >=0.1.4 <2.0.0 but the current SDK is 0.0.0-unknown.
pub get failed (1)
Process finished with exit code 1

## Flutter Doctor

[✓] Flutter (Channel beta, v0.0.0-unknown, on Linux, locale en_US.UTF-8)
    • Flutter version 0.0.0-unknown at /usr/local/flutter
    • Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/fmatuszewski/Android/Sdk
    • Android NDK at /home/fmatuszewski/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.3942.31

[!] VS Code (version 1.19.0)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by viju85** [comment]
@fmatuszewski Have you found a solution to this problem?

**Comment by zoechi** [comment]
I'd try `flutter channel dev` `flutter doctor`
If that helps you can try switching back to beta. 
Something seems to be wrong with your Flutter setup 

> [✓] Flutter (Channel beta, v0.0.0-unknown

looks weird

**Comment by cxrvh** [comment]
The installed Git version could be too old.

I'm using CentOS 7 which provides Git v1.8.3.1. But determine() from GitTagVersion ([packages/flutter_tools/lib/src/version.dart](https://github.com/flutter/flutter/blob/v0.3.2/packages/flutter_tools/lib/src/version.dart#L494)) uses "git describe --first-parent" which was introduced with [Git v1.8.4](https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.4.txt#L204).

As a workaround I simply removed "--first-parent":
> [✓] Flutter (Channel beta, v0.3.2, on Linux, locale de_DE.utf8)

**Comment by meg32** [comment]
@cxrvh Can you please explain how you implemented your fix?   What to do following the edit of the "version.dart" file by removing the "--first-parent"?   At what point is this "tool" executed?

**Comment by zoechi** [comment]
@fmatuszewski is this still an issue?

**Comment by zoechi** [comment]
@meg32 if you have this issue with CentOS 7 as explained by @cxrvh, then it would be better to create a new issue (with a link to this one) and a filled issue template.

**Comment by funkybaboon** [comment]
I'm facing the same issue installing flutter in a centos7 docker. This is part of my dockerfile:

```
# install flutter sdk
ENV FLUTTER_HOME ${HOME}/sdks/flutter
ENV FLUTTER_VERSION 0.5.7

RUN git clone --branch v${FLUTTER_VERSION} https://github.com/flutter/flutter.git ${FLUTTER_HOME}

ENV PATH ${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin

RUN flutter doctor
```
flutter doctor is outputting the same error message.

**Comment by zoechi** [comment]
@funkybaboon 
Please add the output of `flutter doctor -v`.

**Comment by funkybaboon** [comment]
```
[root@5ed9ed2f9a1f /]# flutter doctor -v
[!] Flutter (Channel @{u}, v0.0.0-unknown, on Linux, locale en_US)
    • Flutter version 0.0.0-unknown at /sdks/flutter
    • Framework revision 66091f9696 (6 weeks ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5
      

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /root/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /root/android-sdk-linux
    • Java binary at: /usr/lib/jvm/java-1.8.0/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_151-b12)
    • All Android licenses accepted.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by funkybaboon** [comment]
I fixed it by uprading git.
```
yum -y install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
yum -y install git
```

**Comment by gdky005** [comment]
> I fixed it by upgrading git.
> 
> ```
> yum -y install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
> yum -y install git
> ```

Very good! I'm working!
