### ISSUE TITLE
Firebase For Flutter codelab pubspec.yaml is out of date 

### ISSUE THREAD

**Issue by mdanics** [flutter/flutter#15380]
Following the [code lab](https://codelabs.developers.google.com/codelabs/flutter-firebase/#4) on the 5th step. 

Using the config that is told produces the error:
`Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.`
when trying to run. 

Also seen on this [stackoverflow](https://stackoverflow.com/questions/46267621/unable-to-merge-dex)

**Comment by Sfshaza** [comment]
This codelab has been obsoleted and replaced by a completely new Firebase + Flutter codelab. (Same URL)  Closing.
