### ISSUE TITLE
[interactive_media_ads] AdEventType.contentResumeRequested not triggered sometimes

### ISSUE THREAD

**Issue by abhi7054** [flutter/flutter#153887]
### Steps to reproduce

This issue happens randomly.

### Expected results

The AdEventType.contentResumeRequested should be triggered whenever the ad is skipped or completed. 

### Actual results

The ad starts playing and completes but onAdEvent is not triggered sometimes. It should trigger all the time. I have a debugPrint statement showing which event it was and sometimes all I see in the logs is 
AdEventType.started => {}
AdEventType.contentPauseRequested => {}

Nothing after that. 

### Code sample

```dart
Future<void> _requestAds(AdDisplayContainer container) {
    _adsLoader = AdsLoader(
      container: container,
      onAdsLoaded: (OnAdsLoadedData data) {
        final AdsManager manager = data.manager;
        _adsManager = data.manager;

        manager.setAdsManagerDelegate(AdsManagerDelegate(
          onAdEvent: (AdEvent event) {
            debugPrint('OnAdEvent: ${event.type} => ${event.adData}');
            switch (event.type) {
              case AdEventType.loaded:
                manager.start();
                break;
              case AdEventType.contentPauseRequested:
                _pauseContent();
                break;
              case AdEventType.contentResumeRequested:
                _resumeContent();
                break;
              case AdEventType.allAdsCompleted:
                manager.destroy();
                _adsManager = null;
                break;
              case AdEventType.clicked:
              case AdEventType.complete:
              case _:
                break;
            }
          },
          onAdErrorEvent: (AdErrorEvent event) {
            debugPrint('AdErrorEvent: ${event.error.message}');
            _resumeContent();
          },
        ));

        manager.init();
      },
      onAdsLoadError: (AdsLoadErrorData data) {
        debugPrint('OnAdsLoadError: ${data.error.message}');
        _resumeContent();
      },
    );

    return _adsLoader.requestAds(AdsRequest(adTagUrl: _adTagUrl));
  }
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @abhi7054, what version of `interactive_media_ads` are you using? What platform(s) are you seeing this issue on? Are you experiencing this issue with the plugin example app? If not, please provide a complete minimal reproducible code sample. 

Thank you

**Comment by abhi7054** [comment]
@danagbemava-nc 
I'm using the version 0.1.2+4. 
Flutter 3.24.0
It happens on iOS and android. 
Yes, I'm having the issue with the plug-in example as well.

**Comment by danagbemava-nc** [comment]
Hi @abhi7054, what device(s) are you testing on? How often does it happen that you stop receiving the events? I just tested a few times and I seem to get the events consistently

**Comment by abhi7054** [comment]
@danagbemava-nc  Getting it on every device I tested. 
Here's the class I'm using it in. 
For more context, the app is similar to YouTube. There's a list of videos for users to choose from that opens this view which is supposed to play the ad first then the video. 
If you would like to take a look I can provide you access to the repo. 


class PreviewVideoUi extends StatefulWidget {
  const PreviewVideoUi({
    super.key,
    required this.orientation,
    required this.height,
    required this.url,
  });

  final Orientation orientation;
  final double height;
  final String url;

  @override
  State<PreviewVideoUi> createState() => _PreviewVideoUiState();
}

class _PreviewVideoUiState extends State<PreviewVideoUi> {
  static const String _adTagUrl =
      'https://pubads.g.doubleclick.net/gampad/ads?iu=/21822577512,23154388855/hqz_1_ios&description_url=https%3A%2F%2Fhqz.gg%2F&tfcd=0&npa=0&sz=426x240%7C640x360%7C640x480%7C854x480%7C1280x720%7C1920x1080&min_ad_duration=5000&max_ad_duration=30000&gdfp_req=1&unviewed_position_start=1&output=vast&env=vp&impl=s&correlator=';

  late final AdsLoader _adsLoader;
  AdsManager? _adsManager;
  bool _shouldShowContentVideo = true;
  bool _isVideoLoading = false;
  bool _isShowVideoControls = false;
  final controller = Get.put(NormalVideoDetailsController());

  late final VideoPlayerController _contentVideoController;
  late final AdDisplayContainer _adDisplayContainer = AdDisplayContainer(
    onContainerAdded: (AdDisplayContainer container) {
      _requestAds(container);
    },
  );

  @override
  void initState() {
    super.initState();
    _contentVideoController = VideoPlayerController.networkUrl(Uri.parse(widget.url))
      ..addListener(() {
        setState(() {
          _isVideoLoading = _contentVideoController.value.isBuffering;
          if (_contentVideoController.value.isCompleted) {
            _adsLoader.contentComplete();
          }
        });
      })
      ..initialize().then((_) {
        setState(() {});
      });
  }

  Future<void> _requestAds(AdDisplayContainer container) {
    _adsLoader = AdsLoader(
      container: container,
      onAdsLoaded: (OnAdsLoadedData data) {
        final AdsManager manager = data.manager;
        _adsManager = data.manager;

        manager.setAdsManagerDelegate(AdsManagerDelegate(
          onAdEvent: (AdEvent event) {
            debugPrint('OnAdEvent: ${event.type} => ${event.adData}');
            switch (event.type) {
              case AdEventType.loaded:
                manager.start();
                break;
              case AdEventType.contentPauseRequested:
                _pauseContent();
                break;
              case AdEventType.contentResumeRequested:
                _resumeContent();
                break;
              case AdEventType.allAdsCompleted:
                manager.destroy();
                _adsManager = null;
                break;
              case AdEventType.clicked:
              case AdEventType.complete:
              case _:
                break;
            }
          },
          onAdErrorEvent: (AdErrorEvent event) {
            debugPrint('AdErrorEvent: ${event.error.message}');
            _resumeContent();
          },
        ));

        manager.init();
      },
      onAdsLoadError: (AdsLoadErrorData data) {
        debugPrint('OnAdsLoadError: ${data.error.message}');
        _resumeContent();
      },
    );

    return _adsLoader.requestAds(AdsRequest(adTagUrl: _adTagUrl));
  }

  Future<void> _resumeContent() async {
    await Future.delayed(Duration(milliseconds: 200)); // Ensure smooth transition
    setState(() {
      _shouldShowContentVideo = true;
    });
    return _contentVideoController.play();
  }

  Future<void> _pauseContent() {
    setState(() {
      _shouldShowContentVideo = false;
    });
    return _contentVideoController.pause();
  }

  void _toggleVideoControls() {
    setState(() {
      _isShowVideoControls = !_isShowVideoControls;
    });
  }

  Future<void> _skipForward() async {
    await _contentVideoController.seekTo(
        _contentVideoController.value.position + const Duration(seconds: 10));
  }

  Future<void> _skipBackward() async {
    await _contentVideoController.seekTo(
        _contentVideoController.value.position - const Duration(seconds: 10));
  }

  void _toggleFullscreen() {
    if (widget.orientation == Orientation.portrait) {
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.landscapeRight,
        DeviceOrientation.landscapeLeft,
      ]);
    } else {
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.portraitDown,
      ]);
    }
  }

  void _onBackPressed() {
    if (widget.orientation == Orientation.portrait) {
      _pauseContent();
      Get.back();
    } else {
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.portraitDown,
      ]);
    }
  }

  @override
  void dispose() {
    _contentVideoController.dispose();
    _adsManager?.destroy();
    super.dispose();
  }

  @override
Widget build(BuildContext context) {
  return Container(
    width: double.infinity, // Ensure full width
    height: widget.orientation == Orientation.portrait
        ? widget.height // Fixed height in portrait mode
        : MediaQuery.of(context).size.height, // Fullscreen height in landscape
    color: Colors.black,
    child: !_contentVideoController.value.isInitialized
        ? const Center(child: CircularProgressIndicator(color: Colors.white))
        : Stack(
            children: <Widget>[
              Positioned.fill(
                child: _adDisplayContainer,
              ),
              if (_shouldShowContentVideo)
                GestureDetector(
                  onTap: _toggleVideoControls,
                  child: Container(
                    width: double.infinity,
                    height: double.infinity,
                    child: FittedBox(
                      fit: BoxFit.cover, // Cover the entire space without stretching
                      child: SizedBox(
                        width: _contentVideoController.value.size.width,
                        height: _contentVideoController.value.size.height,
                        child: VideoPlayer(_contentVideoController),
                      ),
                    ),
                  ),
                ),
              if (_isShowVideoControls)
                Positioned.fill(
                  child: Stack(
                    children: [
                      // Back Button
                      Positioned(
                        top: 15,
                        left: 10,
                        child: IconButton(
                          icon: const Icon(Icons.arrow_back, color: Colors.white),
                          onPressed: _onBackPressed,
                        ),
                      ),
                      // More Options Button
                      Positioned(
                        top: 15,
                        right: 10,
                        child: IconButton(
                          icon: const Icon(Icons.more_vert, color: Colors.white),
                          onPressed: () {
                            if (widget.orientation == Orientation.portrait) {
                              // Show bottom sheet or dialog in portrait mode
                              _showMoreOptionsPortrait(context);
                            } else {
                              // Show more options dialog in landscape mode
                              _showMoreOptionsLandscape(context);
                            }
                          },
                        ),
                      ),
                      // Center Video Controls
                      Center(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceAround,
                          children: [
                            IconButton(
                              icon: const Icon(Icons.replay_10, color: Colors.white),
                              onPressed: _skipBackward,
                            ),
                            IconButton(
                              icon: Icon(
                                _contentVideoController.value.isPlaying
                                    ? Icons.pause
                                    : Icons.play_arrow,
                                color: Colors.white,
                                size: 30,
                              ),
                              onPressed: () {
                                setState(() {
                                  _contentVideoController.value.isPlaying
                                      ? _contentVideoController.pause()
                                      : _contentVideoController.play();
                                });
                              },
                            ),
                            IconButton(
                              icon: const Icon(Icons.forward_10, color: Colors.white),
                              onPressed: _skipForward,
                            ),
                          ],
                        ),
                      ),
                      // Fullscreen Button
                      widget.orientation == Orientation.portrait
                          ? Positioned(
                              bottom: 20,
                              right: 20,
                              child: Row(
                                children: [
                                  // Progress Bar
                                  SizedBox(
                                    width: Get.width - 80, // Adjust this width as needed
                                    child: VideoProgressIndicator(
                                      _contentVideoController,
                                      allowScrubbing: true,
                                      colors: const VideoProgressColors(
                                        backgroundColor: Colors.grey,
                                        playedColor: Colors.red,
                                        bufferedColor: Colors.white54,
                                      ),
                                    ),
                                  ),
                                  // Fullscreen Button
                                  IconButton(
                                    icon: const Icon(Icons.fullscreen, color: Colors.white),
                                    onPressed: _toggleFullscreen,
                                  ),
                                ],
                              ),
                            )
                          : const Offstage(),
                      // Additional Landscape Controls
                      if (widget.orientation == Orientation.landscape)
                        ...[
                          Positioned(
                            bottom: 5,
                            child: SizedBox(
                              width: MediaQuery.of(context).size.width,
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.end,
                                children: [
                                  Row(
                                mainAxisAlignment: MainAxisAlignment.spaceAround,
                                children: [
                                  Obx(
                                    () => IconButton(
                                      onPressed: () async {
                                        if (!controller.isLike.value) {
                                          if (controller.isDisLike.value) {
                                            controller.isDisLike.value = false;
                                            controller.customChanges["disLike"]--;
                                          }
                                          controller.isLike.value = true;
                                          controller.customChanges["like"]++;
                                          await LikeDisLikeVideoApi.callApi(controller.videoId, true);
                                        }
                                      },
                                      icon: ImageIcon(
                                        AssetImage(controller.isLike.value
                                            ? AppIcons.likeBold
                                            : AppIcons.like),
                                        size: 25,
                                        color: AppColors.white,
                                      ).paddingOnly(bottom: 2),
                                    ),
                                  ),
                                  Obx(
                                    () => IconButton(
                                      onPressed: () async {
                                        if (!controller.isDisLike.value) {
                                          if (controller.isLike.value) {
                                            controller.isLike.value = false;
                                            controller.customChanges["like"]--;
                                          }
                                          controller.isDisLike.value = true;
                                          controller.customChanges["disLike"]++;
                                          await LikeDisLikeVideoApi.callApi(controller.videoId, false);
                                        }
                                      },
                                      icon: ImageIcon(
                                        AssetImage(controller.isDisLike.value
                                            ? AppIcons.disLikeBold
                                            : AppIcons.disLike),
                                        size: 25,
                                        color: AppColors.white,
                                      ).paddingOnly(top: 2),
                                    ),
                                  ),
                                  IconButton(
                                    onPressed: () {
                                      if (controller.isSave.value == false) {
                                        controller.isSave.value = true;
                                        CustomToast.show(AppStrings.addToWatchLater.tr);
                                        CreateWatchLater.callApi(Database.loginUserId!, controller.videoId);
                                      }
                                    },
                                    icon: Obx(
                                      () => ImageIcon(
                                        AssetImage(controller.isSave.value
                                            ? AppIcons.saveDone1
                                            : AppIcons.addToSave),
                                        size: 22,
                                        color: AppColors.white,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                              SizedBox(
                                    width: Get.width - 80, // Adjust this width as needed
                                    child: VideoProgressIndicator(
                                      _contentVideoController,
                                      allowScrubbing: true,
                                      colors: const VideoProgressColors(
                                        backgroundColor: Colors.grey,
                                        playedColor: Colors.red,
                                        bufferedColor: Colors.white54,
                                      ),
                                    ),
                                  ),
                                ]
                            ).paddingSymmetric(horizontal: 10),
                            ),
                          ),
                          Positioned(
                              bottom: 30,
                              right: 20,
                              child:
                                  // Progress Bar
                                  SizedBox(
                                    width: Get.width - 80, 
                                    height: 5,// Adjust this width as needed
                                    child: VideoProgressIndicator(
                                      _contentVideoController,
                                      allowScrubbing: true,
                                      colors: const VideoProgressColors(
                                        backgroundColor: Colors.grey,
                                        playedColor: Colors.red,
                                        bufferedColor: Colors.white54,
                                      ),
                                    ),
                                  )
                            )
                        ],
                    ],
                  ),
                ),
              if (_isVideoLoading)
                const Center(
                  child: CircularProgressIndicator(
                    color: Colors.white,
                  ),
                ),
            ],
          ),
  );
}

  
  void _showMoreOptionsPortrait(BuildContext context) {
    Get.bottomSheet(
      backgroundColor: isDarkMode.value ? AppColors.secondDarkMode : AppColors.white,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(25),
          topRight: Radius.circular(25),
        ),
      ),
      SizedBox(
        height: 350,
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 15),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SizedBox(height: 8),
                Center(
                  child: Container(
                    width: 30,
                    height: 3,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(60),
                      color: AppColors.grey_300,
                    ),
                  ),
                ),
                const SizedBox(height: 4),
                Center(
                  child: Text(
                    AppStrings.moreOption.tr,
                    style: GoogleFonts.urbanist(
                      textStyle: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 20,
                      ),
                    ),
                  ),
                ),
                Divider(indent: 20, endIndent: 20, color: AppColors.grey_200),
                const SizedBox(height: 5),
                Row(children: [
                  const ImageIcon(AssetImage(AppIcons.loopVideo)),
                  const SizedBox(width: 10),
                  Text(
                    AppStrings.loopVideo.tr,
                    style: GoogleFonts.urbanist(
                      textStyle: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 15,
                      ),
                    ),
                  ),
                  const Spacer(),
                  SizedBox(
                    height: 20,
                    width: 25,
                    child: Transform.scale(
                      scale: 0.7,
                      child: Obx(
                        () => CupertinoSwitch(
                          activeColor: AppColors.primaryColor,
                          value: controller.isLoop.value,
                          onChanged: (value) {
                            controller.isLoop.value = value;
                            controller.onChangeLoop();
                          },
                        ),
                      ),
                    ),
                  ).paddingOnly(right: 10),
                ]),
                const SizedBox(height: 20),
                GestureDetector(
                  onTap: () {
                    Get.back();
                    _showPlaybackSpeedOptions(context);
                  },
                  child: Row(
                    children: [
                      const ImageIcon(AssetImage(AppIcons.playSpeed), size: 22),
                      const SizedBox(width: 10),
                      Text(
                        AppStrings.playbackSpeed.tr,
                        style: GoogleFonts.urbanist(
                          textStyle: const TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 15,
                          ),
                        ),
                      ),
                      const Spacer(),
                      Obx(
                        () => Text(
                          controller.currentSpeedIndex.value == 2
                              ? AppStrings.normal.tr
                              : "${controller.speedOptions[controller.currentSpeedIndex.value]}x",
                          style: GoogleFonts.urbanist(
                            textStyle: const TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 15,
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(width: 3),
                      const ImageIcon(
                        AssetImage(AppIcons.arrowDown),
                        size: 18,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 20),
                GestureDetector(
                  onTap: () {
                    Get.back();
                    CustomReportView.show(controller.videoId);
                  },
                  child: Row(
                    children: [
                      const ImageIcon(AssetImage(AppIcons.report)),
                      const SizedBox(width: 10),
                      Text(
                        AppStrings.report.tr,
                        style: GoogleFonts.urbanist(
                          textStyle: const TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 15,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 20),
                if (controller.videoDetailsModel!.detailsOfVideo!.channelName ==
                    AppSettings.channelName.string) ...[
                  GestureDetector(
                    onTap: () {
                      Get.back();
                      controller.onClickEdit();
                    },
                    child: Row(
                      children: [
                        const ImageIcon(AssetImage(AppIcons.edit)),
                        const SizedBox(width: 10),
                        Text(
                          'Edit Video',
                          style: GoogleFonts.urbanist(
                            textStyle: const TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 15,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 20),
                  GestureDetector(
                    onTap: () {
                      Get.back();
                      controller.onClickDelete(context);
                    },
                    child: Row(
                      children: [
                        const Icon(Icons.delete),
                        const SizedBox(width: 10),
                        Text(
                          'Delete Video',
                          style: GoogleFonts.urbanist(
                            textStyle: const TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 15,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 20),
                ],
                const SizedBox(height: 20),
              ],
            ),
          ),
        ),
      ),
    );
  }

  void _showMoreOptionsLandscape(BuildContext context) {
    Get.defaultDialog(
      title: AppStrings.moreOption.tr,
      titlePadding: const EdgeInsets.only(top: 10),
      titleStyle: GoogleFonts.urbanist(
        textStyle: const TextStyle(
          fontWeight: FontWeight.bold,
          fontSize: 20,
        ),
      ),
      backgroundColor: isDarkMode.value ? AppColors.secondDarkMode : AppColors.white,
      contentPadding: const EdgeInsets.symmetric(horizontal: 10),
      content: Container(
        height: 130,
        padding: EdgeInsets.symmetric(horizontal: 10),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20),
          color: Colors.transparent,
        ),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Divider(indent: 25, endIndent: 25, color: AppColors.grey_300),
              const SizedBox(height: 5),
              Row(children: [
                const ImageIcon(AssetImage(AppIcons.loopVideo)),
                const SizedBox(width: 10),
                Text(
                  AppStrings.loopVideo.tr,
                  style: GoogleFonts.urbanist(
                    textStyle: const TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 15,
                    ),
                  ),
                ),
                const Spacer(),
                SizedBox(
                  height: 20,
                  width: 25,
                  child: Transform.scale(
                    scale: 0.7,
                    child: Obx(
                      () => CupertinoSwitch(
                        activeColor: AppColors.primaryColor,
                        value: controller.isLoop.value,
                        onChanged: (value) {
                          controller.isLoop.value = value;
                          controller.onChangeLoop();
                        },
                      ),
                    ),
                  ),
                ).paddingOnly(right: 10),
              ]),
              const SizedBox(height: 15),
              GestureDetector(
                onTap: () {
                  Get.back();
                  _showPlaybackSpeedOptions(context);
                },
                child: Row(
                  children: [
                    const ImageIcon(AssetImage(AppIcons.playSpeed)),
                    const SizedBox(width: 10),
                    Text(
                      AppStrings.playbackSpeed.tr,
                      style: GoogleFonts.urbanist(
                        textStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 15,
                        ),
                      ),
                    ),
                    const Spacer(),
                    Obx(
                      () => Text(
                        controller.currentSpeedIndex.value == 2
                            ? AppStrings.normal.tr
                            : "${controller.speedOptions[controller.currentSpeedIndex.value]}x",
                        style: GoogleFonts.urbanist(
                          textStyle: const TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 15,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 3),
                    const ImageIcon(
                      AssetImage(AppIcons.arrowDown),
                      size: 18,
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 15),
              GestureDetector(
                onTap: () {
                  Get.back();
                  CustomReportView.show(controller.videoId);
                },
                child: Row(
                  children: [
                    const ImageIcon(AssetImage(AppIcons.report)),
                    const SizedBox(width: 10),
                    Text(
                      AppStrings.report.tr,
                      style: GoogleFonts.urbanist(
                        textStyle: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 15,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _showPlaybackSpeedOptions(BuildContext context) {
    Get.defaultDialog(
      title: AppStrings.playbackSpeed.tr,
      titlePadding: const EdgeInsets.only(top: 20),
      titleStyle: GoogleFonts.urbanist(
        textStyle: const TextStyle(
          fontWeight: FontWeight.bold,
          fontSize: 16,
        ),
      ),
      backgroundColor: isDarkMode.value ? AppColors.secondDarkMode : AppColors.white,
      content: Container(
        height: 170,
        padding: EdgeInsets.symmetric(horizontal: 10),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20),
          color: AppColors.transparent,
        ),
        child: Column(
          children: [
            const Divider(),
            Expanded(
              child: SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                    for (int i = 0; i < controller.speedOptions.length; i++)
                      Padding(
                        padding: const EdgeInsets.only(left: 10, top: 10),
                        child: GestureDetector(
                          onTap: () {
                            controller.currentSpeedIndex.value = i;
                            controller.videoPlayerController?.setPlaybackSpeed(controller.speedOptions[controller.currentSpeedIndex.value]);
                          },
                          child: Obx(
                            () => Row(
                              children: [
                                controller.currentSpeedIndex.value == i
                                    ? Image.asset(AppIcons.done, height: 15, width: 15)
                                    : const SizedBox(width: 15),
                                const SizedBox(width: 10),
                                Text(
                                  "${controller.speedOptions[i]}x",
                                  style: GoogleFonts.urbanist(
                                    textStyle: const TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 15,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by danagbemava-nc** [comment]
Hi @abhi7054, does this happen after you've changed/switched videos? If you could provide a complete runnable sample without any third-party packages so that we could properly investigate this, that would help.

Thank you
