### ISSUE TITLE
Drawer is snapping into place while dragging half way

### ISSUE THREAD

**Issue by azeunkn0wn** [flutter/flutter#153851]
### Steps to reproduce

1. Slowly drag the Drawer to open/close
2. Do not swipe or release, keep dragging until fully closed/open

### Expected results

Drawer will follow the position of my finger while dragging

### Actual results

Drawer will snap to fully closed or fully open position while my finger is still dragging half way.

### Code sample

<details open><summary>Code sample</summary>

```dart
 Scaffold(
      drawer: Drawer(),
    );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
    • Flutter version 3.24.0 on channel stable at C:\DEV\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\DEV\Android\SDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] Connected device (4 available)
    • 21051182G (mobile) • 17c8c276 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 127.0.6533.120
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 127.0.2651.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Thank you for the report. I can reproduce this issue on Flutter master channel `3.25.0-1.0.pre.78` as well. I also checked this on the previous stable release 3.22.3, the issue doesn't happen there. Looks like a regression.

<details open>
<summary>Demo</summary>

| 3.24 and 3.25 ❗ | 3.22.3 ✅ |
| --------------- | --------------- |
<video src="https://github.com/user-attachments/assets/b508e060-f12a-4c78-b44a-4ab246e704c6"/> | <video src="https://github.com/user-attachments/assets/102734ff-b341-4dc2-b7cc-347d167ad6f7"/>

</details>

**Comment by huycozy** [comment]
I bisected this and found the culprit commit 76a07a16464b504bc37b770a836ba85753a33065 which came from a big PR https://github.com/flutter/flutter/pull/148570. Kindly cc @nate-thegrate for thoughts.

**Comment by nate-thegrate** [comment]
Thank you Huy! I'll work on fixing this one.
