### ISSUE TITLE
StandardMessageCodec should be extensible

### ISSUE THREAD

**Issue by Skylled** [flutter/flutter#15389]
Working on issues with the Firestore plugin, specifically #13043, and the need to have support for additional types that are specific to the Firestore plugin, led to the creation of flutter/plugins#343 .

This solution works, but introduces code duplication and additional maintenance needs.

A more permanently correct solution would be to allow for StandardMessageCodec to be extended somehow. The particulars of how to do so are why I opened this for discussion.

**Comment by Skylled** [comment]
The first solution that comes to mind is to make `readValue` and `writeValue` public methods, so they can be overridden. This solution would allow for the FirestoreMessageCodec to look something like this:

```
class FirestoreMessageCodec extends StandardMessageCodec {
  static const int _kDateTime = 14;
  static const int _kGeoPoint = 15;
  static const int _kDocumentReference = 16;

  const FirestoreMessageCodec();

  @override
  void writeValue(WriteBuffer buffer, dynamic value) {
    if (value is DateTime) {
      buffer.putUint8(_kDateTime);
      buffer.putInt64(value.microsecondsSinceEpoch);
    // other types
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  dynamic readValue(ReadBuffer buffer){
    if (!buffer.hasRemaining) throw const FormatException('Message corrupted');
    dynamic result;
    switch (buffer.getUint8()) {
      case _kDateTime:
        final int microseconds = buffer.getInt64();
        result = new DateTime.fromMicrosecondsSinceEpoch(microseconds);
        break;
      default:
        // Obvious problem here is that we've already read the type from the buffer.
        // I'm sure this could be worked around.
        result = super.readValue(buffer);
    }
    return result;
  }
}
```

**Comment by Skylled** [comment]
cc @mravn-google @Hixie @collinjackson

**Comment by Purus** [comment]
Great job Team.
