### ISSUE TITLE
Prototype (land if possible) 1 on-device UI test of an iOS platform view

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#153882]
In https://github.com/flutter/flutter/issues/152376 (https://github.com/flutter/flutter/pull/153878), we added a Dart-driven (using `flutter_driver` with some added functionality we're calling `native_driver`) test that installs, launches, takes a screenshot, and verifies a screenshot of a native Android view embedded in a flutter app; this is the first of its kind (outside of [`scenario_app`](https://github.com/flutter/engine/tree/main/testing/scenario_app/android)) because of lack of completed implementations for native screenshots.

The interface currently is _extremely_ light (some docs omitted for brevity):

```dart
/// Drives a native device or emulator that is running a Flutter application.
abstract interface class NativeDriver {
  /// Closes the native driver and releases any resources associated with it.
  Future<void> close();

  /// Take a screenshot using a platform-specific mechanism.
  Future<NativeScreenshot> screenshot();
}

/// An opaque handle to a screenshot taken on a native device.
abstract interface class NativeScreenshot {
  /// Saves the screenshot to a file at the specified [path].
  Future<String> saveAs([String? path]);

  /// Reads the screenshot as a PNG-formatted list of bytes.
  Future<Uint8List> readAsBytes();
}
```

<details>

<summary>For example, here is <code>AndroidNativeDriver</code></summary>

<br>

_Some docs and implementations omitted for brevity._

```dart
/// Drives an Android device or emulator that is running a Flutter application.
final class AndroidNativeDriver implements NativeDriver {
  @override
  Future<NativeScreenshot> screenshot() async {
    // Similar pause to the one in `<FlutterDriver>.screenshot()`.
    await Future<void>.delayed(const Duration(seconds: 2));
    final io.ProcessResult result = await _adb(
      <String>[
        ..._target._toAdbArgs(),
        'exec-out',
        'screencap',
        '-p',
      ],
      stdoutEncoding: null,
    );

    if (result.exitCode != 0) {
      throw StateError('Failed to take screenshot: ${result.stderr}');
    }

    final Uint8List bytes = result.stdout as Uint8List;
    return _AdbScreencap(bytes, _tmpDir);
  }
}

final class _AdbScreencap implements NativeScreenshot {
  const _AdbScreencap(this._bytes, this._tmpDir);

  /// Raw bytes of the screenshot in PNG format.
  final Uint8List _bytes;

  /// Temporary directory to default to when saving the screenshot.
  final io.Directory _tmpDir;

  static int _lastScreenshotId = 0;

  @override
  Future<String> saveAs([String? path]) async {
    final int id = _lastScreenshotId++;
    path ??= p.join(_tmpDir.path, '$id.png');
    await io.File(path).writeAsBytes(_bytes);
    return path;
  }

  @override
  Future<Uint8List> readAsBytes() async => _bytes;
}
```

</details>

While Android is the priority at the moment, we'd like to at least prototype an iOS backed solution.

The likely outcome is going to be either:

- a simulator only implementation that uses [`xcrun simctl io <device> screenshot <output.png>`](https://www.reddit.com/r/ios/comments/10qhjva/taking_a_screenshot_in_ios_simulator_with_the/);
- a copy of (most) of the code in [`integration_test/ios`](https://github.com/flutter/flutter/tree/master/packages/integration_test/ios)

The former, which I should verify works as I expect, would be the closest in terms of matching the Android behavior, but has the limitation of only working on iOS simulator devices (where-as `adb` also can work on debug-enabled real Android devices). The other approach is a requirement to use Apple's official testing frameworks (XCUITest and XCTest), which means, similar to `integration_test`, we would need to support a more complex workflow than what driver supports today:

```mermaid
graph LR
    subgraph Flutter Tool
        A[Bundle test plugin] --> B[Build and install app]
        B --> C[Launch app via XCUITest]
        C --> D[Start driver script]
    end

    subgraph iOS App
        E[Method channels re-publish as VM service]
    end

    subgraph Driver Script
        F[Connect to app] --> G[Instrument app]
    end

    A --> E
    D --> F
```

FWIW, it's likely we would need a similar approach for "advanced" Android driving.

If we care only about screenshots in 2024, and only simulators, the actual work perhaps is less-so, but I need to verify that.

/cc @jmagman @johnmccutchan @jonahwilliams

**Comment by jmagman** [comment]
> * a simulator only implementation that uses [`xcrun simctl io <device> screenshot <output.png>`](https://www.reddit.com/r/ios/comments/10qhjva/taking_a_screenshot_in_ios_simulator_with_the/);


Here's the code that does the same for `flutter screenshot` against an iOS simulator:
https://github.com/flutter/flutter/blob/62382c7b83a16b3f48dc06c19a47f6b8667005a5/packages/flutter_tools/lib/src/ios/simulators.dart#L288-L293


> but has the limitation of only working on iOS simulator devices (where-as `adb` also can work on debug-enabled real Android devices)

As you point out, unfortunately this has been broken since iOS 17. To cross-list, here's the issue we're using to track `flutter screenshot` being busted for physical devices: https://github.com/flutter/flutter/issues/143218

@vashworth had started on hacking a solution using XCUITest: https://github.com/flutter/flutter/pull/136491

**Comment by matanlurey** [comment]
I have made some progress: I have a test only plugin working that returns the name/ID of the simulator version. Of course that's not really useful ... so, I'm reviving Victoria's prototype above and seeing how far it can go.

**Comment by matanlurey** [comment]
I have a local prototype of using simctl for something similar, but won't land it. Closing for now.
