### ISSUE TITLE
_kMaxDroppedSwipePageForwardAnimationTime is too long

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#153996]
### Steps to reproduce

/Users/weizhang/fvm/versions/3.24.1/packages/flutter/lib/src/cupertino/route.dart
```dart
// An eyeballed value for the maximum time it takes for a page to animate forward
// if the user releases a page mid swipe.
const int _kMaxDroppedSwipePageForwardAnimationTime = 800; // Milliseconds.
```

droppedPageForwardAnimationTime will render jittery text  while using back gesture to close pages.
slow animation https://github.com/flutter/flutter/issues/153809

### Expected results

slow route animation jittery text and widgets

### Actual results

modify it to 270 or support customizing

### Code sample

https://github.com/flutter/packages/tree/main/packages/go_router/example
run this example project on IOS

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by virskor** [comment]
it's a bug about Impeller performance issue whatever

**Comment by huycozy** [comment]
Hi @virskor 
`_kMaxDroppedSwipePageForwardAnimationTime` is no longer used but `_kDroppedSwipePageAnimationDuration = Duration(milliseconds: 350)` instead. It's landed by PR https://github.com/flutter/flutter/pull/153765 recently on Flutter master channel. Can you switch to master channel and confirm it it works for your case?

**Comment by huycozy** [comment]
Glad to know it works for you. Closing this as fixed.
