### ISSUE TITLE
 The application does not run on any device.

### ISSUE THREAD

**Issue by aftercxde** [flutter/flutter#153991]
### Steps to reproduce

1. Create new project 
2. Launch in a  physical device

### Expected results

Should open the default flutter app

### Actual results

It gets stuck in the splash screen with flutter logo, sometimes only a black screen.

I tried  reinstall flutter, clear cache,delete old dependencies, `flutter clean`, `gradlew clean` etc ...(not working)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![e0dd1a5e-6b15-4098-8a77-c799d27f8679](https://github.com/user-attachments/assets/6a333a22-28aa-485b-b3ad-95bfd8fe9351)

</details>

### Logs

<details open><summary>Logs</summary>

[flutter run --verbose](https://github.com/user-attachments/files/16725518/log.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Versi¢n 10.0.22631.4037], locale es-MX)
    • Flutter version 3.24.1 on channel stable at C:\Users\aftercxde\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.92.2)
    • VS Code at C:\Users\aftercxde\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (3 available)
    • SM A145M (mobile) • RF8W90HT7NZ • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Versi¢n 10.0.22631.4037]
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 127.0.2651.105

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @aftercxde, do you only get this issue on android? Are other platforms affected (like web or windows)? Are you only facing this on the Samsung device or do you face this on emulators as well? Can you try moving the project from the D drive to C drive to see if this helps?

**Comment by aftercxde** [comment]
> Hi @aftercxde, do you only get this issue on android? Are other platforms affected (like web or windows)? Are you only facing this on the Samsung device or do you face this on emulators as well? Can you try moving the project from the D drive to C drive to see if this helps?

Hi @danagbemava-nc ,thanks for reply
I tried on the web but got the same result (I don't have installed the development kit for Windows apps)
![image](https://github.com/user-attachments/assets/cff5870b-3f01-45c0-9871-48f089bfd337)

Tested devices:
-Nubia Red Magic 8 Pro
-Samsung A14
-ZTE AXON 50 Lite
-Emulator

I moved the project from **drive D** to **drive C**, and I get the same result...
[flutter run --verbose](https://github.com/user-attachments/files/16731185/out.txt)

**Comment by aftercxde** [comment]
@danagbemava-nc 
I make another project directly on the C drive and it seems to work

![5064384466759298091](https://github.com/user-attachments/assets/54cc728a-d2f9-45c1-86de-49d8d192549f)
![image](https://github.com/user-attachments/assets/e246f9b9-1487-456d-a569-5b40bf02efd8)

I still have a question, what could it be?
Thanks!
