### ISSUE TITLE
Outdated Library

### ISSUE THREAD

**Issue by code-rover** [flutter/flutter#15397]
## Steps to Reproduce

add the following dependencies to pubspec.yaml:

image_picker: 0.1.1
google_sign_in: 0.3.1
firebase_analytics: 0.0.4
firebase_auth: 0.2.0
firebase_database: 0.0.12
firebase_storage: 0.0.5

## How to fix

This is fixed if you change the image_picker dependency to ^0.3.0
It would help people if you change the dependencies added to pubspec.yaml in step five to:

image_picker: ^0.3.0
google_sign_in: 0.3.1
firebase_analytics: 0.0.4
firebase_auth: 0.2.0
firebase_database: 0.0.12
firebase_storage: 0.0.5

**Comment by Hixie** [comment]
Can you elaborate on which codelab this refers to?
