### ISSUE TITLE
TextField can't paste

### ISSUE THREAD

**Issue by TangShin** [flutter/flutter#153906]
### Steps to reproduce

TextField(
    readOnly: false,
    obscureText: false,
    enableInteractiveSelection: true,
    toolbarOptions: ToolbarOptions(
      copy: true,
      cut: true,
      paste: true,
      selectAll: true,
    ),
),

copy, cut, selectAll. is work.
paste is true, but I can't paste.

flutter version 2.5.1.
For project reasons ， I can't update flutter sdk.

![QQ20240822-145946](https://github.com/user-attachments/assets/f5e801c7-c6ac-4eaf-90b2-f4647a9b9fec)

![QQ20240822-145920](https://github.com/user-attachments/assets/993bf2d9-424d-4355-a148-59672188f66d)

### Expected results

paste doesn't work

### Actual results

paste doesn't work

### Code sample

<details open><summary>Code sample</summary>

```dart
TextField(
    readOnly: false,
    obscureText: false,
    enableInteractiveSelection: true,
    toolbarOptions: ToolbarOptions(
      copy: true,
      cut: true,
      paste: true,
      selectAll: true,
    ),
),
```

</details>

**Comment by TangShin** [comment]
flutter version 2.5.1. 
For project reasons ， I can't update flutter sdk.

**Comment by danagbemava-nc** [comment]
The version of flutter you're using is no longer supported so unfortunately we can't offer any support in this area. As such, I'll be closing this issue. If you do encounter this issue on the latest version of flutter, kindly leave a comment below and I will reopen this. 

Thank you
