### ISSUE TITLE
Chrome "Choose your search engine" dialog appears on clean run (only EU)

### ISSUE THREAD

**Issue by westito** [flutter/flutter#153928]
### Steps to reproduce

1. Use Chrome >127 in EU
2. flutter clean
3. flutter run -d chrome

### Expected results

Chrome starts without search engine selector.

A possible solution is add `--disable-search-engine-choice-screen` to Chrome run args here:
https://github.com/flutter/flutter/blob/59e6c8d52f11ca9bd4aedd73a0dc412f7c5c3a21/packages/flutter_tools/lib/src/web/chrome.dart#L200

As described here:
https://stackoverflow.com/questions/78787332/selecting-default-search-engine-is-needed-for-chrome-version-127

### Actual results

Chrome "choose your search engine" dialog appears. 

### Code sample

<details open><summary>Code sample</summary>

```dart
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1189" alt="Képernyőfotó 2024-08-22 - 15 53 43" src="https://github.com/user-attachments/assets/7d66297e-689e-4ced-a237-644177e8427e">

</details>

### Logs

<details open><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale hu-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.2)
[✓] VS Code (version 1.92.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by kevmoo** [comment]
I'm guessing this happens because we start up Chrome without a profile in "run" mode.
