### ISSUE TITLE
Devicelab microbenchmarks take a long time, are close to the timeout limit

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#153981]
This PR failed due to timeout limit: https://github.com/flutter/flutter/pull/143799

I don't know if this test is too big, if the suite has too much tests and should be split, or what? Could anyone that is more familiar with that please take a look for me? I wish we found a way to land this test, even if we have to make it smaller.

**Comment by christopherfujino** [comment]
it looks like your benchmarks added at least 11 minutes to this target, if step 18 timed out after 30 minutes in https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/15257/infra, whereas the passing benchmarks pretty consistently finish in ~19 minutes: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/17407/infra

This seems kind of slow, but I'm not sure exactly what we're benchmarking and if that's reasonable. WDYT @goderbauer?

**Comment by bernaferrari** [comment]
Maybe I can make it quicker/shorter.

**Comment by jmagman** [comment]
Another PR pushed it over the timeout as well https://github.com/flutter/flutter/pull/154183.
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20microbenchmarks_ios/13554/infra

**Comment by jtmcdole** [comment]
These micro's are getting very macro when bunched together and not sharded out to multiple phones.  I'll try to look at which ones are taking too long to be called Micro.

**Comment by jtmcdole** [comment]
Commenting from the other thread:

Android is fast, even with devicelab.  Its 5~6 minutes.
iOS takes forever.  Uninstalling the app takes ~12 seconds. 21 tests * 12 seconds is 4.2 minutes longer.

iOS installing takes **13 seconds** (4.55 minutes)

Moving the uninstall out of the loop (the correct solution) still means the tests are taking **14m 53s**

Without breaking up the tests and sharding (microbenchmarks1, microbenchmarks2) - why aren't we compiling all the microbenchmarks into the same app?

**Comment by jtmcdole** [comment]
Landed this change already. Benchmarks now take ~6 minutes each (android/ios)
