### ISSUE TITLE
The documented CI Flutter build mechanism does not include iOS entitlements

### ISSUE THREAD

**Issue by arnab** [flutter/flutter#153980]
### Steps to reproduce

1. Add iOS entitlements (capabilities) such as sign-in-with-apple, aps (push-notifications), or app-links (universal links) to a Flutter iOS project.
2. Follow the [official Flutter guide for CI/CD](https://docs.flutter.dev/deployment/cd#cloud-build-and-deploy-setup) to create a release ipa: `flutter build ipa --release --no-codesign --build-number=n --build-name=x.y.z`
3. Build and deploy to TestFlight (in my case, I am using `fastlane`, as described above (see `Fastfile` in the code sample in this issue)
4. Notice that the resulting `ipa` is missing the entitlements (you can use `codesign -d --entitlements :- <extracted /Payload/Runner.app from ipa>` to inspect the entitlements)

### Expected results

If I create a release using XCode, and ship to TestFlight, it includes the correct entitlements as expected.

### Actual results

ipa created with flutter build and fastlane does not include the entitlements

### Code sample

My `Fastfile`:

```rb
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :ship_to_testflight do
    setup_ci if ENV['CI']

    version_code = ENV['VERSION_CODE']
    version_name = ENV['VERSION_NAME']
    UI.message("Building flutter ipa for version #{version_name} (#{version_code})")
    Dir.chdir("../") do
      sh(
        "flutter", "build", "ipa",
        "--release",
        "--no-codesign",
        "--build-number=#{version_code}",
        "--build-name=#{version_name}"
      )
    end

    match(type: "appstore", readonly: is_ci)
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_team_id: team_id,
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )

    ipa_path = lane_context[SharedValues::IPA_OUTPUT_PATH]
    UI.message("Uploading ipa to TestFlight: #{ipa_path}")
    upload_to_testflight(
      # To avoid 2FA, and use FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD instead, both apple_id
      # and skip_waiting_for_build_processing must be set. See:
      # https://docs.fastlane.tools/actions/upload_to_testflight/
      apple_id: 'REDACTED',
      skip_waiting_for_build_processing: true,
      ipa: ipa_path
    )
  end
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>
_Note: this is from my CI environment (running in Github Actions, in a `macos-14` type machine:

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by arnab** [comment]
- @ajatprabha - I noticed that you had a similar issue that was created a year ago (but was auto-closed): https://github.com/flutter/flutter/issues/129075
- @techouse - I saw that you had a great comment in there: https://github.com/flutter/flutter/issues/129075#issuecomment-1631063402

However, this mechanism also did not work for me. I am wondering if you could help triage or solve this issue!

**Comment by huycozy** [comment]
Hi @arnab 
>Notice that the resulting ipa is missing the entitlements (you can use codesign -d --entitlements :- <extracted /Payload/Runner.app from ipa> to inspect the entitlements)

I tried this on my end (in local machine) and saw the entitlements still show in the XML output. I am having `aps-environment` and `com.apple.developer.associated-domains` entries in `Runner.entitlements` file. 

I wonder if the issue only happens when you build IPA in CI environment. Per my understanding, if the entitlements are not included in your IPA when checking in local machine, it can happen on every CI tool, right? 

If this issue only happens on Fastlane, you can try https://github.com/flutter/flutter/issues/129075#issuecomment-1631063402 as mentioned to see if it works (I see a user confirmed it worked here https://github.com/fastlane/fastlane/issues/21224#issuecomment-1641966404)

**Comment by arnab** [comment]
Hi @huycozy - thanks for the comments. I had seen the first comment (and that had not worked), but the second comment you added (https://github.com/fastlane/fastlane/issues/21224#issuecomment-1641966404) led me down the right path.

I had to do a few more things, but essentially here is what works (both locally and on CI) (from my `Fastfile`):

```rb
    setup_ci if ENV['CI']

    match(type: "appstore", readonly: is_ci)

    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)

    profile_mapping = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    profile_name = profile_mapping[app_identifier]
    profile_path = ENV["sigh_" + app_identifier + "_appstore_profile-path"]
    codesigning_identity = ENV["sigh_" + app_identifier + "_appstore_certificate-name"]

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: team_id,
      bundle_identifier: app_identifier,
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
      build_configurations: ["Release"],
      entitlements_file_path: "Runner/Runner.entitlements",
      profile_name: profile_name,
    )

    update_project_provisioning(
      xcodeproj: 'Runner.xcodeproj',
      target_filter: 'Runner',
      build_configuration: 'Release',
      profile: profile_path,
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_team_id: team_id,
      output_directory: "../build/ios/ipa",
      output_name: "MyApp.ipa",
      clean: true,
      xcconfig: "Flutter/Generated.xcconfig",
      codesigning_identity: codesigning_identity,
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: profile_mapping,
      }
    )

    if (options[:ship_to_testflight]) then
      ipa_path = lane_context[SharedValues::IPA_OUTPUT_PATH]
      UI.message("Uploading ipa to TestFlight: #{ipa_path}")
      upload_to_testflight(
        apple_id: 'REDACTED',
        skip_waiting_for_build_processing: true,
        ipa: ipa_path
      )
    end
```

**Comment by arnab** [comment]
Thanks for your help!

**Comment by huycozy** [comment]
You are welcome! Glad it works for you.
