### ISSUE TITLE
Expect flutter to officially add features

### ISSUE THREAD

**Issue by maxfrees** [flutter/flutter#153918]
### Use case

Although there are many packages in the community that can implement this feature, packages in the community are unstable and may be at risk of not being maintained, it is recommended that flutter officially add these features

- The height of each item in the listview is uncertain, and it supports jumping to a certain item based on the index, such as jumping to the 22nd item in the list

- listview supports the index position of initializing scrolling, for example, the default is the 44th in the list

- The Material icon has been deprecated, and the official Material Symbols Icon is supported

- listtile support additionalInfo 

### Proposal

Although there are many packages in the community that can implement this feature, packages in the community are unstable and may be at risk of not being maintained, it is recommended that flutter officially add these features

- The height of each item in the listview is uncertain, and it supports jumping to a certain item based on the index, such as jumping to the 22nd item in the list

- listview supports the index position of initializing scrolling, for example, the default is the 44th in the list

- The Material icon has been deprecated, and the official Material Symbols Icon is supported

- listtile support additionalInfo

**Comment by danagbemava-nc** [comment]
Please file specific issues for specific requests and please check for duplicates before filing issues. 

There should be issues for all these requests, kindly upvote them.

Closing from here. 

Thank you

**Comment by maxfrees** [comment]
@danagbemava-nc   That is because these problems have not been solved for several years
