### ISSUE TITLE
It does not finish installing. Windows 10

### ISSUE THREAD

**Issue by matsyendra** [flutter/flutter#15391]
## It does not finish installing. Windows 10

flutter doctor
does not finish 15 minutes later start ..

`PS C:\> flutter doctor`
`Checking Dart SDK version...`
`Downloading Dart SDK from Flutter engine 1d0da7799583b089ede66b81068f40cc4597a429...`
`Unzipping Dart SDK...`
`Updating flutter tool...`

No advance of this state.

**Comment by anandwana001** [comment]
@matsyendra Is this issue solved?

**Comment by matsyendra** [comment]
@anandwana001 at the moment, no.

**Comment by zoechi** [comment]
I have seen this error mentioned when Flutter was installed in `C:/Program Files` or another directory where only the Administrator has write permissions.

Is this still an issue?
