### ISSUE TITLE
[url_launcher] Support FLAG_ACTIVITY_NEW_TASK Intent on Android

### ISSUE THREAD

**Issue by bruce3x** [flutter/flutter#153901]
### Use case

I want to launch a Uri in a new Activity task, a typical scenario is launching a third-party URL scheme.

### Proposal

Maybe we should add `FLAG_ACTIVITY_NEW_TASK` to Intent when using  `LaunchMode.externalApplication`?

[source code](https://github.com/flutter/packages/blob/main/packages/url_launcher/url_launcher_android/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncher.java#L87)

**Comment by bruce3x** [comment]
I try to add `FLAG_ACTIVITY_NEW_TASK` when launch external Intent in my fork version
https://github.com/bruce3x/packages/commit/02dc6d0311f6b6ef243ac733d181cd4ace15c1dd

```
  ActivityInfo activityInfo = launchIntent.resolveActivityInfo(activity.getPackageManager(), 0);

  boolean isOurApp =
      activityInfo != null && activity.getPackageName().equals(activityInfo.packageName);
  if (!isOurApp) {
    launchIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
  }
  ```
  
This change is sufficient for our needs. However, for the Flutter framework, a more generalized solution might be necessary to assist different developers.

**Comment by bruce3x** [comment]
Hi, do you have any suggestions? Maybe I can submit a PR. @gmackall @huycozy

**Comment by stuartmorgan** [comment]
Can you explain at a high level what your use case is here? I.e., what is the change in behavior, in terms of user experience, that you are trying to effect with this flag?
