### ISSUE TITLE
Animations on Android do not respect the duration scale value

### ISSUE THREAD

**Issue by OsamaQureshi796** [flutter/flutter#153910]
I'm getting some unexpected behaviour from the flutter app specially regarding the timer and animation.

### Steps to reproduce

1- Go into developer settings
2- Set all scales to another value than 1x

### Expected results

The Flutter example app should also change the speeds of the animations

### Actual results

Animation speeds in the Flutter example app are the same.

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

// Define the main function
void main() {
  runApp(MyApp());
}

// Create the MyApp class
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: TestingScreen(),
    );
  }
}

// Create the MapScreen class
class TestingScreen extends StatefulWidget {
  @override
  _TestingScreenState createState() => _TestingScreenState();
}

class _TestingScreenState extends State<TestingScreen> {
  // Create the map widget
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Map'),
      ),
      body: Container(
        width: double.infinity,
        height: double.infinity,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            MaterialButton(
                color: Colors.red,
                onPressed: () {
                  Navigator.push(context,
                      MaterialPageRoute(builder: (c) => DummyScreen()));
                })
          ],
        ),
      ),
    );
  }
}

class DummyScreen extends StatefulWidget {
  const DummyScreen({super.key});

  @override
  State<DummyScreen> createState() => _DummyScreenState();
}

class _DummyScreenState extends State<DummyScreen>
    with TickerProviderStateMixin {
  late AnimationController _controller;
  int levelClock = 30;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller = AnimationController(
        vsync: this,
        duration: Duration(
            seconds:
                levelClock) // gameData.levelClock is a user entered number elsewhere in the applciation
        );

    _controller.forward();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            PRowComponent(
              animation: StepTween(
                begin: levelClock, // THIS IS A USER ENTERED NUMBER
                end: 0,
              ).animate(_controller),
            )
          ],
        ),
      ),
    );
  }
}

class PRowComponent extends AnimatedWidget {
  PRowComponent({Key? key, required this.animation})
      : super(key: key, listenable: animation);
  Animation<int> animation;

  @override
  build(BuildContext context) {
    Duration clockTimer = Duration(seconds: animation.value);

    String timerText =
        '${clockTimer.inMinutes.remainder(60).toString()}:${clockTimer.inSeconds.remainder(60).toString().padLeft(2, '0')}';

    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        TextWidgetWithScaleFactor(
          text: "${"resend_otp"} ",
          fontSize: 14,
        ),
        TextWidgetWithScaleFactor(
          text: timerText,
          fontWeight: FontWeight.w700,
          fontSize: 16,
        )
      ],
    );
  }
}

class TextWidgetWithScaleFactor extends StatelessWidget {
  TextWidgetWithScaleFactor(
      {super.key,
      required this.text,
      this.fontSize = 12,
      // this.fontColor = AppColors.blackColor,
      this.isUnderline = false,
      this.fontWeight = FontWeight.w400,
      this.textAlign = TextAlign.start,
      this.maxLines,
      this.textOverflow = TextOverflow.clip,
      this.litterSpacing = 0.0,
      this.wordSpacing,
      this.lineHeight,
      this.fontFamily});
  String text;
  double? fontSize;
  Color? fontColor;
  FontWeight? fontWeight;
  bool? isUnderline;
  TextAlign? textAlign;
  int? maxLines;
  TextOverflow? textOverflow;
  double? litterSpacing;
  double? wordSpacing;
  double? lineHeight;
  String? fontFamily;

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      textAlign: textAlign,
      maxLines: maxLines,
      overflow: textOverflow,
      textScaleFactor: 1.0,
      style: TextStyle(
          fontSize: fontSize,
          fontWeight: fontWeight,
          color: fontColor,
          height: lineHeight,
          letterSpacing: litterSpacing,
          decoration: isUnderline! ? TextDecoration.underline : null,
          decorationColor: Colors.transparent),
    );
  }
}

```

</details>

### Logs

It's a production issue so i don't have any logs neither in crashlytics nor in other logging system.

### Related Issues

Here's some issues that are almost like mine.

https://github.com/flutter/flutter/issues/10101
https://github.com/flutter/flutter/issues/60917

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-QA)
    • Flutter version 3.24.0 on channel stable at /Users/myMac/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/myMac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Users/User/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.120
    ! Error: Browsing on the local area network for Shadi’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by danagbemava-nc** [comment]
Based on this comment, it seems like there isn't a way for flutter to get these values so we can't really do much here https://github.com/flutter/flutter/issues/10101#issuecomment-398940831. 
However, it has been a while since that comment was posted and I don't know if this has changed or not but given that this is a developer setting, it doesn't seem like this might have changed. As such, I'll be closing this based on that comment. If you know of an API that will enable us to change this, kindly leave a comment below and I will reopen this. 

Thank you

**Comment by OsamaQureshi796** [comment]
Hi @danagbemava-nc ,

I figured it out it's problem with Animation no matter what ever animation i run it doesn't respect the time even though settings is normal one.
