### ISSUE TITLE
Pub not recognized after installing flutter?

### ISSUE THREAD

**Issue by doctormellow** [flutter/flutter#15393]
## Steps to Reproduce

Install Flutter
add environment variable of PATH to my flutter directory
Run "flutter doctor" (see below)
(Previously ran doctor to download the dart SDK, and then the command updated the flutter tool)

I follow the low level html tutorial to build a webpage with HTML, CSS & Dart
https://webdev.dartlang.org/tutorials/low-level-html/connect-dart-html 

Once all is said and dandy, says you can run it with..

- dart2js (soon to be deprecated?)
- dartdevc
- pub build & pub serve

https://webdev.dartlang.org/tools

I have my path set to flutter, shouldn't that enable the use of the pub package manager?

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```
PS C:\WINDOWS\system32> flutter doctor -v
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 0.1.5 at C:\Program Files\flutter
    • Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Joseph\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[!] IntelliJ IDEA Community Edition (version 2017.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[!] Connected devices
    ! No devices available
```

**Comment by zoechi** [comment]
For HTML you need the Dart SDK. Flutter doesn't include the webdev related parts.
Also ’pub` doesn't work on Flutter projects, here the `flutter` command has to be usef

**Comment by mraleph** [comment]
Flutter includes only Flutter specific bits and peaces of a custom built Dart SDK.

For Web development you need to install the full Dart SDK following these instructions: https://www.dartlang.org/install/windows

Let us know if that helps.

**Comment by ISimplifyComplexity** [comment]
Hey, I installed the dart SDK but pub is still not recognised in powershell or CMD. 

I checked and "C:\tools\dart-sdk\bin" is in my path 

I went to the directory and it does exist and the dart.exe file is present in the folder.
