### ISSUE TITLE
Error: Uncaught TypeError: Cannot read properties of undefined (reading 'load') for index.html

### ISSUE THREAD

**Issue by hawkewebtpa** [flutter/flutter#153941]
**Describe the bug**

Page sits and spins, trying to load forever, only message is in browser developer tools console see:
"Uncaught TypeError: Cannot read properties of undefined (reading 'load') for index.html
at (index):206:30"

**To Reproduce**

Upgrade from Flutter SDK 3.19 to 3.22 or 3.24, without making any code changes.
Run with newer SDK and see deprecation errors.
Follow recommendations from deprecations errors to modify code in index.html script sections for flutter servicer worker and flutter loader changes.
clean, get, build, run.
See error.

**Expected behavior**

Flutter loader deprecation issues should be addressed, and web page should load normally, not hang.

**Screenshots**

![image](https://github.com/user-attachments/assets/36e019a2-2d56-41cb-b74d-44a674c49507)

**Environment (please complete the following information):**

 - OS: This is a Flutter Web application.
 - 
Experience the error on Windows, Mac, and Linux, with multiple versions of Chrome and Firefox.

<details>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale en-US)
• Flutter version 3.24.1 on channel stable at /Users/User/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/5874a72aa4c779a02553007c47dacbefba2374dc (2 days ago), 2024-08-20 16:46:00 -0500
• Engine revision c9b9d5780d
• Dart version 3.5.1
• DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at /Users/User/Library/Android/sdk
• Platform android-34, build-tools 34.0.0
• ANDROID_HOME = /Users/User/Library/Android/sdk
• ANDROID_SDK_ROOT = /Users/User/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 15F31d
• CocoaPods version 1.15.2

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.90.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.94.0

[✓] Connected device (2 available)
• Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin • macOS 14.5 23F79 darwin-arm64
• Chrome (web) • chrome • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
• All expected network resources are available.

• No issues found!
```
</details>

**Additional context**

We upgraded from 3.19.5 to 3.24.0 (also tried with 3.22.3 but had same problem), and now upgraded to 3.24.1.

After upgrading, then  received messages during build and run about deprecation:

```
* Warning: In index.html:69: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead. See https://docs.flutter.dev/platform-integration/web/initialization for more details.

* Warning: In index.html:189: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead. See https://docs.flutter.dev/platform-integration/web/initialization for more details.
```

Tried dart pub cache clean, flutter clean, flutter pub get, flutter build web.

Still have the same error (and page sits and spins forever waiting to load with no other error messages):

We were abble to address the Service Worker error by updating syntax. Unfortunately, updating syntax for Flutter Loader, leads to this reported error and unusable app. The upgrade is working or the {{flutter_service_worker_version}} upgrade, but still broken for the FlutterLoader.load.

This line change from the previous code triggers the error

`"_flutter.FlutterLoader.load({"`

If revert that line back to deprecated syntax, then the page will load normally:

`"_flutter.loader.loadEntrypoint({"`

But then of course get the deprecation warning returns:

```
"Warning: In index.html:206: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead. See
https://docs.flutter.dev/platform-integration/web/initialization for more details."
```

Any additional suggestions what I can try on our end to address this? Anything else you need from me to help track this down? Should I create this as a new ticket issue?

Here is the whole script snippet for the web/index.html template (any syntax or other issues that might be contributing this perhaps?):

```js
<script>
    function delay(time) {
      return new Promise(resolve => setTimeout(resolve, time));
    }

    window.addEventListener('load', function (ev) {
      // Download main.dart.js      
      _flutter.FlutterLoader.load({
        serviceWorker: {
          serviceWorkerVersion: '{{flutter_service_worker_version}}',
        },
        onEntrypointLoaded: function (engineInitializer) {
          var loaderContent = document.querySelector('#loader-content');

          engineInitializer.initializeEngine().then(async function (appRunner) {
            loaderContent.style.opacity = "0";
            await delay(400);
            await appRunner.runApp();
          });
        }
      });
    });
  </script>
```

**Comment by danagbemava-nc** [comment]
Hi @hawkewebtpa, before applying the custom initialization script, can you try what is at the end of the doc to see if that helps? https://docs.flutter.dev/platform-integration/web/initialization#upgrade-an-older-project

**Comment by hawkewebtpa** [comment]
Trying the suggested approach. Will report back soon.

**Comment by hawkewebtpa** [comment]
I have tried this process (did I make any errors along the way?):

Back up the /web directory and all contents to somewhere outside of the flutter project folder, for example cp -Rf ./web ../../web.old (so that I can incrementally bring back our content and code after web template rebuild).

Remove the web template directory completely from the project.

Remove the test/widget_test.dart file.

Then from inside the flutter project directory run: flutter create . --platforms=web .

If this is the first time working on this upgrade, you probably should clear out your dart cache before going any further: dart pub cache clean (or flutter pub cache clean)f. You probably don't need to do this every time, just if you have been working on older/different SDK versions than this one (3.24.1). This will impact all of your flutter projects on your system for this (OS) login account directory structure.

Then flutter clean (run every time).

Then flutter pub get (run every time).

Then flutter build web.

I had to also copy the backed up scripts directory into the new web directory (from the root of the project directory): cp -R ../../web.old/scripts web/ and other called files used in this app.

At this point, I am now able to load the login screen, login successfully, run through the forum submissions process.

And that partially resolved in that the page loads now instead of just hanging. However I still see error in browser console: "Uncaught TypeError: Cannot read properties of undefined (reading 'load')".

![image](https://github.com/user-attachments/assets/88000754-9cc2-42f7-9821-da14f78893b3)




Also now, later in our flow of form submission, a new error occurs that isn't there before these changes: ". Message: failed to create draft ApiException 500: {"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"An error occurred while processing your request.","status":500,"detail":"Object reference not set to an instance of an object.","traceId":"|85e045bc-43fbb9e6173ab2fd.85e045bd_5de9a763_"}".   Not sure if related or not.

Perhaps a conflict, or issue with syntax as I bring back our required code changes? Perhaps wrong order?

Appreciate any further suggestions. Thanks!

index.html now looks like this (with some redactions as underlines):


<!DOCTYPE html>
<html>

<head>
  


  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">

  
  <meta name="description"
    content="With the _____ app, you can easily access your _______ and take control ______. Download your I________ and more." />
  <meta name="keywords"
    content="________" />
  <meta name="url" content="https://www.________.app" />
  

  
  

  <meta name="mobile-web-app-capable" content="yes">
  
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="__________">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  

  <link rel="icon" type="image/png" href="icons/favicon.png" />
  


  <title>____________</title>
  

  <link rel="manifest" href="manifest.json">


  
  <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.12.313/build/pdf.js" type="text/javascript"></script>
  <script src="scripts.js" defer></script>
  <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.12.313/build/pdf.worker.min.js"
    type="text/javascript"></script>
  <script type="text/javascript">
    pdfjsLib.GlobalWorkerOptions.workerSrc =
      "https://cdn.jsdelivr.net/npm/pdfjs-dist@2.12.313/build/pdf.worker.min.js";
    pdfRenderOptions = {
      // where cmaps are downloaded from
      cMapUrl: "https://cdn.jsdelivr.net/npm/pdfjs-dist@2.12.313/cmaps/",
      // The cmaps are compressed in the case
      cMapPacked: true,
      // any other options for pdfjsLib.getDocument.
      // params: {}
    };
  </script>
  





  
  <script type="text/javascript" src="scripts/pendo.js"></script>
  <script>
    // The value below is injected by flutter build, do not touch.
    // changed syntax below from null due to deprecation in Flutter SDK 3.22 or later
    // recommend using Flutter SDK 3.24.1 or later due to significant bug fixes.
    const serviceWorkerVersion = '{{flutter_service_worker_version}}';
  </script>
  


  
  <script src="flutter.js" defer></script>
  
</head>

<body>

  

  <body>
    <style>___________
    </style>

    


    <script src="flutter_bootstrap.js" async></script>


    

    <script>
      function delay(time) {
        return new Promise(resolve => setTimeout(resolve, time));
      }

      window.addEventListener('load', function (ev) {
        // Download main.dart.js
        // For _______ changed syntax below from serviceWorkerVersion due to deprecation in Flutter SDK 3.22 or later
        // recommend using Flutter SDK 3.24.1 or later due to significant bug fixes.
        // Still working on addressing Flutterloader.loadEntrypoint deprecation issue in separate ticket _________.
        // More detailed information in ______ wiki: 
        // https://_________/_______/_wiki/wikis/Documentation/Index.html-Deprecation-Warnings 
        _flutter.FlutterLoader.load({
          serviceWorker: {
            serviceWorkerVersion: '{{flutter_service_worker_version}}',
          },
          onEntrypointLoaded: function (engineInitializer) {
            var loaderContent = document.querySelector('#loader-content');

            engineInitializer.initializeEngine().then(async function (appRunner) {
              loaderContent.style.opacity = "0";
              await delay(400);
              await appRunner.runApp();
            });
          }
        });
      });
    </script>



    
  </body>

</html>


I am still delving into this, trying to remove the other third-party scripts and our code dependencies to figure out why it is still failing.

**Comment by danagbemava-nc** [comment]
> And that partially resolved in that the page loads now instead of just hanging. However I still see error in browser console: "Uncaught TypeError: Cannot read properties of undefined (reading 'load')".

At what point in your application do you get this error? 

I also noticed you have both `flutter.js` && `flutter_bootstrap.js` in your `index.html` file. It doesn't seem like the `flutter.js` import is necessary. The new index.html does not include it. You can also do the custom initialization with just the `flutter_bootstrap.js`. See https://docs.flutter.dev/platform-integration/web/initialization#customize-initialization onwards

```
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="webby">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>webby</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <script src="flutter_bootstrap.js" async></script>
</body>
</html>
```

**Comment by hawkewebtpa** [comment]
Making progress.

With 3.24.0 it previously it was happening as the index.html page loaded (which is the login prompt page).
`"Uncaught TypeError: Cannot read properties of undefined (reading 'load') for index.html
at (index):206:30"`
This was originally happening loading the index.html page and the screen would just spin.

Running the rebuilt project web steps suggested earlier in this thread, helped solve loading the front page, and shows the login page successfully. The login works, but as the user's home page / dashboard loads, as slight variation on the same error appears: 
`Uncaught TypeError: Cannot read properties of undefined (reading 'load')` 

Now the error occurs right after the login as the user's home page / dashboard loads. So it is definite progress, but clearly something still off. We are utilizing Azure ADB2C as part of our authentication infrastructure.

I pulled the line with flutter.js and just kept the flutter_bootstrap.js, I am not seeing a difference in error output from that change, but appreciate that correction. 

I am also reaching out and experimenting with disabling/isolating the other plugins like Pendo (93 instances across 13 files) to see if they are causing an interaction issue triggering this similar error message.

Any suggestions for specific things to look out for as I wade through main.dart and the other files that might be relevant to this error?

Thanks!

**Comment by ditman** [comment]
@hawkewebtpa Something that I've noticed from [your example](https://github.com/flutter/flutter/issues/153941#issuecomment-2329777922) is that the old and new JS bootstrap methods are mixed:

1. The `flutter.js` script and the `window.addEventListener('load'...` stuff
2. The `flutter_bootstrap.js` script

You should want **only the second one** with Flutter web 3.24+.

Please try to move your custom initialization code (the bits in the `load` callback) into a new file: `flutter_bootstrap.js` (should be next to `index.html`). We have some instructions and examples of the `flutter_bootstrap.js` file in the flutter docsite.

See:

* flutter.dev > [Flutter web app initialization](https://docs.flutter.dev/platform-integration/web/initialization) (With lots of information about the `flutter_bootstrap.js` file).
* https://github.com/flutter/devtools/issues/7444

**Comment by hawkewebtpa** [comment]
Have run into issue with third-party plugin acting up with this change to which is added to challenges debugging and getting response back about this. Still work on this and will report back as soon as able. Trying to clean out the interfering third-party plugins to get cleaner testing of issue here.

**Comment by hawkewebtpa** [comment]
U am still trying to weed out the third-party vendors interference with troubleshooting this (or if it is is a specific plugin that is causing this (for example pendo.js)). 
This is still unresolved, but hopefully I will have something more useful to report in the next 2-3 days.
