### ISSUE TITLE
Widget for changing layout based on rotating device

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#154]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Aug 31, 2015 at 18:19 GMT_
_Originally opened as https://github.com/flutter/engine/issues/963_

----

We should have a Widget that takes two build functions as constructor arguments and calls one or the other based on whether the aspect ratio it is to be laid out in is horizontal or vertical.

Maybe this should be a layout callback case.

Ideally this would be written is such a way as to be ready to handle iOS-style rotation animations.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Nov 03, 2015 at 05:27 GMT_

----

We have MediaQuery now.  Is that sufficient or is more work needed here?  /cc @collinjackson

**Comment by Hixie** [comment]
I'm going to close this one. If we have specific needs we should open a new bug.
