### ISSUE TITLE
TextField height changes if the errorText shows

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15400]
Put this in a dialog, and as you type in the text field, the dialog changes height.

```dart
        new Form(
          autovalidate: true,
          child: new ListBody(
            children: <Widget>[
              new TextFormField(
                decoration: const InputDecoration(
                  labelText: 'User name',
                ),
                validator: (String name) {
                  if (name.length < 2)
                    return 'User names must be alphabetic and at least three characters long.';
                  },
                ),
              ),
            ],
          ),
        ),
```

cc @HansMuller

**Comment by alidawud** [comment]
this might help you
https://stackoverflow.com/questions/50523006/flutter-increase-height-of-textformfield

**Comment by SinaSeirafi** [comment]
Put the TextFormField inside a Container, and give it a certain height.
That should prevent vertical moving.

**Comment by babenkovladimir** [comment]
I used SizedBox. I set a specific height, which was enough for the height not to jump.

**Comment by justinmc** [comment]
Here are some screenshots showing my understanding of the problem:

![flutter_02](https://user-images.githubusercontent.com/389558/54789181-da671880-4bee-11e9-8e94-2aebddbe3e49.png)
![flutter_01](https://user-images.githubusercontent.com/389558/54789180-da671880-4bee-11e9-8980-b1dc472670b7.png)

When the input has an error message, it is considered to be taller than without it, so the parent widget increases its height to accommodate it.  That can definitely be pretty jarring for the developer in cases like this dialog or maybe even with a column of text fields.

I'm going over some solutions and I'll post back.

**Comment by justinmc** [comment]
The two workarounds for this problem are:

1. Wrap the TextFormField in a fixed height parent.

```dart
SizedBox(
  height: 80,
  child: TextFormField(
    validator: myValidator,
  ),
),
```

2. Give a `helperText` of a single space.
```dart
TextFormField(
  decoration: const InputDecoration(
    helperText: ' ',
  ),
  validator: myValidator,
),
```

The referenced PR just adds an explanation of these workarounds to the documentation.  I think this is better than changing any behavior.  We want to avoid breaking changes.  Also, I can see a situation where users want the existing behavior so that they can tightly space their inputs.

**Comment by AyushmanChatterjee** [comment]
> The two workarounds for this problem are:
> 
> 1. Wrap the TextFormField in a fixed height parent.
> 
> ```dart
> SizedBox(
>   height: 80,
>   child: TextFormField(
>     validator: myValidator,
>   ),
> ),
> ```
> 
> 1. Give a `helperText` of a single space.
> 
> ```dart
> TextFormField(
>   decoration: const InputDecoration(
>     helperText: ' ',
>   ),
>   validator: myValidator,
> ),
> ```
> 
> The referenced PR just adds an explanation of these workarounds to the documentation. I think this is better than changing any behavior. We want to avoid breaking changes. Also, I can see a situation where users want the existing behavior so that they can tightly space their inputs.

**Comment by AyushmanChatterjee** [comment]
Thank you so much! This was driving me insane as I am using two textformfields side by side in a row and the validation errorText kept breaking up the alignment of the form fields. Using an empty helperText was a simple solution to the problem.

**Comment by ksankumar** [comment]
> The two workarounds for this problem are:
> 
> 1. Wrap the TextFormField in a fixed height parent.
> 
> ```dart
> SizedBox(
>   height: 80,
>   child: TextFormField(
>     validator: myValidator,
>   ),
> ),
> ```
> 
> 1. Give a `helperText` of a single space.
> 
> ```dart
> TextFormField(
>   decoration: const InputDecoration(
>     helperText: ' ',
>   ),
>   validator: myValidator,
> ),
> ```
> 
> The referenced PR just adds an explanation of these workarounds to the documentation. I think this is better than changing any behavior. We want to avoid breaking changes. Also, I can see a situation where users want the existing behavior so that they can tightly space their inputs.

2nd solution makes awesome solution

**Comment by jacobokoenig** [comment]
This is still an issue for me, even with a sizedbox or container, and a helper text! Can't prevent the text field from becoming smaller!

`Container(
          height: 32,
          child: TextFormField(
            decoration: InputDecoration(
              helperText: '  ',
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(16),
                borderSide: BorderSide(
                  color: Colors.white,
                ),
              ),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(16),
                borderSide: BorderSide(
                  color: Colors.white,
                ),
              ),
            ),
            validator: validator,
          ),
        ),`

**Comment by justinmc** [comment]
@jacobokoenig I don't think I see the TextFormField becoming smaller in your example.  I'm on the master channel.  I changed your code by adding a `color` to the Container so that I could see how tall it is, and I also added `autovalidate` to your TextFormField so that the error message shows immediately.

![flutter_24](https://user-images.githubusercontent.com/389558/69097104-b45a7800-0a0a-11ea-8753-1fca7485ad21.png)
![flutter_25](https://user-images.githubusercontent.com/389558/69097105-b45a7800-0a0a-11ea-857c-24af78085f5b.png)

Neither the border of the TextFormField or the Container in the background change size after the error appears.

**Comment by camsethsum** [comment]
> This is still an issue for me, even with a sizedbox or container, and a helper text! Can't prevent the text field from becoming smaller!
> 
> ```
> Container(
>           height: 32,
>           child: TextFormField(
>             decoration: InputDecoration(
>               helperText: '  ',
>               enabledBorder: OutlineInputBorder(
>                 borderRadius: BorderRadius.circular(16),
>                 borderSide: BorderSide(
>                   color: Colors.white,
>                 ),
>               ),
>               border: OutlineInputBorder(
>                 borderRadius: BorderRadius.circular(16),
>                 borderSide: BorderSide(
>                   color: Colors.white,
>                 ),
>               ),
>             ),
>             validator: validator,
>           ),
>         ),
> ```

I also encountered the same problem, the workaround that I made was make the fontsize of your errorText and helperText the same so that they will take the space.

**Comment by psygo** [comment]
Taken from [this SO answer](https://stackoverflow.com/a/60695612/4756173) and the new issue #52634:

<hr>

There's another alternative to adding extra, permanent padding to cover the `errorText` &mdash; which would probably mess up many designer's original project.

You could create a modified version of the [source's `TextFormField`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_form_field.dart).

To achieve just that, you can:

1. Copy-paste all of the content in the [source's `TextFormField`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_form_field.dart).
1. Rename your custom `TextFormField` just so you avoid naming conflicts with the original. 
    - You should probably also rename the internal state class.
    - In VS Code, you can use <kbd>Ctrl</kbd> + <kbd>H</kbd> to replace `TextFormField` for, say, `TextFormFieldWithErrorTextOption`.
1. Add another parameter to the `TextFormField`'s constructor (below [this line](https://github.com/flutter/flutter/blob/1ca4815035e6aa14831d8148062c732be3a458c4/packages/flutter/lib/src/material/text_form_field.dart#L175)), say, `errorTextPresent`:
    ```dart
    // `true` is the current default, i.e., showing the `errorText`
    bool errorTextPresent = true 
    ```
1. Change the [decoration's initialization](https://github.com/flutter/flutter/blob/1ca4815035e6aa14831d8148062c732be3a458c4/packages/flutter/lib/src/material/text_form_field.dart#L220) for the internal `TextField`:
    1. From:
        ```dart
        decoration: effectiveDecoration.copyWith(field.errorText)
        ```
    1. To:
        ```dart
        decoration: effectiveDecoration.copyWith(
            errorText: errorTextPresent ? field.errorText : null)
        ```
1. Then, you can use your new `TextFormField` similarly to how you use any `TextFormField`:
    ```dart
    TextFormFieldWithErrorTextOption(
      errorTextPresent: false, // `false` will disable the `errorText`
      ...
    ),
    ```

**Comment by ooanishoo** [comment]
https://stackoverflow.com/a/60208333/5392889

try this answer. Worked really well for me

**Comment by TheAlphamerc** [comment]
> https://stackoverflow.com/a/60208333/5392889
> 
> try this answer. Worked really well for me

@ooanishoo  It will probably help if we don't want to show the field validation message.
But  if we want to show error message then https://github.com/flutter/flutter/issues/15400#issuecomment-475773473 really helpful .
