### ISSUE TITLE
XMPP and socket.io packages

### ISSUE THREAD

**Issue by developerandre** [flutter/flutter#15407]
Hello!
Does anyone know of a package to use xmpp in flutter and another for socket.io?

**Comment by ArcticZeroo** [comment]
Check out https://github.com/rikulo/socket.io-dart ? You should be able to hook that up to setState in a StatefulWidget to provide updates to stuff

**Comment by Hixie** [comment]
Please see pub.dartlang.org. If there's nothing there, then I expect there's no current package for this.
