### ISSUE TITLE
[iOS] PageView slide animation jerky appears randomly

### ISSUE THREAD

**Issue by DebugDruid510** [flutter/flutter#154045]
### Steps to reproduce

1. Occasional jerky when swiping page left or right
2. jerky only in Release or Profile mode (disconnected from Devtool)
3. No jerky when turning on iPhone's screen recording feature
4. This jerky doesn't happen every time. It's always random
5. Device: iPhone 15, OS Version: 17.6.1

### Expected results

Smooth sliding animation

### Actual results

Slide animation appears random jerky

### Code sample

<details open><summary>
Code
</summary>

Github: https://github.com/ChenwuApp/flutter_jerky

```dart
import 'package:flutter/material.dart';

class PageViewTest extends StatelessWidget {
  const PageViewTest({super.key});

  static const colorList = [Colors.red, Colors.yellow, Colors.grey];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: PageView.builder(
            allowImplicitScrolling: true,
            itemBuilder: (BuildContext context, int index) {
              return Center(
                child: Column(
                  children: [
                    Text("Current Page: $index"),
                    Expanded(
                        child: Container(
                      color: colorList[index % 3],
                    ))
                  ],
                ),
              );
            }));
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>
When Page 0 slides to Page 1, jerky appears.

https://github.com/user-attachments/assets/62c8f39f-61c0-4511-b6b2-ea8491727d29

</summary>

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.0 on channel stable at /Users/rain/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/rain/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone (mobile)                 • <Removed>                 • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.84

```

</details>

**Comment by ChenwuApp** [comment]
> Does the issue only appear if you set allowImplicitScrolling as true in the sample code?

The purpose of setting allowImplicitScrolling was to fix jank, but it turns out that it doesn't help, so jank has nothing to do with allowImplicitScrolling

> Do you notice any jank from Devtools when the issue occurs?

Yeah, there's a lot of slow Raster going on.

Here is the Trace file:
https://github.com/ChenwuApp/flutter_jerky/blob/main/dart_devtools_2024-08-26_21_35_54.018.json

**Comment by VladRoscaDev** [comment]
@ChenwuApp consider adding a final PageController _controller = PageController(); and try to log its events to get a good feeling if there are any issues. 
I also would like to see if there is only a specific physic that triggers the janky feeling.

**Comment by ChenwuApp** [comment]
@VladRoscaDev 
> consider adding a final PageController _controller = PageController(); 

In my app, I was using PageController, but I removed it in this demo.


> and try to log its events to get a good feeling if there are any issues.

What events need to be recorded?


>  I also would like to see if there is only a specific physic that triggers the janky feeling.

I think there may be more than just this physical, because there are also Listview, Page routing transitions where this jank occurs

**Comment by huycozy** [comment]
@ChenwuApp I checked this on my device `Pixel 7, Android 14` and `iPhone 7, iOS 15.8` but couldn't see the issue, no jank appears from Devtools. This could be a device-specific issue. 

Can you check if this is an Impeller issue? (by disabling Impeller and observe it). If it's an Impeller issue, can you check this on Flutter master channel as well? 

Please also check this on Android if you have any device as well. Thank you!

**Comment by ChenwuApp** [comment]
@huycozy 
I checked the iPhone xr (iOS 14.7.1) and Redmi (Android 13) and neither of them had the jank problem.

I disabled Impeller and the jank issue persists.

Here are the steps I took to summarize the easier way to reproduce the jank (iPhone 15)
1. launch the demo app and swipe left and right on some random pages
2. go back to the home screen (don't close the demo app), use another app, or turn off the screen
3. after some time, open the demo app and swipe left and right randomly on some pages

This issue is not that easy to appear, I have tested the above process 20 times in the last 12 hours and jank appeared 3 times.

**Comment by huycozy** [comment]
Thanks for the update but I still can't reproduce this issue on my end. It would be helpful if you could find consistent steps for this.

Can you also try switching to Flutter master channel and retry checking this?

**Comment by ChenwuApp** [comment]
@huycozy 
I'm testing this jank issue in the master channel and so far I'm not finding the same slow raster issue anymore.

But found other jank issues.

On iPhone 15 there is slow Paint causing jank:
https://github.com/ChenwuApp/flutter_jerky/blob/main/dart_devtools_2024-08-28_15_27_46.000.json

On iPhone XR there is slow Layout causing jank:
https://github.com/ChenwuApp/flutter_jerky/blob/main/dart_devtools_2024-08-28_22_00_26.593.json

Both of these janks have the same behavior, that is, the sliding animation disappears.

Also, this jank appears randomly, and the reproduction is referenced above.

```
Flutter 3.25.0-1.0.pre.159 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3379460596 (9 hours ago) • 2024-08-27 22:23:18 -0700
Engine • revision 8d248aead3
Tools • Dart 3.6.0 (build 3.6.0-175.0.dev) • DevTools 2.39.0-dev.15
```

**Comment by huycozy** [comment]
Thanks for checking it. Looks like the issue only appears on iOS platform. With those timeline trace JSON files, that may be helpful to investigate further.

**Comment by ChenwuApp** [comment]
@huycozy 
Thank you for your help and feel free to contact me if you need any additional info.

**Comment by jmagman** [comment]
team-engine might have a better idea how to profile this (there are no platform views)

**Comment by DebugDruid510** [comment]
This issue is not reproducible in 3.27.0

**Comment by DebugDruid510** [comment]
This issue is not reproducible in 3.27.0
