### ISSUE TITLE
Flutter Impeller [إقتراح] 

### ISSUE THREAD

**Issue by 1999ali1999** [flutter/flutter#154056]
### Use case

The optional preference for Opengl and Vulkan rather than my engine preference for Impeller so that I can choose one of them assumingly if I prefer and choose openGL by default and a system that does not only support openGL here will return the engine to Vulkan and also reverse or opt for Vulkan by default.
The reason for this proposal is my experience of Impeller and after experimenting on many of its android 10 and above devices many of which performed badly with Vulkan unfortunately and previously performed an application before upgrading the project was better.

### Proposal

have to be provided by Flutter directly

**Comment by jonahwilliams** [comment]
I'm not really sure what you are asking for.

Impeller will be opt out for a period of time like we did with the iOS backend. The goal is collect bug reports/performance issues.
