### ISSUE TITLE
Get Started  - Flutter: Command not found

### ISSUE THREAD

**Issue by xxjeep** [flutter/flutter#15408]
## Steps to Reproduce

I'm pretty sure this is a silly issue but I've had not luck googling. I'm just going over the Get Started and it looks like either my `$PATH` variable is messed up or it's something with `zsh`? I swapped shells via `chsh -s /bin/bash` but get the same `command not found: flutter` error.

```
➜  flutter git:(beta) PATH=`pwd`/flutter/bin:$PATH
➜  flutter git:(beta) echo $PATH
/Users/justin/Documents/code/clones/flutter/flutter/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
➜  flutter git:(beta) flutter doctor
zsh: command not found: flutter
```
## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

Can't run so nothing to post...

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by saviour123** [comment]
After cloning the repo, **don't cd ./flutter** before running the commad. 
the `pwd` represent the current directory where you were before cloning the repo.
The full command is: 

```export PATH=`pwd`/flutter/bin:$PATH```

You can make life easier by adding it to your **bashrc or zshrc**

>
 ```
 Move flutter to home dir

$ mv flutter ~

Add the path to your ~/zshrc
path+=('/home/username/flutter/bin')
export PATH
```
* Source it `source ~/.zshrc`
>

**Comment by patelkrunal78** [comment]
You need to correctly set up your flutter path.

from here https://flutter.io/setup-macos/#update-your-path

Determine the directory where you placed the Flutter SDK. You will need this in Step 3.
Open (or create) $HOME/.bash_profile. You can do that by using terminal text editor by going in terminal and typing nano ~/.bash_profile
Add the following line and change [PATH_TO_FLUTTER_GIT_DIRECTORY] to be the path where you cloned Flutter’s git repo:
export PATH=[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin:$PATH

**Comment by santiagorr207** [comment]
Buenos dias , actualice el fluttey me pasa el mismo error.Ç
`bash: flutter: command not found`

**Comment by Allan-Nava** [comment]
> Buenos dias , actualice el fluttey me pasa el mismo error.Ç
> `bash: flutter: command not found`

+1
