### ISSUE TITLE
Issue when using sharedPreferences plugin in iOS builds

### ISSUE THREAD

**Issue by stoichoandreev** [flutter/flutter#15409]
## Steps to Reproduce

I have just created a new flutter application in Intellij and I chose to use Kotlin for the Android part and Swift for the iOS part. I also included shared preferences plugin ver.0.4.0 in the project. I run my application on Android and everything works fine, but on iOS I get error and the build fails. I am not sure what is wrong but it seems that the import of the shared_preferences plugin in iOS file GeneratedPluginRegistrant.m is wrong or the import can't be found, which means that the plugin is not setup correctly. I don't know if I have to do something explicitly on iOS to run the shared preferences plugin or maybe the usage of Swift wasn't good idea?

## Logs

`flutter run` returns: 
```
Launching lib/main.dart on iPhone 6s in debug mode...
Running Xcode clean...                                       0.9s
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    4.2s
 └─Compiling, linking and signing...                  0.7s
Xcode build done                                             6.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/sniper/Development/Flutter/guidlly/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'shared_preferences/SharedPreferencesPlugin.h' file not found
    #import <shared_preferences/SharedPreferencesPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone 6s.
```
## Flutter Doctor

Flutter doctor returns: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.2.0, on Mac OS X 10.13.3 17D102, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[✓] Connected devices (1 available)

• No issues found!
```

BTW: I had to do something in XCode about change Swift3 interface with Default, which was fixed, but after that I got this error and I can't make iOS builds.

**Comment by AlexeySemigradsky** [comment]
I have this issue too.

**Comment by stoichoandreev** [comment]
I guess this issue here : https://github.com/flutter/flutter/issues/15168 is similar, but I still can't solve mine

**Comment by theEpicality** [comment]
@stoichoandreev Yeah, several people are having this problem. Even the workaround that was mentioned in issue #15168 only works for debugging.

**Comment by stoichoandreev** [comment]
Well @theEpicality thanks for the update. I saw that your issue is still open, so I guess we should just wait for the flutter team to solve it or help us somehow.

**Comment by jerrywell** [comment]
Hi,
I just tried the debug and release build and there is some rules for this workaround:

folder to add .h file
debugging on simulator => ios/Debug-iphonesimulator
debugging on iOS => ios/Debug-iphoneos
release on iOS => ios/Release-iphoneos

BTW, I can build my project in all modes with many 3rd lib using this workaround.

**Comment by zoechi** [comment]
I think it's a dup of #15099

**Comment by dustin-graham** [comment]
I'm having this same issue. I'm looking around for the plugin files and I can't find them anywhere. This seems like a tooling error of some kind.

**Comment by curtiscovington** [comment]
Same issue here.

**Comment by xsokev** [comment]
I was able to find a slight difference between the Podfile in a project I was working on a couple of weeks ago and my current project where I am experiencing this issue. After replacing the new Podfile code with the old, the problem went away with a `pod install` command. 
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf Pods/.symlinks')
  system('mkdir -p Pods/.symlinks/flutter')
  system('mkdir -p Pods/.symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('Pods', '.symlinks', 'flutter', File.basename(p[:path]))
      File.symlink(p[:path], symlink)
      pod 'Flutter', :path => symlink
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('Pods', '.symlinks', 'plugins', File.basename(p[:path]))
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/7463
    target.headers_build_phase.files.each do |file|
      file.settings = { 'ATTRIBUTES' => ['Public'] }
    end
  end
end
```

**Comment by mudoY** [comment]
I have the same issue too, mark

**Comment by curtiscovington** [comment]
I fixed my problem by upgrading my version of ruby.

**Comment by xsokev** [comment]
@curtiscovington which version of Ruby did you upgrade to?

**Comment by mudoY** [comment]
I fixed it by upgrading my pod version from 1.1.0 to 1.5.2, and I think it is the right way to fix it.

**Comment by cyanglaz** [comment]
> I fixed it by upgrading my pod version from 1.1.0 to 1.5.2, and I think it is the right way to fix it.

@stoichoandreev Have you tried with this suggestion and is the issue fixed? It seems works for me and I have cocoapod version 1.5.3

**Comment by RohanSakhale** [comment]
I am facing the same issue again
```
 /Labs/Workspace/Flutter/camp-flutter/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error:
    'shared_preferences/SharedPreferencesPlugin.h' file not found
    #import <shared_preferences/SharedPreferencesPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

## Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!
```

## Additional Information

We are using flavors and schemes for iOS build and using below command to run applications

```
flutter run --flavor abcd --target lib/main/abcd_main.dart
```

**Comment by hedrondantas** [comment]
Solved with this https://github.com/flutter/flutter/issues/42745#issuecomment-542638225

**Comment by wafahas** [comment]
i have problem Module 'shared_preferences' not found
Xcode's output:
↳
    /Users/wafaaabudawod/AndroidStudioProjects/shopping55/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'shared_preferences' not found
    @import shared_preferences;
