### ISSUE TITLE
Transition between NavigationRail and NavigationDrawer

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#154022]
### Use case

Material 3 showcases a [UI pattern](https://m3.material.io/components/navigation-drawer/guidelines#f01432c1-e709-4865-9394-b78cf7adcbff) where the navigation drawer can transition into a navigation rail and back. Flutter seems completely void of such support.

### Proposal

https://github.com/user-attachments/assets/98464858-8b04-4d85-a85f-ecb7f7e56cd7

**Comment by Piinks** [comment]
I am going to close this as a duplicate of https://github.com/flutter/flutter/issues/124111. Thank you for contributing!
