### ISSUE TITLE
Global Key Event Listening | Impact of RawKeyboard Deprecation

### ISSUE THREAD

**Issue by Paul-creator** [flutter/flutter#154141]
### Use case

Previously, I was able to listen to keyboard events using RawKeyboard.instance.addListener(_handleKey); even when those events were being handled by other widgets at the same time. This was very useful because it allowed me to intercept key combinations like Escape (for closing a popup) or Cmd+S (for saving) across the entire app, even when a text field was focused.

However, with the introduction of the HardwareKeyboard, this behavior is no longer possible. The HardwareKeyboard only triggers events when its associated focus node is focused, making it difficult to handle global keyboard shortcuts. Now, I have to manage focus nodes for every text field in the app and manually forward key events to my global listener, which is cumbersome and prone to errors.

Below is an example of how I used to implement this:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class GlobalKeyListener extends StatefulWidget {
  final Widget child;
  final Function(RawKeyEvent) onKey;

  const GlobalKeyListener({Key? key, required this.child, required this.onKey})
      : super(key: key);

  @override
  _GlobalKeyListenerState createState() => _GlobalKeyListenerState();
}

class _GlobalKeyListenerState extends State<GlobalKeyListener> {
  @override
  void initState() {
    super.initState();
    RawKeyboard.instance.addListener(_handleKey);
  }

  @override
  void dispose() {
    RawKeyboard.instance.removeListener(_handleKey);
    super.dispose();
  }

  void _handleKey(RawKeyEvent event) {
    widget.onKey(event);
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
```
I believe this change increases the complexity for many apps, as developers now need to handle focus nodes explicitly and manually forward events, which feels like a workaround and could introduce bugs. I would appreciate if there could be a way to restore the previous behavior or provide a simpler method to globally listen to keyboard events.

### Proposal

I am pretty sure, that this has to be provided by flutter directly.

**Comment by bleroux** [comment]
https://api.flutter.dev/flutter/services/HardwareKeyboard/addHandler.html might be what your are looking for.

From https://api.flutter.dev/flutter/services/HardwareKeyboard-class.html documentation, `addHandler` is not related to focus:

```
To stay notified whenever keys are pressed, held, or released, add a handler with addHandler. 
To only be notified when a specific part of the app is focused, use a Focus widget's onFocusChanged attribute.
```

**Comment by danagbemava-nc** [comment]
Hi @Paul-creator, kindly see https://github.com/flutter/flutter/issues/154141#issuecomment-2311759173 to see if it solves your issue

**Comment by Paul-creator** [comment]
> https://api.flutter.dev/flutter/services/HardwareKeyboard/addHandler.html might be what your are looking for.
> 
> From https://api.flutter.dev/flutter/services/HardwareKeyboard-class.html documentation, `addHandler` is not related to focus:
> 
> ```
> To stay notified whenever keys are pressed, held, or released, add a handler with addHandler. 
> To only be notified when a specific part of the app is focused, use a Focus widget's onFocusChanged attribute.
> ```

Thank very much, you that works.
