### ISSUE TITLE
VideoPlayer loses reference when the app stays in the background for a long time

### ISSUE THREAD

**Issue by Henriquek47** [flutter/flutter#154159]
### What package does this bug report belong to?

video_player

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
video_player:
    dependency: "direct dev"
    description:
      name: video_player
      sha256: e30df0d226c4ef82e2c150ebf6834b3522cf3f654d8e2f9419d376cdc071425d
      url: "https://pub.dev"
    source: hosted
    version: "2.9.1"
```

</details>

### Steps to reproduce

1st step: Initialize the videoController with a file using VideoPlayerController.file().

2nd step: Check if the video has loaded.

3rd step: Leave the app in the background for 3-5 minutes.

4th step: Return to the app, and the video loses its reference.

### Expected results

When returning to the app, the videoController loses the reference to the video it was pointing to

### Actual results

Apparently, the videoController loses its reference (I think due to garbage collection).

### Code sample

<details open><summary>Code sample</summary>

```dart
late VideoPlayerController videoPlayerController;

  @override
  void initState() {
    File file = File(
        '/data/user/0/path/cache/442decbe-9c29-4e0c-86ef-7e4159d864d7/1000042017.mp4');
    videoPlayerController = VideoPlayerController.file(file,);
    videoPlayerController.initialize();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        height: double.maxFinite,
        width: double.maxFinite,
        color: Colors.blue,
        child: VideoPlayer(videoPlayerController),
      ),
    );
```

**Comment by danagbemava-nc** [comment]
Hi @Henriquek47, does this only happen when you use the file constructor? Do you get any errors when the reference is lost?

**Comment by Henriquek47** [comment]
@danagbemava-nc the error output inside videoPlayerController.value.errorDescription is:  "Video player had error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001E, -1, null, [864, 1920, 51.236576, ColorInfo(BT601, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES"

I haven't tested it in other formats, only in .file

**Comment by danagbemava-nc** [comment]
Hi @Henriquek47, please provide the full output of `flutter run -v` that captures the issue properly. 

Thank you

**Comment by Henriquek47** [comment]
@danagbemava-nc  Here is the error that appears in the terminal when I exit and return to the app (as I explained in the issue)

[+1655 ms] D/BufferPoolAccessor2.0(24198): bufferpool2 0xb40000753db6ede8 : 5(40960 size) total buffers - 1(8192 size) used buffers - 22/27 (recycle/alloc) - 9/27
(fetch/transfer)
[+1819 ms] D/BufferPoolAccessor2.0(24198): bufferpool2 0xb40000753db75a98 : 5(15667200 size) total buffers - 4(12533760 size) used buffers - 18/24 (recycle/alloc)
- 7/25 (fetch/transfer)
[   +1 ms] D/BufferPoolAccessor2.0(24198): evictor expired: 1, evicted: 1
[+1998 ms] D/BufferPoolAccessor2.0(24198): evictor expired: 1, evicted: 1
[+25258 ms] D/Surface (24198): Surface::disconnect
[        ] D/BufferQueueProducer(24198): [SurfaceView[com.example.editor_minitok/com.example.editor_minitok.MainActivity]#1(BLAST
Consumer)1](id:5e8600000001,api:1,p:24198,c:24198) disconnect: api 1
[        ] D/Surface (24198): Surface::disconnect
[        ] D/BufferQueueProducer(24198): [SurfaceView[com.example.editor_minitok/com.example.editor_minitok.MainActivity]#1(BLAST
Consumer)1](id:5e8600000001,api:0,p:-1,c:24198) disconnect: api -1
[        ] D/Surface (24198): Surface::disconnect
[        ] D/BufferQueueProducer(24198): [VRI[MainActivity]#0(BLAST Consumer)0](id:5e8600000000,api:1,p:24198,c:24198) disconnect: api 1
[+70698 ms] I/OpenGLRenderer(24198): setGrContext validptr-->nullptr
[+45517 ms] D/CCodec  (24198): Component "c2.qti.avc.decoder" returned error: 0xffffffff
[   +2 ms] E/MediaCodec(24198): Codec reported err 0x80000000/UNKNOWN_ERROR, actionCode 0, while in state 6/STARTED
[   +2 ms] D/MediaCodec(24198): flushMediametrics
[   +1 ms] D/BufferPoolAccessor2.0(24198): bufferpool2 0xb40000753db6ede8 : 0(0 size) total buffers - 0(0 size) used buffers - 22/27 (recycle/alloc) - 10/27      
(fetch/transfer)
[        ] D/SurfaceUtils(24198): disconnecting from surface 0xb4000074edb7f1a0, reason disconnectFromSurface
[        ] D/Surface (24198): Surface::disconnect
[        ] D/BufferQueueProducer(24198): [SurfaceTexture-0-24198-0](id:5e8600000002,api:3,p:24198,c:24198) disconnect: api 3
[        ] E/BufferQueueProducer(24198): [SurfaceTexture-0-24198-0](id:5e8600000002,api:0,p:-1,c:24198) cancelBuffer: BufferQueue has no connected producer       
[        ] E/BufferQueueProducer(24198): [SurfaceTexture-0-24198-0](id:5e8600000002,api:0,p:-1,c:24198) cancelBuffer: BufferQueue has no connected producer            
[  +20 ms] D/VRI[MainActivity](24198): update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
[        ] D/VRI[MainActivity](24198):   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
[        ] D/VRI[MainActivity](24198):   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST FIT_INSETS_CONTROLLED
[        ] D/VRI[MainActivity](24198):   vsysui=LAYOUT_STABLE LAYOUT_FULLSCREEN
[        ] D/VRI[MainActivity](24198):   bhv=DEFAULT
[        ] D/VRI[MainActivity](24198):   fitSides=} by setLayoutParams
[  +13 ms] I/OpenGLRenderer(24198): setGrContext nullptr-->validptr
[        ] E/OpenGLRenderer(24198): Unable to match the desired swap behavior.
[ +948 ms] E/MediaCodecVideoRenderer(24198): Video codec error
[   +1 ms] E/MediaCodecVideoRenderer(24198):   android.media.MediaCodec$CodecException: Error 0x80000000
[        ] E/ExoPlayerImplInternal(24198): Playback error
[        ] E/ExoPlayerImplInternal(24198):   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, 
video/avc, avc1.64001E, -1, null, [864, 1920, 51.236576, ColorInfo(BT601, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]),
format_supported=YES
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
[        ] E/ExoPlayerImplInternal(24198):       at android.os.Handler.dispatchMessage(Handler.java:107)
[        ] E/ExoPlayerImplInternal(24198):       at android.os.Looper.loopOnce(Looper.java:242)
[        ] E/ExoPlayerImplInternal(24198):       at android.os.Looper.loop(Looper.java:362)
[        ] E/ExoPlayerImplInternal(24198):       at android.os.HandlerThread.run(HandlerThread.java:85)
[        ] E/ExoPlayerImplInternal(24198):   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder       
[        ] E/ExoPlayerImplInternal(24198):       at
androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
[        ] E/ExoPlayerImplInternal(24198):       ... 4 more
[        ] E/ExoPlayerImplInternal(24198):   Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
[        ] I/MediaCodec(24198): (0xb40000730db58e90) flush
[        ] E/MediaCodec(24198): flush() is valid only at Executing states; currently at Released state
[        ] E/ExoPlayerImplInternal(24198): Disable failed.
[        ] E/ExoPlayerImplInternal(24198):   java.lang.IllegalStateException: flush() is valid only at Executing states; currently at Released state
[        ] E/ExoPlayerImplInternal(24198):   
[        ] E/ExoPlayerImplInternal(24198):       at android.media.MediaCodec.native_flush(Native Method)
[        ] E/ExoPlayerImplInternal(24198):       at android.media.MediaCodec.flush(MediaCodec.java:2523)
[        ] E/ExoPlayerImplInternal(24198):       at
androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:247)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:960)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:953)      
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:780)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:794)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1846)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1566)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1523)
[        ] E/ExoPlayerImplInternal(24198):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:686)
[        ] E/ExoPlayerImplInternal(24198):       at android.os.Handler.dispatchMessage(Handler.java:107)
[        ] E/ExoPlayerImplInternal(24198):       at android.os.Looper.loopOnce(Looper.java:242)
[        ] E/ExoPlayerImplInternal(24198):       at android.os.Looper.loop(Looper.java:362)
[        ] E/ExoPlayerImplInternal(24198):       at android.os.HandlerThread.run(HandlerThread.java:85)
[        ] I/MediaCodec(24198): (0xb40000730dbc1350) flush
[        ] D/CCodecBuffers(24198): [c2.android.aac.decoder#236:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
[        ] D/CCodecBuffers(24198): [c2.android.aac.decoder#236:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
[        ] D/CCodecBuffers(24198): [c2.android.aac.decoder#236:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 2
[        ] D/CCodecBuffers(24198): [c2.android.aac.decoder#236:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 3
[        ] I/MediaCodec(24198): (0xb40000730dbc1350) start
[        ] D/MediaCodec(24198): keep callback message for reclaim
[        ] I/CCodecConfig(24198): query failed after returning 20 values (BAD_INDEX)
[        ] W/Codec2Client(24198): query -- param skipped: index = 1342179345.
[   +3 ms] W/Codec2Client(24198): query -- param skipped: index = 2415921170.
[        ] W/Codec2Client(24198): query -- param skipped: index = 1610614798.
[        ] D/CCodecBufferChannel(24198): [c2.android.aac.decoder#236] start: updating output delay 2
[        ] D/CCodecBufferChannel(24198): [c2.android.aac.decoder#236] MediaCodec discarded an unknown buffer
[        ] D/CCodecBufferChannel(24198): [c2.android.aac.decoder#236] MediaCodec discarded an unknown buffer
[        ] D/CCodecBufferChannel(24198): [c2.android.aac.decoder#236] MediaCodec discarded an unknown buffer
[        ] D/CCodecBufferChannel(24198): [c2.android.aac.decoder#236] MediaCodec discarded an unknown buffer
[        ] E/BufferQueueProducer(24198): [SurfaceTexture-0-24198-0](id:5e8600000002,api:0,p:-1,c:24198) detachBuffer: BufferQueue has no connected producer       
[   +1 ms] D/BufferPoolAccessor2.0(24198): bufferpool2 0xb40000753db75a98 : 4(12533760 size) total buffers - 4(12533760 size) used buffers - 18/24 (recycle/alloc)
- 7/25 (fetch/transfer)
[        ] D/MediaCodec(24198): flushMediametrics
[        ] D/MediaCodec(24198): flushMediametrics
[        ] W/MediaCodec(24198): no metrics handle found
[        ] I/hw-BpHwBinder(24198): onLastStrongRef automatically unlinking death recipients
[        ] D/BufferPoolAccessor2.0(24198): Destruction - bufferpool2 0xb40000753db6ede8 cached: 0/0M, 0/0% in use; allocs: 32, 69% recycled; transfers: 27, 63%
unfetched
[        ] I/hw-BpHwBinder(24198): onLastStrongRef automatically unlinking death recipients
[        ] D/MediaCodec(24198): flushMediametrics
[        ] D/MediaCodec(24198): flushMediametrics
[        ] W/MediaCodec(24198): no metrics handle found
[+5963 ms] D/BufferPoolAccessor2.0(24198): bufferpool2 0xb40000753db75a98 : 0(0 size) total buffers - 0(0 size) used buffers - 18/24 (recycle/alloc) - 7/25
(fetch/transfer)
[   +1 ms] D/BufferPoolAccessor2.0(24198): evictor expired: 2, evicted: 1

**Comment by danagbemava-nc** [comment]
Hi @Henriquek47, have you tried handling the appLifecycle events to see if this resolves the issue? For example, you pause the video when the app gets backgrounded and then try to resume the video when the app is resumed

**Comment by Henriquek47** [comment]
@danagbemava-nc  In the example I provided, I’m only initializing the controller without altering the video state, such as playing or pausing. I'd like to know if there’s a way to handle this error so that when it occurs, I can work around it and reinitialize the videoPlayerController

**Comment by Henriquek47** [comment]
The error occurs regardless of whether I play or pause the video. The problem is that when I return to the app, I no longer have access to the video in the videoPlayerController.

**Comment by danagbemava-nc** [comment]
Hi @Henriquek47,  I just tested with the big buck bunny video, I put the app in the background for about 5 minutes and the screen flashed a bit but the video resumed from where it was when I resumed the app without needing to manually resume the video. 

Does this match your experience?

**Comment by danagbemava-nc** [comment]
Hi @Henriquek47, I just tested on my Pixel 7 running android 14 and it appears to work as expected. I see the behavior I described in https://github.com/flutter/flutter/issues/154159#issuecomment-2320287801
