### ISSUE TITLE
Chinese characters show on wrong font weight on ColorOS with Flutter 3.24.x

### ISSUE THREAD

**Issue by VillagerTom** [flutter/flutter#154166]
### Steps to reproduce

1. Prepare an Android phone running ColorOS.
2. Change Flutter version to 3.22.3 and create a project with code below in `main.dart`.
3. Run the project with the ColorOS phone.
4. Change Flutter version to the latest stable(3.24.x).
5. Rerun the project.

### Expected results

Chinese characters show normally in all font weights.

### Actual results

We can see in the pictures below that with Flutter 3.24.x, Chinese characters in weight w300~w500 show on the wrong weight(w300 same as English w200, w400 & w500 same as English w300). But with Flutter 3.22.3, everything shows correct.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Padding(
        padding: EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              '字重.w100 - Thin',
              style: TextStyle(fontWeight: FontWeight.w100, fontSize: 18),
            ),
            SizedBox(height: 10),
            Text(
              '字重.w200 - Extra Light',
              style: TextStyle(fontWeight: FontWeight.w200, fontSize: 18),
            ),
            SizedBox(height: 10),
            Text(
              '字重.w300 - Light',
              style: TextStyle(fontWeight: FontWeight.w300, fontSize: 18),
            ),
            SizedBox(height: 10),
            Text(
              '字重.w400 - Normal',
              style: TextStyle(fontWeight: FontWeight.w400, fontSize: 18),
            ),
            SizedBox(height: 10),
            Text(
              '字重.w500 - Medium',
              style: TextStyle(fontWeight: FontWeight.w500, fontSize: 18),
            ),
            SizedBox(height: 10),
            Text(
              '字重.w600 - Semi Bold',
              style: TextStyle(fontWeight: FontWeight.w600, fontSize: 18),
            ),
            SizedBox(height: 10),
            Text(
              '字重.w700 - Bold',
              style: TextStyle(fontWeight: FontWeight.w700, fontSize: 18),
            ),
            SizedBox(height: 10),
            Text(
              '字重.w800 - Extra Bold',
              style: TextStyle(fontWeight: FontWeight.w800, fontSize: 18),
            ),
            SizedBox(height: 10),
            Text(
              '字重.w900 - Black',
              style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18),
            )
          ]
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_2024-08-27-17-55-05-51_cf80b1e8c147aa216f96c26e82185a74](https://github.com/user-attachments/assets/6ea05073-8d21-449b-afc1-f91e07bb18e0)
![Screenshot_2024-08-27-18-00-36-76_cf80b1e8c147aa216f96c26e82185a74](https://github.com/user-attachments/assets/82741992-b47a-46a0-9a5f-237f18fa5017)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on Ubuntu 24.04 LTS 6.5.0-1022-azure, locale zh_CN.UTF-8)
    • Flutter version 3.24.0 on channel stable at /home/vscode/.flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (4 周前), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/vscode/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/vscode/Android/sdk
    • ANDROID_SDK_ROOT = /home/vscode/Android/sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu224.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (2 available)
    • PDVM00 (mobile) • 192.168.123.3:43369 • android-arm64 • Android 11 (API 30)
    • Linux (desktop) • linux               • linux-x64     • Ubuntu 24.04 LTS 6.5.0-1022-azure

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by VillagerTom** [comment]
I don't know how many ColorOS versions are affected. I'm using v11.1, but my QQ group chat tested out that v14.0 and _v14.1 have this issue too.

**Comment by VillagerTom** [comment]
After several times of changing Flutter version (`git checkout <commit hash>` in `$FLUTTER_HOME`), I finally located the commit which results in the problem: ab98a0ac78c889e53022a036f18ff58747cb14e6 . Seems there are still many changes included from another repository. I'm a beginner at Flutter. Don't know how it works.😥

**Comment by huycozy** [comment]
Looks like this is an OS-specific issue as I don't see it appear on my device `Pixel 7, Android 14`. I will label this issue to have insight from others.


<details>
<summary>Demo screenshot/video (Pixel 7, Android 14)</summary>

| 3.24.1 | 3.22.3 |
| --------------- | --------------- |
<img width="400" src="https://github.com/user-attachments/assets/a8c1e6ea-9a70-4b60-b62d-d073cc631888"> | <img width="400" src="https://github.com/user-attachments/assets/15b93b5e-3339-45d1-8e59-39e219c5e545">
</details>

**Comment by liuzehnhang** [comment]
the problem has been fixed on Flutter master channel (Channel master, 3.25.0-1.0.pre.147),You can try upgrading
@VillagerTom 
But there are other issues after upgrading #154232 
I don't know if it's still a matter of font weight

**Comment by liuzehnhang** [comment]
![WechatIMG323](https://github.com/user-attachments/assets/0b5b55aa-1879-471c-9eec-a0a42328af69)
Chinese characters show on wrong font weight on ios , There are only two effects

**Comment by VillagerTom** [comment]
> ![WechatIMG323](https://github.com/user-attachments/assets/0b5b55aa-1879-471c-9eec-a0a42328af69)
> Chinese characters show on wrong font weight on ios , There are only two effects

There are only two weights in Chinese🤔According to my groups, some near-stock Android phones have the same issue. But since you have this with 3.22.3, I think it's a different issue from mine.

**Comment by naivetoby** [comment]
I have submitted a similar question https://github.com/flutter/flutter/issues/153677#issuecomment-2305868932
Looks like it has been fixed in the master branch. https://github.com/flutter/flutter/issues/153677#issuecomment-2311923333

**Comment by liuzehnhang** [comment]
The master branch has been fixed your  issue. You can try updating it  @VillagerTom

**Comment by VillagerTom** [comment]
> The master branch has been fixed your  issue. You can try updating it  @VillagerTom 

Yes! My groups test that HyperOS and Color both recovered to normal weight. What I want to know is that, will it be a backport fix to v3.24?

**Comment by huycozy** [comment]
Thanks for confirming @VillagerTom. I will keep this for team's thoughts if this needs a CP.

**Comment by VillagerTom** [comment]
@huycozy My friend with one ui 6.1 says he still has only two weights in Chinese with Flutter latest master. Is it reproducible on your pixel 7?

**Comment by huycozy** [comment]
>My friend with one ui 6.1 says he still has only two weights in Chinese with Flutter latest master.

Sorry, what does this mean? 

> Is it reproducible on your pixel 7?

No, it's not. Please check https://github.com/flutter/flutter/issues/154166#issuecomment-2314575884

**Comment by VillagerTom** [comment]
> >My friend with one ui 6.1 says he still has only two weights in Chinese with Flutter latest master.
> 
> Sorry, what does this mean? 
> 
> > Is it reproducible on your pixel 7?
> 
> No, it's not. Please check https://github.com/flutter/flutter/issues/154166#issuecomment-2314575884

You can compare your screenshot with mine. It seems w100~w500 all in regular weight, w600~w900 all in bold weight.

**Comment by VillagerTom** [comment]
@huycozy I think this is another bug, since it happens with Flutter 3.22.3 already. I don't have a phone with stock-like Android. Would you have a favor to open a new issue?

**Comment by naivetoby** [comment]
### Observations and Analysis

I have observed the following issues and would like to share my perspective:

#### Potentially Affected Scope:
- **Impeller Enabled**
- **Xiaomi Hyper OS**: Font weight appears thicker than expected.
- **Color OS**: Font weight appears lighter than expected.
- Other Android 14 devices with Chinese-language systems.

### Issue 1:
In Flutter 3.24.x, the Roboto default font is not found, causing a fallback to the system's default Chinese font.

This issue might have already been addressed in the Master branch.

### Issue 2:
Since Flutter 3.22.x, when using non-Roboto Chinese fonts, there seems to be a rendering anomaly where only two font weights are displayed.

This issue has not yet been reported or resolved.

### Potential Solutions:
- Use Flutter's official Roboto default font.
- Upgrade to the latest Master branch.

**Comment by liuzehnhang** [comment]
The only two weights in Chinese fonts on iOS phones ,  I found a solution in other issues ，https://github.com/flutter/flutter/issues/105014#issuecomment-2183698142
But it hasn't been solved on the Android emulator          (Pixel_3a_API_34_extension_level_7_arm64-v8a)

**Comment by liuzehnhang** [comment]
The only two weights in Chinese fonts on iOS phones , I found a solution in other issues ，https://github.com/flutter/flutter/issues/105014#issuecomment-2183698142

**Comment by naivetoby** [comment]
@huycozy @liuzehnhang 

Flutter 3.25.0-1.0.pre.219 

the Roboto default font is not found, still fallback to the system's default Chinese font.

**Comment by naivetoby** [comment]
flutter doctor -v

   ```shell
    [✓] Flutter (Channel beta, 3.25.0-0.1.pre, on macOS 14.6.1 23G93 darwin-x64, locale zh-Hans-CN)
        • Flutter version 3.25.0-0.1.pre on channel beta at /Users/toby/flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision d3733fcb0e (12 days ago), 2024-08-21 10:27:04 -0500
        • Engine revision 062b3a72fc
        • Dart version 3.6.0 (build 3.6.0-149.3.beta)
        • DevTools version 2.38.0
   ```

#### Steps to Fix:

1. In your `MaterialApp`, specify the following `fontFamilyFallback`:

   ```dart
   fontFamilyFallback: Platform.isIOS
       ? ['.AppleSystemUIFont', 'PingFang SC']
       : ['Roboto', 'sans-serif'], // 'sans-serif' Solve the problem that the emoticons may display abnormally
   ```

2. Add the Roboto font in `pubspec.yaml`:

   ```yaml
   flutter:
     uses-material-design: true
     fonts:
       - family: Roboto
         fonts:
           - asset: fonts/Roboto-Black.ttf
           - asset: fonts/Roboto-BlackItalic.ttf
           - asset: fonts/Roboto-Bold.ttf
           - asset: fonts/Roboto-BoldItalic.ttf
           - asset: fonts/Roboto-Italic.ttf
           - asset: fonts/Roboto-Light.ttf
           - asset: fonts/Roboto-LightItalic.ttf
           - asset: fonts/Roboto-Medium.ttf
           - asset: fonts/Roboto-MediumItalic.ttf
           - asset: fonts/Roboto-Regular.ttf
           - asset: fonts/Roboto-Thin.ttf
           - asset: fonts/Roboto-ThinItalic.ttf
   ```

**Comment by reidbaker** [comment]
Closed as fixed in the master branch based on https://github.com/flutter/flutter/issues/154166#issuecomment-2316547633

**Comment by VillagerTom** [comment]
> Closed as fixed in the master branch based on https://github.com/flutter/flutter/issues/154166#issuecomment-2316547633

Did you mean there won't be a backport to 3.24?

**Comment by reidbaker** [comment]
@VillagerTom, not right now. If you want a cherry pick to land into 3.24 you need to fill out a cherry pick request/pull request following the instructions here. https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-Cherrypick-Process.md

**Comment by VillagerTom** [comment]
My Codespaces finally become available today. After several times of examination, I found d4124bd5b571c57e4c5ebe545d61a06322a1fe24 in beta branch fix the issue. @huycozy @reidbaker 
 
flutter doctor -v 

```
[!] Flutter (Channel [user-branch], 3.24.0-1.0.pre.245, on Ubuntu 24.04 LTS 6.5.0-1025-azure, locale zh_CN.UTF-8)
    ! Flutter version 3.24.0-1.0.pre.245 on channel [user-branch] at /home/vscode/.flutter-sdk
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision d4124bd5b5 (6 周前), 2024-07-24 00:10:30 -0400
    • Engine revision 1572635432
    • Dart version 3.6.0 (build 3.6.0-75.0.dev)
    • DevTools version 2.37.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/vscode/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /home/vscode/Android/sdk
    • ANDROID_SDK_ROOT = /home/vscode/Android/sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu224.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (2 available)
    • PDVM00 (mobile) • 192.168.123.3:39167 • android-arm64 • Android 11 (API 30)
    • Linux (desktop) • linux               • linux-x64     • Ubuntu 24.04 LTS 6.5.0-1025-azure

[✓] Network resources
    • All expected network resources are available.
```

**Comment by VillagerTom** [comment]
> After multiple investigations, I found d4124bd in beta branch fixes the issue.

I cherry-picked this commit into latest stable branch locally. Everything works fine.
