### ISSUE TITLE
 Dependency 'androidx.credentials:credentials:1.2.0-rc01' requires libraries and applications that  depend on it to compile against version 34 or later of the Android APIs.

### ISSUE THREAD

**Issue by lerowi45** [flutter/flutter#154108]
### Steps to reproduce

1. Download the flutter_news_template
2. Follow the instructions to configure it
3. Run it

### Expected results

flutter_news_template should run without any error because I did not edit anything. I only followed the instructions given in the installation and running video from flutter

### Actual results

Dependency 'androidx.credentials:credentials:1.2.0-rc01' requires libraries and applications that depend on it to compile against version 34 or later of the Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by lerowi45** [comment]
Yes! I had those errors too initially. I had to upgrade the Android plugin version, compile and target sdk to 34, I downgraded JDK to 17 and the gradle too to its compatible version before most of those errors disappeared, but then a new error popped up, which is the twitter_login error. I discovered that its version 4.4.2 (<3.0.0 dart version)  is incompatible with the dart version constraint. I've left it. :(

**Comment by matiasleyba** [comment]
Hi guys 👋🏻 
The problems you are seeing are due to the version of flutter you are using, I suggest you try flutter 3.22.2.
We are working on updating the toolkit to support the latest version of flutter, this should be done soon, probably next week.

@danagbemava-nc @lerowi45

**Comment by matiasleyba** [comment]
Could you try it with the latest version of the toolkit [1.0.14](https://brickhub.dev/bricks/flutter_news_template)? 

@danagbemava-nc @lerowi45

**Comment by matiasleyba** [comment]
Closing the issue as it should be resolved using the latest version of the template, feel free to reopen the issue if the problem persists.
