### ISSUE TITLE
[CP] Make sure usesUnsupportedDependencyVersions property exists before checking it

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#154134]
### Issue Link

https://github.com/flutter/flutter/issues/153668

### Target

stable

### Cherry pick PR Link

tbd
Original pr: https://github.com/flutter/flutter/pull/154121

### Changelog Description

Make sure usesUnsupportedDependencyVersions property exists before checking it in the Flutter Gradle plugin.

### Impacted Users

Android flutter devs 

### Impact Description

Gives incorrect error message which distracts from the actual issue building. 

### Workaround

Users can try building with  `--android-skip-build-dependency-validation`

### Risk

low

### Test Coverage

no

### Validation Steps

n/a

**Comment by gmackall** [comment]
https://github.com/flutter/flutter/pull/154270
