### ISSUE TITLE
TextField maxLines not working

### ISSUE THREAD

**Issue by erkinovalim** [flutter/flutter#154120]
### Steps to reproduce

set TextField's maxLines parameter to anything greater than 1 

### Expected results

The TextField shouldn't let the user put more lines than what's specified in the maxLines parameter.

### Actual results

it doesn't stop the user from typing more lines in the TextField, when you press return in the simulator it just keeps adding more lines and scrolling down with each line being added.

### Code sample

TextField(
maxLines: 4,
keyboardType: TextInputType.multiline,
);

### Screenshots or Video

https://github.com/user-attachments/assets/7b9b071b-2b43-44b7-9f17-5eb696416253

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-KG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)            
[✓] Network resources

**Comment by NobodyForNothing** [comment]
Reproduced on desktop without specifying keyboardInputType:

<details><summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
  home: Scaffold(
    body: TextField(
      maxLines: 4,
    ),
  ),
));
```
</details>
<details><summary><code>flutter doctor -v</code></summary>

[✓] Flutter (Channel beta, 3.24.0-0.2.pre, on Garuda Linux 6.6.46-1-lts, locale
    en_US.UTF-8)
    • Flutter version 3.24.0-0.2.pre on channel beta at /home/derdilla/bin/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7c6b7e9ca4 (4 weeks ago), 2024-07-30 14:26:44 +0700
    • Engine revision 6e4deceb38
    • Dart version 3.5.0 (build 3.5.0-323.2.beta)
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/derdilla/Android/Sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at:
      /home/derdilla/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/derdilla/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at
      /home/derdilla/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 80.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Garuda Linux 6.6.46-1-lts

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

</details>

**Comment by NobodyForNothing** [comment]
But doesn't this work as expected? The [maxLines docs](https://api.flutter.dev/flutter/material/TextField/maxLines.html) clearly state:

> The maximum number of lines to show at one time, wrapping if necessary.

Which is different from say: "the max number of lines that can be entered"

**Comment by erkinovalim** [comment]
Thank you for the clarification, seems like I have misunderstood the purpose of the parameter. But I wish they would add such feature

**Comment by NobodyForNothing** [comment]
@erkinovalim I think you can use inputFormatters for that:
```dart
TextField(
  maxLines: 4,
  inputFormatters: [
    TextInputFormatter.withFunction((oldValue, newValue) {
      if (newValue.text.split('\n').length > 4) return oldValue;
      return newValue;
    })
  ],
)
```

(code untested)

**Comment by erkinovalim** [comment]
I knew this solution but I thought that was what maxLines was supposed to do.
