### ISSUE TITLE
repackage_gradle_wrapper.sh should check if curl is present

### ISSUE THREAD

**Issue by sad1996** [flutter/flutter#15413]
**Got this error while installing Flutter SDK from Android Studio as well as running Flutter Doctor from terminal. Need Help!! Thank you.**
![screenshot from 2018-03-12 02-07-21](https://user-images.githubusercontent.com/13837243/37258215-6a967d96-259a-11e8-9bb3-1826954ddadf.png)

**Comment by xster** [comment]
Does `which curl` return anything? 

Either your Linux distro doesn't come with curl, solvable by `sudo apt-get install curl` (and can be helped with #14050) or your .bashrc is misconfigured (if `/usr/bin/` isn't in your `echo $PATH`).

**Comment by sad1996** [comment]
That worked (sudo apt-get install curl).. Thanks a lot

**Comment by xster** [comment]
Will keep the bug open to make sure we check for curl on the system and show a better error message.

**Comment by sad1996** [comment]
Sure..

**Comment by BondarenkoStas** [comment]
Closing since it's fixed in https://github.com/flutter/flutter/pull/27295 v1.2.1
