### ISSUE TITLE
Google sign in error 400 when trying to change account after first account select screen

### ISSUE THREAD

**Issue by LouisHaftmann** [flutter/flutter#154161]
### What package does this bug report belong to?

google_sign_in

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

https://pastebin.com/EiBCm957

### Steps to reproduce

1. Trigger Google sign in with `googleSignIn.signIn()`
2. Select account
3. Click account selector on top of screen again
4. Error 400

### Expected results

The error should not occur. Just clicking continue after selecting the account in the first step works. It's just the button with the email address at the top that is not working for some reason?

### Actual results

Error 400
The server cannot process the request because it is malformed. It should not be retried. That's all we know

### Code sample

<details open><summary>Code sample</summary>

```dart
await GoogleSignIn(
    clientId: clientId,
    forceCodeForRefreshToken: true,
  ).signIn()
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

![Untitled](https://github.com/user-attachments/assets/ebbca07f-edda-4b9c-a8d1-ec2d8c0f7047)
![Untitled 2](https://github.com/user-attachments/assets/7253d1bf-17cc-419b-b779-7646c81669df)
![image](https://github.com/user-attachments/assets/c7f9afba-0638-43a6-9bf4-368e31c25e91)

</details>

### Logs

<details open><summary>Logs</summary>

```console
<there are no error logs>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1.3)
[✓] VS Code (version 1.92.2)
[✓] Connected device (7 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @LouisHaftmann 
I am unable to replicate this using the google_sign_in package example running on Android emulator. 
Can you try by clearing the cache ? Are you consistently getting this error on mobile only or on other platforms too ?
Also try on other devices to see if it persists or not.

**Comment by LouisHaftmann** [comment]
Sorry for the late replay.

I can reproduce it with the following code:

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

void main() {
  runApp(const MainApp());
}

Future<void> signIn() async {
  const clientId = 'YOUR_CLIENT_ID';
  GoogleSignIn googleSignIn = GoogleSignIn(
    clientId: clientId,
    serverClientId: clientId,
    forceCodeForRefreshToken: true,
  );
  // logout, just for testing
  await googleSignIn.signOut().catchError((_) {});
  await googleSignIn.disconnect().catchError((_) {});

  await googleSignIn.signIn();
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: FilledButton(
              onPressed: () {
                signIn();
              },
              child: const Text('Sign in with Google')),
        ),
      ),
    );
  }
}
```

I also found out that it works without error when setting `forceCodeForRefreshToken` to `false` but then the second screen (with `Sign in to NAME` and account switcher) doesn't even show up.

@darshankawar

**Comment by darshankawar** [comment]
I tried with above code, but getting `sign_in_failed, com.google.android.gms.common.api.ApiException: 10:` which is differrent issue.
Can you add try catch block and see if you get any meaningful log apart from 400 error ?
Also, can you try on other device or other account to check if it persist still ?

**Comment by LouisHaftmann** [comment]
You probably need to set the client id (replace the `YOUR_CLIENT_ID`). The app's Android package name also needs to match the package name in Google Cloud. 

> Also, can you try on other device or other account to check if it persist still
The error occurs on many different Android devices and Google accounts.

> Can you add try catch block and see if you get any meaningful log apart from 400 error
The 400 error doesn't throw an exception in Flutter. I don't even know if such an error could be caused by Flutter or whether this is a bug on Googles side.

@darshankawar

**Comment by darshankawar** [comment]
@LouisHaftmann 
With `clientId` as well, we are seeing same error as reported earlier. Without passing it, the code sample runs well without throwing the said error.
You seem to have declared same `clientId` for `serverClientId` which doesn't seem to be correct. So please check the implementation.

**Comment by LouisHaftmann** [comment]
I'm also getting the same error without `serverClientId`

**Comment by darshankawar** [comment]
Please check [this](https://discussions.apple.com/thread/255249348?sortBy=rank) to see if it helps in your case or not.
Not sure if this is specific to macOS Sonoma or not.
