### ISSUE TITLE
Typo when evaluating visual overflow in FittedBox

### ISSUE THREAD

**Issue by chsigg** [flutter/flutter#15410]
https://github.com/flutter/flutter/blob/e64d44ca78499712dfc0dab5ce074f79f03f5225/packages/flutter/lib/src/rendering/proxy_box.dart#L2176

Should say 'height' at the end: 
_hasVisualOverflow = sourceRect.width < childSize.width || sourceRect.height < childSize.height;

While I'm here, have you considered providing a 'clip' option to FittedBox, to disable clipping entirely?

**Comment by Hixie** [comment]
> While I'm here, have you considered providing a 'clip' option to FittedBox, to disable clipping entirely?

Can you elaborate on the use case for this?

**Comment by Hixie** [comment]
Interesting.

The difficulty with not clipping would be that things like hit-testing wouldn't work right outside the box. But if you have a concrete use case, please don't hesitate to file a bug and we can look at it and see what makes sense to support it.
