### ISSUE TITLE
enableFlutterDriverExtension(); stops android keyboard from showing up.

### ISSUE THREAD

**Issue by yfer** [flutter/flutter#15415]
## Steps to Reproduce

1. Open flutter_gallery project
2. Put enableFlutterDriverExtension(); in lib/main.dart 
3. Run app, try to use android keyboard in any input field, it is not showing.

```
import 'package:flutter/widgets.dart';
import 'package:flutter_driver/driver_extension.dart';
import 'gallery/app.dart';

void main() {
  enableFlutterDriverExtension();
  runApp(const GalleryApp());
}
```
## Problem research

It seems like intended but obsolete behaviour artifacts and lack of documentation.
```
>flutter drive --help

Runs Flutter Driver tests for the current project.
...
-t, --target=<path>             The main entry-point file of the application, as run on the device.
                                If the --target option is omitted, but a file name is provided on
                                the command line, then that is used instead.
                                (defaults to "lib/main.dart")
...
```
 **(defaults to "lib/main.dart")** seems obsolete due to https://flutter.io/testing/ specifically says that you should create new entry point for "Creating instrumented Flutter apps", flutter_gallery follow this document correctly at least for last 2 years.

#5800 Partly about this confusion, seems related.

If this is intended behaviour then https://docs.flutter.io/flutter/flutter_driver_extension/enableFlutterDriverExtension.html
should say about it.

## Flutter Doctor

```
[√] Flutter (Channel master, v0.2.1-pre.61, on Microsoft Windows [Version 10.0.16299.251], locale ru-RU)
    • Flutter version 0.2.1-pre.61 at c:\flutter
    • Framework revision 7865d319ba (2 hours ago), 2018-03-11 13:01:00 -0700
    • Engine revision 1d0da77995
    • Dart version 2.0.0-dev.33.0.flutter-b5b8080b2c

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Yfer\AppData\Local\Android\sdk
    • Android NDK at C:\Users\Yfer\AppData\Local\Android\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.4
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] VS Code, 64-bit edition (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by pujitm** [comment]
This is still an issue as of `v1.2.1`

**Comment by lenaschimmel** [comment]
The same is true for iOS as well (both on simulator and device). I checked on both _dev_ and _stable_.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.33.1)
[✓] Connected device (3 available)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.33.1)
[✓] Connected device (3 available)
```

**Comment by MaiReo** [comment]
This is still an issue as of ```v1.7.9-pre```

**Comment by pujitm** [comment]
Btw if anyone is struggling with this:

Create a separate entry point under `test_driver` and pass it to `flutter drive` like so:
`flutter drive --target=test_driver/test_main.dart`

This entry point *should* have `enableFlutterDriverExtension();`

Then, remove `enableFlutterDriverExtension();` from `main.dart`

**Comment by tnoor-co** [comment]
Still running into this issue while executing the `flutter_driver` tests using the `screenshots` library. It still targets the main `test.dart` file under `test_driver`. Changing the entry point is a good suggestion and I will have to look into it to see where it can be updated.

**Comment by GarimaVats** [comment]
i am also facing the same issue...while using appium_flutter_driver

**Comment by sohitEngg** [comment]
@pujitm Changing the target entry point will resolve the issue for executing the Application but what about the Appium automation tests which will remain failed to type in keyboard using scripts.

**Comment by jonahwilliams** [comment]
This is an intentional consequence of enableFlutterDriver extension. In order to allow the driver to interact with the application, this method changes the behavior of the  framework in several ways - including keyboard interaction and text editing. Applications intended for release should never include this method.

**Comment by GarimaVats** [comment]
@jonahwilliams you are right but due to this limitation appium-flutter-driver ( which is using flutter-driver APIs) is not able to enter text in flutter app. I tried all most all appium command for enter key like sendkey(). Appium doest not support flutter-driver command driver.enterText.

**Comment by jonahwilliams** [comment]
That is a problem that will have to be solved in Appium

**Comment by GarimaVats** [comment]
Agreed @jonahwilliams

**Comment by yapcwed** [comment]
@jonahwilliams What about the cases where you want to test how a keyboard showing up affects your UI? For example if you use something like [keyboard_visibility](https://pub.dev/packages/keyboard_visibility) you'd want the soft keyboard to open even when running tests with flutter_driver. Or is there another method to test this use case?

**Comment by pripriya2** [comment]
Hi All, This is the default implementation of flutter ''enterText" API. see below links:
1_ https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/enterText.html
2_ https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/setTextEntryEmulation.html
However if you use 
world.driver.setTextEntryEmulation(enabled: false);
before enterText keyboard pops up.

**Comment by shibupanda** [comment]
> That is a problem that will have to be solved in Appium

@jonahwilliams I am one of the maintainers in appium-flutter-driver and we are able to enterText in the editbox using flutter driver API.

But the issue(minor) is while entering text soft keyboard is not showing. If we can use setTextEntryEmulation = false, keyboard is showing but it's not able to enterText in the editbox same is mentioned in flutter driver API(enterText). Your input is really helpful.

**Comment by yapcwed** [comment]
@shibupanda I worked around this issue by creating an extension method on the Flutter driver, that opens the keyboard, enters the text and returns a Function to close the keyboard. I'm using the `requestData` interface of the FlutterDriver due to a transitive dependency to `dart:ui`.

DriverExtension:
```dart
extension CustomFlutterDriverExtensions on FlutterDriver {
  Future<Future<void> Function()> enterTextExtended(
    SerializableFinder finder,
    String text, {
    Duration timeout,
  }) async {
    await this.tap(finder);
    final result = await _textInput('TextInput.show');
    if ('true' == result) {
      await this.enterText(text, timeout: timeout);
      return () async => _textInput('TextInput.hide');
    } else {
      throw Exception('Failed to open keyboard');
    }
  }

  Future<String> _textInput(String method) async {
    await this.setTextEntryEmulation(enabled: false);
    final result = await this.requestData(jsonEncode(
      DataRequest('textInput', params: {'method': method}).serialize(),
    ));
    await this.setTextEntryEmulation(enabled: true);
    return result;
  }
}
```

RequestData:
```dart
Future<String> _requestTextInput(String method) async {
  try {
    await SystemChannels.textInput.invokeMethod(method);
    return true.toString();
  } catch (e) {
    return false.toString();
  }
}
```

**Comment by shibupanda** [comment]
Thanks @yapcwed.I may not use in this way in appium-flutter-driver directly until and unless available in flutter driver.
But you can help me on below query where I can do some work around using requestData.

1. What would be the message I need to pass here in requestData constructor. Whether the message `TextInput.show` and `TextInput.hide` would be enough. 
`const RequestData(this.message, { Duration timeout }) : super(timeout: timeout);  `
https://api.flutter.dev/flutter/flutter_driver/RequestData/RequestData.html

**Comment by yapcwed** [comment]
You're welcome. That is up to you, since the callback you register is your own code: `enableFlutterDriverExtension(handler: _myHandler);`. The interface is String based `Future<String> Function(String message);`. For my needs I created a serializable class to be able to support multiple data requests as follows:

```dart
class DataRequest {
  final String type;
  final Map<String, String> params;

  const DataRequest(this.type, {Map<String, String> params})
      : this.params = params ?? const <String, String>{};

  factory DataRequest.fromJson(Map<String, dynamic> json) {
    return DataRequest(
      json['type'],
      params: Map<String, String>.from(json['params']),
    );
  }

  Map<String, dynamic> toJson() => {
        'type': type,
        'params': params,
      };
}
```

**Comment by harih71research** [comment]
@shibupanda can u explain how to solve keyboard issue while running automation and manual. because am not able to find exact way, can you pls share ur code how ur calling handler and request. 

pls pinge me harih71@gmail.com

**Comment by cassioseffrin** [comment]
This bug stills happening on Flutter 1.22.6 • channel stable

**Comment by alexborelli1** [comment]
This bug stills happening on Flutter 1.22.6. 

Any update?
