### ISSUE TITLE
[web] Swipe back on iOS fixed in 3.24.0 but broke again in 3.24.1

### ISSUE THREAD

**Issue by hlynurl** [flutter/flutter#154102]
### Steps to reproduce

Run any flutter app on web in iOS and try the swipe back feature. An extra page is shown making the whole process of swiping back very strange. 

This has been well documented in various issues and one of them is [here](https://github.com/flutter/flutter/issues/114324) 

### Expected results

The swipe back feature should work as expected in iOS.

### Actual results

**THIS WAS FIXED**  🎉  in flutter 3.24.0 but **BROKE AGAIN**  😢  in flutter 3.24.1.

It is easily reproducible by creating a sample flutter project with routes and running them on each versions respectively in iOS.

This issue is created to bring attention to this matter, it is a very important fix to have since when the swiping is fixed, flutter has almost a native feeling on web.

**Comment by huycozy** [comment]
Hi @hlynurl, since https://github.com/flutter/flutter/issues/114324 is still open, I will close this in favor of that one, so that everyone there can aware updates. Please follow it for further updates. Thanks!
