### ISSUE TITLE
DisplayList indexing causes a performance regression for culled DisplayList dispatching

### ISSUE THREAD

**Issue by flar** [flutter/flutter#154164]
As seen in this graph: https://flutter-engine-perf.skia.org/e/?begin=1722726504&end=1724748757&keys=X346e104025d3787e8c5ad568df51e9fc&requestType=0&selected=commit%3D42503%26name%3D%252Cconfig%253Ddefault%252Ccpu_scaling_enabled%253Dfalse%252Cexecutable%253D_b_s_w_ir_cache_builder_src_out_ci_host_release_benchmarks_display_list_builder_benchmarks%252Clibrary_build_type%253Drelease%252Cmhz_per_cpu%253D2200%252Cnum_cpus%253D8%252Csub_result%253Dcpu_time%252Ctest%253DBM_DisplayListDispatchCull_kCulledWithRtree%252Cunit%253Dus%252C&xbaroffset=42409

**Comment by flar** [comment]
But there were also improvements as well. In this graph, the times went down when the indexed dispatching was landed and went up when it was reverted.

https://flutter-flutter-perf.skia.org/e/?begin=1722640878&end=1724724632&keys=Xfc5b6f7fd1231d499395088b9104bda9&requestType=0&selected=commit%3D42242%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dmokey%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dvery_long_picture_scrolling_perf__e2e_summary%252C&xbaroffset=42242

**Comment by jonahwilliams** [comment]
@flar I think this is OK for now, the tradeoffs of having this functionality seem worthwhile. Should we close this issue?

**Comment by flar** [comment]
We could probably "do better", but since these measurements are in uS, they probably aren't worth tracking. The improvements on frame times are in mS, so they outweigh the overhead.
