### ISSUE TITLE
interactive_media_ads mid-rolls/ad breaks/In-Stream ads support

### ISSUE THREAD

**Issue by yogendra-algoworks** [flutter/flutter#154261]
### Use case

I am playing mid-roll(In-Stream) ads.

As filter in interactive_media_ads plugin code.
I have found there is code that support mid-roll ads.

I am getting error as below if i run mid roll-ads

**OnAdsLoadError: Unable to handle cue points, no content progress provider configured.**

### Proposal

Kindly add example, How can use setContentProgressProvider 
to run mid-roll(In-Stream ads)

**Comment by darshankawar** [comment]
> I have found there is code that support mid-roll ads.

@yogendra-algoworks Can you point to the code that supports this type of ads ?



> I am getting error as below if i run mid roll-ads
> 
> **OnAdsLoadError: Unable to handle cue points, no content progress provider configured.**

Can you provide a runnable code sample that shows this error ?

**Comment by yogendra-algoworks** [comment]
Hi @darshankawar 
I have just downloaded example packages of interactive_media_ads  and  replaced Sample VAST TAG URL.

Sample VAST TAG:-
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/vmap_ad_samples&sz=640x480&cust_params=sample_ar%3Dpremidpostoptimizedpodbumper&ciu_szs=300x250&gdfp_req=1&ad_rule=1&output=vmap&unviewed_position_start=1&env=vp&impl=s&cmsid=496&vid=short_onecue&correlator="
      
      
Other Sample Vast Tag:-https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags


<img width="1416" alt="Screenshot 2024-08-29 at 1 03 25 PM" src="https://github.com/user-attachments/assets/463d0eb5-63a6-4810-a663-dd11e10b5d00">
