### ISSUE TITLE
Crash when hot-reloading 

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15429]
When hot-reloading on Android with a Samsung S8

From logcat

```
03-12 00:01:26.505  6712  6735 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10c in tid 6735 (ui_thread)
03-12 00:01:26.507   512   512 W         : debuggerd: handling request: pid=6712 uid=10232 gid=10232 tid=6735
03-12 00:01:26.617  6773  6773 E         : debuggerd: process stopped due to unexpected signal 27
03-12 00:01:26.621  1343  6774 W ActivityManager:   Force finishing activity com.hamilton.app/.activities.MainActivity
```

From flutter tool console output
```
Initializing hot reload...
Error -32601 received from application: Method not found
F/libc    ( 6884): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10c in tid 6907 (ui_thread)
```

**Comment by waihanko** [comment]
My Problem is Here.How Can I solve 
Launching lib\main.dart on Redmi 3 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk (25.4MB).
Installing build\app\outputs\apk\app.apk...
Error: ADB exited with exit code 1
[  0%] /data/local/tmp/app.apk
[  0%] /data/local/tmp/app.apk
[  0%] /data/local/tmp/app.apk
[  0%] /data/local/tmp/app.apk
[  1%] /data/local/tmp/app.apk
[  1%] /data/local/tmp/app.apk
[  1%] /data/local/tmp/app.apk
[  1%] /data/local/tmp/app.apk
[  2%] /data/local/tmp/app.apk
[  2%] /data/local/tmp/app.apk
[  2%] /data/local/tmp/app.apk
[  2%] /data/local/tmp/app.apk
[  3%] /data/local/tmp/app.apk
[  3%] /data/local/tmp/app.apk
[  3%] /data/local/tmp/app.apk
[  3%] /data/local/tmp/app.apk
[  4%] /data/local/tmp/app.apk
[  4%] /data/local/tmp/app.apk
[  4%] /data/local/tmp/app.apk
[  4%] /data/local/tmp/app.apk
[  5%] /data/local/tmp/app.apk
[  5%] /data/local/tmp/app.apk
[  5%] /data/local/tmp/app.apk
[  5%] /data/local/tmp/app.apk
[  6%] /data/local/tmp/app.apk
[  6%] /data/local/tmp/app.apk
[  6%] /data/local/tmp/app.apk
[  6%] /data/local/tmp/app.apk
[  7%] /data/local/tmp/app.apk
[  7%] /data/local/tmp/app.apk
[  7%] /data/local/tmp/app.apk
[  7%] /data/local/tmp/app.apk
[  8%] /data/local/tmp/app.apk
adb: error: failed to copy 'build\app\outputs\apk\app.apk' to '/data/local/tmp/app.apk': no response: Connection reset by peer
Error launching application on Redmi 3.

**Comment by zoechi** [comment]
I'd expect this issue to be stale. A lot has changed since.
But I can't test on Samsung S8.

**Comment by BondarenkoStas** [comment]
I feel safe to close the issue, as I couldn't find anything similar. Please correct me if I'm wrong.
