### ISSUE TITLE
Android Studio (not installed)

### ISSUE THREAD

**Issue by max8888888** [flutter/flutter#15425]
I was install Flutter,  My computer was windows 7, when I run "flutter doctor ", got a error :
```
Doctor summary (to see all details, run flutter doctor -v):
[âˆš] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 6.1.7601], lo
cale zh-CN)
[âˆš] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[X] Android Studio (not installed)
[âˆš] Connected devices (1 available)

! Doctor found issues in 1 category.
```
I'm a Android developer. Use Android studio 3.0.1
But the Flutter cannot find my android studio.  
what can I do ?
how to fix it ?
thank you!

**Comment by max8888888** [comment]
The "flutter doctor" can find the Android SDK, can find Android Platform, can find JAVA ...
why cannot find my android studio? my studio always there all the time……

**Comment by max8888888** [comment]
I was down new android studio from google, and reinstall android studio 3.0.1, but still got the same error......

**Comment by zhzhh7378** [comment]
me too

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
