### ISSUE TITLE
Run Flutter as a Chrome Extension

### ISSUE THREAD

**Issue by pepealonso95** [flutter/flutter#154286]
### Use case

Running Flutter as a chrome extension with skia is not possible due to new manifest updates on chrome extensions which disable importing scripts from external sources such as a url.

### Proposal

If I were able to bundle the skia engine in the app and point to it as a local file instead of having to point to it as an external URL, this would allow me to run Flutter using skia as a web app instead of running it in html mode.

**Comment by yjbanov** [comment]
You can use either `--no-web-resources-cdn` CLI option or `canvaskitBaseUrl` (https://docs.flutter.dev/platform-integration/web/initialization#the-_flutter-loader-load-api) to load canvaskit from a local file rather than the CDN.
