### ISSUE TITLE
flutter/bin/internal/update_dart_sdk.sh: line 54: curl: command not found

### ISSUE THREAD

**Issue by Emil333** [flutter/flutter#15428]
I am getting "flutter/bin/internal/update_dart_sdk.sh: line 54: curl: command not found" error when running flutter doctor in terminal

**Comment by zoechi** [comment]
What OS are you using? Is this a fresh Flutter install created with `git clone ...`?

**Comment by jlmalabanan** [comment]
I have the same issue here. i am running Ubuntu Linux and this is a fresh install created with git clone. This is the error that im getting when im running "flutter doctor" : 

user@ThinkPad:~$ flutter doctor
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
/home/user/flutter/bin/internal/update_dart_sdk.sh: line 54: curl: command not found

**Comment by Emil333** [comment]
@zoechi I am using linux, and yes its a fresh install with git clone. refer @jlmalabanan comment, I am getting the same.

**Comment by zoechi** [comment]
@Emil333 is `curl available on your system?

**Comment by mattjackson114** [comment]
What fixed this for me was installing curl. Worked like a charm after that.

**Comment by n-jay** [comment]
+1 for @mattjackson114, the issue is resolved once CURL is installed with an apt-get.

**Comment by alvarlagerlof** [comment]
This should be closed.
