### ISSUE TITLE
flutter-devicelab-mac-23 cannot access attached iPhone

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#154206]
### Type of Request

bug

### Infrastructure Environment

DeviceLab

### What is happening?

I ssh'ed to `flutter-devicelab-mac-23.mtv.corp.google.com` in order to create and test a new dev signing cert, following the instructions in b/256878500. When I got to step (5) there was no attached iOS device. Running `flutter doctor` and `flutter devices` (even by extending the --device-timeout to 30 seconds) shows no attached device.

Opening Xcode and checking *Window > Devices & Simulators* shows a record of a previous iPhone but it doesn't seem to be attached and accessible.

### Steps to reproduce

1. Set up a port forward to mac23. Use the password recorded in Valentine:
   ```sh
   ssh -L 5900:localhost:5900 swarming@flutter-devicelab-mac-23.mtv.corp.google.com
   ```

2. Make a VNC connection by opening the Finder on your local machine, press Cmd-K, then for the URL, put `vnc://localhost`. 

3. Connect as `swarming` with the password in Valentine.

4. Open the terminal and execute:
   ```sh
   cd ~/Downloads/hello1
   ../flutter/bin/flutter devices
   ```

### Expected results

Expected behaviour: a physical iPhone 12 is listed
Actual behaviour: only the macOS device is listed

**Comment by christopherfujino** [comment]
@kentnguyen99 could you take a look at this host and see why it's not detected the iphone?

**Comment by kentnguyen99** [comment]
@cbracken Can you give another try? It should be working now, there is diaglog prompting on phone device require to respond.

**Comment by cbracken** [comment]
Thanks -- taking a look!

**Comment by cbracken** [comment]
Thanks @kentnguyen99 ! The device now shows as attached.
