### ISSUE TITLE
Gallery App needs an editable value slider

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1542]
From https://www.google.com/design/spec/components/sliders.html#sliders-continuous-slider

"With an editable numeric value

Use for settings for which users need to set the exact value. Upon pressing the thumb, the text box becomes editable for text entry and updates the value automatically with thumb movement."

**Comment by Hixie** [comment]
This is easy to do. Do we really need an example of it in the gallery?

**Comment by MarcinusX** [comment]
Hi, is this issue still valid?
If so, how can I contribute?

**Comment by eseidelGoogle** [comment]
Contributing instructions are listed here: https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md

This looks like a pretty straightforward combination of existing widgets, which means this is probably a good place to start! :)

The code would live somewhere in:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/

**Comment by eseidelGoogle** [comment]
The gallery itself is located here: https://github.com/flutter/flutter/tree/master/examples/flutter_gallery/lib
Maybe we already have this widget and it just needs to be added to the gallery?

**Comment by MarcinusX** [comment]
(Sorry for long delay)
I have a question: Do we want it as separate Widget added to slider.dart and be easy accessible by other developers or just implement it in Gallery app?

**Comment by gspencergoog** [comment]
This issue is just about implementing it for the gallery app. It's pretty straightforward to make this from a Row with editable text fields on one end of the slider.

**Comment by SUPERETDUPER** [comment]
@sethladd @gspencergoog @Hixie I submitted a pull request (#23506). Can someone review please?

**Comment by khalithartmann** [comment]
Hello you awesome people!
I just created a Let's Flutter Berlin group on Facebook to bring flutter developers in Berlin together to discuss problems, share ideas and create beautiful things together. If you live in Berlin, it would be awesome if you could join the group 😊! If you don't live in Berlin, feel free to join too! Im grateful for each and every supporter.  

Let's Flutter Berlin: https://www.facebook.com/groups/276520973054067/about/
Sorry for spamming.

**Comment by khalithartmann** [comment]
> @khalithartmann Please don't spam the issues.
> 
> Please go through and delete all your spam comments so that others don't have to. Event advertisement is not an appropriate use of the issue database.
> 
> Thanks!

okay will do that. sorry for the spam..
