### ISSUE TITLE
[CP]  reland weaken affinity of raster/ui to non-e core instead of only fast core

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#154275]
### Issue Link

flutter/flutter#153690

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/engine/pull/54842

### Changelog Description

* Adjust engine threading affinities on Android to better match actual core count.

### Impacted Users

Android Skia

### Impact Description

* Worse performance in scenarios with multiple flutter applications

### Workaround

No work around

### Risk

low

### Test Coverage

yes

### Validation Steps

Attached unit tests.

**Comment by jonahwilliams** [comment]
@zanderso

**Comment by zanderso** [comment]
CP lgtm
