### ISSUE TITLE
Improve the ListTile docs: explain the Text maxLines dependency

### ISSUE THREAD

**Issue by kylegoetz** [flutter/flutter#15423]
Flutter beta.

Docs say `ListTiles` are all the same height, and all 1–3 lines high. When I build `ListTiles` with subtitle property containing a very length Text object, those `ListTiles` are *wayyyy* taller than three lines and certainly not of equal height like the docs say they're supposed to (even if you construe "three lines" as "three spans of text separated by \n".

See screenshot. These are two ListTiles.

<img width="257" alt="screen shot 2018-03-11 at 23 07 49" src="https://user-images.githubusercontent.com/8161573/37265447-6f2b3572-2581-11e8-9e28-500d4bd5594b.png">

Relevant code:
```dart
    new ListView(
        shrinkWrap: true,
        scrollDirection: Axis.vertical,
        ListTile.divideTiles(
            color: Colors.deepOrange,
            tiles: items.map((item) {
                return _buildRow(item);
            }).toList()
        ).toList()
    )

    Widget _buildRow(Item item) {
        return new Dismissible(
            key: new Key(item.id.toString()),
            //...
            child: new Padding(
                child: new ListTile(
                    title: new Text(item.title),
                    subtitle: new Text(item.content),
                    textAlign: TextAlign.justify
                )
                //...
            )
        );
    }
```

**Comment by Hixie** [comment]
cc @gspencergoog 

We probably lost some limits when adding support for text scaling; I guess the texts should have explicit maxLines and ellipses enabled.

**Comment by kylegoetz** [comment]
I just implemented some truncation just to keep really long content from making a full-screen ListTile and I can see the ListTiles are not the same height. Is it because the ListTiles are wrapped in a Dismissible, so that maybe ListView no longer can set the height of the ListTiles to be the same? Do the ListTiles have to be immediate children of ListView?

**Comment by kylegoetz** [comment]
<img width="242" alt="screen shot 2018-03-11 at 23 30 18" src="https://user-images.githubusercontent.com/8161573/37265851-3c9b3564-2584-11e8-8c2c-ee5e26fe73f7.png">

**Comment by gspencergoog** [comment]
Yeah, the ListTile only knows that the title and subtitle are widgets.  The parameter "isThreeLine" is a little misleading in that regard, and we should probably document that better. Three line tiles differ from two line tiles only in their min height.  One line tiles have a smaller min height than two line, and also don't show the subtitle widget.

It does expand to fit the widgets put inside it, so you will need to set `maxLines` and `overflow` on your `Text` arguments to match what you want your limits to be.

**Comment by HansMuller** [comment]
The documentation for ListTile.title, ListTile.subtitle, ListTile.isThreeLine should explain the need for setting maxLines in Text widgets.

**Comment by Hixie** [comment]
Could ListTile set the maxLines using DefaultTextStyle?

**Comment by mac2000** [comment]
Not sure if it is related or not, but there is no docs explaining how ListTile works with contentPadding, margin and probably something like min height.

I'am trying to build column with 2 divided list tiles, one of them has long text.

There is no extension point to make "paddings" between dividers to be the same for both single line and multi line list tiles.
