### ISSUE TITLE
Feature request: More styling of ExpansionTile

### ISSUE THREAD

**Issue by FunMiles** [flutter/flutter#15427]
Expansion tile is quite a useful widget. But it is very inflexible in its styling.

- [x] it uses a ListTile, but does not allow to put a subtitle 
- [ ] when it expands it adds separators at the top and bottom.
- [x] when expanded it creates a column but does not allow to specify any properties of the column (e.g. the cross axis alignment is always center.)

It would be good to have a lot more control on the styling.

**Comment by Shantanu-Kotambkar** [comment]
@FunMiles @Hixie @HansMuller We would really love to see all these improvements. Is there by any chance any update available on this? Or may be a possible work around, for any of these:

-  when expanded it creates a column but does not allow to specify any properties of the column (e.g. the cross axis alignment is always center. 
-  when it expands it adds separators at the top and bottom.

**Comment by Hixie** [comment]
I don't think we're planning on adding these in the near future but it should be relatively easy to add and we would be happy to review any PRs if you wish to implement and contribute these features!

**Comment by Shantanu-Kotambkar** [comment]
@Hixie  I was able to make changes to the expansion_tile.dart, to get the desired behavior. However, I haven't really contributed changes to a code base before. Would you point me to any guidelines I can review and learn, to start with.

**Comment by jwiese-ms** [comment]
@Shantanu-Kotambkar did this ever go anywhere?  I'd love to see some styling of the 'header' as well to allow for the background of the title area to be set.  I'd be happy to take what you've done and make any other changes and submit a PR if you haven't done this yet.

**Comment by Shantanu-Kotambkar** [comment]
Hi @jwiese-ms ,i have used nested widgets and streams (BLoC pattern) to get better control of the ExpansionTile. I have been looking for full time opportunities and haven't made the implementation generic yet. I would let you know as soon as i am able to get it done!

**Comment by chinmay512** [comment]
Hi there I have a solution to this problem posted as an answer on [stackoverflow](https://stackoverflow.com/a/56886343/6245630). Although this does not fix the issue. But I think it is an easy and effortless workaround. Let me know what you guys think. Cheers.

**Comment by dvorapa** [comment]
Yeah, I miss the subtitle a lot there

**Comment by luizfranca** [comment]
In this PR [#43946](https://github.com/flutter/flutter/pull/43946) I added a subtitle to the expansion tile. I was going to add the styling parameters as well, but I thought maybe this should be in a different PR.

**Comment by Sudhakargundu** [comment]
how can we put the custom trailing icon in ExpansionListTile, that could be changed to another custom icon while it's getting expanded, please provide sufficient example

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue.
We can add the `alignment` property since we are using `Align` [here](https://github.com/flutter/flutter/blob/f139b11009aeb8ed2a3a3aa8b0066e482709dde3/packages/flutter/lib/src/material/expansion_tile.dart#L178).
We can also add the padding for the children, by wrapping the `Column` by `Padding` Widget. 
WDYT?

**Comment by shihaohong** [comment]
@AyushBherwani1998 Sounds good! Make sure to test out how the different alignments affect the contents of the expanded tile on a sample app to ensure the widget behaves as expected. This will also likely help you with writing the test cases needed for the PR

**Comment by AyushBherwani1998** [comment]
@shihaohong  Thanks, I'll keep that in mind. Should I send a PR which includes both the properties alignment and padding or make a separate PR for each?

**Comment by shihaohong** [comment]
I'd do them separately, keeps each PR clean and easy to follow

**Comment by dvorapa** [comment]
Just a side note: The ExpansionTile's recently added "subtitle" option looks different from ListTile subtitle (at least in stable 1.12). This might also be considered when adding some new styling options.

**Comment by shihaohong** [comment]
@dvorapa Could you file a new issue describing the expected and actual behavior? 

Questions to address for when you file the issue (We shouldn't discuss it in this thread since this issue is strictly about implementing new styling for `ExpansionTile`, and not about the nuances of subtitle): At first glance at the code, it seems to be doing the right thing. Also, are you describing a regression, or has this difference been observed since the property was exposed?

**Comment by dvorapa** [comment]
Since the property was exposed. I stuck with not using it as it looks so different from ListTile subtitle, so the list with both of them looks weird. I'll printscreen the difference and file a new issue then (I thought the styling is different by design).

**Comment by AyushBherwani1998** [comment]
@shihaohong I tried with some combinations. It requires me to add three new properties to `ExpansionTile`, `alignment` property for `Align`. `crossAxisAlignment` and `textBaseline` to `Column` used for `ExpansionTile.children`.

When the width of all the children is the same, then `alignment` property can be used to align `Column` which will by default position the children to the alignment specified. 
If the width of all the children is not the same, then the `Column` width will be the maximum width of the children, and then users may have to use both `alignment` and `crossAxisAlignment` property to achieve the desired UI.

**Comment by shihaohong** [comment]
@AyushBherwani1998 That explanation makes sense. Maybe there's a way to try and be clever about using a single parameter control both? However, we should avoid it if it's not straightforward and is instead limiting for the user. Try having combinations of `alignment` and `crossAxisAlignment` and see if there's some setup that might be desirable that cannot be achieved with the use of a single parameter. If not, then maybe wiring both might be necessary.

How does `textBaseline` come into play here?

**Comment by shihaohong** [comment]
Also, if using two params end up becoming necessary, we should provide API doc sample code so that users are aware of what's going on

**Comment by AyushBherwani1998** [comment]
> 
> How does `textBaseline` come into play here?

If the user sets the value to be `CrossAxisAlignment.baseline `, then `textBaseline` is necessary.

**Comment by AyushBherwani1998** [comment]
> 
> 
> @AyushBherwani1998 That explanation makes sense. Maybe there's a way to try and be clever about using a single parameter control both? However, we should avoid it if it's not straightforward and is instead limiting for the user. Try having combinations of `alignment` and `crossAxisAlignment` and see if there's some setup that might be desirable that cannot be easily achieved with the use of a single parameter (edit: thinking about this more, i'm not sure if this is possible and what we want). If not, then maybe wiring both might be necessary.

Sure, I'll play around with the parameters and see if it works.

**Comment by dvorapa** [comment]
> @dvorapa Could you file a new issue describing the expected and actual behavior?
> 
> Questions to address for when you file the issue (We shouldn't discuss it in this thread since this issue is strictly about implementing new styling for `ExpansionTile`, and not about the nuances of subtitle): At first glance at the code, it seems to be doing the right thing. Also, are you describing a regression, or has this difference been observed since the property was exposed?

The layout issue I encountered earlier this year seems to be fixed, but there is still a color difference between subtitle in ListTile and subtitle in ExpansionTile:

![flutter_02](https://user-images.githubusercontent.com/5113916/80529947-94a38480-8998-11ea-8683-5e5c600117ef.png)

**Comment by dvorapa** [comment]
Created #55894 for this issue

**Comment by AyushBherwani1998** [comment]
> 
> 
> @AyushBherwani1998 That explanation makes sense. Maybe there's a way to try and be clever about using a single parameter control both? However, we should avoid it if it's not straightforward and is instead limiting for the user. Try having combinations of `alignment` and `crossAxisAlignment` and see if there's some setup that might be desirable that cannot be easily achieved with the use of a single parameter (edit: thinking about this more, i'm not sure if this is possible and what we want). If not, then maybe wiring both might be necessary.

@shihaohong I guess it should work. Since we are concerned with position of the children and not with the alignment of `Column`, we can expose the `crossAxisAlignment` and `textBaseLine` properties. 
Based on the value of `crossAxisAlignment` we can decide the value of `alignment`. 
For Example
```dart
if (widget.crossAxisAlignment == CrossAxisAlignment.start)
      alignment = Alignment.centerLeft;
if (widget.crossAxisAlignment == CrossAxisAlignment.end)
      alignment = Alignment.centerRight;
```
For `crossAxisAlignment.stretch` the alignment won't come into play, and for handling `crossAxisAlignment.basline` we can have `textBaseLine`. WDYT?

**Comment by shihaohong** [comment]
If we end up going through with having both crossAxisAlignment and alignment be controlled by the same param, do take note that you'll need to pass in an alignment for every other potential value of `CrossAxisAlignment`, as well as handle textDirection correctly:

```dart
    AlignmentGeometry alignment;
    TextDirection textDirection = Directionality.of(context);

    switch (widget.childrenAlignment) {
      case CrossAxisAlignment.start: {
        if (textDirection == TextDirection.ltr) {
          alignment = Alignment.centerLeft;
        } else {
          alignment = Alignment.centerRight;
        }
        break;
      }
      case CrossAxisAlignment.end: {
        if (textDirection == TextDirection.ltr) {
          alignment = Alignment.centerRight;
        } else {
          alignment = Alignment.centerLeft;
        }
        break;
      }
      case CrossAxisAlignment.center:
      case CrossAxisAlignment.baseline:
      case CrossAxisAlignment.stretch:
      default:
        alignment = Alignment.center;
        break;
    }
```

However, I did test for a particular use-case that the user might actually want (alignment centerRight, crossAxisAlignment: start):

<img width="564" alt="Screen Shot 2020-04-30 at 11 00 18 AM" src="https://user-images.githubusercontent.com/27032613/80743437-ca985400-8ad1-11ea-913f-ddea1bd5128c.png">

Notice that the `Align.alignment` is set to `Alignment.centerRight` and `Column.crossAxisAlignment` is set to `CrossAxisAlignment.start`. Without passing in the parameters separately as two parameters, this configuration would not be possible. I think it might make more sense to use separate params for the sake of improved configurability at the expense of having a slightly bigger API.

**Comment by AyushBherwani1998** [comment]
@shihaohong completely makes sense, I'll expose the three parameters in the PR to provide more configuration.

**Comment by AyushBherwani1998** [comment]
Hey @shihaohong I have submitted a PR. Looking forward to your reviews :)

**Comment by AyushBherwani1998** [comment]
@shihaohong while adding the padding property for `children` I was going through the Material specs for `ExpansionTile`. When the value of padding is `null` should I follow the Material specs for the default padding or add an assertion?

For example:
```
 EdgeInsetsGeometry _setPadding(){
    if(widget.childrenPadding == null){
      if(widget.leading == null) {
        return const EdgeInsets.symmetric(horizontal: 16);
      }
      return const EdgeInsets.only(left: 72, right: 16);
    }
    return widget.childrenPadding;
  }
```

Just for easy access, I'm sharing the link for specs: [here](https://material.io/components/lists#specs)

**Comment by shihaohong** [comment]
@AyushBherwani1998 It seems like the specification for an expanded tile's `children` isn't actually in the spec -- From looking over it quickly, all the specifications directly apply to the tile itself.

That said, I would just keep the default to what the original padding is (before introducing any changes) as the default, and provide the parameter to be configurable. Right now, is there a padding by default, or is there none?

**Comment by AyushBherwani1998** [comment]
@shihaohong As of now, there is no default padding for `children`.

**Comment by shihaohong** [comment]
Sounds good, then what I would do is have it default to having no padding and provide a configurable parameter to adjust the padding surrounding the `Column` widget in the expanded segment of the ExpansionTile

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted a PR for adding padding for `children`. Looking forward to reviews.

**Comment by shihaohong** [comment]
The only feature left in the original issue is to add optional separators to the top and bottom of the `ExpansionTile` when it is expanded. Could the definition of "separator" here be better defined? I'm not exactly sure what the desired behavior is.

**Comment by AyushBherwani1998** [comment]
@shihaohong I guess the "separator" here is pointing to the top and bottom border applied to `ExpansionTile`.

![Screenshot_1589819682](https://user-images.githubusercontent.com/34301187/82237910-047fac00-9954-11ea-9a2a-672ee285c679.png)

**Comment by shihaohong** [comment]
If that's the case, it means that the feature is already present. Let's close out the issue for now. If that isn't what the original poster had in mind, we can always just re-open this issue or create a separate issue to track the individual feature request.

Thanks for taking the time to add customization to ExpandedTile @AyushBherwani1998!
