### ISSUE TITLE
viewInsets and padding on Window and MediaQueryData should define how they interact

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15424]
Right now we don't see to say anywhere whether they overlap or add.

If they overlap, we should probably fix removePadding to also reduce the viewInsets by the same amount.

cc @cbracken

**Comment by Hixie** [comment]
cc @cbracken Any chance I could convince you to add these docs soon? The lack of clarity around the semantics of padding and viewInsets is leading to some confusion. (e.g. see https://github.com/flutter/flutter/issues/10826).

**Comment by Hixie** [comment]
(In fact, looking at the `ScaffoldState.build` method, now I'm very confused as to what the semantics are supposed to be myself.)

**Comment by sir-boformer** [comment]
I'm also confused...
