### ISSUE TITLE
Gallery App has Toasts

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1543]
"Android also provides a toast, primarily used for system messaging. Toasts are similar to snackbars but do not contain actions and cannot be swiped off screen."

**Comment by Hixie** [comment]
This isn't really a Flutter feature, in that it's just calling an Android API from Java code. Is this something you want to track for the gallery still? Should we add this to our list of first-party plugins that we want to build?

**Comment by eseidelGoogle** [comment]
I suspect we can close this. It's a very simple plugin to write.  Eventually some internal app will and it will get added to our list of first -party plugins probably.  FYI @mehmetf

**Comment by sethladd** [comment]
yeah, sounds like toasts are really only for "the system", and it's very rare for an app to trigger a toast. Snackbars seem to be sufficient. Closing!
