### ISSUE TITLE
`tests` repo fails "Scorecards supply-chain security"

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#154355]
The tests repo has repeatedly been failing with the "Scorecards supply-chain security"

See: https://github.com/flutter/tests/actions

## log
```
Error: scorecard.Run: repo unreachable: GET https://api.github.com/repos/flutter/tests: 401 Bad credentials []
2024/08/29 17:05:25 error during command execution: scorecard.Run: repo unreachable: GET https://api.github.com/repos/flutter/tests: 401 Bad credentials []
```

**Comment by gaaclarke** [comment]
I don't know who maintains this, throwing it over to the framework.

**Comment by matanlurey** [comment]
We disabled this scorecard for the other repos (packages, engine, fluttee) and should probably just do the same here.

**Comment by goderbauer** [comment]
(triage) @matanlurey Is this work completed with https://github.com/flutter/flutter/pull/154272? Or is there more to do?

**Comment by gaaclarke** [comment]
I suspect the same thing would have to be done for the `tests` repo.  The linked work is for the `flutter` repo.

**Comment by matanlurey** [comment]
I can send a PR 🤷🏼
