### ISSUE TITLE
[CP] [skwasm] Fix platform view occlusion logic.

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#154349]
### Issue Link

https://github.com/flutter/flutter/issues/152139

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/engine/pull/54871

### Changelog Description

Fixes platform view occlusion logic when using the WASM renderer

### Impacted Users

Web apps compiled to WASM using platform views

### Impact Description

Apps using platforms views are broken when compiled to WASM

### Workaround

No workaround

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
Approved by @eyebrowsoffire in https://github.com/flutter/engine/pull/54871

**Comment by Rexios80** [comment]
@itsjustkevin Should this be closed since it was released with 3.24.3?
