### ISSUE TITLE
webview_flutter: ^4.9.0 this version http link not work

### ISSUE THREAD

**Issue by Mustakim-final** [flutter/flutter#154320]
### Steps to reproduce

webpage not available

### Actual results

webpage not available

### Logs

Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk
Debug service listening on ws://127.0.0.1:54022/SrYReywfuUo=/ws
Syncing files to device sdk gphone x86...
I/WebViewFactory( 6018): Loading com.google.android.webview version 83.0.4103.106 (code 410410681)
I/xample.web_vie( 6018): The ClassLoaderContext is a special shared library.
D/nativeloader( 6018): classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/x86:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/x86:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/x86:/product/lib:/system/product/lib
I/xample.web_vie( 6018): The ClassLoaderContext is a special shared library.
D/nativeloader( 6018): classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/x86:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/x86:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/x86:/product/lib:/system/product/lib
I/cr_LibraryLoader( 6018): Loaded native library version number "83.0.4103.106"
I/cr_CachingUmaRecorder( 6018): Flushed 3 samples from 3 histograms.
I/TetheringManager( 6018): registerTetheringEventCallback:com.example.web_view
I/cr_VariationsUtils( 6018): Requesting new seed from IVariationsSeedServer
W/xample.web_vie( 6018): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
D/HostConnection( 6018): HostConnection::get() New Host Connection established 0xe841fb90, tid 6127
D/HostConnection( 6018): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
E/chromium( 6018): [ERROR:gl_surface_egl.cc(549)] eglChooseConfig failed with error EGL_SUCCESS
D/EGL_emulation( 6018): eglCreateContext: 0xe8405a30: maj 2 min 0 rcv 2
D/EGL_emulation( 6018): eglMakeCurrent: 0xe8405a30: ver 2 0 (tinfo 0xac115690) (first time)
E/chromium( 6018): [ERROR:gl_surface_egl.cc(549)] eglChooseConfig failed with error EGL_SUCCESS
I/VideoCapabilities( 6018): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil( 6018): HW encoder for video/avc is not available on this device.
D/EGL_emulation( 6018): eglCreateContext: 0xe8403b90: maj 2 min 0 rcv 2
I/PlatformViewsController( 6018): Hosting view in view hierarchy for platform view: 0
I/PlatformViewsController( 6018): PlatformView is using SurfaceProducer backend
W/Gralloc4( 6018): allocator 3.x is not supported
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
I/flutter ( 6018): Page started loading: http://103.69.151.142:88/hrm/my.php
I/flutter ( 6018): Error: net::ERR_CLEARTEXT_NOT_PERMITTED
I/flutter ( 6018): Page finished loading: http://103.69.151.142:88/hrm/my.php
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
D/ImageReaderSurfaceProducer( 6018): ImageTextureEntry can't wait on the fence on Android < 33
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
I/chatty  ( 6018): uid=10169(com.example.web_view) RenderThread identical 2 lines
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
D/ProfileInstaller( 6018): Installing profile for com.example.web_view
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.
E/FrameEvents( 6018): updateAcquireFence: Did not find frame.

### Flutter Doctor output

not error

**Comment by danagbemava-nc** [comment]
To use http links in the android WebView, you need to enable cleartextTraffic. See https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https for how you can do this. 

Closing from here as this is not a flutter issue. 

Thank you

**Comment by Mustakim-final** [comment]
i enable cleartextTraffic but same error webpage not available

**Comment by danagbemava-nc** [comment]
Do you still see `I/flutter ( 6018): Error: net::ERR_CLEARTEXT_NOT_PERMITTED` in your logs?

**Comment by Mustakim-final** [comment]
yes i still see this error my logs

**Comment by Mustakim-final** [comment]
please suggest me how to solve it

**Comment by danagbemava-nc** [comment]
Hi @Mustakim-final, if you still see `I/flutter ( 6018): Error: net::ERR_CLEARTEXT_NOT_PERMITTED` in your logs it means you have not correctly applied the cleartextTraffic attribute. Kindly share your `AndroidManifest.xml`

**Comment by Mustakim-final** [comment]
<manifest xmlns:tools="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <application android:label="Mock Talk" android:name="${applicationName}" android:icon="@mipmap/ic_launcher">
        <activity
            android:networkSecurityConfig="@xml/network_security_config"
            android:usesCleartextTraffic="true"
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize"
            tools:targetApi="m">
            
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme"/>

            <meta-data android:name="io.flutter.network-policy"
                android:resource="@xml/network_security_config"/>

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data android:name="flutterEmbedding" android:value="2"/>
    </application>
    
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>

**Comment by Mustakim-final** [comment]
<manifest xmlns:tools="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <application android:label="Mock Talk" android:name="${applicationName}" android:icon="@mipmap/ic_launcher">
        <activity
            android:networkSecurityConfig="@xml/network_security_config"
            android:usesCleartextTraffic="true"
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize"
            tools:targetApi="m">
            
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme"/>

            <meta-data android:name="io.flutter.network-policy"
                android:resource="@xml/network_security_config"/>

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data android:name="flutterEmbedding" android:value="2"/>
    </application>
    
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>

**Comment by Mustakim-final** [comment]
<manifest xmlns:tools="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <application android:label="Mock Talk" android:name="${applicationName}" android:icon="@mipmap/ic_launcher">
        <activity
            android:networkSecurityConfig="@xml/network_security_config"
            android:usesCleartextTraffic="true"
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize"
            tools:targetApi="m">
            
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme"/>

**Comment by Mustakim-final** [comment]
xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <application android:label="Mock Talk" android:name="${applicationName}" android:icon="@mipmap/ic_launcher">
        <activity
            android:networkSecurityConfig="@xml/network_security_config"
            android:usesCleartextTraffic="true"
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize"
            tools:targetApi="m">
            
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme"/>

**Comment by Mustakim-final** [comment]
<activity
            android:networkSecurityConfig="@xml/network_security_config"
            android:usesCleartextTraffic="true"
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize"
            tools:targetApi="m">
            
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme"/>

            <meta-data android:name="io.flutter.network-policy"
                android:resource="@xml/network_security_config"/>

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

**Comment by Mustakim-final** [comment]
android:usesCleartextTraffic="true"
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"

**Comment by Mustakim-final** [comment]
[AndroidManifest.zip](https://github.com/user-attachments/files/16833216/AndroidManifest.zip)
this is my manifest file.

**Comment by Mustakim-final** [comment]
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:webview_flutter_android/webview_flutter_android.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int progress = 0;
  late final WebViewController controller;

  @override
  void initState() {
    super.initState();

    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progressValue) {
            setState(() {
              progress = progressValue;
            });
          },
          onPageStarted: (String url) {
            print('Page started loading: $url');
          },
          onPageFinished: (String url) {
            print('Page finished loading: $url');
          },
          onWebResourceError: (WebResourceError error) {
            print('Error: ${error.description}');
          },
        ),
      )
      ..loadRequest(Uri.parse('http://103.69.151.142:88/hrm/my.php'));

    if (Platform.isAndroid) {
      final androidController = controller.platform as AndroidWebViewController;
      androidController.setOnShowFileSelector(_androidFilePicker);
    }
  }

  Future<List<String>> _androidFilePicker(dynamic params) async {
    FilePickerResult? result = await FilePicker.platform.pickFiles();

    if (result != null) {
      String filePath = result.files.single.path!;
      String fileName = result.files.single.name;

      // Convert the file to bytes
      List<int> fileBytes = await File(filePath).readAsBytes();

      // Get the temporary directory
      final cacheDir = await getTemporaryDirectory();
      final fileUri = cacheDir.uri.resolve(fileName);
      final file = await File.fromUri(fileUri).create(recursive: true);

      // Write bytes to the file
      await file.writeAsBytes(fileBytes, flush: true);

      return [file.uri.toString()];
    }

    return [];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("TRSP"),
        centerTitle: true,
      ),
      body: Stack(
        children: [
          WebViewWidget(controller: controller),
          if (progress != 100)
            Center(
              child: CircularProgressIndicator(),
            ),
        ],
      ),
    );
  }
}
this is my code

**Comment by Mustakim-final** [comment]
please solve  my problem

**Comment by danagbemava-nc** [comment]
Hi @Mustakim-final, the cleartextTraffic key should go in the `application` tag and not the `activity` tag. 

This is an issue with your configuration. The network security config should also go in the `application` tag and not the `activity` tag

**Comment by Mustakim-final** [comment]
thank you solve it
