### ISSUE TITLE
Keyboard dismisses in landscape orientation on changing TextFields

### ISSUE THREAD

**Issue by iak-a-dev** [flutter/flutter#154398]
There are already two issues related to this, but they were closed for some reason, even though the problem is still relevant
https://github.com/flutter/flutter/issues/152620 
https://github.com/flutter/flutter/issues/148673

### Steps to reproduce

Steps to reproduce
Use a phone/tablet in landscape orientation
Focus the first TextField
Go to the next TextField with keyboard or click on the next TextField.
Keyboard disappears, while in flutter 3.19.2 or before it worked fine.
The problem persists in flutter 3.24.1

### Expected results

It is expected that the keyboard also stays visible if the focus goes to the next TextField when the phone is in in landscape orientation.

### Actual results

In landscape orientation the keyboard disappears when the next TextField gets focus.
You need to click the TextField again to show the keyboard.

**Comment by darshankawar** [comment]
> #152620
> #148673

@iak-a-dev The fixes for above don't seem to be in 3.24 per [release notes](https://docs.flutter.dev/release/release-notes/release-notes-3.24.0), so it may not be in stable yet.
Can you re-run your scenario in latest master to check if it persists on it or not ?

**Comment by ihorkozar** [comment]
@darshankawar Yes, everything works as it should in the master channel. Is there any understanding of when these changes will be in the stable version ? 
Because this is quite a noticeable problem for users, and using the master in production is a very risky practice due to its possible instability

**Comment by darshankawar** [comment]
> Is there any information on when these changes will be available in the stable version?

You may read about rolling out fixes from master -> beta -> stable here : https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-build-release-channels.md#flutters-channels

Also, /cc @bleroux for thoughts as he worked on fixing the listed issues.

**Comment by ihorkozar** [comment]
@darshankawar @bleroux Thank you for clarifying the current status. Do I understand correctly that these changes are already in the beta channel (3.25.0-0.1.pre) ?

**Comment by bleroux** [comment]
Yes, this fix is part of [3.25.0-0.1.pre](https://github.com/flutter/flutter/releases/tag/3.25.0-0.1.pre).

(it was fixed by a flutter/engine PR which rolled into flutter/flutter in the following commit: https://github.com/flutter/flutter/commit/c03f9955fa34ed557635b65b5702b9cf891dfd51).

**Comment by darshankawar** [comment]
Closing as this works in beta and master.
