### ISSUE TITLE
Ability to change the name of the APK/IPA when building

### ISSUE THREAD

**Issue by Adrianogba** [flutter/flutter#154442]
### Use case

Currently on Android and iOS the default name of the final artifacts is something like:
```
app-release.aab
app-release.apk
Runner.app
MyApp.ipa
```
It's generic and with the name only I can't distinguish the version on where it came from. Specially on "whitelabel" projects, that can generate many artifacts for different clients or modules.

### Proposal

But both Gradle and the Info.plist containg ways to change the name of the final artifact.
I haven't used the one for iOS, but on Android I've used a configuration to change the name to include a variant and version, so the final package would be generated with a name that would make clear which version it is. Like:
```
MyCustomApp-v1.3.2.apk
MyProduct_ClientName_v3.2.1.apk
```

For Android would be something like the below:
```
android {
  tasks.whenTaskAdded {
    val newFileName = "${baseName}_${apkVersionName()}"
    doLast {
      val apkFile = outputs.files.files.last().listFiles().find { it.extension == "apk" }
        ?: throw RuntimeException("APK file not found")
      apkFile.renameTo(File(apkFile.parent, "$newFileName.apk"))
    }
  }
}
```
For iOS I've readed that this are the variables on the Info.plist to change in order to change the name of the final artifact:
```
<key>CFBundleDisplayName</key>
<string>MyApp</string>
<key>CFBundleName</key>
<string>MyApp</string>
```

**Comment by darshankawar** [comment]
@Adrianogba 
Can you check if [this](https://stackoverflow.com/questions/75285030/how-to-change-the-name-of-package-apk-installer-in-flutter) helps in your case or not ?

**Comment by jmagman** [comment]
I know this doesn't actually address your request, but you may also find these project name instructions helpful if you're juggling a lot of very similar projects: https://github.com/flutter/flutter/issues/9767#issuecomment-1533771721
