### ISSUE TITLE
Proposal: breaking(?) change to material_color_utilities

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#154494]
I noticed something while working on https://github.com/flutter/flutter/issues/150751:

| schema    | mutability |
|-----------|------------|
| RGB color | immutable  |
| HSL color | immutable  |
| HSV color | immutable  |
| HCT color | mutable    |

I personally would find it very satisfying if all these color classes followed a immutable/declarative style (especially since the setters for hue/chroma/tone are set up to reconfigure the entire object anyway).

For example, since `MaterialApp` has an `AnimatedTheme`, updating the `seedColor` means that 40+ HCT colors are being configured each frame: it'd be great to make that process as efficient as possible.

The [material-color-utilites](https://github.com/material-foundation/material-color-utilities/tree/main) repo contains implementations in Dart, C++, Swift, Java, and TypeScript, so my guess would be that if a change to the Dart package doesn't break anything in Flutter then it's probably fine. But I thought I'd post this issue to double-check :)

**Comment by Piinks** [comment]
This should be moved to https://github.com/material-foundation/material-color-utilities/issues
