### ISSUE TITLE
Move FlutterLogo out of the Material library

### ISSUE THREAD

**Issue by victorsanni** [flutter/flutter#154448]
### Use case

FlutterLogo is in the Material library, but has no Material dependencies/opinions. So it makes sense to move it out of the Material library.

Also, [CupertinoContextMenu's examples](https://api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html?_gl=1*11gn7bu*_ga*ODkwNDg2NzQxLjE3MTM5OTkwNDQ.*_ga_04YGWK0175*MTcyNTA0NTMzOS4xMzkuMS4xNzI1MDUwMTA3LjAuMC4w) imports the Material library because of FlutterLogo. This move can help remove that import.

### Proposal

Move FlutterLogo out of the Material library.

**Comment by tavindersingh** [comment]
Hi @victorsanni, I have raised PR for this issue https://github.com/flutter/flutter/pull/154634. Can you please review it and let me know if any other changes are required.

Thanks

**Comment by SohanRaidev** [comment]
Hi,
I’ve submitted a pull request #154711 that addresses the issue of moving FlutterLogo out of the Material library.
Please review the pull request and let me know if there are any issues or further adjustments needed.

Thanks!
