### ISSUE TITLE
path_provider v2.1.4 return wrong download folder in android

### ISSUE THREAD

**Issue by toknT** [flutter/flutter#154472]
### Steps to reproduce

1.  run `Directory? directory = await getDownloadsDirectory();`
2.  print `directory.path`

### Expected results

it should return  `/storage/emulated/0/Download`

### Actual results

it return `/storage/emulated/0/Android/data/com.example.app/files/downloads`

### Code sample

 repo to re producte it : https://github.com/toknT/flutter_path_provider_error_demo

<details open><summary>Code sample</summary>

```dart
Directory? directory = await getDownloadsDirectory();
      if (directory != null) {
        return directory.path;
      }```

</details>


### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details open><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.22.3, on Microsoft Windows [Version 10.0.22631.4037], locale ja-JP)
    ! Flutter version 3.22.3 on channel [user-branch] at C:\src\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (3 available)
[!] Network resources
    ✗ A network error occurred while checking "https://pub.dev/": セマフォがタイムアウトしました。

    ✗ A network error occurred while checking "https://storage.googleapis.com/": Failed host lookup:
      'storage.googleapis.com'
    ✗ A network error occurred while checking "https://maven.google.com/": Failed host lookup: 'maven.google.com'
    ✗ A network error occurred while checking "https://cocoapods.org/": Failed host lookup: 'cocoapods.org'
    ✗ A network error occurred while checking "https://github.com/": Failed host lookup: 'github.com'

! Doctor found issues in 4 categories.
```

</details>

**Comment by iapicca** [comment]
> ```
> Flutter (Channel [user-branch], 3.22.3
> ```

does this occur with the latest stable?

**Comment by darshankawar** [comment]
> ### Actual results
> it return `/storage/emulated/0/Android/data/com.example.app/files/downloads`

@toknT This seems to be correct. Per https://pub.dev/documentation/path_provider/latest/path_provider/getDownloadsDirectory.html, it says `Path to the directory where downloaded files can be stored.`, so in the case, it stores the downloaded files at said location. 

I also get below path:

<img width="213" alt="Screenshot 2024-09-02 at 2 06 09 PM" src="https://github.com/user-attachments/assets/b313561d-0e3a-4204-a28b-fbd3138f145d">

**Comment by toknT** [comment]
> > ### Actual results
> > it return `/storage/emulated/0/Android/data/com.example.app/files/downloads`
> 
> @toknT This seems to be correct. Per https://pub.dev/documentation/path_provider/latest/path_provider/getDownloadsDirectory.html, it says `Path to the directory where downloaded files can be stored.`, so in the case, it stores the downloaded files at said location.
> 
> I also get below path:
> 
> <img alt="Screenshot 2024-09-02 at 2 06 09 PM" width="213" src="https://private-user-images.githubusercontent.com/67046386/363620376-b313561d-0e3a-4204-a28b-fbd3138f145d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjgxMjMsIm5iZiI6MTcyNTI2NzgyMywicGF0aCI6Ii82NzA0NjM4Ni8zNjM2MjAzNzYtYjMxMzU2MWQtMGUzYS00MjA0LWEyOGItZmJkMzEzOGYxNDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA5MDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwY2JkZWRlZjYzMmZkOTMyM2EwN2I5MzQ0M2MyMTVjZGY1ZGYzMmMzOGZhYTI3NTE3N2FhYWE2MmNjZWExZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iksO9VB7NrUSFJ3yRDa2BmXH4DfD9yZG9mpFV4bx7wU">

So it not return the global downloads folder in Android ever?I used that to save pdf file to downloads folder. it was ok, but after Auguest's updated it not return that.

**Comment by darshankawar** [comment]
> but after Auguest's updated it not return that.

This is the latest change in the plugin: https://pub.dev/packages/path_provider/changelog#214 and related issue : https://github.com/flutter/flutter/issues/142518

**Comment by darshankawar** [comment]
@BuyMyBeard 
This is a closed issue. I see you have filed a new issue, so we will add applicable labels after triaging it.

**Comment by BuyMyBeard** [comment]
> @BuyMyBeard This is a closed issue. I see you have filed a new issue, so we will add applicable labels after triaging it.

That's not my point. I just want this issue to have the relevant labels, which it doesn't.

**Comment by darshankawar** [comment]
We don't add applicable labels unless we complete triage on issues. In this case, the issue was closed by OP before completing triage.

**Comment by toknT** [comment]
Sorry I find I am using `external_path` in another feature of my application not `path_provider` . So I close it. @darshankawar
