### ISSUE TITLE
Android platform view autofill doesn't work

### ISSUE THREAD

**Issue by FaFre** [flutter/flutter#154495]
### Steps to reproduce

1. Running the official example from https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter/example 
2. Scroll down the flutter page to the social media buttons
3. Open github.com, then navigate to sign-in

### Expected results

My password manager offers to fill credentials.

### Actual results

Password manager will not pop up.

There has been some issues that apparently fixed this in the past:
- https://github.com/flutter/flutter/issues/92165
- The suggested fix is now also in master: https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/android/FlutterView.java#L391
- https://github.com/flutter/engine/pull/40771

The problem exists at least on latest master and stable

### Code sample

I encountered this issue at first in my small example with android platform view: https://github.com/flutter/packages/tree/main/packages/webview_flutter/ 

I could then replicate it with the web view example: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter/example 

So, it seems to be a problem with the platform view itself, that's why I didn't tag `webview_flutter` itself.

I also tried to raise the minSdk to 26 to fix possible side effects (since sdk 26 is required by https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/android/FlutterView.java#L391), but no change.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/487b3a9c-b0a0-4a44-bd25-ee6b88f2ec43

Example on a Firefox (same device, how it is expected):

https://github.com/user-attachments/assets/c21b4e87-1bdc-424b-bfd5-086dee45806e

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.25.0-1.0.pre.219, on Manjaro Linux 6.6.46-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.25.0-1.0.pre.219 on channel master at /home/fafre/Software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6fe09872b1 (2 days ago), 2024-08-30 19:53:11 -0400
    • Engine revision 2d56e44888
    • Dart version 3.6.0 (build 3.6.0-198.0.dev)
    • DevTools version 2.39.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Connected device (3 available)
    • M2012K11AG (mobile) • 859ef07c • android-arm64  • Android 14 (API 34)
    • Linux (desktop)     • linux    • linux-x64      • Manjaro Linux 6.6.46-1-MANJARO
    • Chrome (web)        • chrome   • web-javascript • Chromium 128.0.6613.84 Arch Linux

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @FaFre 
Can you also try with another device (just to make sure it isn't again specific to Poco) ?
I am unable to replicate with the device I tried.

**Comment by FaFre** [comment]
@darshankawar I found the issue, sometimes its explicitly required to call `ViewCompat.setImportantForAutofill(this, View.IMPORTANT_FOR_ACCESSIBILITY_YES)` on nested native views. Problem solved.
