### ISSUE TITLE
Negative spacing in Flex widget

### ISSUE THREAD

**Issue by JakesMD** [flutter/flutter#154410]
### Use case

Most UI design software offers the flexibility of both positive and negative spacing in lists. To address this need in Flutter, I developed the [signed_spacing_flex](https://pub.dev/packages/signed_spacing_flex) package a few years ago. This package is a slightly modified version of Flutter’s `Flex` widget, designed to support both positive and negative spacing between its children.

Recently, Flutter introduced a `spacing` attribute to the `Flex` widget. However, it only allows for positive spacing. The rationale provided for this limitation was that overlapping elements should be handled by the `Stack` widget.

I respectfully disagree with this approach. Creating a clean, overlapping list using a `Stack` is not only cumbersome but also less intuitive compared to using a `Flex` widget with signed spacing.

### Proposal

- allow `spacing` attribute to be negative
- add an overlapping order attribute: first child overlaps last child vs last child overlaps first child

![](https://raw.githubusercontent.com/JakesMD/signed_spacing_flex/main/preview.gif)

**Comment by darshankawar** [comment]
@JakesMD 
There's a similar issue open describing your case https://github.com/flutter/flutter/issues/25042, so please follow-up in it for further updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
