### ISSUE TITLE
Creating flutter projects take too long time and doesn't complete

### ISSUE THREAD

**Issue by el-ghnnam** [flutter/flutter#154478]
### Steps to reproduce

1. when i want to create flutter project using IDEs or flutter tools "flutter create porject_name" i stuck in reslolve dependencies 
it takes long time more than 30 minutes and doesn't complete

### Actual results

![Screenshot 2024-09-01 000400](https://github.com/user-attachments/assets/6aef1188-100f-4812-bbf9-e3d99a2a364f)

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```
![Screenshot 2024-08-31 235919](https://github.com/user-attachments/assets/2767917f-da6a-4a10-b929-87ae0819f719)

</details>

**Comment by danagbemava-nc** [comment]
Hi @el-ghnnam, please provide the full output of `flutter create <foo> -v`. The output may be huge so kindly put it into a .txt file and attach it here. 

Please also upgrade to stable 3.24.1 to see if you still experience this issue. 

Thank you

**Comment by champ96k** [comment]
@el-ghnnam try this cmd then re-run.

```dart
killall -9 dart    
```

**Comment by el-ghnnam** [comment]
> Hi @el-ghnnam, please provide the full output of `flutter create <foo> -v`. The output may be huge so kindly put it into a .txt file and attach it here where `<foo>` is the name of the project
> 
> Please also upgrade to stable 3.24.1 to see if you still experience this issue.
> 
> Thank you

[New Text Document.txt](https://github.com/user-attachments/files/16843843/New.Text.Document.txt)
> Project successfully created. but in some cases i don't know why, when i create new one it stuck in resolving dependencies take more than 30 mintues.

**Comment by el-ghnnam** [comment]
> @el-ghnnam try this cmd then re-run.
> 
> ```dart
> killall -9 dart    
> ```

my main OS is Windows

**Comment by danagbemava-nc** [comment]
Hi @el-ghnnam, according to the logs provided in https://github.com/flutter/flutter/issues/154478#issuecomment-2325628882, the command completed as expected. Did you change do anything before re-running the command?

**Comment by el-ghnnam** [comment]
> Hi @el-ghnnam, according to the logs provided in [#154478 (comment)](https://github.com/flutter/flutter/issues/154478#issuecomment-2325628882), the command completed as expected. Did you change do anything before re-running the command?

convert to stable mode.
but the actual problem is that any resolving dependencies take long time even if i run dart pub upgrade --major-versions.

**Comment by huycozy** [comment]
>but the actual problem is that any resolving dependencies take long time even if i run dart pub upgrade --major-versions.

This could be a network issue. Can you check with `--offline` mode to see any difference? (`flutter create --offline helloworld`)

**Comment by el-ghnnam** [comment]
> > but the actual problem is that any resolving dependencies take long time even if i run dart pub upgrade --major-versions.
> 
> This could be a network issue. Can you check with `--offline` mode to see any difference? (`flutter create --offline helloworld`)
It is indeed an internet problem, so thanks for everything.
