### ISSUE TITLE
Inconsistent Selection Behavior Across Multiple SelectableText Widgets

### ISSUE THREAD

**Issue by usmanovrustam** [flutter/flutter#154487]
### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('SelectableText Issue'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SelectableText(
                "HEY, ",
                style: TextStyle(fontSize: 18),
              ),
              SelectableText(
                "Bro\n",
                style: TextStyle(fontSize: 18),
              ),
              SelectableText(
                "How Are you?",
                style: TextStyle(fontSize: 18),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

- Run the app on an MacOs or Web.
- In the app, try to select the word “HEY” from the first SelectableText widget.
- Without clearing the selection, try to select the word “Bro” from the second SelectableText widget.
- Observe that the selection on “HEY” is automatically cleared.
- Now, select the word “Bro” again and then try to select “How Are you?” from the third SelectableText widget.
- Notice that the selection on “Bro” is not cleared when selecting the text from the third SelectableText widget.

### Expected results

Expected Results

When selecting text across multiple SelectableText widgets:

**Consistent Behavior:** The selection behavior should be consistent across all SelectableText widgets.

_Option 1: If a new selection is made in a different SelectableText widget, the previous selection should automatically be cleared. 
Option 2: Alternatively, if multiple selections are allowed, all selected text across different SelectableText widgets should remain highlighted and selectable._

**User Experience:** The user should experience a seamless and intuitive text selection process without unexpected clearing of previous selections when interacting with different SelectableText widgets.

### Actual results

https://github.com/user-attachments/assets/3a9ddcb9-5608-451f-8d0e-4b5db33a3796

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-UZ)
    • Flutter version 3.24.0 on channel stable at /Users/rustamusmanov/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (5 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rustamusmanov/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/rustamusmanov/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/rustamusmanov/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • Rustam Usmanov’s iPhone (mobile) • ***************************            • ios            • iOS 17.6.1 21G93
    • iPhone 15 Pro (mobile)           • *****************************• ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • macOS (desktop)                  • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop)  • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                     • chrome                               • web-javascript • Brave Browser 127.1.68.141

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@usmanovrustam 
I tried the same in macOS desktop using latest stable version (3.24.1) and was able to select all text without previous text getting cleared, as below:


https://github.com/user-attachments/assets/04906455-d0ac-484b-81a4-c7d8db3a11de

**Comment by usmanovrustam** [comment]
@darshankawar Thank you for paying attention to my question. As you know, other macOS/Web/Desktop applications do not have this problem. If you select the words/letters you wanted one by one in all the lines and press CMD+C(copy button), you will get the word you selected last. other words just seem marked. In addition, in order to unselect the selected text, you only need to click on the same text again. which is rather inconvenient

**Comment by darshankawar** [comment]
> * In the app, try to select the word “HEY” from the first SelectableText widget.
> * Without clearing the selection, try to select the word “Bro” from the second SelectableText widget.
> * Observe that the selection on “HEY” is automatically cleared.
> * Now, select the word “Bro” again and then try to select “How Are you?” from the third SelectableText widget.
> * Notice that the selection on “Bro” is not cleared when selecting the text from the third SelectableText widget.

Thanks for the update. I verified this using latest stable and running on macOS desktop, but observed that above occurs only if there's only one `SelectableText` and all text is in it.

Per my earlier verification, with multiple SelectableText, I was able to select different text without previous text getting cleared.

I though observed that, with multiple `SelectableText`, and selecting all text, the copy paste only shows the last text as you mentioned. This doesn't occur with single SelectableText, wherein, entire text is pasted properly.

So would you like consider / restrict this issue only to copy paste behavior ? Because the actual results you mentioned were not replicable per my verification.

**Comment by usmanovrustam** [comment]
I would like to ask you to consider the issue. The main problem I have is not copy/paste, but when I click on another field after the text is selected, it is not automatically unfocused.

**Comment by darshankawar** [comment]
See if you are hitting https://github.com/flutter/flutter/issues/142040 or not.

**Comment by usmanovrustam** [comment]
> See if you are hitting #142040 or not.

No, It is not.

Let me explain: 

https://github.com/user-attachments/assets/feb325b0-f30c-4846-9b58-06a6229c70cc

**Problem 1:** After selecting the text in this video, I clicked on a different area several times. But the text is not unselected. exactly, it became unselected when I clicked on that text.

**Problem 2:** if I select another text after selecting one text, the first selected text is not automatically unselected.

the video below is exactly the result I wanted: 

https://github.com/user-attachments/assets/71bfb929-a5c1-47a6-8cc3-b20b732e985c

**Comment by darshankawar** [comment]
Thanks for the update and patience. I now think you  are hitting https://github.com/flutter/flutter/issues/117573

**Comment by usmanovrustam** [comment]
> Thanks for the update and patience. I now think you are hitting #117573

yes, this is one of the issues I mentioned,
another one is should be deselected automatically after clicking in a different area

**Comment by darshankawar** [comment]
Thanks for the update. I think it can be clubbed with the original issue. You may share your findings in it for better tracking.
Closing this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.

**Comment by usmanovrustam** [comment]
Thanks for updating the issue. I agree only with the second problem I gave that is "When selecting new text, the previously selected text should be automatically deselected", but the first one is not given in the issue you mentioned, could you please leave the issue opened? or should we open new issue for the second one because of covering two problem once?

**Comment by darshankawar** [comment]
> should we open new issue for the second one because of covering two problem once?

Yes, that will help for proper tracking.
