### ISSUE TITLE
Can no longer create an sms with message only (without phone number)

### ISSUE THREAD

**Issue by tom11011** [flutter/flutter#154479]
### Steps to reproduce

1. Write the code as shown in the example
2. Put a message in
3. For phone number, leave it blank

### Expected results

I expected the sms app to launch with no phone number and only the message.  I want the user to enter their own phone number.

### Actual results

Without any number appearing in the phone number, the message does not appear.  The only way to get the message to appear is to have any number in the phone number.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
String? encodeQueryParameters(Map<String, String> params) {
  return params.entries
      .map((MapEntry<String, String> e) =>
          '${Uri.encodeComponent(e.key)}=${Uri.encodeComponent(e.value)}')
      .join('&');
}

final Uri smsLaunchUri = Uri(
  scheme: 'sms',
  path: '',
  queryParameters: <String, String>{
    'body': Uri.encodeComponent('Example Subject & Symbols are allowed!'),
  },
);

launchUrl(smsLaunchUri);

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
`url_launcher` just hands the URL off to the system, which in turn routes it to an application to handle however that application chooses to handle it. If an application is opening but ignoring the `body`, that's an issue with the application handling the URL (in this case presumably your phone app), not with `url_launcher`, so you would need to report this to the developer of that application.
