### ISSUE TITLE
CupertinoMagnifier/CupertinoTextMagnifier is missing example/accompanying test 

### ISSUE THREAD

**Issue by victorsanni** [flutter/flutter#154439]
### Use case

Makes it easier to see CupertinoMagnifier/CupertinoTextMagnifier in action, like RawMagnifier.

### Proposal

Add accompanying example/test

**Comment by RamonFarizel** [comment]
Hi. I would like to work on this one.

**Comment by RamonFarizel** [comment]
I just found this issue while I was investigating it.
https://github.com/flutter/flutter/issues/155275
