### ISSUE TITLE
Flutter web Image.network doesn't show variable image link when work with reCAPTCHA Enterprise and Firebase appcheck for storage

### ISSUE THREAD

**Issue by thcbk** [flutter/flutter#154482]
### Steps to reproduce

1. Go to my flutter web app at ldv.com.vn
2. You can see all posts and their respective avatar images are displaying properly in the left of each posts
3. Enforce appcheck for firebase storage in Firebase console
4. After over 15 minutes, go back to ldv.com.vn

### Expected results

The avatar images of posts should show normally as before enforcing appcheck for Firebase storage.

### Actual results

The avatar images that come from Image.network(post.headlineImageUrl, fit: BoxFit.fitHeight,) where post.headlineImageUrl is a variable String that point to an image link in my Firebase storage.

For each not shown Image.network call, I receive a warning in debug console like this:

DartError: HTTP request failed, statusCode: 401, https://firebasestorage.googleapis.com/v0/b/luyendonglaocai-thc.appspot.com/o/tuyen-dung%2FImages%2FVHTT.jpg?alt=media&amp;token=cd1a41b6-88f4-45b2-b09d-4ec74c204052

### Code sample

<details open><summary>Code sample</summary>

Here is the code to display the avatar image that comes with each post:
```dart
Image.network(post.headlineImageUrl, fit: BoxFit.fitHeight,)
```

Where
```dart
post.headlineImageUrl
```
is a variable String that point to an image link in my Firebase storage.

Here is the code to display the default avatar image (this is still showing normally)
```dart
Image.network(logoUrl, fit: BoxFit.fitWidth,),
```
where logoUrl is a constant:

'https://firebasestorage.googleapis.com/v0/b/luyendonglaocai-thc.appspot.com/o/Images%2FLogo%202.jpg?alt=media&token=175238e1-2ee0-429a-be99-ac1833c370f1';

</details>

So I can conclude that Image.network just be able to show constant link image when working with reCAPTCHA Enterprise and Appcheck. It doesn't show variable image link.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Before enforce appcheck for Firebase storage:
![before enforce appcheck for storage](https://github.com/user-attachments/assets/14e306fb-c11f-4b6d-b1bc-61e5ce992dd4)

After enforce appcheck for Firebase storage:
![after enable appcheck for storage](https://github.com/user-attachments/assets/4370c7a2-6c14-40b0-b8b8-04755b58fa1f)

Here is avatar image with constant link, it still shows:

![avatar image with constant link](https://github.com/user-attachments/assets/283375e6-dd32-4297-9e24-27e5a5f4df02)

Firebase firestore shows that all request are verified
![firestore](https://github.com/user-attachments/assets/5365b704-0034-4c9a-8615-8936abc5d380)

But Firebase storage shows that all request are unknown, so they will be denied and flutter can't display them.

Maybe there's a bug in flutter framework that send request in the case of Image.network(variable link).

![storage](https://github.com/user-attachments/assets/733a18d0-9957-45b8-9816-6da928923494)

</details>

### Logs

<details open><summary>Logs</summary>

```console
Another exception was thrown: [object ProgressEvent]
DartError: HTTP request failed, statusCode: 401, https://firebasestorage.googleapis.com/v0/b/luyendonglaocai-thc.appspot.com/o/home%2FRa%20m%E1%BA%AFt%20ph%C3%B2ng%20s%C3%A1t%20h%E1%BA%A1ch%20ki%E1%BA%BFn%20th%E1%BB%A9c%20ATVSL%C4%90%20v%C3%A0%20%E1%BB%A9ng%20d%E1%BB%A5ng%20t%E1%BB%B1%20%C3%B4n%20t%E1%BA%ADp%20ATVSL%C4%90%20tr%C3%AAn%20%C4%91i%E1%BB%87n%20tho%E1%BA%A1i%20th%C3%B4ng%20minh%20%2F1.jpg?alt=media&amp;token=df528d8b-f349-4752-a749-5aabe11ba3c9

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4780], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Professional 2019 16.11.38)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++"       
      workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[!] Android Studio (not installed)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by iapicca** [comment]
> ### Steps to reproduce
> 1. Go to my flutter web app at ldv.com.vn
> 2. You can see all posts and their respective avatar images are displaying properly in the left of each posts
> 3. Enforce appcheck for firebase storage in Firebase console
> 4. After over 15 minutes, go back to ldv.com.vn

@thcbk 
- step 2 is not happening in my case, see screenshot below
- not sure how I'm supposed to trigger step 3

I'm not sure this is an issue with flutter itself or a problem in your implementation,
it would be best if you could provide a **_minimal reproducible code sample_**


<img width="1437" alt="image" src="https://github.com/user-attachments/assets/c41974fe-bb28-4138-9723-ad31c5644eaf">

**Comment by thcbk** [comment]
> > ### Steps to reproduce
> > 
> > 1. Go to my flutter web app at ldv.com.vn
> > 2. You can see all posts and their respective avatar images are displaying properly in the left of each posts
> > 3. Enforce appcheck for firebase storage in Firebase console
> > 4. After over 15 minutes, go back to ldv.com.vn
> 
> @thcbk
> 
> * step 2 is not happening in my case, see screenshot below
> * not sure how I'm supposed to trigger step 3
> 
> I'm not sure this is an issue with flutter itself or a problem in your implementation, it would be best if you could provide a **_minimal reproducible code sample_**
> 
> <img alt="image" width="1437" src="https://private-user-images.githubusercontent.com/45637986/363471460-c41974fe-bb28-4138-9723-ad31c5644eaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzgzMDEsIm5iZiI6MTcyNTE3ODAwMSwicGF0aCI6Ii80NTYzNzk4Ni8zNjM0NzE0NjAtYzQxOTc0ZmUtYmIyOC00MTM4LTk3MjMtYWQzMWM1NjQ0ZWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA4MDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZThiZGZiZGM1MDJlOTM1OWU5Mjg1YTdiMzc1YmVhZjcwODU0MTYwZmY5OGE5ZjYyNTIzYjBlZGE5NWE1MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCKVCev0QyMYHcGQ8syv5Kuv9EneWptP2N-d_fwqRTI">

Hello,
you see that situation because I'm enforcing appcheck for Storage. Now I'm going to to unenforcing appcheck and you will see the avatar images shown normally after 15 minutes from now.

**Comment by iapicca** [comment]
> > > ### Steps to reproduce
> > > 
> > > 1. Go to my flutter web app at ldv.com.vn
> > > 2. You can see all posts and their respective avatar images are displaying properly in the left of each posts
> > > 3. Enforce appcheck for firebase storage in Firebase console
> > > 4. After over 15 minutes, go back to ldv.com.vn
> > 
> > 
> > @thcbk
> > 
> > * step 2 is not happening in my case, see screenshot below
> > * not sure how I'm supposed to trigger step 3
> > 
> > I'm not sure this is an issue with flutter itself or a problem in your implementation, it would be best if you could provide a **_minimal reproducible code sample_**
> 
> Hello, you see that situation because I'm enforcing appcheck for Storage. Now I'm going to to unenforcing appcheck and you will see the avatar images shown normally after 15 minutes from now.

I see that,
but note that there a **firebase error** in the logs
this seems to point to a possible problem with your implementation
rather than an issue with flutter

please provide a **_minimal code sample_** to reproduce the issue



<img width="1431" alt="image" src="https://github.com/user-attachments/assets/e18a9794-b67b-4b6e-87ec-0327ab467689">

**Comment by thcbk** [comment]
> > > > ### Steps to reproduce
> > > > 
> > > > 1. Go to my flutter web app at ldv.com.vn
> > > > 2. You can see all posts and their respective avatar images are displaying properly in the left of each posts
> > > > 3. Enforce appcheck for firebase storage in Firebase console
> > > > 4. After over 15 minutes, go back to ldv.com.vn
> > > 
> > > 
> > > @thcbk
> > > 
> > > * step 2 is not happening in my case, see screenshot below
> > > * not sure how I'm supposed to trigger step 3
> > > 
> > > I'm not sure this is an issue with flutter itself or a problem in your implementation, it would be best if you could provide a **_minimal reproducible code sample_**
> > 
> > 
> > Hello, you see that situation because I'm enforcing appcheck for Storage. Now I'm going to to unenforcing appcheck and you will see the avatar images shown normally after 15 minutes from now.
> 
> I see that, but note that there a **firebase error** in the logs this seems to point to a possible problem with your implementation rather than an issue with flutter
> 
> please provide a **_minimal code sample_** to reproduce the issue
> 
> <img alt="image" width="1431" src="https://private-user-images.githubusercontent.com/45637986/363491374-e18a9794-b67b-4b6e-87ec-0327ab467689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU4NDcsIm5iZiI6MTcyNTI2NTU0NywicGF0aCI6Ii80NTYzNzk4Ni8zNjM0OTEzNzQtZTE4YTk3OTQtYjY3Yi00YjZlLTg3ZWMtMDMyN2FiNDY3Njg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4MjU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNTlmNjBhMmIxN2JhN2YxOTYxMmJlZDI0NmQ3Yjk5MDg4YjUxZmU5MTEzOTFjYzk4M2RiNDY5MzU2NTYyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F7bWoL7UigY1mRqadEFm2l2FheJhKDSnssbeMrI2smU">

okay I will make a small project to reproduce the error in the next few days

**Comment by thcbk** [comment]
Hello, I fixed it with the help of firebase team.
It's the issue of security of Firebase cloud storage. When enabling Appcheck for storage, Image.network(url) where url is the link to the image in storage does not work. 
The work around is to use a reference to that image:
`Reference httpsImageRef = FirebaseStorage.instance.refFromURL(url);
`
Then get the download link of it:
`httpsImageRef.getDownloadURL()
`

Then you can display the image like this:
```
FutureBuilder(
    future: httpsImageRef.getDownloadURL(),
    builder: (context, snapshot) {
      if(snapshot.hasData){
        return  
        AspectRatio(
          aspectRatio: 1,
          child: 
          ClipRRect(
            borderRadius: BorderRadius.circular(5),
            child:
            Image.network(snapshot.data!, fit: fit,)
          )
        );
      }
      else{
        return
        const Center(child: CircularProgressIndicator());
      }
    },
  );
```

Thanks for your help! You can close the issue now.
