### ISSUE TITLE
Webtransport support

### ISSUE THREAD

**Issue by ugran** [flutter/flutter#154465]
### Use case

Webtransport is actively being implemented across different languages/frameworks. For example socket.io and currently there is no way to establish connections with it.

### Proposal

Please communicate with the dart team to implement webtransport API.

**Comment by iapicca** [comment]
doesn't this belong in the [dart repo](https://github.com/dart-lang/sdk/issues)?

**Comment by ugran** [comment]
> doesn't this belong in the [dart repo](https://github.com/dart-lang/sdk/issues)?
> 

It does, but according to them, they don't plan and don't have resources to implement it.

To me this feature should be important enough for flutter's future development and maybe the flutter team can help them out somehow?

**Comment by darshankawar** [comment]
@ugran 
There's https://pub.dev/documentation/js_bindings/0.1.2+2/webtransport/webtransport-library.html api already that you can check to see if it helps in your case or not.
