### ISSUE TITLE
Camera showing black screen only.( Android )

### ISSUE THREAD

**Issue by nirav4273** [flutter/flutter#15442]
faced same issue in android 6 (Moto E3 ). Only black screen show when code run.

Flutter 0.1.5 ΓÇó channel beta ΓÇó https://github.com/flutter/flutter.git
Framework ΓÇó revision 3ea4d06 (2 weeks ago) ΓÇó 2018-02-22 11:12:39 -0800
Engine ΓÇó revision ead227f
Tools ΓÇó Dart 2.0.0-dev.28.0.flutter-0b4f01f759

Camera plugin version tried : 0.0.4/ 0.03 / 0.1.0 .
Please give me suggestion or way how to fix this issue

**Comment by MichaelSowah** [comment]
I think this is a dupe of [14053](https://github.com/flutter/flutter/issues/14053#issuecomment-372115046)

**Comment by nirav4273** [comment]
Below version from master branch & 0.1.2 camera package working for so close this.

Flutter 0.2.5-pre.57 ΓÇó channel master ΓÇó https://github.com/flutter/flutter.git
Framework ΓÇó revision c5288c7346 (60 minutes ago) ΓÇó 2018-03-28 08:32:27 -0700
Engine ΓÇó revision dd6f46c485
Tools ΓÇó Dart 2.0.0-dev.41.0.flutter-2f68e82526
