### ISSUE TITLE
Advanced code not working on https://codelabs.developers.google.com/codelabs/flutter-codelab-first#8 for some of the other languages

### ISSUE THREAD

**Issue by Shinsieon** [flutter/flutter#154474]
### Steps to reproduce

I wanted to see advanced code on making first app, but that route is not existable.

### Expected results

see code in dartpad

### Actual results

see code in dartpad

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by iapicca** [comment]
it opens without problems for me, are you behind a vpn?

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/de1bf7e8-6293-49a9-b717-174d390e0b19">

<img width="895" alt="image" src="https://github.com/user-attachments/assets/7ec0596c-8182-4167-932a-d21bc749df3e">

**Comment by iapicca** [comment]
> Had the same problem since it didnt have "?id=", ![image](https://private-user-images.githubusercontent.com/180465900/364520533-43997764-013e-4760-a18a-2fbc06039853.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTMzNjQsIm5iZiI6MTcyNTUxMzA2NCwicGF0aCI6Ii8xODA0NjU5MDAvMzY0NTIwNTMzLTQzOTk3NzY0LTAxM2UtNDc2MC1hMThhLTJmYmMwNjAzOTg1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNTExMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjM4MzNlZGI5MTA2MjgyMjUyMjIyZDljZmZhMTNjMDg3YWE4YTBlM2NiZjg3ZDg2MWE4MGJmMjUyNGY5NjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fQbg3jaLVnHE199pop3PxBMufBLSFFCyMXY-Dpfffyk)

@Dasanti19
where is this link in the page?
this one seems correct
<img width="448" alt="image" src="https://github.com/user-attachments/assets/373279b3-6a28-47b0-9dd3-5774fabc5d30">

**Comment by danagbemava-nc** [comment]
Thanks for the hint @Dasanti19, I changed the language to Indonesian and the link was incorrect as well. 

The link is incorrect for the following languages on that page (This is **not** an exhaustive list)

- Indonesia
- Español/Español - (Latin America) 


cc @domesticmouse

**Comment by domesticmouse** [comment]
Googlers: please see cl/673086768

**Comment by domesticmouse** [comment]
This should be fixed shortly.
