### ISSUE TITLE
Gallery App has Steppers

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1544]
From https://www.google.com/design/spec/components/steppers.html#

"Steppers convey progress through numbered steps. They may also be used for navigation."
- [ ] Horizontal
- [ ] Vertical

**Comment by timsneath** [comment]
Steppers are now [archived](https://material.io/archive/guidelines/components/steppers.html). Adding @willlarche in case there's something else we should replace this with, but closing for now.

**Comment by willlarche** [comment]
Steppers are on the long list of components we’d love to revisit. If Material does, you can count on Flutter getting those designs ASAP! For now they are a great opportunity for a community package.

**Comment by timsneath** [comment]
We have the [widget itself](https://api.flutter.dev/flutter/material/Stepper-class.html), but I don't think we need an open bug for the gallery app to add a sample here.

**Comment by willlarche** [comment]
Awesome! I agree.
