### ISSUE TITLE
DropdownMenu throws RangeError when no matching results are found in DropdownMenuEntries

### ISSUE THREAD

**Issue by sprabhdeep** [flutter/flutter#154532]
### Steps to reproduce

Problem can be reproduced using code in flutter docs.
( https://api.flutter.dev/flutter/material/DropdownMenu-class.html )

When you search the icon using TextField of `DropdownMenu` and you enter a icon name which is not present in IconLabel enum but matches a few characters, it shows a RangeError.

### Expected results

An Example Usage: Filter through existing users from database using `DropdownMenu` and if user does not exist add it into database.

So expected result should be filter the entries and if found nothing then don't throw an error, just show empty list or show no Dropdown below textfield.

It was working perfectly fine a couple of flutter versions back. Request you to look at this immediately as live apps are using it.

### Actual results

The error thrown is 
RangeError (index): Index out of range: no indices are valid: 0

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

// Flutter code sample for [DropdownMenu]s. The first dropdown menu
// has the default outlined border and demos using the
// [DropdownMenuEntry] style parameter to customize its appearance.
// The second dropdown menu customizes the appearance of the dropdown
// menu's text field with its [InputDecorationTheme] parameter.

void main() {
  runApp(const DropdownMenuExample());
}

// DropdownMenuEntry labels and values for the first dropdown menu.
enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Orange', Colors.orange),
  grey('Grey', Colors.grey);

  const ColorLabel(this.label, this.color);
  final String label;
  final Color color;
}

// DropdownMenuEntry labels and values for the second dropdown menu.
enum IconLabel {
  smile('Smile', Icons.sentiment_satisfied_outlined),
  cloud(
    'Cloud',
    Icons.cloud_outlined,
  ),
  brush('Brush', Icons.brush_outlined),
  heart('Heart', Icons.favorite);

  const IconLabel(this.label, this.icon);
  final String label;
  final IconData icon;
}

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController colorController = TextEditingController();
  final TextEditingController iconController = TextEditingController();
  ColorLabel? selectedColor;
  IconLabel? selectedIcon;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 20),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    DropdownMenu<ColorLabel>(
                      initialSelection: ColorLabel.green,
                      controller: colorController,
                      // requestFocusOnTap is enabled/disabled by platforms when it is null.
                      // On mobile platforms, this is false by default. Setting this to true will
                      // trigger focus request on the text field and virtual keyboard will appear
                      // afterward. On desktop platforms however, this defaults to true.
                      requestFocusOnTap: true,
                      label: const Text('Color'),
                      onSelected: (ColorLabel? color) {
                        setState(() {
                          selectedColor = color;
                        });
                      },
                      dropdownMenuEntries: ColorLabel.values
                          .map<DropdownMenuEntry<ColorLabel>>(
                              (ColorLabel color) {
                        return DropdownMenuEntry<ColorLabel>(
                          value: color,
                          label: color.label,
                          enabled: color.label != 'Grey',
                          style: MenuItemButton.styleFrom(
                            foregroundColor: color.color,
                          ),
                        );
                      }).toList(),
                    ),
                    const SizedBox(width: 24),
                    DropdownMenu<IconLabel>(
                      controller: iconController,
                      enableFilter: true,
                      requestFocusOnTap: true,
                      leadingIcon: const Icon(Icons.search),
                      label: const Text('Icon'),
                      inputDecorationTheme: const InputDecorationTheme(
                        filled: true,
                        contentPadding: EdgeInsets.symmetric(vertical: 5.0),
                      ),
                      onSelected: (IconLabel? icon) {
                        setState(() {
                          selectedIcon = icon;
                        });
                      },
                      dropdownMenuEntries:
                          IconLabel.values.map<DropdownMenuEntry<IconLabel>>(
                        (IconLabel icon) {
                          return DropdownMenuEntry<IconLabel>(
                            value: icon,
                            label: icon.label,
                            leadingIcon: Icon(icon.icon),
                          );
                        },
                      ).toList(),
                    ),
                  ],
                ),
              ),
              if (selectedColor != null && selectedIcon != null)
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Text(
                        'You selected a ${selectedColor?.label} ${selectedIcon?.label}'),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 5),
                      child: Icon(
                        selectedIcon?.icon,
                        color: selectedColor?.color,
                      ),
                    )
                  ],
                )
              else
                const Text('Please select a color and an icon.')
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on EndeavourOS 6.10.3-arch1-2, locale en_IN)
    • Flutter version 3.24.1 on channel stable at /usr/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (13 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • EndeavourOS 6.10.3-arch1-2
    • Chrome (web)    • chrome • web-javascript • Chromium 127.0.6533.99 Arch Linux

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
@PurplePolyhedron, it seems like this wasn't completely fixed by https://github.com/flutter/flutter/pull/152378. The video below was recorded on the master channel


https://github.com/user-attachments/assets/b23978be-509a-421f-9b21-3cb413482a8b



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
```

```
[!] Flutter (Channel master, 3.25.0-1.0.pre.219, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.25.0-1.0.pre.219 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6fe09872b1 (3 days ago), 2024-08-30 19:53:11 -0400
    • Engine revision 2d56e44888
    • Dart version 3.6.0 (build 3.6.0-198.0.dev)
    • DevTools version 2.39.0
```
</details>

**Comment by PurplePolyhedron** [comment]
This issue should be fix by https://github.com/flutter/flutter/pull/151969 when it lands.

https://github.com/flutter/flutter/issues/151878 was not fixed by https://github.com/flutter/flutter/pull/152378.
It did fix the issue in a earlier version, but relevant changes are reverted in the final version in favour of  https://github.com/flutter/flutter/pull/151969, and I forgot to update the description.

**Comment by PurplePolyhedron** [comment]
In the current master branch, the example no longer crash on entering non-matching text.
However, after entering non-matching text and the menu is empty, pressing "down key" would cause `IntegerDivisionByZeroException` and then entering text would trigger `RangeError`

**Comment by EhsnJmli** [comment]
I've faced another issue with this on flutter 3.24.3 stable channel.

When you enter one character which is not in the dropdown entries, it works fine and not throwing an exception (For example writing 'a' in example below) but when you enter one character like 'f' which has non null result on search and then add a character which will make search result null like 'fa' it will throw RangeError.

Here is the exmple code: 
`DropdownMenu<String>(
                      controller: _controller,
                      enableSearch: true,
                      dropdownMenuEntries: ['first', 'second', 'third'].map((e) => DropdownMenuEntry<String>(value: e, label: e)).toList(),
                      label: Text('find'),
                      menuHeight: 250,
                      requestFocusOnTap: true,
                      enableFilter: true,
),`

This happens because of the currentHighlight check on search method of _DropdownMenuState in line 6.
`  int? search(List<DropdownMenuEntry<T>> entries, TextEditingController textEditingController) {
    final String searchText = textEditingController.value.text.toLowerCase();
    if (searchText.isEmpty) {
      return null;
    }
    if (currentHighlight != null && entries[currentHighlight!].label.toLowerCase().contains(searchText)) {
      return currentHighlight;
    }
    final int index = entries.indexWhere((DropdownMenuEntry<T> entry) => entry.label.toLowerCase().contains(searchText));

    return index != -1 ? index : null;
  }`

to fix this we should check entries.isNotEmpty() after null check of currentHighlight.

Also for temporary fix in your code you can define searchCallback property for your DropdownMenu then it would not go to the search method of its own and throw error.

You can write it like this:
`DropdownMenu<String>(
                      controller: _controller,
                      enableSearch: true,
                      dropdownMenuEntries: ['first', 'second', 'third'].map((e) => DropdownMenuEntry<String>(value: e, label: e)).toList(),
                      label: Text('find'),
                      menuHeight: 250,
                      requestFocusOnTap: true,
                      enableFilter: true,
                      searchCallback: (entries, query) {
                        final String searchText = _controller.value.text.toLowerCase();
                        if (searchText.isEmpty) {
                          return null;
                        }
                        final int index = entries.indexWhere((DropdownMenuEntry<String> entry) => entry.label.toLowerCase().contains(searchText));

                        return index != -1 ? index : null;
                      },
),`

I hope it helps.
