### ISSUE TITLE
Flutter gallery performance test infra failure during 3.24 hotfix 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#154573]
Primary resolution, determine if passing tests are required to publish. 

Linux_build_test flutter_gallery__transition_perf
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf/11866/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf/11867/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf/11868/overview

Linux_build_test flutter_gallery__transition_perf_e2e
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf_e2e/11546/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf_e2e/11547/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf_e2e/11548/overview 

Linux_build_test flutter_gallery__transition_perf_hybrid
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf_hybrid/11565/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf_hybrid/11566/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf_hybrid/11567/overview

**Comment by reidbaker** [comment]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/894441/overview
Failed due to resource exaustion

**Comment by christopherfujino** [comment]
> https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/894441/overview Failed due to resource exaustion

I think that this is because we got rid of all the moto g4 phones, whose batteries were swelling, and replaced them with mokeys.

**Comment by reidbaker** [comment]
@christopherfujino does that mean you think we should consider this infra failure as non blocking for the release?

**Comment by christopherfujino** [comment]
> @christopherfujino does that mean you think we should consider this infra failure as non blocking for the release since we cant do anything to have available resources?
> 
> Or should I look for the infra migration and cherry pick that change as well?

I say we consider it non-blocking, because this is a performance benchmark, not a regression test (and we're not even checking benchmark data on releases), and it would be difficult--although not impossible--to cherry pick the configuration changes. Just landing these on master was incredibly painful.

**Comment by reidbaker** [comment]
Closing as ignoring resource exhausted for these 3 post submit tests.
