### ISSUE TITLE
Android emulator after MacOS wakes up

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#15459]
## Steps to Reproduce

Android emulator looks great, then I put the screen to sleep and walk away. When I return, it looks as you see it. It has forgotten size/scale.

<img width="515" alt="screen shot 2018-03-12 at 2 02 08 pm" src="https://user-images.githubusercontent.com/6293442/37309444-33b4ae4c-25fe-11e8-9768-8ce92e21de74.png">

**Comment by chinmaygarde** [comment]
I don't think this is a Flutter rendering issue. Even system UI elements are resized. Are you on a retina display maybe (though I don't see how we can do anything about it)?

@741g might have thoughts on this.

**Comment by Hixie** [comment]
Have we been able to reproduce this?

**Comment by charafau** [comment]
it also happens to me. if you want to know other step to reproduce, you can unplug external monitor and those scaling issues will occur.

**Comment by chinmaygarde** [comment]
There isn't much we can do in the Flutter engine as this is an Android emulator issue. I found https://developer.android.com/studio/report-bugs#emulator-bugs that has instructions to file bugs against that tracker.
