### ISSUE TITLE
Add dart fix for `Color.opacity` and `Color.withOpacity`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#154572]
https://github.com/flutter/flutter/issues/127855 deprecates `Color.opacity` and `Color.withOpacity`.  We should make a `dart fix` that will automate migrating these to the new APIs (ie `Color.a` and `Color.withValues`).

**Comment by goderbauer** [comment]
This is where our existing dart fixes live: https://github.com/flutter/flutter/tree/master/packages/flutter/lib/fix_data

You can probably use one of those as a blueprint. The readme there also links to the dart fix documentation with more information.

**Comment by gaaclarke** [comment]
@LouiseHsu here is the `dart fix` that I mentioned.  I've sorted my work items left for wide gamut framework and this one doesn't actually need to be done as fast as I was thinking.  If you're interested in it and could get around to it in the next couple of weeks let me know.  (cc @jmagman).
