### ISSUE TITLE
[CP] When shutting down chrome, guard the call to ChromeConnection.getTab 

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#154536]
### Issue Link

https://github.com/flutter/flutter/issues/153064

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/flutter/pull/154380

### Changelog Description

Prevents CLI crashes when shutting down after running a Flutter app on a browser.

### Impacted Users

All Flutter for Web developers

### Impact Description

Impacts development during `flutter run -d <browser>` workflows. Noisy crashes are generated in scenarios where the CLI tool cannot communicate to the browser (e.g. because the user closed the browser before the app finished bootstrapping).

### Workaround

No. There is nothing to do but to ignore the crash output.

### Risk

low

### Test Coverage

yes

### Validation Steps

Create a Flutter app that targets the web. Run `flutter run -d chrome`. Once the app has finished running., press `q` to quit. The CLI should terminate without a crash.

**Comment by itsjustkevin** [comment]
Approved in https://github.com/flutter/flutter/pull/154380
