### ISSUE TITLE
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/win32-3.1.4/lib/src/guid.dart:31:9: Error: Type 'UnmodifiableUint8ListView' not found.

### ISSUE THREAD

**Issue by yamini-chaudhary** [flutter/flutter#154509]
flutter Doctor:
```
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    • Flutter version 3.24.1 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (13 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sanjaypal/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.90.1)
    • VS Code at /Users/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • iPhone 15 (mobile)              • 13D37D19-2C26-46A4-8A71-25DD784A6124 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by usmanovrustam** [comment]
@yamini-chaudhary  Have you tried `flutter clean` and `flutter pub get`?

**Comment by usmanovrustam** [comment]
> > Are you using it for ios/macos? The win32 package is typically used for Windows-specific functionalities, and it’s not intended to be used on iOS or macOS platforms.
> 
> Hi, win32 package is not being used directly in project. It's an indirect dependency I've tried running flutter clean, flutter pub get, and even flutter pub cache repair, but the issue persists only on iOS. Everything works fine on Android. Do you have any suggestions for resolving this issue on iOS?
> 
> Thanks!

Have you tried `flutter pub cache clean`?

**Comment by yamini-chaudhary** [comment]
> > > Are you using it for ios/macos? The win32 package is typically used for Windows-specific functionalities, and it’s not intended to be used on iOS or macOS platforms.
> > 
> > 
> > Hi, win32 package is not being used directly in project. It's an indirect dependency I've tried running flutter clean, flutter pub get, and even flutter pub cache repair, but the issue persists only on iOS. Everything works fine on Android. Do you have any suggestions for resolving this issue on iOS?
> > Thanks!
> 
> Have you tried `flutter pub cache clean`?

yes

**Comment by darshankawar** [comment]
@yamini-chaudhary 
[This](https://github.com/flutter/flutter/issues/153337#issuecomment-2288049840) most probably should resolve your issue. 
Will close this in favor of it for now. If the issue still persist, write in comments and I'll reopen it.

**Comment by yamini-chaudhary** [comment]
> @yamini-chaudhary [This](https://github.com/flutter/flutter/issues/153337#issuecomment-2288049840) most probably should resolve your issue. Will close this in favor of it for now. If the issue still persist, write in comments and I'll reopen it.

Sure, you can close it. The issue was resolved when I replaced the package that had an indirect dependency on `win32`.
