### ISSUE TITLE
Printing to Printers

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#15457]
I was wondering if printing can be supported on Mobile and Desktop.

Reference conversion for Flutter-Desktop:
https://github.com/google/flutter-desktop-embedding/issues/15#issuecomment-372177134

As i understand it, it needs to be a plugin.

Here are the two use cases i have:

1. For a user to be able to make a Print of what they have on the screen for whatever Printer they are targeting ( A4, A3, etc), so they can have a Paper copy. 
- Not sure how to handle the Header Bar.

2. For a developer to be able to generate a PDF, and send that generated PDF to a Printer. 
- I currently am working on a plugin that does data binding to a PDF Template & generates a PDF, so i need to send the generated PDF to a Printer. 

I hope i made myself clear. 

I am interested to see how many people want this.

**Comment by newbie-gk** [comment]
Would be great if it could be connected to a printer. Like for printing receipts :)
+ 1 vote

**Comment by gedw99** [comment]
I read somewhere that you can print on mobile using the share plugin, but have not tried it. 
Also, I am not sure if it just does a screen capture and prints at screen resolution, which would be not good.

**Comment by Ramsdude** [comment]
Grate if it connect directly to printer Bluetooth or wired.

**Comment by z2228391** [comment]
Great! I love it, Here with a[ pdf plugin for flutter ](https://pub.dartlang.org/packages/pdf), it does a lot of what you said. But It needs a UTF8 support for PDF. If you can do it, it will be useful for all different language.

**Comment by torugok** [comment]
![image](https://user-images.githubusercontent.com/1656859/49043593-a8025d00-f1b2-11e8-9021-143c818bd01f.png)
Is this type of print already possible?

**Comment by Botanium** [comment]
I really need this package for thermal printing. It's there any alternative package as of now?

**Comment by SouengKimmeng** [comment]
Yes it would be great if it support with Thermal Printing. 

 +1

**Comment by meanMonk** [comment]
Hey there,
Is any one find way to create pdf and print it using thermal printer in flutter?

**Comment by Sach97** [comment]
Hi guys, I'm not sure if it is the right place but what about integrating the [skia pdf API SkPDF](https://github.com/google/skia/blob/master/site/user/sample/pdf.md) to the engine ? Theoretically we could paint pdfs in dart.

**Comment by andrey-ushakov** [comment]
For printing receipts on a thermal printer (ESC POS) check this [package](https://pub.dev/packages/esc_pos_printer).

**Comment by Eltute11** [comment]
> For printing receipts with a thermal printer (ESC POS) check this [package](https://pub.dev/packages/esc_pos_printer). @andrey-ushakov 

good alternative, but from what I see it only supports WIFI, it does not support bluetooth

**Comment by Mohammad-ezzidden** [comment]
> For printing receipts with a thermal printer (ESC POS) check this [package](https://pub.dev/packages/esc_pos_printer).

Great but it really need to complete the todo list .

**Comment by ilham-fauzi** [comment]
Guys any update about it ?

**Comment by surajkhanal** [comment]
Is there any update about the desktop print support?

**Comment by Blackheart8788** [comment]
goodnight people, hope you are all fine, is there any news on this topic I'm in real need for a plugin that could help me print on Bluetooth thermal printers

**Comment by UnluckyY1** [comment]
hey there u can use this native good that we did for our app to print an image u can take a screenshot for any widget and use this code to connect and print via bluetooth 
github.com/kthirirania/BluePrint

**Comment by Ali-Azmoud** [comment]
Hi
What about embedded printers like `PAX devices`, for example, [A930](https://www.pax.com.cn/traditionalproducts/info.aspx?itemid=210).  Is there a way to communicate with the printer of these devices without writing native code?

**Comment by Joseph-Nathan** [comment]
Hi all,
can any one show me how can in a flutter windows desktop app print to a local printer connect by USB port ??

**Comment by anandsubbu007** [comment]
Is there any update about the desktop (windows) print support?

**Comment by thatsenam** [comment]
Ia there any update about windows printing???

**Comment by fernando-s97** [comment]
Any updates on printing through usb cable in windows?

**Comment by nicolasdangelo90** [comment]
> Any updates on printing through usb cable in windows?

Hi, i can print over usb, but I made an script with qt, that have print support.
I send data to print over web socket server.
I can share if you are interested

**Comment by DavBfr** [comment]
The https://pub.dev/packages/printing package can print to Windows, Linux, macOS, iOS, Android, and Web.

**Comment by nicolasdangelo90** [comment]
Davbfr, yes I saw it, but You can't print directly to printer, always prompt a preview dialog.
Let me know if I wrong.

**Comment by DavBfr** [comment]
@nicolasdangelo90 yes, you can get the printer list and direct print to it.

**Comment by nicolasdangelo90** [comment]
Do you have an example?
it's work on web?
Thanks!!

**Comment by DavBfr** [comment]
@nicolasdangelo90 something like this:
```dart
 Future<void> _printPdf(Uint8List data) async {
    final printers = await Printing.listPrinters();
    print(printers);
    await Printing.directPrintPdf(
        printer: printers.first, onLayout: (_) => data);
  }
```

But unattended print will not be possible with Flutter Web. A random website can't be allowed to use a printer for obvious security reasons.

**Comment by nicolasdangelo90** [comment]
Ok, that is the problem, I'm working on a billing program, and I need an unattended print.
For this reason I made a program in qt, that get the data across web socket.
Sorry for my English.
Let me know if I was not clear

**Comment by badrinadh** [comment]
any package which prints to a USB printer from windows Desktop?

**Comment by DavBfr** [comment]
@badrinadh Just install the driver ant it will work with the package `printing`

**Comment by rezins** [comment]
> @nicolasdangelo90 something like this:
> 
> ```dart
>  Future<void> _printPdf(Uint8List data) async {
>     final printers = await Printing.listPrinters();
>     print(printers);
>     await Printing.directPrintPdf(
>         printer: printers.first, onLayout: (_) => data);
>   }
> ```
> 
> But unattended print will not be possible with Flutter Web. A random website can't be allowed to use a printer for obvious security reasons.

@DavBfr there is an error try call Printing.listPrinters() , its say Unhandled Exception: MissingPluginException(No implementation found for method listPrinters on channel net.nfet.printing) . I'd try search invoke method like this _channel.invokeMethod<List<dynamic>>('listPrinters', params) , then I search again in PrintingHandler.Java there is no call method of listPrinters. can you fix? thanks

**Comment by DavBfr** [comment]
@rezins unfortunately, there is no API on Android to get a list of printers and directly send a job. That's only available on Flutter desktop.

**Comment by rezins** [comment]
> @rezins unfortunately, there is no API on Android to get a list of printers and directly send a job. That's only available on Flutter desktop.

@DavBfr oh ok, Thanks for answering!

**Comment by masmilon** [comment]
@DavBfr 

> @rezins unfortunately, there is no API on Android to get a list of printers and directly send a job. That's only available on Flutter desktop.


From windows: No implementation found for method listPrinters on channel net.nfet.printing

**Comment by DavBfr** [comment]
@masmilon This method exists on Windows. Maybe upgrade your packages/run flutter clean.

**Comment by masmilon** [comment]
> @masmilon This method exists on Windows. Maybe upgrade your packages/run flutter clean.

@DavBfr  Thanks. It works on run "flutter clean". Today whole day I've searching packages to get printer lists from the windows app. And that's the last moment, you saved my full day's effort, Thank you and Alhamdulillah.

**Comment by DavBfr** [comment]
@masmilon  Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by 10urb** [comment]
> I really need this package for thermal printing. It's there any alternative package as of now?

Have you any solution for that? I have currently with this issue.

**Comment by DavBfr** [comment]
@10urb Usually this work: https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin

**Comment by timothyao** [comment]
Is there a way now, to send raw data (string) to a USB printer on a windows desktop machine in Dart, now?

**Comment by DavBfr** [comment]
@timothyao This plugin https://pub.dev/packages/libusb can send raw data to any USB device.

**Comment by timothyao** [comment]
> @timothyao This plugin https://pub.dev/packages/libusb can send raw data to any USB device.

Thanks @DavBfr I came across that package but could not find any example of its usage from Dart, especially for printing.

**Comment by Aman-Kh** [comment]
> 

did you find any way? to do printing with PAX Device?

**Comment by victorruandev** [comment]
Hello everyone! I would like to print a receipt (tax coupon) where the output is an non fiscal printer. Do you have any ideia about how to solve my problem?

**Comment by DavBfr** [comment]
5 comments up: https://github.com/DavBfr/dart_pdf/wiki/Document-Output#using-another-plugin

**Comment by xaldarof** [comment]
> Is there any update about the desktop print support?

Have you found any solution ?

**Comment by stuartmorgan** [comment]
This isn't something that would be built by the Flutter team, so we're going to close this. This is best served by an ecosystem of plugin for different use cases, since "printing" covers a variety of distinct cases (e.g., traditional desktop printers, PoS printers, cloud print services, etc.), and as noted above there are already a number of plugins in this space.
