### ISSUE TITLE
Allow specifying a custom trace buffer size to the timeline.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#15454]
There is no way to specify a custom trace buffer size to the timeline. The default ring buffer size is sometimes too small and enabling the `--trace-startup` to launch the application with the endless trace buffers attempts to read the startup trace.

**Comment by Hixie** [comment]
Does Dart let us control this?

**Comment by chinmaygarde** [comment]
Yes. It is configurable. But, since the time this issue was filed, we have been increasingly moving towards logging to systrace instead and the buffer size specification is already supported there. So the need for this feature is not as pressing as it once was. I am going to close this issue.
