### ISSUE TITLE
Gallery App has Subheaders

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1545]
From https://www.google.com/design/spec/components/subheaders.html#
- [x] List
- [ ] Grid
- [ ] Menu

**Comment by sethladd** [comment]
@HansMuller I can't seem to find examples of these in gallery. Do you know if we show these anywhere? Thanks!

**Comment by sethladd** [comment]
The [Pesto](https://github.com/flutter/flutter/issues/3961) or [Shrine](https://github.com/flutter/flutter/issues/3962) vignettes might use Subheaders.

**Comment by eseidelGoogle** [comment]
We definitely need this.  @HansMuller recommends we punt this from the first version.

**Comment by Hixie** [comment]
The front page has these now. Is that enough, or do we need more?

**Comment by khalithartmann** [comment]
Hello you awesome people!
I just created a Let's Flutter Berlin group on Facebook to bring flutter developers in Berlin together to discuss problems, share ideas and create beautiful things together. If you live in Berlin, it would be awesome if you could join the group 😊! If you don't live in Berlin, feel free to join too! Im grateful for each and every supporter.  

Let's Flutter Berlin: https://www.facebook.com/groups/276520973054067/about/
Sorry for spamming.

**Comment by TahaTesser** [comment]
1. List example doesn't have sub header https://gallery.flutter.dev/#/demo/lists

<img width="807" alt="Screenshot 2020-05-21 at 7 39 26 PM" src="https://user-images.githubusercontent.com/48603081/82568013-d12f5e00-9b9b-11ea-99ae-c1cc3ea7fd2b.png">


2. Grid example also doesn't have sub header https://gallery.flutter.dev/#/demo/grid-lists
3.  Not sure where we need header in menu example but simple menu example has header "Menu item one"
https://gallery.flutter.dev/#/demo/menu

**Comment by guidezpl** [comment]
Closing as obsolete
