### ISSUE TITLE
examples/stocks fails flutter test --preview-dart-2 after dart/engine roll

### ISSUE THREAD

**Issue by aam** [flutter/flutter#15458]
from https://travis-ci.org/flutter/flutter/jobs/352525306 that is running on dart/engine roll(not yet submitted https://github.com/flutter/flutter/pull/15444): 

```
⏩ RUNNING: cd examples/stocks; ../../bin/flutter test --preview-dart-2
00:00 +0: /home/travis/build/flutter/flutter sdk/examples/stocks/test/icon_color_test.dart: - Icon colors
00:01 +1: loading /home/travis/build/flutter/flutter sdk/examples/stocks/test/locale_test.dart
00:02 +1: /home/travis/build/flutter/flutter sdk/examples/stocks/test/locale_test.dart: - Changing locale
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: ?:<zero widgets with text "MERCADO" (ignoring offstage widgets)>
   Which: means none were found but one was expected
When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/travis/build/flutter/flutter%20sdk/examples/stocks/test/locale_test.dart:30:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:61:25)
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:484:19)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:471:14)
#10     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:653:24)
#16     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:651:16)
#17     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:60:24)
#18     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#19     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#23     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#24     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#28     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#29     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#43     _Timer._runTimers (dart:isolate/timer_impl.dart:382:19)
#44     _Timer._handleMessage (dart:isolate/timer_impl.dart:416:5)
#45     _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
(elided 26 frames from class _FakeAsync, package dart:async, and package stack_trace)
This was caught by the test expectation on the following line:
  file:///home/travis/build/flutter/flutter%20sdk/examples/stocks/test/locale_test.dart line 30
The test description was:
Changing locale
```

**Comment by aam** [comment]
cc @a-siva @mraleph

**Comment by aam** [comment]
Running bisect on dart sdk points to https://dart-review.googlesource.com/45520
 d17db1d5f395e153394aec407bf73b9bfa47e33f as the commit that introduced the failure.

@stereotype441 @kmillikin

**Comment by mraleph** [comment]
This looks like an issue in the `intl` package code generation. See `stock_messages_en.dart`:

```dart
class MessageLookup extends MessageLookupByLibrary {
   get localeName => 'en';

   final messages = _notInlinedMessages(_notInlinedMessages);
   static _notInlinedMessages(_) => {
     "market" : MessageLookupByLibrary.simpleMessage("MARKET"),
     "portfolio" : MessageLookupByLibrary.simpleMessage("PORTFOLIO"),
     "title" : MessageLookupByLibrary.simpleMessage("Stocks")
   };
 }
```

Here `messages` are expected to be `Map<String, Function>` based on [what super class declares](https://www.dartdocs.org/documentation/intl/0.15.2/message_lookup_by_library/MessageLookupByLibrary/messages.html). 

At the same time `_notInlinedMessages` is producing `Map<String, dynamic>` because `MessageLookupByLibrary.simpleMessage` returns `dynamic`. 

I am surprised this did not come with `intl` before. Maybe it rings a bell to you @leafpetersen @alanknight ?

**Comment by leafpetersen** [comment]
Filed https://github.com/dart-lang/sdk/issues/32515 to track the missing DDC runtime error, thanks!

**Comment by pu-tu** [comment]
Expected: exactly one matching node in the widget tree
  Actual: ?:<zero widgets with text "0" (ignoring offstage widgets)>
   Which: means none were found but one was expected
Why occur this error?

**Comment by zoechi** [comment]
@pu-tu The provided information doesn't allow to diagnose the problem.
The error message just says that a widget test contains an expectation that is not met.
It is likely that just the test code contains an error.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by fountainhead-gq** [comment]
@pu-tu @zoechi  I have the same issue . 
```
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: ?:<zero widgets with text "0" (ignoring offstage widgets)>
   Which: means none were found but one was expected
```
how to resolve this error ?

**Comment by victorieaedon** [comment]
i guess by rewriting the test logic. cause that error is because the test contains expectation that is not met.

> The following TestFailure object was thrown running a test:

**Comment by victorieaedon** [comment]
> @pu-tu @zoechi I have the same issue .
> 
> ```
> The following TestFailure object was thrown running a test:
>   Expected: exactly one matching node in the widget tree
>   Actual: ?:<zero widgets with text "0" (ignoring offstage widgets)>
>    Which: means none were found but one was expected
> ```
> how to resolve this error ?

i guess by rewriting the test logic. cause that error is because the test contains expectation that is not met.
