### ISSUE TITLE
flutter_assets module path

### ISSUE THREAD

**Issue by jsw-davidhuang** [flutter/flutter#154558]
### Use case

i am writing an native android app to load fluter module, i do as the step below:
1. flutter create --template=module device_panel
2. write my flutter code
3. flutter build bundle --asset-dir=build/flutter_assets
4. copy the flutter_assets to android path: assets
5. load flutter_assets from native code:
```
    private void initLocalflutter(){
        FlutterEngine flutterEngine = new FlutterEngine(this);
// 初始化 FlutterLoader
        FlutterLoader flutterLoader = FlutterInjector.instance().flutterLoader();
        flutterLoader.startInitialization(this);
        flutterLoader.ensureInitializationComplete(this, null);

// 使用默认路径加载资源（即 assets/flutter_assets）
        flutterEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );
//        flutterEngine.getDartExecutor().executeDartEntrypoint(
//                new DartExecutor.DartEntrypoint(
//                        context.getAssets(),
//                        "flutter_assets",
//                        "main"
//                )
//        );
// 缓存引擎，以便稍后使用
        FlutterEngineCache.getInstance().put("my_engine_id", flutterEngine);
    }

 private void jumpFlutter(String pid){
        startActivity(FlutterActivity.withCachedEngine(pid).build(this));
    }
```
6. and it works
7. but when i try to put the flutter in other path which i may download from my server, such as "/data/data/com.ninetech.myapplication/files/flutter_assets"
8. and load with the code
```
private void initAndCacheFlutterEngine(String pid) {
        Log.i(TAG, "initAndCacheFlutterEngine: with "+pid);
        FlutterEngine flutterEngine = new FlutterEngine(this);
        FlutterLoader flutterLoader = FlutterInjector.instance().flutterLoader();
        flutterLoader.startInitialization(this);
        flutterLoader.ensureInitializationComplete(this, null);
        flutterEngine.getDartExecutor().executeDartEntrypoint(
                new DartExecutor.DartEntrypoint(
                        "/data/data/com.ninetech.myapplication/files/flutter_assets",
                        "main"
                )
        );
        FlutterEngineCache.getInstance().put(pid, flutterEngine);
    }

```
9. and it fail
i search a lot of website, and it said flutter did not support load module from custom path, is it true?  it will only support load from project path "assets". how can i load the flutter module from other path? Thanks

### Proposal

if it's true, can i have the proposal to make the flutter module name a custom loading path

**Comment by darshankawar** [comment]
> 9\. and it fail

@jsw-davidhuang Do you get any error when it fails ? Can you provide the same ?

**Comment by jsw-davidhuang** [comment]
[testloadflutter.zip](https://github.com/user-attachments/files/16862802/testloadflutter.zip)
i had update the project, in the project, i put the flutter_assets(generate by other flutter module) to assets folder, then use native code to jump to the flutter module, and it works. but when i move to the app FilePath, such as i move to /data/data/package name/file/flutter_assets,  and the native code cannot jump to flutter module

**Comment by jsw-davidhuang** [comment]
> > 9. and it fail
> 
> @jsw-davidhuang Do you get any error when it fails ? Can you provide the same ?

it samplely show like this:
```
[ActivityRecord{3e1e300 u0 com.ninetech.myapplication/io.flutter.embedding.android.FlutterActivity t27901}#220489](this:0xb400007cd78e18f8,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'ActivityRecord{3e1e300 u0 com.ninetech.myapplication/io.flutter.embedding.android.FlutterActivity t27901}#220489'
```

**Comment by darshankawar** [comment]
Can you check if [this](https://github.com/flutter/flutter/issues/122802) issue resembles your case or not ?

**Comment by fghjhuang** [comment]
> Can you check if [this](https://github.com/flutter/flutter/issues/122802) issue resembles your case or not ?

sadly, it did not help. can you do some survey on this? if we can load flutter module from app internal storage, we can make the plugin working without update again in the app store.  if the answer is still no, i can only use 3rd-party plugin like open webF.

**Comment by darshankawar** [comment]
> if we can load flutter module from app internal storage,

I don't think this is supported or how to do it. I also checked for any reference for such scenario but couldn't find any.

**Comment by fghjhuang** [comment]
> > if we can load flutter module from app internal storage,
> 
> I don't think this is supported or how to do it. I also checked for any reference for such scenario but couldn't find any.

thanks for your help. it's good news it did not support so thought.
