### ISSUE TITLE
Application ID not set on Linux Wayland sessions

### ISSUE THREAD

**Issue by Merrit** [flutter/flutter#154521]
### Steps to reproduce

From a Wayland session:

1. `flutter create --platforms=linux wayland_icons`
2. `cd wayland_icons`
3. Create a `.desktop` file for the application at `~/.local/share/applications/com.example.wayland_icons.desktop` with the following contents:

```
[Desktop Entry]
Version=1.0
Type=Application

Name=Wayland Icons Example
Comment=Demonstration of mapping icons to a Flutter app on Wayland
Categories=Development;

Icon=dialog-question
Exec=wayland_icons
Terminal=false
```

4. `flutter run -d linux`

### Expected results

Window should have the specified icon on the taskbar, task switcher (Alt+Tab / Overview effect / etc), and in the window decorations.

### Actual results

Window has not adopted the correct icons, instead shows a generic Wayland logo

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![before1](https://github.com/user-attachments/assets/b8452bac-e74c-4f44-9f5b-1895fd29dc28)

![before2](https://github.com/user-attachments/assets/381ea5c1-4150-4cd0-a9dc-b7d65a04337d)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on Fedora Linux 40 (KDE Plasma) 6.10.6-200.fc40.x86_64, locale en_US.UTF-8)
    • Flutter version 3.24.1 on channel stable at /home/merritt/Applications/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (13 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/merritt/Applications/tools/android-sdk/sdk/
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/merritt/Applications/tools/android-sdk/sdk
    • Java binary at: /home/merritt/Applications/tools/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.6 (Fedora 18.1.6-3.fc40)
    • cmake version 3.28.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/merritt/Applications/tools/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.96.0

[✓] VS Code (version 1.93.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.94.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 40 (KDE Plasma) 6.10.6-200.fc40.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.113

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

Results consistent on GNOME & KDE.

**Comment by danagbemava-nc** [comment]
Reproducible using the steps outline above. 

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.24.1, on Ubuntu 24.04 LTS 6.8.0-40-generic, locale en_US.UTF-8)
    • Flutter version 3.24.1 on channel stable at /home/daniel/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (13 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
```

```
[!] Flutter (Channel master, 3.25.0-1.0.pre.219, on Ubuntu 24.04 LTS 6.8.0-40-generic, locale en_US.UTF-8)
    • Flutter version 3.25.0-1.0.pre.219 on channel master at /home/daniel/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6fe09872b1 (3 days ago), 2024-08-30 19:53:11 -0400
    • Engine revision 2d56e44888
    • Dart version 3.6.0 (build [3.6.0-198.0.dev](http://3.6.0-198.0.dev/))
    • DevTools version 2.39.0
```
</details>

**Comment by robert-ancell** [comment]
I reproduced here and the issue is the Exec line in the .desktop file - unless you have that binary in your path it's not valid and won't work.

If I change it to:
```
Exec=/tmp/wayland_icons/build/linux/x64/debug/bundle/wayland_icons
```

Then it works.

**Comment by Merrit** [comment]
@robert-ancell 

It does looks like GNOME has some special handling for this, similar to how KDE has special handling to find the icon for the taskbar. However..

- This approach relies on every window manager in Linux implementing a workaround for apps that haven't set their app id correctly
- Setting the Exec path to absolute doesn't work as a solution when the app is packaged in a sandbox, like Flatpak and Snap; the application and the host see different file paths. They expect to associate via the app id, so that absolute paths don't have to be shared between the sandbox boundary
- Absolute paths are more fragile and less portable, and it is generally preferred to use only the executable name when at all possible
- The [solution](https://github.com/flutter/flutter/pull/154522) is a 1-line change in code, and is what applications on Linux are supposed to do

On GNOME, we can use Looking Glass to see that the app id isn't set on Wayland, as it is on X11 (`wayland_icons`, when it should be `com.example.wayland_icons`:

![image](https://github.com/user-attachments/assets/2273bbcc-6cd4-4daf-abf8-9d471fe1c6ab)

On KDE we can use the `KWin debug console`, and see that similarly the `desktopFileName` & `resourceClass` are set to `wayland_icons`, when they should be the app id `com.example.wayland_icons`:

![image](https://github.com/user-attachments/assets/ec4d1255-bc94-42cf-b816-f201d9620312)

![image](https://github.com/user-attachments/assets/97d7831a-7904-4f01-926a-7a0423710a84)
