### ISSUE TITLE
Design doc: Wide gamut framework support

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#154516]
### Document Link

http://flutter.dev/go/wide-gamut-framework

### What problem are you solving?

In 2023 Flutter added support for rendering colors in the Display P3 color space on iOS devices.  This included support for images taken with the device's camera, high quality images from the internet and any programmatically generated content. However, it did not add support for rendering those colors in Flutter widgets.  This is a proposal to make that possible.

See: https://github.com/flutter/flutter/issues/127855

**Comment by gaaclarke** [comment]
This design doc has already gone through the review process.  Closing this issue out.
