### ISSUE TITLE
Default to software rendering on tooling assisted launches on Android emulators.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#15451]
We have had numerous reports of OpenGL context setup failures on Android emulators. As a workaround, the `--enable-software-rendering` flag was added to avoid using OpenGL altogether. However, that flag is opt-in. We should consider making this the default so that the first time user experience during development does not suffer because the Android emulator's OpenGL emulation was incorrectly setup. We already use software rendering on iOS for other reasons.

**Comment by chinmaygarde** [comment]
@eseidelGoogle There isn't much to be done w.r.t to support in the engine for this bug. We just need to device whether to flip the default.

**Comment by eseidelGoogle** [comment]
@cbracken offered a performance concern.  How much slower is the emulator with this on?  Anything noticable?  If there are no other concerns, from others, my recommendation would be to just make this default. :)

We can even print a message saying "Detected emulator, using Software Backend, a GPU backend is available via --use-gpu-backend" if we really want.

FYI @Hixie

**Comment by eseidelGoogle** [comment]
FYI @741g (from the Android Emulator team).

**Comment by chinmaygarde** [comment]
I do believe there are ways to configure an AVD with the right OpenGL emulation options. So, if there is clear documentation that we can point the user to when it comes to configuring one, I would be fine with keeping this as a fallback of last resort. Or, if possible, we can even configure an AVD for the user in the tooling.

Since I am not sure what guidance to give to users when it comes to AVD configuration, switching to software rendering seems like a safe, if slow(er), default.

**Comment by 741g** [comment]
Documentation on emualtor OpenGL config is here:

"Configuring graphics acceleration on the command line" in https://developer.android.com/studio/run/emulator-acceleration.html

**Comment by eseidelGoogle** [comment]
@chinmaygarde @cbracken another way to phrase this question is to assume we were software rendering by default today.  Under what conditions would we consider switching the default to host-gpu backed?  In that imagined scenario we would have early data to suggest that host-gpu backed is buggy and we would want to find ways to mitigate those bugs presumably.

Chrome I know keeps gpu white and black lists for configurations which Skia is known to work/not.  I don't know if the Android Emulator has similar, or if Skia has any known good/bad Android emulator configurations itself.  FYI @jcgregorio

**Comment by 741g** [comment]
Yes, we keep lists of known good/bad GPUs and apply the settings, although it can take more than one launch of the emulator for them to take effect.

**Comment by chinmaygarde** [comment]
> Under what conditions would we consider switching the default to host-gpu backed?

We can default to software rendering and then suggest to the user that the GPU backend might be more performant. Then, point them to a detailed document (via an in-app toast or a console log message) with relevant links to create an acceleration enabled AVD. That way, the first time user experience with Flutter is reliable and users have the option to enable it if they want to.

@741g Is there a suggested mechanism to query this list. It should be possible to automate AVD creation using Flutter tools.

Honestly, I am most concerned about the FTUE being as friction-free as possible.

**Comment by 741g** [comment]
There's no query for the list because we don't expect it to change often.

host
swiftshader_indirect
(Windows) angle_indirect

**Comment by chinmaygarde** [comment]
@eseidelGoogle Can we ensure that the Flutter tooling creates an AVD on behalf of the user using the recommended settings?

**Comment by eseidelGoogle** [comment]
@chinmaygarde I don't know what that command would look like?  FYI @mit-mit

**Comment by chinmaygarde** [comment]
Based on the doc linked by @741g, something like `emulator -avd avd_name -gpu angle_indirect ....`. On this Flutter tooling created AVD, we can enable GPU rendering. On everything else, default to software. I don't know if this is the right way of going about it. Just a thought.

**Comment by eseidelGoogle** [comment]
Can we detect the emulator configuration at runtime and default to software on ones which don't match that (with a warning explaining how to set up one) and only hardware when it matches our expectations?

**Comment by NathanaelA** [comment]
@chinmaygarde @eseidelGoogle -

Fastest rendering is `-host gpu` and it is pure hardware opengl rendering.
the `-gpu angle_indirect` and `-gpu swiftshader_indirect` are both technically software based renderers.   
The `ANGLE` uses a conversion library from opengl to DirectX; so it can technically as fast as hardware in some cases, with a speed hit in conversion from opengl to DirectX calls.  
`SwiftShader` is probably the most compatible FAST software based renderer as it runs on ALL the platforms.

 A couple notes;
1. `SwiftShader` should work on all platforms, `Angle` is Window ONLY!
2. You might be better off using `swiftshader` and `angle` rather than `angle_indirect` and `swiftshader_indirect`.  v27.0.2 is a brand new emulator and the old depreciated flags still work with the new emulator, but not vise-versa, so if you were to use the new `*_indirect` versions it would fail on I believe all of my machines, and I'm pretty sure I did an update fairly recently.  :grinning:    You could do a `emulator -version` to try and parse the emulators version, BUT you need to run it from the android SDK emulator directory; or it probably won't find the qemu and then even fail that simple command...

**Comment by NathanaelA** [comment]
Hmm, that is weird, I just did emulator -version on my emulator and it says it is 27.0.5.0 & 27.1.10.0 -- so I do have newer versions of the emulators...  But when I do emulator -help-gpu it does not list the `_indirect` versions of the flags.   So I don't know if the `_indirect` flags are actually used or not.   I DO know that in my 27.1.10.0 emulator I am using I use the `swiftshader` setting in my config.ini configuration file as that machine did NOT have a hardware gpu.

**Comment by fmatosqg** [comment]
I'd like to bring in my 2 cents,

I'd like to think there are 2 target users on flutter, either experienced Android developers who will want docs and command line options and what not, and people completely new to flutter that already have lots of friction and a long learning curve ahead. And I do notice that the last group could benefit from not having to open Android Studio to even launch emulators, never mind to create one. That should be the golden goal.

I'd favor anything that works out of the box for everybody to be included in the first stable release. Although it's a nuisance if I don't like how much my CPU is used I'd be even more bogged if I have to set up a new PC where it doesn't work straight away. And I'll always know how / where to find docs if at least the decisions are documented.

Also if it doesn't happen in physical devices it's a dev speed trade off, many people are too happy with hot reload that they downplay other issues.

**Comment by zanderso** [comment]
I'm going to close this under the assumption that a decision was made on this. Please feel free to re-open if I'm mistaken.
