### ISSUE TITLE
[go_route] how dynamically hide or show any tab while using the bottom navigation StatefulShellRoute

### ISSUE THREAD

**Issue by VictorJava** [flutter/flutter#154501]
1. I am using the go_router: ^14.2.3 library in my app.
2. The app has a login screen and a main screen with bottom navigation tabs. Let’s say there are three tabs: Section A, Section B, and Section C.
3. I’ve implemented my StatefulShellRoute following the go_router documentation. You can take a look at the implementation here https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/custom_stateful_shell_route.dart
4. After logging in, I need to show 2 or 3 tabs
5. How can I dynamically hide Section C from Section A?

![Screenshot_20240902_124533](https://github.com/user-attachments/assets/46c5fffe-7c77-49a6-b030-622b29eefe9f)

**Comment by darshankawar** [comment]
@VictorJava 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a code assistance issue rather than a bug report or feature request.
