### ISSUE TITLE
Website: Types getting stripped out of docs

### ISSUE THREAD

**Issue by xqwzts** [flutter/flutter#15453]
In the [drawRawPoints](https://docs.flutter.io/flutter/dart-ui/Canvas/drawRawPoints.html) documentation, the following dartdoc:

```dart
  /// See also:
  ///
  ///  * [drawPoints], which takes `points` as a [List<Offset>] rather than a
  ///    [List<Float32List>].
```

Gets rendered as :
>See also:
>
>   drawPoints, which takes points as a List rather than a List.

Similarly for [drawPoints](https://docs.flutter.io/flutter/dart-ui/Canvas/drawPoints.html):

```dart
/// See also:
///
///  * [drawRawPoints], which takes `points` as a [Float32List] rather than a
///    [List<Offset>].
```

Produces:
>See also:
>
>    drawRawPoints, which takes points as a Float32List rather than a List.

It looks like the markdown parser strips the type declaration out, assuming they are HTML tags [the same would happen in this github view if they weren't wrapped in a code block]

I noticed it in these two docs since I was looking at them and "takes points as a List rather than List" line stood out, but I suppose it's safe to assume it happens in other places as well.

**Comment by zoechi** [comment]
Might be a dup of https://github.com/dart-lang/dartdoc/issues/1520#issuecomment-337624691

**Comment by Hixie** [comment]
Also probably related to https://github.com/dart-lang/dartdoc/issues/1529 and https://github.com/dart-lang/dartdoc/issues/1527.

I'm going to close this since these are open issues with dartdoc.

cc @gspencergoog
