### ISSUE TITLE
I am facing issue to load 4K and HD video playing using video_player flutter package , nothing play on android iOS device 

### ISSUE THREAD

**Issue by bonisha-mandora** [flutter/flutter#154665]
### Steps to reproduce

Upload 4k video from mobile in flutter app
### Expected results

This issue appears to be specific to 4K (high resolution) video content. Users should be able to preview 4K video content seamlessly both during poll creation and when viewing videos in home screen.

### Actual results

The play buttons for 4K video content are visible but non-functional. Users are unable to preview the videos

### Code sample

<details open><summary>Code sample</summary>

```dart
if (option.mediaUrl != null) { final controller = VideoPlayerController.networkUrl( Uri.parse(option.mediaUrl!), ); controller.initialize().then((_) { setState(() {}); // Ensure the UI updates when video is ready }); }
```
https://github.com/flutter/flutter/issues/118148 this is same but its closed without any solution 
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    • Flutter version 3.22.2 on channel stable at /Users/hareshmakadiya/Development/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/hareshmakadiya/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.119

[✓] Network resources
    • All expected network resources are available.
</details>

**Comment by darshankawar** [comment]
@bonisha-mandora 
Are you able to replicate this locally ? If so, can you provide a short video of the behavior ?
Also please provide device details in which it doesn't run properly.

**Comment by bonisha-mandora** [comment]
@darshankawar I am uploading video using [video_editor](https://pub.dev/packages/video_editor) and compressing via https://pub.dev/packages/light_compressor, it not plays in even 4k supported device  OnePlus 11 5G (Android 14), attached device detail also in the image having snapdragon series but still not able to preview uploaded 4k video 
![chrome_Qqi85rRq6I-20240905-131307](https://github.com/user-attachments/assets/07250ef3-f35e-43c5-8968-2b026cb77d57) , 

also screenshot of that device
![vlc_qgdAOBAp8Z](https://github.com/user-attachments/assets/f33cbc40-9a52-47c6-a557-88540c132a4e)


Can you please provide some solution, for that with existing libraries & another approach to preview video in all such devices

**Comment by darshankawar** [comment]
@bonisha-mandora 
It could be device-specific and hardware issue. Please see https://www.blackview.hk/blog/guides/can-snapdragon-695-support-4k#:~:text=Unfortunately%2C%20the%20Snapdragon%20695%20processor,resolution%20for%20both%20these%20functions.
