### ISSUE TITLE
Suggest looking at frame phases in observatory the 'no more jank' article 

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15462]
Filing a new bug to not block the article and iterate after.

It would be really useful to add details for debugging performance by describing that once UI thread jank is detected from the performance overlay the next steps would be to use the observatory timeline to look at the time taken by each frame phase (they're likely going to be from the build, layout, paint phases).

Once that's established, recommend turning on debugProfileBuildsEnabled and debugProfilePaintsEnabled debug flags. They're only available in debug mode and they change the performance itself so timing output is no longer valid but it's helpful for finding out what exactly the code is building each frame to find inefficient animations, excessive rebuilds etc. 

cc @Sfshaza

**Comment by Sfshaza** [comment]
Yes, I originally went into more details about Observatory, but the UI was changing. I'd like to revisit this.

**Comment by Sfshaza** [comment]
Added to doc content plan.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1860](https://github.com/flutter/website/issues/1860) via [**ZenHub**](https://www.zenhub.com/)
