### ISSUE TITLE
Document on Opacity that using a widget with RenderAnimatedOpacity is more efficient that building Opacity on animation

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15464]

**Comment by matthew-carroll** [comment]
@xster should this ticket also be closed, like #15468 ?

**Comment by xster** [comment]
This is on the `Opacity` widget. We can still add something in the doc that says if you're changing the opacity value in rapid succession, such as in an animation, while the child does not change, consider using [RenderAnimatedOpacity] such as via [FadeTransition]. We should also add [FadeTransition] and [AnimatedOpacity] in the 'see also' section.

**Comment by matthew-carroll** [comment]
Ah, I see, I was thinking AnimatedOpacity but we're talking about Opacity.  Alright I'll take a crack at updating Opacity's documentation.
