### ISSUE TITLE
`camera_android` and `camera_android_camerax` integration tests failure on image resolution

### ISSUE THREAD

**Issue by yaakovschectman** [flutter/flutter#154682]
Internal: b/376074365

The packages PR https://github.com/flutter/packages/pull/7587/checks which only updates the targeted SDK for example apps and makes some tweaks to the manifests as necessary to do so is resulting in instrumentation test failures (https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8737614895298399505/+/u/Run_package_tests/Firebase_Test_Lab/stdout) for the `camera_android` and `camera_android_camerax` packages, either from timing out or from an image being taken at a higher than expected resolution.  
Locally, running `dart run script/tool/bin/flutter_plugin_tools.dart drive-examples --android --packages=camera_android_camerax,camera_android` on the branch of that PR resulted in failed assertions for the image resolutions, as well. However, when checking out the `main` branch again, and running the above command on `main`, those tests continue to fail.

**Comment by yaakovschectman** [comment]
@camsim99 Do you have ideas on how I might confirm that the failures I see locally share their cause with whatever is going wrong for PR checks, or any other info regarding the cause of those failures?

**Comment by camsim99** [comment]
@yaakovschectman Noting the actual image resolutions that the devices choose and causes the tests to fail may be useful. I don't know what device you're using locally (like if it's the same as those running in CI) but noting it will still be helpful to help determine if it's something with CameraX and how it behaves on certain devices or how we're using CameraX. 

I know this doesn't "confirm" exactly but if you're seeing it locally and in CI and it's clearly an issue with what resolution is being chosen, I think it's a safe assumption.

**Comment by yaakovschectman** [comment]
The logs from the firebase tests show it used a Pixel 7 API 33, and that it expected a resolution of 240 but got 1080. Locally running integration tests with `main` checked out with a matching emulator running still fails that same "Capture specific image resolutions" test, same as the firebase failure.

**Comment by jesswrd** [comment]
It looks like `camera` integration test is also failing on image resolution: https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_device_tests_shard_1%20master/12254/overview
