### ISSUE TITLE
How to add flutter module project into existing React project

### ISSUE THREAD

**Issue by zjTek** [flutter/flutter#154658]
### Steps to reproduce

1. Create a flutter project with type module 
2. Follow the step in document "Integrate a Flutter module into your Android project"
3. Add this flutter project as submodule of existing React project
4. Run the flutter build web
5. Run the flutter create .
6. Run flutter config –enable-web

### Actual results

1. Works fine on android native project
2. Not working for React project, because flutter module does not contain fold named web
3. Run flutter build web gives error "Missing index.html"
4. Nothing changes after run flutter create . /   flutter config –enable-web

### Logs

flutter build web
Missing index.html.

### Flutter Doctor output

[!] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-CN)
    • Flutter version 3.24.1 on channel stable at /Users/fortress/fvm/versions/3.24.1
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/fortress/fvm/versions/3.24.1. Consider adding /Users/fortress/fvm/versions/3.24.1/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 周前), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fortress/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/fortress/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Pixel 8 (mobile)                • 192.168.2.10:40669    • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.119
    ! Error: Browsing on the local area network for 柯柯柯的iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

**Comment by huycozy** [comment]
Hi @zjTek 
For Web embedding, please check https://docs.flutter.dev/platform-integration/web/embedding-flutter-web. You can also check some samples at https://github.com/flutter/samples/tree/main/web_embedding as well (there is also a React Native sample).

Closing from here as this is more of a `how-to` question. If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly. Thanks!
