### ISSUE TITLE
More clearly document using AnimatedBuilder without child causes poor performance

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15463]
If the child doesn't depend on the animation, building the child in the `builder` instead of passing it in via the `child` causes poor animation performance.

**Comment by xster** [comment]
Link to alternatives for simple animations in the doc.

**Comment by xster** [comment]
Yes, it's the cost of reconstructing the subtree below AnimatedBuilder mostly. The cost mainly depends on how big it is but is also conceptually a 100% waste if no part of the subtree changes wrt the animation. There's also a cost of calling every single setter on all of the subtree's associated render objects to update their properties (I just learned recently). That step isn't necessarily very expensive either since most setters check if the value changes.

**Comment by matthew-carroll** [comment]
Ok, makes sense.

Currently the class doc reads the following.  Can you point to what's missing or underrepresented?

> Performance optimizations
> If your builder function contains a subtree that does not depend on the animation, it's more efficient to build that subtree once instead of rebuilding it on every animation tick.
> 
> If you pass the pre-built subtree as the child parameter, the AnimatedBuilder will pass it back to your builder function so that you can incorporate it into your build.
> 
> Using this pre-built child is entirely optional, but can improve performance significantly in some cases and is therefore a good practice.

Should we specifically call out that the inefficiency is the construction of the Widget tree?  I'm not sure that will add much for readers...

**Comment by xster** [comment]
oh ha, it seems like we already fixed this. We just forgot to close it :)
