### ISSUE TITLE
3.26 Branch Info

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#154674]
### 3.26 beta branch info ###

| Repo | Branch | Commit | g3 CL |
| --- | --- | --- | --- |
| flutter/flutter | [flutter-3.26-candidate.0](https://github.com/flutter/flutter/tree/flutter-3.26-candidate.0) | https://github.com/flutter/flutter/commit/57c4bd0d85f3e41eb21522a0feb2dfaa514f8e22 | [cl/671203946](https://critique.corp.google.com/cl/671203946) |
| flutter/engine | [flutter-3.26-candidate.0](https://github.com/flutter/engine/tree/flutter-3.26-candidate.0) | https://github.com/flutter/engine/commit/652a43bc40559a279b855938fdcc356e40cc5238 | N/A |
| dart-lang/sdk | [3.6.0-216.0.dev](https://github.com/dart-lang/sdk/tree/3.6.0-216.0.dev) | https://github.com/dart-lang/sdk/commit/1a6246225b75aae44a5cba2b98ee6d55ecfc89b6 | [cl/671020183](https://critique.corp.google.com/cl/671020183) |
| google/skia | as needed | https://github.com/google/skia/commit/655699edfc9745af2172ba79b5a99b169fa800fb | N/A |

CC @christopherfujino @reidbaker @zanderso @chingjun

**Comment by christopherfujino** [comment]
Created a recipes branch: https://source.corp.google.com/h/flutter/recipes/+/flutter-3.26-candidate.0:

Here's the recipes bundler build: https://ci.chromium.org/ui/p/flutter/builders/prod/recipes-bundler/b8737609114654468993/infra

**Comment by christopherfujino** [comment]
Framework branch and engine branches also pushed (see links in description to verify).

Framework post-submit CI: https://flutter-dashboard.appspot.com/#/build?repo=flutter&branch=flutter-3.26-candidate.0
Engine post-submit CI: https://flutter-dashboard.appspot.com/#/build?repo=engine&branch=flutter-3.26-candidate.0
