### ISSUE TITLE
Clipping issue of UiKitView 

### ISSUE THREAD

**Issue by Heidi0039** [flutter/flutter#154664]
### Steps to reproduce

Unfortunately I am not able to reproduce this Problem in a clean example project.
It appears that there is a complex relationship between all the components at play.
A big **native View covering the entire Background** (here the Map seen in the Background), multiple layers of **Dart Widgets, including Navigators, Scrollviews and Listviews**. And finally a native **UiKitView within a Scrollable** Dart Widget.

The problem is, that the native UiKitView is rendered on top of dart Widgets, which should actually clip the UiKitView.

Since the problem started occurring when I recently updated to Flutter 3.24 I rolled back my Flutter to 3.19.1 for the time being.
I am sure that having no reproducable code makes this nearly Impossible to debug and fix. So instead I tried locating the actual change that introduced this behaviour in the first place.
After checking dozens of Flutter Versions I have noticed the Problem first occured in `3.23.0-13.0.pre` and further broke it down to Commits within this Version.

 **I found, that the Problem was first introduced with commit  `dccc26a28a`.**
Any older state (e.g. the one just before that `2a127cbdf8`) clips the UiKitView as expected.

Now looking at said commit, it shows a different revision of the flutter engine, which is where my current investigation came to a halt.
I know that having no reproducable code to check this out is difficult, but maybe there is some obvious change that has happened in the engine at that time that would give it away? Or at least lead someone to being able to reproduce this issue in the first place?

### Expected results

The UiKitView is clipped below the dart Widget. `2a127cbdf8`

https://github.com/user-attachments/assets/954bbfac-7290-4ef3-89e3-906942012d02

### Actual results

The UiKitView is rendered on top of the dart Widget. `dccc26a28a`

https://github.com/user-attachments/assets/47c0ba76-30c0-4755-aa5d-8dc95baf167b

### Code sample

The Videos showing both behaviours are recorded using an identical App. The only difference is the underlying Flutter Version used to build the App.

**Comment by huycozy** [comment]
Hi @Heidi0039 
What is your Flutter version? This looks similar to https://github.com/flutter/flutter/issues/153904 and https://github.com/flutter/flutter/issues/154249 which were fixed recently. Please switch to Flutter master channel and retry.

```
flutter channel master
flutter upgrade
```

**Comment by Heidi0039** [comment]
Yeah it does look similar to those other issues mentioned.
I have previously been on the stable channel.

I can confirm that on master this is indeed fixed! Thanks
