### ISSUE TITLE
Flutter is stuck at "Waiting for VM Service port to be available..."

### ISSUE THREAD

**Issue by Brockdish** [flutter/flutter#154685]
### Steps to reproduce

1. add a homescreen widget
2. gradle sync
3. upgrade gradle plugin
4. upgrade sdk
5. move sdk folder
6. update android studio by deleting and installing again
7. run "flutter run -v" in terminal

### Actual results

because of what I did everything is messed up and I can not even start the app. When I do "flutter run -v" I get this at the end:

Waiting for VM Service port to be available...

and then it just stays like that forever

### Logs

<details open>
<summary>Logs</summary>

```console
[...]

[   +3 ms] Installing build\app\outputs\flutter-apk\app-debug.apk...
[   +1 ms] executing: D:\Brockdish\Programming\SDKs\Android\platform-tools\adb.exe -s emulator-5554 install -t -r D:\Brockdish\Programming\Flutter
Projects\clothes_ethics_app\build\app\outputs\flutter-apk\app-debug.apk
[+7765 ms] Performing Streamed Install
                    Success
[   +2 ms] Installing build\app\outputs\flutter-apk\app-debug.apk... (completed in 7,8s)
[   +5 ms] executing: D:\Brockdish\Programming\SDKs\Android\platform-tools\adb.exe -s emulator-5554 shell echo -n d613de727cfacda75e7bd4e15d3f720ebf3e7c66 >
/data/local/tmp/sky.dev.jusoft.clotho.sha1
[ +218 ms] executing: D:\Brockdish\Programming\SDKs\Android\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[+1482 ms] --------- beginning of main
                    09-05 18:36:18.886 D/ControlsListingControllerImpl( 1065): ServiceConfig reloaded, count: 0
[ +162 ms] executing: D:\Brockdish\Programming\SDKs\Android\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f
0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true dev.jusoft.clotho/dev.jusoft.clotho.MainActivity
[+4143 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=dev.jusoft.clotho/.MainActivity (has extras) }
[   +2 ms] Waiting for VM Service port to be available...
```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.22631.4037], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
[√] Connected device (3 available)
[√] Network resources

```

</details>

**Comment by darshankawar** [comment]
> * move sdk folder
> * update android studio by deleting and installing again

@Brockdish I am not sure what was the purpose of carrying out these steps. Looks like your setup / configuration is messed up. 

Can you provide entire verbose log to see if it gives any meaningful error entries that might help to debug this further ?

**Comment by Brockdish** [comment]
> > * move sdk folder
> > * update android studio by deleting and installing again
> 
> @Brockdish I am not sure what was the purpose of carrying out these steps. Looks like your setup / configuration is messed up.
> 
> Can you provide entire verbose log to see if it gives any meaningful error entries that might help to debug this further ?

Thanks for the comment but I decided to revert everything to get around the problem and found out that the problem was the gradle version or the gradle plugin version.
I changed it back to an outdated version to avoid bugs and errors because I do not really know why I should upgrade gradle if the only thing that changes is how many errors I get lol
But thanks for the answer anyway

(For everyone else reading this: The solution is to keep the gradle plugin on an old version such as e.g. 7.3)
