### ISSUE TITLE
webkit2gtk-4.0 missing on Ubuntu Noble (24.04)

### ISSUE THREAD

**Issue by nicolasbock** [flutter/flutter#154633]
### Steps to reproduce

```console
$ flutter run --device-id linux
Launching lib/main.dart on Linux in debug mode...
CMake Error at /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - webkit2gtk-4.0

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  flutter/ephemeral/.plugin_symlinks/desktop_webview_auth/linux/CMakeLists.txt:21 (pkg_check_modules)
```

### Expected results

The current package on 24.04 should be acceptable:

```console
$ apt-cache search --names-only libwebkit2gtk
libwebkit2gtk-4.0-doc - WebKitGTK documentation (transitional dummy package)
libwebkit2gtk-4.1-0 - Web content engine library for GTK
libwebkit2gtk-4.1-dev - Web content engine library for GTK - development files
```

### Actual results

See "steps to reproduce"

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.2, on Ubuntu 24.04.1 LTS 6.8.0-41-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Proxy Configuration
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> ```
>   flutter/ephemeral/.plugin_symlinks/desktop_webview_auth/linux/CMakeLists.txt:21 (pkg_check_modules)
> ```

This dependency is coming from `desktop_webview_auth`, which is a third-party package. You'd need to report this to the package developers, as Flutter has no control over how third-party plugins specify their native dependencies.
