### ISSUE TITLE
[Text] Add onOverflow callback

### ISSUE THREAD

**Issue by npateras** [flutter/flutter#154603]
### Use case

The reason of requesting this feature is to basically calculate when a text is overflowing to show something else.
Use case:
- I want to have a paragraph that shows 3 lines max, when it overflows I show a read more button but if it's not overflowing I hide it.

### Proposal

The above can be easily implemented with an onOverflow callback which will let me set a variable when the text overflows!

**Comment by maRci002** [comment]
Check out https://pub.dev/packages/readmore package

**Comment by npateras** [comment]
> Check out https://pub.dev/packages/readmore package

I don't want to use this package because it doesn't help me with my use case scenario. I prefer to have a simple callback like the one requested.

**Comment by maRci002** [comment]
I think you'll experience a flickering screen because `Text.onOverflow` will be called during build time, which means the app will render the first frame incorrectly.

**Comment by goderbauer** [comment]
You can use a TextPainter [1] to figure out the size of rendered text upfront. Adding a callback for this to the Text widget is a nonstarter because of the flickering issue mentioned above.

[1] https://main-api.flutter.dev/flutter/painting/TextPainter-class.html
