### ISSUE TITLE
Cross reference FadeTransition and AnimatedOpacity in docs and contrast difference

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15468]

**Comment by matthew-carroll** [comment]
@xster any reason that both FadeTransition and AnimatedOpacity exist?  AnimatedOpacity is built with an Opacity Widget internally whereas FadeTransition defers to a render Object called RenderAnimatedOpacity.  The only difference I can see is that one uses a `double` and the other uses an `Animation<double>` - is that distinction worth the difference?

If so, it still seems strange that one is implemented entirely in Widget-land, while the other has a special render Object.  Any reason for that?

**Comment by xster** [comment]
From https://github.com/flutter/flutter/pull/14155, I think it's just to avoid constantly rebuilding the entire widget subtree. If the FadeTransition is on the page transition, then the entire page would rebuild per frame. 

Since the render object listens to the animation directly in the FadeTransition, essentially nothing rebuilds in the widget tree. 

Rather than documenting though, we should just make AnimatedOpacity use RenderAnimatedOpacity instead.

**Comment by xster** [comment]
There's already a bug open. Merging into #15466

**Comment by Hixie** [comment]
@matthew-carroll We have AnimatedFoo and FooTransition widgets for most things; one takes an Animation so you can drive it externally, and one just automatically drives itself when its argument change.

**Comment by matthew-carroll** [comment]
@Hixie Got it.  it might be worth considering an alternate naming convention.  My initial assumption about FadeTransition was that it was a special one-off animation created specifically for page route transitions.  The term "transition" seems to be used a lot online when referring to routing (see questions about "custom transitions"), and it also now seems that "transition" is routinely used for an independent concept in the SDK as well.

**Comment by Hixie** [comment]
Our naming convention here is terrible but it's probably too late to change it.
