### ISSUE TITLE
ButtonStyle: `foregroundColor` no longer controls icon color, contradicting dartdocs

### ISSUE THREAD

**Issue by chrisbobbe** [flutter/flutter#154644]
### Steps to reproduce

1. Make a `FilledButton.icon` with an icon and a label, and `style: const ButtonStyle(foregroundColor: WidgetStatePropertyAll(Colors.orange))`.
2. See the color of the icon and the label.
3. Read the dartdocs on `ButtonStyle.foregroundColor` and `ButtonStyle.iconColor`:

```dart
  /// The color for the button's [Text] and [Icon] widget descendants.
  ///
  /// This color is typically used instead of the color of the [textStyle]. All
  /// of the components that compute defaults from [ButtonStyle] values
  /// compute a default [foregroundColor] and use that instead of the
  /// [textStyle]'s color.
  final MaterialStateProperty<Color?>? foregroundColor;
```

```dart
  /// The icon's color inside of the button.
  ///
  /// If this is null, the icon color will be [foregroundColor].
  final MaterialStateProperty<Color?>? iconColor;
```

### Expected results

The icon and the label should be orange. Or, those dartdocs should not say that `ButtonStyle.foregroundColor` controls the icon color when `iconColor` is null. 

### Actual results

The label is orange, but the icon is not.

The reason: starting with 51ed348f3 (from #143501), the behavior for `iconColor: null` is to color the icon with a hard-coded default, instead of using `foregroundColor`.

See before/after this change in screenshots below.

At the same time, the quoted dartdocs still say that `ButtonStyle.foregroundColor` controls the icon color when `iconColor` is null.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Center(
        child: FilledButton.icon(onPressed: () {},
          style: const ButtonStyle(foregroundColor: WidgetStatePropertyAll(Colors.orange)),
          label: const Text('Icon button'),
          icon: const Icon(Icons.save))));
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

| Before (51ed348f3^) | After (51ed348f3) |
| --- | --- |
| <img width="486" alt="image" src="https://github.com/user-attachments/assets/613fbfbf-027f-4699-850e-75bb822282f8"> | <img width="486" alt="image" src="https://github.com/user-attachments/assets/efa6995d-2bde-4ba8-bd70-be096bba0a6d"> |

</details>

### Logs

<details open><summary>Logs</summary>

No unusual log output expected or observed.

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.24.0-1.0.pre.428, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    ! Flutter version 3.24.0-1.0.pre.428 on channel [user-branch] at /Users/chrisbobbe/.local/lib/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (5 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by chrisbobbe** [comment]
I'm not sure whether it's better to change the behavior or update the doc. Updating the doc seems easier, at least, so I plan to go ahead with that.

cc @gspencergoog @HansMuller @QuncCccccc as authors/reviewers of #143501.

**Comment by gspencergoog** [comment]
> I'm not sure whether it's better to change the behavior or update the doc. Updating the doc seems easier, at least, so I plan to go ahead and open a PR for that.

Yes, updating the doc is the right thing. The Material tokens specify them separately, so they should be independent.

**Comment by chrisbobbe** [comment]
Thanks for the prompt reply! Just sent #154646 for this.

**Comment by darshankawar** [comment]
Thanks for the report and potential fix @chrisbobbe 
Verified that this seems to occuring in master version only, as, on latest stable, it works as expected.

`Master version: 3.25.0-1.0.pre.269`

**Comment by gspencergoog** [comment]
> Verified that this seems to occuring in master version only, as, on latest stable, it works as expected.

Actually, they're both working as expected: https://github.com/flutter/flutter/pull/143501 was intended to change behavior.
