### ISSUE TITLE
Would like a way to disable SearchAnchor

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#154700]
### Use case

Other "button" types disable when you pass null for their onPressed.  SearchAnchor is sorta a button in that it seems to handle onPressed, but there is no way to control that (you can't pass builder:null, since it's not nullable).  (The examples show including a `controller.openView` call from within an ElevatedButton made within the builder, but that call appears to be completely optional, since SearchAnchor seems to detect the gesture itself.)
https://api.flutter.dev/flutter/material/SearchAnchor-class.html

I can obviously just wrap the SearchAnchor in an IgnorePointer and either do my own Opacity wrapper, or pass null for the ElevatedButton's onPressed (assuming I'm using an ElevatedButton within my builder callback).

Feel free to close, mostly just noticed this oddity tonight while trying to use SearchAnchor that sometimes wanted to be disabled.

### Proposal

This was fixed for SearchBar in https://github.com/flutter/flutter/issues/136943

Maybe a similar fix is needed for SearchAnchor?

**Comment by bleroux** [comment]
Probably fixed in https://github.com/flutter/flutter/pull/153256

**Comment by darshankawar** [comment]
> Probably fixed in #153256

Thanks @bleroux for the hint. By passing `enabled: false`, it seem to disable the searchAnchor as below:

<img width="337" alt="Screenshot 2024-09-06 at 2 16 27 PM" src="https://github.com/user-attachments/assets/39aa6840-ccb1-4db9-9140-40f87dea6cc2">

@eseidel Please see if above helps to resolve your case / proposal or not.
