### ISSUE TITLE
`CupertinoActionSheetAction` cursor doesn't change to clickable on desktop.

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#154792]
### Steps to reproduce

Run the `CupertinoActionSheetAction`  code sample below.

### Expected results

Expected a way to change cursor on desktop 

### Actual results

No cursor change 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: const CupertinoThemeData(
        brightness: Brightness.light,
      ),
      home: CupertinoPageScaffold(
        child: Center(
          child: Builder(builder: (BuildContext context) {
            return CupertinoButton(
              onPressed: () {
                showCupertinoModalPopup<void>(
                  context: context,
                  builder: (BuildContext context) {
                    return CupertinoActionSheet(
                      title: const Text('The title'),
                      message: const Text('Message'),
                      actions: <Widget>[
                        CupertinoActionSheetAction(
                          child: const Text('One'),
                          onPressed: () {},
                        ),
                      ],
                    );
                  },
                );
              },
              child: const Text('Go'),
            );
          }),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel main, 3.25.0-1.0.pre.283, on macOS 15.0 24A5327a
    darwin-arm64, locale en-US)
    • Flutter version 3.25.0-1.0.pre.283 on channel main at
      /Users/tahatesser/Code/flutter
    ! Upstream repository git@github.com:TahaTesser/flutter.git is not the same
      as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = git@github.com:TahaTesser/flutter.gitexport
    • Framework revision aea84342eb (3 days ago), 2024-09-05 16:46:22 -0700
    • Engine revision 015f3b1dec
    • Dart version 3.6.0 (build 3.6.0-216.0.dev)
    • DevTools version 2.39.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5230g
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile)          • 00008120-001C559034DB401E • ios
      • iOS 18.0 22A5350a
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 15.0 24A5327a darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 15.0 24A5327a darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
As part of https://github.com/flutter/flutter/issues/86174#issuecomment-1016596648, we added cursor support for web. The cursor on native macOS apps do not change automatically to a clickable cursor. Maybe we could benefit from a `mouseCursor` property. 

I'm not actively working on Cupertino so I'll leave this for someone who can fix it.  

cc: @nilsreichardt for making me aware of this issue

**Comment by huycozy** [comment]
I can reproduce this issue on macOS as well. We can temporarily work around this by wrapping CupertinoActionSheetAction with a MouseRegion like this:

```dart
MouseRegion(
  cursor: SystemMouseCursors.click,
  child: CupertinoActionSheetAction(
    child: const Text('One'),
    onPressed: () {},
  ),
),
```

Reproduced this on Flutter stable `3.24.2` and master `3.25.0-1.0.pre.303`.

**Comment by TahaTesser** [comment]
This would be a Cupertino design issue, as they Cupertino widgets can be used on any desktop platform.  Not specific to a macOS platform.

**Comment by Piinks** [comment]
cc @dkwingsmt who has been doing some work in this area. :)

**Comment by victorsanni** [comment]
Adding a `mouseCursor` property should be sufficient here. Part of https://github.com/flutter/flutter/issues/58192.

**Comment by dkwingsmt** [comment]
Feel free to work it at your convenience :)  

I can think of 3 steps of doing this:
1. Make `CupertinoActionSheetAction`'s cursor `pointer` without being configurable
2. Add a configurable property `CupertinoActionSheetAction.cursor`
3. Allow the property to make use of `WidgetState`.

Completing step 1 should be sufficient to close this issue, but step 2 would be welcome too. Step 3 is not necessary if you think it's too hard.

If you search for `final MouseCursor` you can find a lot of examples of how other widgets define it.

**Comment by TahaTesser** [comment]
@srivats22 Assigned you.

**Comment by victorsanni** [comment]
> I am thinking we can do something like this: `cursor: (kIsWeb || Platform.isMacOS) ? SystemMouseCursors.click : MouseCursor.defer,` 

I am confused here.

Currently, the cursor only becomes clickable on web. However, we want to be able to configure it to be clickable on desktop, if desired. 

This change seems to just make it always clickable on desktop, which I think isn't what we want. Isn't the goal to introduce a property that allows the user configure what `mouseCursor` they would like to use, independent of platform?

Please feel free to correct me if I am missing something.

**Comment by srivats22** [comment]
> > I am thinking we can do something like this: `cursor: (kIsWeb || Platform.isMacOS) ? SystemMouseCursors.click : MouseCursor.defer,`
> 
> I am confused here.
> 
> Currently, the cursor only becomes clickable on web. However, we want to be able to configure it to be clickable on desktop, if desired.
> 
> This change seems to just make it always clickable on desktop, which I think isn't what we want. Isn't the goal to introduce a property that allows the user configure what `mouseCursor` they would like to use, independent of platform?
> 
> Please feel free to correct me if I am missing something.

Oh I can make it like that... I was going based on what was mentioned here

https://github.com/flutter/flutter/issues/154792#issuecomment-2458222862

**Comment by srivats22** [comment]
Hi 
PR: https://github.com/flutter/flutter/pull/158470 is ready for review and this will address this issue

Thanks
