### ISSUE TITLE
How do I use this to create an app for my project?

### ISSUE THREAD

**Issue by Clintonosei123** [flutter/flutter#154773]

**Comment by iapicca** [comment]
@Clintonosei123

0. if you care about android install [android studio](https://developer.android.com/studio)

1. [official installation](https://docs.flutter.dev/get-started/install)
    - unofficial / my personal recommendation: use [fvm](https://fvm.app/documentation/getting-started/installation) instead

2. ensure that flutter installed properly by running in the command line 
   `flutter doctor -v`
   
3. create your app by running in the command line 
    `flutter create my_awesome_app`
    - if you don't like the command line you can use [android studio flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) and proceed from there


I recommend to follow up to this conversation on [discord](https://discord.com/invite/N7Yshp4)
issues are more about reporting bugs and feature requests :)

**Comment by Clintonosei123** [comment]
I want the discord link

**Comment by iapicca** [comment]
> I want the discord link

the same as the above
https://discord.com/invite/N7Yshp4

**Comment by nate-thegrate** [comment]
(I'll go ahead and close this one.)
