### ISSUE TITLE
I would like to see the actual Windows build in flutter doctor

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#154796]
### Use case

Multiple times when I created a issue and added the flutter doctor response I had to add the detail that I am using Windows 11 and not 10.

### Proposal

Check the Windows build number to detect the actual Windows version.

**Comment by andrewkolos** [comment]
If I recall correctly, `flutter doctor -v` should display the OS version. Is the issue here that `flutter doctor -v` is displaying that the OS version is 10 despite actually running on a version 11 host?

**Comment by rekire** [comment]
In both cases it is simply:

> [✓] Windows Version (Installed version of Windows is version 10 or higher)

For Windows 11 Pro, this is why I want to change this behavior. In the PR **[loic-sharma](https://github.com/loic-sharma)** had a great idea to use a power shell instead of maintaining a build list. I will migrate to that one, the next few days.
