### ISSUE TITLE
Broken example for NavigatorPopHandler

### ISSUE THREAD

**Issue by LowLevelSubmarine** [flutter/flutter#154713]
### Steps to reproduce
- Open https://api.flutter.dev/flutter/widgets/NavigatorPopHandler-class.html#widgets.NavigatorPopHandler.2 (Example 2)
- Click "Go to another route ... "
- Click "Go back"
- Error

### Expected results
Successfull back navigation

**Comment by Mairramer** [comment]
@LowLevelSubmarine I believe this has been fixed in https://github.com/flutter/flutter/pull/132249, but it is not yet in stable.
To test the change
https://main-api.flutter.dev/flutter/widgets/NavigatorPopHandler-class.html#widgets.NavigatorPopHandler.2
