### ISSUE TITLE
very    absurd    ,  unexpectedly   it  can't    provide   function to   delete emulator  

### ISSUE THREAD

**Issue by Super1Windcloud** [flutter/flutter#154784]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/30a83427-b6ad-4ace-8864-b099c0212bcb)

### Expected results

![image](https://github.com/user-attachments/assets/a694c5ef-44fa-4c14-a305-6d83b8c9856e)

### Actual results

![image](https://github.com/user-attachments/assets/79cffd39-2f98-45f1-9c99-35affd231a66)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by iapicca** [comment]
@Super1Windcloud 
did you try?
`avdmanager delete avd -n <emulator_name>`

I don't see the value of adding a wrapper for this

**Comment by darshankawar** [comment]
@Super1Windcloud 
Try above command to see if it helps in your case or not.
If not, then are you looking for a flutter command to delete emulator just like there is currently to create and run one ?
