### ISSUE TITLE
[Enhancement] Ability to capture KeyDown/KeyUp/LongPress events in Android 

### ISSUE THREAD

**Issue by NathanaelA** [flutter/flutter#15476]
Android has a event API off the main Application Activity with OnKeyDown/OnKeyUp/OnLongPress events; this api will pass in an entire event class called the KeyEvent

https://developer.android.com/reference/android/view/KeyEvent.Callback.html
https://developer.android.com/reference/android/view/KeyEvent.html

From this class; you can find out:
Pretty much anything about the key stroke(s) hit.  Including metadata like Shift/Ctrl/Alt, etc...
Different types of real keys and special keys like "Calculator", "Volume", "Brightness"...

I would like to create a general purpose plugin where I can pass back to flutter basically the entire KeyEvent and my Dart code will decide what to do with the keystroke.  In the event that Dart will handle the key or keystroke, it will `return true` so that the Android OS will no longer do anything with the keystroke.  In the event that Flutter does not handle the key; then I need to return 'false' to the Android OS.   

At this moment, because the `onKeyDown` and `onKeyUp` and are synchronous events that MUST return true or false when they are done, meaning that there is no way to currently process and handle the event in Flutter, because the minute I send the key over to Dart; the Native OEM side continues and by the time Dart sees the Key to respond; it has already returned back to the OS.

This is blocked by the inability to do sync communication events like engine pull# https://github.com/flutter/engine/pull/4358

CC: @Hixie

**Comment by Hixie** [comment]
The way we normally implement this kind of thing, e.g. the way we implement the accessibility support (which is also a bunch of synchronous APIs), is to have the framework proactively send information to the code running on the OEM side, so that when the request comes in, it can respond immediately. Would that approach work for this problem?

**Comment by NathanaelA** [comment]
There are some scenarios it could work -- for example if all I wanted to do was trap the volume keys...  Then I could write my JAVA wrapper code to only check for VolUp/VolDown and then return true when that occurred and false when it didn't and send those keys over the Async bridge into Dart land..   

However this would not be a generic solution, which is what I am aiming for when I develop a plugin. 

One app might need to capture Meta-A and another app; Brightness-Up.     If you checkout the second link I provided you can see the vast number of permutations that can occur which would make this a nightmare to actually pre-decide.     There are over 240 flags in addition to all the things like getAction(), getKeyCode(), getScanCode() and getMetaState(), getUnicodeChar() etc.   I don't see anyway to make this "generic" and pre-calculate what you need as each app will want to capture different keystrokes for different reasons.   For example a game using a bluetooth keyboard might want to capture WASD, shift, Alt, Ctrl.  on the left side of the keyboard and Arrows, insert, delete on the right side.     

I believe the first version of the plugin that I am thinking of would basically take a flag for which of these calls are needed to track and then call each of those calls to gather the info and create a similar interface on the dart side of the bridge.    i.e. something like `captureKeyDown(METASTATE|SCANCODE|KEYCODE, myHandler)` and then on the Android side it would automatically on each keystroke fill in the MetaState, ScanCode and Keycode structures to send over the sync bridge to myHandler.   The myHandler would then decide what is valid to capture and then proceed to handle the  key stroke how it needs to and return true/false back over the sync bridge to clear the sync state.   If need be -- the dart side of the bridge could have a required "SyncAnswer" call which would clear the sync state and return the value midway through the handler or whatever to allow us to answer immediately back before we actually handle the keystroke...

**Comment by Hixie** [comment]
It seems like it's always possible to know the list of key combinations that are going to be handled ahead of time. Can't you just send an array that says "Meta-A, Brightness-Up", or "W, A, S, D, Left Shift, Left Alt, Left Ctrl, Up, Down, Left, Right, Insert, Delete"?

**Comment by NathanaelA** [comment]
@Hixie - If I am writing something specifically for my own app; then yes you can handle some of this.  

The main answer is nope; if I am writing a generic plugin, and then only the final consumer of the plugin is who knows what keys they are capturing (and when), I as the plugin author has NO idea when/what keys they are wanting to capture and in what instances they don't want to capture.   So my goal is to return all keys back they want.   So in this plugin I would have to have some sort of customization function like `.captureKeyDown(....)` that I post as a message back to java from dart; then in java track every one of these -- then any keystroke that matches my array; I then pass a message back to Dart.  So in this way it can work.

However,  I might not want to capture WASD when in a text field; so the criteria becomes capture of some keys is valid only at certain points of time. Some of this can be pre-determined but now introduces the side effect of race conditions that can happen frequently in keys captured/not captured messages and when they hit vs when a keystroke is hitting.  

So having the ability to call into Dart, have dart process the values; then it figure out if it needs to actually capture or not-capture the characters is pretty critical to be well rounded plugin without race conditions.      

I can think of several ways to work around many of these issues; but the **only reason** they are all issues is because of the lack of sync support.   Seriously, In every other product I've used this is handled extremely easily, in Flutter this is literally a nightmare to do anything really custom in this area, and literally requires a lot of extra overhead on both the Java side and the Dart to do anything that would normally be extremely simple, and  finally the async implementation will always have extra or missing captures do to the race condition that it creates by the nature of its design.

**Comment by ZhennanWu** [comment]
Yes, as a flutter developer who is implementing custom key combinations, I hope this issue can be solved soon.

**Comment by stuartmorgan** [comment]
@gspencergoog Was this addressed by the overhaul of key handling?

**Comment by gspencergoog** [comment]
Yes, if I understand correctly, this was addressed in the overhaul of the key event system. We now respond immediately to the OS with "yes, it was handled", and then if the framework doesn't handle it, then we synthesize a new identical key event and respond "no, we didn't handle it" when the synthesized event arrives at our handler which lets the OS handle it.
