### ISSUE TITLE
Screen Orientation change doesnt work

### ISSUE THREAD

**Issue by mobile-pablo** [flutter/flutter#154786]
### Steps to reproduce

Requirements : 
* Device without rotation sensor
It can be as well that its old device (Android 9, rk3288 terminal)

1. Open flutter applicacion with 
```
SystemChrome.setPreferredOrientations([
    DeviceOrientation.landscapeLeft,
 ]);
```
2. Try to switch orientation

### Expected results

App should rotate

### Actual results

Only default is displayed

### Code sample

``` 
                                     switch (orientation) {
                                        case DeviceOrientation.portraitUp:
                                          {
                                            selectedOptions.add(e);
                                            SystemChrome
                                                .setPreferredOrientations([
                                              DeviceOrientation.landscapeLeft,
                                            ]);
                                            orientation =
                                                DeviceOrientation.landscapeLeft;
                                          }
                                        case DeviceOrientation.landscapeLeft:
                                          {
                                            selectedOptions.add(e);
                                            SystemChrome
                                                .setPreferredOrientations([
                                              DeviceOrientation.portraitDown,
                                            ]);
                                            orientation =
                                                DeviceOrientation.portraitDown;
                                          }

                                        case DeviceOrientation.portraitDown:
                                          {
                                            selectedOptions.add(e);
                                            SystemChrome
                                                .setPreferredOrientations([
                                              DeviceOrientation.landscapeRight,
                                            ]);
                                            orientation = DeviceOrientation
                                                .landscapeRight;
                                          }

                                        case DeviceOrientation.landscapeRight:
                                          {
                                            selectedOptions.removeWhere(
                                                (element) =>
                                                    element ==
                                                    RegisterOptions
                                                        .RotateScreen);
                                            SystemChrome
                                                .setPreferredOrientations([
                                              DeviceOrientation.portraitUp,
                                            ]);
                                            orientation =
                                                DeviceOrientation.portraitUp;
                                          }
                                      }
```

### Screenshots or Video

Because of NDA I cannot

### Flutter Doctor output

flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64 (Rosetta), locale es-VE)
    • Flutter version 3.24.1 on channel stable at /Users/pablo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
    • Android SDK at /Users/pablo/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/pablo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] VS Code (version 1.90.2)
    • VS Code at /Users/pablo/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • rk3288 (mobile)                 • RFGWX0TBYO            • android-arm    • Android 9 (API 28)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64 (Rosetta)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64 (Rosetta)
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment]
Hi @mobile-pablo, for the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), please provide such a sample.

**Comment by mobile-pablo** [comment]
Sure, will do after work

**Comment by iapicca** [comment]
on modern android seems to work

<details>
  <summary>code sample</summary>
  
  ```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(context) => const MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    super.key,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final ValueNotifier<DeviceOrientation> _valueNotifier;

  @override
  void initState() {
    _valueNotifier = ValueNotifier(DeviceOrientation.portraitUp)
      ..addListener(_listener);
    super.initState();
  }

  @override
  void dispose() {
    _valueNotifier
      ..removeListener(_listener)
      ..dispose();
    super.dispose();
  }

  void _next() {
    var next = DeviceOrientation.values.indexOf(_valueNotifier.value) + 1;
    if (!(next < DeviceOrientation.values.length)) {
      next = 0;
    }
    setState(() => _valueNotifier.value = DeviceOrientation.values[next]);
  }

  void _listener() => SystemChrome.setPreferredOrientations(
        [_valueNotifier.value],
      );

  @override
  Widget build(context) => Scaffold(
        body: Center(
          child: ValueListenableBuilder(
            valueListenable: _valueNotifier,
            builder: (context, orientation, _) => Text(orientation.name),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _next,
          tooltip: 'next',
          child: const Icon(Icons.rotate_90_degrees_cw),
        ),
      );
}

  ```
</details>

<details>
  <summary>screen recording</summary>

![image](https://github.com/user-attachments/assets/73cbee97-c780-4a36-b76a-df7badc31c64)

</details>


<details>
  <summary>doctor</summary>
  
  ```console
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (6 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • SM A556B (mobile)               • RZCX318VHFK           • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!
  ```
</details>

**Comment by mobile-pablo** [comment]
Like i mentioned it seem to doesnt work on devices without rotation sensor

**Comment by iapicca** [comment]
> Like i mentioned it seem to doesnt work on devices without rotation sensor

sorry I missed this part,
[SystemChrome](https://api.flutter.dev/flutter/services/SystemChrome-class.html) "Controls specific aspects of the operating system's graphical interface"
so for my understanding if the OS can't do it just does nothing

one option is the solution below
[code sample](https://dartpad.dev/?id=9b77b71ca6dbc77c7c88828f99a96421)

**Comment by mobile-pablo** [comment]
Unfortunatly i wont rewrite whole applicacion at work just to support rotation. I will use appSettings to navigate for user to change manually
