### ISSUE TITLE
PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.shared_preferences_android.SharedPreferencesAsyncApi.getBool"., null, null)

### ISSUE THREAD

**Issue by sylvbravo** [flutter/flutter#154723]
### What package does this bug report belong to?

shared_preferences

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>Details</summary>
<p>

shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      sha256: "746e5369a43170c25816cc472ee016d3a66bc13fcf430c0bc41ad7b4b2922051"
      url: "https://pub.dev"
    source: hosted
    version: "2.3.2"
  shared_preferences_android:
    dependency: transitive
    description:
      name: shared_preferences_android
      sha256: "480ba4345773f56acda9abf5f50bd966f581dac5d514e5fc4a18c62976bbba7e"
      url: "https://pub.dev"
    source: hosted
    version: "2.3.2"
  shared_preferences_foundation:
    dependency: transitive
    description:
      name: shared_preferences_foundation
      sha256: c4b35f6cb8f63c147312c054ce7c2254c8066745125264f0c88739c417fc9d9f
      url: "https://pub.dev"
    source: hosted
    version: "2.5.2"
  shared_preferences_linux:
    dependency: transitive
    description:
      name: shared_preferences_linux
      sha256: "580abfd40f415611503cae30adf626e6656dfb2f0cee8f465ece7b6defb40f2f"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.1"
  shared_preferences_platform_interface:
    dependency: transitive
    description:
      name: shared_preferences_platform_interface
      sha256: "57cbf196c486bc2cf1f02b85784932c6094376284b3ad5779d1b1c6c6a816b80"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.1"
  shared_preferences_web:
    dependency: transitive
    description:
      name: shared_preferences_web
      sha256: d2ca4132d3946fec2184261726b355836a82c33d7d5b67af32692aff18a4684e
      url: "https://pub.dev"
    source: hosted
    version: "2.4.2"
  shared_preferences_windows:
    dependency: transitive
    description:
      name: shared_preferences_windows
      sha256: "94ef0f72b2d71bc3e700e025db3710911bd51a71cefb65cc609dd0d9a982e3c1"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.1"

</p>
</details> 

### Steps to reproduce

```dart
bool isBiometricSupported = false;bool isFingerprintEnabled = false;
Future<void> checkBiometricsStatus() async{
    bool isBiometric = await isBiometricsSupported();
    bool? isFingerprint = await getFingerprintStatus();
    setState(() {
      isBiometricSupported = isBiometric;
      isFingerprintEnabled = isFingerprint ?? false;
    });
  }
``` 
```dart
Future<bool?> getFingerprintStatus() async {
  SharedPreferencesAsync preferences = SharedPreferencesAsync();
//This is the point where the error occurs
  bool? status = await preferences.getBool("fingerprint");

  return status;
}
``` 
```dart
LocalAuthentication authentication = LocalAuthentication();
  Future<bool> isBiometricsSupported () async {
    bool canAuthenticateWithBiometrics = await authentication.canCheckBiometrics;

    return canAuthenticateWithBiometrics;
  }
``` 

### Expected results

I expected the code to run without throwing an exception

### Actual results

It works perfectly on android 14, but when I use android 10.0 Emulator that's when I get this issue don't know what's wrong exactly, I have cleared the cache, reinstall the package, and no changes

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```shell
Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.shared_preferences_android.SharedPreferencesAsyncApi.getBool"., null, null)
E/flutter (15365): #0      SharedPreferencesAsyncApi.getBool (package:shared_preferences_android/src/messages_async.g.dart:246:7)
E/flutter (15365): <asynchronous suspension>
E/flutter (15365): #1      SharedPreferencesAsyncAndroid._convertKnownExceptions (package:shared_preferences_android/src/shared_preferences_async_android.dart:155:24)
E/flutter (15365): <asynchronous suspension>
``` 

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@sylvbravo 
Can you provide complete runnable reproducible code (ex: main.dart) that we can directly use to verify this further ?

**Comment by Eimji** [comment]
Hello,

I'm updating my application for Android 15, and I have a very similar issue with two packages wakelock_plus and path_provider, only in release mode:
```
E/flutter ( 6326): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 6326): #0      PathProviderApi.getApplicationDocumentsPath (package:path_provider_android/messages.g.dart:86)
E/flutter ( 6326): <asynchronous suspension>
E/flutter ( 6326): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121)
E/flutter ( 6326): <asynchronous suspension>
```

```
E/flutter (  634): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.toggle"., null, null)
E/flutter (  634): #0      WakelockPlusApi.toggle (package:wakelock_plus_platform_interface/messages.g.dart:124)
E/flutter (  634): <asynchronous suspension>
E/flutter (  634): #1      MethodChannelWakelockPlus.toggle (package:wakelock_plus_platform_interface/src/method_channel_wakelock_plus.dart:20)
E/flutter (  634): <asynchronous suspension>
```

I notice if I put, eg. for path_provider:
```-keep class io.flutter.plugins.pathprovider.** { *; }```
in the proguard-rules.pro, there are no issues.

It seems like something is wrong with the `pigeon` generated code?

Sorry, I will try to isolate some reproductible code, as it's a very big application.

Thanks.
