### ISSUE TITLE
MacOS desktop  build error - PhaseScriptExecution

### ISSUE THREAD

**Issue by dev-truelligence** [flutter/flutter#154790]
### Steps to reproduce

My MacOS desktop application is not building. i m agetting script error 

```console
   +4 ms] The following build commands failed:
[        ]      PhaseScriptExecution Run\ Script
/Users/..../build/macos/Build/Intermediates.noindex
/Runner.build/Debug/Flutter\ Assemble.build/Script-33CC111E2044C6BF0003C045.sh (in target 'Flutter Assemble' from
project 'Runner')
```

my script file content is 

```bash
#!/bin/sh
"$FLUTTER_ROOT"/packages/flutter_tools/bin/macos_assemble.sh && touch Flutter/e$
```

when i m downgrading fllutter , i m able to build the project.

### Expected results

The app should compile and run

### Actual results

My MacOS desktop application is not building. i m agetting script error 

```console
   +4 ms] The following build commands failed:
[        ]      PhaseScriptExecution Run\ Script
/Users/..../build/macos/Build/Intermediates.noindex
/Runner.build/Debug/Flutter\ Assemble.build/Script-33CC111E2044C6BF0003C045.sh (in target 'Flutter Assemble' from
project 'Runner')
```

### Code sample

my script file content is 

```bash
#!/bin/sh
"$FLUTTER_ROOT"/packages/flutter_tools/bin/macos_assemble.sh && touch Flutter/e$
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dev-truelligence** [comment]
flutter doctor -v output
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-x64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /Users/jayakumarmac/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Users/jayakumarmac/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 15.0 24A335 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!

im also attaching the flutter run -v output
[Untitled.docx](https://github.com/user-attachments/files/17143539/Untitled.docx)

**Comment by huycozy** [comment]
I paste the error from your provided logs here:
 
```console
[   +1 ms] [+3358 ms] ../../../../.pub-cache/hosted/pub.dev/win32-3.1.4/lib/src/guid.dart:31:9:
Error: Type 'UnmodifiableUint8ListView' not found.
[        ] [   +2 ms]   final UnmodifiableUint8ListView bytes;
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../../../.pub-cache/hosted/pub.dev/win32-3.1.4/lib/src/guid.dart:31:9:
Error: 'UnmodifiableUint8ListView' isn't a type.
[        ] [        ]   final UnmodifiableUint8ListView bytes;
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../../../.pub-cache/hosted/pub.dev/win32-3.1.4/lib/src/guid.dart:51:17:
Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]     return Guid(UnmodifiableUint8ListView(guid));
[   +1 ms] [        ]                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../../../.pub-cache/hosted/pub.dev/win32-3.1.4/lib/src/guid.dart:55:31:
Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]   factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
[        ] [        ]                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../../../.pub-cache/hosted/pub.dev/win32-3.1.4/lib/src/guid.dart:99:17:
Error: Method not found: 'UnmodifiableUint8ListView'.
[        ] [        ]     return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
[        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../../../../.pub-cache/hosted/pub.dev/fluent_ui-4.9.0/lib/src/app.dart:521:9:
Error: No named parameter with the name 'checkerboardRasterCacheImages'.
[        ] [        ]         checkerboardRasterCacheImages: widget.checkerboardRasterCacheImages,
[        ] [        ]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[     
```

>Error: Type 'UnmodifiableUint8ListView' not found.

Your project's dependencies depends on older version of `win32` package. Can you try running `flutter pub upgrade` and check if it's latest version on `pubspec.lock` file?

>Error: No named parameter with the name 'checkerboardRasterCacheImages'.

`checkerboardRasterCacheImages` has been removed on the latest version of `fluent_ui`. You should upgrade this package as well.
