### ISSUE TITLE
iOS: cannot delete character in phone number textfield

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#15472]
## Steps to Reproduce

1. Open Flutter Gallery on iOS
2. Navigate to "Text fields" towards the bottom of the "Material Components" section
3. Enter some numbers in the "Phone Number" text 
4. Try to delete some numbers with the delete key on the keyboard
5. See the numbers dance!

This does not reproduce on Android.

/cc @xster @HansMuller

**Comment by xster** [comment]
Duping into #12782
