### ISSUE TITLE
Error in wiki page for previewing Dart 2 in Flutter

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/flutter#15488]
On https://github.com/flutter/flutter/wiki/Trying-the-preview-of-Dart-2-in-Flutter, the text describing how to enable in VSCode is slightly wrong. "Code>Settings>Preferences" should be "Code>Preferences>Settings".

**Comment by DanTup** [comment]
This might be slightly different on Windows too (I don't think there's a "Code" menu). I'll take a look tomorrow.

**Comment by DanTup** [comment]
I've updated this and added the Windows equiv.
