### ISSUE TITLE
[CP] Fix memory leak in overlay surface host buffers.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#154892]
### Issue Link

flutter/flutter#154549

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/engine/pull/55056

### Changelog Description

* fix memory leak in overlay surfaces created when rendering platform views.

### Impacted Users

iOS impeller

### Impact Description

Applications may run out of memory is lots of UI is rendered over platform views

### Workaround

Disable Impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Attached unit tests

**Comment by itsjustkevin** [comment]
@zanderso could you take a look at this cherry-pick request?

**Comment by jonahwilliams** [comment]
It's based on 55036 but does not have the bug I fixed in 55087
