### ISSUE TITLE
add windows sdk

### ISSUE THREAD

**Issue by Mustakim-final** [flutter/flutter#154807]
### Use case

this sdk version not bulid windows apk

### Proposal

bulid windows sdk

**Comment by huycozy** [comment]
Please elaborate on the use case and proposal.

>this sdk version not bulid windows apk

Is `windows apk` a typo? Do you mean building Android apk on Windows host machine? 

Please give a clear and concise description of what the case is and what you would like Flutter to be able to do.

**Comment by Mustakim-final** [comment]
webview_flutter: ^4.9.0 This version can't create Windows apps, it would be nice if it could

**Comment by huycozy** [comment]
Please follow https://github.com/flutter/flutter/issues/37597. Closing this as a duplicate.
