### ISSUE TITLE
[iOS Widget Comparison Tool] Flutter views do not update with drop down selection

### ISSUE THREAD

**Issue by MitchellGoodwin** [flutter/flutter#154837]
This is about the iOS Comparison Tool found here:
https://github.com/flutter/platform_tests/tree/main/ios_widget_catalog_compare

Now when you select a widget from the dropdown, the Flutter view does not update until the app is interacted with.

https://github.com/user-attachments/assets/a50ba2e1-6f1e-4c40-b9ff-321b5ac5734f

**Comment by jonahwilliams** [comment]
This was fixed with https://github.com/flutter/engine/pull/55027
