### ISSUE TITLE
[path_provider] `getDownloadsDirectory()` path result is incorrect in parallels desktop environment

### ISSUE THREAD

**Issue by ANC1024GO** [flutter/flutter#154898]
windows not support getDownloadsDirectory(), is return mac path .

### Code sample

<details open><summary>Code sample</summary>

```dart
Logger().e({
        "getApplicationDocumentsDirectory":
            (await getApplicationDocumentsDirectory()).path,
        'win': Platform.isWindows,
        'getDownloadsDirectory': (await getDownloadsDirectory()),
        'getApplicationSupportDirectory': (await getApplicationSupportDirectory()),
        'getTemporaryDirectory': (await getTemporaryDirectory()),
        'getApplicationCacheDirectory': (await getApplicationCacheDirectory()),
      });
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter: │ ⛔ {
flutter: │ ⛔   "getApplicationDocumentsDirectory": "\\\\Mac\\Home\\Documents",
flutter: │ ⛔   "win": true,
flutter: │ ⛔   "getDownloadsDirectory": "Directory: '\\\\Mac\\Home\\Downloads'",
flutter: │ ⛔   "getApplicationSupportDirectory": "Directory: 'C:\\Users\\xxx\\AppData\\Roaming\\com.example\\xxx'",
flutter: │ ⛔   "getTemporaryDirectory": "Directory: 'C:\\Users\\xxx\\AppData\\Local\\Temp'",
flutter: │ ⛔   "getApplicationCacheDirectory": "Directory: 'C:\\Users\\xxx\\AppData\\Local\\com.example\\xxx'"
flutter: │ ⛔ }
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [版本 10.0.22631.4037], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.2)
[!] Android Studio (not installed)
[√] VS Code (version 1.93.0)
[√] Connected device (2 available)
[!] Network resources
    X A network error occurred while checking。


! Doctor found issues in 4 categories.
```

</details>

**Comment by huycozy** [comment]
@ANC1024GO Which plugin version are you using? I'm using the latest version `path_provider: 2.1.4`,  `path_provider_windows: 2.3.0` and see it prints out the correct path:

```console
flutter: Directory: 'C:\Users\ADMIN\Downloads'
```

Please use sample code below and confirm:
<details>
<summary>Sample code</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(onPressed: () async {
        final Directory? downloadsDir = await getDownloadsDirectory();
        print(downloadsDir);
      }),
    );
  }
}

```
</details>

I'm on the latest Flutter stable version 3.24.2.

**Comment by ANC1024GO** [comment]
> @ANC1024GO Which plugin version are you using? I'm using the latest version `path_provider: 2.1.4`, `path_provider_windows: 2.3.0` and see it prints out the correct path:
> 
> ```
> flutter: Directory: 'C:\Users\ADMIN\Downloads'
> ```
> 
> Please use sample code below and confirm:
> 
> Sample code
> ```dart
> import 'dart:io';
> 
> import 'package:flutter/material.dart';
> import 'package:path_provider/path_provider.dart';
> 
> void main() {
>   runApp(const MaterialApp(home: MyApp()));
> }
> 
> class MyApp extends StatefulWidget {
>   const MyApp({super.key});
> 
>   @override
>   State<MyApp> createState() => _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       floatingActionButton: FloatingActionButton(onPressed: () async {
>         final Directory? downloadsDir = await getDownloadsDirectory();
>         print(downloadsDir);
>       }),
>     );
>   }
> }
> ```
> 
> I'm on the latest Flutter stable version 3.24.2.

i`m use path_provider: ^2.1.2+ verstion, 
I used the win virtual machine (parallels desktop, win11) in my Mac(M1).

**Comment by huycozy** [comment]
Looks like this is a device-specific issue on virtual machine. Could you try using the latest plugin version `path_provider: 2.1.4`?

**Comment by ANC1024GO** [comment]
@huycozy sorry, This  problem with "parallels desktop" sharing a folder.

**Comment by stuartmorgan** [comment]
If Parallels is configured to map specific system directories to the host machine, `path_provider` is going to reflect that. If you believe Parallels shouldn't be doing this, you'd need to report that as in issue to the developer of Parallels.

Closing as the plugin is intended to return whatever the underlying platform returns, so the plugin is behaving correctly.
