### ISSUE TITLE
IMO `Color` should have `copyWith` instead of `withValues`

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#154845]
Discussion here: https://github.com/flutter/flutter/issues/154491#issuecomment-2338728421

If we are breaking things already, I believe they should be "as best as possible" instead of "as familiar" if familiar is different than what you see elsewhere in the framework.

![image](https://github.com/user-attachments/assets/fa32104f-813d-4c11-b50b-d8ee81933151)

**Comment by matanlurey** [comment]
Opening a new issue just to post a screenshot from https://github.com/flutter/flutter/issues/154491#issuecomment-2338728421 is not a good way to engage with folks that are trying to improve things and already had discussed tradeoffs. I am re-closing this issue and request you do not open issues with an "IMO this [previously discussed thing] is wrong".

Thank you.

**Comment by bernaferrari** [comment]
The screenshot is meant to help avoiding the click, and keep the discussion going since that was closed (for other reasons, since it is a different discussion).

I believe the "withValues" goes against Flutter rules, which is why I am against it.
