### ISSUE TITLE
Android emulator screen is full of broken pixels

### ISSUE THREAD

**Issue by MosaadIbrahimB** [flutter/flutter#154831]
### Steps to reproduce

![Screenshot_1725842692](https://github.com/user-attachments/assets/9f01eed0-6121-4430-b135-b45074870393)

### Expected results

Android emulator screen is full of broken pixels

### Actual results

Android emulator screen is full of broken pixels

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
    • Flutter version 3.24.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (6 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\BG\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Users\BG\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.2
    • Flutter plugin version 76.3.1
    • Dart plugin version 222.4167.21

[√] VS Code (version 1.92.2)
    • VS Code at C:\Users\BG\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.264]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.77

[√] Network resources
    • All expected network resources are available.

• No issues found!
</details>

**Comment by huycozy** [comment]
Hi @MosaadIbrahimB 
Please clarify something below that helps to verify the issue:
- Does this issue happen with simpler sample code (counter app) or with your project only? 
- Does this issue happen with a physical device if any?
- Can you share the affected emulator info? (OS version, name)

**Comment by MosaadIbrahimB** [comment]
The problem was solved by canceling the emulator update and using an old version of the Android emulator.
https://developer.android.com/studio/emulator_archive

**Comment by huycozy** [comment]
Was it Android 15 (API 35) emulator? If so, it seems to be an old Android emulator issue, please check https://github.com/flutter/flutter/issues/149328#issuecomment-2284847348 and try upgrading emulator version. If you persist with this issue, please provide info at https://github.com/flutter/flutter/issues/154831#issuecomment-2339847665.
