### ISSUE TITLE
FirebaseAnimatedList should have a 'emptyListChild'

### ISSUE THREAD

**Issue by Panthro** [flutter/flutter#15480]
## Current behavior

When using the firebaseAnimatedList for user generated content, the first time the user loads the application and there's no content, is just not optimal to load an empty container.

## Expected behavior

The ability to show a custom widget when the list is empty

**Comment by kroikie** [comment]
@Panthro

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/892. Any further collaboration will be done there.
