### ISSUE TITLE
flutter 3.24.0, and has error: SocketException: Failed host lookup: 'xxx.com' (OS Error: nodename nor servname provided, or not known, errno = 8)

### ISSUE THREAD

**Issue by gitwangyang** [flutter/flutter#154815]
### Steps to reproduce

1.iOS Version: 17.6.1
Device: iPhone15,3
System locale region: China
System locale language: English
2. flutter: 3.24.0
3. no response

### Expected results

expect: no issue and request has response

### Actual results

```
has issue: Error: SocketException: Failed host lookup: 'xxx.com' (OS Error: nodename nor servname provided, or not known, errno = 8), errorType: GlobalCommonErrorType.other, httpCode: null, response: null}

Flutter error: SocketException: Failed host lookup: 'mall.idux-vw.com' (OS Error: nodename nor servname provided, or not known, errno = 8) #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2487)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2632)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
> 1.iOS Version: 17.6.1

@gitwangyang Is this only occuring with this specific iOS version ? 
Also, you mentioned 3.24.0, if you downgrade to previous stable, did it work on same iOS version ?
To help properly address the issue, please also provide a minimal reproducible code sample that triggers the reported error.

**Comment by gitwangyang** [comment]
import 'package:dio/dio.dart';
 
void main() async {
  Dio dio = Dio();
 
  // 创建多个请求的Future列表
  List<Future<Response>> futures = [];
 
  // 添加请求到futures列表
  for (int i = 0; i < 10; i++) {
    futures.add(dio.get('https://api.example.com/data$i'));
  }
 
  // 使用Future.wait并发执行所有请求
  try {
    List<Response> responses = await Future.wait(futures);
    // 处理所有响应
    for (Response response in responses) {
      print(response.data);
    }
  } catch (e) {
    print(e);
  }
}

类似这种场景下的异常

**Comment by darshankawar** [comment]
@gitwangyang 
`dio` is a third party package. You may need to file this in dedicated repo. Another test you can do is to try `http` package and see if you still get same behavior or not.
