### ISSUE TITLE
AI toolkit MVP

### ISSUE THREAD

**Issue by zoeyfan** [flutter/flutter#154895]

**Comment by parlough** [comment]
@zoeyfan @csells Can we close this MVP issue as complete with the:

- [docs.flutter.dev docs launched](https://docs.flutter.dev/ai-toolkit)
- [Package published](https://pub.dev/packages/flutter_ai_toolkit)
- [Blog posted](https://medium.com/flutter/announcing-flutter-ai-toolkit-e36b16a840d2)
- [Entry added to flutter.dev/ai](https://flutter.dev/ai#ai-toolkit)

Thanks everyone for all the hard work here!

**Comment by csells** [comment]
yep. this has been fixed.
