### ISSUE TITLE
Installation freezes at "Unzipping Dart SDK" in android studio

### ISSUE THREAD

**Issue by puttapravinkumar0** [flutter/flutter#15485]
Recently I had installed flutter plugin in android studio. And when I went for new project, it asked me flutter sdk. I chosen "Install SDK". And it was freezes at ""Unzipping Dart SDK". I kept as it is for more than 3hrs, but was there is no any response.
Please can any one help me to continue....
![image](https://user-images.githubusercontent.com/25848532/37355093-2645be52-2709-11e8-99db-d04c98aa1d33.png)

**Comment by Hixie** [comment]
cc @devoncarew

**Comment by hanzhida** [comment]
same problem. I met this when run "flutter dector", it just hung at Unzipping Dart SDK... forever.
I work on Windows

**Comment by devoncarew** [comment]
This issue was moved to flutter/flutter-intellij#1961
