### ISSUE TITLE
Flickering issue with PageView and GestureDetector on Android

### ISSUE THREAD

**Issue by swabzz** [flutter/flutter#154825]
On Android, when using a PageView widget with a GestureDetector, the page flickers during transitions. The issue does not occur on iOS. The flickering happens particularly when selecting options inside the GestureDetector

Steps to Reproduce:
  1. Create a PageView with multiple pages.
  2. Add a GestureDetector inside the pages.
  3. Run the app on an Android device and observe the flickering during transitions.

Expected Behavior: The page should transition smoothly without flickering.

Actual Behavior: The page flickers during transitions.

Additional Information: Tested on Android 11 and 12, devices: Pixel 4a, Samsung Galaxy S21.

**Comment by darshankawar** [comment]
@swabzz 
Are you seeing this with Impeller enabled ? Can you provide us minimal but complete reproducible code sample (ex: main.dart) without third party package implementation that shows the reported behavior ?
Also, provide `flutter doctor -v` and a short video showing the flickering.
