### ISSUE TITLE
CORS image requests requiring credentials fail to load with HTML renderer

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#154809]
An internal Google customer using the HTML renderer has reported that the images in their app have stopped loading. The images are loaded from a different domain and they require credentials. 

See internal bug b/365475814

It seems like https://github.com/flutter/engine/commit/4844cb489b3fa599cad5b0e499fb709ac490f5ed is the culprit. Could we roll it back seeing as it breaks a customer in production? We might need a flag or some other configuring to make this change.

**Comment by eyebrowsoffire** [comment]
I made a revert of the change here: https://github.com/flutter/engine/pull/55042
