### ISSUE TITLE
AssetImage not recognizing screen densities and not switching image accordingly.

### ISSUE THREAD

**Issue by hatch1315** [flutter/flutter#15487]
## Steps to Reproduce
To reproduce this you will need an image with 3 different variations for the different screen densities.  I'm having an issue with the AssetImage. Using a minimum test case and it appears to not use any image except the 1.0x version.  Running this on an iphone X and the image isn't very clear.  Here is my main.dart.
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Image(
            width: 300.0,
            height: 300.0,
            fit: BoxFit.cover,
            image: new AssetImage('/images/testImage.png')
        )
      ),
       // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
I have each of the different densities within different folders within the the images folder so `/images/2.0x/testImage.png` `/images/3.0x/textImage.png` shown here.  
![screen shot 2018-03-13 at 1 02 36 pm](https://user-images.githubusercontent.com/21246420/37357457-df5cbb7a-26be-11e8-86f7-7f145d55b219.png)
If I specify which density to use it looks good but I was of the understanding AssetImage would do that for me. I have followed this guide and don't see what I am doing wrong https://flutter.io/assets-and-images/#resolution-aware. 
Here is where I specify the asset in my pubspec.yaml.
```
flutter:
  uses-material-design: true
  assets:
    - images/testImage.png
```
I also tried specifying the size variants with no luck. Here are screen shots for the minimum test case. I made the image pretty large to make the differences obvious. This first one is using the code shown above with out specifying which variant to use: 
![image uploaded from ios](https://user-images.githubusercontent.com/21246420/37357283-6797a758-26be-11e8-8252-d704b2669714.png)

This second image is when I hardcode to use the 3.0x variant( `new AssetImage('/images/3.0x/testImage.png')`): 
![image uploaded from ios 1](https://user-images.githubusercontent.com/21246420/37357364-a1c615fe-26be-11e8-9524-b46680145b25.png)

## Flutter Doctor

[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.1 17B1003, locale en-US)
    • Flutter version 0.1.5 at /Users/caleb/flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/caleb/Library/Android/sdk
    • Android NDK at /Users/caleb/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 26.0.2
    • ANDROID_HOME = /Users/caleb/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
You have to actually list the alternative assets in the pubspec.yaml as well. See <https://master-docs-flutter-io.firebaseapp.com/flutter/painting/AssetImage-class.html>.

**Comment by hatch1315** [comment]
@Hixie I have tried this as such.
```
flutter:
  uses-material-design: true
  assets:
    - images/testImage.png
    - images/2.0x/testImage.png
    - images/3.0x/testImage.png
```
Still no luck.

**Comment by hatch1315** [comment]
I was looking through the changelog and saw that leading slashes weren't supported anymore for AssetImages.  So changing my image path to `images/testImage.png` fixed my issue.

**Comment by Hixie** [comment]
Oh wow I didn't notice the leading slash. That's weird though, it still rendered _something_, just not adaptive? We should do better than that, probably always render nothing and have an error message.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zeienko-vitalii** [comment]
Try fit: BoxFit.fill

**Comment by Kedar17developer** [comment]
@hatch1315 does that problem solved by mentioning it as 
flutter:
  uses-material-design: true
  assets:
    - images/testImage.png
**or**
flutter:
  uses-material-design: true
  assets:
    - images/testImage.png
    - images/2.0x/testImage.png
    - images/3.0x/testImage.png

am facing this issue, every time it is actually picking from 1.0 on Android irrespective of device resolution. 
Any help is appreciated.

**Comment by majdjlassi** [comment]
any solution for this problem ?
it always pick images from 1.0x folder which is the root folder "images"
assets:
 - images :
    - image1.png
    - image2.png
    - 1.5x :
       - image1.png
       - image2.png
    - 2.0x :
       - image1.png
       - image2.png
    - 3.0x :
       - image1.png
       - image2.png
    - 4.0x :
       - image1.png
       - image2.png

pubspec.yaml :

flutter:
  uses-material-design: true
  assets:
    - assets/images/

Any help pleasen thanks in advance.

**Comment by darshankawar** [comment]
Hi @hatch1315,
Per your last message, do you feel that this issue can be closed ?

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
