### ISSUE TITLE
! Doctor found issues in 3 categories.

### ISSUE THREAD

**Issue by GentleMotive** [flutter/flutter#154902]
### Steps to reproduce

I've spent the last couple of days trying to fix these issues to no avail. Any help would be greatly appreciated. 

Thank you all!

![Flutter doctor errors](https://github.com/user-attachments/assets/10d53bcd-3846-4926-b501-4936dad43f37)

### Actual results

Administrator: Git CMD
* failed to start daemon
adb.exe: failed to check server version: cannot connect to daemon
[âˆš] Flutter (Channel stable, v1.12.13+hotfix. 8, on Microsoft Windows [Version 6.1.7601], locale en-US)
X
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
X Android license status unknown.
Try re-installing or updating your Android SDK_Manager.
See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[!] Android Studio
X Flutter plugin not installed; this adds Flutter specific functionality. X Dart plugin not installed; this adds Dart specific functionality. X android-studio-dir = ''C:\Program
X Android Studio not found at C:\Program
[0] Connected device (the doctor check crashed)
X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
C:\Users\NST-Kevin\AppData\Local\Android\sdk\platform-tools\adb.exe
! Doctor found issues in 3 categories.
C:\Users\NST-Kevin>

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
You have incorrectly set your `ANDROID_HOME` environment variable. See https://stackoverflow.com/questions/26356359/error-android-home-is-not-set-and-android-command-not-in-your-path-you-must for how you can correct this
You have also incorrectly set your `android-studio-dir`. See https://stackoverflow.com/questions/66170639/android-studio-android-studio-dir-location for how you can correct this. 

You are also using a version of flutter that is outdated. Consider upgrading to the latest version of flutter stable. 

Closing from here as this is an issue with incorrect configuration and not a flutter issue. 

Thank you
