### ISSUE TITLE
[DeviceLab] Minions failing to remotely sign x509 certificates for machine_tokend.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#154938]
From @kentnguyen99:

mac-27 and mac-30 masked as dead due to out of sync with Salt master.  When I ran command "salt-call state.apply" and getting error regarding certificate issue.  Can you look in this issue?

```
ID: /opt/luci/machine_tokend/run.sh
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-mac-30.mtv.corp.google.com.crt
     Started: 09:41:28.490761
    Duration: 0.003 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh >/dev/null 2>&1
    Function: cron.present
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-mac-30.mtv.corp.google.com.crt
     Started: 09:41:28.491236
    Duration: 0.002 ms
     Changes:
```

Got same error for Linux Bots when ran command "salt-call state.apply".

```
ID: /etc/pki/flutter-devicelab-linux-64.mtv.corp.google.com.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2276, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1276, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/x509.py", line 687, in certificate_managed
                  contents = __salt__["x509.create_certificate"](text=True, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/x509.py", line 1454, in create_certificate
                  if not any(certs):
              TypeError: 'NoneType' object is not iterable
     Started: 10:40:22.503283
    Duration: 219.605 ms
     Changes:
```

**Comment by bdero** [comment]
Okay, I think these are two different issues. I'm going to focus on the macOS issues in this bug and push the `x509.certificate_managed` one into a separate issue.

[flutter-devicelab-mac-27](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-27) and flutter-[flutter-devicelab-mac-30](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-30) are registered as dead in swarming.

**Comment by bdero** [comment]
Actually they are probably the same issue. Both are related to machine_tokend certs.

**Comment by bdero** [comment]
Okay, so the master's minion logs contain a bunch of x509 signing jobs. The last successful one was before all the minions got disconnected:
```
2024-08-28 08:05:18,787 [salt.minion :1693][INFO ][20062] User root Executing command x509.sign_remote_certificate with jid 20240828150518766651
2024-08-28 08:05:18,847 [salt.minion :1890][INFO ][2342530] Starting a new job 20240828150518766651 with PID 2342530
2024-08-28 08:05:18,862 [salt.minion :2173][INFO ][2342530] Returning information for job: 20240828150518766651
```

For some reason, the master's key keeps getting removed from the accepted keys list, causing the minion on the master to not stay connected to the master. Probably a symptom of the problem.

```
Unaccepted Keys:
salt-flutter.us-central1-b.c.fuchsia-infra.internal
```

**Comment by kentnguyen99** [comment]
Yes, both mac-27 and mac-30 out of sync with Salt master due to both machines need to re-sync with Salt master again but Salt master could not regenerate new tokens file for both clients.

**Comment by bdero** [comment]
Eliminating some red herrings:

As soon as the master's minion reconnects (and periodically afterwards), it throws this error rendering `base:master.contents`:
```
2024-09-10 13:05:51,896 [salt.state       :1179][INFO    ][1233541] Loading fresh modules for state activity
2024-09-10 13:05:52,046 [salt.utils.templates:274 ][ERROR   ][1233541] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 6, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 410, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'salt.utils.context.NamespacedDictWrapper object' has no attribute 'master'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 261, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 509, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'salt.utils.context.NamespacedDictWrapper object' has no attribute 'master'
2024-09-10 13:05:52,046 [salt.state       :4038][CRITICAL][1233541] Rendering SLS 'base:master.contents' failed: Jinja variable 'salt.utils.context.NamespacedDictWrapper object' has no attribute 'master'
```

However, I don't think this has anything to do with the x509 issue since this has been being continually pooped into the logs since `2024-07-07` (the log cutoff).

In the master logs, we have a continuous stream of:
```
2024-08-05 05:44:47,646 [salt.utils.event :905 ][ERROR   ][3448452] Event iteration failed with exception: 'user'
```
and
```
2024-08-05 05:46:01,794 [salt.transport.ipc:208 ][ERROR   ][3447791] Exception occurred while handling stream: 
```

...which are also not anomalous and present since the beginning of the log stream.

**Comment by kentnguyen99** [comment]
flutter@flutter-devicelab-linux-64:~/Downloads$ sudo systemctl status salt-minion
● salt-minion.service - The Salt Minion
     Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-09-10 16:50:17 PDT; 4min 33s ago
       Docs: man:salt-minion(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltproject.io/en/latest/contents.html
   Main PID: 2729 (salt-minion)
      Tasks: 7 (limit: 8962)
     Memory: 52.4M
     CGroup: /system.slice/salt-minion.service
             ├─2729 /usr/bin/python3 /usr/bin/salt-minion
             └─2735 /usr/bin/python3 /usr/bin/salt-minion

Sep 10 16:53:12 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:53:22 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:53:32 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:53:43 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:53:53 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:54:03 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:54:13 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:54:23 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:54:34 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Sep 10 16:54:44 flutter-devicelab-linux-64 salt-minion[2735]: [ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate

**Comment by bdero** [comment]
I just finished working out the problem with https://github.com/flutter/flutter/issues/154881, so getting back to this.

**Comment by bdero** [comment]
@kentnguyen99 I re-accepted the `flutter-devicelab-linux-64` key. I haven't resolved the x509 issue yet, though.

**Comment by bdero** [comment]
It's erroring out when checking for an error. :^)
```
   1452         if not any(certs):
   1453             raise salt.exceptions.SaltInvocationError(
   1454                 "ca_server did not respond"
   1455                 " salt master must permit peers to"
   1456                 " call the sign_remote_certificate function."
   1457             )
```

The module is publishing `x509.sign_remote_certificate` and it's returning `None` rather than an interable.

```
   1445         certs = __salt__["publish.publish"](
   1446             tgt=ca_server,
   1447             fun="x509.sign_remote_certificate",
   1448             arg=salt.utils.data.decode_dict(kwargs, to_str=True),
   1449             timeout=30,
   1450         )
```

**Comment by bdero** [comment]
`/etc/salt/master.d/peer.conf` looks correct:

```
peer:
  .*:
    - x509.sign_remote_certificate
```

**Comment by bdero** [comment]
`ca_server` is being resolved in a jinja template like this: `grains.master | replace(".endpoints.", ".c.") | replace(".cloud.goog", ".internal")`

Grain `master` is set to `salt-flutter.endpoints.fuchsia-infra.cloud.goog` on all the minions. So it's ending up as `salt-flutter.c.fuchsia-infra.internal`.

However, this is not the correct ID of the master's minion. It's self-identifying as `salt-flutter.us-central1-b.c.fuchsia-infra.internal`, which is what `hostname --fqdn` resolves to right now. The GCP hosts updater is managing `/etc/hosts` and appears to have started including the zone at some point.

Further, the master's minion key is no longer auto-accepting and it's periodically regenerating for some reason, so the master's minion keeps getting disconnected.

**Comment by bdero** [comment]
Got it auto-accepting by adding the fqdn to `/etc/salt/autosign_grains/fqdn`.

Attempted to fix the mapping with this diff:
```diff
diff --git a/salt/ca/map.jinja b/salt/ca/map.jinja
index fd6a772b..e52bc6ec 100644
--- a/salt/ca/map.jinja
+++ b/salt/ca/map.jinja
@@ -1,6 +1,6 @@
-{# Replaces foo.endpoints.bar.cloud.goog with foo.c.bar.internal #}
+{# Replaces foo.endpoints.bar.cloud.goog with foo.us-central1-b.c.bar.internal #}
 {% set ca = {
-    'ca': grains.master | replace(".endpoints.", ".c.") | replace(".cloud.goog", ".internal"),
+    'ca': grains.master | replace(".endpoints.", ".us-central1-b.c.") | replace(".cloud.goog", ".internal"),
     'crt': '/etc/pki/ca.crt',
     'key': '/etc/pki/ca.key',
 } %}
```

**Comment by bdero** [comment]
Confirmed this is fixed now. Ran `state.apply` on mac-6 and it succeeded for all states:
```
Summary for local
-------------
Succeeded: 47 (changed=13)
Failed:     0
-------------
Total states run:     47
```
