### ISSUE TITLE
Benchmarks regressed by engine roll  🚨

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#154951]
**dashboard:** https://flutter-flutter-perf.skia.org/e/?begin=1725896738&end=1725942380&keys=X74ce0dd231bb0a4be9bf036e5c2197d5&num_commits=50&request_type=1&xbaroffset=42497

**likely culprit:** https://github.com/flutter/engine/pull/55036

**regressed probes:**
  - worst_frame_rasterizer_time_millis

**Comment by jonahwilliams** [comment]
Closing as fixed (check those numbers!)
