### ISSUE TITLE
flutter analyze --no-fatal-infos still threats @Deprecated as fatal

### ISSUE THREAD

**Issue by frederikstonge** [flutter/flutter#154922]
### Steps to reproduce

- Add @Deprecated above on of your class in your package
- Use the deprecated member somewhere
- Call `flutter analyze --no-fatal-infos`

### Expected results

Process should exit with code 0

### Actual results

info • '<DeprecatedClass>' is deprecated and shouldn't be used. <Message> •
          <Path> • deprecated_member_use_from_same_package

Even if it's listed as "info", it still fails with exit code 1.

### Code sample

```dart
@Deprecated
class Test {
}

main() {
  final test = Test();
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-CA)
    • Flutter version 3.24.1 on channel stable at /Users/fstonge/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fstonge/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)            
    • iPhone 15 Pro (mobile)          • 1D88873D-7CD7-458D-B4E3-6D4E10EAD6A2 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
@frederikstonge 
I think this will need to be reported in dedicated repo https://github.com/dart-lang/sdk/issues, as with `dart analyze` it also shows same info warning.
Closing from here. If you get directed here, write in comments and I'll reopen it.
