### ISSUE TITLE
Unable to completely remove the dependencies.

### ISSUE THREAD

**Issue by no-chili** [flutter/flutter#154910]
### Steps to reproduce

After removing some packages from pubspec.yaml that are no longer used in the project, an error occurs: “Framework ‘XXX’ not found.” It seems that Xcode is still importing these dependencies. I checked the “Other Linker Flags” in Xcode and found that the related dependencies are still there. Moreover, after manually deleting them, when I run flutter run again, the content I deleted manually reappears. How should I completely remove them?

### Actual results

Make the project clean up unresolved dependencies and run again.

### Logs

[output.txt](https://github.com/user-attachments/files/16942193/output.txt)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.2 on channel stable at /Users/deyongxie/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (6 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/deyongxie/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (5 available)
    • iPhone (mobile)                 • 00008101-000E5086342A001E            • ios            • iOS 17.3.1 21D61
    • iPhone 13 (mobile)              • F6670B47-578C-4117-B589-E7BE1814A852 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by no-chili** [comment]
```
Error (Xcode): Framework 'wakelock' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 13.
```
This package is not even one that I have used before.

**Comment by huycozy** [comment]
Hi @no-chili, I can't reproduce the issue. Can you confirm the following steps on your end?

1. Add `wakelock_plus: ^1.2.8` to `pubspec.yaml`. Run app on iOS device. 

  - Check `ios/.symlinks` and see `wakelock_plus` there.
  
  ```console
  ➜  ios cd .symlinks 
  ➜  .symlinks tree -L 2   
  .
  └── plugins
      ├── package_info_plus -> /Users/huynq/.pub-cache/hosted/pub.dev/package_info_plus-8.0.2/
      └── wakelock_plus -> /Users/huynq/.pub-cache/hosted/pub.dev/wakelock_plus-1.2.8/
  ```
  - Open `ios/Runner.xcworkspace` on XCode and also see `wakelock_plus` inside Build Settings `Other Linker Flags`.


2. Remove `wakelock_plus` from `pubspec.yaml` and run app again. See this error:
```console
Xcode build done.                                           12.1s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
Error launching application on iPhone.
```

Follow the guideline by running `pod install`, `wakelock_plus` is no longer in `.symlinks` directory and inside Build Settings `Other Linker Flags` anymore.

**Comment by no-chili** [comment]
<img width="753" alt="截屏2024-09-10 20 35 29" src="https://github.com/user-attachments/assets/ce188669-5f03-4e08-9486-0197707e8189">
<img width="1387" alt="截屏2024-09-10 20 37 36" src="https://github.com/user-attachments/assets/8e31f6b0-5bd4-4380-b72b-21dbd0d5ef3f">
<img width="595" alt="截屏2024-09-10 21 03 31" src="https://github.com/user-attachments/assets/866a4d5f-8b5c-486c-8783-9b6cc3c97162">
<img width="595" alt="截屏2024-09-10 21 09 30" src="https://github.com/user-attachments/assets/b7b62d44-5295-4abb-9c1b-b232097bcf7d">

The packages hl_image_picker_ios and flutter_aliplayer are ones that I previously used, but now I no longer need them. However, I cannot remove them, otherwise the app won’t run. The wakelock package, I have never used it at all, and wakelock should not refer to wakelock_plus.

**Comment by huycozy** [comment]
>Error (Xcode): The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Do you see this hint from the output console after removing plugin? Will the error disappear if you follow it? 

>The wakelock package, I have never used it at all, and wakelock should not refer to wakelock_plus.

`wakelock_plus` is a community plugin, please file a separate issue to its developer at https://github.com/fluttercommunity/wakelock_plus/issues for better support.

**Comment by no-chili** [comment]
@huycozy 
<img width="434" alt="截屏2024-09-11 13 27 09" src="https://github.com/user-attachments/assets/6d380c8c-c80a-4936-b917-f5839a81bb75">
It has nothing to do with wakelock_plus. I finally got the project running after adding the packages mentioned above. However, if I remove them, the project still throws an error. I’m quite sure I’m not using these packages.

**Comment by huycozy** [comment]
`wakelock` is deprecated and replaced by `wakelock_plus`. Anyway, I used these plugins as yours but saw the similar result as my [above comment](https://github.com/flutter/flutter/issues/154910#issuecomment-2340352931). After executing `pod install`, the project runs well.

```yaml
hl_image_picker_ios: ^1.2.10
flutter_aliplayer: ^6.7.0
wakelock: ^0.6.2
```

Please experiment with a fresh Flutter project and follow the steps I outlined above to check if you encounter a similar outcome. Providing detailed step-by-step validation on a sample isolation will aid in advancing the investigation. If you still see the error, please share a sample project here (GitHub repository is better) so that I can try it on my end.
