### ISSUE TITLE
Add disable prop in SingleChildScrollView

### ISSUE THREAD

**Issue by MajdSallora** [flutter/flutter#154907]
### Use case

When writing separated common widget and add SingleChildScrollView in some cases i want to disable the  SingleChildScrollView because if i put in common widget and use Listview for example it will case render error even if i make 
SingleChildScrollView NeverScrollPhysics so i should to put if statement and repeat same code with and without SingleChildScrollView 

### Proposal

I want to add disable  prop in SingleChildScrollView if its true replacing the SingleChildScrollView in an empty widget

**Comment by huycozy** [comment]
Hi @MajdSallora 
Can you elaborate on what `disable` means in this case? Do you mean if `disable` is true,
1. Will SingleChildScrollView not be rendered in the tree?
2. SingleChildScrollView is still rendered in the tree, but its content/children are not scrollable?

Can you share a minimal sample code for what you have tried?

**Comment by MajdSallora** [comment]
> Hi @MajdSallora Can you elaborate on what `disable` means in this case? Do you mean if `disable` is true,
> 
> 1. Will SingleChildScrollView not be rendered in the tree?
> 2. SingleChildScrollView is still rendered in the tree, but its content/children are not scrollable?
> 
> Can you share a minimal sample code for what you have tried?

Hello @huycozy 
Yes i don't want it to render it 
the code in SingleChildScrollView should be like:

```
class SingleChildScrollView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    if(disable) {
        return SizedBox(child: child);
    }
```

**Comment by huycozy** [comment]
Will the `child` still occupy a space? Have you tried wrapping SingleChildScrollView with a [Visibility](https://api.flutter.dev/flutter/widgets/Visibility-class.html) or [Offstage](https://api.flutter.dev/flutter/widgets/Offstage-class.html) to see if it meets your need? (note: `Visibility.replacement` may fit your case)

**Comment by MajdSallora** [comment]
> Will the `child` still occupy a space? Have you tried wrapping SingleChildScrollView with a [Visibility](https://api.flutter.dev/flutter/widgets/Visibility-class.html) or [Offstage](https://api.flutter.dev/flutter/widgets/Offstage-class.html) to see if it meets your need? (note: `Visibility.replacement` may fit your case)

Yeah it will work Offstage or Visibility but it will repeat the code like this ex:
```
child: disableScroll
                    ? Padding(
                        padding: padding,
                        child: ConstrainedBox(
                          constraints: BoxConstraints(
                            minWidth: context.screenWidth,
                            minHeight: context.screenHeight - appBarHeight,
                          ),
                          child: IntrinsicHeight(
                            child: child,
                          ),
                        ),
                      )
                    : SingleChildScrollView(
                        child: Padding(
                          padding: padding,
                          child: ConstrainedBox(
                            constraints: BoxConstraints(
                              minWidth: context.screenWidth,
                              minHeight: context.screenHeight - appBarHeight,
                            ),
                            child: IntrinsicHeight(
                              child: child,
                            ),
                          ),
                        ),
                      )
```
I don't think this code is clean it would be better if there is prop in SingleChildScrollView

**Comment by MajdSallora** [comment]
@Piinks Hello Kate,
What do you think about add this property?

**Comment by Piinks** [comment]
This is not something we would be likely to add. If you do not want to use a SingleChildScrollView, you can omit it from your widget tree.

**Comment by huycozy** [comment]
@MajdSallora I will proceed with the closure as there are solutions available as previously stated. If you propose another change, please open another issue.
