### ISSUE TITLE
[ui] breaking change: make the default TileMode for image filters default to the "best" tile mode for the context.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#154935]
As in https://github.com/flutter/flutter/issues/110318 , the default tile mode of clamp can cause rendering artifacts along the edges of most blurs. This happens because clamp can double the strength of the edge pixel, which for a blur gets smeared across a large area.

In other cases, clamp can lead to rendering that _is_ correct but looks like a rendering error (is unintuitive). For example see https://x.com/SuprDeclarative/status/1798180992446042329 .

Are there cases where changing the tile mode to decal leads to changes that aren't an improvement? I don't actually think so. While the tile mode has a large impact when using canvas APIs like drawImageRect, I think the image filter tile mode always considers the output size of whatever input geometry, so it can only ever impact edge pixels. may be wrong.

FYI @flar  / @matanlurey

**Comment by flar** [comment]
There is no TileMode setting for the drawImage calls. Only ImageFilter objects have that as an argument.

**Comment by jonahwilliams** [comment]
Right, I mean if you took something like a drawImage rect and gave it an image filter, I think decal has the same approximate impact as if  you were using the ImageFiltered widget.

**Comment by PaulGrandperrin** [comment]
Hi @jonahwilliams,
As I explained in https://github.com/flutter/flutter/issues/110318#issuecomment-2366762364, I don't think this will solve the issue that people are complaining about.

In the DartPad I shared, I'm using `TileMode.decal` and the glitch is visually as strong as with ``TileMode.clamp``

**Comment by flar** [comment]
> Hi @jonahwilliams, As I explained in [#110318 (comment)](https://github.com/flutter/flutter/issues/110318#issuecomment-2366762364), I don't think this will solve the issue that people are complaining about.
> 
> In the DartPad I shared, I'm using `TileMode.decal` and the glitch is visually as strong as with `TileMode.clamp`

This is a problem with our Skia backend. I filed a bug on this (https://github.com/flutter/flutter/issues/155961), we're working with Skia to find out if we can fix it ourselves ("are we holding this right?") or if they need to expose something to enable us to fix the bug.

The suggestions do work with Impeller, though. Mirror is probably the best mode to use overall. Decal does avoid the flashing (on Impeller), but it shows detail at the edges that you probably want obscured. Repeat is similar to Mirror, but is fetching data from "the far end" of the surface which might not make sense in practice.

**Comment by jonahwilliams** [comment]
We've updated this proposal to use decal for saveLayers and mirror for bdfs.
