### ISSUE TITLE
Add a validator function on the dropdown menu 

### ISSUE THREAD

**Issue by muchirajunior** [flutter/flutter#154975]
### Use case

When trying to validate a form where there is a dropdownmenu widget selection it hard to validate because it does not have a option to validate and  you have to do add a manualy check like if statement.

### Proposal

Add an onValidate function to the DropdoenMenu class that will work  with the forms validations.

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/152131

**Comment by expectopatronam** [comment]
Shall i implement this by changing the Textfield to textformfeild and add a validator as argument?
