### ISSUE TITLE
Questions to add to FAQ

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#15496]
Here are some questions from a potential partner meeting.  I've filled in some stub answers.  @mjohnsullivan 

- [ ] Is it possible to have portions written in Flutter or is it 100% in?
Yes. We've not paved this path super well yet, but it is possible.  @mit-mit knows the bug.

- [ ] Possible to compile Dart to JavaScript
Yes.  This is exactly how Dart for the Web works and there is a robust toolchain around this.

- [ ] Accessibility is top focus area for our company; how does Flutter support?
Flutter is used by some of Google's major apps (e.g. AdWords) who have strict accessibility requirements.  Flutter supports screen readers, large text, color contrast, basic hardware switch control.

- [ ] What is the perf cost to bridging between native code and Dart?
We recommend working through platform-channels, which is an asynchronous message passing API.  We don't currently expose a direct synchronous "bridge" for calls or exposing objects directly into Dart.

- [ ] What does adoption look like within Google?
There are many teams using Flutter within Google, most of whom have not yet shipped their apps publicly.  Public ones we can talk about are AdWords and Google's CRM Application "Greentea".

- [ ] How do things like scrolling work across iOS and Android? 
Flutter implements its own custom implementations of iOS and Android scrolling.  However we've worked hard to carefully match the platform scrolling feel on both platforms.

- [ ] When Apple make changes (e.g. iOS 12, iPhone vNext), how quickly will Flutter be able to respond?
Historically we've responded before Apple publicly releases new features.  For example Flutter supported the iPhone X notch and iOS 11 style navigation before launch.  There is always more to do, but generally we've not found much trouble keeping up with visual changes in iOS or Android.  The system is also designed such that one shouldn't have to depend on the Flutter team, as exemplified by the community building things like iOS video controls: https://pub.dartlang.org/packages/chewie or even a system settings implementation in Flutter without any help from Google's Flutter contributors: https://github.com/matthinc/flutter_cupertino_settings

**Comment by zoechi** [comment]
> Possible to compile Dart to JavaScript

You might add that Dart isn't compiled to JS in Flutter to avoid confusion for people who land on this answer for other reasons

**Comment by mit-mit** [comment]
> Is it possible to have portions written in Flutter or is it 100% in?

The bug is: https://github.com/flutter/flutter/issues/14821

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1850](https://github.com/flutter/website/issues/1850) via [**ZenHub**](https://www.zenhub.com/)
