### ISSUE TITLE
iOS FlutterMaster 3.26.0-1.0.pre.75: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

### ISSUE THREAD

**Issue by Heidi0039** [flutter/flutter#154990]
### Steps to reproduce

1. Clone https://github.com/rohit11/Flutter_PlatformView.
I stumbled upon this public example when trying to reproduce this issue without setting up too much myself, and it perfectly illustrates the problem. Thanks rohit11 ;)

2. Replace myapp.dart with the one from CodeSample

3. Tap the button to start Autopush; Wait a few seconds.

### Expected results

The App can Push and Pop without problems

### Actual results

After a few Push/Pop cycles the app terminates with an exception

### Code sample

<details open><summary>main.dart</summary>

A simple MaterialApp with a Navigator.
```dart
import 'package:flutter/material.dart';

import 'src/myapp.dart';

void main() => runApp(RootApp());

class RootApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Platform View example'),
        ),
        body: Navigator(
          onGenerateRoute: (settings) => MaterialPageRoute(
            builder: (context) => const MyApp(),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details open><summary>Code sample src/myapp.dart</summary>

A dummy page containing lots of UiKitView to illustrate the problem.
```dart
import 'package:flutter/material.dart';

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  void _autoPush() {
    Future.delayed(Duration(seconds: 2), () {
      print("PUSH");
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (context) => const MyApp(),
        ),
      );
      _autoPop();
    });
  }

  void _autoPop() {
    Future.delayed(Duration(seconds: 2), () {
      print("POP");
      if (Navigator.of(context).canPop()) {
        Navigator.of(context).pop();
      }
      _autoPush();
    });
  }

  Widget build(context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Platform View'),
        ),
        body: SafeArea(
          child: Stack(
            children: [
              Stack(
                children: List<Widget>.generate(
                  100,
                  (index) {
                    return SizedBox(
                      width: 300,
                      height: 100,
                      child: UiKitView(
                        viewType: 'NativeView',
                      ),
                    );
                  },
                ),
              ),
              Align(
                alignment: Alignment.bottomCenter,
                child: TextButton(
                  child: Text("Start Autopush"),
                  onPressed: () {
                    _autoPush();
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="2056" alt="Screenshot 2024-09-11 at 11 12 01" src="https://github.com/user-attachments/assets/edae109f-4976-4952-b89e-b2a0241ed65d">

</details>

### Logs

<details open><summary>Logs</summary>

```console
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(0x18b090f20 0x182f4a018 0x18b02fb60 0x1066075a0 0x10662c3fc 0x106630534 0x18b0c4a2c 0x18b0c46d0 0x18b0c422c 0x18b060888 0x18b05fcd8 0x1cff101a8 0x18d69890c 0x18d74c9d0 0x18d8c6384 0x102b986d0 0x102b98648 0x102b9874c 0x1ae711e4c)
libc++abi: terminating due to uncaught exception of type NSException```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.26.0-1.0.pre.75, on macOS 15.0 24A5320a darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.92.2)
[✓] Connected device (6 available)
[✓] Network resources```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Heidi0039 
Are you seeing this on simulator or actual physical device ?
I tried on iOS simulator but it didn't crash for me.

**Comment by Heidi0039** [comment]
I am using an actual device.

I am using an iPhone 14 Pro running the latest iOS 17.
I can also reproduce this with a iPhone 13 Pro running the current public beta of iOS 18.
Also a iPhone XR running iOS 17.5.1

I have seen similar tickets like the one you linked, but they all seem old and already resolved. I am unsure if there is any connection to it, but it does sound intriguing.

If there is any other info I can provide to help getting this fixed please let me know! I am really looking forward to the current master branch for some other fixes in there that I urgently need.

**Comment by curt-weber** [comment]
@Heidi0039 - are you able to reproduce this on latest master (78)? We have seen this before but I just ran your sample project on master on device for awhile and couldn't get it to reproduce.

**Comment by darshankawar** [comment]
@Heidi0039 
Please try to latest master to see if you still see the crash or not.
Also, are you seeing this only after upgrading to master or previous versions as well ? Stable (3.24 and 3.22)

**Comment by Heidi0039** [comment]
I have just changed my flutter from 3.26.0-1.0.pre.75 to 3.26.0-1.0.pre.97 and can no longer reproduce this issue. It appears to be completely gone in the current master branch.

Just for completion sake: The crash was not present in the current stable branch and only was introduced recently in the master branch.
