### ISSUE TITLE
Auto Handling of Sign-out in Firebase Auth for all Providers

### ISSUE THREAD

**Issue by Purus** [flutter/flutter#15490]
Firebase Auth should handle sign-out from each network (Google, Facebook..) automatically instead of user calling sign-out methods individually for each network. 

For example, currently we should call `_googleSignIn.signOut()` to avoid silent re-login after the user is signed-out from Firebase. This should be taken care of the package automatically.

**Comment by lucasmatoscc** [comment]
For google:
`GoogleSignIn.channel.invokeMethod("signOut");`

**Comment by Purus** [comment]
It's really difficult to develop an app which support multiple social login providers. This unified feature is much needed to make use of Firebase social login.

**Comment by rma6** [comment]
I'm having troubble Signing-out. I'm calling the following when I tap a button:
```
final GoogleSignIn _googleSignIn = GoogleSignIn();
final FirebaseAuth _auth = FirebaseAuth.instance;

static Future<void> _signOut() async {
    await _auth.signOut();
    await _googleSignIn.signOut();
  }
```
But when I call `googleUser.authentication` on my SignIn function it skips the google login page but returns a valid GoogleSignInAuthentication.
What could I do to fix this?

**Comment by kroikie** [comment]
@Purus

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/891. Any further collaboration will be done there.
