### ISSUE TITLE
Add a way to supply a custom `ParagraphBuilder`

### ISSUE THREAD

**Issue by fischerscode** [flutter/flutter#154947]
### Use case

`ParagraphBuilder` is the abstraction for deciding how paragraphs should be layed out. But widgets like `Text.rich` don't support supplying a custom `ParagraphBuilder`. As described in #154946, it would be useful if one could supply a custom `ParagraphBuilder` to build a chat bubble.

This would also enable packages to provide custom layout algorithms.

### Proposal

I'd suggest adding a `ParagraphBuilderFactory` parameter to the relevant widgets that can be called to receive a custom `ParagraphBuilder`. This parameter could be nullable and fallback to the default `_NativeParagraphBuilder`.

**Comment by fischerscode** [comment]
*I've started implementing this [here](https://github.com/fischerscode/flutter/tree/fix-154947). But I run into #154958 while using my implementation.*

**Comment by jonahwilliams** [comment]
The Native types are not overridable, as their implementation is in the engine and the engine needs to make assumptions about the objects it interacts with. I would recommend pursuing a different strategy.
