### ISSUE TITLE
[MightBeGoodToHave] Add warning when no internet connection on NetworkImage

### ISSUE THREAD

**Issue by pavillet** [flutter/flutter#15499]
I think the NetworkImage ( and I'm sure other Classes too) should warn at least in debug mode that there is no available connection.

My experience is, I just spent the last hour trying 10's of different layout to understand why the NetworkImage would just not display.
Turns out the emulator I was using had no connection to the internet, only local ( deleting and reinstalling it did the trick).

Granted it's on me, but a warning would have been nice and pointed me in the right direction much faster.

**Comment by Hixie** [comment]
This is basically a specific request that will be handled when we resolve https://github.com/flutter/flutter/issues/9676. I'm going to close this issue in favour of that bug.

**Comment by pavillet** [comment]
Please do, sorry for not seeing it !
