### ISSUE TITLE
Add a way to inline align Widgets to the end of TextSpans

### ISSUE THREAD

**Issue by fischerscode** [flutter/flutter#154946]
### Use case

For a chat app, it's a common design pattern to build a chat bubble that shows the send time (a Widget) inline in with the content (a TextSpan), but aligned to the end of the text direction. If the send time does not fit in the last line, it should be placed in the next line while still being aligned to the end.

The following visualizes the desired layout. The black boxes represent the main content and the red box the send time.
![desired](https://github.com/user-attachments/assets/4e25f298-b744-43d2-ac1f-a531cb1347e5)

### Proposal

From a first glance, the desired layout seems like it should be easily achievable. But at a closer look, it's currently not possible to achieve this in a 'native' / non hacking way.

I think, either of the following enhancements could enable users to achieve such a design pattern.
1. A way to change the text alignment withing the paragraph. If `TextAlign` was a part of the `TextStyle`, then users could align the first span to the left and the second to the right. (There might be edge cases, where the behavior of such a feature would have to be defined.) #79749 also requests this feature, but proposes an insufficient implementation.
2. Add a way to supply a custom `ParagraphBuilder` when using `Text.rich`. Then users could define a custom `InlineSpan` and position it in a special way. This change should be simple, but it might be hard to supply a custom `ParagraphBuilder`. (#154947)
3. Add a `InlineSpan` that acts as a spacer with a dynamic width.
4. Something like #135435 or #126775 to receive the position of the last span and using this to layout the red box. 

Issues that do not solve this problem, but might be worth considering when implementing a solution:
- #128218
- #61081

My preference:
- Option 1 feels like it's the most elegant.
- Option 2 is the hardest for the user, since the custom `ParagraphBuilder` might have to be implemented from scratch. But never the less, I feel like it should be possible to supply a custom `ParagraphBuilder`.
- Option 3 might not be generalized enough.
- Option 4 might be costly, since it most users would use the positioning the update the state of an `StatefulWidget` and trigger a new layout phase.

**Comment by fischerscode** [comment]
Turns out #154958 blocks the Option 2 from being an elegant solution to the problem.

**Comment by Piinks** [comment]
This looks like an issue that is primarily a reference to other issues. Is there something in this issue that is not covered by the already open issues? Per [Issue Hygiene](https://github.com/flutter/flutter/tree/master/docs/contributing/issue_hygiene), we do not keep duplicates of existing issues to prevent confusion, separate conversation threads, or the chance that multiple people will end up working on the same thing.
