### ISSUE TITLE
run_tests cares about what directory it's launched in

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#155]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Aug 31, 2015 at 18:21 GMT_
_Originally opened as https://github.com/flutter/engine/issues/964_

----

You should be able to run run_tests from anywhere in your tree. Right now you have to run it from //sky/unit/, as far as I can tell (at least when passing it a specific test's file path).

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Monday Aug 31, 2015 at 20:39 GMT_

----

You can actually run `run_tests` from anywhere.  If you want to run a specific test, you need to pass the path relative to `//sky/unit`, which I agree isn't great.

**Comment by abarth** [comment]
We've got a better bug on file about this issue.
