### ISSUE TITLE
Many `Mac_ios` build failures due to "resource exhaustion"

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#155088]
All of these purple squares (in the 2nd row) are build failures due to "resource exhaustion":

<img width="1007" alt="image" src="https://github.com/user-attachments/assets/34b9fcee-7cec-4eb1-acb5-6763a837b68b">

On the first row, you'll also see multiple builds that succeeded after retry. Those also failed due to resource exhaustion initially, then they succeeded upon retry.

Something similar happened on September 9th:

<img width="975" alt="image" src="https://github.com/user-attachments/assets/7cf0ed36-156a-4426-9069-86bb89e4da2b">
<hr>

_**One thing in common in these 2 occurrences is they both happened soon after 21:00 at night Pacific Time (or after midnight Eastern Time).**_ Are the devices being rebooted at that time causing a shortage in resources? Is there a config update that's pushed at that time? Any periodic tasks scheduled for that time?

**Comment by mdebbar** [comment]
One particular build suffered the most from this failure:

<img width="496" alt="image" src="https://github.com/user-attachments/assets/e80b1b26-ae51-4518-b3fe-acaacb04093e">

<hr>

This build always runs on `-m9` bots.

**Comment by christopherfujino** [comment]
Thanks for the detailed issue, I'll investigate now.

**Comment by christopherfujino** [comment]
> One particular build suffered the most from this failure:
> 
> <img alt="image" width="496" src="https://private-user-images.githubusercontent.com/1278212/366912648-e80b1b26-ae51-4518-b3fe-acaacb04093e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjgyMzEsIm5iZiI6MTcyNjE2NzkzMSwicGF0aCI6Ii8xMjc4MjEyLzM2NjkxMjY0OC1lODBiMWIyNi1hZTUxLTQ1MTgtYjNmZS1hY2FhY2IwNDA5M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTkwNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ1MmYzNzM0MzdhMzNkY2Y3YTc2YzY4YWQ1ZTBkZWFkYzA4OGY5ZjJkZDZlNWM5M2RlM2Y1NmUxZTY5NmFjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wb1EVgJqhjWElushKEPHcFeaAWMnpI1GYixQC0H9fJs">
> This build always runs on `-m9` bots.

Here's an example swarming task: https://chromium-swarm.appspot.com/task?id=6bfcb3cc22783e10&o=true&w=true

And here's the list of bots that could possibly run this: https://chromium-swarm.appspot.com/botlist?f=cpu%3Ax86&f=device_os%3AiOS-17&f=os%3AMac-13%7CMac-14&f=pool%3Aluci.flutter.prod

And they're all currently alive.

> This build always runs on -m9 bots.

The scheduler task for this (e.g. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_build_test%20flutter_gallery__transition_perf_e2e_ios/7641/infra) runs on an -m9 bot, but the actual build that's timing out due to resource exhaustion (e.g. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/453350/infra) is a devicelab build.

**Comment by christopherfujino** [comment]
> And here's the list of bots that could possibly run this: https://chromium-swarm.appspot.com/botlist?f=cpu%3Ax86&f=device_os%3AiOS-17&f=os%3AMac-13%7CMac-14&f=pool%3Aluci.flutter.prod
> 
> And they're all currently alive.

Of those bots, I notice that mac-25 ([#155099](https://github.com/flutter/flutter/issues/155099)) and mac-28 ([#155053](https://github.com/flutter/flutter/issues/155053)) were recently down and needed to be manually recovered.

**Comment by christopherfujino** [comment]
Ahh, I know what it was, around this time I scheduled 56 LED builds to test out a PR, that must have exhausted our capacity for the actual tree: https://github.com/flutter/flutter/pull/155052#issuecomment-2344949929

As we seem to have recovered, I will close this. AI is next time I test a PR by scheduling a ton of prod LED builds, I should ensure the priority is lower than that of regular post-submit.
