### ISSUE TITLE
Gallery App has Menus

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1550]
From https://www.google.com/design/spec/components/menus.html

- [ ] Simple
- [ ] Cascading
- [ ] Scrollable
- [ ] Disabled items
- [ ] Checkmark selections
- [ ] Tested with text field
- [ ] Tested with app bar
- [ ] Icon items

**Comment by HansMuller** [comment]
Support for cascading menu items is a tablet/desktop feature, deferring that for now. See https://github.com/flutter/flutter/issues/2242

Support for scrolling menus is still TBD, deferring that for now too. See https://github.com/flutter/flutter/issues/2243

Support for a text editing menu will be included in a separate gallery demo.  See https://github.com/flutter/flutter/issues/2244

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/2170
