### ISSUE TITLE
Add a floating property to SliverResizingHeader and PinnedHeaderSliver

### ISSUE THREAD

**Issue by k-ane** [flutter/flutter#155064]
### Use case

In the recent stable release of Flutter 3.24, it was implied that you could use these fantastic new widgets to achieve a floating effect. However it is not supported or trivial to implement for users.

![CleanShot 2024-09-12 at 14 05 14](https://github.com/user-attachments/assets/a8db3b68-158f-415e-af36-2a4175f78815)

### Proposal

Ideally both new widgets would support a floating optinon.

For PinnedHeaderSliver, it would slide the child out of view when scrolling down, then slide it back into view when scrolling up.

For SliverResizingHeader it could work the same way except that when the list is scrolled, it would show minExtentPrototype instead of child.

**Comment by Piinks** [comment]
The blog post had an error, and was referring to the [SliverFloatingHeader](https://main-api.flutter.dev/flutter/widgets/SliverFloatingHeader-class.html), which did not make it into this latest stable release. It will be released in the next one.

SliverResizingHeader and PinnedHeaderSliver are intended to be atomically featured, like SliverFloatingHeader for such combinations.

We will not be adding a floating property to SliverResizingHeader or PinnedHeaderSliver, for a sliver that does a bunch of these features all in one, use SliverAppBar.
