### ISSUE TITLE
Gesture not working with STB control

### ISSUE THREAD

**Issue by MohammadAsefPoya** [flutter/flutter#155000]
### Steps to reproduce

Create a flutter project and launch a website using webview_flutter then run this project inside a STB you will see that I can do nothing with the rendered website no clicking no scrolling and so on

### Expected results

I expected that when pressed on up and down button of STB it should focus on buttons , tabs and everything that is clickable in website also do scrolling 

### Actual results

Now that I run on STB I can do nothing none of the button from physical control of STB working well

### Code sample

<details open><summary>Code sample</summary>

```dart
void initState() {
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onHttpError: (HttpResponseError error) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse('https://rahafoundation.af'));
    super.initState();
  }

WebViewWidget(
            controller: _controller,
          ),
</details>


### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@MohammadAsefPoya 
What flutter version are you seeing this on ? Can you provide `flutter doctor -v` ?
What STB version are you using which shows the behavior ? Can you provide STB device details ?
Is it only occuring when you use webview ? Without it, does the navigation / gesture work properly ?

**Comment by MohammadAsefPoya** [comment]
Here is flutter doctore -v result `[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19044.4894], locale en-US)
    • Flutter version 3.24.1 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\My PC\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2024.1)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.4894]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 128.0.6613.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.` I am using Xiaomi TV Box S 2nd generation when I open website from STB browser it has pointer like mouse that appear and controlled by physical control of STB and can do all functionalities like scrolling and clicking but when use webview it has nothing to do this functionalities.

**Comment by darshankawar** [comment]
@MohammadAsefPoya 
Are you using STB remote control device to navigate on the Flutter app that is running in STB device ?

**Comment by darshankawar** [comment]
I think there is no support for platform-view and keyboard events. See this is most relevant issue for further reference: https://github.com/flutter/flutter/issues/102505

**Comment by MohammadAsefPoya** [comment]
So do you have any other solution to implement that ? 
Would you like to add this feature to your package in fluture or not ?

**Comment by darshankawar** [comment]
I think you will need to follow-up in the linked [issue](https://github.com/flutter/flutter/issues/155000#issuecomment-2348052721) for further updates. Once that is fixed, it will hopefully help to resolve your issue as well.
Closing this in favor of it.

**Comment by MohammadAsefPoya** [comment]
Okay thanks
