### ISSUE TITLE
How to know whether bottom sheet is open or not?

### ISSUE THREAD

**Issue by AliEsmaeil** [flutter/flutter#155082]
#### How to know whether `bottomSheet` of the `Scaffold` is open or not through scaffoldKey?

Here's how the sheet is open:

`scaffoldKey.currentState!.showBottomSheet(.....);`

Newer versions of flutter have no encapsulated methods within `scaffoldKey.currentState` that can be used to decide whether it's open or not.

## In Detail
```
class SignInScreen extends StatelessWidget {

  final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();

  SignInScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => SignInCubit(),
      child: BlocConsumer<SignInCubit, SignInStates>(
        listener: (context, state) {
          var cubit = SignInCubit.getCubit(context);

          if(state is SignInSuccessState){
            Navigator.of(context).pushNamed(HomeScreen.routeName);
          }

          if(state is SignInFailureState){
          .......................................................
          // Here i need to know if any bottom sheet is open or not?
          .......................................................
              showSnackBar(
                  context, color: redColor, message: state.failure.errMessage);

          }
          if(state is WannaEnterPhoneInForgottenPassword){

            scaffoldKey.currentState!.showBottomSheet(
              (context)=>ForgetPasswordBottomSheet(scaffoldKey : scaffoldKey),
              showDragHandle: true,
              backgroundColor: radialColor.withOpacity(1),
              enableDrag: true,
              sheetAnimationStyle: AnimationStyle(
                  duration: Duration(seconds: 1),
                  curve: Curves.easeOut,
                  reverseCurve: Curves.easeOut,
                  reverseDuration: const Duration(seconds: 1)),
            );
          }

        },
        builder: (context, state) {.........}
     ),
   );
 }
}
```
 
 
If you need to check the code, go to that [gist](https://gist.github.com/AliEsmaeil/a1621e6f9471168573c5347b7a0d6b7f) or go to [dart pad](https://dartpad.dev/?id=a1621e6f9471168573c5347b7a0d6b7f)

BTW, i have 3 bottom sheets that are being presented. so, it's not good choise to observe the status of each one of them through `PersistentBottomSheetController`. instead **i need to just know whether is that scaffold currently presenting a bottom sheet or not through scaffold key**. btw again: `mounted` property didn't worked! because bottom sheet is considered a part of the scaffold.

### Note
There are  workaround solutions, but i'm looking for a straightforward way using the framework itself. for example
 in earlier versions of flutter there was `isBottomSheetOpen`  but it's deprecated and removed in the current latest version.

### Proposal

You can check my [question](https://stackoverflow.com/questions/78975784/how-to-know-whether-bottom-sheet-is-open-or-not/78975937?) on SO.

for future updates, could you please think of adding such property `isBottomSheetOpen` which directly helps deciding whether the bottom sheet is open or not.

**Comment by darshankawar** [comment]
@AliEsmaeil 
I think this is similar to https://github.com/flutter/flutter/issues/27600, so please follow-up in it for further updates.
Closing this as a duplicate.

**Comment by darshankawar** [comment]
> could you please think of adding such property `isBottomSheetOpen` which directly helps deciding whether the bottom sheet is open or not.

See this similar open issue for reference: https://github.com/flutter/flutter/issues/51719
