### ISSUE TITLE
Security rules configuration in Firebase codelab does not include Cloud Firestore option

### ISSUE THREAD

**Issue by firebird0001** [flutter/flutter#15503]
## Steps to Reproduce

Follow steps from Firebase for Flutter codelab to setup security rules:
https://codelabs.developers.google.com/codelabs/flutter-firebase/#8

## Issue description

To start with a project it guides:
"In the Firebase console, select Database in the left navigation panel, then Get Started (for new Firebase projects)."

However, there is currently an option to choose between Realtime Database and Cloud Firestore.

The config provided in the codelab has the following syntax:
```
{
  "rules": {
    "messages": {
      ".read": true,
      ".write": "auth != null && auth.provider == 'google'"
    }
  }
}
```

The config for Cloud Firestore should have the following syntax:
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
```

**Comment by wmleler** [comment]
This bug is for the old Firebase codelab, which is deprecated.

**Comment by kroikie** [comment]
@firebird0001

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/890. Any further collaboration will be done there.
