### ISSUE TITLE
Remove checks for `assert` across `testing/dart` (`dart:ui` tests)

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#155054]
The tests in `engine/testing/dart` [often have conditional checks if assertions are enabled or not](https://github.com/search?q=repo%3Aflutter%2Fengine%20path%3A%2F%5Etesting%5C%2Fdart%5C%2F%2F%20assert&type=code):

```txt
test('RRect asserts when corner radii are negative', () {
--
381 | bool assertsEnabled = false;
382 | assert(() {
383 | assertsEnabled = true;
384 | return true;
385 | }());
```

However, these tests all use `flutter-tester`, so the checks don't make sense. Talking to @jason-simmons:

> AFAIK Dart assertions are enabled in all use cases of `flutter_tester`.
>
> The flutter_tester binary that we distribute to the framework is a debug build
> (https://github.com/flutter/engine/blob/main/build/archives/BUILD.gn#L87)
>
> The engine can use profile/release builds of flutter_tester to run engine unit tests that are written in Dart.
> But even in profile/release modes flutter_tester is built with the JIT Dart runtime (not the precompiled runtime).
> (https://github.com/flutter/engine/blob/main/shell/testing/BUILD.gn#L39)
>
> Use of the JIT runtime should cause the engine to enable assertions when it configures Dart flags.

**Comment by jonahwilliams** [comment]
I think some of these tests actually get run on profile/release tester variants.

**Comment by matanlurey** [comment]
Where? :P

**Comment by jonahwilliams** [comment]
Hidden in the profile/release host builder shards, see

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2681060/overview

you'll see invocations like:

Command run successfully in 0.23 seconds: /b/s/w/ir/cache/builder/src/out/ci/host_release/exe.unstripped/flutter_tester --force-multithreading --disable-observatory --no-enable-impeller --use-test-fonts --icu-data-file-path=/b/s/w/ir/cache/builder/src/out/ci/host_release/icudtl.dat --flutter-assets-dir=/b/s/w/ir/cache/builder/src/out/ci/host_release/gen/flutter/lib/ui/assets --disable-asset-fonts /b/s/w/ir/cache/builder/src/out/ci/host_release/gen/lerp_test.dart.dill (in /b/s/w/ir/cache/builder/src)


Which are release variants.

**Comment by jason-simmons** [comment]
The profile and release builds of `flutter_tester` use the JIT runtime and run with Dart assertions enabled.

The engine test runner script will run Dart-based engine unit tests in debug, profile, and release modes.  In release mode it will skip some tests that rely on the Dart observatory.
(https://github.com/flutter/engine/blob/main/testing/run_tests.py#L849)
