### ISSUE TITLE
I am able to render a 3D car gltf/obj file but the colour of the car is not rendering properly with any of the package of flutter!!!

### ISSUE THREAD

**Issue by SarathChandra0025** [flutter/flutter#155037]
### Steps to reproduce

I’ve encountered an issue while working with 3D model cars in Flutter on Linux. Specifically, the rendering of 3D models seems to be malfunctioning or not displaying as expected.....I tried to render a 3D car gltf/obj it is not displaying as i expected instead it is displaying a white car with no finishing and colour. " Surprisingly the colour is working for other gltf/obj/glb files but not for a car "

Issue details:
-Platform : Linux 20.04
-Flutter Version : 3.22.3
-Dart Version : 3.4.4

I have used multiple number of widgets of Flutter that supports Linux but none gave me desired output. If there any solution for this problem please let me know ASAP!!!

### Expected results

Need to run a gltf/obj car 3D with as much clarity as it is.

### Actual results

Car got run but the textures and colour are not rendered....This is only happening while i'm using a car gltf/obj but everything is perfect while i'm running other 3D files.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_cube/flutter_cube.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '3D Car Model Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late Cube _cube;

  @override
  void initState() {
    super.initState();
    _cube = Cube(
      onSceneCreated: (Scene scene) {
        scene.world.add(Object(
          fileName: 'assets/models/car.obj',
        ));
        scene.camera.position.z = 5;
        scene.camera.position.y = 1;
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('3D Car Model'),
      ),
      body: Center(
        child: _cube,
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.2, on Ubuntu 20.04.6 LTS 5.15.0-119-generic, locale
    en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.92.1)
[✓] Connected device (2 available)
[!] Network resources
    ✗ A network error occurred while checking "https://pub.dev/": Connection reset by peer
    ✗ A network error occurred while checking "https://cocoapods.org/": Connection reset by
      peer

! Doctor found issues in 3 categories.

```

</details>

**Comment by NobodyForNothing** [comment]
I noticed you are using the 3rd party flutter_cube package. Did you try raising the issue in [their repository](https://pub.dev/packages/flutter_cube)?

Although from your description here this sounds more like a problem in the car 3d model.

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the developers of those packages. Closing as this is not within the control of the Flutter team.
