### ISSUE TITLE
250% regression in `combineSemanticsInfoSyncStar_iteration`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#155105]
## dashboard
https://flutter-flutter-perf.skia.org/e/?begin=1726007560&end=1726073550&keys=X9157b8d013054366e4b85cc49843e3b4&selected=commit%3D42526%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dmokey%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253DcombineSemanticsInfoSyncStar_iteration%252Ctest%253Dmicrobenchmarks%252C&xbaroffset=42527

## introduction pr
https://github.com/flutter/engine/pull/55097

One of those dart changes likely caused it.

**Comment by jtmcdole** [comment]
I'll look into this; I believe this is probably related to day shuffle (of which we've not found some bugs in older microbenchmarks).

**Comment by a-siva** [comment]
I looked at the changes that went into that roll of Dart and found only 2 VM changes

072945e Version 3.6.0-238.0.dev by Dart CI · 13 days ago 3.6.0-238.0.dev
11aa023 [vm] Give a better error message on pthread_join failure. by Ryan Macnak · 13 days ago
2719e10 [vm, timeline] Include thread names when using the file recorder. by Ryan Macnak · 13 days ago

None of those changes look like potential candidates to cause that regression.

**Comment by jonahwilliams** [comment]
The numbers went back down after this point, and then up again. I suspect at some point time, they will go down, or up. I can't say for sure. Closing as we don't need to track this further.
