### ISSUE TITLE
when i run flutter build apk --release i got this error

### ISSUE THREAD

**Issue by ankitunada** [flutter/flutter#155150]
### Steps to reproduce

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                 │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update the  │
│ version number of the plugin with id "org.jetbrains.kotlin.android" in the plugins block of            │
│ /Users/apple/Documents/GitHub/gruham/android/settings.gradle.                                          │
│                                                                                                        │
│ Alternatively (if your project was created before Flutter 3.19), update                                │
│ /Users/apple/Documents/GitHub/gruham/android/build.gradle                                              │
│ ext.kotlin_version = '<latest-version>' 

### Expected results

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                 │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update the  │
│ version number of the plugin with id "org.jetbrains.kotlin.android" in the plugins block of            │
│ /Users/apple/Documents/GitHub/gruham/android/settings.gradle.                                          │
│                                                                                                        │
│ Alternatively (if your project was created before Flutter 3.19), update                                │
│ /Users/apple/Documents/GitHub/gruham/android/build.gradle                                              │
│ ext.kotlin_version = '<latest-version>' 

### Actual results

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                 │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update the  │
│ version number of the plugin with id "org.jetbrains.kotlin.android" in the plugins block of            │
│ /Users/apple/Documents/GitHub/gruham/android/settings.gradle.                                          │
│                                                                                                        │
│ Alternatively (if your project was created before Flutter 3.19), update                                │
│ /Users/apple/Documents/GitHub/gruham/android/build.gradle                                              │
│ ext.kotlin_version = '<latest-version>' 

### Code sample

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                 │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update the  │
│ version number of the plugin with id "org.jetbrains.kotlin.android" in the plugins block of            │
│ /Users/apple/Documents/GitHub/gruham/android/settings.gradle.                                          │
│                                                                                                        │
│ Alternatively (if your project was created before Flutter 3.19), update                                │
│ /Users/apple/Documents/GitHub/gruham/android/build.gradle                                              │
│ ext.kotlin_version = '<latest-version>' 

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
@ankitunada You are duplicating information on all fields. Please try to provide all information indicated in the template so that we can address the issue properly.

What is your current Flutter version? (please provide `flutter doctor -v` output)

Let's check [this](https://github.com/flutter/flutter/issues/137886#issuecomment-1793852741) to see if setting those versions (Kotlin, AGP, Gradle) can make this work. If it doesn't work, please share these file contents:

- /android/settings.gradle
- /android/gradle/wrapper/gradle-wrapper.properties

**Comment by gopelkujo** [comment]
Like the error said your project requires newer version of kotlin.

So to upgrade your kotlin version:
 1. find `android/settings.gradle` file in your project
 2. Then go to `plugins` section
 3. Change the `org.jetbrains.kotlin.android` version to the latest.
example:
```
id "org.jetbrains.kotlin.android" version "1.9.20" apply false
```

To check the kotlin, gradle, and java compability visit this [Compability Matrix](https://docs.gradle.org/current/userguide/compatibility.html)

**Comment by ankitunada** [comment]
> @ankitunada You are duplicating information on all fields. Please try to provide all information indicated in the template so that we can address the issue properly.
> 
> What is your current Flutter version? (please provide `flutter doctor -v` output)
> 
> Let's check [this](https://github.com/flutter/flutter/issues/137886#issuecomment-1793852741) to see if setting those versions (Kotlin, AGP, Gradle) can make this work. If it doesn't work, please share these file contents:
> 



> * /android/settings.gradle
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version '7.4.2' apply false
    // START: FlutterFire Configuration
    id "com.google.gms.google-services" version "4.3.15" apply false
    id "com.google.firebase.crashlytics" version "2.8.1" apply false
    // END: FlutterFire Configuration
    id "org.jetbrains.kotlin.android" version "1.9.10" apply false
}

include ":app"
//include ':app', ':flutter_unity_widget', ':unityLibrary'
//project(':unityLibrary').projectDir = new File(rootProject.projectDir, '../unityLibrary')
//
include ':unityLibrary'
project(':unityLibrary').projectDir = new File(settingsDir, '../unityLibrary')

//
include ":unityLibrary"
project(":unityLibrary").projectDir = file("./unityLibrary")




> * /android/gradle/wrapper/gradle-wrapper.properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip

**Comment by huycozy** [comment]
@ankitunada Can you try setting versions like this?

- /android/settings.gradle
```
plugins {
    ....
    id "com.android.application" version "8.1.1" apply false
}
```

- /android/gradle/wrapper/gradle-wrapper.properties

```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-all.zip
```

If the issue persists, please provide the entire output of flutter build command with verbose (-v): `flutter build apk --release -v` (_The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it_)

**Comment by ankitunada** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 3.24.2, on macOS 13.7 22H123 darwin-x64, locale en-GB)
    • Flutter version 3.24.2 on channel stable at /Users/apple/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (5 weeks ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • SM E346B (mobile) • 192.168.29.2:5555 • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos             • darwin-x64     • macOS 13.7 22H123 darwin-x64
    • Chrome (web)      • chrome            • web-javascript • Google Chrome 129.0.6668.90
    ! Error: Browsing on the local area network for Apple’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Virendra’s Iphone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
