### ISSUE TITLE
the movie automatically start when loading

### ISSUE THREAD

**Issue by YasuakiHaraP** [flutter/flutter#155135]
### Steps to reproduce

I want to stop playback when I load an HLS (MPEG-TS) Playlist with better_player.
1. set BetterPlayerConfigration : autoPlay=false
2. set BetterPlayerDataSource : HLS (MPEG-TS) playlist via network
3. _betterPlayerController.setupDataSource(betterPlayerDataSource) 

### Expected results

Player display the frame of Duration.zero.
Player is PAUSE state.

### Actual results

If the video is less than one minute long, the player will stop playback after running setupDataSource.
However, if the video is long, the player will automatically start playing after running setupDataSource.

Similarly, long videos will automatically start playing when seeking.
This phenomenon only occurs on iOS, not Android.

How can I prevent a long video from automatically playing when seeking when loading it on iOS?

### Code sample

<details open><summary>Code sample</summary>

```dart
    // プレイリストのURLをデータソースとしてセットする.
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
          BetterPlayerDataSourceType.network,
          videoFormat: BetterPlayerVideoFormat.hls, // Android で再生するためには必要.
          playlistUrl,
          headers: {
            'Authorization': 'Bearer xxxxxx',
            'content-type': 'application/json',
            'Accept': '*/*',
          },
        );

    _betterPlayerController = BetterPlayerController(
        const BetterPlayerConfiguration(
          autoPlay: false,
          looping: false,
        ));

    _betterPlayerController.setupDataSource(betterPlayerDataSource)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.6.1 23G93 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (5 available)            
[✓] Network resources

• No issues found!
```

</details>

**Comment by aidarbye** [comment]
It is not the framework problem, fill the issue in better_player

**Comment by YasuakiHaraP** [comment]
sorry...
