### ISSUE TITLE
How to Build Flutter Engine with Software Graphics Backend

### ISSUE THREAD

**Issue by Thiru-01** [flutter/flutter#155116]
I would like to build the Flutter engine with software graphics as the backend instead of using GPU-accelerated rendering (e.g., Skia with Vulkan/Metal/GL). Currently, most of the available guides focus on building the engine with hardware-accelerated graphics, but I am interested in a purely software-based renderer.

In the Flutter documentation, it is mentioned that several platforms support alternative graphics backends, including a software rendering mode. For example:

1. iOS can choose between: OpenGL, software
2. Android can choose between: Vulkan, OpenGL, software
3. macOS can choose between: OpenGL, software, headless (debug only)
4. Linux can choose between: OpenGL, software, headless (debug only)
5. Windows can choose between: OpenGL, software, headless (debug only)

However, the documentation does not provide specific instructions on how to select and build the Flutter engine with the software backend on these platforms.

### Actual results

It's unclear how to switch to the software rendering backend, and the documentation does not provide steps or flags for this configuration.

### Flutter Doctor output

Environment:

OS: Windows
Device: Desktop

**Comment by jonahwilliams** [comment]
The embedders themselves are responsible for rendering backend selection. So for example, the iOS embedder is metal only at this point. The embedder does not expose a rendering selection option - and for the embedders maintained by the Flutter team we do not plan to expose this configuration.

You'd need to build your own embedder or choose a 3rd party embedder that supports this configuration.
