### ISSUE TITLE
[webview_flutter] displays only the webview background and no content on Android

### ISSUE THREAD

**Issue by ianiscardona** [flutter/flutter#155137]
### Steps to reproduce

This code was perfectly working on android days ago, now it displays only the webview background and no content (empty space). Still perfectly works on iOS.

The file path used is from path provider getTemporaryDirectory() and/or getApplicationCacheDirectory().

Hope you can help. Thanks!

### Code sample

<details open><summary>Code sample</summary>

```dart
class FileAttchDispView extends StatefulWidget {
  final String? path;
  const FileAttchDispView({super.key, required this.path});

  @override
  State<FileAttchDispView> createState() => _FileAttchDispViewState();
}

class _FileAttchDispViewState extends State<FileAttchDispView> {
  late String _fileCat;
  late String _fileExt;
  File? _file;
  WebViewController? _wvCtrlr;

  @override
  void initState() {
    _fileExt =
        widget.path!.substring(widget.path!.lastIndexOf('.') + 1).toLowerCase();
    switch (_fileExt) {
      case "pdf" ||
            "docx" ||
            "doc" ||
            "xlsx" ||
            "xls" ||
            "csv" ||
            "xlt" ||
            "dot" ||
            "dotx":
        _file = File(widget.path!);
        _wvCtrlr = WebViewController()
          ..setJavaScriptMode(JavaScriptMode.unrestricted)
          ..loadFile(_file!.path)
          ..clearLocalStorage()
          ..clearCache();
        _fileCat = "document";
      default:
        _fileCat = "invalid";
    }
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        surfaceTintColor: Theme.of(context).colorScheme.secondary,
      ),
      body: StatefulBuilder(
        builder: (context, snapshot) {
          switch (_fileCat) {
            case "document":
              return WebViewWidget(
                controller: _wvCtrlr!,
              );
            default:
              return Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(
                      Icons.system_security_update_warning_rounded,
                      size: 36,
                      color: Color.fromARGB(255, 17, 10, 10),
                    ),
                    Text(
                      "Unable to read file.",
                      style:
                          Theme.of(context).textTheme.headlineMedium?.copyWith(
                                color: const Color(0xFF6B6B6B),
                              ),
                    ),
                  ],
                ),
              );
          }
        },
      ),
    );
  }
}

```

</details>

### Performance profiling on master channel

- [X] The issue still persists on the master channel

### Timeline Traces

<details open><summary>Timeline Traces JSON</summary>

```json
I/PlatformViewsController( 9393): Hosting view in view hierarchy for platform view: 1
I/PlatformViewsController( 9393): PlatformView is using SurfaceTexture backend
D/EGL_emulation( 9393): eglCreateContext: 0x70c85251e210: maj 3 min 0 rcv 3
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9393): app_time_stats: avg=135.44ms min=2.85ms max=3953.11ms count=32
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9393): app_time_stats: avg=7007.08ms min=7007.08ms max=7007.08ms count=1
2
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9393): app_time_stats: avg=386.47ms min=24.49ms max=1105.85ms count=3
D/EGL_emulation( 9393): app_time_stats: avg=599.92ms min=35.05ms max=1164.79ms count=2
2
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9393): app_time_stats: avg=226.89ms min=10.57ms max=985.99ms count=6
6
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
```

</details>

### Video demonstration

<details open>
<summary>Video demonstration</summary>

[Upload media here]

</details>

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

Android emulators and physical devices.

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Is the problem only reproducible with Impeller?

N/A

### Logs

<details open><summary>Logs</summary>

```console
I/PlatformViewsController( 9393): Hosting view in view hierarchy for platform view: 1
I/PlatformViewsController( 9393): PlatformView is using SurfaceTexture backend
D/EGL_emulation( 9393): eglCreateContext: 0x70c85251e210: maj 3 min 0 rcv 3
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9393): app_time_stats: avg=135.44ms min=2.85ms max=3953.11ms count=32
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9393): app_time_stats: avg=7007.08ms min=7007.08ms max=7007.08ms count=1
2
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9393): app_time_stats: avg=386.47ms min=24.49ms max=1105.85ms count=3
D/EGL_emulation( 9393): app_time_stats: avg=599.92ms min=35.05ms max=1164.79ms count=2
2
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
D/EGL_emulation( 9393): app_time_stats: avg=226.89ms min=10.57ms max=985.99ms count=6
6
E/FrameEvents( 9393): updateAcquireFence: Did not find frame.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.19045.4651], locale en-PH)
    • Flutter version 3.19.3 on channel stable at C:\`Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 months ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at D:\Users\ancardona\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35027.167
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.93.0)
    • VS Code at D:\Users\ancardona\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] VS Code, 64-bit edition (version unknown)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.96.0
    X Unable to determine VS Code version.

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.122
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 128.0.2739.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
> now it displays only the webview background and no content (empty space). Still perfectly works on iOS.

@ianiscardona Can you provide a short video of this behavior ?
Also, can you upgrade to latest stable (3.24.3) and re-run your scenario to check if the behavior still persist or not ? If so, can you provide an example of the `path` to provide ?

Regarding `did not find frame`, please read [this](https://github.com/flutter/flutter/issues/104268#issuecomment-1134964433) for your reference

**Comment by ianiscardona** [comment]
> > now it displays only the webview background and no content (empty space). Still perfectly works on iOS.
> 
> @ianiscardona Can you provide a short video of this behavior ? Also, can you upgrade to latest stable (3.24.3) and re-run your scenario to check if the behavior still persist or not ? If so, can you provide an example of the `path` to provide ?
> 
> Regarding `did not find frame`, please read [this](https://github.com/flutter/flutter/issues/104268#issuecomment-1134964433) for your reference

Did tried upgrading to 3.24.3, it still persist. After context.push to this page, it does this and only displays the setBackgroundColor() of the webview. Sample of path goes like this "/data/user/0/com.example.app.dev/cache/default.docx"

https://github.com/user-attachments/assets/4a9c7077-37a2-4de3-8925-debb88a8ba47

**Comment by darshankawar** [comment]
I tried the same using sample path as below, for which it gave me access_denied error that I will check as why is it so:

<img width="217" alt="Screenshot 2024-09-16 at 11 00 04 AM" src="https://github.com/user-attachments/assets/dfc3226f-1c70-4ba4-b719-c3c60a6773c6">



> This code was perfectly working on android days ago, now it displays only the webview background and no content (empty space)

Do you have more details about it ? like did you upgrade Android version or SdK version ? In which version it was working ?

**Comment by ianiscardona** [comment]
> I tried the same using sample path as below, for which it gave me access_denied error that I will check as why is it so:
> 
> 
> 
> <img width="217" alt="Screenshot 2024-09-16 at 11 00 04 AM" src="https://github.com/user-attachments/assets/dfc3226f-1c70-4ba4-b719-c3c60a6773c6">
> 
> 
> 
> 
> 
> 
> 
> > This code was perfectly working on android days ago, now it displays only the webview background and no content (empty space)
> 
> 
> 
> Do you have more details about it ? like did you upgrade Android version or SdK version ? In which version it was working ?

I was working with minsdkversion 24 and targetsdkversion 34. I tried this on flutter 3.19 then tried it on 3.25. Regarding the path from pathprovider, it is indeed working on another package, pdfx.

**Comment by darshankawar** [comment]
I am unable to replicate the reported error with latest stable version. 
@ianiscardona Can you create a new Flutter app and use the code sample provided to check if you still get same behavior or not ?

**Comment by ianiscardona** [comment]
Tried this with:

```
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (6 days ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
```

I get the same error you showed.
![image](https://github.com/user-attachments/assets/d0812dec-0ad8-4327-9954-3e6ea579d6e6)

android/app/build.gradle settings
  ```
compileSdk = flutter.compileSdkVersion
minSdk = flutter.minSdkVersion
targetSdk = flutter.targetSdkVersion
```

Unfortunately, error still persist.

**Comment by ianiscardona** [comment]
Sure, But I'm really just wondering if I can really display document file types in android webview since it can be done in IOS? Is it really possible?

**Comment by aswathyMVP** [comment]
Same issue is happening after updating the package, and flutter version to the latest.

**Comment by MrLiuYunPing** [comment]
Same issue.

**Comment by MrLiuYunPing** [comment]
Same issue, I only display a privacy policy web page. Sometimes the webview only displays the webview's background, sometimes it performs success.

**Comment by yaakovschectman** [comment]
@bparrishMines From triage: Have you been working on webview for Android recently, or know anything about this possible regression?

**Comment by MrLiuYunPing** [comment]
only tap the background can show the content

**Comment by bparrishMines** [comment]
@yaakovschectman I haven't made any major changes to WebView on Android for at least of few months while I've been working on improving the code generation.

**Comment by bparrishMines** [comment]
This looks like it could potentially be a permissions issue. We call `WebSettings.setAllowFileAccess` in [AndroidWebVIewController.loadFile](https://github.com/flutter/packages/blob/main/packages/webview_flutter/webview_flutter_android/lib/src/android_webview_controller.dart#L376). 

Potentially [setAllowContentAccess](https://developer.android.com/reference/android/webkit/WebSettings#setAllowContentAccess(boolean)) needs to be callled.

However, I'm not sure why it would stop working now.

This could be related: https://stackoverflow.com/questions/57131662/err-access-denied-in-webview-in-android

**Comment by gmackall** [comment]
From android triage: to be clear, did this change happen after updating either `flutter` or `webview_flutter`, or were the versions constant?

**Comment by ron-diesel** [comment]
I have the same problem.
I see that the problem appears in release mode and with URLs that contain simple lightweight HTML.
Flutter 3.24.1
webview_flutter: ^4.9.0
HTML
`<html lang="ru"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Пользовательское соглашение</title>
    <style>
        body {
            background-color: black;
            color: white;
            font-family: Arial, sans-serif;
            font-size: 16px;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .title {
            font-weight: bold;
            margin-top: 20px;
        }
        p {
            margin-bottom: 15px;
        }
    </style>
</head>
<body>

<p class="title">1. Общие положения</p>
<p>Настоящее Пользовательское соглашение (далее – Соглашение) регулирует отношения между владельцем сайта и пользователями. Используя сайт, вы соглашаетесь с условиями данного Соглашения.</p>

<p class="title">2. Права и обязанности пользователей</p>
<p>Пользователь обязуется не совершать действий, которые могут нарушить работу сайта, не нарушать законодательство РФ, а также соблюдать правила, установленные на сайте.</p>

<p class="title">3. Права и обязанности администрации</p>
<p>Администрация сайта вправе изменять, дополнять или удалять пункты настоящего Соглашения в любое время без уведомления пользователей. Администрация не несет ответственности за убытки, которые может понести пользователь в результате использования сайта.</p>

<p class="title">4. Конфиденциальность и защита персональных данных</p>
<p>Все персональные данные, которые пользователь передает через сайт, обрабатываются в соответствии с Политикой конфиденциальности.</p>

<p class="title">5. Заключительные положения</p>
<p>Настоящее Соглашение вступает в силу с момента использования сайта. В случае несогласия с условиями Соглашения, пользователь обязан прекратить использование сайта.</p>


</body></html>`

**Comment by reidbaker** [comment]
@ron-diesel can you share the versions of flutter this worked on as well so we can bisect the history? Our current theory is this might be an android change related to local file rendering.

**Comment by Swepilot** [comment]
I am facing this as well in my project. When loading html from string the webview only shows the background, until the screen is tapped, then the html text is displayed. Sometimes it loads immediately, some times not. This is demonstrated in the video below.

 A small demo project where the issue can be replicated is available here:  [https://github.com/Swepilot/webview_debug](url)

https://github.com/user-attachments/assets/92bda524-3dff-4bd4-913e-e21a48822b98

Using Flutter 3.24.3 from Stable with latest webview_flutter package

webview_flutter 4.10.0
    ├── webview_flutter_android 4.0.0
    │   ├── flutter...
    │   └── webview_flutter_platform_interface...
    ├── webview_flutter_platform_interface 2.10.0
    │   ├── plugin_platform_interface 2.1.8
    │   │   └── meta...
    │   ├── flutter...
    │   └── meta...
    ├── webview_flutter_wkwebview 3.16.0
    │   ├── flutter...
    │   ├── path...
    │   └── webview_flutter_platform_interface...
    └── flutter...

**Comment by PrabhatPatel003** [comment]
I have been facing a similar issue on android
the webview won't load the webpage when i run the app from android studio, but after i restart my phone it starts working in the same build.

Flutter 3.24.3 Dart 3.5.3
Android - 14

Here are my logs:-
``` 
W/ziparchive( 8487): Unable to open '/data/app/~~LDQU0qiqWtdq5emnymqqpQ==/com.google.android.trichromelibrary_666810233-NPAhgZAJDHUSxUW7gj_s-Q==/base.dm': No such file or directory
W/ziparchive( 8487): Unable to open '/data/app/~~LDQU0qiqWtdq5emnymqqpQ==/com.google.android.trichromelibrary_666810233-NPAhgZAJDHUSxUW7gj_s-Q==/base.dm': No such file or directory
W/a.android.stage( 8487): Entry not found
D/nativeloader( 8487): Configuring clns-7 for other apk /data/app/~~LDQU0qiqWtdq5emnymqqpQ==/com.google.android.trichromelibrary_666810233-NPAhgZAJDHUSxUW7gj_s-Q==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/lib/arm64:/data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/base.apk!/lib/arm64-v8a:/data/app/~~LDQU0qiqWtdq5emnymqqpQ==/com.google.android.trichromelibrary_666810233-NPAhgZAJDHUSxUW7gj_s-Q==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
D/nativeloader( 8487): Extending system_exposed_libraries: libapuwareapusys.mtk.so:libapuwareapusys_v2.mtk.so:libapuwarexrp.mtk.so:libapuwarexrp_v2.mtk.so:libapuwareutils.mtk.so:libapuwareutils_v2.mtk.so:libapuwarehmp.mtk.so:libmcv_runtime_usdk.mtk.so:libneuron_graph_delegate.mtk.so:libneuronusdk_adapter.mtk.so:libtflite_mtk.mtk.so:libarmnn_ndk.mtk.so:libcmdl_ndk.mtk.so:libnir_neon_driver_ndk.mtk.so:libmvpu_runtime.mtk.so:libmvpu_runtime_pub.mtk.so:libmvpu_engine_pub.mtk.so:libmvpu_pattern_pub.mtk.so:libmvpuop_mtk_cv.mtk.so:libmvpuop_mtk_nn.mtk.so:libmvpu_runtime_25.mtk.so:libmvpu_runtime_25_pub.mtk.so:libmvpu_engine_25_pub.mtk.so:libmvpu_pattern_25_pub.mtk.so:libmvpuop25_mtk_cv.mtk.so:libmvpuop25_mtk_nn.mtk.so:libmvpu_config.mtk.so:libteeservice_client.trustonic.so
W/a.android.stage( 8487): Loading /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/oat/arm64/base.odex non-executable as it requires an image which we failed to load
D/nativeloader( 8487): Configuring clns-8 for other apk /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/lib/arm64:/data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/base.apk!/lib/arm64-v8a:/data/app/~~LDQU0qiqWtdq5emnymqqpQ==/com.google.android.trichromelibrary_666810233-NPAhgZAJDHUSxUW7gj_s-Q==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
I/WebViewFactory( 8487): Loading com.google.android.webview version 129.0.6668.102 (code 666810233)
I/cr_WVCFactoryProvider( 8487): version=129.0.6668.102 (666810233) minSdkVersion=29 isBundle=true multiprocess=true packageId=2
D/nativeloader( 8487): Load /data/app/~~LDQU0qiqWtdq5emnymqqpQ==/com.google.android.trichromelibrary_666810233-NPAhgZAJDHUSxUW7gj_s-Q==/base.apk!/lib/arm64-v8a/libmonochrome_64.so using ns clns-8 from class loader (caller=/data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/base.apk): ok
D/nativeloader( 8487): Load /system/lib64/libwebviewchromium_plat_support.so using ns clns-8 from class loader (caller=/data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/base.apk): ok
E/chromium( 8487): [1029/095101.416971:ERROR:variations_seed_loader.cc(39)] Seed missing signature.
I/cr_LibraryLoader( 8487): Successfully loaded native library
I/cr_CachingUmaRecorder( 8487): Flushed 6 samples from 6 histograms, 0 samples were dropped.
I/cr_CombinedPProvider( 8487): #registerProvider() provider:WV.r8@cbedaa5 isPolicyCacheEnabled:false policyProvidersSize:0
I/cr_PolicyProvider( 8487): #setManagerAndSource() 0
W/cr_ChildProcessConn( 8487): Fallback to ComponentInfo{com.google.android.webview/org.chromium.content.app.SandboxedProcessService1}
E/cr_ChildProcessConn( 8487): Failed to establish the service connection.
I/cr_CombinedPProvider( 8487): #linkNativeInternal() 1
I/cr_AppResProvider( 8487): #getApplicationRestrictionsFromUserManager() Bundle[EMPTY_PARCEL]
I/cr_PolicyProvider( 8487): #notifySettingsAvailable() 0
I/cr_CombinedPProvider( 8487): #onSettingsAvailable() 0
I/cr_CombinedPProvider( 8487): #flushPolicies()
D/CompatibilityChangeReporter( 8487): Compat change id reported: 214741472; UID 10297; state: ENABLED
D/CompatibilityChangeReporter( 8487): Compat change id reported: 171228096; UID 10297; state: ENABLED
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/base.apk' with 1 weak references
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/split_config.bn.apk' with 1 weak references
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/split_config.en.apk' with 1 weak references
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/split_config.gu.apk' with 1 weak references
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/split_config.hi.apk' with 1 weak references
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/split_config.kn.apk' with 1 weak references
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/split_config.mr.apk' with 1 weak references
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/split_config.ta.apk' with 1 weak references
W/a.android.stage( 8487): ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~dOFbc_rqac6Ff3zvkEC1-A==/com.google.android.webview-zpaPUc6KI_RJlNPHy3Z21w==/split_config.te.apk' with 1 weak references
D/libMEOW ( 8487): meow new tls: 0xb400007b69163dd0
D/libMEOW ( 8487): applied 0 plugin for [my-web-link].
W/cr_media( 8487): BLUETOOTH_CONNECT permission is missing.
W/cr_media( 8487): getBluetoothAdapter() requires BLUETOOTH permission
W/cr_media( 8487): registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
W/cr_ChildProcessConn( 8487): Fallback to ComponentInfo{com.google.android.webview/org.chromium.content.app.SandboxedProcessService1}
I/PlatformViewsController( 8487): Hosting view in view hierarchy for platform view: 0
I/PlatformViewsController( 8487): PlatformView is using SurfaceProducer backend
D/CompatibilityChangeReporter( 8487): Compat change id reported: 236825255; UID 10297; state: ENABLED
E/cr_ChildProcessConn( 8487): Failed to establish the service connection.
D/BufferQueueConsumer( 8487): [](id:212700000008,api:0,p:-1,c:8487) connect: controlledByApp=true
D/Surface ( 8487): lockHardwareCanvas
D/CompatibilityChangeReporter( 8487): Compat change id reported: 193247900; UID 10297; state: ENABLED
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/BufferQueueConsumer( 8487): [](id:212700000009,api:0,p:-1,c:8487) connect: controlledByApp=true
D/Surface ( 8487): lockHardwareCanvas
W/chromium( 8487): [WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/Surface ( 8487): lockHardwareCanvas
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/BufferQueueConsumer( 8487): [ImageReader-1x1f22m5-8487-0](id:212700000008,api:0,p:-1,c:8487) disconnect
D/Surface ( 8487): lockHardwareCanvas
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/Surface ( 8487): lockHardwareCanvas
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/Surface ( 8487): lockHardwareCanvas
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/Surface ( 8487): lockHardwareCanvas
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/Surface ( 8487): lockHardwareCanvas
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/Surface ( 8487): lockHardwareCanvas
E/FrameEvents( 8487): updateAcquireFence: Did not find frame.
D/Surface ( 8487): lockHardwareCanvas
```

**Comment by 743306400** [comment]
> I am facing this as well in my project. When loading html from string the webview only shows the background, until the screen is tapped, then the html text is displayed. Sometimes it loads immediately, some times not. This is demonstrated in the video below.
> 
> A small demo project where the issue can be replicated is available here: [https://github.com/Swepilot/webview_debug](url)
> 
>  Screen_Recording_20241019_075720.mp4 
> Using Flutter 3.24.3 from Stable with latest webview_flutter package
> 
> webview_flutter 4.10.0 ├── webview_flutter_android 4.0.0 │ ├── flutter... │ └── webview_flutter_platform_interface... ├── webview_flutter_platform_interface 2.10.0 │ ├── plugin_platform_interface 2.1.8 │ │ └── meta... │ ├── flutter... │ └── meta... ├── webview_flutter_wkwebview 3.16.0 │ ├── flutter... │ ├── path... │ └── webview_flutter_platform_interface... └── flutter...

Hello, have you solved this problem?

**Comment by ewgcat** [comment]
import 'package:flutter/services.dart' show rootBundle;
Future<void> loadAsset() async {
  String  content =await rootBundle.loadString('assets/teamofuser.html');
    webViewController
      ..loadHtmlString(content)
      ..enableZoom(false)
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(Colors.white)
      ..setNavigationDelegate(NavigationDelegate(
          onNavigationRequest: (request) {
            return NavigationDecision.prevent;
          },
          onPageFinished: (url) {},
          onProgress: (progress) {
          
          }));

  }

**Comment by ron-diesel** [comment]
I solved this problem by
```
 void _load() async {
    await controller.loadRequest(Uri.parse(widget.url));

   /// the hack that fixes this bug https://github.com/flutter/flutter/issues/155137
    await controller.scrollTo(0, 1);
    await controller.scrollTo(0, 0);
  }
```
