### ISSUE TITLE
Asset validation failed (90035) Invalid Signature. Code object is not signed at all.

### ISSUE THREAD

**Issue by M-Farjad** [flutter/flutter#155166]
### Steps to reproduce

1. flutter build ipa
2. I am using .env file to secure my credentials but it is saying Invalid Signature even though the .ipa is being built
3. Tranporting .ipa file to the App Store using transporter

### Expected results

App published from transporter to the App Store

### Actual results

`Asset validation failed (90035) Invalid Signature. Code object is not signed at all. The file at path “Runner.app/Frameworks/App.framework/flutter_assets/.env” is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose “Clean All” in Xcode, delete the “build” directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing. (ID: 1de09c30-c098-4e51-8107-37798404b61e)
`
### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![Screenshot 2024-09-13 at 9 22 20 PM](https://github.com/user-attachments/assets/a1299d2d-cf9e-4420-9961-1500a0c8cdb5)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
mac@iMac-de-MAC ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-x64, locale
    en-PK)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.89.0)
[✓] VS Code (version 1.89.0)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for Saad’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by darshankawar** [comment]
> The file at path “Runner.app/Frameworks/App.framework/flutter_assets/.env” is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose “Clean All” in Xcode, delete the “build” directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing

@M-Farjad 
The error gives you the reason why you are getting the error and what you should do to resolve it. Please follow the same and check if it helps to resolve the issue or not.
