### ISSUE TITLE
How to debug Flutter App with Charles ?

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15510]
I tried to use Charles to check the request ,but nothing is shown , any ideas?

**Comment by zoechi** [comment]
Sounds like a similar question as https://stackoverflow.com/questions/49067382/flutter-app-not-using-fiddler-proxy
This kind of question are better asked on SO anyway.

**Comment by xster** [comment]
Flutter uses the system networking stack. Setting proxies in the Android/iOS system wifi preferences should work.

**Comment by realcarlos** [comment]
@zoechi @xster  The problem is that flutter doesn't seem to use the proxy (Most other apps do), so I could not use the Charles to debug ,and the security check guy said I block him , is there a way or a tool to monitor the netwoking request for flutter app?

**Comment by johnwongapi** [comment]
Hi @realcarlos, I am facing the same situation. do u solve it?

**Comment by huuang** [comment]
I have the same problem, any suggestions will be appreciated.

**Comment by ErikDohmen** [comment]
Any progress on this one?

**Comment by zoechi** [comment]
@ErikDohmen The issue is closed, so I wouldn't expect any progress.
Have you tried to ask on StackOverflow?

**Comment by ErikDohmen** [comment]
Well, not yet, but found a solution through the use of dio, so fixed it after all through a temp solution, as I won't be able to do that from within the distribution app.

**Comment by dazza5000** [comment]
Did anyone find a solution to this?

**Comment by KingWu** [comment]
facing the same issue

**Comment by zoechi** [comment]
Duplicate of #20376

**Comment by cesar3030** [comment]
Same issue here! Really frustrating...
