### ISSUE TITLE
[TextField] Incorrect Word Selection and Cursor Behavior in RTL TextField with Special Characters

### ISSUE THREAD

**Issue by oleks-nerd** [flutter/flutter#155153]
### Steps to Reproduce:

1. Open [Flutter's documentation on handling changes to a text field](https://docs.flutter.dev/cookbook/forms/text-field-changes).
2. Paste the code from my code sample into the page.
3. Enter the following text into the TextField: `שלום לכולם, בדיקה ניסיון`.
4. Press Enter and paste the same text again on the next line.
5. Select any word from the first line by double-clicking it and check the cursor position while navigating with the left and right arrow keys.
6. Go to the end of the first line and add a special character, such as `,`.
7. Attempt to select any word by double-clicking and observe the cursor position.

### Additional Notes:

- The problem occurs not only with a comma but with any special character at the end of the line (e.g., `.`, `\`, `/`, `?`, `!`, etc.).
- The issue seems to affect all lines except the last line. For example, if you create 5 lines with the text `שלום לכולם, בדיקה ניסיון,`, the selection on the last line will be correct, but the 4 preceding lines will have incorrect behavior.

### Expected results

- Words should be selected from start to end without any issues when double-clicking.
- The cursor should move between letters without any problems.
- When pressing the delete or backspace key, the correct letter should be removed.

### Actual results

- After step 7, word selection is broken when double-clicking.
- The cursor does not accurately move between letters.
- Deleting or backspacing does not remove the correct letter.
- Special characters at the end of a line cause incorrect selection and cursor behavior on all lines except the last one.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Retrieve Text Input',
      home: MyCustomForm(),
    );
  }
}

// Define a custom Form widget.
class MyCustomForm extends StatefulWidget {
  const MyCustomForm({super.key});

  @override
  State<MyCustomForm> createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds data related to the Form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller and use it to retrieve the current value
  // of the TextField.
  final myController = TextEditingController();

  @override
  void initState() {
    super.initState();

    // Start listening to changes.
    // myController.addListener(_printLatestValue);
    myController.addListener(() {
      if (myController != null) {
        if (myController.selection ==
            TextSelection.fromPosition(
                TextPosition(offset: myController.text.length - 1))) {
          myController.selection = TextSelection.fromPosition(
            TextPosition(
              offset: myController.text.length,
            ),
          );
        }
      }
    });
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is removed from the widget tree.
    // This also removes the _printLatestValue listener.
    myController.dispose();
    super.dispose();
  }

  void _printLatestValue() {
    final text = myController.text;
    print('Second text field: $text (${text.characters.length})');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Retrieve Text Input'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            TextField(
              minLines: 1,
              controller: myController,
              textDirection: TextDirection.rtl,
              maxLines: 2,
              onChanged: (text) {
                print('First text field: $text (${text.characters.length})');
              },
            ),
            TextField(
              minLines: 1,
              maxLines: 2,
              controller: myController,
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/0dfc8c17-609d-41a4-a7bb-2cda970f40e2)

https://github.com/user-attachments/assets/c498e553-e9fb-4a36-88b0-004861bdd516

</details>

### Logs

<details open><summary>Logs</summary>

```console
The issue is reproducible in [Flutter's documentation on handling changes to a text field](https://docs.flutter.dev/cookbook/forms/text-field-changes).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
The issue is reproducible in [Flutter's documentation on handling changes to a text field](https://docs.flutter.dev/cookbook/forms/text-field-changes).
```

</details>

**Comment by huycozy** [comment]
Thanks for the report! 

This is a known issue being tracked at https://github.com/flutter/flutter/issues/117139. Closing this issue as a duplicate, so please follow up on it for further updates.
