### ISSUE TITLE
Unable to find bundled Java version

### ISSUE THREAD

**Issue by JesseBlake** [flutter/flutter#15514]
## Unable to find bundled Java version.

![fluteer](https://user-images.githubusercontent.com/15786782/37391509-72a6bd6e-277c-11e8-9172-032816f6fa37.png)

**Comment by mit-mit** [comment]
cc @jcollins-g I think those can be ignored? Actually, should we filter away older versions of A.S.; I don't think we support those anyway?

**Comment by JesseBlake** [comment]
problem solved bye deleting older version of android studio folder and install a new one

**Comment by jcollins-g** [comment]
@mit-mit It's been mentioned a couple times that we should filter out android studio versions we don't support somehow but I can't find an issue for that.  If this is coming up a lot we should file one?
