### ISSUE TITLE
Gallery App has Cards

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1551]
From https://www.google.com/design/spec/components/cards.html

- [x] Supplemental actions
- [x] Content blocks
- [x] Avatar, title, subtitle

Behaviors: 

* Swipe gesture support (https://github.com/flutter/flutter/issues/3979)
* Pick up and move gesture support (https://github.com/flutter/flutter/issues/3978)

**Comment by eseidelGoogle** [comment]
I suspect most of these exist. @HansMuller

**Comment by HansMuller** [comment]
I've checked the card features that we're currently covering in the gallery.  There's definitely more to do.

**Comment by sethladd** [comment]
Moved the behavior-related features to individual issues. The gallery app now has a cards demos (called Travel stream).
