### ISSUE TITLE
The prefix icon in text fields should line up just below the label text, rather than to the left of it.

### ISSUE THREAD

**Issue by naiveaiguy** [flutter/flutter#15515]
For example, the prefix example in the material design guidelines:

<img width="247" alt="prefix_example" src="https://user-images.githubusercontent.com/8231396/37392890-84c09740-2795-11e8-8b37-b0515ac237b0.png">

Currently, there seems no way to do this. The prefix icon appears to the left of the label:

![current prefix](https://files.gitter.im/flutter/flutter/nuMG/Screen-Shot-2018-03-14-at-9.51.32-AM.png)

**Comment by HansMuller** [comment]
Thanks for pointing this out, it's a bug. The label and the prefix icon should be vertically aligned, just as they are in the spec.  I will fix it.

**Comment by naiveaiguy** [comment]
As it turns out, the guidelines use prefix *text* for this, not icons - and those are already correctly positioned. So this issue is unnecessary. Sorry about that @HansMuller!
