### ISSUE TITLE
How to know if the user uses a 12 or 24 hour time format in the setting of phone?

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15512]
I want to display the time appropriately  no matter the languages selected : 

12-hours :  1:00 PM
24-hours: 13:00

**Comment by zoechi** [comment]
This question should better be asked on StackOverflow
See https://docs.flutter.io/flutter/widgets/MediaQueryData/alwaysUse24HourFormat.html

**Comment by mit-mit** [comment]
Closing as there is no known issue here

**Comment by realcarlos** [comment]
Thank you @zoechi  , but I don't want the value of DateTime changes with the locale, so alwaysUse24HourFormat can not do that , I just want to display am or pm , so I need know the setting .

**Comment by Nazarii77** [comment]
So, how to know what user wants to see? 16:00 or 4:00 PM ?
