### ISSUE TITLE
Lack of clarity in step 5 of flutter_firebase codelab

### ISSUE THREAD

**Issue by gmalagutti** [flutter/flutter#15516]
In 'Configure Firebase for iOS', step 5 I can read
'Firebase generates an Info.plist file that contains configuration details for iOS apps to connect to the Firebase service you created.'
but, for what I have seen, Firebase does not generate a file Info.plist, only a file GoogleService-Info.plist and this file should be downloaded and placed into the directory.
What am I expected to do, rename the file after downloading? If not, where do I get the Info.plist from?

**Comment by mit-mit** [comment]
Sorry, step 5 of what? Can you link to where you are seeing this?

**Comment by gmalagutti** [comment]
I apologize for not adding all the references.
The URL is
https://codelabs.developers.google.com/codelabs/flutter-firebase/#4
5. Set up Firebase integration > Configure Firebase for iOS > 
"Firebase generates an Info.plist file that contains configuration details for iOS apps to connect to the Firebase service you created. Download this file to your development machine. (You do not need to complete the other steps in the wizard.)"

**Comment by mit-mit** [comment]
Looks like the file name may have changed; I also see `GoogleService-Info.plist `, cc @mjohnsullivan

**Comment by mit-mit** [comment]
@gmalagutti is it working correctly if you ignore the incorrectly stated filename?

**Comment by gmalagutti** [comment]
If I copy the downloaded file beside the one distributed in the codelab I still get an error of type 'The default Firebase app has not yet been configured. Add...'
I edited the standard Info.plist to add the portion of xml to activate the google sign-in, but that has not addressed the issue. The app does not start on my Mac - I am using Android Studio based on IntelliJ.

**Comment by smkhalsa** [comment]
I'm having the same issue

**Comment by smkhalsa** [comment]
The full error I'm seeing is:

```
4.10.1 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
```

**Comment by zoechi** [comment]
@smkhalsa As far as I know this is not an error message, merely an hint that you are not using the new feature described in the line contained in the message. 
The feature is explained in the Firebase docs.

**Comment by smkhalsa** [comment]
@zoechi Yes, you are correct. It's now working for me. It wasn't displaying the data before, and I assumed it was because of this, but it turns out it was another issue.

**Comment by gmalagutti** [comment]
Although I failed to get it to work following the instructions, the other steps of the tutorial, downloaded inside the sam zip do work, so I was able to move on

**Comment by LRNZ09** [comment]
I have the same message about Firebase not configured that @smkhalsa quoted, even with the repo `friendlychat-steps` used by the tutorial. Is a false positive or not?

**Comment by Sfshaza** [comment]
This codelab has been obsoleted and replaced (at the same URL) with an entirely new codelab.

Closing.
