### ISSUE TITLE
Extra line rendered when using Padding

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter#15519]
## Steps to Reproduce

  1. Create a custom `PreferredSizeWidget` (for use in the `appBar` of a `Scaffold`)
  2. Place a Container with a Background Color as the root Widget within the `PreferredSizeWidget`
  3. Add `padding` to the `Container`
  4. Launch on PixelXL device.
  5. Notice Extra Line
  6. Launch on emulator / iOS simulator
  7. No such line exists

Sorry I can't share the exact code -- it's a closed source project!

## Temp. Fix

  1. Remove bottom padding from container
  2. Use a Column + SizedBox as the last element for extra spacing

### PixelXL -- Extra Line under Search Box

![pixelxl](https://user-images.githubusercontent.com/126604/37408028-8baaa98c-279b-11e8-9a37-ab7da6c92057.png)

### Emulator (expected result)

![emulator](https://user-images.githubusercontent.com/126604/37408123-bfa34b54-279b-11e8-98c1-31e7cc39742f.png)

## Logs

```
Initializing gradle...                                0.9s
Resolving dependencies...                             0.8s
Launching lib/main.dart on Pixel XL in release mode...
Running 'gradlew assembleRelease'...                      
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Built build/app/outputs/apk/release/app-release.apk (13.7MB).
Installing build/app/outputs/apk/app.apk...           7.9s
```

Run `flutter analyze` and attach any output of that command also.

```
No issues found!
Ran in 7.4s
```

## Flutter Doctor

```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[✓] VS Code (version 1.20.0)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by xqwzts** [comment]
Sounds like this issue: https://github.com/flutter/flutter/issues/15035#issuecomment-370028740

**Comment by brianegan** [comment]
@xqwzts Thanks! Had searched but didn't see that one. Closing now.
