### ISSUE TITLE
Flutter Android studio plugin - wrong option when it's already Android studio

### ISSUE THREAD

**Issue by PareshMayani** [flutter/flutter#15520]
![screen shot 2018-03-14 at 7 58 39 pm](https://user-images.githubusercontent.com/888080/37408724-af67cdd8-27c2-11e8-9f99-d88f5cd28173.png)

## Steps to Reproduce
As shown in attached image, we are finding "Open in Android studio..." option under Tools => Flutter menu, though it's already Android studio.

## Flutter Doctor

/Users/paresh.mayani/Documents/Paresh/Software_Tools/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.1 17B1003, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio
[✓] Android Studio (version 3.0)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by devoncarew** [comment]
Thanks for the feedback! @stevemessick can confirm, but I believe this option will actually open the `android/` submodule in Android Studio, allowing you to better work on the native side of your app.

**Comment by PareshMayani** [comment]
Clicking on this option is opening .iml file actually!

**Comment by stevemessick** [comment]
That menu item name was misleading. It was changed in https://github.com/flutter/flutter-intellij/pull/1758. It now opens the Android module, not the .iml file. There's more work to improve it for Flutter plugins, in progress.

It would be easier for us to have Android Studio issues reported to the [flutter-intellij](https://github.com/flutter/flutter-intellij) project. We'll find them here, anyway.

**Comment by PareshMayani** [comment]
cool to see this fixed! 👍
