### ISSUE TITLE
[Camera_Windows] - The app crashes during camera initialization on Windows 10.

### ISSUE THREAD

**Issue by islamroshan** [flutter/flutter#155223]
I'm using the `camera_windows` plugin to initialize and capture images from the camera stream.

**Issue:**
The `camera_windows` plugin works perfectly in the development environment. However, after generating the MSIX executable for Windows using GitHub Actions and downloading the MSIX from GitHub, the app runs fine until I initialize the camera. At that point, the app crashes and closes itself without any error logs.

**Error Logs:**
I tried capturing any error logs, but no errors are displayed.

**General Explanation:**
When initializing the camera, the USB-connected camera light briefly turns blue for a second, and then the app crashes. After multiple attempts to resolve the issue, I suspect the problem might be within the core plugin. I also tested a simple camera plugin using OpenCV, and it worked even after building the MSIX with GitHub Actions. However, the issue with the custom OpenCV-based plugin is that it displays the camera stream in a separate window, while I prefer the camera_windows plugin since it displays the stream inside the Flutter UI.

Any recommendations on how to fix the `camera_windows` issue would be greatly appreciated.

Thanks!

**Comment by danagbemava-nc** [comment]
Hi @islamroshan, what version of `camera` & `camera_windows` are you using? Please also provide the output of `flutter doctor -v`. 

Do you get this issue only with the usb-connected camera? What about the built-in camera (if the device has one)? What camera are you using and do you get this issue with `flutter run -d windows --release`?

**Comment by GhayasAbouFakher** [comment]
Hello,
I have same issue and I'm using these versions
camera: ^0.11.0+1
camera_windows: ^0.2.2
and this issue happens while using both (build-in and USB-connected) cameras.
camera is working fine in Debug mode without any exception but when I release to Production, App will crash when init the camera.
plus, App Setting shows that App has permission to use camera.

**Comment by danagbemava-nc** [comment]
Hi @GhayasAbouFakher, can you share the error message that the app crashes with? You should be able to capture the exceptions in production using sentry or firebase_crashlytics. Does this also happen with the camera example code?

**Comment by GhayasAbouFakher** [comment]
Hello again
unfortunately yes the camera example code doing same in production.
I just noticed that camera_platform_interface is no longer available on https://pub.dev/packages .
there is another package "camera_platform_interface2" could you please check this?
Appreciate!

**Comment by danagbemava-nc** [comment]
The camera platform interface plugin is still on pub https://pub.dev/packages/camera_platform_interface

Were you able to capture the crash message?
