### ISSUE TITLE
Performance issues with rendering widgets on Windows and web platforms.

### ISSUE THREAD

**Issue by abineshPalanisamy** [flutter/flutter#155293]
### Steps to reproduce

1. Run the attached sample on both Windows and web platforms.
2. Observe the rendering time (**Initial loading time**) of the DataTable widget for both the web and Windows platforms.

### Expected results

The rendering time for the DataTable widget in Windows and the web should be **equal or have minimal differences.**

### Actual results

The rendering time for the DataTable widget differs between Windows and the web, with the web **taking significantly more time**.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Rendering Time Sample',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  // ignore: library_private_types_in_public_api
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late int startTime;

  @override
  void initState() {
    super.initState();
    startTime = DateTime.now().millisecondsSinceEpoch;
    // Measure render time after frame is built
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final endTime = DateTime.now().millisecondsSinceEpoch;
      print('Render Time of TableWidget: ${endTime - startTime} ms');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Rendering Time Measurement'),
      ),
      body: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: DataTable(
            columns: List.generate(
              100,
              (index) => DataColumn(label: Text('Col ${index + 1}')),
            ),
            rows: List.generate(
              30,
              (rowIndex) => DataRow(
                cells: List.generate(
                  100,
                  (colIndex) =>
                      DataCell(Text('Row ${rowIndex + 1} Col ${colIndex + 1}')),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Platform | TimeTaken (ms)
-- | --
Windows | 355 ms
Web | 1553 ms

</div>

</body>

</html>

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.19045.4894], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.9.6)
[!] Android Studio (version 2021.3)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.93.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @abineshPalanisamy 
Since you are using `DataTable` widget, per it's [documentation](https://api.flutter.dev/flutter/material/DataTable-class.html):

<img width="926" alt="Screenshot 2024-09-18 at 12 14 36 PM" src="https://github.com/user-attachments/assets/d8b40b44-d813-4a27-82b7-ac9fdde88fb9">

Try to read through the documentation for performance based consideration and see if using `PaginatedDataTable` helps in your use case or not.

**Comment by abineshPalanisamy** [comment]
Hi @darshankawar ,

Our issue is that **loading times vary depending on the platform**. We haven’t mentioned the performance of the DataTable in relation to other widgets. The problem we’re facing is with rendering time (initial loading time), which **differs significantly between Windows and web platforms.** Both Windows and web platforms use a DataTable widget with 100 columns and 30 rows, but the loading times vary considerably between the two.

Regards 
Abinesh P

**Comment by darshankawar** [comment]
Thanks for the update. Although I don't have windows machine to verify, but I tried on macOS and below are my observations:

1. Web:

```
canvaskit : Render Time of TableWidget: 3560 ms

html : Render Time of TableWidget: 2992 ms
```

2. macOS desktop:

`flutter: Render Time of TableWidget: 2041 ms`

3. mobile (android emulator):

`I/flutter (11542): Render Time of TableWidget: 4243 ms`


If you see the web and desktop timings, there's not huge gap / difference (1519 ms, as compared to 1198 from your findings), while, mobile took most of the time among other platforms.

Are you consistently getting this difference everytime you run on both platforms ? Can you also check on mobile as well ?

**Comment by abineshPalanisamy** [comment]
Hi @darshankawar ,

Yes, we consistently face differences. My main question is **why the initial loading time varies across platforms**. We have used a DataTable with 100 columns and 30 rows on both Windows and web platforms, and the loading time differs depending on the platform. **What is the core reason for these variations in loading time?**. Could you please investigate this issue and provide a suitable solution?

Regards,
Abinesh P

**Comment by berslen** [comment]
I would like to also add that the performance issue mentioned doesn't happen on flutter version 3.19.6. after 3.2x update the performance issue can be seen as far as I can see. I'll drop my related rendering times between different flutter version in both platforms when I have chance.

**Comment by yjbanov** [comment]
The big difference between loading a web app vs a desktop app is that the desktop app is preinstalled and doesn't need to be fetched over the network. OTOH, a web app is first fetched over the network and then interpreted by the browser. This is why desktop apps are almost always faster to load. This is expected. We are continuously working on improving web app load times though.

As for the difference in time to render the table (after the app is loaded), we can take a look. However, it seems like the numbers reported in the original post disagree with the numbers from the triage. Are we sure the difference is that big?

**Comment by abineshPalanisamy** [comment]
Hi @yjbanov ,

The loading time difference between the web and Windows platforms has significantly increased since version 3.22.0. In version 3.19.0, the difference was comparatively smaller, **indicating that the loading time has noticeably worsened**.

Based on the details you provided, it seems you are working on improving the initial loading time (**performance**) for the web platform. Could you share the expected timeline for these improvements? Additionally, can you specify which version will include the fix?

Regards,
Abinesh P

**Comment by yjbanov** [comment]
We're improving load times as part of several independent efforts, such as reducing file sizes, splitting fonts, using wasm for faster initial execution times, etc. There's no one fix and a timeline for it. If there was a significant regression in a particular metric between two versions of Flutter, please provide a repro that measures that one metric (be sure to run the app in release mode). If we cannot confirm the regression in triage, we won't be able to fix it.
