### ISSUE TITLE
Flutter Web Cache problem

### ISSUE THREAD

**Issue by nrajput05** [flutter/flutter#155240]
### Steps to reproduce

After deploying a new version of flutter web app on my server, the latest version/code/UI is not updated until you clear the cache or open the web app once in incognito mode. I have seen 3-4 threads and SO questions on this same issue pointing to add the query string "?v=123123"(random hash) to the main.dart.js in the index.html but those answers date back to 2020 and as of now flutter's index.html doesn't have anything to do with main.dart.js where I can add a random hash. It seems to have been replaced by bootstrap/serviceworker. 

In this context, **what is the most apt way of cache busting in case of new releases**? It would be great to have a mechanism which could load new version of the flutter web app ignoring browser's cache for every new release.

Threads already checked:

1. https://github.com/flutter/flutter/issues/64968
2. https://github.com/flutter/flutter/issues/57964
3. https://stackoverflow.com/questions/77004203/how-to-prevent-cache-in-webapp-flutter-for-web

### Expected results

Whenever a new release is deployed on the server, then the flutter web app should ignore the cache.

### Actual results

On every new release, the user has to clear the cache to see the changes.

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.1.2 23B92 darwin-arm64 (Rosetta), locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.93.0)
[✓] Connected device (3 available)            
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

**Comment by darshankawar** [comment]
@nrajput05 
Check [this](https://github.com/flutter/flutter/issues/104509) issue and underlying comments to see if they help in your case or not.

**Comment by nrajput05** [comment]
Looks somewhat similar. In my case, even if the end user doesn't have an active web app while the deployment happens, still there is a problem. 
Steps:
1. Deployment
2. End user who has previously opened the website opens it again
3. Cached version is displayed until cache is cleared.

**Comment by selimb86** [comment]
It seems that the new Flutter web updates this is automatically handled correctly if you have an updated index.html as it only loads to 'flutter_bootstrap.js' which has the auto updated 'serviceWorkerVersion'. 

So it seems that if you just configure your server to not cache `flutter_bootstrap.js` it will detect on the next load the updated version and (un)cache updated files based on their hash in `flutter_service_worker.js`.

At least this is what I currently reached after some experiencing and needs to be confirmed.

@nrajput05

**Comment by nrajput05** [comment]
I will try this @selimb86 .
Is this something expected to be in the latest flutter version? I am on 3.22.0. right now and I do see 3.24.0 is available

**Comment by darshankawar** [comment]
@nrajput05 Try https://docs.flutter.dev/platform-integration/web/initialization#flutter_bootstrap-js

**Comment by nrajput05** [comment]
@darshankawar I tried the no-cache for flutter_bootstrap.js on a node server on my local machine. Here is the server.js for it but even after this I have to refresh at least twice to get the new content. Is this expected? 

I also see the one of the contributors have [provided a solution back in 2021](https://github.com/flutter/flutter/issues/57391#issuecomment-981060296) regarding this issue. Is this still valid approach?

`const express = require('express');
const path = require('path');
const app = express();

//Middleware to disable caching for flutter_bootstrap.js
app.use((req, res, next) => {
  if (req.url === '/flutter_bootstrap.js') {
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
    res.setHeader('Pragma', 'no-cache');
    res.setHeader('Expires', '0');
  }
  next();
});

// Serve static files from the 'build/web' folder (Flutter Web build output)
app.use(express.static(path.join(__dirname, 'build/web')));

// Fallback to index.html for any unknown routes (for Flutter Web routing)
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'build/web', 'index.html'));
});

// Start the server
const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});`

**Comment by iapicca** [comment]
@nrajput05 
does [this](https://github.com/flutter/flutter/issues/104509#issuecomment-1454867604) help?

**Comment by nrajput05** [comment]
I will have to try this and get back
