### ISSUE TITLE
"flutter packages get" stuck, causes "startup lock"

### ISSUE THREAD

**Issue by deborah-ufw** [flutter/flutter#15527]
## Steps to Reproduce

This process has happened 3 times this morning. Does not matter whether or not IntelliJ is open.

- in app root folder, open a terminal window
- "git pull origin master"
- when it's finished, run a clean script
- in new terminal window, "flutter packages get" (sticks if not in new window)
- wait 10 minutes, nothing seems to be happening
- kill terminal 
- open new terminal, "flutter packages get"

... get message "Waiting for another flutter command to release the startup lock..."

have to reboot to try again.

## Logs

Can not "flutter run", get message "Waiting for another flutter command to release the startup lock..."

## Flutter Doctor

Can not "flutter doctor", get message "Waiting for another flutter command to release the startup lock..."

**Comment by Hixie** [comment]
What platform?
If you reboot, can you run `flutter doctor -v`? What does it say?
What does `ps aux` say?

**Comment by zoechi** [comment]
In older Flutter versions this was common when `build_runner` was used #17422

**Comment by po1arbear** [comment]
I've sovled this problem after run "flutter doctor -v"，and then run "flutter upgrade" according to the warning message @Hixie  thx~!

**Comment by shavigrewal** [comment]
Hello guys,
I was also facing this issue  in Android studio .And solved it by uninstalling both flutter and dart plugins. When we reinstall them issue is gone .
Good luck .

**Comment by Devcyclops** [comment]
Open your task manager then check for adb.exe processes running and end them.... That worked for me
