### ISSUE TITLE
I can't run flutter.

### ISSUE THREAD

**Issue by Mehrzad2011** [flutter/flutter#155256]
Hello
when I run flutter, i see this: ../../runtime/vm/object.h: 13418: error: unreachable code              version=3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "linux_arm" pid=9201, thread=9201, isolate_group=main(0x11267f20), isolate=main(0x1126a440)                                                               os=linux, arch=arm, comp=no, sim=no                                    isolate_instructions=ed194000, vm_instructions=10e9b140                fp=ffbd2a90, sp=ffbd2a20, pc=10fedf0d                                    pc 0x10fedf0d fp 0xffbd2a90 dart::Profiler::DumpStackTrace+0x4d        pc 0x10e9b25f fp 0xffbd2aa0 dart::Assert::Fail+0x1f                    pc 0x10fc79ab fp 0xffbd2ac8 dart::String::CodePointIterator::Next+0xc3                                                                        pc 0x110468e7 fp 0xffbd2af0 dart::Utf8::Length+0x4b                    pc 0x10faa21b fp 0xffbd2b10 dart::Class::SetUserVisibleNameInClassTable+0x5b                                                                  pc 0x10f5820b fp 0xffbd2b28 dart::ClassTable::PopulateUserVisibleNames+0x2f                                                                   pc 0x10f5d647 fp 0xffbd2ba0 dart::Dart::InitIsolateGroupFromSnapshot+0x15f                                                                    pc 0x10f5d69f fp 0xffbd2be8 dart::Dart::InitializeIsolateGroup+0x1b    pc 0x1119203b fp 0xffbd2f10 dart::CreateIsolate+0xa7                   pc 0x11192277 fp 0xffbd2fa0 Dart_CreateIsolateGroup+0xf3               pc 0x10e99985 fp 0xffbd3028 dart::bin::CreateIsolateGroupAndSetupHelper+0x1e9                                                                 pc 0x10e99597 fp 0xffbd30a8 dart::bin::RunMainIsolate+0x7b             pc 0x10e9a043 fp 0xffbd3158 dart::bin::main+0x44b                      pc 0x10e994ff fp 0xffbd3168 main+0xb                                 -- End of DumpStackTrace                                               Aborted

How can i solve this?

**Comment by ZhuJHua** [comment]
You should raise an issue instead of a PR.

For your question, it may be caused by your use of ARM-based linux, which is not currently supported by flutter.

**Comment by Mehrzad2011** [comment]
So,  what should I do?

**Comment by ZhuJHua** [comment]
> So, what should I do? I really need to flutter.

You can just try [flutter-elinux](https://github.com/sony/flutter-elinux).

**Comment by Mehrzad2011** [comment]
Thanks I'll try it.
