### ISSUE TITLE
Slide changed callback on carousel controller

### ISSUE THREAD

**Issue by RohanKPOfficial** [flutter/flutter#155246]
### Use case

carousel_slider provides the callbacks requested in this issue , its unfortunately not an unconstrained view and instead enforces a fixed aspect ratio

### Proposal

3.24 brought in the carousel view and its a welcome feature. Curiously it provides the snapping feature however couldn't find any builtin callback for when the items change or when the carousel snaps to any particular child on the widget or on the controller. Ended up using pageview instead for now. but it would be a great addition given snapping is available as an option. Also its common for carousels to have a slide indicator , if a callback and an index is available it would be handy to build those.

**Comment by darshankawar** [comment]
@RohanKPOfficial 
Can you provide a code example that shows current limitation along with expected behavior using CarouselView so that we can properly address it ?
