### ISSUE TITLE
How do I export Flutter reports for both mobile (flutter test) and web (flutter drive)

### ISSUE THREAD

**Issue by ThatPham2000** [flutter/flutter#155244]
### Type of Request

feature request

### Infrastructure Environment

bitbucket, jenkins

### What is happening?

As a project manager, I want to know the system coverage. As a developer, I want a way to export CONSISTENT reports for both platforms including mobile (flutter test), and web (flutter drive) so that I can consistently map to UI.

In mobile, I already exported the json report via **_flutter test integration_test/app_test.dart --file-reporter json:report.json | tee output.log_**

On the web, I did not see how to export the report via **_flutter drive_**

Are there any ways to export them consistently?

Thanks.

**Comment by darshankawar** [comment]
@ThatPham2000 
For integration_test, you can use below command to export report:

`flutter test integration_test --coverage -r json > integration-test-results.json`

For flutter driver web, I don't think there's a --coverage flag, so I am not sure if it is possible to get report for flutter driver currently. See https://github.com/flutter/flutter/issues/7474

**Comment by ThatPham2000** [comment]
Thank you for your update. Anyway, are there any ways to export JSON (XML) reports for flutter web integration testing (via flutter drive)?

**Comment by darshankawar** [comment]
Please check https://github.com/flutter/flutter/issues/51135 with underlying comments and also https://github.com/flutter/flutter/issues/14134 for further reference.
