### ISSUE TITLE
Flutter FCM Not Working When App is Terminated on Android

### ISSUE THREAD

**Issue by Mohamed-Ash** [flutter/flutter#155233]
### Steps to reproduce

I am encountering an issue where FCM notifications are not working when the app is terminated on Android devices. The notifications function correctly when the app is running or in the background, but they do not appear when the app is completely closed (terminated).

### Expected results

The app should receive and display FCM notifications even when it is fully terminated (closed)

### Actual results

Notifications not received.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=com.barber_salon.barber_salon (has extras) }
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.4894], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by danagbemava-nc** [comment]
This should be reported on flutterfire repository or if you're not using the firebase_messaging plugin, you should report this on the repository of the plugin you're using as this is related to the plugins rather than flutter itself. 

Closing from here. 

Thank you
