### ISSUE TITLE
Add option to rotate camera image

### ISSUE THREAD

**Issue by realtebo** [flutter/flutter#155283]
### Use case

for plugin camera, please add option to rotate image

some Zebra's table has a bug and I supposed some others, so images when taking photo are rotated of 90 degrees

### Proposal

A simple option to rotate camera could be useful

This could be using hardware apis, I think. 
Or adding exif data in the resulting file to 'force' rotation

**Comment by darshankawar** [comment]
> so images when taking photo are rotated of 90 degrees

@realtebo I think you are hitting https://github.com/flutter/flutter/issues/154241 that you can check.

**Comment by realtebo** [comment]
@darshankawar probably yes, for the precision, I landed to #154241 and, from this, I ended on a thread about a fix on camera 0.10 but I'm using 0.11.0+1 and so I think about rollback or not yet properly fixed.

I'll keep watching the thread #154241

**Comment by darshankawar** [comment]
> taking photo are rotated of 90 degrees

This is actually a bug that is being tracked in linked issue, so fixing it will also resolve your use case, so I think let's track this in linked issue for further updates. I will close this as duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by realtebo** [comment]
I thinks that having such an option could be useful.
So, If some hedge cases needs it, it's available.
Actually, to bypass the bug we need to implement an image selector, a photo editor, the rotation, and the saving of photo.
