### ISSUE TITLE
Failed to build iOS app Error (Xcode): 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by herdianajones** [flutter/flutter#155287]
### Steps to reproduce

flutter build ios --release --flavor stg

**pubspec.yaml configuration**
environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  flutter: 
    sdk: flutter

 
  async: ^2.4.1
  avatar_glow: ^2.0.2
  barcode_scan2: ^4.2.2
  cached_network_image: ^3.2.2
  carousel_slider: ^5.0.0
  cloud_firestore: ^4.4.4
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.5
  device_info: ^2.0.3
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  environment_config: ^3.1.0
  firebase_analytics: ^10.0.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.1.0
  firebase_crashlytics: ^3.0.2
  firebase_dynamic_links: ^5.0.2
  firebase_messaging: ^14.0.2
  flutter_custom_tabs: ^2.1.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_launcher_icons: ^0.10.0
  flutter_linkify: ^6.0.0
  flutter_markdown: ^0.6.12
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^6.0.0
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.0
  flutter_webview_plugin:
    git:
      url: https://github.com/Bhagat8533/flutter_webview_plugin # Repo
      ref: master  # Branch name
  font_awesome_flutter: ^10.2.1
  geolocator: ^9.0.2
  graphql_flutter: ^5.1.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.19.0
  location: ^4.4.0
  marquee: ^2.2.3
  overlay_support: ^2.0.1
  package_info_plus: ^5.0.1
  provider: ^6.0.4
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
  screenshot: ^3.0.0
  sentry_flutter: ^7.4.1
  share: ^2.0.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  timeago: ^3.3.0
  timezone: ^0.9.0
  url_launcher: ^6.1.6
  uuid: ^3.0.6
  validators: ^3.0.0
  webview_flutter: ^3.0.4
  wc_flutter_share: ^0.4.0
  flutter_parsed_text: ^2.2.1
  tutorial_coach_mark: 1.2.6
  flutter_native_image: ^0.0.5+3
  quiver: ^3.1.0
  another_flushbar: ^1.12.29
  country_calling_code_picker: ^2.0.1
  country_picker: ^2.0.19
  super_banners: ^0.0.1
  connectivity_plus: ^3.0.3
  app_settings: ^5.1.1
  device_preview: ^1.1.0

  collection: any
  image: any
  linkify: any
  meta: any
dev_dependencies:
  flutter_test:
    sdk: flutter
    
❯ flutter pub deps -s compact
Dart SDK 3.5.0
Flutter SDK 3.24.0
myapp 2.9.1+140

dependencies:
- another_flushbar 1.12.30 [flutter]
- app_settings 5.1.1 [flutter plugin_platform_interface]
- async 2.11.0 [collection meta]
- avatar_glow 2.0.2 [flutter]
- barcode_scan2 4.3.3 [flutter protobuf]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- carousel_slider 5.0.0 [flutter]
- cloud_firestore 4.15.8 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.18.0
- connectivity_plus 3.0.6 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- country_calling_code_picker 2.0.1 [flutter flutter_sim_country_code]
- country_picker 2.0.26 [collection universal_io flutter]
- cupertino_back_gesture 0.1.0 [flutter]
- cupertino_icons 1.0.8
- device_info 2.0.3 [flutter device_info_platform_interface]
- device_preview 1.2.0 [flutter flutter_localizations provider device_frame freezed_annotation json_annotation shared_preferences collection]
- dio 4.0.6 [http_parser path]
- dotted_border 2.1.0 [flutter path_drawing]
- environment_config 3.2.0 [dart_style code_builder args yaml]
- firebase_analytics 10.8.9 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.17.8 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.27.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.18 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.4.17 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.7.19 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_custom_tabs 2.1.0 [flutter flutter_custom_tabs_platform_interface flutter_custom_tabs_android flutter_custom_tabs_ios flutter_custom_tabs_web meta]
- flutter_datetime_picker_plus 2.2.0 [flutter]
- flutter_keyboard_visibility 5.4.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_launcher_icons 0.10.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_linkify 6.0.0 [flutter linkify]
- flutter_markdown 0.6.23 [flutter markdown meta path]
- flutter_native_image 0.0.6+1 [flutter]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_parsed_text 2.2.1 [flutter]
- flutter_secure_storage 6.1.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_slidable 3.1.1 [flutter]
- flutter_svg 2.0.9 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_webview_plugin 0.1.0 [flutter]
- font_awesome_flutter 10.7.0 [flutter]
- geolocator 9.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- graphql_flutter 5.1.2 [graphql gql_exec flutter meta path_provider path connectivity_plus hive plugin_platform_interface flutter_hooks]
- http 0.13.6 [async http_parser meta]
- image 3.3.0 [archive meta xml]
- image_picker 0.8.9 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.19.0 [clock meta path]
- linkify 5.0.0
- location 4.4.0 [flutter location_platform_interface location_web]
- marquee 2.2.3 [fading_edge_scrollview flutter]
- meta 1.15.0
- overlay_support 2.1.0 [flutter async]
- package_info_plus 5.0.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- provider 6.1.2 [collection flutter nested]
- pull_to_refresh 2.0.0 [flutter]
- qr_flutter 4.1.0 [flutter qr]
- quiver 3.2.2 [matcher]
- screenshot 3.0.0 [flutter]
- sentry_flutter 7.20.2 [flutter flutter_web_plugins sentry package_info_plus meta ffi]
- share 2.0.4 [meta mime flutter]
- shared_preferences 2.2.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- super_banners 0.0.1 [flutter]
- timeago 3.7.0 [intl]
- timezone 0.9.4 [path]
- tutorial_coach_mark 1.2.6 [flutter flutter_lints]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.7 [crypto]
- validators 3.0.0
- wc_flutter_share 0.4.0 [flutter path_provider]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _fe_analyzer_shared 72.0.0 [meta]
- _flutterfire_internals 1.3.25 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.2
- analyzer 6.7.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- archive 3.6.1 [crypto path]
- args 2.5.0
- boolean_selector 2.1.1 [source_span string_scanner]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.2.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.10.8 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+8 [meta web]
- crypto 3.0.5 [typed_data]
- dart_style 2.3.7 [analyzer args collection package_config path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_frame 1.2.0 [freezed_annotation flutter]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fading_edge_scrollview 3.0.0 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.9.9 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+21 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 7.1.8 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.9.8 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.2.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_crashlytics_platform_interface 3.6.25 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+25 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.27 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.6.8 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_custom_tabs_android 2.1.0 [flutter flutter_custom_tabs_platform_interface meta]
- flutter_custom_tabs_ios 2.1.0 [flutter flutter_custom_tabs_platform_interface meta]
- flutter_custom_tabs_platform_interface 2.1.0 [flutter meta plugin_platform_interface]
- flutter_custom_tabs_web 2.1.0 [flutter flutter_web_plugins flutter_custom_tabs_platform_interface meta url_launcher_web url_launcher_platform_interface]
- flutter_hooks 0.18.6 [flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_lints 2.0.3 [lints]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.22 [flutter]
- flutter_secure_storage_linux 1.2.1 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 1.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_sim_country_code 0.1.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- geolocator_android 4.3.1 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.3.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.2.1 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- gql 0.14.0 [collection meta source_span]
- gql_dedupe_link 2.0.3+1 [async gql_exec gql_link meta]
- gql_error_link 0.2.3+1 [async gql_exec gql_link meta]
- gql_exec 0.4.3 [collection gql meta]
- gql_http_link 0.4.5 [gql gql_exec gql_link http http_parser meta]
- gql_link 0.5.1 [gql gql_exec meta]
- gql_transform_link 0.2.2+1 [gql_exec gql_link]
- graphql 5.1.3 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_socket_channel stream_channel rxdart uuid]
- hive 2.2.3 [meta crypto]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.12+13 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.12 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 2.1.1
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- macros 0.1.2-main.4 [_macros]
- markdown 7.2.2 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- mime 1.0.6
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- normalize 0.7.2 [gql collection]
- octo_image 2.1.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.4 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.10 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.5
- plugin_platform_interface 2.1.8 [meta]
- protobuf 3.1.0 [collection fixnum meta]
- pub_semver 2.1.4 [collection meta]
- qr 3.0.2 [meta]
- rxdart 0.27.7
- sentry 7.20.2 [http meta stack_trace uuid]
- shared_preferences_android 2.3.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.3.3+1 [flutter sqflite_common path]
- sqflite_common 2.5.4+3 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- synchronized 3.3.0+2
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.3.10 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.2 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.10+1 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.10+1
- vector_graphics_compiler 1.1.10+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 14.2.4
- watcher 1.1.0 [async path]
- web 0.4.2
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webview_flutter_android 2.10.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.5 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.5 [flutter path webview_flutter_platform_interface]
- win32 5.5.4 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

**What I've Tried**
- https://www.reddit.com/r/flutterhelp/comments/n0zlcs/comment/kqif18s/
- https://stem.prasetiyamulya.ac.id/flutter-flutter-h-file-not-found/
- https://www.chethanprabhakar.com/flutter-fixes/flutter-h-file-not-found

"I've been trying to fix this bug for a week.

### Actual results

Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/me/apps/myapp/ios/Runner/GeneratedPluginRegistrant.h:9:8

Error (Xcode): failed to emit precompiled header
'/Users/me/Library/Developer/Xcode/DerivedData/Runner-dpambswswsgpmjcovgqrqfbvwycq/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_32WP8FD3Z0IT8-clang_14TOH7QCSTDMV.pch' for bridging header
'/Users/me/apps/myapp/ios/Runner/Runner-Bridging-Header.h'

Encountered error while building for device.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-x64, locale en-ID)
    • Flutter version 3.24.0 on channel stable at /Users/Herdiana/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (7 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Herdiana/Library/Android/sdk
    • Platform android-34, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@herdianajones 
Check [this](https://github.com/flutter/flutter/issues/135002#issuecomment-1727079620) and see if it helps to resolve your issue or not.

**Comment by herdianajones** [comment]
thank you @darshankawar . Will try
