### ISSUE TITLE
Need a way to specify an appBar "detail view" whose size is based on the screen's width

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#1552]
The figure on the right side of the "Detail View" section of
https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing says that the size of the area below the toolbar/statusbar should have an aspect ratio of 3:2.  The current API really needs a fixed appBar height.

See https://github.com/flutter/flutter/pull/1540

**Comment by Hixie** [comment]
We should update the gallery to do this right. It should be relatively easy to do with a `MediaQuery.of` call.

**Comment by khalithartmann** [comment]
Hello you awesome people!
I just created a Let's Flutter Berlin group on Facebook to bring flutter developers in Berlin together to discuss problems, share ideas and create beautiful things together. If you live in Berlin, it would be awesome if you could join the group 😊! If you don't live in Berlin, feel free to join too! Im grateful for each and every supporter.  

Let's Flutter Berlin: https://www.facebook.com/groups/276520973054067/about/
Sorry for spamming.

**Comment by esarbanis** [comment]
Is this issue still relevant? I see that the code has changed greatly since this issue was created.

**Comment by HansMuller** [comment]
I'm closing this per https://github.com/flutter/flutter/issues/1552#issuecomment-678245947.  Thanks @fourman-alex!
