### ISSUE TITLE
Xcode16, Flutter 2.10.5, ios build failed

### ISSUE THREAD

**Issue by Zipper-Code** [flutter/flutter#155381]
### Steps to reproduce

Run normally to ios device

### Expected results

success

### Actual results

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/104ebac0-49bd-41c3-bb83-d263d33f43e3">

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/fec3dac0-9533-46cc-acda-c81766794dc6">

### Flutter Doctor output

<img width="1246" alt="image" src="https://github.com/user-attachments/assets/fa273444-b661-4ba2-bd26-a49606d0e284">

**Comment by softwarezhou** [comment]
I have also encountered the same problem as you

**Comment by Zipper-Code** [comment]
> I have also encountered the same problem as you

It's really strange. Do I have to force update to the latest version of flutter?

**Comment by softwarezhou** [comment]
> > I have also encountered the same problem as you
> 
> It's really strange. Do I have to force update to the latest version of flutter?

I don't recommend doing this, the cost is too high

**Comment by darshankawar** [comment]
@Zipper-Code 
You are on very old version of the framework. Latest is 3.24.3, so I recommend to upgrade your sdk to latest stable and re-run your scenario to check if you still get reported behavior or not. If still yes, provide the error log in properly formatted text instead of in screenshot.

**Comment by Zipper-Code** [comment]
> @Zipper-Code You are on very old version of the framework. Latest is 3.24.3, so I recommend to upgrade your sdk to latest stable and re-run your scenario to check if you still get reported behavior or not. If still yes, provide the error log in properly formatted text instead of in screenshot.

OK, thanks
