### ISSUE TITLE
flutter build ios-framework  failed

### ISSUE THREAD

**Issue by Tang910103** [flutter/flutter#155391]
### Type of Request

bug

### Infrastructure Environment

![image](https://github.com/user-attachments/assets/6d29df5a-3970-4a5a-87db-e76c92e8c29d)

### What is happening?

``` 
flutter build ios-framework --output=build/archive/ios 

💪 Building with sound null safety 💪

Building frameworks for com.xinxin.flutter in debug mode...
 ├─Copying Flutter.xcframework...                                  152ms
ProcessException: Process exited abnormally:
ld: warning: -bitcode_bundle is no longer supported and will be ignored
ld: warning: -bitcode_process_mode is no longer supported and will be ignored
ld: -mllvm and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)
  Command: /usr/bin/arch -arm64e xcrun clang -x c -arch armv7 -arch arm64 /var/folders/g9/0wgph5b17nx69_lbpphzqkl40000gn/T/flutter_tools.uyrAGL/flutter_tools_stub_source.kzXATZ/debug_app.cc
  -dynamiclib -fembed-bitcode-marker -miphoneos-version-min=9.0 -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -install_name
  @rpath/App.framework/App -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk -o
  /Users/aa/Flutter/xinxin_flutter/.dart_tool/flutter_build/c9c2c595d19b6e94ade41d0a28918e57/App.framework/App
 ├─Building App.xcframework...                                     14.0s
The App.xcframework build failed.
```

### Expected results

I expect to see X when Y is finished.

**Comment by hjdev-codes** [comment]
Step to solve it 
-Disable Bitcode in Xcode
- checkpodfile 
(post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
en)
- update Xcode and flutter
- if still it doesn't help you out then rebuild only Ios dependency
-

**Comment by Tang910103** [comment]
> Step to solve it -Disable Bitcode in Xcode
> 
> * checkpodfile
>   (post_install do |installer|
>   installer.pods_project.targets.each do |target|
>   target.build_configurations.each do |config|
>   config.build_settings['ENABLE_BITCODE'] = 'NO'
>   end
>   end
>   en)
> * update Xcode and flutter
> * if still it doesn't help you out then rebuild only Ios dependency

Thanks for your answer! Your methods still don't solve the problem. I introduced flutter module using cocoapods. It ran successfully on the real machine, but failed on the emulator. The following is a snippet of the error message at runtime.

**Comment by danagbemava-nc** [comment]
Hi @Tang910103, you are using an older version of flutter. Kindly upgrade to the latest version of flutter 3.24.3 to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v` along with the full output of `flutter build ios-framework -v` so that we can properly investigate this issue. 

Thank you

**Comment by Tang910103** [comment]
Thanks for your answer! For some reason, it is not possible to upgrade flutter to 3.24.3, but it is strange that it can be built normally in Xcode Version 15.4 (15F31d)

**Comment by Tang910103** [comment]
> Hi @Tang910103, you are using an older version of flutter. Kindly upgrade to the latest version of flutter 3.24.3 to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v` along with the full output of `flutter build ios-framework -v` so that we can properly investigate this issue.
> 
> Thank you

Thanks for your answer! For some reason, it is not possible to upgrade flutter to 3.24.3, but it is strange that it can be built normally in Xcode Version 15.4 (15F31d)

**Comment by Tang910103** [comment]
> > Hi @Tang910103, you are using an older version of flutter. Kindly upgrade to the latest version of flutter 3.24.3 to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v` along with the full output of `flutter build ios-framework -v` so that we can properly investigate this issue.
> > Thank you
> 
> Thanks for your answer! For some reason, it is not possible to upgrade flutter to 3.24.3, but it is strange that it can be built normally in Xcode Version 15.4 (15F31d)

![image](https://github.com/user-attachments/assets/9386c31e-ee57-43dc-80bf-93aeb4499bc7)

**Comment by danagbemava-nc** [comment]
> but it is strange that it can be built normally in Xcode Version 15.4 (15F31d)

Hi @Tang910103, with almost every Xcode change, apple makes some changes to the build process which eventually gets fixed in flutter (when it is reported). The version of flutter you're using is too old to have the fixes (if this already has been fixed). We will need a complete minimal reproducible code sample with steps to reproduce so that we can properly investigate this. 

Also, in the future, please do not provide screenshots of your logs as screenshots are not searchable. 

Please also provide the full verbose output of `flutter build ios-framework -v` in a .txt file. 

Thank you

**Comment by Tang910103** [comment]
> > but it is strange that it can be built normally in Xcode Version 15.4 (15F31d)
> 
> Hi @Tang910103, with almost every Xcode change, apple makes some changes to the build process which eventually gets fixed in flutter (when it is reported). The version of flutter you're using is too old to have the fixes (if this already has been fixed). We will need a complete minimal reproducible code sample with steps to reproduce so that we can properly investigate this.
> 
> Also, in the future, please do not provide screenshots of your logs as screenshots are not searchable.
> 
> Please also provide the full verbose output of `flutter build ios-framework -v` in a .txt file.
> 
> Thank you

**Comment by Tang910103** [comment]
> > > but it is strange that it can be built normally in Xcode Version 15.4 (15F31d)
> > 
> > 
> > Hi @Tang910103, with almost every Xcode change, apple makes some changes to the build process which eventually gets fixed in flutter (when it is reported). The version of flutter you're using is too old to have the fixes (if this already has been fixed). We will need a complete minimal reproducible code sample with steps to reproduce so that we can properly investigate this.
> > Also, in the future, please do not provide screenshots of your logs as screenshots are not searchable.
> > Please also provide the full verbose output of `flutter build ios-framework -v` in a .txt file.
> > Thank you

Thanks for your answer! Attached is my detailed log. The version of flutter I use is as follows, and a flutter module without any code will reproduce the problem I encountered.
[build_log.txt](https://github.com/user-attachments/files/17158000/build_log.txt)

**Comment by danagbemava-nc** [comment]
Hi @Tang910103, I just created a new module and run `flutter build ios-framework` and it worked as expected. Can you try doing same with the latest stable version of flutter? You can use a tool like fvm to manage your flutter versions

```bash
fs create -t module app_module
Developer identity "Apple Development: XXXXXXXXX" selected
for iOS code signing
Creating project app_module...
Resolving dependencies in `app_module`... (6.6s)
Downloading packages...
Got dependencies in `app_module`.
Developer identity "Apple Development: XXXXXXXXX" selected
for iOS code signing
Developer identity "Apple Development: XXXXXXXXX" selected
for iOS code signing
Wrote 12 files.

All done!
Your module code is in app_module/lib/main.dart.
deanli@FE-9B-AF-FA-EE-10 projects % cd app_module
deanli@FE-9B-AF-FA-EE-10 app_module % ls
README.md		app_module_android.iml	pubspec.yaml
analysis_options.yaml	lib			test
app_module.iml		pubspec.lock
deanli@FE-9B-AF-FA-EE-10 app_module % fs build ios-framework

Building frameworks for com.example.appModule in debug mode...
 ├─Copying Flutter.xcframework...                                  142ms
 ├─Building App.xcframework...                                     10.2s
 └─Moving to build/ios/framework/Debug                               8ms
Building frameworks for com.example.appModule in profile mode...
 ├─Copying Flutter.xcframework...                                  112ms
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184
to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the
--no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184
to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the
--no-tree-shake-icons flag when building your app.
 ├─Building App.xcframework...                                     26.1s
 └─Moving to build/ios/framework/Profile                             6ms
Building frameworks for com.example.appModule in release mode...
 ├─Copying Flutter.xcframework...                                  713ms
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184
to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the
--no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184
to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the
--no-tree-shake-icons flag when building your app.
 ├─Building App.xcframework...                                     16.8s
 └─Moving to build/ios/framework/Release                             6ms
Frameworks written to /Users/deanli/projects/app_module/build/ios/framework.
```

**Comment by Tang910103** [comment]
> Hi @Tang910103, I just created a new module and run `flutter build ios-framework` and it worked as expected. Can you try doing same with the latest stable version of flutter? You can use a tool like fvm to manage your flutter versions
> 
> ```shell
> fs create -t module app_module
> Developer identity "Apple Development: XXXXXXXXX" selected
> for iOS code signing
> Creating project app_module...
> Resolving dependencies in `app_module`... (6.6s)
> Downloading packages...
> Got dependencies in `app_module`.
> Developer identity "Apple Development: XXXXXXXXX" selected
> for iOS code signing
> Developer identity "Apple Development: XXXXXXXXX" selected
> for iOS code signing
> Wrote 12 files.
> 
> All done!
> Your module code is in app_module/lib/main.dart.
> deanli@FE-9B-AF-FA-EE-10 projects % cd app_module
> deanli@FE-9B-AF-FA-EE-10 app_module % ls
> README.md		app_module_android.iml	pubspec.yaml
> analysis_options.yaml	lib			test
> app_module.iml		pubspec.lock
> deanli@FE-9B-AF-FA-EE-10 app_module % fs build ios-framework
> 
> Building frameworks for com.example.appModule in debug mode...
>  ├─Copying Flutter.xcframework...                                  142ms
>  ├─Building App.xcframework...                                     10.2s
>  └─Moving to build/ios/framework/Debug                               8ms
> Building frameworks for com.example.appModule in profile mode...
>  ├─Copying Flutter.xcframework...                                  112ms
> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184
> to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the
> --no-tree-shake-icons flag when building your app.
> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184
> to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the
> --no-tree-shake-icons flag when building your app.
>  ├─Building App.xcframework...                                     26.1s
>  └─Moving to build/ios/framework/Profile                             6ms
> Building frameworks for com.example.appModule in release mode...
>  ├─Copying Flutter.xcframework...                                  713ms
> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184
> to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the
> --no-tree-shake-icons flag when building your app.
> Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184
> to 1384 bytes (99.9% reduction). Tree-shaking can be disabled by providing the
> --no-tree-shake-icons flag when building your app.
>  ├─Building App.xcframework...                                     16.8s
>  └─Moving to build/ios/framework/Release                             6ms
> Frameworks written to /Users/deanli/projects/app_module/build/ios/framework.
> ```

I've tried it with flutter3.22.3 and it's done as expected. But our current project can only use version 2.8.1, please help me to see how I can modify version 2.8.1 successfully? Thank you very much!

**Comment by danagbemava-nc** [comment]
Hi @Tang910103, is there any reason you can't upgrade from 2.8.1? That version of flutter is over 2 years old at this point and we do not provide support for such old versions of flutter

**Comment by Tang910103** [comment]
> Hi @Tang910103, is there any reason you can't upgrade from 2.8.1? That version of flutter is over 2 years old at this point and we do not provide support for such old versions of flutter

Thank you, we are working on upgrading!
