### ISSUE TITLE
[url_launcher] 'UIApplication' does not conform to protocol 'Launcher' with Xcode16 Version 16.0 (16A242d)

### ISSUE THREAD

**Issue by virskor** [flutter/flutter#155342]
### Steps to reproduce

Swift Compiler Error (Xcode): Type 'UIApplication' does not conform to protocol 'Launcher'
/Users/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_ios-6.3.0/ios/url_launcher_ios/Sources/url_launcher_ios/Launcher.swift:21:0

### Actual results

url_launcher: ^6.3.0

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @virskor, please provide a complete minimal reproducible code sample along with steps to reproduce. I just tested the url_launcher example and it works as expected.  I am using the latest macOS and Xcode versions. 

Please also provide the output of `flutter doctor -v`. 

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
.
.
.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-16.0.0.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2
```

Thank you

**Comment by virskor** [comment]
```pubspec.yml
dependency_overrides:
  url_launcher_ios: ^6.3.1
```

any one have same issue using this methods can fix it

**Comment by LiveRock** [comment]
Having the same issue. Any workaround?

**Comment by stuartmorgan** [comment]
Since we're seeing a lot of comments on related issues and PRs: if you are experiencing this issue, please run:
`flutter pub upgrade` to update your transitive dependencies (including `url_launcher_ios` which is where this issue and its fix are).

**Comment by KazzyAPI** [comment]
For me i had to do a little extra. Hope this can help someone!

I did the following same as what [virskor](https://github.com/virskor) did:

> ```miniyaml
> dependency_overrides:
>   url_launcher_ios: ^6.3.1
> ```
> 
> any one have same issue using this methods can fix it

As well as doing in xcode:
Runner > Build Settings
And setting `Allow Non-modular includes in Framework Modules`  to true

**Comment by RothaSoeurn** [comment]
Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/gh/_k1gdfl14f38jt1nclg_x1jm0000gn/T/flutter_tools.g4jjWQ/flu
        tter_ios_build_temp_dircO6E2S/temporary_xcresult_bundle

    /Users/macbook/.pub-cache/hosted/pub.dev/url_launcher_ios-6.2.4/ios/Classe
    s/Launcher.swift:20:1: error: type 'UIApplication' does not conform to
    protocol 'Launcher'
    extension UIApplication: Launcher {}
    ^
    UIKit.UIApplication:24:15: note: candidate has non-matching type '(URL,
    [UIApplication.OpenExternalURLOptionsKey : Any], (@MainActor @Sendable
    (Bool) -> Void)?) -> Void'
        open func open(_ url: URL, options:
        [UIApplication.OpenExternalURLOptionsKey : Any] = [:],
        completionHandler completion: (@MainActor @Sendable (Bool) -> Void)? =
        nil)
                  ^
    /Users/macbook/.pub-cache/hosted/pub.dev/url_launcher_ios-6.2.4/ios/Classe
    s/Launcher.swift:20:1: note: add stubs for conformance
    extension UIApplication: Launcher {}
    ^
    /Users/macbook/.pub-cache/hosted/pub.dev/url_launcher_ios-6.2.4/ios/Classe
    s/Launcher.swift:20:1: error: type 'UIApplication' does not conform to
    protocol 'Launcher'
    extension UIApplication: Launcher {}
    ^
    UIKit.UIApplication:24:15: note: candidate has non-matching type '(URL,
    [UIApplication.OpenExternalURLOptionsKey : Any], (@MainActor @Sendable
    (Bool) -> Void)?) -> Void'
        open func open(_ url: URL, options:
        [UIApplication.OpenExternalURLOptionsKey : Any] = [:],
        completionHandler completion: (@MainActor @Sendable (Bool) -> Void)? =
        nil)
                  ^
    /Users/macbook/.pub-cache/hosted/pub.dev/url_launcher_ios-6.2.4/ios/Classe
    s/Launcher.swift:20:1: note: add stubs for conformance
    extension UIApplication: Launcher {}
    ^
    /Users/macbook/projects/tenh100-ecom/ios/Runner.xcodeproj: warning: The
    iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to
    11.0, but the range of supported deployment target versions is 12.0 to
    18.0.99. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Run Script' will be run during every build
    because the option to run the script phase "Based on dependency analysis"
    is unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build
    because the option to run the script phase "Based on dependency analysis"
    is unchecked. (in target 'Runner' from project 'Runner')

**Comment by stuartmorgan** [comment]
@RothaSoeurn The fix for this issue is was `url_launcher_ios` 6.3.1. You are using 6.2.4.

**Comment by stuartmorgan** [comment]
Locking to avoid comments being made here instead of on the issue this was closed as a duplicate of.
