### ISSUE TITLE
I can't use the Automatically manage signing in Xcode

### ISSUE THREAD

**Issue by erkinovalim** [flutter/flutter#155360]
### Steps to reproduce

When I check the Automatically manage signing in Xcode it gives an error telling me that I have no devices from which to generate a provisioning profile.

### Expected results

So I tried to add a provisioning profile for iOS App Development but then it asks me to add a device, which will be used for testing. I don't have an iOS device, and the documentations (both official and unofficial guides) don't even touch the provisioning profiles section. It seems like it automatically starts working when they check the box.

### Actual results

It asks me to add a device and iOS app development provisioning profile.

### Code sample

⠀

### Screenshots or Video

<img width="1120" alt="Screenshot 2024-09-18 at 19 12 15" src="https://github.com/user-attachments/assets/72aea5a6-f2c5-4b51-bc50-eb5442e71ed4">

### Flutter Doctor output

⠀

**Comment by alihassan143** [comment]
@erkinovalim 
its not a flutter issue you need an ios device to generate a provisional profile without that apple will not allow you to generate build 
if you want to test app just select profile to none that it will start working

**Comment by danagbemava-nc** [comment]
As noted above, this is not a flutter issue. Kindly see https://stackoverflow.com/questions/8774379/xcode-organizer-your-team-has-no-devices-for-which-to-generate-a-provisioning help. 

Closing from here as this is likely an issue with your developer account or Xcode. 

Thank you
