### ISSUE TITLE
Flutter Gallery says it's the "April 2017 Preview"

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#15533]
The "about box" in Flutter Gallery says it's the "April 2017 Preview". I'm pretty sure it's more recent than that!

Perhaps we need to make this more dynamic:
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/drawer.dart#L243

**Comment by xster** [comment]
What should this number be? The time when the user is looking at this? The when this instance of the gallery was built? The current beta version when the instance of the gallery was built? Etc etc.

**Comment by mit-mit** [comment]
The string should capture when the Gallery was built, not when the user is looking at it. The primary objective is to facilitate easily see how recent an installed Gallery app is.

How frequently do we typically push updates? I wonder if the current month-based scheme is fine-grained enough?

Maybe just use a version number, specifically the same version number as the Flutter SDK? So a gallery build from current master build today could say "Version 0.2.4"?

**Comment by zoechi** [comment]
Now it says `April 2018 Preview` but that also sounds outdated.
Perhaps waiting for #22722
#24863 might be related 

Somewhat related the release on the App Store #15618
