### ISSUE TITLE
setTraversalAfter and setTraversalBefore need to have API guard

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#15539]
setTraversalAfter and setTraversalBefore are only available in API level 22 and above. We need to guard them with an API guard.

Ideally, we would switch to using the Compat class so we don't have to worry about it anymore. Doing so is blocked on https://github.com/flutter/flutter/issues/11099.

/cc @gspencergoog

**Comment by Hixie** [comment]
FIXED
