### ISSUE TITLE
in a Flutter application where custom plugin A's native code needs to access a private framework (xxx.framework) from custom plugin B. Seeking solutions from others.

### ISSUE THREAD

**Issue by aberror** [flutter/flutter#155344]
In a Flutter application, the native code of custom plugin A needs to reference the private xxx.framework framework introduced in custom plugin B. Attempts to add dependencies in A's pubspec.yaml configuration or to add vendored_frameworks in a_xxx.podspec dependency library have both failed. Does anyone know how to solve this problem?

**Comment by aberror** [comment]
Lexical or Preprocessor Issue (Xcode): 'xxx/xxxSDK.h' file not found

**Comment by darshankawar** [comment]
@aberror 
Please raise this in support channels like StackOverflow. 
If you think there's a bug in the framework, please use new issue template, fill out requested details so that we can properly address the issue. 
Closing for now due to lack of sufficient detials.
