### ISSUE TITLE
Incorrect comment in polyline.dart: "marker" should be "polyline"

### ISSUE THREAD

**Issue by dhiaCodes** [flutter/flutter#155379]
### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

Android, iOS, Web, macOS, Linux, Windows

### Have you already upgraded your packages?

No

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. Open the `polyline.dart` file.
2. Locate the comment that reads /// True if the marker is visible.

### Expected results

The comment should accurately describe the visibility of the polyline.

### Actual results

The comment incorrectly describes the visibility of a marker.

### Code sample

<details open><summary>Code sample</summary>

```dart
No code sample!
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
No need!
```

</details>

**Comment by danagbemava-nc** [comment]
The comment can be found in https://github.com/flutter/packages/blob/d83d021f70d183ce713d1a3a11da1bbfdd3f1448/packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types/polyline.dart#L99
