### ISSUE TITLE
Chat page, bottom input box, on Android platform, the animation timing of the soft keyboard and the input box is inconsistent

### ISSUE THREAD

**Issue by bing127** [flutter/flutter#155304]
### Steps to reproduce

None

### Expected results

The animation timing should be consistent.

### Actual results

The animation timing is inconsistent, the input box is always slower than the soft keyboard.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

https://github.com/user-attachments/assets/991114de-4e5c-4525-bc26-bc1f5dd5d831

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@bing127 
You are most probably hitting https://github.com/flutter/flutter/issues/116836 so please follow-up in it for further updates.
Closing this as a duplicate.
