### ISSUE TITLE
xcode16  ios 18 Could not build module 'in_app_purchase_storekit'

### ISSUE THREAD

**Issue by JieHaoCai** [flutter/flutter#155357]
### Steps to reproduce

升级最新xcode

### Expected results

1

### Actual results

2

### Code sample

3

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @JieHaoCai, I just tested the in_app_purchase example app and it works as expected. I tried with `flutter run` & `flutter build ios`.  I tested on both a physical device and the iOS simulator. 

Please provide the output of `flutter doctor -v` along with the steps to reproduce the issue. 

Thank you
