### ISSUE TITLE
GoogleMap : newLatLngBounds() inside mapController.animateCamera() throws __NSArrayM doubleValue

### ISSUE THREAD

**Issue by trushal93** [flutter/flutter#155361]
vehicleDetailsMapController
?.animateCamera(CameraUpdate.newLatLngBounds(LatLngBounds(
southwest: const LatLng(21.23755166666667, 72.88526333333333),
northeast: const LatLng(21.251688333333334, 72.89319277777777),
), 100));

I'm experiencing the issue with Flutter on iOS, getting the error:

*** First throw call stack:
(0x18a2e908c 0x1875eb2e4 0x18a3ef7c8 0x18a286888 0x18a2861b0 0x10362986c 0x10362aa78 0x103630060 0x10362fad8 0x1093521e4 0x108dc1794 0x106154a30 0x10615671c 0x106166de8 0x1061669a4 0x18a2bbf64 0x18a2b9188 0x18a2b85b8 0x1d5d4e1c4 0x18ce0e5f0 0x18cebd10c 0x18d1e9e50 0x1025d4c4c 0x1025d4bc4 0x1025d4cc8 0x1afa8bd34)
libc++abi: terminating due to uncaught exception of type NSException

**Comment by danagbemava-nc** [comment]
Hi @trushal93, please provide the following information

- The version of `google_maps_flutter` & `google_maps_flutter_ios` you're using
- The full crash log
- The steps to reproduce the crash 
- A complete minimal reproducible code sample
- The device(s) you're seeing the crash on and the version of iOS they're using
- Your `flutter doctor -v` output

Thank you
