### ISSUE TITLE
CupertinoTextField stays in light mode colors when the device is in dark mode and using MaterialApp with no darkTheme provided

### ISSUE THREAD

**Issue by Trulsmatias** [flutter/flutter#155473]
### Steps to reproduce

1. Create an app using MaterialApp
2. Add a CupertinoTextField
3. Change device brightness to dark mode

### Expected results

CupertinoTextField is shown in its dark mode colors as when using CupertinoApp

### Actual results

CupertinoTextField does not change colors

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: CupertinoTextField(),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.2, on macOS 15.0 24A335 darwin-arm64, locale
    en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.2)
[✓] VS Code (version 1.86.2)
[✓] Connected device (5 available)            
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
I think you are reporting for background color, right? If so, I can reproduce this as well. 

<details open>
<summary>Demo screenshot actual result of issue ❗</summary>

![dark mode](https://github.com/user-attachments/assets/8146a053-bc88-4d00-b6fe-1fc4c7837f73)

</details>

This reminds me of https://github.com/flutter/flutter/issues/146864 which has a similar issue with text colors inside CupertinoTextField in dart mode. You can try one of the workarounds at https://github.com/flutter/flutter/issues/146864#issuecomment-2091882343 to see if it works for you, for eg:

<details>
<summary>Sample code (workaround)</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: const MyApp(),
        themeMode: ThemeMode.system,
        darkTheme: ThemeData(
          brightness: Brightness.dark,
          cupertinoOverrideTheme: const CupertinoThemeData(
            textTheme: CupertinoTextThemeData(
              textStyle: TextStyle(
                color: CupertinoColors.white,
              ),
            ),
          ),
        ),
      ),
    );

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: CupertinoTextField(autofocus: true,),
      ),
    );
  }
}

```
</details>

<details open>
<summary>Demo screenshots (workaround applied)</summary>

| light mode ✅ | dark mode ✅ |
| --------------- | --------------- |
<img width="400" src="https://github.com/user-attachments/assets/a2a5fc46-8690-4f4e-abc1-7bf0c57a6b1e"> | <img width="400" src="https://github.com/user-attachments/assets/f9f2b1fd-d9d0-424a-a9bb-87c1d0db554d">
</details>

**Comment by Trulsmatias** [comment]
Thank you, that workaround works for me. Although I didn't need to specify a textStyle, so this was enough:

```
cupertinoOverrideTheme: const CupertinoThemeData(
    textTheme: CupertinoTextThemeData(),
),
```

**Comment by huycozy** [comment]
>I was not setting the darkTheme property to a ThemeData widget on the MaterialApp widget. When doing so the background becomes the right color, but the text color is still black.

This is indeed https://github.com/flutter/flutter/issues/146864.

>CupertinoTextField stays in light mode colors when the device is in dark mode and using MaterialApp with no darkTheme provided

I will keep this as a separate issue from https://github.com/flutter/flutter/issues/146864 for team to decide later. I will update the title of this issue as well. Reproduced this on master channel `3.26.0-1.0.pre.183`.

**Comment by MitchellGoodwin** [comment]
Closing as a duplicate, as it's the same underlying theming problem.
