### ISSUE TITLE
[web] Proposal to allow custom viewId or tags when app.addView() in Embedded multi-view mode

### ISSUE THREAD

**Issue by 826327700** [flutter/flutter#155444]
### Use case

I am using addView to insert multiple Flutter views in an HTML page, but the view ids I get are sequential and uncontrollable. This makes it difficult for me to render the views as I expect based on their viewId. e.g.:
I have some flutter code:
```dart
void main() {
  runWidget(
    MultiViewApp(
      viewBuilder: (BuildContext context) {
        var viewId = View.of(context).viewId;
        if (viewId == 1) {
          return MaterialApp(
            key: const Key("view1"),
            title: "Application",
            debugShowCheckedModeBanner: false,
            home: HelloWorld(),
          );
        }else
        if (viewId == 2) {
          return MaterialApp(
            key: const Key("view2"),
            title: "Application",
            debugShowCheckedModeBanner: false,
            home: HelloWorld2(),
          );
        }else{
            print('viewId: $viewId');
            return MaterialApp(
                key: const Key("view2"),
                title: "Application",
                debugShowCheckedModeBanner: false,
                home: Scaffold(
                    body: Center(
                        child: Text("Hello World ${viewId}"),
                    ),
                ),
            );
        }
      },
    ),
  );
}
```
When I delay the addView call for a view in HTML, the viewid of multiple views become uncontrollable.

### Proposal

So. I hope to be able to customize the view's ID or tag.
like this:
```javascript
let viewId = app.addView({
  hostElement: document.querySelector('#some-element'),
 tag:'my-tag-1'
});
```
```dart
MultiViewApp(
      viewBuilder: (BuildContext context) {
        var viewId = View.of(context).viewId;
        var tag = View.of(context).tag;
}
)
```

**Comment by ditman** [comment]
@826327700 we have an `initialData` property that you could use to attach any custom information to any view, for example your custom `tag`. What do you think about this:

* https://docs.flutter.dev/platform-integration/web/embedding-flutter-web#initial-view-configuration

I have a small example here:

* Passing initialData in: https://github.com/ditman/flutter-experimental/blob/1ec9da7be0a173153f5e0e3716dc1e6a4458c27b/multi_counter/web/flutter_bootstrap.js#L36-L40
* Defining initialData in JS-interop Dart: https://github.com/ditman/flutter-experimental/blob/main/multi_counter/lib/src/initial_data.dart (slightly outdated but working sample, I'll push a new one today!)
* Using initialData in Dart: https://github.com/ditman/flutter-experimental/blob/1ec9da7be0a173153f5e0e3716dc1e6a4458c27b/multi_counter/lib/main.dart#L22
