### ISSUE TITLE
Add foreground push notifications to firebase_messaging example app

### ISSUE THREAD

**Issue by Herohtar** [flutter/flutter#15542]
The [firebase_messaging](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging) plugin's example app has the code set up with event handlers for foreground push notifications, but they don't actually work; you don't receive any notifications unless the app is closed/in the background. From reading the Firebase Messaging documentation, it seems there is extra configuration that has to be done to receive notifications and data in the foreground:

> Add the following to your app's manifest:
> 
> A service that extends FirebaseMessagingService. This is required if you want to do any message handling beyond receiving notifications on apps in the background. To receive notifications in foregrounded apps, to receive data payload, to send upstream messages, and so on, you must extend this service.

I'm not sure how to do that in Flutter, and it seems to have been left out of the example app.

**Comment by xanZ08** [comment]
Push notifications have two parts - one is title and message of the notification, and one is additional data.
Push notifications will only show up when the app is in background/closed - the purpose of it is to get the user back into the App. Now if you want to send some data along with push notifications, then that will go as Json payload(or key value pairs). When you test the app via Firebase, you will see a section below, where you add key value pairs, and that will show up as the message, which you can capture and make the app react to it with the app in the foreground. 
There will be a method called onMessage, with argument of Map<String, dynamic> msg, where String is the Key and dynamic is the content.

**Comment by zoechi** [comment]
You can use one of the local notification packages to show notifications when the app receives them directly https://pub.dartlang.org/packages?q=local_notifications

**Comment by AppleEducate** [comment]
@zoechiWhat would an example look like with local_notifications? on_message is called whether it is in the foreground or after it comes out of the background

**Comment by zoechi** [comment]
@AppleEducate I don't know. I just saw it mentioned by others that it worked for them.
Perhaps the message content is different depending on whether it's called from foreground or background.

**Comment by AppleEducate** [comment]
Maybe so, ill explore that further. I guess the ideal use case is not to do a local notification but show the message in the app somewhere instead.

**Comment by collinjackson** [comment]
Displaying the message in the app somewhere is a better approach. We could show a snackbar?

**Comment by nikolayDemirev** [comment]
Hello, I need to show push notifications when the app is in foreground too. I have tried with local_notifications plugin. On Android I was abe to implement both local and remote notifications, but on iOS it seems tha when you configure the local notifications plugin, the firebase_messaging stops working and the remote notifications are never received again. Even the generated tokens are invalidated.

**Comment by elricym** [comment]
Same here. I really concern about this issue because it forced me to do platform-specific works for notification and it's kinda error-prone. Since multiple notification plugins can't work together on iOS, I think it's really necessary to add a local notification feature to the firebase_messaging providing a possible solution for struggling developers like me. Notification is always a pain point for app development. Maybe it's better go deep for it.

**Comment by vnbrs** [comment]
> Hello, I need to show push notifications when the app is in foreground too. I have tried with local_notifications plugin. On Android I was abe to implement both local and remote notifications, but on iOS it seems that when you configure the local notifications plugin, the firebase_messaging stops working and the remote notifications are never received again. Even the generated tokens are invalidated.

You're right. I tried many `local_notification*` plugins for Flutter, they all make `firebase_messaging` to stop working on iOS. It seems that is because both plugins register themselves as the delegate to handle push notifications.

**Comment by AppleEducate** [comment]
Oh I see.. that makes sense. Only one can be a delegate at a time.

**Comment by kroikie** [comment]
@Herohtar

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/888. Any further collaboration will be done there.

**Comment by nashihu** [comment]
> Hello, I need to show push notifications when the app is in foreground too. I have tried with local_notifications plugin. On Android I was abe to implement both local and remote notifications, but on iOS it seems that when you configure the local notifications plugin, the firebase_messaging stops working and the remote notifications are never received again. Even the generated tokens are invalidated.

@nikolayDemirev  hello.. can you share which local_notifications plugin that works along with firebase_messaging in android? thank you  🙏

**Comment by nashihu** [comment]
> > Hello, I need to show push notifications when the app is in foreground too. I have tried with local_notifications plugin. On Android I was abe to implement both local and remote notifications, but on iOS it seems that when you configure the local notifications plugin, the firebase_messaging stops working and the remote notifications are never received again. Even the generated tokens are invalidated.
> 
> @nikolayDemirev hello.. can you share which local_notifications plugin that works along with firebase_messaging in android? thank you 🙏

nvm. on android solved using package`flutter_local_notifications`

**Comment by MobileAppDevs** [comment]
Add willPresent notification delegate method in Appdelegate

import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        //FirebaseApp.configure()
        if #available(iOS 10.0, *) {
            UNUserNotificationCenter.current().delegate = self
        }
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    // This method will be called when app received push notifications in foreground
    override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
    {
        completionHandler([.alert, .badge, .sound])
    }
}
