### ISSUE TITLE
`CupertinoSlidingSegmentedControl` doesn't fling

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#155410]
On both iOS 18 and older versions, if I fling from the selected to any direction, it keeps going, proportionally to the force I applied. Too much force, goes to the last. Not a lot, goes to the next. This is a nice detail from Apple that makes it super joyful.

https://github.com/user-attachments/assets/0207a487-638d-4167-a33e-667ff11afe01

**Comment by danagbemava-nc** [comment]
Hi @bernaferrari, I just tested the `CupertinoSlidingSegmentedControl` example on the latest stable version and it appears that this feature has already been implemented. Kindly see the recording below. What version of flutter are you seeing this issue on?


https://github.com/user-attachments/assets/bec89448-a017-44a1-832e-dacbfb0f3171

**Comment by bernaferrari** [comment]
Oh, really?? My bad. Thanks!!

**Comment by yeisa231189** [comment]
Unsubscribe
