### ISSUE TITLE
[Go_router] From where i'm redirected ?

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#155498]
### Use case

In go_router, route can have a redirect method. Inside the method there is not way to read the previous url. 

I'm on a /appartements/details and i want to go to /admin/login. 
In the admin route i've a redirect method which check if i'm well login and well an admin. If i didn't comply with that i want to be redirect from where i come. 

Actually i can't do that because GoRouterState didn't contain the history of routes (as we can have on web for example). 

### Proposal

Maybe `redirect(BuildContext context, GoRouterState state)` should be :

 `redirect(BuildContext context, GoRouterState previous, GoRouterState current)` 
 or
  `redirec(BuildContext context, List<GoRouterState> stack)`

**Comment by danagbemava-nc** [comment]
Hi @EArminjon, I believe this is requesting the same feature as https://github.com/flutter/flutter/issues/141984. 

Kindly follow up in the original issue for updates. 

Closing in favor of the issue linked above. 

Thank you
