### ISSUE TITLE
`flutter doctor` should consider symlink

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#155474]
### Steps to reproduce

When using [puro](https://puro.dev/)([GitHub](https://github.com/pingbird/puro)) to manage `flutter` versions, I ran into an issue. 

It uses symlink so that if you have different environments (different names) that are all the same `Flutter`/`Dart` version, it symlinks them to the same version to make sure you only have one version installed on the machine to reduce used space.

If you add one Flutter environment from it to the path, and also one Dart SDK, here is the output when running `flutter doctor -v`:

```console
[!] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4169], locale pt-BR)
    • Flutter version 3.24.3 on channel stable at C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter
    ! Warning: `dart` on your path resolves to
      C:\Users\felip_0vh5fa6\.puro\shared\caches\fdf38910bad4a775c86b6c9a77b4856c3c26c8cd\dart-sdk\bin\dart.exe, which is
      not inside your current Flutter SDK checkout at C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter. Consider adding
      C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

### Everything else is fine, focus on the above

! Doctor found issues in 1 category.
```

### Expected results

Since that Flutter environment I called stable is actually symlinking to that `dart.exe` it should not show that warning.

**Comment by iapicca** [comment]
cc @pingbird

**Comment by pingbird** [comment]
The current check does consider symlinks of the flutter sdk itself, but not of the directory that the binary sits in (in your case, the `cache` dir is a symlink to `.puro\shared\caches\fdf38910bad4a775c86b6c9a77b4856c3c26c8cd`)

https://github.com/flutter/flutter/blob/ec28b057f24314a01e3fe14ddd6db1556d18c09d/packages/flutter_tools/lib/src/doctor.dart#L637

**Comment by FMorschel** [comment]
Yes that would be it. Thanks, missed it!
