### ISSUE TITLE
Flutter App Can't Be Scrolled While Mirroring With New MacOS 15 (Sequoia) Feature

### ISSUE THREAD

**Issue by adekmaulana** [flutter/flutter#155445]
### Steps to reproduce

1. Use New Mirroring Feature From MacOS 15 and iOS 18
2. Open Built App
3. Try Scrolling Vertical With Mouse or Trackpad

### Expected results

App can be scroll vertically

### Actual results

https://github.com/user-attachments/assets/6fc218fc-7771-4aa2-b914-ff02afd7a14a

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter is already up to date on channel stable
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (8 days ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
```
App on video built with flutter 3.24.0

</details>

**Comment by bazl-E** [comment]
I verified  this with Google Pay in India, flutter apps are not able to scroll

**Comment by danagbemava-nc** [comment]
This was initially reported in https://github.com/flutter/flutter/issues/153897 and has been fixed by https://github.com/flutter/engine/pull/55285. The fix is on the master channel. 

Closing since this has already been fixed. 

Thank you
