### ISSUE TITLE
Implement $XDG_STATE_HOME in xdg_directories

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#155494]
### Use case

There is a single base directory relative to which user-specific state data should be written. This directory is defined by the environment variable $XDG_STATE_HOME. 

### Proposal

Add a `stateHome` directory getter to the `xdg_directories` package.

**Comment by huycozy** [comment]
Adding source here: `XDG_STATE_HOME` is defined on https://wiki.archlinux.org/title/XDG_Base_Directory:

```
Where user-specific state files should be written (analogous to /var/lib).
Should default to $HOME/.local/state.
```

**Comment by stuartmorgan** [comment]
This is not something the Flutter team is likely to directly implement, as we don't currently have a use case for it in `path_provider`, but I'd be happy to review a PR adding it.
