### ISSUE TITLE
TextField obscured characters jump while typing on Android.

### ISSUE THREAD

**Issue by optdxf** [flutter/flutter#155469]
### Steps to reproduce

Creating a new issue since the old one (https://github.com/flutter/flutter/issues/147279) was closed with a solution that unfortunately doesn't work; that is, enabling or disabling the 'case' font feature does not make a difference.

Have a TextField with obscureText set to true, and type a variety of characters (e.g. alphanumeric and special characters).

### Expected results

The height of the characters should stay the same.

### Actual results

The height of the characters fluctuates. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: TextField(
          obscureText: true,
          style: GoogleFonts.inter(
            fontSize: 20,
            // trying with FontFeature.enable('case') or FontFeature.caseSensitiveForms() doesn't work either
            fontFeatures: const [FontFeature.disable('case')],
          ),
        ),
      ),
    ),
  ));
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/8ed95bd2-549d-4b3d-abcc-c296b828967a

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19045.4894], locale en-US)
    • Flutter version 3.24.1 on channel stable at C:\SDKs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (4 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
```

</details>

**Comment by iapicca** [comment]
> Creating a new issue since the old one (#155469) was closed with a solution that unfortunately doesn't work.

you are referencing your own issue as "the old one" 
you probably meant
- https://github.com/flutter/flutter/issues/155439

that was [closed as duplicate](https://github.com/flutter/flutter/issues/155439#issuecomment-2363375229)

>Closing this as duplicate of https://github.com/flutter/flutter/issues/147279
@optdxf Please check https://github.com/flutter/flutter/issues/147279#issuecomment-2076696472 solution mentioned in it.

the [comment](https://github.com/flutter/flutter/issues/147279#issuecomment-2076696472) suggest to amend the code as follow
<details>
  <summary>code</summary>
  
```diff
import 'package:flutter/material.dart';

void main() => runApp(
      const MaterialApp(
        home: Scaffold(
          body: Center(
            child: TextField(
              obscureText: true,
              style: TextStyle(
                fontSize: 20,
-                fontFeatures: const [FontFeature.disable('case')],
+                fontFeatures: [FontFeature.caseSensitiveForms()],
              ),
            ),
          ),
        ),
      ),
    );
```
</details>

<details>
  <summary>doctor</summary>

```console
flutter doctor -v
[✓] Flutter (Channel master, 3.26.0-1.0.pre.160, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.26.0-1.0.pre.160 on channel master at /Users/francesco/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 410968290f (2 days ago), 2024-09-19 01:33:20 -0400
    • Engine revision af3e63a638
    • Dart version 3.6.0 (build 3.6.0-266.0.dev)
    • DevTools version 2.40.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • SM A556B (mobile)               • RZCX318VHFK           • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```


</details>

<details>
  <summary>screen recording</summary>

![issue_155455](https://github.com/user-attachments/assets/9703edf0-95a3-4e6f-a3bd-0cbcd9339745)

</details>

I cannot reproduce the issue with the code suggested in the comment

**Comment by optdxf** [comment]
Hi @iapicca 

Can you try with the Inter font? I agree that the code snippet you provided does not reveal the issue, but switching to say the Inter font does:

```
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: TextField(
          obscureText: true,
          style: GoogleFonts.inter(
            fontSize: 20,
            fontFeatures: const [FontFeature.caseSensitiveForms()],
          ),
        ),
      ),
    ),
  ));
}

```

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate the reported behavior using latest versions. The jumping characters behavior occurs **if we switch to special characters keyboard layout and start inputting chars such as $ followed by other chars**, as shown in below video:

https://github.com/user-attachments/assets/0c0e216d-3de8-494b-8ba4-12896bb88389

The behavior doesn't occur on iOS. 

```
Stable : 3.24.3
Master : 3.26.0-1.0.pre.173
```

**Comment by LongCatIsLooong** [comment]
See https://rsms.me/inter/#features

You probably want to disable contextual alternates (and maybe some other font features). This unfortunately is entirely up to developers, the framework can't just disable these font features because it knows very little about the font and it's usually too hard of a decision to make for a generic text input widget.

**Comment by optdxf** [comment]
re: @LongCatIsLooong 

Thank you for the link -- learned something new today :). And yes, I agree with your rationale. In this case, as you suggested, disabling the `calt` font feature (`fontFeatures: const [FontFeature.disable('calt')],`) fixes the problem.
