### ISSUE TITLE
Keyboard is not working on TextFormField [flutter web chrome mac]

### ISSUE THREAD

**Issue by hs-dev1** [flutter/flutter#155409]
### Steps to reproduce

i just used the simple TextFormField in a class and on sometimes and some devices it occurs that user isnt able to type on the field.

### Expected results

the user should be able to type on all the time.

### Actual results

it doesnt show me anything on console either.

### Code sample

<details open><summary>Code sample</summary>

```dart
TextEditingController fullNameController = TextEditingController();

  FocusNode fullNameFocus = FocusNode();
 Widget fullNameField() {
    return TextFormField(
        controller: fullNameController,
        autovalidateMode: AutovalidateMode.onUserInteraction,
        focusNode: fullNameFocus,
        style: R.textStyles.poppins(
          color: R.colors.black,
          fs: AdaptiveTextSize.getAdaptiveTextSize(context, 15),
          fw: FontWeight.w300,
        ),
        validator: FieldValidator.validateFullName,
        inputFormatters: [LengthLimitingTextInputFormatter(25)],
        textInputAction: TextInputAction.next,
        keyboardType: TextInputType.name,
        decoration: R.decoration.fieldDecoration(
            hintText: "full_name",
            radius: 8,
            suffixIcon: Image.asset(
              R.images.userIcon2,
              scale: 4,
            )));
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@hs-dev1 
Are you able to replicate locally by running the given code in web platform running on macOS ?
Can you provide `flutter doctor -v` and macOS version is this occuring on ? 
Also please provide complete runnable code sample. The code you provided contains custom implementations.

**Comment by hs-dev1** [comment]
The issue occurs intermittently when interacting with text fields across different screens and browsers. Here's a detailed breakdown, and this occurs only on release-mode:

1. Initially, I opened the screen and typed into the fields without any issues.
2. After reloading the screen (tested on both Chrome and Safari), I typed into the first field and pressed the Tab button to move to the next field. At this point, I couldn't type into any field.
3. This issue also happens on the login screen—after typing in the email field, the typing functionality stops working when moving to the password field.
4. Occasionally, when the auto-suggestion dialog appears on a field, typing is disabled for all fields afterward.

**Testing details:**
- This issue occurs only on some devices. I've tested it on multiple devices running macOS and Windows, and it works fine on many of them. However, the issue persists on certain devices.

Here’s the code for the specific class where this issue occurs:

```dart
import 'dart:html' as html;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl_phone_number_input/intl_phone_number_input.dart';

class Create extends StatefulWidget {
  const Create({super.key});

  @override
  State<Create> createState() => _CreateState();
}

class _CreateState extends State<Create> {
  final _formKey = GlobalKey<FormState>();
  FocusNode fullNameFocus = FocusNode();
  FocusNode emailFocus = FocusNode();
  FocusNode phoneNumberFocus = FocusNode();
  TextEditingController fullNameController = TextEditingController();
  TextEditingController emailController = TextEditingController();
  TextEditingController phoneNumberController = TextEditingController();
  PhoneNumber number = PhoneNumber(isoCode: 'IN');

  InputDecoration fieldDecoration({
    bool? isSearch,
    Widget? preIcon,
    String? labelText,
    required String hintText,
    Widget? suffixIcon,
    double? radius,
    double? horizontalPadding,
    double? verticalPadding,
    double? iconMinWidth,
    double? suffixMaxHeight,
    double? suffixMinHeight,
    Color? fillColor,
    FocusNode? focusNode,
    bool? isLabelTranslated = true,
    TextStyle? hintTextStyle,
  }) {
    return InputDecoration(
      suffixIconConstraints: BoxConstraints(minWidth: iconMinWidth ?? 60, minHeight: suffixMinHeight ?? 50, maxHeight: suffixMaxHeight ?? 50),
      contentPadding: EdgeInsets.symmetric(horizontal: horizontalPadding ?? 16, vertical: verticalPadding ?? 14),
      fillColor: fillColor,
      hintText: hintText,
      prefixIcon: preIcon,
      suffixIcon: suffixIcon != null ? Container(child: suffixIcon) : null,
      counterText: "",
      isDense: true,
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: isSearch ?? false ? Colors.grey.shade100 : Colors.blueAccent.shade100),
      ),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: isSearch ?? false ? Colors.grey.shade100 : Colors.blueAccent.shade100),
      ),
      disabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: isSearch ?? false ? Colors.grey.shade100 : Colors.blueAccent.shade100),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: isSearch ?? false ? Colors.grey.shade100 : Colors.blueAccent.shade100),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: Colors.red),
      ),
      focusedErrorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: Colors.red),
      ),
      filled: true,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(key: _formKey, child: largeCreateView()),
    );
  }

  Widget largeCreateView() {
    return Column(
      children: [
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            InkWell(
                onTap: () {
                  html.window.history.back();
                },
                child: Icon(
                  Icons.arrow_back,
                )),
            Text("create"),
          ],
        ),
        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(20),
          ),
          padding: EdgeInsets.symmetric(horizontal: 12),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(child: fullNameField()),
                  SizedBox(width: 10),
                  Expanded(child: emailField()),
                ],
              ),
              SizedBox(height: 10),
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(child: phoneNumberField()),
                ],
              ),
              Align(
                alignment: Alignment.bottomRight,
                child: SizedBox(
                  width: MediaQuery.of(context).size.width / 6.5,
                  height: 60,
                  child: ElevatedButton(
                    child: Text("create"),
                    onPressed: () => createFn(),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget fullNameField() {
    return TextFormField(
        controller: fullNameController,
        autovalidateMode: AutovalidateMode.onUserInteraction,
        focusNode: fullNameFocus,
        inputFormatters: [LengthLimitingTextInputFormatter(25)],
        textInputAction: TextInputAction.next,
        keyboardType: TextInputType.name,
        decoration: fieldDecoration(hintText: "full_name", radius: 8));
  }

  Widget emailField() {
    return TextFormField(
        controller: emailController,
        autovalidateMode: AutovalidateMode.onUserInteraction,
        focusNode: emailFocus,
        textInputAction: TextInputAction.next,
        keyboardType: TextInputType.emailAddress,
        decoration: fieldDecoration(hintText: "your_email", radius: 8));
  }

  Widget phoneNumberField() {
    return InternationalPhoneNumberInput(
      formatInput: true,
      keyboardAction: TextInputAction.done,
      keyboardType: TextInputType.number,
      key: const Key('phone_number'),
      inputDecoration: fieldDecoration(
        hintText: "phone_number",
        radius: 8,
      ),
      onInputChanged: (PhoneNumber pNumber) {
        if (pNumber != null) {
          number = pNumber;
        }
      },
      onInputValidated: (bool value) {},
      textAlignVertical: TextAlignVertical.center,
      selectorConfig: const SelectorConfig(selectorType: PhoneInputSelectorType.BOTTOM_SHEET, showFlags: false, trailingSpace: false, setSelectorButtonAsPrefixIcon: true),
      ignoreBlank: false,
      autoValidateMode: AutovalidateMode.onUserInteraction,
      textFieldController: phoneNumberController,
      focusNode: phoneNumberFocus,
    );
  }

  Future<void> createFn({required}) async {
    if (_formKey.currentState!.validate()) {
      debugPrint("fine");
    }
  }
}```

**Flutter doctor output:**
```
 Flutter (Channel stable, 3.24.2, on macOS 12.6.6 21G646 darwin-x64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/muhammadhussnain/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (2 weeks ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2
Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/muhammadhussnain/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Users/muhammadhussnain/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.6 21G646 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.139

[✓] Network resources
    • All expected network resources are available.```

**macOS version:** 12.6.6 (21G646)

Let me know if you need further details!

**Comment by darshankawar** [comment]
> ```dart
> import 'package:intl_phone_number_input/intl_phone_number_input.dart';
> ```

This is a third party package. Please check if the reported behavior occurs without this implementation or not. If still yes, please provide us updated code sample.

**Comment by hs-dev1** [comment]
the issue occurs regardless of whether I’m using the `intl_phone_number_input` import. I want to clarify that during the login process, there are only the email and password fields present. This issue has also been observed in that screen view. Thank you for your assistance!

**Comment by darshankawar** [comment]
> * This issue occurs only on some devices

Can you provide details of these devices ? A short video of the behavior would also be helpful.

**Comment by hs-dev1** [comment]
Here’s the code for the specific class where this issue occurs:
```

import 'dart:html' as html;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class Create extends StatefulWidget {
  const Create({super.key});

  @override
  State<Create> createState() => _CreateState();
}

class _CreateState extends State<Create> {
  final _formKey = GlobalKey<FormState>();
  FocusNode fullNameFocus = FocusNode();
  FocusNode emailFocus = FocusNode();
  FocusNode phoneNumberFocus = FocusNode();
  TextEditingController fullNameController = TextEditingController();
  TextEditingController emailController = TextEditingController();
  TextEditingController phoneNumberController = TextEditingController();

  InputDecoration fieldDecoration({
    bool? isSearch,
    Widget? preIcon,
    String? labelText,
    required String hintText,
    Widget? suffixIcon,
    double? radius,
    double? horizontalPadding,
    double? verticalPadding,
    double? iconMinWidth,
    double? suffixMaxHeight,
    double? suffixMinHeight,
    Color? fillColor,
    FocusNode? focusNode,
    bool? isLabelTranslated = true,
    TextStyle? hintTextStyle,
  }) {
    return InputDecoration(
      suffixIconConstraints: BoxConstraints(minWidth: iconMinWidth ?? 60, minHeight: suffixMinHeight ?? 50, maxHeight: suffixMaxHeight ?? 50),
      contentPadding: EdgeInsets.symmetric(horizontal: horizontalPadding ?? 16, vertical: verticalPadding ?? 14),
      fillColor: fillColor,
      hintText: hintText,
      prefixIcon: preIcon,
      suffixIcon: suffixIcon != null ? Container(child: suffixIcon) : null,
      counterText: "",
      isDense: true,
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: isSearch ?? false ? Colors.grey.shade100 : Colors.blueAccent.shade100),
      ),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: isSearch ?? false ? Colors.grey.shade100 : Colors.blueAccent.shade100),
      ),
      disabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: isSearch ?? false ? Colors.grey.shade100 : Colors.blueAccent.shade100),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: isSearch ?? false ? Colors.grey.shade100 : Colors.blueAccent.shade100),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: Colors.red),
      ),
      focusedErrorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.all(Radius.circular(radius ?? 8)),
        borderSide: BorderSide(color: Colors.red),
      ),
      filled: true,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(key: _formKey, child: largeCreateView()),
    );
  }

  Widget largeCreateView() {
    return Column(
      children: [

        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(20),
          ),
          padding: EdgeInsets.symmetric(horizontal: 12),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(child: fullNameField()),
                  SizedBox(width: 10),
                  Expanded(child: emailField()),
                ],
              ),
              SizedBox(height: 10),
              
              Align(
                alignment: Alignment.bottomRight,
                child: SizedBox(
                  width: MediaQuery.of(context).size.width / 6.5,
                  height: 60,
                  child: ElevatedButton(
                    child: Text("create"),
                    onPressed: () => createFn(),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget fullNameField() {
    return TextFormField(
        controller: fullNameController,
        autovalidateMode: AutovalidateMode.onUserInteraction,
        focusNode: fullNameFocus,
        inputFormatters: [LengthLimitingTextInputFormatter(25)],
        textInputAction: TextInputAction.next,
        keyboardType: TextInputType.name,
        decoration: fieldDecoration(hintText: "full_name", radius: 8));
  }

  Widget emailField() {
    return TextFormField(
        controller: emailController,
        autovalidateMode: AutovalidateMode.onUserInteraction,
        focusNode: emailFocus,
        textInputAction: TextInputAction.next,
        keyboardType: TextInputType.emailAddress,
        decoration: fieldDecoration(hintText: "your_email", radius: 8));
  }



  Future<void> createFn({required}) async {
    if (_formKey.currentState!.validate()) {
      debugPrint("fine");
    }
  }
}`
```

**Flutter doctor output:**

Flutter (Channel stable, 3.24.2, on macOS 12.6.6 21G646 darwin-x64, locale en-US) • Flutter version 3.24.2 on channel stable at /Users/muhammadhussnain/Desktop/flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision [4cf269e](https://github.com/flutter/flutter/commit/4cf269e36de2573851eaef3c763994f8f9be494d) (2 weeks ago), 2024-09-03 14:30:00 -0700 • Engine revision a6bd3f1de1 • Dart version 3.5.2 • DevTools version 2.37.2 Android toolchain - develop for Android devices (Android SDK version 34.0.0) • Android SDK at /Users/muhammadhussnain/Library/Android/sdk • Platform android-34, build-tools 34.0.0 • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314) • All Android licenses accepted.
[✗] Xcode - develop for iOS and macOS ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development. Download at: https://developer.apple.com/xcode/ Or install Xcode via the App Store. Once installed, run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer sudo xcodebuild -runFirstLaunch ✗ CocoaPods not installed. CocoaPods is a package manager for iOS or macOS platform code. Without CocoaPods, plugins will not work on iOS or macOS. For more info, see https://flutter.dev/to/platform-plugins For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation
[✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2023.1) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
[✓] VS Code (version 1.85.2) • VS Code at /Users/muhammadhussnain/Downloads/Visual Studio Code.app/Contents • Flutter extension version 3.96.0
[✓] Connected device (2 available) • macOS (desktop) • macos • darwin-x64 • macOS 12.6.6 21G646 darwin-x64 • Chrome (web) • chrome • web-javascript • Google Chrome 128.0.6613.139
[✓] Network resources • All expected network resources are available.```

macOS version: 12.6.6 (21G646)
Let me know if you need further details!

**Comment by darshankawar** [comment]
I am unable to replicate it by running above code on latest master version using macOS machine. See below:


https://github.com/user-attachments/assets/5e765cb3-9cfc-48a4-9436-662f9f8248a6


```
fine
fine

```
