### ISSUE TITLE
[webview_flutter_web] [Navigation_Delegate] Add navigation delegate to webview web

### ISSUE THREAD

**Issue by arcas0803** [flutter/flutter#155448]
### Use case

When using webview_flutter_web we can load urls and that's it. It is possible to implement a basic navigation delegate just to know what url is loaded and the state of loading?

### Proposal

Just a basic implementation of navigation delegate to know the state of the iframe and url loaded.

**Comment by stuartmorgan** [comment]
What is your specific use case? Per previous discussion in https://github.com/flutter/flutter/issues/107877 general support for this is impossible.
