### ISSUE TITLE
The Flutter Gradle plugin's `configureLegacyPluginEachProjects` function problem

### ISSUE THREAD

**Issue by goosetapa** [flutter/flutter#155484]
https://github.com/flutter/flutter/blob/2f149da67614349cb60bc77b465ce6a533aa951e/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L689%EC%97%90%EC%84%9C

The Flutter Gradle plugin's `configureLegacyPluginEachProjects` Groovy code is detecting the text content of the existing settings.gradle file, regardless of whether it is in comments or the main body.

Even if I comment out the `'.flutter-plugins'` string in the settings.gradle file, the Flutter Gradle plugin still recognizes that it is using the legacy settings.gradle configuration method. 

As a result, during `flutter build apk` or `flutter run` command, it outputs error logs saying, "Plugin project :<plugin name> listed, but not found. Please fix your settings.gradle/settings.gradle.kts."

**Comment by reidbaker** [comment]
I think we just looked at the existence of the file and if both exist we use the legacy file. If I recall correctly this mirrors the behavior of other gradle plugins. 

Can you share why you want 2 different settings files so I can better understand the use case? 

@gmackall do you think we should read the contents of these files to determine which to pick? I am leaning against making that change.

**Comment by goosetapa** [comment]
> I think we just looked at the existence of the file and if both exist we use the legacy file. If I recall correctly this mirrors the behavior of other gradle plugins.
> 
> Can you share why you want 2 different settings files so I can better understand the use case?
> 
> @gmackall do you think we should read the contents of these files to determine which to pick? I am leaning against making that change.

Okay. I will show you 2 different settings files:  

The first one generates the error(or warning) logs during flutter build apk or flutter run command, but the last one doesn't.

The firlst settings.gradle file:
```groovy
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    println "flutterSdkPath: $flutterSdkPath"

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.4.0" apply false
    id "com.google.gms.google-services" version "4.3.15" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}

include ":app"
```

The second settings.gradle file:
```groovy
// include ':app'

// def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

// def plugins = new Properties()
// def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')   <--- This generates error logs even if it is commented text.
// if (pluginsFile.exists()) {
//     pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
// }

// plugins.each { name, path ->
//     def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
//     include ":$name"
//     project(":$name").projectDir = pluginDirectory
// }

pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    println "flutterSdkPath: $flutterSdkPath"

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.4.0" apply false
    id "com.google.gms.google-services" version "4.3.15" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}

include ":app"
```
