### ISSUE TITLE
[image_picker] The screen opened with pickImage freezes (ios18 & xcode16)

### ISSUE THREAD

**Issue by gulmensedat** [flutter/flutter#155402]
### Steps to reproduce

 ImagePicker imagePicker = ImagePicker();
 var xfile = await imagePicker.pickImage(source: ImageSource.gallery)

I tried it in other projects, there is no problem in ios17.5 emulators, but when I do pickImage in ios18 emulators, the native photo selection screen opens but it hangs, freezes and I cannot click anywhere. Of course, I can remove the app from the background. I cannot click anywhere in the application. No log appears in the debug console.

image_picker: ^1.1.2

flutter version 3.22.3 
I also upgraded to the latest version, the same problem occurs there. The reason I downgraded again was different errors.

### Expected results

none

### Actual results

none

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 15.0 24A335 darwin-arm64 (Rosetta), locale tr-TR)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (8 available)
    ! Error: Browsing on the local area network for iPhone’u. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources```

</details>

**Comment by danagbemava-nc** [comment]
Deduplicating this into https://github.com/flutter/flutter/issues/155401
