### ISSUE TITLE
[go_router] incorrect url when navigating to another ShellRoute

### ISSUE THREAD

**Issue by quaaantumdev** [flutter/flutter#155480]
### Steps to reproduce

1. use shell routes and try to navigate from ```/shell-one/page-one``` to ```/shell-two/page-two```
2. inspect the GoRouterState provided to ```page-one``` and ```page-two``` before/during/after the transition
3. the build function will run for ```page-one``` and ```page-two``` during the transation

### Expected results

correct GoRouteState for ```page-one``` and ```page-two``` respectively during each build run

### Actual results

currently, the ```page-one``` will be built during and even a short time after the transition, that seems fine as the widget transitions out (fade for me).

*BUT* the values ```page-one``` receives during this time are suddenly messed up. Specificially, it the _CustomNavigator currently uses latest matchList (which is for ```page-two``` already) while rendering ```page-one```. [_CustomNavigatorState._buildPageForGoRoute] then uses this matchList to create the state for ```page-one```.

The result is a ```GoRouterState``` with all values incorrect that rely on the RouteMatchList. So ```matchedLocation, pageKey, name, path``` are correct, while ```fullPath, pathParamters, extra, topRoute``` suddenly changed.

### Code sample

here is the fix: https://github.com/quaaantumdev/packages/commit/f88802ed8aba1be843d68976dc4c92f7e1f9ca79

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.4894], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.32)
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.93.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @quaaantumdev 
Can you share a minimal and complete sample code so that we can try to verify the issue first? Thanks!
