### ISSUE TITLE
Too many errors in VSCode but runs correctly sometimes

### ISSUE THREAD

**Issue by Chuan1937** [flutter/flutter#155486]
### Steps to reproduce

I installed and configured vscode using the official example。
- The code I use is the official example and can run normally, but the lower left corner of vscode is full of errors and warnings。

### Actual results

the app run correctly,but errors and warnings will CPU consumption。
![image](https://github.com/user-attachments/assets/6ce7d0ea-9cf7-424f-b649-ec7120880966)
![image](https://github.com/user-attachments/assets/ce5d0bd4-a3df-4737-9eea-4cda421bcdf1)

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[flutter] flutter doctor -v
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [版本 10.0.19045.2965], locale zh-CN)
    • Flutter version 3.24.3 on channel stable at D:\CC++\FLUTTER\FLUTTER SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.11.2)
    • Visual Studio at D:\APP\Visual Studio\vs22
    • Visual Studio Professional 2022 version 17.11.35222.181
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.2965]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 128.0.2739.79

[!] Network resources
    X A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到

! Doctor found issues in 4 categories.
exit code 0

**Comment by huycozy** [comment]
Can you try moving the Flutter SDK folder out of `C++` (to a place where the path [doesn't contain special characters or spaces](https://docs.flutter.dev/get-started/install/windows/desktop#:~:text=The%20path%20contains%20special%20characters%20or%20spaces)) and try again (remember to also update the Flutter PATH environment variable if you follow [Download then install Flutter](https://docs.flutter.dev/get-started/install/windows/desktop#download-then-install-flutter) guideline.

**Comment by Chuan1937** [comment]
Of course, the flutter storage path is correct, and I have configured it completely according to the flutter guideline. Although the sample code can run normally, there are indeed many errors. At the same time, my vscode is normal and can write python and C++ without any problem.

The path is "D:\CC++\FLUTTER\APP_PRO\flutter_application_1"

**Comment by huycozy** [comment]
Can you try moving the Flutter SDK and project folders out of `C++` folder to see if the issue persists? 

Also, I don't see VS Code showing up in your flutter doctor output. Which VS Code version and Flutter extension you are using?
