### ISSUE TITLE
Error (Xcode): 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by fahadx4** [flutter/flutter#155477]
### Steps to reproduce

flutter build ios

### Actual results

```
Failed to build iOS app
Error (Xcode): 'Flutter/Flutter.h' file not found
/app/ios/Runner/GeneratedPluginRegistrant.h:9:8


Error (Xcode): failed to emit precompiled header
/Developer/Xcode/DerivedData/Runner-ekriejbqioyjpfgyijwwluupkcog/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_2U2V4TMIXQ6FQ-clang_1II251I7UVJVL.pch' for bridging
header '/ios/Runner/Runner-Bridging-Header.h'
```

Encountered error while building for device.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
 flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale
    en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@fahadx4 
Looking at the error log, it seems to be probably similar to https://github.com/flutter/flutter/issues/78785 in which you can follow-up for further updates. Closing this as a duplicate.

If you don't think that is the case, please provide complete error log in properly formatted text and try to run the same command using new Flutter counter app project to check if you still get same error or not.
