### ISSUE TITLE
move `SharedPreferencesAsync` and `SharedPreferencesWithCache`  to a new file inside the lib folder

### ISSUE THREAD

**Issue by AbdeMohlbi** [flutter/flutter#155487]
### Use case

`Starting with version 2.3.0 there are three available APIs that can be used in this package. [SharedPreferences] is a legacy API that will be deprecated in the future. We highly encourage any new users of the plugin to use the newer [SharedPreferencesAsync] or [SharedPreferencesWithCache] APIs instead.`

Currently to using  `SharedPreferences` or`SharedPreferencesAsync` or`SharedPreferencesWithCache` requires importing
```dart 
import 'package:shared_preferences/shared_preferences.dart';
```
it would make a lot of sense if the new APIs where imported from a new path for exemple : 
```dart 
import 'package:shared_preferences/shared_preferences_async.dart';
```

1. this could make the migration process  easy and less verbose ,because currently searching for all `import 'package:shared_preferences/shared_preferences.dart';` and then making sure each one does call `SharedPreferencesAsync/WithCache` not  `SharedPreferences` could be hard or could lead to errors 

### Proposal

Move the import from [this line](https://github.com/flutter/packages/blob/f54fe930753f6e44def213297bd8e794c846ad43/packages/shared_preferences/shared_preferences/lib/shared_preferences.dart#L6) to a new file inside the `lib/` . This will allow for more flexible usage of SharedPreferencesAsync and SharedPreferencesWithCache, while in the same time enabling the use of an independent import that separates them from the legacy SharedPreferences API.

**Comment by AbdeMohlbi** [comment]
I'd like to be assigned this if the team considers this a right change.

**Comment by stuartmorgan** [comment]
> it would make a lot of sense if the new APIs where imported from a new path

This would make using the preferred APIs harder, by requiring everyone to learn that they need to do a non-standard thing to get to them. Many users would use the standard import pattern, get auto-suggested only the legacy APIs, and be steered the wrong direction. Given that, this isn't structure we want to adopt for the package.

To separate them, we would want the opposite: a different import for the now-discouraged, legacy API. However, that would have been a breaking change, which could have been extremely disruptive for the ecosystem, so we opted not to do that.

> 1. this could make the migration process  easy and less verbose ,because currently searching for all `import 'package:shared_preferences/shared_preferences.dart';` and then making sure each one does call `SharedPreferencesAsync/WithCache` not  `SharedPreferences`

If someone has complex usage that they want to control/audit, the best option would probably be for them to make their own local file that imports `package:shared_preferences/shared_preferences.dart` and then re-exports desired APIs with `show`.
