### ISSUE TITLE
Arabic Text Rendering in text widget split into two lines

### ISSUE THREAD

**Issue by rahichesoft** [flutter/flutter#15544]
when a try to write arabic words In the Text Widget the word will split into to lines
exactly the last character will go to another line
![bug](https://user-images.githubusercontent.com/10324784/37437166-eea6bca6-27eb-11e8-9d9b-b9e64422e071.jpg)
![screenshot_1521071841](https://user-images.githubusercontent.com/10324784/37437169-f46e3934-27eb-11e8-82ea-5d642b8748a4.png)

 
 but when i add a space character the text will be shown properly  
Dart file:

[QuizPage.zip](https://github.com/flutter/flutter/files/1813532/QuizPage.zip)

**Comment by jason-simmons** [comment]
Try switching to the master branch of Flutter.

We are transitioning to a new implementation of the text rendering engine that will handle this better.  The new renderer is enabled on the master branch but is not yet available on the beta channel.

**Comment by rahichesoft** [comment]
thanks for the great work i will see
