### ISSUE TITLE
firebase_messaging event handlers in example app never trigger with --preview-dart-2

### ISSUE THREAD

**Issue by Herohtar** [flutter/flutter#15541]
## Problem

The [example app](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging/example) for the firebase_messaging plugin has event handlers for `onMessage`, `onLaunch`, and `onResume` that should print the received message to debug and also trigger an action within the app. However, none of these event handlers actually run when a notification is received.

I know messaging is working because I can receive notifications through the app from Firebase Console and tap them and they'll open the app, but nothing prints to debug and the associated action does not occur.

## Flutter Doctor

```
flutter doctor -v
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.1.5 at C:\Users\Caleb\Google Drive\Android\flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Caleb\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] Connected devices (1 available)
    • Pixel 2 XL • 709KPNY0046767 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by zoechi** [comment]
As far as I remember `onMessage` is only called for data messages, not for notifications 
and when the app is active.

**Comment by Herohtar** [comment]
Yes, `onMessage` only gets called when the app is in the foreground, but as far as I can tell the docs don't specify that it requires a data message. However, it also requires additional configuration to work, which is not set up in the example app.

The other two are supposed to be called when you tap a notification, and again there is no listed requirement of it being a data message, so I expect it to work. Though if it does require data messages then that would explain why they don't get called, since the data messaging is not enabled.

**Comment by Herohtar** [comment]
What am I supposed to see there? The only thing it says is that you have to set a custom key-value pair of `click_action: FLUTTER_NOTIFICATION_CLICK` in order for `onResume` or `onLaunch` to be called when the notification is tapped on Android. It's set, but still not calling anything when the notification is tapped.

**Comment by Herohtar** [comment]
I did some debugging to try and figure out what was going on, but I'm confused by what I'm seeing... I put a breakpoint inside the function that I'm assigning to `onMessage` in the `configure()` call, and also put one inside the `onMessage` case of the `FirebaseMessaging` `_handleMethod` function. The debugger will break at the correct line in `_handleMethod` as expected:

```
Future<Null> _handleMethod(MethodCall call) async {
  switch (call.method) {
    case "onToken":
      final String token = call.arguments;
      if (_token != token) {
        _token = token;
        _tokenStreamController.add(_token);
      }
      return null;
    case "onIosSettingsRegistered":
      _iosSettingsStreamController
          .add(new IosNotificationSettings._fromMap(call.arguments));
      return null;
    case "onMessage":
      return _onMessage(call.arguments); // <-- Breakpoint here, hit as expected
    case "onLaunch":
      return _onLaunch(call.arguments);
    case "onResume":
      return _onResume(call.arguments);
    default:
      throw new UnsupportedError("Unrecognized JSON message");
  }
}
```

I verified that `call.arguments` contains the key/value pairs that I'm setting in the message from the Firebase Console; however, when I continue, the breakpoint in my handler never happens, and the code there doesn't run. The debugger only shows the value of `_onMessage` as `_Closure` so I can't tell what is happening there.

**Comment by Herohtar** [comment]
Okay, so after a lot of dead ends, I had a random idea and tried running the project with just `flutter run`, as I had previously been running everything with `flutter run --preview-dart-2`... and everything works. So the problem is actually something with Dart 2.

**Comment by zoechi** [comment]
@Herohtar no exceptions in the log output?
`flutter clean` might be worth a try.

**Comment by Herohtar** [comment]
No exceptions at all. I've been stopping the app and doing `flutter clean` every time I made a change specifically to avoid any potential issues there.

In any case, this may have been fixed by https://github.com/flutter/plugins/pull/434, but I won't be able to check until this evening.

**Comment by naiveaiguy** [comment]
I can also confirm this - I'm having the same problem and it's gone when I add `--no-preview-dart-2` (Dart 2 seems to be the default for 0.2.4)

**Comment by zoechi** [comment]
Is this still an issue?
It is working in my project since quite a while.

**Comment by Herohtar** [comment]
Sorry, I forgot about testing this. I checked just now and it seems to be working with Flutter 0.5.1.

**Comment by zoechi** [comment]
@Herohtar glad to hear and thanks for the feedback!

**Comment by kroikie** [comment]
@Herohtar

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/889. Any further collaboration will be done there.
