### ISSUE TITLE
DevTools CPU profiler doesn't sample the thread use by `compute`

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#155416]
### Steps to reproduce

in my app, I have this code:
```
        _reallyExpensiveValue = compute(reallyExpensiveFunction, argument);
```
but when using DevTools CPU profiler, I see no sign of `reallyExpensiveFunction`
DevTools CPU profiler doesn't sample the thread use by `compute`

I'm on MacOS using VScode

### Expected results

I should see `reallyExpensiveFunction` in my report

### Actual results

I don't see it

### Code sample

<details open><summary>Code sample</summary>

```dart
 _reallyExpensiveValue = compute(reallyExpensiveFunction, argument);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.93.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by moffatman** [comment]
It will be in another isolate at the bottom of the screen. the profiler just does one isolate at a time, by default the main isolate. however the isolate is only alive for the duration of the compute(), it will be hard to switch to it and start profiling.

**Comment by stephane-archer** [comment]
The isolate run for something like 10 seconds on large images, how to select another isolate than the main one? I don't see any option on the screen to select witch isolate to sample

**Comment by moffatman** [comment]
<img width="647" alt="Screenshot 2024-09-19 at 7 14 58 PM" src="https://github.com/user-attachments/assets/8bf94b90-7c49-427b-b86a-098300a2e541">

**Comment by stephane-archer** [comment]
the profiler takes a long time to detect the isolate so I can select it, worst, when the isolate stops the recording stops without showing any data... and if I close the recording before the end of the isolate I can see the data briefly before the isolate stop, then the data disappear again... what a terrible experience... you can't profile temporary isolate with this tool...

**Comment by moffatman** [comment]
sure. we can keep this issue open to improve it.

**Comment by stephane-archer** [comment]
@moffatman I would love to see this improve. thank you for your guidance!

**Comment by stephane-archer** [comment]
@darshankawar can you link "the similar issue is open in devtools repo"?

**Comment by moffatman** [comment]
follow the link .... https://github.com/flutter/devtools/issues/3363

**Comment by darshankawar** [comment]
Closing as duplicate.
