### ISSUE TITLE
Failed to upload app to appstore: `Invalid Bundle Executable. The executable file 'Runner.app/Frameworks/Flutter.framework/ Flutter' contains incomplete bitcode` 

### ISSUE THREAD

**Issue by alib1989** [flutter/flutter#155497]
### Steps to reproduce

upload too app store in xcode 16 

### Expected results

upload the app without error

### Actual results

nvalid Bundle Executable. The executable file 'Runner.app/Frameworks/Flutter.framework/ Flutter' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu. 
<img width="788" alt="Screenshot 2024-09-21 at 7 21 51 PM" src="https://github.com/user-attachments/assets/634a1c56-ecdf-4a28-968f-bf277962ad76">

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by alib1989** [comment]
my pubspec.yaml

`name: project3
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.2
  responsive_sizer: ^3.0.5+1
  animation_page: ^0.0.1
  font_awesome_flutter: ^9.0.0
  group_radio_button: ^1.1.0
  intl: ^0.17.0
  percent_indicator: ^4.0.0
  easy_localization: ^3.0.0
  animate_icons:
  lottie: ^1.0.1
  shared_preferences: ^2.0.6
  adaptive_dialog: ^1.0.1
  flutter_sms: ^2.3.1
  qr_code_scanner: 
   git:
    url: https://github.com/X-SLAYER/qr_code_scanner.git
    ref: flutter-beta  
  permission_handler: ^10.3.0
  tween_image_widget: ^0.0.2
  cached_network_image: ^3.1.0
  dropdown_search: ^2.0.1
  flutter_beep: ^1.0.0
  need_resume: ^1.0.6
  get: ^4.3.8
  local_auth: ^1.1.7
  flutter_phoenix: ^1.0.0
  pattern_formatter: ^2.0.0
  package_info: ^2.0.2
  easy_mask: ^2.0.1
  flutter_rating_bar: ^4.0.0
  easy_image_viewer: ^1.0.3
  printing: ^5.9.2
  esc_pos_utils_plus: ^2.0.1+6
  image: ^3.2.0
  barcode_image: ^2.0.2
  qr: ^3.0.1
  notification_permissions: ^0.6.1
  onesignal_flutter: ^5.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Cr
       fonts:
         - asset: fonts/Cairo-Regular.ttf
 
     - family: Cb
       fonts:
          - asset: fonts/Cairo-Black.ttf
     - family: TjBo
       fonts:
          - asset: fonts/Tajawal Bold.ttf
     - family: TjRg
       fonts:
          - asset: fonts/Tajawal-Regular.ttf
     - family: Bein
       fonts:
          - asset: fonts/bein-normal.ttf





`

**Comment by iapicca** [comment]
does [this](https://stackoverflow.com/a/79003835/9836706) help?

**Comment by alib1989** [comment]
@iapicca  this is not helping 
the error still exists 
<img width="797" alt="Screenshot 2024-09-21 at 8 58 43 PM" src="https://github.com/user-attachments/assets/a3357c04-f6b0-4ed6-a595-1aad69f7601e">

the error shown
when i update the xcode to 16

**Comment by huycozy** [comment]
@alib1989 Does the project build and run normally in `release` mode? (`flutter run --release`)

Can you check if the issue also occur on a newly created Flutter project as well? Please provide the output of `flutter doctor -v`. Thanks!

**Comment by icreativateam** [comment]
@alib1989 Maybe you were able to find a solution to this problem.

**Comment by Lx91** [comment]
Did you solve it

**Comment by Lx91** [comment]
I also encountered this problem。

**Comment by Lx91** [comment]
> @alib1989 Does the project build and run normally in `release` mode? (`flutter run --release`)
> 
> Can you check if the issue also occur on a newly created Flutter project as well? Please provide the output of `flutter doctor -v`. Thanks! 
flutter version 3.0.5

**Comment by tnvietanh** [comment]
i has same issue in flutter 3.0.0 xcode 16

**Comment by pssanchezbfo** [comment]
i has same issue in flutter xcode 16

**Comment by huycozy** [comment]
@tnvietanh @pssanchezbfo Can you provide the output of `flutter run -v`? (_The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it_)

**Comment by tnvietanh** [comment]
> @tnvietanh @pssanchezbfo Can you provide the output of `flutter run -v`? (_The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it_)

[error.txt](https://github.com/user-attachments/files/17238877/error.txt)
this is part of the error. is it enough?

**Comment by huycozy** [comment]
@tnvietanh Do you also see the error reported originally here when distributing app (via XCode?) (`Invalid Bundle Executable` error) 

From the log you provided:

>[  +14 ms] XCResult parsing error: Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.\
           Usage: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]\
             See 'xcresulttool get object --help' for more information.\

This was another issue https://github.com/flutter/flutter/issues/152989 on XCode 16 that the actual error is not showing. https://github.com/flutter/flutter/issues/152989 has been fixed on Flutter beta/master channels so please try switching to one of these channels and retry to see if you can provide the actual error or not.

**Comment by Martian168** [comment]
**Workaround: Manually remove Bitcode of Flutter.framework from.xcarchive file.**

**Mistakes mentioned in the 'Runner. The app/Frameworks/Flutter. Framework/Flutter', is actually in .xcarchive files inside.**

1、In Xcode, open the "Organizer" Window (Window -> Organizer"). 
In the "Archives" TAB, you can see the file you just filed.

2、The right mouse button Show in the Finder, right click "Show package contents", into Products/Applications/Runner. The app. After see Runner. App, continue to right-click "show package contents", thus into the 'Runner. The app/Frameworks/Flutter. Framework' directory.

3、Open Flutter.framework in terminal, 
Run the following command to check whether the framework contains bitcode. If 0 is returned, the framework does not contain Bitcode:
`otool -l Flutter | grep __LLVM | wc -l`

If the detection result is not 0, proceed to remove Bitcode from Flutter.framework by executing the following command:
`xcrun bitcode_strip -r Flutter -o Flutter`

4、Then upload the.xcarchive package to the App Store and the error will no longer appear.
