### ISSUE TITLE
Unable to extend primarySwatch and fontFamily properties using copyWith

### ISSUE THREAD

**Issue by sqoopdata** [flutter/flutter#15546]
## Issue Overview

Using `copyWith` function, we can extend a parent theme with new values. While using the `copyWith` function in a `MaterialApp`, I noticed two properties `primarySwatch` and `fontFamily` are missing in the `copyWith` function. 

## Steps to Reproduce

Using the `copyWith` function attempt to set `fontFamily` or `primarySwatch`, and you will notice the properties are not available.

For example the below code won't work: 

`Theme.of(context).copyWith(fontFamily: 'OpenSans')`

**Comment by Herohtar** [comment]
I think it's because those aren't actual properties of `ThemeData`... if you look at the constructor, `primarySwatch` is only used to set the values of a few of the colors, and `fontFamily` is used to set the font on the text theme properties.

**Comment by nsreenath** [comment]
@sqoopdata found any solution ?

**Comment by anindyamanna** [comment]
Change your code to 
`Theme.of(context).copyWith(textTheme: Theme.of(context).textTheme.apply(fontFamily:'OpenSans'))`

**Comment by TahaTesser** [comment]
Hi @sqoopdata 
Please check out this [comment](https://github.com/flutter/flutter/issues/15546#issuecomment-423501252) above
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by Okladnoj** [comment]
I have no context, who came up with such disgusting methods for applying the theme?
