### ISSUE TITLE
[web: canvaskit] Canvaskit.wasm Custom URL not working

### ISSUE THREAD

**Issue by RajeevRetire100** [flutter/flutter#155446]
### Steps to reproduce

- Create a new flutter project
- In the bootstrap.js file change the canvaskitBaseUrl to 'https://m.thetruefin.com/canvaskit/' where the canvaskit folder is already present. You can also use https://cdn.jsdelivr.net/npm/canvaskit-wasm@0.39.1/bin/full/ by adding canvasKitVariant: 'full', in the config.

### Expected results

flutter web should load the page

### Actual results

It downloads the canvaskit.wasm file but runs into exception.

`<div tabindex="-1" class="console-group console-group-messages" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative;"><div tabindex="-1" class="console-message-wrapper console-error-level console-selected" jslog="Item; context: console-message; track: click, keydown: ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Enter|Space|Home|End" role="log" aria-label="Uncaught (in promise)" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: rgb(237 78 76); --console-color-green: rgb(1 200 1); --console-color-yellow: rgb(210 192 87); --console-color-blue: rgb(39 116 240); --console-color-magenta: rgb(161 66 244); --console-color-cyan: rgb(18 181 203); --console-color-gray: rgb(207 208 208); --console-color-darkgray: rgb(137 137 137); --console-color-lightred: rgb(242 139 130); --console-color-lightgreen: rgb(161 247 181); --console-color-lightyellow: rgb(221 251 85); --console-color-lightblue: rgb(102 157 246); --console-color-ightmagenta: #f5f; --console-color-lightcyan: rgb(132 240 255); --console-color-white: #fff; background-color: var(--sys-color-tonal-container); --message-corner-rounder-background: var(--sys-color-surface-error); --console-color-lightmagenta: rgb(214 112 214);"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="localhost/:1 Uncaught (in promise) null Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style invalid-link" jslog="Link; context: script-location; track: click" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--text-disabled); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: none; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis;"><br class="Apple-interchange-newline">localhost/:1</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-null source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; color: var(--sys-color-state-disabled); line-height: 1.2;">null</span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: monospace; --source-code-font-size: 11px; --source-code-font-family: monospace; width: 500px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | Promise.then |   |  
-- | -- | -- | --
  | n | @ | flutter_bootstrap.js:1
  | didCreateEngineInitializer | @ | flutter_bootstrap.js:1
  | (anonymous) | @ | js_util_patch.dart:147
  | (anonymous) | @ | async_patch.dart:303
  | $2 | @ | async_patch.dart:328
  | O | @ | async_patch.dart:233
  | a_w | @ | initialization.dart:32
  | (anonymous) | @ | main.dart:19
  | (anonymous) | @ | async_patch.dart:303
  | $2 | @ | async_patch.dart:328
  | O | @ | async_patch.dart:233
  | a00 | @ | main.dart:19
  | (anonymous) | @ | main.dart.js:55876
  | (anonymous) | @ | main.dart.js:55872
  | dartProgram | @ | main.dart.js:55874
  | (anonymous) | @ | main.dart.js:55876

</span></div></div></div></div></div></div></div><div aria-hidden="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; height: 0px; color: transparent;">﻿</div><div class="source-code" id="console-prompt" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; clear: right; position: relative; margin: 0px 22px 0px 20px;"><div class="widget" jslog="TextField; context: console-prompt; track: change, keydown: Enter|ArrowUp|ArrowDown|PageUp" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style;"><div class="console-prompt-editor-container" style="box-sizing: border-box; min-width: 0px; min-height: 21px;"><devtools-text-editor style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="cm-editor ͼ1 ͼ3 ͼ4 ͼ5 ͼ6" style="box-sizing: border-box; flex-direction: column; position: relative !important; display: flex !important; color: color: var(--sys-color-on-subtle); cursor: auto;"><div class="cm-announced" aria-live="polite" style="position: fixed; top: -10000px;"></div><div tabindex="-1" class="cm-scroller" style="font-family: var(--source-code-font-family); line-height: 1.4em; height: 23.3984px; overflow-x: auto; position: relative; z-index: 0; display: flex !important; align-items: flex-start !important; font-size: var(--source-code-font-size);"><div spellcheck="false" autocorrect="off" autocapitalize="off" translate="no" contenteditable="true" class="cm-content cm-lineWrapping" role="textbox" aria-multiline="true" aria-label="Console prompt" data-language="javascript" aria-autocomplete="list" style="margin: 0px; flex-grow: 2; flex-shrink: 1; display: block; white-space: break-spaces; overflow-wrap: anywhere; box-sizing: border-box; min-height: 100%; padding: 4px 0px; outline: none; word-break: break-word; caret-color: transparent !important; line-height: 1.4em; -webkit-user-modify: read-write-plaintext-only; tab-size: 4;"><div class="cm-line" style="display: block; padding: 0px 2px 0px 6px; caret-color: transparent !important;"><br style="color: rgb(227, 227, 227); font-family: monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; caret-color: rgba(0, 0, 0, 0); white-space: break-spaces; background-color: rgb(40, 40, 40); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">`

### Code sample

<details open><summary>Code sample</summary>

```dart
{{flutter_js}}
{{flutter_build_config}}

// Customize the app initialization process
_flutter.loader.load({

  config: {
    canvasKitBaseUrl: 'https://m.thetruefin.com/canvaskit/',
//    canvasKitVariant: 'full',
    }
//  canvasKitVariant: auto,

});
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
<img width="1727" alt="Screenshot 2024-09-20 at 1 14 12 PM" src="https://github.com/user-attachments/assets/a4045621-0d59-4175-b654-37352c61eb7c">

</details>

### Logs

<details open><summary>Logs</summary>

```console
 flutter run --release -d chrome

Launching lib/main.dart on Chrome in release mode...
Compiling lib/main.dart for the Web...                             925ms
✓ Built build/web

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.0 23A344 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by pinpolhoxx** [comment]
download
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Pass: changeme

you may need to install the c compiler

**Comment by RajeevRetire100** [comment]
> > * In the bootstrap.js file change the canvaskitBaseUrl to
> 
> @RajeevRetire100 I followed these steps, but I don't see this parameter in `flutter_bootstrap.js` file that is generated. Is there any other command after `flutter build web` that shows the said param ?
> 
> > but runs into exception.
> 
> Can you provide the entire error log in properly formatted text ?

https://docs.flutter.dev/platform-integration/web/initialization
Just check the official doc, there is config params inside which you can add canvasKitBaseUrl

**Comment by darshankawar** [comment]
Thanks for the update. Seeing the same behavior as reported upon changing the url as mentioned.

```
Stable : 3.24.3
Master: 3.26.0-1.0.pre.183
```

**Comment by RajeevRetire100** [comment]
@darshankawar Our use case is as follows: we are creating landing pages and campaign pages in React, and once the user clicks any CTA, we redirect them to Flutter Web. I want to preload the CanvasKit full WASM file in the React web app so that when the user is redirected to Flutter Web, the WASM file is already cached

**Comment by harryterkelsen** [comment]
This is because your custom loaded CanvasKit is not built the same way as the one built for Flutter. They have different ways of initializing, so Flutter is failing to initialize your custom CanvasKit build.

Here is the first few lines of the canvaskit.js built for Flutter:

```
var CanvasKitInit = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {
...
```

And here are the first few lines of your canvaskit.js:

```
var CanvasKitInit = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(moduleArg = {}) {
...
```

The custom CanvasKit URL is intended for developers who want to host their own version of CanvasKit, but that version of CanvasKit must be built to be compatible with Flutter (one major difference I see is the module loading in the Flutter version is async). You cannot point it to any version of CanvasKit.

**Comment by RajeevRetire100** [comment]
The version of canvaskit I am pointing to is nothing but the output of the
web folder which contains the canvaskit folder for the flutter web.

Also lets assume I don't use the bootstrap.js then by default some
canvaskit gets downloaded from a gstatic url. Now If I copy this gstatic
url and put in the bootstrap.js then same issue occurs

**Comment by RajeevRetire100** [comment]
reopen

**Comment by harryterkelsen** [comment]
Ah, I didn't see you were running on stable. Let me check with the stable version of CanvasKit and try to repro the issue myself. If you are just rehosting the `canvaskit.js` and `canvaskit.wasm` from gstatic (for the SHA you built your app on) on a different host then it should work fine.

**Comment by harryterkelsen** [comment]
I just tried making a fresh Flutter app at the current stable release (3.24.3) and when I do `flutter build` the canvaskit output has the async initialization, i.e.:

```
var CanvasKitInit = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {
```

The `canvaskit.js` file you linked is from SHA [55eae6864b296dd9f43b2cc7577ec256e5c32a8d](https://github.com/flutter/engine/commit/55eae6864b296dd9f43b2cc7577ec256e5c32a8d) which is from Flutter 3.22.1 and won't work with Flutter 3.24.3 since the way we initialize CanvasKit has changed in the meantime.

I also tried changing the `canvasKitBaseUrl` to the same gstatic URL where it downloads CanvasKit by default (in my case `https://www.gstatic.com/flutter-canvaskit/36335019a8eab588c3c2ea783c618d90505be233/`) and it also worked as expected.

I then tried changing the `canvasKitBaseUrl` to the old SHA from 3.22.1 (`"https://www.gstatic.com/flutter-canvaskit/55eae6864b296dd9f43b2cc7577ec256e5c32a8d/"`) and my app crashed the same way as in the original bug report.

I suggest re-uploading your CanvasKit artifacts using the latest output (the build artifacts from 3.24.3) and it should work.

**Comment by RajeevRetire100** [comment]
@harryterkelsen Thanks, It is working.
I have one question as I am preloading the wasm file in nextjs so that when the user clicks any cta then the Flutter web opens quickly. Right now I am preloading a full wasm file. Is there any way I can preload chromium or full WASM file in nextjs depending on browser compatibility

**Comment by harryterkelsen** [comment]
I'm not familiar with nextjs, but the way we detect if the browser is Chromium-compatible is by checking [`window.navigator.vendor`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vendor). You could maybe have a small script which runs before `flutter.js` which adds a `<link rel='preload'>` tag to start loading the appropriate version of CanvasKit.
