### ISSUE TITLE
Not able to use flavor options with `Flutter logs` command

### ISSUE THREAD

**Issue by dishankjindal1** [flutter/flutter#155533]
### Steps to reproduce

I have an app which has multiple flavors. But when i was running `Flutter logs` command, It is not running throwing error as below.

>The Xcode project defines schemes: dev, prd
>You must specify a --flavor option to select one of the available schemes.

But when i tried to pass `flutter logs --flavor dev`, it is throwing error as below

> Could not find an option named "flavor".

### Expected results

It should start logging.

### Actual results

It is throwing error and not running.

### Code sample

flutter logs --flavor dev

### Logs

<details open><summary>Logs</summary>

```console
Could not find an option named "flavor".
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.6.1 23G93 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.93.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!```

</details>

**Comment by darshankawar** [comment]
@dishankjindal1 
I am not sure if `flutter logs` command supports `flavor` flag yet. See the help section for `flutter logs` which doesn't contain `flavor` flag:

<img width="1400" alt="Screenshot 2024-09-23 at 5 26 23 PM" src="https://github.com/user-attachments/assets/cae94ee9-1232-4e02-a509-5fe79e3e9747">

unlike, `flutter run` which does support `flavor` as shown below:

<img width="1372" alt="Screenshot 2024-09-23 at 5 25 52 PM" src="https://github.com/user-attachments/assets/e9154ead-948b-45d5-9251-fb1c3f187eab">

So this seems to be a current limitation that you are facing.
