### ISSUE TITLE
[webview_flutter] Wrong webview size in designed for ipad

### ISSUE THREAD

**Issue by jin-motemote** [flutter/flutter#155536]
### Steps to reproduce

1. create flutter project 
2. run below code in designed for ipad

### Expected results

Width fit 100% Device Screen

### Actual results

Width doesn't fit 100% Device Screen

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: const Text('Plugin example app'),
          ),
          body: WebViewWidget(
            controller: WebViewController()..loadRequest(Uri.parse('https://flutter.dev')),
          ),
        ),
      );
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
<img width="528" alt="image" src="https://github.com/user-attachments/assets/588caa69-121f-4d6e-ba1d-1e893169cc06">

### Logs

<details open><summary>Logs</summary>

```console
  webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      sha256: "6869c8786d179f929144b4a1f86e09ac0eddfe475984951ea6c634774c16b522"
      url: "https://pub.dev"
    source: hosted
    version: "4.8.0"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      sha256: "6e64fcb1c19d92024da8f33503aaeeda35825d77142c01d0ea2aa32edc79fdc8"
      url: "https://pub.dev"
    source: hosted
    version: "3.16.7"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      sha256: d937581d6e558908d7ae3dc1989c4f87b786891ab47bb9df7de548a151779d8d
      url: "https://pub.dev"
    source: hosted
    version: "2.10.0"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      sha256: "7affdf9d680c015b11587181171d3cad8093e449db1f7d9f0f08f4f33d24f9a0"
      url: "https://pub.dev"
    source: hosted
    version: "3.13.1"
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.92.2)
[✓] Connected device (0 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
> 2\. code in designed for ipad

@jin-motemote Can you elaborate what does this mean `designed for ipad` ? Is this a physical ipad ?
I tried the code on ipad simulator which shows the webview properly as below:

<img width="553" alt="Screenshot 2024-09-23 at 5 54 21 PM" src="https://github.com/user-attachments/assets/1559181e-4e20-4e3a-ac5a-fc17e6a4ed1f">

**Comment by jin-motemote** [comment]
> > 2. code in designed for ipad
> 
> @jin-motemote Can you elaborate what does this mean `designed for ipad` ? Is this a physical ipad ? I tried the code on ipad simulator which shows the webview properly as below:
> 
> <img alt="Screenshot 2024-09-23 at 5 54 21 PM" width="553" src="https://private-user-images.githubusercontent.com/67046386/369871406-1559181e-4e20-4e3a-ac5a-fc17e6a4ed1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTQ5NDgsIm5iZiI6MTcyNzA5NDY0OCwicGF0aCI6Ii82NzA0NjM4Ni8zNjk4NzE0MDYtMTU1OTE4MWUtNGUyMC00ZTNhLWFjNWEtZmMxN2U2YTRlZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEyMzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDUxM2JmMDhiMjlmOTU4MWViNTI2Njc5NTgwYjVkY2I5OWI0OTkzMjA0YTM5MDEwYjg4MGJhMjk1Zjg1MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.beE6o7N4j06upxy08Jlq91RnY3RQYdeJHdkkdTB-aD8">




> > 2. code in designed for ipad
> 
> @jin-motemote Can you elaborate what does this mean `designed for ipad` ? Is this a physical ipad ? I tried the code on ipad simulator which shows the webview properly as below:
> 
> <img alt="Screenshot 2024-09-23 at 5 54 21 PM" width="553" src="https://private-user-images.githubusercontent.com/67046386/369871406-1559181e-4e20-4e3a-ac5a-fc17e6a4ed1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTU0MzYsIm5iZiI6MTcyNzA5NTEzNiwicGF0aCI6Ii82NzA0NjM4Ni8zNjk4NzE0MDYtMTU1OTE4MWUtNGUyMC00ZTNhLWFjNWEtZmMxN2U2YTRlZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEyMzg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZmQ0YmY0MzYwNzZjMWM5MjdkMThiODViNTU0MTEyMjZlMTBiNmEzOTA4ZTUxOGQ3ZDRjM2NjZWEyN2E5YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ini9n4OFVhrTMvDZWk6Av9NpQsgabTB0qJhP84j1Yxk">

sorry..!
it means app for Apple Silicon
https://developer.apple.com/kr/macos/iphone-and-ipad-apps/

**Comment by jin-motemote** [comment]
oh.. it works thank!
