### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by ThreeHands** [flutter/flutter#155531]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\Programs\Android\Workspace\flutter_vap\android\src\main\kotlin\com\transsion\flutter_vap\FlutterVapPlugin.kt'

```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:217:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:216:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:205:53)
#7      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:153:49)
#8      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart)
#9      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:147:30)
#10     _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:316:40)
#11     _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:324:53)
#12     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1077:11)
<asynchronous suspension>
#13     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:386:5)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1736:7)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

**Comment by lizhenZuo** [comment]
i have the same problem

**Comment by darshankawar** [comment]
@ThreeHands 
Can you provide `flutter doctor -v` ?
Do you get same crash consistently everytime you are trying to run `flutter run` ?

**Comment by ThreeHands** [comment]
PS D:\Programs\Android\Workspace\flutter_vap> flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [版本 10.0.19044.1415], locale zh-CN)
    ? Flutter version 3.22.1 on channel stable at D:\Programs\Android\Flutter\flutter
    ? Upstream repository https://github.com/flutter/flutter.git
    ? Framework revision a14f74ff3a (4 months ago), 2024-05-22 11:08:21 -0500
    ? Engine revision 55eae6864b
    ? Dart version 3.4.1
    ? DevTools version 2.34.3
    ? Pub download mirror https://pub.flutter-io.cn
    ? Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ? Android SDK at D:\Programs\Android\SDK
    ? Platform android-34, build-tools 34.0.0
    ? Java binary at: D:\Programs\Android\Android Studio\jbr\bin\java
    ? Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    ? All Android licenses accepted.

[√] Android Studio (version 2024.1)
    ? Android Studio at D:\Programs\Android\Android Studio
    ? Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ? Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    ? Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Connected device (4 available)
    ? TECNO AE11 (mobile) ? ASALE3741B000022 ? android-arm64  ? Android 14 (API 34)
    ? Windows (desktop)   ? windows          ? windows-x64    ? Microsoft Windows [版本 10.0.19044.1415]
    ? Chrome (web)        ? chrome           ? web-javascript ? Google Chrome 98.0.4758.102
    ? Edge (web)          ? edge             ? web-javascript ? Microsoft Edge 128.0.2739.54

[√] Network resources
    ? All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by ThreeHands** [comment]
Every time I execute "flutter run" it appears.

PS D:\Programs\Android\Workspace\flutter_vap> flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [版本 10.0.19044.1415], locale zh-CN)
    ? Flutter version 3.22.1 on channel stable at D:\Programs\Android\Flutter\flutter
    ? Upstream repository https://github.com/flutter/flutter.git
    ? Framework revision a14f74ff3a (4 months ago), 2024-05-22 11:08:21 -0500
    ? Engine revision 55eae6864b
    ? Dart version 3.4.1
    ? DevTools version 2.34.3
    ? Pub download mirror https://pub.flutter-io.cn
    ? Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ? Android SDK at D:\Programs\Android\SDK
    ? Platform android-34, build-tools 34.0.0
    ? Java binary at: D:\Programs\Android\Android Studio\jbr\bin\java
    ? Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    ? All Android licenses accepted.

[√] Android Studio (version 2024.1)
    ? Android Studio at D:\Programs\Android\Android Studio
    ? Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ? Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    ? Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] Connected device (4 available)
    ? TECNO AE11 (mobile) ? ASALE3741B000022 ? android-arm64  ? Android 14 (API 34)
    ? Windows (desktop)   ? windows          ? windows-x64    ? Microsoft Windows [版本 10.0.19044.1415]
    ? Chrome (web)        ? chrome           ? web-javascript ? Google Chrome 98.0.4758.102
    ? Edge (web)          ? edge             ? web-javascript ? Microsoft Edge 128.0.2739.54

[√] Network resources
    ? All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by ThreeHands** [comment]
> @ThreeHands 你能提供一下吗`flutter doctor -v`？ 每次尝试运行时，是否都会出现相同的崩溃`flutter run`？


This is my code. If I only keep the first line "package com.transsion.flutter_vap", there will be no crash.
`package com.transsion.flutter_vap

import androidx.annotation.NonNull

import io.flutter.embedding.engine.plugins.FlutterPlugin

class FlutterVapPlugin : FlutterPlugin {
    override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        flutterPluginBinding.registerViewFactory(
                "flutter_vap",
            NativeVapViewFactory(flutterPluginBinding.binaryMessenger))
    }

    override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {

    }
}`

> Every time I execute "flutter run" it appears.
> 
> PS D:\Programs\Android\Workspace\flutter_vap> flutter doctor -v Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source! [√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [版本 10.0.19044.1415], locale zh-CN) ? Flutter version 3.22.1 on channel stable at D:\Programs\Android\Flutter\flutter ? Upstream repository https://github.com/flutter/flutter.git ? Framework revision [a14f74f](https://github.com/flutter/flutter/commit/a14f74ff3a1cbd521163c5f03d68113d50af93d3) (4 months ago), 2024-05-22 11:08:21 -0500 ? Engine revision 55eae6864b ? Dart version 3.4.1 ? DevTools version 2.34.3 ? Pub download mirror https://pub.flutter-io.cn ? Flutter download mirror https://storage.flutter-io.cn
> 
> [√] Windows Version (Installed version of Windows is version 10 or higher) [√] Android toolchain - develop for Android devices (Android SDK version 34.0.0) ? Android SDK at D:\Programs\Android\SDK ? Platform android-34, build-tools 34.0.0 ? Java binary at: D:\Programs\Android\Android Studio\jbr\bin\java ? Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314) ? All Android licenses accepted.
> 
> [√] Android Studio (version 2024.1) ? Android Studio at D:\Programs\Android\Android Studio ? Flutter plugin can be installed from: https://plugins.jetbrains.com/plugin/9212-flutter ? Dart plugin can be installed from: https://plugins.jetbrains.com/plugin/6351-dart ? Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
> 
> [√] Connected device (4 available) ? TECNO AE11 (mobile) ? ASALE3741B000022 ? android-arm64 ? Android 14 (API 34) ? Windows (desktop) ? windows ? windows-x64 ? Microsoft Windows [版本 10.0.19044.1415] ? Chrome (web) ? chrome ? web-javascript ? Google Chrome 98.0.4758.102 ? Edge (web) ? edge ? web-javascript ? Microsoft Edge 128.0.2739.54
> 
> [√] Network resources ? All expected network resources are available.
> 
> ! Doctor found issues in 1 category.

This is my code. If I only keep the first line "package com.transsion.flutter_vap" and delete the rest of the code, there will be no crash.

`package com.transsion.flutter_vap

import androidx.annotation.NonNull

import io.flutter.embedding.engine.plugins.FlutterPlugin

class FlutterVapPlugin : FlutterPlugin {
    override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        flutterPluginBinding.registerViewFactory(
                "flutter_vap",
            NativeVapViewFactory(flutterPluginBinding.binaryMessenger))
    }

    override fun onDetachedFromEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {

    }
}`

**Comment by darshankawar** [comment]
The stacktrace is different from the original issue https://github.com/flutter/flutter/issues/65021, so I will keep this open for team's input whether this need to be tracked separately or can be clubbed with linked issue.

**Comment by ThreeHands** [comment]
I get it. Our company's encryption software intercepted the Kotlin code. Thanks!
@darshankawar
