### ISSUE TITLE
[Question] How to integrate flutter on exsiting app？

### ISSUE THREAD

**Issue by specneeo** [flutter/flutter#15556]
I hava an app which most pages written by native code. Now I want to integrate flutter, in order to write new pages.  I have read flutter doc, for example:
Android
```
public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
```
this activity run with ```main.dart``` automatically. 
But if I have ```mainA.dart``` and ```mainB.dart```, how to assign ```mainA.dart``` to ```AActivity```, assign ```mainB.dart``` to ```BActivity```. Or how to specify which dart file to load?

many thanks.

**Comment by zoechi** [comment]
I believe this is a dup of #14821

**Comment by xster** [comment]
Specifying an dart file entry point is not yet supported but in progress (@chinmaygarde can correct me if I'm wrong). Please append your request and follow progress on #14821.
