### ISSUE TITLE
[Impeller] Add an FML_CHECK to initial host buffer creation 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#155555]
https://github.com/flutter/engine/blob/main/impeller/core/host_buffer.cc#L31-L33

**Comment by gaaclarke** [comment]
I'll do this.  I'll also change the allocator signature to use StatusOr so we'll get a good assert message.

**Comment by gaaclarke** [comment]
I changed my mind about `StatusOr`.  It was a bit involved and since the return type is a pointer where null previously meant some sort of error I was a bit worried about confusing errors since you'd have to check `FML_CHECK(buffer.ok() && buffer.value())` everywhere.

**Comment by jonahwilliams** [comment]
fml::StatusOr is not really great for APIs that return pointers, because you end up with the Java Optional problem where you can have fml::Status(value), fml::Status(nullptr), fml::Status(nullptr, failure).
