### ISSUE TITLE
Q4 Impeller iOS configuration changes

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#155541]
By the October deadline discussed offline, the engine should work as follows on iOS:

- [x] On iOS hardware, the engine flag to disable Impeller will be ignored, and the parts of Skia that are no longer needed will not be included in the binary.
- [x] On iOS simulator, the engine flag to disable Impeller will be ignored, but when Metal API access is not available, the engine will fall back to Skia, which will still be included in the binary.

cc @jtmcdole @chinmaygarde @jonahwilliams

**Comment by chinmaygarde** [comment]
> the engine will fall back to Skia, which will still be included in the binary

Sorry, just re-read this bit. I thought the plan for such simulators for the null renderer. Or was that just for G3?

**Comment by zanderso** [comment]
> > the engine will fall back to Skia, which will still be included in the binary
> 
> Sorry, just re-read this bit. I thought the plan for such simulators for the null renderer. Or was that just for G3?

That is phase two of the operation. This issue is just covering phase one.

**Comment by chinmaygarde** [comment]
Patch is up https://github.com/flutter/engine/pull/55808

**Comment by zanderso** [comment]
This is done.
