### ISSUE TITLE
How to manage page stack in flutter/native hybrid App?

### ISSUE THREAD

**Issue by korbin-w** [flutter/flutter#15559]
Hello, I'm doing a project to migrate an existing app to Flutter, a page-by-page migration, so we need to mix Flutter with Native(Android/IOS). 
The biggest problem in the mixing process is how to manage the page stack.  

For example (N: Native, F: Flutter):
Page opening order: Page1(N) -> Page2(F) -> Page3(F) -> Page4(N) ->Page5(F)

Due to the normal usage of FlutterActivity is singleton, problems occur when returning along this stack. In order to solve this problem, we thought about some possible solutions as below. Which one is appropriate？ Wish your suggestion. 

Plan 1, the application records this stack data by itself, and when the page is rolled back,  try to modify the native stack. This method works on IOS, but since Android doesn't provide an interface to manage the system stack, it's hard to work on Android, and we can only lose the Page2(F) and Page3(F) stack frames.

![image](https://user-images.githubusercontent.com/454020/37460907-a2c02cf4-2887-11e8-86fb-4eeb8d925bdd.png)

Plan 2, Refactor the functions of FlutterActivity,  extract it into a singleton Fragment instance. Each Flutter page corresponds to a new Activity nested with this singleton Fragment.

![image](https://user-images.githubusercontent.com/454020/37460750-1fceea06-2887-11e8-8d87-d4009652f797.png)

Plan 3, Similar to option 2, extracts the FlutterNativeView in FlutterView as a singleton instance. Each Flutter page use a new FlutterActivity instance nested with this singleton FlutterNativeView instance.

![image](https://user-images.githubusercontent.com/454020/37460714-03d3ed88-2887-11e8-947e-d8c5fcb14e37.png)

Plan 4, Start a new FlutterActivity instance for each Flutter page. In this case, the system can easily manage the stack. However, starting multiple instances of Flutter may cause performance problems, and the startup speed of the page will be slower.

![image](https://user-images.githubusercontent.com/454020/37460758-2a3ecee8-2887-11e8-8bb6-e123c2b49ce0.png)

**Comment by sbbbbb** [comment]
this is a good idea。
but i dont know how to isolate  context （isolate） of each flutterActivity

**Comment by InMatrix** [comment]
@mravn-google: This is a specific use case related to #14821.

**Comment by xster** [comment]
The long-term solution is option 4. @chinmaygarde is working on steps to enable this and can probably refer you to the tracking bug (I couldn't find it). 

If you're trying to implement this right away, perhaps opt for a low-ish cost solution for now like option 2 which other users have successfully adopted. https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java is already somewhat interfaced out to fit ok with a Fragment API minus all the splash screen stuff.

**Comment by korbin-w** [comment]
Thanks @xster . If I use option 4, I will create many FlutterActivity instance.  Will the memory size be problem?  Or will there be any other problems you can suppose?

**Comment by korbin-w** [comment]
Thanks to your suggestions @xster @InMatrix , following these hints, we have solved this problem by a manner similar to plan 2, reusing a singleton FlutterView and embed it into different Activities. The result is proved to be well.
