### ISSUE TITLE
Incompatible version constraints on async

### ISSUE THREAD

**Issue by KeshavAdityaRP** [flutter/flutter#15554]
I am trying to get my flutter_gallery app to work 

When I run **pub get** or **pub upgrade** 

Resolving dependencies... (19.3s)
Incompatible version constraints on async:
- flutter_gallery depends on version 2.0.6
- pub itself depends on version >=1.8.0 <2.0.0

When I run **flutter analyze**

Running "flutter packages get" in flutter_gallery...
Package file has no versions that match 2.3.6 derived from:
- flutter_driver 0.0.0 depends on version 2.3.6
- flutter_gallery depends on version 2.3.7
pub get failed (1)

Can someone help me resolve these ?

**Comment by Raymond69** [comment]
I'm getting same issue ...

**Comment by jonahwilliams** [comment]
@KeshavAdityaRP , @Raymond69 do you get the same results from running `flutter update-packages` ?

**Comment by Raymond69** [comment]
@jonahwilliams Unfortunately yes ...

**Comment by zoechi** [comment]
What about `flutter update-packages --force-upgrade`
I believe this is supposed to update constraints in `pubspec.yaml`, not only load the latest version within these constraints.

**Comment by Raymond69** [comment]
Got the same issue ..

**Comment by zoechi** [comment]
What Flutter version are you using? (`flutter -v`)
Have you tried with latest `dev` channel, or only `beta` channel. I remember having issues with `async` as well recently but it's fixed for me.

**Comment by Raymond69** [comment]
Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (3 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

**Comment by zoechi** [comment]
I think you should try `dev` channel. `flutter channel dev` `flutter doctor` `flutter update-packages --force-upgrade`

**Comment by Hixie** [comment]
@KeshavAdityaRP Do you still see this on current builds? We were having some issues with old packages back in March.
