### ISSUE TITLE
Salt master is not responding on the network.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#155546]
### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

Hi Brandon,

Will you check Salt master server, Bot mac-4 unable to connect to Salt master obtain new certificate file.

flutter@flutter-devicelab-mac-4 ~ % ping salt-flutter.endpoints.fuchsia-infra.cloud.goog
PING salt-flutter.endpoints.fuchsia-infra.cloud.goog (34.67.250.43): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

ID: /etc/pki/flutter-devicelab-mac-4.mtv.corp.google.com.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.9-py3.7.egg/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.9-py3.7.egg/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3002.9-py3.7.egg/salt/states/x509.py", line 674, in certificate_managed
                  name, days_remaining, append_certs, **kwargs
                File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3002.9-py3.7.egg/salt/states/x509.py", line 504, in _certificate_is_valid
                  testrun=True, **cert_spec
                File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3002.9-py3.7.egg/salt/modules/x509.py", line 1452, in create_certificate
                  if not any(certs):
              TypeError: 'NoneType' object is not iterable
     Started: 09:19:11.269530
    Duration: 225.905 ms
     Changes: 

ID: /opt/luci/machine_tokend/run.sh
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-mac-4.mtv.corp.google.com.crt
     Started: 09:19:11.823871
    Duration: 0.007 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh >/dev/null 2>&1
    Function: cron.present
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-mac-4.mtv.corp.google.com.crt
     Started: 09:19:11.825214
    Duration: 0.005 ms
     Changes:

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by bdero** [comment]
ICMP traffic is blocked, so `ping` is not a valid way to test for connectivity.

**Comment by bdero** [comment]
mac-4 is connected to the salt master.
```
$ sudo salt 'flutter-devicelab-mac-4.mtv.corp.google.com' test.ping
flutter-devicelab-mac-4.mtv.corp.google.com:
    True
```

Today `state.apply` is succeeding on mac-4, so I think this is all set.
```
----------
          ID: /etc/pki/flutter-devicelab-mac-4.mtv.corp.google.com.crt
    Function: x509.certificate_managed
      Result: True
     Comment: Certificate /etc/pki/flutter-devicelab-mac-4.mtv.corp.google.com.crt is valid and up to date
     Started: 07:26:10.145095
    Duration: 1443.578 ms
     Changes:
```
