### ISSUE TITLE
Google Sigin issue

### ISSUE THREAD

**Issue by hoangminhhung-addx** [flutter/flutter#155505]
### Steps to reproduce

I got a issue with Google sign when use Google Provider. I am using Flutter 3.24.0 and google_sign_in: ^6.2.1. When I got this error message after look deeply inside the Google Signin Code. It related to com.google.android.gms.auth.GoogleAuthException: ERROR
![Screenshot 2024-09-22 at 21 30 28](https://github.com/user-attachments/assets/8d3b632d-3256-4587-a75d-a66973c653a7)

### Expected results

Should allow to login normaly

### Actual results

Getting error with com.google.android.gms.auth.GoogleAuthException: ERROR
![Screenshot 2024-09-22 at 21 31 40](https://github.com/user-attachments/assets/d778c794-868c-4e5a-896f-c8ed6dcba524)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by LPLabrys99** [comment]
I had this issue as well. This fix worked for me.
https://github.com/flutter/flutter/issues/155490#issuecomment-2365441075

**Comment by darshankawar** [comment]
@hoangminhhung-addx 
You are most probably hitting https://github.com/flutter/flutter/issues/155429, so please follow-up in it for further updates.
Check above comment for workaround.
Closing as duplicate.
