### ISSUE TITLE
flutter run --machine doesn't report exceptions

### ISSUE THREAD

**Issue by Waqar144** [flutter/flutter#155527]
### Steps to reproduce

I am writing a flutter development plugin for a text editor using the [flutter daemon](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md) to do hot reloads etc. However, when the flutter app is run using `flutter run --machine`, it doesn't report any exceptions that occurred on reload/restart.

### Expected results

Exceptions are reported just like they are reported when running `flutter run` (without --machine argument)

### Actual results

No exceptions reported

### Code sample

<details open><summary>Code sample</summary>

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on Manjaro Linux 6.6.47-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.22.3 on channel stable at /home/waqar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (10 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/waqar/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/waqar/Downloads/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.1 (https://github.com/llvm/llvm-project.git e19b7dc36bc047b9eb72078d034596be766da350)
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/waqar/Downloads/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Manjaro Linux 6.6.47-1-MANJARO

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@Waqar144 
Please provide us a runnable reproducible code sample that shows the reported behavior.

**Comment by Waqar144** [comment]
@darshankawar Did you read the issue? This issue is not about usage flutter as a framework. Its about developer tool that I am creating for a text editor that will be helpful for flutter development. The question is about that tool (which as I understand lives in this repository). If the issues for such things are managed elsewhere please let me know where to report.

If anything is unclear in the OP, please ask a direct question.

**Comment by darshankawar** [comment]
@Waqar144 
Please take a moment to read about [code of conduct](https://github.com/flutter/flutter/blob/main/CODE_OF_CONDUCT.md).

> I am writing a flutter development plugin for a text editor using the [flutter daemon](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md) to do hot reloads etc. However, when the flutter app is run using `flutter run --machine`, it doesn't report any exceptions that occurred on reload/restart.

By providing these details, we would want to know any specific code sample you are using to run it. If this is not relevant, provide us exact steps to replicate so that we can properly address the issue.

**Comment by Waqar144** [comment]
- Create a flutter project
- Run it using `flutter run`
- Add some code that triggers an exception for e.g:
```dart
Column(
    children: [
        ListView.builder(
            itemCount: 1000,
            itemBuilder: (context, index) => Text("Hello $index"),
        ),
    ],
)
```
- Hot reload by pressing `r` in the terminal
- Exception is reported

Now repeat the above steps but use `flutter run --machine` in the second step, no exception is reported.

Note: You can't reload by pressing `r` in the terminal when using machine mode, so that will need to be triggered by either writing a json command manually or with the help of some tool.

**Comment by darshankawar** [comment]
Thanks for the update. I believe you are hitting https://github.com/flutter/flutter/issues/92903 so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by Waqar144** [comment]
Yep thats it, thanks
