### ISSUE TITLE
TabBar ignores Theme's iconTheme.size

### ISSUE THREAD

**Issue by NoBrainer** [flutter/flutter#155518]
### Steps to reproduce

Open dartpad.dev with the latest version of Dart & Flutter. For me, that was:
- Dart 3.5.3
- Flutter 3.24.3

Paste my code sample from below.

### Expected results

The icon gets its size from the theme in the `TabBar` and in the `TabBarView`.

### Actual results

- For `TabBarView`, the icon gets its size from the theme, as expected.
- For `TabBar`, the icon ignores the theme. (Bad.)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        iconTheme: IconThemeData(size: 64),
      ),
      home: const Scaffold(
        body: DefaultTabController(
          length: 2,
          child: Column(
            children: [
              TabBar(
                tabs: [
                  // The icon theme is ignored for both:
                  Icon(Icons.backpack_outlined),
                  Tab(icon: Icon(Icons.map_outlined)),
                ],
              ),
              Expanded(
                child: TabBarView(
                  children: [
                    // The icon theme is respected for both:
                    Icon(Icons.backpack_outlined),
                    Icon(Icons.map_outlined),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19045.4894], locale en-US)
    • Flutter version 3.24.1 on channel stable at C:\Users\Vinnie\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (5 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Vinnie\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Dart plugin version 242.22855.32

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4894]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 128.0.6613.138
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 128.0.2739.42

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ramkishoreprajapat** [comment]
Can you share the screenshots?

**Comment by TahaTesser** [comment]
`TabBar` currently overrides the IconTheme size and color.

https://github.com/flutter/flutter/blob/4ca51a1de59772d6adc6f8fbcc627c79d975a564/packages/flutter/lib/src/material/tabs.dart#L313-L319

Since `IconThemeData` cannot be nullable when calling `IconTheme.of(context)` . Allowing inherited `IconTheme` isn't straight forward.

 I tried to find other classes running into similar situation when calling `IconTheme.of(context)` and found a [workaround](https://github.com/flutter/flutter/commit/586e1fce1b25f7115b5e6c813047e7c0fbd8a796#diff-f6f982b3097efaf0114b8eddfc96748422e90b0dea0e9bf054537d7eb1fb0459R1360) in `search_anchor.dart` in  by @nate-thegrate.

https://github.com/flutter/flutter/blob/4ca51a1de59772d6adc6f8fbcc627c79d975a564/packages/flutter/lib/src/material/search_anchor.dart#L1444-L1452

I'm not sure if this workaround is worth copying in other classes. 


cc: @QuncCccccc, as you worked on Icon related stuff.

**Comment by TahaTesser** [comment]
@QuncCccccc 
Could we make `IconThemeData` nullable when returned by `IconTheme.of(context)`  without breaking change?

**Comment by darshankawar** [comment]
Current behavior reported is as rendered below:

<img width="226" alt="Screenshot 2024-09-23 at 5 02 42 PM" src="https://github.com/user-attachments/assets/198cdac1-96ba-486c-b59e-dbd63ecc5e09">
<img width="227" alt="Screenshot 2024-09-23 at 5 02 50 PM" src="https://github.com/user-attachments/assets/893bf2f6-3742-4d25-abdf-b20db79c3f3f">

```
Stable : 3.24.3
Master: 3.26.0-1.0.pre.173
```

**Comment by QuncCccccc** [comment]
> @QuncCccccc Could we make `IconThemeData` nullable when returned by `IconTheme.of(context)` without breaking change?

Probably no. Changing it to be nullable doesn't follow the convention that `of` method always return non-null values, and it may cause a lot of breaking changes. Maybe we can create a `maybeOf()` method for `IconTheme` and it only return a `IconThemeData` getting by `context.dependOnInheritedWidgetOfExactType<IconTheme>()`. So in `TabBar`, we can call this method to get the ambient icon theme and icon size if there's any. WDYT:)?

**Comment by QuncCccccc** [comment]
> We cannot check for default colors inside `IconTheme.maybeOf` as it will require importing Material library inside `widgets/icon_theme.dart`, interesting problem.

Can we check it in `TabBar`?

**Comment by TahaTesser** [comment]
> > We cannot check for default colors inside `IconTheme.maybeOf` as it will require importing Material library inside `widgets/icon_theme.dart`, interesting problem.
> 
> 
> 
> Can we check it in `TabBar`?
> 
> 
> 
> 

Currently we're doing it in the same search anchor. I'm just wondering if there is a better way that can be applied in multiple classes.
