### ISSUE TITLE
How to run test files in SDK

### ISSUE THREAD

**Issue by MrQiaoJian** [flutter/flutter#155647]
I want to run test files in SDK. But reported some errors.
![image](https://github.com/user-attachments/assets/b3b71373-e86a-492c-8159-3eabc87be718)
 I want to know if it's related to the engine. Do I need to compile an engine to run unit tests？

**Comment by darshankawar** [comment]
@MrQiaoJian 
Please don't paste screenshot as it is not readable. Always paste error log in properly formatted text.

Go through https://docs.flutter.dev/cookbook/testing/unit/introduction to know in detail about running unit tests.

Closing for now.
