### ISSUE TITLE
Wasm app causes exceptional fatal crash in Chromium (Windows)

### ISSUE THREAD

**Issue by JaffaKetchup** [flutter/flutter#155695]
### Steps to reproduce

EDIT: [I can now reproduce on Edge 129.0.2792.52](https://github.com/flutter/flutter/issues/155695#issuecomment-2376306347) and the standard version of Chrome as well.

I believe that this may be an issue in Chrome or Chromium's implemementation of WebGL, as this issue is difficult to reproduce. I am using Chrome Dev 131.0.6724.0 (64-bit), ~~this is likely important~~, as some developers on lower versions of Chrome cannot reproduce. However, I'm filing the issue here, as I am not certain about this, and it's also not at all clear to me where would be a good place to file this issue otherwise (I have sent the crash report to Chrome). If this is an issue outside of Flutter's control, I'll be happy to report somewhere else.

The crash message is an unusual one and suggests a memory issue: STATUS_ACCESS_VIOLATION.

The app concerned is https://demo.fleaflet.dev/markers. I find it's quickest on this page, but it will happen on any page eventually. It is built from the source of the example app at https://github.com/fleaflet/flutter_map.

Open the page (in the specified version of Chrome, and confirm WASM is in use with the indicator in the side menu), and pan and interact with the map until the crash occurs. Sometimes, the app slows, produces one final frame, then just hangs without a definite crash. In this scenario, reloading the page after the crash also doesn't work (further suggesting an issue with Chrome). Othertimes, Chrome handles the crash immediately with an "Aw, Snap". Othertimes, it produces the more common "Page not responding. Wait/Exit?" dialog.

https://github.com/user-attachments/assets/970096a6-009f-4f5f-9642-91ea10ca8816

### Expected results

Not crash :D

### Actual results

As described.

### Code sample

It is built from the source of the example app at https://github.com/fleaflet/flutter_map.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.24.0-0.2.pre, on Microsoft Windows [Version 10.0.22635.4225], locale en-GB)
    • Flutter version 3.24.0-0.2.pre on channel beta at C:\Users\lukas\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7c6b7e9ca4 (8 weeks ago), 2024-07-30 14:26:44 +0700
    • Engine revision 6e4deceb38
    • Dart version 3.5.0 (build 3.5.0-323.2.beta)
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\lukas\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome Dev\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.10.35027.167
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code, 64-bit edition (version 1.93.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22635.4225]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.41

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
@JaffaKetchup 
I downloaded Chrome Dev and ran the plugin example using latest master version in mac machine, but didn't get the reported error.

In your case, when it crashes, does browser console show any logs ? If so, please share it.



> confirm WASM is in use with the indicator in the side menu

Where do you see this ? Can you elaborate ? Also, what's the command are you running to run in web ?

**Comment by JaffaKetchup** [comment]
Here's the indicator, at the top of the side drawer:
![image](https://github.com/user-attachments/assets/ed595e97-ee5d-4a40-a0b9-0d3633bcf63b)

I can now also confirm reproduction in Edge 129.0.2792.52 "(Official build) stable app, beta channel (64-bit)". This further suggests an issue with either Flutter or Chromium, and hopefully means that it's not something wrong with my Chrome profile (as some other unrelated issues on help forums were resolved by a total re-install).
![image](https://github.com/user-attachments/assets/0e0a085e-fbdf-471c-8b13-e788b7380bcf)

The command used to build is the standard `flutter build web --wasm`.

**Comment by JaffaKetchup** [comment]
When reproducing with Edge, I find https://demo.fleaflet.dev/polyline_perf_stress most consistently produces the issue. I am having a harder time in general reproducing today, but I can still get it semi-consistently, I just have to play around for longer.

Interestingly, the issue seems to be prevented completely when the DevTools are open (in Edge or Chrome) - but it isn't screen size related.

Here's me reproducing in Edge, and you can see that opening DevTools significantly slows performance, but also prevents the issue completely (even when it is open but invisible in a smaller window):

(I'll upload the video when I'm back on a better network).

I wonder whether it is crashing at higher frame rates because it can't keep up? I might be having more issues in general reproducing today because I'm using my laptop without a charger connected, which causes some throttling. Why does opening DevTools tank the performance so much?

**Comment by jpohhhh** [comment]
I have all of these same symptoms, to the letter, on the same versions. Except a different stack trace, and occassional error logs about a platform view I'll dig up.

Extremely hard to reproduce. Clearing all caches for the site doesn't help. Restarting browser doesn't help. But if you spend 10 minutes reloading and loading, you're guaranteed to get it. Flutter WASM only.

I only get an app stack trace via matching reproduction time to crash reports uploaded to Sentry. Here's one for Chrome on Android on Pixel Fold. It reproduces in every Chromium browser afaik, observed on Edge on Windows and Chrome stable on macOS ARM.

**Comment by darshankawar** [comment]
@JaffaKetchup 
I see that you are on beta version, maybe try the same on latest stable as well to check if you still get same behavior or not ?

@jpohhhh What flutter version are you seeing this on ?

**Comment by mraleph** [comment]
I would suspect this might be caused by https://issues.chromium.org/issues/368241691, should be fixed on stable Chrome channel in version 129.0.6668.70. Chrome Canary contains fix in  131.0.6729.0 or newer.

**Comment by jpohhhh** [comment]
@darshankawar Flutter stable for me

@mraleph nailed it, I believe:

- 129.0.6668.59: repros
- 129.0.6668.71: does not repro (latest stable version, triggered update manually via Help > About Google Chrome)
- 131.0.6742.0: this issue does not repro [1]

[1] there's another issue here where it "gets stuck" almost immediately after interaction w/ unreachable error in Skia WASM. I don't think that's related to the issue reported here, or that it's worth pursuing on Flutter's end, since it's Chrome Canary. Happy to file a separate issue/give more detail if needed. https://gist.github.com/jpohhhh/1fda7b7b2228691e6265c52b6780d477

**Comment by JaffaKetchup** [comment]
Closing as this isn't an issue with Flutter. I guess #155411 can also be closed?
