### ISSUE TITLE
Scroll-to-top feature on iOS is blocking touches

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#15569]
The scroll-to top-feature of Scaffold on iOS is blocking/consuming touches, even when there is no main scroll view attached to the Scaffold. This is an issue when creating a custom header for the Scaffold which may include custom widgets (like buttons etc).

The code that needs a small fix is in `scaffold.dart`.

Perhaps only add the GestureDetector if `_primaryScrollController.hasClients`.

```dart
    if (themeData.platform == TargetPlatform.iOS) {
      _addIfNonNull(
        children,
        new GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: _handleStatusBarTap,
          // iOS accessibility automatically adds scroll-to-top to the clock in the status bar
          excludeFromSemantics: true,
        ),
        _ScaffoldSlot.statusBar,
        removeLeftPadding: false,
        removeTopPadding: true,
        removeRightPadding: false,
        removeBottomPadding: true,
      );
    }
```

**Comment by xster** [comment]
@cbracken can likely provide more details

**Comment by vlidholt** [comment]
I've added a test case here: https://github.com/vlidholt/flutter_bugs

**Comment by vlidholt** [comment]
@rockingdice Quick fix is to comment out the code in material/scaffold.dart that adds the gesture detector at the top of the screen.

![screen shot 2018-11-14 at 3 34 53 pm](https://user-images.githubusercontent.com/1539812/48489260-ef880100-e822-11e8-87a7-4b24270482f6.png)

**Comment by rockingdice** [comment]
@vlidholt thank you, I fix it in your way and it's working now.

**Comment by rockingdice** [comment]
As a reminder, I still find these codes in the latest code (master channel). I don't know if this issue is fixed or not. I have to keep the codes commented.

**Comment by TahaTesser** [comment]
Hi @vlidholt 
Are you still experiencing this issue on latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
