### ISSUE TITLE
Support custom Avatar size in ListTile

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15561]
Now the size is 20 x 20 , and can not change

**Comment by escamoteur** [comment]
IMHO the Leading and Trailing icon properties of ListTile are really only for icons. If you need bigger images build your would ListTile by using a Row or Container Object

**Comment by Hixie** [comment]
cc @HansMuller @jonahwilliams

**Comment by HansMuller** [comment]
ListTile implements the layout defined here: https://material.io/design/components/lists.html#specs

The width of the leading widget is arbitrary however at least 40 pixels (width) are always allocated if a leading widget is specified, and 16 pixels are inserted in between that and the titles.

**Comment by adrianvintu** [comment]
I found out here that we can set the width of the LEADING
https://github.com/flutter/flutter/issues/28685#issuecomment-478130992

Why is it not possible to set the height?

**Comment by galki** [comment]
@adrianvintu in the [Material Design specs](https://material.io/components/lists/#specs) the height of the tile determines the height of its content.

**Comment by timsneath** [comment]
Closed as by design.
