### ISSUE TITLE
`Windows tool_integration_tests_2_7` builder frequently times out

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#155621]
Looking at the most recent 200 runs, there are quite a few timeouts in this builder: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_2_7?limit=200

The timeout appears to be 45 minutes, but I thought most of our CI tasks had a timeout of 60 minutes. Perhaps we should consider increasing the timeout to 60 minutes, or possibly breaking this group of tests into more shards

**Comment by christopherfujino** [comment]
This was resolved with increasing sharding: https://github.com/flutter/flutter/pull/155631
