### ISSUE TITLE
How do I know the quantity when purchasing?

### ISSUE THREAD

**Issue by jiayixu420** [flutter/flutter#155603]
Now I am using the in_app_purchase and in_app_purchase package in my app.

in_app_purchase: ^3.2.0
in_app_purchase_android: ^0.3.6+8

I want to purchase the multi instances in app.
But I can't find the method to get the quantity.
Please let me know how I can process this problem.
![image](https://github.com/user-attachments/assets/47825fec-1cf8-4e27-a682-b0a4945c43f9)

**Comment by huycozy** [comment]
This doesn't seem to be implemented on Android yet, please follow https://github.com/flutter/flutter/issues/88351 for updates. Closing this in favor of that issue.
