### ISSUE TITLE
Can we publish Flutter package to pub dev from two different branches at Github ?

### ISSUE THREAD

**Issue by wasim270** [flutter/flutter#155614]
### Use case

We are having latest flutter versions of '2.0.0' in pub.dev.  However our CX reported issue in our previous version '1.1.6'.  We cannot downgrade flutter version. We are trying to publish '1.1.7' version to pub dev. 

But the error saying that ' The latest published version is 2.0.0. Your version 1.1.7 is earlier than that.' 

We want to maintain both our '1.x' version and '2.x' version in upcoming builds. How should we achieve this ?

### Proposal

Can we  publish version 1.0.1 to pub.dev if version 2.0.0 is already published.

**Comment by darshankawar** [comment]
@wasim270 
I think your case is similar to https://github.com/dart-lang/pub/issues/2272 that you can follow-up in.
Closing from here. You may also raise this in support channels like StackOverflow or Flutter's reddit help page.

**Comment by wasim270** [comment]
My case is not similar to that.  Actually my case is, in my flutter package we are having latest version of '2.0.0'. My CX reported issue in our older version '1.1.6'. We need to provide patch version of '1.1.7' on pub dev. 

My doubt is if i publish '1.1.7' version to pub dev, will my latest version '2.0.0' will get deleted or override by this '1.1.7' version.  If so, how should i avoid '2.0.0' to get deleted. Kindly clarify this case @darshankawar

**Comment by darshankawar** [comment]
Maybe https://github.com/dart-lang/pub/issues/3563 is something you can check. And your request probably belongs to same repo and not in this repo.
