### ISSUE TITLE
Have to add flutterfire to the path

### ISSUE THREAD

**Issue by gracken00** [flutter/flutter#155688]
[Get to know Firebase for Flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter)

In the (unnumbered) title: 'Install the FlutterFire CLI', i performed the step 2 of running the following code:

`$ dart pub global activate flutterfire_cli`

I got the following result:

PS C:\Users\Usuario\flutter-codelabs\firebase-get-to-know-flutter\step_02> dart pub global activate flutterfire_cli
Package flutterfire_cli is currently active at version 1.0.0.
Downloading packages... . (2.9s)
The package flutterfire_cli is already activated at newest available version.    
To recompile executables, first run `dart pub global deactivate flutterfire_cli`.
**_Installed executable flutterfire.
Warning: Pub installs executables into C:\Users\Usuario\AppData\Local\Pub\Cache\bin, which is not on your path.
You can fix that by adding that directory to your system's "Path" environment variable.
A web search for "configure windows path" will show you how._**                           
Activated flutterfire_cli 1.0.0.    

The guide says: 'Once installed, the flutterfire command is globally available.'

But this is not true, as you can read from the bold-italisized text, flutterfire still needs to be added to the path.

In the next section, 'Configure your apps', running the command: 

`$ flutterfire configure`

Doesn't work for this reason, flutterfire is not added to the system path variable.

Anyway, just thought this would be a helpful correction, others might get stuck here.

Have a good one!

Galo

**Comment by darshankawar** [comment]
@gracken00 
I think this was already fixed as part of https://github.com/flutter/flutter/issues/137966 that you can check and confirm.
