### ISSUE TITLE
IconTreeShakerException: ConstFinder failure: Unhandled exception: Bad state: No canonical name found.

### ISSUE THREAD

**Issue by Mike278** [flutter/flutter#155624]
### Steps to reproduce

Our app build (`flutter build apk --release`/`flutter build ios --release`) started failing with this `IconTreeShakerException` error after making seemingly-benign code changes. 

We haven't upgraded Flutter since 3.22.2 back in June, and the code changes don't explicitly add or remove anything icon related.

We target Android and iOS, both of which fail with the same error both locally and in CI. 

### Expected results

Build succeeds with the the usual info log message of `Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 11504 bytes (99.3% reduction)`

### Actual results

Build fails with
```
Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
Bad state: No canonical name found.
#0      BinaryBuilder.readNonNullCanonicalNameReference (package:kernel/binary/ast_from_binary.dart:1073:7)
#1      BinaryBuilder._readExtensionMemberDescriptor (package:kernel/binary/ast_from_binary.dart:1603:32)
#2      BinaryBuilder._readExtensionMemberDescriptorList.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:1595:24)
#3      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#4      new List.generate (dart:core-patch/array_patch.dart:46:13)
#5      BinaryBuilder._readExtensionMemberDescriptorList (package:kernel/binary/ast_from_binary.dart:1594:16)
#6      BinaryBuilder.readExtension (package:kernel/binary/ast_from_binary.dart:1582:30)
#7      BinaryBuilder._readExtensionList.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:1311:34)
#8      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#9      new List.generate (dart:core-patch/array_patch.dart:46:13)
#10     BinaryBuilder._readExtensionList (package:kernel/binary/ast_from_binary.dart:1310:40)
#11     BinaryBuilder.readLibrary (package:kernel/binary/ast_from_binary.dart:1265:5)
#12     BinaryBuilder._readOneComponent (package:kernel/binary/ast_from_binary.dart:935:9)
#13     BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:710:34)
#14     Timeline.timeSync (dart:developer/timeline.dart:173:22)
#15     BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:695:21)
#16     loadComponentFromBytes (package:kernel/kernel.dart:33:28)
#17     loadComponentFromBinary (package:kernel/kernel.dart:28:10)
#18     ConstFinder.findInstances (package:kernel/const_finder.dart:207:12)
#19     main (file:///C:/b/s/w/ir/cache/builder/src/flutter/tools/const_finder/bin/main.dart:103:41)
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### Code sample

Unfortunately I've been unsuccessful at reproducing it in a new empty Flutter project, but in our code base it seems to be caused by unused code. 

This is roughly what our code looks like - `pushBarScreen` is unused in the body of `getSomeScreenController`, and we can work around this issue by commenting out the unused code.

```diff

SomeScreenController getSomeScreenController({
  required void Function(FooController) pushFooScreen, 
- required void Function(BarController) pushBarScreen, 
}) {
  // ...
  // pushFooScreen is used in this function body
  // ...
  // pushBarScreen is NOT used in this function body
  // ...
}

Future<void> pushFooScreen(FooController foo) {
  navigator.push(MaterialPageRoute(builder: (_) => Foo(foo)));
}
Future<void> pushBarScreen(BarController bar) {
  navigator.push(MaterialPageRoute(builder: (_) => Bar(bar)));
}

Future<void> pushSomeScreen() {
  final controller = getSomeScreenController(
    pushFooScreen: pushFooScreen,
-   pushBarScreen: pushBarScreen,
  );
  navigator.push(MaterialPageRoute(builder: (_) => SomeScreen(controller)));
}

```

Interestingly, replacing some types with `dynamic` also seems to successfully work around the issue:

```diff
 SomeScreenController getSomeScreenController({
   required void Function(FooController) pushFooScreen,
-  required void Function(BarController) pushBarScreen,
+  required void Function(dynamic) pushBarScreen,
 }) {
   // ...
   // use pushFooScreen
   // ...
   // do NOT use pushBarScreen
   // ...
 }

 Future<void> pushFooScreen(FooController foo) {
   navigator.push(MaterialPageRoute(builder: (_) => Foo(foo)));
 }
-Future<void> pushBarScreen(BarController bar) {
+Future<void> pushBarScreen(dynamic bar) {
-  navigator.push(MaterialPageRoute(builder: (_) => Bar(bar)));
+  navigator.push(MaterialPageRoute(builder: (_) => Bar(bar as BarController)));
 }

 Future<void> pushSomeScreen() {
   final controller = getSomeScreenController(
     pushFooScreen: pushFooScreen,
     pushBarScreen: pushBarScreen,
   );
   navigator.push(MaterialPageRoute(builder: (_) => SomeScreen(controller)));
 }
 ```

But whenever I try to replicate these conditions in a new project, I can't reproduce the issue.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.4169], locale en-CA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.0)
[√] Android Studio (version 2024.1)
[√] IntelliJ IDEA Ultimate Edition (version 2024.2)
[√] Connected device (3 available)
[√] Network resources
```

Note: Build machine is Ubuntu and it experiences the same problem.

</details>

**Comment by Mike278** [comment]
Searching for "Bad state: No canonical name found", the only 2 hits are from the last couple weeks, so this might be relatively new?

https://github.com/flutter/flutter/issues/154660
https://github.com/flutter/flutter/issues/67153#issuecomment-2352082319 (old issue, new comment)

**Comment by darshankawar** [comment]
I tried following https://github.com/flutter/flutter/issues/67153#issuecomment-2074718741 to replicate but wasn't able to see the reported failure.



> #154660

As mentioned in that issue, it looks a genuine error but asked OP to provide replication steps or pattern.



> [#67153 (comment)](https://github.com/flutter/flutter/issues/67153#issuecomment-2352082319) (old issue, new comment)

This is 4 year old issue so not sure if the root-cause is same as you are seeing on stable 3.22. I will keep the issue open for team's attention and to know whether this can be clubbed in above issue or should be kept separate.

**Comment by Mike278** [comment]
> > [#67153 (comment)](https://github.com/flutter/flutter/issues/67153#issuecomment-2352082319) (old issue, new comment)
> 
> 
> 
> This is 4 year old issue so not sure if the root-cause is same as you are seeing on stable 3.22.
> 
> 
> 
> 

Yeah the error message in the OP is slightly different, but the latest comment has the same error message as this issue. The commenter probably didn't notice this difference.

**Comment by andrewkolos** [comment]
@johnniwinther I wonder if this is a compiler frontend issue?

Also cc @christopherfujino, who knows most about the icon tree shaking feature, though he is out-of-action for about a week.

**Comment by johnniwinther** [comment]
@jensjoha Can you reproduce this issue? Given that we see the same stack trace in #67153, are we serializing the (perhaps tree-shaken) AST in an inconsistent state?

**Comment by a-siva** [comment]
@Mike278 without a clear reproduction test case this is going to be hard to debug

**Comment by drumkiller-peter** [comment]
`Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
Bad state: No canonical name found.
#0      BinaryBuilder.readNonNullCanonicalNameReference (package:kernel/binary/ast_from_binary.dart:1073:7)
#1      BinaryBuilder._readExtensionMemberDescriptor (package:kernel/binary/ast_from_binary.dart:1603:32)
#2      BinaryBuilder._readExtensionMemberDescriptorList.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:1595:24)
#3      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#4      new List.generate (dart:core-patch/array_patch.dart:46:13)
#5      BinaryBuilder._readExtensionMemberDescriptorList (package:kernel/binary/ast_from_binary.dart:1594:16)
#6      BinaryBuilder.readExtension (package:kernel/binary/ast_from_binary.dart:1582:30)
#7      BinaryBuilder._readExtensionList.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:1311:34)
#8      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#9      new List.generate (dart:core-patch/array_patch.dart:46:13)
#10     BinaryBuilder._readExtensionList (package:kernel/binary/ast_from_binary.dart:1310:40)
#11     BinaryBuilder.readLibrary (package:kernel/binary/ast_from_binary.dart:1265:5)
#12     BinaryBuilder._readOneComponent (package:kernel/binary/ast_from_binary.dart:935:9)
#13     BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:710:34)
#14     Timeline.timeSync (dart:developer/timeline.dart:173:22)
#15     BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:695:21)
#16     loadComponentFromBytes (package:kernel/kernel.dart:33:28)
#17     loadComponentFromBinary (package:kernel/kernel.dart:28:10)
#18     ConstFinder.findInstances (package:kernel/const_finder.dart:207:12)
#19     main (file:///Volumes/Work/s/w/ir/cache/builder/src/flutter/tools/const_finder/bin/main.dart:103:41)
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)


To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/peterbk/fvm/versions/3.24.2/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 47s
Running Gradle task 'assembleRelease'...                          107.6s
Gradle task assembleRelease failed with exit code 1`

**Comment by jensjoha** [comment]
This is smaller version of co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A24_t02:

```dart
extension type ET1(int id) {
  ET1.c1() : this(0);
  ET1.c2(this.id);
  factory ET1.f1() = ET1.c1;
  factory ET1.f2(int v) => ET1.c2(v);
}

void main() {
  print(ET1.f1);
  print(ET1.f2);
}
```

Here, when compiled with `out/ReleaseX64/dart pkg/vm/bin/gen_kernel.dart --platform  out/ReleaseX64/vm_platform_strong.dill --aot t.dart` this reproduces in that it writes a 0 in a similar situation (I added this check:
```
diff --git a/pkg/kernel/lib/binary/ast_to_binary.dart b/pkg/kernel/lib/binary/ast_to_binary.dart
index 46f9b6c0be1..ca45b5ff1cd 100644
--- a/pkg/kernel/lib/binary/ast_to_binary.dart
+++ b/pkg/kernel/lib/binary/ast_to_binary.dart
@@ -1049,10 +1049,13 @@ class BinaryPrinter implements Visitor<void>, BinarySink {
   }
 
   void writeNonNullCanonicalNameReference(Reference reference) {
+    var previousCanonicalName = reference.canonicalName;
     CanonicalName name = _ensureCanonicalName(reference);
     checkCanonicalName(name);
     assert(name.index >= 0);
-    if (name.index < 0) throw "About to write null non-null reference.";
+    if (name.index < 0) {
+      throw "About to write null non-null reference ($previousCanonicalName vs $name).";
+    }
     writeUInt30(name.index + 1);
   }
```
)

Where seemingly in `_TreeShakerPass1.defaultMember` it's concluded that because `ET1.f1` is not reachable (`shaker.isMemberBodyReachable`) it's not added to the list of kept members, so when it comes to `_TreeShakerPass2.visitExtensionTypeDeclaration ` isMemberUsed is false and isTearOffUsed: true --- making it keep the `ExtensionTypeMemberDescriptor` with a "link" to the otherwise removed member.

**Comment by alexmarkov** [comment]
Extension members are handled similarly in the tree shaker, so there is likely a similar problem with `ExtensionMemberDescriptor.memberReference`.

This tree-shaking dependency between lowered members and lowered tear-offs was added in https://github.com/dart-lang/sdk/commit/4c1a94c0d39033b0f4f0d74215b74237e9344967, when tear-off references were added to ExtensionTypeMemberDescriptor and ExtensionMemberDescriptor.

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/401382

**Comment by alexmarkov** [comment]
The fix was rolled into Flutter in https://github.com/flutter/flutter/commit/895f0e291af00c3d45df0d931900bbad3061b681.
