### ISSUE TITLE
Can we add Hijri month localization in arabic please ?

### ISSUE THREAD

**Issue by Amr1440** [flutter/flutter#155683]
### Use case

If the app localization is arabic the Gregorian date show month in arabic but if i choose Hijri it shows Hijri month in english

### Proposal

Can we add Hijri month localization in arabic

**Comment by darshankawar** [comment]
@Amr1440 
Are you referring to selecting month using ShowDatePicker ?
Can you provide an example of the use case you are facing currently ?

**Comment by iapicca** [comment]
@Amr1440 
does [this](https://pub.dev/packages/hijriyah_indonesia) help?
