### ISSUE TITLE
Failed to apply plugin 'dev.flutter.flutter-gradle-plugin', Could not get unknown property 'usesUnsupportedDependencyVersions' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by herisarwanto99** [flutter/flutter#155687]
### Steps to reproduce

- melos clean && melos bootstrap
- fvm flutter pub get                                                
- fvm flutter pub upgrade
- fvm flutter pub run build_runner clean
- fvm flutter pub run build_runner build --delete-conflicting-outputs
- running project

### Expected results

Success running

### Actual results

Failed to compile

### Logs

<details open><summary>Logs</summary>

```console
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/herisarwanto/AndroidStudioProjects/FREELANCE/99Group/NEW-Rumah123-Pro/rumah123-pro-apps/packages/app/android/app/build.gradle' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'dev.flutter.flutter-gradle-plugin']
> Failed to apply plugin 'dev.flutter.flutter-gradle-plugin'.
   > Could not get unknown property 'usesUnsupportedDependencyVersions' for project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Error: Gradle task assembleDevDebug failed with exit code 1

```

</details>

### Flutter Doctor output

`[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-ID)
    • Flutter version 3.24.0 on channel stable at /Users/herisarwanto/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (8 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/herisarwanto/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • SM A528B (mobile)               • RRCT2007KEX           • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 118.0.5993.117
    ! Error: Browsing on the local area network for iPhone 13 Pro Max. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
`

**Comment by mbahgojol** [comment]
@herisarwanto99 Hello have you try clean gradle? `./gradlew clean`

**Comment by darshankawar** [comment]
@herisarwanto99 
Check [this](https://github.com/flutter/flutter/issues/153668) issue with underlying comments and see if it helps to resolve your issue or not.

**Comment by herisarwanto99** [comment]
This issue has been resolved in my monorepo project by following these steps:

1. Delete Gradle cache
2. In the android directory, clean the project:
`./gradlew clean`
3. In the /app directory, delete the .dart_tool folder, then run:
`fvm flutter pub get
fvm flutter pub upgrade
fvm flutter pub run build_runner clean
fvm flutter pub run build_runner build --delete-conflicting-outputs
`
4. In the root project directory, run:
 `melos clean && melos bootstrap`
