### ISSUE TITLE
Form validation returned from server

### ISSUE THREAD

**Issue by marscj** [flutter/flutter#15574]
![simulator screen shot - iphone x - 2018-03-15 at 18 56 19](https://user-images.githubusercontent.com/17241896/37471211-a2b3b708-2882-11e8-9afa-5a033186720f.png)

Please add the following code in FormFieldState
Thank you
By the way, I don’t want another branch.

```dart
void setValidate(String error){
    setState((){
      _errorText = error;
    });
  }
```

**Comment by Hixie** [comment]
Can you elaborate? I don't really understand the request.

**Comment by zoechi** [comment]
Sounds like a dup of #9688 to me.
