### ISSUE TITLE
Make the text field cursor configurable

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#15571]
## Steps to Reproduce

Go to the Text Fields demo in the Flutter Gallery. Type some text. Compare the text cursor to any other iOS app. The cursor in Flutter is too short and too thin.

## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.2.0, on Mac OS X 10.13.2 17C88, locale en-US)
    • Flutter version 0.2.0 at /Users/vik/Projects/flutter
    • Framework revision f8ac23cd86 (10 days ago), 2018-03-05 23:27:57 +0100
    • Engine revision a00f8e8bc0
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio - old.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • Viktor’s iPhone • 0f78a8bf61e64931b13636987dc7597b86ba55a7 • ios • iOS 11.2.6

! Doctor found issues in 1 category.
```

**Comment by xster** [comment]
Can you show a screenshot? Tested on the gallery though both just draw the caret by painting a Rect (0.0, 2.0, 1.0, 17.0) with the same color (0xff90caf9) and looks the same to me.

cc @alardizabal who saw similar issues.

**Comment by vlidholt** [comment]
Update: Also checked the native text inputs on Android, while they look wildly different in different apps, no-one matches Flutter. I figured that Chrome probably has the most standard one, which looks pretty similar to the one on iOS. Different apps also use different colors, so being able to choose a color would be nice.

**Comment by xster** [comment]
Ah I see. When you said short, I thought it was just https://github.com/flutter/flutter/issues/16257 though there are indeed other issues. 

Yes, the width does look different from the OS one. My suggestion is to also add cursor width to EditableText, then style it with a Cupertino TextField https://github.com/flutter/flutter/issues/13695. The `cursorColor` is already configurable on the EditableText.

**Comment by xster** [comment]
Also cc @willlarche on whether a Material TextField should auto adapt text cursor color. It's currently `textSelectionColor` which is primarySwatch[200]

**Comment by willlarche** [comment]
Cursor color should always be either the active color or error color. See [MDC-iOS](https://github.com/material-components/material-components-ios/blob/dcb219525bd4d56843fcdf4dd38b37949fea1f27/components/TextFields/src/MDCTextInputControllerBase.m#L560).

These colors are themeable. The active color should be the primary or primaryVariant color. The error color is the error color. See [Color theme creation](https://material.io/design/color/the-color-system.html#color-theme-creation). If those values don't exist yet, consult with @HansMuller for short-term plan.

**Comment by vlidholt** [comment]
@xster thanks for reopening this. If you look a bit more carefully you will also see that the height of the cursor is different (it's not just the height of the text, but maybe the full line height?) and that the iOS cursor has rounded edges.

**Comment by xster** [comment]
Makes sense, we should keep the height and the rounded corners in mind when adapting.

**Comment by xster** [comment]
In terms of code, we should start at `EditableText` and add new fields `double cursorWidth` and `Radius cursorRadius`. Pipe that through _Editable to RenderEditable. 

Make sure the width is accounted for in `_caretPrototype` and the various places where layout is done. 

In `_paintCaret`, switch on whether Radius is null and either create the Rect like it is now or create an RRect instead with the provided Radius and call canvas.drawRRect instead.

**Comment by sandrasandeep** [comment]
I am also going to add a parameter in the EditableText constructor for cursorHeight. 

Also, as a note, it looks like the active color for the cursor is different from the regular "activeBlue" color. Also, the cursor color is not always the active color or the error color. For example, in the native Notes app, the cursor color is orange.

**Comment by zoechi** [comment]
Related PR at #18888

**Comment by xster** [comment]
@sandrasandeep this is done now right?

**Comment by droidery** [comment]
When I make a `TextField` there is no option for `cursorWidth`, `cursorColor`& `cursorRadius` but if you make a `EditableText` there are these options. Is this intentional?

**Comment by sandrasandeep** [comment]
yes, it is done @xster

**Comment by xster** [comment]
@droidery: we added these APIs in preparation for a CupertinoTextField (#13695). Did you wish these options to be added to the Material TextField? It's currently not in the Material spec.

**Comment by droidery** [comment]
@xter It would be helpful if it was in the Material `TextField`, as the Flutter cursor width is too small when comparing the Flutter `TextField` cursor with a native cursor. e.g. in the Gmail app the "to" field has a thicker cursor, while typing in the body field the cursor is thinner. In the Flutter equivalent the cursor is always thin.

**Comment by droidery** [comment]
@xster  It would be helpful if it was in the Material `TextField`, as the Flutter cursor width is too small when comparing the Flutter `TextField` cursor with a native cursor. e.g. in the Gmail app the "to" field has a thicker cursor, while typing in the body field the cursor is thinner. In the Flutter equivalent the cursor is always thin.

**Comment by xster** [comment]
cc @willlarche, @HansMuller.

I don't see the cursor adaptability in the specs. Should we make this modification in the Material TextField?

**Comment by willlarche** [comment]
I think we should expose those properties in Material, yes. 

Also, listening to @droidery it sounds like the default values for them should be tweaked as well. If the spec does not have enough information, let me know and we can inspect the raw designs.

**Comment by alanrussian** [comment]
This is blocking Mulligan. cc @johnfesa

**Comment by xster** [comment]
Sounds like @sandrasandeep is working on this (Material TextField) as of this morning.

**Comment by yohom** [comment]
So far I have only found cursorWidth, cursorRadius and cursorColor in EditableText. When will cursorHeight be added? @sandrasandeep

**Comment by panuavakul** [comment]
+1 to this. This is actually a pretty big problem when using other language like Japanese, which the character is larger than English letters with same font size so the cursor looks even smaller. An option for cursorHeight would be great.

**Comment by zoechi** [comment]
@panuavakul this issue is closed since a while.
If you're still seeing this please create a new issue with a properly filled out issue template.

**Comment by changfeifan** [comment]
> cursorHeight

I can not find cursorHeight at EditableText widget.Is it merge to master or dev branch?

**Comment by zoechi** [comment]
> I can not find cursorHeight at EditableText widget.Is it merge to master or dev branch?

probably both

**Comment by xster** [comment]
There is no cursorHeight API. The general incorrect cursor height problem on non-latin scripts will be fixed separately in #20183

**Comment by vishna** [comment]
@xster Here's what cursor height looks for [Sailec](https://www.myfonts.com/fonts/typedynamic/sailec/) font

on Android Native:
<img width="329" alt="screenshot 2019-02-19 at 22 05 36" src="https://user-images.githubusercontent.com/121164/53047602-0f1e6d80-3493-11e9-86db-8620a8f1a487.png">

on Android Flutter:
<img width="339" alt="screenshot 2019-02-19 at 22 07 57" src="https://user-images.githubusercontent.com/121164/53047608-13e32180-3493-11e9-8004-174b09fbc07d.png">

That cursorHeight API would be useful to have.

**Comment by xster** [comment]
If you're still facing cursor height issues, please open a new issue. Please also note that it's worth checking on master again since we've fixed some line height issues on master since #27612.
