### ISSUE TITLE
Hot reload performance degradation on Dart 2

### ISSUE THREAD

**Issue by swavkulinski** [flutter/flutter#15578]
I have created the test project to measure hot reload time.
https://github.com/swavkulinski/flutter-stress-test

There is a degradation in performance when running Dart 2.

When using project to create 250 packages with 80 nested widgets
Dart 1

> Reloaded 252 of 984 libraries in 3,219ms.

Dart 2
> Reloaded 252 of 733 libraries in 9,304ms.

## Steps to Reproduce

1) checkout repo above
2) cd generator
3) dart generator.dart 80 250  _(250 packages with 80 widgets each)_
4) cd ..
5) flutter run
6) press r for reload
7) notice :   Reloaded 252 of 984 libraries in **3,219ms**
8) Ctrl+C to stop flutter
9) flutter run --preview-dart-2
10) press r for reload
11) notice: Reloaded 252 of 733 libraries in **9,304ms**

## Logs

**> flutter run**

```
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...                                1.1s
Starting Xcode build...
 ├─Assembling Flutter resources...             6.3s
 └─Compiling, linking and signing...           1.7s
Xcode build done                                      9.1s
Syncing files to device iPhone X...                   3.0s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

Initializing hot reload...
Reloaded 252 of 984 libraries in 3,153ms.

Performing hot reload...
Reloaded 0 of 984 libraries in 774ms.
```

**> flutter run --preview-dart-2**
```
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...                                0.9s
Starting Xcode build...
 ├─Assembling Flutter resources...             6.5s
 └─Compiling, linking and signing...           1.9s
Xcode build done                                      9.5s
Syncing files to device iPhone X...                   4.8s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

Initializing hot reload...
Reloaded 0 of 733 libraries in 948ms.

Performing hot reload...
Reloaded 252 of 733 libraries in 9,304ms.
```

## Flutter Doctor
```
✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-GB)
    • Flutter version 0.1.5 at /Users/swavkulinski/Git/flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/swavkulinski/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/swavkulinski/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • iPhone X • DFE6D52B-54D5-438F-8259-7BD3B0E7678B • ios • iOS 11.2 (simulator)

• No issues found!
```

**Comment by mraleph** [comment]
How do subsequent smaller reloads fare? (e.g. if you just edit something small)

/cc @kmillikin

**Comment by swavkulinski** [comment]
I just pressed reload after initial start
0 diff hot reload on Dart 1 keeps 450-700 ms
0 diff hot reload on Dart 2 is around 700-1000 ms

Changing 1-2 packages won't change the result.
they keep steady results on subsequent hot reloads.

**Comment by a-siva** [comment]
I am trying to reproduce your numbers here is what I get
flutter run --no-preview-dart-2
Initializing hot reload...                                       
Reloaded 719 of 735 libraries in 17,164ms.
Performing hot reload...                                         
Reloaded 252 of 735 libraries in 13,977ms.
Performing hot reload...                                         
Reloaded 0 of 735 libraries in 1,232ms.

flutter run --preview-dart-2
Initializing hot reload...                                       
Reloaded 0 of 735 libraries in 1,671ms.
Performing hot reload...                                         
Reloaded 252 of 735 libraries in 14,973ms.
Performing hot reload...                                         
Reloaded 0 of 735 libraries in 1,410ms.
Performing hot reload...                                         
Reloaded 0 of 735 libraries in 1,398ms.

These numbers don't seem to match up with your numbers. I am running my numbers on a Moto G Android phone.

Maybe I should try this on an iOS device.

**Comment by swavkulinski** [comment]
I was deploying to iOS Simulator

**Comment by yathit** [comment]
Now hot reload is very slow and I am not even using now.

```
[✓] Flutter (Channel master, v0.3.6-pre.7, on Linux, locale en_US.UTF-8)
    • Flutter version 0.3.6-pre.7 at /home/k/flutter
    • Framework revision 8f03d27fa7 (30 hours ago), 2018-04-24 19:14:39 -0700
    • Engine revision 6a93ef1c70
    • Dart version 2.0.0-dev.49.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/k/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/k/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/k/opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /home/k/opt/ideaIU-2018.1/idea-IU-181.4203.550
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4203.498

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /home/k/opt/idea
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[!] VS Code (version 1.22.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
I get frequent timeouts and therefore hot reload doesn't work most of the time. I stick with hot restart which works fine.
```
Flutter 0.3.5 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 7ffcd3d22d (2 days ago) • 2018-04-24 14:03:41 -0700
Engine • revision ec611470b5
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b
```

The update to IntelliJ 2018.1.2 and Flutter plugin 23.2.3 didn't fix it.

**Comment by mraleph** [comment]
@zoechi can you file a separate bug? I think `listViews` timing out is something unrelated.

**Comment by ssarangi** [comment]
I see the same problem with hot reloads.  In my case I see an error from Dart VM..


Connected Path: satisfied (Path is satisfied), interface: en0
Duration: 60.807s, DNS @0.000s took 0.005s, TCP @0.006s took 0.005s, TLS took 0.069s
bytes in/out: 6748/2205, packets in/out: 13/13, rtt: 0.011s, retransmitted packets: 0, out-of-order packets: 0
**TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({})**

**Comment by bkonyi** [comment]
@a-siva is this issue worth keeping open? I haven't heard any talk recently about hot reload performance being quite as bad as mentioned in the original issue and all of our benchmarks are showing < 3000ms reload times currently.

**Comment by bkonyi** [comment]
Closing for now. If anyone still feels this is an issue, feel free to reopen and add more details.

**Comment by firatcetiner** [comment]
I'm facing this issue, not sure what is the problem. The reload times increases more when I added more and more layouts to the application, thus a compex application. I just saw 12 seconds while debugging on Pixel XL emulator with VS Code. It is not that bad when running on a real device but still, isn't that a huge time?

It is the same with Android Studio, I ugraded plugins etc. but result is the same.

Also when this happens the app freezing, I can't interact with the screen. It requires another hot reloat or hot restrart to work properly again. Annoying...

```
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.657], locale tr-TR)
    • Flutter version 1.12.13+hotfix.7 at C:\Users\asus\Documents\SDK\flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\asus\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.0)
    • VS Code at C:\Users\asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1


[√] Connected device (2 available)
    • MI 6                • 16185061      • android-arm64 • Android 9 (API 28)
    • AOSP on IA Emulator • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by mraleph** [comment]
@firatcetiner I suggest to file a separate bug and if possible provide a way to reproduce your issue. It is highly unlikely that you are facing the problem that this particular issue was about. I can be for example that your build methods are expensive (so rebuilding UI after reload takes a lot of time).
