### ISSUE TITLE
addJavaScriptChannel is not implemented on the current platform webview_flutter_web: ^0.2.3+2

### ISSUE THREAD

**Issue by marslannasrmuab** [flutter/flutter#155753]
### Steps to reproduce

```
class CaptchaWebPlatform extends StatefulWidget {
  final Function(String) callback;
  final String htmlContent;

  const CaptchaWebPlatform(
      {super.key, required this.callback, required this.htmlContent});

  @override
  State<CaptchaWebPlatform> createState() => _CaptchaWebPlatformState();
}

class _CaptchaWebPlatformState extends State<CaptchaWebPlatform> {
  late final PlatformWebViewController _controller = PlatformWebViewController(
      const PlatformWebViewControllerCreationParams(
      ));

  @override
  void initState() {
    super.initState();

    _controller.addJavaScriptChannel(
      JavaScriptChannelParams(
        name: 'Captcha',
        onMessageReceived: (message) {
          widget.callback(message.message);
        },
      ),
    );
    _controller.loadHtmlString(widget.htmlContent);
  }

  @override
  Widget build(BuildContext context) {
    return PlatformWebViewWidget(
      PlatformWebViewWidgetCreationParams(controller: _controller),
    ).build(context);
  }
}
```

### Expected results

Get the addJavaScriptChannel callback response but getting a crash message addJavaScriptChannel is not implemented on the current platform

### Actual results

Need to load html and get the message within the callback

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```
[!] Flutter (Channel stable, 3.22.2, on macOS 15.0 24A335 darwin-arm64, locale en-PK)
    • Flutter version 3.22.2 on channel stable at /Users/arslan/fvm/versions/3.22.2
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/arslan/fvm/versions/3.22.2. Consider adding /Users/arslan/fvm/versions/3.22.2/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/arslan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 129.0.6668.60

[✓] Network resources
    • All expected network resources are available.
</details>

**Comment by marslannasrmuab** [comment]
Please check below is the html which i am passing in flutter_web. @darshankawar 

Note: web_flutter working fine issue only coming in flutter web and i am using web related package

```
<html>
<head>
    <title>hCaptcha</title>
    <script src="https://hcaptcha.com/1/api.js?host=host" async defer></script>
    <style>
        /* Ensure that the body and form take 
up the full height of the available space */
        body, html {
            margin: 0;
          padding: 0;
            height: 100%;
            width: 100%;
        }
form {
            display: flex;
            height: 100%;
            width: 100%;
                 }
        /* Scale the captcha to fit the container */
        .h-captcha {

transform: scale(1.5); /* Adjust the scale factor as needed */
            transform-or
igin: top left;
        }
        /* Scale the iframe containing the puzzle window */

 iframe {
            transform: scale(1.5); /* Adjust the scale factor to match the ca
ptcha */
            transform-origin: top left;
            width: 150%;
            heig
ht: 150%;
        }
    </style>
</head>
<body style='background-color: white;'>
    <form
action="?" method="POST">
        <div class="h-captcha"
             data-sitekey="28dce
c46-35be-497c-bf56-78e6f88832a6"
             data-callback="captchaCallback">
        </d
iv>
    </form>
    <script>
        function captchaCallback(response) {
            if (
typeof Captcha !== "undefined") {
                Captcha.postMessage(response);

}
        }
    </script>
</body>
</html>
```




> > final Function(String) callback;
> > final String htmlContent;
> 
> @marslannasrmuab Can you provide what values to pass here ?
> 
> runnable code
> ```
> 
> import 'package:flutter/material.dart';
> import 'package:webview_flutter/webview_flutter.dart';
> import 'package:webview_flutter_platform_interface/webview_flutter_platform_interface.dart';
> 
> void main() {
>   runApp(MaterialApp(
>     home: CaptchaWebPlatform(),
>   ));
> }
> 
> class CaptchaWebPlatform extends StatefulWidget {
>   final Function(String) callback;
>   final String htmlContent;
> 
>   const CaptchaWebPlatform(
>       {super.key, required this.callback, required this.htmlContent});
> 
>   @override
>   State<CaptchaWebPlatform> createState() => _CaptchaWebPlatformState();
> }
> 
> class _CaptchaWebPlatformState extends State<CaptchaWebPlatform> {
>   late final PlatformWebViewController _controller = PlatformWebViewController(
>       const PlatformWebViewControllerCreationParams(
>       ));
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     _controller.addJavaScriptChannel(
>       JavaScriptChannelParams(
>         name: 'Captcha',
>         onMessageReceived: (message) {
>           widget.callback(message.message);
>         },
>       ),
>     );
>     _controller.loadHtmlString(widget.htmlContent);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return PlatformWebViewWidget(
>       PlatformWebViewWidgetCreationParams(controller: _controller),
>     ).build(context);
>   }
> }
> ```

**Comment by stuartmorgan** [comment]
Note that this is the documented behavior; please see https://pub.dev/packages/webview_flutter_web#webview_flutter_web

Given that you are loading web content that you control and the goal is just to get a message out, I believe this is covered by https://github.com/flutter/flutter/issues/101758, so closing as a duplicate. If the limited version described there would not cover your use case, please file an issue using the Feature Request issue template, describing the use case as clearly as possible, since generic support for this API on web is impossible.
