### ISSUE TITLE
Allow customization of AppBar's end padding

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#155747]
### Use case

Flutter currently does not follow the Material 3 spec for AppBars, in regards to the margin of the action icons, them being 8dp too close to the end.

Being required to add `SizedBox` or `Padding` to every `AppBar` used throughout the app in order to follow through with visual fidelity is not feasible.

This issue has been reported several times now (#17852, #91884, #115349, including mine #137274, which was dismissed due to open-source bureaucracy), all of them being closed under the conclusion it would break apps. However, I think this viewpoint does not help fix the issue any time soon.

I am not requesting to change the *default behavior*. I am requesting to add an *option*, so developers can explicitly opt-in to this behavior, similar to the `useMaterial3` flag.

### Proposal

A property which will allow the developer to add a margin/padding at their own discretion. See #155632.

Should the Flutter Material team ever change their stance on this matter, this property would gracefully allow developers to undo the changes (i.e. `AppBarTheme.endPadding = 0.0`). In the mean time, it would allow me and others, to fix it for themselves early.

**Comment by TahaTesser** [comment]
cc: @QuncCccccc
