### ISSUE TITLE
Flutter incorrectly reports the "resumed" in a lifecycle event when on the lock screen on iOS18

### ISSUE THREAD

**Issue by reduxdj** [flutter/flutter#155754]
### Steps to reproduce

Interact with the lock screen, on a flutter app and you get the wrong events.

### Expected results

Expect not to get the state not to be `resumed`.

### Actual results

the event should not happen when i lock the device

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[[Paste your logs here]](flutter:  APP_LOG 2024-09-26 05:17:12.034400 SIPController: ApplifecycleState _onStateChanged AppLifecycleState.resumed)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.3 23D56 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for Patrick’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Cailin’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @reduxdj, I just tested with the code sample from  https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html and I can't reproduce the issue. When my device is locked/unlocked (without opening the app), I don't receive any events in the app. 

Can you provide a complete minimal reproducible code sample along with detailed steps to reproduce? Also can you upgrade to the latest version of flutter stable to see if you still experience this issue? 

I tested this on my iPhone XS running iOS 18

**Comment by jahertor** [comment]
Same here. Often my Android app triggers the "resume" event when is in background. It is a game and I pause the music in "onPause" and resume it in "onResume", so the music starts playing in background.

**Comment by danagbemava-nc** [comment]
Hi @jahertor, does this happen immediately after the app is put in the background or it happens a while later?

**Comment by jahertor** [comment]
> Hi @jahertor, does this happen immediately after the app is put in the background or it happens a while later?

A while later, randomly. Usually it doesn't happen. Maybe some service is awaking the app and triggering the onResume, but it's hard to intuit.

I'm using [flutter_soloud](https://pub.dev/packages/flutter_soloud) for playing music in loop. My device is S23 Ultra running Android 14 (One UI 6.1).

**Comment by danagbemava-nc** [comment]
Hi @jahertor, can you provide a complete minimal reproducible code sample that we can use to properly investigate this issue?
