### ISSUE TITLE
Engine -> Framework roll failing

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#155727]
Roller: https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
First failure: https://github.com/flutter/flutter/pull/155696

Example failure: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/87429/overview
```
ELAPSED TIME: 0.584s for bin/flutter update-packages --verify-only in /b/s/w/ir/x/w/flutter
▌16:40:59▐ Package Allowlist...
Unhandled exception:
Null check operator used on a null value
#0      _checkConsumerDependencies (file:///b/s/w/ir/x/w/flutter/dev/bots/analyze.dart:2022:49)
<asynchronous suspension>
#1      run (file:///b/s/w/ir/x/w/flutter/dev/bots/analyze.dart:170:3)
<asynchronous suspension>
#2      main (file:///b/s/w/ir/x/w/flutter/dev/bots/analyze.dart:52:3)
<asynchronous suspension>
```

**Comment by bdero** [comment]
Earliest failed roll I linked failed due to a different issue (10:26AM):

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: [
            'indicator: BoxDecoration(color: Color(0xff00ff00))',
            'indicatorColor: MaterialColor(primary value: Color(0xfff44336))',
            'indicatorSize: TabBarIndicatorSize.label',
            'dividerColor: Color(0xff000001)',
            'dividerHeight: 20.5',
            'labelColor: Color(0xff000002)',
            'labelPadding: EdgeInsets.all(20.0)',
            'labelStyle: TextStyle(inherit: true, color: MaterialColor(primary value:
Color(0xffffc107)))',
            'unselectedLabelColor: Color(0xff654321)',
            'unselectedLabelStyle: TextStyle(inherit: true, color: MaterialColor(primary value:
Color(0xff2196f3)))',
            'overlayColor: WidgetStatePropertyAll(MaterialColor(primary value: Color(0xffffeb3b)))',
            'mouseCursor: WidgetStatePropertyAll(SystemMouseCursor(contextMenu))',
            'tabAlignment: TabAlignment.center',
            'textScaler: no scaling',
            'indicatorAnimation: TabIndicatorAnimation.elastic'
          ]
  Actual: [
            'indicator: BoxDecoration(color: Color(alpha: 1.0000, red: 0.0000, green: 1.0000, blue:
0.0000, colorSpace: ColorSpace.sRGB))',
            'indicatorColor: MaterialColor(primary value: Color(alpha: 1.0000, red: 0.9569, green:
0.2627, blue: 0.2118, colorSpace: ColorSpace.sRGB))',
            'indicatorSize: TabBarIndicatorSize.label',
            'dividerColor: Color(alpha: 1.0000, red: 0.0000, green: 0.0000, blue: 0.0039,
colorSpace: ColorSpace.sRGB)',
            'dividerHeight: 20.5',
            'labelColor: Color(alpha: 1.0000, red: 0.0000, green: 0.0000, blue: 0.0078, colorSpace:
ColorSpace.sRGB)',
            'labelPadding: EdgeInsets.all(20.0)',
            'labelStyle: TextStyle(inherit: true, color: MaterialColor(primary value: Color(alpha:
1.0000, red: 1.0000, green: 0.7569, blue: 0.0275, colorSpace: ColorSpace.sRGB)))',
            'unselectedLabelColor: Color(alpha: 1.0000, red: 0.3961, green: 0.2627, blue: 0.1294,
colorSpace: ColorSpace.sRGB)',
            'unselectedLabelStyle: TextStyle(inherit: true, color: MaterialColor(primary value:
Color(alpha: 1.0000, red: 0.1294, green: 0.5882, blue: 0.9529, colorSpace: ColorSpace.sRGB)))',
            'overlayColor: WidgetStatePropertyAll(MaterialColor(primary value: Color(alpha: 1.0000,
red: 1.0000, green: 0.9216, blue: 0.2314, colorSpace: ColorSpace.sRGB)))',
            'mouseCursor: WidgetStatePropertyAll(SystemMouseCursor(contextMenu))',
            'tabAlignment: TabAlignment.center',
            'textScaler: no scaling',
            'indicatorAnimation: TabIndicatorAnimation.elastic'
          ]
   Which: at location [0] is 'indicator: BoxDecoration(color: Color(alpha: 1.0000, red: 0.0000,
green: 1.0000, blue: 0.0000, colorSpace: ColorSpace.sRGB))' instead of 'indicator:
BoxDecoration(color: Color(0xff00ff00))'
```

**Comment by bdero** [comment]
The analyzer failure first appears 2 rolls ago (4:04PM):
https://github.com/flutter/flutter/pull/155720

**Comment by bdero** [comment]
`onSurfaceCreated` issue is still present in the most recent roll. Reverting https://github.com/flutter/engine/pull/55418 to fix

**Comment by bdero** [comment]
The [Linux framework_tests_librararies](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20framework_tests_libraries/68414/overview) failure is probably related to the recent color work that @gaaclarke is working on. But the first trouble roll doesn't seem to contain any commit content that I would expect to cause an issue here: https://github.com/flutter/flutter/pull/155696

**Comment by bdero** [comment]
NVM, the current roll (https://github.com/flutter/flutter/pull/155729) is not suffering from this issue. So we're good with that one. Only known issue left is the analyzer.

**Comment by bdero** [comment]
`Linux analyzer` failure started on: https://github.com/flutter/flutter/pull/155720
The roll just before it (which succeeded the `Linux analyze` was https://github.com/flutter/flutter/pull/155718

Diff is these two commits:

2024-09-25 [jonahwilliams@google.com](mailto:jonahwilliams@google.com) [engine] set platform thread name to ui. (https://github.com/flutter/engine/pull/55362)
2024-09-25 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Dart SDK from c2728b947e46 to 016368ee313d (1 revision) (https://github.com/flutter/engine/pull/55444)

So probably this Dart roll: https://github.com/flutter/engine/pull/55444
Diff of Dart roll is https://dart.googlesource.com/sdk.git/+log/c2728b947e46..016368ee313d

**Comment by zanderso** [comment]
The failing line of code in the analyzer script is below an invocation of `pub deps` at https://github.com/flutter/flutter/blob/master/dev/bots/analyze.dart#L1986.

The Dart SDK roll contained a roll of pub here: https://dart.googlesource.com/sdk.git/+/92ed87daae85b0a4461d4751ce0a793448625699, which contains a change to the output of the `pub deps` command: https://dart.googlesource.com/pub.git/+/23e3d4f4 cc @sigurdm

**Comment by bdero** [comment]
Dart roll is stopped and trouble roll (https://github.com/flutter/engine/pull/55454) is reverted.

Waiting on postsubmit artifacts.

**Comment by bdero** [comment]
From the [comment](https://dart.googlesource.com/pub.git/+/23e3d4f4a761867b1e3eded9a92a4290a01daadb/lib/src/command/deps.dart#129), it sounds like the `dependency` field wasn't supposed to change behavior. But the ternary [here](https://dart.googlesource.com/pub.git/+/23e3d4f4a761867b1e3eded9a92a4290a01daadb/lib/src/command/deps.dart#132) got flipped:

```dart
          'dependencies': (isRoot
                  ? currentPackage.dependencies
                  : currentPackage.immediateDependencies)
              .keys
              .toList(),
```

Previously it was set to `next`, which is:
```dart
        final next = (isRoot
                ? currentPackage.immediateDependencies
                : currentPackage.dependencies)
            .keys
            .toList();
```


For recovering the Dart roll quickly, this might work:
```dart
diff --git a/dev/bots/analyze.dart b/dev/bots/analyze.dart
index 8bf5836aeb..4104a78dc6 100644
--- a/dev/bots/analyze.dart
+++ b/dev/bots/analyze.dart
@@ -2011,7 +2011,12 @@ Future<void> _checkConsumerDependencies() async {
       }
       dependencies.add(currentPackage['name']! as String);

-      final List<String> currentDependencies = (currentPackage['dependencies']! as List<Object?>).cast<String>();
+      final List<String> currentDependencies = <String>[];
+      for (final String key in <String>['dependencies', 'devDependencies', 'directDependencies']) {
+        if (currentPackage.containsKey(key)) {
+          currentDependencies.addAll((currentPackage[key]! as List<Object?>).cast<String>());
+        }
+      }
       for (final String dependency in currentDependencies) {
         // Don't add dependencies we've already seen or we will get stuck
         // forever if there are any circular references.
```

But I don't really know if `directDependencies` + `devDependencies` is equivalent to `dependencies` previous behavior or not.

**Comment by sigurdm** [comment]
> From the [comment](https://dart.googlesource.com/pub.git/+/23e3d4f4a761867b1e3eded9a92a4290a01daadb/lib/src/command/deps.dart#129), it sounds like the dependencies field wasn't supposed to change behavior. But the ternary [here](https://dart.googlesource.com/pub.git/+/23e3d4f4a761867b1e3eded9a92a4290a01daadb/lib/src/command/deps.dart#132) got flipped

Oops - sorry about that. I'll fix it.

old dependencies = directDependencies + devDependencies + dependencyOverrides. (If you don't have dependency overrides they should be the same)

**Comment by gaaclarke** [comment]
> NVM, the current roll (#155729) is not suffering from this issue. So we're good with that one. Only known issue left is the analyzer.

Ahh yea, this is because of https://github.com/flutter/flutter/pull/155476.  It passed presubmit checks and broke in post submit checks since the PR didn't include the color change.  It has since been reverted.

**Comment by bdero** [comment]
We're waiting on the pub version bump here to unblock the Dart roller: https://dart-review.googlesource.com/c/sdk/+/387260/1
