### ISSUE TITLE
How to run flutter example

### ISSUE THREAD

**Issue by zhangyulong882** [flutter/flutter#1557]
I opened a terminal in the directory examples/widgets and run the command like "flutter start --checked -t  fab.dart", it failed. What I got is like:
Cannot locate the sky_engine package; did you include 'flutter' in your pubspec.yaml file?

Is there anything wrong with my command? How can I run the flutter example?

**Comment by a14n** [comment]
Each example directory contains its own `pubspec.yaml`. You should run `flutter upgrade` in `examples/widgets` before launching `flutter start`.

**Comment by sethladd** [comment]
Thanks for the question!

Sounds like we should provide a better instruction here. I opened https://github.com/flutter/flutter/issues/1563 to track. Thanks to @a14n for the help here!

@zhangyulong882 if that doesn't work, please reopen the issue.

**Comment by zhangyulong882** [comment]
It worked. Thanks!

**Comment by sethladd** [comment]
@zhangyulong882 great to hear! Keep the feedback coming.
