### ISSUE TITLE
Support `exitFullscreen` in FireFox flutter web

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#155756]
### Use case

The [`exitFullscreen`](https://api.dart.dev/stable/3.2.5/dart-html/HtmlDocument/exitFullscreen.html) function is not supported in Firefox Flutter Web.

### Proposal

And it seems that Firefox currently [supports](https://developer.mozilla.org/en-US/docs/Web/API/Document/exitFullscreen) this option, but it is not supported in Flutter Web. I suggest that this function be supported.

**Comment by danagbemava-nc** [comment]
This should be reported on the dart-lang/sdk repo as this is method is from that `dart:html` package. It seems this has already been reported. See https://github.com/dart-lang/sdk/issues/50857 

You may try using `package:web` as it appears to work there. See https://github.com/dart-lang/sdk/issues/50857#issuecomment-2294345267

Closing from here as this is not a flutter issue. 

Thank you
