### ISSUE TITLE
ANR on ibc.so-> libutils.so-> libandroid_runtime.so

### ISSUE THREAD

**Issue by erluxman** [flutter/flutter#155777]
### Steps to reproduce

Couldnt reproduce but its reported on Firebase crashlytics 

### Expected results

NO ANRS

### Actual results

**ANRs Reported on crashlytics**

**Details:** 
I am getting ANR reports on crashlytics when the app is in background but it only appears on the Android version >=14. Sadly I cannot reproduce it on the emulator and I do not have an Android 14 device. 

It doesn't mention particularly any native method that I can pinpoint to any features that my app uses 

**Major features my app uses that might have something to do with  the *Background ANR* are:**

 - location tracking
 - local and push notification
 - firebase firestore
 
### Logs

**Below is the textual version of the bug report** 

     main (native):tid=1 systid=12610 
    #00 pc 0xc7d28 libc.so (__epoll_pwait + 8) (BuildId: 1d36f8ae6e0af6158793abea7d4f4f2b)
    #01 pc 0xfc28 libutils.so (android::Looper::pollOnce + 184) (BuildId: c07f08c7e5a964a8f8c6bc5c820fb795)
    #02 pc 0x18c53c libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce + 44) (BuildId: e0fc1ccfe043ab286e745f48696bc0d8)
           at android.os.MessageQueue.nativePollOnce(Native method)
           at android.os.MessageQueue.next(MessageQueue.java:349)
           at android.os.Looper.loopOnce(Looper.java:189)
           at android.os.Looper.loop(Looper.java:317)
           at android.app.ActivityThread.main(ActivityThread.java:8592)
           at java.lang.reflect.Method.invoke(Native method)
           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

The list of dependency I am using 

    dependencies:
      address: ^0.1.0+2
      flutter:
          sdk: flutter
      battery_plus: ^5.0.1
      cached_network_image: ^3.1.0
      confetti: ^0.7.0
      dartx: ^1.2.0
      flutter_osm_plugin: ^1.3.0
      dropdown_search: ^5.0.6
      email_validator: ^2.1.16
      easy_localization: ^3.0.0
      cloud_firestore: ^4.9.0
      firebase_analytics: ^10.2.1
      flutter_card_swiper: ^6.0.0
      firebase_auth: ^4.2.6
      firebase_dynamic_links: ^5.0.12
      firebase_core: ^2.24.2
      firebase_crashlytics: ^3.0.12
      firebase_database: ^10.0.10
      firebase_messaging: ^14.2.2
      firebase_performance: ^0.9.2+7
      firebase_storage: ^11.0.11
      flutter_picker_plus: ^1.2.0
      fl_chart: ^0.68.0
      flutter_background_geolocation: ^4.15.5
      duration_picker: 
        path: packages/duration_picker
      flutter_spinkit: ^5.1.0
      flutter_image_compress: ^2.1.0
      flutter_stripe: ^9.6.0
      flutter_bloc: ^8.1.3
      flutter_polyline_points: ^2.0.0
      flutter_local_notifications: ^17.2.2
      flutter_rating_bar: ^4.0.0
      flutter_riverpod: ^2.3.7
      flutter_staggered_grid_view: ^0.7.0
      flutter_svg: ^2.0.9
      fluttertoast: ^8.0.8
      flutter_chat_types: ^3.6.2
      logging: ^1.2.0
      #geolocator: ^8.2.1
      get_it: ^7.2.0
      google_fonts: ^4.0.4
      google_maps_flutter: ^2.5.0
      google_maps_place_picker_mb: ^3.1.2
      google_sign_in: ^6.1.6
      hive_flutter: ^1.1.0
      http: ^1.2.0
      image_picker: ^1.0.4
      location: ^5.0.0
      lottie: ^2.3.2
      percent_indicator: ^4.2.3
      permission_handler: ^11.0.1
      shared_preferences: ^2.0.17
      share_plus: ^7.2.1
      rxdart: ^0.27.7
      sign_in_with_apple: ^6.1.2
      # tflite_flutter: ^0.9.0
      url_launcher: ^6.0.18
      diacritic: ^0.1.4
      device_info_plus: ^9.0.2
      path_provider: ^2.0.5
      flash: ^3.0.5+2
      uuid: ^4.3.3
      webview_flutter: ^4.4.2
      flutter_date_pickers: ^0.4.3
      meta: ^1.8.0
      # date_time_picker: ^2.1.0
      # flutter_datetime_picker:
      #     git:
      #         url: https://github.com/Realank/flutter_datetime_picker.git
      #         ref: master
      smooth_page_indicator: ^1.0.0+2
      showcaseview: ^3.0.0
      package_info_plus: ^5.0.1
      version: ^3.0.2
      cupertino_icons: ^1.0.3
      flutter_custom_clippers: ^2.0.0
      barcode_widget: ^2.0.4
      flutter_countdown_timer: ^4.1.0
      flutter_widget_from_html_core: ^0.14.9
      tutorial_coach_mark: ^1.2.11
      flutter_typeahead: ^5.2.0
      community_charts_flutter: 1.0.1
      stacked: ^3.4.0
      # day_picker: ^2.2.0
      time_range: ^1.1.0
      flutter_chat_ui: ^1.6.6
      firebase_remote_config: ^4.2.6
      collection: ^1.15.0-nullsafety.4
      geolocator: 10.1.1
      app_settings: ^5.1.1
      firebase_in_app_messaging: ^0.7.5+7
      firebase_app_installations: ^0.2.5+7
      pointer_interceptor: ^0.10.1+2
      mapbox_search: any
      polyline_codec: ^0.1.6
    
    dependency_overrides:
      package_info_plus: ^4.1.0
      google_api_headers: ^3.2.1
      web: ^1.0.0
      flutter_osm_web: ^1.3.0
      google_maps_flutter_platform_interface: ^2.9.2
      # firebase_core_platform_interface: ^4.8.0
      #test_api: 0.4.18
      # stripe_android: "9.5.0+1"
      
    dev_dependencies:
      flutter_test:
        sdk: flutter
      build_runner: ^2.1.2
      flutter_launcher_icons: ^0.13.1
      lint: ^2.0.20
      dependency_validator: ^3.2.2

Any clue what might be causing it?

### Screenshots or Video

[![enter image description here][2]][2]
[![enter image description here][3]][3]
[![enter image description here][4]][4]

  [2]: https://i.sstatic.net/CUJxqHyr.png
  [3]: https://i.sstatic.net/kEz43j1b.png
  [4]: https://i.sstatic.net/BHyLXqgz.png

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    ✗ Unable to get list of installed Simulator runtimes. (recently updated mac and flutter so haven't setup iOS but issue  is with Android)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1.3)
[✓] VS Code (version 1.93.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
[✓] Network resources

</details>

**Comment by darshankawar** [comment]
Thanks for the report @erluxman 
Looking at the crash log, it seems mostly coming from native as I don't see any flutter related frames in it. If there's more crash log, please provide the same.

There have been couple of similar reports:

https://github.com/flutter/flutter/issues/147155
https://github.com/flutter/flutter/issues/144696

Since you are using webview_flutter, and looking at `android::android_os_MessageQueue_nativePollOnce` entry in the log, it may be related to https://github.com/flutter/flutter/issues/125090 that you can check.
