### ISSUE TITLE
Add foundational bits to enable `dart_test`-type rules in the engine

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#155769]
- [ ] Write a `tool_executable` (name TBD) rule that generates a shell (and later, batch, for Windows) in `out/`
~~- [ ] Write a `dart_snapshot` rule that generates a [kernel snapshot][^1] and depfile for a given Dart entrypoint~~
- [ ] Write a `dart_test` rule that generates a `tool_executable` ~~and `dart_snapshot`,~~ and uses `dart test` to run a file

---

Working on https://github.com/flutter/flutter/issues/147013 and wanted to write out some of my thoughts to explain what I _think_ needs to get done, and why it will take a different path the @cbracken's original PR, https://github.com/flutter/engine/pull/52241, and need (likely 1-2 PRs) foundational work as a starting step.

We'd like to get to a world where (something) like the following can be written:

```gn
# //flutter/tools/engine_tool/BUILD.gn

import("//flutter/build/dart/rules.gni")

dart_test_suite("tests") {
  sources = ["test/**/*_test.dart"],
}
```

But let's break that down a bit, and make it more verbose to make it more understandable:

```gn
# //flutter/tools/engine_tool/BUILD.gn

import("//flutter/build/dart/rules.gni")

dart_test("build_command_test") {
  script = "test/build_command_test.dart",
}

dart_test("utils_test") {
  script = "test/utils_test.dart",
}

dart_test("worker_pool_test") {
  script = "test/worker_pool_test.dart",
}
```

Ok, now one step further, what does/would `et test //flutter/tools/engine_tool:build_command_test` do?

1. Generate a `build_command_test.depfile` (and as a side-effect, snapshot)
2. Generate a `build_command_test.sh` file that has contents something like:

    ```sh
    #!/bin/bash
    set -e
    pushd {{WORKING_DIR}}
    {{DART_BINARY}} test test/build_command_test.dart
    popd
    ```

3. Runs a ninja build that builds (1) and (2)
4. Runs the executable output by (2), i.e. `../out/host_debug/build_command_test.sh` (or whatever)

[^1]: Technically the snapshot is not needed, and we could work with the VM team to skip if it would improve build times.

---

/cc @jonahwilliams @cbracken @jakemac53 @johnmccutchan

**Comment by jonahwilliams** [comment]
Seems reasonable. ideally we could use the snapshot as the input to the test script but that isn't strictly necessary. Alternatively, we could have a compile mode that just produced a depfile with no compilation, if there was too much overhead on that.

**Comment by jakemac53** [comment]
If you are anyways creating the snapshot just to create the deps file then yeah you might as well try and get it working with `--precompiled` and pass the kernel file directly.

As a future optimization  you also might want to try and move in the modular build direction, where you have some sort of `dart_library` rule which produces a kernel file, and `deps` attributes to dart_test and dart_library, which take in kernel files produced from other dart libraries, to reduce duplicate work across tests. Even if you just included a single separately compiled kernel file for package:test and its dependencies, that would speed up your builds a large amount.

**Comment by johnmccutchan** [comment]
This all sounds reasonable. One user experience I would like to have:

Running 

`et test //flutter/blah:blah`

repeatedly will only build the shell script/snapshot of test code once

**Comment by matanlurey** [comment]
One ask by @zanderso (other than being included in GN discussions), is that the initial approach does not touch the `dart:ui` fixture tests, which have custom machinery (i.e. in `run_tests.py`) for things like crash reporting. I concur, and the v0 approach will be "plain" Dart VM tests.

**Comment by matanlurey** [comment]
@johnmccutchan:

> One user experience I would like to have:
> 
> Running
> 
> `et test //flutter/blah:blah`
> 
> repeatedly will only build the shell script/snapshot of test code once

Assuming we _only_ rebuilt the (static) shell script, any objections? I've been talked out of building the snapshot (for now).
