### ISSUE TITLE
flutter_local_notifications: ^17.2.2 & iOS 18

### ISSUE THREAD

**Issue by EnriqueTapiadorDonaire** [flutter/flutter#155770]
Hello, 
I'm seeing that flutter_local_notifications: ^17.2.2 when launching notifications in iOS18, being the screen off, you only hear the associated sound but are not able to wake up the screen so that they are seen.

**Comment by cedvdb** [comment]
It seems like you have an issue with an external library, in which case the best place to create in issue is in that repository.

The issue template has not been respected either.

**Comment by EnriqueTapiadorDonaire** [comment]
Sorry for the mistake, I am new to github. Could you tell me how to access this repository please? thanks.

**Comment by huycozy** [comment]
Closing this as it's not a Flutter framework or 1st party packages issue.
