### ISSUE TITLE
`@SuppressLint("...")` does not work as expected, forced to use `baseline.xml`

### ISSUE THREAD

**Issue by jesswrd** [flutter/flutter#155712]
### Use case

I wanted to suppress the deprecation linter using @SuppressLint("deprecation") [here](https://github.com/flutter/engine/blob/c558459ec9c1f70aaf230ad74622e57ad51bc9b9/shell/platform/android/io/flutter/embedding/android/FlutterView.java#L688), but I couldn’t so I added to baseline.xml [here](https://github.com/flutter/engine/pull/55002/files#diff-eca62fa9b484a45814df9d1989b602e5f53c5d8a7c599208d5639d19d832a82f:~:text=10406996%5D%20%22%3E-,%3Cissues%20format%3D%226%22%20by%3D%22lint,%3C/issue%3E,-%3Cissue).

**Comment by matanlurey** [comment]
Thanks!

**Comment by matanlurey** [comment]
This turns out to work fine, though the ID of the lint perhaps was not what you and @reidbaker expected?

https://github.com/flutter/engine/pull/55447
