### ISSUE TITLE
adb processes hanging around after using Flutter

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#15575]
I often find `adb` processes still listed in task manager long after I've closed IDEs etc. There are no Dart/Flutter/Gradle/Java processes left; only adb. I presume that these should be cleaned up when the flutter commands end?

![adb](https://user-images.githubusercontent.com/1078012/37476539-55ba73d4-286d-11e8-958b-826f7115bbcd.png)

(I don't see it all the time, I don't think it's reliably reproducible).

**Comment by jason-simmons** [comment]
The Android adb server process continues to run in the background after adb is used.  You can stop it manually with `adb kill-server`

See https://developer.android.com/studio/command-line/adb.html

**Comment by DanTup** [comment]
Ah, that explains that then! Does this mean the instance is reused and there should only be one, even after many sessions using Flutter?

**Comment by jason-simmons** [comment]
Yes, there should only be one adb server process

**Comment by xster** [comment]
I think this is reasonably working as intended. If you `adb start-server` (called implicitly when doing `adb anything`) for doing native Android dev, `ps` will show it hanging around as well. 

Please reopen if this is incorrect or causes other issues.

**Comment by DanTup** [comment]
Sounds fine to me, I thought it was spawned for each flutter process. Thanks!
