### ISSUE TITLE
GPU Hang Error using Impeller on iPad Pro 9.7 with iPadOS 16

### ISSUE THREAD

**Issue by mtallenca** [flutter/flutter#155883]
### Steps to reproduce

Using repo https://github.com/mtallenca/flutter_typeahead, run the example program on an iPad Pro 9.7 running iOS 16.7.10. in profile mode.

It also only happens in release (and profile builds), and only if Impeller is turned on.

### Expected results

Expected the app to work without GPU Hang Errors.

### Actual results

Once the GPU Hang Error occurs the app is in a state that cannot recover. The screen may still be flickering, but the app is unresponsive.

### Code sample

<details open><summary>Code sample</summary>

```dart
// Run the example program in repo https://github.com/mtallenca/flutter_typeahead
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

[logs.txt](https://github.com/user-attachments/files/17175583/logs.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/mike/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mike/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mike/Library/Android/sdk
    • Java binary at: /Users/mike/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/mike/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.3)
    • IntelliJ at /Users/mike/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[✓] Connected device (5 available)
    • Michael’s iPad (2) (mobile)     • f3dc95991d1b14a5bc3430040228accee7477ba7 • ios            • iOS 16.7.10 20H350
    • Michael’s iPad (mobile)         • 00008103-000329C9363B001E                • ios            • iOS 18.0 22A3354
    • macOS (desktop)                 • macos                                    • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                                   • web-javascript • Google Chrome 129.0.6668.60

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @mtallenca, does this work as expected on other iPad versions? I don't have the device in question and when I tested on my M1 iPad AIR, it worked as expected

**Comment by mtallenca** [comment]
Yes, repo works as expected on other ipads.  In our released product we see this hang when using this package on older ipads / iPhones (iPad mini 4, iPhone 6s, and iPad pro 9.7). I am only able to see the hang immediately with this repo using the ipad pro 9.7.  Also see https://github.com/flutter/flutter/issues/153574

**Comment by danagbemava-nc** [comment]
Hi @mtallenca, is this issue still occurring on the latest master/beta channels?

**Comment by mtallenca** [comment]
The repo does not cause GPU hang in beta.

**Comment by danagbemava-nc** [comment]
Hi @mtallenca, curious, does your app itself work as expected on the beta channel?

**Comment by mtallenca** [comment]
No. There is a crash in platform view code. a repo was submitted and https://github.com/flutter/engine/pull/55334 addresses it. But that's not in beta yet.

**Comment by danagbemava-nc** [comment]
Hi @mtallenca, per our triage policy, issues should be closed when they are fixed on the master/main channel. Since it appears that this has been fixed on the master channel, is there anything more we need to address in this issue?
