### ISSUE TITLE
[web] multiple severe benchmark regressions after engine roll

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#155850]
Engine roll: https://github.com/flutter/flutter/pull/155799

Regression: https://flutter-flutter-perf.skia.org/t/?begin=1727400207&end=1727400209&subset=all

Some regressions seem to have been misattributed to another PR too here: https://flutter-flutter-perf.skia.org/t/?begin=1727398530&end=1727398532&subset=all

I suspect this is due to https://github.com/flutter/engine/pull/55464. According to the benchmark history a previous attempt to land platform view changes cause the same regression: https://github.com/flutter/flutter/pull/155733

**Comment by harryterkelsen** [comment]
Fixed by https://github.com/flutter/engine/pull/55501
