### ISSUE TITLE
VS Code not able to find flutter

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#15584]
Here is the error: 

<img width="788" alt="screen shot 2018-03-15 at 3 22 18 pm" src="https://user-images.githubusercontent.com/16604/37489159-be4c27b6-2864-11e8-9db1-ec53f879d944.png">

The flutter has been clone and temp PATH has been setup.

**Comment by xster** [comment]
Does invoking `flutter` from the command line work? How did you open VS Code?

**Comment by DanTup** [comment]
@azamsharp As a quick fix, clicking the `Locate SDK` button on the message will let you browse to the SDK and it will be saved.

Most commonly, people set `PATH` in their terminals profile (eg. a `.bashrc`) which only applies to the terminal, so if you launch VS Code from a launcher/dock it may not apply (you can confirm this by launching Code from the terminal and see if it works there - if it does, then this is likely the issue). A way to fix this might be by setting path somewhere that applies globally (like `/etc/path.d/xxx` or `/etc/profile.d/xxx`).

**Comment by DanTup** [comment]
@azamsharp Did you get this sorted? Is there anything you want me to look into, or can I close this?

**Comment by Hixie** [comment]
Closing since there was no response.
