### ISSUE TITLE
I opened all permissions, but it still crashed. Is your problem solved?

### ISSUE THREAD

**Issue by huangxianyu** [flutter/flutter#155895]
> @will-tcg @rpungin I had the same issue, and it turned out to be a permissions problem with my IDE. I was able to fix it by adjusting the settings on my Mac: `System Settings -> Privacy & Security -> Local Network -> [Find your IDE] -> Toggle ON`. Hopefully, this might solve the issue for you as well! 🤞🏻

Seems like truth. But unfortunately, it didn't help :(

_Originally posted by @DES-Destry in https://github.com/flutter/flutter/issues/150131#issuecomment-2367204426_

**Comment by iapicca** [comment]
@huangxianyu
maybe wouldn't be better to continue the conversation in the original [issue](https://github.com/flutter/flutter/issues/150131) since it's still open

**Comment by danagbemava-nc** [comment]
Closing this since the referenced issue is still open
