### ISSUE TITLE
Windows UDP bug, "port unreachable" will close a UDP listener

### ISSUE THREAD

**Issue by beelabcloud** [flutter/flutter#155823]
### Steps to reproduce

A UDP listener will throw a SocketException and be closed when it be used for sending data to unreachable host.
It's actually a bug of MS Windows, as discussed here: "**https://stackoverflow.com/questions/34242622/windows-udp-sockets-recvfrom-fails-with-error-10054**". As addressed in the discussion, to solve it, the socket  need to disable SIO_UDP_CONNRESET, for example:

```
#pragma comment(lib, "ws2_32.lib")
#define SIO_UDP_CONNRESET _WSAIOW(IOC_VENDOR, 12)

BOOL bNewBehavior = FALSE;
DWORD dwBytesReturned = 0;
WSAIoctl(s, SIO_UDP_CONNRESET, &bNewBehavior, sizeof bNewBehavior, NULL, 0, &dwBytesReturned, NULL, NULL);
```
By the way, the latest stable version SDK breaks Android Studio Dart code "parsing"  on both my laptop and desktop, therefore I stuck at version 3.22.0.

### Expected results

 It's a udp listener,  it should not be closed on receiving error. 

### Actual results

The listener would be close due to the SocketException "OS Error: No service is operating at the destination network endpoint on the remote system"

### Code sample

```
    var _socket = await RawDatagramSocket.bind(InternetAddress.anyIPv4, 9099);
    _socket.listen((RawSocketEvent e) {
      // Bee.debug("e: $e");
      switch (e) {
        case RawSocketEvent.read:
          Datagram? d = _socket.receive();
          if (d != null) {
            print("recv: $d");
          }
      }
    }, onError: (e) {
      print("listen or recv exception: $e");
    });

    for (int i = 1; i < 255; i++) {
      _socket.send(Uint8List(10), InternetAddress("192.168.199.$i"), 9100);
    }   
```

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4780], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.40)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by darshankawar** [comment]
Labeling this for team's tracking.

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/390140
