### ISSUE TITLE
p:camera Capture 16:9 or 4:3 photos

### ISSUE THREAD

**Issue by jozefvodicka** [flutter/flutter#155818]
### Use case

4:3 photos can capture "more", 16:9 is cropped version of 4:3. You can try it yourself using native camera.

previously closed issue: https://github.com/flutter/flutter/issues/93994

### Proposal

Ability to choose preference whether camera should result in preview and photo captured 16:9 or 4:3 or 1:1...

**Comment by darshankawar** [comment]
@jozefvodicka 
I think your use case is similar to below open issues, so I will close this in favor of them:

https://github.com/flutter/flutter/issues/45665
https://github.com/flutter/flutter/issues/80393

If you disagree, please write in comments and I'll reopen it.
