### ISSUE TITLE
Docs for integrating with Fastlane

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#15582]
I'm currently trying to figure out how to start building/signing/deploying a Flutter project using Fastlane tools and there is really no information out there on this topic.

Seems like a good candidate to document on flutter.io/fastlane.

I'll try to update this issue with my findings, but if someone already have an example it would be really helpful.

For now I'm thinking to use Gallery app configs as primary example.

**Comment by Purus** [comment]
I am interested in this. Let's see if we can coloborate on this.

**Comment by xster** [comment]
No doc as of yet. Ideally we would like to add a proper `build_with_flutter` action or plugin to Fastlane but it's not on our immediate worklist queue. 

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/android/fastlane/Fastfile and https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/ios/fastlane/Fastfile are indeed good places to start. 

On Android, most of the building/signing is done on gradle/Play console anyway the Fastlane part should be minimal.

**Comment by AppleEducate** [comment]
Ideally, we could even have a shared Fastlane folder too. Then run Fastlane release and it release android and ios

**Comment by xster** [comment]
Adding Flutter awareness back into Fastlane and letting Fastlane build both platform apps is a medium term goal that makes sense to us. It's just not in priority at this moment.

**Comment by xster** [comment]
Added a wiki at https://github.com/flutter/flutter/wiki/Continuous-delivery-with-Flutter

**Comment by xster** [comment]
Reopening to move to flutter.io website

**Comment by Sfshaza** [comment]
The doc is on the website. Closing.
