### ISSUE TITLE
Flutter debugging stopped working in Intellij

### ISSUE THREAD

**Issue by xtien** [flutter/flutter#155812]
### Steps to reproduce

1. Start intellij Ultimate, Flutter and Dart plugins installed
2. start your flutter project, set a breakpoint
3. find that the debugger doesn't stop at your breakpoint

### Expected results

Debugger stops at breakpoint

### Actual results

debugger does not stop at any breakpoint

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 24.04.1 LTS 6.8.0-45-generic, locale en_US.UTF-8)
    • Flutter version 3.24.3 on channel stable at /home/christine/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /opt/android
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /opt/android
    • Java binary at: /home/christine/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/christine/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at /home/christine/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3)
    • IntelliJ at /home/christine/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate-2
    • Flutter plugin version 81.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04.1 LTS 6.8.0-45-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

**Comment by huycozy** [comment]
Hi @xtien 
I checked this on `IntelliJ IDEA 2024.2.3 (Community Edition)` but it can stop at breakpoint as expected. 

I see you are using two IntelliJ IDEA Ultimate versions, which version does the issue occur on? And does the issue occur on a simple Flutter project (counter app for eg) or only on your project?

**Comment by RuberDucky** [comment]
I recommend trying Visual Studio Code (VS Code) as your development environment. It offers a wide range of powerful extensions that can significantly boost your productivity and streamline your workflow as a Flutter developer. If you find it challenging to get started with VS Code, I'm happy to guide you through the setup and demonstrate how you can leverage its features to improve your development experience.

Feel free to reach out if you need any assistance!
