### ISSUE TITLE
Using SelectableRegion (or invisible platform views in general) on web causes memory leaks

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#155833]
### Steps to reproduce

Use the SelectionRegistrar on web

### Expected results

Not leak memory

### Actual results

Memory leaks

### Code sample

https://dartpad.dev/?id=bd2db0fba7834b11106f8ada372ab542

Watch memory usage grow here, take out the SelectableRegion and problem goes away.

### Flutter Doctor output

Reproducable also on current dartpad version in sample linked.

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.93.0)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by jezell** [comment]
Seems to be leaking picture recorders during compositing maybe @harryterkelsen, only happens in the case where the picture count > 1

**Comment by grahamsmith** [comment]
Ah that's where this is coming from! Seeing this in Sentry.

Good catch!

**Comment by darshankawar** [comment]
Thanks for the report. Seeing the same behavior with profile and release modes as well. 

```
Stable : 3.24.3
Master : 3.26.0-1.0.pre.201
```

**Comment by chunhtai** [comment]
My guess is the platform view may not be disposed correctly, cc @yjbanov and @Renzo-Olivares

**Comment by harryterkelsen** [comment]
I'm working on this area right now. I'll see if this is fixed by my latest PR

**Comment by jezell** [comment]
@harryterkelsen awesome

**Comment by harryterkelsen** [comment]
It seems my PR refactoring platform view does indeed fix this: https://github.com/flutter/engine/pull/55563

![Screenshot 2024-10-02 at 11 25 07 AM](https://github.com/user-attachments/assets/86379684-f7e9-4259-aee4-c8df66688d13)

**Comment by jezell** [comment]
@harryterkelsen do you think it's too big of a fix to hotfix? If it's not too big, I'm sure a lot of people would really like a fix. Seems to maybe only happen when frames are getting dropped or something, so it's a bit random in the wild, but when it does happen, it only takes a minute or to for the app to go OOM.

**Comment by jezell** [comment]
Looks from the code like the PR flattens the picture recorders a bit better. This is really nice. Did seem like the number of recorders wasn't in alignment with the number of real layers in 3.24.x.

**Comment by harryterkelsen** [comment]
Unfortunately I think this change is too big and hasn't been thoroughly tested enough on real world apps to cherry pick to stable.

**Comment by jezell** [comment]
Yeah, had a feeling after looking at the change. Looks like a good change, but not just a hotfix for this problem, part of a larger improvement.
