### ISSUE TITLE
[url_launcher] intent:// is not supported in ViewView launched by url_launcher LaunchMode.inAppWebView

### ISSUE THREAD

**Issue by 551100kk** [flutter/flutter#155872]
Copied from internal bug b/370006369

The `intent://` urls opened from the android webview show errors
![image](https://github.com/user-attachments/assets/c333a6f5-da23-4235-9c94-86479e73fc1a)

**What's the expected outcome and the actual outcome?**

The intent should be opened as a new activity. In this case: open native google map app if installed. 
Example fix: `urllauncher/WebViewActivity.java`

```java
@RequiresApi(Build.VERSION_CODES.N)
@Override
public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
  String url = request.getUrl().toString();
  if (url.startsWith("intent://")) {
    return handleIntentUrl(view, url);
  }

  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    view.loadUrl(url);
  }
  return false;
}

private boolean handleIntentUrl(WebView view, String url) {
  try {
    Intent intent = Intent.parseUri(url, Intent.URI_INTENT_SCHEME);
    Context context = view.getContext();

    if (intent == null) {
      Log.wtf(TAG, String.format("Intent url is not handled: %s, intent is null", url));
      return false;
    }

    ResolveInfo resolveInfo =
        context
            .getPackageManager()
            .resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY);

    if (resolveInfo == null) {
      Log.wtf(
          TAG, String.format("Intent url is not handled: %s, resolveInfo is null", url));
      return false;
    }

    view.stopLoading();
    context.startActivity(intent);
  } catch (URISyntaxException e) {
    Log.wtf(TAG, "handleIntentUrl exception", e);
    return false;
  }
  Log.wtf(TAG, String.format("Intent url is not handled: %s", url));
  return false;
}
};

```

**[Reproduction project]**

minimal code to reproduce:

```dart
url_launcher.launchUrlString(
  https://www.google.com/maps/contrib/115213115031834685567/reviews, 
  mode: LaunchMode.inAppWebView,
);
```

**Comment by stuartmorgan** [comment]
> **What's the expected outcome and the actual outcome?**
> 
> The intent should be opened as a new activity.

Could you clarify why this is the expected outcome? `url_launcher` is providing an option to open in the standard system webview, and the standard system webview apparently chooses not to automatically support the `intent:` scheme. Why would the expectation for `url_launcher` be different than for the webview itself?

**Comment by 551100kk** [comment]
**Problem:**
In native Android development, you can customize how a WebView handles URLs (like "open in app" links) using `shouldOverrideUrlLoading` in `WebViewClient`. However, Flutter's `url_launcher` doesn't offer this customization. It simply opens the link in the system's `WebView` when `LaunchMode.inAppWebView`, which may not handle "open in app" links correctly.

**Expected Solution:**
Flutter's `url_launcher` should provide a mechanism similar to Android's `shouldOverrideUrlLoading`. This would allow developers to control how different URLs are handled, including "open in app" links, within their Flutter apps.

**Why this is important:**
Many apps use custom URL schemes (like intent:) for deep linking and other functionalities.
Without custom handling, these links might not work correctly when launched from a Flutter app.

**Comment by stuartmorgan** [comment]
> In native Android development, you can customize how a WebView handles URLs (like "open in app" links) using `shouldOverrideUrlLoading` in `WebViewClient`. However, Flutter's `url_launcher` doesn't offer this customization.

That's because `url_launcher` isn't intended to provide highly customizable webview experiences; exposing all the functionality and customization of `WebView` is what `webview_flutter` is for. `url_launcher` is intended for simple use cases.

> **Expected Solution:**
> Flutter's `url_launcher` should provide a mechanism similar to Android's `shouldOverrideUrlLoading`. This would allow developers to control how different URLs are handled, including "open in app" links, within their Flutter apps.

Is there a reason you aren't using `webview_flutter` if the goal is to customize the behavior of in-app web content handling?

**Comment by 551100kk** [comment]
I see. Thanks for the quick response on the design idea behind the `url_launcher ` and the alternative approach `webview_flutter ` to resolve the issue!

Tested locally the alternative solution works well. Thus, closing the issue.
