### ISSUE TITLE
Every time I refresh the h5 application, the text cannot be loaded and it appears after 1 second.

### ISSUE THREAD

**Issue by wangbf11** [flutter/flutter#155907]
### Steps to reproduce

<img width="262" alt="image" src="https://github.com/user-attachments/assets/6d1bfcf7-75b3-46aa-98eb-7bb09e6d7ead">

### Expected results

<img width="262" alt="image" src="https://github.com/user-attachments/assets/070e1a9a-5bab-4c6c-b9a4-0e5102e84317">

### Actual results

How to deal with it?

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by kjxbyz** [comment]
There have been similar issues on the web page when the language is Chinese.

**Comment by wangbf11** [comment]
> 当网页语言为中文时，也出现过类似的问题。

怎么解决呢

**Comment by darshankawar** [comment]
@wangbf11 
It is not clear what issue are you exactly reporting. You didn't provide any code sample , steps to replicate or proper screenshot.
Please try to fill out requested details from the issue template and in English language so that it is readable and we can properly address it.

Closing for now due to lack of details.

**Comment by wangbf11** [comment]
> @wangbf11 不清楚您具体报告了什么问题。您没有提供任何代码示例、复制步骤或正确的屏幕截图。 请尝试从问题模板中填写所需详细信息并使用英语，以便其可读，我们能够正确解决它。
> 
> 由于缺乏细节，目前关闭。

Every time the H5 page refreshes the text display, it takes 1 second for it to display normally, as shown in the figure
