### ISSUE TITLE
Dart 2 - "implementation limit" requires const or new for most widgets

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#15590]
```
[√] Flutter (Channel master, v0.2.2-pre.55, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.2.2-pre.55
    • Framework revision c640b19167 (7 hours ago), 2018-03-15 07:30:32 -0700
    • Engine revision 520529dbba
    • Dart version 2.0.0-dev.37.0.flutter-7328726088
```

When running (via `flutter run` or vscode) with the `--preview-dart-2` argument I get the following error for most of my widget / class declarations:

```
The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
```

You can see the issue by using the following repo: https://github.com/lukef/cam/tree/dart2 (`dart2` branch)

Screenshot:

![screenshot_1521149022](https://user-images.githubusercontent.com/37941/37493029-cc079fb0-2860-11e8-88f4-3d4a5b0a577e.png)

**Comment by mit-mit** [comment]
cc @kmillikin

**Comment by kmillikin** [comment]
cc @peter-ahe-google

I'm sorry about this.

We discovered that implicit new/const wasn't working correctly in some places where it had to choose between new or const, so we attempted to make just those cases a compile-time error.  This was a temporary measure to ensure that users would not write code depending on our incorrect behavior and get a surprise when we fixed it.

Unfortunately, we disabled the feature in many more contexts than we intended.  We're working on a fix.

**Comment by peter-ahe-google** [comment]
I'm getting started on removing this limitation next week. I've created dart-lang/sdk#32553 which I'll be updating regularly with status.

**Comment by tensor-programming** [comment]
Can anyone comment on when or if the CL 48481 fix has been pushed into flutters version of the dart sdk?

**Comment by tvolkert** [comment]
A bulk of these occurrences should have been fixed by https://github.com/dart-lang/sdk/commit/59d859645ef0557bc7f8e2ee07957f506b755255, which has been picked up by flutter master channel.  However, there's still more work to do - e.g. https://github.com/dart-lang/sdk/issues/32737 was reported this morning against flutter master.

**Comment by mit-mit** [comment]
The master bug for this on the Dart side is https://github.com/dart-lang/sdk/issues/32798

**Comment by zoechi** [comment]
This should be long fixed.
