### ISSUE TITLE
[iOS] Eliminate ARC __bridge casts where possible

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#155943]
During ARC migration in https://github.com/flutter/flutter/issues/137801 we left behind some unfortunate `__bridge` casts. In the interest of safety and readability, we should eliminate these where possible.

**Comment by jmagman** [comment]
Following the link from https://github.com/flutter/engine/blob/033fa28a58bb775a519dc5fde148d5b4dbee3b20/shell/platform/darwin/ios/framework/Source/FlutterEngineGroup.mm#L86-L87
If `self.engines` is swapped to a `[NSPointerArray weakObjectsPointerArray]` maybe the `kFlutterEngineWillDealloc` notification can be totally deleted?

**Comment by cbracken** [comment]
Yep - I was looking at doing just that; the one issue with NSPointerArray is that it doesn't have a remove by value message, just by index. Probably still worth it though.
