### ISSUE TITLE
[Proposal] Prevent hot reload when adding/removing comments

### ISSUE THREAD

**Issue by AbdeMohlbi** [flutter/flutter#155998]
### Use case

Right now, in Flutter, hot reload is triggered even when I add or delete comments in the code. This doesn’t seem necessary since comments don’t change how the code behaves.
consider this code for exemple: 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}
// some comments
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Simple Text App'),
        ),
        body: Center(
          child: Text('Hello, World!'),
        ),
      ),
    );
  }
}

```

### Proposal

 I’m proposing that Flutter skips hot reloads for changes that are only related to comments, which would save some time and make the development process smoother.

**Comment by huycozy** [comment]
From primary triage: This would likely be better suited for [dart-lang/sdk](https://github.com/dart-lang/sdk) repository initially and then we can figure out next steps on framework side. Perhaps the team tool could help, but I'm uncertain.

**Comment by a-siva** [comment]
It needs to do the reload as source positions in the file would change, breakpoints would have to move.
