### ISSUE TITLE
Android notifications aren't received with app closed when Battery optimisation is on standard mode. 

### ISSUE THREAD

**Issue by ccbernardo** [flutter/flutter#155926]
### Steps to reproduce

Just have the app installed, battery optimisation on standard mode. Notifications will only appear when the app is opened. Out app was previously on native code and working normally. 

### Code sample

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  if (message.data["pulse_id_to_delete"] != null) {
    await flutterLocalNotificationsPlugin
        .cancel(int.parse(message.data["pulse_id_to_delete"]));
  } else {
    flutterLocalNotificationsPlugin.show(
        int.parse(message.data["pulse_id"] ?? "0"),
        message.data["title"] ?? "OnePulse",
        message.data["body"] ?? "New Pulses available",
        const NotificationDetails(
            android: AndroidNotificationDetails(
          "Onepulse",
          "Onepulse",
          icon: '@drawable/new_logo',
        )),
        payload: json
            .encode({"data": message.data, "message_id": message.messageId}));
  }
}

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

Android 14

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-GB)
    • Flutter version 3.24.1 on channel stable at /Users/ccbernardo/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (6 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ccbernardo/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • DA8FA6B7-7E3F-461E-B2C9-AD39F67B7643 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93
      darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome
      129.0.6668.60

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
@ccbernardo 
Please report this in dedicated repo: https://github.com/firebase/flutterfire/issues
