### ISSUE TITLE
[Impeller] Opening CupertinoDatePicker on iOS leads to visual glitches and error 'could not find font/glyph position in the atlas'

### ISSUE THREAD

**Issue by victorsanni** [flutter/flutter#155947]
### Steps to reproduce

1. Open an iOS simulator
2. Run sample code
3. Click on the '+' button to open the date picker

### Expected results

Date picker doesn't glitch and has normal behavior.

### Actual results

Date picker glitches severely, scrolling or not.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        DefaultCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        Locale('en', 'EN'),
        //const Locale('ar', 'AR'),
      ],
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  MyHomePageState createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  final int _counter = 0;

  void _incrementCounter() {
    showCupertinoModalPopup(
      context: context,
      builder: (_) => Container(
        height: 190,
        color: const Color.fromARGB(255, 255, 255, 255),
        child: Column(
          children: [
            SizedBox(
              height: 180,
              child: CupertinoDatePicker(
                mode: CupertinoDatePickerMode.date,
                initialDateTime: DateTime.now(),
                onDateTimeChanged: (value) {},
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              const Text(
                'You have pushed the button this many times: ',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/188e9626-4db2-4937-aa20-7f42853ec07e

<img width="374" alt="Screenshot 2024-09-30 at 10 54 47 AM" src="https://github.com/user-attachments/assets/81361111-742c-4d10-a74d-dfaf1fe5652d">

</details>

### Logs

<details open><summary>Logs</summary>

```console
32
[ERROR:flutter/impeller/entity/contents/text_contents.cc(179)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find font in the atlas.
2
[ERROR:flutter/impeller/entity/contents/text_contents.cc(214)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
185
[ERROR:flutter/impeller/entity/contents/text_contents.cc(179)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find font in the atlas.
334
[ERROR:flutter/impeller/entity/contents/text_contents.cc(214)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

Flutter 3.26.0-1.0.pre.271 • channel master • git@github.com:flutter/flutter.git
Framework • revision 3941346723 (7 minutes ago) • 2024-09-30 10:53:08 -0700
Engine • revision f4507e7a4b
Tools • Dart 3.6.0 (build 3.6.0-300.0.dev) • DevTools 2.40.0-dev.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.26.0-1.0.pre.271, on macOS 14.7 23H124 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Victor’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

This channel is intended for Flutter contributors. This channel is not as thoroughly tested as the "beta" and "stable" channels. We do not recommend using this channel for normal use as it more likely to contain serious regressions.

For information on contributing to Flutter, see our contributing guide:
    https://github.com/flutter/flutter/blob/main/CONTRIBUTING.md

For the most up to date stable version of flutter, consider using the "beta" channel instead. The Flutter "beta" channel enjoys all the same automated testing as the "stable" channel, but is updated roughly once a month instead of once a quarter.
To change channel, run the "flutter channel beta" command.
```

</details>

**Comment by victorsanni** [comment]
Related issue: https://github.com/flutter/flutter/issues/153392

**Comment by huycozy** [comment]
Thanks for the report, Victor!

From my end, I also see the issue as reported on Flutter master `3.26.0-1.0.pre.280`, but not on Flutter stable 3.24.3. Checked on `iPhone 16 Pro, iOS 18.0` emulator.

The issue does not occur if I disable Impeller.

### A different visual issue on old iPhone

On both stable and master channels, I see the text is not rendered completely on `iPhone 7, iOS 15.8` (physical device), only the date column shows up rarely when I try to scroll it as video below:

<details>
<summary>Demo video on iPhone 7, iOS 15.8</summary>

https://github.com/user-attachments/assets/53e1369b-3bd7-4973-bcdd-90b2604b9c19
</details>

<details>
<summary>flutter doctor (stable and master)</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-x64, locale en-VN)
    • Flutter version 3.24.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (11 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
```

```console
[!] Flutter (Channel master, 3.26.0-1.0.pre.280, on macOS 15.0 24A335 darwin-x64, locale en-VN)
    • Flutter version 3.26.0-1.0.pre.280 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e6c955416d (3 hours ago), 2024-09-30 20:20:08 -0400
    • Engine revision bfb6dddb2b
    • Dart version 3.6.0 (build 3.6.0-302.0.dev)
    • DevTools version 2.40.0-dev.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```
</details>

**Comment by huycozy** [comment]
I bisected this to https://github.com/flutter/flutter/commit/52d8d0715c48b745666fb74a2c2665d312a2eef6 which is a big roll engine commit

**Comment by zuhabul** [comment]
# flutter doctor --verbose
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-x64, locale en-GB)
    • Flutter version 3.24.3 on channel stable at /Users/zuhabul/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/zuhabul/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] VS Code (version 1.79.0-insider)
    • VS Code at /Users/zuhabul/Downloads/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008101-000A256E0E02001E • ios            • iOS 18.0 22A3354
    • macOS (desktop) • macos                     • darwin-x64     • macOS 15.0 24A335 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 129.0.6668.89

[✓] Network resources
    • All expected network resources are available.

• No issues found!

# Logs

[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find font in the atlas.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find font in the atlas.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find font in the atlas.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find font in the atlas.
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find font in the atlas.

Receiving this error on Stable 3.24.3 as well.

https://github.com/flutter/flutter/issues/153392#issuecomment-2298786173

**Comment by jason-simmons** [comment]
This is due to the `TextFrameDispatcher` culling mechanism added in https://github.com/flutter/engine/commit/11d36ff0503a78cd4656575a2fcac85fde81adc3

The display list built by the `CupertinoDatePicker` is producing `drawTextFrame` operations that are culled by `TextFrameDispatcher` but not `DlDispatcherBase`.  So the atlas is not populated with all the content needed to draw the frames.

`DlDispatcherBase::drawDisplayList` disables culling if the transform has perspective.  `TextFrameDispatcher::drawDisplayList` likely needs to do the same.

@jonahwilliams
