### ISSUE TITLE
 Flutter APK Not Compatible with Client's Samsung S24

### ISSUE THREAD

**Issue by abbskhan** [flutter/flutter#155925]
I’ve generated a Flutter APK that works fine on my phone having android version 14, but when I sent it to my client through Whatsapp, who is using a Samsung S24, they received the error: "App not installed App not compatible with your phone."

Details:

Target SDK Version:  34
Min SDK Version: 21
Build Type: APK (Release)
Steps to Reproduce:
I generated a release APK using the following command:
flutter build apk --release --split-per-abi --no-shrink

The APK works as expected on my device.
I sent the APK via WhatsApp to my client, who is using a Samsung S24.
Upon trying to install, the client received the error: "App not installed App not compatible with your phone."
What I’ve Tried:
Verified that the APK works on other devices.
Checked that the minSdkVersion and targetSdkVersion are compatible with the client’s device.

The app should install and run successfully on the Samsung S24.

Actual Behavior:
The client receives the error: "App not installed App not compatible with your phone."

Additional Information:
Client’s device: Samsung S24
Distribution method: APK sent via WhatsApp 
Questions:
Are there any known issues with Flutter APK compatibility on Samsung devices, specifically the S24?
Could there be a problem related to ABI or SDK versioning that I might be missing?
Any guidance or suggestions would be greatly appreciated!

**Comment by darshankawar** [comment]
@abbskhan 
Does S24 has Android 14 version ? Can you provide S24 device details (OS version) if not 14 ?


> the client received the error: "App not installed App not compatible with your phone."

Is it possible to get more details about it ? example, the error log if any ?

This may also be an issue S24, as I see similar thread here about it https://www.reddit.com/r/samsunggalaxy/comments/19evjr3/s24_old_app_not_compatible/ and https://www.reddit.com/r/oneui/comments/19eq6nt/unable_to_install_apks_in_the_samsung_s24/

**Comment by abbskhan** [comment]
![IMG-20241001-WA0002](https://github.com/user-attachments/assets/6f9f46f1-06b7-42c3-a3fd-5b81ee6928f7)

the android version is 14 and the app is working on other phones having android version 14 but didnt install on s24+

**Comment by darshankawar** [comment]
> This may also be an issue S24, as I see similar thread here about it https://www.reddit.com/r/samsunggalaxy/comments/19evjr3/s24_old_app_not_compatible/ and https://www.reddit.com/r/oneui/comments/19eq6nt/unable_to_install_apks_in_the_samsung_s24/

Did you get a chance to look at these links and try any solutions mentioned in them ?

**Comment by abbskhan** [comment]
Yeah,i have looked that conversations.
the main conclusion was 
 it seems like s24 is 64 bit arch cpu and these apps are all 32 bit.
 and the 
 adb install --bypass-low-target-sdk-block GD.apk


how can i check that my apk is 32 bit or 64

**Comment by darshankawar** [comment]
Can you try by running `flutter build apk --release --target-platform=android-arm64` and then share this apk to the client and check if it works ?

**Comment by abbskhan** [comment]
sure ill do it like this if i got back to work will inform you then
and thanks alot for your time

**Comment by xRidney** [comment]
Any news on that?

I'm having the same issue and I've tried:
`flutter build apk --target-platform=android-arm64 --obfuscate --split-debug-info=$debugInfoFolder
`
