### ISSUE TITLE
GOOGLE.COM not working in webview

### ISSUE THREAD

**Issue by james-rosales** [flutter/flutter#155984]
### Steps to reproduce

Copy and paste code to VSCODE

### Expected results

should show google.com in webview

### Actual results

![image](https://github.com/user-attachments/assets/09cab22b-5227-4236-8847-6f3a32097fd4)

### Code sample

Webview Body Code

```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:webview_flutter_platform_interface/webview_flutter_platform_interface.dart';
import 'package:white_label/pages/web_view/web_view.dart';

class WebViewBody extends StatefulWidget {
  const WebViewBody({super.key});

  @override
  State<WebViewBody> createState() => _WebViewBodyState();
}

class _WebViewBodyState extends State<WebViewBody> {
  late final PlatformWebViewController _controller;

  @override
  void initState() {
    super.initState();
    var bloc = context.read<WebViewBloc>();
    _controller = PlatformWebViewController(
      const PlatformWebViewControllerCreationParams(),
    )..loadRequest(
        LoadRequestParams(
          uri: Uri.parse(bloc.state.url ?? ''),
        ),
      );
  }

  @override
  Widget build(BuildContext context) {
    return PlatformWebViewWidget(
      PlatformWebViewWidgetCreationParams(controller: _controller),
    ).build(context);
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version
    10.0.22631.4169], locale en-PH)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.93.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by huycozy** [comment]
Hi @james-rosales 
The given sample code contains 3rd package and is incomplete. Please try the [package simple sample code](https://github.com/flutter/packages/blob/main/packages/webview_flutter/webview_flutter/example/lib/simple_example.dart) to see if the issue also occurs. You should also try opening Google site on device's browser to see if it's up or not as well.

**Comment by james-rosales** [comment]
I am using this package
https://pub.dev/packages/webview_flutter_platform_interface and I am
implementing it in flutter web, the other websites works. But the google.com
doesn't.

**Comment by huycozy** [comment]
I use this complete sample code but the google site loads as desired on my Android device. Please try with this code and confirm the result.

And again, you should also try opening Google site on device's browser to see if it's up or not as well.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter_platform_interface/webview_flutter_platform_interface.dart';

void main(List<String> args) {
  runApp(const MaterialApp(home: WebViewBody()));
}

class WebViewBody extends StatefulWidget {
  const WebViewBody({super.key});

  @override
  State<WebViewBody> createState() => _WebViewBodyState();
}

class _WebViewBodyState extends State<WebViewBody> {
  late final PlatformWebViewController _controller;

  @override
  void initState() {
    super.initState();
    _controller = PlatformWebViewController(
      const PlatformWebViewControllerCreationParams(),
    )..loadRequest(
        LoadRequestParams(
          uri: Uri.parse('https://www.google.com/'),
        ),
      );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PlatformWebViewWidget(
        PlatformWebViewWidgetCreationParams(controller: _controller),
      ).build(context),
    );
  }
}
```
</details>

**Comment by stuartmorgan** [comment]
> I am using this package https://pub.dev/packages/webview_flutter_platform_interface

That package is an implementation detail of the federated plugin, and we do not provide support for direct client use of it. Is there a reason you are bypassing the `webview_flutter` package that is intended for client use?

**Comment by james-rosales** [comment]
Still not working with your code

**Comment by huycozy** [comment]
@james-rosales Kindly answer all questions mentioned above to expedite the progress of the issue.
