### ISSUE TITLE
[Impeller] Production issue. Blank screen on navigation. Impeller errors seen, logs provided.

### ISSUE THREAD

**Issue by codyfilatov** [flutter/flutter#155995]
### Steps to reproduce

I have 8 users who have reported this behavior, I have only been able to replicate it every now and then using LabbdaTest's Galaxy S9 "real-device" using Android 10. Sometimes navigation succeeds for me, sometimes it doesn't. Seems 50/50, although other users can reproduce the problem 100% of the time.

As far app flow.

- Create any Widget with a Scaffold, let's make it blue. Stick it in a MaterialApp.
- Create any other Widget, lets make it red. Add a Center(child: Text('Hello')).
- Navigate from the blue widget to the red widget using Navigator.of(context).pushReplacement()

### Expected results

Using the examples above, I expect to see navigation from blue to red with the "Hello" text in the center.

### Actual results

I see the navigation from blue to red, except there is no text in the center... and logs are printing many errors related to impeller eventually repeatedly spamming

```
10-01 13:01:57.309 16165 18422 E flutter : [ERROR:flutter/impeller/base/validation.cc(59)] Impeller validation: Fence wait failed: Timeout
10-01 13:01:57.309 16165 18422 E flutter : [ERROR:flutter/impeller/base/validation.cc(59)] Impeller validation: Could not wait for fence.
10-01 13:01:57.309 16165 18422 E flutter : [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(66)] No surface available.
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {

  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      home: const Red(),
    );
  }
}

class Red extends StatefulWidget {
  const Red({super.key});
  @override
  _RedState createState() => _RedState();
}
class _RedState extends State<Red> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      body: GestureDetector(
        onTap: () => _onTap(),
        child: Center(
          child: Text('Page 1')
        ),
      )
    );
  }

  _onTap(){
    PageRouteBuilder route = PageRouteBuilder(pageBuilder: (context, animation, secondaryAnimation) => const Blue());
      Navigator.of(context).pushReplacement(route);
  }
}

class Blue extends StatefulWidget {
  const Blue({super.key});
  @override
  _BlueState createState() => _BlueState();
}
class _BlueState extends State<Blue> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.blue,
      body: Center(
        child: Text('Hello')
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>
</details>
[logs.txt](https://github.com/user-attachments/files/17210205/logs.txt)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4169], locale en-US)
    • Flutter version 3.24.3 on channel stable at C:\Programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\codyf\AppData\Local\Android\sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35312.102
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.5
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.93.1)
    • VS Code at C:\Users\codyf\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] Connected device (4 available)
    • SM G998U (mobile) • R5CRB1E04GT • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22631.4169]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 124.0.6367.156
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 129.0.2792.65

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @codyfilatov 
I tried the code sample on S10+ device running Android 12 but didn't get to see the reported behavior.
By running with Impeller enabled, it properly navigated to next screen and showed `Hello` text in the center and printed below log in console:

```
Running Gradle task 'assembleRelease'...                          135.3s
✓ Built build/app/outputs/flutter-apk/app-release.apk (17.4MB)
Installing build/app/outputs/flutter-apk/app-release.apk...      2,791ms

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (29863): [IMPORTANT:flutter/shell/platform/android/android_context_vulkan_impeller.cc(67)] Using the Impeller rendering backend (Vulkan).

```



> I have 8 users who have reported this behavior

Is your app Impeller enabled in production ?

> I have only been able to replicate it every now and then using LabbdaTest's Galaxy S9 "real-device" using Android 10.

Is it a device lab ? And were you running with Impeller enabled in release or in debug mode ?

**Comment by codyfilatov** [comment]
> Thanks for the report @codyfilatov I tried the code sample on S10+ device running Android 12 but didn't get to see the reported behavior. By running with Impeller enabled, it properly navigated to next screen and showed `Hello` text in the center and printed below log in console:
> 
> ```
> Running Gradle task 'assembleRelease'...                          135.3s
> ✓ Built build/app/outputs/flutter-apk/app-release.apk (17.4MB)
> Installing build/app/outputs/flutter-apk/app-release.apk...      2,791ms
> 
> Flutter run key commands.
> h List all available interactive commands.
> c Clear the screen
> q Quit (terminate the application on the device).
> I/flutter (29863): [IMPORTANT:flutter/shell/platform/android/android_context_vulkan_impeller.cc(67)] Using the Impeller rendering backend (Vulkan).
> ```
> 
> > I have 8 users who have reported this behavior
> 
> Is your app Impeller enabled in production ?
> 
> > I have only been able to replicate it every now and then using LabbdaTest's Galaxy S9 "real-device" using Android 10.
> 
> Is it a device lab ? And were you running with Impeller enabled in release or in debug mode ?

Hello, so this is tough for me to describe. As I said I was only able to reproduce on a Galaxy S9 device running Android 10, and half the time it worked. Although reported users constantly have the issue. Those users were using Galaxy 9, Note 9, both running Android 10 and one  iPhone 15 Pro Max device on iOS 18 beta.

Yes this is in production with impeller enabled (I had it as true in manifest) on a release build, on the store. It could also be replicated by users with a direct APK install (sent for testing). I never attempted in debug. Again I personally couldnt replicate outside of LambdaTest's real Galaxy S 9 service.

I have attached three videos. One of the user report for the white screen they see, one with the red and blue test described where the second screen is not loading any widgets, and finally the expected output in production

Impeller in production has been disabled for us because of this issue on both iOS and Android.

https://github.com/user-attachments/assets/07d89305-d0d3-413c-b5f9-7454a27d2cab


https://github.com/user-attachments/assets/5059cd22-0765-4e67-909d-7369f484461b


https://github.com/user-attachments/assets/61a07aec-85fd-4ff5-8771-b579e0eb94e8

**Comment by darshankawar** [comment]
Maybe your case is similar or closely related to https://github.com/flutter/flutter/issues/154103 which was fixed recently.
Is there a way for you to switch to latest master and re-run your scenario on same setup to see if you still get same reported behavior or not ?
