### ISSUE TITLE
Bug on Android with tiktok link

### ISSUE THREAD

**Issue by quocviet1996** [flutter/flutter#155918]
### Steps to reproduce

Open tiktok link https://www.tiktok.com/@metadoc.vn/video/7171635924302957826 on Android face this issue, IOS is just fine

### Expected results

![image](https://github.com/user-attachments/assets/2c28fc71-98cd-4432-a850-13031598c8c3)

### Actual results

![image](https://github.com/user-attachments/assets/69e7d206-64e9-4c58-9395-68644effd488)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';


class WebViewScreen extends StatefulWidget {
  String url = '';
  String title = '';

  WebViewScreen({super.key, required this.url, required this.title});

  @override
  State<WebViewScreen> createState() => _WebViewScreenState();
}

class _WebViewScreenState extends State<WebViewScreen> {
  int _progress = 0;
  late WebViewController _controller;

  @override
  void initState() {
    // TODO: implement initState
    init();
    super.initState();
  }

  init() async {
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
            print(progress);
            setState(() {
              _progress = progress;
            });
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onHttpError: (HttpResponseError error) {},
          onWebResourceError: (WebResourceError error) {},
        ),
      )
      ..loadRequest(Uri.parse(widget.url));
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: _progress < 100
          ? const Center(
              child: CircularProgressIndicator(color: Colors.black),
            )
          : WebViewWidget(controller: _controller),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@quocviet1996 
`ERR_UNKNOWN_URL_SCHEME` usually indicates the url is not valid. So check the same and make sure the link is valid. Does it open properly if you directly access it ?
Also, in order to properly address the issue, provide minimal but complete reproducible code sample without third party package implementation.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by quocviet1996** [comment]
> https://www.tiktok.com/@metadoc.vn/video/7171635924302957826

Thanks you, and yes, i can directly open this link, and i have prodive minimal code for this, please check this out.

**Comment by quocviet1996** [comment]
> @quocviet1996 `ERR_UNKNOWN_URL_SCHEME` usually indicates the url is not valid. So check the same and make sure the link is valid. Does it open properly if you directly access it ? Also, in order to properly address the issue, provide minimal but complete reproducible code sample without third party package implementation.
> 
> https://stackoverflow.com/help/minimal-reproducible-example

Thanks you, and yes, i can directly open this link, and i have prodive minimal code for this, please check this out.
Also this link fb is broken too: https://www.facebook.com/groups/5097678227028214/?hoisted_section_header_type=recently_seen&multi_permalinks=8176416499154356

**Comment by darshankawar** [comment]
Does the same links work with native Android app ?

**Comment by quocviet1996** [comment]
> Does the same links work with native Android app ?

Yes, it's work properly

**Comment by darshankawar** [comment]
Try https://stackoverflow.com/questions/70921109/fix-neterr-unknown-url-scheme-whatsapp-link-on-flutter-webview to see if it helps in your case or not.

**Comment by quocviet1996** [comment]
"Based on your suggestion, I switched to using launchUrl, which opens the link in a browser and works effectively. However, if I still want to use WebView, what can i do? thanks

> Try https://stackoverflow.com/questions/70921109/fix-neterr-unknown-url-scheme-whatsapp-link-on-flutter-webview to see if it helps in your case or not.

**Comment by darshankawar** [comment]
@quocviet1996 
Does it work on a physical device ? Can you also try using [this](https://pub.dev/packages/flutter_inappwebview/install) package to check if it works or not using it ?

**Comment by quocviet1996** [comment]
> @quocviet1996 Does it work on a physical device ? Can you also try using [this](https://pub.dev/packages/flutter_inappwebview/install) package to check if it works or not using it ?

I tried it, unfortunately I got the same error, because when I open the tiktok or facebook link on my android phone, it will automatically redirect to another string link instead of a normal website, so it will lead to the error.I think any plugin will have the same error

**Comment by darshankawar** [comment]
Check [this](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1748#issuecomment-1803940031) to see if it helps.
