### ISSUE TITLE
`CarouselView` feedback on its limitations

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#155903]
I spent the weekend playing with CarouselView and loved it, but found several limitations that make it harder to use:
- There is no way to disable `onTap`. It is common for some carousels have buttons inside them (such as Instagram/Tiktok).
- CarouselController has no way to jump to a specific page. This package (https://pub.dev/packages/carousel_slider) has some very helpful methods:
`.nextPage({Duration duration, Curve curve})`
`.previousPage({Duration duration, Curve curve})`
`.jumpToPage(int page)`
`.animateToPage(int page, {Duration duration, Curve curve})`
- carousel_slider suffer from the same issue, but mouse scrolling with `scrollDirection: Axis.vertical` is super buggy/laggy. You are fighting with the framework. 
- `flexWeights` only accept int[]. You might wonder "why" would I need double: I have a 1:1 aspect ratio content and I want the Carousel to "fill" the edges. I can't do this with ints because it is a big jump from one to the other.
- Maybe this is too advanced, but I miss a way to coordinate the items. I would like to show a certain content when not expanded, then another when expanded, and coordinate the transition between them. The idea is that I show the alt description when "compact", but the image when expanded (the image only really works when 1:1, so I would make it fade/expand on the animation). A way to deal with animation/tweens/curves could be very helpful.

**Comment by darshankawar** [comment]
@bernaferrari Thanks for the report. 
It will be better to separate out each feedback so that they can be tracked and addressed properly. So I suggest you to file separate issue for each bullet point.

A current issue with `onTap` that you can check for reference https://github.com/flutter/flutter/issues/154701

**Comment by bernaferrari** [comment]
Okay. I'll do. I didn't want to pollute, was thinking more on umbrella kind of issue.
