### ISSUE TITLE
RichText support for inheriting TextStyles automatically

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#15594]
From discussing with g3 Flutter users, there's interest in styling RichTexts with an inherited text style by default.

Not doing this is leading some users into unexpected differences between RichText and Text, such as #14675.

Would we be willing to simplify the API to inherit TextStyles in RichText?  Could this even be the default behavior of RichText, so that it produces results similar to Text by default?

**Comment by jonahwilliams** [comment]
@DaveShuckerow I just added a [Text.rich](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/text.dart#L218) constructor which inherits styles (but still allows specifying them per span).  I _believe_ this would cover the use case listed

**Comment by tvolkert** [comment]
@jonahwilliams is this done then?

**Comment by jonahwilliams** [comment]
@tvolkert Should be, unless there are additional requests

**Comment by tvolkert** [comment]
Paging @paolosoares

**Comment by zoechi** [comment]
This issue appears stale.
