### ISSUE TITLE
Flutter: Debugger not working, breakpoints disabled when application run in debug mode

### ISSUE THREAD

**Issue by akabisdev** [flutter/flutter#155924]
A very strange behaviour I encountered while debugging one of my flutter project, in this very specific project I am not able to debug, if I add breakpoints in the project and start debugging the app, it will automatically disabled the breakpoints.

![image](https://github.com/user-attachments/assets/0fc0586b-9a91-4af7-aa5b-a60a4fef6e10)

However, if I add breaking point in the `main.dart` file, it is working at that point :

![image](https://github.com/user-attachments/assets/1e35f19c-eadb-442e-b122-6270624900f2)

But the breaking points are not working on any other file.

Things I have tried :

* Flutter clean, Invalidate cache and restart
* Update flutter version, earlier project was working with flutter 3.3.10, I updated it to work with flutter 3.22.2
* Also tried with latest flutter sdk v3.24.3
* Update flutter plugin used in android studio (earlier i was using 80.0.2, which i upgraded to 81.0.2).

My other flutter projects works fine. Let me know if any other information is required from my side.

Any help would be much appreciated..

Thanks in advance

**Comment by darshankawar** [comment]
@akabisdev 
I think your question / issue is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
