### ISSUE TITLE
[Web] Chinese characters are momentarily displayed in garbled form when loading initially

### ISSUE THREAD

**Issue by kjxbyz** [flutter/flutter#155927]
### Steps to reproduce

Chinese characters are displayed in garbled form.

I'm not sure if it's [slang](https://pub.dev/packages/slang) that's causing the issue.

### Expected results

Chinese is displayed normally.

### Actual results

Chinese characters are displayed in garbled form.

<img width="1144" alt="2024-09-30 19 29 10" src="https://github.com/user-attachments/assets/24ba106c-2816-4d2b-8363-aa7680ee34f6">

After a while, it will show normal.

<img width="1160" alt="2024-09-30 19 29 25" src="https://github.com/user-attachments/assets/59e395e3-9e4f-40da-8d17-3455cd4e4a1e">

### Code sample

<details open><summary>Code sample</summary>

https://github.com/kjxbyz/chinese_fonts_issues

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.24.3 on channel stable at /Users/ying/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 周前), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/ying/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_SDK_ROOT = /Users/ying/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • Kimmy's iPhone (mobile) • 00008020-000A1D110A32002E • ios            • iOS 18.0 22A3354
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 15.0 24A335 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 129.0.6668.71

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @kjxbyz 
I ran your project and used Chinese on Chrome but couldn't see the issue:

<details>
<summary>Demo screenshot/video</summary>

![Screenshot 2024-10-01 at 12 32 38](https://github.com/user-attachments/assets/e539eefd-7858-4293-850c-817fdf7c12bb)
</details>

Can you try using [intl](https://pub.dev/packages/intl) to see if this is an issue with [slang](https://pub.dev/packages/slang) or not?

**Comment by kjxbyz** [comment]
1. Have you set `Preferred languages` ​​to `Chinese (Simplified)`?

<img width="1126" alt="2024-10-01 13 42 42" src="https://github.com/user-attachments/assets/69944335-b3e3-47f3-96a6-22a64a04f097">

2. The garbled characters are displayed for a very short time, so you need to record the screen and then view it frame by frame.

3. I will switch to [intl](https://pub.dev/packages/intl) to see if this is the issue.

**Comment by huycozy** [comment]
Thanks for checking with `intl` and providing the updated sample code.

>Have you set Preferred languages ​​to Chinese (Simplified)?

Yes, this is the way I set the display language on Chrome.

You are right, I can see the issue momentarily when the web loads at the first frame. The issue also occurs on Flutter master channel `3.26.0-1.0.pre.307`.

<details>
<summary>Demo gif on Chrome</summary>

![Screen Recording 2024-10-02 at 10 21 37](https://github.com/user-attachments/assets/7987ee79-776d-4fd2-8a74-41a84d93c19c)
</details>

I also tried the macOS app, on Language & Region settings > Preferred languages, but the issue didn't appear there.

**Comment by kjxbyz** [comment]
This issue is not found on mobile and desktop.

**Comment by amake** [comment]
I think the default fonts don't include many characters outside of ASCII, so it needs to download additional fonts. This is not specific to Chinese; you can get the same issue with emoji.

Basically I think this is a dup of #76248

**Comment by yjbanov** [comment]
Deduplicating into https://github.com/flutter/flutter/issues/138288
