### ISSUE TITLE
assertion failure

### ISSUE THREAD

**Issue by rohanfalcon** [flutter/flutter#155953]
### Steps to reproduce

 ```
@override
    build(BuildContext context) {
      return Scaffold(
        body: Center (
          child: FutureBuilder<String> (
            future:  _onValidate(context) ,
            builder: (context,snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const CircularProgressIndicator(); // Loading indicator
              } else if (snapshot.hasError) {
                return Text('Error: ${snapshot.error}');
              } else {
                return Text(snapshot.data ?? 'No data'); // Display the data
              }
            }
```

### Expected results

New widget to be launched from a future

### Actual results

error after widget launched

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@rohanfalcon 
What assertion failure are you getting ? Can you provide entire error log ?
Also, provide complete runnable code sample along with `flutter doctor -v`.
