### ISSUE TITLE
Clicking a disabled `SearchBar` opens the search view

### ISSUE THREAD

**Issue by ndonkoHenri** [flutter/flutter#156077]
### Steps to reproduce

1. Run the code
2. Click on the disabled bar and notice that the searchview opens up

### Expected results

The Bar is disabled, so I expect it not to respond to clicks as mentioned in the docs.

### Actual results

Clicking on the disabled searchbar triggers an opening of the searchview even though `onTap` is `null`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [SearchBar].

void main() => runApp(const SearchBarApp());

class SearchBarApp extends StatefulWidget {
  const SearchBarApp({super.key});

  @override
  State<SearchBarApp> createState() => _SearchBarAppState();
}

class _SearchBarAppState extends State<SearchBarApp> {
  bool isDark = false;

  @override
  Widget build(BuildContext context) {
    final ThemeData themeData = ThemeData(
        useMaterial3: true,
        brightness: isDark ? Brightness.dark : Brightness.light);

    return MaterialApp(
      theme: themeData,
      home: Scaffold(
        appBar: AppBar(title: const Text('Search Bar Sample')),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SearchAnchor(
              builder: (BuildContext context, SearchController controller) {
            return SearchBar(
              enabled:false,
              controller: controller,
              padding: const MaterialStatePropertyAll<EdgeInsets>(
                  EdgeInsets.symmetric(horizontal: 16.0)),
              onTap: null,
              onChanged: (_) {
                controller.openView();
              },
              leading: const Icon(Icons.search),
              trailing: <Widget>[
                Tooltip(
                  message: 'Change brightness mode',
                  child: IconButton(
                    isSelected: isDark,
                    onPressed: () {
                      setState(() {
                        isDark = !isDark;
                      });
                    },
                    icon: const Icon(Icons.wb_sunny_outlined),
                    selectedIcon: const Icon(Icons.brightness_2_outlined),
                  ),
                )
              ],
            );
          }, suggestionsBuilder:
                  (BuildContext context, SearchController controller) {
            return List<ListTile>.generate(5, (int index) {
              final String item = 'item $index';
              return ListTile(
                title: Text(item),
                onTap: () {
                  setState(() {
                    controller.closeView(item);
                  });
                },
              );
            });
          }),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

I used dartpad based on Dart SDK 3.5.3 and Flutter SDK 3.24.3

</details>

**Comment by danagbemava-nc** [comment]
Hi @ndonkoHenri, on the master channel, the `SearchAnchor` has a property which disables opening the view. See https://github.com/flutter/flutter/pull/153256

Does this suffice for your use case? Since the SearchBar is built in the `SearchAnchor`, I think without disabling the anchor, the bar will still receive input

**Comment by ndonkoHenri** [comment]
Thanks for the quick response. I tried it and it worked.

> Since the SearchBar is built in the SearchAnchor, I think without disabling the anchor, the bar will still receive input

Just one question: even if the bar receives input in this case, why is the view automatically opened though `onTap` is `null`. With an enabled bar, this won't happen.

**Comment by danagbemava-nc** [comment]
Hi @ndonkoHenri, from what I see in the source code, the anchor has a GestureDetector that calls openView on tap. If the search bar is enabled, the textfield captures the tap event so it doesn't open but if the search bar is disabled there's nothing to capture the input so the view opens.

https://github.com/flutter/flutter/blob/e7c993d7f96d6b10a061b34258115eca0e9d064c/packages/flutter/lib/src/material/search_anchor.dart#L483-L494

Does this help?
