### ISSUE TITLE
Flutter doctor running failed

### ISSUE THREAD

**Issue by erwinmendrofa** [flutter/flutter#15609]
How to solve this ???
Flutter doctor can't run.
[flutter_01.log](https://github.com/flutter/flutter/files/1819158/flutter_01.log)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] VS Code (version 1.21.0)
CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: ab13bf71e832edbf)
CreateProcessW failed 193
Crash report written to C:\Users\Erwin SM\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by jonahwilliams** [comment]
The error message is `ProcessException: ProcessException: %1 is not a valid Win32 application.`  This happens when trying to launch adb here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L555

@erwinmendrofa what happens when you run `adp` or `where adb`?

**Comment by erwinmendrofa** [comment]
I just want to install adb on my computer

**Comment by DanTup** [comment]
Do you still see this? Based on https://github.com/flutter/flutter/issues/9976#issuecomment-365051558 this should be fixed; however the date on those comments seems like before v0.1.5 was released so I'm not so sure. Also have a report at https://github.com/flutter/flutter/issues/18938 but it's not clear what version of Flutter that is.

I cannot repro issues with spaces in my Android SDK paths using master on Windows 10.

**Comment by lwinaungmoe** [comment]
I have same issue
