### ISSUE TITLE
Hard to use common finders

### ISSUE THREAD

**Issue by deonchimple** [flutter/flutter#15606]
## Steps to Reproduce

The finder options available to QAs are a bit limited. I understand there is a package 'finders.dart' which has loads of finders but they don't let you perform actions on it like Tap, getText, etc. 

Another function 'CollectAllFrom' shows up after importing the necessary files but it doesnot take any finders.

## Logs

The application runs fine with flutter run. I am trying to automated the testing.

## Flutter Doctor

[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 0.1.5 at C:\Users\Deon\Documents\Flutter\flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.21.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.

**Comment by Hixie** [comment]
The WidgetTester lets you do things like tap and drag and so on. Those methods take finders as arguments. Does that answer your question? If not, please can you elaborate on what exactly is the problem you want us to solve? Thanks.
