### ISSUE TITLE
Load time increased unlike before

### ISSUE THREAD

**Issue by iamevaristus** [flutter/flutter#156022]
Hi, I recently discovered that my app now takes much time to load unlike before. The code at the app initialization is still the same but the load time has increased incessantly, and it is troubling since my apps are up for review currently.

When I run `flutter run --verbose`, I get this as part of the logs:
```
[GETX] Instance "MainConfiguration" has been created
[GETX] Instance "MainConfiguration" has been initialized
[+2575 ms] I/TRuntime.CctTransportBackend(22397): Status Code: 200
[+27484 ms] I/Choreographer(22397): Skipped 1800 frames!  The application may be doing too much work on its main thread.
```

Sometimes, the `Skipped frames` part might even log twice.

I would like to know what is happening so that I can continue my app review on app gallery.

**Comment by iamevaristus** [comment]
Flutter version: 3.24.3
Platform: Android

**Comment by darshankawar** [comment]
> Also, in order to properly address the issue, please try to provide minimal reproducible code sample (without third party implementation) that still shows increased load time. It may be a factor that you are using external dependencies.

Please provide this as well.

**Comment by iamevaristus** [comment]
I cannot produce the code sample without the third party implementation.

**Comment by darshankawar** [comment]
Try to see what changes in your implementation could be causing it and if you think it is coming from framework itself, provide relevant details so that we can take a look.

**Comment by iamevaristus** [comment]
I've been able to figure out the problem. Turns out that one of the packages am using was causing the issue.

Thanks
