### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by kimathikim** [flutter/flutter#156075]
## Command
```sh
flutter run
```

## Error

[ERROR:flutter/runtime/dart_isolate.cc(147)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(549)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(690)] Could not launch engine with configuration.

**Comment by kimathikim** [comment]
Kildly someone to look into this

**Comment by kimathikim** [comment]
Was soo often for the 2 days. Fixed the issue. Though. Thanks.

**Comment by danagbemava-nc** [comment]
We would like to investigate and fix the root cause of the issue so if you experience this again, please file a new issue and provide detailed information. 

Thank you
