### ISSUE TITLE
[bug report] image_picker compress the video when using ImagePicker().pickVideo(source: ImageSource.gallery) on iOS and there is no option to get video metadata (like picking images) or uncompressed videos

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#156009]
https://github.com/user-attachments/assets/5197fb25-fdf5-4fbe-9852-8e2f879a0b97

**Comment by huycozy** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/24954. Please follow it for updates.
