### ISSUE TITLE
does flutter work on raspberry pi ?

### ISSUE THREAD

**Issue by arun-gautham** [flutter/flutter#156128]
Really ? or am I just my time with flutter?

is it really runnable flutter on ARM ?? 
Ubuntu on raspberry pi

Note: Flutter_pi doesn't serve my purpose ...

**I don't see ARM64 in flutter docs ( for linux )**

Flutter snap is all broken 
I just keep. getting error 
/snap/flutter/current/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/9/liblto_plugin.so: error loading plugin: /snap/flutter/146/usr/bin/../../lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/gcc/aarch64-linux-gnu/9/liblto_plugin.so)

if it doesn't work please do be open about it ... and tell no it doesn't work ...

**Comment by danagbemava-nc** [comment]
Official support for Raspberry pi is being tracked in https://github.com/flutter/flutter/issues/35042

Kindly follow up in the issue linked above for updates. 

Any issues you face with flutter snap should be reported on its repo. 

Closing from here. 

Thank you
