### ISSUE TITLE
Error: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH environment variable.

### ISSUE THREAD

**Issue by ChandanJS** [flutter/flutter#156102]
### Steps to reproduce

Please help in installation on flutter environment in my win-10 OS machine.

### Actual results

1. downloaded git & installed it successfully
2. downloaded flutter sdk & the copied & extracted in C:/src/flutter
3. then opened the flutter console to test whether all files are extracted.

 Error: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try again after restarting the terminal and/or IDE.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```
Unhandled exception:
Error: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try again after restarting the terminal and/or IDE.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:511:7)
#2      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:103:43)
#3      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:131:46)
#4      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:155:36)
#5      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#6      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#7      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#8      AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#9      androidSdk (package:flutter_tools/src/globals.dart:71:39)
#10     generateCommands (package:flutter_tools/executable.dart:191:25)
#11     main.<anonymous closure> (package:flutter_tools/executable.dart:95:11)
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:53:13)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

</details>

**Comment by danagbemava-nc** [comment]
Hi, Thanks for filing this issue.
From the error message:

```
Error: Cannot find the executable for where. This can happen if the System32 folder (e.g.
C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try
again after restarting the terminal and/or IDE.
```

Kindly ensure you follow the exact step-by-step process in setting up flutter on your system. More specifically to update your PATH, see [docs.flutter.dev/get-started/install/windows#update-your-path](https://docs.flutter.dev/get-started/install/windows#update-your-path)

Please ensure that you have `C:\Windows\System32` in your path. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
