### ISSUE TITLE
FirebaseAnimatedList won't update if app goes in background

### ISSUE THREAD

**Issue by PrimeNexes** [flutter/flutter#15611]
FirebaseAnimatedList won't update if app goes in background , when you navigate it gets updated.

**Comment by Hixie** [comment]
What do you mean by "background"? Still visible but with another app on top, or not visible at all?

**Comment by PrimeNexes** [comment]
As far as I remember now , when put you app in pause state ( Press Home ) and when you resume the list won't update.

**Comment by kroikie** [comment]
@PrimeNexes

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/886. Any further collaboration will be done there.
