### ISSUE TITLE
Release the Gallery on the App Store

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15618]

**Comment by milhomem** [comment]
I've spent some time trying to find it on AppStore and I couldn't. I was following the auto-build process with Fastlane and was pretty sure this was published already.

What's missing here? Can I help somehow?

**Comment by pedromassangocode** [comment]
Does this still a valid issue? it has been three years now without updates on this. 

Unless the Gallery app will include more functionalities, right now it may get rejected on App Store accordingly to the guidelines described here: https://developer.apple.com/app-store/review/guidelines/#minimum-functionality.

**Comment by guidezpl** [comment]
@pedromassangocode that's right, it was rejected initially, and even after we added functionality (source code viewing, copying, etc.) it was still considered a demo app. As such, closing this issue.
