### ISSUE TITLE
Tickers sometimes report "negative time"

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#156120]
I was going back and forth about whether to make an issue for this, since it's very infrequent and thus difficult to reproduce.
But once in a blue moon, the animation controller's `assert(duration.inMicroseconds > 0)` evaluates to `false`, seemingly for no reason.

<br>

Based on what I saw on Discord recently, maybe tracking this down won't be as difficult as I thought?

cc: @jtmcdole

**Comment by jtmcdole** [comment]
Duplicate of #106277 ?

**Comment by jtmcdole** [comment]
If you have a way of reproducing this I would love to not pull out my hair anymore

**Comment by jtmcdole** [comment]
If you have a way of reproducing this I would love to not pull out my hair anymore

**Comment by nate-thegrate** [comment]
The only solution that has allowed me to stop pulling my hair out is: to be bald 👨‍🦲

(closing as duplicate)
