### ISSUE TITLE
Issue from website page Get Started: Configure Editor

### ISSUE THREAD

**Issue by syedliya3** [flutter/flutter#15615]
From URL: https://flutter.io/get-started/editor.md

There is no option to include the flag --enable-software-rendering . which is required  if there is a gpu fault. now I cant use vscode for this.

**Comment by theamberlies** [comment]
thanks the issue is solved now.. that syedliya3 guy was me!

**Comment by DanTup** [comment]
Yep, this is the correct way to pass custom args to flutter using VS Code. Thanks @xqwzts!
