### ISSUE TITLE
iOS engine out directory contains large `clang_arm64/obj/third_party/vulkan-deps` copy

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#156180]
engine `out/ios_debug_unopt/clang_arm64/obj/third_party/vulkan-deps` is almost 2 GB.  

I don't think `vulkan-deps` would be needed for iOS, but it's getting pulled in with `clang`.  Is there any way to prevent this from being written?  

cc @chinmaygarde

**Comment by chinmaygarde** [comment]
> I don't think vulkan-deps would be needed for iOS 

The dependencies seem to be coming from `impellerc`. The [Stage 1 compiler and optimizer](https://github.com/flutter/engine/tree/9fa363bdde2085893f5802890ef4ce67753dfd77/impeller#the-offline-shader-compilation-pipeline) uses SPIRV as an intermediate before MSL conversion. So yes, iOS doesn't need it at runtime. But those dependencies are used during the construction of MSL at build time.

I should say the GN rules aren't great there are multiple targets that generate archives we don't need that end up inflating size of artifacts on disk. But those rules are vended by third parties. We could go an tinker on them for modest size reductions or maintain a copy of those rules.
