### ISSUE TITLE
Would like a slightly more optimized "first hour" for new contributors to flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#15619]
@timsneath and I were brainstorming today about successes in other projects at fostering community growth.  There are many great open source examples.

I would like to think that Flutter has done the fundamentals of open source pretty well (happy/healthy community, fully open development, good docs, tests, etc.) but I suspect we could throw out the red carpet a bit more than we do and make our "first hour" be a bit more welcoming.

If I'm new to Flutter from flutter.io or github.com/flutter/flutter where do I?
* Learn how to contribute?
* Learn how to help (other than just maybe coding)?
* Get suggestions on places to help and/or starter bugs?

I don't think we need a lot here.  But I didn't see anything obvious in flutter.io and 
https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md
seemed to be mostly technical focused if that's our "come help with Flutter" page?

Thoughts?  I would love comments from others pointing to great "come help!" or "getting started" pages from other OSS projects.

**Comment by escamoteur** [comment]
In ReactiveUI we have easy issues marked as for first time contributors.

**Comment by xqwzts** [comment]
FWIW the [easy fix](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22easy+fix%22) label exists and is used here.

Maybe it could get more visibility if CONTRIBUTING.md suggested that people look at issues under that label if they're interested in diving in?

**Comment by xqwzts** [comment]
>  I would love comments from others pointing to great "come help!" or "getting started" pages from other OSS projects.

I'm a fan of Django's [contributing docs](https://docs.djangoproject.com/en/dev/internals/contributing/). Particularly the [guidelines for new contributors](https://docs.djangoproject.com/en/dev/internals/contributing/new-contributors/#guidelines).

They even have a walkthrough tutorial on [writing your first patch for Django](https://docs.djangoproject.com/en/dev/intro/contributing/).

**Comment by InMatrix** [comment]
We've previously discussed linking to source code on Github from API docs to lower the barrier to making small improvements (e.g., fixing typos or adding a usage sample) via the Github Web editor. The tracking bugs are: https://github.com/dart-lang/dartdoc/issues/1454 and https://github.com/flutter/flutter/issues/10416.

We did this for flutter.io pages by adding a link to edit the source of the code, which I've seen being used by contributors. 

Cc: @jcollins-g

**Comment by irrigator** [comment]
[React has a pretty good "how to contribute" documentation.](https://reactjs.org/docs/how-to-contribute.html).

1. It writes clearly on how to contribute.
2. It has a detailed overview of the code base and some details.

**Comment by Hixie** [comment]
cc @Sfshaza @RedBrogdon @mjohnsullivan

**Comment by InMatrix** [comment]
We'll consider where a How to Contribute section should go. Cc: @galeyang

**Comment by Sfshaza** [comment]
Making a note to myself that I should take a look (and probably update) the website README.

**Comment by galeyang** [comment]
**Update**: from the study, we suggested to retain the Github link on the top nav. The reason is that some developers who are new to Flutter have a good interest to visit Github. They want to get a sense of full features available and the update frequency (which means the team's commitment and activeness of community).

For the short term, we can consider **adding an external link (to the current Contribution page on Github) both in the footer and on the Community page.** 

In the future, if we have more detailed content (like the above examples from React), we may consider adding a new section to the Doc's side nav.

What do you think @Sfshaza ?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2008](https://github.com/flutter/website/issues/2008) via [**ZenHub**](https://www.zenhub.com/)
