### ISSUE TITLE
Do not see headers inspect(F12) on browser event I passed at httpHeaders.

### ISSUE THREAD

**Issue by ltnghia97** [flutter/flutter#156269]
<img width="723" alt="Screenshot 2024-10-05 at 17 46 14" src="https://github.com/user-attachments/assets/b3144169-3c07-4b43-b617-f793cb98d0a4">

Hello authors, please double check this issue. I think this is the big issue for this package. When I play video from url, then inspect browser to check httpHeaders but not see it. That's not my expect.

**Comment by darshankawar** [comment]
I believe you are hitting https://github.com/flutter/flutter/issues/109379 so please follow-up in it for further updates.
Closing this as duplicate.
