### ISSUE TITLE
url_launcher cannot open the app on iOS through alipays://

### ISSUE THREAD

**Issue by Clushdada** [flutter/flutter#156244]
### Steps to reproduce

1.<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>alipays</string>
	</array>
2.Compile using xcode16

### Expected results

Open Alipay normally

### Actual results

There is no response or error message

### Code sample

   if(await canLaunchUrlString('alipays://platformapi/startapp?appId=20000067&url=https://qr.alipay.com/bax001378ilyo1ekwhns0026')){
             await launchUrlString('alipays://platformapi/startapp?appId=20000067&url=https://qr.alipay.com/bax001378ilyo1ekwhns0026');
           }else{
             EasyLoading.showError('fail');
           }

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 15.0 24A335 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.13.9 on channel stable at /Users/crush/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 months ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/crush/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/crush/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.1.1
    • Dart plugin version 223.8888

[✓] Connected device (2 available)
    • 14 Pro Max (mobile) • 00008120-001075413470201E • ios          • iOS 18.0 22A3354
    • macOS (desktop)        • macos                     • darwin-arm64 • macOS 15.0 24A335 darwin-arm64

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by TheCodeDaniel** [comment]
Hi there @Clushdada ,

Looking at your issue, I tried opening your provided URL on my browser,
"https://render.alipay.com/p/yuyan/180020040001212700/?cid=wap_dc"

the link open's just fine on my browser(chrome)


try using the code below instead

``
 if (await canLaunchUrl(Uri.parse(
                      "https://render.alipay.com/p/yuyan/180020040001212700/?cid=wap_dc"))) {
                    launchUrl(
                      Uri.parse(
                          "https://render.alipay.com/p/yuyan/180020040001212700/?cid=wap_dc"),
                    );
                  }
``

also, make sure that your button or gesture recognizer is working too,
you can debug to see if your gesture recognizer works with normal print statments too...

You can try this and let me know.

**Comment by Clushdada** [comment]
> Hi there @Clushdada ,
> 
> Looking at your issue, I tried opening your provided URL on my browser, "https://render.alipay.com/p/yuyan/180020040001212700/?cid=wap_dc"
> 
> the link open's just fine on my browser(chrome)
> 
> try using the code below instead
> 
> `if (await canLaunchUrl(Uri.parse( "https://render.alipay.com/p/yuyan/180020040001212700/?cid=wap_dc"))) { launchUrl( Uri.parse( "https://render.alipay.com/p/yuyan/180020040001212700/?cid=wap_dc"), ); }`
> 
> also, make sure that your button or gesture recognizer is working too, you can debug to see if your gesture recognizer works with normal print statments too...
> 
> You can try this and let me know.

What I mean is that the app cannot be opened through alipay://. Normally, the app should be opened through Scheme, but now it cannot be opened without any errors or prompts

**Comment by Clushdada** [comment]
This situation occurred after I upgraded to XCode

**Comment by Clushdada** [comment]
@onhyeon618

**Comment by TheCodeDaniel** [comment]
> This situation occurred after I upgraded to XCode

What current xcode version are you using ?
also, what macOs version are you on ?

**Comment by Clushdada** [comment]
> > This situation occurred after I upgraded to XCode
> 
> What current xcode version are you using ? also, what macOs version are you on ?

macOS 15.0
xcode16

**Comment by onhyeon618** [comment]
> @onhyeon618

Hello, why am I tagged here?

**Comment by Clushdada** [comment]
I have restored it after upgrading url_ launcher _ios

**Comment by TheCodeDaniel** [comment]
> I have restored it after upgrading url_ launcher _ios

that's cool, happy coding
