### ISSUE TITLE
MouseRegion has inconsistent behavior using stylus and touch

### ISSUE THREAD

**Issue by beeshi** [flutter/flutter#156223]
Copied from internal bug b/371544489

**[Summary]**

The MouseRegion widget triggers onEnter when a stylus touches down in it, but doesn't trigger onExit when the stylus goes elsewhere on the page. Neither onEnter nor onExit gets triggered when you use a finger instead of a stylus.

**[Reproduction project]**

The example code on this page: https://api.flutter.dev/flutter/widgets/MouseRegion-class.html 
I'm seeing this behavior on a touchscreen chromebook and on ipad, haven't tried on other devices that support touch

**[Reason for prioritization]**

Causing issues in prod when users use a stylus to draw.

**Comment by TahaTesser** [comment]
There was a MouseRegion related issue on Android related to stylus, see https://github.com/flutter/flutter/issues/154842#issuecomment-2350740631

**Comment by huycozy** [comment]
Checking this using iPad with Apple Pencil, I see the stylus is working as expected, onEnter and onExit are both triggered (please watch the demo video). I also tested with a Bluetooth mouse and see the same expected result here.

<details open>
<summary>Demo video (iPad Air 5, iPadOS 17.5.1)</summary>

| Pencil | Mouse |
| --------------- | --------------- |
<video src="https://github.com/user-attachments/assets/5f463248-3d7b-4c9a-9061-4cbec5293b25"/> | <video src="https://github.com/user-attachments/assets/8a73de82-7ea6-43ab-bc63-5dbe73d6c535"/>
</details>

However, onEnter nor onExit are not triggered with touch gesture by finger as reported. 

Checked on Flutter versions:
```console
Channel stable, 3.24.3
Channel master, 3.26.0-1.0.pre.374
```

**Comment by beeshi** [comment]
vcbvbb

**Comment by beeshi** [comment]
iPad pro, iPadOS 17.4.1

https://github.com/user-attachments/assets/7f7ee38f-c2b5-41a3-9738-f23cc9f61725

**Comment by xster** [comment]
Google triage: validating that it's impacting users in production

**Comment by beeshi** [comment]
We’re not entirely sure since I think we didn’t test with a stylus before, but I’d guess its been this way for a while

**Comment by chunhtai** [comment]
not entirely sure what is going on, maybe the stylus doesn't follow the pointer event lifecycle. Should stylus be included in mouse event for the first place?

**Comment by dkwingsmt** [comment]
Update: I'm investigating it. I can reproduce it on my iPad. It occurs only on Web with a stylus.
