### ISSUE TITLE
WillPopScope onWillPop  is no longer getting triggered on a root page. Flutter 3.24.3

### ISSUE THREAD

**Issue by spiderion** [flutter/flutter#156298]
### Steps to reproduce

Add a WillPopScope on a route at the root. Tap the android system back button.
The method onWillPop should get  triggered.
but the method is not getting triggeredAndroid

### Expected results

onWillPop should get triggered

### Actual results

onWillPop is not getting triggered

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)            
[✓] Network resources

• No issues found!


```

</details>

**Comment by danagbemava-nc** [comment]
Hi @spiderion, please provide a complete minimal reproducible code sample so that we can properly investigate this issue. 

Thank you

**Comment by spiderion** [comment]
I can't provide code, maybe this is related. https://github.com/flutter/flutter/issues/140869
It started happening with the new flutter version.

**Comment by danagbemava-nc** [comment]
Hi @spiderion, are you using go_router? Also, the code sample doesn't have to be your project code. Just a complete runnable sample that reproduces the issue so that we can properly investigate the issue.

**Comment by spiderion** [comment]
Hi @danagbemava-nc , No I am not using go_router, 
I am using WillPopScope/PopScope.
This happens with android only and when I press the android system back button the app just exists without triggering the callbacks.
I tried to build a sample on a new project but I can't reproduce on a new project.
Does that mean that the issue in my code only?

Can we wait to see if anyone else has the same bug?

**Comment by danagbemava-nc** [comment]
Hi @spiderion, what version of android are you using? Do you have `android: enableOnBackInvokedCallback=true` in your `AndroidManifest.xml` file?

**Comment by spiderion** [comment]
Hi @danagbemava-nc, I have tested with android 14 and android 12 and the issue was the same.
I tried this with android:enableOnBackInvokedCallback="false" and true and no difference there.

**Comment by spiderion** [comment]
HI @danagbemava-nc , I am diving deep into the root of the issue and I found out that adding a global key to the PopScope makes the callback work. 

  Widget pageScaffold(SectionIndexDataState data) {
    return PopScope(
        key: GlobalKey(), // this part makes the  onPopInvokedWithResult be triggered again
        canPop: false,
        onPopInvokedWithResult: (bool didPop, result) async {
          print('Pop Invoked $popInvoked');
          popInvoked++;
          data.onWillPop.call(false, null);
        },
        child: _scaffold(data.index, data.sections));
  }
  
  But of course now I have some side effects on pages being rebuilt

**Comment by spiderion** [comment]
I think I fixed my issue.
The problem was that I was creating a GlobalKey<NavigatorState>() on every set state in my flutter widget tree. 
Although with the old flutter was working fine in the new fluter was causing an issue.
