### ISSUE TITLE
app Returning to home Screen

### ISSUE THREAD

**Issue by omninosDeepankar** [flutter/flutter#156280]
### Steps to reproduce

I tried to pick image and click on on or check icon then app crash.

### Expected results

it must return to previous page.

### Actual results

it just navigate to home page directelly

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.90.2)
[✓] Connected device (2 available)
[✓] Network resources

</details>

**Comment by TheCodeDaniel** [comment]
Hello @omninosDeepankar ,
please can you provide more description to you issue,
like code samples that can be used for more debugging ?
also the crash logs, it would be helpful , thanks

**Comment by huycozy** [comment]
@omninosDeepankar You may probably encounter memory issue, you can check [Handling MainActivity destruction](https://pub.dev/packages/image_picker#handling-mainactivity-destruction) to see if it helps. 

If the issue still persists, please try to provide more information as mentioned in above comment for us to investigate the issue.

**Comment by TheCodeDaniel** [comment]
> @omninosDeepankar You may probably encounter memory issue, you can check [Handling MainActivity destruction](https://pub.dev/packages/image_picker#handling-mainactivity-destruction) to see if it helps.
> 
> If the issue still persists, please try to provide more information as mentioned in above comment for us to investigate the issue.

yeah, that's true, it could be a memory issue, 
that's why i'm asking for the code example.

i want to check if it contains a Image.memory() or MemoryImage(), those large dataset can cause the app to crash, but let's see if any code example will be provided

**Comment by omninosDeepankar** [comment]
Future<void> _pickImage(ImageSource source) async {
    
    final pickedFile = await _picker.pickImage(source: source);

    if (pickedFile != null) {
      setState(() {
        _selectedImage = File(pickedFile.path);
      });
    }
  }
  while i did not get any error message 
  
  
  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    
 
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.FLASHLIGHT"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

    <application
        android:label="-------name-----"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        tools:replace="android:icon, android:label"
        android:requestLegacyExternalStorage="true"> 

        
                

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
         
        <intent>
            <action android:name="android.intent.action.VIEW"/>
            <data android:scheme="sms"/>
        </intent>
        
        <intent>
            <action android:name="android.intent.action.VIEW"/>
            <data android:scheme="tel"/>
        </intent>
        
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService"/>
        </intent>
    </queries>

</manifest>

**Comment by TheCodeDaniel** [comment]
ok, there's something i think you can try:

The Android "READ_EXTERNAL_STORAGE" permission has been replaced with "READ_MEDIA_IMAGES" starting from Android 13 (API level 33). However, this permission needs to be requested at runtime. (make the changes in your android manifest.xml)

So you're gonna need to setup permission handler in your app:
Request for permission in initState or wherever you want and call the function below:

import 'package:permission_handler/permission_handler.dart';

`
Future<void> requestPermissions() async {
  if (await Permission.storage.isGranted) {
    // Permission is already granted
    return;
  }
  if (await Permission.photos.isGranted) {
    // Android 13+ permission for images
    return;
  }

  // Request storage permission for Android < 13
  await Permission.storage.request();
  
  // Request photos permission for Android 13+
  if (await Permission.photos.isDenied) {
    await Permission.photos.request();
  }
}
`

then call the function below to pick an image:
`
Future<void> pickImage() async {
  try {
    final pickedFile = await _picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      setState(() {
        _selectedImage = File(pickedFile.path);
      });
    }
  } catch (e) {
    print("Error picking image: $e");
  }
}
`

before you test the code, remember to run "flutter clean" and "flutter pub get".

Let's see if this will work for you.

**Comment by huycozy** [comment]
@omninosDeepankar Just to confirm, are you using [image_picker](https://pub.dev/packages/image_picker)? 

If so, you can try using [package's example](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) first to see if the crash occurs or not.

Otherwise, if the issue only occurs on your application code, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. You should narrow the issue down by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a minimal sample code that can produce the issue. And please share it here when you have such an example. 

>while i did not get any error message

If you can't get crash log from flutter, I would suggest you try catching native log with `adb logcat`, for eg:

```console
adb logcat | grep -F "`adb shell ps | grep <your-app-id>  | tr -s [:space:] ' ' | cut -d' ' -f2`"
```

**Comment by omninosDeepankar** [comment]
> @omninosDeepankar Just to confirm, are you using [image_picker](https://pub.dev/packages/image_picker)?
> 
> If so, you can try using [package's example](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) first to see if the crash occurs or not.
> 
> Otherwise, if the issue only occurs on your application code, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. You should narrow the issue down by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the affected page into a minimal sample code that can produce the issue. And please share it here when you have such an example.
> 
> > while i did not get any error message
> 
> If you can't get crash log from flutter, I would suggest you try catching native log with `adb logcat`, for eg:
> 
> ```
> adb logcat | grep -F "`adb shell ps | grep <your-app-id>  | tr -s [:space:] ' ' | cut -d' ' -f2`"
> ```
with some more changes this worked for me ,thanks
