### ISSUE TITLE
Running flutter apk, Can not locate Resources: Directory: 'apk/res', ignoring

### ISSUE THREAD

**Issue by kingkazuma** [flutter/flutter#1562]
Ubuntu 15.10
Android SDK Tools 24.4.1
Android SDK Platform-tools 23.1
Android SDK Build-tools 22.0.1
Android 5.1.1(API 22) SDK Platform 

`root@OZ:/# cat /etc/environment 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/jdk1.8.0_71/bin:/dart-sdk/bin:/flutter/bin:$ANDROID_HOME/build-tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools
ANDROID_HOME=/android-sdk-linux
JAVA_HOME=/jdk1.8.0_71

root@OZ:/# flutter --version
Flutter
Repository: https://github.com/flutter/flutter.git
Branch: alpha
Revision: 1b75de1b164a3c5f668933a7603aa9094c181aae (6 days ago)

root@OZ:/# cd /Dart-Project/hello_world/
root@OZ:/Dart-Project/hello_world# flutter apk
Can not locate Resources: Directory: 'apk/res', ignoring.
ProcessException: No such file or directory
  Command: /android-sdk-linux/build-tools/22.0.1/aapt package -M apk/AndroidManifest.xml -A /tmp/flutter_toolsvgZRT7/assets -I /android-sdk-linux/platforms/android-22/android.jar -F /tmp/flutter_toolsvgZRT7/app.apk.unaligned /tmp/flutter_toolsvgZRT7/artifacts
dart:io                                                           Process.runSync
package:flutter_tools/src/base/process.dart 86                    _runWithLoggingSync
package:flutter_tools/src/base/process.dart 66                    runCheckedSync
package:flutter_tools/src/commands/apk.dart 106                   _ApkBuilder.package
package:flutter_tools/src/commands/apk.dart 319                   ApkCommand._buildApk
package:flutter_tools/src/commands/apk.dart 399                   ApkCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/apk.dart 405                   ApkCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/apk.dart                       ApkCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 54          FlutterCommand.run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 152  FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/executable.dart 60                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 54                          main.<async>`

**Comment by devoncarew** [comment]
I think this is fixed; we always create an android/res dir now.
