### ISSUE TITLE
Target debug_unpack_ios failed: Exception: Binary for "flutter build ipa"

### ISSUE THREAD

**Issue by ravimandal06** [flutter/flutter#156288]
## log file
[build_log.txt](https://github.com/user-attachments/files/17269220/build_log.txt)

##

## Error : 
Target debug_unpack_ios failed: Exception: Binary /Users/umeshsubedi/Library/Developer/Xcode/DerivedData/Runner-fwrxelryhikflbbasglaqvfqypgr/Build/Products/Debug-iphoneos/Flutter.framework/Flutter does not contain . Running lipo -info:

**Comment by darshankawar** [comment]
@ravimandal06 


> Target debug_unpack_ios failed: Exception: Binary /Users/umeshsubedi/Library/Developer/Xcode/DerivedData/Runner-fwrxelryhikflbbasglaqvfqypgr/Build/Products/Debug-iphoneos/Flutter.framework/Flutter does not contain . Running lipo -info

@ravimandal06 Is it the only error line you get ? If more, please provide the entire error log. 
Also, the build log you shared doesn't contain the log for the error you are reporting.
Moreover, please provide `flutter doctor -v` to know what flutter version are you on.
