### ISSUE TITLE
TabBar.height adds a gap between the AppBar.toolbar and AppBar.bottom

### ISSUE THREAD

**Issue by BenjiFarquhar** [flutter/flutter#156200]
### Use case

    If we add a smaller height to TabBar, E.G:
    
```
AppBar(
  bottom: const TabBar(
    tabs: [
      Tab(
        text: 'Profile',
        height: 30,
      ),
      Tab(
        text: 'Appearance',
        height: 30,
      ),
    ],
  ),
```
    It adds a gap between the `AppBar` `toolbar` and the `bottom`:
    
<img width="510" alt="Screenshot 2024-10-04 at 8 32 59 pm" src="https://github.com/user-attachments/assets/243bbbb5-57cf-4152-976b-a20bb67e29d0">

And without the height specified on the Tab, it has no gap:

<img width="507" alt="Screenshot 2024-10-04 at 8 31 39 pm" src="https://github.com/user-attachments/assets/2f2e9183-f57f-4ae5-b917-96101a7d352f">

I don't want the gap. So i want this:

<img width="506" alt="Screenshot 2024-10-04 at 8 35 25 pm" src="https://github.com/user-attachments/assets/74208acc-8aed-4203-ac84-8f98ec2120de">

    

### Proposal

Ideally we should be able to control the padding between them but i found just adding `mainAxisSize: MainAxisSize.min,` below to `app_bar.dart` at least removed the gap entirely which is better than mandatory gap:

    if (widget.bottom != null) {
      appBar = Column(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Flexible(
            child: ConstrainedBox(
              constraints: BoxConstraints(maxHeight: toolbarHeight),
              child: appBar,
            ),
          ),
          if (widget.bottomOpacity == 1.0)
            widget.bottom!
          else
            Opacity(
              opacity: const Interval(0.25, 1.0, curve: Curves.fastOutSlowIn).transform(widget.bottomOpacity),
              child: widget.bottom,
            ),
        ],
      );

Adding this between them gave the padding desired: `SizedBox(height: 5),` so ideally you would add `bottomSpacer` as a parameter to customise: `SizedBox(height: bottomSpacer),` or make it EdgeInsets and wrap the `bottom` with it.

**Comment by TahaTesser** [comment]
@Piinks 

This is by design. When the tabs height is less than the default `_kTabHeight` then it defaults to the value of `_kTabHeight` (46 pixels)
https://github.com/flutter/flutter/blob/71ddc6836a7a9e5afb328809597233f6c2f58aaa/packages/flutter/lib/src/material/tabs.dart#L1290-L1298

If we want ti change this behavior, to avoid breaking change we would need to some sort of parameter.

**Comment by Piinks** [comment]
Ah right, thanks for taking a look. Should we add to the docs that TabBars cannot be less than 46 pixels in height?

**Comment by TahaTesser** [comment]
> Ah right, thanks for taking a look. Should we add to the docs that TabBars cannot be less than 46 pixels in height?

+1 and I remember folks using `PreferredSize` for a custom tab bar. It can be leveraged to get a smaller than default tab bar.

```dart 
bottom: const PreferredSize(
              preferredSize: Size.fromHeight(20),
              child: TabBar(
                tabs: [
                  Tab(
                    text: 'Profile',
                    height: 20,
                  ),
                  Tab(
                    text: 'Appearance',
                    height: 20,
                  ),
                ],
              ),
            ),
```
<img width="907" alt="Screenshot 2024-10-22 at 18 29 23" src="https://github.com/user-attachments/assets/213eaf06-c84e-491b-a7a0-848dcaba2591">
