### ISSUE TITLE
 flutter build windows error 

### ISSUE THREAD

**Issue by luoqiang110** [flutter/flutter#156289]
### Steps to reproduce

 flutter build windows

### Actual results

download error

### Logs

PS C:\WINDOWS\system32> flutter build windows
Flutter assets will be downloaded from https://storage.flutter-io.cn/. Make sure you trust this source!
Downloading windows-x64-debug/windows-x64-flutter tools...         40.9s
Downloading windows-x64/flutter-cpp-client-wrapper tools...        139ms
Downloading windows-x64-profile/windows-x64-flutter tools...        52.4s
Downloading windows-x64-release/windows-x64-flutter tools...        197ms
Downloading windows-x64-release/windows-x64-flutter tools...        160ms
Failed to download
https://storage.flutter-io.cn//flutter_infra_release/flutter/2c25423ea6187025c20a42781da9c7a5a88f0e1f/windows-x64-release/windows-x64-flutter.zip.
Ensure you have network connectivity and then try again.
RedirectException: Redirect loop detected

### Flutter Doctor output

PS C:\WINDOWS\system32> flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn/. Make sure you trust this source!
[√] Flutter (Channel master, 3.26.0-1.0.pre.372, on Microsoft Windows [版本 10.0.19044.1706], locale zh-CN)
    • Flutter version 3.26.0-1.0.pre.372 on channel master at D:\FlutterInstallPath\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 672eebc55b (8 hours ago), 2024-10-06 00:29:30 -0400
    • Engine revision 2c25423ea6
    • Dart version 3.6.0 (build 3.6.0-326.0.dev)
    • DevTools version 2.40.0
    • Pub download mirror https://pub.flutter-io.cn/
    • Flutter download mirror https://storage.flutter-io.cn/

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\FlutterInstallPath\Andorid\download
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: D:\FlutterInstallPath\Andorid\AndoridStudioInstall\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at D:\FlutterInstallPath\Andorid\AndoridStudioInstall
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.94.0)
    • VS Code at C:\Users\think\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.67

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment]
Hi @luoqiang110 
From the logs you provided, it seems to be an issue with your network/connectivity. I would suggest you follow [Configuring Flutter to use a mirror site](https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) or try switching to a better network or check if you are using any anti-virus or firewall that might be causing the error.

I'm going ahead and closing the issue. If you disagree, please write in the comments and I will reopen it.
