### ISSUE TITLE
Remove use_modular_headers! from Swift Podfiles

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#156259]
# Background

We added `use_modular_headers!` to our `Podfile`s as we originally planned to phase out `use_frameworks!` (see https://github.com/flutter/flutter/pull/42204). However, our plans have now changed and we are instead phasing out CocoaPods entirely in favor of Swift Package Manager.

CocoaPods's `use_frameworks!` and `use_modular_headers!` are two different overlapping options that should not be used together. This change removes the `use_modular_headers!` from the macOS `Podfile` and the iOS Swift `Podfile` (the iOS Objective-C template was recently deprecated https://github.com/flutter/flutter/pull/155867).

# Work

Remove `use_modular_headers!` from all Swift `Podfile`s.

**Comment by navaronbracke** [comment]
Would including a project migrator for apps be a good thing here? And do we need to modify the SPM migration docs to tell developers to remove it there as well?

**Comment by loic-sharma** [comment]
@navaronbracke While in theory this change is necessary, in practice we're not aware of any problems caused by this today. We're concerned that a migration could break apps if not done well.

For now, we'll fix new apps but not existing apps. Long-term, all existing apps will migrate to SwiftPM and won't be affected by this problem. We want to put all our resources on getting the SwiftPM migration right :) 

Let me know if you have any concerns!
