### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleDataTransport"

### ISSUE THREAD

**Issue by KalybosPro** [flutter/flutter#156367]
[!] CocoaPods could not find compatible versions for pod “GoogleDataTransport”: In Podfile: firebase_messaging (from .symlinks/plugins/firebase_messaging/ios) was resolved to 15.1.3, which depends on Firebase/Messaging (= 11.2.0) was resolved to 11.2.0, which depends on FirebaseMessaging (> 11.2.0) was resolved to 11.2.0, which depends on GoogleDataTransport (> 10.0)

I need your help please. I'm on this issue for 7 days.
I'm using the latest version of xcode (v16)

**Comment by ShuheiSuzuki-07** [comment]
@KalybosPro 

Please check out these two issues! They are not related to Flutter.

https://github.com/googlesamples/mlkit/issues/877
https://issuetracker.google.com/issues/362452861

**Comment by danagbemava-nc** [comment]
This is not a flutter issue. See https://stackoverflow.com/questions/78958362/cocoapods-could-not-find-compatible-versions-for-pod-googledatatransport to see if any of the links helps. 
See also https://github.com/flutter/flutter/issues/156367#issuecomment-2398265939


Closing from here as this is not a flutter issue. 

Thank you

**Comment by KalybosPro** [comment]
Ok thanks.
