### ISSUE TITLE
 Flutter imports are not case sensitive resulting in static variables not behaving correctly

### ISSUE THREAD

**Issue by hasen6** [flutter/flutter#156314]
### Steps to reproduce

1. Create a new file with a static boolean variable.
2. Import the file in two separate files, one with capital letters in the import path and the other with the correct casing
3. Set the static variable to true and update state for both
4. The variable is true with the correct import and false without
5. Zero indication anywhere that the reason is the import is incorrect

This issue has already been reported here and for some reason nothing has been done about it and it's just been closed. https://github.com/flutter/flutter/issues/98993

I just spent an hour tearing my hair out over what appeared to be a completely impossible problem. The reason is the import has been "found" despite the incorrect file name but it has not since it's a totally different static variable. It's very easy to have this kind of error when you're running some kind of find and replace action.

### Expected results

It should flag a huge error up saying your file import is completely incorrect.

### Actual results

The import sits there like it's perfectly fine with no error in sight.

### Code sample

<details open><summary>Code sample</summary>

```dart
import '../utils/Demo.dart';

vs

import '../utils/demo.dart';
```

</details>

**Comment by danagbemava-nc** [comment]
This is a general dart issue rather than a flutter issue. See https://github.com/dart-lang/linter/issues/3244

Kindly follow up in the issue linked above for updates.

Closing from here. 

Thank you
