### ISSUE TITLE
flutter google maps hide logs

### ISSUE THREAD

**Issue by leeflix** [flutter/flutter#156302]
### Use case

it is ridicoulous how many logs are produced by the google maps plugin. it makes working with the console near impossible. there should be none if not specified otherwise

### Proposal

please introduce a debug flag. and only if it is set to true (default=false) logs are printed in the console

**Comment by huycozy** [comment]
There is an open issue for this at https://github.com/flutter/flutter/issues/55148. Closing this issue in favor of that one.
