### ISSUE TITLE
[Impeller] libImpeller: Publish impeller library artifacts.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#156358]
Similar to the [Flutter Embedder API](https://github.com/flutter/engine/blob/main/docs/Custom-Flutter-Engine-Embedders.md), publish to artifacts to the `flutter_infra_release` bucket.

**Comment by zanderso** [comment]
It might be easiest to package along with the embedder .so.

Tracing back from that archive starting here:

https://github.com/flutter/engine/blob/db0c0b7ca42899aaf43fa5ca28f76e92030a305c/ci/builders/linux_host_engine.json#L19C67-L19C85

That file is generated by the rule here:

https://github.com/flutter/engine/blob/db0c0b7ca42899aaf43fa5ca28f76e92030a305c/shell/platform/embedder/BUILD.gn#L583.

So you can either add a file to that archive, or create a new path in parallel from a new `zip_bundle` target to a new file listed in the `archives` section of the `.json` file.
