### ISSUE TITLE
How to perform UI automation (integration testing) for a Flutter app on HarmonyOS？

### ISSUE THREAD

**Issue by joly-chen** [flutter/flutter#156395]
### Use case

Unable to access elements in a Flutter app on HarmonyOS

### Proposal

Support flutter integration testing on HarmonyOS

**Comment by darshankawar** [comment]
@joly-chen 
You will probably need to file this here  https://gitee.com/openharmony-sig/flutter_flutter/issues
Also check https://github.com/flutter/flutter/issues/38437
Closing from here.
