### ISSUE TITLE
Invalid Kernel binary: Indicated size is invalid [DART-2-PREVIEW]

### ISSUE THREAD

**Issue by envious** [flutter/flutter#15636]
## Steps to Reproduce

When trying to run tests with the following command:
`flutter test --preview-dart-2`
I receive the following error:

`[   +9 ms] Shell: e:\b\build\slave\windows_engine\build\src\third_party\dart\runtime\vm\kernel_binary.cc: 42: error: Invalid kernel binary: Indicated size is invalid.
[        ] Shell: Stack dump aborted because no current Dart thread.
[  +33 ms] test 0: process with pid 8108 crashed before connecting to test harness
[   +5 ms] test 0: waiting for controller sink to close
[   +7 ms] test 0: cleaning up...
[   +3 ms] test 0: shutting down test harness socket server`

If I try to run the same tests through Intellij with the dart-2 preview enabled in Intellij settings, I receive the same error with some extra information:

`Shell: e:\b\build\slave\windows_engine\build\src\third_party\dart\runtime\vm\kernel_binary.cc: 42: error: Invalid kernel binary: Indicated size is invalid.
Shell: Stack dump aborted because no current Dart thread.
Failed to load "<test file path>":
Shell subprocess crashed with unexpected exit code -1073740791 before connecting to test harness.`

## Logs

`flutter analyze --preview-dart-2` results:
`No issues found!
Ran in 4.1s`

## Flutter Doctor

`flutter doctor` results:

`[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-GB)
    • Flutter version 0.1.5 at C:\Users\<user>\Desktop\flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\<user>\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[!] IntelliJ IDEA Community Edition (version 2016.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] VS Code (version 1.19.3)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.`

**Comment by mraleph** [comment]
This was fixed on `master` with https://fuchsia-review.googlesource.com/c/garnet/+/131115

Consider switching to `master` from beta.
