### ISSUE TITLE
Prompt user to run flutter upgrade if they never did

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1563]
From https://github.com/flutter/flutter/issues/1557

If a user gets a flutter project, and tries to run `flutter start ...`, it will fail with this message: "Cannot locate the sky_engine package; did you include 'flutter' in your pubspec.yaml file?"

Since we (the flutter tool) puts flutter into the pubspec.yaml (and, because that's a scary Dart term most users won't know), then could we instead print this message:

"Unable to start, dependencies are not installed. Please run `flutter upgrade`, and then retry your command. If that doesn't work, please run `flutter doctor`, and file an issue at https://github.com/flutter/flutter/issues/new"

**Comment by Hixie** [comment]
`flutter upgrade` will upgrade the flutter repo checkout, right?
Don't they just need to run `pub get`?
Why don't we run `pub get` for them?

**Comment by sethladd** [comment]
flutter upgrade runs pub get for me. I don't know under what conditions it does, but seems to be "often".

If we auto-run pub get for them, let's make it very clear that this is an operation that takes a long time, and that it's a rare option. We don't want them to think that flutter start is always slow. Something like: "We detected your dependencies are out of date. Stand by while we update..."

**Comment by devoncarew** [comment]
`run` (and `build`) now run pub get if the deps are out of date; we do show text for `Running pub get...` if we need to run it.
