### ISSUE TITLE
Running flutter create with a reserved keyword in org is not escaped

### ISSUE THREAD

**Issue by idragon81** [flutter/flutter#15631]
Running the following command 
`flutter create -akotlin --org="in.company.domain" flutter_app`
is problematic.

MainActivity.kt is created with the following package 
package in.company.domain
instead of 
package \`in\`.company.domain

Which results in failed compilation

**Comment by Hixie** [comment]
@jonahwilliams I unassigned this from you since it looks like the assignment was stale.

**Comment by zoechi** [comment]
Duplicate of #16521
which has more activity
