### ISSUE TITLE
Screen flickering in iOS simulators running in virtual machines

### ISSUE THREAD

**Issue by priitlatt** [flutter/flutter#156321]
### Steps to reproduce

When running Flutter app using default settings in an iOS simulator within a virtual machine then animations are flickering or there are artifacts on the device screen.

The issue is very similar to what is already described and presumably fixed in https://github.com/flutter/flutter/issues/148660.

The issue should be reproducible with any macOS virtual machine that is using Apple's [Virtualization.framework](https://developer.apple.com/documentation/virtualization) under the hood, but let us limit ourselves with [Tart](https://tart.run/) for now.

**Steps:**
1. Install Tart to run virtualized macOS instances with `brew install cirruslabs/cli/tart`.
2. Create a macOS virtual machine from [`ghcr.io/cirruslabs/macos-sonoma-xcode:16`](https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-sonoma-xcode/275081790?tag=16) image (it comes with both Xcode 16 and Flutter pre-installed): `tart clone ghcr.io/cirruslabs/macos-sonoma-xcode:16 macos`.
3. Run the VM: `tart run macos`.
4. From the VM open terminal and update Flutter if need be.
5. Launch suitable iOS simulator in VM.
6. Create a new Flutter app and run it on simulator:
  a. `flutter create app`
  b. `cd app`
  c. `flutter run` 
7. Play around with the application in simulator and observe the screen.

**Host environment:**

```shell
% sw_vers
ProductName:		macOS
ProductVersion:		14.7
BuildVersion:		23H124
```

```shell
% tart --version
2.18.4
```

**Guest environment:**

```shell
% sw_vers
ProductName:		macOS
ProductVersion:		14.6
BuildVersion:		23G80
```

```shell
% xcodebuild -version
Xcode 16.0
Build version 16A242d
```

```shell
% flutter --version
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (4 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
```

### Expected results

The app should run in the iOS simulator within a virtual machine the same way as it does on a simulator that is running on bare metal. It is expected that the application runs without any glitches or screen flickering; animations are rendered smoothly without unexpected overlays and texts are clearly visible.

### Actual results

Flutter applications in iOS simulators which virtual machines are have rendering issues. There are visible glitches and screen is flickering when something is changing on the screen.

The flickering can be "fixed" if build settings for the `Debug` build target in Xcode are updated so that Excluded Architectures contain `amd64` (see the screenshot below).

### Code sample

The issue can be reproduced using default counter app.

<details open><summary>Code sample</summary>

```shell
flutter create app
cd app
flutter run
```

</details>

### Screenshots or Video

<details open>
<summary>Video demonstration of issue</summary>

https://github.com/user-attachments/assets/e0aec632-696e-4cbf-9a94-105991e4a65a

</details>

<details open>
<summary>Fix in Xcode</summary>

![Screenshot 2024-10-07 at 17 01 04](https://github.com/user-attachments/assets/c9a616bc-4555-4be9-a845-f6c1bd4381e7)

</details>

### Logs

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6 23G80 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/admin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/admin/android-sdk
    • Platform android-33, build-tools 34.0.0
    • ANDROID_HOME = /Users/admin/android-sdk
    • ANDROID_SDK_ROOT = /Users/admin/android-sdk
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.12+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode_16.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] Connected device (3 available)
    • iPhone 16 (mobile)              • C8BCE9F4-3EC7-40D9-A5CC-D0E85207512B • ios          • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 14.6 23G80 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Thank you for the detailed issue! This looks similar to https://github.com/flutter/flutter/issues/150169. 

But I see the output console is clean and no crash trace there from your demo video. And you also mentioned the issue can be resolved if disable `arm64` arch in XCode. 

Can you please try switching to Flutter master channel and running again with/without Impeller to see if you see the same crash trace at https://github.com/flutter/flutter/issues/150169#issuecomment-2167171503?

**Comment by priitlatt** [comment]
Thanks @huycozy for getting back so quickly with those extra details.

Issue https://github.com/flutter/flutter/issues/150169 was closed with a resolution that this should be addressed on Tart side. To be sure that this is not just an issue with Tart I tested it out on another macOS virtualization platform [Orka Desktop](https://orkadocs.macstadium.com/docs/desktop-getting-started), where the glitching reproduced on `stable` channel:

<details>
<summary>Screen recording of simulator in Orka Desktop VM (<b>Flutter <code>stable</code>, Impeller enabled</b>)</summary>

https://github.com/user-attachments/assets/ff99ad14-81ed-4726-9645-cec9dab74888

</details>

However, the glitches / artifacts are gone when the app is run on simulator using `--no-enable-impeller`.

<details>
<summary>Screen recording of simulator in VM (<b>Flutter <code>stable</code>, Impeller disabled</b>)</summary>

https://github.com/user-attachments/assets/d5fc8ec4-a5d6-4858-8023-1a57444b5cba

</details>

And finally, the **issue does not reproduce on `master`** channel regardless of Impeller being enabled or disabled.

<details>
<summary>Screen recording of simulator in VM (<b>Flutter <code>master</code>, Impeller enabled</b>)</summary>

https://github.com/user-attachments/assets/b14c62ef-9ac2-4541-be58-ee2bcfb18ef9

</details>
