### ISSUE TITLE
[tool_crash] StateError: Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by pankajkcodes-dev** [flutter/flutter#156391]
## Command
```sh
flutter run --machine
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Stream has already been listened to.
```console
#0

**Comment by danagbemava-nc** [comment]
Hi @pankajkcodes-dev, do you get this every time you run your app? What version of flutter are you using? If this is a frequent occurrence, can you please provide the full output of `flutter run --machine -v` that captures the tool crash?
