### ISSUE TITLE
[google_sign_in][web] work perfect on debug mode, but get MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in) in release mode

### ISSUE THREAD

**Issue by Kinwailo** [flutter/flutter#156357]
### What package does this bug report belong to?

google_sign_in

### What target platforms are you seeing this bug on?

Web

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
https://pastebin.com/hhsz6ruh
```

</details>

### Steps to reproduce

work perfect on debug mode
but build in release mode and publish to web get error:
MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### Expected results

build in release mode work perfect like debug mode

### Actual results

get error:
MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sig

### Code sample

<details close><summary>Code sample</summary>

```dart
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/bf23437e-f2e7-49fc-b048-11563d3e6f10)

</details>

### Logs

<details open><summary>Logs</summary>

```console
https://pastebin.com/ntymGC1X
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.4169], locale zh-HK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.94.0)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @Kinwailo, I checked this on my end but couldn't reproduce the issue as reported (tried both canvaskit and HTML renderers). I'm on the latest Flutter stable 3.24.3 and deployed web with Firebase hosting. Please try upgrading Flutter to see if the issue persists or not. 

Can you share the deployed site here? And please provide the error trace in text format instead of screenshot for better readability and investigation.
