### ISSUE TITLE
[go_router] Go Router 14.0 migration guide is shared with commenter permissions

### ISSUE THREAD

**Issue by raffaelecostanzo** [flutter/flutter#156425]
### Steps to reproduce

If you go to the GitHub repository page of Go Router and click on the link of the latest migration guide, you'll notice that the document is shared with commenter permissions by default and the document is unreadable.

I know it is sufficient to change it to view mode, but as the others migration guides of the package, I think it should only have view permissions to the public.

### Expected results

The document should be in view mode only.

### Actual results

The document can be in view mode and commenter mode. It is shared with commenter mode by default.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
This has led to the vandalization of the document. A lot of the content is missing now

**Comment by chunhtai** [comment]
@ValentinVignal

looks like you owned the doc, can you turn it into a view only doc?

**Comment by ValentinVignal** [comment]
Sorry for that. I turned it into a view only doc
