### ISSUE TITLE
Unable to build or run flutter project other then c/CurrentUser/AndroidStudioProjects path 

### ISSUE THREAD

**Issue by YazadDumasia** [flutter/flutter#156470]
After 3.10.6 flutter version updated and Android studio arctic fox version at current version I unable to build android module or run flutter project in other drivers expect path of C/CurrentUser/AndroidStudioProjects or studioproject.

Please flutter maintainers I request you to please take look into it, I can save all projects in c drive it almost getting full due to low allocation and there is kind password protected every time to access it. I am using windows 10 os

**Comment by danagbemava-nc** [comment]
Hi @YazadDuamasia, please share the error you get and whether or not the drives are NTFS or not. 

Please also provide the output of `flutter doctor -v`

Thank you

**Comment by danagbemava-nc** [comment]
Hi @YazadDuamasia, is drive D an NTFS or ExFat drive? What error do you get when you try to build your application?

**Comment by danagbemava-nc** [comment]
Hi @YazadDuamasia, please provide the full output of `flutter doctor -v` and the full output of `flutter build -v` or `flutter run -v` depending on the command that you ran. 

Thank you

**Comment by danagbemava-nc** [comment]
Please provide the full output of `flutter build -v` or `flutter run -v` depending on the command that you ran.
