### ISSUE TITLE
Can't run flutter app inside Android Studio

### ISSUE THREAD

**Issue by FraneCal** [flutter/flutter#156463]
Hi all,

I have seen this issue here and on stackoverflow but I didn't find any solution to it. 

When I run my code I get the following error message:

> Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
> 	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
> 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
> 	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
> 	at org.gradle.wrapper.Download.download(Download.java:44)
> 	at org.gradle.wrapper.Install$1.call(Install.java:61)
> 	at org.gradle.wrapper.Install$1.call(Install.java:48)
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
> 	at org.gradle.wrapper.Install.createDist(Install.java:48)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
> 	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
> 	at java.base/sun.security.validator.Validator.validate(Unknown Source)
> 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
> 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
> 	... 25 more
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
> 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
> 	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
> 	... 30 more
> Error: Gradle task assembleDebug failed with exit code 1

My flutter doctor -v is:

```
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale sl-SI)
    • Flutter version 3.24.3 on channel stable at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
```

How to resolve this issue?

**Comment by darshankawar** [comment]
Looking at the error log, it doesn't seem to be related to Flutter, but coming from native. Check your local internet connection and confirm if it is working fine. Make sure you are not using VPN or any restricted network or office network with proxy.
Another possibility is combination of gradle + android studio config. Check https://stackoverflow.com/questions/26697118/android-studio-unable-to-find-valid-certification-path-to-requested-target for further reference.

Closing for now. You may ask this in support channels like StackOverflow.

**Comment by FraneCal** [comment]
I am using my company computer to run it which probably uses VPN. Will check out that stackoverflow question.
