### ISSUE TITLE
getting this issue after updating from xcode 16 to xcode 15

### ISSUE THREAD

**Issue by AdwaidSuresh001** [flutter/flutter#156465]
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
2
    { platform:iOS Simulator, id:5D168DF6-7EE9-4AEE-91D7-CC9B0B5EF3FE, OS:17.5, name:iPhone 15 Pro Max }
    ** BUILD FAILED **

**Comment by danagbemava-nc** [comment]
Hi @AdwaidSuresh001, please provide the full verbose output of the command that you ran along with the output of `flutter doctor -v`. 

Please also provide your `Podfile` & `Podfile.lock`

Thank you

PS: In the future, please provide all/some of the information requested in the template.

**Comment by AdwaidSuresh001** [comment]
//podfile
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  platform :ios, '12.0'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#   end
# end
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end
end

//appdeligate.swift

import UIKit
import Flutter
import FirebaseCore
import CleverTapSDK
import clevertap_plugin
// This is required for calling FlutterLocalNotificationsPlugin.setPluginRegistrantCallback method.
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    CleverTap.autoIntegrate() // integrate CleverTap SDK using the autoIntegrate option
    CleverTapPlugin.sharedInstance()?.applicationDidLaunch(options: launchOptions)
    if #available(iOS 10.0, *) {
    UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
//flutter doctor

**Comment by danagbemava-nc** [comment]
Hi @AdwaidSuresh001, you have commented out the step that does some additional configuration for flutter and the plugins, i.e 

```
installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
 end
```

Kindly add it back and see if you're still able to build or not. 

You should be able to add it as another block in the post_install script, so your post_install script could look like this


```
post_install do |installer|
  installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end
end
```

Make sure it is properly formatted in your IDE

**Comment by AdwaidSuresh001** [comment]
in xcode terminal it says the issue is with fflutter_inappwebview

**Comment by AdwaidSuresh001** [comment]
![Screenshot 2024-10-18 at 3 51 33 PM](https://github.com/user-attachments/assets/55414596-3133-4268-9ead-45aa1ade957f)

**Comment by danagbemava-nc** [comment]
This should be reported on the `flutter_inappwebview` repo. It appears it may have been fixed. See https://github.com/pichillilorenzo/flutter_inappwebview/issues/2221

Make sure you're using the latest version of the plugin. If you still experience this after upgrading to their latest version, please report this on their repo. 

Closing from here. 

Thank you
