### ISSUE TITLE
Tests on macOS cannot simulate the enter key triggering the `onEditingComplete` method of a `TextField`.

### ISSUE THREAD

**Issue by yiiim** [flutter/flutter#156414]
### Use case

When creating tests for #156412, I was unable to simulate the enter key triggering `onEditingComplete` for the `TextField`. When I used `simulateKeyDownEvent(LogicalKeyboardKey.enter)`, it always sent the `insertNewline` message due to the code at https://github.com/flutter/flutter/blob/7976d49686976935df2b87a592b0d5633ba382e1/packages/flutter_test/lib/src/test_text_input_key_handler.dart#L206.

`tester.binding.testTextInput.receiveAction(TextInputAction.done)` also does not satisfy this case, because I am not always sure that the focus is on the `TextField`.

### Proposal

Provide a way to simulate the enter key triggering the `onEditingComplete` method of a `TextField`.

**Comment by darshankawar** [comment]
@yiiim 
Can you try by changing `simulateKeyDownEvent` to `sendKeyEvent` ? See https://github.com/flutter/flutter/pull/117550 for reference and check if it helps in your case or not.

**Comment by yiiim** [comment]
I overlooked the documentation here. As stated in the documentation, I cannot use `tester.sendKeyEvent(LogicalKeyboardKey.enter)` to trigger `onEditingComplete` and `onSubmitted`. This prevents me from testing my case.

https://github.com/flutter/flutter/blob/c077b8c61acd0205f92caa6c05d832bfcb8e0a29/packages/flutter/lib/src/widgets/editable_text.dart#L1438-L1450

**Comment by darshankawar** [comment]
Can you check if [this](https://github.com/flutter/flutter/issues/51244) is similar / resembles your case ?

**Comment by yiiim** [comment]
NO, in my case, which is only in tests, as shown in the code below, I cannot trigger `onEditingComplete` using `await tester.sendKeyEvent(LogicalKeyboardKey.enter);`. Although I can trigger it using `await tester.testTextInput.receiveAction(TextInputAction.done)`, in my case, I am not sure if the focus is on the `TextField`. For example, in #143505, it is not possible to perform a regression test for that issue. An alternative approach is to test whether the `TextField` has focus.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets(
    "my test",
    (tester) async {
      bool isEditingComplete = false;
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Center(
              child: TextField(
                autofocus: true,
                onEditingComplete: () {
                  isEditingComplete = true;
                },
              ),
            ),
          ),
        ),
      );
      await tester.sendKeyEvent(LogicalKeyboardKey.enter);
      await tester.pumpAndSettle();
      expect(isEditingComplete, true);
    },
  );
}
```

**Comment by justinmc** [comment]
@dkwingsmt Does this line (linked in the description) look correct for a Mac keyboard's enter key in tests, or was it a mistake?

https://github.com/flutter/flutter/blob/7976d49686976935df2b87a592b0d5633ba382e1/packages/flutter_test/lib/src/test_text_input_key_handler.dart#L206

**Comment by yiiim** [comment]
I have some additional findings: `await tester.testTextInput.receiveAction(TextInputAction.done);` triggers `onEditingComplete` when the focus is on a child of the `TextField` (such as the suffix), which should not happen. If the focus is outside the `TextField`, it correctly does not trigger `onEditingComplete`.

``` dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets(
    'my test',
    (WidgetTester tester) async {
      int onEditingCompleteCallTimes = 0;
      FocusNode textFieldFocusNode = FocusNode();
      FocusNode suffixIconButtonFocusNode = FocusNode();
      FocusNode iconButtonFocusNode = FocusNode();
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Center(
              child: Column(
                children: [
                  IconButton(
                    onPressed: () {},
                    icon: const Icon(Icons.search),
                    focusNode: iconButtonFocusNode,
                  ),
                  TextField(
                    focusNode: textFieldFocusNode,
                    onEditingComplete: () {
                      onEditingCompleteCallTimes++;
                    },
                    decoration: InputDecoration(
                      suffix: IconButton(
                        onPressed: () {},
                        icon: const Icon(Icons.search),
                        focusNode: suffixIconButtonFocusNode,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      );
      textFieldFocusNode.requestFocus();
      await tester.pump();
      await tester.testTextInput.receiveAction(TextInputAction.done);
      await tester.pump();
      expect(onEditingCompleteCallTimes, 1); // Passes

      suffixIconButtonFocusNode.requestFocus();
      await tester.testTextInput.receiveAction(TextInputAction.done);
      await tester.pump();
      expect(onEditingCompleteCallTimes, 2); // Passes, but should fail, 

      iconButtonFocusNode.requestFocus();
      await tester.testTextInput.receiveAction(TextInputAction.done);
      await tester.pump();
      expect(onEditingCompleteCallTimes, 3); // Fails
    },
    variant: TargetPlatformVariant.only(TargetPlatform.macOS),
  );
}

```

**Comment by yiiim** [comment]
Sorry, I should have awaited `tester.pump();` after requesting focus. Closing this issue.
