### ISSUE TITLE
[Flutter Web] TextFormField not working properly in release mode - Issues with typing and "space" key

### ISSUE THREAD

**Issue by AdrielCosta420** [flutter/flutter#156421]
### Steps to reproduce

Create a custom widget for the TextFormField as shown in the code example below.
Build the Flutter Web project with the following command:

`flutter build web --no-tree-shake-icons --release --web-renderer auto`

Open the generated project in the browser in release mode.
Try typing text into the TextFormField field and check the behavior of the keyboard keys, especially the 'space' key.

### Expected results

The TextFormField should allow normal typing, including the use of the 'space' key, as it does in debug mode.

### Actual results

In release mode, the TextFormField often doesn't accept typing.
When typing works, the 'space' key doesn't respond correctly.
In debug mode, the TextFormField works as expected, with no issues.

### Code sample

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class TextFieldBorderWidget extends StatelessWidget {
  final TextEditingController? textController;
  final String? label;
  final String? hintText;
  final int? maxLines;
  final Function(String)? onChanged;
  final double? width;
  final double? height;
  final String? initialValue;
  final String? Function(String?)? validator;
  final TextInputType? keyboardType;
  final List<TextInputFormatter>? inputFormatters;
  final Widget? prefixIcon;
  final bool? enabled;
  final bool obscureText;
  final Widget? suffixIcon;
  final void Function(String)? onFieldSubmitted;

  const TextFieldBorderWidget({
    super.key,
    this.textController,
    this.label,
    this.hintText,
    this.maxLines,
    this.onChanged,
    this.width,
    this.height,
    this.initialValue,
    this.validator,
    this.keyboardType,
    this.inputFormatters,
    this.prefixIcon,
    this.enabled,
    this.obscureText = false,
    this.suffixIcon,
    this.onFieldSubmitted,
  });

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: width,
      height: height,
      child: TextFormField(
        obscureText: obscureText,
        enabled: enabled,
        validator: validator,
        keyboardType: keyboardType,
        inputFormatters: inputFormatters,
        initialValue: initialValue,
        style: TextStyle(
          fontSize: 13,
          letterSpacing: 0.1,
          fontWeight: FontWeight.w400,
          color: Colors.black,
        ),
        onFieldSubmitted: onFieldSubmitted,
        onChanged: onChanged,
        controller: textController,
        decoration: InputDecoration(
          prefixIcon: prefixIcon,
          suffixIcon: suffixIcon,
          contentPadding: const EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
          hintText: hintText ?? label,
          hintStyle: TextStyle(
            color: Colors.grey.shade400,
            fontSize: 12,
            letterSpacing: 0.1,
          ),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(6),
            borderSide: const BorderSide(),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(6),
            borderSide: BorderSide(
              color: Colors.grey.shade400,
            ),
          ),
          filled: true,
          fillColor: Colors.white,
        ),
        maxLines: maxLines ?? 1,
      ),
    );
  }
}

```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [versÆo 10.0.19045.4894], locale pt-BR)
    • Flutter version 3.24.3 on channel stable at C:\Users\Adriel\.puro\envs\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Adriel\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35303.130
    • Windows 10 SDK version 10.0.22621.0
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code, 64-bit edition (version 1.93.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.19045.4894]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.79

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by huycozy** [comment]
Hi @AdrielCosta420 
The sample code is missing the usage of custom TextFormField. Also, there are numerous attributes in the class. It's essential to narrow the class by removing irrelevant attributes to the issue. Please provide such an example. Thanks!

**Comment by AdrielCosta420** [comment]
I tested changing textfomfield to textfield and apparently, after clearing the cache or testing in the incognito tab, it responded as expected. The problem is that the 'initial value' and 'validator' attributes are not part of the textfield widget.

**Comment by huycozy** [comment]
Your usage code above contains application code, it's not runnable for me. So I used the first sample code of [TextFormField](https://api.flutter.dev/flutter/material/TextFormField-class.html). I don't see the issue happen here when building app with command line as reported:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(home: MyApp()),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextFormField(
              initialValue: 'Peter Parker',
              decoration: const InputDecoration(
                icon: Icon(Icons.person),
                hintText: 'What do people call you?',
                labelText: 'Name *',
              ),
              onSaved: (String? value) {
                // This optional block of code can be used to run
                // code when the user saves the form.
              },
              validator: (String? value) {
                return (value != null && value.contains('@')) ? 'Do not use the @ char.' : null;
              },
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

https://github.com/user-attachments/assets/145431d2-930a-4950-8a93-aca210def932

Please try this sample code and confirm. If the issue only occurs with your code, you should narrow it down until having a 
[completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.

**Comment by AdrielCosta420** [comment]
I would like to inform you that I managed to solve the problem, apparently, it was my state management that was rebuilding the screen, causing the inputs to get stuck. Thank you for your willingness to help!

**Comment by huycozy** [comment]
You're welcome. Closing this as it's not a Flutter framework but an implementation issue.
