### ISSUE TITLE
[Impeller] Delete the STB typographer backend.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#156429]
AFAICT, after the typography changes to libImpeller, this backend will be unused and not feature complete.

We should delete it.

**Comment by chinmaygarde** [comment]
I'll followup to once the one user we know of is no longer using it and has migrated to using the libImpeller.

**Comment by jonahwilliams** [comment]
Unless they're rolling at head we could delete this before they migrate.

**Comment by chinmaygarde** [comment]
Yeah, I don't think they are.
