### ISSUE TITLE
impeller: opengles backend doesn't render lines

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#156438]
The tests introduced in https://github.com/flutter/engine/pull/55717 don't render the lines in the opengles backend.

## seen result
<img width="1235" alt="Screenshot 2024-10-08 at 3 17 32 PM" src="https://github.com/user-attachments/assets/ab6fc757-82d8-4598-9ae3-c1d26825c56f">

## expected result
<img width="1225" alt="Screenshot 2024-10-08 at 3 16 35 PM" src="https://github.com/user-attachments/assets/08d47a08-bb24-4007-8c1d-b75056067436">

**Comment by jason-simmons** [comment]
The line rendering behavior changed with https://github.com/flutter/engine/commit/19ef4a9c0c1129ef7dcf3f8848f70842a946228f

This renders consistently on Vulkan and GLES if I patch `LineGeometry::ComputePixelHalfWidth` to set `min_size = 1.0 / max_basis`
