### ISSUE TITLE
ARM and x86 Emulator hang on non-primary monitor

### ISSUE THREAD

**Issue by DetonatorB** [flutter/flutter#15648]
## Steps to Reproduce

I have a fresh install of Android studio and flutter on a multi-monitor (3) setup (AMD Radeon R9 380).

Install Android Studio 3.0.1
Install Android Studio plugins
Install flutter using flutter doctor

Create a new flutter project.
Change nothing.
Run on simulator (either the ARM of x86 based emulator will reproduce problem. Running on device works fine).
Drag the simulator to a non-primary monitor.
The simulator will hang, a message of a 'Qt event loop' hanging message in the IDE.

## Logs
```
IDE: Emulator: emulator: ERROR: detected a hanging thread 'Qt event loop'. No response for 15001 ms
```
## Workaround

Always keep the emulator on the primary screen. If you happen to have moved it, it will hang next time as the last window location is kept. I just made sure the emulator was killed, temporarily disconnected 2nd and 3rd monitor, restarted the emulator to force it onto the primary monitor, moved it a bit to make sure the location was stored, re-attached the monitors and everything was fine. Just remember not to move it to a non-primary screen.
For use with multiple monitors, this is extremely annoying.

Does anybody have a solution to this?

## Flutter Doctor
```
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale nl-NL)
    • Flutter version 0.1.5 at J:\flutter\flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\columnae\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: J:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at J:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices (3 available)
    • Android SDK built for x86 • emulator-5556   • android-x86 • Android 6.0 (API 23) (emulator)
    • C4F1253018AF26E           • C4F1253018AF26E • android-arm • Android 4.0.4 (API 15)
    • sdk google phone armv7    • emulator-5554   • android-arm • Android 6.0 (API 23) (emulator)

• No issues found!
````

**Comment by DetonatorB** [comment]
Thanks for your time. Unfortunately this does not help. And the more I think of it, it must be the emulator itself. Starting just the emulator (just booting Android, no apps running) on primary screen works. Just dragging it to a non-primary screen after that makes it hang. So I think this is not a flutter issue, but an emulator issue.
What do you think?
Where should I drop this issue?

**Comment by 741g** [comment]
@DetonatorB Please file them in https://issuetracker.google.com/issues?q=componentid:192727

**Comment by zoechi** [comment]
I'm going to close because this is not a Flutter issue.
