### ISSUE TITLE
Outdated main.dart is always run.

### ISSUE THREAD

**Issue by ansaardollie** [flutter/flutter#15649]
## Steps to Reproduce

This applies to all my flutter  projects but will reproduce a general case. 
I use Intellij but experience the same issue with CLI 

1) Create new flutter project ( Intellij: File >> New >> Project.. > Flutter Project | CLI: `flutter create run_issue` )
2) Run project (IntelliJ: Run >> Run 'main.dart' | CLI : `flutter run`)
3) Notice primary theme color is blue
4) Quit Application
5) Edit primary color in main.dart 
Change
`primarySwatch: Colors.blue` 
to
`primarySwatch: Colors.red`
6) Save main.dart
7) Run project again 
8) Notice primary theme color is still blue.
9) Hot reload 
10) Notice color has changed 
11) Quit Application
12) Run project again
13) Notice once again primary theme color is still blue

If you delete /build directory and run project the color will change. However deleting build directory each time you change something is cumbersome and unrealistic.

## Logs

Result of `flutter run`
`
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                3.8s
Resolving dependencies...                             4.8s
Running 'gradlew assembleDebug'...                    4.4s
Built build\app\outputs\apk\debug\app-debug.apk (24.6MB).
I/FlutterActivityDelegate( 9444): onResume setting current activity to this
Syncing files to device Android SDK built for x86 64...  4.6s`

Result of `flutter analyze`

`Analyzing C:\Users\Ansaar Dollie\test\run_issue...
No issues found!
Ran in 14.3s`

## Flutter Doctor

`[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.1.5 at C:\Users\Ansaar Dollie\Software\Tools\flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Ansaar Dollie\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] VS Code (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

• No issues found!`

**Comment by jonahwilliams** [comment]
@ansaardollie What happens when you use the "Restart the flutter app" option in Intellij?

**Comment by ansaardollie** [comment]
@jonahwilliams When the app is run, running old code, and then restarted then the updated code will be run. However once you terminate the app and then run the app again the outdated project will run.

**Comment by jonahwilliams** [comment]
@ansaardollie anything that is defined in `main` won't be hot reloaded, since `main` is only invoked once.  I would recommend placing the majority of your code within custom widgets.

**Comment by ansaardollie** [comment]
@jonahwilliams My issue isn't with the Hot Reload features. It is that when no app is running , and I update code, one run again the app won't run the  updated code but rather the outdated code.

**Comment by zoechi** [comment]
I had similar experience a few times where only `flutter clean` fixed it.

**Comment by zoechi** [comment]
It still happens to me frequently and also feedback from others indicates that `flutter clean` is frequently necessary to fix such issues.

**Comment by zoechi** [comment]
@ansaardollie is this still an issue.
This got much better for me lately (using `master`)

Probably a dup of #16604
