### ISSUE TITLE
[video_player] Video getting stuck at app launch on some devices. 

### ISSUE THREAD

**Issue by dishankjindal1** [flutter/flutter#156449]
I am getting Future Already Completed in firebase crashlytics ARN. No issues on iOS.

I am playing the video during app launch via asset file. And it makes the app unresponsive for some users. And what i observed clearing the cache of app makes it run properly.
 
video which is used for running on the devices.
https://github.com/user-attachments/assets/e9297888-685a-41e3-8c6c-0ba2848b17d0

source code for reference
```
class SplashScreen extends ConsumerStatefulWidget {
  const SplashScreen({super.key});

  @override
  ConsumerState<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends ConsumerState<SplashScreen>
    with AppStorageMixin {
  final videoPlayer =
      VideoPlayerController.asset(RiverAsset.fullscreenLogoAnimation);

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addPostFrameCallback((_) {
      initalize();
    });
  }

  Future<void> initalize() async {
    try {
      getRef<AnalyticsService>().logEvent(
        '$runtimeType',
        description: 'Started',
      );

      await videoPlayer.initialize().then((_) async {
        if (mounted) {
          setState(() {
            /// Refresh Ui
          });
        }
        await Future.delayed(Duration(milliseconds: 100));
        if (mounted) {
          setState(() {
            videoPlayer.play();
          });
        }
      });

      if (!getRef<AuthService>().loggedStatus)
        getRef<AuthService>().shuffleTokens();
      await Future.delayed(videoPlayer.value.duration);


      context.go(
        getRef<AuthService>().navigationRedirect ?? HomeScreenRoute.path,
      );

      getRef<AnalyticsService>().logEvent(
        '$runtimeType',
        description: 'Ended',
      );
    } catch (e) {
      getRef<AnalyticsService>().logEvent(
        '$runtimeType',
        description: 'Error : $e',
      );

      if (e is DioException) {
        if (e.response?.statusCode == 403) {
          late final OverlayEntry entry;

          entry = OverlayEntry(
            builder: (context) => ReloginPopup(callback: entry.remove),
          );

          Overlay.of(context).insert(entry);
        }
      }

      context.go(
          getRef<AuthService>().navigationRedirect ?? EnterMobileRoute.path);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: const SystemUiOverlayStyle(
        systemNavigationBarColor: RiverColorPalette.riverBlue05,
        systemNavigationBarIconBrightness: Brightness.dark,
        systemNavigationBarDividerColor: RiverColorPalette.riverBlue05,
        statusBarIconBrightness: Brightness.light,
        statusBarColor: Colors.transparent,
        statusBarBrightness: Brightness.dark,
      ),
      child: Material(
        color: RiverColorPalette.riverBlue05,
        child: videoPlayer.value.isInitialized
            ? SizedBox(
                height: 100.hs(context),
                width: 100.ws(context),
                child: OverflowBox(
                  minHeight: 110.hs(context),
                  maxHeight: 110.hs(context),
                  maxWidth: 100.ws(context),
                  minWidth: 100.ws(context),
                  child: AspectRatio(
                    aspectRatio: videoPlayer.value.aspectRatio,
                    child: VideoPlayer(videoPlayer),
                  ),
                ),
              )
            : const SizedBox.shrink(),
      ),
    );
  }
}
```

Stack trace from the firebase crashlytics

> Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Future already completed
>        at _AsyncCompleter.complete(dart:async)
>        at VideoPlayerController.initialize.eventListener(video_player.dart:468)

plugin version - video_player: 2.9.1
flutter version 
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /Users/dishankjindal/.puro/envs/3.24.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dishankjindal/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.94.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

**Comment by huycozy** [comment]
Hi @dishankjindal1 
Do you see any stack trace of ANR on the crashlytic report? Please share it if any.

Can you reproduce the ANR locally if running project in `release` mode? If it appears this case, please try to narrow sample code down into a minimal one (without 3rd party packages) and share it here.

And please also provide:
- Flutter and `video_player_android` versions used when you build the project
- List of affected device information (model, OS version) along with the percentage occurrence of the crash

**Comment by dishankjindal1** [comment]
@huycozy - updated my response above.

**Comment by matanlurey** [comment]
This was already fixed in `video_player_android: ^2.7.6` (https://pub.dev/packages/video_player_android/changelog#276).

**Comment by dishankjindal1** [comment]
@matanlurey - I am on plugin version - video_player: 2.9.1 

Which means, this still requires some attention, maybe you can keep this issue open. Because my prod customers are facing this issue.

**Comment by matanlurey** [comment]
Your two options are using an older version that works for you or using the newer version with the fix, there is nothing we can do for an already published version.

**Comment by matanlurey** [comment]
Just to be clear @dishankjindal1,

**Comment by dishankjindal1** [comment]
@matanlurey - I had pushed the app to prod users with the latest video player version. I am seeing a lot of events.

<img width="1150" alt="Screenshot 2024-10-10 at 12 09 41 AM" src="https://github.com/user-attachments/assets/42b579b8-d729-4c7d-acad-c402a88ac9e9">

**Comment by matanlurey** [comment]
Without a repro we won't be able to help.

**Comment by dishankjindal1** [comment]
@matanlurey - by any change, can the video be a problem in my simple usecase? because previously it never use to run, and after converting the video encoding to a different format worked.

**Comment by dishankjindal1** [comment]
@matanlurey You can use the video i provided just after the app launch, using initState call. No special code is required.
