### ISSUE TITLE
Material shadowColor field is ignored if child contains a TextField

### ISSUE THREAD

**Issue by theEpicality** [flutter/flutter#15641]
## Steps to Reproduce

I created a custom widget based off of the Card widget found in 'flutter/src/material/card.dart' to customize the shadow effects:
```
class CustomCard extends StatelessWidget {
  const CustomCard({
    Key key,
    this.color,
    this.elevation: 2.0,
    this.child,
    this.shadowColor, // added
  }) : super(key: key);

  final Widget child;
  final Color color;
  final double elevation;
  final Color shadowColor; // added

  @override
  Widget build(BuildContext context) {
    return new Semantics(
      container: true,
      child: new Container(
          margin: const EdgeInsets.all(4.0),
          child: new Material(
            shadowColor: shadowColor, // added
            color: color,
            type: MaterialType.card,
            elevation: elevation,
            child: child,
            borderRadius: new BorderRadius.circular(6.0), // added
          )
      ),
    );
  }
}
```
The card looks wonderful but I noticed that when I add a TextField as a child of the custom card, the shadow color defaults to black as opposed to the light gray color I've set it to.

### 1. Card appearance before adding the TextField:
![Screenshot 1](https://i.imgur.com/257lwds.png "Screenshot 1")
### 2. Card appearance after adding nothing more than an empty TextField:
Notice that the shadow is significantly darker even though the only thing that has been changed in the main.dart file is the TextField widget

![Screenshot 2](https://i.imgur.com/wpDLise.png "Screenshot 2")

Another thing to note is that I've also been messing with the borderRadius property and it works as expected regardless of whether the TextField is there or not.

## Flutter Doctor

[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.12.6 16G29, locale en-US)
    • Flutter version 0.1.5 at /Users/nathanbird/flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/nathanbird/Library/Android/sdk
    • Android NDK at /Users/nathanbird/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] VS Code (version 1.19.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Nexus 6P • 84B7N16804000234 • android-arm64 • Android 8.1.0 (API 27)

**Comment by theEpicality** [comment]
@jonahwilliams, interestingly, the elevation isn't actually changing. What's happening is that the custom shadow color is being ignored when the TextField is inside a material widget

**Comment by jonahwilliams** [comment]
@theEpicality you're right, I see that too now.

Reproduced in this example: https://gist.github.com/jonahwilliams/26b63c58efd8e899bd3495047864cea3

### Comparisons
The left screenshot shows a material canvas with a slightly green shadow.  Toggling the `TextField` child changes the shadow to have the default color values on the right.

<img  width="250" src="https://user-images.githubusercontent.com/8975114/37571826-049875ba-2abf-11e8-90c1-534c3034506a.png"> <img width="250" src="https://user-images.githubusercontent.com/8975114/37571829-0d5874b6-2abf-11e8-99da-794cbd61341a.png">

Same setup, but with default colors.  The elevation appears to change slightly when toggling the `TextField`.  (I'm not sure that this one is a bug)


<img  width="250" src="https://user-images.githubusercontent.com/8975114/37571832-13810010-2abf-11e8-94d2-5f94057c1a3d.png"><img  width="250" src="https://user-images.githubusercontent.com/8975114/37571847-4e949126-2abf-11e8-802b-3216e0002836.png">

**Comment by jonahwilliams** [comment]
Update: I've found the issue and I've started working on a fix.

**Comment by theEpicality** [comment]
Awesome! I've been building around it anyways. No rush.

**Comment by jonahwilliams** [comment]
@theEpicality This should be fixed on master!

**Comment by theEpicality** [comment]
Awesome, thank you!

**Comment by kezzbr** [comment]
The same behaviour, placing TextField inside a Card, is messing with the border radius as well. Visible the border is getting worse. The pixelation of it is very notable.

See a comparison using TextField and not:

![img_2098](https://user-images.githubusercontent.com/3750220/45511656-f7b8b700-b773-11e8-843d-ea948738b426.PNG)

![img_2097](https://user-images.githubusercontent.com/3750220/45511669-0010f200-b774-11e8-9faf-24c921499956.PNG)

**Comment by jonahwilliams** [comment]
@kezzbr _please_ file a new issue instead of commenting on old ones.
