### ISSUE TITLE
[CP-beta] Flutter tool assumes impeller is enabled by default

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#156546]
### Issue Link

https://github.com/flutter/flutter/issues/132712

### Target

beta

### Cherry pick PR Link

https://github.com/flutter/flutter/pull/156545

### Changelog Description

Enables proper analytics reporting for default impeller.

### Impacted Users

Flutter Android Devs

### Impact Description

Our analytics will be wrong

### Workaround

None.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the tests that were included.

**Comment by zanderso** [comment]
CP LGTM

**Comment by reidbaker** [comment]
@jtmcdole I updated this because it is targeting 3.27 which is actually beta.

**Comment by jtmcdole** [comment]
Thank you, @reidbaker!
