### ISSUE TITLE
[Android] lifecycle events dropped due to thread merging changes.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#156595]
The engine roll here https://github.com/flutter/flutter/pull/156562 was reverted for consistent failures in the framework postsubmit test ` Linux_mokey flutter_gallery__back_button_memory`

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_mokey%20flutter_gallery__back_button_memory/1629/overview

Wondering if https://github.com/flutter/engine/pull/55810 was related @jonahwilliams

P0 since this is blocking the engine -> framework roll.

**Comment by zanderso** [comment]
Is the theory that the delay here is not long enough? https://github.com/flutter/flutter/blob/7424766f2c5ade4b6a16f367ec32304a669f71b8/dev/devicelab/lib/tasks/perf_tests.dart#L2010

**Comment by jonahwilliams** [comment]
Sorry, wrong test: see https://github.com/flutter/flutter/pull/156596

I can repro this locally easily enough 

The test waits for a message to be printed after backgrounding the app: https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_gallery__back_button_memory.dart#L35

The app prints the message. But the logreader doesn't get the message for some reason. Maybe the device log reader stops when the app is closed? Or there is some other race condition.

But the app itself is functional

**Comment by jonahwilliams** [comment]
Closing as fixed

**Comment by zanderso** [comment]
Thanks!

**Comment by jason-simmons** [comment]
I'm seeing a difference in behavior with the platform/UI thread merge.

With https://github.com/flutter/engine/commit/2eedaf147b9f164f188618b2a6c7137c6903c671, if I navigate back in an Android app the framework only receives the `flutter/lifecycle` channel message for the `AppLifecycleState.inactive` state.

The Android embedding does try to send the messages for `AppLifecycleState.paused` and `AppLifecycleState.detached`.  However, those messages are not reaching the framework.
 `Shell::OnPlatformViewDispatchPlatformMessage` queues those message send tasks to the UI task runner.  But by the time the tasks execute, the engine has been deleted and the messages can not be sent.

If `Shell::OnPlatformViewDispatchPlatformMessage` is patched to use `fml::TaskRunner::RunNowOrPostTask(task_runners_.GetUITaskRunner())` for the send task, then that causes a different outcome.
With that patch, the Android back gesture only sends a `flutter/navigation` message and does not suspend the application.  Doing the back gesture a second time will suspend the app and send all of the expected `flutter/lifecycle` messages.

@jonahwilliams Is this expected?  Will there be any issues if applications do not see the full series of lifecycle events before shutdown?

**Comment by jonahwilliams** [comment]
When closing applications there are no guarantees that you can or will receieve any lifecycle events. See https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html

> Applications should not rely on always receiving all possible notifications.

**Comment by jason-simmons** [comment]
Changing `Shell::OnPlatformViewDispatchPlatformMessage` to call `RunNowOrPostTask(ui_task_runner)` does not complete the back navigation action because microtasks are not being run.  If the UI and platform threads are merged and `RunNowOrPostTask` runs the message send task immediately, then the message loop does not invoke the task observer callback that drains any pending microtasks.

The navigation will finish if you interact with the application in any way that will cause execution of microtasks.

I was able to get the UI/platform thread merge to deliver all of the  `AppLifecycleState` events with a different patch.  If the threads are merged then `Shell::OnPlatformViewDispatchPlatformMessage` can dispatch the message on the current thread and then queue an empty task to force execution of microtasks.

```
    if (task_runners_.GetUITaskRunner()->RunsTasksOnCurrentThread()) {
      engine_->DispatchPlatformMessage(std::move(message));
      task_runners_.GetUITaskRunner()->PostTask([] {});
    } else {
      task_runners_.GetUITaskRunner()->PostTask(
        fml::MakeCopyable([engine = engine_->GetWeakPtr(),
                           message = std::move(message)]() mutable {
          if (engine) {
            engine->DispatchPlatformMessage(std::move(message));
          }
        }));
    }
```

But I'm not sure if this is worthwhile unless applications are relying on the current behavior.

**Comment by jonahwilliams** [comment]
I would be happy to review a PR that added the above code.
