### ISSUE TITLE
firebase_database. await operations not working when offline. (even when using local persistence enabled)

### ISSUE THREAD

**Issue by StephaneBischoff** [flutter/flutter#15653]
## Steps to Reproduce

1) using firebase_database plugin version 0.4.0
2) using code
```dart
// Opening database and setting local persistence (keep sync)
_database = FirebaseDatabase.instance;
_database.setPersistenceEnabled(true);
_database.setPersistenceCacheSizeBytes(10000000);
_myReference = _database.reference().child('users/${user.uid}');
_myReference.keepSynced(true);
```
**When online (Wifi connectivity)**
```dart
var snapshot = await _myReference.once();
print(snapshot.value);
```

await works. Once() returns and print statement is called.

**When offline (NO Wifi connectivity)**
**IMPORTANT: When there is no connectivity before launching the mobile app**
If the database was initialized prior to losing connectivity, then the await calls work as expected.
```dart
var snapshot = await _myReference.once();
print(snapshot.value); <=== NEVER CALLED
```
await does not work. Once() never returns and print statement is never called.

## Expected Behavior

Offline support in firebase_database should work when user has no connectivity prior to opening the mobile app.

## Logs

Not applicable. There are no logs that I can see which would help debugging here.
No exceptions, no stack trace from Flutter or anything else.

## Flutter Doctor
```
[√] Flutter (Channel dev, v0.1.7, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 0.1.7 at C:\Workspace_Flutter\flutter
    • Framework revision 3b84503403 (3 weeks ago), 2018-02-26 20:11:11 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\stephanebi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • H1621 • W7TDU16827002676 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
```
**IT's OK, not using VS Code with Flutter.**

**Comment by GreeenPig** [comment]
`_database.setPersistenceEnabled(true);`
Are you sure this line is returning true?
In my case this line was failing (returning false) because of a race condition between the setPersistenceEnabled method and the next few lines of database code.

I waited until the setPersistenceEnabled is actually completed (returns true) before doing the other database functions and the persistence works.

The [firebase_database example app](https://github.com/flutter/plugins/tree/master/packages/firebase_database) seems to have the same issue.

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by b-cancel** [comment]
Can we get an update on this please, it's essential that the database works offline for the app I'm building

**Comment by probuse** [comment]
I am facing the same challenge, await operations do not work when app is offline.
How can i enable await operations to work offline in my app. ???

**Comment by krooq** [comment]
I too have this issue using firebase_database 2.0.1+1 and flutter
I'm rather surprised this has been an open issue for almost a year, this is essentially breaking offline mode as there is no way to be sure whether data exists or not at a reference.

Has someone found an acceptable work around?

**Comment by krooq** [comment]
I've just tried this using a "then" on the future instead of async await and it works!

**Comment by krooq** [comment]
Ok, so a bit more information.

var snapshot = await _myReference.once()
Uses the firebase onValueChanged event.  If you have no data, nothing changes.
More info here:
https://stackoverflow.com/questions/42430992/firebase-ondatachange-not-called-when-offline

One solution is to attach a listener to
_myReference.onValue

Then you always get data events, even null.
If you want to synchronize with the cache you should prime your reference with default data as suggested in the above stackoverflow thread.

**Comment by spedalilama** [comment]
I have encountered the same issue, firebase await operations don't work when offline, and I have persistence enabled which returned true.  This is a major issue for my apps, any update on this?

**Comment by kroikie** [comment]
@StephaneBischoff

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/885. Any further collaboration will be done there.
