### ISSUE TITLE
Card Widgets does not support white color and rest of Colors supports

### ISSUE THREAD

**Issue by ut7174** [flutter/flutter#156579]
### Steps to reproduce

 Card widgets do not support a white color. However, they do support a variety of other colors. 

### Expected results

Card Widgets does not support white color and rest of Colors supports I want card also support white color

### Actual results

Default Flutter color show when use white 

### Code sample

<details open><summary>Code sample</summary>

```dart
 Widget _buildProfileCard() {
    return Card(
      color: Colors.white,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          children: [
            const CircleAvatar(
              radius: 30,
              backgroundImage: AssetImage('assets/Ellipse 3067.png'),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Alexander Michael',
                    style: GoogleFonts.poppins(
                      fontSize: 18.sp,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  Text(
                    '+91 9410000123',
                    style: GoogleFonts.poppins(
                      fontSize: 14.sp,
                      color: Colors.grey[600],
                    ),
                  ),
                ],
              ),
            ),
            const Icon(Icons.edit, color: Color(0xFF3F51B5)),
          ],
        ),
      ),
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 15.0 24A335 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    ! iOS 18.0 Simulator not installed; this may be necessary for iOS and macOS development.
      To download and install the platform, open Xcode, select Xcode > Settings > Platforms,
      and click the GET button for the required platform.

      For more information, please visit:
        https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (3 available)            
    ! Error: Browsing on the local area network for Ashish’s iPhone (2). Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.

codenia@Codenias-MacBook-Pro givzo % 
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ut7174, you're using an older version of flutter. Kindly upgrade to the latest version of flutter stable to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v` along with a complete minimal reproducible code sample so that we can properly investigate this.

Any screenshots of the issue would also help.

Thank you

**Comment by nate-thegrate** [comment]
Here's a DartPad code sample that correctly displays a white card: https://dartpad.dev/?id=152b044160cb0f2c44a766cbd3d550e3

@ut7174 I recommend double-checking the "surface tint color"; it's possible that setting `surfaceTintColor` to white would resolve your issue.

If not, please update the comment so that the code sample can be copy-pasted & run (for example via DartPad) as @danagbemava-nc has suggested.

<br>

Thank you!
