### ISSUE TITLE
Editing one playground test has a turn around time of 20s

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#156504]
I think a fair portion of this time is setting up RBE which probably cost more time to setup than it saves when just compiling one file.  There is also 4.4 seconds before VSCode even appears to be launching the build and 5 seconds between it finishing and the playground actually showing.

Also note that the C++ Test Mate is only building the `impeller_unittests` target, so it's just linking one thing.

## steps to reproduce

1) open the engine.workspace
1) execute one of the playground impeller_unittests tests
1) edit the test
1) execute the test again
1) notice it takes 20 seconds before the playground displays

## expected results
I think I would expect it to be about twice as fast.

## video
https://github.com/user-attachments/assets/82f372cd-91fa-4a16-9c91-4d5b7a2432fb

**Comment by matanlurey** [comment]
```sh
flutter % time et build -c host_debug_unopt_arm64 //flutter/impeller:impeller_unittests
[2024-10-09T15:38:27.974][macos/host_debug_unopt_arm64: GN]: OK
[2024-10-09T15:38:29.203][macos/host_debug_unopt_arm64: RBE startup]: Proxy started successfully.
[2024-10-09T15:38:34.436][macos/host_debug_unopt_arm64: ninja]: 100.0% (3/3) LINK ./impeller_unittests
[2024-10-09T15:38:34.439][macos/host_debug_unopt_arm64: ninja]: OK
[2024-10-09T15:38:34.786][macos/host_debug_unopt_arm64: RBE shutdown]: Actions completed: 1 (1 cache hit)
$ENGINE/flutter/bin/et build -c host_debug_unopt_arm64   4.49s user 1.30s system 70% cpu 8.230 total
```

Fwiw I get a much smaller number.

If you wanted to determine if RBE is the cause of your slowdown, you could try this patch:

```diff
diff --git a/engine.code-workspace b/engine.code-workspace
index 491b6a4451..4db6032ba5 100644
--- a/engine.code-workspace
+++ b/engine.code-workspace
@@ -235,6 +235,7 @@
         "command": "./flutter/bin/et",
         "args": [
           "build",
+          "--build-strategy=local",
           "-c",
           "host_debug_unopt_arm64",
           "//flutter/impeller:impeller_unittests"

```

**Comment by gaaclarke** [comment]
18s with the local build for me.  Drat, that probably isn't worth chasing.  I was hoping this would be an easy fix of just selectively ignoring RBE.

**Comment by matanlurey** [comment]
You might need a laptop upgrade if it takes 18s to build a unit test locally 😁
