### ISSUE TITLE
The Material Icons.send_outlined is inconsistent with the spec (and looks ugly).

### ISSUE THREAD

**Issue by Loading102** [flutter/flutter#156552]
### Steps to reproduce

1. See the gist with send_outlined at [dartpad.dev](https://dartpad.dev/?id=97d1e553abdafb406d61e97cfc18729f) (Based on Dart SDK 3.5.3 and Flutter SDK 3.24.3).
2. Run the gist.
3. Go to [fonts.google.com/icons](https://fonts.google.com/icons?icon.query=send&selected=Material+Symbols+Outlined:send:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed&icon.platform=web)
4. Compare. 

### Expected results

The icons should be the same.

### Actual results

The icons are not the same, and the flutter one looks bad.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(_) => MaterialApp(
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
        themeMode: ThemeMode.system,
        home: Icon(Icons.send_outlined),
      );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/0693289b-e415-4651-b3a4-45eecf487429)

![image](https://github.com/user-attachments/assets/dfd3db8b-1e68-4d62-821e-b04039d3711e)

</details>

### Logs

<details open><summary>Logs</summary>

```console
Not applicable
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Not applicable
```

</details>

**Comment by nate-thegrate** [comment]
Flutter is still in the process of transitioning from "Material Icons" to "Material Symbols":

- https://github.com/flutter/flutter/issues/102560

<br>

The ugly icon can be found here: https://fonts.google.com/icons?icon.query=send&selected=Material+Icons+Outlined:send:&icon.size=24&icon.color=%23e8eaed&icon.platform=web&icon.set=Material+Icons

For now, feel free to use the [material_symbols_icons](https://pub.dev/packages/material_symbols_icons) package for getting access to the better-looking ones :)

**Comment by darshankawar** [comment]
> feel free to use the [material_symbols_icons](https://pub.dev/packages/material_symbols_icons) package for getting access to the better-looking ones :)

@Loading102 Please check if this solution works in your case or not.

**Comment by Loading102** [comment]
Thank you, the package is great, and has resolved my issue.
