### ISSUE TITLE
Flutter is embedded into the iOS project as a framework，Error: Multiple commands produce

### ISSUE THREAD

**Issue by pps228** [flutter/flutter#156525]
I created a new empty ios project and an empty flutter module, and then I set the flutter module to a framework, but when I embedded the framework into the iOS project, I found a strange problem. My iOS The project can run normally in Debug mode, but cannot be compiled successfully in release mode, and the following error is reported: 
![2567-10-10 17 38 15](https://github.com/user-attachments/assets/5d39ed3a-8626-423d-b873-2281db4aa67f)

The project's hybrid engineering settings are based on the official Flutter documentation.
lutter build ios-framework --no-debug --no-profile --output=./framework/
![2567-10-10 17 38 27](https://github.com/user-attachments/assets/3de96af4-7524-45ab-881b-b04a77db8496)

![2567-10-10 17 38 31](https://github.com/user-attachments/assets/d8238dc7-1853-403b-bac8-76d4babdf6dd)
I would like to state that I did not write any code in the iOS project and the flutter module, nor did I integrate cocopods. I just did a test to see if the iOS project could integrate the flutter framework normally, and it failed in release mode. I made some attempts based on information on the Internet, such as:
![2567-10-10 17 52 56](https://github.com/user-attachments/assets/96b1e4bb-9090-4b83-b19a-b1fc10d1c5c2)
but this has no effect.
Has anyone encountered the same problem? Can you give me an answer? Thanks!

**Comment by darshankawar** [comment]
@pps228 
Please check [this](https://github.com/flutter/flutter/issues/130220) issue to see if it resonates / is similar to your case or not. 
Also check https://github.com/flutter/flutter/issues/146957

**Comment by michaelnew** [comment]
Ran into exactly this issue. The problem is that building in release mode includes the dSYM files, and both `App.xcframework` and `Flutter.xcframework` include a `Flutter.framework.dSYM` directory. So Xcode errors.

The workaround is to just delete `App.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM`.

I assume it's a bug that `App.xcframework` is including `Flutter.framework.dSYM`. I looks exactly the same as what's in `Flutter.xcframework` so I'm not sure why it's in both places.

**Comment by pps228** [comment]
> Ran into exactly this issue. The problem is that building in release mode includes the dSYM files, and both `App.xcframework` and `Flutter.xcframework` include a `Flutter.framework.dSYM` directory. So Xcode errors.
> 
> The workaround is to just delete `App.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM`.
> 
> I assume it's a bug that `App.xcframework` is including `Flutter.framework.dSYM`. I looks exactly the same as what's in `Flutter.xcframework` so I'm not sure why it's in both places.

This definitely solved my problem, thank you very much!

**Comment by pps228** [comment]
> @pps228 Please check [this](https://github.com/flutter/flutter/issues/130220) issue to see if it resonates / is similar to your case or not. Also check #146957

I don't think it's similar！Thanks!

**Comment by michaelnew** [comment]
@darshankawar @pps228 this really shouldn't be closed. The workaround is easy enough but this is a very hard to understand error. The dSYM generation really need to be fixed so this doesn't happen to everyone trying to integrate Flutter into an iOS app in release mode.

**Comment by pps228** [comment]
> @darshankawar @pps228 this really shouldn't be closed. The workaround is easy enough but this is a very hard to understand error. The dSYM generation really need to be fixed so this doesn't happen to everyone trying to integrate Flutter into an iOS app in release mode.

Taking your advice, I reopened.

**Comment by darshankawar** [comment]
@pps228 and @michaelnew 
A similar issue has been [fixed](https://github.com/flutter/flutter/issues/154019) recently that you can check and confirm. Make sure you are on latest master, as this fix isn't in latest stable yet. See also https://github.com/flutter/engine/pull/54746#issuecomment-2327094531 for further reference.
