### ISSUE TITLE
Power outage in Flutter Devicelab

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#156547]
There is a power outage in the building (it appears the entire block) that houses Flutter's Devicelab.

As of now, I would not expect any Flutter CI tests that require physical phones to be scheduled. I will keep this issue open until we are fully recovered.

**Comment by kentnguyen99** [comment]
Here is ticket for power outage for Building 1240 229486997.

**Comment by christopherfujino** [comment]
I just got an SMS from an internal Google team informing me that "the duration of the power outage is expected to be prolonged." I will continue to provide updates.

**Comment by christopherfujino** [comment]
I'm heading home for the day, I have no other updates on this, and no ETA for when power will be restored. I will check in tomorrow morning.
