### ISSUE TITLE
Error at saving TextEditingController to getter method

### ISSUE THREAD

**Issue by WonderProgrammer** [flutter/flutter#15652]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0,9s
Resolving dependencies...                             1,1s
Running 'gradlew assembleDebug'...                    9,2s
Built build/app/outputs/apk/debug/app-debug.apk (25.1MB).
Installing build/app/outputs/apk/app.apk...           2,2s
I/FlutterActivityDelegate(12900): onResume setting current activity to this
Syncing files to device Android SDK built for x86...  3,0s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8101/
For a more detailed help message, press "h". To quit, press "q".

Analyzing /home/stefan/Schreibtisch/Android/flutter_app...
  lint • Name non-constant identifiers using lowerCamelCase at lib/Details.dart:7:10 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/Details.dart:8:10 • non_constant_identifier_names
  lint • Name types using UpperCamelCase at lib/generated/i18n.dart:29:7 • camel_case_types
  lint • Name non-constant identifiers using lowerCamelCase at lib/Neues_Rezept/beschreibung.dart:12:7 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/Neues_Rezept/beschreibung.dart:13:25 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/Neues_Rezept/Neues_Rezept.dart:16:7 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/Neues_Rezept/neueZutat.dart:11:7 • non_constant_identifier_names
  hint • Unused import: 'package:flutter_test/flutter_test.dart' at lib/Neues_Rezept/beschreibung.dart:3:8 • unused_import
8 issues found.
(Ran in 6.5s)

## Flutter Doctor

[✓] Flutter (Channel beta, v0.1.5, on Linux, locale de_AT.UTF-8)
    • Flutter version 0.1.5 at /home/stefan/flutter
    • Framework revision 3ea4d06340 (vor 3 Wochen), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/stefan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/stefan/Downloads/Programme/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/stefan/Downloads/Programme/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

• No issues found!

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by xqwzts** [comment]
Hi @WonderProgrammer Could you share some more details?

There is no error in the logs you provided, what error are you seeing?
Could you provide a small snippet that reproduces this issue?

Thanks.

**Comment by WonderProgrammer** [comment]
This is the Link to the Files, where the problem appeared: https://github.com/WonderProgrammer/Rezepte-Speichern/tree/master/lib/Neues_Rezept. 
"bearbeiten.dart" saves the textedit Input into a setter-method inside the file "Details.dart" in the parent folder. After that "Neue_Zutat.dart" tries to get the saved variable from the getter-method and at this point the program falls.

**Comment by xqwzts** [comment]
Could you include the error details that appear in your console upon failure?
And perhaps a condensed snippet that can reproduce this error?

**Comment by WonderProgrammer** [comment]
Thanks for your answer, but the problem has solved from itself
