### ISSUE TITLE
SelectionArea: drag from side padding , support select a line.

### ISSUE THREAD

**Issue by toly1994328** [flutter/flutter#156515]
### Use case

when use SelectionArea, select from side padding. code is like:

```dart
SelectionArea(
  child: Container(
  decoration:BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(6)),
  constraints: BoxConstraints(maxWidth: 500),
  padding: EdgeInsets.symmetric(horizontal: 12, vertical: 8),
  child: Text('this is line1\nthis is line2\nthis is line3\nthis is line4'),
  ),
),
```

this video show : drag from side padding , will select from start or end. can't select this line: 

https://github.com/user-attachments/assets/7532a906-e13a-4dbb-954c-74f5efc92f6b

### Proposal

I hope selection like this:

https://github.com/user-attachments/assets/cc22a32c-4232-4317-8982-8ed261e5d59e

**Comment by darshankawar** [comment]
@toly1994328 
What platform are you seeing / running this on ?
Can you also check if your case is similar to https://github.com/flutter/flutter/issues/139890 ?

**Comment by toly1994328** [comment]
Platform is Windows. It's not similar，here SelectionArea with inner padding. 

flutter doctor -v

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.24.3, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
    • Flutter version 3.24.3 on channel stable at D:\SDK\Flutter\flutter3.24.0\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\SDK\Android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\SDK\Android
    • Java binary at: D:\Soft\IDE\AndroidStudio2024\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at D:\Soft\IDE\VS\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at D:\Soft\IDE\AndroidStudio2024
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at D:\Soft\IDE\IntelliJ IDEA 2024.1.4
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 241.18808

[✓] Connected device (4 available)
    • PDNT00 (mobile)   • 1650e3ec • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22631.4317]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 128.0.2739.63

[✓] Network resources
    • All expected network resources are available.

**Comment by darshankawar** [comment]
Check if [this](https://github.com/flutter/flutter/issues/133637) recently fixed issue helps in your case or not.
