### ISSUE TITLE
Installation Error on Mac OS 10.13

### ISSUE THREAD

**Issue by michaelspeed** [flutter/flutter#15661]
Installation failed with error - 

> flutter: line 33: sed: command not found

## Steps to Reproduce
git clone -b beta https://github.com/flutter/flutter.git
export PATH='$path'/flutter/bin:$PATH

tried installing  gnu-sed with default name

## Logs
No Logs
## Flutter Doctor
gives error
> flutter: line 33: sed: command not found

**Comment by michaelspeed** [comment]
anyone got this working?

**Comment by affinnen** [comment]
**You need to run:**  
brew install gnu-sed --with-default-names

Basically, follow this - https://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-x

Then make sure your git bash has:
PATH=/usr/local/bin:${PATH}
PATH=/bin:${PATH}
