### ISSUE TITLE
A question about PageView .

### ISSUE THREAD

**Issue by ZhangQinglian** [flutter/flutter#15664]
When I switch PageView from  pageA to pageB , pageB's 'initState' and 'build' method  will be called every time . Is there any way to keep pageB alive and avoid 'initState' and 'build' method be called .

**Comment by tfzxyinhao** [comment]
more and more people complain this,need a completed documents to explain lifecycle

**Comment by zoechi** [comment]
I believe the SO answer answers the question. Thanks @LRNZ09
