### ISSUE TITLE
[Flutter Web] ESC Key cannot be obtained at TextField when deployed to the Host.

### ISSUE THREAD

**Issue by ffpresents** [flutter/flutter#156697]
### Steps to reproduce

Press Escape Key at TextField.

### Expected results

"pressed" will be printed in console. (Chrome inspect panel) 

### Actual results

**When you execute sample code on [dartPad ](https://dartpad.dev/)or Web Hosted Page ([like this](https://counter-firebase-6e841.web.app/) But you may see security warning.) -**
ESC Key: **Nothing has occurred.**
Other Keys: "pressed" will be printed in console.

**When you execute sample code (Run or Debug) from Android Studio -**
ESC Key: **"pressed" will be printed in console.**
Other Keys: "pressed" will be printed in console.

onKeyEvent can detect almost all keys, including the Enter key, but I think it lacks consistency that it cannot detect the ESC key in certain situations.
I think it should be possible to detect the ESC key as well.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Focus(
          onKeyEvent: _processEvent,
          child: TextField(),
        ),
      ),
    );
  }

  KeyEventResult _processEvent(FocusNode node, KeyEvent event) {
    print("pressed");
    return KeyEventResult.handled;
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS C:\src\flutter_projects\textfield_esc_tst> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.5011], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2024.1)
    X Unable to find bundled Java version.
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ffpresents, I just tested your deployed sample and it appears to work as expected in chrome. See the recording below. Is there any additional information you can provide? 

https://github.com/user-attachments/assets/ee67ae55-a91b-4e35-a908-756b88b4baa2

**Comment by ffpresents** [comment]
@danagbemava-nc, thank you for checking. I rechecked it various way and Oh, I found one of Chrome Extension affected it.

I apologize for bothering you by lack of my confirmation. But your reply helped me identify the cause. I appreciate it.
I'll close this issue.
