### ISSUE TITLE
Enhancement to drag_target

### ISSUE THREAD

**Issue by agreensh** [flutter/flutter#15665]
## Steps to Reproduce

LongPressDraggable ALWAYS provides haptic feedback. This is not always required or wanted.
Could this be made an option.

**Comment by Hixie** [comment]
If you would like to submit a PR to add this feature we would certainly be happy to review and land it.

**Comment by SUPERETDUPER** [comment]
From my understatement, this was fixed with the PR. Should the issue be closed.
