### ISSUE TITLE
Removal of Dart SDK snapshots blocking engine -> framework roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#156654]
It looks like this change: https://dart.googlesource.com/sdk.git/+/9fec00aeedea94ac96d6b97f9ae36910591c826f

Is causing failures like: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20build_tests_3_5/1508/overview

cc @a-siva

**Comment by a-siva** [comment]
The flutter web test needs to use the command 'dart compile js' to compile files and not reach into the internals of the Dart SDK and name snapshot file names. Let me take a look at the web test which is failing.

**Comment by a-siva** [comment]
Creating a revert here https://dart-review.googlesource.com/c/sdk/+/390020

Will fix flutter tools to not use snapshot names to invoke commands and instead use the 'compile js' option.

**Comment by a-siva** [comment]
https://github.com/flutter/flutter/pull/156735 was submitted to have flutter tools not use snapshot names

**Comment by a-siva** [comment]
https://github.com/flutter/engine/pull/55884 is the manual roll of Dart SDK which has the revert, once this lands we can close this issue.

**Comment by a-siva** [comment]
Manual roll has landed, closing issue.
