### ISSUE TITLE
Installation error on ubuntu 64bit

### ISSUE THREAD

**Issue by swsiong97** [flutter/flutter#15660]
this is the problem after i clone it from github and wanna proceed to enter the code: flutter doctor but there was an error told me that the particular file error.
And i had screen shot the error that occur in particular file "--continue-at fill with nothing".
.
![screenshot from 2018-03-18 08-08-54](https://user-images.githubusercontent.com/29449170/37565674-e0c72bbc-2a83-11e8-8ce6-1bbb90d900ac.png)
![screenshot from 2018-03-18 08-09-02](https://user-images.githubusercontent.com/29449170/37565675-e4177fb0-2a83-11e8-860f-f363140dc63b.png)

**Comment by zoechi** [comment]
You need to install `curl`
