### ISSUE TITLE
Gallery App has Toolbars

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1566]
From https://www.google.com/design/spec/components/toolbars.html

Many of these features can be composed into an "App Bar" (see https://www.google.com/design/spec/layout/structure.html#structure-app-bar)

- [x] w/ drawer icon
- [x] w/ buttons
- [x] w/ title
- [x] default height
- [x] full height
- [x] floating
- [ ] bottom toolbar (see https://www.google.com/design/spec/layout/structure.html#structure-toolbars)

**Comment by eseidelGoogle** [comment]
I suspect most of these are done by now.  @HansMuller

**Comment by HansMuller** [comment]
I am closing this because #3577 covers the bottom bar lacuna and we've covered everything else.

**Comment by sethladd** [comment]
woohoo!
