### ISSUE TITLE
Provides an in-memory buffer of the captured image

### ISSUE THREAD

**Issue by jozefvodicka** [flutter/flutter#156643]
### Use case

Ability to work with image without saving to tmp folder for increased privacy

### Proposal

Right now we have an option to get path to file after the photo is taken.
We should be able to request to receive the photo directly within memory as an in-memory buffer.

For CameraX to leverage Image Capture method which provides an in-memory buffer of the captured image.
https://developer.android.com/media/camera/camerax/take-photo

For iOS similar approach.

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/137889

**Comment by jozefvodicka** [comment]
> possibly related to 
> - https://github.com/flutter/flutter/issues/137889

You are right, but now, since Google IO we have cameraX so it's much easier to implement this functionality.

The same goes with iOS.

How to prioritise it?

**Comment by iapicca** [comment]
> How to prioritise it?

"thumb-up" the existing issue I guess

**Comment by darshankawar** [comment]
I will close this in favor of https://github.com/flutter/flutter/issues/137889, so please follow-up in it for further updates.
You may share your findings in that issue for better tracking.
If you disagree, please write in comments and I'll reopen it.
