### ISSUE TITLE
Instructions about getting reverse url of client ID are unclear in the 'Firebase for Flutter' codelab.

### ISSUE THREAD

**Issue by jeroen-meijer** [flutter/flutter#15663]
Hi there.

Just a suggestion. I've been stressing to find out why my app has been crashing for the last half an hour when implementing GoogleSignIn into my FriendlyChat app.

The tutorial states: 
> Add the bundle ID and reverse URL of your client id to the main dictionary of your app's `Info.plist` file:
> (...)
> You can find the reverse URL of your client id in your `Info.plist` file.

To me, this didn't make sense, since the instructions were just telling me to put the reverse client id into my `Info.plist`. I tried reversing and using the Web SDK configuration from the Google sign-in method on the Firebase console, because it looked exactly the same as the one the tutorial tells me to find, but to no avail. When using that one, the app crashes on me. Not a problem, just look at the debug console output. Problem is, the debugger didn't give me any hints that the client ID was wrong. It just told me `Lost connection to device.`.

**Turns out, what the tutorial meant to say was**
> You can find the reverse URL of your client id in the `GoogleService-Info.plist` file you've downloaded prior.

**My question: could the tutorial get this edit, to clear up any misconceptions and confusion people might get.**

I was able to find the problem when debugging with Xcode and reading its debugging output. Is this expected behaviour? I would imagine that VS Code should also be able to provide errors and logs Xcode can give.

Thank you for reading.
Best regards.

**Comment by felideon** [comment]
Thanks. Found this issue by scratching my head and promptly googling to see if anyone else encountered this and figured it out already.

**Comment by jeroen-meijer** [comment]
@felideon No problem, mate.

**Comment by Hixie** [comment]
cc @Sfshaza

**Comment by Sfshaza** [comment]
Thanks, @jeroen-meijer, for diagnosing this bug and providing a workaround! This last May, we rewrote the Firebase codelab, so this is no longer relevant. Closing.

**Comment by kroikie** [comment]
@jeroen-meijer

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/884. Any further collaboration will be done there.
