### ISSUE TITLE
Typo in the tutorial in 'Firebase for Flutter'

### ISSUE THREAD

**Issue by AugustusLi** [flutter/flutter#15668]
In the 9th Chapter "Enable Data Syncing", it has a typo in the following code:
ChatMessage({this.snapshot, this.animation)};

main.dart
// Modify the following line of ChatMessage in main.dart.

```
class ChatMessage extends StatelessWidget {
  ChatMessage({this.snapshot, this.animation)};
  final DataSnapshot snapshot;
  final Animation animation;

  @override
  Widget build(BuildContext context) {
    return new SizeTransition(
      sizeFactor: new CurvedAnimation(
          parent: animation, curve: Curves.easeOut),            // modified
```
Remove the TickerProviderStateMixin widget and the List variable from the ChatScreenState class definition, as shown.

**Comment by Hixie** [comment]
cc @Sfshaza

**Comment by Sfshaza** [comment]
This bug refers to the deprecated (and removed) codelab. (It was replaced for Google I/O 2018.) Closing.

**Comment by kroikie** [comment]
@AugustusLi

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/883. Any further collaboration will be done there.
