### ISSUE TITLE
flutter doctor is not working, Error :  Checking Dart SDK version... 'PowerShell.exe' is not recognized as an internal or external command, operable program or batch file. Error: Unable to update Dart SDK. Retrying...

### ISSUE THREAD

**Issue by yash365** [flutter/flutter#15675]
I followed the procedure mentioned in the documentation

1. I have installed the git for windows
2. Then used this command in cmd : $ git clone -b beta https://github.com/flutter/flutter.git
3. Then i set the environment path in user variables of flutter.
4. Then using flutter doctor i got this error :

C:\Windows\System32>flutter doctor
Checking Dart SDK version...
'PowerShell.exe' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to update Dart SDK. Retrying...

**Comment by abhi-tupparwar** [comment]
Add " %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\ " to your Path variable

**Comment by yash365** [comment]
i will try that

**Comment by yash365** [comment]
it worked thanks

**Comment by ansarisufiyan777** [comment]
Thanks it worked perfectly

**Comment by abhi-tupparwar** [comment]
Welcome :)
Close this issue

**Comment by monojbasumatary** [comment]
this works

**Comment by gibbsvjy007** [comment]
nice solution. it worked

**Comment by mayank-rajput** [comment]
i set  " %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\ " this but still not working

**Comment by akiroussama** [comment]
thanks for help, work perfectly!

**Comment by abhi-tupparwar** [comment]
mayank-rajput  did you add "C:\Windows\System32" to your path?

**Comment by HamzaTanveer78** [comment]
> i set " %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\ " this but still not working

perfect for me too thanks

**Comment by d-Skillz** [comment]
> i set " %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\ " this but still not working

do this....search for system32 on search bar, once you see the folder, right click and open folder location.. then go to windowsPowershell, open it, open v1.0 then copy and paste in environmental variables....the  most import thing is to open the folder location

**Comment by YasminLuz** [comment]
For Windows 10, if the paths above doesn't work, use "%windir%\System32\WindowsPowerShell\V1.0" (64 bits) or "%windir%\Syswow64\WindowsPowerShell\V1.0" (32 bits)

**Comment by d-Skillz** [comment]
Thank you. It worked

**Comment by Ashuto7h** [comment]
yes it works.

**Comment by klebertonlee** [comment]
Muito obrigado, não estava conseguindo ai fiz o caminho e copiei e colei e passou

**Comment by Farhan786555** [comment]
For those still facing the error after setting the path variable just move the path up above the flutter bin or npm path variable. 
There will be two buttons MOVE UP or MOVE DOWN on the right side panel just set the powershell path above the npm or flutter paths.

**Comment by Farhan786555** [comment]
> For those still facing the error after setting the path variable just move the path up above the flutter bin or npm path variable.
> There will be two buttons MOVE UP or MOVE DOWN on the right side panel just set the powershell path above the npm or flutter paths.

**Comment by ahmedmohamed13896** [comment]
> For Windows 10, if the paths above doesn't work, use "%windir%\System32\WindowsPowerShell\V1.0" (64 bits) or "%windir%\Syswow64\WindowsPowerShell\V1.0" (32 bits)

it's work thanks

**Comment by Asfemi** [comment]
please i need help on this 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.gms.internal.measurement.zzu found in modules jetified-firebase-analytics-impl-16.2.2-runtime.jar (com.google.firebase:firebase-analytics-impl:16.2.2) and play-services-measurement-base-17.2.2-runtime.jar (com.google.android.gms:play-services-measurement-base:17.2.2)

**Comment by shwetavw** [comment]
Hi,
Can someone help, for me I am still getting an error as 'flutter' is not recognized as an internal or external command,operable program or batch file."

I have my flutter folder inside D:\ drive, it is mandatory to copy this folder in C:\ drive
Thank you

**Comment by ahmedmohamed13896** [comment]
> Hi,
> Can someone help, for me I am still getting an error as 'flutter' is not recognized as an internal or external command,operable program or batch file."
> 
> I have my flutter folder inside D:\ drive, it is mandatory to copy this folder in C:\ drive
> Thank you

I am using windows 10 and VS Code
Try to add these to your path 
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
C:\Windows\System32\WindowsPowerShell\V1.0;
C:\Users\USER_NAME\AppData\Local\GitHubDesktop\bin;
C:\Users\USER_NAME\AppData\Roaming\npm;
C:\Users\USER_NAME\AppData\Local\Programs\Microsoft VS Code\bin;
D:\YOUR_PROJECT_FOLDER_PATH;
C:\Users\USER_NAME\flutter\bin;
%ANDROID_HOME%\tools;
%ANDROID_HOME%\tools\bin;
%ANDROID_HOME%\platform-tools;
C:\Users\USER_NAME\AppData\Local\Android\Sdk\emulator

**Comment by rodrigozotto** [comment]
You need close the powershell to get new path configurations.

**Comment by hrithikrtiwari** [comment]
> Add " %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\ " to your Path variable
> you might also need to add " C:\Windows\System32 " if it's not there in the path variable

Dude you are awesome
Thanks a lot, may the force be with you and help you to achieve what you desire
