### ISSUE TITLE
Gallery App has Text Selection

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1567]
From https://www.google.com/design/spec/patterns/selection.html#selection-text-selection

- [x] selection gesture
- [x] handles
- [x] copy / cut / paste toolbar
- [x] iOS
- [x] Android

**Comment by tain335** [comment]
I think text input widget is important to the framework, it should has the highest priority.

**Comment by sethladd** [comment]
Thanks for the feedback. We're working on it :)

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/3567
