### ISSUE TITLE
 google_sign_in: ^6.2.1 Every time stuck on white screen

### ISSUE THREAD

**Issue by devsigofficial** [flutter/flutter#156739]
### Steps to reproduce

```dart
Future<UserCredential> signInWithGoogle() async {
    // Trigger the authentication flow
    await GoogleSignIn().signOut();
    final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();

    // Obtain the auth details from the request
    final GoogleSignInAuthentication? googleAuth =
    await googleUser?.authentication;

    // Create a new credential
    final credential = GoogleAuthProvider.credential(
      accessToken: googleAuth?.accessToken,
      idToken: googleAuth?.idToken,
    );

    // Once signed in, return the UserCredential
    return await FirebaseAuth.instance.signInWithCredential(credential);
  }
```

### Expected results

It should be work

### Actual results

<img width="400" src="https://github.com/user-attachments/assets/0f30dc61-4905-494e-86e6-8e6fc38778d1">

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Performing hot reload...
Syncing files to device iPhone 16...
Reloaded 0 libraries in 751ms (compile: 111 ms, reload: 0 ms, reassemble: 483 ms).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
bholendraofficial@Bholendras-MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64 (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-243.15521.24)
[✓] VS Code (version 1.94.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Bholendra’s iPhone. Ensure the device is unlocked and attached
      with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @devsigofficial 
I see you are using `FirebaseAuth`. To check if this is related to `firebase_auth` plugin, can you try running google_sign_in's [example](https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in/example) to see if the issue persists? (I tested this example and couldn't see the issue on iOS app)

Please ensure your internet connection is green when accessing google login site as well. You can try logging-in to your account on your device's browser/app.
