### ISSUE TITLE
Notable Mishaps

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#156720]
This issue is essentially the opposite of https://github.com/flutter/flutter/issues/121415.

Owning up to mistakes can feel great, and it's nice to look back and see the progress I've made, along with the areas that still need work.
(I've become very good at following the Flutter style guide, but I continue to struggle with overall reading comprehension.)

<br>

Below is a list of my snafus during interactions with the Flutter community. This list is by no means comprehensive.
Feel free to comment with your own mishaps, if you'd like!

<br>

### First attempted contribution
<sub>**Date:** September 12, 2023</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/134605</sub>
<sub>**Person most affected:** [Michael Goderbauer](https://github.com/goderbauer)</sub>
- Tried introducing a `_DynamicBox` widget!
- `// ignore_for_file: prefer_final_locals, always_specify_types`

<br>

### Second attempted contribution
<sub>**Date:** October 7, 2023</sub>
<sub>**Link:** https://github.com/flutter/flutter/issues/136139#issuecomment-1751852100</sub>
<sub>**Person most affected:** [Stuart Morgan](https://github.com/stuartmorgan)</sub>
- My original [issue comment](https://github.com/flutter/flutter/issues/136139) was 1 sentence: "I want to make a PR"
- Changed 170 files in one go!
(and [violated the style guide](https://github.com/flutter/flutter/pull/136140#discussion_r1349586844), of course)

<br>

### Caused a regression
<sub>**Date:** April 4, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/150041</sub>
<sub>**Person most affected:** [Taha Tesser](https://github.com/TahaTesser)</sub>
- Taha fixed [the bug I introduced](https://github.com/flutter/flutter/issues/150000)!

<br>

### Caused another regression
<sub>**Date:** May 3, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/148634</sub>
<sub>**Person most affected:** [Zachary Anderson](https://github.com/zanderso)</sub>
- `late initialization error`!

<br>

### Caused yet another regression
<sub>**Date:** May 17, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/issues/153851#issuecomment-2305197145</sub>
<sub>**Person most affected:** [Huy](https://github.com/huycozy)</sub>
- "Let's make the logic a bit shorter, and if checks pass then it's all good!"
(it wasn't all good)

<br>

### Another regression (2-day streak!)
<sub>**Date:** May 18, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/148978</sub>
<sub>**Person most affected:** [Renzo Olivares](https://github.com/Renzo-Olivares)</sub>
- Didn't notice that Renzo had landed a change to the same file
- …so my "fix" resulted in a [memory leak](https://github.com/flutter/flutter/issues/148985) and was [delayed](https://github.com/flutter/flutter/pull/151144) until the next stable release!

<br>

### Missed a breaking change
<sub>**Date:** June 8, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/149963#discussion_r1645018978</sub>
<sub>**Person most affected:** [Justin McCandless](https://github.com/justinmc)</sub>
- Somebody had to go through my PR's Google Testing failures, and that somebody was not me!
(shoutout to Mitchell Goodwin, who [also had to do this](https://github.com/flutter/flutter/pull/146043#issuecomment-2105246088)!)

<br>

### Refactored code to make it uglier
<sub>**Date:** July 12, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/151667</sub>
<sub>**Person most affected:** [Victor Sanni](https://github.com/victorsanni)</sub>
- `if (item case PreferredSizeWidget(preferredSize: Size(:final double height)))`

<br>

### Created a wiki page that already exists
<sub>**Date:** July 25, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/152348</sub>
<sub>**Person most affected:** [Christopher Fujino](https://github.com/christopherfujino)</sub>
- …and then [created it again](https://github.com/flutter/flutter/pull/154629), because why not?
- I had seen the link to this page [hundreds of times](https://github.com/flutter/flutter/issues/154628)!

<br>

### Confidently stated that "Flutter on Windows uses Impeller"
<sub>**Date:** August 15, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/issues/153517#issuecomment-2292148491</sub>
<sub>**Person most affected:** [Jonah Williams](https://github.com/jonahwilliams)</sub>
- (to be fair, gradients look much nicer on Windows than on Web)

<br>

### Approved a PR that I knew nothing about
<sub>**Date:** August 26, 2024</sub>
<sub>**Link:** https://github.com/flutter/packages/pull/7498</sub>
<sub>**Person most affected:** [Matan Lurey](https://github.com/matanlurey)</sub>
- Granted Matan's LGTM request as fast as physically possible
- …and then [shifted the blame](https://github.com/flutter/packages/pull/7498#issuecomment-2310710316) when things didn't go well!

<br>

### Did not comprehend a direct question
<sub>**Date:** August 27, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/issues/154197#issuecomment-2313369388</sub>
<sub>**Person most affected:** [Mateus Felipe](https://github.com/mateusfccp)</sub>
- Mateus asked me if `WidgetStatePropertyOr` could be implemented as a tagged union type, albeit with poor ergonomics
- …I disagreed by [going over the poor ergonomics](https://github.com/flutter/flutter/issues/154197#issuecomment-2313388993)!

<br>

### Pretended to know about flutter/tests
<sub>**Date:** September 4, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/154629#discussion_r1744211661</sub>
<sub>**Person most affected:** [Navaron Bracke](https://github.com/navaronbracke)</sub>
- Said "it'd be nice to double-check my understanding"
- …in response to Navaron directing me to [the exact information I needed](https://github.com/flutter/tests?tab=readme-ov-file#flutter-customer-test-registry)!

<br>

### Merged without proper approval
<sub>**Date:** October 3, 2024</sub>
<sub>**Link:** https://github.com/flutter/flutter/pull/154753</sub>
<sub>**Person most affected:** [Kate Lovett](https://github.com/Piinks)</sub>
- Kate [circulated my contribution with the whole team](https://github.com/flutter/flutter/pull/154753#pullrequestreview-2341204732)
- …yet somehow I glossed over that fact entirely, despite having [responded](https://github.com/flutter/flutter/pull/154753#event-14480609311) to the following sentence from that same comment!
(not to mention contradicting [my own agreement](https://github.com/flutter/flutter/pull/154753#pullrequestreview-2341920078))

**Comment by nate-thegrate** [comment]
And one more:

<br>

### Used the wrong venue for a postmortem
<sub>**Date:** October 3, 2024</sub>
<sub>**Link:** [this page]</sub>
<sub>**Person most affected:** myself</sub>
- Decided it'd be fun to make an "inverse" of the [notable commits issue](https://github.com/flutter/flutter/issues/121415)
- …when, in fact, there's already a [postmortem directory](https://github.com/flutter/flutter/tree/master/docs/postmortems) for this purpose!

**Comment by bleroux** [comment]
"The only man who never makes a mistake is the man who never does anything"

TIL the english word 'mishaps', thanks!
