### ISSUE TITLE
regression in 99p frame raster time on mokey on shader_mask_cache_perf__e2e_summary

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#156715]
On the engine roll here https://github.com/flutter/engine/compare/205484009711...d38f5e560a98

https://flutter-flutter-perf.skia.org/e/?begin=1725056493&end=1728888985&keys=X2ef9e657410668684a10f065f26dd5a6&requestType=0&selected=commit%3D42813%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dmokey%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dshader_mask_cache_perf__e2e_summary%252C&xbaroffset=42813

**Comment by zanderso** [comment]
Some other movement on that roll https://flutter-flutter-perf.skia.org/e/?begin=1726228050&end=1728888985&keys=X0ef48979781f2f2d99f24cfdb111f650&requestType=0&selected=commit%3D42813%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dmokey%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_gpu_memory_mb%252Ctest%253Dfading_child_animation_perf__timeline_summary%252C&xbaroffset=42813

**Comment by jonahwilliams** [comment]
Expected because of "[Impeller] generate mipmaps for toImage. (flutter/engine#55655)"
