### ISSUE TITLE
showDialog doesn't have "builder" property

### ISSUE THREAD

**Issue by moseskarunia** [flutter/flutter#15670]
## Steps to Reproduce

```
showDialog<Null>(
      context: context,
      builder: (BuildContext context) {
        return new AlertDialog(
          content: const Text('You tapped the floating action button.'),
          actions: <Widget>[
            new FlatButton(
              onPressed: () {
                Navigator.pop(context);
              },
              child: const Text('OK')
            )
          ],
        );
```
      },
    );

## Logs

`flutter run`
Launching lib/main.dart on SM N750 in debug mode...
Initializing gradle...                                2.5s
Resolving dependencies...                             6.1s
Running 'gradlew assembleDebug'...                   23.1s
Built build\app\outputs\apk\debug\app-debug.apk (24.6MB).
I/FlutterActivityDelegate(20280): onResume setting current activity to this
E/flutter (20280): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (20280): NoSuchMethodError: The method 'call' was called on null.
E/flutter (20280): Receiver: null
E/flutter (20280): Tried calling: call()
E/flutter (20280): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
E/flutter (20280): #1      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
E/flutter (20280): #2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Syncing files to device SM N750...                    6.4s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on SM N750 is available at: http://127.0.0.1:8101/
For a more detailed help message, press "h". To quit, press "q".
D/mali_winsys(20280): new_window_surface returns 0x3000,  [720x1280]-format:1
D/SRIB_DBQ(20280): SurfaceView:updateWindow: viewRoot.sSVBufferCount=-1 mSVBufferCount=-1
I/FlutterActivityDelegate(20280): onResume setting current activity to this
I/Timeline(20280): Timeline: Activity_idle id: android.os.BinderProxy@207b0d7a time:6227739

`flutter analyze`
Analyzing M:\Work\Projects\FlutterTestApp\startup_namer...
  error - The named parameter 'builder' isn't defined at lib\main.dart:68:7 - undefined_named_parameter
  error - The constructor returns type 'dynamic' that isn't of expected type 'Widget' at test\widget_test.dart:15:29 - strong_mode_invalid_cast_new_expr
  error - Undefined class 'MyApp' at test\widget_test.dart:15:33 - undefined_class
  warning - The parameter 'child' is required at lib\main.dart:66:5 - missing_required_param
  hint - Unused import: 'package:startup_namer/main.dart' at test\widget_test.dart:10:8 - unused_import
5 issues found.
(Ran in 14.9s)

## Flutter Doctor

[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.1.5 at M:\Work\flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at M:\Work\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = M:\Work\Android\sdk
    • Java binary at: M:\Work\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at M:\Work\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • SM N750 • 192.168.100.2:5555 • android-arm • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

So yeah, both in demo and doc has builder property in the AlertDialog, which I have none. The code on the top is copied from the docs / demo. How to fix it?

**Comment by jonahwilliams** [comment]
@moseskarunia the `builder` property exists on version 0.2.2 and greater.  You are currently on the beta branch version 0.1.5 which doesn't have this update.

Instead of `builder`, use the `child` parameter.

```
showDialog(child: new MyWidget(), context: context);
```


Also see the [changelog](https://github.com/flutter/flutter/wiki/Changelog) for major breaking changes and updates at each version.

**Comment by moseskarunia** [comment]
Any plan on when it will be rolled to beta?

**Comment by jonahwilliams** [comment]
@moseskarunia No announced dates yet, stay tuned.

**Comment by Hixie** [comment]
This has been rolled to beta now.
