### ISSUE TITLE
Find a BottomNavigationBar in bug

### ISSUE THREAD

**Issue by zhenghuan87916275** [flutter/flutter#15680]
Find a BottomNavigationBar in bug, click the tab button when not let go at this time (color water ripple MD style), and then click on the mobile phone menu appears at this time to return to the task stack, app, found that no matter how to operate or switch tab, before the water ripples will not disappear, the bug can also be superimposed

**Comment by HansMuller** [comment]
Can you send a small example, and some instructions in terms of that example, that demonstrates the problem you're running into?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
