### ISSUE TITLE
Flutter environment in MacBook Pro Intel Core i7 occur Error

### ISSUE THREAD

**Issue by TuCTu** [flutter/flutter#156805]
### Steps to reproduce

1.I configured the environment according to the official website and downloaded the flutter sdk version of flutter_macos_3.24.3-stable.zip
2.I unzipped the installation package and placed it in the /Users/xxx(username)/development/ directory
3.Configured environment variables in zshrc
![Uploading image.png…]()
export PATH=$HOME/development/flutter/bin:$PATH

### Expected results

1.flutter
An error occurred when running flutter doctor: PathAccessException: Cannot create file, path = '/Users/caipeikun/.dart-tool/dart-flutter-telemetry-session.json' (OS Error: Permission denied, errno = 13)
![image](https://github.com/user-attachments/assets/705c92a8-ac6f-49d2-a83e-1fff2f6f25f3)

2.flutter doctor
An error occurred when running flutter doctor: PathAccessException: Cannot create file, path = '/Users/caipeikun/.dart-tool/dart-flutter-telemetry-session.json' (OS Error: Permission denied, errno = 13)
![image](https://github.com/user-attachments/assets/4280f784-b007-487c-8ec4-280a8b136dd7)

No matter what command I run I get an error unless I add sudo
![image](https://github.com/user-attachments/assets/85ad65b5-2ce4-4494-80c0-2b60108b89b6)

I don't want to use sudo, what should I do?

### Actual results

1.flutter
An error occurred when running flutter doctor: PathAccessException: Cannot create file, path = '/Users/caipeikun/.dart-tool/dart-flutter-telemetry-session.json' (OS Error: Permission denied, errno = 13)
![image](https://github.com/user-attachments/assets/705c92a8-ac6f-49d2-a83e-1fff2f6f25f3)

2.flutter doctor
An error occurred when running flutter doctor: PathAccessException: Cannot create file, path = '/Users/caipeikun/.dart-tool/dart-flutter-telemetry-session.json' (OS Error: Permission denied, errno = 13)
![image](https://github.com/user-attachments/assets/4280f784-b007-487c-8ec4-280a8b136dd7)

No matter what command I run I get an error unless I add sudo
![image](https://github.com/user-attachments/assets/85ad65b5-2ce4-4494-80c0-2b60108b89b6)

I don't want to use sudo, what should I do?

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

No matter what command I run I get an error unless I add sudo
![image](https://github.com/user-attachments/assets/85ad65b5-2ce4-4494-80c0-2b60108b89b6)

I don't want to use sudo, what should I do?

**Comment by danagbemava-nc** [comment]
Hi @TuCTu, does the user you're logged in as have the right permissions to access the directpry?

**Comment by TuCTu** [comment]
> Hi @TuCTu, does the user you're logged in as have the right permissions to access the directpry?

It is caused by the problem that there is no permission on the current file. After modification, the flutter command can be used normally.
![image](https://github.com/user-attachments/assets/400f1787-b915-4655-afcd-22012f1f2791)
