### ISSUE TITLE
 Chinese Characters Get Cut Off When Using Italics and Background in RichText on Flutter Web

### ISSUE THREAD

**Issue by maoyuliuxin** [flutter/flutter#156807]
### Steps to reproduce

Description:
When using RichText in Flutter Web to render Chinese characters with italic style and a background color, the width of the characters gets cut off. This issue seems to be caused by incorrect width calculations when applying italic fonts, especially for non-Latin scripts like Chinese.

Steps to Reproduce:
Create a RichText or Text widget.
Apply FontStyle.italic in TextStyle.
Set a background color using backgroundColor in TextStyle.
Render the text with Chinese characters on a Flutter Web application.

RichText(
  text: TextSpan(
    text: '中文示例',
    style: TextStyle(
      fontStyle: FontStyle.italic,
      backgroundColor: Colors.yellow, // Background color
    ),
  ),
)

### Actual results

Chinese characters should be displayed completely, without any truncation, even when using italic style and background color.
Bug  the width of the Chinese characters is cut off, resulting in incomplete rendering of the text.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
    • Flutter version 3.22.3 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

**Comment by danagbemava-nc** [comment]
This is not specific to Chinese text. This is also being tracked in https://github.com/flutter/flutter/issues/151404

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you
