### ISSUE TITLE
How to slide a row to show actions just like IOS

### ISSUE THREAD

**Issue by korbin-w** [flutter/flutter#15683]
Hi, in a table view, I need to slide a row from right to left and show actions in the right end, just like the UITableView RowAction in IOS.  Is there a demo or existing component?

A example like below:

![image](https://user-images.githubusercontent.com/454020/37587700-ff6cd6e4-2b9a-11e8-9383-c7dca34afb4f.png)

**Comment by korbin-w** [comment]
We did not find an existing Widget and finally we develop a new one.

**Comment by korbin-w** [comment]
I find an existing issue the same as mine, thanks.  https://github.com/flutter/flutter/issues/14388 [](https://github.com/flutter/flutter/issues/14388)

**Comment by prabhuthiran** [comment]
@korbin-w I also struggling with this problem.. Can you please post your idea if you have anything..

**Comment by korbin-w** [comment]
@prabhuthiran My colleague will share the idea this later.  It's our pleasure.

**Comment by chaokongzwp** [comment]
@prabhuthiran 
The code has not yet been collated into a common interface. So first send the demo to you for reference.
[lib.zip](https://github.com/flutter/flutter/files/1870026/lib.zip)

**Comment by prabhuthiran** [comment]
Thank you so much @korbin-w , @chaokongzwp  you guys saved my life.. I tried to run the code it is perfectly working.. i have another question is it possible to have  swipe on the both sides of the card..?

**Comment by prabhuthiran** [comment]
Is it possible to have a icon/image instead of background color and text?

**Comment by chaokongzwp** [comment]
@prabhuthiran  it is just demo， 
It's relatively simple, follow-up I will provide a way to set widget as a background. In addition, right-scratch features can be done, but I have no time recently and you may need to wait a few days

**Comment by jianggaocheng** [comment]
@chaokongzwp Thank you for your widget, It helps me a lot.
