### ISSUE TITLE
Regression in backdrop filter perf benchmark raster time

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#156871]
On the engine -> framework roll in https://github.com/flutter/engine/compare/0e7344ae240d...db0c0b7ca428

https://flutter-flutter-perf.skia.org/e/?keys=X5091b64d31a29b82a43623a80066ad75&requestType=0&selected=commit%3D42869%26name%3D%252Carch&xbaroffset=42869

**Comment by gaaclarke** [comment]
I was able to verify locally that the change was introduced in https://github.com/flutter/engine/pull/55717

**Comment by gaaclarke** [comment]
A regression was seen on iOS too: https://flutter-flutter-perf.skia.org/e/?queries=test%3Dbackdrop_filter_perf__timeline_summary&selected=commit%3D42868%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf__timeline_summary%252C

**Comment by gaaclarke** [comment]
I'm unable to capture the frame with xcode, the replay mechanism crashes after the capture.  I reduced the number of blurs to 1 and it still has that problem.

**Comment by gaaclarke** [comment]
As jonah pointed out, we are blurring the whole area now.  This can be more easily duplicated by looking at `AiksTest.CanRenderBackdropBlurInteractive`

[CanRenderBackdropBlurInteractive-before.gputrace.zip](https://github.com/user-attachments/files/17385860/CanRenderBackdropBlurInteractive-before.gputrace.zip)
[CanRenderBackdropBlurInteractive-after.gputrace.zip](https://github.com/user-attachments/files/17385873/CanRenderBackdropBlurInteractive-after.gputrace.zip)
