### ISSUE TITLE
Wrong documentation for Snackbar's `actionOverflowThreshold` property

### ISSUE THREAD

**Issue by OutdatedGuy** [flutter/flutter#156817]
### Steps to reproduce

Use any default example app or the default counter app and set `actionOverflowThreshold` to `0` while showing a SnackBar with actions.

### Expected results

The Action button should not overflow to next line. (i.e. should be center aligned vertically at the right side of snackbar)

### Actual results

The action button overflows to the end of widget (i.e. overflows to newline, renders at bottom right of snackbar)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by OutdatedGuy** [comment]
https://github.com/flutter/flutter/blob/2b36701456d25d48e5c923d115d719e691c3f9b7/packages/flutter/lib/src/material/snack_bar.dart#L429
The documentation above should be changed to: `At a value of 1, the action will not overflow to a new line.`

**Comment by darshankawar** [comment]
@OutdatedGuy 
I used below code sample and passed `actionOverflowThreshold` as 0, but didn't get any overflow upon running on Android emulator. 

<details>
<summary> runnable code </summary>

```

import 'package:flutter/material.dart';

void main() => runApp(const SnackBarDemo());

class SnackBarDemo extends StatelessWidget {
  const SnackBarDemo({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SnackBar Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('SnackBar Demo'),
        ),
        body: const SnackBarPage(),
      ),
    );
  }
}

class SnackBarPage extends StatelessWidget {
  const SnackBarPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: () {
          final snackBar = SnackBar(
            actionOverflowThreshold: 0,
            content: const Text('Yay! A SnackBar!'),
            action: SnackBarAction(
              label: 'this is test',
              onPressed: () {
                // Some code to undo the change.
              },
            ),
          );

          // Find the ScaffoldMessenger in the widget tree
          // and use it to show a SnackBar.
          ScaffoldMessenger.of(context).showSnackBar(snackBar);
        },
        child: const Text('Show SnackBar'),
      ),
    );
  }
}

```

</details>

<img width="373" alt="Screenshot 2024-10-16 at 12 08 35 PM" src="https://github.com/user-attachments/assets/df096070-f931-4cfd-ae63-2598ebb22ef0">

Can you provide some visuals or elaborate on actual results you are seeing ?

**Comment by darshankawar** [comment]
I see, thanks for the update. 

Without `actionOverflowThreshold: 0,`, I see below:

<img width="192" alt="Screenshot 2024-10-16 at 5 08 23 PM" src="https://github.com/user-attachments/assets/672af99c-4115-4ff5-afdc-2a18f6143637">

With that parameter, it shows as shown [earlier](https://github.com/flutter/flutter/issues/156817#issuecomment-2415864589).

**Comment by OutdatedGuy** [comment]
@darshankawar if you add a really long string in snackbar and set `actionOverflowThreshold: 1,` then the action will always be right side vertically aligned, which is what the doc is trying to say about `0`

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/issues/156817 landed
