### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by ombudev** [flutter/flutter#15688]
![untitled](https://user-images.githubusercontent.com/30596910/37595203-364f231a-2b78-11e8-850a-dbbd8ca1b4ce.jpg)

**Comment by mraleph** [comment]
@ombudev are you using `beta` channel? What kind of CPU you have? If this is Core 2 or similar CPU then you need to upgrade to `master` or `dev` channel.

**Comment by ombudev** [comment]
@mraleph it's an Intel(R) Pentium(R) CPU N350 @ 2,16GHz   2.16GHz

**Comment by mraleph** [comment]
@ombudev I can't find CPU called exactly that on the Intel site. 

Could you download [coreinfo](https://docs.microsoft.com/en-us/sysinternals/downloads/coreinfo) utility from the Microsoft site, run it and then post the output?

**Comment by ombudev** [comment]
@mraleph Hi

**Comment by mraleph** [comment]
@ombudev sorry, I did not get back to you on this. My original suspicion was that it has the same cause as #12666 - but unfortunately this does not seem to be the case - as your processor is new enough and seems to support `POPCNT` instruction. 

Have you tried upgrading to `master` instead of `beta`?

**Comment by ombudev** [comment]
@mraleph No, I haven't... How do I do that?

**Comment by mraleph** [comment]
@ombudev delete your `flutter` checkout and do:

```
git clone -b master https://github.com/flutter/flutter.git
```

(notice `master` instead of `beta`)

Then follow the rest of the instructions.

**Comment by ombudev** [comment]
@mraleph By deleting, you mean deleting the folder? Which folder if there's a folder to be deleted?

**Comment by mraleph** [comment]
@ombudev when you followed instructions before those instructions created a folder called `flutter` somewhere (maybe in your home directory?)

**Comment by ombudev** [comment]
@mraleph Ok let me find that folder

**Comment by Hixie** [comment]
@ombudev any luck?
