### ISSUE TITLE
How to automate gestures in flutter ?  

### ISSUE THREAD

**Issue by Biswajeet-chimple** [flutter/flutter#15682]
how to write test scripts for drag and drop,multi-tap,long press using gesture class in flutter driver?

**Comment by rmathias86** [comment]
Integration testing @ https://flutter.io/testing/

**Comment by zoechi** [comment]
I assume this can be closed. Thanks @rmathias86

**Comment by javierforero** [comment]
@zoechi  y close? Theres no long press. You gotta do a hacky thing and scroll for x amount in the same target and sometimes that fails. Flutter driver is unpredictable
