### ISSUE TITLE
Physical device detected as emulator due to which I'm unable to run my app in release mode

### ISSUE THREAD

**Issue by caulifla** [flutter/flutter#15685]
I'm trying to run my app in release mode so I added --release argument to `flutter run`. After that I got a strange error.

`Release mode is not supported for emulators.`

So I went ahead and ran `flutter devices` and got the following result.

```
1 connected device:

SM A520F • 5210a324ea8d14bf • android-arm64 • Android 7.0 (API 24) (emulator)

```
Why is my phone detected by flutter as an emulator?

## Flutter Doctor

```
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-IN)
    • Flutter version 0.1.5 at D:\Coding\flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\skart\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.21.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] Connected devices (1 available)
    • SM A520F • 5210a324ea8d14bf • android-arm64 • Android 7.0 (API 24) (emulator)
```

**Comment by lobo84** [comment]
Same for me, I have an SMA310F

**Comment by skromm** [comment]
Same for me (SM A520F). 
Is there a workaround?

**Comment by KuzmenkoEvgenij** [comment]
same for SM G965F

**Comment by BabkenM** [comment]
same here 

adb shell getprop ro.build.characteristics
phone,emulator

adb shell getprop ro.hardware
samsungexynos7885

flutter devices
1 connected device:

SM A730F • 52007d66ee1f55e5 • android-arm64 • Android 8.0.0 (API 26) (emulator)

**Comment by mpacate** [comment]
same here
• SM G570Y       • 4200f619fccb64b9                         • android-arm • Android 8.0.0 (API 26) (emulator)

**Comment by zoechi** [comment]
Please also upvote the initial comment to raise priority.

**Comment by dgm3333** [comment]
Does anyone know of a workaround for this yet?

**Comment by zoechi** [comment]
@dgm3333 You should still be able to `fluter build apk` `flutter install` or at least `adb install ...`

**Comment by saturov** [comment]
The same for me. I do another operation `flutter run --profile` with my Samsung A5 (A520F) getting the same output:
`Profile mode is not supported for emulators.`

Both in Android Studio and VS Code.

**Comment by TahaTesser** [comment]
Hi @caulifla  @saturov
Are you still experiencing this issue?
Thank you

**Comment by jaween** [comment]
@TahaTesser 
I'm not the one who opened the issue, but I had the same physical device showing up as an emulator issue (same device Samsung A5, SM A520F running Android 8).

For me the issue has been fixed, though I'm not sure when it happened.

Here's my `flutter doctor -v` ouput:
```
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.14.6 at /opt/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jaween/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • SM A520F   • 5200676a4a815579 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.122
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by A-freedom** [comment]
same for me 
`[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /home/max/Android/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/max/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.0

[✓] Connected device (1 available)
    • SM A520F • 5210dec9b8e754bf • android-arm64 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 2 categories.
`
