### ISSUE TITLE
Issue from website page Adding Interactivity to Your Flutter App

### ISSUE THREAD

**Issue by kojole** [flutter/flutter#15689]
From URL: https://flutter.io/tutorials/interactive/#getting-ready

A closing `</aside>` tag appears.

![adding_interactivity_to_your_flutter_app_-_flutter](https://user-images.githubusercontent.com/35105763/37595389-fdc66a5a-2bbb-11e8-9e03-3bf8c4e8ff76.png)

Source: https://github.com/flutter/website/blame/f9577afe9d754b10b188ad1dd1c21b0eb13c5231/tutorials/interactive/index.md#L62

**Comment by Hixie** [comment]
Looks like this is solved.
