### ISSUE TITLE
Xcode seems fine, but flutter reports that it requires additional components

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15697]
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.2.3-pre.46, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted.
[✓] Android Studio (version 2.3)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

However, when I launch Xcode, it doesn't show anything out of the ordinary.  It lets me create new projects without complaint.

**Comment by jonahwilliams** [comment]
might have been broken by https://github.com/flutter/flutter/pull/15628, I will roll it back for now

**Comment by tvolkert** [comment]
Yep, confirmed  #15628 is the culprit.  This goes away if I reverse that commit.

**Comment by cad0p** [comment]
having the same issue now! latest flutter

**Comment by Maxwell6635** [comment]
Having this issues now.

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-MY)
    • Flutter version 1.9.1+hotfix.2 at /Users/jackson.foo/Downloads/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jackson.foo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted.
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 8 Plus • D10A35F7-2746-448D-AF92-0D36F7522256 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
