### ISSUE TITLE
[local_auth] "Enter your password" is not working while face not recognised in IOS app.

### ISSUE THREAD

**Issue by MOhsain** [flutter/flutter#156969]
### Steps to reproduce

1- Enable face recognisation in the IOS App. Call function for only biomateric. A dialog would be open for recognise the face.
2- Now hide your face and the dialog will show the message "Face not recognised" and at the bottom it show the "Try again" button. and. when you click on this button again hide your face and again you will see the "Face not recognised" message.
3- But at the button the "Try again " button replaced with "Enter Password". When i click on this button it show the error "flutter: PlatformException(NotAvailable, Authentication failure., com.apple.LocalAuthentication, null)" and nothing happend.

### Expected results

1- When i click on "Enter password" button i would open the keyboard where i can enter the mobile passcode.
So user can authenticate in this app.

### Actual results

1- But when i click on "Enter password" button, nothing happened. only dialog closed and in the logs there is an error ->
Error :"flutter: PlatformException(NotAvailable, Authentication failure., com.apple.LocalAuthentication, null)" 

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<void> authenticateWithBiometrics() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
          localizedReason: 'Scan your fingerprint (or face or whatever) to authenticate',
          options: const AuthenticationOptions(
            stickyAuth: true,
            biometricOnly: true,
            useErrorDialogs: false,
          ));
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = "Error - ${e.message}";
      });
      return;
    }
    if (!mounted) return;

    final String message = authenticated ? 'Authorized' : 'Not Authorized';
    setState(() {
      _authorized = message;
    });
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter: PlatformException(NotAvailable, Authentication failure., com.apple.LocalAuthentication, null)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @MOhsain, this is working as documented. See  https://pub.dev/documentation/local_auth/latest/local_auth/AuthenticationOptions/biometricOnly.html

If you want to be able to fallback to the password or other forms of authentication, you should set `biometricOnly` to `false` otherwise you will have to provide your own fallback method of authentication in case it fails.  

Given that this is working as documented, I'll be closing this issue. 

Thank you
