### ISSUE TITLE
Wrong documentation or behaviour for MaterialApp.builder property

### ISSUE THREAD

**Issue by Lurchfresser** [flutter/flutter#156959]
### Steps to reproduce

1. create a new project with "flutter create bug"
2. paste the minimal reproducible sample in the main.dart
3. uncomment or comment out the field "MaterialApp.themeAnimationStyle"

### Expected results

The result won't change, as no animation is used. The red border always remains, as the documentation for the builder states: 
"A builder for inserting widgets above the [Navigator] or - when the [WidgetsApp.router] constructor is used - above the [Router] but below the other widgets created by the [WidgetsApp] widget, or for replacing the [Navigator]/[Router] entirely."

### Actual results

If the themeAnimationStyle is AnimationStyle.noAnimation, the builder wont get executed

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const Placeholder(),
      builder: (context, child) => Container(
        decoration: BoxDecoration(
          border: Border.all(color: Colors.red, width: 20),
        ),
        child: child,
      ),
      //uncomment the line below
      //themeAnimationStyle: AnimationStyle.noAnimation,
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.24.3, on Fedora Linux 40 (Workstation Edition) 6.11.3-200.fc40.x86_64, locale en_US.UTF-8)
    • Flutter version 3.24.3 on channel stable at <path-to-flutter>/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8 (Fedora 18.1.8-1.fc40)
    • cmake version 3.28.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] VS Code (version 1.94.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.98.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 40 (Workstation Edition) 6.11.3-200.fc40.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by huycozy** [comment]
Reproduced the issue on `Channel master, 3.27.0-1.0.pre.64` as well.

<details open>
<summary>Demo screenshot/video</summary>

| without AnimationStyle.noAnimation | with AnimationStyle.noAnimation |
| --------------- | --------------- |
<img width="400" src="https://github.com/user-attachments/assets/2a66cfdc-c3fe-41e6-9022-a244104322f2"> | <img width="400" src="https://github.com/user-attachments/assets/ecd67d90-eb9a-49cb-82ef-8e0033ecc03b">

</details>

**Comment by Lurchfresser** [comment]
Ok had some trouble with the google cla, but now its working. I have created a pull request:

https://github.com/flutter/flutter/pull/156982

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/pull/156982 landed
