### ISSUE TITLE
flutter_tools: Some tests violate Dart 2 semantics

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#15696]
... which I think is hidden at the moment, by `mockito`'s use of `dynamic`.

These likely will become runtime errors in the near future. I'm happy to send PRs to help:

* cocoapods_test.dart:50
  ```The argument type 'ProcessResult' can't be assigned to the parameter type 'Future<ProcessResult>'. #argument_type_not_assignable```

* cocoapods_test.dart:180
  ```The argument type 'ProcessResult' can't be assigned to the parameter type 'Future<ProcessResult>'. #argument_type_not_assignable```

* cocoapods_test.dart:363
  ```The argument type 'ProcessResult' can't be assigned to the parameter type 'Future<ProcessResult>'. #argument_type_not_assignable```

* code_signing_test.dart:133
  ```The argument type 'int' can't be assigned to the parameter type 'Future<int>'. #argument_type_not_assignable```

* code_signing_test.dart:192
  ```The argument type 'int' can't be assigned to the parameter type 'Future<int>'. #argument_type_not_assignable```

* code_signing_test.dart:262
  ```The argument type 'int' can't be assigned to the parameter type 'Future<int>'. #argument_type_not_assignable```

* code_signing_test.dart:324
  ```The argument type 'int' can't be assigned to the parameter type 'Future<int>'. #argument_type_not_assignable```

* code_signing_test.dart:393
  ```The argument type 'int' can't be assigned to the parameter type 'Future<int>'. #argument_type_not_assignable```

* devices_test.dart:62
  ```The argument type 'String' can't be assigned to the parameter type 'Future<String>'. #argument_type_not_assignable```

* devices_test.dart:63
  ```The argument type 'String' can't be assigned to the parameter type 'Future<String>'. #argument_type_not_assignable```

* devices_test.dart:64
  ```The argument type 'String' can't be assigned to the parameter type 'Future<String>'. #argument_type_not_assignable```

* devices_test.dart:65
  ```The argument type 'String' can't be assigned to the parameter type 'Future<String>'. #argument_type_not_assignable```

* ios_workflow_test.dart:36
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:37
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:221
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:222
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:238
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:239
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:240
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:246
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:256
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:257
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* ios_workflow_test.dart:258
  ```The argument type 'bool' can't be assigned to the parameter type 'Future<bool>'. #argument_type_not_assignable```

* mac_test.dart:44
  ```The argument type 'ProcessResult' can't be assigned to the parameter type 'Future<ProcessResult>'. #argument_type_not_assignable```

* mac_test.dart:52
  ```The argument type 'ProcessResult' can't be assigned to the parameter type 'Future<ProcessResult>'. #argument_type_not_assignable```

* mac_test.dart:75
  ```The argument type 'ProcessResult' can't be assigned to the parameter type 'Future<ProcessResult>'. #argument_type_not_assignable```

* simulators_test.dart:279
  ```The expression here has a type of 'void', and therefore cannot be used. #use_of_void_result```

**Comment by matanlurey** [comment]
To clarify, these are valid today because `dynamic` is always returned, and as long as the returned type is never treated explicitly as a `Future` (i.e. it is `await`-ed), this "just works". There is a landed change to Mockito that will correctly type these:

https://github.com/dart-lang/mockito/commit/8fbf1b1de695ffd868e03dc4559a90b57ba300f4

... but that exposes these errors above.

**Comment by matanlurey** [comment]
The last one:

> * simulators_test.dart:279
>   ```The expression here has a type of 'void', and therefore cannot be used. #use_of_void_result```

... I'm not sure how to fix. /cc @MichaelRFairhurst who helped land this check, I believe. Ideas?

**Comment by jonahwilliams** [comment]
@matanlurey `final dynamic foo = bar() as dynamic`

**Comment by matanlurey** [comment]
😭

**Comment by MichaelRFairhurst** [comment]
Jonah's correct, you can do when(x.start(...) as dynamic).thenAnswer(...)

But you shouldn't have to. I can push out a fix to this on the mockito side.

**Comment by matanlurey** [comment]
@MichaelRFairhurst Thanks! I'm not going to fix the last case then. We'll have to update Mockito before `flutter_tools` can use the latest version, then (and likely `--preview-dart-2` - though I'm not sure).

**Comment by MichaelRFairhurst** [comment]
@matanlurey looks like I misunderstood this situation a bit, I think upgrading mockito to latest will solve this problem. I knew I'd updated `verify`/`verifyAll` to handle void here, and I just confirmed that luckily I had not missed `when` for the case of `thenAnswer()`. So I think all you need is newer mockito and that one will work, please let me know if that isn't the case that you saw
