### ISSUE TITLE
[google_sign_in] Getting build failed in android studio

### ISSUE THREAD

**Issue by Preetthee** [flutter/flutter#156977]
### Steps to reproduce
1. Add the `google_sign_in` dependency to `pubspec.yaml`:
   ```yaml
   dependencies:
     google_sign_in: ^6.2.1
2. Run flutter pub get to fetch the dependency.
3. Configure Google Sign-In in the Android project (add SHA-1, modify android/build.gradle).
4. Try to run the build using flutter run or via the Android Studio "Run" button.



### Actual Results

The build is failing with the following error:

```console
* What went wrong:
Execution failed for task ':google_sign_in_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':google_sign_in_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\User\.jdks\corretto-11.0.24\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\User\.gradle\caches\transforms-3\01761d3d44a592c784df1715afe57f9c\transformed\output\temp\jmod --add-modules java.base --output C:\Users\User\.gradle\caches\transforms-3\01761d3d44a592c784df1715afe57f9c\transformed\output\jdkImage --disable-plugin system-modules}
```

### I'm using these additional dependencies:

```yaml
dependencies:
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  provider: ^6.1.2
  wakelock_plus: ^1.2.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  animations: ^2.0.11
```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-US)
    • Flutter version 3.24.3 on channel stable at C:\Users\User\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35303.130
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] IntelliJ IDEA Community Edition (version 2024.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.94.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 124.0.6367.91
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 129.0.2792.89

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by Jorrmungandr** [comment]
I fixed this issue by downgrading `jdk` to version 17, just download jdk17 and run `flutter config --jdk-dir "C:\Program Files\Java\jdk-17"`

**Comment by Preetthee** [comment]
> I fixed this issue by downgrading `jdk` to version 17, just download jdk17 and run `flutter config --jdk-dir "C:\Program Files\Java\jdk-17"`

That worked

**Comment by rajeswarmohanty** [comment]
yes worked
