### ISSUE TITLE
Placeholder widget for images that haven't yet loaded

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#157]
<a href="https://github.com/afandria"><img src="https://avatars.githubusercontent.com/u/2432033?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [afandria](https://github.com/afandria)**
_Friday Sep 04, 2015 at 23:29 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1072_

----

Related: #801 

Since images can occasionally fail to load, it reminded me that it's worth having alternative text drawn on-screen in the missing image's place.

(Supposedly, this would also be helpful for accessibility purposes, but I'm not sure if Sky intends to support screen readers and such.)

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Sep 08, 2015 at 16:18 GMT_

----

Sky will support screen readers.  We'll need to think about what we want to have happen when network images fail to load.  We probably want a callback at minimum so that developers can choose to do whatever they want.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Tuesday Oct 13, 2015 at 19:17 GMT_

----

Why would images fail to load? If they're core app assets, presumably they come with the app, and basically can't fail (unless something catastrophic is going on). If they're network images like a user's album photos or whatnot, it's not clear that the right behaviour is to display text instead.

(This is orthogonal to accessibility concerns.)

Do you have a concrete case in mind?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/afandria"><img src="https://avatars.githubusercontent.com/u/2432033?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [afandria](https://github.com/afandria)**
_Tuesday Oct 13, 2015 at 19:24 GMT_

----

I don't know why the images are failing to load, but they are. I even specified them in my app's `manifest.yaml`. (I haven't updated recently, but I am on 0.0.53 and the images are still lost occasionally. IIRC, there was a fix for image decoders that went in just after that version.)

Otherwise, my use case is the same as the web's. When an image that is pulled from the internet fails to load, I want alt text to show up in its place. That would require NetworkImage to accept the alt text as a property. It doesn't have to be the only fallback, but I think it's one of the common ones.

An alternative would be to allow a placeholder Widget until the image loads, since that will satisfy many use cases.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Tuesday Oct 13, 2015 at 19:34 GMT_

----

If you're getting lost images on the latest trunk, please do file a bug for that. We shouldn't be losing images.

The Web's use case for alternative text is that sometimes people disable images, sometimes people use text-only browsers, and sometimes they write documents where they use images in place of text, and when using screen readers, the image should be in-place replaced by text. None of these apply to flutter. (Also, on the Web, we've learnt that authors are horrifically bad at writing good alternative text, so even if those were the use cases, we should find better solutions.)

Having a placeholder widget for images that are not yet loaded is interesting. A big concern with image loading in general is that because layout depends on image dimensions, as images are loading the layout can change. This is bad for performance and results in really ugly UI reminiscent of the way the Web jumps around when pages are loading. I'd really like us to find a way to avoid that.

**Comment by Hixie** [comment]
This now only applies to images that are coming from the network, and thus not part of the app, since images in the assets file will be quick to load. Showing network images is probably something that the developer would wrap with loading behaviour anyway, so I'm not sure we really need to do anything explicit here.

**Comment by sethladd** [comment]
Going to close because we don't have plans to take action, but please reopen if we need to.
