### ISSUE TITLE
Libtxt causes clipping issues

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#15702]
I noticed that the slider value indicator path is sometimes being clipped by things around it, and that over a certain text scale (about 2.0), the text in the value indicator doesn't draw at all (but the path does).  I bisected this on the framework and engine sides, and it appears that turning on libtxt caused both of these problems.

Framework at good engine: b9bd51cc36b706215915711e580851901faebb40
Framework at bad engine: 5a58b36e36b8d7aace89d3950e6deb307956a6a0

Last good engine commit: e44cd55fc452ba5524147280c451fb3ace350ec4
First bad engine commit: e61bb9ac3a3fd789754e2e54220bcfc27076a857

![screenshot_20180319-102657](https://user-images.githubusercontent.com/8867023/37612232-dcde3ade-2b61-11e8-8326-d3a1ecad03a3.png)

![screenshot_20180319-102711](https://user-images.githubusercontent.com/8867023/37612234-dfde23c0-2b61-11e8-838e-8ca7ca3e76eb.png)

**Comment by xqwzts** [comment]
Seems safe to guess that this is also what causes https://github.com/flutter/flutter/issues/15659

**Comment by jason-simmons** [comment]
Skia bug: https://bugs.chromium.org/p/skia/issues/detail?id=7739

**Comment by gspencergoog** [comment]
It looks like Skia bug is fixed, but just not yet closed in their system.
