### ISSUE TITLE
Custom video and audio codecs / container formats for camera plugin

### ISSUE THREAD

**Issue by Flajt** [flutter/flutter#157055]
### Use case

I'd like to record videos and capture images with the device camera. However I want to decide what codec is used in case I need a specific format (My usecase would be adding metadata to files so any new mpeg4 codecs are suboptimal).

I looked into camera_awesome, however they only support custom codecs for ios and not android.

I've tried to generate bindings for android using jnigen but either I'm to stupid or it doesn't work.
I've also tried to create a custom plugin, but I'm failing at displaying the preview using the camera2 api (recording works tho...) but I'm no native developer so I'm somewhat stuck.

### Proposal

Provide the either one option class or two (one android, one ios or a combined one), with video, audio and optional container format, instead of autoselecting it (I only checked the android code, as far as I understand it, it will select the best option for the mediarecorder to use)

**Comment by huycozy** [comment]
I think this is similar to https://github.com/flutter/flutter/issues/86984. Please also add a comment there with your use case that may be useful. Closing this as a duplicate.
