### ISSUE TITLE
[CP-beta] Starts looking for the bdf fast path in relation to the snapshot_entity's transform

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#157060]
### Issue Link

https://github.com/flutter/flutter/issues/156871

### Target

beta

### Cherry pick PR Link

https://github.com/flutter/engine/pull/55917

### Changelog Description

Fixes a rendering performance regression for users of BackdropFilter on Impeller iOS and Android where small filters were being rendered as large filters.

### Impacted Users

all users that use backdrop filter blurs

### Impact Description

Possible visible framerate drop and lower battery life.

### Workaround

None.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the `backdrop_filter_perf*` devicelab benchmarks before and after.

**Comment by zanderso** [comment]
CP LGTM

**Comment by gaaclarke** [comment]
> @gaaclarke can I get you to reformat the change log description to follow these best practices.

You are talking about the commit message for the cherry-pick PR?

**Comment by gaaclarke** [comment]
> @gaaclarke can I get you to reformat the change log description to follow these best practices.

@reidbaker done (he was referring to the "change description" section in the issue's description)
