### ISSUE TITLE
Broken Android Dart integration tests when ran through gradle 

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#157018]
Dart integration tests with Android are consistently failing and blocking flutter -> packages roller seemingly due to: https://github.com/flutter/flutter/pull/156597.

This PR causes the Firebase TestLab Android tests to fail. The common error looks to be:

```
10-13 08:52:39.058 23656 23656 I flutter : The following assertion was thrown during a scheduler callback:
10-13 08:52:39.058 23656 23656 I flutter : Matrix4 entries must be finite.
10-13 08:52:39.058 23656 23656 I flutter : 'dart:ui/painting.dart':
10-13 08:52:39.058 23656 23656 I flutter : Failed assertion: line 42 pos 10: '<optimized out>'
10-13 08:52:39.058 23656 23656 I flutter : 
10-13 08:52:39.058 23656 23656 I flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
10-13 08:52:39.058 23656 23656 I flutter : more information in this error message to help you determine and fix the underlying cause.
10-13 08:52:39.058 23656 23656 I flutter : In either case, please report this assertion by filing a bug on GitHub:
10-13 08:52:39.058 23656 23656 I flutter :   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
10-13 08:52:39.058 23656 23656 I flutter : 
10-13 08:52:39.058 23656 23656 I flutter : When the exception was thrown, this was the stack:
10-13 08:52:39.058 23656 23656 I flutter : #2      _matrix4IsValid (dart:ui/painting.dart:42:10)
10-13 08:52:39.058 23656 23656 I flutter : #3      _NativeSceneBuilder.pushTransform (dart:ui/compositing.dart:628:12)
10-13 08:52:39.058 23656 23656 I flutter : #4      TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1969:27)  
```

I was not able to reproduce the failure locally when running the integration from the Android Studio IDE, but could reproduce when running the tests with gradle.

**Note:** The Firebase Testlab tests compile the app with gradle and then uploads the test to Firebase to be ran.

To reproduce test failure locally:

1. Choose an Android plugin that is failing consistently in [flutter/packages](https://github.com/flutter/packages) (I typically choose `pacakges/webview_flutter/webview_flutter_android`).

2. Build example in `example/` 

```
flutter build apk --debug
```

3. Run Dart integration with Gradle in `example/android/`:

```
./gradlew app:connectedAndroidTest -Ptarget=`pwd`/../integration_test/webview_flutter_test.dart
```

Most of the test will fail when running.

I used https://github.com/flutter/flutter/issues/157018 for testing on Firebase Testlab failures. See https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8733974383434278129/+/u/Run_package_tests/Firebase_Test_Lab/stdout?format=raw for logs.

**Comment by bparrishMines** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
Can you share a link to one of the tests? The error message indicates that the layer tree has bad data, but that is all produced via the UI thread operations. so in theory, it should be possible to determine what changed just via inspecting the dart code.

One possibility: we have exisitng issues where tests/widgets et cetera do not correctly handle having a window size of 0,0. Its entirely possible that via division or some such we can end up with infinite or nan values in a matrix.

**Comment by bparrishMines** [comment]
Yes here are the result of a failing Firebase Testlab test:

Full log file: https://ff0ecf8677b8f33fa0ba25424df5632075d333efebf7099dfdc5586-apidata.googleusercontent.com/download/storage/v1/b/flutter_firebase_testlab_staging/o/plugins_android_test%2Fpackages%2Fespresso%2Funknown_build%2F32c75136-88fd-4898-be6a-9592e2d36cb7%2Fexample%2F0%2Fpanther-33-en-portrait%2Flogcat?jk=AdvOr8sEaLp49thad2JGWZTPzAGSPvC7heBHPJHSASMW06ZfMInzCe--lYhJsJJKTWl-NMWRgn6CK_E46v1CvNSV7oQ2QgTOfask8FPdpMDJfOdhXOYfeN2Xlua96z73xZH7mfEgyKf7wg7gO3YkROFvMhaQgb59UgRxnbdQAtSHNsz9ULpAJT8bGstyaaa_EX4DjWDIfD1B6pN1I7cCG2Mn9GNgdVWLC2VKF2Xw_gq9f8Z3hQ59iCixRLb5_goYhoO_WvioOjYJ-fMZrA7LlcsAIW8ob2_3-9bkUjbPf3T1jqgwqf8mYGTPU928-EfQBFEN6I8_4k1Rijn6DZ1BnVT7Uw84PYUMR6FUM789uxg7hseI2PlFbfCKcz0nrWf9LPo6D9bGmjK6HCh_lrHsNvIcl69w5o1E-gJ8sqdDICmSKiMJwl1AcXUaxUi_Hk-fKK_WYxLkBAkeGK_W3MblIPI9YgLeA4bBg1H7CJTVJlG1PWL_o6TL4rylIsVnjT49btr5x-XWgr1q4wrmoyYA3TPGngJXonIHRfD6RUKk4khVKIi5Z_3mlZmspeL-vzgicoGG9RqoTzIiX8qzNHmkRvZSb2x1N6xDdcL1hbDSxLLCAw49LURkcI9xybcfSMjm_-3ad187USq-cNTiCp-PGUHQnP4OYci2cP3dXGmAHlT5M1O4UpA8RTokdYskat4jXtwfm8IZgCiAETOo5Vkl82BcXNYIzNkiWFRb9gDP47otB4WhtSp2OW1SpKoMeqC3kxgR515lclIan6as7a5_rIAG8CeOnhzC7oUXNhIhS4a7cOQq80SsT5yp-0El4mp49cIB2hIFBIAG-dGQ0zbCzyEXPJKobx75_zxP1yeTC2kS9Q0j9dQ3-hTiCNeAx6lvMnCwTH_S7MKt0Erwo5u3wIgAB6i50Ve769ASCxcoygLhIBXqHvO8nIft4qQwcNdBStHutAx-dIzzIB0AgivNgcBrwD_teAP6NTgYpYOOSbGm4RvhlOcMuwheM2ZOJca11JDrmUtwytJklN9AsGlseLZl1phNAoUGGygK6WHtpJGbnehjDJPyY-kVHK9BIvHNXLT6jXipMGmO1sks_m3Lf74RkXdQAjXVj0stJTHOmW-b7HTkBQc_9AlEz56a36zJqlpg7bZNr_V4HdNSH9-vsRXQajP7afKQgX33bZvUVxj0terJsifBrRBQnnmSvk70CKQoQiSopdalGH71YZR5yP9D_oFTRxUGP1mtvZEaPQ1pdVV_qsWHlytkNplTUl4HpPsJ-xkXNjds232xx4jnhRqWEE_vWnIlmXAh_jv2V3H1toYEaYX9CG3SYmgrXQ&isca=1

Firebase Testlab Link: https://console.firebase.google.com/project/flutter-infra-staging/testlab/histories/bh.368058afb9fac8d2/matrices/5532374539830738416

**Comment by bparrishMines** [comment]
The first test to fail locally for `webview_flutter_android` was `onHttpError`: https://github.com/flutter/packages/blob/main/packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart#L974

**Comment by jason-simmons** [comment]
Reproduced this locally on an Android API 33 emulator:

* `cd packages/webview_flutter/webview_flutter_android/example/android`
* ```./gradlew app:assembleDebug -Ptarget=`pwd`/../integration_test/webview_flutter_test.dart```
* `./gradlew app:assembleAndroidTest`
* `adb install -r ../build/app/outputs/apk/debug/app-debug.apk`
* `adb install -r ../build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk`
* `adb shell am instrument io.flutter.plugins.webviewflutterandroidexample.test/androidx.test.runner.AndroidJUnitRunner`

The Android logcat logs will show various exceptions starting with the `_matrix4IsValid` assertion.

Confirmed that this started with the https://github.com/flutter/flutter/pull/156597 engine roll.

**Comment by jason-simmons** [comment]
There is a race between the Android embedding receiving viewport metrics and the layout of the first frame in the framework.

The `FlutterView` in the Android embedding does not learn its size until Android does its first view layout and calls `FlutterView.onSizeChanged`. `FlutterView` will send the new viewport metrics to the engine, which will propagate them to the framework.

Before that the Android embedding will send viewport metrics populated with zero values.

There is no synchronization between the size update and the framework's building of frames.  The UI/platform thread merge apparently changes the timing so that the framework builds the initial warm-up frame before it receives the nonzero viewport metrics.

This test is using the integration test framework.  `IntegrationTestWidgetsFlutterBinding` overrides `createViewConfigurationFor` with an implementation that creates a `TestViewConfiguration` based on the currently known size.

The test fails because `TestViewConfiguration._getMatrix` is computing a matrix containing NaN values.  It needs to be updated to handle a zero size.
