### ISSUE TITLE
Investigate/Instrument performance benefits of using multithreading in EAGLContext.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#15707]
We already have a separate GPU thread on all platforms and use multiple OpenGL ES contexts where available. However, [`[EAGLContext multithreaded]`](https://developer.apple.com/documentation/opengles/eaglcontext/1624881-multithreaded) attempts to offload some on the work typically performed by OpenGL ES to another (managed) thread. This has some overhead but may yield a net benefit on iOS. We should enable this option and understand if there is a benefit for Flutter applications. [This document](https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/ConcurrencyandOpenGLES/ConcurrencyandOpenGLES.html#//apple_ref/doc/uid/TP40008793-CH409) details all the ways in which concurrency in rendering may benefit us. We follow all the best practices listed in that document except the multithreading flag in OpenGL ES. Let's find out if it makes sense to flip that flag.

**Comment by Hixie** [comment]
With our move to Metal should we forget about this?

**Comment by chinmaygarde** [comment]
Sounds good to me.
