### ISSUE TITLE
Spelling Error in ChangeLog

### ISSUE THREAD

**Issue by rennylangat** [flutter/flutter#157083]
### Steps to reproduce

1. Navigate to the Flutter Github Repo.
2. In the root folder open the ChangeLog.MD file
3. In the latest documentation, there is a spelling error on 3.24.3 changelog addressing issue #153574

### Expected results

The changelog should read as follows:

```[Impeller][iOS] Fixes an issue when using Impeller on iOS when using backdrop filers on older iPads,causing the GPU to hang.```

### Actual results

The changelog now reads as follows:

```[Impeller][iOS] Fixes an issue when using Impeller on iOS when using backdrop filers on older iPads,causing the GPU to hand.```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
There's another typo in that particular message. It says `backdrop filers` instead of `backdrop filters`.

**Comment by Piinks** [comment]
@rennylangat would you like to send a PR?
