### ISSUE TITLE
Update Getting to know firebase for flutter codelab

### ISSUE THREAD

**Issue by stevebetts** [flutter/flutter#157014]
It seems there have been changes to dart, the sdk, and/or some of the dependencies that could use to be addressed in the "Get to know Firebase for Flutter" codelabs - https://firebase.google.com/codelabs/firebase-get-to-know-flutter?hl=en

**Comment by danagbemava-nc** [comment]
Hi @stevebetts, are you facing any errors when using the codelab? If so, kindly share the errors along with the version of flutter you're using and the dependencies you're using. 

Thank you

**Comment by stevebetts** [comment]
Yes.  I'm completely new to Flutter and Dart.  This is only my second day working with any of it.  I set up my environment (mac) as explained in the getting started guide at https://docs.flutter.dev/get-started/install/macos/mobile-ios.  Everything seemed to install without issue.

Running flutter --version returns...
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (5 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

As for dependencies - just what is specified in the codelab files - firebase-get-to-know-flutter/Step_02 and those I was instructed to add when working through the exercises.  I'll note that adding some of the dependencies resulted in messages like "18 packages have newer versions incompatible with dependency constraints."  Not sure if that is an issue or not or how to resolve it if it is.

I made it to the end of step five in the exercise but, when it came time to run the app - no luck.  The debug output window in vscode shows...
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is a package manager for iOS or macOS platform code.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/to/platform-plugins
For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

Error: CocoaPods not installed or not in valid state.

When I installed cocoa pods I received the following...
Successfully installed cocoapods-1.15.2
Parsing documentation for cocoapods-1.15.2
Done installing documentation for cocoapods after 1 seconds
1 gem installed

No errors were shown so I have to think it was installed correctly.

Anyway, I was just trying to point out that I have followed the steps as outlined in the codelab exercise and can't get past step 5.  That may not be on you but perhaps it is something to look into.  I wish I could be more helpful but this is all very new to me.

You can flag this issue as closed if you want.  I think my journey into Flutter has come to an end.  I was curious to see it in action but don't have the time or desire to fight with it. 

Cheers

**Comment by stevebetts** [comment]
Following up in case it helps someone.  I restarted vscode and that seemed to resolve the cocoapods issue.  I then started getting an error stating...
The plugin "cloud_firestore" requires a higher minimum iOS deployment version than your application is targeting.

To resolve that issue I had to modify the iOS/Podfile file.  Uncommenting the second line and changing the platform :ios value from '12.0' to '13.0' cleared that up.

I then tried running the debugger and it has been stuck on "Flutter: Running Xcode build..." for over 20 minutes.  I'm definitely done and moving on now.

**Comment by danagbemava-nc** [comment]
> "18 packages have newer versions incompatible with dependency constraints." Not sure if that is an issue or not or how to resolve it if it is.

The codelab was written a while ago so some of its dependencies are out of date. 

> I then tried running the debugger and it has been stuck on "Flutter: Running Xcode build..." for over 20 minutes. I'm definitely done and moving on now.

Could we get the full output of `flutter run -v` ? The output will be huge, so kindly put it into a .txt or a .log file and attach it here.  We could use this to help you and others who may run into this issue in the future

**Comment by stevebetts** [comment]
I have nothing more of substance to add.  I have since completely uninstalled Flutter and have moved on as I indicated in my previous response.  The only point I was trying to make is I followed the codelab instructions and something didn’t work.  Perhaps it is just me but I thought it was worth mentioning so someone might be compelled to look into it.

**Comment by danagbemava-nc** [comment]
The codelab is being reviewed in https://github.com/flutter/flutter/issues/157571 and this will likely be fixed as part of the review. 

Closing this in favor of the issue linked above. 

Thank you
