### ISSUE TITLE
Failing to run my first ever Flutter App

### ISSUE THREAD

**Issue by 1SouravGhosh** [flutter/flutter#15703]
I'm getting below error on running my first ever flutter app:
* Error running Gradle:
Exit code 1 from: D:\PROJECTS\softwareProjects\AndroidProjects\flutter_app_2\android\gradlew.bat app:properties:
Download https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar

========================================
* Error running Gradle:
Exit code 1 from: D:\PROJECTS\softwareProjects\AndroidProjects\flutter_app_2\android\gradlew.bat app:properties:
Download https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download bcprov-jdk15on.jar (org.bouncycastle:bcprov-jdk15on:1.56)
Finished with error: Please review your Gradle project setup in the android/ folder.
      > Could not get resource 'https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'.
         > Response 304: Not Modified has no content!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

=====================================================

What would possibly be the solution ? Help!!

**Comment by salehahmedZ** [comment]
Could you please post the "flutter doctor -v" output.

**Comment by 1SouravGhosh** [comment]
PFB:

C:\Users\silve>flutter doctor -v
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-IN)
    • Flutter version 0.1.5 at C:\Users\silve\flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\silve\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\AndroidStudio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!

**Comment by zoechi** [comment]
Sounds like an issue with Gradle

**Comment by 1SouravGhosh** [comment]
how to fix Gradle issue?? The jar file, downloading from the link seems to be broken.

**Comment by rmtmckenzie** [comment]
You can probably fix that by going opening a command prompt to your project/android folder and running `gradlew build --refresh-dependencies`.

Once you've done the initial `flutter run` or `flutter build` command (or pressed build in your IDE) you can use gradle as you would for any other android project.

Quick question though - have you added anything to your gradle dependencies in `android/build.gradle` or `android/app/build.gradle`? I don't remember bouncy castle being needed for flutter.

Another thing to try would be deleting your gradle cache. See [this stackoverflow question](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache) clearing gradle cache.

If that doesn't work and you haven't added anything manually, it would help to list which packages you depend on in your pubspec.yaml.

**Comment by 1SouravGhosh** [comment]
I'm getting same error while running gradlew build --refresh-dependencies or trying to remove the gradle cache.

d:\PROJECTS\softwareProjects\AndroidProjects\flutter_app_2\android>gradlew build --refresh-dependencies

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by 1SouravGhosh** [comment]
I deleted the cache and tried to run the App from my ide but still getting the same issue.

**Comment by rmtmckenzie** [comment]
Hmm. Well the gradlew build error seems like a completely different issue - are you running java 9? If so, you need to be using a recent version of Gradle or it won't work (I believe 4.4+ but I could be wrong about that). To upgrade gradle you can modify android/gradle/wrapper/gradle.properties and change the gradle distribution url to https\://services.gradle.org/distributions/gradle-4.6-all.zip. Or just make sure java 8 is in your path when working on this project.

Flutter Doctor says it's using java 1.8 though so that shouldn't affect the IDE's build or anything using flutter commands.

Try adding maven central to your repositories in android/build.gradle. That might be the problem, although the errors it's giving is a bit weird.
```
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}
```

**Comment by 1SouravGhosh** [comment]
I changed the gradle distribution to url to https://services.gradle.org/distributions/gradle-4.6-all.zip.
tried with the Java version 9 in my machine but it didn't work. then downgraded my Java version to 8 and
added mavenCentral() to allprojects.
Nothing is working. Even checked my firewall in case it's blocking the download of the file, but firewall also is not the issue here.

**Comment by rmtmckenzie** [comment]
Hmm well I'm at a little bit of a loss. Is your project something that can be made public? I'd be willing to give it a try if you're able to share the source.
If not, if you could post your android/build.gradle, android/app/build.gradle, and pubspec.yaml that might help me figure out what's going on.

**Comment by rmtmckenzie** [comment]
Ah. This might not be anything to do with your project, although I'm still slightly curious as to why bcprov-jdk15on is needed unless you've explicitly required it. But check [this](https://github.com/gradle/gradle/issues/4703) and [this](http://status.bintray.com/) out - it seems as though there's an issue with jcenter's Bintray configuration.

If you remove jcenter() or put it after mavenCentral() that might help as it should then try to download the dependency from mavenCentral first.

**Comment by 1SouravGhosh** [comment]
Sure I can upload my project. It's just a demo app to test run flutter on my new pc.

**Comment by 1SouravGhosh** [comment]
[flutter_app_3.zip](https://github.com/flutter/flutter/files/1828046/flutter_app_3.zip)

**Comment by 1SouravGhosh** [comment]
@rmtmckenzie Please find above. I zipped the entire app folder to make sure I was missing nothing.

**Comment by 1SouravGhosh** [comment]
I just added both mavenCentral(),  jcenter() in allprojects and it worked!!  :)
I did it once previously also but it didn't work. May be I did something wrong that time but now it's working!!

@rmtmckenzie Thanks for the suggestion. PFB 
========= below code is from fixed project=======================
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by rmtmckenzie** [comment]
Glad it worked out! I think the problem is that jCenter is having issues right now, and by putting MavenCentral before it in your build.gradle gradle checks that first and so doesn't fail when jCenter craps out =D.

**Comment by jinxac** [comment]
yeah even i was facing this issue and it works after adding `mavenCentral()`, thanks @1SouravGhosh

**Comment by zhuiye** [comment]
The same problem,adding mavenCentral(),But it did not work properly, and it gave an error.
on windows
* Error running Gradle:
ProcessException: Process "E:\flutter\first_app\android\gradlew.bat" exited abnormally:
FAILURE: Build failed with an exception.
* What went wrong:
org/gradle/api/internal/artifacts/ivyservice/ErrorHandlingConfigurationResolver$BrokenResolvedConfiguration
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
  Command: E:\flutter\first_app\android\gradlew.bat app:properties

**The following is my build file**

`buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
       
    }

    **dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }**
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}



`
