### ISSUE TITLE
Selection misalignment occurs when mixing custom emojis with text

### ISSUE THREAD

**Issue by men620** [flutter/flutter#157157]
Hello, my SelectionArea encountered a misalignment of emoji text when selecting and copying while mixing custom emojis and text
![无标题](https://github.com/user-attachments/assets/33596846-1942-4a25-81a9-496412dda572)

```dart
import 'dart:ui';
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:extended_text/extended_text.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_svg/svg.dart';
import 'package:intl/intl.dart';
import 'generated/intl/messages_all.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      supportedLocales: S.delegate.supportedLocales,
      localizationsDelegates: const [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
      title: 'SelectionArea实现文本全选复制功能',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'SelectionArea实现文本全选复制功能'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final String content = "天气[aiyi][aiyi][aiyi]啊\nemm[baituo][baituo]唉";

  get _listView => ListView(
        padding:
            const EdgeInsets.only(left: 12, right: 12, top: 15, bottom: 15),
        children: [_textContent],
      );

  get _textContent => IBSelectionArea.wrap(ExtendedText(
        content,
        style: TextStyle(fontSize: 16),
        specialTextSpanBuilder: DefaultSpecialTextSpanBuilder(
          context: context,
          highlightStyle:
              TextStyle(fontSize: 16, fontWeight: FontWeight.w400, height: 1.5),
        ),
        maxLines: null,
        overflow: TextOverflow.fade,
        boxHeightStyle: BoxHeightStyle.max,
      ));

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: _listView,
    );
  }
}

class DefaultSpecialTextSpanBuilder extends SpecialTextSpanBuilder {
  DefaultSpecialTextSpanBuilder(
      {TextStyle? highlightStyle, this.emojiSize, this.context}) {
    _highlightStyle = highlightStyle;
  }

  late TextStyle? _highlightStyle;
  double? emojiSize;
  BuildContext? context;

  @override
  TextSpan build(String data,
      {TextStyle? textStyle, SpecialTextGestureTapCallback? onTap}) {
    if (data == '') {
      return const TextSpan(text: '');
    }
    List<InlineSpan> inlineList = <InlineSpan>[];
    inlineList = getSpans(data, context!, textStyle, onTap);
    return TextSpan(children: inlineList, style: textStyle);
  }

  List<InlineSpan> getSpans(String data, BuildContext context,
      TextStyle? textStyle, SpecialTextGestureTapCallback? onTap) {
    String originalData = revertBreakWord(data);
    var urls = UrlList().getUrls(originalData);
    List<InlineSpan> spans = [];
    int start = 0;
    int end;
    if (urls.isNotEmpty) {
      for (var element in urls) {
        end = originalData.toLowerCase().indexOf(element.toLowerCase(), start);
        String beforeUrl = originalData.substring(start, end);
        spans.addAll(buildString(beforeUrl, textStyle, onTap));
        spans.add(TextSpan(
            text:
                breakWord(originalData.substring(end, (end + element.length))),
            style: _highlightStyle));
        start = (end + element.length);
      }
    }
    String afterUrl = originalData.substring(start, originalData.length);
    spans.addAll(buildString(afterUrl, textStyle, onTap));
    return spans;
  }

  SpecialText? createSpecialText1(String flag, String data,
      {TextStyle? textStyle,
      SpecialTextGestureTapCallback? onTap,
      required int index}) {
    if (flag == '') {
      return null;
    }
    if (isStart(flag, '[')) {
      return Emoji(textStyle,
          start: index - ('['.length - 1), sizeRatio: emojiSize);
    } else if (isStart(flag, Highlight.flag)) {
      return Highlight(_highlightStyle,
          start: index - (Highlight.flag.length - 1));
    }
    return null;
  }

  List<InlineSpan> buildString(
      String data, TextStyle? textStyle, SpecialTextGestureTapCallback? onTap) {
    final List<InlineSpan> inlineList = <InlineSpan>[];
    if (data == '') {
      return inlineList;
    }
    if (data.isNotEmpty) {
      SpecialText? specialText;
      String textStack = '';

      //String text
      for (int i = 0; i < data.length; i++) {
        final String char = data[i];
        textStack += char;
        if (specialText != null) {
          // always append
          // and remove endflag in getContent method
          specialText.appendContent(char);
          if (specialText.isEnd(textStack)) {
            inlineList.add(specialText.finishText());
            specialText = null;
            textStack = '';
          }
        } else {
          specialText = createSpecialText1(textStack, data,
              textStyle: textStyle, onTap: onTap, index: i);
          if (specialText != null) {
            if (textStack.length - specialText.startFlag.length >= 0) {
              textStack = textStack.substring(
                  0, textStack.length - specialText.startFlag.length);
              if (textStack.isNotEmpty) {
                inlineList.add(TextSpan(text: textStack, style: textStyle));
              }
            }
            textStack = '';
          }
        }
      }

      if (specialText != null) {
        inlineList.add(TextSpan(
            text: specialText.startFlag + specialText.getContent(),
            style: textStyle));
      } else if (textStack.isNotEmpty) {
        if (textStack == '\u200B\u200B') {
          textStack = " $textStack";
          textStyle = textStyle?.copyWith(fontSize: 1);
        }
        inlineList.add(TextSpan(text: textStack, style: textStyle));
      }
    } else {
      inlineList.add(TextSpan(text: data, style: textStyle));
    }
    return inlineList;
  }

  @override
  SpecialText? createSpecialText(String flag,
      {TextStyle? textStyle,
      SpecialTextGestureTapCallback? onTap,
      required int index}) {
    return null;
  }
}

class Highlight extends SpecialText {
  Highlight(TextStyle? textStyle, {this.start}) : super(flag, flag, textStyle);

  static const String flag = '\$&※';
  final int? start;

  @override
  InlineSpan finishText() {
    final String text = getContent();

    return SpecialTextSpan(
        text: breakWord(text),
        actualText: toString(),
        start: start!,
        deleteAll: true,
        style: textStyle);
  }
}

///解决字符串中有- 空格等导致Text控件异常换行的问题.
String breakWord(String word) {
  if (word.isEmpty) {
    return word;
  }
  StringBuffer breakWord = StringBuffer();
  for (var element in word.trim().runes) {
    breakWord.write(String.fromCharCode(element));
    breakWord.write('\u200B');
  }
  return breakWord.toString();
}

String revertBreakWord(String word) {
  if (word.isEmpty) {
    return word;
  }
  StringBuffer breakWord = StringBuffer();
  for (var element in word.trim().runes) {
    if (element != 8203) {
      breakWord.write(String.fromCharCode(element));
    }
  }
  breakWord.write('\u200B\u200B');
  return breakWord.toString();
}

/// 表情文本
///
/// 例如：这里包含表情[jingli1]。其中“[jingli1]”将被尝试识别为表情，查找表示你好的表情并填充在它的位置。
class Emoji extends SpecialText {
  Emoji(TextStyle? textStyle, {this.start, this.sizeRatio})
      : super(Emoji.flag, ']', textStyle);
  static const String flag = '[';
  final int? start;
  final double? sizeRatio;

  @override
  InlineSpan finishText() {
    final String key = toString();
    if (EmojiUtil.instance.defaultCommonEmojiMap.containsKey(key)) {
      double size = 18;
      if (textStyle?.fontSize != null) {
        double ratio = 1.15;
        final tempRatio = sizeRatio;
        final height = textStyle!.height;
        if (tempRatio != null &&
            height != null &&
            tempRatio >= 1.0 &&
            tempRatio <= height) {
          ratio = tempRatio;
        } else if (height != null) {
          ratio = height;
        }
        size = textStyle!.fontSize! * ratio;
      }
      return ImageSpan(
          MyAssets.assetImage(
            EmojiUtil.instance.defaultCommonEmojiMap[key]!,
          ),
          actualText: key,
          imageWidth: size,
          imageHeight: size,
          start: start!,
          fit: BoxFit.contain,
          margin: const EdgeInsets.all(2));
    }
    return TextSpan(text: toString(), style: textStyle);
  }
}

class EmojiUtil {
  EmojiUtil._() {
    for (var name in _commonEmojiSet) {
      _defaultCommonEmojiMap['[$name]'] =
          '$_defaultCommonEmojiBasePath/$name.png';
    }
  }
  final String _defaultCommonEmojiBasePath = 'assets/commonEmoji';
  final Map<String, String> _defaultCommonEmojiMap = <String, String>{};
  /// 通用表情，表情名-表情文件名映射关系
  Map<String, String> get defaultCommonEmojiMap => _defaultCommonEmojiMap;
  final List<String> _commonEmojiSet = ["aiyi", "baituo"];
  /// 通用表情贴图，表情贴图名集合
  List<String> get defaultCommonEmojiSet => _commonEmojiSet;
  static EmojiUtil? _instance;
  static EmojiUtil get instance => _instance ??= EmojiUtil._();
}

class S {
  S();
  static S? _current;
  static S get current {
    assert(_current != null,
        'No instance of S was loaded. Try to initialize the S delegate before accessing S.current.');
    return _current!;
  }
  static const AppLocalizationDelegate delegate = AppLocalizationDelegate();

  static Future<S> load(Locale locale) {
    final name = (locale.countryCode?.isEmpty ?? false)
        ? locale.languageCode
        : locale.toString();
    final localeName = Intl.canonicalizedLocale(name);
    return initializeMessages(localeName).then((_) {
      Intl.defaultLocale = localeName;
      final instance = S();
      S._current = instance;

      return instance;
    });
  }

  static S of(BuildContext context) {
    final instance = S.maybeOf(context);
    assert(instance != null,
        'No instance of S present in the widget tree. Did you add S.delegate in localizationsDelegates?');
    return instance!;
  }

  static S? maybeOf(BuildContext context) {
    return Localizations.of<S>(context, S);
  }

  /// `Love`
  String get love {
    return Intl.message(
      'Love',
      name: 'love',
      desc: '',
      args: [],
    );
  }

  /// `Please`
  String get please {
    return Intl.message(
      'Please',
      name: 'please',
      desc: '',
      args: [],
    );
  }
}

class AppLocalizationDelegate extends LocalizationsDelegate<S> {
  const AppLocalizationDelegate();
  List<Locale> get supportedLocales {
    return const <Locale>[
      Locale.fromSubtags(languageCode: 'en'),
      Locale.fromSubtags(languageCode: 'zh'),
    ];
  }
  @override
  bool isSupported(Locale locale) => _isSupported(locale);
  @override
  Future<S> load(Locale locale) => S.load(locale);
  @override
  bool shouldReload(AppLocalizationDelegate old) => false;
  bool _isSupported(Locale locale) {
    for (var supportedLocale in supportedLocales) {
      if (supportedLocale.languageCode == locale.languageCode) {
        return true;
      }
    }
    return false;
  }
}

class MyAssets {
  static String? moduleName;
  static AssetImage assetImage(String assetName) {
    return AssetImage(assetName, package: moduleName);
  }
}

class UrlList {
  List<String> getUrls(String content) {
    List<String> urlList = [];
    RegExp exp = RegExp(
        "(https?|ftp|file)://[-A-Za-z0-9+&#/%?=~_|!:,.;]+[-A-Za-z0-9+&#/%=~_|]");
    var theURl = exp.allMatches(content);
    for (var element in theURl) {
      urlList.add(content.substring(element.start, element.end));
    }
    return urlList;
  }
}

///文本全选、复制
class IBSelectionArea {
  static Widget wrap(Text child, {bool selectAll = true, bool copy = true}) {
    //选择的文本
    var selectedText = '';
    return SelectionArea(
      child: child,
      onSelectionChanged: (SelectedContent? selectContent) =>
          selectedText = selectContent?.plainText ?? "",
      contextMenuBuilder:
          (BuildContext context, SelectableRegionState selectableRegionState) {
        bool selectAllEnable = false;
        //如果还有可选的内容则展示全选菜单
        if (selectedText.length < (child.data?.length ?? 0)) {
          selectAllEnable = true;
        }
        final List<ContextMenuButtonItem> buttonItems = [
          if (selectAll && selectAllEnable)
            ContextMenuButtonItem(
                label: '全选',
                onPressed: () {
                  selectableRegionState
                      .selectAll(SelectionChangedCause.toolbar);
                }),
          if (copy)
            ContextMenuButtonItem(
                label: '复制',
                onPressed: () {
                  selectableRegionState
                      .copySelection(SelectionChangedCause.toolbar);
                })
        ];
        return AdaptiveTextSelectionToolbar.buttonItems(
          buttonItems: buttonItems,
          anchors: selectableRegionState.contextMenuAnchors,
        );
      },
    );
  }
}

```

**Comment by huycozy** [comment]
Hi @men620 
Do you mean you can't select all text inside SelectionArea when it has emoji?

Which platform are you seeing the issue? (OS, device model) Please provide the output of `flutter doctor -v`.

Also, for the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Thank you!

**Comment by men620** [comment]
@huycozy 
Hi， My complete code has been pasted out. Follow this example to reproduce it. It appears on Windows 10 PC
![Uploading image.png…]()

import 'dart:ui';
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:extended_text/extended_text.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_svg/svg.dart';
import 'package:intl/intl.dart';
import 'generated/intl/messages_all.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      supportedLocales: S.delegate.supportedLocales,
      localizationsDelegates: const [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
      title: 'SelectionArea实现文本全选复制功能',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'SelectionArea实现文本全选复制功能'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final String content = "天气[aiyi][aiyi][aiyi]啊\nemm[baituo][baituo]唉";

  get _listView => ListView(
        padding:
            const EdgeInsets.only(left: 12, right: 12, top: 15, bottom: 15),
        children: [_textContent],
      );

  get _textContent => IBSelectionArea.wrap(ExtendedText(
        content,
        style: TextStyle(fontSize: 16),
        specialTextSpanBuilder: DefaultSpecialTextSpanBuilder(
          context: context,
          highlightStyle:
              TextStyle(fontSize: 16, fontWeight: FontWeight.w400, height: 1.5),
        ),
        maxLines: null,
        overflow: TextOverflow.fade,
        boxHeightStyle: BoxHeightStyle.max,
      ));

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: _listView,
    );
  }
}

class DefaultSpecialTextSpanBuilder extends SpecialTextSpanBuilder {
  DefaultSpecialTextSpanBuilder(
      {TextStyle? highlightStyle, this.emojiSize, this.context}) {
    _highlightStyle = highlightStyle;
  }

  late TextStyle? _highlightStyle;
  double? emojiSize;
  BuildContext? context;

  @override
  TextSpan build(String data,
      {TextStyle? textStyle, SpecialTextGestureTapCallback? onTap}) {
    if (data == '') {
      return const TextSpan(text: '');
    }
    List<InlineSpan> inlineList = <InlineSpan>[];
    inlineList = getSpans(data, context!, textStyle, onTap);
    return TextSpan(children: inlineList, style: textStyle);
  }

  List<InlineSpan> getSpans(String data, BuildContext context,
      TextStyle? textStyle, SpecialTextGestureTapCallback? onTap) {
    String originalData = revertBreakWord(data);
    var urls = UrlList().getUrls(originalData);
    List<InlineSpan> spans = [];
    int start = 0;
    int end;
    if (urls.isNotEmpty) {
      for (var element in urls) {
        end = originalData.toLowerCase().indexOf(element.toLowerCase(), start);
        String beforeUrl = originalData.substring(start, end);
        spans.addAll(buildString(beforeUrl, textStyle, onTap));
        spans.add(TextSpan(
            text:
                breakWord(originalData.substring(end, (end + element.length))),
            style: _highlightStyle));
        start = (end + element.length);
      }
    }
    String afterUrl = originalData.substring(start, originalData.length);
    spans.addAll(buildString(afterUrl, textStyle, onTap));
    return spans;
  }

  SpecialText? createSpecialText1(String flag, String data,
      {TextStyle? textStyle,
      SpecialTextGestureTapCallback? onTap,
      required int index}) {
    if (flag == '') {
      return null;
    }
    if (isStart(flag, '[')) {
      return Emoji(textStyle,
          start: index - ('['.length - 1), sizeRatio: emojiSize);
    } else if (isStart(flag, Highlight.flag)) {
      return Highlight(_highlightStyle,
          start: index - (Highlight.flag.length - 1));
    }
    return null;
  }

  List<InlineSpan> buildString(
      String data, TextStyle? textStyle, SpecialTextGestureTapCallback? onTap) {
    final List<InlineSpan> inlineList = <InlineSpan>[];
    if (data == '') {
      return inlineList;
    }
    if (data.isNotEmpty) {
      SpecialText? specialText;
      String textStack = '';

      //String text
      for (int i = 0; i < data.length; i++) {
        final String char = data[i];
        textStack += char;
        if (specialText != null) {
          // always append
          // and remove endflag in getContent method
          specialText.appendContent(char);
          if (specialText.isEnd(textStack)) {
            inlineList.add(specialText.finishText());
            specialText = null;
            textStack = '';
          }
        } else {
          specialText = createSpecialText1(textStack, data,
              textStyle: textStyle, onTap: onTap, index: i);
          if (specialText != null) {
            if (textStack.length - specialText.startFlag.length >= 0) {
              textStack = textStack.substring(
                  0, textStack.length - specialText.startFlag.length);
              if (textStack.isNotEmpty) {
                inlineList.add(TextSpan(text: textStack, style: textStyle));
              }
            }
            textStack = '';
          }
        }
      }

      if (specialText != null) {
        inlineList.add(TextSpan(
            text: specialText.startFlag + specialText.getContent(),
            style: textStyle));
      } else if (textStack.isNotEmpty) {
        if (textStack == '\u200B\u200B') {
          textStack = " $textStack";
          textStyle = textStyle?.copyWith(fontSize: 1);
        }
        inlineList.add(TextSpan(text: textStack, style: textStyle));
      }
    } else {
      inlineList.add(TextSpan(text: data, style: textStyle));
    }
    return inlineList;
  }

  @override
  SpecialText? createSpecialText(String flag,
      {TextStyle? textStyle,
      SpecialTextGestureTapCallback? onTap,
      required int index}) {
    return null;
  }
}

class Highlight extends SpecialText {
  Highlight(TextStyle? textStyle, {this.start}) : super(flag, flag, textStyle);

  static const String flag = '\$&※';
  final int? start;

  @override
  InlineSpan finishText() {
    final String text = getContent();

    return SpecialTextSpan(
        text: breakWord(text),
        actualText: toString(),
        start: start!,
        deleteAll: true,
        style: textStyle);
  }
}

///解决字符串中有- 空格等导致Text控件异常换行的问题.
String breakWord(String word) {
  if (word.isEmpty) {
    return word;
  }
  StringBuffer breakWord = StringBuffer();
  for (var element in word.trim().runes) {
    breakWord.write(String.fromCharCode(element));
    breakWord.write('\u200B');
  }
  return breakWord.toString();
}

String revertBreakWord(String word) {
  if (word.isEmpty) {
    return word;
  }
  StringBuffer breakWord = StringBuffer();
  for (var element in word.trim().runes) {
    if (element != 8203) {
      breakWord.write(String.fromCharCode(element));
    }
  }
  breakWord.write('\u200B\u200B');
  return breakWord.toString();
}

/// 表情文本
///
/// 例如：这里包含表情[jingli1]。其中“[jingli1]”将被尝试识别为表情，查找表示你好的表情并填充在它的位置。
class Emoji extends SpecialText {
  Emoji(TextStyle? textStyle, {this.start, this.sizeRatio})
      : super(Emoji.flag, ']', textStyle);
  static const String flag = '[';
  final int? start;
  final double? sizeRatio;

  @override
  InlineSpan finishText() {
    final String key = toString();
    if (EmojiUtil.instance.defaultCommonEmojiMap.containsKey(key)) {
      double size = 18;
      if (textStyle?.fontSize != null) {
        double ratio = 1.15;
        final tempRatio = sizeRatio;
        final height = textStyle!.height;
        if (tempRatio != null &&
            height != null &&
            tempRatio >= 1.0 &&
            tempRatio <= height) {
          ratio = tempRatio;
        } else if (height != null) {
          ratio = height;
        }
        size = textStyle!.fontSize! * ratio;
      }
      return ImageSpan(
          MyAssets.assetImage(
            EmojiUtil.instance.defaultCommonEmojiMap[key]!,
          ),
          actualText: key,
          imageWidth: size,
          imageHeight: size,
          start: start!,
          fit: BoxFit.contain,
          margin: const EdgeInsets.all(2));
    }
    return TextSpan(text: toString(), style: textStyle);
  }
}

class EmojiUtil {
  EmojiUtil._() {
    for (var name in _commonEmojiSet) {
      _defaultCommonEmojiMap['[$name]'] =
          '$_defaultCommonEmojiBasePath/$name.png';
    }
  }
  final String _defaultCommonEmojiBasePath = 'assets/commonEmoji';
  final Map<String, String> _defaultCommonEmojiMap = <String, String>{};
  /// 通用表情，表情名-表情文件名映射关系
  Map<String, String> get defaultCommonEmojiMap => _defaultCommonEmojiMap;
  final List<String> _commonEmojiSet = ["aiyi", "baituo"];
  /// 通用表情贴图，表情贴图名集合
  List<String> get defaultCommonEmojiSet => _commonEmojiSet;
  static EmojiUtil? _instance;
  static EmojiUtil get instance => _instance ??= EmojiUtil._();
}

class S {
  S();
  static S? _current;
  static S get current {
    assert(_current != null,
        'No instance of S was loaded. Try to initialize the S delegate before accessing S.current.');
    return _current!;
  }
  static const AppLocalizationDelegate delegate = AppLocalizationDelegate();

  static Future<S> load(Locale locale) {
    final name = (locale.countryCode?.isEmpty ?? false)
        ? locale.languageCode
        : locale.toString();
    final localeName = Intl.canonicalizedLocale(name);
    return initializeMessages(localeName).then((_) {
      Intl.defaultLocale = localeName;
      final instance = S();
      S._current = instance;

      return instance;
    });
  }

  static S of(BuildContext context) {
    final instance = S.maybeOf(context);
    assert(instance != null,
        'No instance of S present in the widget tree. Did you add S.delegate in localizationsDelegates?');
    return instance!;
  }

  static S? maybeOf(BuildContext context) {
    return Localizations.of<S>(context, S);
  }

  /// `Love`
  String get love {
    return Intl.message(
      'Love',
      name: 'love',
      desc: '',
      args: [],
    );
  }

  /// `Please`
  String get please {
    return Intl.message(
      'Please',
      name: 'please',
      desc: '',
      args: [],
    );
  }
}

class AppLocalizationDelegate extends LocalizationsDelegate<S> {
  const AppLocalizationDelegate();
  List<Locale> get supportedLocales {
    return const <Locale>[
      Locale.fromSubtags(languageCode: 'en'),
      Locale.fromSubtags(languageCode: 'zh'),
    ];
  }
  @override
  bool isSupported(Locale locale) => _isSupported(locale);
  @override
  Future<S> load(Locale locale) => S.load(locale);
  @override
  bool shouldReload(AppLocalizationDelegate old) => false;
  bool _isSupported(Locale locale) {
    for (var supportedLocale in supportedLocales) {
      if (supportedLocale.languageCode == locale.languageCode) {
        return true;
      }
    }
    return false;
  }
}

class MyAssets {
  static String? moduleName;
  static AssetImage assetImage(String assetName) {
    return AssetImage(assetName, package: moduleName);
  }
}

class UrlList {
  List<String> getUrls(String content) {
    List<String> urlList = [];
    RegExp exp = RegExp(
        "(https?|ftp|file)://[-A-Za-z0-9+&#/%?=~_|!:,.;]+[-A-Za-z0-9+&#/%=~_|]");
    var theURl = exp.allMatches(content);
    for (var element in theURl) {
      urlList.add(content.substring(element.start, element.end));
    }
    return urlList;
  }
}

///文本全选、复制
class IBSelectionArea {
  static Widget wrap(Text child, {bool selectAll = true, bool copy = true}) {
    //选择的文本
    var selectedText = '';
    return SelectionArea(
      child: child,
      onSelectionChanged: (SelectedContent? selectContent) =>
          selectedText = selectContent?.plainText ?? "",
      contextMenuBuilder:
          (BuildContext context, SelectableRegionState selectableRegionState) {
        bool selectAllEnable = false;
        //如果还有可选的内容则展示全选菜单
        if (selectedText.length < (child.data?.length ?? 0)) {
          selectAllEnable = true;
        }
        final List<ContextMenuButtonItem> buttonItems = [
          if (selectAll && selectAllEnable)
            ContextMenuButtonItem(
                label: '全选',
                onPressed: () {
                  selectableRegionState
                      .selectAll(SelectionChangedCause.toolbar);
                }),
          if (copy)
            ContextMenuButtonItem(
                label: '复制',
                onPressed: () {
                  selectableRegionState
                      .copySelection(SelectionChangedCause.toolbar);
                })
        ];
        return AdaptiveTextSelectionToolbar.buttonItems(
          buttonItems: buttonItems,
          anchors: selectableRegionState.contextMenuAnchors,
        );
      },
    );
  }
}

**Comment by huycozy** [comment]
Thanks for the response but the updated sample code is incomplete and also uses 3rd party package ([extended_text](https://pub.dev/packages/extended_text)). You should try removing/commenting out it to see if the issue persists or not. Please see [Provide reduced test cases](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#provide-reduced-test-cases) and [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) for an ideal sample. 

Please also ensure that all the questions above are clarified to help provide a clearer understanding of the issue.

**Comment by men620** [comment]
@huycozy 
I'm glad to see your reply, but my custom emoji requires ExtendeText for highlighting. Please forgive me for not being very good at Flutter language. Currently, this demo can reproduce the problem. Today, I repositioned it and it feels like it's caused by BoxHeightStyle.max. However, without using BoxHeightStyle.max, the line height of the text is smaller than that of the custom emoji, which will cause this issue. But if BoxHeightStyle.max is not used, the selected emoji will display higher than the text (which is similar to the # 137976 problem)

**Comment by men620** [comment]
@huycozy 
I'm glad to see your reply, but my custom emoji requires ExtendeText for highlighting. Please forgive me for not being very good at Flutter language. Currently, this demo can reproduce the problem. Today, I repositioned it and it feels like it's caused by BoxHeightStyle.max. However, without using BoxHeightStyle.max, the line height of the text is smaller than that of the custom emoji, which will cause this issue. But if BoxHeightStyle.max is not used, the selected emoji will display higher than the text (which is similar to the #137976  problem)

**Comment by men620** [comment]
@huycozy

**Comment by huycozy** [comment]
Let's make sure we understand the same issue first. When you said "misalignment", does that mean the height of highlighted areas of emojis and text are not consistent? (On your screenshot, I don't see that)

I also checked the issue using a minimal code below (without using `extended_text`), and I encountered https://github.com/flutter/flutter/issues/137817:

<details>
<summary>Minimal sample code without 3rd party packages</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [SelectionArea].

void main() => runApp(const SelectionAreaExampleApp());

class SelectionAreaExampleApp extends StatelessWidget {
  const SelectionAreaExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('SelectionArea Sample')),
        body: const Center(
          child: SelectionArea(
            child: Text('天气😀😀😀啊\nemm😀😀唉'),
          ),
        ),
      ),
    );
  }
}
```
</details>

![IMG_4810](https://github.com/user-attachments/assets/229be86b-0ff8-4737-9bbb-f24339517db0)

Please confirm if this is or is not the issue you are reporting. If it is, you should follow https://github.com/flutter/flutter/issues/137817 and I will close this issue in favor of that one.

Otherwise, please add more information to understand the issue better. If the issue only occurs when using `extended_text`, I would suggest you file an issue on the dedicated [repository](https://github.com/fluttercandies/extended_text/issues) first then come back here once you have more information. Thanks!

**Comment by men620** [comment]
@huycozy 
Thank you for your answer, but the emojis in your demo are text emojis, while my emojis are customized. Each emoji is an ImageSpan converted to a WidghtSpan, which you can understand as each emoji being an ImageSpan
