### ISSUE TITLE
[video_player]

### ISSUE THREAD

**Issue by locooo** [flutter/flutter#157150]
### Steps to reproduce

I use the sliding distance of 'ScrollController' to calculate the time the video needs to jump to in real time. Although I set real-time seekTo in 'value.addListener', on Android, the video will not actually jump until the scroll view corresponding to the 'ScrollController' stops. And the later the 'seekTo' time is, the longer it takes. These problems only occur on Android.

### Expected results

on Android, the video will not actually jump until the scroll view corresponding to the 'ScrollController' stops. And the later the 'seekTo' time is, the longer it takes. These problems only occur on Android.

### Actual results

on Android, the video will not actually jump until the scroll view corresponding to the 'ScrollController' stops. And the later the 'seekTo' time is, the longer it takes. These problems only occur on Android.

### Code sample

<details open><summary>Code sample</summary>

```dart
  bottomScrollController.value.addListener(() async {
  
        debugPrint("手动滑动");
        await firstVideoPlayerController.value?.pause();

        currentPlaySate.value = false; //当前播放状态为停止

        var totalTimeMicroseconds =
            firstVideoAllTime.value.toDouble(); // 12,000,000 微秒
        var totalWidth =
            bottomItemWidth * bottomFirstVideoFramesIndex.length; // 100 像素

        // 计算每个像素代表的时间
        double timePerPixel = totalTimeMicroseconds / totalWidth;

        // 示例：计算特定距离的时间
        double distance =
            bottomScrollController.value.offset; // 假设我们要计算距离为 50 像素)
        double timeAtDistance = timePerPixel * distance;
        if (timeAtDistance < 0) {
          timeAtDistance = 0;
        }
        if (timeAtDistance > totalTimeMicroseconds) {
          timeAtDistance = totalTimeMicroseconds;
        }

        var dur = Duration(microseconds: timeAtDistance.round());
        firstVideoPlayerController.value!.seekTo(dur);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @locooo, the code sample you have provided is not complete. Please provide a complete minimal reproducible code sample without any third-party packages so that we can properly investigate this. 

Please also provide the following 
- The version of `video_player` & `video_player_android` you're using 
- The output of `flutter doctor -v`

Your issue title is also not complete. Please update it to accurately reflect what the issue is. 

Thank you
