### ISSUE TITLE
[Impeller] Render bug canvas.drawImageRect when src param is bigger than image

### ISSUE THREAD

**Issue by rokarnus** [flutter/flutter#157167]
### Steps to reproduce

Download a jpg image and put it in pubspec.yaml as an asset. This sample uses free image from https://www.pexels.com/photo/clear-glass-cup-filled-with-chocolate-cream-1684880/ in Medium size.

Then run the code sample with and without impeller. When the "Rect src" parameter for canvas.drawImageRect is bigger than the actual image a stretched image bug appears with impeller. But not with Skia.

The screenshots are from Android. The same happens on iOS.

### Expected results

Should draw the image without "stretched" render bug.
![Screenshot_20241018-175002](https://github.com/user-attachments/assets/4589146b-d624-4832-ac34-addd247a5bf8)

### Actual results

Draws the image with "stretched" render bug.
![Screenshot_20241018-174935](https://github.com/user-attachments/assets/b44df50a-4289-4be8-9308-4c285e0a3097)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'package:flutter/services.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  ui.Image? loadedImage;

  @override
  void initState() {
    super.initState();

    //load image
    _loadImage();
  }

  Future<void> _loadImage() async {
    String imagePath = 'assets/chocolate-cream.jpg';
    loadedImage = await _loadImageFromAssets(imagePath);
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: _getBody(),
      ),
    );
  }

  Widget _getBody() {
    if (loadedImage == null) {
      return const Center(
        child: Text('Loading ...'),
      );
    } else {
      return CustomPaint(
        painter: MyCustomPainter(loadedImage: loadedImage!),
        child: Container(),
      );
    }
  }
}

class MyCustomPainter extends CustomPainter {
  final ui.Image loadedImage;

  MyCustomPainter({super.repaint, required this.loadedImage});

  @override
  void paint(Canvas canvas, Size size) {
    //get the center of the screen
    ui.Offset centerOffset = Offset(size.width / 2.0, size.height / 2.0);

    //store original imageSize
    Size imageSize =
        Size(loadedImage.width.toDouble(), loadedImage.height.toDouble());

    //The Rect src is intentionally bigger than image dimensions.
    //This causes the render bug on impeller.
    Rect src =
        Rect.fromLTWH(0, 0, imageSize.width * 1.3, imageSize.height * 1.3);

    //this 200x200 rect should fit on most screens.
    Rect dst = Rect.fromCenter(center: centerOffset, width: 200, height: 200);

    canvas.drawImageRect(loadedImage, src, dst, Paint());
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}

Future<ui.Image?> _loadImageFromAssets(String path) async {
  try {
    final ByteData data = await rootBundle.load(path);

    final List<int> bytes = data.buffer.asUint8List();
    final Completer<ui.Image> completer = Completer();
    ui.decodeImageFromList(Uint8List.fromList(bytes), (image) {
      completer.complete(image);
    });

    return completer.future;
  } catch (e) {
    // If asset loading fails, return null
    return null;
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-SI)
    • Flutter version 3.24.3 on channel stable at C:\Users\Rok\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Rok\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at C:\Users\Rok\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • Pixel 8 (mobile)  • 37261FDJH00C99 • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 129.0.6668.103
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 125.0.2535.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @rokarnus 
Can you switch to latest master and re-run your scenario ? 
I did the same and observed that with and without impeller, the image is rendered properly. See below:
First is with impeller, other is without it.

<img width="288" alt="Screenshot 2024-10-21 at 12 29 36 PM" src="https://github.com/user-attachments/assets/fe05a3e2-5451-45d6-b2ec-5e33a22dc5ce">


<img width="284" alt="Screenshot 2024-10-21 at 12 29 28 PM" src="https://github.com/user-attachments/assets/2c924c4a-1806-4e16-b463-b76532e9a606">

**Comment by rokarnus** [comment]
> Thanks for the report @rokarnus Can you switch to latest master and re-run your scenario ? I did the same and observed that with and without impeller, the image is rendered properly. See below: First is with impeller, other is without it.
> 
> <img alt="Screenshot 2024-10-21 at 12 29 36 PM" width="288" src="https://private-user-images.githubusercontent.com/67046386/378307687-fe05a3e2-5451-45d6-b2ec-5e33a22dc5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTEzMjgsIm5iZiI6MTcyOTUxMTAyOCwicGF0aCI6Ii82NzA0NjM4Ni8zNzgzMDc2ODctZmUwNWEzZTItNTQ1MS00NWQ2LWIyZWMtNWUzM2EyMmRjNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDExNDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYWU5OGM0NWI2NTc5OWVkOGI1YjZkYjJiNGQ0NmQyNDc2ZmM3NmEzYjAzYTQ2YjU4NmQ1ZjVhYjIzYTNhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J-qLEHxCM-3qNaUofprR3HUrGrdxX0h2SFOgXvchdjE"> <img alt="Screenshot 2024-10-21 at 12 29 28 PM" width="284" src="https://private-user-images.githubusercontent.com/67046386/378307683-2c924c4a-1806-4e16-b463-b76532e9a606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTEzMjgsIm5iZiI6MTcyOTUxMTAyOCwicGF0aCI6Ii82NzA0NjM4Ni8zNzgzMDc2ODMtMmM5MjRjNGEtMTgwNi00ZTE2LWI0NjMtYjc2NTMyZTlhNjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDExNDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNTZhOThiYjA2NGRiOTYwNDlhZWI3MmVkOGJmZWU5NzI2YjBkN2Y2ZTFmMzExMzVkNTExMThjZWRjMDY5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kr_yVeVnu4rSZMqUqbR-gghwpFwL-pT9GNEhXkDWQDo">

Both images you posted are rendered with the stretched bug. Se my original image, how it should look.

**Comment by darshankawar** [comment]
Thanks for the update. Revisiting the image dimensions and looking at them again, I see what you are saying and reporting. 

```
Stable : 3.24.3
Master : 3.27.0-1.0.pre.120
```
