### ISSUE TITLE
[Flutter test] Support streaming screenshots from tests to IDEs

### ISSUE THREAD

**Issue by johnsonmh** [flutter/flutter#157124]
The testing experience on Flutter would be a lot easier of one could easily visualize the widgets being pumped. 

Generating screenshots from the testing environment seems feasible, it would be nice if we could use these inside of an IDE.

Even better if we could have arrows to tick through screenshots of each call to `pumpWidget`. 

Crude recreation of what I'd want:

![2EnZLHZhFb4](https://user-images.githubusercontent.com/4229329/83304644-37843400-a1cd-11ea-8781-b54b38f5eed9.png)

**Comment by elliette** [comment]
Transferring to Flutter repo from the Flutter DevTools repo.

**Comment by huycozy** [comment]
Looks like the issue needs collaboration of Flutter tool with IDE's plugin/extention teams: https://github.com/flutter/flutter-intellij, https://github.com/Dart-Code/Dart-Code.

@johnsonmh I wonder if this should be implemented in https://github.com/flutter/flutter/issues/51890 first? If it can be done, then we can bring it to IDE's plugin/extention teams next.
