### ISSUE TITLE
OS Error: Access Denied, errno = 5

### ISSUE THREAD

**Issue by tamasbanki** [flutter/flutter#15711]
## Steps to Reproduce
After following the stepps (https://flutter.io/setup-windows/) I created a new project and added a dependence (barcode_scan: "^0.0.3"). When I clicked on the "Packages get" and "Packages upgrade" link I get "Access denied" error messages like:

```
"Running "flutter packages get" in kondi...
Cannot open file, path = '.\.packages' (OS Error: A hozzáférés megtagadva.
, errno = 5)
pub get failed (66)
Process finished with exit code 66"
```

>  *"A hozzáférés megtagadva" in Hungarian means "Access denied".

I moved the project directory to the "C:\" root too, but I've got the same error. It seems the path is O.K., because my non-Flutter Android Studio projects are works great. If I create a new project and i simply run it, it works, but after adding the dependence, it's not work anymore. I have full permission over all folders, but the "flutter" folder in my user folder and my project's folder shows 'read-only' (I can't remove it). If I remove the hidden state of the ".packages" file and I clicked on the "Packages get" it worked once. I also deleted the cache from the "\AppData\Roaming\Pub\" folder, but didn't work... There is no Antivirus Software installed right now (removed because of this).

## Logs

```
## command

flutter run

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'D:\YandexDisk\Projektek\Programozas\AndroidStudioProjects\kondi\.flutter-plugins' (OS Error: A hozzáférés megtagadva.
, errno = 5)

#0      _File.throwIfError (dart:io/file_impl.dart:628)
#1      _File.openSync (dart:io/file_impl.dart:472)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:597)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:621)
#4      _LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:143)
#5      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:89)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:239)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:62)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:278)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///C:/Users/tamas/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## Flutter Doctor

```
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale hu-HU)
    • Flutter version 0.1.5 at C:\Users\tamas\flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\tamas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

**Comment by tamasbanki** [comment]
The problem seems to be solved!
The Flutter is conflicts with the Yandex Disk cloud service. 

"Unable to read files
The app cannot access certain files in the Yandex.Disk folder. This means that the file is either in use by another program or the file name contains invalid (non-Unicode) characters.

Check the program's access rights to your Yandex.Disk folder and the files it contains. Files for syncing can not be in use by another program."
[[https://yandex.com/support/disk/desktop/problems.html](url)]

**Comment by shubham2385** [comment]
I am still getting this issue @tamasbanki

**Comment by ravipatel147** [comment]
I am still facing this issue

**Comment by H03in** [comment]
just remove .flutter-plugins file inside project folder.

**Comment by rami-alloush** [comment]
This answer explains the solution [here](https://stackoverflow.com/a/50589165/4157431)

**Comment by l3lackcurtains** [comment]
Just remove **.flutter-plugins** and **.packages** files.

**Comment by Nico04** [comment]
Personnally, I didn't have any of the files you recommand to delete.
I had to start a new project and copy code inside : it worked.
(It was an old project, unopened for quite long)

**Comment by l3lackcurtains** [comment]
Windows Defender blocked the folder access (Windows 10 new update default setting). Solved the problem by disabling it. Or you can allow the window defender to access the folder after being notified.

**Comment by akatriel** [comment]
@l3lackcurtains Could you elaborate how you discovered that Windows Defender blocked the folder access?

**Comment by l3lackcurtains** [comment]
I got the notification from Window Defender (Didn't show up every time I ran the command, usually after a fresh restart). I follow the notification, and grant access to folder it is asking me for permission. but, It didn't solve the issue so, I thought maybe there are other folders flutter needs permission to and notification is not showing up. So, I disabled the "Controlled Folder Access" setting and it did work.

In case you are struggling to disable Controlled Folder Access in Window Defender:
1. Open "Windows Security"
2. Go to "Virus and Threat Protection"
3. Click on "Virus and Threat Protection Setting > Manage Settings"
4. Click on "Manage Controlled Folder Access"
5. Turn off the switch button.

**Comment by l3lackcurtains** [comment]
@akatriel I got the notification from Window Defender (Didn't show up every time I ran the command, usually after a fresh restart). I follow the notification, and grant access to folder it is asking me for permission. but, It didn't solve the issue so, I thought maybe there are other folders flutter needs permission to and notification is not showing up. So, I disabled the "Controlled Folder Access" setting and it did work.

In case you are struggling to disable Controlled Folder Access in Window Defender:
1. Open "Windows Security"
2. Go to "Virus and Threat Protection"
3. Click on "Virus and Threat Protection Setting > Manage Settings"
4. Click on "Manage Controlled Folder Access"
5. Turn off the switch button.

**Comment by TarchyV** [comment]
I tried all the solutions in the post and am still getting the issue. I don't even have a .flutter-plugins

**Comment by ahmedkubur** [comment]
deleted the .packages file from the project folder worked fine for me

**Comment by abdulmuaz97** [comment]
I solved this issue in case someone is having it..
Firstly I copied the entire content of **pubspec.lock** and then deleted it..
After that I created new file in the same path with the same file name which is **pubspec.lock** and paste the content that I already copied..
run "flutter pub get" and it should absolutely work fine.

**Comment by ChristianEdwardPadilla** [comment]
If your project directory is hidden, for whatever reason, you'll also see this error.

**Comment by mattemartin** [comment]
Hoping this can help others who has the same frustration. The link to the project can't have special characters. I had and # in my path so it broke everything. Could check for special characters in your path TarchyV

**Comment by JohnKinyanjui** [comment]
**I finally  got the solution to fix this**
Fixing this error is actually simple than you think.

https://stackoverflow.com/questions/54233412/flutter-pub-get-failed-66/60717742#60717742
