### ISSUE TITLE
Text size and color issue in OnePlus Android device

### ISSUE THREAD

**Issue by LP-sleep** [flutter/flutter#157155]
### Steps to reproduce

After upgrading to flutter 3.24.3, the font color and size of the app on OnePlus phones have changed. This problem does not occur on other Android devices and Apple devices.

### Expected results

![正常](https://github.com/user-attachments/assets/b20cb76a-4a01-4020-8f29-ac11f253a31a)

### Actual results

![异常](https://github.com/user-attachments/assets/beffbc43-7394-46e5-9114-4dc95ae52d40)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

➜  ~ flutter doctor

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ The Google Privacy Policy describes how data is handled in this service.   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/to/crash-reporting                                     ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ║                                                                            ║
  ║ To disable animations in this tool, use                                    ║
  ║ 'flutter config --no-cli-animations'.                                      ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.1 23B2073 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.94.2)
[✓] Network resources

**Comment by LP-sleep** [comment]
Flutter 3.19.3 is upgraded to flutter 3.24.3. Please help confirm whether it is an official bug. If so, please fix it as soon as possible. Thank you.

**Comment by taosimple** [comment]
Also occurs in my Android device Realme. The Chinese font weight is changed too light.
Before upgrade:
<img width="311" alt="image" src="https://github.com/user-attachments/assets/4f489151-e4e7-4a80-9942-98d9461c8bf2">

After upgrade:
<img width="312" alt="image" src="https://github.com/user-attachments/assets/c65845d8-c504-4a14-8f65-ad5385d9a333">

**Comment by soone** [comment]
I also encountered the same problem.
