### ISSUE TITLE
Firestore auto_id name generation should mimic Firestore iOS behavior

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#15715]
We should follow the behavior of the Firestore iOS SDK instead of the RTDB behavior.

https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/core/src/firebase/firestore/util/autoid.cc

**Comment by KevinTheGray** [comment]
@collinjackson @zoechi I believe this can be closed now with flutter/plugins#1907 being merged in.  Thanks

**Comment by collinjackson** [comment]
Yep! Thank you.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/881. Any further collaboration will be done there.
