### ISSUE TITLE
WidgetStateProperty Animation

### ISSUE THREAD

**Issue by heyarny** [flutter/flutter#157117]
### Use case

I would like to animate the style changes set via WidgetStateProperty.
But as of now I don't see an easy way as it was with simple properties.

### Proposal

It would be nice to extend the use of animationDuration to more properties.

```
  Color getIconBackgroundColor(Set<WidgetState> states) {
    const Set<WidgetState> interactiveStates = <WidgetState>{
      WidgetState.pressed
    };
    if (states.any(interactiveStates.contains)) {
      return Colors.red;
    }
    return Colors.transparent;
  }

...

 IconButton(
    style: ButtonStyle(
      animationDuration: Duration(microseconds: 500),
      backgroundColor: WidgetStateProperty.resolveWith(getIconBackgroundColor)),
    icon: Icon(...),
    onPressed: () {},
  ),
```

Or maybe even have another way to define an animationStyle or something.

**Comment by darshankawar** [comment]
@heyarny 
Can you take a look at [this](https://github.com/flutter/flutter/issues/146042) issue to see if it helps in your case or not ?
