### ISSUE TITLE
Flutter version puzzle 

### ISSUE THREAD

**Issue by eiffelqiu** [flutter/flutter#15724]
when i run 'flutter doctor', it always download the latest 2.0.0-edge dart-sdk， and "Building flutter tool.." process always fails and retry repeatly because of version problem.

it output log like this 

===============================================
Package flutter_tools requires SDK version >=1.19.0 <2.0.0 but the current SDK is 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0.
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...

**Comment by eiffelqiu** [comment]
BTW， this occurs in every branch: dev, beta, master branch

**Comment by zoechi** [comment]
dup of #15014 ?

**Comment by eiffelqiu** [comment]
to zoechi : 

 definitely not dup of #15014 
1: i use Mac to install flutter, did not have any issues related to windows.  
2: It seems that flutter_tools requires SDK version >=1.19.0 <2.0.0 , but when you first run 'flutter doctor' on shell,  it will download the latest dart-sdk, which is alwasy the version above 2.0.0, it the upgrade process never work.

**Comment by Hixie** [comment]
Can you try running `git clean -xffd` in the root of your repository, then `git checkout master`, then `git pull --rebase`, then trying again?

Any idea how you ended up in this state? We're not at all sure how to reproduce this.

**Comment by eiffelqiu** [comment]
to Hixie:  

I tried your method, but with no luck.  I follow your link:  https://github.com/flutter/flutter/wiki/Using-Flutter-in-China .  test in dev, beta, master branch， all have the version problem.

error:
================
➜  flutter git:(master) flutter
Downloading Dart SDK from Flutter engine 6280adbfb1f9f63cdc6179b9b78634add1e4f2e3...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.6M  100 44.6M    0     0  22.1M      0  0:00:02  0:00:02 --:--:-- 22.1M
Building flutter tool...
Package flutter_tools requires SDK version >=1.19.0 <2.0.0 but the current SDK is 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0.
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
Package flutter_tools requires SDK version >=1.19.0 <2.0.0 but the current SDK is 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0.
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
Package flutter_tools requires SDK version >=1.19.0 <2.0.0 but the current SDK is 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0.
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
Package flutter_tools requires SDK version >=1.19.0 <2.0.0 but the current SDK is 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0.
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
Package flutter_tools requires SDK version >=1.19.0 <2.0.0 but the current SDK is 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0.
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
Package flutter_tools requires SDK version >=1.19.0 <2.0.0 but the current SDK is 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0.
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...

It seems that when i first run 'flutter' command, it will download the latest dart-sdk to its cache folder, but the latest Dart-SDK is to new(version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0) to upgrade flutter tool, it require SDK version >=1.19.0 <2.0.0 .  is there a way i can bypass the sdk download process,  so i can use dart installed with homebrew.

**Comment by Hixie** [comment]
Is it possible that you have a version of flutter on your path that isn't the same as the one you're trying to upgrade, or something?

We use our own version of Dart (compiled specifically for Flutter) so there shouldn't be any need to use the homebrew version. Maybe they are conflicting somehow? Though I don't see how that would happen.

Does this happen if you use one of our prebuilt archives now available on flutter.io?

**Comment by Hixie** [comment]
I'm going to close this since we haven't heard back from you, but please don't hesitate to open a new bug if you still see this. Thanks!
