### ISSUE TITLE
Can't running on iOS devices when start on Android Studio but running on XCode

### ISSUE THREAD

**Issue by phamthanh1003** [flutter/flutter#157259]
### Steps to reproduce

I have issues for running project on Devices iOS. It's working when run with Xcode but throw an issues when run with Android Studio.
This is my Flutter Doctor: 
[✓] Flutter (Channel master, 3.25.0-1.0.pre.9, on macOS 15.0.1 24A348
    darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.94.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
MacOS Sequoia v 15.0.1
Xcode: 16.0
Android Studio: Android Studio Jellyfish | 2023.3.1 Patch 1

### Expected results

- Running with Android Studio for hot reload,....

### Actual results

```console
ProcessException: Process exited abnormally with exit code 1:
_LSOpenURLsWithCompletionHandler() failed for the application /Users/Downloads/Xcode.app with error -10664 for the file /Users/Downloads/appFlutter/ios/Runner.xcworkspace.
  Command: open -a /Users/Downloads/Xcode.app -g -j -F /Users/Downloads/appFlutter/ios/Runner.xcworkspace
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:389:19)
<asynchronous suspension>
#2      XcodeDebug._openProjectInXcode (package:flutter_tools/src/ios/xcode_debug.dart:315:7)
<asynchronous suspension>
#3      XcodeDebug.debugApp (package:flutter_tools/src/ios/xcode_debug.dart:66:31)
<asynchronous suspension>
#4      IOSDevice._startAppOnCoreDevice (package:flutter_tools/src/ios/devices.dart:953:33)
<asynchronous suspension>
#5      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:547:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:470:33)
<asynchronous suspension>
#7      HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart:425:14)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:456:34)
<asynchronous suspension>
#10     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:809:9)
<asynchronous suspension>
#11     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:807:5)
<asynchronous suspension>
#12     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:754:15)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1432:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#19     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Could not run build/ios/iphoneos/Runner.app on 00008110-000A25DE2EC2401E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Test iPhone.
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
This looks like a macOS environment issue. Can you try attempt to execute this command from Terminal to see if the same error occurs?

```console
open -a /Users/Downloads/Xcode.app -g -j -F /Users/Downloads/appFlutter/ios/Runner.xcworkspace
```

**Comment by phamthanh1003** [comment]
@huycozy i execute this command and still throw error.
_LSOpenURLsWithCompletionHandler() failed for the application /Users/Downloads/Xcode.app with error -10664 for the file /Users/Downloads/appFlutter/ios/Runner.xcworkspace.

**Comment by huycozy** [comment]
I noticed that your XCode app is on `Downloads` directory. Can you try moving/copying XCode app to `Applications` and retry? 

If this solution does not work, please check the following:
- Does this issue happen on a newly create Flutter project?
- Please provide the entire output of `flutter run -v` [^1] and `flutter doctor -v`. Thank you!

[^1]:The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it.
