### ISSUE TITLE
Add manually notify function in ValueNotifier.

### ISSUE THREAD

**Issue by TheinThanHlan** [flutter/flutter#157262]
### Use case

Manually notifying function in ValueNotifier.
ie:  valueNotifierInstance.valueChanged()

### Proposal

I am using ValueListenableBuilder in flutter. 
I think adding a function in ValueNotifier to manually notify the value change to its subscribers instead of reassigning new object every time , will save my memory.

```dart
ValueNotifier<int,Employee> employeesNoti=ValueNotifier({});

void updateEmployee(int id,String name) {

    employeesNoti.value[id].name=name;

    employeesNoti.valueChanged();

}
```

**Comment by huycozy** [comment]
This is more sufficient for a specific implementation than adding a generic function to ValueNotifier. You can override ValueNotifier and add any methods you want, for eg:

```dart
class AppValueNotifier extends ValueNotifier<int> {
  AppValueNotifier(int value) : super(value);

  void valueChanged() {
    value++;
    notifyListeners();
  }

  void resetValue() {
    value = 0;
    notifyListeners();
  }
}
```

I am closing the issue as explained. If you disagree, please provide more information, and I will reopen this.

**Comment by TheinThanHlan** [comment]
What is the reason that the flutter team decided to make notifyListeners() private?

**Comment by TheinThanHlan** [comment]
I think creating new class for +1 and -1 is too many step for a small operation.
