### ISSUE TITLE
Consider shifting Linux mac_clangd to the "standalone" recipe

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#157275]
It looks like `Linux mac_clangd` doesn't need the full power of the `engine_v2/engine_v2` recipe, and could be shifted to the `engine_v2/builder` recipe. It looks like this is already what `Linux clangd` does. https://github.com/flutter/engine/blob/1a8ef6e24fc6846ae1fd02cfdfcee4818688f7a4/.ci.yaml#L406.

cc @matanlurey @jmagman

**Comment by jmagman** [comment]
+1 this would be an example of https://github.com/flutter/flutter/issues/155041.

This should be pretty easy, here's the Linux clangd one I moved: https://github.com/flutter/engine/pull/55186

https://github.com/flutter/engine/blob/5eb21d2706c0228ff16fed08857ef1d4dbb7da5c/ci/builders/mac_unopt_debug_no_rbe.json

**Comment by jmagman** [comment]
You sniped me @zanderso  https://github.com/flutter/engine/pull/56014
