### ISSUE TITLE
[web] Compressed size regression on "Support woff2 fonts"

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#157287]
See

https://flutter-flutter-perf.skia.org/e/?keys=Xf055046cc5ae7c850bec058174ad56e8&selected=commit%3D43007%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dflutter_gallery_web_build_dir_compressed_bytes%252Ctest%253Dweb_size__compile_test%252C&xbaroffset=43007

Not sure if expected or not. @yjbanov @mdebbar

**Comment by mdebbar** [comment]
Thanks for alerting us, @jonahwilliams!

This is expected. We added the Brotli dependency to our CanvasKit build to be able to decode woff2 fonts.
