### ISSUE TITLE
Cursor Moves in Wrong Direction in RTL TextField on Flutter Web

### ISSUE THREAD

**Issue by Aminadav** [flutter/flutter#157232]
### Steps to reproduce

1. *Set up a Flutter Web project:*

Create a new Flutter Web project using flutter create.
Ensure that your environment is set up to run web builds (flutter build web or flutter run -d chrome).
Create a TextField in RTL mode:

In your Flutter app, add a TextField widget inside a Directionality widget.
Set the textDirection of the Directionality widget to TextDirection.rtl.

2. Run the app:

*Run the app on a web platform (e.g., Chrome).*
Test the TextField:

3. Focus on the TextField by clicking inside it.
Type some text in an RTL language (or in any language) to ensure there's content. such as: `שלום`
Press the left and right arrow keys:

*Press the left arrow key on your keyboard and observe the cursor movement.*
*Press the right arrow key on your keyboard and observe the cursor movement again.*

### Expected results

- Pressing the left arrow key should move the cursor to the left.
- Pressing the right arrow key should move the cursor to the right.

### Actual results

- The cursor moves in the opposite direction (left key moves the cursor right, right key moves it left), which is incorrect for RTL text input.

### Code sample

<details open><summary>Code sample</summary>

```dart
Directionality(
  textDirection: TextDirection.rtl,
  child: TextField(),
)
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.24.1, on macOS 14.7 23H124 darwin-arm64, locale en-IL)
    ! Flutter version 3.24.1 on channel [user-branch] at /Users/ag/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Warning: `flutter` on your path resolves to /Users/ag/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at
      /Users/ag/flutter. Consider adding /Users/ag/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/ag/flutter/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/ag/flutter. Consider adding /Users/agflutter/bin to the front of your path.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.94.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Aminadav iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category
```
</details>

**Comment by huycozy** [comment]
Thanks for the report. However, there is a similar issue at https://github.com/flutter/flutter/issues/78660. Closing this to concentrate on that one.
