### ISSUE TITLE
Cannot initialize flutter run, failure on gradle - on unzipping gradle.wrapper

### ISSUE THREAD

**Issue by doctormellow** [flutter/flutter#15721]
## Steps to Reproduce

Error using flutter run
Using iMac on High Sierra (running with Visual Studio Code).
Following the flutter guide for the random words project
I was able to get it to work with my windows 10 laptop.
I have the Java SDK downloaded, I have removed the gradle file and then re-downloaded 
as per https://github.com/NativeScript/NativeScript/issues/3930 

```
Error executing simctl: -6
dyld: Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
Reason: image not found
Initializing gradle...                                   /
Oops; flutter has exited unexpectedly: "Exit code 1 from: /Projects/Coding/flutterProjects/myapp01/android/gradlew -v:
Unzipping /var/root/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1-all.zip to /var/root/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)".

Sending crash report to Google.
Crash report sent (report ID: ea0ef7b98c6b296d)
Crash report written to /Projects/Coding/flutterProjects/myapp01/flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
```
After removing gradle, I reinstalled it and was given this error message

```
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar'.
         > SSL peer shut down incorrectly
```

It's stuck on initializing gradle, though I am on slow internet speeds --> does that affect the rate of initializing gradle? 

## Flutter Doctor
Passed. No issues detected.

**Comment by Hixie** [comment]
Presumably the gradle wrapper is failing to notice that the download failed, and then tries to unzip it?

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by dnfield** [comment]
I just ran in to this and it was 100% due to internet connectivity issues (zip file was corrupt/incomplete due to spotty connection, gradle tried to unzip it and failed, spat out this error).

I resolved it by removing my `$HOME/.gradle/wrapper/dist` directory and retrying after my internet connection was restored.

It is very likely due to your internet connection being so slow as to time out or spotty and not being able to establish a reliable connection.

**Comment by zhangzhenxi** [comment]
So, why not give us a config for which gradle should be use (wrapper or local distributions) ? 
Just like this :
![image](https://user-images.githubusercontent.com/7889171/42312122-1dcd0db2-8072-11e8-813e-f658ff544d81.png)

Cause you know, some time network issues in China is painful.

**Comment by dnfield** [comment]
You can do that manually by editing the file in `android/gradle/wrapper/gradle-wrapper.properties`.  It should look something like this:

```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

You can change it to 

```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=gradle-4.1-all.zip
```

Which would have it look for `gradle-4.1-all.zip` in that same folder.  Note you should be using at least Gradle 4.1 for this project - I don't think 3.3 would work.  See https://stackoverflow.com/questions/22896569/how-to-use-gradle-zip-in-local-system-without-downloading-when-using-gradle-wrap for some more examples.

**Comment by zhangzhenxi** [comment]
I'm totally sure that runs good for ONCE. But not the best for the REST.

**Comment by zhou3q** [comment]
The reason:Net is to slow...
Modifty the gradle/gradle-wrapper.properties

Windows:
distributionUrl=file\:/d:/gradle-xxx-all.zip

Linux:
distributionUrl=file\:/tmp/gradle-xxx-all.zip

**Comment by zoechi** [comment]
Closing as dup of #13645
Please upvote and follow there
