### ISSUE TITLE
Android Studio "New Flutter Project" AndroidManifest.xml errors.

### ISSUE THREAD

**Issue by gitspeak** [flutter/flutter#15722]
<img width="715" alt="1" src="https://user-images.githubusercontent.com/37540903/37630030-c99ca0b2-2bea-11e8-8391-59b8384276b0.png">

<img width="887" alt="2" src="https://user-images.githubusercontent.com/37540903/37630040-d7e2fe50-2bea-11e8-9d7a-2a8503eef3a9.png">

<img width="832" alt="3" src="https://user-images.githubusercontent.com/37540903/37630045-dd2e5d5a-2bea-11e8-8e27-328502089d8a.png">

jumbo ~/AndroidStudioProjects/startup_namer $ flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-IL)
• Flutter version 0.1.5 at /usr/local/flutter
• Framework revision 3ea4d06 (4 weeks ago), 2018-02-22 11:12:39 -0800
• Engine revision ead227f
• Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
• Android SDK at /Users/jumbo/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-27, build-tools 27.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 9.2, Build version 9C40b
• ios-deploy 1.9.2
• CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (2 available)
• GT I9500 • <REMOVED: DON'T KNOW IF THIS SHOULD BE CONSIDERED PRIVATE> • android-arm • Android 5.0.1 (API 21)
• iPhone 8 • <REMOVED: DON'T KNOW IF THIS SHOULD BE CONSIDERED PRIVATE> • ios • iOS 11.2 (simulator)

• No issues found!

**Comment by Hixie** [comment]
Can you elaborate?

**Comment by gitspeak** [comment]
Please tell me what else you want me to check.. The issue is visible in the screenshots attached (red highlighted references)

**Comment by Hixie** [comment]
What are the errors? I don't think the red text means errors, I think that's just the highlighting that Android Studio uses for files that don't exist? The idea is that you can add those files if you want, but don't have to, if I remember correctly.

**Comment by Hixie** [comment]
Oops, bot got a bit excited there.

@gitspeak: can you explain it? I don't see any errors in the screenshots.

**Comment by zoechi** [comment]
You probable need to adjust the Java SDK settings in AS modul config.

**Comment by eduardhasanaj2** [comment]
I tried but there is no option. I went to Android View and project pluginname_android doesn't have a Open Module Settings. Here I added android code implementation.

**Comment by zoechi** [comment]
I think it was


Menu > File > Project Structure > Modules > (Flutter Android project) > Language level

perhaps also 

Menu > File > Project Structure > Platform Settings > SDKs > 1.8 

I played around there some months ago and got rid of lots of warnings but don't remember details.

**Comment by eduardhasanaj2** [comment]
i have it 1.8 but the problem is min API version. current is 0. Please see photos above. I tried to config min sdk in gradle but nothing.

**Comment by zoechi** [comment]
What is the "Java SDK: version" in

![image](https://user-images.githubusercontent.com/405837/44530102-f9034080-a6ed-11e8-9de2-cacd41151c0b.png)

**Comment by eduardhasanaj2** [comment]
it is 1.8. The warnings that I see are because of min SDK API. mine is 0

**Comment by chaitanyabhardwaj** [comment]
@eduardhasanaj2  I've got a similar problem. In app/build.gradle -

`minSdkVersion 16`
`targetSdkVersion 28`

But I'm getting error in AndroidManifest.xml - 
`android:hardwareAccelerated="true"`
error - _Attribute hardwareAccelerated is only used in api level 11 and higher(current min is 1)_

Did you find any solution?)

**Comment by chankruze** [comment]
I am also having these issues.I formatted my pc and re installed everything.And the new project (the default one)is also not building.
I was planning for a release build but here debug build is in vain.
I can see these as Errors in verbose mode as below:
```
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: package="com.gookofia.tinyurl" (Raw: "com.gookofia.tinyurl")
               A: platformBuildVersionCode=(type 0x10)0x1
               A: platformBuildVersionName="1.0.0" (Raw: "1.0.0")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1b
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=24)
                 A: android:label(0x01010001)="tinyurl" (Raw: "tinyurl")
                 A: android:icon(0x01010002)=@0x7f020000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 E: activity (line=29)
                   A: android:theme(0x01010000)=@0x7f030000
                   A: android:name(0x01010003)="com.gookofia.tinyurl.MainActivity" (Raw: "com.gookofia.tinyurl.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400035b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=43)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw:
                     "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=47)
                     E: action (line=48)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=50)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
```

**Comment by zoechi** [comment]
@chankruze 

> And the new project (the default one)is also not building.

what exactly do you mean by that?
Did you just create a new project with `flutter create foo` and `cd foo` `flutter build apk` to produce the error output?

**Comment by chankruze** [comment]
Yeh i tried 2 times,and got error output with stable not beta.

**Comment by zoechi** [comment]
@chankruze that means it's fixed already and only needs to roll into stable.

**Comment by naguchennai** [comment]
Yes i am also having same problem 
Cannot resolve symbol '@mipmap/ic_launcher' 
Cannot resolve symbol '@style/LaunchTheme'
Cannot resolve symbol '@drawable/launch_background' 
Cannot resolve symbol '@style/NormalTheme' 
Unresolved package 'audioservice'

**Comment by csabag** [comment]
I had a similar problem and this is what fixed it for me:
https://github.com/flutter/flutter/issues/56686#issuecomment-626113298
