### ISSUE TITLE
Flutter NFC: Host Card Emulation

### ISSUE THREAD

**Issue by EINS-SD-MOHAMMED** [flutter/flutter#157398]
### Use case

Use Case: HCE Communication Between Mobile App and NFC Device
Description:
A Flutter app acts as a virtual access card, designed to receive and respond to commands sent by an NFC device.

Actors:
User: Individual using the app for access.
NFC Device: Hardware that communicates with the mobile app.
Mobile App: Flutter application emulating the access card.
Preconditions:
The user has the Flutter app installed on their NFC-enabled device.
Flow of Events:
NFC Detection:

The NFC device detects the smartphone and establishes NFC communication.
Command Transmission:

The NFC device sends a command to the mobile app (e.g., to select an application).
The mobile app receives the command and processes it accordingly.
Response Handling:

The mobile app sends back an appropriate response to the NFC device, confirming receipt or providing requested information.
Continued Communication:

The NFC device may send additional commands (e.g., read mobile identifier, initiate authentication).
The mobile app continues to receive and respond to each command.
Postconditions:
The mobile app successfully receives and processes commands from the NFC device.
Benefits:
Real-time Interaction: Enables seamless communication between the app and NFC device.
Enhanced Security: The app can manage secure responses based on commands received.

The package available on pub.dev (nfc_host_card_emulation) do not resolve the issue, as they continuously send the old value from the NFC device, even when the device is transmitting new data alongside the old data.

### Proposal

An HCE feature package on pub.dev will provide comprehensive solutions to effectively manage NFC communication, ensuring accurate and timely data reception from NFC devices.

**Comment by danagbemava-nc** [comment]
The flutter team has no plans to maintain an NFC plugin. If there's an existing package that doesn't work as expected, kindly report it on their repo so that it can be properly addressed. 

Closing from here as the team has no plans to maintain this type of plugin. 

Thank you
