### ISSUE TITLE
Make slider widget with divisions more responsive

### ISSUE THREAD

**Issue by MiroKeimioniemi** [flutter/flutter#157375]
### Use case

Every time I have used the slider widget with divisions, I have wondered why it lags behind as compared to a slider without division.  My latest use case was to create a permanently visible custom value indicator as a separate widget and sync it to the current position of the discrete slider but it constantly lagged behind the thumb when sliding further. 

I learned from other people who have faced a similar issue that this is actually hardcoded in as a delay of 75 milliseconds as _positionAnimationDuration. Modifiying the source code so as to remove this solved the issue for me and achieved perfect synchronization. 

### Proposal

I propose to make positionAnimationDuration into a parameter of the Slider widget or the SliderTheme so that developers gain control over it directly.

**Comment by huycozy** [comment]
Hi @MiroKeimioniemi, this is a known issue at https://github.com/flutter/flutter/issues/51715. Closing this in favor of that one, so please follow it.
