### ISSUE TITLE
window.history.state freezes after restarting the browser when using initialLocation (address bar doesn't change for new routes)

### ISSUE THREAD

**Issue by mErrenst** [flutter/flutter#157334]
### Steps to reproduce

This will only happen when you set an **initialLocation** for GoRouter, in our case to keep the last location the user visited.
It sometimes needs many tries until it's reproducible so might just happen random. It seems that something is breaking the window.history.state so it doesn't get updated anymore.
1. Open several routes in a row by clicking through many widgets.
2. Restart the browser.
3. Try to open a different route and look at the address bar. For me the URL in the address bar doesn't change anymore although I can still open different pages. Neither using the Navigator nor GoRouter will update that.

When this happens, neither Navigator nor GoRouter can update the window.location anymore.
I have found a workaround for this, in case someone has the same problem and needs to solve it somehow, just call this on web app start:
```
window.history.pushState(
  {
    'serialCount': 0,
  },
  initialLocation, // replace with what you want as initialLocation
  null,
);
```

### Expected results

URL in the address bar should change when I go to different routes.

### Actual results

After clicking through several pages and then restarting the browser, the URL in the address bar doesn't change anymore (only when initialLocation is set).

### Code sample

To be honest I wasn't able to reproduce this in a small sample app. Even for the app that I work on in my job I can sometimes only reproduce it after some tries.

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 22.04.5 LTS 6.8.0-45-generic, locale de_DE.UTF-8)
    • Flutter version 3.24.3 on channel stable at /home/malin/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (vor 6 Wochen), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/malin/AndroidSDK
    • Platform android-34, build-tools 30.0.3
    • ANDROID_HOME = /home/malin/AndroidSDK
    • ANDROID_SDK_ROOT = /home/malin/AndroidSDK
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 76.3.1
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.94.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • SM G970F (mobile) • RF8M22KPTEE • android-arm64  • Android 12 (API 31)
    • Linux (desktop)   • linux       • linux-x64      • Ubuntu 22.04.5 LTS 6.8.0-45-generic
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 130.0.6723.58

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @mErrenst 

>Restart the browser.

Do you mean to close and reopen browser? Can you provide more specific `steps to reproduce` along with a `complete and minimal sample code` so that I can verify this issue on my end? And a demo video would be appreciated. Thanks!

**Comment by mErrenst** [comment]
@huycozy I mean close (all windows of the browser) and reopen the browser.
And I'm really sorry but I tried to reproduce it in a minimal sample app but wasn't able to. Probably this only happens in more complex apps.

What I can provide is our GoRouter config:
```
GoRouter(
      navigatorKey: goRouterNavigatorKey,
      observers: [
        SentryNavigatorObserver(),
      ],
      initialLocation: SplashScreen.initialRoute,
      refreshListenable: StreamListenable(client.onLoginStateChanged.stream),
      redirect: rootRedirector,
      routes: [
        GoRoute(
          path: '/',
          redirect: rootRedirector,
          routes: columnMode ? _tabletRoutes : _mobileRoutes,
        ),
        ..._homeRoutes,
      ],
      debugLogDiagnostics: true,
    );
```

I already tried to strip off all config except for the initialLocation which is set in a widget.
When this happens, it will happen again even when just refreshing the page until I remove the complete route from the URL in the addressbar (just leaving the domain) or call window.history.pushState(). If I remove just parts of the route and press enter it works again until reload or restart.
[Bildschirmaufzeichnung vom 22.10.2024, 13:27:33.webm](https://github.com/user-attachments/assets/ca8423dc-eceb-4b3f-8dd0-c47bf629bf48)

**Comment by huycozy** [comment]
Thanks for your update. Maybe this is related to logic inside your redirection `rootRedirector`? 

Without a minimal sample code or consistent steps, the issue unfortunately is unactionable. For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please try to narrow the project code down until you see a pattern to reproduce the issue consistently. Please also check [Provide reduced test cases](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#provide-reduced-test-cases), thank you!

**Comment by maRci002** [comment]
Maybe #132464 is related since GoRouter doesn't correctly recognize the initial state
