### ISSUE TITLE
type '_Future' is not a subtype of type 'VoidCallback' of 'onPressed' where

### ISSUE THREAD

**Issue by shyjuzz** [flutter/flutter#15739]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by mraleph** [comment]
You are passing `Future` somewhere where a function is expected. Please share the snippet of the code - otherwise we can't assist you with that.

**Comment by zoechi** [comment]
Probably a case of
```dart
onTap: someFunc() // invalid
```
instead of

```dart
onTap: () => someFunc() // ok
```
or
```dart
onTap: someFunc // ok
```

**Comment by zoechi** [comment]
probably a dup of #15740

about code from https://flutter.io/networking/

**Comment by shyjuzz** [comment]
Thanks for the reply. Forgot to remove the parenthesis in the function call.
