### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/android.kindergartens.com-2/base.apk"],nativeLibraryDirectories=[/data/app/android.aa.com-2/lib/arm, /system/fake-libs, /data/app/android.aa.com-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by zhangruiyu** [flutter/flutter#15733]
When I use abiFilters "armeabi-v7a", I found a mistake.
![image](https://user-images.githubusercontent.com/10591822/37636192-a2e747f0-2c3b-11e8-813e-167f0ff9ff4c.png)
![image](https://user-images.githubusercontent.com/10591822/37636263-05ff19ee-2c3c-11e8-83a8-e37ab54e9f3b.png)
![image](https://user-images.githubusercontent.com/10591822/37636268-104d5ffa-2c3c-11e8-90c2-6e96d9cb4238.png)

**Comment by igorwojda** [comment]
Duplicates https://github.com/flutter/flutter/issues/15530

**Comment by swavkulinski** [comment]
It happens when the target (device) doesn't match provided NDK libraries.

**Comment by zoubihai** [comment]
ava.lang.UnsatisfiedLinkError

dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.-FabcS_7QM_yF3XFcLxrhww==/base.apk"],nativeLibraryDirectories=[/data/app/com.-FabcS_7QM_yF3XFcLxrhww==/lib/arm64, /data/app/com.-FabcS_7QM_yF3XFcLxrhww==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"，我的是小米5splus cpu是arm64-v8a
