### ISSUE TITLE
[CP-beta] Allow flavor-conditional assets from package dependencies

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#157308]
### Issue Link

https://github.com/flutter/flutter/issues/155755

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/flutter/pull/157306

### Changelog Description

When declaring an asset within a package dependency to be bundled only in certain flavors of an app, the asset is never bundled.

### Impacted Users

All Flutter for iOS/macOS/Android devs

### Impact Description

Users cannot specify assets from packages to be bundled only when building with a specific `--flavor`. This is probably mostly relevant for users that have larger monorepo projects.

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

Follow the repro steps in the description of https://github.com/flutter/flutter/issues/155755. I'm also happy to demo the feature upon request.

**Comment by reidbaker** [comment]
@andrewkolos can I get you to reformat the change log description to follow these best practices. 

https://github.com/flutter/flutter/blob/master/docs/releases/Hotfix-Documentation-Best-Practices.md

In the past this was something a release engineer would do but we are moving to having cherry pickers do it since they have a better understanding of the change.

**Comment by andrewkolos** [comment]
I've updated the changelog description to match the format in the wiki page. It now just states the issue (that this patch fixes)

**Comment by reidbaker** [comment]
@andrewkolos can I get you to do a second pass. Specifically I am looking at the Changelog Description
"When declaring an asset within a package dependency to be bundled only in certain flavors of an app, the asset is never bundled." In this issue. 

I think you updated the pr message and it also does not have the format we are expecting. 

The key parts of the documentation I shared are 

* Should be clear to a non-contributor who is developing with Flutter
* Should be succinct (one line) for ease of scanning
* Within above, should identify as best as possible:
* * What the scenario is (describe the problem)
* * What platforms it affects
* * In what context it may occur
* * How likely it is to occur

example https://github.com/flutter/flutter/issues/90783: In rare circumstances, engine may crash during app termination on iOS and macOS
