### ISSUE TITLE
Swift Compiler Error (Xcode): 'header Value()' is unavailable in Swift: Use asyncHeaderValue() async -> String? instead.

### ISSUE THREAD

**Issue by noahclark556** [flutter/flutter#157311]
Seeing this issue after updating to most recent of Flutter SDK, Xcode, MacOS, and firebase packages. Temporary fix is listed below for context, not entirely sure whats happening but I do believe it's a genuine issue. This is adjustment to pod file to make it work correctly for the time being.

 ### In root flutter project directory, run: sudo chown -R $(whoami) .

# Adjust pod file post install to contain the bottom portion of this snippet

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
    file_path = 'Pods/FirebaseAuth/FirebaseAuth/Sources/Swift/Backend/AuthBackend.swift'
    text = File.read(file_path)
    new_contents = text.gsub('heartbeatLogger.headerValue()', 'await heartbeatLogger.asyncHeaderValue()')
    File.open(file_path, "w") {|file| file.puts new_contents }
end

**Comment by Peng-Qian** [comment]
This is a known Firebase bug: [issue here](https://github.com/firebase/flutterfire/issues/13527).

A current workaround is to update your Podfile as follows:
```dart
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'FirebaseCoreExtension', '11.3'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by noahclark556** [comment]
This is great, thanks for the info, much more stable than my workaround

**Comment by asropinr** [comment]
+1

**Comment by danagbemava-nc** [comment]
Closing from here as this is a firebase issue. 

Thank you
