### ISSUE TITLE
Scroll to end of scrollview

### ISSUE THREAD

**Issue by kentcb** [flutter/flutter#15730]
## Steps to Reproduce

1. Try and scroll to end of a `ScrollView`, such as `SingleChildScrollView`.
2. Find there is no supporting API
3. Pull hair out trying to work around this

I was expecting some kind of `extent` property on the `ScrollView`, but there is none that I can find. I've seen some advice online to reverse the `ScrollView` and scroll to offset `0.0`, but that results in completely undesirable behavior in my app.

I've since been down the path of obtaining render boxes, using `BuildContext.size` via a global key on the scroll view's child, etc etc. Nothing has given me the correct measurement that I can use to scroll exactly to the end of the scroll view. I've even tried _two_ global keys (despite the guidance to not overuse them) - one against the `ScrollView` and one against its child. I could then calculate `child height - scroll view height`, thinking that would give me the exact amount to scroll by. Well, it still overshoots the end of the scrollview, causing it to snap up after the scroll request.

How does one accurately scroll to the end of a `ScrollView`?

## Logs

N/A

## Flutter Doctor

```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.309], locale en-AU, channel alpha)
    • Flutter version 0.0.22-pre.1 at C:\Users\kent\Repository\flutter
    • Framework revision 553fc4264e (3 weeks ago), 2018-03-01 09:30:25 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)
```

**Comment by xqwzts** [comment]
I believe you can achieve this with a combination of [ScrollController](https://docs.flutter.io/flutter/widgets/ScrollController-class.html)'s movement methods and [ScrollPosition](https://docs.flutter.io/flutter/widgets/ScrollPosition-class.html)'s extent properties:

You'll want to create a new ScrollController and attach it to your ScrollView by passing it in to the [controller](https://docs.flutter.io/flutter/widgets/ScrollView/controller.html) property in ScrollView's constructor.

Now when you want to scroll to the end you can have the controller [animateTo](https://docs.flutter.io/flutter/widgets/ScrollController/animateTo.html) or [jumpTo](https://docs.flutter.io/flutter/widgets/ScrollController/jumpTo.html) the attached ScrollPosition's [which you can get from the controller's [position](https://docs.flutter.io/flutter/widgets/ScrollController/position.html) property] [maxScrollExtent](https://docs.flutter.io/flutter/widgets/ScrollPosition/maxScrollExtent.html).

**Comment by kentcb** [comment]
@xqwzts thanks! That must have been the only place I _didn't_ look 🙃

**Comment by kentcb** [comment]
For the record, I ended up with this code:

```dart
var scrollPosition = _scrollController.position;

if (scrollPosition.viewportDimension < scrollPosition.maxScrollExtent) {
  _scrollController.animateTo(
    scrollPosition.maxScrollExtent,
    duration: new Duration(milliseconds: 200),
    curve: Curves.easeOut,
  );
}
```
I found that if scrolling isn't necessary (because the viewport exceeds the maximum extent), an attempt to scroll to `maxScrollExtent` would scroll past the end of the child widget. Seems like it must be a bug, but separate to my original problem.

**Comment by Nk54** [comment]
@kentcb in landscape mode, it won't work as you expect.

**Comment by yuikns** [comment]
@kentcb Thank you.

However, it seems like the variable `viewportDimension` is a fixed variable if the window does not changed. And the `maxScrollExtent` will increased from 0 to the height ( suppose the `scrollDirection` is `Axis.vertical` ) - `viewportDimension`.

Besides, it will crashed if the widget was not appeared yet.

```
void _scrollToEnd() {
  if (!_scrollController.hasClients) {
    return;
  }

  var scrollPosition = _scrollController.position;

  if (scrollPosition.maxScrollExtent > scrollPosition.minScrollExtent) {
    _scrollController.animateTo(
      scrollPosition.maxScrollExtent,
      duration: new Duration(milliseconds: 200),
      curve: Curves.easeOut,
    );
  }
}
```

Hoping it helps.

**Comment by HeartDawnWY** [comment]
i wan't listview can scroll to end when page open.
but i don't know when exec [_scrollController.animateTo]
who can tell me?

**Comment by Maulik009** [comment]
ListView.builder(
    controller: _scrollController,
    itemCount: list.lenght,
    itemBuilder: (BuildContext ctxt, int index) {
        return Text("GMF ${list[index]}");
    }
)

and after that 

_scrollController.animateTo(_scrollController.position.maxScrollExtent, duration: const Duration(milliseconds: 500), curve: Curves.easeOut);

**Comment by po1arbear** [comment]
> For the record, I ended up with this code:
> 
> ```dart
> var scrollPosition = _scrollController.position;
> 
> if (scrollPosition.viewportDimension < scrollPosition.maxScrollExtent) {
>   _scrollController.animateTo(
>     scrollPosition.maxScrollExtent,
>     duration: new Duration(milliseconds: 200),
>     curve: Curves.easeOut,
>   );
> }
> ```
> 
> I found that if scrolling isn't necessary (because the viewport exceeds the maximum extent), an attempt to scroll to `maxScrollExtent` would scroll past the end of the child widget. Seems like it must be a bug, but separate to my original problem.

My Code like this，so when do I call the method "scrollToEnd"? I don't know what's the lifecycle called after 'build' method.
build(){
Controller controller;
return SingleChildScrollView(
controller:controller
)
}

**Comment by Maulik009** [comment]
Resolved this issue by calling scrollController on top of widget, because in my case widget is dynamic and everytime updated. So, whenever UI will get update, that time it calls scrollcontroller.jumpto() : 

 ` Widget buildListMessage() {
      Timer( Duration(milliseconds: 100), () =>    listScrollController.jumpTo(listScrollController.position.maxScrollExtent));

 return new Expanded(
        child: Container(
      child: ListView.builder(
        shrinkWrap: true,
        itemBuilder: (BuildContext ctxt, int index) {
          return buildColumnItem(index);
        },
        itemCount: mChatRepliesList.length,
        controller: listScrollController,
     
      ),
      margin:
          const EdgeInsets.only(top: 5.0, right: 5.0, left: 10.0, bottom: 1.0),
    ));
  }`

**Comment by sickworm** [comment]
> i wan't listview can scroll to end when page open.
> but i don't know when exec [_scrollController.animateTo]
> who can tell me?


Add it on Widget build(BuildContext context).

```
WidgetsBinding.instance.addPostFrameCallback((_) => _scrollToEnd());
```

And:
```
  _scrollToEnd() async {
    if (_needScroll) {
      _needScroll = false;
      _scrollController.animateTo(_scrollController.position.maxScrollExtent,
          duration: Duration(milliseconds: 400), curve: Curves.ease);
    }
  }
```

**Comment by patelkrunal78** [comment]
Wrap your widget tree inside a SingleChildScrollView

body: SingleChildScrollView(
child: Stack(
children: <Widget>[
new Container(
decoration: BoxDecoration(
image: DecorationImage(...),
new Column(children: [
new Container(...),
new Container(...... ),
new Padding(
child: SizedBox(
child: RaisedButton(..),
),
....
...
); // Single child scroll view

Find At [Here](https://icetutor.com/question/how-to-scroll-page-in-flutter)
