### ISSUE TITLE
Transpaency Issue

### ISSUE THREAD

**Issue by App1309** [flutter/flutter#157342]
### Steps to reproduce

1. Create an app with a bottom navigation bar of at least 4 items.
2. Provide the flutter Google map in any one of the tabs.
3. Run the app on any pixel device(Specifically pixel device).
4. While zooming on any position up to a specific resolution the background becomes transparent
5. while reaching that level the content of the other tab is visible from the map

### Expected results

The actual result should be that the map should not become transparent at a specific zoom level  in pixel devices.

### Actual results

The map becomes transparent after zooming on a map after reaching a specific level.

### Code sample

<details open><summary>Code sample</summary>

```dart

Container(
                  color: AppColors.addButtonBackground,
                  child: GoogleMap(
                    initialCameraPosition: state.initialMapPosition,
                  
                    onMapCreated: (mapController) async {
                      await mapController.setMapStyle(AppMapStyle.styleString);
                      state.store.trophyClusterManager
                          .setMapId(mapController.mapId);
                      state.store.businessPinsClusterManager
                          .setMapId(mapController.mapId);
                      controller.add(MapUpdateControllerEvent(mapController));
                    },
                    compassEnabled: false,
                    onCameraMove: (position) {
                      
                      state.store.trophyClusterManager.onCameraMove(position);
                      state.store.businessPinsClusterManager
                          .onCameraMove(position);
                    },
                    onCameraIdle: () {
                      state.store.trophyClusterManager.updateMap();
                      state.store.businessPinsClusterManager.updateMap();
                    },
                    myLocationButtonEnabled: false,
                    buildingsEnabled: false,
                    trafficEnabled: false,
                    zoomControlsEnabled: false,
                    onTap: (latlng) async {
                      final zoom = await state.controller?.getZoomLevel();
                      if (context.mounted &&
                          !showTrophies &&
                          zoom != null &&
                          zoom >= 6.3) {
                        CountyFeedPopup.show(
                          context,
                          Coordinates.fromLatlng(latlng),
                        );
                      }
                    },
                    mapToolbarEnabled: false,
                    
                  ),
                )



```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![media_20241022_163314_190373198617611078](https://github.com/user-attachments/assets/173a6cde-8d7c-4619-aa16-9e7e830383bf)
![media_20241022_163314_6166740445788758578](https://github.com/user-attachments/assets/8f7fca1a-b45c-411f-b8f0-2506c4da7168)

https://github.com/user-attachments/assets/82327da6-a01a-4688-a0b0-3498d9b36c1e

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.19.6, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.19.6 on channel stable at /Users/appinventiv/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (6 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/appinventiv/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • iPhone 11 (mobile)                  • 00008030-00192D6A1150802E            • ios            • iOS 18.0.1 22A3370
    • iPhone SE (3rd generation) (mobile) • 94CF5751-DEC8-44A4-9D82-9EFA9AB1FBD3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • iPhone 15 Pro Max (mobile)          • 4EF25C24-8B25-4690-9866-7AC8CE679586 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 129.0.6668.101

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @App1309, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.24.3) to see if you still experience this issue. 

If you do, please provide the updated output of `flutter doctor -v` along with the version of `google_maps_flutter` you're using. Please make sure you're using the latest version. 

Thank you

**Comment by App1309** [comment]
Hey, Daniel.

I have already been using the latest version of the package along with the
latest Flutter version. Here is the output of the flutter doctor -v


[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64,
locale en-IN)
    • Flutter version 3.24.3 on channel stable at
/Users/appinventiv/fvm/versions/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version
34.0.0)
    • Android SDK at /Users/appinventiv/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • iPhone SE (3rd generation) (mobile) •
94CF5751-DEC8-44A4-9D82-9EFA9AB1FBD3 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • iPhone 15 Pro Max (mobile)          •
4EF25C24-8B25-4690-9866-7AC8CE679586 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                     • macos
     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad
     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 130.0.6723.59

[✓] Network resources
    • All expected network resources are available.

**Comment by App1309** [comment]
Hey, Daniel.

I have already been using the latest version of the package along with the latest Flutter version. Here is the output of the flutter doctor -v


[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /Users/appinventiv/fvm/versions/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/appinventiv/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • iPhone SE (3rd generation) (mobile) • 94CF5751-DEC8-44A4-9D82-9EFA9AB1FBD3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • iPhone 15 Pro Max (mobile)          • 4EF25C24-8B25-4690-9866-7AC8CE679586 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 130.0.6723.59

[✓] Network resources
    • All expected network resources are available.

**Comment by danagbemava-nc** [comment]
Hi @App1309, does this happen without the use of the custom map style? I tested the plugin example in a setup similar to what you describe and I cannot reproduce the issue. See the recording below


https://github.com/user-attachments/assets/51970ca7-a21b-4bf0-8ea3-052e1e6ce619

**Comment by App1309** [comment]
Hey, Daniel.

Yes, I am using a map style.
I will share it with you and please make sure that you are checking it on a
pixel device and that to with a release build not with a debug build and
also please provide some data in all the tabs.




*Regards,*
*Aditya Agarwal,*
*Software Engineer Flutter, **Appinventiv Technologies Pvt. Ltd.*
*Employee  ID:- AI2140*
https://appinventiv.com/
***@***.***
B-25, Sector 58, Noida-201301

**Comment by App1309** [comment]
import 'dart:convert';

class AppMapStyle {
  static List<Map<String, dynamic>> get style => [
        {
          "featureType": "administrative",
          "elementType": "geometry",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "administrative.land_parcel",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "administrative.neighborhood",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "administrative.province",
          "elementType": "geometry.stroke",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "landscape.natural",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "simplified"},
            {"weight": 8}
          ]
        },
        {
          "featureType": "landscape.natural",
          "elementType": "geometry.stroke",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "landscape.natural.landcover",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "landscape.natural.terrain",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi",
          "elementType": "labels.text",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.attraction",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.business",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.government",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.medical",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.park",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "poi.place_of_worship",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.school",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.sports_complex",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "road",
          "elementType": "labels",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "road",
          "elementType": "labels.icon",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "road.arterial",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "road.arterial",
          "elementType": "labels.text",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "road.highway",
          "stylers": [
            {"visibility": "simplified"}
          ]
        },
        {
          "featureType": "road.highway",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit.station",
          "elementType": "geometry.stroke",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit.station.airport",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit.station.bus",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit.station.rail",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "water",
          "elementType": "geometry.fill",
          "stylers": [
            {"color": "#487183"}
          ]
        },
        {
          "featureType": "water",
          "elementType": "geometry.stroke",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "water",
          "elementType": "labels.text",
          "stylers": [
            {"visibility": "off"}
          ]
        }
      ];

  static String get styleString => jsonEncode(style);
}

**Comment by danagbemava-nc** [comment]
Hi @App1309, I just tested again with the mapStyle in release mode and I don't see the map becoming transparent at points. I tested this on a Pixel 7. 

Please provide a complete minimal reproducible code sample without any third party packages so that we can properly investigate this. 

Thank you

**Comment by akshay-appinventiv** [comment]
Hi @danagbemava-nc can you share the release build with mapstyle added, just wanna check it on my device. The thing is it's only happening for Pixel devices as of now, and more confusing is that the code & logics are same.

**Comment by danagbemava-nc** [comment]
This is the full code sample I'm testing with. Can you run this in a new app to see if you still experience this issue? 

<details>
<summary>code sample</summary>

```dart
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  final _index = ValueNotifier(2);
  final _items = <Widget>[
    const ListPage(
      backgroundColor: Colors.red,
      itemCount: 100,
    ),
    const ListPage(
      backgroundColor: Colors.green,
      itemCount: 50,
    ),
    const MapSample(),
    const ListPage(
      backgroundColor: Colors.blueAccent,
      itemCount: 70,
    ),
    const ListPage(
      backgroundColor: Colors.orange,
      itemCount: 82,
    ),
  ];

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      bottomNavigationBar: NavigationBar(
        selectedIndex: _index.value,
        destinations: const [
          NavigationDestination(icon: Icon(Icons.abc), label: 'label1'),
          NavigationDestination(icon: Icon(Icons.abc), label: 'label2'),
          NavigationDestination(icon: Icon(Icons.map), label: 'maps'),
          NavigationDestination(icon: Icon(Icons.abc), label: 'label3'),
          NavigationDestination(icon: Icon(Icons.abc), label: 'label4')
        ],
        onDestinationSelected: (index) {
          _index.value = index;
        },
      ),
      body: ValueListenableBuilder<int>(
        valueListenable: _index,
        builder: (context, value, child) {
          return _items[value];
        },
      ),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller = Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        style: AppMapStyle.styleString,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    await controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

class AppMapStyle {
  static List<Map<String, dynamic>> get style => [
        {
          "featureType": "administrative",
          "elementType": "geometry",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "administrative.land_parcel",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "administrative.neighborhood",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "administrative.province",
          "elementType": "geometry.stroke",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "landscape.natural",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "simplified"},
            {"weight": 8}
          ]
        },
        {
          "featureType": "landscape.natural",
          "elementType": "geometry.stroke",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "landscape.natural.landcover",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "landscape.natural.terrain",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi",
          "elementType": "labels.text",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.attraction",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.business",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.government",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.medical",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.park",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "poi.place_of_worship",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.school",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "poi.sports_complex",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "road",
          "elementType": "labels",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "road",
          "elementType": "labels.icon",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "road.arterial",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "road.arterial",
          "elementType": "labels.text",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "road.highway",
          "stylers": [
            {"visibility": "simplified"}
          ]
        },
        {
          "featureType": "road.highway",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit.station",
          "elementType": "geometry.stroke",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit.station.airport",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit.station.bus",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "transit.station.rail",
          "elementType": "geometry.fill",
          "stylers": [
            {"visibility": "off"}
          ]
        },
        {
          "featureType": "water",
          "elementType": "geometry.fill",
          "stylers": [
            {"color": "#487183"}
          ]
        },
        {
          "featureType": "water",
          "elementType": "geometry.stroke",
          "stylers": [
            {"visibility": "on"}
          ]
        },
        {
          "featureType": "water",
          "elementType": "labels.text",
          "stylers": [
            {"visibility": "off"}
          ]
        }
      ];

  static String get styleString => jsonEncode(style);
}

class ListPage extends StatelessWidget {
  const ListPage({required this.backgroundColor, required this.itemCount, super.key});

  final Color backgroundColor;
  final int itemCount;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: backgroundColor,
      child: ListView.builder(
        itemBuilder: (context, index) {
          return ListTile(
            title: Text('item: ${index + 1}'),
          );
        },
        itemCount: itemCount,
      ),
    );
  }
}

```
</details>
