### ISSUE TITLE
`flutter build ios-framework --xcframework` incorrectly copies `Flutter.framework.dSYM` into App.xcframework

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#157359]
Add-to-app xcframework generation in release mode produces `App.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM` and `Flutter.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM`.  `App.xcframework` should not contain this dSYM.

This causes the IPA error:
```
error: Multiple commands produce '......./BuildProductsPath/Release-iphoneos/Flutter.framework.dSYM/Contents'
```

## Steps to Reproduce
Checkout https://github.com/flutter/samples
```
$ cd add_to_app/prebuilt_module/flutter_module
$ flutter build ios-framework --xcframework --output=../ios_using_prebuilt_module/Flutter --no-debug --no-profile
```
Observe `ios_using_prebuilt_module/Flutter/Release/App.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM` and `ios_using_prebuilt_module/Flutter/Release/Flutter.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM`.

The workaround is to delete `App.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM`.

**Comment by jmagman** [comment]
Logic is here:
https://github.com/flutter/flutter/blob/5fa5a648428f03a9b6bdffba2cb77876146b8d79/packages/flutter_tools/lib/src/commands/build_ios_framework.dart#L153-L155

**Comment by jmagman** [comment]
Test to be updated is here:
https://github.com/flutter/flutter/blob/5fa5a648428f03a9b6bdffba2cb77876146b8d79/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart#L191-L199

**Comment by jmagman** [comment]
And also the unit test add something like `parentA.childFile('Flutter.framework.dSYM')..createSync();` and confirm the command doesn't change (also confirm it fails before the fix because I didn't actually try this 😅)
https://github.com/flutter/flutter/blob/e9fb545c0584eca610e629718ac984bf3f189728/packages/flutter_tools/test/commands.shard/hermetic/build_darwin_framework_test.dart#L559

**Comment by dorukbasaran** [comment]
We are encountering the following issue with our iOS framework builds in release mode. Previously, the size of the framework was around 100MB, but now it has increased to over 1GB. We are removing the dSYM files and their references from the Info.plist files via a script during the release build. However, after doing this, we are now facing the following signature error. Could you please assist us?

SignatureCollection /Users/runner/Library/Developer/Xcode/DerivedData/ProjectName-edzqkohwcavlbfdkjtskcbnbjloe/Build/Intermediates.noindex/ArchiveIntermediates/QA/BuildProductsPath/QA-iphoneos/Flutter.xcframework-ios.signature
    cd /Users/runner/work/1/s/ProjectName.xcodeproj
    builtin-collectSignature --input /Users/runner/work/1/s/Flutter/QA/Flutter.xcframework --output /Users/runner/Library/Developer/Xcode/DerivedData/ProjectName-edzqkohwcavlbfdkjtskcbnbjloe/Build/Intermediates.noindex/ArchiveIntermediates/QA/BuildProductsPath/QA-iphoneos/Flutter.xcframework-ios.signature --info platform ios --info library Flutter.framework
error: signature-collection failed: The operation couldn’t be completed. (XCBUtil.CodeSignatureInfo.Error error 0.)

**Comment by sulaimansust** [comment]
I am facing the same issue. My project is failing to build.

**Comment by jmagman** [comment]
@dorukbasaran The fix just merged, would you be willing to test it on the [master channel](https://github.com/flutter/flutter/blob/master/docs/releases/Flutter-build-release-channels.md#how-to-change-channels)?

**Comment by jmagman** [comment]
@dorukbasaran or @sulaimansust can you confirm the fix? I'd like to hotfix to stable if it's working.

**Comment by jmagman** [comment]
Or anyone else hitting this, maybe 👍  @goncg007 @farukarslan?

**Comment by jogboms** [comment]
Hey @jmagman I can verify this works as expected on master

**Comment by jmagman** [comment]
Stable channel cherry pick request at https://github.com/flutter/flutter/pull/158125

**Comment by Jeanno** [comment]
@jmagman It also works for me. Thanks
