### ISSUE TITLE
Plugin: Firebase messages not working anymore on master version

### ISSUE THREAD

**Issue by Devjone** [flutter/flutter#15735]
## Steps to Reproduce
```
Upgrade to last channel master version
Try to run the firebase messages example
```

This part will never run

```
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) {
        print("onMessage: $message");
        _showItemDialog(message);
      },
      onLaunch: (Map<String, dynamic> message) {
        print("onLaunch: $message");
        _navigateToItemDetail(message);
      },
      onResume: (Map<String, dynamic> message) {
        print("onResume: $message");
        _navigateToItemDetail(message);
      },
    );
```

On debugging values of onMessage, onLaunch and onResume are set to null

## Flutter Doctor
Flutter doctor shows no issues

**Comment by salehahmedZ** [comment]
I faced the same issue, you have to go back to beta version for now.

**Comment by Herohtar** [comment]
I haven't tried recently, but the handlers weren't working for me on beta not too long ago.

**Comment by salehahmedZ** [comment]
Yes, I can confirm there are working just fine on beta version. I'm using them right now on my project.

**Comment by Herohtar** [comment]
I just checked again and they're still not working for me in beta. I can debug and put a breakpoint inside the lines of `_handleMethod`:
```
case "onMessage":
  return _onMessage(call.arguments);
case "onLaunch":
  return _onLaunch(call.arguments);
case "onResume":
  return _onResume(call.arguments);
```

It will go to the appropriate `return _on*` and I can see that `call.arguments` has the values from my message, but it never enters the function assigned to it. The debugger just shows the values of `_onMessage` and so as "_Closure" so I'm not sure what is going on.

**Comment by salehahmedZ** [comment]
It's really hard to figure out the issue without seeing the whole project files.

1-Did you modify the AndroidManifest.xml to include:

```
  <intent-filter>
      <action android:name="FLUTTER_NOTIFICATION_CLICK" />
      <category android:name="android.intent.category.DEFAULT" />
  </intent-filter>
```

2-Did you include this key/value pairs as part of your message payload or custom data.

`click_action=FLUTTER_NOTIFICATION_CLICK`

**Comment by Herohtar** [comment]
Yes, I have done that, and when I set a breakpoint at, for example, `return _onResume(call.arguments)` I can see that `call.arguments` contains `"click_action": "FLUTTER_NOTIFICATION_CLICK"`. It just doesn't call my function once that statement executes.

**Comment by Herohtar** [comment]
Do you mean for the handler or something else?

I tried this, but it made no difference:
```
onMessage: (Map<String, dynamic> message) {
  SchedulerBinding.instance.addPostFrameCallback((_) {
    debugPrint('onMessage: $message');
    // other code
  });
}
```

**Comment by salehahmedZ** [comment]
Here is the working initState() function on my code:

```
void function1(message) {
    SchedulerBinding.instance.addPostFrameCallback((_) {
     //Other code
    });
  }



  @override
  void initState() {
    super.initState();

    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) {
        function1(message);
      },
      onLaunch: (Map<String, dynamic> message) {
        function1(message);
      },
      onResume: (Map<String, dynamic> message) {
        function1(message);
      },
    );

    _firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(sound: true, badge: true, alert: true));

    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });

    _firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      print("Push Messaging token: $token");
      //Other code
    });
  }
```

**Comment by Herohtar** [comment]
So, I tried what you did and still got nothing, so I put my original code back. Then I had a random thought and tried running it without `--preview-dart-2`... and it worked. So something about Dart 2 is breaking it.

**Comment by mravn-google** [comment]
Yes, with Dart 2 semantics, the message handlers expect Map<String, dynamic> but receive Map<dynamic, dynamic> from the channel. I'll fix later today, unless somebody else beats me to it.

**Comment by anondev32** [comment]
Still Map<dynamic,dynamic> ja received. And Updates?
