### ISSUE TITLE
"flutter packages get" failing on Windows 10 (beta)

### ISSUE THREAD

**Issue by PaulHMason** [flutter/flutter#15737]
## Steps to Reproduce

Create a new Flutter project. The "flutter packages get" command fails:

**Failed to delete entry because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.**

It works fine for the alpha.

## Logs

No logs

## Flutter Doctor

[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
    • Flutter version 0.1.5 at E:\flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at E:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = E:\AndroidSDK
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4343.25

[√] Connected devices (1 available)
    • SM G930F • xxx • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by PaulHMason** [comment]
And now it works :-/

Closing the issue.

**Comment by VRspace4** [comment]
@PaulHMason, how did you resolve this issue? I've tried running it in a command prompt with admin privileges but got the same error message:

> Running "flutter packages get" in myapp3...
> Failed to rename directory because access was denied.
> This may be caused by a virus scanner or having a file
> in the directory open in another application.
> pub get failed (1)

**Comment by PaulHMason** [comment]
I didn't do anything - it just started working again. I find deleting reinstalling Flutter usually works when it does strange things.
