### ISSUE TITLE
Issue from website page Support

### ISSUE THREAD

**Issue by kinnariarastu** [flutter/flutter#15736]
From URL: https://flutter.io/support.md

**Comment by kinnariarastu** [comment]
While trying to import dependencies from pubspec.yaml getting  errors. this are the dependencies i have tried with - (shared_preferences: "^0.4.0") - (qrcode_reader: "^0.3.2")
and how to directly import any flutter project in android studio?

**Comment by zoechi** [comment]
>  trying to import dependencies from pubspec.yaml

What does that mean exactly?
What are the full error messages?
What is the output of `flutter doctor -v`?

**Comment by kinnariarastu** [comment]
I mean when import dependencies in pubspec.yaml that time show success message,but when import in main.dart(import 'package:shared_preferences/shared_preferences.dart') file that time occur error

When Click on Get dependencies Full Error Message:
/home/kinnari/NewAndroidVersion/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in shared_preferences...
Error on line 12, column 3 of pubspec.yaml: A package may not list itself as a dependency.
  shared_preferences: ^0.4.0
  ^^^^^^^^^^^^^^^^^^
pub get failed (65)

flutter doctor -v : 0.2.2-pre.41

**Comment by zoechi** [comment]
What is the name of your project in `pubspec.yaml`?

**Comment by kinnariarastu** [comment]
pubspec.yaml

name: shared_preferences
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  english_words: ^3.1.0
  shared_preferences: ^0.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

**Comment by zoechi** [comment]
Can you please edit your comment and wrap the pubspec.yaml content in ``` to get it properly formatted. 
As mentioned above, you need to change the name of your project 

    name: shared_preferences

should be

    name: some_other_name

**Comment by kinnariarastu** [comment]
Thank you @zoechi by doing that have resolved the issue
