### ISSUE TITLE
Latest flutter SDK changed the default text weight on Android

### ISSUE THREAD

**Issue by taosimple** [flutter/flutter#157395]
### Steps to reproduce

After upgrading to flutter 3.24.3, the Chinese font weight is changed too light on my Android device (Realme). It seems that both OPPO and OnePlus phones have been affected.
Before upgrade:
<img width="311" alt="image" src="https://github.com/user-attachments/assets/4f489151-e4e7-4a80-9942-98d9461c8bf2">

After upgrade:
<img width="312" alt="image" src="https://github.com/user-attachments/assets/c65845d8-c504-4a14-8f65-ad5385d9a333">

### Expected results

picture-2 above

### Actual results

picture-1 above

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Welcome to Flutter'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text('这是一段中文字'),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/taotao/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/taotao/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/taotao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.


```

</details>

**Comment by danagbemava-nc** [comment]
Hi @taosimple, this was initially reported in https://github.com/flutter/flutter/issues/154166. 

It appears to have been fixed on the `beta` & `master` channels. Can you check if you are still able to reproduce this on either the beta or master channel? 

You can switch to either channel by running 

```
flutter channel master or beta
flutter upgrade
```

**Comment by taosimple** [comment]
@danagbemava-nc  
I checked, it fixed on master, thanks.
