### ISSUE TITLE
[cocoon] handle engine .ci.yaml in different location

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#157358]
There are commands that validate "runIf".  In a merged world, either we have merged ci.yaml or we have to handle two.

```dart
        // Verify runIf includes foundational files.
        if (target.runIf.isNotEmpty) {
          if (!target.runIf.contains('.ci.yaml')) {
            exceptions.add('ERROR: ${target.name} is missing `.ci.yaml` in runIf');
          }
          if (slug == Config.engineSlug && !target.runIf.contains('DEPS')) {
            exceptions.add('ERROR: ${target.name} is missing `DEPS` in runIf');
          }
        }
```

**Comment by jtmcdole** [comment]
@christopherfujino: would you want to have merged ci.yaml files? if so, would we want to have some flag for engine tests?

**Comment by christopherfujino** [comment]
> @christopherfujino: would you want to have merged ci.yaml files? if so, would we want to have some flag for engine tests?

What do you mean by "merged ci.yaml files"?

Could we just update the cocoon code to be:

```diff
        // Verify runIf includes foundational files.
        if (target.runIf.isNotEmpty) {
          if (!target.runIf.contains('.ci.yaml')) {
            exceptions.add('ERROR: ${target.name} is missing `.ci.yaml` in runIf');
          }
-          if (slug == Config.engineSlug && !target.runIf.contains('DEPS')) {
+          if (_isMonoRepo(repo) && slug == Config.engineSlug && !target.runIf.contains('DEPS')) {
            exceptions.add('ERROR: ${target.name} is missing `DEPS` in runIf');
          }
        }
```

Where `_isMonoRepo()` checks if it's a flutter/flutter repo with the engine in it?

**Comment by jtmcdole** [comment]
> What do you mean by "merged ci.yaml files"?

Is there a world where we want to `cat .ci.yaml engine/src/flutter/.ci.yaml > .ci.yaml` or keep them apart? (this is not how we would merge them).

> Where _isMonoRepo() checks if it's a flutter/flutter repo with the engine in it?

In your example we'd need to have
```dart
if ((isMonoRepo(repo) || slug == Config.engineSlug) && !target.runIf.contains('DEPS')) {
}
```

The problem with that block is its not checking if the ci.yaml is the one from the `engine/src/flutter` folder.

**Comment by christopherfujino** [comment]
> Is there a world where we want to cat .ci.yaml engine/src/flutter/.ci.yaml > .ci.yaml or keep them apart? (this is not how we would merge them).

Ahh, I see what you mean. I think for this initial change we should keep them separate. All of our infrastructure has baked in assumptions that the build environments for the two repos are separate, so I think we should keep them separate for now.

**Comment by christopherfujino** [comment]
And yes, you're right about the code sample :)

**Comment by jtmcdole** [comment]
> I think for this initial change we should keep them separate

Thanks - I thought the same. I'll file a future feature request after the dust settles!

**Comment by jtmcdole** [comment]
@christopherfujino - `CiYaml` doesn't appear to have a PR to check with.  Would you be opposed to adding `monorepo: false` to ci.yaml (both locations) which we could use internally on some of these checks?

**Comment by christopherfujino** [comment]
> `CiYaml` doesn't appear to have a PR to check with.

What do you mean by this? Do you mean the Dart class within the cocoon app_dart project does not have a reference to the PR from which to introspect the file structure? If so, I think adding a top-level `monorepo` boolean field to .ci.yaml that defaults to false would make sense.

**Comment by jtmcdole** [comment]
I mean the dart class, `CiYaml`, is handed parsed contents:

```dart
  CiYaml({
    required this.slug,
    required this.branch,
    required this.config,
    CiYaml? totConfig,
    bool validate = false,
  }) {
```

I'm already going to have to find every site that looks up `flutter/flutter/.ci.yaml` and make it check `flutter/flutter/engine/src/flutter/.ci.yaml` and that would work from the top end; but if you're handed only scheduler configs deeper down; how do you know its a monorepo or not? If you have a PR, we can check for files, but in other cases its just "here's yaml".

Instead of updating the actual files; I could update the proto to have the field and set it when we fetch the contents.

**Comment by christopherfujino** [comment]
We could also change the meaning of `slug`. Today slug means what repo you're operating on. We could change slug to be an enum, including:

- flutter/flutter framework
- flutter/engine engine
- monorepo framework
- monorepo engine

**Comment by jtmcdole** [comment]
I'm not sure if that creates more work or not. We'd have to figure out, at call time, which slug we are in.

**Comment by jtmcdole** [comment]
scheduler.dart looks at the PR

```dart
  /// Load in memory the `.ci.yaml`.
  Future<CiYaml> _getCiYaml(
```

This is called twice; once to get tip of tree, and the second time to get the one for the commit:

```dart
  /// Process and filters ciyaml.
  Future<CiYaml> getCiYaml(
    Commit commit, {
    bool validate = false,
  }) async {
    final Commit totCommit = await generateTotCommit(slug: commit.slug, branch: Config.defaultBranch(commit.slug));
    final CiYaml totYaml = await _getCiYaml(totCommit);
    return _getCiYaml(commit, totCiYaml: totYaml, validate: validate);
  }```

The CI path is hard-coded: 

```dart
    ciPath = '${commit.repository}/${commit.sha!}/$kCiYamlPath';
```

I think this should potentially return an array of ciyaml, based on the needs of the PR under presubmit... "isEngine()" "isFramework()"
