### ISSUE TITLE
DRM Video player support for windows Desktop

### ISSUE THREAD

**Issue by meadow-tulips** [flutter/flutter#157433]
### Use case

Hello, Guys.

Wanted to know if there are any current plans on developing or extending the support of flutter's default video player to work with windows desktop applications.

![image](https://github.com/user-attachments/assets/a71ad2bf-2db0-44ad-bc4a-96e11a32ce0d)

I can see that windows is not marked as supported. Also, in current version.. can we play DRM encrypted videos ?
Needed to know if there are any such plans in the near future.

### Proposal

I am looking for a cross platform video player solution (Android, IOS and windows applications) with DRM support. I could see that there is https://pub.dev/packages/media_kit .. but does not have a DRM support.

**Comment by danagbemava-nc** [comment]
Windows support is being tracked in https://github.com/flutter/flutter/issues/37673

DRM support is being tracked in https://github.com/flutter/flutter/issues/24923

Kindly follow up in the issues linked above for updates. 

Closing from here as these feature requests are being tracked in other issues.
