### ISSUE TITLE
[GoRouter] [iOS] deep link when app terminated does not open app on right route

### ISSUE THREAD

**Issue by dgugolf** [flutter/flutter#157498]
### Steps to reproduce

Terminate app, and open it by clicking on Depp link with rout parameter or app scheme <scheme>:///booking.

If app in background, link works fine

### Expected results

App should open on booking route

### Actual results

App still stays on initial route "/"
RedirectSuccessPage never opens

### Code sample

<details open><summary>Code sample</summary>

```dart
@TypedGoRoute<HomeRoute>(
  path: HomeRoute.path,
  routes: <TypedGoRoute<GoRouteData>>[
    bookingRedirect,
  ],
)
class HomeRoute extends GoRouteData {
  static const path = "/";

  const HomeRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      const AppContent(title: "home");
}

const bookingRedirect = TypedGoRoute<BookingRedirectPage>(
  path: BookingRedirectPage.path,
  routes: [],
);

class BookingRedirectPage extends GoRouteData {
  static const path = "booking";
  final String clubid;

  const BookingRedirectPage({this.clubid = ""});

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      RedirectSuccessPage();
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (7 available)            
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
This is a known issue which is being tracked in https://github.com/flutter/flutter/issues/142988

Kindly follow up in the original issue for updates

Closing from here as duplicate 

Thank you
