### ISSUE TITLE
Issue from website page Making HTTP Networking Requests in Flutter

### ISSUE THREAD

**Issue by shyjuzz** [flutter/flutter#15740]
From URL: https://flutter.io/networking.md

Getting the exception "type '_Future' is not a subtype of type 'VoidCallback' of 'onPressed' where" when we call async method from button on pressed event. App is not working

**Comment by zoechi** [comment]
How did you get above URL?
I think it should be https://flutter.io/networking/

**Comment by zoechi** [comment]
Are you sure you didn't write `onPressed: _getIPAddress(),` instead of `onPressed: _getIPAddress,`?

**Comment by lucidappstudio** [comment]
Thanks for the reply. Was added parenthesis in the function call by mistake

**Comment by shyjuzz** [comment]
Thanks for the reply. Was added parenthesis in the function call by mistake
