### ISSUE TITLE
Is any sort of backend implementation required for the Product Purchase?

### ISSUE THREAD

**Issue by hunnyopenxcell** [flutter/flutter#157434]
Is any sort of backend implementation required for the Product Purchase?

Frontend Devs have implemented the IAP and saying that Backed is not required just save the receipts and transaction.
They say that it's required when working with Subscriptions.
I just need to confirm that is any sort of verification is required for the IAP of Google Play and App store.

Thanks.

**Comment by darshankawar** [comment]
@hunnyopenxcell 
Your question is better suited for support channels like stackoverflow, as this is neither a bug report or proposal but more of a support question.
Closing from here.
