### ISSUE TITLE
Can't copy multiple lines within SelectionArea in Flutter WEB

### ISSUE THREAD

**Issue by berslen** [flutter/flutter#157445]
### Steps to reproduce

1. Open official example of usage https://api.flutter.dev/flutter/material/SelectionArea-class.html
2. Select multiple lines of text within the example app
3. Right click
4. It deselects the rest of the lines
5. Hit copy
6. It copies only the line I right clicked

### Expected results

As user I should be able to select multiple lines and copy them on Web Platform 

### Actual results

I can only copy line single even though I selected multiple lines

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [SelectionArea].

void main() => runApp(const SelectionAreaExampleApp());

class SelectionAreaExampleApp extends StatelessWidget {
  const SelectionAreaExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SelectionArea(
        child: Scaffold(
          appBar: AppBar(title: const Text('SelectionArea Sample')),
          body: const Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text('Row 1'),
                Text('Row 2'),
                Text('Row 3'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/72e57bdd-0e71-405f-9489-c15ed9ad4d56)
![image](https://github.com/user-attachments/assets/2e057227-6bfa-414a-b04c-50f6da8429fd)

</details>

### Logs

No exceptions thrown

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale tr-TR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.5)
[√] Android Studio (version 4.2)
[√] VS Code (version unknown)
    X Unable to determine VS Code version.
[√] VS Code, 64-bit edition (version 1.94.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @berslen, this has been fixed on the latest beta (3.27.0-0.1.pre) & master(3.27.0-1.0.pre.209). See the recording below. 


https://github.com/user-attachments/assets/13cc7609-3d1e-4f6e-842c-8990217cee71

Closing this since it has already been fixed. 

Thank you
