### ISSUE TITLE
TextField and TextFormField fillColor is not bounded by OutlineInputBorder

### ISSUE THREAD

**Issue by savy-91** [flutter/flutter#15742]
## Steps to Reproduce

I was trying to make some TextField fields to use on an image background so I wanted them to be on a white background and surrounded by a border. When I tried to fill the fields with a solid color I noticed that the field background color is rectangular regardless of the border radius I set.

This happens both using master and beta branches.

The following code produces the result below:
```Dart
new TextFormField(
                  decoration: new InputDecoration(
                    fillColor: Colors.greenAccent,
                      filled: true,
                      contentPadding: new EdgeInsets.fromLTRB(
                          10.0, 30.0, 10.0, 10.0),
                      border: new OutlineInputBorder(
                        borderRadius: new BorderRadius.circular(12.0),
                      ),
                      labelText: 'Nome'),
                )
```

![image](https://user-images.githubusercontent.com/6215122/37661349-e4d79fde-2c54-11e8-8c88-77225d6a4868.png)

In order to obtain the desired behaviour, I need to completely remove the decoration from the TextFormField and use a Container:

```Dart
new Container(
                padding: const EdgeInsets.all(8.0),
                alignment: Alignment.center,
                height: 60.0,
                decoration: new BoxDecoration(
                  color: Colors.blueGrey,
                  border: new Border.all(
                    color: Colors.black54,
                    width: 4.0
                  ),
                  borderRadius: new BorderRadius.circular(12.0)
                ),
                child: new TextFormField(
                  decoration: null,
                ),
              )
```

![image](https://user-images.githubusercontent.com/6215122/37661513-45e3d9d2-2c55-11e8-8f72-72f5dd86d382.png)

## Flutter Doctor

> flutter doctor -v
> [√] Flutter (Channel master, v0.2.4-pre.64, on Microsoft Windows [Versione 10.0.16299.251], locale it-IT)
>     • Flutter version 0.2.4-pre.64 at c:\flutter
>     • Framework revision 619ebd67a9 (7 hours ago), 2018-03-20 00:26:10 -0700
>     • Engine revision c3ab0c9143
>     • Dart version 2.0.0-dev.39.0.flutter-f1ebe2bd5c
> 
> [√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at C:\Users\savy9\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-27, build-tools 27.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> 
> [√] Connected devices (2 available)
>     • Android SDK built for x86 • emulator-5554      • android-x86   • Android 8.0.0 (API 26) (emulator)
>     • MI 6                      • 192.168.1.111:4444 • android-arm64 • Android 8.0.0 (API 26)
> 
> • No issues found!

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
This is indeed a bug. I have a fix, will try and upload a PR today.

**Comment by augustocadini** [comment]
How I can make a `TextField` like this:

![screen shot 2019-01-17 at 15 02 28](https://user-images.githubusercontent.com/18659348/51335320-f4f30900-1a68-11e9-8a00-0a4a83488675.png)

**Comment by zoechi** [comment]
@augustocadini 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by augustocadini** [comment]
> @augustocadini
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Ok, sorry.

**Comment by stickyboiproject** [comment]
Is this problem has a solution already? Im having the same issue, the background of my textformfield doesnt follow the border shape

**Comment by klaszlo8207** [comment]
any news on this issue?

**Comment by md-weber** [comment]
Just if someone stumbles on this because the fillColor is not set. You also have to set the value for "filled".
`
                  TextFormField(
                    decoration: InputDecoration(
                      filled: true,
                      fillColor: Colors.white,
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                    ),
                  )
`

**Comment by fardeen9983** [comment]
The only solution I found is to remove border property from your Input border and just put it in a container with decoration:
`` Container(
                        margin: EdgeInsets.symmetric(vertical: 8),
                        width: size.width * 0.75,
                        padding: EdgeInsets.all(3.0),
                        decoration: BoxDecoration(
                            color: Colors.grey.withAlpha(10),
                            borderRadius: BorderRadius.circular(8.0)),
                        child: TextFormField(
                          decoration: InputDecoration(
                              border: InputBorder.none,
                              labelText: "Email Address",
                              labelStyle: TextStyle(fontSize: 14),
                              prefixIcon: Icon(
                                Icons.mail_outline,
                                size: 24,
                                color: Colors.blueAccent,
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderSide: BorderSide(
                                    color: Colors.blueAccent, width: 1),
                                borderRadius: BorderRadius.circular(8.0),
                              )),
                        ),
                      ),``
