### ISSUE TITLE
Logger received error output during the run, and "--fatal-warnings" is enabled is evil

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#157542]
Ostensibly https://github.com/flutter/flutter/pull/157388 broke the build (https://github.com/flutter/flutter/pull/157541).

The only reported cause is:
```txt
11:37 +16476 ~151: Some tests failed.
Logger received error output during the run, and "--fatal-warnings" is enabled.
╔═╡ERROR #1╞════════════════════════════════════════════════════════════════════
║ Command: ../../bin/flutter test --reporter=expanded --file-reporter=json:/Volumes/Work/s/w/ir/x/t/metrics_1729793120661295.json --test-randomize-ordering-seed=20241024 --fatal-warnings --enable-impeller
║ Command exited with exit code 1 but expected zero exit code.
║ Working directory: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter
╚═══════════════════════════════════════════════════════════════════════════════
▌11:17:12▐ Test failed.
```

([Logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8733174319067180289/+/u/run_test.dart_for_framework_tests_shard_and_subshard_impeller/stdout))

I can't seem to find where the error output is, if it's actually my change, or what to do about it.

/cc @jtmcdole

**Comment by jmagman** [comment]
You DIDN'T find this output convenient? 🙃 
```
For your convenience, the error messages reported above are repeated here:
  🙙  🙛  
```

**Comment by matanlurey** [comment]
Closed by https://github.com/flutter/flutter/pull/157548.
