### ISSUE TITLE
Flutter web: Various "CompileError: WebAssembly.compileStreaming()" errors in production build

### ISSUE THREAD

**Issue by bpjhe** [flutter/flutter#157585]
### Steps to reproduce

Issue is only occurring on some devices and is kinda hard to setup step by step guide for how to reproduce.

The app is built with:
`flutter build web --release --web-renderer canvaskit --source-maps --no-web-resources-cdn --base-href /next/ --dart-define-from-file config.json`

When user opens the site in production the application never loads.

My gut feeling is that the issue occurs after publish of a new update but I cannot comfirm that this is the case.

### Expected results

I would expect the application to load

### Actual results

The application never loads, in the console we have observed these two messages on a Pixel 7 Pro using Chrome. We have some reports from customers on apple devices also.
```

Uncaught (in promise) CompileError: WebAssembly.compileStreaming(): size 8257536 > maximum function size 7654321 @+220223

Uncaught (in promise) CompileError: WebAssembly.compileStreaming(): extra bits in varint @+283677

Uncaught (in promise) CompileError: WebAssembly.compileStreaming(): reached end while decoding body size @+4907927
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/jheckholdt/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jheckholdt/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    ! iOS 18.0 Simulator not installed; this may be necessary for iOS and macOS development.
      To download and install the platform, open Xcode, select Xcode > Settings > Platforms,
      and click the GET button for the required platform.

      For more information, please visit:
        https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • Pixel 7 Pro (mobile)            • 29201FDH30011N        • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 130.0.6723.70

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
@bpjhe 
In order to properly address the issue, it would be really helpful if you could provide us a reproducible code sample that shows the reported logs.

**Comment by bpjhe** [comment]
Not sure I will be able create a code sample for this. The issue only happens for some devices and only in production. I have not seen it on macOS or Windows trying Firefox, Chrome and Safari. Happen consistently on Pixel 7 with both Chrome and Firefox, but not on Pixel 9. We have some reports from customers on Apple devices.

We are running with `--no-web-resources-cdn` which means that we are hosting `canvaskit.wasm` ourselves, which is as far as I can understand the file that causes issues here. Anything I should be mindful of when doing so?
