### ISSUE TITLE
[WidgetsApp][BackdropFilter] Strange blur effect inside a WidgetsApp

### ISSUE THREAD

**Issue by oliver-hrkltz** [flutter/flutter#157594]
### Steps to reproduce

1. `flutter create --platforms=web example`
2. lib should contain the following three files: blur_component.dart, material_main.dart, widgets_main.dart (see code section)
3. `flutter run -d web-server -t libs/material_main.dart` and `flutter run -d web-server -t libs/widgets_main.dart`

(You can achieve the same strange behaviour if you simply remove the Scaffold widget from the MaterialApp. Somehow the Scaffold is doing something which affects the blur effect.)

### Expected results

The blur should look the same as the BackdropFilter class is not part of the material lib.

### Actual results

The BackdropFilter looks different. The blur effect on the widgets app looks more like a shadow (right window on the screenshot).

### Code sample

<details open><summary>blur_component.dart</summary>

```dart
import 'dart:ui';
import 'package:flutter/widgets.dart';


class BlurComponent extends StatelessWidget {
  final Widget child;


  const BlurComponent({super.key, required this.child});


  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        // Content
        child,

        // Blur
        BackdropFilter(filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
          child: Container(
            color: const Color.fromRGBO(0, 0, 0, 0.3),
          ),
        ),
      ],
    );
  }
}
```

</details>

<details open><summary>material_main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:example/blur_component.dart';


void main() {
  runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});


  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}


class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});


  @override
  State<MyHomePage> createState() => _MyHomePageState();
}


class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(body: BlurComponent(child:Center(child:Text('Hello World!',)))
    );
  }
}

```

</details>

</details>

<details open><summary>widgets_main.dart</summary>

```dart
import 'package:flutter/widgets.dart';
import 'package:example/blur_component.dart';


void main() {
  runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});


  @override
  Widget build(BuildContext context) {
    return WidgetsApp(
      debugShowCheckedModeBanner: false,
      color: const Color.fromARGB(255, 255, 0, 255,),
      builder: (context, child) {
        return child!;
      },
      pageRouteBuilder: <T>(RouteSettings settings, WidgetBuilder builder) {
        return PageRouteBuilder<T>(
          settings: settings,
          pageBuilder: (context, animation, secondaryAnimation) => builder(context),
          transitionDuration: const Duration(seconds: 0), // No animation
          reverseTransitionDuration: const Duration(seconds: 0), // No animation
        );
      },
      home: const MyHomePage(),
    );
  }
}


class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});


  @override
  State<MyHomePage> createState() => _MyHomePageState();
}


class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const BlurComponent(child:Center(child:Text('Hello World!',)));
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/d3c3f8a5-8893-44b9-b13d-6a16a8c2184f)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-CH)
    • Flutter version 3.22.3 on channel stable at /Users/oliver/Others/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/oliver/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 130.0.6723.70
    ! Error: Browsing on the local area network for iPhone von Oliver. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@oliver-hrkltz 
I tried the code sample using latest master and running on macOS desktop and observed below:

1. With materialApp code:

<img width="352" alt="Screenshot 2024-10-28 at 12 24 30 PM" src="https://github.com/user-attachments/assets/fad825a9-313d-4b18-984f-cefb6ab2d1ba">


2. With WidgetsApp code:

<img width="378" alt="Screenshot 2024-10-28 at 12 25 49 PM" src="https://github.com/user-attachments/assets/b94415e9-db1a-4507-b906-ebc9e2375611">

What's the expected behavior are you looking for ? 1 to match 2 or vice versa ?

**Comment by oliver-hrkltz** [comment]
Hey @darshankawar,

The first picture is the desired result. Everything behind the BackdropFilter should be not clear / readable.

**Comment by darshankawar** [comment]
Thanks for the update. Per my verification, replicable on latest versions.

```
stable : 3.24.3
master : 3.27.0-1.0.pre.259
```

**Comment by nate-thegrate** [comment]
Hey @oliver-hrkltz, I think I figured out the bug!


```dart
// MaterialApp home page
return Scaffold(body: BlurComponent(...));

// WidgetsApp home page
return BlurComponent(...);
```

The inconsistency comes from the fact that material_main.dart is wrapping the `BlurComponent` in a `Scaffold`, while widgets_main.dart is not.

This could be fixed by wrapping the `BlurComponent` with a `ColoredBox` or something similar.

```dart
return ColoredBox(
  color: Color(0xFFFFFFFF),
  child: BlurComponent(...),
);
```

<br>

Just for fun, here's a [**DartPad link**](https://dartpad.dev/?id=13de30236c7873f82bd472a3fe7c1ea3) where you can try out the different combinations!
Let me know if you have any further questions :)

**Comment by oliver-hrkltz** [comment]
Thanks @nate-thegrate! ColoredBox() solved the issue in my project. 

For me this workaround fine. Not sure how you guys want to continue on this ticket as it still requires some undocumented additional widgets to work as expected.

**Comment by nate-thegrate** [comment]
> it still requires some undocumented additional widgets to work as expected.

Actually, I think I disagree here. The [BackdropFilter docs](https://main-api.flutter.dev/flutter/widgets/BackdropFilter-class.html) describe it as "a widget that applies a filter to the existing painted content," and the issue here was that there wasn't an existing backdrop with painted content.

I think I'll go ahead and close this, but feel free to respond with any follow-up questions and we can re-open!
