### ISSUE TITLE
Physical keyboard: enter key should trigger appropriate keyboard action on text fields if set.

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15757]
Enter key blurs the field, which is unexpected.  It essentially maps to the "done" key on the android keyboard which hides the keyboard, but that seems wrong when using a physical keyboard.  We should seek UX guidance on what the right behavior is here.

**Comment by jslavitz** [comment]
Shouldn't it just add a new line character to the current string and move the cursor to the next line?

**Comment by jonahwilliams** [comment]
@jslavitz that sounds about right and I think this is already the behavior the text fields have if the `textInputAction` provided is none, see https://github.com/flutter/flutter/blob/00aac68e2da653920aac8c82d52b9382d3743895/packages/flutter/lib/src/services/text_input.dart#L138.

**Comment by jslavitz** [comment]
Yah, so it does do this in text fields right now. Can we close this issue then?

**Comment by jonahwilliams** [comment]
In the case of a chromebook maybe we want all of the ime actions to become enter? Thoughts @tvolkert ?

**Comment by tvolkert** [comment]
We need UX guidance.  For instance, I'd expect `IME_ACTION_NEXT`, for instance, to traverse the focus (and opposite for `IME_ACTION_PREVIOUS`).  Also, we probably want different behavior for multi-line vs single-line text fields (where for multi-line, enter adds a newline, but for single-line, it traversed the focus?).

/cc @willlarche

**Comment by franciscojma86** [comment]
FWIW, I added this [change](https://github.com/flutter/flutter/commit/d556d2117d77bf8309f399d989ae058fbe0671b7) in Oct. It calls onSubmitted if maxLines == 1. On desktop, hitting Enter on multiline text fields does nothing.

**Comment by goderbauer** [comment]
@gspencergoog FYI

**Comment by gspencergoog** [comment]
I think this is done, but needs to be tested to verify.

**Comment by gspencergoog** [comment]
Actually not done.  Physical enter key submits, but that's it.

**Comment by AndiDog** [comment]
For web, I expect a `TextField` within a `Form` to call a method on the form (something like `Form::onSubmitted`). That probably doesn't fit well in the current API, so instead there could at least be a good recommendation to do this (in the documentation). Having only the "Submit" button react to the Enter key isn't sufficient.

**Comment by tvolkert** [comment]
@gspencergoog does this being in the "Done" project bucket mean it should be closed?

**Comment by markusaksli-nc** [comment]
This seems fixed on the latest master `1.21.0-6.0.pre.17` when testing on web, Windows desktop, and Pixel C tablet emulator with a physical keyboard. Enter key submits on single line TextField, and adds linebreak and moves cursor in multiline TextField as expected.
<details>
 <summary>Used sample code</summary>

 ```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Container(
          child: Center(child: Column(
            children: [
              TextField(onSubmitted: (_) => print(_),),
              TextField(maxLines: null,onSubmitted: (_) => print(_)),
            ],
          ),),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-6.0.pre.17, on Microsoft Windows [Version 10.0.18362.959], locale et-EE)
    • Flutter version 1.21.0-6.0.pre.17 at C:\Development\flutter_master
    • Framework revision e64fe11542 (9 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.959]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

Closing this as fixed, feel free to reopen if this is not the case @gspencergoog.

**Comment by sonicseaweed** [comment]
I may have misunderstood this issue, but I would argue that this is not working. 

On an android device (emulated or physical) with a physical keyboard, hitting enter on a `TextField` will not result in focus moving to the next element, even if `maxLines: 1` and `textInputAction: TextInputAction.next`.

Further, if a `FocusScope.of(context).nextFocus()` is used on submit or on editing done, then the focus visibly shifts, however, the keyboard remains stuck in that input field and can no longer be released from it. This takes the form of typing on the keyboard brings up the virtual keyboard and text in it (autocorrect) shows up, but nothing appears in the text field, and navigation is no longer possible using the keyboard.

**Comment by gspencergoog** [comment]
I tried reproducing this, @sonicseaweed, and it appears to be fixed on the master branch, although I do see it on the current stable. You can either switch to the dev channel, or wait for the fix to propagate to the stable channel.
