### ISSUE TITLE
The first page returns to a blank page for flutter web 

### ISSUE THREAD

**Issue by StanleyCocos** [flutter/flutter#157502]
### Steps to reproduce

1. Create a blank project
2. Run into Google browser
3. Run webview_flutter example
   a. Requires iOS device
   b. setAllowsBackForwardNavigationGestures(true) must be turned on
4. Swipe sideways from the homepage

### Expected results

No gesture navigation (back)

### Actual results

back to blank page

### Code sample

<details open><summary>Code sample</summary>

```dart
if (controller.platform is WebKitWebViewController) {
      (controller.platform as WebKitWebViewController)
          .setAllowsBackForwardNavigationGestures(true);
}
```

```html
<body>
  <div style="width: 200px; height: 300px; background-color: blue;">

  </div>

  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/8249c588-8be2-4399-bd13-62e8cd88c10f

</details>

### Logs

<details open><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.94.2)
[✓] Connected device (6 available)
[✓] Network resources
• No issues found!
```

</details>

**Comment by StanleyCocos** [comment]
I have verified many times that calling canGoBack on the home page is true. This problem exists even in iOS native wkwebview. My guess is that converting flutter to html creates an extra layer of pages.

**Comment by danagbemava-nc** [comment]
Hi @StanleyCocos, this is a known issue which is being tracked in https://github.com/flutter/flutter/issues/99755

Kindly follow up in the original issue for updates

Closing from here

Thank you
