### ISSUE TITLE
Flutter Camera Plugin Example Throws Error

### ISSUE THREAD

**Issue by ezrasandzerbell** [flutter/flutter#15753]
## Steps to Reproduce

I followed the camera plugin instructions: 

Created a new flutter project. Specified the dependencies in pubspec, plist, and gradle. Replaced existing default flutter project with the Camera plugin example code (here: [https://pub.dartlang.org/packages/camera](https://pub.dartlang.org/packages/camera))

## Logs

Performing full restart...
Restarted app in 2,591ms.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following RangeError was thrown attaching to the render tree:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)
#1      _CameraAppState.initState (/Users/ezra/Library/Developer/CoreSimulator/Devices/A77CA19B-61A0-4AC4-A79E-00B5131D4975/data/Containers/Data/Application/135A9093-4F08-4AD1-B6F1-72503943B9FA/tmp/camera_apptJyPAQ/camera_app/lib/main.dart:23:46)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#6      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
#7      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
#8      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
#10     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
#11     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
#12     runApp (package:flutter/src/widgets/binding.dart:699:7)
#13     main (/Users/ezra/Library/Developer/CoreSimulator/Devices/A77CA19B-61A0-4AC4-A79E-00B5131D4975/data/Containers/Data/Application/135A9093-4F08-4AD1-B6F1-72503943B9FA/tmp/camera_apptJyPAQ/camera_app/lib/main.dart:9:3)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
════════════════════════════════════════════════════════════════════════════════════════════════════

Analyzing /Users/ezra/AndroidStudioProjects/camera_app...
No issues found!
Ran in 7.8s

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.2.1-pre.51, on Mac OS X 10.13.3 17D47, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

• No issues found!

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by ezrasandzerbell** [comment]
This issue was caused by rendering in an emulator. Same app loads fine on an actual ios device.

**Comment by matte5031** [comment]
I get the same error, so this plugin can't be used with the iOS simulator or? did you get it to work in the simulator? works on the android simulator
