### ISSUE TITLE
Reduce iOS memory

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#157573]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/8067bf83-c277-4fd2-a866-58bb07985e27)
I am working about  reducing ios memory. When I opening flutter app , there are  three IOSurface memory, and every one of them costs about 20MB memory and they altogether costs about 60MB memory
Why there are three IOSurface memory? Whether can reduce the amount of IOSurface？

### Expected results

Reduce the amount of IOSurface

### Actual results

 There are  three IOSurface memory

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter 3.22.2 
Framework • revision 761747bfc5 (4 个月前) 
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by jonahwilliams** [comment]
There are three IOSurfaces because these are the three swapchain images. We don't plan to/can't remove them
