### ISSUE TITLE
Maximizing the app restarts it in Chromebooks

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15750]
## Steps to Reproduce

1. Start a the gallery on a Chromebook and put it in non-full-screen windowed mode
2. Navigate somewhere in the app
3. Maximize the window

## Expected behavior

The app should maintain its state / route

## Actual behavior

The app restarts.

**Comment by jonahwilliams** [comment]
Related to https://github.com/flutter/flutter/issues/12588?

**Comment by tvolkert** [comment]
Sounds like it.  I'm gonna keep this open though to make sure that Chromebooks explicitly work since it's a requirement for mulligan.

**Comment by jonahwilliams** [comment]
This is fixed by adding smallestScreenSize to the config changes parameter, which was done in https://github.com/flutter/flutter/pull/43245

**Comment by edu1345dev** [comment]
Hello guys, I'm experiencing a big decrease on supported smartphone devices and after some testing I realised that by removing this smallestScreenSize from AndroidManifest would solve the problem. What about removing it from default generated AndroidManifest?
<img width="1091" alt="Screen Shot 2020-09-29 at 09 30 00" src="https://user-images.githubusercontent.com/22550246/94558580-6c190280-0236-11eb-9d60-a0a17903503a.png">

and then after removing smallestScreenSize:
<img width="1089" alt="Screen Shot 2020-09-29 at 09 31 54" src="https://user-images.githubusercontent.com/22550246/94558761-aaaebd00-0236-11eb-8fb5-236e85e0c417.png">
