### ISSUE TITLE
Status bar error

### ISSUE THREAD

**Issue by andim27** [flutter/flutter#157593]
### Steps to reproduce

Render status bar error:

1) Page_1 -> call Page_2(with white container)
2) Page_1 is showing of 2/3 of full width
3) Page_2 works good
ERROR:
Top(and bottom) status bars renders only 2/3 of full width

### Expected results

Render full width o status bar

### Actual results

Normal color of status bar on all width

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Uploa
[status_error.txt](https://github.com/user-attachments/files/17522967/status_error.txt)
d media here]
![iPhone_16_Pro_status_error](https://github.com/user-attachments/assets/5821ced6-2bea-4d70-8fc0-3b0f374dc384)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.27.0-0.1.pre 
IOS 18
flutter doctor is OK
```

</details>

**Comment by darshankawar** [comment]
@andim27 
Please provide a complete runnable reproducible code sample (ex: main.dart) that we can directly use to verify the reported behavior.

**Comment by darshankawar** [comment]
@andim27 
We would need at least minimal reproducible code sample to properly investigate and address the issue.
