### ISSUE TITLE
Hot fixes for `3.24.4` are not available

### ISSUE THREAD

**Issue by adonisRodxander** [flutter/flutter#157591]
In https://github.com/flutter/flutter/blob/stable/CHANGELOG.md we should see the new hot fixes for version `3.24.4` but actually, there is nothing

**Comment by kjxbyz** [comment]
1. Add macOS privacy manifest.

**Comment by cezaryjk** [comment]
And [CHANGELOG  ](https://docs.flutter.dev/release/release-notes)
links to 
https://github.com/flutter/flutter/blob/stable/CHANGELOG.md 
without any notes on 3.24.4

**Comment by kjxbyz** [comment]
https://github.com/flutter/flutter/blob/master/CHANGELOG.md

**Comment by danagbemava-nc** [comment]
This has now been added. 

Closing

**Comment by cezaryjk** [comment]
Hi, 
Well, I wouldn't say so... 

![2024-10-31 08_56_51-flutter_changelog](https://github.com/user-attachments/assets/a595d5df-093c-44fd-b24e-9332ae11bfaf)

**Comment by danagbemava-nc** [comment]
The changelog is present 

<img width="1091" alt="Screenshot 2024-10-31 at 1 00 06 PM" src="https://github.com/user-attachments/assets/9dcbaf15-8502-46ec-9107-930d7f043cfa">

**Comment by adonisRodxander** [comment]
@danagbemava-nc in https://github.com/flutter/flutter/blob/stable/CHANGELOG.md the changelog is not present, but in https://github.com/flutter/flutter/blob/master/CHANGELOG.md is pressent

**Comment by cezaryjk** [comment]
> The changelog is present
> <img alt="Screenshot 2024-10-31 at 1 00 06 PM" width="1091" src="https://private-user-images.githubusercontent.com/88313112/381955356-9dcbaf15-8502-46ec-9107-930d7f043cfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjUxNDcsIm5iZiI6MTczMDk2NDg0NywicGF0aCI6Ii84ODMxMzExMi8zODE5NTUzNTYtOWRjYmFmMTUtODUwMi00NmVjLTkxMDctOTMwZDdmMDQzY2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA3MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMmM0NmQyZmRjOTk5ZjEwNDlmMTQ5YzhhNGMyMGNhZTkyZDI2NWFkNmIwNGUwYTlmOTA5NWEwMzY0NWEwM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LigI9ELCGQTHqJSQPO7gt9_OxqWEL-Nl1l195FXkBwo">

Hi again, 
Yes, it is for MASTER. 
But if it is applied in STABLE, the note should be present in linked [document ](https://github.com/flutter/flutter/blob/stable/CHANGELOG.md) too. 
Especially since the official [article ](https://docs.flutter.dev/release/release-notes) leads to it... 
Guys might be a bit confused... 
BR
