### ISSUE TITLE
The "BlendMode.plus" does not work in Flutter version 3.24.3, impeller mode, under certain condition.

### ISSUE THREAD

**Issue by ginsenggo** [flutter/flutter#157508]
### Steps to reproduce

The Impeller is excellent and extremely important, thanks for the work on this. But I have a problem.

The following code, in Flutter version 3.24.3, impeller mode, "BlendMode.plus" does not work. 
Non-Impeller mode (skia) then the plus effect can work.

```dart
final paint = Paint()..blendMode = BlendMode.plus;
  if (alpha != 1) {
  paint.color = paint.color.withOpacity(alpha);
}

canvas.drawAtlas(
  spriteSheet.image,
  transforms,
  rects,
  null,
  null,
  null,
  paint,
);
```

### Expected results

"BlendMode.plus" should work for "canvas.drawAtlas" in impeller mode.

### Actual results

"BlendMode.plus" does not work for "canvas.drawAtlas" in impeller mode.

### Code sample

<details open><summary>Code sample</summary>

```dart
final paint = Paint()..blendMode = BlendMode.plus;
  if (alpha != 1) {
  paint.color = paint.color.withOpacity(alpha);
}

canvas.drawAtlas(
  spriteSheet.image,
  transforms,
  rects,
  null,
  null,
  null,
  paint,
);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.94.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@ginsenggo 
Can you provide us complete runnable code sample that shows the reported behavior ?

**Comment by ginsenggo** [comment]
> @ginsenggo Can you provide us complete runnable code sample that shows the reported behavior ?

Ok, maybe I can create an example project, but it might be complicated and take some time.
