### ISSUE TITLE
"FlutterLoader.loadEntrypoint" is deprecated and Local variable for "serviceWorkerVersion" is deprecated.

### ISSUE THREAD

**Issue by asmiralic** [flutter/flutter#157582]
### Steps to reproduce

1. Add Lottie animation to index.html.
2. Launch the app in debug mode for web (e.g., flutter run -d chrome).
3. The console shows deprecation warnings for:
4. serviceWorkerVersion
5. FlutterLoader.loadEntrypoint
6. Follow the suggestion to replace FlutterLoader.loadEntrypoint with FlutterLoader.load as per the Flutter Web documentation.
7. Try building the app for release.

### Expected results

The app should build and work as expected after replacing deprecated methods with the suggested alternatives.

### Actual results

When I replace FlutterLoader.loadEntrypoint with FlutterLoader.load, the app fails to build. However, when keeping the deprecated code, the app builds successfully, but the warnings remain.

### Code sample

```
<!DOCTYPE html>
<html>
  <head>
    <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
    <base href="$FLUTTER_BASE_HREF" />

    <meta charset="UTF-8" />
    <meta content="IE=Edge" http-equiv="X-UA-Compatible" />
    <meta name="description" content="App" />

    <!-- iOS meta tags & icons -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-title" content="example" />
    <link rel="apple-touch-icon" href="icons/Icon-192.png" />

    <!-- Facebook Meta Tags -->
    <meta
      property="og:image"
      content="https://d2036qg8j5zv6p.cloudfront.net/static/app-logo.png"
    />
    <meta property="og:title" content="app" />
    <meta
      property="og:description"
      content="
App is a self-improvement platform designed to help individuals enhance their productivity, set personal growth goals, and track progress. It provides a range of tools and resources, from personalized plans to community-driven support, all aimed at fostering development and achieving success."
    />

    <!-- Google / Search Engine Tags -->
    <meta
      itemprop="image"
      content="https://d2036qg8j5zv6p.cloudfront.net/static/app-logo.png"
    />
    <meta itemprop="title" content="App" />
    <meta
      itemprop="description"
      content="
App is a self-improvement platform designed to help individuals enhance their productivity, set personal growth goals, and track progress. It provides a range of tools and resources, from personalized plans to community-driven support, all aimed at fostering development and achieving success."
    />

    <!-- Twitter/X Meta Tags -->
    <meta
      name="twitter:card"
      content="https://d2036qg8j5zv6p.cloudfront.net/static/app-logo.png"
    />
    <meta name="twitter:title" content="App" />
    <meta
      name="twitter:description"
      content="
App is a self-improvement platform designed to help individuals enhance their productivity, set personal growth goals, and track progress. It provides a range of tools and resources, from personalized plans to community-driven support, all aimed at fostering development and achieving success."
    />
    <meta
      name="twitter:image"
      content="https://d2036qg8j5zv6p.cloudfront.net/static/app-logo.png"
    />

    <script
      src="https://cdn.jsdelivr.net/npm/hls.js@latest"
      type="application/javascript"
    ></script>
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script src="https://unpkg.com/pica/dist/pica.min.js"></script>

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="favicon.png" />

    <title>App</title>
    <link rel="stylesheet" href="splash/style.css" />
    <link rel="manifest" href="manifest.json" />

    <script>
      // The value below is injected by flutter build, do not touch.
      const serviceWorkerVersion = "{{flutter_service_worker_version}}";
    </script>
    <!-- This script adds the flutter initialization JS code -->
    <script src="flutter.js" defer></script>

    <!-- cropperjs -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.js"></script>
  </head>
  <body>
    <div id="preloader" class="preloader-container">
      <div class="animation">
        <div class="player">
          <lottie-player
            src="splash/splash.json"
            background="transparent"
            speed="1"
            style="width: 164px; height: 164px"
            autoplay
          ></lottie-player>
        </div>
      </div>
    </div>
    <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
    <script>
      var isInitialized = false;
      var isCompleted = false;
      let box = document.querySelector("#preloader");
      const animation = document.querySelector("lottie-player");

      animation.addEventListener("complete", () => {
        isCompleted = true;
        checkSplashAnimation();
      });
      animation.addEventListener("loop", () => {
        isCompleted = true;
        checkSplashAnimation();
      });

      function fadeOutSplashAnimation() {
        box.classList.add("visuallyhidden");
        box.addEventListener(
          "transitionend",
          function (e) {
            box.classList.add("hidden");
          },
          {
            capture: false,
            once: true,
            passive: false,
          }
        );
      }

      function removeSplashAnimation() {
        box.classList.add("hidden");
      }

      function checkSplashAnimation() {
        if (!isCompleted) {
          return;
        }
        if (!isInitialized) {
          return;
        }
        removeSplashAnimation();
      }

      window.addEventListener("load", function (ev) {
        // Download main.dart.js
        _flutter.loader
          .load({
            serviceWorkerVersion: serviceWorkerVersion,
          })
          .then(function (engineInitializer) {
            engineInitializer
              .initializeEngine({ useColorEmoji: true })
              .then(async function (appRunner) {
                await appRunner.runApp();
                isInitialized = true;
                checkSplashAnimation();
              });
          })
          .catch(function (error) {
            console.error('Error during Flutter initialization:', error);
          });
      });
    </script>
  </body>
</html>
```

### Screenshots or Video

![Screenshot 2024-10-25 at 10 06 48](https://github.com/user-attachments/assets/861f7bda-78cf-477c-a021-57e2f357377b)

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-BA)
    • Flutter version 3.24.3 on channel stable at /Users/asmiralic/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/asmiralic/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • QUAD CORE A133 c3 (mobile)      • 10.40.3.68:5555           • android-arm    • Android 10 (API 29)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
Thanks for the report @asmiralic 





> 1. Add Lottie animation to index.html.

Does the reported error occur without this step ? Or just using the default index.html that Flutter generates ?

**Comment by asmiralic** [comment]
With default index.html that Flutter generates error does not occur.

**Comment by darshankawar** [comment]
Thanks for the update. Seeing the same behavior upon following steps to replicate and code sample provided.

```
stable : 3.24.3
master : 3.27.0-1.0.pre.231
```

**Comment by eyebrowsoffire** [comment]
@asmiralic You need to add the `{{flutter_build_config}}` template token into your `index.html` or `flutter_bootstrap.js` file for the flutter tool to inject some build information. There is some information documented here: https://docs.flutter.dev/platform-integration/web/initialization#customize-initialization

**Comment by asmiralic** [comment]
I appreciate your help @eyebrowsoffire. I followed the documentation you provided, but I still have an issue, the loader stays on the browser and I can not access my app.

This is an updated index.html with added template token:
`<!DOCTYPE html>
<html>
  <head>
    <base href="$FLUTTER_BASE_HREF" />

    <meta charset="UTF-8" />
    <meta content="IE=Edge" http-equiv="X-UA-Compatible" />
    <meta name="description" content="A new Flutter project." />

    
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-title" content="example" />
    <link rel="apple-touch-icon" href="icons/Icon-192.png" />

    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@latest" type="application/javascript"></script>

    
    <link rel="icon" type="image/png" href="favicon.png" />

    <title>Flutter Web Console Template</title>
    <link rel="stylesheet" href="splash/style.css" />
    <link rel="manifest" href="manifest.json" />

    <script>
      // Updated to use the recommended template token
      const serviceWorkerVersion = "{{flutter_service_worker_version}}";
    </script>
    
    <script src="flutter.js" defer></script>
  </head>
  <body>
    <div id="preloader" class="preloader-container">
      <div class="animation">
        <div class="player">
          <lottie-player
            src="splash/splash.json"
            background="transparent"
            speed="1"
            style="width: 200px; height: 200px"
            autoplay
          ></lottie-player>
        </div>
      </div>
    </div>

    <script>
      {{flutter_js}}
      {{flutter_build_config}}
      
      var isInitialized = false;
      var isCompleted = false;
      let box = document.querySelector("#preloader");
      const animation = document.querySelector("lottie-player");

      animation.addEventListener("complete", () => {
        isCompleted = true;
        checkSplashAnimation();
      });
      animation.addEventListener("loop", () => {
        isCompleted = true;
        checkSplashAnimation();
      });

      function fadeOutSplashAnimation() {
        box.classList.add("visuallyhidden");
        box.addEventListener(
          "transitionend",
          function (e) {
            box.classList.add("hidden");
          },
          {
            capture: false,
            once: true,
            passive: false,
          }
        );
      }

      function removeSplashAnimation() {
        box.classList.add("hidden");
      }

      function checkSplashAnimation() {
        if (!isCompleted) {
          return;
        }
        if (!isInitialized) {
          return;
        }
        removeSplashAnimation();
      }

      window.addEventListener("load", function (ev) {
        // Updated to use the new FlutterLoader.load method
        _flutter.loader
          .load({
            serviceWorker: {
              serviceWorkerVersion: serviceWorkerVersion,
            },
          })
          .then(function (engineInitializer) {
            engineInitializer.initializeEngine().then(async function (appRunner) {
              await appRunner.runApp();
              isInitialized = true;
              checkSplashAnimation();
            });
          });
      });
    </script>
  </body>
</html>
`

**Comment by asmiralic** [comment]
Thank you so mutch for your time and effort, I SOLVED this issue following your's instruction. I will separate js script in another file, but for easier reading I will provide my index.html that is working now:

`<!DOCTYPE html>
<html>
  <head>
    <base href="$FLUTTER_BASE_HREF" />

    <meta charset="UTF-8" />
    <meta content="IE=Edge" http-equiv="X-UA-Compatible" />
    <meta name="description" content="Brainbow admin console" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-title" content="example" />
    <link rel="apple-touch-icon" href="icons/Icon-192.png" />

    
    <meta property="og:image" content="https://d2036qg8j5zv6p.cloudfront.net/static/brainbow-logo.png">
    <meta property="og:title" content="Brainbow admin console">
    <meta name="twitter:card" content="https://d2036qg8j5zv6p.cloudfront.net/static/brainbow-logo.png">

    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <link rel="icon" type="image/png" href="favicon.png" />
    <title>Brainbow Admin Console</title>
    <link rel="stylesheet" href="splash/style.css" />
    <link rel="manifest" href="manifest.json" />
  </head>
  <body>
    <div id="preloader" class="preloader-container">
      <div class="animation">
        <div class="player">
          <lottie-player
            src="splash/splash.json"
            background="transparent"
            speed="1"
            style="width: 200px; height: 200px"
            autoplay
          ></lottie-player>
        </div>
      </div>
    </div>
    <script>
      var isInitialized = false;
      var isCompleted = false;
      const box = document.querySelector("#preloader");
      const animation = document.querySelector("lottie-player");

      animation.addEventListener("complete", () => {
        isCompleted = true;
        checkSplashAnimation();
      });

      function removeSplashAnimation() {
        box.classList.add("hidden");
      }

      function checkSplashAnimation() {
        if (isCompleted && isInitialized) {
          removeSplashAnimation();
        }
      }

      {{flutter_js}}
      {{flutter_build_config}}


      // Flutter initialization
      _flutter.loader.load({
        onEntrypointLoaded: (engineInitializer) => {
          engineInitializer.initializeEngine().then(async (appRunner) => {
            await appRunner.runApp();
            isInitialized = true;
            checkSplashAnimation();
          });
        },
      });
    </script>
  </body>
</html>
`

**Comment by eyebrowsoffire** [comment]
Awesome! Happy to help. I'll go ahead and close this ticket then.
