### ISSUE TITLE
Mouse pointer does not change into a caret while over a text field

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#15755]
... when using a mouse.

**Comment by tvolkert** [comment]
Note for Chromebook compatibility: this is an L2 requirement.

**Comment by zoechi** [comment]
Related to #757

**Comment by goderbauer** [comment]
@gspencergoog FYI

**Comment by dkwingsmt** [comment]
I don't get what the "caret" stands for.
I assume it's talking about mouse cursors changing into the "I-beam" cursor, which should have been fixed. 
@tvolkert Can you confirm or further illustrate?

**Comment by tvolkert** [comment]
Yep, it means the mouse cursor changing into an "I-beam" cursor when the mouse is moved over text.
