### ISSUE TITLE
[go_router] Add a way to prevent navigation

### ISSUE THREAD

**Issue by rMozes** [flutter/flutter#157598]
### Use case

I have a scenario where I want to prevent navigation from Screen A to Screen B under certain conditions. While I can implement a partial solution using redirect by checking the condition and, if true, returning the current route, this approach only works correctly when using go or goNamed. However, it doesn't work as expected with pushNamed.

With pushNamed, returning the current route in redirect results in the same screen being stacked on top of itself. This createsan issue where, upon pressing the back button, the user is brought back to the same screen repeatedly.

### Proposal

I would like to request a feature that enables us to prevent a navigation event from occurring. Currently, the redirect API provides a way to intercept navigation and redirect to another screen, but there is no straightforward way to entirely block a navigation action based on specific conditions from a centralized place.
I propose adding a way to centrally block a navigation attempt based on conditions, without needing to redirect or modify the navigation stack, regardless of whether go, goNamed, or pushNamed is used. This feature would allow for cleaner handling of navigation prevention without creating back-navigation loops.

**Comment by darshankawar** [comment]
@rMozes 
Can you check below issues to see if they resemble your case or not ?

https://github.com/flutter/flutter/issues/134013
https://github.com/flutter/flutter/issues/140794
https://github.com/flutter/flutter/issues/145290
https://github.com/flutter/flutter/issues/146578
https://github.com/flutter/flutter/issues/155635
