### ISSUE TITLE
Some very popular devices are excluded by rule on Android when building an AppBundle

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#157589]
### Steps to reproduce

I have already released several apps on the Google Play Store using Flutter. 
I always build with : 

`flutter build appbundle --obfuscate --release --split-debug-info=/Users/foxtom/StudioProjects/myproject/build --build-name=1.0.0 --build-number=1`

And when i release my app, always the same devices (more or less 30) are `excluded by rule` in the Device Catalog.

Since the Google Play Support told me that they can't help with this issue because it comes from my configuration, i am raising an issue here.

You can find all the details on my [SO](https://stackoverflow.com/questions/79125299/flutter-app-some-devices-are-excluded-by-rule-in-google-play-console) post to avoid duplicating here. 

I am raising an issue here in case there is an actual Flutter bug because some of the most popular Android phones seem to not be supported by my Android app.

Note : To replicate the issue, you can simply copy past most of my `manifest configuration` and `build.gradle` files in a new project and build the obfuscated `appbundle` with the above command if the issue doesn't depend on dependencies. 

### Expected results

The devices that respects the `build.gradle` configuration + hardware requirements from the app's manifest file should not be `excluded by rule` in the Google Play Device catalog.

### Actual results

Some devices that respects the `build.gradle` configuration + hardware requirements from the app's manifest file are `excluded by rule` anyway. 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-x64, locale fr-FR)
    • Flutter version 3.24.3 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 15.0.1 24A348 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 130.0.6723.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Tom3652 
Please take a look at https://support.google.com/googleplay/android-developer/answer/7353455?hl=en to see if it helps to know as why it could be happening.

**Comment by Tom3652** [comment]
I have seen it @darshankawar and it's where i come from since i have a case with Google Play Support that was closed yesterday.

I am raising this issue because Google Play Support said the device exclusion is coming from my app's manifest and gradle configuration for release and they can't provide additional technical support.
 
Since i am using a very basic configuration with just 1 permission and a `minSdkVersion: 23` and `maxSdkVersion: 35` , there is absolutely nothing on my configuration that is excluding the Redmi Note 8 under Android 12 (SDK 31). 

That's why i think there is an issue here either from Flutter's Android configuration itself or with some hidden component i am not aware of...

**Comment by darshankawar** [comment]
@Tom3652 
Try [this](https://github.com/flutter/flutter/issues/111987#issuecomment-1254040309) to see if it helps in your case as well or not.

**Comment by Tom3652** [comment]
Hi @darshankawar it is a very different case since : 

1. I have no issues installing my app on any of my devices from internal testing or Google Play Store production. I have never encountered myself the message of incompatible device.

2. I have not one of the very popular phones that are excluded by rule to test on it.

3. This bug happens on my live users and not on tester accounts, they can't install the new app if they have a phone excluded by rule.q

I am really guessing there is an underlying issue, maybe not with Flutter but since Google Play Support said so indirectly as mentioned before it's worth investigating.

Note : the same 30 devices are excluded by rule on my 4 released apps on 4 different accounts and all my apps have been released in the same way using flutter for the same target range of Android SDKs.

**Comment by darshankawar** [comment]
Thanks for the update @Tom3652 and for your patience while we try to figure this out, because we haven't seen such issues earlier.

Per your SO post, I see that you have `compileSdk 35` so could it be that it may be higher sdk for some of the devices ? Also, need to check if the abi arch could be conflicting with the devices such as in SO post screenshot, I see `arm64-v8a` but the aap bundle generated may be having different abi arch ?

**Comment by Tom3652** [comment]
Hi @darshankawar no problem, the goal is to understand what is going on here.
Please see the screenshot of my app bundle : 

<img width="582" alt="Capture d’écran 2024-10-30 à 08 36 50" src="https://github.com/user-attachments/assets/f47e8975-066e-4322-8896-a6aa783ff8b4">

And the permissions / features : 

<img width="893" alt="Capture d’écran 2024-10-30 à 08 36 16" src="https://github.com/user-attachments/assets/b173f837-4898-4657-9dc4-54b0db1c5a51">

I am seeing that it uses `android.hardware.faketouch` but i am not sure if this is the [problem](https://stackoverflow.com/questions/6528167/uses-feature-android-hardware-faketouch) since it seems most of new phones today have a touch screen...

**Comment by huycozy** [comment]
Thanks for the update, @Tom3652. I can see your app bundle included all default abi(s) per https://docs.flutter.dev/deployment/android#build-an-app-bundle.

My last question: Can you please share the list of 30 devices that are excluded here? And are you noticing this issue recently with your Flutter version `3.24.3`, or has it been around for a while on previous Flutter versions?

**Comment by Tom3652** [comment]
Hi @huycozy thanks for the reply, yes indeed i have seen the documentation you show and i am using the default Flutter Behavior.
Yes indeed i am using Flutter `3.24.3` in my latest release. 

Here is the list of the devices : [devices_excluded_google_play.csv](https://github.com/user-attachments/files/17583329/devices_excluded_google_play.csv)

Please let me add some explanations : 
1. There are 46 devices excluded in total 
2. There are 11 devices excluded by "No Opt-In" and when i check these devices, it is written the real reason of why they are excluded such as for example : 

<img width="839" alt="Capture d’écran 2024-10-31 à 08 13 58" src="https://github.com/user-attachments/assets/be68decd-3a0d-4302-8bab-2f5c25299dae">

3. So there are 35 devices excluded by Rule that show no reason at all but 11 excluded because of the hardware requirements not found (which is fine). 

The weirdest thing is that on the 2 first devices, i have an install base of 1 despite it is excluded :

<img width="1432" alt="Capture d’écran 2024-10-31 à 08 15 00" src="https://github.com/user-attachments/assets/e3a69f64-6718-4752-906b-89cdd0e14f32">

I have received few mails from my users with the `Xiaomi ginkgo` telling me they have a message on the Play Store "Your device is not compatible with the app" or something like this.

Thanks for your help on this !

**Comment by huycozy** [comment]
Thanks for sharing it. Labeling the issue for input from android team.

**Comment by Tom3652** [comment]
Hi @huycozy this issue is closed, this was entirely a Play Integrity issue despite the Google sentence : 

![Capture d’écran 2024-11-06 à 15 14 06](https://github.com/user-attachments/assets/5de67120-0648-4bd5-902f-dea087e48069)

It is wrong, when i have lowered the Play Integrity settings to "Basic integrity checks" instead of the recommended ones, it didn't exclude any devices.
