### ISSUE TITLE
iOS build fails with 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by banool** [flutter/flutter#157694]
### Steps to reproduce

1. Clone https://github.com/banool/auslan_dictionary
2. Check out this PR: https://github.com/banool/auslan_dictionary/pull/209
3. `flutter run`

### Actual results

I can't build or run the ios build. The Android version of the app builds fine (as you can see from the CI in the PR above).

I have tried everything I've read online, various hacks with Podfile to set the target IOS deployment target (of the app and its dependencies, and I've tried many different versions like 12, 13, 16, etc), exclude simulation targets, etc. I have tried reinstalling flutter from scratch, I've tried the latest stable and main versions of flutter. I confirmed that the build settings in Xcode look correct (correct order, "for install builds only" unticked). I have reinstalled various versions of ruby, cocoapods, XCode, etc. I've cleaned every cache I can find in every permutation. I have tried deleting the `ios` folder and regenerating it. Deleting various generated files in the `ios/Flutter` directory. Pretty much anything that pops up from searching for this error on Google, you name it (definitely everything here and in a few other posts: https://stackoverflow.com/q/64973346/3846032). Even things that I wouldn't expect to work, like building using the Flutter extension from Android studio.

I have updated every dependency to the latest, including across major version boundaries, and transitively via that dictionarylib dep.

The error message tends to change, but I think it's related to any dependency that requires a platform integration (so some pod gets installed), e.g. sqflite, http_proxy, the splash page package, device_info_plus, package_info_plus, etc.

Worth noting that this app used to build fine, but is now failing on the latest version of Flutter / XCode / etc. I can't quite tell which thing broke it.

### Logs

The verbose output is too long for an issue, you can find it in this gist: https://gist.github.com/banool/32c02eaf030a56d8477be5697acb0260.

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Users/dport/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dport/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

⣷^⣟[✓] Connected device (5 available)
    • Daniel iPhone (mobile)          • 00008110-001270480A0B801E            • ios            • iOS 18.0.1 22A3370
    • iPhone 15 Pro Max (mobile)      • 85EDB580-EEF0-4F6E-B721-2A6BA72B46E7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 130.0.6723.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by berbsd** [comment]
same issue for me - my older builds from 24h ago are now failing as well.

**Comment by ekasetiawans** [comment]
I'm facing this issue too.
Adding `config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'` in Podfile didn't help

**Comment by ekasetiawans** [comment]
I have successfully build my app, just remove cocoapods and reinstall cocoapods using homebrew.

**Comment by banool** [comment]
Well I'll be damned, the solution was indeed to install cocoapods with brew instead of gem:
```
sudo gem uninstall cocoapods
brew install cocoapods
```

**Comment by vanyasem** [comment]
@banool wow, that actually worked - I reinstalled cocoapods via homebrew and it compiled on the first attemp

I had the latest version of `cocoapods` installed via non-system `ruby@3.2.2` managed globally by [mise](https://github.com/jdx/mise). I have been using this setup for years, and this is the first time I've encountered any kind of issue with it. I wonder what could be the reason for this issue to appear out of nowhere

**Comment by adnit** [comment]
Still work for me

**Comment by adnit** [comment]
@banool do you mind reopening the issue, I have the exact issue as you did but the fix doesn't work for me

**Comment by adnit** [comment]
Adding my build logs here:

`Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running pod install...                                           1,856ms
Running Xcode build...                                                  
Xcode build done.                                           151.6s
Failed to build iOS app
Error (Xcode): double-quoted include "SqfliteImportPublic.h" in framework header, expected angle-bracketed instead
/Users/adnitkamberi/Documents/GitHub/blue-esim/blue_esim_flutter/ios/Pods/Target%20Support%20Files/sqflite_darwin/sqflite_darwin-umbrella.h:12:8


Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/adnitkamberi/.pub-cache/hosted/pub.dev/sqflite_darwin-2.4.1-1/darwin/sqflite_darwin/Sources/sqflite_darwin/include/sqflite_darwin/SqfliteImportPublic.h:14:8


Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c++_arm64-apple-ios12.0-simulator_gnu++20/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c++_arm64-apple-ios12.0-simulator_gnu++20/Test/Test.mm:0:8


Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c++_x86_64-apple-ios12.0-simulator_gnu++20/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c++_x86_64-apple-ios12.0-simulator_gnu++20/Test/Test.mm:0:8


Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c_arm64-apple-ios12.0-simulator_gnu17/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c_arm64-apple-ios12.0-simulator_gnu17/Test/Test.m:0:8


Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c_x86_64-apple-ios12.0-simulator_gnu17/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c_x86_64-apple-ios12.0-simulator_gnu17/Test/Test.m:0:8


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.`

**Comment by adnit** [comment]
```adnitkamberi@Adnits-Mac-mini ~ % pod --version
1.15.2 

adnitkamberi@Adnits-Mac-mini ~ % ruby --version
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]

adnitkamberi@Adnits-Mac-mini ~ % where ruby         
/opt/homebrew/opt/ruby/bin/ruby
/usr/bin/ruby

adnitkamberi@Adnits-Mac-mini ~ % where pod          
/opt/homebrew/bin/pod```

I am running macOS 15.0.1, Xcode 16.0, flutter stable channel

```adnitkamberi@Adnits-Mac-mini ~ % flutter --version
Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (4 days ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3```

My Podfile is like this:

```# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by berbsd** [comment]
I realized that the issue only happens when I build the ipa with --release, --dev and --profile work without any problem.  I attached flutter doctor output and error below. Interestingly, the problem occurred on Sunday and I was not able to even trigger older builds off GitHub after that.  Would love to understand root cause and certainly looking forward to a fix. 

```
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.95.0-insider)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

```
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Archiving ...
Running pod install...                                              4.9s
Running Xcode build...                                                  
Xcode archive done.                                         273.0s
Failed to build iOS app
Error (Xcode): double-quoted include "SmartAuthPlugin.h" in framework header, expected angle-bracketed instead
/Users/david/development/mobile_app/ios/Pods/Target%20Support%20Files/smart_auth/smart_auth-umbrella.h:12:8

Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/david/.pub-cache/hosted/pub.dev/smart_auth-2.0.0/ios/Classes/SmartAuthPlugin.h:0:8

Error (Xcode): (fatal) could not build module 'smart_auth'
/Users/david/Library/Developer/Xcode/DerivedData/Runner-aknjobheqjstsiavbbyipmgzkiup/Build/Intermediates.noindex/ArchiveIntermediates/dev/IntermediateBuildFilesPath/Pods.build
/Release-dev-iphoneos/smart_auth.build/VerifyModule/smart_auth_objective-c++_arm64-apple-ios16.0_gnu++20/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/david/Library/Developer/Xcode/DerivedData/Runner-aknjobheqjstsiavbbyipmgzkiup/Build/Intermediates.noindex/ArchiveIntermediates/dev/IntermediateBuildFilesPath/Pods.build
/Release-dev-iphoneos/smart_auth.build/VerifyModule/smart_auth_objective-c++_arm64-apple-ios16.0_gnu++20/Test/Test.mm:0:8

Error (Xcode): (fatal) could not build module 'smart_auth'
/Users/david/Library/Developer/Xcode/DerivedData/Runner-aknjobheqjstsiavbbyipmgzkiup/Build/Intermediates.noindex/ArchiveIntermediates/dev/IntermediateBuildFilesPath/Pods.build
/Release-dev-iphoneos/smart_auth.build/VerifyModule/smart_auth_objective-c_arm64-apple-ios16.0_gnu17/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/david/Library/Developer/Xcode/DerivedData/Runner-aknjobheqjstsiavbbyipmgzkiup/Build/Intermediates.noindex/ArchiveIntermediates/dev/IntermediateBuildFilesPath/Pods.build
/Release-dev-iphoneos/smart_auth.build/VerifyModule/smart_auth_objective-c_arm64-apple-ios16.0_gnu17/Test/Test.m:0:8


Encountered error while archiving for device.```

**Comment by klaussk8** [comment]
Same problem... I tried a lot of things here... I also reinstalled cocoapods using brew... macos using Sonoma with Intel.
I reinstalled flutter, I have create an entire new project, just added sqflite lib, and same problem... missing Flutter/Flutter.h file

**Comment by kishormainali** [comment]
@klaussk8 try following

1. check xcodeproj version

```sh xcodeproj --version```

2. if it is 1.26.* then uninstall and install version 1.25.0
```sh gem uninstall xcodeproj ```
```sh gem install xcodeproj  --version=1.25.0" ```

**Comment by colonal** [comment]
I have successfully build my app, removed cocoapods, and reinstall cocoapods 1.16.0v

```
sudo gem uninstall cocoapods
brew uninstall cocoapods
sudo gem install cocoapods
```
then clear cache data

```
sudo rm -rf ~/Library/Developer/Xcode/DerivedData/; sudo rm -rf ~/Library/Caches/CocoaPods/
rm ios/Podfile.lock
rm -rf ios/.symlinks
rm -rf ios/Pods
flutter clean
flutter pub get
cd ios
pod deintegrate && pod install --repo-update
```
finally
```
flutter build ios --release
```
I hope this helps you. 🥳

pod version: 1.16.0
ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-darwin23]
Xcode version: 15.4
Flutter version:
Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (5 days ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

**Comment by adnit** [comment]
> @klaussk8 try following
> 
> 1. check xcodeproj version
> 
> ``` xcodeproj --version```
> 
> 2. if it is 1.26.* then uninstall and install version 1.25.0
> ``` gem uninstall xcodeproj ```
> ```gem install xcodeproj  --version=1.25.0" ```

Okay this did it

**Comment by klaussk8** [comment]
> 2\. gem install xcodeproj  --version=1.25.0"

Thank you so much!

I initially had version 1.26 installed, but I removed all RVM versions to downgrade to 1.25. After doing this, xcodeproj --version correctly shows 1.25. I also tested by creating a new empty project, which worked perfectly. Then, I added the necessary sqflite library to the dependencies, and it installed without issues!

I did encounter some problems with the CocoaPods repo update in my main project, but after resolving that, everything is working, and I can run my project again! Thanks again for the help!

**Comment by klaussk8** [comment]
> @klaussk8 try following
> 
> 1. check xcodeproj version
> 
> ` xcodeproj --version`
> 
> 2. if it is 1.26.* then uninstall and install version 1.25.0
>    `gem uninstall xcodeproj`
>    `gem install xcodeproj  --version=1.25.0" `

Thank you so much!

I initially had version 1.26 installed, but I removed all RVM versions to downgrade to 1.25. After doing this, xcodeproj --version correctly shows 1.25. I also tested by creating a new empty project, which worked perfectly. Then, I added the necessary sqflite library to the dependencies, and it installed without issues!

I did encounter some problems with the CocoaPods repo update in my main project, but after resolving that, everything is working, and I can run my project again! Thanks again for the help!

**Comment by anthonyhunter** [comment]
Xcode version 16.1 was my problem.

This worked for me.
- Xcode 15.4 (Xcode CLT 16.0 or 16.1 did not work)
- Pod 1.16.1
- xcodeproj 1.26.0
- cocoapods 1.16.1

and clearing cache as described above https://github.com/flutter/flutter/issues/157694#issuecomment-2443321940
