### ISSUE TITLE
`ImageFilter.blur` Causes Artifacts on Android, iOS, and macOS but Not on Web

### ISSUE THREAD

**Issue by tech-andgar** [flutter/flutter#157693]
### Steps to reproduce

1. **Create a new Flutter project** or use an existing one.
2. **Replace the `main.dart`** with the code sample provided below.
3. **Run the app** on an Android, iOS, or macOS device/emulator.
4. **Observe the blurred circle** in the center of the screen.
5. **Notice the visual artifacts**, such as a horizontal and vertical line through the circle.
6. **Run the same app on the web platform** (e.g., using `flutter run -d chrome`).
7. **Observe that the blurred circle renders correctly** without any artifacts.

### Expected results

The blurred circle should render smoothly without any visual artifacts on all platforms, similar to how it appears on the web.

### Actual results

- On **Android, iOS, and macOS**, the blurred circle shows visual artifacts, such as a horizontal line through the center.
- On the **web platform**, the blurred circle renders correctly without any artifacts.

### Code sample

<details open><summary>Code sample</summary>

[Live code](https://dartpad.dev/?id=37f804cc1ba1893717234ccea063a112)

```dart
import 'dart:ui';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: BlurredCircle(),
      ),
    ),
  ));
}

class BlurredCircle extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ImageFiltered(
      imageFilter: ImageFilter.blur(sigmaX: 20, sigmaY: 20),
      child: Container(
        width: 200,
        height: 200,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          color: Colors.black.withOpacity(0.4),
        ),
      ),
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
<img width="1956" alt="Screenshot 2024-10-27 at 1 14 16 PM" src="https://github.com/user-attachments/assets/077fc9ca-ce92-4fd1-9fe2-f18011e98769">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B82 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/andgar2010/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (7 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/[username]/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16B5029d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Connected device (7 available)
    • sdk gphone64 arm64 (mobile)         • emulator-5554                        • android-arm64  • Android 15 (API 35) (emulator)
    • iPhone SE (3rd generation) (mobile) • 1DBE318D-CB40-4F0E-AD86-6EDBEA717FE1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • iPad Pro 13-inch (M4) (mobile)      • 39552C9A-8554-4733-968E-E3515A5634A5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 15.1 24B82 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 15.1 24B82 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 132.0.6801.0 canary

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Additional Information:**

- The issue seems to occur when applying `ImageFilter.blur` to a **solid color** `Container` or shape.
- The problem does **not occur** when using `ImageFilter.blur` on images or widgets with varying pixel data.
- This suggests that the blur filter might not be handling solid colors correctly on certain platforms.
- The issue might be related to the rendering engines **Impeller** and **Skia** on these platforms.
- The problem persists across different devices and emulator configurations.

**Workaround:**

A possible workaround is to simulate the blur effect using a `BoxShadow` on a transparent `Container` instead of using `ImageFilter.blur`.

**Workaround Code Example:**

```dart
Container(
  width: 200,
  height: 200,
  decoration: BoxDecoration(
    shape: BoxShape.circle,
    color: Colors.transparent, // Fully transparent color
    boxShadow: [
      BoxShadow(
        color: Colors.black.withOpacity(0.4),
        blurRadius: 20,
        spreadRadius: 0,
      ),
    ],
  ),
),
```
![Screenshot 2024-10-27 at 1 24 15 PM](https://github.com/user-attachments/assets/6e81e7df-e42d-4aed-b69d-587f9cb99b53)

**Logs:**

No specific error logs are produced when this issue occurs.

**Potential Impact:**

- Developers relying on `ImageFilter.blur` for UI effects may encounter unexpected visual artifacts.
- This affects the visual consistency of apps across different platforms.

**Comment by jonahwilliams** [comment]
This is working as expected. What you want is to use TileMode.decal as an argument to your image filter instead of the default clamp. We plan to change the default in a future release of flutter.

**Comment by tech-andgar** [comment]
I have tried to change the value of the `tileMode` parameter to `TileMode.decal` in `ImageFilter.blur`, and now it works correctly without the visual artifacts. 
<img width="1027" alt="Screenshot 2024-10-27 at 1 35 12 PM" src="https://github.com/user-attachments/assets/99eaf43f-4a2c-4ebd-b4b1-826d22b273a8">

Thank you very much for your help and clarification. 
I hope that in future versions the default value will be changed to avoid this problem.

Thank you again!
