### ISSUE TITLE
improve the help message from flutter run

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#15762]
When an app is running, typing `h` on the console will display help for the other keybindings. This help is unstructured and has grown a bit large. We should address, and add some structure (now that it's a bit larger than works for a flat list). Some work in that direction - that may prove useful for future efforts - in this closed PR: https://github.com/flutter/flutter/pull/14651.

**Comment by zanderso** [comment]
Addressed by https://github.com/flutter/flutter/commit/23ce192a8f37ae00af12c510fd103b70405e7a3d
