### ISSUE TITLE
[impeller] disable gradient dithering when using high bitrate pixel format

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#157645]
In shaders like the `linear_gradient_ssbo_fill.frag` dithering is happening at the end.  When we are using wide gamut support on iOS which uses a high bitrate pixel format this is unnecessary since banding is imperceptible at this point.  We should avoid the extra calculations and disable dithering.

Although, this would cause a new shader to have to be made which does incur a cost as well.

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
wide gamut adds more colors at the ends of the gamut, and the higher bit depth is nice - but gradient banding is caused by a linerar interpolation through a color space that isn't actually linear. For example, a gradient between shades of grey should still show banding.

**Comment by gaaclarke** [comment]
That's not quite how it works, the extra 2 bits per color component in MTLPixelFormatBGRA10_XR aren't just allocated to the extra space at the end of the gamut, they are distributed evenly across the whole gamut.  That means when using MTLPixelFormatBGRA10_XR, for `Color(0xff000000)` and `Color(0xff000001)` there are values between them.

The pixel format goes from [-0.752941, 1.25098], so each step in a color component is worth (1.25098 - -0.752941) / 2^10 = 0.001956954102.  Whereas with with MTLPixelFormatRGBA8Unorm, it goes from [0, 1] so each step is worth 1/2^8 = 0.00390625.  That's twice as many representable values across one color component.  I don't believe you can see the banding at that level.

I remember apples documentation having images but I couldn't find it.  It's probably easiest just to test it out to demonstrate.

**Comment by jonahwilliams** [comment]
You can use a specialization constant to conditionally disable this based on the surface format without adding new shaders

**Comment by gaaclarke** [comment]
I was thinking about this a bit and the only device we could do this for would be iOS because for things like desktop the gpu might support high bitrate color formats but the display might not.  So maybe turning off dithering may be more complicated and not worth the effort.

**Comment by jonahwilliams** [comment]
I'll close for now then
