### ISSUE TITLE
Visual Code is unable to locate the Flutter SDK

### ISSUE THREAD

**Issue by hcpsneyvelip** [flutter/flutter#15766]
## Flutter Doctor

There is nothing wrong here all dependencies have been fulfilled 

```
Warning: the 'flutter' tool you are currently running is not the one from the current directory:
  running Flutter  : /Users/pranavneyveli/flutter/flutter
  current directory: /Users/pranavneyveli/flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify
that you're running the expected version (run 'flutter --version' to see which flutter is on your path).

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.2 17C88, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✗] Android Studio (not installed)
[✓] VS Code (version 1.21.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
Pranavs-Air:flutter pranavneyveli$ 
```

**Comment by InMatrix** [comment]
It looks like you have a copy of Flutter in `/Users/pranavneyveli/flutter/flutter` and another copy in `/Users/pranavneyveli/flutter`. If that's the case, I'd delete `/Users/pranavneyveli/flutter/flutter` and make sure `/Users/pranavneyveli/flutter/bin` is in your PATH.

**Comment by hcpsneyvelip** [comment]
Thank you for your kind reply, how would I go about deleting the one in /Users/pranavneyveli/flutter/flutter and how would I set the other one as my path sir? I did that on VS code and it is not working sir.

Have a good night!
Pranav Neyveli.

**Comment by InMatrix** [comment]
Cc: @DanTup who might have more insights into how this happened (and worked out). Glad Flutter now works for you.

**Comment by DanTup** [comment]
@hcpsneyvelip I think @InMatrix's comment is correct - seems like you have two versions of flutter and the one in your path was likely the parent one. I would try to resolve that to avoid complications in future (for example with upgrades).

The settings you mention aren't required in VS Code unless it can't find Flutter on your `PATH`. I would get down to one version, add it to `PATH` and then delete those options to see if it's detected automatically. If not, it'll give you a `Locate SDK` button that'll let you select it from a folder picker.

**Comment by hcpsneyvelip** [comment]
@InMatrix @DanTup  That is all good sir, but how would I change the path to avoid those complications, again very new to the terminal stuff, not many tutorials online for flutter as it is new.

**Comment by DanTup** [comment]
@hcpsneyvelip If you're on a Mac, you could add them to `/etc/paths`. I edited mine with `wudo nano /etc/paths` and then added `~/Dev/Google/flutter/bin` to the end of the file (note: may require a reboot).

With that done, you should be able to open a terminal and run `flutter doctor` and it'll work (without you needing to run it explicitly from the bin folder with a path). Hopefully then VS Code will also find it automatically.

**Comment by hcpsneyvelip** [comment]
@DanTup yes good point sir, I had to keep going and cloning the git to even run flutter doctor. Although it runs smoothly on vs code and is amazing and love it.

**Comment by bpavan1** [comment]
![Unable to locate Android SDK ](https://i.imgur.com/8tyQvt3.jpg)

**Comment by zoechi** [comment]
@bpavan1 like https://stackoverflow.com/questions/54035572/unable-to-locate-the-android-sdk-flutter
