### ISSUE TITLE
[vector_graphics] review package API and publish new versions.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#157626]
Format stability has been achieved mostly via not changing the API for N years. Document this explicitly and declare the package 1.0

**Comment by stuartmorgan** [comment]
> and declare the package 1.0

That will be tricky since they are all on `1.1.11+1` :)

**Comment by jonahwilliams** [comment]
well, something like that :)

1.5!

**Comment by stuartmorgan** [comment]
Capturing from offline discussion to provide more context here: in the past, `vector_graphics*` has use exact, pinned dependencies between the different versions, and special release logic that ensures they are all published in dependency order. Both of these would require a bunch of custom work in our repo, and it sounds like we don't need that level of tight coupling any more.

For now I'm importing with almost-exactly-pinned versions (allowing both the last pre-import and the first post-import version, but nothing else) to preserve existing behavior, with comments referencing this issue in the pubspec, but very soon we should replace those contraints with something based on the plan going forward. My strong preference would be to apply semver, as even setting aside the tooling aspects, having a small number of packages in a repo with many, many other packages that follows weird special rules that anyone touching the package has to know about is a significant maintenance burden.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/packages/pull/7991 changed the version of only one package, so things are now mis-aligned. If the solution doesn't end up being to use semver, that will need to be addressed.
