### ISSUE TITLE
What is the best way to freeze an input form while saving

### ISSUE THREAD

**Issue by zhenqiu1101** [flutter/flutter#15768]
Hi Flutter team,

We have a FR that after user filled in a form and hit submit, we show a loading indicator in the middle and prevent users from inputting until the form is successfully saved.

I tried to implement this by pushing another transparent route on the top of the form which could prevent user input. But it turns black after 1 sec or 2. I guess the reason is the underlying page didn't get repaint. 

I also played around with https://docs.flutter.io/flutter/widgets/PageRoute/opaque.html field. But it doesn't work.

I'm wondering what is the recommended way to handle this use case. Thank you!

**Comment by Hixie** [comment]
You can push a PopupRoute (which is a ModalRoute) using Navigator.push, which just shows the spinner.

Or you could disable every text field while you're saving.

Or you could not disable the text fields, let them continue editing, while you're saving. Personally as a user I prefer this last one. :-)

**Comment by zhenqiu1101** [comment]
Thanks Ian! That solved my problem! And thank you for your suggestion : )
