### ISSUE TITLE
The flutter project is stalling horizontally on the ipad10

### ISSUE THREAD

**Issue by Mr-Zheng-maker** [flutter/flutter#157699]
### Steps to reproduce

Install the flutter project and turn on horizontal and vertical screens

### Expected results

Normal use, no delay

### Actual results

The flutter project has a horizontal or vertical screen stall on ipad10. After starting the screen recording, the stall is normal.

### Code sample

no

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Mr-Zheng-maker, what version of flutter are you experiencing this issue on? Does this reproduce on simulators as well or only on physical iPads? Would it be possible to capture a video of the issue? Does this happen with the flutter counter app?
