### ISSUE TITLE
[web] Wrong font rendering some emojis.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#157763]
For some emoji glyph codes, like `0x1f3d5`, Flutter web will resolve Noto Sans Symbols instead of Noto Color Emoji.

This is what it looks like:

<img width="346" alt="Screenshot 2024-10-28 at 4 25 53 PM" src="https://github.com/user-attachments/assets/2bdb63e2-aeaa-4c72-80b8-cf3b15b45eaa">

But the emoji [should look like this](https://emojipedia.org/camping#designs):

<img width="932" alt="Screenshot 2024-10-28 at 4 26 58 PM" src="https://github.com/user-attachments/assets/84e70731-531e-4a2f-b6c6-491d9dc7f8a6">

Can we prefer the Noto Color Emoji font whenever there's a tie with Symbols (?)

---

## Repro

On the web (with a non-html renderer) in the default starter app, render this widget:

```dart
Text(String.fromCharCode(0x1f3d5));
```

That'll render the monochrome "camping" emoji, instead of the colorful one.

<details>
<summary>Full <tt>main.dart</tt></summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: EmojiRepro(),
    );
  }
}

class EmojiRepro extends StatelessWidget {
  const EmojiRepro({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              // Should use Noto Color Emoji, but uses Noto Sans Symbols
              String.fromCharCode(0x1f3d5),
              style: Theme.of(context).textTheme.displayLarge,
            ),
            // Uncomment this so Noto Color Emoji wins the "tie"
            // Text(
            //   String.fromCharCode(0x26fa),
            //   style: Theme.of(context).textTheme.displayLarge,
            // ),
          ],
        ),
      ),
    );
  }
}
```
</details>

---

Another example:

<img width="339" alt="Screenshot 2024-10-28 at 4 33 07 PM" src="https://github.com/user-attachments/assets/8b6f5f05-aec0-43c6-a7a4-2c2c14025780">

Designs of [`0x1f39e` film_frames](https://emojipedia.org/film-frames#designs).

**Comment by ditman** [comment]
In some frames, we fire a "Could not find a set of Noto fonts to display all missing characters" warning, and download the Noto Symbols TTF font even when Color Emoji is supposed to render the glyph, I wonder if there's a race condition somewhere...

<img width="1374" alt="Screenshot 2024-10-28 at 5 48 10 PM" src="https://github.com/user-attachments/assets/9f10c182-3030-46bd-962c-405764be05e3">

**Comment by ditman** [comment]
OK, there seems to be two things. One is that we don't like the [`0xFE0F Variation Selector` glyph](https://www.compart.com/en/unicode/U+FE0F).

The other one seems to be that when we do `_selectFont`, we end up with both "Noto Sans Symbols X" **above** "Noto Color Emoji X" and the tie breaker decides for "Noto Sans Symbols".

Maybe we can always untie in favor of "Color Emoji" when it's a candidate?

**Comment by ditman** [comment]
I've created a PR to prioritize Noto Color Emoji above Noto Sans Symbols fonts. This only required a change to the font roller script.

https://github.com/flutter/engine/pull/56187

**Comment by danagbemava-nc** [comment]
Reproducible using the sample provided above.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (5 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
```

```
[!] Flutter (Channel master, 3.27.0-1.0.pre.277, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
    • Flutter version 3.27.0-1.0.pre.277 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4a8e2f983f (6 hours ago), 2024-10-28 23:06:38 -0400
    • Engine revision c05af6f939
    • Dart version 3.7.0 (build 3.7.0-75.0.dev)
    • DevTools version 2.40.1

```
</details>
