### ISSUE TITLE
Space key doesn't work in iOS Device Mobile Browser Only Flutter Web TextField/TextFormField

### ISSUE THREAD

**Issue by hgandhi67** [flutter/flutter#157791]
### Steps to reproduce

Just run any deployed or production flutter web app in iOS Device Mobile Browser, and try to enter space in any of the textfields.

### Expected results

Space key should work as expected.

### Actual results

It does not allows us to add space between words in TextFormField. It does not work in any of the iOS device mobile browsers like Safari or Even chrome.

### Code sample

<details open><summary>Code sample</summary>

```dart
TextFormField(
    onSaved: (String? value) {
       debugPrint('Value for field $index saved as "$value"');
    },
),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/8550c336-cf13-44bb-ae0a-ed2a519ec1c3

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.2.1 23C71 darwin-x64, locale en-IN)
    • Flutter version 3.24.4 on channel stable at /Users/mac/Public/flutter_sdks/3.24.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (5 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/mac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.2.1 23C71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by hgandhi67** [comment]
https://github.com/flutter/flutter/issues/78652

**Comment by huycozy** [comment]
I see your demo video recorded on a production/complicated app. Does the issue happen with the given sample code or a simple TextField/TextFormField? I checked this on my end with TextField() but didn't see the issue on iOS Safari browser.

If the issue only appears on your project code, please try to narrow it down into a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by hgandhi67** [comment]
https://testwebappflutter-8e451.web.app/

I tested and deployed this TEST app, in this it works fine and as expected in iOS devices.

My app's textfield only has issues in iPhone devices even in simulator's safari browser.

I'm closing this issue, but if you can share some insights what might be the issues from my side or any help is appericiated, Thanks
