### ISSUE TITLE
problem with discounts, after setting discount price in appstore the price is still without discount

### ISSUE THREAD

**Issue by norberthanysz** [flutter/flutter#157705]
### Steps to reproduce

1. choose subscription with discount
2. try to buy subscription 
3. the price is without discount 

### Expected results

price should be with discount 

### Actual results

regular price when want to pay 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Are you using [in_app_purchase](https://pub.dev/packages/in_app_purchase) package? If so, please try to provide all information indicated in [Flutter's first-party package issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml) so we have enough information to verify the issue. Thanks!

- The version of the package
- Target platforms
- A minimal sample code to reproduce the issue

**Comment by norberthanysz** [comment]
hi, thanks for the quick response, so I'm using the 3.2.0 version of the library, target platforms: Android (works fine), iOS (a problem when I set discount in the store). I use Future<bool> buyNonConsumable from library, and after my small investigation i found problem in 

    await _skPaymentQueueWrapper.addPayment(SKPaymentWrapper(
        productIdentifier: purchaseParam.productDetails.id,
        quantity:
            purchaseParam is AppStorePurchaseParam ? purchaseParam.quantity : 1,
        applicationUsername: purchaseParam.applicationUserName,
        simulatesAskToBuyInSandbox: purchaseParam is AppStorePurchaseParam &&
            purchaseParam.simulatesAskToBuyInSandbox,
        paymentDiscount: purchaseParam is AppStorePurchaseParam
            ? purchaseParam.discount
            : null));
            
it's 113 line from in_app_purchase_storekit_platform.dart file

**Comment by norberthanysz** [comment]
when I want to crate SKPaymentWrapper in_app_purchase_storekit_platform.dart (113 line) paymentDiscount always is null, but purchaseParam -> productDetails -> skProduct -> discounts is not null

**Comment by huycozy** [comment]
What is the instance type of your purchaseParam in the implementation code? Is it `AppStorePurchaseParam`? Can you share a sample code for this? Please check https://github.com/flutter/flutter/issues/145898#issuecomment-2026903867 to see if some info there is useful.

**Comment by norberthanysz** [comment]
yeah you are right, I didn't implement a in_app_purchase_store_kit, now my code looks like: 

final discounts = (product as AppStoreProductDetails).skProduct.discounts;

      final purchaseParam = AppStorePurchaseParam(
        productDetails: product,
        applicationUserName: userId,
        discount: discounts,
      );
      await _iap.buyNonConsumable(purchaseParam: PurchaseParam(productDetails: product, applicationUserName: userId));


but still doesn't work I can't add discount to AppStorePurchaseParam

**Comment by huycozy** [comment]
>but still doesn't work I can't add discount to AppStorePurchaseParam

Do you mean the price has not been updated with the discount you provided to `AppStorePurchaseParam`? Can you please provide a complete sample code and the version of `in_app_purchase_storekit` you are using? You may try with [plugin example](https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example) and modify it but please point out which line of code you modified since the sample code is quite long. Thanks!

**Comment by norberthanysz** [comment]
I set a 50% discount price for 1 year for 1 year subscription in App Store Connect, this is working ok because when I download data from app store I see discount in AppStoreProductDetails -> SKProduct model. But when I choose this subscription and go forward to payment I see price without discount. I use 0.3.18+3 in_app_purchase_storekit version. I can't mapped SKProduct.discount to AppStorePurchaseParam.discounts I can't find any information how I should implement this in my app.

**Comment by huycozy** [comment]
>I can't mapped SKProduct.discount to AppStorePurchaseParam.discounts I can't find any information how I should implement this in my app.

I am not sure about the mapping you are mentioned to but if you want to get discount you passed to AppStorePurchaseParam, you can try getting it on SKPaymentQueueDelegateWrapper as below:

1. Check `ExamplePaymentQueueDelegate` at https://github.com/flutter/packages/blob/79f8b0b6655132ac8d11a50243afe85867a09405/packages/in_app_purchase/in_app_purchase/example/lib/main.dart#L499 
2. On `shouldContinueTransaction` method, get discount from transaction: `transaction.payment.paymentDiscount`
