### ISSUE TITLE
There is a problem using PopScop and GoRouter

### ISSUE THREAD

**Issue by LiuPack** [flutter/flutter#157779]
### Steps to reproduce

When I use `StatefulShellRoute.indexedStack` and `NavigationBar`, the login status will be intercepted when switching, and then jump to the login page. At this time, the login page seems to be the only one in the stack. When I call the system return button, the application will exit, and Instead of going back to where `StatefulShellRoute.indexedStack` is, I also tried using `PopScope` interception on the login page, but it didn't work. Then I added a `BackButton` to the login page, and clicked `BackButton` to return to where `StatefulShellRoute.indexedStack` was. I I also searched for related issues. It seems that there is a problem with the new version of `go_router`.In the v12 version, `PopScope` can intercept normally.

### Expected results

The `PopScope` of the login page needs to intercept system returns normally, perform its own business, or return normally to the page where `StatefulShellRoute.indexedStack` is located.

### Actual results

Exited the app

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.4 on channel stable at /Users/liuxin/fvm/versions/3.24.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (5 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/liuxin/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Users/liuxin/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[✓] Android Studio (version 2024.2)
    • Android Studio at /Users/liuxin/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.4)
    • IntelliJ at /Users/liuxin/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 82.0.3
    • Dart plugin version 242.22855.32

[✓] Connected device (5 available)
    • 23113RKC6C (mobile)             • 86d57eeb              • android-arm64  • Android 14 (API 34)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Microsoft Edge 130.0.2849.46

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
This is a know issue which is being tracked in https://github.com/flutter/flutter/issues/140869

Kindly follow up in the original issue for updates 

Closing from here

Thank you
