### ISSUE TITLE
[local_auth] Detect New Fingerprints or Face ID Added After Enabling Biometric Authentication

### ISSUE THREAD

**Issue by Yim-Sekny** [flutter/flutter#157701]
### Use case

The `local_auth` package currently lacks the ability to detect if new biometric data (e.g., fingerprints or Face ID) has been added to the device after a user initially enables biometric authentication. For security-sensitive applications, it is essential to check if any new biometrics have been enrolled. This allows the app to prompt the user to re-enable biometrics as an extra layer of security. Adding this feature would enhance app security by alerting users of potential unauthorized changes to their biometric data.

### Proposal

Adding this feature request will bring visibility to the need for enhanced biometric security within the `local_auth` package.

**Comment by danagbemava-nc** [comment]
This is out of scope for the local_auth plugin. See https://github.com/flutter/flutter/issues/88848#issuecomment-906724327

Closing from here
