### ISSUE TITLE
Make standard codec extension APIs more consistent across Dart/Java/ObjC

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#15779]
See [this PR](https://github.com/flutter/plugins/pull/429/files/91b8db4465f5451803747e0e66b3deae7e99c78a..505ea4a0f6b23f8f8ccdb3dd2f7ad1efb1dd4bfb).

The code you have to write to correctly read/write values of known types (Strings and doubles in the example above) is subtly different across the three platforms. We should expose consistent convenience methods in the base/helper classes to make code like that simple enough to be obviously correct.

**Comment by jonahwilliams** [comment]
Closing as obsolete
