### ISSUE TITLE
[in_app_purchase] not found products in my phone

### ISSUE THREAD

**Issue by charles0122** [flutter/flutter#157712]
### Steps to reproduce

**I don't understand why the same code has such a result on different phones**

### example code
![Screenshot_2024-10-28-18-31-45-812_com dreamingcall app android](https://github.com/user-attachments/assets/2d4e98d6-9fb4-4916-a69c-e28d46d56be4)
### example code
![Screenshot_2024-10-28-18-31-50-71_b8edf4146bfc3d249e4036b6570b32d1](https://github.com/user-attachments/assets/9aeeb841-c2cd-4157-82f3-56e005e9c746)

**I don't understand why the same code has such a result on different phones**

more infos:
purchase in play store (not use this plugin)  on phone two
![Screenshot_2024-10-28-18-55-06-20_b5a5c5cb02ca09c784c5d88160e2ec24](https://github.com/user-attachments/assets/c48237cc-8c39-435b-9a6d-6972ba151e22)
purchase in play store (unknown plugin) on phone two
![Screenshot_2024-10-28-18-54-00-29_b5a5c5cb02ca09c784c5d88160e2ec24](https://github.com/user-attachments/assets/cd468d0b-d2ea-4b22-90a1-085a32836eb0)

### Expected results

phone two equals phone one result when run with this plugin example code

### Actual results

not equals

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@charles0122 
Your question / issue is better suited for support channels like StackOverflow.
If you think there's a bug in the plugin, please provide us all the relevant details asked in the template so that we can properly address the issue.
Closing for now.
