### ISSUE TITLE
i want to know how to do full wheel animation like casino meter ?

### ISSUE THREAD

**Issue by ramaranjandey** [flutter/flutter#15776]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by xster** [comment]
Not sure what a casino meter is. Do you have a picture of the intended effects? Perhaps https://docs.flutter.io/flutter/widgets/ListWheelScrollView-class.html?

**Comment by ramaranjandey** [comment]
these pics u can refer

**Comment by ramaranjandey** [comment]
help me please about the implementation of ListWheelScrollView class

**Comment by xster** [comment]
Seems like you haven't attached any images. Please also consider using stackoverflow.com for usage questions

**Comment by ramaranjandey** [comment]
thank you
