### ISSUE TITLE
Failed to build iOS app: `double-quoted include "SqfliteImportPublic.h" in framework header, expected angle-bracketed instead`

### ISSUE THREAD

**Issue by adnit** [flutter/flutter#157761]
Adding my build logs here:

```Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running pod install...                                           1,856ms
Running Xcode build...                                                  
Xcode build done.                                           151.6s
Failed to build iOS app
Error (Xcode): double-quoted include "SqfliteImportPublic.h" in framework header, expected angle-bracketed instead
/Users/adnitkamberi/Documents/GitHub/blue-esim/blue_esim_flutter/ios/Pods/Target%20Support%20Files/sqflite_darwin/sqflite_darwin-umbrella.h:12:8


Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/adnitkamberi/.pub-cache/hosted/pub.dev/sqflite_darwin-2.4.1-1/darwin/sqflite_darwin/Sources/sqflite_darwin/include/sqflite_darwin/SqfliteImportPublic.h:14:8


Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c++_arm64-apple-ios12.0-simulator_gnu++20/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c++_arm64-apple-ios12.0-simulator_gnu++20/Test/Test.mm:0:8


Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c++_x86_64-apple-ios12.0-simulator_gnu++20/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c++_x86_64-apple-ios12.0-simulator_gnu++20/Test/Test.mm:0:8


Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c_arm64-apple-ios12.0-simulator_gnu17/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c_arm64-apple-ios12.0-simulator_gnu17/Test/Test.m:0:8


Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c_x86_64-apple-ios12.0-simulator_gnu17/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/adnitkamberi/Library/Developer/Xcode/DerivedData/Runner-bjtkyvsfwetfungwwnieasbodziw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/sqflite_darwin.bu
ild/VerifyModule/sqflite_darwin_objective-c_x86_64-apple-ios12.0-simulator_gnu17/Test/Test.m:0:8


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.```



_Originally posted by @adnit in https://github.com/flutter/flutter/issues/157694#issuecomment-2442793144_

**Comment by adnit** [comment]
```
adnitkamberi@Adnits-Mac-mini ~ % pod --version
1.15.2 

adnitkamberi@Adnits-Mac-mini ~ % ruby --version
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]

adnitkamberi@Adnits-Mac-mini ~ % where ruby         
/opt/homebrew/opt/ruby/bin/ruby
/usr/bin/ruby

adnitkamberi@Adnits-Mac-mini ~ % where pod          
/opt/homebrew/bin/pod
```

I am running macOS 15.0.1, Xcode 16.0, flutter stable channel

```
adnitkamberi@Adnits-Mac-mini ~ % flutter --version
Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (4 days ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3
```

My Podfile is like this:

```
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by matehat** [comment]
Similarly here, we're completely blocked since this morning (Montreal time):

```
Building staging.health.braver.pro for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: LU9Z5SG9T7
Running Xcode build...
Xcode build done.                                           76.7s
Failed to build iOS app
Error (Xcode): double-quoted include "RecordPlugin.h" in framework header, expected angle-bracketed instead
/Users/mathieudamours/Development/braver/platform-copy/dart/apps/mobile/ios/Pods/Target%20Support%20Files/record/record-umbrella.h:12:8


Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/mathieudamours/.pub-cache/hosted/pub.dev/record-4.4.4/ios/Classes/RecordPlugin.h:0:8


Error (Xcode): (fatal) could not build module 'record'
/Users/mathieudamours/Library/Developer/Xcode/DerivedData/Runner-cpjsmorunysewhbbcfkywlgigqvt/Build/Intermediates.noindex/Pods.build/Release-staging-iphoneos/record.build/VerifyModule/record_objective-c++_arm64-apple-ios13.0_gnu++20/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/mathieudamours/Library/Developer/Xcode/DerivedData/Runner-cpjsmorunysewhbbcfkywlgigqvt/Build/Intermediates.noindex/Pods.build/Release-staging-iphoneos/record.build/VerifyModule/record_objective-c++_arm64-apple-ios13.0_gnu++20/Test/Test.mm:0:8


Error (Xcode): (fatal) could not build module 'record'
/Users/mathieudamours/Library/Developer/Xcode/DerivedData/Runner-cpjsmorunysewhbbcfkywlgigqvt/Build/Intermediates.noindex/Pods.build/Release-staging-iphoneos/record.build/VerifyModule/record_objective-c_arm64-apple-ios13.0_gnu11/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/mathieudamours/Library/Developer/Xcode/DerivedData/Runner-cpjsmorunysewhbbcfkywlgigqvt/Build/Intermediates.noindex/Pods.build/Release-staging-iphoneos/record.build/VerifyModule/record_objective-c_arm64-apple-ios13.0_gnu11/Test/Test.m:0:8


Error (Xcode): (fatal) could not build module 'record'
/Users/mathieudamours/Library/Developer/Xcode/DerivedData/Runner-cpjsmorunysewhbbcfkywlgigqvt/Build/Intermediates.noindex/Pods.build/Release-staging-iphoneos/record.build/VerifyModule/record_objective-c_arm64-apple-ios13.0_gnu17/Test/Test.framework/Headers/Test.h:0:8


Error (Xcode): (fatal) could not build module 'Test'
/Users/mathieudamours/Library/Developer/Xcode/DerivedData/Runner-cpjsmorunysewhbbcfkywlgigqvt/Build/Intermediates.noindex/Pods.build/Release-staging-iphoneos/record.build/VerifyModule/record_objective-c_arm64-apple-ios13.0_gnu17/Test/Test.m:0:8


Encountered error while building for device.
```

As mentioned by others, each time a build is run, a different pod fails to build.

In our case it stared when we tried to upgrade to Flutter 3.24.4, but even going back to earlier commits in the past where we were on Flutter 3.23.3 and builds worked properly, now show the same errors even on a clean git checkout.

Tried all that was mentioned by others: flutter clean, pod deintegrate, xcode clean, reinstall. Nothing worked. I also tried removing the entirety of the `ios/` folder and rebuilt it to have a similar configuration as we currently have with entitlements, flavors and all, and came right back to the same issues.

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6.1 23G93 darwin-arm64, locale en-CA)
[✗] Android toolchain - develop for Android devices
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.94.2)
[✓] Connected device (7 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

**Comment by SebastianKlaiber** [comment]
For me it was an issue with cocoapods, there is a new version released and after updating the issue is resolved.

**Comment by himamis** [comment]
This was driving me crazy, but hopefully https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.0 fixes it.

**Comment by tonypottera24** [comment]
This one works for me https://github.com/flutter/flutter/issues/157694
Downgrade `xcodeproj` from 1.26.0 to 1.25.0 by the following command.
```
sudo gem install xcodeproj  --version=1.25.0"
```

**Comment by cyrilcolinet** [comment]
Oh, thank you! I thought I was going crazy; I tried everything but still have no idea how this annoying issue is happening, lol.

**UPDATE:** By upgrading CocoaPods to [1.16.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.0), everything works well. Here are the steps I followed:

1. Upgrade `xcodeproj` and `cocoapods`: 
```bash
   sudo gem update xcodeproj      # this upgrades to 1.26.0
   sudo gem update cocoapods      # this upgrades to 1.16.0
``` 

2. Fully clean and re-install pods:
```bash
flutter clean
cd ios
rm -rf Pods/
rm -rf Podfile.lock
pod install --repo-update
```

Now you should be able to build your app successfully 🚀

**Comment by huycozy** [comment]
As I can see, most of the logs above show that the error comes from 3rd party plugins but not from 1st party plugins or Flutter framework.

>By upgrading CocoaPods to [1.16.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.0), everything works well

@adnit Does this also work for you?

**Comment by fonstack** [comment]
I was having a nightmare yesterday's night. I can confirm updating cocoapods to `1.16.0` solved the issue.

**Comment by loading1031** [comment]
In my case, I'm already using version 1.16.0, but it's still not working.
```
(base)  yunseongmun@yunseongmuns-MacBook-Air  ~/Golbang_FE/golbang_jb/ios  ↱ main ±✚  sudo gem update xcodeproj      # this upgrades to 1.26.0
sudo gem update cocoapods      # this upgrades to 1.16.0
Updating installed gems
Nothing to update
Gems already up-to-date: xcodeproj
Updating installed gems
Nothing to update
Gems already up-to-date: cocoapods

Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
/Users/yunseongmun/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.12+1/ios/image_picker_ios/Sources/image_picker_ios/messages.g.m:11:8
```

**Comment by SebastianKlaiber** [comment]
@loading1031 could you share some more details? 
Flutter version
xcode version
...

Have you cleaned your dependencies after updating cocoapods? 

```
cd ios
pod deintegrate
rm Podfile.lock
rm -rf Pods
pod install
cd ..
flutter clean
flutter pub get
flutter run
```

**Comment by cyrilcolinet** [comment]
> In my case, I'm already using version 1.16.0, but it's still not working.
> 
> ```
> (base)  yunseongmun@yunseongmuns-MacBook-Air  ~/Golbang_FE/golbang_jb/ios  ↱ main ±✚  sudo gem update xcodeproj      # this upgrades to 1.26.0
> sudo gem update cocoapods      # this upgrades to 1.16.0
> Updating installed gems
> Nothing to update
> Gems already up-to-date: xcodeproj
> Updating installed gems
> Nothing to update
> Gems already up-to-date: cocoapods
> 
> Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
> /Users/yunseongmun/.pub-cache/hosted/pub.dev/image_picker_ios-0.8.12+1/ios/image_picker_ios/Sources/image_picker_ios/messages.g.m:11:8
> ```

Hi, sorry to hear that. I hope your nightmare is soon behind you...
Could you please provide more details about your installation ? (eg: flutter version and dart version)

Also:
- make sure your packages are up-to-date (by exec `flutter pub upgrade` -> you shouldn't have breaking changes).
- did you completely re-install your pods ?

**Comment by loading1031** [comment]
Thankyou for your interest

@SebastianKlaiber 
I attempted to work on it yesterday with SPM, but I had to stop as it wasn’t successful. 
When I ran the code you sent, I encountered the following error:
<details>
  <summary>Error Details</summary>
```
Uncategorized (Xcode): Exited with status code 127 Could not build the application for the simulator. Error launching application on iPhone 16 Plus
```
I’ll try to troubleshoot it this evening and give it another go.
But It didn’t work yesterday either, unfortunately…
</details>
@cyrilcolinet 
Here it is..!
<details>
  <summary>Flutter doctor</summary>
(base)  yunseongmun@yunseongmuns-MacBook-Air  ~/Golbang_FE/golbang_jb/ios  ↱ main ±✚  flutter doctor -v
[✓] Flutter (Channel main, 3.27.0-1.0.pre.286, on macOS 14.5 23F79 darwin-arm64, locale ko-KR)
    • Flutter version 3.27.0-1.0.pre.286 on channel main at /Users/yunseongmun/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ebc80f0164 (7 hours ago), 2024-10-29 11:51:26 -0400
    • Engine revision 4cb4478016
    • Dart version 3.7.0 (build 3.7.0-78.0.dev)
    • DevTools version 2.40.1
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yunseongmun/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
```
</details>

**Comment by anthonyhunter** [comment]
Xcode version 16.1 was my problem.

This worked for me.
- Xcode 15.4 (Xcode CLT 16.0 or 16.1 did not work)
- Pod 1.16.1
- xcodeproj 1.26.0
- cocoapods 1.16.1

and clearing cache as described above https://github.com/flutter/flutter/issues/157694#issuecomment-2443321940

**Comment by loading1031** [comment]
> * Xcode 15.4 (Xcode CLT 16.0 or 16.1 did not work)
> * Pod 1.16.1
> * xcodeproj 1.26.0
> * cocoapods 1.16.1

As you suggested, I tried to update my Xcode version, but I found that my Xcode isn’t up-to-date. However, I’m running into storage issues, so I can’t install a new version or update the existing one. I’ll share the current process with other developers on the team and let them know about the Xcode version situation as well 😭

thank you for letting me know

**Comment by kstmasa** [comment]
> This one works for me #157694 Downgrade `xcodeproj` from 1.26.0 to 1.25.0 by the following command.
> 
> ```
> sudo gem install xcodeproj  --version="1.25.0"
> ```

I downgrade my xocdeproj from 1.26.0 to 1.23.0 

This is a tremendous success. A grateful heart. 🥳🥳🥳

**Comment by corrosive4354** [comment]
Make sure that the dependencies of sqflite and Flutter are correctly added in your Podfile. You can try running pod install or pod update to update the dependencies.

If you have other packages to download,
you can try using [servbay](https://servbay.com), which currently supports one-click deployment of mongoDB/php/nodejs/mariadb

**Comment by cyrilcolinet** [comment]
@loading1031 maybe try to remove derived data from xcode ?

My side I use DevCleaner tool from app store by you can do it manually by completely close XCode and executing 

rm -rf ~/Library/Developer/Xcode/DerivedData/*

**Comment by Tigls** [comment]
We have the same problem and completely blocked with ios releases. Tried on 2 different machines.
Cocoapods are also the latest version - 1.16.1.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.7 23H124 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
[✓] VS Code (version 1.94.2)
[✓] Connected device (3 available)            
[✓] Network resources

pod --version
1.16.1

I tried cleaning up everything as everyone here and in other issues suggested - no progress. Every time we have the same result - a random dependency with this error as original post here. 

Even if I update every package that shows up in the error, at some point it starts showing the packages I've just updated.

**Comment by cyrilcolinet** [comment]
@Tigls what is your xcodeproj gem version ?

**Comment by Tigls** [comment]
@cyrilcolinet I am using xcodeproj version 1.26. Installing version 1.25 via gem does not downgrade it, as I previously didn't have xcodeproj installed via gem.

However, my colleague has xcodeproj 1.25 and CocoaPods 1.15.2, and he is experiencing the same issue. He upgraded CocoaPods to 1.16.1, but it still had no effect.

**Comment by cyrilcolinet** [comment]
@Tigls you can try to upgrade Xcode Project Version like the following:

![CleanShot 2024-10-30 at 17 45 20](https://github.com/user-attachments/assets/03092bd7-e450-4056-a43d-89495da38c9d)

Click on the main target on project structure, and you'll be able to select project version on right side.

Lemme know

**Comment by cyrilcolinet** [comment]
> As you suggested, I tried to update my Xcode version, but I found that my Xcode isn’t up-to-date. However, I’m running into storage issues, so I can’t install a new version or update the existing one. I’ll share the current process with other developers on the team and let them know about the Xcode version situation as well 😭
> 
> thank you for letting me know

Hi @loading1031, maybe you can follow the step aboce and let us know if it works

**Comment by adnit** [comment]
It works on latest `Xcode 16.1`, `cocoapods 1.16.1`, `xcodeproj 1.26.0`. Marking the issue as closed

**Comment by Leo199206** [comment]
> 适用于最新的`Xcode 16.1`、`cocoapods 1.16.1`、`xcodeproj 1.26.0`。将问题标记为已关闭

- I have already updated all the tools to match your versions, but I am still encountering similar errors when using the in_app_purchase plugin.

> /Users/leo/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/in_app_purchase_storekit-0.3.18+3/darwin/Classes/FIAPRequestHandler.h:5:9 'FLTRequestHandlerProtocol.h' file not found with <angled> include; use "quotes" instead

- Then I made local code modifications to the in_app_purchase plugin, and the project ran successfully.

**Before modification：**
`
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#import <FLTRequestHandlerProtocol.h>
#import <Foundation/Foundation.h>
#import <StoreKit/StoreKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface FIAPRequestHandler : NSObject <FLTRequestHandlerProtocol>

- (instancetype)initWithRequest:(SKRequest *)request;
- (void)startProductRequestWithCompletionHandler:(ProductRequestCompletion)completion;

@end

// The default request handler that wraps FIAPRequestHandler
@interface DefaultRequestHandler : NSObject <FLTRequestHandlerProtocol>

// Initialize this wrapper with an instance of FIAPRequestHandler
- (instancetype)initWithRequestHandler:(FIAPRequestHandler *)handler;
@end
NS_ASSUME_NONNULL_END
`

**After modification：**
`
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#import "FLTRequestHandlerProtocol.h"
#import "Foundation/Foundation.h"
#import "StoreKit/StoreKit.h"
NS_ASSUME_NONNULL_BEGIN

@interface FIAPRequestHandler : NSObject <FLTRequestHandlerProtocol>

- (instancetype)initWithRequest:(SKRequest *)request;
- (void)startProductRequestWithCompletionHandler:(ProductRequestCompletion)completion;

@end

// The default request handler that wraps FIAPRequestHandler
@interface DefaultRequestHandler : NSObject <FLTRequestHandlerProtocol>

// Initialize this wrapper with an instance of FIAPRequestHandler
- (instancetype)initWithRequestHandler:(FIAPRequestHandler *)handler;
@end
NS_ASSUME_NONNULL_END
`

**Although the local code runs successfully, I don’t think this is a good solution, especially when using Jenkins for builds, as it may not resolve the issue effectively.**

**Comment by cyrilcolinet** [comment]
@Leo199206 had you tried this https://github.com/flutter/flutter/issues/157761#issuecomment-2447777827 ?

**Comment by Tigls** [comment]
@cyrilcolinet I can also confirm that updated version of cocoapods to 1.16 solved the problem. 

My problem was that the local environment was different from the fastlane environment. Fastlane "bundle install" command was still installing the cocoapods 1.15.2 even though the version in the gem file was not specified and supposed to be the latest. 

After running "bundle update" fastlane updated its cocoapods to 1.16 - everything started to build successfully.

Thank you, guys!

**Comment by cyrilcolinet** [comment]
@Tigls Oh yeah good point! Happy coding 🙃

**Comment by Leo199206** [comment]
> @Leo199206您尝试过这个[#157761 (评论)](https://github.com/flutter/flutter/issues/157761#issuecomment-2447777827)吗？

I’ve tried it, but it didn’t work for my project.

**Comment by cyrilcolinet** [comment]
> I’ve tried it, but it didn’t work for my project.

Looks like the solution given by @Tigls works for big majority of users, can you confirm that this solution don't work for you as well?

**Comment by pabloaimagine** [comment]
I'm building on XCode Cloud (suposed to use the lastest versions) and still don't work.

Error
`'Flutter/Flutter.h' file not found

OpenFilePlugin.h:1`

- Xcode Project versio 16.0
- Xcode 16.1 (16B40)
- macOS Sequoia 15 (24A335)
- Cocoapods 1.16.2
- Dart SDK constrained to ^3.5.4 -> Flutter Version [3.24.4]

**Comment by Leo199206** [comment]
> > I’ve tried it, but it didn’t work for my project.
> 
> Looks like the solution given by @Tigls works for big majority of users, can you confirm that this solution don't work for you as well?
Confirm, my system version is macOS Sequoia 15.1.

**Flutter Version Information**
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2024.2)
[✓] Android Studio (version 2024.1)
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for 14 Pro Max. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

**Comment by cyrilcolinet** [comment]
Argh, to be honest I don't have any other idea to help you there, sorry.
Hope someone (or God) will ear you and help you on that 🚀
