### ISSUE TITLE
Possibility to serialize `Color` after deprecation of `Color.value`

### ISSUE THREAD

**Issue by FaFre** [flutter/flutter#157776]
### Use case

The getter `Color.value` is now deprecated:

```dart
@Deprecated('Use component accessors like .r or .g.')
  int get value {
    if (_a != null && _r != null && _g != null && _b != null) {
      return _floatToInt8(_a) << 24 |
          _floatToInt8(_r) << 16 |
          _floatToInt8(_g) << 8 |
          _floatToInt8(_b) << 0;
    } else {
      return _value;
    }
  }
```

This came in handy for serialization when storing color in e.g. database or shared preferences, since there is a default constructor that takes the value for initialization:

```dart
const Color(int value)
      : _value = value & 0xFFFFFFFF,
        colorSpace = ColorSpace.sRGB,
        _a = null,
        _r = null,
        _g = null,
        _b = null;
```

### Proposal

There should be a way to get the color as a primitive data type that allows colors to get serialized and de-serialized.

**Comment by matanlurey** [comment]
This is the flip-side of https://github.com/flutter/flutter/issues/157128, which seems reasonable.
