### ISSUE TITLE
flaky test: test/signing_test.dart sometimes fails

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1577]
When it fails, the Travis log looks like this:

```
+cd packages/flx
+pub run test -j1
00:00 +2 -1: test/signing_test.dart: signManifest and verifyManifestSignature work                 
  Expected: <true>
    Actual: <false>

  package:test                 expect
  test/signing_test.dart 71:5  main.<async>.<fn>

00:01 +7 -1: Some tests failed.                                                                    
```

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/45408d3ee64d8949e7718e8994d2c07ad7738472/packages/flx/test/signing_test.dart#L64

**Comment by eseidelGoogle** [comment]
It's the first test:
https://github.com/flutter/flutter/blob/45408d3ee64d8949e7718e8994d2c07ad7738472/packages/flx/test/signing_test.dart#L71

**Comment by Hixie** [comment]
@mpcomplete any ideas?

**Comment by mpcomplete** [comment]
I think this is a bug in cipher, the third-party crypto library I'm using for signing. I filed https://github.com/izaera/cipher/issues/95 upstream. We probably want to move away from using a third-party library for crypto, but there's no equivalent available yet.

**Comment by eseidelGoogle** [comment]
@jason-simmons saw this on the bots again yesterday?  Curious what's the current status?

**Comment by mpcomplete** [comment]
This is a bug in cipher (now PointyCastle). Our options are:
- Wait for them to fix it.
- Disable the test.
- Use a constant seed to eliminate randomness.

**Comment by Hixie** [comment]
we should totally use a constant seed in tests. ideally the seed that fails. 🙂

**Comment by Hixie** [comment]
This test appears to be gone now.
