### ISSUE TITLE
Material datePicker should hide years that can not be selected

### ISSUE THREAD

**Issue by markbeij** [flutter/flutter#157785]
### Use case

Currently when selecting the year for a date, several years prio to the current year are show even though they cannot be selected.
It is now not clear that they cannot be selected.
![image](https://github.com/user-attachments/assets/25b7d9f5-6097-4c87-9225-4ae0a49686fa)

### Proposal

Years that cannot be selected (depending on `firstDate` and `lastDate)` should be greyed out, or not be shown at all.

**Comment by danagbemava-nc** [comment]
Hi @markbeij, you can use your theme to configure how the enabled vs enabled years appear. Alternatively, if you set useMaterial3 to true in your theme, this comes out of the box, but you will need to make sure that your application is how you expected it to be. 

See https://api.flutter.dev/flutter/material/DatePickerThemeData-class.html 

You can use the year* properties to modify how the year should appear

Does this help?
