### ISSUE TITLE
Apk size of flutter app

### ISSUE THREAD

**Issue by himanshu-mind** [flutter/flutter#15778]
While creating a simple list view in flutter app the size of the apk reaches 25mb. Is this normal or is there a way to reduce the apk size?

**Comment by ics042** [comment]
Is this a release apk or debug apk, from my experience, size of debug apk is 20+MB, but if you build a release apk, the size would be reduced to around 7MB if there is no too many assets(images, font files, etc.)

**Comment by chinmaygarde** [comment]
Like @ics042 mentioned, it seems like you are measuring the size of the debug APK. Can you run `flutter build apk --release` and check the size of the APK generated as a result of that command?

**Comment by ics042** [comment]
From my observation, the size of android released APK file is reasonable(around 7MB without too many assets), but when I built an iOS ipa, the size of the released ipa was 19.8MB. If it's a normal size of a relessed ipa file, hopefully this would be optimized in the future.

**Comment by eseidelGoogle** [comment]
ipas are typically uncompressed where as .apks are compressed. :)

We really need an FAQ entry to better explain measuring sizes.  I've filed https://github.com/flutter/flutter/issues/16191

I'm going to close this for now, but please feel empowered to re-open if you don't feel we've resolved your issue.
