### ISSUE TITLE
h

### ISSUE THREAD

**Issue by midoo2020h** [flutter/flutter#157778]
### Steps to reproduce

ملخص المشكلة
المشكلة الأساسية:

تواجه خطأ متكرر في تحميل وإعداد ملفات Gradle عند محاولة بناء ملف APK لمشروع Flutter.

الأخطاء المتكررة:

Execution failed for task ':gradle:compileGroovy'.

Could not resolve all files for configuration ':gradle:detachedConfiguration1'.

Could not find org.codehaus.groovy:groovy:٣.٠.١٧.

ما تم تجربته:

إعادة تثبيت Flutter من البداية.

إنشاء مشروع جديد ونقل الملفات الأساسية.

التعديل على ملفات gradle-wrapper.properties وbuild.gradle.

محاولة تشغيل الأمر flutter build apk --release مع إضافة خيارات --verbose.

الخطوات الأخيرة قبل التواصل مع الدعم:

تأكدت من إعدادات متغيرات البيئة بشكل صحيح.

تأكدت من حذف مجلد flutter القديم وإعادة تنزيل وتثبيت Flutter.

واجهت نفس الأخطاء بالرغم من جميع المحاولات.

### Actual results

ملخص المشكلة
المشكلة الأساسية:

تواجه خطأ متكرر في تحميل وإعداد ملفات Gradle عند محاولة بناء ملف APK لمشروع Flutter.

الأخطاء المتكررة:

Execution failed for task ':gradle:compileGroovy'.

Could not resolve all files for configuration ':gradle:detachedConfiguration1'.

Could not find org.codehaus.groovy:groovy:٣.٠.١٧.

ما تم تجربته:

إعادة تثبيت Flutter من البداية.

إنشاء مشروع جديد ونقل الملفات الأساسية.

التعديل على ملفات gradle-wrapper.properties وbuild.gradle.

محاولة تشغيل الأمر flutter build apk --release مع إضافة خيارات --verbose.

الخطوات الأخيرة قبل التواصل مع الدعم:

تأكدت من إعدادات متغيرات البيئة بشكل صحيح.

تأكدت من حذف مجلد flutter القديم وإعادة تنزيل وتثبيت Flutter.

واجهت نفس الأخطاء بالرغم من جميع المحاولات.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by midoo2020h** [comment]
h

**Comment by darshankawar** [comment]
@midoo2020h 
The log you shared isn't complete for us to look into so we can't properly address it. Please try to use new issue template, fill out requested details so that we can investigate properly.
Closing for now due to lack of details. Also, please try to use English for better readability.
