### ISSUE TITLE
[iOS] : Inconsistency in Simulator and Real Device when using ColorFiltered and Opacity together 

### ISSUE THREAD

**Issue by deepakg202** [flutter/flutter#157716]
### Steps to reproduce

The code that i am trying to run uses `ColorFiltered` and `Opacity` widgets together which renders differently on IOS Simulator (Iphone 15 Pro Max - iOS 17.5) and actual device (iPhone XR - iOS 18.0). 
`Opacity` is ignored in the actual device whereas in the simulator, the opacity works. 

Tested it on android device and emulator as well. The output is the same as the simulator one.

### Expected results

The rendered widget should match on both simulator and device

### Actual results

The rendered widget does not match on simulator and device

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: SafeArea(
          child: Opacity(
            opacity: 0.5,
            child: ColorFiltered(
              colorFilter:
                  ColorFilter.mode(Colors.transparent, BlendMode.saturation),
              child: FlutterLogo(size: 550),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Output from Simulator</summary>
<img width="556" alt="image" src="https://github.com/user-attachments/assets/4b7d9c5c-d79c-4272-82c4-ed56903faa90">
</details>

<details open>
<summary>Output from Device</summary>
<img width="556" alt="image" src="https://github.com/user-attachments/assets/1599c93e-cc66-4459-b7c2-aa91744c86d4">
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2024.1)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by Chinmay-KB** [comment]
I have tested the same for iPhone 12 with iOS 17.7, the issue persists

**Comment by darshankawar** [comment]
Thanks for the report. Seeing the same behavior as reported on iOS simulator (13 pro max iOS 15.3.1). If we remove `Opacity` widget, then it matches rendering with the physical device.
Also, this works as expected on Android emulator and physical device, so this seems to be iOS simulator specific.

```
stable : 3.24.3
master : 3.27.0-1.0.pre.259
```

**Comment by deepakg202** [comment]
Just noticed that the opacity looks different in android also 

<details open>
<summary>Output from Android Emulator (API 35)</summary>
<img width="556" alt="image" src="https://github.com/user-attachments/assets/19e5be10-eedc-4ceb-8640-9d336f303af5">

</details>

**Comment by jason-simmons** [comment]
The output is inconsistent because the device is using the framebuffer blend pipeline but the simulator is not.

Both pipelines have issues affecting this example.

* In the non-framebuffer case, `advanced_blend.frag` should only apply `blend_info.dst_input_alpha` to the alpha channel after the destination color is unpremultipled.

* In the framebuffer case, `CreateFramebufferAdvancedBlend` is not applying `dst_snapshot->opacity` due to its implementation of `AbsorbOpacity`

**Comment by deepakg202** [comment]
Thanks @darshankawar @jason-simmons It is working fine now on the latest master branch. 
Any plans on releasing this as hotfix. This issue was also causing other things to behave differently in IOS like taking screenshots of widgets with transparency. This seems to fix it.
