### ISSUE TITLE
https://pub.flutter-io.cn,https://storage.flutter-io.cn blocked by organization due to  contains of the Phishing and Malicious activity.

### ISSUE THREAD

**Issue by divyachandran** [flutter/flutter#157781]
### Steps to reproduce

1. flutter doctor

### Actual results

 X An HTTP error occurred while checking "https://pub.flutter-io.cn": Proxy failed to establish tunnel (407 Proxy Authentication Required)
    X An HTTP error occurred while checking "https://storage.flutter-io.cn": Proxy failed to establish tunnel (407 Proxy Authentication Required)

Upon contacting the organizational network team received the following replay:

"Requested URLs are not allowed due to contains of the Phishing and Malicious activity. "

![Malicious URL](https://github.com/user-attachments/assets/a97d9f89-bfed-4b53-a27f-d4ed75a5da6d)

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

(base) PS I:\FlutterWorks\app1_26_10_24> flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.22631.4391], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2024.2)
[√] IntelliJ IDEA Community Edition (version 2024.2)
[√] VS Code, 64-bit edition (version 1.44.2)
[√] Proxy Configuration
[√] Connected device (3 available)
[!] Network resources
    X An HTTP error occurred while checking "https://pub.flutter-io.cn": Proxy failed to establish tunnel (407 Proxy Authentication Required)
    X An HTTP error occurred while checking "https://storage.flutter-io.cn": Proxy failed to establish tunnel (407 Proxy Authentication Required)

**Comment by rehmaan-dev** [comment]
I too had a similar situation, my organisation uses Falcon CrowdStrike and Netskope. Solution was that: One of the network guy, opened the NetSkope configuration and updated the definitions.

But yea, the question still remains why is it being marked malicious.

**Comment by huycozy** [comment]
For flutter doctor error, can you confirm you followed [Configuring Flutter to use a mirror site](https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site)?

About the error when accessing the site, please report issue to maintainers of the website.

**Comment by rehmaan-dev** [comment]
Yes, I tried configuring a mirror site, but no luck it did not worked. 
Only thing I want to point out is that it's is probably due to Enterprise based Security Apps that does not behave well be it Netskope or Zscaler. 
And as I mentioned, simply updating the Netskope definitions made it work.

**Comment by rehmaan-dev** [comment]
> For flutter doctor error, can you confirm you followed [Configuring Flutter to use a mirror site](https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site)?
> 
> About the error when accessing the site, please report issue to maintainers of the website.



Yes, I tried configuring a mirror site, but no luck it did not worked.
Only thing I want to point out is that it's is probably due to Enterprise based Security Apps that does not behave well be it Netskope or Zscaler.
And as I mentioned, simply updating the Netskope definitions made it work.

**Comment by divyachandran** [comment]
> For flutter doctor error, can you confirm you followed [Configuring Flutter to use a mirror site](https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site)?
> 
> About the error when accessing the site, please report issue to maintainers of the website.

Not working with mirror site configuration.
Can you please provide the contact to report this issue to maintainers of the website.

**Comment by huycozy** [comment]
>Can you please provide the contact to report this issue to maintainers of the website.

You can scroll down to the end of the site and should see the bug report icon there, it will go to https://github.com/dart-lang/pub-dev. I'm not sure if there is another site for `cn` but maintainers on `pub-dev` repo may know that.

>Yes, I tried configuring a mirror site, but no luck it did not worked.

>Not working with mirror site configuration.

Per https://docs.flutter.dev/community/china#china-flutter-user-group, I would suggest filing an issue on https://github.com/cfug for better support. Kindly cc @chenglu to help direct the appropriate repository there.

I will go ahead and close this issue. If you disagree, please write in the comments and I will reopen it.

**Comment by chenglu** [comment]
Let me take care of this issue, and try to reach out the phishing & malicious scanning sites.

Thanks to @huycozy
