### ISSUE TITLE
[CP] Removed clamping from dithering

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#157732]
### Issue Link

https://github.com/flutter/flutter/issues/157731

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/engine/pull/56174

### Changelog Description

Removes clamp from gradient dithering which was removing wide gamut colors for iOS Impeller users.

### Impacted Users

iOS users who used wide gamut gradients

### Impact Description

Displays gradients in sRGB instead of DisplayP3 on iOS.

### Workaround

None.

### Risk

low

### Test Coverage

yes

### Validation Steps

Integration test in https://github.com/flutter/flutter/pull/157643

**Comment by itsjustkevin** [comment]
Approved by @jonahwilliams in https://github.com/flutter/engine/pull/56174.
