### ISSUE TITLE
CPU ALWAYS OVER 100%

### ISSUE THREAD

**Issue by cryuhy** [flutter/flutter#157836]
### Steps to reproduce

is anybody konws what is this 
<img width="781" alt="截屏2024-10-30 11 11 07" src="https://github.com/user-attachments/assets/dcbcc85e-dba9-4bb1-b8b2-fdb2f2302683">
lib it is to heavy to use my device cpu, i did not operate my apps

### Actual results

no

### Logs

no

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6.1 23G93 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.79.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for chenrui. Ensure the device
      is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

• No issues found!

**Comment by jonahwilliams** [comment]
That weight is relative, it will always add up to 100%

**Comment by cryuhy** [comment]
<img width="1749" alt="截屏2024-10-30 15 52 34" src="https://github.com/user-attachments/assets/78dd13f3-11e6-4743-8422-b05af2bf1e24">
i mean this ,use instrument 
<img width="1102" alt="截屏2024-10-30 15 54 05" src="https://github.com/user-attachments/assets/d92061ba-ef87-49a5-9bd1-3dd27f95a332">

**Comment by cryuhy** [comment]
i found rease third lib open lot of thread over 10 ,and debug model i open thread checker ,close it will fix this issue
