### ISSUE TITLE
OptionsViewBuilder Not Fully Selectable Across Two Autocomplete TextFields 

### ISSUE THREAD

**Issue by Halim-Elmenshawi** [flutter/flutter#157857]
### Steps to reproduce

I have two Autocomplete Widgets, and I need their text fields to be positioned side by side. Additionally, I want the optionsViewBuilder for both to span the full width from the start of the first text field to the end of the second. To achieve this, I used CompositedTransformTarget and CompositedTransformFollower, and it works perfectly as intended.

### Expected results

However, the logic isn't working perfectly. I'm facing an issue with the second TextField: only the area directly below this TextField is selectable and scrollable, while the area directly below the first TextField is not selectable or scrollable for the second optionsViewBuilder.

### Actual results

only the area in the black box is selectable or scrollable for the second Autocomplete Widget as shown in this foto

![Screenshot 2024-10-30 at 11 27 44](https://github.com/user-attachments/assets/c6e9a6ad-b06e-43b3-8af1-477bb8b34302)

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    final LayerLink layerLink = LayerLink();
    final List<String> fruits = [
      'Apple',
      'Banana',
      'Cherry',
      'Grapes',
    ];
    final List<String> vegetables = [
      'Carrot',
      'Broccoli',
      'Spinach',
      'Potato',
    ];
    return Column(
      children: [
        SizedBox(
          height: 200,
        ),
        CompositedTransformTarget(
          link: layerLink,
          child: Row(
            children: [
              Flexible(
                child: Autocomplete(
                  optionsBuilder: (textEditingValue) => fruits,
                  optionsViewBuilder: (context, onSelected, options) =>
                      CompositedTransformFollower(
                    targetAnchor: Alignment.bottomLeft,
                    link: layerLink,
                    child: MyAutocompleteOptionsViewBuilder<String>(
                      options: options,
                      onSelected: onSelected,
                    ),
                  ),
                ),
              ),
              Flexible(
                child: Autocomplete(
                  optionsBuilder: (textEditingValue) => vegetables,
                  optionsViewBuilder: (context, onSelected, options) =>
                      CompositedTransformFollower(
                    targetAnchor: Alignment.bottomLeft,
                    link: layerLink,
                    child: MyAutocompleteOptionsViewBuilder<String>(
                      options: options,
                      onSelected: onSelected,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class MyAutocompleteOptionsViewBuilder<T> extends StatelessWidget {
  const MyAutocompleteOptionsViewBuilder({
    super.key,
    required this.options,
    required this.onSelected,
  });
  final Iterable<T> options;
  final void Function(T) onSelected;
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.topLeft,
      child: Material(
        elevation: 4.0,
        color: Colors.white,
        child: ConstrainedBox(
          constraints: BoxConstraints(
            maxHeight: MediaQuery.of(context).size.height * 0.2,
          ),
          child: ListView.builder(
            shrinkWrap: true,
            padding: EdgeInsets.zero,
            itemCount: options.length,
            itemBuilder: (BuildContext context, int index) {
              final option = options.elementAt(index);
              return ListTile(
                title: Text(option.toString()),
                onTap: () {
                  onSelected(option);
                },
              );
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v      
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale
    en-DE)
    • Flutter version 3.24.4 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.22.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (6 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror
      https://dev.dvz-mv.net/artifactory/api/pub/dart-virtual

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/halim/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.11799.172

[✓] VS Code (version 1.95.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0
```

</details>

**Comment by victorsanni** [comment]
Yep this seems like the same old [Autocomplete options width](https://github.com/flutter/flutter/pull/143249) issue.

**Comment by Halim-Elmenshawi** [comment]
It seems that issue #78746  occurs because the Autocomplete OptionsViewBuilder doesn’t align with the width of the TextField. However, my requirement is a bit different I need the OptionsViewBuilder to have a width independent of the TextField. =D
@huycozy in your second screen, the Autocomplete OptionsViewBuilder 2,  doesn’t start from the first Autocomplete Textfield, which what i need.

**Comment by victorsanni** [comment]
@Halim-Elmenshawi can you share an image or video of your desired result? I'm still confused on the requirement for the optionsViewBuilder spanning the width underneath both text fields. Is there no visible vertical barrier between both optionsViewBuilders?

**Comment by Halim-Elmenshawi** [comment]
@victorsanni  If you try my sanshot code, you'll notice that when using the second Autocomplete widget (for "vegetables"), the OptionsViewBuilder appears starting from the first pixel in the Row widget, which contains both Autocomplete widgets. This is exactly the behavior I want. To achieve it, I used CompositedTransformTarget and CompositedTransformFollower.

As shown in the image, when using the second OptionsViewBuilder, it can be divided into two main areas: the first area appears below the first Autocomplete widget, and the second area appears below the second Autocomplete widget.

My issue => However, there's an issue: when attempting to select any item from the "vegetables" list within the first area, selection doesn’t work but it only works in the second area.
my issue is in the first area when you try to select any "vegetables" item, you can't do that but it works in the second area.

Notice: Both of these areas belong to the same OptionsViewBuilder widget (OptionsViewBuilder for the second Autocomplete widget (for "vegetables")) 

![Untitled](https://github.com/user-attachments/assets/059a49de-2fe7-482e-be24-809524a3e8e8)

**Comment by huycozy** [comment]
### Experiment with OverlayEntry instead of Autocomplete (1)
Here is a demo of implementation without Autocomplete but using CompositedTransformTarget/Follower + OverlayEntry, issue is not reproduced here which means both 1st and 2nd areas (as mentioned in screenshot above comment) are clickable:

<details>
<summary>Demo video (CompositedTransformTarget/Follower + OverlayEntry)</summary>

https://github.com/user-attachments/assets/c10aba99-ecde-48e3-a87c-b863dc62c5fb

</details>

<details>
<summary>Sample code (CompositedTransformTarget/Follower + OverlayEntry)</summary>

```dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(MaterialApp(
    home: Scaffold(
      body: MyWidget(),
    ),
  ));
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final LayerLink layerLink = LayerLink();
  OverlayEntry? fruitsOverlayEntry;
  OverlayEntry? vegetablesOverlayEntry;
  String selectedFruit = '';

  final List<String> fruits = [
    'Apple',
    'Banana',
    'Orange',
    'Grapes',
  ];

  final List<String> vegetables = [
    'Carrot',
    'Broccoli',
    'Spinach',
    'Potato',
  ];

  void showFruitsOverlay() {
    fruitsOverlayEntry = OverlayEntry(
      builder: (context) => Positioned(
        width: MediaQuery.of(context).size.width,
        child: CompositedTransformFollower(
          link: layerLink,
          showWhenUnlinked: false,
          offset: Offset(0, 40),
          child: buildOverlay(fruits),
        ),
      ),
    );
    Overlay.of(context).insert(fruitsOverlayEntry!);
  }

  void showVegetablesOverlay() {
    vegetablesOverlayEntry = OverlayEntry(
      builder: (context) => Positioned(
        width: MediaQuery.of(context).size.width,
        child: CompositedTransformFollower(
          link: layerLink,
          showWhenUnlinked: false,
          offset: Offset(0, 40),
          child: buildOverlay(vegetables),
        ),
      ),
    );
    Overlay.of(context).insert(vegetablesOverlayEntry!);
  }

  void hideFruitsOverlay() {
    fruitsOverlayEntry?.remove();
    fruitsOverlayEntry = null;
  }

  void hideVegetablesOverlay() {
    vegetablesOverlayEntry?.remove();
    vegetablesOverlayEntry = null;
  }

  Widget buildOverlay(List<String> items) {
    return Material(
      elevation: 4.0,
      child: ListView(
        padding: EdgeInsets.zero,
        shrinkWrap: true,
        children: items
            .map((item) => ListTile(
                  title: Text(item),
                  onTap: () {
                    setState(() {
                      selectedFruit = item;
                    });
                    hideFruitsOverlay();
                    hideVegetablesOverlay();
                  },
                ))
            .toList(),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text('Select a fruit or vegetable: $selectedFruit'),
        SizedBox(
          height: 20,
        ),
        CompositedTransformTarget(
          link: layerLink,
          child: Row(
            children: [
              Flexible(
                child: GestureDetector(
                  onTap: showFruitsOverlay,
                  child: Container(
                    width: double.infinity,
                    padding: EdgeInsets.all(8.0),
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey),
                    ),
                    child: Text('Select a fruit'),
                  ),
                ),
              ),
              Flexible(
                child: GestureDetector(
                  onTap: showVegetablesOverlay,
                  child: Container(
                    width: double.infinity,
                    padding: EdgeInsets.all(8.0),
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey),
                    ),
                    child: Text('Select a vegetable'),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

```
</details>

### Reproduction
Because of (1), this issue looks like an issue with Autocomplete widget and needs investigation so that I will label this for further insights. Reproduced this on Flutter `Channel master, 3.27.0-1.0.pre.364` as well.

<details>
<summary>Demo video of the issue</summary>

https://github.com/user-attachments/assets/4dc65c8c-8722-4514-b20a-63b14222d8ce
</details>

**Comment by justinmc** [comment]
The way that the options view is put on the screen is changing significantly in https://github.com/flutter/flutter/pull/143249, which should land soon, so be aware that any solution based on current versions of Flutter may break soon.

I tried to implement this idea using the branch in https://github.com/flutter/flutter/pull/143249, but I want to say it's not possible. At least, if it is possible, it will be a fragile hack.

My take is that this is not worth supporting inside of Autocomplete/RawAutocomplete. You are better off making your own custom version of Autocomplete.

The only way I can think of is to create some kind of builder parameter that by default does most of what `RawAutocomplete.build` does now. However, even that is probably too complex, because there is a lot going on in that method both around the field and inside of the overlay in order to position the options.

If someone has a better idea of how to support this then I'd love to hear it though!
