### ISSUE TITLE
Does Windows OS Support the 'Flutter Test' Command?

### ISSUE THREAD

**Issue by xiaozn-github** [flutter/flutter#157835]
### Steps to reproduce

1、configuration the flutter development environment using my windows OS ;
2、enter to testcase path: .\packages\flutter\test
3、execute command 'flutter test'

### Expected results

testcase executed success

### Actual results

Shell: [ERROR:flutter/runtime/dart_snapshot.cc(107)] ResolveVMData: NonOwnedMapping
Shell: [INFO:platform_view.cc(18)] PlatformView
Shell: [WARNING:flutter/shell/common/platform_view.cc(24)] This platform does not provide a Vsync waiter implementation. A simple timer based fallback is being used.
Shell: [WARNING:flutter/shell/common/platform_view.cc(91)] This platform does not set up the resource context on the IO thread for async texture uploads.
Shell: [WARNING:flutter/shell/common/shell_io_manager.cc(57)] The IO manager was initialized without a resource context. Async texture uploads will be disabled. Expect performance degradation.
Shell: [WARNING:flutter/common/graphics/persistent_cache.cc(284)] Could not acquire the persistent cache directory. Caching of GPU resources on disk is disabled.
Shell: [WARNING:flutter/shell/common/platform_view.cc(91)] This platform does not set up the resource context on the IO thread for async texture uploads.
Shell: vm-service: Error: Unhandled exception:
Shell: Unsupported operation: Not supported on simulated architectures.
Shell: #0      _get_ffi_native_resolver (dart:ffi:897:57)
Shell: #1      _ffi_resolver (dart:ffi:901:23)
Shell: #2      _ffi_resolver (dart:ffi)
Shell: #3      _Logger.__printString$Method$FfiNative$Ptr (dart:ui/natives.dart)
Shell: #4      _Logger.__printString$Method$FfiNative$Ptr (dart:ui/natives.dart)
Shell: #5      _Logger._printString (dart:ui/natives.dart)
Shell: #6      _print (dart:ui/natives.dart:27:11)
Shell: #7      printToConsole (dart:_internal-patch/print_patch.dart:13:16)
Shell: #8      print (dart:core/print.dart:12:5)
Shell: #9      serverPrint (dart:vmservice_io/vmservice_server.dart:16:3)
Shell: #10     Server.outputConnectionInformation (dart:vmservice_io/vmservice_server.dart:509:5)
Shell: #11     Server.startup (dart:vmservice_io/vmservice_server.dart:499:13)
Shell: <asynchronous suspension>
Shell: 
Shell: [ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
Shell: Unsupported operation: Not supported on simulated architectures.
Shell: #0      _get_ffi_native_resolver (dart:ffi:897:57)
Shell: #1      _ffi_resolver (dart:ffi:901:23)
Shell: #2      _ffi_resolver (dart:ffi)
Shell: #3      _Logger.__printString$Method$FfiNative$Ptr (dart:ui/natives.dart)
Shell: #4      _Logger.__printString$Method$FfiNative$Ptr (dart:ui/natives.dart)
Shell: #5      _Logger._printString (dart:ui/natives.dart)
Shell: #6      _print (dart:ui/natives.dart:27:11)
Shell: #7      printToConsole (dart:_internal-patch/print_patch.dart:13:16)
Shell: #8      print (dart:core/print.dart:12:5)
Shell: #9      serverPrint (dart:vmservice_io/vmservice_server.dart:16:3)
Shell: #10     Server.outputConnectionInformation (dart:vmservice_io/vmservice_server.dart:509:5)
Shell: #11     Server.startup (dart:vmservice_io/vmservice_server.dart:499:13)
Shell: <asynchronous suspension>

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by liamappelbe** [comment]
Hi @xiaozn-github. The ["Not supported on simulated architectures" error](https://github.com/dart-lang/sdk/blob/e5602b34670d375d1887c8d24b14e62d367deb27/runtime/lib/ffi_dynamic_library.cc#L37) is because your [host architecture is different from your target architecture](https://github.com/dart-lang/sdk/blob/e5602b34670d375d1887c8d24b14e62d367deb27/runtime/platform/globals.h#L360). Since you're running on windows, I'm guessing your host architecture is x64. What architecture are you targeting in your tests? Can you try targeting an x64 architecture?

**Comment by xiaozn-github** [comment]
my host architecture is x86_64; 
Does flutter test is supported on  x86_64 architecture ?
 I will try on an x64 architecture

**Comment by huycozy** [comment]
@xiaozn-github When you come back, can you also share the output of `flutter doctor -v`?

**Comment by xiaozn-github** [comment]
[!] Flutter (Channel dev, 3.7.12-ohos, on Microsoft Windows [版本 10.0.19045.2006], locale zh-CN)
    • Flutter version 3.7.12-ohos on channel dev at E:\flutter_flutter
    ! Upstream repository https://gitee.com/znxiao/flutter_flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://gitee.com/znxiao/flutter_flutter.git to dismiss this error.
    • Framework revision a2ec95a4e4 (4 weeks ago), 2024-10-06 10:07:02 +0000
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] HarmonyOS toolchain - develop for HarmonyOS devices
    • OpenHarmony Sdk at D:\huawei\DevEco\DevEco Studio\sdk, available api versions has [12:default]
    • Ohpm version 5.0.8
    • Node version v18.20.1
    • Hvigorw binary at D:\huawei\DevEco\DevEco Studio\tools\hvigor\bin\hvigorw

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

Checking Android licenses is taking an unexpectedly long time...[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000
    •

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2024.1)
    • Android Studio at D:\Android\studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at D:\ideaIC-2020.1.2.win
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.7817

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is ::1,localhost,127.0.0.1,*.huawei.com
    • NO_PROXY contains localhost
    • NO_PROXY contains ::1
    • NO_PROXY contains 127.0.0.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.2006]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.101
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.56

**Comment by huycozy** [comment]
>[!] Flutter (Channel dev, 3.7.12-ohos, on Microsoft Windows [版本 10.0.19045.2006], locale zh-CN)
• Flutter version 3.7.12-ohos on channel dev at E:\flutter_flutter
! Upstream repository https://gitee.com/znxiao/flutter_flutter.git is not a standard remote.

@xiaozn-github Your Flutter version is quite old and is not an upstream repository. Please try upgrading to the latest version 3.24.4 and using upstream version (https://docs.flutter.dev/release/archive?tab=windows) to see if the issue persists or not.
