### ISSUE TITLE
[CP] Disable Maleoon GPU series from using Vulkan backend.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#157811]
### Issue Link

https://github.com/flutter/flutter/issues/156623

### Target

beta

### Cherry pick PR Link

https://github.com/flutter/engine/pull/56207

### Changelog Description

Disable the Maleoon GPU series from using the Vulkan rendering backend, as several bug reports indicate these drivers may not function correctly.

### Impacted Users

Flutter users with certain Huawei hardware

### Impact Description

Rendering may be broken on certain Huawei hardware.

### Workaround

Disable Impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached unit tests

**Comment by zanderso** [comment]
cp lgtm
