### ISSUE TITLE
Android back button is blocked by AnimatedCrossFade

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15787]
If I remove AnimatedCrossFade ,it becomes ok.

**Comment by chinmaygarde** [comment]
cc @Hixie

**Comment by Hixie** [comment]
You will need to provide some sample code for us to see what's going on. :-)

Ideally, a small `main.dart` that, when used to run an app, demonstrates the issue.

**Comment by goderbauer** [comment]
@realcarlos any chance you can provide some sample code so we can investigate?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
