### ISSUE TITLE
Flutter UI

### ISSUE THREAD

**Issue by himanshu-mind** [flutter/flutter#15785]
I want to know is there a simple and easy way of creating UI in flutter app like drag and drop feature ?

**Comment by xster** [comment]
Please reopen if your question hasn't been address.d

**Comment by himanshu-mind** [comment]
I am not talking about drag and drop fetaure in the app. I want to create UI in flutter using drag and drop from palette like in android studio for xml layouts.

**Comment by g33kidd** [comment]
Oh, sorry I misunderstood. I came across this a while back, but I haven't found anything else. And I also can't get this thing to work. Maybe someday we'll see a "Flutter Studio" or something. https://medium.com/@pmutisya/create-flutter-studio-using-dart-501f6577c1ca

**Comment by himanshu-mind** [comment]
Thanks for the reply.

**Comment by gedw99** [comment]
Thanks for the link to the flutter IDE AppBuilder. Is this open ?
I want to extend it further.

**Comment by g33kidd** [comment]
I don't believe it is. I've looked everywhere and can't seem to find it.

**Comment by MichaelSowah** [comment]
@gedw99 maybe you can try and contact the developer from this https://medium.com/@pmutisya/create-flutter-studio-using-dart-501f6577c1ca
