### ISSUE TITLE
[CP] disable Adreno 506.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#157823]
### Issue Link

 flutter/flutter#155185

### Target

beta

### Cherry pick PR Link

https://github.com/flutter/engine/pull/56216

### Changelog Description

Disable Vulkan usage on Adreno 506 series GPU.

### Impacted Users

Android users on older model hardware

### Impact Description

The Vulkan driver on the Adreno 506 has correctness/rendering bugs.

### Workaround

Disable impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached unit tests. Phone issue was reported on is not easily acquirable.

**Comment by zanderso** [comment]
cp lgtm
