### ISSUE TITLE
FormatException: FormatException: Bad UTF-8 encoding 0xb4 (at offset 91)

### ISSUE THREAD

**Issue by CarefreeTour** [flutter/flutter#15793]
this is compile errors!

**Comment by chinmaygarde** [comment]
Can elaborate on when this crash happened? Did it happen immediately after the run or after a specific action? Are there repro steps or a reduced test case?

**Comment by CarefreeTour** [comment]
I test this case https://github.com/flutter/flutter/tree/master/examples/platform_channel

,but my yaml is 

name: smartalbum
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  image_picker:
  path_provider:
  image: "^1.1.27"
  dart_image: "^1.0.2"
  pool: "^1.3.1"

$ flutter --version
Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (4 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

**Comment by linlexing** [comment]
I also encountered such an error, and later found that it was caused by a java compilation error. May be an error message generated by the grade compile but cannot be read correctly by flutter (with non-English characters?), I am in China.

**Comment by CarefreeTour** [comment]
怎么修改？

**Comment by xqwzts** [comment]
@chinmaygarde Looks like the same issue @linlexing saw, this is a compile time error, but rather than throw a helpful error message it throws a UTF-8/Bad encoding message [I believe the original error was Chinese as well]

**Comment by zoechi** [comment]
@spkingr sounds like you are using relative imports in `lib/main.dart`.
**Don't do that**
If you have only `package:... and `dart:...` imports in `lib/main.dart` you should be able to use mixed imports in all other files inside `lib/...`

**Comment by spkingr** [comment]
@zoechi Em, thanks!

**Comment by Nightmare-MYS** [comment]
So am I ,Bad UTF-8 encoding 0xb4 (at offset 82),I have edited MainActivity.java and it break down,

**Comment by zoechi** [comment]
@Nightmare-MYS please follow #15646.
This issue is long closed.

**Comment by NawazS** [comment]
I had the same problem. Using ENG-UK windows.

Changing my project encoding to UTF-8 also fixed the problem.

File -> Other Settings -> Settings For New Project, then find "File Encodings", change Project Encoding to UTF-8.

**Comment by sdh7700** [comment]
d
