### ISSUE TITLE
What is the best way to start an intent that shows a .pdf file?

### ISSUE THREAD

**Issue by eduardotd** [flutter/flutter#15790]
We are searching for a flutter alternative to a native FileProvider.

Our software manages a local file cache and we need to start an external intent to display  .pdf files.

We already tried android_intent package. With that package, we were able to open the chrome browser but we were not able to pass the .pdf file to display.

Did anyone already make something like that in flutter?

**Comment by NMateu** [comment]
You probably want to use share plugin. https://pub.dartlang.org/packages/share but to share pdf file you must edit a little java file in this plugin https://github.com/flutter/plugins/blob/master/packages/share/android/src/main/java/io/flutter/plugins/share/SharePlugin.java
Pass a file url to pdf file and in java file edit this line https://github.com/flutter/plugins/blob/35604a0ca7a99df5340cf7d5439c1c9e8b58bb48/packages/share/android/src/main/java/io/flutter/plugins/share/SharePlugin.java#L48 to .setDataAndType(Uri.parse("file://" + pathToFile), "application/pdf")) then should work.

**Comment by eduardotd** [comment]
Thank you very much for the direction.

We will try here.

2018-03-21 11:00 GMT-03:00 NMateu <notifications@github.com>:

**Comment by farcasclaudiu** [comment]
maybe this plugin will do https://pub.dartlang.org/packages/open_file

**Comment by zoechi** [comment]
I'd expect https://pub.dartlang.org/packages/url_launcher to do that

**Comment by gerryhigh** [comment]
@zoechi Unfortunately the url_launcher package doesn't implement the setDataAndType (e.g. https://developer.android.com/reference/android/content/Intent.html#setDataAndType(android.net.Uri,%20java.lang.String)) and thus it fails to launch a PDF. I think if the url_launcher package added setDataAndType as an option or it detected the type from the URL and then did a setDataAndType it would work. But as it stands now it will fail to launch a PDF.  As a result I am using the open_file package here: https://pub.dartlang.org/packages/open_file
