### ISSUE TITLE
[impeller] AiksTest_ImageFilteredSaveLayerWithUnboundedContents rendered incorrectly on opengles

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#157956]
seen in dcc8c65eb3d1d43decb52d276b7f29390ea67c9d
test: AiksTest_ImageFilteredSaveLayerWithUnboundedContents

## metal
![impeller_Play_AiksTest_ImageFilteredSaveLayerWithUnboundedContents_Metal](https://github.com/user-attachments/assets/3230f545-d2ec-4e85-bdd5-32fe352acce5)

## opengles
![impeller_Play_AiksTest_ImageFilteredSaveLayerWithUnboundedContents_OpenGLES](https://github.com/user-attachments/assets/a02e2f96-5fb3-4cc3-b32b-d9ddd72279f6)

**Comment by jonahwilliams** [comment]
I think this is a bug with the decal sampling mode.

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/issues/139773
