### ISSUE TITLE
Remove useless utility functions from path_parsing

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#157974]
[blendPoints](https://pub.dev/documentation/path_parsing/latest/path_parsing/blendPoints.html) and [reflectedPoint](https://pub.dev/documentation/path_parsing/latest/path_parsing/reflectedPoint.html) both take and return a private type `_PathOffset`.

These should be made private in the next release.

**Comment by stuartmorgan** [comment]
Isn't this a duplicate of https://github.com/flutter/flutter/issues/157940?

**Comment by kevmoo** [comment]
> Isn't this a duplicate of #157940?

I guess 🤷 didn't go searching before I filed. Good find!
