### ISSUE TITLE
Glitching Text Rendering in Custom Fonts (Cyrillic)

### ISSUE THREAD

**Issue by skippetr** [flutter/flutter#157992]
### Steps to reproduce

We have encountered an intermittent rendering issue in our Flutter application where Cyrillic text using a designated custom font becomes glitched, appearing as a pixelated mess. This error makes the text unreadable and affects the user experience negatively. There is no clear reproducibility pattern for this bug; it has only come to our attention through user feedback and screenshots. No related errors or warnings have been observed in the development logs. We are also interested in knowing if this is a known issue within the Flutter community and seek advice on possible workarounds or fixes.
Most of the rendering issues occur on Samsung devices (SM-A125F, SM-A137F, SM-A105F, SM-J600F), sometimes on others (itel L6006, RMX3201, 220333QNY, vivo 1904) and even one time on iPhone.

### Expected results

When using a custom font (at least Cyrillic) in a Flutter application, text should render clearly and be easily readable, without any distortion or pixelation.

How it should be:
![photo_2024-11-01 13 24 41](https://github.com/user-attachments/assets/3a9089a1-0811-46a0-91f8-559bff7175fc)
![photo_2024-11-01 13 24 45](https://github.com/user-attachments/assets/7e28d4ce-1c42-46ba-967b-862a3db05139)

### Actual results

Occasionally, Cyrillic text rendered using a custom font in the Flutter framework appears as a scrambled mix of pixels, making it indecipherable. There is no indication of any error in the application logs, which suggest that everything is functioning correctly. The issue does not follow a predictable pattern and is only identifiable through user-reported screenshots.

How it can be sometimes:
![photo_2024-11-01 13 24 44](https://github.com/user-attachments/assets/7fc63fd9-fd3f-4113-bbdb-e409edfe07f9)
![photo_2024-11-01 13 24 46](https://github.com/user-attachments/assets/c1e47d35-64a7-4f65-b521-03d776fe281a)
![photo_2024-11-01 13 24 47](https://github.com/user-attachments/assets/1676128a-2106-43af-9233-dea1cfdec235)

### Code sample

<details open><summary>Code sample</summary>

It's very hard to find out which code is necessary here, but actually, it's a pretty basic `Text` widget.

```dart
Text(
  'data',
  style: TextStyle(
    package: 'some.package',
    fontFamily: 'some.fontFamily',
  ),
);
```

</details>

### Logs

There are no logs.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.19.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-RU)
    • Flutter version 3.19.2 on channel stable at /Users/***/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/***/flutter. Consider adding
      /Users/***/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (8 months ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/***/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/***/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.13.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 13 (API 33)
      (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 14.4.1 23E224
      darwin-arm64

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @skippetr, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.24.4) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v` along with a minimal code sample (if possible). We may also need the custom fonts you're using. 

Thank you

**Comment by skippetr** [comment]
Thank you for the guidance. I understand your recommendation to upgrade to the latest stable version of Flutter (3.24.4). However, at this time, our team is unable to upgrade our Flutter version due to certain constraints within our project. Additionally, I am unable to provide the custom fonts we are using, as our company policy restricts the sharing of these resources.

Given these constraints, I believe we may close this issue for now.

**Comment by danagbemava-nc** [comment]
Closing this for now since there's no way for us to take this forward at the moment. 

Please file a new issue when you're able to provide enough information us to act on this. 

Thank you
