### ISSUE TITLE
[Impeller] sanity check existing OpenGL ES goldens

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#157935]
To see if we have any lurking bugs...

**Comment by gaaclarke** [comment]
ran at dcc8c65eb3d1d43decb52d276b7f29390ea67c9d:
- AiksTest_CanRenderRoundedRectWithNonUniformRadii is noticeably more aliased in opengl (impeller_Play_AiksTest_FilledEllipsesRenderCorrectly_OpenGLES too)
- impeller_Play_AiksTest_ColorFilterAdvancedBlend_OpenGLES results are slightly blurry and offset
- impeller_Play_AiksTest_GradientOvalStrokeMaskBlur_OpenGLES has the missing lines (already filed in a bug, should work now: https://github.com/flutter/engine/pull/55717)
- impeller_Play_AiksTest_MaskBlurTexture_OpenGLES has slightly different blurring behavior at the edge of the image (seen in impeller_Play_AiksTest_MaskBlurDoesntStretchContents_OpenGLES too)
- impeller_Play_AiksTest_CanRenderDifferenceClips_OpenGLES renders incorrectly
- impeller_Play_AiksTest_CanRenderLinearGradientWithOverlappingStopsClamp_OpenGLES renders incorrectly (this is the overlapping gradients thing jonah mentioned the other day)
- impeller_Play_AiksTest_CanRenderSweepGradientManyColorsRepeat_OpenGLES has a weird artifact in it
- impeller_Play_AiksTest_ColorMatrixFilterSubpassCollapseOptimization_OpenGLES is missing the black border around the square
- impeller_Play_AiksTest_ImageFilteredSaveLayerWithUnboundedContents_OpenGLES is drawn wrong

## impeller_Play_AiksTest_ColorFilterAdvancedBlend_Metal
![impeller_Play_AiksTest_ColorFilterAdvancedBlend_Metal](https://github.com/user-attachments/assets/332566b6-80ab-424a-9038-f584bdf3dd1d)
impeller_Play_AiksTest_ColorFilterAdvancedBlend_OpenGLES
![impeller_Play_AiksTest_ColorFilterAdvancedBlend_OpenGLES](https://github.com/user-attachments/assets/1b7bde40-91db-4b0d-874e-6683f84aa8ec)

## impeller_Play_AiksTest_CanRenderDifferenceClips_Metal
![impeller_Play_AiksTest_CanRenderDifferenceClips_Metal](https://github.com/user-attachments/assets/8fd049e6-2c02-42bf-a422-4a9be2f1a66d)
![impeller_Play_AiksTest_CanRenderDifferenceClips_OpenGLES](https://github.com/user-attachments/assets/8b9c84d0-1d31-41c2-8472-b6e9469410a6)

## impeller_Play_AiksTest_CanRenderSweepGradientManyColorsRepeat_Metal
![impeller_Play_AiksTest_CanRenderSweepGradientManyColorsRepeat_Metal](https://github.com/user-attachments/assets/1f7fab15-2b55-48ea-bc69-224297bc66be)
impeller_Play_AiksTest_CanRenderSweepGradientManyColorsRepeat_OpenGLES
![impeller_Play_AiksTest_CanRenderSweepGradientManyColorsRepeat_OpenGLES](https://github.com/user-attachments/assets/39604a7d-ae5c-43c7-9bbe-095dbc63258a)

## impeller_Play_AiksTest_ColorMatrixFilterSubpassCollapseOptimization_Metal
![impeller_Play_AiksTest_ColorMatrixFilterSubpassCollapseOptimization_Metal](https://github.com/user-attachments/assets/65d7e1e9-0aba-4d62-ab8f-7f084b0482f1)
impeller_Play_AiksTest_ColorMatrixFilterSubpassCollapseOptimization_OpenGLES
![impeller_Play_AiksTest_ColorMatrixFilterSubpassCollapseOptimization_OpenGLES](https://github.com/user-attachments/assets/72702222-9844-4013-897b-28d32cf68b80)

## impeller_Play_AiksTest_ImageFilteredSaveLayerWithUnboundedContents_Metal
![impeller_Play_AiksTest_ImageFilteredSaveLayerWithUnboundedContents_Metal](https://github.com/user-attachments/assets/3d5b939f-e92d-462b-9844-d520d7a4b3c3)
impeller_Play_AiksTest_ImageFilteredSaveLayerWithUnboundedContents_OpenGLES
![impeller_Play_AiksTest_ImageFilteredSaveLayerWithUnboundedContents_OpenGLES](https://github.com/user-attachments/assets/5b875dd4-f5be-4cb3-b92c-9a36936285fd)

**Comment by gaaclarke** [comment]
Filed issues:
- https://github.com/flutter/flutter/issues/157951
- https://github.com/flutter/flutter/issues/157953
- https://github.com/flutter/flutter/issues/157954
- https://github.com/flutter/flutter/issues/157955
- https://github.com/flutter/flutter/issues/157956
