### ISSUE TITLE
`flutter create` (and other flutter commands) should warn before being destructive

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#15792]
Looks like `flutter create` overwriting files w/o warning bit at least one user:
https://twitter.com/askari01/status/976345575414145024

Thoughts @jcollins-g @tvolkert @mravn-google?

**Comment by jcollins-g** [comment]
The help text for flutter create strongly implies that it won't overwrite existing files.  If it is overwriting files that exist for any reason, that's a bug either in the help text or the code for sure.

Longer term I don't think repair functionality belongs in create.  While they might share some code, user intention is likely to be very different for the two cases and can lead to surprises like this.

**Comment by mravn-google** [comment]
Just reviewed the code for the create command. It certainly pretends to not be overwriting anything.

I have been unable to reproduce so far.

**Comment by eseidelGoogle** [comment]
OK.  I replied to the tweet author.  My understanding of the bug may be false.  I'll just close this unless there is reason to keep it open @jcollins-g ?

**Comment by zoechi** [comment]
A user complained yesterday about such an incident in Gitter. He claimed to have lost important files, but, wasn't willing or able to provide any concrete information about what steps he took and how the affected directories were related, therefore hard to say if it was reliable.
