### ISSUE TITLE
hardware keyboard can not work with some characters,like currency symbols , ‘¿’, etc

### ISSUE THREAD

**Issue by tifcty1** [flutter/flutter#157907]
### version
Andoird API 24, 
Target device: android 7.1.1

### description
My device has a scanner to scan a barcode or QR code, when success, it will input the result to the TextField when the TextField is focused, the interaction is just like the hardware keyboard input, no any sdk or code needed.
eg:
scan result: 2000
Flutter app received : 2000

the scanner can add prefix like '#', and a postfix `<CR>` to complete edit,  it will be 

scan result: 2000
Flutter app received : #2000`<CR>`

and other characters like '?', '.', ',' worked well too.
### problem 
everything works fine until I changed the prefix character to another
#### case 1
With Chinese input keyboard method, when I use '$', flutter app got '￥2000' , not "$2000", it might be some system locale setting? 
only flutter app would got '￥',  I tested with Google's "Message" app, it got '$2000'

https://github.com/user-attachments/assets/da7b816c-aae1-40ed-9d0e-c2f9372d6803

https://github.com/user-attachments/assets/9dda59c6-9aac-4ea8-ba63-40b99cfe4bd2

I got stack traces to 
```
'dart:ui': hooks.dart 
void _dispatchPlatformMessage(String name, ByteData? data, int responseId)


//below image show the data calculated from 
utf8.decode(data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes))
```
the '$' was already changed to '￥'.
![WXWorkCapture_17303446333447](https://github.com/user-attachments/assets/77f12782-5eb5-4c62-a5a0-f619fcc48aa6)

#### case  2
With any Input method, when I use '£', '€', and '¿', I exspect to got '£2000' but it got nothing

I tested with Google's "Message" app, it worked well too.

https://github.com/user-attachments/assets/e0fceb84-e070-4c6b-8710-f4f8e97158df

### Steps
1. Declare a simple demo TextFiled project, like 
```
flutter create --sample=material.TextField.1 mysample
```
![image](https://github.com/user-attachments/assets/e0cd4882-50ef-462b-b343-f7bf3321e3dd)
2. fucos the TextField, and begin to scan.

### Expected results

As Google's 'Message' do

### Actual results

It has been changed.

### Code sample
```
import 'package:flutter/material.dart';

/// Flutter code sample for [TextField].

class ObscuredTextFieldSample extends StatelessWidget {
  const ObscuredTextFieldSample({super.key});

  @override
  Widget build(BuildContext context) {
    return const SizedBox(
      width: 250,
      child: TextField(
//         obscureText: true,
//         decoration: InputDecoration(
//           border: OutlineInputBorder(),
//           labelText: 'Password',
//         ),
      ),
    );
  }
}

class TextFieldExampleApp extends StatelessWidget {
  const TextFieldExampleApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Obscured Textfield')),
        body: const Center(
          child: ObscuredTextFieldSample(),
        ),
      ),
    );
  }
}

void main() => runApp(const TextFieldExampleApp());

```
### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.19045.3803], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.11.5)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.94.2)
[√] Connected device (4 available)
[!] Network resources
    X A cryptographic error occurred while checking "https://pub.flutter-io.cn": Handshake error in client
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware
      installed on your computer.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @tifcty1 

>My device has a scanner to scan a barcode or QR code, when success, it will input the result to the TextField when the TextField is focused

>With Chinese input keyboard method, when I use '$'

I can't imagine how you input text from a scanner (I haven't used it). Could you elaborate on the steps? It will be easier to understand if you can share a demo video for this. Thanks!

Also, can you please check this on the latest Flutter stable or master channels.

**Comment by tifcty1** [comment]
> Hi @tifcty1
> 
> > My device has a scanner to scan a barcode or QR code, when success, it will input the result to the TextField when the TextField is focused
> 
> > With Chinese input keyboard method, when I use '$'
> 
> I can't imagine how you input text from a scanner (I haven't used it). Could you elaborate on the steps? It will be easier to understand if you can share a demo video for this. Thanks!
> 
> Also, can you please check this on the latest Flutter stable or master channels.

Hi @huycozy  Thank you for your reply, I'v upgrade to the latest 3.24.4 and rebuild the sample app. The issues remains.  
I uploaded the video, hope it could help to understand the question.

**Comment by huycozy** [comment]
I see, thanks a lot for the demo video, it's easier to understand. 

My last question: Can you please check on Android native project with EditText to see if the issue also appears there? 

>I got stack traces to

Also, did you debug the code and found it or was there crash stack trace in the output console? If it's crashed, can you please share the entire stack trace here? Thanks!

**Comment by tifcty1** [comment]
> I see, thanks a lot for the demo video, it's easier to understand.
> 
> My last question: Can you please check on Android native project with EditText to see if the issue also appears there?
> 
> > I got stack traces to
> 
> Also, did you debug the code and found it or was there crash stack trace in the output console? If it's crashed, can you please share the entire stack trace here? Thanks!

Hi @huycozy 
The "vm-entrypoint" is the earlist code I can track, and the  character had been changed as previews image showed.

Thank you for your suggestion, I reproduced the issue in jetpack compose app, it is not a flutter issue. I'll try to search other solutions from scanner app itself.

 :)

**Comment by huycozy** [comment]
Thanks for checking that. Hope you can find the cause of this.
