### ISSUE TITLE
[impeller] AiksTest_CanRenderDifferenceClips renders incorrectly for opengles

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#157954]
seen in dcc8c65eb3d1d43decb52d276b7f29390ea67c9d
test: impeller_Play_AiksTest_CanRenderDifferenceClips

## metal
![impeller_Play_AiksTest_CanRenderDifferenceClips_Metal](https://github.com/user-attachments/assets/aa05b1a7-1a75-4687-8da6-4609d27668a9)

## opengles
![impeller_Play_AiksTest_CanRenderDifferenceClips_OpenGLES](https://github.com/user-attachments/assets/86af1435-21af-4e0b-8383-ea208cca0213)

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/153504

**Comment by gaaclarke** [comment]
I'll close this as a dup of https://github.com/flutter/flutter/issues/153504
