### ISSUE TITLE
Embedder: Refactor EmbedderTest to separate Metal, Vulkan, GL, Software backends

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#157942]
Today classes like [`EmbedderConfigBuilder`](https://github.com/flutter/engine/blob/a65f1d59edc618ae81e2e8ed78d59fb729291afa/shell/platform/embedder/tests/embedder_config_builder.h#L133-L143) and [`EmbedderTestBackingStoreProducer`](https://github.com/flutter/engine/blob/a65f1d59edc618ae81e2e8ed78d59fb729291afa/shell/platform/embedder/tests/embedder_test_backingstore_producer.h#L16-L26) are full of `#ifdef`s for `SHELL_ENABLE_METAL`, `SHELL_ENABLE_VULKAN`, `SHELL_ENABLE_GL` etc.

Because this is all stock C++ code, we can't include Objective-C types in any headers transitively imported into any of them. This is problematic for Metal code since it precludes the usage of `id<MTLDevice>`, `id<MTLCommandQueue>` etc. in classes such as [`TestMetalContext`](https://github.com/flutter/engine/blob/main/testing/test_metal_context.h#L41-L42), forcing us back to manual reference counting via `__bridge_retained` and `__bridge_transfer`.

Instead, we should break this code apart by backend, and implement the Metal code in Objective-C++.

**Comment by jonahwilliams** [comment]
Embeeeeeder

**Comment by cbracken** [comment]
Somehow forgot I'd filed this but it's a dupe of https://github.com/flutter/flutter/issues/158998, which is where all the action is.
