### ISSUE TITLE
google_sign_in does not provide offline capabilities

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#15796]
## Steps to Reproduce

1. Create an app which uses `google_sign_in` plugin
2. Run it on a device, sign in with Google
3. Stop the app
4. Turn on airplane mode
5. Open the app, attempt to call `signInSilently`

Expected result: returns already signed in user account

Actual result: `null`

I'm using it in conjunction with `firebase_auth` plugin which does work when offline. However in my project I'm using other Google APIs which require `accessToken` and I can only get it from `google_sign_in` plugin, so I can't fully initialize authorized user when the app starts while offline.

Creating this issue for tracking purposes. I might be able to work on updating the plugin to support this in coming weeks.

Preliminary research tells that native SDKs provide a way to fetch current user.

On iOS can probably use currentUser property:
https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_sign_in.html#ac49bf5dabe7b89781cd58e69cb015651

On Android - most likely getLastSignInAccount:
https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignIn.html#getLastSignedInAccount(android.content.Context)

Though it'd probably be a breaking change as `GoogleSignIn.currentUser` is already used and it would have to be changed to return `Future<GoogleSignInAccount>`.

**Comment by pulyaevskiy** [comment]
A small update. After some more debugging it looks like on iOS when device is in airplane mode I get `kGIDSignInErrorCodeHasNoAuthInKeychain` from `signInSilently`.

So this may be just an edge case issue.

**Comment by pulyaevskiy** [comment]
It looks like native SDKs do not support offline mode at all.
After tweaking plugin's source code I discovered that native side actually throws some sort of socket exception (`NSURLErrorDomain` or similar) when attempting `signInSilently` while offline.

However it gets silenced by the Dart side:
https://github.com/flutter/plugins/blob/35604a0ca7a99df5340cf7d5439c1c9e8b58bb48/packages/google_sign_in/lib/google_sign_in.dart#L220-L225

Thinking about it more it seems like Dart side should probably rethrow everything, because currently it gives false impression that silent sign in actually worked but there was no authenticated user.

For this issue though (enable offline mode in google sign in) it doesn't seem possible to achieve without support from native SDKs, so it should probably be tagged as blocked.

**Comment by js1972** [comment]
I've run into the same issue - so sounds like we cannot currently use google_sign_in with apps that require offline.

**Comment by pulyaevskiy** [comment]
The only way I found this could be solved is by writing a plugin to wrap AppAuth: https://appauth.io .

As added benefit AppAuth can potentially handle multiple authenticated accounts at the same time, which is not possible with google sign in.

**Comment by js1972** [comment]
@pulyaevskiy thanks for the info on appauth.io; I'll check them out. I actually plan on using custom sign-in to firebase as we need to authenticate with Azure AD (for which I've already written a plugin based around the flutter webview). So I'm hoping that that will persist the user session when offline and after an app restart unlike google_sign_in.

I created a test app using google_sign_in to proof firebase's offline capabilities where I hit the issues noted in this incident.

Interesting that RFC8252 recommends against using webviews; so at some stage looks like I'll have to redo things using something like appauth. Though I'm still unsure as to how remote the threat would be.

You're not publishing you plugin by any chance?   ;-)

**Comment by pulyaevskiy** [comment]
> You're not publishing you plugin by any chance? ;-)
 
If/when I get to the point of writing it I’ll definitely publish it as open source. For now I’m still using google sign in

**Comment by js1972** [comment]
No problem... if I beat you to it, I'll do the same...  ;-)

**Comment by nickolas-pohilets** [comment]
FirebaseAuth does provide offline capabilities. You can sign-in with Google and use Google credentials to sign-in with Firebase. After successful Firebase sign-in you don't need Google credentials anymore, so  you can sign-out from Google right away.

**Comment by hillelcoren** [comment]
We're still working on a similar problem, I believe this PR may help (please upvote if it does).

https://github.com/flutter/plugins/pull/2116

The PR add support for serverAuthCode which according to this doc can be used server-side to enable offline support.

https://developers.google.com/identity/sign-in/web/server-side-flow

**Comment by M1Joe** [comment]
> FirebaseAuth does provide offline capabilities. You can sign-in with Google and use Google credentials to sign-in with Firebase. After successful Firebase sign-in you don't need Google credentials anymore, so you can sign-out from Google right away.

Thanks @nickolas-pohilets this was a super helpful point.  Any idea how long Firebase caches the user info for? I couldn't seem to find that anywhere.

**Comment by rebeccamcfadden** [comment]
> FirebaseAuth does provide offline capabilities. You can sign-in with Google and use Google credentials to sign-in with Firebase. After successful Firebase sign-in you don't need Google credentials anymore, so you can sign-out from Google right away.

This is true, but any api calls to google apps will need current access tokens which I don't believe you can get from firebase (correct me if I'm wrong). Is there any way to get offline mode for this purpose?

**Comment by rebeccamcfadden** [comment]
As stated in [this issue ](https://github.com/FirebaseExtended/flutterfire/issues/1079), Firebase auth focuses on AuthN, not AuthZ. Google_sign_in as of now also doesn't allow for refreshing AuthZ type credentials

**Comment by fbcouch** [comment]
Does the solution in this PR fix this issue as well? https://github.com/flutter/plugins/pull/3356 (It is solving a similar problem – forcing Google Sign In to return a serverAuthCode that can be exchanged for a refresh token)

**Comment by stuartmorgan** [comment]
> It looks like native SDKs do not support offline mode at all

Since the purpose of the plugin is to wrap the native SDKs, closing given this.
