### ISSUE TITLE
 FlutterView imposes FULL_SCREEN flag on any activity

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#15799]
Currently putting FlutterView into an existing activity on Android causes bizarre layout issues. The root cause is the following chain of calls:

activity.onPostResume()
flutterView.onPostResume()
==> invokes lifecycle listeners, one of which is PlatformPlugin
[plugin.onPostResume()](https://github.com/flutter/engine/blob/2114a88b5ee0c5240f2aec6cde164798d00b61b4/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L258)
updateSystemUiOverlays()
which ends up setting the [FULL_SCREEN flag](https://github.com/flutter/engine/blob/2114a88b5ee0c5240f2aec6cde164798d00b61b4/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L33).

My solution for now is either not call `postResume` or undo the effect of `updateSystemUiOverlays()`. Neither of these are appetizing so we should allow apps to modify this behavior, perhaps by detecting if FlutterView is at the root of an activity's content view.

**Comment by lukef** [comment]
I feel like there are other issues with the way that Flutter takes control of the "chrome" in Android. It is often impossible to make Android obey the light statusbar flag also. It'd be great if they could be controlled manually.

**Comment by Hixie** [comment]
We probably should do the logic in updateSystemUiOverlays if we've received a message from Dart about it. And then we should make the Dart code have a flag to not send any updates along these lines.

Or will this cause problems in normal Flutter apps? (Are our defaults different from Android's?)

**Comment by jonahwilliams** [comment]
@lukef  Regarding the light status bar: Previous the NavBar and AppBar widgets called `SystemChrome.setSystemUIOverlayStyle` in their build methods to update system chrome styles, which would overwrite anything set on the android side.  I've updated this with a different implementation which can be disabled. On the `RenderView` class, there is a member called `automaticSystemUiAdjustment` which can be set to false to disable this.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/view.dart#L104

Perhaps we should expand this behavior to the ui overlays as well?

**Comment by mit-mit** [comment]
This has been resolved in the `module` template, which does not force full screen.
