### ISSUE TITLE
Strictly enforce that a plugin package's pub version is bumped with a change log on each PR

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15803]
Posse has been bitten by this on a few occasions where 

- Multiple developers getting the same package version and building at different times results in different behaviour
- Critical PRs aren't updated onto users' machines because they already have the 'same' pub version

We should enforce that every significant PR is accompanied by a pubspec version bump, a changelog addition and a new upload to pub.

**Comment by zoechi** [comment]
> getting the same package version and building at different times results in different behaviour

I think this can only happen if they use Git dependencies instead of hosted (pub.dartlang.org default) They could use a commit has instead of the pub version.
Pub enforces each published version to have an incremented version.
So the only one left should be the changelog entry.

**Comment by mklim** [comment]
We've since created a tool to check the changelog version in the presubmit, but it has an outstanding known issue with CHANGELOG: flutter/flutter#44749. Closing this since it's a little outdated.
