### ISSUE TITLE
[in_app_purchase] Got crash for iOS 18.2 when purchase

### ISSUE THREAD

**Issue by bohowu** [flutter/flutter#158097]
### Steps to reproduce

1. On iOS 18.2 calling buyNonConsumable api will crash

### Expected results

Should not crash.

### Actual results

Got 
Fatal Exception: NSInvalidArgumentException -[NSNull length]
in Xcode

### Code sample

<details open><summary>Code sample</summary>

```dart
PurchaseParam purchaseParam =
            PurchaseParam(productDetails: product, applicationUserName: null);
        _connection.buyNonConsumable(purchaseParam: purchaseParam);
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)

```

</details>

**Comment by hank1233211** [comment]
This problem seems to be a problem with iOS 18.2. Try assigning a value to applicationUserName. This is how I solved it.

**Comment by darshankawar** [comment]
@bohowu 
Can you provide complete crash log ? If you pass value to `applicationUserName`, does it still crash ?

**Comment by bohowu** [comment]
> @bohowu Can you provide complete crash log ? If you pass value to `applicationUserName`, does it still crash ?

It won't crash if adding `applicationUserName` value.

**Comment by darshankawar** [comment]
@bohowu 
According to [this](https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername#discussion) documentation, we need to provide UUID to `applicationUserName`. Since you were passing null, hence you were getting a crash. Since passing a value it is not crashing, I will close it as solved. If you disagree, write in comments and I'll reopen it.
