### ISSUE TITLE
Gallery App has Colors

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1580]
From https://www.google.com/design/spec/style/color.html#color-color-palette

- [ ] Shows various color palettes

(note: it's not necessary to show all palette combinations in the gallery app. A smaller set is sufficient.)

**Comment by Hixie** [comment]
We should probably also provide a higher-level way to change the theme across the gallery, so that you can look at all the various parts of the app with different themes. Ideally we'd do this somewhere where you can enjoy the animated transition between themes.

**Comment by sethladd** [comment]
@Hixie sounds like you're talking about https://github.com/flutter/flutter/issues/1569 ?

**Comment by Hixie** [comment]
Ah, right.
