### ISSUE TITLE
There's no way to assign an aria-level to Widgets with Semantics(header: true)

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#158029]
### Steps to reproduce

1) Open dev tools
2) Enable accessibility
3) Inspect text with Semantics(header: true)

### Expected results

<flt-semantics id="flt-semantic-node-4" role="heading" **aria-level=1** style="position: absolute; overflow: visible; width: 74.6162px; height: 20px; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, 800.692, 634.5); pointer-events: all; z-index: 1;">Hello World</flt-semantics>

### Actual results

<flt-semantics id="flt-semantic-node-4" role="heading" style="position: absolute; overflow: visible; width: 74.6162px; height: 20px; transform-origin: 0px 0px 0px; transform: matrix(1, 0, 0, 1, 800.692, 634.5); pointer-events: all; z-index: 1;">Hello World</flt-semantics>

no aria-level found

### Code sample

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Repro examples'),
        ),
        body: Center(
          child: Semantics(header: true, child: Text('Hello World')),
        ),
      ),
    );

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by franciscojma86** [comment]
b/331475013

**Comment by franciscojma86** [comment]
b/328627991

**Comment by darshankawar** [comment]
@franciscojma86 
Can you please check [this](https://github.com/flutter/flutter/issues/151929) issue with underlying comments and also [this](https://github.com/flutter/flutter/issues/156203#issuecomment-2394523592) comment to see if it helps in your case ?
