### ISSUE TITLE
Text is not searchable in browser search.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#158079]
Repro:
1. Create web-app with MaterialApp with title, Markdown of flutter_markdown, and Text
2. Open  the app in Chrome on desktop
3. Press Ctrl+F
4. See that not texts are searchable

Reading this post it seems it is regression, as it worked before: https://stackoverflow.com/questions/62448168/can-text-in-a-flutter-web-app-be-made-searchable

**Comment by danagbemava-nc** [comment]
Hi @polina-c, this was never properly implemented and if it worked, it was likely by accident. There's an issue tracking support for this in https://github.com/flutter/flutter/issues/65504

Kindly follow up in the original issue for updates. 

Closing from here as duplicate. 

Thank you
