### ISSUE TITLE
'/usr/lib/swift/Flutter.framework/Flutter' (no such file, not in dyld cache)

### ISSUE THREAD

**Issue by ClaudinNarsis** [flutter/flutter#158090]
### Steps to reproduce

https://github.com/Photo-Owl/bringer-cam-dev-v2/tree/ios
(The code on **iOS** branch is causing this issue while trying to run on Apple silicon )
run the following commands on the root of the project
1. dart pub cache clean
2. flutter clean
3. cd ios
4. pod deintegrate
5. rm -rf Pod podfile.lock
6. cd ../
7. flutter pub get
8. cd ios
9. arch -x86_64 pod install
10. cd ../
11. flutter run

### Expected results

The Flutter Engine should start, and the app should go to the initial route

### Actual results

The app starts and shows an empty white screen (LaunchScreen)

### Code sample

<details open><summary>Code sample</summary>

https://github.com/Photo-Owl/bringer-cam-dev-v2/tree/ios

simply running this app in ios would replicate the issue

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
nick@Nickys-MacBook-Air photoowldev % flutter run --debug
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running pod install...                                             27.9s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        28.9s
Xcode build done.  
```

But while running the app, i get this log 
```console
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/Flutter.framework/Flutter
Referenced from: <90307E20-FBC3-3BA8-A479-7B0D1925DEBB> /Users/USER/Library/Developer/CoreSimulator/Devices/09DA24B2-C683-47BB-8C9B-B8DCD796B79B/data/Containers/Bundle/Application/64AB2C0D-C126-4E83-8835-86E68F8DF908/Runner.app/Runner.debug.dylib
Reason: tried: '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/Flutter.framework/Flutter' (no such file), '/usr/lib/swift/Flutter.framework/Flutter' (no such file, not in dyld cache), '/Users/nick/Library/Developer/CoreSimulator/Devices/09DA24B2-C683-47BB-8C9B-B8DCD796B79B/data/Containers/Bundle/Application/64AB2C0D-C126-4E83-8835-86E68F8DF908/Runner.app/Frameworks/Flutter.framework/Flutter' (no such file), '/Users/nick/Library/Developer/CoreSimulator/Devices/09DA24B2-C683-47BB-8C9B-B8DCD796B79B/data/Containers/Bundle/Application/64AB2C0D-C126-4E83-8835-86E68F8DF908/Runner.app/Frameworks/Flutt
(terminated at launch; ignore backtrace)
```

fully summary of crash available here
https://pastebin.com/Y3RWV0T1
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
nick@Nickys-MacBook-Air ~ % flutter doctor -v
[!] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale
    en-IN)
    • Flutter version 3.24.4 on channel stable at
      /Users/nick/development/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/nick/Development/flutter/bin/flutter, which is not inside your
      current Flutter SDK checkout at /Users/nick/development/flutter. Consider
      adding /Users/nick/development/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/nick/Development/flutter/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/nick/development/flutter. Consider adding
      /Users/nick/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (11 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.95.1)
    • VS Code at /Applications/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (2 available)
    • macOS (desktop)                 • macos                 • darwin-arm64 • macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin       • macOS 15.1 24B83 darwin-arm64
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.
```

</details>

**Comment by darshankawar** [comment]
> run the following commands on the root of the project

@ClaudinNarsis Can you elaborate why do we need to follow these commands before running the app ?

> 9\. arch -x86_64 pod install

Also, specifying this arch type can be related to https://github.com/flutter/flutter/issues/125647. If you run pod install without specifying this type, does it work or still give same error ?


> ```
> Library not loaded: @rpath/Flutter.framework/Flutter
> ```

For this, although it doesn't look like a third party, but check https://github.com/flutter/flutter/issues/115053#issuecomment-1340161984

Also, the repo you shared contains lot of third party packages, please try to narrow it down to only framework code to see if it still replicates or not.

**Comment by ClaudinNarsis** [comment]
Running pod install without specifying this type also gives the same issue

I looked into [this comment](https://github.com/flutter/flutter/issues/115053#issuecomment-1340161984) but the error is from Flutter.

I am also attaching the console log from Xcode for additional information.
https://pastebin.com/4iMj4QXQ

I'll narrow it down to framework code and post the results soon

**Comment by ClaudinNarsis** [comment]
Hey @darshankawar , This is a high priority for us. Please help us solve it

**Comment by darshankawar** [comment]
@ClaudinNarsis 
Check if [this](https://github.com/flutter/flutter/issues/143436#issuecomment-1965542511) helps in your case or not.

**Comment by ClaudinNarsis** [comment]
<img width="1440" alt="Screenshot 2024-11-05 at 12 05 51 PM" src="https://github.com/user-attachments/assets/d1d481c3-ee41-4cad-9069-1e8fe382dc63">

Hey @darshankawar , Thanks for the help, it seems the script was only running for install builds. turning off the checkbox solved the issue.
