### ISSUE TITLE
firebase - documentation - setup

### ISSUE THREAD

**Issue by acidjazz** [flutter/flutter#15805]
I was trying to install firebase via the firebase_storage package and had difficulties, later i found following the instructions at https://pub.dartlang.org/packages/firebase_auth in order to properly install it.

Apologies if this issue isn't made at the right repo, but I'd like to suggest we add notes to each firebase package that people need to go through this process for installing and setting up firebase for the 1st time.

**Comment by chinmaygarde** [comment]
cc @collinjackson

**Comment by collinjackson** [comment]
cc @wmleler

**Comment by kroikie** [comment]
@acidjazz

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/879. Any further collaboration will be done there.
