### ISSUE TITLE
The getter 'ui' isn't defined for the class '_MaterialAppState'

### ISSUE THREAD

**Issue by codetotech** [flutter/flutter#158077]
### Steps to reproduce

1 -run and compile flutter app on mac m2 with sequoia os
2- I use androidstudio ladybug Android Studio Ladybug Feature Drop | 2024.2.2 Canary 9
Build #AI-242.23339.11.2422.12584204, built on October 31, 2024
Runtime version: 21.0.4+-12422083-b607.1 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  Dart (242.22855.32)
  io.flutter (82.0.3)

```
3- Error
- '_MaterialAppState' is from 'package:flutter/src/material/app.dart' ('../../developer/flutter/packages/flutter/lib/src/material/app.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ui'.
      || (mode == ThemeMode.system && platformBrightness == ui.Brightness.dark);
                                                            ^^
Failed to compile application.
```

4- I've the error every time I use -materialappstate, ui.Brightness, with or without import dart:ui

### Expected results

compile application

### Actual results

```
../../developer/flutter/packages/flutter/lib/src/material/app.dart:940:61: Error: The getter 'ui' isn't defined for the class '_MaterialAppState'.
 - '_MaterialAppState' is from 'package:flutter/src/material/app.dart' ('../../developer/flutter/packages/flutter/lib/src/material/app.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ui'.
      || (mode == ThemeMode.system && platformBrightness == ui.Brightness.dark);
                                                            ^^
Failed to compile application.
```

### Code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.system,
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    final brightness = MediaQuery.of(context).platformBrightness;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Home Page'),
      ),
      body: Center(
        child: Text(
          'Current brightness: $brightness',
          style: TextStyle(fontSize: 24),
        ),
      ),
    );
  }
}

class CustomThemeWidget extends StatelessWidget {
  final Widget child;

  const CustomThemeWidget({required this.child});

  @override
  Widget build(BuildContext context) {
    final brightness = MediaQuery.of(context).platformBrightness;

    return Theme(
      data: brightness == Brightness.dark ? ThemeData.dark() : ThemeData.light(),
      child: child,
    );
  }
}

class AnotherClass extends StatelessWidget {
  const AnotherClass({super.key});

  @override
  Widget build(BuildContext context) {
    return CustomThemeWidget(
      child: Container(
        color: Colors.white,
        child: Center(
          child: Text(
            'Another brightness: ${MediaQuery.of(context).platformBrightness}',
            style: TextStyle(fontSize: 24),
          ),
        ),
      ),
    );
  }
}

```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media 
![Screenshot 2024-11-03 alle 16 55 50](https://github.com/user-attachments/assets/e47acc5e-d24b-4867-a29b-dfc2bb66546f)
here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale it-IT)
    • Flutter version 3.24.4 on channel stable at /Users/idtc/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (10 giorni fa), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/idtc/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)



</details>

**Comment by codetotech** [comment]
thanks in advance for every hints that could bring to a solution.....

**Comment by darshankawar** [comment]
@codetotech 
Please try to format the code and error log for better readability. 
I am not getting the said error although I am not on M2 and using latest AS version, which doesn't seem to have to do with the error you are getting.
It seems it is related to your flutter sdk which may not be properly / completely installed or may be corrupted. If you create a new Flutter project and try to run, does it work ? If so, if you copy paste the code sample provided in new project and run, does it work ?

**Comment by codetotech** [comment]
Hi there, thanks to darshankawar for some ideas.....

I will be able to find a solution in that way:
1- delete my:
a-  flutter sdk installation
b- android studio installation
c- vscode

2- after a restart I install:
a- flutter sdk and check all the path to ".zshrc" profile
b- reinstall android studio (upgrade to a version) actually this (I found only in the english channel):
Android Studio Ladybug Feature Drop | 2024.2.2 Canary 9
Build #AI-242.23339.11.2422.12584204, built on October 31, 2024
Runtime version: 21.0.4+-12422083-b607.1 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
c- reinstall plugin flutter plugin have a new update to version 82.1.3.
d- reinstall vscode same version
e- update flutter plugin on intellij

3- now after a retstr of the ide and a restart of the machine i chec my flutter app code and make a clean in that way:

1- $ dart fix --dry-run
2- $ dart fix --apply

then use:
1- $ flutter clean
2-$ flutter pub get (only when I think was necessary)...... make the outdated as request...
3-$ flutter run (you could also in alternative use the graphical command to run the app)

4- And at the end all my error and warning disappear without change a single line of the source code of the app,
at the contrary of the suggestion in no-pass check that I have before the brand new install.

Hope that helps who as me develop on apple m2 machine on flutter via androidstudio (and encounter this:
 '_MaterialAppState' is from 'package:flutter/src/material/app.dart' ('../../developer/flutter/packages/flutter/lib/src/material/app.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ui'.
      || (mode == ThemeMode.system && platformBrightness == ui.Brightness.dark);

:) bye and happy coding....

**Comment by codetotech** [comment]
completed
