### ISSUE TITLE
The fontWeight differs dependant on renderer

### ISSUE THREAD

**Issue by komakur** [flutter/flutter#158163]
### Steps to reproduce

I've been using Flutter 3.22.0 with html renderer.
Switched to default renderer - canvaskit.
And all text became thinner.

### Expected results

![image](https://github.com/user-attachments/assets/ff9d7718-971b-40bd-9e71-91e0a6585cc8)

 The fonts representation shouldn't change.

### Actual results

![image](https://github.com/user-attachments/assets/8d4b2075-c6c4-4ec9-9e43-0888dc53e9e4)
 All the fonts became thinner.

### Code sample

You can use flutter counter example.

### Screenshots or Video

![image](https://github.com/user-attachments/assets/09e4c238-9ec2-4d3e-8e3c-48412d68088f)
 Here you can see how they differs

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 15.1 24B83 darwin-arm64, locale en-US)
    • Flutter version 3.22.0 on channel stable at /Users/admin/fvm/versions/3.22.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.95.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1 24B83 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 130.0.6723.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@komakur 
Please check [this](https://github.com/flutter/flutter/issues/80103#issuecomment-2136271189) comment for reason behind the difference you are seeing. Will close in favor of it.
Also, you may follow-up in https://github.com/flutter/flutter/issues/137834 for further reference.
If you disagree, write in comments and I'll reopen it.

**Comment by komakur** [comment]
Hello, @darshankawar
The problem is also that canvaskit is ignoring w500.

![image](https://github.com/user-attachments/assets/e6968efc-51b5-4eda-a4f4-f96008a19246)

**Comment by komakur** [comment]
Oh, not only w500...

<img width="1478" alt="image" src="https://github.com/user-attachments/assets/3927b725-dd85-4752-8baa-e3d3823a2f1a">

**Comment by darshankawar** [comment]
See https://github.com/flutter/flutter/issues/75832 for your reference.
