### ISSUE TITLE
Long NavigationBar tab titles can't be padded from the sides of the screen

### ISSUE THREAD

**Issue by math1man** [flutter/flutter#158130]
### Steps to reproduce

1. Run the code sample below in DartPad
2. Adjust the width of the Flutter window and observe the behavior of the labels relative to the window edges and each other.

### Expected results

There should be a way to apply padding between the tab labels and the edges of the screen.

### Actual results

There is no padding, and I don't believe there is any way to apply such padding.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: const Center(
          child: Text('Hello, World!'),
        ),
        bottomNavigationBar: NavigationBar(
          destinations: [
            NavigationDestination(
              icon: Icon(Icons.add),
              label: 'Long tab name one',
            ),
            NavigationDestination(
              icon: Icon(Icons.add),
              label: 'Long tab name two',
            ),
            NavigationDestination(
              icon: Icon(Icons.add),
              label: 'Long tab name three',
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/041e794f-549d-43ff-9907-4d014dea74ac)

</details>

### Flutter Doctor output

Internal google client, skipping Flutter Doctor output

**Comment by TahaTesser** [comment]
@polina-c 
Thanks for the update! I'll work on it tomorrow :)

**Comment by TahaTesser** [comment]
Filed a fix https://github.com/flutter/flutter/pull/158260
