### ISSUE TITLE
Add mechanism for entirely offline development (including resolving dependencies)

### ISSUE THREAD

**Issue by abmoudz** [flutter/flutter#15817]
Hello i am having some trouble with flutter when i try to run the app 
well my issue is am in company proxy internet so i am strugling with dart and flutter 
i tried the 

`set http_proxy=adress:ip `
solution and it didnt work 

so i am wendering can i resolve dependecies OFFLINE
if there is any thing that i can download and put on some folder and run the app 
the big question is how to run flutter app without having to be on the internet at all

**Comment by Hixie** [comment]
cc @mit-mit @kevmoo (not sure who is the right person, please cc them accordingly)

**Comment by kevmoo** [comment]
You can run `pub get --offline` – or the flutter equivalent. That will use any packages you have in your local cache.

**Comment by zoechi** [comment]
`flutter packages get --offline` in this case
and perhaps `flutter packages pub cache add -h`

**Comment by pejalo** [comment]
It would be awesome if Android Studio had a solution for this. I recently opened my laptop on a plane expecting to be able to play around with my Flutter project, and it would not run, and obviously I couldn't look up how to get it to run.

**Comment by 5yunus2efendi** [comment]
> You can run `pub get --offline` – or the flutter equivalent. That will use any packages you have in your local cache.

May I ask where is the local cache directory?

**Comment by zoechi** [comment]
@5yunus2efendi check the created `.packages` file. It contains paths to the local cache of all direct and transitive dependencies.

**Comment by Justin-Randall** [comment]
What about Maven and Android build dependencies?

**Comment by lukepighetti** [comment]
Offline development (or at least poor internet access) would be nice to have. I'm on a train ride and can use my hotspot but the reception is pretty spotty.

**Comment by zanderso** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/22429
