### ISSUE TITLE
[CP] Disable thread merging for iOS

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#158185]
### Issue Link

N/A

### Target

beta

### Cherry pick PR Link

https://github.com/flutter/engine/pull/56378

### Changelog Description

* Disable thread merging behavior on iOS until feature is fully baked.

We could leave out this changelog entry.

### Impacted Users

all iOS users

### Impact Description

I do not believe the thread merging behavior has been sufficiently tested, as it landed very close to the release cut.

### Workaround

N/A

### Risk

low

### Test Coverage

yes

### Validation Steps

Restores existing behavior, covered by unit tests and implicitly tested by all of our CI.

**Comment by zanderso** [comment]
cp lgtm
