### ISSUE TITLE
Issue from website page Using Packages

### ISSUE THREAD

**Issue by shyjuzz** [flutter/flutter#15815]
From URL: https://flutter.io/using-packages.md

got the below exception when using the plugin async_loader

 Another exception was thrown: NoSuchMethodError: The method 'reloadState' was called on null.

**Comment by zoechi** [comment]
Where did you get the URL from?
It is not valid. I saw similar invalid URLs frequently recently. 

There is more information necessary to diagnose your problem.
- Output of `flutter doctor -v`
- content of `pubspec.yaml`
- what code and what action caused the exception

**Comment by Hixie** [comment]
@shyjuzz Can you provide us with the information @zoechi mentions? Without it it's not clear how we can help. Thanks.
