### ISSUE TITLE
Selection controls flicker when using "Scribble" feature on iOS

### ISSUE THREAD

**Issue by PrimaryFeather** [flutter/flutter#158177]
### Steps to reproduce

Add a `TextField` or a `CupertinoTextField` to the application (see sample code below) and enter text with an Apple Pencil via [scribble](https://support.apple.com/guide/ipad/enter-text-with-scribble-ipad355ab2a7/ipados). 

In principle, it will work, but the toolbar with the selection controls will flicker wildly; especially when trying to select some text by wiping over it. (See video below).

There is actually an easy fix. Just add the following argument:

```dart
CupertinoTextField(           
    selectionControls: cupertinoTextSelectionControls,
);
```

Of course, the default setup should work, just as well.

### Expected results

Scribble should work without any flickering of the selection toolbar.

### Actual results

With the default settings, the toolbar will flicker wildly - although scribbling still works in principle.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 450),
            child: CupertinoTextField(
              scribbleEnabled: true,
              // enable this line for a fix:
              // selectionControls: cupertinoTextSelectionControls,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Here's how the toolbar will flicker with the standard _TextField_ / _CupertinoTextField_ settings:

https://github.com/user-attachments/assets/00609b14-d6f4-4e85-9797-1a03e015f0d4

And here is how it looks with the workaround. This is what I'd expect in all cases.

https://github.com/user-attachments/assets/6bac3b88-ad0c-450d-aa6e-3b8de7dc97d3
</details>

### Logs

<details open><summary>Logs</summary>
(not applicable)
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Users/redge/Shared/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (12 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/redge/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.101.20241031

[✓] Connected device (5 available)
    • Daniels iPad Air (mobile)       • 00008112-000108C13E81A01E • ios            • iOS 18.1 22B83
    • iPhone Mini Daniel (mobile)     • 00008110-001C410C2112401E • ios            • iOS 18.1 22B83
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1 24B83 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 130.0.6723.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Thank you for the report! Reproduced this on Flutter beta `3.27.0-0.1.pre` and master `3.27.0-1.0.pre.393` channels as well, on `iPad Air 5 (iPadOS 17.5.1)`.

**Comment by PrimaryFeather** [comment]
Thanks for taking the time to reproduce the issue, @huycozy! If there is anything I can do to help, just let me know. 🙏

**Comment by justinmc** [comment]
FYI @fbcouch since you worked on Scribble, in case you have any ideas.

**Comment by fbcouch** [comment]
I wonder if something changed where this no longer has a default or is trying to default to the system menu?

It's been awhile, but I had originally returned false from the canPerformAction selector in the FlutterTextInputPlugin because the native toolbar would pop up - https://github.com/flutter/engine/commit/1ae721c0230e8e3f3618f7e9d301ad2133b2fd61#diff-4c7b102c0690b8ec5e2212b079f5d69fe3f816c84e47ce94bc7bc89312f39e40R1014 - it looks like that has changed now, so it could be related to that, but maybe the combination of changes to that method and something else.

**Comment by jmagman** [comment]
@justinmc is this fixed by https://github.com/flutter/flutter/pull/159508?

**Comment by jmagman** [comment]
Or @PrimaryFeather maybe you can verify since you also filed https://github.com/flutter/flutter/issues/159259 ?

**Comment by PrimaryFeather** [comment]
Thus, I'm closing this issue. 👍
