### ISSUE TITLE
Flutter iOS- The flutter webview on an iOS device fails to load assets, images, and CSS files with relative URLs from the local directory.

### ISSUE THREAD

**Issue by yadavsunilmagic** [flutter/flutter#158157]
Flutter web view- I am downloading assets from server and using that assets to create html file to load on web view. I downloaded them to the local document directory on the device. From there I can load the HTML files in a webview using the file:// schema, with the benefit that images, css etc. that are referenced in the HTML are loaded as well.

This works fine in Android (simulator and real device) as well as in an iOS simulator. But on an iOS device the flutter webview fails to load assets , images & css files with a relative URL from local directory.

This is strange as the iOS simulator should behave the same in that case (as it is not really a hardware related issue).

Help me out from this issue.

**Comment by darshankawar** [comment]
@yadavsunilmagic 
When you open an issue, please try to use new issue template, fill out requested details so that we'll have enough info to work with. 
Just describing the issue without any code sample, flutter doctor or any error log, we can't properly address it.
Closing for now due to lack of details.

**Comment by yadavsunilmagic** [comment]
Flutter web view- I am downloading assets from server and using that assets to create html file to load on web view. I downloaded them to the local document directory on the device. From there I can load the HTML files in a webview using the file:// schema, with the benefit that images, css etc. that are referenced in the HTML are loaded as well.

This works fine in Android (simulator and real device) as well as in an iOS simulator. But on an iOS device the flutter webview fails to load assets , images & css files with a relative URL from local directory.

This is strange as the iOS simulator should behave the same in that case (as it is not really a hardware related issue).

What should i do?
