### ISSUE TITLE
Flutter Delete My data.

### ISSUE THREAD

**Issue by ishbo** [flutter/flutter#15818]
Hello i have just set the project location for flutter and , after that flutter deleted my whole data except two folder which was in that folder.

For Example  - i have set a folder with name "DATA" for project location and after some time what i have found in that folder is totally undesirable my whole important data were replaced with a idea folder.
Please tell me the way to recover that or i promise i will sue google for that.

**Comment by zoechi** [comment]
As mentioned in Gitter, without more specific information what steps exactly led to the data loss.
 
There is no way to tell you from here how to recover lost data. You can try recovery tools or check if you have backups, but otherwise I'm afraid there isn't much anybody can do.

**Comment by Hixie** [comment]
@ishbo Can you describe the precise steps that we can follow to reproduce this problem?
