### ISSUE TITLE
Roboto Bold renders differently than what you see in Google's Roboto Font page

### ISSUE THREAD

**Issue by bramvbilsen** [flutter/flutter#15811]
I'm using a normal `Text` widget to display some text. But like you can see in this image: 
![capture](https://user-images.githubusercontent.com/16825392/37745741-da0bb86a-2d76-11e8-8743-cdf4ac1436ec.PNG)
There is an awkward amount of space between the capital T and the lowercase A characters.  
I believe the Roboto Font is thus not rendering correctly because this looks different from the Google's Roboto font page.

**Comment by chinmaygarde** [comment]
Can you post the engine and framework versions you are using (`flutter doctor` should give you this information)? We recently switched to a new text layout and rendering engine and this may be an issue with kerning setup.

**Comment by marcglasberg** [comment]
I am working with Bram on this, and I have the same problem here. My flutter doctor is this:
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)

...

**Comment by Hixie** [comment]
@chinmaygarde adding new labels is fine. :-)

**Comment by chinmaygarde** [comment]
@marcglasberg Thanks. I believe this is the old layout engine. I will try to reproduce this on ToT.

**Comment by zoechi** [comment]
Are you still seeing this?
