### ISSUE TITLE
Failing postsubmit test: 'FormatException: No value was provided for required key: out_dir_shared'

### ISSUE THREAD

**Issue by victorsanni** [flutter/flutter#158120]
### Type of Request

bug

### Infrastructure Environment

Postsubmit tests (LUCI)

### What is happening?

<details>
<summary>Error logs</summary>

```
05:25 +30: test/integration.shard/isolated/native_assets_test.dart: flutter build apk succeeds without libraries
05:38 +30 -1: test/integration.shard/isolated/native_assets_test.dart: flutter build apk succeeds without libraries [E]
  Exception: flutter build failed: 1
  Unhandled exception:
  FormatException: No value was provided for required key: out_dir_shared
  #0      MapJsonUtils.get (package:native_assets_cli/src/json_utils.dart:50:7)
  #1      MapJsonUtils.path (package:native_assets_cli/src/json_utils.dart:25:48)
  #2      new HookConfig (package:native_assets_cli/src/config.dart:88:38)
  #3      new BuildConfig (package:native_assets_cli/src/config.dart)
  #4      build (package:native_assets_cli/src/api/build.dart:99:18)
  #5      main (file:///Volumes/Work/s/w/ir/x/t/UUbYLX/package_with_native_assets/hook/build.dart:4:9)
  #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
  #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  Building native assets for package:package_with_native_assets failed.
  file:///Volumes/Work/s/w/ir/x/t/UUbYLX/package_with_native_assets/hook/build.dart returned with exit code: 255.
  To reproduce run:
  /Volumes/Work/s/w/ir/x/w/flutter/bin/dart --packages=/Volumes/Work/s/w/ir/x/t/UUbYLX/package_with_native_assets/.dart_tool/package_config.json /Volumes/Work/s/w/ir/x/t/UUbYLX/package_with_native_assets/.dart_tool/native_assets_builder/545fcee0f93c80dfaac63b71612fc26c/hook.dill --config=/Volumes/Work/s/w/ir/x/t/UUbYLX/package_with_native_assets/.dart_tool/native_assets_builder/545fcee0f93c80dfaac63b71612fc26c/config.json
  stderr:
  Unhandled exception:
  FormatException: No value was provided for required key: out_dir_shared
  #0      MapJsonUtils.get (package:native_assets_cli/src/json_utils.dart:50:7)
  #1      MapJsonUtils.path (package:native_assets_cli/src/json_utils.dart:25:48)
  #2      new HookConfig (package:native_assets_cli/src/config.dart:88:38)
  #3      new BuildConfig (package:native_assets_cli/src/config.dart)
  #4      build (package:native_assets_cli/src/api/build.dart:99:18)
  #5      main (file:///Volumes/Work/s/w/ir/x/t/UUbYLX/package_with_native_assets/hook/build.dart:4:9)
  #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
  #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
  
  stdout:
  
  
  Target native_assets failed: Error: Building native assets failed. See the logs for more details.
  
  
  FAILURE: Build failed with an exception.
  
  * What went wrong:
  Execution failed for task ':app:compileFlutterBuildDebug'.
  > Process 'command '/Volumes/Work/s/w/ir/x/w/flutter/bin/flutter'' finished with non-zero exit value 1
  
  * Try:
  > Run with --stacktrace option to get the stack trace.
  > Run with --info or --debug option to get more log output.
  > Run with --scan to get full insights.
  > Get more help at https://help.gradle.org.
  
  BUILD FAILED in 9s
  Gradle task assembleDebug failed with exit code 1
  
  Resolving dependencies...
  Downloading packages...
    async 2.11.0 (2.12.0 available)
    boolean_selector 2.1.1 (2.1.2 available)
    characters 1.3.0 (1.3.1 available)
    clock 1.1.1 (1.1.2 available)
    collection 1.19.0 (1.19.1 available)
    fake_async 1.3.1 (1.3.2 available)
    matcher 0.12.16+1 (0.12.17 available)
    material_color_utilities 0.11.1 (0.12.0 available)
    meta 1.15.0 (1.16.0 available)
    path 1.9.0 (1.9.1 available)
    string_scanner 1.3.0 (1.4.0 available)
    vm_service 14.3.0 (14.3.1 available)
  Got dependencies!
  12 packages have newer versions incompatible with dependency constraints.
  Try `flutter pub outdated` for more information.
  
  Running Gradle task 'assembleDebug'...                          
  Running Gradle task 'assembleDebug'...                             10.2s
  
  test/integration.shard/isolated/native_assets_test.dart 241:11       main.<fn>.<fn>
  ===== asynchronous gap ===========================
  test/integration.shard/isolated/native_assets_test_utils.dart 275:5  inTempDir
  ===== asynchronous gap ===========================
  test/integration.shard/isolated/native_assets_test.dart 227:7        main.<fn>
```
</details>

**Comment by victorsanni** [comment]
cc @bdero

**Comment by zanderso** [comment]
Not sure @bdero is the right person here. I think @dcharkes owns these tests.

**Comment by jmagman** [comment]
It looks like the tool has native_assets_cli pinned

https://github.com/flutter/flutter/blob/9ee00ae168e82742099b2077d4abe580dbf11dda/packages/flutter_tools/lib/src/update_packages_pins.dart#L27

But the ffi template has it at `^0.8.0`
https://github.com/flutter/flutter/blob/9ee00ae168e82742099b2077d4abe580dbf11dda/packages/flutter_tools/templates/package_ffi/pubspec.yaml.tmpl#L12
The test is making a new ffi project 
https://github.com/flutter/flutter/blob/9ee00ae168e82742099b2077d4abe580dbf11dda/packages/flutter_tools/test/integration.shard/isolated/native_assets_test_utils.dart#L14-L24

I suspect the test is pulling in 0.9.0 and https://github.com/dart-lang/native/pull/1643 ?  cc @mkustermann @mosuem

**Comment by bdero** [comment]
+1. The tests started failing with the `native_assets_cli` 0.9.0 push.

**Comment by christopherfujino** [comment]
I am going to disable this test--it's also blocking our pub roll

**Comment by matanlurey** [comment]
This is as a result of a test running `flutter pub add native_assets_cli`, will [add the latest stable version](https://dart.dev/tools/pub/cmd/pub-add), in this case `0.9.0` which appears to either have a bug or otherwise not be compatible with the environment created in the integration test:

https://github.com/flutter/flutter/blob/32cb866d3a617a108774761cbe9a1265bd25dc2d/packages/flutter_tools/test/integration.shard/isolated/native_assets_test_utils.dart#L78-L87

Easy 1-liner fix: `pub add native_assets_cli ^0.8.0`

Better long-term fix: Either reading the version from another source (i.e. pubspec or whatnot), or adding another dependency so that `pub add` knows to resolve it to a version that works with the rest of the tooling.

**Comment by christopherfujino** [comment]
Unassigning myself as I'm working on another p0 in the devicelab, @victorsanni can you update your PR, following https://github.com/flutter/flutter/issues/158120#issuecomment-2455558129, to have this add `^0.8.0` with a TODO linked to this issue to do the better long-term fix?

**Comment by matanlurey** [comment]
I have an easier fix that is `-1` line, @victorsanni I will send you a PR.

**Comment by matanlurey** [comment]
I am coming back to this after a meeting.

I'm actually ... not sure what this test is testing, that is, it's possibly @victorsanni's original take might have been correct (deleting the test). It doesn't use a template, so it creates a blank `flutter create .` project, and then adds `native_assets_cli` (which resolves to a new version).

Looking at the git history to try to get a better idea.

**Comment by matanlurey** [comment]
This test suite was added by @bdero in https://github.com/flutter/flutter/pull/150742 ("Fix macOS host build failure when there are no frameworks to sign"). I suspect there is another, macOS specific way to test this (as written this test runs for multiple platforms and seems to over-test).

**Comment by dcharkes** [comment]
cc @mkustermann

**Comment by bdero** [comment]
It's testing that native asset build hooks which don't link libraries don't cause projects to fail building.

> I suspect there is another, macOS specific way to test this (as written this test runs for multiple platforms and seems to over-test).

Although the fix is just for macOS, I think we should continue verifying this case on all host platforms supported by native assets.

**Comment by matanlurey** [comment]
Acknowledged. Ok, I'll send you a patch.

**Comment by mkustermann** [comment]
Thanks, @matanlurey !

CI should always be deterministic for a given commit and it's result shouldn't vary depending on what is available on pub at the time of running tests - otherwise CI can go red any moment someone publishes a new package version from the side.
