### ISSUE TITLE
App hanging for at least 2000 ms on 3.24

### ISSUE THREAD

**Issue by DebugDruid510** [flutter/flutter#158173]
### Steps to reproduce

1. After I updated the app to 3.24, Sentry has been receiving reports of some app hanging.
2. I'm not sure what's happening here, please help me with this problem

### Expected results

The app is working.

### Actual results

App hanging for at least 2000 ms.

### Code sample

<details open><summary>Code sample</summary>

```stacktrace
  libsystem_kernel    0x1e7109424  kevent_id
  libdispatch         0x1a637d7d0  _dispatch_kq_poll
  libdispatch         0x1a637e1b8  _dispatch_event_loop_wait_for_ownership
  libdispatch         0x1a636a590  __DISPATCH_WAIT_FOR_QUEUE__
  libdispatch         0x1a636a158  _dispatch_sync_f_slow
  FileProvider        0x1bccf2e7c  -[FPItemCollection suspendUpdates]
  CloudDocs           0x1b9588cec  -[BRItemCollectionGatherer disableUpdates]
  CloudDocs           0x1b957ce04  __25-[BRQuery disableUpdates]_block_invoke
  Foundation          0x19d2f98bc  __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
  Foundation          0x19d2f977c  -[NSBlockOperation main]
  Foundation          0x19d2f957c  __NSOPERATION_IS_INVOKING_MAIN__
  Foundation          0x19d2f781c  -[NSOperation start]
  Foundation          0x19d37c264  __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
  Foundation          0x19d37beb0  __NSOQSchedule_f
  libdispatch         0x1a6369e58  _dispatch_block_async_invoke2
  libdispatch         0x1a635add0  _dispatch_client_callout
  libdispatch         0x1a63695a0  _dispatch_main_queue_drain
  libdispatch         0x1a63691b4  _dispatch_main_queue_callback_4CF
  CoreFoundation      0x19e48770c  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  CoreFoundation      0x19e484910  __CFRunLoopRun
  CoreFoundation      0x19e483cd4  CFRunLoopRunSpecific
  GraphicsServices    0x1e2ed11a4  GSEventRunModal
  UIKitCore           0x1a0abdae4  -[UIApplication _run]
  UIKitCore           0x1a0b71d94  UIApplicationMain
  UIKitCore           0x1a0ceb500  keypath_get_selector_hoverStyle
  Runner              0x1042e0ef4  $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ6Runner03AppB0C_Tgm5 (AppDelegate.swift)
  Runner              0x1042e0ef4  AppDelegate.$main (<compiler-generated>:6)
  Runner              0x1042e0ef4  main (AppDelegate.swift)
  0x1c1c5b154  <redacted>
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment]
Hi @DebugDruid510 
Are you seeing the issue on iOS platform? Please provide the list of impacted device info and the percentage occurrence of the crash. 

Do you also see any other Flutter traces from Sentry?

**Comment by DebugDruid510** [comment]
Hello @huycozy, Thank you for your reply.

Here are the device models and system version details for all instances of this issue.

<details><summary>Device Model</summary>
<img width="956" alt="2024-11-07 09 45 34" src="https://github.com/user-attachments/assets/5a4145d0-f39c-480f-9d7b-52fc5daa95ea">
</details>

<details><summary>OS Version</summary>
<img width="947" alt="2024-11-07 09 46 27" src="https://github.com/user-attachments/assets/91a77a7d-cd5a-4ce0-aab0-b17ddee180e4">
</details>

And all the traces. [trace](https://pastebin.com/Q9w7HLDg)

**Comment by huycozy** [comment]
Thanks for the update. There is an issue reported for `App hanging for at least 2000 ms` at https://github.com/flutter/flutter/issues/133557 but the trace is not the same. Keeping this as a separate issue for team's thought.

**Comment by hellohuanlin** [comment]
@DebugDruid510 could you provide some minimum reproducible code?

**Comment by DebugDruid510** [comment]
@hellohuanlin 
I can't reproduce the issue locally, the issue was collected by me at sentry, so I can't provide the reproduction code either.

Here is the list of plugins I am using.
<details><summary>Plugins</summary>

  cupertino_icons: ^1.0.8

  flutter_svg: ^2.0.10+1

  sqflite: ^2.3.3+1

  path_provider: ^2.1.4

  flutter_picker_plus: ^1.3.0

  image_picker: ^1.1.2

  pull_down_button: ^0.10.1

  extended_image: ^8.2.1

  image_editor: ^1.5.1

  fluttertoast: ^8.2.8

  intl: ^0.19.0

  photo_view: ^0.15.0

  flutter_local_notifications: ^17.2.2

  shared_preferences: ^2.3.2

  image_gallery_saver: ^2.0.3

  mime: ^1.0.5

  in_app_review: ^2.0.9

  encrypt: ^5.0.3

  share_plus: ^10.0.2

  flutter_riverpod: ^2.5.1

  riverpod_annotation: ^2.3.5

  hooks_riverpod: ^2.5.2

  freezed_annotation: ^2.4.4

  flutter_hooks: ^0.20.5

  posthog_flutter: ^4.5.0

  dotted_border: ^2.1.0

  photo_manager: ^3.2.3

  app_settings: ^5.1.1

  sentry_flutter: ^8.7.0

  screenshot: ^3.0.0

  webview_flutter: ^4.8.0

  dio: ^5.6.0

  package_info_plus: ^8.0.2

  json_annotation: ^4.9.0

  url_launcher: ^6.3.0

  in_app_purchase: ^3.2.0

  modal_bottom_sheet: ^3.0.0

  flutter_secure_storage: ^9.2.2

  uuid: ^4.4.2

  flutter_easyloading: 3.0.5

  flutter_image_compress: ^2.3.0

  icloud_storage: 2.2.0

  easy_localization: ^3.0.7

  sentry_dart_plugin: ^2.1.0

  flutter_quill: ^10.8.5
</details>

**Comment by jmagman** [comment]
I doubt this is a Flutter bug since the hang is something calling `CloudDocs` APIs on the main thread. I suggest filing an issue against the icloud_storage plugin.
