### ISSUE TITLE
Cannot override default `CircularProgressIndicator` size

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#158106]
### Use case

Currently, it's not possible to resize `CircularProgressIndicator`.

https://github.com/flutter/flutter/blob/8591d0c16a6c7edfbea3b5b1bf08ae09db117b71/packages/flutter/lib/src/material/progress_indicator.dart#L868-L871

### Proposal

Add ability to override `CircularProgressIndicator` size

**Comment by rehmaan-dev** [comment]
I can work on this , would be great if you assign me this?

**Comment by TahaTesser** [comment]
@rehmaan-dev thanks! This is already fixed in the linked PR
