### ISSUE TITLE
[image_picker] ImageSource.camera isn't working for windows

### ISSUE THREAD

**Issue by Aruljebaraj** [flutter/flutter#158155]
### Steps to reproduce

implemented image picker
Works fine while picking images from gallery though ImageSource.camera isn't working for windows

### Actual results

ImageSource.camera isn't working for windows
any other way to resolve this??

**Comment by stuartmorgan** [comment]
The camera source is supported via an optional delegate, [as documented in the README](https://pub.dev/packages/image_picker#windows-macos-and-linux). If you don't set a delegate to support the camera source, not working is the expected and documented behavior.

**Comment by Aruljebaraj** [comment]
@stuartmorgan  can you give me an example how it implement It exactly using delegate
