### ISSUE TITLE
Gallery App has Vignettes

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1581]
Beautiful, inspirational compositions of material-design-compliant showcases. Should reflect how a real app would look and feel. We intend to link to these vignettes from the component gallery, from within the app. One vignette should showcase many aspects of Flutter and MD (use lots of stuff :)

- [ ] Pesto (https://github.com/flutter/flutter/issues/3961)
- [ ] Shrine (https://github.com/flutter/flutter/issues/3962)

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/pull/1494 adds weather and is ready to land (or nearly) I believe.

**Comment by sethladd** [comment]
@HansMuller @vlidholt open season for vignettes and showcases! We'd like to get to four, please add your ideas above. You may find inspirational from the [MD spec](https://www.google.com/design/spec/material-design/introduction.html) as well.

**Comment by vlidholt** [comment]
A few ideas, more coming: https://drive.google.com/a/google.com/file/d/0B7Hmx81AdvM0T1BSVlpfOFhOZHc/view?usp=sharing

**Comment by sethladd** [comment]
Closing in favor of individual issues.
