### ISSUE TITLE
[in_app_purchase_storekit] add `expirationDate` to `Transaction`

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#158226]
### Use case

The current `Transaction` wrapper doesn't include many properties available in the swift object, we should expose those to the dart layer as well, specially [`expirationDate`](https://developer.apple.com/documentation/storekit/transaction/transaction_properties#4225461) as it helps with determining how long for a subscription to end.

### Proposal

Add [`expirationDate`](https://developer.apple.com/documentation/storekit/transaction/transaction_properties#4225461) to `Transaction` and possibly all other properties as well.

**Comment by darshankawar** [comment]
@feinstein 
Can you confirm if [this](https://github.com/flutter/flutter/issues/147698) issue resembles your case ?

**Comment by feinstein** [comment]
@darshankawar my issue is only about the iOS integration, the other one seems to include all platforms, I am sending a PR that will close the iOS side only, so I can only reference this issue, otherwise I will close the other issue

**Comment by darshankawar** [comment]
The linked issue is part of umbrella issue https://github.com/flutter/flutter/issues/157558 related to storekit.

**Comment by feinstein** [comment]
Yeah, but I can't close it too with my PR

**Comment by darshankawar** [comment]
Ok, reopening this for better tracking. You are welcome to send a PR to add this feature as described.
