### ISSUE TITLE
"flutter doctor fails with no error "

### ISSUE THREAD

**Issue by 31SUFI** [flutter/flutter#158276]
### Steps to reproduce

The flutter --version command works fine and shows the Flutter version, but flutter doctor fails without errors it just stucked with no progress at all 

### Actual results

as basic flutter doctor commad is not working as so flutter projects are not creating due to this

### Logs

![image](https://github.com/user-attachments/assets/82f7bce3-e53d-4199-82d6-013f4e0130d2)

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@31SUFI 
Check if there's any anti-virus or proxy setting that could be affecting the command. 

> i run cmd as an administrator

You probably don't need to run as as admin, but as a regular user.

**Comment by 31SUFI** [comment]
The issue is resolved in such way that i deleted the entire bin folder from flutter sdk and run flutter doctor command again, and then dark sdk downloading was started and then after this flutter doctor was working perfectly fine

**Comment by darshankawar** [comment]
Closing as resolved. Maybe it was due to a corrupted installation.
