### ISSUE TITLE
Framework post submit bots all appear to be Idle.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#158224]
See https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.prod/Linux_pixel_7pro%20native_assets_android  / https://ci.chromium.org/ui/p/flutter/builders/staging/Mac%20platform_channel_sample_test_macos

Looks like nothing is queuing up?

**Comment by jonahwilliams** [comment]
on https://ci.chromium.org/p/flutter/g/flutter_staging/console I don't see anything running.

**Comment by christopherfujino** [comment]
> on https://ci.chromium.org/p/flutter/g/flutter_staging/console I don't see anything running.

This is for staging.

Prod is this one: https://ci.chromium.org/p/flutter/g/flutter/console, which also has nothing running for the past 2/3 commits...

**Comment by christopherfujino** [comment]
Here is the view for all of our prod bots. A few are doing work, but most of them are idle.

**Comment by christopherfujino** [comment]
From spot checking a few, it looks like the last builds were started around 3:46pm PT today.

**Comment by christopherfujino** [comment]
On the build dashboard, it looks like there was a dramatic reduction in builds per commit being scheduled starting from this commit: https://github.com/flutter/flutter/commit/49a16fccd1c24050cccd818c482e5822c0ae574c

Which merged November 5, ~8:48am PT. This *could* be explained by the morning 8am CRON deploying cocoon, going from commit 8bfa1f4 to c68f1a2

**Comment by christopherfujino** [comment]
I just split traffic 100% to the previous version of cocoon app-dart: version-8bfa1f4 

Now it looks like builds have been scheduled and we're utilizing our capacity in the botlist: https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&s=id

**Comment by christopherfujino** [comment]
And I paused the cloudscheduler job the deploy cocoon app-dart. Once we find the bug in cocoon app-dart and fix it at HEAD, we should resume that CRON.

**Comment by jtmcdole** [comment]
OK; the culprit is probably this:

- Every time we call `getCiYaml(Commit)`, we check to see if the commit is in a monorepo.
- The backfiller in on a cron job of 5 minutes.
- Every 5 minutes the backfiller walks over *ALL* the *datastore* checklists / tasks and calls "get the CI Yaml for this
- For every task in the list, the backfiller was hitting github / gob urls
- backfiler dies due to timeouts

Solution: cache the ref->bool calculation and call it a day.

**Comment by jtmcdole** [comment]
flutter/cocoon#4014 should have fixed this. Following along in the morning.
