### ISSUE TITLE
The intrinsic dimension methods of the RenderParagraph class returned values that violate the intrinsic protocol contract.

### ISSUE THREAD

**Issue by Phrohdoh** [flutter/flutter#15829]
## Steps to Reproduce

This is similar to #11082 but the exception is a bit different.

I *only get this exception when running `flutter test`* (`flutter run` does not throw).

#### widget_test.dart
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:whoami/main.dart' show App;
//
import 'package:whoami/pages/quiz_page.dart' show QuizPage;

void main() {
  testWidgets('Landing page renders and can be tapped away from', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(App());

    // Verify that the landing page's text is rendered
    expect(find.text('who am i?'), findsOneWidget);

    // Tap the inkwell to navigate to the quiz page
    await tester.tap(find.byType(InkWell));
    await tester.pump();

    // Verify that the landing page is no longer rendered
    //
    //
    expect(find.byType(QuizPage), findsOneWidget);
  });
}
```

#### main.dart
```dart
import 'package:flutter/material.dart';
import 'package:whoami/pages/landing_page.dart' show LandingPage;
import 'package:whoami/pages/quiz_page.dart' show QuizPage;

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        "/quiz": (_) => QuizPage(),
      },
      home: LandingPage(),
    );
  }
}
```

#### landing_page.dart
```dart
import 'package:flutter/material.dart';

class LandingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.green,
      child: InkWell(
        onTap: () => Navigator
            .of(context)
            .pushReplacementNamed("/quiz"),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              "who am i?",
              style: TextStyle(
                color: Colors.white,
                fontSize: 50.0,
                fontWeight: FontWeight.bold,
              ),
            ),
            Text(
              "tap to find out!",
              style: TextStyle(
                color: Colors.white,
                fontSize: 20.0,
                fontWeight: FontWeight.bold,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
#### quiz_page.dart
```dart
import 'package:flutter/material.dart';

import 'package:whoami/models/quiz.dart';
import 'package:whoami/models/statement.dart';

import 'package:whoami/ui/answer_button.dart';
import 'package:whoami/ui/statement_text.dart';
import 'package:whoami/ui/choice_overlay.dart';

import 'package:whoami/pages/score_page.dart';

class QuizPage extends StatefulWidget {
  @override
  State createState() => QuizPageState();
}

class QuizPageState extends State<QuizPage> {
  var quiz = Quiz([
    Statement("Bulbasaur can learn 'overgrow'", true),
    Statement("Bulbasaur is a 'poison' type", true),
    Statement("Bulbasaur is a 'grass' type", true),
    Statement("Bulbasaur is a 'dark' type", false),
    Statement("Ivysaur evolves from Bulbasaur", true),
    Statement("Bulbasaur evolves directly into Venusaur", false),
    Statement("toby is the scranton strangler", true),
  ]);

  Statement currentStatement;
  String stmtText;
  int currStmtNum;
  bool isCorrect;
  bool displayOverlay = false;

  @override
  void initState() {
    super.initState();
    currentStatement = quiz.nextStatement;
    stmtText = currentStatement.statement;
    currStmtNum = quiz.statementNumber;
  }

  void handleChoice(bool choice) {
    isCorrect = choice == currentStatement.correctAnswer;
    quiz.answerChosen(isCorrect);

    this.setState(() {
      displayOverlay = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      fit: StackFit.expand,
      children: [
        Column(
          children: [
            AnswerButton(true, () => handleChoice(true)),
            StatementText(stmtText),
            AnswerButton(false, () => handleChoice(false)),
          ],
        ),
        displayOverlay
            ? ChoiceOverlay(
                isCorrect,
                () {
                  currentStatement = quiz.nextStatement;
                  this.setState(() {
                    if (currStmtNum == quiz.length) {
                      Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (ctx) => ScorePage(quiz.score, quiz.length)));
                      return;
                    }

                    displayOverlay = false;
                    stmtText = currentStatement.statement;
                    currStmtNum = quiz.statementNumber;
                  });
                },
              )
            : Container(),
      ],
    );
  }
}
```

## Logs

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the RenderParagraph class returned values that violate the
intrinsic protocol contract.
The following failures was detected:
 * getMaxIntrinsicWidth(Infinity) returned a non-finite value: NaN
 * getMaxIntrinsicWidth(800.0) returned a non-finite value: NaN
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1762:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1772:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1507:17)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1507:65)
#4      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:257:5)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#6      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#8      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#13     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141:11)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#15     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:509:15)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#27     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2711:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#31     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:509:15)
#32     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
#33     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
#34     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:620:23)
#35     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#36     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#37     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#38     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:585:9)
#41     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#42     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:573:27)
#43     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:213:47)
#46     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#47     WidgetTester.pump (package:flutter_test/src/widget_tester.dart:213:27)
#48     main.<anonymous closure> (file:///Users/thill/src/mobile/whoami/src/test/widget_test.dart:18:18)
#62     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:667:16)
#63     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:473:5)
#64     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:653:24)
#70     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:651:16)
#71     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:60:24)
#72     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
#84     Declarer._runSetUps (package:test/src/backend/declarer.dart)
(elided 51 frames from class _FakeAsync, package dart:async, and package stack_trace)

The following RenderObject was being processed when the exception was fired:
  RenderParagraph#af6c8 relayoutBoundary=up5 NEEDS-PAINT
  creator: RichText ← Text ← Center ← Padding ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
  _InkFeatures-[GlobalKey#42f69 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
  PhysicalModel ← AnimatedPhysicalModel ← Material ← StatementText ← ⋯
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=800.0, 0.0<=h<=Infinity)
  size: Size(800.0, 1.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  maxLines: unlimited
This RenderObject has no descendants.
```

## Flutter Doctor

```
[✓] Flutter (Channel dev, v0.2.3, on Mac OS X 10.12.6 16G1114, locale en-US)
    • Flutter version 0.2.3 at /Users/thill/src/mobile/flutter
    • Framework revision 5a58b36e36 (9 days ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/thill/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/thill/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.10.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by jason-simmons** [comment]
Does this work on the master branch of Flutter?

I commented out the missing parts of the app (such as the AnswerButton and StatementText widgets) and was able to run the test successfully on the master branch.

If it's still failing, then we would need complete source code for the app to debug further.

**Comment by martipello** [comment]
i think i have more info on this, i have a FadeInImage.memoryNetwork inside a stack inside an aspect ratio as per this 

`return AspectRatio(
      aspectRatio: 16.0 / 9.0,
      child: Stack(
        children: <Widget>[
          Container(
            child: Center(
              child: CircularProgressIndicator(),
            ),
            width: double.infinity,
            height: double.infinity,
          ),
          _buildImage(attributes, renderContext),
        ],
      ),
    );`


`Widget _buildImage(Map<String, String> attributes, RenderContext renderContext) {
    return FadeInImage.memoryNetwork(
      placeholder: kTransparentImage,
      image: attributes['src'],
//      width: double.infinity,
//      height: double.infinity,
      fit: BoxFit.cover,
      imageErrorBuilder: (context, child, stacktrace) {
        print('error loading image: $stacktrace');
        return _buildImageError(renderContext);
      },
    );
  }`

and it throws this



══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the RenderAspectRatio class returned values that violate the
intrinsic protocol contract.
The following failures was detected:
 * getMinIntrinsicWidth(Infinity) returned a non-finite value: Infinity
 * getMaxIntrinsicWidth(Infinity) returned a non-finite value: Infinity
 * getMinIntrinsicHeight(Infinity) returned a non-finite value: Infinity
 * getMaxIntrinsicHeight(Infinity) returned a non-finite value: Infinity
 * getMinIntrinsicWidth(Infinity) returned a non-finite value: Infinity
 * getMaxIntrinsicWidth(Infinity) returned a non-finite value: Infinity
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  AspectRatio


When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2023:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2035:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1752:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1754:6)
#4      RenderAspectRatio.performLayout (package:flutter/src/rendering/proxy_box.dart:524:5)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#8      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#10     RenderParagraph._layoutChildren (package:flutter/src/rendering/paragraph.dart:530:13)
#11     RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:580:5)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#13     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:266:13)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#15     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:394:13)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#19     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#21     RenderParagraph._layoutChildren (package:flutter/src/rendering/paragraph.dart:530:13)
#22     RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:580:5)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#24     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:266:13)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#26     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:394:13)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#30     RenderParagraph._layoutChildren (package:flutter/src/rendering/paragraph.dart:530:13)
#31     RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:580:5)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#33     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:266:13)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#35     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:266:13)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#37     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:512:13)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#57     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
#58     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
#59     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#60     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#65     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#82     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3225:13)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#84     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:700:15)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#98     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
#99     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
#100    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#101    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1009:23)
#102    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#103    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#104    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#105    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:879:9)
#108    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#109    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:866:27)
#110    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:441:22)
#113    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#114    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:438:27)
#115    main.<anonymous closure> (file:///Users/martinseal/luna-custom-app/apps/zurich_places/test/content/content_renderer_widget_test.dart:132:18)
#116    main.<anonymous closure> (file:///Users/martinseal/luna-custom-app/apps/zurich_places/test/content/content_renderer_widget_test.dart:131:63)
#117    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
#130    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#131    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 31 frames from class _FakeAsync, dart:async, and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderAspectRatio#95173 relayoutBoundary=up25 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: AspectRatio ← DecoratedBox ← Padding ← Container ← ContainerSpan ← RichText ← Text ←
    SizedBox ← StyledText ← Align ← DecoratedBox ← Padding ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=784.0, 0.0<=h<=Infinity)
  size: Size(784.0, 441.0)
  aspectRatio: 1.8
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderStack#48ff6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 1: RenderConstrainedBox#e79ea NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderPositionedBox#3ad5f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderSemanticsAnnotations#90d4a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderConstrainedBox#de062 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 2: RenderSemanticsAnnotations#5307f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderStack#06276 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child 1: RenderAnimatedOpacity#67dde NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderImage#8c0c5 NEEDS-LAYOUT NEEDS-PAINT
          child 2: RenderAnimatedOpacity#b2283 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child: RenderImage#b18bf NEEDS-LAYOUT NEEDS-PAINT



it goes on through the heirarchy giving me all the parents issues too but the full log was too much for paste bin

**Comment by martipello** [comment]
commenting out the width and height of the image removes the error
