### ISSUE TITLE
is it possible to create iOS app for testing and distributing using flutter via Adhoc distribution?

### ISSUE THREAD

**Issue by yash365** [flutter/flutter#15825]
getting this error while selecting Adhoc distribution

![ios error](https://user-images.githubusercontent.com/25004640/37773274-2cc6b49c-2e03-11e8-88aa-38db8edc44ab.png)

**Comment by zoechi** [comment]
Cross-ref https://stackoverflow.com/questions/49429127/error-while-building-ios-app-using-flutter-and-selecting-adhoc-distribution

**Comment by jmagman** [comment]
This looks like a bug in Xcode's ipatool.  Can you confirm this works on the latest version of Xcode?

**Comment by dnfield** [comment]
I have done this many times. The answer is yes.

This question would be better suited for a forum like StackOverflow.  If you have reproduction instructions that indicate a bug in the Flutter tooling or framework, we can reopen this.
