### ISSUE TITLE
Remove or migrate `firebase_abstract_method_smoke_test` off of v1 embedding types

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#158212]
This test has been marked bringup, so it was missed in the v1 cleanup because it didn't cause any failures.

https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.staging/Linux%20firebase_abstract_method_smoke_test?limit=200&cursor=id%3E8733123663121339889

Example of failure
https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20firebase_abstract_method_smoke_test/4711/overview
From
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8733232984625024545/+/u/test_execution/Build_appbundle/stdout
```
Running Gradle task 'bundleRelease'...                          

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1028 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
e: /b/s/w/ir/x/w/flutter/dev/integration_tests/abstract_method_smoke_test/android/app/src/main/kotlin/com/example/abstract_method_smoke_test/MainActivity.kt: (10, 44): Unresolved reference: shim
e: /b/s/w/ir/x/w/flutter/dev/integration_tests/abstract_method_smoke_test/android/app/src/main/kotlin/com/example/abstract_method_smoke_test/MainActivity.kt: (37, 34): Unresolved reference: ShimPluginRegistry

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

The `ShimPluginRegistry` type was deleted in the v1 embedding deletion pr, so this test will continue to fail until references to the type are removed. Alternatively, it seems like @christopherfujino was considering deleting this test in https://github.com/flutter/flutter/issues/147335, which would also remove the reference to the type 😄

**Comment by reidbaker** [comment]
Example https://github.com/flutter/flutter/pull/158223/files
