### ISSUE TITLE
Flutter tools `--analyze-size` command prints the wrong output to CLI

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#158211]
Example output after running: `flutter build apk --analyze-size --target-platform=android-arm64`
<img width="836" alt="Screenshot 2024-11-05 at 2 31 04 PM" src="https://github.com/user-attachments/assets/c722a16d-db20-49df-9be6-4e6d67b757a0">

Then running `dart devtools --appSizeBase=apk-code-size-analysis_03.json` as the CLI output instructs does not work as expected. The command has the wrong file path, and so this results in an error:

`No JSON file available at /Users/kenzieschmoll/develop/test_apps/fresh_app_nov_2024/apk-code-size-analysis_03.json.`

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate this as reported.

The apk analysis is saved at `A summary of your APK analysis can be found at: /Users/dhs/.flutter-devtools/apk-code-size-analysis_02.json` but when we run `dart devtools --appSizeBase=apk-code-size-analysis_02.json`, it looks for the file at ` /Users/dhs/Documents/NCFlutter/integration_dummy/` location.

**Comment by andrewkolos** [comment]
The code comment here implies that the instructions are correct:
https://github.com/flutter/flutter/blob/e695cd6e9a2a7d1b85e75ba3edb6e5ea7d383cb1/packages/flutter_tools/lib/src/android/gradle.dart#L632-L640

Therefore, I am left to wonder if this is a bug in devtools or flutter. Regardless, I'm okay with flutter just providing the full file path in the instructions.

**Comment by bkonyi** [comment]
Where do we expect to write this file? Flutter Tools assumes that DevTools is going to look for it within `~/.flutter-devtools/` and is outputting the file there. Is this the behavior we want? If so, DevTools needs to be updated to look at that location by default.
