### ISSUE TITLE
Keyboard pop-up animation is not synchronized

### ISSUE THREAD

**Issue by bing127** [flutter/flutter#158256]
### Steps to reproduce

On iOS or Android, there is a chat page with an input box at the bottom. When getting focus in the input box, the animation of the keyboard moving up is not synchronized, and it always feels slow by one frame；
I remember mentioning a similar bug in the issues before. Do you know if there’s a plan or timeline to address it, or when it might be fixed?
If there’s no plan to address it, I might have to refactor and switch to native development instead.

### Expected results

I hope to achieve a native like effect；
similar https://developer.android.com/develop/ui/views/layout/sw-keyboard?hl=zh -CN # Kotlin in this link

### Actual results

When the keyboard actually pops up, there’s a noticeable lag to the human eye.

### Code sample

#

### Screenshots or Video

#

### Logs

#

### Flutter Doctor output

Flutter is already up to date on channel stable
Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (13 天前) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

**Comment by darshankawar** [comment]
@bing127 
There's similar [issue](https://github.com/flutter/flutter/issues/116836) open describing your case, so please follow-up in it for further updates.
Closing this as a duplicate.
