### ISSUE TITLE
[Android] communication between Flutter app and the underlying platform (Android) failed when trying to launch a URL

### ISSUE THREAD

**Issue by SMDParsa** [flutter/flutter#158298]
### Steps to reproduce

1. String url = "www.google.com";
2. _openLink(url);
3. app crashed

### Expected results

should launch the link in web browser.

### Actual results

Throwing error in the logcat

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<void> _openLink(String url) async {
    if (!await launchUrl(
      Uri(path: url),
      mode: LaunchMode.externalApplication,
    )) {
      throw Exception('Could not launch $url');
    }
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Logcat:
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.url_launcher_android.UrlLauncherApi.launchUrl"., null, null)
E/flutter (12394): #0      UrlLauncherApi.launchUrl (package:url_launcher_android/src/messages.g.dart:165:7)
E/flutter (12394): <asynchronous suspension>
E/flutter (12394): #1      UrlLauncherAndroid.launchUrl (package:url_launcher_android/url_launcher_android.dart:115:11)
E/flutter (12394): <asynchronous suspension>
E/flutter (12394): #2      LoginScreen._openLink (package:xxxx/xxxx/xxxx/login_screen.dart:45:10)
E/flutter (12394): <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.19045.4894], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.95.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
I don't see the error as reported when using the sample code above. But I see the uri is not correct, please try this sample code and let me know if it works.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main(List<String> args) {
  runApp(MaterialApp(
    title: 'Flutter Demo',
    home: const MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Demo Home Page'),
      ),
      body: Center(
        child: TextButton(
          onPressed: () {
            _openLink(Uri(scheme: 'https', host: 'www.google.com'));
          },
          child: Text('Click here'),
        ),
      ),
    );
  }

  Future<void> _openLink(Uri uri) async {
    if (!await launchUrl(
      uri,
      mode: LaunchMode.externalApplication,
    )) {
      throw Exception('Could not launch $uri');
    }
  }
}

```
</details>

**Comment by AdrianBaqueiro** [comment]
I have the same issue PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.url_launcher_android.UrlLauncherApi.launchUrl"., null, null)

test code

`import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());

}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);



  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Prueba URL Launcher',
      supportedLocales: const [
        Locale('es', ''),
        Locale('en', ''),
      ],
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Color(0xFFD10002)),
        useMaterial3: true,
      ),
      home: PruebaUrlLauncher(), // Definimos una pantalla de inicio para la prueba
    );
  }
}

class PruebaUrlLauncher extends StatelessWidget {
  const PruebaUrlLauncher({Key? key}) : super(key: key);

  void _launchURL() async {
    final Uri url = Uri.parse('https://www.google.com');
    try {
      if (!await launchUrl(
        url,
        mode: LaunchMode.externalApplication,
      )) {
        print('No se pudo abrir la URL');
      }
    } catch (e) {
      print('Error al intentar abrir la URL: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Prueba URL Launcher'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: _launchURL,
          child: Text('Abrir Google'),
        ),
      ),
    );
  }
}
`

  url_launcher: ^6.3.1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.24.0"

**Comment by SMDParsa** [comment]
It's working whith your sample code and im using it in my project. Issue
resolved and working nicely. Thanks

**Comment by huycozy** [comment]
@AdrianBaqueiro I used your code and modified it (removed unnecessary `flutter_gen` implementation) and ran it but couldn't see the issue. Are you seeing this issue on Android (app)? Can you confirm on a new Flutter project?
