### ISSUE TITLE
JAVA HOME is set to invalid directory

### ISSUE THREAD

**Issue by Sayem-Ahmed-Shayeed** [flutter/flutter#158320]
### Steps to reproduce

1. I was facing gradle related problem in the newer version of android studio then i decided to shift to the java 19 then the actual problem begun.

### Actual results

I have set the JAVA_HOME variable to the correct path but still i am getting an error please help me to fix this.
THE official documentation is bit confusing.

### Logs

![image](https://github.com/user-attachments/assets/f9ff88a1-a750-422f-9f7c-3ca41f1fe7d0)
![image](https://github.com/user-attachments/assets/b1163778-1d34-4616-8005-bda6fd62afd9)

### Flutter Doctor output

[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4317], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    X Cannot execute C:\Program Files\Java\jdk-22\bin\java to determine the version
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] Android Studio (version 2024.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Looks like your JAVA_HOME path is not correct, I see there is an empty space between `Java` and `jdk-19`. Can you share how JAVA_HOME looks like in Environment Variables? Let's try setting it as: `C:\Program Files\Java\jdk-19` then `flutter config --jdk-dir "C:\Program Files\Java\jdk-19"`
