### ISSUE TITLE
[packages] Document the process of updating generated files

### ISSUE THREAD

**Issue by OlegKrymskyi** [flutter/flutter#158321]
### What is happening?

I am trying to make changes to your lib, however, I need to be able to regenerate pegion files, because of luck of flatter development experience, I don't understand how you are doing this:

```
dart pub global run pigeon --input ....
```

Please, give me instructions how can I do this my own?

**Comment by stuartmorgan** [comment]
This should be documented in our contributing docs; I've posted https://github.com/flutter/flutter/pull/158326 to add instructions.
