### ISSUE TITLE
flutter_markdown is working well in English but it's not work for arabic

### ISSUE THREAD

**Issue by ahmedelwan-mvp** [flutter/flutter#158371]
### Steps to reproduce

English is working well, but Arabic isn't

### Expected results

English is working well, but Arabic isn't

### Actual results

English is working well, but Arabic isn't

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-x64, locale
    en-GB)
    ! Warning: `dart` on your path resolves to
      /usr/local/Cellar/dart/3.5.3/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/ahmedelwan/development/flutter.
      Consider adding /Users/ahmedelwan/development/flutter/bin to the front of
      your path.
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by huycozy** [comment]
@ahmedelwan-mvp Please try to provide all information indicated in the template so that we can address the issue properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
- An actual result describes how it's not working for Arabic text
- Screenshots demo if any
