### ISSUE TITLE
firebase_auth is not installed or this dependensies can't installed, how and why

### ISSUE THREAD

**Issue by kleponijo** [flutter/flutter#158369]
like what i say in title, i can't install firebase_auth in this my version for firebase_auth is ^5.3.1, that my version for dependences, i don't know why, i would the problem let's for succes  and thank you, i'm sorry my english so bad.

**Comment by darshankawar** [comment]
@kleponijo 
Your issue isn't clear to me as you didn't provide any error log. I suggest you to raise this in support channels like StackOverflow.
Closing from here.

**Comment by kleponijo** [comment]
Oowh i'm sorry, OK, I'll do as you say

Pada tanggal Jum, 8 Nov 2024 18.21, darshankawar ***@***.***>
menulis:
