### ISSUE TITLE
[Impeller] Clipping bug in OpenGL backend on wonderous.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#158385]
Maybe state error with scissor? Tested on Pixel 7 Pro.

https://github.com/user-attachments/assets/83fc1a81-1c90-4989-a482-bea7712ccbeb

**Comment by gaaclarke** [comment]
This might be related to https://github.com/flutter/flutter/issues/158392.  This is clipping things that shouldn't be clipped, but that is failing to clip things that should be clipped.

**Comment by jonahwilliams** [comment]
This is working correctly after https://github.com/flutter/engine/pull/56494
