### ISSUE TITLE
Context menu for TextField copy-paste not showing on Flutter web for iOS and Android.

### ISSUE THREAD

**Issue by MrPiou94** [flutter/flutter#158376]
### Steps to reproduce

This issue only occurs on the web version. Tested on Android with Google Chrome and iOS with Safari, the context menu does not appear when selecting the TextField. It seems to disappear upon the appearance of the virtual keyboard.

### Expected results

In previous versions of Flutter, the context menu was present.

### Actual results

It is very rare to see the context menu appear; 90% of the time, it behaves as shown in the attached photos.

### Code sample

NA

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![WhatsApp Image 2024-10-30 à 18 31 06_c5f98751](https://github.com/user-attachments/assets/cdd022a5-ec69-4e77-978b-79ee533bb8df)

![WhatsApp Image 2024-11-08 à 13 22 50_8962bf28](https://github.com/user-attachments/assets/2f97fbf3-75ad-448d-bb2b-b78c59881aec)

</details>

### Flutter Doctor output

NA

**Comment by huycozy** [comment]
Hi @MrPiou94 

Can you share the Flutter version? (`flutter doctor -v` if possible)

I checked this on Android Chrome and iOS Safari browsers, but the issue only appears on Android Chrome. I am on the latest Flutter stable version `3.24.4` and master version `3.27.0-1.0.pre.442`. Please upgrade Flutter and retry?

>In previous versions of Flutter, the context menu was present.

If so, this looks like a regression. Which Flutter version did you see it works without issue?
