### ISSUE TITLE
Need to explain how to add OEM UI views and textures to Flutter apps

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#15832]
https://flutter.io/platform-channels/ doesn't mention UI.  It could point to:
https://github.com/flutter/flutter/tree/master/examples/platform_view
https://github.com/flutter/flutter/tree/master/examples/flutter_view
or in the case of foreign Textures (like for AR, GL, etc.):
https://github.com/flutter/plugins/tree/master/packages/video_player
https://github.com/flutter/plugins/tree/master/packages/camera

Maybe some of this will happen as part of other add-to-app work @mravn-google and co are looking at.

**Comment by zoechi** [comment]
Is this a dup of #14927 ?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2063](https://github.com/flutter/website/issues/2063) via [**ZenHub**](https://www.zenhub.com/)
