### ISSUE TITLE
The button within the SliverAppBar does not function while scrolling.

### ISSUE THREAD

**Issue by hiddenparts** [flutter/flutter#158305]
### Steps to reproduce

One of the requirements is that the AppBar should be hidden during list scrolling, so I created the widget using CustomScrollView, SliverAppBar, and SliverListView. When scrolling, the AppBar hides as required, and when scrolling in the opposite direction, the AppBar reappears.

At this point, I expected to navigate back when pressing the back button on the AppBar while scrolling. However, the actual behavior is that the AppBar hides instead.

Is this the intended behavior of Flutter, or is it a bug?

The same issue occurs on both Android and iOS.

Thank you.

### Expected results

The back button in the app bar should work.

### Actual results

The app bar disappears.

### Code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text('test'),
        ),
        body: Center(
          child: ElevatedButton(
              onPressed: () {
                Navigator.push(context, MaterialPageRoute(builder: (_) => const Sample1()));
              },
              child: const Text('sample1')
          ),
        ),
    );
  }
}

class Sample1 extends StatefulWidget {
  const Sample1({super.key});

  @override
  State<Sample1> createState() => _Sample1State();
}

class _Sample1State extends State<Sample1> {

  ScrollController scrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: CustomScrollView(
          controller: scrollController,
          slivers: [
            SliverAppBar(
              snap: true,
              floating: true,
              title: const Text('Sample1'),
              leading: IconButton(
                  icon: const Icon(Icons.arrow_back),
                  onPressed: () async {
                    Navigator.pop(context);
                  }
              ),
            ),

            const SliverToBoxAdapter(
              child: Padding(
                padding: EdgeInsets.symmetric(horizontal: 16),
                child: Column(
                  children: [
                    Text('Title'),
                  ],
                ),
              ),
            ),

            SliverList(
              delegate: SliverChildBuilderDelegate(
                    (context, index) {
                  return ListTile(title: Text('List $index'),);
                },
                childCount: 200,
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.4, on macOS 14.3 23D56 darwin-arm64, locale ko-KR)
    • Flutter version 3.24.4 on channel stable at /Users/me/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (2 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

**Comment by darshankawar** [comment]
@hiddenparts 
When you say app bar back button should work, can you provide a short video of that behavior ?
I tried the code on Android emulator using latest master with which I was able to se the appbar and also could navigate back. See below:


https://github.com/user-attachments/assets/27d810f5-0e4a-48f2-9fc7-4f7ecf23ffd4

**Comment by hiddenparts** [comment]
Hello!

I am sending you the requested short video.

The main point of this bug is that “while scrolling,” if you press the button in the navigation bar to go back, the navigation bar is hidden.

Thank you as always!

https://github.com/user-attachments/assets/99d719ee-dfa8-41f6-91f5-2c51a1e3f6df

**Comment by darshankawar** [comment]
@hiddenparts 
If you add `pinned: true` inside `SliverAppBar`, does it help in your case ?

**Comment by hiddenparts** [comment]
@darshankawar 
I apologize for the delayed response. 
To get straight to the point, it doesn’t help. With `pinned: true`, pressing the button while scrolling stops the scroll. 
Thank you!

**Comment by darshankawar** [comment]
Please check if your case resembles https://github.com/flutter/flutter/issues/42588 or not.

**Comment by hiddenparts** [comment]
@darshankawar 
This issue definitely seems similar. However, regardless of options like `snap` or `pinned`, it appears that the notifier problem mentioned in the issue is causing trouble with event delivery to the AppBar.

**Comment by plooliveira** [comment]
I'm having the same problem here and haven't found any solution yet.

**Comment by darshankawar** [comment]
@hiddenparts 
I suggest you to share your findings in the original issue for better tracking because the root-cause seems to be similar and there have been similar issues [reported](https://github.com/flutter/flutter/issues/42588#issuecomment-1439261892) that were closed in favor of it. 
I will also close this as duplicate. If you disagree, write in comments and I'll reopen it.
