### ISSUE TITLE
Add benchmark measuring text rendering

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#15839]
We need a benchmark that measures the efficiency of our text rendering pipeline. Something like [this](https://medium.com/@biz84/how-fast-is-flutter-i-built-a-stopwatch-app-to-find-out-9956fa0e40bd) might be a good start.

**Comment by chinmaygarde** [comment]
The [txt_benchmark harness](https://github.com/flutter/engine/blob/0f59c7919d93f2a4225f6a6c0bdc35f0bdb213be/third_party/txt/BUILD.gn#L317) does this now.

**Comment by eseidelGoogle** [comment]
Neat!

This doesn't need to derail this issue, but curious if we have any dart-level tests (e.g. ones which would be able to be run against both Web and C++.  My current understanding from the profiling I've done of Web is that Text measurment is the biggest bottleneck. There is a cache in front of the text measurement to reduce that, but that mostly just makes first-paint (or any measurement-using animations) slow.

**Comment by liyuqian** [comment]
CC @GaryQian who I believe recently added some performance tests written in Dart that are text-related.
