### ISSUE TITLE
[tool_crash] _Exception

### ISSUE THREAD

**Issue by sbiitju** [flutter/flutter#158343]
## Command
```sh
flutter analyze
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_Exception
```console

```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale en-BD)
    [32m•[39m Flutter version 3.24.4 on channel stable at /Users/md.shahinbashar/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 603104015d (2 weeks ago), 2024-10-24 08:01:25 -0700
    [32m•[39m Engine revision db49896cf2
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/md.shahinbashar/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Users/md.shahinbashar/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16B40
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Users/md.shahinbashar/Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2024.2.2)
    [32m•[39m IntelliJ at /Users/md.shahinbashar/Applications/IntelliJ IDEA Ultimate.app
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m VS Code (version 1.86.1)
    [32m•[39m VS Code at /Users/md.shahinbashar/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.100.0

[32m[✓][39m VS Code (version 1.93.1)
    [32m•[39m VS Code at /Users/md.shahinbashar/Downloads/Visual Studio Code 2.app/Contents
    [32m•[39m Flutter extension version 3.100.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Pixel 6 (mobile)                • 26211FDF6007JX        • android-arm64  • Android 15 (API 35)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1 24B83 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1 24B83 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript • Google Chrome 130.0.6723.92

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.11+17
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 682aa387cfe4fbd71ccd5418b2c2a075729a1c66
### Plugins
awesome_notifications-0.7.4+1
file_picker-5.5.0
file_selector_linux-0.9.3
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
firebase_core-2.32.0
firebase_core_web-2.18.1
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
flutter_callkit_incoming-1.0.3+3
flutter_inappwebview-5.8.0
flutter_plugin_android_lifecycle-2.0.23
flutter_sslcommerz-2.3.6
fluttertoast-8.2.8
geocoding-2.2.2
geocoding_android-3.3.1
geocoding_ios-2.3.0
geolocator-10.1.1
geolocator_android-4.3.1
geolocator_apple-2.3.7
geolocator_web-2.2.1
geolocator_windows-0.2.3
google_api_headers-1.6.0
google_maps_flutter-2.9.0
google_maps_flutter_android-2.14.10
google_maps_flutter_ios-2.13.1
google_maps_flutter_web-0.5.10
image_picker-0.8.9
image_picker_android-0.8.12+17
image_picker_for_web-2.2.0
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
jitsi_meet_wrapper
location-5.0.3
location_web-4.2.0
package_info_plus-4.2.0
path_provider-2.1.4
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
printing-5.13.3
shared_preferences-2.3.2
shared_preferences_android-2.3.3
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.13
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
webview_flutter-4.10.0
webview_flutter_android-4.0.0
webview_flutter_wkwebview-3.16.0

**Comment by huycozy** [comment]
Do you see this issue appear consistently? Is there a crash stack trace that you can provide for us to investigate further?

(Maybe similar to https://github.com/flutter/flutter/issues/123495)
