### ISSUE TITLE
[video_player]: Semantics label params for Play/Stop button for better accessibility explanation

### ISSUE THREAD

**Issue by moshe5745** [flutter/flutter#158314]
### Use case

Better support for Voice-Over accessability feature.

### Proposal

params: semanticPlayLabel, semanticStopLabel.

**Comment by huycozy** [comment]
Hi @moshe5745 
Isn't Play/Stop button implemented by developer? Can you share a sample code and point out these buttons?

**Comment by moshe5745** [comment]
No. There is a default play/stop button that sits in the native(cause i didn't find it in the flutter source code).

But I can see now how we can solve this and get more control.

We can put some widget on top of the video. Catch the onTap events without allowing them to propagate to the default buttons(that I mentioned earlier) and control the video with the controller. Then in this onTap event we can enforce the reader to say whatever we need.

We will check this solution. And if it works I will close the issue.

**Comment by moshe5745** [comment]
@huycozy There is a problem with the solution I proposed.
The problem is when the video is stoped from the controller  we lose the fading effect and the default icon for play(triangle in circle).
And mainly we lose the VideoScrubber too.
The icon we could add manually but the VideoScrubber is more complex feature.
