### ISSUE TITLE
Usage of non-SDK interfaces with latest flutter update

### ISSUE THREAD

**Issue by Stivalo** [flutter/flutter#158412]
Usage of non-SDK interfaces with latest flutter update

Hello i am using the latest flutter and android studio version and my app works fine on all devices starting from api 26 and above but i always get warning in testLab with  robotest on api 29 and above that says Non-SDK API Usage Violation so , i have tried to create a fully new project without any external dependencies and still get the warning after searching i found the problem in the sdk files of the framework it self can you provide me an solution to avoid using them or i just can ignore them and publish to google play and my app would not reject because of them.

those are the 4 non sdk

Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J
Landroid/util/LongArray;->get(I)J
Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J

that is my log on firebase testLab
[web-build_20241107_rjzh_a14xm-34-en_US-portrait_logcat.txt](https://github.com/user-attachments/files/17686406/web-build_20241107_rjzh_a14xm-34-en_US-portrait_logcat.txt)

**Comment by huycozy** [comment]
There was a known issue https://github.com/flutter/flutter/issues/36915, you can check the details at https://github.com/flutter/flutter/issues/36915#issuecomment-525668810. Another similar issue is at https://github.com/flutter/flutter/issues/109815 as well. Closing as a duplicate.
