### ISSUE TITLE
[Windows] When using Android Studio run or debug flutter project.  Process.run to open another exe written in Flutter,UI not display,like is daemon

### ISSUE THREAD

**Issue by windinternet** [flutter/flutter#158461]
### Steps to reproduce

1.Create a Flutter project with Windows support.
2.Build some UI.
3.Build the project and get the build result.
4.Record the executable path for the build result.
5.Create a new Flutter project with Windows support.
6.Use the Process.run API anywhere to open the executable path from step 5.
7.Launch this new Flutter project using the running or debugging features of Android Studio
8.Watch your Task Manager.

Directly opening the compiled product does not have this issue

### Expected results

Display the UI !

### Actual results

No UI display,juset run as daemon.

 

I have made many attempts, including but not limited to:

1. Adjust the inShell parameter, true or false

2. Use start instead of run

3. Use the Windows built-in start command to restart the exe written by Flutter

4. Use C # and Windows form to write desktop programs to restart the exe written by Flutter. The C # program can display normally, but Flutter is not.

frustrating！

### Code sample

```
var exePath ="xxxx.exe"; // your flutter windows app exe path
debugPrint(exePath);
Process.run(exePath, [], runInShell: true);
```

### Screenshots or Video

![screenshot-20241112-020341](https://github.com/user-attachments/assets/5365f27d-1940-414a-914c-0f8eb87baafb)

### Logs

no log

### Flutter Doctor output

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.2)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version 1.95.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by huycozy** [comment]
I tested this on my end with a simple Flutter app (which only displays a Text widget) but couldn't see the issue. The `exe` file can be runnable and opened with UI as expected. 

I'm on the latest Flutter stable `3.24.4`, can you try upgrading Flutter and retry? If the issue persists, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.

**Comment by windinternet** [comment]
> I tested this on my end with a simple Flutter app (which only displays a Text widget) but couldn't see the issue. The `exe` file can be runnable and opened with UI as expected.
> 
> I'm on the latest Flutter stable `3.24.4`, can you try upgrading Flutter and retry? If the issue persists, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.

Thank you for your response, but I seem to have made a mistake. After discovering new differences, I modified the problem title but forgot to modify the reproducing steps. Here, I want to clarify that this issue only exists when running or debugging with Android Studio. Manually opening the compiled product does not have this issue. I guess this may be related to the way various tools are launched when running or debugging projects with Android Studio, rather than issues with Flutter itself. Thank you again!

**Comment by huycozy** [comment]
I also use Android Studio (version 2024.2) but can't reproduce the issue. I noticed that you are on Windows 11 while I'm on Windows 10, is this an OS-specific issue on Windows 11 only? 

I will boot my Windows 11 machine and give it a try later. In the meantime, can you try on the Flutter stable 3.24.4?

>I guess this may be related to the way various tools are launched when running or debugging projects with Android Studio, rather than issues with Flutter itself

You can check the version of Flutter/Dart plugin on your Android Studio. On my side, I'm using Dart plugin version `242.22855.32` and Flutter plugin version `82.1.3`.
