### ISSUE TITLE
why the flutter doesn't support the video casting!!!!?I even can't find a single library for this common feature.

### ISSUE THREAD

**Issue by CupidChow** [flutter/flutter#158403]
### Steps to reproduce

why the flutter doesn't support the video casting!!!!?I even can't find a single library for this common feature.

### Actual results

why the flutter doesn't support the video casting!!!!?I even can't find a single library for this common feature.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->
why the flutter doesn't support the video casting!!!!?I even can't find a single library for this common feature.
```

</details>

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/59554.
