### ISSUE TITLE
Flutter app crashes on startup on some older ChromeOS devices

### ISSUE THREAD

**Issue by Jon-Salmon** [flutter/flutter#158424]
### Steps to reproduce

I've not been able to reproduce the bug locally, but after updating my app from flutter 3.13 to 3.24.4 a number of users have got in touch to say the app crashes on startup on their device. They are all using older asus chromebooks (ASUS C302C, Acer N15Q8 etc), and asking one user to install another flutter app they also reported the same issue (https://github.com/immich-app/immich/tree/v1.120.1/mobile). I am using crashlytics, but havn't seen any failures in there.

### Expected results

The app should open as expected on all supported devices.

### Actual results

Some ChromeOS devies cause the app to crash

### Code sample

N/A

### Flutter Doctor output

N/A

**Comment by Jon-Salmon** [comment]
I've been unable to reproduce this myself due lack of hardware (so can't test the counter app), but have managed to get some specs from one customer. They have ChromeOS version 103.0.5060.132 (running Android 9 build R103) on a device I think has 4GB RAM and a Celeron N3060.

Nothing particularly complex on startup (reading some data from a SQLite DB).

**Comment by danagbemava-nc** [comment]
Hi @Jon-Salmon, I'm not entirely sure if the ChromeOS version is linked to the chrome versions, but if it is, then those versions of chromeOS would be unsupported by flutter. See https://docs.flutter.dev/reference/supported-platforms

**Comment by Jon-Salmon** [comment]
It is not running flutter web, ChromeOS allows running android apps so it was flutter android where the issue was. The user was using android 9.

**Comment by danagbemava-nc** [comment]
Hi @Jon-Salmon, can we get the crash logs? That would be helpful in investigating the issue
