### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git    

### ISSUE THREAD

**Issue by wenyangliu** [flutter/flutter#15851]
there was already .git file。but run `flutter packages get` is error

**Comment by zoechi** [comment]
I don't think there is a way to diagnose the problem with this little information.
I'd suggest you delete the Flutter installation directory and start over.

**Comment by Hixie** [comment]
@wenyangliu Can you tell us more about what your situation was? As @zoechi says, without more information I don't know how we can do anything here.
