### ISSUE TITLE
How to serve output of flutter build web --wasm.

### ISSUE THREAD

**Issue by ebala96** [flutter/flutter#158571]
### Steps to reproduce

I am taking a wasm build of my application by running  `flutter build web --wasm` and trying to serve this using my dart server.
Since this creates dual-compatible output for both dart2js and wasm, it picks the js bundle by default.

I also tried the following config in my index.html file.
`config : {"compileTarget":"dart2wasm","renderer":"skwasm","mainWasmPath":"main.dart.wasm","jsSupportRuntimePath":"main.dart.mjs"}` inside `_flutter.loader.load`

This throws an error `FlutterLoader could not find a build compatible with configuration and environment.`

### Actual results

Looking for a way to set the config to pick wasm file when I serve the output of flutter build web --wasm.

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.24.4, on Ubuntu 22.04.5 LTS 5.15.0-117-generic, locale en_US.UTF-8)
    • Flutter version 3.24.4 on channel stable at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.5 LTS 5.15.0-117-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 122.0.6177.0

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by huycozy** [comment]
Hi @ebala96 
How do you serve your web? Please check this to see if it helps: https://docs.flutter.dev/platform-integration/web/wasm#serve-the-built-output-with-an-http-server

Please also check https://github.com/flutter/flutter/issues/154541 if it's similar to your case.

**Comment by Levi-Lesches** [comment]
@huycozy, that section of the docs has since been removed in https://github.com/flutter/website/pull/11367

@sfshaza2, that section was marked as "not needed" since Flutter run works by default, but that doesn't address the issue of serving a release build from your own web server. [This page](https://developer.chrome.com/blog/coep-credentialless-origin-trial) of Chrome Developers seems to suggest the config is still very much needed. 

Can we consider re-adding it?
