### ISSUE TITLE
Issue from website page Get Started: Install on Windows

### ISSUE THREAD

**Issue by tabinnorway** [flutter/flutter#15857]
From URL: https://flutter.io/get-started/setup_windows.md

This doesn't work on many corporate networks: **flutter doctor**

You will get
> Got TLS error trying to find package archive at https://pub.dartlang.org.
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
> timeout: invalid time interval '/t'
> Try 'timeout --help' for more information.

**Comment by zoechi** [comment]
Probably a dup of #15014

**Comment by Hixie** [comment]
Closing as dupe as per previous comment.
