### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by arlantaiters** [flutter/flutter#15855]
I just started app developing and im struggling with navigation bar. The bottom one is good but the one at the top is not. I want to remove the grey space above the buttons.

Can you help me?

Image:
![Image of Yaktocat](https://i.imgur.com/A8Rgb0Z.png)

Code:

```@override
  Widget build(BuildContext context) {   
    return new Scaffold(
        appBar: new AppBar(
          backgroundColor: Colors.grey,
          bottom: new TabBar(
            controller: controller,
            tabs: <Tab>[
              new Tab(icon: new Icon(Icons.arrow_forward)),
              new Tab(icon: new Icon(Icons.arrow_downward)),
              new Tab(icon: new Icon(Icons.arrow_back)),
            ]
          )
        ),        
        body: new TabBarView(
            controller: controller,
            children: <Widget>[
              new first.First(),
              new second.Second(),
              new third.Third(),
              new fourth.Fourth(),
              new fifth.Fifth()
            ]
        ),
    );
  }

**Comment by xster** [comment]
It depends. When you navigate into a child page after this main page, where would you expect the back button to be if there's no top row in the app bar? 

If it's just a one page app or you just want the desired effect as described, you don't need to have an AppBar or use the appBar slot in the scaffold. Just put a TabBar on top of the Scaffold body.

Also consider using https://stackoverflow.com/questions/tagged/flutter for usage questions.
