### ISSUE TITLE
GrMtlCommandBuffer::commit(bool) (in FlutterMacOS) (GrMtlCommandBuffer.mm:225) Crash on Mac14,7 MacOS 12.5

### ISSUE THREAD

**Issue by zhangc20** [flutter/flutter#158577]
### Steps to reproduce

Our App Crashs on GrMtlCommandBuffer::commit(bool) (in FlutterMacOS) (GrMtlCommandBuffer.mm:225) 
The stack:
```
ExceptionHandling               0x1de99fed8 -[NSExceptionHandler _handleException:mask:] + 480
ExceptionHandling               0x1de99fbc0 NSExceptionHandlerUncaughtSignalHandler + 52
libsystem_platform.dylib        0x1c033f4a4 _sigtramp + 56
FlutterMacOS                    0x10b1785a4 _ZdaPvSt11align_val_t + 3943196
FlutterMacOS                    0x10b179b88 _ZdaPvSt11align_val_t + 3948800
FlutterMacOS                    0x10b0a2a90 _ZdaPvSt11align_val_t + 3067912
FlutterMacOS                    0x10aeb014c _ZdaPvSt11align_val_t + 1025732
FlutterMacOS                    0x10b5fd568 _ZdaPvSt11align_val_t + 8682208
FlutterMacOS                    0x10b5fe348 _ZdaPvSt11align_val_t + 8685760
FlutterMacOS                    0x10b343c54 _ZdaPvSt11align_val_t + 5824972
FlutterMacOS                    0x10b342138 _ZdaPvSt11align_val_t + 5818032
FlutterMacOS                    0x10b34204c _ZdaPvSt11align_val_t + 5817796
FlutterMacOS                    0x10b361634 _ZdaPvSt11align_val_t + 5946284
FlutterMacOS                    0x10adc1278 _ZdaPvSt11align_val_t + 47088
FlutterMacOS                    0x10adc90fc _ZdaPvSt11align_val_t + 79476
CoreFoundation                  0x1c040f964 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
CoreFoundation                  0x1c040f54c __CFRunLoopDoTimer + 1064
CoreFoundation                  0x1c040efd4 __CFRunLoopDoTimers + 392
CoreFoundation                  0x1c03f3a64 __CFRunLoopRun + 1936
CoreFoundation                  0x1c03f2b34 CFRunLoopRunSpecific + 600
FlutterMacOS                    0x10adc9394 _ZdaPvSt11align_val_t + 80140
FlutterMacOS                    0x10adc1070 _ZdaPvSt11align_val_t + 46568
FlutterMacOS                    0x10adc8164 _ZdaPvSt11align_val_t + 75484
libsystem_pthread.dylib         0x1c032826c _pthread_start + 148

wo use atos to decode:
GrMtlCommandBuffer::commit(bool) (in FlutterMacOS) (GrMtlCommandBuffer.mm:225)
GrMtlGpu::submitCommandBuffer(GrMtlGpu::SyncQueue) (in FlutterMacOS) (GrMtlGpu.mm:222)
GrGpu::submitToGpu(bool) (in FlutterMacOS) (GrGpu.cpp:760)
SkCanvas::onFlush() (in FlutterMacOS) (GrDirectContext.h:0)
flutter::EmbedderExternalView::Render(flutter::EmbedderRenderTarget const&) (in FlutterMacOS) (embedder_external_view.cc:105)
flutter::EmbedderExternalViewEmbedder::SubmitFrame(GrDirectContext*, std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::SurfaceFrame, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::SurfaceFrame> >) (in FlutterMacOS) (embedder_external_view_embedder.cc:195)
flutter::Rasterizer::DrawToSurfaceUnsafe(flutter::FrameTimingsRecorder&, flutter::LayerTree&) (in FlutterMacOS) (rasterizer.cc:613)
flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&) (in FlutterMacOS) (rasterizer.cc:483)
flutter::Rasterizer::DrawLastLayerTree(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::FrameTimingsRecorder, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::FrameTimingsRecorder> >) (in FlutterMacOS) (rasterizer.cc:172)
std::_LIBCPP_ABI_NAMESPACE::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDrawLastLayerTree(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::FrameTimingsRecorder, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::FrameTimingsRecorder> >)::$_0>, std::_LIBCPP_ABI_NAMESPACE::allocator<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDrawLastLayerTree(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<flutter::FrameTimingsRecorder, std::_LIBCPP_ABI_NAMESPACE::default_delete<flutter::FrameTimingsRecorder> >)::$_0> >, void ()>::operator()() (in FlutterMacOS) (function.h:359)


```
### Expected results

not crash

### Actual results

crashed

### Code sample

App name is Infoflow，the flutter sdk is 3.10.6

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter (Channel stable, 3.10.6, on macOS 12.6.8 21G725 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at
      /Users/zhangcheng09/Develop/flutter-sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (1 year, 4 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (2 available)            
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.8 21G725 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
> the flutter sdk is 3.10.6

@zhangc20 
You are on very old version of framework. Current version is 3.24.4. Please upgrade to latest and re-run your scenario to check if you still see the crash or not.
Closing for now, as the issue occurs on old version. If you disagree, write in comments and I'll reopen it.
