### ISSUE TITLE
google_sign_in and extension_google_sign_in_as_googleapis_auth doesn't support Linux. Can't login with google on Linux apps.

### ISSUE THREAD

**Issue by allComputableThings** [flutter/flutter#158544]
### Steps to reproduce

Run the sample: https://pub.dev/packages/extension_google_sign_in_as_googleapis_auth/example
with a Linux target.

### Expected results

Supports Google login with Linux

### Actual results

Fails with 

flutter: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Those plugins do not yet support linux. There's an issue tracking implementing this in https://github.com/flutter/flutter/issues/61831. 

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
