### ISSUE TITLE
Flutter 3.24.4 SDK upgrade: Chinese text appears thinner, Latin and numeral characters unaffected

### ISSUE THREAD

**Issue by evanwsu** [flutter/flutter#158550]
### Description:

After upgrading my Flutter SDK from version **3.10.6** to **3.24.4**, I've noticed a change in the appearance of `Text` widgets in my app:
- **Issue**: Chinese text has become noticeably thinner, whereas Latin characters and Arabic numerals appear as expected.
- **Attempts to resolve**: Setting `useMaterial3` to `false` in the `ThemeData` was not enough to restore the original thickness of the Chinese text.

### Environment

- **Old Flutter version**: 3.10.6
- **New Flutter version**: 3.24.4
- **useMaterial3**: `false`

### Steps to Reproduce

1. Create a Flutter app in version 3.10.6 using `Text` widgets that display Chinese characters alongside Latin characters and Arabic numerals.
2. Upgrade Flutter to 3.24.4.
3. Observe the difference in text appearance, specifically the thinner rendering of Chinese characters.

### Expected results

After the upgrade, I expected the appearance of all `Text` widgets to remain the same as in version 3.10.6.

### Actual results

After the upgrade:
- Chinese characters are thinner.
- Latin and Arabic numeral characters are unaffected.

### Code sample

<details open><summary>Code sample</summary>

```dart
    Center(child: Text("Hello, 你好啊, 123", style: TextStyle(fontWeight: FontWeight.w500, fontSize: 16, color: Color(0xFF0D0E10))));
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![WX20241113-111236@2x](https://github.com/user-attachments/assets/5ad9b58a-ffcc-4d2a-9b94-028c1c33933d)
![1731468286938](https://github.com/user-attachments/assets/06a3c51b-607d-40df-96e7-a360feb6cf9e)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.2 23C64 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.24.4 on channel stable at
      /Users/xxx/develop/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @evanwsu, this was initially reported in https://github.com/flutter/flutter/issues/154166 and has since been fixed on the master and beta channels. 

You may try either of these channels to see if you still experience this. 

Per our triage policy, I'll be closing this since it has already been fixed. 

If you experience this after checking either the beta or master channels, kindly leave a comment with the version you used and I will reopen this issue. 

Thank you

**Comment by evanwsu** [comment]
@danagbemava-nc 
Since the application is in a production environment, could using the master branch pose stability risks? Which stable branch can address this concern?

**Comment by danagbemava-nc** [comment]
You can try out the beta channel instead. It is typically the channel that becomes the next stable version. The stable branch does not have this fix, unless you cherrypick it into your own fork of flutter.
