### ISSUE TITLE
Bad state: Failed to start Dart Development Service

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#158537]
On beta/3.27.0-0.1.pre we are seeing a high crash rate (0.7-2.6% depending on the day).

The most frequent crasher (affecting half of clients that have reported at least one crash) is by far this one from `flutter run`:

```
StateError: Bad state: Failed to start Dart Development Service
at DartDevelopmentService.startDartDevelopmentService(dds.dart:114)
at <asynchronous gap>(async)
at FlutterDevice.connect.<anonymous closure>(resident_runner.dart:295)
at <asynchronous gap>(async)
```

Less often, we also see

```
Bad state: WebSocketChannelException: SocketException: The remote computer refused the network connection.
 (OS Error: The remote computer refused the network connection.
, errno = 1225), address = [127.0.0.1](https://www.google.com/url?sa=D&q=http%3A%2F%2F127.0.0.1), port = 2726
```

```
Bad state: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = [http://127.0.0.1:23862/z6K6q1577PM=/ws](https://www.google.com/url?sa=D&q=http%3A%2F%2F127.0.0.1%3A23862%2Fz6K6q1577PM%3D%2Fws)
```

```
Bad state: Failed to create server socket (호출에 대한 포인터 인수를 사용하려는 동안 시스템에서 잘못된 포인터 주소를 감지했습니다.
): [127.0.0.1:0](https://www.google.com/url?sa=D&q=http%3A%2F%2F127.0.0.1%3A0)
```

```
Bad state: WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = [127.0.0.1](https://www.google.com/url?sa=D&q=http%3A%2F%2F127.0.0.1), port = 43862
```

```
Bad state: WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = [127.0.0.1](https://www.google.com/url?sa=D&q=http%3A%2F%2F127.0.0.1), port = 62394
```

**Comment by andrewkolos** [comment]
Source:

https://github.com/flutter/flutter/blob/04d3d1a4c3f005beb8cf37fb4f66ad6b7b8d666f/packages/flutter_tools/lib/src/resident_runner.dart#L291-L313

I wonder if

https://github.com/flutter/flutter/blob/04d3d1a4c3f005beb8cf37fb4f66ad6b7b8d666f/packages/flutter_tools/lib/src/resident_runner.dart#L309-L312

should also handle instances of `Error`

**Comment by bkonyi** [comment]
I think this is actually a bug introduced after my migration from using `DartDevelopmentService` to `DartDevelopmentServiceLauncher`. Throwing the `StateError` was supposed originally there to handle some string parsing issues, not to wrap `DartDevelopmentServiceException`s. We should be `rethrow`ing `DartDevelopmentServiceException` which the resident runner will catch and handle.
