### ISSUE TITLE
Widget View Glitches on Scroll (Safari, Web-Render HTML)

### ISSUE THREAD

**Issue by rohitkhatri75436** [flutter/flutter#158576]
### **Steps to Reproduce**

1. **Create a Flutter Project**:
	* Start with a new, basic Flutter project to isolate the issue.
2. **Add a Scrollable Widget**:
	* In your `main.dart`, wrap your `body` content with either:
		+ `SingleChildScrollView`
		+ `ListView` (choose one for initial reproduction, then test the other)
3. **Insert a TextField with Label**:
	* Inside the scrollable widget, add a `TextField` with an `InputDecoration` that includes:
		- `labelText` property set to a non-empty string (e.g., "My Label")
		- Alternatively, test with `Label` widget (if applicable, provide specific Label widget details)
4.  Run  ```flutter run --web-renderer html```
5. **Reproduce the Glitch**:
	* Write anything in the `TextField`.
	*Scrolling the list/view up and down (use the drag/scroll using the cursor and avoid using the mouse's scroller).

- **Flutter Version**: 3.24.3.

### Expected results

Widget rendering should be rendered normally.

### Actual results

Widgets are not rendering properly and showing glitches while scrolling.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      scrollBehavior: const MaterialScrollBehavior().copyWith(
        dragDevices: {
          PointerDeviceKind.mouse,
          PointerDeviceKind.touch,
          PointerDeviceKind.stylus,
          PointerDeviceKind.unknown
        },
      ),
      home: Scaffold(
        body: SingleChildScrollView(
          child: Column(
            children: [
              TextFormField(decoration: const InputDecoration(labelText: 'First Name'),),
              Padding(
                padding: const EdgeInsets.all(12.0),
                child: Text(
                    ' Lists are the most popular elements of every web or mobile application. They are made up of multiple rows of items, which include text, buttons, toggles, icons, thumbnails, and many more. We can use it for displaying various information such as menus, tabs, or to break the monotony of pure text files ' *
                        10,
                    style: const TextStyle(
                      fontWeight: FontWeight.w700,
                      leadingDistribution: TextLeadingDistribution.even,
                    )),
              ),
            ],
          ),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

in safari browser Mac os Sequoia 15.1:

https://github.com/user-attachments/assets/facd1227-ad23-49b9-9484-93df7ae3f757

in iPhone 18.1's Safari browser: 

https://github.com/user-attachments/assets/70f4695d-8ecc-4076-b725-fc1af8e0b4a8

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK 
    • Platform android-34, build-tools 34.0.0
    • Java binary 
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome 

[✓] Android Studio (version 2024.2)
    • Android Studio 
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] Connected device (7 available)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.1 24B83 darwin-arm64
    • Chrome (web)                    • chrome                               

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @rohitkhatri75436 
This seems to be fixed on Flutter master `3.27.0-1.0.pre.491` as I don't see it appear anymore. Can you switch to master channel and confirm?

**Comment by rohitkhatri75436** [comment]
> Hi @rohitkhatri75436 This seems to be fixed on Flutter master `3.27.0-1.0.pre.491` as I don't see it appear anymore. Can you switch to master channel and confirm?

@huycozy, I tried the master channel ```3.27.0-1.0.pre.491``` on Safari in macOS 15.1 Sequoia, but the problem persists. The issue arises when selecting "html" as the web-render option.

**Comment by huycozy** [comment]
Yes, I built web in HTML renderer (btw, this renderer will be deprecated soon, see https://github.com/flutter/flutter/issues/145954). I am on `macOS 15.1 24B83`,  Flutter stable `3.24.5` and master `3.27.0-1.0.pre.511` but couldn't see the issue. 

https://github.com/user-attachments/assets/5342a6e4-2942-439b-b10f-8ae7c7511883

My Safari browser version is `Version 18.1 (20619.2.8.11.10)`. Can you check this as well?

**Comment by rohitkhatri75436** [comment]
> Yes, I built web in HTML renderer (btw, this renderer will be deprecated soon, see #145954). I am on `macOS 15.1 24B83`, Flutter stable `3.24.5` and master `3.27.0-1.0.pre.511` but couldn't see the issue.
> 
>  Screen.Recording.2024-11-15.at.11.19.01.mov 
> My Safari browser version is `Version 18.1 (20619.2.8.11.10)`. Can you check this as well?

@huycozy, As I mentioned in step no. 5,

 you must enter text into the text field to generate the issue. Please let me know if you have also done this. I also tried ``the Flutter versions you mentioned```  

Please check the below recording of Safari(20619.2.8.11.10): 
https://github.com/user-attachments/assets/7a3d0377-f3d6-4ec0-bd5f-111193af59db

**Comment by huycozy** [comment]
I see, I missed it. The issue only happens when the TextField contains some texts. 

<details>
<summary>Flutter versions (stable and master)</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-x64, locale en-VN)
    • Flutter version 3.24.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (32 hours ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
```

```console
[!] Flutter (Channel master, 3.27.0-1.0.pre.511, on macOS 15.1 24B83 darwin-x64, locale en-VN)
    • Flutter version 3.27.0-1.0.pre.511 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eaa99f28b1 (2 hours ago), 2024-11-14 17:38:26 -0800
    • Engine revision 619804c0fb
    • Dart version 3.7.0 (build 3.7.0-140.0.dev)
    • DevTools version 2.41.0-dev.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```
</details>

**Comment by ditman** [comment]
It is unlikely that we'll get to fix this issue, due to:

* https://github.com/flutter/flutter/issues/145954

So I'm closing this issue. Thanks for reporting @rohitkhatri75436!

**Comment by elliotkhd** [comment]
I had the same problem and the canvaskit package size is too big for my case, a bit frustrating to hear this can't be fixed
