### ISSUE TITLE
Optonal parameter to adjust drawer width

### ISSUE THREAD

**Issue by pahwa014** [flutter/flutter#15854]
There is no option to modify the default drawer width in the drawer properties. There is a work around(edit the main file) but it fails on certain screen options. Is there any optimum solution for all screen types.

**Comment by zoechi** [comment]
You can still change the size from the outside
https://stackoverflow.com/questions/51174594/is-there-any-alternative-way-to-change-the-scaffold-drawer-width

#19724 seems related

**Comment by zoechi** [comment]
Duplicate of #19724
