### ISSUE TITLE
[impeller:opengles] clipping of images not working in wonderous

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#158531]
## description
This only seems to happen on some hardware.  It's reproducible on the `Pixel 4a`.

Note from Jonah:
```
the clip rect is implemented via scissor which is working correctly, whereas the rest of the clip is implemented as a depth test that appears broken on adreno hardware
```

## seen on 
https://github.com/flutter/engine/pull/56511 @ [83280c8320d84680888d36045fa9919335c5e679](https://github.com/flutter/engine/pull/56511/commits/83280c8320d84680888d36045fa9919335c5e679) 

## observed
<img src="https://github.com/user-attachments/assets/24acc5f1-5db6-45ab-ab90-60582e91b0f3" width=320>

## expected
<img src="https://github.com/user-attachments/assets/8696107b-b502-4579-a03f-6343d17fb8fb" width=320>

**Comment by jonahwilliams** [comment]
This works as expected on Pixel 7 Pro (Mali) and is broken on the Pixel 4(a) (Adreno).

I've tried a varierty of different adjustments to the depth testing but haven't made a difference yet.

**Comment by gaaclarke** [comment]
I managed to get a renderdoc frame capture of it working for one frame and not working for one frame:

https://drive.google.com/drive/folders/13j5pmpKKnFUNi4s9M1wPMsxNXWtfIKj-?usp=sharing (google only, sorry)

**Comment by gaaclarke** [comment]
Note: the capture that "works" above is rendering one of the carousel items differently for one frame as a subpass.  That's why it works.

Here is something that looks odd to me:
## draw 1
The stencil buffer is written to, notice the stencil value is 0x81 after the draw.
![Screenshot 2024-11-12 165932](https://github.com/user-attachments/assets/724520b7-6f49-4550-b9f2-a35f43e0ccac)

## draw 2
The stencil buffer's values are wiped out, notice the stencil value is 0x81 after the draw.
![Screenshot 2024-11-12 165949](https://github.com/user-attachments/assets/618a0dad-8c7a-46e9-96cf-6405316ca5ee)

## draw 3
The draw that should be clipped is made
![Screenshot 2024-11-12 170006](https://github.com/user-attachments/assets/9036490b-ca39-457e-ba01-73284b004d89)

---
I would have expected the stencil buffer to have some value where the circle was drawn for clipping to happen correctly.
