### ISSUE TITLE
flutter crash with gomobile

### ISSUE THREAD

**Issue by hjlp20150803** [flutter/flutter#15858]
what's fuck google do? flutter is yours,golang is yours, why can't they live together?

The two team are in fight?

/////////////////////////////////////////
03-23 10:21:32.043 15289-15289/? I/art: Not late-enabling -Xcheck:jni (already on)
03-23 10:21:32.043 15289-15289/? W/art: Unexpected CPU variant for X86 using defaults: x86
03-23 10:21:32.187 15289-15289/com.example.blender I/InstantRun: starting instant run server: is main process
                                                                 
                                                                 [ 03-23 10:21:32.286 15289:15289 D/         ]
                                                                 HostConnection::get() New Host Connection established 0x9dad0100, tid 15289
03-23 10:21:32.375 15289-15289/com.example.blender D/EGL_emulation: eglCreateContext: 0x9bbfcf00: maj 3 min 0 rcv 3
                                                                    
                                                                    [ 03-23 10:21:32.409 15289:15309 D/         ]
                                                                    HostConnection::get() New Host Connection established 0xa051d4c0, tid 15309
03-23 10:21:32.454 15289-15312/com.example.blender I/flutter: Observatory listening on http://127.0.0.1:49074/
03-23 10:21:32.466 15289-15309/com.example.blender D/EGL_emulation: eglMakeCurrent: 0x9bbfcf00: ver 3 0 (tinfo 0xa0503760)
03-23 10:21:32.492 15289-15289/com.example.blender D/MainActivity: onCreate Thread id is 1
03-23 10:21:32.499 15289-15289/com.example.blender I/FlutterActivityDelegate: onResume setting current activity to this
03-23 10:21:32.503 15289-15314/com.example.blender D/onStartCommand: empty service  
03-23 10:21:32.503 15289-15314/com.example.blender D/MyService: empty service     Thread id is 432
03-23 10:21:32.558 15289-15316/com.example.blender A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 15316 (Thread-4)
                                                           
                                                           [ 03-23 10:21:32.559  1293: 1293 W/         ]
                                                           debuggerd: handling request: pid=15289 uid=10084 gid=10084 tid=15316

**Comment by Hixie** [comment]
@hjlp20150803 This kind of abusive language is not tolerated in this community. Please reconsider your tone and, if you are willing to engage in a more productive fashion, file a new issue to track this.
