### ISSUE TITLE
Add onPause to ActivityLifecycleListener

### ISSUE THREAD

**Issue by chsigg** [flutter/flutter#15860]
I would like to write an NFC plugin, which requires to get notified when the (Flutter)Activity pauses, see https://developer.android.com/reference/android/nfc/NfcAdapter.html#disableForegroundDispatch(android.app.Activity). I'm thinking the most natural approach would be to add an onPause to the ActivityLifecycleListener.

I can easily make this work for my pet project by adding an EventChannel from the FlutterActivity to the plugin, or by using my own Activity. In other words, consider this issue a suggestion and feel free to ignore.

**Comment by xster** [comment]
I suspect this might be solved with https://github.com/flutter/engine/pull/4848

**Comment by guyulmaz** [comment]
Is there a plan for a nfc plugin to read write iso 14443 type A cards

**Comment by matthew-carroll** [comment]
@chsigg Can you elaborate on the situation that you're trying to handle?  Which part of your plugin needs to know about onPause?  Can you describe the situation?

Also, can you confirm whether or not this issue still exists today?

**Comment by matthew-carroll** [comment]
As far as I can tell, this behavior is implemented here:
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/FlutterView.java#L261

I'm going to close the issue.  Please re-open if I'm mistaken.
