### ISSUE TITLE
Need API for clearing an Input field

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1586]
The firechat example app wants to clear the input field when you submit a message.

Proposed solution (warning: this is a bit of a yak shave, but it makes Input behave more like our other Material widgets)

Example usage of new Input that clears on submit:
https://gist.github.com/collinjackson/33906003d2eef047b6fc

Add InputValue to editable.dart
https://gist.github.com/collinjackson/b7af2b2fc2349594e1f1

EditableString is designed to be mutable private state, InputValue is immutable and suitable for passing into widget constructors

onUpdated/onSubmitted take an InputValue instead of a String

Rename RawEditableLine -> RawInputLine so that InputValue can live in editable.dart

On build, detect when the passed InputValue doesn’t match the editableString’s InputValue and change the value

RawEditableLine should probably take onUpdated/onSubmitted arguments and manage the EditableString instead of Input?

Rename setSelection on EditableString to _setSelection since only RawEditableLine uses it?

**Comment by abarth** [comment]
I believe @jason-simmons resolved this with #1747
