### ISSUE TITLE
Make CupertinoTabBar and TabBar (and scaffolds) more customizable

### ISSUE THREAD

**Issue by timahrentlov** [flutter/flutter#15863]
CupertinoTabBar always have a top border. So you cannot use this for making a more flat iOS design even though this is typical.

BottomNavigationBar only shows labels when type = fixed, but then background color is not customizable - even though a customer very typically requests this.

BottomNavigationBar only allows background color customisation when type = shifting, but then labels are not always visible - even though a customer very typically requests this.

The above combinations makes it impossible to create a very typical flat look - from simply using the standard tabbar widgets and/or scaffolds.

It would be nice to avoid the (dreaded!) situation in Xamarin Forms where you constantly have to make a renderer just to remove a border, add a color or the like. 

In Flutter terms this means copying the code and remove the border, add the background color or the like. This is what I currently have to do!

So please allow for more customisation option in these top widgets (and scaffolds).

**Comment by xster** [comment]
I think it's reasonable to extract some common parts of the BottomNavigationBar and CupertinoTabBar out to a barebones common element in the widgets layer. 

Though the common code is fairly short and may not satisfy everyone. Our primary goal is to make the creation of custom look and feels tab bar so easy it's 'affordable' to do for every app.

**Comment by xster** [comment]
@timahrentlov @fmatosqg, can you guys give us a mock-up or an image of the visual effects you're trying to achieve? So we can get a better idea of whether it's something that's better served with a customizable Material/Cupertino widget or an 'unskinned' widget.

**Comment by fmatosqg** [comment]
I'm not visualising anything specific, I guess this would be an approach to designing widget's apis that would help achieve both high level and high tweaking. A successful example would be having both the material button and at the same time the material, inkwell, button widgets separately.

**Comment by adriancmurray** [comment]
How about CupertinoTabScaffold and associated TabBar but with the TabBar having a Material graphical design? I want a hybrid between the two. Specifically, the indicator on the Material TabBar is what I'm after while maintaining the Navigation of a CupertinoTabScaffold having tabviews that are rendered off screen while also keeping a separate navigation history between tabs. I want the iOS Human Interface rules but with Material options. Make sense?

**Comment by artrmz** [comment]
I would add 'Allow hiding item's title" to the list :) It's common practice to hide titles on the bottom tabBar.

**Comment by xster** [comment]
Closing this since you [patched](https://github.com/flutter/flutter/pull/22804) this @artrmz
