### ISSUE TITLE
Upgrade check is too aggressive for beta channel

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#15862]
## Steps to Reproduce

Run a flutter command from current beta:

```
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 28 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝
```

At a minumum we should extend the window to be a bit longer, but ideally the check should see if an upgrade actually exists?

**Comment by MichaelSowah** [comment]
@mit-mit has there been a new beta release? :)

**Comment by mit-mit** [comment]
Not yet, one is expected fairly soon

**Comment by MichaelSowah** [comment]
:) How soon...lol...

**Comment by nni123** [comment]
actually, if you run flutter upgrade after the warning message it should not come back unless a new version is released. I was in hunting mode why flutter won't upgrade to latest version etc.

Node platform has a nice solution i.e. add @latest (e.g. flutter upgrade/@latest) or provide version number you want to upgrade

**Comment by mcfarljw** [comment]
![screen shot 2018-03-27 at 10 50 05 am](https://user-images.githubusercontent.com/4167341/37975202-c53ee58a-31ac-11e8-8028-72a988a8bf30.png)

I'm seeing this same message, but it's only been two days since I last ran update.

**Comment by mit-mit** [comment]
Cc @jcollins-g

**Comment by mit-mit** [comment]
> I'm seeing this same message, but it's only been two days since I last ran upgrade.
@mcfarljw does `flutter --version` confirm you are on a more recent version?

**Comment by mcfarljw** [comment]
```console
Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5a58b36e36 (3 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264
```

I haven't seen the message for a week or so now. I think it stopped displaying when it upgraded from `0.1.x` to `0.2.x`.

**Comment by mit-mit** [comment]
@Hixie @gspencergoog I wonder if the root issue here is us having "staleness" determined based on time. I think this was a good metric when most developers were on master, but now that we have regular beta releases, I wish we would tell developers when new builds were available based on their availability not based on time (i.e., if a developers runs flutter from the beta channel, and a more recent beta channel build is available, prompt them to upgrade)?

**Comment by gspencergoog** [comment]
This sounds reasonable to me. In order to know that there is a new version, we need to have a network connection and connect to a server, so it'll slow things down a little, and won't work offline, but I think that's might be OK.  Maybe we can just fork a process that does the check in the background, and you're not notified until the next time you run flutter (to avoid slowing things down).

**Comment by Hixie** [comment]
Checking if an update exists SGTM. I thought we actually did that.
cc @yjbanov who wrote this code
cc @tvolkert who owns this code

**Comment by tvolkert** [comment]
I'm gonna close this in favor of https://github.com/flutter/flutter/issues/14920

**Comment by yjbanov** [comment]
The original version "freshness" checking code was written before we had the beta channel. I totally support updating it.

**Comment by DanTup** [comment]
With #18016, users shouldn't ever see this warning if there isn't a newer version for their channel.
