### ISSUE TITLE
Checkbox is missing a ripple

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#15870]
The Checkbox widget is missing a ripple when toggled that is in the spec.

**Comment by HansMuller** [comment]
I think the checkbox's ink splash is correct. 

Ripple-style splashes aren't the default however the Flutter Gallery is configured that way. 

If you still think there's a problem, could you provide a screenshot that demos what doesn't match the spec?

**Comment by cbracken** [comment]
Thanks for your contribution. Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
