### ISSUE TITLE
AnimatedCrossFade between two Scaffolds shows gray background in middle frames

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#15873]
Here's a sample app: https://gist.github.com/alanrussian/4af31dfd27f339cfae52e7fd7962ceaf

In the middle frames, the background of the Scaffold is gray. I expect it to be white.

If you're a Googler I can PM you a video. GitHub won't let me add one here. 

![end](https://user-images.githubusercontent.com/2225255/37848651-1fe529a4-2e92-11e8-9096-642c1efee2f6.png)
![middle](https://user-images.githubusercontent.com/2225255/37848652-1ff6c3e4-2e92-11e8-9c3b-1c658b0b86c4.png)
![start](https://user-images.githubusercontent.com/2225255/37848654-20080276-2e92-11e8-8e43-3bafbb85bc9a.png)

This is a blocking issue for Mulligan.

**Comment by alanrussian** [comment]
We don't really need a cross-fade here. After thinking about this some more, mulligan can be unblocked by just doing a FadeTransition of just the second screen. Thanks.

**Comment by yjbanov** [comment]
`AnimatedCrossFade` uses `FadeTransition` behind the scenes. I imagine you'd have the same behavior, no?

**Comment by alanrussian** [comment]
`AnimatedCrossFade` will fade out the first widget and fade in the second widget. In our case, we can simply fade in the second widget on top of the first widget. I've tested this out, and it does not produce the artifacts I described in my OP.

**Comment by yjbanov** [comment]
Got it, but you should be able to tweak the `firstCurve` and `secondCurve` parameters of `AnimatedCrossFade`. `FadeTransition` LGTM too though, since you are not animating size.

**Comment by yjbanov** [comment]
I dropped the labels. But I'm also wondering if we should close this as working-as-intended. We can certainly change the intention, but I imagine that would be based on a different formulation of the problem.

**Comment by alanrussian** [comment]
I still think this is an issue. Why are grey frames being shown between two white screens?

**Comment by yjbanov** [comment]
Haven't verified it myself, but guessing the two widgets are semi-transparent during the transition, and the darkening of colors happens due to the black background being blended in. Normally you wouldn't cross-fade the entire `Scaffold`, and the background you temporarily see would be made of widgets that are under the `AnimatedCrossFade`.

**Comment by alanrussian** [comment]
Ok, makes sense. I guess if for some reason I needed to do a cross fade here, I could have put it on top of a widget that drew the `ThemeData.scaffoldColor`. Thanks!

**Comment by Vardiak** [comment]
No this doesn't make sense. A cross fade transition is not supposed to show the background. It would be a cross fade to black transition if it was. This issue should be reopened.

**Comment by yjbanov** [comment]
The cross fade is implemented by animating the opacities of the two widgets. When the opacity values are strictly between 0 and 1 they blend onto a third color, the background.

I can see how we could add a different blending mode, one that does not expose the background. However, that would be a separate feature request.
