### ISSUE TITLE
[flutter_svg] Can't load assets with declaring folder paths in pubspec.yml in Android Platform

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158795]
_Imported from https://github.com/dnfield/flutter_svg/issues/1033_

Original report by @Ali-Fadaei on Jan 20, 2024

### Issue
when declaring folders paths in pubspec.yml like tihs: 
```
assets:
  - assets/icons/filled/
```
and use it  `SvgPicture.asset('assets/icons/filled/user.svg')`   this error happens:

I/flutter (20755): Unable to load asset: "assets/icons/filled/user.svg".
I/flutter (20755): The asset does not exist or has empty data.
I/flutter (20755): #0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:324:9)

but when declaring each svg file on pubspec.yml like:
```
assets:
  - assets/icons/filled/user.svg
```
every thing is Ok but it's make hard to manage assets in large sccale projects.

this issue happen just  in android platform. (windows platform works fine!).

### Flutter Doctor
[!] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.22621.3007], locale en-US)
    ! Warning: `flutter` on your path resolves to C:\Flutter\flutter.bat, which is not inside your current Flutter SDK
      checkout at C:\Flutter\flutter. Consider adding C:\Flutter\flutter\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Flutter\dart.bat, which is not inside your current Flutter SDK
      checkout at C:\Flutter\flutter. Consider adding C:\Flutter\flutter\bin to the front of your path.
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.4)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources

---
Comment by @mohammadhosein13637 on Sep 29, 2024
I also encountered this problem and there is no way except to enter the exact path in pubsec.yml, this is really annoying

**Comment by jonahwilliams** [comment]
This isn't a bug with flutter svg
