### ISSUE TITLE
[flutter_svg] Artifacts/Pixelated Issues on iOS with changed colors of SVG when using impeller

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158755]
_Imported from https://github.com/dnfield/flutter_svg/issues/948_

Original report by @VirtualAstronaut on Jun 19, 2023

Hello, I am facing artifacts on iOS when using impeller and changed colours of SVG. One interesting is that when you use some height like 200 it does not show artifacts. 

`flutter_svg version - ^2.0.5`

## With Impeller
![Simulator Screenshot - iPhone 14 Pro - 2023-06-19 at 11 48 55](https://github.com/dnfield/flutter_svg/assets/36418182/521a1967-4fb1-4a35-be1f-4aa8e4fc8a17)
## Without Impeller
![without_impeller](https://github.com/dnfield/flutter_svg/assets/36418182/f5e5bf6c-05cc-4e55-996b-075110e232e3)

SVG: 
![activity](https://github.com/dnfield/flutter_svg/assets/36418182/53a1d146-483a-4832-9445-d5de3946034b)

Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```
here is sample code.
Code:
```

import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blueAccent),
        useMaterial3: true,
      ),
      home: const _SvgTest(),
    );
  }
}

class _SvgTest extends StatelessWidget {
  const _SvgTest({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SvgPicture.asset(
          'assets/activity.svg',
          colorFilter: const ColorFilter.mode(
            Color(0xff0231C8),
            BlendMode.srcIn,
          ),
        ),
      ),
    );
  }
}
```

---
Comment by @vscmaster on Jun 19, 2023
Hello,
facing same issue here, pixelated images on ios only.

---
Comment by @VirtualAstronaut on Jun 19, 2023
@vscmaster You can try disabling impeller for iOS with a flag tho. seems fine for now maybe when it is fixed we can enable it again. try flutter run with this flag
```--no-enable-impeller```

---
Comment by @beingsalmanshaikh on Jun 19, 2023
I'm experiencing the same issue!

---
Comment by @cogivn on Jun 20, 2023
I using ` flutter_svg: ^2.0.7` and facing this issue too.

---
Comment by @freethinkel on Jun 20, 2023
You can try wrapping `SvgPicture` widget with `Transform.scale(scale: 0.9999, child: child)`

---
Comment by @vscmaster on Jun 21, 2023
Hi @VirtualAstronaut, 
would you consider my investigation about another point that might cause the issue?

Some icons those have bigger size other than physical look pixelated.

Like this `<svg width="72" height="72" viewBox="0 0 72 72" fill="none"`
and this `<svg width="37" height="40" viewBox="0 0 37 40" fill="none"`

will look differently, the first one will have pixelated.

---
Comment by @VirtualAstronaut on Jun 26, 2023
Hello @vscmaster, so what are you saying is my SVG's dimension should be less than viewBox constraints? if i am not mistaken.

---
Comment by @jonas-zebari on Jun 28, 2023
Should this issue potentially also be reported to the Flutter team? It could end up being related to Impeller and not so much an issue on the part of this package.

---
Comment by @pavlo-zin on Jun 28, 2023
Looks like the issue is [already fixed](https://github.com/flutter/flutter/issues/129552) on Flutter master branch.

---
Comment by @GruppeGAM on Jul 14, 2023
I think not, because when I version 3.13.0-0.1.pre is with me, the error nevertheless. But if I set the flag --no-enable-impeller it works. 

---
Comment by @wiigolas on Aug 17, 2023
@pavlo-zin  I have tested this on - as seen in my report.
Flutter 3.12.0-11.0.pre.32 • channel master • https://github.com/flutter/flutter.git Framework • revision 7dbdacff46 (10 hours ago) • 2023-06-26 22:05:23 -0400 Engine • revision f320b8c36f Tools • Dart 3.1.0 (build 3.1.0-246.0.dev) • DevTools 2.24.0
It was working as intended. 

When upgrading today from 3.10.6 to 3.13.0 the issue still exists. 

---
Comment by @GiacomoPignoni on May 30, 2024
Hello, I just want to raise up again this issue because it still exists after almost 1 year, even it seems more rare then before. In my experience it still present on some svg, I can give another example

This svg has the problem
![floppy_disk](https://github.com/dnfield/flutter_svg/assets/34923063/f2bdb1b1-302a-4bf1-b9f6-3adf901ed311)

But this one not
![images](https://github.com/dnfield/flutter_svg/assets/34923063/39122fd3-7b85-4f69-b7d8-b20cd8cb31c1)

---
Comment by @Badar25 on Jul 8, 2024
Its still occuring

---
Comment by @maxAtIppen on Jul 11, 2024
Same issue https://github.com/dnfield/flutter_svg/issues/975

**Comment by jonahwilliams** [comment]
I believe this is fixed, assigning to myself to verify.

**Comment by jonahwilliams** [comment]
This fixed
