### ISSUE TITLE
Feature request: Object tree transfer of ownership between isolates

### ISSUE THREAD

**Issue by cbazza** [flutter/flutter#15875]
Basically I want a way to transfer an object (and all other objects linked from it) from one isolate to another. 
Right now you can only transfer basic primitives, lists and maps between isolates.

**Comment by Hixie** [comment]
You should be able to transfer anything between isolates except a few rare types like closures. It might be limited to immutable types? Not sure. But it's definitely more than just primitives. See for example: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/binding.dart#L64

Does that satisfy your needs?

**Comment by cbazza** [comment]
The example you provided is just transferring a list of strings which is supported as stated above (basic primitives, lists and maps).

**Comment by zoechi** [comment]
I thought this was supported but then reverted but I'm not sure.
Anyway I guess this should be reported in the Dart SDK repo.

**Comment by zoechi** [comment]
If you think there is still something that needs to be done, please create a new issue in the dart-lang/sdk repo. Isolates are not Flutter specific.
