### ISSUE TITLE
get-started codelab doesn't say how to "run your app"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15877]
I was going through the https://flutter.io/get-started/codelab/ codelab, and step 1 bullet point 2 just says "Run your app".

As I was pretending to be a new user, and I was editing the code from the command line with nano, I had no idea how to do that. The idea of running "flutter run" hasn't been broached by this point.

cc @Sfshaza

**Comment by Hixie** [comment]
The code lab does point to https://flutter.io/get-started/test-drive/#terminal which I see now has a section on how to run your app, but since I was directed to that page just to "create" the app, I didn't read past the section on creation.

**Comment by Sfshaza** [comment]
Fixed in PR https://github.com/flutter/website/pull/1124
