### ISSUE TITLE
arm64 macs in the devicelab in the staging pool are failing to pair with their attached iPhones

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#158740]
These machines

https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.staging&f=cpu%3Aarm64&f=device%3AiPhone12%2C1&k=device&s=id

Are failing like this:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8731399186119743441/+/u/Prepare_iOS_device/Dismiss_iOS_dialogs/Run_app_to_dismiss_dialogs/stdout

Which is causing `Mac_arm64_ios hot_mode_dev_cycle_ios__benchmark` to fail consistently after moving to `bringup: true` for https://github.com/flutter/flutter/issues/158241.

**Comment by zanderso** [comment]
@kentnguyen99 Could you check on these devices?

**Comment by kentnguyen99** [comment]
@zanderso, All phone devices were lost "trust" from the machine. Problems have resolved and fixed.  Can you ask end-user to give another try and and test again on these machines above?

**Comment by zanderso** [comment]
The test is passing in staging now. Thanks!
