### ISSUE TITLE
get-started codelab doesn't fully identify the pubspec.yaml file

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15878]
I was going through the https://flutter.io/get-started/codelab/ codelab, and step 2 just says "The pubspec file manages...". It doesn't call it `pubspec.yaml`. There are multiple `pubspec` files in the directory by this point.

cc @Sfshaza

**Comment by Sfshaza** [comment]
Fixed in PR https://github.com/flutter/website/pull/1124
