### ISSUE TITLE
Keyboard covers input fields that are at the bottom of a Column

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1587]

**Comment by abarth** [comment]
Do you have a specific case you're working with?  The keyboard adds some padding to the window so that widgets can move out of the way.  For example, the Scaffold sizes its body (and positions the floating action button, etc) to avoid the keyboard.

**Comment by collinjackson** [comment]
I understand that this supposed to work, it just doesn't seem to be doing it consistently. I'll add a reduced test case.

**Comment by collinjackson** [comment]
https://gist.github.com/collinjackson/3495326873871035d3e4

    import 'package:flutter/material.dart';

    void main() {
      runApp(
        new MaterialApp(
          title: "Input Demo",
          routes: <String, RouteBuilder>{
            '/': (RouteArguments args) => new FlutterDemo()
          }
        )
      );
    }

    class FlutterDemo extends StatefulComponent {
      @override
      State createState() => new FlutterDemoState();
    }

    class FlutterDemoState extends State {

      GlobalKey _inputKey = new GlobalKey();

      Widget build(BuildContext context) {
        return new Scaffold(
          toolBar: new ToolBar(
            center: new Text("Input Demo")
          ),
          body: new Material(
            child: new Center(
              child: new Column(
                children: <Widget>[
                  new Flexible(
                    child: new Container(
                      decoration: const BoxDecoration(
                        backgroundColor: const Color(0xFF00FF00)
                      )
                    )
                  ),
                  new Input(
                    key: _inputKey
                  )
                ]
              )
            )
          )
        );
      }
    }

**Comment by collinjackson** [comment]
![image](https://cloud.githubusercontent.com/assets/394889/12801021/33d2ffbe-ca8e-11e5-9a10-c4e78b6b435e.png)

**Comment by collinjackson** [comment]
/cc @qchong

@abarth do you want to investigate this one?

**Comment by abarth** [comment]
Yeah, I can take a look.

**Comment by abarth** [comment]
Works on my phone.
![screen](https://cloud.githubusercontent.com/assets/112007/12801142/284ba58c-ca8f-11e5-9f58-69f736ff7ec9.png)

clearzen:flutter abarth$ flutter --version
Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: 488285f11205337392cc337f1bd9bc502ce141f9 (2 hours ago)

Maybe it depends on the version of Android?  What Android version are you using?

**Comment by collinjackson** [comment]
I'm seeing it on both Android 5.1.1 and 6.0.1, tested on two Nexus 5s and a OnePlus.

flutter --version
Flutter from <unknown> (on )
flutter revision: 488285f11205337392cc337f1bd9bc502ce141f9 (2 hours ago)

**Comment by collinjackson** [comment]
@sethladd tried using a Nexus 6P with the latest Flutter revision and Android 6.0.1, same issue

**Comment by abarth** [comment]
That's pretty odd.  Hopefully I should be in the office tomorrow and we can look at it face-to-face.
