### ISSUE TITLE
cloud_firestore: 0.3.1 : Execution failed for task ':cloud_firestore:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by Ethras** [flutter/flutter#15883]
## Steps to Reproduce

Brand new flutter project, follow instruction to install cloud_firestore: "^0.3.1" and try to "flutter run"

## Logs

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:498: error: cannot inherit from final StandardMessageCodec
final class FirestoreMessageCodec extends StandardMessageCodec {
                                          ^
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:64: error: constructor StandardMethodCodec in class StandardMethodCodec cannot be applied to given types;
            new StandardMethodCodec(FirestoreMessageCodec.INSTANCE));
            ^
  required: no arguments
  found: FirestoreMessageCodec
  reason: actual and formal argument lists differ in length
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:498: error: StandardMessageCodec() has private access in StandardMessageCodec
final class FirestoreMessageCodec extends StandardMessageCodec {
      ^
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:505: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:509: error: cannot find symbol
      writeLong(stream, ((Date) value).getTime());
      ^
  symbol:   method writeLong(ByteArrayOutputStream,long)
  location: class FirestoreMessageCodec
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:512: error: cannot find symbol
      writeAlignment(stream, 8);
      ^
  symbol:   method writeAlignment(ByteArrayOutputStream,int)
  location: class FirestoreMessageCodec
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:513: error: cannot find symbol
      writeDouble(stream, ((GeoPoint) value).getLatitude());
      ^
  symbol:   method writeDouble(ByteArrayOutputStream,double)
  location: class FirestoreMessageCodec
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:514: error: cannot find symbol
      writeDouble(stream, ((GeoPoint) value).getLongitude());
      ^
  symbol:   method writeDouble(ByteArrayOutputStream,double)
  location: class FirestoreMessageCodec
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:517: error: cannot find symbol
      writeBytes(stream, ((DocumentReference) value).getPath().getBytes(UTF8));
      ^
  symbol:   method writeBytes(ByteArrayOutputStream,byte[])
  location: class FirestoreMessageCodec
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:519: error: writeValue(ByteArrayOutputStream,Object) is not public in StandardMessageCodec; cannot be accessed from outside package
      super.writeValue(stream, value);
           ^
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:523: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:529: error: cannot find symbol
        readAlignment(buffer, 8);
        ^
  symbol:   method readAlignment(ByteBuffer,int)
  location: class FirestoreMessageCodec
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:532: error: cannot find symbol
        final byte[] bytes = readBytes(buffer);
                             ^
  symbol:   method readBytes(ByteBuffer)
  location: class FirestoreMessageCodec
C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:536: error: cannot find symbol
        return super.readValueOfType(type, buffer);
                    ^
  symbol: method readValueOfType(byte,ByteBuffer)
Note: C:\Users\vladi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
14 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloud_firestore:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle build failed: 1

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [version 10.0.16299.309], locale fr-CH)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[!] VS Code (version 1.21.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by Ethras** [comment]
Ok found my solution. Needed to switch flutter branch to master instead of beta

**Comment by smkhalsa** [comment]
I had the same issue on iOS
