### ISSUE TITLE
[flutter_svg] SVG not rendering on Google/Android TV apk build

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158829]
_Imported from https://github.com/dnfield/flutter_svg/issues/1089_

Original report by @pmp02 on Jul 19, 2024

Hi

I have a Flutter app which loads and displays some images from a central location.
The application runs on web but on TVs as well.

Recently we want to add support for SVG images but we have some issues with rendering on the TVs.

This is the piece of code that should the display the SVG:

```
SvgPicture.network(
            graphicalContentNetwork,
            semanticsLabel: 'SVG Image',
            placeholderBuilder: (BuildContext context) =>
                const CircularProgressIndicator(),            
          );
```

pubspec.yaml: `flutter_svg: ^2.0.10+1`

The web build works fine (the SVG is supported and renders fine in the web build): `flutter build web --release`
The problem is with the APK build: `flutter build apk --release` . On this build, the SVG is not rendered at all.

Any suggestions?

Thanks in advance!

**Comment by jonahwilliams** [comment]
Hey, without an example to reproduce the problem we can't do anything here. One potential cause is that without adjusting the AndroidManifest settings release mode apps do not have http(s) access.
