### ISSUE TITLE
[flutter_svg] Load a picture in case the given picture doesn't exists.

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158802]
_Imported from https://github.com/dnfield/flutter_svg/issues/1044_

Original report by @aggeloskoutanis on Feb 28, 2024

Hello, first of all, thanks for this great package. Moving on, I would like to express a suggestion that might be handy in some situations. 

I work on a project where I fetch some courier companies from the server and then I iterate them and create a list of couriers with the name and the picture of the courier company.

The courier images are stored in the assets folder and are rendered to the user using SvgPicture.asset() constructor. 

**The problem:**

Sometimes, we introduce new couriers that the old mobile clients don't have the necessary data to display (i.ie.: the courier logo). 

**The solution:**

Here, it would have been helpful if SvgPicture.asset() constructor had an errorBuilder that renders a default courier icon if the asset is not found.

---
Comment by @dev-aniketj on Mar 23, 2024
@aggeloskoutanis  Consider using the null check operator or the if condition in your code to handle null values.

Developers should refrain from creating default icons since different developers require different icons to suit their needs.

---
Comment by @aggeloskoutanis on Mar 26, 2024
I don't suggest putting a default icon but exporting an error builder, where every developer can insert their Widget, which I would use to display my Error icon. 

Check for example Image.asset() from Flutter SDK.

**Comment by jonahwilliams** [comment]
This isn't something we're planning to adding.
