### ISSUE TITLE
[in_app_purchase_storekit] Prevent ios devices below ios 15 from enabling storekit

### ISSUE THREAD

**Issue by LouiseHsu** [flutter/flutter#158894]
Devices under ios 15 don't support storekit2, so add a version check.

**Comment by jmagman** [comment]
I thought the plan was to add a fallback to StoreKit 1 when run on > iOS 15?

**Comment by LouiseHsu** [comment]
yes, do they not mean the same thing? itll just revert to original storekit if its < ios 15

**Comment by jmagman** [comment]
> yes, do they not mean the same thing? itll just revert to original storekit if its < ios 15

I _think_ your PR does what I was expecting: the app can call `enableStoreKit2()` and on < iOS 15 it drops back to StoreKit1, without the app author needing to handle that case or even know that it happened, right?

https://github.com/flutter/packages/blob/e95f6d8fce589a6dfbd8ceb6f2ddaa537ec2b2e6/packages/in_app_purchase/in_app_purchase_storekit/lib/src/in_app_purchase_storekit_platform.dart#L45-L46

**Comment by LouiseHsu** [comment]
> > yes, do they not mean the same thing? itll just revert to original storekit if its < ios 15
> 
> I _think_ your PR does what I was expecting: the app can call `enableStoreKit2()` and on < iOS 15 it drops back to StoreKit1, without the app author needing to handle that case or even know that it happened, right?
> 
> https://github.com/flutter/packages/blob/e95f6d8fce589a6dfbd8ceb6f2ddaa537ec2b2e6/packages/in_app_purchase/in_app_purchase_storekit/lib/src/in_app_purchase_storekit_platform.dart#L45-L46

yep! no action from them. I also enabled storekit 2 in the example app and it should work correctly using the appropriate implementation no matter the device version
