### ISSUE TITLE
Add a `--dry-run` to `test.dart` to observe what shards run what tests

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#158884]
@matanlurey:

> Is there a deterministic (by humans) way of mapping a `package/foo/test/foo_test.dart` to the task and shard it is executing on? I'd settle for "I know the task, tell me the shard" if that is all we have.
> 
> For example, imagine the query:
> "I am a test owner of package/foo/test, and I want to see if foo_test.dart is running slowly"

@christopherfujino:

> There is a deterministic way, but it's not easy. We could add a special flag to `test.dart` though, that doesn't actually run any tests but prints out what tests would have run on which shard. this seems useful

**Comment by christopherfujino** [comment]
I believe that [this](https://github.com/flutter/flutter/blob/master/dev/bots/utils.dart#L546) is the function that's partitioning the test libraries between the sub-shards.
