### ISSUE TITLE
[flutter_svg] Correct error handling in custom ByteLoader

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158822]
_Imported from https://github.com/dnfield/flutter_svg/issues/1080_

Original report by @escamoteur on Jun 12, 2024

Hi @dnfield,

first of all, I'm thrilled by the elegance of your internal design. so it was pretty easy to add an `SvgCachedNetworkLoader` 

```dart
class SvgCachedNetworkLoader extends SvgLoader<File> {
  /// See class doc.
  const SvgCachedNetworkLoader(
    this.url, {
    this.headers,
    super.theme,
    super.colorMapper,
  });

  /// The [Uri] encoded resource address.
  final String url;

  /// Optional HTTP headers to send as part of the request.
  final Map<String, String>? headers;

  @override
  Future<File> prepareMessage(BuildContext? context) async {
    return await _cacheManager.getSingleFile(url, headers: headers);
  }

  @override
  String provideSvg(File? message) {
    final Uint8List bytes = message!.readAsBytesSync();
    return utf8.decode(bytes, allowMalformed: true);
  }

  @override
  int get hashCode => Object.hash(url, headers, theme, colorMapper);

  @override
  bool operator ==(Object other) {
    return other is SvgCachedNetworkLoader &&
        other.url == url &&
        other.headers == headers &&
        other.theme == theme &&
        other.colorMapper == colorMapper;
  }

  @override
  String toString() => 'SvgCachedNetworkLoader($url)';
}
```

Besides that I find it amazing that it is possible to pass a `File` to `compute` I wasn't sure if I need to do any special error handling in case `prepareMessage` or `provideSvg` throws an exception or if that is totally ok if they do.

**Comment by jonahwilliams** [comment]
I don't understand this bug it doesn't seem like anything is wrong. Closing.

**Comment by escamoteur** [comment]
@jonahwilliams I was asking to get clarification how svg_image expects the error handling if you create your own ByteLoader
