### ISSUE TITLE
get-started codelab links to unofficial files

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15880]
I was going through the https://flutter.io/get-started/codelab/ codelab, and at the end of step 2 it links to:

https://gist.githubusercontent.com/Sfshaza/bb51e3b7df4ebbf3dfd02a4a38db2655/raw/57c25b976ec34d56591cb898a3df0b320e903b99/pubspec.yaml
https://gist.githubusercontent.com/Sfshaza/bb51e3b7df4ebbf3dfd02a4a38db2655/raw/57c25b976ec34d56591cb898a3df0b320e903b99/main.dart

These should be hosted somewhere officially Flutter-related.

Also, the name in the pubspec.yaml is wrong.

cc @Sfshaza

**Comment by Hixie** [comment]
Step 3 also links to a solution file in this way.

**Comment by Sfshaza** [comment]
Fixed in PR https://github.com/flutter/website/pull/1124.
