### ISSUE TITLE
[flutter_svg] svg not displayed with public urls

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158827]
_Imported from https://github.com/dnfield/flutter_svg/issues/1086_

Original report by @karanSman on Jul 6, 2024

i have svg string which has public urls directly using the svg string does not display anything
when i use the base64 of url it is working and display.

**Comment by jonahwilliams** [comment]
@karanSman please file a new bug with an example of the SVG that does not work and we will investigate it.
