### ISSUE TITLE
Make `flutter --verbose` not opt-in to `pub --verbose`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#158896]
Using `flutter --verbose <command>` is potentially very useful when debugging.

However, for any command that implicitly (or otherwise) uses `pub`, the output is _way_ too much - overwhelmingly not useful, and not directly connected to what I'm trying to do. I'd like to propose making `--verbose` no longer imply `pub --verbose`.

I suspect it will be sufficient to use `flutter pub <command> --verbose` explicitly, or, if really needed, there can be a hidden `--pub-verbose` option (but I doubt this would be used). Open to what others think.

**Comment by jonahwilliams** [comment]
Ship it

**Comment by andrewkolos** [comment]
SGTM. I don't remember any instance where verbose pub output was useful.
