### ISSUE TITLE
[flutter_svg] How can I change the color of an SVG string using colorMapper

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158837]
_Imported from https://github.com/dnfield/flutter_svg/issues/1101_

Original report by @Marlenfranto on Oct 1, 2024

I want to change the color of an SVG before converting it to an image. Here's the code I'm currently using—how can I modify it to achieve this?

```
PictureInfo pictureInfo = await vg.loadPicture(SvgStringLoader(svgString), null);
image = await pictureInfo.picture.toImage(150, 150);
```

**Comment by jonahwilliams** [comment]
For questions on how to use Flutter svg please use a community chat channel and not the issue tracker.

**Comment by TesteurManiak** [comment]
> For questions on how to use Flutter svg please use a community chat channel and not the issue tracker.

I have the same question.
@jonahwilliams which community chat channel are you referring to?
