### ISSUE TITLE
[flutter_svg] Display issues when using --web-renderer html

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158803]
_Imported from https://github.com/dnfield/flutter_svg/issues/1045_

Original report by @momrak on Mar 8, 2024

I see some issues that seem related, at least
https://github.com/dnfield/flutter_svg/issues/960
https://github.com/dnfield/flutter_svg/issues/845

And we have the same in our app. One example here.
![CleanShot 2024-03-08 at 12 20 09@2x](https://github.com/dnfield/flutter_svg/assets/6552049/90ea1e16-2092-46b2-9d91-c3dd01e29623)

It is strange because some of the SVGs we use display properly while others will be similar to the attached image.

1. does anyone know what is causing some to be displayed weirdly while others look proper? Maybe we can change our SVGs if there is some simple workaround
2. is this being worked on or is it on the roadmap to look into?

Tested now with v2.0.10+1

---
Comment by @pedrolaranjeiro on May 6, 2024
I have the same issue.

**Comment by navaronbracke** [comment]
Since the HTML renderer will be deprecated soon, see #145954 I think this issue can be closed?

**Comment by yjbanov** [comment]
I agree. There are no plans to improve the HTML renderer beyond what it is right now. Closing.
