### ISSUE TITLE
Enable Java assertions on Android builds if you use --debug

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1588]
We have a bunch of them, but I'm guessing we've never actually run code with them enabled.

The web says:

```
adb shell setprop debug.assert 1
```

...should turn them on but I failed to reproduce this.

**Comment by Hixie** [comment]
@j9brown any ideas?

**Comment by eseidelGoogle** [comment]
@jason-simmons should we do something here?

**Comment by Hixie** [comment]
Jason didn't know about this either.

I'm going to close this bug. We don't know enough to enable this, and nobody has been asking for it. We can revisit if we get more concrete information or requests.
