### ISSUE TITLE
How to add on tap gesture on a textField?

### ISSUE THREAD

**Issue by rohanpanda001** [flutter/flutter#15882]
## Add onTap gesture on a textField
onTap gesture using GestureDetector class is working for every element except for the textField type.
How can i use onTap gesture on textfield element?

**Comment by zoechi** [comment]
You can wrap it in a GestureDetector (or InkWell)

**Comment by cyrsis** [comment]
```
new TextField(
                  controller: _textController,
                  onChanged: (String txt) {
                    _isWriting = txt.length > 0;
                  },
                  onSubmitted: _submitMsg,
                  decoration: new InputDecoration.collapsed(
                      hintText: "Enter Some Text to send a message"),
                ),

```

**Comment by NiklasPor** [comment]
@Freundschaft you have to disable the TextField ( ``enabled: false``). Then wrap it with a gesture recognizer (or InkWell). If you wanna navigate and use your textfield as your hero, just pass it enabled in it's constructor. Just tested it, works without flaws (except that you cannot type in the TextField, obviously 😅 ).

**Comment by Freundschaft** [comment]
alright, but then how can I add this functionality AND type in the textfield? 😄

**Comment by NiklasPor** [comment]
@Freundschaft First you create a new stateful widget and disable the TextField in it. Then when your `onTap` gets triggered, you change the state of your TextField set `enable: true` and `autofocus: true`. It's kind of an hack and you may have to adjust the style of your TextField, that it look like enabled even when disabled. I suggest you to create a custom Widget and manage everything in there. Good luck 😃

**Comment by NiklasPor** [comment]
@AlexandreRoba I've found a better way to make this possible using the `IgnorePointer` Widget. 
Take a look at the following example. It increases the counter and opens the TextField thereafter:
```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int timesTapped = 0;
  TextEditingController controller;
  FocusNode focusNode;

  @override
  void initState() {
    super.initState();
    controller = TextEditingController();
    focusNode = FocusNode();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          Text('TextField tapped $timesTapped'),
          GestureDetector(
            onTap: _onTap,
            child: Container(
              color: Colors.green,
              child: IgnorePointer(
                child: TextField(
                  focusNode: focusNode,
                  controller: controller,
                ),
              ),
            ),
          )
        ],
      ),
    );
  }

  void _onTap() {
    setState(() {
      timesTapped++;
    });

    FocusScope.of(context).requestFocus(focusNode);
  }
}
```

**Comment by NiklasPor** [comment]
@AlexandreRoba try setting the background color of your wrapping Container to Colors.transparent. I'm not sure what the exact hitbox of the TextField is.

Like this:
``` dart
[...]
child: Container(
    color: Colors.transparent,
    child: IgnorePointer(
        child: TextField(
[...]
```

**Comment by AlexandreRoba** [comment]
@NiklasPor This works!!!! thanks! should this be filled as a Bug?

**Comment by NiklasPor** [comment]
@AlexandreRoba No, I don't think so. [IgnorePointer](https://docs.flutter.io/flutter/widgets/IgnorePointer-class.html) disables all gestures on underlying widgets. To give the widgets under IgnorePointer a valid hitbox, we surround them with the transparent Container. 

Anyway I am no developer of the flutter project. If other behavior is intended, they may decide on this 🤷‍♂️

**Comment by ROTGP** [comment]
I'm not sure what you're trying to achieve here but why don't you just add a listener to the textfield's focus node? 

`focusNode.addListener(textFieldFocusDidChange);
void textFieldFocusDidChange() {
    if (focusNode.hasFocus) {
      // textfield was tapped
    }
  }
`

**Comment by NiklasPor** [comment]
@ROTGP I would be careful with your solutions. It also gets triggered if another way of focusing is used. E.g. by tapping next in another textfield..

**Comment by ROTGP** [comment]
@NiklasPor of course, that's why I prefaced my comment with "I'm not sure what you're trying to achieve".

**Comment by alanrussian** [comment]
I've just discovered calling `FocusScope.of(context).requestFocus(...)` is not good enough. It does not [request for the keyboard](https://github.com/flutter/flutter/blob/9bf8502fef3f35d8d3ba692ce0383e9f55a34624/packages/flutter/lib/src/material/text_field.dart#L491). This can be an issue in the following case:

1. Tap on text field. We provide it focus. This opens the keyboard.
2. Tap Android back button. Keyboard is dismissed. Field still has focus.
3. Tap on text field again. We try to provide it focus again but this doesn't do anything. **There is no way to get the keyboard back up.** 

In order to display the keyboard, we need to call `requestKeyboard` on the `EditableTextState` but this is [not exposed to us](https://github.com/flutter/flutter/blob/9bf8502fef3f35d8d3ba692ce0383e9f55a34624/packages/flutter/lib/src/material/text_field.dart#L441) as the global key is private.

**Comment by Hixie** [comment]
@alanrussian That sounds like a distinct bug than this one. Would you mind filing a new bug to track that? Thanks.

**Comment by alanrussian** [comment]
Filed a separate issue. Fixing either of these issues would address our need. Thanks.

**Comment by MilkBiscuit** [comment]
What about TextFormField? I found onTap does not work for TextFormField case as well.
Flutter version 1.0.0

**Comment by zoechi** [comment]
@MilkBiscuit if it does not work in `dev` channel (`flutter channel dev`) please create a new issue. This issue is closed.

**Comment by caztial** [comment]
> I'm not sure what you're trying to achieve here but why don't you just add a listener to the textfield's focus node?
> 
> ```
> focusNode.addListener(textFieldFocusDidChange);
> void textFieldFocusDidChange() {
>     if (focusNode.hasFocus) {
>       // textfield was tapped
>     }
>   }
> ```

This is working like a charm when you need to get onTap on a TextFormField

**Comment by alanrussian** [comment]
For me, I wanted to know when a user tapped on a field, even if it already
had focus.

**Comment by HansMuller** [comment]
https://docs.flutter.io/flutter/material/TextField/onTap.html

**Comment by Kilo-Loco** [comment]
> @Freundschaft, @AlexandreRoba I've found a better way to make this possible using the [IgnorePointer](https://docs.flutter.io/flutter/widgets/IgnorePointer-class.html) Widget.
> Take a look at the following example. It increases the counter and opens the TextField thereafter:
> 
> view demo
> view sourcecode
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   int _timesTapped = 0;
>   TextEditingController controller;
>   FocusNode focusNode;
> 
>   @override
>   void initState() {
>     super.initState();
>     controller = TextEditingController();
>     focusNode = FocusNode();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Column(
>         mainAxisAlignment: MainAxisAlignment.spaceAround,
>         children: <Widget>[
>           Text('TextField tapped $_timesTapped'),
>           GestureDetector(
>             onTap: _onTap,
>             child: Container(
>               color: Colors.green,
>               child: IgnorePointer(
>                 child: TextField(
>                   focusNode: focusNode,
>                   controller: controller,
>                 ),
>               ),
>             ),
>           )
>         ],
>       ),
>     );
>   }
> 
>   void _onTap() {
>     setState(() {
>       _timesTapped++;
>     });
> 
>     FocusScope.of(context).requestFocus(focusNode);
>   }
> }
> ```

This solution works only if you set the color for the container for some reason. Just set the color to `Colors.transparent` and it will work as expected

**Comment by sanjay4one** [comment]
Simply use `onTap` function of `TextField`.

`TextField(
              onTap: () {
                //Your code
              })`

**Comment by shakiz** [comment]
Wrapping it with InkWell widget will to your work even though the TextField is disabled.

`InkWell(
       onTap: () {
             _yourMethod();
       },
       child: Container(
             child: TextField(
                    enabled: false,
                        onChanged: (value) {
                           },
                    ),
)),`

**Comment by Balday2** [comment]
a textfield has already an on tape: 
TextField( onTap: () =>{}, ... );
