### ISSUE TITLE
[flutter_svg] colorFilter not working in Flutter Web Apps on mobile devices with iOS 17.2 on Safari anymore

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158821]
_Imported from https://github.com/dnfield/flutter_svg/issues/1079_

Original report by @chrisDK1977 on Jun 12, 2024

SvgPicture.asset(pathToAsset, colorFilter: ColorFilter.mode(Color(0xFFFF0000), BlendMode.srcIn));

... tints the asset red on iOS 15 on Safari on mobile devices but not when mobile device is running on safari  on iOS17.2 it does not change the color.

---
Comment by @jannisnikoy on Jun 13, 2024
I *think* this might be a change in Flutter 3.22 that broke it. Noticed the same issue after upgrading our project to latest Flutter SDK.

---
Comment by @chrisDK1977 on Jun 16, 2024
@dnfield Should I open an issue in the flutter project or is this project the correct place for the bug?

---
Comment by @chrishibler on Aug 13, 2024
I'm seeing the same thing. It works as expected in desktop Chrome, but not on iOS web.

---
Comment by @Hmmza-tariq on Sep 11, 2024
I am also facing this issue, anyone knows the solution?

---
Comment by @Hmmza-tariq on Sep 11, 2024
Update:
 This solution worked for me:
`flutter run -d chrome --web-renderer=canvaskit`
`flutter build web --release --web-renderer canvaskit`

**Comment by jonahwilliams** [comment]
Closing this as out of date.
