### ISSUE TITLE
[flutter_svg] Undefined class 'DrawableRoot

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158800]
_Imported from https://github.com/dnfield/flutter_svg/issues/1042_

Original report by @Tigran-Kosemyan on Feb 21, 2024

I use old version after update I have any problems. 
Undefined class 'DrawableRoot'
Drawable also not found,
image  to byte data also not

---
Comment by @osnipezzini on Feb 27, 2024
Same here, i moved to PNG to fix temporarily 

---
Comment by @lore-co on Aug 19, 2024
Same

**Comment by jonahwilliams** [comment]
This functionality was removed from flutter svg in 2.0 as noted in the breaking changes.
