### ISSUE TITLE
[flutter_svg] Flutter Web CanvasKit Rendere View Not Displayed

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158805]
_Imported from https://github.com/dnfield/flutter_svg/issues/1049_

Original report by @parancode on Mar 21, 2024

I used HtmlElementView with ui.platformViewRegistry.registerViewFactory. 

However, starting from the 8th HtmlElementView, the z-index becomes abnormal and the Flutter view moves behind it. 
I tried various options to solve this, but the problem persists.

**Comment by jonahwilliams** [comment]
This is not a problem with Flutter SVG.
