### ISSUE TITLE
get-started codelab has old quote for hot reload warning

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15881]
I was going through the https://flutter.io/get-started/codelab/ codelab, and there is mention of the "hot reload might have failed" warning. However, it quotes old text that appears to no longer be correct. We currently say the following:

```
Some program elements were changed during reload but did not run when the view was reassembled;
you may need to restart the app (by pressing "R") for the changes to have an effect.
```

cc @Sfshaza

**Comment by Sfshaza** [comment]
Fixed in PR https://github.com/flutter/website/pull/1124
