### ISSUE TITLE
Spell checker returns null in TextField with custom spellCheckSuggestionsToolbarBuilder

### ISSUE THREAD

**Issue by iamnicat** [flutter/flutter#158929]
### Steps to reproduce

The spell checker functionality in a TextField widget is not working as expected. When trying to use a custom contextMenuBuilder and spellCheckSuggestionsToolbarBuilder in combination with spellCheckConfiguration, editableTextState.spellCheckResults returns null when printed. It seems the spell check service is not triggering properly or returning results as expected.

Reproduction Steps:

Create a TextField with the following configurations:
contextMenuBuilder that prints editableTextState.spellCheckResults.
spellCheckConfiguration using DefaultSpellCheckService with a spellCheckSuggestionsToolbarBuilder that also prints editableTextState.spellCheckEnabled.
Type text into the TextField to trigger spell checking.
Expected Results: editableTextState.spellCheckResults should provide spell check results when printed, and spellCheckEnabled should reflect the correct status.

Actual Results: editableTextState.spellCheckResults and spellCheckEnabled return null, indicating the spell checker is not functioning as expected.

### Expected results

editableTextState.spellCheckResults should return a list of spelling errors or suggestions when printed.
editableTextState.spellCheckEnabled should indicate whether spell checking is active.

### Actual results

editableTextState.spellCheckResults and spellCheckEnabled return null, indicating that the spell checker is either not initialized or not functioning.

### Code sample

<details open><summary>Code sample</summary>

```dart
TextField(
  enableSuggestions: true,
  autocorrect: true,
  contextMenuBuilder: (context, editableTextState) {
    print(editableTextState.spellCheckResults); // Returns null
    return SpellCheckSuggestionsToolbar.editableText(
      editableTextState: editableTextState,
    );
  },
  spellCheckConfiguration: SpellCheckConfiguration(
    spellCheckService: DefaultSpellCheckService(),
    spellCheckSuggestionsToolbarBuilder: (context, editableTextState) {
      print(editableTextState.spellCheckEnabled); // Also returns null
      return SpellCheckSuggestionsToolbar.editableText(
        editableTextState: editableTextState,
      );
    },
  ),
)

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B2082 darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Users/nijathajiyev/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.95.2)
    • VS Code at /Users/nijathajiyev/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • iPhone 16 Pro (mobile)          • CAFB639C-EA21-49AD-B4EA-F3CBB5B21E7A • ios          •
      com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64 • macOS 15.1 24B2082
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin       • macOS 15.1 24B2082
      darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @iamnicat 
Checking the issue using Flutter master version `3.27.0-1.0.pre.511` on Android and iOS apps, I see:
- On Android, when I type text on TextField, both `spellCheckResults` and `spellCheckEnabled` are null as reported. But if I select text on TextField, I see `spellCheckResults` output as below and there is no suggestion popup appears (as iOS below)

```console
I/flutter ( 1548): editableTextState.spellCheckResults: SpellCheckResults(spellCheckText: abc store , suggestionSpans: [])
I/flutter ( 1548): editableTextState.spellCheckResults: SpellCheckResults(spellCheckText: abc store , suggestionSpans: [])
I/flutter ( 1548): editableTextState.spellCheckResults: SpellCheckResults(spellCheckText: abc store fohj, suggestionSpans: [])
```

- On iOS, `spellCheckResults` and `spellCheckEnabled` are also null when typing text but it seems the expected results are here when selecting text:

```console
flutter: editableTextState.spellCheckEnabled: true
flutter: editableTextState.spellCheckResults: SpellCheckResults(spellCheckText: fhg , suggestionSpans: [SuggestionSpan(range: TextRange(start: 0, end: 3), suggestions: [fog, fig, fhb])])
```


<img width="400" src="https://github.com/user-attachments/assets/ac7b98e3-c936-4718-a250-73885790f590">

So, I wonder if the text selection is a correct trigger or I am missing something. Can you retry and confirm?

**Comment by iamnicat** [comment]
@huycozy  can you share your code please?

**Comment by huycozy** [comment]
I only re-use your code. Here is the complete one:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: TextField(
        enableSuggestions: true,
        autocorrect: true,
        contextMenuBuilder: (context, editableTextState) {
          print('editableTextState.spellCheckResults: ${editableTextState.spellCheckResults}'); // Returns null
          return SpellCheckSuggestionsToolbar.editableText(
            editableTextState: editableTextState,
          );
        },
        spellCheckConfiguration: SpellCheckConfiguration(
          spellCheckService: DefaultSpellCheckService(),
          spellCheckSuggestionsToolbarBuilder: (context, editableTextState) {
            print('editableTextState.spellCheckEnabled: ${editableTextState.spellCheckEnabled}'); // Also returns null
            return SpellCheckSuggestionsToolbar.editableText(
              editableTextState: editableTextState,
            );
          },
        ),
      ),
    );
  }
}

```
</details>

**Comment by iamnicat** [comment]
@huycozy  Thanks, I checked again, but it is same, maybe because of flutter version, it does not work?

**Comment by huycozy** [comment]
Do you mean `spellCheckResults` and `spellCheckEnabled` are still null when selecting text? 

_Update to my comment [above](https://github.com/flutter/flutter/issues/158929#issuecomment-2478376730) after I check this again: Actually, it behaves the same on Android. We should select a **misspelled** word, and then a suggestion popup will appear. In my test above, I selected a correct word, that is reason why the suggestion popup did not appear._

So, to conclude this from my end: `spellCheckResults` and `spellCheckEnabled` are not null when selecting **misspelled** word. Can you please confirm this?
