### ISSUE TITLE
When selecting an image, a future exception is thrown

### ISSUE THREAD

**Issue by lifufa** [flutter/flutter#158923]
### Steps to reproduce

call pickMultiImage

Current test devices: iPhone 15 with system version 17.6.1, and iPhone 16 Pro with version 18.0.1, both have this issue.

### Expected results

 a future no exception

### Actual results

a future exception is thrown

### Code sample

<details open><summary>Code sample</summary>

```dart
List<XFile> pick = await _picker.pickMultiImage(limit: IMAGE_LIMIT_COUNT - imageUrlList.length, imageQuality: 50, requestFullMetadata: false);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @lifufa, please provide the following 

- The actual error you're getting
- The version of `image_picker` & `image_picker_ios` you're using
- The output of `flutter doctor -v`

Thank you

**Comment by lifufa** [comment]
https://pub.dev/packages/image_picker
image_picker 1.1.2


trl@trls-MacBook-Air-3 ios % flutter doctor -v
![Uploading 20241115-191900.jpeg…]()

[✓] Flutter (Channel stable, 3.19.0, on macOS 14.4.1 23E224 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.0 on channel stable at /Users/trl/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (9 months ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/trl/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (3 available)
    • Cliff的iPhone (mobile) • 00008120-001661562112201E • ios            • iOS 18.2 22C5131e
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 130.0.6723.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by lifufa** [comment]
![20241115-192709](https://github.com/user-attachments/assets/6a653aa4-401a-4cf8-af86-79c3d4baeca4)

**Comment by lifufa** [comment]
![Uploading 20241115-191900.jpeg…]()

**Comment by lifufa** [comment]
![20241115-191900](https://github.com/user-attachments/assets/4d44268d-673c-4114-9a9a-cc29d80b02a2)
