### ISSUE TITLE
AAPT2 aapt2-7.3.1-8691043-windows Daemon #0: Daemon startup failed

### ISSUE THREAD

**Issue by ugur010** [flutter/flutter#158931]
```console
PS C:\Users\ugura\Desktop\Mobileapp> flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 3688 bytes (99.8% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 aapt2-7.3.1-8691043-windows Daemon #0: Daemon startup failed
     Please check if you installed the Windows Universal C Runtime.
     This should not happen under normal circumstances, please file an issue if it does.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 10s
Running Gradle task 'assembleRelease'...                           10,8s
Gradle task assembleRelease failed with exit code 1
```

```console
PS C:\Users\ugura\Desktop\Mobileapp> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19045.5131], locale tr-TR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Derleme Araçları 2019 16.11.41)
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.95.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
PS C:\Users\ugura\Desktop\Mobileapp> 
```

**Comment by ugur010** [comment]
helppp :(

**Comment by huycozy** [comment]
This looks like a Gradle settings issue. Do you see this issue on a newly created Flutter project? 

Can you share these file contents? (please remove sensitive info if any)

- /android/settings.gradle
- /android/build.gradle
- /android/gradle/wrapper/gradle-wrapper.properties

**Comment by ugur010** [comment]
> This looks like a Gradle settings issue. Do you see this issue on a newly created Flutter project?
> 
> Can you share these file contents? (please remove sensitive info if any)
> 
> * /android/settings.gradle
`pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.1" apply false
    id "org.jetbrains.kotlin.android" version "1.9.20" apply false
    id "com.google.gms.google-services" version "4.3.15" apply false
}

include ":app"`


> * /android/build.gradle
`allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}`
> * /android/gradle/wrapper/gradle-wrapper.properties
`#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip`

**Comment by huycozy** [comment]
I am using the same AGP and Gradle versions on a new Flutter project but don't see the error as reported. All APK files are built as expected. 

I see you are using an old Flutter version. Can you try upgrading it and retry? I am on Flutter stable 3.24.5.
