### ISSUE TITLE
Network Image Height Limit in Flutter

### ISSUE THREAD

**Issue by ironfactory8684** [flutter/flutter#158903]
### Steps to reproduce

I'm encountering an issue in Flutter when loading extremely tall images (e.g., 1080x19174) from a network source. When I check the image's height using ImageStreamListener, it doesn't exceed 8192, which results in the image appearing squashed.

Here’s the code I’m using to retrieve the image dimensions:

```
final ImageStreamListener listener = ImageStreamListener(
  (ImageInfo info, bool _) {
    completer.complete(Size(
      info.image.width.toDouble(),
      info.image.height.toDouble(),
    ));
  },
);
```
The image’s actual height is 19174, but it gets capped at 8192, causing distortion. Is there a way to bypass this limitation or handle extremely tall images without squashing them?

Any advice or solutions would be greatly appreciated. Thank you!

### Expected results

The image should display with its correct dimensions, maintaining the original aspect ratio, even if the height is greater than 8192.

### Actual results

The image’s height is capped at 8192, which distorts the image and causes it to appear squashed.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

host@host-MacBookPro talk % flutter doctor -v
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.2 23C64 darwin-arm64, locale ko-KR)
    • Flutter version 3.24.1 on channel stable at /Users/jepiloseu/Desktop/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 months ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jepiloseu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.89.1)
    • VS Code at /Users/jepiloseu/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (5 available)
    • iPhone (mobile)                 • 00008101-001A689C2220001E            • ios            • iOS 18.1 22B83
    • iPhone 15 Pro Max (mobile)      • 2A6AE4AF-B725-4F65-95B1-95FFDE88692A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 130.0.6723.117
    ! Error: Browsing on the local area network for iPhone (4). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by ironfactory8684** [comment]
Hello @danagbemava-nc 

I'm seeing this issue on the following devices/platforms:
- Samsung Galaxy S24
- Samsung Galaxy S20
- iPhone 11
- iOS Simulator

The issue occurs when using Image.network:
```dart
Image.network(imgUrl)
```

So I checked image size using ImageStreamListener:

```dart
final ImageStreamListener listener = ImageStreamListener(
  (ImageInfo info, bool _) {
    completer.complete(Size(
      info.image.width.toDouble(),
      info.image.height.toDouble(),
    ));
  },
);
```
After checking the image heights, I discovered that any image with a height greater than 8192 pixels is being automatically compressed. For example:

Original image size: 1080 x 19174 pixels
Compressed to: 1080 x 8192 pixels

This compression maintains the original width but forces the height to 8192 pixels, causing image distortion. I've confirmed this behavior occurs consistently with multiple images that exceed 8192 pixels in height.
Let me know if you need any additional code samples to reproduce this issue.

Thank you

**Comment by danagbemava-nc** [comment]
Hi @ironfactory8684, we will need a full runnable code sample along with some sample images so that we can properly investigate this. 

Thank you
