### ISSUE TITLE
Noticeable lag, fps drop, long response time in 3.24 in debug mode

### ISSUE THREAD

**Issue by darielkurt** [flutter/flutter#158908]
### Steps to reproduce

Ever since our app has upgraded to 3.24.0, it is very laggy like fps drop when ran in debug mode compared when we are in 3.13.8. It is annoying while developing.

This happens on both Android and iOS, whether physical device, emulator, or simulator (high-end devices too)
This does not happen when ran in Impeller mode

Our suspects are; Flutter 3.24.0, the packages which are upgraded up to date

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Performance profiling on master channel

- [X] The issue still persists on the master channel

### Timeline Traces

[dart_devtools_2024-11-14_15_22_01.989.json.zip](https://github.com/user-attachments/files/17744777/dart_devtools_2024-11-14_15_22_01.989.json.zip)
<details open><summary>Timeline Traces JSON</summary>

</details>

### Video demonstration

<details open>
<summary>Video demonstration</summary>

[Upload media here]

</details>

### What target platforms are you seeing this bug on?

Android, iOS

### OS/Browser name and version | Device information

This happens on both Android and iOS, whether physical device, emulator, or simulator (high-end devices too)

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Is the problem only reproducible with Impeller?

No

### Logs

<details open><summary>Logs</summary>

```console
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.4.1 23E224
    darwin-arm64, locale en-PH)
    • Flutter version 3.24.0 on channel stable at
      /Users/kurtdariel/.asdf/installs/flutter/3.24.0-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (4 months ago), 2024-07-30
      23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK
    version 34.0.0)
    • Android SDK at /Users/kurtdariel/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)            
    • SM A715F (mobile)               • R58N94EZYZW           •
      android-arm64  • Android 13 (API 33)
    • macOS (desktop)                 • macos                 •
      darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad •
      darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                •
      web-javascript • Google Chrome 131.0.6778.69

[✓] Network resources
    • All expected network resources are available.

• No issues found!
                           
```

</details>

**Comment by huycozy** [comment]
Hello @darielkurt,
Application performance can be janky in debug mode. You should measure performance in [profile](https://docs.flutter.dev/testing/build-modes#profile) mode on an actual device (see https://docs.flutter.dev/testing/build-modes).

In case the issue persists in profile mode, please try to narrow your code down into a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so we can look into it. And please also share the device info (OS version and model name).

**Comment by darielkurt** [comment]
Hi @huycozy, I indicated above that there are no problems when it is in profile mode (or release mode). It only occurs on debug mode. I understand that it can be janky in debug mode but it is more noticeably janky in Flutter 3.24.0 compared to our previous Flutter version 3.13.8. 

However, I find that it is performing fine when running the Flutter 3.24.0 version on Impeller mode, which I just learned from the issue template when submitting this issue.

**Comment by huycozy** [comment]
Impeller is enabled by default on iOS (on all Flutter channels) and Android (on Flutter beta and master channels currently, not on stable 3.24.5 yet: https://github.com/flutter/engine/pull/54156), see more at https://docs.flutter.dev/perf/impeller.

If you still see performance issue without Impeller enabled in **Profile** mode and think it should be solved, please provide a sample code as mentioned above for further investigation.
