### ISSUE TITLE
Please analyze the code lab snippets

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#15890]
We currently have one codelab, which lives on flutter.io. The code for each step of the codelab should be analyzed when new versions Flutter are released. For I/O, we'll have around 8 codelabs, so we'll need to analyze all relevant code going forward. (I expect most of our codelab code will live in Git repos.)

Codelab: [Write Your First Flutter App](https://flutter.io/get-started/codelab/)
Code:
*  [Step 1](https://gist.github.com/Sfshaza/a87b03bbb0bde68abeddc976bf95827c)
*  [Step 2](https://gist.github.com/Sfshaza/bb51e3b7df4ebbf3dfd02a4a38db2655)
*  [Step 3](https://gist.github.com/Sfshaza/d7f13ddd8888556232476be8578efe40)
*  [Step 4](https://gist.github.com/Sfshaza/d6f9460a04d3a429eb6ac0b0f07da564)
*  [Step 5](https://gist.github.com/Sfshaza/936ce0059029a8c6e88aaa826a3789cd)
*  [Step 6](https://gist.github.com/Sfshaza/bc5547e112e4dc3a1aa87afdf917caeb)
*  [Step 7](https://gist.github.com/Sfshaza/c07c91a4061fce4b5eacaaf4d82e4993)

**Comment by Hixie** [comment]
Can you elaborate on what you would like? For example, do you want us to download each step above, and run `flutter analyze` on it, for every PR on the framework repo? Or...?

**Comment by travisbhartwell** [comment]
I think this issue would address one I filed recently: flutter/website#2539. I had some confusion trying to following the codelab mentioned by @Sfshaza above because of two different versions of the code. Using `flutter analyze` and `dartfmt --fix` I was able to get the code I had previous to nearly match the newer code.

**Comment by iapicca** [comment]
Hi @Sfshaza 
given your [answer](https://github.com/flutter/website/issues/2539#issuecomment-500537230) I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
