### ISSUE TITLE
In the Flutter 3.24.5, AppLifecycleListener. OnStateChange and didChangeAppLifecycleState didn't work

### ISSUE THREAD

**Issue by M2dL1fe** [flutter/flutter#158971]
### Steps to reproduce

AppLifecycleListener. OnStateChange  or  didChangeAppLifecycleState

### Expected results

working

### Actual results

not working

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @M2dL1fe, please provide a complete minimal reproducible code sample along with detailed steps to reproduce so that we can properly investigate this. 

Thank you

**Comment by Kuhlemann** [comment]
Hi @M2dL1fe, 

using AppLifecycleListener works proper in my case with Flutter 3.24.5.
Tested on Android virtual device.

`  late final AppLifecycleListener _lifecycleListener;
`
```
@override
  void initState() {
    super.initState();
    _lifecycleListener = AppLifecycleListener(
      onResume: () => _handleResume(),
    );
  };
```

```
  void _handleResume() {
    log('App was resumed');
  }
```

**Comment by M2dL1fe** [comment]
Sorry. Just reboot the computer and it works @Kuhlemann
