### ISSUE TITLE
Flutter web canvaskit cors errors.

### ISSUE THREAD

**Issue by edze-worla-alex** [flutter/flutter#158983]
### Steps to reproduce

1. Build the flutter web project with --web-renderer canvaskit.
2. Deploy to liveserver.
3. Try accessing the site.
4. Cors prevents canvaskit.wasm access

### Expected results

Canvaskit loads and initiates the app.

### Actual results

Access to fetch at 'https://unpkg.com/canvaskit-wasm@0.33.0/bin/canvaskit.wasm' from origin 'http://deployment.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.Understand this error
unpkg.com/canvaskit-wasm@0.33.0/bin/canvaskit.wasm:1 
        
       Failed to load resource: net::ERR_FAILEDUnderstand this error
canvaskit.js:257 

### Code sample

<details open><summary>Code sample</summary>

```html
<html><head>
    <base href="/">
    <meta charset="UTF-8">
    <meta content="IE=Edge" http-equiv="X-UA-Compatible">
    <meta name="description" content="Sikanua Diets">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Sikanua Diets">
    <link rel="apple-touch-icon" href="icons/Icon-192.png">
    <link rel="icon" type="image/png" href="favicon.png">
    <title>Deployment</title>
    <link rel="manifest" href="manifest.json">
  
<script src="https://unpkg.com/canvaskit-wasm@0.33.0/bin/canvaskit.js"></script></head>

<body class="loaded">
    <div id="app">
    </div>

    <script>
        if ('serviceWorker' in navigator) {
            window.addEventListener('flutter-first-frame', function() {
                navigator.serviceWorker.register('flutter_service_worker.js?v=1714280078');
            });
        }
    </script>
    <script src="main.dart.js" type="application/javascript"></script>

</body></html>
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>

```console
Access to fetch at 'https://unpkg.com/canvaskit-wasm@0.33.0/bin/canvaskit.wasm' from origin 'http://deploymeny.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.Understand this error
unpkg.com/canvaskit-wasm@0.33.0/bin/canvaskit.wasm:1 
        
       Failed to load resource: net::ERR_FAILEDUnderstand this error
canvaskit.js:257 
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Not applicable

</details>

**Comment by darshankawar** [comment]
@edze-worla-alex 
Is this only occuring for your project or if you create a new Flutter project and deploy, you still see the same error ?
