### ISSUE TITLE
How to hide underline in TextField Widget?

### ISSUE THREAD

**Issue by BarbaricGamester** [flutter/flutter#15893]
I am trying to make iOS native search bar but according to iOS guidelines there are no underlines for the search bar so how can I remove this, Wasn't flutter suppose to be cross-platform?

**Comment by goderbauer** [comment]
You can set the `border` property of the `decoration` of the textfield to `InputBorder.none`, see here for an example:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/search.dart#L424

**Comment by jdiegodcp** [comment]
Hey @BarbaricGamester  sorry if this is too late but the way to fix it was using a Scaffold to utilize correctly Material Package.
the link for more info is here: https://stackoverflow.com/a/47123685

hope it helps for whoever is looking for an answer.
