### ISSUE TITLE
Inconsistent constraints

### ISSUE THREAD

**Issue by MariaMelnik** [flutter/flutter#158976]
### Steps to reproduce

1. Run code sample

### Expected results

No overflow error (sizes of the text and surrounding SizedBox are the same)

### Actual results

There is overflow error

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  static const multiplier = 1.19444444444444;
  
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: SizedBox(
            height: 24 * multiplier, 
            child: Column(
              children: [
                 Text('Hello, World!', style: TextStyle(fontSize: 24 * multiplier, height: 1)),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![flutter_01](https://github.com/user-attachments/assets/5da87430-725a-46e9-be54-d247aca99d0a)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6 23G80 darwin-arm64, locale
    ru-RS)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.2.3)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@MariaMelnik 
Check [this](https://docs.flutter.dev/testing/common-errors) document to see if it helps in your case or not.

**Comment by MariaMelnik** [comment]
@darshankawar unfortunately not. In the example sizes are the same for outer container and inner text.
