### ISSUE TITLE
Will Camera have MacOS support in the near future?

### ISSUE THREAD

**Issue by hammonjj** [flutter/flutter#158948]
### Use case

I apologize that I don't know where else to ask this question, but I see the MacOS Camera package that seems to work OK but definitely has some different implementation details than the rest of the package. Is getting MacOS camera support something that is currently on the roadmap?

### Proposal

Is it possible to merge in the MacOS implementation to the Flutter repository? If not, what needs to be done to make it happen. I would be willing to take this on

**Comment by stuartmorgan** [comment]
macOS support is tracked in https://github.com/flutter/flutter/issues/41708; closing as a duplicate.

> Is it possible to merge in the MacOS implementation to the Flutter repository? If not, what needs to be done to make it happen. I would be willing to take this on

Anyone interested in implementing macOS support is welcome to continue the work of the branch I linked to in that issue.
