### ISSUE TITLE
Scrolling list changes lead to graphical glitches

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#159]
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [collinjackson](https://github.com/collinjackson)**
_Thursday Sep 10, 2015 at 23:03 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1125_

----

This demo should sort a scrollable list of green bubbles by brightness when you press the sort button. But there are some graphical glitches, try scrolling around and sorting a few times.

    // Copyright 2015 The Chromium Authors. All rights reserved.
    // Use of this source code is governed by a BSD-style license that can be
    // found in the LICENSE file.

    import 'package:sky/widgets.dart';

    class Circle extends Component {
      Circle(this.color);

      final Color color;

      Widget build() {
        return new Container(
          decoration: new BoxDecoration(
            shape: Shape.circle,
            backgroundColor: color
          )
        );
      }
    }

    List<Color> colors = [
      const Color(0x0F00FF00),
      const Color(0xCF00FF00),
      const Color(0x1F00FF00),
      const Color(0xBF00FF00),
      const Color(0xAF00FF00),
      const Color(0x9F00FF00),
      const Color(0x3F00FF00),
      const Color(0x8F00FF00),
      const Color(0x4F00FF00),
      const Color(0x7F00FF00),
      const Color(0x5F00FF00),
      const Color(0x6F00FF00)
    ];

    class ScrollingApp extends App {
      bool shouldSort = false;

      Widget build() {
        List<Color> sortedColors = new List<Color>.from(colors);
        if (shouldSort) {
          sortedColors.sort((a, b) => a.alpha.compareTo(b.alpha));
        }
        List<Widget> circles = [];
        for(Color color in sortedColors) {
          circles.add(new Circle(color));
        }
        for(int i = 0; i < colors.length; i++)
        return new Column([
          new Container(
            height: 300.0,
            child: new ScrollableViewport(
              // key: new GlobalKey(),
              child: new Grid(
                circles,
                maxChildExtent: 150.0
              )
            )
          ),
          new Flexible(
            child: new Center(
              child: new RaisedButton(
                child: new Text("Toggle sorting"),
                onPressed: () => setState(() => shouldSort = !shouldSort)
              )
            )
          )
        ]);
      }
    }

    void main() {
      runApp(new ScrollingApp());
    }

**Comment by FlutterIssues** [comment]
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [collinjackson](https://github.com/collinjackson)**
_Thursday Sep 10, 2015 at 23:04 GMT_

----

![screen](https://cloud.githubusercontent.com/assets/394889/9803256/9149c924-57d5-11e5-8a70-7ea9ad722e80.png)

**Comment by FlutterIssues** [comment]
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [collinjackson](https://github.com/collinjackson)**
_Thursday Sep 10, 2015 at 23:04 GMT_

----

cc @abarth @Hixie

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Tuesday Sep 15, 2015 at 05:22 GMT_

----

cc @chinmaygarde for a first look

**Comment by sethladd** [comment]
I have a feeling this is out of date. :) Should we close?

**Comment by Hixie** [comment]
We should test it :-)

**Comment by sethladd** [comment]
We should test a lot of stuff :)

Going to close, but feel free to open a new issue specific to testing.
