### ISSUE TITLE
Delete Firebase Auth User

### ISSUE THREAD

**Issue by Cretezy** [flutter/flutter#15907]
With the latest version of Firebase Auth (0.5.2), it is impossible to delete a user.

Other Firebase Auth libraries (such as the one for Web) have a `user.delete()` instance method, which is missing from the Flutter implementation.

I would like to do a PR, although I do not have a iOS dev enviroment setup. I'll see if I can set one up shortly, but I think this could be a pretty trivial PR for anyone else to do!

**Comment by Asoseil** [comment]
+1

**Comment by aqwert** [comment]
Just wanting to give this a slight bump. With the [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) coming in, the user should be able to delete their account. If not offered through the firebase plugin then there will have to be some other manual way of doing this, such as emailing the organisation. Having said that deleting a user's account beyond firebase_auth would be needed such as other personally created data.

**Comment by RobertBrunhage** [comment]
The following link contains an example from firebase about how they use the .delete() function.

https://firebase.google.com/docs/auth/android/manage-users#re-authenticate_a_user

Scroll down to Delete a user.

**Comment by ISGinnovations** [comment]
You could also use a Cloud Function like this:
```javascript
const admin = require('firebase-admin');
admin.initializeApp();

exports.deleteUser = functions.firestore
    .document('users/{userID}')
    .onDelete((snap, context) => {
      return admin.auth().deleteUser(snap.id)
          .then(() => console.log('Deleted user with ID:' + snap.id))
          .catch((error) => console.error('There was an error while deleting user:', error));
    });
```

**Comment by huextrat** [comment]
Any news about this important feature ? :/

**Comment by baeharam** [comment]
> You could also use a Cloud Function like this:
> 
> ```js
> const admin = require('firebase-admin');
> admin.initializeApp();
> 
> exports.deleteUser = functions.firestore
>     .document('users/{userID}')
>     .onDelete((snap, context) => {
>       return admin.auth().deleteUser(snap.id)
>           .then(() => console.log('Deleted user with ID:' + snap.id))
>           .catch((error) => console.error('There was an error while deleting user:', error));
>     });
> ```

Can only it be with javascript?

**Comment by peek4y** [comment]
Any updates on this feature?

**Comment by HadiSDev** [comment]
How is this not implemented yet ? 😂😂😂 It is so basic, and so crucial to have.

**Comment by collinjackson** [comment]
It looks like this was added in https://github.com/flutter/plugins/pull/928

**Comment by kroikie** [comment]
@Cretezy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/875. Any further collaboration will be done there.

**Comment by Abhishek-kumar09** [comment]
FireBase Authenticated user can be deleted : [StackOverFlow](https://stackoverflow.com/a/58780768/11966205),this just only deletes the user fron FireBase Authentication List

**Comment by Rajdeep-4321** [comment]
But now delete function is available in auth for flutter..
So what is code to dele current user?

**Comment by joseph9991** [comment]
> But now delete function is available in auth for flutter..
> So what is code to dele current user?

Have you found anything? I also need to give an option to my user to delete his account and his data!! But, there is no proper solution!!
