### ISSUE TITLE
My app runs on high CPU and makes my phone(both iOS and android) heated up

### ISSUE THREAD

**Issue by lushuang07** [flutter/flutter#159059]
### Steps to reproduce

Our app is a live streaming platform where real-time videos are broadcast, accompanied by numerous animation effects. The more animations there are in the live room, the easier it is for the phone to overheat, and the CPU and memory usage become extremely high, more than double that of iOS native apps. After using it for five to six minutes, it becomes very laggy.

Our app uses WebSocket for communication (there are many instant messaging interactions in the live room, with frequent data communication), and the video is provided by a third-party vendor. Almost all the UI is written in Flutter. The above tests were conducted in release mode without the charger connected.

I found that when the original app created with Flutter is opened, the CPU usage is consistently at 5% to 6%, while for a native app, the CPU usage is 0% in such a scenario. Additionally, when clicking a button to increment a number, the CPU usage spikes to 60% to 70%.

Can anyone help solve these problems?

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```
My dart

</details>

### What target platforms are you seeing this bug on?

Android, iOS

### OS/Browser name and version | Device information

iphone 15

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Flutter (Channel stable, 3.24.5, on macOS 15.0.1 24A348 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.24.5 on channel stable at /Users/gaigai/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/gaigai/flutter. Consider adding
      /Users/gaigai/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 days ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gaigai/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)            
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 130.0.6723.119
    ! Error: Browsing on the local area network for Shaw’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for 卢双的iPhone. Ensure the device
      is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@lushuang07 
Please provide us reproducible code sample that shows the reported behavior. Without it would be difficult to address the issue.

https://stackoverflow.com/help/minimal-reproducible-example
