### ISSUE TITLE
Test wrapper code should be a sharable resource

### ISSUE THREAD

**Issue by keertip** [flutter/flutter#15903]
The source for the [test wrapper](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart#L607-L637) that is generated during test should be made available. Currently in our internal workflow we are using a copy of this, and so can lead to skew.

**Comment by zoechi** [comment]
I assume the link above should point to https://github.com/flutter/flutter/blob/3352a3fb488df4742ff323243d3dc44d9b7cd3e8/packages/flutter_tools/lib/src/test/flutter_platform.dart#L606-L636

Seems to be https://github.com/flutter/flutter/blob/8426910a19abc4ab081c58fd1a72c433353eaa31/packages/flutter_tools/lib/src/test/flutter_platform.dart#L184-L212 now

Is this still relevant?

**Comment by tvolkert** [comment]
This was fixed by the creation of the `generateTestBootstrap()` method.
