### ISSUE TITLE
Image.asset render difference macOS vs Windows

### ISSUE THREAD

**Issue by LeoRc01** [flutter/flutter#159075]
### Steps to reproduce

Place an Image.asset in a view and start the software desktop in macOS and Windows

### Expected results

Images looking the same

### Actual results

Windows image has much less quality compared to macOS

### Code sample

<details open><summary>Code sample</summary>

This is the image placed in a stack

```dart
        Positioned(
          top: 0,
          bottom: 0,
          left: 0,
          right: 0,
          child: Image.asset(
            'assets/images/background/galbusera.png',
            scale: 7,
            filterQuality: FilterQuality.high,
          ),
        ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

(first one is Windows, then macOS)

![Immagine 2024-11-18 145916](https://github.com/user-attachments/assets/83b49618-e4a6-41c0-a457-01428910127d)
![Screenshot 2024-11-18 alle 15 06 59](https://github.com/user-attachments/assets/eff0ef2c-6b29-47bc-9883-884ab8e55576)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale
    it-IT)
    • Flutter version 3.24.3 on channel stable at
      /Users/leonardo/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (10 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/leonardo/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.95.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • iPhone di Leonardo (mobile)     • 00008120-000638C03AF3C01E • ios
      • iOS 18.0.1 22A3370
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 130.0.6723.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @LeoRc01 
Have you observed this difference on other platforms (if any)? Can you please attach the original image file here? Thanks!

**Comment by LeoRc01** [comment]
Hi @huycozy thanks for your reply.
No, I didn't try it out on different platforms.

This is the original file!

![galbusera](https://github.com/user-attachments/assets/323ec86c-bd57-4133-a9eb-c4c0505ab4f3)

**Comment by huycozy** [comment]
Thanks for your update. Using the asset image above, I can see the issue appears on both Windows and macOS apps. However, I think this is an issue with `filterQuality` instead, please check demo below for its variants:

| filterQuality: none/low/high | filterQuality: medium |
| --------------- | --------------- |
<img width="400" src="https://github.com/user-attachments/assets/c903915a-5fcd-4d4c-9196-d3eb88baa9ad"> | <img width="400" src="https://github.com/user-attachments/assets/43d997fe-c782-4566-aee9-ab74c20051d9">

And I found that, when scaling them down, `medium` is frequently better (see https://github.com/flutter/flutter/issues/82919#issuecomment-853416029).

Can you retry with these filterQuality(s) and confirm?

**Comment by LeoRc01** [comment]
@huycozy I have tried and it looks much better! Thanks a lot!

Do you have any suggestion to make it look even sharper? Do you think switching to SVG would make it look better? 

Thanks again!

**Comment by huycozy** [comment]
>Do you have any suggestion to make it look even sharper? Do you think switching to SVG would make it look better?

Maybe you can also try this? https://docs.flutter.dev/ui/assets/assets-and-images#resolution-aware. 

I will close the original issue to concentrate on https://github.com/flutter/flutter/issues/82919. Thank you for confirming that.
