### ISSUE TITLE
Issue guidance for "resource only" packages

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#15905]
Meta issue in the `pub` repository: https://github.com/dart-lang/pub/issues/1848.

In particular, @xster and @ScottS2017 want to know what the best way is to create resource/asset-only packages, and whether we need additional functionality in pub (or otherwise). Might be worth tracking here for the "official" Flutter response.

**Comment by ScottS2017** [comment]
Also, I'm finishing an article for Medium on doing this via path packages in pubspec.yaml and then using that local package (on your own hard drive) to keep your entire library of images, audio, video and code. This way you can access all of your local resources via one, simple path package import.

I still need to write a sample package and sample app that uses it but the (very) rough draft of the article is here:

https://github.com/ScottS2017/local_package/blob/master/lib/Image%20Library%20Article.docx

**Comment by zoechi** [comment]
Did this work? 
Is there still anything for the Flutter team to do?

**Comment by ScottS2017** [comment]
The path packages did the job that was needed at the time. It just wasn't all that easy to find out how to use them.
