### ISSUE TITLE
Android test VIVO, HUWEI even if the fps is set to 1, the actual capture is still 24fps

### ISSUE THREAD

**Issue by tolink-Mengtianfu** [flutter/flutter#159062]
### Steps to reproduce

      cameraController = CameraController(frontCamera!, ResolutionPreset.low,enableAudio: false,imageFormatGroup: ImageFormatGroup.jpeg,fps: 1);

### Expected results

fps is set to 1, but the actual capture should be 1fps, which is currently only normal on iOS

### Actual results

The fps is set to 1, but the actual capture is still 24fps

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by tolink-Mengtianfu** [comment]
fps is set to 1 result on Android phones

https://github.com/user-attachments/assets/3b862392-3644-4f8e-8728-c315b7904328

fps is set to 1 result on iOS phones

https://github.com/user-attachments/assets/dd94d0b7-6e37-4c08-82ef-eed42edbfbaa

The iOS platform preview component and startImageStream callback are expected to be 1fps, Android platform preview component and startImageStream callback even set 1fps, but the actual capture is still 24fps

**Comment by darshankawar** [comment]
@tolink-Mengtianfu 
Can you provide your `flutter doctor -v` and camera plugin version you are using ?
Also please provide the Android device details which you listed (make, model, OS version).

**Comment by tolink-Mengtianfu** [comment]
@darshankawar Thank you for your reply

![image](https://github.com/user-attachments/assets/19fe2cc1-ed2e-406a-8b0b-2539269972ca)
I have tested three different brands of Android phones in total, and I will send the detailed parameters of the other two brands tomorrow



➜  gqdz_camera git:(完整版) ✗ flutter doctor                               
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.95.1)
[✓] Connected device (5 available)


camera plugin version is 
  camera: ^0.11.0+2

**Comment by darshankawar** [comment]
@tolink-Mengtianfu 
Please try with camera plugin [example](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) and pass `fps: 1` in it on same affected devices you mentioned to see if you still get same behavior or not.
