### ISSUE TITLE
✔️ Ideas to reduce `flutter build apk` flakes on CI

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#159000]
_Working theory: This is caused by https://github.com/flutter/flutter/issues/51421._

---

_A lot of credit goes both to @gmackall and @reidbaker for offline conversations that led to this issue._

As of today (2024-11-15), different integration tests (in particular, tooling integration tests, if that ends up mattering) are having somewhat significant and currently undiagnosed problems with tests that call (and block on) `flutter build apk`.

For example:

- <https://github.com/flutter/flutter/issues/157640>
- <https://github.com/flutter/flutter/issues/158560>

Three possible things happen that end up leading to failures:

1. The test times out (taking longer than 15m) or the shard times out (taking longer than 30-60m)
2. The test fails due to a Java Heap/OOM
3. The test fails due to (hypothesis) the OS killing Gradle due to low memory

Some things to try:

- [x] Try creating a `bringup: true` shard where failures happen somewhat consistently to try fixes
- [x] Try adding `--verbose` to get information about the version of Gradle/Gradle settings being used
- [ ] Remove the `no-daemon` from recipes which doesn't appear to be having any effect/is confusing
- [ ] Try using [jps](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jps.html) to list active Java processes and memory usage between/after tests.
- [ ] Try running with double the amount of RAM to see if higher memory lowers flakes significantly

/cc @andrewkolos @bkonyi.

**Comment by matanlurey** [comment]
> Is the current state that your bringup tests are a clone of an existing shard/subshard?

No, because unfortunately that is impossible (https://github.com/flutter/flutter/issues/158972).

**Comment by gmackall** [comment]
Do you know what the flake rate of the existing shard it copied is? Should we have expected to see one for certain by now?

Perhaps there is some difference between staging and prod bots?

**Comment by matanlurey** [comment]
> Do you know what the flake rate of the existing shard it copied is? Should we have expected to see one for certain by now?

It was relatively high (6%) before I added the skip statements, though that _did_ include timeouts that were a result of the shard being too large, so it is possible it just hasn't happened yet. I suppose I could use LED to try and "speed things up" :P

**Comment by gmackall** [comment]
Not directly related to building apks, but another instance of something randomly taking much longer than expected:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20build_android_host_app_with_module_source/235/overview

**Comment by matanlurey** [comment]
I haven't observed a flake ever since the process cleanup, so I am closing for now.
