### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Illegal character in path

### ISSUE THREAD

**Issue by Arty1909** [flutter/flutter#159052]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Illegal character in path
```console
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1934:11)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:2036:7)
#2      new _Uri.file (dart:core/uri.dart:1897:11)
#3      NativeAssetsBuildRunner._compileHookForPackageCached.<anonymous closure> (package:native_assets_builder/src/build_runner/build_runner.dart:672:27)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:442:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:371:26)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:190:27)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#8      new List.of (dart:core-patch/array_patch.dart:40:18)
#9      ListIterable.toList (dart:_internal/iterable.dart:224:7)
#10     NativeAssetsBuildRunner._compileHookForPackageCached (package:native_assets_builder/src/build_runner/build_runner.dart:673:12)
<asynchronous suspension>
#11     NativeAssetsBuildRunner._runDryRun (package:native_assets_builder/src/build_runner/build_runner.dart:416:11)
<asynchronous suspension>
#12     _runDartDryRunBuild (package:flutter_tools/src/isolated/native_assets/native_assets.dart:839:42)
<asynchronous suspension>
#13     runFlutterSpecificDartDryRunOnPlatforms (package:flutter_tools/src/isolated/native_assets/native_assets.dart:173:36)
<asynchronous suspension>
#14     HotRunner.run (package:flutter_tools/src/run_hot.dart:371:26)
<asynchronous suspension>
#15     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:853:27)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
```
```console
[32m[✓][39m Flutter (Channel main,
    3.27.0-1.0.pre.536, on
    Microsoft Windows [Version
    10.0.19045.5131], locale en-US)
    [32m•[39m Flutter version
      3.27.0-1.0.pre.536 on channel
      main at C:\flutter
    [32m•[39m Upstream repository
      https://github.com/flutter/fl
      utter.git
    [32m•[39m Framework revision 41c273f8c6
      (4 hours ago), 2024-11-17
      09:12:30 -0500
    [32m•[39m Engine revision 4878f1c9ed
    [32m•[39m Dart version 3.7.0 (build
      3.7.0-157.0.dev)
    [32m•[39m DevTools version 2.41.0-dev.2

[32m[✓][39m Windows Version (10 Enterprise
    64-bit, 22H2, 2009)

[32m[✓][39m Android toolchain - develop for
    Android devices (Android SDK
    version 35.0.0)
    [32m•[39m Android SDK at
      C:\Users\ADMIN\AppData\Local\
      Android\Sdk
    [32m•[39m Platform android-35,
      build-tools 35.0.0
    [32m•[39m ANDROID_HOME =
      C:\Users\ADMIN\AppData\Local\
      Android\Sdk
    [32m•[39m Java binary at: C:\Program
      Files\Android\Android
      Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK

**Comment by Arty1909** [comment]
+Runtime%0A++++++Environment+%28build%0A++++++17.0.10%2B0--11572160%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses%0A++++++accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram%0A++++++Files%5CGoogle%5CChrome%5CApplicati%0A++++++on%5Cchrome.exe%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Visual+Studio+-+develop+Windows%0A++++apps+%28Visual+Studio+Community%0A++++2022+17.6.5%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+at+C%3A%5CProgram%0A++++++Files%5CMicrosoft+Visual%0A++++++Studio%5C2022%5CCommunity%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+Community+2022%0A++++++version+17.6.33829.357%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+10+SDK+version%0A++++++10.0.22000.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2024.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+C%3A%5CProgram%0A++++++Files%5CAndroid%5CAndroid+Studio%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be%0A++++++installed+from%3A%0A++++++%F0%9F%94%A8%0A++++++https%3A%2F%2Fplugins.jetbrains.com%0A++++++%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed%0A++++++from%3A%0A++++++%F0%9F%94%A8%0A++++++https%3A%2F%2Fplugins.jetbrains.com%0A++++++%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime%0A++++++Environment+%28build%0A++++++17.0.10%2B0--11572160%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.90.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at%0A++++++C%3A%5CUsers%5CADMIN%5CAppData%5CLocal%5C%0A++++++Programs%5CMicrosoft+VS+Code%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version%0A++++++3.100.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%284+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+sdk+gphone64+x86+64+%28mobile%29%0A++++++%E2%80%A2+emulator-5554+%E2%80%A2+android-x64%0A++++++%E2%80%A2+Android+15+%28API+35%29%0A++++++%28emulator%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+%28desktop%29%0A++++++%E2%80%A2+windows+++++++%E2%80%A2+windows-x64%0A++++++%E2%80%A2+Microsoft+Windows+%5BVersion%0A++++++10.0.19045.5131%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29%0A++++++%E2%80%A2+chrome++++++++%E2%80%A2%0A++++++web-javascript+%E2%80%A2+Google%0A++++++Chrome+131.0.6778.69%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Edge+%28web%29%0A++++++%E2%80%A2+edge++++++++++%E2%80%A2%0A++++++web-javascript+%E2%80%A2+Microsoft%0A++++++Edge+131.0.2903.51%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Network+resources%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+expected+network%0A++++++resources+are+available.%0A%0A%1B%5B32m%E2%80%A2%1B%5B39m+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+main%0A%2A%2ACreation+framework+version%2A%2A%3A+41c273f8c66c4a5a373cea8b13605c6d7c813829%0A%0A&labels=tool%2Csevere%3A+crash

**Comment by darshankawar** [comment]
@Arty1909 
Are you consistently getting this error while running `flutter run` ?
Can you also check if you have any invalid chars in assets or in pubspec.yaml file ?

**Comment by Arty1909** [comment]
> @Arty1909 Are you consistently getting this error while running `flutter run` ? Can you also check if you have any invalid chars in assets or in pubspec.yaml file ?


I launched a copy of the flutter scene project on Windows 10 in the Android 15 emulator in the main branch

**Comment by darshankawar** [comment]
> copy of the flutter scene project

Can you provide link of this ?

**Comment by darshankawar** [comment]
Not sure if it is related to https://github.com/flutter/flutter/pull/155745

/cc @mkustermann for thoughts. 

> ```
> NativeAssetsBuildRunner._compileHookForPackageCached.<anonymous closure> (package:native_assets_builder/src/build_runner/build_runner.dart:672:27)
> #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:442:31)
> #5      ListIterator.moveNext (dart:_internal/iterable.dart:371:26)
> #6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:190:27)
> #7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
> #8      new List.of (dart:core-patch/array_patch.dart:40:18)
> #9      ListIterable.toList (dart:_internal/iterable.dart:224:7)
> #10     NativeAssetsBuildRunner._compileHookForPackageCached (package:native_assets_builder/src/build_runner/build_runner.dart:673:12)
> <asynchronous suspension>
> #11     NativeAssetsBuildRunner._runDryRun (package:native_assets_builder/src/build_runner/build_runner.dart:416:11)
> <asynchronous suspension>
> #12     _runDartDryRunBuild (package:flutter_tools/src/isolated/native_assets/native_assets.dart:839:42)
> <asynchronous suspension>
> #13     runFlutterSpecificDartDryRunOnPlatforms (package:flutter_tools/src/isolated/native_assets/native_assets.dart:173:36)
> <asynchronous suspension>
> ```

@Arty1909 Can you provide a clear log of below ? Currently it is not formatted so can't read it properly. Please provide a formatted text.

> +Runtime%0A++++++Environment+%28build%0A++++++17.0.10%2B0-

**Comment by dcharkes** [comment]
@Arty1909 What is the path your flutter project?

**Comment by Arty1909** [comment]
> Not sure if it is related to #155745
> 
> /cc @mkustermann for thoughts.
> 
> > ```
> > NativeAssetsBuildRunner._compileHookForPackageCached.<anonymous closure> (package:native_assets_builder/src/build_runner/build_runner.dart:672:27)
> > #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:442:31)
> > #5      ListIterator.moveNext (dart:_internal/iterable.dart:371:26)
> > #6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:190:27)
> > #7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
> > #8      new List.of (dart:core-patch/array_patch.dart:40:18)
> > #9      ListIterable.toList (dart:_internal/iterable.dart:224:7)
> > #10     NativeAssetsBuildRunner._compileHookForPackageCached (package:native_assets_builder/src/build_runner/build_runner.dart:673:12)
> > <asynchronous suspension>
> > #11     NativeAssetsBuildRunner._runDryRun (package:native_assets_builder/src/build_runner/build_runner.dart:416:11)
> > <asynchronous suspension>
> > #12     _runDartDryRunBuild (package:flutter_tools/src/isolated/native_assets/native_assets.dart:839:42)
> > <asynchronous suspension>
> > #13     runFlutterSpecificDartDryRunOnPlatforms (package:flutter_tools/src/isolated/native_assets/native_assets.dart:173:36)
> > <asynchronous suspension>
> > ```
> 
> @Arty1909 Can you provide a clear log of below ? Currently it is not formatted so can't read it properly. Please provide a formatted text.
> 
> > +Runtime%0A++++++Environment+%28build%0A++++++17.0.10%2B0-


You can simply run your library according to your instructions on an Android emulator in the Windows 10 development environment, and you will immediately get all the bugs

**Comment by Arty1909** [comment]
> @Arty1909 What is the path your flutter project?
> 
> That line is trying to read the dep file, maybe somehow that gets corrupted on Windows with certain characters in the path.
> 
> You cold take a look at `<your-project>/.dart_tool/native_assets_builder/<long-hash>/hook.dill.d` to see if there is an invalid file path in there. (Invalid characters `["*/:<>?\\|]`)
> 
> As a workaround, you can delete `<your-project>/.dart_tool/native_assets_builder/`, that should purge all caches related to native assets.


all paths similar given instructions

**Comment by darshankawar** [comment]
@Arty1909 
We tried to run the said repo on Windows but unable to properly run it, as you pointed to `node.dart` which is throwing error and it doesn't have `main.dart`. If you could provide exact steps to replicate, would be helpful to address it properly.
