### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by hyplegfabricvot** [flutter/flutter#159065]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```console
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/tools/shader_compiler.dart:190:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:221:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:187:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:1005:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:583:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:334:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.5, on macOS 14.6.1 23G93 darwin-x64, locale
    en-NG)
    [32m•[39m Flutter version 3.24.5 on channel stable at
      /usr/local/Caskroom/flutter/3.24.5/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision dec2ee5c1f (5 days ago), 2024-11-13 11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[33m[!][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS
      and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [32m•[39m CocoaPods version 1.16.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.83.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 14.6.1 23G93 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.119

[33m[!][39m Network resources
    [31m✗[39m A cryptographic error occurred while checking "https://pub.dev/":
      Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be
      compromised, or you may have malware installed on your computer.
    [31m✗[39m A network error occurred while checking "https://storage.googleapis.com/":
      Connection failed
    [31m✗[39m A network error occurred while checking "https://maven.google.com/":
      Failed host lookup: 'maven.google.com'
    [31m✗[39m A network error occurred while checking "https://cocoapods.org/": Failed
      host lookup: 'cocoapods.org'
    [31m✗[39m A network error occurred while checking "https://github.com/": Failed host
      lookup: 'github.com'

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.0.1+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f72efea43c3013323d1b95cff571f3c1caa37583
### Plugins
connectivity_plus-5.0.2
desktop_drop-0.4.4
device_info_plus-9.1.2
irondash_engine_context-0.4.1
path_provider-2.1.5
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
screen_retriever-0.1.9
super_native_extensions-0.7.3
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.1
url_launcher_linux-3.2.1
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
window_manager-0.3.9

**Comment by danagbemava-nc** [comment]
Hi @hyplegfabricvot, can we get the full output of `flutter run -v` when this crash occurs? 

Is this a frequent occurrence for you?

**Comment by hyplegfabricvot** [comment]
It's my first time trying to run it

below is the output of flutter run -v 


[  +32 ms] executing: sw_vers -productName
[  +41 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +28 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.6.1
[        ] executing: sw_vers -buildVersion
[  +25 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23G93
[        ] executing: uname -m
[   +8 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +16 ms] executing: sysctl hw.optional.arm64
[  +12 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +45 ms] Unable to locate an Android SDK.
[ +306 ms] executing: sysctl hw.optional.arm64
[  +12 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[  +31 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer
tool or in PATH
[   +9 ms] Xcode not found. Run 'flutter doctor' for more information.
[  +56 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required,
skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +220 ms] executing: xcrun xcodebuild -version
[  +15 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer
tool or in PATH
[   +5 ms] executing: xcrun simctl list devices booted
[  +40 ms] Exit code 72 from: xcrun simctl list devices booted
[        ] xcrun: error: unable to find utility "simctl", not a developer tool
or in PATH
[  +17 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +42 ms] executing: xcrun xcodebuild -version
[  +16 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer
tool or in PATH
[ +115 ms] Connected devices:
[+18106 ms] macOS (desktop) • macos  • darwin-x64     • macOS 14.6.1 23G93
darwin-x64
[  +11 ms] Chrome (web)    • chrome • web-javascript • Google Chrome
130.0.6723.119
[   +1 ms] Checking for wireless devices...
[   +1 ms] [1]: macOS (macos)
[        ] [2]: Chrome (chrome)
[   +3 ms] Please choose one (or "q" to quit)
[        ] : 
[   +9 ms] No wireless devices were found.
[        ] Connected devices:
[   +3 ms] macOS (desktop) • macos  • darwin-x64     • macOS 14.6.1 23G93
darwin-x64
[        ] Chrome (web)    • chrome • web-javascript • Google Chrome
130.0.6723.119
[        ] [1]: macOS (macos)
[        ] [2]: Chrome (chrome)
[        ] Please choose one (or "q" to quit):

**Comment by danagbemava-nc** [comment]
Hi @hyplegfabricvot, please run flutter run until the application starts or you hit the error and share the logs. The logs you shared above stop at your selection of the platform/ target device
