### ISSUE TITLE
Flutter not running on Microsoft Android Emulator

### ISSUE THREAD

**Issue by solomon-okolie** [flutter/flutter#15908]
## Steps to Reproduce

Tried running a new flutter app on Microsoft Android Emulator

1. flutter create hello_world
2. flutter doctor -v
3. flutter run -v

Outcome:
Application flashes on the emulator. 
Opening it manually on the emulator displays white background

## Logs
[flutter_run_v.txt](https://github.com/flutter/flutter/files/1844567/flutter_run_v.txt)
[opening_application_in_emulator.txt](https://github.com/flutter/flutter/files/1844569/opening_application_in_emulator.txt)
[flutter_analyze.txt](https://github.com/flutter/flutter/files/1844575/flutter_analyze.txt)

## Flutter Doctor
[√] Flutter (Channel dev, v0.2.2, on Microsoft Windows [Version 10.0.15063], locale en-GB)
    • Flutter version 0.2.2 at C:\Flutter\flutter
    • Framework revision b9bd51cc36 (11 days ago), 2018-03-13 12:42:29 -0700
    • Engine revision e44cd55fc4
    • Dart version 2.0.0-dev.35.flutter-290c576264

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\AndroidSetup\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\AndroidSetup\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.4
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] VS Code, 64-bit edition (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] Connected devices (1 available)
    • 5 2 inch Marshmallow 6 0 0 XXHDPI Phone • 169.254.76.233:5555 • android-x86 • Android 6.0 (API 23)

• No issues found!

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by klinki** [comment]
I have the same issue

**Comment by cyrsis** [comment]
Genymotion seems better in this case

**Comment by solomon-okolie** [comment]
also if this helps i recall the first time i installed flutter it worked on Microsoft Android Emulator. this was sometime in January.

**Comment by timsneath** [comment]
Looks like Microsoft has abandoned work on their Android emulator. See here: https://github.com/MicrosoftDocs/visualstudio-docs/issues/748 and [this statement posted by Microsoft](https://stackoverflow.com/questions/44864647/running-api-level-24-on-vs-emulator-for-android-hyper-v).

**Comment by klinki** [comment]
@timsneath But it is still the only emulator which works with hyper-v :(

**Comment by klinki** [comment]
@timsneath Hi, are there any updates since Build 2018 official Android Emulator with Hyper-V support announcement?

I'm trying to get it working, but I'm having hard times to do it with flutter.

**Comment by MitchDresdner** [comment]
Just installed latest VS Android Emulator and created a KitKat 4VS Emulator I can see the VM instance running:

**flutter emulators**

Starting the emulator instance give the following error:

**flutter emulators --launch Pixel_2_API_28**
_emulator: ERROR: x86 emulation currently requires hardware acceleration!_

I don't see an option in hyperv to enable acceleration. Is there a way to short circuit HW accel using the -_-enable-software-rendering_ switch? It doesn't seem to work with the emulators launch commands.

Any other thoughts would be helpful, am trapped like the others with Hyperv/Docker.

**Comment by samcarton** [comment]
I have just tried with the latest Android Emulator (27.3.10) with Hyper-V and Windows Hypervisor Platform enabled, and debugging a Flutter app on the emulator works. Performance is not as smooth as HAXM however.
