### ISSUE TITLE
[shared_preferences] Wish for nullable preferences.

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#159073]
I often see that being able to "reset" a preference value to `null` would have been very convenient. Is that possible, or may it be possible in near future ?

**Comment by huycozy** [comment]
Can you elaborate on the use case of this? In which case do you want to set or reset value to null?

**Comment by RoarGronmo** [comment]
Typical, threestate checkboxes, where null is undetermined. Real world
example: a setting which is mandatory may be determined out of location
(sweden, norway or denmark (value is null)), but you may override it (true
or false).

tir. 19. nov. 2024, 06:08 skrev Huy ***@***.***>:

**Comment by stuartmorgan** [comment]
> I often see that being able to "reset" a preference value to `null` would have been very convenient.

Could you elaborate on how what you are requesting is different from the `remove` method that already exists?
