### ISSUE TITLE
cloud_firestore update from 0.3.0 to 0.3.1 error

### ISSUE THREAD

**Issue by Galahand** [flutter/flutter#15906]
## Steps to Reproduce

I was using firestore 0.3.0 plugin but i updated to 0.3.1 to be able to save and request timestamp, before updating i had no problems but now i can´t compile.

## Logs

when i compile i get the following errors:
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:557: error: cannot inherit from final StandardMessageCodec
final class FirestoreMessageCodec extends StandardMessageCodec {
                                          ^
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:67: error: constructor StandardMethodCodec in class StandardMethodCodec cannot be applied to given types;
            new StandardMethodCodec(FirestoreMessageCodec.INSTANCE));
            ^
  required: no arguments
  found: FirestoreMessageCodec
  reason: actual and formal argument lists differ in length
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:557: error: StandardMessageCodec() has private access in StandardMessageCodec
final class FirestoreMessageCodec extends StandardMessageCodec {
      ^
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:564: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:568: error: cannot find symbol
      writeLong(stream, ((Date) value).getTime());
      ^
  symbol:   method writeLong(ByteArrayOutputStream,long)
  location: class FirestoreMessageCodec
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:571: error: cannot find symbol
      writeAlignment(stream, 8);
      ^
  symbol:   method writeAlignment(ByteArrayOutputStream,int)
  location: class FirestoreMessageCodec
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:572: error: cannot find symbol
      writeDouble(stream, ((GeoPoint) value).getLatitude());
      ^
  symbol:   method writeDouble(ByteArrayOutputStream,double)
  location: class FirestoreMessageCodec
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:573: error: cannot find symbol
      writeDouble(stream, ((GeoPoint) value).getLongitude());
      ^
  symbol:   method writeDouble(ByteArrayOutputStream,double)
  location: class FirestoreMessageCodec
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:576: error: cannot find symbol
      writeBytes(stream, ((DocumentReference) value).getPath().getBytes(UTF8));
      ^
  symbol:   method writeBytes(ByteArrayOutputStream,byte[])
  location: class FirestoreMessageCodec
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:578: error: writeValue(ByteArrayOutputStream,Object) is not public in StandardMessageCodec; cannot be accessed from outside package
      super.writeValue(stream, value);
           ^
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:582: error: method does not override or implement a method from a supertype
  @Override
  ^
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:588: error: cannot find symbol
        readAlignment(buffer, 8);
        ^
  symbol:   method readAlignment(ByteBuffer,int)
  location: class FirestoreMessageCodec
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:591: error: cannot find symbol
        final byte[] bytes = readBytes(buffer);
                             ^
  symbol:   method readBytes(ByteBuffer)
  location: class FirestoreMessageCodec
C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java:595: error: cannot find symbol
        return super.readValueOfType(type, buffer);
                    ^
  symbol: method readValueOfType(byte,ByteBuffer)
Note: C:\Users\David Moreno\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.3.2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
14 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cloud_firestore:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Finished with error: Gradle build failed: 1

## Flutter Doctor

"C:\Users\David Moreno\flutter\bin\flutter.bat" --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
[√] Android Studio (version 3.0)
[!] VS Code (version 1.17.0)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by Diizzayy** [comment]
your using the flutter beta channel,
run `flutter channel master` in the terminal, it will be fixed after that

**Comment by dexcell** [comment]
Thanks @Diizzayy after change the channel i was able to compile

**Comment by parth181195** [comment]
@Diizzayy any particular reason for this issue on beta channel

**Comment by ryanmt** [comment]
I had to remove an upgraded support services dependency in my gradle dependencies for this to work for me.

**Comment by zoechi** [comment]
Sorry for the late reply.
Is this still an issue with recent Flutter versions?

**Comment by Galahand** [comment]
right now i'm using channel beta v0.4.4 with cloud_firestore 0.7.3 with no issues

**Comment by zoechi** [comment]
@Galahand Thanks for the update! I'm going to close the issue.
Feel free to create a new one if you think something needs to be fixed.

**Comment by rajeshjeshar** [comment]
@zoechi 
Flutter 0.5.7 • channel dev 
cloud_firestore: ^0.7.4
Still I'm having this Issue, in debugging Console but the app works fine,Any Fixes??

**Comment by zoechi** [comment]
@rajeshjeshar please create a new issue with fully filled issue template.
