### ISSUE TITLE
Widget Focus Order

### ISSUE THREAD

**Issue by r2d2Proton** [flutter/flutter#159098]
### Steps to reproduce

Please run attached main.dart on Windows desktop.
Press down-arrow until you get to the last control.
Press the up-arrow.

### Expected results

The widget above to have focus.

### Actual results

Focus jumped to the first widget. I am following along with this document:
https://docs.flutter.dev/ui/interactivity/focus

And just learning the finer details of the widget focus manager. And my setup could be wrong.

TAB and SHIFT-TAB work as expected.

Down-arrow does too in the sense the focus changes to the control below the currently focused widget.
Up-arrow jumps to the top.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());


class MyApp extends StatelessWidget {

  static const String _title = 'Focus Sample';

  const MyApp({super.key});


  @override
  Widget build(BuildContext context) {
    return MaterialApp
    (
      title: _title,
      home: Scaffold
      (
        appBar: AppBar(title: const Text(_title)),
        body: Column
        (
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>
          [
            MyCustomWidget(key: UniqueKey(), isAutofocus: true),
            Divider(height: 3),
            OrderedButtonRow(key: UniqueKey()),
            Divider(height: 3),
            MyCustomWidget(key: UniqueKey(), isAutofocus: false),
          ],
        ),
      ),
    );
  }
}


// ignore: must_be_immutable
class MyCustomWidget extends StatefulWidget {

  late bool isAutofocus;
  
  MyCustomWidget({required Key key, required this.isAutofocus}) : super(key: key);

  @override
  State<MyCustomWidget> createState() => _MyCustomWidgetState();
}


class _MyCustomWidgetState extends State<MyCustomWidget> {

  late bool isAutofocus;
  Color _color = Colors.white;
  String _label = 'Unfocused';


  @override
  void initState() {
    super.initState();
    isAutofocus = widget.isAutofocus;
  }


  @override
  Widget build(BuildContext context) {
    return Focus
    (
      autofocus: isAutofocus,
      onFocusChange: (focused) {
        setState(() {
          _color = focused ? Colors.black26 : Colors.white;
          _label = focused ? 'Focused' : 'Unfocused';
        });
      },
      child: Center
      (
        child: Container
        (
          width: 300,
          height: 50,
          alignment: Alignment.center,
          color: _color,
          child: Text(_label),
        ),
      ),
    );
  }
}


// ignore: must_be_immutable
class OrderedButtonRow extends StatelessWidget {

  OrderedButtonRow({required Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FocusTraversalGroup(
      policy: OrderedTraversalPolicy(),
      child: Row(
        children: <Widget>[
          const Spacer(),
          FocusTraversalOrder(
            order: const NumericFocusOrder(2),
            child: TextButton(
              child: const Text('ONE'),
              onPressed: () {},
            ),
          ),
          const Spacer(),
          FocusTraversalOrder(
            order: const NumericFocusOrder(1),
            child: TextButton(
              child: const Text('TWO'),
              onPressed: () {},
            ),
          ),
          const Spacer(),
          FocusTraversalOrder(
            order: const NumericFocusOrder(3),
            child: TextButton(
              child: const Text('THREE'),
              onPressed: () {},
            ),
          ),
          const Spacer(),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![focustests-01](https://github.com/user-attachments/assets/f608a38c-088e-4371-b253-7d70bfa7d69a)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@r2d2Proton 
Can you take a look at [this](https://api.flutter.dev/flutter/widgets/FocusTraversalGroup-class.html#widgets.FocusTraversalGroup.1) official focus traversal example to check if it helps in your case ? With it, I was able to traverse properly using up and down arrow keys. See if any code implementation is missing at your end.

**Comment by r2d2Proton** [comment]
Thank you @darshankawar :) I will definitely review that, and all of the focus specific documentation I can find. It does take time for me to read the documentation, and rework the examples to a point where I am personalizing them for my use. I will report back here once I am done. Thank you again.

**Comment by r2d2Proton** [comment]
The code posted above is using the FocusTraversalGroup class too. In fact the group is wrapped by two Focus widgets, one at the top, and the other at the bottom. Also, how do I make the NumericFocusOrder(1) show the focus?

**Comment by darshankawar** [comment]
I will try to look into the implementation a bit later, but meantime, check https://api.flutter.dev/flutter/widgets/FocusScope-class.html to see if it helps. 
Also, would be good to raise your question in support channels like StackOverflow.

**Comment by r2d2Proton** [comment]
@darshankawar thank you again for your help : )

**Comment by darshankawar** [comment]
Has this been resolved ? I didn't get much time to look into this.
