### ISSUE TITLE
[flutter_web] `--web-header` flag does not work for `flutter drive`

### ISSUE THREAD

**Issue by dtscalac** [flutter/flutter#159037]
### Steps to reproduce

1. Call `flutter drive --help --verbose` to see docs on how to use the `--web-header` flag:

```
   --web-header=<X-Custom-Header=header-value>              Additional key-value pairs that will added by the web server as headers to all responses. Multiple
                                                             headers can be passed by repeating "--web-header" multiple times.
```

2. Clone flutter repository, navigate to [/dev/integration_tests/web_e2e_tests](https://github.com/flutter/flutter/tree/master/dev/integration_tests/web_e2e_tests), run the test with a `--web-header` flag with `--no-headless` so that the browser window appears:
```
chromedriver --port=4444 

flutter drive --target=test_driver/text_editing_integration.dart \
  -d web-server \
  --browser-name=chrome \
  --profile \
  --web-renderer=html \
  --web-header="test-header=test-value" \ 
  --no-headless
```

3. Inspect the headers the index.html and other files are served with.

### Expected results

`test-header` with `test-value` appears as HTTP header for each file served by the server.

![Screenshot 2024-11-16 at 22 13 43](https://github.com/user-attachments/assets/01e73b0c-b8a6-438d-b4c4-7b6e1e0f89a5)

### Actual results

The server doesn't add the HTTP header. The `--web-header` flag has no effect.

![Screenshot 2024-11-16 at 22 21 36](https://github.com/user-attachments/assets/f076b668-95f5-4f48-80ed-cccec5febceb)

### Code sample

<details open><summary>Code sample</summary>

No code sample since the issue is reproducible on examples from the flutter repository. Refer to **Steps to reproduce** for details.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.27.0-1.0.pre.530, on macOS 15.1 24B83 darwin-arm64, locale en-PL)
    ! Flutter version 3.27.0-1.0.pre.530 on channel [user-branch] at /Users/shemhazai/Projects/GitHub/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.95.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Reproduced the issue using my [simple setup](https://gist.github.com/huycozy/36914852af216f29ae230bc8b9387f91) with a minor update as below sample (add delay inside test). I can't observe header value using the sample code as reported since the test runs too fast (not sure how you observe it). 

<details>
<summary>Sample test</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:repro_issues/main_counter.dart';

void main () {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group("end-to-end test", () {
    testWidgets("tap on the floating action button, verify counter", (tester) async {
      
      await Future.delayed(Duration(seconds: 5));

      await tester.pumpWidget(const MyApp());
      // Verify the counter starts at 0.
      expect(find.text('0'), findsOneWidget);

      await tester.tap(find.byIcon(Icons.add));

      // Trigger a frame.
      await tester.pumpAndSettle();

      // Verify the counter increments by 1.
      expect(find.text('1'), findsOneWidget);

      await Future.delayed(Duration(seconds: 5));

    });
  });
}
```
</details>

<details>
<summary>Flutter versions (stable and master)</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-x64, locale en-VN)
    • Flutter version 3.24.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (32 hours ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
```

```console
[!] Flutter (Channel master, 3.27.0-1.0.pre.511, on macOS 15.1 24B83 darwin-x64, locale en-VN)
    • Flutter version 3.27.0-1.0.pre.511 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eaa99f28b1 (2 hours ago), 2024-11-14 17:38:26 -0800
    • Engine revision 619804c0fb
    • Dart version 3.7.0 (build 3.7.0-140.0.dev)
    • DevTools version 2.41.0-dev.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```
</details>

**Comment by dtscalac** [comment]
> Reproduced the issue using my [simple setup](https://gist.github.com/huycozy/36914852af216f29ae230bc8b9387f91) with a minor update as below sample (add delay inside test). I can't observe header value using the sample code as reported since the test runs too fast (not sure how you observe it).
> Sample test
> 
> Flutter versions (stable and master)

The default behavior of `flutter drive` is to close the browser after the test finishes so either you configure it to keep the browser window open after the test finishes or you add delay in your tests (like you did in your sample) to keep the test running. Sorry, should have written that.

**Comment by ditman** [comment]
@dtscalac what headers are you trying to pass? If you're trying to test with COOP/COEP for Wasm you could use `--wasm`.

**Comment by dtscalac** [comment]
> @dtscalac what headers are you trying to pass? If you're trying to test with COOP/COEP for Wasm you could use `--wasm`.

@ditman COOP/COEP headers.

A little more background: I'm working on a flutter web application that uses [flutter_rust_bridge](https://github.com/fzyzcjy/flutter_rust_bridge), the package uses [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) thus COOP/COEP headers are required.

Except from using `flutter_rust_bridge` the app I'm working on imports many other packages that are not supporting wasm compilation yet therefore compiling the app to `wasm` is not an option.

**Comment by ditman** [comment]
OK, so you're attempting to serve a Flutter JS app with COOP/COEP through `flutter drive`, if I understood correctly?

This probably should work, I wonder what's up with the `flutter driver` command. I'm going to assign a priority to this, we need to look at it (I might be looking at the `flutter_tool` next week, so if I do, I'll take a look "while I'm there)

Thanks for reporting!

**Comment by dtscalac** [comment]
> OK, so you're attempting to serve a Flutter JS app with COOP/COEP through `flutter drive`, if I understood correctly?
Yes, correct.

Please have a look at #159039 PR, I've done initial investigation and provided a fix to address this problem.
