### ISSUE TITLE
[google_maps_flutter] Should add data-driven styling

### ISSUE THREAD

**Issue by dkhawk** [flutter/flutter#159092]
### Use case

This is a pure maps functionality that is absent.

### Proposal

Flutter is missing data driven styling support.

https://mapsplatform.google.com/resources/blog/introducing-data-driven-styling/

https://developers.google.com/maps/documentation/android-sdk/dds-datasets/overview?hl=en

Thanks

**Comment by stuartmorgan** [comment]
@dkhawk What does implementing this require from the plugin? Looking at the links you provided, this appears to be a server-side map style feature, not a client API.
