### ISSUE TITLE
Screen Flickering Issue on iOS Flutter Apps

### ISSUE THREAD

**Issue by ArataAI** [flutter/flutter#159061]
Hi Flutter team,

I’ve encountered an intermittent issue on iOS devices while using Flutter. The problem involves the screen flickering unexpectedly when the app UI is idle. The flickering stops as soon as the user interacts with the screen, such as tapping anywhere.

Interestingly, this issue isn’t limited to my app. I’ve also observed the same behavior in an open-source Flutter app called [LocalSend](https://github.com/localsend/localsend), indicating it might be a broader issue with Flutter on iOS rather than app-specific implementation.

Here are the details:

Platform: iOS (iPhone)

Issue: Random screen flickering when the UI is idle.

Behavior:
The flickering doesn’t happen consistently but appears sporadically under certain conditions.
Tapping or interacting with the screen immediately resolves the flicker.

Reproducibility: I haven’t identified a guaranteed way to reproduce this issue, but it occurs randomly during normal use.
This issue impacts user experience and might affect other apps as well. I’d appreciate it if the team could look into this.

https://github.com/user-attachments/assets/40ea7ffd-fa1d-4b56-9f9f-e823009bca4f

**Comment by MurtadhaS** [comment]
seems like there is a widget with a rectangle on top.

**Comment by huycozy** [comment]
@ArataAI For the issue to be workable, you should narrow your code down into a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), please check [provide reduced test cases](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#provide-reduced-test-cases).

**Comment by ArataAI** [comment]
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/seiya/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/seiya/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • My iPhone (mobile)        • 00008101-001C1xxxxx80001E • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by ArataAI** [comment]
Thank you for your response. I appreciate the guidance on narrowing down the issue to a minimal reproducible code sample. However, I’d like to share some additional context that makes this particular problem challenging to isolate.

The issue involves intermittent screen flickering on iOS devices when the UI is idle, which resolves immediately upon user interaction (e.g., tapping the screen). This behavior isn’t specific to my app; I’ve observed the same issue in another open-source Flutter app called LocalSend, which uses a completely different UI architecture. This leads me to believe the problem might stem from the Flutter framework or the iOS engine, rather than app-specific implementation.

Here’s the current situation:

Devices tested: iPhone 12 and iPhone 14
iOS version: 18.0.1
Reproducibility: The issue occurs sporadically and doesn’t follow a predictable pattern, making it difficult to isolate a minimal code sample. It sometimes appears during normal use without any consistent trigger.
Given the random nature of the problem and its occurrence in unrelated apps, it is unclear how to create a simplified test case that reliably reproduces the issue. However, since this affects multiple applications, I suspect it could be related to Flutter’s iOS rendering pipeline or lifecycle management.

**Comment by danagbemava-nc** [comment]
Hi @ArataAI, are you using `impeller` or `skia` as your rendering engine in your iOS app?

In your app, do you have some animations playing when you experience this? Either an animated widget or a gif or something similar. 

There was a similar issue a while back which as fixed. See https://github.com/flutter/flutter/issues/100522#issuecomment-1096731639

**Comment by ArataAI** [comment]
I haven’t specifically configured the rendering engine for iOS, so I believe the app is using the default Impeller engine. While some pages in my app do include animations (such as animated widgets), the issue also occurs on pages without any animations.

The flickering seems to happen at the UI’s lowest layer in certain cases, while the upper-layer widgets remain unaffected.

**Comment by danagbemava-nc** [comment]
Hi @ArataAI, could you upgrade to the latest stable version (3.24.5) to see if you still experience this issue? 

Also, is this happening across your entire application or only on specific screens within your app?

**Comment by danagbemava-nc** [comment]
Labeling this for further investigation and insight

**Comment by ArataAI** [comment]
The issue seems to occur randomly, and I haven’t found a way to reproduce it consistently. Based on my observations, it often happens under the following conditions:

After opening the app, switching it to the background, using other apps for a while, and then bringing it back to the foreground. If you don’t interact with the screen, the flickering sometimes starts.
Leaving the app idle for a few seconds after opening it without any screen interactions. There’s a chance the screen will start flickering, though this doesn’t happen every time.
Unfortunately, because the issue isn’t reliably reproducible, it’s challenging to create a minimal reproduction. However, I’ve noticed that this flickering issue also occurs in the open-source app “LocalSend.” Perhaps you can investigate their codebase to look into this further.

[https://github.com/localsend/localsend](url)

**Comment by ArataAI** [comment]
I did some further testing with the open-source app "LocalSend" and managed to reproduce the flickering issue once. The steps were:

Open the LocalSend app.
Switch it to the background.
Use another app for a while, then switch back to LocalSend.
Without interacting with the screen, let it idle for a few seconds.
In this case, the flickering started. However, I wasn’t able to consistently reproduce the issue using the same steps afterward. It seems there are additional unknown factors contributing to the problem, and I’m not sure what specific conditions trigger it reliably.

I hope this information helps narrow down the investigation. 

https://github.com/user-attachments/assets/625a392c-0216-41cc-8988-9f73a1c10914

**Comment by ArataAI** [comment]
Thanks for your suggestion. My app is already using the latest stable version of Flutter, but the issue still persists. I haven’t tried the beta or master channels yet, as I’ve been sticking to the stable release.

**Comment by ArataAI** [comment]
Additionally, I’ve noticed that the issue is more likely to occur on an iPhone 12 compared to an iPhone 16, where it happens much less frequently. I’m not sure if this might be related to differences in memory size or other hardware factors.

**Comment by ArataAI** [comment]
I also wanted to share additional observations. I’ve tested this on iOS 18.1.1, and while the issue is difficult to reproduce consistently, it does occur unexpectedly at times. Based on what I’ve seen so far, the flickering only happens when the screen is idle. It doesn’t occur during UI interactions, like tapping buttons or navigating. For example, if I navigate to a page using the bottom navigation bar and then leave the screen idle for a few seconds without any interaction, the flickering might start.

**Comment by sunguard** [comment]
I am experiencing the same issue on iOS 18.1.1. As @ArataAI mentioned, it seems to occur more frequently on the iPhone 12 compared to other devices. Notably, I haven’t encountered this problem on the iOS simulator; it only appears on physical devices.

**Comment by ArataAI** [comment]
Yes, I’ve had the same experience. This issue doesn’t occur on the iOS simulator; it only happens on physical devices. The chances of it happening are low, and unfortunately, I haven’t found a reliable way to reproduce it consistently either.

**Comment by jonahwilliams** [comment]
We'll need you to test on the beta to see if this still reproduces, otherwise the current stable is very old.

**Comment by eddyuan** [comment]
Just came by the same issue recently, I believe it’s in the newer versions of flutter or maybe iOS since we have used flutter for 3 years and this only happened in recent 2 months. It is indeed very hard to reproduce with low probability about once every 8hrs of app usage, only on real device. Behavior is identical to the op’s, a rectangle part of the screen is not flashing while the rest are. It could happen randomly in any page regardless which widget are used as far as I can tell. And when user interacted (ui repainted) the flash went away. We use extended image and provider package, but other than those our app is pretty much “original” flutter.
