### ISSUE TITLE
Keyboard on Safari mobile causes flexible container to intermittently collapse

### ISSUE THREAD

**Issue by koskotheim** [flutter/flutter#159180]
### Steps to reproduce

Minimum reproducible example app: https://safari-keyboard-example.web.app/

 Visit the app on safari on an iphone and open the keyboard. Sometimes it works correctly the first time but fails the 2nd time you open the keyboard. 

### Expected results

The flexible container above the text input does not collapse

### Actual results

The flexible container above the text input often collapses

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Safari Keyboard Issue Example',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          _buildFlexibleElement(),
          _buildTextInput(),
        ],
      ),
    );
  }

  Widget _buildFlexibleElement() {
    return Flexible(
      fit: FlexFit.tight,
      child: Container(
        height: 200,
        color: Colors.blue.shade300,
        alignment: Alignment.center,
        child: const Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text("Flexible Container"),
          ],
        ),
      ),
    );
  }

  Widget _buildTextInput() {
    return Container(
      padding: const EdgeInsets.all(8),
      color: Colors.green.shade200,
      height: 100,
      alignment: Alignment.center,
      child: const TextField(
        decoration: InputDecoration(
          hintText: 'Default Text Field',
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/55a41973-6c59-47d7-9359-e9379be53203

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.5 23F79 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] VS Code (version 1.95.3)
[✓] Connected device (3 available)
[✓] Network resources```

</details>

**Comment by arslanraza7** [comment]
Hi @koskotheim,

I noticed the flexible container above the text input often collapses when interacting with the keyboard on Safari for iPhone. To potentially fix this, you might try wrapping the Flexible widget in a SingleChildScrollView or use a LayoutBuilder to ensure it handles size changes more effectively. Safari's rendering of the keyboard often causes unexpected layout shifts, especially with nested Flexible widgets.

Another approach might be to ensure that the TextField has enough space when the keyboard opens by adjusting the layout to accommodate the keyboard frame.

It would also be useful to verify the behavior using a FocusNode on the TextField to manage and control focus, which could help prevent unexpected collapses.

**Comment by huycozy** [comment]
This is a known issue being tracked at https://github.com/flutter/flutter/issues/124205. Closing this issue as a duplicate, so please follow up on it for further updates.
