### ISSUE TITLE
The engine roller seems to fancy closing engine rolls that have completed their tasks and are waiting on the merge queue

### ISSUE THREAD

**Issue by flar** [flutter/flutter#159139]
The engine team is aware of the issue, tracking it, and trying to come up with a solution.

**Comment by flar** [comment]
One potential cause that seems to match what we see in the roller bot code is that the bot is missing a case for "and if the PR is in the merge queue state then leave it be". It already does that for a number of conditions, but there is no test for being on the merge queue.

It may be that the API used to query the PR states doesn't support querying information about the merge queue which might mean that the bot will need to start using a new API to detect these states.

**Comment by yjbanov** [comment]
https://github.com/flutter/cocoon/pull/4041 did fix it. Closing.
