### ISSUE TITLE
Default .gitignore from `flutter create` should ignore more files

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#15910]
The `.gitignore` file created by the `flutter create` command should be updated to ignore the following files that are created automatically at build time:
```
android/gradlew
android/gradlew.bat
android/gradle/wrapper/gradle-wrapper.jar
```

The [Dart guidelines](https://www.dartlang.org/guides/libraries/private-files) also suggest ignoring the following IntelliJ files:
```
*.iml
*.ipr
*.iws
```

**Comment by zoechi** [comment]
Fixed in #21192
