### ISSUE TITLE
go_router_builder persist dialogs and bottom sheets on routing to different routes

### ISSUE THREAD

**Issue by YukiAttano** [flutter/flutter#159135]
### Steps to reproduce

Using [go_router_builder](https://pub.dev/packages/go_router_builder) for generating routes introduces the behavior that Dialogs and BottomSheets stay opened on screen, while navigating to different routes

### Expected results

I expect that the Dialogs are closed, if another route is called.

### Actual results

Dialogs persist on Screen

### Code sample

<details open><summary>Code sample</summary>

[Repo](https://github.com/YukiAttano/go_router_bug)

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

With Bug (go_router_builder routes)
https://github.com/user-attachments/assets/d902acd9-c2e4-41d1-b606-0e0d60a86e2c

Without Bug (handcrafted routes)
https://github.com/user-attachments/assets/bffe07c3-4f51-4c5c-a86d-ca8ac071a1c7

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 flutter doctor -v
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.0.1 24A348 darwin-arm64, locale de-DE)
    • Flutter version 3.24.5 on channel stable at /Users/user/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (6 days ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3


[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] Connected device (4 available)
    • iPhone von user (mobile) • 00008110-001229C43413A01E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                       • macos                     • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop)       • mac-designed-for-ipad     • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 130.0.6723.119
    ! Error: Browsing on the local area network for iPhone Small King. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@YukiAttano Thanks for the report and repo. I observed that when we tap on `Go to Home`, it does pop the route but doesn't close the dialog. When we `close` it, we see that we are on first screen. This behavior reminds me of [this](https://github.com/flutter/flutter/issues/146045) open issue that you can check to see if it resembles your case or not.

**Comment by YukiAttano** [comment]
> @YukiAttano Thanks for the report and repo. ...

yes you are right, it seems to be related. I guess my example will help to pin down to root cause.

**Comment by darshankawar** [comment]
@YukiAttano 
I suggest you to follow-up in that issue for better tracking. You may share your findings, code and example so that it will help to be at one place, as, [this](https://github.com/flutter/flutter/issues/146045#issuecomment-2223998690) could be the root-cause per mentioned comment.
 I will close this as a duplicate. If you disagree, write in comments and I'll reopen it.
