### ISSUE TITLE
weather demo initialises globals in initState() 

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1591]
`examples/material_gallery/lib/demo/weathers_demo.dart` initialises _images and _sprites in initState(), but they're global, so it will stomp on them each time. This means we load more than we need to, thus losing the benefit of them being global, and if there's two instances (e.g. in a demo showing this side-by-side) they'll overwrite each other.

**Comment by vlidholt** [comment]
The images are cached, so they will not be loaded more than once. Currently I cannot find a good way to access load/access the images without passing references down the tree, which is somewhat cumbersome. I feel like this is an area where the framework need to support a better solution. Can take some time to outline a proposal for how this could be made much easier if someone isn't working on it already.

**Comment by Hixie** [comment]
I'm not sure what you mean by "they are cached". `initState()` calls `_loadAssets` which calls `_images = new ImageMap()`. This can happen more than once per app lifetime.

**Comment by vlidholt** [comment]
The images in the image map are cached somewhere (not sure where), but they definitely doesn't take time to load the second time.

**Comment by Hixie** [comment]
Sure. This isn't a performance bug, just a correctness one. We shouldn't have globals that are initialised multiple times, that doesn't make sense.

**Comment by abarth** [comment]
Weather demo isn't a thing anymore.
