### ISSUE TITLE
Bad performance on Moto G (2014)

### ISSUE THREAD

**Issue by wooque** [flutter/flutter#15915]
## Steps to Reproduce
Build **flutter_gallery** from examples from **beta** branch with `flutter build apk`.
Install it on Moto G (2014) (Android 7.1.2).
Animations are stuttery, especially in shopping app when entering item and then scrolling through images on the bottom and in section organizer demo when sliding between sections, performance overlay is showing FPS dropping to 8-9 FPS (rasterizer, engine is fine).

**Comment by wooque** [comment]
Checked the master (49c87d010c88d7936254e8fe919ea37638da5343) and it few FPS better but still terrible.

**Comment by zoechi** [comment]
Performance should be tested with release builds `flutter build apk --release`

**Comment by wooque** [comment]
@zoechi 
I checked master with `flutter build apk --release`, but I now went through all combination `master` (77403ba6ec98972da5daa6f50bd5d626db4a5f4a)/beta and  `--release`/`--profile` and in all combinations performance is not great, but especially terrible is those 2 scenarios I mentioned in first comment

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by zoechi** [comment]
Related #11861

**Comment by wooque** [comment]
I can't check, my Moto G broke.

**Comment by liyuqian** [comment]
Between May 2018 and December 2018, we've improved Flutter gallery's average rasterizer time from ~35ms to ~10ms on Moto G4 by improving the clip and retained layer raster cache (https://github.com/flutter/flutter/issues/13736, https://github.com/flutter/flutter/issues/21756). Hence I'm closing this issue unless someone reproduces it again on Flutter's master branch.
