### ISSUE TITLE
Flutter Error: Navigator operation requested with a context that does not include a Navigator

### ISSUE THREAD

**Issue by 1SouravGhosh** [flutter/flutter#15919]
## Steps to Reproduce
I have attached the main and decorationPage, which I have created. Run the AVD --> Launch the app --> Go to Navigator Drawer --> Click on "Decoration". 

Exception: "Another exception was thrown: Navigator operation requested with a context that does not include a Navigator. "
[lib.zip](https://github.com/flutter/flutter/files/1845083/lib.zip)

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)

[√] Connected devices (1 available)

! Doctor found issues in 1 category.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by im-minion** [comment]
suffering the same issue :(

**Comment by burhanrashid52** [comment]
There is some issue with MateriaApp context in the library.The Navigator won't work if you're doing in under MateriaApp context like this
(This wont work)
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text("Title"),
        ),
        body: new Center(child: new Text("Click Me")),
        floatingActionButton: new FloatingActionButton(
          child: new Icon(Icons.add),
          backgroundColor: Colors.orange,
          onPressed: () {
            print("Clicked");
            Navigator.push(
              context,
              new MaterialPageRoute(builder: (context) => new AddTaskScreen()),
            );
          },
        ),
      ),
    );
  }
}
```

Instead, you need to create a new Widget as home in MaterialApp like this
(This will work)
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        home: new HomeScreen());
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Title"),
      ),
      body: new Center(child: new Text("Click Me")),
      floatingActionButton: new FloatingActionButton(
        child: new Icon(Icons.add),
        backgroundColor: Colors.orange,
        onPressed: () {
          print("Clicked");
          Navigator.push(
            context,
            new MaterialPageRoute(builder: (context) => new AddTaskScreen()),
          );
        },
      ),
    );
  }
}
```

**Comment by Jambazishvili** [comment]
Thank you very much @burhanrashid52, I had same issue and your solution works like a charm. In addition I think that the correct solution is more expressive rather than the first one.

**Comment by SG14-96** [comment]
I have a similar issue.
`actions: <Widget>[
              new IconButton(icon: new Icon(Icons.account_circle),
              onPressed: (){
                Navigator.push(context, new MaterialPageRoute(builder: (context) => new AccountScreen()));
              }),
            ],`

**Comment by akashgudadhe1** [comment]
I have similar issue but I solved it by using your trick..
Here is my correct code.

import 'package:flutter/material.dart';

class MyApp extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
       home: new FirstScreen(),
    );
  }
}

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
     return new Scaffold(
        appBar: AppBar(
          title: Text('First Screen'),
        ),
        body: Center(
          child: RaisedButton(
            child: Text('Launch screen'),
            onPressed: () {
              Navigator.push(
                context,
                 MaterialPageRoute(builder: (context) => SecondScreen()),
              );
            },
          ),
        ),
      );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

      return new Scaffold(
        appBar: AppBar(
          title: Text("Second Screen"),
        ),
        body: Center(
          child: RaisedButton(
            onPressed: () {
              Navigator.pop(context);
            },
            child: Text('Go back!'),
          ),
        ),
    );
  }
}

**Comment by 1SouravGhosh** [comment]
This is issue has been resolved. Please refer to the comments above.

**Comment by burhanrashid52** [comment]
On which version its resolved? @1SouravGhosh

**Comment by 1SouravGhosh** [comment]
Yes in my case there was the problem in the code itself. I followed the above comments and fixed it, thus I closed the issue.

**Comment by Aanu1995** [comment]
I was faced with this problem but now it has been solved. Thanks to you

**Comment by haiderkhalil** [comment]
thanks @burhanrashid52 , Solved my problem as well.

**Comment by mdabdullahbaig** [comment]
Thanks for your suggestion. to create a HomePage();

**Comment by danyismail** [comment]
thanks u so much.....

**Comment by HizkiasAbraham** [comment]
Thanks. It solved my  problem.

**Comment by phanirithvij** [comment]
How to do this for statefulwidgets no examples anywhere

**Comment by ilyamolokov** [comment]
Thank you, your solution works with StatelessWidget.
But how to do this for StatefulWidget?
@burhanrashid52

**Comment by jithin-pal** [comment]
i have multiple pages and when i use your fix, i still keep getting the same error.

**Comment by dmitrijkiltau** [comment]
For those who ask: The @burhanrashid52 solution works the same for StatefulWidget.

**Comment by patelkrunal78** [comment]
I set up this simple example for routing in a flutter app:

Find [Here](https://icetutor.com/question/navigator-operation-requested-with-a-context-that-does-not-include-a-navigator)

**Comment by CodePhilanthropist** [comment]
Can you please provide example for StatefilWidgets please

**Comment by dae54** [comment]
was helped by it too... great charm

**Comment by ritheesh4** [comment]
> There is some issue with MateriaApp context in the library.The Navigator won't work if you're doing in under MateriaApp context like this
> (This wont work)
> 
> ```dart
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new MaterialApp(
>       home: new Scaffold(
>         appBar: new AppBar(
>           title: new Text("Title"),
>         ),
>         body: new Center(child: new Text("Click Me")),
>         floatingActionButton: new FloatingActionButton(
>           child: new Icon(Icons.add),
>           backgroundColor: Colors.orange,
>           onPressed: () {
>             print("Clicked");
>             Navigator.push(
>               context,
>               new MaterialPageRoute(builder: (context) => new AddTaskScreen()),
>             );
>           },
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> Instead, you need to create a new Widget as home in MaterialApp like this
> (This will work)
> 
> ```dart
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new MaterialApp(
>         home: new HomeScreen());
>   }
> }
> 
> class HomeScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new Scaffold(
>       appBar: new AppBar(
>         title: new Text("Title"),
>       ),
>       body: new Center(child: new Text("Click Me")),
>       floatingActionButton: new FloatingActionButton(
>         child: new Icon(Icons.add),
>         backgroundColor: Colors.orange,
>         onPressed: () {
>           print("Clicked");
>           Navigator.push(
>             context,
>             new MaterialPageRoute(builder: (context) => new AddTaskScreen()),
>           );
>         },
>       ),
>     );
>   }
> }
> ```

thanks man. you fixed my error.

**Comment by bekagaw653** [comment]
already solved here https://icetutor.com/question/navigator-operation-requested-with-a-context-that-does-not-include-a-navigator/

**Comment by mohammedmoheed** [comment]
> I have similar issue but I solved it by using your trick..
> Here is my correct code.
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> class MyApp extends StatelessWidget
> {
>   @override
>   Widget build(BuildContext context) {
>     return new MaterialApp(
>        home: new FirstScreen(),
>     );
>   }
> }
> 
> class FirstScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>      return new Scaffold(
>         appBar: AppBar(
>           title: Text('First Screen'),
>         ),
>         body: Center(
>           child: RaisedButton(
>             child: Text('Launch screen'),
>             onPressed: () {
>               Navigator.push(
>                 context,
>                  MaterialPageRoute(builder: (context) => SecondScreen()),
>               );
>             },
>           ),
>         ),
>       );
>   }
> }
> 
> class SecondScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
> 
>       return new Scaffold(
>         appBar: AppBar(
>           title: Text("Second Screen"),
>         ),
>         body: Center(
>           child: RaisedButton(
>             onPressed: () {
>               Navigator.pop(context);
>             },
>             child: Text('Go back!'),
>           ),
>         ),
>     );
>   }
> }
> ```

**Comment by yvonmanzi** [comment]
Thanks guys! had the same issue for a few hours, but this thread helped me fix it!

**Comment by vinothvino42** [comment]
I have this issue if I return a widget with `MediaQuery`.

**Not Working**
`
 class MyApp extends StatelessWidget {
       @override
       Widget build(BuildContext context) {
          return MaterialApp(
            title: 'MyApp',
            debugShowCheckedModeBanner: false,
           onGenerateRoute: Router.generateRoutes,
           theme: appTheme(),
           builder: (context, child) => MediaQuery(
             child: HomeBottomNavigationScreen(),
             data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                ),
           );
        }
    }
`

But the same widget without a MediaQuery works fine. 

**Working**

`
return MaterialApp(
      title: 'MyApp',
      debugShowCheckedModeBanner: false,
      onGenerateRoute: Router.generateRoutes,
      theme: appTheme(),
      home: HomeBottomNavigationScreen(),
    );
`

**Comment by tsniveda** [comment]
> There is some issue with MateriaApp context in the library.The Navigator won't work if you're doing in under MateriaApp context like this
> (This wont work)
> 
> ```dart
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new MaterialApp(
>       home: new Scaffold(
>         appBar: new AppBar(
>           title: new Text("Title"),
>         ),
>         body: new Center(child: new Text("Click Me")),
>         floatingActionButton: new FloatingActionButton(
>           child: new Icon(Icons.add),
>           backgroundColor: Colors.orange,
>           onPressed: () {
>             print("Clicked");
>             Navigator.push(
>               context,
>               new MaterialPageRoute(builder: (context) => new AddTaskScreen()),
>             );
>           },
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> Instead, you need to create a new Widget as home in MaterialApp like this
> (This will work)
> 
> ```dart
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new MaterialApp(
>         home: new HomeScreen());
>   }
> }
> 
> class HomeScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new Scaffold(
>       appBar: new AppBar(
>         title: new Text("Title"),
>       ),
>       body: new Center(child: new Text("Click Me")),
>       floatingActionButton: new FloatingActionButton(
>         child: new Icon(Icons.add),
>         backgroundColor: Colors.orange,
>         onPressed: () {
>           print("Clicked");
>           Navigator.push(
>             context,
>             new MaterialPageRoute(builder: (context) => new AddTaskScreen()),
>           );
>         },
>       ),
>     );
>   }
> }
> ```

Thank you! Works seamlessly!
