### ISSUE TITLE
InkWell's enableFeedback cannot be set to null.

### ISSUE THREAD

**Issue by StanleyCocos** [flutter/flutter#159122]
### Steps to reproduce

```dart
InkWell(
    enableFeedback: null,
)
```

### Expected results

enableFeedback == false

### Actual results

enableFeedback == true

### Code sample

<details open><summary>Code sample</summary>

```dart
class InkWell extends InkResponse {
  const InkWell({
    super.key,
    super.child,
    super.onTap,
    super.onDoubleTap,
    super.onLongPress,
    super.onTapDown,
    super.onTapUp,
    super.onTapCancel,
    super.onSecondaryTap,
    super.onSecondaryTapUp,
    super.onSecondaryTapDown,
    super.onSecondaryTapCancel,
    super.onHighlightChanged,
    super.onHover,
    super.mouseCursor,
    super.focusColor,
    super.hoverColor,
    super.highlightColor,
    super.overlayColor,
    super.splashColor,
    super.splashFactory,
    super.radius,
    super.borderRadius,
    super.customBorder,
    bool? enableFeedback = true,
    super.excludeFromSemantics,
    super.focusNode,
    super.canRequestFocus,
    super.onFocusChange,
    super.autofocus,
    super.statesController,
    super.hoverDuration,
  }) : super(
    containedInkWell: true,
    highlightShape: BoxShape.rectangle,
    enableFeedback: enableFeedback ?? true,
  );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.95.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by StanleyCocos** [comment]
Fix request: https://github.com/flutter/flutter/pull/158907

**Comment by StanleyCocos** [comment]
The issue has been resolved via [PR](https://github.com/flutter/flutter/pull/158907); therefore, it is being closed.

**Comment by huycozy** [comment]
@StanleyCocos Next time, you can use [link a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), so that the linked issue will be auto closed when PR is merged.

**Comment by StanleyCocos** [comment]
@huycozy Thank you for your guidance; I understand now.
