### ISSUE TITLE
The CupertinoPicker widget has a display issue on the web.

### ISSUE THREAD

**Issue by quochuyR** [flutter/flutter#159285]
### Steps to reproduce

The steps are similar to the video.

### Expected results

Display similar to the mobile app.

### Actual results

#

### Code sample

https://api.flutter.dev/flutter/cupertino/CupertinoPicker-class.html

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/d56b078a-3a47-4988-8060-9fcefd0bb68f

</details>

### Logs

#

### Flutter Doctor output

#

**Comment by darshankawar** [comment]
@quochuyR 
It works properly on latest master as shown below:


https://github.com/user-attachments/assets/fc54eb29-354d-450c-ad7e-7e8caa95ae1d

I will close this as fixed.
