### ISSUE TITLE
'/' will allways root router even set initialRoute: '/home'

### ISSUE THREAD

**Issue by ahyangnb** [flutter/flutter#159255]
### Steps to reproduce

run the code in flutter 3.24.3

### Expected results

'/home' as root router and can not be pop.

### Actual results

'/home' not root router and it can be pop.

### Code sample

code

```
import 'package:flutter/material.dart';

void main() {
  runApp(const RootRouteError());
}

class RootRouteError extends StatelessWidget {
  const RootRouteError({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/home': (context) => const HomeScreen(),
        '/': (context) => const OtherScreen(),
      },
      initialRoute: '/home',
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('HomeScreen')),
    );
  }
}

class OtherScreen extends StatelessWidget {
  const OtherScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('OtherScreen')),
    );
  }
}
```

### Screenshots or Video

https://github.com/user-attachments/assets/d3d507c5-c306-4c4a-8848-6076d997ca9f

### Flutter Doctor output
```
zengyang@zengyangdeMac-mini ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.0 23A344 darwin-arm64, locale
    en-CN)
    • Flutter version 3.24.3 on channel stable at
      /Users/zengyang/fvm/versions/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/zengyang/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/zengyang/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.93.1)
    • VS Code at /Volumes/Extreme SSD/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (5 available)
    • 苹果11啊 (mobile)                  • 00008030-0019082236E2802E • ios
      • iOS 17.6.1 21G93
    • iPhone 11 Pro Max (mobile)      • 00008030-000224190CE8802E • ios
      • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 131.0.6778.70
    ! Error: Browsing on the local area network for qqqqqqq1iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.
```

**Comment by darshankawar** [comment]
> routes: {
>         '/home': (context) => const HomeScreen(),
>         '/': (context) => const OtherScreen(),
>       },
>       initialRoute: '/home',

@ahyangnb You have this code. What is the expected behavior are you looking for ? There's back button so pressing it is taking you to previous screen (other). So I am not clear with what issue are you reporting ?

**Comment by ahyangnb** [comment]
> > routes: {
> > '/home': (context) => const HomeScreen(),
> > '/': (context) => const OtherScreen(),
> > },
> > initialRoute: '/home',
> 
> @ahyangnb You have this code. What is the expected behavior are you looking for ? There's back button so pressing it is taking you to previous screen (other). So I am not clear with what issue are you reporting ?

it should not have back button in '/home' because this one is root router but the AppBar of '/home' will add the back button automatically, this is not what i expected.

**Comment by ahyangnb** [comment]
> Hi @ahyangnb,
> 
> It looks like the issue here is that the `/home` route, which is expected to be the root, is still showing a back button, allowing it to be popped. This happens because the `/` route (OtherScreen) is implicitly treated as the default root route, even if `/home` is set as the initial route.
> 
> To solve this problem, you can use the `Navigator` to clear the navigation stack and make `/home` the true root without any back navigation. Here's how:
> 
> 1. Set `home` as the initial route:
>    ```dart
>    initialRoute: '/home',
>    ```
> 2. In the `HomeScreen`, replace the `AppBar` with the following code to remove the back button:
>    ```dart
>    appBar: AppBar(
>      title: const Text('HomeScreen'),
>      automaticallyImplyLeading: false, // This removes the back button.
>    ),
>    ```
> 
> This will ensure that `/home` is treated as the root route and cannot be popped.
> 
> Alternatively, you could consider using `Navigator.pushAndRemoveUntil()` or use a `WillPopScope` widget to control the behavior of the back button and ensure the expected navigation behavior.

What a strange operation.

**Comment by ahyangnb** [comment]
it's okay
