### ISSUE TITLE
vscode displaying flutter test exception at correct line

### ISSUE THREAD

**Issue by lewinpauli** [flutter/flutter#159276]
### Use case

When writing tests, finding the line that causes the problem is not very convenient.

![image](https://github.com/user-attachments/assets/2acb427d-fe1d-45a7-8c08-38811f976abe)

The test exception is displayed at the very top of the function, which is more of a distraction than a help, especially in larger test functions.

The debug output does not highlight the causing line either.

Displaying the error message at the correct line and highlighting the line in the debug output text would make testing DX much easier.

**Comment by darshankawar** [comment]
This looks similar to https://github.com/flutter/flutter/issues/79386 so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by lewinpauli** [comment]
the issue #79386  is only about the teardown method, I think this issue is much more general
