### ISSUE TITLE
[Slider]:TickShape bug displays wrong position when changing trackHeight parameter

### ISSUE THREAD

**Issue by SAOKIM99** [flutter/flutter#159249]
### Steps to reproduce

1: Access the Slider example: https://api.flutter.dev/flutter/material/Slider-class.html
2: Edit the example according to the template below
3: Run

### Expected results

TickShape displays correctly, not misaligned with ThumbShape

### Actual results

![Screenshot 2024-11-21 at 13 56 02](https://github.com/user-attachments/assets/bf07b581-219f-437f-8b2a-0dba5c14fc8c)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Slider].

void main() => runApp(const SliderApp());

class SliderApp extends StatelessWidget {
  const SliderApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: SliderExample(),
    );
  }
}

class SliderExample extends StatefulWidget {
  const SliderExample({super.key});

  @override
  State<SliderExample> createState() => _SliderExampleState();
}

class _SliderExampleState extends State<SliderExample> {
  int angleChange = 1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Slider')),
      body: Container(
        width: 400,
        decoration: BoxDecoration(
          color: Colors.grey,
        ),
        child: SliderTheme(
          data: SliderThemeData(
            trackHeight: 20,
          ),
          child: Slider(
            value: angleChange.toDouble(),
            min: 1,
            max: 3,
            divisions: 2,
            thumbColor: Colors.orange,
            activeColor: Colors.grey[600],
            inactiveColor: Colors.grey[200],
            onChanged: (value) {
              setState(() {
                angleChange = value.toInt();
              });
            },
            onChangeEnd: (value) {
            },
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/user-attachments/assets/3e90fc07-dac5-4cd1-8cb8-f568a7e8f7e7

</details>

### Logs

<details open><summary>Logs</summary>

```console
I tested directly on the Web
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
I tested directly on the Web
```

</details>

**Comment by darshankawar** [comment]
@SAOKIM99 
The behavior occurs in stable version on all platforms, but not in latest master as shown below:


https://github.com/user-attachments/assets/92638d28-7e73-454d-a21d-d8ba8ff3da56

As it appears to be fixed in master, I will close this as resolved.

**Comment by darshankawar** [comment]
@SAOKIM99 
As I mentioned in my earlier comment, it persist in latest stable version but not in latest master. So you need to switch to latest master and retry by running below commands.

`flutter channel master`
`flutter upgrade`
