### ISSUE TITLE
SelectionArea selects incorrectly when there is a mix of special text and regular text

### ISSUE THREAD

**Issue by men620** [flutter/flutter#159245]
### Steps to reproduce

Mixing regular TextCpan with WidgetSpan may result in abnormal selection, which may be related to height?

### Expected results

Select text from the mouse position normally

### Actual results

![error](https://github.com/user-attachments/assets/fdeb2be2-f55e-4e10-9ffe-8c446bb9c506)
Start selecting at the arrow position, but the preferred selection is indeed special text

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home:  Scaffold(
        body: Column(
          children: [
              SelectionArea(child:  Text.rich(TextSpan(children: [
                TextSpan(text: "This is a test text \nThis is a test text\n1.",  style: TextStyle( color: Colors.black, fontSize: 25, height: 1.5),),
                WidgetSpan(child: Text.rich(TextSpan(text: "special text", style: TextStyle( color: Colors.red, fontSize: 25, height: 1.5),)),),
                TextSpan(text: "and \nThis is an intermediate text\nIP is 20.0.64.49\n2.",  style: TextStyle( color: Colors.black, fontSize: 25, height: 1.5),),
                WidgetSpan(child: Text.rich(TextSpan(text: "special text special text",  style: TextStyle(color: Colors.red, fontSize: 25, height: 1.5),))),
                TextSpan(text: "\nThis is an end text\n20.0.80.225​​", style: TextStyle(color: Colors.black, fontSize: 25, height: 1.5),),
              ])),
              ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
flutter 3.13.9
dart 3.1.5
```

</details>

**Comment by darshankawar** [comment]
> ```
> flutter 3.13.9
> ```

@men620 This is old version. Please upgrade to latest stable and re-run your scenario to check if you still get same behavior or not.

**Comment by men620** [comment]
I also want to upgrade to the latest version, but my code must be compatible with the Win7 system. The current stable version of Flutter does not support the Win7 system @darshankawar

**Comment by darshankawar** [comment]
That is correct. It maybe specific to win7 system you are using. Please try the same on latest windows system (10 or 11) to check if the behavior persist or not.
