### ISSUE TITLE
IDE / lint highlighting of await Future.delayed(const Duration(seconds: X)); inside flutter tests because its not working

### ISSUE THREAD

**Issue by lewinpauli** [flutter/flutter#159284]
### Use case

"await Future.delayed(const Duration(seconds: 5));" inside the /integration_test folder works as expected (but also causes problems with nested tests).

In the /test directory, the same test loads forever.

This is unexpected behaviour, I know there is some documentation where its written down, but it would be nice to highlight it within the IDE/linter and warn devs not to use Future.delayed() or replace it with load indicators within ui tests.

I know that await Future.delayed(const Duration(seconds: X)); should not be used in production tests, but for debugging it can be useful.

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:debugging_flutter/main.dart';

void main() {
  testWidgets('test', (WidgetTester tester) async {
    await tester.pumpWidget(const MyApp());

    await Future.delayed(const Duration(seconds: 5));

    await tester.tap(find.byIcon(Icons.add));

  });
}
```

**Comment by darshankawar** [comment]
@lewinpauli 
Check https://api.flutter.dev/flutter/flutter_test/TestWidgetsFlutterBinding/delayed.html and https://github.com/flutter/flutter/issues/57754 for reference.

Also, if you are suggesting for IDE / linter, then it would fall under respective github repos.
