### ISSUE TITLE
Flutter could use a Vertical Divider

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#15926]
Currently there is a `Divider` widget and a `ListTiles.divideTiles` which can be used to divide content horizontally.

There isn't anything for dividing lists vertically (unless I've missed something); while this is not as common I'd imagine it still comes up fairly often (see [this stackoverflow](https://stackoverflow.com/questions/49388281/flutter-vertical-divider) question).

It's easy enough to implement on its own, but might be worth including as I'm sure that's not the first person to need it. The only question is whether it should be a separate class, whether it could just be an optional parameter to the existing `Divider` and `ListTiles.divideTiles`, or whether there's some fancy way that could be used to determine automatically if the divider / divideTiles is in a horizontal or vertical list.

If I could get some feedback on which of those options would be preferred I may be able to do a PR at some point 😃.

**Comment by firebird0001** [comment]
cycsis, looks like this approach will only work if the divider is placed between other elements. It will occupy all available area in the row if it is the only element in it.

**Comment by MaskyS** [comment]
Made #20826 for this :D

**Comment by jgillich** [comment]
#22377 has been merged so this can be closed I think.

**Comment by jonahwilliams** [comment]
Thanks @jgillich, fixed via https://github.com/flutter/flutter/pull/22377
