### ISSUE TITLE
iOS "Scribble" feature: assertion error when using SystemContextMenu

### ISSUE THREAD

**Issue by PrimaryFeather** [flutter/flutter#159259]
### Steps to reproduce

1. Compile and run the code sample from below on an iPad. The sample simply displays a TextField that is using a `SystemContextMenu`.
2. Enter some text into the text field.
3. Use the Apple Pencil to select some text or use any other "Scribble" feature.

### Expected results

One would expect this to "just work". 😉

### Actual results

Sooner or later (in my tests, always really quickly) you'll run into the assertion error `Attempted to show while another instance was still visible.` in the _SystemContextMenuController_ (to be exact, [here](https://github.com/flutter/flutter/blob/f7869a47993d49ce640dbd7b719d551a4e00ccf2/packages/flutter/lib/src/services/text_input.dart#L2550)). 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 450),
            child: TextField(
              scribbleEnabled: true,
              contextMenuBuilder: (_, ets) =>
                  SystemContextMenu.editableText(editableTextState: ets),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.24.5 on channel stable at /Users/redge/Shared/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (8 days ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/redge/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.101.20241031

[✓] Connected device (4 available)
    • Daniels iPad Air (mobile)       • 00008112-000108C13E81A01E • ios            • iOS 18.1 22B83
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I currently don't have physical ipad / latest version with scribble feature, so can't verify this, but based on the report, keeping it open and labeling for team's tracking.

**Comment by jmagman** [comment]
cc @hellohuanlin I'm guessing this is engine-side since it's specific to Apple Pencil.

**Comment by justinmc** [comment]
@PrimaryFeather I have a suspicion that this is caused by hot restarting or hot reloading. Can you try to reproduce from a fresh start?

We maintain a static instance of the last system context menu shown [here in SystemContextMenuController](https://github.com/flutter/flutter/blob/5e2a62a602222bf922aee6e6904398a146d77c3c/packages/flutter/lib/src/services/text_input.dart#L2480). This was maybe a sketchy choice... I don't think it will get cleared out on hot reload, or in between tests.

**Comment by PrimaryFeather** [comment]
@justinmc Unfortunately, that's not it - I just tried it out, and the issue pops up even after a fresh start.

However, I could isolate the issue a little further. In my test, I first enter some text (either via keyboard or via Scribble), and then I try to select some text with the stylus (by simply striking it through). When I do that, the context menu quickly closes and opens and again while moving over the first word; that looks weird, but it doesn't cause an exception. When the stylus leaves the first word and moves over the second one, the exception comes up.

I recorded a short video that shows the issue. Of course, you can't see the stylus and the exception, but the latter is the reason why the image is freezing at the end.


https://github.com/user-attachments/assets/b7dbe96e-a448-40af-bb80-b562a673b964

**Comment by justinmc** [comment]
Thank you for the clarification! Ok here's my new hunch: the SystemContextMenu is being closed and opened in a single frame, and the `initState` of the new one is called before the `dispose` of the old one. I think that could be possible. The solution may be just to fix that crazy flickering.

I will try to investigate this when I have an iPad and Apple Pencil around.

**Comment by justinmc** [comment]
I can reproduce this on a physical iPad and Apple Pencil! The selection menu flicker happens with the Flutter-rendered context menu too, not just SystemContextMenu. I suspect that this flicker is a regression caused by https://github.com/flutter/flutter/pull/142463.

**Comment by PrimaryFeather** [comment]
@justinmc Wow, thanks so much for looking into it so swiftly! That pull request seems already like a big improvement. Keep up the great work! 🙌☺️

**Comment by jmagman** [comment]
Thank you, @justinmc!

**Comment by justinmc** [comment]
Thanks @PrimaryFeather! Let me know if you ever see that error again after upgrading.
