### ISSUE TITLE
Flutter Doctor is not working ?!!

### ISSUE THREAD

**Issue by moinsaadati** [flutter/flutter#15929]
## Flutter Doctor

Output is :
`Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    110      0  0:00:01  0:00:01 --:--:--   110
[/home/seyedmoein/flutter/bin/cache/dart-sdk-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/seyedmoein/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/seyedmoein/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/seyedmoein/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.
`

**Comment by cyrsis** [comment]
in Linux?

**Comment by moinsaadati** [comment]
yes.on linux mint18.3

**Comment by zoechi** [comment]
We are sorry for not being able coming back to this earlier.
Is this still an issue?
