### ISSUE TITLE
Firestore chaining multiple orderBy make on snapshot called multiple times with blank documents.

### ISSUE THREAD

**Issue by dexcell** [flutter/flutter#15928]
## Steps to Reproduce

In the example below snapshots called twice, which means it will call `print` twice, with the second time `data.documents` is blank array.
```dart
Firestore.instance
      .collection('talks')
      .orderBy('isPinned', descending: true)
      .orderBy('createdAt', descending: true)
      .snapshots.listen((data){
        print('on snapshot');
        data.documents.forEach((talk){
          print(talk.documentID + ': ' + talk['message']);
        });
    });
```

This will end up being a problem when creating `StreamBuilder` such as below. as it will show up as empty list. I'm using cloud_flutter 0.3.2.

```dart
return new StreamBuilder<QuerySnapshot>(
      stream: Firestore.instance
          .collection('talks')
          .orderBy('isPinned', descending: true)
          .orderBy('createdAt', descending: true)
          .snapshots,

      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (!snapshot.hasData) return const Text('Loading...');
        return new ListView(
          padding: new EdgeInsets.symmetric(vertical: 8.0),
          children: snapshot.data.documents.map((DocumentSnapshot document) {
            return TalkWidget(document);
          }).toList()
        );
      }
    );
```

**Comment by Asoseil** [comment]
same problem, orderby make the stream empty

**Comment by knot123** [comment]
Same here

**Comment by blaneyneil** [comment]
yep.  this works for me:

Stream<QuerySnapshot> _query = 
        Firestore.instance.collection('alerts')
        .where('dismissed', isEqualTo: false)
        //.orderBy('createdAt', descending: true)
        .snapshots();

being used like so:

child: StreamBuilder(
                stream: _query,
                builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {

but the moment i uncomment the orderBy then the list flickers on the screen and then goes blank.  it has nothing to do with DateTime either - it won't order by any field.

**Comment by blaneyneil** [comment]
turns out this is because you need to manually create an index in firestore, as documented here:

https://firebase.google.com/docs/firestore/query-data/index-overview#single-field_indexes

if you're going to orderBy a field that isn't the field in the where clause (or if you don't have a where clause).  in my case, i was using this:

```
.where('userID', isEqualTo: uid)
.where('dismissed', isEqualTo: false)
.orderBy('createdAt', descending: true) 
```

so i had to create an index with those 3 fields, making sure that 'createdAt' was descending.  the problem, as it pertains to cloud_firestore, is that there wasn't an error thrown.  in my streambuilder i had this:

`builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
              
                  if (snapshot.hasError) {
                    print(snapshot.error);
                  }`

and nothing ever printed.

**Comment by blaneyneil** [comment]
i cannot use two orderBy's - it just flickers the results then goes blank.

**Comment by jggerrits** [comment]
Same here!

**Comment by AppleEducate** [comment]
This is happening on a simple query:

``` dart
 .orderBy('index', descending: false)
 .where('active', isEqualTo: true)
```

It flickers in the stream builder with the right results and then returns 0 documents.

**Comment by 5ummit** [comment]
Any fixes?

**Comment by RollyPeres** [comment]
I'm using two orderBy clauses and it only loads the first batch correctly, and nothing after that. This happens with a composite index in place...will it be fixed anytime soon?
content.asap is a boolean field in a map and posted is timestamp.
`ref =>
        ref
          .orderBy('content.asap')
          .orderBy('posted')
          .startAfter(offset)
          .limit(this.batchSize)`

**Comment by shaunc869** [comment]
Any updates here? We're still seeing this issue.

**Comment by hironytic** [comment]
I think that the second callback originates from an error on native Firebase SDK.

On iOS, [the program flow continues even after errors are handled](https://github.com/flutter/plugins/blob/eaa1388b11ac3ee6143ad782e573b9b9e314bc4b/packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m#L419). And maybe the errors are also ignored 😢
On the other hand on Android, [the errors are printed out to the console though they are not sent to Dart after all](https://github.com/flutter/plugins/blob/eaa1388b11ac3ee6143ad782e573b9b9e314bc4b/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java#L230-L231). And second callback doesn't occur.

Although I have no idea how to fix this issue unfortunately, you could see an error message in the console at least when you run the program on Android.

**Comment by DFilipeS** [comment]
I also experiencing this on really simple queries like:

```dart
Firestore.instance
   .collection('wallets')
   .where('userId', isEqualTo: user.uid)
   .orderBy('name')
   .snapshots()
```

It shows the correct documents for a split second and immediately flickers to a blank collection. Right now, the `orderBy` is not working at all.

Any news on this one?

**Comment by collinjackson** [comment]
It seems like there are several things going on on here:

1. Needing to create a composite index in the Firebase console on the fields you would like to order. This isn't really specific to Flutter, it's behavior of the native SDK.
2. Issue with the iOS cloud_firestore plugin where it sends empty snapshots in error cases (as pointed out by @hironytic)

If we fix the second item (see flutter/plugins#1203) is there more work to be done here?

**Comment by collinjackson** [comment]
Marking this as closed since flutter/plugins#1203 landed but feel free to reopen if there's more work to be done

**Comment by martinglan** [comment]
I've added the Indexes but chaining "where" with "orderBy" courses unrealible behavour.
using two devices on the same filter show different results. 

As discribed above only querring for "where" works fine. When only querring for "orderBy" this works finne too. But as soon as we chain both these devices are not in sync.  For different devices I mean, the desktop emulator and my smartphone. 

Flutter 1.2.1

**pubspec.yaml**
`  firebase_core: 0.3.1
  firebase_auth: 0.8.1
  cloud_firestore: 0.9.5
  google_sign_in: ^3.2.4`

`Firestore.instance
          .collection(messageCollection)
          .where(messageHandler.fieldScriptID, isEqualTo: docID)
          .orderBy(fieldCreated, descending: true)
          .snapshots();
`

**Comment by andrescr94** [comment]
Im still having the same issue, empty results set

```
Firestore.instance
   .collection('docs')
   .where('createdAt', isLessThanOrEqualTo: timestamp)
   .orderBy('createdAt', descending: true)
   .snapshots()
```

**Comment by collinjackson** [comment]
@andrescr94 since there's only one orderBy in your query, I think it's not related to the issue above. If you feel there's a functionality problem, could you file a new issue or better yet contribute an PR adding an integration test for the problem? Here's where the tests live.

https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/example/test_driver/cloud_firestore.dart

**Comment by 91priyansh** [comment]
We need to add indexes in order to do composite query..

**Comment by collinjackson** [comment]
@91priyansh yes, that's normal for Firestore.

**Comment by kroikie** [comment]
@dexcell

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/874. Any further collaboration will be done there.

**Comment by chan-dev** [comment]
it's an issue with firebase sdk itself, but stumbled upon here searching a solution for the same problem. I'm also using two `orderBy` queries, it returns the right data then goes blank after that. It basically gets called twice when i inspected it with breakpoints.

**Comment by ljanecek** [comment]
Im sorry, i don't want create new issue, but i was stopped with the similar problem like describe above and the setup of indexing it's not working for me. 
I was try to describe my case here: https://stackoverflow.com/questions/59601772/flutter-ios-firebase-cloud-firestore-the-sync-of-data-doest-work

**Comment by marciorr** [comment]
> This is happening on a simple query:
> 
> ```dart
>  .orderBy('index', descending: false)
>  .where('active', isEqualTo: true)
> ```
> 
> It flickers in the stream builder with the right results and then returns 0 documents.
> 
> The only way I found is to sort the list after the stream builder returns a snapshot and remove the `.orderBy` from the query:
> 
> ```dart
> final songs = snapshot.data.documents;
> songs.sort((a, b) {
>     return a['index'].compareTo(b['index']);
> });
> ```

Best solution yet!!!!

**Comment by 8ctopotamus** [comment]
Creating a composite index in the Firebase console and using `orderBy` worked for me.

**Comment by healer2030** [comment]
It seems the issue with snapshot being empty has been fixed, however when you chain `.orderBy()` and `.where()` in a stream, the StreamBuilder breaks.
Widgets correctly build based on the snapshot, however when the document is updated on Firestore, StreamBuilder does not rebuild to show the change.

**Comment by Limitless-Kode** [comment]
You would have to go to your firestore console and index the fields you are ordering by.

**Comment by Limitless-Kode** [comment]
> It seems the issue with snapshot being empty has been fixed, however when you chain `.orderBy()` and `.where()` in a stream, the StreamBuilder breaks.
> Widgets correctly build based on the snapshot, however when the document is updated on Firestore, StreamBuilder does not rebuild to show the change.

You would have to go to your firestore console and index the fields you are ordering by. That should work perfectly.

**Comment by obaidey** [comment]
Add a limit to the stream will do the job after a refresh method wi a timer could be a solution for now

**Comment by grantespo** [comment]
just add a `.limit(int)` to your StreamBuilder<QuerySnapshot>.

Not even sure why this was required for it to work.
