### ISSUE TITLE
[flutter_svg]: iphone unwanted padding on top/bottom in landscape caused by SafeArea

### ISSUE THREAD

**Issue by maknon** [flutter/flutter#159329]
### Steps to reproduce

run the sample code

### Expected results

the image border is at the top with no padding

### Actual results

there is extra unwanted padding on top and bottom caused by SafeArea

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
            body: Container(
              alignment: Alignment.center,
              padding: EdgeInsets.zero,
              child: SingleChildScrollView(
                  child: Container(
                      decoration: BoxDecoration(
                          border: Border.all(color: Colors.red)
                      ),
                      child: SvgPicture.network(
                        width: MediaQuery
                            .of(context)
                            .size
                            .width,
                        'https://haq.app/assets/hafs/3.svg',
                      )
                  )
              ),
            )
        ),
      ),
    );
  }
}
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-22 at 18 39 18](https://github.com/user-attachments/assets/2f403bed-80a5-4006-8e76-7ad246935e30)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.27.0-0.1.pre, on macOS 14.3 23D56 darwin-x64, locale en)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] Connected device (1 available)
    ! Error: Browsing on the local area network for Mariam’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Mariam’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 3 categories.

```

</details>

**Comment by darshankawar** [comment]
@maknon 
See if [this](https://github.com/flutter/flutter/issues/69877) issue resembles your case or not.

**Comment by maknon** [comment]
> @maknon See if [this](https://github.com/flutter/flutter/issues/69877) issue resembles your case or not.

not really sure since applying top/bottom to false in SafeArea didn't resolve the issue like the other case.

**Comment by darshankawar** [comment]
@maknon 
Does this occur without using flutter_svg ? with just image.network ?

**Comment by maknon** [comment]
thank you for the hint, using just image.network seems fine without these extra padding. Even no need for top/bottom adjustment

```
Image.network(
   fit: BoxFit.fitWidth,
   width: MediaQuery.of(context).size.width,
   'https://maknoon.com/download/quran/hafs/3.png',
)
```
![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-26 at 09 56 06](https://github.com/user-attachments/assets/fc048d3c-7d9a-4d4e-9d89-274a808c91cc)


so i think the issue might be with the behavior of flutter_svg  under SafeArea

**Comment by darshankawar** [comment]
@maknon 
It doesn't seem to be specific to flutter_svg, as, with image.network as well running on iphone simulator, it gives me same behavior:

<img width="358" alt="Screenshot 2024-11-27 at 10 55 10 AM" src="https://github.com/user-attachments/assets/c5163aa1-9875-4182-8b4c-0c95b9b0dab5">

This only seems to be specific to iOS, as on Android, the svg is rendered properly:

<img width="326" alt="Screenshot 2024-11-27 at 10 57 05 AM" src="https://github.com/user-attachments/assets/8dd34595-82f8-4c8a-87b5-506a97d43371">

So I am guessing if this issue is same as https://github.com/flutter/flutter/issues/120682

**Comment by maknon** [comment]
please try it with landscape. 

in normal it is normal to have padding because the height of the image is less than the screen sop it is normal to have it centralized. thats why i put the red border to show that there is no padding in the image it self. in landscape you will see the border is expanded to have the unwanted padding

**Comment by darshankawar** [comment]
Thanks for the update. I was able to replicate the reported behavior on iOS in landscape mode as below:

<img width="717" alt="Screenshot 2024-11-28 at 10 57 56 AM" src="https://github.com/user-attachments/assets/f062adbc-2ac3-47da-bf5c-b3b7de78fa8c">

Without `flutter_svg` package and only using `Image.network`, in landscape mode, there's no top padding:

<img width="718" alt="Screenshot 2024-11-28 at 10 59 38 AM" src="https://github.com/user-attachments/assets/3c3d2e45-70c1-4c62-be96-f19bdff088ca">

In Android though, there's no padding with svg in landscape:

<img width="525" alt="Screenshot 2024-11-28 at 10 52 42 AM" src="https://github.com/user-attachments/assets/61104946-bf3e-415c-978e-db35e17f66fd">

```
stable : 3.24.5
master : 3.27.0-1.0.pre.628
```

**Comment by jmagman** [comment]
@domesticmouse I see you listed as the flutter_svg codeowner since it was pulled into the packages repo.  Do you have any bandwidth to dig into why this could be happening? There isn't any native iOS code in that package.

**Comment by domesticmouse** [comment]
Ok, I assume the intended outcome is to have a scrollable full width view of the SVG. The code causing the issue has a number of problems that are causing the SVG renderer to generate sub-optimal rendering. The first is that you have wrapped the `Scaffold` with a `SafeView`. The `Scaffold` knows how to properly play with the various cutouts that mobile phones have, so you need to push the `SafeView` further down the stack.

The second issue is that you are relying on `MediaQuery.of(context).size.width` which is conflicting with the aforementioned `SafeView`. The `MediaQuery` is telling you the size of the screen, but the `SafeView` is stripping away some of the usable space, which means you are giving the `SvgPicture` conflicting constraints. You are telling it to be wider than the view tree constraints allows. So use `LayoutBuilder` to get the available width instead.

So, here is a working version of your code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Scaffold(
        body: SafeArea(child: LayoutBuilder(builder: (context, constraints) {
      return SingleChildScrollView(
          child: Container(
              decoration: BoxDecoration(border: Border.all(color: Colors.red)),
              child: SvgPicture.network('https://haq.app/assets/hafs/3.svg',
                  width: constraints.maxWidth)));
    }))));
  }
}
```

(I stripped commas to reduce vertical space usage, please reformat to your preferred layout)

![simulator_screenshot_247CCDF7-BCDA-4F9B-B73A-3680A1470C0E](https://github.com/user-attachments/assets/55d37027-1027-4d61-bd5f-849157a32f5c)
