### ISSUE TITLE
There are two Flutter Gallery apps on the Play Store

### ISSUE THREAD

**Issue by newfivefour** [flutter/flutter#15934]
There are two Gallery apps on the Play store (https://play.google.com/store/apps/details?id=io.flutter.gallery and https://play.google.com/store/apps/details?id=io.flutter.demo.gallery). The first is authored by Google Samples. The second is authored by Flutter.io. The Flutter.io is much more up to date than the Google Samples one.

Should we remove the Google Samples app?

**Comment by xster** [comment]
Duping into #15034
