### ISSUE TITLE
The Flutter.io Gallery app on the Play store takes about 5 seconds to open

### ISSUE THREAD

**Issue by newfivefour** [flutter/flutter#15936]
## Steps to Reproduce

Open the Flutter.io Gallery app on the Play Store (https://play.google.com/store/apps/details?id=io.flutter.demo.gallery).

It takes just under five seconds to start. It should take about a second at most.

The top review on (https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&hl=en) also confirms this big.

Incidentally, the older Google Samples Gallery app takes around one second to load https://play.google.com/store/apps/details?id=io.flutter.gallery&hl=en).

**Comment by chinmaygarde** [comment]
@eseidelGoogle Do we know the engine and framework SHAs for the gallery release on the Play Store. I am trying to reproduce this on my phone and the load time seems fine.

@newfivefour: Can you add information about the device and Android version you saw this issue on?

**Comment by newfivefour** [comment]
A Nexus 7, Android 6.0. I doubt it's just me as the top post on the Play store says the same.

**Comment by newfivefour** [comment]
@chinmaygarde Actually with the new update to the Store app it's fine now.

https://github.com/flutter/flutter/issues/14504#issuecomment-377742539 reports they've updated the engine.
