### ISSUE TITLE
Getting pixel values of an Image?

### ISSUE THREAD

**Issue by Kartik1607** [flutter/flutter#15931]
Hello, 
I was thinking of making a widget  but would need some suggestions on how to approach it.
The widget would take up the Image as a child, get it's pixel values (RGB color, count etc) do some manipulation and return a new image.

I am new to flutter and dart here and have been reading source code and docs for hours and haven't found a way to get the required information.

Possible widget usage is like this

```
new myWidget(
    image: Image.network(url")
) 
```

Is  this possible? Or do I need to instead create different workarounds to manage fetching image from network, asset, memory etc?

**Comment by cyrsis** [comment]
```
new Image.network(
                  'https://github.com/flutter/website/blob/master/_includes/code/layout/lakes/images/lake.jpg?raw=true',
                  color: Colors.black12,
                ),
```

**Comment by Kartik1607** [comment]
@crysis This is not what I want. I want to know how to access the pixel information of the image for some kind of manipulation and processing. Something like bitmap in android.

**Comment by rmtmckenzie** [comment]
Try the [Image library](https://pub.dartlang.org/packages/image) for dart - it should allow you to do what you want. Note that it probably won't be particularly optimized; if you're doing anything particularly complicated you'll probably run into performance issues.

Also, I don't think it handles actually loading files so you'll have to do that yourself.

**Comment by Kartik1607** [comment]
@rmtmckenzie So, there is no way currently to utilize the flutter Image widget and I would have to reinvent  the wheel of loading images from different sources, caching them, potentially resizing them and returning them with bounds just to get something as trivial as pixel information.

this is actually really sad.

**Comment by zoechi** [comment]
Perhaps loading the image imperatively and then using `Image.memory()` would work

**Comment by rmtmckenzie** [comment]
@Kartik1607 I might be wrong - there could be a better way of doing this (I'm not a flutter developer, just someone who uses it).  I'd imagine that if/once they do expose the native layer this stuff could become easier, but for now flutter is mainly a UI framework for creating performant UIs and animations.

I would imagine that by exposing all of the things you're asking for, they'd have to make sacrifices on either performance or at least other features - even though it's google they don't have unlimited development resources =P. But I bet that if you made a non-snarky feature request, eventually they'd consider it.

In the meantime, dart is still flexible enough to allow you to do what you want with a relatively minute amount of work for you to do considering there are libraries for doing http requests and loading generic files from assets - although you haven't been particularly clear about what that is beyond wanting to access the pixels. If you provided more details, someone may be able to give you a suggestion about how to do it.

And if that library isn't enough, you can always use a [texture](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/texture.dart), implement whatever you're wanting to do separately in Android and iOS, and then have it shown in flutter's UI using the texture.

**Comment by Kartik1607** [comment]
I have been digging the flutter source code extensively and have tried the following approaches.
1. [dart:ui Image class](https://docs.flutter.io/flutter/dart-ui/Image-class.html) mentions it provides **Opaque handle to raw decoded image data (pixels).**. The flow takes to using [Codec](https://docs.flutter.io/flutter/dart-ui/Codec-class.html) and [FrameInfo](https://docs.flutter.io/flutter/dart-ui/FrameInfo-class.html) none of which actually provide the pixel info.

2. [ImageFilter](https://docs.flutter.io/flutter/dart-ui/ImageFilter-class.html) can blur the image. To do so, it must be using pixel level information of image. But unfortunately, the code is **native** for the class.

I will be digging more at the available code to explore other options. 
I came to this point as I wanted to get the prominent colors in an image ( **Palette library on Android**). Since flutter had no widget, I decided to port the library. I'll be looking at the code of how the native implementation works for now.

**Comment by Kartik1607** [comment]
I'll be looking into **MethodChannels** to see if this issue is resolvable by that approach.

**Comment by jonahwilliams** [comment]
What you need is https://github.com/flutter/engine/pull/4762.  The problem is that bits which come in via the network or in memory are encoded, and so require processing before you can actually use the buffer.

**Comment by andreidiaconu** [comment]
@Kartik1607 Any luck with the Palette implementation?

**Comment by andreidiaconu** [comment]
For anyone interested, I needed to implement Palette in Flutter and I ended up creating a plugin that uses the Android Palette implementation on Android and https://github.com/shnhrrsn/ImagePalette on iOS. I intend to publish it at some point in the upcoming weeks but since right now I have other priorities, it will have to wait.

If there's anyone that expresses deep interest until then, I will create a github repo to show the code.

**Comment by Kartik1607** [comment]
@andreidiaconu publish it.

**Comment by andreidiaconu** [comment]
@Kartik1607 Haven't yet published to pub yet. Until I do, please use this repo https://github.com/andreidiaconu/FlutterPalette

**Comment by Kartik1607** [comment]
Had a quick look at the library. Seems like it takes the path of a local image file and then generates palette. This is rarely the case in most of high performance apps.

**Comment by andreidiaconu** [comment]
For network, if you download the files in dart, then you could use the library by pointing it at the downloaded file. For my use case this was enough. I was also thinking we could use [Scene.toImage()](https://github.com/flutter/flutter/issues/16274) to extract the colors from any part of the UI, but this would also require saving a png on disk and handing it over to the plugin.

**Comment by lukepighetti** [comment]
I am trying to do something similar. I'd like to get the average color of an image on Flutter. Any ideas?

**Comment by andreidiaconu** [comment]
@lukepighetti average is one thing, dominant color is another. Using the above library you can ask for all swatches and then see which one has the largest population (dominant color). If you have a small red flower on a larger, green background, the dominant color will be green. Hope this helps, feel free to clone or fork the repo and let me know if you run into issues.

**Comment by lukepighetti** [comment]
Yes, dominant color is what I'm looking for. Thank you.

**Comment by zoechi** [comment]
flutter/packages#2 might be related

**Comment by andreidiaconu** [comment]
For anyone landing here looking for Palette implementations, https://github.com/flutter/packages/pull/2 looks like the real deal as it is implemented in dart, instead of using platform specific implementations as https://github.com/andreidiaconu/FlutterPalette does 👍

**Comment by Kartik1607** [comment]
Looked at the package code. I was coding up a similar approach. Glad to see a great solution. It is now clear that to get pixel value's one would have to add listeners to image providers and to render image, would need to pass the same provider to Image widget. Great!

**Comment by Kartik1607** [comment]
Closing this issue. For solution refer https://github.com/flutter/packages/pull/2

**Comment by chornbe** [comment]
I think the point that is being missed here is, the original poster wants to load an image - by whatever means is appropriate for the situation - and have access to the actual underlying bytes of the RENDERED image (to account for widget scaling, BoxFit, etc.) and get, say, the color and opacity of  any given byte in the rendered image.
