### ISSUE TITLE
Adding spellCheckConfiguration to CupertinoTextFormFieldRow constructor

### ISSUE THREAD

**Issue by sargntpi** [flutter/flutter#159382]
### Use case

Currently **CupertinoTextFormFieldRow** has no property to set the _spellCheckConfiguration_. This appears to be an oversight. Behind the scenes the CupertinoTextFormFieldRow creates a CupertinoTextField.borderless, which allows for that to be set, and defaults to SpellCheckConfiguration.disabled() if null, which will always be the case when using a CupertinoTextFormFieldRow.

Currently possible:

```dart
CupertinoTextField(
     spellCheckConfiguration: const SpellCheckConfiguration(),
 );
```

Not currently possible:

```dart
CupertinoTextFormFieldRow(
    spellCheckConfiguration: const SpellCheckConfiguration(),
);
```

### Proposal

Add the _spellCheckConfiguration_ property to the constructor for **CupertinoTextFormFieldRow**, and pass it through to the CupertinoTextField.borderless that is created.

**Comment by krishpranav** [comment]
Hi, is this issue still open?

**Comment by sargntpi** [comment]
> Hi, is this issue still open?

Hello, the pull request has been approved, but I wasn't sure whether to close now or after it's been merged.

**Comment by krishpranav** [comment]
oh okay cool no issues

**Comment by krishpranav** [comment]
I am looking to contribute to flutter repo that's why asked.
