### ISSUE TITLE
Compilation error after upgrading to Xcode 16

### ISSUE THREAD

**Issue by TianXiaoBei** [flutter/flutter#159321]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/7a896416-e18f-409c-ad56-ecb8f64ee1da)

### Expected results

Expect compilation to pass

### Actual results

Compilation failed

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

无

### Logs

<details open><summary>Logs</summary>

```
运行：flutter build ios-framework --no-profile --no-release
```console
💪 Building with sound null safety 💪

Building frameworks for com.hbg.globalFlutter in debug mode...
 ├─Copying Flutter.xcframework...                                  132ms
ProcessException: Process exited abnormally:
ld: warning: -bitcode_bundle is no longer supported and will be ignored
ld: warning: -bitcode_process_mode is no longer supported and will be ignored
ld: file cannot be open()ed, errno=2 path=marker in 'marker'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
  Command: /usr/bin/arch -arm64e xcrun clang -x c -arch arm64 /var/folders/hl/g09yw5j54ks6tjsz6prmsg500000gp/T/flutter_tools.hkn0em/flutter_tools_stub_source.GPIJ55/debug_app.cc -dynamiclib
  -fembed-bitcode-marker -miphoneos-version-min=11.0 -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -install_name
  @rpath/App.framework/App -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk -o
  /Users/tianlong/Desktop/app_huobiapp_ios/GlobalAppFlutter/.dart_tool/flutter_build/a0ff7df05ec8201ba7983250dfa2ec74/App.framework/App
 ├─Building App.xcframework...                                     18.7s
The App.xcframework build failed.
```

```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  GlobalAppFlutter git:(release/20241127) ✗ flutter doctor -v
[WARN] FVM_HOME environment variable is deprecated. 
```
Please use FVM_CACHE_PATH instead
[✓] Flutter (Channel stable, 3.3.8, on macOS 15.1.1 24B91 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.8 on channel stable at /Users/tianlong/fvm/versions/3.3.8
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 years ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • iPhone (mobile)      • 00008101-000A054C0203001E • ios            • iOS 17.6.1 21G93
    • 沐晨的12ProMax (mobile) • 00008101-001C59921168001E • ios            • iOS 17.7 21H16
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 131.0.6778.86

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>
```

**Comment by darshankawar** [comment]
> Channel stable, 3.3.8

@TianXiaoBei You are on obsolete version of the sdk. Latest version is 3.24.5. Please upgrade to latest, update your config to latest and re-run to check if you still get same behavior or not.

Closing for now, as stable version is not latest.
