### ISSUE TITLE
Google Streamer file_picker not working/causing crashes

### ISSUE THREAD

**Issue by syleishere** [flutter/flutter#159315]
### Steps to reproduce

Using file_picker will cause infinite loop causing google streamer to freeze up temporarily.
A quick way to reproduce is download wireguard app and click "+" symbol on screen, it will produce same errors in logcat as using fluttter file_picker

### Expected results

It should open up a file manager program to select a file

### Actual results

logcat shows an endless loop of app crashing.

### Code sample

Just download wireguard app and click "+" and watch logcat as app crashes, or code your own flutter example using file_picker.

### Logs

https://sunsaturn.com/logcat.txt

### Flutter Doctor output

latest version

**Comment by darshankawar** [comment]
@syleishere 
I am not sure completely about the reported behavior. 

> Just download wireguard app and click "+"

What is wireguard ? Does it replicate with flutter create template code ? Can you also provide the crash log ?

**Comment by syleishere** [comment]
Log above is from logcat in the url, it just repeats that log over and over again freezing app. Wireguard was the openvpn replacement everyone uses for private VPNs. In that app the "+" is for selecting a config file for it, it should open a file manager to select a file, but it suffers same fate as using file_picker in flutter with exact same loop from logcat freezing the app.

**Comment by syleishere** [comment]
On previous google tv 4k, it would bring up one of file managers you downloaded to say select a config file for wireguard off your local drive or NAS.

**Comment by syleishere** [comment]
Yeah here simple counter app with file_picker that will reproduce issue:

```
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';



void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() async {
    setState(() {
      _counter++;
    });
    FilePickerResult? result = await FilePicker.platform.pickFiles(allowMultiple: true);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const Text('hello dude'),
            ElevatedButton(
              onPressed: _incrementCounter,
              child: const Text('Select File'),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by syleishere** [comment]
Running just that in debug mode to the google streamer will send logcat out of control on the device.

**Comment by syleishere** [comment]
On running more tests, it seems this happens when type: FileType.any is set, which is the default.

**Comment by syleishere** [comment]
I'll submit a new PR with that patch to project, all can do to fix the google streamer.

**Comment by syleishere** [comment]
https://github.com/miguelpruivo/flutter_file_picker/compare/master...syleishere:flutter_file_picker:master

PR submitted, best I can do, thank-you trying to debug this with me.

**Comment by darshankawar** [comment]
@syleishere since file_picker is a third party package, please follow-up in it for further updates.
Closing as this isn't a flutter issue.
