### ISSUE TITLE
Issue running the app on simulator: You can't open the application "Runner" because this application is not supported on this Mac.

### ISSUE THREAD

**Issue by bhagat-abhishek** [flutter/flutter#159389]
### Steps to reproduce

* So this is just happening to this specific app we are running. Whenever I create a new flutter app it works fine for both IOS and Android Simulators. Although here are the steps I follow.

1. git clone repo
2. flutter pub get
3. run on simulator

### Actual results

Below is the screenshot of the error.
https://ibb.co/444YvPb

Below is the debug output 
```
Launching lib/main.dart on iPhone 16 Pro in debug mode...
Xcode build done.                                           21.9s
Connecting to VM Service at ws://127.0.0.1:54994/QRAQMhRlfaw=/ws
Connected to the VM Service.
Lost connection to device.

Exited.
```

Although this app works fine on android.

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by bhagat-abhishek** [comment]
Hey @danagbemava-nc thanks for your response, unfortunately I do not have physical device actually right now. 

Attaching the files https://filetransfer.io/data-package/0O9ppN40#link

**Comment by danagbemava-nc** [comment]
Hi @bhagat-abhishek, have you modified any of the build settings in Xcode? Did this start after an upgrade of flutter or addition of a plugin?

**Comment by bhagat-abhishek** [comment]
Hello @danagbemava-nc thanks for your response. Let me explain it all.

So basically this project was created on a windows machine which is running, all the flutter checks; I have compared between both devices are same, still this is happening. All other projects work fine creating on this device.

**Comment by danagbemava-nc** [comment]
Hi @bhagat-abhishek, can you try recreating the iOS folder on your Mac to see if you still experience this? Please create a backup of the original folder before you recreate it.

**Comment by bhagat-abhishek** [comment]
Hi @danagbemava-nc thanks you for your response. Sorry for the late reply.
The issue was resolved yesterday. 

For me the issue turned out to be related to the `ios/Runner/Info.plist` file not having the permissions specified; required for location, adding which resolved the issue.
