### ISSUE TITLE
Pub Not install

### ISSUE THREAD

**Issue by Coder-Ashish** [flutter/flutter#15935]
when i tried to install Angular Dart it installed successfully bit it wont install pub. how i will install Pub manually in windows

**Comment by zoechi** [comment]
Please provide information about what steps you took.
`pub` is part of Dart, not Angular Dart. 
How is this even related to Flutter?

**Comment by Coder-Ashish** [comment]
i downloaded the dart setup from official dart website .exe file and installed it
the like from where i downloaded the dart is 
http://www.gekorm.com/dart-windows/

**Comment by zoechi** [comment]
Dart is not Equal Flutter and Angular is not related to Flutter in any way, so it's quite unclear why you created the issue here.
The information you provided also doesn't allow to diagnose the problem.

**Comment by zoechi** [comment]
Closing because it's unclear if there is something to do.
