### ISSUE TITLE
Auto submit bot can revert correctly due to merge queue

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#159356]
### Type of Request

bug

### Infrastructure Environment

github, autosubmit bot

### What is happening?

https://github.com/flutter/flutter/pull/159354

The bot created the revert and tried to merge the revert with merge queue. The bot then close the pr instantly before waiting for the merge queue to merge the pr. I had to manually reopen the revert and merge myself.

### Steps to reproduce

use revert label on a merged pr.

### Expected results

should work correctly

**Comment by chunhtai** [comment]
cc @yjbanov

**Comment by Piinks** [comment]
I think this might be fixed by https://github.com/flutter/cocoon/pull/4043

**Comment by yjbanov** [comment]
That's correct. Deduping into https://github.com/flutter/flutter/issues/159365
