### ISSUE TITLE
if `macos/Runner/Release.entitlements` is invalid, `flutter build macos` should fail, not silently ignore `macos/Runner/Release.entitlements`

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#159327]
### Steps to reproduce

when building on MacOS targeting MacOS `macos/Runner/Release.entitlements` with the following content will activate the MacOS sandbox:
``` XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
</dict>
</plist>
```
but if you have any error in `macos/Runner/Release.entitlements` like:
``` XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>a</key>
</dict>
</plist>
```
the program will compile and silently ignore `macos/Runner/Release.entitlements`
This should not happen!

### Expected results

if `macos/Runner/Release.entitlements` is invalid, `flutter build macos` should fail, not silently ignore `macos/Runner/Release.entitlements`

### Actual results

when `macos/Runner/Release.entitlements` is invalid, `flutter build macos` silently ignore `macos/Runner/Release.entitlements`

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
Entitlements files are part of the underlying design of macOS application builds, and are handled entirely by the Xcode build process; the `flutter` tool never interacts with that file. Suggested changes to how Xcode validates project components during build would need to be directed to Apple.

Closing as out of scope for Flutter.
