### ISSUE TITLE
Flutter can't detect if it should use 32bit when third party libraries are using 32bit NDK only

### ISSUE THREAD

**Issue by swavkulinski** [flutter/flutter#15941]
## Steps to Reproduce

1) Find any library which has only 32bit (armeabi-v7a) NDK code
2) Add it to the flutter project
3) Try to run on any 64bit (arm64-v8a) device

Notice: App crashes because it tries to run 64bit while only 32bit dependencies are satisfied
Expected: App is compiled with 32bit support only and during compile, it sends a warning stating that resulting APK has 64bit excluded due to missing dependencies.

Notice: ``` flutter run --target-platform android-arm``` compiles and executes correctly on 64bit device

## Logs

```
03-26 07:14:55.437 26092-26092/com.theappbusiness.flutter.helloworld E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.theappbusiness.flutter.helloworld, PID: 26092
                                                                       java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.theappbusiness.flutter.helloworld-8vjCHZsfrBa5rfrnJLsV5g==/base.apk"],nativeLibraryDirectories=[/data/app/com.theappbusiness.flutter.helloworld-8vjCHZsfrBa5rfrnJLsV5g==/lib/arm64, /data/app/com.theappbusiness.flutter.helloworld-8vjCHZsfrBa5rfrnJLsV5g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "liblept.so"
                                                                           at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                           at java.lang.System.loadLibrary(System.java:1657)
```

created APK has following libraries:

<img width="804" alt="screen shot 2018-03-26 at 07 41 56" src="https://user-images.githubusercontent.com/2101969/37914025-29d8233e-310e-11e8-8e19-f05b739ba592.png">

Unfortunately, the library used in above sample (scanbot) is proprietary so I can't include it.

## Flutter Doctor

[✓] Flutter (Channel master, v0.2.5-pre.41, on Mac OS X 10.13.3 17D102, locale en-GB)
    • Flutter version 0.2.5-pre.41 at /Users/swavkulinski/Git/flutter
    • Framework revision 2171fcb882 (32 hours ago), 2018-03-25 00:04:24 -0700
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/swavkulinski/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/swavkulinski/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • iPhone X • DFE6D52B-54D5-438F-8259-7BD3B0E7678B • ios • iOS 11.2 (simulator)

• No issues found!

**Comment by xster** [comment]
Tentatively duping into #15530
