### ISSUE TITLE
[web] Reduce CanvasKit's initial memory allocation

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#159499]
Currently, CanvasKit eagerly [allocates 128MB](https://github.com/flutter/engine/blob/95b5e5ec25ca7e8f45ca064d7ca0b738c55516ab/skia/modules/canvaskit/BUILD.gn#L173) of wasm memory. Let's try to reduce that to 64MB or 32MB.

The reason we can do it is because most image decoding is now done by the browser ([PR](https://github.com/flutter/engine/pull/53201)).

**Comment by yjbanov** [comment]
We should also make it customizable, like we allow customizing the max number of overlays, `cavaskitBaseUrl`, etc.

**Comment by yjbanov** [comment]
I think 64MB would be a reasonable new default for all browsers. However, some customers may be interested in lowering it further, down to 32MB or something.
