### ISSUE TITLE
TextField maxLines > 0, initial height to 1

### ISSUE THREAD

**Issue by tobire** [flutter/flutter#15946]
I'd like to limit the input lines on a TextField to 5 but I'd also like to start out with only one line so that the TextField isn't taking up too much space in the beginning.
If I set the maxLines to 5 it starts out with a height of 5 lines.
After exceeding the limit of 5 lines I'd like the field to be scrollable just like it is right now if I exceed the maxLines.

This is how I imagine it:

![screenshot_20180326-213655](https://user-images.githubusercontent.com/1534148/37928796-5934b540-313e-11e8-8891-ee8f3088103c.png)
![screenshot_20180326-213800](https://user-images.githubusercontent.com/1534148/37928800-5d01ee22-313e-11e8-8994-d3d960c76372.png)

**Comment by tobire** [comment]
Dupe of #15388

**Comment by QoLTech** [comment]
Support.
