### ISSUE TITLE
Flutter Web App Crashes in Firefox after Frequent Actions (Navigation, API Calls, Form Submission)

### ISSUE THREAD

**Issue by wasimCronySoft** [flutter/flutter#159481]
I am encountering a persistent issue with my Flutter web app built using Flutter 3.24.5, where the app crashes in Firefox after performing frequent actions such as navigating between pages, submitting forms, or fetching data from an API. This causes the browser to close the tab and display the error message: "Your tab just crashed."

When inspecting the Firefox Console, the following warnings appear consistently before the crash:

**1. targetWidth and targetHeight for multi-frame images not supported:** This warning appears when handling multi-frame images (e.g., GIFs). It seems Firefox does not support resizing multi-frame images using targetWidth or targetHeight.

**2. Layout was forced before the page was fully loaded:** This warning suggests that layout recalculations or DOM updates are being triggered prematurely, possibly contributing to performance issues.

The crash appears to be specific to Firefox, as the app works correctly in other browsers such as Chrome and Safari, without crashes or significant warnings.

**Steps to Reproduce:**

1. Build and deploy a Flutter web app using Flutter 3.24.5.
2. Integrate the app with Firebase (Firestore and Authentication).
3. Perform frequent actions like:
        Navigating between routes.
        Fetching data from Firestore or submitting forms.
        Rendering pages with multi-frame images (e.g., GIFs).
4. Observe the crash in Firefox after repeated actions.

**Key Observations:**

1. The crash behavior becomes more frequent with repeated actions (API requests or rapid navigation).
2. The targetWidth and targetHeight warning suggests compatibility issues with Firefox when handling certain image types.
3. The layout recalculation warning points to potential inefficiencies in rendering or style application.
4. The issue does not occur in Chrome or Safari, suggesting Firefox-specific behavior.

**Attempted Solutions:**

1. Ensured proper disposal of controllers (e.g., ScrollController, StreamController) and listeners.
2. Minimized unnecessary widget rebuilds using const constructors and RepaintBoundary.
3. Checked for memory leaks using Flutter DevTools, but no clear issues were found.
4. Despite these efforts, the app continues to crash in Firefox.

### Sample Code List
<details open><summary>Code</summary>

```
class DummyListDesktop extends StatelessWidget {
  const DummyListDesktop({super.key});
  @override
  Widget build(BuildContext context) {
    return GetBuilder<DummyPageController>(builder: (controller) {
        int length = controller.filteredList.length;
        return RefreshIndicator(
          onRefresh: (() => controller.getDummyList()),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: length > 0 || controller.loading
                    ? ListView.separated(
                        itemCount:
                            controller.loading ? AppStyles.shimmerLength : length,
                        padding: const EdgeInsets.all(AppStyles.mainPaddingOrMargin),
                        separatorBuilder: (context, index) => const DividerWidget(
                              height: 0,
                              thickness: 1,
                            ),
                        itemBuilder: (context, index) {
                          return Container(
                              decoration: UIHelper.defaultShadowDecoration(
                                onlyTopRounded: index == 0,
                                borderRadius: index == 0 || (index == length - 1)
                                    ? AppStyles.globalRadius
                                    : 0,
                                onlyBottomRounded: (index == length - 1),
                              ),
                              child: InkWellCustomWidget(
                                onlyTopRounded: index == 0,
                                borderRadius: index == 0 || (index == length - 1)
                                    ? AppStyles.globalRadius
                                    : 0,
                                onlyBottomRounded: (index == length - 1),
                                padding: AppStyles.mainPaddingOrMargin,
                                backgroundColor: Colors.transparent,
                                hoverOpacity: 0.7,
                                onTap: controller.loading
                                    ? null
                                    : () => controller.itemTap(index),
                                child: controller.loading
                                    ? _shimmerWidget()
                                    : _dataWidget(
                                        index: index,
                                        data: controller.filteredList[index]),
                              ));
                        })
                    : controller.errorWidget(),
              ),
            ],
          ),
        );
      }
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2024-11-26 at 4 53 05 PM](https://github.com/user-attachments/assets/4522175c-1d1d-4d06-b8df-9e62f7333807)

</details>

### Logs

<details open><summary>Logs</summary>

```console
targetWidth and targetHeight for multi-frame images not supported
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded, this may cause a flash of unstyled content.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-arm64, locale en-PK)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by ubaidsuhailcronysoft** [comment]
Any Update I have faced same issue after upgrading to flutter 3.22 from 3.16.8.

**Comment by danagbemava-nc** [comment]
Hi @wasimCronySoft, without a complete minimal reproducible code sample, there isn't much we can do on this. Please provide a complete minimal reproducible code sample so that we can properly investigate this. 

Thank you

**Comment by wasimCronySoft** [comment]
@danagbemava-nc Look at this update. The issue is explained in more detail.

Thanks

**Comment by danagbemava-nc** [comment]
Hi @wasimCronySoft, we will still need a complete minimal reproducible code sample so that we can properly investigate this. 
Please try to provide a sample app we can use. 

Thank you
