### ISSUE TITLE
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

### ISSUE THREAD

**Issue by shashank-shinde** [flutter/flutter#15942]
**Log:**
> E:\Flutter>flutter doctor
> Checking Dart SDK version...
> Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8
> a...
> Unzipping Dart SDK...
> Updating flutter tool...
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
> 
> Waiting for 0 seconds, press CTRL+C to quit ...
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
> 
> Waiting for 0 seconds, press CTRL+C to quit ...
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
> 
> Waiting for 0 seconds, press CTRL+C to quit ...
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
> 
> Waiting for 0 seconds, press CTRL+C to quit ...
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
> 
> Waiting for 0 seconds, press CTRL+C to quit ...
> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
>

![ss](https://user-images.githubusercontent.com/7486205/37921034-427dc406-3146-11e8-8c7f-ddc1e66ca6ae.JPG)

**Comment by shashank-shinde** [comment]
P.S.- I've checked previous issues but non of them solved this problem.

**Comment by zoechi** [comment]
which previous issues have you checked? What have you tried?

**Comment by zoechi** [comment]
I collected a few things people reported to fix the issue for them in https://github.com/flutter/flutter/issues/15014#issuecomment-374501940

**Comment by shashank-shinde** [comment]
#12666

**Comment by shashank-shinde** [comment]
I cloned the master branch using `git clone -b master https://github.com/flutter/flutter.git` instead `git clone -b master https://github.com/flutter/flutter.git` then issue is fixed. Thank you @zoechi :)
