### ISSUE TITLE
Travis iOS store push build is hanging on 0.2.4

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15944]
https://travis-ci.org/flutter/flutter/jobs/357173090 hangs on 

```
▸ Running script 'Run Script'
```

Reproducible locally.

**Comment by xster** [comment]
Seems stuck on `/Users/xster/development/flutter/bin/flutter --suppress-analytics build aot --output-dir=build/aot --target-platform=ios --target=lib/main.dart --release --preview-dart-2` where the `flutter` process never finished.

**Comment by xster** [comment]
Seems to have originated from #15547 though I don't know why yet

**Comment by xster** [comment]
Not sure if it helps. Calling io.exit(0) doesn't actually end the process and these resources are still held by the process (on osx):
```
COMMAND   PID  USER   FD   TYPE             DEVICE   SIZE/OFF       NODE NAME
bash    96052 xster  cwd    DIR                1,4       1056    1149552 /Users/xster/development/flutter/examples/flutter_gallery
bash    96052 xster  txt    REG                1,4     618448 8590576354 /bin/bash
bash    96052 xster  txt    REG                1,4     837248 8594593182 /usr/lib/dyld
bash    96052 xster  txt    REG                1,4 1160380416 8599372101 /private/var/db/dyld/dyld_shared_cache_x86_64
bash    96052 xster    0u   CHR               16,1  0t4935702        821 /dev/ttys001
bash    96052 xster    1   PIPE 0x97ae8860036ecdf3      16384            ->0x97ae8860036ee6b3
bash    96052 xster    2   PIPE 0x97ae8860036ecdf3      16384            ->0x97ae8860036ee6b3
bash    96052 xster  255r   REG                1,4       6821 8600345531 /Users/xster/development/flutter/bin/flutter
```

**Comment by pulyaevskiy** [comment]
It might be worth pinging someone from the VM team, maybe? Looks like there are a few open issues searchable for "vm hangs": https://github.com/dart-lang/sdk/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+vm+hangs
