### ISSUE TITLE
On iOS, using DatePickerDialog with showGeneralDialog function causes the dialog to have a weird scrolling behavior

### ISSUE THREAD

**Issue by ahmednoaman-git** [flutter/flutter#159450]
### Steps to reproduce

I am trying to make an animation for dialog popups in my app to blur the background with a smooth animation as they popup. For this I used the `showGeneralDialog` function instead of the usual `showDialog` as it has a `transitionBuilder`.

To reproduce:
Simply call `showGeneralDialog` and inside its `builder` callback return a `DatePickerDialog`.

### Expected results

when calling with `showDialog`
![simulator_screenshot_6F3D6ABE-C534-4507-920B-E468DA8ACA60](https://github.com/user-attachments/assets/7dd011b8-d475-4a1b-960a-7fbc343f8c50)

### Actual results

when calling with `showGeneralDialog`
iOS:
![simulator_screenshot_B8F3C5A6-58E6-453E-A799-AE174D99B897](https://github.com/user-attachments/assets/84bf3474-2d52-4507-bf02-b257f9000f90)

Android:
![image](https://github.com/user-attachments/assets/916fb744-1a83-4b19-84f4-2d553c8e0664)

As you can see for some reason the day selection buttons seem to be initially scrolled down on iOS

### Code sample

Here is a small example showing my exact usecase with the desired blur animation
<details open><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Date Picker bug'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: const SizedBox.shrink(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showBlurredBackgroundPopUp(
            context: context,
            builder: (context) {
              return DatePickerDialog(
                firstDate: DateTime.now(),
                lastDate: DateTime.now().add(const Duration(days: 365)),
              );
            },
          );
        },
        child: const Icon(Icons.calendar_month_rounded),
      ),
    );
  }
}

Future<T?> showBlurredBackgroundPopUp<T extends Object?>({
  required BuildContext context,
  required Widget Function(BuildContext context) builder,
}) async {
  return await showGeneralDialog<T>(
    context: context,
    barrierDismissible: true,
    barrierLabel: '',
    barrierColor: Colors.transparent,
    transitionDuration: const Duration(milliseconds: 500),
    pageBuilder: (context, anim1, anim2) {
      return builder(context);
    },
    transitionBuilder: (context, anim1, anim2, child) {
      final double blurAnimationValue = Curves.easeOut.transform(anim1.value);
      return BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 10 * blurAnimationValue, sigmaY: 10 * blurAnimationValue),
        child: FadeTransition(
          opacity: anim1,
          child: child,
        ),
      );
    },
  );
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @ahmednoaman-git 
I do see the same behavior as below:

<img width="353" alt="Screenshot 2024-11-26 at 3 28 05 PM" src="https://github.com/user-attachments/assets/2f0d2a29-ec5f-4600-a09e-6e8fcfdb9eac">

Although we need to confirm if this is occuring due to blur effect applied in the background or not. Can you try without blur effect or BackDropFilter to check if the behavior still persist or not ? Also, I tried with official [example](https://api.flutter.dev/flutter/material/showDatePicker.html#material.showDatePicker.1) with which the cut-off at the bottom doesn't occur:

<img width="350" alt="Screenshot 2024-11-26 at 3 45 10 PM" src="https://github.com/user-attachments/assets/e8ffb2db-e241-48c9-adeb-8849ec688dee">

**Comment by ahmednoaman-git** [comment]
Yes, @darshankawar. Using just the plain function `showGeneralDialog` leads to the same behavior

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Date Picker bug'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: const SizedBox.shrink(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showGeneralDialog(
            context: context,
            pageBuilder: (context, anim1, anim2) {
              return DatePickerDialog(
                firstDate: DateTime.now(),
                lastDate: DateTime.now().add(const Duration(days: 365)),
              );
            },
          );
        },
        child: const Icon(Icons.calendar_month_rounded),
      ),
    );
  }
}
```
![simulator_screenshot_1256567B-CEB7-4BE2-ADA3-B427EC040D6A](https://github.com/user-attachments/assets/a493c441-a437-4ac8-8db8-53a14e9472e0)

**Comment by ahmednoaman-git** [comment]
@darshankawar The official example works because `showDatePicker` dialog is internally just calling `showDialog` rather than `showGeneralDialog`

**Comment by darshankawar** [comment]
Thanks for the update. Please see https://github.com/flutter/flutter/issues/130691#issuecomment-1639675057 reasoning as why it doesn't work with `showGeneralDialog` and we should be using `showDialog` as it supports M3. You may also try to wrap `showGeneralDialog` with `SafeArea` to see if it works.

But based on the linked comment, I will close this as not an issue. If you disagree, write in comments and I'll reopen it.
