### ISSUE TITLE
Error while running flutter pub get

### ISSUE THREAD

**Issue by asin-shabi** [flutter/flutter#159492]
### Steps to reproduce

1. Install flutter and setup VSCode
2. Create a flutter project
3. try to run `flutter pub get`

### Actual results

After running the following command I got the following error:
`flutter pub get`

> Resolving dependencies... (2.0s)
> Because repay depends on flutter_native_splash any which doesn't exist (authorization failed), version solving failed.
> 
> Insufficient permissions to the resource at the https://pub.dev package repository.
> You can modify credentials using:
>     dart pub token add https://pub.dev

My pubspec.yaml file:

> name: MyApp
> description: "This is my app"
> version: 0.9.0+1
> 
> environment:
>   sdk: ^3.5.2
> dependencies:
>   flutter:
>     sdk: flutter
>   flutter_localizations:
>     sdk: flutter
>   intl: ^0.19.0
>   flutter_native_splash: ^2.4.3
>   cupertino_icons: ^1.0.8
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
>   flutter_lints: ^4.0.0
> flutter:
>   uses-material-design: true
>   assets:
>     - assets/lang/fa.json
>     - assets/lang/en.json
>     - assets/images/logotranscolored.png

Solutions I've tried:

1. Changed the Windows
2. Using VPN and DNS changers
3. Login to pub.dev using `dart pub login`
4. Create new project tons of times

Please give me a solution cause I'm dealing with this bug for weeks.

### Logs

<details open>
<summary>Logs</summary>

```console

Resolving dependencies... (2.0s)
Because repay depends on flutter_native_splash any which doesn't exist (authorization failed), version solving failed.

Insufficient permissions to the resource at the https://pub.dev/ package repository.
You can modify credentials using:
dart pub token add https://pub.dev/

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.26100.2314], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.12.0)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[!] Android Studio (not installed)
[√] VS Code (version 1.95.3)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by iapicca** [comment]
@asin-shabi 
try these steps:

1. delete pub cache `rm ~/.pub-cache/credentials.json` (or whatever works for windows)
2. clean up flutter
```console
flutter upgrade
flutter pub cache repair
```
3. clean up the project `flutter clean`


alternatively some country restrict its citizens from internet access
you may try [this](https://docs.flutter.dev/community/china)

**Comment by asin-shabi** [comment]
Thanks for your reply. I've already done the mirror and china solution and still get the same error. I don't know what the problem is. Did Flutter add a new step to call `pub get` or is it a bug? As I'd mentioned already I changed my IP and DNS

**Comment by iapicca** [comment]
> [...] I've already done the mirror and china solution and still get the same error. [...]

@asin-shabi
could you do the cleaning steps as well

> try these steps:
> 
> 1. delete pub cache `rm ~/.pub-cache/credentials.json` (or whatever works for windows)
> 2. clean up flutter
> 
> ```
> flutter upgrade
> flutter pub cache repair
> ```
> 
> 3. clean up the project `flutter clean`

**Comment by asin-shabi** [comment]
I did it too. I have done it multiple times before

**Comment by darshankawar** [comment]
Are you trying to access a private repo ? Looks more like a pub issue than flutter's. See a similar one https://github.com/dart-lang/pub/issues/3368, so please follow-up in it for further updates. Also check if https://dart.dev/tools/pub/cmd/pub-token helps or not and [this](https://stackoverflow.com/a/79074124).
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by asin-shabi** [comment]
What was the reason for closing this question?

The package I'm trying to add is flutter_native_splash which is a public package.
The funnier part is if I remove this package the `pub get` will show the flutter default packages and dependencies as error, so the problem is not about packages. 

My only solution for this problem (which is a typical problem for devs in our country) was using VPN or DNS changer, but when those options didn't work I found out that I don't know exactly what to do...

**Comment by iapicca** [comment]
@asin-shabi 
try this brother (be precise with the indentation)
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash:
    git: https://github.com/jonbhanson/flutter_native_splash
```

**Comment by asin-shabi** [comment]
@iapicca
Thanks for your comment, but this solution returned the same error:

`flutter pub get`
> Resolving dependencies... (30.5s)
> Because every version of flutter_native_splash from git depends on universal_io any which doesn't exist (authorization failed), flutter_native_splash from git is forbidden.
> So, because repay depends on flutter_native_splash from git, version solving failed.
> 
> Insufficient permissions to the resource at the https://pub.dev package repository.
> You can modify credentials using:
>     dart pub token add https://pub.dev

I have used VPN and DNS changer again.
Is it possible that the VPN is not tunneling vscode?

**Comment by iapicca** [comment]
try on terminal
(powershell or whatever windows people use)

**Comment by darshankawar** [comment]
> @darshankawar
> What was the reason for closing this question?

@asin-shabi It could be related to limited or restricted access of pub.dev from the location you are trying to access. See similar issues:

https://github.com/flutter/flutter/issues/150060
https://github.com/flutter/flutter/issues/145169

**Comment by iapicca** [comment]
> > @darshankawar
> > What was the reason for closing this question?
> 
> @asin-shabi It could be related to limited or restricted access of pub.dev from the location you are trying to access. See similar issues:
> 
> #150060 #145169

@darshankawar 
it didn't seem to me @asin-shabi argued against the restrictions
and the issue he reported seems to occur only on vscode and not on terminal

not a big fan of the syllogism 
"if you have a pub issue and you are from Iran then it's automatically you problem now"

**Comment by darshankawar** [comment]
> not a big fan of the syllogism
> "if you have a pub issue and you are from Iran then it's automatically you problem now"

I just posted related links. Not sure why you deduce that.

> I hope the problem was with the VSCode Terminal

You may need to reach in dedicated repo https://github.com/Dart-Code/Dart-Code/issues
