### ISSUE TITLE
Flutter packages caching for offline app bootstrapping.

### ISSUE THREAD

**Issue by kasonde** [flutter/flutter#15940]
##Feature request.

Not to sure if this already a feature but it'd be great to be able to create an app whilst offline. Currently the project create process fails at running get packages.

**Comment by zoechi** [comment]
You can use `pub cache add` to add packages to the local cache without creating a `pubspec.yaml`
`flutter create --offline ...`
`flutter run --no-pub ...`
Please provide more concrete information about where this causes problems and the exact commands and exact error message.

**Comment by kasonde** [comment]
Thanks a lot. This took care of my concerns
