### ISSUE TITLE
[IOS] Flutter FPS drops when "resuming from background" and "after unlocking the screen".

### ISSUE THREAD

**Issue by quochuyR** [flutter/flutter#159409]
### Steps to reproduce

- I reviewed issue #96381, but unfortunately, this problem persists.
- I observed that, in addition to 'resuming from background,' a similar issue arises when the screen is locked (screen off) and then unlocked to continue using the Flutter application.
- The FPS drop rate is significantly high when the screen is locked (screen off) and then unlocked, followed by continued usage.
- I am using an iPhone 15 Plus running iOS 18.1.1 for development.

### Expected results

#

### Actual results

#

### Code sample

#

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 13.5.1 22G90 darwin-x64, locale en-VN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.77.3)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@quochuyR 
The issue you linked was fixed last year. If you are facing same issue, please provide us updated / runnable reproducible code sample that shows the reported behavior along with detailed expected vs actual result you are looking for.

**Comment by quochuyR** [comment]
The issue doesn’t occur frequently, but I usually encounter it during app development and testing—specifically when switching to another app and then returning, or after turning the screen off and back on.

**Comment by darshankawar** [comment]
@quochuyR 
Please provide us some data or visuals that backs your reported behavior. Also, if possible, check if this occurs using previous iOS devices as well or just with new version.
