### ISSUE TITLE
Application crashes when app is running in background and I change some app permission to deny state from app settings.

### ISSUE THREAD

**Issue by Mohit8G** [flutter/flutter#159432]
### Steps to reproduce

1. I am using microphone permission and first i have granted permission to it.
2. Then I go to background and change microphone permission to deny from app info.
3. When I go back to my application from background  it shows a black screen.

### Expected results

Expected results -> When I do the same thing in android it automatically restart the whole app,

### Actual results

A strange black screen is appearing.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.3 23D56 darwin-arm64, locale en-IN)
    • Flutter version 3.22.2 on channel stable at /Users/mohit/.puro/envs/new/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mohit/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available


```

</details>

**Comment by the-best-is-best** [comment]
App auto close when change permission state from setting in any apps 

Check this in any apps in your mobile

**Comment by Mohit8G** [comment]
Hey thanks for the reply but I am launching the flutter module on top of native via flutter engine, and in this case flutter doesn't restart it self

**Comment by darshankawar** [comment]
@Mohit8G 
Can you provide `flutter doctor -v` and a sample repo that we can clone to verify this further ? Also provide us exact steps to replicate so that we can properly address it.

**Comment by Mohit8G** [comment]
> @Mohit8G Can you provide `flutter doctor -v` and a sample repo that we can clone to verify this further ? Also provide us exact steps to replicate so that we can properly address it.

added in the post itself.
Also adding the video to reproduce it.
Link - > https://drive.google.com/file/d/1GgvxDsRZXklk2XCZogLp55qZb44TWXMC/view?usp=sharing
The base screen is in android and on clicking search icon we launch a flutter module. 
App restart it self but flutter engine crashes
