### ISSUE TITLE
ClipRRect when using google_maps_flutter clip iOS bug

### ISSUE THREAD

**Issue by kmeljko** [flutter/flutter#159590]
### Steps to reproduce

1. Create new flutter app
2. Add google_maps_flutter package
3. Add GoogleMap to ClipRRect widget inside scrollable widget (ListView)
4. Overscroll on iPhone device

### Expected results

GoogleMap widget stays in Clipped state even when overscrolling 

### Actual results

ClipRRect stops clipping GoogleMap when part of widget is outside viewport

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(
          children: [
            Container(
              color: Colors.purple,
              width: 200,
              height: 1000,
            ),
            Container(
              padding: const EdgeInsets.all(12),
              height: 200,
              child: ClipRRect(
                borderRadius: BorderRadius.circular(20),
                child: const GoogleMap(
                  initialCameraPosition:
                      CameraPosition(target: LatLng(40, 10), zoom: 5),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Simulator Screen Recording - iPhone 16 Pro - 2024-11-28 at 14 27 28](https://github.com/user-attachments/assets/ace6489e-171e-45a4-8b90-9ea77ece687b)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6 23G80 darwin-arm64, locale en-RS)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @kmeljko 
What iphone device are you using ? I actually tried on simulator with latest stable and master versions with which the clip behavior doesn't occur. See below:


https://github.com/user-attachments/assets/fd825944-dd9b-4841-bc11-a58027f41370

 google_maps_flutter: ^2.10.0
 master version: 3.27.0-1.0.pre.668
 stable : 3.24.5

**Comment by kmeljko** [comment]
Hi!
I was testing on iPhone 15 pro max in simulator.
I am having this issue in app that is already in App Store and I believe most people have same bug on different iPhone devices. My personal iPhone also has same problem but It may be because most of iPhone's I tested are iOS 17+

Can you try with newer iOS beacuse in screen record says that you are using iOS 15.2.
Thanks

**Comment by darshankawar** [comment]
@kmeljko 
We verified on iOS 18.1 version in which we were unable to replicate it. Please see below:


https://github.com/user-attachments/assets/9de99f1e-ec7d-4814-9cc5-991b7435b7a0


Please try to upgrade to latest stable to check if you still get the same behavior or not.

**Comment by kmeljko** [comment]
Last time I updated flutter and it didn't solve the issue. This time after update it works as it should. 
I guess there was a bug in flutter material regarding cliprrect which made the issue at first. 

Thank you for all your help! @darshankawar
