### ISSUE TITLE
Error in image picker: PlatformException(already_active, Image picker is already active, null, null)

### ISSUE THREAD

**Issue by moin-maniar** [flutter/flutter#159553]
### Steps to reproduce

I am facing this issue in image_picker library with API level 28 (Android 9) or below. please help to resolve this issue. 

Link of image_picker library: [https://pub.dev/packages/image_picker](url)

### Expected results

camera should open properly and image should be selected from it

### Actual results

First time camera is opened perfectly then it does not open at all with image_picker library. Please help to soive this issue in android 9 or below

### Code sample

<details open><summary>Code sample</summary>

```dart
final ImagePicker picker = ImagePicker();

pickedImage = await picker.pickImage(
      source: ImageSource.camera,
       mageQuality: 20,
 );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by moin-maniar** [comment]
> you provide `flutter doctor -v`

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.22.0 on channel stable at /Users/mm/Desktop/flutterDev/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (7 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/moinmaniar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mm/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mm/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • RMX3710 (mobile)                • CQI7PNXOSC89EA4D      • android-arm64 • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64  • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin        • macOS 14.6.1 23G93 darwin-arm64
    ! Error: Browsing on the local area network for YelowSoft’s iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone 12_. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

My Device is oneplus a3003_28_191104 (API Level 28)

![IMG_20241129_163154](https://github.com/user-attachments/assets/fe1facc3-1ff1-4d0a-a935-059a87b12f3e)

Please help me to solve this issue.

**Comment by moin-maniar** [comment]
@darshankawar , I hope there would a positive response from your side for this issue

**Comment by darshankawar** [comment]
As I see from your config and device you are using, (oneplus), you are most probably having same issue as https://github.com/flutter/flutter/issues/87896, so please follow-up in it for further updates. Closing this as a duplicate.
