### ISSUE TITLE
exportArchive exportOptionsPlist error for key "method" expected one {} but found app-store

### ISSUE THREAD

**Issue by InfinitySoftware-House** [flutter/flutter#159519]
### Steps to reproduce

1. flutter build ipa --release --build-number xx --export-options-plist path/to/exportOptions.plit

### Actual results

```
Archiving com.company.x...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXX
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        31.1s
 └─Compiling, linking and signing...                        13.6s
Xcode archive done.                                         308.1s
✓ Built build/ios/archive/Runner.xcarchive (871.7MB)

[✓] App Settings Validation
    • Version Number: 1.0.13
    • Build Number: 96
    • Display Name: AppName
    • Deployment Target: 12.0
    • Bundle Identifier: com.company.x

[!] App Icon and Launch Image Assets Validation
    ! App icon is set to the default placeholder icon. Replace with unique icons.
    ! Launch image is set to the default placeholder icon. Replace with unique launch image.

To update the settings, please refer to https://flutter.dev/to/ios-deploy

Building App Store IPA...                                          607ms
Encountered error while creating the IPA:
error: exportArchive exportOptionsPlist error for key "method" expected one {} but found app-store


Try distributing the app in Xcode: "open /build/ios/archive/Runner.xcarchive"
```

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @InfinitySoftware-House, can you share the content of your `exportOptions.plist` file? 

Please also provide the output of `flutter build ipa --release --build-number xx --export-options-plist path/to/exportOptions.plist -v`

The output may be huge, so kindly put it into a .txt file and attach it here. 

Thank you

**Comment by InfinitySoftware-House** [comment]
Hi!

This is the exportOptions.plist file content:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">
    <dict>
        <key>compileBitcode</key>
        <true/>
        <key>destination</key>
        <string>export</string>
        <key>method</key>
        <string>app-store</string>
        <key>signingStyle</key>
        <string>automatic</string>
        <key>stripSwiftSymbols</key>
        <true/>
        <key>teamID</key>
        <string>XXXXXXX</string>
        <key>thinning</key>
        <string>&lt;none&gt;</string>
    </dict>
</plist>

The output log is too big, 66MB, when the maximum to upload is 25, what can I do?

**Comment by danagbemava-nc** [comment]
Hi @InfinitySoftware-House, you can upload it pastebin or a similar site. 

Can you try making the method `app-store-connect` instead of `app-store` to see if it works? I might have seen somewhere that the key is no longer `app-store` but I can't find it at the moment.

**Comment by InfinitySoftware-House** [comment]
> Hi @InfinitySoftware-House, you can upload it pastebin or a similar site.
> 
> Can you try making the method `app-store-connect` instead of `app-store` to see if it works? I might have seen somewhere that the value is no longer `app-store` but I can't find it at the moment.

It's the same:
exportArchive exportOptionsPlist error for key "method" expected one {} but found app-store-connect

This is the url for the log.txt:

https://jumpshare.com/s/u1w2jPWEZ6qjxPh6s9q7

**Comment by danagbemava-nc** [comment]
Hi @InfinitySoftware-House, curious, do you get this same issue with the counter app?

**Comment by InfinitySoftware-House** [comment]
Hi! Thank you for your help! The "counter app" is building the IPA, but I see that the ios folder is slightly different, the counter app has no pods or podfile.
Is it changed during flutter's updates?
If yes, how can I change the project to not use the Pods?

**Comment by danagbemava-nc** [comment]
Hi @InfinitySoftware-House, kindly share the ExportOptions.plist file and the flutter build -v logs for the counter app so that we can try comparing both of them to see if there's any differences. 

Thank you

**Comment by InfinitySoftware-House** [comment]
Hi @danagbemava-nc, for the build of the counter app I am not using the custom ExportOptions parameters, but the default one.
This is the log file for the counter app "build ipa" command:
https://jumpshare.com/s/jk9F605n5cBoSqhCm7B2

I don't really know what changed between my project and the counter app...
Please help me🥲

**Comment by InfinitySoftware-House** [comment]
Ok, I don't know why, but the issue was caused by a library, "awesome_notifications", I've tried to remove it, now it works!

**Comment by danagbemava-nc** [comment]
Hi @InfinitySoftware-House, do you get the same issue if you add the `awesome_notifications` plugin to the counter app?

**Comment by entrepreneur1001** [comment]
> Hi @InfinitySoftware-House, do you get the same issue if you add the `awesome_notifications` plugin to the counter app?

I was also facing the same issue after adding awesome_notifications plugin but finally found the solution on their discord .

add these 3 lines to your podfile
unless target.name == 'Runner'
        config.build_settings['SKIP_INSTALL'] = "YES"
      end
it will look like this 

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        unless target.name == 'Runner'
             config.build_settings['SKIP_INSTALL'] = "YES"
      end
    end
    flutter_additional_ios_build_settings target
  end

**Comment by InfinitySoftware-House** [comment]
Thank you! I resolved the issue! @entrepreneur1001 

Thank you too! You were very helpful! @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Glad to see it has been resolved. 

Closing this as solved.
