### ISSUE TITLE
Gallery App has Pull to Refresh

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1595]
From https://www.google.com/design/spec/patterns/swipe-to-refresh.html
- [x] gesture
- [x] visual feedback (progress indicators)

Phase 2:
- [x] It always appears at the top and bottom of its scrollable. This should be configurable and it should default to just appearing at the top.
- [x] During the drag phase, the refresh indicator should only animate when the drag is moving.
- [x] While the refresh callback is running, the refresh indicator's arrowhead shouldn't appear.
- [ ] ~~It should be possible for the refresh callback to update the indicator with its actual progress.~~ https://github.com/flutter/flutter/issues/7664
- [ ] The refresh indicator should disappear "when the user navigates away from the refreshing content".
- [x] Currently the duration of overscrolls is extended because all drags end in a fling. Both OverscrollIndicator and RefreshIndicator need to cause the Scrollable's ScrollBehavior to set overscroll fling velocities to zero.

This is a common pattern, something we might want to implement convenience support for. At a minimum, we'd like to show this in the gallery. Also, we should show this behavior in a vignette/showcase.

**Comment by sethladd** [comment]
Phase 1 completed in https://github.com/flutter/flutter/pull/3354

**Comment by sethladd** [comment]
Dupes https://github.com/flutter/flutter/issues/425

**Comment by eseidelGoogle** [comment]
We have this, it's just not quite right.  @HansMuller plans to fix this.

**Comment by olostan** [comment]
Though I didn't found any "pull-to-refresh" functionality, my solution was:

1. Wrap scrollable into `Stack` (in my case it was `ScrollableGrid`
2. Put such set of widgets as first element (under scrollable):
```
      new Positioned(
          left: 0.0,
          top: 170.0,
          right: 0.0,
          child: new Opacity(
              opacity: overscroll,
              child: new Center(
                  child: new Transform(
                      alignment: FractionalOffset.center,
                      transform: new Matrix4.rotationZ(overscroll * 3 * 3.14),
                      child: new Icon(Icons.refresh, size: 50.0))))),
```
3. Add `double overscroll = 0` into state
4. Add `onScroll` handler to something like:
```
          onScroll: (offset) {
            var newOverscroll = 1 - (100.0 + offset).clamp(0.0, 100.0) / 100.0;
            if (newOverscroll != overscroll)
              setState(() {
                overscroll = newOverscroll;
                if (overscroll == 1 && !loading) {
                  reload();
                }
              });
          },
```

Seems working! Hope this will help to someone who need "pull-to-refresh" :)

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/overscroll_demo.dart demonstrates one way to do pull to refresh.  There are two buttons in the upper right to switch between overscroll and pull to refresh.

**Comment by eseidelGoogle** [comment]
It looks like this is already closed, but maybe we need to file a new doc about making the example or docs more obvious?

**Comment by Hixie** [comment]
I don't know what "The refresh indicator should disappear "when the user navigates away from the refreshing content"" means we should do.

I've split out the last remaining issue into its own bug. I'm going to close this as otherwise done.

**Comment by amlang** [comment]
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/overscroll_demo.dart

**Comment by Mutembeijoe** [comment]
[flutter/gallery](https://github.com/flutter/gallery) now lives here
