### ISSUE TITLE
Default TabBar indicatorColor should contrast with its background

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#15958]
Running the example provided here  https://flutter.io/cookbook/design/tabs/ fails if the TabBar's `indicatorColor` isn't explicitly set to white.

This is a regression.

**Comment by HansMuller** [comment]
This appears to have be an inadvertant side-effect of https://github.com/flutter/flutter/pull/15265

**Comment by tvolkert** [comment]
This affects `v0.2.4` (and probably `v0.2.5` depending on when the fix lands).  Does this make for a Bad Build?

**Comment by HansMuller** [comment]
Yes, this was a serious regression.
