### ISSUE TITLE
Unable to test SharedPreferences

### ISSUE THREAD

**Issue by jgfoster** [flutter/flutter#159597]
### Steps to reproduce

1. `flutter create bug`.
2. Replace `bug/test/widget_test.dart` with the code sample provided below.
3. Try to run tests.

### Expected results

Tests pass—I should be able to write tests when my application uses SharedPreferences*. 

### Actual results

* SharedPrefs: hangs
* SharedPreferencesAsync: "Bad state: The SharedPreferencesAsyncPlatform instance must be set."
* SharedPreferencesWithCache: "Bad state: The SharedPreferencesAsyncPlatform instance must be set."

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:prefs/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const MyApp());

    // Verify that our counter starts at 0.
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    // Tap the '+' icon and trigger a frame.
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    // Verify that our counter has incremented.
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });

  testWidgets('SharedPrefs', (WidgetTester tester) async {
    print('SharedPrefs test - 1');
    // hangs
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    print('SharedPrefs test - 2 - $prefs');
  });

  testWidgets('SharedPreferencesAsync', (WidgetTester tester) async {
    // Obtain shared preferences.
    print('SharedPreferencesAsync test - 1');
    // Bad state: The SharedPreferencesAsyncPlatform instance must be set.
    final SharedPreferencesAsync asyncPrefs = SharedPreferencesAsync();
    print('SharedPreferencesAsync test - 2 - $asyncPrefs');
  });

  testWidgets('SharedPreferencesWithCache', (WidgetTester tester) async {
    // Obtain shared preferences.
    print('SharedPreferencesWithCache test - 1');
    // Bad state: The SharedPreferencesAsyncPlatform instance must be set.
    final SharedPreferencesWithCache prefsWithCache =
        await SharedPreferencesWithCache.create(
      cacheOptions: const SharedPreferencesWithCacheOptions(
        // When an allowlist is included, any keys that aren't included cannot be used.
        allowList: <String>{'repeat', 'action'},
      ),
    );
    print('SharedPreferencesWithCache test - 2 - $prefsWithCache');
  });
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
% flutter test
00:01 +1: SharedPrefs                                                                                                                       
SharedPrefs test - 1
^Cunhandled error during finalization of test:
/Users/jfoster/temp/prefs/test/widget_test.dart
TestDeviceException(Shell subprocess terminated by ^C (SIGINT, -2).)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.1)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
Please see https://docs.flutter.dev/testing/plugins-in-tests; closing as this is a fundamental, documented limitation of Dart unit tests when trying to use Flutter plugins.

[`InMemorySharedPreferencesAsync`](https://pub.dev/documentation/shared_preferences_platform_interface/latest/in_memory_shared_preferences_async/InMemorySharedPreferencesAsync-class.html) is one option for unit tests (corresponding closely to [this testingoption](https://docs.flutter.dev/testing/plugins-in-tests#mock-the-plugins-platform-interface)).

**Comment by jgfoster** [comment]
This is a disappointing outcome.

* At the base level, all packages make "platform functionality available to the app", even if it is just the GUI (which varies dramatically across the platforms supported by Flutter).
* While some packages may be identified as a "plugin", there is no clear indication that testing is not supported. This should be a prominent part of the README.
* When testing is not supported in the HTTP package (does it make platform functionality available to the app?), there is at least a clear indication ("All HTTP requests return 40X in test").
* This attitude reduces my confidence in the Dart/Flutter ecosystem. I could completely understand if the answer were "It is hard and low-priority but we agree it should be done and is on our roadmap" but the response seems to be "testing is not important and we don't see any reason to encourage it".
* Is there any way to tell when code is being run in a testing environment? The HTTP package seems to manage. 
* If there is an obvious testing option, why not build it in to the package itself (or at least point to an issue proposing that this be done)?

I've spent many hours trying to figure out why our app just hangs when running the tests. I've told my students that they should start with the assumption that the vendor's packages work and any problem is in our code. I'm frustrated to discover that testing is so poorly supported. I suggest documenting the lack of testing support with each plugin and an indication when calling the package during a test that the package doesn't work.

**Comment by stuartmorgan** [comment]
> * While some packages may be identified as a "plugin", there is no clear indication that testing is not supported.

Testing is supported via integration tests (as discussed in the documentation linked above).

> This should be a prominent part of the README.

I would recommend requesting this as [a feature request in pub.dev](https://github.com/dart-lang/pub-dev), as having every plugin in the ecosystem document fundamental Flutter behaviors in their README is not scalable. pub.dev has the ability to identify plugins, so could surface this information automatically.

> * This attitude reduces my confidence in the Dart/Flutter ecosystem. I could completely understand if the answer were "It is hard and low-priority but we agree it should be done and is on our roadmap"

That is not a possible answer. Plugins are fundamentally, inherently linked to the process of building and running a Flutter application, and `test` does not do that step. The native portion of the plugin's code does not exist in the context of a Dart unit test.

Integration tests, on the other hand, run in the context of the application, and thus contain all of the plugin code, allowing them to work in integration tests.

Making Flutter plugins work in all tests would, in essence, require making all tests integration tests, which would not be a desirable outcome given that integration tests—due to this build requirement—have a build/run cycle that is orders of magnitude slower.

> but the response seems to be "testing is not important and we don't see any reason to encourage it".

That was not the intended message of my response. We believe that testing is important, and we encourage people to write a variety of tests using the appropriate test systems. We encourage people writing integration tests to use the integration test system, and we encourage people writing unit tests to appropriately partition off external dependencies.

**Comment by jgfoster** [comment]
Is there a way for code to know when it is being run in a test?

**Comment by stuartmorgan** [comment]
> * Is there a way for code to know when it is being run in a test (other than me setting a flag at the beginning of a test)?

Please file a new issue for general test documentation requests, so it can be triaged and routed to the right subteam.

> * How can I tell when a package is a plugin?

A package is a Flutter plugin if it contains [the `flutter:plugin:` entry in pubspec.yaml](https://docs.flutter.dev/packages-and-plugins/developing-packages#plugin-platforms).

> Is `io` a plugin or not? Is [http](https://pub.dev/packages/http) a plugin?

Neither is a Flutter plugin. `shared_preferences` doesn't use either though, so I'm not sure how that relates to this issue.

**Comment by jgfoster** [comment]
> I'm not sure how that relates to this issue.

This was in the context of "How can I tell when a package is a plugin?" Given that "A plugin package is a special kind of package that makes platform functionality available to the app" ([source](https://docs.flutter.dev/packages-and-plugins/using-packages)), I had imagined that someting that deals with the file system or OS processes was closely tied to platform functionality. And, as noted earlier, the GUI is closely related to platform functionality. 

So, while all plugins provide platform functionality, not all packages that provide platform functionality are plugins. 

In any case, thanks for clarifying the role of `pubspec.yaml` in identifying plugins.
