### ISSUE TITLE
Add a test to check that we can upgrade/downgrade to the commit when we publish a new dev/beta build

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15950]
The roll script should test upgrading/downgrading to the new dev build.

cc @tvolkert

**Comment by csells** [comment]
@Hixie can you provide repro steps, the behavior you're seeing and the expected behavior?

**Comment by digiter** [comment]
Triage: @pcsosinski Is this still needed?

**Comment by pcsosinski** [comment]
yes, this is currently a manual test step for a beta release.

**Comment by godofredoc** [comment]
@christopherfujino is this something that can be automated?

**Comment by christopherfujino** [comment]
> @christopherfujino is this something that can be automated?

yeah, we have some integration test coverage on this, I'll assign to myself to track.

**Comment by christopherfujino** [comment]
yep
