### ISSUE TITLE
Add getters to easely access Brightness and ThemeMode

### ISSUE THREAD

**Issue by stan-at-work** [flutter/flutter#159569]
### Use case

I would be nice if we could do:

```dart
final brightness = Brightness.light;

// This is long
final isLightMode = brightness == Brightness.light;
final isDarkMode = brightness == Brightness.dark;

---

//This is better
final isLightMode = brightness.isLight;
final isDarkMode = brightness.isDark;
```

---

The same for ThemeMode

`system`
`light`
`dark`

### Proposal

[PR Brightness](https://github.com/flutter/engine/pull/56841)
[PR ThemeMode](https://github.com/flutter/flutter/pull/159570)

**Comment by matanlurey** [comment]
As discussed on attached PRs, we aren't going to be adding convenience getters to enums. Individuals can use extension methods in their own projects if they find this pattern useful.
