### ISSUE TITLE
SelectionArea does not work on  CustomPaint

### ISSUE THREAD

**Issue by jisuz** [flutter/flutter#159532]
### Use case

SelectionArea does not work on  CustomPaint。
`SelectionArea(`
              `child: CustomPaint(`
               ` painter: MyPainter(useTextPainter),`
            `  ),`
             ` onSelectionChanged: (value) {`
                `debugPrint("onSelectionChanged: ${value}");`
             ` },`
         `   ),`

### Proposal

`SelectionArea(`
              `child: CustomPaint(`
               ` painter: MyPainter(useTextPainter),`
            `  ),`
             ` onSelectionChanged: (value) {`
                `debugPrint("onSelectionChanged: ${value}");`
             ` },`
         `   ),`

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137977

Kindly leave a thumbs up on the original issue. 

Thank you
