### ISSUE TITLE
Error: The pod "Firebase/Firestore," required by the plugin "cloud_firestore" requires a higher minimum iOS deployment version than the plugin's reported minimum version. To build, remove the plugin "cloud_firestore", or contact the plugin's developers for assistance.

### ISSUE THREAD

**Issue by AbScott1985** [flutter/flutter#159547]
Error: The pod "Firebase/Firestore," required by the plugin "cloud_firestore" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "cloud_firestore", or contact the plugin's developers for assistance.

I have changed deployment all the way to iOS 18 and I still get the error

**Comment by RepliedSage11** [comment]
Hi, 

try to `cd` into the `ios` directory in your Flutter project and run:

```
pod repo update
pod update
```

This type of error can happen if you have recently updated your pub dependencies.

**Comment by AbScott1985** [comment]
I have tried that done flutter clean flutter build dont the platform all the way to iOS 18 and its still the same no matter what I do also done this

arch -x86_64 pod install --repo-update 

sudo arch -x86_64 gem install ffi                                                                

arch -x86_64 pod install                                                                    

arch -x86_64 pod repo update                    

I have also tried deleting the pods the podlock files as well and created a new pod file still the same error 

Error: The pod "Firebase/Firestore," required by the plugin "cloud_firestore" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "cloud_firestore", or contact the plugin's developers for assistance.
Error running pod install
Error launching application on iPhone 16.

**Comment by danagbemava-nc** [comment]
This is a firebase issue and should be reported on the flutterfire repo https://github.com/firebase/flutterfire/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

Closing from here as this is not a flutter issue. 

If you are redirected here after filing an issue on their repo, kindly leave a comment below and I will reopen this issue. 

Thank you
