### ISSUE TITLE
ios TextField "中文"

### ISSUE THREAD

**Issue by yangyiyyds** [flutter/flutter#159659]
How to solve the problem of inputting Chinese in the "TextField" component of "ios"? The problem is different from Apple systems

**Comment by yangyiyyds** [comment]
> @yangyiyyds 您遇到了什么问题？请尝试使用新问题[模板](https://github.com/flutter/flutter/issues/new/choose)并填写所需详细信息，以便我们能够正确解决问题。目前您尚未提供任何详细信息，因此我将因缺乏详细信息而关闭此问题。

demo：
  final TextEditingController _controller3 = TextEditingController();  
TextField(
                  controller: _controller3,
                  autofocus: true,
                  decoration: const InputDecoration(
                    hintText: '请输入文本3',
                    border: OutlineInputBorder(),
                  ),
                  style: const TextStyle(fontSize: 18),
                ),


Flutter version： environment:
  sdk: '>=3.1.0 <4.0.0'     
The ios15 emulator and the real Apple 15 cannot enter Chinese

**Comment by darshankawar** [comment]
@yangyiyyds 
I am not sure if I understand what's the issue you are facing. I tried pasting the text 中文 on iOS simulator (16.0) as below:

<img width="356" alt="Screenshot 2024-12-03 at 11 35 20 AM" src="https://github.com/user-attachments/assets/694222dd-9c75-4a6c-99a9-395ebe8d54f7">

Are you saying, using chinese keyboard input, you are unable to input that text (中文) in the textfield ?

**Comment by yangyiyyds** [comment]
> @yangyiyyds 我不确定我是否理解您面临的问题。我尝试在 iOS 模拟器 (16.0) 上粘贴文本中文，如下所示：
> 
> <img alt="截图于 2024-12-03 上午 11 点 35 分 20 秒" width="356" src="https://private-user-images.githubusercontent.com/67046386/391832750-694222dd-9c75-4a6c-99a9-395ebe8d54f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTAwMzksIm5iZiI6MTczMzIwOTczOSwicGF0aCI6Ii82NzA0NjM4Ni8zOTE4MzI3NTAtNjk0MjIyZGQtOWM3NS00YTZjLTk5YTktMzk1ZWJlOGQ1NGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA3MDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MTUzMTQ0NTZiM2RhOGU5M2VkYWFlYmQ5MTg4OTgxNTg1N2ViYzAwZWZhMmMxNWZmMjIwNjU3NmMxY2UwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KPOFsuWkVZ3m4_nVnMQEUPNXI5FxUX0OheZ7IY2PL-s">
> 您是说，使用中文键盘输入，您无法在文本字段中输入该文本（中文）？

**Comment by yangyiyyds** [comment]
> @yangyiyyds 我不确定我是否理解您面临的问题。我尝试在 iOS 模拟器 (16.0) 上粘贴文本中文，如下所示：
> 
> <img alt="截图于 2024-12-03 上午 11 点 35 分 20 秒" width="356" src="https://private-user-images.githubusercontent.com/67046386/391832750-694222dd-9c75-4a6c-99a9-395ebe8d54f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTAxNTIsIm5iZiI6MTczMzIwOTg1MiwicGF0aCI6Ii82NzA0NjM4Ni8zOTE4MzI3NTAtNjk0MjIyZGQtOWM3NS00YTZjLTk5YTktMzk1ZWJlOGQ1NGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA3MTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNGU3ZDAyNDI1MzJmNmRkOTQxYWU2OTg2YWQ4MTA2MDBkYThhOGRlMDJlZmQyMmQzMTQ2YTY3ZjM5ZTYyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SVBUZXrczcERZ2SYQHYlLhbKtaVriiv9AkQ5U9xW120">
> 您是说，使用中文键盘输入，您无法在文本字段中输入该文本（中文）？


I tried to use "flutter": "3.22.1" and found that there was no problem entering Chinese the first time, but I couldn't enter when I canceled the focus and got the focus the second time.
This is the second image that has gained focus
![image](https://github.com/user-attachments/assets/ce7c3bd5-106f-49a3-a97d-90a892e5e781)

I updated some of the code：

//昵称设置
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

//有状态控件
class SetUserName extends StatefulWidget {
  const SetUserName({super.key});
  @override
  // ignore: library_private_types_in_public_api
  _SetUserNameState createState() {
    return _SetUserNameState();
  }
}

//有状态控件，必须结合一个状态管理类，来进行实现
class _SetUserNameState extends State<SetUserName> {
  final TextEditingController _controller = TextEditingController();

  late String nickName = '';

  //控件被创建的时候，会执行initState函数类似于
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
        onTap: () {
          // 点击空白处时移除焦点
          FocusScope.of(context).requestFocus(FocusNode());
        },
        child: Scaffold(
            appBar: AppBar(
              backgroundColor: const Color(0xFF023d8d),
              title: const Center(
                child: Text(
                  'demo',
                  style: TextStyle(fontSize: 18, color: Color(0xffffffff)),
                ),
              ),
            ),
            body: Container(
                width: double.infinity,
                height: double.infinity,
                color: const Color(0xfff1f0f5),
                child: Column(
                  children: [
                    Container(
                      padding:
                          const EdgeInsets.only(left: 25, top: 10, bottom: 10),
                      color: const Color(0xffffffff),
                      child: TextField(
                        controller: _controller,

                        onSubmitted: (text) {
                          print("提交的文本: $text");
                        },
                        onChanged: (text) {
                          print("输入的文本: $text");
                          nickName = text;
                          setState(() {});
                        },
                        decoration: const InputDecoration(
                          hintText: '请输入新昵称',
                          border: InputBorder.none, // 隐藏下划线
                        ),
                        inputFormatters: [
                          LengthLimitingTextInputFormatter(8)
                        ], //
                      ),
                    ),
                    Text("输入文字：$nickName")
                  ],
                ))));
  }
}

**Comment by darshankawar** [comment]
So if I understand correctly, you tried entering text in Chinese, then unfocus the field and then coming back to same field, you are not able to input Chinese and can only see English ?

**Comment by yangyiyyds** [comment]
> 所以如果我理解正确的话，你尝试输入中文文本，然后取消焦点，然后返回到同一字段，你无法输入中文，只能看到英文？最新的稳定版本是否也出现同样的情况？

虽然 但是 还是谢谢你的回复 我更新版本 "3.24.3" 没有问题了

English：
Although thanks for your reply, I have no problem with the updated version "3.24.3"

**Comment by darshankawar** [comment]
> I have no problem with the updated version "3.24.3"

So this seems to be resolved then and we can conclude that it is working fine ?

**Comment by yangyiyyds** [comment]
> > 我对更新后的版本“3.24.3”没有任何问题
> 
> 那么这个问题似乎已经解决了，我们可以得出结论说它运行良好？

Yes, this version can solve my Chinese input problem, thank you
