### ISSUE TITLE
[Widget Inspector] Disable show widgets created by the flutter framework by default (or provide toggle in settings to change default behavior)

### ISSUE THREAD

**Issue by bibaswan-bhawal** [flutter/flutter#159663]
### Use case

The new widget inspector, when enabled, shows widgets created by the Flutter framework and libraries by default. While useful for debugging in certain scenarios, can clutter the view.

### Proposal

Either have the show Flutter framework widgets disabled by default or provide a toggle in the settings to change the default behaviour.

**Comment by darshankawar** [comment]
> The new widget inspector, when enabled, shows widgets created by the Flutter framework and libraries by default. While useful for debugging in certain scenarios, can clutter the view.

@bibaswan-bhawal Can you provide us a screenshot / visual of the use case you are facing ?
