### ISSUE TITLE
Flutter hot-restart on web does not load new assets

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#159666]
Using flutter on native platforms (e.g. `flutter run -d macos --debug`) allows adding new assets (by adding entries to `pubspec.yaml`s `flutter.assets....` section). Once the app runs one can use both hot-reload as well as hot-restart and both will pick up new assets from `pubspec.yaml` and make them available.

Though it seems on the web (tested on `flutter run -d chrome --debug`) it doesn't make new assets available after a hot-restart.

Reproduction is very easy:
* Make example app
* Add two assets into `assets/{foo,bar}.txt`
* Modify `lib/main.dart` to try to load both assets and print whether it works or not
* Make `pubspec.yaml` contain
 ```
flutter:
  assets:
    - assets/foo.txt
    # - assets/bar.txt
``` 
* Run `flutter run -d chrome --debug`
  => It should find one asset but not the other.
* Uncomment the commented line in `pubspec.yaml`
* Trigger hot-restart
* => Still cannot find the asset

(repeating the same with `flutter run -d macos --debug` works.

**Comment by danagbemava-nc** [comment]
Hi @mkustermann, this hasn't been implemented yet but there's already an issue tracking this. See  https://github.com/flutter/flutter/issues/137265

Closing this in favor of the issue linked above. 

Thank you
