### ISSUE TITLE
How to cancel the task in Future.delay

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15968]
In StatefulWidget A :
```
  _scheduleTask() async {
    print('======= task =======');
    await new Future.delayed(const Duration(seconds: 10), () {
      if (!mounted) {
        return;
      }

      _scheduleTask();
    });
  }
```

When I pushed to another StatefulWidget B , I still can see the '======= task =======' , how to cancel it? Thank you !

**Comment by zoechi** [comment]
You can use `CancelableOperation` from https://pub.dartlang.org/packages/async

How-to questions are better asked on StackOverflow

**Comment by xster** [comment]
Tentatively closing this issue. Feel free to reopen if your request isn't fully addressed.

**Comment by realcarlos** [comment]
Thank you , I will .

**Comment by realcarlos** [comment]
Thank you , it will be better if there is a demo about CancelableOperation.

**Comment by zoechi** [comment]
https://github.com/dart-lang/async/blob/bcbaeca7be91ee10e3a44ca7639ac65bb3b71845/test/cancelable_operation_test.dart

**Comment by krishnaSoni2113** [comment]
Hello guyz
Please have look at below code.

Future sessionTask;

// Cancelling api here before to call it again

```
   if (sessionTask != null){
  CancelableOperation.fromFuture(sessionTask).cancel().then((data){
    print("CancelableOperation ======== $data");
  });
}
```

// calling api here…

```
sessionTask = APIRequest.shared.login().then((response){
  print("Response ========== ${response.body}");
});
```

/// Login api…

```
Future<http.Response> login() async {
  return _POST(
      "login",
      {
        "email": "tom@mailinator123.com",
        "password": "abc123",
        "latitude": "23.055",
        "longitude": "72.549316406200006"
      },
      headers).then((response) {
    return response;
  });
}
```


/// Http Request..

```
Future<http.Response> _POST(String apiTag, Map<String, String> para,
    Map<String, String> internalHeaders) async {
  Map<String, String> finalHeaders = new Map();
  finalHeaders.addAll(apiHeaders());
  finalHeaders.addAll(internalHeaders);

  try {
    return http
        .post(BASEURL + apiTag, body: para, headers: finalHeaders)
        .then((http.Response response) {
      return response;
    });
  } catch (e) {
    // Handel Error
    return null;
  }
}
```


I am calling api like this way and I am cancelling api before calling again by using the below code but its not working, Please let me know 

1. How can I store request?
2. How can I cancel request?

```
 if (sessionTask != null){
  CancelableOperation.fromFuture(sessionTask).cancel().then((data){
    print("CancelableOperation ======== $data");
  });
}
```

**Comment by zoechi** [comment]
@krishnaSoni2113 I think it's better to ask this kind of question in StackOverflow.
