### ISSUE TITLE
Change SwitchListTile and RadioListTile property name from secondary to leading.

### ISSUE THREAD

**Issue by md-rifatkhan** [flutter/flutter#159673]
Most of us are more familiar with the leading property than secondary, as it is commonly used in widgets like **AppBar, ListTile,** and others. However, **SwitchListTile** and **RadioListTile** use secondary for a similar purpose, which can be confusing. To improve consistency and clarity, I believe the secondary property in these widgets should be renamed to leading to align with the naming convention in other Flutter widgets.

Example Code: 
```
void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Example'),
          leading: Icon(Icons.add),
        ),
        body: ListView(
          children: [
            const ListTile(
              leading: Icon(Icons.add),
              title: Text("Option 1"),
            ),
            const Divider(),
            RadioListTile<int>(
              value: 1,
              groupValue: 1,
              onChanged: (value) {},
              title: const Text('Option 1'),
              secondary: const Icon(Icons.radio_button_checked),
            ),
            const Divider(),
            SwitchListTile(
                value: true,
                onChanged: (value) {},
                title: const Text('Option 2'),
                secondary: const Icon(Icons.radio_button_checked)),
          ],
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@md-rifatkhan 
There's a similar [issue](https://github.com/flutter/flutter/issues/18817) open describing your case, so please follow-up in it for further update. You may share your findings in that issue for better tracking and upvote it.
Closing this as a duplicate.
