### ISSUE TITLE
when flutter 1.0 release will be ready ?

### ISSUE THREAD

**Issue by toplinuxsir** [flutter/flutter#15960]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment]
Google can't answer such questions https://en.wikipedia.org/wiki/Forward-looking_statement

**Comment by timsneath** [comment]
We're not announcing anything right now, but as @sethladd described in the [Flutter Beta 1 announcement](https://medium.com/flutter-io/announcing-flutter-beta-1-build-beautiful-native-apps-dc142aea74c0), our focus is stabilization and scenario completion, with approximately monthly beta releases. We just shipped a [Beta 1 Update](https://groups.google.com/forum/#!topic/flutter-dev/YgSaubUXfOA), which you can download by running `flutter upgrade` from a machine that is on the beta channel.
