### ISSUE TITLE
[Flutter News Toolkit] Upgrade to Mason v0.1.0 (stable release)

### ISSUE THREAD

**Issue by felangel** [flutter/flutter#159641]
### Use case

There's finally a stable release of `pkg:mason` and `pkg:mason_cli` (v0.1.0) 🎉 
This issue is tracking the changes needed to upgrade the `flutter_news_template` to v0.1.0 of `pkg:mason`

cc @wolfenrain @alestiago @tomarra

### Proposal

The only changes needed should be to upgrade the environment constraint in the template's `brick.yaml` to include `^0.1.0` and to bump the mason version in the hooks' `pubspec.yaml` to ^0.1.0.

**Comment by SofiaRey** [comment]
Great to know! What do you think if adding Dependabot there to make sure it's always updated?

**Comment by felangel** [comment]
> Great to know! What do you think of adding Dependabot there to make sure it's always updated?

Yup sounds like a great idea 👍

**Comment by SofiaRey** [comment]
Done! Dependabot added and Mason updated 👌
