### ISSUE TITLE
`No Device` in VSCode and Android Studio but `flutter devices` works

### ISSUE THREAD

**Issue by thatsgolden** [flutter/flutter#159626]
### Steps to reproduce

1. Follow [Flutter Docs](https://docs.flutter.dev/get-started/install) install VSCode, Flutter Extension, Dart Extension
    - Flutter SDK path: `D:\dev\flutter`
    - VSCode path: `D:\Program Files\Microsoft VS Code`
 2. Run `flutter devices`, 4 devices are listed. See **Flutter Doctor output** below.
 3. Run `flutter run -d windows` or `flutter run -d <mobile phone id>` works fine.
 4. Using Flutter's [First Flutter App tutorial](https://docs.flutter.dev/get-started/codelab), from 0 to step 4.
 5. Open VSCode, tip 'No Devices' shows, and the popup bar always loading.
  ![image](https://github.com/user-attachments/assets/6dd0b037-284f-4ced-8850-d79dc9ca6f10)
 6. Open Android Studio, the devices status always loading.
  ![image](https://github.com/user-attachments/assets/3e8de67b-a251-43ef-aba9-d119a1d24800)
![image](https://github.com/user-attachments/assets/074208aa-2177-4290-be39-cc3fec136738)

7. Tried reinstall VSCode, Android Studio, Flutter four times, not work.
8. tried solutions, none worked.
    - #4642
    - [Emulator stucks on loading devices in android studio](https://www.youtube.com/watch?v=7O796HyG8i0)
    - [How to set up devices for Visual Studio Code](https://stackoverflow.com/questions/49280884/how-to-set-up-devices-for-visual-studio-code-for-a-flutter-emulator)
    - [Message "flutter run: No connected devices"](https://stackoverflow.com/questions/49045393/message-flutter-run-no-connected-devices)
    - [Android SDK cannot be found by flutter](https://stackoverflow.com/questions/44485848/android-sdk-cannot-be-found-by-flutter)
    - [flutter: showing no devices connected in android studio and vscode](https://stackoverflow.com/questions/57338724/flutter-showing-no-devices-connected-in-android-studio-and-vscode)
    - Downgrade `adb` version from `1.0.41` to `1.0.40`, not work.

### Actual results

Both VSCode and Android Studio cannot detect my devices that listed by `flutter devices` command.

### Logs

See **Flutter Doctor output** below.

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
> flutter doctor -v
[!] Flutter (Channel stable, 3.24.5, on Microsoft Windows [版本 10.0.22631.4460], locale zh-CN)
    • Flutter version 3.24.5 on channel stable at D:\dev\flutter
    ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (2 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\dev\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\dev\Android\Sdk
    • Java binary at: D:\Program Files\JetBrains\Toolbox\app\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.2)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.12.35521.163
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.2)
    • Android Studio at D:\Program Files\JetBrains\Toolbox\app\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3)
    • IntelliJ at D:\Program Files\JetBrains\Toolbox\app\IntelliJ IDEA Ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains ::1
    • NO_PROXY contains 127.0.0.1

[✓] Connected device (4 available)
    • 9f91daaa (mobile) • 9f91daaa • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22631.4460]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 131.0.6778.86
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 131.0.2903.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</detail

**Comment by ZhuJHua** [comment]
你的flutter咋装的？

**Comment by thatsgolden** [comment]
> 你的flutter咋装的？

follow official installnation document， tried both VSCode way and manually download zip file， the issue remains.

**Comment by darshankawar** [comment]
@thatsgolden 
If the flutter command line works properly but not via IDEs, then it might be related to the path or config that you need to re-check. 
You may try using `flutter config` command to see if it properly takes the path where your VSCode and AS are installed. 

Running `flutter config -h` gives below:

<img width="1336" alt="Screenshot 2024-12-02 at 1 39 21 PM" src="https://github.com/user-attachments/assets/71e73a1d-f5f2-43df-a5a4-44eadfda2d92">

And check if using above params helps in your case or not.

**Comment by thatsgolden** [comment]
@darshankawar 
 I restart my windows, still not work
![image](https://github.com/user-attachments/assets/1b0f2b00-5779-4bed-a270-78af6c098ac4)

**Comment by thatsgolden** [comment]
By the way, I'm use https://docs.flutter.dev/get-started/codelab tutorial to create the App.

**Comment by darshankawar** [comment]
@thatsgolden 
Can you try [this](https://codelabs.developers.google.com/codelabs/flutter-codelab-first#1) instead to check if it helps ?

**Comment by thatsgolden** [comment]
> @thatsgolden Can you try [this](https://codelabs.developers.google.com/codelabs/flutter-codelab-first#1) instead to check if it helps ?

Yes, I had tried, still not work.
1. [Flutter Docs](https://docs.flutter.dev/get-started/install), Windows+Android, Windows+Web, Windows+Desktop
2. [Google Codelabs](https://codelabs.developers.google.com/codelabs/flutter-codelab-first#1)

**Comment by darshankawar** [comment]
@thatsgolden You are most probably hitting https://github.com/flutter/flutter/issues/143625 so please follow-up in it for further updates. Also refer https://github.com/Dart-Code/Dart-Code/issues/1634.
Closing this as a duplicate.

**Comment by thatsgolden** [comment]
> Also refer [Dart-Code/Dart-Code#1634](https://github.com/Dart-Code/Dart-Code/issues/1634). Closing this as a duplicate.

Unfortunately, I tried this. It didn't work.

> You are most probably hitting #143625 so please follow-up in it for further updates

But seems like this issue, the same output, I will follow-up in it. Thanks~

![image](https://github.com/user-attachments/assets/6eeae3b3-9bc2-403b-97fa-26ec7402fba9)

**Comment by thatsgolden** [comment]
For others whos trapped in the same situation as me, this helps. [#4840#issuecomment-2215258127](https://github.com/Dart-Code/Dart-Code/issues/4840#issuecomment-2215258127)

Move other git installation down, let Git of cygwin64 be lower then other Git for Windows, my devices list shows.

![image](https://github.com/user-attachments/assets/90cfe375-fe85-4707-b280-958b11fdcd06)

![image](https://github.com/user-attachments/assets/d6a8de90-9d4c-4c9e-8742-3a4bb73a3d44)
