### ISSUE TITLE
[Impeller]Font weight could be changed according to the system font weight setting in HyperOS.

### ISSUE THREAD

**Issue by FridayAutum** [flutter/flutter#159654]
### Use case

Xiaomi HyperOS offers a system-level font weight adjustment function, yet this function doesn't work for Flutter applications. Currently, we are able to obtain the font weight modification multiplier and pass it into the engine (Impeller)simultaneously. However, we still haven't managed to locate a suitable place within the engine to make the modification. We aim to introduce a system-level value in the engine to adjust the font weight parameter, but up until now, we haven't discovered a sufficiently appropriate location (such as paragraph_builder.cc) for such a modification.
![1](https://github.com/user-attachments/assets/ecbbd158-014a-49af-81c5-13348140ef3e)
![2](https://github.com/user-attachments/assets/0e7de5d7-9969-4522-ab7c-f86e00c0f11f)
![3](https://github.com/user-attachments/assets/28dc97db-424e-4d38-a8dd-753e741424b2)
![4](https://github.com/user-attachments/assets/d9926ff4-ebb0-4aaf-83ea-cfb2b6c43123)

### Proposal

I'm eager to identify a proper location or approach to initiate the modification of the global font weight data within the engine.

**Comment by darshankawar** [comment]
@FridayAutum 
If I understand correctly, the font weight on HyperOS devices does not match or render properly per system's font weight ?
Could you reduce the use case to runnable details or concrete example that shows the reported use case ?
Also please check if https://github.com/flutter/flutter/issues/154166 is applicable or resembles your case or not.

**Comment by FridayAutum** [comment]
Our current need is to establish a global setting for the font weight multiplier within the system. However, the relevant configuration of the Flutter application is unable to detect this setting. Currently, we are able to pass such a multiplier to the Engine code via certain methods. Nevertheless, we are uncertain about where to utilize this data in order to modify the multiplier of the global font weight data.
An example is that I intercepted the "wght" field in the FontVaration processing logic(in paragraph_builder.cc), and then multiplied the obtained data by the multiple I passed in, so that the font weight of my application can be changed, but I hope to find a more appropriate place to process this logic so that it can take effect on all text.

**Comment by FridayAutum** [comment]
The example given above is a Java Android application，we hope that our Flutter app can also change according to the font weight configuration.

**Comment by darshankawar** [comment]
See if [this](https://github.com/flutter/flutter/issues/48381) resembles your case or not.

**Comment by FridayAutum** [comment]
This issue should be irrelevant to what I want to express.What I want to achieve is the same effect as shown in the following video.

I'm looking to locate a proper spot in the engine code to capture text font weight data and then process it, so as to achieve the effect of adjusting the font weight.

https://github.com/user-attachments/assets/2f662b23-98f7-48be-88cc-17cb869d7366

**Comment by kuku955** [comment]
Our focus is on modifying font weight specifically within the Android platform, a scenario distinctly different from that of MacOS. Importantly, this issue is entirely unrelated to font size. Once the system font weight is configured and we have accurately obtained the system's font weight scaling factor, our goal is to identify an appropriate moment to seamlessly adjust the font weight across all fonts within the Flutter application.

**Comment by FridayAutum** [comment]
We think it may not helps acturally.We hope that our changes can achieve the change of font weight without switching font files.

**Comment by jonahwilliams** [comment]
This isn't an Impeller feature, you can't just tell the engine about a font weight multiplier - the framework needs to know as well. We have some of these sorts of configurations in the framework media query which is provided via the embedders. i don't know what embedder hyper OS is using but that would be the appropriate place to provide it.

Closing as I don't believe this is actually a bug with flutter.
