### ISSUE TITLE
Scrolling down licenses takes a full minute, scrollbar shaking

### ISSUE THREAD

**Issue by frankkienl** [flutter/flutter#15967]
## Steps to Reproduce

(optional: grab a coffee)
1) Install Flutter Gallery, 
2) open the Hamburger menu, 
3) click 'About Flutter Gallery', 
4) click 'view licenses'.
5) Scroll to the bottom. 

What happens
- This [scrolling all the way down] take a full minute. (This is not the bug, there are just a LOT of licenses)
- The scrollbar is shaking up and down while scrolling down. (this might be a bug)

Video: 
https://youtu.be/zvbSB23gBfI

Not including logs and flutter doctor output here, because the app has been downloaded from the Google Play Store.

**Comment by zoechi** [comment]
Did you run in release mode?

**Comment by xster** [comment]
Seems like a sliver extent calculation issue

**Comment by knopp** [comment]
This gets actually way worse on iOS. Every time viewport extent estimation changes (which is often with uneven item size) the ballistic simulation is restarted, killing current momentum. Relevant #24715 and #11599

I think one of the possible fixes would be to get final position from simulation and then only restart the simulation if new extent is before, but even this would alleviate problem only partially, as the last fling might still be broken.

@xster, this is a major issue for us, and it affects pretty much every app where items are not same size. Do you have any idea what would the best way of addressing this be?

**Comment by VladyslavBondarenko** [comment]
Still persists. Flutter master v1.16.3-pre.56

**Comment by VladyslavBondarenko** [comment]
Closing current issue, please follow up on https://github.com/flutter/flutter/issues/25652
