### ISSUE TITLE
iOS app crashes when running on Apple Silicon Mac

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#159639]
### Steps to reproduce

1. An iOS app is build and published to the Apple App store
2. Users install it on Apple Silicone Mac device
3. We are receiving crash reports in Crashlytics from user's devices

I wasn't been able to reproduce this locally. There are references to PlatformViews in the code and the only platform view's in the app are from the `webview_flutter` iOS plugin.

The app is built using the current latest stable Flutter version. See the doctor output below.

### Expected results

The app should not crash when it is running on Apple Silicone Mac devices.

### Actual results

The crash seems to be coming from some FlutterEngine internals native code, e.g. EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000006d0  See logs below

### Code sample

<details open><summary>Code sample</summary>

```dart
N/A
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000006d0

0  Flutter                        0x11b28 -[FlutterEngine platformView] + 53 (weak_ptr.h:53)
1  Flutter                        0x11994 -[FlutterEngine updateViewportMetrics:] + 186 (ref_ptr.h:186)
2  Flutter                        0x1f854 -[FlutterViewController updateViewportMetricsIfNeeded] + 427 (vector:427)
3  Flutter                        0x1f9b8 -[FlutterViewController viewDidLayoutSubviews] + 1411 (FlutterViewController.mm:1411)
4  UIKitCore                      0x8c864 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2376
5  QuartzCore                     0x1fa0c CA::Layer::layout_if_needed(CA::Transaction*) + 516
6  QuartzCore                     0x1ae84c CA::Context::commit_transaction(CA::Transaction*, double, double*) + 516
7  QuartzCore                     0x2888 CA::Transaction::commit() + 648
8  AppKit                         0xb38848 __37+[NSDisplayCycle currentDisplayCycle]_block_invoke.7 + 44
9  AppKit                         0xb38c94 ___NSMainRunLoopPerformBlockInModes_block_invoke + 44
10 CoreFoundation                 0x7d8c0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
11 CoreFoundation                 0x7d7d0 __CFRunLoopDoBlocks + 356
12 CoreFoundation                 0x7cc00 __CFRunLoopRun + 2432
13 CoreFoundation                 0x7bbc4 CFRunLoopRunSpecific + 588
14 HIToolbox                      0x10bf64 RunCurrentEventLoopInMode + 292
15 HIToolbox                      0x111d54 ReceiveNextEventCommon + 636
16 HIToolbox                      0x111eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
17 AppKit                         0x3aa08 _DPSNextEvent + 660
18 AppKit                         0x97ae0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
19 AppKit                         0x24f680 -[NSApplication _shouldTerminate] + 1124
20 AppKit                         0x2427ec -[NSApplication terminate:] + 848
21 Foundation                     0x78fe8 __NSFireDelayedPerform + 372
22 CoreFoundation                 0x97824 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
23 CoreFoundation                 0x974c8 __CFRunLoopDoTimer + 1012
24 CoreFoundation                 0x96fd8 __CFRunLoopDoTimers + 356
25 CoreFoundation                 0x7c9c0 __CFRunLoopRun + 1856
26 CoreFoundation                 0x7bbc4 CFRunLoopRunSpecific + 588
27 HIToolbox                      0x10bf64 RunCurrentEventLoopInMode + 292
28 HIToolbox                      0x111d54 ReceiveNextEventCommon + 636
29 HIToolbox                      0x111eb8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
30 AppKit                         0x3aa08 _DPSNextEvent + 660
31 AppKit                         0x97ae0c -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
32 AppKit                         0x2dae0 -[NSApplication run] + 480
33 AppKit                         0x4364 NSApplicationMain + 888
34 AppKit                         0x252870 _NSApplicationMainWithInfoDictionary + 22
35 UIKitMacHelper                 0x4b38 UINSApplicationMain + 972
36 UIKitCore                      0x43a8 UIApplicationMain + 148
37 UIKitCore                      0x49e01c block_destroy_helper.23 + 11736
38 Runner                         0x872c main + 4369614636 (AppDelegate.swift:4369614636)
39 ???                            0x199e4c274 (Missing)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
> flutter doctor -v
[✓] Flutter (Channel stable, 3.24.5, on macOS 13.6.6 22G630 darwin-arm64, locale en-CA)
    • Flutter version 3.24.5 on channel stable at ***
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (2 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode_15.2.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 82.2.4
    • Dart plugin version 243.22562.3

[✓] Connected device (6 available)
    • macOS (desktop)                    • macos                                • darwin-arm64   • macOS 13.6.6 22G630 darwin-arm64
    • Mac Designed for iPad (desktop)    • mac-designed-for-ipad                • darwin         • macOS 13.6.6 22G630 darwin-arm64

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
@ekuleshov 
Based on the flutter frames, it might be similar to https://github.com/flutter/flutter/issues/98735 that you can check and confirm.

**Comment by darshankawar** [comment]
@ekuleshov Can you check [this](https://github.com/flutter/engine/blob/main/docs/Crashes.md#ios) to see if it helps to provide more meaningful logs ?

**Comment by darshankawar** [comment]
Thanks for the update. Keeping the issue open based on the report and for team's tracking.

**Comment by jmagman** [comment]
@cbracken any chance this is fixed https://github.com/flutter/engine/pull/56828?

**Comment by cbracken** [comment]
@jmagman my patch cleaned up `FlutterPlatformViewsController`; however, this is a case where we're looking up a `WeakPtr` to a C++ `PlatformView` (glue code between the engine and iOS embedder that paradoxically is unrelated to platform views). 

Looking at the stack trace:
```
0  Flutter                        0x11b28 -[FlutterEngine platformView] + 53 (weak_ptr.h:53)
1  Flutter                        0x11994 -[FlutterEngine updateViewportMetrics:] + 186 (ref_ptr.h:186)
2  Flutter                        0x1f854 -[FlutterViewController updateViewportMetricsIfNeeded] + 427 (vector:427)
3  Flutter                        0x1f9b8 -[FlutterViewController viewDidLayoutSubviews] + 1411 (FlutterViewController.mm:1411)
4  UIKitCore                      0x8c864 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2376
```

Top frame is `-[FlutterEngine platformView]`:
```objc
322 - (fml::WeakPtr<flutter::PlatformView>)platformView {
323   FML_DCHECK(_shell);
324   return _shell->GetPlatformView();
325 }
```

For reference, here's the definition of `Shell::GetPlatformView()`:
```cc
813 fml::WeakPtr<PlatformView> Shell::GetPlatformView() {
814   FML_DCHECK(is_set_up_);
815   return weak_platform_view_;
816 }
```
`weak_platform_view_` is here in `shell.h`:
```cc
469   fml::WeakPtr<PlatformView>
470       weak_platform_view_;  // to be shared across threads
```

The crash says we're blowing up on line 53 of `weak_ptr.h`:
```cc
46 template <typename T>
47 class WeakPtr {
48  public:
49   WeakPtr() : ptr_(nullptr) {}
50
51   // Copy constructor.
52   // NOLINTNEXTLINE(google-explicit-constructor)
53   WeakPtr(const WeakPtr<T>& r) = default;
```

So we're blowing up in the copy constructor, which means that the incoming `const WeakPtr& r` is garbage, which in our case is the field on `Shell`, which `FlutterEngine` owns via a `std::unique_ptr`:
```objc
151 @implementation FlutterEngine {
152   std::shared_ptr<flutter::ThreadHost> _threadHost;
153   std::unique_ptr<flutter::Shell> _shell;
```

Yes there's an `FML_DCHECK` on the line above this in the getter but that's a no-op in any non-unopt builds... so my guess is that we're getting the callback after `destroyContext` has been called but before the engine is dealloc'ed:
```objc
450 - (void)destroyContext {
451   [self resetChannels];
452   self.isolateId = nil;
453   _shell.reset();
454   _profiler.reset();
455   _threadHost.reset();
456   _platformViewsController = nil;
457 }
```

`destroyContext` is only ever called from `notifyViewControllerDeallocated` and triggers in `[FlutterViewController dealloc]`.

If I were to guess, this is a race condition where the Flutter view is being removed from the UI tree, the `FlutterView` and `FlutterViewController` are gone, but the engine hasn't yet been shut down and `[FlutterEngine dealloc]` hasn't yet been called. And in fact you can see lower in the stack trace we're in the middle of app shutdown:
```
20 AppKit                         0x2427ec -[NSApplication terminate:] + 848
```

Just at that moment, we're cleaning one last CoreAnimation transaction commit that's assumes things are still live, when in fact they're not. My guess is that `Shell::GetPlatformView` was inlined, which is why we're seeing the crash in the WeakPtr ctor and not on `shell_` dereference. There are a couple options here:
1. Add null checks before every use of `shell_` (and anything else we clean up in `destroyContext`.
2. Fix the shutdown process to set a flag preventing any future frames from being scheduled but allow any inflight frame to be processed, then shut down.

Of these two, option (1) is probably a lot simpler.

**Comment by cbracken** [comment]
I can send a patch tomorrow that should prevent this crash.

**Comment by ekuleshov** [comment]
> Sent [flutter/engine#57099](https://github.com/flutter/engine/pull/57099). Thanks for reporting @ekuleshov.

Appreciate the work. It was pleasure to read your analysis.

What are the chances of having this fix pushed/promoted into the next hotfix release or the next closest stable one?

**Comment by cbracken** [comment]
Will find out and get back to you. This patch will land after the cutoff for the upcoming stable release.

How frequently are you seeing this?

**Comment by ekuleshov** [comment]
> Will find out and get back to you. This patch will land after the cutoff for the upcoming stable release.
> 
> How frequently are you seeing this and what's the user impact? On iOS devices, I'd expect the crash on app termination to mostly go unnoticed by users, but curious -- are users getting crash dialogs on macOS?

About about 30 crashes in about a month time period and 15..20 users affected according to the Firebase Crashlytics reports for one of the apps.

**Comment by cbracken** [comment]
Thanks. Out of curiosity, are these mostly happening with iOS apps running on macOS, or are you also seeing the same crashes on iOS devices?

**Comment by ekuleshov** [comment]
@cbracken as far as I can see, those are only from iOS app running on Mac devices.

**Comment by cbracken** [comment]
Given that this primarily affects a pretty narrow usecase and primarily on app shutdown, and  I can see a similar bug from Feb 2022, with only 5 thumbs-up reactions in nearly 3 years, I suspect this is unlikely meet the bar for a cherry-pick.

Until then, if you need this patch, one option would be to temporarily build off `master` branch, then `beta` once we've cut the next beta, then `stable` once the next stable cut happens.
