### ISSUE TITLE
how to call a function using for loop in flutter ...mine is not working

### ISSUE THREAD

**Issue by ramaranjandey** [flutter/flutter#15961]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment]
This issue doesn't contain any information.
Can you please update or close?

**Comment by ramaranjandey** [comment]
i have defined a function which is returning a container inside a stateful class ... and want to render it on the screen for 5 times or more .... where to us for loop???
share your mail id i will send the code

**Comment by zoechi** [comment]
Issues are for bugs and feature requests.
I think this question should better be asked on StackOverflow. 
If you do ask on StackOverflow, please add the information what you try to accomplish, the code that demonstrates what you tried, and information about where you failed.

**Comment by xster** [comment]
From what I can piece together, if you want 5 Containers in a widget's build, depending on how you want them arranged, you can instantiate a [List](https://api.dartlang.org/stable/1.24.3/dart-core/List-class.html) of widgets (such as by using the [generate](https://api.dartlang.org/stable/1.24.3/dart-core/List/List.generate.html) factory or filling the List in the build() or anywhere else using any method you prefer), then use that list when constructing a Column or Row etc. 

Feel free to add more details to your question or add an example in stackoverflow.
