### ISSUE TITLE
Everything evaluated after system platfromBrightness changes

### ISSUE THREAD

**Issue by im-trisha** [flutter/flutter#159672]
### Steps to reproduce

I was trying to change the platformBrightness while I had my app open to test if my app router persisted, and doing so I noticed that the runApp function was run everytime I tried to change the system brightness.

I tried on 6 physical devices:

1. Samsung Galaxy A54 5g - A14
2. Samsung S23 Ultra - A14
3. Samsung A14 - A12
4. Xiaomi Redmi 11 Pro - crDroid 10.4, A14
5. Samsung Galaxy A52s - A14
6. OPPO A94 5G - ColorOS 13, A13

And the bug happened only on (3). I tought this was an OS/Custom rom issue, but opening another open source app ([WallYou](https://github.com/you-apps/WallYou/)) and changing the dark/light theme that didn't happen. The app continued functioning like normal.

I then tried other flutter apps i had in my phone ([Lichess mobilev2](https://github.com/lichess-org/mobile/), [Boorusphere](https://github.com/nullxception/boorusphere), and [Hype Banking](https://play.google.com/store/apps/details?id=it.hype.app&hl=it&firstTP=hype_home&lastTP=hype_home&pli=1) and more)

The issue happened on every Flutter app except the Hype app for some reason.

I then tried debugging further, and EVERYTHING WAS RUN AGAIN. Not just the runApp. Global variables were evaluated again, const, final, everything. The main was run again. It was like i launched the app again.

I wanted to attibute this as a ROM issue, but the fact that it doesn't happen on native apps makes this a flutter issue 

### Expected results

I expect the app to only rebuild widgets that are marked as dirty by a didChangeSystemBrightness (e.g. MaterialApp). Not the whole dart code to be run again

### Actual results

The dart code is run every time the platformBrightness changes. Creating black screens between each runApp call, and most importantly an unexpected, slow and buggy behavior

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const Bug());
}

class Bug extends StatelessWidget {
  const Bug({super.key});

  @override
  Widget build(BuildContext context) =>
      const MaterialApp(home: Scaffold(body: Text("Hello, World")));
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Video](https://github.com/user-attachments/assets/eca792a5-9f8c-43a3-ab92-95ddbb425e82)
</details>

### Logs

<details open><summary>Logs</summary>
Here are the logs, i run the app, change platformBrightness and then close the app from the device.
[flutter_run.log](https://github.com/user-attachments/files/17979203/flutter_run.log)
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console[✓] Flutter (Channel , 3.24.3, on Arch Linux 6.12.1-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.24.3 on channel  at /usr/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision archlinuxaur (unknown (arch linux aur package)), 2038-01-19 03:14:08
    • Engine revision 36335019a8ea
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.5+11)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.31.1
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (2 available)
    • 2201117TG (mobile) • 54ae7337 • android-arm64 • Android 14 (API 34)
    • Linux (desktop)    • linux    • linux-x64     • Arch Linux 6.12.1-arch1-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@im-trisha 
Can you provide exact steps to replicate upon running the code ? What do we need to do that shows the reported behavior ?

**Comment by im-trisha** [comment]
@darshankawar Hello, Unfortunately as I stated, it only happens in my phone + rom combination. I will try to create a ROM for an emulator and get back to you to make the issue more reproducible.

**Comment by moffatman** [comment]
It must be restarting the activity. reminds me of this https://github.com/flutter/flutter/issues/133722
wont' be easy to fix

**Comment by im-trisha** [comment]
Hello @moffatman, indeed it seems similar. However, nothing gets restarted on wallpaper change in my case

**Comment by darshankawar** [comment]
@im-trisha 
Can you try to listen to platform brightness changes using `platform.onPlatformBrightnessChanged` to see if gives more reference on the reported behavior ?

**Comment by im-trisha** [comment]
@darshankawar Hello, using `WidgetsBindingObserver.didPlatformBrightnessChange` and changing the brightness, indeed works correctly and gets called when i change the platform brightness. Is this all or did I understand incorrectly?

**Comment by darshankawar** [comment]
@im-trisha 
Does it mean the behavior you reported is now resolved per above implementaiton ? or still some open ends ?

**Comment by im-trisha** [comment]
@darshankawar Well my problem isn't that i can't detect platform changes, but that my app activity gets restarted after updating the platformBrightness

**Comment by darshankawar** [comment]
Ok, I see. I tried on S10+ device with the sample code provided but I couldn't replicate it. There's some setting in the device that might be affecting the behavior you are seeing such as `don't keep activities` which you can try to see if it helps in your case or not.

**Comment by im-trisha** [comment]
@darshankawar i don't have any strange settings enabled. As i stated, i don't think my device settings are the problem, when i try to change platform brightness on any flutter app, it gets restarted. if i do it on a native app, it doesn't get restarted

**Comment by moffatman** [comment]
There isn't any solution. It's a defect on Android in my opinion. Native apps which use Android Activity things properly might do better. But other apps will break too, like games I think.

**Comment by im-trisha** [comment]
@moffatman you.. are right? I have two games on my phone (clash of clans and dokkan battle) and they both get restarted after platform change? Could you elaborate further on what happens?

**Comment by im-trisha** [comment]
Like, what does flutter do in this regard that is different than what happens on native?

**Comment by moffatman** [comment]
https://stuff.mit.edu/afs/sipb/project/android/docs/guide/topics/resources/runtime-changes.html

different brands implement it differently. with different settings causing it

**Comment by im-trisha** [comment]
@moffatman hello, many thanks, that resolves the why only on my phone problem but... what does flutter and those game do differently than native apps that make this problem appear?

Thanks!

**Comment by moffatman** [comment]
flutter and games don't use the android activity system. so they dont have automatic save and restore.

**Comment by darshankawar** [comment]
@im-trisha See if [this](https://docs.flutter.dev/platform-integration/android/restore-state-android) helps in anyway in your case or not.
Per above conversation, it seems like it is undoable in Flutter.

**Comment by im-trisha** [comment]
@darshankawar well, it surely helps out a bit. 

@moffatman @darshankawar i want to thank you both for the support provided and the answers i was searching for!
