### ISSUE TITLE
Color.ToString() not working in release mode since 3.24.5 stable

### ISSUE THREAD

**Issue by Nimo11** [flutter/flutter#159686]
### Steps to reproduce

Use code below

### Expected results

Color.ToString() return Color(#0xff640a0a) in debug and also in release mode

### Actual results

Color.ToString() return
- in debug mode : **Color(#0xff640a0a)**
- but in release mode : **Instance of Color**

Problem found on ios and android, not on web.
For serialization function it's a problem.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    var c = Color.fromARGB(255, 100, 10, 10);
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text("Mode: ${kReleaseMode ? 'Release' : 'Debug'} \n" +
              c.toString() +
              "\n" +
              'Color(0x${c.value.toRadixString(16).padLeft(8, '0')})'),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20241202-205216](https://github.com/user-attachments/assets/02983c36-6da4-4f65-ab34-1f0c1308e847)

![Screenshot_20241202-205414](https://github.com/user-attachments/assets/226308c2-322c-4b49-9362-5ba4744b84a1)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [version 10.0.19045.5131], locale fr-FR)
    • Flutter version 3.24.5 on channel stable at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Users\info\Android\SDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = D:\Users\info\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java     
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35431.28
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.95.3)
    • VS Code at C:\Users\info\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[√] Connected device (4 available)
    • SM G960U1 (mobile) • 36344b3547413098 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [version 10.0.19045.5131]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 131.0.6778.86
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 131.0.2903.70

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate this on mobile and desktop platforms, whereas on web it works as expected in release mode:

<img width="656" alt="Screenshot 2024-12-03 at 3 40 34 PM" src="https://github.com/user-attachments/assets/2a0476b4-3a43-4048-9206-3eeb87526a6a">

I checked on 3.22.0 as well to see if this is a regression or not, but it shows same result as latest versions.  

@Nimo11 When you says 3.5.4, what and whose version are you referring to ?

```
stable : 3.24.5
master : 3.27.0-1.0.pre.682
```

**Comment by Nimo11** [comment]
Hello, thank you for your responsiveness, this is the stable version.

**Comment by darshankawar** [comment]
Which version it worked on earlier ?

**Comment by Nimo11** [comment]
I can’t say sorry.

**Comment by Nimo11** [comment]
I have the same problem with another type. For example AlignmentDirectional.centerEnd.toString() returns **AlignmentDirectional.centerEnd** in debug mode or Web and **Instance of AlignmentDirectional** in desktop release mode.

**Comment by darshankawar** [comment]
Please file a new issue for above behavior.

**Comment by Nimo11** [comment]
it's done #159791

**Comment by Flucadetena** [comment]
Same issue with the color, is there any "temp" solution that anyone has found out?

**Comment by Flucadetena** [comment]
Until all the updates hit the next version, I'm using the deprecated method ".value" and use it to generate a Hex value.
```
background.value.toRadixString(16)
```

In case anyone has the problem.

Also there is a discussion about the changes in Color here: https://github.com/flutter/flutter/issues/160184

**Comment by matanlurey** [comment]
toString methods are optimized out of the Flutter framework when building in profile and release modes.

See https://github.com/flutter/flutter/commit/7c89ec8bbc6da2b8c59d18615a2c31c5b404d77b

Closing as WAI.
