### ISSUE TITLE
Unable to make network request

### ISSUE THREAD

**Issue by HaloWang** [flutter/flutter#159647]
### Steps to reproduce

1. On a macbook
2. `flutter create test`.
3. write any network request.
4. run the app on iOS real device or macOS.
5. call network request.

### Expected results

Can get response

### Actual results

**Unhandled Exception: ClientException with SocketException**  
I encountered the following error on both macOS and iOS (real device):

```console
Unhandled Exception: ClientException with SocketException: Failed host lookup: 'www.baidu.com' (OS Error: nodename nor servname provided, or not known, errno = 8), uri=http://www.baidu.com
```

### Details:

1. I am an experienced Flutter developer with 3–4 years of experience in Flutter development.
2. I have two MacBooks:
   - **MacBook A**: This issue was initially reproducible, but after upgrading the macOS system, the problem disappeared.
   - **MacBook B**: The issue is still reproducible.
3. The following factors are consistent across both MacBooks:
   - Networking environment
   - iOS real device
   - Flutter version
   - Xcode version
   - macOS version
   - CocoaPods version
4. The issue does **not** occur when:
   - Running in **release mode**.
   - Selecting "Outgoing connections" in Xcode for the macOS project and then running the app.
   - Running in android / iPhone simulator
5. Steps I’ve tried (unsuccessfully):
   - Running `sudo find . -type f -exec xattr -d -r com.apple.quarantine {} \;` in the Flutter directory.
   - Restarting both the MacBook and the iPhone.
   - Upgrading macOS to "15.2 Beta (24C5089c)".
6. The issue remains unresolved, and I haven’t been able to identify the root cause or a definitive solution.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.favorite),
          onPressed: () async {
            final response = await get(Uri.parse('http://www.baidu.com'));
            print(response.body.length);
          },
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

[https://github.com/HaloWang/log-of-bug/blob/master/log.txt](https://github.com/HaloWang/log-of-bug/blob/master/log.txt)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.2 24C5089c darwin-arm64, locale en-CN)
    • Flutter version 3.24.5 on channel stable at /Users/wangce/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    • Android SDK at /Users/wangce/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (5 available)
    • Halo's iPad (mobile)            • 00008103-001911122160801E • ios            • iOS 17.7 21H16
    • Ce’s iPhone (mobile)            • 00008140-000641E02EDB001C • ios            • iOS 18.1 22B83
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.2 24C5089c darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.2 24C5089c darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by HaloWang** [comment]
Flutter 3.22.3 can not reproduce this bug. Same device!

**Comment by HaloWang** [comment]
Flutter 3.24.4 can not reproduce this bug. Same device!

**Comment by HaloWang** [comment]
After re-download flutter 3.24.5. I found that I can not reproduce this bug. It's really weird.

**Comment by darshankawar** [comment]
@HaloWang 
I tried running on macOS with different url which worked and didn't throw the reported error. I tried on latest stable and master.
Does above mean the issue is resolved and can be closed ?

**Comment by HaloWang** [comment]
Thanks. Let's close this issue.

**Comment by HaloWang** [comment]
Thanks. Let's close this issue.
