### ISSUE TITLE
CupertinoTabScaffold current index 

### ISSUE THREAD

**Issue by Asoseil** [flutter/flutter#15969]
CupertinoTabScaffold should support the current index using CupertinoTabBar value. 

How can I change current index on CupertinoTabScaffold?

**Comment by xster** [comment]
If you meant being able to programmatically change the currently open tab in the CupertinoTabScaffold, sounds like a reasonable feature request. Will add.

**Comment by Asoseil** [comment]
yes exactly, _CupertinoTabScaffoldState set _currentPage to 0 ignoring widget.tabBar.currentIndex that could be defined

**Comment by Asoseil** [comment]
@xster Could also be useful add a way to reset the currentTabIndex. I would like to reset the tab bar on the first index at user logout; Is there a way at now?

**Comment by xster** [comment]
I'm not sure if I understood the question. Isn't that possible by just rebuilding the CupertinoTabScaffold with currentTabIndex = 1?
