### ISSUE TITLE
video_player HLS plays on iOS but without sound

### ISSUE THREAD

**Issue by christianr11** [flutter/flutter#159607]
### Steps to reproduce

- Im using **video_player 2.9.2** and I tried playing .m3u8 like the example below.

https://vz-1505cdb4-0af.b-cdn.net/4029bcb6-f1e8-4606-a708-c811db0e1061/playlist.m3u8

I tested it on both Android and iOS, but on iOS, there was no sound.

- Then I tried using **media_kit 1.1.11**, and the video played correctly on iOS with sound. (same file .m3u8 above)

This is what the playlist.m3u8 looks like:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="96a",URI="audio/96a/audio.m3u8",NAME="Default"
#EXT-X-STREAM-INF:BANDWIDTH=600000,RESOLUTION=352x240,AUDIO="96a"
video/240p/video.m3u8

### Expected results

- The video should play with sound on both Android and iOS.

### Actual results

- Works correctly on Android (video and sound)
- No sound on iOS (only video plays)

### Code sample

<details open><summary>Code sample</summary>

```dart
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.networkUrl(Uri.parse(
        'https://vz-1505cdb4-0af.b-cdn.net/4029bcb6-f1e8-4606-a708-c811db0e1061/playlist.m3u8'))
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.4.1 23E224 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.95.3)
[✓] VS Code (version 1.85.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @christianr11, can you check if you're able to play the audio with a native iOS AVFoundation AVPlayer? That is what flutter uses under the hood for iOS video. You can use the swiftui sample code from https://github.com/flutter/flutter/issues/111457#issuecomment-1245424598 to test. I tested the sample with the url but the video does not play, so this is either an issue with the avplayer or an issue with your video. Can you confirm if you get the desired behavior with the swiftui sample?

**Comment by christianr11** [comment]
Hi @danagbemava-nc , I tested it with the SwiftUI sample from https://github.com/flutter/flutter/issues/111457#issuecomment-1245424598, the video plays but there's still no sound.

**Comment by danagbemava-nc** [comment]
Hi @christianr11, the unfortunately, this is not an issue with the flutter video_player plugin. It's either an issue with your video or a bug in `AVFoundation` player. The video_player plugin on iOS/macOS wraps around functionality from the native library so if it doesn't work with the native player as well, there's not much we can do to fix it. You may try reporting this on the apple forums to see anyone offers a solution but given that at this point, it doesn't work with the native video player either, I'll be closing this. 

Thank you
