### ISSUE TITLE
%5Btool_crash%5D RPCError

### ISSUE THREAD

**Issue by Thiararapeter** [flutter/flutter#159637]
## Command

```bash
flutter run
```

Steps to Reproduce
...
...
...

### Logs

RPCError

#30 new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:13:34)
#31 VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:3:25)

**Comment by Hamos66** [comment]
Hola cómo Feria 🎡
