### ISSUE TITLE
Release version on Stores crash until it is re-installed

### ISSUE THREAD

**Issue by BlueAgateSupport** [flutter/flutter#159732]
Good day,

I need some insight if possible please. If this is the wrong place to ask then please forgive me 😊

I am facing a very strange occurrence on the project that I am working on.

When I started on the project it was discovered that the code base wasn’t maintained and neither was SOLID principles implemented throughout. We did a whole lot of refactoring in the past months with some good results however, when we push to the stores(or test) we get users contacting support that they are unable to log in or the app hangs until the old app is removed on their device and the new one installed.

We have no idea where the problem can lie or where to start and thus my reason for asking for insight. Minimal caching is done locally (User tokens and some caching minutes).

We utilise packages like GetIt, Provider, Bloc, Freezed and periodically we update dependencies where possible. Our services are register during app config and the app runs perfectly fine during development. Periodically on our test tracks releases do testers have this issue as well for which we have no explanation. Any insight or advice would be greatly appreciated.

Thanks

**Comment by darshankawar** [comment]
@BlueAgateSupport 
I think your question is better suited for support channels like StackOverflow or Flutter's reddit help page. 
This repo is to track specific issues or feature requests only. If you would have provided a code sample, some crash logs that would have helped us to properly address the issue, but since you provided neither, I suggest you to raise this in support channels I mentioned.

Closing for now. If you get a concrete replication steps, crash log and possible code sample that shows a bug in framework, we would be happy to address it further.

**Comment by BlueAgateSupport** [comment]
> @BlueAgateSupport I think your question is better suited for support channels like StackOverflow or Flutter's reddit help page. This repo is to track specific issues or feature requests only. If you would have provided a code sample, some crash logs that would have helped us to properly address the issue, but since you provided neither, I suggest you to raise this in support channels I mentioned.
> 
> Closing for now. If you get a concrete replication steps, crash log and possible code sample that shows a bug in framework, we would be happy to address it further.

@darshankawar Thank you for the response and you are absolutely correct it is just that the issue was difficult to isolate due to not having control over this process. We have resolved the issue today and was not front end related (timing out of an external API call that was slow only on certain users). Apologies for the inconvenience.
