### ISSUE TITLE
can't login      google_sign_in

### ISSUE THREAD

**Issue by joon610** [flutter/flutter#15976]
problem:
     
i try login  but  occurrence of error
        
![default](https://user-images.githubusercontent.com/29224157/37979190-e90cefa4-3222-11e8-806c-021658974cc9.png)

message_codecs.dart
```
if (errorCode is String && (errorMessage == null || errorMessage is String) && !buffer.hasRemaining)
                                       <--- this point always break and fail login -->
      throw new PlatformException(code: errorCode, message: errorMessage, details: errorDetails);
                                                                   <------------->
    else
 throw const FormatException('Invalid envelope');
```

## Logs

PS C:\work\flutter\login> flutter run -d emulator-5554

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                1.1s
Resolving dependencies...                             1.9s
Running 'gradlew assembleDebug'...                   11.7s
Built build\app\outputs\apk\debug\app-debug.apk (26.5MB).
Installing build\app\outputs\apk\app.apk...           1.3s
Error: ADB exited with exit code 1
adb: failed to install build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
Uninstalling old version...
Installing build\app\outputs\apk\app.apk...           2.5s
I/FlutterActivityDelegate( 6514): onResume setting current activity to this
Syncing files to device Android SDK built for x86...  1.8s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8107/
For a more detailed help message, press "h". To quit, press "q".
D/EGL_emulation( 6514): eglMakeCurrent: 0x9fc055a0: ver 2 0 (tinfo 0x8c4a94a0)
I/FlutterActivityDelegate( 6514): onResume setting current activity to this
I/flutter ( 6514): can't login in google
D/EGL_emulation( 6514): eglMakeCurrent: 0x9fc055a0: ver 2 0 (tinfo 0x8c4a94a0)

run flutter analyze
PS C:\work\flutter\login> flutter analyze
Analyzing C:\work\flutter\login...
No issues found!
Ran in 6.0s

## Flutter Doctor
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.64], locale ko-KR)
    • Flutter version 0.1.5 at C:\git\flutter
    • Framework revision 3ea4d06340 (5 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\AndroidSDK\AppData\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\AndroidSDK\AppData
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554      • android-x86   • Android 7.1.1 (API 25) (emulator)
    • SM G935F                  • ce0516056c32430503 • android-arm64 • Android 7.0 (API 24))

     google_sign_in: "^3.0.0"
    installed  google-services.jason

**Comment by joon610** [comment]
i solved this problem.   it was debug.keystore probem~~~

**Comment by CyanBlob** [comment]
For anyone else confused about this, make sure that you add your SHA1/SHA256 fingerprints to your Firebase project (https://stackoverflow.com/questions/37273145/error-statusstatuscode-developer-error-resolution-null?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)  
Your fingerprint can be found via the command: `keytool -list -v -keystore <path/to/.android/debug.keystore> -alias androiddebugkey -storepass android -keypass android`  
On my system I replaced <path/to/.android/debug.keystore> with ~/.android/debug.keystore

**Comment by zoechi** [comment]
@joon610 I assume this can be closed then.

**Comment by jrparthkodala** [comment]
> I solved this problem. it was debug.keystore probem~~~

how you solved it?
