### ISSUE TITLE
Gallery App has Scrolling Techniques

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1597]
From https://www.google.com/design/spec/patterns/scrolling-techniques.html#

App bar

- [ ] The app bar can scroll off-screen with the content and return when the user reverse scrolls.
- [ ] The app bar can stay fixed at the top with content scrolling under it.

Tabs

- [ ] The tab bar stays anchored at the top, while the toolbar scrolls off.
- [ ] The app bar stays anchored at the top, with the content scrolling underneath.
- [ ] Both the toolbar and tab bar scroll off with content. The tab bar returns on reverse-scroll, and the toolbar returns on complete reverse scroll.

Flexible space (app bar)

- [ ] The flexible space shrinks until only the toolbar remains. The title shrinks to 20sp in the navigation bar. When scrolling to the top of the page, the flexible space and the title grow into place again.
- [ ] The whole app bar scrolls off. When the user reverse scrolls, the toolbar returns anchored to the top. When scrolling all the way back, the flexible space and the title grow into place again.
- [ ] With an image.

Flexible space with overlapping content

- [ ] The app bar’s starting position should be located behind the content. Upon upward scroll, the app bar should scroll faster than the content, until the content no longer overlaps it. Once anchored in place, the app bar lifts up to allow content to scroll underneath.

(We probably also want to show these in action, with some vignettes/showcases.)

**Comment by HansMuller** [comment]
The gallery home screen, the "Flexible space toolbar" demo ", and "Tabs" gallery demos cover these scrolling techniques.
