### ISSUE TITLE
[iOS] TextFormField sometimes cannot be focused

### ISSUE THREAD

**Issue by McK-95** [flutter/flutter#159771]
### Steps to reproduce

Note: I have only been able to make this happen on an iPad, Android devices appear to be fine.

1. Ensure there is code in the onTapOutside callback on the TextFormField, which causes the keyboard to close and unfocus the form field when tapping outside of it.
`TextFormField(
      decoration: const InputDecoration(hintText: 'Enter some text'),
      onTapOutside: (event) => FocusManager.instance.primaryFocus?.unfocus())`
2. On an iPad, continually tap on and around a TextFormField with four fingers at the same time to make it gain/regain focus.
3. The field will eventually freeze up and become unfocusable.

This also happens just by closing the keyboard **without** the code in the onTapOutside callback however it's much harder to reproduce.

### Expected results

The TextFormField shouldn't freeze and always be focusable.

### Actual results

Doing this continually will cause the keyboard to open/close and will eventually cause the TextFormField to freeze up and become unfocusable. There are no visible errors being displayed in the logs when this happens.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:test_text_form_field/text_form_field.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: SizedBox(width: 300, child: TestTextFormField()),
      ),
    );
  }
}

import 'package:flutter/material.dart';

class TestTextFormField extends StatelessWidget {
  const TestTextFormField({super.key});

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      decoration: const InputDecoration(hintText: 'Enter some text'),
      onTapOutside: (event) => FocusManager.instance.primaryFocus?.unfocus(),
    );
  }
}


```

</details>
``

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/444b5141-8616-4a9d-a7d6-7afbdb66997e

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@McK-95 Thanks for the report.
There's a similar [issue](https://github.com/flutter/flutter/issues/101067) open describing your case that you can check and confirm if it resembles your case or not.

**Comment by McK-95** [comment]
> @McK-95 Thanks for the report. There's a similar [issue](https://github.com/flutter/flutter/issues/101067) open describing your case that you can check and confirm if it resembles your case or not.

Thanks yes that looks like the same issue I am having

**Comment by darshankawar** [comment]
Thanks for confirming. I will close this in favor of it. Please follow-up in it for further updates. You may share your findings in that issue for better tracking.
