### ISSUE TITLE
[Suggestion about the site] Copy button in code snippets

### ISSUE THREAD

**Issue by jdamacena** [flutter/flutter#15978]
I would like to have a Copy button close to code snippets on the site, like we've seen in several site out there, it's great to copy easily, especialy those great Complete Examples.

**Comment by Sfshaza** [comment]
@InMatrix, a good suggestion for the new site.

**Comment by InMatrix** [comment]
Cc: @filiph it would be nice to implement this on flutter.io.

**Comment by Sfshaza** [comment]
@fertolg @chalin, would this be hard?

**Comment by chalin** [comment]
No. This is something that had come up during early dash discussions. @fertolg: is there a standard implementation used for other sites that we could use here too?

**Comment by InMatrix** [comment]
Cc: @gspencergoog DartDoc probably can use the same implementation for copying code snippets once the website has it.

**Comment by gspencergoog** [comment]
This is not hard.  "clipboard.js" is the magic package for this, and it's pretty trivial to hook up.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2397](https://github.com/flutter/website/issues/2397) via [**ZenHub**](https://www.zenhub.com/)
