### ISSUE TITLE
[APP OOM] When entering the secondary page from the home page of the APP，oom.

### ISSUE THREAD

**Issue by WangXiaoRi** [flutter/flutter#159711]
### Steps to reproduce

When entering the secondary page from the home page of the APP, even a simple green container will not trigger GC, which may lead to oom crash, and both Android and iOS platforms will appear.

### Expected results

no oom.

### Actual results

Low trigger frequency of garbage collection may cause oom.

### Code sample

<details open><summary>Code sample</summary>

```dart

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1407" alt="截屏2024-12-03 14 38 16" src="https://github.com/user-attachments/assets/9ed2869b-b9b3-4869-ba42-2562829f2353">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.95.3)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by WangXiaoRi** [comment]
dart::TimelineEventArguments::SetNumArguments(long)	
Dart_RecordTimelineEvent

I can't tell you the specific code, because even if the secondary page is an empty container, it will appear, but I found that using xcode's debugging tool to see flutter create a lot of Timeline-related objects caused the memory to skyrocket.

**Comment by danagbemava-nc** [comment]
Hi @WangXiaoRi, are you loading a lot of images in your application?

**Comment by WangXiaoRi** [comment]
> Hi @WangXiaoRi, are you loading a lot of images in your application?

Yes, it's a shopping mall APP with many pictures. I've tried to use resizeImage, but it's still oom in some models of mobile phones.

**Comment by danagbemava-nc** [comment]
Hi @WangXiaoRi, approximately, how many images are you loading when the app starts? Have you tried setting cacheWidget and cacheHeight for the images?

**Comment by WangXiaoRi** [comment]
> Hi @WangXiaoRi, approximately, how many images are you loading when the app starts? Have you tried setting cacheWidget and cacheHeight for the images?

The number of pictures shall not exceed one hundred. Yes, I have tried，but it's still oom in some models of mobile phones.

**Comment by danagbemava-nc** [comment]
Hi @WangXiaoRi, what values are you setting the cacheWidth & cacheHeight to? What versions of android are these devices running and how much ram do they have? Can you share the list of devices they are crashing on?
