### ISSUE TITLE
ListTile padding render issue

### ISSUE THREAD

**Issue by Camden031** [flutter/flutter#159716]
### Steps to reproduce

1. Create a list using ListTiles.
2. Make sure to give the ListTile contentPadding.
3. The list must load dynamically when you navigate to the page with the list.
4. You should notice when the page loads initially the padding on some of the ListTiles will not render correctly causing text to overflow outside if the ListTile in weird ways.
5. If you scroll on this page or simply move the page up and down the issue corrects itself and then renders correctly.

![large-Image_01](https://github.com/user-attachments/assets/f1b87c5d-f95a-487f-b5d3-93bb61ae5981)

### Expected results

The expected result should be as shown in the image attached: Basically the text inside the ListTiles should be aligned correctly.

![WhatsApp Image 2024-12-03 at 12 36 42_834ec37f](https://github.com/user-attachments/assets/b97e8a50-bef0-4635-b5ad-8eceff74e1f8)

### Actual results

When the page opens the ListTile is not rendering correctly at first. The text inside the ListTile will be missaligned and sometimes overflow outside of the ListTile. When you scroll or move up and down on the page it will correct itself. Please see video attached:

https://github.com/user-attachments/assets/0bc7436b-23bf-47d5-90f6-df6cfefbe1c4

### Code sample

<details open><summary>Code sample</summary>

```dart
Padding(
      padding: const EdgeInsets.only(bottom: 5),
      child: ListTile(
        onTap: (){
          controller.toggleCheck();
          if (onClick != null) {
            onClick!(id, title, controller!.getChecked());
          }
        },
        contentPadding: const EdgeInsets.fromLTRB(8, 6, 20, 6),
        horizontalTitleGap: 10,
        tileColor: Colors.white,
        leading: Checkbox(
          value: controller.getChecked(),
          onChanged: (p0) {
            controller.setChecked(p0!);
            if (onClick != null) {
              onClick!(id, title, p0);
            }
          },
        ),
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            CustomText(
              content: title ?? '',
              color: Colors.black,
              fontWeight: FontWeight.w500,
              fontSize: 16,
            ),
            CustomText(content: desc ?? '', fontSize: 12,),
          ],
        ),
      ),
    );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![large-Image_01](https://github.com/user-attachments/assets/acb37f60-95c3-4f5c-a8a1-d7a86f839d75)
![WhatsApp Image 2024-12-03 at 12 36 42_834ec37f](https://github.com/user-attachments/assets/d59324ab-de56-46c6-a0af-7ebf3d993f7d)

https://github.com/user-attachments/assets/cb74b648-be5b-471f-8eb4-790564eb40d1

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Camden031, please provide a complete minimal reproducible code sample so that we can properly investigate this.
Please also provide the output of `flutter doctor -v`

Side note: Why are you using a Column in your title? If you want to have a subtitle in your `ListTile` you can use `subTitle` property of the `ListTile`.

**Comment by Camden031** [comment]
> Hi @Camden031, please provide a complete minimal reproducible code sample so that we can properly investigate this.
> Please also provide the output of `flutter doctor -v`
> 
> Side note: Why are you using a Column in your title? If you want to have a subtitle in your `ListTile` you can use `subTitle` property of the `ListTile`. 

Thank you, I will provide a sample code. I will remove the column and try with the subtitle instead just to make sure it's not that causing it.
