### ISSUE TITLE
Flutter Gallery - Animation error, back from item in Shrine, regression

### ISSUE THREAD

**Issue by frankkienl** [flutter/flutter#15971]
When pressing back from an item in Shrine, there is an animation error.
This animation happens in the 'new' version of Flutter Gallery (with .demo. in the packagename) and not in the old version. (Both on the Google Play Store)

## Steps to Reproduce

1) Install Flutter Gallery from Google Play Store 
(the new one, with .demo. in the packagename)
2) Click Shrine
3) Click on a Shopping Item (I clicked on the clock)
4) Press back.
The animation back to the list of shopping items is not smooth.
In the old version, it was smooth.

Video:
Video shows old version first, then new version.
https://youtu.be/0o14RWzDDgc

Device: Samsung Galaxy Note 8

No logs or flutter doctor output, because apps are from the Play Store.

**Comment by frankkienl** [comment]
I've made a little discovery, if you set the UI-mode to iOS first, then the animation works correctly.

**Comment by zoechi** [comment]
Are you still seeing this? I don't have a SGN8 at hand.

**Comment by bitfactory-frank-bouwens** [comment]
No, the animation is smooth in the latest version. 👍 
https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&rdid=io.flutter.demo.gallery
