### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by iamgap23** [flutter/flutter#159793]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM

**Comment by danagbemava-nc** [comment]
Hi @iamgap23, please share the full crash log so that we can properly investigate this. 

Thank you
