### ISSUE TITLE
Material card margin is too small

### ISSUE THREAD

**Issue by robertoscaramuzzi** [flutter/flutter#15977]
Material specs say (https://material.io/guidelines/components/cards.html#cards-content-blocks)

```
Card margins on mobile

Padding from edge of screen to card: 8dp
Space between cards: 8dp
```

But Flutter has a 4 point margin: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/card.dart#L88

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
I believe that the 4dp margin was to ensure that adjacent cards would be separated by 8dp.

If we were going to change this, I think it would be best to leave padding out of the Cards widget. It's easy enough to add back. Intrinsic padding is often inconvenient.

**Comment by Hixie** [comment]
Can we default to 4.0px but make it customizable by adding a `margin` argument?

**Comment by HansMuller** [comment]
Sure, will do.
