### ISSUE TITLE
Asset images directory problem in web

### ISSUE THREAD

**Issue by DagmawiIsaiah** [flutter/flutter#159788]
If an asset image in located at "assets/images/logo.png" and when testing in web the asset images won't be found since it automatically add the assets folder automatically so it becomes "assets/assets/images/logo.png" so if make it Image.asset("images/logo.png") it fixes it but in the built site the same thing happens it needs the full path therefor have to be Image.asset("assets/images/logo.png") please fix it

**Comment by danagbemava-nc** [comment]
This is a known issue which is being tracked in https://github.com/flutter/flutter/issues/86833

Kindly follow up in the original issue for updates

Closing from here 

Thank you
