### ISSUE TITLE
SystemInput plugin crash on android

### ISSUE THREAD

**Issue by andra1eu** [flutter/flutter#15985]
E/FlutterView( 9814): Failed to create input connection
E/FlutterView( 9814): org.json.JSONException: Value TextInputType.emailAddress at inputType of type java.lang.String cannot be converted to JSONObject
E/FlutterView( 9814): 	at org.json.JSON.typeMismatch(JSON.java:100)
E/FlutterView( 9814): 	at org.json.JSONObject.getJSONObject(JSONObject.java:613)
E/FlutterView( 9814): 	at io.flutter.plugin.editing.TextInputPlugin.createInputConnection(TextInputPlugin.java:129)
E/FlutterView( 9814): 	at io.flutter.view.FlutterView.onCreateInputConnection(FlutterView.java:371)
E/FlutterView( 9814): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1200)
E/FlutterView( 9814): 	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1142)
E/FlutterView( 9814): 	at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:199)
E/FlutterView( 9814): 	at io.flutter.plugin.editing.TextInputPlugin.onMethodCall(TextInputPlugin.java:67)
E/FlutterView( 9814): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/FlutterView( 9814): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/FlutterView( 9814): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterView( 9814): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/FlutterView( 9814): 	at android.os.Looper.loop(Looper.java:136)
E/FlutterView( 9814): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/FlutterView( 9814): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterView( 9814): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/FlutterView( 9814): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by HansMuller** [comment]
I'm seeing this as well. Tapping on any textfield in the Flutter gallery will generate these Java exceptions..

**Comment by andra1eu** [comment]
Only on master branch. I've switched to dev and I'm ok.

**Comment by jason-simmons** [comment]
Looks like this is related to a pending change to add some new keyboard types.

The engine side of the change is in master (https://github.com/flutter/engine/commit/7fa08b3ba94cb32cf0a2f466e5ee5d539d144705) but the matching framework change has not yet landed (https://github.com/flutter/flutter/pull/15846)

@sbaranov can you merge the framework PR?

**Comment by sbaranov** [comment]
The change is now landed.
