### ISSUE TITLE
App crashed when i click on video shutter button

### ISSUE THREAD

**Issue by FlutterDevCelebaze** [flutter/flutter#159875]
### Steps to reproduce

choose pick video from. camera and  start video when you click on to shutter button to stop the video then app crashed.

### Expected results

ImageFile

### Actual results

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.Long)' on a null object reference
E/AndroidRuntime(14640): 	at com.android.camera.VideoModule.saveVideo(VideoModule.java:1263)
E/AndroidRuntime(14640): 	at com.android.camera.VideoModule.stopVideoRecording(VideoModule.java:1513)
E/AndroidRuntime(14640): 	at com.android.camera.VideoModule.onStopVideoRecording(VideoModule.java:656)
E/AndroidRuntime(14640): 	at com.android.camera.VideoModule.onShutterButtonClick(VideoModule.java:697)
E/AndroidRuntime(14640): 	at com.android.camera.ShutterButton.performClick(ShutterButton.java:190)
E/AndroidRuntime(14640): 	at android.view.View.performClickInternal(View.java:7636)
E/AndroidRuntime(14640): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
E/AndroidRuntime(14640): 	at android.view.View$PerformClick.run(View.java:30156)
E/AndroidRuntime(14640): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(14640): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14640): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(14640): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(14640): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(14640): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14640): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(14640): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

### Code sample

<details open><summary>Code sample</summary>

  ImagePicker picker = ImagePicker();
                                        XFile? file = await picker.pickVideo(
                                          source: ImageSource.camera,
                                        );

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.Long)' on a null object reference
E/AndroidRuntime(14640): 	at com.android.camera.VideoModule.saveVideo(VideoModule.java:1263)
E/AndroidRuntime(14640): 	at com.android.camera.VideoModule.stopVideoRecording(VideoModule.java:1513)
E/AndroidRuntime(14640): 	at com.android.camera.VideoModule.onStopVideoRecording(VideoModule.java:656)
E/AndroidRuntime(14640): 	at com.android.camera.VideoModule.onShutterButtonClick(VideoModule.java:697)
E/AndroidRuntime(14640): 	at com.android.camera.ShutterButton.performClick(ShutterButton.java:190)
E/AndroidRuntime(14640): 	at android.view.View.performClickInternal(View.java:7636)
E/AndroidRuntime(14640): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
E/AndroidRuntime(14640): 	at android.view.View$PerformClick.run(View.java:30156)
E/AndroidRuntime(14640): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(14640): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14640): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(14640): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(14640): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(14640): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14640): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(14640): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
This is similar to https://github.com/flutter/flutter/issues/118443. It seems to appear on emulator only (https://github.com/flutter/flutter/issues/118443#issuecomment-1384287020). More generally, the crash occurs outside the scope of the package, please check https://github.com/flutter/flutter/issues/118443#issuecomment-1454881242.

Closing this as it's not an issue with image_picker package.
