### ISSUE TITLE
firebase_database plugin not working with Android Studio 3.1

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#15986]
Including the `firebase_database` plugin to the `pubspec.yaml` with Android Studio 3.1 gives the following error
```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/KG/Developer/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 194

* What went wrong:
A problem occurred configuring project ':firebase_database'.
> Could not find method debugProvided() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

## Steps to Reproduce
- Have Android Studio 3.1 installed 
- `flutter create` a new project
-  Add ` firebase_database: "^0.4.1"` to the pubspec.yaml
- `flutter packages get`
- `flutter build apk` 
- See above error

## Logs
No issues reported 

## Flutter Doctor
```
[✓] Flutter (Channel master, v0.2.5-pre.46, on Mac OS X 10.12.6 16G1212, locale en-US)
    • Flutter version 0.2.5-pre.46 at /Users/KG/Developer/Flutter/flutter
    • Framework revision e59651f925 (53 minutes ago), 2018-03-27 10:38:20 -0700
    • Engine revision dd6f46c485
    • Dart version 2.0.0-dev.41.0.flutter-2f68e82526

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0RC2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.10.0
```

**Comment by xster** [comment]
cc @collinjackson

**Comment by KevinTheGray** [comment]
I was trying to debug the issue and forked the plugin repository.  In the end, I found that putting this in the pubspec.yaml

```
firebase_database:
      git:
        path: ./packages/firebase_database/
        url: git://github.com/flutter/plugins.git
        version: "^0.4.1"
```
instead of 
`firebase_database: "^0.4.1"`

will prevent the error, and then I can build and run the app.

`firebase_database: "^0.4.1"` will consistently cause the error to happen.  @xster @collinjackson any ideas on why this would be?

**Comment by zoechi** [comment]
Have you tried `flutter clean`?
I have experienced it frequently after such updates that changes don't take effect without `flutter clean`

**Comment by KevinTheGray** [comment]
@zoechi the only reason I don't think it's a `flutter clean` issue is because this can be reproduced with a fresh `flutter create` and adding the dependency there and building.

but also to be sure, I did a `flutter clean` in the project and still see the error

**Comment by joon610** [comment]
i soled it  just i did turn off and on Vscode...   and then work it..

**Comment by zoechi** [comment]
Sorry for not being able to come back to this issue earlier.
Is this still an issue with recent Flutter and plugin version?

**Comment by KevinTheGray** [comment]
@zoechi I'm actually not sure when/how this eventually got fixed, but i think it's good now.  feel free to close and i'll re-open if I see it again

**Comment by zoechi** [comment]
Sounds great. Thanks for the feedback!
