### ISSUE TITLE
[Impeller]Flutter applications(backend:impeller) use a lot of memory when they are moved to the background.

### ISSUE THREAD

**Issue by FridayAutum** [flutter/flutter#159821]
### Steps to reproduce

Use wonderous-app as example.
![image](https://github.com/user-attachments/assets/95eeaa37-dc16-4ae0-889c-2a045a807df4)
The above figure shows the memory usage of the application in the foreground and after it goes to the background. I found that compared with Java Android applications, the memory occupied by Flutter applications after going to the background is relatively high, only slightly lower than when it is in the foreground. Is this by design? Is there anything that can be optimized?

### Code sample

<details open><summary>Code sample</summary>

Use wonderous-app as example(using impeller as backend)

</details>

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

Xiaomi 15 Pro Qcom Snapdragon 8 elite
HyperOS 2.0(Android)

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Logs

<details open><summary>Logs</summary>

```console
foreground
 mi@Redmi-Book  ~  adb shell dumpsys meminfo com.gskinner.flutter.wonders |grep "PSS"
           TOTAL PSS:   266802            TOTAL RSS:   428164       TOTAL SWAP PSS:    13233
background
 mi@Redmi-Book  ~  adb shell dumpsys meminfo com.gskinner.flutter.wonders |grep "PSS"
           TOTAL PSS:   244294            TOTAL RSS:   405724       TOTAL SWAP PSS:    13185

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.27.0-1.0.pre.599, on Ubuntu 24.04.1 LTS 6.8.0-49-generic, locale zh_CN.UTF-8)
    ! Flutter version 3.27.0-1.0.pre.599 on channel [user-branch] at /home/mi/workspace/devkit/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 728cedc62a (13 天前), 2024-11-21 21:40:11 +0100
    • Engine revision d1a08064e1
    • Dart version 3.7.0 (build 3.7.0-164.0.dev)
    • DevTools version 2.41.0-dev.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/mi/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /home/mi/Android/Sdk
    • Java binary at: /home/mi/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2024.2)
    • Android Studio at /home/mi/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin version 81.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at /home/mi/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.98.0

[✓] Connected device (3 available)
    • 2410DPN6CC (mobile) • 3df54007 • android-arm64  • Android 15 (API 35)
    • Linux (desktop)     • linux    • linux-x64      • Ubuntu 24.04.1 LTS 6.8.0-49-generic
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 131.0.6778.108

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by jonahwilliams** [comment]
The wonderous application decodes a large number of high resolution images. These are kept resident by the application logic, as decoding them is expensive. I'd expect that in general Flutter will use more memory but I don't think you can comapre wonderous to any java or kotlin applications and expect generalization.

**Comment by FridayAutum** [comment]
If we aim to release these resources upon the app's exit to the background (while disregarding other potential impacts), what actions can we take?

**Comment by darshankawar** [comment]
@FridayAutum Is there a way to provide us minimal code sample that shows the reported behavior ?

**Comment by FridayAutum** [comment]
`import 'package:flutter/material.dart';


class PictureSlidePage extends StatefulWidget {
  PictureSlidePage({Key? key}) : super(key: key);

  @override
  _PictureSlidePageState createState() => _PictureSlidePageState();
}

class _PictureSlidePageState extends State<PictureSlidePage> {
  @override
  void didChangeDependencies() {
    var height = MediaQuery.of(context).size.width / 10;
    var width = height;
    for (var index = 0; index < 10; index++) {
      precacheImage(
        Image.asset(
          GridRotareItem.getImage(index),
          height: height,
          width: width,
          cacheHeight: height.floor(),
          cacheWidth: width.floor(),
          fit: BoxFit.cover,
        ).image,
        context,
      );
    }
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GridView.builder(
        itemCount: 200,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 10,
        ),
        itemBuilder: (context, index) {
          var animateIndex = index % 3;
          if (animateIndex == 0) {
            return GridRotareItem(index: index);
          }
          if (animateIndex == 1) {
            return GridFadeItem(index: index);
          }
          return GridScaleItem(index: index);
        },
      ),
    );
  }
}

class GridRotareItem extends StatefulWidget {
  final int index;

  const GridRotareItem({Key? key, required this.index}) : super(key: key);

  @override
  _GridRotareItemState createState() => _GridRotareItemState();

  static String getImage(int index) {
    var url = 'assets/images/${index % 20}.jpeg';
    return url;
  }
}

class _GridRotareItemState extends State<GridRotareItem>
    with SingleTickerProviderStateMixin {
  late AnimationController animationController;
  late double height;
  late double width;

  @override
  void initState() {
    super.initState();
    animationController = AnimationController(
      vsync: this,
      duration: Duration(seconds: 5),
    );
    animationController.repeat(reverse: true);
  }

  @override
  void didChangeDependencies() {
    height = MediaQuery.of(context).size.width / 10;
    width = height;
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return RotationTransition(
      turns: Tween(begin: 0.0, end: 1.0).animate(animationController),
      child: Image.asset(
        GridRotareItem.getImage(widget.index),
        height: height,
        width: width,
        cacheHeight: height.floor(),
        cacheWidth: width.floor(),
        fit: BoxFit.cover,
      ),
    );
  }
}

class GridFadeItem extends StatefulWidget {
  final int index;

  const GridFadeItem({Key? key, required this.index}) : super(key: key);

  @override
  _GridFadeItemState createState() => _GridFadeItemState();

  static String getImage(int index) {
    var url = 'assets/images/${index % 20}.jpeg';
    return url;
  }
}

class _GridFadeItemState extends State<GridFadeItem>
    with SingleTickerProviderStateMixin {
  late AnimationController animationController;
  late double height;
  late double width;

  @override
  void initState() {
    super.initState();
    animationController = AnimationController(
      vsync: this,
      duration: Duration(seconds: 5),
    );
    animationController.repeat();
  }

  @override
  void didChangeDependencies() {
    height = MediaQuery.of(context).size.width / 10;
    width = height;
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FadeTransition(
      opacity: Tween(begin: 0.0, end: 1.0).animate(animationController),
      child: Image.asset(
        GridFadeItem.getImage(widget.index),
        height: height,
        width: width,
        cacheHeight: height.floor(),
        cacheWidth: width.floor(),
        fit: BoxFit.cover,
      ),
    );
  }
}

class GridScaleItem extends StatefulWidget {
  final int index;

  const GridScaleItem({Key? key, required this.index}) : super(key: key);

  @override
  _GridScaleItemState createState() => _GridScaleItemState();

  static String getImage(int index) {
    var url = 'assets/images/${index % 20}.jpeg';
    return url;
  }
}

class _GridScaleItemState extends State<GridScaleItem>
    with SingleTickerProviderStateMixin {
  late AnimationController animationController;
  late double height;
  late double width;

  @override
  void initState() {
    super.initState();
    animationController = AnimationController(
      vsync: this,
      duration: Duration(seconds: 5),
    );
    animationController.repeat();
  }

  @override
  void didChangeDependencies() {
    height = MediaQuery.of(context).size.width / 10;
    width = height;
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ScaleTransition(
      scale: Tween(begin: 0.0, end: 1.0).animate(animationController),
      child: Image.asset(
        GridScaleItem.getImage(widget.index),
        height: width,
        width: height,
        cacheHeight: height.floor(),
        cacheWidth: width.floor(),
        fit: BoxFit.cover,
      ),
    );
  }
}`

**Comment by FridayAutum** [comment]
import 'package:flutter/material.dart';
import 'dart:math';

class LineSlidePage extends StatefulWidget {
  @override
  _LineSlidePageState createState() => _LineSlidePageState();
}

class _LineSlidePageState extends State<LineSlidePage> {
  int _currentIndex = 0;
  final List<Widget> _pages = [
    HomePage(),
    SettingsPage(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _pages[_currentIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        onTap: (index) {
          setState(() {
            _currentIndex = index;
          });
        },
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: 1000,
      itemBuilder: (context, index) {
        return Container(
          margin: EdgeInsets.all(9),
          child: CustomPaint(
            painter: RandomLinePainter(),
            child: Container(),
          ),
        );
      },
    );
  }
}

class RandomLinePainter extends CustomPainter {
  final Random _random = Random();

  @override
  void paint(Canvas canvas, Size size) {
    // 设置画笔属性
    final Paint paint = Paint()
      ..color = Colors.black
      ..strokeWidth = 2.0;

    // 随机生成线条数量
    int lineCount = _random.nextInt(5) + 1;

    for (int i = 0; i < lineCount; i++) {
      // 随机生成起点和终点坐标
      double startX = _random.nextDouble() * size.width;
      double startY = _random.nextDouble() * size.height;
      double endX = _random.nextDouble() * size.width;
      double endY = _random.nextDouble() * size.height;

      // 绘制线条
      canvas.drawLine(
        Offset(startX, startY),
        Offset(endX, endY),
        paint,
      );
    }
  }

  @override
  bool shouldRepaint(covariant RandomLinePainter oldDelegate) {
    return false;
  }
}
class SettingsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Settings Page'),
    );
  }
}

**Comment by FridayAutum** [comment]
<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:math';

class LineSlidePage extends StatefulWidget {
  @override
  _LineSlidePageState createState() => _LineSlidePageState();
}

class _LineSlidePageState extends State<LineSlidePage> {
  int _currentIndex = 0;
  final List<Widget> _pages = [
    HomePage(),
    SettingsPage(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _pages[_currentIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        onTap: (index) {
          setState(() {
            _currentIndex = index;
          });
        },
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'Home',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: 1000,
      itemBuilder: (context, index) {
        return Container(
          margin: EdgeInsets.all(9),
          child: CustomPaint(
            painter: RandomLinePainter(),
            child: Container(),
          ),
        );
      },
    );
  }
}

class RandomLinePainter extends CustomPainter {
  final Random _random = Random();

  @override
  void paint(Canvas canvas, Size size) {
    // 设置画笔属性
    final Paint paint = Paint()
      ..color = Colors.black
      ..strokeWidth = 2.0;

    // 随机生成线条数量
    int lineCount = _random.nextInt(5) + 1;

    for (int i = 0; i < lineCount; i++) {
      // 随机生成起点和终点坐标
      double startX = _random.nextDouble() * size.width;
      double startY = _random.nextDouble() * size.height;
      double endX = _random.nextDouble() * size.width;
      double endY = _random.nextDouble() * size.height;

      // 绘制线条
      canvas.drawLine(
        Offset(startX, startY),
        Offset(endX, endY),
        paint,
      );
    }
  }

  @override
  bool shouldRepaint(covariant RandomLinePainter oldDelegate) {
    return false;
  }
}
class SettingsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('Settings Page'),
    );
  }
}

```

</details>

**Comment by darshankawar** [comment]
Thanks for the code @FridayAutum 
Can you also provide us the memory dump for above code for the device you are running on ? I tried on S10+ device with and without impeller, but not getting any spike in memory usage.

**Comment by FridayAutum** [comment]
**foreground**
![CZO4S13ElK](https://github.com/user-attachments/assets/248ff477-6735-493d-a827-3e30eaa02487)
**background**
![bWliwlRgHY](https://github.com/user-attachments/assets/f513bf14-671e-4d5d-9437-a6fd5a95cb89)

**Comment by darshankawar** [comment]
@FridayAutum 
Please check [this](https://github.com/flutter/flutter/issues/128191) issue with underlying comments to see if they help in your case or not.
