### ISSUE TITLE
ListView doesn't autoscroll when keyboards appears

### ISSUE THREAD

**Issue by Galahand** [flutter/flutter#15983]
## Steps to Reproduce
I was using a ListView on my project to make a Signin Form but when there is an InputField at the bottom of the screen the keyboard, overlaps it, i checked the gallery demo and it also happens there.

The screen resizes but it has to be manually scrolled.

![image](https://user-images.githubusercontent.com/11549714/37984861-a5735d64-31b4-11e8-9cc7-452179673793.png)

![image](https://user-images.githubusercontent.com/11549714/37984890-b0e5f742-31b4-11e8-81a8-36c0484dec38.png)

**Comment by eseidelGoogle** [comment]
I think this is https://github.com/flutter/flutter/issues/10826 ?  Please re-open if you disagree!

**Comment by hovanhung98hust** [comment]
you just add ScrollController for listview. This work for me
