### ISSUE TITLE
Gallery App has Navigational transitions

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1598]
From https://www.google.com/design/spec/patterns/navigational-transitions.html#

- [x] Parent to child
- [x] Sibling to sibling

**Comment by sethladd** [comment]
Example of "sibling to sibling" is at "Selection controls".

I couldn't find an example of "parent to child".

**Comment by abarth** [comment]
In the grid demo when you go back from viewing one of the tiles.

**Comment by sethladd** [comment]
Good call! Thanks for the tip.
