### ISSUE TITLE
anchor is not working on web

### ISSUE THREAD

**Issue by dennymoradiya** [flutter/flutter#159873]
### Use case

anchor is not working on web

___________ Code ________________

 ```
Marker newMarker = Marker(
          markerId: MarkerId(currentPoint.toString()),
          position: LatLng(currentPoint.latitude, currentPoint.longitude),
          anchor: const Offset(0.5, 0.0),
          icon: await Transform.rotate(
              angle: rotation * (pi / 180),
              child: Image(
                image: AssetImage(
                  Assets.png.map.arrowIcon.path,
                ),
                height: 15,
                width: 15,
              )).toBitmapDescriptor(),
        );
```
____________________________________

### Proposal

anchor is not working on web
<img width="553" alt="Screenshot 2024-12-06 at 11 10 50 AM" src="https://github.com/user-attachments/assets/b446a81d-21cc-4215-b92b-c5c922abc893">

**Comment by darshankawar** [comment]
@dennymoradiya 
Are you using a custom anchor ? Can you check if your issue is same as https://github.com/flutter/flutter/issues/80578 or not ?

**Comment by darshankawar** [comment]
Closing as duplicate.
