### ISSUE TITLE
macOS 15.1.1, XCode 16.1: Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle

### ISSUE THREAD

**Issue by txthinking** [flutter/flutter#159825]
### Steps to reproduce

Recently I found that macOS can run normally with flutter run -d macos . However, when uploading to the AppStore, the above error occurs. The minimal reproducible method is:

1. `flutter create test`
2. `cd test`
3. `open macos/Runner.xcworkspace/` and fill all necessary signing, bundle id. Of course, I can confirm that there is no problem with this step.
4. `flutter pub add url_launcher`, add a dep, actually all other deps such as shared_preferences all will be failed
5. `flutter run -d macos`, it works
6. `flutter build macos`
7. In XCode, Product - Archive - Distribute App - App Store Connect - Distribute
    error: Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle

### Expected results

upload to App Store Connect success

### Actual results

Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle

### Code sample

<details open><summary>Code sample</summary>

```dart
Please see the Steps to reproduce, that is minimal reproducible
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.24.5 on channel stable at /Users/xxx/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] Connected device (5 available)
    • Pixel 3 (mobile)                • xxx                 • android-arm64  • Android 12 (API 31)
    • iPhone (mobile)    • xxx • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.108

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by txthinking** [comment]
Thanks for your quick reply.

```
	error: Asset validation failed
Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle shared_preferences_foundation_privacy [com.xxx.pkg/Payload/X.app/Contents/Frameworks/shared_preferences_foundation.framework/Versions/A/Resources/shared_preferences_foundation_privacy.bundle] property list file. (ID: X)
```

If your versions in flutter doctor same with mine exactly, it may something other thing different not show in doctor

**Comment by darshankawar** [comment]
I will keep the issue open based on the reported error above for team's input.
I found a reference of same issue in apple forum : https://forums.developer.apple.com/forums/thread/749481

**Comment by jmagman** [comment]
Can you attach the Info.plist after `flutter build macos --release`?  It will be in 
`build/macos/Build/Products/Release/test.app/Contents/Frameworks/url_launcher_macos.framework/Versions/A/Resources/url_launcher_macos_privacy.bundle/Contents/Info.plist`

Also does upgrading to CocoaPods 1.16.2 fix it?  Wondering if this line impacts it 
https://github.com/CocoaPods/Xcodeproj/commit/3157b7c087e215e89ce839edd04e5ff0dd120a5a#diff-29289dc6f82ba9c9455cec05b2f7033bfa62746c89352ba2d0a5cefc9fcc803cR4

**Comment by txthinking** [comment]
Sure.

> Can you attach the Info.plist after `flutter build macos --release`? It will be in `build/macos/Build/Products/Release/test.app/Contents/Frameworks/url_launcher_macos.framework/Versions/A/Resources/url_launcher_macos_privacy.bundle/Contents/Info.plist`
> 

<details>
<summary>Info.plist</summary>
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>24B91</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>url_launcher_macos_privacy</string>
	<key>CFBundleIdentifier</key>
	<string>org.cocoapods.url-launcher-macos-privacy</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>url_launcher_macos_privacy</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>24B75</string>
	<key>DTPlatformName</key>
	<string>macosx</string>
	<key>DTPlatformVersion</key>
	<string>15.1</string>
	<key>DTSDKBuild</key>
	<string>24B75</string>
	<key>DTSDKName</key>
	<string>macosx15.1</string>
	<key>DTXcode</key>
	<string>1610</string>
	<key>DTXcodeBuild</key>
	<string>16B40</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.14</string>
</dict>
</plist>
```
</details>

> Also does upgrading to CocoaPods 1.16.2 fix it? Wondering if this line impacts it [CocoaPods/Xcodeproj@3157b7c#diff-29289dc6f82ba9c9455cec05b2f7033bfa62746c89352ba2d0a5cefc9fcc803cR4](https://github.com/CocoaPods/Xcodeproj/commit/3157b7c087e215e89ce839edd04e5ff0dd120a5a#diff-29289dc6f82ba9c9455cec05b2f7033bfa62746c89352ba2d0a5cefc9fcc803cR4)

Yes, fixed

The reason is it will generate and overwrite Info.plist when build release
