### ISSUE TITLE
[!] Flutter (Channel stable, 0.0.0-unknown, on Microsoft Windows [版本 10.0.22631.4460], locale zh-CN)     ! Flutter version 0.0.0-unknown on channel stable at D:\flutter       Cannot resolve current version, possibly due to local changes.       Reinstall Flutter by following instructions at https://flutter.dev/setup.     ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL [√] Windows Version (Installed version of Windows is version 10 or higher) [X] Android toolchain - develop for Android devices     X Unable to locate Android SDK.       Install Android Studio from: https://developer.android.com/studio/index.html       On first launch it will assist you in installing the Android SDK components.       (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).       If the Android SDK has been installed to a custom location, please use       `flutter config --android-sdk` to update to that location.

### ISSUE THREAD

**Issue by 427719101** [flutter/flutter#159822]
### Steps to reproduce

[!] Flutter (Channel stable, 0.0.0-unknown, on Microsoft Windows [版本 10.0.22631.4460], locale zh-CN)
    ! Flutter version 0.0.0-unknown on channel stable at D:\flutter
      Cannot resolve current version, possibly due to local changes.
      Reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

### Actual results

[!] Flutter (Channel stable, 0.0.0-unknown, on Microsoft Windows [版本 10.0.22631.4460], locale zh-CN)
    ! Flutter version 0.0.0-unknown on channel stable at D:\flutter
      Cannot resolve current version, possibly due to local changes.
      Reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL
[√] Windows Version (Installed version of Windows is version 10 or higher)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @427719101, how did you install flutter? Did you follow the steps in https://docs.flutter.dev/get-started/install/windows/desktop? 

Have you modified your local installation? 

Do you have git installed on your system?

**Comment by MisaGu** [comment]
Same here on mac book air 
running `flutter pub get`, resulting in 
```The current Flutter SDK version is 0.0.0-unknown.```

pub get complains that any of the installed plugins are compatible with version 0.0.0-uknown

**Comment by MisaGu** [comment]
> Hi @427719101, how did you install flutter? Did you follow the steps in https://docs.flutter.dev/get-started/install/windows/desktop?
> 
> Have you modified your local installation?
> 
> Do you have git installed on your system?

@danagbemava-nc  The problem is probably on the Flutter Git side. When I add this Flutter version to Android Studio in the settings, it tries to fetch the necessary information, such as the channel and version, from Git. However, it somehow returns 0.0.0 as the version and an unknown channel.

**Comment by MisaGu** [comment]
I also received a notification today in Android Studio:

> Support for v2.10.3 of the Flutter SDK will be removed in an upcoming release of the Flutter plugin. Consider updating to a more recent Flutter SDK.

Could this somehow be related? Is it possible that this affects the Git integration or the version fetching process?

**Comment by danagbemava-nc** [comment]
Hi @MisaGu, what version of git do you have installed on your system? What is your default terminal shell?

**Comment by MisaGu** [comment]
Hi @danagbemava-nc 
`gir version 2.39.3 (Apple Git-146)`

Default terminal shell is `zch`

**Comment by MisaGu** [comment]
@danagbemava-nc  There was no changes made from my side, I just run the build script and the issue just occur and it's there since then (( 
The flutter version is:
`2.10.3`
As I mentioned above, Im thinking the issue is somehow related the the latest update to flutter IDE plugin, as it happens as soon as the plugin display the note, that it will no longer support flutter 2 sdk

**Comment by danagbemava-nc** [comment]
Are you still using flutter 2.10.3? If so, kindly upgrade to the latest version of flutter stable.

FWIW: The error you're getting is likely related to the git directory in your flutter directory. The IDE plugin does not modify the flutter source and this error is directly from the flutter tooling
