### ISSUE TITLE
Create a new flutter app project, and an error will be reported when running, Error resolving plugin [id: 'dev.flutter.flutter-plugin-loader', version: '1.0.0']

### ISSUE THREAD

**Issue by yoer** [flutter/flutter#159883]
### Steps to reproduce

1. upgrade Flutter version 3.24.5
2. new flutter project by android studio
3. run

### Expected results

run normal

### Actual results

Launching lib/main.dart on sdk gphone arm64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/yoer/workspace/sources/1122/flutter/untitled1/android/settings.gradle' line: 21

* What went wrong:
Error resolving plugin [id: 'dev.flutter.flutter-plugin-loader', version: '1.0.0']
> Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by settings file 'settings.gradle'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 442ms
Error: Gradle task assembleDebug failed with exit code 1

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.0 23A344 darwin-arm64, locale en-CN)
    • Flutter version 3.24.5 on channel stable at /Users/yoer/workspace/sources/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yoer/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/yoer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • sdk gphone arm64 (mobile)       • emulator-5554             • android-arm64  • Android 11 (API 30) (emulator)
    • ejunyue (mobile)                • 00008101-00020C423CD2001E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.109
    ! Error: Browsing on the local area network for iPhone (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Adam 的iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone (3). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone14pm. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by iperfectapp** [comment]
遇到一样的问题了 same question

**Comment by yoer** [comment]
> 遇到一样的问题了 same question

都弄疯了，新建项目都这样，运行旧项目就正常
It's all going crazy. Even new projects are like this, but running old projects is normal.

**Comment by iperfectapp** [comment]
https://stackoverflow.com/questions/69163511/build-was-configured-to-prefer-settings-repositories-over-project-repositories-b

**Comment by yoer** [comment]
> https://stackoverflow.com/questions/69163511/build-was-configured-to-prefer-settings-repositories-over-project-repositories-b

not work

**Comment by darshankawar** [comment]
@yoer 
What's the AGP and gradle version does the project use ?
If you create a new project from terminal / command line, doe it still show the reported error ?

**Comment by yoer** [comment]
- **android/gradle/wrapper/gradle-wrapper.properties:**
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip


- **android/build.gradle:**
``` gradle
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```

- **android/app/build.gradle**:
```gradle
plugins {
    id "com.android.application"
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

android {
    namespace = "com.example.untitled2"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.untitled2"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}

```

**Comment by yoer** [comment]
> If you create a new project from terminal / command line, doe it still show the reported error ?

No, creating a project from the command line still fails.

```shell

yoer@yoerdeMacBook-Pro 1122 % flutter create test
Found saved certificate choice "Apple Development: yanjun yue (9V96X972N6)". To clear, use "flutter config".
Developer identity "Apple Development: --- (------)" selected for iOS code signing
Creating project test...
Resolving dependencies in `test`... (16.6s)
Downloading packages...
Got dependencies in `test`.
Wrote 129 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd test
  $ flutter run

Your application code is in test/lib/main.dart.

yoer@yoerdeMacBook-Pro 1122 % cd test
yoer@yoerdeMacBook-Pro test % flutter pub get
Resolving dependencies...
Downloading packages...
  async 2.11.0 (2.12.0 available)
  boolean_selector 2.1.1 (2.1.2 available)
  characters 1.3.0 (1.3.1 available)
  clock 1.1.1 (1.1.2 available)
  collection 1.18.0 (1.19.1 available)
  fake_async 1.3.1 (1.3.2 available)
  flutter_lints 4.0.0 (5.0.0 available)
  leak_tracker 10.0.5 (10.0.8 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.9 available)
  lints 4.0.0 (5.1.0 available)
  matcher 0.12.16+1 (0.12.17 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  path 1.9.0 (1.9.1 available)
  stack_trace 1.11.1 (1.12.0 available)
  string_scanner 1.2.0 (1.4.0 available)
  test_api 0.7.2 (0.7.4 available)
  vm_service 14.2.5 (15.0.0 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
yoer@yoerdeMacBook-Pro test % flutter run
Connected devices:
RMX3511 (mobile)                • 0H52919V3710247C      • android-arm64  • Android 12 (API 31)
HMA L29 (mobile)                • HJS5T18C21004561      • android-arm64  • Android 10 (API 29)
macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.0 23A344 darwin-arm64
Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.109

Checking for wireless devices...

[1]: RMX3511 (0H52919---247C)
[2]: HMA L29 (HJS5T18---04561)
[3]: macOS (macos)
[4]: Mac Designed for iPad (mac-designed-for-ipad)
[5]: Chrome (chrome)
Please choose one (or "q" to quit): 2
Launching lib/main.dart on HMA L29 in debug mode...

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/yoer/workspace/sources/1122/test/android/settings.gradle' line: 20

* What went wrong:
**Error resolving plugin [id: 'dev.flutter.flutter-plugin-loader', version: '1.0.0']**
> Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by settings file 'settings.gradle'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                              3.4s
Error: Gradle task assembleDebug failed with exit code 1
yoer@yoerdeMacBook-Pro test %
```

**Comment by yoer** [comment]
it's a very troublesome problem. 
the same newly created project can be run by another colleague, but it fails to run by me.
the flutter/android studio versions are all the same

**Comment by zanderpu** [comment]
I'm having the same problem and don't know how to fix it

**Comment by darshankawar** [comment]
@yoer 
Can you provide `android/settings.gradle` file ?

**Comment by yoer** [comment]
> @yoer Can you provide `android/settings.gradle` file ?

android/settings.gradle:
```gradle
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.1.0" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}

include ":app"

```

**Comment by darshankawar** [comment]
I also have same file as above after creating new flutter project but didn't get the reported error.
Based on the report, I will keep the issue open for team's tracking.

**Comment by yoer** [comment]
Yes, the same project works on my colleague's mac, but it doesn't work on me.
After comparing my and his flutter/android studio/java versions, they are all consistent.

**Comment by yoer** [comment]
> I also have same file as above after creating new flutter project but didn't get the reported error. Based on the report, I will keep the issue open for team's tracking.

thanks a lot

**Comment by lipuliang** [comment]
I had the same problem, and even the downgrade didn't work. Have we solved it now

**Comment by yoer** [comment]
> I had the same problem, and even the downgrade didn't work. Have we solved it now

not yet

**Comment by ChanryLimmy** [comment]
btw, i could easily run the project created by flutter 3.10.3 on my device (Android 15 (API 35) (emulator)).


and all the things above could run on browser and desktop, including the project created by flutter 3.10.3   3.24.5  and 3.27.0.

**Comment by dalugm** [comment]
Please check whether you have personal gradle configuration in `~/.gradle/init.gradle` or somewhere else.

I met the same problem yesterday, after delete it everything works fine...

**Comment by autoantwort** [comment]
I don't have a `~/.gradle/init.gradle` file but still get the error :/

**Comment by yoer** [comment]
![image](https://github.com/user-attachments/assets/96b70b9d-a70a-4dfb-acfe-d341b9445635)
There is no such file

**Comment by dalugm** [comment]
Does delete `~/.gradle` fix this? (I reinstalled flutter 3.27.1 and delete `~/.gradle` completely, it also works fine)

Before delete, please backup important files in it.

**Comment by zanderpu** [comment]
> Please check whether you have personal gradle configuration in or somewhere else.`~/.gradle/init.gradle`
> 
> I met the same problem yesterday, after delete it everything works fine...

According to your method, delete/. gradle/init.gradle from the user folder under user and restore it. Thank you

**Comment by yoer** [comment]
> Does delete `~/.gradle` fix this? (I reinstalled flutter 3.27.1 and delete `~/.gradle` completely, it also works fine)
> 
> Before delete, please backup important files in it.
> 
> My env is
> 
> ```
> [✓] Flutter (Channel stable, 3.27.1, on Arch Linux 6.12.3-zen1-1-zen, locale en_US.UTF-8)
> [✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
> [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> [✓] Linux toolchain - develop for Linux desktop
> [✓] Android Studio (version 2024.2)
> [✓] IntelliJ IDEA Community Edition (version 2024.3)
> [✓] Connected device (2 available)
> [✓] Network resources
> ```
> 
> 1. delete `~/flutter` and `~/.gradle` completely (backup important files first!)
> 2. download flutter-3.27.1.tar.xz and untar
> 3. add flutter to PATH
> 4. flutter create demo && cd demo && flutter run

![image](https://github.com/user-attachments/assets/71672654-2a48-4a44-8a77-14b9a3d4a383)

still error

**Comment by yoer** [comment]
> Please check whether you have personal gradle configuration in `~/.gradle/init.gradle` or somewhere else.
> 
> I met the same problem yesterday, after delete it everything works fine...

delete/. gradle/init.gradle from the user folder under user and restore it. Thank you

**Comment by dalugm** [comment]
> still error

Perhaps you have personal gradle configuration somewhere else.

From your console output, you're downloading gradle7.3, while flutter 3.27 is using gradle8.3 now.

I'm not a flutter expert, let's hope someone can help...

---

> delete/. gradle/init.gradle from the user folder under user and restore it. Thank you

Well... you're welcome 😄
