### ISSUE TITLE
how to fix text auto scale

### ISSUE THREAD

**Issue by cryuhy** [flutter/flutter#159841]
### Steps to reproduce

Text(
                      info.getSubTitle(),
                      style: TextStyle(
                        fontSize: 14,
                        fontFamily: "PingFang SC",
                        color: CityColors.light.description,
                      ).setPingFang(),
                      overflow: TextOverflow.ellipsis,
                      maxLines: 1,
                    ) 
when i set fontfamily i will see text auto scale at the end of the line
![IMG_0068](https://github.com/user-attachments/assets/0a1b7393-d223-45dd-840d-20d3f7328778)
you can see mark by yellow line this text is not the same fontSize

### Actual results

not the same fontSize

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by cryuhy** [comment]
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.6.1 23G93 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.79.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for chenrui. Ensure the device
      is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

**Comment by darshankawar** [comment]
@cryuhy 
Your issue is better suited for support channels like Stackoverflow, so please ask the same there.
Closing from here, as this seems more of a code implementation support question rather than a bug. If you disagree, write in comments and I'll reopen it.
