### ISSUE TITLE
Gallery App has Bidirectionality

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1599]
From https://www.google.com/design/spec/usability/bidirectionality.html#
- [ ] LTR to RTL
- [ ] Navigational buttons

**Comment by abarth** [comment]
Blocked on https://github.com/flutter/flutter/issues/2598

**Comment by Hixie** [comment]
So this is technically possible now, but to do a real job we'd need to translate all the strings in the app to an RTL language, which seems excessive and hard to maintain. I propose that we close this without fixing it.

**Comment by Hixie** [comment]
Closing per comment above.
