### ISSUE TITLE
[ios] A thin wrapper for C++ APIs in iOS embedder

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#159988]
### Use case

Currently the iOS embedder is in ObjC++ (`.mm` rather than `.m`), because the engine API is in C++. However, many iOS developers (including myself) are not comfortable working with ObjC++. 

### Proposal

Create a thin wrapper around engine APIs, so that the rest of the iOS embedder can be written in pure ObjC (`.m` files). 

Need to watch out for performance impact of additional wrapper call though, but I suspect it can be minimal.

**Comment by jonahwilliams** [comment]
Hey, I don't we should do this as most of the engine APIs and implementations are already C++. Wrappers have low value here

**Comment by cbracken** [comment]
Agreed. All shared cross-platform utility code (FML etc.) and the core engine is currently C++ and we make heavy use of it for threading, graphics (both Skia and Impeller), engine-interop, etc.

In the engine-facing bits of the embedder, there's no avoiding C++. The iOS-facing parts of the embedder are Objective-C, since that provides the best interop with the rest of the embedder.

Apple has already started releasing some SDKs as Swift-only, and I can imagine a day when it may be that we need to add support for Swift. In such as case though we'd be adding new code in Swift where necessary. I don't think there's much value in rewriting existing code.

**Comment by hellohuanlin** [comment]
> All shared cross-platform utility code (FML etc.) and the core engine is currently C++ and we make heavy use of it for threading, graphics (both Skia and Impeller), engine-interop, etc.

Ya those are the code that I was not familiar with and wanted to get rid of (by wrapping it). But i guess that would be lots of overhead to wrap them all.

**Comment by loic-sharma** [comment]
The engine's embedder API is a C API. In theory, once the iOS embedder moves to the embedder API, we'd be able to reduce our usage of Objective-C++.

That being said, the macOS embedder - which does use the embedder API - still uses Objective-C++ extensively... So maybe not?

**Comment by hellohuanlin** [comment]
> The engine's embedder API is a C API. In theory, once the iOS embedder moves to the embedder API, we'd be able to reduce our usage of Objective-C++.

> That being said, the macOS embedder - which does use the embedder API - still uses Objective-C++ extensively... So maybe not?

I think a large part of it is the types that the engine expects (e.g. Skia types, vectors, maps).

**Comment by loic-sharma** [comment]
> > The engine's embedder API is a C API. In theory, once the iOS embedder moves to the embedder API, we'd be able to reduce our usage of Objective-C++.
> 
> > That being said, the macOS embedder - which does use the embedder API - still uses Objective-C++ extensively... So maybe not?
> 
> I think a large part of it is the types that the engine expects (e.g. Skia types, vectors, maps).

The embedder API introduces wrapper types in C for _everything_. It avoids things like vectors and maps.

There is significant C++ logic in [`//flutter/shell/platform/common/`](https://github.com/flutter/engine/tree/main/shell/platform/common). Perhaps this is why macOS uses Objective-C++ so much? If so, introducing a thin-wrapper for this layer might allow us to reduce our Objective-C++.

**Comment by cbracken** [comment]
re: [//flutter/shell/platform/common/](https://github.com/flutter/engine/tree/main/shell/platform/common):

I'm all for sharing code across embedders where possible and C++ is the best option we have for that across our embedders; it's not perfect, but better than maintaining duplicate implementations of shared logic.

When it comes to language choice, the important thing is that Runner-facing APIs fit on the platform they service: Obj-C/Swift on Apple platforms, Java on Android, C (with a friendly C++ wrapper around them for Windows/Linux), but we've got that today.
