### ISSUE TITLE
The GL proc resolver's glGetString(GL_VERSION) failed

### ISSUE THREAD

**Issue by 18611429192** [flutter/flutter#159963]
### Steps to reproduce

1. git clone https://github.com/flutter/flutter.git
2. flutter channel stable
3. change to another floder 
4. flutter create hello_world
5. flutter build linux
6. flutter doctor
```
[root@bogon ~]# flutter doctor
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on kylin 10 (Azalea) 4.19.90-23.28.v2101.ky10.aarch64, locale zh_CN.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 4 categories.
```
 

### Expected results

When I run an example, I encounter an error, [FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(76)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed. 

I searched for this problem and found that it always occurs in Nvidia, but I don't use it. My graphics card model is as follows.

```
[root@bogon ~]# lspci | grep VGA
04:00.0 VGA compatible controller: Jingjia Microelectronics Co Ltd JM7200 Series GPU (rev 01)
```

### Actual results

[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(76)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@18611429192 
I think your issue is similar to https://github.com/flutter/flutter/issues/85460. You may share your findings that it also occurs without nvidia card. 
Closing this as a duplicate.
