### ISSUE TITLE
Autosubmit fails with HTTP 400 error "GraphQL mutate failed"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#159916]
`auto label is removed for flutter/flutter/159079, Failed to enqueue flutter/flutter/159079 with HTTP 400: GraphQL mutate failed.`

https://github.com/flutter/flutter/pull/159079#issuecomment-2524645870

**Comment by christopherfujino** [comment]
@yjbanov do you think this could be a monorepo-related regression?

**Comment by christopherfujino** [comment]
Btw, this was on a release branch, so the bug might be that Cocoon assumes that the merge queue applies to all branches (but it does not apply to release branches currently).

**Comment by yjbanov** [comment]
This is MQ-related, and by extension, related to the monorepo project. I'll need to look into it.

**Comment by yjbanov** [comment]
Your hypothesis about Cocoon applying the MQ rules to all branches sounds very reasonable.

**Comment by christopherfujino** [comment]
> Your hypothesis about Cocoon applying the MQ rules to all branches sounds very reasonable.

It was actually your hypothesis :)

**Comment by christopherfujino** [comment]
@yjbanov btw, this is actually pretty severe. I thought anyone on the release team could manually merge to get around this, but actually only admins can. Until this is fixed, a GitHub admin will need to manually merge every release PR.

**Comment by yjbanov** [comment]
Gotcha. Looking into it now.
