### ISSUE TITLE
Google Maps - Mouse wheel zoom support on iOS apps (and in particular when running on MacOS)

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#159936]
### Use case

When running an iOS app on MacOS the mouse wheel does not zoom the map? It also appears not to work on Mouse with iPad too.

### Proposal

Is there a way to support the mouse wheel?

**Comment by darshankawar** [comment]
@zambetpentru 


> It also appears not to work on Mouse with iPad too.

I can imagine this use case, ie running maps on physical ipad and trying to use mouse to navigate and for zooming in and out, but I am not too sure about running ios app on macOS ? Are you saying running maps on macOS desktop ? 



> Is there a way to support the mouse wheel?

Currently I don't see any similar / related issues for this. Do you by any chance know if native maps supports mouse wheel ?

**Comment by zambetpentru** [comment]
Greetings, the use case is that on M1 macs iOS apps can run natively so that is where our users encountered the scenario using the Google maps package.

**Comment by darshankawar** [comment]
> on Native Google Maps on IPad the mouse wheel does not zoom. And unlike Android there are no zoom buttons at the side.

See [this](https://github.com/flutter/flutter/issues/140741#issuecomment-1872353642) for further reference.

**Comment by zambetpentru** [comment]
I was able to implement this using a Listener widget around the Google Maps and detect the scroll event.
