### ISSUE TITLE
ListTile don't show leading icons

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#159989]
### Steps to reproduce

```  Dart
ListView.separated(
                      shrinkWrap:
                          true, // Shrink wrap the ListView to its content
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      itemCount: folders.length,
                      itemBuilder: (context, index) {
                        final folder = folders[index];
                        return Card(
                          elevation: 2,
                          margin: const EdgeInsets.symmetric(vertical: 8.0),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(8.0),
                          ),
                          child: ListTile(
                            leading: const Icon(
                              CupertinoIcons.folder,
                              color: CupertinoColors.activeBlue,
                            ),
                            title: Text(folder),
                            trailing: IconButton(
                              icon: const Icon(
                                CupertinoIcons.delete,
                                color: CupertinoColors.destructiveRed,
                              ),
                              onPressed: () async {
                                var watchFoldersNotifier =
                                    ref.read(watchFoldersProvider.notifier);
                                await watchFoldersNotifier
                                    .removeWatchFolers(folder);
                              },
                            ),
                          ),
                        );
                      },
                      separatorBuilder: (context, index) =>
                          const SizedBox(height: 4),
                    )
``` 

<img width="1440" alt="Screenshot 2024-12-09 at 19 59 21" src="https://github.com/user-attachments/assets/afc5ae6a-ed80-474c-ba24-c2caccc118a8">

### Expected results

icons has been replace by `?`  

### Actual results

I expect the icons to appear

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
The icons are showing just fine here. Are you sure you have `cupertino_icons` package in your `pubspec.yaml`? If you do, please provide the version and also the output of `flutter doctor -v`. 

Thank you 

<img width="912" alt="Screenshot 2024-12-10 at 7 41 10 AM" src="https://github.com/user-attachments/assets/f180b0b3-5cd8-4818-abf6-153fe06916e2">

**Comment by stephane-archer** [comment]
I didn't had it, but the compiler or the IDE should have complained about it, right ?

**Comment by danagbemava-nc** [comment]
The `CupertinoIcons` class is from the framework but the icon fonts are from the package. This is similar to how if you use a font you haven't included in your assets file, it defaults to a fallback font. This is the fallback icon for if an icon is not found. 

There is an issue tracking warning the user if a font package is missing in https://github.com/flutter/flutter/issues/139778. You may follow up there for updates. 

Closing from here. 

Thank you
