### ISSUE TITLE
Cannot find executable for ...\android-arm-profile\windows-x64\gen_snapshot

### ISSUE THREAD

**Issue by osorito** [flutter/flutter#15998]
## Steps to Reproduce
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\lib\main.dart --output-file C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\build\app\intermediates\flutter\debug/app.flx --depfile C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --snapshot C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\build\app\intermediates\flutter\debug/snapshot_blob.bin --working-dir C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\build\app\intermediates\flutter\debug/flutter_assets

## exception

ArgumentError: Invalid argument(s): Cannot find executable for C:\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      runCommand (package:flutter_tools/src/base/process.dart:115)
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:133)
<asynchronous suspension>
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:53)
#5      Snapshotter._build (package:flutter_tools/src/base/build.dart:209)
<asynchronous suspension>
#6      Snapshotter.buildScriptSnapshot (package:flutter_tools/src/base/build.dart:174)
<asynchronous suspension>
#7      build (package:flutter_tools/src/flx.dart:62)
<asynchronous suspension>
#8      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:50)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     new Future.sync (dart:async/future.dart:222)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1126)
#21     _CustomZone.run (dart:async/zone.dart:1023)
#22     runZoned (dart:async/zone.dart:1501)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#26     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[!] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    â€¢ Flutter version 0.2.3 at C:\flutter
    â€¢ Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    â€¢ Engine revision e61bb9ac3a
    â€¢ Dart version 2.0.0-dev.35.flutter-290c576264
    âœ— Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      

[âœ“] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    â€¢ Android SDK at C:/Android/sdk
    â€¢ Android NDK location not configured (optional; useful for native profiling support)
    â€¢ Platform android-P, build-tools 27.0.3
    â€¢ ANDROID_HOME = C:/Android/sdk
    â€¢ Java binary at: C:\Temp\android-studio-ide-173.4630681-windows\android-studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)
    â€¢ All Android licenses accepted.

[âœ“] Android Studio (version 3.1)
    â€¢ Android Studio at C:\Program Files\Android\Android Studio
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[âœ“] Android Studio (version 3.2)
    â€¢ Android Studio at C:\Temp\android-studio-ide-173.4630681-windows\android-studio
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)

[âœ“] IntelliJ IDEA Community Edition (version 2017.3)
    â€¢ IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    â€¢ Flutter plugin version 22.2.2
    â€¢ Dart plugin version 173.4548.30

[âœ“] Connected devices (1 available)
    â€¢ Android SDK built for x86 â€¢ emulator-5554 â€¢ android-x86 â€¢ Android P (API 27) (emulator)

! Doctor found issues in 1 category.
```

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by osorito** [comment]
flutter upgrade -v
[  +97 ms] [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +368 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/beta
[        ] [C:\flutter\] git rev-parse --abbrev-ref HEAD
[ +170 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [C:\flutter\] git ls-remote --get-url origin
[ +161 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\flutter\] git log -n 1 --pretty=format:%H
[ +297 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
[   +1 ms] [C:\flutter\] git log -n 1 --pretty=format:%ar
[ +215 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[   +2 ms] [C:\flutter\] git describe --match v*.*.* --first-parent --long --tag
s
[ +203 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long -
-tags
[        ] v0.2.3-0-g5a58b36e3
[ +597 ms] [C:\flutter\] git rev-parse @{u}
[ +234 ms] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
[   +1 ms] Upgrading Flutter from C:\flutter...
[   +6 ms] [C:\flutter\] git pull --ff-only
[+3529 ms] Already up to date.
[   +3 ms] Upgrading engine...
[        ] [C:\flutter\] bin\flutter --no-color precache
[+4489 ms] Already up-to-date.
[ +536 ms] Flutter 0.2.3 ΓÇó channel beta ΓÇó https://github.com/flutter/flutter
.git
           Framework ΓÇó revision 5a58b36e36 (2 weeks ago) ΓÇó 2018-03-13 13:20:
13 -0700
           Engine ΓÇó revision e61bb9ac3a
           Tools ΓÇó Dart 2.0.0-dev.35.flutter-290c576264
[  +28 ms] Running "flutter packages upgrade" in flutter_puzzle_game...
[   +6 ms] [C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\] C:\
flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning --verbose upgrade --n
o-precompile
[+7173 ms] Running flutter doctor...
[   +1 ms] [C:\flutter\] bin\flutter doctor
[+4382 ms] Doctor summary (to see all details, run flutter doctor -v):
[+5496 ms] [!] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 6.1.
7601], locale en-US)
[   +1 ms]     X Downloaded executables cannot execute on host.
[        ]       See https://github.com/flutter/flutter/issues/6207 for more inf
ormation
[+8826 ms] [ΓêÜ] Android toolchain - develop for Android devices (Android SDK 27
.0.3)
[        ] [ΓêÜ] Android Studio (version 3.1)
[        ] [ΓêÜ] Android Studio (version 3.2)
[        ] [ΓêÜ] IntelliJ IDEA Community Edition (version 2017.3)
[        ] [ΓêÜ] Connected devices (1 available)
[        ] ! Doctor found issues in 1 category.
[ +146 ms] "flutter upgrade" took 35,024ms.
[  +95 ms] ensureAnalyticsSent: 90ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

**Comment by Hixie** [comment]
Can you try running `git clean -xffd` in your Flutter repository and then attach the output of `flutter precache -v; flutter doctor -v` to this PR? Thanks!

**Comment by osorito** [comment]
C:\flutter>git clean -xffd
warning: failed to remove bin/cache/artifacts/engine/android-arm-profile: Direct
ory not empty
Unlink of file 'bin/cache/dart-sdk/bin/dart.exe' failed. Should I try again? (y/
n) y
Unlink of file 'bin/cache/dart-sdk/bin/dart.exe' failed. Should I try again? (y/
n) y
Unlink of file 'bin/cache/dart-sdk/bin/dart.exe' failed. Should I try again? (y/
n) y
Unlink of file 'bin/cache/dart-sdk/bin/dart.exe' failed. Should I try again? (y/
n) y
Unlink of file 'bin/cache/dart-sdk/bin/dart.exe' failed. Should I try again? (y/
n) y
Unlink of file 'bin/cache/dart-sdk/bin/dart.exe' failed. Should I try again? (y/
n) y
Removing bin/cache/artifacts/engine/android-arm-profile/dart_io_entries.txt
Removing bin/cache/artifacts/engine/android-arm-profile/dart_vm_entry_points.txt

Removing bin/cache/artifacts/engine/android-arm-profile/entry_points.json
Removing bin/cache/artifacts/engine/android-arm-profile/entry_points_extra.json
Removing bin/cache/artifacts/engine/android-arm-profile/flutter.jar
Removing bin/cache/artifacts/engine/android-arm-profile/windows-x64
Removing bin/cache/artifacts/engine/android-arm
Removing bin/cache/artifacts/engine/android-arm-release
Removing bin/cache/artifacts/engine/android-arm64
Removing bin/cache/artifacts/engine/android-arm64-profile
Removing bin/cache/artifacts/engine/android-arm64-release
Removing bin/cache/artifacts/engine/android-x64
Removing bin/cache/artifacts/engine/android-x86
Removing bin/cache/artifacts/engine/common
Removing bin/cache/artifacts/engine/windows-x64
Removing bin/cache/artifacts/gradle_wrapper
Removing bin/cache/artifacts/material_fonts
Removing bin/cache/.dartignore
Removing bin/cache/dart-sdk
Removing bin/cache/downloads
Removing bin/cache/engine-dart-sdk.stamp
Removing bin/cache/engine.stamp
Removing bin/cache/flutter.bat.lock
Removing bin/cache/flutter_tools.snapshot
Removing bin/cache/flutter_tools.stamp
Removing bin/cache/gradle_wrapper.stamp
Removing bin/cache/lockfile
Removing bin/cache/material_fonts.stamp
Removing bin/cache/pkg
Removing packages/flutter_tools/.dart_tool/
Removing packages/flutter_tools/.packages
Removing packages/flutter_tools/pubspec.lock
Removing version

C:\flutter>flutter precache -v; flutter doctor -v
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine e61bb9ac3a3fd789754e2e54220bcfc27076a85
7...
Unzipping Dart SDK...
Updating flutter tool...
Option "-v" is a flag and cannot handle value ";".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
options.

C:\flutter>flutter doctor -v
Downloading Material fonts...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: e92be778159e363f)
Crash report written to C:\flutter\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

I'm running the commands separately. 

C:\flutter>flutter precache -v
[  +48 ms] [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +184 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[   +3 ms] [C:\flutter\] git rev-parse --abbrev-ref HEAD
[ +103 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[   +3 ms] [C:\flutter\] git ls-remote --get-url origin
[ +100 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +2 ms] [C:\flutter\] git log -n 1 --pretty=format:%H
[  +97 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
[   +2 ms] [C:\flutter\] git log -n 1 --pretty=format:%ar
[  +92 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 2 weeks ago
[   +3 ms] [C:\flutter\] git describe --match v*.*.* --first-parent --long --tag
s
[  +91 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long -
-tags
[   +1 ms] v0.2.3-0-g5a58b36e3
[ +620 ms] "flutter precache" took 116ms.

Oops; flutter has exited unexpectedly.
[  +42 ms] Sending crash report to Google.
[ +540 ms] Crash report sent (report ID: d65a113314edc891)
Crash report written to C:\flutter\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
[+6545 ms] ensureAnalyticsSent: 1ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

C:\flutter>flutter doctor -v

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: c2b3026642484ad2)
Crash report written to C:\flutter\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by osorito** [comment]
C:\flutter>git clean -xffd
warning: Could not stat path 'bin/cache/artifacts/engine/android-arm-profile/win
dows-x64': Permission denied
Removing bin/cache/artifacts/material_fonts
Removing bin/cache/.dartignore
Removing bin/cache/dart-sdk
Removing bin/cache/downloads
Removing bin/cache/engine-dart-sdk.stamp
Removing bin/cache/flutter.bat.lock
Removing bin/cache/flutter_tools.snapshot
Removing bin/cache/flutter_tools.stamp
Removing bin/cache/lockfile
Removing bin/cache/material_fonts.stamp
Removing flutter_01.log
Removing flutter_02.log
Removing flutter_03.log
Removing packages/flutter_tools/.dart_tool/
Removing packages/flutter_tools/.packages
Removing packages/flutter_tools/pubspec.lock
Removing version

C:\flutter>flutter precache -v
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine e61bb9ac3a3fd789754e2e54220bcfc27076a85
7...
Unzipping Dart SDK...
Updating flutter tool...
[  +57 ms] [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +221 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [C:\flutter\] git rev-parse --abbrev-ref HEAD
[ +106 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [C:\flutter\] git ls-remote --get-url origin
[ +126 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\flutter\] git log -n 1 --pretty=format:%H
[ +107 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
[        ] [C:\flutter\] git log -n 1 --pretty=format:%ar
[ +105 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[   +2 ms] [C:\flutter\] git describe --match v*.*.* --first-parent --long --tag
s
[ +100 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long -
-tags
[        ] v0.2.3-0-g5a58b36e3
[ +698 ms] Downloading Material fonts...
[  +13 ms] Downloading: https://storage.googleapis.com/flutter_infra/flutter/fon
ts/13ac995daa9dda0a6ba0a45f1fccc541e616a74c/fonts.zip
[ +386 ms] Received response from server, collecting bytes...
[+1112 ms] "flutter precache" took 1,612ms.

Oops; flutter has exited unexpectedly.
[  +34 ms] Sending crash report to Google.
[ +356 ms] Crash report sent (report ID: 86354ef291992857)
Crash report written to C:\flutter\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
[+6894 ms] ensureAnalyticsSent: 1ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

C:\flutter>

C:\flutter>flutter doctor -v

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 3830434511d5a81e)
Crash report written to C:\flutter\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by osorito** [comment]
Antivirus complains a treat was found on this file
Trojan Sonar.heur.rgc!g110 in gen_snapshot.exe
https://www.symantec.com/security_response/writeup.jsp?docid=2016-040503-2121-99

**Comment by Hixie** [comment]
Yeah, that sounds like your antivirus is being a little aggressive (or maybe you do have a virus? hard to tell). I'm not sure there's anything we can do about it from here though.

I'm going to close this issue because it appears to be machine-specific and not specific to Flutter. Please don't hesitate to file a new bug if you have any additional information that could lead to us fixing this issue in Flutter generally. Thanks!

**Comment by hktom** [comment]
the file gen_snapshot.exe was deleted or put in quarantine by your antivirus.

**Comment by Sunbreak** [comment]
> the file gen_snapshot.exe was deleted or put in quarantine by your antivirus.

While building engine targeting for Windows, I'm encontering `gen_snapshot.exe` failure.
Is there any workaround?

**Comment by hktom** [comment]
what antivirus are you using?

**Comment by Sunbreak** [comment]
> what antivirus are you using?

The compilation succeed on several Win10, but fail on several Win7 (One virtual fails, One `Lenovo` fails, One `HP` succeeds)

The HP laptop is the only one installed with `Symantec Endpoint Protection`

There is a note how I setup the develop environment: https://juejin.cn/post/6854573209262489607

**Comment by Sunbreak** [comment]
It seems unrelasted. I could manually execute the `gen_snapshot.exe`. I'd look into the `gen_snapshot.exe` failure further
