### ISSUE TITLE
Chip design does not conform to official Material Design

### ISSUE THREAD

**Issue by tadejkan** [flutter/flutter#15997]
There is a discrepancy between how Chips look in Flutter and how they look like in official Material Design guidelines.

The design used to be okay, but this pull request seems to have changed it - https://github.com/flutter/flutter/pull/15596.

My issue is specifically regarding chips with icons, since CircleAvatar seems to now always have a padding around it.
This padding is controlled by constant _kEdgePadding in chip.dart.

How it should look like: https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bx4BSt6jniD7aF92ZTRxOTU4U00/components-chips-contact1.png

How it looks right now: https://user-images.githubusercontent.com/8867023/37541559-4bfecfce-2918-11e8-9b35-a676528b6254.png

I'm not sure if there was a reason for this change (maybe there's a new Material Design spec?), but at the very least I would expect it to be configurable.

**Comment by gspencergoog** [comment]
There are more PRs coming soon for Chips, and they do include configurable padding.

**Comment by tadejkan** [comment]
Okay, great to hear :+1:
