### ISSUE TITLE
Add WebGPU in Impeller (or provide proper example how to use it)

### ISSUE THREAD

**Issue by munrocket** [flutter/flutter#159941]
### Use case

WebGPU team worked 6 years with Apple, Intel, Google, Mozilla together to make an API that is suitable for iOS/Android/Web/Etc. OpenGL is deprecated.

**Why it is important:**

* compute shaders is used in any advanced graphics or neural networks.
* WGSL shader language is actually cool because it is common denominator between all specifications.
* features that provided by WebGPU created with mobiles in mind (for example f16).

**It follows ultimate goal of Flutter**

Flutter is not so good at Native UI but it is good for rendering custom UI in games. Providing infrastructure for cross platform game engines is critical and should be top priority.

Related issues: #124334 #111950 #66618

### Proposal

Dawn creating shaders on the fly, but in Flutter we need offline shader compilation. I am suggesting to remove Tint from Dawn (shaders translation is the most heavy dependency) and make infrastructure for shipping precompiled shaders in flutter build as it done in Impeller. In Skia WebGPU backend exist and webgpu.h become 1:1 with JS.

**Comment by jonahwilliams** [comment]
We have no plans to incorporate Dawn into the flutter engine nor to expose WebGPU as an AP in Flutter.
