### ISSUE TITLE
Make BoxDecoration extensible

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#160]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Sep 14, 2015 at 16:32 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1156_

----

We should have BoxDecoration inherit from a superclass that has a "get painter" method that returns an object that does the painting, and BoxDecoration overrides that method to return a BoxPainter constructed with a copy of the BoxDecoration in question.

**Comment by abarth** [comment]
Do we still want this given that we now have CustomPaint?  I'm not sure when I'd use this instead of either CustomPaint or just make new MyDecoratedBox / MyBoxDecoration.

**Comment by Hixie** [comment]
I'm not sure. I tried implementing it; see the example at the top of the diff:

https://github.com/flutter/flutter/pull/781

I agree that it's weird to have two ways to do this. Maybe Container should use a CustomPaint instead of RenderDecoratedBox?

**Comment by abarth** [comment]
@Hixie did this.
