### ISSUE TITLE
run the 'flutter run rendering/hello_world.dart' command in the  example/layer directory. Texts are not displayed on the Linux desktop but can be displayed on the web page 

### ISSUE THREAD

**Issue by wucong1997** [flutter/flutter#160078]
### Steps to reproduce

1. run the 'flutter run rendering/hello_world.dart' command in the  example/layer directory.
2. choose linux
3. choose Chrome

### Expected results

Texts are displayed on the Linux desktop and on the web page 

### Actual results

Texts are not displayed on the Linux desktop but can be displayed on the web page 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@wucong1997 
Although I don't have Linux, but I tried the same on macOS desktop in which the text is displayed properly. 
What flutter version are you seeing this on ? Can you provide a screenshot ?

**Comment by wucong1997** [comment]
flutter version: 3.7, this is error info: 
![image](https://github.com/user-attachments/assets/7a04e9b1-23eb-43ea-a851-2646b17a4233)

**Comment by wucong1997** [comment]
But when I run this command again, there is no error, which is strange:
 
![image](https://github.com/user-attachments/assets/365ead14-26ec-4c1d-9d46-6f2eedaf0aaf)

**Comment by darshankawar** [comment]
Upgrade to latest stable and re-run your scenario to check if you still see same behavior or not.

**Comment by wucong1997** [comment]
There is same behavior on flutter 3.22:
![image](https://github.com/user-attachments/assets/5c1e479b-89a4-4826-b2ee-656c981e08e2)

**Comment by wucong1997** [comment]
flutter doctor -v:
[✓] Flutter (Channel oh-3.22.0, 3.22.1-0.0.pre.16, on Ubuntu 22.04.4 LTS 6.8.0-49-generic, locale zh_CN.UTF-8)
    • Flutter version 3.22.1-0.0.pre.16 on channel oh-3.22.0 at /home/wucong/flutter3.22/flutter
    • Upstream repository https://gitee.com/harmonycommando_flutter/flutter.git
    • FLUTTER_GIT_URL = https://gitee.com/harmonycommando_flutter/flutter.git
    • Framework revision c44cfb3a15 (2 周前), 2024-11-25 11:58:38 +0000
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] HarmonyOS toolchain - develop for HarmonyOS devices
    • OpenHarmony Sdk at /home/wucong/tools/commandline-tools-linux-x64-5.0.5.300/command-line-tools/sdk, available api versions has [13:default]
    • Ohpm version 5.0.10
    • Node version v18.20.1
    • Hvigorw binary at /home/wucong/tools/commandline-tools-linux-x64-5.0.5.300/command-line-tools/hvigor/bin/hvigorw

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.93.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.4 LTS 6.8.0-49-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.137

[✓] Network resources
    • All expected network resources are available.

**Comment by darshankawar** [comment]
@wucong1997 
3.22 is beta or master ? If either, they are still not latest. Try to latest stable (3.27.0)

**Comment by wucong1997** [comment]
> @wucong1997 3.22 is beta or master ? If either, they are still not latest. Try to latest stable (3.27.0)

The lastest version also has this problem. you can see this issue: https://github.com/flutter/flutter/issues/160157

**Comment by darshankawar** [comment]
Ok, de-duplicating with the linked issue. Please follow-up in it.
