### ISSUE TITLE
Decrease Api Requests in Flutter map 

### ISSUE THREAD

**Issue by MohamedGendy2** [flutter/flutter#160067]
I am using flutter_map with TomTom tiles to display a map and fetch data. However, while zooming or panning the map, it sends excessive API requests, leading to an overload of requests to the TomTom API. How can I optimize this behavior to minimize API requests during zooming or panning actions?

i use it too for windows application 

TileLayer(
  tileBuilder: (context, tileWidget, tile) {
    return tileWidget;
  },
  tileProvider: CachedTileProvider(
    urlTemplate: "https://api.tomtom.com/map/1/tile/basic/main/{z}/{x}/{y}.png?key=$apiKey",
    apiKey: apiKey,
  ),
),

class CachedTileProvider extends TileProvider {
  final String urlTemplate;
  final String apiKey;
  late CacheManager _cacheManager;

  CachedTileProvider({
    required this.urlTemplate,
    required this.apiKey,
  }) {
    _cacheManager = CacheManager(
      Config(
        'map_tiles_cache1',
        maxNrOfCacheObjects: 100000,
        stalePeriod: const Duration(minutes: 5),
      ),
    );
  }

  @override
  ImageProvider getImage(TileCoordinates coordinates, TileLayer options) {
    final url = getTileUrl(coordinates, options);

    return CachedNetworkImageProvider(
      url,
      cacheManager: _cacheManager,
    );
  }

  @override
  String getTileUrl(TileCoordinates coordinates, TileLayer options) {
    return urlTemplate
        .replaceAll('{x}', coordinates.x.toString())
        .replaceAll('{y}', coordinates.y.toString())
        .replaceAll('{z}', coordinates.z.toString())
        .replaceAll('$apiKey', apiKey);
  }
}

@override
Widget build(BuildContext context) {
  return FlutterMap(
    options: MapOptions(
      minZoom: 11,
      initialCenter: LatLng(24.7136, 46.6753),
      initialZoom: 11,
      // Note: Zooming or panning triggers multiple requests
      onTap: (_, tappedPoint) => _handleMapTap(tappedPoint),
    ),
    children: [
      TileLayer(
        tileBuilder: (context, tileWidget, tile) {
          return tileWidget;
        },
        tileProvider: CachedTileProvider(
          urlTemplate: "https://api.tomtom.com/map/1/tile/basic/main/{z}/{x}/{y}.png?key=$apiKey",
          apiKey: apiKey,
        ),
      ),
      TileLayer(
        tileProvider: CachedTileProvider(
          urlTemplate: "https://api.tomtom.com/traffic/map/4/tile/flow/relative/{z}/{x}/{y}.png?key=$apiKey",
          apiKey: apiKey,
        ),
      ),
    ],
  );
}

**Comment by danagbemava-nc** [comment]
This should be reported on the [flutter_map](https://github.com/fleaflet/flutter_map/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) repo 

Closing from here 

Thank you
