### ISSUE TITLE
[CP] Disable Impeller on Adreno GPUs older than 630.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#160041]
### Issue Link

flutter/flutter#159834

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/engine/pull/57100

### Changelog Description

* Disable Adreno GPUs older than 640.

### Impacted Users

Flutter Android users on older Adreno devices

### Impact Description

Device drivers do not fully support vulkan resulting in rendering bugs.

### Workaround

Disable Impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached unit test.

**Comment by zanderso** [comment]
cp lgtm

**Comment by jonahwilliams** [comment]
OK, should be working now. Whenever we get around to it.
