### ISSUE TITLE
Get rid of the engine's dependency on Garnet from the Fuchsia repository.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#16003]
This primarily includes removing the FXL dependency from Tonic and the Engine. We can move most of the stuff currently needed from FXL to FML (or just use `std` variants where available.)

**Comment by chinmaygarde** [comment]
cc @cbracken

**Comment by kulakowski** [comment]
I was looking at the engine BUILD.gn stuff just now. There's a few references to //garnet still, but most (or maybe all?) of them are old (that is, the subdirectory within //garnet no longer exists in fuchsia), and are behind a using_fuchsia_sdk flag. Is that using_fuchsia_sdk path always taken?

**Comment by chinmaygarde** [comment]
In the Flutter buildroot, the `using_fuchsia_sdk` path is always taken. The other path needs to be cleaned up. This can be closed.

Also, welcome back 👋
