### ISSUE TITLE
System dark/light mode not working on Android

### ISSUE THREAD

**Issue by srochacito** [flutter/flutter#160031]
### Steps to reproduce

I'm using vscode 1.95.3 on windows 11 machine:

Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

1. Run in debug mode or release mode on Android emulator
2. Change settings in to dark mode in emulator
3. Theme mode not changing in app.

Works fine on iOS or Windows.

### Expected results

When changing system theme mode settings, the app should be set to that mode: dark or light

### Actual results

App doesn't change mode even if hot reloaded or restarted

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Theme Test',
      themeMode: ThemeMode.system,
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      home: const TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({super.key});

  @override
  Widget build(BuildContext context) {
    final brightness = MediaQuery.of(context).platformBrightness;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Theme Test'),
      ),
      body: Center(
        child: Text(
          'Brightness: $brightness',
          style: Theme.of(context).textTheme.headlineMedium,
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/55b24577-5e51-4558-887c-1f80d1d27c89

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.26100.2454], locale es-MX)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.95.3)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by mu7ammadkamel** [comment]
Maybe the issue related to the Emulator.
Have you tried it on real device?

**Comment by maheshj01** [comment]
Hi @srochacito, Thanks for filing the issue. I am able to reproduce the issue on the emulator but not on a physical device or ios Simulator. So I suspect this is an issue with **Android emulator** and not with Flutter.


**Reproducible on Android emulator only**

https://github.com/user-attachments/assets/3fe0c0fb-871f-4632-9527-d796738557f6

_works fine on physical Android device and ios simulator_

Pixel 7 (Physical device) | iphone 16 pro (simulator)
:-: | :-:
<video src='https://github.com/user-attachments/assets/41a710f6-50f8-4ce6-8d1f-44f7f9b0db99' width=180/> | <video src='https://github.com/user-attachments/assets/02f3e8cd-5369-4c5e-b1be-4cdd8d5187e2' width=180/> 

**Works fine on MacOS web and desktop**

https://github.com/user-attachments/assets/33d3d753-5e02-486c-b468-d05be91d2361

<details>
<summary>flutter doctor -v</summary>

```console

```
</details> 

I believe there is no action required on the flutter side, However I will label this for the team to take another look.

**Comment by srochacito** [comment]
Thank you, I found a simple work around.
Setting dark theme (in the settings app) makes it work:

<img width="873" alt="image" src="https://github.com/user-attachments/assets/cc408f48-a9e5-455d-9b05-a0f2a276e3ba">

**Comment by camsim99** [comment]
Closing as this doesn't appear to be broken.
