### ISSUE TITLE
Getting errors in console log for iOS build.

### ISSUE THREAD

**Issue by MuhammadMueed** [flutter/flutter#160065]
### Steps to reproduce

1. Flutter build ios

### Expected results

Build file created successfully.

### Actual results

<img width="1128" alt="Screenshot 2024-12-11 at 11 45 22 AM" src="https://github.com/user-attachments/assets/40516939-ddc3-456b-83f3-e9a0c21db9fe">

### Code sample

<details open><summary>Code sample</summary>

```dart
name: uuealth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^27.2.4
  syncfusion_flutter_datagrid: ^27.2.4
  intl: ^0.19.0
  provider: ^6.0.5
  badges: ^3.1.1
  multi_select_flutter: ^4.1.3
  freezed_annotation: ^2.2.0
  carousel_slider: ^5.0.0
  http: ^1.2.0
  http_interceptor: ^2.0.0-beta.8
  web_socket_channel: ^3.0.1
  timeline_tile: ^2.0.0
  timer_count_down: ^2.2.2
  video_player: ^2.7.0
  video_player_win: ^3.1.1
  flutter_rating_bar: ^4.0.1
  window_manager: ^0.4.3
  tutorial_coach_mark: ^1.2.9
  syncfusion_flutter_core: ^27.2.4
  veriff_flutter: ^4.3.0
  app_settings: ^5.1.1
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.15
  # flutter_local_notifications: ^16.3.0
  # url_launcher: ^6.1.14
  custom_rounded_rectangle_border: ^0.3.0
  path_provider: ^2.1.3
  simple_gesture_detector: ^0.2.1
  shared_preferences: ^2.0.13
  flutter_animate: ^4.5.0
  popover: ^0.3.0+1
  image_picker: ^1.0.8
  syncfusion_flutter_pdfviewer: ^27.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.14.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/files/
    - assets/flags/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: 'AppIcon'
  image_path: 'assets/images/logo.png'
  min_sdk_android: 21

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1128" alt="Screenshot 2024-12-11 at 11 45 22 AM" src="https://github.com/user-attachments/assets/22387ebf-f952-49fb-ac54-05248af280dc">

</details>

### Logs

Building com.wavelabs.uuealth for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: PYC99XAKXQ
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      1,256ms
Xcode build done.                                           33.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/5t/rh6p8g0j6p9fdhbv97b7sgfw0000gn/T/flutter_tools.rZ7nsP/flutter_ios_build_temp_dirfSg0Gw/temporary_xcresult_bundle

    Unhandled exception:
    Null check operator used on a null value
    #0      Context.embedFlutterFrameworks
    (file:///Users/muhammadmueed/Documents/Wavelabs/Mobile%20Dev/tools/flutter/packages/flutter_tools/bin/xcode_backend.dart:237:68)
    #1      Context.run (file:///Users/muhammadmueed/Documents/Wavelabs/Mobile%20Dev/tools/flutter/packages/flutter_tools/bin/xcode_backend.dart:61:9)
    #2      main (file:///Users/muhammadmueed/Documents/Wavelabs/Mobile%20Dev/tools/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
    #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target
    'url_launcher_ios-url_launcher_ios_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target
    'shared_preferences_foundation-shared_preferences_foundation_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target
    'path_provider_foundation-path_provider_foundation_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'VeriffSDK' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target
    'device_info_plus-device_info_plus_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target
    'video_player_avfoundation-video_player_avfoundation_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target
    'image_picker_ios-image_picker_ios_privacy' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'url_launcher_ios' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'shared_preferences_foundation' from
    project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'app_settings' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'path_provider_foundation' from project
    'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'syncfusion_flutter_pdfviewer' from
    project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'video_player_avfoundation' from project
    'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'image_picker_ios' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'device_info_plus' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'veriff_flutter' from project 'Pods')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is
    unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is
    unchecked. (in target 'Runner' from project 'Runner')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'Pods-Runner' from project 'Pods')
    note: Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-O, expected -Onone (in target 'Flutter' from project 'Pods')

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@MuhammadMueed 
Check if you have profile runner mismatch in your xcode config. For example, profile runner was pointing to some Pods-Runner.xcconfig instead of the release one or vice-versa.
Based on the error log, it seems to be similar to https://github.com/flutter/flutter/issues/140845, so please follow-up in it for further updates.
