### ISSUE TITLE
Antivirus reports gen_snapshot.exe contains treat

### ISSUE THREAD

**Issue by osorito** [flutter/flutter#16008]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

File: c:\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\ gen_snapshot.exe Threat Removed
File: c:\users\omar osorio\androidstudioprojects\flutter_sunshine\build\app\intermediates\flutter\debug\ snapshot_blob.bin Threat Removed
File: c:\users\omar osorio\androidstudioprojects\flutter_sunshine\build\app\intermediates\flutter\debug\ snapshot_blob.bin.d Threat Removed
File: c:\users\omar osorio\androidstudioprojects\flutter_puzzle_game\build\app\intermediates\flutter\debug\ snapshot_blob.bin Threat Removed

## command

flutter build flx --suppress-analytics --target C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\lib\main.dart --output-file C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\build\app\intermediates\flutter\debug/app.flx --depfile C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --snapshot C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\build\app\intermediates\flutter\debug/snapshot_blob.bin --working-dir C:\Users\Omar Osorio\AndroidStudioProjects\flutter_puzzle_game\build\app\intermediates\flutter\debug/flutter_assets

## exception

ArgumentError: Invalid argument(s): Cannot find executable for C:\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      runCommand (package:flutter_tools/src/base/process.dart:115)
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:133)
<asynchronous suspension>
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:53)
#5      Snapshotter._build (package:flutter_tools/src/base/build.dart:209)
<asynchronous suspension>
#6      Snapshotter.buildScriptSnapshot (package:flutter_tools/src/base/build.dart:174)
<asynchronous suspension>
#7      build (package:flutter_tools/src/flx.dart:62)
<asynchronous suspension>
#8      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:50)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     new Future.sync (dart:async/future.dart:222)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1126)
#21     _CustomZone.run (dart:async/zone.dart:1023)
#22     runZoned (dart:async/zone.dart:1501)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#26     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[!] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    â€¢ Flutter version 0.2.3 at C:\flutter
    â€¢ Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    â€¢ Engine revision e61bb9ac3a
    â€¢ Dart version 2.0.0-dev.35.flutter-290c576264
    âœ— Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      

[âœ“] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    â€¢ Android SDK at C:\Android\sdk
    â€¢ Android NDK location not configured (optional; useful for native profiling support)
    â€¢ Platform android-P, build-tools 27.0.3
    â€¢ ANDROID_HOME = C:\Android\sdk;C:\Android\sdk\tools\bin
    â€¢ Java binary at: C:\Temp\android-studio-ide-173.4630681-windows\android-studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)
    â€¢ All Android licenses accepted.

[âœ“] Android Studio (version 3.1)
    â€¢ Android Studio at C:\Program Files\Android\Android Studio
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[âœ“] Android Studio (version 3.2)
    â€¢ Android Studio at C:\Temp\android-studio-ide-173.4630681-windows\android-studio
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)

[âœ“] IntelliJ IDEA Community Edition (version 2017.3)
    â€¢ IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    â€¢ Flutter plugin version 22.2.2
    â€¢ Dart plugin version 173.4548.30

[âœ“] Connected devices (1 available)
    â€¢ Android SDK built for x86 â€¢ emulator-5554 â€¢ android-x86 â€¢ Android P (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by Hixie** [comment]
This is probably the same as 15998.

**Comment by Hixie** [comment]
Which antivirus do you use? Does it say what virus it's seeing?

**Comment by osorito** [comment]
Sonar.heur.rgc!g110 in gen_snapshot.exe

**Comment by osorito** [comment]
https://www.symantec.com/security_response/writeup.jsp?docid=2016-040503-2121-99

**Comment by NathanaelA** [comment]
@osorito - Reading the tech details -- which basically say this is a generic test that may flag things for what it considers suspicious behavior.     Compilers tend to read and write and modify files...  Suspicious..

Submitting the latest version (and a prior version) of the `gen_snapshot.exe` -- I would venture a guess it is a false positive.    

See:
https://www.virustotal.com/#/file/5f12105facc4f88ff40f41e7d18b0d472fab89476560762b5b73f072ec0a32ee/detection
https://www.virustotal.com/#/file/e237ebe7fe52d26b1410e45dce89637da47527045b4cb291fd05a021c7ef2719/detection

Silly anti-virus products; you probably should just whitelist your flutter directory to eliminate any more false positives.

**Comment by osorito** [comment]
This happened after the upgrade. Before flutter upgrade antivirus reported no problems. Sure the file is safe?

**Comment by NathanaelA** [comment]
Yeah, that wouldn't surprise me that a virus checker might flag that -
1. You did an upgrade; which means you unzipped a new version of the file over an old version.  (Flag 1)
2. You did a build (Reads, Writes and modifies files) -- (Flag 2).

Both of those are suspicious events to virus checkers in general; you add both together.....

:trumpet: 

...and it does look suspiciously like you had a drive by download that is now modifying files.  

But this is what I did when I posted my response above -- I did a fresh `git pull` on the "dev" branch; which pulled the latest of flutter repo as of about 3 hours or so ago.   Then I did a `flutter upgrade` -- which downloaded the new dart and sky engines.  So I had the latest of everything...

I then took that specific gen_snapshot.exe file from the same path that your virus checker had issues with and uploaded it to virustotal's -- which ran it against about 65 different virus engines.   No virus's found.

So if there is a virus -- it is on your machine.  It doesn't appear to be in the repo as none of the 65 virus checkers flagged either the old version (which was from a couple weeks ago) nor the brand new version that I pulled today.

If you really feel their is an issue; I would 
1. Disable your virus checker on the Flutter directory.  
2. Do a Re-install of flutter (as who knows how many files are now missing because of your virus checker)
3. Upload that specific file to virus totals; and verify it is clean from your machine.  :grinning:

**Comment by osorito** [comment]
In command prompt in administrator mode. 
1 Deleted the folder c:\Flutter\
2 run Norton (No detections found)
3 Run Malwarebytes (No malware found)
4 Got git file as instructed in https://flutter.io/
5 Once step 4 is done the folder c:\flutter is created go inside it cd \flutter
6 inside the flutter folder run flutter doctor, it starts to download files and ask's to replace dart folder
This is where the fun starts if antivirus is not disabled.
7 inside flutter folder run flutter upgrade for some reasons this is where it fails multiple times. So i told antivirus to remove file from quarantine and exclude it. Rinse and repeat from step 1 with antivirus down and exception allowed for the file. As you say this file is a compiler but so is javac and it's not recognized as a treat every time I build an Android app. For now i'm allowing the file to exist since i really wish to keep programming in flutter and without that file it's impossible

**Comment by NathanaelA** [comment]
@osorito - I really recommend you just white list the whole flutter directory.      I can't tell you the specific steps for Norton; but I do know Norton/Symantic antivirus has a white list feature.     You basically tell it to ignore everything inside the flutter directory (and flutter sub-directories).      

After install; if you feel like you want to verify their are no virus; you can manually upload any file to virustotal and it will tell if it is clean.   65 different virus engines (including Symantics) check the file...  ;-)

The virus it tagged flutter with is one of the fuzzy-logic based ones where it evaluates the behavior of the program and then if it acts too suspiciously it is flagged as potentially having a virus.    Fresh install of a compiler which is then ran; can easily cause enough "suspicious" flags to be raised for that executable.

**Comment by zoechi** [comment]
Do you think there is still something the Flutter team can do?

**Comment by zoechi** [comment]
@NathanaelA thanks for the feedback.
I'm going to close the issue. 
If you think the Flutter team needs to do something please add a comment to get the issue reopened.
