### ISSUE TITLE
Flake: git fetch packfile does not match index

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#16000]
During Travis run of analysis shard, saw the following git failure:
```
Running "flutter packages get" in complex_layout...             
Git error. Command: git fetch
error: packfile ./objects/pack/pack-626e142fd37b210efcb529f5272d88034fb56397.pack does not match index
error: packfile ./objects/pack/pack-626e142fd37b210efcb529f5272d88034fb56397.pack does not match index
```

**Comment by jonahwilliams** [comment]
It's not clear that there is anything actionable here, re-open if you disagree

**Comment by cbracken** [comment]
I haven't seen this in a long time, but the actionable item would be to provide a useful error message to the user. I'm fine leaving closed until someone else reports this.
