### ISSUE TITLE
Text field input type issue for Android 

### ISSUE THREAD

**Issue by TiruKallepalli** [flutter/flutter#160020]
### Steps to reproduce

I am working on a OTP UI screen ,I am facing issue in android works fine for iOS ,Where while entering the numbers the input type keyboard flickers in between and switching back to default keyboard.

### Expected results

The Keyboard UI should not flicker while entering the input number

### Actual results

The Keyboard UI is flickering in between and switching back to default keyboard for input type number keyboard 

### Code sample

<details open><summary>Code sample</summary>

```dart
[import 'dart:async';  // For timer functionality
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class ModernOTPBottomSheet extends StatefulWidget {
  final Function(String) onOtpSubmitted;
  final Function() onRetryRequested;

  ModernOTPBottomSheet({required this.onOtpSubmitted, required this.onRetryRequested});

  @override
  _ModernOTPBottomSheetState createState() => _ModernOTPBottomSheetState();
}

class _ModernOTPBottomSheetState extends State<ModernOTPBottomSheet> with SingleTickerProviderStateMixin {
  final List<TextEditingController> _controllers = List.generate(4, (index) => TextEditingController());
  final FocusNode _focusNode = FocusNode();
  final ValueNotifier<bool> _isButtonEnabled = ValueNotifier(false);  // To track if all OTP digits are entered
  late Timer _timer;  // Timer to track 3-minute period
  int _remainingTime = 180; // 3 minutes in seconds
  bool _canRetry = false;
  late AnimationController _animationController;  // Animation controller for scaling

  @override
  void initState() {
    super.initState();
    _startTimer();
    _animationController = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 200),  // Fast scaling animation
    );
  }

  @override
  void dispose() {
    _controllers.forEach((controller) => controller.dispose());
    _isButtonEnabled.dispose();
    _timer.cancel();
    _animationController.dispose();
    super.dispose();
  }

  // Start the countdown timer
  void _startTimer() {
    _timer = Timer.periodic(Duration(seconds: 1), (timer) {
      if (_remainingTime > 0) {
        setState(() {
          _remainingTime--;
        });
      } else {
        setState(() {
          _canRetry = true;
        });
        _timer.cancel();
      }
    });
  }

  String get _formattedTime {
    int minutes = _remainingTime ~/ 60;
    int seconds = _remainingTime % 60;
    return "$minutes:${seconds.toString().padLeft(2, '0')}";
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(25),
          topRight: Radius.circular(25),
        ),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Text(
            'Enter OTP',
            style: TextStyle(
              fontSize: 22,
              fontWeight: FontWeight.bold,
              color: Colors.black87,
            ),
          ),
          const SizedBox(height: 20),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: List.generate(4, (index) {
              return _buildTextField(context, _controllers[index], index);
            }),
          ),
          const SizedBox(height: 20),
          Text(
            'Resend OTP in ${_formattedTime}',
            style: TextStyle(fontSize: 16, color: Colors.grey),
          ),
          const SizedBox(height: 10),
          GestureDetector(
            onTap: _canRetry ? () {
              widget.onRetryRequested();  // Call retry function
              setState(() {
                _remainingTime = 180; // Reset timer
                _canRetry = false;
                _startTimer();  // Restart the timer
              });
            } : null,
            child: Text(
              'Resend OTP',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: _canRetry ? Colors.blue : Colors.grey,
              ),
            ),
          ),
          const SizedBox(height: 30),
          ValueListenableBuilder<bool>(
            valueListenable: _isButtonEnabled,
            builder: (context, isEnabled, child) {
              return ElevatedButton(
                onPressed: isEnabled
                    ? () {
                  String otp = _controllers.map((controller) => controller.text.trim()).join();
                  widget.onOtpSubmitted(otp);
                  Navigator.pop(context);
                }
                    : null,  // Disable the button if not all digits are entered
                child: Text('Submit'),
                style: ElevatedButton.styleFrom(
                  padding: EdgeInsets.symmetric(vertical: 15),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(20),
                  ),
                  textStyle: TextStyle(fontSize: 18),
                  minimumSize: Size(double.infinity, 50),  // Full-width button
                  backgroundColor: isEnabled ? Colors.deepPurple : Colors.grey,  // Change color based on enabled state
                ),
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildTextField(BuildContext context, TextEditingController controller, int index) {
    return AnimatedContainer(
      duration: Duration(milliseconds: 200),  // Animation duration
      width: _focusNode.hasFocus ? 55 : 45,  // Increase size when focused
      height: _focusNode.hasFocus ? 55 : 45,  // Increase size when focused
      child: TextField(
        autofillHints: const <String>[AutofillHints.oneTimeCode],
        controller: controller,
        autocorrect: false,
        autofocus: false,
        focusNode: index == 0 ? _focusNode : null,  // Optional: manage focus
        keyboardType: TextInputType.number,
        textAlign: TextAlign.center,
        inputFormatters: [LengthLimitingTextInputFormatter(1), FilteringTextInputFormatter.digitsOnly],
        decoration: InputDecoration(
          filled: true,
          fillColor: Colors.grey.shade100,  // Light background for a modern look
          border: UnderlineInputBorder(
            borderSide: BorderSide(color: Colors.black54),  // Underline instead of box
          ),
        ),
        style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
        onTap: () {
          _animationController.forward();
        },
        onChanged: (value) {
          if (value.length == 1 && index < 3) {
            FocusScope.of(context).nextFocus();  // Move to the next field
          } else if (value.isEmpty && index > 0) {
            FocusScope.of(context).previousFocus();  // Move to the previous field on backspace
          }
          _checkOtpComplete();  // Check if all fields are filled
        },
      ),
    );
  }

  // Method to check if all fields are filled and enable/disable the button accordingly
  void _checkOtpComplete() {
    bool isComplete = _controllers.every((controller) => controller.text.trim().isNotEmpty);
    _isButtonEnabled.value = isComplete;
  }
}
]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@TiruKallepalli 
Can you provide `flutter doctor -v` to know on which version you are seeing the reported behavior ?
Can you also provide device details (make, model and OS version) on which you are seeing this ? Also provide a short video of the behavior. Most importantly, provide only minimal but complete runnable reproducible code sample (ex: main.dart) that we can simply copy paste and run to verify further, so you can remove unwanted code implementation and only keep which matters to trigger the behavior.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by TiruKallepalli** [comment]
Hi @darshankawar 
Here are my flutter details
**• Flutter version 3.24.3 on channel stable at /Users/tirumalesh/Documents/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3**

1. I have tested by creating the new project as well

2. I have tested in android emulator and even on real device google pixel 8 and samsung note 10 plus which is running on android 15 and android 12 versions.
3. The above code can be called simply in main.dart file.
Attaching the video for your reference
 if you see in the video how the keyboard is flickering while entering input
https://github.com/user-attachments/assets/dee8b427-6ec7-4ab1-9cfd-69dcb79b294a

**Comment by darshankawar** [comment]
> ```dart
> final Function(String) onOtpSubmitted;
>   final Function() onRetryRequested;
> ```

@TiruKallepalli Please provide these values to be passed in the main function.

**Comment by TiruKallepalli** [comment]
final Function(String) onOtpSubmitted == This callback to pass otp value which is entered to other class;
final Function() onRetryRequested==  This is nothing just a function to call api

**Comment by darshankawar** [comment]
I see below upon running the code so I am unable to verify this properly. 

<img width="270" alt="Screenshot 2024-12-11 at 11 39 36 AM" src="https://github.com/user-attachments/assets/6f87fdb3-8dda-4d8c-bf77-0208f2233d81">

Hence, as I had requested earlier, only provide minimal code by removing unwanted implementation.

**Comment by TiruKallepalli** [comment]
@darshankawar 

Please check this code


`import 'dart:async';  // For timer functionality
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class ModernOTPBottomSheet extends StatefulWidget {
  final Function(String) onOtpSubmitted;
  final Function() onRetryRequested;

  ModernOTPBottomSheet({required this.onOtpSubmitted, required this.onRetryRequested});

  @override
  _ModernOTPBottomSheetState createState() => _ModernOTPBottomSheetState();
}

class _ModernOTPBottomSheetState extends State<ModernOTPBottomSheet> with SingleTickerProviderStateMixin {
  final List<TextEditingController> _controllers = List.generate(4, (index) => TextEditingController());
  final FocusNode _focusNode = FocusNode();
  final ValueNotifier<bool> _isButtonEnabled = ValueNotifier(false);  // To track if all OTP digits are entered
  late Timer _timer;  // Timer to track 3-minute period
  int _remainingTime = 180; // 3 minutes in seconds
  bool _canRetry = false;
  late AnimationController _animationController;  // Animation controller for scaling

  @override
  void initState() {
    super.initState();
    _startTimer();
    _animationController = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 200),  // Fast scaling animation
    );
  }

  @override
  void dispose() {
    _controllers.forEach((controller) => controller.dispose());
    _isButtonEnabled.dispose();
    _timer.cancel();
    _animationController.dispose();
    super.dispose();
  }

  // Start the countdown timer
  void _startTimer() {
    _timer = Timer.periodic(Duration(seconds: 1), (timer) {
      if (_remainingTime > 0) {
        setState(() {
          _remainingTime--;
        });
      } else {
        setState(() {
          _canRetry = true;
        });
        _timer.cancel();
      }
    });
  }

  String get _formattedTime {
    int minutes = _remainingTime ~/ 60;
    int seconds = _remainingTime % 60;
    return "$minutes:${seconds.toString().padLeft(2, '0')}";
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          padding: EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.only(
              topLeft: Radius.circular(25),
              topRight: Radius.circular(25),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Text(
                'Enter OTP',
                style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  color: Colors.black87,
                ),
              ),
              const SizedBox(height: 20),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: List.generate(4, (index) {
                  return _buildTextField(context, _controllers[index], index);
                }),
              ),
              const SizedBox(height: 20),
              Text(
                'Resend OTP in ${_formattedTime}',
                style: TextStyle(fontSize: 16, color: Colors.grey),
              ),
              const SizedBox(height: 10),
              GestureDetector(
                onTap: _canRetry ? () {
                  widget.onRetryRequested();  // Call retry function
                  setState(() {
                    _remainingTime = 180; // Reset timer
                    _canRetry = false;
                    _startTimer();  // Restart the timer
                  });
                } : null,
                child: Text(
                  'Resend OTP',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: _canRetry ? Colors.blue : Colors.grey,
                  ),
                ),
              ),
              const SizedBox(height: 30),
              ValueListenableBuilder<bool>(
                valueListenable: _isButtonEnabled,
                builder: (context, isEnabled, child) {
                  return ElevatedButton(
                    onPressed: isEnabled
                        ? () {
                      String otp = _controllers.map((controller) => controller.text.trim()).join();
                      widget.onOtpSubmitted(otp);
                      Navigator.pop(context);
                    }
                        : null,  // Disable the button if not all digits are entered
                    child: Text('Submit'),
                    style: ElevatedButton.styleFrom(
                      padding: EdgeInsets.symmetric(vertical: 15),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                      textStyle: TextStyle(fontSize: 18),
                      minimumSize: Size(double.infinity, 50),  // Full-width button
                      backgroundColor: isEnabled ? Colors.deepPurple : Colors.grey,  // Change color based on enabled state
                    ),
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField(BuildContext context, TextEditingController controller, int index) {
    return AnimatedContainer(
      duration: Duration(milliseconds: 200),  // Animation duration
      width: _focusNode.hasFocus ? 55 : 45,  // Increase size when focused
      height: _focusNode.hasFocus ? 55 : 45,  // Increase size when focused
      child: TextField(
        autofillHints: const <String>[AutofillHints.oneTimeCode],
        controller: controller,
        autocorrect: false,
        autofocus: false,
        focusNode: index == 0 ? _focusNode : null,  // Optional: manage focus
        keyboardType: TextInputType.number,
        textAlign: TextAlign.center,
        inputFormatters: [LengthLimitingTextInputFormatter(1), FilteringTextInputFormatter.digitsOnly],
        decoration: InputDecoration(
          filled: true,
          fillColor: Colors.grey.shade100,  // Light background for a modern look
          border: UnderlineInputBorder(
            borderSide: BorderSide(color: Colors.black54),  // Underline instead of box
          ),
        ),
        style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
        onTap: () {
          _animationController.forward();
        },
        onChanged: (value) {
          if (value.length == 1 && index < 3) {
            FocusScope.of(context).nextFocus();  // Move to the next field
          } else if (value.isEmpty && index > 0) {
            FocusScope.of(context).previousFocus();  // Move to the previous field on backspace
          }
          _checkOtpComplete();  // Check if all fields are filled
        },
      ),
    );
  }

  // Method to check if all fields are filled and enable/disable the button accordingly
  void _checkOtpComplete() {
    bool isComplete = _controllers.every((controller) => controller.text.trim().isNotEmpty);
    _isButtonEnabled.value = isComplete;
  }
}
`

**Comment by TiruKallepalli** [comment]
@darshankawar 
Yes in master branch there is no issue can i expect in stable branch for a new flutter version

**Comment by darshankawar** [comment]
Yes it most probably be available in next stable release, so watch out for it.
Closing this as fixed.
