### ISSUE TITLE
Flutter 3.27.0 Bug with dart_webrtc

### ISSUE THREAD

**Issue by scharalambous3** [flutter/flutter#160106]
### Steps to reproduce

1. Use dart_webrtc dart_webrtc 1.4.9
2. Use flutter version that has just been released (3.27.0)
3. Build for web

### Expected results

No build error for web

### Actual results

19:54:31.904	Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
19:54:31.904	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/media_stream_track_impl.dart:13:68:
19:54:31.904	Error: Function converted via 'toJS' contains invalid types in its function signature: '*dynamic* Function(*dynamic*)'.
19:54:31.904	    jsTrack.addEventListener('ended', ((event) => onEnded?.call()).toJS);
19:54:31.905	                                                                   ^
19:54:31.905	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/media_stream_track_impl.dart:14:66:
19:54:31.905	Error: Function converted via 'toJS' contains invalid types in its function signature: '*dynamic* Function(*dynamic*)'.
19:54:31.905	    jsTrack.addEventListener('mute', ((event) => onMute?.call()).toJS);
19:54:31.905	Compiling lib/main.dart for the Web...                                                                                           ^
19:54:31.905	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/media_stream_track_impl.dart:15:70:
19:54:31.905	Error: Function converted via 'toJS' contains invalid types in its function signature: '*dynamic* Function(*dynamic*)'.
19:54:31.905	    jsTrack.addEventListener('unmute', ((event) => onUnMute?.call()).toJS);
19:54:31.906	                                                                     ^
19:54:31.906	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_peerconnection_impl.dart:34:11:
19:54:31.906	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.906	        }.toJS);
19:54:31.906	          ^
19:54:31.907	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_peerconnection_impl.dart:42:11:
19:54:31.907	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.907	        }.toJS);
19:54:31.907	          ^
19:54:31.907	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_peerconnection_impl.dart:82:11:
19:54:31.907	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.907	        }.toJS);
19:54:31.907	          ^
19:54:31.907	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_peerconnection_impl.dart:94:11:
19:54:31.908	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.908	        }.toJS);
19:54:31.908	          ^
19:54:31.908	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_peerconnection_impl.dart:103:13:
19:54:31.908	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.908	          }.toJS);
19:54:31.908	            ^
19:54:31.909	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_peerconnection_impl.dart:110:11:
19:54:31.909	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.909	        }.toJS);
19:54:31.909	          ^
19:54:31.909	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_data_channel_impl.dart:18:11:
19:54:31.909	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.909	        }.toJS,
19:54:31.909	          ^
19:54:31.910	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_data_channel_impl.dart:26:11:
19:54:31.910	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.910	        }.toJS,
19:54:31.910	          ^
19:54:31.910	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_data_channel_impl.dart:34:11:
19:54:31.910	Error: Function converted via 'toJS' contains invalid types in its function signature: '*Future<Null>* Function(MessageEvent)'.
19:54:31.910	        }.toJS,
19:54:31.910	          ^
19:54:31.910	../.pub-cache/hosted/pub.dev/dart_webrtc-1.4.9/lib/src/rtc_data_channel_impl.dart:40:11:
19:54:31.910	Error: Function converted via 'toJS' contains invalid types in its function signature: 'Null Function(*dynamic*)'.
19:54:31.911	        }.toJS,
19:54:31.911	          ^
19:54:31.911	Error: Compilation failed.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
19:53:40.043	Doctor summary (to see all details, run flutter doctor -v):
19:53:40.139	[!] Flutter (Channel stable, 3.27.0, on Ubuntu 22.04.4 LTS 4.4.0, locale en_US)
19:53:40.139	    ! The flutter binary is not on your path. Consider adding /opt/buildhome/repo/flutter/bin to your path.
19:53:40.140	    ! The dart binary is not on your path. Consider adding /opt/buildhome/repo/flutter/bin to your path.
19:53:40.144	[✗] Android toolchain - develop for Android devices
19:53:40.144	    ✗ Unable to locate Android SDK.
19:53:40.144	      Install Android Studio from: https://developer.android.com/studio/index.html
19:53:40.145	      On first launch it will assist you in installing the Android SDK components.
19:53:40.145	      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
19:53:40.145	      If the Android SDK has been installed to a custom location, please use
19:53:40.145	      `flutter config --android-sdk` to update to that location.
19:53:40.145	
19:53:40.148	[✓] Chrome - develop for the web
19:53:40.262	[✗] Linux toolchain - develop for Linux desktop
19:53:40.263	    ✗ clang++ is required for Linux development.
19:53:40.263	      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
19:53:40.263	    ✗ CMake is required for Linux development.
19:53:40.263	      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
19:53:40.264	    ✗ ninja is required for Linux development.
19:53:40.264	      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
19:53:40.264	    ✗ GTK 3.0 development libraries are required for Linux development.
19:53:40.264	      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
19:53:40.264	[!] Android Studio (not installed)
19:53:40.497	[✓] Connected device (2 available)
19:53:40.784	[✓] Network resources
19:53:40.784	
19:53:40.784	! Doctor found issues in 4 categories.
19:53:41.185	Setting "enable-web" value to "true".
```

</details>

**Comment by maheshj01** [comment]
Hi @scharalambous3, [dart_webrtc](https://pub.dev/packages/dart_webrtc) is a third party plugin (not owned by flutter/dart team), I would suggest filing issue in the dart-webrtc repository https://github.com/flutter-webrtc/dart-webrtc 
 
 Closing as this isn't related to flutter.

**Comment by amohr1964** [comment]
Good evening. You can solve it with "fvm" by going back to the previous version 3.24.0. With 3.27 the camera does not work. The million dollar question is, do they solve it or will it stay like this? And then they say they are from the first world. 🥇
