### ISSUE TITLE
[webview_flutter] WebViewController.setHeaders()

### ISSUE THREAD

**Issue by juandelgado** [flutter/flutter#160150]
### Use case

When embedding a web app with `webview_flutter` it's fairly common to need to send a custom set of headers for all requests. Typically things such as app version or the fact that the web app is being embedded at all.

This can currently be done for the initial request in [WebViewController.loadRequest()](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewController/loadRequest.html), but it's a lot harder to do for the requests once the web app has been loaded, since it requires intercepting them.

### Proposal

Add `WebViewController.setHeaders(Map<String, String> headers)`, similar to the already implemented [WebViewController.setUserAgent()](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewController/setUserAgent.html).

This would allow for doing something like this:

```dart
WebViewController.setHeaders({
    'X-My-App-Source': 'embedded',
    'X-My-App-Version': '1.34.3',
});
```

Which the embedded web app can use to modify its behaviour as required.

Thanks : )

**Comment by stuartmorgan** [comment]
`webview_flutter` is a wrapper for the underlying OS webview components on each platform; neither iOS nor Android's webview provided a method like this, so there isn't anything for us to wrap and expose.

Given that, closing as out of scope.
