### ISSUE TITLE
Fullscreen route transition broken on 3.27.0(stable)

### ISSUE THREAD

**Issue by yuukiw00w** [flutter/flutter#160135]
### Steps to reproduce

Same steps at #159289 
The same issue is occurring.
It seems the fix has not yet been merged into the stable branch.

### Expected results

The underlying route should not be transitioned out when a fullscreen route is pushed on top.

### Actual results

The underlying route is transitioned out to the left side while the fullscreen route is pushed from bottom up. This leads to a broken transition animation.

### Code sample

https://github.com/kuhnroyal/flutter_route_transition

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 14.6.1 23G93 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for iPhone 15 Pro. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for 野瀬田裕樹のiPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for 野瀬田裕樹のiPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @yuukiw00w, the fix is not yet in stable. It is only on the master channel. You may request a cherry-pick using the process outlined below. 

Closing as this has already been fixed. Thank you 

https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process/e7b042dd481d4ac66477fb281b6e626e8dba8a4e#how-do-i-request-a-cherry-pick

**Comment by yuukiw00w** [comment]
@danagbemava-nc 

https://github.com/flutter/flutter/issues/159289#issuecomment-2502178232

Despite the expectations outlined in this comment, it was released in a broken state.
I think there is an issue with the release process.
If a cherry-pick request is not submitted, does that mean it’s acceptable to leave it unresolved until the next minor version?
