### ISSUE TITLE
Unable to show snackbar

### ISSUE THREAD

**Issue by kasonde** [flutter/flutter#16011]
Whenever I have this code: 
`Scaffold.of(context).showSnackBar(new SnackBar(content: new Text("")))`
in the build function of the main App Widget, I get back this log. What could be the problem?
`
Reloaded 2 of 485 libraries in 602ms.
I/flutter (10562): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (10562): The following assertion was thrown while handling a gesture:
I/flutter (10562): Scaffold.of() called with a context that does not contain a Scaffold.
I/flutter (10562): No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This
I/flutter (10562): usually happens when the context provided is from the same StatefulWidget as that whose build
I/flutter (10562): function actually creates the Scaffold widget being sought.
I/flutter (10562): There are several ways to avoid this problem. The simplest is to use a Builder to get a context that
I/flutter (10562): is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
I/flutter (10562):   https://docs.flutter.io/flutter/material/Scaffold/of.html
I/flutter (10562): A more efficient solution is to split your build function into several widgets. This introduces a
I/flutter (10562): new context from which you can obtain the Scaffold. In this solution, you would have an outer widget
I/flutter (10562): that creates the Scaffold populated by instances of your new inner widgets, and then in these inner
I/flutter (10562): widgets you would use Scaffold.of().
I/flutter (10562): A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, then use the
I/flutter (10562): key.currentState property to obtain the ScaffoldState rather than using the Scaffold.of() function.
I/flutter (10562): The context used was:
I/flutter (10562):   SignUpPage(state: _SignUpPageState#3aee7)
I/flutter (10562):
I/flutter (10562): When the exception was thrown, this was the stack:
I/flutter (10562): #0      Scaffold.of (package:flutter/src/material/scaffold.dart:691:5)
I/flutter (10562): #1      _SignUpPageState.build.<anonymous closure> (/data/user/0/com.example.smartsaver/cache/smartsaverCPMDQS/smartsaver/lib/screens/auth/SignUp.dart:133:37)
I/flutter (10562): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
I/flutter (10562): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
I/flutter (10562): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (10562): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (10562): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter (10562): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (10562): #8      BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (10562): #9      BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (10562): #10     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (10562): #11     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (10562): #12     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (10562): #13     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:134)
I/flutter (10562): #14     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
I/flutter (10562):
I/flutter (10562): Handler: onTap
I/flutter (10562): Recognizer:
I/flutter (10562):   TapGestureRecognizer#75676(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (10562):   Offset(215.0, 658.2), sent tap down)
I/flutter (10562): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10562): Another exception was thrown: Scaffold.of() called with a context that does not contain a Scaffold.
`

**Comment by peng8350** [comment]
I got the same problem,But I try to move the showSnackBar to another class,such like this:
```
class ToastShower extends StatelessWidget{
  
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new GestureDetector(

      child:new Text("显示Toast"),
      onTap: () {
        SnackUtils.show(context, "show Toast");
      },
    );
  }
}

```
This has solved my problem.But the solution is really too much trouble,Is there another convenient solution?
