### ISSUE TITLE
Unable to get text from raised buttons using flutter_driver(QA environment)

### ISSUE THREAD

**Issue by deonchimple** [flutter/flutter#16013]
## Steps to Reproduce

Trying to get text from raised buttons throws an exception. While driver.getText(....) works mostly fine with other widgets, raised button seems to be causing some issues.

## Logs
```
DriverError: Error in Flutter application: Uncaught extension error while executing get_text: type 'MyButton' is not a subtype of type 'Text' of 'text' where
   MyButton is from package:maui/games/match_the_following.dart
   Text is from package:flutter/src/widgets/text.dart

 #0      FlutterDriverExtension._getText (package:flutter_driver/src/extension/extension.dart:333)
 <asynchronous suspension>
 #1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:168)
 <asynchronous suspension>
 #2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:370)
 <asynchronous suspension>
```

**Comment by Hixie** [comment]
Can you include a reduced example? The app code and driver code that shows the problem? Thanks.

**Comment by dbenninger** [comment]
I have got the same problem, but with a `TextField`. It seems that `getText` only works with the `Text` component:

`DriverError: Error in Flutter application: Uncaught extension error while executing get_text: type 'TextField' is not a subtype of type 'Text'`

Example code:
...
`children: <Widget>[
          new Text(
            'Client private key:',
          ),
          new TextField(
              key: Key('private key field'), controller: _privateKeyController),
          new Text(
            'Client public key:',
          ),`
...

test code:
...
`test('can generate key pair', () async {
      // Record the performance timeline of things that happen inside the closure
      await driver.traceAction(() async {
        // Find the scrollable user list

        var privateKey = await driver.getText(find.byValueKey('private key field'));`

...

**Comment by Hixie** [comment]
Overzealous bot.

**Comment by PauloKeller** [comment]
Maybe I facing the same issue with TextFormFields: 

> DriverError: Error in Flutter application: Uncaught extension error while executing get_text: type 'TextFormField' is not a subtype of type 'Text' 

Some solution!?

**Comment by sceee** [comment]
I am facing the same issue with RichText:

> DriverError: Error in Flutter application: Uncaught extension error while executing get_text: type 'RichText' is not a subtype of type 'Text'

In general it would be great to have a `driver.getWidget(finder)` method that would allow to access some properties of the returned "widget" that could allow manual comparison of some content of the widget.

**Comment by DK15** [comment]
@deonchimple I just ran a test to validate `raised button` text using `find.text()` and it worked for me.

Here's what I did:

```
home: Center(
          child: RaisedButton(
            onPressed: () {},
            child: Text('Click me'),
          ),
        )
```

And test:

```
test('test raisedbutton text', () async {
        final SerializableFinder buttonTextFinder = find.text('Click me');

        await driver.waitFor(buttonTextFinder);
        await driver.tap(buttonTextFinder);
        print('button clicked');
      });
```

Result:

![Screen Shot 2019-07-18 at 5 06 40 PM](https://user-images.githubusercontent.com/16548367/61454494-b0e0b280-a97e-11e9-9c3d-f8c38b572863.png)

**Comment by AnhPhamIT** [comment]
Same issue for me with TextFromField
main.dart

```
new TextFormField(
key: new Key('welcome'),
decoration: new InputDecoration(labelText: 'welcome ...'),
validator: (val) =>
val.isEmpty ? 'Welcome can\'t be empty.' : null,
),
```

test_driver\home_test.dart
`    await driver.getText(txtFinder);`

Is there any solution for this?

**Comment by ManojMM026** [comment]
Anything on TextFormField ?

**Comment by SwapTact** [comment]
I am also having this issue:
<pre>
DriverError: Error in Flutter application: 
    Uncaught extension error while executing get_text: 
        type 'EditableText' is not a subtype of type 'Text'
</pre>
This makes it impossible for me to test/verify the "initialValue:" of a TextFormField.

**Comment by sowens-csd** [comment]
I've found that 
```Dart
await driver.waitFor(find.text("some text to look for"));
```
Does work for finding text in TextFormField widgets.

**Comment by kf6gpe** [comment]
Given @sowens-csd 's comment on TextFormField widgets was the last case to be discussed, I'm going to close this issue as fixed.

**Comment by boskokg** [comment]
I don't understand why this ticked is closed? Issue is that we cannot get text from mostly used components. All previous comments are some workarounds for getting things done.

getText method should be able to get text from the tested component and flutter team should provide that somehow.
