### ISSUE TITLE
[Impeller] glitches on Android emulator 35.2.10 / Windows Host.

### ISSUE THREAD

**Issue by AresVampire** [flutter/flutter#160133]
### Steps to reproduce

I have upgraded the Flutter version to 3.27.0 and now the app is glitching even for a basic demo app.

### Expected results

Expected a smooth-running app.

### Actual results

Glitching app with dozens of console logs.

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(child: CircularProgressIndicator()),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/user-attachments/assets/9f248675-b31a-41f5-84e4-a021351838e2

</details>

### Logs

<details open><summary>Logs</summary>

```console
Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on sdk gphone64 x86 64 is available at: http://127.0.0.1:62080/C-dP2MJNJL4=/     
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:62080/C-dP2MJNJL4=/
I/MESA    ( 9593): on_vkCreateFence: ensure sync device
I/MESA    ( 9593): on_vkCreateFence: getting fence info
I/MESA    ( 9593): on_vkCreateFence: info set (fence still -1). fence: 0x79f45d0a8a90
I/MESA    ( 9593): on_vkGetFenceFdKHR: got fd: 146
I/MESA    ( 9593): on_vkCreateFence: ensure sync device
I/MESA    ( 9593): on_vkCreateFence: getting fence info
I/MESA    ( 9593): on_vkCreateFence: info set (fence still -1). fence: 0x79f45d0bf6d0
I/MESA    ( 9593): on_vkGetFenceFdKHR: got fd: 148
I/MESA    ( 9593): on_vkCreateFence: ensure sync device
I/MESA    ( 9593): on_vkCreateFence: getting fence info
I/MESA    ( 9593): on_vkCreateFence: info set (fence still -1). fence: 0x79f45d0c3810
I/MESA    ( 9593): on_vkGetFenceFdKHR: got fd: 150
I/MESA    ( 9593): on_vkCreateFence: ensure sync device
I/MESA    ( 9593): on_vkCreateFence: getting fence info
I/MESA    ( 9593): on_vkCreateFence: info set (fence still -1). fence: 0x79f45d0b3e50
I/MESA    ( 9593): on_vkGetFenceFdKHR: got fd: 153
I/MESA    ( 9593): on_vkCreateFence: ensure sync device
I/MESA    ( 9593): on_vkCreateFence: getting fence info
I/MESA    ( 9593): on_vkCreateFence: info set (fence still -1). fence: 0x79f45d0d8690
I/MESA    ( 9593): on_vkGetFenceFdKHR: got fd: 150
I/MESA    ( 9593): on_vkCreateFence: ensure sync device
I/MESA    ( 9593): on_vkCreateFence: getting fence info
I/MESA    ( 9593): on_vkCreateFence: info set (fence still -1). fence: 0x79f45d0b16d0
I/MESA    ( 9593): on_vkGetFenceFdKHR: got fd: 150
I/MESA    ( 9593): on_vkCreateFence: ensure sync device
I/MESA    ( 9593): on_vkCreateFence: getting fence info
I/MESA    ( 9593): on_vkCreateFence: info set (fence still -1). fence: 0x79f45d0be190
I/MESA    ( 9593): on_vkGetFenceFdKHR: got fd: 150
I/MESA    ( 9593): on_vkImportFenceFdKHR: import actual fd, dup and close()
I/MESA    ( 9593): on_vkWaitForFences: scheduling ext waits
I/MESA    ( 9593): on_vkWaitForFences: wait on 150
I/MESA    ( 9593): done waiting on fd 150
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows       
    [Version 10.0.19045.5247], locale en-US)
    • Flutter version 3.27.0 on channel stable at
      C:\Users\h\fvm\versions\3.27.0
    • Upstream repository https://github.com/flutter/flutter.git    • Framework revision 8495dee1fd (28 hours ago), 2024-12-10  
      14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10
    or higher)

[√] Android toolchain - develop for Android devices (Android SDK    version 35.0.0)
    • Android SDK at C:\Users\h\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android   
      Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build    
      21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program
      Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio
    Community 2022 17.11.5)
    • Visual Studio at C:\Program Files\Microsoft Visual        
      Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35327.3        
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio 
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter        
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      21.0.3+-12282718-b509.11)

[√] VS Code (version 1.96.0)
    • VS Code at C:\Users\h\AppData\Local\Programs\Microsoft VS 
      Code
    • Flutter extension version 3.103.20241202

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64      • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64      • Microsoft Windows [Version 10.0.19045.5247]
    • Chrome (web)                 • chrome        •
      web-javascript • Google Chrome 131.0.6778.110
    • Edge (web)                   • edge          •
      web-javascript • Microsoft Edge 131.0.2903.86

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
What is your android emulator binary version? 

fairly recent android emulator versions had serious Vulkan bugs. If you're not on the very latest version i'd try updating.

**Comment by AresVampire** [comment]
My Android emulator version is 35.2.10

**Comment by CaoGiaHieu-dev** [comment]
have same issue when run on simulator app start crash without log

**Comment by AresVampire** [comment]
I think this is related to Vulkan support. Since my GPU is GT 740, it doesn't support Vulkan. Disabling the impeller seems working smoothly on the emulator now.

**Comment by jonahwilliams** [comment]
I'm not sure that is the case, the android emulator is running in QEMU with swiftshader, I didn't think it used the host drivers at all - but I could be wrong. At any rate, i would expect the device to report that it doesn't support vulkan rather than not working. :(

**Comment by mateoghione99** [comment]
have same issue

I/MESA    (24907): on_vkCreateFence: ensure sync device
I/MESA    (24907): on_vkCreateFence: getting fence info
I/MESA    (24907): on_vkCreateFence: info set (fence still -1). fence: 0x7f059d799b10

**Comment by justyork** [comment]
same, starts yesterday...

**Comment by ruwiss** [comment]
Any solution?

**Comment by Jazzykhan** [comment]
same.
I am using ubuntu. and changed the gpu mode to host in config.ini on avd folder. without it the emulator was crashing,.

**Comment by TheSHEEEP** [comment]
Same issue, although it doesn't cause an app crash for me.
But the log spam is very bothersome.

**Comment by ikyyy777** [comment]
same, downgrading to 3.25 version and it fixed the problem

**Comment by codertapsu** [comment]
I got the same issue after upgrading to v3.27 I resolved it by downgrading it back to v3.26

**Comment by Jazzykhan** [comment]
> I got the same issue after upgrading to v3.27 I resolved it by downgrading it back to v3.26

Are you on windows?

**Comment by codertapsu** [comment]
> > same, downgrading to 3.25 version and it fixed the problem
> 
> which OS you are using?

I am using windows 11

**Comment by TheSHEEEP** [comment]
I am on Linux - but as I wrote, I do not get any crash, "just" the log spam.

**Comment by jonahwilliams** [comment]
I believe this can be fixed by disabling surface control. if you're encountering this problem try adding the following line to your AndroidManifest:

```
<meta-data
    android:name="io.flutter.embedding.android.DisableSurfaceControl"
    android:value="true" />
    ```
    
We plan to cherry pick a change that will disable surface control for all devices

**Comment by jonahwilliams** [comment]
Flutter 3.27.1 is available on the stable channel and should have the fix for the originally reported issue. If you are experiencing similar symptoms but it is not fixed by the hotfix please file a new bug.

**Comment by AresVampire** [comment]
Same on Flutter 3.27.1. I am sure it is related to Vulkan. Disabling the impeller solves the problem.

`flutter run -d emulator-5554 --no-enable-impeller`

My concern is whether I have to disable the impeller for the release version as well. From my research, it seems the version built with the impeller enabled won't work on some phones without Vulkan support. So, if a Flutter-built app can automatically detect the phone's support for Vulkan and disable the impeller if the phone doesn't support it, it would be great. For example, it works for Flutter web with SKIA enabled on a PC browser but using HTML on mobile automatically.
