### ISSUE TITLE
Can't omitted 'new' and 'const' word.

### ISSUE THREAD

**Issue by kuochaoyi** [flutter/flutter#16017]
## Steps to Reproduce

When I enabled `--preview-dart-2` option in Flutter plugin for Android Studio 3.0. I can omitted `new` and `const` keywords.

Today i upgraded to 3.1(Android Studio) and Flutter plugin 0.23.2. the option's be deleted. and I can't omitted that keywords. I upgraded flutter framework to newly.

## Version

`Flutter 0.2.5-pre.55 • channel master • https://github.com/flutter/flutter.git Framework • revision 39eeec47d6 (11 hours ago) • 2018-03-27 15:27:24 -0700 Engine • revision 3e877d371a Tools • Dart 2.0.0-dev.40.0.flutter-06949dc985`

## Logs

`Performing full restart...
compiler message: lib/main.dart:71:16: Error: The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
compiler message:         title: Text(widget.title),
compiler message:                ^
compiler message: lib/main.dart:92:13: Error: The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
compiler message:             Text(
compiler message:             ^
compiler message: lib/main.dart:95:13: Error: The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
compiler message:             Text(
compiler message:             ^
compiler message: lib/main.dart:73:13: Error: The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
compiler message:       body: Center(
compiler message:             ^
compiler message: lib/main.dart:105:16: Error: The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
compiler message:         child: Icon(Icons.add),
compiler message:                ^
compiler message: lib/main.dart:102:29: Error: The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
compiler message:       floatingActionButton: FloatingActionButton(
compiler message:                             ^
compiler message: lib/main.dart:67:12: Error: The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here.
compiler message:     return Scaffold(
compiler message:            ^
Restarted app in 2,984ms.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CompileTimeError was thrown building MyHomePage(dirty, state:
_MyHomePageState#6cd5b):
'file:///Users/kuochaoyi/AndroidStudioProjects/flutter_android_3_1/lib/main.dart': error: line 67
pos 12: lib/main.dart:67:12: Error: The keyword 'const' or 'new' is required here. Due to an
implementation limit, the compiler isn't able to infer 'const' or 'new' here.
return Scaffold(
^
return Scaffold(
^

When the exception was thrown, this was the stack:
#0      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
#1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#3      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#19     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4742:32)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#72     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#81     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#97     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#103    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#108    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#109    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#116    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#119    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4742:32)
#120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#122    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
#123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#128    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#129    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#134    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#138    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#144    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#145    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#148    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#151    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#152    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#156    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#157    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#158    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#164    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#166    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#167    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#172    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#173    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#177    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#178    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#179    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#180    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#184    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#185    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#189    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#190    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#191    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#195    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#196    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#197    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#198    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#202    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#203    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#204    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#205    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#209    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#210    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#212    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#214    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#215    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#216    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#217    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#218    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#221    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#222    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#223    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#224    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#225    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#228    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#229    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#230    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#234    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#235    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#236    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#239    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#240    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#241    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#242    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#243    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#246    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#247    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#248    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#249    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#253    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#254    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#255    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#256    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#259    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#260    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#261    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#262    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#263    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#264    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
#265    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
#266    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
#267    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
#268    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
#269    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
#270    runApp (package:flutter/src/widgets/binding.dart:699:7)
#271    main (file:///Users/kuochaoyi/AndroidStudioProjects/flutter_android_3_1/lib/main.dart:3:16)
#272    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#273    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
════════════════════════════════════════════════════════════════════════════════════════════════════
`

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

**Comment by kuochaoyi** [comment]
Sorry. I forward the issue to flutter/flutter-intellij.

**Comment by zoechi** [comment]
That's still work in progress and not supposed to work yet.

**Comment by a14n** [comment]
dup of #15590
