### ISSUE TITLE
[Proposal]Provide a alternative to deprecated `Color.value`

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#160184]
### Use case

In Flutter 3.17.0, `Color.value` was deprecated.

The same `Color` object has a constructor that accepts an integer (and it is not deprecated), which makes no sense (a one-way only conversion???).

Also, there is no other method in the `Color` object to get the integer value of a color (this is needed for color serialization).

What is the purpose of this deprecation? A color is a color, it has ARGB. Flutter already have other color utilities in packages, such as the `Hct` color model (which has only a `fromInt` factory to convert a color to HCT).

### Proposal

Since all platforms uses 32-bit color, why deprecated it? At very least, create a method called `toARGB32()` with the same code that value has (it shouldn't be a method, but, at least is consistent with `toString()`).

**Comment by jonahwilliams** [comment]
I mean its still there, and we won't remove it for many releases anyway

But I understand the request as being don't deprecate it, because its too convenient. We did add a to ARGB32 method but that didn't make it in the release cut. I don't know if the deprecation is worth the pain anyway.

**Comment by maurovanetti** [comment]
The constructor of `MaterialColor` uses the deprecated int value.

**Comment by maheshj01** [comment]
Hi @JCKodel, Thanks for filing the issue. Labeling this issue as a valid proposal.

**Comment by MrCsabaToth** [comment]
Why is it deprecated. As the post says there a constructor. I ended up lifting the two functions into a `ColorEx` extension. But everyone will do that now?

```
import 'dart:ui';

/// This class is to supplement deprecated_member_use for value
/// value converted RGBA into a 32 bit integer, but the SDK doesn't provide
/// a successor?
extension ColorEx on Color {
  static int floatToInt8(double x) {
    return (x * 255.0).round() & 0xff;
  }

  /// A 32 bit value representing this color.
  ///
  /// The bits are assigned as follows:
  ///
  /// * Bits 24-31 are the alpha value.
  /// * Bits 16-23 are the red value.
  /// * Bits 8-15 are the green value.
  /// * Bits 0-7 are the blue value.
  int get toInt32 {
    return floatToInt8(a) << 24 | floatToInt8(r) << 16 | floatToInt8(g) << 8 | floatToInt8(b) << 0;
  }
}
```

**Comment by nickcuypers** [comment]
I did exactly the same as @MrCsabaToth, for now that seems the only way to have no wartnings about deprecations and still be able to use the constructor of MaterialColor. 
I've been following this Issue since opening and the deprecation should be lifted or any alternative should be presented. Now you leave a lot of devs with no other option then add these methods themselves which isn't a clean solution at all

**Comment by deakjahn** [comment]
> Why is it deprecated? As the post says there a constructor. I ended up lifting the two functions into a `ColorEx` extension. But everyone will have to do that now?

It would probably be wise to name it `toARGB32()` and then you'll only need to remove the extension when it's fixed...

**Comment by deakjahn** [comment]
Not because it's a better name but because the Flutter devs already told us above that `toARGB32()` _was_ the intended, new replacement for the `value` getter, only that the deprecation made it into the current version and the new function missed the train. But, I suspect, it will, so we will have the function from the next version forward.

As to the second, I simply went with withValues(alpha)... :-)

**Comment by atbeat** [comment]
I agree with most that color.value should NOT be deprecated, especially for novice developers. If something is working why deprecate it to make life difficult for most, unless there is a strong reason, and that should be clearly stated, what we are deprecating what is the correct alternative, and now to implement the new code with ease.

**Comment by lsaudon** [comment]
`WidgetStateColor`want this value

**Comment by filiph** [comment]
`Color.value` is also the most convenient way to feed `Vertices.raw()` with color values, since it expects an `Int32List` of colors. So I assume that we need to ignore the warning for now and update to `toARGB32()` when that's available?

Also, I'm not sure what the performance implications are. As far as I understood it, `Color.value` used to be a simple accessor to a single `int`. From now on, it's a computation involving multiplication, rounding, and some bitwise arithmetic. Since I'm running this in a very tight loop (generating vertices data every frame), I have to worry about these things. I could make my own little simplified color class I guess since my `drawVertices()` code definitely doesn't worry about color spaces.

**Comment by JCKodel** [comment]
> Color.value used to be a simple accessor to a single int

It's not.

It is exactly the implementation @MrCsabaToth wrote above (which I believe he copied from Flutter's code, as I did).

There's a lot of code out there that expects an int colour (Material Color Utilities, for instance, in `DynamicScheme` asks for a `sourceColorArgb`).

The whole problem is not about colour at all, it's about messing with something without apparently any regards for impact. It seems something done hasty, for some other purpose (maybe to show that we support iPhone better?). I know other colour schemes, such as P3 and HDR needs more bits for colours, hence the colour being expressed in double instead of a byte, but new features should be that: new features. 

**Maybe some nice new library about Colour? With support for many colour spaces *and* different colour representations, such as HSL, HSV, etc?**

If such functionality is available, then the original Color could be deprecated (but not before we had some options).

Another very important thing to say is: some developers, including me, don't work with warnings. In the old days, my Visual Studio had `warningAsErrors = true`. Why? Because warnings are things that can bite us later, and they should not be ignored. Once our IDE's (or glorified notepads) starts to show a lot of warnings that we should ignore for *many* months, we tend to not pay attention to them any more. So, an important feature of our tooling must not be used any more.

**Comment by filiph** [comment]
> > Color.value used to be a simple accessor to a single int
> 
> It's not.

I know. My point was that it used to be: https://github.com/flutter/flutter/blob/285d77e993a4645910235132d05152b272c8a900/engine/src/flutter/lib/ui/painting.dart#L147

**Comment by naamapps** [comment]
I'm using Color.value to serialize and save colors inside my app local DB, this depreciation will eventually urge me to do a DB migration to serialize colors in a different way - while it's not so difficult to do, I really don't see the point as to why this was needed to be done in the first place.
Please don't rush into deprecating long standing properties/features that almost every Flutter developer uses in their app - it's super frustrating and lowers people's trust in the Flutter ecosystem.
And if you do decide to deprecate a feature for whatever reason, it should at least come with an alternative.

**Comment by matanlurey** [comment]
There is an alternative that is not deprecated and coming in the next stable, it's [`toARGB32()`](https://main-api.flutter.dev/flutter/dart-ui/Color/toARGB32.html); our apologies for it not making it into the 3.27 release; we do guarantee that method will stick around and not be deprecated.

In terms of changing Color _back_ to being reified as a single integer - to be blunt, that is not going to happen. If `Color` was a sealed class (where we totally controlled the type hierarchy), we could have done (something) like:

```txt
Color
|- Color8Bit
```

... but that, as of right now, would be massively breaking.

---

> @filiph:
>
> Since I'm running this in a very tight loop (generating vertices data every frame), I have to worry about these things. I could make my own little simplified color class I guess since my `drawVertices()` code definitely doesn't worry about color spaces.

That would be my recommendation. The other alternative (above) is massively breaking.

---

As this will be "fixed" (albeit, not in a way everyone wants) in the upcoming stable, I'm marking this as closed.
