### ISSUE TITLE
Abnormal memory usage when `FontLoader.load`ing the same fonts multiple times

### ISSUE THREAD

**Issue by vitto4** [flutter/flutter#160185]
### Steps to reproduce

1. Create a new Flutter project : `flutter create bug && cd bug`
2. - Create a `fonts` folder : `mkdir fonts`.
	- Download [these fonts](https://fonts.google.com/share?selection.family=Noto+Sans+JP:wght@100..900|Noto+Serif+JP:wght@200..900).
	- Place both `NotoSansJP-VariableFont_wght.ttf` and `NotoSerifJP-VariableFont_wght.ttf` in the folder.
3. Add the fonts in `pubspec.yaml` :
	```yaml
	# ...
	flutter:
	  # ...
	  fonts:
	    - family: NotoSansJP
	      fonts:
	        - asset: fonts/NotoSansJP-VariableFont_wght.ttf
	    - family: NotoSerifJP
	      fonts:
	        - asset: fonts/NotoSerifJP-VariableFont_wght.ttf
	```
4. Replace `lib/main.dart` with the code below (in code sample section).
5. Run the app (`flutter run ...`). Tested on android and web, in `debug` and `profile` build modes.
6. Repeatedly click the blue container.
7. Watch the memory usage, either in your browser's task manager (usually <kbd>Shift</kbd> + <kbd>Esc</kbd>) or in the `memory` tab of Flutter DevTools.

### Expected results

Used memory grows on first run and doesn't increase further (?)

### Actual results

Memory used by the app increases quite fast, I was able to reach 1 GB in a few seconds. It doesn't seem to ever stop as long as one keeps clicking the container. It also doesn't seem to come down.

Looking at a memory snapshot in Chrome, the results seem to be roughly the same as in #153678.
> Basically all the RAM is taken by some `JSArrayBufferData` object

### Notes
- It still seems to occur but (significantly) slower with `--web-renderer html`.
- It seems to be related to large (CJK ?) fonts.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(
      MaterialApp(
        onGenerateRoute: (_) => MaterialPageRoute(builder: (context) => const LeakPage()),
      ),
    );

class LeakPage extends StatelessWidget {
  const LeakPage({
    super.key,
  });

  /// This would also have worked in a loop, but it gets out of hand real fast, hence the clickable container.
  Future<int> leak() async {
    final fontLoaderNotoSansJP = FontLoader('NotoSansJP')
      ..addFont(
        rootBundle.load("fonts/NotoSansJP-VariableFont_wght.ttf"),
      );
    await fontLoaderNotoSansJP.load();

    final fontLoaderNotoSerifJP = FontLoader('NotoSerifJP')
      ..addFont(
        rootBundle.load("fonts/NotoSerifJP-VariableFont_wght.ttf"),
      );
    await fontLoaderNotoSerifJP.load();

    return 1;
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: leak(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done) {
          return GestureDetector(
            onTap: () {
              Navigator.of(context).pushNamedAndRemoveUntil(
                '/',
                (Route<dynamic> route) => false,
              );
            },
            child: Container(
              color: Colors.blue,
            ),
          );
        } else
          return Scaffold(
            body: Placeholder(),
          );
      },
    );
  }
}
```

</details>

### What target platforms are you seeing this bug on?

Android, Web

#### Web
- Firefox 133.0.3
- Chrome 131.0.6778.140 (64 bits)

#### Android
- Android 11 (armv8-a)
- Android 13 (armv8-a)

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on Ubuntu 22.04.5 LTS 5.15.167.4-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 3.24.5 on channel stable at /home/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /usr/lib/android-sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 20.0.2+9-78)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.5 LTS 5.15.167.4-microsoft-standard-WSL2

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by jonahwilliams** [comment]
So AFAIK there is no actual way to know from just the name that something is the "same" font. Could be different versions of the same font, or different fonts with similar names, et cetera. So its unlikely that we can do anything here.

**Comment by vitto4** [comment]
Ahh yes makes sense !
Though, wouldn't it be possible to check the hash of the font file before loading it again ?

Also, memory usage seems to go up by anywhere from 30 ～ 150+ MB with each click on the container, even though the fonts are only a combined 22 MB.
I don't know what happens behind the scenes, but that sounds a little odd to me.

**Comment by jonahwilliams** [comment]
Hashing a font is going to be very expensive and also no guarantee that they're the same

**Comment by jonahwilliams** [comment]
I'm closing this as infeasible for reasons I discussed above.
