### ISSUE TITLE
[Impeller] AHB swapchain usage on Pixel 5 emulator (broken emulator check?).

### ISSUE THREAD

**Issue by vargab95** [flutter/flutter#160168]
### Steps to reproduce

1. Start a pixel 5 emulator
2. Create a new project by running flutter create test
3. cd test
4. flutter run -d em

### Expected results

The example app comes up.

### Actual results

The example add crashes.

### Code sample

The source code generated by flutter create test.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...                          
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
Running Gradle task 'assembleDebug'...                             11.5s
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...          699ms
I/flutter ( 6053): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
E/flutter ( 6053): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(108)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find memory type of external image.
E/flutter ( 6053): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2274)
E/flutter ( 6053): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(108)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find memory type of external image.
E/flutter ( 6053): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2274)
E/flutter ( 6053): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(108)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find memory type of external image.
E/flutter ( 6053): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_texture_pool_vk.cc(69)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create hardware buffer texture source for swapchain image of size: (1080, 2274)
Syncing files to device sdk gphone64 x86 64...                  
E/flutter ( 6053): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(110)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 6053): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
E/flutter ( 6053): [ERROR:flutter/impeller/renderer/backend/vulkan/swapchain/ahb/ahb_swapchain_impl_vk.cc(110)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create AHB texture source.
E/flutter ( 6053): [ERROR:flutter/shell/gpu/gpu_surface_vulkan_impeller.cc(58)] No surface available.
Syncing files to device sdk gphone64 x86 64...                      96ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on sdk gphone64 x86 64 is available at: http://127.0.0.1:39585/0hVlAIZ_aig=/
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:39585/0hVlAIZ_aig=/
D/ProfileInstaller( 6053): Installing profile for com.example.test

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.27.0, on Debian GNU/Linux 12 (bookworm) 6.1.0-28-amd64, locale en_US.UTF-8)
    • Flutter version 3.27.0 on channel stable at /home/vargab95/devtools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (2 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/vargab95/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /var/lib/flatpak/exports/bin/com.google.Chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (version unknown)
    • Android Studio at /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir = /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.98.0

[✓] VS Code (version 1.95.3)
    • VS Code at /var/lib/flatpak/app/com.visualstudio.code/x86_64/stable/active/files/extra/vscode
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Debian GNU/Linux 12 (bookworm) 6.1.0-28-amd64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 131.0.6778.108

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by jonahwilliams** [comment]
What emulator binary version are you running on and what host platform?

> Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find memory type of external image.

Does your app have platform views, or is this happening on hello world too?

**Comment by lucas404x** [comment]
This is happening on my application as well.

[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.22631.4602], locale pt-BR)
    • Flutter version 3.27.0 on channel stable at C:\dev\flutter\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (2 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Josel\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.12.35527.113
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.96.0)
    • VS Code at C:\Users\Josel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.4602]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 130.0.6723.92
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 131.0.2903.86

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by jonahwilliams** [comment]
It looks like our logic to detect emulators is failing and we're trying to use the AHB swapchain which is known to not work with emulators.

**Comment by vargab95** [comment]
@jonahwilliams 

Emulator version: Android emulator version 35.2.10.0 (build_id 12414864) (CL:N/A)
OS: Debian GNU/Linux 12 (bookworm)

It happens with the basic app template generated with the "flutter create" command (flutter version 3.27.0).

**Comment by vargab95** [comment]
It works fine with 3.27.1. Thanks for the quick fix! I really appreciate it.
