### ISSUE TITLE
Need know the next route name in the didPopNext call

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#16019]
I have a Page A , and there are two button , when I press button1 I want to it is pushed to Page B ,and pushed to Page C when press button2 ,but I need do someting before push , how coudl I know which page it will be pushed to?

**Comment by realcarlos** [comment]
And another case:   PageA - push -> PageB, PageA -push-> PageC ,when pop from B or C ,I need to know where it is poped from, any idea?

**Comment by zoechi** [comment]
StackOverflow is a better place to ask how-to questions

**Comment by zoechi** [comment]
Were you able to make this work?
I'm going to close the issue because it's not clear if there is something the Flutter team needs to do.
Feel free to add a comment to get the issue reopened or create a new issue.
