### ISSUE TITLE
After scrolling, Top Text field value vanishes when focus to another text field inside ListView.

### ISSUE THREAD

**Issue by smruti-ranjan-rana** [flutter/flutter#16028]
![flutterissue](https://user-images.githubusercontent.com/30388973/38043774-a2c7e252-32d5-11e8-943b-67dcf30500f0.gif)

**Comment by zoechi** [comment]
Might be a dup of #14104

**Comment by leonemdev** [comment]
I have assigned individual controllers to my TextFormFields (with initialValue specified and I have attempted the exact code provided in [15484 ](https://github.com/flutter/flutter/pull/15484) and get the same result as discussed above. Scrolling immediately clears the content of the ListView fields.

**Comment by zoechi** [comment]
Where did you hold the references to the `TextInputControllers`? If they are created inside `build()` they are dropped and recreated every time the UI is re-rendered. They need to be held outside of `build()`
