### ISSUE TITLE
Missing CHANGELOG for 3.24.5

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#160227]
### Steps to reproduce

1. Go to https://github.com/flutter/flutter/blob/master/CHANGELOG.md
2. See that version 3.24.5 is not there

### Expected results

Version 3.24.5 changelog should be documented

### Actual results

Version 3.24.5 changelog is not documented

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
It doesn't appear in either the stable or beta changelogs either and the changelog for 3.27 is also not available on these branches 

https://github.com/flutter/flutter/blob/beta/CHANGELOG.md
https://github.com/flutter/flutter/blob/stable/CHANGELOG.md

**Comment by itsjustkevin** [comment]
https://github.com/flutter/flutter/pull/160284 and https://github.com/flutter/flutter/pull/160253 close this issue.

@danagbemava-nc the beta branch is a no-op.  We do not directly update changelogs on stable.  During our release process, when we create a new beta, master becomes the new beta branch at a specific point.  Whatever has landed on master at that time becomes the new beta branch.

**Comment by feinstein** [comment]
Thanks!
