### ISSUE TITLE
Uncommitted files preventing `flutter upgrade`

### ISSUE THREAD

**Issue by OutdatedGuy** [flutter/flutter#160200]
### Steps to reproduce

1. Upgrade flutter from v3.24.5 to v3.27.0 using command `flutter upgrade`

### Actual results

Upgrading flutter using the command `flutter upgrade` fails with the error: `You have some changes to the code, use flutter upgrade --force to force upgrade`.

So I opened the flutter folder and saw that 3 files were un-tracked in the location `packages/flutter_tools/gradle/bin/main`
- app_plugin_loader.groovy
- flutter.groovy
- native_plugin_loader.groovy

So I upgraded flutter using the `--force` flag and it got upgraded successfully, but the above mentioned files still exists.

Is it safe to delete them or should I just don't do anything about it?

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@OutdatedGuy 
You may `git stash` them to clear the path for upgrade process.
Closing as this doesn't seem to be a bug but your local setup. If you disagree, write in comments and I'll reopen it.

**Comment by darshankawar** [comment]
> my only concern is if the above mentioned files are necessary for **flutter_tools** to work correctly or not.

After upgrading, did you face any issues yet relating to those files ? I think it could be a cache issue at your end. If it has successfully upgraded and you are not facing any issues after, I think it should be fine.

**Comment by OutdatedGuy** [comment]
Hi @darshankawar, I didn't faced any issues, however just to be safe I completely uninstalled flutter and re-installed using the VS Code Plugin.

After the fresh install, these files did not exist, but while try to upgrade to v3.27.1 today, these files again popped up. I don't think these files are causing any issue other than the need to use `--force` always while upgrading flutter.

Can you investigate on this a little?

**Comment by darshankawar** [comment]
> but while try to upgrade to v3.27.1 today, these files again popped up

I upgraded to this version but didn't see this behavior. Maybe it was a bad / corrupted copy of sdk you have earlier ?
