### ISSUE TITLE
Feature Request: Make firebase_messaging support creating channels from Dart

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#16022]
In Android Oreo, notifications are encouraged to have "channels" so users can control types of notifications more easily. Can this feature be natively supported in the `firebase_messaging` plugin?

For now, I've managed to solve this problem with a semi-hacky platform channel, as below:

```java
    new MethodChannel(getFlutterView(), "notifications").setMethodCallHandler(
        new MethodCallHandler() {
            @Override
            public void onMethodCall(MethodCall call, Result result) {
                if(call.method.equals("registerChannel")) {
                    if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                        String id = call.argument("id");
                        String name = call.argument("name");
                        String description = call.argument("description");

                        NotificationChannel mChannel =
                            new NotificationChannel(id, name,
                                                    NotificationManager.IMPORTANCE_DEFAULT);
                        mChannel.setDescription(description);

                        NotificationManager notificationManager =
                            (NotificationManager) getSystemService(NOTIFICATION_SERVICE);

                        notificationManager.createNotificationChannel(mChannel);

                        result.success("Notification channel " + name + " created");
                    } else {
                        // No-op
                        result.success("Android version is less than Oreo");
                    }
                }
            }
        });
  }
```

This works, but doesn't allow us to set notification priorities without significant modifications, and would be better as part of the plugin anyway.

NB: Am willing to make a PR for this later, with the priority functionality as soon as I figure out how to do it (and if others say this is a good idea).

**Comment by markflarup** [comment]
It would be wonderful if anybody could implement the functionality to support Notification Channels (let it be in `firebase_messaging`, another package, or out-of-the-box) as this is a requirement for Android API 28 and above 🤓

**Comment by isacben** [comment]
Also looking forward to have this feature! :)

**Comment by shehrazjazib** [comment]
Please implement this feature ASAP.

**Comment by amervelic** [comment]
Implement oreo channels ! please. One year old request ! 😯

**Comment by JonathanJude** [comment]
Has anyone done this? Perhaps, OP should provide a gist as to how to handle it.

**Comment by pacifire** [comment]
@zoechi : As you guided, we added reaction to this, but this feature is still stuck, & there is no workaround for the same.

We tried to create FlutterService also, but it doesn't exists, like FlutterActivity.

Thus I request everybody to comment maximum on this issue, such that Flutter Team can help us here.

**Comment by netfirms** [comment]
Still cannot do this...

**Comment by JonathanJude** [comment]
Really sad.

**Comment by ranjanexlvis** [comment]
Dear flutter team..  we stopped working on flutter.... because this feature  is very much important. Our project is stuck due to unavailability of channelID..

**Comment by rajeshjeshar** [comment]
In order to send custom notifications we need channel ids and it sucks.. over a year ..!

**Comment by mkliger11** [comment]
@ghost 
Does the workaround work in the sense it let's you send heads up notifications?

I can only get notifications to appear subtlety in the sys tray... Can't even set default channel in manifest

**Comment by OptivolveThiyraashDavid** [comment]
What is the progress? Still the same?

**Comment by kroikie** [comment]
@ghost

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/873. Any further collaboration will be done there.

**Comment by ppavecha4** [comment]
AndroidNotificationDetails() this can be used for managing notification channels in flutter

**Comment by Yunus0or1** [comment]
Getting Notification sound in Samsung S5 but no notification sound in Samsung S9. The app uses the guidelines of Flutter firebase_messaging. Any workaround?
