### ISSUE TITLE
CupertinoPicker only rendering first and last widget on iOS

### ISSUE THREAD

**Issue by Ethras** [flutter/flutter#16029]
## Steps to Reproduce

Flutter on channel master :

- Add a CupertinoPicker  with  3-4 children of any type in your App.
- Run on iOs.
- The first item is rendered properly but if you start scrolling the next items doesn't render (picker is blank)
- When you get to the end of the picker the last item eventually load

## Flutter Doctor

[✓] Flutter (Channel master, v0.2.5-pre.57, on Mac OS X 10.13.3 17D47, locale fr-CH)
    • Flutter version 0.2.5-pre.57 at /Users/vladimir/flutter
    • Framework revision c5288c7346 (79 minutes ago), 2018-03-28 08:32:27 -0700
    • Engine revision dd6f46c485
    • Dart version 2.0.0-dev.41.0.flutter-2f68e82526

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.1

[✓] Connected devices (1 available)
    • iPhone • 5ac2f63dedb336eebbcb8b0a4050229b4dbda9e1 • ios • iOS 11.2.6

! Doctor found issues in 2 categories.

**Comment by Ethras** [comment]
![395119b8-5958-48c2-a3d1-066225c817da](https://user-images.githubusercontent.com/17152220/38045471-22ed7d8e-32bd-11e8-8840-a3f431c69506.png)

**Comment by xster** [comment]
Looks like https://bugs.chromium.org/p/skia/issues/detail?id=7537 is back. Can you let me know which iPhone is it?

**Comment by Ethras** [comment]
The screenshot above is from an iPhone 5s (physical device) and I also tried with the simulator on a iPhone 8 If i remember correctly

**Comment by xster** [comment]
Yes, I can reproduce. Patch in review.
