### ISSUE TITLE
Enum AutovalidateMode has incorrect capitalization

### ISSUE THREAD

**Issue by StanleyCocos** [flutter/flutter#160240]
I noticed some inappropriate naming conventions in the code while reviewing it,
I'd like to make a request regarding this, but the issue seems disruptive. Once modified, the impact could be significant. I'm not sure how to approach this in general.
https://github.com/flutter/flutter/blob/26ea690af8adc6d58a4eca098211a37feb23b4d8/packages/flutter/lib/src/widgets/form.dart#L768

https://github.com/flutter/flutter/blob/26ea690af8adc6d58a4eca098211a37feb23b4d8/packages/flutter/lib/src/widgets/form.dart#L784

The same issue applies to: https://github.com/flutter/flutter/issues/115820

**Comment by mit-mit** [comment]
I don't see an issue with the second one -- "unfocused" is a single word, not two.

**Comment by maheshj01** [comment]
Hi @StanleyCocos, Thanks for filing the issue.  Looks like a valid proposal to me.
enum `AutovalidateMode` should follow PascalCase and be renamed to `AutoValidateMode`

**Comment by nate-thegrate** [comment]
As far as "autovalidate" vs. "auto validate", it looks like [Apple uses 1 word](https://developer.apple.com/documentation/appkit/nstoolbaritem/autovalidates) whereas [Microsoft uses 2](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.autovalidate).

And apparently "autovalidation" is a single word in [Wikitionary](https://en.wiktionary.org/wiki/autovalidation).

Overall, I'm leaning toward not performing any name changes, but I'm interested to hear others' thoughts.

**Comment by goderbauer** [comment]
I don't think we should create churn here and it looks like we are not the only one in the industry spelling it that way.
