### ISSUE TITLE
DropdownButton  dont open in RTL in material

### ISSUE THREAD

**Issue by javadbat** [flutter/flutter#16024]
the problem is simple dropdown work on ltr and dont open in rtl it compiled but when we tap on it , option menu dont open
in ltr mode it work fine:
![photo_2018-03-28_18-35-39](https://user-images.githubusercontent.com/11534875/38034142-e489cc7e-32b6-11e8-974d-8305f5227f70.jpg)
![photo_2018-03-28_18-35-43](https://user-images.githubusercontent.com/11534875/38034143-e4b7492e-32b6-11e8-89d9-d56eb6c712a1.jpg)
but in rtl 
![photo_2018-03-28_18-35-22](https://user-images.githubusercontent.com/11534875/38034191-f945b844-32b6-11e8-906e-c6767d04540c.jpg)

here is the code:

https://github.com/javadbat/flutter1/blob/debug-rtl-dropdown/lib/main.dart

**Comment by HansMuller** [comment]
Thanks for the report, will check.

**Comment by javadbat** [comment]
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
@javadbat that's quite an old Flutter version. Even the `beta` channel has a newer version (0.2.3 as far as I remember)

**Comment by javadbat** [comment]
flutter update so fast and i move to master Chanel and update after that it get better but not work properly as expected

**Comment by zoechi** [comment]
Some time and many updates passed since then. Is this still an issue?

**Comment by javadbat** [comment]
i dont know i dont code flutter anymore

**Comment by zoechi** [comment]
@javadbat I'll check. Thanks for the update!

**Comment by zoechi** [comment]
![screenshot_1535742170](https://user-images.githubusercontent.com/405837/44931240-3fe1dd80-ad61-11e8-8afc-887459500f63.png)

It's working now.

Flutter 0.7.4-pre.21 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7cebaac985 (2 days ago) • 2018-08-29 21:53:39 -0700
Engine • revision 252da48082
Tools • Dart 2.1.0-dev.3.0.flutter-760a9690c2

**Comment by fawadkhanucp** [comment]
@zoechi I'm having this issue. Using 0.9.6. Can you check this again on your end please? Might be a regression. Thanks.

**Comment by zoechi** [comment]
@fawadkhanucp I can't reproduce with
```
[✓] Flutter (Channel master, v0.9.7-pre.62, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.9.7-pre.62 at /Users/zoechi/flutter/flutter
    • Framework revision 2c063b7ca5 (3 hours ago), 2018-10-08 08:45:24 +0200
    • Engine revision 572fa5646a
    • Dart version 2.1.0-dev.6.0.flutter-c6254163dc
```

**Comment by fawadkhanucp** [comment]
@zoechi alrighty. something on my end then. thanks!

**Comment by fawadkhanucp** [comment]
@zoechi the issue im having is that when i set directionality to rtl, the drop down menu shows all the options on the left side instead of the right.

**Comment by zoechi** [comment]
@fawadkhanucp this way `Directionality.rtl` is not applied to dialogs. Check the source link in the initial comment.

**Comment by fawadkhanucp** [comment]
@zoechi got it. thank you so much.
