### ISSUE TITLE
[CP] Disable AHB based swapchains

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#160206]
### Issue Link

https://github.com/flutter/flutter/issues/160025

### Target

stable

### Cherry pick PR Link

https://github.com/flutter/engine/pull/57173

### Changelog Description

* Disable Android HardwareBuffer based swapchains on all devices.

### Impacted Users

Android Impeller

### Impact Description

* Android HardwareBuffer swapchains were non functional for a larger than expected number of physical devices.

### Workaround

Add the following line to AndroidManifest:

```
<meta-data
    android:name="io.flutter.embedding.android.DisableSurfaceControl"
    android:value="true" />
```

### Risk

low

### Test Coverage

yes

### Validation Steps

Both swapchains are tested on CI, this is a pure delete

**Comment by jonahwilliams** [comment]
FYI @zanderso  / @chinmaygarde

**Comment by zanderso** [comment]
cp lgtm

**Comment by astudilloalex** [comment]
Check this error does not work solution

I add this line on Android Manifest

```
<meta-data
    android:name="io.flutter.embedding.android.DisableSurfaceControl"
    android:value="true" />
```
  
Testing on Android Redmi Note 8 Pro

https://github.com/user-attachments/assets/0263b4f5-8a28-4044-a489-955b23f9957a


Continue flicker
