### ISSUE TITLE
Allow customization of _DropdownMenuPainter's corner radius

### ISSUE THREAD

**Issue by candostdagdeviren** [flutter/flutter#16020]
I want to increase rounded corner value for `DropdownMenuPainter` but couldn't succeeded without changing the `_painter` initialization with `BorderDecoration`. I just want to increase the value in `borderRadius: new BorderRadius.circular(2.0),` to `8.0`. Is there an easy way to achieve this with current implementation without creating my own widget from the beginning. If there isn't, could anyone consider this as a feature request?

## Flutter Doctor

```
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-DE)
    • Flutter version 0.1.5 at /Users/candost/Documents/flutter
    • Framework revision 3ea4d06340 (5 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/candost/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by goderbauer** [comment]
StackOverflow is probably a better place to ask these kind of support questions.

**Comment by candostdagdeviren** [comment]
This was not a 100% support question. The problem was not possible to implement what I want with the framework. I asked how we can handle easier than creating a custom widget from scratch. If we cannot handle easier than now, as I said in the issue this may count as a feature request. Basically, I want to change the rounded corners of `DropdownMenuPainter`.

**Comment by goderbauer** [comment]
Oh sorry. `DropdownMenuPainter` doesn't exist as a public class anymore. Presumably, you're talking about something related to `DropdownButton`? Which corners do you want to round there?

**Comment by jamesblasco** [comment]
Here someone implemented the corner radius inside DropdownMenu but never submitted the PR.
https://stackoverflow.com/a/56285735/8096916.

Here is the files with the changes -> https://gist.github.com/hugocbpassos/2a63594a21d7f231e97dd7dc1f18ee68

**Comment by deandreamatias** [comment]
Hi @goderbauer 
Do you can add this issue to someone project or milestone? 
To not forget or lose it.
Thanks

**Comment by WieFel** [comment]
I also need a custom dropdown menu border radius. Still no good solution around there!
