### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildRelease'.         

### ISSUE THREAD

**Issue by fatihfoot** [flutter/flutter#160286]
### Use case

    ../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flet-0.25.1/lib/src/utils/theme.dart:356:28: Error: A value of type 'TabBarThemeData' can't be returned from a function with return type 'TabBarTheme?'.
            - 'TabBarThemeData' is from 'package:flutter/src/material/tab_bar_theme.dart' ('/C:/Program%20Files/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
            - 'TabBarTheme' is from 'package:flutter/src/material/tab_bar_theme.dart' ('/C:/Program%20Files/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
             return theme.tabBarTheme.copyWith(
                                      ^
           ../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flet-0.25.1/lib/src/utils/theme.dart:438:28: Error: A value of type 'DialogThemeData' can't be returned from a function with return type 'DialogTheme?'.
            - 'DialogThemeData' is from 'package:flutter/src/material/dialog_theme.dart' ('/C:/Program%20Files/flutter/packages/flutter/lib/src/material/dialog_theme.dart').
            - 'DialogTheme' is from 'package:flutter/src/material/dialog_theme.dart' ('/C:/Program%20Files/flutter/packages/flutter/lib/src/material/dialog_theme.dart').
             return theme.dialogTheme.copyWith(
                                      ^
           ../../../../AppData/Local/Pub/Cache/hosted/pub.dev/flet-0.25.1/lib/src/utils/theme.dart:482:26: Error: A value of type 'CardThemeData' can't be returned from a function with return type 'CardTheme?'.
            - 'CardThemeData' is from 'package:flutter/src/material/card_theme.dart' ('/C:/Program%20Files/flutter/packages/flutter/lib/src/material/card_theme.dart').
            - 'CardTheme' is from 'package:flutter/src/material/card_theme.dart' ('/C:/Program%20Files/flutter/packages/flutter/lib/src/material/card_theme.dart').
             return theme.cardTheme.copyWith(
                                    ^
           Target kernel_snapshot_program failed: Exception

           FAILURE: Build failed with an exception.

           * What went wrong:
           Execution failed for task ':app:compileFlutterBuildRelease'.
           > Process 'command 'C:\Program Files\flutter\bin\flutter.bat'' finished with non-zero exit value 1

           * Try:
           > Run with --stacktrace option to get the stack trace.
           > Run with --info or --debug option to get more log output.
           > Run with --scan to get full insights.
           > Get more help at https://help.gradle.org.

           BUILD FAILED in 5m 25s
           Gradle task assembleRelease failed with exit code 1

           Error building Flet app - see the log of failed command above.
![Untitled](https://github.com/user-attachments/assets/83d4d7ea-5afd-4a6a-81a1-ca1eb10f125c)

### Proposal

 pub.dev/flutter

**Comment by maheshj01** [comment]
Hello @fatihfoot, Thanks for filing the issue. From the build logs it looks like this is an issue in the third party package flet

I would suggest filing an issue with them: https://github.com/flet-dev/flet/issues  
Closing this issue as invalid. Incase you disagree please feel free to write in the comments and we will reopen it.
