### ISSUE TITLE
我无法执行 `flutter upgrade -v`

### ISSUE THREAD

**Issue by AndromedaX7** [flutter/flutter#160229]
### Steps to reproduce

执行 `flutter upgrade -v `

### Expected results

[        ]      | The process cannot access the file because it is being used by another process.
[  +65 ms] Error: Unable to update Dart SDK. Retrying...
[   +8 ms] ERROR: Input redirection is not supported, exiting the process immediately.
[  +57 ms] Checking Dart SDK version...
[   +1 ms] Downloading Dart SDK from Flutter engine 5eedfefe38c1a465283e7352a542881497efc681...
[ +366 ms] Rename-Item: C:\Users\miaom\flutter\bin\internal\update_dart_sdk.ps1:81
[        ] Line |
[        ]   81 |          Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
[        ]      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[        ]      | The process cannot access the file because it is being used by another process.
[  +65 ms] Error: Unable to update Dart SDK. Retrying...
[   +9 ms] ERROR: Input redirection is not supported, exiting the process immediately.
[  +60 ms] Checking Dart SDK version...
[   +1 ms] Downloading Dart SDK from Flutter engine 5eedfefe38c1a465283e7352a542881497efc681...
[ +377 ms] Rename-Item: C:\Users\miaom\flutter\bin\internal\update_dart_sdk.ps1:81
[        ] Line |
[        ]   81 |          Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
[        ]      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[        ]      | The process cannot access the file because it is being used by another process.
[  +65 ms] Error: Unable to update Dart SDK. Retrying...
[   +9 ms] ERROR: Input redirection is not supported, exiting the process immediately.
[  +64 ms] Checking Dart SDK version...
[   +1 ms] Downloading Dart SDK from Flutter engine 5eedfefe38c1a465283e7352a542881497efc681...
[ +366 ms] Rename-Item: C:\Users\miaom\flutter\bin\internal\update_dart_sdk.ps1:81
[        ] Line |
[        ]   81 |          Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"
[        ]      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[        ]      | The process cannot access the file because it is being used by another process.

### Actual results

正常执行 `flutter upgrade -v`

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by usakingjp** [comment]
Try killing "dart.exe" in Task Manager.

**Comment by AndromedaX7** [comment]
ty
