### ISSUE TITLE
[monorepo] need build-only builder for the web engine

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#160211]
In the monorepo world we need to be able to just build the engine without running tests to support the following:

* **PRs and post-submit**: immediately after the engine is built we can schedule framework tests without waiting for engine tests to complete.
* **Merge queue**: build the engine without tests quickly so that framework hackers can iterate on the framework without building the engine locally.

To do that we need to split `linux_web_engine.json` into two files:

* `linux_web_engine_build.json`: just build the web engine and upload the artifacts to the GCS buckets.
* `linux_web_engine.json`: build and test the web engine (do not upload artifacts to GCS).

**Comment by yjbanov** [comment]
@eyebrowsoffire is looking into this now. It's mostly landed already, it seems.

**Comment by eyebrowsoffire** [comment]
This is done.
