### ISSUE TITLE
Switching channels should prompt to run flutter upgrade

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#16030]
## Steps to Reproduce
Was on beta channel, and ran the following:

```
$ flutter channel master                                                        
Switching to flutter channel 'master'...
git: Switched to branch 'master'
git: Your branch is behind 'origin/master' by 272 commits, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
```

The message here is technically accurate (the best kind of accurate), but confusing in that it suggests the next step is to run `git pull`. It would be better if it instead closed with something like the following (assuming no error was returned from git):

```
Successfully switched to flutter channel 'master'.
Now run "flutter upgrade" to ensure that you're on the latest build from this channel.
```

(Or even better, perhaps we should automatically run `flutter upgrade` after switching channels, since the tools are otherwise in an indeterminate state.)

**Comment by escamoteur** [comment]
Seems closely related to https://github.com/flutter/flutter/issues/14979 although if I understand it correct there they want to first upgrade before switching.
