### ISSUE TITLE
[webview_flutter_android] Please add support for "setCacheMode"

### ISSUE THREAD

**Issue by jiagengArctuition** [flutter/flutter#160334]
### Use case

Android native can use "LOAD_CACHE_ELSE_NETWORK" cache mode , but Flutter cannot set it

### Proposal

Support for 5 native Android cache modes
- LOAD_DEFAULT
- LOAD_NORMAL
- LOAD_CACHE_ELSE_NETWORK
- LOAD_NO_CACHE
- LOAD_CACHE_ONLY

**Comment by danagbemava-nc** [comment]
This is being tracked in https://github.com/flutter/flutter/issues/160070

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate 

Thank you
