### ISSUE TITLE
math.min is not working after importing import 'dart:math';

### ISSUE THREAD

**Issue by riazahmadkakar** [flutter/flutter#160317]
### Steps to reproduce

it showing a red line below math.min 

### Expected results

i just want to use in my code 

### Actual results

error

### Code sample

import 'dart:math';

void main() {
  final numbers = [10, 5, 20, 15];
  final minimum = math.min(numbers[0], numbers[1]); // Using math.min
  print('Minimum: $minimum');
}

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```          

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
If you want to use the `dart:math` import as `math.method()` you will have to create an alias for the import 

```
import 'dart:math' as math;

void main() {
final numbers = [10, 5, 20, 15];
final minimum = math.min(numbers[0], numbers[1]); // Using math.min
print('Minimum: $minimum');
}
```

Otherwise you will just have to use the min method as is. 

Closing as this is an issue with your code and not a flutter issue. 

Thank you
