### ISSUE TITLE
MaterialApp.title doesn't affect iOS title

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#16031]
From the [Flutter docs on MaterialApp.title](https://docs.flutter.io/flutter/material/MaterialApp/title.html), this property is used to identify the app: 

> A one-line description used by the device to identify the app for the user.
>
> On Android the titles appear above the task manager's app snapshots which are displayed when the user presses the "recent apps" button. Similarly, on iOS the titles appear in the App Switcher when the user double presses the home button. 

On Android, this works as intended. But on iOS, the name used in the App Switcher is the name of the project, even when this property is set.

## Repo

1. From a command line, run `flutter create materialtitle`
2. In a code editor, edit `lib/main.dart` so that `MaterialApp.title` is initialized to `foobar`
3. Run `flutter run -d iPhone` to launch the app in a simulator
4. Press Command+Shift+H twice in quick succession to launch the App Switcher
5. Expected: App Switcher shows `foobar`. Actual: App Switcher shows `materialtitle`

## Environment
```
$ flutter doctor -v                                                      
[✓] Flutter (Channel master, v0.2.5-pre.57, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.5-pre.57 at /Users/timsneath/flutter
    • Framework revision c5288c7346 (2 hours ago), 2018-03-28 08:32:27 -0700
    • Engine revision dd6f46c485
    • Dart version 2.0.0-dev.41.0.flutter-2f68e82526

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/timsneath/Library/Android/sdk
    • Android NDK at /Users/timsneath/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.0

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone 7                  • 81F64B40-5DDD-45CF-A56E-E816369DA5CB • ios         • iOS 11.2 (simulator)

• No issues found!
```

**Comment by Hixie** [comment]
cc @xster

**Comment by Hixie** [comment]
cc @mklim @GaryQian in case one of you wants to tackle this before @xster gets back.

**Comment by mklim** [comment]
This eventually traces down to a [deliberate non-op with a comment saying that the functionality is Android-only](https://github.com/flutter/engine/blob/6e780fdc672e59fc7bc84d5b7963b1fb9cc68830/shell/platform/darwin/ios/framework/Source/FlutterPlatformPlugin.mm#L127). Looking into this to see if and how it could be added in for iOS, or if it's the docs that need to be updated to specify that this does nothing in iOS.

**Comment by mklim** [comment]
I don't think it's possible to alter the title of an app in the Switcher in iOS dynamically at runtime, like the original code comment indicated. It looks like this is completely controlled by `CF(Bundle)DisplayName`, from the app's `Info.plist`. I'll update the documentation to clarify the limitation.
