### ISSUE TITLE
[vector_graphics_compiler] Any chance of using it in an app?

### ISSUE THREAD

**Issue by deakjahn** [flutter/flutter#160315]
### Use case

I'm sure it's not easy without Dan and it probably only gets minimal fixes now but is there any chance of using it from an app rather than from the dev environment during development? Maybe without optimizations? The tool relies on interfacing into various platform libraries now. I have incoming SVGs that I'd like to store for later display and while I do support compiled SVGs coming in, I'd like to be able to compile plain ones into the compiled form in my app for better storage and performance later.

### Proposal

I'd be willing to put some work into it if you think it's possible at all, eg. just a plain SVG-to-binary conversion without various optimization techniques. Even that would save space and speed up display, I suppose.

**Comment by jonahwilliams** [comment]
flutter_svg already does this, no?

There isn't anything stopping you from importing the compiler afaik

**Comment by deakjahn** [comment]
The secret ingredient was to disable the optimizations there, it works then, indeed — it must be one of those that requires some extra data in order to work. Very nice, thanks.
