### ISSUE TITLE
The TabLabel class should support local image

### ISSUE THREAD

**Issue by zhangyulong882** [flutter/flutter#1604]
I think the TabLabel class should support local image, the function **_buildLabelIcon** in tabs.dart should look like this:

```dart
  Widget _buildLabelIcon(bool aIsLocal, [ int aWidth, int aHeight ] ) {
      assert(label.icon != null);
      if (aisLocal && $aWidth != 0 && $aHeight != 0) {
        return new AssetImage(name: label.icon, width: aWidth.toDouble(), height: aheight.toDouble());
      } else {
        return new Icon(icon: label.icon, color: color);
      }
  }
```

**Comment by abarth** [comment]
Maybe we should let you provide an arbitrary `Widget` as the icon for the tab label.

**Comment by HansMuller** [comment]
Just making the parameter a widget and ensuring that it's sized properly should get the job done, yes.

**Comment by HansMuller** [comment]
Looking at this a little more closely. The tab icons (and their text labels) are supposed to reflect selection. This is currently not working, tab labels' text and icons are always rendered with the same color (it used to work...).

Although an arbitrary widget is the most convenient way to show a tab label icon, we'll need to ensure it reflects the selection properly. Perhaps by wrapping it with an Opacity widget.

**Comment by abarth** [comment]
> Perhaps by wrapping it with an Opacity widget.

That's a lot more expensive than colorizing an icon...  Given that the original request was for an image as well, maybe we should have a builder function that takes the desired color.

**Comment by HansMuller** [comment]
Good idea. That sounds more flexible too.
