### ISSUE TITLE
in_app_purchase - Pending Transaction Handling Issue in StoreKit

### ISSUE THREAD

**Issue by MelbourneDeveloper** [flutter/flutter#160498]
### Steps to reproduce

1. Attempt to buy a product on iOS
2. Cancel out by closing the purchase with a X button
3. Attempt to buy the same product again
4. Note the error

> PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases., {paymentDiscount: null, productIdentifier: com.storytowns.pass.7day, requestData: null, simulatesAskToBuyInSandbox: false

### Expected results

The expectation is that we can query the existing transactions so we can either complete or cancel them before attempting to purchase again. However, this doesn't seem to be possible, and the only mechanism for doing this seems to be calling `restorePurchases` and wait for the update to get emitted on the stream. 

### Actual results

The update does appear on the stream, but there is either no list of products in the emitted value, or the purchase is cancelled, but even if it is cancelled, we still get an error saying that there is a pending transaction. 

### Code sample

This code has been throw many iterations. This may or may not be correct, but I cannot work out a way to get rid of pending transactions. If the user starts a transaction and doesn't finish it, that's it, this code will never be able to actually make a purchase.

```dart
import 'dart:async';

import 'package:StoryTowns/globals.dart';
import 'package:StoryTowns/logging/fault.dart';
import 'package:StoryTowns/logging/logging.dart';
import 'package:StoryTowns/services/auth_notifier.dart';
import 'package:in_app_purchase/in_app_purchase.dart';

/// Handles in app purchases.
class InAppPurchasesService {
  InAppPurchasesService(this._inAppPurchase, this._authNotifier) {
    _subscription = _inAppPurchase.purchaseStream.listen(
      _onPurchaseUpdated,
      onDone: () => log('Stopped listening for purchase changes'),
      onError: (error) => log('Error in purchaseStream: $error'),
    );
  }

  final InAppPurchase _inAppPurchase;
  final AuthNotifier _authNotifier;
  late final StreamSubscription<List<PurchaseDetails>> _subscription;
  Completer<PurchaseDetails?>? _purchaseCompleter;

  /// Handle the purchase stream events
  Future<void> _onPurchaseUpdated(
    List<PurchaseDetails> purchaseDetailsList,
  ) async {
    try {
      logInfo(
        'Purchase Stream Event Received',
        structuredData: {
          'purchaseDetailsList': purchaseDetailsList
              .map(
                (p) => 'Product ID: ${p.productID} '
                    'status ${p.status} '
                    'pendingCompletionPurchaseId ${p.pendingCompletePurchase} '
                    'error ${p.error} '
                    'transactionDate ${p.transactionDate}',
              )
              .join(', '),
        },
        tags: ['InAppPurchases'],
      );

      if (!_authGuard()) {
        logWarning(
          'User is not authenticated. Doing nothing.',
          tags: ['InAppPurchases'],
        );
        return;
      }

      for (final purchase in purchaseDetailsList) {
        await _handlePurchaseUpdate(purchase);
      }
    } catch (e, s) {
      logError(
        'Error in purchase stream event',
        fault: Fault.fromObjectAndStackTrace(e, s),
        tags: ['InAppPurchases'],
      );
    }
  }

  bool _authGuard() {
    //Guard against unauthenticated users.
    if (!_authNotifier.isAuthenticated) {
      logWarning(
        'User is not authenticated. Doing nothing.',
        tags: ['InAppPurchases'],
      );
      _completePurchase(null);
      return false;
    }
    return true;
  }

  /// Handle a purchase from an update
  Future<void> _handlePurchaseUpdate(PurchaseDetails purchase) async {
    switch (purchase.status) {
      case PurchaseStatus.pending ||
            PurchaseStatus.purchased ||
            PurchaseStatus.restored:
        log(
          'Attempting to complete purchase',
          structuredData: {
            'productId': purchase.productID,
            'status': purchase.status.toString(),
            'pendingCompletionPurchaseId':
                purchase.pendingCompletePurchase.toString(),
          },
          tags: ['InAppPurchases'],
        );

        //Attempt to complete the pending purchase
        await _inAppPurchase.completePurchase(purchase);

        log(
          level: LogLevel.info,
          'Successfully completed purchase',
          structuredData: {
            'productId': purchase.productID,
            'status': purchase.status.toString(),
            'transactionDate': purchase.transactionDate ?? '',
          },
          tags: ['InAppPurchases'],
        );

        _completePurchase(purchase);

      case PurchaseStatus.error:
        logError(
          'Error purchasing ${purchase.productID}',
          structuredData: {
            'error': purchase.error?.toString() ?? '',
            'status': purchase.status.toString(),
            'pendingCompletionPurchaseId':
                purchase.pendingCompletePurchase.toString(),
          },
          tags: ['InAppPurchases'],
        );

        _completePurchase(null);
      case PurchaseStatus.canceled:
        logWarning(
          'Purchase was canceled',
          structuredData: {
            'productId': purchase.productID,
            'status': purchase.status.toString(),
          },
          tags: ['InAppPurchases'],
        );

        _completePurchase(null);
    }
  }

  /// Finishes waiting for a purchase to complete
  void _completePurchase(PurchaseDetails? purchase) {
    if (_purchaseCompleter?.isCompleted == false) {
      _purchaseCompleter?.complete(purchase);
    }
  }

  /// Get the product details for a specific product ID
  Future<ProductDetails?> getProductDetails(String productId) async {
    // Check if the store is available
    if (!await _inAppPurchase.isAvailable()) {
      logError('The store is not available', tags: ['InAppPurchases']);
      return null;
    }

    final response = await _inAppPurchase.queryProductDetails({productId});

    if (response.error != null) {
      logError(
        'Error querying product details: ${response.error}',
        tags: ['InAppPurchases'],
      );
      return null;
    }

    final products = response.productDetails;

    if (products.isEmpty) {
      logWarning(
        'Product details not found for $productId',
        tags: ['InAppPurchases'],
      );
      return null;
    }

    final product = products.firstOrNull;

    if (product != null) {
      log(
        'Product available: ${product.title} (${product.id})'
        ' - ${product.price}',
        tags: ['InAppPurchases'],
      );
    }

    return product;
  }

  /// Prompt user to buy product and wait until they do, or cancel
  Future<PurchaseDetails?> buyProduct(String productId) async {
    try {
      _purchaseCompleter = Completer<PurchaseDetails?>();

      log(
        'Starting purchase flow',
        structuredData: {
          'productId': productId,
          'isAuthenticated': _authNotifier.isAuthenticated.toString(),
          'userId': _authNotifier.currentUser?.id ?? '',
        },
        tags: ['InAppPurchases'],
      );

      // Restore purchases to trigger any pending transactions
      await _inAppPurchase.restorePurchases();

      // Wait for the stream to emit the cancelled purchases
      await Future.delayed(const Duration(seconds: 3));

      final product = await getProductDetails(productId);

      if (product == null) {
        logWarning(
          'Product details not found for $productId. Not attempting purchase',
          tags: ['InAppPurchases'],
        );
        return null;
      }

      //Guard against unauthenticated users.
      final userId = _authNotifier.currentUser?.id;
      if (userId == null) {
        logWarning(
          'User ID is null',
          tags: ['InAppPurchases'],
        );
        return null;
      }

      log(
        'Initiating purchase',
        structuredData: {
          'productId': productId,
          'userId': userId,
          'productTitle': product.title,
          'productPrice': product.price,
        },
        tags: ['InAppPurchases'],
      );

      final success = await _inAppPurchase.buyConsumable(
        purchaseParam: PurchaseParam(
          productDetails: product,
          applicationUserName: userId,
        ),
      );

      if (!success) {
        throw Exception(
          'Failed to buy product: ${product.title}',
        );
      }

      log(
        'Purchase initiated successfully',
        structuredData: {
          'productId': productId,
          'userId': userId,
        },
        tags: ['InAppPurchases'],
      );

      return await _purchaseCompleter?.future;
    } catch (e, s) {
      logError(
        'Error in purchase flow',
        fault: Fault.fromObjectAndStackTrace(e, s),
        tags: ['InAppPurchases'],
      );
      _completePurchase(null);
      return null;
    } finally {
      _purchaseCompleter = null;
    }
  }

  Future<void> dispose() async {
    await _subscription.cancel();
  }
}
```

### Logs

Here you can see that it looks like it's taking a pending transaction and completing it, but it doesn't

Then it logs a cancelled purchase, which is correct.

And then I get 

> There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases

Which is the problem

flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:19.504784
flutter: Starting purchase flow
flutter: productId: com.storytowns.pass.7day
isAuthenticated: true
userId: 65bb7e61-179a-468b-990b-362c7e55952c
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:01:20.435393
flutter: Purchase Stream Event Received
flutter: purchaseDetailsList:
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:01:21.365114
flutter: Inserted 7 logs into Supabase
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:23.548039
flutter: Product available: 7-Day Pass (com.storytowns.pass.7day) - $29.99
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:23.548387
flutter: Initiating purchase
flutter: productId: com.storytowns.pass.7day
userId: 65bb7e61-179a-468b-990b-362c7e55952c
productTitle: 7-Day Pass
productPrice: $29.99
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:23.550075
flutter: Purchase initiated successfully
flutter: productId: com.storytowns.pass.7day
userId: 65bb7e61-179a-468b-990b-362c7e55952c
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:01:23.558467
flutter: Purchase Stream Event Received
flutter: purchaseDetailsList: Product ID: com.storytowns.pass.7day status PurchaseStatus.pending pendingCompletionPurchaseId false error null transactionDate null
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:23.559275
flutter: Attempting to complete purchase
flutter: productId: com.storytowns.pass.7day
status: PurchaseStatus.pending
pendingCompletionPurchaseId: false
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:01:23.562974
flutter: Successfully completed purchase
flutter: productId: com.storytowns.pass.7day
status: PurchaseStatus.pending
transactionDate:
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:01:31.635242
flutter: Inserted 3 logs into Supabase
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:01:34.093175
flutter: Purchase Stream Event Received
flutter: purchaseDetailsList: Product ID: com.storytowns.pass.7day status PurchaseStatus.canceled pendingCompletionPurchaseId true error IAPError(code: purchase_error, source: app_store, message: SKErrorDomain, details: {NSUnderlyingError: {domain: ASDErrorDomain, userInfo: {NSUnderlyingError: {domain: AMSErrorDomain, userInfo: {NSDebugDescription: Payment Sheet Failed Payment sheet dismissed with neither an error nor a result, AMSURL: https://sandbox.itunes.apple.com/WebObjects/MZBuy.woa/wa/inAppBuy?guid=00008101-001269020081401E, AMSDescription: Payment Sheet Failed, AMSStatusCode: 200, AMSFailureReason: Payment sheet dismissed with neither an error nor a result, AMSServerPayload: {dialog: {defaultButton: Buy, cancelButtonString: Cancel, m-allowed: false, okButtonString: Buy, paymentSheetInfo: {requestor: AppStore, salableIconType: app, confirmationTitle: Pay, salableInfo: [7-Day Pass, Storytowns %%image_0%% %%image_1%%, In-App Purchase], styles: [{name: priceMain, size: large, bold: true}, {name: priceSubGray, color: gray}, {name: account, color: gray}], countryCode: AU, title: {type: text, value: Sandbox}, price: 29.99, caseControl: true, images: [{type: itunesgames, value: 4+}, {type: apps-australia, value: Unrated}], suppressPrice: true, designVersion: 2, flexList: [{value: [{value: $29.99, style: priceMain}, {value: One-time charge, style: priceSubGray}]}, {value: For testing purposes only. You will not be charged for confirming this purchase., header: DETAILS}, {value: Account: %%appleId%%, style: account}], salableIcon: https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/f9/c5/74/f9c57427-5a1f-780d-cae8-da0f7f170cff/AppIcon-0-0-1x_U007emarketing-0-10-0-0-85-220.png/144x144bb.jpg, currency: AUD}, message: Sign in with Apple Account, explanation: Enter the password for %%appleId%% to authorise this transaction.

[Environment: Sandbox], kind: authorization, okButtonAction: {kind: Buy, itemName: com.storytowns.pass.7day, buyParams: hasFailedTouchIDChallenge=true&offrd-free-trial=false&salableAdamId=6736430958&showIAPExtraDialog=false&applicationUsername=65bb7e61-179a-468b-990b-362c7e55952c&offerName=com.storytowns.pass.7day&productType=A&hasBeenAuthedForBuy=true&quantity=1&price=29990&ageCheck=true&pricingParameters=STDQ&vid=AF7E9048-03F9-4AB2-B0A0-1274DC27D3E6&bvrs=0&pg=default&hasConfirmedPaymentSheet=true&offrd-intro-price=false&bid=com.storytowns.travelapp&hasWebOptIn=false}, initialCheckboxValue: true}, failureType: , m-allowed: false, customerMessage: Sign in with Apple Account, pings: [https://xp.apple.com/report/2/xp_its_main?code=MZCommerceInAppBuy.ConfirmationNeededForBuyOneItem.CPS.Auth&buttons=Buy%3ACancel&baseVersion=1&dsId=22153956840&eventVersion=1&storeFrontHeader=143460-27%2C29&eventTime=1734516084526&eventType=dialog&message=Sign%20in%20with%20Apple%C2%A0Accoun], metrics: {osloTitleValue: AbstractSalableInfoModule.SandboxTitle, mtEventTime: 2024-12-18 10:01:23 Etc/GMT, osloTitleType: text, eventType: dialog, actionUrl: sandbox.itunes.apple.com/WebObjects/MZBuy.woa/wa/inAppBuy, message: Sign in with Apple Accoun, topic: xp_its_main, dialogId: MZCommerceInAppBuy.ConfirmationNeededForBuyOneItem.CPS.Auth, mtTopic: xp_its_main}, cancel-purchase-batch: true}}, code: 6}}, code: 907}}) transactionDate null
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: WARN 2024-12-18 21:01:34.097945
flutter: Purchase was canceled
flutter: productId: com.storytowns.pass.7day
status: PurchaseStatus.canceled
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:35.095690
flutter: Auth check successful
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:35.096290
flutter: Starting purchase flow
flutter: productId: com.storytowns.pass.7day
isAuthenticated: true
userId: 65bb7e61-179a-468b-990b-362c7e55952c
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:01:36.025283
flutter: Purchase Stream Event Received
flutter: purchaseDetailsList:
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:39.070427
flutter: Product available: 7-Day Pass (com.storytowns.pass.7day) - $29.99
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: TRACE 2024-12-18 21:01:39.070899
flutter: Initiating purchase
flutter: productId: com.storytowns.pass.7day
userId: 65bb7e61-179a-468b-990b-362c7e55952c
productTitle: 7-Day Pass
productPrice: $29.99
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: ERROR 2024-12-18 21:01:58.570205
flutter: Error in purchase flow
flutter: ***** Fault *****
Exception: PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases., {quantity: 1, applicationUsername: 65bb7e61-179a-468b-990b-362c7e55952c, requestData: null, simulatesAskToBuyInSandbox: false, productIdentifier: com.storytowns.pass.7day, paymentDiscount: null}, null)
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:01:58.829808
flutter: Inserted 3 logs into Supabase
flutter: ---------------------------------
flutter:
flutter: ---------------------------------
flutter: INFO 2024-12-18 21:02:09.122735
flutter: Inserted 1 logs into Supabase
flutter: ---------------------------------
flutter:

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B2091 darwin-arm64, locale
    en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.96.0)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!

**Comment by darshankawar** [comment]
@MelbourneDeveloper There's a similar issue open describing your case, https://github.com/flutter/flutter/issues/119620, so please follow-up in it for further updates.
Closing this as a duplicate.
