### ISSUE TITLE
Invaild argument

### ISSUE THREAD

**Issue by Nankarina** [flutter/flutter#160412]
### Steps to reproduce

FATAL:flutter/fml/thread_local.cc(32)Check failed:false.
pthread_setspecific failed(22):Invaild argument

### Code sample

Process.run();
exit(0);

### What target platforms are you seeing this bug on?

Linux

### OS/Browser name and version | Device information

Linux CentOS 7.9

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Flutter Doctor output

 Flutter (Channel stable, 3.7.11, on Llinux linux-64 CentOS Linux7, locale zh-CN)
    • Flutter version 3.7.11 on channel stable at D:\xn\flutter_bin\flutter_project
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (1 year, 8 months ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

**Comment by darshankawar** [comment]
> Flutter (Channel stable, 3.7.11,

@Nankarina You are on obsolete version. Please upgrade to latest (3.27.1) and re-run your scenario to check if the error still persist or not. If still yes, provide all requested details.
Closing for now.
