### ISSUE TITLE
[monorepo, tech debt] remove "Linux Web Framework tests"

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#160405]
With the monorepo "Linux Web Framework tests" is no longer needed because all framework tests will run immediately on every engine change. In fact, none of this would even work in the monorepo, because most of the code deals with cloning the right revisions of the engine and the framework, and redirecting the CLI tool to a local engine build, all of which is bogus when you have everything in one repo. Filing this issue to remove it from all the places.

The tasks must be completed in the exact order as listed below (to not break the CI):

- [x] Delete the "Linux Web Framework tests" builder from [.ci.yaml](https://github.com/flutter/engine/blob/23731d6a967dd21d357033ea05caa92b6d71fdef/.ci.yaml#L419).
  - [x] Do the same in flutter/flaux.
- [x] Delete the recipe [web_engine_framework.py](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/web_engine_framework.py).
  - Gerrit CL for this item: https://flutter-review.googlesource.com/c/recipes/+/61720
- [x] Delete [clone_flutter.sh](https://github.com/flutter/engine/blob/main/tools/clone_flutter.sh).
- [x] Delete [configure_framework_commit.sh](https://github.com/flutter/engine/blob/main/tools/configure_framework_commit.sh).

**Comment by matanlurey** [comment]
Yayyyyyyy

**Comment by jtmcdole** [comment]
<3 <3 <3
