### ISSUE TITLE
[tool] Unable to install APK through `flutter run` when uninstalled once and installed a previous version

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#160402]
### Steps to reproduce

1. Set the `pubspec.yaml` version to `1.0.0+1`.
2. `flutter build apk --release && adb install build/app/outputs/flutter-apk/app-release.apk`
3. Run the app on the device, and ensure it is `v1.0.0+1`.
4. Set the `pubspec.yaml` version to `1.0.1+2`.
5. `flutter run -d the_android_device_id`
6. Ensure it is `v1.0.1+2`.
7. Uninstall the current `v1.0.1+2`, then reinstall the previous version through `adb install build/app/outputs/flutter-apk/app-release.apk`.
8. Run the app on the device, and ensure it is `v1.0.0+1`.
9. `flutter run -v -d the_android_device`
10. The log shows `Latest build already installed` and launched the app, but the latest APK was not installed.

### Expected results

`flutter run` should installs the latest APK.install

### Actual results

When a temporary file of a previously installed version exists, the tool will recognize that the latest version is installed.

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

<details open><summary>Logs</summary>

```console
[   +2 ms] Stopping app 'app-debug.apk' on ONEPLUS A6010.
[        ] executing: /Users/alex/dev/android-sdk/platform-tools/adb -s f8e67ce3 shell am force-stop com.example.test
[  +95 ms] executing: /Users/alex/dev/android-sdk/platform-tools/adb -s f8e67ce3 shell pm list packages com.example.test
[ +109 ms] package:com.example.test
[        ] executing: /Users/alex/dev/android-sdk/platform-tools/adb -s f8e67ce3 shell cat /data/local/tmp/sky.com.example.test.sha1
[  +61 ms] a46ba751dfd13d0c0c4e153c8f8c52cc00b2a627
[        ] Latest build already installed.
[        ] executing: /Users/alex/dev/android-sdk/platform-tools/adb -s f8e67ce3 shell -x logcat -v time -t 1
[ +242 ms] --------- beginning of main
           12-17 09:53:38.172 I/cmd     (27942): oneway function results will be dropped but finished with status OK and parcel size 4
[   +3 ms] executing: /Users/alex/dev/android-sdk/platform-tools/adb -s f8e67ce3 shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.example.test/com.example.test.MainActivity
[  +88 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=com.example.test/.MainActivity (has extras) }
[        ] Waiting for VM Service port to be available...

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.27.0-1.0.pre.753, on macOS 14.7.1 23H222 darwin-arm64, locale zh-Hans-CN)
```

</details>

**Comment by AlexV525** [comment]
https://github.com/flutter/flutter/blob/256a127da361188c08ff6e6fc314cd59a9ec7e71/packages/flutter_tools/lib/src/android/android_device.dart#L361-L363

**Comment by danagbemava-nc** [comment]
Thanks for the detailed steps. 

Reproducible using the steps outlined above. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.27.1 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (16 hours ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2
```

```
[!] Flutter (Channel master, 3.28.0-1.0.pre.157, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-1.0.pre.157 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 27ef1967b0 (6 hours ago), 2024-12-16 20:29:14 -0800
    • Engine revision 23731d6a96
    • Dart version 3.7.0 (build 3.7.0-256.0.dev)
    • DevTools version 2.41.0

```

</details>

**Comment by andrewkolos** [comment]
I am curious, could you share a little about the workflow that caused you discover this? For example, did you make changes to the native config of your app (e.g. `android/app/build.gradle.kts`), re-run/install it, and notice that the changes did not make it to the device?

**Comment by AlexV525** [comment]
> I am curious, could you share a little about the workflow that caused you discover this?

I was developing the new version for a while with the storage migration, in the end I want to double check whether it will cause a repression which may erase previous data, so I uninstalled the developing one and installed one of our previous release.

**Comment by code-ashishkumar** [comment]
Im facing the same issue 
In my case its in vs code
I created new peoject 
I run the project and it stuck at
![Screenshot 2024-12-18 152249](https://github.com/user-attachments/assets/8f21b1ec-4428-411b-b664-f320892ca9df)
app installed in emulator but stuck 
I did not change any settings
Created a project and was directly running it

**Comment by AlexV525** [comment]
@code-ashishkumar Your case seems variant. Please submit a new issue with the required contexts.

**Comment by code-ashishkumar** [comment]
@AlexV525 

Sure, thanks
