### ISSUE TITLE
pubspec.yaml Added platform-specific configuration

### ISSUE THREAD

**Issue by melancholyboy** [flutter/flutter#160489]
### pubspec.yaml Added platform-specific configuration

> 1.When developing for mobile and desktop, you may encounter different sizes of the same image.
> 2.Mobile and desktop rely on different libraries
> 3.Use different fonts for each platform

etc.

### Proposal

I hope flutter pubspec.yaml can support differentiated platform configurations

**Comment by danagbemava-nc** [comment]
There are several issues discussing this on this repo. A few are listed below
Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you 

https://github.com/flutter/flutter/issues/81650
https://github.com/flutter/flutter/issues/8230
