### ISSUE TITLE
Link to NetworkImage is a broken link in step 6 - Sign users into your app 

### ISSUE THREAD

**Issue by fatcatdog** [flutter/flutter#16047]
This was a great Codelab I learned a lot,

step 6: Sign users into your app 
Section: Personalize the avatar 

There is a link NetworkImage which links to a dead page for me:

"https://docs.flutter.io/flutter/services/NetworkImage-class.html"
404 error 

Thank you Team Flutter

**Comment by xster** [comment]
Seems like the package was moved from services to painting

https://docs.flutter.io/flutter/painting/NetworkImage-class.html

cc @Sfshaza

**Comment by Sfshaza** [comment]
@fatcatdog, thanks for the compliment, but I just went through the [9 Flutter codelabs](https://codelabs.developers.google.com/?cat=Flutter) more than once, and I cannot find the bug you're referencing. Could it be a deprecated codelab?

**Comment by fatcatdog** [comment]
Maybe it was updated since then? From what I remember it was the link that
was broken

Fatcatdog

**Comment by Sfshaza** [comment]
Thanks, @fatcatdog, I'm closing.
