### ISSUE TITLE
SliverGridLayout's documentation for get[Min|Max]ChildIndexForScrollOffset is misleading

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#16045]
Current documentation: 
```
getMaxChildIndexForScrollOffset(double scrollOffset) → int
The maximum child index that is visible at (or before) this scroll offset.
getMinChildIndexForScrollOffset(double scrollOffset) → int
The minimum child index that is visible at (or after) this scroll offset.
```

How these are actually used seems to indicate this should be the documentation:

```
getMaxChildIndexForScrollOffset(double scrollOffset) → int
The maximum child index that intersects with (or is before) this scroll offset.
getMinChildIndexForScrollOffset(double scrollOffset) → int
The minimum child index that intersects with (or is after) this scroll offset.
```

Basically, all the children from getMin...(scrollOffset) to getMax...(scrollOffset+extent) are being laid out but the documentation suggests that getMin...(scrollOffset) to getMax...(scrollOffset) should be all the children being laid out.

**Comment by Hixie** [comment]
cc @goderbauer We should also mention the accessibility padding in these docs.

**Comment by pedromassangocode** [comment]
Still valid on latest master. The comments were not updated.

https://github.com/flutter/flutter/blob/e10bdbbd9de69a79101d8e79030532ee2be58b89/packages/flutter/lib/src/rendering/sliver_grid.dart#L105-L115
