### ISSUE TITLE
Workspaces Breaks Pub Get For Standalone Packages

### ISSUE THREAD

**Issue by rayliverified** [flutter/flutter#160477]
### Steps to reproduce

Add `resolution: workspace` to a package's pubspec.yaml file. Pub get will throw the following error:

> [ExampleSDK] flutter pub get --no-example
> Found a pubspec.yaml at /Users/ray/Development/ExampleSDK. But it has resolution `workspace`.
> But found no workspace root including it in parent directories.
> 
> See https://dart.dev/go/pub-workspaces for more information.
> Failed to update packages.
> exit code 66

### Actual results

Packages `pub get` no longer works if the package is opened outside of a workspace.

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.28.0-0.1.pre, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-0.1.pre on channel beta at /Users/ray/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3e493a3e4d (6 days ago), 2024-12-12 05:59:24 +0900
    • Engine revision 2ba456fd7f
    • Dart version 3.7.0 (build 3.7.0-209.1.beta)
    • DevTools version 2.41.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/ray/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B2091 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B2091 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.140

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by matanlurey** [comment]
Why would you add `resolution: workspace` to a package you don't want included as a workspace?

**Comment by rayliverified** [comment]
Hi @matanlurey , I have multiple packages that are used in multiple projects as submodules. The packages are also standalone and published to Pub.dev 

When the packages are included in a workspace, it makes sense to add that. But then when they're used alone pub get fails.

For example, my navigation package is published and standalone. But I include it in my parent project to test and develop features.

**Comment by darshankawar** [comment]
@rayliverified 
I think this will be more suitable in pub repo: https://github.com/dart-lang/pub/issues
I see a similar issue that you can refer https://github.com/dart-lang/pub/issues/4393. Check if it helps in your case or not.
I will close this from here. If you disagree, write in comments and I'll reopen it.

**Comment by rayliverified** [comment]
Hi @darshankawar , thanks for taking a look and linking https://github.com/dart-lang/pub/issues/4393

It helped me create a workaround but doesn't solve the issue.

With `pubspec_overrides.yaml`, these files still go in the package repositories and will throw the error when run independently.

Here's my workaround:
1. Add "pubspec_overrides.yaml" to the `.gitignore` of each package.
2. Remove resolution: workspace from each `pubspec.yaml`.
3. In the parent repository, add the packages as workspaces.
4. Create a script that creates the override files.

```dart
import 'dart:io';
import 'package:path/path.dart' as path;

void main() async {
  final directories = [
    'PackageA',
    'PackageB',
    'PackageC',
  ];

  final overridesContent = '''
resolution: workspace
''';

  for (final dir in directories) {
    try {
      final file = File(path.join(dir, 'pubspec_overrides.yaml'));
      await file.writeAsString(overridesContent);
      print('✅ Created override in $dir');
    } catch (e) {
      print('❌ Failed to create override in $dir: $e');
    }
  }
}

```

5. Run the script when using the parent project.

Not ideal. I really wish the implementation was an automatic lookup, and doesn't require multiple linked file changes.

**Comment by rayliverified** [comment]
Let's keep the issue closed. Let's see if anyone else runs into this issue.
