### ISSUE TITLE
JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by theSonGoku1991** [flutter/flutter#160543]
### Steps to reproduce

A friend of mine is having trouble configuring his java correctly/making the very same app I am regularly working on able to run on his system. I am writing this issue because he is new to programming.

He started out using Java 23 (because I recommended him to, because its the latest version, I later knew better), I asked him to downgrade to 21 or 17 though because of gradle compatibility etc. He keeps receiving the message "ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jdk-23" though, and that even though he not only tried to uninstall and completely removed Java 23 but also when he uninstalled all Java versions available on his system until the terminal did not recognize the keyword "java" anymore.

Printing out the current Java version with ´java --version´ shows Java 21 instead of Java 23. Only ´flutter doctor´ and Visual Studio Code (when he tries to run his app) seem to be stuck with Java 23 (like as if we forgot to delete the browsers cache or so). Having a look at the registry (regedit command) was not helpful neither.

Helping him to troubleshoot this problem, I found a few issues from the past mentioning the very same problem:
July 2022: https://github.com/flutter/flutter/issues/108618
July 2023: https://github.com/flutter/flutter/issues/130635
Jan 2024: https://github.com/flutter/flutter/issues/140848

Thats why I do not neccesarrily think we are speaking about a bug but also can not exclude this possibility from troubleshooting.

We both run the same/latest Flutter version 3.28, the same version of Android Studio and the same version of Visual Studio Code.

### Actual results

My friend receives the error message "ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jdk-23" even though Java 23 is not installed anymore, the path does no longer exist and his environment variable is set correctly.

### Flutter Doctor output

I need to request this from him but already gave you the information about the current Flutter and Java version.

**Comment by iapicca** [comment]
> Helping him to troubleshoot this problem, I found a few issues from the past mentioning the very same problem:
> July 2022: #108618

@theSonGoku1991 
the issue you mentioned is still open
and as you mentioned it addresses the same problem
wouldn't be better to keep the conversation in that issue?

**Comment by darshankawar** [comment]
@theSonGoku1991 
You may try to set the jdk version you have / using currently to set it via `flutter config --jdk-dir "your path to current jdk"` to see if it helps to resolve the issue or not.

**Comment by theSonGoku1991** [comment]
@darshankawar 
This solved out problem we have been trying to fix for days!
Can you tell me why? Is it possible the old jdk/java version was stuck in the flutter "cache" and the command you posted overwrote it?

**Comment by darshankawar** [comment]
The command description is as below:

```
 --jdk-dir                               The Java Development Kit (JDK)
                                            installation directory. If unset,
                                            flutter will search for one in the
                                            following order:
                                            1) the JDK bundled with the latest
                                            installation of Android Studio,
                                            2) the JDK found at the directory
                                            found in the JAVA_HOME environment
                                            variable, and
                                            3) the directory containing the java
                                            binary found in the user's path.

```

**Comment by darshankawar** [comment]
Closing as this is resolved per your comment.
