### ISSUE TITLE
Flutter `master` channel is broken on `flutter/codelabs` CI

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#160558]
I'm seeing the following behavior only on the `master` channel of my `flutter/codelabs` CI:

```console
  dart --version
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.1[3](https://github.com/flutter/codelabs/actions/runs/12401981182/job/34622521206#step:5:3)-11/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.13-11/x6[4](https://github.com/flutter/codelabs/actions/runs/12401981182/job/34622521206#step:5:4)
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/master-any-x64
    PUB_CACHE: /home/runner/.pub-cache
fatal: Not a valid object name upstream/master
```

Full context: https://github.com/flutter/codelabs/actions/runs/12401981182/job/34622521206

**Comment by domesticmouse** [comment]
You can see the various attempts to fix this breakage in https://github.com/flutter/codelabs/pull/2273

**Comment by jtmcdole** [comment]
> fatal: Not a valid object name upstream/master

We calculate the engine hash based on the difference between upstream/master and HEAD. Is your upstream origin?

**Comment by domesticmouse** [comment]
This is happening in CI, so it's `subosito/flutter-action` pulling a Flutter channel in the CI bot. That repo does checks for stable, beta, and master on linux, macos and windows hosts.

**Comment by jtmcdole** [comment]
Yep; master doesn't work because it can't find the HASH for the engine because almost assuredly action is checking out with origin vs upstream

**Comment by domesticmouse** [comment]
So `subosito/flutter-action` needs to be fixed?

**Comment by jtmcdole** [comment]
No - I think we could fix this by testing for upstream vs origin:

```
git remote get-url upstream
```

I'm looking deeper.

**Comment by a-h-mzd** [comment]
This also happens on local machines and is not exclusive to CI tools. #160552

**Comment by jtmcdole** [comment]
We're aware and making a change

**Comment by jtmcdole** [comment]
@a-h-mzd - can you confirm this has fixed your issue?

**Comment by a-h-mzd** [comment]
![image](https://github.com/user-attachments/assets/16cb86ce-1096-4c61-854f-b063a0ab807f)
