### ISSUE TITLE
Simple animation uses much higher CPU than SwiftUI in iOS

### ISSUE THREAD

**Issue by chooyan-eng** [flutter/flutter#160562]
### Steps to reproduce

# Flutter
1. run the code with simple continuous scaling animation in profile mode on iPhone
2. open Xcode and hit "Show the Debug navigator" icon
3. the tool shows approximate 30% CPU usage

# SwiftUI
1. run the code with simple continuous scaling animation
2. open Xcode and hit "Show the Debug navigator" icon
3. the tool shows approximate 1% CPU usage

### Code sample

# Flutter
<details open><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: TapCancelDemo()));

class TapCancelDemo extends StatefulWidget {
  const TapCancelDemo({super.key});

  @override
  State<TapCancelDemo> createState() => _TapCancelDemoState();
}

class _TapCancelDemoState extends State<TapCancelDemo>
    with TickerProviderStateMixin {
  bool _isLarge = true;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      setState(() => _isLarge = false);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: AnimatedContainer(
          duration: const Duration(seconds: 1),
          onEnd: () {
            setState(() => _isLarge = !_isLarge);
          },
          width: _isLarge ? 200 : 100,
          height: _isLarge ? 200 : 100,
          color: Colors.blue,
        ),
      ),
    );
  }
}

```

</details>

# SwiftUI
<details open><summary>Code sample</summary>

```swift
import SwiftUI

struct ContentView: View {
    @State private var isAnimating = false
    
    var body: some View {
        Rectangle()
            .fill(.blue)
            .frame(width: 100, height: 100)
            .scaleEffect(isAnimating ? 2 : 1.0)
            .onAppear {
                withAnimation(
                    .easeInOut(duration: 1.0)
                    .repeatForever(autoreverses: true)
                ) {
                    isAnimating = true
                }
            }
    }
}
```

</details>

### Performance profiling on master channel

- [X] The issue still persists on the master channel

### Timeline Traces

<details open><summary>Timeline Traces JSON</summary>

[dart_devtools_2024-12-19_10_38_29.942.json.zip](https://github.com/user-attachments/files/18191223/dart_devtools_2024-12-19_10_38_29.942.json.zip)

</details>

### Video demonstration

<details open>
<summary>Video demonstration</summary>

[Upload media here]

</details>

### What target platforms are you seeing this bug on?

iOS

### OS/Browser name and version | Device information

iPhone 12 Pro max (OS 18.11)

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Is the problem only reproducible with Impeller?

No

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 14.3.1 23D60 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.95.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```
</details>

**Comment by darshankawar** [comment]
@chooyan-eng Thanks for the report.
Please check if your case resembles https://github.com/flutter/flutter/issues/142218 or not.

**Comment by jonahwilliams** [comment]
Two notes If you're using Xcode's built in CPU profiler:

1. You need to run the Flutter applicaiton in release mode. XCode doesn't know what parts of the process are the app and which part is our own profiler/debugger, so you're essentially measuring debugger/profiler performance.

2. iOS defers some of the animation work to a secondary render server process, and the XCode CPU profiler *does not* count this workload. The XCode cpu profiler therefore does not give you an apples to apples comparison between a Flutter and SwiftUI/UIKit application as the latter is only partially profiled.
