### ISSUE TITLE
Screen record detection

### ISSUE THREAD

**Issue by Mohamed-Elmeligy8** [flutter/flutter#160517]
### Use case

why thers is no direct api for detection the screen record ? .. you should find a solution for it because its and important feature now that most teachers ask for it on thier app we made and we find it hard ( who doesnt know anything about native code ) as we first know about programming is dart and flutter ,,, using flag secure and flutter window manager is useless because the recorded video still have it's audio and this not good at the educational apps ,, please solve this issue as fast as u can .

### Proposal

no media for my imagining available

**Comment by matanlurey** [comment]
Thanks for filing an issue.

Every platform has its own way of implementing something like this, and some platforms intentionally have (for security reasons) no way to implement something like this. As such, it would be a poor fit to supply out of the box in Flutter. You could [develop your own plugin](https://docs.flutter.dev/packages-and-plugins/developing-packages) for platforms you care about by calling native APIs.

Closing as we won't be doing this.

**Comment by Mohamed-Elmeligy8** [comment]
Your response feels dismissive, almost as if you're suggesting I should find help elsewhere. I expected more depth and professionalism from a proficient developer in flutter team ( that if u are really one of thier team ) ....
