### ISSUE TITLE
Can't run any flutter commands after switching to main/master channel

### ISSUE THREAD

**Issue by a-h-mzd** [flutter/flutter#160552]
### Steps to reproduce

1. download stable 3.27.x version
2. switch to the main channel
3. try to run any flutter command (running just `flutter` would also suffice)
4. observe that you will get `fatal: Not a valid object name upstream/master`

### Actual results

Flutter should work as normal.

### Logs

<details open>
<summary>Logs</summary>

```console

fatal: Not a valid object name upstream/master

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

fatal: Not a valid object name upstream/master

```

</details>

Note that I’m using a MacBook running on an M1 chip.

**Comment by jtmcdole** [comment]
Duplicate #160558
