### ISSUE TITLE
Need 360° Free Orbit Rotation for 3D Model in All Directions Without Constraints

### ISSUE THREAD

**Issue by RajatDBazaar** [flutter/flutter#160583]
I am developing a 3D model rendering app using Flutter, and everything is working well except for one issue. We need our model to rotate freely in 360° in all directions without restrictions. Currently, the model rotates infinitely on the horizontal axis, but vertically, it is limited to 180°, causing the rotation to lock beyond that point.

What we're aiming for is trackball-style movement, but right now, we only have turntable-style movement. We've been trying various methods to resolve this issue for the past 3 weeks without success, and we're feeling quite exhausted. Any help or suggestions would be greatly appreciated.

Like this website has -- https://app.emb3d.com/3dviewer [View Point - Trackball]

Can anyone help me regrading this issue

**Comment by darshankawar** [comment]
@RajatDBazaar 
Please raise support questions on stackoverflow or Flutter's reddit help page.
Closing from here, as this repo is for tracking bugs and feature requests against the sdk.
