### ISSUE TITLE
Error when deploy WASM web - FlutterLoader could not find a build compatible with configuration and environment

### ISSUE THREAD

**Issue by kjm0202** [flutter/flutter#160581]
### Steps to reproduce

Here's my test repo (sorry, it's GitLab): https://gitlab.com/kjm0202/wasm_test
It's exactly same Counter Example App except `web/index.html`.
Here's my `index.html`:
<details>
<summary>Fold/Unfold</summary>

```
<!DOCTYPE html>
<html>
<head>
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="wasm_test">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>wasm_test</title>
  <link rel="manifest" href="manifest.json">

  <style>
    /* Load Screen Style */
    #loading {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: #ffffff;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      z-index: 9999;
      transition: opacity 0.5s ease;
    }

    .spinner {
      border: 8px solid #f3f3f3;
      border-top: 8px solid #6750A4;
      border-radius: 50%;
      width: 60px;
      height: 60px;
      animation: spin 1.5s linear infinite;
      margin-bottom: 20px;
    }

    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }

    .loading-text {
      font-family: 'Pretendard', sans-serif;
      font-size: 1.2rem;
      color: #3498db;
      animation: fadeIn 1.5s ease-in-out infinite;
    }

    @keyframes fadeIn {
      0%, 100% { opacity: 0.5; }
      50% { opacity: 1; }
    }
  </style>
</head>

<body>
  <div id="loading">
    <div class="spinner"></div>
    <div class="loading-text">Loading...</div>
  </div>

  <script>
    {{flutter_js}}
    {{flutter_build_config}}
    
    // check Chromium and its version
    function getChromeVersion() {
      const userAgent = navigator.userAgent;
      const isChrome = /Chrome\/([0-9]+)/.test(userAgent);
      if (!isChrome) return 0;
      return parseInt(userAgent.match(/Chrome\/([0-9]+)/)[1]);
    }

    // select renderer using Chromium version
    const chromeVersion = getChromeVersion();
    console.log(chromeVersion);
    const useCanvasKit = chromeVersion < 119;
    
    const config = {
      renderer: useCanvasKit ? "canvaskit" : "skwasm",
    };
    
    const loading = document.getElementById('loading');
    const loadingText = loading.querySelector('.loading-text');
    _flutter.loader.load({
      config: config,
      onEntrypointLoaded: async function (engineInitializer) {
        loadingText.textContent = "Initializing Engine...";
        const appRunner = await engineInitializer.initializeEngine();

        loadingText.textContent = "Almost there!";
        await appRunner.runApp();

        // Hide loading screen
        loading.style.opacity = '0';
        setTimeout(() => {
          loading.style.display = 'none';
        }, 500);
      }
    });
  </script>
</body>
</html>

```

</details>

1. git clone & upload to your repo (or fork?)
2. Deploy it to GitLab Pages (I've already uploaded .gitlab-ci.yml for deploy in git. It uses `flutter build web --wasm`)
3. After complete, check your GitLab Page.
You can also check my (already) deployed GitLab Page in here:
https://wasm-test-24d608.gitlab.io/

! ATTENTION !
It will not be reproduced in local environment.
It only happens when it is deployed.

### Expected results

Little loading time, then goes to counter app.

### Actual results

Error while loading.

### Code sample

Please check example app code in this git: https://gitlab.com/kjm0202/wasm_test
You can also check my already deployed site in here: https://wasm-test-24d608.gitlab.io/

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/7d9b61df-3df5-4f19-bbe5-984437194033)

</details>

### Logs

<details open><summary>Logs</summary>

```console
(index):90 Uncaught (in promise) FlutterLoader could not find a build compatible with configuration and environment.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26100.2605], locale ko-KR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.6)
[√] Android Studio (version 2024.1)
[√] IntelliJ IDEA Ultimate Edition (version 2024.3)
[√] VS Code (version 1.96.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@kjm0202 
Please check if [this](https://github.com/flutter/flutter/issues/147610) helps in your case or not.

**Comment by kjm0202** [comment]
@darshankawar 
The error is same with mine, but the case seems to be different.
That case is something with `--web-renderer=auto`, and mine is something with `--wasm'
Also, I have no idea how to apply that solution into my case.

**Comment by darshankawar** [comment]
Keeping the issue open for team's tracking.

**Comment by kjm0202** [comment]
OK, I found what is the problem.
The problem was either GitHub Pages / GitLab Pages doesn't support COOP / COEP headers.
[Related Flutter docs](https://docs.flutter.dev/platform-integration/web/wasm#serve-the-built-output-with-an-http-server)

Here are 2 solutions that I found:
* Use another static web hosting services which supports custom headers: Netlify or Cloudflare Pages
* If you want to stick with GitHub / GitLab Pages with WASM support, then use [coi-serviceworker](https://github.com/gzuidhof/coi-serviceworker) for workaround.
 1. Download `coi-serviceworker.min.js` file and put it in `web` folder
 2. Add `<script src="coi-serviceworker.js"></script>` in your `<body>` of `index.html`.

I tested 2nd solution and it worked today. Hope it would work for long time...
You can close this issue, or give new / better solution for this issue. Thanks.

**Comment by darshankawar** [comment]
Closing as resolved based on above comment.
