### ISSUE TITLE
flutter is not initializing.

### ISSUE THREAD

**Issue by RajatKD** [flutter/flutter#16051]
## Steps to Reproduce
rajath@rajath-HP-Notebook:/developer$ export PATH=`pwd`/flutter/bin:$PATH
rajath@rajath-HP-Notebook:/developer$ flutter

## Logs

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 6a8fccd28a63efa6)
Crash report written to /tmp/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by zoechi** [comment]
Thanks for filing the issue and sorry that we were not able to return to you earlier.
Is this still an issue?
