### ISSUE TITLE
`engine/src/flutter/bin/et.bat` showing as modified after git clone

### ISSUE THREAD

**Issue by Mike278** [flutter/flutter#160529]
### Steps to reproduce

I have a script that checks out a specific flutter version like this:

`git clone https://github.com/flutter/flutter.git && cd flutter && git checkout tags/3.22.2`

Normally this script works as expected and checks out the specified tag.

### Actual results

Ever since the flutter engine repo was merged into the main repo (721b47e7e61b60a8b8b6b8d0f2b0f3f932b139c3), this command has been spuriously failing:

```
error: Your local changes to the following files would be overwritten by checkout:
        engine/src/flutter/bin/et.bat
```

The strangest part is that it works sometimes but not others. I've seen it fail then succeed within 1 minute apart. It feels like a github caching issue, possibly due to the size of the engine repo commit?

The diffs in `et.bat` are solely CRLF line endings

### Logs

<details open>
<summary>Logs</summary>

```console

18-Dec-2024 15:39:19 | Step 17/22 : RUN git clone https://github.com/flutter/flutter.git && cd flutter && git checkout tags/$FLUTTER_VERSION
-- | --
18-Dec-2024 15:39:19 | ---> Running in e821e7afea46
18-Dec-2024 15:39:19 | Cloning into 'flutter'...
18-Dec-2024 15:39:44 | error: Your local changes to the following files would be overwritten by checkout:
18-Dec-2024 15:39:44 | engine/src/flutter/bin/et.bat
18-Dec-2024 15:39:44 | Please commit your changes or stash them before you switch branches.
18-Dec-2024 15:39:44 | Aborting


```

</details>

### Flutter Doctor output

n/a

**Comment by christopherfujino** [comment]
I can repro this locally on linux

**Comment by christopherfujino** [comment]
```
[✓] Flutter (Channel master, 3.28.0-1.0.pre.38699, on Debian GNU/Linux rodete
    6.10.11-1rodete2-amd64, locale en_US.UTF-8)
    • Flutter version 3.28.0-1.0.pre.38699 on channel master at
      /home/fujino/git/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f0bf495594 (75 minutes ago), 2024-12-18 12:18:06 -0800
    • Engine revision f0bf495594
    • Dart version 3.7.0 (build 3.7.0-260.0.dev)
    • DevTools version 2.41.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/fujino/Android/Sdk
    • Platform android-35, build-tools 33.0.1
    • Java binary at: /home/fujino/Downloads/android-studio/jbr/bin/java
      This is the JDK bundled with the latest Android Studio installation on this
      machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 16.0.6 (27+build1)
    • cmake version 3.29.6
    • ninja version 1.12.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/fujino/Downloads/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.87.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete
      6.10.11-1rodete2-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 131.0.6778.139

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by jason-simmons** [comment]
In the engine repository `engine/src/flutter/bin/et.bat` was checked in as a binary file with CRLF line endings.

The merged framework+engine repository contains a `.gitattributes` file at its root that declares `.bat` files to be text files.  `engine/src/flutter/bin/et.bat` needs to be checked in using LF line endings to match the expected format.

I can post a PR to do that once the tree stabilizes.

**Comment by christopherfujino** [comment]
> In the engine repository `engine/src/flutter/bin/et.bat` was checked in as a binary file with CRLF line endings.
> 
> The merged framework+engine repository contains a `.gitattributes` file at its root that declares `.bat` files to be text files. `engine/src/flutter/bin/et.bat` needs to be checked in using LF line endings to match the expected format.
> 
> I can post a PR to do that once the tree stabilizes.

Nice, thanks.

**Comment by christopherfujino** [comment]
> The merged framework+engine repository contains a `.gitattributes` file at its root that declares `.bat` files to be text files. `engine/src/flutter/bin/et.bat` needs to be checked in using LF line endings to match the expected format.

Would that mean that windows clients would know to check it out with CRLF?

I actually didn't know about .gitattributes, or that git differentiated between binary and text files.

**Comment by jason-simmons** [comment]
Git will convert these files to CRLF format when checking them out to the local working directory.

see https://github.com/flutter/flutter/blob/master/.gitattributes#L18

**Comment by christopherfujino** [comment]
> Git will convert these files to CRLF format when checking them out to the local working directory.
> 
> see https://github.com/flutter/flutter/blob/master/.gitattributes#L18

ahh, nice!

**Comment by Mike278** [comment]
Huh, TIL! 

That all makes sense, but are any of y'all able to get a successful clone? (i.e clean git status after clone). That's still the part I don't understand. 

I have a few working and broken clones locally - with this new knowledge I'll have a closer look at how they differ.

**Comment by matanlurey** [comment]
FWIW I also get this, on a clean checkout, and I don't know how to fix it (TM):

```sh
$ git reset --hard upstream/main
HEAD is now at f0bf495594 Trigger Build Part Deux (#160481)

$ git status
On branch main
Your branch is up to date with 'upstream/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   engine/src/flutter/bin/et.bat
```
