### ISSUE TITLE
[Impeller] 3.27.1 DisableImpeller in Android Manifest does not disable impeller

### ISSUE THREAD

**Issue by franco-conroo** [flutter/flutter#160595]
### Steps to reproduce

1. Add DisableImpeller meta-data to Android Manifest like described in the docs underneath `<application>` tag.

`<meta-data
           android:name="io.flutter.embedding.android.DisableImpeller"
           android:value="true" />`

2. Build the android app
3. See in the logs that Impeller is still used
4. Change flag with following

`<meta-data
           android:name="io.flutter.embedding.android.EnableImpeller"
           android:value="false" />`
           
5. Still works and disables impeller

Tested on Android using Android 13 and physical device CPH2205

### Expected results

DisableImpeller should disable usage of impeller as per documentation. Using the run flag --no-enable-impeller does yield the expected result!

### Actual results

DisableImpeller does not disable impeller as of Flutter 3.27.1. Still the old EnableImpeller flag does.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (7 available)
[✓] Network resources

• No issues found!```

</details>

**Comment by vishnumukundan** [comment]
Same issue here.

**Comment by matanlurey** [comment]
This was a mistake, the flag is and always will be `EnableImpeller`, so `EnableImpeller` with `"false"` is correct.
