### ISSUE TITLE
Inconsistent appFlavor Initialization When Launching with --flavor

### ISSUE THREAD

**Issue by YaserH25** [flutter/flutter#160540]
### Steps to reproduce

1.	Set up multiple flavors for a Flutter app (e.g., development, production), and ensure environment variables are defined in separate .env files.
2.	Launch the app with a specified flavor using a launch.json configuration such as:
```json
{
  "name": "Claro Mobile App (Production)",
  "request": "launch",
  "type": "dart",
  "toolArgs": ["--flavor", "production"]
}
```
3.	In the app’s initialization code, print or assert the value of appFlavor before loading .env.production.
4.	Observe that appFlavor appears as null at runtime, while stepping through with a debugger breakpoint shows the correct value.
5.	Perform a hot restart.
6.	Note that after restart, the flavor is correctly set and the environment loads as intended.

### Expected results

The specified flavor (production in this case) should be consistently available from the initial app launch without requiring a breakpoint or hot restart.

### Actual results

The flavor variable is initially null when the app first launches. Only after performing a hot restart does the value become correctly populated, and when i add a breakpoint i see the actual value

### Code sample

<details open><summary>Code sample</summary>

```dart
static Future<void> initFlavor() async {
    const flavorString = appFlavor ?? 'development';

    String envFile = '.env.$flavorString';

    await dotenv.load(fileName: envFile);

    final flavor = AppFlavor.values.firstWhere(
      (f) => f.toString().split('.').last == flavorString,
    );

    Environment.init(
      flavor,
      FlavorValues(
        appName: dotenv.env['APP_NAME']!,
        showInspectorLabel: dotenv.env['SHOW_INSPECTOR_LABEL'] == 'true',
        baseUrl: dotenv.env['BASE_URL']!,
        apiHost: dotenv.env['API_HOST']!,
        imageUrl: dotenv.env['IMAGE_URL']!,
        appCastUrl: dotenv.env['APP_CAST_URL']!,
      ),
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

As u see here, the `appFlavor` is `production` when debugging with breakpoint but intially `null`, so `flavorString` takes `development` as its value instead of `appFlavor`.

![image](https://github.com/user-attachments/assets/d05b1177-1f44-4cfd-a5b2-41e2bfd0e2b2)

![image](https://github.com/user-attachments/assets/21121cf3-490e-4a41-ab79-878595e5e550)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 15.1.1 24B91 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.93.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Yaser’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@YaserH25 
Can you provide complete runnable reproducible code sample (ex: main.dart) that shows the behavior ?
The code you provide seems to have custom implementation so we can't use it directly.

**Comment by YaserH25** [comment]
> @YaserH25 Can you provide complete runnable reproducible code sample (ex: main.dart) that shows the behavior ? The code you provide seems to have custom implementation so we can't use it directly.

Just the normal flavor example from Flutter Doc is enough, actually i solved it by applying a base64 flavor value in `Dart Define` in xcode, following this issue https://github.com/flutter/website/issues/11178 , but it's not mentioned in the documentation.

**Comment by darshankawar** [comment]
Good to know that you resolved the issue.

> but it's not mentioned in the documentation.

You may file a documentation request for same so that we can track and address it properly.
