### ISSUE TITLE
Test colocation

### ISSUE THREAD

**Issue by balazsotakomaiya** [flutter/flutter#160523]
### Use case

Coming from a React background where test colocation is the standard practice (e.g., `Component.tsx` and `Component.test.tsx` living side by side), the current Flutter testing convention feels like a step backward. The requirement to place all test files in a separate `/test` directory, disconnected from their corresponding implementation files, creates several practical issues:

1. **Cognitive Overhead**: Developers must constantly context switch between implementation and test files across different directory trees, breaking the natural flow of test-driven development. This is particularly jarring for developers coming from React and other modern frameworks where colocation is the norm.

2. **Maintainability Challenges**: When moving or renaming implementation files, developers must remember to update the corresponding test files in a completely different directory structure, leading to potential synchronization issues.

3. **Discovery Problems**: New team members have difficulty finding tests for specific components, as they must understand and navigate a parallel directory structure rather than simply looking next to the implementation file.

4. **Violated Locality**: As Kent C. Dodds explains in [his article on colocation](https://kentcdodds.com/blog/colocation), "Things that change together should be located together." Tests are most frequently updated alongside their implementation files, yet the current structure places them far apart.

### Proposal

Add support for colocated test files in Flutter projects while maintaining compatibility with existing tooling. Specifically:

1. Allow test files to be placed next to their implementation files using the `_test.dart` suffix:
```
lib/
  └── src/
      └── feature/
          ├── feature.dart
          └── feature_test.dart  // Colocated test file
```

2. Update the test runner to discover and execute tests from both:
   - Traditional `/test` directory
   - Colocated `_test.dart` files within the `lib` directory

3. Add documentation for both approaches:
   - Traditional directory structure for those who prefer it
   - New colocated approach for teams wanting better locality, especially those transitioning from React and similar frameworks

This change would align Flutter with modern testing practices seen in other ecosystems (React, Jest, Vitest, etc.) while maintaining backward compatibility with existing projects. It would also significantly improve the developer experience for the growing number of web developers adopting Flutter from React backgrounds.

Interestingly, the Dart test runner seems to support this [according to the docs](https://pub.dev/packages/test#running-tests):

> The test runner accepts one or more path arguments. If there are no path arguments the runner defaults to running tests under the test/ directory. When running for test/ or any other directory, the runner will recursively search the directory for files that match the test name pattern *_test.dart. The pattern can be overridden in dart_test.yaml.

**Comment by matanlurey** [comment]
This is not something we'll be doing. You should feel free to experiment with what works best for your own projects.

Thanks for trying Dart and Flutter!

**Comment by balazsotakomaiya** [comment]
What's the reasoning behind it / why is this a thing in Dart but not Flutter?
