### ISSUE TITLE
The animation loop caton during execution  cpu 70%

### ISSUE THREAD

**Issue by pj0579** [flutter/flutter#16059]
![image](https://user-images.githubusercontent.com/20592579/38132520-00524f70-343e-11e8-81c2-fa366ed69a66.png)

[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13 17A405, locale zh-Hans-CN)
    • Flutter version 0.1.5 
    • Framework revision 3ea4d06340 (5 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Connected devices (1 available)
    • iPhone 8 Plus • 2D07321F-AD58-4649-98CE-05FA393DB672 • ios • iOS 11.2 (simulator)

**Comment by pj0579** [comment]
class AnimatedLogo extends AnimatedWidget {
  AnimatedLogo({Key key, Animation<double> animation})
  : super(key: key, listenable: animation);
  Widget build(BuildContext context) {
    final Animation<double> animation = listenable;
    return new Center(
      child: new Transform(
        origin: new Offset(70.0, 70.0),
        transform: new Matrix4.rotationZ(animation.value),
        child: new Image.asset('images/test.jpg'),
  ),
);
}}
class LogoApp extends StatefulWidget {
   _LogoAppState createState() => new _LogoAppState();
}
class _LogoAppState extends State<LogoApp> with 
SingleTickerProviderStateMixin {

AnimationController controller;
Animation<double> animation;

initState() {
  super.initState();
  controller = new AnimationController(
    duration: const Duration(milliseconds: 2000), vsync: this);
  animation = new Tween(begin: 0.0, end: PI * 2).animate(controller);
  controller.repeat();


}

Widget build(BuildContext context) {
  return new AnimatedLogo(animation: animation);
}

 dispose() {
    controller.dispose();
    super.dispose();
  }
}

void main() {
  runApp(new LogoApp());
}

**Comment by pj0579** [comment]
You can try this code, any picture is the same

**Comment by zoechi** [comment]
Sorry for not coming back to this issue earlier.
A lot has changed since then. Is this still an issue?

**Comment by pj0579** [comment]
This only happens on the ios simulator

**Comment by pj0579** [comment]
Perhaps is not important

**Comment by kyryloz** [comment]
It's still an issue. Happens on the iOS simulator after calling AnimationController#repeat().

Flutter (Channel stable, 2.2.1, on macOS 11.3 20E232 darwin-x64, locale en-GB).
