### ISSUE TITLE
Dart analysis issue

### ISSUE THREAD

**Issue by lzxyh0227** [flutter/flutter#160639]
### Steps to reproduce

<img width="613" alt="image" src="https://github.com/user-attachments/assets/54442989-080d-446d-857d-9c725a84bc85" />
All my Flutter projects suddenly started showing Dart analysis errors.
I have already tried clearing the Flutter and Dart caches, as well as uninstalling and reinstalling Flutter, but the issue still persists.

Please help resolve this problem.

### Actual results

Bad state: Suspected cycle. [(uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/key.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/key.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/_edit_score_horizontal_view.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/_edit_score_horizontal_view.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/_edit_score_horizontal_view.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/_edit_score_horizontal_view.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart), (uri: file:///Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart, path: /Users/obito/StudioProjects/flutter_sdk_music_score/lib/src/score_widget/src/extension/widget/widget/widget/widget/widget/widget/widget/widget/widget/_edit_score_horizontal_view.dart), (uri:

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

Last login: Fri Dec 20 10:35:51 on ttys000
obito@daitu ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on macOS 14.2 23C64 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/obito/software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (1 年 8 个月前), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/obito/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/obito/Library/Android/sdk
    • Java binary at: /Users/obito/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/obito/Applications/Android Studio Electric Eel 2022.1.1
      Patch 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/obito/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • 2211133C (mobile) • 7add3a9 • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos   • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.205

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
The version of flutter you're using is obsolete and no longer supported. Kindly upgrade to the latest version of flutter stable (3.27.1). If you still experience this on the latest flutter version, kindly file a new issue and provide all the relevant information. 

Closing since the version of flutter you're using is no longer supported. 

Thank you
