### ISSUE TITLE
LUCI not reporting back status

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#160611]
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20mac_android_aot_engine/30521/overview failed on lucy, but it was never reported back to github. On github the check remained pending indefinitely. 

A rerun with the "Retry Build" button on Luci succeeded, but also didn't have its result reported b ack to github:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20mac_android_aot_engine/30530/infra

**Comment by jtmcdole** [comment]
Todo: dig through logs / add more to the pubsub to figure out why this didn't report back to github. This could be the new staging doc.

to un stick this; the PR pushed a new empty commit to kick a new PR set.

**Comment by jtmcdole** [comment]
This was probably fixed by: flutter/cocoon/pull/4106
