### ISSUE TITLE
`Linux ci_yaml engine roller` not adding new builders

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#160670]
In https://github.com/flutter/flutter/commit/d363fdc31b7239d9d0ac08b319dab7ccf318b433

The `Linux linux_web_engine_tests` .ci.yaml engine target was added. However, since then, there has only been 1 `Linux ci_yaml engine roller` build, and it determined there were no changes needed: https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20ci_yaml%20engine%20roller/19217/infra

**Comment by christopherfujino** [comment]
This is part of the fix: https://flutter-review.googlesource.com/c/recipes/+/61680 but dependent on an update to cocoon to handle the new cli argument

**Comment by eyebrowsoffire** [comment]
I have the cocoon side fix pending here: https://github.com/flutter/cocoon/pull/4112

**Comment by christopherfujino** [comment]
flutter/flutter PR to deprecate the engine roller target here: https://github.com/flutter/flutter/pull/160682

**Comment by christopherfujino** [comment]
So we had a successful `Linux ci_yaml flutter roller` build that generated configs for both framework AND engine: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/17000/infra

Which merged: https://flutter-review.googlesource.com/c/infra/+/61700

And we know have a builder for `Linux linux_web_engine_tests`: https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.staging/Linux%20linux_web_engine_tests

Just waiting for builds to be scheduled now.

**Comment by eyebrowsoffire** [comment]
Builds were successfully scheduled (although they are failing for unrelated reasons) so I think we're good to close this!

**Comment by christopherfujino** [comment]
Ok, builds are scheduled (and failing)! https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20linux_web_engine_tests/1/infra

Closing this as resolved.
