### ISSUE TITLE
Remove 'skeleton' template

### ISSUE THREAD

**Issue by ericwindmill** [flutter/flutter#160673]
I was planning on updating 'skeleton' to reflect the website's new [app architecture recommendations](https://docs.flutter.dev/app-architecture), but over the past 30 days about 5000 out of ~1m usages of `flutter create -t` used 'skeleton'.  Should we deprecate it instead?

**Comment by matanlurey** [comment]
I would love to deprecate this, as its the only template that uses the now deprecated `flutter_gen` internationalizations.

It would save me a lot of time to deprecate/remove this :)

**Comment by zanderso** [comment]
I suspect if this were updated and promoted it would see more usage, but I also suspect that the template doesn't provide much that isn't already covered in codelabs, examples, tutorials, the [Wonderous app](https://github.com/gskinnerTeam/flutter-wonderous-app), and community resources like https://flutter-builder.app/ and probably many others. I'm supportive of deleting it.

**Comment by matanlurey** [comment]
I'll prepare a PR 🫡
