### ISSUE TITLE
[monorepo] bringup targets not scheduled in monorepo

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#160620]
<img width="990" alt="Screenshot 2024-12-19 at 1 44 22 PM" src="https://github.com/user-attachments/assets/161f7f25-6d2d-4146-9236-d65317323491" />

**Comment by christopherfujino** [comment]
Look at this one: https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_mokey%20run_release_test/1660/infra

which ran for https://flutter.googlesource.com/mirrors/flutter/+/1c52436853303c1ee71d8b06914c0b734f37578c

Maybe we're scheduling them but cocoon's not populating them in the dashboard?
