### ISSUE TITLE
How to get a height of a widget?

### ISSUE THREAD

**Issue by itsJoKr** [flutter/flutter#16061]
I'm trying to get the height of an arbitrary widget, and I found no answer in docs or online (gitter, stack...). I am developing a package, and other developers provide me the widgets. I need widget height to calculate some scroll effects. It seems like a most basic function to be able to get the height of a widget. After going through several options, I landed on SingleChildLayoutDelegate.

I extended that delegate, and I was able to get the height of widget in `getPositionForChild(Size size, Size childSize)` method. BUT, the first method that is called is `Size getSize(BoxConstraints constraints)` and as constraints, I get 0 to INFINITY because I'm laying these CustomSingleChildLayouts in a ListView.

My problem is that SingleChildLayoutDelegate getSize operates like it needs to return the height of a view. I don't know the height of a child at that moment. I can only return constraints.smallest (which is 0, the height is 0), or constraints.biggest which is infinity and crashes the app.

**Comment by itsJoKr** [comment]
I asked it several times on gitter, and once on the StackOverflow: https://stackoverflow.com/questions/49307677/how-to-get-a-height-of-a-widget-using-layoutbuilder

This was the time when someone recommended me LayoutBuilder, which I don't think is even used to get the height. I found SingleChildLayoutDelegate later, but really stuck at the `getSize` part. Since no one was able to help me, I decided to post here.

**Comment by zoechi** [comment]
@itsJoKr thanks for the link! 
This way if someone answers here he can also post the answer to the SO question for others to be found.

**Comment by Kartik1607** [comment]
I may be wrong but have a look at [MediaQuery](https://docs.flutter.io/flutter/widgets/MediaQuery-class.html). I was playing around around flutter examples and saw it being used like this 

```dart
    new Image(
                  width: math.min(280.0, MediaQuery.of(context).size.width),
                  fit: BoxFit.fitHeight,
                  image: new AssetImage(_steps[i].imageUris[0]),
              )
```

**Comment by itsJoKr** [comment]
@zoechi Absolutely. I agree that "how-to's" should go in StackOverflow, but this sounds like a basic functionality that should be documented. 

@Kartik1607 I don't see how MediaQuery can help me. In that example, they are using MediaQuery to get the size of a screen. But you can't get the height of an arbitrary widget with MediaQuery. Problem is a bit tricky, you cannot get height in `build` method because height is calculated at layout pass.

**Comment by mehmetf** [comment]
@itsJoKr you are already plenty experienced with various options. There is only one way for you to get the size of anything before you lay it out first: You have to know the height ahead of time. This trick is done with many widgets (such as AppBar). See

https://docs.flutter.io/flutter/widgets/BuildContext/size.html and
https://docs.flutter.io/flutter/widgets/PreferredSizeWidget-class.html

For instance, I wrote this tidbit and it prints the size correctly because I am calling it from an event handler. 

```dart
class HeightReporter extends StatelessWidget {
  final Widget child;

  HeightReporter({this.child});

  @override
  Widget build(BuildContext context) {
    return new GestureDetector(
      child: child,
      onTap: () {
        print('Height is ${context.size.height}');
      },
    );
  }
}
```

The answer to your question lies in your exact use case. Typically, the use case calls for finding out the height of a widget when the user is doing something (such as scrolling or tapping). If this does not work for you, perhaps you can share what you are trying to do.

**Comment by itsJoKr** [comment]
@mehmetf This clears up some things. 

These Widgets that I need the height of are placed in ListView. I need their heights when the user starts to scroll the ListView. So I was thinking about two options: 

Docs say that the BuildContext size getter:

> It should only be called from paint callbacks or interaction event handlers (e.g. gesture callbacks).

You used the gesture onTap callback, but I don't have that case. I need to get the height when the user starts to scroll the parent ListView. I cannot save the context "for later" because I get _"Cannot get size of inactive element."_.  I have some ideas in my head, but none of them are pretty.

The other option that would really be helpful is to have some callback when the render is done. Something, what this user proposes: https://github.com/flutter/flutter/issues/14488
He is doing double 60ms delay as a hack.

**Comment by mehmetf** [comment]
ListView lazily renders its child widgets so it is not going to be possible for you to know the size of each element in the list. 

If you could tell us what effect you are trying to achieve using Flutter, we might be able to offer better advice. For example, building a "alphabet bar" for a list? (which requires you to jump to a specific point in the list when a letter is tapped)

![image](https://user-images.githubusercontent.com/6687929/38290761-aacb4d3e-3791-11e8-9fcf-467d372eeb8f.png)

**Comment by itsJoKr** [comment]
@mehmetf Sure. I am building sticky-headers thing, like https://github.com/bgogetap/StickyHeaders

I started with SliverPersistentHeader, but I couldn't make it work like in that example above. The headers would either all pin to the top (so if you scroll 5 headers, all 5 would pin), or all 5 would just scroll. I need only most recent header to pin and slowly push other.

I saw this guy that uses ListView for something similar: https://pub.dartlang.org/packages/side_header_list_view. I was able to achieve what I wanted very easily with ListView and one header widget stacked above, that's faking the header and translation on Y-axis. Only thing is that I knew the exact height of each row, and that's what I wanted to remove as input parameters.

**Comment by rrousselGit** [comment]
I answered your SO question. 

A TLDR here : `OverlayEntry` widget can be sized based on others, as it's rendered in a different flow.

You can get other widgets's size/position using `context`

```
final RenderBox box = keyContext.findRenderObject();
final size = box.size;
final topLeftPosition = box.localToGlobal(Offset.zero);
```

To ensure that your `OverlayEntry` always have the latest size/position, you can combine it with an `AnimatedBuilder` that has as `animation` a `ScrollController`.

**Comment by mehmetf** [comment]
@itsJoKr Would resolution of https://github.com/flutter/flutter/issues/12319 help your case? In the side_header_list_view project, the only reason fixed extent is used is to figure out the index of the list element currently on top.  If so, please chime in that thread. That issue will be resolved soon as it is a customer blocker. It would be good to get on that train and get the API you want.

**Comment by itsJoKr** [comment]
I didn't know you can use GlobalKey to access height from context. That's what I needed. 

More details with the explanation in StackOverflow answer: https://stackoverflow.com/a/49650741/4110778

**Comment by debuggerx01** [comment]
Hey guys , Maybe this simple widget is what you want : [rect_getter](https://pub.dartlang.org/packages/rect_getter)
This is a widget provide a simple way to get child's rectangle information after rendered.
![](https://github.com/debuggerx01/rect_getter/raw/master/example/demo.gif?raw=true)

**Comment by Guang1234567** [comment]
@itsJoKr 

maybe the below blog save your time.

https://medium.com/@diegoveloper/flutter-widget-size-and-position-b0a9ffed9407

**Comment by patelkrunal78** [comment]
if you would like to immediately scroll to the bottom of the list on start (in the initState()), you can place the following code chunk from Collin’s solution before the first time you call setState().

This Can Help Chek It [Here ](https://icetutor.com/question/how-to-get-full-size-of-a-scrollcontroller)

**Comment by milanpatel18** [comment]
You will want to use the LayoutBuilder widget which will build at layout time and provides the parent widget’s constraints.

The LayoutBuilder takes in a build() function which has the the standard BuildContext along with the BoxConstraints as parameters that can be used to help dynamically render widgets based on size.

Let’s build a simple example of widget that renders “LARGE” if the parent width is greater than 200px and “SMALL” if the parent width is less or equal to that.

https://icetutor.com/question/how-can-i-layout-widgets-based-on-the-size-of-the-parent/

**Comment by feinstein** [comment]
@mehmetf I have a similar issue, but not related to scroll or a click of a button, I want to achieve this:

![contact](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQcaa3bRvjvsqWTn7tCNZMLsa79hVlJDRSdE0bqI9SmF30nINyF)

Basically, an `AppBar` with an image on the back. The problem is `AppBar` has a fixed size, and `SliverAppBar` needs an `expandedHeight`, so I need to grab the future height of my widget to provide it into `expandedHeight`.

And the images can have different sizes, so I can't just throw an aspect ratio calculation (and even if I did, I wanted to know how to solve this for other cases where I need the size of a widget).

**Comment by AkiraMizoguchi** [comment]
I personally use another way to solve the problem above
here is my way.
<img width="597" alt="スクリーンショット 2020-12-26 午前2 58 03" src="https://user-images.githubusercontent.com/67590079/103140169-d4d52580-4726-11eb-9ff8-0cd26a18efc8.png">
