### ISSUE TITLE
Using mysql in flutter

### ISSUE THREAD

**Issue by Ajikuru** [flutter/flutter#16068]
I'm new to flutter and i really want to know, is there a way to connect to a database server (for instance mysql which is hosted on inmotion server) in flutter rather using firebase. 

I'm working on a project whichi need to connect to the mysql database (hosted on inmotion server) to generate some Account report. Pls i need someone to help out.

Thanks

**Comment by Ajikuru** [comment]
I have try to get in touch with my hosting provider (inmotion) but they
don't have an API for MySQL what can I do.

I forget to say this I have the project writing in PHP which is hosted on
inmotion server. I only want to make an app that I can use to fetch some
database from the database and make a report with the data.

**Comment by zoechi** [comment]
Usually you build a server app yourself that provides such an API. You can do that using Dart, PHP, or any other language.

**Comment by Ajikuru** [comment]
Thanks I really appreciate you reply.

Let say the API was written in PHP how can I use it in with flutter.

Thanks.

**Comment by zoechi** [comment]
You can just make HTTP requests https://webdev.dartlang.org/articles/get-data/json-web-service

**Comment by Ajikuru** [comment]
Thanks a lot.

I will try and work on it. I really appreciate chatting with you.

**Comment by zoechi** [comment]
Sure, if you're stuck please ask in

- https://stackoverflow.com/questions/tagged/flutter 
- https://gitter.im/flutter/flutter
- https://gitter.im/dart-lang/TALK-general

GitHub issues are for bug reports and feature requests.

Would you mind closing this issue?
