### ISSUE TITLE
Add 15 days to 2024-03-03 00:0000 and the new DateTime is 2024-04-18 01:00:00 (why is the new date "time" changed?)

### ISSUE THREAD

**Issue by ykoehler** [flutter/flutter#160641]
### Steps to reproduce

      DateTime test1 = DateTime(2024, 3, 3);
      DateTime test2 = test1.add(Duration(days: 15));
      print("test1 $test1 test2 $test2");

### Expected results

test1 2024-03-03 00:00:00.000 test2 2024-03-18 00:00:00.000

### Actual results

test1 2024-03-03 00:00:00.000 test2 2024-03-18 01:00:00.000

For some reason, the "hour" goes from 00 to 01.  It actually doesn't do that with other date so far that I test with.

### Code sample

<details open><summary>Code sample</summary>

```dart
      DateTime test1 = DateTime(2024, 3, 3);
      DateTime test2 = test1.add(Duration(days: 15));
      print("test1 $test1 test2 $test2");
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1.1 24B2091 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.96.1)
[✓] Connected device (4 available)
    ! Device emulator-5566 is offline.
[✓] Network resources

• No issues found!
```

</details>

**Comment by ykoehler** [comment]
So the logic issue appears to be related to daytime savings... I hit the same issue in November.

Would it be possible to implement a method to DateTime such as addDays(), addMonths(), etc.  So that we can work with DateTime without the "time" aspect and not get hit by those issue which, the more I think about it, the more I feel is a DateTime design.  Adding 1 hour to a DateTime when the daytime saving hits will return you a no change, that make no sense, not clear why people think it is acceptable for add to return the exact same date time value if you add 1 hour at the time the clock has to go back.


When doing date arithmetic such as add(), date should be converted to a non-daylight saving datetime first internally, then you do the algorithmic and then you convert it back to local date time.

It is also strange that Duration accept days as a parameter but can only represent that as hours...  Really think there is a DateTime design issue here.

**Comment by ykoehler** [comment]
The same issue exists with days at every 4 years...  calculate diff between date exceeding 4 years fails because inDays() doesn't round up...

Again, this is a bad design, no one can safely use Duration/add() or inDays because of that, what is the point inDays() if you can't use it.

There are workaround, but a workaround is to work around a bug...

**Comment by danagbemava-nc** [comment]
This should be reported on the dart-lang/sdk repo as the DateTime class is part of the dart:core libraries. https://github.com/dart-lang/sdk/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

Closing from here as this a core dart-lang issue. 

Thank you

**Comment by ykoehler** [comment]
Found a similar ticket on the sdk: https://github.com/dart-lang/sdk/issues/48744

Thanks will bring my concern over there.
