### ISSUE TITLE
Tooltip of FAB doesn't end up as semantics label of FAB

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#16063]

**Comment by goderbauer** [comment]
This broke somewhere between 3352a3fb488df4742ff323243d3dc44d9b7cd3e8 and bffae2157102dd75a625153d3dc866d3de69c853. Need to bisect further to narrow it down.

**Comment by tvolkert** [comment]
Culprit is https://github.com/flutter/flutter/pull/15841

**Comment by HansMuller** [comment]
Do you have a regression test that demos the problem? Looking at the FAB implementation: creates  a Tooltip and the Tooltip creates a semantics node whose label is the tooltip...

**Comment by tvolkert** [comment]
This was caught by an internal regression test during a Flutter Google roll.

As part of this fix, we should add a test that runs on Travis too.

**Comment by goderbauer** [comment]
This might be a bug in the merge algorithm for semantics nodes. I plan to debug in the afternoon.
