### ISSUE TITLE
Offer a bundled iOS 11 style large-title pull-to-refresh

### ISSUE THREAD

**Issue by xster** [flutter/flutter#16069]
iOS 11 has a pull-to-refresh between the persistent nav bar and its scrollable large title instead of below the nav bar in the scrollable list itself. 

Offer a default built-in equivalent.

**Comment by xster** [comment]
CupertinoRefreshControl reuses some of the subcomponents of BouncingScrollPhysics (to deal with snap back etc) which are not the default behavior on Android. If you want to pull them in, see the ScrollConfiguration widget.

**Comment by shaohui10086** [comment]
Thank you for you reply. I will have a try.

**Comment by HansMuller** [comment]
We are investigating this as part of https://github.com/flutter/flutter/issues/124330 and see https://github.com/flutter/uxr/discussions/93
