### ISSUE TITLE
Flutter upgrade has mismatched engine versions on master

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#160640]
These two hashes should be the same.

```
PS C:\Users\john> flutter --version
Flutter 3.28.0-2.0.pre.38547 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8ad15cd81e (3 hours ago) • 2024-12-19 15:52:54 -0800
Engine • revision b79ee9282c
Tools • Dart 3.7.0 (build 3.7.0-260.0.dev) • DevTools 2.41.0
```

The `bin\internal\engine.version` and `bin\cache\engine-dart-sdk.stamp` files are the the same value:  `b79ee9282c3403197dece9dfeb82a90abe85a5f3` and yet:

```
git -C "$flutterRoot"  merge-base HEAD origin/master
8ad15cd81e4cd2ad86524a8afa7021ea51c09169
```

**Comment by jtmcdole** [comment]
Previous code to download the hash is found in `update_dart_sdk.ps1`; but that code is called by `shared.bat` only if:

```BAT
  IF NOT EXIST "%engine_stamp%" GOTO do_sdk_update_and_snapshot
  SET /P dart_required_version=<"%engine_version_path%"
  SET /P dart_installed_version=<"%engine_stamp%"
  IF %dart_required_version% NEQ %dart_installed_version% GOTO do_sdk_update_and_snapshot
```

A clean checkout of the tree means engine.version will not be there; but we leave it behind because downstream tools require its presence.  It should be safe to outright call the update_dart_sdk.ps1 if merged since there are safeguards:

```PS1
if ((Test-Path $engineStamp) -and ($engineVersion -eq (Get-Content $engineStamp))) {
    return
}
```

**Comment by jtmcdole** [comment]
This appears to work at first glance; but then it fails because it runs the download at each invocation. We could probably break out a new ps1 / sh file to find the engine version and bail out quickly. 

```BAT
  IF EXIST "%FLUTTER_ROOT%\DEPS" IF EXIST "%FLUTTER_ROOT%\engine\src\.gn" GOTO do_sdk_update_and_snapshot
```

```shell
PS C:\Users\john> flutter --version
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ...
Building flutter tool...
Running pub upgrade...
Resolving dependencies... (1.0s)
Downloading packages...
Got dependencies.
Flutter 3.28.0-2.0.pre.38547 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8ad15cd81e (3 hours ago) • 2024-12-19 15:52:54 -0800
Engine • revision 8ad15cd81e
Tools • Dart 3.7.0 (build 3.7.0-260.0.dev) • DevTools 2.41.0
```

**Comment by yjbanov** [comment]
If this turns out to be caused by some custom remotes again, how about we consider adding a new remote that doesn't use a common name such as `origin` or `master`, but something Flutter-specific, perhaps literally `flutter`? That is, the bash/ps scripts can do:

```
git remote add flutter https://github.com/flutter/flutter.git
```

Then we change all our code to use `flutter/master` as the source of Flutter's true version history.

**Comment by jtmcdole** [comment]
This is not that; its just higher in the stack (setup.bat vs update_dart_sdk.ps1)-  We were originally going to delete the engine.version file completely and update the tool to use the CAH.  I just need to ensure the engine.version is correct - which is "move the logic for writing engine.version out of update_dart_sdk.* and call it in setup.*"
