### ISSUE TITLE
Add built-in export and import functionality for Flutter tables.

### ISSUE THREAD

**Issue by soufianebenyaala** [flutter/flutter#160769]
### Use case

Users often need to export table data to formats like CSV, Excel, or PDF, or import such data for display.

### Proposal

Introduce methods like `exportToCsv() `and `importFromCsv() `in DataTable.

**Comment by iapicca** [comment]
> export table data to formats like CSV, Excel, or PDF

there are 3rd party packages that provide similar functions, (eg: [syncfusion_flutter_pdf](https://pub.dev/packages/syncfusion_flutter_pdf#extract-text))
