### ISSUE TITLE
Document font discovery / fallback

### ISSUE THREAD

**Issue by xster** [flutter/flutter#16077]
Extracting from https://github.com/flutter/flutter/issues/6139#issuecomment-278454660

would be nice to document the font discovery mechanism / choices in https://docs.flutter.io/flutter/painting/TextStyle/fontFamily.html or somewhere and describe if there's a preset number of bundled assets available, inherited from the OS or something.

**Comment by markusaksli-nc** [comment]
Closing this since custom fonts are explained in [cookbook](https://flutter.dev/docs/cookbook/design/fonts) and the system defaul fallback in [fontFamilyFallback](https://api.flutter.dev/flutter/painting/TextStyle/fontFamilyFallback.html)

> When fontFamily is null or not provided, the first value in fontFamilyFallback acts as the preferred/first font family. When neither is provided, then the default platform font will be used.
