### ISSUE TITLE
go_route unnecessary rebuilds

### ISSUE THREAD

**Issue by xOldeVx** [flutter/flutter#160724]
### Steps to reproduce

First problem:
1. Run the example app - you can see the `return const HomeScreen();` is running twice, instead of only once.

Second problem:
1. Click on "Go to the Details screen" button. - you can see the `return const DetailsScreen();` is running fine BUT after this the `return const HomeScreen();` is running and rebuild the `HomeScreen`!

Third problem:
1. Now click on Back button (on the device), and you can see the `return const HomeScreen();` is running again and rebuild the `HomeScreen`...

I focused these problems in my own project and i thought it's because of some changes in my code, but I see the same behaviour is in the official example

### Expected results

First problem:
Expected `return const HomeScreen();` to run only once.

Second problem:
Expected only `return const DetailsScreen();` run.

Third problem:
Expected nothing to run or at least not REBUILD the HomeScreen widget.

### Actual results

First problem:
`return const HomeScreen();` is running twice.

Second problem:
`return const HomeScreen();` running additionally.

Third problem:
`return const HomeScreen();` is rebuild the HomeScreen widget.

### Code sample

<details open><summary>Code sample</summary>

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app shows an app with two screens.
///
/// The first route '/' is mapped to [HomeScreen], and the second route
/// '/details' is mapped to [DetailsScreen].
///
/// The buttons use context.go() to navigate to each destination. On mobile
/// devices, each destination is deep-linkable and on the web, can be navigated
/// to using the address bar.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return const DetailsScreen();
          },
        ),
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.go('/details'),
          child: const Text('Go to the Details screen'),
        ),
      ),
    );
  }
}

/// The details screen
class DetailsScreen extends StatelessWidget {
  /// Constructs a [DetailsScreen]
  const DetailsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.go('/'),
          child: const Text('Go back to the Home screen'),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6.1 23G93 darwin-arm64, locale en-IL)
    • Flutter version 3.24.4 on channel stable at /Users/myUser/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (8 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/myUser/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/myUser/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.96.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • SM S908E (mobile)               • R5CTA0YHY4F           • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by iapicca** [comment]
@xOldeVx 
yeah, lately flutter documentation is quite poor
here is the solution

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final GoRouter _router = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      pageBuilder: (context, state) => MaterialPage(
        key: state.pageKey,
        child: const HomeScreen(),
      ),
      routes: [
        GoRoute(
          path: 'details',
          pageBuilder: (context, state) => MaterialPage(
            key: state.pageKey,
            child: const DetailsScreen(),
          ),
        ),
      ],
    ),
  ],
);

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(context) => MaterialApp.router(
        routerConfig: _router,
      );
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(context) {
    print('building HomeScreen');
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.go('/details'),
          child: const Text('Go to the Details screen'),
        ),
      ),
    );
  }
}

class DetailsScreen extends StatelessWidget {
  const DetailsScreen({super.key});

  @override
  Widget build(context) {
    print('building DetailsScreen');
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => context.go('/'),
          child: const Text('Go back to the Home screen'),
        ),
      ),
    );
  }
}

```

**Comment by xOldeVx** [comment]
@iapicca It's really fix the first issue, thanks! but the second and the third issues is still exists

**Comment by iapicca** [comment]
> @iapicca It's really fix the first issue, thanks! but the second and the third issues is still exists

does it? in the latest flutter version doesn't show up (look the logs)

[dartpad example](https://dartpad.dev/?id=08dc2bd1d210e163b561399d1974ba84)

**Comment by xOldeVx** [comment]
I checked it by a breakpoint and I saw every it's still exists, but you read, only the breakpoint is triggered (at `pageBuilder: (context, state) => MaterialPage()`), but the screen isn't rebuild thanks to `state.key`.

One more thing, it's fix the problems only if using `const` keyword (omit it and watch the logs), but In my real project I can't use `const` in all my screens, so it's not really fix my problem :|

**Comment by iapicca** [comment]
> One more thing, it's fix the problems only if using `const` keyword (omit it and watch the logs), but In my real project I can't use `const` in all my screens, so it's not really fix my problem :|

I'm afraid it kinda is your problem,  it does make a difference if the widget is `const` or not.
I'm assuming it can't be `const` because you are passing some argument to the page constructor, 
why not making it available through riverpod?

actually I strongly recommend to slap the whole router in [riverpod](https://pub.dev/packages/riverpod), 
it will make your life much easier, just:

1. create the router provider somewhere

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

@riverpod
GoRouter router(RouterRef ref) {
  final router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        pageBuilder: (context, state) => MaterialPage(
          key: state.pageKey,
          child: HomeScreen(),
        ),
        routes: [
          GoRoute(
            path: 'details',
            pageBuilder: (context, state) => MaterialPage(
              key: state.pageKey,
              child: DetailsScreen(),
            ),
          ),
        ],
      ),
    ],
  );
  ref.onDispose(router.dispose);
  return router;
}

```

2. use it in `MaterialApp`

```dart
class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
    Widget build(context, ref) => MaterialApp.router(
      routerConfig: ref.watch(routerProvider),
    );
  }
}
```

3. use the navigator normally (eg:`context.go('/'),`)
4. pass whatever info  you need for your page through `riverpod` so that can be `const`

**Comment by xOldeVx** [comment]
Thank you, it's really can be a solution, but it's not change the fact that every change route the main route is trigger ( `I mean pageBuilder: (context, state) => MaterialPage( `). It's really worrying that Google maintains this library and there are bugs like this.

**Comment by iapicca** [comment]
> Thank you, it's really can be a solution, but it's not change the fact that every change route the main route is trigger ( `I mean pageBuilder: (context, state) => MaterialPage( `). It's really worrying that Google maintains this library and there are bugs like this.

I don't think it's a bug, I believe this behavior is intended

**Comment by danagbemava-nc** [comment]
There are several issues related to rebuilding in go_router and based on the team member comments, these are not bugs. Rebuilds are to be expected. 

Closing based on the comments below

https://github.com/flutter/flutter/issues/108730#issuecomment-1205795863
https://github.com/flutter/flutter/issues/132049#issuecomment-1673962209
https://github.com/flutter/flutter/issues/138708#issuecomment-1834679881
https://github.com/flutter/flutter/issues/144511#issuecomment-2116270547


> I'm more concerned by the fact that nobody triaged the issue in a week time

@iapicca, we were away for the holidays

**Comment by iapicca** [comment]
> @iapicca, we were away for the holidays

merry christmas
