### ISSUE TITLE
Add support for right-click or long-press context menus for table rows/cells.

### ISSUE THREAD

**Issue by soufianebenyaala** [flutter/flutter#160774]
### Use case

Many desktop applications provide context menus to interact with individual rows or cells in a table (e.g., to delete or edit a record). Flutter tables lack this built-in functionality.

### Proposal

Implement a context menu system where right-click or long press triggers an options menu for rows/cells.

**Comment by iapicca** [comment]
according to the docs [PaginatedDataTable](https://api.flutter.dev/flutter/material/PaginatedDataTable-class.html) is 
`A table that follows the [Material 2](https://material.io/go/design-data-tables) design specification, using multiple pages to display data.`
and said [design](https://m2.material.io/components/data-tables) doesn't include this functionality
