### ISSUE TITLE
flutter_tools feature request- prime hot reload

### ISSUE THREAD

**Issue by jwren** [flutter/flutter#16078]
After the initial launch of a Flutter app onto a device, immediately kick off a hot reload.

The initial launch takes many seconds, lets say 10.  If it takes 11.5 before everything is done, but at the same 10 seconds my app is up and running, the experience is basically equivalent.

If though because of this, my initial hot reload never takes the first 1500ms, but starts and stays at 200ms-300ms even from the first reload, then the first impression is much better.

**Comment by jonahwilliams** [comment]
Based on the performance improvements we've made to hot reload this should no longer be necessary:

```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone XS Max is available at: http://127.0.0.1:65463/tuR8EbEfzRA=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Initializing hot reload...                                              
Reloaded 0 of 315 libraries in 63ms.

Performing hot reload...                                                
Reloaded 0 of 315 libraries in 44ms.

Performing hot reload...                                                
Reloaded 0 of 315 libraries in 47ms.
```
