### ISSUE TITLE
Tree is red because engine binaries are not available (yet?)

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#160704]
The PR https://github.com/flutter/flutter/pull/160690 was merged by the merge queue as commit  https://github.com/flutter/flutter/commit/3dc695d1ad9a76a56420efc09fd66abd501fc691. When post-submits were scheduled, they all(?) failed with a 404 to download engine binaries, for example:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_5_5/1913/infra

```
[   +1 ms] "flutter update-packages" took 3,716ms.
[   +9 ms] Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/3dc695d1ad9a76a56420efc09fd66abd501fc691/flutter_patched_sdk_product.zip. Ensure you have network connectivity and then try again.
           Exception: 404
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
           #1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1152:11)
           <asynchronous suspension>
           #2      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:992:7)
           <asynchronous suspension>
           #3      CachedArtifact.update (package:flutter_tools/src/cache.dart:894:5)
           <asynchronous suspension>
           #4      Cache.updateAll (package:flutter_tools/src/cache.dart:765:9)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1862:7)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1558:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:496:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:98:11)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:99:3)
           <asynchronous suspension>
```

I'm not sure if it's relevant, but this PR was merged with the `warning: land on red to fix tree breakage` label.

**Comment by jtmcdole** [comment]
fyi: @yjbanov

**Comment by jtmcdole** [comment]
We need to:

* Make all presubmits block adding to the MQ
* Make the MQ run a smoke test that proves the tool can run before allowing it to merge.

**Comment by jtmcdole** [comment]
Yegor has found that the linux_host build (which is responsible for this) has the wrong hash:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_host_engine/13603/overview

**Comment by yjbanov** [comment]
It seems LUCI has checked out the wrong revision. [This build](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/1026792/infra) should have checked out 3dc695d1ad9a76a56420efc09fd66abd501fc691. However, instead it checked out 021b2b36275342ad94a1ef44f9748b1e6153b0a3, as you can see in [this log](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8727987248893864001/+/u/Checkout_source_code/bot_update/json.output).

**Comment by yjbanov** [comment]
**New hypothesis**: cocoon is checking for the existence of the commit in GoB, but it doesn't check if the main/master branch has been retagged to that commit, so when LUCI fetches `upstream master` there's no guarantee that you will get the correct commit.

**Comment by jtmcdole** [comment]
Most damning "this is a race condition" is the following lines:

```
**2024-12-20 16:10:29.010484 ===Running git checkout --force refs/remotes/origin/HEAD -- ===
In directory: /b/s/w/ir/cache/builder/.
Previous HEAD position was a44f745180 Allow integration test helpers to work on substrings instead of whole strings (#160437)
HEAD is now at 021b2b3627 Ensure engine.version is up to date in the monorepo (#160668)
post-checkout: The engine source tree has been updated.
```

The commit under test was not `021b2b3627`. 
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8727987248893864001/+/u/Checkout_source_code/bot_update/stdout

**Comment by DanTup** [comment]
Not sure if it's obvious/known, but just in case - this issue isn't isolated to the bots, it prevents syncing to master for development too (see https://github.com/flutter/flutter/issues/160654 - I also see this locally).

**Comment by sma** [comment]
… and one cannot switch channels once the installation got broken, so you have to reinstall flutter.

**Comment by jtmcdole** [comment]
@yjbanov : I'm going to look into setting the url and ref to force the correct checkout.

@sma - the install is just a git check out.  If you `git checkout stable` it will return you to a valid state.

**Comment by jtmcdole** [comment]
Going back and looking at some logs for the first failure:

* The other orchestrator builds were happy with the tags and able to get the correct version
* It was just the linux_host_engine that got the wrong one

## Clang Tidy

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_clang_tidy/9560/in

```json
{
  "got_revision": "3dc695d1ad9a76a56420efc09fd66abd501fc691"
}
```

## Linux Web

```json
{
  "cas_output_hash": {
    "wasm_release": null
  },
  "git_cache_epoch": "1714507002",
  "got_engine_revision": "3dc695d1ad9a76a56420efc09fd66abd501fc691"
}
```

## Linux Host Build Infra Page
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_host_engine/13603/infra

Tags
buildset:	commit/git/3dc695d1ad9a76a56420efc09fd66abd501fc691
buildset:	[commit/gitiles/flutter.googlesource.com/mirrors/flutter/+/3dc695d1ad9a76a56420efc09fd66abd501fc691](https://flutter.googlesource.com/mirrors/flutter/+/3dc695d1ad9a76a56420efc09fd66abd501fc691)

```json
{
  "git_cache_epoch": "1714507002",
  "got_engine_revision": "021b2b36275342ad94a1ef44f9748b1e6153b0a3",
  "got_revision": "021b2b36275342ad94a1ef44f9748b1e6153b0a3"
}
```

### Drone

```json
{
  "cas_output_hash": {
    "ci/host_debug": null,
    "full_build": "3da3f09c14188a64b116309c2fa1b9da573ea9ac1cfc02643eff4412935c1e5d/76"
  },
  "git_cache_epoch": "1714507002",
  "got_engine_revision": "021b2b36275342ad94a1ef44f9748b1e6153b0a3"
}
```


The cache epoch is the same.

**Comment by jtmcdole** [comment]
The specific  luci/recipe section that has me questioning my sanity:

`recipe_modules/repo_util/api.py`

```python
  def engine_checkout(
...
    git_url = REPOS[engine_repo]
    git_id = self.m.buildbucket.gitiles_commit.id
    git_ref = self.m.buildbucket.gitiles_commit.ref
    if 'git_url' in self.m.properties and 'git_ref' in self.m.properties:
      git_url = self.m.properties['git_url']
      git_id = self.m.properties['git_ref']
      git_ref = self.m.properties['git_ref']
```

Where in cocoon we set:

```dart
      gitilesCommit: bbv2.GitilesCommit(
        project: 'mirrors/${commit.slug.name}',
        host: 'flutter.googlesource.com',
        ref: 'refs/heads/${commit.branch}',
        id: commit.sha,
      ),
```

This ends up using gclient to checkout the tree:

```python
            src_cfg = self.m.gclient.make_config()
            soln = src_cfg.solutions.add()
            soln.name = repo_path
            soln.url = git_url
            soln.revision = git_id
            soln.managed = False
            soln.custom_vars = local_custom_vars
            src_cfg.parent_got_revision_mapping['parent_got_revision'
                                               ] = 'got_revision'
            src_cfg.repo_path_map[git_url] = (
                repo_path, git_ref or
                'refs/heads/%s' % default_branch
            )
            self.m.gclient.c = src_cfg
```

**Comment by jtmcdole** [comment]
That said; I'm running on one cup of coffee and I keep coming back to: the orchestrator just calls git fetch and gets the wrong fetch_head. Could this be because we set `"exe_cipd_version": "refs/heads/master"`?  The git-fetch step should probably not be calling origin - master.

```
Executing command [
  '/b/s/w/ir/cipd_bin_packages/git',
  'fetch',
  'origin',
  'master',
  '--recurse-submodules',
  '--progress',
  '--tags',
]
escaped for shell: /b/s/w/ir/cipd_bin_packages/git fetch origin master --recurse-submodules --progress --tags
```

**Comment by jtmcdole** [comment]
The git_ref for api.py checkout:
```python
        git_ref = (
            ref or self.m.buildbucket.gitiles_commit.id or
            self.m.buildbucket.gitiles_commit.ref or
            'refs/heads/%s' % REPO_BRANCHES[name]
        )
```

the call to this in engine_v2 (which is not gclient)
```python
    parent_commit = api.repo_util.checkout(
        project,
        checkout_path=checkout_path,
        url=api.properties.get('git_url'),
        ref=api.properties.get('git_ref')
    )
```

We do not set `git_url` or `git_ref` in Cocon when scheduling the merge queue. The only time we set `git_ref` is for presubmits. We do set the gitiles though:

```dart
      gitilesCommit: bbv2.GitilesCommit(
        project: 'mirrors/${commit.slug.name}',
        host: 'flutter.googlesource.com',
        ref: 'refs/heads/${commit.branch}', // this is gh-readonly-queue/master/pr-160690-021b2b36275342ad94a1ef44f9748b1e6153b0a3
        id: commit.sha, // headSha which is 3dc695d1ad9a76a56420efc09fd66abd501fc691
      ),
```

So at a minimum, the git_ref should be 3dc695d1ad9a76a56420efc09fd66abd501fc691. This isn't logged though.

**Comment by jtmcdole** [comment]
in `.recipe_deps/depot_tools/recipes/recipe_modules/git/api.py`:

```python
      # There are five kinds of refs we can be handed:
      # 0) None. In this case, we default to api.buildbucket.gitiles_commit.ref.
      # 1) A fully qualified branch name, e.g. 'refs/heads/main'.
      #    Chop off 'refs/heads/' and now it matches case (4).
      # 2) A 40-character SHA1 hash.
      # 3) A fully-qualifed arbitrary ref, e.g. 'refs/foo/bar/baz'.
      # 4) A branch name, e.g. 'main'.
      # Note that 'FETCH_HEAD' can be many things (and therefore not a valid
      # checkout target) if many refs are fetched, but we only explicitly fetch
      # one ref here, so this is safe.
      if not ref:                                  # Case 0.
        ref = self.m.buildbucket.gitiles_commit.ref or 'main'

      # If it's a fully-qualified branch name, trim the 'refs/heads/' prefix.
      if ref.startswith('refs/heads/'):            # Case 1.
        ref = ref[len('refs/heads/'):]

      fetch_args = []
      if self._GIT_HASH_RE.match(ref):             # Case 2.
        fetch_remote = remote_name
        fetch_ref = ''
        checkout_ref = ref
      else:                                        # Cases 3 and 4.
        fetch_remote = remote_name
        fetch_ref = ref
        checkout_ref = 'FETCH_HEAD'
```

when I look at the logs, its fetching master and then the checkout_ref is `FETCH_HEAD`.


**If we look at a successful run like [linux_android_aot_engine](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_android_aot_engine/13567/overview)** - you can see it does the right things, and the recipe has the gitiles. This is the missing part from the failed run:

```json
        "gitilesCommit": {
          "host": "flutter.googlesource.com",
          "project": "mirrors/flutter",
          "id": "3dc695d1ad9a76a56420efc09fd66abd501fc691",
          "ref": "refs/heads/gh-readonly-queue/master/pr-160690-021b2b36275342ad94a1ef44f9748b1e6153b0a3"
        },
```

**Comment by munrocket** [comment]
> … and one cannot switch channels once the installation got broken, so you have to reinstall flutter.

This is really annoying.

**Comment by jtmcdole** [comment]
It was pointed out that the only place `gitilesCommit` is not copied over is on a retry - and it looks like the failed build here was a retry.  The extra properties did ride along, so if we did set `git_ref` to the branch, it would work.

**Comment by jtmcdole** [comment]
build linux_host_engine 8727887820311286353 failed and was [rescheduled](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_host_engine/13620/overview) with the correct gitiles.  Uploads look correct. Waiting for post submits before closing.

**Comment by jtmcdole** [comment]
woot
