### ISSUE TITLE
Add row highlighting on hover for Flutter tables.

### ISSUE THREAD

**Issue by soufianebenyaala** [flutter/flutter#160776]
### Use case

For better user interaction, highlighting a row when the user hovers over it is common in desktop applications, especially when selecting or editing items.

### Proposal

Implement a `hoverHighlight: true` property to `DataTable` that automatically highlights rows on hover for desktop platforms.

**Comment by iapicca** [comment]
DataTable already highlight the row on hover,  see [code sample](https://dartpad.dev/?id=8e489f2af93b644b4ca0aede6a827b13)
