### ISSUE TITLE
[pigeon] Make generated Swift classes and protocols public

### ISSUE THREAD

**Issue by feduke-nukem** [flutter/flutter#160737]
### Use case

I am using add-to-app approach with Pigeon and the result is great. However I had to fork the library to add `public` to generated `Swift` classes/structures/protocols.

This is a kind of a duplicate of [issue](https://github.com/flutter/flutter/issues/150691) but I believe that it was closed unfair and Pigeon should not limit users in such scenario. Kotlin code is generated `public` by default so what's the problem to do the same in Swift?

The 'recommendation' to make 'wrappers' around generated code is unnecessary boilerplate almost in 100% of cases (at least for our application) but I agree that such 'wrappers' are more 'clean'  way to maintain public API. However, I believe that it should be the choice not the restriction.

### Proposal

The same as https://github.com/flutter/flutter/issues/150691

**Comment by stuartmorgan** [comment]
> This is a kind of a duplicate of [issue](https://github.com/flutter/flutter/issues/150691) but I believe that it was closed unfair 

Please do not file duplicate issues just because you disagree with the outcome of the original.

> Kotlin code is generated `public` by default so what's the problem to do the same in Swift?

This is an oversight; I've filed https://github.com/flutter/flutter/issues/160739

Closing as a duplicate.

**Comment by feduke-nukem** [comment]
> Please do not file duplicate issues just because you disagree with the outcome of the original.

Why?

There's community request for such changes. Why couldn't there be any appropriate discussion on that without 'dictatorship attitude' ?

Flutter provides freedom with many aspects and it is disappointing to see such desicions

**Comment by stuartmorgan** [comment]
> There's community request for such changes. Why couldn't there be any appropriate discussion

There was discussion. Then we, the package owners, reached a conclusion.

> What is the problem for adding `SwiftVisibilityModifier`/`KotlinVisibilityModifier` or something that will provide opportunity to control `public` or `private` (or whatever) class would be.

We do not want to add complexity to the package for the sole purpose of supporting a use case that we believe is an anti-pattern given the way Pigeon is developed.

> This is a developer choice that you are restricting for no reason

We do have a reason. The fact that you disagree with the reason isn't the same as us not having one.

**Comment by feduke-nukem** [comment]
> We do not want to add complexity to the package for the sole purpose of supporting a use case that we believe is an anti-pattern given the way Pigeon is developed.

Such an anti-pattern that Kotlin code was generating `public` since the beginning and only now you have noticed that.

That's ironic actually.

**Comment by yuukiw00w** [comment]
Since the Swift code generated by pigeon causes an error in Swift 6 mode, I tried to isolate it as a package to be built in Swift 5, but since it is not public, I was not able to do that. If making it public is also unacceptable, I think it would be better to establish a system that can quickly respond to the latest language version so that errors do not occur. What do you think?

**Comment by stuartmorgan** [comment]
> Such an anti-pattern that Kotlin code was generating `public` since the beginning and you have noticed that only now.
> 
> That's ironic actually.

I'm not sure how it's ironic that we've never noticed that a thing that we have never tried to do, because we think it's an anti-pattern, happens to work. It seems entirely expected to me that we would not have noticed a thing that we have no mechanism to have noticed organically, and that nobody has ever had any cause to report an issue about (since people generally don't report issues about things that *do* work the way they want them to).

**Comment by stuartmorgan** [comment]
> I think it would be better to establish a system that can quickly respond to the latest language version so that errors do not occur.

If you have specific suggestions about how to make things easier for community members interested in adding better compatibility with Swift 6, please file a feature request.

**Comment by yuukiw00w** [comment]
I have raised some issues for Swift 6, but they have been left unattended. If this situation continues, I would like the ability to add public so that it can be isolated as a package fixed for a specific language version.

**Comment by stuartmorgan** [comment]
> I have raised some issues for Swift 6, but they have been left unattended.

I don't see any issues that you have filed that haven't been triaged. If by "unattended" you mean not fixed, please see https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#when-will-my-bug-be-fixed.

> If this situation continues, I would like the ability to add public

You are certainly welcome to fork Pigeon or to manually edit Pigeon's output to make things public. We are not going to add API complexity to Pigeon for the purpose of working around an issue that could instead be fixed. Anyone is welcome to submit fixes for issues that are important to them.
