### ISSUE TITLE
[path_provider][windows] Paths reported are not the real ones when app installed from Microsoft Store

### ISSUE THREAD

**Issue by kaciula** [flutter/flutter#160729]
### What package does this bug report belong to?

path_provider

### What target platforms are you seeing this bug on?

Windows

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

https://pastebin.com/8QLYvsSL

</details>

### Steps to reproduce

`getApplicationSupportDirectory()` returns a path such as `C:\Users\John\AppData\Roaming\CompanyName\AppName` and it works fine to save and read files using this and dart:io.

However, I see that the actual location for this directory is at a path such as `C:\Users\John\AppData\Local\Packages\CompanyAppNameHash\LocalCache\Roaming\CompanyName\AppName`

So it seems there is some abstraction/translation of paths being done by Flutter or Windows OS. 

The issue I am running into is that I want to run an in-app executable with `Process.run` and I need the actual paths in order to run it. It seems that `Process.run` does not do the abstraction/translation part that happens when using dart:io and so the commands fail by not resolving the supplied paths. I don't see any way to get the real paths to use in the command.

One thing to note is that I think the different paths situation happen when you install the app from Microsoft Store. Locally on my Windows 10 dev machine, the paths reported (`\Roaming\CompanyName\AppName` ) are the actual paths. However, when installing the app from MS Store on a different Windows 10 computer, the real paths are different from the reported ones, as noted above.

### Expected results

Return the real paths or provide a way to map the abstracted paths to the real ones.

### Actual results

The paths returned by the plugin are not the real ones and cannot be used in Process.run commands.

### Code sample

<details open><summary>Code sample</summary>

```dart
getApplicationSupportDirectory()
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.19045.5247], locale en-US)
    • Flutter version 3.24.2 on channel stable at C:\dev\tools\flutter       
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (4 months ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.12.35527.113
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).

[√] VS Code (version 1.96.0)
    • VS Code at C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.5247]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.99

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by stuartmorgan** [comment]
`path_provider` simply reports the OS-provided paths; issues with what paths the OS reports in different scenarios would need to be reported to Microsoft.

> or provide a way to map the abstracted paths to the real ones

The community is welcome to make plugins that do path mapping (assuming Windows provides APIs that do that), but it's not in scope for `path_provider`.

Closing as out of scope.
