### ISSUE TITLE
[packages][tool] Analysis breaking after pubspec_parse change.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#160799]
I'm having some analyze repo tools failures in files that I haven't touched in flutter/packages (both in stable and master?)

See: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze%20stable/14294/overview

A couple of lints are failing:

* `invalid_null_aware_operator`
* `unnecessary_non_null_assertion`

---

@bparrishMines took a look and found the root cause:

> It looks like the lint is caused by the `pubspec_parse` package. Their latest version made `Pubspec.environment` nonull: https://pub.dev/packages/pubspec_parse/changelog#140

Fix the tool.

**Comment by munrocket** [comment]
Can confirm, my PR also broken. It can be prehook with `analyze fix` on each commit.

**Comment by munrocket** [comment]
Still broken on PRs in tools, maybe because `strict_top_level_inference` is on.
