### ISSUE TITLE
`Icons.thumb_up_off_alt_rounded` and `Icons.thumb_up_off_alt_sharp` are both filled

### ISSUE THREAD

**Issue by JHubi1** [flutter/flutter#160807]
### Steps to reproduce

1. Add a `Icon(Icons.thumb_up_off_alt_rounded)`
2. Open your eyes

### Expected results

1. The icon should be outlined because of `_off`, without the `_off` it's supposed to be filled
   - `Icons.thumb_down_off_alt_rounded` and `Icons.thumb_down_off_alt_sharp` have the correct behavior

### Actual results

1. Both are filled, see below

### Code sample

<details open><summary>Code sample</summary>

```dart
class WrongIcon extends StatelessWidget {
  const WrongIcon({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
        body: Center(
            child: Column(mainAxisSize: MainAxisSize.min, children: [
      Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Icon(Icons.thumb_up_off_alt_outlined),
            Icon(Icons.thumb_up_off_alt_rounded),
            Icon(Icons.thumb_up_off_alt_sharp)
          ]),
      Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Icon(Icons.thumb_down_off_alt_outlined),
            Icon(Icons.thumb_down_off_alt_rounded),
            Icon(Icons.thumb_down_off_alt_sharp)
          ])
    ])));
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![flutter_01](https://github.com/user-attachments/assets/ef059b0e-1d45-47c1-9004-ac42a71b7cfd)

</details>

### Logs

<details open><summary>Logs</summary>

> Not needed

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.26100.2605], locale de-DE)
    • Flutter version 3.24.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (6 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\jakob\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35027.167
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code, 64-bit edition (version 1.96.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.102.0

[✓] Connected device (3 available)
    • Pixel 6 (mobile)  • 25141FDF6001LD • android-arm64  • Android 15 (API 35)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.26100.2605]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by maheshj01** [comment]
Hello @JHubi1, Thanks for filing the issue. I checked the [material icons](https://fonts.google.com/icons?selected=Material+Icons+Outlined:thumb_down_off_alt:&icon.query=thumb+down&icon.size=24&icon.color=%23e8eaed&icon.set=Material+Icons&icon.style=Rounded&icon.platform=web)  and flutter icons seems to show same behavior. so I would say this is working as expected. 

### Material Icons Flutter 

thumb_up_off_alt_outlined | thumb_up_off_alt_rounded | thumb_up_off_alt_sharp
:-------------------------:|:-------------------------:|:---------------------------------------
thumb_down_off_alt_outlined | thumb_down_off_alt_rounded | thumb_down_off_alt_sharp

<img width="494" alt="image" src="https://github.com/user-attachments/assets/322dd6fe-13f8-4b1f-bad9-bb9f7497854e" />

---
### [Material Icons](https://fonts.google.com/icons?selected=Material+Icons+Outlined:thumb_down_off_alt:&icon.query=thumb+down&icon.size=24&icon.color=%23e8eaed&icon.set=Material+Icons&icon.style=Rounded&icon.platform=web)

thumb_up_off_alt_outlined | thumb_up_off_alt_rounded | thumb_up_off_alt_sharp
:-------------------------:|:-------------------------:|:---------------------------------------
<img width="96" alt="image" src="https://github.com/user-attachments/assets/21ccd11c-5056-40fc-a1d1-7e83a6106d13" /> | <img width="96" alt="image" src="https://github.com/user-attachments/assets/c0362cfc-5c2b-4502-a61c-d10c3e7a2c00" /> | <img width="96" alt="image" src="https://github.com/user-attachments/assets/42273b83-75f8-4219-b182-78188e17166f" />


thumb_down_off_alt_outlined | thumb_down_off_alt_rounded | thumb_down_off_alt_sharp
:-------------------------:|:-------------------------:|:---------------------------------------
<img width="96" alt="image" src="https://github.com/user-attachments/assets/1ea67c13-6a61-4afe-823e-f147d643ca1e" /> | <img width="96" alt="image" src="https://github.com/user-attachments/assets/17537d74-ab2b-4ea2-91ef-f9c86452857b" /> | <img width="96" alt="image" src="https://github.com/user-attachments/assets/2263f343-476b-46f1-9124-021ba1395d15" />

**Comment by maheshj01** [comment]
Closing as invalid. Incase you disagree feel free to write in the comments and we will reopen it.

**Comment by JHubi1** [comment]
Valid, then this is not a Flutter issue, sorry for not checking myself.

I would call it an issue though. The filled icon does use the outlined style, and that's probably the thing you would expect from a turned off icon. That the other styles are missing this behavior is probably an oversight.

Problem is, hence Material Icons are deprecated by Google, there's seemingly no way to request a fix.
