### ISSUE TITLE
@immutable should be moved?

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#160820]
### Use case

``` Dart
import 'package:flutter/material.dart';

@immutable
class Resolution {
  final int width;
  final int height;
  const Resolution(this.width, this.height);
  double get aspectRatio {
    return width / height;
  }
}
``` 

immutable is not related to material app. I think the immutable annotation should be located somewhere else. Maybe it can be part of the dart SDK? I don't see how this is Flutter-specific.

### Proposal

move @immutable

**Comment by danagbemava-nc** [comment]
The same explanation in https://github.com/dart-lang/sdk/issues/59803#issuecomment-2561284061 applies here. It is not defined in material. 

Closing as there's no further action to take here

**Comment by stephane-archer** [comment]
@danagbemava-nc why can this be imported using material.dart?
This probably should not be exposed to the outside through material.dart?

**Comment by danagbemava-nc** [comment]
It is exported by foundation.dart which is exported in material.dart. 
It is done to reduce the number of imports you have in a file. Otherwise you'd most likely have to import every single library that is used in material individually which would create too much cognitive load in a file
