### ISSUE TITLE
Add a parameter in Checkbox Widget to modify the width or size of it.

### ISSUE THREAD

**Issue by rehmaan-dev** [flutter/flutter#160811]
**Current Situation**
As I'm working on web based project using flutter in my org. I created a login screen, which had a "Remember Me" checkbox.
As the project is required to run on small screens i.e Hand Terminals. I needed to size the checkbox.
Below is the attached image.
I tried adding a sized box, but it did not worked as expected.
![image](https://github.com/user-attachments/assets/1442e7fe-e3d0-4234-a3ca-4f0fd048cb98)

### Proposal

**Suggestion**
I made some changes in the checkbox.dart, menu_anchor.dart related to the checkbox. And added an additional parameter named:

- alternateWidth: (nullable type), if null uses the default width specified within the checkbox widget i.e. 18.

This is the result , after the changes:

1. Alt Width : 12 
![image](https://github.com/user-attachments/assets/58543883-e9ba-4f22-b4ba-a1b49dc4d550)

2. Alt Width: 10
![image](https://github.com/user-attachments/assets/9e08820c-7862-4b39-84a4-8ceb1fa4a096)

![image](https://github.com/user-attachments/assets/89715eb0-5685-4837-b1db-fbec4a3e6a55)

Note: I did not wanted to use any external package, therefore I did this modification. So I'm creating this request hoping it's useful for those who need it.

**Comment by danagbemava-nc** [comment]
Closing this based on https://github.com/flutter/flutter/issues/81334#issuecomment-2318465333
