### ISSUE TITLE
Focus-based navigation

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1608]
We should implement next/prev (tab) and direction (d-pad) navigation of focusable controls, and ensure that everything is keyboard-accessible.

From http://developer.android.com/guide/topics/ui/accessibility/checklist.html:

> Make sure users can navigate your screen layouts using hardware-based or software directional controls (D-pads, trackballs, keyboards and navigation gestures). In a few cases, you may need to make user interface components focusable or change the focus order to be more logical for user actions.

**Comment by Hixie** [comment]
See also parts of http://developer.android.com/guide/topics/ui/accessibility/apps.html

**Comment by Hixie** [comment]
We can't use the semantics tree, it's not created if semantics are disabled.

**Comment by gspencergoog** [comment]
Focus navigation order could very well be different from semantics order.  For instance, for focus navigation you probably want to skip the labels in the form, but you don't want to skip them in semantics traversal.

**Comment by jonahwilliams** [comment]
The focus tree is a subset of the semantic tree though (right?).

**Comment by gspencergoog** [comment]
Maybe?  They feel like different use cases, so I wouldn't be surprised to learn that there are cases where it isn't a simple subset.

**Comment by khalithartmann** [comment]
Hello you awesome people!
I just created a Let's Flutter Berlin group on Facebook to bring flutter developers in Berlin together to discuss problems, share ideas and create beautiful things together. If you live in Berlin, it would be awesome if you could join the group 😊! If you don't live in Berlin, feel free to join too! Im grateful for each and every supporter.  

Let's Flutter Berlin: https://www.facebook.com/groups/276520973054067/about/
Sorry for spamming.

**Comment by gspencergoog** [comment]
This was finally fixed by https://github.com/flutter/flutter/pull/40186

**Comment by gspencergoog** [comment]
#40186 had to be reverted :-( . Will close this again as soon as https://github.com/flutter/flutter/pull/42278 lands.

**Comment by gspencergoog** [comment]
This has re-landed in https://github.com/flutter/flutter/pull/42278

**Comment by andredealmei** [comment]
on web , tab not focus next textfield

**Comment by dudeofawesome** [comment]
Tab focus also seems to not work on macOS builds on v1.15.4-pre.83

**Comment by SimonAmpleman** [comment]
Android with external keyboard : When I press tab on the keyboard, it sometime jumps to the next field, sometime add a tab spacing in the field, and sometime add a tab spacing in the field and jump to the next field.

**Comment by gspencergoog** [comment]
@SimonAmpleman, yes, this is a known issue that will be addressed. See https://github.com/flutter/flutter/issues/33521 for progress. Unfortunately, to fix this problem, it's a pretty big change. What's happening is because of two problems: there's no synchronous key handling, so we can't stop propagation of key events when an action handles them (and so the text field eventually gets them too), and there's not one source of truth for the state of a text edit, so editing updates are racy. These will both be addressed. I can't give an exact timeline, but they are a priority.

**Comment by SimonAmpleman** [comment]
Thank you for your detailed reply. Awesome news ! Your team rocks, after so
many years of mobile software development, I am totally blown away by what
you have created !

Good day!

**Comment by Timmmm** [comment]
Am I right in thinking that this adds best-guess automatic tab ordering? There doesn't seem to be any way to specify the tab order manually. I guess that's decent for simple apps but it can give pretty weird results:

https://user-images.githubusercontent.com/376842/110383766-ab087b00-8054-11eb-9d60-3332bf2f87ef.mp4

We need a way to specify the tab order manually. Is there an issue for this already or should I open one?

**Comment by gspencergoog** [comment]
@Timmmm No, we already have that.  Check out [FocusTraversalGroup](https://api.flutter.dev/flutter/widgets/FocusTraversalGroup-class.html) and [OrderedTraversalPolicy](https://api.flutter.dev/flutter/widgets/OrderedTraversalPolicy-class.html).
