### ISSUE TITLE
Chip should support tap handling on the body too; not just delete

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#16083]
Chip widget currently only supports onDelete handler.

We used to wrap it with a `GestureDetector` to detect the taps on the body of the chip but the following no longer works (regression).

```dart
new GestureDetector(
   onTap: () => print('tapped'),
   child: new Chip(
          onDeleted: () => print('removed'),
          deleteButtonTooltipMessage: 'Remove',
          label: new Text('Value'),
   ),
);
```

It would be nice to have:
```dart
new Chip(
   onDeleted:
   onTap:
)
```

**Comment by gspencergoog** [comment]
Heh.  Take a look at this PR: https://github.com/flutter/flutter/pull/16039

All of your dreams will come true, and more.

I'll take a look at the regression too, however.  Probably I'll just have to return "false" for the taps on the main body for the original Chip class, but will support callbacks for the others.
