### ISSUE TITLE
Issue with Keyboard Interaction on iOS 18 in flutter_inappwebview

### ISSUE THREAD

**Issue by shanshen6** [flutter/flutter#160846]
### Steps to reproduce

Dear flutter_inappwebview Team,

I hope this message finds you well.

I am writing to report an issue I have encountered with the flutter_inappwebview plugin on iOS 18. Below are the details of the problem:

Environment:

flutter_inappwebview version: ^6.1.5
Flutter version: 3.28.0-1.0.pre
Dart version: 3.7.0 (build 3.7.0-259.0.dev)
DevTools version: 2.41.0
iOS version: 18
Issue Description: When using the flutter_inappwebview plugin on iOS 18, I have observed the following issues related to keyboard interaction:

Activating the soft keyboard causes the screen to scroll back and forth.
When there are multiple input fields, it becomes impossible to focus on other input fields after focusing on one.
Tapping on a blank area does not dismiss the keyboard.
Tapping on input fields or other elements becomes unresponsive.
These issues significantly affect the user experience, making it difficult to interact with web content within the app.

Steps to Reproduce:

Open a web page with multiple input fields using flutter_inappwebview.
Focus on one of the input fields to activate the soft keyboard.
Attempt to focus on another input field.
Tap on a blank area to dismiss the keyboard.
Expected Behavior:

 207eb954593451e606fde6fea1abfe75.mov 
The screen should not scroll back and forth when the keyboard is activated.
Users should be able to focus on different input fields without any issues.
Tapping on a blank area should dismiss the keyboard.
Tapping on input fields and other elements should be responsive.
I would greatly appreciate any assistance or guidance you can provide to resolve these issues. If you need any additional information or logs, please let me know.

Thank you for your attention to this matter.

Best regards,

### Expected results

like iOS 17

### Actual results

UI error

### Code sample

      <div v-for="(item, idx) of state?.aliasNames" :key="idx" class="inputItem">
        <input
          class="name-input"
          :placeholder="`${idx + 1}`"
          type="text"
          maxlength="20"
          :value="item"
          @input="updateInputTitle(idx, ($event.target as HTMLInputElement)?.value)"
          @keydown="judgeEllipsis(item)"
          @blur="saveDataForTitle()"
        />
      </div>

### Screenshots or Video

<details open>

https://github.com/user-attachments/assets/e893dc38-e0af-4a6a-bc4a-f87a3f6fb329

<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

no

**Comment by danagbemava-nc** [comment]
This is not the `flutter_inappwebview` repo. Find the correct repo below. 

https://github.com/pichillilorenzo/flutter_inappwebview/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

Closing from here as this appears to have been filed at the wrong place. 

Thank you
