### ISSUE TITLE
Issue from website page Get Started: Test Drive

### ISSUE THREAD

**Issue by zzj0402** [flutter/flutter#16099]
From URL: https://flutter.io/get-started/test-drive.md
Android Studio direction is not correct. There is no New Dart Project option.

**Comment by zoechi** [comment]
Where did you get the link from? It's broken.

**Comment by zzj0402** [comment]
https://flutter.io/get-started/test-drive/#androidsstudio
I clicked on the top-right corner "File Issue".

**Comment by s-bauer** [comment]
@zzj0402 You have to install the "Dart" and "Flutter" extensions for android IDE to get this menu option

**Comment by zzj0402** [comment]
@s-bauer I missed that. Thank you sir!
