### ISSUE TITLE
Could not find or load main class java.se.ee

### ISSUE THREAD

**Issue by Noah-Huppert** [flutter/flutter#16093]
## Steps to Reproduce

I am attempting to run the Flutter Hello world on my Pixel 2, from my Arch Linux environment.  

Steps:

1. Create a sample Flutter project
    ```
    $ flutter create hello_flutter
    $ cd hello_flutter
    ```
2. Check Flutter Doctor output
    ```
    $ flutter doctor -v
    ```
    [Flutter Doctor Output Gist](https://gist.github.com/Noah-Huppert/4b2f12e54fd2b2bd935c7414ae3be08d#file-flutter-doctor-out)  
3. Run
    ```
    $ flutter run -v
    ```
    [Flutter Run Output Gist](https://gist.github.com/Noah-Huppert/4b2f12e54fd2b2bd935c7414ae3be08d#file-flutter-run-out)

Flutter run will fail with the error:  
```
Could not find or load main class java.se.ee
```

I had a very hard time finding any material online on how to address this issue.  
The only thing I know about the `java.se.ee` package is that I had to add:

```
export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
```

To my terminal profile in order to get Intellij products to launch.  

However when I remove this line no change in Flutter Run behavior occurs.

## Logs
[Flutter Run Log File](https://gist.github.com/Noah-Huppert/4b2f12e54fd2b2bd935c7414ae3be08d#file-flutter_01-log)  

```
$ flutter analyze
[  +22 ms] [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: no upstream configured for branch 'makepkg'
[        ] [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] makepkg
[        ] [/opt/flutter/] git log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
[        ] [/opt/flutter/] git log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[        ] [/opt/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +5 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.2.3-0-g5a58b36e3
[ +312 ms] /opt/flutter/bin/cache/dart-sdk/bin/dartanalyzer --packages /home/noah/Documents/workspace/mobile/hello_flutter/.packages /home/noah/Documents/workspace/mobile/hello_flutter
[  +72 ms] Analyzing /home/noah/Documents/workspace/mobile/hello_flutter...
[+5943 ms] No issues found!
[  +29 ms] Ran in 6.1s
[  +10 ms] "flutter analyze" took 6,325ms.
[  +35 ms] ensureAnalyticsSent: 33ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

## Flutter Doctor

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v0.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.3 at /opt/flutter
    • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK at /opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • Pixel 2 • FA7B41A01320 • android-arm64 • Android 8.1.0 (API 27)
• No issues found!
```

**Comment by zoechi** [comment]
`v0.1.5` is quite old already. Can you try again after `flutter upgrade`?

**Comment by Noah-Huppert** [comment]
I actually have the latest version. It looks like I posted the output from `flutter_01.log` (From ages ago) instead of `flutter_13.log`. One sec let me update the info.

**Comment by Noah-Huppert** [comment]
Ok outputs from the version of Flutter which is actually installed on my system at the moment have been posted. Sorry for the confusion there.

I suspect the error I'm getting has more to do with my Java environment. However `flutter doctor` says everything is ok.

**Comment by zoechi** [comment]
Does `/opt/android-sdk` exist?
I have for example
```
ANDROID_HOME = /usr/local/opt/android-sdk
```

**Comment by Noah-Huppert** [comment]
Yes.  

```
$ ls /opt/android-sdk
add-ons      emulator  licenses    patcher    platform-tools         sources        tools
build-tools  extras    ndk-bundle  platforms  platform-tools.backup  system-images
```

**Comment by Noah-Huppert** [comment]
Just tested the Android SDK by creating a basic Android project and it successfully built and ran on my laptop and mobile device.

[Screenshots](https://photos.app.goo.gl/oQopYXuF6HkyNrB32)

**Comment by jtromo** [comment]
Has this issue been resolved? Running into the same crash:

# Flutter crash report

## command

flutter run

## exception

String: Exit code 1 from: /Users/jamesromo/Development/xxx/xxx/android/gradlew -v:
Error: Could not find or load main class java.se.ee

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:249)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:180)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:162)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:97)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:90)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:84)
<asynchronous suspension>
#6      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:88)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:272)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:401)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#19     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#28     new Future.sync (dart:async/future.dart:224)
#29     CommandRunner.run (package:args/command_runner.dart:109)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1126)
#34     _CustomZone.run (dart:async/zone.dart:1023)
#35     runZoned (dart:async/zone.dart:1501)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:49)
#39     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#40     main (file:///Users/jamesromo/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.3.2 at /Users/jamesromo/Development/flutter
    • Framework revision 44b7e7d3f4 (3 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jamesromo/Library/Android/sdk
    • Android NDK at /Users/jamesromo/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/jamesromo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • IntelliJ at /Users/jamesromo/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • PH 1 • PM1LHMA820703747 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by Noah-Huppert** [comment]
No I did not ever get this resolved. My theory is that the Java
distribution I installed did not include some enterprise Java classes?

I have not had much luck finding any knowledge about the java.se.ee class.

**Comment by jtromo** [comment]
Sounds plausible. I'll try changing my distribution. I thought it might be something to do with my project, but I tried created a fresh sample app and am hitting the same issue.

**Comment by Noah-Huppert** [comment]
Yea I thought the same. Not really sure what to try next.

Keep me updated on anything that you try. Maybe it will give me inspiration.

I was really looking forward to checking out Flutter but this issue left me
unable to do so.

**Comment by alfanhui** [comment]
I had the exact same error. I resolved it by removing an export I put when my Android SDK was not showing up ([from this issue](https://github.com/NativeScript/nativescript-cli/issues/3139)): 
 
`export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'`

I removed this export from my shell profile.

**Comment by Noah-Huppert** [comment]
The fix mentioned by @alfanhui worked. This was something I tried in my initial debugging before posting this issue.

However it looks like I either did something wrong when unsetting this environment variable (Perhaps I didn't set the environment variable to `""` so the value remained) or there was a fix in one of the releases since I had this issue.  

Either way thanks to everyone who helped out. And I hope anyone who runs into this in the future can benefit from the fix as well.

**Comment by florentsorel** [comment]
I have the same problem on Linux Mint 18.3
On Windows it's works.
I have java 10 and flutter v1.2.1 on both OS.

On Linux I have exported the path `export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'` in my `~/.profile` otherwise the command `flutter doctor --android-licenses` doesn't work and ask me to update the sdkmanager.

I tried everything I saw on GitHub but none of them works for me.

**Comment by zoechi** [comment]
@florentsorel This is not Flutter related, only Android SDK-related.
You might be able to find more helpful information if you do not focus on Flutter when searching.

**Comment by zoechi** [comment]
@florentsorel https://github.com/flutter/flutter/issues/16025#issuecomment-468009198 might help

**Comment by alexxsanya** [comment]
> @alfanhui I will try this fix again. However when I tried this initially:
> 
> > The only thing I know about the java.se.ee package is that I had to add:
> > ```
> > export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'`
> > ```
> > 
> > 
> > To my terminal profile in order to get Intellij products to launch.
> > However when I remove this line no change in Flutter Run behavior occurs.
> 
> Thank you regardless of if this fix works for me. Hopefully it will help someone in the future.

Sure, It has

**Comment by z3cko** [comment]
This did the trick for me: 
`unset JAVA_OPTS`

**Comment by deepak1235** [comment]
I ran into `set JAVA_OPTS=` error while `flutter run` in vscode in windows 10..
This fix worked for me:

1. open <YOUR_PROJECT>/android/gradlew.bat
2. add the following line: `set JAVA_OPTS=`
(yes there is nothing after "=")
3. save the file and try using `flutter run` again!

Hope this helps!!

**Comment by alianando** [comment]
worked for me

https://stackoverflow.com/a/55999615/10177438

**Comment by tahadostifam** [comment]
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

im try `sdmanager --help` command with superuser(**sudo**)... its work fine
