### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "../.pub-cache/hosted/pub.dartlang.org/term_glyph-1.0.0".

### ISSUE THREAD

**Issue by myulz** [flutter/flutter#16100]
Hi! I am trying to run the test drive code using android studio but I am getting this error whenever `flutter packages get` is ran:

`Could not find a file named "pubspec.yaml" in "/Users/../.pub-cache/hosted/pub.dartlang.org/term_glyph-1.0.0".
pub get failed (66)`

Just followed all of the directions on the 'Get Started' page, but this is happening when I open/start any project in android studio or try to run it in terminal. I also just successfully set it up on my old laptop a few weeks ago so I'm not sure what I missed.

 flutter doctor -v results:

`[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.3 17D47, locale en-US)
    • Flutter version 0.2.3 at /Users/../flutter
    • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264`

`[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.`

`[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0`

`[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)`

`[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins`

`[✓] Connected devices (1 available)
    • SM J327V • ~~~~~~~~~ • android-arm • Android 7.0 (API 24)`

`! Doctor found issues in 1 category.`

**Comment by danysz** [comment]
me too...

**Comment by wlals822** [comment]
+ 1

**Comment by zoechi** [comment]
Sorry for not responding earlier.
Is this still an issue?

What seems weird is `..` in 

> Flutter version 0.2.3 at /Users/../flutter

**Comment by fusion44** [comment]
Not sure this could be the reason for this particular case, but I had the same error message. I've tried to add [graphql-flutter](https://github.com/zino-app/graphql-flutter) to my project and used their sample app as a guide. The sample app says to add this to the dependencies section:
  graphql_flutter:
    path: ..
But this only makes sense when you directly check out the package source and run from there. I've got the package from pub, so it tried to find the package in the parent folder.

**Comment by zoechi** [comment]
@fusion44 good call, but then it wouldn't report a path `"../.pub-cache/hosted/...`

In @myulz 's case `flutter pub pub cache repair`  might be worth a try.

**Comment by jaikumarcipher** [comment]
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
 help, please..

**Comment by zoechi** [comment]
@jaikumarcipher please create a question on StackOverflow.

**Comment by jayant07** [comment]
I have been trying to run project from the root directory itself and it definitely contains pubspec.yaml file. Still not sure why i am getting this error repeatedly. It's been the case since in migrated the project to androidX. 

ERROR: Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter

Nothing seems to be working and i have probably gone through every issue related. Right now trying running flutter pub cache repair. Not sure if thats gonna work either. Help!!!
