### ISSUE TITLE
showDatePicker widget has small white strip (visual bug)

### ISSUE THREAD

**Issue by zzzev** [flutter/flutter#16115]
## Steps to Reproduce

1. invoke showDatePicker
2. observe 1px-ish wide vertical white line at extreme upper left of dialog

This happens in our app and in the flutter gallery.

![datepickerissue](https://user-images.githubusercontent.com/1498161/38154020-8f623a6e-3424-11e8-8e8c-9584d9d294cc.png)

**Comment by chinmaygarde** [comment]
cc @HansMuller @Hixie

**Comment by HansMuller** [comment]
I can reproduce a version of the problem with the Flutter Gallery on Android, Nexus 5:

![date_picker](https://user-images.githubusercontent.com/1377460/38204852-4d1b056e-3659-11e8-92c4-a00637e3c766.png)

**Comment by Hixie** [comment]
We probably want to change how we build the dialog so that the appbar is over transparency, not over white.

**Comment by Hixie** [comment]
cc @yjbanov who most recently worked on this code.

This should be a relatively easy fix.
