### ISSUE TITLE
Cloud Firestore crash on create new document?

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#16113]
## Steps to Reproduce

I'm 95% sure this *used* to work and then something changed and now a crash happens. Using Flutter-dev branch. 
I'm sure there is smaller version of this bug, but for now:

load our app: https://github.com/emshack/sufficient_goldfish
try to type into one of the text fields (we have a "try to submit to cloud firestore when you are done editing the text").
See the lovely stack trace below. I've tried specifying a specific database document and letting it autogenerate a new one. Either way it crashes... and it used to not do that.

## Logs

the stacktrace of the crash:
D/NetworkSecurityConfig(15253): No Network Security Config specified, using platform default
I/ProviderInstaller(15253): Installed default security provider GmsCore_OpenSSL
E/flutter (15253): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (15253): PlatformException(Error performing updateData, NOT_FOUND: No document to update: projects/sufficientgoldfish/databases/(default)/documents/profiles/-L8sLzI5Ua9cXqRfnxaM, null)
E/flutter (15253): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:544:7)
E/flutter (15253): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
E/flutter (15253): <asynchronous suspension>
E/flutter (15253): #2      DocumentReference.updateData (file:///usr/local/google/home/efortuna/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.3.2/lib/src/document_reference.dart:49:30)
E/flutter (15253): #3      _ProfilePageState._updateProfile (file:///usr/local/google/home/efortuna/googleio/sufficient_goldfish/lib/main.dart:58:14)
E/flutter (15253): <asynchronous suspension>
E/flutter (15253): #4      _ProfilePageState.build.<anonymous closure> (file:///usr/local/google/home/efortuna/googleio/sufficient_goldfish/lib/main.dart:80:15)
E/flutter (15253): #5      EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:397:18)
E/flutter (15253): #6      _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:400:36)
E/flutter (15253): <asynchronous suspension>
E/flutter (15253): #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:201:55)
E/flutter (15253): <asynchronous suspension>
E/flutter (15253): #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:174:54)
E/flutter (15253): #9      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
E/flutter (15253): <asynchronous suspension>
E/flutter (15253): #10     _invoke3 (dart:ui/hooks.dart:162:13)
E/flutter (15253): #11     _dispatchPlatformMessage (dart:ui/hooks.dart:75:5)

## Flutter Doctor

[✓] Flutter (Channel dev, v0.2.6, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.6 at /usr/local/google/home/efortuna/googleio/flutter
    • Framework revision 1d067220da (16 hours ago), 2018-03-29 22:14:04 -0700
    • Engine revision 9af82c5a1a
    • Dart version 2.0.0-dev.43.0.flutter-e305117519

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/efortuna/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-3.0
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700

[✓] Connected devices (2 available)
    • Nexus 5X                  • 00b316142e9555f5 • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 8.0.0 (API 26) (emulator)

**Comment by Ethras** [comment]
From a quick look at your code and logs, seems to me like you're trying to update a document before creating it in the first place

**Comment by efortuna** [comment]
user error of using updateData instead of setData(SetOptions.merge).

**Comment by kroikie** [comment]
@efortuna

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/872. Any further collaboration will be done there.
