### ISSUE TITLE
AOT VM on Fuchsia contains the VM and Isolate snapshots.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#16120]
AOT mode on Fuchsia takes the VM/Isolate snapshot data and instructions from the libapp.so of the first application loaded into the process. Consequently, the snapshots are unnecessarily present in the executable. This adds to the size of the executable and build times.

**Comment by chinmaygarde** [comment]
cc @tvolkert

**Comment by zanderso** [comment]
cc @rmacnak-google

**Comment by tvolkert** [comment]
Outdated - closing
