### ISSUE TITLE
Example documentation for fetching data doesn't work 

### ISSUE THREAD

**Issue by mrbm** [flutter/flutter#16131]
## Steps to Reproduce
Go here:
https://flutter.io/cookbook/networking/fetch-data/

This line in the example:   

final json = json.decode(response.body);

Not working.

Thoughts on making this example work?

**Comment by mrbm** [comment]
@xqwzts spotted the issue and solutio...so please fix

```
  final json = json.decode(response.body);
  return new Post.fromJson(json);
```

Should be:

```
  final _json = json.decode(response.body);
  return new Post.fromJson(_json);
```

**Comment by brianegan** [comment]
Thanks for the report! We've got a fix up in PR form, should be up soon.

**Comment by brianegan** [comment]
Fixed
