### ISSUE TITLE
Install script uses absolute path for shebangs

### ISSUE THREAD

**Issue by OhadRau** [flutter/flutter#16130]
Hi all,

I am attempting to install Flutter on NixOS. As part of NixOS's design, the path to `bash` is not located in `/bin`. However, some of the scripts included in the installation process make the assumption that `bash` will always be located in `bin`, which is not the case for NixOS and possibly some other Linux distros. This is a relatively easy fix (just replace with `#!/usr/bin/env bash` in https://github.com/flutter/flutter/blob/master/bin/flutter and https://github.com/flutter/flutter/blob/master/bin/internal/update_dart_sdk.sh). There are some other files that use an absolute path to `bash` but I don't think any of them are needed to install Flutter.

I can make a PR with this fix (and potentially any other changes that will fix the installation process on NixOS) in a little while.

**Comment by chinmaygarde** [comment]
Patches for this will be highly appreciated!
