### ISSUE TITLE
Sliders feedback

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1613]
- [x] The slider thumbs (the draggable part) feel like they might be a bit small, especially in the disabled state
- [x] The disabled thumb needs a "stroke" of background color surrounding it to make it stand out from the slider line (you should be able to see this in the spec images)
- [x] The thumb should enlarge when it's being dragged

**Comment by abarth** [comment]
![sliders3](https://cloud.githubusercontent.com/assets/112007/14154950/4da1df34-f674-11e5-937e-7d7644d83bf8.png)

**Comment by abarth** [comment]
![slider-large-compare](https://cloud.githubusercontent.com/assets/112007/14155841/5c4f75d8-f678-11e5-827d-bc7c50b694ea.png)

**Comment by abarth** [comment]
Above, blue is from the spec.  Purpose is from Flutter.
