### ISSUE TITLE
Selection controls feedback

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1614]
- [x] I believe the animation for checkboxes generally transitions to the checked color (yellow, in this case) before filling the square/check mark. Feels a bit strange to have it fill with grey and then turn yellow at the very end.
- [x] The touch targets, at least on the checkboxes, feel a bit small (could just be mind playing tricks, though)

**Comment by abarth** [comment]
> The touch targets, at least on the checkboxes, feel a bit small

The touch target is 48x48 pixels.

**Comment by abarth** [comment]
With https://github.com/flutter/flutter/pull/1882 we will complete the color transition 25% of the way through the animation, which is well before the check starts to grow (at 50% of the way through the animation).

**Comment by abarth** [comment]
With regard to touch target size, I'm happy to make it whatever size it's supposed to be.  Currently it's 48x48.  Does the spec say anything about how big the targets should be?
