### ISSUE TITLE
Issues with BackdropFilter

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#16148]
Continuation of [https://github.com/flutter/flutter/issues/16144](https://github.com/flutter/flutter/issues/16144)

## Steps to Reproduce

I've encountered couple of issues while using BackdropFilter 
- BackdropFilter doesn't match its child's border radius
Ex. Backdrop filter doesn't have round borders If we have Container with borderRadius
```dart
decoration: new BoxDecoration(
    color: const Color.fromRGBO(0, 0, 0, 0.5),
    borderRadius: new BorderRadius.all(const Radius.circular(8.0)),
)
```

- BackdropFilter behaves strange when its child has shadows
Ex. Backdrop filter is larger then its child if we have Container with shadow even tho shadows have 0 offset
```dart
decoration: new BoxDecoration(
    color: const Color.fromRGBO(0, 0, 0, 0.5),
    boxShadow: [
                  new BoxShadow(
                      offset: new Offset(0.0, 0.0),
                      color: const Color.fromRGBO(0, 0, 0, 0.42),
                      blurRadius: 4.0
                  ),
                ],
)
```
![filter when there are shadows](https://user-images.githubusercontent.com/6430214/38195199-92f3b766-367c-11e8-951e-09985c718809.png)

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.2.4-pre.64, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
[√] Connected devices (1 available)

• No issues found!
Process finished with exit code 0
```

**Comment by zoechi** [comment]
Sorry for not coming back to you earlier.
A lot has changed. Is this still an issue in recent Flutter versions?

**Comment by iptton** [comment]
any workaround to solved this problem ?

**Comment by adriancmurray** [comment]
@iptton what version are you running? This hasn't been an issue for awhile. As long as you're using a pattern such as: ClipRRect -> BackgroundFilter -> Container -> ...Children...

**Comment by iptton** [comment]
thanks! @adriancmurray . using ClipRRect solved my problem.  the key point is ClipRRect.
this issue should be closed I think 👍 
----
And another question : why using BackDropFilter in floatingActionButton cannot blur body ?
We can only blur the content at same stack or at same container ?

**Comment by TahaTesser** [comment]
Hi @fralways 
A lot has changed since `Flutter (Channel master, v0.2.4-pre.64,`
If you're still experiencing this issue. Please create a new issue and provide necessary details 
Thank you

**Comment by fluttercorner** [comment]
[How To Create Rounded Corners Image in Flutter](https://fluttercorner.com/how-to-create-rounded-corners-image-in-flutter/)
