### ISSUE TITLE
Chinese characters can not be bold. [i18n, font]

### ISSUE THREAD

**Issue by korbin-w** [flutter/flutter#16149]
## Steps to Reproduce

1, Sample code:
            new Text("bold: 你好你好*55", style: new TextStyle(fontSize: 25.0, fontWeight: FontWeight.bold,)),
            new Text("normal: 你好你好*55", style: new TextStyle(fontSize: 25.0, fontWeight: FontWeight.normal,)),
2, Got:
![image](https://user-images.githubusercontent.com/454020/38195472-2fee9580-36b0-11e8-89d7-f5ee5c049de3.png)

Problem:
The Chinese characters in the first line are not bold.

## Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.12.6 16G1212, locale zh-Hans-HK)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by eseidelGoogle** [comment]
Maybe @jason-simmons could take a look?

**Comment by cbracken** [comment]
This is likely also an issue across all CJK fonts, which often implement bold by shipping weight-based variants like W4 for regular and W8 for bold.
