### ISSUE TITLE
Could you add Vietnam support material_localizations.dart

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#16146]
Hi , Flutter team
Just like the https://github.com/flutter/flutter/issues/15192, n ow our app need to support Vietnam, but I found there is no material_vn.arb file in the flutter_localizations folder ,

By the way , could you addVietnam in the flutter/packages/flutter_localizations/lib/src/material_localizations.dart ?

Thank you very much.

**Comment by HansMuller** [comment]
I have submitted a request to have Vietnamese added to the list of Flutter's supported locales. The language code is 'vi' not 'vn' though. I'm not aware of a locale whose language code is 'vn'.

**Comment by realcarlos** [comment]
Thank you @HansMuller , yeah it should be 'vi' .
