### ISSUE TITLE
Website build broken due to deprecated constants

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#16153]
The website build is broken due to deprecated constants. This was fixed recently, but a PR was merged (https://github.com/flutter/website/pull/839) since. The PR branch passed Travis because it built before the changed landed (and the website doesn't get rebuilt when flutter updates, even though it's dependant on it).

Travis log:

https://travis-ci.org/flutter/website/builds/361053013

**Comment by DanTup** [comment]
I was going to have a look at this, but I couldn't figure out how to run the analysis locally. I tried running some chunks of the `travis.sh` script, but it fails like this:

```text
Running "flutter packages get" in animate1...                0.5s
Run flutter analyze on _includes/code/animation/animate1

ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/dantup/Dev/Google/flutter-website/ios/Runner.xcodeproj -target Runner -showBuildSettings
```

Indeed that `ios` folder does not exist, but I can't figure out where it was supposed to come from or how it'd be on Travis either.

(cc @filiph)

**Comment by goderbauer** [comment]
https://github.com/flutter/website/pull/922 should fix it... again.

**Comment by DanTup** [comment]
Great, it's green now :-)

Is there a way I can run those analysis scripts locally? I can't figure out why I get the error above but it works on Travis?

**Comment by DanTup** [comment]
Yeah, I saw the errors there but wanted confirmation of the fix before pushing :D I'll open an issue, ta!

**Comment by DanTup** [comment]
(opened https://github.com/flutter/flutter/issues/16156)
