### ISSUE TITLE
Thai can not be displayed correctly with the latest version flutter (master)

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#16151]
It works well in last week.

![img_7326](https://user-images.githubusercontent.com/13853/38196883-f1183638-36b7-11e8-90be-93333e05a34a.jpg)

Does any text lib change?

**Comment by HansMuller** [comment]
@jason-simmons

**Comment by realcarlos** [comment]
How about this issue?  @jason-simmons , we are planning to release an app in Thailand ,it blocks us ,could you help ? Thank you!

**Comment by jason-simmons** [comment]
What version of Flutter are you using, and what device are you deploying to?

Can you provide a code sample that reproduces the problem?

**Comment by realcarlos** [comment]
Yes , it is easy to reproduce .

<img width="625" alt="2018-04-10 12 08 43" src="https://user-images.githubusercontent.com/13853/38537321-1b6fe5ec-3cb8-11e8-909f-f64b54dca9fa.png">
<img width="393" alt="2018-04-10 12 08 21" src="https://user-images.githubusercontent.com/13853/38537322-1e252f04-3cb8-11e8-8f7e-64d253a676e2.png">


I just added some Thai text to the Stock sample ,it display wrong characer.
