### ISSUE TITLE
Website repository doesn't analyze intended dart code section

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#16158]
https://github.com/flutter/website/blob/master/tool/extract.dart doesn't analyze dart code sections which are intended, e.g. if you have the following in a markdown file, it will not be analyzed:

```markdown
* Some important bullet point illustrated with code:
  ```dart
  print("Hello World")
  ``
```

/cc @devoncarew

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1849](https://github.com/flutter/website/issues/1849) via [**ZenHub**](https://www.zenhub.com/)
