### ISSUE TITLE
Flutter doctor - "NoSuchMethodError: The method 'run' was called on null."

### ISSUE THREAD

**Issue by klilley** [flutter/flutter#16160]
'flutter doctor' worked correctly it suggested I update so then
I ran 'flutter upgrade' as well as updating my macos and xcode. Then ran xcode and which installed additional updates.

Karls-MBP-2:~ karllilley$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.2.3 at /Users/karllilley/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

 
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 11ccd05f01dbb253)
Unhandled exception:
NoSuchMethodError: The method 'run' was called on null.
Receiver: null
Tried calling: run(Instance(length:2) of '_GrowableList', environment: null, workingDirectory: null)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      runAsync (package:flutter_tools/src/base/process.dart:227)
<asynchronous suspension>
#2      IOSWorkflow.macDevMode (package:flutter_tools/src/ios/ios_workflow.dart:45)
<asynchronous suspension>
#3      IOSWorkflow.validate (package:flutter_tools/src/ios/ios_workflow.dart:90)
<asynchronous suspension>
#4      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///Users/karllilley/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

**Comment by klilley** [comment]
Duplicate of https://github.com/flutter/flutter/issues/15943

**Comment by klilley** [comment]
I downloaded the alpha build and that seemed to work instead.

git clone -b alpha https://github.com/flutter/flutter.git

**Comment by rongshuizhou** [comment]
I encountered the same problem in version 0.2.3, how did you solve it?Because my projects are based on 0.2.3。

**Comment by zoechi** [comment]
@rongshuizhou 0.2.3 is quite old. Any reason why you are not upgrading to a newer Flutter version?

**Comment by rongshuizhou** [comment]
The project I am working on has been using 0.2.3, there is no official upgrade yet, and I plan to upgrade after releasing a version. But this problem I solved, is the problem of Android sdk, I reinstalled it again.

**Comment by AngeloGiuseppe** [comment]
I hope this can help , I experienced this error when I edited the property `package` in the AndroidManifest.xml file 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.project01">
```

Its seems that when you change that part you get the error, so just return it to its original name in the meantime
