### ISSUE TITLE
Unable to get packages for flutter_gallery example

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#16162]
Running `flutter packages get` in examples/flutter_gallery from master, I get the following error:

```
Package connectivity has no versions that match 0.3.0 derived from:
- flutter_gallery depends on version 0.3.0
pub get failed (1)
```

I can see that connectivity 0.3.0 is available on pub: https://pub.dartlang.org/packages/connectivity

I've tried running the following commands to clean the pub cache and retrieve the correct dependency:

* `flutter packages upgrade`
* removing the build dir manually
* `flutter clean`
* removing ~/.pub-cache manually
* `flutter packages pub cache repair`
* `flutter update-packages`
   * I've attached the output of that below

`flutter update-packages` output:
```
Running "flutter packages get" in complex_layout...          5.7s
Running "flutter packages get" in microbenchmarks...         5.4s
Running "flutter packages get" in devicelab...               5.5s
Running "flutter packages get" in automated_tests...         4.2s
Running "flutter packages get" in manual_tests...            4.3s
Running "flutter packages get" in vitool...                  4.4s
Running "flutter packages get" in tools...                   4.6s
Running "flutter packages get" in bots...                    4.4s
Running "flutter packages get" in platform_interaction...    4.7s
Running "flutter packages get" in external_ui...             4.5s
Running "flutter packages get" in ui...                      4.9s
Running "flutter packages get" in channels...                4.6s
Running "flutter packages get" in flavors...                 4.6s
Running "flutter packages get" in platform_view...           0.7s
Running "flutter packages get" in layers...                  4.2s
Running "flutter packages get" in catalog...                 4.7s
Running "flutter packages get" in platform_channel...        4.5s
Running "flutter packages get" in flutter_gallery...             
Package connectivity has no versions that match 0.3.0 derived from:
- flutter_gallery depends on version 0.3.0
pub get failed (1)
```

Are there any things I could try that I've missed?

**Comment by DaveShuckerow** [comment]
Flutter doctor:

[✓] Flutter (Channel unknown, v0.0.22-pre.523, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.2)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
[✓] VS Code (version 1.21.1)
[✓] Connected devices (1 available)

**Comment by DaveShuckerow** [comment]
Output from `flutter packages pub get --verbosity=solver`:

```
Resolving dependencies...
Solving dependencies:
- collection 1.14.6 from hosted (collection)
- typed_data 1.1.5 from hosted (typed_data)
- meta 1.1.2 from hosted (meta)
- device_info 0.2.0 from hosted (device_info)
- charcode 1.1.1 from hosted (charcode)
- url_launcher 3.0.0 from hosted (url_launcher)
- video_player 0.3.0 from hosted (video_player)
- connectivity 0.3.0 from hosted (connectivity)
- intl 0.15.4 from hosted (intl)
- flutter any from sdk (flutter)
- path 1.5.1 from hosted (path)
- flutter_gallery_assets any from git ({url: https://flutter.googlesource.com/gallery-assets, ref: d318485f208376e06d7e330d9f191141d14722b8, path: .})
- cupertino_icons 0.1.1 from hosted (cupertino_icons)
- vector_math 2.0.5 from hosted (vector_math)
- source_span 1.4.0 from hosted (source_span)
- string_scanner 1.0.2 from hosted (string_scanner)
* start at root
| * select pub itself
| | * select args 1.4.1 from hosted
| | | * select async 2.0.6 from hosted
| | | | * select barback 0.15.2+15 from hosted
| | | | | * select boolean_selector 1.0.3 from hosted
| | | | | | * select charcode 1.1.1 from hosted
| | | | | | | * select cli_util 0.1.2+1 from hosted
| | | | | | | | version 1.14.9 of collection doesn't match 1.14.6:
| | | | | | | |   flutter_gallery 0.0.0 (root) -> collection 1.14.6 from hosted (collection)
| | | | | | | |   async 2.0.6 from hosted -> collection ^1.5.0 from hosted (collection)
| | | | | | | |   barback 0.15.2+15 from hosted -> collection ^1.5.0 from hosted (collection)
| | | | | | | |   boolean_selector 1.0.3 from hosted -> collection ^1.5.0 from hosted (collection)
| | | | | | | | version 1.14.7 of collection doesn't match 1.14.6:
| | | | | | | |   flutter_gallery 0.0.0 (root) -> collection 1.14.6 from hosted (collection)
| | | | | | | |   async 2.0.6 from hosted -> collection ^1.5.0 from hosted (collection)
| | | | | | | |   barback 0.15.2+15 from hosted -> collection ^1.5.0 from hosted (collection)
| | | | | | | |   boolean_selector 1.0.3 from hosted -> collection ^1.5.0 from hosted (collection)
| | | | | | | | * select collection 1.14.6 from hosted
| | | | | | | | | version 0.2.1 of connectivity doesn't match 0.3.0:
| | | | | | | | |   flutter_gallery 0.0.0 (root) -> connectivity 0.3.0 from hosted (connectivity)
| | | | | | | | | version 0.2.0 of connectivity doesn't match 0.3.0:
| | | | | | | | |   flutter_gallery 0.0.0 (root) -> connectivity 0.3.0 from hosted (connectivity)
| | | | | | | | | version 0.1.1 of connectivity doesn't match 0.3.0:
| | | | | | | | |   flutter_gallery 0.0.0 (root) -> connectivity 0.3.0 from hosted (connectivity)
| | | | | | | | | version 0.1.0 of connectivity doesn't match 0.3.0:
| | | | | | | | |   flutter_gallery 0.0.0 (root) -> connectivity 0.3.0 from hosted (connectivity)
| | | | | | | | | version 0.0.1+1 of connectivity doesn't match 0.3.0:
| | | | | | | | |   flutter_gallery 0.0.0 (root) -> connectivity 0.3.0 from hosted (connectivity)
| | | | | | | | | version 0.0.1 of connectivity doesn't match 0.3.0:
| | | | | | | | |   flutter_gallery 0.0.0 (root) -> connectivity 0.3.0 from hosted (connectivity)
BacktrackingSolver took 0:00:04.905841 seconds.
- Tried 1 solutions
- Requested 62 version lists
- Looked up 8 cached version lists

Package connectivity has no versions that match 0.3.0 derived from:
- flutter_gallery depends on version 0.3.0
pub finished with exit code 1

```

**Comment by DaveShuckerow** [comment]
The cause of this was my git branch wasn't properly tracking master, and pulling the latest code was not updating the version tags locally.  

This resulted in the flutter version shown (0.0.22) not matching the current version, which broke against the constraints in the connectivity plugin's version solver.

**Comment by Sun3** [comment]
I just download from git and I receive the same error as you did...  any thoughts?

Thanks.

**Comment by hallywang** [comment]
I just download from git and I receive the same error as you did...   +1

**Comment by DaveShuckerow** [comment]
How did you both download Flutter from git?

**Comment by zoechi** [comment]
@DaveShuckerow https://flutter.io/get-started/install/

**Comment by DaveShuckerow** [comment]
@InMatrix 
I editted my above comment to explain what I did to fix.

To pull back your own changes from remotely, you can do this:

```bash
git branch -d my-branch
git checkout -b my-branch upstream/master
git pull origin my-branch
```

@Sun3 @hallywang @zoechi : 
I opened #16283 to discuss the problem that you're having installing Flutter from git.  Each of you, Please comment on that issue with the following:

```
## Logs

Run your application with `flutter run` and attach all the log output.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```

**Comment by Sun3** [comment]
I downloaded it from Git as a Zip file. Then unzipped, opened the gallery folder and did a flutter get, the flutter upgrade.

No go.

**Comment by Sun3** [comment]
Works fine with the Beta 2 Update.

**Comment by hallywang** [comment]
## Logs

Running "flutter packages get" in flutter_gallery...
Package file has no versions that match 3.0.0 derived from:
- flutter_driver 0.0.0 depends on version 3.0.0
- flutter_gallery depends on version 2.3.7
pub get failed (1)

## Flutter Doctor
flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.2.8 at /apps/flutter
    • Framework revision b397406561 (8 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.19.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Haili的 iPhone • xxxxxxx • ios • iOS 11.3

**Comment by hallywang** [comment]
Works fine after delete these lines:
  ```
flutter_test:
     sdk: flutter
  flutter_driver:
    sdk: flutter
```
from the file pubspec.yaml
