### ISSUE TITLE
Widget: TabBar labelStyling buggy

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#16169]
## Steps to Reproduce

Using a `TabBar` for the bottom of a `AppBar` and trying to set the style for the "selected" tab to be bold text, and the "unselected" tabs to be normal text doesn't seem to work.

Here's what it looks like when I set labelStyle to bold and unselectedLabelStyle to normal:
![screen shot 2018-04-02 at 10 23 27 pm](https://user-images.githubusercontent.com/7272343/38225779-84959854-36c4-11e8-9fcf-713dc649a4c4.png)

As you can see from the shot, "Recommended" and "Articles" is also bold, even though they are not selected.

This is the code I've used:

```
TextStyle activeTabLabelStyle = new TextStyle(fontSize: 15.0, fontWeight: FontWeight.bold);
TextStyle tabLabelStyle = new TextStyle(fontSize: 15.0, fontWeight: FontWeight.normal);


new TabBar(
            controller: _controller,
            indicatorColor: CoreTheme.MainColor,
            indicatorWeight: 1.0,
            labelColor: CoreTheme.MainColor,
            labelStyle: activeTabLabelStyle,
            unselectedLabelStyle: tabLabelStyle,
            unselectedLabelColor: Colors.black,
            isScrollable: true,
            tabs: [
              new Tab(text: "Latest"),
              new Tab(text: "Recommended"),
              new Tab(text: "News"),
              new Tab(text: "Articles"),
              new Tab(text: "Blogs")
            ],
          )
```

**Comment by realcarlos** [comment]
yes, I met same issue ,font is strange
