### ISSUE TITLE
Animated page selector widget

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1616]
Check out this movie of how the dots animate: [demo](https://storage.googleapis.com/spec-prod-media/foundation/0B7C_rrbeaTQOaHZ5a0dycVVDblU/pagination.dots-white.mp4)

**Comment by Hixie** [comment]
We should implement this as a Scrollbar-style widget that just watches scroll events, once we have pageable.

**Comment by Hixie** [comment]
@sethladd The movie is gone.
@HansMuller Is this one of the widgets that is one your shortlist to update?

**Comment by khalithartmann** [comment]
Hello you awesome people!
I just created a Let's Flutter Berlin group on Facebook to bring flutter developers in Berlin together to discuss problems, share ideas and create beautiful things together. If you live in Berlin, it would be awesome if you could join the group 😊! If you don't live in Berlin, feel free to join too! Im grateful for each and every supporter.  

Let's Flutter Berlin: https://www.facebook.com/groups/276520973054067/about/
Sorry for spamming.

**Comment by TahaTesser** [comment]
Due to video link not working and no response to above comment
Closing this issue as non-actionable
if you disagree please write in the comments and I will reopen it 
Thank you
