### ISSUE TITLE
Improve error messages when attempting to restart in profile(/release?) mode

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#16175]
The message that comes back if you try to restart in profile mode is just "unsupported":

```text
[08:47:34]: ==> [{"id":"6","method":"app.restart","params":{"appId":"47791932-57cb-4460-908e-1ec544de2e12","fullRestart":false,"pause":true}}]
[08:47:34]: <== [{"id":"6","error":"unsupported"}]
```

In Dart Code we route these errors back to the debug console so it looks like this:

![screen shot 2018-04-03 at 08 50 10](https://user-images.githubusercontent.com/1078012/38236438-09bc9bc0-371c-11e8-9db7-1dcc975eb03c.png)

While I could maintain a mapping of errors to friendlier display text, I think it'd be better if the error was just a bit more descriptive. I don't know for sure, but I think it's just this string here:

https://github.com/flutter/flutter/blob/f8998091c858988240ca0363cbf6af97e54db735/packages/flutter_tools/lib/src/resident_runner.dart#L469

**Comment by zoechi** [comment]
In IntelliJ when I modify the run configuration and add `Additional arguments: --profile --no-track-widget-creation`

and click hot-reload in the debug window, I get

![image](https://user-images.githubusercontent.com/405837/51329967-da279100-1a76-11e9-8e5d-1b655b52c23c.png)

**Comment by DanTup** [comment]
I've opened a PR to tweak this text (#27186) but also prefixed it in Dart Code (https://github.com/Dart-Code/Dart-Code/commit/c1483ff5a8821e5d0ebb86489cb6559bde7fd5a9).
