### ISSUE TITLE
Tabs feedback

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1617]
- [x] The tab indicator is meant to feel a bit less static. Polymer's tab component does a decent job of illustrating it: https://elements.polymer-project.org/elements/paper-tabs?view=demo:demo/index.html&active=paper-tabs. Basically, the head of the indicator gets "pulled" to the new position, and the tail lags behind a little
- [x] Tab titles should be all caps

**Comment by eseidelGoogle** [comment]
It looks like this continues in https://github.com/flutter/flutter/issues/2653.

**Comment by mpcomplete** [comment]
Fixed with https://github.com/flutter/flutter/commit/ca8dbe902a5cc659f8304ad88c408d7fa6a40e3e
