### ISSUE TITLE
firebase_storage plugin's channel name should match the other Flutterfire plugins

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#16171]
Right now it's "firebase_storage" instead of "plugins.flutter.io/firebase_storage"

I think we should also rename `FirebaseStorage._channel` to `FirebaseStorage.channel` and mark it `@visibleForTesting` so it can only be used in tests, like we do for [firebase_auth](https://github.com/flutter/plugins/blob/master/packages/firebase_auth/lib/firebase_auth.dart#L89). Then we wouldn't need to duplicate the channel name in tests.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/870. Any further collaboration will be done there.
