### ISSUE TITLE
Issue from website page Get Started: Test Drive

### ISSUE THREAD

**Issue by jotisa** [flutter/flutter#16177]
From URL: https://flutter.io/get-started/test-drive/
In Android Studio 3.1 for Linux it also asks you to fill out the Flutter SDK path and there is a page next.  See Attachment pic for package name and if you would like Kotlin and S
![pantallazo-2018-04-03 04-09-28_flutter_](https://user-images.githubusercontent.com/22183762/38240456-42773e1a-36f5-11e8-8f97-59e4238290bb.png)
wift support

**Comment by timsneath** [comment]
Hi @jotisa -- thanks for filing the issue. Were you expecting to see something different here? At this point, you should be pressing the "Finish" button as described in step 4 of the "Create new app" section. Let us know what you were expecting.
