### ISSUE TITLE
From past 2 days, i am not able to run my project through 'flutter run ' command . Please help! After syncing file and Xcode build, it losses the connection to device. Please help. 

### ISSUE THREAD

**Issue by Pushkar98** [flutter/flutter#16173]
Xcode build done                                     16.7s
Syncing files to device iPhone X...
Lost connection to device.

**Comment by zoechi** [comment]
Trying `dev` channel might be worth a try.

**Comment by tvolkert** [comment]
> Trying dev channel might be worth a try.

+1.  Can you try switching to the `dev` channel via: `flutter channel dev` -- then trying again?

Also, if that doesn't work, please attach the full logs from `flutter run -v`

**Comment by Hixie** [comment]
@Pushkar98 
Please let us know if this still occurs for you. For now I will close this issue since we don't have enough information to act on. If you do still see this please file a new bug with as much information as you can provide. Thanks!

**Comment by zoechi** [comment]
@Abosrie this issue is long closed. Please create a new issue with the information requested by the issue template.

**Comment by JuanmaMenendez** [comment]
For me, the issue was a geolocation permission issue, pleas read https://stackoverflow.com/a/63119836/7336232
