### ISSUE TITLE
FlutterFire/firebase-dart abstraction

### ISSUE THREAD

**Issue by davidmarne** [flutter/flutter#16186]
It would be great if FlutterFire could collaborate with firebase-dart to agree upon common interfaces, in which both packages implement.

I'm working on a project where I am building a web app and a flutter app, and I am trying to abstract the common business logic into another library for both apps to consume. As it stands right now I have to implement a lot of things twice, once for web and once for flutter, and the logic is almost the exact same each time.

See the companion issue at [firebase-dart](https://github.com/firebase/firebase-dart/issues/170)

**Comment by davidmarne** [comment]
@collinjackson @efortuna thoughts on this?
Can you get the correct labels applied?

**Comment by efortuna** [comment]
OMG YES THIS ISSUE SO MUCH. I have been feeling this pain too.  I'll add some labels and cc some other people.
cc @kevmoo @Janamou

**Comment by kevmoo** [comment]
Zero argument here. Just need to find someone w/ the time and talent to make it happen...

**Comment by efortuna** [comment]
Collin, would you have bandwidth to look into this? @collinjackson

**Comment by simonhull** [comment]
Any updates to this issue?  I too would love to see some sort of abstraction between these two packages.

**Comment by pulyaevskiy** [comment]
I'd like to be in the loop on this one as I'm maintaining [firebase_admin](https://github.com/pulyaevskiy/firebase-admin-interop) and [firebase_functions](https://github.com/pulyaevskiy/firebase-functions-interop) interop packages.

**Comment by efortuna** [comment]
@bparrishMines, might you be able to take a look at this? @collinjackson mentioned you might be a good fit for this.

**Comment by bparrishMines** [comment]
Yea I can. @collinjackson was telling me about this. I will most likely need to talk to him to get his thoughts on the best way to go about doing this. 

I’m assuming we will mainly just need to talk and start coordinating on our code structure.

**Comment by efortuna** [comment]
Great, thanks! A lot of people (including me) will be thrilled!

**Comment by pulyaevskiy** [comment]
Just saw this on dart-misc: https://github.com/apptreesoftware/crossfire

**Comment by bparrishMines** [comment]
cc @kroikie

**Comment by zoechi** [comment]
https://github.com/fluttercommunity/firebase_flutter_sdk is a community effort for a Dart Firebase client implementation.

**Comment by kroikie** [comment]
@davidmarne

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/869. Any further collaboration will be done there.
