### ISSUE TITLE
Potential false positive warnings from hot reload 

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#16195]
## Steps to Reproduce

I was working through the [Write Your First App](https://flutter.io/get-started/codelab/) tutorial. I received warnings that some program elements didn't run when the view was reassembled, but the UI seemed to be updated correctly. 

For example, when I changed my code from [step 2](https://gist.githubusercontent.com/Sfshaza/bb51e3b7df4ebbf3dfd02a4a38db2655/raw/57c25b976ec34d56591cb898a3df0b320e903b99/main.dart) to [step 3](https://gist.githubusercontent.com/Sfshaza/d7f13ddd8888556232476be8578efe40/raw/329c397b97309ce99f834bf70ebb90778baa5cfe/main.dart), I received the following message:

```
Performing hot reload...
Reloaded 1 of 430 libraries in 627ms.

Some program elements were changed during reload but did not run when the view was reassembled;
you may need to restart the app for the changes to have an effect.
  • RandomWordsState.didUpdateWidget (lib/main.dart:28)
  • RandomWordsState._widget= (lib/main.dart:28)
```

In addition to the UI appeared to be fine, I didn't know how relevant RandomWordsState.didUpdateWidget and RandomWordsState._widget were to me, since these two methods were not actually in the code I wrote.

Then, when I changed my code from [step 3](https://gist.githubusercontent.com/Sfshaza/d7f13ddd8888556232476be8578efe40/raw/329c397b97309ce99f834bf70ebb90778baa5cfe/main.dart) to [step 4](https://gist.githubusercontent.com/Sfshaza/d6f9460a04d3a429eb6ac0b0f07da564/raw/34fe240f4122435c871bb737708ee0357741801c/main.dart), I got the following message:

```
Initializing hot reload...
Reloaded 1 of 430 libraries in 915ms.

Some program elements were changed during reload but did not run when the view was reassembled;
you may need to restart the app for the changes to have an effect.
  • RandomWordsState._suggestions (lib/main.dart:22)
  • RandomWordsState._biggerFont (lib/main.dart:24)
```

Again, the UI seemed to be functioning correctly, including the font size, which the message says the relevant code didn't run. 

## Flutter Doctor
```
[✓] Flutter (Channel master, v0.2.9-pre.9, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.9-pre.9 at /Users/taodong/Code/flutter_repos/flutter
    • Framework revision 5e9424419e (35 minutes ago), 2018-04-03 10:35:07 -0700
    • Engine revision 04f3c6557c
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.0

[✓] Connected devices (1 available)
    • iPhone SE • AD00445E-9D4A-454D-892F-1419FF77D3A1 • ios • iOS 11.2 (simulator)

! Doctor found issues in 1 category.
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by InMatrix** [comment]
Cc: @a-siva @devoncarew

**Comment by a-siva** [comment]
This appears to be a Dart 2 issue, the front end seems to have introduced these synthetic functions, fields causing the message to show up. Will discuss with the front end team and figure out how to suppress them

**Comment by a-siva** [comment]
After more investigation I found the following issues
- source finger prints are not implemented in kernel (dart 2) as a result changes to functions/fields or classes are not tracked correctly
- only new classes, functions or fields added will be tracked for changes
- kernel seems to add new synthetic functions 'forwarding-stub' into a class and these need to be skipped over when computing changes.

My conclusion is that we should turn off these hot reload warnings in dart2 until these issues are fixed (raises false positives and misses potential correct situations).

**Comment by a-siva** [comment]
https://github.com/flutter/flutter/pull/16520 turns these unused reload messages off and the IDE will take over the functionality of indicated unused changes in the UI.

**Comment by DanTup** [comment]
As I understand it, these messages are gone and won't return in this form, so I think this issue is not relevant any more.
