### ISSUE TITLE
The setter 'readEventsEnabled=' was called on null.

### ISSUE THREAD

**Issue by keluokeda** [flutter/flutter#16208]
## flutter run --release in flutter demo error.
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/16809185/38287598-1cc16b1e-37fe-11e8-8a90-f22f31a8a2f1.png">

## curl google ok
<img width="759" alt="image" src="https://user-images.githubusercontent.com/16809185/38287657-6664b9b0-37fe-11e8-934c-189e50b3b216.png">

## flutter doctor
<img width="682" alt="image" src="https://user-images.githubusercontent.com/16809185/38287718-b4eae2bc-37fe-11e8-8d5e-78db486b5d18.png">

i am in chain,but net OK,who can help us?

**Comment by zoechi** [comment]
Have you tried the command that is suggested for fixing the "Some Android licenses not accepted"?

**Comment by keluokeda** [comment]
no @zoechi

**Comment by tvolkert** [comment]
Looks like a crash in the `pub` tool.  /cc @munificent can you have a look?

**Comment by munificent** [comment]
@nex3 is the person who probably knows what's going on here.

**Comment by nex3** [comment]
This is an error from `dart:io`; see https://github.com/dart-lang/sdk/issues/31750

**Comment by tvolkert** [comment]
@zanderso can you help?

**Comment by zanderso** [comment]
It looks like we are failing to `throw SocketException.closed()` in a few places where it might be needed. Fixing those places will at least give a less confusing error message, but it won't solve the underlying problem that the socket is closed.

**Comment by keluokeda** [comment]
close http_proxy solve my problem.
# export http_proxy=127.0.0.1:58422
# export https_proxy=127.0.0.1:58422
