### ISSUE TITLE
Create an injectable flutter tool customization mechanism

### ISSUE THREAD

**Issue by xster** [flutter/flutter#16204]
For instance to use a specific code signing scheme. 
Maybe use flutter config for override mapping.

**Comment by tvolkert** [comment]
You want to use `AppContext`:

https://github.com/flutter/flutter/blob/b8629bab8d14b29009f13d108b1f58322ec4f319/packages/flutter_tools/lib/src/base/context.dart#L47

You'd create some abstraction for whatever behavior you want to be swappable, then inject a default implementation of that abstraction here:

https://github.com/flutter/flutter/blob/b8629bab8d14b29009f13d108b1f58322ec4f319/packages/flutter_tools/lib/src/context_runner.dart#L45

Then vendors (or different places in `flutter_tools`) could call `context.run(overrides: ...)` to override the behavior provided by the abstraction.

We do this already for things like `Artifacts` (or `FileSystem` in tests).

**Comment by xster** [comment]
Where would the vendor injection code live? In a different google_flutter_tools repo?

**Comment by tvolkert** [comment]
Closing as a dup of https://github.com/flutter/flutter/issues/25377
