### ISSUE TITLE
Reverse listview scrolls to bottom when tapping on status bar

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#16201]
## Steps to Reproduce

This can be observed in chat example (https://codelabs.developers.google.com/codelabs/flutter/index.html)

When tapping on iOS status bar, the list view scrolls to bottom instead of top

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.2 17C88, locale en-SK)
    • Flutter version 0.2.3 at /Users/Matej/Projects/flutter/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264
```

**Comment by zoechi** [comment]
Sorry for the late response. Is this still an issue in recent Flutter versions?
