### ISSUE TITLE
Feedback property of Draggable widget is not animating .

### ISSUE THREAD

**Issue by sutara-aayush** [flutter/flutter#16212]
![screenshot 14](https://user-images.githubusercontent.com/35102016/38289004-a1b0aa36-37f1-11e8-879f-acac0e6ba281.png)
![screenshot 16](https://user-images.githubusercontent.com/35102016/38289005-a1dedf0a-37f1-11e8-91ff-46bc3e8fcd00.png)
![screenshot 9](https://user-images.githubusercontent.com/35102016/38289015-ad440b5e-37f1-11e8-92d7-676307a99f87.png)
![screenshot 11](https://user-images.githubusercontent.com/35102016/38289016-ad720efa-37f1-11e8-9aaf-5b21b72d9703.png)
![screenshot 13](https://user-images.githubusercontent.com/35102016/38289017-ad9edf70-37f1-11e8-9f55-30756e194b1e.png)
![screenshot 14](https://user-images.githubusercontent.com/35102016/38289018-adcce4ba-37f1-11e8-881c-f0f27eb4a385.png)
![screenshot 15](https://user-images.githubusercontent.com/35102016/38289019-adf9c200-37f1-11e8-8502-eb1c6bf8e3e9.png)
![screenshot 16](https://user-images.githubusercontent.com/35102016/38289020-ae255852-37f1-11e8-8409-166b0d37ba77.png)

As you can see from image above I am changing the height and width of the draggable widget continuously and animating it using `curves.easin` from curved animation but as soon as I am starting dragging it towards the drop target the feedback is not animating instead it is holding the state at which i started the dragging the button. so please help and let me know how to make it animate-able so that the size of feedback continuously keep on changing when under the pointer while dragging.

Code i have written for the game:

```dart
 import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/animation.dart';

class IdentifyGame extends StatefulWidget {
  Function onScore;
  Function onProgress;
  Function onEnd;
  int iteration;

  IdentifyGame({key, this.onScore, this.onProgress, this.onEnd, this.iteration})
      : super(key: key);

  @override
  State<StatefulWidget> createState() => new _IdentifyGameState();
}

class _IdentifyGameState extends State<IdentifyGame> {
  @override
  Widget build(BuildContext context) {
    return new Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          new Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              new DropTarget('c', Colors.lightBlue),
              new DropTarget('a', Colors.red),
              new DropTarget('b', Colors.orange),
            ],
          ),
          new Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              new DragBox('a', Colors.red),
              new DragBox('b', Colors.orange),
              new DragBox('c', Colors.lightBlue),
            ],
          )
        ],
      );
  }
}

class DropTarget extends StatefulWidget {
  final String expectedLabel;
  final Color dropColor;

  DropTarget(this.expectedLabel, this.dropColor);

  @override
  DropTargetState createState() => new DropTargetState();
}

class DropTargetState extends State<DropTarget> {
  String caughtText = '';
  String expectedText = '';
  Color targetColor = Colors.cyan;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    expectedText = widget.expectedLabel;
    targetColor = widget.dropColor;
  }

  @override
  Widget build(BuildContext context) {
    return new DragTarget(
      onAccept: (String text) {
        if (text == expectedText) {
          caughtText = text;
        } else {
          caughtText = '';
        }
      },
      builder: (
        BuildContext context,
        List<dynamic> accepted,
        List<dynamic> rejected,
      ) {
        return new Container(
          width: 120.0,
          height: 120.0,
          decoration: new BoxDecoration(
            // color: accepted.isEmpty ? caughtColor : Colors.grey.shade200,
            color: targetColor,
          ),
          child: new Center(
            child: new Text(
              accepted.isEmpty ? caughtText : '',
            ),
          ),
        );
      },
    );
  }
}

class DragBox extends StatefulWidget {
  final String label;
  final Color itemColor;

  DragBox(this.label, this.itemColor);

  @override
  DragBoxState createState() => new DragBoxState();
}

class DragBoxState extends State<DragBox> with SingleTickerProviderStateMixin {
  
  AnimationController controller;
  Animation<double> animation;


  Color draggableColor;
  String draggableText;

  void toAnimateFunction(){
    animation.addStatusListener(( AnimationStatus status){
      if (status == AnimationStatus.completed){
        controller.reverse();
      } else if (status == AnimationStatus.dismissed){
        controller.forward();
      }
    });
    controller.forward();
  }


  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    controller = new AnimationController(
      duration: const Duration(milliseconds: 400), vsync: this
    );
    animation = new CurvedAnimation(parent: controller, curve: Curves.easeIn)
      ..addListener((){
        setState((){});
      });
    
    toAnimateFunction();

    draggableColor = widget.itemColor;
    draggableText = widget.label;
  }


  

  @override
  void dispose(){
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return new Draggable(
      data: draggableText,
      child: new Container(
        width: animation.value*100.0,
        height: animation.value*100.0,
        color: draggableColor,
        child: new Center(
          child: new Text(
            draggableText,
            style: new TextStyle(
              color: Colors.white,
              decoration: TextDecoration.none,
              fontSize: 20.0,
            ),
          ),
        ),
      ),
      // onDraggableCanceled: (velocity, offset) {
      //   setState(() {
      //     //position = offset;
      //   });
      // },
      feedback: new Container(
        width: animation.value*120.0,
        height: animation.value*120.0,
        color: draggableColor.withOpacity(0.5),
        child: new Center(
          child: new Text(
            draggableText,
            style: new TextStyle(
              color: Colors.white,
              decoration: TextDecoration.none,
              fontSize: 18.0,
            ),
          ),
        ),
      ),
    );
  }
} 
```

Thanks in advance :) ../\..

**Comment by zoechi** [comment]
Can you please edit your issue and wrap the code in ``` to make it readable?

**Comment by sutara-aayush** [comment]
@zoechi Pls have a look, I did what you ask for .

**Comment by zoechi** [comment]
@sutara-aayush I don't think I can help you here, but now with the code properly formatted the chances someone who can having a closer look are much higher ;-)

**Comment by zoechi** [comment]
Is this still an issue? 

The code results in different UI than what your screenshots show.
Can you please make a self-contained complete running example (adding `main() {}`) so that just copy-past allows to run and reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by madisonkwynn** [comment]
Have you used: 
childWhenDragging? 
Feedback is only when you click on it and it will remain "stuck" like you said.

**Comment by boiwantlearncode** [comment]
I face a similar issue but mine is more simplified.

`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  void initState(){
    super.initState();
    SystemChrome.setPreferredOrientations([
        DeviceOrientation.landscapeRight,
        DeviceOrientation.landscapeLeft,
    ]);
  }

  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: DragItem(name: 'Bag'),
        )
      )
    );
  }
}

class DragItem extends StatefulWidget {
  final String name;
  DragItem({Key key, @required this.name}) : super(key: key);

  DragItemState createState() => DragItemState();
}

class DragItemState extends State<DragItem> with SingleTickerProviderStateMixin {
  AnimationController controller;
  Animation<double> animationSize, animationMargin;

  void initState() {
    super.initState();
    controller = AnimationController(duration: Duration(seconds: 1), vsync: this);
    animationSize = Tween<double>(begin: 80.0, end: 70.0).animate(controller)
      ..addListener(() {
        setState(() {

        });
      });
  }

  @override
  Widget build(BuildContext context) {
    return Draggable<String>(
      data: widget.name,
      child: Container(
        color: Colors.blue,
        height: 80.0,
        width: 80.0
      ),
      childWhenDragging: Container(),
      feedback: Container(
        color: Colors.blue,
        height: animationSize.value,
        width: animationSize.value,
        margin: EdgeInsets.only(top: 5.0, left: 5.0)
      ),
    );
  }
}`

The feedback does not animate at all. My plan is to make the item scale down in a smooth, animated manner when it is being dragged.

**Comment by boiwantlearncode** [comment]
I face a similar issue.
The feedback does not animate at all. My plan is to make the item scale down in a smooth, animated manner when it is being dragged. I'm not sure as to whether I can set the begin value to be greater than the end value at the line with the comment "OVER HERE". However, it does not matter as to whether I set the begin value to be less than the end value, the feedback will still not be animated.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  void initState(){
    super.initState();
    SystemChrome.setPreferredOrientations([
        DeviceOrientation.landscapeRight,
        DeviceOrientation.landscapeLeft,
    ]);
  }

  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          child: DragItem(name: 'Bag'),
        )
      )
    );
  }
}

class DragItem extends StatefulWidget {
  final String name;
  DragItem({Key key, @required this.name}) : super(key: key);

  DragItemState createState() => DragItemState();
}

class DragItemState extends State<DragItem> with SingleTickerProviderStateMixin {
  AnimationController controller;
  Animation<double> animationSize, animationMargin;

  void initState() {
    super.initState();
    controller = AnimationController(duration: Duration(seconds: 1), vsync: this);
    animationSize = Tween<double>(begin: 80.0, end: 70.0).animate(controller) // OVER HERE
      ..addListener(() {
        setState(() {

        });
      });
  }

  @override
  Widget build(BuildContext context) {
    return Draggable<String>(
      data: widget.name,
      child: Container(
        color: Colors.blue,
        height: 80.0,
        width: 80.0
      ),
      childWhenDragging: Container(),
      feedback: Container(
        color: Colors.blue,
        height: animationSize.value,
        width: animationSize.value,
        margin: EdgeInsets.only(top: 5.0, left: 5.0)
      ),
    );
  }
}
```
