### ISSUE TITLE
firebase_auth: Clearer docs

### ISSUE THREAD

**Issue by beardo01** [flutter/flutter#16217]
It would pay to be more explicit in the firebase_auth documentation and state exactly which APIs are and are not currently supported.

The about plugin for firebase_auth states "Flutter plugin for Firebase Auth, enabling Android and iOS authentication using passwords, and identity providers like Google, Facebook, and Twitter." when Twitter isn't currently supported.

**Comment by Paul-Todd** [comment]
I would also like an example showing how to check if a user is signed in and an example showing signin with signInWithEmailAndPassword.

I am playing around with this so I might do a PR at somepoint

**Comment by mit-mit** [comment]
cc @collinjackson

**Comment by beardo01** [comment]
Hey @codegrue. Thanks for your contribution.

From what I can tell, the library does in fact support some other providers, namely:
- signInWithEmailAndPassword
- signInWithFacebook
- signInWithGoogle
- signInWithCustomToken

You can find the implementations [here](https://github.com/flutter/plugins/blob/master/packages/firebase_auth/lib/firebase_auth.dart).

The only one that I have currently tested is signInWithGoogle which seems to be working well. I am in the middle of writing an implementation of signInWithTwitter and will submit a PR once I have something working.

Cheers.

**Comment by jmrboosties** [comment]
I've had no problem doing sign in with email and password, it works just like it does on Android.

**Comment by codegrue** [comment]
This is what I came up with to get this to work:

```
final auth = FirebaseAuth.instance;
FirebaseUser currentUser;

Future<Null> _logIn() async {
    if (currentUser == null) {
      final FirebaseUser user = await auth.signInWithEmailAndPassword(
        email: 'user@email.com',
        password: 'somePassword'
      );
      assert(user.email != null);
      assert(!user.isAnonymous);

      analytics.logLogin();

      currentUser = await auth.currentUser();    
    }
}
```

But I can't persist the login between app launches. There is no auth.setPersistence. Is there a better pattern to do this?

**Comment by jmrboosties** [comment]
@codegrue this is my implementation, which does persist:

```

	Future<FirebaseUser> _signIn(String email, String password) async {
		FirebaseUser user = await _auth.signInWithEmailAndPassword(email: email, password: password);
		print('found user:' + user.email);
		return user;
	}
```

similar to what you're doing, as with detecting an existing user on current session, i also just do `_auth.currentUser()`

my best guess is something on the android or ios side might not be right?

**Comment by beardo01** [comment]
Are there any updates around what sign in methods are now supported?

**Comment by cyanglaz** [comment]
Fixed with https://github.com/flutter/plugins/pull/1219. Please feel free to reopen the issue if more documentations or examples are desired.

**Comment by kroikie** [comment]
@beardo01

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/866. Any further collaboration will be done there.
