### ISSUE TITLE
Cupertino fullscreenDialog transition with CupertinoTabBar

### ISSUE THREAD

**Issue by harry7cao** [flutter/flutter#16219]
In iOS, while having a `TabBar` at the bottom, presenting a ViewController modally should cover the `TabBar`. It means in the newly presented ViewController, the `TabBar` is covered, cannot be seen.

Currently in Flutter, however, if we are using `CupertinoTabScaffold` with a `CupertinoTabBar`, modally pushing a new screen using `MaterialPageRoute` won't cover that `TabBar`. It stills stay visible on top the the newly pushed screen.

This should be fixed.

**Comment by moesaeed** [comment]
What about CupertinoFullscreenDialogTransition?

**Comment by zoechi** [comment]
There was a lot of work done for Cupertino widgets. Is this still an issue in `dev` or `master`.
Unfortunately `beta` is currently a bit outdated and probably doesn't yet contain these updates.

**Comment by xster** [comment]
We added some documentation to the `CupertinoTabScaffold` recently. Since tab scaffold makes use of parallel nested navigation inside each tab, to push something on top of everything, be sure to use `Navigator.of(rootNavigator: true)`

**Comment by zoechi** [comment]
And a new beta is out as well \o/

**Comment by wwwdata** [comment]
@xster yes using the `rootNavigator` works. However, Hero transitions do not work in that case. What is the best workaround for that? As far as I have read the code the Hero transitions only work for pushed screens that are downwards in the widgets tree. So the "scanner" for hero widgets does not look upwards, therefore they do not run. Is it planned to adjust this behaviour as well?

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/22084. I'm open to altering that behavior though I'd like to concretely visualize the intended behavior a bit more.
