### ISSUE TITLE
Tutorial Error

### ISSUE THREAD

**Issue by beardo01** [flutter/flutter#16213]
In the fifth code block located at the [Flutter Firebase](https://codelabs.developers.google.com/codelabs/flutter-firebase/#8) tutorial on step eight where it states

`itemBuilder: (_, DataSnapshot snapshot, Animation<double> animation) {` 

it should state

`itemBuilder: (_, DataSnapshot snapshot, Animation<double> animation, index) {` 

or else an error is thrown.

**Comment by beardo01** [comment]
I forgot to mention, this is when using the most up to date plugins. I'd say if I had stuck to the tutorial's plugin versions, I wouldn't have had the same issue.

Perhaps it is worth updating the tutorial to use the most recent plugins and making the above change?

**Comment by Sfshaza** [comment]
The Firebase + Flutter codelab was re-written for Google I/O. This old codelab is now obsolete. Closing.

**Comment by kroikie** [comment]
@beardo01

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/867. Any further collaboration will be done there.
