### ISSUE TITLE
Support Android Studio 3.1

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#16215]
Android Studio 3.1 was released on March 26.

- [ ] Upgrade project templates to use Android Studio Gradle plugin version 3.1.2 and Gradle version 4.4
- [ ] Update documentation on how to open a plugin project for editing in Android Studio (importing the `example/android/build.gradle` file no longer works)

**Comment by mravn-google** [comment]
@mit @Hixie @devoncarew Upgrading the project templates means they stop working in Android Studio 3.0.1. Not upgrading means (at least) users will be met with a "To take advantage of all the latest features (such as Instant Run), improvements and security fixes, we strongly recommend that you update the Android Gradle plugin to version 3.1.0 and Gradle to version 4.4." dialog upon opening the `android/` folder of a Flutter project in Android Studio 3.1.

**Comment by mravn-google** [comment]
It appears that one can open a plugin project by just opening the `example` folder with AS 3.1.
It further appears that after accepting to update the Gradle stuff, the example project (and the plugin) works.

**Comment by zoechi** [comment]
Is there still something to do? Seems to work fine and I am not aware of related bug reports.

**Comment by stevemessick** [comment]
Flutter projects should use Gradle version 4.4. Until they do users are hit with a confusing message (see above). Opening the android folder works fine, as mentioned, and the IDE has support for that.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by devoncarew** [comment]
I think this is addressed.
