### ISSUE TITLE
cannot compile after removing the plugin from dependecies

### ISSUE THREAD

**Issue by matejthetree** [flutter/flutter#16220]
## Steps to Reproduce

Create fresh project.

add 
```
dependencies:
  flutter:
    sdk: flutter
  medcorder_audio:
```
to dependecies.

add import inside main file
```
import 'package:medcorder_audio/medcorder_audio.dart';
```

and instantiate it inside state
```
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  MedcorderAudio audio = new MedcorderAudio();
```

The plugin is old, and you get error on compilation.

So I remove import, usage and entry inside pubscpec.yaml.
I try to compile the app and I get

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk (30.3MB).
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate(12421): onResume setting current activity to this
Syncing files to device Android SDK built for x86...
compiler message: Error: Could not resolve the package 'medcorder_audio' in 'package:medcorder_audio/medcorder_audio.dart'.
```

## Logs
While preparing the logs, I got new bug. I think it is unrelated but here it is
```
matejs-MacBook-Pro:add_remove_dependency matejsimunic$ flutter analyze
Running "flutter packages get" in add_remove_dependency...   0.6s
Analyzing /Users/matejsimunic/Work/dart/add_remove_dependency...
No issues found!
Ran in 6.0s
matejs-MacBook-Pro:add_remove_dependency matejsimunic$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.2s
Resolving dependencies...                                    1.4s
W/zipro   ( 4426): Error opening archive build/app/outputs/apk/app.apk: Invalid file
ERROR: dump failed because no AndroidManifest.xml found

Oops; flutter has exited unexpectedly: "Exit code 1 from: /Users/matejsimunic/Library/Android/sdk/build-tools/27.0.3/aapt dump badging build/app/outputs/apk/app.apk".
Sending crash report to Google.
Crash report sent (report ID: ed78036892500b3d)
Crash report written to /Users/matejsimunic/Work/dart/add_remove_dependency/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```
## Flutter Doctor

matejs-MacBook-Pro:add_remove_dependency matejsimunic$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.3 17D102, locale en-HR)
    • Flutter version 0.2.3 at /Users/matejsimunic/Work/dart/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/matejsimunic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/matejsimunic/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

**Comment by mit-mit** [comment]
cc @mravn-google

**Comment by zoechi** [comment]
Have you tried `flutter clean`?

**Comment by matejthetree** [comment]
@zoechi `flutter clean` did the job. 

my question is should this be automated upon the plugin removal, or at least should there be some console message to try `flutter clean` on dependencies error?

Thank you though.

**Comment by zoechi** [comment]
@matejthetree `flutter clean` should not be necessary, so I think this is a valid bug.
My suggestion was only to get you un-blocked.

**Comment by matejthetree** [comment]
@zoechi thx
