### ISSUE TITLE
Inconsistent timing of animations when swiping between tabs

### ISSUE THREAD

**Issue by rmkl** [flutter/flutter#16230]
## Steps to Reproduce

See sample code on github that illustrates the problem: https://github.com/rmkl/flutter_tab_index_is_changing
Because of the redux libraries used this needs to be run with the **flutter-beta** branch and:
**> flutter run --preview-dart-2**

Set-up: There are three tabs. On the first and second tab there is a floating action button on the page. When navigating to the third tab this button slides off the screen to the right to hide it. When navigating back to the first or second tab the button slides back onto the screen from the right to show it.

Expected behavior: The animation to transition between tabs runs at the same time as the animation to slide the button on/off the screen.

Problem: When swiping between tabs the tab transition animation and the button animation run after each other instead of simultaneously. It seems that when swiping between tabs the `controller.indexIsChanging` event only fires after the tab has fully changed instead of when the swipe starts.

## Notes
Note: When clicking on a tab title to switch between tabs, instead of swiping, the animation works simultaneously as expected.

What is not working: I've tried adding listeners in `/lib/components/home_tabs.dart` to the tab controller, the animation, or the animation status. None of these give the desired result.

Question: Is there a way to reliably detect a swipe to/from tab three **during** the swipe instead of after it has completed? Preferably a way that would also allow to detect the swipe being reversed/cancelled halfway through so that the button animation can be reversed likewise.

## Flutter Doctor
```
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.1.5 at C:\Users\username\flutter
    • Framework revision 3ea4d06340 (6 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.2

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

**Comment by alisson226** [comment]
I'm having the same problem! Is there any way to change the Tabcontroller.index before it concludes the animation?

Changing tabs by clicking on the buttons:
![capture-1](https://user-images.githubusercontent.com/24798322/43105266-b0e6ccbe-8eaa-11e8-846e-b1fbb38a1bc3.gif)

Changing tabs by swiping:
![capture-2](https://user-images.githubusercontent.com/24798322/43105276-b68c2bd2-8eaa-11e8-8916-467c539a69ab.gif)

**Comment by TahaTesser** [comment]
Hi @rmkl 
if you're still experiencing this problem, please create a new issue and provide the information required in
the template.
Thank you

**Comment by Raed-Abada** [comment]
Hi @alisson226 @rmkl 
it's too late but for someone facing the same problem he can find the solution in the link below: 
https://stackoverflow.com/questions/57948157/tabcontroller-does-not-change-when-scrolling-the-screenlike-its-waiting-1-sec
