### ISSUE TITLE
Scroll views do not respond to scroll wheel input

### ISSUE THREAD

**Issue by billy1380** [flutter/flutter#16235]
## Steps to Reproduce
Run any flutter application on Android with a mouse plugged in to the device. Hover over a scrollable view and move the mouse wheel in any direction.

## Observation
The view does not scroll. When compared to a native scroll view on android, flutter scroll views do not respond to scroll wheel events.

### Note
If this is added it would be useful for it to be surfaced it to the embedder so that other platforms can wire this behaviour too.

**Comment by zoechi** [comment]
#21953 or #22762 might fix this

**Comment by stuartmorgan** [comment]
22762 (and the engine change it relied on) provided most of what's needed, but the missing piece is the Android code to send scroll events to the engine. It's plumbed through to the embedding API, and in the macOS shell, but not Android yet.

IIRC @jslavitz had code for that for a previous iteration of the patch; if that still exists it could be updated for the API changes. If not, I would expect that it wouldn't be hard to re-write from scratch for someone familiar with the Android scrolling APIs.

**Comment by stuartmorgan** [comment]
This should now be fixed on Android as well with https://github.com/flutter/engine/pull/8149; closing.
