### ISSUE TITLE
[website] https://flutter.io/networking/ should include an example of a test

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#16233]
https://flutter.io/networking/ includes an example of how to make an `HttpClientRequest` using the `dart:io` package, but doesn't include any example of a test using `HttpOverrides`.  We have some mocks inside of the flutter repo which are really the only examples.

**Comment by adchang** [comment]
An app in the sdk's examples would be super useful as well!

**Comment by Sfshaza** [comment]
@brianegan, would this be a good candidate for the cookbook?

**Comment by brianegan** [comment]
Ah, that's actually another great candidate for the Cookbook, especially when testing Widgets that display Images. 

We've actually got a recipe on how to test this functionality using Mockito + `http` package now, but for Image Widgets overriding the HttpClient can be a great way to avoid making full-on network calls in tests.

**Comment by zoechi** [comment]
Dup of #13792 ?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2263](https://github.com/flutter/website/issues/2263) via [**ZenHub**](https://www.zenhub.com/)
