### ISSUE TITLE
missed_frame_build_budget_count regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16234]
In the last 20 or so days, missed_frame_build_budget_count has regressed a couple of times, to the point where it's now 93 frames vs our baseline of 75 frames.

**Comment by Hixie** [comment]
The initial regression was caused by https://github.com/flutter/flutter/pull/15583, and is being tracked in https://github.com/flutter/flutter/issues/13736, but there have been additional regressions since.

**Comment by sbaranov** [comment]
Benchmark fluctuates wildly between runs, so it's somewhat hard to pinpoint, but all of the following commits have significant effect when reverted separately from each other: 0e8b1, 68c77, 7a6a6.

@gspencergoog FYI

**Comment by tvolkert** [comment]
Hyperlinked commits: 0e8b187, 68c77e3, 7a6a65a

**Comment by Hixie** [comment]
I've split off the two issues into the above issues and will close this one. Thanks everyone for investigating the cause.
