### ISSUE TITLE
Enable C++ SQLite integration

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#16231]
This is a specific case related to https://github.com/flutter/flutter/issues/7053

I would like to see C/C++ to Dart binding exposed in such a way that I could directly use SQLite __without going through the iOS/Android implementations__.  This would allow me to normalize (:wink:) my code so that it didn't have to take into account quirks on Android or iOS, and allow me to potentially take advantage of later versions of SQLite regardless of the OEM provided version installed with the OS. 

I expect that this would also allow me to potentially improve performance for queries that return or require larger amounts of data (I could more easily choose different serialization formats, or devise some platform agnostic way of streaming the data, or choose to handle logic entirely in the C++ side and still have reuse across platforms), but I'm primarily interested in a simpler code base across platforms.

Opening this as a separate issue per recommendation of @eseidelGoogle

**Comment by dnfield** [comment]
(Note - there is a SQLite plugin available that doesn't meet all the wants of this issue, but is better than no SQLite at all if you're looking for that: https://github.com/tekartik/sqflite)

**Comment by escamoteur** [comment]
This goes beyond SQLite IMHO there should be an easy integration for C++ libraries so that e.g. Realm could be used.

**Comment by zimmi** [comment]
One feature that sqflite can't support easily is [encryption](https://github.com/tekartik/sqflite/issues/32). It would be awesome if this was built in / could be added easily by the application developer.

**Comment by dnfield** [comment]
From what I can tell, this is now supported (albeit in preview mode) via dart:ffi.  I'm going to close this.

/cc @sjindel-google or @dcharkes in case I'm wrong on this.

**Comment by dcharkes** [comment]
@dnfield Yes, although we only support JIT and DBC at the moment. AOT compilation is still on our todolist. See progress at https://github.com/dart-lang/sdk/issues/34452 and https://github.com/dart-lang/sdk/projects/13.
