### ISSUE TITLE
SizeTransition.build should use max(sizeFactor.value, 0.0)

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#16247]
## Steps to Reproduce

Step 7 of codelab. https://codelabs.developers.google.com/codelabs/flutter/#6

In the class ChatMessage -> 
Widget build(context) ->
**change**
SizeTransition(sizeFactor: CurvedAnimation(parent: animationController, curve: Curves.easeOut)
**to**
SizeTransition(sizeFactor: CurvedAnimation(parent: animationController, curve: Curves.elasticIn)

**Now try sending a message**

## Logs

When the exception was thrown, this was the stack:
I/flutter (27371): #0      _AssertionError._doThrowNew (dart:core/errors_patch.dart)
I/flutter (27371): #2      new Align (package:flutter/src/widgets/basic.dart)
I/flutter (27371): #3      SizeTransition.build (package:flutter/src/widgets/transitions.dart:291:18)
I/flutter (27371): #4      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:97:48)
I/flutter (27371): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter (27371): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (27371): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27371): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter (27371): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (27371): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (27371): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (27371): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (27371): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (27371): #14     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (27371): #15     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (27371): (elided one frame from class _AssertionError)
I/flutter (27371): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (27371): Another exception was thrown: 'package:flutter/src/widgets/basic.dart': Failed assertion: line 1326 pos 15: 'heightFactor == null || heightFactor >= 0.0': is not true.
I/chatty  (27371): uid=10148(com.andrehaueisen.flutterapp) Thread-4 identical 8 lines
I/flutter (27371): Another exception was thrown: 'package:flutter/src/widgets/basic.dart': Failed assertion: line 1326 pos 15: 'heightFactor == null || heightFactor >= 0.0': is not true.
## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.2.3 at C:\Users\andre\flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\andre\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Nexus 6P • 84B7N16126000743 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
Can you dump the entire message from the first "══════════════════" to the second one?

**Comment by Hixie** [comment]
Oh, I see. The problem is just that `Align` expects `widthFactor` and `heightFactor` to be non-negative, but the elastic curves go negative.

**Comment by Hixie** [comment]
We could just clamp the values to positive numbers in `SizeTransition.build`.
