### ISSUE TITLE
ImageCache should default to a smaller size (1000 images leads to crashes)

### ISSUE THREAD

**Issue by minikin** [flutter/flutter#16241]
## Steps to Reproduce

I developed a small  Flutter application for testing, which fetches 5000 images and displays it with ListView.builder.

During debugging I found that ListView doesn't release memory so memory allocation keeps increasing until app crash. 

1. Clone repo  ```https://github.com/minikin/flutter-vs-react-native.git```
2. Navigate to `flutter` folder.
3. Run `flutter run`
4. Scroll,  scroll ...
5. Open http://127.0.0.1:8104/#/vm open ```heap snapshot``` and check size of ```WidgetsFlutterBinding```
6. Scroll, scroll ...
7. Refresh ```heap snapshot``` check size of ```WidgetsFlutterBinding```
8. Continue scrolling and checking of ``WidgetsFlutterBinding``

At some point application crashes.

The bug is reproducible on real devices also in simulators.

### Expected behavior

`ListView` should release memory for ```cells``` (iOS terminology) which are out of a screen.

----

Trace file from Instruments  (you need to have Xcode 9 to open):
https://drive.google.com/open?id=1yA9mSvuaNEqyapk_Dc2jVSUrJ9tUFFKi>

----

## Logs

```bash
21:36 $ flutter run
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...                                       1.1s
Starting Xcode build...
 ├─Assembling Flutter resources...                    3.6s
 └─Compiling, linking and signing...                  6.9s
Xcode build done                                            12.4s
Syncing files to device iPhone X...                          2.3s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8104/
For a more detailed help message, press "h". To quit, press "q".
```

```bash
22:50 $ flutter analyze
Analyzing /Developer/Minikin/Prototypes/flutter-vs-react-native/flutter...
No issues found!
Ran in 5.1s
```

## Flutter Doctor

```bash
22:50 $ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.8, on Mac OS X 10.13.3 17D102, locale en-DE)
    • Flutter version 0.2.8 at /Users/sasha.prokhorenko/flutter
    • Framework revision b397406561 (2 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/sasha.prokhorenko/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone X • 3086EAAC-5C90-4E39-82A3-ED1C1D27B416 • ios • iOS 11.3 (simulator)

• No issues found!
```

Thank you in advance!

**Comment by eseidelGoogle** [comment]
This was raised to me via twitter.  I believe this is just our ImageCache having no memory backpressure by default, but I don't know.

**Comment by Hixie** [comment]
Seems plausible.

**Comment by minikin** [comment]
@Hixie 

I'm not sure if it's correct approach but I tried to override `imageCache.maximumSize` 
and the issue is resolved now. 

```
import 'package:flutter/widgets.dart';

class CustomImageCache extends WidgetsFlutterBinding {
  @override
  ImageCache createImageCache() {
    this.imageCache.maximumSize = 10;
    return super.createImageCache();
  }
}
```
But please, check another memory trace wich I did with Instruments.
You will see that the first memory leaks check didn't pass.
This situation is reproducible.
https://drive.google.com/open?id=1jit-bAQGlpPzchsNzTfGlmKUgpFR6FVo

**Comment by Hixie** [comment]
If it doesn't replicate when the image cache size is smaller, that means that it's not really a leak so much as we're caching too much. I've reworded the issue to say that it's specifically about making the defaults better. See also https://github.com/flutter/flutter/issues/13606.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/16375.

**Comment by jonahwilliams** [comment]
Could be addressed by the changes in https://github.com/flutter/flutter/pull/17614.
