### ISSUE TITLE
Pod package files not found

### ISSUE THREAD

**Issue by code-rover** [flutter/flutter#16246]
## Steps to Reproduce

First I downloaded the dev branch of flutter because cloud_firestore package was not working with the beta branch.
When I tried to run my app with the new flutter I got errors like:
```
fatal error: file <cloud_firestore/CloudFirestorePlugin.h> not found.
```
This was fixed by changing the target membership type from project to public:

![screen shot 2018-04-05 at 8 06 08 am](https://user-images.githubusercontent.com/26103979/38337350-45bb8de2-38a8-11e8-9c8b-0ec02c1e3d9a.png)

I'm guessing that this is a problem with the way flutter generates pod files.

## Logs

![screen shot 2018-04-05 at 8 11 30 am](https://user-images.githubusercontent.com/26103979/38337532-fd35b966-38a8-11e8-91b1-1d2b8d7cafad.png)

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.2.8, on Mac OS X 10.13.3 17D102, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] Connected devices (2 available)

• No issues found!
```

**Comment by xster** [comment]
When was the project created? Can you copy/paste the Podfile that's present in your project? (may have been a version of the Podfile from previous Flutter releases)

**Comment by mikeashelby** [comment]
I'm having this problem too - did you get anywhere with it?

Here's my podfile:

`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runner

end

pod 'Firebase/Core'
`

**Comment by zoechi** [comment]
@mikeashelby can you please try `pod update` in `ios/`?

**Comment by GraceWayDCDevelopment** [comment]
I'm having the same problem.  It started when I added Firestore to my project.
**Error**:
.... ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'cloud_firestore/CloudFirestorePlugin.h' file not found
    #import <cloud_firestore/CloudFirestorePlugin.h>
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Podfile**:
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end

Tried "pod update", "flutter clean", and "flutter run" to no avail.

**Comment by zoechi** [comment]
@GraceWayDCDevelopment did you check you have the most recent versions of plugins?

**Comment by GraceWayDCDevelopment** [comment]
@zoechi FirebaseFirestore is 0.12.5. (From ios/Pods/Manifest.lock).

Additionally, I tried deleting all the Pods, deleting the cache, running "flutter clean", all with no benefit.

**Comment by zoechi** [comment]
@GraceWayDCDevelopment the newest is cloud_firestore 0.7.3
https://pub.dartlang.org/packages/cloud_firestore

**Comment by GraceWayDCDevelopment** [comment]
@zoechi Is there a known workaround/solution to this?  I already tried setting the version manually and it didn't work.

**Comment by zoechi** [comment]
@GraceWayDCDevelopment don't know what you mean.
I don't know where your `0.12.5` comes from. 
You need to set a valid range manually in `pubspec.yaml` that allows the `0.7.3` version and then run `flutter packages get` or `flutter packages upgrade`

**Comment by mikeashelby** [comment]
I've just done `pod update`, `flutter packages get`, `flutter packages upgrade` and `flutter clean`. I'm now getting this error when trying to build on iOS:

```5.4.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bf601e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010b5fd031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bfd5975 +[NSException raise:format:] + 197
	3   Runner                              0x00000001083dd72e +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 158
	4   Runner                              0x00000001083dd5b5 +[FIRApp configure] + 501
	5   Runner                              0x00000001083dcc49 -[AppDelegate application:didFinishLaunchingWithOptions:] + 121
	6   UIKit                               0x000000010c3d46fb -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 278
	7   UIKit                               0x000000010c3d6172 -[UIApplication _callInitializationDelegatesForMainSce<…>
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:58304/ws
```

What's next?!

**Comment by OskarKaminski** [comment]
@code-rover I have faced the same issue. It was probably caused because I added __cocoapods__ to the _Podfile_ in _ios_ folder and installed it by `pod install`.
You don't have to do it with _Flutter_.
I've started new project and added only __cloud_firestore__ to the _pubspec.yaml_, so when I clicked run, __pods__ have been installed automatically.

Everything works fine now.

Hope I could help.

**Comment by Black-Horse** [comment]
@mikeashelby I am facing the same problem.

`5.4.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bf601e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010b5fd031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bfd5975 +[NSException raise:format:] + 197
	3   Runner                              0x00000001083dd72e +[FIRApp configureDefaultAppWithOptions:sendingNotifications:] + 158
	4   Runner                              0x00000001083dd5b5 +[FIRApp configure] + 501
	5   Runner                              0x00000001083dcc49 -[AppDelegate application:didFinishLaunchingWithOptions:] + 121
	6   UIKit                               0x000000010c3d46fb -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 278
	7   UIKit                               0x000000010c3d6172 -[UIApplication _callInitializationDelegatesForMainSce<…>
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:58304/ws`

Have you found a solution for this?

**Comment by jashanpj** [comment]
Any one have a solution for this problem? I facing the same after upgrading flutter with dart. I used all the latest version for dependencies and the problem still exist. Here is the console out:

Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Firebase/Core":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Core
    
    Specs satisfying the `Firebase/Core` dependency were found, but they required a higher minimum deployment target.
    CocoaPods could not find compatible versions for pod "GoogleUtilities/AppDelegateSwizzler":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Core was resolved to 5.8.0, which depends on
            FirebaseAnalytics (= 5.1.2) was resolved to 5.1.2, which depends on
              GoogleUtilities/AppDelegateSwizzler (~> 5.2.0)
    
    Specs satisfying the `GoogleUtilities/AppDelegateSwizzler (~> 5.2.0)` dependency were found, but they required a higher minimum deployment target.
    CocoaPods could not find compatible versions for pod "gRPC-Core":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Firestore was resolved to 5.8.0, which depends on
            FirebaseFirestore (= 0.13.3) was resolved to 0.13.3, which depends on
              gRPC-C++ (~> 0.0.3) was resolved to 0.0.3, which depends on
                gRPC-C++/Implementation (= 0.0.3) was resolved to 0.0.3, which depends on
                  gRPC-Core (= 1.14.0)
    
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Firestore was resolved to 5.8.0, which depends on
            FirebaseFirestore (= 0.13.3) was resolved to 0.13.3, which depends on
              gRPC-ProtoRPC (~> 1.0) was resolved to 1.14.1, which depends on
                gRPC-ProtoRPC/Main (= 1.14.1) was resolved to 1.14.1, which depends on
                  gRPC (= 1.14.1) was resolved to 1.14.1, which depends on
                    gRPC/Main (= 1.14.1) was resolved to 1.14.1, which depends on
                      gRPC-Core (= 1.14.1)

**Comment by leorachit** [comment]
Same issue. Please help.

**Comment by GraceWayDCDevelopment** [comment]
@leorachit 
I didn't actually solve the problem.  I think I reinstalled an older version of Flutter and it worked fine after that.

**Comment by NightCrawler33** [comment]
Also running into the same issue. Tried switching from the new version of cloud firestore (0.8+)  to "^0.7.4" as suggested here: https://github.com/flutter/flutter/issues/24395 but couldn't get it to work.

Error output from Xcode build:
↳
    2018-12-12 21:46:20.493 xcodebuild[81757:864198]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-14098/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:757
    Details:  unexpected successful exit code from cancelled command <C0015:'CpResource flutter_assets':P12>
    Object:   <PBXTargetBuildContext: 0x7fafb9d1ac50>
    Method:   -createCommandInvocationRecordFromInvocation:
    Thread:   <NSThread: 0x7fafbaaac9e0>{number = 11, name = (null)}
    Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

**Comment by earyzhe** [comment]
Any more news on this issue? I have the same error 
''cloud_firestore/CloudFirestorePlugin.h' file not found'

**Comment by jacao** [comment]
Im getting the same issue

```
cloud_firestore/CloudFirestorePlugin.h' file not found
    #import <cloud_firestore/CloudFirestorePlugin.h>
```

my pubspec.yaml contains: `
cloud_firestore: ^0.8.2+3
`

my Podfile contains: 
```
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
```

I tried moving down to cloud_firestore: ^0.7.4, same error.

**Comment by zoechi** [comment]
@jacao try uncommenting `use_frameworks!` or add it if it isn't there to uncomment
```
target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
```
in `ios/Podfile`

**Comment by moritzmorgenroth** [comment]
Thanks @jacao, this solved the issue for me. However, I had to remove the line ` FirebaseApp.configure()` from my `AppDelegate.swift`.  Is this the new intended usage of the libraries? Should the pod config be left up to flutter now? I find it rather convenient, however, it is not reflected in any documentation.

**Comment by gitmoto** [comment]
> @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> 
> I found a fix:
> 
> I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> 
> I removed the pod resources I had setup using:
> 
> ```
> $ sudo gem install cocoapods-deintegrate cocoapods-clean
> $ pod deintegrate
> $ pod clean
> $ rm Podfile
> ```
> I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> 
> One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`

This worked great for me. They really need to update the documentation since this dead-ends you just when you're getting started with Firebase for Flutter

**Comment by sunnypatel** [comment]
> @leorachit
> I didn't actually solve the problem. I think I reinstalled an older version of Flutter and it worked fine after that.

Which version works for you?

**Comment by GraceWayDCDevelopment** [comment]
master branch

**Comment by sunnypatel** [comment]
> @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> 
> I found a fix:
> 
> I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> 
> I removed the pod resources I had setup using:
> 
> ```
> $ sudo gem install cocoapods-deintegrate cocoapods-clean
> $ pod deintegrate
> $ pod clean
> $ rm Podfile
> ```
> I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> 
> One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`

I also had to run `flutter clean` before `flutter run`

**Comment by kyleodev** [comment]
> @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> 
> I found a fix:
> 
> I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> 
> I removed the pod resources I had setup using:
> 
> ```
> $ sudo gem install cocoapods-deintegrate cocoapods-clean
> $ pod deintegrate
> $ pod clean
> $ rm Podfile
> ```
> I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> 
> One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`

Doesn't work once attempting an `archive`

**Comment by kakazaro** [comment]
> > @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> > I found a fix:
> > I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> > I removed the pod resources I had setup using:
> > ```
> > $ sudo gem install cocoapods-deintegrate cocoapods-clean
> > $ pod deintegrate
> > $ pod clean
> > $ rm Podfile
> > ```
> > I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> > One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`
> 
> Doesn't work once attempting an `archive`
> 
> Update: After a long search I've mended the problem, for future references make sure you open `Runner.xcworkspace` and not `Runner.xcodeproj` as the latter does not have access to Pods.

Thank you @kyleodev, you save my life...

**Comment by clairtonluz** [comment]
> > @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> > I found a fix:
> > I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> > I removed the pod resources I had setup using:
> > ```
> > $ sudo gem install cocoapods-deintegrate cocoapods-clean
> > $ pod deintegrate
> > $ pod clean
> > $ rm Podfile
> > ```
> > I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> > One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`
> 
> Doesn't work once attempting an `archive`
> 
> Update: After a long search I've mended the problem, for future references make sure you open `Runner.xcworkspace` and not `Runner.xcodeproj` as the latter does not have access to Pods.

Tks @kyleSHD this tip solve my problem.

**Comment by yanisalfian** [comment]
I had the same issue but somehow I can fix it by executing ```pod install``` in ```ios/```. I am using ```cloud_firestore 0.10.0```

**Comment by sknightq** [comment]
> @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> 
> I found a fix:
> 
> I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> 
> I removed the pod resources I had setup using:
> 
> ```
> $ sudo gem install cocoapods-deintegrate cocoapods-clean
> $ pod deintegrate
> $ pod clean
> $ rm Podfile
> ```
> 
> I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> 
> One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`

After I running `flutter run`, I got error from  install BoringSSL-GRPC, which will take a long time to clone, but always failed. Does anyone fix it?
![image](https://user-images.githubusercontent.com/8033144/62414084-eb6a7080-b649-11e9-9c6b-9fa06d9ff435.png)

**Comment by sknightq** [comment]
> > @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> > I found a fix:
> > I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> > I removed the pod resources I had setup using:
> > ```
> > $ sudo gem install cocoapods-deintegrate cocoapods-clean
> > $ pod deintegrate
> > $ pod clean
> > $ rm Podfile
> > ```
> > 
> > 
> > I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> > One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`
> 
> After I running `flutter run`, I got the error from install BoringSSL-GRPC, which will take a long time to clone, but always failed. Does anyone fix it?
> ![image](https://user-images.githubusercontent.com/8033144/62414084-eb6a7080-b649-11e9-9c6b-9fa06d9ff435.png)

I fixed it! Caution! Caution! I will use Chinese to explain this problem because of the block from the government. People who are in other countries can't be facing this problem.
当大家使用VPN的时候，由于设置的代理可能针对当前终端，而不是全局的，设为全局之后就可以解决以上问题。

**Comment by LSambo02** [comment]
> @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> 
> I found a fix:
> 
> I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> 
> I removed the pod resources I had setup using:
> 
> ```
> $ sudo gem install cocoapods-deintegrate cocoapods-clean
> $ pod deintegrate
> $ pod clean
> $ rm Podfile
> ```
> 
> I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> 
> One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`


Really thanks for the tip @jacao. It worked just fine after that, though I added ```$ flutter clean
``` before flutter run! It took a while to run the project, but it did! Regards

**Comment by kroikie** [comment]
@code-rover

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/863. Any further collaboration will be done there.

**Comment by thubamamba** [comment]
> > @zoechi thanks for the suggestion, I tried it and it seemed to cause some other issues.
> > I found a fix:
> > I had manually setup my Podfile and used `pod install` to add the Firebase/Firestore dependancy to my flutter iOS app. I read somewhere that you don't need to do that and flutter will handle it if you pubspec.yaml has the correct dependencies in.
> > I removed the pod resources I had setup using:
> > ```
> > $ sudo gem install cocoapods-deintegrate cocoapods-clean
> > $ pod deintegrate
> > $ pod clean
> > $ rm Podfile
> > ```
> > 
> > 
> > I then ran `flutter run` which then ran the pod install etc for me and then ran on my simulator fine.
> > One thing I did have to change though, was to make sure that the Build System set to legacy. In XCode `File -> Workspace Settings -> Build System: Legacy Build System`
> 
> Doesn't work once attempting an `archive`
> 
> Update: After a long search I've mended the problem, for future references make sure you open `Runner.xcworkspace` and not `Runner.xcodeproj` as the latter does not have access to Pods.

Worked for me. Thanks.
