### ISSUE TITLE
PerformanceOverlay doesn't draw correctly.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1625]
I don't see the individual data points.  The chart range seems to change over time, but other than that all I see is two horizontal light grey bars and two horizontal blue bars.

**Comment by chinmaygarde** [comment]
I am not able to reproduce this in the samples. May I have a reduced test case?

**Comment by abarth** [comment]
I'm assuming this was a modroid problem.  If you're still seeing this, please re-open.
