### ISSUE TITLE
Make the license generation and checking process usable.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#16255]
* There are no instructions on how to update the licenses before submission of a pull request on GitHub.
* There is no script to update the licenses in one step. The current license script only checks if the licenses are out of date.
* If the licenses are out of date, the script must be run again and the right files picked from a specific directory and placed in the correct spot before updating the PR. All this has to be inferred by reading the bash file that runs the script on Travis.
* The license script seems to have wildly different and undocumented behavior based on whether the script is in run in checked mode vs not.
* The script has hardcoded paths in it. Changing DEPS file entries makes this go out of sync.
* The license script can only be run on Linux since it dies regularly on hidden files on Mac.
* The license script takes a very long time to run and seems to run a small fraction of the resources on the workstation.
* The script requires a pristine working tree and dependencies. This makes working on multiple patches with different DEPS at the same time almost impossible. Forgetting the clear untracked DEPS and having to run the script again wastes a lot of time (twice since the script must first be run locally and then again on the bots).
* Submitting multiple patches that change licenses must be serialized.
* Running the license script in the tree generate a lot of untracked files.

**Comment by chinmaygarde** [comment]
We should really make this a priority. I have lost many productive days having to deal with this step of the engine contribution process. The situation is really really bad.

Maybe make a bot generate the licenses or something on an framework roll. @Hixie @jason-simmons: WDYT?

**Comment by Hixie** [comment]
The problem this is trying to solve is stopping people from checking in code (usually from new dependencies) that includes licenses that we haven't yet properly vetted and added to our LICENSE. So I think we should definitely have it run as part of the Travis pre-commit.

But we could definitely go through your list above and fix each one. The first three are easy to fix. The fourth I believe has already been fixed. The fifth is a little tricky but could be done. Mac support could be added; so far only Jason and I really did any work on it and we've both not really tested it on Mac.

Making the code better e.g. by using isolates to shard the work is definitely an option though I don't know how easy it would be. My impression is that this script is mostly I/O-bound.

Handling differing DEPS without breaking the intent of the script may be difficult.

Handling merge conflicts isn't going to be easy, but we could refactor the output of the "golden" files to be more merge-friendly. The LICENSE file itself (which is what really matters) will still be hard to merge, there's not much getting around that.

The last issue should be easy enough to deal with.

**Comment by Hixie** [comment]
We're going to have a period of time soon where we are focusing on technical debt issues, this seems like the perfect candidate for something to work on.

**Comment by Hixie** [comment]
A lot of this has been improved since this was filed. If there's still issues we should file new bugs to address them.
