### ISSUE TITLE
Investing using Clang for Window builds.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#16256]
The current compiler toolchain is capable of building for Windows. We need the appropriate SDK setup.

**Comment by dnfield** [comment]
We also need the Windows clang binaries right?  Fuchsia only gives us mac/Chromium.

This might want to get bumped in priority since Goma will no longer support VS2019, and we don't want to get stuck on 2017 or lose goma.

This would also have the benefit of unifying our compiler toolchain across platforms, avoiding silly bugs around things like differences in VA_ARGS handling or C++14/17/whatever support.

**Comment by dnfield** [comment]
@stuartmorgan says Chromium has Windows builds that might be usable for us - @chinmaygarde or @cbracken do you know if it's important that we keep using Fuchsia's builds, or would switching to Chromium's be fine?  I suspect it would be but I don't have much context on how that choice was made.

**Comment by stuartmorgan** [comment]
> we don't want to get stuck on 2017

This is already a concrete concern; I need to roll ANGLE, and the ToT version of ANGLE seems to crash VS 2017's cl.exe.

**Comment by chinmaygarde** [comment]
Switching to Chromium's toolchain should be fine. Since we already need to depend on the Fuchsia toolchain for Fuchsia SDK builds, it would have been nice to settle on a single source for all our toolchain needs[1]. But this is not a hard requirement. In the absence of us building and maintaining our own toolchains, we should get the toolchain from the best source possible.

[1] One desirable outcome of this is that all platforms could theoretically use the same version of Clang/LLVM. But this is not the case today and the whole point is moot if no single source gives us a toolchain that we can use for all target platforms.

**Comment by dnfield** [comment]
Fuchsia is working on a clang toolchain for windows: https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=44436

**Comment by stuartmorgan** [comment]
Taking at least temporarily, since I'm working on testing locally to see if there are any source-level or GN-level issues that need to be addressed to support clang builds.

**Comment by stuartmorgan** [comment]
At the moment clang builds are working for me with a manually installed toolchain, so for now we're just waiting on the clang binary being available. (Things may regress before then, since we don't have bots building that configuration, so I'll recheck regularly.)

**Comment by stuartmorgan** [comment]
This was fixed by the PR above, I just forgot to close the bug.
