### ISSUE TITLE
Update flutterfire plugins to version 12+

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#16266]
Firebase has moved on to version 12+ and uses version 3.2.0 of the google-services Gradle plugin. The `flutter/plugins` repo should follow suit.

https://firebase.google.com/docs/android/setup

**Comment by zoechi** [comment]
Seems everything is on 4.2.0 currently

**Comment by kroikie** [comment]
@mravn-google

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/862. Any further collaboration will be done there.
