### ISSUE TITLE
std::bad_alloc error

### ISSUE THREAD

**Issue by lakexyde** [flutter/flutter#16270]
I keep getting this error and my app crashes: 
```
F/libc    ( 9731): /usr/local/google/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed
F/libc    ( 9731): Fatal signal 6 (SIGABRT), code -6 in tid 9753 (Thread-2)
Lost connection to device.
```
I use the method below to push another screen after a tap from a list item. Where ```Product``` is a class I created from a network ```JSON``` response.
```
_gotoDetail(Product pItem) {
    Navigator.of(context).push(new MaterialPageRoute(
        builder: (BuildContext context) => new DetailsScreen(product: pItem)));
  }
```
What's funny and also frustrating is that it pushes the screen when you tap the first item. But throws that error on subsequent list items taps. 

Please what am I doing wrong? I need help ASAP

**Comment by jason-simmons** [comment]
What version of the Flutter framework and engine are you using?

Does this still happen if you build your app with the master branch of Flutter?  If so, then can you provide a subset of your application code that reproduces the crash?

**Comment by lakexyde** [comment]
Thanks @jason-simmons .
I am currently on the beta branch, still the same thing.
However, I discovered that a widget I used in an attempt to render partial HTML is the cause. Removed it and it works again.

**Comment by zoechi** [comment]
@palkatap this issue is quite old.
Please create a new issue with full information about how to reproduce.
Please add a link to this issue if you think it is relevant.
