### ISSUE TITLE
Issue from website page Reading and Writing Files

### ISSUE THREAD

**Issue by ctac1287** [flutter/flutter#16278]
Why I can't save file on this path?

I got error:

E/flutter (19356): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception: E/flutter (19356): FileSystemException: Cannot create file, path = '/storage/emulated/0/Download/tempfile.txt' (OS Error: Permission denied, errno = 13)

**Comment by zoechi** [comment]
I guess you need to add 
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
to `AndroidManifest.xml`

https://developer.android.com/training/data-storage/files.html

**Comment by zoechi** [comment]
I guess you can only write to directories provided by https://pub.dartlang.org/packages/path_provider
and need to use an intent for downloading

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/path_provider helps you to get paths where you app can read and write.
Hope this helps.
