### ISSUE TITLE
Scene.toImage()

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16274]
Spawned from various discussions in https://github.com/flutter/flutter/issues/6774 and https://github.com/flutter/flutter/issues/11648 -- we should have the following API:

```dart
Image Picture.toImage(int width, int height);        // Done in flutter/engine#3657
Future<Image> Scene.toImage(int width, int height);  // Not yet done
Future<ByteData> Image.toByteData();                 // Done in flutter/engine#4762
```

This issue tracks the last remaining API method: `Scene.toImage()`.

This should be the last blocker for having a good solution for https://github.com/flutter/flutter/issues/1433

**Comment by gspencergoog** [comment]
I asked Chinmay what needed to be done to implement this, and he said:

- We need to create an SkPictureRecorder-backed canvas and flatten the layer tree associated with the picture into it.
- Right now, the compositor needs to be created and a frame acquired from it, but this is wasteful as that object is quite heavyweight.
- The compositor context API needs to be updated to take just a picture recorder.
- Make sure to turn off the preroll pass.

**Comment by tvolkert** [comment]
This was fixed by https://github.com/flutter/engine/pull/5021

**Comment by nsreenath** [comment]
@tvolkert Now, is it possible to create a PNG from a widget tree ? If so, can you please share a sample code ?

**Comment by gspencergoog** [comment]
Yes, it's definitely possible: we're generating all of the API doc diagrams with it now.  I have an example that I can clean up and post here.

**Comment by tvolkert** [comment]
Also: https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/RenderRepaintBoundary/toImage.html

**Comment by nsreenath** [comment]
![original](https://user-images.githubusercontent.com/3154529/39959080-eb9b5258-5629-11e8-9231-2d5a2f1cd0dd.png)

In my Android phone (7.0), when I capture above text using:

```
ui.Image image = await boundary.toImage();
ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
Uint8List pngBytes = byteData.buffer.asUint8List();
```

and then setting it as `pngBytes` for `Image.memory(pngBytes)`,
I get the following image, with some pixelation. Is the pixelation expected for PNG ?
Android OS's screenshot mechanism however captures the text without any pixelation in PNG.

![captured](https://user-images.githubusercontent.com/3154529/39959093-38feff7c-562a-11e8-9079-2d0983b73f72.png)

**Comment by tvolkert** [comment]
re: previous comment, this is https://github.com/flutter/flutter/issues/17448

**Comment by nsreenath** [comment]
@tvolkert I am getting the above pixelation when using `boundary.toImage()` but not when taking screenshot using `flutter screenshot --type=rasterizer`. What does this rasterizer command do ?
(Flutter 0.4.5-pre.3 in master channel)

**Comment by nsreenath** [comment]
> re: previous comment, this is #17448

@tvolkert I was getting the pixelation when using `boundary.toImage()` because I was using the default argument of `boundary.toImage()` which was `pixelRatio: 1.0`. When I used my actual device pixel ratio of 3.0, the pixelation is gone. Does #17448 has anything to do with this ?

**Comment by andreidiaconu** [comment]
Not related to pixelation, but related to flakiness, `Image` widgets sometimes don't render in the final result. Filed a bug for this: https://github.com/flutter/flutter/issues/17687 . Is it possible to get some guidance on this?

**Comment by nsreenath** [comment]
@tvolkert `Picture.toImage()` is also causing pixelation while creating an image from a canvas. Is it expected ?

**Comment by tvolkert** [comment]
Nope, assuming you're passing it a sensible width & height

**Comment by nsreenath** [comment]
@tvolkert but I am using correct width and height.

![image](https://user-images.githubusercontent.com/3154529/40210147-f4fc7dbe-5a60-11e8-9cf1-7d57f598538c.png)

You can see the code here:
[main.dart.txt](https://github.com/flutter/flutter/files/2015091/main.dart.txt)

**Comment by tvolkert** [comment]
For archeologists, relevant follow-up discussion is in https://github.com/flutter/flutter/issues/17782
