### ISSUE TITLE
'flutter apk' fails if flutter.yaml does not exist

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#1628]
@mpcomplete 

~/flutter/examples/hello_world $ flutter apk
The null object does not have a method '[]'.

NoSuchMethodError: method not found: '[]'
Receiver: null
Arguments: ["services"]
dart:core                                                         Object.noSuchMethod
package:flutter_tools/src/commands/apk.dart 223                   _findServices.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/apk.dart 249                   _findServices.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/apk.dart                       _findServices
package:flutter_tools/src/commands/apk.dart 287                   _findApkComponents.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/apk.dart                       _findApkComponents
package:flutter_tools/src/commands/apk.dart 477                   buildAndroid.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/apk.dart                       buildAndroid
package:flutter_tools/src/commands/apk.dart 198                   ApkCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/apk.dart                       ApkCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 51          FlutterCommand.run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 174  FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/executable.dart 63                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 57                          main.<async>

**Comment by eseidelGoogle** [comment]
Fine to fail, just need to fail gracefully. :)
