### ISSUE TITLE
Archive page on website should load my OS first.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#16282]
The [archive page](https://flutter.io/sdk-archive/) on the website should sort the tabs with the OS that is in the user agent first, and then always select the first tab at load time.

Currently it appears to keep the last one you selected in a cookie, but that's not really the best behavior: I usually want my platform, not the last one I was looking at.

**Comment by mit-mit** [comment]
Or perhaps at least default to current OS if the cookie is not there?

**Comment by DanTup** [comment]
The behaviour of remembering the last one was added when the tabs were for tools (eg. VS Code vs Android Studio), so it just happened here too. We can easily change it in this case (we pass in the name of the localStorage setting to use, so can just skip it for OS tabs).

If we're going to change the order of the tabs, we might want to think about having them hidden until they're re-ordered - there's already a bit of a flicker as we change the selected tab at page load. The risk though is if JS is disabled/errors that the user gets a blank page!

**Comment by mit-mit** [comment]
I think we should start with just selecting the tab based current OS.

**Comment by DanTup** [comment]
@mit-mit Do you want this to always pre-select the users or only when there's no local storage (note: the local storage doesn't expire)?

**Comment by DanTup** [comment]
PR at https://github.com/flutter/website/pull/958, staged at https://dantup-flutter-staging.firebaseapp.com/sdk-archive/
