### ISSUE TITLE
Build failed after added cloud_firestore package

### ISSUE THREAD

**Issue by paavalan** [flutter/flutter#16286]
**## Logs**

Note: C:\Users\Paavalan\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.4.0\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
Finished with error: Gradle build failed: 1

**## Flutter Doctor**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v0.2.9, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.21.1)
[√] Connected devices (1 available)

**Comment by elliottolson** [comment]
This error typically means that some of your dependencies use a different version. Try to downgrade or upgrade your plugins to unify the version.

**Comment by paavalan** [comment]
Solved. Thanks @elliottolson

**Comment by Pratyum** [comment]
What is the version that makes it work? I seem to have the same problem

**Comment by zoechi** [comment]
@Pratyum that depends on your project. There are several things that need to have compatible version ranges. I'd suggest you create a StackOverflow question with your 2 `build.gradle` files.

**Comment by Pratyum** [comment]
I fixed it with in the `app/build.gradle` file by adding
```
android{
    multiDexEnabled true
}
```
