### ISSUE TITLE
New installs encountering trouble getting packages in the flutter_gallery example

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#16283]
This is happening to users following the https://flutter.io/get-started/install/ instructions.  

The error appears similar to #16162.

I'm asking them to provide more details on this thread.

**Comment by Sun3** [comment]
I downloaded it from Git as a Zip file. Then unzipped, opened the gallery folder and did a flutter get, the flutter upgrade.

## Logs
Pix:flutter_gallery marco$ flutter run
Running "flutter packages get" in flutter_gallery...
Package file has no versions that match 2.3.7 derived from:
- flutter_driver 0.0.0 depends on version 2.3.7
- flutter_gallery depends on version 3.0.0
pub get failed (1)
Pix:flutter_gallery marco$

## Flutter Doctor
Pix:flutter_gallery marco$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.2.3 at /Users/marco/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/marco/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone X • 55C63F10-A0FA-4CD8-9E89-BF66AA5FEA8F • ios • iOS 11.3 (simulator)

• No issues found!
Pix:flutter_gallery marco$


---  I also tried the flutter packages get

## flutter packages get
[flutter_gallery] flutter packages get
Running "flutter packages get" in flutter_gallery...
Package file has no versions that match 2.3.7 derived from:
- flutter_driver 0.0.0 depends on version 2.3.7
- flutter_gallery depends on version 3.0.0
pub get failed (1)
exit code 1

**Comment by Sun3** [comment]
Works fine with the Beta 2 Update.

**Comment by DanTup** [comment]
Based on the age of this, the comment above and comments in https://github.com/flutter/flutter/issues/16162 I think this is long fixed. Please post back if you still have issues.
