### ISSUE TITLE
flutter upgrade fatal: Not possible to fast-forward, aborting.

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#16294]
## Steps to Reproduce

`flutter upgrade`

## Logs

```
Upgrading Flutter from /Users/zoechi/flutter/flutter...
From https://github.com/flutter/flutter
   b39740656..487e6bc91  dev        -> origin/dev
   7010bd416..2134adce6  master     -> origin/master
 * [new tag]             v0.2.9     -> v0.2.9
fatal: Not possible to fast-forward, aborting.
```
Might be related to https://github.com/flutter/flutter/issues/9218#issuecomment-378772440

```
(dev) $ git status -v
On branch dev
Your branch and 'origin/dev' have diverged,
and have 7 and 10 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

```
 (dev) $ git clean -xffd
Removing bin/cache/
Removing packages/flutter_tools/.dart_tool/
Removing packages/flutter_tools/.packages
Removing packages/flutter_tools/pubspec.lock
Removing version
zoechi@mac ~/flutter/flutter
 (dev) $ flutter upgrade
Downloading Dart SDK from Flutter engine c903c217a1a8206cdebdab1703b52ec6180edf37...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.8M  100 44.8M    0     0  2958k      0  0:00:15  0:00:15 --:--:-- 3165k
Building flutter tool...
Upgrading Flutter from /Users/zoechi/flutter/flutter...
fatal: Not possible to fast-forward, aborting.
```
```
 (dev) $ git reset --hard
HEAD is now at c0d1eb751 Merge branch 'dev' of https://github.com/flutter/flutter into dev
zoechi@mac ~/flutter/flutter
 (dev) $ git pull
Merge made by the 'recursive' strategy.
 analysis_options.yaml                                           |   6 ++++++
...
packages/fuchsia_remote_debug_protocol/pubspec.yaml             |   8 ++++----
 40 files changed, 338 insertions(+), 120 deletions(-)
```
```
 (dev) $ git reset --hard
HEAD is now at 8f6798fd0 Merge branch 'dev' of https://github.com/flutter/flutter into dev
zoechi@mac ~/flutter/flutter
 (dev) $ flutter doctor
Waiting for another flutter command to release the startup lock...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.2.2-pre.8, on Mac OS X 10.13.4 17E199, locale en-AT)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

This finally fixed it, but it's quite cumbersome.
I'm not (knowingly) modifying anything in the `flutter` directory (as `git status` shows).

Is there an easier way? It seems I have to go through this procedure every time since a few weeks when I try to update my Flutter installation.

## Flutter Doctor

```
✓] Flutter (Channel dev, v0.2.2-pre.7, on Mac OS X 10.13.4 17E199, locale en-AT)
    • Flutter version 0.2.2-pre.7 at /Users/zoechi/flutter/flutter
    • Framework revision c0d1eb7513 (3 days ago), 2018-04-03 12:52:53 +0200
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by DanTup** [comment]
> I'm not (knowingly) modifying anything in the `flutter` directory (as `git status` shows).

I don't think this one is related to uncommitted local modifications, but rather commits (eg. commits you have locally that aren't in the branch being pulled):

> Your branch and 'origin/dev' have diverged,
> and have 7 and 10 different commits each, respectively.

An simple fix here is probably `git reset --hard origin/dev` which would throw away the local commits pointing your local branch at the same revision as the remote. However, I'm curious what's happened - how do you have commits in your local branch that aren't in the origin? It seems like either local commits have been made or the origin branch had commits removed/rebased (both of which sound a little strange to me - though I don't know a lot about how flutter upgrade is supposed to work or whether rebasing is intended to ever happen on the channel branches).

If you see this one again, it'd be interesting to see the last few local commits you have before you fix it.

**Comment by DanTup** [comment]
> HEAD is now at 8f6798fd0 Merge branch 'dev' of https://github.com/flutter/flutter into dev

That hash doesn't seem to exist in the flutter repo, making me think something has been making commits locally - have you used git to pull changes directly, which may have merged?

I think `git log dev..origin/dev` should show you the changes you have in your `dev` branch that aren't in the origins.

**Comment by zoechi** [comment]
@DanTup thanks. So it seems to be only a lack of Git knowledge on my side :/
I'll try your suggestion and report back

**Comment by zoechi** [comment]
@DanTup seems to have fixed it. If it happens again with the next update, I'll reopen.
