### ISSUE TITLE
Issue from website page Internationalizing Flutter Apps

### ISSUE THREAD

**Issue by GoHash-Include** [flutter/flutter#16298]
From URL: https://flutter.io/tutorials/internationalization/ Hi, am trying to add multiple language support in my flutter app but am confusing with your tutorial, can you please share sample project of Internationalizing translation with intl package. Thank you.

**Comment by HansMuller** [comment]
The tutorial provides the source for a complete intl example: https://github.com/flutter/website/tree/master/_includes/code/internationalization/intl/
