### ISSUE TITLE
How to animate line graph on ECG real-time data?

### ISSUE THREAD

**Issue by Developer1234567** [flutter/flutter#16299]
I'm currently trying to use this module to use a line graph for my ECG data and animate it with new data.

Is it possible to use real-time data and show it in a line graph? Here is what I mean by animation.

Please let me know.

Thanks

**Comment by zoechi** [comment]
How-to questions are better asked on StackOverflow

**Comment by eswarvarma-dev** [comment]
> I'm currently trying to use this module to use a line graph for my ECG data and animate it with new data.
> 
> Is it possible to use real-time data and show it in a line graph? Here is what I mean by animation.
> 
> Please let me know.
> 
> Thanks

Hi have you solved the issue
