### ISSUE TITLE
Loading assets via platform channels incurs unnecessary copies.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#16291]
Assets should instead be loaded via a native binding.

An additional optimization is to only create a mapping of the read-only assets in the bundle (via an `mmap` of the asset or via the `AAssetManager` where available) and wrap it with with a `Dart_WeakPersistentHandle` created using `Dart_NewWeakPersistentHandle`. The wrapped object can then be set as a peer to the VM managed allocation via `Dart_SetPeer`. Later, when the engine gets this allocation, it can access this peer directly instead of creating an extra copy from the allocation for asynchronous use of said data. This usually happens when the framework attempts to load an asset and send it to back to the engine for asynchronous texture upload. In this case, using the peer directly (along with not using the platform channel) would save three copies of the asset.

Care must be taken on the platform side to ensure that the framework or client code does not modify the peer backed allocation. This can be done via wrapping the the byte buffer on the framework side with a [`UnmodifiableUint8ListView`](https://docs.flutter.io/flutter/dart-typed_data/UnmodifiableUint8ListView-class.html). The side effect of this change would be that assets would be unmodifiable by the Dart application. If applications don't even need read access to the asset and instead only use it to pass back to the engine, the framework should even consider assets as opaque engine vended handles.

**Comment by chinmaygarde** [comment]
This came up during a discussion with @rmacnak-google and @jason-simmons on performance of handling assets. It is possible that we should split this issue into two and tackle them separately. One issue for the use of the platform channels and another for the extra optimization mentioned.

@Hixie: Making the asset buffer unmodifiable would be a breaking change but it would be quite performant. We could also implement a COW mechanism if we think we are past the point of introducing such changes.

**Comment by Hixie** [comment]
This is a good breaking change. Changing the data is pretty bug-prone anyway.

When you announce it, you can say that we're reducing the number of copies but that if they want to be able to mutate it they just need to add back the copy, and show how (probably just call `.toList()` or some such, I think).

**Comment by chinmaygarde** [comment]
@jason-simmons has implemented using weak persistent handles to give the framework engine managed allocations in this patch. This reduces one copy.

**Comment by chinmaygarde** [comment]
As it turns out, since the engine does not write into the allocation once it creates the weak persistent handle to give to the framework, the framework is free to write into it. So wrapping the list in a UnmodifiableUint8ListView is not necessary.

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by chinmaygarde** [comment]
No. Both discussed optimizations ([loading assets by mapping](https://github.com/flutter/engine/blob/2226c2a1ec9644d37ff25f246a9d81c326320f8b/shell/common/engine.cc#L545) and [Dart views into native mappings](https://github.com/flutter/engine/blob/2226c2a1ec9644d37ff25f246a9d81c326320f8b/lib/ui/window/platform_message_response_dart.cc#L46)) are in place.
