### ISSUE TITLE
Debugging tests is unnecessarily hard

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#163]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Sep 16, 2015 at 19:49 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1196_

---

It would be great if there was a way to launch a single test in Observatory. Right now since there's no way to set breakpoints before you've loaded the code, the only way I can think to do it is to modify the code to call debugger(), then run the test, then attach the debugger (somewhere? it's not clear where to attach it, really). Really I want the equivalent of "start with gdb" but for observatory.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sethladd](https://github.com/sethladd)**
_Friday Sep 18, 2015 at 01:48 GMT_

----

cc @devoncarew as we're exploring a debugger

Would make a ton of sense to right-click on a single test and run that, with the debugger, from Atom

**Comment by eseidelGoogle** [comment]
@Hixie has a patch in progress which may address some of this?

**Comment by Hixie** [comment]
It's not yet easy to debug a test under `flutter test` in observatory. What I'm doing will make it possible to test under `flutter run`, but that's not really the same.

**Comment by sethladd** [comment]
Did we make progress on this?

I'd like to clarify this request is for making it easier to debug a test without using an IDE. We could open a separate request for a test runner (implied: debugging) in the IDE plugin, but I believe you are looking for a solution without the IDE?

**Comment by Hixie** [comment]
What we need to resolve this is support for `flutter test --start-paused filename.dart`.
