### ISSUE TITLE
flutter_webview plugin

### ISSUE THREAD

**Issue by rymotion** [flutter/flutter#16315]
I'm trying to integrate the flutter_webview plugin in `webPage.dart` and am having a problem with build on iOS and Android platforms.

## Background
I have already upgraded to the latest Flutter build and have written in the dependencies to the .yaml
I understand there are requirements as per the docs to change certain things with the Android Manifest but nothing explicitly stated for iOS although I'm thinking I have to manually put in the `.h` file that is missing even though I think it should be there on compile.

### Logs
[androidLog.txt](https://github.com/flutter/flutter/files/1884879/androidLog.txt)

### Logs
[iosLog.txt](https://github.com/flutter/flutter/files/1884880/iosLog.txt)

### Analyze
[fAnaLog.txt](https://github.com/flutter/flutter/files/1884925/fAnaLog.txt)
### Doctor
[fDocLog.txt](https://github.com/flutter/flutter/files/1884926/fDocLog.txt)

**Comment by mit-mit** [comment]
For issues in `flutter_webview_plugin`, please file bugs in it's repo (it's a community contribution):
https://github.com/dart-flitter/flutter_webview_plugin/issues
