### ISSUE TITLE
Tree shake material icons

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16311]
Inspired by http://fluttericon.com/

We should be able to tree-shake our `.ttf` file that holds our material icons.  Un-shaken, it's ~130K in size, but every icon takes up only ~300 bytes.  We know from the app's usage of [`Icons`](https://github.com/flutter/flutter/blob/731ed1b11b388f714eaeb3ed03969f27d195e1a2/packages/flutter/lib/src/material/icons.dart#L29) what icons it actually needs, so we should be able to ship a font file that's much lower than 130K - likely saving over 100K on final app bundle size.

**Comment by dnfield** [comment]
A different approach to this: https://github.com/flutter/flutter/issues/34206

**Comment by willlarche** [comment]
Related #6177
