### ISSUE TITLE
Syntax errors - Please Do Not FIx!

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#16313]
**Please do not fix!**

I am creating this issue as part of training for a new writer, Christine Z.

---

The following files have instances of "the the".

flutter-for-android.md
flutter-for-react-native.md
formatting.md

**Comment by czakdesign** [comment]
1 Found in formatting.md -- /GitHub/website/formatting.md

1 Found in index.md. /GitHub/website/tutorials/international/index.md
'file servers as a template for the the English...'

In flutter-for-react-native.md >> it's showing as 'the theme' -- not 'the the'

Didn't find it in flutter-for-android.md
Let me know if you want me to submit the updated files  /cz

**Comment by czakdesign** [comment]
Hey Shamz - Is there a specific branch that should I use to upload the changed files - then I'll create a pull request - anything else ?
