### ISSUE TITLE
Would like a doc about our decision process for modifying dart:ui

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#16316]
My impression is that our processes around modifying dart:ui are slightly different (more conservative) than Flutter framework.

Assuming others agree, it seems we should write this down somewhere?

- We care more about performance in the engine.  And specifically seem to have policy around only exposing "fast" things.  (e.g. https://github.com/flutter/flutter/issues/4858 discussion)
- We feel like it's even harder to deprecate things from the engine.  So maybe a stronger policy than https://flutter.io/design-principles/#handling-breaking-changes is needed specifically for the engine?
- We care a lot about "focus" of the code in the engine and only exposing the minimum set (leaving the rest to plugins and frameworks when possible.

Thoughts @cbracken @Hixie?  Maybe this is written down somewhere already?

**Comment by Hixie** [comment]
> We care more about performance in the engine

We care about performance everywhere. The same logic would apply to doing this in the painting layer, for example.

> We feel like it's even harder to deprecate things from the engine

I think that may actually be backwards. At least for dart:ui, the engine is far more abstracted away from developers than, say, the material library.

> We care a lot about "focus" of the code in the engine and only exposing the minimum set 

That's true of all layers, not just the engine.

Anyway, this should all be written down in the design principles doc. I've tried to update it for some recent lessons learnt in https://github.com/flutter/website/pull/942.

**Comment by Sfshaza** [comment]
@Hixie, are we still waiting for the PR?

**Comment by Sfshaza** [comment]
@Hixie, I see the changes to design principles was merged some time ago. Do you feel that the points in the original issue are satisfied?  I read the changed text and it wasn't so obvious to me.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2080](https://github.com/flutter/website/issues/2080) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sfshaza2** [comment]
Re-opening as the design principles doc has been moved to the Flutter wiki, under engineering control.
