### ISSUE TITLE
Request: SystemChrome.setSystemUIOverlayStyle support in Android (engine)

### ISSUE THREAD

**Issue by mbullington** [flutter/flutter#16320]
Hello Flutter team!

I'm working on an app where I wanted dark status bar icons (popular in Android M+ applications), and dug up that SystemChrome.setSystemUIOverlayStyle actually does nothing on Android.

https://github.com/flutter/engine/blob/ba98f2634b230f6ce006f8513902c3ad0bd8a6d6/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L225 

I read the comment pertaining to why this wasn't implemented, and although I'm not sure if changing the color of the nav bar (in addition to the status bar) is a good idea, it's also possible starting in Android Oreo.

Thanks!

**Comment by mbullington** [comment]
Fixed by this commit, thanks!

https://github.com/flutter/engine/commit/57f53b98a482c6f7f921f06f974c4d199097bfa1

**Comment by jonahwilliams** [comment]
Hi @mbullington, https://github.com/flutter/flutter/issues/16837 is the issue to follow for the addition of framework support for this feature
