### ISSUE TITLE
Document conventions for accessing and checking MethodCall arguments on Java

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#16327]
Cf https://github.com/flutter/plugins/pull/466#discussion_r179887667

**Comment by xster** [comment]
Document the preferred way of handling exceptions between `result.error(...)`, `throw new IllegalArgumentException`, `result.notImplemented` etc on Java. 

`@throw`, `result([FlutterError...`,  `result(FlutterMethodNotImplemented)` on iOS.

**Comment by Sfshaza** [comment]
The referred issue is fixed and landed. Presumably this is ready to address.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2077](https://github.com/flutter/website/issues/2077) via [**ZenHub**](https://www.zenhub.com/)
