### ISSUE TITLE
Text To Speech (TTS) plugin for IOS needed

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#16321]
There is a plugin for Android available :
https://github.com/flutter/flutter/issues/12025

To be useful we need the feature available on IOS also.

**Comment by Coder-256** [comment]
This should be trivial to implement, here's some demo code from [NSHipster](http://nshipster.com/avspeechsynthesizer/):

```objc
NSString *string = @"Hello, World!";
AVSpeechUtterance *utterance = [[AVSpeechUtterance alloc] initWithString:string];
utterance.voice = [AVSpeechSynthesisVoice voiceWithLanguage:@"en-US"];

AVSpeechSynthesizer *synthesizer = [[AVSpeechSynthesizer alloc] init];
[synthesizer speakUtterance:utterance];
```

Setting `utterance.voice` probably isn't even necessary (see [here](https://developer.apple.com/documentation/avfoundation/avspeechutterance/1619710-voice?language=objc)).
The only other parts to consider are adding pausing and delegate functionality (ex. for callbacks after speaking finishes). More info here on [iOS Speech Synthesis](https://developer.apple.com/documentation/avfoundation/speech_synthesis).

**Comment by dlutton** [comment]
@Rockvole I created a package if you want to play with TTS on ios/android until they release an official version.  It's a basic implementation.  I'm still trying to add features such as setting the speech volume and also adding better error handling.  https://pub.dartlang.org/packages/flutter_tts

**Comment by Rockvole** [comment]
Cool thanks, I will give it a try.

**Comment by Rockvole** [comment]
Hi @dlutton 
I tried your plugin, I just added this code to get started :

    @override
    void initState() {
      super.initState();
      FlutterTts flutterTts = new FlutterTts();
    }

Unfortunately I get an error :

    E/AndroidRuntime( 4821): FATAL EXCEPTION: main
    E/AndroidRuntime( 4821): Process: com.example.testtts, PID: 4821
    E/AndroidRuntime( 4821): java.lang.NullPointerException: collection == null
    E/AndroidRuntime( 4821): 	at android.os.Parcel.readException(Parcel.java:1552)
    E/AndroidRuntime( 4821): 	at android.os.Parcel.readException(Parcel.java:1499)
    E/AndroidRuntime( 4821): 	at android.speech.tts.ITextToSpeechService$Stub$Proxy.getVoices(ITextToSpeechService.java:700)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech$15.run(TextToSpeech.java:1712)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech$15.run(TextToSpeech.java:1677)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2232)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:742)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:732)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech.getDefaultVoice(TextToSpeech.java:1677)
    E/AndroidRuntime( 4821): 	at com.eyedeadevelopers.fluttertts.FlutterTtsPlugin$2.onInit(FlutterTtsPlugin.java:71)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech.access$1400(TextToSpeech.java:59)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2146)
    E/AndroidRuntime( 4821): 	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2101)
    E/AndroidRuntime( 4821): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
    E/AndroidRuntime( 4821): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
    E/AndroidRuntime( 4821): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
    E/AndroidRuntime( 4821): 	at android.os.Handler.dispatchMessage(Handler.java:102)
    E/AndroidRuntime( 4821): 	at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime( 4821): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
    E/AndroidRuntime( 4821): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime( 4821): 	at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime( 4821): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    E/AndroidRuntime( 4821): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by dlutton** [comment]
@Rockvole 
Thanks for the stack trace.

It appears the android getDefaultVoice method is returning null.
Per the android documentation "The default voice instance for the default language, or null if not set or on error."

Sounds like there is some type of error or the default language on your device is not set, however I'll add a try catch block around that.

**Comment by Rockvole** [comment]
Nice job on the TTS plugin @dlutton 

I tried out your plugin on a couple of devices.
Nexus 9 : Android 7.1.1 (Hardware) - works well
Nexus 5 : Android 6.0.1 (Hardware) - works well

Nexus 5 : Api 24 (emulator) - works but choppy voice
Nexus 6 : Api 22 (emulator) - gives the error above

I guess the emulator choppiness is just due to the speed of the emulators.
Perhaps the error above is due to the Api being too old ? If so, it would be good to throw an UnsupportedDevice exception or something which can be caught so I can display an appropriate message ?

**Comment by dlutton** [comment]
@Rockvole 

Thanks for the additional information.  I'll try to recreate the issue with that Api and throw an appropriate exception.

**Comment by dlutton** [comment]
@Rockvole 
Per the android documentation, the methods I'm using should be supported by Android API version 21 and 22, however it appears there are some known Android issues that were never addressed (https://issuetracker.google.com/issues/37012397).  I'll simply add a version check and run the deprecated methods if less than or equal to API 22.

**Comment by Rockvole** [comment]
plugin works well.
