### ISSUE TITLE
Re-word "Create the starting Flutter app"

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16324]
When I first read this, I had to read it a few times to know what we meant -- I was reading "starting" as a verb.

How about "Create the initial Flutter app" instead?

**Comment by mit-mit** [comment]
This is https://flutter.io/get-started/codelab/#step-1-create-the-starting-flutter-app

cc @Sfshaza who created the codelab.

**Comment by Sfshaza** [comment]
Fixed.
