### ISSUE TITLE
intellij_test is not hermetic

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16339]
Added in https://github.com/flutter/flutter/pull/16198

This test isn't hermetic and is subject to flakiness. We try to ensure that all new tests are hermetic by using `MemoryFileSystem`, `FakePlatform`, and a mocked `ProcessManager` where need be (using context overrides).

**Comment by scheglov** [comment]
1. I copied these tests from `doctor_test.dart`, which does not use overrides. Or do I miss them?

2. These tests check presence and content of several jars, which we have in physical file system. How is this situation usually solved Flutter tests? It seems that copying them into `MemoryFileSystem` will not make them more hermetic, will it? Hm... Maybe I should instead just create jars inside of the test? Should not be too hard, we need just `META-INF/plugin.xml` in these jars.

**Comment by tvolkert** [comment]
> I copied these tests from `doctor_test.dart`, which does not use overrides

Ah, makes sense - `doctor_test.dart` is blacklisted in Google because it's not hermetic 😄 

Yeah, creating jars inside the test would work.

If this is meant to be more of an integration test, then we can leave it as-is and just blacklist it within Google.   It looks like it's meant to be more of a unit test though.
