### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type 'Future<Response>'

### ISSUE THREAD

**Issue by ShawnRG** [flutter/flutter#16337]
## Steps to Reproduce

Using [Twitter package](https://github.com/sh4869/twitter.dart).

After running this piece of code:
`var responses = await twitter.request("GET", "statuses/user_timeline.json");`

## Logs

E/flutter (21301): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (21301): type 'Future<dynamic>' is not a subtype of type 'Future<Response>' where
E/flutter (21301):   Future is from dart:async
E/flutter (21301):   Future is from dart:async
E/flutter (21301):   Response is from package:http/src/response.dart
E/flutter (21301): 
E/flutter (21301): #0      Twitter.request (package:twitter/twitter.dart:71:23)
E/flutter (21301): #1      TwitterData.getTweet (package:prototype/ui/meldingen/twitter_page.dart:144:21)
E/flutter (21301): <asynchronous suspension>
E/flutter (21301): #2      new TwitterData (package:prototype/ui/meldingen/twitter_page.dart:126:5)
E/flutter (21301): #3      new TwitterPage (package:prototype/ui/meldingen/twitter_page.dart:157:26)
E/flutter (21301): #4      _MyHomePageState._toggleBodyView (file:///home/programmeur/Downloads/flutter_local_notifications-master/prototype/lib/main.dart:129:18)
E/flutter (21301): #5      _MyHomePageState.build (file:///home/programmeur/Downloads/flutter_local_notifications-master/prototype/lib/main.dart:241:19)
E/flutter (21301): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
E/flutter (21301): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
E/flutter (21301): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter (21301): #9      StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
E/flutter (21301): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter (21301): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter (21301): #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
E/flutter (21301): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
E/flutter (21301): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
E/flutter (21301): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
E/flutter (21301): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
E/flutter (21301): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter (21301): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter (21301): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
E/flutter (21301): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter (21301): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter (21301): #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
E/flutter (21301): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter (21301): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter (21301): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
E/flutter (21301): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
E/flutter (21301): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
E/flutter (21301): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
E/flutter (21301): #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
E/flutter (21301): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
E/flutter (21301): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
E/flutter (21301): #43     ComponentElement.performRebuild 

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

[✓] Flutter (Channel dev, v0.2.9, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.9 at /home/programmeur/Software/flutter
    • Framework revision 487e6bc91e (4 days ago), 2018-04-03 10:59:12 -0700
    • Engine revision 04f3c6557c
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/programmeur/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/programmeur/Software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/programmeur/Software/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Nexus 7 • 10.0.0.202:5555 • android-arm • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by ShawnRG** [comment]
Thanks for your response. But no the only import i have is the import to the twitter.dart

**Comment by jonahwilliams** [comment]
@ShawnRG The problem appears to be a strong mode type error in the flutter.dart library. The `Completer` used to return the http response is created as a `Completer<dynamic>`, so the returned future is a `Future<dynamic>`.  This will fail at runtime if passed to a method which expects a `Future<http.Request>`.

**Comment by ShawnRG** [comment]
Thank you for your comment. Any idea how I could solve this?

**Comment by ShawnRG** [comment]
@jonahwilliams Thank you for your response. I have filed an issue on the twitter.dart repo [here](https://github.com/sh4869/twitter.dart/issues/9)
