### ISSUE TITLE
FadeInImage does not work as intended when filtering

### ISSUE THREAD

**Issue by namanix** [flutter/flutter#16340]
I found a small but really breaking bug (For me at least).

Currently i'm trying to create a userlist with search function and a small picture in front of every user.
When i first load everything in it works well. But when i start searching. The pictures in front of the users don't correspond with the correct users anymore.

To make this a lot easier to reproduce, i've created a sample project.
Just run the app. Wait for the picture to load (Only the first picture will load. The second one will 404 but that's intended). WHen the picture is loaded click on "Press here" and you will see that the url containing the 404 picture will be displayed in front of a working picture.

As a small addition. This does not happen with the normal Image widget. Only with the FadeInImage

I really hope we can find a solution for this problem. I started digging in the code to find it. But my knowledge of Flutter isn't high enough to find it.

Sample project: [Flutter_FadeInImageBug](https://github.com/namanix/Flutter_FadeInImageBug)

**Comment by zoechi** [comment]
Thanks for reporting the issue and sorry for the late response.
I just tried but the URL the test project accesses seems not to be valid anymore.
Can you still reproduce the issue?
