### ISSUE TITLE
Not able write into /storage/emulated/0/ & /mnt/sdcard/

### ISSUE THREAD

**Issue by ctac1287** [flutter/flutter#16347]
when run this code:
```dart
File file = await new File('/mnt/sdcard/Download/tempfile.txt').create();
```
i have error:
```
FileSystemException: Cannot create file, path = '/mnt/sdcard/Download/tempfile.txt' (OS Error: Permission denied, errno = 13)
```
manifest have:
```yml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by zoechi** [comment]
I guess the https://pub.dartlang.org/packages/path_provider package needs support for 
Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS); 
https://stackoverflow.com/a/7908446/217408

**Comment by creativecreatorormaybenot** [comment]
@zoechi I do not understand the upvotes for this suggestions. It seems like the underlying problem is entirely different.

**Comment by jinfagang** [comment]
Yes, indeed this issue https://github.com/flutter/flutter/issues/40498
Also indicates some permission denies error.

Even after I using permission_handler package to ask permissions the directory still can not writable.

**Comment by TahaTesser** [comment]
Hi everyone, 
path_provider is there to provide a path, it doesn't write, the main issue is https://github.com/flutter/flutter/issues/40498
Since `path_provider` does its job, I am closing this issue 
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by darshansharma** [comment]
I am still getting the error in targetSdk 30
`E/flutter (18294): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/mydir' (OS Error: Operation not permitted, errno = 1)`

I have already given WRITE_EXTERNAL_STORAGE, READ_EXTRNAL_STORAGE and ACCESS_MEDIA_LOCATION permission in manifest

**Comment by princesanjivy** [comment]
> I am still getting the error in targetSdk 30
> `E/flutter (18294): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/mydir' (OS Error: Operation not permitted, errno = 1)`
> 
> I have already given WRITE_EXTERNAL_STORAGE, READ_EXTRNAL_STORAGE and ACCESS_MEDIA_LOCATION permission in manifest

Its working fine with API 30 but fails in 31 and I'm getting the same error.

**Comment by TahaTesser** [comment]
Please follow https://github.com/flutter/flutter/issues/40498
