### ISSUE TITLE
Error "Android license status unknown" after running 'flutter upgrade' on Mac and Windows 10

### ISSUE THREAD

**Issue by xemox** [flutter/flutter#16342]
[✓] Flutter (Channel dev, v0.2.9, on Mac OS X 10.13.4 17E199, locale en-ID)
    • Flutter version 0.2.9 at /Users/yudhi/flutter
    • Framework revision 487e6bc91e (4 days ago), 2018-04-03 10:59:12 -0700
    • Engine revision 04f3c6557c
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /Users/yudhi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-23, build-tools 23.0.1
    • ANDROID_HOME = /Users/yudhi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

try to run 'flutter doctor --android-licenses' but only suggesting this
A newer version of the Android SDK is required. To update, run:
/Users/yudhi/Library/Android/sdk/tools/bin/sdkmanager --update

previously flutter works well before upgrade

**Comment by MickeyBadBad** [comment]
same issue here . sdkmanager is already latest update . but still got : `/Users/xxx/Library/Android/sdk/tools/bin/sdkmanager --update`

[✓] Flutter (Channel dev, v0.2.9, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.2.9 at /opt/flutter
    • Framework revision 487e6bc91e (6 days ago), 2018-04-03 10:59:12 -0700
    • Engine revision 04f3c6557c
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mickey/Library/Android/sdk
    • Android NDK at /Users/mickey/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

**Comment by xemox** [comment]
Upgrading to v0.2.10 solved the problem
