### ISSUE TITLE
Firebase Messaging iOS Build Errors

### ISSUE THREAD

**Issue by IhorKlimov** [flutter/flutter#16345]
## Steps to Reproduce

Building from Android Studio, firebase_messaging: 0.2.1. The same bugs appear when trying to build from Xcode
![image](https://user-images.githubusercontent.com/13784275/38464023-3f81f97a-3b0f-11e8-89b2-e0018195e3d2.png)

## Logs

Xcode's output:
↳
    === BUILD TARGET firebase_messaging OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/ihor/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-0.2.1/ios/Classes/FirebaseMessagingPlugin.m:7:
    In file included from /Users/ihor/Documents/Flutter Projects/flutter_tic_tac_toe/ios/Pods/Headers/Private/Firebase/Firebase.h:37:
    In file included from /Users/ihor/Documents/Flutter Projects/flutter_tic_tac_toe/ios/Pods/Headers/Public/FirebaseMessaging/FirebaseMessaging/FirebaseMessaging.h:1:
    Headers/Public/FirebaseMessaging/FirebaseMessaging/FIRMessaging.h:127:41: warning: 'FIRMessagingDelegate' is only available on iOS 10.0 or newer [-Wunguarded-availability]
    @property(nonatomic, weak, nullable) id<FIRMessagingDelegate> remoteMessageDelegate;
                                            ^
    Headers/Public/FirebaseMessaging/FirebaseMessaging/FIRMessaging.h:104:11: note: 'FIRMessagingDelegate' has been explicitly marked partial here
    @protocol FIRMessagingDelegate <NSObject>
              ^
    Headers/Public/FirebaseMessaging/FirebaseMessaging/FIRMessaging.h:122:12: note: annotate 'FIRMessaging' with an availability attribute to silence this warning
    @interface FIRMessaging : NSObject
               ^
    Headers/Public/FirebaseMessaging/FirebaseMessaging/FIRMessaging.h:194:12: warning: parameter 'to' not found in the function declaration [-Wdocumentation]
     *  @param to           A string identifying the receiver of the message. For FCM
               ^~
    Headers/Public/FirebaseMessaging/FirebaseMessaging/FIRMessaging.h:194:12: note: did you mean 'receiver'?
     *  @param to           A string identifying the receiver of the message. For FCM
               ^~
               receiver
    /Users/ihor/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-0.2.1/ios/Classes/FirebaseMessagingPlugin.m:39:30: error: property 'delegate' not found on object of type 'FIRMessaging *'
        [FIRMessaging messaging].delegate = self;
                                 ^
    /Users/ihor/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-0.2.1/ios/Classes/FirebaseMessagingPlugin.m:141:29: error: no visible @interface for 'FIRMessaging' declares the selector 'setAPNSToken:type:'
      [[FIRMessaging messaging] setAPNSToken:deviceToken type:FIRMessagingAPNSTokenTypeSandbox];
       ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings and 2 errors generated.

## Flutter analyze 

No issues found!
Ran in 8.1s

## Flutter Doctor

[✓] Flutter (Channel dev, v0.2.9, on Mac OS X 10.13.3 17D47, locale en-UA)
    • Flutter version 0.2.9 at /Users/ihor/Documents/flutter
    • Framework revision 487e6bc91e (5 days ago), 2018-04-03 10:59:12 -0700
    • Engine revision 04f3c6557c
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/ihor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone • 0fc72c1cae31aba146eeddf659df9e2146af5a9e • ios • iOS 11.2.6

! Doctor found issues in 1 category.

**Comment by leonardop21** [comment]
Solved?
