### ISSUE TITLE
`flutter test` pauses on exceptions in tests on Travis but not locally

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#16350]
Not sure if there's a bug here, but I've hit a a bit of a wall...

I've started creating some automated tests for the debug adapters in Dart Code but found that many of them seem to hang on Travis despite working fine locally. After much debugging I was able to get logging of `flutter test` and observatory from Travis and discovered the problem - on Travis, when a test throws, the debugger is pausing on the exception. This actually seems like reasonable behaviour - however it's different to what I see locally, where the test just fails with no break. The exception pause mode is set the same in both cases.

The test is just the sample stocks one from flutter, but with the text changed so that it'll fail:

```dart
void main() {
  testWidgets('Hello world test', (WidgetTester tester) async {
    hello_world.main();
    await tester.pump();
    expect(find.text("won't find this"), findsOneWidget);
  });
}
```

Here are logs of both `flutter test` and communication with the vm service:

**Local** (does not stop on exception, completes the test run with a failure):

[flutter_test_debugger_stops_on_exception_flutterTest.txt](https://github.com/flutter/flutter/files/1887391/flutter_test_debugger_stops_on_exception_flutterTest.txt)
[flutter_test_debugger_stops_on_exception_observatory.txt](https://github.com/flutter/flutter/files/1887392/flutter_test_debugger_stops_on_exception_observatory.txt)

**Travis**:

[flutter_test_debugger_stops_on_exception_flutterTest.txt](https://github.com/flutter/flutter/files/1887395/flutter_test_debugger_stops_on_exception_flutterTest.txt)
[flutter_test_debugger_stops_on_exception_observatory.txt](https://github.com/flutter/flutter/files/1887396/flutter_test_debugger_stops_on_exception_observatory.txt)

I'll try and dig into it more, but I'm not sure how far I'll get. In both observatory logs, the exception pause mode is set to unhandled and gets a success response.

(cc @devoncarew)

**Comment by DanTup** [comment]
I tried delaying my `resume` request after the `PauseStart` for a while to ensure the responses to all `setLibraryDebuggable` and `setExceptionPauseMode` had finished (I noticed in the logs that we were sending the resume before the debugger settings acknowledgement) but it made no difference, same behaviour (as in, locally, I still don't break on the exception).

**Comment by devoncarew** [comment]
I don't know the reason for the difference, but I suspect that the reason flutter test is running with the service protocol active is to collect coverage information after the run. /cc'ing @cbracken as the coverage expert.

If we're not actually intending to debug the tests, we should likely set the exception pause mode to `None`.

**Comment by DanTup** [comment]
The reason for the VM service active is because I'm running it with `--start-paused` in the debug adapter. I actually think the Travis behaviour is correct and my local Mac is bad. My test fails because I wrote it against the Mac forgetting that it would break on the exception (and it didn't while I was writing the test). I'm trying to figure out why it *doesn't* break on my Mac, so I can fix the test up to expect that (which would then cause it to pass on Travis too).

I'm not sure why it's not breaking on the exception locally though. I'm assuming that it's expected that test failures (failed asserts) will break the debugger if running in debug mode? (the test framework could be catching them, so I wouldn't be surprised if it didn't, but that wouldn't explain why it does break on Travis).

**Comment by DanTup** [comment]
Can anyone confirm whether it's expected for the debugger to break on exceptions/failures on tests? I would expect so, but I don't know if the test framework would be catching the exceptions and stopping them?

**Comment by DanTup** [comment]
Behaviour seems consistent now (maybe recent beta changed things, and maybe I was running on latest code locally when the CI was running beta+master and failing on the beta branch).

So, closing this for now - however, I may open another case about not breaking on exceptions when running tests in the debugger as I think that might not be working as expected.
