### ISSUE TITLE
Question :: Can we load fonts on demand from a network ttf file?

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#16353]
Is it possible to not bundle the font files via pubsepc.yaml file and load them dynamically.
Can NetworkAssetBundle be used for this purpose? Is there an example implementation of such a scenario somewhere?

**Comment by zoechi** [comment]
dup of #15386 ?

**Comment by manujbahl** [comment]
Is there a list of the default fonts supported out of box?

**Comment by manujbahl** [comment]
Is there a possible workaround ?

**Comment by manujbahl** [comment]
@Hixie .. any ideas on a workaround and is there a list of out of box fonts included in the platform

**Comment by Hixie** [comment]
You can ship whatever fonts you want with Flutter and use them. See https://flutter.io/cookbook/design/fonts/

**Comment by Hixie** [comment]
The fonts available by default are whatever fonts ship with the operating system.

Closing as dupe of #15386.

**Comment by srix55** [comment]
Progress at #17910
