### ISSUE TITLE
Flutter has DOS/Windows style line endings

### ISSUE THREAD

**Issue by knuppe** [flutter/flutter#16359]
## Steps to Reproduce

The `/bin/flutter` has DOS/Windows style line endings (CR LF), and unfortunately gives me the following error on Ubuntu:

```bash: ./flutter: /bin/bash^M: bad interpreter: No such file or directory```

Running `dos2unix /bin/flutter` kinda fixes the issue, but it broke other thing, now when I try to run `flutter upgrade` I get the message:

```error: Cannot pull with rebase: You have unstaged changes.```

## Flutter Doctor
```
user@pc:~/flutter/bin$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.21.1)
[✓] Connected devices (1 available)
```

**Comment by zoechi** [comment]
You might have enabled to auto-fix line endings https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

**Comment by knuppe** [comment]
@zoechi thanks for your help!

incredibly the settings was true and I never changed it on my system. :disappointed: 
after reinstalling, everything is working.
