### ISSUE TITLE
Hint Text Alignment issue

### ISSUE THREAD

**Issue by mahmed8003** [flutter/flutter#16366]
There is an issue with Hint Text alignment.
I want right aligned TextField. I set the property to textAlign: TextAlign.end, by doing this actual text is now starting from right side( which is correct) but the hint text still starting from left(it should also be on the right side of text field).

```dart
class _ProfileItem extends StatelessWidget {
  _ProfileItem({this.title, this.hint});

  final String title;
  final String hint;

  @override
  Widget build(BuildContext context) {
    return new Container(
      margin: const EdgeInsets.only(left: 16.0, right: 16.0),
      height: 58.0,
      child: new Column(
        children: <Widget>[
          new Container(
            margin: const EdgeInsets.only(left: 19.0, right: 19.0),
            height: 57.0,
            child: new Row(
              //mainAxisAlignment: MainAxisAlignment.spaceBetween,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                new Text(title,
                    style: new TextStyle(
                        fontWeight: Appearance.fontWeights.semiBold,
                        fontSize: 11.0,
                        letterSpacing: 0.92,
                        color: const Color(0x99000000))),
                new Expanded(
                  child: Padding(
                    padding: const EdgeInsets.only(left: 20.0),
                    child: new TextField(
                      style: new TextStyle(
                        fontWeight: Appearance.fontWeights.light,
                        fontSize: 14.0,
                        letterSpacing: 0.92,
                        color: const Color(0xFF000000),
                      ),
                      decoration: new InputDecoration(
                          hintText: this.hint, border: InputBorder.none),
                      textAlign: TextAlign.end,
                    ),
                  ),
                ),
              ],
            ),
          ),
          new _Divider(),
        ],
      ),
    );
  }
}
```

Hints are starting from left side(which is incorrect, they needs to be start from right side)
![screen shot 2018-04-09 at 2 19 36 pm](https://user-images.githubusercontent.com/1140343/38490054-71e7d52c-3c01-11e8-8fc1-72599aaddf2c.png)

Actual text is starting from right side( it is working properly)
![screen shot 2018-04-09 at 2 20 06 pm](https://user-images.githubusercontent.com/1140343/38490070-7c22876c-3c01-11e8-9652-91f4000df5c5.png)

```
Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5a58b36e36 (4 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264
```

**Comment by ivangodfather** [comment]
I have the same problem, btw, should the hint and the text have the same alignment?

**Comment by aubykhan** [comment]
@ivangodfather yes they should.

**Comment by aubykhan** [comment]
@ivangodfather yes they should. I have a login form that's completely center-aligned so left aligned hint looks very odd while the actual text does get center-aligned.

**Comment by rickyazhari** [comment]
I've faced same issue  either exactly such @aubykhan comment

**Comment by aubykhan** [comment]
Just saw that after I prepared a workaround through a new widget 👍Anyways, my solution can be found [here](https://github.com/aubykhan/flutter-ui-experiments/blob/master/lib/extended_text_field.dart)

**Comment by omartoutounji** [comment]
Is there any way we can do separate alignments for hintText and normalText in the same TextField?
