### ISSUE TITLE
Request for a Firebase Functions plugin

### ISSUE THREAD

**Issue by freewheelnat** [flutter/flutter#16364]
Now, Firebase provides a simple way to call Firebase Functions from apps, with the firebase-functions library (refer https://firebase.google.com/docs/functions/callable#set_up_your_client_development_environment ).

This was added to Firebase Android SDK v12.0.0 and Firebase iOS SDK v4.11.0, released 20th March. 

I know it's new, but it would be great to have a Flutter plugin for it! That would make using Firebase Functions as a backend for apps much easier (removing the need to add our own auth to Firebase Functions).

**Comment by auggernaut** [comment]
This package was just added:
https://pub.dartlang.org/packages/cloud_functions

**Comment by freewheelnat** [comment]
Thanks, exactly what I was after!

**Comment by dileepxdn** [comment]
how to use this package with flutter to send some data/message to that cloud function. The documentation is for this ( https://pub.dartlang.org/packages/cloud_functions ) package is not provided

**Comment by freewheelnat** [comment]
README is a bit slim indeed but example shows how to send parameter to function (tap on "example" tab in link above to view it)

**Comment by kroikie** [comment]
@freewheelnat

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/860. Any further collaboration will be done there.
