### ISSUE TITLE
'Flutter camera plugin' raises error in Memu emulator

### ISSUE THREAD

**Issue by dikatok** [flutter/flutter#16363]
OS: Windows 10
IDE: VS Code + plugins
Emulator: Memu (Android 5.1.1)

I am running the basic camera example from [the readme](https://github.com/flutter/plugins/tree/master/packages/camera) and it was working fine on my phone, but when I deploy the application to memu emulator it throws error as follows and the screen state is blank

`Launching lib\main.dart on SM G955F in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk (24.6MB).
I/FlutterActivityDelegate( 4420): onResume setting current activity to this
I/CameraManagerGlobal( 4420): getCameraService: Reconnecting to camera service
E/MethodChannel#plugins.flutter.io/camera( 4420): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera( 4420): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at java.lang.StringToReal.parseFloat(StringToReal.java:304)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at java.lang.Float.parseFloat(Float.java:306)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.hardware.Camera$Parameters.getFloat(Camera.java:4108)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.hardware.Camera$Parameters.getExposureCompensationStep(Camera.java:3547)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.hardware.camera2.legacy.LegacyMetadataMapper.mapControlAe(LegacyMetadataMapper.java:473)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.hardware.camera2.legacy.LegacyMetadataMapper.mapCharacteristicsFromParameters(LegacyMetadataMapper.java:183)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.hardware.camera2.legacy.LegacyMetadataMapper.createCharacteristics(LegacyMetadataMapper.java:154)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:191)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:182)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:133)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.os.Looper.loop(Looper.java:122)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/MethodChannel#plugins.flutter.io/camera( 4420): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`

can anyone help me or give any insight where to look for the root cause? I am a newbie in flutter and android stuffs XD

ps: basic flutter app works fine on memu

**EDIT**
`flutter-doctor`
[√] Flutter (Channel master, v0.2.10-pre.39, on Microsoft Windows [Version 10.0.16299.334], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.21.1)
[√] Connected devices (1 available)

• No issues found!

**Edit 2**
Stack trace:
`StandardMethodCodec.decodeEnvelope (c:\flutter\packages\flutter\lib\src\services\message_codecs.dart:547)
MethodChannel.invokeMethod (c:\flutter\packages\flutter\lib\src\services\platform_channel.dart:279)
<asynchronous gap> (Unknown Source:0)
availableCameras (c:\Users\holya\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\camera-0.1.2\lib\camera.dart:42)
<asynchronous gap> (Unknown Source:0)
main (c:\Users\holya\Documents\flutter_imrecog_template\lib\main.dart:8)
<asynchronous gap> (Unknown Source:0)
main (c:\Users\holya\Documents\flutter_imrecog_template\lib\main.dart:0)
_Closure.call (dart:core/runtime/libfunction.dart:0)
_startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279)
_Closure.call (dart:core/runtime/libfunction.dart:0)
_RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)`

**Comment by zoechi** [comment]
Sorry for not responding earlier.
Is this still an issue with recent Flutter and plugin versions?
