### ISSUE TITLE
Google SignIn not working with FriendlyChatApp with Firebase Tutorial

### ISSUE THREAD

**Issue by calirails** [flutter/flutter#16365]
## Steps to Reproduce

I am following along with this section of the tutorial: https://codelabs.developers.google.com/codelabs/flutter-firebase/#5

Repro:
1. Run the flutter app (on my device via flutter run -d <device-id>)
2. Type a message
3. Hit send
4. App does not add message to the List of messages and instead fails with the logged output below.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
`Not Applicable`
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.
`Not Applicable`

## Logs
Run your application with `flutter run` and attach all the log output.
`
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type '_Future' is not a subtype of type 'Future<Null>' where
  _Future is from dart:async
  Future is from dart:async
  Null is from dart:core

#0      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart)
<asynchronous suspension>
#1      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:196:28)
#2      _RootZone.run (dart:async/zone.dart:1376:54)
#3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151:18)
#4      _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603:39)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:659:37)
#6      _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342:9)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
`

Run `flutter analyze` and attach any output of that command also.
`
➜  whatschat git:(master) ✗ flutter analyze
Analyzing /Users/calvinnguyen/safezone/projects/mobile/flutter/whatschat...
No issues found!
Ran in 5.3s
`
## Flutter Doctor
Paste the output of running `flutter doctor -v` here.
`
➜  whatschat git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.4, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.4 at /usr/local/Cellar/google-flutter/flutter
    • Framework revision 3352a3fb48 (3 weeks ago), 2018-03-20 19:30:06 +0100
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/calvinnguyen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.1

[✓] Connected devices (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 8.1.0 (API 27) (emulator)
    • CALVIN’s iPhone X         • 59a045705b5301f9f931d1731b52997e48305a4a • ios         • iOS 11.3
    • iPhone 5s                 • 3EA133DB-9AE9-4B42-86C7-06B818C50C51     • ios         • iOS 11.2 (simulator)

! Doctor found issues in 1 category.
`
➜  whatschat git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.4, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.4 at /usr/local/Cellar/google-flutter/flutter
    • Framework revision 3352a3fb48 (3 weeks ago), 2018-03-20 19:30:06 +0100
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/calvinnguyen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.1

[✓] Connected devices (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 8.1.0 (API 27) (emulator)
    • CALVIN’s iPhone X         • 59a045705b5301f9f931d1731b52997e48305a4a • ios         • iOS 11.3
    • iPhone 5s                 • 3EA133DB-9AE9-4B42-86C7-06B818C50C51     • ios         • iOS 11.2 (simulator)

! Doctor found issues in 1 category.
➜  whatschat git:(master) ✗ A
`
> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by calirails** [comment]
I've renamed and attached my single source file: ./lib/main.dart(.txt)
[main.dart.txt](https://github.com/flutter/flutter/files/1890858/main.dart.txt)

I appreciate your help and look forward to continuing this tutorial.

**Comment by jmrboosties** [comment]
Would you mind sharing your gradle files here? i've been trying to get some basic Firebase integration working, and while it runs just fine on iOS, I have a problem with it on Android. Before I make an issue of my own I figured I'd reach out to some people working on the same stuff here.

Specifically, I've found that adding the line `apply plugin: 'com.google.gms.google-services'` to the bottom of the app/build.gradle file causes this to be thrown: 

FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

on compile. It seems like you've gotten past that step, so I thought I'd ask. Thanks!

**Comment by calirails** [comment]
jmrboosties@, I've attached both build.gradle files with their specific paths as an inline comment.
[build.gradle.txt](https://github.com/flutter/flutter/files/1892477/build.gradle.txt)
[build.gradle.txt](https://github.com/flutter/flutter/files/1892481/build.gradle.txt)

Good luck. BTW, did you ever run into the error that I am getting with 'type '_Future' is not a subtype of type 'Future' where _Future is from dart:async ... Future is from dart:async' that suggests some duplicate type definitions?

**Comment by jmrboosties** [comment]
Unfortunately I haven't even been able to get that far yet, ha. Thanks for those files, they look pretty similar to mine save for some more dependencies that I require in gradle, and that I support kotlin while you don't. I'm going to create a new project from scratch and test if that's the issue. I'll keep an eye out for your problem as well, good luck!

**Comment by calirails** [comment]
Debugging async methods in Visual Studio Code has been difficult so I've tried turning all of the Google Sign logic into synchronous code. Still debugging to locate root cause.

In case it helps, here's a list of deprecation warnings on startup, that may or may not be relevant to the runtime exceptions. 
➜  whatschat git:(master) ✗ flutter run -d emulator-5554
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.1s
Running 'gradlew assembleDebug'...
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Configuration 'compile' in project ':firebase_analytics' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_auth' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_database' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_storage' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':google_sign_in' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':image_picker' is deprecated. Use 'implementation' instead.
Built build/app/outputs/apk/debug/app-debug.apk (33.8MB).
Installing build/app/outputs/apk/app.apk...                  4.1s
I/FlutterActivityDelegate( 7730): onResume setting current activity to this
Syncing files to device Android SDK built for x86...         2.3s

**Comment by wmleler** [comment]
The Friendlychat Firebase tutorial has been deprecated because it is not compatible with the new FlutterFire plugins.
