### ISSUE TITLE
Will it be OK to bridge the native image library with Texture?

### ISSUE THREAD

**Issue by korbin-w** [flutter/flutter#16372]
Hi, we are migrating an existing native app to Flutter. 
We have an existing native image library which is well performed, with multiple level caching and image size adaption for CDN.   
We hope to try to use the native image library to Flutter, though the Texture. But I wonder if there is any potential problem.  Will it work?

**Comment by sigurdm** [comment]
I think it would work.

From a FlutterView you can get a `SurfaceTextureEntry` via [`createSurfaceTexture()`](https://docs.flutter.io/javadoc/io/flutter/view/TextureRegistry.html#createSurfaceTexture).

From this you can get an id to send to the dart side and a `SurfaceTexture` to draw in.

Remember to use `SurfaceTexture#setDefaultBufferSize(int width, int height)` to set the backing buffer size.

To draw in the texture you can use a [Surface](https://developer.android.com/reference/android/view/Surface.html) created from the `SurfaceTexture`.
To get hold of a canvas use `lockHardwareCanvas()` followed by `unlockCanvasAndPost(Canvas canvas)`.

On the dart side you can display the texture using the [`Texture`](https://docs.flutter.io/flutter/widgets/Texture-class.html) widget.

Notice that Texture does not know anything about the size of the image, and will stretch it unless you constrain the layout (e.g. with a https://docs.flutter.io/flutter/widgets/SizedBox-class.html) so the native side has to send image information.
