### ISSUE TITLE
Can not start 'examples/fluter_gallery'

### ISSUE THREAD

**Issue by pdescham49** [flutter/flutter#16379]
## Steps to Reproduce
pdescham49@laptopPD:/opt/flutter/examples/flutter_gallery$ cd flutter_gallery/
pdescham49@laptopPD:/opt/flutter/examples/flutter_gallery$ flutter upgrade
Upgrading Flutter from /opt/procrastotron/framework/flutter/flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (7 days ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

Running "flutter packages upgrade" in flutter_gallery...         
Incompatible version constraints on vector_math:
- flutter 0.0.0 depends on version 2.0.5
- flutter_gallery depends on version 2.0.6
pub upgrade failed (1)

## Flutter Doctor

flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_CA.UTF-8)
    • Flutter version 0.2.8 at /opt/procrastotron/framework/flutter/flutter
    • Framework revision b397406561 (7 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/pdescham49/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/pdescham49/android-sdk-linux
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.21.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • SM A520W • 5210439db8e85489 • android-arm64 • Android 7.0 (API 24) (emulator)

! Doctor found issues in 1 category.

**Comment by chjaeggi** [comment]
I have the same issue but it also happens with the hello_world example

**Comment by aadimator** [comment]
yeah, same problem here

**Comment by uinz** [comment]
`git checkout beta`
`flutter upgrade`

hope helps you
