### ISSUE TITLE
flutter crash when start "flutter run"

### ISSUE THREAD

**Issue by viczx** [flutter/flutter#16373]
Hi, i set "flutter run" and suddenly the app crashed and send the log. i am pasting it so you can help me please

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/vic/itgeeks/ios/Runner.xcodeproj -target Runner -showBuildSettings

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
#5      runCheckedSync (package:flutter_tools/src/base/process.dart:280)
#6      XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart:144)
#7      new IOSApp.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:184)
#8      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:274)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:264)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:368)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#16     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#17     new Future.sync (dart:async/future.dart:222)
#18     CommandRunner.run (package:args/command_runner.dart:109)
#19     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#20     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#21     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#22     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     runZoned (dart:async/zone.dart:1501)
#26     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#27     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#28     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#29     main (file:///Users/vic/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.2.3 at /Users/vic/flutter
    • Framework revision 5a58b36e36 (4 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/vic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone X • DBF3EBA2-30D1-4591-B95C-633A864C4FAA • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by KgotsoK** [comment]
Also experiencing the same issue with a newly-cloned flutter_architecture_samples project.


## command

flutter --no-color packages get

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/kgotso/development/flutter_architecture_samples-master/ios/Runner.xcodeproj -target Runner -showBuildSettings

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
#5      runCheckedSync (package:flutter_tools/src/base/process.dart:280)
#6      XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart:141)
#7      CocoaPods.setupPodfile (package:flutter_tools/src/ios/cocoapods.dart:114)
#8      injectPlugins (package:flutter_tools/src/plugins.dart:246)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:62)
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:80)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#19     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#28     new Future.sync (dart:async/future.dart:222)
#29     CommandRunner.run (package:args/command_runner.dart:109)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:168)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1126)
#34     _CustomZone.run (dart:async/zone.dart:1023)
#35     runZoned (dart:async/zone.dart:1501)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:49)
#39     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#40     main (file:///Users/kgotso/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-ZA)
    • Flutter version 0.2.8 at /Users/kgotso/development/flutter
    • Framework revision b397406561 (8 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/kgotso/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Kgotsofatso’s iPhone • 2eac06edf37d8b73afc52b989f6c0bf367a2072a • ios • iOS 11.3

• No issues found!
```

**Comment by KgotsoK** [comment]
Same here on a newly cloned flutter_architecture_samples project.

**Comment by KgotsoK** [comment]
#15301

**Comment by zoechi** [comment]
Sorry for the late response. Is this still an issue in recent Flutter versions?

**Comment by niceguy1** [comment]
indeed, happened to me today in china, my guess is can't async from china since google is blocked by firewall

**Comment by zoechi** [comment]
@niceguy1 can you please add the output of `flutter doctor -v` or does this error as well?

**Comment by niceguy1** [comment]
@zoechi i dont get error on flutter doctor, i get errors with async <asynchronous suspension> same as @viczx , i wonder if he is also in china hmmm

Syncing files to device Android SDK built for x86...
E/flutter ( 4068): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 4068): Unable to load asset: assets/stock1.json
E/flutter ( 4068): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter ( 4068): <asynchronous suspension>
E/flutter ( 4068): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter ( 4068): <asynchronous suspension>

**Comment by zoechi** [comment]
@niceguy1 did you follow https://github.com/flutter/flutter/wiki/Using-Flutter-in-China ?
If `flutter doctor -v` doesn't produce an error, please post the output of `flutter doctor -v`

**Comment by niceguy1** [comment]
yea i did,

`C:\Users\niceguy>flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.547], locale en-US)
    • Flutter version 0.5.1 at C:\src\flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\niceguy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[!] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.`
thank you for asking

**Comment by zoechi** [comment]
@niceguy1 is this still an issue? Should we reopen this issue?

**Comment by niceguy1** [comment]
not for me,  it's ok
thanks for asking @zoechi

**Comment by RayOkaah** [comment]
Yes. It is still an issue unfortunately. 
Been having issues making Futures async calls too. Used to work at some point. Now even my Alertdialogue does not show up.

Heres the code. Is there a fix please?






 [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (16731): FormatException: Unexpected character (at character 1)
E/flutter (16731): <!DOCTYPE html>
E/flutter (16731): ^
E/flutter (16731): 
E/flutter (16731): #0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1362:5)
E/flutter (16731): #1      _ChunkedJsonParser.parseNumber (dart:convert/runtime/libconvert_patch.dart:1258:9)
E/flutter (16731): #2      _ChunkedJsonParser.parse (dart:convert/runtime/libconvert_patch.dart:926:22)
E/flutter (16731): #3      _parseJson (dart:convert/runtime/libconvert_patch.dart:29:10)
E/flutter (16731): #4      JsonDecoder.convert (dart:convert/json.dart:542:36)
E/flutter (16731): #5      JsonCodec.decode (dart:convert/json.dart:169:41)
E/flutter (16731): #6      _PaymentPageState.rechargeMethod (package:rmb/ui/frienddetails/payment_page.dart:117:31)
E/flutter (16731): <asynchronous suspension>
E/flutter (16731): #7      _RootZone.run (dart:async/zone.dart:1376:54)
E/flutter (16731): #8      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151:18)
E/flutter (16731): #9      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603:39)
E/flutter (16731): #10     Future._propagateToListeners (dart:async/future_impl.dart:659:37)
E/flutter (16731): #11     Future._completeError (dart:async/future_impl.dart:485:5)
E/flutter (16731): #12     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
E/flutter (16731): #13     _Completer.completeError (dart:async/future_impl.dart:27:5)
E/flutter (16731): #14     _PaymentPageState.requestMethod (package:rmb/ui/frienddetails/payment_page.dart)
E/flutter (16731): <asynchronous suspension>
E/flutter (16731): #15     _PaymentPageState.initState (package:rmb/ui/frienddetails/payment_page.dart:30:5)
E/flutter (16731): #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
E/flutter (16731): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (16731): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (16731): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (16731): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (16731): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (16731): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (16731): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (16731): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (16731): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (16731): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (16731): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (16731): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (16731): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (16731): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (16731): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (16731): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (16731): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (16731): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (16731): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (16731): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (16731): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (16731): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (16731): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (16731): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (16731): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (16731): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (16731): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (16731): #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
E/flutter (16731): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (16731): #46     Element.inflateWidget (package:fl

**Comment by jashanpj** [comment]
I am having the issue after upgrading the flutter, two projects of mine returns the same error. Which was perfectly worked 1 month ago with my old flutter. Any available solutions?

**Comment by ctykaya** [comment]
I am having the issue for now. Also crash on terminal flutter doctor -v
terminal log 
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x4a00005270
version=2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "macos_x64"
thread=8707, isolate=vm-service(0x7f8c8300b800)
  pc 0x000000010458c963 fp 0x0000700006b5fe40 dart::MarkingVisitorBase<true>::VisitPointers(dart::RawObject**, dart::RawObject**)
  pc 0x000000010458cd53 fp 0x0000700006b5fe80 dart::MarkingVisitorBase<true>::DrainMarkingStack()
  pc 0x000000010458d52e fp 0x0000700006b5ff10 dart::ParallelMarkTask::Run()
  pc 0x00000001043d06dd fp 0x0000700006b5ff40 dart::ThreadPool::Worker::Loop()
  pc 0x00000001043d0510 fp 0x0000700006b5ff70 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x0000000104340181 fp 0x0000700006b5ffb0 dart::ThreadStart(void*)
  pc 0x00007fff71a02e65 fp 0x0000700006b5ffd0 _pthread_start
  pc 0x00007fff719fe83b fp 0x0000700006b5fff0 thread_start
-- End of DumpStackTrace
