### ISSUE TITLE
"Adding all the different types of chips, along with their complex behaviors" regressed missed_frame_build_budget_count

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16378]
"Adding all the different types of chips, along with their complex behaviors" (https://github.com/flutter/flutter/pull/16039) regressed `missed_frame_build_budget_count`.

Please investigate the cause and resolve this issue. Thanks!

(Splitting this off from https://github.com/flutter/flutter/issues/16234)

**Comment by goderbauer** [comment]
Fixed by https://github.com/flutter/flutter/pull/17047.
