### ISSUE TITLE
ImageCache should flush itself when told about memory pressure

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16375]
See also https://github.com/flutter/flutter/issues/13606

**Comment by zoechi** [comment]
Related #3600, #15479

**Comment by maks** [comment]
Is this issue about Flutter app authors not having to manually wire up: https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didHaveMemoryPressure.html 
to call https://api.flutter.dev/flutter/painting/ImageCache/clear.html ?

**Comment by Hixie** [comment]
Yes.
