### ISSUE TITLE
Widget Inspector: Method not found Matrix4.tryInvert (problem with BETA2)

### ISSUE THREAD

**Issue by jatty** [flutter/flutter#16380]
I've just upgraded to Dart BETA2.

Now I get the following errors:

Launching lib/dbtest.dart on iPhone X in debug mode...
compiler message: file:///Users/achim/Install/git/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart:567:37: Error: Method not found: 'Matrix4.tryInvert'.
compiler message:     final Matrix4 inverse = Matrix4.tryInvert(transform);
compiler message:                                     ^^^^^^^^^
compiler message: file:///Users/achim/Install/git/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:2041:39: Error: Method not found: 'Matrix4.tryInvert'.
compiler message:       final Matrix4 inverse = Matrix4.tryInvert(_effectiveTransform);
compiler message:                                       ^^^^^^^^^
compiler message: file:///Users/achim/Install/git/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:2224:37: Error: Method not found: 'Matrix4.tryInvert'.
compiler message:     final Matrix4 inverse = Matrix4.tryInvert(_transform);
compiler message:                                     ^^^^^^^^^
compiler message: file:///Users/achim/Install/git/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:4029:37: Error: Method not found: 'Matrix4.tryInvert'.
compiler message:     final Matrix4 inverse = Matrix4.tryInvert(getCurrentTransform());
compiler message:                                     ^^^^^^^^^

Greetings
Achim

**Comment by jatty** [comment]
Problem is solved when leaving out the "new" command in the program code (dart 1 style).

**Comment by leafpetersen** [comment]
Possibly look for zombie directories in your repo and remove them?  specifically packages/flutter_markdown and examples/hello_services?

https://github.com/flutter/flutter/issues/16438

**Comment by chaim1986** [comment]
hello jatty , can you give a fix example ? thanks..

**Comment by FistMeNaruto** [comment]
I am getting this error when running the default application after initiating a new project

**Comment by zoechi** [comment]
Seems to be fixed. Thanks @jatty for the update.

@chaim1986  @FistMeNaruto 
If this is still an issue for you please create a new issue with a filled out issue template.
