### ISSUE TITLE
TextFormField losing value when changing focus.

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#16391]
![TextFormField loses value](https://media.giphy.com/media/xFkaqTVmjOmRLKYBrc/giphy.gif)

## Steps to Reproduce

The problem is reproducible in a StatefulWidget with the following code:
```Dart
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        body: new Center(
          child: new Form(
            key: _formKey,
            child: new ListView(
              shrinkWrap: true,
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              children: <Widget>[
                new TextFormField(
                  decoration: new InputDecoration(
                      labelText: "TextFormField with TextEditingController",
                      suffixIcon: new Icon(Icons.bug_report)),
                  controller: new TextEditingController(),
                ),
                new TextFormField(
                    obscureText: true,
                    decoration:
                        new InputDecoration(labelText: "obscureText: true"))
              ],
            ),
          ),
        ));
}
```
**If we remove the `TextEditingController` from the first `TextFormField` the issue does not occur.**

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /home/knuppe/flutter
    • Framework revision b397406561 (7 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/knuppe/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/knuppe/Android/Sdk
    • Java binary at: /home/knuppe/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/knuppe/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] VS Code (version 1.21.1)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
I just tried your code and can't reproduce.
Is this issue still relevant?

**Comment by delizondo** [comment]
I had the same problem, and found a solution for that, just define a `controller` variable outside the `build` method.

Should look something like this: 

```
var _myController = TextEditingController();

@override
  Widget build(BuildContext context) {
    return new Scaffold(
        body: new Center(
          child: new Form(
            key: _formKey,
            child: new ListView(
              shrinkWrap: true,
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              children: <Widget>[
                new TextFormField(
                  decoration: new InputDecoration(
                      labelText: "TextFormField with TextEditingController",
                      suffixIcon: new Icon(Icons.bug_report)),
                  controller: _myController,
                ),
                new TextFormField(
                    obscureText: true,
                    decoration:
                        new InputDecoration(labelText: "obscureText: true"))
              ],
            ),
          ),
        ));
}
```

**Comment by jonahwilliams** [comment]
The problem above is that if you create a `new TextEditingController()` on every build, then anything which causes your tree to rebuild will reset your form.  The proper way to use this is to create a `StatefulWidget` which holds your controller. Placing a text editing controller inside of a `StatelessWidget` is only going to cause further subtle bugs.

```dart
class MyForm extends StatefulWidget {
  @override
  State createState() => new MyFormState();
}

class MyFormState extends State<MyForm> {
  final _controller = new TextEditingController();

  @override
  Widget build(BuildContext context) { ... }
}
```

**Comment by Josemboa** [comment]
Solved by using StatefulWidget instead of StatelessWidget. Thank you @jonahwilliams.

**Comment by OnGhostMode** [comment]
Thanks @jonahwilliams  . Issue was solved converting to StatefulWidget

**Comment by Otman404** [comment]
Solved by defining the controller outside the build method

**Comment by Haidar0096** [comment]
The solution mentioned  didn't work for me:

> The problem above is that if you create a `new TextEditingController()` on every build, then anything which causes your tree to rebuild will reset your form. The proper way to use this is to create a `StatefulWidget` which holds your controller. Placing a text editing controller inside of a `StatelessWidget` is only going to cause further subtle bugs.
> 
> ```dart
> class MyForm extends StatefulWidget {
>   @override
>   State createState() => new MyFormState();
> }
> 
> class MyFormState extends State<MyForm> {
>   final _controller = new TextEditingController();
> 
>   @override
>   Widget build(BuildContext context) { ... }
> }
> ```

Here is an [issue](https://github.com/rrousselGit/flutter_hooks/issues/131#issue-606778449) I created a short time ago on flutter_hooks repository thinking that the problem was because of hook widget, but I tried with  StatefulWidget and still same result (result is that TextField is losing its contents when I go to recent apps while I am typing in it, more description and a video in the last comment are available in the link above)

so is there a fix for this?

**Comment by arupnaskarbkp** [comment]
Use initState
