### ISSUE TITLE
Unclear error message when using adding Container class

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#1639]
This code added to a Column:

    Widget _createWorkoutAnimation() {
        return new Flex(
          children: <Widget>[
            new Container(
              decoration: new BoxDecoration(backgroundColor: const Color(0xff990000))
            )
          ]
        );
      }

generates this error:

[Android] I/flutter : a manner consistent with the constraints provided, and, in addition, that
[Android] I/flutter : the getMinIntrinsicWidth(), getMaxIntrinsicWidth(), etc, functions all
[Android] I/flutter : return consistent values within the same constraints.
[Android] I/flutter : If you are not writing your own RenderObject subclass, then this is not
[Android] I/flutter : your fault. Contact support: https://github.com/flutter/flutter/issues/new
[Android] I/flutter : Stack trace:
[Android] I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
[Android] I/flutter : #1      RenderBox.debugDoesMeetConstraints (packages/flutter/src/rendering/box.dart:536)
[Android] I/flutter : #2      RenderBox.size= (packages/flutter/src/rendering/box.dart:450)
[Android] I/flutter : #3      RenderParagraph.performLayout (packages/flutter/src/rendering/paragraph.dart:100)
[Android] I/flutter : #4      RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #5      RenderFlex.performLayout (packages/flutter/src/rendering/flex.dart:380)
[Android] I/flutter : #6      RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #7      RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
[Android] I/flutter : #8      RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #9      RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
[Android] I/flutter : #10     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #11     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
[Android] I/flutter : #12     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #13     MultiChildLayoutDelegate.layoutChild (packages/flutter/src/rendering/custom_layout.dart:47)
[Android] I/flutter : #14     _ScaffoldLayout.performLayout (packages/flutter/src/material/scaffold.dart:64)
[Android] I/flutter : #15     MultiChildLayoutDelegate._callPerformLayout (packages/flutter/src/rendering/custom_layout.dart:82)
[Android] I/flutter : #16     RenderCustomMultiChildLayoutBox.performLayout (packages/flutter/src/rendering/custom_layout.dart:167)
[Android] I/flutter : #17     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #18     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
[Android] I/flutter : #19     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #20     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
[Android] I/flutter : #21     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #22     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
[Android] I/flutter : #23     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
[Android] I/flutter : #24     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
[Android] I/flutter : #25     RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:945)
[Android] I/flutter : #26     RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:923)
[Android] I/flutter : #27     BindingBase&Scheduler&Gesturer&MojoShell&Renderer.beginFrame (packages/flutter/src/rendering/binding.dart:83)
[Android] I/flutter : #28     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:92)
[Android] I/flutter : #29     BindingBase&Scheduler&Gesturer&MojoShell&Renderer._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:77)
[Android] I/flutter : #30     BindingBase&Scheduler.invokeFrameCallback (packages/flutter/src/scheduler/scheduler.dart:270)
[Android] I/flutter : #31     BindingBase&Scheduler.handleBeginFrame (packages/flutter/src/scheduler/scheduler.dart:247)
[Android] I/flutter : #32     _beginFrame (file:///home/travis/build/flutter/buildbot/src/out/android_Release/gen/sky/bindings/hooks.dart:48)

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/1637 should make the message much clearer.

**Comment by Hixie** [comment]
@vlidholt Can you try this now and see if the message is better?
