### ISSUE TITLE
Document the gesture arena

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#164]
<a href="https://github.com/krisgiesing"><img src="https://avatars.githubusercontent.com/u/13855787?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [krisgiesing](https://github.com/krisgiesing)**
_Wednesday Sep 16, 2015 at 23:21 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1201_

----

The principles involved in how gestures interact with each other is novel enough that it probably merits some extra developer documentation.

**Comment by Hixie** [comment]
@krisgiesing  Is http://flutter.io/gestures/ sufficient?

**Comment by krisgiesing** [comment]
I think it's a good introduction to the topic.  We probably also need more detailed API documentation to go with it; for example, you mentioned wanting to document how gestures join the arena, and the sweep semantics. That's only relevant for gesture authors though so it doesn't need to go in the general docs.
