### ISSUE TITLE
How to use native Android UI

### ISSUE THREAD

**Issue by yanhaogoogle** [flutter/flutter#16401]
How to use native Android Ui?

**Comment by naiveaiguy** [comment]
If you mean OEM widgets, Flutter doesn't use them. See [this article](https://medium.com/flutter-io/why-flutter-doesnt-use-oem-widgets-94746e812510) about it. However, for the most part, Flutter widgets (at least on Android) are fairly on par with the OEM widgets. If you absolutely need OEM widgets, I would advise you to use React Native or just write native code.

**Comment by naiveaiguy** [comment]
Bump, this should be closed.
