### ISSUE TITLE
different text linespacing  effect on devices

### ISSUE THREAD

**Issue by Yacumima** [flutter/flutter#16403]
i want set text linespacing by code:
```dart
      return new Text(text,textAlign: TextAlign.start,
          style: new TextStyle(fontSize: 18.0,height: 1.5));
    }
```
but has different effects on two devices, both screen is 1920 * 1080.

![device1](http://gw.alicdn.com/mt/TB1a9atkStYBeNjSspaXXaOOFXa-1080-1920.png)
![device2](http://gw.alicdn.com/mt/TB15OwWkAOWBuNjSsppXXXPgpXa-1080-1920.jpg)

**Comment by zoechi** [comment]
Are you still seeing this?

Please add the output of `flutter doctor -v`
and details about the phone models you were using in the 2 examples above.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by Sp4Rx** [comment]
#48069 Same issue for images too.
