### ISSUE TITLE
Issue from website page Get Started: Install on Windows

### ISSUE THREAD

**Issue by venkatramachandran** [flutter/flutter#16410]
From URL: https://flutter.io/setup-windows/
I followed the instructions to install Flutter and ran the Flutter Console. In the console, on running `flutter doctor`, I get the following error: 
```
'"C:\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an internal or external command,
operable program or batch file.
```
The mentioned directory has a file called `dart.lib` and not `dart.exe`.

What steps am I missing in installing flutter?

**Comment by zoechi** [comment]
I believe this was fixed.
Is this still an issue for you?

**Comment by venkatramachandran** [comment]
Works!

**Comment by zoechi** [comment]
Thanks for the update!

**Comment by timbaert** [comment]
I am having the same problem. I just downloaded flutter from [https://flutter.dev/docs/get-started/install/windows](https://flutter.dev/docs/get-started/install/windows). The version I've downloaded is v1.5.4-hotfix.2. Should I better install a previous version?
