### ISSUE TITLE
Android license detection failure

### ISSUE THREAD

**Issue by jcollins-g** [flutter/flutter#16429]
## Steps to Reproduce

Run flutter doctor -v on @mit-mit's Mac.

flutter doctor -v:
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ✗ Android license status unknown.

mit$ /Users/mit/Library/Android/sdk/tools/bin/sdkmanager
No Java runtime present, requesting install.

JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/" /Users/mit/Library/Android/sdk/tools/bin/sdkmanager --licenses
Warning: File /Users/mit/.android/repositories.cfg could not be loaded.
All SDK package licenses accepted.======] 100% Computing updates...

## Flutter Doctor

@mit-mit : please edit with full flutter doctor -v output.

**Comment by mit-mit** [comment]
Sorry, this no longer repros. I'll reactivate if I get a repro again.
