### ISSUE TITLE
Sensors 0.3.0 plugin not working in iOS 11

### ISSUE THREAD

**Issue by chrystianv** [flutter/flutter#16425]
## Steps to Reproduce
I ran the basic example of the sensor plugin, and it displays the accelerometer, and gyroscope values on Android, however on iOS on both the emulator, and a physical device all values return null.

**Comment by mravn-google** [comment]
@chrystianv Thanks for reporting. Corrected package 0.3.1 published.

**Comment by chrystianv** [comment]
@mravn-google I just tested the version 0.3.1 and it works properly on iOS. Thank you for fixing this problem so quickly.
