### ISSUE TITLE
Support serverTimestampBehavior in cloud_firestore

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#16431]
https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Enums/ServerTimestampBehavior?authuser=1&hl=zh-cn

**Comment by zoechi** [comment]
I think this is now supported https://github.com/flutter/plugins/blob/a6a469a0da9e90b83d957c2c612a994ff1c73adc/packages/cloud_firestore/lib/src/field_value.dart#L41

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/859. Any further collaboration will be done there.
