### ISSUE TITLE
Support for sentinel values in cloud_firestore

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#16437]
https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FieldValue

**Comment by zoechi** [comment]
Looks like this is now supported https://github.com/flutter/plugins/blob/a6a469a0da9e90b83d957c2c612a994ff1c73adc/packages/cloud_firestore/lib/src/field_value.dart

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/854. Any further collaboration will be done there.
