### ISSUE TITLE
Attempt to hide project structure in generated snapshot files

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#1643]
Our generated snapshots currently contain the absolute paths of the files that comprise the snapshot in clear text.  As such, they run the risk of inadvertently leaking internal project structure.

We should come up with a better scheme to use as the canonical names for libraries.  Relative paths are better, though still not ideal since they could still leak internal codenames.

https://github.com/flutter/engine/blob/master/sky/tools/sky_snapshot/loader.cc#L70

**Comment by eseidelGoogle** [comment]
It seems like relative to checkout root makes a lot of sense (to naive me).

I would think that https://github.com/domokit/base/blob/master/files/file_path.h would have a way to make relative paths given a root, but I don't see one.  I suspect @abarth will tell us that there is a dark history there (or that I'm just looking in the wrong place).

**Comment by abarth** [comment]
> I don't see one.

Yeah, I'm sure it's an operation that can't be done correctly.  :)

**Comment by eseidelGoogle** [comment]
customer: mulligan ran into this, but it's not a launch blocker.  I expect other large teams (like Alibaba) may also hit this and want to hide paths from their build infrastructure.

**Comment by eseidelGoogle** [comment]
Does https://github.com/flutter/flutter/wiki/Obfuscating-Dart-Code cover this?

**Comment by mehmetf** [comment]
Yes it does but it comes at the cost of having to hook into a crash reporting system that understands obfuscation. To my knowledge, no such support exists yet.

**Comment by eseidelGoogle** [comment]
It looks like Sentry doesn't support deobfuscation:
https://github.com/getsentry/sentry/issues/2613
But crashlytics does:
https://docs.fabric.io/android/crashlytics/dex-and-proguard.html
(once the more general problem of full, official flutter/dart crashlytics support is solved):
https://github.com/flutter/flutter/issues/14765

**Comment by jonahwilliams** [comment]
It's unclear what this issue is tracking - we have obfuscation support today, and we'll be able to remove even more information with dwarf-stack-traces soon. If mulligan is otherwise satisfied today, I'm closing this issue as the remaining asks are tracked elsewhere
