### ISSUE TITLE
Localization quality of life improvement: DelegateFactory

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#16435]
I was doing a review for some internal localizations in Flutter, and @paolosoares pointed out that the pattern for creating LocalizationsDelegates could be simplified by adding a factory constructor to LocalizationsDelegate.

```dart
class IntlFooLocalizations implements FooLocalizations {
  /*...*/

  static Future<FooLocalizations> load(Locale locale) =>
      new SynchronousFuture(new IntlFooLocalizations());

  static LocalizationsDelegate<FooLocalizations> delegate =
        LocalizationsDelegate<FooLocalizations>.build(
          load: load,
          isSupported: (Locale locale) => true,
          shouldReload: (Locale locale) => false,
        );
```

This is a lot less code than the current pattern:

```dart
class IntlFooLocalizations extends FooLocalizations {
  /*...*/

  static Future<FooLocalizations> load(Locale locale) =>
      new SynchronousFuture(new IntlFooLocalizations());

  static LocalizationsDelegate<FooLocalizations> delegate =
      const _IntlFooLocalizationsDelegate();
}

class _IntlFooLocalizationsDelegate
    extends LocalizationsDelegate<FooLocalizations> {
  const _IntlFooLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<FooLocalizations> load(Locale locale) =>
      IntlFooLocalizations.load(locale);

  @override
  bool shouldReload(LocalizationsDelegate<AutocompleteLocalizations> old) =>
      false;
}
```

The factory pattern is 9 lines of boilerplate, while the current pattern is 21 lines of boilerplate.

### Proposed change
The change in the framework would just be to add the `LocalizationsDelegate<T>.build()` constructor.  Adding this constructor would mean no API breakage.

**Comment by HansMuller** [comment]
I'm going to close this because we'ree considering a different approach, one that would obviate writing the the localizations delegate: https://github.com/flutter/flutter/issues/41437.
