### ISSUE TITLE
Support for FirestoreSettings in cloud_firestore

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#16436]
https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/FirestoreSettings?hl=da

**Comment by ened** [comment]
@collinjackson this seems to be implemented already in 0.9.5, except:
- dispatchQueue (which seems platform specific - and platform internal)
- cacheSizeInBytes

So, the only required addition is `cacheSizeInBytes`?

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/855. Any further collaboration will be done there.
