### ISSUE TITLE
Compiler crash when "new" keyword removed from default app

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/flutter#16440]
## Steps to Reproduce

I accidentally left the "new" keyword out of a line of code while working on an app, and when I rebuilt it, the compiler crashed. I then created a brand new project in IntelliJ, and verified the issue still occurred.

Steps to reproduce:

1) Create a new IntelliJ Flutter project
2) IntelliJ spits out the "increment counter" app.
3) Remove the new keyword from line 67:

        66: // than having to individually change instances of widgets.
        67: return new Scaffold(
        68:   appBar: new AppBar(

4) Trigger a hot reload.
5) The compiler crashes with the message included below.

Interestingly, the compiler does not crash if you leave line 67 alone and instead remove the "new" keyword from line 68. Line 67 is creating the instance that's used as the return value of the method, if that matters. 

## Logs

    Performing hot reload...
    compiler message: Unhandled exception:
    compiler message: Crash when compiling file:///Users/redbrogdon/source/crashtest/lib/main.dart,
    compiler message: at character offset 2160:
    compiler message: lib/main.dart: Internal problem: Unhandled this in defaultTreeNode.
    compiler message: #0      internalProblem (package:front_end/src/fasta/problems.dart:30)
    compiler message: #1      unhandled (package:front_end/src/fasta/problems.dart:43)
    compiler message: #2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
    compiler message: #3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
    compiler message: #4      TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
    compiler message: #5      ThisExpression.accept (package:kernel/ast.dart:3341)
    compiler message: #6      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
    compiler message: #7      PropertyGet.accept (package:kernel/ast.dart:2242)
    compiler message: #8      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
    compiler message: #9      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
    compiler message: #10     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
    compiler message: #11     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
    compiler message: #12     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
    compiler message: #13     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
    compiler message: #14     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
    compiler message: #15     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
    compiler message: #16     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
    compiler message: #17     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
    compiler message: #18     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
    compiler message: #19     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
    compiler message: #20     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
    compiler message: #21     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
    compiler message: #22     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
    compiler message: #23     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
    compiler message: #24     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
    compiler message: #25     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
    compiler message: #26     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
    compiler message: #27     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
    compiler message: #28     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
    compiler message: <asynchronous suspension>
    compiler message: #29     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
    compiler message: <asynchronous suspension>
    compiler message: #30     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
    compiler message: <asynchronous suspension>
    compiler message: #31     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
    compiler message: <asynchronous suspension>
    compiler message: #32     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
    compiler message: #33     _rootRun (dart:async/zone.dart:1126)
    compiler message: #34     _CustomZone.run (dart:async/zone.dart:1023)
    compiler message: #35     runZoned (dart:async/zone.dart:1501)
    compiler message: #36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
    compiler message: #37     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
    compiler message: <asynchronous suspension>
    compiler message: #38     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
    compiler message: <asynchronous suspension>
    compiler message: #39     FrontendCompiler.recompileDelta (package:vm/frontend_server.dart:338)
    compiler message: <asynchronous suspension>
    compiler message: #40     _FlutterFrontendCompiler.recompileDelta (package:frontend_server/server.dart:34)
    compiler message: <asynchronous suspension>
    compiler message: #41     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:468)
    compiler message: <asynchronous suspension>
    compiler message: #42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
    compiler message: #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    compiler message: #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    compiler message: #45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
    compiler message: #46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
    compiler message: #47     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
    compiler message: #48     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
    compiler message: #49     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
    compiler message: #50     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
    compiler message: #51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
    compiler message: #52     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
    compiler message: #53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    compiler message: #54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    compiler message: #55     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
    compiler message: #56     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
    compiler message: #57     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
    compiler message: #58     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
    compiler message: #59     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
    compiler message: #60     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
    compiler message: #61     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
    compiler message: #62     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
    compiler message: #63     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
    compiler message: #64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    compiler message: #65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    compiler message: #66     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
    compiler message: #67     _StreamController._add (dart:async/stream_controller.dart:639)
    compiler message: #68     _StreamController.add (dart:async/stream_controller.dart:585)
    compiler message: #69     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
    compiler message: #70     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
    compiler message: #71     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    compiler message: #72     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    compiler message: #73     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
    compiler message: #74     _StreamController._add (dart:async/stream_controller.dart:639)
    compiler message: #75     _StreamController.add (dart:async/stream_controller.dart:585)
    compiler message: #76     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
    compiler message: #77     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
    compiler message: #78     _microtaskLoop (dart:async/schedule_microtask.dart:41)
    compiler message: #79     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    compiler message: #80     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
    compiler message: #81     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
    compiler message: 
    compiler message: 
    compiler message: #0      internalProblem (package:front_end/src/fasta/problems.dart:30)
    compiler message: #1      unhandled (package:front_end/src/fasta/problems.dart:43)
    compiler message: #2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
    compiler message: #3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
    compiler message: #4      TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
    compiler message: #5      ThisExpression.accept (package:kernel/ast.dart:3341)
    compiler message: #6      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
    compiler message: #7      PropertyGet.accept (package:kernel/ast.dart:2242)
    compiler message: #8      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
    compiler message: #9      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
    compiler message: #10     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
    compiler message: #11     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
    compiler message: #12     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
    compiler message: #13     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
    compiler message: #14     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
    compiler message: #15     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
    compiler message: #16     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
    compiler message: #17     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
    compiler message: #18     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
    compiler message: #19     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
    compiler message: #20     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
    compiler message: #21     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
    compiler message: #22     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
    compiler message: #23     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
    compiler message: #24     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
    compiler message: #25     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
    compiler message: #26     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
    compiler message: #27     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
    compiler message: #28     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
    compiler message: <asynchronous suspension>
    compiler message: #29     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
    compiler message: <asynchronous suspension>
    compiler message: #30     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
    compiler message: <asynchronous suspension>
    compiler message: #31     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
    compiler message: <asynchronous suspension>
    compiler message: #32     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
    compiler message: #33     _rootRun (dart:async/zone.dart:1126)
    compiler message: #34     _CustomZone.run (dart:async/zone.dart:1023)
    compiler message: #35     runZoned (dart:async/zone.dart:1501)
    compiler message: #36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
    compiler message: #37     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
    compiler message: <asynchronous suspension>
    compiler message: #38     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
    compiler message: <asynchronous suspension>
    compiler message: #39     FrontendCompiler.recompileDelta (package:vm/frontend_server.dart:338)
    compiler message: <asynchronous suspension>
    compiler message: #40     _FlutterFrontendCompiler.recompileDelta (package:frontend_server/server.dart:34)
    compiler message: <asynchronous suspension>
    compiler message: #41     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:468)
    compiler message: <asynchronous suspension>
    compiler message: #42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
    compiler message: #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    compiler message: #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    compiler message: #45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
    compiler message: #46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
    compiler message: #47     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
    compiler message: #48     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
    compiler message: #49     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
    compiler message: #50     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
    compiler message: #51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
    compiler message: #52     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
    compiler message: #53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    compiler message: #54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    compiler message: #55     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
    compiler message: #56     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
    compiler message: #57     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
    compiler message: #58     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
    compiler message: #59     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
    compiler message: #60     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
    compiler message: #61     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
    compiler message: #62     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
    compiler message: #63     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
    compiler message: #64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    compiler message: #65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    compiler message: #66     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
    compiler message: #67     _StreamController._add (dart:async/stream_controller.dart:639)
    compiler message: #68     _StreamController.add (dart:async/stream_controller.dart:585)
    compiler message: #69     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
    compiler message: #70     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
    compiler message: #71     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
    compiler message: #72     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
    compiler message: #73     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
    compiler message: #74     _StreamController._add (dart:async/stream_controller.dart:639)
    compiler message: #75     _StreamController.add (dart:async/stream_controller.dart:585)
    compiler message: #76     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
    compiler message: #77     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
    compiler message: #78     _microtaskLoop (dart:async/schedule_microtask.dart:41)
    compiler message: #79     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    compiler message: #80     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
    compiler message: #81     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
    Reloaded 1 of 385 libraries in 902ms.

## Flutter Doctor

    $ flutter doctor
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D102, locale en-US)
    [✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    [✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    [✓] Android Studio (version 3.0)
    [✓] IntelliJ IDEA Community Edition (version 2018.1)
    [✓] VS Code (version 1.20.1)
    [✓] Connected devices (1 available)
    
    • No issues found!

**Comment by aam** [comment]
According to `flutter doctor` this happens on `beta` channel, are you running with explicitly specified `--preview-dart-2` flag?
Have you tried running this on `master`?

**Comment by RedBrogdon** [comment]
Running from the command line with `--preview-dart-2` didn't change the error message. Going into my flutter directory and running `git checkout master`, however, caused the issue to disappear.

Master is ahead of beta, right? So it sounds like this is already fixed?

**Comment by aam** [comment]
> Going into my flutter directory and running git checkout master, however, caused the issue to disappear.

Got you. You could have also done `flutter channel master` :-)

> Master is ahead of beta, right? So it sounds like this is already fixed?

Yes, sounds like it was.

**Comment by RedBrogdon** [comment]
> `flutter channel master`

Mind blown.

**Comment by newfivefour** [comment]
https://github.com/flutter/flutter/issues/16449

I think this is related issue above. 

I ran `flutter channel master`. Then `flutter clean` then `flutter run`. And my issue disappeared too.

**Comment by Hixie** [comment]
Closing per comments above. Thanks for reporting this bug!
