### ISSUE TITLE
`flutter run` fails in incomprehensible ways when run on packages created with very old flutters

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16441]
`flutter run` failed with the following completely useless message:

```
* Error running Gradle:
Exit code 1 from: /Users/ianh/dev/dummy/android/gradlew app:properties:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ianh/dev/dummy/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Please review your Gradle project setup in the android/ folder.
```

**Comment by Hixie** [comment]
This was with a package create with an old version of Flutter. When I tried `flutter create` to create an up to date package, I got told to run `flutter doctor --android-licenses`. Dunno if that's related.

**Comment by Hixie** [comment]
...then that told me to run `/Users/ianh/Library/Android/sdk/tools/bin/sdkmanager --update`.

**Comment by Hixie** [comment]
(The original package was so old that it didn't have a `.metadata` file.)

**Comment by zoechi** [comment]
Related #14974, #12573, #12983, #9827

**Comment by eseidelGoogle** [comment]
I'm not sure we should worry too much about ancient Flutter packages.  We could probably improve our error handling in the tool, but my gut tells me we should just close this?

Is there something still you'd like done here @Hixie?  Otherwise speculatively closing.  Thanks!
