### ISSUE TITLE
Video Player plugin - support file of the application folder

### ISSUE THREAD

**Issue by idofilus** [flutter/flutter#16444]
Recently the plugin updated and `new VideoPlayerController.asset(path)` have been added, is it possible also to add `new VideoPlayerController.file(path)` to access the application's folder of saved videos ?

For example, my application is downloading videos from network and saves it in the application folder. I want to be able to load that video again via the Video Player.

**Comment by mit-mit** [comment]
cc @szakarias

**Comment by szakarias** [comment]
cc @sigurdm

**Comment by sigurdm** [comment]
The video can already be played by using a file URL with the new VideoPlayerController.network('file://$path').

I agree we should probably rename `.network` => `.uri` or somesuch.

**Comment by sigurdm** [comment]
On further consideration, for alignment with [Image](https://docs.flutter.io/flutter/widgets/Image-class.html) we should probably have a `.file()` constructor...

**Comment by idofilus** [comment]
@sigurdm You right, totally my fault of how I used the API .. thanks.

**Comment by zhen1991** [comment]
Hi!
Do you have any idea if we upload a video from assets ,does it play in ios!
for me its working fine on android but not on ios!

**Comment by sigurdm** [comment]
It should work...
If it does not could you open a new issue at https://github.com/flutter/flutter/issues/new , and describe more detailed what you do and what goes wrong.
