### ISSUE TITLE
flutter should not require brew on mac

### ISSUE THREAD

**Issue by championswimmer** [flutter/flutter#16458]
I am assuming I an not the only person in the world who is happy using Macports, and do not require brew. (In fact using both creates conflicts). 

I have been perfectly able to work with Android, iOS, NodeJS development, including Nativescript and React Native over the last 5 years, without ever requiring brew. 

I have been able to install, including ideviceinstaller, ios-deploy and cocoapods without brew. Why does flutter complain about brew, when the required packages are already present.

**Comment by championswimmer** [comment]
For anyone whose Google search brings them here - 

Flutter checks `which brew`

So if you are sure you have `ios-deploy` and `imobiledevice` installed and working, you do not need brew. Flutter does not require `brew` itself, but it requires `brew` to install those packages. 

My dirty fix was to create an empty file `/opt/local/bin/brew` (any directory in your path basically)
Chmod it to 777 or `a+x` 
And voila, Flutter doctor stops complaining.

**Comment by xster** [comment]
This seems sensible. We should check the end rather than the mean. 

Pull requests also welcome :)

**Comment by xster** [comment]
Oops, sorry, didn't notice you already sent us PRs :)
