### ISSUE TITLE
Dartdocs for scrolling refactor

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1645]
I think we need some high level documentation of all the list and viewport classes, including a class hierarchy diagram showing inheritance, mixins, ownership, and who creates whom. It should probably lean on some other documentation explaining the purpose of custom Element subclasses, too.

**Comment by abarth** [comment]
IMHO, there are two pieces to this:

- [ ] Documentation for app developers about how to use these classes effectively.
- [ ] Documentation for framework developers to understand how the pieces all fit together.

I've mostly been working on the first of these, which is what prompted me to remove ScrollableWidgetList recently.

**Comment by Hixie** [comment]
Agreed, though our system is intentionally designed to make it easy for people to slide from one to the other, so there's not as strict a separation as it might seem.

**Comment by sethladd** [comment]
Hi @Hixie is this issue actionable, or do we need to break it out into smaller issues?

**Comment by Hixie** [comment]
It's actionable. We have a list of members needing docs, we just need to walk it.

**Comment by abarth** [comment]
I'm working through these.

**Comment by abarth** [comment]
After https://github.com/flutter/flutter/pull/9735 and https://github.com/flutter/flutter/pull/9731 land, this will be mostly done.  I filed https://github.com/flutter/flutter/issues/9736, https://github.com/flutter/flutter/issues/9737, and https://github.com/flutter/flutter/issues/9739 for the tree remaining pieces.
