### ISSUE TITLE
Video Player plugin - Support HTTP headers

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#16466]
It would be nice to add support for HTTP headers:

```dart
new VideoPlayerController.network("https://example.com/test.mp4",
    headers: {HttpHeaders.AUTHORIZATION: "Basic your_api_token_here"}
)
```

**Comment by freewheelnat** [comment]
Agreed, it would allow us to use the plugin to show videos hosted on our servers (for which we need Authorization header).

**Comment by charafau** [comment]
I can volunteer to implement that..

**Comment by cbenhagen** [comment]
@charafau any news on this?

**Comment by charafau** [comment]
sorry didn't have much time over the week, I got working android implementation, give me some time to get around with objc and ios

**Comment by freewheelnat** [comment]
Any update on this? It's becoming quite critical for my app, but I only need the Android implementation for now, so trying to figure out how to proceed.

**Comment by cbenhagen** [comment]
For mine as well. @charafau may I suggest to open a WIP pull request with what you have got? This way others might help with what is missing or review what is already there.

**Comment by charafau** [comment]
@freewheelnat  @cbenhagen  sorry about keeping you wait, headers on ios seems more complicated than I thought. I created WIP for android

**Comment by freewheelnat** [comment]
FYI, I have found a workaround for my use case, as the url I call for the video accept the https://username:password@url format for authentication, so I don't need to send an authorisation header.

**Comment by cbenhagen** [comment]
Unfortunately this does not work for us.

**Comment by viju85** [comment]
Same here. Is there any update on adding headers support?

**Comment by charafau** [comment]
I must say I failed to implement this for iOS, you'd have to change how current plugin works (or worked at that time)

**Comment by cbenhagen** [comment]
There are two PR trying to fix this issue but on iOS both use a private API (`AVURLAssetHTTPHeaderFieldsKey`). I wonder if that would really get an app rejected. Is there someone on here with good contacts to Apple which could get this approach approved?

**Comment by Yarikk26** [comment]
Our app has been approved by Apple with this fix without a problem.

**Comment by kangwang1988** [comment]
AVURLAssetHTTPHeaderFieldsKey is indeed a risk.

**Comment by pepie** [comment]
Hello. Has there been any progress on this?
I can definitely use a solution for this.

**Comment by JohnGalt1717** [comment]
Same here.

**Comment by morchidnb** [comment]
Hello, any progress in this, it will be very useful ??

**Comment by Appli-chic** [comment]
Any news about it?

**Comment by JarvanMo** [comment]
[Video Player plugin - Support HTTP headers](https://github.com/flutter/plugins/pull/2074) #2074

**Comment by JohnGalt1717** [comment]
Can we get this merged and ready to go?

**Comment by JarvanMo** [comment]
@zoechi hi, can we merge it?

**Comment by JarvanMo** [comment]
@morchidnb @Appli-chic  [PR here](https://github.com/flutter/plugins/pull/2074)

**Comment by JarvanMo** [comment]
Well, take a look at this clean PR.

**Comment by amadeu01** [comment]
the workaround of using this syntax `https://username:password@url` for some URL's didn't work.

**Comment by green-Flamingo** [comment]
Would be really nice to have this PR merged. We need this feature for our application and can't use the workaround.

**Comment by JohnGalt1717** [comment]
@green-Flamingo 100%.  Hope someone makes it a priority and it gets into the basic package.

(And same for PlayReady, Fairplay, Widevine etc. drm)

**Comment by JohnGalt1717** [comment]
Bump

**Comment by sc4v3ng3r** [comment]
Please add support to headers. It's a crucial setting.

**Comment by TRUSTMEIMJEDI** [comment]
Are there any news about merging it to the master need this functionality for my engineer thesis ASAP ?

**Comment by Ladriel** [comment]
I second that idea,iIt would be really handy.

**Comment by alibt** [comment]
i have same issue. any news?

**Comment by cherlow** [comment]
any update on this issue?

**Comment by Yarikk26** [comment]
The proposed solutions use private iOS API. I heard that Apple started rejecting applications based on Electron for this reason. I don't think that they would take a risk to get such a solution merged in master.

**Comment by cherlow** [comment]
> The proposed solutions use private iOS API. I heard that Apple started rejecting applications based on Electron for this reason. I don't think that they would take a risk to get such a solution merged in master.

do you have a workaround for android only...i need it urgently

**Comment by jaysephjw** [comment]
Since supporting arbitrary headers currently seems blocked because of the private iOS API, I have created a separate issue (#61639) and PR (flutter/plugins#2882) for _supporting Cookies only_ as a workaround 🤞

**Comment by JohnGalt1717** [comment]
So the work around is to create a proxy in your REST api, call the proxy to get the m3u8 rewritten to embed the token and then point your video player at the m3u8 file.

**Comment by AhmedNourJamalElDin** [comment]
Any update?

**Comment by jhancock4d** [comment]
This appears to not be working for web despite jsplayer fully supporting it.
