### ISSUE TITLE
Video Controller constructor doesn't allow methods

### ISSUE THREAD

**Issue by vijaykanta** [flutter/flutter#16462]
I am writing a flutter video app with latest Android 3.0 under Ubuntu 12.04 64bit machine. I can almost write any flutter app without much hassle, however I am having trouble getting a video to play. The biggest hurdle is the constructor of this plugin itself. I do the following..

`new VideoPlayerController.network(url)`
or
`new VideoPlayerController.asset(source)`

In both cases the method is marked red indicating the instance doesn't support the routine. I have installed dependency as given in guideline by simply adding 'video_player:' in the dev_dependencies after it didn't work for simply dependencies target.

I don't understand why it doesn't work. Help much appreciated.

**Comment by cbenhagen** [comment]
`VideoPlayerController.network` was added in version 0.4.0. Make sure to get update the package:

`pubspec.yaml`:
```yaml
dependencies:
  video_player: "^0.4.1"
```

Then run `flutter packages upgrade`.

**Comment by zoechi** [comment]
@vijaykanta switch to the latest `dev` channel version, then you'll get a better error message about the conflict in your dependencies. Otherwise just check manually you have the latest versions of dependencies.

**Comment by cbenhagen** [comment]
This might help: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by vijaykanta** [comment]
Thanks, I was looking at that from google search, and switched to dev branch using **flutter channel dev** and did **flutter upgrade**, and this is what I got

`The current Flutter SDK version is 0.0.0-unknown.

Because xxxproject depends on video_player >=0.3.0 which requires Flutter SDK version >=0.1.4
  <2.0.0, version solving failed.`
pub upgrade failed (1)`

**Comment by zoechi** [comment]
As mentioned above
This is what the dependency should look like (with or without quotes)

> video_player: "^0.4.1"

You seem to have

`video_player: 0.4.0`

**Comment by zoechi** [comment]
What do you get for `flutter doctor -v`?
With and without quotes doesn't matter `^` does matter though

**Comment by vijaykanta** [comment]
`flutter doctor -v`

>
[✓] Flutter (Channel beta, v0.0.0-unknown, on Linux, locale en_IN)
    • Flutter version 0.0.0-unknown at /home/vizcreations/development/flutter
    • Framework revision b397406561 (10 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/vizcreations/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.1)
    • Android Studio at /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • SM G900H • 4d0071064f25514b • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
> [✓] Flutter (Channel beta, v0.0.0-unknown, on Linux, locale en_IN)

looks definitely wrong

This is what looks on my system

> ✓] Flutter (Channel dev, v0.2.10, on Mac OS X 10.13.4 17E199, locale en-AT)

I'd try `flutter channel dev`

Also 

> ✗ Android license status unknown.

is an issue

**Comment by vijaykanta** [comment]
I found the problem to be the outdated Ubuntu 12.04, duly updated to 14.04, reinstalled as, flutter and the video player plugin. Flutter doctor gives a proper version for Flutter sdk v0.2.8 and video plays asset clealy, though I got issue from network which I shall post in another thread.

as too looks pretty clean with dart code. Thanks @zoechi and @cbenhagen for your help.
