### ISSUE TITLE
New Feature Request - TabController disable Slide Transition

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter#16474]
## New Feature - TabController disable Slide Transition

Ability to Disable or change the Horizontal Slide Transition when changing Tabs. I would like to switch pages by Fading instead of sliding left or right.

Thank you.

**Comment by HansMuller** [comment]
This feature was also requested by https://github.com/flutter/flutter/issues/18258

**Comment by HansMuller** [comment]
@felipecesar42  reported a workaround here: https://github.com/flutter/flutter/issues/18258#issuecomment-471158333

**Comment by Xgamefactory** [comment]
> @felipecesar42 reported a workaround here: [#18258 (comment)](https://github.com/flutter/flutter/issues/18258#issuecomment-471158333)

this just disables swipe transition not tabbarview page transition.

**Comment by ngoryachev** [comment]
Me too! I have qr code scanner on my first tab page. There is noticeable freeze while camera shutter opens...

**Comment by ariefabubakar** [comment]
Any news on this?

**Comment by EricBichara** [comment]
Any news? Is there a way to disable transition but creating a custom animation with duration = 0?

**Comment by anticafe** [comment]
I think we can use a IndexedStack for tab content instead. Thus, when touch on a tab item, just show corresponding view in Stack.
There is a Medium article here: [Making Bottom Tabbar with Flutter](https://medium.com/fluttervn/making-bottom-tabbar-with-flutter-5ff82e8defe0). Let take a look.

**Comment by yolofy** [comment]
Workaround: You can use a PageView and pagecontroller.jumpToPage for this.

```
 PageController _pageController;

 @override
  void initState() {
    super.initState();
    _pageController = PageController(initialPage: initialTab);
  }

  @override
  Widget build(BuildContext context) {
   var pages = [Container(child: /* TODO */), Container(child: /* TODO */), Container(child: /* TODO */)];

    var pageView = PageView(
      controller: _pageController,
      physics: NeverScrollableScrollPhysics(),
      children: pages,
    );

    var bottomNav = BottomNavigationBar(
      onTap: (tabIndex) {
        _pageController.jumpToPage(tabIndex);
      },
      items: [
        BottomNavigationBarItem(/* TODO */),
        BottomNavigationBarItem(/* TODO */),
        BottomNavigationBarItem(/* TODO */),
      ],
      );

    return Scaffold(
        body: pageView,
        bottomNavigationBar: bottomNav,
        );   
  }
```

**Comment by Sun3** [comment]
I am also still looking for a response and update.

**Comment by Blaeriz** [comment]
I am also still looking for a response and update.

**Comment by darkstarx** [comment]
> @felipecesar42 reported a workaround here: [#18258 (comment)](https://github.com/flutter/flutter/issues/18258#issuecomment-471158333)

This not working. I can't manually scroll the page but it still animates on switching the current tab.

**Comment by Hasankanso** [comment]
any news?

**Comment by crsmillan** [comment]
any news?

**Comment by DanielYK** [comment]
any news ?

**Comment by miguelfs** [comment]
any news?

**Comment by miguelfs** [comment]
any news?

**Comment by iulian0512** [comment]
no animation helps when dealing with ios jank

**Comment by markusaksli-nc** [comment]
Fixed by https://github.com/flutter/flutter/pull/91987
