### ISSUE TITLE
[Flutter] The default Firebase app has not yet been configured. Error with adding on ios 

### ISSUE THREAD

**Issue by arpitgoyal2008** [flutter/flutter#16472]
Hi,

I am getting following issue while adding Firebase to iOS.

Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...
Starting Xcode build...
Xcode build done.
[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
[Firebase/Analytics][I-ACS005000] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb
[Firebase/Messaging][I-IID001001] FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
[Firebase/Analytics][I-ACS023007] Firebase Analytics v.3900000 started
[Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[Firebase/Analytics][I-ACS003007] Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
[Firebase/Analytics][I-ACS032003] iAd framework is not linked. Search Ad Attribution Reporter is disabled.
[Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
Syncing files to device iPhone X...

## Info.plist

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>abc</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>reverse_client_id</string>
				<string>xyz.pkgname</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
```
## Flutter Doctor

[✓] Flutter (Channel master, v0.2.11-pre.26, on Mac OS X 10.12.6 16G1212, locale en-IN)
    • Flutter version 0.2.11-pre.26 at /Users/arpitgoyal/Documents/flutter
    • Framework revision 5cd825a8dc (2 hours ago), 2018-04-11 12:01:28 -0700
    • Engine revision ed303c628f
    • Dart version 2.0.0-dev.47.0.flutter-23ae4fa098

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/arpitgoyal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • iPhone X • 66197942-93D1-49FF-949E-26E4D0B3C68F • ios • iOS 11.2 (simulator)

**Comment by anilcancakir** [comment]
I have same problem. The database doesn't work because the database can't connect to the firebase app. Then, I looked the plugin and i found the firebase app can configure in dart. I done it my source and the database works but this warning continues.

The sample
```dart
FirebaseApp.configure(name: 'app', options: new FirebaseOptions(
  googleAppID: 'App ID',
  apiKey: 'Web API Key',
  projectID: 'Project ID'
))
```

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by dark-chocolate** [comment]
I'm having this issue. I am using Firebase Realtime database and Firebase auth. Did anyone find any solution?

I was watching this video (at [4:16](https://youtu.be/iMkifTEaefE?t=256)) and I failed to find `AppDelegate.swift` file. I can see `AppDelegate.m` file in Runner folder but using `import` and `FIRApp.configure()` shows error in this file. 

`Unknown type name import
`
`Use of undeclared identifier FIRApp
`

PS: I am coming from Native Android Development (Java). Don't have any experience in iOS.

**Comment by zoechi** [comment]
If you use `final db = FirebaseDatabase(FirebaseApp('MyApp'));` instance instead of `final db = FirebaseDatabase.instance;` then this message should go away.

**Comment by dark-chocolate** [comment]
Thanks @zoechi, actually I followed a tutorial from YouTube and that guy was using windows, so he just said that for iOS, we need to place the `GoogleServices-info.plist` file at x place and it was the reason for the error. 

Now that I have put the file under Runner and without using anything like `import` or` FIRApp.configure()`  I could successfully run the app in iOS simulator. Many thanks for all your help. I really appreciate your time.
