### ISSUE TITLE
Changing PageView scrollDirection doesn't update controller.position.viewportDimension

### ISSUE THREAD

**Issue by joshwagoner** [flutter/flutter#16481]
If I change the scrollDirection of a PageView from Axis.horizontal to Axis.vertical (or vice versa) it no longer stops in the correct positions for the page size when scrolling. I created a gist of a simple repro here: 

https://gist.github.com/joshwagoner/acab3788949639eca29f4a1663d8076e

It appears that the viewportDimension is not being recalculated for the new axis direction and it uses the size from the initial scrollDirection set on the PageView.

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue in recent Flutter versions?

**Comment by jimlywu** [comment]
> If I change the scrollDirection of a PageView from Axis.horizontal to Axis.vertical (or vice versa) it no longer stops in the correct positions for the page size when scrolling. I created a gist of a simple repro here:
> 
> https://gist.github.com/joshwagoner/acab3788949639eca29f4a1663d8076e
> 
> It appears that the viewportDimension is not being recalculated for the new axis direction and it uses the size from the initial scrollDirection set on the PageView.

add following code to solve:
`
Size _screenSize = MediaQuery.of(context).size;
void _changeAxis() {
    setState(() {
      _scrollDirection =
          _scrollDirection == Axis.vertical ? Axis.horizontal : Axis.vertical;
    // recalculate viewport dimension
      _pageController.position.applyViewportDimension(Axis.vertical ? _screenSize.height : _screenSize.width);
    });
  }`
