### ISSUE TITLE
Need a way to cache channel messages from Android services

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#16489]
The ID service, etc for Firebase Messaging will be registered in the Android manifest and will respond (`onTokenRefresh()`, etc) before the Flutter lifecycle has an opportunity to execute. Any messages sent to Flutter from the service will therefore be lost (e.g: notify flutter that the token has changed). This means implementing logic on the native side to deal with these situations.

It would be great if there was a way to cache the channel messages and restore them on application start so you don't need to resort to other mechanisms.

cc/ @xster

**Comment by goderbauer** [comment]
@gaaclarke I seem to remember that we do cache message now?

**Comment by gaaclarke** [comment]
Yep, channel buffers hold messages destined for the framework from the host API: https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html

By default the buffers are just one size, but they can be increased.
