### ISSUE TITLE
About AutomaticKeepAliveClientMixin's keepAlive

### ISSUE THREAD

**Issue by IT-crackpot** [flutter/flutter#16499]
In channel master, when I use AutomaticKeepAliveClientMixin, it can work.
but in channel bate, it can't work

**Comment by xster** [comment]
@goderbauer may have just fixed this

**Comment by goderbauer** [comment]
Yeah, I just submitted a fix to master for this: https://github.com/flutter/flutter/pull/16445

It will take a little time until it's available on the beta channel.
