### ISSUE TITLE
We should pump one frame at app startup even if the screen is off

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#165]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Sep 17, 2015 at 15:29 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1206_

----

Authors are rarely going to test their apps with the screen off, but if we don't pump their app with the screen off, their App widget isn't going to be synced, their RenderObject tree isn't going to be laid out, and so forth, so if they try to do anything using the tree, it'll fail.

So we should either pump one frame to ensure that the app is always more or less in the same state, or we should document patterns and anti-patterns for how to do things that depend on app state and render tree layout, e.g. don't use a timer but use an animation frame callback, etc.

**Comment by abarth** [comment]
We now pump a single frame synchronously inside `runApp`.

**Comment by abarth** [comment]
See https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/binding.dart#L81
