### ISSUE TITLE
Document flutter engine Java/ObjC shell classes

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#16503]
Class-level Java/ObjC doc of FlutterView and friends is patchy, and it is not immediately clear what the role of each class is, or what options exist for composing them into a working shell for different situations.

**Comment by cbracken** [comment]
We've made a heap of progress on this over the last year but things are still pretty scanty. I'm assigning to myself (a) to verify our current coverage and (b) so we can add some form of infra to prevent regressions.

* [Objective-C docs](https://api.flutter.dev/objcdoc/index.html)
* [Java docs](https://api.flutter.dev/javadoc/)

**Comment by pedromassangocode** [comment]
The API docs seems to have information enough now. @cbracken does the actual documentation satisfy this issue?

**Comment by cbracken** [comment]
I believe we can close this now. We've done a ton of work in the last year to improve things here, particularly @gaaclarke
