### ISSUE TITLE
TextInputFormatter doesn't works on iOS

### ISSUE THREAD

**Issue by alexandresoler** [flutter/flutter#16506]
## Steps to Reproduce

TextInputFormatter encounter a bug on iOS.
You can reproduce it easily with the "Flutter Gallery", play with the phone number TextField on the "Text fields" demo.

I've tried to implement my TextInputFormatter and I encounter the same problem (not present on Android platform)

**Comment by SeniorIvan** [comment]
why is this still not fixed?

**Comment by goderbauer** [comment]
What is the problem here? Can you please provide additional information? What is your expected behavior? What's the behavior you were seeing?

**Comment by xster** [comment]
Duping into #12347
