### ISSUE TITLE
`flutter stop` no longer stops apps running on android

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1651]
Doing a `flutter start` and a `flutter stop` does not stop the app on android. `stop` is sending in:

```
adb shell am force-stop org.domokit.sky.shell
```

Using adb to find the running activities, and instead passing in:

```
adb shell am force-stop com.example.flutter_sunflower
```

does shut down the app. Perhaps `start` is pulling the activity name from AndroidManifest.xml, and `stop` is not?

**Comment by abarth** [comment]
@mpcomplete
