### ISSUE TITLE
How Do I hide statusbar?

### ISSUE THREAD

**Issue by rffanlab** [flutter/flutter#16514]
I could not found anything in doc?

**Comment by zoechi** [comment]
I hope this answers your question https://stackoverflow.com/questions/43877288/hide-android-status-bar-on-flutter-app
Sorry for the late response.

**Comment by rffanlab** [comment]
It is not..I could not find this function.

**Comment by zoechi** [comment]
You can find it in https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/system_chrome.dart#L270

The online docs https://docs.flutter.io/flutter/services/SystemChrome/setEnabledSystemUIOverlays.html (the SO answer links to these docs as well)

Add the import

```dart
import 'package:flutter/services.dart';
```
to make it available.

**Comment by milanpatel18** [comment]
SystemChrome.setEnabledSystemUIOverlays([]) should do what you want.

You can bring it back with SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values).

Import it using

import 'package:flutter/services.dart';

[Credit Goes To](https://icetutor.com/question/hide-android-status-bar-on-flutter-app/)

**Comment by fathah** [comment]
How to hide only for a specific page

**Comment by Harshit221** [comment]
> How to hide only for a specific page

To hide statusbar: SystemChrome.setEnabledSystemUIOverlays([]);
To bring back to default: SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);

SystemChrome.setEnabledSystemUIOverlays function let you to choose which ui overlay you want to display, passing empty list will hide every overlay and SystemUiOverlay.values is default list of overlays

**Comment by fathah** [comment]
> > How to hide only for a specific page
> 
> To hide statusbar: SystemChrome.setEnabledSystemUIOverlays([]);
> To bring back to default: SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
> 
> SystemChrome.setEnabledSystemUIOverlays function let you to choose which ui overlay you want to display, passing empty list will hide every overlay and SystemUiOverlay.values is default list of overlays

But if I add this it is applying for all routes. I need to do this for particular route (Like being full-page view in reading mode) and not to all routes(Activities in Android)

**Comment by Harshit221** [comment]
> > > How to hide only for a specific page
> > 
> > To hide statusbar: SystemChrome.setEnabledSystemUIOverlays([]);
> > To bring back to default: SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
> > 
> > SystemChrome.setEnabledSystemUIOverlays function let you to choose which ui overlay you want to display, passing empty list will hide every overlay and SystemUiOverlay.values is default list of overlays
> 
> But if I add this it is applying for all routes. I need to do this for particular route (Like being full-page view in reading mode) and not to all routes(Activities in Android)

When you push content, before that call SystemChrome.setEnabledSystemUIOverlays([]);

Similarly when you pop your full screen view, before that call SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);

**Comment by sumanthnani10** [comment]
> How to hide only for a specific page

@override
  void initState() {
    SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
    super.initState();
  }

  @override
  void dispose() {
    SystemChrome.setEnabledSystemUIOverlays(
        [SystemUiOverlay.top, SystemUiOverlay.bottom]);
    super.dispose();
  }

**Comment by fathah** [comment]
> > How to hide only for a specific page
> 
> @override
> void initState() {
> SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
> super.initState();
> }
> 
> @override
> void dispose() {
> SystemChrome.setEnabledSystemUIOverlays(
> [SystemUiOverlay.top, SystemUiOverlay.bottom]);
> super.dispose();
> }

Awesome

**Comment by fathah** [comment]
> > > > How to hide only for a specific page
> > > 
> > > 
> > > To hide statusbar: SystemChrome.setEnabledSystemUIOverlays([]);
> > > To bring back to default: SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
> > > SystemChrome.setEnabledSystemUIOverlays function let you to choose which ui overlay you want to display, passing empty list will hide every overlay and SystemUiOverlay.values is default list of overlays
> > 
> > 
> > But if I add this it is applying for all routes. I need to do this for particular route (Like being full-page view in reading mode) and not to all routes(Activities in Android)
> 
> When you push content, before that call SystemChrome.setEnabledSystemUIOverlays([]);
> 
> Similarly when you pop your full screen view, before that call SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);

Yeah.. That works great. Thanks
