### ISSUE TITLE
Flutter WebView do not work on Android

### ISSUE THREAD

**Issue by vascoV** [flutter/flutter#16511]
Hello,

I have created a list view and whenever you click on any of the tiles a web view appears, on IOS devices works but I am getting an error that `com.package/com.apptreesoftware.flutterwebview.WebViewActivity}; have you declared this activity in your AndroidManifest.xml?, null)` on Android see the following image:
![screen shot 2018-04-12 at 5 24 32 pm](https://user-images.githubusercontent.com/15817701/38683896-1f7de812-3e77-11e8-8a94-83dfd58dd5aa.png)
 I am using this plugin for the web view -> https://pub.dartlang.org/packages/flutter_web_view#-example-tab-

**Comment by EpicEricEE** [comment]
It looks like you did not add the activity to the manifest file. As stated on the readme page [here](https://pub.dartlang.org/packages/flutter_web_view#-readme-tab-), you have to add the following activity to the ``AndroidManifest.xml``:

```xml
<activity android:name="com.apptreesoftware.flutterwebview.WebViewActivity">
</activity>
```

**Comment by vascoV** [comment]
oww, thanks!! Didn't notice it 0:)
