### ISSUE TITLE
escape reserved keywords in the generated project

### ISSUE THREAD

**Issue by championswimmer** [flutter/flutter#16521]
`in` is a reserved keyword in kotlin, and thus we have to write package names like this - 

```
pagkage `in`.championswimmer.myapp
```

(Taking my example here, as I usually use 'in.championswimmer' as company domain.

Android Studio escapes it when generating default project. Flutter does not. 

I believe other kotlin keywords need to be escaped similarly from the package name

List of keywords to escape by language

### Kotlin  

- [ ] `in`
- [ ] `when`

**Comment by fmatosqg** [comment]
when is also a keyword that brings in issues wherever used as a method name, usually found in Mockito. It probably has the same issues.

**Comment by championswimmer** [comment]
@fmatosqg I am making a list inside OP

**Comment by championswimmer** [comment]
@xster turning this into a tracking issue so we can list all reserved keywords here and fix them

**Comment by championswimmer** [comment]
Update: I am not having any time immediately to contribute with a PR, but anyone coming to look at this issue : 

https://github.com/flutter/flutter/blob/797b39e9b26b08fe847b95cec7229bdb179e1109/packages/flutter_tools/lib/src/template.dart#L88 
This is where the identifier is created.

**Comment by noiissyboy** [comment]
The problem persist when i try to create flutter project with `in`.example domain extention using android studio or windows poweshell terminal. i get it working when i created the project with same command with backticks in VS code terminal (MINGW64). I could able to run the flutter app.

**Comment by deepakkj6** [comment]
I too faced a similar issue like @noiissyboy when I am running in the system terminal but its working fine when I am creating the same application using the following command 'flutter create --org=`in`.dreamlogic.vamor --androidx vamor' in VSCode terminal. My system configuration is Ubuntu 18.x.x

**Comment by Lav-Hinsu** [comment]
Is there any fix/update yet? was just about to file this issue. maybe someone should do a feature request?
