### ISSUE TITLE
Possible leaks on font collection

### ISSUE THREAD

**Issue by xster** [flutter/flutter#16526]
![screen shot 2018-04-12 at 12 28 36 pm](https://user-images.githubusercontent.com/156888/38699836-1313d2e0-3e4e-11e8-86f1-48efd9490725.png)

Playing around in the Gallery for a minute resulted in a few thousand leaks reported from Xcode Instruments. 

They seem to all have 
```
SkFontMgr::matchFamily(char const*) const ../../third_party/skia/src/core/SkFontMgr.cpp:107
txt::FontCollection::GetMinikinFontCollectionForFamily(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ../../flutter/third_party/txt/src/txt/font_collection.cc:103
```
in common. 

Trace is at https://drive.google.com/drive/folders/1Sa-6BHO6LSlGe69msuJHUsBohQRtUzzo

@cbracken @jason-simmons

**Comment by eseidelGoogle** [comment]
@yjbanov Do we have any testing in place to make sure we prevent leaks like this in the future?

**Comment by yjbanov** [comment]
We do have some memory benchmarks. Theoretically, a new memory leak would bump the numbers if it were exercised. The benchmarks don't know anything so I'm guessing we're not exercising this part of the system in the benchmark.
