### ISSUE TITLE
iOS: error when running flutter start (Error listening to iPhone 6s logs.)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1652]
```
flutter start --checked • flutter logs
testme/ • checked mode • debug
Starting lib/main.dart on iPhone 6s...
Unable to connect to the observatory (port 8181).
Logging for iPhone 6s...
Error listening to iPhone 6s logs.
exited with code 1
```

```
~/flutter/testme $ flutter --version
Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: 01a5b83766e827b0f2bfc96652f4fcae30e329c8 (12 hours ago)
engine revision : 3f1bde71969d9da119767e479e11fc22948e3bc2
```

**Comment by devoncarew** [comment]
We can remove the error, but adding support for running in debug mode is blocked on https://github.com/flutter/flutter/issues/1511.

**Comment by sethladd** [comment]
Is it a warning? I'd figure an error is "the app failed to run", but this is "head's up, something probably isn't right".

"Warning: Unable to debug app: Unable to connect to observatory (port 8181)."

**Comment by chinmaygarde** [comment]
I think this should be fixed after https://github.com/flutter/flutter/pull/1699 but I am not sure if there something else in the tooling that needs to be wired up.

**Comment by devoncarew** [comment]
I think all that's left is this line:

> Error listening to iPhone 6s logs.

I'll re-title this issue.

**Comment by sethladd** [comment]
Should be fixed.
