### ISSUE TITLE
Use a more real-world JSON structure for tutorial

### ISSUE THREAD

**Issue by troyibm** [flutter/flutter#16533]
From URL: https://flutter.io/json/

1% of JSON is just a flat `key:value` structure, most have objects within the JSON.  While the example is easily understood, it could be more useful if the JSON structure you use for the example has a more structure to it.

Please revamp the tutorial to have JSON structure like
```json
{
  "name": "John Smith",
  "email": "john@example.com",
  "address": {
     "city": "Austin",
     "state": "Texas",
     "street": "106 Burnet Road"
   }
}
```

Also providing dart classes for standard JSON structures would help, but these could be available as I haven't looked around at all.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2260](https://github.com/flutter/website/issues/2260) via [**ZenHub**](https://www.zenhub.com/)
