### ISSUE TITLE
Remove spurious "default app not configured" warning from Flutterfire iOS logs

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#16534]
## Steps to Reproduce

Flutterfire iOS apps have this message in their logs:

```
"4.8.1 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization.
```

This message occurs because they are checking if the defaultApp is configured yet.

We should switch from using `defaultApp` to `appNamed:@"__FIRAPP_DEFAULT"`

See the discussion on firebase/firebase-ios-sdk#1003

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/853. Any further collaboration will be done there.
