### ISSUE TITLE
Crashed when trying to upgade

### ISSUE THREAD

**Issue by kentonraiford** [flutter/flutter#16536]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by tvolkert** [comment]
@kentonraiford can you attach the logs in verbose mode including the command you ran?

**Comment by kentonraiford** [comment]
Hi Todd,

I deleted it and re-downloaded. It worked again.

Kenton

This electronic message has been marked confidential. Electronic communication is very serious, all emails and the messages contained within are legal documents. In forwarding or sharing the message without permission from the sender, the recipient acknowledges that the sender reserves their right to legal action.

CONFIDENTIALITY NOTICE: This email message is for the sole use of the intended recipient(s) and may contain confidential and/or privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message. The contents of this email, and any attachments are the intellectual property of Kenton. D. Raiford. Any release, or distribution without prior consent from Kenton D. Raiford is an act of copyright infringement.

**Comment by tvolkert** [comment]
Sounds good.  I'm gonna close this issue then.  If you encounter any more issues, please feel free to file again.
