### ISSUE TITLE
Would like to be able to delay plugin load

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#16539]
A team recently approached us using Flutter in an add-to-app scenerio on iOS and asked for it to be possible to delay plugin initialization until after App startup.

This team cares a lot about app launch time, and their FlutterView is not always displayed in the app, so they would prefer to not initialize plugins at launch time.

cc @mravn-google @collinjackson

**Comment by collinjackson** [comment]
I think most plugins should work fine if you call `registerWithRegistry` at some point after `onCreate`. This isn't something I've personally experimented with though, so there may be rough edges.
