### ISSUE TITLE
No RouteAware callback is invoked when route is removed via NavigatorState.pushNamedAndRemoveUntil

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#16547]
I would expect that one of the methods in `RouteAware` would be called when a route is removed using `NavigatorState.pushNamedAndRemoveUntil`. However, when I follow the example in the `RouteObserver` docs to make a widget aware of when the route containing it is removed, no callback is invoked. 

My guess is the fix here is to make `RouteAware` have a callback for `didRemove`, which is already present in `RouteObserver`?

**Comment by Hixie** [comment]
`ModalRoute.of(context).isCurrent` should tell you if you're top, and in theory should get called when that changes. (This may not currently be working.)

**Comment by alanrussian** [comment]
Oh didn't know that existed. Will try tomorrow. Thanks!

**Comment by alanrussian** [comment]
That works, thanks! I'll remove the customer label. I still think this would be nice to fix for future users, though.

**Comment by zinwalin** [comment]
ModalRoute.of(context).isCurrent just works, thanks a lot.

**Comment by zoechi** [comment]
Can this issue be closed?

**Comment by alanrussian** [comment]
While it may be possible to work around this, I think the issue should remain open. Future users of `RouteAware` are likely to run into this.

**Comment by alanrussian** [comment]
FYI one of my teammates ran into this again. If this cannot be fixed soon, can the `RouteAware` documentation be updated to mention it doesn't support a route becoming visible due to removals?

**Comment by TahaTesser** [comment]
Hi @alanrussian 
Are you still experiencing this issue? 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
