### ISSUE TITLE
flutter is has bug on dart2 ,when less of new key word

### ISSUE THREAD

**Issue by bravekingzhang** [flutter/flutter#16549]
![image](https://user-images.githubusercontent.com/4476322/38713877-2aa1691e-3f06-11e8-8841-9e21e3c85315.png)

**Comment by bravekingzhang** [comment]
**we  should add new key word manually to make flutter run ok.**

I'm sorry, my english is very poor ,I wish you understand my question.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v` and the error you get (if you get one).

**Comment by bravekingzhang** [comment]
I think my  Android toolchain  is **OK**

**Comment by bravekingzhang** [comment]
![image](https://user-images.githubusercontent.com/4476322/38726432-bca0011e-3f3c-11e8-9f7b-9bdc94a65a63.png)
I think ,the error message is not related to my problem, As you can see what I mentioned above。
to solve this problem ,i just add new keyword like this

![image](https://user-images.githubusercontent.com/4476322/38726585-275d43c2-3f3d-11e8-9d5f-bb66d7d50af4.png)

then ,it will be run ok .

this is my project : https://github.com/bravekingzhang/flutter_me

My guess this problem is  related to dart2 SDK, your paper mentioned that ，**when dart2 ,we can omit new keyword** ,but it is not the same as what I am expect.

so ,I think the dart2  compile tool is not match dart2 build tool.since my editor show no problem, well, when build ,It goes error. do you think so?

**Comment by MichaelSowah** [comment]
@bravekingzhang 
according to this article https://medium.com/flutter-io/https-medium-com-flutter-io-announcing-flutters-beta-2-c85ba1557d5e
optional new/const is not ready yet for use

**Comment by zoechi** [comment]
Could be a dup of #16182

**Comment by tvolkert** [comment]
Not a dup of #16182.  As @MichaelSowah points out, optional new/const is known to still be incomplete.  There's a dup issue in dart-lang/sdk, but I'm on my phone right now, so I can't look it up.

**Comment by tvolkert** [comment]
Likely a dup of https://github.com/dart-lang/sdk/issues/32798

@bravekingzhang if you switch to the `master` channel (`flutter channel master && flutter upgrade`), does this still happen?
