### ISSUE TITLE
Running from Atom triggers analysis

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1654]
Running my app via Atom (via Cmd-R) triggers analysis. I see the gear spinning shortly after I hit Cmd-R. Not sure why, but this might be an unnecessary thing to do.

**Comment by devoncarew** [comment]
It's something in the iOS / iOS Simulator build (when running start). The pubspec.lock file is getting touched - so I'd guess somewhere we're running pub get or something similar. This also causes the next flutter start for an android device to rebuild the apk.

**Comment by sethladd** [comment]
Yikes. Thanks for the diagnosis. Definitely want to fix this then :)

**Comment by devoncarew** [comment]
PR here: https://github.com/flutter/engine/pull/2361 :)

**Comment by devoncarew** [comment]
The fix will be in the next engine roll. People will need to delete the ios/ dir and re-gen with `flutter ios --init`.

**Comment by sethladd** [comment]
Thanks!
