### ISSUE TITLE
Issue from website page Get Started: Configure Editor

### ISSUE THREAD

**Issue by arorayogita** [flutter/flutter#16554]
From URL: https://flutter.io/get-started/editor/

I have installed both plugins dart and flutter and but i am not able to create new flutter project from android studio

**Comment by zoechi** [comment]
> not able to create new flutter project

Means what exactly?

Please add the output of `flutter doctor -v`

**Comment by arorayogita** [comment]
Its working fine now I have to enable android apk support plugin..thanks
for replying

On Apr 13, 2018 12:18 PM, "Günter Zöchbauer" <notifications@github.com>
wrote:

not able to create new flutter project

Means what exactly?

Please add the output of flutter doctor -v

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter/issues/16554#issuecomment-381040662>,
or mute the thread

**Comment by zoechi** [comment]
Thanks for the update. Looks like this issue can be closed.
