### ISSUE TITLE
Exception while using Navigator popUntil and push

### ISSUE THREAD

**Issue by bartektartanus** [flutter/flutter#16557]
I have a widget with button which has onPressed like this:
```
Navigator.popUntil(context, (r)=>false);
Navigator.push(context, new MaterialPageRoute(builder: (context)=> new MyWidget()));
```
This way I'm forcing my previous widget to refresh when getting back. This worked, but sometimes it  gives me this error:
`Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1846 pos 12: '!_debugLocked': is not true.
`

**Comment by jeanpaulcozzatti** [comment]
what was you solution?

**Comment by bartektartanus** [comment]
Updated flutter to next version and it helped.
