### ISSUE TITLE
flutter outline plugin suggestions

### ISSUE THREAD

**Issue by bravekingzhang** [flutter/flutter#16559]
![image](https://user-images.githubusercontent.com/4476322/38720541-30185e8e-3f29-11e8-81bc-82b0043c3466.png)

1. would you offer us `warp with Container`
2. add padding seems to be  have bug ,The loss of `new` key word may lead to run errors

**Comment by bravekingzhang** [comment]
I really like this plug-in

**Comment by zoechi** [comment]
@devoncarew do you think there is still something to do?

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2566](https://github.com/flutter/flutter-intellij/issues/2566) via [**ZenHub**](https://www.zenhub.com/)
