### ISSUE TITLE
.h file not found

### ISSUE THREAD

**Issue by keluokeda** [flutter/flutter#16556]
here is project navigator
![image](https://user-images.githubusercontent.com/16809185/38719574-4a792118-3f25-11e8-8ee5-43f8fa7f7aed.png)

i want import ViewController.h in Hello,
but i got error
"ViewController.h" file not found,
why?

**Comment by guchan-fout** [comment]
Do you mean import uikit?
Like this 
> #import <UIKit/UIKit.h>

**Comment by keluokeda** [comment]
@guchan-fout #import <UIKit/UIKit.h> also has problem

**Comment by guchan-fout** [comment]
@keluokeda how about restart xcode?

**Comment by keluokeda** [comment]
add file location to Header Search Paths,
it solve this problem.
