### ISSUE TITLE
Consider renaming flutter start to flutter run

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1655]
`start` sounds like "begin something and keep it going", but the start command runs and then exits.

`flutter run` sounds like it indicates the intention a bit more clearly: "run my app".

**Comment by sethladd** [comment]
cc @devoncarew @chinmaygarde

**Comment by devoncarew** [comment]
Similarly, perhaps `flutter list` ==> `flutter devices`.

**Comment by sethladd** [comment]
sgtm
