### ISSUE TITLE
On Using maybePop(). I'm getting this error. Can anyone help?

### ISSUE THREAD

**Issue by Pushkar98** [flutter/flutter#16563]
```
type 'MaterialPageRoute<dynamic>' is not a subtype of type 'Route<String>' where
 MaterialPageRoute is from package:flutter/src/material/page.dart
 Route is from package:flutter/src/widgets/navigator.dart
 String is from dart:core

#0      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:1643:37)
<asynchronous suspension>
#1      SignUpState.build.<anonymous closure> (package:ecommerce_pro/screens/SignUp/index.dart:47:39)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
#7      PrimaryPointerGestureRecognizer.handleEve<…>
```

**Comment by zoechi** [comment]
What's the output of `flutter doctor -v`

**Comment by Pushkar98** [comment]
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.4 17E199, locale en-IN)
    • Flutter version 0.2.3 at /Users/sahusoft/Sites/projects/flutter
    • Framework revision 5a58b36e36 (4 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sahusoft/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Users/sahusoft/Downloads/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • iPhone X • E6EF78DA-77F4-44FC-8262-B8760FBE5153 • ios • iOS 11.2 (simulator)

**Comment by zoechi** [comment]
Do you have relative imports in your `lib/main.dart`? (where the path doesn't start with `'package:...'`)

**Comment by Hixie** [comment]
Can you show `package:ecommerce_pro/screens/SignUp/index.dart` ?
