### ISSUE TITLE
Delete legacy WebKit code

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#16571]
Now that we've switched over to libtxt, we should be able to delete the legacy WebKit code.  It would make compliance easier on the Fuchsia side if we could delete this code by mid-May.  Thanks!

@jason-simmons @eseidelGoogle

**Comment by eseidelGoogle** [comment]
@abarth brought this up in our sync again today.  Still targeting mid-may for this need, but the driving requirement may slip to end-of-may.

**Comment by chinmaygarde** [comment]
@jason-simmons really want to fix a couple of typography related issues while he has the ability to compare and contrast between the two implementations. The removal itself if straightforward.

**Comment by chinmaygarde** [comment]
This is done.

**Comment by abarth** [comment]
Thanks!
