### ISSUE TITLE
Runtime Error with Sign In methods when following FriendlyChatApp with Firebase Tutorial

### ISSUE THREAD

**Issue by calirails** [flutter/flutter#16575]
## Steps to Reproduce
Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.
I've run into a Runtime Error when invoking Google Sign In methods that suggest _Future<> and Future<> types are not compatible and failing. This occurs while running and debugging this section of the Flutter tutorial: https://codelabs.developers.google.com/codelabs/flutter-firebase/#5

Repro:
Run the flutter app (on my device via flutter run -d )
Type a message
Hit send
App does not add message to the List of messages and instead fails with the logged output below.
If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
=>Not Applicable
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.
=>Not Applicable

Run your application with `flutter run` and attach all the log output.
`
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type '_Future' is not a subtype of type 'Future' where
_Future is from dart:async
Future is from dart:async
Null is from dart:core

#0 GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart)

#1 GoogleSignIn._addMethodCall. (package:google_sign_in/google_sign_in.dart:196:28)
#2 _RootZone.run (dart:async/zone.dart:1376:54)
#3 _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151:18)
#4 _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603:39)
#5 _Future._propagateToListeners (dart:async/future_impl.dart:659:37)
#6 _Future._addListener. (dart:async/future_impl.dart:342:9)
#7 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
`
Run `flutter analyze` and attach any output of that command also.
➜ whatschat git:(master) ✗ flutter analyze Analyzing /Users/calvinnguyen/safezone/projects/mobile/flutter/whatschat... No issues found! Ran in 5.3s

## Flutter Doctor
Paste the output of running `flutter doctor -v` here.
`
➜ whatschat git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.4, on Mac OS X 10.13.3 17D102, locale en-US)
• Flutter version 0.2.4 at /usr/local/Cellar/google-flutter/flutter
• Framework revision 3352a3f (3 weeks ago), 2018-03-20 19:30:06 +0100
• Engine revision 6280adb
• Dart version 2.0.0-dev.39.0.flutter-06949dc985

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
• Android SDK at /Users/calvinnguyen/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-27, build-tools 27.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
• All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 9.2, Build version 9C40b
✗ Verify that all connected devices have been paired with this computer in Xcode.
If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
To update, run:
brew uninstall --ignore-dependencies libimobiledevice
brew install --HEAD libimobiledevice
brew install ideviceinstaller
• ios-deploy 1.9.2
• CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.21.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Dart Code extension version 2.11.1

[✓] Connected devices (3 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
• CALVIN’s iPhone X • 59a045705b5301f9f931d1731b52997e48305a4a • ios • iOS 11.3
• iPhone 5s • 3EA133DB-9AE9-4B42-86C7-06B818C50C51 • ios • iOS 11.2 (simulator)

! Doctor found issues in 1 category.
`
➜ whatschat git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.4, on Mac OS X 10.13.3 17D102, locale en-US)
• Flutter version 0.2.4 at /usr/local/Cellar/google-flutter/flutter
• Framework revision 3352a3f (3 weeks ago), 2018-03-20 19:30:06 +0100
• Engine revision 6280adb
• Dart version 2.0.0-dev.39.0.flutter-06949dc985

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
• Android SDK at /Users/calvinnguyen/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-27, build-tools 27.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
• All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 9.2, Build version 9C40b
✗ Verify that all connected devices have been paired with this computer in Xcode.
If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
To update, run:
brew uninstall --ignore-dependencies libimobiledevice
brew install --HEAD libimobiledevice
brew install ideviceinstaller
• ios-deploy 1.9.2
• CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.21.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Dart Code extension version 2.11.1

[✓] Connected devices (3 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
• CALVIN’s iPhone X • 59a045705b5301f9f931d1731b52997e48305a4a • ios • iOS 11.3
• iPhone 5s • 3EA133DB-9AE9-4B42-86C7-06B818C50C51 • ios • iOS 11.2 (simulator)

! Doctor found issues in 1 category.
➜ whatschat git:(master) ✗ A

FWIW, I also get the compile time warnings
In case it helps, here's a list of deprecation warnings on startup, that may or may not be relevant to the runtime exceptions.
➜ whatschat git:(master) ✗ flutter run -d emulator-5554
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle... 0.9s
Resolving dependencies... 1.1s
Running 'gradlew assembleDebug'...
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Configuration 'compile' in project ':firebase_analytics' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_auth' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_database' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_storage' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':google_sign_in' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':image_picker' is deprecated. Use 'implementation' instead.
Built build/app/outputs/apk/debug/app-debug.apk (33.8MB).
Installing build/app/outputs/apk/app.apk... 4.1s
I/FlutterActivityDelegate( 7730): onResume setting current activity to this
Syncing files to device Android SDK built for x86... 2.3s

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment]
I'd try `flutter channel master` `flutter doctor`. 
I think I saw this issue and think it was fixed already.

**Comment by calirails** [comment]
zoechi@, thanks for the recommendation. I've tried running against the 'master' branch and get the same runtime error prior to switching branches.

**Comment by wmleler** [comment]
Friendlychat with Firebase codelab has been deprecated. If you have a similar problem with the new codelab, please open a new issue to let us know.
