### ISSUE TITLE
Issue from website page Internationalizing Flutter Apps

### ISSUE THREAD

**Issue by moesaeed** [flutter/flutter#16588]
From URL: https://flutter.io/tutorials/internationalization/

The example @ https://github.com/flutter/website/blob/master/_includes/code/internationalization/intl/main.dart
```
throw an error
#0 _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1362:5)
#1 _ChunkedJsonParser.parseNumber (dart:convert/runtime/libconvert_patch.dart:1258:9)
#2 _ChunkedJsonParser.parse (dart:convert/runtime/libconvert_patch.dart:926:22)
#3 _parseJson (dart:convert/runtime/libconvert_patch.dart:29:10)
#4 JsonDecoder.convert (dart:convert/json.dart:542:36)
#5 JsonCodec.decode (dart:convert/json.dart:169:41)
```

To fix the issue, I believe change line 51 
**Original**: return initializeMessages(localeName).then((Null _) {
**Suggested**: return initializeMessages(localeName).then((dynamic _) {

**Comment by zoechi** [comment]
The exception seems to indicate a different cause to me.

Please add the output of `flutter doctor -v`?

**Comment by Sfshaza** [comment]
Can you weigh in, @HansMuller?

**Comment by HansMuller** [comment]
Thanks for the report; we've been caught by a small change in the rules :-) Will fix.

**Comment by Sfshaza** [comment]
@HansMuller, is this fixed?

**Comment by HansMuller** [comment]
It has been fixed, thanks for the reminder.
