### ISSUE TITLE
Rename ios or apk directories?

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1658]
Our current project structure:

```
apk/ (AndroidManifest.xml and other android related files)
ios/ (.xcodeproj files, ios source files, and ios build artifacts)
build/ (android build artifacts - foo.apk - and the flx build artifact)
```

`ios/` is using the name of the target platform, and `apk/` is using the name of the build artifact. Thoughts on renaming `apk/` to `android/`?

We may also want to see if we can target some of the ios build artifacts into `build/`.

**Comment by abarth** [comment]
+1 to renaming `apk` to `android`.

Ideally we'd put all of the iOS bits that the tools control in `build/` and leave `ios/` for the bits the author controls.  I'm not sure how separated those two kinds of bits are.  /cc @chinmaygarde

**Comment by sethladd** [comment]
sgtm
