### ISSUE TITLE
[flutter packages pub run build_runner build] Unable to spawn isolate: Unhandled exception:

### ISSUE THREAD

**Issue by bravekingzhang** [flutter/flutter#16586]
Unable to spawn isolate: Unhandled exception:
Could not load "http://localhost:53204/build_runner.dart": Failure getting http://localhost:53204/build_runner.dart:
  504 Gateway Time-out
null
pub finished with exit code 1

`sudo flutter packages pub run build_runner build`  will ok ,but it's not safely

➜  douban_me git:(master) ✗ sudo flutter packages pub run build_runner build
Password:
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎

**Comment by chinmaygarde** [comment]
How are you spawning the isolate? Can you add a reduced test case?

**Comment by bravekingzhang** [comment]
do you mean `flutter packages pub run build_runner build`  add -v  ?? @chinmaygarde

**Comment by Hixie** [comment]
Does it work if you just use build_runner directly, without using flutter? It's not clear if this is a flutter bug or a more low-level dart bug.

Can you provide us with a zip file of the smallest project that shows the exact failure?
