### ISSUE TITLE
Arabic text with Vowels (E'raab) not displayed properly

### ISSUE THREAD

**Issue by saeedjassani** [flutter/flutter#16598]
## Steps to Reproduce

Arabic text without eraab is displayed properly. 
![screen shot 2018-04-15 at 12 14 23](https://user-images.githubusercontent.com/11854320/38775729-1eb9b622-40a7-11e8-8d45-be0eec958470.png)

But, text with Eraab messes up

![screen shot 2018-04-15 at 12 14 45](https://user-images.githubusercontent.com/11854320/38775734-2f8e65f6-40a7-11e8-96a8-3309f65ff3fd.png)

Actual text:
            "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ", 
            "اَلْحَمْدُ لِلّٰهِ رَبِّ الْعٰلَمِيْنَ", 

## Logs

Run your application with `flutter run` and attach all the log output.
No error or Warning log!

Run `flutter analyze` and attach any output of that command also.
```
Analyzing /Users/saeedjassani/Workspace/---...
No issues found!
Ran in 9.5s
```
## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.2.11, on Mac OS X 10.13.4 17E199, locale en-IN)
    • Flutter version 0.2.11 at /Users/saeedjassani/flutter
    • Framework revision f408bb06f9 (4 days ago), 2018-04-10 14:27:53 -0700
    • Engine revision 6474647f52
    • Dart version 2.0.0-dev.46.0.flutter-ef926f98f5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/saeedjassani/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/saeedjassani/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by chinmaygarde** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
This should be fixed by https://github.com/flutter/engine/commit/9eec9848e902b564a53fe23684a992ce9a32d5d9.

Try switching to the master channel of Flutter to get the update.

**Comment by saeedjassani** [comment]
Thanks a lot. Works perfectly after upgrade.

Closing the issue.

**Comment by dahabit** [comment]
@jason-simmons  Thanks I  Confirm also that issue fixed with latest flutter update from the master channel, the beta channel still have it

![screen shot 2018-04-22 at 12 44 04 am](https://user-images.githubusercontent.com/284535/39089407-c4d42f6e-45c6-11e8-8057-19b0cae03f12.png)

Thanks Dartisans :)
