### ISSUE TITLE
Try-Catch Not working properly

### ISSUE THREAD

**Issue by BasedMusa** [flutter/flutter#16592]
## General

This is one of my methods in my app. It checks if an asset image with a name exists, if not then it uses 
the 'cached_network_image' plugin to display the image and store it in the app's cache. 

## Problem
The  only executed code is the try block, it just prints 'unable to load asset: x' in console. The catch block is never executed. Help...

## Code
```dart
_getIcon() {
    try {

      var symbol = widget.currency.symbol.toLowerCase();
      var assetLocation = 'images/coins/' + symbol +'.png';
      
      return new Image.asset(assetLocation);

    } catch (Exception) {
      
      print('Downloading icon...');

      var rank = widget.currency.rank;
      
      return new CachedNetworkImage(
        imageUrl: getIconsURL(BigInt.parse(rank).toInt()),
        placeholder: new CircularProgressIndicator(),
        errorWidget: new Icon(Icons.error),
      );
    
    }
  }
}
```

**Comment by chinmaygarde** [comment]
Reading the API docs, it is not clear to me that the constructor actually throws an exception when the asset cannot be resolved. @Hixie @HansMuller: What would be the best way to check the if an asset exists in an asset bundle? All the methods I see in [AssetBundle](https://docs.flutter.io/flutter/services/AssetBundle-class.html) actually attempt to load the data for that asset which would be unnecessary.

**Comment by BarbaricGamester** [comment]
@chinmaygarde Can you give some sample code, I understand what you are saying but I don't know how to do this. Should I do something like AssetBundle.image('img_name') ?

**Comment by apaatsio** [comment]
I ran into the same issue. Here's minimal code code to reproduce the problem:

```dart
try {
  return Image.asset('assets/DOES_NOT_EXIST.jpg');
} catch (e) {
  print('THIS NEVER GETS PRINTED');
}
```

Despite the try..catch an exception is thrown

```
I/flutter (25479): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (25479): The following assertion was thrown resolving an image codec:
I/flutter (25479): Unable to load asset: assets/DOES_NOT_EXIST.jpg
I/flutter (25479):
I/flutter (25479): When the exception was thrown, this was the stack:
I/flutter (25479): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (25479): <asynchronous suspension>
I/flutter (25479): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:427:44)
I/flutter (25479): <asynchronous suspension>
I/flutter (25479): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:412:14)
I/flutter (25479): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
...
```

**Comment by Hixie** [comment]
Actually fetching the asset is done asynchronously, when the widget is inflated, placed into the tree, and has its `State` object created. Creating the `Image` object itself doesn't do anything (creating widgets in general doesn't do anything, they're just immutable state descriptions). That's why this isn't catching the exception: it's not thrown until much later.

**Comment by maryx** [comment]
What would be a good way to catch the Exception that gets thrown later on?

**Comment by Hixie** [comment]
Try using the onError callback on precacheImage.

**Comment by maryx** [comment]
Thanks for the advice! I must be missing something obvious here, as my error calls are not being triggered. I've done something like this:

```
    precacheImage(
      image, // a NetworkImageWithRetry
      context,
    ).then((success) {
      print(success); // this is always null
      } else {
        return Container(
          padding: EdgeInsets.only(right: 8.0),
          child: Image(
            image: image,
            fit: BoxFit.fitWidth,
          ),
          height: 20.0,
          width: 20.0,
        );
      }
    }, onError: (e) {
      print('hey error'); // This is never printed
      print(e);
      return Container();
    });
```
and now it seems like the original exception (FetchFailure) is being caught, but I'm never actually making it into the `onError` - I keep going into the `success` callback, where `success` is null.

Error message:
```
EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE
The following _Exception was thrown resolving an image codec:
Exception: NetworkImage is an empty file: https://spicysouthernkitchen.com/favicon.ico
When the exception was thrown, this was the stack:
NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:494:7)
 #7      consolidateHttpClientResponseBytes.<anonymous closure> (package:flutter/src/foundation/consolidate_response.dart:29:15)
(elided 20 frames from package dart:async)
```

I then also tried using `.catchError()` at the end of `precachedImage` but that never gets called either.

**Comment by Hixie** [comment]
It looks like we put the onError handler on `precacheImage` itself rather than on the `Future`, unfortunately. We should probably fix that, though that might be a breaking change.

**Comment by maryx** [comment]
Should I file a separate issue for that or is this one sufficient?

In the meantime, do you have other ideas on how to catch the error, or render UI conditionally based on whether an image successfully loads?

**Comment by Hixie** [comment]
You should just be able to pass the `onError` to precacheImage directly.

**Comment by maryx** [comment]
Oh yeah! Thanks! I had missed it in the docs (https://docs.flutter.io/flutter/widgets/precacheImage.html). 

Unfortunately, that onError is not being triggered. Is it because it expects a ImageErrorListener type, whereas the FetchFailure is a different type?

With (the `image` object is as defined here: https://stackoverflow.com/questions/52637606):
```
 precacheImage(image, context, onError: (e, stackTrace) {
      print('hey error');
      print(e);
      return Container();
    });
```
I am getting a 
```
 EXCEPTION CAUGHT BY PACKAGE:FLUTTER_IMAGE
The following FetchFailure was thrown NetworkImageWithRetry failed to load
https://spicysouthernkitchen.com/favicon.ico:
FetchFailure(
attemptCount: 1
httpStatusCode: 404
totalDuration: 0:00:00.613799
originalException: null
)
```

**Comment by xster** [comment]
Seems like there's a pattern difference between package:flutter_image's NetworkImageWithRetry and the other ImageProviders from the Flutter framework. 

The other ImageProviders will construct a MultiFrameImageStreamCompleter or a OneFrameImageStreamCompleter with a Future-returning constructor parameter that will throw whereas NetworkImageWithRetry will directly call FlutterError.onError without throwing into the completer https://github.com/flutter/flutter_image/blob/master/lib/network.dart#L165. 

We should probably keep NetworkImageWithRetry consistent with the other ImageProviders.

**Comment by maryx** [comment]
I was able to get a version with `NetworkImage` working! For anyone interested, this is what I have in my build(), and `imageFailedToLoad` is defined as a bool in my State object (and gets reset when the image URL updates).

```
    precacheImage(image, context, onError: (e, stackTrace) {
      log.fine('Image ${widget.url} failed to load with error $e.');
      setState(() {
        imageFailedToLoad = true;
      });
    });
    return imageFailedToLoad
        ? Container()
        : Container(
            padding: EdgeInsets.only(right: 8.0),
            child: Image(
              image: image,
              fit: BoxFit.fitWidth,
            ),
            height: 20.0,
            width: 20.0,
          );
```

**Comment by junyao-yu** [comment]
> I ran into the same issue. Here's minimal code to reproduce the problem:
> 
> ```dart
> try {
>   return Image.asset('assets/DOES_NOT_EXIST.jpg');
> } catch (e) {
>   print('THIS NEVER GETS PRINTED');
> }
> ```
> 
> Despite the try..catch an exception is thrown
> 
> ```
> I/flutter (25479): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
> I/flutter (25479): The following assertion was thrown resolving an image codec:
> I/flutter (25479): Unable to load asset: assets/DOES_NOT_EXIST.jpg
> I/flutter (25479):
> I/flutter (25479): When the exception was thrown, this was the stack:
> I/flutter (25479): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
> I/flutter (25479): <asynchronous suspension>
> I/flutter (25479): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:427:44)
> I/flutter (25479): <asynchronous suspension>
> I/flutter (25479): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:412:14)
> I/flutter (25479): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
> ...
> ```

I also met the same problem, know how to solve?

**Comment by sjmcdowall** [comment]
@maryx -- Hey Mary!  Can I see more of your solution? I am running into the same problem but I can't quite grasp the total solution with the partial code you posted .. I too am doing a NetworkImage so your solution seems spot on with what I want to do as well.  Thanks!

**Comment by zoechi** [comment]
@sjmcdowall you make an extra call to precache an image for example in `initState` using the code above and then just use `Image.network(...)` or similar as before (without any error handling) where you actually want to show the image.

**Comment by westy92** [comment]
Just adding some more information here. I received a similar exception, but not the same as ones previously mentioned.

```
I/flutter (22719): ══╡ EXCEPTION CAUGHT BY PACKAGE:FLUTTER_IMAGE ╞═════════════════════════════════════════════════════
I/flutter (22719): The following FetchFailure was thrown NetworkImageWithRetry failed to load
I/flutter (22719): https://static.checkiday.com/img/600/salsa-669389.jpg:
I/flutter (22719): FetchFailure(
I/flutter (22719):   attemptCount: 1
I/flutter (22719):   httpStatusCode: null
I/flutter (22719):   totalDuration: 0:00:00.087055
I/flutter (22719):   originalException: HttpException: Connection closed before full header was received, uri =
I/flutter (22719):   https://static.checkiday.com/img/600/salsa-669389.jpg
I/flutter (22719): )
I/flutter (22719): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by AppleEducate** [comment]
This is what ended up working for me:

``` dart
Container(
              child: Builder(builder: (BuildContext context) {
                try {
                  return Image.network(
                    image + mediumQuality,
                    fit: BoxFit.cover,
                  );
                } on PlatformException {
                  return Container();
                }
              }),
 );
```

**Comment by larssn** [comment]
Seems related to https://github.com/flutter/flutter/issues/33427

**Comment by BasedMusa** [comment]
Closing this as the original seems to be resolved with multiple solutions. For any beginner devs reading this, you can also add refresh buttons and error widgets to your image, not sure if the Built In `Image.x() `widget supports this, but the `AdvancedNetworkImage` widget found on pub.dev does support this.

**Comment by shaimo** [comment]
I'm having the same issue and can't seem to get any of these solutions to work. Simply need to be able to load images from the assets folder, and if missing I want to use some default icon. No matter what I do I can't catch that exception:

```
Widget getImage(String symbol) {
    try {
      return new Image.asset(
          "assets/images/" + symbol + ".png",
          height: 28.0, width: 28.0);
    } catch (e) {
      print("Got exception ${e.toString()}");
      return Icon(Icons.account_balance, color: Colors.white);
    }
}
```
This throws an exception instead of handling it gracefully. Totally stuck with this...
I tried PlatformException but it didn't change anything.

**Comment by sudeshkumara** [comment]
Yes. I know this is about try-catch.  But I also had this problem and I was able to avoid this problem by using errorBuilder. According to my need, I wanted to return a sample image. So customize it to your needs.

```
Image.asset(
     "assets/images/subjects/api_given_image_name.png",
     width: 90,
     errorBuilder: (BuildContext context, Object exception, StackTrace stackTrace) {
           print(exception);
           return Image.asset(
                "assets/images/your_sample_image.png",
                width: 90,
           );
     },
)
```

**Comment by MstrZeroOne** [comment]
I have the same problem. But not in the Images cases.

`try {
      RequestModel data = RequestModel().formJson(response.data['data']);
      return data;
    } catch (e, st) {
      print("Error $e");//This do not print
      print("Stacktrace $st");//This do not print
      return "Something went wrong!";//But this is working and returns the text
    }`

**Comment by fernando-s97** [comment]
Why is this issue closed if the problem is not solved?
