### ISSUE TITLE
Flutter Doctor

### ISSUE THREAD

**Issue by Shruti-Mahajan** [flutter/flutter#16591]
Hi
I am facing issues while installing flutter. when I am running flutter doctor I am getting one error

'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.

Even though I have set the git path and flutter path in environment variable. please help me to resolve that error.

Thanks!

**Comment by Shruti-Mahajan** [comment]
Hi
I am facing issues while installing flutter. when I am running flutter doctor I am getting one error

'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.

Even though  I have set the git path and flutter path in environment variable. please help me to resolve that error. 

Thanks!

**Comment by chinmaygarde** [comment]
`where` is a shell built-in and is probably being used to locate the location of `git`. Can you add more information to this issue about your environment? The platform, shell, command you executed, additional log files that the tool generates when it crashes.

**Comment by onatcipli** [comment]
I'm getting the same error when I try to open a new project. I add the path to my environment but it's not working. I'm using IntelliJ idea 
/*
'where' is not recognized as an internal or external command,
Error: Unable to find git in your PATH. 
operable program or batch file.
*/

When I try to run flutter doctor I get this error
/*
'flutter' is not recognized as an internal or external command,
operable program or batch file.
*/
The path already added to my Environment.

**Comment by zoechi** [comment]
@onatcipli what operating system?
What happens when you execute `where` in a shell?

**Comment by onatcipli** [comment]
Windows 10 home 
when I executed 'where' in a shell I get this error 
/*
'where' is not recognized as an internal or external command,
operable program or batch file.
*/

**Comment by zoechi** [comment]
@onatcipli I think there should be a `where` command on Windows https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line

**Comment by eynol** [comment]
Try to add `C:\Windows\System32` to your PATH.
The `where.exe` exists in  `C:\Windows\System32` and `C:\Windows\SysWOW64` .

**Comment by zoechi** [comment]
I think this is a dup of #12129

**Comment by zoechi** [comment]
@jcodinginflow 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Marwa-Eltayeb** [comment]
Add 
C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32 
to your PATH variable 

Do not create new variable for git but add them as I did one after another separating them by ;

**Comment by AnasGhareib** [comment]
hey I have a proplem when I start to run flutter and flutter doctor 
**Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: cadc6c7f7b463c3a)**
[flutter_08.log](https://github.com/flutter/flutter/files/3333478/flutter_08.log)

**Comment by AnasGhareib** [comment]
**Oops; fluttproblemexited unexpectedly.Sending crash report to Google.Crash report sent (report ID: cadc6c7f7b463c3a)**

**Comment by srigowrideo** [comment]
same problem

**Comment by TanishaSingh16** [comment]
> Add
> C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32
> to your PATH variable
> 
> Do not create new variable for git but add them as I did one after another separating them by ;

You mean 'Path' not

**Comment by atikakiki** [comment]
Hi

**Comment by acousticclown** [comment]
> Try to add `C:\Windows\System32` to your PATH.
> The `where.exe` exists in `C:\Windows\System32` and `C:\Windows\SysWOW64` .

This fixed my problem. Thank You :)

**Comment by anu10943** [comment]
It worked for me after adding 
C:\Windows\System32;C:\flutter\flutter\bin
to PATH of user variable and
C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\flutter\flutter\bin;C:\Windows\System32
to PATH of system variable in environment variable (from edit the system environment variables )

**Comment by victorkab92** [comment]
> @zoechi
> Windows 10 home
> when I executed 'where' in a shell I get this error
> /*
> 'where' is not recognized as an internal or external command,
> operable program or batch file.
> */

try to run cmd or PowerShell on your window home computer as an administrator
This will solve this problem :)

**Comment by jamal4sabr** [comment]
Hi, when i ever i try to clone fluuter on my C\src drive inside source folder it says 'git' is not recognized as an internal or external command,
operable program or batch file

**Comment by sijen** [comment]
> Try to add `C:\Windows\System32` to your PATH.
> The `where.exe` exists in `C:\Windows\System32` and `C:\Windows\SysWOW64` .

thanks this solved my problem when i added the secound path in my system variable.Thank you very much

**Comment by f0mster** [comment]
had same issue.
after research I found out that it happens cause of "SETLOCAL ENABLEDELAYEDEXPANSION" in file flutter.bat
when i removed this string, all back to normal behavior.

**Comment by kios19** [comment]
> Try to add `C:\Windows\System32` to your PATH.
> The `where.exe` exists in `C:\Windows\System32` and `C:\Windows\SysWOW64` .

thnks man this works

**Comment by RonyPixel** [comment]
Firstly Run your Cmd as administrator .. because of the different file path..
or try to set path of where.exe in environment variable
