### ISSUE TITLE
Entering immersive corrupts part of the screen for a frame due to GL context size mismatch

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#166]
<a href="https://github.com/apwilson"><img src="https://avatars.githubusercontent.com/u/142874?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [apwilson](https://github.com/apwilson)**
_Thursday Sep 17, 2015 at 23:55 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1227_

----

It's hard to explain better than that but I've a video I can share offline.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/apwilson"><img src="https://avatars.githubusercontent.com/u/142874?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apwilson](https://github.com/apwilson)**
_Friday Sep 18, 2015 at 00:01 GMT_

----

Upon further inspection of my video I believe this is due to a resize that takes place shortly after launch due to immersive mode being enabled.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Friday Sep 18, 2015 at 05:17 GMT_

----

cc @chinmaygarde @abarth

**Comment by FlutterIssues** [comment]
<a href="https://github.com/apwilson"><img src="https://avatars.githubusercontent.com/u/142874?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apwilson](https://github.com/apwilson)**
_Monday Oct 12, 2015 at 21:48 GMT_

----

Is there anything I can do on my side to prevent the glitch?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Monday Oct 12, 2015 at 21:53 GMT_

----

I don't think there's any way to work around the issue on your side.  We just need to size the GL context correctly in C++.

**Comment by apwilson** [comment]
I feel like I haven't seen this for a while.

**Comment by eseidelGoogle** [comment]
Is this still an issue for you @apwilson?
