### ISSUE TITLE
Android, not able to use other Locales in speech_recognition plugin

### ISSUE THREAD

**Issue by rubencg195** [flutter/flutter#16609]
I've implemented a system in Flutter in which I can choose my language from a menu. The program starts by default in English but when I try to set it to Spanish or French it doesn't work. **The developer who made it had left the issues without an answer for more than a month, so I come to you for help.**

I know that in the **readme.md** says that to make it work, more configuration is needed. **The question is what do I need to do to make it work in other languages.**

![image](https://user-images.githubusercontent.com/25628940/37566710-9570ffc2-2a82-11e8-8f85-cae2991ab1b7.png)

https://github.com/rxlabz/speech_recognition/issues/2
```dart
 _speech.listen( locale: widget._language ).then((result) => setState(() {
            print("Listening ${result}");
            this.setState(() {
              transcription = result;
            });
          }));
```

**Comment by dlutton** [comment]
@rubencg195 do you have the locale string you're passing?

**Comment by rubencg195** [comment]
The locales I´ve tried are "en_US", "fr_FR", and "es_ES". I made a library in Unity3D for voice recognition using the same phone and it worked. The phone is a Galaxy Note 3 v5.0.0

**Comment by zoechi** [comment]
Is this still an issue?
I'm not sure there is anything the Flutter team can do.

**Comment by rubencg195** [comment]
@zoechi Can you explain me what can I do to access other languages(locales) or edit the plugin to download extra languages for it to be possible.

**Comment by zoechi** [comment]
I would need to investigate, but I don't have the time for that. 
You could try asking on StackOverflow.

**Comment by Hixie** [comment]
This isn't our plugin, so I'm afraid there isn't much we can do. I recommend trying to debug the plugin yourself, then submitting a PR to the plugin author. Sorry we can't be more helpful.
