### ISSUE TITLE
Google SignIn: Getting ID Token for Server-side Auth

### ISSUE THREAD

**Issue by nevi-me** [flutter/flutter#16613]
## Steps to Reproduce

I started using Firebase Auth after I already had a custom OAuth impl in place, so in my previous app, I would authenticate the user on Firebase, but also request an ID Token from Google Signin [https://developers.google.com/identity/sign-in/android/offline-access](https://developers.google.com/identity/sign-in/android/offline-access).

Is there currently a way to do this on `google_sign`in? On Android, I would do something like `SignIn.requestServerAuthCode(serverClientId)`.

## Logs

n/a

## Flutter Doctor

```
[√] Flutter (Channel master, v0.2.12-pre.33, on Microsoft Windows [Version 10.0.14393], locale en-ZA)
    • Flutter version 0.2.12-pre.33 at C:\Users\<me>\flutter
    • Framework revision ea30c95dc9 (2 days ago), 2018-04-13 17:02:14 -0700
    • Engine revision 76cb311d9c
    • Dart version 2.0.0-dev.47.0.flutter-f76dad0adc

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\<me>\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.0.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.4
    • Flutter plugin version 23.0.2
    • Dart plugin version 173.4700

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[√] VS Code, 64-bit edition (version 1.22.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.2

[√] Connected devices (1 available)
    • SM G610F • 5203f84b5378a381 • android-arm • Android 7.0 (API 24)

• No issues found!
```

**Comment by mravn-google** [comment]
Maybe Firebase Auth has the API you want: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser.html#getIdToken(boolean)

**Comment by zoechi** [comment]
The token returned from `getIdToken()` worked for me to access Google APIs using HTTP requests.
I don't fully understand your requirement though.

**Comment by calebisstupid** [comment]
I believe I'm trying to solve a similar issue; was there any resolution to this?

We have a back-end server that uses Google Auth for users. I've started building out a flutter app, and used the google_sign_in plug-in but each authentication request returns a null idToken.

Every other thread on the topic I have found points me towards Firebase documentation, which is not what I need. I have found some posts saying that we need to use our back-end "web token", but for the life of me I cannot find any help on how to actually modify or change this using flutter or non-firebase techniques.

**Comment by nevi-me** [comment]
@calebisstupid it hasn't been resolved

**Comment by matthew5025** [comment]
@nevi-me I've tested this, and it works for Android. I do not have a Mac so I can't really help with iOS stuff.

 

1. Create a new Firebase project. It's ok to link the old Google Cloud Project.

2. Select get started with android, and follow the instructions. The important parts are the google-services.json files, and the additional dependencies. 

3. You will now be able to retrieve an idToken.

**Comment by nevi-me** [comment]
@matthew5025 my Android device is in for repairs, but I'll try on the emulator and revert nack

**Comment by laertispappas** [comment]
@matthew5025 do you happen to know how to handle multiple clients ids? I have 1 client id generated in my firebase (from the debug keystroke) I added into the same project my production SHA1 to sign the app but when I release the app I cannot verify the token in the backend. Google API returns bad request: Invalid Value. 

Since it is working in the emulators but not when I install the app in my mobile I assume that I need to add another client id in https://console.cloud.google.com/apis/credentials. Just assumptions any ideas?

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by senacand** [comment]
@laertispappas I'm having the same issue as yours. I can get the id token using the Firebase workaround, unfortunately I cannot verify the ID Token neither using the SDK nor Google's API.

**Comment by zainzafar90** [comment]
@mravn-google  `idToken` it keeps returning null no matter what I do

`FirebaseUser.getIdToken`  doesn't work either

```dart
final GoogleSignInAccount googleUser = await _googleSignIn.signIn();

final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

// Able to get accessToken
print(googleAuth.accessToken);

//But not this
print(googleAuth.idToken);


```

**Comment by rcrescenti** [comment]
> @laertispappas I'm having the same issue as yours. I can get the id token using the Firebase workaround, unfortunately I cannot verify the ID Token neither using the SDK nor Google's API.
> 
> UPDATE: Nvm. I tried debugPrinting the ID Token and use the output to validate to Google's API and get Invalid Value. Turns out the reason was as simple as the ID Token was cut by the log, therefore cutting in the middle of the signature part.

I have the same problem.
I have registered an issue: https://github.com/flutter/flutter/issues/31635

**Comment by premtemp1** [comment]
need the refresh token to validate again the backend Api .

**Comment by PJosue100** [comment]
Does anyone know how to implement the serverClientId option to return serverAuthCode?

**Comment by rebeccamcfadden** [comment]
I'm still having issues with this. I am using version 4.5.6 of google_sign_in and I am not receiving the serverAuthCode.

**Comment by rebeccamcfadden** [comment]
https://github.com/flutter/flutter/issues/57712#issuecomment-703382420 

this instruction fixed it for me, but it would be great if this PR got merged in
