### ISSUE TITLE
Feature request: Firebase Auth Link-To 

### ISSUE THREAD

**Issue by Arno-Z** [flutter/flutter#16610]
Right now, Firebase Auth allows linking accounts of two types:

- Username/Password:     `_auth.linkWithEmailAndPassword()`
- Google ID: `_auth.linkWithGoogleCredential()`

Account linking is used in a useful stories:

Story 1:
A user initialises the app, after initialisation the app gathers data from the user. This is not analytics data, but user-oriented data. Such as user preferences or data for a sign-up wizard. This can be stored in local preferences or in an anonymous login firebase session. Such a session may require linking to a real (not-anonymous) account later.

 Story 2:
A user uses Facebook sign-in but decides to abandon facebook, user wants to convert to another account type for sign-in, for example Twitter.

As Firebase can by default use to a multitude of auth methods (including Twitter/FaceBook/GitHub/Phone etc, see https://firebase.google.com/docs/auth/) it would be nice if all of these were supported.

Thanks!

**Comment by harrisonturton** [comment]
I'd imagine this wouldn't be too hard to do manually, you'd just need to store info related to the Twitter (for example) login and just 'link' it within your app's database.

Also, this is the repo for Flutter (Google's mobile UI framework), not Firebase. Although it's commonly integrated with Firebase, they are two separate things. Correct me if I'm wrong 👍

**Comment by osorito** [comment]
In the firebase console i can set many login methods, but the only ones available right now is email and google. When will you add support for the other providers supported by firebase? example facebook, twitter, github.

Thanks.

**Comment by harrisonturton** [comment]
Go to Firebase console > Authentication > Sign In Method

You should see the following list:

- Email / Password
- Phone
- Google
- Play Games
- Facebook
- Twitter
- Github
- Anonymous

You should be able to use any of these.

Note that (at the time of writing), FB has restricted third-party access to their APIs. This may affect social authentication, but I'm not sure.

As for adding support for other providers, I have no idea 😃  I don't work for Google

**Comment by harrisonturton** [comment]
@osorito You should be able to implement those sign-ins using the [Firebase Auth package](https://pub.dartlang.org/packages/firebase_auth). See the sign-in methods [here](https://pub.dartlang.org/documentation/firebase_auth/0.5.5/firebase_auth/FirebaseAuth-class.html) (Although I don't see Twitter and Github? Maybe post an issue on their Github repo).

Note that FB login *might* not work, because (at the time of writing), Facebook has suspended access to their third-party APIs. I'm not sure if this extends to social login, however.

**Comment by fmatosqg** [comment]
I'd be surprised if FB cut social login through firebase, that's going to be a big problem for a lot of people who don't even use FB data. But who knows.

**Comment by kroikie** [comment]
@Arno-Z

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/850. Any further collaboration will be done there.
