### ISSUE TITLE
test framework does not trigger dragEnd correctly if a dragUpdate occurs.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1661]
The following code will always trigger a dragStart, if deltaY and/or deltaX are non-zero it'll trigger a dragUpdate but no dragEnd.  If deltaX/deltaY are 0.0, dragEnd is triggered but no dragUpdate.

```dart
void _drag(WidgetTester tester, Point origin,
    {double deltaX: 0.0, double deltaY: 0.0}) {
  TestPointer pointer = new TestPointer(8);
  tester.dispatchEvent(pointer.down(origin), origin);
  tester.pump();
  tester.dispatchEvent(
      pointer.move(origin + new Offset(deltaX, deltaY)), origin);
  tester.pump();
  tester.dispatchEvent(pointer.up(), origin);
  tester.pump();
}
```
You should always get a dragEnd if you get a dragStart.  Getting a dragStart when you don't move the pointer is questionable imo.

**Comment by Hixie** [comment]
Can you show more code? Are you using a GestureDetector and onDragStart/onDragMove/onDragEnd?

**Comment by apwilson** [comment]
Yes, GestureDetector; onDrag*

I'll try to make a reduced test.

**Comment by apwilson** [comment]
Hmm the reduced test doesn't exhibit this issue.  Makes me wonder what's going on in my test...

**Comment by apwilson** [comment]
I'll close for now.  Problem is probably on my end.
