### ISSUE TITLE
Issue from website page Fetch data from the internet

### ISSUE THREAD

**Issue by BugsBunnyBR** [flutter/flutter#16611]
From URL: https://flutter.io/cookbook/networking/fetch-data/

There is no error handling in that page. 
What if there is no internet?
What if the server answer a 4xx with a JSON body?

The page just don't answer these questions.

Thanks.

**Comment by brianegan** [comment]
Good call, I was trying to keep it simple, but perhaps it's a bit too simple. I'll look at how I can add those sections to the recipe / separate recipe.

Thanks!

**Comment by brianegan** [comment]
This has been addressed in a recent PR. Should land on the website soon!
