### ISSUE TITLE
-fobjc-weak is not supported on the current deployment target

### ISSUE THREAD

**Issue by codegrue** [flutter/flutter#16627]
Suddenly started getting this error every time trying to run on the iOS Simulator:

```
Launching lib/main.dart on iPhone 6s in debug mode...
Xcode build done
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
clang: error: -fobjc-weak is not supported on the current deployment target
Could not build the application for the simulator.
Error launching application on iPhone 6s.
Exited (sigterm)
```

Google searched on this produce sparse and dated commentary.

Checked my XCode install and it's the latest release.

Ran a clean startup flutter app, and it worked. So something got corrupted in my main project and I am not sure how to fix this. 

I believe this started soon (but not immediately) after referencing firebase in pubspec.yaml:

`firebase_auth: ^0.5.3`

-------

flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.2.8 at /Users/jeff/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/jeff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.22.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (2 available)
    • iPhone 6s • 76FFA6A9-06F8-4587-A6A9-08219259954D • ios • iOS 11.3 (simulator)
    • iPhone X  • CA9C0D6A-F4CE-44D6-B204-195620E70949 • ios • iOS 11.3 (simulator)

• No issues found!

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`

**Comment by codegrue** [comment]
Solved. Per the firebase instructions had to execute the following:

```
brew install cocoapods
 pod setup
```

https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#4

(At least this issue now ties this error to a firebase install problem.)
