### ISSUE TITLE
Feature request: video_player ability to set speed

### ISSUE THREAD

**Issue by Jasonthefirst** [flutter/flutter#16624]
It would really help me (and I think a lot of other people if the video_player would be able to set to certain speed steps (like 25%, 50%, 75%, 100%, 150%) so you can watch a clip in different speeds.

Edit: Second request put into another issue.

**Comment by cbenhagen** [comment]
Please open a second issue for the seeking and give some information about the platform and key frame interval of your clips.

**Comment by ditman** [comment]
Published [video_player v0.11.0](https://pub.dev/packages/video_player/changelog), which contains the playback speed feature!
