### ISSUE TITLE
video_player plugin: allow to specify headers with dataSource

### ISSUE THREAD

**Issue by freewheelnat** [flutter/flutter#16623]
At the moment, the dataSource is a string, ie the url, and we cannot pass headers (from what I understood by reading the source code). This means the plugin only works for public video urls. 

Please consider adding the option to add headers (eg in Android code, use `setDataSource (Context context, Uri uri,   Map<String, String> headers)` ). This would allow us to use the plugin to show videos hosted on our servers (for which we need Authorization header).

**Comment by cbenhagen** [comment]
Duplicate: https://github.com/flutter/flutter/issues/16466

**Comment by freewheelnat** [comment]
Oops, did a search for it last week, nothing turned up but didn't have time to post new issue and forgot to do a search for it again today before posting, apologies.
