### ISSUE TITLE
Filled textfield contrast too low.

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#16628]
The contrast ratio between the filling and the text of a filled textfield is too low, Android's Accessibility Scanner reports it as 4.23, but it needs to be 4.5. See the "Name", "Phone Number", and "E-mail" fields below from Flutter Gallery. 

![image](https://user-images.githubusercontent.com/1227763/38824175-3a0cfb3a-415d-11e8-8a13-842f0bdabde7.png)

/cc @HansMuller

**Comment by jonahwilliams** [comment]
@HansMuller I'm trying to look at the colors in the spechttps://material.io/design/components/text-fields.html#spec, but they make no sense to me.  Are the 'colors' in the spec just for reference for the color picker tool?

**Comment by HansMuller** [comment]
The current spec doesn't really define specific colors, just layout

**Comment by HansMuller** [comment]
This PR was supposed to have brought us to 4.5: https://github.com/flutter/flutter/pull/15504

**Comment by jonahwilliams** [comment]
This looks like an error with the accessibility scanner.  If I remove the leading icon and add just a bit more text to the TextField it reports no accessibility issues. 

## No Errors
<img src="https://user-images.githubusercontent.com/8975114/41493583-744af178-70bd-11e8-8e6b-d87ed65d01dd.png" width="300">
