### ISSUE TITLE
Internet connected or not 

### ISSUE THREAD

**Issue by prasant10050** [flutter/flutter#16621]
1) i know The **_connectivity_** plugin states in its docs that it only provides information if there is a network connection, but not if the network is connected to the Internet
but how to know the network is connected to the Internet or not?
is there any code to solve this issue.

2)when i use Connectivity plugin it shows error-
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/prashant/IdeaProjects/job_posting/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'connectivity/ConnectivityPlugin.h' file not found
    #import <connectivity/ConnectivityPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

How to fit it?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`

**Comment by prasant10050** [comment]
flutter doctor -v
[✓] Flutter (Channel master, v0.3.1-pre.17, on Mac OS X 10.13.4 17E199, locale en-IN)
    • Flutter version 0.3.1-pre.17 at /Users/prashant/Library/flutter
    • Framework revision c83d24d547 (34 minutes ago), 2018-04-16 21:48:21 -0700
    • Engine revision 76cb311d9c
    • Dart version 2.0.0-dev.47.0.flutter-f76dad0adc

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/prashant/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/prashant/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] Connected devices (1 available)
    • iPhone X • F043D5AC-E2C2-4B56-876A-623C9F5D8C83 • ios • iOS 11.1 (simulator)

• No issues found!

**Comment by koraxis** [comment]
I am having the same issue, Have you found a solution?

**Comment by prasant10050** [comment]
NO solution

**Comment by faraz-ahmad** [comment]
I am facing this issue when I try to install on iphone simulator. 

fatal error: 'connectivity/ConnectivityPlugin.h' file not found

**Comment by zoechi** [comment]
Try running `pod update` in `ios/`

**Comment by zoechi** [comment]
Cosing as dup of #18673
