### ISSUE TITLE
Image.file file is null errors

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#16639]
I have been experimenting with Image.file since I want to display images which have been downloaded via http.
I am getting exceptions with the code below, and also with the same code which is run inside a dialog (opened via a button from the main() page). The image doesnt seem to matter, but this example is from <i>Android/Sdk/platforms/android-27/data/res/drawable-hdpi/battery_charge_background.png</i>
The code works and the image is displayed, but this giant error is off-putting.

    import 'dart:io';
    import 'dart:async';
    import 'package:path_provider/path_provider.dart';
    import 'package:flutter/material.dart';

    void main() => runApp(new MyApp());

    class MyApp extends StatelessWidget {

      Future<File> _getLocalFile(String filename) async {
        String dir = (await getApplicationDocumentsDirectory()).path;
        print("MyApp.File=$dir/$filename");
        File f = new File('$dir/$filename');
        return f;
      }

      @override
      Widget build(BuildContext context) {
        return new MaterialApp(
            title: 'Flutter Demo',
            home: new FutureBuilder(
                future: _getLocalFile("flutter_assets/battery_charge_background.png"),
                builder: (BuildContext context, AsyncSnapshot<File> snapshot) {
                  return new Image.file(snapshot.data);
                })
        );
      }
    }

**Comment by Rockvole** [comment]
This is the exception which I am getting :

Performing full restart...
Restarted app in 1,182ms.
I/flutter ( 4109): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4109): The following assertion was thrown building FutureBuilder<File>(dirty, state:
I/flutter ( 4109): _FutureBuilderState<File>#7c798):
I/flutter ( 4109): 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 482 pos 16: 'file !=
I/flutter ( 4109): null': is not true.
I/flutter ( 4109): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4109): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4109): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4109):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4109): When the exception was thrown, this was the stack:
I/flutter ( 4109): #2      new FileImage (package:flutter/src/painting/image_provider.dart)
I/flutter ( 4109): #3      new Image.file (package:flutter/src/widgets/image.dart:199:20)
I/flutter ( 4109): #4      MyApp.build.<anonymous closure> (file:///work/projects/flutter/image_test/lib/main.dart:24:26)
I/flutter ( 4109): #5      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
I/flutter ( 4109): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter ( 4109): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter ( 4109): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #77     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #99     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4742:32)
I/flutter ( 4109): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #102    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter ( 4109): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #108    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #124    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #128    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #131    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #136    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #137    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): MyApp.File=/data/data/com.example.imagetest/app_flutter/flutter_assets/battery_charge_background.png
I/flutter ( 4109): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #147    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4109): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #152    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #155    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #157    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #158    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #159    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #161    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #163    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #164    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #170    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #175    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #176    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #181    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #182    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #183    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #184    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #185    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #186    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #188    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #190    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #194    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #195    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #196    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #197    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #198    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #201    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #202    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #203    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #204    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #205    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #207    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #208    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #209    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #210    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #213    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #214    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #215    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #216    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #219    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #221    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #222    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #224    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #226    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #227    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #228    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #229    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #230    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #232    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #233    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #234    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4109): #235    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #236    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #237    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4109): #239    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4109): #240    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4109): #241    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4109): #242    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4109): #243    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4109): #244    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
I/flutter ( 4109): #245    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
I/flutter ( 4109): #246    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
I/flutter ( 4109): #247    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
I/flutter ( 4109): #248    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
I/flutter ( 4109): #249    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
I/flutter ( 4109): #250    runApp (package:flutter/src/widgets/binding.dart:699:7)
I/flutter ( 4109): #251    main (file:///work/projects/flutter/image_test/lib/main.dart:6:16)
I/flutter ( 4109): #252    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter ( 4109): #253    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 4109): (elided 2 frames from class _AssertionError)
I/flutter ( 4109): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Rockvole** [comment]
I am using android studio, flutter doctor :

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.2.11, on Linux, locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
[!] VS Code (version 1.22.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
Do you get the same error if you change the line to

     return snapshot.data != null ? new Image.file(snapshot.data) : new Container();

**Comment by zoechi** [comment]
When a frame is due, Flutter has to render one.
Waiting doesn't make sense.
 Dart doesn't support stopping execution of code while waiting anyway.

**Comment by Rockvole** [comment]
Ok, thanks for the help.

**Comment by Pooja275** [comment]
I m facing error on
 new Image.network("https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/lakes/images/lake.jpg",fit: BoxFit.cover,height: 100.0,width: 100.0,alignment: Alignment.center,),

[New Microsoft Office Word Document.docx](https://github.com/flutter/flutter/files/2025773/New.Microsoft.Office.Word.Document.docx)
