### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by dmjones** [flutter/flutter#16631]
## Steps to Reproduce

Attempted to restart my app, having made changes to a StatelessWidget so that a boolean constructor parameter is used to enable/disable a callback.

Just posting this because the framework asked me to :-)

The widget in question:

```
class IconTextButton extends StatelessWidget {
  final IconData icon;
  final String text;
  final VoidCallback callback;
  final bool enabled;

  IconTextButton(this.icon, this.text, this.callback,
  {enabled: true}); // <--- enabled is the new parameter

  @override
  Widget build(BuildContext context) {
    return new GestureDetector(
      onTap: (enabled) ? callback : null, 
      child: new Container(
        margin: const EdgeInsets.all(10.0),
        padding: const EdgeInsets.all(10.0),
        decoration: new BoxDecoration(
          border: new Border.all(
            color: Theme.of(context).primaryColor,
            width: 1.0,
          ),
          borderRadius: const BorderRadius.all(const Radius.circular(5.0)),
          color: Theme.of(context).primaryColor.withOpacity(0.1),
        ),
        child: new Row(
          children: <Widget>[
            new Icon(icon),
            new Container(
              margin: const EdgeInsets.only(left: 5.0),
              child: new Text(text),
            ),
          ],
        ),
      ),
    );
  }
}
```

## Logs

Logs from the IDE:

```
Performing hot reload...
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building IconTextButton(dirty):
Failed assertion: boolean expression must not be null

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#0      IconTextButton.build (package:project_grid/shared.dart)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#4      StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#6      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4362:32)
#7      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4752:17)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4362:32)
#14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4752:17)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#18     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#22     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#26     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#28     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4362:32)
#29     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4752:17)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#47     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#57     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#61     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#65     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#69     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#77     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#83     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4362:32)
#84     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4752:17)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#88     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#90     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#93     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#94     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#96     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#110    StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#114    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#120    ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#126    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#130    StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#132    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#136    ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
Reloaded 3 of 391 libraries in 1,747ms.
#140    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
#141    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
#142    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#143    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
#147    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#148    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#149    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided one frame from package dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Failed assertion: boolean expression must not be null
Another exception was thrown: A RenderFlex overflowed by 199680 pixels on the right.
Another exception was thrown: A RenderFlex overflowed by 99847 pixels on the bottom.
```

`flutter analyze` has a smoking gun look to it:

```
  warning • The final variable 'enabled' must be initialized at lib/shared.dart:53:3 • final_not_initialized_constructor_1
1 issue found.
(Ran in 8.2s)
```

## Flutter Doctor

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-GB)
    • Flutter version 0.2.8 at /Users/duncan/git/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/duncan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] Connected devices (1 available)
    • iPhone SE • AF39984C-77CB-4FBF-B4A4-E9E3627DDBB7 • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by dmjones500** [comment]
(The error was using `enabled` rather than `this.enabled`)

**Comment by zoechi** [comment]
@dmjones500 you could close the issue

**Comment by gregko** [comment]
I have also a completely bogus "Failed assertion: boolean expression must not be null" error that completely blocks my work progress... Tested today master, dev and beta channels, happens on every build. It happens on the following code fragment (processing OPDS xml feed):

``    for (var e2 in e.findElements('link')) {
      String type = e2.getAttribute('type')?.toString() ?? '';
      String rel = e2.getAttribute('rel')?.toString() ?? '';
      String href = e2.getAttribute('href')?.toString() ?? '';
      href = fullUrl(href, baseUrl);
      if (type.contains('application/atom+xml')) {
        opdsUrl = href;
        // but ManyBooks.net book entry does not have atom+xml link anymore, just
        // cover and thumbnail images link type "link type="application/epub+zip"
        // (possibly different types?) and
        // rel="http://opds-spec.org/acquisition" to download it. Or buy?
      } else if (type.contains('image/')) {
        print(rel);
        if (rel.contains('thumbnail')) { // bug in flutter, in some cases rel.contains('...') makes Failed assertion: boolean expression must not be null
          thumbUrl = wantCoverThumbs ? href : 'assets/graphics/book.png';
        } else {
          coverUrl = href;
        }
      } else if (rel.endsWith('/acquisition') ||
          rel.endsWith('/acquisition/open-access')) {
        downloadUrl = href;
      } else if (rel.endsWith('/acquisition/borrow')) {
        borrowUrl = href;
      } else if (rel.endsWith('/acquisition/sample')) {
        sampleUrl = href;
      }
    }

The offending line is marked with // bug in flutter comment. The rel variable is not null, the print(rel) instruction just before the crash outputs:

I/flutter (11647): http://opds-spec.org/image/thumbnail

and then I get a crash:

I/flutter (11647): Failed assertion: boolean expression must not be null

Any thoughts? Also tried replacing rel.contains('thumbnail') with rel.indexOf('thumbnail') > -1 - same error...

**Comment by DanAdrenaline** [comment]
This example code from google.io produces the same error if you comment out the where condition:
var filteredFish = widget.allFish.where((FishData data) {
      if (_viewType == ViewType.available) {
        return data.reservedBy == null || data.reservedBy == user.uid;
      } else {
        return data.reservedBy == user.uid;
      }
    }).toList();

**The below builds but produces the same error as above.**
var filteredFish = widget.allFish.where((FishData data) {
      //if (_viewType == ViewType.available) {
      //  return data.reservedBy == null || data.reservedBy == user.uid;
      //} else {
      //  return data.reservedBy == user.uid;
      //}
    }).toList();

**Comment by zoechi** [comment]
Change the constructor to
```
  IconTextButton(this.icon, this.text, this.callback,
  {enabled: true}) : this enabled = enabled ?? false; // <--- enabled is the 
```
to ensure `enabled won't be `null`

**Comment by ThinkDigitalRepair** [comment]
It would be nice if it mentioned which expression or allowed us somehow to find it. It points me to a line, but I don't see how the expression is null.

**Comment by zoechi** [comment]
@ThinkDigitalRepair the stack trace should point you to the expression.

**Comment by gregko** [comment]
At least a few Flutter builds back (maybe 2-3 months back) it used to be that the stack trace for "boolean must not be null" was pointing to a wrong code line. I did submit a bug report, don't know if that was fixed yet or not. Examine at least the next line of code, after the place the stack trace points - boolean null may be there.

**Comment by zoechi** [comment]
@ThinkDigitalRepair can you still reproduce? 
The code in the gist is not runnable to verify.
#17544 is also closed.

**Comment by volgin** [comment]
This code throws the same error:

```
bool _login = true;
@override
Widget build(BuildContext context) {
    return Scaffold(
        body: _login ? _loginPanel() : _signupPanel());
}
```

This code works:

```
static bool _login = true;
@override
Widget build(BuildContext context) {
    return Scaffold(
        body: _login ? _loginPanel() : _signupPanel());
}
```

The error message is misleading - boolean expression is not null in either case.

**Comment by gabrielziegler3** [comment]
It would be great if Flutter could say which line of code or which method ran into this problem, looking at all the conditions in the code can be painful

**Comment by citdevs** [comment]
Unhandled Exception: Failed assertion: boolean expression must not be null

void _register() async{
    setState(() {
      _isLoading = true;
    });

    var data = {
      'name' : name,
      'phone': phone,
      'email': email,
      'password': password,
      'address': address
    };

    var res = await Authapi().authData(data, '/register');
    var body = json.decode(res.body);
    if(body['success']){
      SharedPreferences store = await SharedPreferences.getInstance();
      store.setString('token', json.encode(body['token']));
      store.setString('user', json.encode(body['user']));
      print('Store: ${store}');
      //Navigator.push(context, MaterialPageRoute(builder: (context)=> DashboardPage()));
    }
    setState(() {
      _isLoading = false;
    });
  }

**Comment by wolfc01** [comment]
Same problem here,

Future<bool> _doLogin(String server, String Id, String uuid) async {
    String request = "http://" + server + "/login?id=" + Id + "&uuid=" + uuid;
    bool loginOk = false;
    http.Response resp = await http.get(request);
    if (resp.statusCode == 200) {
      Map<String, dynamic> data = json.decode(resp.body);
      **loginOk = data['sucess'];**
    }
    return loginOk;
}

rep.body contains:
{
  "success": true
}

at the bold line flutter fails with stacktrace:
E/flutter (11287): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Failed assertion: boolean expression must not be null
E/flutter (11287): #0      _MyHomePageState.LoginPage.<anonymous closure>.<anonymous closure> (package:questionnaire/main.dart:279:37)
E/flutter (11287): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (11287): #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (11287): #3      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter (11287): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter (11287): #5      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter (11287): #6      Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter (11287): #7      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
E/flutter (11287): #8      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
E/flutter (11287): #9      _doLogin (package:questionnaire/main.dart)
E/flutter (11287): <asynchronous suspension>
E/flutter (11287): #10     _MyHomePageState.LoginPage.<anonymous closure> (package:questionnaire/main.dart:278:11)
E/flutter (11287): #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (11287): #12     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (11287): #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (11287): #14     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (11287): #15     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (11287): #16     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (11287): #17     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (11287): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (11287): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (11287): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (11287): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (11287): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (11287): #23     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (11287): #24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (11287): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (11287): #26     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (11287): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (11287): 

C:\Users\vse>flutter -v doctor
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17763.1158], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\vse\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\vse\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.0

[√] Connected device (1 available)
    • SM G930F • 9886274c4e4f504759 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
