### ISSUE TITLE
Expose accessibility on iOS

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1664]

**Comment by abarth** [comment]
Todd said he was going to look at this issue.

**Comment by tvolkert** [comment]
https://github.com/flutter/engine/pull/2594 wires up basic knowledge of our widget tree exposed as accessible elements.

Sub-tasks that need doing:
- [ ] Communicate when a view is modal
- [ ] Default actions
- [ ] Incrementing and decrementing adjustable elements
- [ ] Scroll gestures
- [ ] Escape gesture and semantic escapes

**Comment by tvolkert** [comment]
Calling this done for v1.  I filed separate issues for the remaining tasks needed before we can call Flutter apps on iOS 100% accessible:

#3814
#3815
#3816
#3817
#3819
#3821
