### ISSUE TITLE
Make custom paint accessible

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1666]
We need a way for custom painters to provide additional semantic nodes subtrees.

**Comment by Hixie** [comment]
We need to take an arbitrary tree of SemanticsNode that we graft into the semantics tree.

We'll need this for datepicker.

**Comment by yjbanov** [comment]
AIs:

- [ ] Introduce `CustomPainterSemantics` that contains the same data as the `Semantics` widgets (importantly it also contains `key` field for diffing), is also stateless, but is not a `Widget`, does not contains a `child`, adds `Rect`, label, actions, and other semantics-specific fields
- [ ] Add `List<CustomPainterSemantics> buildSemantics(Size size)` method to `CustomPainter`, whose default implementation returns `const <CustomPainterSemantics>[]`, but concrete implementations can override and provide domain-specific semantics.
- [ ] `RenderCustomPaint` in `assembleSemanticsNode` calls `buildSemantics` and creates `SemanticsNode` list from `CustomPainterSemantics` list, and caches them. It also implements diffing algorithm that takes a new list of `CustomPainterSemantics` and updates previously created `SemanticsNode` list. It uses `key` field to find the correct location of a semantics node. `null` `key` field means we're updating nodes pair-wise, truncating or expanding the list as necessary.
- [ ] to reuse as much of the `Semantics` widget as possible, we will extract most of its fields into a `SemanticsProperties` class (or mixin, if possible) and forward to it both from `Semantics` and `CustomPainterSemantics`.

This change will be implemented first, then https://github.com/flutter/flutter/pull/13152 will be updated to use the new infrastructure.

/cc @goderbauer

**Comment by Hixie** [comment]
> diffing algorithm

Please try to match the algorithm in framework.dart that we use for widget child lists. Also, maybe only allow LocalKeys, not GlobalKeys, for CustomPainterSemantics objects.
