### ISSUE TITLE
Would like instructions on how to use EmojiCompat in a Flutter-using app

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#16660]
My understanding from reading the docs on EmojiCompat is that it's a/the recommend way to use Emojis on Android?  Seems like it requires one line in your gradel, plus an initialization in onCreate.

https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat.html

Would be good to verify that Flutter's minkin/libtxt font-lookup correctly finds Emoji's provided by EmojiCompat and what the few lines added to a Flutter create template should be. (FYI @jason-simmons)

This is non-urgent, but probably affects whatever the canonical "FriendlyChat" demo should look like and given that Emoji usage is relatively common, this maybe a relatively common Android library for folks to run in to.

**Comment by Hixie** [comment]
As far as I can tell, EmojiCompat is for apps that use Android views (specifically the TextView and its android.text.style.ReplacementSpan feature). So it wouldn't work for Flutter at all.

I don't understand why EmojiCompat is needed, though... why can't the OS just update the emoji font?

**Comment by eseidelGoogle** [comment]
I heard about this from @siyamed, I suspect he can tell us why?

**Comment by siyamed** [comment]
there is no system font update mechanism in the Android OS.  However it is possible to download  fonts using [Downloadable Fonts](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts.html). EmojiCompat is a layer on top of Downloadable Fonts and Noto Emoji font can be fetched using the query provided [here](https://github.com/googlesamples/android-EmojiCompat)

The downloaded font is shared between all apps (both in memory and on disk, though this depends on the android version). Don't know much about Flutter text stack, maybe Flutter can use downloadable fonts and add the downloaded font to the font fallback stack.

**Comment by Sfshaza** [comment]
It sounds like this could use some engineering support. Not adding to doc content plan until it's clearer.

**Comment by kassim** [comment]
any movement on a solution to this? or a recommended workaround?

**Comment by eseidelGoogle** [comment]
FYI @xster for Android-specific adaptations.

**Comment by xster** [comment]
AFAICT, EmojiCompat does 2 things. 

Most of it is not useful to us ("EmojiCompat identifies emoji for a given CharSequence, replaces them with EmojiSpans"). The downloadable font configuration via FontRequest part isn't particularly useful either since Flutter already has services/font_loader.dart. 

The `implementation "androidx.emoji:emoji:1.0.0"` gradle library is potentially useful since it's bundles Android's opinion on what the best font should be for emojis (currently NotoColorEmojiCompat.ttf). The font is 7mb so it should definitely be selectively used rather than be in the engine. 

This should be a plugin.

**Comment by dreamer2q** [comment]
Is there a way to detect whether an emoji character is supported in old android systems? ( If this can be detected, I can switch to a default emoji character as a fallback choice )

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
