### ISSUE TITLE
didReceiveLocalNotification not firing when plugin is registered as an app delegate in iOS

### ISSUE THREAD

**Issue by MaikuB** [flutter/flutter#16662]
## Steps to Reproduce

Sample code found in the example project of the plugin I've been developing at https://github.com/MaikuB/flutter_local_notifications/tree/didReceiveLocalNotificationIssue

Create a plugin and in the iOS code for that plugin. Add the plugin as an application delegate

```
[registrar addApplicationDelegate:instance];
```

add code to handle when a local notification has been received
```
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
   ...
}
```

Add code to display a notification and run the app on an iOS device older than version 10 (tried this on an iOS 9 simulator). _didReceiveLocalNotification_ is never fired but other application delegate methods like detecting if the app has entered the background are working fine.

## Logs

flutter run logs

[flutter run logs.txt](https://github.com/flutter/flutter/files/1919748/flutter.run.logs.txt)

No issues found through flutter analyze command

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D102, locale en-AU)
    • Flutter version 0.2.8 at /Users/michaelbui/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/michaelbui/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/michaelbui/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.0.2
    • Dart plugin version 173.4700

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone 6s Plus • 30903B0A-AC8E-411A-A1A9-08246FE97C7F • ios • iOS 9.0 (simulator)

• No issues found!
```

**Comment by mravn-google** [comment]
It appears we have not wired up plugins with the deprecated [application:didReceiveLocalNotification:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622930-application?language=objc), nor with the iOS 10 replacement, [userNotificationCenter:willPresentNotification:withCompletionHandler:](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc).

Until that happens in `flutter/engine`, rolls into `flutter/flutter`, and arrives into a stable Flutter build, I suggest documenting with your plugin that app authors would have to wire that up themselves in their `UIApplicationDelegate` class.

**Comment by MaikuB** [comment]
Yep I have documented that but will add a note that it's dependent on the engine to wire it up. Cheers :)

**Comment by bkonyi** [comment]
@MaikuB sorry this took so long to resolve! Once this change rolls into the Flutter framework multiple plugins should be able to receive `didReceiveLocalNotification` invocations.

**Comment by MaikuB** [comment]
All good, thanks for the update @bkonyi :)

How can one tell when the change has rolled into the framework though? More specifically I'm trying to track when it's available on beta as opposed to master or dev. I'm assuming it's to do with the commits on rolling the engine to a specific hash?

**Comment by Hixie** [comment]
Should be rolled in by now :-)

**Comment by MaikuB** [comment]
@rlee1990 I've done this about a week ago though out of courtesy for the Flutter team, I would suggest taking such questions elsewhere since it's off-topic for them/this board :)
