### ISSUE TITLE
Does flutter support the iOS Tool Bar?

### ISSUE THREAD

**Issue by allowthere** [flutter/flutter#16683]
iOS has two types of action bars - the [Tool Bar](https://developer.apple.com/ios/human-interface-guidelines/bars/toolbars/) and the [Tab Bar](https://developer.apple.com/ios/human-interface-guidelines/bars/tab-bars/).

I found where flutter (Cupertino) has [Tab Bar](https://docs.flutter.io/flutter/cupertino/CupertinoTabScaffold-class.html) support, but I can't [find](https://docs.flutter.io/flutter/cupertino/cupertino-library.html) Flutter's equivalent Tool Bar. Am I missing something?

**Comment by najeira** [comment]
You can create a widget like ToolBar by yourself using Row etc.

Or you can use [Scaffold#persistentFooterButtons](https://docs.flutter.io/flutter/material/Scaffold/persistentFooterButtons.html)

**Comment by xster** [comment]
I'm going to close this one since the tool bar doesn't seem to have enough design complexity to warrant bundling one in Cupertino instead of just using Row etc.

**Comment by AppleEducate** [comment]
> You can create a widget like ToolBar by yourself using Row etc.
> 
> Or you can use Scaffold#persistentFooterButtons

This is not supported on the Cupertino Page Scaffold, only on material. To create a tool bar you want to be able to hide and show it as well as support showing the tool bar when the keyboard appears (very common on iOS) as for many cases the tool bar is how you close a bottom sheet if you entering in a number for example.

**Comment by cmengler** [comment]
I've created a workaround as a package `cupertino_toolbar` @ https://pub.dartlang.org/packages/cupertino_toolbar

Essentially you place `CupertinoToolbar` as the `[child]` to a `CupertinoPageScaffold` and move the existing UI that was defined as the child to the `[body]` of the toolbar component. The toolbar actions are defined as a list of `[items]` of `CupertinoToolbarItem`.
