### ISSUE TITLE
Wrong CupertinoIcons

### ISSUE THREAD

**Issue by allowthere** [flutter/flutter#16685]
## Steps to Reproduce

I display `Icon(CupertinoIcons.right_chevron)` and I get a dark calculator (F413 on [this](https://raw.githubusercontent.com/flutter/cupertino_icons/master/map.png) map).

Also, CupertinoIcons.left_chevron is F411.

To get a left_chevron, i write:
 `const IconData left_chevron = const IconData(0xf3cf,
    fontFamily: 'CupertinoIcons',
    fontPackage: 'cupertino_icons',
    matchTextDirection: true);`

It seems that all values are off by exactly one row in the chart.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

[✓] Flutter (Channel dev, v0.3.0, on Linux, locale en_US.UTF-8)
    • Flutter version 0.3.0 at /home/user/flutter
    • Framework revision c73b8a7cf6 (5 days ago), 2018-04-12 16:17:26 -0700
    • Engine revision 8a6e64a8ef
    • Dart version 2.0.0-dev.47.0.flutter-4126459025

**Comment by allowthere** [comment]
But some have already been fixed (For example, down_arrow shows is correct, despite the [source](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/icons.dart) being wrong).

**Comment by xster** [comment]
Ah, I thought I already fixed them. Will check again. Feel free to submit a PR to change as well.
