### ISSUE TITLE
fatal: unable to access 'https://flutter.googlesource.com/gallery-assets/': Failed to connect to flutter.googlesource.com port 443: Operation timed out

### ISSUE THREAD

**Issue by linguowu** [flutter/flutter#16694]
## Issues

when i run the example of flutter gallery,it shows below  

## Logs

Git error. Command: git fetch
fatal: unable to access 'https://flutter.googlesource.com/gallery-assets/': Failed to connect to flutter.googlesource.com port 443: Operation timed out

## Flutter Channel
beta
## ps
I can access [https://flutter.googlesource.com/gallery-assets/](https://flutter.googlesource.com/gallery-assets/) by chrome

**Comment by zoechi** [comment]
Can you please add the output of `flutter doctor -v`?

**Comment by linguowu** [comment]
@zoechi thanks for your comment, the output of flutter doctor -v
country5$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.12 16A323, locale zh-Hans-CN)
    • Flutter version 0.2.8 at /Users/country5/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/country5/Development/android-sdk-macosx
    • Android NDK at /Users/country5/Development/android-sdk-macosx/ndk-bundle
    • Platform android-27, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a
    ✗ Flutter requires a minimum Xcode version of 9.0.0.
      Download the latest version or update via the Mac App Store.
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Nexus 6P • ENU7N15A30000390 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.

**Comment by linguowu** [comment]
help....

**Comment by Solomon-8** [comment]
facing the same problem,when run git clone https://flutter.googlesource.com/gallery-assets get Timed out,I  have checked my vpn,i can access it by chrome,but can't git clone.
is there mirror in github or anywhere else?
I mean which site can be access in china.

**Comment by Solomon-8** [comment]
found way to solve this problem 😀 
http://flutter-dev.cn/topic/75/%E5%B7%B2%E8%A7%A3%E5%86%B3-%E5%AF%BC%E5%85%A5%E5%AE%98%E6%96%B9demo-flutter-gallery-flutter-packages-get-%E8%BF%90%E8%A1%8C%E5%87%BA%E9%94%99%E6%80%8E%E4%B9%88%E5%8A%9E

find a mirror in https://gitee.com/creatint/gallery-assets.git
but it's latest commit is 5month ago....

**Comment by bagualing** [comment]
I also encountered the same problem. But I solved it by setting up git's proxy.
>git config --global http.proxy http://127.0.0.1:1880
>git config --global https.proxy http://127.0.0.1:1880

127.0.0.1:1880 is my proxy service's address & port.

**Comment by yy1300326388** [comment]
I have the same problem

**Comment by slb2709673** [comment]
哈哈哈哈

**Comment by ikkyu0319** [comment]
@noiary 貌似还不行啊，直接打开url能打开~

**Comment by yy1300326388** [comment]
看这里我的回答：[#13763](https://github.com/flutter/flutter/issues/13763)

```java
flutter_gallery_assets:
   git:
  #   url: https://flutter.googlesource.com/gallery-assets
     url: https://github.com/yy1300326388/gallery-assets-china
```

> 记得来个 Star [https://github.com/yy1300326388/gallery-assets-china](https://github.com/yy1300326388/gallery-assets-china)

**Comment by zoechi** [comment]
Is this solved?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
