### ISSUE TITLE
Publish API docs for Firebase service

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1669]
Tracking issue so we don't forget. We want to help our developers explore the Firebase service.

**Comment by collinjackson** [comment]
https://www.dartdocs.org/documentation/firebase/latest/firebase/firebase-library.html

**Comment by collinjackson** [comment]
I added a link to docs in README of https://github.com/flutter/firechat-flutter.

**Comment by sethladd** [comment]
Thanks for checking into it, but we might want to update the README for that package. There's no hint that it can be used with Flutter, nor if there are any special gotchas for Flutter+Firebase.  https://www.dartdocs.org/documentation/firebase/0.6.5+1/index.html

**Comment by collinjackson** [comment]
I think the next steps are:

[ ] Conditional imports need to be supported in Dart. https://github.com/dart-lang/sdk/issues/24581
[ ] We merge our changes into https://github.com/firebase/firebase-dart. https://github.com/firebase/firebase-dart/issues/71
[ ] Ensure that the Firebase dartdoc describes Flutter usage
[ ] Update the dart Firebase package

Alternatively, we could publish a separate Dart package now for Flutter-enabled Firebase, but that might cause more confusion down the road when we merge into one repo.

**Comment by sethladd** [comment]
We can assume that "Conditional imports need to be supported in Dart." will be a long time coming. How does that change our approach to documenting our Firebase service?

**Comment by sethladd** [comment]
Firebase API docs are at https://github.com/flutter/firebase-dart

**Comment by collinjackson** [comment]
For now:
  * flutter/firebase-dart should link to the firebase/firebase-dart's dartdoc, since the APIs are the same. 
  * Caveats and usage should be noted in the flutter/firebase-dart README.

If we get tired of waiting for conditional imports, we can update firebase-dart to a new major version that doesn't rely on conditional imports but instead has developers import a platform-specific class (FirebaseJs, FirebaseFlutter) when they want to construct a Firebase from a URL.

**Comment by kasperl** [comment]
@sethladd FWIW, we expect to land support for conditional imports in Dart within days -- not weeks. @floitschG is working on it :)

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1030. Any further collaboration will be done there.
