### ISSUE TITLE
Enable logcat and android profiler from flutter projects

### ISSUE THREAD

**Issue by fmatosqg** [flutter/flutter#16691]
They still contain valuable features that can be used while debugging, allowing for skipping opening android module.

**Comment by zoechi** [comment]
Can you elaborate more what the request is about?
Is this about IDE support?
`adb logcat` works with Flutter apps. 
(I don't know about Android profiler.)

**Comment by fmatosqg** [comment]
Android Studio support. Those panels are visible for Android projects but not for Flutter ones.

**Comment by zoechi** [comment]
Is this still missing in AS?
IntelliJ provides that view 

![image](https://user-images.githubusercontent.com/405837/42768519-0bdd2e28-8920-11e8-89f3-2bc8f66a0975.png)

**Comment by ricardobrg** [comment]
It's not woking in AS for me... It says "Configure Android SDK" but it is configured already...

I'm working with AS 3.1.3 in Ubuntu 18.04

**Comment by zoechi** [comment]
@ricardobrg That sounds like a different problem. Please create a new issue with the issue template filled out.

**Comment by ricardobrg** [comment]
@zoechi I don't think that it's different... I just wanted to add some info since it was waiting response from OP. In Android Studio the logcat panel doesn't work with flutter projects. 
![captura de tela de 2018-07-27 11-08-55](https://user-images.githubusercontent.com/8357343/43325612-85d4eaca-918d-11e8-9021-168626041ff7.png)
It says "Configure Android SDK" but it's already configured. I'm able to debug Android apps using the debugger but not the logcat.

**Comment by zoechi** [comment]
Works the same in IntelliJ and Android Studio for a simple Flutter project.

![image](https://user-images.githubusercontent.com/405837/43336455-433a1246-91d1-11e8-8f65-e56d90e75687.png)

**Comment by HassanMeer** [comment]
Goto File -> Project structure and choose your platform sdk, 
api 27 ...ISSUE OF Logcat (Please configure SDK) will resolve INSHAllah .
![adc4m](https://user-images.githubusercontent.com/45714713/49686982-3f09d600-fb1e-11e8-9ade-a41d515ec3ad.png)

**Comment by hjJunior** [comment]
To solve this problem I just opened on Android studio the `android` folder

**Comment by mpeng5120** [comment]
> Goto File -> Project structure and choose your platform sdk,
> api 27 ...ISSUE OF Logcat (Please configure SDK) will resolve INSHAllah .
> ![adc4m](https://user-images.githubusercontent.com/45714713/49686982-3f09d600-fb1e-11e8-9ade-a41d515ec3ad.png)

this solve my  problem thanks

**Comment by mofada** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/22286246/66974007-4ac61180-f0cc-11e9-8f01-d3caab21b679.png)

![image](https://user-images.githubusercontent.com/22286246/66974013-50bbf280-f0cc-11e9-9b99-f71aa429e447.png)

**Comment by Kav47** [comment]
To solve this:
1. Go to Project Settings (**File -> Project Structure**)
2. Change Project SDK to API 27 ([Left Tab] **Project Settings -> Project**)
<img width="974" alt="image" src="https://user-images.githubusercontent.com/4541988/72197786-3d939700-341d-11ea-9b2d-1fdb99174693.png">

3. Change "Build Target" for "Android API 27 Platform" to "Android API 28" ([Left Tab]**Platform Settings -> SDKs**)
<img width="591" alt="image" src="https://user-images.githubusercontent.com/4541988/72197882-4c2e7e00-341e-11ea-9853-b98b22b99a19.png">

4. Then Click Apply and OK

**Comment by asidt** [comment]
This happens still nowadays, with a clean Flutter project started from scratch. What worked for me , like mentioned in https://github.com/flutter/flutter/issues/16691#issuecomment-448598851 , was in Studio to Edit -> Open ... and point to the android subproject within the Flutter project. Once opened and synced, closed the second window of Studio opened, and the first this time had logcat tab finally working.

**Comment by jasonflaherty** [comment]
> To solve this problem I just opened on Android studio the `android` folder

This was easy. Thanks. Just open android folder, click record in the logcat area, then go to your device / emulator and begin navigating around.
