### ISSUE TITLE
Why is the AnimatedBuilder's builder called after animation ends.

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#16699]
Need some help with animations.
I running an animation using AnimatedBuilder. What I see is that after the animation finishes (i.e. await animationController.forward returns ) the builder method is called one more time. Anyone knows why?

See the gist I have created below to demo the issue. If you put a breakpoint on line 27 you will see that the animation has finished by then and after this the _animateBuilder is called one more time. 

[Code Gist ](https://gist.github.com/manujbahl/2bfd2e155de94b614e55c5c69fd7712c)
https://gist.github.com/manujbahl/2bfd2e155de94b614e55c5c69fd7712c

I don't understand why the builder is called after the animation finishes. This is causing issues for me because it resets the widget. I want it to maintain its last frame of the animation and did not expect the builder to be called after the animation ends.

**Comment by manujbahl** [comment]
@Hixie @xster any ideas ?

**Comment by Hixie** [comment]
You should assume that builders will get called arbitrarily, possible up to every frame. If we don't call a builder, it's just an optimisation.

**Comment by Hixie** [comment]
I tried looking at the gist but it's pretty long (hundreds of lines); can you try making it shorter by removing the bits that aren't needed to show the problem?

**Comment by manujbahl** [comment]
OK I updated the gist to make it considerable smaller.
Put breakpoints at line# 53 and 112.

i was not expecting to see the breakpoint at 112 hit after 53. (click the Animate button)

**Comment by Hixie** [comment]
The first thing that jumps out is you have several Stateless Widgets that have state. You can run the analyzer (`flutter analyze`) to find issues like this.

Having said that, as far as I can tell the code is working as expected. On the last frame of the animation, in the animation phase, the animation reached its last value, causes setState to be called, then the future completes, so line 53 runs. After that we have the build phase, at which time the widgets build, and you hit line 123.
