### ISSUE TITLE
Crash when running my app with Flutter master branch

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#16692]
It works well in last weekend (4/15) , but after I pull the lasted Flutter master codes , crash happend.

this is the logs:

<img width="499" alt="2018-04-18 3 05 38" src="https://user-images.githubusercontent.com/13853/38916447-0732c96a-431a-11e8-8157-a1dcba8de565.png">

I could run same code on Beta branch.

**Comment by zoechi** [comment]
Can you please add the output of `flutter doctor -v`?

**Comment by jonjon-coder** [comment]
@zoechi 

[✓] Flutter (Channel master, v0.3.1-pre.35, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.3.1-pre.35 at /Users/*/Documents/work/flutter
    • Framework revision 7b163c7c0b (8 hours ago), 2018-04-18 20:31:45 -0700
    • Engine revision 3cc8d82895
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/*/Library/Android/sdk
    • Android NDK at /Users/*/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/jonjon/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone 8 • 3332829E-AB4B-4D91-8762-680A565135E0 • ios • iOS 11.3 (simulator)

• No issues found!

**Comment by realcarlos** [comment]
It seems fixed .
