### ISSUE TITLE
Spaces in Text collapse into a single space when many are next to each other.

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#167]
<a href="https://github.com/apwilson"><img src="https://avatars.githubusercontent.com/u/142874?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [apwilson](https://github.com/apwilson)**
_Monday Sep 21, 2015 at 17:55 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1253_

----

**Comment by FlutterIssues** [comment]
<a href="https://github.com/apwilson"><img src="https://avatars.githubusercontent.com/u/142874?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apwilson](https://github.com/apwilson)**
_Monday Oct 12, 2015 at 21:47 GMT_

----

This is partially fixed - spaces have intrinsic height but multiple spaces still collapse down to one.  I'll edit the title to reflect that.

**Comment by Hixie** [comment]
We should just never collapse spaces.

**Comment by abarth** [comment]
I fixed this.
