### ISSUE TITLE
Flutter TextFormField space between  input text and the bottom line.

### ISSUE THREAD

**Issue by GOHILCHIRAG** [flutter/flutter#16704]
I am an anroid developer and I have just started developing for flutter. I am creating a login screen in which TextFormField is used with label but the space between the input text and the bottom line is larger as from android Edittext, so am I missing some property or it behaves likes this?
![device-2018-04-18-140053](https://user-images.githubusercontent.com/12772015/38921453-731a06d6-4313-11e8-9b41-420ae3e424ff.png)
![device-2018-04-18-140013](https://user-images.githubusercontent.com/12772015/38921454-734afeda-4313-11e8-9a57-8b572248783b.png)

**Comment by engr-zeeshan** [comment]
I also have created a form and getting this space between text and bottom line

**Comment by GOHILCHIRAG** [comment]
@HansMuller Hey thanks. The link you shared has the perfect solution for my problem. It is solved now.
![device-2018-04-19-182637](https://user-images.githubusercontent.com/12772015/39011585-784ee276-442f-11e8-9e23-187c6393f86f.png)

**Comment by Meet-Vyas** [comment]
But the error here is that now the labelText and hintText are getting squeezed(i.e are just starting directly no padding or margin inside the border) if the border is enabled
![2](https://user-images.githubusercontent.com/33172289/59020544-d353bc00-8867-11e9-8d2a-2a309ccd4a79.jpg)
![1](https://user-images.githubusercontent.com/33172289/59020546-d51d7f80-8867-11e9-84db-1243d2ed3434.jpg)

**Comment by krossroll** [comment]
> But the error here is that now the labelText and hintText are getting squeezed(i.e are just starting directly no padding or margin inside the border) if the border is enabled
> ![2](https://user-images.githubusercontent.com/33172289/59020544-d353bc00-8867-11e9-8d2a-2a309ccd4a79.jpg)
> ![1](https://user-images.githubusercontent.com/33172289/59020546-d51d7f80-8867-11e9-84db-1243d2ed3434.jpg)

use contentpadding: const Edge.........
in the decoration

**Comment by atul-chaudhary** [comment]
As described above the issue can be solved by using ` contentpadding` property in textField and here is the code.

`
TextField(
                        //maxLength: 10,
                        maxLines: 1,
                        minLines: 1,
                        keyboardType: TextInputType.number,
                        decoration: InputDecoration(
                            //labelText: "Phone number",
                            hintText: "Phone number",
                            contentPadding: EdgeInsets.all(5),
                            isDense: true,
                            enabledBorder: UnderlineInputBorder(
                                borderSide: BorderSide(color: Colors.grey)),
                            focusedBorder: UnderlineInputBorder(
                                borderSide: BorderSide(color: Colors.red[400]))
                            //border: InputBorder.none
                            ),
                      ),
`
