### ISSUE TITLE
The following NoSuchMethodError was thrown while handling a gesture

### ISSUE THREAD

**Issue by santoshgistto** [flutter/flutter#16709]
More details here
https://github.com/shamblett/xml2json/issues/11

**Comment by jason-simmons** [comment]
The Xml2Json code is catching an exception and reading the exception's `message` field here:
https://github.com/shamblett/xml2json/blob/bce817c21622b5981f2acab5b9dc788330dc60af/lib/src/Xml2Json.dart#L55

But the exception that was thrown is a Dart `CastError` that does not have a `message` field.

I'd suggest patching that line to use `e.toString()` (as is done elsewhere in Xml2Json.dart)

**Comment by zoechi** [comment]
Is there still something to do for the Flutter team?
Did the suggestion solve your problem?

**Comment by santoshgistto** [comment]
currently i am not using xml2json package.
Thanks @zoechi  💯

**Comment by zoechi** [comment]
Thanks for the update. Feel free to create a new issue.
