### ISSUE TITLE
Need to be able to specify a global replacement font for Emojis

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#16702]
In order to be consistent across OSs and to support a wider range of Emoji, we would like to use a custom Emoji font (called Emoji One).
The problem is that, even if I saw some issues related to the fact that libtxt right now has a per character fallback strategy, I didn’t find a clear example on how to set our custom Emoji font inside the stack of this fallback fonts, so that it can be correctly picked by the Text renderer independently from the theme font.

**Comment by zoechi** [comment]
#16660 might be related

**Comment by GaryQian** [comment]
Have not tested the exact use case but yes, the fallback system should allow you to specify a font to use for emojis that overrides the default emoji fallback.

If you can verify it works for your specific use case, that would be great!

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
