### ISSUE TITLE
Error message when switching to Android

### ISSUE THREAD

**Issue by Henge9** [flutter/flutter#16710]
This error message only appear after I have changed os to Android. When I change back to iOS it works again. 

## Steps to Reproduce

- Start flutter with `flutter run`.
- Press o to change operating system.
- Press o or r and the the error appear

## Logs
**flutter run**
 `❰❙~/dev/vnext(git✱≠NHA2-50_Simple_Login_Mock)❱✔≻ flutter run
Launching lib/main.dart on iPhone SE in debug mode...
Running Xcode clean...                                       0.8s
Starting Xcode build...
 ├─Assembling Flutter resources...                    3.2s
 └─Compiling, linking and signing...                  1.8s
Xcode build done                                             5.9s
asdf 320.0
320.0
Syncing files to device iPhone SE...                         1.9s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone SE is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

asdf 320.0
Switched operating system to android

asdf 320.0
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building SlideTransition(animation: AnimationController#ff23a(⏭
1.000; paused; for MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.40, 0.00, 0.20,
1.00)➩Tween<Offset>(Offset(0.0, 0.3) → Offset(0.0, 0.0))➩Offset(0.0, 0.0), state:
_AnimatedState#c92b0):
'package:flutter/src/rendering/object.dart': Failed assertion: line 1792 pos 12: '() {
final AbstractNode parent = this.parent;
if (parent is RenderObject)
return parent._needsCompositing;
return true;
}()': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      RenderObject.markNeedsCompositingBitsUpdate (package:flutter/src/rendering/object.dart)
#3      RenderObject.attach (package:flutter/src/rendering/object.dart:1232:7)
#4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2588:11)
#5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:128:13)
#6      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1077:11)
#7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2583:7)
#8      SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4652:18)
#9      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4496:35)
#10     Element._activateWithParent (package:flutter/src/widgets/framework.dart:2957:5)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2882:18)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#53     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#59     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#63     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
#64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
#65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
#70     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#71     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#72     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided 3 frames from class _AssertionError and package dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
Another exception was thrown: Tried to paint a RenderObject before its compositing bits were updated.
Switched operating system to iOS
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 3099 pos 12: '_ancestorChain.length == 1': is not`

**flutter analyze**
`❰❙~/dev/vnext(git✱≠NHA2-50_Simple_Login_Mock)❱✔≻ flutter analyze
Analyzing /Users/henge/dev/vnext...
  hint • 'child' is deprecated and shouldn't be used at lib/presentation/event_details.dart:97:61 • deprecated_member_use
1 issue found.
(Ran in 6.5s)`

## Flutter Doctor
`❰❙~/dev/vnext(git✱≠NHA2-50_Simple_Login_Mock)❱✘≻ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-SE)
    • Flutter version 0.2.8 at /Users/henge/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/henge/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone SE • F4FB5CA0-CA86-4981-A3EE-87B3C1B0A3BF • ios • iOS 11.3 (simulator)

• No issues found!`

**Comment by zoechi** [comment]
What code causes this error?

**Comment by Henge9** [comment]
I get the same error with a new project. And it is the same on a android phone as in the iOS simulator.

**Comment by ohir** [comment]
Confirmed with vanilla "counter" example app from AS templates with:
```
Flutter (Channel dev, v0.3.2, on Linux, locale pl_PL.utf8)
Framework revision 44b7e7d3f4 (9 days ago), 2018-04-20 01:02:44 -0700
Engine revision 09d05a3891
Dart version 2.0.0-dev.48.0.flutter-fe606f890b
Platform android-27, build-tools 27.0.3
Android Studio (version 3.1)
Flutter plugin version 23.2.2
Dart plugin version 173.4700
OpenJDK Runtime build 1.8.0_152-release-1024-b01
```
on an `android-x86 • Android 6.0 (API 23) (emulator)`
```
Switched platform rendering to iOS.
I/flutter (31743): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
I/flutter (31743): The following assertion was thrown building _CupertinoBackGestureDetector<dynamic>(state:
I/flutter (31743): _CupertinoBackGestureDetectorState<dynamic>#626e6):
I/flutter (31743): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1792 pos 12: 
[...cut ~140 lines...]
I/flutter (31743): Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#b3c0a DETACHED
Switched platform rendering to Android.
```
This exception kicks in **AFTER** returning to Android platform.
[✓] Android -> iOS - counter still counts; then iOS -> Android triggers this exception.

Additional log lines:
```
I/flutter (31743): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1091 pos 12: 'child.parentData != null': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3489 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3489 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31743): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter (31743): Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#28fa6 NEEDS-PAINT DETACHED
I/flutter (31743): Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#63ce6 NEEDS-PAINT DETACHED
I/flutter (31743): Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#b3c0a NEEDS-PAINT DETACHED
I/flutter (31743): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter (31743): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1457 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter (31743): Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#b3c0a DETACHED
Switched platform rendering to Android.
```

**Comment by brilliant-ember** [comment]
I have the same exception as well, I think it has to do with an assertion in rendering/object.dart

**Comment by ibhavikmakwana** [comment]
Got the same issue while toggling from ios to android

```
The following assertion was thrown building _CupertinoBackGestureDetector<dynamic>(state:
    _CupertinoBackGestureDetectorState<dynamic>#98c0f):
    'package:flutter/src/rendering/object.dart': Failed assertion: line 1785 pos 12: '() {
          final AbstractNode parent = this.parent;
          if (parent is RenderObject)
            return parent._needsCompositing;
09-14 18:58:01.349 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter:       return true;
        }()': is not true.
09-14 18:58:01.355 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
    more information in this error message to help you determine and fix the underlying cause.
    In either case, please report this assertion by filing a bug on GitHub:
09-14 18:58:01.356 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter:   https://github.com/flutter/flutter/issues/new
    When the exception was thrown, this was the stack:
09-14 18:58:01.368 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #2      RenderObject.markNeedsCompositingBitsUpdate (package:flutter/src/rendering/object.dart:1785:12)
    #3      RenderObject.attach (package:flutter/src/rendering/object.dart:1225:7)
    #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2654:11)
    #5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
    #6      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1070:11)
    #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2649:7)
    #8      SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4681:18)
    #9      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4525:35)
    #10     Element._activateWithParent (package:flutter/src/widgets/framework.dart:2986:5)
09-14 18:58:01.369 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2911:18)
    #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
    #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #15     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
    #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
09-14 18:58:01.370 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
    #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
09-14 18:58:01.371 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
    #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
09-14 18:58:01.372 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
09-14 18:58:01.373 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
    #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
    #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
    #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
09-14 18:58:01.374 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
    #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
    #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
09-14 18:58:01.375 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
09-14 18:58:01.377 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #45     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
    #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
    #51     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
    #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
09-14 18:58:01.378 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
09-14 18:58:01.380 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
    #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
09-14 18:58:01.381 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
09-14 18:58:01.382 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
09-14 18:58:01.383 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
    #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
    #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #69     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
    #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
    #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
    #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
09-14 18:58:01.384 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
    #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
    #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
09-14 18:58:01.385 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #79     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
    #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
09-14 18:58:01.386 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
    #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
    #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #85     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
    #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
09-14 18:58:01.387 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
09-14 18:58:01.388 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
    #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
    #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
    #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
    #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
    #96     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
    #97     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
    #98     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
09-14 18:58:01.389 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: (elided 3 frames from class _AssertionError and package dart:async)
    ════════════════════════════════════════════════════════════════════════════════════════════════════
09-14 18:58:01.403 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
09-14 18:58:01.406 9664-9692/com.ibhavikmakwana.fluttermovieapp I/chatty: uid=10096(com.ibhavikmakwana.fluttermovieapp) Thread-2 identical 2 lines
09-14 18:58:01.408 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
09-14 18:58:01.409 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1084 pos 12: 'child.parentData != null': is not true.
    Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1084 pos 12: 'child.parentData != null': is not true.
09-14 18:58:01.410 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
09-14 18:58:01.413 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
09-14 18:58:01.414 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1084 pos 12: 'child.parentData != null': is not true.
09-14 18:58:01.416 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
09-14 18:58:01.417 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
09-14 18:58:01.468 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: NoSuchMethodError: The method '_enableMutationsToDirtySubtrees' was called on null.
09-14 18:58:01.471 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
09-14 18:58:01.473 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#d92ca NEEDS-PAINT DETACHED
    Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#6f977 NEEDS-PAINT DETACHED
09-14 18:58:01.475 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#173f2 NEEDS-PAINT DETACHED
09-14 18:58:01.476 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
    Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
09-14 18:58:01.483 9664-9692/com.ibhavikmakwana.fluttermovieapp I/flutter: Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#173f2 DETACHED
```
