### ISSUE TITLE
Update FlutterLogoDecoration

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16713]
We should change "normal" to "multiply" on this line:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/flutter_logo.dart#L333

...and update the gradient colours to 0x661A237E at top 0 and 0x001A237E at stop 1.

**Comment by zoechi** [comment]
Is this fixed? I see `multiply` at the linked location.

**Comment by Hixie** [comment]
I think I meant change multiply to normal.

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by ADVavvas** [comment]
After a quick look it looks like `multiply` is the correct blend mode (since it's for the shadow). As far as the gradient colours are concerned, I'm not too sure but they seem out of place compared to the other values.

If that's not the case I'd be happy to take another look and fix the issue.

**Comment by Pragya007** [comment]
@Hixie  Do I need to change multiply to normal also which color you want to change the shades of blue used..???

Please tell me I want to fix this issue..
