### ISSUE TITLE
Idea: Reduce nesting in Flutter

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#16714]
I see a bunch of complaints about the levels of nesting in flutter due to Padding / Margin etc, and why doesn't every Widget have Padding ?
The answer is that Flutter focuses on Composition over inheritance - so just make your own widget if you want that.

I think that there is still scope for improvement while still using composition. What if we add an appearance parameter which every widget uses but provides some of the commonly used Widgets ? This way we don't need to make a new Widget because we want 10 buttons with identical padding.
e.g.
```dart
    Appearance myAppearance = new Appearance(
               padding: const EdgeInsets.all(8.0), 
               margin: new EdgeInsets.symmetric(horizontal: 20.0),
               centerVertical: true,
               centerHorizontal: true,
               alignment: FractionalOffset.center,
               fit: FlexFit.tight);

    new Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              new RaisedButton(
                        appearance: myAppearance,
                        child: new Text(
                          "Raised Button",
                          style: new TextStyle(color: Colors.white),
                        ),
                        color: Colors.indigo,
                      ),
              new FlatButton(
                        appearance: myAppearance,
                        child: new Text(
                          "Flat Button",
                          style: new TextStyle(color: Colors.white),
                        ),
                        color: Colors.indigo,
                      ),
              new IconButton(
                        appearance: myAppearance,
                        icon: const Icon(Icons.sentiment_very_satisfied),
                      )
		]
    );
```

**Comment by dahabit** [comment]
great Idea Thanks, I like that there one property that contains all "Appearance" that will solve the issue that we need to add too many properties to every widget

**Comment by PaulHMason** [comment]
I like this idea - a slight variation would be to have the container (column) have a "childAppearance" property that the immediate children use if they don't set their own appearance property. That way you cut down on a bit of repetitive code if all children use the same padding and margin.

I suppose you could also write a custom layout container - that would work without modifying any of the existing widgets.

**Comment by Rockvole** [comment]
These are some of the related questions I have seen recently :

https://github.com/flutter/flutter/issues/3753
https://github.com/flutter/flutter/issues/5166
https://stackoverflow.com/questions/44053363/flutter-padding-for-all-widgets
https://stackoverflow.com/questions/48068498/is-there-a-way-to-join-flutter-widgets-with-padding

**Comment by lukepighetti** [comment]
I really like what you guys are doing with Flutter but this is an argument that I cannot agree with.

Imagine if React-Native didn't have easy access styling properties, it would be much more clunky than it is now.

Now imagine if Flutter had similar easy access styling properties, perhaps it would be less clunky.

**Comment by Hixie** [comment]
Flutter is explicitly designed to allow for both kinds of approaches. You should totally feel empowered to create a package that provides an alternative set of widgets that work as is described above. The building blocks provided by the core framework make that possible. (It would not be possible to do the reverse, so it doesn't make sense for the core framework to have the large widgets, because then we couldn't cater for those who want the style we have now.)

**Comment by Rockvole** [comment]
I don't think the approach I outlined would stop from being able to do the reverse. If you don't pass in the Appearance widget everything could be the same as before. 

If I decided to make my own package it would be hard for me to get the level of finish and consistency which the language designers can. 

Also, personally I don't like to work everyday with a roll-your-own variation of a tool. One day you end up in an interview being asked how to do things and no-one knows what you are talking about :)

**Comment by LucasLiao** [comment]
Add this please

**Comment by amnykon** [comment]
Several things to think about with this... Appearance could be an inherited widget, which would drop the line between.

In my opinion the best approach would be to use modifiers like swiftUI uses. A modifier is a widget method that returns another widget where the returned widget.child is the modified widget. This allows adding padding without nesting. This feature also requires Swift extensions to add these modifies to the Widget class, which dart does not support...

To work around darts lack of support of extensions, add the following 2 classes and have Widget conform to Modifiable<Widget>.

```
abstract class Modifier<T> {
   T modify(T base);
}

mixin Modifiable<T extends Modifiable<T>> {
  T modifyBy(Modifier modifier) => modifier.modify(this);
}
```

This way several modifiers could be added to the Widget tree without increasing nesting.

If someone wants a custom appearance modifier, that applies a list of defined modifiers, that would be easy to do. That modifier could even get it's list of defined modifiers to use from an inherited widget...

**Comment by amnykon** [comment]
Dart now has extensions. Modifiers are now the way to go. I might even add them to the framework myself...

**Comment by Hixie** [comment]
I don't think this is something we should add to the core framework, but it would make a lot of sense in a package.

I'm going to close this for now since it's not something we plan to do in Flutter itself.
