### ISSUE TITLE
Flutter demo app that includes all official plugins for CI and testing

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#16736]
I am doing CI testing on different devices.

Could the team make a Flutter Plugin Gallery please that uses all the official plugins and publish it to the Play and Apple store please ?

It will make it much easier to test on various real devices and in saucelabs.

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/18237, which seems to be requesting the same thing but has more discussion.
