### ISSUE TITLE
on Using maybePop() . I m getting this in the terminal. Earlier maybePop was working fine v 0.2.3, however with v 0.2.8. it's not working anymore. Please help! 

### ISSUE THREAD

**Issue by Pushkar98** [flutter/flutter#16739]
```
#0      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:1643:37)
<asynchronous suspension>
#1      AddressState.build.<anonymous closure> (package:ecommerce_pro/screens/Address/index.dart:48:37)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
#7      PrimaryPointerGestureRecognizer.handleE<…>
```

flutter doctor -v

[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-IN)
    • Flutter version 0.2.8 at /Users/sahusoft/Sites/projects/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sahusoft/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Users/sahusoft/Downloads/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • iPhone 6s • 9ED9D1B7-5465-4421-8372-DE58DE6BB8DD • ios • iOS 11.2 (simulator)

• No issues found!

**Comment by zoechi** [comment]
Is this still an issue?
There seems to be something missing from the error output, like an error message or an exception name.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
