### ISSUE TITLE
Feature: allow app to set its own badge like "debug" or "slowMode"

### ISSUE THREAD

**Issue by sanox559** [flutter/flutter#16731]
It would be cool if we could have an option to create own badge over application like "debug" or "slowMode" programatically since most of the companies have apps with their alpha and beta build so it would be easier for QAs to determinate which build is it

**Comment by zoechi** [comment]
Shouldn't be too difficult to show your own widget there depending on some configuration.

**Comment by zoechi** [comment]
I'm going to close this because you can just do this with a custom widget.
If you do not think this is good enough please add a comment to get the issue reopened.
