### ISSUE TITLE
Implement bidi support for accessibility of horizontal scrolling text fields

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1673]
Right now `AccessibilityNodeInfo.ACTION_SCROLL_BACKWARD` and `AccessibilityNodeInfo.ACTION_SCROLL_FORWARD` always assume left and right respectively for horizontal scrolling fields. They should switch that around if the node being scrolled is RTL.

**Comment by goderbauer** [comment]
Single-line text fields are not exposed as scrollable. I am closing this bug as not longer applicable. Please open new issues if you run into other problems with RTL/LTR and a11y.
