### ISSUE TITLE
Why Navigation Transition is'nt smooth?

### ISSUE THREAD

**Issue by wisit-phusi** [flutter/flutter#16735]
I use Flutter v0.3.0. When I navigate with Navigator.pushNamed() to route to a screen its transition isn't smooth. Does anyone know what going on?

This is my result.
https://drive.google.com/file/d/1Z9ehnZllPgyCJBycBicljcXzKm5JzyA6/view?usp=sharing

But I wanna be like this.
https://drive.google.com/file/d/1AoYoQ_eHkOA3Qzu4bU4tn2i_v81EW7zq/view?usp=sharing

**Comment by zoechi** [comment]
Performance tests in debug mode are meaningless. 
Test in release mode.
Also please add the output of `flutter doctor -v`

**Comment by wisit-phusi** [comment]
I have tried to Test in release mode but it still isn't smooth.

This is my result.
https://drive.google.com/file/d/1IBPlVL0ocjP9WzQgBKmL3oTB2GnB5HN_/view?usp=sharing

**Comment by wisit-phusi** [comment]
This is an example. Stocks Project.
I have tried to decrease animation speed to see clearly.

The result.
https://drive.google.com/file/d/1TT--_o0xNKotnHgNgwwerhA995S45yms/view?usp=sharing

**Comment by wisit-phusi** [comment]
When I started to navigate to a screen it starts from middle to top and when I navigated to back it starts from top to middle. I think it should start from bottom to top and when We navigate back it should start from top to bottom.

**Comment by brianegan** [comment]
There's a performance issue with it at the moment that's being worked on: https://github.com/flutter/flutter/issues/12877

You can enable the smooth transition with this flag for the time being in your `main.dart` file:

`MaterialPageRoute.debugEnableFadingRoutes = true;`

**Comment by wisit-phusi** [comment]
Thank you. I have been able to solve it already.

**Comment by Dibro89** [comment]
@wisit-phusi Could you say how, please?

**Comment by channae** [comment]
Whoever looking for the solution modify main() as below,
```
void main() {
  MaterialPageRoute.debugEnableFadingRoutes =
      true; // ignore: deprecated_member_use
  runApp(MyApp());
}
```
**Note here we are calling** 
```MaterialPageRoute.debugEnableFadingRoutes = true;```

**Comment by sdresche17** [comment]
Has this been modified? I tried: 
void main() async {
  await SimplePermissions.requestPermission(permissionFromString('Permission.AccessFineLocation'));
  MaterialPageRoute.debugEnableFadingRoutes=true;
  runApp(MyApp());
}
And it's saying debugEnabled isn't a method of MaterialPageRoute

**Comment by zoechi** [comment]
@sdresche17 It was removed in https://github.com/flutter/flutter/commit/6c4b38b7070ec3536e3192de49a09addfd305dac#diff-4b673411bff408351f353abf1b412f0f 
It was deprecated since a while https://docs.flutter.io/flutter/material/MaterialPageRoute/debugEnableFadingRoutes.html

**Comment by sergiossm** [comment]
Any alternatives to the debugEnableFadingRoutes flag?

**Comment by brianegan** [comment]
@sergiossm That flag should no longer be necessary, the fading routes should "Just work" now :) If that's not the case, might be a good idea to file a new bug!

**Comment by akash09766** [comment]
I am still getting the above mentioned same issue.
  sdk: ">=2.0.0-dev.68.0 <3.0.0".

anyone got the fixed for this?

**Comment by VadimOsovsky** [comment]
this is one of the reasons flutter disappointed me, the other being linear and blunt transitions by default for most widgets, weird scrolling which seems to stop abruptly after slowing down - just to name a few. Generally since it doesn't use native components, like RN does, they don't feel natural to a user's specific device. Personally I think it's a pretty good choice for building game-like apps like Reflectly, not more. Hope they'll fix the aforementioned issues, because Flutter managed to provide the best dev experience so far.
