### ISSUE TITLE
Json loading has red page error

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#16738]
I have weather json data. When I tab the app it loads a red error page and few seconds later loads the data. Here is the stackoverflow error list. And I have a demo app that shows the error.

Any help please.
https://stackoverflow.com/questions/49894981/on-flutter-parsing-json-in-the-background-fails

Source:
https://github.com/NTMS2017/ntmsweather

**Comment by mit-mit** [comment]
Which Flutter version are you using? `flutter doctor` should tell you.

**Comment by mit-mit** [comment]
Looks like the main issue is that you are setting `weatherData` by calling a *asynchronous* method, yet use the value of it right away in the build method. I suggest you move the building of the main page contents into a separate method, e.g.:

```
 Widget buildWeather() {
    return new Stack(children: <Widget>[
      new ListView(
        padding: const EdgeInsets.all(5.0),
        children: [
```
and then render conditionally if the `weatherData` is null:

```
@override
  Widget build(BuildContext context) {
    return new Scaffold(
    ...
      body: weatherData == null ? new Text('Loading') : buildWeather(),
    );
```

**Comment by mit-mit** [comment]
Oh, I would also recommend cleaning up some of the redundancy, for example introduce some constants:

```
Widget buildWeather() {
    const smallText = const TextStyle(
      fontSize: 12.0,
      fontWeight: FontWeight.w400,
      color: Colors.white,
    );

    const largeText = const TextStyle(
      fontSize: 15.0,
      fontWeight: FontWeight.w400,
      color: Colors.white,
    );

    return new Stack(children: <Widget>[
      new ListView(
        padding: const EdgeInsets.all(5.0),
        children: [
...
                    // ITEM-0
                    new Column(
                      children: <Widget>[
                        new Text(
                          weatherData['list'][0]['main']['temp_max'].toString(),
                          style: smallText,
                        ),
                        new Text(
                          weatherData['list'][0]['main']['temp_min'].toString(),
                          style: largeText,
                        ),
 
```

And rather than copy the code for items 0 through 3, move that into a method that takes in the weatherData, and then call that four times.

**Comment by mit-mit** [comment]
Closing; there seems to be no issue here in the Flutter framework.

**Comment by NTMS2017** [comment]
I am using "Flutter (Channel master, v0.3.1-pre.35, on Mac OS X 10.13.4 17E199, locale tr-TR)" version.
Also in body in my original app I am using 2 different json. So how come I can use:

**body:** weatherData == null ? new Text('Loading') : buildWeather(),

the body also has more than 1 container. Thank you for Text style const. I will implement that.

**Comment by NTMS2017** [comment]
@mit-mit creating separate Widget buildWeather() works well. By the way do you know how to show the Flutter loading animation instead of using "loading" text

**Comment by atilkan** [comment]
@NTMS2017 https://flutterbyexample.com/set-up-app-loading/
