### ISSUE TITLE
The Flutter Gallery should be localized

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#16747]
Currently the app is configured for the default US-English locale only. There are many reasons why the Flutter Gallery app should be localized:

- The audience for the app is worldwide. 
- The app is intended to demonstrate best practices. This is a good opportunity to demonstrate localization.
- Localizing the app will help shake out limitations of Flutter's i18n APIs

**Comment by pedromassangocode** [comment]
Closing this as fixed since the Gallery app is now localized to more languages. In the image below I was able to use Portuguese language in the Gallery app.

![Screen Shot 2020-09-07 at 15 09 53](https://user-images.githubusercontent.com/67424416/92396017-33e14100-f11c-11ea-9d51-4315f46e8d50.png)
