### ISSUE TITLE
UI Testing: Taphandler does not get called when wrapped in another function

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#16745]
## Steps to Reproduce

This is pretty strange. When simulating a Tap using flutter UI Testing I realized that the handler does not get called when wrapped inside a anonymous function:

the affected project can be found here 
https://github.com/escamoteur/rx_widgets/tree/UI_Test_Timeout

Go to `rx_widgets\example\test\homepage_test.dart` and run the test.

This is the critical part in `rx_widgets\example\test\homepage..dart`  line 64

![image](https://user-images.githubusercontent.com/16635729/38992502-39843cba-43e1-11e8-8dcd-e01dc1b7c351.png)

if I first assign the function to a variable and call it then it works

https://github.com/escamoteur/rx_widgets/tree/UI_Test_Complete 

![image](https://user-images.githubusercontent.com/16635729/38992471-21710ec8-43e1-11e8-917a-888e0a3acb48.png)

`updateWeatherCommand` is a callable class. 

When the `updateWeatherCommand` is called (which is a `MockCommand` for the tests) it will print `Called Execute` which never does happen when assigning it to a variable first or assign it directly to the handler without wrapping it in another function.

When running the App both versions work. only in test there is a difference. 

## Logs
This is the output of where all Tests pass

https://github.com/escamoteur/rx_widgets/tree/UI_Test_Complete

[test-ok.log](https://github.com/flutter/flutter/files/1928411/test-ok.log)

This the version with the Wrapped function that times out

https://github.com/escamoteur/rx_widgets/tree/UI_Test_Timeout

[test-timeout.log](https://github.com/flutter/flutter/files/1928420/test-timeout.log)

The timeout happens because there is another test waiting for a Stream emiting the result

The test that causes this is `rx_widgets\example\test\homepage_test.dart`

## Flutter Doctor

```
PS C:\Entwicklung\FlutterApps\packages\rx_widgets\example> flutter doctor -v
[√] Flutter (Channel dev, v0.3.0, on Microsoft Windows [Version 10.0.16299.371], locale de-DE)
    • Flutter version 0.3.0 at C:\Entwicklung\Flutter
    • Framework revision c73b8a7cf6 (7 days ago), 2018-04-12 16:17:26 -0700
    • Engine revision 8a6e64a8ef
    • Dart version 2.0.0-dev.47.0.flutter-4126459025

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 32-bit edition (version 1.22.2)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.12.0-dev.windows-paths-experimental

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!
```

**Comment by jason-simmons** [comment]
This is probably due to how the test configures the Mockito objects.

Stubs for method calls have different syntax from stubs for field getters:

`when(model.updateWeatherCommand()).thenReturn(command);`
versus
`when(model.updateWeatherCommand).thenReturn(command);`

**Comment by escamoteur** [comment]
Oh, that makes sense so by assigning it I got the correct response so that I could call afterwards.
Thanks a lot, will try tomorrow.

**Comment by escamoteur** [comment]
yep, that solved it. Thanks again to @jason-simmons
