### ISSUE TITLE
Status bar text color changes randomly between black and white. 

### ISSUE THREAD

**Issue by Pushkar98** [flutter/flutter#16740]
As we have a white background appbar, the status bar doesn't appear.  
It randomly changes between black and white. 

fllutter doctor -v 
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-IN)
    • Flutter version 0.2.8 at /Users/sahusoft/Sites/projects/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sahusoft/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Users/sahusoft/Downloads/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • iPhone 6s • 9ED9D1B7-5465-4421-8372-DE58DE6BB8DD • ios • iOS 11.2 (simulator)

• No issues found!

**Comment by zoechi** [comment]
Sorry for the late response. Is this still an issue?

**Comment by Pushkar98** [comment]
Yes it is. For the apps with dark app bar it's fine. However with light app bar the status bar text colour changes from black to white as we move from splash screen to homepage and then keeps on changing randomly. Watch the gif completely.
![flutter issues](https://user-images.githubusercontent.com/34940419/42810096-c00c6d3c-89d4-11e8-994c-07699981c6ab.gif)

**Comment by Pushkar98** [comment]
On the splash screen the colour is black but as we move to the home page it turns white. Since the App bar colour is itself white the text does not appear. We have tested it with dark app bar and found that the status bar colour changes to white

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/7347#issuecomment-325456201 should work at least as workaround.
Might be even a dup of #7347

**Comment by zoechi** [comment]
@Pushkar98 why the laugh reaction?

**Comment by HansMuller** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
@Pushkar98 The AppBar (and nav bar in cupertino) provides some hints to the framework on what the brightness of the status bar should be based on the theme color.  Could you try passing `Brightness.dark` and `Brightness.light` to the `brightness` field of your AppBar to see how that effects the status bar?

**Comment by ebeem** [comment]
I faced this issue today, the problem only occurs in `IOS`
for some reason, the status bar color is not inherited from the `theme data` (brightness field)
the issue seems to occur when you don't have an `AppBar` which seems to be what @Pushkar98 is doing


in my case, I needed a light statusbar, the only thing that worked for me was calling `SystemOverlayStyle`

`SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);`

**Comment by thenexus00** [comment]
I have SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light) everywhere and Brightness light but I still see flutter flick back to black on the status colour. It seems to do this when you have states and updating or fetching from API services and rendering content from there. When you update the state of the widget it looses the knowledge for some reason.

**Comment by thenexus00** [comment]
I think we have also identified it may be a bug in MaterialPageRoute with its builder.
When you navigate to a new widget it will go black unless you specify the SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light); in that widget too. That also does not always work and we had to use a package (ScreenTheme) which allows you to change it on the fly as a backup to fix it.

Basically without that despite the whole app being set to light it will flicker from white to black and the package helps revert that.

From the page route the default back button when fired can then reset these back to black as well.

It is very random behavior both on IOS and android and we can not really fix it. It just looks to be a bug in flutters implementation currently.
As I mentioned, it also occurs when you have stateful widgets and pulling in content through API etc.

**Comment by Pushkar98** [comment]
The problem was resolved from what zoechi and jonahwilliams pointed out. Thank you! I am closing this issue

**Comment by zsirfs** [comment]
I faced this iusse today. look: 
![image](https://user-images.githubusercontent.com/22249411/46060833-1c128b80-c197-11e8-8072-ad52c69651c5.png)

**Comment by zsirfs** [comment]
how to resolved?
`SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);` is not anything.

**Comment by thenexus00** [comment]
> how to resolved?
> `SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);` is not anything.

We have actually seen it on various IOS apps and not all on flutter.
Our solution was a combination of the output settings and a plugin. I will share what we did when I am back working on the app projects phase 2.

**Comment by Pushkar98** [comment]
The problem is seen on ios device. You can use ```    brightness: Brightness.light``` in the app bar. It resolves the issue if you have a light colour appbar.

**Comment by thomashbailey** [comment]
We have this issue too.  What was the solution?
using Flutter 1.7.8+hotfix.3

**Comment by dbbd59** [comment]
same here in 1.7.8+hotfix.4.
the status bar does not return dark, after becoming light, in a page without app bar.

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-IT)
    • Flutter version 1.7.8+hotfix.4 at /Users/davide/Documents/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/davide/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone 8 • 22B480FF-CE09-405A-BD00-93D496A8EBF7 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

**Comment by samuelg123** [comment]
I'm also encountered this problem

**Comment by RobertasB** [comment]
I think it's important not to forget specifying `brightness` and `color` attributes to avoid "randomness", e.g. in `ThemeData/AppBarTheme`.

**Comment by Zeeshan0201** [comment]
@RobertasB yes 
=> For text color of white add

>  brightness: Brightness.dark 

in Appbar
=> And for text color of black add 

> brightness: Brightness.light

 in Appbar
