### ISSUE TITLE
Disable scroll actions that aren't relevant

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1675]
Right now when you're at the top of a list, we still add the "scroll backward" action. We should probably split all the scroll booleans into "canScrollLeft", "canScrollRight", etc, rather than just horizontal vs vertical.

**Comment by goderbauer** [comment]
This is actually necessary to get accessibility scrolling working properly on Android: https://github.com/flutter/flutter/issues/1714#issuecomment-314201658
