### ISSUE TITLE
Fuzzy rendering in screenshotting -- off-by-half pixel?

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16754]
After https://github.com/flutter/engine/pull/4998, we started seeing some fuzzy rendering:

![fuzze-text](https://user-images.githubusercontent.com/15253456/39008237-f0eda258-43bc-11e8-8d08-9767a4982290.gif)

Note that this is seen on tests that use [`FlutterDriver.screenshot`](https://docs.flutter.io/flutter/flutter_driver/FlutterDriver/screenshot.html), so it's _possible_ that this rendering difference is only visible when run through the screenshotter.

**Comment by tvolkert** [comment]
Here's the same screenshot, blown up 300%:

![fuzze-text](https://user-images.githubusercontent.com/15253456/39008530-c4e97730-43bd-11e8-8446-2cb6a0d7ef2d.gif)

**Comment by goderbauer** [comment]
`FlutterDriver.screenshot` takes a screenshot directly from the engine, it bottoms out at https://github.com/flutter/engine/blob/a0804f37388cafa68a19611e34bd5ca8753f15b5/shell/common/rasterizer.cc#L151.

**Comment by ds84182** [comment]
I've seen something similar happen when running the engine in an embedder. Looks like it has something to do with the rasterizer cache.

Normal:
![image](https://user-images.githubusercontent.com/2268005/39013851-a7e4befa-43e6-11e8-996a-b95a24206304.png)

In rasterizer cache:
![image](https://user-images.githubusercontent.com/2268005/39013859-b07f49a4-43e6-11e8-91b8-0bc0a1d8a20f.png)

In rasterizer cache (without checkerboard):
![image](https://user-images.githubusercontent.com/2268005/39013935-e82fbde8-43e6-11e8-9b89-975c2707dbf9.png)

**Comment by jason-simmons** [comment]
In the recent engine refactoring (https://github.com/flutter/engine/commit/58e84c8bf0b6304649340e6eaad988602961d7f6) the screenshot API was changed to ignore the raster cache when rasterizing the layer tree.

This yields screenshot bitmaps that differ from results from before the refactoring.

**Comment by mravn-google** [comment]
@jason-simmons Are we not going to fix the raster cache?

**Comment by tvolkert** [comment]
It sounds like in the cases where this happens, the device has a half-pixel.  The raster cache needs a full pixel boundary, so when it sees a half-pixel, it rounds up to a whole value.  In doing so, it yields more pleasing rendering results. And more to the point, the real rendering path uses the raster cache, so in order to get the same results in the screenshotting code as we do in the real render path, we should be using the raster cache.
