### ISSUE TITLE
Text inside stack's positioned wrapped in Backdrop Filter "bleeds out" if not wrapped in material widget

### ISSUE THREAD

**Issue by moseskarunia** [flutter/flutter#16760]
## Disclaimer
I'm not an english native. My english possibly messy.

## Story
So I want to make a column of text (as a "header"), on top of a background image, while also blurring the background.
That's why, I use a stack, and then position my "header" on top, left, right at 0. Then a weird thing happen, I expect the "header" to have a same height as the content (which is a column), but, it turns out the entire screen got blurred, while still leaving the column neat.

Incorrect screenshot:
https://imgur.com/a/CmsJwKE

That being said, luckily I found out that I need to wrap **each text** widgets (i have 2 texts, and i need to wrap both of them, more on code snippet) inside a material widget (with transparent color). After that, the blurred area is now correct.

Correct screenshot:
https://imgur.com/a/hqPgnTq

## Code snippet
```
@override
  Widget build(BuildContext context) {
    return new Scaffold(
        body: new SizedBox.expand(
            child: new Stack(children: <Widget>[
      ...
      ...
      new Positioned(
          top: 0.0,
          left: 0.0,
          right: 0.0,
          child: new BackdropFilter(
              filter: new ui.ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
              child: new Container(
                  color: Colors.transparent,
                  child: new Column(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: <Widget>[
                        new Container(height: 72.0),
                        new Material(
                          color: Colors.transparent,
                          child: new Container(
                              padding: new EdgeInsets.all(16.0),
                              decoration: new BoxDecoration(
                                  border: new Border.all(
                                      color: Colors.white.withOpacity(0.8),
                                      width: 3.0)),
                              child: new Text("BANDUNG",
                                  textScaleFactor: 0.8,
                                  style: new TextStyle(
                                      letterSpacing: 4.0,
                                      fontWeight: FontWeight.w700,
                                      color: Colors.white.withOpacity(0.8),
                                      fontSize: Theme
                                          .of(context)
                                          .textTheme
                                          .display1
                                          .fontSize))),
                        ),
                        new Padding(padding: new EdgeInsets.only(top: 32.0)),
                        new Material(
                          color: Colors.transparent,
                          child: new Padding(
                            padding:
                                const EdgeInsets.symmetric(horizontal: 16.0),
                            child: new Text(
                                "Kota yang merupakan ibukota Jawa Barat ini terkenal dengan wisata kuliner, belanja, dan alamnya.",
                                style: new TextStyle(
                                    color: Colors.white.withOpacity(0.8),
                                    fontSize: Theme
                                        .of(context)
                                        .textTheme
                                        .body1
                                        .fontSize),
                                textAlign: TextAlign.center,
                                textScaleFactor: 1.1),
                          ),
                        ),
                        new Padding(padding: new EdgeInsets.only(top: 16.0)),
                        new Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              new Flexible(
                                  child: new Container(
                                      decoration: new BoxDecoration(
                                          color: Colors.white.withOpacity(0.8),
                                          borderRadius:
                                              new BorderRadius.circular(2.0)),
                                      padding: new EdgeInsets.symmetric(
                                          horizontal: 16.0),
                                      width: 75.0,
                                      height: 1.0))
                            ]),
                        new TabBar(
                            indicatorColor: Colors.white,
                            indicatorWeight: 3.0,
                            isScrollable: true,
                            controller: _tabController,
                            tabs: <Tab>[
                              new Tab(text: "Kuliner"),
                              new Tab(text: "Belanja"),
                              new Tab(text: "Wisata"),
                              new Tab(text: "Blog")
                            ])
                      ])))),
    ...
    ])));
  }
```

## How to reproduce the error

Just delete at least 1 material widget in above snippet.

## Flutter Run

No irregularity

## Flutter Analyze

No irregularity

## Flutter Doctor

[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
    • Flutter version 0.2.8 at M:\Work\flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at M:\Work\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = M:\Work\Android\sdk
    • Java binary at: M:\Work\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at M:\Work\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at M:\Work\JetBrains\IntelliJ IDEA Community Edition 2017.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • SM N750 • xxx.xxx.xxx.x:xxxx • android-arm • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by xster** [comment]
Related #10302

Skia issue at https://bugs.chromium.org/p/skia/issues/detail?id=6753

**Comment by zoechi** [comment]
Seems to be fixed. Can this be closed?
