### ISSUE TITLE
ProcessException: Permission Denied

### ISSUE THREAD

**Issue by seant4** [flutter/flutter#16768]
I was trying to run an app I made onto my phone, but when I run it, I get this error
I am running linux
ProcessException: ProcessException: Permission denied
  Command: /home/sean/Android/Sdk/build-tools/27.0.3/aapt dump badging build/app/outputs/apk/app.apk
## Flutter Doctor
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /home/sean/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/sean/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
    • All Android licenses accepted.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.20.0)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • SM G930V • 7bb6a80b • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

Also, if i run it as sudo
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
• Flutter version 0.2.8 at /home/sean/flutter
• Framework revision b397406 (2 weeks ago), 2018-04-02 13:53:20 -0700
• Engine revision c903c21
• Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✗] Android toolchain - develop for Android devices
✗ Unable to locate Android SDK.
Install Android Studio from: https://developer.android.com/studio/index.html
On first launch it will assist you in installing the Android SDK components.
(or visit https://flutter.io/setup/#android-setup for detailed instructions).
If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] VS Code (version 1.20.0)
• VS Code at /usr/share/code
• Dart Code extension not installed; install from
https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

\Error retrieving device properties for ro.product.cpu.abi:
ADB server didn't ACK

    failed to start daemon *
    error:

[✓] Connected devices (1 available)
• SM G930V • 7bb6a80b • android-arm • Android null (API null)

! Doctor found issues in 3 categorie

**Comment by seant4** [comment]
Also, if i run it as sudo
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /home/sean/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] VS Code (version 1.20.0)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

\Error retrieving device properties for ro.product.cpu.abi:
ADB server didn't ACK
* failed to start daemon *
error: 

[✓] Connected devices (1 available)
    • SM G930V • 7bb6a80b • android-arm • Android null (API null)

! Doctor found issues in 3 categorie

**Comment by zoechi** [comment]
Have you tried to fix the issues `flutter doctor` reports?

**Comment by seant4** [comment]
@zoechi I know Android studio is not an issue, but I have the sdk downloaded. I don't know what else to do,

**Comment by zoechi** [comment]
> [✗] Android toolchain - develop for Android devices
> ✗ Unable to locate Android SDK.

>  I know Android studio is not an issue, 

Looks different to me, but if you know :D

**Comment by seant4** [comment]
@zoechi Android studio is not required, it is used to install the SDK. But if you have the sdk installed then there is no issue. This was brought up in another issues page discussing how android studio was not required. Do you know why I am getting this error in flutter?

**Comment by zoechi** [comment]
@seant4 You are right. 

I saw 

> Also, if i run it as sudo
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
• Flutter version 0.2.8 at /home/sean/flutter
• Framework revision b397406 (2 weeks ago), 2018-04-02 13:53:20 -0700
• Engine revision c903c21
• Dart version 2.0.0-dev.43.0.flutter-52afcba357

and assumed installing AS would be the easiest way to get that fixed, but now I saw this is only when you run with `sudo` and otherwise it's ok anyway.

Sorry for the noise.

**Comment by zoechi** [comment]
@seant4 no, running with sudo is diiscouraged. I just didn't pay attention

**Comment by zoechi** [comment]
Sorry for not coming back earlier. Is this still an issue?

**Comment by Mritunjay10** [comment]
Worths a try https://github.com/flutter/flutter/issues/20364#issuecomment-480373990
