### ISSUE TITLE
TextFormField textAlign center is not working for the hint text

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#16769]
`child: new TextFormField(
        textAlign: TextAlign.center,
        decoration: new InputDecoration(
          hintText: "Full name",
        ),
      ),`
dose not center hintText as it should.

[√] Flutter (Channel dev, v0.3.0, on Microsoft Windows [Version 10.0.17133.73], locale en-US)
    • Flutter version 0.3.0 at M:\flutter
    • Framework revision c73b8a7cf6 (7 days ago), 2018-04-12 16:17:26 -0700
    • Engine revision 8a6e64a8ef
    • Dart version 2.0.0-dev.47.0.flutter-4126459025

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.22.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.2

[√] Connected devices (1 available)
    • TECNO C9 • H535C90123456789 • android-arm64 • Android 6.0 (API 23)

• No issues found!

**Comment by zoechi** [comment]
dup of #16366 ?
