### ISSUE TITLE
firebase_auth updatePassword method missing

### ISSUE THREAD

**Issue by vagrantrobbie** [flutter/flutter#16775]
The method updatePassword(to:..) is missing from the FirebaseAuth.currentUser(). 

This means we can not update a authenticated user's password in app. We have have to send a password reset email instead which means the user has to leave the app.
This exists on the[ iOS, Android and Web SDK documentation](https://firebase.google.com/docs/auth/web/manage-users#set_a_users_password)

I am using firebase_auth: "^0.5.5". This affects both iOS and Android

**Comment by zoechi** [comment]
Duplicate of #167775

**Comment by kroikie** [comment]
@vagrantrobbie

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/848. Any further collaboration will be done there.
