### ISSUE TITLE
ErrorWidget should be less scary in release builds

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16774]

**Comment by mauriciogior** [comment]
I suggest adding an option to change the background color and also the text color, so if people want to hide the broken widget, they can simply set a bg & text color to match the container bg.

**Comment by Levi-Lesches** [comment]
How about just not showing this screen at all? It doesn't make any sense to users anyway. #40452

**Comment by Levi-Lesches** [comment]
This is now possible: From #40452:

> Also, in #13578, it is now possible to override the error widget by setting [`ErrorWidget.builder`](https://api.flutter.dev/flutter/widgets/ErrorWidget/builder.html). It defaults to [`RenderErrorBox`](https://api.flutter.dev/flutter/rendering/RenderErrorBox-class.html), which has a number of static properties you can change to alter its appearance. Or you can just replace it with another widget entirely (but read the docs for warnings).

I guess the only point in keeping this issue open would be to change the **default** appearance of the error widget.

**Comment by Hixie** [comment]
Duping to https://github.com/flutter/flutter/issues/40452
