### ISSUE TITLE
firebase_auth sendEmailVerification method missing

### ISSUE THREAD

**Issue by vagrantrobbie** [flutter/flutter#16776]
The method sendEmailVerification(to:..) is missing from the FirebaseAuth.currentUser().

We can check if the user is email verified but can not send the verification email link directly from the app.
This exists on the [iOS, Android and Web SDK documentation](https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email)

I am using firebase_auth: "^0.5.5". This affects both iOS and Android

**Comment by zoechi** [comment]
Looks like a dup of #12459

**Comment by hsun-cnnxty** [comment]
The sendEmailVerification() is not implemented in #12459.  It only implements sendPasswordResetEmail()

**Comment by zoechi** [comment]
@hsun-cnnxty #12459 still covers `sendEmailVerification` and it's not closed.

**Comment by aqwert** [comment]
Should be closed now due to it merged 0.5.7 : https://github.com/flutter/plugins/pull/529

**Comment by zoechi** [comment]
Thanks @aqwert
