### ISSUE TITLE
engine roll regressed the dart1 hot reload benchmarks

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#16777]
This engine roll:

https://github.com/flutter/flutter/commit/e9177ba3d18fe6c66e0ceeafeffb5bf6a841f96c

regressed the dart1 hot reload benchmarks substantially (perhaps 6x). I don't know if these benchmarks are at the top of our list, but it's worth noting the regression. /cc @chinmaygarde 

Locally, when I reload an app w/ changes (when using --no-preview-dart-2) I see hundreds of reloaded (changed) libraries on every reload, when there had been no changes to the libraries.

```
Reloaded 490 of 506 libraries in 1,629ms.
```

**Comment by devoncarew** [comment]
@aam, I believe you fixed this recently?

**Comment by chinmaygarde** [comment]
This was fixed by @aam in https://github.com/flutter/engine/pull/5096.
