### ISSUE TITLE
FlutterLogoDecoration with Roboto doesn't render right on iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#16773]
Noticed while fixing b/77980873.

There's probably some math issue.

![flutter_01](https://user-images.githubusercontent.com/156888/39024679-580dcc94-43f7-11e8-8b3b-609eb74c5d5b.png)

https://github.com/xster/flutter-test/tree/master/t89_flutter_logo_canvas

**Comment by xster** [comment]
Seems libtxt related. 
A screen diff between blink and libtxt:
![f81f948e197cb2e9143800ee9442ea07 prnfizga2obka89qx3bfltg5z0p4pp07](https://user-images.githubusercontent.com/156888/39025366-69f3cea0-43fb-11e8-80f8-22d3a8af6244.png)

Given the same TextPainter, the text was laid out to different sizes.

**Comment by GaryQian** [comment]
Just tried this on modern flutter, seems to be fixed!
