### ISSUE TITLE
[Localizations]iOS can't get correct system language.

### ISSUE THREAD

**Issue by xuexin** [flutter/flutter#16789]
[Minimal internationalization](https://github.com/flutter/website/tree/master/_includes/code/internationalization/minimal/)
iOS always get 'en_'
Android is ok.
Test device:iPhone X(Simulator), iPhone 6
Language and region are not en

Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git Framework • revision b397406561 (3 weeks ago) • 2018-04-02 13:53:20 -0700 Engine • revision c903c217a1 Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

**Comment by xuexin** [comment]
Add:
This bug will happen when system languages more than one.

**Comment by zoechi** [comment]
Is it a dup of #14128 ?

**Comment by zoechi** [comment]
Closing as dup of #14128
