### ISSUE TITLE
AS doesn't sync pubspec.yaml to disk when clicking "packages get"

### ISSUE THREAD

**Issue by fmatosqg** [flutter/flutter#16786]
## Steps to Reproduce

- Edit pubspec.yaml
- Immediately click `get packages`  
- Notice that it won't read the latest changes

If you `cmd+s` before clicking the expected result happens.

AS 3.1.1 with flutter plugin 23.2.2 and flutter beta 2.

**Comment by zoechi** [comment]
You don't have disabled auto-save? https://stackoverflow.com/questions/28946013/how-to-disable-auto-save-save-in-android-studio

**Comment by fmatosqg** [comment]
Definitely no, I haven't used cmd+s in Intellij for years :)
If I wait a few seconds or switch screens I get expected behavior.

**Comment by zoechi** [comment]
Sounds similar to flutter/flutter-intellij#2472

@devoncarew should this be moved over to flutter/flutter-intellij ?
