### ISSUE TITLE
Add a test for the compute method in Foundation.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#16781]
The [`compute`](https://docs.flutter.io/flutter/foundation/compute.html) method in the in Foundation spawns isolates and attempts to run tasks on the same. This exercises the Engine and the VM in unique ways. There are no tests for this method in the framework. Isolate spawning tests in the engine also do not test child and grandchild isolate runs. Tests should be added for the following cases:

* Single child isolate spawn and shutdown.
* Child isolate spawns its own children.
* Child isolates are spawned and the engine (the Flutter view) is torn down.

**Comment by chinmaygarde** [comment]
cc @rmacnak-google who may be able to think of more uses cases of secondary isolates we might not be testing.

I can wire up the tests for the same in the engine. Can anyone do the same in the framework? cc @tvolkert, @Hixie

**Comment by Hixie** [comment]
Wow, I suck, I didn't add a test. My bad.

**Comment by Hixie** [comment]
I'll add a test to the framework once I get my desktop back up.

**Comment by rmacnak-google** [comment]
Since we implemented spawning in https://github.com/flutter/engine/commit/09d05a38912a3c1a906e95099cac9a7e14fae85f without looking at the URI, it's probably also worth testing that `Isolate.spawnUri` fails in a reasonable way and doesn't just silently behave like `Isolate.spawn`.

**Comment by chinmaygarde** [comment]
Can we assert that in the engine somehow? Actually support spawnURI in the JIT environment and fail with an error generated in the engine in AOT contexts.

**Comment by Hixie** [comment]
If we don't intend to support spawnUri in an AOT context, we probably should also not support it in a JIT context unless we can provide the JIT context to release builds.

cc @sbaranov @zanderso

**Comment by Hixie** [comment]
Actually, I can't add a test for "Child isolate spawns its own children" because `compute` is sync, not async.
