### ISSUE TITLE
TextFormField textAlign center does not center hintText

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#16784]
I been trying everything to center the hintText of a TextFormField but not working, what am I doing wrong?
here's the code

```
  child: new TextFormField(
        textAlign: TextAlign.center,
        decoration: new InputDecoration(
          hintText: "Full name",
        ),
      ),

```
Is this supposed to center the hintText? if yes why is it not centering?
whats the supposed behaviour?

**Comment by zoechi** [comment]
Isn't this the same as #16769 ?
