### ISSUE TITLE
Allow authors to override focus order for keyboard navigation

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1678]
Depends on #1608.

**Comment by gspencergoog** [comment]
This can now be closed: [`FocusTraversalPolicy`](https://master-api.flutter.dev/flutter/widgets/FocusTraversalPolicy-class.html) subclasses implement custom policy, and [`DefaultFocusTraversal`](https://master-api.flutter.dev/flutter/widgets/DefaultFocusTraversal-class.html) widgets place that policy in the tree.
