### ISSUE TITLE
Flutter generated arm32 App.framework  crashes on a iPhone4S

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#16797]
## Steps to Reproduce

We built a arm32 Flutter.framework and App.framework with the instructions at "https://github.com/flutter/engine/wiki/iOS-Builds-Supporting-ARMv7".

The app works fine for iPhone5C.
However, it crashes in a iPhone4S(iOS9.1).

We have a stack in iPhone4S.
![image](https://user-images.githubusercontent.com/817851/39055373-a680d156-44e6-11e8-9964-2d7b7edabd59.png)

## Flutter Doctor
flutter doctor -v
Building flutter tool...
[✓] Flutter (Channel beta, v0.1.6-pre.45, on Mac OS X 10.13.4 17E199, locale en-CN)
    • Flutter version 0.1.6-pre.45 at /Users/kylewong/Codes/fwn_idlefish/flutter
    • Framework revision f55599e0b8 (5 hours ago), 2018-04-20 16:37:35 +0800
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK at /Users/kylewong/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

**Comment by kangwang1988** [comment]
@eseidelGoogle

**Comment by eseidelGoogle** [comment]
Looks like it's crashing in Dart code?
https://api.dartlang.org/stable/1.24.3/dart-core/Stopwatch/elapsedMicroseconds.html
FYI @a-siva

**Comment by mraleph** [comment]
My guess would be that iPhone 4S does not support SDIV instruction. 

@kangwang1988 could you try building with this patch applied on top your flutter tools?

```diff
diff --git a/packages/flutter_tools/lib/src/commands/build_aot.dart b/packages/flutter_tools/lib/src/commands/build_aot.dart
index 7f82d3a65..576cab200 100644
--- a/packages/flutter_tools/lib/src/commands/build_aot.dart
+++ b/packages/flutter_tools/lib/src/commands/build_aot.dart
@@ -341,6 +341,7 @@ Future<String> _buildAotSnapshot(
       } else {
         genSnapshotCmd.add('--snapshot_kind=app-aot-assembly');
         genSnapshotCmd.add('--assembly=$assembly');
+        genSnapshotCmd.add('--no-use-integer-division');
         outputPaths.add(assemblyO);
       }
       break;
```

(make sure to delete `bin/cache/flutter_tools.snapshot` after applying the patch and delete `build` folder before rebuilding).

**Comment by kangwang1988** [comment]
@mraleph 
It does no use. I follow your instructions, however, the problem still exists.

**Comment by kangwang1988** [comment]
@mraleph 
(lldb) frame select 0
frame #0: 0x05230fe4 App`Precompiled__IntegerImplementation_0150898____426 + 68
App`Precompiled__IntegerImplementation_0150898____426:
->  0x5230fe4 <+68>: .long  0xe7100011                ; unknown opcode
    0x5230fe8 <+72>: cmp    r0, #1073741824
    0x5230fec <+76>: lslne  r0, r0, #1
    0x5230ff0 <+80>: bxne   lr
(lldb) register read
General Purpose Registers:
        r0 = 0x3b9aca00
        r1 = 0x00000000
        r2 = 0x00000066
        r3 = 0x00000000
        r4 = 0x0d281961
        r5 = 0x109a6c11
        r6 = 0x108b3221
        r7 = 0x4038a8d0
        r8 = 0x1103dd1c
        r9 = 0x1103dcf9
       r10 = 0x15dc9c00
       r11 = 0x109a3819
       r12 = 0x77359400
        sp = 0x4038a8b8
        lr = 0x05257984  App`Precompiled_Stopwatch_get_elapsed_725 + 308
        pc = 0x05230fe4  App`Precompiled__IntegerImplementation_0150898____426 + 68
      cpsr = 0x20000010

(lldb) di -s `$pc-8` -c 10
App`Precompiled__IntegerImplementation_0150898____426:
    0x5230fdc <+60>: asr    r0, r0, #1
    0x5230fe0 <+64>: asr    r1, r1, #1
->  0x5230fe4 <+68>: .long  0xe7100011                ; unknown opcode
    0x5230fe8 <+72>: cmp    r0, #1073741824
    0x5230fec <+76>: lslne  r0, r0, #1
    0x5230ff0 <+80>: bxne   lr
    0x5230ff4 <+84>: push   {r5, r6, r7, lr}
    0x5230ff8 <+88>: add    r7, sp, #8
    0x5230ffc <+92>: ldr    r5, [r6, #0xb]
    0x5231000 <+96>: ldr    r12, [r10, #0x4]
(lldb)

**Comment by mraleph** [comment]
```
-> 0x5230fe4 <+68>: .long 0xe7100011 ; unknown opcode
```

This is `SDIV` instruction - which confirms my original hypothesis that iPhone 4S simply does not support it. I will look tomorrow into why `--no-use-integer-division` did not disable the generation of this instruction.

**Comment by kangwang1988** [comment]
@mraleph 
Thanks.

**Comment by mraleph** [comment]
@kangwang1988 I have verified that my original patch should have indeed fixed the issue. Here is the code that we generate without my patch:

```
Code for optimized function 'dart:core__IntegerImplementation@0150898_~/' {
0x12bed10    e59ac070               ldr ip, [thr, #+112]
0x12bed14    e12fff1c               bx ip
        ;; MonomorphicCheckedEntry
0x12bed18    e3100001               tst r0, #1
0x12bed1c    11d0c0b1               ldrneh ip, [r0, #+1]
0x12bed20    03a0c033               moveq ip, #51
0x12bed24    e1a090c9               mov r9, r9, asr #1
0x12bed28    e15c0009               cmp ip, r9
0x12bed2c    1afffff7               bne -28 ; 0x12bed10
        ;; Intrinsic
0x12bed30    e59d0000               ldr r0, [sp, #+0]
0x12bed34    e59d1004               ldr r1, [sp, #+4]
0x12bed38    e180c001               orr ip, r0, r1
0x12bed3c    e31c0001               tst ip, #1
0x12bed40    1a000007               bne +36 ; 0x12bed64
0x12bed44    e3500000               cmp r0, #0
0x12bed48    0a000005               beq +28 ; 0x12bed64
0x12bed4c    e1a000c0               mov r0, r0, asr #1
0x12bed50    e1a010c1               mov r1, r1, asr #1
0x12bed54    e7100011               sdiv r0, r0, r1
0x12bed58    e3500101               cmp r0, #1073741824
0x12bed5c    11a00080               movne r0, r0, lsl #1
0x12bed60    112fff1e               bxne lr
```

Notice SDIV instruction which would cause the crash if CPU does not support it.

Here is the code that we generate with my patch:

```
Code for optimized function 'dart:core__IntegerImplementation@0150898_~/' {
0x123ed10    e59ac070               ldr ip, [thr, #+112]
0x123ed14    e12fff1c               bx ip
        ;; MonomorphicCheckedEntry
0x123ed18    e3100001               tst r0, #1
0x123ed1c    11d0c0b1               ldrneh ip, [r0, #+1]
0x123ed20    03a0c033               moveq ip, #51
0x123ed24    e1a090c9               mov r9, r9, asr #1
0x123ed28    e15c0009               cmp ip, r9
0x123ed2c    1afffff7               bne -28 ; 0x123ed10
        ;; Intrinsic
0x123ed30    e59d0000               ldr r0, [sp, #+0]
0x123ed34    e59d1004               ldr r1, [sp, #+4]
0x123ed38    e180c001               orr ip, r0, r1
0x123ed3c    e31c0001               tst ip, #1
0x123ed40    1a00000d               bne +60 ; 0x123ed7c
0x123ed44    e3500000               cmp r0, #0
0x123ed48    0a00000b               beq +52 ; 0x123ed7c
0x123ed4c    e1a000c0               mov r0, r0, asr #1
0x123ed50    e1a010c1               mov r1, r1, asr #1
0x123ed54    ee011a10               vmovs s2, r1
0x123ed58    eeb81bc1               vcvtdi d1, s2
0x123ed5c    ee000a10               vmovs s0, r0
0x123ed60    eeb80bc0               vcvtdi d0, s0
0x123ed64    ee810b00               vdivd d0, d1, d0
0x123ed68    eebd0bc0               vcvtid s0, d0
0x123ed6c    ee100a10               vmovr r0, s0
0x123ed70    e3500101               cmp r0, #1073741824
0x123ed74    11a00080               movne r0, r0, lsl #1
0x123ed78    112fff1e               bxne lr
```

Notice that VFP instructions are used instead of SDIV. 

Please apply my patch, delete all build artifacts, delete flutter tools snapshot and then do `flutter build aot -v --release` and verify that you see `--no-use-integer-division` passed to the `gen_snapshot` invocation.

**Comment by kangwang1988** [comment]
@mraleph 
Good news.
I've verified your patch works.
Previously, I mis-modify the build_aot.dart and added flag to the command-line arguments for android.Sorry.

Thanks for your time.

**Comment by eseidelGoogle** [comment]
@mraleph do you still need this open to apply your patch to master?  Or was that already done?

**Comment by mraleph** [comment]
@cbracken I think this needs to be incorporated in your patches somehow. We need to pass `--no-use-integer-division` to `gen_snapshot`

**Comment by mraleph** [comment]
@kangwang1988 thanks for confirming it works now!

**Comment by kangwang1988** [comment]
@mraleph 
As a patch for ios,is it for armv7 only or armv7&arm64?

**Comment by mraleph** [comment]
@kangwang1988 only for `armv7`. ARM64 always has `sdiv`

**Comment by kangwang1988** [comment]
@mraleph 
Never mind, we've done it on our own.
In my practice, it only applies to armv7.
Thanks.

**Comment by cbracken** [comment]
#2089 is now landed and ensures that `--no-use-integer-division` is set on armv7 builds for iOS.
