### ISSUE TITLE
Would like instructions on how to implement onSaveInstanceState

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#16799]
https://twitter.com/championswimmer/status/987327881960357889

My understanding is that FlutterView will handle the config change if AndroidManifest.xml contains:
`android:configChanges="orientation|screenSize"`
https://developer.android.com/guide/topics/resources/runtime-changes.html

But I'm not sure that we've written that down anywhere in our docs.  I believe some of our sample are locked to portrait for historical reasons too?

**Comment by eseidelGoogle** [comment]
I'm aware of at least one bug reported with Flutter's rotation code: https://github.com/flutter/flutter/issues/16322 there may be others.

**Comment by championswimmer** [comment]
There needs to be documentation regarding how `onSaveInstanceState` is to be implented in Flutter as well.

**Comment by championswimmer** [comment]
Also pertinent : https://github.com/flutter/flutter/issues/6827

**Comment by Sfshaza** [comment]
Yes, added to content plan.

**Comment by Sfshaza** [comment]
OK, PR  https://github.com/flutter/website/pull/1037 handles the documenting landscape view and also that android should not restart a Flutter app.

The onSaveInstanceState doc is not yet written.

**Comment by mzgreen** [comment]
Please note that `onSaveInstanceState` is not only about persisting state during config changes. More important part is that it's used it to persist transient app state when OS kills the app when it's in background.
https://developer.android.com/topic/libraries/architecture/saving-states#system_initiated_ui_state_dismissal

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2004](https://github.com/flutter/website/issues/2004) via [**ZenHub**](https://www.zenhub.com/)
