### ISSUE TITLE
firebase_auth on ios not using getTokenId refresh bool

### ISSUE THREAD

**Issue by bjon** [flutter/flutter#16807]
Refresh bool is hard coded to YES for ios. Android uses the bool as expected.

https://github.com/flutter/plugins/blob/master/packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
```swift
  } else if ([@"getIdToken" isEqualToString:call.method]) {
    [[FIRAuth auth].currentUser
        getIDTokenForcingRefresh:YES
                      completion:^(NSString *_Nullable token, NSError *_Nullable error) {
                        result(error != nil ? error.flutterError : token);
                      }];
```

**Comment by kroikie** [comment]
@bjon

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/847. Any further collaboration will be done there.
