### ISSUE TITLE
Switch breaks on Release Touch in Middle

### ISSUE THREAD

**Issue by AppleEducate** [flutter/flutter#16800]
## Steps to Reproduce

1. Create new Switch and initialize it.
2. Run App
3. Toggle Switch Normally
4. Then Toggle Switch Half Way and Release
![videotogif_gif](https://user-images.githubusercontent.com/31253215/39060824-6a810fc8-4490-11e8-8da3-fb8e446cf3b7.GIF)

## Flutter Doctor
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

• No issues found!
exit code 0

**Comment by zoechi** [comment]
Seems to be a dup of #17773 and fixed.
