### ISSUE TITLE
Support splitting a Flutter app's Dart code into multiple packages

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16813]
In Fuchsia land, we will want different `package:` boundaries to create different .dill files each of which can be shipped separately and loaded independently (though run all together).

We also need to be able to run code as part of hot updates.

We also need to be able to split the code up into different APKs for Android Instant Apps.

cc @zanderso @tvolkert @jason-simmons @chinmaygarde @cbracken

**Comment by Hixie** [comment]
See also: https://github.com/flutter/flutter/issues/16812, https://github.com/flutter/flutter/issues/16815,

**Comment by kf6gpe** [comment]
cc @iskakaushik -- we haven't heard this as a concrete ask from Fuchsia, have we?

**Comment by jmagman** [comment]
\cc @GaryQian re: https://github.com/flutter/flutter/issues/57617, not sure what work these are separately tracking.

**Comment by zanderso** [comment]
> In Fuchsia land, we will want different `package:` boundaries to create different .dill files each of which can be shipped separately and loaded independently (though run all together).

This was done.

> We also need to be able to run code as part of hot updates.

I'm not sure about the status of this, but it sounds like it could use its own issue if should still be a priority.
 
> We also need to be able to split the code up into different APKs for Android Instant Apps.

This is being more actively tracked here: https://github.com/flutter/flutter/issues/57617
