### ISSUE TITLE
MissingPluginException on iOS native/flutter hybrid 

### ISSUE THREAD

**Issue by alexwhiteside1** [flutter/flutter#16819]
## Steps to Reproduce

I've merged flutter into our existing iOS application by moving all our native files into the Runner Xcode project and adding our pods into the pod file. The application currently works, however every flutter plugin fails due to 

```
MissingPluginException(No implementation found
```

I'm thinking in some way while merging the projects, I messed up/broke however flutter manages plugins and their method channels natively, and I can't find any documentation on how that system works. All plugins work fine on Android and on iOS with the original empty Runner. 

Architecture :

-Swift 4 native app with storyboards and xibs
-Initial storyboard/controller is native. 
-Eventually a user gets into the flutter feature via a segue and is then within flutter until the return to the previous view. (All pure dart/flutter works fine) 
-Upon launch of the FlutterViewController I create a custom method channel that I use to pass the bearer token so Flutter can do all its own API calls.  (which works fine) 

```dart
  if(segue.identifier == "showFlutter"){
            
            let controller = segue.destination as! FlutterViewController
            let channel = FlutterMethodChannel(
                name: "base",
                binaryMessenger: controller,
                codec: FlutterJSONMethodCodec.sharedInstance())
            channel.setMethodCallHandler{(call: FlutterMethodCall?, result: FlutterReply?) -> Void in
                print("Swift-> methodCallHandler \(call!.method)")
                
                switch (call!.method) {
                case "getToken":
                    let keychainSwift = KeychainSwift()
                    let token = keychainSwift.get("token")
                    if token != nil{
                        result!(token!)
                    }else{
                        result!("ERROR")
                    }
                    break;
                default:
                    print("Error !!! Unknown method -> \(call!.method)")
                }
            }
        }
```
- 3 Plugins are used within my Flutter project, 2 of which require native method calls. None of which work on iOS (all work fine on Android, and work when I use an empty runner):
-flutter_secure_storage
-url_launcher
-cached_network_image

Things I've done/confirmed:
1) AppDelegate extends FlutterAppDelegate
2) All AppDelegate functions overridden and call super. 
3) "GeneratedPluginRegistrant.h" added to bridging header
4) GeneratedPluginRegistrant.register(with: self) called in didFinishLaunchingWithOptions
5) Confirmed that the pods for the plugins are being used 
```
Using flutter_secure_storage (0.0.1)
Using local_auth (0.0.1)
Using nanopb (0.3.8)
Using package_info (0.0.1)
Using path_provider (0.0.1)
Using share (0.0.1)
Using shared_preferences (0.0.1)
Using url_launcher (0.0.1)
```
6) Confirmed that the plugins show up as targets in my Pods project. 
![screen shot 2018-04-20 at 13 40 04](https://user-images.githubusercontent.com/5420059/39072766-616d29c0-44a0-11e8-84bb-7564c0039ee8.png)

Yet, for all native calls, I get a 'MissingPluginException(No implementation found'

## Logs

Using any of the plugins results in:
```
MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      canLaunch (package:url_launcher/url_launcher.dart:63:25)
<asynchronous suspension>
#2      launchURL (package:birch/PortfolioRecs/PortfolioDetailpage.dart:789:13)
<asynchronous suspension>
#3      PortfolioDetailPageState.build.<anonymous closure> (package:birch/PortfolioRecs/PortfolioDetailpage.dart:332:27)
<asynchronous suspension>
#4      _PopupMenuButtonState.showButtonMenu.<anonymous closure> (package:flutter/src/material/popup_menu.dart)
#5      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:666:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:481:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:511:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.2.11, on Mac OS X 10.13.3 17D102, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
[✓] Connected devices (2 available)
```

**Comment by cyanglaz** [comment]
@alexwhiteside1 Did @zoechi 's link help?

**Comment by Alok81234881** [comment]
@alexwhiteside1 have you solved this issue?
if yes, then please provide the solution for the same

**Comment by weekitmo** [comment]
looking for it for so long, this kind of problem has never been solved.

**Comment by Alok81234881** [comment]
@weekitmo Provide me with the steps that you followed.

**Comment by weekitmo** [comment]
@Alok81234881 like this issue #59683

**Comment by mugbug** [comment]
FYI,
I had a similar one and it took me a while to figure out the problem. So here's what I did:
- On iOS-side:
```swift 
// instead of using `initialRoute`
engine.run(withEntrypoint: nil, initialRoute: route)

// switch to default
engine.run()
```

- On Flutter-side
```dart
void main() => runApp(App());

class App extends StatelessWidget {
   App({Key key}) : super(key: key);

   @override
   Widget build(BuildContext context) {
     return MaterialApp(
       // instead of expecting the iOS to invoke a route
       routes: {
         '/some_custom_route': (c) => MyCustomScreen(),
       }
       // set your screen as the `home`, once you won't be inputing a custom route name
       home: MyCustomScreen(),
     );
   }
 }
```

> Note: probably there's a way to keep using route names when running the engine, but I still need to dig a little deeper to figure that out.
