### ISSUE TITLE
Support shipping Flutter's engine as a separate package from the Dart code and assets

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16812]
In Fuchsia land, we will want .dill files to be able to ship separately from the engine.

cc @zanderso @tvolkert @jason-simmons @chinmaygarde @cbracken

**Comment by Hixie** [comment]
See also: https://github.com/flutter/flutter/issues/16813, https://github.com/flutter/flutter/issues/16815

**Comment by fmatosqg** [comment]
I love the idea for Instant Apps. Shipping the engine separately plus SVG support can enable very skinny apks.

**Comment by chinmaygarde** [comment]
> In Fuchsia land, we will want .dill files to be able to ship separately from the engine.

Not clear what need to be done here. The engine is already a separate dylib. Dart code that is either in .dill form or in AOT form in a .dylib is loaded separately.

**Comment by fmatosqg** [comment]
A source of inspiration for me are apps based on OpenCv. You have the option to bundle the libraries for android inside apps apk file (quite big) or check if there's a dedicated library app installed similar in concept to a `.so` library in a desktop. And redirect user to play store when not available.

It may need for play store support for seamless Android support. 

https://play.google.com/store/apps/details?id=org.opencv.engine
http://answers.opencv.org/question/2188/opencv-for-android-do-i-need-to-install-opencv-manager-separately/

**Comment by Hixie** [comment]
Based on @chinmaygarde's comment earlier, sounds like this one is done already.
