### ISSUE TITLE
Recipe page doesn't link to other recipes or cookbook, hard to tell what I'm looking at

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#16828]
We're now linking to recipes from #FlutterFriday tweets. Yay! But, when you view the recipe, especially on mobile, it's not clear what you're looking at, and it's not clear how to find the other recipes.

Suggestion: add a link to the Cookbook homepage (maybe at the top, near the title), making it clear that "this is a recipe" and "there's a whole bunch of other recipes" :)

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by brianegan** [comment]
@zoechi It is! I've talked with the Flutter team and they mentioned they're working on some redesigns of the documentation pages and so I've held off on adding anything like this manually. 

That said, perhaps I can add a "Breadcrumb" module for Jekyll see if it works for this purpose.

**Comment by Sfshaza** [comment]
I like the idea of a breadcrumb for the cookbook. But, yes, given that we are reworking the website, I want to avoid setting up links that will have to be changed in the near future.

**Comment by zoechi** [comment]
@Sfshaza 

>  given that we are reworking the website

Is this still wip or is this completed already?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2070](https://github.com/flutter/website/issues/2070) via [**ZenHub**](https://www.zenhub.com/)
