### ISSUE TITLE
Users evaluating Flutter find the app size is 30MB (because they are in debug mode)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#16829]
We see tweets like "why is a Flutter app 30MB?" , which might be true in debug mode, but in production/release mode the apps are much smaller.

In order to avoid incorrect assumptions (e.g. "all flutter apps are 30MB or bigger", which is not correct) I wonder if our tools can display some output that explains the size.

For example, after a `flutter run` or `flutter build`, perhaps we can print "App size is much bigger in debug mode. For a smaller, faster app, build with --release. Read more here: ______" or similar.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
We currently print out:

```
Built build/app/outputs/apk/debug/app-debug.apk (34.2MB).
```

in debug, profile, and release mode. Showing the size in debug mode isn't generally useful, and can cause confusion about our actual on-device size for release builds.

We could change that to something like:

```
Built build/app/outputs/apk/debug/app-debug.apk (34.2MB; note that debug mode builds are larger than release ones).
```

but that seems a little wordy, esp. given that most user runs will be in debug mode. I think we should just not emit the app size in debug builds.

**Comment by sethladd** [comment]
>  I think we should just not emit the app size in debug builds.

That's a good start.
