### ISSUE TITLE
checked mode needs a visual indicator

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1682]
First thing that came to mind is one of the corners could have a red tag. Even just a few pixels would help me look at someones screen and not have to ask "is that in checked mode?" (i.e. should I care that it's slow?)

Maybe a red check-mark? :heavy_check_mark: 

@Hixie @apwilson

**Comment by Hixie** [comment]
![checked-mode](https://cloud.githubusercontent.com/assets/551196/12902671/6f0c6466-ce77-11e5-9c60-375c6aa2517c.png)
