### ISSUE TITLE
Issue from website page Parsing JSON in the background

### ISSUE THREAD

**Issue by bellemere** [flutter/flutter#16845]
From URL: https://flutter.io/cookbook/networking/background-parsing/

At line 20 it should be:
```
return parsed.map<Photo>((json) => new Photo.fromJson(json)).toList();
```
a "Photo" is necessary after map, or it will report:
>type 'List<dynamic>' is not a subtype of type 'List<Photo>'

**Comment by bellemere** [comment]
sorry., the error message is:
>type 'List\<dynamic\>' is not a subtype of type 'List\<Photo\>'

**Comment by brianegan** [comment]
Thanks! A fix for this is in review.

**Comment by brianegan** [comment]
Fixed is now deployed
