### ISSUE TITLE
Why when I tab TabBar it jumps across another TabBarView?

### ISSUE THREAD

**Issue by wisit-phusi** [flutter/flutter#16843]
Usually, When develop by Android Native will slide across every view but when I use TabBar in Flutter and I tab to navigate to another Tab, It looks like appear by Transition.

This is the example.
https://drive.google.com/file/d/1GxQdAFTijoSqMKl8Ot0LusQUNldSIFKE/view?usp=sharing

It should be like this.
https://drive.google.com/file/d/1dHcZjs_wUtolKafPvSTff_YWXI8Di2g6/view?usp=sharing

**Comment by harrisonturton** [comment]
Quick note:
I looked through the [Material Design Tab Specs](https://material.io/guidelines/components/tabs.html#tabs-specs) expecting to find Flutter's current behavior -- but I found neither the current, nor the proposed one.
