### ISSUE TITLE
Make Flutter Docs Microsoft Edge Friendly

### ISSUE THREAD

**Issue by bramvbilsen** [flutter/flutter#16849]
Currently, the documentation website for Flutter([https://docs.flutter.io/](https://docs.flutter.io/)) does not work well on Microsoft Edge. Call me crazy, but I actually really enjoy Edge as a web browser. And it is inconvenient that I have to have two web browsers open just to browse the docs.
Anyways, whether you like Edge or not, searching in the docs (via the search bar) leads to the following error page:
![capture](https://user-images.githubusercontent.com/16825392/39088535-33eaf896-45b4-11e8-8de8-59706d8b13ff.PNG)
This should not happen.

**Comment by Hixie** [comment]
Probably a bug in Edge?

**Comment by bramvbilsen** [comment]
I can't think of any other website that has this behavior on Edge.

**Comment by miyoyo** [comment]
This URL doesn't work on chrome either.

Your url is https://docs.flutter.io/flutter/widgets/widgets/Text-class.html , whereas it should be https://docs.flutter.io/flutter/widgets/Text-class.html

**Comment by miyoyo** [comment]
Behaviour is caused because of this
![applicationframehost_2018-04-23_15-12-53](https://user-images.githubusercontent.com/3525610/39128730-d840bd04-4708-11e8-868e-aa781551f2f5.png)
Which calls a script (script.js) which does this:
![Script](https://i.imgur.com/FL7QxWM.png)

I'm not sure why chrome keeps the "/flutter/" and cuts everything else after that, but edge just changes the top level element

So either edge implements it correctly and chrome is wrong, both are wrong or there is some javascript magic I'm not aware of that keeps the "/flutter/" in the URL

**Comment by Hixie** [comment]
Edge is wrong. 

Setting `window.location` goes through this: https://html.spec.whatwg.org/#dom-location-href
This refers to the base URL set here: https://html.spec.whatwg.org/#script-settings-for-window-objects
...which, if you follow it through, is the document's URL.

So setting window.location should parse the URL relative to the document's URL, which means the
`/widgets/` should remain.

**Comment by bramvbilsen** [comment]
Not sure why "widgets" was in the url twice, but I tried searching again and it generated this url: [https://docs.flutter.io/flutter/widgets/foundation/Listenable-class.html](url)
I'm getting the same error page.

**Comment by Hixie** [comment]
On Edge, or in every browser?

**Comment by bramvbilsen** [comment]
Just Edge 😥

**Comment by bramvbilsen** [comment]
Exactly, the user shouldn't have to worry about the browser (s)he uses.

**Comment by Hixie** [comment]
Sure, I'm just trying to figure out what kind of issue we should be looking for though when fixing it.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1915](https://github.com/flutter/website/issues/1915) via [**ZenHub**](https://www.zenhub.com/)
