### ISSUE TITLE
Support golden file image diffing in `testWidgets`

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16859]
After https://github.com/flutter/flutter/pull/16758 lands, we'll ostensibly have the ability to capture a screenshot in a widget test running via `flutter_tester` and compare it to a golden file, as follows:

```dart
testWidgets('test', (WidgetTester tester) async {
  await tester.pumpWidget(new MyApp());

  // Get the bytes of the screenshot
  RenderRepaintBoundary repaintRenderBoundary = tester
      .allRenderObjects
      .firstWhere((RenderObject object) => object is RenderRepaintBoundary);
  ui.Image image = await repaintRenderBoundary.toImage();
  ByteData bytes = await image.toByteData(format: ui.ImageByteFormat.png);

  // Get the bytes of the golden file
  File golden = new ui.File('/path/to/golden.png');
  List<int> goldenBytes = await golden.readAsBytes();

  // Fail the test if the screenshot isn't within tolerance of golden
  ...
});
```

But doing so causes the following exception due to `flutter_test`'s use of `FakeAsync`:

```
  TimeoutException after 0:00:05.000000: Test timed out after 5 seconds.
  dart:async  _startMicrotaskLoop
```

A hacked up attempt to call `_fakeAsync.flushTimers()` ends up yielding the same exception when we await that call.

**Comment by Hixie** [comment]
we should just have a "tester.compareToGolden" or something that jumps through the appropriate hoops.

**Comment by tvolkert** [comment]
Within Google, there's an existing system set up to do golden file comparisons (it saves results to a location where they can be visualized, etc.).  It has roughly the following API:

```dart
typedef Future<List<int>> ScreenshotTaker();

class GoldenFileComparisonService {
  /// User-defined function for taking a screenshot.
  ScreenshotTaker takeScreenshot;

  /// Makes a diff request against a golden image and publishes the result.
  Future<Null> diffScreenshot(String key);
}
```

Then test code is expected to hook into the API like so:

```dart
void main() {
  GoldenFileComparisonService service;

  setUp(() {
    service = new GoldenFileComparisonService();
  });

  testWidgets('matches golden file', (WidgetTester tester) async {
    service.takeScreenshot = () async {
      // Use `tester` to get image bytes
    };

    await service.diffScreenshot('imageKey.png');
  });
}
```

So at the heart of it, the service expects two things:

1) We have a method that can return `Future<List<int>>` for the screenshot bytes
2) We can safely `await` arbitrary futures in our test code

We potentially have some amount of influence over that API, but we _do_ want to delegate to the service to do the comparison, because it exports its findings in such a way that they can be visualized in test results (providing a suite of UI tools for visualizing the differences and approving the test files as the new goldens).

**Comment by Hixie** [comment]
SGTM.

Rather than `--local-goldens` how about just putting the checkout in `bin/cache`? That way everyone has it in a known location.

We'll have to make sure the `flutter_test_config.dart` logic is protected by a lock to prevent multiple simultaneous checkouts or some such.

**Comment by tvolkert** [comment]
Currently blocked on https://github.com/dart-lang/sdk/issues/32982

**Comment by tvolkert** [comment]
As of https://github.com/flutter/flutter/pull/17141 (out for review), the only item left is to build a Flutter-specific test configuration in `packages/flutter/test/flutter_test_config.dart` that sets up a custom comparator that loads its golden files from a newly created `flutter/goldens` repo.

**Comment by tvolkert** [comment]
Ok, marking this as done.  There are still several improvements we should make, being tracked in:

* https://github.com/flutter/flutter/issues/17258 -- Implement better logic in golden file comparators
* https://github.com/flutter/flutter/issues/17259 -- Allow centralized place where tests can output files
* https://github.com/flutter/flutter/issues/17260 -- Visualize golden image file failures in test output
* https://github.com/flutter/flutter/issues/17262 -- Test golden files without shadows

**Comment by FrankApiyo** [comment]
This this in production already?

**Comment by rknell** [comment]
@FrankApiyo Just found this:
https://medium.com/flutter-community/flutter-golden-tests-compare-widgets-with-snapshots-27f83f266cea
