### ISSUE TITLE
i try the test drive but failed

### ISSUE THREAD

**Issue by guanbiao33** [flutter/flutter#16851]
##Run my application with `flutter run` and attach all the log output.
G:\flutterws\myapp3>flutter run
Launching lib/main.dart on Custom Tablet, 6 0 0, API 23, 1536x2048 in debug mode
...
Initializing gradle...
Built build\app\outputs\apk\debug\app-debug.apk (30.3MB).

and my phone shown me an alert said, Unfortunately,myapp3 has stopped!
-----------------------------------------------------------------------------------------------------
##Run `flutter analyze` and attach any output of that command also.
G:\flutterws\myapp3>flutter analyze
Analyzing G:\flutterws\myapp3...
No issues found!
Ran in 13.2s
-----------------------------------------------------------------------------------------------------
## Flutter Doctor
λ flutter doctor -v
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 0.2.8 at G:\flutter
    • Framework revision b397406561 (3 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at G:\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = G:\android-sdk-windows
    • Java binary at: E:\developer\AS\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at E:\developer\AS
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices (1 available)
    • Custom Tablet, 6 0 0, API 23, 1536x2048 • 192.168.13.101:5555 • android-x86 • Android 6.0 (API 23)

• No issues found!

**Comment by zoechi** [comment]
Please check if you can reproduce in `dev` channel and `master` channel as well
`flutter channel dev`

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by guanbiao33** [comment]
@zoechi No，thank you

**Comment by zoechi** [comment]
Thanks for the update!
