### ISSUE TITLE
fontStyle and fontWeight properties of Text widget are not working.

### ISSUE THREAD

**Issue by mohith7548** [flutter/flutter#16853]
## But this is what I'm getting....

![screenshot_20180422_164918](https://user-images.githubusercontent.com/24828445/39094479-b36ad1ba-464d-11e8-8645-8f66c19b7035.jpg)

## Steps to Reproduce
I'm trying to make the text look Bold and Italic, but it is not working for me. fontStyle and fontWeight are not working for me. Other properties like fontSize, color are perfectly fine. I wonder why this is happening. here is the main.dart code. please let me know if I'm doing anything wrong.

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Material(
        child: new Center(
          child: new Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              new Text('Hello World',
                style: new TextStyle(
                  fontSize: 30.0,
                  fontWeight: FontWeight.bold,
                  color: Colors.blueAccent,
                ),
              ),
              new Text('Welcome Kune Mohith',
                style: new TextStyle(
                  fontSize: 20.0,
                  fontStyle: FontStyle.italic,
                  color: Colors.pinkAccent,
                ),
              ),
            ],
          )
        ),
      )
    );
  }
}```

## Flutter Doctor

muser@kali:~$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /home/muser/flutter
    • Framework revision b397406561 (3 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/muser/Android/Sdk
    • Android NDK at /home/muser/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/muser/MySoftware/Cananry-android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/muser/MySoftware/Cananry-android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /home/muser/MySoftware/idea-IC-173.4548.28
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • vivo V3Max • 8464c02f • android-arm64 • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
Code blocks should be wrapped in ``` instead of a single backtick. 
Single backticks are just for inline code.
Please also try in `master` channel to check if the issue wasn't already fixed.

**Comment by andela-pessien** [comment]
@mohith7548 Could you post the `fonts` section of your `pubspec.yaml` file as well? It might be that you're missing the bold/italic font files for your font family or haven't pointed them out to Flutter. [This](https://flutter.io/cookbook/design/fonts/) should provide more info about adding custom fonts.

**Comment by filleduchaos** [comment]
@mohith7548 Could you post the fonts section of your pubspec.yaml file as well? It might be that you're missing the bold/italic font files for your font family or haven't pointed them out to Flutter. [This](https://flutter.io/cookbook/design/fonts/) should provide more info about adding custom fonts.

**Comment by najeira** [comment]
I tested it with 0.3.4. FontWeight.w600 is works but w500 is same as w400.

**Comment by filleduchaos** [comment]
Do you have the medium font file for your family, and did you declare it in
your pubspec.yaml?

There's a standard heuristic for determining the absolute font weight to
actually render. If the font family you're using doesn't provide glyphs at
weight 500 then yes, rendering them at weight 400 is the norm.

**Comment by najeira** [comment]
I am not using custom fonts. 

With Flutter 0.2.1, texts became a bold at w500.

**Comment by filleduchaos** [comment]
@najeira That's strange - what device/simulator are you running on? On 0.3.3 and on 0.3.6-pre.7 font weights 400, 500 and 600 are distinctly rendered on my Android phone and on iOS Simulator (the difference is a bit less clear on my phone, but it's a small-ish screen/resolution and if anything the medium (500) weight looks a bit *too* bold).

**Comment by najeira** [comment]
I tested it with Japanese text. Perhaps alphabets are okay.

**Comment by mohith7548** [comment]
Hey I just upgraded the Flutter Sdk Today morning and it just fixed the problem. I thinsk it was a bug in the previous version, now It's completely fixed ! ThankYou, Flutter Team
