### ISSUE TITLE
a11y: public webpage docs text readability could be better

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16860]
Report from an internal customer:

> https://flutter.io/getting-started/
>
> Site is now rendered using 'Roboto Light', which results is too-low contrast. Consider using Roboto Normal.
>
> Changing main.css line 22 to 'font-weight: normal' in chrome devtools made a massive difference.

/cc @mit-mit

**Comment by mit-mit** [comment]
I gave it a try, and moving from weight 300 to 500 looks a bit too heavy for my personal taste:

300:
![screen shot 2018-04-23 at 11 09 13](https://user-images.githubusercontent.com/13644170/39117238-cf376d10-46e6-11e8-8ae2-b79a795fcca2.png)

500:
![screen shot 2018-04-23 at 11 09 25](https://user-images.githubusercontent.com/13644170/39117237-cf1e5de8-46e6-11e8-927a-4c517f57a8ae.png)

**Comment by mit-mit** [comment]
cc @mjohnsullivan @filiph 

Maybe try changing to sans-serif and weight 400 (which I believe a number of Google products use)?

**Comment by filiph** [comment]
If this really is a a11y concern, then I think we should go with `font-weight: normal`, even though I personally find it less pleasing to the eye.

Was the original feedback from an internal customer really a11y-driven (i.e. there's an a11y guideline against using light fonts, or the person is an a11y expert), or was it more a personal preference feedback?

**Comment by tvolkert** [comment]
I think it was personal preference feedback.  That said, maybe we could get an a11y review of our site from a Google a11y team?

**Comment by Sfshaza** [comment]
We are having an ally review of the new (in process) site. Closing this.
