### ISSUE TITLE
Website contains incomplete information on gradle 4.1 migration instructions

### ISSUE THREAD

**Issue by fmatosqg** [flutter/flutter#16867]
The page mentions updating some versions in gradle file, specifically from `25.0.3` to `27.0.3`. 
- expected that users will do that update for build tools
- docs don't mention anything about build tools, support library or dex
- build tools 27.0.3 exists but support library doesn't exist
- I got a dev understandably updating support library and running into "lib not found" problems

I'd submit the PR myself but I can't find the md file on github. I'd be happy to do it if somebody can point me into the right direction.

- page needing update https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1
- I can see the footnote on that link directing me to clone https://github.com/flutter/flutter.wiki.git but I'd rather edit on Chrome as usual.

**Comment by Sfshaza** [comment]
@zoechi, the website and wiki are separate and supported by different groups. Maybe we need a wiki label.

**Comment by zoechi** [comment]
@Sfshaza very much appreciate such feedback to be able to better triage in the future!!

**Comment by Sfshaza** [comment]
Thanks, @zoechi!  Your community contribution of triaging the bugs is much appreciated. I hope you have a Dash or two.  :)

**Comment by zoechi** [comment]
The wiki says

> (This wiki page applies to people migrating code written before February 2017. It is unlikely to still be relevant. The flutter tool directs people to this page when a non-Gradle project is detected.)

I think it's unlikely further work will happen here.

I'm going to close.
Feel free to add a comment if you disagree to have it reopened.
