### ISSUE TITLE
Request: Add Discord Flutter Community Server to Flutter pages

### ISSUE THREAD

**Issue by apritykin** [flutter/flutter#16862]
As requested by: [Twitter](https://twitter.com/g33kidd/status/988099808576573441)
There is a growing developer community on Discord dedicated to Flutter. Discord is a very popular chat for gamers/developers due to its application that also includes voice channels for developers to collaborate together in real time. In no way are we trying to split the community from Gitter; a lot of users use Discord for other communities (such as /r/Android and Swift).

https://discord.gg/p7Aj8wF

**Comment by apritykin** [comment]
Thanks to KingBaal on Reddit, server link has been added under the Misc section sidebar of /r/FlutterDev

**Comment by acidjazz** [comment]
I would say that we could use a badge that points to that invite URL on the readme as well
