### ISSUE TITLE
"Team" Icon

### ISSUE THREAD

**Issue by kentcb** [flutter/flutter#16869]
It's not clear to me where `CupertinoIcons.ttf` comes from (is it created by google? By Apple?) but this icon strikes me as more than a little bit off:

![image](https://user-images.githubusercontent.com/1901832/39104938-13e9983e-46f6-11e8-8052-20c289f47abd.png)

I was looking for an icon to represent "team", but I think I'll pass on using a man standing in front of two women.

Can this be fixed? Or am I overlooking a specific purpose for this icon (maybe for all the pimp apps)?

**Comment by xster** [comment]
Sorry for the confusion. It's from an open source third party font done to the style of iOS fonts. http://ionicons.com/ 

It's likely a coincidence. For any additional semantics besides the system default icons https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/system-icons/, I'd recommend using your own icon or icon font.
