### ISSUE TITLE
http.MultipartRequest with utf-8 support for body fields 

### ISSUE THREAD

**Issue by Eimji** [flutter/flutter#16879]
Hello

I writing a form to upload one image along with form fields
```
Future<Map<String, dynamic>> multipartPostRequest(String method, String route, Map<String, String> bodyFields,  List<http.MultipartFile> files) async {
    // method = POST or PUT...
    var url = Uri.parse( Application.backendBaseURL + route);
    var request = new http.MultipartRequest(method, url)
    ..fields.addAll(bodyFields);
    if (files != null && files.length > 0)
      request.files.addAll(files);    


    return LocalAuth.getJWToken()
    .then((token) {
      request.headers[HttpHeaders.AUTHORIZATION] = 'Bearer $token';
      return request.send();
    })
    .then((streamedResponse) {
      _updateJWTokenFrom(streamedResponse);
      return http.Response.fromStream(streamedResponse);
    })
    .then((response) {
      return response.body;
    })
    .then((body) {
      if (isJSON(body))
        return json.decode(body);
      else 
        return {'mssg': body};
    })
    .catchError((e) {
      return {'mssg': 'Got error: $e'};
    });
  }
}

```

This code for making a POST as multipart/form-data works well, but whan a body field contains characters such as é à ç, the field is reset to empty. So my question is how can I make a post multipart/form-data with fields in utf-8 ?
Trying to add request.headers[HttpHeaders.CONTENT_TYPE] = 'multipart/form-data;charset=utf-8'; does not change.

Thanks a lot in advance

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!

**Comment by jonahwilliams** [comment]
@Eimji is that the multipart request class from `package:http`? If so I would file an issue on it's repo https://github.com/dart-lang/http, since it's not maintained by the flutter team directly.

**Comment by Eimji** [comment]
@jonahwilliams yes !! It's package http. 
Thanks

**Comment by zoechi** [comment]
@Eimji did you report the issue there? Can this be closed?
