### ISSUE TITLE
Rebuild the engine and run, crashed with log 'Error while initializing the Dart VM: Wrong full snapshot version, expected 'cd8223b4ae8a3e78182fd55e29ba31de' found '39646f79e9336fb65ac68c8568544c92''

### ISSUE THREAD

**Issue by LevinYan** [flutter/flutter#16876]
## Steps to Reproduce

I rebuild the engine following the steps from [(CONTRIBUTING.md)](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md) , and run the example project with Flutter.framework. I get crash with log ' Runner[91916:11242220] [VERBOSE-3:dart_init.cc(698)] Error while initializing the Dart VM: Wrong full snapshot version, expected 'cd8223b4ae8a3e78182fd55e29ba31de' found '39646f79e9336fb65ac68c8568544c92''. Does anyone know how to fix it. Thank you

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`

**Comment by LevinYan** [comment]
flutter doctor -v
[✓] Flutter (Channel master, v0.3.1-pre.34, on Mac OS X 10.13.2 17C88, locale zh-Hans-CN)
    • Flutter version 0.3.1-pre.34 at /Users/levinyang/Desktop/Project/Tencent/flutter
    • Framework revision 044dfdb446 (5 days ago), 2018-04-18 17:46:20 -0700
    • Engine revision c73be7ada2
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode9.2.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.0.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • iPhone 8 Plus • 2D71DF13-BEA9-42CD-90D4-32239D024E8D • ios • iOS 11.2 (simulator)


I just need run in iOS platform

**Comment by ninexus-pankaj** [comment]
I do have the same Isuse,please help

**Comment by ninexus-pankaj** [comment]
@zoechi the vs code give option about the dart  upgrade available and it got updated, after this has happen I believe it stoped working,  after it,

**Comment by zoechi** [comment]
@ninexus-pankaj 
Please add the output of `flutter doctor -v`.

**Comment by ninexus-pankaj** [comment]
Just to brief it again 

I did as suggested Deleted Flutter/bin/Cache , run the flutter doctor after it , run the flutter iOS build, it build fine, in Xcode 10, run the Runner app on iOS 12 iPhone 7 , it builds fine , but when it get installed on iPhone it gives the same error 

**Error Log** 
2018-11-22 19:32:07.208596+0530 Runner[616:95067] [VERBOSE-3:dart_vm.cc(403)] Error while initializing the Dart VM: Wrong full snapshot version, expected '8343f188ada07642f47c56e518f1307c' found '46b2bfb57b5647c5f7527ff9aa56c69b'
(lldb) 

**Thread Output**

Runner`main:
    0x102c7bf20 <+0>:   sub    sp, sp, #0x40             ; =0x40 
    0x102c7bf24 <+4>:   stp    x29, x30, [sp, #0x30]
    0x102c7bf28 <+8>:   add    x29, sp, #0x30            ; =0x30 
    0x102c7bf2c <+12>:  stur   wzr, [x29, #-0x4]
    0x102c7bf30 <+16>:  stur   w0, [x29, #-0x8]
    0x102c7bf34 <+20>:  stur   x1, [x29, #-0x10]
    0x102c7bf38 <+24>:  bl     0x102d5ddf4               ; symbol stub for: objc_autoreleasePoolPush
    0x102c7bf3c <+28>:  adrp   x1, 347
    0x102c7bf40 <+32>:  add    x1, x1, #0x6c8            ; =0x6c8 
    0x102c7bf44 <+36>:  adrp   x30, 351
    0x102c7bf48 <+40>:  add    x30, x30, #0x730          ; =0x730 
    0x102c7bf4c <+44>:  ldur   w8, [x29, #-0x8]
    0x102c7bf50 <+48>:  ldur   x9, [x29, #-0x10]
    0x102c7bf54 <+52>:  ldr    x30, [x30]
    0x102c7bf58 <+56>:  ldr    x1, [x1]
    0x102c7bf5c <+60>:  str    x0, [sp, #0x18]
    0x102c7bf60 <+64>:  mov    x0, x30
    0x102c7bf64 <+68>:  str    w8, [sp, #0x14]
    0x102c7bf68 <+72>:  str    x9, [sp, #0x8]
    0x102c7bf6c <+76>:  bl     0x102d5de9c               ; symbol stub for: objc_msgSend
    0x102c7bf70 <+80>:  bl     0x102d5dae8               ; symbol stub for: NSStringFromClass
    0x102c7bf74 <+84>:  mov    x29, x29
    0x102c7bf78 <+88>:  bl     0x102d5def0               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x102c7bf7c <+92>:  mov    x9, #0x0
    0x102c7bf80 <+96>:  ldr    w8, [sp, #0x14]
    0x102c7bf84 <+100>: str    x0, [sp]
    0x102c7bf88 <+104>: mov    x0, x8
    0x102c7bf8c <+108>: ldr    x1, [sp, #0x8]
    0x102c7bf90 <+112>: mov    x2, x9
    0x102c7bf94 <+116>: ldr    x3, [sp]
    0x102c7bf98 <+120>: bl     0x102d5db6c               ; symbol stub for: UIApplicationMain
    0x102c7bf9c <+124>: stur   w0, [x29, #-0x4]
    0x102c7bfa0 <+128>: ldr    x1, [sp]
    0x102c7bfa4 <+132>: mov    x0, x1
    0x102c7bfa8 <+136>: bl     0x102d5dec0               ; symbol stub for: objc_release
    0x102c7bfac <+140>: ldr    x0, [sp, #0x18]
    0x102c7bfb0 <+144>: bl     0x102d5dde8               ; symbol stub for: objc_autoreleasePoolPop
    0x102c7bfb4 <+148>: ldur   w0, [x29, #-0x4]
    0x102c7bfb8 <+152>: ldp    x29, x30, [sp, #0x30]
    0x102c7bfbc <+156>: add    sp, sp, #0x40             ; =0x40 
    0x102c7bfc0 <+160>: ret    

**Flutter Doctor** Command output after deleting the flutter/bin/cache 


Downloading Dart SDK from Flutter engine 5c8147450db52b81232c138b9f9a65a8f9c61862...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49.7M  100 49.7M    0     0   253k      0  0:03:21  0:03:21 --:--:--  664k
Building flutter tool...
Downloading Material fonts...                                2.6s
Downloading package sky_engine...                            1.5s
Downloading common tools...                                  7.3s
Downloading darwin-x64 tools...                             28.9s
Downloading android-arm-profile/darwin-x64 tools...          3.4s
Downloading android-arm-release/darwin-x64 tools...          2.6s
Downloading android-arm64-profile/darwin-x64 tools...        3.6s
Downloading android-arm64-release/darwin-x64 tools...        3.0s
Downloading android-x86 tools...                            17.0s
Downloading android-x64 tools...                            17.8s
Downloading android-arm tools...                             6.3s
Downloading android-arm-profile tools...                     6.5s
Downloading android-arm-release tools...                     4.3s
Downloading android-arm64 tools...                           7.4s
Downloading android-arm64-profile tools...                   6.1s
Downloading android-arm64-release tools...                   4.5s
Downloading android-arm-dynamic-profile tools...             8.9s
Downloading android-arm-dynamic-release tools...             5.8s
Downloading android-arm64-dynamic-profile tools...           7.1s
Downloading android-arm64-dynamic-release tools...           5.6s
Downloading ios tools...                                    40.6s
Downloading ios-profile tools...                            37.1s
Downloading ios-release tools...                            24.4s
Downloading Gradle Wrapper...                                0.5s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.14 18A391, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Android license status unknown.
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.1)

**Comment by zoechi** [comment]
Can you please run in your Flutter install directory
```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
```

**Comment by ninexus-pankaj** [comment]
since suggested , did all , I went into the directory, where flutter is installed its on mac os library folder 

Inside the flutter directory 
**I run command** : git clean -xfd
**Output** : it removed all 

 **run command** :  git stash save --keep-index
**Output** : No local changes to save

**run command :** git stash drop
**Output** : No stash entries found.
**run command** : git pull
**Output**: Already up to date.
**run command:**  flutter doctor
Output : Downloaded files and building flutter tools ....

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.14 18A391, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**After this I went to flutter app project folder**

**Run Command :**  flutter clean
**Run command:**  flutter build iOS
**Output:** xcode build done. 

open the Runner.xcworkspace file in Xcode 10, 

Run it in iPhone 7 iOS 12 : 
 
**Output:** build successful , 
**Runner installed on iPhone successfully** 
While Running Runner on iPhone 7 

**Error in Xcode log : same** 
Runner[711:119293] [VERBOSE-3:dart_vm.cc(403)] Error while initializing the Dart VM: Wrong full snapshot version, expected '8343f188ada07642f47c56e518f1307c' found '46b2bfb57b5647c5f7527ff9aa56c69b'
(lldb)  


@zoechi _** Please let me know if there is anything missed or ignored by me, I appreciate your help and concern, thanks in advance **_

**Comment by zoechi** [comment]
Thanks for checking. I don't know what else to try. I'll leave it for the specialists.

**Comment by zoechi** [comment]
Is there a reason you run it from XCode instead of just `flutter run`?

**Comment by ninexus** [comment]
Deleted flutter SDK folder from previous installed directory , installed flutter sdk in again in different location this time, gives same error, weird flutter, 

 Runner[1146:224406] [VERBOSE-3:dart_vm.cc(403)] Error while initializing the Dart VM: Wrong full snapshot version, expected '8343f188ada07642f47c56e518f1307c' found '46b2bfb57b5647c5f7527ff9aa56c69b'

**Comment by ninexus** [comment]
I found the place where this snapcode is placed Runner.app/Frameworks/App.framework/App and found the Dart VM version 46b2bfb57b5647c5f7527ff9aa56c69b inside the Runner.app/Frameworks/App.framework/App but not sure how it get to be updated to 8343f188ada07642f47c56e518f1307c , any suggestion,

**Comment by ninexus** [comment]
no direct solution found , now installed old backup of project again and build it, **IT WORKS** ,  all the new work done removed.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by Letty-Liang** [comment]
same  problem
```
E/flutter ( 5559): [ERROR:third_party/tonic/dart_library_natives.cc(18)] DartLibraryNatives::Register1IsolateNameServerNatives_LookupPortByName11
E/flutter ( 5559): [ERROR:third_party/tonic/dart_library_natives.cc(18)] DartLibraryNatives::Register1IsolateNameServerNatives_RegisterPortWithName21
E/flutter ( 5559): [ERROR:third_party/tonic/dart_library_natives.cc(18)] DartLibraryNatives::Register1IsolateNameServerNatives_RemovePortNameMapping11
F/flutter ( 5559): [FATAL:flutter/runtime/dart_vm.cc(403)] Error while initializing the Dart VM: Wrong full snapshot version, expected '8343f188ada07642f47c56e518f1307c' found '1d050a3c598cf7fdd388109d771809b3'

```

**Comment by LorenzoBaggio98** [comment]
On Mac follow this : https://github.com/flutter/flutter/issues/16103#issuecomment-476744947 
It worked for me.

**Comment by VickySalunkhe** [comment]
Deleting 

> flutter/bin/cache

folder, then rebuilding the app
worked for me.

**Comment by dened** [comment]
> Deleting
> 
> > flutter/bin/cache
> 
> folder, then rebuilding the app
> worked for me.

Thanks a lot. It worked for me.

**Comment by Mrcooder** [comment]
> Deleting
> 
> > flutter/bin/cache
> 
> folder, then rebuilding the app
> worked for me.

Thanks deeply. It saved me

**Comment by ailosf8n** [comment]
Folks, I can't delete this folder 'cause the dart-sdk is there!
Are you removing ALL content in this folder or only the files?

**Comment by lamkr** [comment]
Folks, I can't delete this folder 'cause the dart-sdk is there!
Are you removing ALL content in this folder or only the files?
