### ISSUE TITLE
Please add support for "MI Push", the most popular message push server like GCM in China

### ISSUE THREAD

**Issue by 276562578** [flutter/flutter#16874]
this is link https://dev.mi.com/console/doc/detail?pId=1252
By some reason of connecting of Google, MI Push is the most popular message push server in China, just like GCM in other place. It will greatly helpful to popularize Flutter in China.
It's very appreciate for Flutter's work!

**Comment by 276562578** [comment]
is it possible for supporting that?

**Comment by zoechi** [comment]
cc @Hixie

**Comment by stuartmorgan** [comment]
Closing as out of scope; this is something that would be best served by a community-owned plugin.
