### ISSUE TITLE
iOS crash during start (Firebase configure)

### ISSUE THREAD

**Issue by enrichman** [flutter/flutter#16871]
It seems that I'm missing some steps but everything should be in place.

I've followed all the offline and online configuration (Info.plist, GoogleService-Info.plist, I have the `pod 'FBSDKLoginKit'` and `pod 'Firebase/Core'` in the Podfile).

But the app still crash badly (on Android it starts).

## Steps to Reproduce

The app is a default app created through `flutter create` and then I've added these dependencies:

```yaml
dependencies:
  flutter:
    sdk: flutter
  google_sign_in: 3.0.2
  firebase_analytics: 0.3.3
  firebase_auth: 0.5.5
  firebase_database: 0.4.5
  firebase_storage: 0.2.5
  flutter_facebook_login: 1.1.1
```

## Logs

```bash
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...                                       1.1s
Starting Xcode build...
 ├─Assembling Flutter resources...                    1.7s
 └─Compiling, linking and signing...                  7.8s
Xcode build done.                                           15.4s
4.13.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106a3c1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001060d1031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106ab1975 +[NSException raise:format:] + 197
	3   Runner                              0x0000000101e3336a +[FIRApp configure] + 352
	4   Runner                              0x0000000101eeef49 -[FLTFirebaseAnalyticsPlugin init] + 185
	5   Runner                              0x0000000101eeee28 +[FLTFirebaseAnalyticsPlugin registerWithRegistrar:] + 168
	6   Runner                              0x0000000101d9723c +[GeneratedPluginRegistrant registerWithRegistry:] + 124
	7   Runner                  <…>
```

## Flutter Doctor

I'm on the `master` channel.

```
[✓] Flutter (Channel master, v0.3.3-pre.12, on Mac OS X 10.13.4 17E199, locale en-IT)
    • Flutter version 0.3.3-pre.12 at /Users/enrico/development/flutter
    • Framework revision fb18ac650e (26 hours ago), 2018-04-21 19:52:46 -0700
    • Engine revision cb3376c5de
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by enrichman** [comment]
It seems that I found how to fix it.

In the end I've removed the `GoogleService-Info.plist` file from the project and readded through XCode (right click on `Runner` and then `Add Files...`).

I'm going to close this. 👍

**Comment by nokia6290** [comment]
@enrichman hey, I got a similar issue with flutter.

Could elaborate more on how you solved the issue?

**Comment by ryanrelf** [comment]
I experience the same issue with the Auth variable. I wanted to access it globally so I created a global variable for it var user = Auth.auth().currentUser - This caused my app to crash.

**Comment by knitterb** [comment]
Per another issue, make sure you are adding `GoogleService-Info.plist` through XCode.  You cannot simply copy this into the `iOS/Runner` directory.

**Comment by SheldonWangRJT** [comment]
I think the document from Google is a little bit misleading on this.
```
Add the Firebase iOS configuration file to your app:

Click Download GoogleService-Info.plist to obtain your Firebase iOS config file (GoogleService-Info.plist).

You can download your Firebase iOS config file again at any time.

Move the file into the Runner/Runner directory of your Flutter app.
```

Moving the file will not help at all. You have to add the file through Xcode so that the project file will be able to recognize the file.

**Comment by awhitford** [comment]
HINT:  `GoogleService-Info.plist` needs to be **added under Runner using XCode**!
(File copy isn’t enough.)  Load the `ios/Runner.xcodeproj` into XCode, then under _Runner_, add the file.  That should do the trick.  (_I wasted over an hour on this one._)

**Comment by mbrookson** [comment]
Flutter docs would definitely benefit from adding this information about adding via Xcode!

**Comment by KraemerJoe** [comment]
Hello, same for me, I added GoogleService-Info.plist trough Xcode..

**Comment by kasp1** [comment]
It would be nice if there would be any log or if the exception threw an error message.

**Comment by KraemerJoe** [comment]
Ok fixed, I copied my project from Windows to Mac OS, I had to create a new fresh project.

**Comment by kasp1** [comment]
@KraemerJoe Would you mind running a diff between the copied project and the newly created one to see what's the difference please? :-)

**Comment by KraemerJoe** [comment]
No difference I think it's a problem with XCode, on windows I tried to modify manualy some infos, without xcode, maybe the origin of all my problems, now all is ok.

**Comment by kasp1** [comment]
Still stuck.

I have found out it is [this exception](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Core/FIRApp.m#L118) that throws. So I suppose the code still can't find the .plist.

I have added the file through XCode:

![Image of Yaktocat](https://i.ibb.co/NrpWwV4/Screenshot-at-Oct-29-16-02-57.png)

What am I missing? :-)

**Comment by theochampion** [comment]
If you're still running into this issue after adding `GoogleService-Info.plist` through Xcode ensure

```swift
FirebaseApp.configure()
```

is place BEFORE

```swift
GeneratedPluginRegistrant.register(with: self)
```

in `AddDelegate.swift`like so

```swift
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

This was causing the crash in my case

**Comment by clk0115** [comment]
In case, someone still can't find the solution, you may check the 'Display Name' in 'General'. 
It should be reminded as 'Runner'.
Only change the iOS app name in 'Info.plist' - 'Bundle Name'.

https://stackoverflow.com/a/58542610

**Comment by hemalmoradiya** [comment]
I solved my problem with below code, i added it in my info.plist file 

<key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLSchemes</key>
            <array>
                
                <string> REVERSED_CLIENT_ID </string>
            </array>
        </dict>
    </array>

**Comment by AmruthPillai** [comment]
I got it working through @enrichman's suggestion. But I'm curious to know, wouldn't this break the CI/CD pipeline? I'm using Codemagic and it's ENV variable setup to load the GoogleService-Info.plist just before build time. How do we ensure it works there as well?

Also, side note: Why does Apple make everything so difficult? 😭

**Comment by Peet-A** [comment]
hello guys , i am still stuck at this issue , i made the above solution , "remove the .plist file and add it again from xcode " but , i got the same error :
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
	3   Runner                              0x000000010d4a2c21 -[FIRPhoneAuthProvider verifyPhoneNumber:UIDelegate:completion:] + 193
	4   Runner                              0x000000010da1191d -[FLTFirebaseAuthPlugin handleMethodCall:result:] + 18109
	5   Flutter                             0x000000010f5f0f95 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	6   Flutter                             0x000000010f584d80 _ZNK7flutter21PlatformMessageRouter21HandlePlat<…>

**Comment by softronaut** [comment]
I already referenced plist file but still getting same error.
```
Configuring the default Firebase app...
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107fd88db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010757bac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107fd8735 +[NSException raise:format:] + 197
	3   Runner                              0x0000000104359a1a +[FIRApp configure] + 138
	4   Runner                              0x000000010445a176 -[FLTFirebaseAnalyticsPlugin init] + 214
	5   Runner                              0x0000000104459fad +[FLTFirebaseAnalyticsPlugin registerWithRegistrar:] + 173
	6   Runner                              0x000000010430c434 +[GeneratedPluginRegistrant registerWithRegistry:] + 212
	7   Runner                  <…>
```

**Comment by rfitz123** [comment]
@AmruthPillai Also wondering something along these lines. I don't have the option to add the .plist through XCode because it is copied in by a script during build. Any ideas?

**Comment by durgendra** [comment]
I was getting same errors. 
Finally the issue I found was using the name of the document  not as per Firestore guideline. Please make sure name of your collection and document names follow these guidelines

https://cloud.google.com/firestore/quotas

Limit | Details
-- | --
Constraints on collection IDs | Must be valid UTF-8 charactersMust be no longer than 1,500 bytesCannot contain a forward slash (/)Cannot solely consist of a single period (.) or double periods (..)Cannot match the regular expression __.*__


Constraints on document IDs | Must be valid UTF-8 charactersMust be no longer than 1,500 bytesCannot contain a forward slash (/)Cannot solely consist of a single period (.) or double periods (..)Cannot match the regular expression __.*__
-- | --
