### ISSUE TITLE
flutter run "Initializing gradle..." ignores http_proxy env vars -> timeout

### ISSUE THREAD

**Issue by melo0187** [flutter/flutter#16875]
## Steps to Reproduce

I'm running flutter on macOS 10.13.3 and struggle to use it properly when being at my work location.
At work I can access the internet only by means of an **NTLM proxy**.
What I am used to do is to set up cntlm to run on localhost:3128 and define this as proxy:
```
~$ echo $http_proxy && echo $https_proxy
http://localhost:3128
http://localhost:3128
cscollo@CMTCL08U014:~$ brew services list
Name  Status  User    Plist
cntlm started cscollo /Users/cscollo/Library/LaunchAgents/homebrew.mxcl.cntlm.plist
~$ curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
~$ 
```
However Flutter does not seem to respect and use the proxy env vars.
I created a simple app in my home network following the official "Write your first Flutter app" guide (https://flutter.io/get-started/codelab/) and it worked fine on the iOS Simulator.

Today at work I am behind the proxy and use cntlm as shown above.

When trying to run the same app on iOS with the cntlm proxy configured, I get the following error:
```
[        ] vm-service: Error: Unhandled exception:
[        ] WebSocketException: Invalid WebSocket upgrade request
```
Full verbose output [here](https://gist.github.com/melo0187/aaf63c8b9344b0da95e016b050c3bccc)

When trying to run the same app on a physical Android device (for the first time) with the cntlm proxy configured, I get the following error:
```
Exception in thread "main" java.net.ConnectException: Operation timed out (Connection timed out)
```
Full verbose output [here](https://gist.github.com/melo0187/d0b517b584f0b59c4bfbe8dd7cd6dfee).

## Flutter Doctor

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D47, locale en-DE)
    • Flutter version 0.2.8 at /Users/cscollo/Development/flutter
    • Framework revision b397406561 (3 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] Connected devices (2 available)
    • Nexus 5X • 01e5a4a6e630bfcc                     • android-arm64 • Android 8.1.0 (API 27)
    • iPhone X • 2F2FAF3E-4E09-4266-BC53-A2358DDB3452 • ios           • iOS 11.3 (simulator)

! Doctor found issues in 2 categories.
```
I guess I'm not the only person sitting behind an NTLM proxy at work and interested in looking into Flutter, so maybe I wouldn't be the only one happy about a solution =)

If I can provide further details, let me know!
Thanks in advance for any feedback!

**Comment by melo0187** [comment]
Short update.

Adding `no_proxy=127.0.0.1` to my .bash_profile helped in solving the issue with the failing WebSocket connection required for the interactive features like Hot Releod.
This makes perfect sense to me and solves the issue.

For the issues with initialising Gradle behind a proxy I had no other choice than adding the proxy settings to the `gradle.properties` file:
```
# when cntlm is not running (or at least not on this port) change/remove these systemProbs
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=3128
systemProp.http.nonProxyHosts=localhost
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=3128
systemProp.https.nonProxyHosts=localhost
```
However I think this is less than ideal. If I now share the project with people not running with the same proxy setup, I created an issue for them.
I wonder if this couldn't be set dynamically when calling Gradle and the http_proxy env var is detected instead: https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy

**Comment by iapicca** [comment]
Hi @melo0187 
are you  still experiencing this issue with the latest version of flutter?
thank you

**Comment by melo0187** [comment]
@iapicca since I'm not actively using flutter anymore, I can't answer that question :man_shrugging:

**Comment by iapicca** [comment]
Hi @melo0187 
thank you for letting me know

**Comment by wenjunxiao** [comment]
You can set `gradle.properties` in the user home directory `~/.gradle/gradle.properties` instead of the project
