### ISSUE TITLE
Android's FlutterView would be black sometimes.It can respond to user click, and could be restored fine by background/foreground switch.

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#16877]
## Steps to Reproduce

I've wrapped a FlutterView(singleton) in a FlutterWrapperActivity(FWA). When FWA1 started FWA2, FluterView is removed from FWA1 and added above FWA2. When FWA2 is poped to FWA1, vice versa.
When I push many FlutterWrapperActivity in a stack, and then pop again and again until the root one.
Sometimes, I found that the FlutterView became black totally. Though it's black, it responds to user click. And it can also restore to normal when I switch to background and foreground again.

Is there anyway for me to detect this kind of error scenario? Is it possible for me to call some method to ensure that the ui-rendering works fine?

Screenshot on  a Huawei Mate9 (Abnormal)
![image](https://user-images.githubusercontent.com/817851/39116604-73ae1468-4717-11e8-93b3-605f47ff371c.png)

Screenshot on a Huawei Mate9 (Normal)
![image](https://user-images.githubusercontent.com/817851/39116650-8f3a2b22-4717-11e8-8bdd-2d5352c55c8a.png)

## Flutter Doctor
[✓] Flutter (Channel beta, v0.1.6-pre.47, on Mac OS X 10.13.4 17E199, locale en-CN)
    • Flutter version 0.1.6-pre.47 at /Users/kylewong/Codes/fwn_idlefish/flutter
    • Framework revision 538c8e12b6 (2 days ago), 2018-04-21 19:47:45 +0800
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK at /Users/kylewong/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • MHA AL00 • GWY7N16B02004245 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

@eseidelGoogle

**Comment by zoechi** [comment]
You are using a quite old Flutter version. There was an issue with `flutter upgrade` with this version.
You could try `git clean -xffd` `git pull` `flutter doctor` in the flutter install dir and see if this properly updates to the most recent `beta` version.

**Comment by kangwang1988** [comment]
@zoechi 
As we're embedding flutter into our already mature and native app. We have to ensure the stability.So in our last version, we used then beta version and fix some bugs when we met. After it's released, we will upgrade it. We will keep up to the latest beta version, but not immediately.

**Comment by zoechi** [comment]
@kangwang1988 I wouldn't expect fixes for old beta versions.

**Comment by kangwang1988** [comment]
@zoechi 
Though it's a old version, the problem are probably still in latest beta branch.

**Comment by zoechi** [comment]
@kangwang1988 are you planning to backport it yourself to the Flutter version you're using?
Just curious.

**Comment by kangwang1988** [comment]
@zoechi 
As we start to develop this version in certain commit (like tag/v0.2.3), before it's released and all serious problems are solved, we would not like to make big changes.

**Comment by kangwang1988** [comment]
We've upgraded our flutter to beta v0.3.1.
I will check if this issue remains.

**Comment by kangwang1988** [comment]
After upgrading flutter to betav0.3.1, I found there's some activity lifecycle related bug in my multiple-activity-while-one-flutterview implementation based on v0.3.1. So i fix it and notice that this issue disappears.

**Comment by kangwang1988** [comment]
This problem still exists in flutter betav0.3.1
@eseidelGoogle

**Comment by kangwang1988** [comment]
This problem due to that implementation that I shared one flutterview among multiple Activies, and I remove and add a FlutterView successively in a method call. After I split the remove and add operation into multiple eventloop(based on flutter beta v0.5.1), this problem disappears. 
So I will close this issue now. 
@zoechi 
@eseidelGoogle
