### ISSUE TITLE
TabController no expected results

### ISSUE THREAD

**Issue by 7449** [flutter/flutter#16885]
[Demo](https://github.com/7449/flutter_example/tree/master/flutter_issues)

As shown in the figure, Tab's page is not according to my expectation. When the drawer's Item is switched, it always shows the index of the previous click.

[https://github.com/7449/flutter_example/blob/master/flutter_issues/flutter-issues.gif](https://github.com/7449/flutter_example/blob/master/flutter_issues/flutter-issues.gif)

![](https://github.com/7449/flutter_example/blob/master/flutter_issues/flutter-issues.gif)

thanks

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by 7449** [comment]
no,commit version:[9c49255f3eeb4873e6398c805b4bb6b9737be962](https://github.com/flutter/flutter/commit/9c49255f3eeb4873e6398c805b4bb6b9737be962)

**Comment by zoechi** [comment]
Thanks a lot for the feedback!
