### ISSUE TITLE
[sentry][web] Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by lejard-h** [flutter/flutter#16884]
not related to flutter but [flutter/sentry](https://github.com/flutter/sentry) does not have is own issue tracker.
---------------------

When using the package on a web application and reporting an error, I am getting this error.

`html_dart2js.dart:22938 Refused to set unsafe header "User-Agent"`.

But I can see the issue on the dashboard.

I just hope it is not causing this https://github.com/flutter/flutter/issues/16883

**Comment by zoechi** [comment]
That is not allowed and prevented by the browser AFAIK

**Comment by lejard-h** [comment]
linked to https://github.com/flutter/flutter/issues/16883
