### ISSUE TITLE
[sentry][web] sourcemap not used

### ISSUE THREAD

**Issue by lejard-h** [flutter/flutter#16883]
not related to flutter but [flutter/sentry](https://github.com/flutter/sentry) does not have is own issue tracker.
--------------------------------------

On a web application in production with minify javascript.
Sentry is correctly reporting issues but does not seem to use the sourcemap to unminify the stacktrace.

Even after following the [doc](https://docs.sentry.io/clients/javascript/sourcemaps/), my file is public but I also try to upload artifact with the correct version.

I don't know if it is related to the package or the sourcemap itself.

Note that the platform is not defined as `javascript` https://docs.sentry.io/clientdev/attributes/

**Comment by zoechi** [comment]
So this is for the use of flutter/sentry in a web project.
I guess a PR is welcome but unlikely to be implemented by the Flutter team.
/cc @yjbanov

**Comment by lejard-h** [comment]
I started a PR 
https://github.com/flutter/sentry/pull/22

**Comment by yjbanov** [comment]
Web support is still TBD for flutter/sentry. @kevmoo, @matanlurey: would you be interested in guiding an effort to add Web support to this package?

Alternatively, there are Sentry client implementations that seem to have been built specifically for web apps:

* https://pub.dartlang.org/packages/sentry_client
* https://pub.dartlang.org/packages/angular_sentry

**Comment by kevmoo** [comment]
I think the effort to support sentry w/ Dart's web offerings would be a completely separate project/repo.

It'd be great if they could share code, though... @yjbanov pointers above look like good places to start

**Comment by lejard-h** [comment]
Still need to move my PR to the new `packages` repo but the sentry report is working in some case.

The only other difference with flutter vs browser are headers User-Agent and the gzip compression of the request which is not possible on bowser.

https://github.com/flutter/sentry/pull/22/files#diff-37a98cdce61f000783eb09e54c8195a6R99
https://github.com/flutter/sentry/pull/22/files#diff-37a98cdce61f000783eb09e54c8195a6R90

I also had to specify the origin for file_path
https://github.com/flutter/sentry/pull/22/files#diff-5e35fb01d572693f3f256bf34d4f7a09R39

I still have problems with the stacktrace on the browser which is not correctly resolved by sentry while the flutter stacktrace is correct (maybe I am missing something).
https://github.com/dart-lang/build/issues/1874
The browser is also generating file path that sentry cannot resolve (ex: org-dartlang-sdk:///sdk/_internall/...)

Note that the updated version (not on pub) of angular_sentry is using this PR 
https://github.com/leftyio/angular_sentry/tree/update

**Comment by MOPineyro** [comment]
@lejard-h any recommended way to deal with sourcemaps on flutter web? Currently facing the same issue with an app in prod.

**Comment by bruno-garcia** [comment]
The current Sentry SDK works with Flutter Web. I did some tests with Flutter Web, basically I [build it like this](https://github.com/getsentry/sentry-flutter/blob/d22e8376648dd9746304646036dbd24bb885e177/example/run.sh#L24-L29).

[And upload sourcemaps like this](https://github.com/getsentry/sentry-flutter/blob/d22e8376648dd9746304646036dbd24bb885e177/example/run.sh#L38-L52). 

It's not ideal yet but you can see the actual dart file name and line number.

We're focusing on better Android and iOS support first in Q4.
But expecting that Flutter Web goes out of the beta channel in Q1 2021, we should be ready to focus on that.

**Comment by MOPineyro** [comment]
@bruno-garcia appreciate the tip, did you have to do anything to modify the source root?

**Comment by bruno-garcia** [comment]
> @bruno-garcia appreciate the tip, did you have to do anything to modify the source root?

Not that I recall. I'm closing this issue since it's possible to use sourcemaps [as pointed out in this comment](https://github.com/flutter/flutter/issues/37875#issuecomment-685858456). But also, [there's a tracking issue for changes on the Sentry side here](https://github.com/getsentry/sentry-dart/issues/417).

No changes are needed in Flutter, so closing this one.
