### ISSUE TITLE
Arabic Quran diacritics problem

### ISSUE THREAD

**Issue by dahabit** [flutter/flutter#16886]
Hello Dartisans, 

There is a problem with Flutter using a custom font "KFGQPC Uthmanic Script HAFS "  with Arabic Text that contains diacritics like Quran 

The text with the same font on ios simulator using Xcode is working perfectly

on the other hand, when using flutter  the same Text  `'يَسۡ‍َٔلُونَ' `with the same font is not displayed correctly 

**this is known issue with Android, I don't know why it appears with flutter although Flutter is using different text engine** 
**Font**
The font that used with these two examples is built specially for that and it has good support for that type of writing 

http://fonts.qurancomplex.gov.sa/?page_id=35
Direct download link
http://fonts.qurancomplex.gov.sa/download/UthmanicHafs1Ver09Font.zip

![flutter_xcode](https://user-images.githubusercontent.com/284535/39149298-eac8a1e0-473e-11e8-8e73-6a54d72638f1.jpg)

the Hex code for the word is
`يَسۡ‍َٔلُونَ (25 bytes): "\u64A\u64E\u633\u6E1\u200D\u654\u64E\u644\u64F\u648\u646\u64E"`

the diacritics moved to the begining off the letter not the end

## Steps to Reproduce & Examples

**Xcode  sample**

![preview](https://user-images.githubusercontent.com/284535/39133389-5b750918-4714-11e8-8cd9-2b5987e0c018.png)

![xcode2](https://user-images.githubusercontent.com/284535/39133401-6323686c-4714-11e8-8029-a223136fcd15.png)

**Source Code**
https://github.com/dahabit/xcode_arabic_test

**Flutter Example**
![flutter](https://user-images.githubusercontent.com/284535/39133437-789de578-4714-11e8-9e46-fb7edc1cc486.png)

![flutter_code](https://user-images.githubusercontent.com/284535/39133468-870f92dc-4714-11e8-85de-e1990d216e44.png)

**Source Code**
https://github.com/dahabit/flutter-arabic-diacritics-test

**Comment by jason-simmons** [comment]
Flutter text rendering on Android does use some of the same libraries (Skia, HarfBuzz, FreeType) that are used by the Android UI framework

**Comment by dahabit** [comment]
@jason-simmons yeah, I heard that, I thought that Android using something else and this mean that issue will be with Flutter and may be the fuchsia os :(

**Comment by dahabit** [comment]
First I would like to thank @slightfoot for his help 

second, this what we get until now

1- the problem how Skia engine deal with Arabic joining and render the letters in a wrong way & apple use another closed source solution for that 
 the problem with `u200D ` if we replace it with `u0640` everything works perfectly 

![screen shot 2018-04-26 at 5 23 34 pm](https://user-images.githubusercontent.com/284535/39315277-9dc7a0b4-4976-11e8-8b7a-a9cbca4a3366.png)


for more info about Arabic joining check here "Arabic Cursive Joining"
https://www.unicode.org/versions/Unicode10.0.0/ch09.pdf

![screen shot 2018-04-26 at 5 02 26 pm](https://user-images.githubusercontent.com/284535/39315337-bfe8be8a-4976-11e8-854e-ab5838cbea6a.png)


I'm now working to collect all words that have the similar problem to find the best solution for that

**Comment by slightfoot** [comment]
These two issues might help/be related:
* #16408 - Should pass the Locale from Localizations to Text/RichText/etc to painting.TextStyle to ui.TextStyle
* #17879 - Pass Text/RichText locale along to RenderParagraph

This issue should be re-retested when the above is merged.

**Comment by zoechi** [comment]
@dahabit is this still an issue.
What @slightfoot linked to seems to be fixed.

**Comment by slightfoot** [comment]
Needs retesting, but I think is a bug in the unicode parsing.

**Comment by dahabit** [comment]
Thanks, @zoechi for your reply and sorry for the late response the issue still not fixed 
I tested it with the latest update on dev channel today 15-9-2018

`[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.6 17G65, locale en-EG)`

![screen shot 2018-08-15 at 3 47 55 pm](https://user-images.githubusercontent.com/284535/44151460-f294c080-a0a2-11e8-9dd8-cb672ee26c38.png)

**Comment by Hixie** [comment]
This is probably an issue in HarfBuzz. cc @behdad

**Comment by behdad** [comment]
Ugh. This is a true hack of a font & text encoding.  But since Uniscribe also produces the Apple result, I'll find a way to match it in HarfBuzz.  cc @khaledhosny

**Comment by behdad** [comment]
Khaled: I *think* what's happening is we are jumping over the joiner and attach hamza somwhere the font doesn't expect...

**Comment by behdad** [comment]
> Khaled: I _think_ what's happening is we are jumping over the joiner and attach hamza somwhere the font doesn't expect...

Whereas the font expects, and other engines do, that the hamza be left there simply because it cannot jump over the ZWJ to find a base to attach to...

**Comment by behdad** [comment]
> Khaled: I _think_ what's happening is we are jumping over the joiner and attach hamza somwhere the font doesn't expect...

Whereas the font expects, and other engines do, that the hamza be left there simply because it cannot jump over the ZWJ to find a base to attach to...

**Comment by behdad** [comment]
cc @jfkthame Any suggestions?

**Comment by khaledhosny** [comment]
I think this is a font bug. The glyph `afii57427.calt` (the س glyph) has two top anchors and the font is expecting ZWJ to prevent the marks after it from attaching to the marks before it so that they attach to the second anchor, i.e. as if ZWJ was CGJ. Indeed if I use CGJ  in the text above (and modify the font so that CGJ triggers the calt lookup that replaces `afii57427.init` with `afii57427.calt`), I get the expected output.

Using `يَسۡ͏َٔلُونَ` (and the modified font):
![out](https://user-images.githubusercontent.com/93914/45823591-4d4e1000-bcee-11e8-8e89-f7f7f09ec346.png)

**Comment by jfkthame** [comment]
So I guess the question is whether we should also block mark attachment across ZWJ, for better compatibility with other engines. Have we seen examples that currently depend on this?

**Comment by slightfoot** [comment]
@khaledhosny I appreciate this might be a font-bug but when this is the official font provided by gov and the same font works fine on other platforms perhaps there is a compromise here. Also I'm pretty sure this is an issue with other Arabic font's as well including Noto... perhaps @dahabit can supply some.

**Comment by slightfoot** [comment]
Attached are the font files I tried whilst trying to figure the bug out.

[fonts.zip](https://github.com/flutter/flutter/files/2401657/fonts.zip)

**Comment by khaledhosny** [comment]
IMO, the font should have used CGJ all along, what it wants here is precisely what this character is for. But it is not my call, up to @behdad to see if there is a reasonable way to handle this without breaking the special treatment of ZWJ that the other engines are known not to implement.

**Comment by khaledhosny** [comment]
I do sympathies with the font author(s), though. The deeper issue here is that Unicode makes encoding many of the feature of Quranic orthography in a clean way hard to impossible. Been there, done that.

**Comment by dahabit** [comment]
Hello All :)
Thanks for checking that issue again, I can provide a lot of samples for the same problem with other letters 

Thanks, @khaledhosny @behdad @slightfoot @Hixie   again for helping us with this issue :)

**Comment by behdad** [comment]
> I think this is a font bug. The glyph `afii57427.calt` (the س glyph) has two top anchors and the font is expecting ZWJ to prevent the marks after it from attaching to the marks before it so that they attach to the second anchor,

There is no second anchor.  Font expects the second mark to NOT attach to anything.  Its natural position is where the expected rendering shows.

**Comment by khaledhosny** [comment]
I see two top anchors in FontForge, but indeed the hamza glyph does not have an anchor corresponding to the second one, so no attachment would happen.

**Comment by behdad** [comment]
I'm out of ideas here.  I don't want to completely disable the ZWJ skipping logic, obviously.  Possibly just disallow it between marks and bases, ie. when looking back to attach mark/mkmk features, don't skip anything.  I'm fine with that.

**Comment by behdad** [comment]
I finally have a patch for this, but it breaks some of our tests.  I'll figure it out with Jonathan next week.

**Comment by behdad** [comment]
This is fixed in HarfBuzz master now.  I'll make a release later this week.

**Comment by slightfoot** [comment]
Thanks so much for your time on this @behdad. I can see a big uptake in the arabic world because of this change. A lot of app previously have relied on images to render text which make them very large in a size compared to their iOS counterparts. Not to mention the quality of text itself. This will make a huge difference. I'm sure @dahabit will confirm.

**Comment by slightfoot** [comment]
I just tried with master [Flutter 0.10.1-pre.27] and I don't see it in there yet.

**Comment by jfkthame** [comment]
With what version of harfbuzz?

**Comment by behdad** [comment]
I haven't made a HarfBuzz release yet, so, no surprise.  Will do next week.

**Comment by slightfoot** [comment]
Looks like it is resolved in version `0.10.3-pre.1` I saw that the [changelog](https://github.com/flutter/flutter/wiki/Changelog) notied `harfbuzz 2.1.0` is now included. It doesn't mention Arabic text now displays correctly. So it might be worth updating the changelog to represent this. Attached is screenshot from Emulator.

It's worth mentioning that it currently only works with the Noto font. If I use the other font it fails. So I see this as a font issue.

<img width="540" alt="screenshot-2018-11-15_12 30 04 847" src="https://user-images.githubusercontent.com/906564/48555559-7bf4fb00-e8d9-11e8-8941-220b4f748756.png">

**Comment by dahabit** [comment]
Hello, Thanks @behdad @khaledhosny and @slightfoot  for your contribution and efforts, I test it now with 0.11.7-pre.35 build, and the issue resolved 

![image](https://user-images.githubusercontent.com/284535/48744487-20779400-ec70-11e8-85f2-f5487e6d0d47.png)

**Comment by alfianakbar** [comment]
Hi,
I want to re-open this issue, I have a problem while displaying arabic number with arabic brackets. There is the code:
```
String translateNumber(int number) {
    String result = "";
    List<String> angkaArab = ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"];
    int tempNum = number;

    if (tempNum >= 100) {
      result += angkaArab[(tempNum / 100).floor()];
      tempNum %= 100;
    }
    if (tempNum >= 10) {
      result += angkaArab[(tempNum / 10).floor()];
      tempNum %= 10;
    }

    result += angkaArab[tempNum];
    result = "﴿$result﴾"; // i use arabic bracket, not ordinary bracket
    return result;
  }
RichText(
      textAlign: TextAlign.right,
      text: new TextSpan(
        children: <TextSpan>[
          new TextSpan(
              text: "﻿بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ"),
          new TextSpan(
              text: translateNumber(1)),
        ],
      ),
    );
  }
```
![image](https://user-images.githubusercontent.com/989885/54254127-f0912b00-4595-11e9-8231-bc66e2f1ebb1.png)

Thanks,

**Comment by jfkthame** [comment]
> I have a problem while displaying arabic number with arabic brackets.

This looks unrelated to the original problem discussed here. I think your issue is that you're not ensuring the overall text (the top-level TextSpan within your RichText) has right-to-left base directionality.

**Comment by dahabit** [comment]
@khaledhosny I think this is the problem that you told me about the font before, which doesn't display aya no correctly? any suggestion?

**Comment by khaledhosny** [comment]
I don’t think it is the same issue. Like @jfkthame said, the text direction need to be set right-to-left.

**Comment by Mr-Umar** [comment]
![image](https://user-images.githubusercontent.com/56406786/112293856-69aed700-8cb4-11eb-9902-e4c4c449e3cf.png)
"مَٰلِكِ يَوْمِ ٱلدِّينِ" 
again this issues exist

**Comment by behdad** [comment]
> "مَٰلِكِ يَوْمِ ٱلدِّينِ"
> again this issues exist

File a new issue.
