### ISSUE TITLE
Flutter crashes when installed in read-only folder

### ISSUE THREAD

**Issue by flip-D** [flutter/flutter#16898]
On create new flutter project, Android Studio or IntelliJ, keeping defaults except project name, flutter crashes and creates log:

> Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/opt/flutter/bin/cache/lockfile' (OS Error: Permission denied, errno = 13)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:351)
#1      _rootRunUnary (dart:async/zone.dart:1134)
#2      _CustomZone.runUnary (dart:async/zone.dart:1031)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#5      Future._propagateToListeners (dart:async/future_impl.dart:666)
#6      Future._completeWithValue (dart:async/future_impl.dart:481)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:511)
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## flutter doctor

```
[✓] Flutter (Channel dev, v0.3.0, on Linux, locale en_GB.utf8)
    • Flutter version 0.3.0 at /opt/flutter
    • Framework revision c73b8a7cf6 (11 days ago), 2018-04-12 16:17:26 -0700
    • Engine revision 8a6e64a8ef
    • Dart version 2.0.0-dev.47.0.flutter-4126459025

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/phild/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/phild/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.1)
    • Android Studio at /home/phild/android-studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /usr/share/intellijidea-ce
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] Connected devices (1 available)
    • Nexus 6 • ZX1G522RKP • android-arm • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.
```
Trying to run flutter doctor again produces:

> flutter doctor

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 75a5b0127a9c7e7d)
Crash report written to /home/phild/flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.

Previous flutter projects open and run

**Comment by mravn-google** [comment]
You probably don't want to install Flutter in `/opt`, because then you'd require write permissions to that folder, something which on many systems is a `root` privilege. Better to select a subfolder under your home (e.g. `/home/phild/flutter`)

**Comment by filleduchaos** [comment]
I suppose a check for filesystem permissions/warning from `flutter doctor` would be nice?

Or catching and printing a clearer message for `EACCES` errors and exiting instead of crashing

**Comment by flip-D** [comment]
Thank you. Very new to Linux, clean install of Manjaro, installed Flutter via package manager (AUR), installs to /opt by default. Worked for two days creating, opening and running projects before crashing.

**Comment by zoechi** [comment]
Looks like a dup of #11698

**Comment by kapiljhajhria** [comment]
same issue on manjaro i tried setting it up under documents folder but then android studio can't detect flutter sdk and also can't set it as path. this was not an issue on ubuntu. on manjaro i have wasted whole day trying to find a fix for this.

**Comment by oliver-gomes** [comment]
@diablodale what was the solution? I am facing the same issue, running as admin does not work

**Comment by kapiljhajhria** [comment]
> @diablodale what was the solution? I am facing the same issue, running as admin does not work

For me issue was missing app for rar. I had to install program for opening rar files. Or it was zip files. I forgot exact extension but it was compressed files that failed to unzip. So installed one program for it and it worked after that.

**Comment by diablodale** [comment]
@kapiljhajhria , I can't remember if I resolved it. And I am not currently working with flutter to share my current experience.
