### ISSUE TITLE
SegmentControl in CupertinoSliverNavigationBar with largeTitle

### ISSUE THREAD

**Issue by The-Redhat** [flutter/flutter#16897]
It would be pretty nice if you can integrate a Segment Control in the new CupertinoSliverNavigationBar with large Title, like in this example: 
![1 ojkhwqt9auwulaxg9vvkog 2](https://user-images.githubusercontent.com/33162310/39151479-a18bf6c4-4745-11e8-88c6-c222abaa0de4.png)
If there's already a solution to this then i'm sorry, but i couldn't find one.
Thanks

**Comment by xster** [comment]
Oh, there's a bug for it already actually #10469
