### ISSUE TITLE
'flutter ios' doesn't seem to do anything (as seen from help on Linux)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1689]
We expose the "ios" command on Linux, but when you say `flutter help ios` it just says:

```
Commands for creating and updating Flutter iOS projects.

Usage: flutter ios [arguments]
-h, --help         Print this usage information.
    --[no-]init    Initialize the Xcode project for building the iOS application

Run "flutter help" to see global options.
```

...which doesn't really explain what it's for. Also, if you try to run `flutter ios` it says it only works on Mac, but the help above doesn't mention this.

**Comment by devoncarew** [comment]
It would be nice if we could just create the ios/ and android projects as part of the `create` command (https://github.com/flutter/flutter/issues/1681); this command would then just go away.

**Comment by devoncarew** [comment]
It's gone -
