### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by sdahlbac** [flutter/flutter#16893]
## Steps to Reproduce

Trying to install flutter for the first time. 

- Downloaded https://storage.googleapis.com/flutter_infra/releases/beta/macos/flutter_macos_v0.2.8-beta.zip
- unzipped
- fixed PATH
- `flutter doctor`

got greeted with 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-FI)

Oops; flutter has exited unexpectedly.
Error executing simctl: -6
dyld: Symbol not found: _SimDeviceBootKeyDisabledJobs
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
  Expected in: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
 in /Applications/Xcode.app/Contents/Developer/usr/bin/simctl

Crash report written to /Users/sdahlbacka/git/flutter_01.log;
```

suspected issues with xcode, so started that and it wanted to install extra components

tried `flutter doctor` again:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-FI)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: c6fffac939733321)
Crash report written to /Users/sdahlbacka/git/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

and 

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-FI)
    • Flutter version 0.2.8 at /Users/sdahlbacka/git/flutter
    • Framework revision b397406561 (3 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357


Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 93eb2896c6925a6a)
Crash report written to /Users/sdahlbacka/git/flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
```

and

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-FI)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 5f11ec524a657c4c)
Crash report written to /Users/sdahlbacka/git/flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
```

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by filleduchaos** [comment]
Could you post the first twenty or so lines of the log(s) as well?

**Comment by sdahlbac** [comment]
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/sdahlbacka/Library/Android/sdk/tools/bin/sdkmanager.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      runCommand (package:flutter_tools/src/base/process.dart:115)
#3      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:188)
<asynchronous suspension>
#4      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:149)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
```
(The ssue got resolved by upgrading android studio et al.)

Nevertheless, if the prescribed installation instructions is run `flutter doctor` then that should not crash no matter what.

**Comment by mit-mit** [comment]
cc @jcollins-g

**Comment by zoechi** [comment]
Looks like a dup of #16271
