### ISSUE TITLE
When there's a failure on startup, we should display a description of the failure on the device

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#169]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Sep 22, 2015 at 23:53 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1295_

---

Right now we just crash (see #1243). On Android this manifests as "Unfortunately, Sky Shell has stopped." We should probably have a dialog that says "This Flutter application has failed to start. The first error found was: ..." with a way to copy that text to the clipboard or something.

**Comment by Hixie** [comment]
We don't believe this is either critical or actionable.
