### ISSUE TITLE
Error upgrade version

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#16911]
I/Process ( 5819): Sending signal. PID: 5819 SIG: 9

**Comment by tvolkert** [comment]
@giovannilima262 we need more info in order to know the context for your error report.  Such as:

* What command did you issue?
* Can you attach a `flutter doctor --verbose` output
* What output do you see if you run with `--verbose`?
* Is it 100% reproducible, or did  you just see it once?

**Comment by giovannilima262** [comment]
Actually wanted to know how to update the flutter project without knowing how to create a new one

**Comment by giovannilima262** [comment]
to create a project with update and pass the files to it, 
this error appears when you include the apply plugin: 'com.google.gms.google-services' at the build.gradle

**Comment by zoechi** [comment]
Sorry for the late response.

> update the flutter project

What do you mean by that?  

> create a project with update and pass the files to it,

what files to pass, and for what purpose?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
