### ISSUE TITLE
On some devices it stays this way

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#16915]
![whatsapp image 2018-04-23 at 22 08 10](https://user-images.githubusercontent.com/22526617/39160666-f23fd11a-4742-11e8-8601-ecf8c00c95db.jpeg)
![whatsapp image 2018-04-23 at 22 07 51](https://user-images.githubusercontent.com/22526617/39160667-f261fd26-4742-11e8-9603-6685ace411d8.jpeg)

**Comment by giovannilima262** [comment]
It's normal in my cell phone, but in another it stays that way

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.
What is the expected behavior?

**Comment by giovannilima262** [comment]
![whatsapp image 2018-04-24 at 18 29 27 1](https://user-images.githubusercontent.com/22526617/39215216-77b0e082-47ed-11e8-8f69-bdffc9cf8f34.jpeg)
![whatsapp image 2018-04-24 at 18 29 27](https://user-images.githubusercontent.com/22526617/39215217-78ed53cc-47ed-11e8-8082-c4f362c6660f.jpeg)

**Comment by giovannilima262** [comment]
in my cell phone showing right

**Comment by giovannilima262** [comment]
[✓] Flutter (Channel beta, v0.1.5, on Linux, locale pt_BR.UTF-8)
    • Flutter version 0.1.5 at /home/giovanni/flutter
    • Framework revision 3ea4d06340 (9 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/giovanni/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.2

**Comment by zoechi** [comment]
That's quite an old Flutter version

**Comment by zoechi** [comment]
try `git clean -xffd` `git pull` `flutter doctor` inside the `flutter` installation directory

**Comment by giovannilima262** [comment]
appeared a series of problems

**Comment by giovannilima262** [comment]
Mensages

Git: Your local changes to the following files would be overwritten by checkout:

**Comment by giovannilima262** [comment]
$ flutter upgrade
Upgrading Flutter from /home/giovanni/flutter...
From https://github.com/flutter/flutter
 + 2a51829c7...bfc329370 Hixie-patch-2 -> origin/Hixie-patch-2  (forced update)
   a742b11a5..7ffcd3d22  dev           -> origin/dev
   c816cee20..e06f69e1c  master        -> origin/master
 * [new tag]             v0.3.4        -> v0.3.4
 * [new tag]             v0.3.5        -> v0.3.5
error: Your local changes to the following files would be overwritten by merge:
	dev/automated_tests/pubspec.yaml
	dev/benchmarks/complex_layout/pubspec.yaml
	dev/benchmarks/microbenchmarks/pubspec.yaml
	dev/bots/pubspec.yaml
	dev/devicelab/pubspec.yaml
	dev/integration_tests/channels/pubspec.yaml
	dev/integration_tests/external_ui/pubspec.yaml
	dev/integration_tests/flavors/pubspec.yaml
	dev/integration_tests/platform_interaction/pubspec.yaml
	dev/integration_tests/ui/pubspec.yaml
	dev/manual_tests/pubspec.yaml
	dev/tools/pubspec.yaml
	dev/tools/vitool/pubspec.yaml
	examples/catalog/pubspec.yaml
	examples/flutter_gallery/pubspec.yaml
	examples/flutter_view/pubspec.yaml
	examples/hello_world/pubspec.yaml
	examples/layers/pubspec.yaml
	examples/platform_channel/pubspec.yaml
	examples/platform_channel_swift/pubspec.yaml
	examples/platform_view/pubspec.yaml
	examples/stocks/pubspec.yaml
	packages/flutter/pubspec.yaml
	packages/flutter_driver/pubspec.yaml
	packages/flutter_localizations/pubspec.yaml
	packages/flutter_test/pubspec.yaml
	packages/flutter_tools/pubspec.yaml
Please commit your changes or stash them before you merge.
Aborting
Updating 3ea4d0634..12bbaba9a

**Comment by giovannilima262** [comment]
localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', 'US')
      ],

Include this in MaterialApp
