### ISSUE TITLE
Deprecate __FlutterEngineFlushPendingTasksNow and allow embedder to create their own threads and message loops.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#16912]
`__FlutterEngineFlushPendingTasksNow` was added as a workaround for embedders to flush tasks on threads where the engine didn't own the message loop (or couldn't interact with the same as is the case on Android and Darwin). This API is hard to use and was a temporary hack. Remove the same and allow embedders to specify thread up front. This API has landed on the C++ side via the TaskRunner configuration passed to the [Shell::Create](https://github.com/flutter/engine/blob/ec611470b571c35156723a163fdcacd1f58b1809/shell/common/shell.h#L45) call. This has to be wrapped up in the stable C API and exposed to custom embedders.

**Comment by chinmaygarde** [comment]
XRef: [b/77652157](http://b/77652157)

**Comment by stuartmorgan** [comment]
@chinmaygarde is there anything left to do here other than mark the API as deprecated? The recent platform message loop API that was added is what's needed to move off of `__FlutterEngineFlushPendingTasksNow`, right?

**Comment by chinmaygarde** [comment]
Yes. Embedders should have everything they need to move off of this API.

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/8273
