### ISSUE TITLE
how to switch to the correct one?

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#16913]
Configuration 'compile' in project ':firebase_auth' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_database' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_storage' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':google_sign_in' is deprecated. Use 'implementation' instead.

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue?
Can you please provide more information about how to reproduce?

**Comment by giovannilima262** [comment]
no

**Comment by zoechi** [comment]
Bot acted weird - closing again.
