### ISSUE TITLE
Log to start

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#16914]
Note: /home/giovanni/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.2.0/android/src/main/java/io/flutter/firebaseauth/FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by zoechi** [comment]
please add the output of `flutter doctor -v`

**Comment by giovannilima262** [comment]
[✓] Flutter (Channel beta, v0.1.5, on Linux, locale pt_BR.UTF-8)
    • Flutter version 0.1.5 at /home/giovanni/flutter
    • Framework revision 3ea4d06340 (9 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/giovanni/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.2

**Comment by amlbar** [comment]
I agree @ryepassport . My android app will stop running when I use Firebase Auth.

**Comment by sbadisa** [comment]
Did anyone find a solution to this?

**Comment by zoechi** [comment]
This issue is closed since quite some time. 
Please create a new issue instead.
