### ISSUE TITLE
firebase_auth package missing "Send Verification Email" method

### ISSUE THREAD

**Issue by harrisonturton** [flutter/flutter#16928]
Hello,

The [firebase_auth](https://pub.dartlang.org/packages/firebase_auth) package is missing the ability to  send [verification emails.](https://firebase.googleblog.com/2017/02/email-verification-in-firebase-auth.html)

This is pretty essential for client's that require email. Is there a workaround, or function that I missed?

Cheers.

**Comment by zoechi** [comment]
Looks like a dup of #12459
