### ISSUE TITLE
We should autodetect the android SDK location if 'adb' is in the path

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1692]
Our installation instructions just say to put 'adb' in the path. They don't mention setting $ANDROID_HOME. However, `device_android.dart` looks for ANDROID_HOME.

We should instead try to find the paths automatically by checking where 'adb' is based, and if that fails, only then trying for an $ANDROID_HOME magic variable, and only if all that fails should we even mention that variable (maybe by saying "'adb' is not on your path. Please make sure you followed the installation instructions at https://flutter.io/getting-started/. If you wish to use a specific installation of your SDK you can set the ANDROID_HOME environment variable." or some such).

**Comment by eseidelGoogle** [comment]
I'm not sure that adb always leads to an `ANDROID_HOME`.  For example for me I have adb at `/usr/local/bin/adb` via homebrew, but my android sdk is at `~/Library/Android/sdk` via Android Studio or in my engine checkout.

**Comment by jimbeveridge** [comment]
I can confirm that looking for adb has issues. I fixed that bug in early Sky tools.

**Comment by qchong** [comment]
Running into this issue when trying to do 'flutter start' (F5) from Atom on my Ubuntu machine. 
Atom console returns "Unable to find adb. Is "adb" in your path? Unable to run application - no connected device." However, typing 'adb devices' on my terminal works.

**Comment by abarth** [comment]
I believe @devoncarew just landed a patch that does this.

**Comment by devoncarew** [comment]
Yup, we try and do some path detection now (and validate that what we find does actually point to an android sdk). We have more work to do re: messaging when things aren't installed, which will probably happen as part of work for a `doctor` command.

The atom launching issue on Ubuntu is tracked here: https://github.com/flutter/atom-flutter/issues/43. I think we can close this out.
