### ISSUE TITLE
include of non-modular header inside framework module

### ISSUE THREAD

**Issue by keluokeda** [flutter/flutter#16922]
### Creating a plugin using 'flutter create -i swift' produce this error

Launching lib/main.dart on iPhone X in debug mode...
Skipping compilation. Fingerprint match.
Running Xcode clean...                                       0.9s
Starting Xcode build...                                          
Xcode build done.                                            1.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET test01 OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/test01-umbrella.h"
            ^
    /Users/yuyanhui/Desktop/flutter_project/test01/example/ios/Pods/Target Support Files/test01/test01-umbrella.h:13:9: error: include of non-modular header inside framework module 'test01': '/Users/yuyanhui/Desktop/flutter_project/test01/ios/Classes/Test01Plugin.h'
    #import "Test01Plugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'test01'
Could not build the application for the simulator.
Error launching application on iPhone X.

## Flutter Doctor

[✓] Flutter (Channel master, v0.3.4-pre.17, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.3.4-pre.17 at /Users/yuyanhui/Desktop/flutter/flutter
    • Framework revision c7ee37a0d8 (3 hours ago), 2018-04-23 21:26:51 -0700
    • Engine revision ec611470b5
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/yuyanhui/Library/Android/sdk
    • Android NDK at /Users/yuyanhui/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2016.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

**Comment by krsolutions** [comment]
Same Here
Launching lib/main.dart on iPhone XR in debug mode...
Warning: CocoaPods recommended version 1.5.0 or greater not installed.
Pods handling may fail on some projects involving plugins.
To upgrade:
  brew upgrade cocoapods
  pod setup

Starting Xcode build...
Xcode build done.                                           49.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
Could not build the application for the simulator.
Error launching application on iPhone XR.
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_inappbrowser-umbrella.h"
            ^
    /FlutterProjects/leader/ios/Pods/Target Support Files/flutter_inappbrowser/flutter_inappbrowser-umbrella.h:13:9: error: include of non-modular header inside framework module 'flutter_inappbrowser': '/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappbrowser-0.5.51/ios/Classes/InAppBrowserFlutterPlugin.h'
    #import "InAppBrowserFlutterPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_inappbrowser'
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-2.1.5/ios/Classes/FluttertoastPlugin.m:16:23: warning: unused variable 'viewController' [-Wunused-variable]
        UIViewController *viewController =
                          ^
    1 warning generated.
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-3.2.4/ios/Classes/GoogleSignInPlugin.m:137:41: warning: 'UIApplicationOpenURLOptionsSourceApplicationKey' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      NSString *sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /FlutterProjects/leader/ios/Pods/Target Support Files/google_sign_in/google_sign_in-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:538:51: note: 'UIApplicationOpenURLOptionsSourceApplicationKey' has been explicitly marked partial here
    UIKIT_EXTERN UIApplicationOpenURLOptionsKey const UIApplicationOpenURLOptionsSourceApplicationKey NS_AVAILABLE_IOS(9_0);   // value is an NSString containing the bundle ID of the originating application
                                                      ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-3.2.4/ios/Classes/GoogleSignInPlugin.m:137:41: note: enclose 'UIApplicationOpenURLOptionsSourceApplicationKey' in an @available check to silence this warning
      NSString *sourceApplication = options[UIApplicationOpenURLOptionsSourceApplicationKey];
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-3.2.4/ios/Classes/GoogleSignInPlugin.m:138:27: warning: 'UIApplicationOpenURLOptionsAnnotationKey' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      id annotation = options[UIApplicationOpenURLOptionsAnnotationKey];
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /FlutterProjects/leader/ios/Pods/Target Support Files/google_sign_in/google_sign_in-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:539:51: note: 'UIApplicationOpenURLOptionsAnnotationKey' has been explicitly marked partial here
    UIKIT_EXTERN UIApplicationOpenURLOptionsKey const UIApplicationOpenURLOptionsAnnotationKey NS_AVAILABLE_IOS(9_0);   // value is a property-list typed object corresponding to what the originating application passed in UIDocumentInteractionController's annotation property
                                                      ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-3.2.4/ios/Classes/GoogleSignInPlugin.m:138:27: note: enclose 'UIApplicationOpenURLOptionsAnnotationKey' in an @available check to silence this warning
      id annotation = options[UIApplicationOpenURLOptionsAnnotationKey];
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:10:19: warning: 'SFSafariViewController' is only available on iOS 9.0 or newer [-Wunguarded-availability]
    @property(strong) SFSafariViewController *safari;
                      ^
    In module 'SafariServices' imported from /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:5:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/SafariServices.framework/Headers/SFSafariViewController.h:27:12: note: 'SFSafariViewController' has been explicitly marked partial here
    @interface SFSafariViewController : UIViewController
               ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:9:12: note: annotate 'FLTUrlLaunchSession' with an availability attribute to silence this warning
    @interface FLTUrlLaunchSession : NSObject <SFSafariViewControllerDelegate>
               ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:29:31: warning: 'SFSafariViewController' is only available on iOS 9.0 or newer [-Wunguarded-availability]
    - (void)safariViewController:(SFSafariViewController *)controller
                                  ^
    In module 'SafariServices' imported from /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:5:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/SafariServices.framework/Headers/SFSafariViewController.h:27:12: note: 'SFSafariViewController' has been explicitly marked partial here
    @interface SFSafariViewController : UIViewController
               ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:29:1: note: annotate 'safariViewController:didCompleteInitialLoad:' with an availability attribute to silence this warning
    - (void)safariViewController:(SFSafariViewController *)controller
    ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:41:40: warning: 'SFSafariViewController' is only available on iOS 9.0 or newer [-Wunguarded-availability]
    - (void)safariViewControllerDidFinish:(SFSafariViewController *)controller {
                                           ^
    In module 'SafariServices' imported from /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:5:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/SafariServices.framework/Headers/SFSafariViewController.h:27:12: note: 'SFSafariViewController' has been explicitly marked partial here
    @interface SFSafariViewController : UIViewController
               ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:41:1: note: annotate 'safariViewControllerDidFinish:' with an availability attribute to silence this warning
    - (void)safariViewControllerDidFinish:(SFSafariViewController *)controller {
    ^
                                                                                API_AVAILABLE(ios(9.0))
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:23:17: warning: 'SFSafariViewController' is only available on iOS 9.0 or newer [-Wunguarded-availability]
        _safari = [[SFSafariViewController alloc] initWithURL:url];
                    ^~~~~~~~~~~~~~~~~~~~~~
    In module 'SafariServices' imported from /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:5:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/SafariServices.framework/Headers/SFSafariViewController.h:27:12: note: 'SFSafariViewController' has been explicitly marked partial here
    @interface SFSafariViewController : UIViewController
               ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:23:17: note: enclose 'SFSafariViewController' in an @available check to silence this warning
        _safari = [[SFSafariViewController alloc] initWithURL:url];
                    ^~~~~~~~~~~~~~~~~~~~~~
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:103:18: warning: 'openURL:options:completionHandler:' is only available on iOS 10.0 or newer [-Wunguarded-availability]
        [application openURL:url
                     ^~~~~~~~~~~
    In module 'UIKit' imported from /FlutterProjects/leader/ios/Pods/Target Support Files/url_launcher/url_launcher-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:135:1: note: 'openURL:options:completionHandler:' has been explicitly marked partial here
    - (void)openURL:(NSURL*)url options:(NSDictionary<UIApplicationOpenExternalURLOptionsKey, id> *)options completionHandler:(void (^ __nullable)(BOOL success))completion NS_AVAILABLE_IOS(10_0) NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.2/ios/Classes/UrlLauncherPlugin.m:103:18: note: enclose 'openURL:options:completionHandler:' in an @available check to silence this warning
        [application openURL:url
                     ^~~~~~~~~~~
    5 warnings generated.
    /FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.1.0+1/ios/Classes/FlutterWebView.m:53:34: warning: comparison of distinct pointer types ('NSString *' and 'NSNull * _Nonnull') [-Wcompare-distinct-pointer-types]
        if (initialUrl && initialUrl != [NSNull null]) {
                          ~~~~~~~~~~ ^  ~~~~~~~~~~~~~
    1 warning generated.

**Comment by krsolutions** [comment]
Please help

**Comment by zoechi** [comment]
@krsolutions you could try https://github.com/flutter/flutter/issues/21973#issuecomment-424290794

**Comment by zoechi** [comment]
@krsolutions see also https://github.com/flutter/flutter/issues/21096

**Comment by krsolutions** [comment]
Getting below error with proposed solution.

    -> Using webview_flutter (0.0.1)
      - Running pre install hooks
    [!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: flutter_inappbrowser

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:116:in `block (2 levels) in verify_framework_usage'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:111:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:111:in `block in verify_framework_usage'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:108:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:108:in `verify_framework_usage'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:406:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:118:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳
    Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone XR.
