### ISSUE TITLE
Problem with installing 

### ISSUE THREAD

**Issue by shariarrazm** [flutter/flutter#16929]
I installed flutter and changed path but when i run flutter doctor i get this error

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-SE)
 
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: a4b30801c016fca1)
Crash report written to /Users/ShariarRazm1/flutter_06.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by shariarrazm** [comment]
this is what i have

**Comment by mit-mit** [comment]
OK, I'm afraid this bug is not actionable then. If you hit this again, please take a look in the log file.

**Comment by shariarrazm** [comment]
how to do this?

**Comment by mit-mit** [comment]
Open the `.log` file (e.g. `/Users/ShariarRazm1/flutter_06.log` in the original report you had) in your favorite text editor, and browse through it's contents to see if there is something relevant.

**Comment by mit-mit** [comment]
Also, can you include the output of `flutter doctor` ?

**Comment by shariarrazm** [comment]
this is what happens when i run flutter doctor
