### ISSUE TITLE
Some Unicode Characters are not supported by the Text Widget

### ISSUE THREAD

**Issue by wilburt** [flutter/flutter#16925]
Some Unicode characters like the naira (₦) sign are not being rendered by the Text widget. I think it is a Text Widget problem because I can see the sign in the console if I `print` it. 
## Steps to Reproduce
 `new Text('\u{20A6}')`
 `new Text(₦)`
Either of those displays a question mark while other characters like `\u{25cf}` displays normally. Actually, I have tested five other characters and they work except for the naira sign.
## Logs
```
04-24 11:59:33.505 512-590/ng.app.blah I/flutter: ₦2,526.72
04-24 11:59:33.507 512-590/ng.app.blah I/flutter: ₦87,167.20

```

**Comment by jason-simmons** [comment]
What device and OS version are you using?

I was able to render this character with the latest Flutter engine on a Nexus 5X (Android 8.1.0) and Moto G4 (Android 7.0).  Flutter and Skia will search the available fonts on the device to find one containing a given character, but possibly something is going wrong with the font selection process.

**Comment by wilburt** [comment]
My bad---I was using AvenirNext. The sign shows on the default font of the device.

**Comment by alann-maulana** [comment]
Sorry for reopening this issue, because I found some unicode characters cannot rendered in `Text` widget.

## Steps to Reproduce
```dart
Text('﻿Bismi Alla̲hi a𝐥rrah̲ma̲ni a𝐥rrah̲eem𝐢')
```
The widget failed to render `\u{1d425}` and `\u{1d422}` character. I'm already trying to use some assets font and still having the same.

## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.6 17G65, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.26.0)
[✓] Connected devices (2 available)

• No issues found!
```

## Screenshoot
![Unicode not rendered](https://preview.ibb.co/iR7vQz/Screenshot_1534477961.png)

**Comment by wilburt** [comment]
Does the characters render outside of flutter, say in the default Messages app? I googled the characters on Chrome mobile browser and I all saw are tofu characters.

**Comment by alann-maulana** [comment]
@wilburt yes, you're right. Default Messages app can't render it too. See :
![Unicode not rendered in messages app](https://preview.ibb.co/nyk2oK/Screenshot_1534486032.png)

I have test it on iOS simulator/devices and rendered perfectly. But not running well on Android. So what we can do now?

**Comment by wilburt** [comment]
Try using a font that supports the characters in question.

**Comment by alann-maulana** [comment]
@wilburt very well. Thanks for your suggestion

**Comment by francis94c** [comment]
May i suggest using a RichTextBox with TextSpan widgets. Use a TextSpan with the system's default font or a font that supports the missing character, then use a different TextSpan with your preferred font that renders other characters properly together...
