### ISSUE TITLE
Stepper Icons are too big

### ISSUE THREAD

**Issue by MarcinusX** [flutter/flutter#16920]
## Problem

`Stepper` Icons have no space between Icon itself and the circle.
In my opinion, it looks disturbing, especially for edit icon.
<img src="https://user-images.githubusercontent.com/16286046/39167311-d2d2c642-478e-11e8-8366-c91cefed5872.png" alt="Drawing" height="600" />

## Solution

Changing this
```
case StepState.editing:
    return new Icon(
        Icons.edit,
        color: isDarkActive ? _kCircleActiveDark : _kCircleActiveLight,
    );
case StepState.complete:
    return new Icon(
        Icons.check,
        color: isDarkActive ? _kCircleActiveDark : _kCircleActiveLight,
    );
```
Into this:
```
case StepState.editing:
    return new Icon(
        Icons.edit,
        color: isDarkActive ? _kCircleActiveDark : _kCircleActiveLight,
        size: 18.0,
    );
case StepState.complete:
    return new Icon(
        Icons.check,
        color: isDarkActive ? _kCircleActiveDark : _kCircleActiveLight,
        size: 18.0,
    );
```
Would result in this:
<img src="https://user-images.githubusercontent.com/16286046/39167356-09af753e-478f-11e8-9e52-23df78fe659a.png" alt="Drawing" height="600" />

In [Material specs](https://material.io/guidelines/components/steppers.html#steppers-usage) there is no mention of icon size. Only that the circle should be 24dp.

Can we make this change? I can make a pull request.

**Comment by Shantanu-Kotambkar** [comment]
@MarcinusX Is there a way already defined in stepper implementation, for changing the icon example editing, complete whenever, we are on the step. I am unable to find a way, but your screenshots looks interesting.

**Comment by MarcinusX** [comment]
I don't think there is such a way. Those code snippets are coming from material library source, so they're not customizable.

**Comment by dereklakin** [comment]
The icons honour the sizing from the `iconTheme` property in the theme. As a workaround, you could override this in the `MaterialApp.theme` property, but that would affect all icons that also use the same theme, so you can wrap your `Stepper` in a `Theme` widget and override the `size` on the `iconTheme`:

```
var theme = Theme.of(context);
Theme(
  data: theme.copyWith(iconTheme: theme.iconTheme.copyWith(size: 18.0),
  child: Stepper(…)
),
```
