### ISSUE TITLE
Null Children Should be Allowed

### ISSUE THREAD

**Issue by agrosner** [flutter/flutter#16935]
## Steps to Reproduce

```dart
class AppBuildInfoItem extends StatelessWidget {
  final BuildInfo buildInfo;

  AppBuildInfoItem(this.buildInfo);

  @override
  Widget build(BuildContext context) {
    return new ListTile(
        title: Padding(
            padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 8.0),
            child: Text("Build ${buildInfo.displayName}")),
        subtitle: Text(buildInfo.getDisplayTime()),
        trailing: Row(children: <Widget>[
          buildInfo.result != "SUCCESS" ? Text(buildInfo.result) : null,
          Platform.isAndroid ? null : Icon(Icons.chevron_right),
        ]));
  }
}
```

`flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1648 pos 14: '!children.any((Widget child) => child == null)': is not true.`

We should be able to return null items in a `Widget[]` and the framework should just globally filter those out. This is useful coming from React, where this is completely valid.

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.3.3, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
[✓] Connected devices (3 available)

• No issues found!

**Comment by StokeMasterJack** [comment]
Agreed. This makes a lot of coding scenarios easier. Which is why React works this way.

**Comment by lyquocnam** [comment]
hope this will done soon !

**Comment by zoechi** [comment]
Closing as dup of #17862.
This one is older but the other has more discussion and upvotes.
