### ISSUE TITLE
Cant add theme to Scaffold

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#16933]
Using this code :

    import 'package:flutter/material.dart';

    void main() => runApp(new MyApp());

    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return new MaterialApp(
          title: 'Flutter Demo',
          theme: new ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: new MyHomePage(title: 'Flutter Demo Home Page'),
        );
      }
    }

    class MyHomePage extends StatefulWidget {
      MyHomePage({Key key, this.title}) : super(key: key);

      final String title;

      @override
      _MyHomePageState createState() => new _MyHomePageState();
    }

    class _MyHomePageState extends State<MyHomePage> {
      @override
      Widget build(BuildContext context) {
        return new Theme(
            data: new ThemeData(backgroundColor: Colors.green),
            child: new Scaffold(
              //backgroundColor: Colors.green,
              appBar: new AppBar(
                title: new Text(widget.title),
              ),
              body: new Center(child: new Text("Hello World")),
            ));
      }
    }

If I have the Scaffold wrapped in a Theme, with <code>backgroundColor: Colors.green</code> the Scaffold does not take on the green background color. If I remove the Theme and uncomment the <code>backgroundColor: Colors.green</code> (inside the Scaffold) the Scaffold background becomes green.

Is this to be expected ? I have been trying to theme a section of my app and wrapping a Scaffold in a Theme seemed like the most logical way to do it.

**Comment by HansMuller** [comment]
The scaffold's background color defaults to the Theme's [scaffoldBackgroundColor](https://docs.flutter.io/flutter/material/Scaffold/backgroundColor.html). You'll want to set that up in the ThemeData provided to the MaterialApp.

The second Theme you've added, the one that wraps MyHomePage, is probably not what you want. It will mask the MaterialApp's theme but it will not affect MyHomePage because they're both part of the same BuildContext. 

Here's [a version of your example](https://gist.github.com/HansMuller/5aa63a86a4e16d6c2a47c8fa720d3e40) that DTRT.

**Comment by Rockvole** [comment]
Ok thanks for clarifying, I didn't expect to find a specific Theme for the scaffold.
Not sure what I was expecting - perhaps something like :

    new ThemeData(
      scaffoldTheme : new ScaffoldTheme(backgroundColor: Colors.green, fontSize: 18.0),
      accentTheme: new AccentTheme(color: Colors.yellow),
      primaryTheme: new PrimaryTheme(colorDark: Colors.slategray)
    )

And then you could override specific themes, like :

    new Scaffold(scaffoldTheme: new ScaffoldTheme(backgroundColor: Colors.darkgreen))

The Theme which wraps MyHomePage was generated from the <code>flutter doctor create</code> script, I didn't really touch it.
