### ISSUE TITLE
Observatory is broken

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1694]

**Comment by Hixie** [comment]
building 5a7907d3517cacbe2a83630cba26d4b99d6a47f4

**Comment by jason-simmons** [comment]
I'm also seeing this on my device after a reboot.  adb says that it established a port forward.  But netstat on the device doesn't show anyone listening on the observatory port.

Possibly this is tied to the recent update to a new release of Dart?

@johnmccutchan

**Comment by Hixie** [comment]
building fcc26eeff8a706a4e876fec8168110f38f19b848 (dart roll)

**Comment by Hixie** [comment]
building @99bc35379a73ea99c934cf0b3d430282c386e611 (one before the dart roll)

**Comment by Hixie** [comment]
Ok I can confirm this broke with the dart roll.

**Comment by eseidelGoogle** [comment]
Once we fix this, ideally we'd have a super basic integration test to test that this works. :D  @yjbanov may have suggestions as to how, or someone can just write a simple dart script?  I don't know that we have any launch testing yet (but desperately need some).  `flutter` has some tests:
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/test
which might be able to drive this?

**Comment by yjbanov** [comment]
Saucelabs [seems to have real devices](https://saucelabs.com/features#features-automated-mobile). We could dedicate one of the builds to run on Saucelabs.

**Comment by johnmccutchan** [comment]
@eseidelGoogle That's a good idea. The mojo tree has a very simple integration test to protect against this. I'm starting work on this, should have things fixed in the morning.

**Comment by johnmccutchan** [comment]
These are the integration tests we run:

- We can make a service protocol call over HTTP.
- We can make a service protocol call over WebSocket.
- We can fetch some asset from Observatory.

**Comment by eseidelGoogle** [comment]
Is this specific to devices?  If so I can make sure to add on-real-device-testing to our up-and-coming chrome-infra based infrastructure: https://build.chromium.org/p/client.flutter/waterfall  (I know on-device testing is needed, just getting the simpler stuff sable first.)

**Comment by johnmccutchan** [comment]
It would be best to test this against an android device and an iOS device with service protocol + observatory baked in.

**Comment by johnmccutchan** [comment]
@yjbanov https://github.com/flutter/engine/pull/2370 adds a heart beat test that runs on Linux (but not against actual devices).
