### ISSUE TITLE
[Android Plugin] Auto generated code(GeneratedPluginRegistrant) can't fit plugin written in Kotlin

### ISSUE THREAD

**Issue by xuexin** [flutter/flutter#16955]
In GeneratedPluginRegistrant.java
`Plugin.registerWith();`
But if plugin written in Kotlin, the code shoule be like this:
`Plugin.Companion.registerWith()`

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by xuexin** [comment]
no

**Comment by zoechi** [comment]
Thanks for the update!
