### ISSUE TITLE
Confusing error: _debugLifecycleState != _StateLifecycle.defunct

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#1695]
In `setState` in framework.dart, there's an assert that reads:

`assert(_debugLifecycleState != _StateLifecycle.defunct);`

The meaning of this assert is difficult for a beginner to divine. This assert should be in the documentation for setState to say something like "setState() was called by a widget that was not included in the widget tree in the last call to build()."

This assert is easy to hit with an AnimationController continuing to call an old object.

**Comment by abarth** [comment]
Yeah, this assert is meant to catch that case.  We should add more documentation explaining what went wrong when you hit that.

**Comment by jimbeveridge** [comment]
I propose that dispose() is not a beginner-level function. Forcing the developer to implicitly understand the Widget lifecycle well enough to know when dispose is called does not help beginners solve the problem. What is the circumstance that causes dispose to be called? Maybe that's more helpful.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/1698/files is the text I wrote.  Do you want to suggest different text?  We can also link to a web page if we want to explain in detail with diagrams and such.
