### ISSUE TITLE
Change/regression in Font Rendering in latest beta

### ISSUE THREAD

**Issue by Areiser** [flutter/flutter#16954]
## Steps to Reproduce

The Font rendering in Flutter changed when I updated to the latest beta. I attached two screenshots. In the second button "Challenge a friend" the dot on the i is rendered in a different way. I am using the Pilkius Romeus Font. The rendering is like this in every instance a small "i" is used in my App. 

Below you can see the screenshots.

![screenshot_1524568495](https://user-images.githubusercontent.com/14922864/39233846-deac5364-4871-11e8-85fd-0af9610e07c5.png)

![screenshot_20180425-101405](https://user-images.githubusercontent.com/14922864/39233889-f4b785ac-4871-11e8-9d5f-a38622a3a415.png)

Is there a way to quickly rollback to the previous beta?

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.3.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.3.1 at /run/media/andreas/Andreas/Programmieren/flutter
    • Framework revision 12bbaba9ae (5 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/andreas/Android/Sdk
    • Android NDK at /home/andreas/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /usr/share/intellijidea-ce
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] Connected devices (1 available)
    • HUAWEI VNS L31 • FUH7N17220000709 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

**Comment by xster** [comment]
cc @jason-simmons

**Comment by Areiser** [comment]
Thanks for taking a look. I can reproduce with https://github.com/Areiser/font-repro on my Huawei P9 lite and on the android emulator.

**Comment by jason-simmons** [comment]
This is happening when a bold font weight is applied to this font.

Starting in https://github.com/flutter/engine/commit/2ef8e3039603e7f3dda0a98deacb7b14c64aba71 Flutter asks Skia to synthesize bold text when a bold variant of the requested font is unavailable.  The rendering of the "i" character is the result of the fake bold output.

You can work around this by embedding a bold version of the font in the app (if one exists) or switching to a normal font weight.

**Comment by Areiser** [comment]
Thank you very much! 
So it was not a regression but an intentional change and I just set an unsupported font weight. 
After switching to a normal font weight the rendering is fine!
