### ISSUE TITLE
No display of flag emojis on iOS

### ISSUE THREAD

**Issue by sma** [flutter/flutter#16960]
## Steps to Reproduce

This code

```dart
Text("🇩🇪😢"),
```

is displayed as

![image](https://user-images.githubusercontent.com/14989/39243854-24f614f0-488f-11e8-9339-dad00dcbe384.png)

(that is `D E 😢`) and not a German flag. Looks like flag emojis fail to display.

I've checked only iOS 11.3 so far. Seems to work on Android (API 26).

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.3.4, on Mac OS X 10.13.4 17E199, locale de-DE)
    • Flutter version 0.3.4 at /Users/sma/Work/flutter
    • Framework revision c7ee37a0d8 (32 hours ago), 2018-04-23 21:26:51 -0700
    • Engine revision ec611470b5
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone 8 • 25BC5818-6300-43D9-ABEB-09370F081240 • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by jason-simmons** [comment]
This also happened in the Blink-based text rendering engine originally used by Flutter.

HarfBuzz as configured on iOS is not mapping the regional indicator symbol pairs to flag glyphs.

Here is a log of how this was handled in Chromium's renderer.  We could try a similar approach in Flutter:
    https://bugs.chromium.org/p/chromium/issues/detail?id=739641

@chinmaygarde

**Comment by chinotapales** [comment]
Hi guys, any update regarding this?

I'm building an app mainly revolving around flag emojis and so far for iOS it's still not working. Hopefully this can be fixed soon :)

**Comment by RishitKedia** [comment]
This just got fixed in the `master` branch. Yay! 🤘
See #9652.

@sma @zoechi This issue can be closed now, I guess. 😋

**Comment by sma** [comment]
works for me, thanx.

**Comment by milanobrenovic** [comment]
Hello this issue seems to be broken again, anyone knows how to fix this? Flags are the only emojis that cannot be rendered
