### ISSUE TITLE
Isolate.spawn on a Future no longer works with latest beta (example in docs also broken)

### ISSUE THREAD

**Issue by hugovangalen** [flutter/flutter#16961]
I noticed that my code, that calls Isolate.spawn with a Future as the first argument, no longer works on latest Flutter (Channel beta, v0.3.1, on Linux, locale en_US.UTF-8).

If I changed the called method to be a normal, non-Future / async method, it works. 

I double checked the docs, and noticed that the Isolate example code on this page is also broken:
  https://flutter.io/flutter-for-android/

**Comment by zoechi** [comment]
Can you try with `--no-preview-dart-2`?

**Comment by jason-simmons** [comment]
This should be fixed on the `master` channel

**Comment by mit-mit** [comment]
Closing now we know this was resolved in master.
