### ISSUE TITLE
Flutter runs lib/main.dart despite saying it was running lib/broken.dart

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#16962]
I've had a few complaints from Dart Code users before, but never seen it myself. Today, I am!

I have two scripts in my `lib` folder, `main.dart` and `broken.dart`. `main.dart` renders `Heeello, world!` but `broken.dart` throws an exception in the build method. Almost all of the time when I pass `lib/broken.dart` to `flutter run --machine` it claims that's running that script (note the output text in the `Debug Console`) however it still runs `main.dart`!

<img width="1065" alt="screen shot 2018-04-25 at 3 06 09 pm" src="https://user-images.githubusercontent.com/1078012/39251065-4a55d1d0-489a-11e8-8b34-1c288d3e5312.png">

To test it wasn't just a cached build, I modified `main.dart` and it got the update text on the next run (originally it said `Hello, world`, I added some e's).

**Comment by DanTup** [comment]
Can repro from the command line.

<img width="1080" alt="screen shot 2018-04-25 at 3 11 38 pm" src="https://user-images.githubusercontent.com/1078012/39251379-04fee0c6-489b-11e8-90e3-295664124c64.png">

**Comment by xster** [comment]
Might be #16787

**Comment by DanTup** [comment]
Yeah, that seems likely, since I didn't see it when using the flutter_test device. I'll close this assuming a dupe and re-open if it turns out to not be the case.
