### ISSUE TITLE
Ability to reset state

### ISSUE THREAD

**Issue by StokeMasterJack** [flutter/flutter#16969]
I'm referring to the feature of hot reload where it preserves the apps state. I get that most of the time this is "feature". But sometimes it can be a pain in the butt. Sometimes I want hot (fast) reload but I _don't_ want to preserve app state. Instead I want my state to go back to it's initial state. 

For example suppose I have a 7 step wizard. And suppose my app doesn't have a "Go back to step 1" button. I would like to do a hot reload that doesn't preserve state.

**Comment by jonahwilliams** [comment]
This feature is called "Hot Restart".  From the command line, "r" is hot reload and "R" is hot restart.  The actual UI feature varies per IDE and i'm not sure what you are using

**Comment by fmatosqg** [comment]
you can use `reassemble` to clean things or redo whatever you did on `initState`. `reassemble` runs every time you hot reload.

**Comment by jonahwilliams** [comment]
@fmatosqg you shouldn't need to use reassemble in application code, that is framework level support for hot reload

**Comment by zoechi** [comment]
I assume this can be closed.
