### ISSUE TITLE
Error GoogleSignln

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#16980]
E/flutter ( 3652): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3652): type 'Future<dynamic>' is not a subtype of type 'Future<Null>' where
E/flutter ( 3652):   Future is from dart:async
E/flutter ( 3652):   Future is from dart:async
E/flutter ( 3652):   Null is from dart:core
E/flutter ( 3652):
E/flutter ( 3652): #0      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart)
E/flutter ( 3652): <asynchronous suspension>
E/flutter ( 3652): #1      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:196:28)
E/flutter ( 3652): #2      _RootZone.run (dart:async/zone.dart:1376:54)
E/flutter ( 3652): #3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151:18)
E/flutter ( 3652): #4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:607:39)
E/flutter ( 3652): #5      Future._propagateToListeners (dart:async/future_impl.dart:663:37)
E/flutter ( 3652): #6      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:346:9)
E/flutter ( 3652): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 3652): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
D/FirebaseInstanceId( 3652): background sync failed: SERVICE_NOT_AVAILABLE, retry in 120s
D/FirebaseInstanceId( 3652): background sync failed: SERVICE_NOT_AVAILABLE, retry in 240s
W/DynamiteModule( 3652): Local module descriptor class for com.google.firebase.auth not found.

**Comment by jldork** [comment]
Hi @giovannilima262 , I had the same issue and it had been resolved in this thread: https://github.com/flutter/flutter/issues/16463

**Comment by giovannilima262** [comment]
I got

**Comment by jldork** [comment]
If this worked can you close the issue :) ?
