### ISSUE TITLE
time_to_first_frame flutter_gallery_ios__start_up on iOS is super noisy

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#16988]
flutter_gallery_ios__start_up ranges from 370ms to 1300ms depending on the run. :/

@yjbanov @Hixie

**Comment by yjbanov** [comment]
It hasn't always been like this, but it also didn't regress in a single commit. It seems to have been getting worse over a long period of time.

<img width="1339" alt="screen shot 2018-04-26 at 10 50 30 am" src="https://user-images.githubusercontent.com/211513/39322867-f937a476-493f-11e8-94cc-8d7fe60d86da.png">

**Comment by chinmaygarde** [comment]
This benchmark does not exist anymore.
