### ISSUE TITLE
Problem with background-parsing (i.e. compute function) example in docs

### ISSUE THREAD

**Issue by StokeMasterJack** [flutter/flutter#16983]
When running this example:
https://flutter.io/cookbook/networking/background-parsing/
I get a runtime error:
List<dynamic>' is not a subtype of type 'List<Photo>

I think the problem has nothing to do with the compute function. The issue is this part:

```
List<Photo> parsePhotos(String responseBody) {
    final parsed = json.decode(responseBody);
    return parsed.map((json) => new Photo.fromJson(json)).toList();
  }
```
What ever toList() is returning is not the correct type.

This code works:

```
List<Photo> parsePhotos(String responseBody) {
    final parsed = json.decode(responseBody);
    List<Photo> photos = [];
    for (var jsonObject in parsed) {
      Photo photo = Photo.fromJson(jsonObject);
      photos.add(photo);
    }
    return photos;
```

**Comment by jonahwilliams** [comment]
It looks the inference for `map` is failing, and parsed becomes `List<dynamic>`.  If you replace parsePhotos with the following do you still get a type error?

```
List<Photo> parsePhotos(String responseBody) {
    final parsed = json.decode(responseBody);
    return parsed.map<Photo>((json) => new Photo.fromJson(json)).toList();
  }
```

**Comment by jonahwilliams** [comment]
@StokeMasterJack

**Comment by brianegan** [comment]
Hey all, sorry about this one! I've got a PR with a fix up for this on the Website repo, but it hasn't been reviewed quite yet. I've pinged a few folks to see if they can help out!

**Comment by vipulasri** [comment]
I am getting **"object is a closure - Function 'parsePhotos'"** this error: 

    [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function 'parsePhotos':.)
    #0      Isolate._spawnFunction (dart:isolate/runtime/libisolate_patch.dart:510:59)
    #1      Isolate.spawn (dart:isolate/runtime/libisolate_patch.dart:361:7)
    <asynchronous suspension>

**Comment by koraxis** [comment]
I am getting the same "Illegal argument in isolate message " error.

**Comment by vipulasri** [comment]
@brianegan Please look at this.

**Comment by brianegan** [comment]
Thanks all -- just back from vacation. I'll take a look tomorrow.

**Comment by vipulasri** [comment]
@brianegan welcome back, did you get the time to look at this?

**Comment by brianegan** [comment]
Sorry @vipulasri, arrived home from travel to some family health problems and didn't get a chance yet. I'll update soon!

**Comment by brianegan** [comment]
Heya @vipulasri -- just ran the recipe from the Cookbook, and it seems to be running for me. Does the example in the Flutter cookbook work, or is that failing?

If the example is failing, could you please copy and paste the results of `flutter doctor -v`? If you're trying this out with your own classes, please note the restrictions on passing objects between isolates: https://flutter.io/cookbook/networking/background-parsing/#notes-on-working-with-isolates

It sounds like you might have a class that contains closures (Functions) as data, and that will throw an error.

**Comment by vipulasri** [comment]
@brianegan Yeah, I am trying put with my own class. I am unable to figure out to make it work. Thanks for looking into it.

**Comment by brianegan** [comment]
@vipulasri Gotcha! Yep, the objects you can pass back and forth between Isolates generally need to be  "primitive types" such as Strings, ints, etc.

If you have a class that contains a closure (such as `final Function() myFunc;`, you'll see Dart throw errors. In these cases, you might need to rework the classes you're passing back and forth a bit to contain only simple data.

**Comment by vipulasri** [comment]
@brianegan Thanks for this detailed explanation. Earlier, I wasn't able to quite properly understand it.

**Comment by brianegan** [comment]
Good feedback, I'll update the recipe to add a bit more detail.

**Comment by vipulasri** [comment]
@brianegan btw I followed the same way that is depicted in sample: https://flutter.io/cookbook/networking/background-parsing/ but for my code, still facing the issue.
My Code:

    class Api {
    
	Future <List<Painting>> getFeaturedArts(int page) async {
		final url = "https://www.wikiart.org/?json=2&layout=new&param=featured&layout=new&page=$page";
		final response = await http.get(url);
		return compute(parseFeaturedArts, response.body);
	}

	List<Painting> parseFeaturedArts(String response) {
		final responseJson = json.decode(response);
		final paintingResponse = new PaintingResponse.fromJson(responseJson);
		return paintingResponse.paintings;
	}

    }

Though, I am not using `FutureBuilder`.

**Comment by brianegan** [comment]
Heya @vipulasri -- I don't think `FutureBuilder` would make the difference. The above code generally looks fine to me. Could you please show me the code for your `Painting` class?

**Comment by vipulasri** [comment]
@brianegan Here it is: https://gist.github.com/vipulasri/669e76299f1784d13ad3aa311ccf1e9d

**Comment by brianegan** [comment]
Ah wait, sorry -- I'd missed something in the first piece of code you pasted. This is another odd restriction in Dart -- you can't pass a method of a class across isolates. You must extract the `parseFeaturedArts` function out as a top-level function. 

If you arrange your code like so, it should work:

```dart
class Api {
  Future<List<Painting>> getFeaturedArts(int page) async {
    final url =
        "https://www.wikiart.org/?json=2&layout=new&param=featured&layout=new&page=$page";
    final response = await http.get(url);
    return compute(parseFeaturedArts, response.body);
  }
}

List<Painting> parseFeaturedArts(String response) {
  final responseJson = json.decode(response);
  final paintingResponse = new PaintingResponse.fromJson(responseJson);
  return paintingResponse.paintings;
}
```

**Comment by vipulasri** [comment]
@brianegan Awesome 👍 It worked! All these things should be mentioned in the documentation :(

**Comment by brianegan** [comment]
Fair point, I'll add that info!

**Comment by lastant** [comment]
@brianegan Also seems the callback function (parseFeaturedArts) cannot return results of asynchronous functions (basically can't do `await` on other functions)? Because then it would have to return a Future, but it must return a value?

**Comment by MichaelSowah** [comment]
@brianegan I get this error from the updated code on the cookbook link https://flutter.io/cookbook/networking/background-parsing/
``` Dart Error: Unhandled exception:
E/flutter (31340): NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance method 'map' with matching arguments.
E/flutter (31340): Receiver: _LinkedHashMap len:2
E/flutter (31340): Tried calling: map<Yaip>(Closure: (dynamic) => Yaip)
E/flutter (31340): Found: map<K2, V2>((K, V) => MapEntry<K2, V2>) => Map<K2, V2>
```

**Comment by johnny-stevie** [comment]
same, i gave up with the example as it was outdated or something as it always broke down

**Comment by brianegan** [comment]
Heya @johnny-stevie -- could you describe the problem you're seeing? I've just run the sample code against Flutter Stable, Beta, and Master channels and I didn't encounter any issues.

**Comment by antoninobajeli** [comment]
Hello, in my project I'm facing this problem:

> Invalid argument(s): Illegal argument in isolate

 Then I replaced my with the original example:

` Future<List<Photo>> fetchPhotos(http.Client client) async {
    final response =
    await client.get('https://jsonplaceholder.typicode.com/photos');
    return compute(parsePhotos, response.body);
  }

  List<Photo> parsePhotos(String responseBody) {
    final parsed = jsonDecode(responseBody).cast<Map<String, dynamic>>();
    return parsed.map<Photo>((json) => Photo.fromJson(json)).toList();
  }
`
but unfortunatelly I'm facing the same problem: 
**[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function 'parsePhotos':.)
#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:541:55)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:381:7)**



Here is my Flutter configuration:
`[✓] Flutter (Channel master, v1.16.4-pre.73, on Mac OS X 10.15.2 19C57, locale it-IT)
    • Flutter version 1.16.4-pre.73 at /Users/antoninobajeli/Documents/FlutterSDK/flutter
    • Framework revision 6fddb7ee8c (5 hours ago), 2020-04-02 10:31:03 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/antoninobajeli/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/antoninobajeli/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.5.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.5.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPhone di Antonino Bajeli • 1dc32573e1ee148d13ae7c8cee583152725b9185 • ios            • iOS 12.4.5
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 80.0.3987.149
    • Web Server                • web-server                               • web-javascript • Flutter Tools
`

**Comment by johnny-stevie** [comment]
@brianegan I've given up on that already and moved on to another part of my project. Thanks for offering to help anyway!

**Comment by antoninobajeli** [comment]
I solved by myself.
My mistake has been to put both metohss inside the same class. 
The solution has bee to put the method calling 'compute' in a class "MyClass" and the method called by the 'compute' outside "MyClass" class.

May be this can be an help for other facing the same problem.

Tony
