### ISSUE TITLE
Hi everyone. If there anyway for flutter to insert one picture in a row?

### ISSUE THREAD

**Issue by sjtutyx** [flutter/flutter#16997]
I want to design a row in flutter like this:

![image](https://user-images.githubusercontent.com/9338658/39299525-78161026-497b-11e8-8702-2cf899e92524.png)

Is there anyway can insert one picture at the left part of a row?

Thanks for the help.

**Comment by najeira** [comment]
Yes you can do that.
How-to questions are better asked on StackOverflow.

**Comment by mit-mit** [comment]
Closing; as mentioned above StackOverflow is a better venue for Q&A.
