### ISSUE TITLE
ResourceExtractor in Flutter.jar seems wired in some certain devices.

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#16993]
## Steps to Reproduce

When we released our apk to thousands users, we received a lot crash reports.
#16919  #16748 
According to explanation from @jason-simmons  , those are all resulted from a broken icudtl.dat.
After we refactored our code to the way recommended by flutter team, the problem still appears. One Nexus5(Android7) for testing will continuously crash when we want to enter the flutter page.
So we dug more and found that ResourceExtractor.extractResources works unexpectedly when running in background. The inputstream will give the false length for icudtl.dat.The right length is 6635168 while the inputsteam give us 6563104. The file with wrong length will not changed until upgraded, i.e, once broken, it can't be repaired in the same version. As flutter engine has logic to read this file,wordbreaker,etc, it will continuously crash when used.
```
InputStream is = manager.open(asset)
```
```
01-18 18:08:14.355 17040 17040 W [KWLM]  : [KWLM]manager.open: icudtl.dat:6635168
01-18 18:08:14.421 17040 17040 W [KWLM]  : [KWLM2]manager.open: icudtl.dat:6635168
01-18 18:08:14.437 17040 17057 W ResourceExtractor: [KWLM]manager.open: vm_snapshot_data:23416
01-18 18:08:14.462 17040 17057 W ResourceExtractor: [KWLM]:os.flush: vm_snapshot_data:23416
01-18 18:08:14.470 17040 17057 W ResourceExtractor: [KWLM]manager.open: isolate_snapshot_data:4293720
01-18 18:08:17.009 17040 17057 W ResourceExtractor: [KWLM]:os.flush: isolate_snapshot_data:4293720
01-18 18:08:17.010 17040 17057 W ResourceExtractor: [KWLM]manager.open: isolate_snapshot_instr:5311776
01-18 18:08:18.853 17040 17057 W ResourceExtractor: [KWLM]:os.flush: isolate_snapshot_instr:5311776
01-18 18:08:18.857 17040 17057 W ResourceExtractor: [KWLM]manager.open: icudtl.dat:6563104
01-18 18:08:19.783 17040 17057 W ResourceExtractor: [KWLM]:os.flush: icudtl.dat:6563104
01-18 18:08:19.794 17040 17057 W ResourceExtractor: [KWLM]manager.open: vm_snapshot_instr:10160
01-18 18:08:19.812 17040 17057 W ResourceExtractor: [KWLM]:os.flush: vm_snapshot_instr:10160
```

The api works fine when in foreground and fails in background.
So I've changed the engine as below for a workaround and it seems ok.

![image](https://user-images.githubusercontent.com/817851/39287176-f0ec2250-4954-11e8-92af-dbd37cb3a94a.png)

Maybe the flutter.jar should ensure the file's integrality based on mechanism like md5, at least the length.

We are still increasing our user amount who will hit the flutter page logic. Up to now, no flutter related issue found for over 1k users.

## Flutter Doctor
KyleWongdeMacBook-Pro:~ kylewong$ /Users/kylewong/Codes/fwn_idlefish/flutter/bin/flutter doctor -v
Building flutter tool...
[✓] Flutter (Channel beta, v0.1.6-pre.50, on Mac OS X 10.13.4 17E199, locale en-CN)
    • Flutter version 0.1.6-pre.50 at /Users/kylewong/Codes/fwn_idlefish/flutter
    • Framework revision 1d95c20064 (18 hours ago), 2018-04-25 19:11:05 +0800
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK at /Users/kylewong/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

@eseidelGoogle

**Comment by najeira** [comment]
It has been fixed in Flutter 0.2.0 and later.

**Comment by kangwang1988** [comment]
But we're using flutter v0.2.3.

**Comment by kangwang1988** [comment]
In fact, we are using the engine generated Flutter.framework/flutter.jar.
![image](https://user-images.githubusercontent.com/817851/39311177-c944d194-499e-11e8-8c01-dcbdd67dab78.png)
![image](https://user-images.githubusercontent.com/817851/39311184-ce0a4be6-499e-11e8-8aea-f0aa336d818c.png)

**Comment by jason-simmons** [comment]
Is there any chance that something could be using the Flutter engine before `FlutterMain.ensureInitializationComplete` returns?

`ensureInitializationComplete` should block until the `ResourceExtractor` has finished writing all asset files.  If the `ResourceExtractor` background task is still running, then the engine can not be used safely.

**Comment by kangwang1988** [comment]
After we move the extractResources logic in ResourceExtractor.java, the problem disappear now.

**Comment by mimers** [comment]
@kangwang1988  I encounter a crash which stack trace was just same as you put before.
I am using flutter beta 0.4.4, both x86/android-arm-release will crash in my situation:
It works fine If I call FlutterMain#startInitialization in Application#onCreate, but it will crash if I call FlutterMain#startInitialization in FlutterActivity#onCreate(or before onCreate, e.g. when user click the page entry icon). I guess the engine need some more time to `real` initialize the icudtl.dat content?
I also found the crash related to the complexity of the widget tree. My flutter page has a loading animation before displaying full content, it only crash when building the full content widget tree. 

Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (4 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

Symbolicated stack trace:
Build fingerprint: 'Android/sdk_google_phone_x86/generic_x86:6.0/MASTER/4729342:userdebug/test-keys'
pid: 24103, tid: 24459, name: 1.ui  >>> li.joker.tutorial <<<
signal 11 (SIGSEGV), code 0 (SI_USER), fault addr 0x0
Stack frame #00 pc 004bea19  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine minikin::WordBreaker::setText(unsigned short const*, unsigned int) at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../flutter/third_party/txt/src/minikin/WordBreaker.cpp:55
Stack frame #01 pc 004bc5df  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine minikin::LineBreaker::setText() at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../flutter/third_party/txt/src/minikin/LineBreaker.cpp:74
Stack frame #02 pc 004c32e8  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine txt::Paragraph::ComputeLineBreaks() at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../flutter/third_party/txt/src/txt/paragraph.cc:273
Stack frame #03 pc 004c42d6  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine txt::Paragraph::Layout(double, bool) at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../flutter/third_party/txt/src/txt/paragraph.cc:428
Stack frame #04 pc 000aff8f  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine blink::ParagraphImplTxt::layout(double) at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../flutter/lib/ui/text/paragraph_impl_txt.cc:54
Stack frame #05 pc 000add90  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine blink::Paragraph::layout(double) at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../flutter/lib/ui/text/paragraph.cc:80
Stack frame #06 pc 000ae0a0  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine tonic::DartDispatcher<tonic::IndicesHolder<0u>, void (blink::Paragraph::*)(double)>::Dispatch(void (blink::Paragraph::*)(double)) at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../topaz/lib/tonic/dart_args.h:150
Stack frame #07 pc 000ad9f7  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine blink::Paragraph_layout(_Dart_NativeArguments*) at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../flutter/lib/ui/text/paragraph.cc:36
Stack frame #08 pc 0067ac2e  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../third_party/dart/runtime/vm/native_entry.cc:198
Stack frame #09 pc 0067aa93  /data/app/li.joker.tutorial-2/lib/x86/libflutter.so: Routine dart::NativeEntry::AutoScopeNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) at /b/build/slave/Linux_Engine/build/src/out/android_debug_x86/../../third_party/dart/runtime/vm/native_entry.cc:168
Stack frame #10 pc 00000776  <unknown>
Stack frame #11 pc 0003202e  <unknown>

**Comment by zoechi** [comment]
Is there still something to do for the Flutter team?

**Comment by kangwang1988** [comment]
I don't know whether https://github.com/flutter/flutter/issues/18514 has fixed this issue.
Now I am upgrading to betav0.8.2, and will update the status for this issue after some blue-green deployments.

**Comment by Hixie** [comment]
@kangwang1988 I'm going to close this one since we think it's resolved; please open a new bug if you still see issues.
