### ISSUE TITLE
`flutter run` fails to use flutter_tester on Travis

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#16996]
I'm not sure if this is Travis-specific, but it seems to work fine on my MacBook. On Travis, however:

```
flutter run --machine -t lib/main.dart -d flutter-tester

Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
```

If I try to run `flutter_tester` directly, it works fine:

```
flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --non-interactive --packages=.packages test/widget_test.dart

Observatory listening on http://127.0.0.1:50684/
00:00 +0: - Hello world test
00:00 +1: All tests passed!
```

Travis is running latest `master` code at the time of testing:

```
 [✓] Flutter (Channel unknown, v0.3.6-pre.21, on Mac OS X 10.12.6 16G29, locale en-US)
    • Flutter version 0.3.6-pre.21 at /Users/travis/build/Dart-Code/Dart-Code/with spaces/dev/flutter
    • Framework revision 4bb7496b62 (4 hours ago), 2018-04-25 22:16:59 -0700
    • Engine revision cb2092b3fd
    • Dart version 2.0.0-dev.50.0.flutter-8d4074175f
```

Since it only happens on Travis, it's not simple to step through or add logging. My guess is it's failing to start the test device, but maybe the output from that isn't making it's way back anywhere?

**Comment by DanTup** [comment]
cc @scheglov

**Comment by DanTup** [comment]
Ok, looks like it's due to not having an Android SDK. Here's what happens on Travis when running with `--verbose`:

```
[  +15 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.3.5-21-g4bb7496b6
[ +179 ms] Unable to locate an Android SDK.
[  +10 ms] Unable to locate an Android SDK.
[ +119 ms] Unable to locate a development device; please run 'flutter doctor' for information about installing additional 
```

But locally I get:

```
[  +12 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.3.5-21-g4bb7496b6
[ +119 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +34 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +127 ms] /Users/dantup/Library/Android/sdk/platform-tools/adb devices -l
[  +14 ms] Exit code 0 from: /Users/dantup/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +4 ms] idevice_id -h
[ +158 ms] /usr/bin/xcrun simctl list --json devices
[ +114 ms] Running "flutter packages get" in flutter_hello_world...
```

and then shortly after it launches flutter_tester.

So, I'm not sure whether this is deliberate (and we need an Android SDK) or something that could be fixed by not failing in this way if it's not found if we're going to spawn `flutter_tester`. @devoncarew @scheglov, any thoughts?

**Comment by DanTup** [comment]
If we wanted to support this, I think the relevant code might be in `_DefaultDoctorValidatorsProvider`. It has two worksflows added to the list:

```
if (androidWorkflow.appliesToHostPlatform)
  _validators.add(androidWorkflow);

if (iosWorkflow.appliesToHostPlatform)
  _validators.add(iosWorkflow);
```

These both return false for `canLaunchAnything` which is called in `RunCommand.validateCommand()` via `findAllTargetDevices()` and quits. Possibly there should be a tester workflow if we're going to be launching on the test device so that we don't quit early?

(ofc, if the tester device has a dependency on Android or iOS this might not be an option, but I don't think that's the case based on it running the test ok when invoked directly).

**Comment by devoncarew** [comment]
We'll probably need to improve the logic for listing available devices in the presence of the `--show-test-device` flag, or `--device=flutter-tester`.

**Comment by scheglov** [comment]
Hm... So, what is the problem if "shortly after it launches flutter_tester"? If I don't run in the verbose mode, I don't even notice that my `Android` folder is renamed, so that Android SDK is not available.

**Comment by DanTup** [comment]
@scheglov It it can't find either Android or iOS dependencies, it throws "Unable to locate a development device; please run 'flutter doctor' for information about installing additional". If you only moved Android, maybe you have iOS available?

If you return `false` from `canListAnything` (or `canLaunchAnything`?) in both `AndroidWorkflow` and `iOSWorkflow` I think it should repro (without having to get another machine or use Travis).

**Comment by scheglov** [comment]
Thanks. Yes, if I also hide Xcode, I get the same error.
I will need to do something with it...
