### ISSUE TITLE
Flutter Build Apk generates a signed apk with old code

### ISSUE THREAD

**Issue by Cyan101** [flutter/flutter#16992]
## Steps to Reproduce

Write some flutter code and build an apk, then modify and change the code and run the same `flutter build apk` again to generate an apk, this will be signed with the latest androidmanifest but will not contain the latest up-to-date code in the /lib files

using `flutter run` or the debug running inside android studio will build the app from the latest files, but if you build an apk in the morning, do a bunch of testing in debug mode and modify lots then build an apk in the afternoon, it will just rebuild the earlier apk with all the unedited code

## Logs
```
C:\Users\Cyan\Documents\flutter-apps\x>flutter build apk
Initializing gradle...
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
Skipping AOT snapshot build. Fingerprint match.
Built build\app\outputs\apk\release\app-release.apk (8.0MB).
```

## Flutter Doctor

C:\Users\Cyan\Documents\flutter-apps\x>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
This is a known issue. Don't know if there is one filed explicitly for that.

`flutter clean` before `flutter build ...` should help

**Comment by mit-mit** [comment]
This is the same underlying issue as https://github.com/flutter/flutter/issues/16597

**Comment by Cyan101** [comment]
`flutter clean` fails to clean my build/ because it's not empty
