### ISSUE TITLE
Shadows (and other paintBounds-exceeding paints) are dropped by lazy lists

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#170]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Sep 24, 2015 at 19:07 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1323_

---

Suppose you have a widget whose `position & size` happens to place it so that its bottom is just off the top of a vertically scrolling list. Its shadow, if any, will vanish.

We should base these widgets on the children's paintBounds, not their sizes.

**Comment by abarth** [comment]
Paint bounds isn't a thing anymore.  Maybe the solution here is to pad the viewport by one item?  It's hard to know how far a shadow will extend from beyond the viewport...

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/5467 would provide a real fix for this, but we should probably do the padding thing.

**Comment by Hixie** [comment]
A bunch of bugs about scrolling laziness claim that this is the fix, but actually a better fix for this is pad the viewport by one on each side. We'll also need that to fix https://github.com/flutter/flutter/issues/1714.
