### ISSUE TITLE
Install fails on macOS

### ISSUE THREAD

**Issue by TheSirC** [flutter/flutter#17009]
## Steps to Reproduce

On a fresh install with [those steps](https://flutter.io/setup-macos/#get-sdk) : 

1. Get the SDK (either the one on the page before or the most recent version (at the moment) via `git clone -b beta https://github.com/flutter/flutter.git .flutter`)
2. Unzip it to `~/.flutter`
3. Add the folder above to the `PATH` with the corresponding line in my `.zshrc`
4. Run `flutter`

<details>
<summary>Error output</summary>
<p>

```
Unhandled exception:
FileSystemException: Cannot create file, path = '/Users/sirc/.flutter' (OS Error: Is a directory, errno = 21)
#0      _File.throwIfError (dart:io/file_impl.dart:628)
#1      _File.createSync (dart:io/file_impl.dart:271)
#2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:119)
#3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30)
#4      new Usage (package:flutter_tools/src/usage.dart:28)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:71)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
#7      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114)
#10     Usage.instance (package:flutter_tools/src/usage.dart:52)
#11     flutterUsage (package:flutter_tools/src/usage.dart:20)
#12     _handleToolError (package:flutter_tools/runner.dart:108)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:58)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#20     run (package:flutter_tools/runner.dart:49)
#21     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#22     main (file:///Users/sirc/.flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

</p>
</details>

## Logs

Every flutter command sends back the same output as above.

The `PATH` look like this : `/Users/sirc/.flutter/bin:/Users/sirc/.flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin/Users/sirc/.flutter/bin:/Users/sirc/.flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin`

## Flutter Doctor 

`flutter doctor` sends back the same output as above.

**Comment by TheSirC** [comment]
I am utterly sorry to fill your bug tracker with that bug which is definitely my fault but I do not see where.

**Comment by maryx** [comment]
What about if you run `/Users/sirc/.flutter/bin/flutter`?

And no worries! You could try posting to StackOverflow (https://stackoverflow.com/search?q=flutter) if you think the issue is with your setup/your code rather than with Flutter itself :)

**Comment by TheSirC** [comment]
After further investigations 🙄  it seems that `.flutter` is not a valid name for the directory containing the repository. I do not close it myself for you to know about it. Feel free to close it as soon as you want.
