### ISSUE TITLE
Error update flutter 0.1.5 -> 0.3.1

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#17001]
I/flutter (11940): Color(0xffffde00), borderRadius: BorderRadius.circular(25.0)), constraints:
I/flutter (11940): BoxConstraints(0.0<=w<=Infinity, h=50.0), margin: EdgeInsets(10.0, 0.0, 10.0, 10.0)):
I/flutter (11940): The getter 'value' was called on null.
I/flutter (11940): Receiver: null
I/flutter (11940): Tried calling: value
I/flutter (11940): When the exception was thrown, this was the stack:
I/flutter (11940): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter (11940): #1      _TabBarState._indicator (package:flutter/src/material/tabs.dart:694:51)
I/flutter (11940): #2      _TabBarState._initIndicatorPainter (package:flutter/src/material/tabs.dart:738:18)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`

**Comment by giovannilima262** [comment]
[✓] Flutter (Channel beta, v0.3.1, on Linux, locale pt_BR.UTF-8)
    • Flutter version 0.3.1 at /home/giovanni/flutter
    • Framework revision 12bbaba9ae (6 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/giovanni/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • A18 • 0123456789ABCDEF • android-arm • Android 4.4.2 (API 19)

**Comment by giovannilima262** [comment]
I run as flutter run --no-preview-dart-2

**Comment by giovannilima262** [comment]
I got
