### ISSUE TITLE
Idea : Improving theme discover-ability

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#17013]
I am halfway through my second flutter app and its starting to dawn on me that the Theme system is actually pretty neat. Whenever I have tried to use Themes before they have not worked as expected (mostly due to not finding the correct keywords) and so I gave up and littered my code with color constants and such.

I think with some tweaking the themes could become the default way of changing styles.
By partitioning ThemeData we can use keywords which are consistent :
```dart
    new MaterialApp(
      appBarThemeData : new AppBarThemeData(backgroundColor: Colors.orange),
      scaffoldThemeData : new ScaffoldThemeData(backgroundColor: Colors.green, 
                                                fontSize: 18.0),
      accentThemeData: new AccentThemeData(color: Colors.yellow),
      primaryThemeData: new PrimaryThemeData(colorDark: Colors.slategray)
    )
```
When wrapping Widgets in Themes the scaffold and the scaffold appBar will take on the theme from the parent ThemeData :
```dart
    new Theme(
      scaffoldThemeData: new ScaffoldThemeData(backgroundColor: Colors.purple),
      appBarThemeData: new AppBarThemeData(backgroundColor: Colors.blue),
      new Scaffold(
        appBar: new AppBar(
            title: new Text(widget.title),
          ),
      );
    );
```
We can also override any part of those themes :
```dart
    new Scaffold(
      scaffoldThemeData: new ScaffoldThemeData(backgroundColor: Colors.cyan),
      appBar: new AppBar(
            appBarThemeData: new AppBarThemeData(backgroundColor: Colors.indigo),
            //backgroundColor : Colors.indigo, <- This will be deprecated
            title: new Text(widget.title),
          ),
    );
```
This would improve the current situation because :
1. You can use the same themes with the same names throughout your app (use a `const ScaffoldThemeData` for example)
2. Improve consistency e.g. Scaffold has a `backgroundColor` attribute, but in `ThemeData` it is called `scaffoldBackgroundColor`
3. By deprecating all the individual color attributes we ensure devs will be using Themes from the start.

This idea has a similar theme :) to my previous scheme :
[Idea: Reduce nesting in Flutter](https://github.com/flutter/flutter/issues/16714)

**Comment by Rockvole** [comment]
Here are some issues I found which could be related to (or improved by) my idea :
https://github.com/flutter/flutter/issues/16277
https://github.com/flutter/flutter/issues/14598
https://github.com/flutter/flutter/issues/13962
https://github.com/flutter/flutter/issues/12845
https://github.com/flutter/flutter/issues/12681
https://github.com/flutter/flutter/issues/9148
https://github.com/flutter/flutter/issues/3856
https://github.com/flutter/flutter/issues/2222

**Comment by Hixie** [comment]
cc @HansMuller this could be useful to you given your work on updating the theming mechanism. Please close this issue once you have taken its suggestions and linked bugs into account (i.e. once it is no longer actionable).

@Rockvole thanks for the ideas!

**Comment by HansMuller** [comment]
@Rockvole - thanks for all of the suggestions about improving the Material theme system and please accept my apology for not having addressed this issue for such a long time. We are undertaking an long-term project to improve the theme system, it's described here [flutter.dev/go/material-theme-system-updates](https://flutter.dev/go/material-theme-system-updates). The doc is open for comments if you're still interested in this topic.

**Comment by Rockvole** [comment]
Thanks @HansMuller for taking an interest in my issue. 
The document looks like it would provide an improvement. I don't feel confident to provide comments since I have not worked in Flutter for over a year so I am out-of-date with the framework updates (have been part-time on a dart project instead).
