### ISSUE TITLE
firebase_auth on iOS getIdToken() causes app to crash?

### ISSUE THREAD

**Issue by vagrantrobbie** [flutter/flutter#17022]
## Steps to Reproduce

After signing in a user, I call getIdToken() but this causes the app to crash on iOS with no error sent to Flutter debug.

I have wrapped it in a try{} catch to try and catch any error but this doesn't work.

I am using firebase_auth 0.5.5. This works fine on Android

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by vagrantrobbie** [comment]
Thanks for replying. I don't think this should matter but every time I run brew install --HEAD libimobiledevice I am told it is already installed. I can definitely discover iOS devices fine. 

[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
      To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy out of date (1.9.2 is required). To upgrade:
        brew upgrade ios-deploy
[✓] Android Studio (version 2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[!] VS Code (version 1.9.1)

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by vagrantrobbie** [comment]
Works now

Thanks for following up!

**Comment by zoechi** [comment]
Glad to hear. Thanks!
