### ISSUE TITLE
How can I set startup page?    and  is there a recommend  way to manage my page?

### ISSUE THREAD

**Issue by Solomon-8** [flutter/flutter#17020]
each time i start a flutter app,i will see a white screen for seconds.

it's unacceptable for an nice app.

i want to use a picture to make the startup page more beautiful

how can i do it?    
is there an example?(i mean code,such as in pub.dartlang.org i can find example in each package's github )

is there a recommend way to manage my page?

**Comment by Solomon-8** [comment]
I have found way to set startup page 
thx
i see the AndroidManifest.xml found there is annotation to help me to solve this problem.

but i still need help with the second problem

is there a recommend way to manager my pages?

**Comment by zoechi** [comment]
Did you check https://stackoverflow.com/questions/43879103/adding-a-splash-screen-to-flutter-apps/48101776#48101776 ?
