### ISSUE TITLE
Loading Uint8List from bundle for Image display shouldn't cause exception

### ISSUE THREAD

**Issue by jerrywell** [flutter/flutter#17038]
## Steps to Reproduce

In very high frequency scrolling case, the Image widget will be broken. reproduce steps:
1. build with following example
2. in list view, keep high frequency scrolling to make image keep triggering bundle loading.

both issue happened in Dart 1 and 2 compilation. It should be in the framework level. (we don't have this issue in Beta 1). If we cache the loaded [bytes] in [TestImageWidgetState], the exception will disappear. so there are two issues

1. image.memory loading a bytes list from bundle will throw exception in high frequency access.
2. log for exception should show stack trace or advanced info.

Following is the sample code and image(according to above test result, any image is acceptable i think).

Workaround: cache the bytes in memory.

Thank you very much.

```
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      appBar: new AppBar(
        title: new Text('Test'),
      ),
      body: new Center(
        child: new ListView(
          children: new List.filled(300, new Container(
            child: new Column(
              children: <Widget>[
                new TestImageWidget(),
                new Container(
                  height: 1.0,
                  color: Colors.black,
                )
              ],
            )
          )),
        ),
      ),
    ),
  ));
}

class TestImageWidget extends StatefulWidget {

  @override
  State createState() {
    return new TestImageWidgetState();
  }
}

class TestImageWidgetState extends State<TestImageWidget> {
  Uint8List bytes;

  @override
  void initState() {
    super.initState();
    rootBundle.load('assets/image-2.jpg').then((data) {
      if (mounted)
        setState(() {
          bytes = data.buffer.asUint8List();
        });
    });
  }

  @override
  Widget build(BuildContext context) {
    final decoration = new BoxDecoration(
      image: bytes == null ? null :
      new DecorationImage(
        image: new MemoryImage(bytes),
      ),
    );

    return new Container(
      width: 30.0,
      height: 30.0,
      decoration: decoration,
    );
  }

}
```

![image-2](https://user-images.githubusercontent.com/4530697/39351101-f841bafe-4a32-11e8-892f-9320259e5cf0.jpg)

## Logs
```
E/flutter ( 7985): [ERROR:flutter/lib/ui/painting/codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter ( 7985): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter ( 7985): The following _Exception was thrown resolving an image codec:
I/flutter ( 7985): Exception: operation failed
I/flutter ( 7985): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter ( 7985): [ERROR:flutter/lib/ui/painting/codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
E/flutter ( 7985): [ERROR:flutter/lib/ui/painting/codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter ( 7985): Another exception was thrown: Exception: operation failed
I/flutter ( 7985): Another exception was thrown: Exception: operation failed
E/flutter ( 7985): [ERROR:flutter/lib/ui/painting/codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
E/flutter ( 7985): [ERROR:flutter/lib/ui/painting/codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter ( 7985): Another exception was thrown: Exception: operation failed
```
## Flutter Doctor

[✓] Flutter (Channel master, v0.3.6-pre.36, on Mac OS X 10.13.4 17E199, locale en-TW)
    • Flutter version 0.3.6-pre.36 at /Users/jerry/Documents/project/flutter
    • Framework revision 4033937c89 (5 hours ago), 2018-04-26 19:54:39 -0700
    • Engine revision e11905c6e5
    • Dart version 2.0.0-dev.50.0.flutter-8d4074175f

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/jerry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] Connected devices (3 available)
    • SM G930F                  • ce01171121b67a1a02                       • android-arm64 • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5556                            • android-x86   • Android 8.0.0 (API 26) (emulator)
    • JWC                       • fd083d452b93623e60d9f8d57a47c8966899dfe3 • ios           • iOS 11.3

• No issues found!

**Comment by jason-simmons** [comment]
This should be fixed by https://github.com/flutter/engine/commit/b6be9377c58c488afea042a1b0ed8910b158c319

(That change hasn't reached the `master` channel yet but should be rolled out in a few days)

**Comment by jerrywell** [comment]
it won't happen anymore after apply the fix commit few days ago. thanks @jason-simmons :)
