### ISSUE TITLE
Flutter build including very old version of asset files from seemingly nowhere

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter#17037]
This is an issue I can't reproduce 100% of the time.

I am trying to develop an app using Flutter, where all remote connections are mocked. All API calls will actually return local asset files. I am developing on Windows 10, only Android devices are used for testing.

At some point I observed some weird behavior of the list not showing all loaded items properly (e.g. I expected 2 items but only 1 is shown), but there is no error in the log. Strangely I can see all items showing correctly in some builds, but not in others (the JSON asset files are untouched between the builds).

From the debugger, it appears that the loaded items are actually showing correctly. The problem is that the JSON file is indeed returning only one item - it is an old version of the file, and a couple of changes (like adding more items) has been made since then.

So I started cleaning up stuffs by deleting the `bulid/` and `ios/Flutter/flutter_assets/` directories where a copy of the asset files are found, did a search to ensure that only the new version exists, and rebuild again. I also deleted the `.pub` and `.dart_tool` directories. I even removed the .git directory. But the old JSON files still sometimes got included and served! It seems that the file came from nowhere, which is a bit scary.

In addition to using the debugger I also ran the following adb command to see the old version of the json file:
`adb shell run-as com.myapp`
`cat /data/user/0/com.myapp/app_flutter/flutter_assets/assets/mock/category1/subcategory1/items.json`

To alleviate this, I changed the path of the files as a temporary measure. 

Sorry that information is probably lacking, but the trickiest part is that it only appears in random builds. I'll try to see if I can 100% reproduce this.

## Flutter Doctor

```
[√] Flutter (Channel beta, v0.3.1, on Microsoft Windows [Version 10.0.16299.402], locale zh-HK)
    • Flutter version 0.3.1 at C:\flutter
    • Framework revision 12bbaba9ae (7 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\CY\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio 3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[!] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio 3
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Android Studio (version 2.1)
    • Android Studio at C:\Android\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] VS Code, 64-bit edition (version 1.19.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • Nexus 5X • 00e1c63e154fae10 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 3 categories.
```

**Comment by tamcy** [comment]
Well, I have tested the code on 3 devices (1 emulator & 2 real devices, all running Android). On one of the real device (Nexus 5X) I also tried building a release apk (`flutter build apk`), with the old version uninstalled before installing a new one using the `adb install` command. Same issue. It really sounds weird.

**Comment by tamcy** [comment]
After some investigation, I'm certain that flutter is reading my asset files correctly. And I've extracted the APK to investigate the files inside `flutter_assets` directory to confirm that files are the most-update one. So I fired up a "clean" emulator that never ran this app before. Expectedly, now the files are loaded correctly!

So it looks like there are leftovers in the emulator/phone which could not be replaced nor removed even by uninstalling the app.

**Comment by tamcy** [comment]
Okay... I managed to make the actual, updated assets being loaded, for once:

1. Install and start app
2. Observe that old JSON is loaded
3. Run the following commands:
```
adb run-as com.myapp
rm -rf /data/data/com.myapp/app_flutter
```
4. Reopen app, observe that new JSON is loaded correctly. Kill and restart app. New JSON still loaded correctly.
5. Uninstall and reinstall app again
6. Restart app. Observe that old JSON is loaded.

BTW, I also noticed another unexpected behavior - the saved user credentials still retains when the app is uninstalled and installed again. makes me wonder, is Flutter doing something globally in the system?

**Comment by handras** [comment]
Today I discovered the same artifact with images. I have a gallery that shows static images. 
I decided to resize them, pressed hot reload and the images showed up resized. After performing a full restart the old images are loaded.
Flutter clean does not help.

**Comment by robertonic** [comment]
I have the same problem with JSON files.  After changing these it is almost impossible to predict which version will be used. Sometimes Flutter shows the changes, sometimes it reverts to an earlier version.

**Comment by zoechi** [comment]
@tvolkert

**Comment by robertonic** [comment]
![image](https://user-images.githubusercontent.com/7998815/44632260-59ed7b80-a96f-11e8-91b3-344ced4226c1.png)

When running in IntelliJ IDEA hitting 'hot restart' rather than 'hot reload'  uses the latest version of a JSON file.

**Comment by benbarbersmith** [comment]
As a workaround, renaming the asset solved the problem - but the old asset (now with an unused/unreferenced filename that does not appear in pubspec.yaml) continues to be accessible from code after following the reproduction steps in my last comment. To repeat: uninstalling the app, then freshly installing it, allows me to access old assets which are not included in the latest build.

**Comment by ThinkDigitalRepair** [comment]
I've been having this issue with old code running. If I rebuild, I have to hot-restart and then it'll load the new code. This makes me think that my bug fixes aren't working...

**Comment by tamcy** [comment]
To avoid confusion, I want to clarify that this issue is about an *older version* of an asset file being included in a *fresh build*. It's nothing to do with source code or hot restart and hot reload.

**Comment by zoechi** [comment]
Are you still experiencing this?
I haven't seen this (or similar issues) mentioned since quite some time.

**Comment by tamcy** [comment]
I avoided storing asset files this way by then, and if needed I would rename the asset (just as @benbarbersmith said). The thing is, as this happens randomly I just feared that this will occur in production, and we still have no clue of the possible causes. This makes me feel unconfident. Sorry for not being able to confirm if this is really resolved.

**Comment by ColbyMaloy** [comment]
Having a similar problem with .json files im using in a a lottie package. 

using the asset path of Gong.json but the Timer.json is what is showing. I've completely deleted Timer from my project, cleaned the app on the device, deleted it, ran flutter clean, changed the name of the file, emptied my recycle bin, chugged a monster energy, dragged it back into assets folder, flutter run and it STILL uses an animation that shouldn't exist.

**Comment by naco-siren** [comment]
Experiencing exactly the same issue.
`flutter clean` **sometimes** works though

**Comment by honzasvasek** [comment]
Same on an Opportunity F5, developing on Ubuntu.

**Comment by milindmantri** [comment]
Having the same issue, when using image assets.
Tried, clearing cache/storage, uninstalling for all users, `flutter clean` and then re-installing.

Still doesn't work. I'm on the `stable` channel. Have tried the same for `master`.
Changing the assets while keeping the same asset names for newer builds shows up old assets, when testing. This is very strange.

**Comment by jonahwilliams** [comment]
I think this is ultimately the same issue as https://github.com/flutter/flutter/issues/16604, since assets are part of the build process.

**Comment by EzeBera** [comment]
I'm having the same problem
