### ISSUE TITLE
Support keyboard cursor move on iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17030]
On iOS, 3d force pressing and moving around on the keyboard moves the cursor in text fields. Recreate that effect for Flutter text fields.

**Comment by lukepighetti** [comment]
Started my closed alpha a couple weeks ago and this was the first complaint from iOS camp. It's ubiquitous for text editing on iOS now. Please support.

**Comment by matthew-carroll** [comment]
@xster I think the effect is as follows:

Long press: Cursor appears at finger position and circle magnifier shows up. Left/right motion moves cursor.

Long press then Force press: The current word is selected and the round magnifier shows up.  Left/right motion expands selection to the left/right.

Immediate force press: Seems to select the current word, elevate that word into a draggable, and then allow transposing of that word.

Is this ticket aimed any one particular effect?

**Comment by matthew-carroll** [comment]
Talked with @xster.  This ticket is about force touching the keyboard and then being able to drag around the keyboard and have the cursor in the active text field move around accordingly.

**Comment by xster** [comment]
It's currently not in works for Q4 but we understand it's an important item.

**Comment by richgoldmd** [comment]
The text editing experience is jarring on iOS - no magnifying glass and no 3D Touch . iOS users notice the missing features almost immediately.

**Comment by ykphuah** [comment]
Note also that in iOS12, the same effect can be started by long pressing on the spacebar.

**Comment by lukepighetti** [comment]
@richgoldmd Whenever I show someone on iOS a flutter app they find this within 30 seconds of using the app.

**Comment by ykphuah** [comment]
Would be good if we know this is something that is technically possible or not. 

I noticed that the selection and the bubble when we have selected is "emulated" in the iOS, hence they appear slightly different than the default one from the OS. So it does felt like this cursor move thing can be supported as well eventually.

It is very important for my text input heavy app though, and causing me to re-evaluate moving to native just because of this one issue.

**Comment by lukepighetti** [comment]
I will say that I've moved my chat app to a PWA until Flutter can resolve emojis and text input on iOS.

**Comment by jslavitz** [comment]
@ykphuah – This feature is very much technically possible and will be added within the three weeks. We are extremely sorry for the delay!

**Comment by xster** [comment]
Reopening since the PR was reverted

**Comment by alexandergottlieb** [comment]
Just wondering if there are plans to bring this to the numeric keyboard too? (`TextInputType.numberWithOptions(...)`)

**Comment by bulldriver** [comment]
So what's the solution?

**Comment by lucien144** [comment]
This doesn't seem to be working. Is this in the current stable channel (v1.17) already?

**Comment by lukepighetti** [comment]
> This doesn't seem to be working. Is this in the current stable channel (v1.17) already?

It definitely should be.

**Comment by lucien144** [comment]
@lukepighetti Doesn't look to me this is working. If I compare other native app with Flutter app, the cursor doesn't work same. The magnifying isn't there. Hasn't this been just reverted? https://github.com/flutter/flutter/pull/25352

**Comment by lukepighetti** [comment]
This issue covered the use case where you force press on the keyboard and a cursor appears in the text field and you can move it around by moving your finger around on the keyboard.

**Comment by lucien144** [comment]
@lukepighetti Ok. Do you have any info regarding the floating cursor by any chance? Even though you can move the cursor now it still doesn't feel native to some of my users... Thanks.

**Comment by lukepighetti** [comment]
You'll need to find or create another issue for text field functionality that isn't covered by this particular issue.

**Comment by krema** [comment]
On iOS it is possible to  _tap-and-hold the spacebar_ and then move your finger around to move the text cursor in the text. 
This only works until you reach the point where the TextField has to be scrolled with the cursor.

The _tap-and-hold the text_ movement works by the way. The only thing not working is the tap-and-hold the spacebar movement?
