### ISSUE TITLE
TextFormFlield does not look native on Android

### ISSUE THREAD

**Issue by moodstubos** [flutter/flutter#17040]
## Steps to Reproduce

- create new project
- add a TextFormField widget
- run and compare with android native

**Native Android**
-> new Android Studio project - selected "Login Activity"-template

![image](https://user-images.githubusercontent.com/5072232/39352289-8b610300-4a04-11e8-82fc-7393ec6fc025.png)

**Flutter**
-> new clean project - TextFormField added:
![image](https://user-images.githubusercontent.com/5072232/39352420-eea45728-4a04-11e8-8d52-69fdbd232972.png)

![image](https://user-images.githubusercontent.com/5072232/39352374-cc122924-4a04-11e8-946e-68006e812ce1.png)

## Logs

Launching lib/main.dart on Nexus 5 in debug mode...
Initializing gradle...                                       0,8s
Resolving dependencies...                                    1,1s
Running 'gradlew assembleDebug'...                           7,8s
Built build\app\outputs\apk\debug\app-debug.apk (30.4MB).
Installing build\app\outputs\apk\app.apk...                  9,4s
I/FlutterActivityDelegate( 8200): onResume setting current activity to this
Syncing files to device Nexus 5...                           2,9s

To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Nexus 5 is available at: http://127.0.0.1:8104/
For a more detailed help message, press "h". To quit, press "q".

Run `flutter analyze` and attach any output of that command also.

Analyzing C:\Users\x\Projekte\x\flutter\testapp...
No issues found!

## Flutter Doctor

[√] Flutter (Channel beta, v0.3.1, on Microsoft Windows [Version 10.0.16299.371], locale de-DE)
    • Flutter version 0.3.1 at C:\Users\x\Projekte\SDK\flutter
    • Framework revision 12bbaba9ae (7 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\x\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.22.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.2

[√] Connected devices (1 available)
    • Nexus 5 • 02cd7a87d023fb75 • android-arm • Android 6.0.1 (API 23)

• No issues found!

**Comment by moodstubos** [comment]
I think my report is a duplicate of this one:
https://github.com/flutter/flutter/issues/16704

sorry for that.
Basically I think a clean TextFormField should look native without any style adjustments

**Comment by moodstubos** [comment]
Update:
It seems it is not possible to change the space between input text and label (space between label "Email" and text "Test" in the sample above). contentPadding only impacts the padding above label. Therefore it is NOT possible to get a TextField that fits to the material design guidelines. It is a great pity :-(

see:
https://material.io/guidelines/components/text-fields.html#text-fields-layout

**Comment by HansMuller** [comment]
As you know the visual changes to InputDecorator layout were introduced in early January, https://github.com/flutter/flutter/pull/13734. They were based on an extensive program of usability testing by the Material design team. In the coming weeks you should see other similar implementations as well as matching updates to the Material spec itself.

**Comment by moodstubos** [comment]
brilliant!
It's not a bug, it's a feature :-)

Thank you for your answer. And thank you for this great work. I totally love flutter.
