### ISSUE TITLE
iOS Arguments on Launch not working

### ISSUE THREAD

**Issue by eikebartels** [flutter/flutter#17043]
## Steps to Reproduce

Add some `Arguments on Launch` to your Schema in iOS for example `-FIRAnalyticsDebugEnabled`

Run your application trough `flutter run` or Android Studio. 

This is not working at all. 

`To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled`

If I run the project directly from Xcode it works.

## Logs

`To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled`

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E199, locale en-DE)
    • Flutter version 0.3.1 at /Users/eikebartels/Applications/flutter
    • Framework revision 12bbaba9ae (7 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/eikebartels/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
```

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by eikebartels** [comment]
Yes it is

**Comment by zoechi** [comment]
Where do you add these parameters (I haven't done much iOS stuff yet).

**Comment by eikebartels** [comment]
![screen shot 2018-07-26 at 17 22 48](https://user-images.githubusercontent.com/767979/43271722-91a6c728-90f8-11e8-94d7-74618622666c.png)


![screen shot 2018-07-26 at 17 22 53](https://user-images.githubusercontent.com/767979/43271721-918cbd06-90f8-11e8-94a3-cb8e02b57742.png)

**Comment by almeynman** [comment]
Is there any workaround for now?

**Comment by almeynman** [comment]
The workaround I used is to run the app from XCode.

**Comment by vargavince91** [comment]
One place where users might need it is the Firebase Analytics [event debugging](https://firebase.google.com/docs/analytics/debugview).  (see iOS steps)

**Comment by stephenhuey** [comment]
Another place it would be helpful is for dynamic links diagnostics:

https://firebase.google.com/docs/dynamic-links/debug#ios_self-diagnostic_tool

It should be possible to call using a platform channel like so:

https://flutter.dev/docs/development/platform-integration/platform-channels

But this shows up in the logs if you try to call the method:

```
To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
```

**Comment by williamdias** [comment]
The problem persists in flutter v1.7.8+hotfix.3.

**Comment by joepb** [comment]
I added the options in XCode following instructions of @eikebartels and ran it successfully from XCode.
After closing up XCode and switching back to VSCode, the arguments seems to persist. Not sure why it works for me, though.

```
Xcode build done.                                           55,5s
6.5.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60004000 started
6.5.0 - [Firebase/Analytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
	[C1.1 F0F6CD3D-0209-427B-8F81-0061CD77D4A5 192.168.43.250:51249<->172.217.17.138:443]
	Connected Path: satisfied (Path is satisfied), interface: en1
	Duration: 0.862s, DNS @0.003s took 0.006s, TCP @0.013s took 0.033s, TLS took 0.696s
	bytes in/out: 4699/1050, packets in/out: 10/9, rtt: 0.059s, retransmitted packets: 0, out-of-order packets: 0
```

Not sure if relevant, but maybe it helps:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.13.6 17G65, locale nl-NL)
    • Flutter version 1.7.8+hotfix.4 at /Users/joep/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/joep/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone XR • 48E0E1CE-F9C8-44C6-8DBF-DDEE8EFBF9F8 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by jlepocher-dev** [comment]
Problem persists in Flutter 1.9.1+hotfix.2

**Comment by kroikie** [comment]
@eikebartels

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/844. Any further collaboration will be done there.

**Comment by blasko** [comment]
Still seeing this issue with no obvious fix or resolution almost 1 year on. Any progress or information that could potentially lead to a resolution?

**Comment by vargavince91** [comment]
@blasko The ticket was moved to https://github.com/FirebaseExtended/flutterfire/issues/844 and then was closed... However, there's a new issue that tracks the same request/complaint https://github.com/FirebaseExtended/flutterfire/issues/1586

**Comment by blasko** [comment]
Thanks for the update @vargavince91 . Unfortunately both linked issues are either locked or closed. 

As a long shot, I reached out to JetBrains to see if there was any potential input from an IntelliJ perspective (passing in command line arguments via main build tool other than XCode), but understandably since all Flutter related components are third-party, they didn't have much to contribute.

Seems we're at an impasse with all these discussions closed on the topic.
