### ISSUE TITLE
Show time taken during flutter start

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1704]
Right now when doing "flutter start" it looks like:

```
Building APK...
Signing the APK using the debug keystore.
Generated APK to build/app.apk.
Starting lib/main.dart on Nexus 6...
Installing app.apk on device.
```

It would be nice if it ended up being:

```
Building APK... (3.2 seconds)
Signing the APK using the debug keystore... (2.1 seconds)
Installing app.apk on device... (5.8 seconds)
Starting lib/main.dart on Nexus 6... (1.0 seconds)
```

**Comment by eseidelGoogle** [comment]
@jason-simmons did some recent investigation into start's timings.  I think he's moved on to other things at the moment, but he may have context for someone who tackles this or want to do it himself at some point.

**Comment by jason-simmons** [comment]
Running the flutter tool with the --verbose flag will show timestamps for some of the major steps

**Comment by eseidelGoogle** [comment]
I think -v addresses this.  Closing, please re-open if you disagree.

**Comment by Hixie** [comment]
This is about showing it even without `-v`.

**Comment by Hixie** [comment]
This is done now.
