### ISSUE TITLE
Firebase plugins versioning

### ISSUE THREAD

**Issue by charafau** [flutter/flutter#17046]
Hi! I noticed that currently firebase plugins (firebase_storage, firebase_auth) have different versions. On android all plugins (i.e. for support, firebase) from given group have the same version. The reason for this is that flutter plugin adds specific version of firebase to android projects, so you don't know if firebase version is the same. 

This is only my suggestion but I think it would be better if all plugins had the same version.

**Comment by zoechi** [comment]
My suggestion https://github.com/flutter/flutter/issues/12945#issuecomment-349601132
and let `pub` figure matching versions out.

**Comment by fmatosqg** [comment]
Starting with v 15.0 they apparently are removing incompatibilities. The instructions seem to apply changes to the app's gradle file,as shown near the end of the following post :
https://android-developers.googleblog.com/2018/05/announcing-new-sdk-versioning.html?m=1
