### ISSUE TITLE
Issue from website page Write Your First Flutter App

### ISSUE THREAD

**Issue by nikhil-seth** [flutter/flutter#17049]
From URL: https://flutter.io/get-started/codelab/
In Step 2: sub point 4:
    `child: new Text(wordPair.asPascalCase),`
This Code Produces error when typed

**Comment by zoechi** [comment]
What's the error that it produces?
Can you please add the output of `flutter doctor`?

**Comment by Sfshaza** [comment]
Fixed in PR https://github.com/flutter/website/pull/1124

**Comment by yrstruely** [comment]
I had the same problem, so I used the following code instead:

`generateWordPairs().take(1).first.asPascalCase`
