### ISSUE TITLE
Cursor didn't move to the new line until next character input

### ISSUE THREAD

**Issue by jerrywell** [flutter/flutter#17041]
## Steps to Reproduce

reproduce steps:
1. type "boy" and press enter button
2. the cursor is at the end of "y" of boy
at this moment, the new line is created (this behavior is fixed in https://github.com/flutter/flutter/issues/13765)
3. type any word and the cursor is show on the new line.

the right behavior should be:
after the step 1, the cursor should be at the beginning of newline.

I already tested it on Samsung S7 and simulator API 26 with google service.

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'TextField',
      home: new Scaffold(
        appBar: new AppBar(),
        body: new TextField(maxLines: null),
      ),
    );
  }
}
```

## Flutter Doctor

[✓] Flutter (Channel master, v0.3.6-pre.36, on Mac OS X 10.13.4 17E199, locale en-TW)
• Flutter version 0.3.6-pre.36 at /Users/jerry/Documents/project/flutter
• Framework revision 4033937 (5 hours ago), 2018-04-26 19:54:39 -0700
• Engine revision e11905c6e5
• Dart version 2.0.0-dev.50.0.flutter-8d4074175f

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
• Android SDK at /Users/jerry/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-27, build-tools 26.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 9.2, Build version 9C40b
• ios-deploy 1.9.2
• CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 23.2.2
• Dart plugin version 173.4700
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
• IntelliJ at /Applications/IntelliJ IDEA CE.app
• Flutter plugin version 23.2.3
• Dart plugin version 181.4445.29

[✓] Connected devices (3 available)
• SM G930F • ce01171121b67a1a02 • android-arm64 • Android 7.0 (API 24)
• Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.0.0 (API 26) (emulator)
• JWC • fd083d452b93623e60d9f8d57a47c8966899dfe3 • ios • iOS 11.3

• No issues found!

**Comment by leisure520** [comment]
i had the same  issues  with you.

**Comment by d-silveira** [comment]
me too

**Comment by zoechi** [comment]
I think this is a dup of #15572
I'm going to close this one because the other one has a bit more discussion.
