### ISSUE TITLE
support for firebase_performance HTTPMetric

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#17052]
The firebase_performance plugin added in https://github.com/flutter/plugins/pull/508 doesn't include an analogue for the `HTTPMetric` class. 

The example app should include working code that uses it by overwriting [`createHttpClient`](https://api.dartlang.org/dev/2.0.0-dev.35.0/dart-io/HttpOverrides/createHttpClient.html). Something like this sketch:

    final oldCreateHttpClient = createHttpClient;
    createHttpClient = () => new _MyHttpClient(oldCreateHttpClient());

    class _MyHttpClient extends BaseClient {
      _MyHttpClient(this._inner);

      final Client _inner;

      @override
      Future<StreamedResponse> send(BaseRequest request) async {
        final HttpMetric metric = new HttpMetric(url: request.url, method: request.method)
         ..start();
        StreamedResponse result;
        try {
          result = await _inner.send(request);
          metric.responseCode = result.responseCode;
          metric.responsePayloadSize = result.size;
          metric.responseContentType = result.contentType;
          return result;
        } finally {
          metric.stop();
        }
      }
    }

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/843. Any further collaboration will be done there.
