### ISSUE TITLE
Remove all Dart1 support

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#17051]
Once all the Dart tooling is flipped over to Dart2 by default, we should remove our Dart1 support.

cc @cbracken

**Comment by cbracken** [comment]
Reverted again in #18460.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/17804

**Comment by cbracken** [comment]
See also #18278.

**Comment by cbracken** [comment]
All Dart 1 support has now been removed from the framework.

**Comment by cbracken** [comment]
As of flutter/engine#5621, Dart 1 support has been removed from the engine.
