### ISSUE TITLE
I want to disable the scrollable when using showModalBottomSheet

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#17066]
Because I add a ListVIew on the BottomSheet, and I noticed it is hard to detect the click action in the ListIView , I doubt that the reason is the BottomSheet also detects the drag action, so is there a way to disable it?

**Comment by zoechi** [comment]
@realcarlos is this still an issue or can it be closed?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by dnfield** [comment]
I believe whatever work is done for #497 should make the challenges here better - but if @realcarlos  has any clarifications to add it could help.
