### ISSUE TITLE
Add an option to dump render tree to a file instead of slowly piping it through the terminal

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17061]
Sometimes it takes so long to pump them out that it times out `TimeoutException: Request to Dart VM Service timed out: ext.flutter.debugDumpRenderTree({isolateId: isolates/812973255})`

**Comment by jonahwilliams** [comment]
A JSON format would be nice too...

**Comment by Hixie** [comment]
Now that we send the data really quickly to the terminal, this seems less critical.
