### ISSUE TITLE
Google Sign in Error

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#17065]
E/flutter (14695): type 'Future<dynamic>' is not a subtype of type 'Future<Null>' where
E/flutter (14695):   Future is from dart:async
E/flutter (14695):   Future is from dart:async
E/flutter (14695):   Null is from dart:core

**Comment by giovannilima262** [comment]
$ flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Linux, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

• No issues found!

**Comment by johnstef99** [comment]
same problem after flutter upgrade

**Comment by AnandGupta7866** [comment]
java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.internal.measurement.zziy@30fac2cb
W/ContextImpl(11146): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1105)
W/ContextImpl(11146): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1873)
W/ContextImpl(11146): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:562)
W/ContextImpl(11146): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.disconnect(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.zzcv(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.zzc(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzil.run(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzeq.run(Unknown Source)
W/ContextImpl(11146): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/ContextImpl(11146): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzgm.run(Unknown Source)
W/ContextImpl(11146): forgetServiceDispatcher failed for:
W/ContextImpl(11146): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.internal.measurement.zziy@30fac2cb
W/ContextImpl(11146): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1105)
W/ContextImpl(11146): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1873)
W/ContextImpl(11146): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:562)
W/ContextImpl(11146): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.disconnect(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.zzcv(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.zzc(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzil.run(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzeq.run(Unknown Source)
W/ContextImpl(11146): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/ContextImpl(11146): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzgm.run(Unknown Source)
W/InputMethodManager(11146): startInputInner : InputBindResult == null need restart
W/ContextImpl(11146): forgetServiceDispatcher failed for:
W/ContextImpl(11146): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.internal.measurement.zziy@30fac2cb
W/ContextImpl(11146): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1105)
W/ContextImpl(11146): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1873)
W/ContextImpl(11146): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:562)
W/ContextImpl(11146): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.disconnect(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.zzcv(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.zzc(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzil.run(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzeq.run(Unknown Source)
W/ContextImpl(11146): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/ContextImpl(11146): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzgm.run(Unknown Source)
I/flutter (11146): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
W/ContextImpl(11146): forgetServiceDispatcher failed for:
W/ContextImpl(11146): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.internal.measurement.zziy@30fac2cb
W/ContextImpl(11146): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1105)
W/ContextImpl(11146): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1873)
W/ContextImpl(11146): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:562)
W/ContextImpl(11146): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.disconnect(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.zzcv(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzik.zzc(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzil.run(Unknown Source)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzeq.run(Unknown Source)
W/ContextImpl(11146): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/ContextImpl(11146): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/ContextImpl(11146): 	at com.google.android.gms.internal.measurement.zzgm.run(Unknown Source)
