### ISSUE TITLE
flutter --release (Error)

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#17067]
$ flutter run --release
Building flutter tool...
Running "flutter packages get" in enigmaz2.0...              5.8s
Initializing gradle...                                       2.2s
Resolving dependencies...                                    1.1s
Launching lib/main.dart on A18 in release mode...
Running 'gradlew assembleRelease'...
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_auth:verifyReleaseResources'.
> com.android.builder.internal.aapt.AaptException: Failed to compile file /home/giovanni/Documentos/repoEnigmaZ/enigmaz2.0/build/firebase_auth/intermediates/res/merged/release/drawable-v21

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Gradle build failed: 1

**Comment by stemuk** [comment]
Hey @giovannilima262 , I ran into the same error today, could you maybe give me your solution to the problem since you closed this issue? Thanks a lot in advance!

**Comment by giovannilima262** [comment]
I remove the past build

**Comment by zoechi** [comment]
`flutter clean` does that.
