### ISSUE TITLE
How to add AnimatedList in ListView?

### ISSUE THREAD

**Issue by prashantnevase** [flutter/flutter#17079]
new ListView(
  children: <Widget>[
    new Text("Sometext"),
    new AnimatedList(
      key: _listKey,
      initialItemCount: _list.length,
      itemBuilder: _buildItem,
    ),
  ],
);

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue?
You want nested lists?
Can you please elaborate what exactly you try to accomplish and what the problem is?
