### ISSUE TITLE
Thai characters rendering wrong.

### ISSUE THREAD

**Issue by siteslave** [flutter/flutter#17076]
same with #16460 

![screen shot 2561-04-28 at 21 58 57](https://user-images.githubusercontent.com/526890/39397833-d49be2b6-4b2f-11e8-9ed0-41131426046c.png)

Flutter 0.3.6-pre.50 • channel master • https://github.com/flutter/flutter.git
Framework • revision c813eabf50 (9 hours ago) • 2018-04-27 22:55:51 -0700
Engine • revision 613aae032f
Tools • Dart 2.0.0-dev.50.0.flutter-cd0c4e4fe1

**Comment by siteslave** [comment]
@jukbot ปัญหาเดิมกับ #16460 หรือเปล่าครับ

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by siteslave** [comment]
Solved by using new font family :)
