### ISSUE TITLE
Can't run flutter test on a Mac with prebuilt binaries

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1707]
We just don't upload the binaries to google storage, but we could.

For now I'm disabling running `flutter test` tests on our new mac infra.

**Comment by eseidelGoogle** [comment]
Disabling `flutter test` on the mac bots for now: https://codereview.chromium.org/1678283004/

**Comment by abarth** [comment]
You can run `flutter test` on a mac if you have an engine build.  Re-titling.

**Comment by eseidelGoogle** [comment]
Just change this one line of code:
https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py#141
And we will suddenly have prebuilt binaries for the Mac. :)  I suspect you and I will do that today in our infra handoff.

**Comment by eseidelGoogle** [comment]
I briefly looked at adding this just now.  The (small) complexity is that SkyShell.app is a directory and the current UploadArtifacts logic expects files:
https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py#48

We can teach it to check if things are files or directories and call AddDirectory instead when necessary.

**Comment by eseidelGoogle** [comment]
https://codereview.chromium.org/1713153002/ was my attempt, likely wrong though.

**Comment by eseidelGoogle** [comment]
My impression is @chinmaygarde may have started on this too.

**Comment by eseidelGoogle** [comment]
Second attempt at adding SkyShell.app to the zip:
https://codereview.chromium.org/1884703002

**Comment by chinmaygarde** [comment]
Fixed with https://codereview.chromium.org/1991003003

**Comment by pylaligand** [comment]
Wow, I was just about to file a bug for this as I'm getting:
```
Cannot find Flutter shell at /foo/bar/blah/src/third_party/flutter/bin/cache/artifacts/engine/darwin-x64/sky_shell
```
Thanks!

**Comment by chinmaygarde** [comment]
@pylaligand You will have to wait a few minutes till https://github.com/flutter/flutter/pull/4028 lands.
