### ISSUE TITLE
GestureDetector : onLongPress eats up OnTapUp event.

### ISSUE THREAD

**Issue by Kartik1607** [flutter/flutter#17072]
I have setup the following code : 

```dart
  void onTapDown(TapDownDetails tap) {
    print('Down');
  }

  void onTapUp(TapUpDetails tap) {
    print('Up');
  }

  void onLongPress() {
    print('Hold');
  }

new GestureDetector(
        onTapUp: onTapUp,
        onTapDown: onTapDown,
        onLongPress: onLongPress,
        child: container
)
```

The result when I tap is 
```
Down
Up
```

When I hold the result is 
```
Down
Hold
```
Notice that **OnTapUp is not fired** when I remove my finger. Is this by design? Is so, why?

**Comment by rtorresware** [comment]
what happened with this one? is it closed because it's solved or was it a mistake?

**Comment by Kartik1607** [comment]
Mostly due to lack of any response.

**Comment by moodstubos** [comment]
Please reopen!
I need a callback when long press has been released. 
Or we should have a e.g. onLongPressReleased callback.

**Comment by zoechi** [comment]
@Kartik1607 if you still think it's a valid request, then you should keep it open.
The Flutter team is a bit swamped with the amount if issues created every day.

**Comment by zoechi** [comment]
cc @Hixie

**Comment by wenerme** [comment]
I also expected onTap instead of

```dart
Listener(
    onPointerUp: (e) {
        print("onPointerUp");
    },
    child: GestureDetector(
        onTap: _onTap,
        onLongPress: _onLongPress,
        child: CircleAvatar(
            radius: 30.0,
            backgroundColor: Colors.white,
        ),
    ),
),
```

**Comment by sandangel** [comment]
any idea on this. onTapUp is not being triggered in my case. I'm using dev channel 0.5.7

**Comment by Hixie** [comment]
I've got a patch that updates the documentation to make all this clearer:
https://github.com/flutter/flutter/pull/20647

If you want to know when a long-press is released, that would be onLongPressUp, which is what #18949 proposes to add. If anyone would like to run with that, that test mostly just needs a bit of cleanup and a test and then we can land it.

**Comment by Hixie** [comment]
I'm closing this since I'm updated the documentation. Please file a new bug if this still seems wrong to you. Thanks!
