### ISSUE TITLE
Firebase Admob - banner ad overlaps the drawer menu

### ISSUE THREAD

**Issue by riftninja** [flutter/flutter#17075]
Drawer Opened             |  Drawer Closed
:-------------------------:|:-------------------------:
![screenshot_20180428-131121](https://user-images.githubusercontent.com/23476626/39396451-556da036-4ae6-11e8-9b89-ad63b6b1e2a0.png)  |  ![screenshot_20180428-131113](https://user-images.githubusercontent.com/23476626/39396455-5da5965a-4ae6-11e8-9e3d-2bc7e6f8e6ca.png)

**Comment by zoechi** [comment]
Similar to #14222

**Comment by mulderpf** [comment]
This didn't seem to be a major issue when the banner is placed at the bottom, but to accommodate the iPhone X, I have been experimenting with putting the banner at the top of the page.  When I then open the drawer, the banner is in the way.  I'm fairly sure this is not acceptable according to policy.

![image](https://user-images.githubusercontent.com/13488242/49337237-270af180-f608-11e8-8cb7-cddd36f89a35.png)

**Comment by zoechi** [comment]
Duplicate of #14222

**Comment by kroikie** [comment]
@riftninja

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/842. Any further collaboration will be done there.

**Comment by Dabhipb** [comment]
Any updates?
