### ISSUE TITLE
Publish plugin in china

### ISSUE THREAD

**Issue by keluokeda** [flutter/flutter#17070]
i want publish my plugin ,but when i run `flutter packages pub publish`,i got this error
```
Waiting for your authorization...
Authorization received, processing...
It looks like accounts.google.com is having some trouble.
Pub will wait for a while before trying to connect again.
OS Error: Operation timed out, errno = 60, address = accounts.google.com, port = 53481
pub finished with exit code 69
```
how can i solve this problem.

**Comment by peng8350** [comment]
got the same problem,chinese too,I have already opened the agency

```
Waiting for your authorization...
Authorization received, processing...

```
No response

**Comment by zoechi** [comment]
Could you try to create an uploader first using `flutter packages pub uploader add`

Please also add the output of `flutter doctor`

**Comment by LiuC520** [comment]
how to add the output of flutter doctor?

**Comment by zoechi** [comment]
Run `flutter doctor -v` and post the output here.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by LiuC520** [comment]
IO  : Retry #5 for POST https://accounts.google.com/o/oauth2/token...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.2.0-dev.1.1.flutter-f9ebf21297
ERR : OS Error: Operation timed out, errno = 60, address = accounts.google.com, port = 51895
FINE: Exception type: SocketException
FINE: dart:_http                                _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36     IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_retry/http_retry.dart        RetryClient.send
    | package:pub/src/http.dart 194:43          _ThrowingClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart  ThrottleClient.send
    | package:http/src/base_client.dart 169:38  BaseClient._sendUnstreamed
    | ===== asynchronous gap ===========================
    | dart:async                                StreamView.listen
    | package:shelf/shelf_io.dart 64:14         serveRequests.<fn>
    | package:shelf/src/util.dart 24:20         catchTopLevelErrors
    | package:shelf/shelf_io.dart 63:3          serveRequests
    | package:pub/src/oauth2.dart 185:5         _authorize.<fn>
    | dart:async                                _completeOnAsyncReturn
    | package:pub/src/io.dart                   bindServer
    | ===== asynchronous gap ===========================
    | dart:async                                Future.then
    | package:pub/src/oauth2.dart 184:30        _authorize
    | package:pub/src/oauth2.dart 114:41        _getClient
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/oauth2.dart 112:26        _getClient
    | package:pub/src/oauth2.dart 83:10         withClient
    | package:pub/src/command/lish.dart 67:13   LishCommand._publish
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/command/lish.dart 64:18   LishCommand._publish
    | package:pub/src/command/lish.dart 143:13  LishCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:pub/src/command/lish.dart         LishCommand.run
    | package:args/command_runner.dart 194:27   CommandRunner.runCommand
pub finished with exit code 69

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:186:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand
(package:flutter_tools/src/commands/packages.dart:148:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:526:18)
#4      _asyncThenWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#8      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:642:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#10     Future._complete (dart:async/future_impl.dart:476:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:33:20)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure>
(dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback
(dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by LiuC520** [comment]
please help me how to Publish plugin

**Comment by LiuC520** [comment]
[✓] Flutter (Channel master, v1.1.4-pre.9, on Mac OS X 10.13.6 17G4015, locale
    zh-Hans-CN)
    • Flutter version 1.1.4-pre.9 at
      /Users/vittorio/Desktop/kaifa/flutter/flutter
    • Framework revision 3d8aec2b99 (8 hours ago), 2018-12-19 20:09:07 -0800
    • Engine revision 5ec8ef8509
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vittorio/Library/Android/sdk
    • Android NDK at /Users/vittorio/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/vittorio/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.2

[!] Android Studio
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

**Comment by zoechi** [comment]
@LiuC520  When you run `flutter packages pub publish` there is an URL printed that requests you to authenticate to Google. Did the authentication succeed?

**Comment by zoechi** [comment]
See also https://github.com/dart-lang/pub/issues/2008#issuecomment-445239186

**Comment by LiuC520** [comment]
i use shadowsocks , 
var proxy = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;";

Proxy all traffic

after copy long address to  broswer, tap the google account，redirect to 
http://localhost:62928/?code=4/vACjMFB6TtqeEMCj2rBV910NE4IKTl36mQtqxZJXXONXe1xHiUGaELhuPGenRP0fHf-FkQUEjF-p0aeufWL5sig&scope=openid%20email%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/plus.me 

port become 62928，but I set proxy to 127.0.0.1:1080.

**Comment by LiuC520** [comment]
so it can not authorize success

**Comment by joker-fu** [comment]
@LiuC520 请问你怎么解决的 我也publish不了

**Comment by LiuC520** [comment]
> @LiuC520 请问你怎么解决的 我也publish不了

我的也没有解决

**Comment by keluokeda** [comment]
@joker-fu 我试过了，还是不行，我用的翻墙是蓝灯

**Comment by WosLovesLife** [comment]
Further, I refer to https://teddysun.com/448.html This article builds the **L2TP/IPSec** service in my VPS.

**Comment by kangwang1988** [comment]
It's a pure network problem, stackoverflow is a better place to resolve this kind of support questions.
For me on MacOS, proxifier and shadowsocks would do the job very well.
Feel free to comment below, and we would like to reopen this issue when needed.

**Comment by kandroid29** [comment]
> MagicVPN

Is this VPN still working? I was also uploading the plugin on a Macbook Pro with failure

**Comment by 02002love** [comment]
> @LiuC520 我今天解决了，总结了一下 https://juejin.im/post/5c21d39ae51d4516da711073

老铁 你的帖子看不了额

**Comment by raoxudong** [comment]
Looks great! Are you ready to upload your package (y/n)? y
Uploading...
Invalid request method
pub finished with exit code 69


help

**Comment by MeDeity** [comment]
> @LiuC520 我今天解决了，总结了一下 https://juejin.im/post/5c21d39ae51d4516da711073

In my case (win7 env):
delete below configure:
```
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```
set proxy for termial(shadowsocks):
```
set http_proxy=http://127.0.0.1:1080
set https_proxy=https://127.0.0.1:1080
```
