### ISSUE TITLE
ImagePicker and StorageReference Functions need update in step 10 of Firebase for Flutter Codelab

### ISSUE THREAD

**Issue by Nomadjackalope** [flutter/flutter#17081]
When following Firebase for Flutter codelab in step 10 under "Enable sending images" heading

`ImagePicker.pickImage()` gives error: `The parameter source is required`
Fixed by replacing with `ImagePicker.pickImage(source: ImageSource.camera)`

In `StorageUploadTask uploadTask = ref.put(imageFile);` `ref.put(imageFile)` is depreciated
Fixed by replacing with `ref.putFile(imageFile);`

**Comment by Sfshaza** [comment]
This bug is against the old firebase+flutter codelab. It has been replaced. Closing.

(See @wmleler's comment in [Issue 17380](https://github.com/flutter/flutter/issues/17380) for more information.)
