### ISSUE TITLE
Firebase Messaging seems to be broken on Android / iOS

### ISSUE THREAD

**Issue by flschweiger** [flutter/flutter#17086]
## Steps to Reproduce

I just installed the Firebase Messaging plugin into my app and unfortunately it's not working at all. The only thing it can do is display a notification on Android when I send it through the Firebase console. 

Also the method ```FirebaseMessaging().getToken()``` will never return a token and does not throw an error. Listening to onTokenRefresh will never dispatch an event.

I'm on master right now (v0.3.6-pre.52) but also tried beta and dev.

## Logs

```
Launching lib/main.dart on iPhone von Frederik in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ABCD123456
Starting Xcode build...                                          
 ├─Building Dart code...                              0.9s
 ├─Assembling Flutter resources...                    1.4s
 └─Compiling, linking and signing...                  4.2s
Xcode build done.                                            8.5s
Installing and launching...                                      
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
4.13.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
4.13.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40200000 started
4.13.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
4.13.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
flutter: Listening for Tokens..
4.13.0 - [Firebase/Firestore][I-FST000001] The behavior for system Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
Syncing files to device iPhone von Frederik...               2.4s
```

## Flutter Doctor

[✓] Flutter (Channel master, v0.3.6-pre.52, on Mac OS X 10.13.4 17E202, locale en-DE)
    • Flutter version 0.3.6-pre.52 at /Users/frederikschweiger/Documents/Flutter
    • Framework revision 8860627b63 (11 hours ago), 2018-04-28 15:14:46 -0700
    • Engine revision 613aae032f
    • Dart version 2.0.0-dev.50.0.flutter-cd0c4e4fe1

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/frederikschweiger/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.0

**Comment by goderbauer** [comment]
I just ran the example app from that plugin on my android device and it seems to be working as expected. Did you do the firebase integration in your app as described in https://github.com/flutter/plugins/tree/master/packages/firebase_messaging#android-integration?

**Comment by flschweiger** [comment]
@goderbauer Yeah, I did everything as described. Mmmh, that's weird.

**Comment by 0916174** [comment]
I'm having the same problem. My apps run fine though, however, I do have some problems with Hot Reload now and again, but I don't know if this is related.

**Comment by Mahi-K** [comment]
hmm i'm having the same problem , but only occuring on iOS not on android, android no issues, only in iOS there's seems to be a problem.

**Comment by rihtam** [comment]
Exactly same issue here...
Except FirebaseMessaging().getToken() is returning token in debug and not in release apk.
Somebody please help.

**Comment by flschweiger** [comment]
FYI: works after calling configure() which seemed to be optional: https://github.com/flutter/flutter/issues/17699

**Comment by NewITCorp** [comment]
yes after calling configure(), gettoken() will return a token correctly.

**Comment by ffeu** [comment]
Hi, the problem described here calling `getToken` before `configure` is actually solved by flutter/plugins#869 . I'm using the latest versions both on Android and iOS and it's working.
I suggest closing this issue.

**Comment by flschweiger** [comment]
@ffeu Yup, thanks for the heads-up 👍

**Comment by kroikie** [comment]
@flschweiger

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/841. Any further collaboration will be done there.
