### ISSUE TITLE
pub run test fails in packages/flutter_tools in test/create_test.dart on Mac

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1709]
Only seems to happen on Mac.  Both on the bot and on my local machine.  Travis doesn't run our tests on Mac, hence we didn't catch this prior.

```
00:01 +22 -1: test/create_test.dart: create flutter-simple                                         
  Expected: <0>
    Actual: <69>
  
  package:test                 expect
  test/create_test.dart 38:33  defineTests.<fn>.<fn>.<async>.<fn>
  ===== asynchronous gap ===========================
  dart:async                   _Future.then
  test/create_test.dart 38:14  defineTests.<fn>.<fn>.<async>
  ===== asynchronous gap ===========================
  dart:async                   Future.Future.microtask
  test/create_test.dart        defineTests.<fn>.<fn>
  
00:01 +22 -1: Some tests failed. 
```

From a quick look at the code, looks like probably the pub get its running s returning 69?  I don't see how else it could be getting 69 from that code.

This is non-critical, I can just disable this test on Mac.

FYI @devoncarew

**Comment by eseidelGoogle** [comment]
Strange the test has a comment in it about a windows bot.  I'm not aware of any windows bot for this test.  Probably copypasta from some other test.

**Comment by devoncarew** [comment]
We (very briefly) used AppVeyor to test on windows.

**Comment by chinmaygarde** [comment]
I am no longer able to reproduce this.
![screen shot 2016-02-19 at 5 43 21 pm](https://cloud.githubusercontent.com/assets/44085/13193617/546a4382-d730-11e5-81c2-38eb31cbe5c1.png)
