### ISSUE TITLE
Make text on BottomNavigationBarItem optional

### ISSUE THREAD

**Issue by harrisonturton** [flutter/flutter#17099]
Hello,

Many apps have a bottom navigation bar that showcases icons, but no text (E.g. Instagram). I think this would be very useful to have in the Material library.

You can (kind of) emulate it by mixing Material & Cupertino widgets, but it's an imperfect solution.

**Comment by AppleEducate** [comment]
Could you pass in a empty string?

`new Text (""),`

**Comment by harrisonturton** [comment]
@AppleEducate  You can, but the padding/margin remains, causing the icons to be small & off-center.

**Comment by AppleEducate** [comment]
@harrisonturton Could you add `new Container(height: 0.0,) ` instead?

**Comment by harrisonturton** [comment]
@AppleEducate putting `new Container(height: 0.0)` is significantly better, but there is still surplus padding on the bottom.

To get around this issue, (and to simplify using bottom navigation -- the examples are so complex!) I've built this little widget:

```
import 'package:flutter/material.dart';

class BottomNavigation extends StatefulWidget<_BottomNavigationState> {
	BottomNavigation({
		this.children,
		this.items,
		this.fadeDuration
	});
	final List<Widget> children;
	final List<Widget> items;
	final Duration fadeDuration;

	_BottomNavigationState createState() => new _BottomNavigationState();
}

class _BottomNavigationState extends State<BottomNavigation> with TickerProviderStateMixin {

	int _currentIndex = 0;
	int _prevIndex = 1;
	List<Widget> _items;

	@override
	void initState() {
		super.initState();
		_items = List.generate(widget.items.length, (i) {
			return new InkWell(
				onTap: () => _changePage(i),
				child: widget.items[i]
			);
		});
	}

	void _changePage(int index) {
		if (index == _currentIndex) return;
		setState(() {
			this._prevIndex = _currentIndex;
			this._currentIndex = index;
		});
	}

	List<Widget> _buildTransitions() => List.generate(
		widget.children.length,
		(int i) => new AnimatedOpacity(
			opacity: _currentIndex == i ? 1.0 : 0.0,
			duration: widget.fadeDuration == null ? new Duration(milliseconds: 150) : widget.fadeDuration,
			child: widget.children[i]
		)
	).toList();

	Widget build(BuildContext context) {
		return new Scaffold(
			body: new Stack(
				children: _buildTransitions()
			),
			bottomNavigationBar: new Row(
				mainAxisAlignment: MainAxisAlignment.spaceAround,
				children: _items
			)
		);
	}
}
```

`children` are the different pages, and `items` are the items within the bottom nav bar. It'll fade transition between each page -- I've found it very useful.

**Comment by Th3Alch3m1st** [comment]
I am facing similar issue. I have tried this  `new Container(height: 0.0)` but there is still surplus padding on the bottom. 
![1525872254_tmp_screenshot_20180509-190117](https://user-images.githubusercontent.com/35175271/39816958-9f8d8bbe-53be-11e8-8085-d5e16ff4d0a3.png)

**Comment by baank** [comment]
Seriously BottomNavigationBar should be implemented like the example above.

Significantly easier and more flexible.

**Comment by zoechi** [comment]
@HansMuller

**Comment by xster** [comment]
Seems reasonable. Feel free to send us a PR.

**Comment by farukzahra** [comment]
+1 !!!

**Comment by hendricgc** [comment]
+1, very useful

**Comment by psyanite** [comment]
+1 Pretty Please 🍒

**Comment by IshanFx** [comment]
+1 It good to make text optional

**Comment by xster** [comment]
Big thanks for @artrmz for sending us a PR to make the text component of tabs optional for the Cupertino tab bar https://github.com/flutter/flutter/pull/22804. 

For Material, since it's explicitly against its specs to not have a tab label (https://material.io/design/components/bottom-navigation.html#anatomy), redirecting the remaining Material part to @willlarche for the Material specs.

**Comment by willlarche** [comment]
Material is tracking this in #22882 and PR #22956. We will keep titles mandatory for `Semantics`.

**Comment by xster** [comment]
Oh cool, thanks for the info @willlarche

**Comment by noman798** [comment]
+1, very useful

**Comment by willlarche** [comment]
That kinda changed. We are allowing titles to not be shown as long as the Semantic tree is identical with or without them.

**Comment by pedromassango** [comment]
Why it is still opened?

**Comment by willlarche** [comment]
The PR is still incomplete. https://github.com/flutter/flutter/pull/22956

**Comment by raveesh-me** [comment]
I achieved no labels using a column -> tab bar -> tab bar view combination. But it does not have options for activeIcon and inactiveIcon.
I want to use this in Scaffold's bottom navigation bar so using anything other than BottomNavigationBarItem is kind of out of the question.

Also, with having so many types of navigation bars and paging views that all do almost the same things in different contexts is quite confusing. There should have been a lower level of abstraction for this so that we could have more control and decide how these bars will behave.

**Comment by raveesh-me** [comment]
Also this stackoverflow answer...
https://stackoverflow.com/questions/40183239/remove-bottomnavigationview-labels

![screenshot 17](https://user-images.githubusercontent.com/15698263/52035247-12879e80-2550-11e9-90a2-87a2d8a94983.png)

**Comment by pedromassango** [comment]
I do not know wy it is taking so much time to add this feature. It looks simple to implement.

**Comment by alann-maulana** [comment]
I'm using `BottomAppBar` to achieve this `BottomNavigationBarItem` without label

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: body,
      bottomNavigationBar: new BottomAppBar(
          child: new Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: <Widget>[
              IconButton(
                  icon: Icon(Icons.home),
                  disabledColor: Colors.green,
                  onPressed: _currentIndex == 0
                      ? null
                      : () => setState(() => _currentIndex = 0)),
              IconButton(
                  icon: Icon(Icons.notifications),
                  disabledColor: Colors.green,
                  onPressed: _currentIndex == 1
                      ? null
                      : () => setState(() => _currentIndex = 1)),
              IconButton(
                  icon: Icon(Icons.settings),
                  disabledColor: Colors.green,
                  onPressed: _currentIndex == 2
                      ? null
                      : () => setState(() => _currentIndex = 2)),
            ],
          )
      ),//bottomAppBar
    );
  }
```

**Comment by dkobia** [comment]
Nicely done @alann-maulana - works so far.

**Comment by MohamedSayedKarim** [comment]
Text("",style: TextStyle(fontSize: 0),)
simply solved it
