### ISSUE TITLE
Hardware acceleration on Raspberry Pi (androidthings)

### ISSUE THREAD

**Issue by carnivorePaul** [flutter/flutter#17093]
Flutter apps are working on a Raspberry Pi 3 with AndroidThings!

*But not without some issues:*

If just `flutter run` is used, I experience a similar thing as issue #6135 outlines, where the app won't refresh unless im actively using it.

If I instead `--enable-software-rendering`, the app is usable but only runs at about 5fps.

The latest AndroidThings build does mention it supports hardware acceleration on the RPi, see here: https://developer.android.com/things/preview/releases#new_in_preview_5

I'd love to use Flutter for our IoT product.

What would it take to get hardware acceleration working?

**Comment by gedw99** [comment]
@captnPlanet this is great. I was just asking the dev group a few weeks ago about this and heard nothing.

**Comment by gedw99** [comment]
got it working. Pretty cool
