### ISSUE TITLE
error in the SnackBar

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#17097]
I/flutter (18687): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (18687): The following assertion was thrown while handling a gesture:
I/flutter (18687): Scaffold.of() called with a context that does not contain a Scaffold.
I/flutter (18687): No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This
I/flutter (18687): usually happens when the context provided is from the same StatefulWidget as that whose build
I/flutter (18687): function actually creates the Scaffold widget being sought.
I/flutter (18687): There are several ways to avoid this problem. The simplest is to use a Builder to get a context that
I/flutter (18687): is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
I/flutter (18687):   https://docs.flutter.io/flutter/material/Scaffold/of.html
I/flutter (18687): A more efficient solution is to split your build function into several widgets. This introduces a
I/flutter (18687): new context from which you can obtain the Scaffold. In this solution, you would have an outer widget
I/flutter (18687): that creates the Scaffold populated by instances of your new inner widgets, and then in these inner
I/flutter (18687): widgets you would use Scaffold.of().
I/flutter (18687): A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, then use the
I/flutter (18687): key.currentState property to obtain the ScaffoldState rather than using the Scaffold.of() function.
I/flutter (18687): The context used was:
I/flutter (18687):   Phase1(state: _Phase1State#83458)
I/flutter (18687): When the exception was thrown, this was the stack:
I/flutter (18687): #0      Scaffold.of (package:flutter/src/material/scaffold.dart:944:5)
I/flutter (18687): #1      _Phase1State.build.<anonymous closure> (package:enigmaz/phases/phase1.dart:52:24)
I/flutter (18687): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter (18687): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter (18687): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (18687): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (18687): #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
I/flutter (18687): #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter (18687): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (18687): #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (18687): #10     BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
I/flutter (18687): #11     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (18687): #12     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (18687): #13     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (18687): #14     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (18687): #15     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:134)
I/flutter (18687): #16     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
I/flutter (18687): Handler: onTap
I/flutter (18687): Recognizer:
I/flutter (18687):   TapGestureRecognizer#aa574(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter (18687):   Offset(587.0, 48.0), sent tap down)
I/flutter (18687): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by giovannilima262** [comment]
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.3.5, on Linux, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

• No issues found!

**Comment by giovannilima262** [comment]
the code: 



 new IconButton(
            icon: new Icon(Icons.wb_incandescent),
            onPressed: () {
              final snackBar = new SnackBar(
                content: new Text('Yay! A SnackBar!', style: new TextStyle(color: Colors.white),),
                action: new SnackBarAction(
                  label: 'Undo',
                  onPressed: () {
                    // Some code to undo the change!
                  },
                ),
              );

              // Find the Scaffold in the Widget tree and use it to show a SnackBar!
              Scaffold.of(context).showSnackBar(snackBar);
            },
          ),

**Comment by godara01** [comment]
I am having the same error. 
Please share the changes that are needed to be done.

**Comment by Viibrant** [comment]
Same error here too

**Comment by zoechi** [comment]
This issue is long closed. Please create a new issue with the information you can provide that allows to reproduce. Adding a link to this issue might be a good idea as well.

**Comment by programadornatal** [comment]
Hi, I dit it, work for me :)

`@override
Widget build(BuildContext context) {
  return new Scaffold(
    appBar: new AppBar(
      title: new Text('Fabio App')
    ),
    body: new Builder(
      // Create an inner BuildContext so that the onPressed methods
      // can refer to the Scaffold with Scaffold.of().
      builder: (BuildContext context) {
        return new Center(
          child: new RaisedButton(
            child: new Text('SHOW A SNACKBAR'),
            onPressed: () {
              Scaffold.of(context).showSnackBar(new SnackBar(
                content: new Text('Hello!'),
              ));
            },
          ),
        );
      },
    ),
  );
}`

**Comment by sgon00** [comment]
To fix this, you can just create a new StatelessWidget. For example:

```dart
class SomeButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return IconButton(...);
  }
}
```

and then put the new `SomeButton()` instance to where your old `IconButton` is.

Btw, you can use `Builder` too as shown in the above comment. But I like creating a new widget. It looks clean to me.

**Comment by carl1990** [comment]
same error

`  _pushSaved(BuildContext context) async{
    print("点击了");
   final result = await Navigator.push(
        context,
        new MaterialPageRoute(
          builder: (context) => new SecondScreen(params: "hello"),
        ));

   print("$result");
    Scaffold
        .of(context)
        .showSnackBar(new SnackBar(content: new Text("$result")));
  }`

`class RandomWords extends StatefulWidget {
  @override
  createState() => new RandomWordsState();
}

class RandomWordsState extends State<RandomWords> {
  final _suggestions = <WordPair>[];

  final _saved = new Set<WordPair>();

  final TextStyle _biggerFont = new TextStyle(fontSize: 20.0);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Startup Name Generator'),
        actions: <Widget>[
          new IconButton(
              icon: new Icon(Icons.favorite),
              onPressed: () {
                _pushSaved(context);
              })
        ],
      ),
      body: _buildSuggesttions(),
    );
  }`

**Comment by giovannilima262** [comment]
```dart
  final GlobalKey<ScaffoldState> _scaffoldstate =
      new GlobalKey<ScaffoldState>();
```

```dart

_scaffoldstate.currentState.showSnackBar(
      new SnackBar(
        duration: new Duration(seconds: tempo),
        content: new Text(value),
      ),
    );
```

**Comment by SPK-RPI** [comment]
**This is A dialog box Class**
import 'package:flutter/material.dart';
class PinChangeDialog extends StatefulWidget {
  final FirebaseUser user;
  final Function acPerform;
  final ValueChanged<Map<String,dynamic>> returnValues;
  PinChangeDialog({this.user,this.acPerform,this.returnValues, Key key}) : super(key: key);

  _PinChangeDialogState createState() => _PinChangeDialogState();
}

class _PinChangeDialogState extends State<PinChangeDialog>
    with SingleTickerProviderStateMixin {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _pinOld = TextEditingController();
  final TextEditingController _pinNew = TextEditingController();
  bool oldpinError = false;
  bool showSucess = false;
  AnimationController controller;

  Animation<double> scaleAnimation;
  @override
  void initState() {
    super.initState();

    controller =
        AnimationController(vsync: this, duration: Duration(milliseconds: 450));
    scaleAnimation =
        CurvedAnimation(parent: controller, curve: Curves.elasticInOut);

    controller.addListener(() {
      setState(() {});
    });

    controller.forward();
  }
@override
  void dispose() {
    controller.dispose();
    _pinNew.dispose();
    _pinOld.dispose();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    Widget pinInput(
        String hint, bool firstInput, TextEditingController editingController) {
      String validator(String pin) {
        if (pin.length < 4) {
          return "In valid";
        }
        return null;
      }

      return TextFormField(
        controller: editingController,
        validator: (pin) => firstInput ? validator(pin) : validator(pin),
        maxLength: 4,
        keyboardType: TextInputType.number,
        decoration: InputDecoration(
          hintText: hint,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.all(
              Radius.circular(10.0),
            ),
          ),
        ),
      );
    }

    final height = MediaQuery.of(context).size.height;
    final width = MediaQuery.of(context).size.width;
    return Center(
      child: Material(
        color: Colors.transparent,
        child: ScaleTransition(
          scale: scaleAnimation,
          child: AlertDialog(
            title: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[Icon(Icons.vpn_key), Text("Change Pin")],
            ),
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(15.0)),
            content: Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  pinInput("Old Pin", true, _pinOld),
                  pinInput("New Pin", false, _pinNew),
                  oldpinError
                      ? Text(
                          "Old Pin is wrong !!",
                          style: TextStyle(color: Colors.red),
                        )
                      : Container()
                ],
              ),
            ),
            actions: <Widget>[
              FlatButton(
                child: Text("OK"),
                onPressed: () {
                  print("hellow from pinChnage class");
                  widget.returnValues({"oldPin":_pinOld.text,"newPin":_pinNew.text,"isValid":_formKey.currentState.validate()});
                },
              ),
              FlatButton(
                child: Text("Cancel"),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              )
            ],
          ),
        ),
      ),
    );
  }
}








**SettingsScreen calling class to PinChangeDialog class**
import 'package:flutter/material.dart';


class SettingsScreen extends StatelessWidget {
  SettingsScreen({Key key}) : super(key: key);
  var _scaffoldKey = GlobalKey<ScaffoldState>();
  @override
  Widget build(BuildContext context) {
    StorageUploadTask uploadTask;
    FirebaseUser user = Provider.of<FirebaseUser>(context);
    String name = user.displayName;
    String urlPhoto = user.photoUrl;
    String email = user.email;
    bool logOut() {
      void x() {
        Navigator.of(context).pop();
        Navigator.of(context).pop();
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(
            builder: (context) => DocumentVault(
              show: false,
            ),
          ),
        );
        GoogleRegistorService().auth.signOut();
      }

      showDialog(
        context: context,
        builder: (BuildContext context) => CuAlertDialog(
          subtitle: "You are going to sign Out",
          title: "Are you sure ?",
          okAction: x,
          tag: "logout",
        ),
      );
      return true;
    }

    bool clean() {
      void x() {
        CRUD(user, uploadTask).deleteAllDocuments().then((value) {
          if (value) {
            Navigator.of(context).pop();
            _scaffoldKey.currentState.showSnackBar(
              SnackBar(
                content: Text("Deleted All the Documents"),
              ),
            );
          } else {
            Navigator.of(context).pop();
            _scaffoldKey.currentState.showSnackBar(
              SnackBar(
                content: Text("Nothing To Delete !!"),
              ),
            );
          }
        });
      }

      showDialog(
        context: context,
        builder: (BuildContext context) => CuAlertDialog(
          subtitle: "Delete all the documents from cloud.",
          title: "Are you sure ?",
          okAction: x,
          tag: "logout",
        ),
      );
      return true;
    }

    bool changePin() {
      void showSneakBar(String text) {
        _scaffoldKey.currentState.showSnackBar( SnackBar(
            content: Text(text),
          ),);
        /* _scaffoldKey.currentState.showSnackBar(
          SnackBar(
            content: Text(text),
          ),
        ); */
      }

      void mainLogic(data) {
        if (data["isValid"]) {
          print(data["newPin"]);
          PinManager(user: user).getPin().listen((pin) {
            if (pin.value.toString() != data["oldPin"]) {
              //Navigator.of(context).pop();

              showSneakBar("Cloud pin and Entered Pin no match !!");
            } else {
              PinManager(user: user).setPin(data["newPin"]).then((c) {
                //Navigator.of(context).pop();

                showSneakBar("Pin Updated to ${data["newPin"]}");
              });
            }
          });
        } else {
          showSneakBar("Check your Inputs !!1");
        }
      }

      showDialog(
        context: context,
        builder: (BuildContext context) => PinChangeDialog(
            user: user,
            returnValues: (data) {
              mainLogic(data);
            }),
      );
      return true;
    }

    return Scaffold(
      key: _scaffoldKey,
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            leading: Hero(
              tag: "settings",
              child: Icon(
                Icons.settings,
                color: Colors.black,
              ),
            ),
            pinned: true,
            backgroundColor: Color(0xfff8faf8),
            elevation: 0.0,
            centerTitle: true,
            title: Text(
              "Settings",
              style: TextStyle(color: Colors.black),
            ),
          ),
          SliverList(
            delegate: SliverChildListDelegate(
              [
                UserAccountsDrawerHeader(
                  margin: EdgeInsets.all(10.0),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(25.0),
                    gradient: LinearGradient(
                      colors: [
                        Color(0xFFFF9945),
                        Color(0xFFFc6076),
                      ],
                    ),
                  ),
                  currentAccountPicture: CircleAvatar(
                    backgroundImage: NetworkImage(urlPhoto),
                  ),
                  accountEmail: Text(email),
                  accountName: Text(name),
                ),
                ListTile(
                  leading: Hero(tag: "logout", child: Icon(Icons.exit_to_app)),
                  title: Text("Log out"),
                  subtitle: Text("Log Out and keep all the data in cloud."),
                  onTap: () => logOut(),
                ),
                ListTile(
                  leading: Icon(Icons.clear_all),
                  title: Text("Clean"),
                  subtitle: Text("Delete all the files in the cloud"),
                  onTap: () => clean(),
                ),
                ListTile(
                  leading: Icon(Icons.vpn_key),
                  title: Text("Change Pin"),
                  subtitle: Text("Change the pin"),
                  onTap: () => changePin(),
                )
              ],
            ),
          )
        ],
      ),
    );
  }
}
I am getting the following Error !!!!
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'showSnackBar' was called on null.

**Comment by giovannilima262** [comment]
This is solution https://github.com/flutter/flutter/issues/17097#issuecomment-501762525

**Comment by patelkrunal78** [comment]
This exception happens because you are using the context of the widget that instantiated Scaffold. Not the context of a child of Scaffold.

You can solve this by just using a different context :
Find more At Here https://icetutor.com/question/scaffold-of-called-with-a-context-that-does-not-contain-a-scaffold

**Comment by errorsolve** [comment]
[Already [Solved] Scaffold.of() called with a context that does not contain a Scaffold
](https://fluttercorner.com/scaffold-of-called-with-a-context-that-does-not-contain-a-scaffold/)
