### ISSUE TITLE
big_switch.dart is crazy janky

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#171]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Sep 24, 2015 at 22:51 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1333_

----

@abarth says it's something in skia. The problem goes away if you use the identity transform.

**Comment by sethladd** [comment]
Is this still an issue?

**Comment by Hixie** [comment]
Can't find big_switch anymore, so going to close for inability to reproduce.
