### ISSUE TITLE
The Nesting rows and columns tutorials on flutter.io has an issue, even I copy down the whole code and run it. 

### ISSUE THREAD

**Issue by JonathanSum** [flutter/flutter#17109]
[https://flutter.io/tutorials/layout/](tutorials/layout/)
It is under the Nesting rows and columns section. 
I even downloaded the code on flutter.io and ran it. It throws this error:

> I/flutter (  828): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (  828): The following message was thrown during layout:
I/flutter (  828): A RenderFlex overflowed by 15 pixels on the bottom.
I/flutter (  828): 
I/flutter (  828): The overflowing RenderFlex has an orientation of Axis.vertical.
I/flutter (  828): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter (  828): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter (  828): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter (  828): RenderFlex to fit within the available space instead of being sized to their natural size.

[Code:](https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/pavlova/main.dart)
[Image:](https://github.com/flutter/website/tree/master/_includes/code/layout/pavlova/images)

**Comment by JonathanSum** [comment]
Here is my solution for the flutter.io tutorial, but it only works in horizon view. https://github.com/JonathanSum/layoutrecap4/blob/master/lib/main.dart

**Comment by JonathanSum** [comment]
This is what we get if we copy down the code from the flutter IO and run it.
- Dart code: main.dart
https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/pavlova/main.dart



- Pubspec: pubspec.yaml
https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/pavlova/pubspec.yaml


- https://flutter.io/tutorials/layout/
![screenshot_20180512-010740](https://user-images.githubusercontent.com/21982975/40021107-cff44582-5778-11e8-938a-1adb24f3090b.png)

**Comment by Sfshaza** [comment]
Hi @JonathanSum! This tutorial was written for a larger screen device, and I suspect you are viewing it on a too-small screen. There's a note to this effect right on that page:

<img width="751" alt="screen shot 2018-05-18 at 3 16 32 pm" src="https://user-images.githubusercontent.com/6293442/40262594-5a53e9b6-5abd-11e8-9d84-c8965931bd48.png">

I suggest you try running it on a tablet-sized device. Thx

**Comment by JonathanSum** [comment]
Thank You for answer. I thought the example work
