### ISSUE TITLE
Proposal For Copy Writing

### ISSUE THREAD

**Issue by ewuoso** [flutter/flutter#17108]
I just checked your project and i feel it is missing out some important details like faq, about us, contact us, privacy policy etc. If i you dont mind i am available and i can write it for you.

ewuosoolusesi@gmail.com

**Comment by mit-mit** [comment]
Pull requests are always welcome! Closing this issue as it's not tracking something specific.

**Comment by zoechi** [comment]
FAQ is at https://flutter.io/faq/

**Comment by ewuoso** [comment]
What about.... About us
