### ISSUE TITLE
Issue from website page Support

### ISSUE THREAD

**Issue by fcarrizosaflores** [flutter/flutter#17107]
From URL: https://flutter.io/support/

Can I monetize with admob in flutter?

**Comment by JonathanSum** [comment]
You can take a look at this post: https://github.com/flutter/flutter/issues/8098#issue-207296757.
We also have a tutorial about using firebase too: https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..%2Findex#0

**Comment by fcarrizosaflores** [comment]
Veeeeeryyyy thaaaaanksss!!

2018-04-30 5:25 GMT-05:00 Jonathan Sum <notifications@github.com>:

**Comment by zoechi** [comment]
Seems to be solved. Thanks @JonathanSum
