### ISSUE TITLE
Add ability to save Server timestamp (Firebase Firestore)

### ISSUE THREAD

**Issue by harrisonturton** [flutter/flutter#17114]
Hello,

It'd be super useful to add a "Server timestamp" when persisting data using [cloud_firestore](https://pub.dartlang.org/documentation/cloud_firestore/0.6.3/).

It's documented (in JS, Swift, Obj-C, Android, Java, Python) at the very bottom of [this page](https://firebase.google.com/docs/firestore/manage-data/add-data).

I image this would be added through a platform channel invoking something in the [CloudFirestorePlugin.java](https://github.com/flutter/plugins/blob/7e4d7a6befdf696725f1130f6b441fa4b4864c11/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java) and in [CloudFirestorePlugin.m](https://github.com/flutter/plugins/blob/7e4d7a6befdf696725f1130f6b441fa4b4864c11/packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m) for iOS.

I've tried to do this myself, but I'm not familiar with the Java/iOS versions of the library, nor am I handy with `PlatformChannels`.

**Comment by zoechi** [comment]
Closing as dup of #13905
