### ISSUE TITLE
Windows - "Downloaded executables cannot execute on host (see #6207 for more information)"

### ISSUE THREAD

**Issue by prujohn** [flutter/flutter#17116]
re #6207

I got this error when attempting to flutter doctor after I had installed flutter into a mapped drive on windows.  More specifically, I was attempting to install it into my google stream drive.

When I relocated the flutter folder to my local drive, everything worked fine.

Obviously some sort of rights issue, but I wanted to report the simple workaround nonetheless.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Also asked on https://stackoverflow.com/questions/44143548/gradle-error-building-base-flutter-app

**Comment by kangwang1988** [comment]
Duple of: https://github.com/flutter/flutter/issues/22910
