### ISSUE TITLE
Flutter Firebase Messaging example app - run in foreground then run in background no result for background message

### ISSUE THREAD

**Issue by JohnAherne** [flutter/flutter#17111]
## Steps to Reproduce
The example app is unmodified.
All options work when run as the only option
Run in foreground
Run in background
Run when terminated

Run the app with flutter -v

Leave in foreground
send a message - get popup and all is fine.
Put app into background by pressing home button.
Send a message - nothing happens on the screen

## Logs
end when live is OK
Send when in background - no navigator called

##Log from run screen

[  +59 ms] I/flutter (16241): Push Messaging token: emCSa6FmEN4:APA91bGl2VdOigd4W4vgyAioS_Yg8U2jnSvYjHw6l3kxH6Hzkl8nIeDAiOV7JpfU2yIAnUaHjADGZYAiZ42o0veqMdf_ccl4RFc1wO2GsPRbcI0Eaes4WNzfCcbw_3QiKK16_PNpunJ_
[+1845 ms] Updating files
[ +701 ms] DevFS: Sync finished
[        ] Synced 1.1MB.
[   +2 ms] _flutter.listViews: {}
[   +6 ms] Connected to _flutterView/0x9c2ab960.
[   +1 ms] ??  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
[   +1 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8105/
[        ] For a more detailed help message, press "h". To quit, press "q".
[+7871 ms] I/flutter (16241): onMessage: {status: 280418, id: 12345, click_action: FLUTTER_NOTIFICATION_CLICK}
[+25494 ms] D/EGL_emulation(16241): eglMakeCurrent: 0x9c2ac140: ver 3 0 (tinfo 0x9a2ba9b0)
[+10619 ms] I/FlutterActivityDelegate(16241): onResume setting current activity to this
[  +10 ms] I/flutter (16241): onResume: {google.sent_time: 1525082193638, click_action: FLUTTER_NOTIFICATION_CLICK, status: 280418, collapse_key: com.example.fcmtest1, id: 12345, from: 915347252314, google.message_id: 0:1525082193642529%fe1fa160fe1fa160, google.ttl: 2419200}
[   +3 ms] D/EGL_emulation(16241): eglCreateContext: 0xa0a86260: maj 3 min 0 rcv 3
[ +180 ms] D/EGL_emulation(16241): eglMakeCurrent: 0xa0a86260: ver 3 0 (tinfo 0x9c232820)
[   +1 ms] E/eglCodecCommon(16241): glUtilsParamSize: unknow param 0x00008cdf
[   +3 ms] E/eglCodecCommon(16241): glUtilsParamSize: unknow param 0x00008824
[   +9 ms] D/EGL_emulation(16241): eglMakeCurrent: 0xa0a86260: ver 3 0 (tinfo 0x88fff310)
[ +164 ms] D/EGL_emulation(16241): eglMakeCurrent: 0x9c2ac140: ver 3 0 (tinfo 0x9a2ba9b0)

##Log from log screen

C:\flutter_tests\fcm_test1>flutter logs
Showing Android SDK built for x86 logs:

No LOG Output except above

## Flutter Doctor

C:\flutter_tests>flutter doctor -v
[v] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-GB)
    • Flutter version 0.2.8 at c:\flutter_dev\flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[v] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\john2\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[v] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[v] VS Code, 64-bit edition (version 1.22.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.0

[v] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

##Flutter analyze
C:\flutter_tests\fcm_test1>flutter analyze
Analyzing C:\flutter_tests\fcm_test1...
  error - The constructor returns type 'dynamic' that isn't of expected type 'Widget' at test\widget_test.dart:15:29 - strong_mode_invalid_cast_new_expr
  error - Undefined class 'MyApp' at test\widget_test.dart:15:33 - undefined_class
  hint - Unused import: 'package:fcm_test1/main.dart' at test\widget_test.dart:10:8 - unused_import
3 issues found.

**Comment by JohnAherne** [comment]
Same problem as 27112

**Comment by zoechi** [comment]
Close as dup of #17112 - thanks @JohnAherne
