### ISSUE TITLE
Flutter TextField Display Bug

### ISSUE THREAD

**Issue by HxBreak** [flutter/flutter#17115]
##Futter 0.3.1 Dart 2.0.0
A part of the text was cut off when i type the chinese
android device: oneplus 5T
ios device:iPhone X simulator

![9c4f740b3e928b5ea90c9358201e06cc](https://user-images.githubusercontent.com/15846180/39427484-78d3fb70-4cb6-11e8-9c1e-bab7253db774.jpg)
![qq20180430-202857](https://user-images.githubusercontent.com/15846180/39427485-790d1a36-4cb6-11e8-8c6b-54ebde02c0cc.png)

**Comment by dokinkon** [comment]
Also found similar situation on TextField with decoration.
![default](https://user-images.githubusercontent.com/524313/40268002-534dbecc-5b98-11e8-844c-acb60d50bdbf.jpg)
![eng](https://user-images.githubusercontent.com/524313/40268003-553bbad6-5b98-11e8-8223-2b15db0a58e2.jpg)

✓] Flutter (Channel master, v0.4.5-pre.39, on Mac OS X 10.13.4 17E202, locale zh-Hant-TW)
    • Flutter version 0.4.5-pre.39 at /Users/dokinkon/Case/flutter
    • Framework revision 8a83d0df7f (2 days ago), 2018-05-17 15:12:08 -0700
    • Engine revision 65d52d94fd
    • Dart version 2.0.0-dev.55.0.flutter-43635d3372

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/dokinkon/Library/Android/sdk
    • Android NDK at /Users/dokinkon/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

• No issues found!

I love flutter so much, but I can't launch my new app in Chinese market with this issue.
Thanks awesome flutter.

**Comment by HxBreak** [comment]
@dokinkon 修改字体高度(1.2)，字体大小，能让文字剪裁效果最小化

**Comment by dokinkon** [comment]
@HxBreak Thanks your reply. But I think that is a workaround approach. I also found this issue is more noticeable on Android devices. Hopefully the official dev team can resolve this issue in next few releases.

**Comment by cctse** [comment]
Issues with TextField on Android
1、cursor doesn't focus on the center of line
2、cursor doesn't move to next line when press "enter" to switch to the next line
3、TextField can't scroll to bottom when text exceeded the height of the TextField, this may be the same with issue 1

![textfieldbug](https://user-images.githubusercontent.com/3608665/41952311-dac66b38-7a01-11e8-919a-89985d1b07d7.jpg)
![textfieldbug](https://user-images.githubusercontent.com/3608665/41952312-dd336a2e-7a01-11e8-9eec-90bfc1fc1e70.png)

**Comment by cctse** [comment]
4、Actions of long press doesn't translate to local language
5、the bottom of text will be cut when content exceeded the widget width in single line TextField
![textfieldbug3](https://user-images.githubusercontent.com/3608665/41955334-36b54684-7a12-11e8-8f4f-950b37a8ef5e.jpg)

**Comment by asmh1989** [comment]
I use a Chinese font by default, the cursor can be unified between Chinese and other characters, but there will still be problems when inputting expressions.

**Comment by zywj** [comment]
@cctse You need to set the font family if your cursor doesn't align vertical center in Chinese text.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by cctse** [comment]
@zoechi It's ok for 1/2/3/5,  not for 4th
**how to change actions to local language?**

for current version, cursor seems to draw from baseline, a little bit ugly compare to android native.

flutter gallery
![flu2](https://user-images.githubusercontent.com/3608665/54192936-03ebba00-44f4-11e9-8a71-c618d77e4a84.jpg)

android wechat
![flu1](https://user-images.githubusercontent.com/3608665/54192985-1b2aa780-44f4-11e9-9445-a468787f0bb5.jpg)
