### ISSUE TITLE
New Widget: SearchBar

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#17119]
Provide a widget with the features described in the [Patterns– Search](https://spec.googleplex.com/m2/navigation/search.html) section of the Material spec.

Features:
- RawSearchBar: just input handling, no decoration
- History and auto-completion
- Scaffold searchBar

![image](https://user-images.githubusercontent.com/1377460/39437364-761ad400-4c55-11e8-8033-35fbcd269e89.png)

**Comment by MaskyS** [comment]
Hope to see this soon :smiley:

**Comment by AppleEducate** [comment]
It would be cool to implement this into a a table view like ios. 

https://www.raywenderlich.com/157864/uisearchcontroller-tutorial-getting-started

**Comment by johrpan** [comment]
@HansMuller Is there any kind of information, when this will be ready? In #6691 someone said that you already had it internally.

**Comment by HansMuller** [comment]
@goderbauer is actively working on it. Next week is the Google I/O conference, so there will be a break in the action; we will keep you-all posted after that.

**Comment by CyanBlob** [comment]
I was just about to start implementing my own version of this. I'm glad to see that it's being added natively! Not to nag you, but has any progress been made recently?

**Comment by johrpan** [comment]
@goderbauer Thanks a lot for the information, this is indeed great progress. I just wanted to make clear that this issue is about Persistent Search, not Expandable Search (by what I don't necessarily want to say, that you aren't aware of that).

**Comment by ebeem** [comment]
a very useful widget, would love to see it soon

**Comment by CyanBlob** [comment]
Not to keep spamming this thread, but has any progress been made on the non-expandable material search bar?

**Comment by Ethiel97** [comment]
Good job 💪. Looking forward to using it. I can help too.

**Comment by iapicca** [comment]
@HansMuller 
isn't this issue solved by [SearchDelegate](https://api.flutter.dev/flutter/material/SearchDelegate-class.html)?

**Comment by HansMuller** [comment]
This sprit of this very old issue has been resolved by https://github.com/flutter/flutter/pull/122309 and https://github.com/flutter/flutter/pull/123256.
