### ISSUE TITLE
CustomPainter & BlendMode.multiply clipping artifacts

### ISSUE THREAD

**Issue by rav3r** [flutter/flutter#17113]
I am trying to mask one rectangle with another one using CustomPainter with BlendMode.multiply. When I embed it in ListView (also happens when embedded in GridView or PageView) then I see strange white artifact on top of the list and on left border of masked rectangle:

![screenshot](https://user-images.githubusercontent.com/2051417/39425922-ee4ff978-4c7d-11e8-8d8f-64a96b2d59ba.png)

## Steps to Reproduce

Run following code:

```
void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new Container(
        color: new Color.fromARGB(255, 128, 128, 128),
        margin: new EdgeInsets.all(50.0),
        child: new ListView.builder(
          itemBuilder: (context, index) {
            return _buildRow();
          },
          itemCount: 50,
        ),
      ),
    );
  }

  Widget _buildRow() {
    return new Container(
      height: 100.0,
      child: new CustomPaint(
        painter: new MaskingPainter(),
      ),
    );
  }
}

class MaskingPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final Rect rect = new Rect.fromLTRB(
      5.0,
      5.0,
      size.width - 10.0,
      size.height - 10.0,
    );

    canvas.drawRect(
      rect,
      new Paint()..color = new Color.fromARGB(255, 255, 255, 255),
    );

    canvas.drawRect(
      rect,
      new Paint()
        ..blendMode = BlendMode.multiply
        ..color = new Color.fromARGB(255, 128, 0, 0),
    );
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```

Reproducable on Xiaomi Redmi4A

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.2.11, on Mac OS X 10.12.6 16G29, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
Flutter version seems a bit outdated. Can you try with a newer version?

**Comment by zoechi** [comment]
Can't reproduce in 

[✓] Flutter (Channel master, v0.5.8-pre.142, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.5.8-pre.142 at /Users/zoechi/flutter/flutter
    • Framework revision f72c514c59 (27 hours ago), 2018-07-26 05:08:11 -0700
    • Engine revision 95e91e31fa
    • Dart version 2.0.0-dev.69.0.flutter-937ee2e8ca

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

Can this be closed?

**Comment by rav3r** [comment]
Thanks, please close this.
