### ISSUE TITLE
Extend the list of supported locales

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#17122]
Add the following locales to [material_localizations.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/material_localizations.dart) et al:

```
bg - Bulgarian
hr - Croatian
cs - Czech
da - Danish
fil - Fillipino
fi - Finnish
el - Greek
hi - Hindi
hu - Hungarian
lv - Latvian
lt - Lithuanian
sr - Serbian
sk - Slovak
sl - Slovenian
sv - Swedish
uk - Ukranian
```

**Comment by alanrussian** [comment]
@HansMuller we need the following locales added to launch. Sorry for just noticing this.

```
bg,
ca,
cs,
da,
el,
et,
fi,
hi,
hr,
hu,
lt,
lv,
sk,
sl,
sr,
sv,
tl,
uk
```

**Comment by alanrussian** [comment]
Feel free to ping me if you have any questions. I'm marking as a customer blocker since I'm assuming these localizations take time, so we would need to get the process started ASAP.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
In addition to the locales this issue was supposed to add, you're asking for:

ca - Catalan
et - Estonian
hr - Croatian

And for 'tl - Tagalog' I'm hoping that 'fil' (Filipino) will work. 

I will add request translations for all of the new languages.

**Comment by efroim102** [comment]
@Hixie Does flutter support the `yi` or `ji` locale for Yiddish?

```
I/flutter ( 6430): Warning: This application's locale, yi, is not supported by all of its
I/flutter ( 6430): localization delegates.
I/flutter ( 6430): > A MaterialLocalizations delegate that supports the yi locale was not found.
```
