### ISSUE TITLE
Document why AOT build outputs are different on iOS vs. Android in release mode

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#17135]
@kangwang1988 asked:
"As flutter is in aot mode for release, when it comes to ios, gen_snapshot make the dart code into machine code(App.framework finally). However, when it comes android, we have four files. vm/isolate_snapshot_dart/instr, why vm here? Is there a dart vm running in runtime for android in release mode? What is isolate_snapshot_instr exactly? Is it dart byte code for dartvm in runtime?"

The answer, as I recall is:
The reason the outputs are different on iOS vs. Android is mostly due to toolchains. On Android we try not to depend on the NDK toolchain, which would be required if we wanted to make .so files. So instead we just make a file of arm instructions and load it directly at runtime. On iOS, we comple that file of arm instructions into a real .so (or dylib as iOS calls them) and package it into a .framework, because all the tools are readily available.
We've talked about moving to using .so's on Android too, just haven't.
The NDK toolchain adds some gig(s)? of download size if I remember correctly.

Others may ask the same, so writing this down here.  It might belong in some engine wiki or README.  FYI @cbracken

**Comment by chinmaygarde** [comment]
I have jotted down the details in [this document](https://docs.google.com/document/d/1TIoaCM1zrpp6nSCPG8wqeGXAwaG95opjJS1VO6AH7D0/edit?hl=en#) and shared it with the team for fact checking. Will move it to the engine wiki when done.

**Comment by chinmaygarde** [comment]
Comments on the document have been addressed and it has been moved to the [engine wiki here](https://github.com/flutter/engine/wiki/Flutter-Engine-Operation-in-AOT-Mode). We can make edits to it as needed there.

**Comment by kangwang1988** [comment]
Thank you guys.

**Comment by Zo2m4bie** [comment]
@eseidelGoogle Thank you for description. I have some question related to it. So as I understand isolate_snapshot_instr is instruction that were build from dart code. Am I correct? If so, could you please give some more information about this instruction? Is it something like assembling all dart code into one file?

**Comment by eseidelGoogle** [comment]
@Zo2m4bie https://github.com/flutter/flutter/wiki/Flutter-engine-operation-in-AOT-Mode is the updated location for the wiki page.

**Comment by Zo2m4bie** [comment]
@eseidelGoogle Thank you for your response. According to link Isolate Instructions contains the AOT code that is executed by the Dart isolate. Ok, I'm interesting from security perspective. Is it encrypted in this file? I try to open this file to see what inside and I can't. I try to understand how secure data inside

**Comment by chinmaygarde** [comment]
The AOT code is assembled and linked into a dynamic library on iOS (look in `App.framework` in the iOS application bundle by default) and memory mapped with read-exec on Android. The AOT code looks like a regular dynamic library. For example, here it is what I see using Hopper.

<img width="1354" alt="Screen Shot 2019-03-12 at 3 02 01 PM" src="https://user-images.githubusercontent.com/44085/54239360-3687b980-44d8-11e9-8e0b-1d3906b3d1ac.png">
