### ISSUE TITLE
Copy edit "Flutter for React Native"

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#17131]
Please copy edit /flutter-for-react-native.

For reference, Google Documentation Style Guide: https://developers.google.com/style/

**Comment by czakdesign** [comment]
Shams,  Just for reference,  the [Flutter for React Native Developers](https://flutter.io/flutter-for-react-native/) is 59 pages in a PDF file.  I don't work off a pdf - i just created it to see the whole web page in one doc/file -- quite large I would say for one web page.  

I'll review and edit and make suggestions possibly for breaking up that info into separate pages/docs.

**Comment by zoechi** [comment]
Still to do?

**Comment by Sfshaza** [comment]
No, @zoechi. We are generally asked to keep our pages to one file. It makes searching easier.
