### ISSUE TITLE
Make the launch view of the FlutterViewController configurable.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#17140]
Right now, the `UILaunchStoryboardName` key in the main application's Info.plist is used to initialize the launch view. For Flutter embedders that embed multiple Flutter applications or Flutter applications that don't occupy the entire screen, this mechanism is not flexible enough. FlutterViewController must have an API that allows embedders to specify their own launch views.

**Comment by jamesderlin** [comment]
Should be fixed by https://github.com/flutter/engine/pull/6112.
