### ISSUE TITLE
When Inspecting Layouts or Running with Developer Options, Flutter App Has No Layout Bounds

### ISSUE THREAD

**Issue by ngoctranfire** [flutter/flutter#17149]
Not sure if this is something that is based on how flutter, works, but is it not possible to show its layout bounds? This makes it seem like it is a web view (even though it is obviously not), and it is quite performant. I just wanted to get a better understanding of how Flutter works.

I see that:
1) There is no layout hierarchy. This is okay, because I can inspect the flutter layout with the Flutter Inspector. However, can someone describes what is going on that is allowing this to happen and can make flutter feel "native" regardless.
2) Why Flutter Shows no Layout Bounds when Developer Options with Layout Bounds Shown is on. 

I know these might be dumb questions, but I'm always curious about how things work under the hood. This is a question to help understand this.

**Comment by ngoctranfire** [comment]
I just read up on this and I finally understand Flutter a lot more now! This is great resource, especially their explanation on "Layout". Would highly recommend for those who are interested in how flutter is so performant underneath. Widgets are so cool xD.

**Comment by dsprenkels** [comment]
@ngoctranfire Care to share a link to the specific explanation? :)

**Comment by jawand** [comment]
@dsprenkels i think this might help.

https://flutter.io/docs/testing/debugging#visual-debugging
