### ISSUE TITLE
Crash on startup: '!node.isInvisible': is not true

### ISSUE THREAD

**Issue by pinkfish** [flutter/flutter#17148]
## Steps to Reproduce

Restarted the job from scratch after replugging my android device back into the mac,

## Logs
```
I/flutter (13856): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13856): The following assertion was thrown during a scheduler callback:
I/flutter (13856): 'package:flutter/src/rendering/object.dart': Failed assertion: line 3118 pos 12:
I/flutter (13856): '!node.isInvisible': is not true.
I/flutter (13856): 
I/flutter (13856): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13856): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13856): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13856):   https://github.com/flutter/flutter/issues/new
I/flutter (13856): 
I/flutter (13856): When the exception was thrown, this was the stack:
I/flutter (13856): #2      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart)
I/flutter (13856): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:153:12)
I/flutter (13856): #4      Iterable.single (dart:core/iterable.dart:567:13)
I/flutter (13856): #5      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2282:96)
I/flutter (13856): #6      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:887:16)
I/flutter (13856): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:274:19)
I/flutter (13856): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622:13)
I/flutter (13856): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (13856): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13856): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13856): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (13856): #14     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (13856): #15     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (13856): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (13856): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (13856): ════════════════════════════════════════════════════════════════════════════════════════════════════


analyze:
Analyzing /Users/ddb/git/mobile/flutter_fuse...
  lint • Name non-constant identifiers using lowerCamelCase at lib/widgets/calendar/calendar.dart:48:21 • non_constant_identifier_names
  hint • The value of the field '_controllers' isn't used at lib/screens/invites/addinvitetoplayer.dart:23:38 • unused_field
  hint • The value of the field '_checked' isn't used at lib/screens/invites/addinvitetoplayer.dart:25:8 • unused_field
  hint • The value of the field '_controller' isn't used at lib/widgets/calendar/calendar.dart:43:20 • unused_field
  hint • The method '_buildCalendarList' isn't used at lib/widgets/calendar/calendar.dart:163:20 • unused_element
  hint • Unused import: 'dart:collection' at lib/widgets/calendar/sliverlistcalendar.dart:1:8 • unused_import
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/form/genderformfield.dart:34:25 • invalid_use_of_protected_member
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/form/opponentformfield.dart:39:25 • invalid_use_of_protected_member
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/form/playerformfield.dart:36:25 • invalid_use_of_protected_member
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/form/relationshipformfield.dart:34:23 • invalid_use_of_protected_member
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/form/roleinteamformfield.dart:34:29 • invalid_use_of_protected_member
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/form/seasonformfield.dart:36:31 • invalid_use_of_protected_member
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/form/sportformfield.dart:34:31 • invalid_use_of_protected_member
  hint • The value of the field '_overtime' isn't used at lib/widgets/games/editresultdialog.dart:28:23 • unused_field
  hint • The value of the field '_penalty' isn't used at lib/widgets/games/editresultdialog.dart:29:23 • unused_field
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/games/gameeditform.dart:109:10 • invalid_use_of_protected_member
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/games/gameeditform.dart:111:10 • invalid_use_of_protected_member
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/games/gameeditform.dart:124:35 • invalid_use_of_protected_member
  hint • The value of the field '_scrollController' isn't used at lib/widgets/games/ganeslistcalendar.dart:9:20 • unused_field
  hint • The value of the local variable 'nowMs' isn't used at lib/widgets/games/ganeslistcalendar.dart:39:9 • unused_local_variable
  hint • The member 'setValue' can only be used within instance members of subclasses of 'FormFieldState' at lib/widgets/games/trainingeditform.dart:80:10 • invalid_use_of_protected_member
  hint • Unused import: 'fabdialer.dart' at lib/widgets/util/fabminimenuitem.dart:4:8 • unused_import
  hint • The member 'activity' can only be used within instance members of subclasses of 'ScrollPosition' at lib/widgets/util/numberpicker.dart:310:35 • invalid_use_of_protected_member
  hint • The member 'activity' can only be used within instance members of subclasses of 'ScrollPosition' at lib/widgets/util/statepicker.dart:149:35 • invalid_use_of_protected_member
24 issues found.
(Ran in 10.1s)
```

## Flutter Doctor

[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.3 17D102, locale en)
    • Flutter version 0.2.8 at /Users/ddb/git/flutter/flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /opt/android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /opt/android_sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode_9.2.0_fb.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Pixel • FA76H0300497 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by chinmaygarde** [comment]
Do you have a reduced test case of your application that reproduces this issue?

@Hixie or @HansMuller may be able to tell by looking at the stack trace too maybe.

**Comment by HansMuller** [comment]
I don't see an obvious source for the problem based on the stack trace. As @chinmaygarde  said, a test case that demo'd the problem would really help here.

The exception is in the a11y code, cc @goderbauer

**Comment by pinkfish** [comment]
It only happens sporadically, not all the time.  Hard to make a smaller
subset that would reproduce, sorry.

**Comment by jonahwilliams** [comment]
I can reproduce this easily on a Pixel 2.  `flutter run` an app and then lock the phone screen, the same error message is printed.

**Comment by ThinkDigitalRepair** [comment]
I'm having this as well. It only seems to happen when I have a physical device, probably because of the screen timeout.

**Comment by yusosov** [comment]
the same, but nothing really dramatic happens to me:
the app Startup Name Generator loads and runs normally afterwards
here is the log:

flutter -v run
...
[ +217 ms] Syncing files to device ANDY 45EL...
[   +3 ms] DevFS: Starting sync from LocalDirectory: '/home/yus/dev/flutter/myapp'
[        ] Scanning project files
[   +3 ms] Scanning package files
[  +87 ms] Scanning asset files
[        ] Scanning for deleted files
[  +13 ms] Compiling dart to kernel with 461 updated files
[   +3 ms] /usr/local/flutter/bin/cache/dart-sdk/bin/dart /usr/local/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /usr/local/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build/app.dill --packages /home/yus/dev/flutter/myapp/.packages --filesystem-scheme org-dartlang-root
[+3657 ms] I/flutter ( 9861): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[  +42 ms] I/flutter ( 9861): The following assertion was thrown during a scheduler callback:
[        ] I/flutter ( 9861): 'package:flutter/src/rendering/object.dart': Failed assertion: line 3169 pos 12:
[        ] I/flutter ( 9861): '!node.isInvisible': is not true.
[  +14 ms] I/flutter ( 9861): Either the assertion indicates an error in the framework itself, or we should provide substantially
[   +4 ms] I/flutter ( 9861): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 9861): In either case, please report this assertion by filing a bug on GitHub:
[   +2 ms] I/flutter ( 9861):   https://github.com/flutter/flutter/issues/new
[        ] I/flutter ( 9861): When the exception was thrown, this was the stack:
[  +53 ms] I/flutter ( 9861): #2      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart)
[   +1 ms] I/flutter ( 9861): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:153:12)
[        ] I/flutter ( 9861): #4      Iterable.single (dart:core/iterable.dart:556:13)
[        ] I/flutter ( 9861): #5      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2325:7)
[        ] I/flutter ( 9861): #6      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:887:16)
[        ] I/flutter ( 9861): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:274:19)
[   +1 ms] I/flutter ( 9861): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
[        ] I/flutter ( 9861): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
[        ] I/flutter ( 9861): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[   +1 ms] I/flutter ( 9861): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter ( 9861): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
[   +1 ms] I/flutter ( 9861): #14     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ] I/flutter ( 9861): #15     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[        ] I/flutter ( 9861): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[   +8 ms] I/flutter ( 9861): (elided 3 frames from class _AssertionError and package dart:async)
[        ] I/flutter ( 9861): ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +919 ms] Updating files
[+1770 ms] DevFS: Sync finished
[        ] Synced 0.8MB.
[   +2 ms] _flutter.listViews: {isolateId: isolates/285474914}
[  +38 ms] Connected to _flutterView/0x7f93237e18.
[        ] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".

**Comment by darshankawar** [comment]
Hi @pinkfish,
I am unable to replicate this issue on latest Flutter version (dev) using physical device (Samsung).
Can you please confirm if you still experience this issue on latest Flutter ?
Thanks.
