### ISSUE TITLE
Failed assertion while using push of navigator.dart

### ISSUE THREAD

**Issue by maeni70** [flutter/flutter#17153]
## Steps to Reproduce

Please refer to [stackoverflow: 'flutter-failed-assertion-while-using-navigator-dart'](https://stackoverflow.com/questions/50117831/flutter-failed-assertion-while-using-navigator-dart).

## Logs

```
PS D:\Flutter Projects\startup_namer> flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...                                    1.6s
Running 'gradlew assembleDebug'...                          11.4s
Built build\app\outputs\apk\debug\app-debug.apk (30.5MB).
Installing build\app\outputs\apk\app.apk...                  2.5s
I/FlutterActivityDelegate(16805): onResume setting current activity to this
Syncing files to device Android SDK built for x86...         2.4s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8109/
For a more detailed help message, press "h". To quit, press "q".
```

```
PS D:\Flutter Projects\startup_namer> flutter analyze
Analyzing D:\Flutter Projects\startup_namer...
No issues found!
Ran in 6.4s
```

## Flutter Doctor
```
PS D:\Flutter Projects\startup_namer> flutter doctor -v
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale de-CH)
    • Flutter version 0.2.8 at D:\flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\rschmidt\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 32-bit edition (version 1.21.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.11.2

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

• No issues found!
```
Cheers,
Roger

**Comment by maeni70** [comment]
Here all the details from debug console:

> Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk (30.5MB).
I/FlutterActivityDelegate(17133): onResume setting current activity to this
E/flutter (17133): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (17133): 'package:flutter/src/widgets/routes.dart': Failed assertion: line 177 pos 12: '!_transitionCompleter.isCompleted': Cannot install a MaterialPageRoute<dynamic> after disposing it.
E/flutter (17133): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
E/flutter (17133): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
E/flutter (17133): #2      TransitionRoute.install (package:flutter/src/widgets/routes.dart)
E/flutter (17133): #3      ModalRoute.install (package:flutter/src/widgets/routes.dart:740:11)
E/flutter (17133): #4      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1444:11)
E/flutter (17133): #5      RandomWordsState.build._popupMenuSelected (file:///D:/Flutter%20Projects/startup_namer/lib/main.dart:166:29)
E/flutter (17133): #6      _PopupMenuButtonState.showButtonMenu.<anonymous closure> (package:flutter/src/material/popup_menu.dart)
E/flutter (17133): #7      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (17133): #8      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (17133): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (17133): #10     Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (17133): #11     Future._completeWithValue (dart:async/future_impl.dart:477:5)
E/flutter (17133): #12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507:7)
E/flutter (17133): #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (17133): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter (17133): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17133): The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
I/flutter (17133): _WidgetsAppState#72d66](dirty, state: NavigatorState#cb7c6(tickers: tracking 2 tickers)):
I/flutter (17133): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1846 pos 12: '!_debugLocked':
I/flutter (17133): is not true.
I/flutter (17133):
I/flutter (17133): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17133): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17133): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17133):   https://github.com/flutter/flutter/issues/new
I/flutter (17133):
I/flutter (17133): When the exception was thrown, this was the stack:
I/flutter (17133): #2      NavigatorState.build (package:flutter/src/widgets/navigator.dart)
I/flutter (17133): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter (17133): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (17133): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (17133): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter (17133): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (17133): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (17133): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17133): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17133): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (17133): #12     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (17133): #13     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (17133): (elided 2 frames from class _AssertionError)
I/flutter (17133): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by maeni70** [comment]
Thanks for asking. Not important anymore. It was at my first steps with Flutter. Maybe I was doing something „stupid“... but it might still be interesting for you to find the cause.

**Comment by zoechi** [comment]
Thanks for the update

> but it might still be interesting for you to find the cause.

Yup, but too many such questions to investigate already ;-)

**Comment by iptton** [comment]
This problem  occurred to me now..
I wish to provide a simple demo to represent it.
and then.. **I found that's because I pass a function call but not an function to a button(so stupid)**:

`FloatingActionButton( 
//...
  onPessed: _showDialog(context) // a function to show dialog. here is the problem. because I define the function without return type, static check doesn't found the problem.
//...
)`

to all new-be of flutter , define  functions/variables with return type may save your life :)

**Comment by wangyongf** [comment]
> This problem occurred to me now..
> I wish to provide a simple demo to represent it.
> and then.. **I found that's because I pass a function call but not an function to a button(so stupid)**:
> 
> ```dart
> FloatingActionButton( 
> 
> //...
> 
>   onPessed: _showDialog(context) // a function to show dialog. here is the problem. because I define the function without return type, static check doesn't found the problem.
> 
> //...
> )
> ```
> 
> to all new-be of flutter , define functions/variables with return type may save your time :)

Thank you very much, you saved my life!

**Comment by Anyoks** [comment]
> This problem occurred to me now..
> I wish to provide a simple demo to represent it.
> and then.. **I found that's because I pass a function call but not an function to a button(so stupid)**:
> 
> ```dart
> FloatingActionButton( 
> 
> //...
> 
>   onPessed: _showDialog(context) // a function to show dialog. here is the problem. because I define the function without return type, static check doesn't found the problem.
> 
> //...
> )
> ```
> 
> to all new-be of flutter , define functions/variables with return type may save your time :)

Thank you very much. You save me so much time!!!

**Comment by zoujiejun** [comment]
> 这个问题现在发生在我身上.. 
> 我希望提供一个简单的演示来代表它。
> 然后.. **我发现那是因为我传递一个函数调用而不是一个函数到一个按钮（这么愚蠢）**：
> 
> ```dart
> FloatingActionButton（
> 
> // ...
> 
>   onPessed ： _showDialog（context）//一个显示对话框的函数。这是问题所在。因为我定义的函数没有返回类型，静态检查没有发现问题。
> 
> // ... 
> ）
> ```
> 
> 对于所有新的动态，使用返回类型定义函数/变量可以节省您的时间:)

Thank you !!!!!!!!!!!!!!!!!!
