### ISSUE TITLE
Accessibility: In material gallery app, activating drawer masks clicks last checkbox

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1716]
STEPS TO REPRODUCE:
1. Enable TalkBack.
2. Launch material gallery app.
3. Open the drawer.
4. Long-press on the mask.
5. Double tap.

The "Animate Slowly" checkbox gets checked instead of the drawer being dismissed.

**Comment by goderbauer** [comment]
This was recently fixed on iOS, Android probably needs a similar fix.

**Comment by goderbauer** [comment]
This is a dup of https://github.com/flutter/flutter/issues/1715.
