### ISSUE TITLE
Provide a way to specify behavior of error message on InputDecorator when it overflows

### ISSUE THREAD

**Issue by chrsfang** [flutter/flutter#17172]
Currently, error message on TextField ellipsis when it overflows.
There's no solid way to specify error message Text behavior like max lines and the TextOverflow type.

Specifying max lines could be done by wrapping the TextField in a DefaultTextStyle widget, but ideally there should be a way to specify behavior for error text/helper text

code:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L345

**Comment by mehmetf** [comment]
@HansMuller I don't see any recommendation on Text wrapping behavior on Material.

One alternative is to always wrap. Clipped error messages are an application problem. Error messages should be succinct, so we should just assume that and not clip. What do you think?

**Comment by HansMuller** [comment]
We could allow one to specify the number of lines to be occupied by the error/helper text via `InputDecoration`. That would essentially just provide a `maxLines` value for the corresponding text widget.

Should specifying a maxLines value > 1 increase the textfield's height? Or should the textfield just overflow its bounds in this (somewhat unusual) case?

**Comment by chrsfang** [comment]
I'll consult with them tomorrow. Thanks for the help.

**Comment by HansMuller** [comment]
@chrsfang  The difference between 2 and 3: i

Option 2 will make the text field's height match the maximum number of lines (see `Text.maxLines`) the error message might occupy.  Textfields that use maxLines values > 1 will be bigger than what Material specifies. Their height will not change when an error is displayed.

Option 3 will make the text field's height match the actual height of the wrapped error message.  That means that when an error message is displayed the text field's height might grow which may, in turn, disturb the overall layout that contains the text field.  For example, in a form with fields arranged in a scrollable list, the appearance of a text field might cause some of the form to scroll out of view.

**Comment by chrsfang** [comment]
@HansMuller 
Awesome, thanks!
