### ISSUE TITLE
firebase_remote_config using old Firebase Android SDK versions

### ISSUE THREAD

**Issue by bjon** [flutter/flutter#17188]
All the other flutterfire packages using firebase `15.+`, but remote config is using `[11.4.0,12.0[`.

Im not sure but i think this is the reason remote config package keeps crashing.
```
Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzexm>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzfjm;
```

**Comment by johnlabarge** [comment]
I'm seeing this.   Is there a workaround?

**Comment by johnlabarge** [comment]
Doing a PR.

**Comment by kmcnellis** [comment]
I'm seeing this as well

**Comment by bjon** [comment]
Fixed in https://github.com/flutter/plugins/pull/551

**Comment by kroikie** [comment]
@bjon

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/839. Any further collaboration will be done there.
