### ISSUE TITLE
Display error when I set language to 'Malaysia' 

### ISSUE THREAD

**Issue by YukiRed** [flutter/flutter#17182]
```
I/flutter ( 4941): The getter 'openAppDrawerTooltip' was called on null.
I/flutter ( 4941): Receiver: null
I/flutter ( 4941): Tried calling: openAppDrawerTooltip
I/flutter ( 4941): Another exception was thrown: NoSuchMethodError: The getter 'openAppDrawerTooltip' was called on null.
I/flutter ( 4941): Another exception was thrown: NoSuchMethodError: The getter 'signedInLabel' was called on null.
```

Why I got this error when I switch to Malay?

This is my supported language
```
static Iterable<Locale> get supportedLocales => [
    const Locale('en', 'US'),
    const Locale('ms', 'MY'),
    const Locale('zh', 'CN'),
];
```

**Comment by zoechi** [comment]
cross-ref https://stackoverflow.com/questions/50126855/display-error-when-i-set-language-to-malaysia-in-flutter

**Comment by zoechi** [comment]
Might be a dup of #13482

**Comment by zulfahmi93** [comment]
Flutter not yet supported 'ms' locale but my pull request for adding the locale already merged in #17121.

**Comment by HansMuller** [comment]
That's right. Support for Malay has landed in the Flutter repo but it's not in the dev channel yet.

For future reference, if you click on the commit that was merged into master (in this case https://github.com/flutter/flutter/commit/286cdf43f018583e84ded36e0eb26211db6bdd3f), it'll show you the tags that contain that commit. As of this writing, https://github.com/flutter/flutter/commit/286cdf43f018583e84ded36e0eb26211db6bdd3f is not yet associated with any tags, which means it's not on the dev channel yet.

**Comment by zoechi** [comment]
Looks like this landed a while ago.
