### ISSUE TITLE
AbsorbPointer's hitTest should only absorb if tap is inside it

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17180]
Otherwise it creates the very confusing behaviour where in a row, if there are 2 items side by side and the last item is an AbsorbPointer (because defaultHitTestChildren checks from the last to first children), the first item is not tappable even though the first item is tapped. 

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart#L2851

cc @Hixie in case there are scenarios where we want this behaviour that I'm missing.

**Comment by Hixie** [comment]
That's just a bug. When absorbing, it should return `size.contains(position)` instead of `true`.
