### ISSUE TITLE
Unable to build project on AppCenter (iOS)

### ISSUE THREAD

**Issue by diegodurli** [flutter/flutter#17197]
## Steps to Reproduce

I've tried to run a build on AppCenter (appcenter.ms), configuring my build as an `iOS` project, however, during the process the build tries to find a script called `xcode_backend.sh`, and since it does not find it, it fails the build with the following error:

`/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory`

I've attached below a full build log.

## Discussion

I do understand that flutter has it's own building process, however:

- There would be any way where I could make flutter build on AppCenter?
- If not, would it be a matter of waiting for AppCenter to add support for Flutter?

I appreciate your help!

## Logs

[Build Job Fail - AppCenter.ms.txt](https://github.com/flutter/flutter/files/1967871/Build.Job.Fail.-.AppCenter.ms.txt)

## Flutter Doctor

```
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.3.1 at /Users/diegodurli/Documents/Projects/FlutterEngine/flutter
    • Framework revision 12bbaba9ae (12 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/diegodurli/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/diegodurli/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.0

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • E6ECD6E0-560C-4557-88E4-6D1B573917A7 • ios         • iOS 11.3 (simulator)

• No issues found!
```

**Comment by artAst** [comment]
I resolved mine with trying to run `export FLUTTER_ROOT=/flutterpath` on terminal before executing xcode build

**Comment by diegodurli** [comment]
Hi @artAst!

Thanks for answering. My problem is specifically when running on `AppCenter` itself, not locally. Locally my build works normally.

I've got under the impression you're building locally. Let me know otherwise. Thanks!

**Comment by agrapine** [comment]
I've contacted AppCenter support. It would seem that it might be added later on.
Nothing for now.

But you can still build locally and upload the apk/ipa

**Comment by diegodurli** [comment]
That's right @agrapine, this can be done locally for now.
Closing this one.

**Comment by nosmirck** [comment]
Does this help you? https://github.com/Microsoft/appcenter-build-scripts-examples/tree/master/flutter

I found that on their github build script examples.

**Comment by schmorrison** [comment]
After asking a representative of appcenter that can be contacted using the live chat button in the apppcenter UI, we found out that the newest flutter apps have a default .gitignore file that excludes some necessary gradle-wrapper files from the Android folder. By including those files the projects is successfully detected as an Android project, and builds successfully as well.

**Comment by rubiktubik** [comment]
@schmorrison can you tell exactly how i should modify the default gitignore to make it work with flutter?
I removed the gradle-wrapper.jar but i not seems to work

**Comment by schmorrison** [comment]
This is the edited portion of my .gitignore file.

```
# Android related
# **/android/**/gradle-wrapper.jar
**/android/.gradle
**/android/captures/
# **/android/gradlew
# **/android/gradlew.bat
**/android/local.properties
**/android/**/GeneratedPluginRegistrant.java
```

**Comment by rubiktubik** [comment]
It workes fine! Thank you. You saved me alot of time!
