### ISSUE TITLE
Scrolling a page with a big toolbar shows white above the toolbar

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1719]
e.g. gallery app, open components: when you drag down, you see white above the toolbar.

**Comment by HansMuller** [comment]
This is because the Scrollable that's driving the toolbar animation has overscroll behavior turned on.

Overscrolling should be turned off when the scrollable has this role however I think applications will have to do that.  Will see if I can DTRT in the gallery app.

**Comment by Hixie** [comment]
I can see two "correct" behaviours: you just can't overscroll, and, if you overscroll you get the toolbar background.
