### ISSUE TITLE
When an item in a lazy list is being dismissed, we should keep it alive

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#172]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Sep 25, 2015 at 19:37 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1347_

---

Currently, if you scroll the item being dismissed off the screen, then scroll it back, it isn't being dismissed anymore. Also, if you scroll it off and wait, after a bit the list jumps up. Not smooth.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Friday Sep 25, 2015 at 19:57 GMT_

----

This manifests really badly when you dismiss multiple items at once when you've scrolled off-screen, because once one is entirely done it resets the size cache and this requeries the items for their size, which then causes them to reappear on-screen at their original size.

To reproduce, launch card_collection, dismiss items 0 through 6 with a short pause between each one, then scroll so the top item is item 7. Now watch as nothing happens, then suddenly items bounce up and down.

(You'll want to increase the scheduler time dilation to 100.0 or some such.)

**Comment by Hixie** [comment]
See also #105; the same fix should fix both.
