### ISSUE TITLE
No way to get true device orientation

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#17215]
There doesn't appear to be a way to get the device orientation in flutter without resorting to methodChannels. I've taken a look at OrientationBuilder and it doesn't do what I need as it doesn't differentiate between the left and right landscape modes. I may be missing it but I haven't seen any way to get the orientation directly including this information. If I did miss it, I'd appreciate being told I'm wrong! =D

The issue I'm having is that I'm writing a plugin which interfaces with the camera. I'm using the texture API to display the preview image.

Without 1) stopping and starting the preview each time a rotation happens on the android side, or 2) stopping and starting the preview on the flutter side each time a rotation happens, I'm not able to display the preview correctly when the screen is rotated.

I'm working around this for the plugin by simply sending an orientation change event of my own, but this is not ideal.

Note that as notches become more popular, it might become more important to be able to differentiate landscape left & landscape right....

**Comment by Rockvole** [comment]
Can you not do something like :

    double screenWidth = MediaQuery.of(context).size.width;
    double screenHeight = MediaQuery.of(context).size.height;

When screenWidth > screenHeight its landscape.

**Comment by rmtmckenzie** [comment]
Thanks for the  comment @Rockvole but I'm aware of that; that is exactly what OrientationBuilder does. However, that doesn't solve the problem as I explained because it doesn't differentiate between left and right landscape modes. I need to rotate the texture to keep the image upright regardless of which orientation it is at.

**Comment by anilcancakir** [comment]
The Flutter gets the orientation by matching width and height. So, if you want to know left or right landscape orientation, it should be hard. Because, the media query returns only two options.

Using
```dart
MediaQuery.of(context).orientation
```

Please look document of this property
https://docs.flutter.io/flutter/widgets/MediaQueryData/orientation.html

**Comment by rmtmckenzie** [comment]
Thanks for the response @anilcancakir, But the MediaQuery orientation is ostensibly the same as OrientationBuilder's. And locking to only one landscape is not an option as I'm writing a plugin that needs to be flexible. Imagine using a plugin and then finding out that you have to restrict your app's orientation or it doesn't work - I'd certainly be frustrated.

What this is, is me asking for someone on the flutter team to consider adding a more useful property that describes which way the device is actually orientated (i.e. PortraitUp, PortraitDown, LandscapeLeft, and LandscapeRight).

FYI - for my app, I only need portrait mode, so this is just for other people using the plugin.

**Comment by Rockvole** [comment]
It looks like in Android there is only 2 properties :
ORIENTATION_PORTRAIT & ORIENTATION_LANDSCAPE
https://developer.android.com/reference/android/content/res/Configuration#orientation_portrait

**Comment by rmtmckenzie** [comment]
There's also the rotation of the screen, using `((WindowManager) context.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay().getRotation();`.

**Comment by lewixlabs** [comment]
Hi,
OrientationBuilder, using Flutter 0.3.2 with Android Emulator, seems not correctly working (with MediaQuery i have not this issue).

I attach this screenshot, is it the same issue you are talking about? If not, sorry, i will move this ticket.

![image](https://user-images.githubusercontent.com/7371215/40129525-c1802db4-5934-11e8-9870-134045b1f0e1.png)

**Comment by rmtmckenzie** [comment]
So just leaving this here - I've written [a plugin](https://pub.dartlang.org/packages/native_device_orientation) that gets the native device orientation (i.e. portrait up/down, landscape left/right). 

I'd still like to something like this make it into flutter at some point though - something within flutter obviously knows right vs left, so it would be nice to expose that (especially for dealing with notches).

**Comment by zoechi** [comment]
According to the docs OrientationBuilder provides the orientation of the parent widget, not the orientation of the device.

**Comment by timsneath** [comment]
Thank you for the great plugin contribution! 

I'm going to close this for the time being, since the original issue is resolved and we are continuing to keep the core Flutter framework small.
