### ISSUE TITLE
floatingActionButton contains a Row

### ISSUE THREAD

**Issue by rahichesoft** [flutter/flutter#17211]
## Steps to Reproduce

```
new Scaffold(
      appBar: new AppBar(),
      floatingActionButton: new Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          new FloatingActionButton(onPressed: null),
          new FloatingActionButton(onPressed: null),
        ],
      ),
    );
```
![Image](https://i.imgur.com/KEi75pJ.png)
the first **FloatingActionButton** is not in the correct place i need to add padding to make it right
![Image](https://i.imgur.com/cE1WftN.jpg)

**Comment by HansMuller** [comment]
This is definitely not the use-case that the scaffold's layout was intended for, in fact layouts with more than one FAB are called out as a bad idea in the Material design spec.  However.

What's happening in this case is that the scaffold is laying out the Row with a width constraint that matches the width of the screen.  The MainAxisAlignment.spaceBetween constraint causes the FABs to appear at either end of the row. Then the Scaffold's default [floatingActionButtonLocation](https://docs.flutter.io/flutter/material/Scaffold/floatingActionButtonLocation.html) causes the row's location to be adjusted to the left a bit, as you can see.

If you really want to do this, consider writing a custom `FloatingActionButtonLocation` that puts the FAB where you want it.

**Comment by rahichesoft** [comment]
thank you @HansMuller

**Comment by mistercx** [comment]
I've the same. So, it's bug or feature?

**Comment by jhonnnsx** [comment]
use MainAxisAlignment.end
