### ISSUE TITLE
Verify the CPU and memory cost of a rotating and fading image

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17217]
https://mp.weixin.qq.com/s/j9ibj4ZYAqNZwwvSpIAtLA states a 64% simulator CPU usage which is plausible but also seems like a bug. 

Could be related to #13203 and/or iOS simulator only too

**Comment by uloga** [comment]
I see this same issue with any type of animations or gifs on IphoneX Simulator and Hardware even when using CircularProgressIndicator().

**Comment by liyuqian** [comment]
@xster : is this a duplicate of https://github.com/flutter/flutter/issues/13203 as you can't reproduce it on real iOS devices? If so, can we close this in favor of https://github.com/flutter/flutter/issues/13203?

**Comment by chinmaygarde** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/13203
