### ISSUE TITLE
TextFormField Validator not showing validator message

### ISSUE THREAD

**Issue by bowojori7** [flutter/flutter#17226]
I tried to create this form with validation, so it shows the errors when the user returns each field. But for some reason it doesn't work. I have no reason why. I'm just stuck now. 

Here's the code:
`
    import 'package:flutter/material.dart';
    import 'package:validate/validate.dart';
    
    void main() => runApp(new MaterialApp(
      title: 'Forms in Flutter',
      home: new LoginForm(),
      theme: ThemeData.dark(),
    ));
    
    class LoginForm extends StatefulWidget {
      String email;
      String password;
      final Function saveEmail;
      final Function savePassword;
      final Function attemptLogin;
    
      LoginForm({this.email, this.password, this.saveEmail, this.savePassword,
        this.attemptLogin});
    
      @override
      LoginFormState createState(){
        return new LoginFormState();
      }
    }
    
    class LoginFormState extends State<LoginForm> {
      final loginFormKey = GlobalKey<FormState>();
      final emailController = new TextEditingController();
      final passController = new TextEditingController();
    
      @override
      Widget build(BuildContext context) {
        return new Scaffold(
            appBar: new AppBar(
              title: new Text('Login'),
            ),
            body: new Container(
              padding: new EdgeInsets.all(10.0),
              child: new Form(
                key: loginFormKey,
                child: new Column(
                  children: <Widget>[
                    new Row(
                      children: <Widget>[
                        new Container(
                          width: 2.0,
                          height: 18.0,
                          color: Colors.white,
                        ),
                        new Container(
                            width: 5.0,
                            height: 0.0
                        ),
                        new Expanded(child: new TextFormField(
                          decoration: new InputDecoration.collapsed(
                            hintText: "EMAIL",
                          ),
    
                          validator: (String value) {
                            if (!Validate.isEmail(value)) {
                              return 'Please enter Email';
                            }
                          },
                          onFieldSubmitted: (val) {
                            print(loginFormKey.currentState.validate());
                            if (loginFormKey.currentState.validate()) {
                              widget.email = val;
                              widget.saveEmail(val);
                            }
                          },
                          controller: emailController,
    
                        ),)
                      ],
    
                    ),
    
                    new Row(
                      children: <Widget>[
                        new Container(
                          width: 2.0,
                          height: 18.0,
                          color: Colors.white,
                          padding: const EdgeInsets.fromLTRB(0.0, 0.0, 5.0, 0.0),
                        ),
                        new Container(
                            width: 5.0,
                            height: 0.0
                        ),
                        new Expanded(child: new TextFormField(
                          obscureText: true,
                          decoration: new InputDecoration.collapsed(
                              hintText: 'PASSWORD',
                          ),
                          validator: (val) =>
                          val.length < 6 ?
                          'Still too short' : '',
                          onFieldSubmitted: (val) {
                            if (loginFormKey.currentState.validate()) {
                              widget.email = emailController.text;
                              print(widget.email);
                              widget.saveEmail(emailController.text);
                              widget.password = val;
                              print(widget.password);
                              widget.savePassword(val);
                              widget.attemptLogin();
                            }
                          },
                          controller: passController,
                        ),)
                      ],
                    )
                  ],
                ),
              ),
            )
        );
      }
    }
`
I really don't know what's causing this. It seems like everything in the onfieldSubmitted part of the fields don't work. If I remove the If statements, they work okay, but once it's added it gives no response.

Seems like something simple but I'm just missing the point. Any help would be greatly appreciated. Thanks.

**Comment by HansMuller** [comment]
I don't understand exactly what you mean by "it doesn't work".  Please provide a description of the problem that's roughly like: user did _this_, user expected _that_ to happen, but _that_ did not happen.

Looking through the code, I noticed a few things: 

Your validator callbacks should return null if the field is valid.

When the onFieldSubmitted callbacks change the state of the LoginForm, the state change should be wrapped in `setState(() { your change here })` so that the widget is rebuilt.

**Comment by HansMuller** [comment]
For an example of TextFormFields with validation, see https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart

**Comment by bowojori7** [comment]
Thank you @HansMuller, the example helped me see a couple things I was doing wrong. I went ahead to implement validation through a Snackbar though.

**Comment by krngd2** [comment]
The reason its not working is because Validator needs to be returned a `null` in order to show the message. Simple '' empty quotes is not null so its not showing.
replace validator with 

> validator: (val) =>
                      val.length < 6 ?
                      'Still too short' : null,

**Comment by theepag** [comment]
if we add a container inside a form, still the validation work?

**Comment by JigarMangukiya7876** [comment]
> if we add a container inside a form, still the validation work?

hi @theepag 
yes it is still works.
Thanks.

**Comment by theepag** [comment]
Thank you !

**Comment by goga133** [comment]
> 
> 
> For an example of TextFormFields with validation, see https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart
404 :(

**Comment by prateekmedia** [comment]
> > For an example of TextFormFields with validation, see https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart
> 
> 404 :(

You ca  Use the magical powers of your favourite search engine

https://github.com/flutter/gallery/blob/master/lib/demos/material/text_field_demo.dart
