### ISSUE TITLE
Android: AppBar IconButton action doesn't trigger onPressed

### ISSUE THREAD

**Issue by ffeu** [flutter/flutter#17222]
I hope this is me doing something wrong, but following code works fine on iOS simulator, but doesn't work on Android Emulator. Same result on both dev and beta channels.

## Steps to Reproduce

- Run following program on Android emulator and iOS simulator.
- Pressing the button should print 'onPressed' on the console.
- Long-pressing should show tooltip.

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'AppBar Action Demo',
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text("App Bar Title"),
          actions: <Widget>[
            new IconButton(
              icon: new Icon(Icons.add),
              tooltip: 'Action Tool Tip',
              onPressed: () { 
                print("onPressed");
              },
            ),
          ])));
  }
}
```

## Flutter Doctor

```
>flutter doctor -v
[✓] Flutter (Channel dev, v0.3.5, on Mac OS X 10.12.6 16G1114, locale en-BR)
    • Flutter version 0.3.5 at /Users/feu/Projects/flutter
    • Framework revision 7ffcd3d22d (8 days ago), 2018-04-24 14:03:41 -0700
    • Engine revision ec611470b5
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/feu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.0

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.0.0(API 26) (emulator)
    • iPhone SE                 • 53063166-68D3-41F4-A114-8F58BA11976A • ios         • iOS 11.2 (simulator)

• No issues found!
```

**Comment by xster** [comment]
Nothing jumps out at me looking at the code. Consider using `debugPrintHitTestResults` while running and use in conjunction with the 't' key to dump the render tree to look at which render object absorbed the touch.

**Comment by ffeu** [comment]
As soon as I placed the debugPrintHitTestResults, it started working. Then, I removed the debugPrintHitTestResults and it was working alright. :-O My original app started working too (no code has changed).

As nothing changed in my environment, I'm blaming the Android emulator. :)

```
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
  debugPrintHitTestResults = true;
  runApp(new MyApp());
}

...
```

**Comment by xster** [comment]
This seems suspicious. How did you re-execute the code originally? Was it hot reload or did you re-run `flutter run` each time?

**Comment by ffeu** [comment]
```flutter run``` each time! a few times debugging through VS Code, a few times pressing R, a few times 'q' and run again...

On my original app, I spent some time testing against iOS only. Suddenly I switch to Android and nothing is working anymore...

switched channels, upgraded, restarted the android emulator... not working.

Then I created that simple app _from scratch_. with ```flutter create```! And found the some problem. That's when I created the issue.

And then, the problem suddenly disappears, no changes at all. I _*did*_ restart the android emulator once more... still, it's quite mysterious.

**Comment by lionoggo** [comment]
@ffeu 
How did you solve this problem?

**Comment by ffeu** [comment]
I didn't, it suddenly disappeared after a few emulator restarts - and never happened again with me.

**Comment by aliak00** [comment]
This happened to me just now as well. Reran on android emulator a few times, was not getting the `onPressed` event, stopped and reran and still nothing. 

Relaunched on iOS emulator and it worked. 

Ran `flutter clean` and still didn't work on android.

Created new emulator and it worked on android 🤷‍♂️ 

```
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.amber[200],
        body: SafeArea(
          child: Center(
            child: Example(
              counter: 7,
            ),
          ),
        ),
      ),
    );
  }
}

class Example extends StatefulWidget {
  final int counter;

  const Example({Key? key, required this.counter}) : super(key: key);

  @override
  _ExampleState createState() => _ExampleState(counter);
}

class _ExampleState extends State<Example> {
  late int _counter;
  _ExampleState(int c) {
    _counter = c;
    print('init');
  }
  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        IconButton(
          icon: Icon(Icons.person),
          onPressed: () {
            print('pressed2');
          },
        ),
        IconButton(
          icon: Icon(Icons.person),
          onPressed: () {
            setState(() {
              _counter++;
            });
            print('pressed');
          },
        ),
        Text('${_counter}'),
      ],
    );
  }
}
```

**Comment by ffeu** [comment]
It's interesting as it looks like an Android Emulator bug, but it's suspicious that you had the same problem with `IconButton` too.

**Comment by aliak00** [comment]
Ah! I did not notice that it was `IconButton` as well! I agree that it's a bit suspicious indeed.
