### ISSUE TITLE
image_picker resize image

### ISSUE THREAD

**Issue by vagrantrobbie** [flutter/flutter#17227]
Is it possible at the moment to resize an image without "locking up" the Flutter app UI?

I am using the image_picker plugin to pick an image from the device's Photo Gallery and image.dart lib https://pub.dartlang.org/packages/image to resize the chosen image to a more manageable resolution and then upload it to Firebase Cloud Storage. While the image decoded and then encoded the Flutter UI locks up. Could a chosen image size be generated if passed to .getImage()?

**Comment by vagrantrobbie** [comment]
Thanks for the response. 

I have this working now! After resizing the image, I write the bytes back to a temporary file, upload it and then delete the temp. It works well most of the time but I am having the odd device crash (iPhone 5s). Is there a good way to debug this? 

Some times this error is thrown on the resize
[VERBOSE-2:dart_isolate.cc(713)] Isolate (149972410) 'main.dart:_spawn()' exited with an error
[VERBOSE-2:dart_error.cc(16)] isolate terminated by Isolate.kill

Is there a maximum of isolates that can be called at once? Do we need to clean them up?

**Comment by urbanmania** [comment]
@vagrantrobbie did you ever get this sorted? I'm having similar problems, odd crashes on older devices.

**Comment by zoechi** [comment]
@vagrantrobbie I don't think there is a hard limit of isolates, but they take up memory and if you run to many at once you can easily run out of memory.

@urbanmania please add details about the problems.

**Comment by urbanmania** [comment]
ok, thanks. I'm looking at this plugin now to get around this problem https://github.com/btastic/flutter_native_image

**Comment by vagrantrobbie** [comment]
@urbanmania I never really fixed the problem but with a clean run on the app and no hot reloading the error was infrequent enough for me to be happy.

ImagePicker plugin has a maxWidth property which I utilised 
ImagePicker.pickImage(source: ImageSource.gallery, maxWidth: 800.0); and this was enough to fix my problem

**Comment by urbanmania** [comment]
ah, had forgotten about that, I should look into that, thanks for reminding me of that.

**Comment by zoechi** [comment]
@vagrantrobbie do you think there is still something the Flutter team needs to do?
The `ImagePicker` issue you mentioned should better be reported in a new issue.

**Comment by vagrantrobbie** [comment]
@zoechi sorry for the late reply. I consider this closed. Thanks for following!

**Comment by zoechi** [comment]
@vagrantrobbie thanks for the status update!

**Comment by dooboolab** [comment]
@zoechi @vagrantrobbie I think this isn't enough since we need to generate the `thumbnail` for every image in general. Therefore `maxWidth: 800.0` property is not enough. I've played around with `flutter-native-image` for this currently but I think ImagePicker should support this feature itself.

**Comment by zoechi** [comment]
@dooboolab I think it's better to create a new issue.
