### ISSUE TITLE
TensorflowJS Plugin Dart-Flutter

### ISSUE THREAD

**Issue by rubencg195** [flutter/flutter#17233]
Is there an integration of Tensorflow JS for dart/Flutter?

**Comment by jonahwilliams** [comment]
Flutter does not compile to JavaScript so it's not possible to use Dart/JavaScript interop libraries.  I'm not familiar with the Tensorflow Android or iOS, but the standard practice for using native libraries like these is through a plugin.

**Comment by JonathanSum** [comment]
Hi, rubencg192. I saw this last week, and I hope this one is helpful to you: [dartl/packages/tensorflow_lite](https://pub.dartlang.org/packages/tensorflow_lite).
This package is kind of new, and it only works on Android.

**Comment by rubencg195** [comment]
Thank you @JonathanSum.

**Comment by CUGProject** [comment]
Oh,I success to use tensorflow.js in flutter throw webview

**Comment by Khalid-Nowaf** [comment]
I would use [flutter_tflite](https://pub.dev/packages/tflite) for now.

**Comment by stuartmorgan** [comment]
Closing since per https://github.com/flutter/flutter/issues/17233#issuecomment-386181011 the specific request here isn't viable on most platforms.
