### ISSUE TITLE
Appbar isn't magnetic (should snap open or closed)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1723]
A toolbar like in the Ali Connors demo should either:
- scroll off the screen, but be magnetic when near its short height so that if you let go, it snaps to that height, or
- not scroll, gain a shadow when it reaches its short height, and have the page go under it.

We do a hybrid approach where we get a shadow, but still scroll with the content, and do nothing magnetic.

**Comment by eseidelGoogle** [comment]
Another AppBar bug.  @HansMuller  :)  This may be too big of a fix for the first release of the gallery.

**Comment by Hixie** [comment]
@HansMuller Is this on your radar for after i18n?

**Comment by HansMuller** [comment]
I'm happy to do something about it however I think it would be worth getting some UX feedback about snapping behavior.  Not all apps that could snap do snap and sometimes - IMHO - apps like Google Newsstand that do incorporate some appbar snapping behavior may end up being more distracting than feeling natural.

**Comment by Hixie** [comment]
Ok, let's close this for now and address this reactively instead.
