### ISSUE TITLE
Looking for Overlay Field feature on Map

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#17246]
Flutter team we are are developing app for farmers where we want to overlay 2 search fields ( crop name and location) over map. 
Similar to overlay fields appearing in Uber. 
Looks like that feature is not supported in flutter. 
Any one know how to achieve that using flutter? 
Does anyone has any plugin for this?

**Comment by zoechi** [comment]
Did you check https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter
It might still miss some features though.
