### ISSUE TITLE
Does the Gallery demo display correctly?

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#17242]
![7943780fde895d2194eb259b7f1dc725](https://user-images.githubusercontent.com/13853/39565033-005c942e-4ee9-11e8-90dd-181c2403b647.jpg)

**Comment by mit-mit** [comment]
That looks add. Can you paste the output of `flutter doctor -v`, please?

**Comment by HxBreak** [comment]
dev channel ?

**Comment by HansMuller** [comment]
Have you `flutter update-packages`?

The gallery depends on an icon font from the gallery-assets package.

**Comment by realcarlos** [comment]
@HxBreak master channel

@HansMuller yes I did

**Comment by realcarlos** [comment]
@mit-mit 

$ flutter doctor -v
[✓] Flutter (Channel master, v0.3.6-pre.113, on Mac OS X 10.13.2 17C88, locale zh-Hans-CN)
    • Flutter version 0.3.6-pre.113 at /Users/xxx/Documents/GitHub/flutter
    • Framework revision d820e5f3b1 (79 minutes ago), 2018-05-03 22:27:29 -0700
    • Engine revision e976be13c5
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (3 available)
    • A1601                                       • EM6TP7IVQKNR8SDQ                     • android-arm64 • Android 5.1 (API 22)
    • Samsung Galaxy S8, 7 0 0, API 24, 1440x2960 • 192.168.56.101:5555                  • android-x86   • Android 7.0 (API 24)
    • iPhone 6s                                   • 07F5411B-04C3-45BE-8608-87DC5A3E1F10 • ios           • iOS 11.2 (simulator)

**Comment by zoechi** [comment]
Closing as dup of #17485 because there is more discussion
