### ISSUE TITLE
Provide a way to Select Material Colors from an Image

### ISSUE THREAD

**Issue by agrosner** [flutter/flutter#17245]
https://developer.android.com/training/material/palette-colors

You already support material palettes. What would be nice is to be able to pick colors from an image and use that as basis for customized UI. It really would be amazing to get that on Flutter.

If there is already a way, I could not find it via searching.

**Comment by zoechi** [comment]
https://github.com/flutter/packages/pull/2 might provide that as well.

**Comment by goderbauer** [comment]
Looks like https://pub.dartlang.org/packages/palette_generator solved this? Is there anything missing? Otherwise we should close this bug.

**Comment by agrosner** [comment]
Yes this looks good. I was awaiting a native flutter version instead of reloading image in native space.
