### ISSUE TITLE
labelStyle != null assertion Fails in flutter/src/material/chip_theme.dart

### ISSUE THREAD

**Issue by VineshRaju** [flutter/flutter#17251]
I am using Flutter (Channel dev, v0.3.5, on Mac OS X 10.13.5 17F45c, locale en-IN)
I am getting an assertion failed on the following file.

'package:flutter/src/material/chip_theme.dart': Failed assertion: line 218 pos 12: 'labelStyle != null': is not true.

When the exception was thrown, this was the stack:
I/flutter (27821): #2      new ChipThemeData.fromDefaults (package:flutter/src/material/chip_theme.dart)
I/flutter (27821): #3      new ThemeData (package:flutter/src/material/theme_data.dart:173:23)
I/flutter (27821): #4      MyApp.build (file:///Users/vineshraju/Development/Melaan/melaan/lib/main.dart:25:18)
I/flutter (27821): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3687:28)
I/flutter (27821): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
I/flutter (27821): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (27821): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter (27821): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter (27821): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter (27821): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter (27821): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter (27821): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter (27821): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter (27821): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
I/flutter (27821): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter (27821): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter (27821): #18     runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter (27821): #19     main (file:///Users/vineshraju/Development/Melaan/melaan/lib/main.dart:11:3)
I/flutter (27821): #20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (27821): #21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (27821): (elided 2 frames from class _AssertionError)

**Comment by VineshRaju** [comment]
Defining '''chipTheme''' inside '''theme''' of '''MaterialApp''' seems to help resolving the issue

**Comment by HansMuller** [comment]
cc @gspencergoog

**Comment by gspencergoog** [comment]
Hmm.  This appears (from) to be something that should happen even with every app, but that's not happening.  Can you give me some more context to go on, maybe some simple code that fails?

My suspicion from looking at the ThemeData code is that your textTheme doesn't have a body2 style set.

**Comment by VineshRaju** [comment]
Yes, There is no definition for body2 in my ThemeData.  I have defined only headline and caption.
Wont the default style be taken if its not defined?
