### ISSUE TITLE
[video_player plugin] Get the aspect ratio/witdth-height or preserve the aspect ratio of a video

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#17254]
Hi, I have to download multiple online videos of different and unknown aspect ratio, and I would like to know if there is a way or if there will be a way to get the aspect ratio (or resolution) of the video, or simply have a bool that let's you decide if to resize the video (like images).

Thank you.

**Comment by Ivaskuu** [comment]
Nevermind.. it's the value property

**Comment by AkramChauhan** [comment]
Can you explain how you did it.

Thanks in advance.

**Comment by lifenautjoe** [comment]
@Ivaskuu , could you elaborate please?
