### ISSUE TITLE
video_player plugin video not playing with some Samsungs

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#17252]
There seem to be an issue with the skia rendering the images and some Samsungs. I'm trying with the S5. Tried with iPhone and it works great, however in Samsung this is the stack trace when the video kicks in (I get this stack exception on loop as the video goes on, since I can still listen to the sound).

> D/skia    ( 2422): GLSL compilation error
D/skia    ( 2422): ----------------------
D/skia    ( 2422): GLSL:
D/skia    ( 2422):    1	#version 310 es
D/skia    ( 2422):    2	
D/skia    ( 2422):    3	#extension GL_OES_EGL_image_external : require
D/skia    ( 2422):    4	#extension GL_OES_EGL_image_external_essl3 : require
D/skia    ( 2422):    5	precision mediump float;
D/skia    ( 2422):    6	out mediump vec4 sk_FragColor;
D/skia    ( 2422):    7	uniform lowp samplerExternalOES uTextureSampler_0_Stage0;
D/skia    ( 2422):    8	uniform lowp sampler2D uTextureSampler_1_Stage0;
D/skia    ( 2422):    9	uniform lowp sampler2D uTextureSampler_2_Stage0;
D/skia    ( 2422):   10	uniform lowp sampler2D uTextureSampler_3_Stage0;
D/skia    ( 2422):   11	flat in mediump vec4 vcolor_Stage0;
D/skia    ( 2422):   12	in highp vec2 vtextureCoords_Stage0;
D/skia    ( 2422):   13	flat in highp int vtextureIdx_Stage0;
D/skia    ( 2422):   14	void main() {
D/skia    ( 2422):   15	    mediump vec4 outputColor_Stage0;
D/skia    ( 2422):   16	    {
D/skia    ( 2422):   17	        outputColor_Stage0 = vcolor_Stage0;
D/skia    ( 2422):   18	        highp vec2 texCoord;
D/skia    ( 2422):   19	        texCoord = vtextureCoords_Stage0;
D/skia    ( 2422):   20	        highp int texIdx;
D/skia    ( 2422):   21	        texIdx = vtextureIdx_Stage0;
D/skia    ( 2422):   22	        switch (texIdx) {
D/skia    ( 2422):   23	            case 0:
D/skia    ( 2422):   24	                outputColor_Stage0 = outputColor_Stage0 * texture(uTextureSampler_0_Stage0, texCoord);
D/skia    ( 2422):   25	                break;
D/skia    ( 2422):   26	            case 1:
D/skia    ( 2422):   27	                outputColor_Stage0 = outputColor_Stage0 * texture(uTextureSampler_1_Stage0, texCoord);
D/skia    ( 2422):   28	                break;
D/skia    ( 2422):   29	            case 2:
D/skia    ( 2422):   30	                outputColor_Stage0 = outputColor_Stage0 * texture(uTextureSampler_2_Stage0, texCoord);
D/skia    ( 2422):   31	                break;
D/skia    ( 2422):   32	            case 3:
D/skia    ( 2422):   33	                outputColor_Stage0 = outputColor_Stage0 * texture(uTextureSampler_3_Stage0, texCoord);
D/skia    ( 2422):   34	                break;
D/skia    ( 2422):   35	        }
D/skia    ( 2422):   36	    }
D/skia    ( 2422):   37	    {
D/skia    ( 2422):   38	        sk_FragColor = outputColor_Stage0;
D/skia    ( 2422):   39	    }
D/skia    ( 2422):   40	}
D/skia    ( 2422):   41	
D/skia    ( 2422): Errors:
D/skia    ( 2422): 0:4: P0003: Extension 'GL_OES_EGL_image_external_essl3' not supported
D/skia    ( 2422): 0:1: Warning: GL_OES_EGL_image_external is deprecated in ESSL 3 and later versions

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by miguelpruivo** [comment]
Fixed by following these @zoechi steps, since it's fixed on the revision e976be13c5 engine:

> @miguelpruivo flutter channel master
if that doesn't work run git clean -xffd in the Flutter install directory and then flutter doctor
