### ISSUE TITLE
Implement better logic in golden file comparators

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#17258]
Follow-up work to https://github.com/flutter/flutter/issues/16859:

The current golden file comparator (both [`LocalFileComparator `](https://github.com/flutter/flutter/blob/d0125d94b095ad2b768d9c10c74960a4dc335036/packages/flutter_test/lib/src/goldens.dart#L120) and [`FlutterGoldenFileComparator `](https://github.com/flutter/flutter/blob/d0125d94b095ad2b768d9c10c74960a4dc335036/packages/flutter_goldens/lib/flutter_goldens.dart#L37)) are very simplistic.  They compare encoded PNG bytes and report failure if the byte-for-byte comparison turned up any differences.

What would be more useful would to be for the comparator to decode the PNG to raw pixels and reporting which pixels differ - optionally being configurable to allow for a tolerance of N number of pixel differences allowed before it reports as a failure (or even N RGB allowable differences per pixel, and M allowable pixels different outside of the N tolerance).

To do this, we would either need to:

1. Use `package:image` to decode the PNG bytes.

    ```dart
    PngDecoder decoder = new PngDecoder();
    Image image = decoder.decodeImage(pngBytes);
    Uint8List rawPixels = image.data;
    ```

1. Use `dart:ui` to decode the PNG bytes:

    ```dart
    Codec codec = await instantiateImageCodec(pngBytes);
    assert(codec.frameCount == 0);
    FrameInfo frameInfo = await codec.getNextFrame();
    ByteData rawPixels = await frameInfo.image.toByteData();
    ```

We probably also want to allow the augment the `GoldenFileComparator` API to allow it to declare the preferred format in which it receives image bytes during the call to `compare()`.  Then the matcher would consult the comparator and request the appropriate format up-front, thus saving the comparator from having to convert the recorded image.

**Comment by apaatsio** [comment]
`matchesReferenceImage` already compares pixels and it can report things like `does not match as width or height do not match` and `does not match on N pixels`. Maybe that code can be reused here. I think it would make sense that `matchesReferenceImage` and `matchesGoldenFile` worked in a similar fashion.
