### ISSUE TITLE
Create a SceneBoundary widget

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17271]
Create a RepaintBoundary like widget that indicates that its complex widget subtree is static and should be raster cached with an eviction mechanism in the render object.

**Comment by Hixie** [comment]
Should we just expose the bits on RepaintBoundary?

**Comment by Hixie** [comment]
Unassigning and clearing milestone since my understanding is @xster is working on iOS features now.

**Comment by liyuqian** [comment]
@xster : is this still something that you'd like to pursue considering our newly added retained-engine-layer subtree raster cache? (See https://github.com/flutter/flutter/issues/21756 and https://github.com/flutter/flutter/issues/23535)

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
