### ISSUE TITLE
Add option to customize TabBar animation speed

### ISSUE THREAD

**Issue by harrisonturton** [flutter/flutter#17272]
Hello,

It'd be fantastic to be able to customize the `TabBar` swipe animation speed. This has come up previously in [#7479](https://github.com/flutter/flutter/issues/7479#issuecomment-386323427), but back then it was too fast.

For example, when I compare it to Twitter, the animation feels a bit sluggish.

This isn't a huge issue, and I could probably make a PR if someone points me in the right direction 😄

**Comment by VinciShark** [comment]
Also need this feature.

**Comment by micimize** [comment]
Can't we just add a `duration` argument, and use it as the default for `_changeIndex`?

**Comment by LucasSu520** [comment]
I think we should add duration argument for the _changeIndex

**Comment by PaulLVoelker** [comment]
Any updates or work-arounds here?

**Comment by PaulLVoelker** [comment]
You can control the general physics of the scroll animation.

```
TabBarView(
  physics: CustomTabBarViewScrollPhysics(),
            
```

**Control the scroll behavior:**

```

class CustomTabBarViewScrollPhysics extends ScrollPhysics {
  const CustomTabBarViewScrollPhysics({ScrollPhysics? parent})
      : super(parent: parent);

  @override
  CustomTabBarViewScrollPhysics applyTo(ScrollPhysics? ancestor) {
    return CustomTabBarViewScrollPhysics(parent: buildParent(ancestor)!);
  }

  @override
  SpringDescription get spring => const SpringDescription(
        mass: 50,
        stiffness: 100,
        damping: 0.8,
      );
}

```
You should also be able to calculate the duration with mass, stiffness, damping, but I believe having those options is even better suited for your problem. [Source][1]


  [1]: https://github.com/flutter/flutter/issues/55103#issuecomment-747059541
