### ISSUE TITLE
Flutter Post API

### ISSUE THREAD

**Issue by NavjeetSaini26** [flutter/flutter#17279]
How can i work with post API with parameters in Flutter . I need methods for post API (for login/singup page). But no tutorials available for post API .

**Comment by zoechi** [comment]
I think this question is better asked on StackOverflow (with more details)

**Comment by NavjeetSaini26** [comment]
yeah but i want full demo for post api with parameters. but on StackOverflow little information is available. so that tutorial is not understandable for me .
