### ISSUE TITLE
Create a BoundaryLayer that self evicts

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17275]
Use with #17271 to perform the function of #17270 but implicitly in the engine. 

Instead of the framework calling pushScene with a cached scene and then swapping out the call to pushing a different layer tree once the cache is broken, let the cache eviction be implicit too. 

Insert a BoundaryLayer with the layer tree it should have. It caches it and value hashes its descendent. 

Once the subtree changes, auto evict and start drawing the new tree.

**Comment by Hixie** [comment]
Spoke to @cbracken and it's not on his radar. Moving back to Goals milestone.

**Comment by liyuqian** [comment]
@xster : is this still something that you'd like to pursue?

**Comment by pedromassangocode** [comment]
Definitely would be great to have any update on this.

**Comment by jonahwilliams** [comment]
This is no longer relevant as we're moving away from scene caching as a performance technique.
