### ISSUE TITLE
Expose scene caching to the framework

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17270]
Create a new ContainerLayer type or an argument to a SceneBuilder.build() or SceneBuilder.pushScene() that allows the framework to explicitly raster cache the subtree right away so subsequent redraws of the scene are optimized.

**Comment by liyuqian** [comment]
We probably won't create a new layer for this as we'll have retained information for all current layers. Once we know that a layer is retained between frame to frame, we can cache the raster of its subtree to improve the performance. @chinmaygarde : please confirm if I understand correctly (BTW, are you actively working on that?)

**Comment by liyuqian** [comment]
This seems to be a duplicate of https://github.com/flutter/flutter/issues/32662. Closing this and preserve https://github.com/flutter/flutter/issues/32662 as there are more discussions and details there. Please feel free to reopen this issue if I'm mistaken.
