### ISSUE TITLE
TimePicker doesn't switch to minute after selecting hour like the Android native time picker does

### ISSUE THREAD

**Issue by BowenYin** [flutter/flutter#17276]
In the native Android time picker, it automatically switches to minute after you select an hour. In Flutter material, it seems you have to manually tap on the minute part of the time after choosing an hour in order to select a minute.
Just a minor suggestion—it should be an easy fix.

**Comment by tjunxiang92** [comment]
Here are the changes for the fix to switch over to the minute.
https://github.com/tjunxiang92/flutter/pull/1/files

**Comment by vitoscalleta** [comment]
Noob question. so where do i get the time_picker.dart with all the incorporated changes ?

**Comment by lucaslcode** [comment]
created a new pull request [here](https://github.com/flutter/flutter/pull/29876) since @tjunxiang92 hasn't responded for a while to his pull request and I'm waiting for this to land
