### ISSUE TITLE
VS Code tries to launch Flutter app on Dart VM

### ISSUE THREAD

**Issue by 2015-lizaiyang** [flutter/flutter#17286]
**Environment is a MAC OSX, completely is according to the website operation.**
<img width="1415" alt="qq20180504-225625 2x" src="https://user-images.githubusercontent.com/21666293/39634841-68249510-4fee-11e8-9fe5-cdb446a87365.png">

**Comment by zoechi** [comment]
Seems you try to run Flutter code with the Dart SDK.
You need to configure your IDE to use the Flutter SDK.
There is a Flutter plugin for VSCode, IntelliJ, and Android Studio.

**Comment by DanTup** [comment]
This looks like a Dart Code bug to me. Dart Code should detect that this is a Flutter script based on the pubspec referencing Flutter.

Can you send me a copy of your pubspec.yaml and a screenshot like the one above with the full status bar visible?

**Comment by DanTup** [comment]
@2015-lizaiyang If you're able to provide the above info, please open a new issue in the [Dart Code repo](https://github.com/Dart-Code/Dart-Code) for me to investigate.
