### ISSUE TITLE
initialValue of TextFormField is not set if it is fetched async

### ISSUE THREAD

**Issue by benjaminhorner** [flutter/flutter#17282]
## Steps to Reproduce
1. Create a `TextFormField` with `initialValue` = `_var`
2. In the `initState()` of the `StatefulWidget` it is in set the `_var` async and call `setState()`
3. The `TextFormField` is not filled with the `_var`

**Note**: it works fine with when the `_var` is set sync instead of async.

## Workaround for now
Use a `TextEditingController()` and set it's `text` attribute in the async callback rather than setting the `initialValue` attached to a key in the state.

**Comment by HansMuller** [comment]
TextFormField's initial value is only used to [initialize its TextController](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_form_field.dart#L135) and then only if an explicit TextController wasn't provided. This initialization can't be deferred with async.

The approach you've listed as a workaround is the correct way to initialize a TextFormField with an async value.

**Comment by zoechi** [comment]
I assume this is solved?

**Comment by jackyq2015** [comment]
@benjaminhorner can you please paste the code for "workaround"? Come across the same issue.

**Comment by benjaminhorner** [comment]
@jackyq2015 I am assuming some knowledge of `Rx` here as that is what I use for apps.

My Widget has a factory in which I initialize a `final _textEditingController = TextEditingController()`;

Then I add a listener to my `_textEditingController` in the `initState()` method (don't forget to remove it in the overridden `dispose() `method) which calls on `_textEditingControllerListener()`: `_textEditingController.addListener(_textEditingControllerListener);`

```
void _textEditingControllerListener() {
    this.appUser.username = _textEditingController.text;
}
```

Finally my TextFormField is like so:
```
TextFormField(
  controller: _textEditingController,
  autocorrect: false,
  decoration: InputDecoration(
    labelText: AppLocalizations.of(context).textFieldHint,
    labelStyle: Font.textFieldLabelStyle(),
  )
),
```

Of course you could use anything else `async` and set the `_textEditingController.text` from the callback.

**Comment by iamchathu** [comment]
What about if you any many fields? Then you have to set controllers for ever field ?

**Comment by snarcraft** [comment]
> What about if you any many fields? Then you have to set controllers for ever field ?

@iamchathu Unfortunately, Yeah!

A workaround would be to set a Key with the same value as the initialValue 

`TextFormField(
      key: Key(value),
      initialValue: value,
      ....
)`
