### ISSUE TITLE
Deleted android/gradle/wrapper/gradle-wrapper.jar is not restored

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#17280]
Flutter tooling creates (as copies from `bin/cache/artifacts/gradle_wrapper/`)
```
android/gradlew
android/gradlew.bat
android/gradle/wrapper/gradle-wrapper.jar
```
if these files do not exist in a project. However, deleting only the jar file does not result in recreation of that file. Instead `flutter run` fails with
```
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...                                          |
Oops; flutter has exited unexpectedly: "Exit code 1 from: /Users/mravn/apps/tst02/example/android/gradlew -v:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain".
...
```
To work around this, one would have to delete also the `gradlew` script file.

**Comment by mravn-google** [comment]
FYI @sigurdm

**Comment by zhangjianli** [comment]
Just ran into this issue today. Deleting `gradlew` works for me though.

**Comment by dsp1589** [comment]
@zhangjianli did you delete another file too?


I am facing the same issue now. Here is the log. Any help much appreciated. it was just fine today morning.

cat /Users/dhanasekarapandiansrinivasan/Development/MyFlutterApp:Mobile/MyFlutterApp/Mobile/flutter_03.log;
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

command

flutter run -t lib/home/main.dart -d Android SDK built for x86

exception

ProcessException: ProcessException: Process "/Users/dhanasekarapandiansrinivasan/Development/MyFlutterApp:Mobile/MyFlutterApp/Mobile/android/gradlew" exited abnormally:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Command: /Users/dhanasekarapandiansrinivasan/Development/MyFlutterApp:Mobile/MyFlutterApp/Mobile/android/gradlew -v

#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:185:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:166:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:95:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:111:11)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:51:10)
#42     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#43     main (file:///Users/dhanasekarapandiansrinivasan/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter doctor

[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 1.0.0 at /Users/dhanasekarapandiansrinivasan/Development/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/dhanasekarapandiansrinivasan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (3 available)
    • SM G960U                  • 4545525a44553398          • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554             • android-x86   • Android 9 (API 28) (emulator)
    • Dsp                       • 00008020-001A596A363A002E • ios           • iOS 12.1.1

• No issues found!

**Comment by jonahwilliams** [comment]
This is now fixed:

```
jonahwilliams-macbookpro2:hello_world jonahwilliams$ rm android/gradle/wrapper/gradle-wrapper.jar 
jonahwilliams-macbookpro2:hello_world jonahwilliams$ 
jonahwilliams-macbookpro2:hello_world jonahwilliams$ flutter build apk

You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       4.0s
✓ Built build/app/outputs/apk/release/app-release.apk (13.2MB).
jonahwilliams-macbookpro2:hello_world jonahwilliams$ 
jonahwilliams-macbookpro2:hello_world jonahwilliams$ ls android/gradle/wrapper/gradle-wrapper.
gradle-wrapper.jar         gradle-wrapper.properties  
jonahwilliams-macbookpro2:hello_world jonahwilliams$ ls android/gradle/wrapper/gradle-wrapper.

```
