### ISSUE TITLE
Add a Code of Conduct to Github

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#17288]
Noticed there is this feature: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/
Would be cool if the Flutter org and its various repos had a Code of Conduct :) Maybe grab the bottom of this: https://flutter.io/design-principles/

**Comment by zoechi** [comment]
Looks like we have that now https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md
