### ISSUE TITLE
flutter behind proxy

### ISSUE THREAD

**Issue by fpitpit** [flutter/flutter#17285]
Impossible to update flutter when it is behind a proxy
error 407

Where to set the http_proxy with flutter ?

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/24021315/network-connection-proxies-in-dart-editor might help

**Comment by danieldaeschle** [comment]
I get that:

```Updating flutter tool...
Got TLS error trying to find package mockito at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...```

Env vars for proxy are set.

**Comment by zoechi** [comment]
@danieldaeschle 
Are you using self-signed certificates?
See also #15014

@fpitpit did the link help? Is this still an issue?

**Comment by danieldaeschle** [comment]
Yes, self signed Certificates from my company to the proxy server. I can't test it at the moment.

**Comment by zoechi** [comment]
About self-signed certificates. This might apply here too https://github.com/dart-lang/pub/issues/1882#issuecomment-415588527

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/16875#issuecomment-384758566
