### ISSUE TITLE
AnimatedList Sample screenshot should be animated

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#17294]
I was staring at the screenshot on https://flutter.io/catalog/samples/animated-list/ for minutes waiting for it to move and show me the awesome animation of animated lists. Turns out, the screenshot is static 😞. It should really by an animation to show of what an *Animated*List looks like. 😀 

/cc @mit-mit @gspencergoog

**Comment by Sfshaza** [comment]
@HansMuller

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1859](https://github.com/flutter/website/issues/1859) via [**ZenHub**](https://www.zenhub.com/)
