### ISSUE TITLE
Flutter looking for host_debug_sim when using --local-engine=ios_debug_sim

### ISSUE THREAD

**Issue by fuzzybinary** [flutter/flutter#17305]
I'm working on an engine patch for iOS and I'm looking at how it performs in an optimized build, but the flutter executable is looking in the wrong place when for the host tools when the local-engine is set to ios_debug_sim.

Error message:
> Launching lib/main.dart on iPhone X in debug mode...
> Unable to find Dart binary at /Users/jeffward/Projects/engine/src/out/host_debug_sim/dart-sdk/bin/dart
> Error launching application on iPhone X.

I think the issue is that this line:
https://github.com/flutter/flutter/blob/43c74341b2f434af696c7c860ce0409ae00dd3cc/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L376

Should read:
`final String hostBasename = 'host_' + basename.replaceFirst('_sim', '').substring(basename.indexOf('_') + 1);`

**Comment by cbracken** [comment]
Thanks for spotting this.

`host_debug_sim` is a valid engine target, but it's identical to `host_debug`, so it doesn't make a ton of sense for us to require developers to build it. 

I'll land a fix. In the meantime, a quick and dirty hack to work around this is to symlink `host_debug_sim` to `host_debug` in your out dir.

**Comment by fuzzybinary** [comment]
Does host_debug work for simulator builds? I was specifically testing whether a patch would work in the simulator.

**Comment by cbracken** [comment]
Yep, it’ll work fine.

**Comment by fuzzybinary** [comment]
cool, Closing
