### ISSUE TITLE
DatePicker with boundaries (last and first date) failed I when scroll to dates out of range

### ISSUE THREAD

**Issue by marica27** [flutter/flutter#17309]
DatePicker failed on assertion when I choose past year and selected day-month is before firstDate

I have a DatePicker with first and last dates. Lets say from 6-09-2016 to 15-01-2019. Today is 4th May 2018.  I choose year 2016. DatePicker changes only year in selected date. So it wants to show 4-05-2016. But it's out of range. It failed on assertions.

`Another exception was thrown: 'package:flutter/src/material/date_picker.dart': Failed assertion: line 504 pos 15: 'selectedDate.isAfter(firstDate) || selectedDate.isAtSameMomentAs(firstDate)': is not true.
`

It can be fixed as to choose first possible date:
in _YearPickerState build()
`onTap: () {
            DateTime dateTimeYearChanged = new DateTime(year, widget.selectedDate.month, widget.selectedDate.day);
            if (dateTimeYearChanged.isBefore(widget.firstDate)) {
              dateTimeYearChanged = widget.firstDate;
            }
            widget.onChanged(dateTimeYearChanged);
          }`

Also, if I choose 2019 year, DatePicker scrolls from month May to month January.  So user doesn't see selected date. But he can press OK and selected date is 4-05-2019, which is out of range. So this is a bug

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by marica27** [comment]
`flutter doctor -v`
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.12.6 16G29, locale en-NL)
    • Flutter version 0.3.1 at /Users/marica/Development/flutter
    • Framework revision 12bbaba9ae (2 weeks ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/marica/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • SM G930F • 98862743595a513755 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by HansMuller** [comment]
cc @yjbanov

**Comment by VyMajoris** [comment]
Also having the same issue.

**Comment by alexZaicev** [comment]
Does anyone experience the same issue? Because, when I change the year, with preset min and max date the confirmed date is messed up with unmatched month and days.
