### ISSUE TITLE
Animation vignette opens to wrong size on Pixel 2 

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#17306]
Looks like this after tapping "Decoration":

![screenshot_20180504-112838](https://user-images.githubusercontent.com/551196/39649116-7eff20a2-4f99-11e8-9b58-7cf84bdb7d45.png)

cc @HansMuller

**Comment by zoechi** [comment]
I tried to reproduce with flutter_gallery > Studies > Animation which looks quite like the screenshot above on my Pixel 2 but can't reproduce. Not sure this is representative but I don't know where exactly above screenshot comes from

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
[✓] Connected device (1 available)
    • Pixel XL                  • HT69V0203649  • android-arm64 • Android 9 (API 28)
```
![screenshot_flutter_6007](https://user-images.githubusercontent.com/405837/51484376-af517b80-1d9b-11e9-8a5e-827e2c62db3c.png)

**Comment by Hixie** [comment]
This is specific to the old gallery, so closing. We're not going to fix bugs in the old gallery itself now that it's just a benchmarking target.
