### ISSUE TITLE
Fatal build errors due to compilation errors are really ugly

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#17307]
Current output:

```
Launching lib/main.dart on Pixel 2 XL in debug mode...
Initializing gradle...
compiler message: file:///Users/ianh/dev/flutter/packages/flutter/lib/src/painting/debug.dart:26:17: Error: Method not found: 'FlutterError'.
compiler message:       throw new FlutterError(reason);
compiler message:                 ^^^^^^^^^^^^
Compiler failed on /Users/ianh/dev/flutter/examples/flutter_gallery/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/ianh/dev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 435

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command '/Users/ianh/dev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Gradle build failed: 1
```

The ideal output would be more like:

```
Launching lib/main.dart on Pixel 2 XL in debug mode...

/Users/ianh/dev/flutter/packages/flutter/lib/src/painting/debug.dart:26:17: Method not found: 'FlutterError'.
Compilation failed.
```

...or:

```
Launching lib/main.dart on Pixel 2 XL in debug mode...

../../packages/flutter/lib/src/painting/debug.dart:26:17: Method not found: 'FlutterError'.
Compilation failed.
```

...or maybe, if we really want to show the code inline:

![screen shot 2018-05-04 at 12 47 53 pm](https://user-images.githubusercontent.com/551196/39649099-6bc5a83a-4f99-11e8-8c90-3b8f6825b4d5.png)

...where "FlutterError" is highlighted with ANSI colours.

**Comment by Hixie** [comment]
cc @aam is this on your radar?

**Comment by aam** [comment]
Not on immediate list of things to do, but yes that was the feedback I remember from our 'what to do with errors' discussion.

**Comment by Hixie** [comment]
Moving out of bucket5 since there is no committed assignee; please don't hesitate to move these to a specific milestone if there is someone who is committed to working on it by that milestone.

**Comment by gspencergoog** [comment]
Do you mean that you just want the `compiler message:` part of the output to be prettier, or do you also want to suppress all of the other extraneous `gradle` output?

**Comment by Hixie** [comment]
Both.

**Comment by gspencergoog** [comment]
Looking at the Gradle docs, it's not possible to change the output mode of it to some structured form like JSON or XML, but there is an IDE interface called GradleConnector that would allow us to start gradle builds and listen to the build events as structured events.  It seems like overkill for this use case, but we could write a Java wrapper that starts gradle builds and outputs structured output from the build in any form we'd like.

For now, I'm not going to parse the compiler output messages: they can be far longer than a couple of lines, and the format is not very predictable.
