### ISSUE TITLE
Flutter doctor is not working for Windows machine

### ISSUE THREAD

**Issue by charmy4896** [flutter/flutter#17321]
```C:\WINDOWS\system32> flutter doctor -v
[√] Flutter (Channel master, v0.3.7-pre.9, on Microsoft Windows [Version 10.0.16299.371], locale en-IN)
   • Flutter version 0.3.7-pre.9 at C:\Users\charmy\Desktop\fuzzycloud\flutter
   • Framework revision b2b4665926 (5 hours ago), 2018-05-04 18:17:35 -0700
   • Engine revision e976be13c5
   • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b[!] Android toolchain - develop for Android devices
   • Android SDK at C:\Android\android-sdk
   • Android NDK location not configured (optional; useful for native profiling support)
   • ANDROID_HOME = C:\Android\android-sdk
   X Android SDK is missing command line tools; download from https://goo.gl/XxQghQ
   • Try re-installing or updating your Android SDK,
     visit https://flutter.io/setup/#android-setup for detailed instructions.[√] Android Studio (version 3.1)
   • Android Studio at C:\Program Files\Android\Android Studio
   • Flutter plugin version 24.0.1
   • Dart plugin version 173.4700
   • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)[√] VS Code, 64-bit edition (version 1.22.2)
   • VS Code at C:\Program Files\Microsoft VS Code
   • Dart Code extension version 2.12.1[!] Connected devices
   ! No devices available```

**Comment by charmy4896** [comment]
It happens when Android has two folders with same name. Try to remove the useless folder and then run flutter doctor again. And also change the path variables.

**Comment by eseidelGoogle** [comment]
Thanks for the report.  Sounds like you worked past the issue, but there is still changes we should make to `flutter doctor`.

Can you help me understand what you meant by when Android has two folders with the same name`?

**Comment by HamzaTanveer78** [comment]
after the upgrade, the flutter from git bash cmd "flutter doctor" is not working in both windows cmd and git cmd

**Comment by zoechi** [comment]
Perhaps it's #19359

**Comment by zoechi** [comment]
@charmy4896 aAre you still seeing this?

Perhaps it's from `android/local.properties` check `flutter config`

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by SamukaDEV** [comment]
![image](https://user-images.githubusercontent.com/13206430/51292550-4b713080-19f2-11e9-93e4-a2ab78f187c6.png)

in my cmd, this is the error, and i dont know if are my System, or is some config wrong! 
some help please?

**Comment by kangwang1988** [comment]
@SamukaDEV 

![image](https://user-images.githubusercontent.com/817851/51294526-548feb00-1a4e-11e9-9b97-8904b3b41c49.png)

This might be the source.
Try call the `full-path-to-adb/adb.exe devices -l` from the cmd prompt and check if it works well.
Besides, when there is something wrong, add the verbose flag. e.g., call `flutter doctor -v`.

**Comment by zoechi** [comment]
@SamukaDEV probably #19359

**Comment by SamukaDEV** [comment]
Thanks, solved for me!
