### ISSUE TITLE
Use the FirebaseAnimatedList with the Cloud firestore query stream

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#17332]
I'd like to suggest also using the FirebaseAnimatedList with the cloud firestore stream. 

It would be nice to share the UI components across both realtime database and cloud firestore. 

Then again, it might be better to make new ui widgets for the firestore plugin.

**Comment by gildaswise** [comment]
Tried to solve this in a [pull request](https://github.com/flutter/plugins/pull/757), but for now, please use the pub [package](https://pub.dartlang.org/packages/firestore_ui)!

**Comment by kroikie** [comment]
@branflake2267

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/836. Any further collaboration will be done there.
