### ISSUE TITLE
A question about the future: Would Flutter support using C/C++ on Fuschia if you want something high performance?

### ISSUE THREAD

**Issue by fadi-botros** [flutter/flutter#17336]
On Android and iOS, tasks that needs high performance, couldn't be done on Java (a VM language, so slow and memory constrained), nor Objective-C (a very dynamic language, that, though compiled, approaches the scripting languages in terms of slowness), so they could be implemented in C/C++, then make Java/Objective-C functions that call your code.

In Fuschia, Flutter is extremely constrained language, you even don't have real multithreading (multithreading for some old developers = shared data, which is seen as bad practice by Dart, and so it is completely banned), also in Dart I think there is no way to handle memory. So, if something is a bottleneck (according to either time or memory), what will be the solution? Will Flutter permit using C/C++ in Fuschia? Or will it be backed by a real compiled language (for example, Rust), so that you can fallback to it if you want?

I know that a lot of things could be done using messages, and asyncs, if you want to share a big amount of data, you can divide it into small parts, and put them on a stream and use async to "emulate" threading. But this may be a bottleneck if done wrong.  Also there are some things that are better done in C/C++, like big calculations for example. I think in games, Fuschia will use a framework rather than Flutter, which is not my problem, my problem is, what if a developer needs to break Flutter's constraints???

**Comment by fadi-botros** [comment]
So, it is for JavaScript compatibility, which is a good thing, since Dart is a cross-platform language.
But, what about Flutter on Fuschia??? On Fuschia, no Java, no Objective-C, so how could one raise the performance of his application? or if one thinks threaded with shared data (bad practice I know some will say this, but I think if well unit tested it is not bad), how could one like this develop on Fuschia ? I think Flutter is the only permitted way to do UI apps on Fuschia.

**Comment by zoechi** [comment]
I guess this is why #7053 got so many upvotes.
The issue is still open. Currently getting Flutter V1.0 and Dart V2.0 released just has higher priority.

**Comment by zoechi** [comment]
See also the latest comment

> In fuchsia this is done with FIDL and it has bindings to c, rust and golang.

**Comment by zoechi** [comment]
I guess this can be closed?

**Comment by PM44** [comment]
i want to enable mobile data through app in flutter can you please help
