### ISSUE TITLE
SimpleDialog not showing after call showDialog

### ISSUE THREAD

**Issue by hanzhida** [flutter/flutter#17337]
If I call displayDialog, the Dialog cannot show, but the screen is dimmed, like the dialog size is zero....

from the console, I see the following message:

> I/flutter (25138): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#7094d relayoutBoundary=up2 NEEDS-PAINT
**I/flutter (25138): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.**
I/flutter (25138): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#7094d relayoutBoundary=up2

The code is like below:

```dart
class LabelListDialogView extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new _LabelListDialogState();
  }
  static Future displayDialog(BuildContext context) async{
    await showDialog(context: context, builder: (BuildContext context) {
      return new SimpleDialog(title: new Text('Select the label'),
        children: <Widget>[new LabelListDialogView()],);
    });
  }
}
class _LabelListDialogState extends State<StatefulWidget> {
  Map<String, bool> mCheckedState = {
  };
  @override
  Widget build(BuildContext context) {
    return new FutureBuilder(builder: (BuildContext context, AsyncSnapshot<List<MemLabel>> snapshot){
      return new ListView(padding: new EdgeInsets.symmetric(vertical: 8.0),
        children: _generateListViewItem(snapshot.data),);
    },
    future: new MemDataManager().getAllMemLabels(),);
  }
  List<Widget> _generateListViewItem(List<MemLabel> labelList){
    List<Widget> list = <Widget>[];
    list.add(_generateListViewAddLabel());
    if(labelList != null) {
      list.addAll(labelList.map((label){
        return _generateListViewLabel(label);
      }).toList());
    }
    return list;
  }
  Widget _generateListViewAddLabel(){
    return new ListTile(leading: new Icon(Icons.add),
      title: new Text('Add new label'),
      onTap: (){
        // TODO
      },);
  }
  Widget _generateListViewLabel(MemLabel label){
    return new CheckboxListTile(value: mCheckedState.containsKey(label.uuid) ? mCheckedState[label.uuid] : false, onChanged: (bool value){
      setState(() {
        mCheckedState[label.uuid] = value;
      });
    },title: new Text(label.name),
    );
  }
}
```
Why the dialog does not show?

**Comment by burhanrashid52** [comment]
I am also having have the sample problem. For me its happing in high-resolution devices for other devices it's working for me. I tried various hit and trail and came to the conclusion that there is some issue in rendering ListView in SimpleDialog.

If you set up children like this it will work
```
new SimpleDialog(
            title: const Text('Select Priority'),
            children: <Widget>[
              buildContainer(Status.PRIORITY_1),
              buildContainer(Status.PRIORITY_2),
              buildContainer(Status.PRIORITY_3),
              buildContainer(Status.PRIORITY_4),
            ],
          );
        }
```
But it wont work when you put ListView in its childrens.This goes same with AlertDialog and SimpleDialog

**Comment by silentsudo** [comment]
Can you try this https://stackoverflow.com/questions/50095763/flutter-listview-in-a-simpledialog/50099921

**Comment by burhanrashid52** [comment]
I have Tried this solution. It works fine for the static list but I have a dynamic list. For a dynamic list, it needs ListView.Builder which is not working @silentsudo

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by danielilie** [comment]
Same problem here with Note8. ListView.builder is not working in AlertDialog.

**Comment by zoechi** [comment]
@danielilie 

> ListView.builder is not working in AlertDialog.

What does this mean exactly?
Please add the output of `flutter doctor -v`
and the code that allows to reproduce.
