### ISSUE TITLE
Firebase Authentication : Unlink user account

### ISSUE THREAD

**Issue by aqwert** [flutter/flutter#17344]
After lookng at all the current open issues and since this is not implemented I am raising this issue for the firebase_auth plugin: https://github.com/flutter/plugins/tree/master/packages/firebase_auth

The functionality exists as part of firebase:
https://firebase.google.com/docs/auth/android/account-linking#unlink-an-auth-provider-from-a-user-account

Raised against the plugin: firebase_auth up to 0.5.8

**Comment by kroikie** [comment]
@aqwert

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/834. Any further collaboration will be done there.
