### ISSUE TITLE
Would like instructions on how to attach to a FlutterView launched from XCode/Android Studio

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#17341]
@kangwang1988 asked:

"As we're based on a large codebase, i.e., the already existed ios/android code accounts for the majority. So we would rather to develop the project in ios/android mode. When I opened a debuggable ios application, I can attach it using lldb. I can do the same thing in android too. How about flutter? If a opened a android app with flutter in debug mode, how can i attach it?
Should I specify a observatory port when running a snapshot_blob.bin and then use the "Dart Remote Debug" to connect it?As far as i know, dart supports the remote debug, so I think flutter can do it too.
If possible, how? As to our development environment, it would save a lot of efforts for us if we can attach to the dart vm service in debug mode."

This is a pretty common user journey for folks using Flutter in an Add2App capacity.  @mravn-google any thoughts?

**Comment by mravn-google** [comment]
cc @floitschG

**Comment by eseidelGoogle** [comment]
iirc @jason-simmons added a command to do this at one point.  I don't see it now listed in `flutter -v` so maybe it was removed?

**Comment by kangwang1988** [comment]
@floitschG Once I used the command "flutter run --use-application-binary" and the  Flutter will automatically connect to the VM, can I still use Intellij(with Flutter plugin) to set breakpoint and debug it?

Is it possible for us to launch a app from Xcode/Android studio, then I use Intellij to connect to specific observatory port?

**Comment by floitschG** [comment]
I haven't tried yet. If not, we would probably need to adjust the plugins for IntelliJ.

**Comment by kangwang1988** [comment]
@floitschG  
Thanks. In our case, we want to launch a App from Android Studio/Xcode, then we want to attach to the dart observatory to debug with Intellij plugins.

**Comment by eseidelGoogle** [comment]
Per discussion with @kangwang1988: "We wanna to do more in flutter, henceforth, this "attach to a flutter engine" issue launched from xcode or android studio is much urgent. @eseidelGoogle This development efficiency issue is a blocker now."  Hence marking as a customer: blocker.  Although @Hixie customer: critical may be more appropriate parlance?

@mehmetf also needs this for a Google customer soon too, and @mravn-google will likely run into this need in his add2app work, so either way we're likely to do things in this space very soon.  @Hixie feel empowered to adjust tagging as needed.

**Comment by kangwang1988** [comment]
@mehmetf 
We've also know how to debug flutter and native already.
Just launch the flutter app and attach to it using android or lldb. We can implement debug flutter and android/ios in the same time. Though it may be slow, it works.

However, for our case in ios, we have over thousands of ios source files, dozens of dart. As we are applying flutter in a gradual way, most of the guys and work are still using ios. We don't want to break their original workflow. Of course, for guys who are mainly focusing on flutter, we use the standard flutter way. So it's strongly recommended to allow the developers to debug in both way.

This principle also applies for the android developers.
Currently, I think even flutter can not support it in its toolchain, a how-to-debug-a-launched-app-from-androidstudio/xcode wiki will help us a lot. Just like the armv7 in iOS issue.

**Comment by Hixie** [comment]
Is this about connecting to a FlutterView's debugger, or connecting the 'flutter run' tooling to a running FlutterView to be able to do hot reloads and such? Or connecting an IDE?

**Comment by Hixie** [comment]
If the desire here is just to connect the Observatory (to do debugging), then to do it should be straight-forward: look for the observatory port in the device logs, tell `adb` to forward that port locally, then connect to the forwarded port.

**Comment by kangwang1988** [comment]
@Hixie 
Yeah, just connect to the observatory to enable debugging.
The adb approach might work for android.
How about ios?

**Comment by Hixie** [comment]
I think we use `ideviceproxy` on iOS for the same problem. @cbracken might know more.

**Comment by cbracken** [comment]
Yep `iproxy` is part of the `libimobiledevice` suite installed via homebrew. The usage is:
```shell
iproxy HOST_PORT DEVICE_PORT DEVICE_UDID
```

**Comment by kangwang1988** [comment]
@cbracken 
Let me have a try.

**Comment by kangwang1988** [comment]
I've figure it out and make it work for the flutter Intellij plugin too.
As long as i have the observatory port, i can forward it to local one. Then I the web-socket based observatory approach. Besides, I  can also use the dart remote debug app to connect to it. It works.
Thank you guys.

**Comment by eseidelGoogle** [comment]
Looks like customer:gold found a workaround, but @mravn-google we will still have work here to automate this for others, no?

**Comment by Hixie** [comment]
I'm going to close this issue since it was a specific request from a specific customer, and that is now resolved. If there is more long term work to do, please feel free to file a specific bug on that work.

**Comment by mravn-google** [comment]
@eseidelGoogle Yes, but this sounds like IDE plugin work rather than Flutter tooling work?

**Comment by kangwang1988** [comment]
@mravn-google 
Yes, the observatory and ide plugin works fine.
I don't know how to do it with flutter.Besides, the hotreload is inavailable in this case.
