### ISSUE TITLE
Firebase Authentication - UpdateEmail

### ISSUE THREAD

**Issue by aqwert** [flutter/flutter#17343]
After lookng at all the current open issues and since this is not implemented I am raising this issue for the firebase_auth plugin: https://github.com/flutter/plugins/tree/master/packages/firebase_auth

The functionality exists as part of firebase:
https://firebase.google.com/docs/auth/web/manage-users#set_a_users_email_address

Much like changing the users password (https://github.com/flutter/flutter/issues/16775) this should also be possible.

Raised against the plugin: firebase_auth up to 0.5.8

**Comment by ffeu** [comment]
@zoechi I think this one can be closed, isn't it?

[FIrebaseUser.updateEmail()](https://github.com/flutter/plugins/blob/master/packages/firebase_auth/lib/src/firebase_user.dart#L79)

**Comment by zoechi** [comment]
@ffeu Yes. Looks good. Thanks for tracking it down!

**Comment by kroikie** [comment]
@aqwert

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/835. Any further collaboration will be done there.
