### ISSUE TITLE
Investigate using image decoding/encoding codecs available on the platform.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#17356]
Currently, the Flutter engine enables the JPEG, WEBP, GIF, ICO, BMP and WBMP codecs on all supported platforms. This allows us to guarantee being able to decode/encode (not all encoders are available to the framework) these formats. We need to ship libraries for these formats in the engine. This has worked out well so far for the following reasons:

* Easy to guarantee whether a given format can be decoded by the engine.
* Easy to build and package the libraries in the engine.
* The Skia team monitors contributions to these projects and ensures that performance enhancing patches are immediately applied.

The downsides to this approach are:

*  Adds to the overall size of the engine (about [7% of the size of the engine](https://github.com/flutter/flutter/files/1981330/flutter_engine.svg.zip) is codecs).
* The Flutter team needs to update dependencies regularly.
* The latest codecs available on the platform (for example HEIF) either need to be shipped in the engine and these dependencies need to be kept up to date by the Flutter team.

The Flutter team has investigated using platform codecs in the past. But, writing platform bindings was seen to be a significant enough undertaking to put this task lower in the list of priorities (not to mention losing some of the advantages mentioned above). The team was also not sure if these bindings should exist in the Flutter engine or Skia.

It is possible that a hybrid approach can be taken as well.

**Comment by bdero** [comment]
I think this one's good to close now that:
* We have our own image decoder facade and registered decoders cascade
* New decoders can be easily installed from embedders
* Native image decoders are installed for Android P+/iOS/MacOS/Windows
