### ISSUE TITLE
Text glitches on iPhone 5

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#17364]
When running the Gallery's animation demo on an iPhone 5, there's a fairly reproducible text glitchiness issue with similar symptoms to previous iOS text rendering issues. Verified this repros under both iOS 8 and iOS 9.

Similar previous issues for ref: #13817 #13087 #12934
Relevant Skia patches: https://skia-review.googlesource.com/c/skia/+/71780

Potentially relevant: this is combined with unusually poor performance, but only on the transition to and from the leftmost tab of the animation demo (Eyeglasses) to the second-from-leftmost tab (Seating).

![image-1](https://user-images.githubusercontent.com/351029/39730112-86115f5e-5214-11e8-9b9f-a412119033cd.jpg)

/cc @brianosman @chinmaygarde

**Comment by chinmaygarde** [comment]
@brianosman claims that the text bugs should be fixed on ToT. @cbracken: Can we verify and close this issue?

**Comment by cbracken** [comment]
Will check it out momentarily!

**Comment by cbracken** [comment]
@chinmaygarde @brianosman verified that this has not been fixed at head of flutter/flutter (Skia commit 1986036f69f81a52d390cc01899cd68d6b200e30).

**Comment by brianosman** [comment]
I know the bug says iPhone 5, but I previously saw this on an iPad. I haven't been able to reproduce it on that device in a long time. Do you know if this is device specific, now - or are there other specific steps to get it to reproduce?

**Comment by zoechi** [comment]
Does this still reproduce?

**Comment by sbauer1799** [comment]
Testing my apps on an iPhone 4S. Can easily reproduce that when playing with a SliverAppBar with FlexbileSpaceBar. After that, the font rendering is broken on different kind of pages.

**Comment by ovaldi** [comment]
+1

**Comment by kf6gpe** [comment]
Wondering if this is still an issue. Assigning `P4`.

**Comment by chinmaygarde** [comment]
Closing as stale. We haven't seen issues with multi-texturing in a while.
