### ISSUE TITLE
New users must install xcode to install ideviceinstaller to use flutter start

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1737]
Looks like new users must install Xcode related utilities to use Flutter. We should make it optional, if some developers only want to test on Android (or, don't want to install Xcode right away)

```
device_id not found. To work with iOS devices, please install ideviceinstaller. If you use homebrew, you can install it with "$ brew install ideviceinstaller". 
```

Not sure if the above is actually stopping the workflow, because we encounter another error right after this.

* Let's try to make Xcode and related tools (like ideviceinstaller) optional unless the developer explicitly opts into the iOS flow
* If that's not possible, we need to reorder the Getting Started guide.

**Comment by sethladd** [comment]
cc @mrasz

**Comment by lukechurch** [comment]
I've just run into this trying to take Flutter out for a spin. The repair instructions don't appear to work:

the first time I do a brew install ideviceinstaller I get a lot of errors during the installation. The second I get 

```
Lukes-MacBook-Pro-2:my_app lukechurch$ flutter start
idevice_id not found. To work with iOS devices, please install ideviceinstaller.
If you use homebrew, you can install it with "$ brew install ideviceinstaller".
Android SDK not found. The ANDROID_HOME variable must be set.
Failure building APK. Unable to find components.
Starting lib/main.dart on Nexus 6...
"build/app.apk" does not exist.

Lukes-MacBook-Pro-2:my_app lukechurch$ brew install ideviceinstaller
Warning: ideviceinstaller-1.1.0_1 already installed
```

**Comment by sethladd** [comment]
Thanks. The error message is also a bit confusing. I'm seeing two messages, one for iOS and one for Android.

**Comment by sethladd** [comment]
If this flow is required (install all xcode tools before you can even use Flutter), then we need to reorder the https://flutter.io/getting-started/ page, because it has the flow of:

* install flutter
* install enough android tools
* see flutter run on your android phone
* install xcode
* see flutter running in your ios simulator

**Comment by devoncarew** [comment]
Hmm, so to clarify this one, we should only warn about missing bits of the Android toolchain if they're trying to use android devices, and only warn about missing bits of the ios one if they're trying to use ios devices.

**Comment by abarth** [comment]
@devoncarew That sounds right to me.

**Comment by Hixie** [comment]
Ideally we'd just go and fetch the relevant parts (like we now fetch dart) so that the user wouldn't have to do anything. Obviously xcode is a bit of a wildcard there, being >4GB and having its own non-CLI install flow.

**Comment by devoncarew** [comment]
I think this is addressed. Closing now, and we can open more issues as we encounter them.
