### ISSUE TITLE
Would be nice to understand Flutter's total download size

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#17374]
We occasionally get complaints about all the things needed to install to get develop with Flutter:
https://twitter.com/sajadbeheshti/status/993531843818422274

Most of those installs are not under our control, but it would be nice if we had a way to measure the total sizes (at least occasionally if not automatically).

**Comment by eseidelGoogle** [comment]
We get quite a few complaints about this in the twitterverse.  I'm not really sure why.  I think maybe it's cocoapods + brew, etc?  https://twitter.com/clarklab/status/997974712562208769 is another.  @mit-mit

**Comment by mit-mit** [comment]
The main contributors here are not "ours", so not sure how to explain the size of a dependency we don't control.

I think the root fix here is to allow running initial Flutter apps without these dependencies installed in the first place.

**Comment by zoechi** [comment]
Is this superseded by #17374 ?

**Comment by kf6gpe** [comment]
@zoechi , you're referring to #21737, right?

**Comment by zoechi** [comment]
@kf6gpe yup. Thanks for pointing out!
