### ISSUE TITLE
Flutter installing freezes on "Updating Flutter tools.." with master branch cloned. 

### ISSUE THREAD

**Issue by karthibe45** [flutter/flutter#17384]
Followed the procedure from [Flutter](https://flutter.io/setup-windows/).

1. System Requirements:
OS: Windows 8.1
Powershell V5
Git installed
2.When i completed the SDK complete setup through "Flutter Doctor" command, setup freezes at this point without any error  or warning messages.

**Comment by notes-jj** [comment]
In my case it was the company's ntlm proxy. I have cntlm installed on the local machine and set via environment variables. For a unknown reason updates from `https://www.dartlang.org/` could not be downloaded. I fixed the problem by downloading by tethering via mobile phone.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
