### ISSUE TITLE
Apparently required to set ANDROID_HOME

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1738]
```
Error executing simctl: 117 Usage: simctl list [devices|devicetypes|runtimes] Android SDK not found. The ANDROID_HOME variable must be set. Failure building APK. Unable to find components. Starting lib/main.dart on Nexus 9... "build/app.apk" does not exist.
```

On master branch, we're seeing the above error. Didn't find instructions in our Getting Started that sets ANDROID_HOME.

Did we miss a step? (if so, we'll need to document it)
Did we hit a known bug?

**Comment by sethladd** [comment]
cc @mrasz

cc @devoncarew do you know why we're seeing the above?

**Comment by sethladd** [comment]
cc @qchong as this might require an update to "Getting Started" ?

**Comment by devoncarew** [comment]
We should first try and locate adb on the path, and then fall back to something like ANDROID_HOME. In the passed I've used the `which` package (https://pub.dartlang.org/packages/which).

**Comment by sethladd** [comment]
Are we responsible for saying "The ANDROID_HOME variable must be set." ?

If so, let's try: "Please visit https://flutter.io/getting-started/ for instructions on how to install the Android SDK." instead.

Talking about ANDROID_HOME here in this error message is confusing, since we've never asked the user to set that.

Thoughts?

**Comment by lukechurch** [comment]
@sethladd I've just run into this and found it confusing. I kinda expected to be able to follow just the getting started instructions from a vanilla mac and have Flutter running.

I don't mind installing the full Android SDK if I need to, or adding an extra variable after doing the adb install.

**Comment by sethladd** [comment]
>  I kinda expected to be able to follow just the getting started instructions from a vanilla mac and have Flutter running.

Agreed. Following the Getting Started guide should get you to a working "hello world"

**Comment by sethladd** [comment]
The "flutter doctor" command could help here. See https://github.com/flutter/flutter/issues/1466

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/issues/1692

**Comment by mrasz** [comment]
Is there a workaround while this check gets implemented?

**Comment by qchong** [comment]
Updated the Getting Started per Seth's comment. (pr: https://github.com/flutter/website/pull/160)

**Comment by eseidelGoogle** [comment]
I suspect this is a new requirement as part of the dynamic services work?  @mpcomplete?  Previously we would always use a prefab apk from the cloud for `flutter start`, but such an apk only works in the zero-optional-services case which is likely to decrease in frequency soon.

**Comment by mpcomplete** [comment]
I think this might be caused by my change to 'flutter start' to make it call 'flutter apk'. That should only happen if the app contains an apk/AndroidManifest.xml.

I think we should change the Getting Started guide. We're going to eventually require the android SDK in all cases.

**Comment by Hixie** [comment]
I really would rather we not require any environment variables be set to develop in flutter. Is there no way for us to autodetect the path in the common case? What do we need ANDROID_HOME for?

**Comment by Hixie** [comment]
To expand on why: Ideally, I'd like us to get to a state where you just download the Flutter SDK, and you're done. You can start coding right away. Everything just works. This won't be feasible if we require that you go and hack at your .bashprofile or AUTOEXEC.BAT or whatever.

**Comment by abarth** [comment]
We no longer need ANDROID_HOME.  We autodetect the Android SDK if its in the normal location.
