### ISSUE TITLE
Dismissable doesn't dismiss to the right edge

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#174]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Sep 25, 2015 at 20:08 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1349_

----

If you dismiss an item, it fades to 0 opacity by the time it goes about a third of the way across the screen. It should slide all the way across.

This is particularly obvious if you comment out the FadeTransition (or set its range to 1.0..0.5, to fix bug #824) and try to slide a card in card_collection.

**Comment by Hixie** [comment]
Looks like it's dismissing up to where the text label ends.

**Comment by Hixie** [comment]
Oh, nevermind, I see this is just hard-coded to 0.4.

**Comment by Hixie** [comment]
But we still need it to automatically dismiss if you drag it mostly off screen and then let go without flinging.

**Comment by Hixie** [comment]
Also, maybe the opacity part should be configurable... maybe a transition builder callback that you hand the child and the performance and it wraps the row in a fade transition or whatever. Or maybe it's a method you override in each widget library.
