### ISSUE TITLE
Be consistent about callback parameter names for tapping/pressing something

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#17407]
Some widgets use `onPressed` and others use `onTap`. I find two issues here:
- The name is inconsistent.
- The tense is inconsistent.

This makes it (very slightly) more difficult to use these widgets.

Is there a preferred naming convention for these callbacks?

**Comment by alanrussian** [comment]
In regards to tense, it looks like present tense is preferred by the style guide: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#naming-rules-for-typedefs-and-function-variables

**Comment by goderbauer** [comment]
I added this to the list in https://github.com/flutter/flutter/issues/24722.
