### ISSUE TITLE
Typo on BottomAppBar class documentation (appears "ised" instead of used)

### ISSUE THREAD

**Issue by Josemboa** [flutter/flutter#17406]
BottomAppBar class

A container that s typically _**ised**_ with Scaffold.bottomNavigationBar, and can have a notch along the top that makes room for an overlapping FloatingActionButton.

**Should be:** A container that's typically used with Scaffold.bottom Navigation Bar, and can have a notch along the top that makes room for an overlapping FloatingActionButton.

Link: [https://docs.flutter.io/flutter/material/BottomAppBar-class.html](https://docs.flutter.io/flutter/material/BottomAppBar-class.html)

**Comment by HansMuller** [comment]
Thanks for the report; will fix!

**Comment by HansMuller** [comment]
Actually it was already fixed, although the docs haven't been updated yet: https://github.com/flutter/flutter/pull/17381
