### ISSUE TITLE
Add/Clarify DropdownButton docs on how to differentiate between button and menu item text styles

### ISSUE THREAD

**Issue by sargntpi** [flutter/flutter#17414]
In short, I'm placing a drop down button in the bottom of my app bar. I'm allowing the users to select the theme of the application, including customizing the app bar color and dialog color. The issue I'm having is that the drop down button's style property seems to relate to both the buttons text, and the text that is shown in the list when tapped. 

As an extreme example, if my App Bar background is black with white text, and my dialog background is white, there is no way to specify black text for the list items. White text is shown over the white background. If I then change the style property to be black in color, I can no longer see the text when the button is minimized.

I'd like to be able to either a) specify two different text styles for the dropdown button, such as buttonTextStyle and listTextStyle (default to style if neither specified or something along those lines), or b) pass a function to run when the list is shown/hidden so I can manually specify the style based on this.

**Comment by modulovalue** [comment]
I'm also struggling with this. 

![bildschirmfoto 2018-07-13 um 16 02 00](https://user-images.githubusercontent.com/24444584/42695583-23e835ec-86b6-11e8-9b45-44464ba641fc.jpg)

As you can see, changing the style property of the DropdownButton also changes the style property of the items.

**Comment by modulovalue** [comment]
Here's a workaround for this problem:
set the "value" attribute of your DropdownButton to null and put the widget that you want to display when the DropdownButton is not *open* into the "hint" attribute.
This way you can provide styles for each state independently.

**Comment by jacksontempra** [comment]
@modulovalue thanks for your workaround! Will definitely be using that :)

**Comment by jacksun0124** [comment]
Hi guys, Is there a way to change dropdown icon color? I mean the arrow icon color.

**Comment by rgbinnovation** [comment]
Any update on this feature?

**Comment by troyzhao** [comment]
I am caring about this issue too.

**Comment by furkanvatandas** [comment]
Any update?

**Comment by mkiisoft** [comment]
This should be a super must! I had to change the color of the background and doesn't look great.

**Comment by divyanshub024** [comment]
Is there any update on this. Looks like many people having a problem with it.

**Comment by CountPablo** [comment]
> Hi guys, Is there a way to change dropdown icon color? I mean the arrow icon color.

use the 'iconEnabledColor' parameter

**Comment by cahyowhy** [comment]
upp

**Comment by shabab477** [comment]
Someone should really add this feature.

**Comment by Albertyson** [comment]
> Hi guys, Is there a way to change dropdown icon color? I mean the arrow icon color.

`iconEnabledColor`

**Comment by malikdoksoz** [comment]
user in themedata canvascolor

**Comment by shabab477** [comment]
I added a PR for this feature. Can anyone look into it? Not sure whether I should write a test for it though, unsure of the attribute name also. :crying_cat_face:

**Comment by shihaohong** [comment]
With the introduction of DropdownButton.selectedItemBuilder, similar problems to this issue could be resolved as [seenn in this gist](https://gist.github.com/shihaohong/72cb30560017ad50072ed7c37513c438). We could clarify how to combine using DropdownButton.selectedItemBuilder with the DropdownButton.style property to achieve the correct effects.
