### ISSUE TITLE
Image.file(file) is not updated on build()

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#17419]
am using the https://pub.dartlang.org/packages/camera
and am having a problem with image update. I have an image instantiated in my `build()` method with a new `Image.file(new File(img))`, where file is the local file saved from the camera. The file is saved and and new path is send to Flutter, but the image is not updated and according to this issue https://github.com/flutter/flutter/issues/7503 this is supposed to be fixed but it does not look that way.
```
[√] Flutter (Channel dev, v0.4.0, on Microsoft Windows [Version 10.0.17134.5], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.23.0)
[√] Connected devices (1 available)
```

**Comment by bhagirath** [comment]
facing a same issue. is there any solutions of it.

**Comment by bhagirath** [comment]
Future pickImage() async {
    ImagePicker.pickImage(source: ImageSource.gallery).then((onValue) {
    storage.imageStoragePath.then((dynamic dirPath) {
        final myPath = dirPath;
        File file = new File('$myPath/capture.png');
        file.writeAsBytes(onValue.readAsBytesSync()).then((savedFile) {
          setState(() {
            _imagePath = '$myPath/capture.png';
          });
        });
      });
    });
  }

Show Image 
Image.file(new File(_imagePath), width: 50.0, height: 50.0, fit: BoxFit.fitHeight,);

**Issue case.**
1. Pick image and save on local dir. (document directory)
2. Get file path of image and show image on screen. (it works)
3. Update image (Pick image again and save) on local dir with some other image. (same file name, same file path.)
4. Show updated image on screen. (Not working as aspected. It shows old image on screen.)

**Comment by zoechi** [comment]
Could you please try
```dart
        file.writeAsBytes(onValue.readAsBytesSync()).then((savedFile) {
          final imagePath = '$myPath/capture.png';
          new FileImage(imagePath).evict();
          setState(() {
            _imagePath = imagePath;
          });
        });
```

**Comment by bhagirath** [comment]
Hello Zoechi. thanks for prompt support. 

I have tried with above code. 
Following syntax error shows on  (new FileImage(imagePath).evict();) 
_The argument type string can not be assigned to the parameter type ‘File’._

Then I have tried with following syntax as well but no of them stops cashing and shows new image.
new FileImage(File(imagePath)).evict(); 
new FileImage(File(_imagePath)).evict();

Plz let me know if any solution available for it.

**Comment by zoechi** [comment]
```dart
new FileImage(File(imagePath)).evict();
```
is correct.
We will have to wait for someone else to have a look.

**Comment by bhagirath** [comment]
```
        File file = new File(imagePath);
        file.writeAsBytes(onValue.readAsBytesSync()).then((savedFile) {
          new FileImage(File(imagePath)).evict().then((evicted) {
            _imageFile = null;
            Future.delayed(Duration(milliseconds: 500)).then((val) {
              setState(() {
                _imageFile = new Image.file(new File(imagePath),
                    width: 50.0,
                    height: 50.0,
                    fit: BoxFit.fitHeight,
                    scale: 1.0);
              });
            });
          });
        });
```
Hello zoechi. 
Above code is working. and it change image on screen with other image for same image path. 
(1) required to evict cache. (2) then make image null & (3) add delay of at-least 500 milliseconds before setState.
All three steps are required. if i stop even one off them, it stops working. 
another thing is its flickers between image change on screen that is not correct. 

Plz help me if you get some idea by reviewing above logic.

Thanks.

**Comment by Thomas-Merlet** [comment]
Hello @bhagirath,
I'm running into the same issue. 
`new FileImage(File(imagePath)).evict()` returns that the method evict isn't defined for the class 'FileImage'. Am I missing something?

Thanks.

**Comment by jonahwilliams** [comment]
@bhagirath I would recommend just generating some auto incrementing id to replace the image path every time it is updated - there will always be at least a flicker if you try to replace the file in-place. While you can wait for the Dart image cache to release the image, there is no way to wait for the engine cache, so something like a timer would always be required.

@Thomas-Merlet you are probably on an older version of flutter, this was added in the last few months.

**Comment by MrWaggel** [comment]
I am having the same issue to date. Both on a virtual and physical android phone.

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/gilles/development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/gilles/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.3)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Moto G 5                  • ZY3222HBN9    • android-arm • Android 7.0 (API 24)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.0.2 (API 21) (emulator)
```

**Comment by rockingdice** [comment]
Met the same issue. 
Is the image cached behind the scene? I don't understand why the Image.file is not updating when the file is changed. 
Can I clean the cache if there's one?

**Comment by Levi-Lesches** [comment]
Thanks @rockingdice, your solution works!

There should really be a better way though, since this reloads the entire image every build (I'm making a private app so my users have no right to expect 60 FPS). Maybe something like checking the metadata of the file to see if it's been changed since last cached, and if so, automatically invalidate the cache (and perhaps animate to a new picture).

**Comment by voivoed** [comment]
I'm having the same issue. Now, I noticed this:

I'm debugging, and the wrong image is showing on my emulator. If I put a breakpoint and stop inside the Build() where the image is added to the tree (on the "child:" line below) and change something on the code that adds the image, in this case the scale of the image from 0.7 to 0.75 for example, when I save the file and the emulator hot reloads, the old image goes away and the correct image is shown.

Could it be some weird caching issue and when I rescale during the debug stop the image is recached? I don't know.

```
Padding(
  padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 16.0),
  child: Image.file(_image, scale: 0.7,),
),

```

**Comment by hyb1996** [comment]
same issue.
I found that the didUpdateWidget in image.dart caused this problem:
```dart
  @override
  void didUpdateWidget(Image oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (_isListeningToStream &&
        (widget.loadingBuilder == null) != (oldWidget.loadingBuilder == null)) {
      _imageStream.removeListener(_getListener(oldWidget.loadingBuilder));
      _imageStream.addListener(_getListener());
    }
    if (widget.image != oldWidget.image)
      _resolveImage();
  }
```
Even if the cache is cleared from imageCache, as long as widget.image has not changed, the image will not be reloaded. 
While FileImage compares the path and scale when comparing to others, obviously both of them have not changed.
```dart
@override
  bool operator ==(Object other) {
    if (other.runtimeType != runtimeType)
      return false;
    return other is FileImage
        && other.file?.path == file?.path
        && other.scale == scale;
  }
```

A workground is to copy the source of FileImage and modify it to compare by a id or file timestamp.

**Comment by Levi-Lesches** [comment]
So this _would_ update the image if the path passed to `Image.file` changes? Sorry, it's been a while since I touched that branch of my project.

**Comment by iamsandeepsk** [comment]
so, what is the best solution?

**Comment by marcos930807** [comment]
I will contribute my grain of sand. this is a workaround;
In my case changing the path of the files was not an option, so the solution is a combination of what was read in this thread. first if the file changes it is necessary to invalidate the cache this will guarantee that when the file is reloaded it will be updated with the new one.
1-**imageCache.clear();**
After de cache is cleared:
Second taken into account @hyb1996 comment abobe we need to grap de Image widget within a Valuekey  **key: ValueKey<int>(file.lengthSync())**, this wiil ensure that when the widget tree get rebuilded the image widget get rebuilded too.
Sorry for my bad English.
Hope that help.

**Comment by duncanista** [comment]
Someone just referenced this issue in a stackOverFlow post I made a while ago, what I did was using `Image.memory(encodeJpg(file))` to update the image.

[https://stackoverflow.com/questions/58794144/flutter-image-widget-wont-update-on-change-state](url)

**Comment by karmazinkd** [comment]
@marcos930807 is right.
The solution is just to ad a `key` property to your image widget and that's it.

Here is my example:

`ClipOval(
                  key: ValueKey(_avatarImageFile.lengthSync()), // <--- I added this line
                  child: Image.file(
                    _avatarImageFile,
                    width: 164.0,
                    height: 164.0,
                    fit: BoxFit.cover,
                  ),
                )`

**Comment by emileswain** [comment]
I had an issue where by i was loading an image, changing the contents of the file and then calling setstate on a Gridview with Cards using Image.file(). Of course they weren't updating. 

Stepping through the code i can see that Image.file() calls ResizeImage.resizeIfNeeded() which is passed an instance of FileImage() which is the image provider use to load and cache the image. 

The hash and == methods on FileImage use the file path and scale properties to check if the image needs acting upon. 

Compared to MemoryImage whos hash is the bytes of the image. Hence it Image.memory() will detect a change and update.

I tried tweeking the FileImage to use file.lastmodifiedSync() as a part of its hash, to varying degrees of success. I'm afraid i'm not that hot on Dart constructor instantiation so i couldn't quite get it to work. 

It makes sense perhaps that you could create a custom provider thats a tweeked version of FileImage. I.e. FileChangesImage whith the appropriate lastmodified check.

**Comment by emileswain** [comment]
The following adjustments seemd to work for me in detecting changes in a file image. I haven't fully tested it for edge cases but it appears to update the image in a gridview when the file itself is actually rewritten to. 

I duplicated the standard FileImage.dart and created a new one that includes the lastmodified data in the hash and == check.

Ok, so in Image.dart i added
```
Image.fileModifiable(
    File file, {
    Key key,
    double scale = 1.0,
    this.frameBuilder,
    this.errorBuilder,
    this.semanticLabel,
    this.excludeFromSemantics = false,
    this.width,
    this.height,
    this.color,
    this.colorBlendMode,
    this.fit,
    this.alignment = Alignment.center,
    this.repeat = ImageRepeat.noRepeat,
    this.centerSlice,
    this.matchTextDirection = false,
    this.gaplessPlayback = false,
    this.isAntiAlias = false,
    this.filterQuality = FilterQuality.low,
    int cacheWidth,
    int cacheHeight,
  }) : image = ResizeImage.resizeIfNeeded(cacheWidth, cacheHeight, FileImageModifiable(file, scale: scale, lastModified:file.lastModifiedSync().microsecondsSinceEpoch)),
       loadingBuilder = null,
       assert(alignment != null),
       assert(repeat != null),
       assert(filterQuality != null),
       assert(matchTextDirection != null),
       assert(cacheWidth == null || cacheWidth > 0),
       assert(cacheHeight == null || cacheHeight > 0),
       assert(isAntiAlias != null),
       super(key: key);
```

And in image_provider.dart i added

```
@immutable
class FileImageModifiable extends ImageProvider<FileImageModifiable> {
  /// Creates an object that decodes a [File] as an image.
  ///
  /// The arguments must not be null.
  const FileImageModifiable(this.file, { this.scale = 1.0, this.lastModified = -1 })
    : assert(file != null),
      assert(scale != null),
      assert(lastModified != null);

  /// The file to decode into an image.
  final File file;

  /// The scale to place in the [ImageInfo] object of the image.
  final double scale;

  /// The last Modified date
  final int lastModified;

  @override
  Future<FileImageModifiable> obtainKey(ImageConfiguration configuration) {
    return SynchronousFuture<FileImageModifiable>(this);
  }

  @override
  ImageStreamCompleter load(FileImageModifiable key, DecoderCallback decode) {
    return MultiFrameImageStreamCompleter(
      codec: _loadAsync(key, decode),
      scale: key.scale,
      informationCollector: () sync* {
        yield ErrorDescription('Path: ${file?.path}');
      },
    );
  }

  Future<ui.Codec> _loadAsync(FileImageModifiable key, DecoderCallback decode) async {
    assert(key == this);

    final Uint8List bytes = await file.readAsBytes();

    if (bytes.lengthInBytes == 0) {
      // The file may become available later.
      PaintingBinding.instance.imageCache.evict(key);
      throw StateError('$file is empty and cannot be loaded as an image.');
    }

    return await decode(bytes);
  }

  @override
  bool operator ==(Object other) {
    if (other.runtimeType != runtimeType)
      return false;
    return other is FileImageModifiable
        && other.file?.path == file?.path
        && other.scale == scale
        && other.lastModified == lastModified;
  }

  @override
  int get hashCode => hashValues(file?.path, scale, lastModified);

  @override
  String toString() => '${objectRuntimeType(this, 'FileImageModifiable')}("${file?.path}", scale: $scale, lastModified: $lastModified)';
}
```

**Comment by darshankawar** [comment]
Hi @MichaelSowah,
Can you please confirm if you still experience this issue on latest Flutter version and with latest `camera` plugin ?
Thanks.

**Comment by workflow2** [comment]
Same problem here, even when using imageCache.clear() doesn't work, any solution?

**Comment by emileswain** [comment]
> Same problem here, even when using imageCache.clear() doesn't work, any solution?

See @hyb1996 comment above for explanation of the problem. And if you feel confident i've posted above a solution i used (though its not great because updates to the flutter library will errase the changes i've made to the local flutter framework source files.)

**Comment by devviktoria** [comment]
Hi,
I had a similar issue, but in my case the Image widget was in a dialogue that can be opened/closed. If I reopened the dialogue the correct image was displayed. For me the imageCache.Clear nor the FileImage.evict() did not solved the issue. (Actually during debugging the ImageCache was completely empty when I observed it in the local variables section of the debugger ....)
For me what worked is:
1. Use an Image constructor with a FileImage parameter
2. In the Image widget specify the key as a ValueKey(hashValues(
      currentFileImageProvider.file.path,
      currentFileImageProvider.scale,
      currentFileImageProvider.file.lastModifiedSync(),
    );) where the currentFileImageProvider is the FileImage I used for creating the Image widget. (That is sort of a combination to what @marcos930807 and @emileswain suggested.)
I haven't checked the performance of this solution though.

**Comment by codetinker** [comment]
> It might be an issue with the image cache? I had a similar problem where a brand new image which was just added to the project, and just added to assets in pubspec.yaml, would not display, but it magically appeared after running this once in my code:
> 
> ```
> imageCache.clear();
> ```
> 
> I don't understand why this fixed it, because surely if the image doesn't exist in the cache previously, it should load from the file, so just wondered if there is a bug there somewhere.

imageCache.clear();
Solved my problem. Thanks
