### ISSUE TITLE
Having problem defining flutter as global variable for each terminal session to recognize flutter commands

### ISSUE THREAD

**Issue by Romnn** [flutter/flutter#17418]
I have followed the flutter.io steps to install flutter sdk
 Here are the steps I took : 
 1. Opened a new terminal window and entered the command 
`git clone -b beta https://github.com/flutter/flutter.git`
 It gave 

> fatal: destination path 'flutter' already exists and is not an empty directory.

I can understand that I have previously run the same command for installation process and thus have created this directory . fine 

Then I changed the path by : export PATH=`pwd`/flutter/bin:$PATH 
 as i press return a new line 

> Emperor-MacBook-Pro:~ Notorious$ 
appears as usual whenever we press return in terminal

To create a new .bash_profile file i commanded terminal `touch .bash_profile`

To Open the created .bash_profile i commanded `sudo nano .bash_profile`

Terminal asked for password and I gave it the password . It opened the .bash_profile file.

There i exported path as `export PATH=/flutter/bin:$PATH` and Hit control + X to save and quit -> Y to yes and return key to return back to terminal window

Then I entered `source $HOME/.bash_profile` to refresh the current window 
It gives me

>  -bash: export: `=': not a valid identifier
-bash: export: `/flutter/bin:/Users/mac/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin': not a valid identifier

When I command` $echo $PATH` i get 

> Users/mac/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

When I type flutt and Tab terminal automatically recognizes it as flutter 

And commanding `flutter doctor ` gives 

> Emperor-MacBook-Pro:bin Notorious$ flutter doctor
Warning: the 'flutter' tool you are currently running is not the one from the current directory:
  running Flutter  : /Users/mac/flutter
  current directory: /Users/mac/Documents/flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify
that you're running the expected version (run 'flutter --version' to see which flutter is on your path).

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.4.0, on Mac OS X 10.12.6 16G29, locale en-NP)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.23.0)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

In Opening new Terminal window to create new app say 'ios' i get error 

Emperor-MacBook-Pro:~ Notorious$ `flutter create ios`

> -bash: flutter: command not found

Emperor-MacBook-Pro:~ Notorious$

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by rowild** [comment]
@RomanEmperor the error is in this line:
```
There i exported path as export PATH=/flutter/bin:$PATH and Hit control + X to save and quit```

You need to add a `$HOME` before the flutter or whatever your `pwd` (present working directory) is.
