### ISSUE TITLE
[Enhancement] Ability to use Cronet in Flutter

### ISSUE THREAD

**Issue by NathanaelA** [flutter/flutter#17413]
I just saw that Cronet was released (just showed up in my Twitter feed today, so it might be a Google IO2018 release?) to be used in Android (and iOS in future(?); can't seem to find iOS docs yet) - For those coming to this issue Cronet is the network library that Chrome, Youtube, Play store, etc uses.    Talk about a battle tested network stack; Supports HTTP, HTTP2, Quic, Spdy, etc.     

I'm very interested in using this in my projects as the network stack that is current present has some shortcomings.     Now ultimately I doubt this is something that we want to replace the default dart network stack with; so for those who do want this -- it probably should be a optional plugin.

Now me being the enterprising plugin :grinning: developer - I quickly looked at the docs (https://developer.android.com/guide/topics/connectivity/cronet/start) real quick and saw that supporting this fully and properly is impossible in Flutter currently as a plugin due to the missing flutter sync support.  The callbacks that this uses require Sync support as the callbacks needs in some cases an immediate answer based on the data passed into the callback.

Which now leads me back to the lack of this: https://github.com/flutter/engine/pull/4358 is causing me issues again.      Unfortunately, I feel like I'm a broken record; @Hixie -- I almost didn't post this feature request; but decided if you really wanted all the places I run into blockers because of no sync support...

Without the iOS side of the docs, I can't tell you if I would run into the same issue; but if the plugin is using delegates the exact same fashion as android is using the callback; I would say it will have the same Sync requirement.

**Comment by Eimji** [comment]
Hello,
For my Flutter-based application (spilhenn https://play.google.com/store/apps/details?id=com.orange.labs.spilhenn, https://itunes.apple.com/fr/app/id1385377725) I am also looking for a way to enable QUIC with Flutter by using Cronet. 

NathanaelA, have you found more info since your post?

Patrick
Thanks.

Eimji

**Comment by huuang** [comment]
I need QUIC supporting too.

**Comment by Leadrive** [comment]
I need QUIC supporting too.

**Comment by zoechi** [comment]
@Leadrive 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by perezd** [comment]
Would love to see this happen, especially a win given that it's available on both native iOS and Android platforms!

**Comment by cuitao2046** [comment]
Looking forward to this feature for both android and iOS platforms!
Any plan so far?

**Comment by zzjjob** [comment]
I need QUIC supporting too.

**Comment by fzyzcjy** [comment]
Also need QUIC here. Any updates?

**Comment by AlexGx** [comment]
+1 for QUIC in Flutter

**Comment by erickharyono** [comment]
+1 for QUIC support
