### ISSUE TITLE
Flutter plugin for Android studio issue

### ISSUE THREAD

**Issue by deshmukhrohit11** [flutter/flutter#17416]
I installed flutter plugin. But it's not working. I am not able to create new flutter application using Android studio. There is no option to create new flutter project.

Build: 3.1.2, AI-173.4720617, 201804132127, 

AI-173.4720617, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1680x1050; Retina

Android Gradle Plugin: 3.1.2
Gradle: 4.4
NDK: from local.properties: (not specified); latest from SDK: (not found); 
LLDB: pinned revision 3.1 not found; latest from SDK: LLDB 2.3 (revision: 2.3.3614996); 
CMake: from local.properties: (not specified); latest from SDK: (not found); from PATH: 3.10.0;

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`

**Comment by deshmukhrohit11** [comment]
[rohitd@SYN-RM-MACPRO-12 flutter_study] flutter doctor -v
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.3 17D102, locale en-IN)
    • Flutter version 0.3.1 at /Volumes/Data/developement/flutter
    • Framework revision 12bbaba9ae (3 weeks ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Volumes/Data/sdk
    • Android NDK at /Volumes/Data/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Volumes/Data/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.1.2
    • Dart plugin version 181.4668.60

[✓] VS Code (version 1.23.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • 127.0.0.1:62001 • 127.0.0.1:62001 • android-x86 • Android 4.4.2 (API 19)

• No issues found!

<img width="1653" alt="screen shot 2018-05-09 at 12 12 54 pm" src="https://user-images.githubusercontent.com/3175812/39799585-6161a992-5382-11e8-8c4e-e333ce15c5d0.png">

**Comment by zoechi** [comment]
What if you click `New Project ...`?

![image](https://user-images.githubusercontent.com/405837/39799891-35584d72-5366-11e8-92c1-3603a1a0f12e.png)

There should also be a new beta available. Run `flutter upgrade` to get the new version.

**Comment by deshmukhrohit11** [comment]
[rohitd@SYN-RM-MACPRO-12 flutter_study] flutter upgrade
Upgrading Flutter from /Volumes/Data/developement/flutter...
From https://github.com/flutter/flutter
   12bbaba9a..44b7e7d3f  beta       -> origin/beta
   a742b11a5..de332ec78  dev        -> origin/dev
   a21c93dd7..21c2e47f2  master     -> origin/master
 * [new tag]             v0.3.4     -> v0.3.4
 * [new tag]             v0.4.2     -> v0.4.2
 * [new tag]             v0.3.5     -> v0.3.5
 * [new tag]             v0.3.6     -> v0.3.6
 * [new tag]             v0.4.0     -> v0.4.0
 * [new tag]             v0.4.1     -> v0.4.1
Updating 12bbaba9a..44b7e7d3f
 1 file changed, 1 insertion(+), 1 deletion(-)

Upgrading engine...
Building flutter tool...
Already up-to-date.

Flutter 0.3.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 12bbaba9ae (3 weeks ago) • 2018-04-20 01:02:44 -0700
Engine • revision 09d05a3891
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

Running "flutter packages upgrade" in flutter_study...      18.6s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.3 17D102, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.2)
[✓] VS Code (version 1.23.0)
[✓] Connected devices (1 available)

• No issues found!

<img width="1655" alt="screen shot 2018-05-09 at 12 23 25 pm" src="https://user-images.githubusercontent.com/3175812/39800158-8505c0ca-5384-11e8-9b39-de64ca6e6355.png">

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by ravichandrasv** [comment]
After installing flutter plugin android studio dart and flutter sdk i am getting this error

C:\...\...>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[ΓêÜ] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 6.1.7601]
cale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/inde
ml
      On first launch it will assist you in installing the Android SDK compo
s.
      (or visit https://flutter.io/setup/#android-setup for detailed instruc
s).
      If Android SDK has been installed to a custom location, set $ANDROID_H
to that location.
[!] Android Studio (version 2.3)
    X Flutter plugin not installed; this adds Flutter specific functionality
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
[ΓêÜ] Android Studio (version 3.1)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = /path/to/android/studio
    X Android Studio not found at /path/to/android/studio
[!] VS Code, 64-bit edition (version 1.25.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 5 categories.

C:\Users\Ravichandra>flutter doctor --v
Could not find an option named "v".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands
options.

C:\Users\Ravichandra>flutter doctor -v
[ΓêÜ] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 6.1.7601]
cale en-US)
    ΓÇó Flutter version 0.8.2 at C:\flutter
    ΓÇó Framework revision 5ab9e70727 (5 weeks ago), 2018-09-07 12:33:05 -07
    ΓÇó Engine revision 58a1894a1c
    ΓÇó Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/inde
ml
      On first launch it will assist you in installing the Android SDK compo
s.
      (or visit https://flutter.io/setup/#android-setup for detailed instruc
s).
      If Android SDK has been installed to a custom location, set $ANDROID_H
to that location.

[!] Android Studio (version 2.3)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    ΓÇó Try updating or re-installing Android Studio.

[ΓêÜ] Android Studio (version 3.1)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio1
    ΓÇó Flutter plugin version 29.0.1
    ΓÇó Dart plugin version 173.4700
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-10
02)

[!] Android Studio
    ΓÇó Android Studio at /path/to/android/studio
    X Flutter plugin not installed; this adds Flutter specific functionality
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = /path/to/android/studio
    X Android Studio not found at /path/to/android/studio
    ΓÇó Try updating or re-installing Android Studio.
    ΓÇó Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[!] VS Code, 64-bit edition (version 1.25.1)
    ΓÇó VS Code at C:\Program Files\Microsoft VS Code
    ΓÇó Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 5 categories.

**Comment by zoechi** [comment]
@ravichandrasv 

You have 2 Android Studio versions installed.
```
Android Studio (version 2.3)
```
```
[ΓêÜ] Android Studio (version 3.1)
```
Do you want to use VSCode or Android Studio with Flutter?
Did you install the Dart and Flutter plugins in Android Studio?
