### ISSUE TITLE
flutter --version slow and appears to have side effects

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#1742]
@sethladd  During the getting started workflow: https://flutter.io/getting-started/

I was very surprised that: ```Run flutter --version to ensure the flutter command is on your PATH.```
took many seconds to execute, and from the looks of the response:

```
Lukes-MacBook-Pro-2:flutter lukechurch$ flutter --version
Updating flutter tool...
Flutter from https://github.com/flutter/flutter.git (on alpha)
flutter revision: b6678c62bd3d4f6ddc89be7a480790f87ab62319 (2 hours ago)
```

Appears to have had a side effect?

I expected --version to be instant and always harmless to run. Perhaps telling me that there is another version available, a bit like the gcloud tools that I can apply with 'flutter upgrade' or the like.

**Comment by sethladd** [comment]
Hm, yeah, surprised that `flutter --version` actually runs an update.

**Comment by Hixie** [comment]
"Updating flutter tool..." happens the first time you run "flutter', it's independent of the "--version" part. We do that before we parse the arguments -- it's fetching the code that parses arguments (amongst other things). :-) (Basically it's doing "pub get".)

The rest of the code is side-effect free.

**Comment by sethladd** [comment]
@lukechurch suggestions on what wording we could use to make this cleaner/more obvious?

**Comment by lukechurch** [comment]
@sethladd "Running first time flutter setup, bear with us. You won't see this again"

also maybe consider putting a note in the getting started that it's going to do this?

**Comment by sethladd** [comment]
I love both of those ideas. Maybe "Running a setup for flutter, bear with us." since you will see this pause again after you update flutter.

**Comment by abarth** [comment]
In https://github.com/flutter/flutter/pull/1895 I'm changing this to say "Building flutter tool..."

**Comment by abarth** [comment]
IMHO, the messaging is clearer now.  We still need to add some information to the getting started guide, but that's in my revised draft that's being reviewed currently.  I'm going to close this issue.
