### ISSUE TITLE
flutter analyze --watch fails with optional const

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#17429]
If I apply the following diff:

```diff
diff --git a/packages/flutter/lib/src/widgets/banner.dart b/packages/flutter/lib/src/widgets/banner.dart
index c2efa4c..1026ee8 100644
--- a/packages/flutter/lib/src/widgets/banner.dart
+++ b/packages/flutter/lib/src/widgets/banner.dart
@@ -15,9 +15,9 @@ const double _kHeight = 12.0; // height of banner
 const double _kBottomOffset = _kOffset + 0.707 * _kHeight; // offset plus sqrt(2)/2 * banner height
 final Rect _kRect = new Rect.fromLTWH(-_kOffset, _kOffset - _kHeight, _kOffset * 2.0, _kHeight);

-const Color _kColor = const Color(0xA0B71C1C);
-const TextStyle _kTextStyle = const TextStyle(
-  color: const Color(0xFFFFFFFF),
+const Color _kColor = Color(0xA0B71C1C);
+const TextStyle _kTextStyle = TextStyle(
+  color: Color(0xFFFFFFFF),
   fontSize: _kHeight * 0.85,
   fontWeight: FontWeight.w900,
   height: 1.0
```

`flutter analyze --watch --flutter-repo` incorrectly displays errors in unrelated files:

```
   info • Prefer const with constant constructors. • examples/flutter_gallery/lib/gallery/home.dart:372:11
  error • Evaluation of this constant expression throws an exception. • examples/flutter_gallery/lib/gallery/home.dart:374:20
  error • Evaluation of this constant expression throws an exception. • packages/flutter/test/widgets/banner_test.dart:252:7
  error • Evaluation of this constant expression throws an exception. • packages/flutter/test/widgets/banner_test.dart:254:16
```

`flutter analyze --flutter-repo` displays no errors.

```
[✓] Flutter (Channel master, v0.4.1-pre.30, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.1-pre.30 at /home/aar-dw/perso/dev/dart/flutter/flutter
    • Framework revision 231b9425d6 (il y a 20 heures), 2018-05-08 11:06:58 -0700
    • Engine revision 20b286dd42
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b
```

I haven't found a simple reproduction for now.

**Comment by devoncarew** [comment]
I haven't dug into this, but I assume that `flutter analyze --flutter-repo` (non --watch) doesn't exhibit the  issue? Do you still see if if you clear the analysis server cache? (`rm -rf ~/.dartServer/.analysis-driver/`)

**Comment by a14n** [comment]
Same error after deleting `~/.dartServer/.analysis-driver/`.

**Comment by a14n** [comment]
@devoncarew did you have time to take a look? It looks related to top level const variables.

**Comment by a14n** [comment]
@mit-mit removing optional `const` in example works without issue (I can make a PR for that if you want). If I also remove optional `new` some lints start reporting false positives and those lints need to be updated to handle optional new/const.

**Comment by mit-mit** [comment]
I believe @Hixie requested that we wait with removing until the lint is ready?

**Comment by devoncarew** [comment]
@a14n, to clarify, this isn't a problem with the `avoid_keyword_to_create_instances` lint, but with lints (and possibly general analysis errors) that don't handle optional new/const well?

**Comment by a14n** [comment]
@devoncarew yes. This issue is specific to analysis.

**Comment by devoncarew** [comment]
Filed an issue here: https://github.com/dart-lang/linter/issues/1008 to upgrade the lints to work with optional new / const.

**Comment by devoncarew** [comment]
@bwilkerson - the `Evaluation of this constant expression throws an exception` error above seems like an issue with the const eval code, not necessarily a lint. Can you take a look (and, would you like a separate tracking bug?).

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/57000

**Comment by a14n** [comment]
Awesome, thanks!
