### ISSUE TITLE
how does flutter implement jetpack

### ISSUE THREAD

**Issue by touseefbsb** [flutter/flutter#17433]
io18 just announced **Android Jetpack** https://developer.android.com/jetpack/

which simplifies and implements best practices for modern android development, along with kotlin and kotlin-ktx. my question is that when flutter generates android apps, does it also apply those best practices to ensure better quality apps? or does flutter just have their own independent architecture?

**Comment by touseefbsb** [comment]
maybe this question clarifies in detail what I want to actually know. :) https://www.reddit.com/r/androiddev/comments/8j6jju/kotlin_with_jetpack_or_flutter_which_one_is/

**Comment by Rockvole** [comment]
Sorry I don't have a Reddit account.

I found a video about some of the new jetpack features :
https://www.youtube.com/watch?v=IrMw7MEgADk

I think there is no competition - Flutter is easier for a beginner to get started with.
The flutter tutorials I have viewed have been straightforward to follow :
https://www.youtube.com/watch?v=CEPCGXQ7IQg

**Comment by touseefbsb** [comment]
yes I already watched these sessins from io 18 but still thanks :) @Rockvole  I just want some technical insights between two technologies because I dont wanna choose 1 of them , build my complex app on it and later on regret that I didnt choose the other better option and then migrating would be very tough, so I want to choose best option before hand.

**Comment by Rockvole** [comment]
There are probably not many people who know both of those well right now. Maybe just a few people in google, and they don't want to say anything bad about another project.

You can assume you can do anything its possible to do using jetpack and android native - so you wont have any restrictions. It would probably be easier to ask a few questions about whether flutter can do what you need. There are a lot of experts on the flutter gitter you can ask :
https://gitter.im/flutter/flutter

**Comment by jules15** [comment]
I do think the poster raises an interesting point. It took Android a long time before it introduced an "opinionated" framework (Jetpac) that provided a canonical architecture, separation of concerns and better testability, all helping to avoid Android's many pitfalls. When I look at Flutter examples, I'm concerned that history is repeating itself. I realize there are many competing architectures and approaches (MVP, MVVM, MVC, ...), but it might be useful for the team to start encouraging appropriate separation of concerns.

**Comment by touseefbsb** [comment]
also am not sure if this is relevant but introducing functional programming into the mix will make the code less error prone and even more testable and many more benefits which only a FP expert can tell ( which I am not ) dart does look like a language relevant to FP, so if flutter can also have a built in framework or even a separate one to just plug in like jetpack which encourages separation of concerns and maybe encourage functional programming, it can be beneficial for long term maintenance of the framework and also maintenance of the apps built with the framework

**Comment by zoechi** [comment]
I think it would be better to raise individual issues for features you're missing.
I just had a brief look at the jetpack page linked in the initial comment, but it seems like a collection of features and tools from all kind of areas.
Requesting to add an "all-covering" framework to a framework seems to be a weird request to me.

**Comment by Hixie** [comment]
I don't really understand the request here. We do intend to do the right thing on each platform, though we may not always yet do so. I recommend filing specific bugs on any issues that need work.
