### ISSUE TITLE
Incremental building and hot reload do not take into account changes to packages  

### ISSUE THREAD

**Issue by fuzzybinary** [flutter/flutter#17437]
It appears that when performing an incremental build or a hot reload, Flutter does not capture changes to local packages.  In order for Flutter to capture the changes I usually need to
* Delete the built app from the simulator
* flutter clean
* rebuild and re-run the app. 

This is difficult in two circumstances:
1) Using a shared package for Flutter / AngularDart development (a rare case)
2) Running examples during plugin development.

I wouldn't necessarilly expect Flutter to capture changes in all packages, but at least those mapped to a local or relative director (as in the two above use cases) would be helpful.

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

As far as I remember this worked for me.

**Comment by fuzzybinary** [comment]
Unfortunately I haven't had time to experiment with this much recently, so we may want to close this unless someone else complains.

Last I checked, hot reload would capture package changes, but build would not, so the workaround would end up being to run the app and then immediately hot reload to pick up changes in a specific library.
