### ISSUE TITLE
Integrating Javascript business logic into Flutter App

### ISSUE THREAD

**Issue by bryanrideshark** [flutter/flutter#17440]
Is it possible to integrate business logic written in Javascript, with a Flutter app?

We use a Redux style business logic layer in our enterprise web app; We cannot afford to write this logic in two separate languages.

Would it be possible to run a Javascript thread on the V8 engine, inside a Flutter app? Then, the flutter app would talk to the business logic via a simple interface, with flutter taking the responsibility of much of the UI / navigation, leaving the responsibility of the app logic to the shared business layer?

We are deciding whether or not to go with a React Native implementation. Right now, that's the only platform which can support this code sharing scenario. We'd be interested in Flutter if it were possible to share Javascript business logic.

**Comment by NathanaelA** [comment]
At this point Flutter is only Dart; however one potential work around is that you could technically embed the Node engine into Flutter as a plugin.   This will give you an additional thread that runs JavaScript on iOS and Android, so you could basically do something like Node.Run("jscode()").  

I haven't actually tried this with Flutter, but I did create a plugin to do it with NativeScript, so I do believe it should be very possible to do this in Flutter.    (NativeScript; is also a JavaScript based system that would also support code sharing JavaScript just like RN, so don't limit yourself to just RN.)

**Comment by zoechi** [comment]
You could also run JavaScript in a WebView https://github.com/dart-flitter/flutter_webview_plugin
but Dart itself has no JavaScript capabilities, it can just be compiled to JavaScript to be run in the browser (or Nodejs).
