### ISSUE TITLE
Commands given to upgrade to cocoapods 1.5.0 don't upgrade to 1.5.0

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#17447]
On a recent `flutter run` I got the following message:

```
Warning: CocoaPods recommended version 1.5.0 or greater not installed.
Pods handling may fail on some projects involving plugins.
To upgrade:
  brew upgrade cocoapods
  pod setup
```

Executing the first command tells me this:
```
Error: cocoapods 1.4.0 already installed
```

What's the actual command to upgrade to 1.5.0?

@xster @mravn-google

**Comment by goderbauer** [comment]
Also: shouldn't `flutter doctor` also tell me that my version is out of date?

**Comment by goderbauer** [comment]
The following sequence of commands worked for me:

```
$ brew update
$ brew upgrade cocoapods
$ pod setup
```

**Comment by thetnaingmizo** [comment]
Execute the following on your terminal to get the latest stable version:

> sudo gem install cocoapods

Add --pre to get the latest pre release:

> sudo gem install cocoapods --pre

**Comment by cuichanghao** [comment]
Mac high sierra cannot install to /usr/bin you need below command to install /usr/local/bin

```
sudo gem install cocoapods -n /usr/local/bin
```

**Comment by Moukale** [comment]
> Mac high sierra cannot install to /usr/bin you need below command to install /usr/local/bin
> 
> ```
> sudo gem install cocoapods -n /usr/local/bin
> ```

It really did the job for me. Thx @cuichanghao

**Comment by cnTomato** [comment]
> > Mac high sierra cannot install to /usr/bin you need below command to install /usr/local/bin
> > ```
> > sudo gem install cocoapods -n /usr/local/bin
> > ```
> 
> It really did the job for me. Thx @cuichanghao

good job

**Comment by jmagman** [comment]
The text was updated with https://github.com/flutter/flutter/pull/36093.
```
sudo gem install cocoapods
```
Closing.

**Comment by Jonathansoufer** [comment]
sudo gem uninstall cocoapods or brew uninstall cocoapods
sudo gem install cocoapods or brew install cocoapods
rm -fr ˜/.rbenv/shims/pod
ln -s /usr/local/bin/pod ˜/.rbenv/shims/pod

Hope it helps.
