### ISSUE TITLE
Flutter MethodChannel for Obj-C should support NSData as an argument type

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#17449]
`NSData` is the type that's most frequently used in Obj-C for representing binary data; however, the Flutter plugin expects you to wrap `NSData` in `FlutterStandardTypedData`. Since that API is not type safe and `NSData` is what's typically used, I've accidentally checked in code using `NSData` instead of `FlutterStandardTypedData` twice now. Can the method channel for Obj-C support `NSData` directly?

**Comment by matthew-carroll** [comment]
CC @dnfield for visibility
