### ISSUE TITLE
Including firebase_auth creates errors and I cannot even start the app.  Steps to reproduce:  Create a flutter app Add firebase_auth: "^0.5.9" to the pubspec.yaml file Add the GoogleService-Info.plist downloaded from firebase console to the Runner directory of the app Run flutter run command Here is the outputs of flutter run

### ISSUE THREAD

**Issue by ludashen** [flutter/flutter#17458]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by zoechi** [comment]
Including firebase_auth creates errors and I cannot even start the app.  Steps to reproduce:  Create a flutter app Add firebase_auth: "^0.5.9" to the pubspec.yaml file Add the GoogleService-Info.plist downloaded from firebase console to the Runner directory of the app Run flutter run command Here is the outputs of flutter run

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?
