### ISSUE TITLE
AdMob Plugin - Ad Positioning

### ISSUE THREAD

**Issue by gcshri** [flutter/flutter#17452]
Currently using firebase_admob: "^0.5.4+1" in pubspec.yaml.

Is it possible to use the admob banner (ideally DFP, but since DFP support is unavailable) to inline a banner in a widget scaffold?

Would ideally like to be able display banners in our content, not as interstitial or sticky ads at the bottom.

E.g.

![screenshot_20180510-085442](https://user-images.githubusercontent.com/14210493/39846771-1e16b2dc-5430-11e8-8f33-27012f9a6b51.png)

**Comment by amirh** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
Support for ads that can be embedded in Flutter's widget tree  requires https://github.com/flutter/flutter/issues/12114. Unfortunately #19030 doesn't help with that.

**Comment by Purus** [comment]
There is another plugin in the pub now which has this feature... https://github.com/YoussefKababe/admob_flutter . Refer to the screenshots.

**Comment by amirh** [comment]
As mentioned in https://github.com/flutter/flutter/issues/17452#issuecomment-415128984 this requires #12114. I'm closing this issue and we will keep tracking this in #12114.

**Comment by kroikie** [comment]
@gcshri

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/832. Any further collaboration will be done there.
