### ISSUE TITLE
How to add tabBar to Scaffold without appBar.

### ISSUE THREAD

**Issue by vipulasri** [flutter/flutter#17459]
I want to have `tabBar` as the topmost widget in the `Scaffold` but with no `appBar` and have elevation to the `tabBar`.

![screenshot_20180510-124052](https://user-images.githubusercontent.com/7822179/39857814-4bc3ac54-5452-11e8-8a9f-571bc934bf49.png)

I dont want to have that empty space above `tabBar` because of `appBar` title. And also move the `tab` in `tabBar` to left/start alignment.

    new Scaffold(
      appBar: new AppBar(
        bottom: new TabBar(
          isScrollable: true,
          unselectedLabelColor: Colors.grey,
          indicatorColor: Colors.black54,
          tabs: <Tab>[
            new Tab(
              text: "Featured",
            ),
            new Tab(
              text: "Popular",
            ),
          ],
          controller: _tabController,
        ),
        title: null,
      ),
    );

**Comment by kaetemi** [comment]
Tried `flexibleSpace`?

```
    return new DefaultTabController(
      length: 3,
      child: new Scaffold(
        appBar: new AppBar(
          flexibleSpace: new Column(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              new TabBar(,
                tabs: [
                  new Tab(icon: new Icon(Icons.directions_car)),
                  new Tab(icon: new Icon(Icons.directions_transit)),
                  new Tab(icon: new Icon(Icons.directions_bike)),
                ],
              ),
            ],
          ),
        ),
      ),
    );
```

**Comment by vipulasri** [comment]
@kaetemi Thanks, the elevation thing worked and using `crossAxisAlignment: CrossAxisAlignment.start` tabs moved to left/start.

**Comment by TakeoffAndroid** [comment]
@kaetemi and @vipulasri You guys are awesome. Both the things worked!. Thanks a lot

**Comment by sandangel** [comment]
should we rename the appBar prop of Scaffold? As we can use PreferredSize too.
```dart
     child: Container(
        height: 230.0,
        decoration: BoxDecoration(border: Border.all(color: kOrangeColor)),
        child: DefaultTabController(
          length: 2,
          child: Scaffold(
            appBar: PreferredSize(
              preferredSize: Size.fromHeight(35.0),
              child: TabBar(
                indicator: BoxDecoration(color: kOrangeColor),
                labelStyle: TextStyle(color: Colors.white),
                unselectedLabelColor: kOrangeColor,
                tabs: <Widget>[
                  Tab(child: Text('基本機能', style: TextStyle(fontSize: 18.0))),
                  Tab(child: Text('拡張機能', style: TextStyle(fontSize: 18.0))),
                ],
              ),
            ),
            body: Container(
```

**Comment by baixiaoyu2997** [comment]
我就是想要一个tabbar 顶部没有空白的写法，但是试了`flexibleSpace `这个例子还是不行。原因是Column布局`mainAxisAlignment: MainAxisAlignment.end,`导致了`Tabbar`显示在下边。可行的代码为：
```diff
DefaultTabController(
      length: 3,
      child: new Scaffold(
        appBar: new AppBar(
          flexibleSpace: new Column(
-          mainAxisAlignment: MainAxisAlignment.end,
            children: [
              new TabBar(
                tabs: [
                  new Tab(icon: new Icon(Icons.directions_car)),
                  new Tab(icon: new Icon(Icons.directions_transit)),
                  new Tab(icon: new Icon(Icons.directions_bike)),
                ],
              ),
            ],
          ),
        ),
      ),
    );
```
