### ISSUE TITLE
flutter upgrade won't run if the engine is out of date

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1745]
Running `flutter upgrade` will fail with a message to run `pub get` if the engine is out of date. We should not include `upgrade` in the engine check, since it would fix the issue.

**Comment by collinjackson** [comment]
Can you clarify what you mean by "should not include upgrade in the engine check"?

**Comment by devoncarew** [comment]
Yup, when I ran `flutter upgrade`, I got an error:

```
[~/flutter/flutter_sunflower] flutter upgrade
Error: incompatible sky_engine package; please run 'pub get' to get the correct one.
```

which `pub get` fixed, but my understanding is that `flutter upgrade` should fix the error as well. We should not include the `upgrade` command in the sky_engine package check.

**Comment by collinjackson** [comment]
OK, I understand now that you mean we should perform the sky_engine package check in the ```upgrade``` command. Makes sense!
