### ISSUE TITLE
Change IME action button

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#17465]
I wrote a detailed description of my problem [here](https://stackoverflow.com/q/50107284/6509751) and I realized that this is not supported by Flutter natively at the moment.

Basically it is changing the action button of the soft keyboard. This is possible through code/XML in Android and iOS native, but not supported for Flutter `TextField`'s.

**Comment by goderbauer** [comment]
Dup of https://github.com/flutter/flutter/issues/17525.

**Comment by creativecreatorormaybenot** [comment]
@goderbauer Other way bout, but hey..
