### ISSUE TITLE
CupertinoRefreshControl doesn't disappear in some cases

### ISSUE THREAD

**Issue by Asoseil** [flutter/flutter#17474]
I tested this behavior on the example https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/cupertino/cupertino_refresh_demo.dart
If i change childCount to 2, after a pull to refresh, the CupertinoRefreshControl widget doesn't disappear. RefreshIndicatorMode seems correctly set to "done" so the problem could be related to the scrollview or to the render system

**Comment by xster** [comment]
Yup, I can repro, it's definitely broken

**Comment by xster** [comment]
Not sure I completely understand what's going on yet. Seems like the sliver constraints are correctly reflecting that there's a -60px overlap and is in overscroll mode at the end of the refresh but isn't triggering the overscroll physics for some reason.

**Comment by Asoseil** [comment]
Without onrefresh field or with a short delay it works, but if the delay is more than 1 second it remains stuck

**Comment by Winghin2517** [comment]
I'm experiencing this as well. Please see sample code to reproduce the issue as well as gif demonstrating the issue here: https://stackoverflow.com/questions/50305379/flutter-cupertinorefreshcontrol-does-not-dismiss

**Comment by xster** [comment]
The flow is basically that after `_RenderCupertinoRefreshSliver.performLayout` returns a SliverGeometry with a `scrollOffsetCorrection`, in `RenderViewport.performLayout`, if the list was previously filling the viewport, in `offset.applyContentDimensions`, it would eventually look for how much scroll extent there is and if it was different, it would eventually go to the scroll activity and trigger `delegate.goBallistic(0.0)` on IdleScrollActivity. 

However, if both with and without the refresh indicator, the list content is smaller than the viewport, `ScrollPosition.applyContentDimensions` ends up skipping everything and doesn't trigger the now overscrolled list to snap back.

**Comment by Winghin2517** [comment]
So in other words, if the list is too short, the Cupertino Refresh Control
will not disappear.
Is there anyway to fix this?
