### ISSUE TITLE
Build gen_snapshot with correct target_os on Windows

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#17489]
In Windows builds, we [override](https://github.com/flutter/engine/blob/f2acd0adec76bc827d7e213f4224cf98c0b6de4e/tools/gn#L127-L133) `target_os` to `win`. For `android-arm` and `android-arm64` builds of `gen_snapshot` we should be building with `target_os="android"`. Previously this resulted in #17387. 

We should eliminate this override and fix up the rest of the build to correctly support building gen_snapshot (and ideally the engine) on Windows; this would also make it easier for Windows developers to contribute to the engine.

**Comment by dnfield** [comment]
Is this still the case? It looks like the linked code is no longer that way, and AFAICT we're building gen_snapshot on Windows now.

**Comment by markusaksli-nc** [comment]
Closing this as it seems done, feel free to reopen if this isn't the case.
