### ISSUE TITLE
Ensure goldens generated on different host platforms are identical

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17483]
Extracting a tracking TODO from https://github.com/flutter/flutter/pull/17366 to make sure tests can update and match on different platforms.

**Comment by markusaksli-nc** [comment]
Hasn't this been done at some point already?

**Comment by kf6gpe** [comment]
@Piinks Is this now happening with the goldens work you did last spring?

**Comment by Piinks** [comment]
Yes! I believe we can close this. :)

**Comment by nilsreichardt** [comment]
Is this really fixed? Even with Flutter `2.2.0` generated goldens are different between macOS and Linux.
