### ISSUE TITLE
firebase_messaging: Management of data messages when activity is killed

### ISSUE THREAD

**Issue by jankuss** [flutter/flutter#17482]
If the app is in a killed state and a data message is sent, the app will call the onMessageReceived of the FlutterFirebaseMessagingService, but since the Activity is killed the FirebaseMessagingPlugin can not respond to the intent and the message is lost.

This is a problem when somebody wants to perform an action depending on the data which is contained in a message.

Are there any plans to handle this kind of behaviour?

**Comment by janpansa** [comment]
We have a similar use case. When the app is terminated the notification is not delivered. We would still like to store a record of these messages in the application where a user can view or delete them later from the app. Currently, this is not possible on Android devices, although this worked when not using flutter and just the standard android sdk. Would really like to see an option for this use case.

**Comment by pavankumarkatakam** [comment]
I would also like to see this feature

**Comment by pavankumarkatakam** [comment]
Can we add one more class extending FirebaseMessagingService and register in Manifest file, is this possible?

**Comment by kroikie** [comment]
@jankuss

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/829. Any further collaboration will be done there.
