### ISSUE TITLE
Issue from website page Get Started: Install

### ISSUE THREAD

**Issue by ericstandlee** [flutter/flutter#17492]
From URL: https://flutter.io/get-started/install/
No Chromebook? Why not Android?

**Comment by zoechi** [comment]
Is installing Linux tools officially supported in Chromebook?
For what Android devices would this make sense?

**Comment by jslavitz** [comment]
@chihyun

**Comment by JediBurrell** [comment]
>Why not Android?

This link is for installing the Flutter SDK, not the apps built with it. The SDK cannot be installed on Android.

---

@zoechi It's in beta, but yes.  
Chromebooks don't need a separate "instruction" link from Linux as the steps are the same.

**Comment by Hixie** [comment]
I think this is answered by the comments above.
