### ISSUE TITLE
Flutter related crash after released(Android)

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#17495]
We've released our app, and notice several crashes.I've symbolicated the log as below:
1.LayoutUtils.cpp related crash.
```terminal
KyleWongdeMacBook-Pro:engine kylewong$ cd /Users/kylewong/Codes/Flutter/betav031/engine/src 
KyleWongdeMacBook-Pro:src kylewong$ ./third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line -e out/android_release/libflutter.so 00305af8 00303eb9 00303dc5 0030a50d 0006c685 00069f05 00069ebf 003e1e1b
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/third_party/txt/src/minikin/LayoutUtils.cpp:88
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/third_party/txt/src/minikin/Layout.cpp:664
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/third_party/txt/src/minikin/Layout.cpp:616
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/third_party/txt/src/txt/paragraph.cc:531
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/lib/ui/text/paragraph_impl_txt.cc:54
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../topaz/lib/tonic/dart_args.h:150
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../topaz/lib/tonic/dart_args.h:198
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../third_party/dart/runtime/vm/native_entry.cc:198
```

2.Memory related crash
a.
```terminal
KyleWongdeMacBook-Pro:src kylewong$ ./third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line -e out/android_release/libflutter.so 0014e28d 001fc0ed 000745c7 000748f9 000748a7 00508113 0007412f 0007406d 0007c11d 0007b89b 0007f32b 0007bfb1 0004da95 00053651
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../third_party/skia/src/ports/SkMemory_malloc.cpp:21
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../garnet/public/lib/fxl/logging.cc:93
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/runtime/dart_vm.cc:407
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../garnet/public/lib/fxl/memory/ref_ptr_internal.h:32
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../garnet/public/lib/fxl/memory/ref_ptr.h:232
/Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/mutex.cpp:241
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/mutex:548
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/runtime/dart_vm.cc:230
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/shell/common/shell.cc:190
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/shell/common/shell.cc:47
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/shell/common/shell.cc:178
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/shell/common/shell.cc:174
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/shell/platform/android/android_shell_holder.cc:64
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/memory:3047
```

b.
```terminal
KyleWongdeMacBook-Pro:src kylewong$ ./third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line -e out/android_release/libflutter.so 0050ac21 0050ace5 005097ed 0050935d 005098c3 000a6673 000a6773 0007b33d 0007b1a7 000816ef 0005a871 0005d2af 0005d26b 0005a9cf 0005bf69
/Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74
/Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/cxa_default_handlers.cpp:63
/Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/cxa_handlers.cpp:68
/Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/cxa_exception.cpp:149
/Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/cxa_new_delete.cpp:50 (discriminator 2)
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../third_party/skia/src/core/SkData.cpp:69
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../third_party/skia/src/core/SkData.cpp:100
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/shell/common/rasterizer.cc:194
linux-atomic.c:?
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/shell/common/shell.cc:896
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/functional:1756
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/fml/platform/android/message_loop_android.cc:93
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/fml/platform/android/message_loop_android.cc:69
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/fml/message_loop_impl.cc:76
/Users/kylewong/Codes/Flutter/betav031/engine/src/out/android_release/../../flutter/fml/thread.cc:34
```

##Flutter Doctor Result
```
[✓] Flutter (Channel xy_beta_v0.3.1, v0.3.2-pre.23, on Mac OS X 10.13.4 17E202, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[!] Connected devices
    ! No devices available
```

**Comment by eseidelGoogle** [comment]
@kangwang1988 mentioned to me: "The crash rate is slow and acceptable. You guys may have a look at it to see if it's a problem. For us, it's not a blocker.
These four are all for android now."

**Comment by najeira** [comment]
I am getting same crashes.

Flutter v0.4.4

```
flutter/third_party/txt/src/minikin/LayoutUtils.cpp:88
flutter/third_party/txt/src/minikin/Layout.cpp:664
flutter/third_party/txt/src/minikin/Layout.cpp:616
flutter/third_party/txt/src/txt/paragraph.cc:557
flutter/lib/ui/text/paragraph_impl_txt.cc:54
topaz/lib/tonic/dart_args.h:150
topaz/lib/tonic/dart_args.h:198
third_party/dart/runtime/vm/native_entry.cc:198
third_party/icu/source/i18n/rematch.cpp:3510
```

**Comment by najeira** [comment]
Flutter v0.4.4

```
third_party/skia/include/core/SkRefCnt.h:332
third_party/skia/src/gpu/gl/GrGLSemaphore.cpp:18
third_party/skia/include/core/SkRefCnt.h:87
third_party/skia/src/gpu/GrBackendTextureImageGenerator.cpp:71
third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/memory:2431
third_party/skia/include/core/SkRefCnt.h:193
third_party/skia/include/core/SkRefCnt.h:87
flutter/flow/skia_gpu_object.cc:18
garnet/public/lib/fxl/memory/ref_counted.h:71
garnet/public/lib/fxl/memory/ref_ptr.h:105
linux-atomic.c:?
third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/deque:2810
third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/deque:1552
flutter/fml/thread.cc:34
```

**Comment by najeira** [comment]
Flutter v0.4.4

```
flutter/fml/memory/weak_ptr.h:175
flutter/shell/common/shell.cc:492
flutter/shell/common/platform_view.cc:36
flutter/shell/platform/android/platform_view_android.cc:74
flutter/shell/platform/android/platform_view_android_jni.cc:424
```

**Comment by najeira** [comment]
Flutter v0.4.4

```
flutter/shell/common/vsync_waiter.cc:38
third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/__functional_base:380
third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/functional:1756
```

Low frequency

**Comment by eseidelGoogle** [comment]
@jason-simmons can you look at the top crash?

**Comment by jason-simmons** [comment]
It's happening within Minikin's word breaking logic.  I didn't notice any obvious problems with the word breaker, so possibly we're passing in an invalid buffer.  It would help a lot to know more about the text that is being rendered when this happens.

**Comment by najeira** [comment]
It seems that it does not always occur with a specific text.

**Comment by najeira** [comment]
After upgraded Flutter 0.2.1 to 0.4.4, crash and ANR are increasing in our app.

Is not this reported from English users? If so, is the issue related to Japanese and Chinese?

**Comment by najeira** [comment]
I will try upgrading Flutter to 0.5.7. It has some libtxt fixes.

**Comment by najeira** [comment]
I think I can solve the crash at LayoutUtils.cpp. Now, I am testing custom engine. I will send a Pull-Request if it goes well.

**Comment by najeira** [comment]
This issue has some crash reports. I will report them as another issue.

**Comment by kangwang1988** [comment]
We've received hundreds of crash reports about libflutter.so.

Thread Name: '1.ui'
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr c3980000
  r0 c397ffc0  r1 0000e000  r2 0000008d  r3 00000000
  r4 0000000c  r5 0000000f  r6 0000000c  r7 0000000c
  r8 00000000  r9 c397ffc0  10 00000000  fp 00000000
  ip 00000020  sp c296d638  lr c888347d  pc c88850b8  cpsr 800d0030
    #00 pc 0x2db0b8 libflutter.so
    #01 pc 0x2d9479 libflutter.so
    #02 pc 0x2d9385 libflutter.so
    #03 pc 0x2dfc17 libflutter.so
    #04 pc 0x6a2bd libflutter.so
    #05 pc 0x691f5 libflutter.so
    #06 pc 0x691af libflutter.so
    #07 pc 0x3b5b77 libflutter.so
    #08 pc 0x2344 vm_snapshot_instr

The symbolicated call stack is as below:
KyleWongdeMacBook-Pro:src kylewong$ ./third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line -e /Users/kylewong/Codes/EngineProducts/android_release/libflutter.so 
0x305af8
/Users/xyqa/Documents/SourceCode/Flutter/engine/src/out/android_release/../../third_party/boringssl/src/crypto/fipsmodule/bn/add.c:90
0x303eb9
/Users/xyqa/Documents/SourceCode/Flutter/engine/src/out/android_release/../../third_party/boringssl/src/crypto/evp/p_dsa_asn1.c:182
0x303dc5
/Users/xyqa/Documents/SourceCode/Flutter/engine/src/out/android_release/../../third_party/boringssl/src/crypto/evp/p_dsa_asn1.c:127
0x30a50d
/Users/xyqa/Documents/SourceCode/Flutter/engine/src/out/android_release/../../third_party/boringssl/src/crypto/fipsmodule/bn/generic.c:695
0x06c685
/Users/xyqa/Documents/SourceCode/Flutter/engine/src/out/android_release/../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/string:1791
0x069f05
/Users/xyqa/Documents/SourceCode/Flutter/engine/src/out/android_release/../../topaz/lib/tonic/dart_args.h:93
0x069ebf
/Users/xyqa/Documents/SourceCode/Flutter/engine/src/out/android_release/../../topaz/lib/tonic/dart_args.h:93
0x3e1e1b
/Users/xyqa/Documents/SourceCode/Flutter/engine/src/out/android_release/../../third_party/dart/runtime/vm/object.cc:3949

We're using flutter betav0.5.1 and the corresponding commit(engine repo git) is:1ed25ca7b7e3e3e8047df050bba4174074c9b336

The problem mainly happens on android7.0/8.0/7.1.1.
@eseidelGoogle 
Please have a look why this problem might happen and how to fix it.

**Comment by zoechi** [comment]
@kangwang1988 to me your issue looks different than the original report.
Can you please create a new issue and fill the issue template?
#18744 or #15727 look more similar than this one. 
There was also a fix recently in `master` channel.

**Comment by kangwang1988** [comment]
@zoechi  Sorry, just now, I used the wrong libflutter.so for symbolicating.
I want to say that this problem(minikin logic related crash in Layout.cpp) still exists in our app.
@jason-simmons  What's your suggestion? Should I add some print logic about what is being rendered so that it could be reported to us when crashed?

**Comment by kangwang1988** [comment]
@zoechi  Which commit?

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/19379#issuecomment-405714031

**Comment by najeira** [comment]
I fixed crash at LayoutUtils.cpp by https://github.com/flutter/engine/commit/b8cd25b4fcae781c781797c9a80ff193f4488f1f .

I use Flutter v0.5.1 and custom engine that include the patch by cherry-picking.

**Comment by kangwang1988** [comment]
@najeira Well done.
Besides, how can I reproduce the problem and verify it has been fixed?

**Comment by najeira** [comment]
@kangwang1988 It is difficult to confirm that it was fixed. Because the crash caused by memory access outside the buffer, that is, it depends on the memory data at that time.

I distributed a new version of our app to some users. I had them use the app for a while. I confirmed that the crash no longer occurred.

**Comment by kangwang1988** [comment]
@najeira 
Got it. Thanks for your contribution. I will try a new version for bucket testing to check whether the problem disappears.
