### ISSUE TITLE
Dismissable invalidates the MixedViewport even when the size doesn't change

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#175]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Sep 25, 2015 at 20:16 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1352_

----

Dismissable uses a SquashTransition with a performance with a 0.4..1.0 Interval. This means that for the first 40% of the performance, it's ticking but not doing anything. Yet we still fire resize events on the mixed viewport. We should not.

**Comment by abarth** [comment]
Fixed by LazyBlock.
