### ISSUE TITLE
Issue from website page Support

### ISSUE THREAD

**Issue by RohanAndroid** [flutter/flutter#17505]
From URL: https://flutter.io/support/
Hello,
I am using an android studio to make flutter application. It runs fine on Android phones. Now I want to check on iPhone. what can I do now and is there any IDE which runs flutter application both in android and ios at once?

**Comment by zoechi** [comment]
You need XCode to create an iOS version of your app.
XCode only runs on OSX.
See also this comment https://github.com/flutter/flutter/issues/17471#issuecomment-388171536
