### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by efidje** [flutter/flutter#17508]
Hi,

I ran into some issues while testing out an appBar demo. Took a screen dump and included the main.dart file (saved as .txt). Not sure why it threw an error.

![exception_error](https://user-images.githubusercontent.com/17090510/39925870-afe2b514-552d-11e8-81f2-e644547abd26.png)
[main_dart.txt](https://github.com/flutter/flutter/files/1995383/main_dart.txt)

**Comment by zoechi** [comment]
`length: 3` but `TabBarView(
            children: [ ... ` has 6 children

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
