### ISSUE TITLE
Add info in the doc about order in returned list for Future.wait(Iterable<Future> futures)

### ISSUE THREAD

**Issue by marica27** [flutter/flutter#17506]
In the [doc](https://www.dartlang.org/tutorials/language/futures#waiting-on-multiple-futures-to-complete-using-futurewait) about Futures.wait(Iterable<Future> futures) there is no information about the order of responses in returned list. 
> This Future completes with a list containing the values produced by each function

So it's unclear which result is where in List responses.

 @zoechi answered in chat that order is the same as function order.
So, mention please this in the tutorial page and in the code.  

It could be like this:
typedef String expensiveA();
typedef int expensiveB();
typedef int expensiveC();

Future
    .wait([expensiveA(), expensiveB(), expensiveC()])
    .then((List responses) {
    String resultA = responses[0];
    int resultB = responses[1];
    int resultC = responses[2];
}).catchError((e) => handleError(e));

**Comment by zoechi** [comment]
Dup of https://github.com/dart-lang/sdk/issues/31109
