### ISSUE TITLE
Scaffold without AppBar still drawing its container in iOS

### ISSUE THREAD

**Issue by cetorres** [flutter/flutter#17519]
My app has a BottomNavigationBar. I have a Stack with Offstage widgets holding each one a MaterialApp widget as child.
Inside each MaterialApp widget there's a default Scaffold, but with no AppBar (because the main AppBar is outside already, this MaterialApp is inside a tab). 
So, even setting the AppBar to null or not setting it at all, the bar empty space still appears on the screen.
In my app, I have a ListView taking the whole screen of the tab. So the list starts beneath the "invisible" AppBar. I realized that I can set padding 0 to listview and it appears on top of the screen again. But then the first item of the list is almost unclickable because the "invisible" AppBar is on top of it, avoiding the touch.
This happens only on iOS. It doesn't happen on Android.

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.3.5, on Mac OS X 10.13.4 17E202, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (3 available)

• No issues found!

**Comment by zoechi** [comment]
Can you please provide the code for a minimal reproduction?
