### ISSUE TITLE
NetworkImage changes headers

### ISSUE THREAD

**Issue by zocker1996** [flutter/flutter#17515]
The NetworkImage class changes the headers I provided.
More specifically it appended "Dart/2.0 (dart:io), " before what I set as User-Agent. I want my server to only serve requests from my application so I want to enforce my custom User-Agent. Of course I could allow a User-Agent with "Dart/2.0 (dart:io), " as prefix but the problem here is that I don't know if "Dart/2.0 (dart:io), " is going to change soon.

**Comment by jonahwilliams** [comment]
This isn't set by the NetworkImage, but by the Dart sdk's HttpClient.  Presumably this wouldn't change without a bump in the Dart sdk version.

cc @zanderso

**Comment by jonahwilliams** [comment]
@zocker1996  If you want to you can override the HttpClient created by NetworkAsset and NetworkImage using [HttpOverrides](https://docs.flutter.io/flutter/dart-io/HttpOverrides-class.html).  This will give you a change to set the user agent manually using the API mentioned above.

**Comment by zoechi** [comment]
I assume the suggestions solve this issue.
