### ISSUE TITLE
Support for customizing return key

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#17525]
iOS has support for changing what the return/done key on the keybaord should be labeled with, see https://developer.apple.com/documentation/uikit/uireturnkeytype?language=objc.

We should expose this in Flutter. Currently, we only support `UIReturnKeyDefault` and `UIReturnKeyDone`, see [1]

We should also cross-check this with what android supports.

[1] https://github.com/flutter/engine/blob/7fa08b3ba94cb32cf0a2f466e5ee5d539d144705/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L32-L36

**Comment by sir-boformer** [comment]
It would be great to have an inputAction field in the `TextField` widget. It's crucial for chat apps ("send"), search fields ("search") and complex forms ("next"). 

I stumbled upon this issue while porting a login form: The keyboard of the user name input should display a "next" button, which moves the focus to the password input.

---------------------

Here is what Android supports:

- `IME_ACTION_DONE`
- `IME_ACTION_GO`
- `IME_ACTION_NEXT`
- `IME_ACTION_SEARCH`
- `IME_ACTION_SEND`
- `IME_ACTION_NONE` (newline)

https://developer.android.com/reference/android/view/inputmethod/EditorInfo

Right now the displayed action is [bound to the `keyboardType` of the `TextField`](https://github.com/flutter/flutter/blob/2ae48845a8b05dba8310ad78ea21beb16d442bb2/packages/flutter/lib/src/widgets/editable_text.dart#L458-L460).

In the Android engine, only a small change in the [inputActionFromTextInputAction](https://github.com/flutter/engine/blob/7fa08b3ba94cb32cf0a2f466e5ee5d539d144705/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L117-L121) method is required to support additional actions.

**Comment by goderbauer** [comment]
@matthew-carroll You implemented this, right? Can we close it?

**Comment by matthew-carroll** [comment]
@goderbauer Yep, I think we're good here.  Interested parties can refer to the following PR:
https://github.com/flutter/flutter/pull/18855
