### ISSUE TITLE
CustomScrollView not clipping properly

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#17522]
From a G3 customer:

> I just added a CustomScrollView to our nascent app, and ran into what seems to be a funny rendering issue.
> 
> It looks like the CustomScrollView overflows at the end (right) when it is scrolled all the way to the beginning.  The moment I scroll one pixel to the left, the overflow at the end (right) disappears, and the CustomScrollView behaves as expected.

The client has a horizontal list of Chips inside their scrollview, and the list isn't clipping properly when scrolled all the way to the left.

We're tracking this at b79582605.

**Comment by mehmetf** [comment]
We are unable to reproduce this.
