### ISSUE TITLE
flutter_platform should use `package:build_runner_core` when it becomes available

### ISSUE THREAD

**Issue by grouma** [flutter/flutter#17520]
Running Dart programs from source in Dart 2 has non-trivial overhead compared to running from kernel. To improve the developer workflow for iterating on tests, we should leverage `package:build_runner_core` to modularly build and run flutter tests from kernel.

This is blocked on:
https://github.com/dart-lang/build/issues/1428
https://github.com/dart-lang/build/issues/1427

**Comment by grouma** [comment]
Note as a part of this work we should also create some benchmark tests.

**Comment by zoechi** [comment]
The linked issues are fixed.

**Comment by grouma** [comment]
I believe this work falls on the Build and Test team and @jakemac53 is looking into it.

**Comment by jakemac53** [comment]
There is currently a problem blocking CI environments for packages with a lot of tests - probably blocked on that https://github.com/dart-lang/sdk/issues/33952. We might actually be able to get around that though for flutter because they might already have the plumbing to work with modular kernel files.

**Comment by zoechi** [comment]
@jakemac53  dart-lang/sdk#33952 seems to be fixed.

**Comment by jakemac53** [comment]
Yes, we need to give that a chance to make its way into the flutter sdk as well - but I don't know the best way to track that :thinking:

**Comment by jakemac53** [comment]
we also need to update build_vm_compilers to use it first, which I can work on as soon as it is in a dev release which should be soon if one isn't already available

**Comment by zoechi** [comment]
@jakemac53 friendly ping

**Comment by jonahwilliams** [comment]
We currently run flutter_tests from kernel today, though we don't use build_runner.

**Comment by jakemac53** [comment]
We can probably close this issue given that we are pretty much going in the opposite direction at this point for flutter at least. This is assuming the frontend_server has some way of sharing work across tests, otherwise build_runner may be better.

**Comment by jonahwilliams** [comment]
SGTM
