### ISSUE TITLE
SharedPreferences in Flutter are cumbersome and confusing

### ISSUE THREAD

**Issue by gregko** [flutter/flutter#17526]
Assume I have created a SharedPreferences object and now want to get say a bool value from it, which I may have stored there before or not. In Android Java it's just one line:

> boolean myBool = sharedPrefs.getBoolean("MyBool", false); // default to false if not present.

In Flutter somehow myBool becomes null now if it was not stored before - just wasted 2 hours wondering where and how a simple bool variable could be null. In Flutter I have to write instead:

```
bool myBool = sharedPrefs.getBool("myBool");
if (myBool == null)
  myBool = false;
```

Please provide default value for a preference not present, like Android Java/Kotlin, and if you make that default optional, please initialize it to correct type default value, e.g. bool to false, int to 0 etc.

**Comment by gregko** [comment]
Thank you, indeed. I'm still learning Dart and Flutter. I never expected that a value explicitly declared as bool may be null, why is it allowed? Here is how my original confusion originated and it may indicate instead a bug in Flutter debugger.

Not expecting that a variable explicitly declared as bool may have a null value, I instead wrapped the SharedPreferences get in a try-catch, expecting an error or exception when the value was not present. This worked for a few weeks, until Beta 3 of Flutter was released:

```
bool myBool = false
try {
  myBool = sharedPrefs.getBool("myBool");
} catch () {}
```
Later in the code I had the following lines:

```
String someStr = ...; // it was NOT null
//...
if (someStr.contains('something')) {
  otherStr = myBool ? 'one' : 'two'; // string expressions were more complex
  // ...
}  else {
  // other code
}
```

All of this worked until Beta 3 was released yesterday (I actually work from Master branch, but when I hit this problem, I tested also Dev and Beta yesterday). What was very confusing was the error message like "AssertError: bool cannot be null". It was NOT giving me the exact line number, just the module name. So I traced the code under a debugger in Android Studio and the error triggered as soon as I pressed F8 on this line:

`if (someStr.contains('something')) {`

Therefore I thought the contains() function had a bug and was producing null value, but copying and pasting it into Alt-F9 window (evaluate variable or expression under the debugger) worked fine. This is why I wasted 2 hours, trying to find work-around, submitting then deleting another Flutter bug etc.

If the exception was triggered instead on otherStr = myBool ? 'one' : 'two';  line, it would be obvious where the problem was instantly. Or if the stack trace of the Assert failure contained the number of this line. Should this be submitted as a bug against the Flutter debugger instead?

**Comment by zoechi** [comment]
> I never expected that a value explicitly declared as bool may be null, why is it allowed?

In Dart variables of every type can be `null`. It's the same as a variable of type `int` or `Foo` can be `null`.
There are plans to introduce non-nullable types after Dart 2.0.

> This worked for a few weeks, until Beta 3 of Flutter was released:

Flutter switched to `--preview-dart-2` being switched on by default to enable Dart 2 semantics where tighter type checks are used.

> Should this be submitted as a bug against the Flutter debugger instead?

If you can provide steps to reproduce then it's definitely worth creating an issue.

**Comment by gregko** [comment]
Thank you, submitted, with a complete source code in zip. Issue link:

https://github.com/flutter/flutter/issues/17544
