### ISSUE TITLE
List<Widget> How to auto-wrap into a block? 

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#17531]
**Flutter** is really a great framework. I am having a simple trouble on doing a tiny APP. I wanna build a block of chips which generate by a for.. loop like this:
```
List<Widget> _buildChips(){
    List<Widget> chipsWidgets = [];
    for (int i=0; i< this.hotSearched.length; i++) {
      chipsWidgets.add(new Chip(
        avatar: new CircleAvatar(
                      backgroundColor: Colors.grey.shade800,
                      child: new Text('AB'),
                    ),
        label: new Text(this.hotSearched[i]),
      ));
    }
    return chipsWidgets;
  }
```
Its just take strings from a defined list. But **no idea how to place it**, it can not place into a row, cause it will out of boundry. it also can not place into a cloum, because I want the chips automatically wrap and change line.

After a long search there are no solution. Anyone would like to help me out?

**Comment by escamoteur** [comment]
Use a Flow or Wrap

**Comment by zoechi** [comment]
Is this still an issue?
