### ISSUE TITLE
ML Kit for Firebase (for Flutter) - Google I/O 2018

### ISSUE THREAD

**Issue by ColquePaxi** [flutter/flutter#17532]
Is there any date? Is there packages or plugins has been develop? There are many interesting things to do!!!

**Comment by wtesler** [comment]
I want this so bad.

**Comment by zoenberger** [comment]
Yes, I neeeeed this. Specifically for iOS. About to start coding, but I need a way to read barcodes first. Would prefer to use ML Kit.

**Comment by ColquePaxi** [comment]
Hey @zoenberger,  there is a brazilian guy (Eduardo Folly) playing this project:

https://pub.dartlang.org/packages/flutter_mobile_vision

Inspire yourself or use it.  

Hugs.

**Comment by ColquePaxi** [comment]
My dear @azihsoyn  , so glad for your iniative, but to newbies like me would be cool gift us with a documentation to show minimal prerequisites, configs (gradle, manisfest, etc),  and mainly Firebase version's incompatibilities. See you too the package https://pub.dartlang.org/packages/flutter_mobile_vision to inpire yourself. Hugs, guy.

**Comment by azihsoyn** [comment]
@ColquePaxi awesome package! Thanks, introduce!

**Comment by Hixie** [comment]
cc @mravn-google @collinjackson @kroikie

**Comment by wtesler** [comment]
https://pub.dartlang.org/packages/flutter_mobile_vision uses the outdated
Google Mobile Vision ( https://developers.google.com/vision/ ) so it's not
ideal. An ML-kit library would be the better option.

**Comment by ColquePaxi** [comment]
Perfectly @wtesler .

**Comment by azihsoyn** [comment]
flutter_mlkit now supports iOS and document updated.

https://pub.dartlang.org/packages/mlkit

In 0.2.0, Scanning barcode supported for iOS. (android will be released in 0.2.1)

Thanks.

**Comment by Hixie** [comment]
@bparrishMines Did you say you wanted to work on this one? (If so, please assign it to yourself, thanks!)

**Comment by bparrishMines** [comment]
Yea, I am. I'm starting on it this week. I'll assign myself to it.

**Comment by startupgurukul** [comment]
@bparrishMines  Noticed a couple of pull requests for MLVision. Looking forward to a flutter package. And curious to know why the name, MLVision, not MLKit. Could we expect another plugin for using custom tf models?

**Comment by bparrishMines** [comment]
I named it MLVision in order to maintain similar naming to the Android and iOS APIs.

https://firebase.google.com/docs/reference/android/com/google/firebase/ml/vision/FirebaseVision

And yes, there will most likely need to be a separate plugin for custom models. Ideally named MLInterpreter.

**Comment by startupgurukul** [comment]
Thank you @bparrishMines, created an issue for CustomML Interpreter. #18660 hoping that you get some bandwidth to implement that as well

**Comment by manikvashisht** [comment]
@azihsoyn Is there a way to use this Library and scan the barcode in Camera View(without capturing the actual image)

**Comment by azihsoyn** [comment]
Hi, @manikvashisht !
Live detection (https://github.com/flutter/plugins/pull/688) is now in progress.

**Comment by yuenweikdu** [comment]
May i know is scan QR Code supported? i will be happy if reply is fast ^^

**Comment by charafau** [comment]
> May i know is scan QR Code supported? i will be happy if reply is fast ^^

There is barcode scanner in pub: https://pub.dartlang.org/packages/barcode_scan

**Comment by zoechi** [comment]
Is this covered by https://pub.dartlang.org/packages/firebase_ml_vision or is this about something else?

**Comment by startupgurukul** [comment]
Not yet looking to being able to run custom tflite model.

**Comment by bparrishMines** [comment]
@zoechi Yes, the `firebase_ml_vision` plugin covers the ML Kit vision portion. However, there will also be a `firebase_ml_custom` and `firebase_ml_speech` plugins. However, these are long term milestones.

**Comment by bparrishMines** [comment]
Closing this issue and opening a new one for custom ML models https://github.com/flutter/flutter/issues/28859

**Comment by kroikie** [comment]
@ColquePaxi

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/828. Any further collaboration will be done there.
