### ISSUE TITLE
Unable to hot reload. No instance of Flutter is currently running.

### ISSUE THREAD

**Issue by 1priyank1** [flutter/flutter#17533]
When I change some code or strings of Text widget and save the file, below error show in the console. 
Then after I need to relaunch application to run.

```
Initializing hot reload...
Unable to hot reload. No instance of Flutter is currently running.
Unhandled exception:
Bad state: No element
#0      List.first (dart:core-patch/dart:core/array.dart:165)
#1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:542)
#2      _rootRunUnary (dart:async/zone.dart:1134)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      Future._propagateToListeners (dart:async/future_impl.dart:666)
#7      Future._completeWithValue (dart:async/future_impl.dart:481)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:511)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by 1priyank1** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Linux, locale en_IN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Android license status unknown.
[✓] Android Studio (version 2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by mravn-google** [comment]
Seen this one twice today, on two different dev machines. [This line](https://github.com/flutter/flutter/blame/master/packages/flutter_tools/lib/src/run_hot.dart#L579) assumes there is at least one reload report, which apparently isn't always true.

**Comment by mravn-google** [comment]
cc @aam

**Comment by mravn-google** [comment]
Reproduced twice across quite a lot of attempts. Both times were on first launch after clean builds.

**Comment by aam** [comment]
Thanks for the report. This seems to be a different flavor of https://github.com/flutter/flutter/issues/14517, which was papered over. Generally speaking, lack of reload report from the VM should be treated as a fatal error since from that point on flutter on the host machine can't have any confidence in what is happening on the device.
Ideally we figure out why Dart VM didn't provide a report. If it is possible to repro this failure with engine with `--trace_reload` and `--trace_reload_verbose` added to the https://github.com/flutter/engine/blob/master/runtime/dart_vm.cc#L68, that should help

**Comment by zoechi** [comment]
I believe this is stale. #14517 is fixed.
Please let us know if you're still seeing this problem.

**Comment by prntcena** [comment]
Hot reload failed: Bad state: No element
