### ISSUE TITLE
Breakpoints with crosses on Android Studio

### ISSUE THREAD

**Issue by rignaneseleo** [flutter/flutter#17546]
Hello,
My app doesn't debug: I've the 'breakpoints with the crosses' issue on Android Studio and I don't know how to fix it.

<img width="196" alt="immagine" src="https://user-images.githubusercontent.com/11429943/39967976-da26bc1e-56c5-11e8-899c-c104fb7a38a1.png">

[Here](https://stackoverflow.com/questions/24040220/android-studio-breakpoint-cross-explanation) I read about the same problem and a guy says that its caused by the old code running on the device. 
In my case it's not true because I tried fresh installation in differend devices.

I also tryied the command 'flutter clean' but nothing.
What do you suggest to do?

I'm running the last version of flutter with the last android studio on Mac.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by rignaneseleo** [comment]
I tried to remove and reinstall Android Studio but nothing changed.
I noticed that if I try to attach the debugger to the app process, it gives me this error:
![image 2018-05-14 17 15 44](https://user-images.githubusercontent.com/11429943/40006352-70a4fc4e-579a-11e8-8cc2-7e53a749cde6.jpg)

Maybe there is something wrong with the JDK.

**Comment by JSANL** [comment]
@rignaneseleo 
May I ask if you found a solution? I have the exact same problem.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.
