### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by absalomedia** [flutter/flutter#17542]
Just wondering if the Google Analytics data integrated with flutter should be opt in instead of opt out, in line with GDPR..

**Comment by Areiser** [comment]
I was also wondering how/if the firebase admob plugin will allow the developer to specify if non-personalized ads or personalized ads should be served. Not everything is clear so far on that front, I am also waiting for the Consent-SDK to understand the situation better.

**Comment by bearty** [comment]
Any news? I need GDPR for multiplayer and ads in my app.

**Comment by Areiser** [comment]
@bearty Even though it wasn't posted in this thread, NPAs are now available in the admob plugin to address my main issue. Not sure if there is an official opt-in/opt-out widget.

**Comment by kroikie** [comment]
@absalomedia

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/827. Any further collaboration will be done there.
