### ISSUE TITLE
Flutter Gallery 0.4.2 fails to load icons.

### ISSUE THREAD

**Issue by nsreenath** [flutter/flutter#17549]
Flutter Gallery 0.4.2 April 2018 version running on Android 7.0 Moto G4 Plus fails to load the icons as shown in below screenshots.

![screenshot_20180514-005339 01](https://user-images.githubusercontent.com/3154529/39971044-5469d082-5712-11e8-9e57-f21936216fa4.png)
![screenshot_20180514-005332 01](https://user-images.githubusercontent.com/3154529/39971045-551ce14a-5712-11e8-9c1b-1c5043b27b9a.png)

**Comment by zoechi** [comment]
Dup of #17485 ?

**Comment by nsreenath** [comment]
Closing this as dup of #17485
