### ISSUE TITLE
Flutter ImagePicker Plugin (No implementation found for method pickImage)

### ISSUE THREAD

**Issue by PonnamKarthik** [flutter/flutter#17545]
### MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)

```
E/flutter ( 8747): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 8747): MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter ( 8747): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 8747): <asynchronous suspension>
E/flutter ( 8747): #1      ImagePicker.pickImage (package:image_picker/image_picker.dart:47:40)
E/flutter ( 8747): <asynchronous suspension>
E/flutter ( 8747): #2      _HomeState.getImage (package:sensegrass/screens/home.dart:20:35)
E/flutter ( 8747): <asynchronous suspension>
E/flutter ( 8747): #3      _HomeState.build.<anonymous closure> (package:sensegrass/screens/home.dart:85:11)
E/flutter ( 8747): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
E/flutter ( 8747): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
E/flutter ( 8747): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 8747): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter ( 8747): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter ( 8747): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter ( 8747): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 8747): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 8747): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter ( 8747): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter ( 8747): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 8747): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter ( 8747): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter ( 8747): #17     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter ( 8747): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

```

**Comment by pythoneer** [comment]
@PonnamKarthik what did resolve your problem? I am having the same issue and by closing this issues by yourself on the same day makes me wonder that this was due to some error by using this plugin. Could you explain how you got rid of this problem?

**Comment by pythoneer** [comment]
Ok i think i figured out myself. The trivial thing was to add permissions to the Android manifest file for using the camera. 

```xml
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
```

i guess that's an issue with the documentation! On the iOS side its clearly documented how to configure your project on iOS but it is explicitly stated for Android that

```
Android

No configuration required - the plugin should work out of the box.
```

which lead me to just ignore setting permissions explicitly. Its not only missing to set permissions, it is misleading to do the right thing in the first place and try to figure out how to solve this, whereas you would normally just look at the permission which the documentation misleads by saying "don't care about permissions, we have your back".

**Comment by Mounikareddymouni** [comment]
Android :
I added permissions in android but still facingsame issue

**Comment by wilk3ns** [comment]
Problem still persists why topic is closed? I'm facing similar issues. Can't get plugin working on Android. iOS works ok

**Comment by chorauoc** [comment]
Problem still persists why topic is closed? , i have the same issue with image picker

**Comment by supotsaea2504** [comment]
I solve this problem by 'flutter clean && flutter run'  command in terminal.

**Comment by wilk3ns** [comment]
flutter clean solves the problem indeed. But often leads another error.

**Comment by quangvuk** [comment]
Hi all,

I tried : 
`import 'dart:io';
import 'dart:async';`

[Follow this ](https://www.youtube.com/watch?v=gkYQKFE0Fmk)

It worked well for me!

**Comment by karam-esf** [comment]
I am having the same problem -:(

**Comment by mishkashishka** [comment]
All you need to do is reinstall your app to aplly changes, at least it works for me)

**Comment by alange-pivotal** [comment]
Having this issue on IOS:

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel external_custom_packages.plugins.flutter.io/image_picker)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      ImagePicker.pickImage (package:image_picker/image_picker.dart:53:40)
<asynchronous suspension>
#2      _AvatarNameComponents._getPicture (package:swopda_frontend/widgets/editcontact/avatar_name_components.dart:85:23)
<asynchronous suspension>
#3      _AvatarNameComponents._settingCustomModalBottomSheet.<anonymous closure>.<anonymous closure> (package:swopda_frontend/widgets/editcontact/avatar_name_components.dart:141:21)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#15     _rootRunUnary (dart:async/zone.dart:1136:13)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18     _invoke1 (dart:ui/hooks.dart:233:10)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)


using:
  image_picker: ^0.6.0+9
in pubspec.yml

using flutter project -i swift -a kotlin

**Comment by halfbaked** [comment]
In my case, as the image picker plugin is using android X, my project also needed to be upgraded to Android X. 
Details on how to do that can be found here: https://flutter.dev/docs/development/androidx-migration
I simply had to add the following lines to `android/gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```
and then run `flutter clean`

**Comment by AamirSk** [comment]
In my case, Android is working fine but **iOS have problem**. I am using latest version **image_picker 0.6.1+8**. Anyone have clue on this

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      ImagePicker.pickImage (package:image_picker/image_picker.dart:59:40)
<asynchronous suspension>
#2      _SESSEditProfileScreenState.showImagePicker (package:saed_ess/ui/screens/Profile/SESSEditProfileScreen.dart:1252:36)
<asynchronous suspension>
#3      _SESSEditProfileScreenState._openFileSelector.<anonymous closure>.<anonymous closure> (package:saed_ess/ui/screens/Profile/SESSEditProfileScreen.dart:1235:17)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureR<…>

**Comment by AamirSk** [comment]
> Having this issue on IOS:
> 
> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel external_custom_packages.plugins.flutter.io/image_picker)
> #0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
> 
> #1 ImagePicker.pickImage (package:image_picker/image_picker.dart:53:40)
> 
> #2 _AvatarNameComponents._getPicture (package:swopda_frontend/widgets/editcontact/avatar_name_components.dart:85:23)
> 
> #3 _AvatarNameComponents._settingCustomModalBottomSheet.. (package:swopda_frontend/widgets/editcontact/avatar_name_components.dart:141:21)
> #4 _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
> #5 _InkResponseState.build. (package:flutter/src/material/ink_well.dart:566:30)
> #6 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
> #7 TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
> #8 TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
> #9 GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> #10 _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
> #11 _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
> #12 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
> #13 _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
> #14 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
> #15 _rootRunUnary (dart:async/zone.dart:1136:13)
> #16 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #17 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
> #18 _invoke1 (dart:ui/hooks.dart:233:10)
> #19 _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
> 
> using:
> image_picker: ^0.6.0+9
> in pubspec.yml
> 
> using flutter project -i swift -a kotlin

Did you get any solution for this..?

**Comment by hashirabdulbasheer** [comment]
This happens to me too. Happens for iOS only. The plugins works fine on android. Happens for other plugins like shared_preferences too. 

I debugged the plugins a little bit and found that its register method does get called on iOS. However the handleMessage method never gets invoked and the exception is thrown.

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)

I suspected setMockMethodCallHandler implementation initially. Here is a comment that i found over the method implementation in platform_channel.dart

/// Sets a mock callback for intercepting method invocations on this channel.
  ///
  /// The given callback will replace the currently registered mock callback for
  /// this channel, if any. To remove the mock handler, pass null as the
  /// `handler` argument.
  ///
  /// Later calls to [invokeMethod] will result in a successful result,
  /// a [PlatformException] or a [MissingPluginException], determined by how
  /// the future returned by the mock callback completes. The [codec] of this
  /// channel is used to encode and decode values and errors.
  ///
  /// This is intended for testing. Method calls intercepted in this manner are
  /// not sent to platform plugins.
  /

However, the strange thing is that the plugin works on android. And, there were no calls to setMockMethodCallHandler. 

My flutter doctor output:

[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.3 18D109, locale en-SA)
    • Flutter version 1.10.7 at /Users/hashir/Developer/flutter
    • Framework revision e70236e36c (3 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hashir/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    ✗ Android SDK file not found: /Users/hashir/Library/Android/sdk/platforms/android-29/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone Xʀ • 4A93D602-957E-4BE2-8E5E-2F5B931590CB • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

**Comment by hashirabdulbasheer** [comment]
we had converted an existing iOS app into flutter. We did it long time back and it was not as per the guidelines specified in [](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps).

Following the guidelines mentioned in the wiki to convert existing ios app into flutter solves the missing plugin exceptions.

**Comment by WillGatto** [comment]
ok, I got this one,  at least worked here...these are the codes to get the image from the source I used:

Future getImageFromCamera() async {
    var image = await ImagePicker.pickImage(source: ImageSource.camera);
    setState(() => imageURI = image);
  }

  Future getImageFromGallery() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
    setState(() => imageURI = image);
  }

and the pickImage method has an Future with async call,  so when you call the get image inside your code it also must have this async call, as here:

 FloatingActionButton(
                                      backgroundColor:
                                      Color.fromRGBO(73, 117, 152, 1.0),
                                      child: Icon(Icons.image),
                                      onPressed: () async =>
                                      await getImageFromGallery(),
                                    ),

I really hope this helps. :)

**Comment by pushpam5** [comment]
flutter clean and then flutter run worked for me

**Comment by salahuddin-1** [comment]
Just reinstall ur app and it will work
Just quit ur app, and flutter run it again..
