### ISSUE TITLE
CreateProcessW failed 193, on flutter doctor & flutter upgrade

### ISSUE THREAD

**Issue by joergenwold** [flutter/flutter#17543]
Have some serious issues with my flutter in both intelliJ Ultimate and Android studio. Problems started occurring while i was trying to get the camera package to my project in the pubspec.yaml file. Then i tried to run the doctor, but that failed aswell, not sure what to do guys...

Please ask if there is something you dont understand with my English, not my first language :)

list of problems i am having:
- packages get: exit code 0
- doctor/doctor -v: CreateProcessW failed 193

[flutter_02.log](https://github.com/flutter/flutter/files/1998327/flutter_02.log)
[flutter_03.log](https://github.com/flutter/flutter/files/1998328/flutter_03.log)
[flutter_04.log](https://github.com/flutter/flutter/files/1998329/flutter_04.log)
[flutter_01.log](https://github.com/flutter/flutter/files/1998330/flutter_01.log)

-----------------terminal output--------------------------------------------------
Microsoft Windows [Version 10.0.17134.48]

C:\AndroidProjects\chappy2\chappy>C:\flutter\flutter\bin\flutter.bat config --no-analytics
Analytics reporting disabled.

C:\AndroidProjects\chappy2\chappy>C:\flutter\flutter\bin\flutter.bat update-packages
Running "flutter packages get" in automated_tests...         0,9s
Running "flutter packages get" in complex_layout...          1,2s
Running "flutter packages get" in microbenchmarks...         1,1s
Running "flutter packages get" in bots...                    1,0s
Running "flutter packages get" in devicelab...               1,1s
Running "flutter packages get" in channels...                1,1s
Running "flutter packages get" in external_ui...             1,1s
Running "flutter packages get" in flavors...                 0,9s
Running "flutter packages get" in platform_interaction...    0,9s
Running "flutter packages get" in ui...                      1,2s
Running "flutter packages get" in manual_tests...            0,8s
Running "flutter packages get" in vitool...                  0,8s
Running "flutter packages get" in tools...                   1,0s
Running "flutter packages get" in catalog...                 1,0s
Running "flutter packages get" in flutter_gallery...         1,3s
Running "flutter packages get" in flutter_view...            0,7s
Running "flutter packages get" in hello_world...             0,9s
Running "flutter packages get" in layers...                  1,0s
Running "flutter packages get" in platform_channel...        0,9s
Running "flutter packages get" in platform_channel_swift...  0,9s
Running "flutter packages get" in platform_view...           0,5s
Running "flutter packages get" in stocks...                  0,9s
Running "flutter packages get" in flutter...                 0,9s
Running "flutter packages get" in flutter_driver...          0,9s
Running "flutter packages get" in flutter_localizations...   0,9s
Running "flutter packages get" in flutter_test...            1,0s
Running "flutter packages get" in main...                    0,5s
Running "flutter packages get" in flutter_tools...
! analyzer 0.31.2-alpha.1 from path ..\..\bin\cache\dart-sdk\lib\analyzer
! front_end 0.1.0-alpha.11 from path ..\..\bin\cache\dart-sdk\lib\front_end
! kernel 0.3.0-alpha.11 from path ..\..\bin\cache\dart-sdk\lib\kernel
Running "flutter packages get" in fuchsia_remote_debug_protocol...  1,3s
Downloading lcov data for package:flutter...                 1,2s

Ran 'pub' 29 times and fetched coverage data in 29.7s.

C:\AndroidProjects\chappy2\chappy>C:\flutter\flutter\bin\flutter.bat upgrade-packages
Could not find a command named "upgrade-packages".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

C:\AndroidProjects\chappy2\chappy>C:\flutter\flutter\bin\flutter.bat upgrade
Upgrading Flutter from C:\flutter\flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.3.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 44b7e7d3f4 (3 weeks ago) • 2018-04-20 01:02:44 -0700
Engine • revision 09d05a3891
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

Running "flutter packages upgrade" in chappy...             18,8s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.17134.48], locale nb-NO)
CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: f334c72beefbe55d)
CreateProcessW failed 193
Crash report written to C:\flutter\flutter\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.

C:\AndroidProjects\chappy2\chappy>C:\flutter\flutter\bin\flutter.bat flutter doctor -v
Could not find a command named "flutter".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

C:\AndroidProjects\chappy2\chappy>C:\flutter\flutter\bin\flutter.bat doctor -v
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.17134.48], locale nb-NO)
    • Flutter version 0.3.2 at C:\flutter\flutter
    • Framework revision 44b7e7d3f4 (3 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

-CreateProcessW failed 193
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: a83d4aad9b8a2f9b)
-CreateProcessW failed 193                                                                                                                                                C
rash report written to C:\AndroidProjects\chappy2\chappy\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

C:\AndroidProjects\chappy2\chappy>

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by zoechi** [comment]
Does your Windows user name contain a space?
Probably a dup of #18938

**Comment by rakhirocky365** [comment]
C:\Users\my lappy>flutter doctor
CreateProcessW failed 193

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{

**Comment by zoechi** [comment]
@rakhirocky365 responded in https://github.com/flutter/flutter/issues/15481#issuecomment-461763247
