### ISSUE TITLE
 Showing All Issues "x86_64" is not an allowed value for option "ios-arch".

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#17547]
When I try to run the app on the simulator from xcode I get this.

"x86_64" is not an allowed value for option "ios-arch".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
Failed to build /Users/long1eu/IdeaProjects/serve_you_app.
Command /bin/sh failed with exit code 255

Build failed    13/05/2018, 18:52

**Comment by sparksisnotspark** [comment]
I have got this error like you! and how you fix this?

**Comment by long1eu** [comment]
I've done some flutter clean and upgrade my flutter version and go to sleep. The other day it just worked. :D
