### ISSUE TITLE
A Tabbar problem

### ISSUE THREAD

**Issue by ikakaxi** [flutter/flutter#17557]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.3 17D47, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.

*********
I found a problem that dynamically refreshes the TabBar. If there is no data initially, then calling setState after the data of the TabBar is obtained will not refresh the data. If there are 2 initial data, after getting TabBar data (if there are 10), only the first 2 can be swiped and the following 8 can't slide.

********code:
```
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
        appBar: AppBar(
        title: Text("flush tabbar issue"),
        ),
        body: TabBarDemo()
    ),
  ));
}

class TabBarDemo extends StatefulWidget {
  @override
  TabBarDemoState createState() {
    return new TabBarDemoState();
  }
}

class TabBarDemoState extends State<TabBarDemo> with SingleTickerProviderStateMixin{

  List<String> textList = ["abc","def"];
  TabController tabController;

  @override
  void initState() {
    super.initState();
    tabController = TabController(vsync: this,length: textList.length);
    Timer(new Duration(seconds: 0), () {
      for(int i=0;i<20;i++){
        textList.add("num "+i.toString());
      }
      setState(() {
        print("ok");
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    final Widget tabBar = TabBar(
      controller: tabController,
      isScrollable: true,
      unselectedLabelColor: Colors.grey,
      labelColor: Theme
          .of(context)
          .primaryColor,
      indicatorColor: Theme
          .of(context)
          .primaryColor,
      indicatorWeight: 2.0,
      tabs: textList.map((String str) {
        return Tab(
          text: str,
        );
      }).toList(),
    );
    return tabBar;
  }

  @override
  void dispose() {
    tabController.dispose();
    super.dispose();
  }
}

```

**Comment by najeira** [comment]
Every time the number changes TabController needs to be renewed.

**Comment by zoechi** [comment]
Is this still an issue?
