### ISSUE TITLE
We should gracefully handle the Gradle wrapper ending up with mac (or Windows) line endings

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#17554]
I have run my flutter source codes on Windows, but when back to Linux (Ubuntu 18.04) it can not work. Error says:
```
Running "flutter packages get" in flutter_fairydiary...      6.8s
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                          -
Oops; flutter has exited unexpectedly: "Exit code 127 from: /media/jintian/sg/dev/d_flutter/products/flutter_fairydiary/android/gradlew -v:
/usr/bin/env: ‘bash\r’: No such file or directory".
 
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = clients2.google.com, port = 443
Crash report written to /media/jintian/sg/dev/d_flutter/products/flutter_fairydiary/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

```

Any suggestions?

**Comment by jinfagang** [comment]
Sorry, I found that I created flutter project under macOS, and the gradlew script like this:
```
#!/usr/bin/env bash

##############################################################################
##
##  Gradle start up script for UN*X
##
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

```
I think is nothing about Windows, how to edit this to work on Linux?

**Comment by PhillipMwaniki** [comment]
Hello, I'm having the same issue. I think this is a migration issue between machines. Did you get a fix to the problem ?

**Comment by jinfagang** [comment]
@PhillipMwaniki No, I am now not switch between machines.

**Comment by zoechi** [comment]
`android/gradlew` is gitignored in my project (check `android/.gitignore`. 
I'd assume it's safe to delete and it should be auto-generated for the current platform.

**Comment by jinfagang** [comment]
@zoechi how to make gradle file generate right both on windows and other unix system?

**Comment by Hixie** [comment]
```
Oops; flutter has exited unexpectedly: "Exit code 127 from: /media/jintian/sg/dev/d_flutter/products/flutter_fairydiary/android/gradlew -v:
/usr/bin/env: ‘bash\r’: No such file or directory".
```
...means that somehow the gradlew file ended up with mac line endings.
We should detect this and report it or handle it.

**Comment by zoechi** [comment]
I think this is a general problem if people copy a project between machines (no matter the OS) using file/directory copy commands.

When moving a project to another machine all `.gitignored` files should be deleted. 
So if this is required then make the project a Git repo and commit all files and then `git clone` from that directory and you have a properly working copy.

**Comment by jonahwilliams** [comment]
These files are all correctly gitignored in the flutter project templates, and we don't expect this to work for a number of different file types. Detecting all of the potential differences is far out of scope of what we can or should do in the tool

**Comment by robinjohn** [comment]
For anyone else still struggling to find answers to this bug, 
Try the below and that should fix it:  

1. Clean build
``` 
flutter clean
```
2. Make the gradlew bin runnable in unix.
```
vim gradlew
:set fileformat=unix
:wq
```
3. Fix the flutter pub packages cache built from earlier session in windows
```
flutter pub cache repair
```

**Comment by mudi256** [comment]
just remove gredlew from the android directory and issue resolved. 
happy coding
