### ISSUE TITLE
Firebase Auth emails with '.al' suffix dont work

### ISSUE THREAD

**Issue by kondasoft** [flutter/flutter#17569]
On iOS if you try this method (im not sure for other create methods)

`FirebaseAuth.instance.linkWithEmailAndPassword()`
with an email something like
`test@test.al` 
it doesn't work on iOS. it seems that the suffix '.al' cant be seems valid. it works fine on android.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by kroikie** [comment]
@kondasoft

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/826. Any further collaboration will be done there.
