### ISSUE TITLE
flutter packages get not working

### ISSUE THREAD

**Issue by harriscreativity** [flutter/flutter#17565]
it aint downloading the package and it giving off red package error import 'package:firebase_database/firebase_database.dart';
it saying error: Target of URI doesn't exist: 'package:firebase_auth/firebase_auth.dart'.

**Comment by zoechi** [comment]
Please post the whole output of `flutter packages get`

**Comment by harriscreativity** [comment]
![screen shot 2018-05-14 at 13 30 59](https://user-images.githubusercontent.com/20087512/39994951-1ec56aea-577b-11e8-9111-7978d7fed5f0.png)

**Comment by zoechi** [comment]
Please post the whole output of flutter packages get

**Comment by harriscreativity** [comment]
![screen shot 2018-05-14 at 15 04 15](https://user-images.githubusercontent.com/20087512/40000964-7892f9ae-578d-11e8-88bd-b523d8504d78.png)
the log is printing normal indicator but it aint download while it was working fine couple hours before

**Comment by harriscreativity** [comment]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET firebase_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.h:5:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:37:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:80:42: warning: 'UIUserNotificationSettings' is only available on iOS 8.0 or newer [-Wunguarded-availability]
        didRegisterUserNotificationSettings:(UIUserNotificationSettings*)notificationSettings;
                                             ^
    In module 'UIKit' imported from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Target Support Files/firebase_auth/firebase_auth-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:43:12: note: 'UIUserNotificationSettings' has been explicitly marked partial here
    @interface UIUserNotificationSettings : NSObject
               ^
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.h:5:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:37:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:79:1: note: annotate 'application:didRegisterUserNotificationSettings:' with an availability attribute to silence this warning
    - (void)application:(UIApplication*)application
    ^
    /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:95:44: warning: 'UIBackgroundFetchResult' is only available on iOS 7.0 or newer [-Wunguarded-availability]
              fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler;
                                               ^
    In module 'UIKit' imported from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Target Support Files/firebase_auth/firebase_auth-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:76:29: note: 'UIBackgroundFetchResult' has been explicitly marked partial here
    typedef NS_ENUM(NSUInteger, UIBackgroundFetchResult) {
                                ^
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.h:5:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/Flutter.h:37:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/FlutterAppDelegate.h:11:
    /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/Flutter/Flutter/FlutterPlugin.h:93:1: note: annotate 'application:didReceiveRemoteNotification:fetchCompletionHandler:' with an availability attribute to silence this warning
    - (BOOL)application:(UIApplication*)application
    ^
    /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:70:41: error: incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)')
            signInAnonymouslyWithCompletion:^(FIRAuthDataResult *dataResult, NSError *error) {
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Private/Firebase/Firebase.h:13:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FirebaseAuth.h:4:
    /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FIRAuth.h:493:73: note: passing argument to parameter 'completion' here
    - (void)signInAnonymouslyWithCompletion:(nullable FIRAuthResultCallback)completion;
                                                                            ^
    /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:103:41: error: incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)')
                                 completion:^(FIRAuthDataResult *dataResult, NSError *error) {
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Private/Firebase/Firebase.h:13:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FirebaseAuth.h:4:
    /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FIRAuth.h:590:61: note: passing argument to parameter 'completion' here
                     completion:(nullable FIRAuthResultCallback)completion;
                                                                ^
    /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:131:37: error: incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)')
                             completion:^(FIRAuthDataResult *dataResult, NSError *error) {
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Private/Firebase/Firebase.h:13:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FirebaseAuth.h:4:
    /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FIRAuth.h:372:57: note: passing argument to parameter 'completion' here
                 completion:(nullable FIRAuthResultCallback)completion;
                                                            ^
    /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:188:43: error: incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)')
                                   completion:^(FIRAuthDataResult *dataResult, NSError *error) {
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.m:5:
    In file included from /Users/mobileappsdev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/ios/Classes/FirebaseAuthPlugin.h:7:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Private/Firebase/Firebase.h:13:
    In file included from /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FirebaseAuth.h:4:
    /Users/mobileappsdev/AndroidStudioProjects/musicplayer/apps/ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FIRAuth.h:537:63: note: passing argument to parameter 'completion' here
                       completion:(nullable FIRAuthResultCallback)completion;
                                                                  ^
    2 warnings and 4 errors generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by zoechi** [comment]
There is no point in building if there are invalid imports.
Please add the output of `flutter doctor`

**Comment by harriscreativity** [comment]
firebase_auth: "^0.4.6" is working well without any problem

Last login: Mon May 14 15:49:50 on ttys002
Dotcoms-MacBook-Air:~ mobileappsdev$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (2 available)

• No issues found!
Dotcoms-MacBook-Air:~ mobileappsdev$

**Comment by harriscreativity** [comment]
[Archive.zip](https://github.com/flutter/flutter/files/2003879/Archive.zip)

**Comment by harriscreativity** [comment]
Running "flutter packages get" in govnews...
tar: Failed to set default locale
tar: Failed to set default locale
Process finished with exit code 0

**Comment by zoechi** [comment]
That's a different output than in your first 2 comments. Any idea why that is?
https://stackoverflow.com/questions/3907719/how-to-fix-tar-failed-to-set-default-locale-error might help

**Comment by zoechi** [comment]
I believe one of the suggestions should fix the issue

https://github.com/flutter/flutter/issues/18340#issuecomment-396457808
https://github.com/flutter/flutter/issues/17457#issuecomment-405117816
https://github.com/flutter/flutter/issues/17469#issuecomment-391976660
https://github.com/flutter/flutter/issues/17721#issuecomment-390259983

**Comment by maccine** [comment]
:(

**Comment by zoechi** [comment]
@maccine  should this comment fulfill any purpose?

**Comment by maccine** [comment]
omg 

```
pod repo update
sudo gem install cocoapods
rm -rf ~/Library/Caches/CocoaPods
rm -rf ios/Pods
pod update
flutter clean
pod repo update
flutter packages upgrade
```

MADE IT WORK!!!!!......... on my end

took me 34876481  hourssss

@zoechi thanks, it did

**Comment by eturk1** [comment]
yes, I know this is closed but...

having the same problem recently in Android Studio where packages get DOES get the package, it can be seen in pubspec.lock BUT Studio doesn't know about the package. Closing & reopening Studio magically then shows the import is valid.

**Comment by zoechi** [comment]
@eturk1 I have experienced this myself occassionally.

**Comment by Hmaal** [comment]
I have just experienced this as well. Reopening VS Code seems to have resolved it.

**Comment by Hongwing** [comment]
I solved this by change the network. 「maybe the network's problem」
**then**:
![shot](https://ws3.sinaimg.cn/large/006tNbRwly1fw9t0w1gx4j30y40cmjs7.jpg)

**Comment by pranavkarnik** [comment]
> yes, I know this is closed but...
> 
> having the same problem recently in Android Studio where packages get DOES get the package, it can be seen in pubspec.lock BUT Studio doesn't know about the package. Closing & reopening Studio magically then shows the import is valid.
> 
> (On Windows 10)

Finally I got some solution. Closing the project and reopening it resolved the package.

**Comment by johnvarg** [comment]
> omg
> 
> ```
> pod repo update
> sudo gem install cocoapods
> rm -rf ~/Library/Caches/CocoaPods
> rm -rf ios/Pods
> pod update
> flutter clean
> pod repo update
> flutter packages upgrade
> ```
> MADE IT WORK!!!!!......... on my end
> 
> took me 34876481 hourssss
> 
> @zoechi thanks, it did

Been struggling with "[dart] Target of URI doesn't exist: 'package:flutter/http.dart'. [uri_does_not_exist]" issue since past 48 hours ... 
None of the suggestions worked... 
1) Added  dependencies in pubspec.yaml
  http: 0.12.0+1
2) Ran flutter packages get
3) Restarted Visual Studio 
4 Tried following too 
> pod repo update
> sudo gem install cocoapods
> rm -rf ~/Library/Caches/CocoaPods
> rm -rf ios/Pods
> pod update
> flutter clean
> pod repo update
> flutter packages upgrade

None of the above solved it .... PLEASE HELP!!!

**Comment by lifenduwi** [comment]
Restarting the IDE fixed the issue for me!

**Comment by wangkang0833** [comment]
I must restart my computer. so sad

**Comment by patelkrunal78** [comment]
It is clear way to add http to flutter

Add this to your package's pubspec.yaml file:
dependencies:
  http: ^0.12.0 // latest one might change
Install it You can install packages from the command line:
with pub:

$ pub get

with Flutter:

$ flutter packages get

Import it Now in your Dart code, you can use:
import 'package:http/http.dart';

Find Your Solution At [Here](https://icetutor.com/question/flutter-http-package-does-not-exist)

**Comment by coldapache** [comment]
Running into the same issue.

The pubspec.yaml file has all the dependencies listed appropriately, and the pubspec.lock file has them listed as well, but the packages never actually install in the flutter packages section.

The imports show up as "problems", and nothing from those packages works. It's like flutter packages get installs the package but puts it nowhere.

**Comment by staticeye** [comment]
> Restarting the IDE fixed the issue for me!
I Don't know the reason, but this worked for me :D

**Comment by jaitjacob** [comment]
I had a similar issue with the command but I am not sure if it should be opened as a new issue. 

I ran the following and as you can see I got no "`exit code 0`" and the prompt was back again without any verbose on how the downloading of the package went.
```
C:\Users\jaitj\Documents\Summer 2019\flutter\myapp>flutter pub get
Running "flutter pub get" in myapp...                              0.5s
```

What I tried then, was to delete the pubspec.lock file and run the command again but this time the import was underlined in blue saying "imports not used" instead of the "imports not found".

Screenshot.
![image](https://user-images.githubusercontent.com/14340591/69226065-a6a41e80-0bd3-11ea-825e-cf58d66fb8f9.png)

**Comment by Lppapineau** [comment]
Hi all, I had the same problem and the solution for me was only to type inside the flutter terminal this command: flutter clean.
Bye

**Comment by ther12k** [comment]
I having same problem, but when I change :

```
dependencies:
  image_gallery: ^1.2.0
  flutter:
    sdk: flutter
```

instead of 

```
dependencies:
  flutter:
    sdk: flutter
  image_gallery: ^1.2.0
```

it's working now

**Comment by pcgeek86** [comment]
1. Delete `pubspec.lock`
2. Run `flutter pub get`

^^^ worked for me

**Comment by benCaoili** [comment]
try run pud get one by one if nothing issue 
  
 cached_network_image: ^2.0.0
  cloud_firestore: ^0.13.3
  firebase_auth: ^0.15.2
  firebase_database: ^3.0.7
  provider: ^3.2.0
  shared_preferences: ^0.5.6+3


thanks ben

**Comment by Tanzil7274** [comment]
The same thing is happening to me.First the problem was isolated to one package, but now it just randomly appears for many of the packages

**Comment by scorchy38** [comment]
Why @zoechi is rude to everyone?

**Comment by erperejildo** [comment]
tried everything proposed here but didn't work. The packages installation gets stuck every time

**Comment by Isuru01** [comment]
I tried everything in the comment section. Anyone has a new solution.
