### ISSUE TITLE
Rename 'full restart' to 'hot restart' in flutter_tools

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#17568]
IntelliJ action was renamed in https://github.com/flutter/flutter-intellij/pull/2225

We should get `flutter_tools` updated: https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=%22full+restart%22+&type=

**Comment by devoncarew** [comment]
All user facing changes landed here: https://github.com/flutter/flutter/pull/17408.

**Comment by devoncarew** [comment]
1) That flag is unfortunately named - it's not related to hot restarts.
2) It looks like it's orphaned, and not ever queried by code.
