### ISSUE TITLE
No image asset location found 

### ISSUE THREAD

**Issue by AbhijitL** [flutter/flutter#17561]
I got an error saying no image location found 
here is the screenshot
https://ibb.co/eqwi1J
## Logs

     [  +88 ms] [C:\flutter_windows_v0.3.2-beta\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +125 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] [C:\flutter_windows_v0.3.2-beta\flutter\] git rev-parse --abbrev-ref HEAD
[  +69 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [C:\flutter_windows_v0.3.2-beta\flutter\] git ls-remote --get-url origin
[  +81 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\flutter_windows_v0.3.2-beta\flutter\] git log -n 1 --pretty=format:%H
[ +129 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 44b7e7d3f42f050a79712daab253af06e9daf530
[        ] [C:\flutter_windows_v0.3.2-beta\flutter\] git log -n 1 --pretty=format:%ar
[  +67 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[        ] [C:\flutter_windows_v0.3.2-beta\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +85 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.3.2-0-g44b7e7d3f
[ +743 ms] C:\Users\My\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +41 ms] Exit code 0 from: C:\Users\My\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
[  +13 ms] No connected devices.
[  +74 ms] "flutter run" took 681ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:256)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:312)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:224)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#31     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

    Running "flutter packages get" in flutter_login...
Error on line 29, column 4 of pubspec.yaml: Expected a key while parsing a block mapping.
   assets:
   ^
pub get failed (65)

 flutter doctor -v

 [√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 0.3.2 at C:\flutter_windows_v0.3.2-beta\flutter
    • Framework revision 44b7e7d3f4 (3 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\My\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700

[√] VS Code, 64-bit edition (version 1.23.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
There is a space to many before ` assets:`.
It doesn't align with `uses-material-design:`

**Comment by AbhijitL** [comment]
thanks, it works

**Comment by AbhijitL** [comment]
@zoechi    It doesn't work for the image it works only for the font
here is the screenshot:-
![errpr](https://user-images.githubusercontent.com/28972945/39985073-e719af3e-577a-11e8-810f-c5094129c2dd.JPG)

**Comment by zoechi** [comment]
Please try `flutter clean` and then run again.

**Comment by AbhijitL** [comment]
@zoechi     Nope I get the error again  
I got 1 warning 
![errpr](https://user-images.githubusercontent.com/28972945/39987958-c2ba3d3a-5783-11e8-8aae-94559dccd00e.JPG)

**Comment by zoechi** [comment]
The indentation is wrong. In YAML spaces are significant.
I'd suggest you create a new project using `flutter create` and look up the indentation there (or check https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/pubspec.yaml)

**Comment by lakziro** [comment]
stop your debugging. don't do hot reload. be course of that case could not recognize new repository.
cancel debug and do debug again.
