### ISSUE TITLE
Relative and absolute imports don't resolve to the same path

### ISSUE THREAD

**Issue by RyanAfrish7** [flutter/flutter#17575]
I was trying to accomplish something similar to `Scaffold.of(context)`, where the closest `ScaffoldState` ancestor is obtained using the method `ancestorStateOfType`.

[Source code from StackOverflow](https://stackoverflow.com/questions/47121411/flutter-retrieving-top-level-state-from-child-returns-null) for demonstrating this error,

```
class IApp extends StatefulWidget {    
  @override
  IAppState createState() => new IAppState();

  static IAppState of(BuildContext context) =>
    context.ancestorStateOfType(const TypeMatcher<IAppState>());
}
```
```
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      // ommitted: some localization and theming details
      home: new HomePage(),
    );
  }
```
```
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      // ommited: some Scaffold properties such as AppBar
      // runtimeType not actual goal, but just for demonstration purposes
      body: new Text(IApp.of(context).runtimeType.toString()),
    );
  }
```

Here IApp.of() returns null. 

The StackOverflow answer explains this is particularly because of Dart's addressing policy. Opposing to the answer in my case, the absolute addressed and relative addressed class are treated alike but somehow different from the one within the widget tree. After I spent an hour debugging, I obtained the runtimeType of the state in the widgettree as IAppState but it's comparing to inequal.

**Comment by RyanAfrish7** [comment]
This error message may add clarity to what I'm trying to explain.

```
I/flutter (12520): type 'IAppState' is not a subtype of type 'IAppState' where
I/flutter (12520):   IAppState is from file:///.../istore/lib/main.dart
I/flutter (12520):   IApp is from file:///.../istore/lib/main.dart
I/flutter (12520):   IAppState is from package:istore/main.dart
I/flutter (12520):   IApp is from package:istore/main.dart

```

**Comment by jonahwilliams** [comment]
This is unfortunately surprising behavior but currently working as expected. For more context see https://github.com/dart-lang/sdk/issues/32601.

**Comment by zoechi** [comment]
Just ensure all imports paths in `lib/main.dart` start with `'dart:...'` or `'package:...'`

**Comment by RyanAfrish7** [comment]
I made sure all imports are made with `'package:..'`. Once I did that, call to `context.ancestorStateOfType` returns `null`.

Then I added a small routine which forcefully visits every ancestor to find the one with same type name (using the comparision `element.state.runtimeType.toString()=="IAppState"`) and attempted to store it in `IAppState` (declared within the same file), now I get an error:

```
I/flutter (12520): type 'IAppState' is not a subtype of type 'IAppState' where
I/flutter (12520):   IAppState is from file:///.../istore/lib/main.dart
I/flutter (12520):   IApp is from file:///.../istore/lib/main.dart
I/flutter (12520):   IAppState is from package:istore/main.dart
I/flutter (12520):   IApp is from package:istore/main.dart

```

**Comment by zoechi** [comment]
```
I/flutter (12520):   IApp is from file:///.../istore/lib/main.dart
I/flutter (12520):   IApp is from package:istore/main.dart
```
Still 2 different paths to the same file. 
Do you import `lib/main.dart` anywhere?

**Comment by zoechi** [comment]
It's hard to tell with the available information, but from above output I think there is something fishy with your file structure or imports. Perhaps you can make the code available in a public GitHub project?

**Comment by RyanAfrish7** [comment]
I wrote a workaround.
```
// main.dart
import 'package:istore/main.dart' as main2;

// changed all uses of IApp to main2.IApp. This fixed the issue.
```
I will write a minimal app to demonstrate this error as soon as I find some free time. I am worried about why Dart distinguishes between different addressing schemes and wasting a day for every Dart developer.

**Comment by zoechi** [comment]
> Nope, I have no such import within the project.

> import 'package:istore/main.dart' as main2;

I'd say importing `main.dart` is a very bad idea. Just move the code to another file and import the code from there.

**Comment by Hixie** [comment]
This is a Dart issue.

**Comment by Hixie** [comment]
cc @leafpetersen

**Comment by Hixie** [comment]
@leafpetersen we have heard of this from multiple people.

**Comment by Hixie** [comment]
I've filed this on the Dart team, I'm going to close this bug on our side.
