### ISSUE TITLE
Get current context

### ISSUE THREAD

**Issue by dankop123** [flutter/flutter#17571]
Hi,
I'm using flutter_local_notifications plugin to schedule local notifications. When notification is received I want to open the app (if it's killed or in the background) and navigate to a specific view. The problem is that i don't know which build context to pass to a navigator in order this to work. Is there a way to get app current context or somehow navigate app just after it launches?

**Comment by zoechi** [comment]
Just override `didChangeDependencies` and check there if you need to navigate. Context is available in this method.

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by 1343** [comment]
how to get context here any idea?

 Future<void> onSelectNotification(String payload) async {
    print("Notification selected");
    toastMessage("Notification selected", currentContext);
    Navigator.of(currentContext).pushNamed(notifiScreen);
   /* Navigator.push(
      currentContext,
      MaterialPageRoute(
          builder: (context) => NotificationDeeplinking(payload, true)),
    );*/
  }
this code is not working

**Comment by Vinoth1094** [comment]
I'm also facing the exact same issue where I need to push to a new Page using Navigator which requires 'context' of current page.
I've initialised notification plugin in a common launch page whose context cannot be used at the time Notification is received. Also I don't want to track the current context in a variable as storing context in a static variable is costly.
I'm not really sure how to use the 'didChangeDependencies' in a utility class as 'didChangeDependencies' is available only inside a 'Stateful Widget'.
Please help me out to solve this.

**Comment by kevinengel** [comment]
You can navigate without the current context by using this method: https://github.com/brianegan/flutter_redux/issues/5#issuecomment-361215074
