### ISSUE TITLE
Add debugPaint property to all widgets

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#17576]
Enabling debug point for a running App is a great help but if you have a heavily nested UI you cannot interpret it anymore.

Therefore I would propose to add a `debugOutLineColor` and `debugFillColor` that will draw the outline and/or it's region if another color that transparent is set.

**Comment by Hixie** [comment]
Many render objects exactly overlap, so I'm not sure that would really be feasible. We'd have to change the layout as well, which wouldn't really work.

The real solution to this is the Widget Inspector. cc @jacob314

**Comment by escamoteur** [comment]
While building the UI with Hot Reload it would be often helpful to be able to highlight certain Widgets. Another solution could be to set a flag in the widgets that paints them differently and on top when DebugPaint is switched on.
If you have a lot of widgets it's often not easy to discern them from each other with DebugPaint.

**Comment by jacob314** [comment]
This is absolutely a problem we want to solve in the widget inspector. As soon as I find time to do the required refactoring, the widget inspector will display the debug paint for the selected widget.

**Comment by escamoteur** [comment]
yeah, but it would also be great if we could trigger that from code if there is any chance

**Comment by Hixie** [comment]
@escamoteur to get the effect Jacob is describing, just wrap your Widget in a decorated box.

**Comment by escamoteur** [comment]
Hmm, just thinking if that always is possible. I guess to make this really useful it would be necessary to see the outline of the widget highlighted even if it is covered by some other widget. 
Also always to wrap/unwrap widgets is way less comfortable than having this as a property.

**Comment by Hixie** [comment]
debugPaint can't paint over other widgets either. can you explain the problem you're actually trying to solve? maybe there's a better solution.

**Comment by escamoteur** [comment]
ah ok, I thought that would be possible somehow. I don't want to make things more difficult. I haven't a specific problem currently, just while working with Flutter I felt this would be a help while layouting my page. I hope that widget inspector will be available for VS code soon too.

I was expecting that this would be a nobrainer, so we can also close that issue if it makes more trouble than it adds worth.
There are aother more pressing issues I guess

**Comment by Hixie** [comment]
I'm going to close this because we've working on devtools features that show the actual layout, which is a much more tractable way of approaching this (see e.g. the flex layout inspector).
