### ISSUE TITLE
Loading the weather demo is super janky in release mode

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1757]

**Comment by jimbeveridge** [comment]
FWIW, the Dart team is looking at performance issues during VM startup that we identified.

**Comment by Hixie** [comment]
this is even with a warm VM

**Comment by sethladd** [comment]
Is this a dupe of https://github.com/flutter/flutter/issues/3082 ?

**Comment by Hixie** [comment]
Obsolete, we've removed flutter_sprites for now.
