### ISSUE TITLE
iOS 'archive' fails

### ISSUE THREAD

**Issue by kondasoft** [flutter/flutter#17570]
Everything runs fine on iOS simulator but when i try to "archive" the build as described the iOS release page on Flutter docs, i get the following error. I have everything latest version including pods. Any ideas?

```
clang: error: no such file or directory: '/Users/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.5/ios/Classes/FirebaseAuthPlugin.m'
clang: error: no input files
```

**Comment by kondasoft** [comment]
Not sure how but this error was solved. I suppose closing the project in xcode and opening it again fixed it

**Comment by cbracken** [comment]
@alexlovar Flutter uses Dart's `pub` package manager under the hood to fetch packages from pub.dartland.org and cache them locally in `~/.pub-cache`. I wonder if it's possible that somehow the package download failed mid-way or was corrupted.

From the terminal can you try the following and see if that resolves your issue?
```shell
rm -rf /Users/alexander/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.20
```

One surprising thing here is the location of your `.pub-cache` directory. Typically it's in your home directory. It looks like you're on macOS, so I'd have expected it to be at `/Users/alexander/.pub-cache`, not `/Users/alexander/flutter/.pub-cache` -- unless somehow `$HOME` is set to `/Users/alexander/flutter`, which would be unexpected. You can check via `echo $HOME`.

**Comment by zoechi** [comment]
@alexlovar The output of `flutter doctor -v` might be helpful.
