### ISSUE TITLE
To view this content, install and set up a web browsing app.

### ISSUE THREAD

**Issue by 1priyank1** [flutter/flutter#17596]
When I launching app on my mobile device first time, It's show screen as below.

![screenshot_20180515-090811](https://user-images.githubusercontent.com/6890651/40035830-523b45a6-5821-11e8-9e37-3eb87ced0951.png)

After then, When I press back button, then it will show app screen.

Console details:
```

Launching lib\main.dart on Moto G 4 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk (30.4MB).
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(16161): onResume setting current activity to this
Syncing files to device Moto G 4...

```

**Comment by 1priyank1** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.1, on Microsoft Windows [Version 6.2.9200], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.0)
[√] Android Studio (version 2.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
Is this a debug run from the IDE?

**Comment by 1priyank1** [comment]
Problem Fixed. It was not flutter related problem.

It's due to no default browser was selected in the phone.

To resolve this issue, Install (if not installed) and select Chrome as your default web browser using below steps.
1. On your Android, open Settings.
2. Tap Apps & notifications.
3. At the bottom, tap Advanced.
4. Tap Default apps.
5. Tap Browser App and then Chrome.

**Comment by lekeCoder** [comment]
@1priyank1  I am afraid your solution did not work for me. I had Chrome as default browser app and still got the same error message

**Comment by vivchar** [comment]
I have the same problem. Not sure that it is Flutter problem
Xiaomi Redmi 4X

It happens when I try to open this page:
https://play.google.com/redeem


```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.5 18F132, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
```
