### ISSUE TITLE
Input Widgets Bugs

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#176]
<a href="https://github.com/afandria"><img src="https://avatars.githubusercontent.com/u/2432033?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [afandria](https://github.com/afandria)**
_Tuesday Sep 29, 2015 at 02:26 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1387_

----

- [x] When there is an `initialValue`, Backspace doesn't do anything until you type other characters.
- [x] When there are multiple Inputs, all of them are considered active at the same time. There's probably an internal error, since after the first letter is typed, the inputs all stop responding. (Interestingly, Android must keep an internal buffer of what's being typed since its autocomplete carries on without concern.)
- [x] I cannot choose to get or lose focus.
- [x] Keyboard's Enter/Return doesn't look like it does anything, and Input doesn't have an optional parameter callback for the Enter/Return case.

(As mentioned in other issues, it would also be nice to manipulate the cursor position and selection. #151 and #152)

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Sep 29, 2015 at 23:34 GMT_

----

/cc @jason-simmons

**Comment by FlutterIssues** [comment]
<a href="https://github.com/afandria"><img src="https://avatars.githubusercontent.com/u/2432033?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [afandria](https://github.com/afandria)**
_Friday Oct 02, 2015 at 20:48 GMT_

----

I've found some more bugs

* I can't type any digits when using the standard `KeyboardType.TEXT`.
* When Android autocomplete spits out a word, if you press backspace repeatedly then the Input's internal text buffer seems to get confused. (This works when there is an `initialValue`)

For the latter one, the example is the placeholder `1106332964`. I typed some random characters. And then swiped a lot on my keyboard (which completed to the word `judiciously`). After that, I tapped backspace, which after a few times ended up messing up the Input.

```
I/sky     (12189): Updating color with 1106332964h
I/sky     (12189): Updating color with 1106332964hj
I/sky     (12189): Updating color with 1106332964hjj
I/sky     (12189): Updating color with 1106332964hjjj
I/sky     (12189): Updating color with 1106332964hjjjh
I/sky     (12189): Updating color with 1106332964hjjjhg
I/sky     (12189): Updating color with 1106332964hjjjhgj
I/sky     (12189): Updating color with 1106332964hjjjhgjb
I/sky     (12189): Updating color with 1106332964hjjjhgjbg
I/sky     (12189): Updating color with 1106332964hjjjhgjbg 
I/sky     (12189): Updating color with 1106332964hjjjhgjbg judiciously
I/sky     (12189): Updating color with 1106332964hjjjhgjbg 
I/sky     (12189): Updating color with 1106332964hjjjhgjbg
I/sky     (12189): Updating color with hjjjhgjb4hjjjhgjbg
```

**Comment by abarth** [comment]
>  I cannot choose to get or lose focus.

The Input widget has an `autofocus` argument now that you can use to grab focus if no one else has it.  To get focus, you can call `Focus.moveTo` with the key you want to focus.

Losing focus is #1308

**Comment by abarth** [comment]
`Focus.clear` now exists.

**Comment by abarth** [comment]
> Keyboard's Enter/Return doesn't look like it does anything, and Input doesn't have an optional parameter callback for the Enter/Return case.

We now call the `onSubmitted` callback for `Input` when the user taps Enter/Return.

I think I've fixed all the issues in this bug.  Please let me know if you're still having trouble.
