### ISSUE TITLE
Implement on click event for all widget

### ISSUE THREAD

**Issue by jayesh28589** [flutter/flutter#17602]
Hello,

I am android developer and learning developing application in flutter.
I want to make on click listener for all the widget, Can you develop this feature in Flutter sdk ?

In android we can set on click listener for any view, but in Flutter right now only button widget have supported method onPress().

Thanks.

**Comment by zoechi** [comment]
You can use GestureDetector or InkWell

**Comment by jayesh28589** [comment]
Can you please post the code here how can I set onTap method for Icon or Text ?

**Comment by xster** [comment]
See sample code in https://docs.flutter.io/flutter/widgets/GestureDetector-class.html. 

Flutter uses the composition pattern instead of letting each widget have all types of features by inheritance. 

The GestureDetector's `child` can be anything.
