### ISSUE TITLE
Issue from website page Get Started: Install on Windows

### ISSUE THREAD

**Issue by JoeCodeswell** [flutter/flutter#17607]
From URL: https://flutter.io/setup-windows/
There seems to be NO WAY to develop for iOS on my Windows machine. Am I right?
Is there anything Google/Flutter can do?
This seems to me to be an unfair advantage for Apple.
Thanks.
Love and peace,
Joe Dorocak

**Comment by development-s365** [comment]
You need xcode to run your flutter app on a iOS device.
To install xcode you will need a mac.

**Comment by zoechi** [comment]
@development-s365 is correct.
See also this comment https://github.com/flutter/flutter/issues/17471#issuecomment-388171536
