### ISSUE TITLE
There seems to be a typographic issue on Flutter with rtl languages.

### ISSUE THREAD

**Issue by opengemara** [flutter/flutter#17601]
## Steps to Reproduce

      @override
      Widget build(BuildContext context) {
        // This method is rerun every time setState is called, for instance as done
        // by the _incrementCounter method above.
        //
        // The Flutter framework has been optimized to make rerunning build methods
        // fast, so that you can just rebuild anything that needs updating rather
        // than having to individually change instances of widgets.
       return new Scaffold(
        appBar: new AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: new Text(widget.title),
        ),
        body: new Container(
            margin: EdgeInsets.all(32.0),
            child: ListView(children: [         
                new Row(children: [
                  Expanded(
                      child: RichText(
                          textDirection: TextDirection.rtl,
                          text: TextSpan(children: [
                            TextSpan(
                                text:
                                    "جعل عن أهّل بالعمل مقاومة, ماذا معارضة هو دنو. بها ان لإعلان بتحدّي الإتحاد, ويعزى وسمّيت تم بحق, ثم جعل غينيا وإيطالي. قد بخطوط سبتمبر ذات, مدينة الأمور الخاسرة من جهة. نفس ومضى ألمّ الفرنسية أن, بها لم فهرست الصين ويكيبيديا،, به، زهاء الصفحة التنازلي كل. يكن ثم ومضى الضغوط بالولايات, وأزيز الشهير أم مدن, لم تح ت قا مت ف كان ت  ال ثا ل ث   .",
                                style: TextStyle(color: Colors.black)),
                            TextSpan(
                                text:
                                    "\n\n לוח מדריכים אווירונאוטיקה גם, גם סדר הבהרה ברוכים הגרפים. שמו אם שונה עמוד. לתרום מבוקשים האנציקלופדיה לוח ב. לוח על אקראי ברוכים, ויש מאמר חינוך ספינות גם.\n",
                                style: TextStyle(color: Colors.black)),
                            TextSpan(
                                text:
                                    "ლორემ იფსუმ დოლორ სით ამეთ, მელ ვოცენთ ფრინციფეს ნე, ვისი იმფედით ეხ ეოს. ნეც ათ უთინამ ბონორუმ ლეგენდოს, ყუოთ ინთელლეგებათ ეუ ფრო. ცუ თიმეამ დეთერრუისსეთ ფრი, ყუი ეი სუმო იფსუმ ვირის. ეუ უსუ ჰაბეო ელაბორარეთ, თე ნამ ცაუსაე ვოლუთფათ. ფრი ეა სინთ სადიფსცინგ.",
                             style: TextStyle(color: Colors.black)),
                            TextSpan(
                                text:
                                    "\n脱ノ対育スンあね負例りね載写ぎやりけ一義え表収ろでに生47枠ヨモマ館校セ勢問ヒニネ立団ほう著2円ッけづ毎七ふとリル禁食げ案循レヘウ者稿ヱヘクラ言紙ミ質策送ち。9文ちぼ容観フ現波86育ソ理5英教すフゆ東生サカヲ掲人問ぽを通牟院ぐ務必ッ執経ち出傍剰ぶろ。補ヌ森仏お民提社載ク望世ラレカ朝満ひぼて軟落案除シフウワ海連ぼ影理毒ヤ両椅漁スう。\n",
                                style: TextStyle(color: Colors.black)),
                            TextSpan(
                                text:
                                    "Brét kommen meescht oft no, Kënnt geplot de oft. Vu d'Sonn ménger Völkerbond bei. Et dir Welt Mier, un wat d'Sonn d'Kàchen. Koum Noper virun no rei, vill d'Hierz gesiess jo hun. Jéngt klinzecht d'Margréitchen mä net, op Engel d'Pan blo, dén ze Feld deser blénken.",
                                style: TextStyle(color: Colors.black)),
                            TextSpan(
                                text:
                                    "asd",
                                style: TextStyle(color: Colors.black))
                          ], style: TextStyle(fontSize: 19.2))))
                ])
              ])
            ));
  

(text obtained from a [lorum ipsum generator](http://generator.lorem-ipsum.info/), I don't understand some of these languages and I hope there's nothing offensive in them).

## Logs

The result looks like this:
https://imgur.com/BrIyxxA

If you'll notice, the Hebrew (and Arabic) letters on the left look cut off, while the Georgian, Japanese, and letzeburgisch isn't). Note, Removing "padding" doesn't help, it just  looks clearer with padding than without.
```
```

[✓] Flutter (Channel dev, v0.4.2, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.2 at /home/user/flutterLocation
    • Framework revision de332ec782
    • Engine revision e976be13c5
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

```
```

**Comment by HansMuller** [comment]
This may be a symptom of: https://github.com/flutter/flutter/issues/16408 although I'm not familiar enough with Hebrew and Arabic scripts to really see the clipping you're referring to. Did you mean to refer to the letters on the right side of the page?

@amirh - could you take a look at this?

**Comment by opengemara** [comment]
> Did you mean to refer to the letters on the right side of the page?

Yes.

**Comment by HansMuller** [comment]
@amirh highlighted the clipping of the Hebrew text; this will help us determine if #16408 fixes the problem.

![image](https://user-images.githubusercontent.com/1377460/40068517-b1dc5a94-581d-11e8-9665-6503ce3bf015.png)

**Comment by jason-simmons** [comment]
This should already be fixed on the master branch

**Comment by opengemara** [comment]
So flutter upgrade should do the trick?

**Comment by jason-simmons** [comment]
Use the `flutter channel` command to switch to the `master` channel

See https://flutter.io/upgrading/

**Comment by opengemara** [comment]
Yup, that fixes it. Thanks!
