### ISSUE TITLE
i have problem while installing flutter ,,it said that flutter command was unsuccessful

### ISSUE THREAD

**Issue by mehul235** [flutter/flutter#17600]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by zoechi** [comment]
Please provide more details. 
What steps did you take?
What step caused the error?
Please add the full and **exact** error message.
What OS and what version do you use?

**Comment by zoechi** [comment]
This issue is not actionable with the provided informations.
Feel free to create a new issue if you think there needs something to be done.
