### ISSUE TITLE
Selection handle touch target is too small in TextFields.

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#17618]
The Flutter editable text widget (`TextField`) displays a selection handle; however, the touch target is too small. 

This is an accessibility issue, so I'm marking it as blocking for mulligan.

**Comment by Hixie** [comment]
cc @jonahwilliams

**Comment by tvolkert** [comment]
@goderbauer I hear this issue amounts to a disagreement between the Material spec and the a11y reviewers.  Do you know who we can get connected to resolve this disparity?

**Comment by tvolkert** [comment]
@jonahwilliams after talking with @goderbauer it sounds like the best way forward is to keep the visual element as-is but increase the size of the touch target.

**Comment by jonahwilliams** [comment]
Some other issues:

- Focusing the Paste/Select All/Dots is difficult/impossible currently
- (At least on P) volume buttons allow you to move the cursor forward and backward

I need to check an older phone but I don't believe the selection handle is meant to be used.  Not that we shouldn't increase the touch target anyway to make it easier to used

**Comment by alanrussian** [comment]
On P, there's a totally different UI too. See #17617

**Comment by jonahwilliams** [comment]
actually the volume controls appear to be working

**Comment by goderbauer** [comment]
@jonahwilliams Any update on this one since the attached PR got closed?

**Comment by jonahwilliams** [comment]
I tried increase the size in the overlay with padding, however I observed odd painting behavior.  I am still investigating

**Comment by jonahwilliams** [comment]
waiting for green to submit
