### ISSUE TITLE
Support magnify glass (loupe) feature for text selection in TextField in Android P

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#17617]
Android P changed the text cursor to have a magnifying preview above the user's finger. Editable text boxes in Flutter don't implement this. This inconsistency makes these text boxes feel broken to users who are on Android P.

https://9to5google.com/2018/03/07/android-p-dp1-text-zoom-tool-cursor/

**Comment by tedhenry100** [comment]
This is critical! I cannot see the cursor under my finger and the app feels broken!! I'm using `TextFormField`.

**Comment by charleshan** [comment]
Can we change the title of this issue? It doesn't explain what the issue is, so it's not searchable. 

Maybe "Support magnify glass feature for text selection in TextField in Android P."

I also agree with @tedhenry100. Text selection feels completely broken without this.

**Comment by justinmc** [comment]
I updated the title.  Also note that a similar feature was requested for iOS before iOS 13 dropped the magnifying glass cursor: https://github.com/flutter/flutter/issues/9507

**Comment by cbracken** [comment]
@blasten mentioned the https://developer.android.com/guide/topics/text/magnifier API in offline discussion.

**Comment by blasten** [comment]
I suspect `FlutterSurfaceView` would not work with the magnifier API. However, it might be work if `FlutterImageView` is used during this time.  Magnifying text has more moving parts (like notifying Android about where Flutter is drawing text.), but worth experimenting with.

**Comment by justinmc** [comment]
The magnifying glass is now back in iOS as well, as mentioned in https://github.com/flutter/flutter/issues/9507#issuecomment-865387887.

**Comment by MobileSoftHK** [comment]
Any update?

**Comment by yuhaocan** [comment]
mark

**Comment by nilsreichardt** [comment]
For `SelectionArea` we have now the same issue: https://github.com/flutter/flutter/issues/104555

**Comment by iosephmagno** [comment]
Any news about that? Magnifying glass is a core feature on ios textfield. Not having it looks like cross-platform, but even worse, common users would consider it just as a bug.

**Comment by antholeole** [comment]
@iosephmagno Good news! the loupe PR landed and the loupe is now in flutter 😁

**Comment by iosephmagno** [comment]
@antholeole great news! We must remain stick to our native wrapper because we need that emojis are rendered with native-like size. But step by step flutter textfield will become usable on ios 👍

**Comment by iosephmagno** [comment]
@antholeole eg. with current flutter textfield, we couldnt have this (see vid below). Emojis size would be very small (not native-like) and the feeling would be the one of a subpar app. But thank you very much for this pr. It is so good 👏

https://user-images.githubusercontent.com/83366073/182472936-b1ad7de1-a543-4013-89c3-c463c6b545e0.MOV

**Comment by nilsreichardt** [comment]
@antholeole Congrats to the PR 🎉

**Comment by antholeole** [comment]
> @antholeole Congrats 🎉 Amazing PR!

Thanks so much :) glad you like it. Feel free to tag me if you find any bugs!
