### ISSUE TITLE
Hero transition is above appbar and other widgets

### ISSUE THREAD

**Issue by BigMarco254** [flutter/flutter#17627]
## Steps to Reproduce

I have made a stack that has a hero with a container as a child to have the expanding background effect. The issue is the background is on-top of all other widgets until the transition is complete. The code is posted in the repository [here](https://github.com/littlemarc2011/FlutterTodo). I believe it would be cool to have something like z-index and/or be able to choose if a hero animation is above/below the appbar/scaffold/content.

What it looks like:
![broken hero example](https://user-images.githubusercontent.com/13179783/40082524-dfb0b166-5856-11e8-9e2d-fc8f8bbae997.gif)

## Logs

There are no error producing logs.

## Flutter Analyze

```
Analyzing FlutterTodo...                                         

   info • The top level variable '_kUnspecifiedArgument' isn't used • lib/CustomAppBar.dart:7:14
   info • Duplicate import • lib/main.dart:4:8
   info • Unused import: 'dart:async' • lib/main.dart:6:8
   info • Unused import: 'CustomAppBar.dart' • lib/main.dart:12:8
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method • lib/main.dart:80:8
   info • The operator x ~/ y is more efficient than (x / y).toInt() • lib/main.dart:87:18
   info • The value of the local variable '_ratioW' isn't used • lib/main.dart:124:18
   info • The value of the local variable '_ratioH' isn't used • lib/main.dart:127:18
warning • Element 'TextStyle' from SDK library 'ui.dart' is implicitly hidden by 'text_style.dart' • lib/main.dart:186:40
   info • Avoid empty statements • lib/main.dart:441:8
   info • Unused import: 'dart:collection' • lib/todo.dart:5:8

11 issues found. (ran in 2.3s)
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.4.3-pre.91, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.4.3-pre.91 at /Users/bigmarco254/flutter
    • Framework revision 674e44f361 (4 days ago), 2018-05-11 10:14:32 -0700
    • Engine revision 9ae10ef702
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/bigmarco254/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • IntelliJ at /Users/bigmarco254/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • iPhone X • 7C969D13-C3CE-4AB6-9DB1-0361698B3489 • ios • iOS 11.3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by littlemarc2011** [comment]
Does anyone have any ideas or is there any update on fixing this?

**Comment by BufferUnderflower** [comment]
Wrapping AppBar with Hero widget helped me avoid this.  see [SO Answer](https://stackoverflow.com/a/45888237/4076256)

**Comment by TahaTesser** [comment]
Hi @BigMarco254 
Are you still experiencing this issue with latest stable?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @BigMarco254 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by KermitTheFrogerino** [comment]
@TahaTesser I've also been experiencing the same issue... Latest stable release. I've got a widget above the hero widget. I'll try wrapping the above widget with a hero widget

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by rjeyy** [comment]
> ## Steps to Reproduce
> I have made a stack that has a hero with a container as a child to have the expanding background effect. The issue is the background is on-top of all other widgets until the transition is complete. The code is posted in the repository [here](https://github.com/littlemarc2011/FlutterTodo). I believe it would be cool to have something like z-index and/or be able to choose if a hero animation is above/below the appbar/scaffold/content.
> 
> What it looks like:
> ![broken hero example](https://user-images.githubusercontent.com/13179783/40082524-dfb0b166-5856-11e8-9e2d-fc8f8bbae997.gif)
> 
> ## Logs
> There are no error producing logs.
> 
> ## Flutter Analyze
> ```
> Analyzing FlutterTodo...                                         
> 
>    info • The top level variable '_kUnspecifiedArgument' isn't used • lib/CustomAppBar.dart:7:14
>    info • Duplicate import • lib/main.dart:4:8
>    info • Unused import: 'dart:async' • lib/main.dart:6:8
>    info • Unused import: 'CustomAppBar.dart' • lib/main.dart:12:8
>    info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method • lib/main.dart:80:8
>    info • The operator x ~/ y is more efficient than (x / y).toInt() • lib/main.dart:87:18
>    info • The value of the local variable '_ratioW' isn't used • lib/main.dart:124:18
>    info • The value of the local variable '_ratioH' isn't used • lib/main.dart:127:18
> warning • Element 'TextStyle' from SDK library 'ui.dart' is implicitly hidden by 'text_style.dart' • lib/main.dart:186:40
>    info • Avoid empty statements • lib/main.dart:441:8
>    info • Unused import: 'dart:collection' • lib/todo.dart:5:8
> 
> 11 issues found. (ran in 2.3s)
> ```
> 
> ## Flutter Doctor
> ```
> [✓] Flutter (Channel master, v0.4.3-pre.91, on Mac OS X 10.13.3 17D102, locale en-US)
>     • Flutter version 0.4.3-pre.91 at /Users/bigmarco254/flutter
>     • Framework revision 674e44f361 (4 days ago), 2018-05-11 10:14:32 -0700
>     • Engine revision 9ae10ef702
>     • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at /Users/bigmarco254/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-27, build-tools 27.0.3
>     • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 9.3, Build version 9E145
>     • ios-deploy 1.9.2
>     • CocoaPods version 1.5.2
> 
> [✗] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.io/setup/#android-setup for detailed instructions).
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
>     • IntelliJ at /Users/bigmarco254/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
>     • Flutter plugin version 24.2.1
>     • Dart plugin version 173.4700
> 
> [✓] VS Code (version 1.23.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Dart Code extension version 2.12.1
> 
> [✓] Connected devices (1 available)
>     • iPhone X • 7C969D13-C3CE-4AB6-9DB1-0361698B3489 • ios • iOS 11.3 (simulator)
> 
> ! Doctor found issues in 1 category.
> ```

Hi @BigMarco254 
I'm facing the same issue. Did you solve this problem?

**Comment by rjeyy** [comment]
Hi @BigMarco254 
I'm facing the same issue. Did you solve this problem?

**Comment by kashishkhullar** [comment]
We can use fade in animation for the rest of the content which is affected by the hero transition. This would work if your use case can have animations. See [Flutter Fade In](https://flutter.dev/docs/cookbook/animation/opacity-animation)

This won't solve the issue and hero image will be shown on top till it completes its transition but this would gives a nice look.
