### ISSUE TITLE
Flutter issue 

### ISSUE THREAD

**Issue by NavjeetSaini26** [flutter/flutter#17648]
Failed assertion: boolean expression must not be null

**Comment by zoechi** [comment]
Can you please add information how to reproduce?
This usually just points out an error in your code.
A common mistake is to assume that a variable of type `bool` can not be `null` in Dart, but it can.

**Comment by xster** [comment]
This issue is unfortunately not actionable. Feel free to open a new issue if you fill out the details requested in the bug filing template https://github.com/flutter/flutter/issues/new?template=BUG.md
