### ISSUE TITLE
Flutter Right-to-Left rtl wrapped multiline text hide first letter

### ISSUE THREAD

**Issue by drmsi** [flutter/flutter#17655]
Nothing is working to get multiline text to be wrapped with Right aligment

even without using SingleChildScrollView

@override Widget build(BuildContext context) {

var tt = "ومن رأى: أن إبرته التي يخيط بها انكسرت أو انتزعت منه، فإن شأنه يتفرق ويفسد أمره، وتدل الإبرة أيضاً على المرأة لإدخال الخيط فيها، وكذلك المسلة، فمن رأى أن بيده مسلة وكانت إمرأته حبلى ولدت له إبنة، وإن لم يكن هناك حمل دل ذلك على سفره.";

return new Scaffold(
  appBar: new AppBar(
    title: new Text(gettitle()) ,
  ),

    body:
    new Directionality(textDirection: TextDirection.rtl, child:
    new Padding(
    padding: const EdgeInsets.all(16.0),
    child:
      new SingleChildScrollView(
          child:
            new Text(
              tt,
              textAlign: TextAlign.right,
              textDirection: TextDirection.rtl,
            )
        ,)
    ),
    )

);    }
Doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale en-JO)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.0)
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0

**Comment by jason-simmons** [comment]
This should work better with the current engine on the master channel

**Comment by zoechi** [comment]
@drmsi is this still an issue?

**Comment by drmsi** [comment]
no it is not an issue any more, it is working perfectly on master channel

**Comment by zoechi** [comment]
Thanks for the update!
