### ISSUE TITLE
Make SystemChrome updates deterministic

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#17664]
Currently we schedule a microtask and update the system chrome to whatever the last value is.  This can vary based on which widget subtrees get rebuilt, since it is conventional to call this API in build.

Instead we should always pick an overlay style setting based on the topmost widgets.

**Comment by jonahwilliams** [comment]
Explored a solution that involved hitTesting near the very top of the screen, triggered by a special widget.  Problems:
  - Only works consistently if the widget is sufficiently early in the tree
  - Blocked by certain parent widgets that handle gestures
 - Page transition animations will build this set of widgets, however the new theme won't be in position to be hitTested until the route animation has completed.
  - Because of above, seems like we would need to do this on every frame.

I'm looking for a more robust solution.

cc @HansMuller , @Hixie

**Comment by Hixie** [comment]
you want to hit test on the layer tree. See https://github.com/flutter/flutter/issues/4630#issuecomment-371324100

**Comment by jonahwilliams** [comment]
Closing as a dupe of flutter/flutter#4630
