### ISSUE TITLE
Empty trailing Container in ListTile widget causes layout issues

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#17666]
@HansMuller There were some changes made to `ListTile` that caused some issues in the Hamilton app. In our modal bottom sheets that present a user state/country options, the trailing widget is either a checkmark icon or an empty container depending on the user's selection. It seems that now if the trailing widget is an empty `Container` the title lays out incorrectly. Replacing `Container` with `IgnorePointer` fixes the issue, but I'm filing the issue in case that was an unintended side effect.

**Before:**
![img_2412](https://user-images.githubusercontent.com/3614291/40142346-5602dce8-5926-11e8-92fa-c342a0ad8d35.PNG)

**Now:**
![img_2411](https://user-images.githubusercontent.com/3614291/40142363-64646694-5926-11e8-861e-301e0219a40c.PNG)

`flutter doctor -v`
```
[✓] Flutter (Channel master, v0.4.5-pre.10, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.4.5-pre.10 at /Users/albertlardizabal/dev/flutter
    • Framework revision 5159ab3513 (27 hours ago), 2018-05-15 10:09:25 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Android NDK at /Users/albertlardizabal/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1
```

**Comment by HansMuller** [comment]
I definitely didn't intend to disturb existing code however the current implementation gives the trailing widget as much horizontal space as it wants, so I expect the trailing empty container is grabbing up all the available width.  

In this case I would have expected the ListTile's trailing widget to either be null or a SizedBox with the same width as the check, or the check.  Would that work in your app?

**Comment by alardizabal** [comment]
Ok taking up all the horizontal space makes sense. `null` seems to work as well.

**Comment by HansMuller** [comment]
The SizedBox approach might make more sense if the title ever gets wide enough to wrap

**Comment by kostaa** [comment]
I have a similar problem - before I upgraded to the latest Flutter version: 

![screenshot_2018-05-26-19-05-02](https://user-images.githubusercontent.com/7585117/40579118-99094cc6-6118-11e8-9ded-fa3009d398b3.png)

and this is after the upgrade:

![image](https://user-images.githubusercontent.com/7585117/40579132-e41d54e6-6118-11e8-8ad5-e5154ecea206.png)

**Comment by HansMuller** [comment]
Sorry, you've run into a bug.

ListTile's layout is only loosely constraining the widget of its trailing widget and in this case the trailing text widget is consuming all the available width.  You could hack around the problem for the moment by giving the trailing widgets a fixed width with `new SizedBox(width: 100.0, child: myTrailingWidget)`.

Working on a proper fix now.

**Comment by HansMuller** [comment]
@kostaa - I was unable to reproduce the bug you're seeing with the current "tip of tree" version of Flutter

This is the test app I tried: https://gist.github.com/HansMuller/e1e7c655fa2952feb149e09299cd87e9

If you can send along an example that demonstrates the problem, I will look into it.

**Comment by kostaa** [comment]
@HansMuller - I will try to extract the relevant part. 
Will come back to you once I have (not) working.

**Comment by kostaa** [comment]
@HansMuller - managed to find the bit that is causing the issue - it is related to the `ListTile::trailing` property:

``` 
        child: new ListTile(
          title: const Text('Marks & Spencer'),
          subtitle: const Text('01/12/2017'),
          trailing: amount('-2','20'),
        ),

  Widget amount(String whole, String dec) =>  new Row(
        mainAxisAlignment: MainAxisAlignment.end,
        crossAxisAlignment: CrossAxisAlignment.baseline,
        textBaseline: TextBaseline.alphabetic,
        children: <Widget>[
          Text(whole),
          Text('.'),
          Text(dec),
        ]);
``` 

The idea is that the amount is split and both parts can be styled separately.

**Comment by HansMuller** [comment]
I see the problem. The Row will consume all of the available width unless you specify `mainAxisSize: MainAxisSize.min`: https://docs.flutter.io/flutter/rendering/MainAxisSize-class.html

**Comment by kostaa** [comment]
Indeed that makes sense. 
Thanks for pointing that out.

Regards,
Adam

**Comment by HansMuller** [comment]
I'm leaving this issue open since some improvements are warranted:
- The documentation should warn about trailing widgets that expand horizontally
- We could assert if the trailing widget consumes all of the available width and provide a helpful message
