### ISSUE TITLE
[Cloud Firestore Plugin] Error performing transaction

### ISSUE THREAD

**Issue by matgrz1993** [flutter/flutter#17663]
Hello,

I have been doing this tutorial step by step:
[flutter-firebase](https://codelabs.developers.google.com/codelabs/flutter-firebase/#9)
and everything works execelent, but when I tap on any row the java.lang.Exception is thrown.

## Code

```dart
onTap: () => Firestore.instance.runTransaction((transaction) async {
    DocumentSnapshot postSnapshot =
        await transaction.get(document.reference);
    if (postSnapshot.exists) {
      await transaction.update(document.reference,
          <String, dynamic>{'votes': postSnapshot.data['votes'] + 1});
    }
  }),
```

## Logs

```
E/flutter ( 4032): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 4032): PlatformException(Error performing transaction, java.lang.Exception: Do transaction failed., null)
E/flutter ( 4032): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter ( 4032): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter ( 4032): <asynchronous suspension>
E/flutter ( 4032): #2      Firestore.runTransaction (file:///c:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/lib/src/firestore.dart:115:10)
E/flutter ( 4032): <asynchronous suspension>
E/flutter ( 4032): #3      MyHomePage._buildListItem.<anonymous closure> (file:///X:/Projects/baby_names/lib/main.dart:62:39)
E/flutter ( 4032): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
E/flutter ( 4032): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
E/flutter ( 4032): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 4032): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter ( 4032): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter ( 4032): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 4032): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter ( 4032): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter ( 4032): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 4032): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter ( 4032): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter ( 4032): #15     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter ( 4032): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): Failed to handle method call result
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): java.lang.IllegalStateException: Task is already complete
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source:8)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at com.google.android.gms.tasks.zzu.zzdr(Unknown Source:8)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at com.google.android.gms.tasks.zzu.setException(Unknown Source:9)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at com.google.android.gms.tasks.TaskCompletionSource.setException(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$3$1.error(CloudFirestorePlugin.java:290)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:171)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at io.flutter.view.FlutterNativeView.handlePlatformMessageResponse(FlutterNativeView.java:171)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 4032): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
## Note:

When I try this solution, it works:
```dart
onTap: () {           // DO NOT USE THIS VERSION!
       document.reference.updateData({'votes': document['votes'] + 1});
},
```

## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 6.3.9600], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.23.1)
[√] Connected devices (1 available)
```

**Comment by felipe-quiroz** [comment]
https://github.com/flutter/flutter/issues/14655

**Comment by RedTech64** [comment]
Any updates on this? I'm having this same problem!!

**Comment by zoechi** [comment]
@RedTech64 can you please add the output of `flutter doctor`?
@brianegan do you know about that?

**Comment by brianegan** [comment]
@zoechi Unfortunately I'm not quite sure about that one -- Looks like it could be a legit bug with the plugin, or perhaps the tutorial needs to be updated, but it's not a plugin or tutorial I maintain :(

**Comment by RedTech64** [comment]
I figured out my problem which had to do with how I was accessing the Firestore database. However, I feel like there could be some improvements to how Flutter shows these errors because I was getting errors that were not very helpful to diagnose.

**Comment by zoechi** [comment]
cc @Hixie

**Comment by mortenboye** [comment]
@RedTech64 can you elaborate on the changes you did, to fix this? I'm experiencing a similar error.

**Comment by manbach** [comment]
Im not sure if this helps someone but we got the same error, when we didnt await the result of transaction.update()

So this throws the same Error:

```
firestore.runTransaction((Transaction transaction) async {
        DocumentSnapshot snapshot = await transaction.get(docRef);
         transaction.update(docRef,{
            'content' : snapshot['content']+1
          }
        );
      });
```

This works for me

```
firestore.runTransaction((Transaction transaction) async {
        DocumentSnapshot snapshot = await transaction.get(docRef);
         **await** transaction.update(docRef,{
            'content' : snapshot['content']+1
          }
        );
      });
```

**Comment by matthiask1** [comment]
I'm experiencing this issue since I have started playing around with the firebase security rules. The exception raised by @matgrz1993 is thrown, but the transactions complete as expected...

**Comment by SoA-YD** [comment]
It works with this code.
Recommend you to check the type of variable in your Cloud Firestore.
I've got the same errors when I didn't check the `types...`
'hits' was bound as 'String'.....:(
 
https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..%2Findex#9
 
`onTap: () => Firestore.instance.runTransaction((transaction) async {
              print(document.documentID);
              DocumentSnapshot freshSnap =
                  await transaction.get(document.reference);
              await transaction
                  .update(freshSnap.reference, {'hits': freshSnap['hits'] + 1});
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => CommunityPost()),
              );
            }));`

**Comment by darrencole** [comment]
@SoA-YD's, suggestion solved the problem for me. I erroneously had "votes" set up as string instead of number. The code at https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#9 works fine if you follow it properly.

**Comment by leorachit** [comment]
This is happening intermittently, especially when there are multiple transactions happening at the same time. Please help.

**Comment by darrencole** [comment]
@leorachit can you verify that the votes variable is set to string for all your baby name documents?

**Comment by RishitKedia** [comment]
Hey there, wonderful people! 👋

I've been battling this for the past few hours, and I've managed to get past this.

In my case, I was getting the **'Task is already complete'** exception due to **'missing or insufficient permissions'** to update a document. This was because of the `Firestore Rules` that I had set up. It would've been nice if `Firestore` had thrown the **'Missing or insufficient permissions'** exception instead of the one we're getting here, but hey, that's life for you. 😋

You can try all the operations in your transaction normally (without the transaction itself), and see what that gives you, which is how I came to know about the other exception. Running in **debug** mode will help surface the exceptions (at least in my experience).

I know this may not be the case for you, so YMMV, but, hey, it's worth a shot. Gotta keep trying! 😅

**Comment by kentcb** [comment]
@RishitKedia Yes, I think the fundamental problem is that _all_ errors are manifesting in the same "Task is already complete" error, and the original error is lost. In my case, I am coding against a completely wide-open Firestore, so it's definitely not the same problem for me.

For me, everything works fine outside of the transaction. I can do writes inside a transaction. I cannot do reads.

It's hard for me to understand how anyone is able to use it in its current state, but then it could be that the actual error is specific to my environment. I plan on trying a few other things when I get some time, but right now I'm completely blocked by this. And I won't be able to take my app to production without a fix.

**Comment by Purus** [comment]
As Kent pointed out, I am also having the wider access permission and it
should not be the reason. When a normal update works, using transaction
gives this error.

It's necessary that the actual exception is shown instead of a high level
message.

Thanks,

Purusothaman Ramanujam

**Comment by kentcb** [comment]
Another update from me. Whilst I certainly don't understand everything about the situation yet, I can say this:

* On the Java side, the lambda that gets passed into `runTransaction` is being executed twice. Firestore must be calling it twice, and I assume the lambda is supposed to anticipate this possibility.
* This means `channel.invokeMethod` is being called twice, causing the Dart-side code to run twice per my previous comment.
* It also means that the callback executes twice. The second execution results in the error I posted above.

By changing the Java code from `setResult` to `trySetResult`, I can bypass the error. However, it's not clear to me why the transaction handler is executing twice in the first place.

Can anyone from the Dart/Firebase team weigh in on this? Is it being looked at? It would be nice not to be left in the dark for so long.

**Comment by stt106** [comment]
is there any update on this?

**Comment by faizalshap** [comment]
wrap the code in try/catch to see what is the actual error. 
For me, i was trying to get a document after write which was causing this error.

**Comment by kentcb** [comment]
@faizalshap As pointed out [above](https://github.com/flutter/flutter/issues/17663#issuecomment-439222725), the problem is that many errors are manifesting in the same, useless error on the Dart side.

**Comment by collinjackson** [comment]
Per @kentcb's comment, it's a somewhat unsatisfying solution but I think https://github.com/flutter/plugins/pull/1202 would prevent the crash by calling `trySetResult` instead of `setResult`. If anyone has feels that there's more to this issue let me know.

**Comment by unibeck** [comment]
I've updated to the new `cloud_firestore: ^0.9.5+1` and I'm still receiving the `java.lang.Exception: Do transaction failed` error as seen here:
```
E/flutter (22524): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (22524): PlatformException(Error performing transaction, java.lang.Exception: Do transaction failed., null)
E/flutter (22524): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (22524): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (22524): <asynchronous suspension>
E/flutter (22524): #2      Firestore.runTransaction (file:///opt/flutter_linux_v1.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.5+1/lib/src/firestore.dart:117:10)
E/flutter (22524): <asynchronous suspension>
```

@collinjackson's fix was provided in `cloud_firestore: 0.9.2` and I verified I have his changes by looking at the dependency pulled from pub. The following is the code that I'm using and is giving me the error, it's very similar to previous reports and I've tried various patterns all with the same result:
```
  Future<bool> addTagToTaleTX(Tale tale, String tag) async {
    List<String> newTagList = List.from(tale.tags)..add(tag);

    return Firestore.instance.runTransaction((Transaction tx) async {
      //Make sure the tale still exists before we update it
      DocumentSnapshot taleSnapshot = await tx.get(tale.reference);
      if (taleSnapshot.exists) {
        await tx.update(tale.reference, <String, dynamic>{"tags": newTagList});
        return {"updated": true};
      }

      return {"updated": false};
    })
        .then((result) => result["updated"])
        .catchError((error) {
      print("error: $error");
      return false;
    });
  }
```

**Comment by collinjackson** [comment]
@unibeck We could get a more verbose error message by fixing https://github.com/flutter/flutter/issues/17024

**Comment by kentcb** [comment]
@unibeck it's a shot in the dark because the error message is so non-specific, but I ran into exactly the same thing. Turns out I had forgotten about permissions on the DB. I was trying to test the txn mechanism but was violating my security rules in the process. There's a small chance you're hitting the same thing. But yeah, #17024 is crucial imho.

**Comment by HengJunXi** [comment]
I think I found a workaround for this (which worked for me)
For **every document reference read** in the transaction, you must also perform update to that specific document reference (even though no change to the data)

Following code works successfully using cloud_firestore 0.8.2+3
```
db.runTransaction((Transaction tx) async {
    var courseDoc = await tx.get(courseRef);       // read courseRef
    await tx.update(courseRef, courseDoc.data);    // extra update to courseRef
    await tx.set(chatRef, chat);                   // actual intended operation
}
```

**Comment by MDSADABWASIM** [comment]
I had the same issue which appears after the solution, the problem was I was not using async keyword in runtransaction function.

**Comment by HengJunXi** [comment]
Well... it worked for me using cloud_firestore 0.8.2+3, try using async instead maybe?

**Comment by MeshkaniMohammad** [comment]
@HengJunXi I tried this solution but It couldn't help me!
My problem is STRANG because I used this code in two different part of my app and just one part has problem!

**Comment by HengJunXi** [comment]
That is strange... you sure it is not because of other problems? Or all the document reference read in the transaction is updated? Or all write operations are done after read operations? (library version: cloud_firestore 0.8.2+3)

**Comment by PandaGeek1024** [comment]
Im getting similar issue when using transaction to delete multiple docs. 

It always reports "Transaction has already completed."

**Comment by anand-bhat** [comment]
Running into the same issue at [Step 11 - Use a Cloud Firestore transaction](https://codelabs.developers.google.com/codelabs/flutter-firebase/#10) of codelab when I click the name to register a vote. I'm seeing this error happen when I double click on a name in the emulator. The counts do get updated once, despite the error.

**Comment by Levi-Lesches** [comment]
I got this error and it turns out there was a problem with my security rules. I think there should be a more specific error here, like "access denied", just like a regular read/write.

**Comment by HengJunXi** [comment]
> I got this error and it turns out there was a problem with my security rules. I think there should be a more specific error here, like "access denied", just like a regular read/write.

May I know specifically what's the security rules problem? In order for us to tackle this problem

**Comment by Levi-Lesches** [comment]
Well I have this larger project so I have rules for each collection, but when I realized something wasn't working, I set up a new collection to use for the standard Flutter counter demo (really simple, just increment whenever the button is pressed). But I forgot to write new rules for this collection, so it wouldn't let me through.

The thing is though, with this error message, the problem could really be any number of things, and should just be a simple ACCESS DENIED or something.

**Comment by kentcb** [comment]
@Levi-Lesches Mentioned that at https://github.com/flutter/flutter/issues/17663#issuecomment-468470817

**Comment by Levi-Lesches** [comment]
Exactly, I totally agree with you (actually your comment is what prompted me to check my security rules in the first place). There really needs to be better error messages here.

**Comment by thevzurd** [comment]
I had the same problem. Try this. Hope it Helps 
[FIrestore Transaction Handler](https://github.com/thevzurd/Firestore-Transaction-Handler)

**Comment by kroikie** [comment]
@matgrz1993

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/823. Any further collaboration will be done there.

**Comment by copmorty** [comment]
Hi, I had the same problem, and I found the solution. In my case the error was because I put the wrong reference in the update function, this reference was about a nonexistent document, by mistake the reference that I built was a totally new one (like the one you use for the set function). And I didn't need to use await with the update function.
Hope it helps someone.

**Comment by Vkadel** [comment]
I had the same problem and was able to solve it by changing the timeout of the operation, the standard 5 secs they provide was causing problems for me. I changed it to 30sec.

**Comment by flutterium** [comment]
Hi everyone !

I had the same problems (also multiple transaction) and then i got solution with this code block ;
_Flutter version : 1.12.13+hotfix8
cloud_firestore version : ^0.13.0+1_

`try {
      userReference.runTransaction((Transaction tx) async {
      DocumentSnapshot postSnapshot = await tx.get(userDocumentReference);
      if (postSnapshot.exists) {
        await tx.update(userDocumentReference, <String, dynamic>{
          'dailyLimit': (int.parse(postSnapshot.data['dailyLimit']) - 1).toString()
        });
      } else {
        await tx.set(userDocumentReference, <String, dynamic>{
          'dailyLimit': (int.parse(postSnapshot.data['dailyLimit']) - 1).toString()
        });
      }
    }).whenComplete(() =>  userReference.runTransaction((Transaction tx) async {
      DocumentSnapshot postSnapshot = await tx.get(userDocumentReference);
      if (postSnapshot.exists) {
        await tx.update(userDocumentReference, <String, dynamic>{
          'omega': (int.parse(postSnapshot.data['omega']) - int.parse('$prizeAmount')).toString()
        });
      } else {
        await tx.set(userDocumentReference, <String, dynamic>{
          'omega': (int.parse(postSnapshot.data['omega']) - int.parse('$prizeAmount')).toString()
        });
      }
    }));
    } catch (e) {
      print(e);
    }`
