### ISSUE TITLE
Flutter Firestore crassssshhhhhhh (follow the tutorial by CodeLab)

### ISSUE THREAD

**Issue by weicheng95** [flutter/flutter#17678]
## Ok here is my problem, when I 'flutter run' my app on my iphone simulator, it crash with this issues.
I already setup the googleService-info.plist inside Runner.

-----------------------------------------------------------------------------

### pubspec.yaml

> dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: '^0.7.2'
  firebase_core: '^0.2.2'
-----------------------------------------------------------------------------

> Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    3.4s
 └─Compiling, linking and signing...                  8.4s
Xcode build done.                                           16.7s
5.0.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

> 5.0.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50000000 started
5.0.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
	[1.1 B4CCB9B4-7E7D-4296-95D3-0732AD787EB2 2001:e68:5445:16d9:584:8439:fdbc:de7.51192<->2404:6800:4001:807::200a.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.234s, DNS @0.030s took 0.017s, TCP @0.055s took 0.015s, TLS took 0.080s
	bytes in/out: 3756/1064, packets in/out: 9/10, rtt: 0.009s, retransmitted packets: 0, out-of-order packets: 0
5.0.0 - [Firebase/Core][I-COR000004] App with name test does not exist.
	[2.1 8ED74D42-07D6-47A2-BD95-4BEDCCEA0892 2001:e68:5445:16d9:584:8439:fdbc:de7.51193<->2404:6800:4001:807::200a.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.087s, DNS @0.002s took 0.012s, TCP @0.016s took 0.005s, TLS took 0.035s
	bytes in/out: 3422/1064, packets in/out: 10/10, rtt: 0.006s, retransmitted packets: 0, out-of-order packets: 0
5.0.0 - [Firebase/Firestore][I-FST000001] The behavior for system Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:

> let db = Firestore.firestore()
let settings = db.settings
settings.areTimestampsInSnapshotsEnabled = true
db.settings = settings

> With this change, timestamps stored in Cloud Firestore will be read back as Firebase Timestamp objects instead of as system Date objects. So you will also need to update code expecting a Date to instead expect a Timestamp. For example:

> // old:
let date: Date = documentSnapshot.get("created_at") as! Date
// new:
let timestamp: Timestamp = documentSnapshot.get("created_at") as! Timestamp
let date: Date = timestamp.dateValue()
Please audit all existing usages of Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do<…> First throw call stack:
(
	0   CoreFoundation                      0x000000010f1411e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010e7d6031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f146472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010dd53652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Runner                              0x000000010ae57b0e -[GRPCHost setTLSPEMRootCerts:withPrivateKey:wit<…>
Lost connection to device.
Syncing files to device iPhone X...         

-----------------------------------------------------------------------------

**Comment by JonathanSum** [comment]
Are you in step 9? Could you tell us which step you are on?

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by weicheng95** [comment]
@johnmccutchan Yes, I'm stuck at step 9

**Comment by weicheng95** [comment]
@zoechi 
here is my flutter doctor output

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.4.5-pre.23, on Mac OS X 10.13.4 17E202, locale en-MY)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✗] Android Studio (not installed)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)
! Doctor found issues in 2 categories.

**Comment by weicheng95** [comment]
@JonathanSum I tried to run the apps on Android, it's work pretty fine. Only crash on IOS

**Comment by weicheng95** [comment]
@JonathanSum @zoechi So just now I try to make it use swift with "flutter create -i swift projectname"
and It's work. Thank you guys.

**Comment by sabik22** [comment]
It was working fine but suddenly crash with error

`Running "flutter packages get" in futsal_hub_admin...
Launching lib/main.dart on iPhone X in debug mode...
[VERBOSE-2:dart_error.cc(16)] error: import of dart:mirrors with --enable-mirrors=false
[VERBOSE-2:engine.cc(151)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(116)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(178)] Could not launch engine with configuration.
5.0.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.0.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50000000 started
5.0.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
	[1.1 763E2677-DA0A-44FA-803A-396E4919B867 192.168.100.4.50649<->172.217.160.42:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.483s, DNS @0.012s took 0.019s, TCP @0.039s took 0.099s, TLS took 0.213s
	bytes in/out: 3536/1080, packets in/out: 9/10, rtt: 0.097s, retransmitted packets: 0, out-of-order packets: 0
Syncing files to device iPhone X...
`

Flutter doctor
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.5-pre.7, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

`
I tried  "flutter create -i swift projectname" also but doesn't work
