### ISSUE TITLE
Issue from website page Get Started: Install on Windows

### ISSUE THREAD

**Issue by emmanuelagarry** [flutter/flutter#17674]
I have all the requirements to run flutter on my computer and i followed all the installation guidelines on flutter from this page ' https://flutter.io/setup-windows/ '.  but when run flutter doctor on the flutter_console.bat file, it does nothing. I get no error message. I also added flutter to my path, but it still does nothing on my command prompt

**Comment by rmathias86** [comment]
Please paste here flutter doctor.

**Comment by zoechi** [comment]
What shell are you using?

**Comment by emmanuelagarry** [comment]
i used windows power shell and windows command prompt, but it works now. I have to run my shell as administrator. It is just kind of annoying to run as administrator every time

**Comment by zoechi** [comment]
That shouldn't be necessary, but I'd guess that's rather an issue with your configuration than with Flutter itself.

**Comment by zoechi** [comment]
See also https://flutter.io/setup-windows/

> Extract the zip-file and place the contained flutter in the desired installation location for the Flutter SDK (eg. C:\src\flutter; do not install flutter in a directory like C:\Program Files\ that requires elevated privileges).
