### ISSUE TITLE
Issue with Isolate + Async methods

### ISSUE THREAD

**Issue by patrykpoborca** [flutter/flutter#17671]
## Steps to Reproduce

```
void myEntryPoint(SendPort port) {
port.send("Hello");
thisBreaksUs(); // we won't hit this instead we'll get a message to the "onExit" callbak
port.send("World");
}

void thisBreaksUs() async {
}
```

I think this is important because of the documentation found here says that this should work as shown here: https://puu.sh/An0J9/f9b077bfce.png

https://flutter.io/flutter-for-android/#how-do-you-move-work-to-a-background-thread

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by DaGump** [comment]
The same happens to me too

here the output of my flutter doctor:

> C:\src\flutter\bin\flutter.bat doctor --verbose
> [√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.107], locale de-AT)
>     • Flutter version 1.2.1 at C:\src\flutter
>     • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\mga\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 34.0.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [√] Connected device (1 available)
>     • FRD L09 • 73QDU17517001330 • android-arm64 • Android 7.0 (API 24)
> 
> • No issues found!
> Process finished with exit code 0

it happens whenever I try to invoke a async Method inside my Isolate(d) oder Compute Method. No direct error is shown.
only on my device a void message is shown a thousand times:
2019-04-12 23:48:57.551 1204-1400/? E/HwCHRWebMonitor: running processName=sensai.android.mga.at.sensai>
