### ISSUE TITLE
valueIndicatorTextStyle == null when using accentTextTheme

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#17670]
The problem appears to be in **accentTextTheme**. When I leave it in, I get the following error:

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (32258): The following assertion was thrown building UnitConverterApp(dirty):
I/flutter (32258): 'package:flutter/src/material/slider_theme.dart': Failed assertion: line 233 pos 12:
I/flutter (32258): 'valueIndicatorTextStyle != null': is not true.
I/flutter (32258): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (32258): more information in this error message to help you determine and fix the underlying cause.
I/flutter (32258): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (32258):   https://github.com/flutter/flutter/issues/new
I/flutter (32258): When the exception was thrown, this was the stack:
I/flutter (32258): #2      new SliderThemeData.fromPrimaryColors (package:flutter/src/material/slider_theme.dart)
I/flutter (32258): #3      new ThemeData (package:flutter/src/material/theme_data.dart:167:25)
I/flutter (32258): #4      UnitConverterApp.build (file:///C:/Users/andre/Desktop/Flutter/udacity_flutter_app/lib/main.dart:21:14)
I/flutter (32258): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3687:28)
I/flutter (32258): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
I/flutter (32258): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter (32258): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
I/flutter (32258): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (32258): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (32258): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (32258): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (32258): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (32258): #15     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (32258): #16     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (32258): #17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (32258): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (32258): ════════════════════════════════════════════════════════════════════════════════════════════════════

Here is the code:

```
void main() {
  runApp(UnitConverterApp());
}

const _defaultAccentTextStyle = TextStyle(
  color: Color(0xFF000000),
);

class UnitConverterApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        brightness: Brightness.dark,
        primaryColor: Color(0xFF424242),
        primaryColorLight: Color(0xFF6D6D6D),
        primaryColorDark: Color(0xFF1B1B1B),
        accentColor: Color(0xFFFCD734),
        accentTextTheme: TextTheme(
          title: _defaultAccentTextStyle,
          button: _defaultAccentTextStyle,
        ),
        accentIconTheme: IconThemeData(
          color: Color(0xFFC5A600),
        ),
      ),
      debugShowCheckedModeBanner: false,
      title: 'Unit Converter',
      home: CategoryScreen(),
    );
  }
}

```

Here is the doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!

**Comment by gspencergoog** [comment]
This can be fixed by creating your ThemeData using `Theme.of(context).copyWith` instead of creating a new ThemeData from scratch.  That will carry along the default values without leaving the rest of the sub-themes as `null` values.

Something like this:
```dart
class UnitConverterApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: Theme.of(context).copyWith(
        brightness: Brightness.dark,
        ...
```

We're aware that this trips people up: https://github.com/flutter/flutter/issues/9148
