### ISSUE TITLE
Multiple flutter views seems to interfere with each others graphics context.

### ISSUE THREAD

**Issue by sigurdm** [flutter/flutter#17688]
I have only tried this on iOS.

I created an iOS project creating two distinct FlutterViewControllers, each showing the same image (using `new Image.asset("assets/a.jpeg")`).
The image is garbled in the second view.

Attaching a screen recording showing the problem (the two views should show the same image).

The code instantiating the FlutterViewController is as follows:

```objective-c
- (void)pushFlutter1 {
    NSLog(@"Pushed");
    if (!_flutterViewController1) {
    _flutterViewController1 = [[FlutterViewController alloc] initWithProject:nil nibName:nil bundle:nil];
        messageChannel = [FlutterBasicMessageChannel messageChannelWithName:@"channel"
                                                            binaryMessenger:_flutterViewController1
                                                                      codec:[FlutterStandardMessageCodec sharedInstance]];
        [_flutterViewController1 setInitialRoute:@"1"];
        UINavigationController*  __weak weakSelf = self;
        _flutterViewController1.edgesForExtendedLayout = UIRectEdgeNone;
        [messageChannel setMessageHandler:^(id message, FlutterReply reply) {
            [weakSelf popViewControllerAnimated:YES];
            NSLog(@"Popping");
            reply(@"");
        }];
    }

    NSAssert([self navigationController], @"Must have a NaviationController");
    [[self navigationController] pushViewController:_flutterViewController1 animated:YES];
}
```

(and similarly for the second view).
<img src="https://user-images.githubusercontent.com/8613953/40173402-ff0653be-59d1-11e8-8bb3-0f4dbe6bbc1d.gif" width="200" />

**Comment by xster** [comment]
cc @chinmaygarde

**Comment by chinmaygarde** [comment]
Do you have a reduced test case? Both flutter views have entirely separate rendering contexts operating on different threads. So it is surprising that they are interfering.

**Comment by darshankawar** [comment]
@sigurdm 
Is this still a valid issue on latest Flutter version ?
If so, Can you provide a complete minimal reproducible code sample that shows the issue along with `flutter doctor -v` ?
Thanks.

**Comment by sigurdm** [comment]
Sorry - this was long time ago - I don't even have access to an ios test device.
