### ISSUE TITLE
Is it possible to tween between icons?

### ISSUE THREAD

**Issue by Gacnt** [flutter/flutter#17689]
I have a little Icons.favorite and Icons.favorite_border

I’d like to Tween between them when I toggle a “favorite” state. Is this doable at the moment? 

Sorry for formatting. On mobile x.x

**Comment by EpicEricEE** [comment]
You could use an [AnimatedCrossFade](https://docs.flutter.io/flutter/widgets/AnimatedCrossFade-class.html) for that.

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/fluttie
https://pub.dartlang.org/packages/lottie_flutter
might also be useful for this use case.

Did EpicEricEE's suggestion help?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
