### ISSUE TITLE
How can I get write external permission?

### ISSUE THREAD

**Issue by JAICHANGPARK** [flutter/flutter#17681]
I'd like to use camera and save photo to external storage in my own folder.

How can I get Write/Read External Permissions?

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/simple_permissions

**Comment by xster** [comment]
Closing this bug for now. Feel free to re-open if the answer doesn't address your needs.

**Comment by zoechi** [comment]
I tried a few as well and run into several issues.
The `permission` worked well for me last time though. 
I leave it to @xster to decide if it should be reopened.

**Comment by iamprakash13** [comment]
simple permissions shows duplicate mappingkey on pub get packages.
help me resolve issue @zoechi @xster 
this: [https://github.com/flutter/flutter/issues/24619](url)

**Comment by rdcoder33** [comment]
simple_permission is not updated with AndroidX
