### ISSUE TITLE
Create PDF in Flutter

### ISSUE THREAD

**Issue by mjsunny** [flutter/flutter#17685]
Is there any flutter package or way to design and create a pdf file like [iText](https://itextpdf.com/)

**Comment by ahmed-eg** [comment]
please take a look  at this https://github.com/flutter/flutter/issues/14259
 (but it works on Android only so far)

**Comment by Hixie** [comment]
This isn't really something we are likely to support as a first-party package, but it looks like there are some third-party packages that implement such a feature.
