### ISSUE TITLE
how to select and copy text from Text widget ?

### ISSUE THREAD

**Issue by wendux** [flutter/flutter#17680]
I want to select some text from Text/RichText widget , and then paste to other application . But I have not find there is an attribute like "selectable" in Text/RichText widget.

**Comment by zoechi** [comment]
The closest I found was https://docs.flutter.io/flutter/rendering/RenderEditable-class.html

**Comment by zoechi** [comment]
@Hixie

**Comment by lifenautjoe** [comment]
How can we use the RenderEditable class? 

`The element type 'RenderEditable' can't be assigned to the list type 'Widget'.`

**Comment by zoechi** [comment]
@lifenautjoe please provide a minimal runnable self-contained reproduction (`lib/main.dart`)

**Comment by zoechi** [comment]
Merging with #5422

**Comment by stephensamonte** [comment]
You can save text to the clipboard with the service package. 

This is a possible solution: https://stackoverflow.com/questions/46260055/how-to-make-copyable-text-flutter-widget

You can't select the specific text to copy with this solution.

This copies an entire block of text:
```
import 'package:flutter/services.dart';

String textToCopy = "test";
    return new GestureDetector(
      child: new Text(textToCopy),
      onLongPress: () {
        Clipboard.setData(new ClipboardData(text: textToCopy));
        key.currentState.showSnackBar(
            new SnackBar(content: new Text("Copied to Clipboard"),));
      },
    );
```

**Comment by patelkrunal78** [comment]
Your Solution At Here https://icetutor.com/question/how-to-make-copyable-text-widget-in-flutter
