### ISSUE TITLE
flutter start support for `--debug-port` on ios simulator

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1769]
It doesn't look like the `--debug-port` flag is supported by the ios simulator. When passing in `--debug-port=6161` to flutter start, the ios simulator starts up and listens on 8181 (the default). I see that we're invoking `xcrun simctl launch` with `--observatory-port=6161`, but am not sure where the param passing logic is breaking down inside the engine.

@chinmaygarde

**Comment by devoncarew** [comment]
Closing this out - I had an older engine in my `ios/` directory. We'll add a sha file (`REVISION`) here in order to warn about this in the future.

**Comment by chinmaygarde** [comment]
A `REVISION` file is now added to the `ios/` directory. Tooling needs to be wired in.
