### ISSUE TITLE
flutter doesn't generate android native java code 

### ISSUE THREAD

**Issue by rolandbrake** [flutter/flutter#17690]
i'm a beginner user of flutter framework i don't know the detail mechanism behind of this technology yet and how exactly it's work but from what i read about this framework the main reason for using it is to help the programmer to generate hyper apps for more than one platform. i have an idea for a new app i'm making right now i want to make the UI with the flutter framework then i will continue coding the app with native java code  but after sometime of using this framework i realized that the android code that initially exist in newly created flutter app still the same even after rebuilding or changing the dart code, the java code still the same every time, is there any solution for this problem?.

**Comment by MisterJimson** [comment]
No, flutter does not generate native code.

You can implement some native features with Platform Channels, see here: https://flutter.io/platform-channels/

**Comment by rolandbrake** [comment]
but if what you are saying is true why flutter created projects have android and ios folders on it, inside each folder there's the native code for each platform

**Comment by MisterJimson** [comment]
There is some native code to bootstrap the app and initiate the flutter engine and UI. 

This code is not the UI itself, just a starting point for the flutter app to start and take over.

**Comment by zoechi** [comment]
Flutters Dart code is compiled to binary code for the target CPU, **not** for the target native platform like Java, Swift/Object-C.
There is some code in `android` and `ios` folders to interact with the native platform is all.

**Comment by hnvn** [comment]
Give this [article](https://medium.com/flutter-io/why-flutter-doesnt-use-oem-widgets-94746e812510) a read. I see many misunderstandings about Flutter. Flutter is based on the top of Skia engine to render its own UI elements in independence with native UI elements of Android or iOS sdk. That's why Flutter don't have to deal with backward compatibility problems.

**Comment by zoechi** [comment]
I assume this question is answered.
