### ISSUE TITLE
Low frame-rates on HTC One A9

### ISSUE THREAD

**Issue by al1b** [flutter/flutter#17694]
I've downloaded Flutter Gallery on my `HTC One A9`:

Chipset | Qualcomm MSM8952 Snapdragon 617
-- | --
CPU | Octa-core (4x1.5 GHz Cortex-A53 & 4x1.2 GHz Cortex-A53)
GPU | Adreno 405

It seems slow and not smooth at all.

Here is the frame-rates in `material` and `chips` page.

Section	|	Frame-rates
-- | --
GPU	|	3.6 fps
UI	|	8.4 fps

**Comment by al1b** [comment]
Any progress?

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by al1b** [comment]
@zoechi 
How could I test it?
Download the latest flutter gallery?

**Comment by al1b** [comment]
Unfortuantelly My HTC One A9 is broken now and I cannot test it. I only test it over my new Nokia 6.1 plus and it worked very well. (without any red on the performance graph)
