### ISSUE TITLE
hot reload benchmarks 2-3x regressed in recent engine roll(with dart roll)

### ISSUE THREAD

**Issue by aam** [flutter/flutter#17705]
With https://github.com/flutter/flutter/commit/2e24351fb1a329cbf279cd87e1b647898e609262

hot_mode_dev_cycle_win__benchmark 2203ms(used to be 739ms) hotReloadFlutterReassembleMilliseconds

hot_mode_dev_cycle_linux__benchmark 2219ms(used to be 819ms) hotReloadFlutterReassembleMilliseconds

hot_mode_dev_cycle_linux__benchmark 2609ms(used to be 1299ms) hotReloadMillisecondsToFrame

Could be time-accounting issue since we also see 2x speed up in hotRestartMillisecondsToFrame 2397ms(used to be 5070ms)

**Comment by cbracken** [comment]
Closing in favour of #17888 which came later, but is better-tagged.
