### ISSUE TITLE
"Creating a new project from existing source code" guidance is not valid anymore

### ISSUE THREAD

**Issue by haqqi** [flutter/flutter#17707]
From URL: https://flutter.io/using-ide/

Because the recent Flutter plugin for Android Studio, the guide for importing existing code is not valid anymore. I cannot find any menu of creating Flutter using existing code. If i try to create new Flutter app, it will show error if the existing folder exists.

Any idea how to import existing project properly in Android Studio?

![image](https://user-images.githubusercontent.com/831763/40207686-0669ba2c-5a60-11e8-9e67-5e13547a6740.png)

**Comment by skota** [comment]
Hmm!....i just clicked 'open an existing android studio project'.

Disclaimer: I am an absolute beginner with flutter. Pls ignore if my answer above is not relevant.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2923](https://github.com/flutter/flutter-intellij/issues/2923) via [**ZenHub**](https://www.zenhub.com/)
