### ISSUE TITLE
Feature request: network (request) inspection tool

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#17709]
It would be tremendously useful to have a network inspection tool to inspect network requests in Flutter. We use [Stetho](http://facebook.github.io/stetho/) for Android native to accomplish this. It integrates with Chrome's developer inspector tool and shows all requests in the network tab.

**Comment by QuirijnGB** [comment]
Hey, there already seems to be a plugin for exactly that
[https://pub.dartlang.org/packages/flutter_stetho](https://pub.dartlang.org/packages/flutter_stetho)

**Comment by zoechi** [comment]
@alanrussian does the suggested package satisfy your requirements?

**Comment by zoechi** [comment]
cc @cbracken (not sure this concerns you)

**Comment by zgosalvez** [comment]
Might be more helpful if it's already part of the Dart DevTools?

**Comment by jacob314** [comment]
This should be part of the Dart DevTools.
Here is the bug tracking that work. Please thumbs up the issue if it is useful. That is helpful for our prioritization particularly for this feature as the right solution will also require changes to the DartVM.
https://github.com/flutter/devtools/issues/368

**Comment by rknell** [comment]
Looks like the dart sdk side of the work will be available in the September 2020 milestone and the issue was completed yesterday:
https://github.com/dart-lang/sdk/issues/42952

**Comment by jonahwilliams** [comment]
Network profiler was added, closing issue
