### ISSUE TITLE
More documentation on PluginRegistry/Registrar/Registrant

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17703]
While helping someone debug why plugins handlers weren't registering when the binaryMessenger isn't the rootViewController (for iOS), it took me a while to read the code to understand what's the difference between the registry and the registrar and registrant etc. 

Can we add a diagram somewhere for how the code gen auto-wires the plugins or maybe some java/obj-cdoc at each of these interfaces that points out how it interacts with the other registr*?

cc @mravn-google

**Comment by xster** [comment]
Yes, a line at each of these sites that summarizes the relationships between them would be sufficient.

**Comment by Igorpi25** [comment]
> The interfaces and protocols already have (brief) documentation. Would adding something like
> 
> ```
> The generated registrant uses the registrar as a context for registering itself with the registry.
> ```
> help? Not sure a diagram would be of much use.


I tried to read text file from Flutter assets in Today Extension of iOS. I'm new in iOS and Swift(Objective-C surely). There is registrant.lookupKeyForAsset method for that. But how to get registrant in Today Extension? I'm some experienced in Android only, and this is not trivial for me. I'm still misunderstanding how does it work all, and how to get registrant. Please, show me example if you know how to. Thank you
