### ISSUE TITLE
TextFormField doesn't take into account UnderlineInputBorder

### ISSUE THREAD

**Issue by nicolashemonic** [flutter/flutter#17717]
## Steps to Reproduce

Hi guys,

I would like to change the color of the underline border of a text form field.
I have defined the text input's border with an UnderlineInputBorder but he doesn't take it into account.

```
TextFormField(
  decoration: new InputDecoration(
    labelText: 'email',
    border: UnderlineInputBorder(
      borderSide: BorderSide(
        color: Colors.blue,
        width: 1.0,
        style: BorderStyle.solid,
      ),
    ),
  ),
),
```

Below, the border should be blue instead of a default black color:

![fluttertextformfield](https://user-images.githubusercontent.com/1469457/40227384-a70953ce-5a8e-11e8-80ab-12d5dabe3d04.jpeg)

## Gist

[Find here the complete example](https://gist.github.com/nicolashemonic/9e83ad2f9570c328382949494837f902)

## Logs

```
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale fr-FR)
    • Flutter version 0.3.2 at /users/nicolas/flutter
    • Framework revision 44b7e7d3f4 (4 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • iPhone 5s • 5F509FCF-FC65-4B78-8925-DD83D7EB3A43 • ios • iOS 11.3 (simulator)
```

Thanks for your help !

**Comment by nicolashemonic** [comment]
I have simplified the example to demonstrate the presume bug.

**Comment by qomg** [comment]
￼![input_decorator](https://user-images.githubusercontent.com/11417472/40531097-dff7c342-602d-11e8-98ec-719e1caa9bde.png)
see... In order that u may modify source code.

**Comment by rolurq** [comment]
I also had the same problem, I resolved by looking at the source code of the `InputDecorator` and realize that the color in the border gets ignored, instead it uses the `hintColor` in the theme, you can see it [here](https://github.com/flutter/flutter/blob/48f4ff6ddab5520a6a761f4e6079c64000c16d29/packages/flutter/lib/src/material/input_decorator.dart#L1500)

**Comment by alanrussian** [comment]
Mulligan needs to change the color of the border on our input fields. Right now, we're doing a hacky workaround to wrap the input fields in a theme that overrides the color that's being used. Fixing this issue would be a much better solution to our problem.

**Comment by HansMuller** [comment]
This general issue has come up several times recently: #18751, #17592, #17717

I'm going to try and land a fix this week.

**Comment by alanrussian** [comment]
Thanks!

**Comment by luchichang** [comment]
hy guys did anyone get the answer of how to solve this??

if yes could you please explain it or add the resource link..
