### ISSUE TITLE
Only test ad showing in release apk but its showing normal ads in debug apk

### ISSUE THREAD

**Issue by Ajit121** [flutter/flutter#17714]
Implemented firebase admob. Replaced the appId and adUnitId with the my ids. Its showing only test default test ad of admob in the release apk but i'm able to see normal ads on debug apk.

**Comment by robertonic** [comment]
I'm having the same problem.  My debug build shows banner and interstitial ads.  The release build shows no ads.

I'm using the firebase_admob plugin.

I've built a release without obfuscation and the ads are still not shown so it isn't that.

Does anyone know how to step through a release build to get some idea what is causing this or have any other suggestions about a way to track the cause of the problem?

**Comment by FFGuerrero** [comment]
I have the same problem with ads, my application only show test ads, in release  i'm able to see ads.

Regards,

**Comment by iampawan** [comment]
Any Update on this? Everything works fine in debug mode but for me interstitial ads are not showing in release mode.

**Comment by yatindeokar** [comment]
I have the same problem, ads working fine on debug apk but not showing on released apk.  I'm using com.google.android.gms:play-services-ads:17.1.2 version.

**Comment by kyungjoongo** [comment]
same issue.

**Comment by Purus** [comment]
I had a strange one.. In debug mode, ads were not showing up (error code 3). But when in release mode, ads were showing up.

**Comment by zoechi** [comment]
@kyungjoongo 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by danielnguyen1401** [comment]
Same for me. Can you help us please !

**Comment by kyungjoongo** [comment]
Solutions?

**Comment by Ajit121** [comment]
For me it solved after cleaning flutter.  Just try this.

**Comment by kroikie** [comment]
@Ajit121

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/820. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by blasten** [comment]
This issue was moved to https://github.com/FirebaseExtended/flutterfire/issues/820
