### ISSUE TITLE
collapsed ExpansionTile vanishes when below ListView.builder is scrolled to end 

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#17716]
## Steps to Reproduce

```
TabBarView
  Column
    ExpansionTile
    Flexible
      Stack
        ListView.builder(reverse: true, ...)
        FAB
```     
![screenshot_1526635402](https://user-images.githubusercontent.com/405837/40227176-10076fce-5a8e-11e8-98e1-1850b00e583f.png)

![screenshot_1526635490](https://user-images.githubusercontent.com/405837/40227191-1874ba2c-5a8e-11e8-8de5-fa4b7b764168.png)

When I scroll up the ListView until the end is reached, the ExpansionTile vanishes (2nd Screenshot),
but only when the ExpansionTile is collapsed. 
When it is expanded, it doesn't vanish.

For debugging purposes I wrapped the ExpansionTile in a Container with `BoxConstraints(minHeight 108)` (~double the size of the closed ExpansionTile), then it also doesn't vanish.

## Logs

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
[✓] Connected devices (2 available)
```

**Comment by zoechi** [comment]
Can't reproduce with `reverse: false`,
but I want to keep `reverse: true` of course.

**Comment by zoechi** [comment]
Reproduction https://github.com/bwu-dart-playground/flutter_expansion_tile_listview_reverse

It behaves a little bit different then in the screenshots above.

![image](https://user-images.githubusercontent.com/405837/40233237-75c5b1d6-5aa2-11e8-92de-253e2bb6cbcf.png)

![image](https://user-images.githubusercontent.com/405837/40233240-7aa6f458-5aa2-11e8-9141-ce68bdfb0da9.png)

The `ExpansionTile` is not disappearing, but `Item 3` is appearing above the `ExpansionTile` even though the list is supposed to be below the `ExpansionTile`

**Comment by zoechi** [comment]
Works on `beta` (thanks to @xqwzts)

**Comment by zoechi** [comment]
also broken in 
```
[✓] Flutter (Channel master, v0.4.5-pre.43, on Mac OS X 10.13.4 17E202, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
[✓] Connected devices (1 available)
```

**Comment by zoechi** [comment]
`git bisect` led to

```
Author: Michael Goderbauer <goderbauer@google.com>
Date:   Fri May 4 10:48:06 2018 -0700

    Implicit a11y scrolling for iOS (and caching in Viewports) (#17021)

:040000 040000 d2d780742bbaeba8927ce9dd7970152b7d249ab2 3154719eb5620807f96e9bfe163d8f6b97c20a3c M      packages
```
@goderbauer

**Comment by goderbauer** [comment]
@zoechi I have https://github.com/flutter/flutter/pull/18410 out for review which fixes the issue in the repro case you posted. Let me know if that's not working for your original issue.

**Comment by goderbauer** [comment]
See also: #17426 and https://github.com/flutter/flutter/issues/18368, which are both caused by the same root cause.
