### ISSUE TITLE
BottomAppBar + FloatingActionButton + SnackBar

### ISSUE THREAD

**Issue by Peetz0r** [flutter/flutter#17712]
I have an app with a BottomAppBar with a FloatingActionButton docked on it.

When I create a SnackBar, the FAB animates upwards to make room, but it does so from the non-docked position. This is wrong.

This happens in my own app with flutter 0.3.2 and 0.4.4, and in the Ecample Gallery app.

See this video for the example app: https://vimeo.com/270610044

---

Also, the Material Guidelines suggest that we should display the SnackBar above the FAB in this case: https://material.io/design/components/snackbars.html#placement

But as far as I could find out, Flutter does not support this.

**Comment by xster** [comment]
cc @amirh

**Comment by amirh** [comment]
cc @DaveShuckerow

**Comment by DaveShuckerow** [comment]
We can take the repositioning logic out of the docked positions so it doesn't move relative to the snackbar, that should solve this issue.

If it turns out we draw the FAB on top of the snackbar, then we can reverse the order, but we should announce that before landing it.

@Peetz0r, if you're interested in contributing on this, you can take a look at the Floating Action Button Location class. The definitions for the two docked locations, end docked and center docked, contain logic for moving the FAB relative to the snackbar. Removing that logic should correct the behavior.

I'll be on vacation and won't be able to make any changes myself until I get back.

**Comment by AppleEducate** [comment]
@DaveShuckerow has there been any updates on this?

**Comment by sebbe1** [comment]
I'm curious, too. I'm so close to just implementing it by myself, because this bugs me so much.

**Comment by sebbe1** [comment]
Okay, I just implemented a very simplistic, but working solution:
`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/floatingSnackbar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:elevation="16dp"
    android:visibility="gone"
    app:layout_constraintBottom_toBottomOf="parent">
    <android.support.design.card.MaterialCardView
        android:layout_marginLeft="10dp"
        android:layout_marginRight="10dp"
        android:layout_marginTop="10dp"
        android:layout_marginBottom="100dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:backgroundTint="@color/colorBlack"
        app:cardCornerRadius="6dp">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">
            <TextView
                android:id="@+id/floatingSnackbarText"
                android:layout_marginLeft="15dp"
                android:textSize="16sp"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:text="@string/done"
                android:textColor="@color/colorPrimary"/>
            <Button
                android:id="@+id/floatingSnackbarButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@android:color/transparent"
                android:text="@string/undo"
                android:textColor="@color/colorAccent"
                android:textSize="16sp"/>
        </LinearLayout>
    </android.support.design.card.MaterialCardView>
</FrameLayout>`

Include this as a child of the root-element in the layout where you want it to show up. You may change the BackgroundTint of the MaterialCardView.

Then, in your activity:
`floatingSnackbar.visibility = View.VISIBLE
 floatingSnackbar.findViewById<Button>(R.id.floatingSnackbarButton).setOnClickListener {
        floatingSnackbar.visibility = View.GONE

        doAsync {
            database.taskDao().updateTaskDoneStatus(taskId, false)

            uiThread { refreshTasks() }
        }
    }

    val closeSnackbar = Runnable { floatingSnackbar.visibility = View.GONE }
    Handler().postDelayed(closeSnackbar, SNACKBAR_DURATION)`

For this code to work, you need to use Kotlin and [Anko](https://github.com/Kotlin/anko). Also you would need to set the `SNACKBAR_DURATION` as Long in Milliseconds. According to the [guidelines](https://material.io/design/components/snackbars.html#behavior) it should show up at minimum of 4 seconds and at maximum of 10 seconds.

**Comment by Hixie** [comment]
cc @HansMuller We have this bug in the gallery "bottom app bar" demo, too. When the FAB is docked, hitting one of the buttons makes the snack bar appear between the app bar and the FAB, forcing it to suddenly undock without animation.

**Comment by RaviKavaiya** [comment]
@zoechi sir, any update on this?

**Comment by green-Flamingo** [comment]
We are facing the same issue 😕

**Comment by JamesMcIntosh** [comment]
The behaviour parameter SnackBarBehavior.floating can be set either directly or in the Theme which will cause the snackbar to dodge the docked FAB and position itself above the menu.
```
Scaffold.of(context).showSnackBar(
  SnackBar(
    behavior: SnackBarBehavior.floating,
    content: Text("Message"),
  )
)

ThemeData.snackBarTheme.behavior
```

**Comment by TahaTesser** [comment]
Hi @Peetz0r 
Provided [solution](https://github.com/flutter/flutter/issues/17712#issuecomment-519499175)  in the above comment solves the issue

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
