### ISSUE TITLE
Allow Stack to contain Null children

### ISSUE THREAD

**Issue by phase** [flutter/flutter#17711]
When building a Stack, it's useful to allow objects to be null in the children for widgets that don't need
to be rendered. My current use case is adding a login widget over my main app by stacking it on top,
but I can't directly include my `loginWidget` in the `children: <Widget>[]` list because a Stack doesn't
allow null children inside the list. (I got around it by constructing the list outside of the stack and adding
the login widget to the stack if it's not null.)

The error points to these lines of code:

https://github.com/flutter/flutter/blob/e4b574d3d3c211d9fa2c44f2f862617b6075b708/packages/flutter/lib/src/widgets/framework.dart#L1654-L1657

My hope would be to skip over any null objects and not render them.

**Comment by zoechi** [comment]
You can use `children: [...].where((c) => c != null).toList()` to filter out `null`s yourself.

It might be more comfortable if the framework does this for you, but then the cost for this checks can't be avoided, even when you're sure you never pass `null`.

**Comment by phase** [comment]
That's a beautiful solution!

Similar question, what would to recommend for only assigning an optional argument if a variable isn't
null? I've got a Scaffold and I want to set the `bottomNavigationBar` only if a field isn't null. Currently
`bottomNavigationBar: theField` isn't throwing any error but I want to be sure that it's safe for the future.

**Comment by phase** [comment]
Ah, excellent! Thanks for the help!

**Comment by Ivaskuu** [comment]
You can also do `widget ?? new Container()` where it passes a Container if the widget is null (a Container alone doesn't have a form).

**Comment by alexdacoda** [comment]
well but in a Row() where you set mainAxisAlignment to spacebetween it does and it just ruins my UI is there no other fix
