### ISSUE TITLE
assertion was thrown building FutureBuilder

### ISSUE THREAD

**Issue by hoichong** [flutter/flutter#17728]
I am trying to learn Flutter, by developing an App, here is the code I tried,

```dart
Future<User> fetchUser(http.Client client) async {
  final response =
      await client.get('https://backend-server/api/v1/users/getMyUser');
  final responseJson = json.decode(response.body);

  return new User.fromJson(responseJson);
}
```

myClient is a Client returned from an OAUTH2 auth session.
I am trying to use a delay of 5 seconds before calling fetchUser(myClient)

```dart
class TestUser extends StatelessWidget {

  Future<User> delayfetchUser(int timeInSec) async {
    await new Future.delayed(Duration(seconds: timeInSec));
    return fetchUser(myClient);
  }

  @override
  Widget build(BuildContext context) {
    Widget textofUser = new Center(
      child: new FutureBuilder<User>(
        future: delayfetchUser(5),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return new Text(snapshot.data.firstName);
          } else if (snapshot.hasError) {
            return new Text("${snapshot.error}");
          }

          // By default, show a loading spinner
          return new CircularProgressIndicator();
        },
      ),
    );
    return textofUser;
  }
}
```

Hit this error, when trying the code above...

I/flutter (17728): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17728): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17728):   https://github.com/flutter/flutter/issues/new
I/flutter (17728):
I/flutter (17728): When the exception was thrown, this was the stack:
I/flutter (17728): #2      new Text (package:flutter/src/widgets/text.dart)
I/flutter (17728): #3      TestUser.build.<anonymous closure> (file:///E:/workspaces/mw3o_ess_4/lib/main.dart:306:24)
I/flutter (17728): #4      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
I/flutter (17728): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3722:27)
I/flutter (17728): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)

**Comment by jonahwilliams** [comment]
@hoichong It looks like your error message got cut off a bit.  But my guess is that `snapshot.data.firstName` is null?

**Comment by hoichong** [comment]
Yes, that is the cause of the error.
