### ISSUE TITLE
Feature Request: Google Maps Plugin add InfoWindowClickListener and Resize

### ISSUE THREAD

**Issue by gerryhigh** [flutter/flutter#17730]
I need the ability to get notified when a user clicks on an info window in the package https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter. Currently it appears you can only get an event when they click on the marker and not the info window. In my kotlin app I've done it via setting setOnInfoWindowClickListener on the map.

Also, in order to handle rotation events I need the ability to resize the map.  Currently it appears that there is only the ability to set the size at construction time.

@mravn-google @mit-mit 

Thanks!

**Comment by gerryhigh** [comment]
FWIW I've implemented the setOnInfoWindowClickListener to get callbacks in flutter when the user clicks on the Info Window. That was pretty trivial. Eventually I'll post the code/PR; ping me in the interim if interested.

I'm currently working on the map resize feature.

**Comment by mravn-google** [comment]
PRs are most welcome, especially for additions to the `GoogleMapController` API such as responding to extra touch events.

For PRs that make platform overlays work in more situations, please keep it *as simple as possible*. Platform overlays are not the long-term solution to integrating Google Maps, and we'd very much like to avoid throwing a lot of effort and complex code into this dead end.

**Comment by gerryhigh** [comment]
@mravn-google @mit-mit Any idea when this pull request will get looked at? https://github.com/flutter/plugins/pull/594

**Comment by mravn-google** [comment]
@gerryhigh Sorry, I somehow overlooked this PR.

**Comment by iskakaushik** [comment]
Looks like this has merged.
