### ISSUE TITLE
RefreshIndicator onRefresh doesn't get called until the screen is on top of stack

### ISSUE THREAD

**Issue by jyygu** [flutter/flutter#17733]
We are using RefreshIndicator to show that data is loading.  This can be triggered by some user action other than pull-to-refresh.  (Using it as described here: https://docs.flutter.io/flutter/material/RefreshIndicatorState/show.html)  The user action can take place on another screen while the screen that contains RefreshIndicator is in the back stack and just listening on a value stream emitted by the user action.

The problem is when the RefreshIndicator is not on top of the stack, its onRefresh callback doesn't get called until we pop to that screen.  This results in RefreshIndicator being displayed very short duration (less than a second) because the callback essentially immediately returns.

Why is the callback not occurring right away?  If callback is called even while in back stack, then when we pop back to the screen, the indicator will be still be shown only if the loading truly hasn't finished.

**Comment by darshankawar** [comment]
Hi @jyygu,
Can you please confirm if you still experience this issue on latest Flutter version (eg: dev, master) ?
Thanks.
