### ISSUE TITLE
Log when users try to put an IgnorePointer immediately under a GestureDetector with default behavior

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#17736]
Let's say you have tappable widget A. In some situations, I want a separate tap handler such that A doesn't receive the tap event. My instinct is to come up with the following combination of widgets:

- GestureDetector
     - IgnorePointer
          - A

However, I have learned (after some time) that `GestureDetector`'s default `GestureDetector.behavior` tests for hits on the child. If your child is an `IgnorePointer`, the `GestureDetector` is effectively pointless. Can the framework log if a user tries to create this combination of widgets? I think it would save developers some time.

**Comment by iapicca** [comment]
Hi @alanrussian 
does this [code sample](https://dartpad.dev/e4ddf85b03943733454c1e62d89c3c50) represent the issue you are describing?
thank you

**Comment by alanrussian** [comment]
I don't remember anything here other than my original post, sorry.

**Comment by iapicca** [comment]
Hi @alanrussian 
given your last message and since the code appears to work as intended
I'm closing the issue.

If you disagree please write in the comments and I will reopen it
Thank you
