### ISSUE TITLE
Confusing warning from flutter command

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#17748]
I ran "flutter upgrade" today (previous time was a few days ago). I got a WARNING. The problem seems to be that the beta channel is over 29 days old. Devon suggests that we increase 29 to something like 60 or so (two typical release cycles).

Here's the output:

```
wmleler$ flutter upgrade
Upgrading Flutter from /Users/wmleler/Dart/flutter...
From https://github.com/flutter/flutter
   8a83d0df7..8717a5e6f  master     -> origin/master
Already up to date.

Upgrading engine...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 29 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
 ╚════════════════════════════════════════════════════════════════════════════╝

Already up-to-date.

Flutter 0.3.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 44b7e7d3f4 (4 weeks ago) • 2018-04-20 01:02:44 -0700
Engine • revision 09d05a3891
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Similar to #12991

**Comment by mcfarljw** [comment]
I've seen this pop up again recently too, might also be related to:

https://github.com/flutter/flutter/issues/15862
https://github.com/flutter/flutter/issues/14920

**Comment by DanTup** [comment]
I think it'd be better to make this a real update check than just bump the number of days. We could use GitHub or the JSON that serves the [archive page](https://flutter.io/sdk-archive/) to find out what the latest version if (and the release date)?

**Comment by DanTup** [comment]
I think this was just a bug - there was already code to check the git remotes for newer versions, but it always picked the `master` branch if you're weren't on the `alpha` channel. I've opened a PR that I think should fix it:

https://github.com/flutter/flutter/pull/18016

It should stop any warnings about out-of-date flutter if the remote for your channel (assuming it's alpha/beta/dev) doesn't actually have any updates.

**Comment by DanTup** [comment]
#18016 has been merged, so you shouldn't see this warning going forwards if there isn't a newer version for your channel (of course, you may still see it on the current beta channel until after it includes this change).
