### ISSUE TITLE
Android Studio - flutter TODO issue

### ISSUE THREAD

**Issue by Servo97** [flutter/flutter#17753]
When I open an existing project with some TODOs in it and click on a TODO from the taskbar below, the studio refreshes kind of, saying "updating indices" again and again. If I don't click on a TODO and directly run the app, this doesn't happen till I click on the TODO.
This only occurs when opening the app for the first time. As many courses online give out TODOs to the students, this is a troubling issue, albeit a tiny one.

**Comment by zoechi** [comment]
What kind of "TODOs" are you talking about?
Please also add the output of `flutter doctor`?

**Comment by Servo97** [comment]
I am running flutter on android studio. I can't seem to run flutter commands inside the studio terminal. i am attaching a screenshot of the 'TODOs' I was talking about.
<img width="698" alt="capture" src="https://user-images.githubusercontent.com/22110708/40279868-ef90f298-5c67-11e8-8dc2-51a844e0aa96.PNG">

**Comment by JonathanSum** [comment]
@Servo97 
Do you see the word "Terminal" in the photo that you posted? Could you click it and run a flutter commands "flutter doctor" for zoechi's request?

**Comment by Servo97** [comment]
I tried doing that first, it didn't work. Says flutter isn't recognized as an internal or external command.
This doesn't mean I don't have flutter. I have created 4 mini apps now, just that every time I try to open the app for the first time and click on the TODO button, studio goes into that weird state.

**Comment by JonathanSum** [comment]
You need to install flutter and set the environment variable. 
The guideline is here=> [guideline ](https://flutter.io/setup-windows/)

Or I can help you personally. Just tell me that you downloaded flutter or not before on your computer and where it is.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
