### ISSUE TITLE
RefreshIndicator stops spinning when displaying for more than 6 seconds

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#17757]
Attempting to show a RefreshIndicator for an extended period of time (more than 6 seconds, in my testing) results in it stopping spinning.

How to reproduce: 
Change the Timer's duration in line 29 in https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/overscroll_demo.dart to something more lengthy like 30 seconds.

**Comment by najeira** [comment]
same as #13782

**Comment by goderbauer** [comment]
Dup of https://github.com/flutter/flutter/issues/17923.
