### ISSUE TITLE
Support For Nano HTTPD

### ISSUE THREAD

**Issue by gaurav1999** [flutter/flutter#17752]
Hello Everyone,
Is it possible to use embed Nano HTTPD in FLutter Applications ?

**Comment by zoechi** [comment]
Sure. You can make it available to Dart by building a plugin.
You can also use the Dart `shelf*` packages to create an HTTP server in plain Dart code (or just use `dart:io`.

**Comment by gaurav1999** [comment]
Thank you for your valuable suggestions , @zoechi , 
Sir can you please also tell how can I start with plugins , I have never built any plugin , I am really excited to contribute.

**Comment by zoechi** [comment]
https://flutter.io/platform-channels/
