### ISSUE TITLE
 How to connect flutter app with flask server because i want to excess rethinkdb

### ISSUE THREAD

**Issue by hunnain** [flutter/flutter#17751]
How to connect python-flask server with flutter app.Please help me hot connect server with flutter app.

**Comment by zoechi** [comment]
https://flutter.io/cookbook/networking/fetch-data/

**Comment by hunnain** [comment]
so in this way i will send and get data from flask server

**Comment by zoechi** [comment]
yup

**Comment by zoechi** [comment]
I assume this issue is obsolete.
Please don't hesitate to comment on the bug if you think it should be reopened.
Thanks for your contribution.
