### ISSUE TITLE
My app suddenly failed starting up, leaving just white screen

### ISSUE THREAD

**Issue by hanzhida** [flutter/flutter#17754]
It shows the following log in the console

> Built build\app\outputs\apk\debug\app-debug.apk (27.4MB).
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(29937): onResume setting current activity to this
E/flutter (29937): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
E/flutter (29937): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(104)] Could not launch engine in configuration.
Syncing files to device MI 5...

I didn't change any configuration of the environment.
I'm sure there is the entry function of "main" in my main.dart
`void main() => runApp(new MyApp());`

Uninstalling the app does not solve this issue. Maybe my flutter environment is broken? 
Why this happens, how to fix it?

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by kaseggie** [comment]
having the same issue

`Kavans-MBP:quiz_app kavan$ flutter doctor -v
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale en-GB)
    • Flutter version 0.3.2 at /Users/kavan/Code/flutter
    • Framework revision 44b7e7d3f4 (4 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/kavan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • iPhone X • 3E169B8F-9401-4162-A2F1-3E7FFD6308A0 • ios • iOS 11.3 (simulator)

! Doctor found issues in 1 category.`

**Comment by zoechi** [comment]
`flutter clean` might be worth a try

**Comment by newfivefour** [comment]
I had this error on os x with vs code. I had a bunch of errors but "Could not launch engine in configuration." was the last one. I did clean and then rerun and it worked fine.

**Comment by zoechi** [comment]
Can this issue be closed?
Anyone still encountered this recently where `flutter clean` didn't help?
There is another issue about `flutter clean` being required too often.

**Comment by MasseElch** [comment]
I still do where only removing the app from the device does help. First start always works, but when i restart / hot restart the app i get a white screen. 

Adding a `print` in the `main` function is not called on every attempt after the first one.

**Comment by MasseElch** [comment]
Well, i did provide some more information. What more do you need? Please tell and im happy to provide any information needed.

**Comment by MasseElch** [comment]
Nevermind, i somehow managed to not catch an failing future before my `runApp()` in the `main` function. Error is gone.

**Comment by Hixie** [comment]
@MasseElch sorry, the bot only looks at the person who originally filed the bug! Please file a separate bug if you still have any issues!

**Comment by ch-muhammad-adil** [comment]
it gets stuck there, but while it is stuck by doing hot reload it just work fine.

**Comment by SagarPanwala** [comment]
still facing the issue. Can any one please tell me how can I provide logs ?
I'm using VS Code.
Flutter Doctor shows no working. Tick marks for all items.

**Comment by alex9153** [comment]
in terminal "flutter build ios --release" removes white screen

**Comment by add118** [comment]
I have been having this same issue with some apps. I still haven't found the problem. I've tried all the above solutions. If I find an answer I will post it here.

**Comment by pratikbutani** [comment]
I got same problem yesterday and I have tried all the solution. 

Finally I got the solution as I have added `--no-shrink` in command of building apk.

    flutter build apk --no-shrink

Hope it will work.

Thank you.

**Comment by aysayabakaro** [comment]
@pratikbutani 

where did you put it? Im having the same issue, thanks.

**Comment by pratikbutani** [comment]
> @pratikbutani
> 
> where did you put it? I'm having the same issue, thanks.

When you go for the build, you need to put that option.
