### ISSUE TITLE
`flutter test` exits with exit code `1` if there are no tests

### ISSUE THREAD

**Issue by lwasylkowski** [flutter/flutter#17760]
As stated in the title, `flutter test` properly recognises no tests, but returns with exit code `1` instead of `0`. I feel it no tests should count as _no tests failed_ and return successfully -- this is useful if one wants to have CI pipeline ready before the tests are written. Currently pipeline would fail, at least for the simplest setup which checks return code of `flutter test` (which was suggested in some other issue I think).

```
▶ flutter test ; echo $?
Test directory "test" not found.
1
```

Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
[✓] VS Code (version 1.23.0)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
Personally, if I'd added `flutter test` to a CI script and it "passed" when the tests weren't found, I'd be a bit upset. If I told you to run tests and you couldn't find them, that seems like an error condition. What's the reason you want to call `flutter test` without any tests?
