### ISSUE TITLE
InputField can not get the input value.

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#17764]
Here is the code:

```
new InputField(
                              name: '账号',
                              hintText: '注册时的用户名',
                              textInputType: TextInputType.emailAddress,
                              onEmpty: '账号必须',
                              icon: Icons.account_circle,
                              obscureText: false,
                              onSaved: (String value) {
                                setState(() {
                                  _username = value;
                                });
                              },
                            ),
```
Simple enough, but the _username always be none (_username is set local global variable). What is wrong?

**Comment by najeira** [comment]
What is InputField, did you made it? Paste whole code including InputField.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
