### ISSUE TITLE
Merge flutter refresh and flutter start

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1776]
- [ ] Track all the dependencies and their timestamps when building the snapshot, FLX, and APK, as well as the identity of the connected device(s)
- [ ] On start, for each device, figure out the minimum amount of work required to get the device into an up to date state.
- [ ] Add a `--force` argument to force a full refresh.

cc @devoncarew, @jason-simmons since they were just talking about this

**Comment by danrubel** [comment]
This has been superseded by hot reload and hot refresh - and `flutter refresh` has been removed.
