### ISSUE TITLE
Is there any option to dynamically create instance of class?

### ISSUE THREAD

**Issue by asstet** [flutter/flutter#17766]
Hey, there's the question – could I create class instance if I have string variable which contains its name?
For example, i have 
`var className = 'DocumentsList';`, 
could I do something like this 
`var docListWidget = createInstance(className[, params]);`

**Comment by zoechi** [comment]
There is currently no such thing in Dart. 
You could create a map from strings to factory methods like

```dart
var factories = <String, Object Function()>{'Foo', () => new Foo(), 'Bar', () => new Bar()};

String name = 'Foo';
Object instance = factories[name]();
```

**Comment by LaksCastro** [comment]
Currently you can also:
```dart
T? createInstanceOf<T>() {
  final factories = <Type, T Function()>{
    Foo: () => Foo() as T, 
    Bar: () => Bar() as T,
  };
  
  final createInstance = factories[T];

  return createInstance?.call(); // Same as createInstance() but null safety
}
```

<samp>[DartPad Preview](https://dartpad.dev/f10661370488191b57ab064fc1fe217d?null_safety=true)</samp>
