### ISSUE TITLE
Intermittent errors running "flutter build apk"

### ISSUE THREAD

**Issue by MaikuB** [flutter/flutter#17769]
See attached log

[flutter_01.log](https://github.com/flutter/flutter/files/2022437/flutter_01.log)

**Comment by zoechi** [comment]
Is this still an issue with recent Flutter versions?

**Comment by MaikuB** [comment]
I've not run it recently for a while so will have to get back to you on that

**Comment by MaikuB** [comment]
Haven't run into this lately so am going to close this and open an issue if it happens again
