### ISSUE TITLE
whenever i ran flutter_ble_lib example, this is what i get and i dont understand

### ISSUE THREAD

**Issue by aidooyaw1992** [flutter/flutter#17774]
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (23288): The following assertion was thrown while handling a gesture:
I/flutter (23288): type 'Future<dynamic>' is not a subtype of type 'Future<Null>' where
I/flutter (23288):   Future is from dart:async
I/flutter (23288):   Future is from dart:async
I/flutter (23288):   Null is from dart:core

**Comment by Hixie** [comment]
Do you have code showing the problem?

**Comment by zoechi** [comment]
Sounds like relative imports in `lib/main.dart`
See also https://github.com/dart-lang/sdk/issues/32601
