### ISSUE TITLE
Material Switch shouldn't bounce like a pinball

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#17773]
![img-1934 1](https://user-images.githubusercontent.com/1227763/40320075-3b1853ba-5cdf-11e8-9761-1c9531c86952.gif)

See video above: When a switch is given momentum with a flick it should probably not bounce off the opposite wall like a pinball.

**Comment by eseidelGoogle** [comment]
Are you sure @abarth didn't add this as an easter egg? :)

**Comment by abarth** [comment]
Woah.

**Comment by cbracken** [comment]
Was able to repro (though, to be honest, I'm not certain how) on an iPhone 4s in the settings page of the new gallery.

**Comment by goderbauer** [comment]
For me it repros pretty reliably if I start the flick at the far end of the switch and move my finger towards the other side with momentum and then lift it just before the finger reaches the other end of the switch.

**Comment by goderbauer** [comment]
@eseidelGoogle This is the [Switch from Material](https://docs.flutter.io/flutter/material/Switch-class.html), not the [CupertinoSwitch](https://docs.flutter.io/flutter/cupertino/CupertinoSwitch-class.html). I can't repro this with CupertinoSwitch.

**Comment by eseidelGoogle** [comment]
Oh, you're right.  My bad.

**Comment by eseidelGoogle** [comment]
Both switches seem to respect scroll velocity. e.g. you can get the heads to move slower by doing flick scrolls.  Not sure if that's desirable either?

**Comment by AppleEducate** [comment]
I created this issue a while back for this already. #16800

https://github.com/flutter/flutter/issues/16800
