### ISSUE TITLE
Fuchsia needs font fallback for emojis

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#17786]

**Comment by Hixie** [comment]
We need font fallback in general.

**Comment by Hixie** [comment]
Done!

**Comment by sroddy** [comment]
Sorry @Hixie when you say done, what do you exactly mean? Is it now possible to specify a list of fallback fonts somehow?

**Comment by Hixie** [comment]
@jason-simmons can elaborate, I believe.

**Comment by jason-simmons** [comment]
Flutter currently does not support specifying a list of fallback fonts.  The fix for this bug added logic to Fuchsia's font manager that looks up a fallback font for emoji characters.
