### ISSUE TITLE
Fuzzy rendering with `Picture.toImage()`

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#17782]
I would expect the following code to render three identical images.  Instead, the font icon and the canvas render look (nearly) identical, but the version using `Picture.toImage()` and a custom `ImageProvider` is fuzzy.  I've tried some different changes in flutter/engine to use a custom SkPaint (e.g. with antialiasing on or off) here https://github.com/flutter/engine/blob/master/lib/ui/painting/picture.cc#L34 but haven't come up with anything that fixes it (although it might be nice to let callers pass in their own `Paint` to be used with that method).

Here's the rendered output of the code below:

![image](https://user-images.githubusercontent.com/8620741/40328767-7e9b8400-5d15-11e8-84ba-e07c80df5058.png)

From top to bottom: using `Picture.toImage()`, using a `CustomPainter`, and using `Icon` with the material icon font.  The custom painter is slightly off from the Icon, but close enough for my taste. The Picture.toImage is terrible.

Similar code in a Skia fiddle looks like this https://fiddle.skia.org/c/7350bdbb4191997e2444f135ab7c5502 which is closer to the icon/painter.

```
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

Path get sendPath => new Path()
  ..moveTo(2.01, 21.0)
  ..lineTo(23.0, 12.0)
  ..lineTo(2.01, 3.0)
  ..lineTo(2.0, 10.0)
  ..relativeLineTo(15.0, 2.0)
  ..relativeLineTo(-15.0, 2.0)
  ..close();

Paint get blackPaint => new Paint()..color = const Color(0xFF000000);

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Image(image: new InMemoryImageProvider()),
            new SizedBox(
                width: 24.0,
                height: 24.0,
                child: CustomPaint(painter: new SendPainter())),
            new Icon(Icons.send),
          ],
        ),
      ),
    );
  }
}

class SendPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawPath(sendPath, blackPaint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}

class InMemoryImageProvider extends ImageProvider<String> {
  ui.Image getImage() {
    var rec = new ui.PictureRecorder();
    var canvas = new Canvas(rec);
    canvas.drawPath(sendPath, blackPaint);
    var picture = rec.endRecording();
    return picture.toImage(24, 24);
  }

  @override
  ImageStreamCompleter load(String key) {
    return new OneFrameImageStreamCompleter(
        Future.value(
          new ImageInfo(
            image: getImage(),
          ),
        ), informationCollector: (StringBuffer information) {
      information.writeln('Image provider: $this');
      information.write('Image key: $key');
    });
  }

  @override
  Future<String> obtainKey(ImageConfiguration configuration) {
    return Future.value('test');
  }
}
```

**Comment by dnfield** [comment]
My actual use case is to implement some custom image providers for SVG rendering.  But when I go to do that, I'm seeing great variance in image quality, especially with smaller image sizes.

**Comment by dnfield** [comment]
I added some more code to dump the `Image.toByteData()` out to disk and note the same artifacts/fuzziness.  It seems like something's up with the `toImage()` call.

**Comment by tvolkert** [comment]
This may be a confusion of logical vs physical pixels.  @dnfield what happens if you multiply your desired image width and height by `ui.window.devicePixelRatio`?

**Comment by dnfield** [comment]
If I do that I just get a wider/taller image with the fuzzy send icon in the top left.  

I've tried scaling the image up and down and it doesn't really make a difference - although at higher resolutions the effect is less pronounced; for example, if I scale the canvas and image dimensions by 10x (so 240x240 instead of 24x24), there's very little perceptible difference.

I'm wondering if this is a Skia issue - for instance, if there's something at the smaller dimensions that's forcing lines to be drawn off of pixel offsets and forcing some weird antialiasing to happen somewhat like this (https://groups.google.com/forum/#!topic/skia-discuss/-u0O2WY3tqI - but that issue has to do with strokes rather than fills, I'm seeing this with fills).

**Comment by tvolkert** [comment]
In order to help diagnose this, can you capture an SKP screenshot using:

    flutter screenshot --type=skia --observatory-port=<port>

And attach a ZIP file containing the screenshot here?

Thanks!

**Comment by dnfield** [comment]
[flutter_01.skp.zip](https://github.com/flutter/flutter/files/2024517/flutter_01.skp.zip)

**Comment by tvolkert** [comment]
So that SKP does show that it's scaling up from a 24x24 image using `SkCanvas::drawImageRect()`

**Comment by dnfield** [comment]
> So that SKP does show that it's scaling up from a 24x24 image using SkCanvas::drawImageRect()

The original `Path` is 24x24 - so is the icon font.  The destination and source are both 24x24 if I understand that right.  I don't think the image is getting scaled (at least not after it's drawn).  Even if I save the image using `toByteStream()` I'm still seeing the pixelation.

**Comment by dnfield** [comment]
for instance `skp_parser flutter_01.skp data/1 > send.png` shows the same fuzzy png image.

**Comment by tvolkert** [comment]
The issue is that when you use a `CustomPaint`, it hands you a `Canvas` that's already scaled for the display.  The `Canvas` you create from scratch isn't, so you need to manually apply that scale:


```dart
  ui.Image getImage() {
    var rec = new ui.PictureRecorder();
    var canvas = new Canvas(rec);
    var dpr = ui.window.devicePixelRatio;
    canvas.scale(dpr, dpr);
    canvas.drawPath(sendPath, blackPaint);
    var picture = rec.endRecording();
    return picture.toImage((24 * dpr).ceil(), (24 * dpr).ceil());
  }
```

That'll give you an `Image` that's appropriately scaled.  Then you need to size it back down when you lay it out:

```dart
            new SizedBox(
                width: 24.0,
                height: 24.0,
                child: new Image(image: new InMemoryImageProvider()),
            ),
```

@Hixie this feels clunky at best.  Thoughts?

**Comment by dnfield** [comment]
This is closer but still not quite it - the SizedBox just cuts off the edges of the picture, it doesn't actually rescale it.  

Testing out rescaling the image in the `MakeFromPicture` call...

**Comment by Hixie** [comment]
This all seems to be working as intended. If you want to do vector graphics that handle scales well, don't convert to a bitmap (as with `toImage`). Just use the Picture directly.

**Comment by tvolkert** [comment]
I'm gonna close this then.  @dnfield feel free to re-open if you have suggestions as to how this could be made easier to work with.

**Comment by dnfield** [comment]
You can size the image back down by using the `width` and `height` properties on the image as well:"

```
new Image(image: new InMemoryImageProvider(), width: 24.0, height: 24.0),
```

It might be nice to be able to pass an optional flag to the `PictureRecorder` constructor that could handle this a little more transparently - I suspect that you may still see people trying to create images of their widgets and wondering why they don't look as good.  I'll create a PR at some point and we could discuss its merits there.

**Comment by nsreenath** [comment]
Scaling up the canvas by device pixel ratio and scaling down the image while rendering fixes the issue I mentioned in this comment: https://github.com/flutter/flutter/issues/16274#issuecomment-390056640
But some more transparency in the process, as @dnfield mentioned, would be nice.

**Comment by Florence2016** [comment]
if your still having pixelated image just increase the pixelRatio like this
(--sample saving image) 

    ui.Image image = await boundary.toImage(pixelRatio: 6.0);

**Comment by skquo** [comment]
> ```dart
>     var dpr = ui.window.devicePixelRatio;
> ```

Hi @tvolkert, is there any different between yours and this code

```dart
ui.Image getImage() {
    var rec = new ui.PictureRecorder();
    var canvas = new Canvas(rec*ui.window.devicePixelRatio);
    canvas.drawPath(sendPath, blackPaint);
    var picture = rec.endRecording();
    return picture.toImage(24, 24);
  }
```

**Comment by Annotium** [comment]
Hi all, I found out if we using this method to generate image with correct device pixel ratio, now the output image becomes very big, e.g 1000x2000 image with dpr 3 now becomes image with 3000x6000 and I want to save the image to file, the device crashed now.

Is there a way to work around the problem, resize???

**Comment by undefdev** [comment]
It would still be a good idea to fix `Picture.toImage`, as it is pretty useless with the current behavior.

**Comment by jdevp** [comment]
Please fix the issue with ​`Picture.toImage`. If the fuzzy issue is caused by canvas created from scratch, then there should be an option to associate canvas with dpr.  I did try to use Picture itself instead of bitmap but `canvas.drawPicture` seems to consume a lot of memory and freezes the app.

**Comment by jdevp** [comment]
Since there is already an option for dpr for `RenderRepaintBoundary.toImage(pixelRatio: dpr) `, hopefully it is not too hard to add the same option to `ui.PictureRecorder().toImage(width: width, height: height)`.  If someone is interested, I reported `canvas.drawPicture` issue here (https://github.com/flutter/flutter/issues/84571). This is a show stopper for me to release my app for now because the bad image quality rendered.

**Comment by jdevp** [comment]
I have fixed the image fuzzy issue by scaling up and down the image as mentioned by @tvolkert but it would be still nice to have an API `ui.PictureRecorder().toImage(width: width, height: height, devicePixelRatio: dpr)`
