### ISSUE TITLE
Expanding toolbar does not account for scroll-position when going back

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1778]
Open the gallery
Navigate to the components
Scroll down a bit
Click on a demo
Click back
Be surprised that the toolbar is expanded, despite the demos being scrolled.

![screen](https://cloud.githubusercontent.com/assets/11857803/12985686/bb71e7bc-d0a8-11e5-8b13-ee798d3bf2e8.png)

**Comment by abarth** [comment]
@HansMuller
