### ISSUE TITLE
MaterialApp ThemeData iconTheme color is ignored

### ISSUE THREAD

**Issue by Mythar** [flutter/flutter#17799]
MaterialApp
-theme: ThemeData
--iconTheme: IconThemeData
---color <- is being ignored
---opacity <- works
---size <- works

**Comment by HansMuller** [comment]
Could you provide an example that demonstrates this problem?

**Comment by Mythar** [comment]
```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        iconTheme: new IconThemeData(
            color: Colors.blue,
            opacity: 1.0,
            size: 50.0
        ),
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      drawer: new Drawer(
        child: new ListView(
          children: <Widget>[
            new ListTile(
              title: new Text('Some text'),
              trailing: new Icon(Icons.search),
              onTap: () => null,
            )
          ],
        ),
      ),
      body: new Center(
        child: new ListView(
          children: <Widget>[
            new ListTile(
              leading: new Icon(Icons.search),
              title: new Text('Some Text'),
              trailing: new Icon(Icons.print),
              onTap: () => null,
            ),
            new Icon(Icons.cancel),
          ],
        ),
      ),
    );
  }
}

```
The iconTheme color is inherited in the ListView, but not in the rest of the classes, however opacity and size are inherited in all classes

**Comment by HansMuller** [comment]
Most of the ListTile visual defaults are configured with the inherited ListTileTheme.

The default IconTheme iconColor is black, but in ListTiles the default is supposed to be grey (Colors.black45). So if a ListTileTheme.iconColor isn't specified we don't default to the IconTheme's iconColor, we default to grey.

You can get the effect you want by wrapping the Scaffold and the Drawer with:

```
new ListTileTheme(
  iconColor: Colors.blue,
  child: ..
)
```

**Comment by zoechi** [comment]
I assume the problem is solved by HansMullers comment.

**Comment by ivenxu** [comment]
> Most of the ListTile visual defaults are configured with the inherited ListTileTheme.
> 
> The default IconTheme iconColor is black, but in ListTiles the default is supposed to be grey (Colors.black45). So if a ListTileTheme.iconColor isn't specified we don't default to the IconTheme's iconColor, we default to grey.
> 
> You can get the effect you want by wrapping the Scaffold and the Drawer with:
> 
> ```
> new ListTileTheme(
>   iconColor: Colors.blue,
>   child: ..
> )
> ```

Is there anyway, we can get such inherited information via Dart DevTools?
