### ISSUE TITLE
From now on, Flutter using a third-party library is a great pain to me

### ISSUE THREAD

**Issue by bravekingzhang** [flutter/flutter#17791]
When I want to use some third party SDK into my flutter project，I met a problem that I can't across！
 such as [Tencent IMSDK](https://cloud.tencent.com/product/im#sdk), they provides both Android and IOS version。

1. as you know , **I am not familiar with IOS development**，so ,if I want to use the SDK, I count only able to encapsulate the android part, SO I HAVE TO  look for a person who skill at IOS and Willing to help me encapsulate the IOS part, But also he has time, etc。

2. **Tencent IMSDK** offer us lots of functions ,most of the function is useful to me ,so if I  encapsulate all the funciton into **method_channel** ,it is really a **boring wok**,so I think method channel is not a friendly way to use third party,
3. Would you provide use some more friendly way to use third-party libraries in future features？

**Comment by hnvn** [comment]
Platform Channel feature is the very elegant way to deal with the matter of integrating third-party platform-specific library. Flutter is just a 'client' dedicating for UI render and living on the 'host' Android or iOS system.

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/7053 might make it easier in some cases if it will be implemented.

**Comment by zoechi** [comment]
I'm sure the Flutter team is aware that this should be made easier.
I think this issue is to broad though and not actionable and I am going to close it.
If you have more concrete issues that you think need to be fixed or improved, please create new issues.
Thank your for your contribution.
