### ISSUE TITLE
Barcode scanner plugin

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#17796]
Hello there

I wanted to know if you're interested into a barcode scanner plugin for flutter. I'm working on one and as it will use most of the camera plugin will be nice to be able either to merge it a make it an official plugin or have a way to extends the camera plugin from an external plugin instead of duplicate everything ^^

What do you think ?

**Comment by rmathias86** [comment]
Already exists a barcode scanner plugin 
https://pub.dartlang.org/packages/barcode_scan

**Comment by rmathias86** [comment]
I got it...
I'm willing to modify the current camera plugin as well, it is asking to use Android SDK 21 and I would like to make it work with Android SDK 16 at least.

**Comment by jaumard** [comment]
Same for me =(

**Comment by henrik-d** [comment]
I would very much appreciate such a plugin. Currently I have my own solution but it is limited and error-prone.

**Comment by faspadaro** [comment]
I appeciate this plugin too. 
Could you add button on camera menu for dismiss camera ? 
Imagine user start scan but change your mind and he wants to back to main, how he can do it ?
On Android he can do it by back button but on ios no.

**Comment by DinoSane** [comment]
Does anyone went further on this? Use the Android SDK 21 just to use camera is a problem indeed

**Comment by jaumard** [comment]
Fixed by https://pub.dev/packages/flutter_camera_ml_vision
