### ISSUE TITLE
I wanted to know how to use the CupertinoDialog dialog box

### ISSUE THREAD

**Issue by bruceclxu** [flutter/flutter#17792]
I wanted to know how to use the CupertinoDialog dialog box, and I created a dialog box that did not find the show method for the dialog box, and I didn't know how to display the dialog box.

**Comment by zoechi** [comment]
Can you please add the output of `flutter doctor` 
and the code that demonstrates what you tried 
and information about what errors it caused.

**Comment by zoechi** [comment]
Sorry for the late response.
You can use https://docs.flutter.io/flutter/material/showDialog.html to show a dialog.

Should CupertinoDialog, CupertinoAlertDialog, be mentioned in this page under `See also:` as well?

**Comment by Hixie** [comment]
sure

**Comment by xster** [comment]
the showDialog cross reference to showCupertinoDialog was added in https://github.com/flutter/flutter/pull/20152. #30887 adds a few more.
