### ISSUE TITLE
Stream listen and broadcast to all pages?

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#17807]
**Flutter** is amazing! I am nearly new to dart and flutter (get into it for 2 weeks or so.). I am in trouble now and lack of doc in these field, so that I want ask for some help here. This is my question:

I have websocket and I listened it's stream in every page, it shows an error when second time get into page:
```
Bad state: Stream has already been listened to.
```
So, How do I listen it just in the main page and when data chagnes, broadcast to all other widgets? Or Listen and de-Listen in every page so that it will not conflict?

Many appreciate if any help!

**Comment by zoechi** [comment]
Similar to https://stackoverflow.com/questions/50482557/flutter-how-to-make-websocket-stream-broadcast-to-many-other-pages
Is the SO question from you?

**Comment by jinfagang** [comment]
@zoechi Well... Sorry for bother, I just figure it out using a StreamController to achieve this, it can be locate on stackoverflow for the future people may have this issue, close it one.

**Comment by CandyTalkKent** [comment]
i have encontered the same issue, so whats ur solution of this problem ?
