### ISSUE TITLE
"ImportError: cannot import name _remove_dead_weakref" on device but simulator works

### ISSUE THREAD

**Issue by fotiDim** [flutter/flutter#17803]
When trying to run an app on an actual device, I am getting:

```
Running pod install...
Running Xcode clean...
Starting Xcode build...
Xcode build done.
Installing and launching...
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Syncing files to device iPhone...
flutter: Error performing request for GARAGE/LOADING_GARAGE/REQUEST: <html>
flutter: Error occured (GARAGE/LOADING_GARAGE/FAILURE): Error performing request for GARAGE/LOADING_GARAGE/REQUEST: <html>
Application finished.
```

In the meantime the same app on the simulator works fine.

**Comment by fotiDim** [comment]
`brew uninstall --force python@2` resolved the issue for me

**Comment by christian-muertz** [comment]
```
brew uninstall --force python@2

Error: Refusing to uninstall /usr/local/Cellar/python@2/HEAD
because it is required by libimobiledevice, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies python@2
```

Did you ignore dependecies?

**Comment by zoenberger** [comment]
I had same issue. I just added the --ignore-dependencies flag and now my app deploys to the iPhone. Thanks @fotiDim

**Comment by christian-muertz** [comment]
Yep works! 
Thanks @zoenberger and @fotiDim!!!

**Comment by shinriyo** [comment]
```
brew uninstall --ignore-dependencies python@2
```

**Comment by minimaluminium** [comment]
Any solution other than uninstalling python@2?

**Comment by ganeshp0001** [comment]
I followed the suggestion given by flutter logs and ran the following command
`open ios/Runner.xcworkspace`

Select team in "general" tab in Xcode, and run the app once through Xcode, the app installed successfuly. (I had to change device setting in iPhone in General->Device Management & select developer app and click on "trust" button")
Once I ran the app successfully through Xcode, later I was able to run it from terminal also.

P.S. : Error "ImportError: cannot import name _remove_dead_weakref" still appears but does not hangs or exits.

**Comment by JuliusNM** [comment]
Any updates on this `ImportError: cannot import name _remove_dead_weakref` ?
I have uninstalled python@2 but still can not get past this.

**Comment by cbracken** [comment]
I believe this issue should be solved on `dev` channel by #19281 and should be part of the next beta. If you'd like to verify, try `flutter channel dev` to switch to dev branch (`flutter channel beta` to switch back).

**Comment by wuziyou199217** [comment]
brew uninstall --force python@2, that works for me

**Comment by cbracken** [comment]
As noted in [my comment](https://github.com/flutter/flutter/issues/17803#issuecomment-413925127) above, I believe this should be fixed by #19281 (now available on all branches).

**Comment by thinkycx** [comment]
> Any solution other than uninstalling python@2?

Hello, everybody! I have melt with this problem and fix it by using the macOS system /usr/bin/python version 2.7.10 . Please should not use /usr/local/bin/python version 2.7.14  which is installed by brew.
You can change the python by `export PATH=/usr/bin:$PATH` .

I don't know why this works. If anybody knows, please tell me. Thank you very much.
@fotiDim @christian-muertz @zoenberger @shinriyo @minimaluminium

**Comment by kianoosh** [comment]
just brew unlink python@2 and turn it back by brew link python@2 if needed in my case when I use lldb do the unlink and link back if you need for Gtk, Qt, or..

**Comment by topherno** [comment]
> just brew unlink python@2 and turn it back by brew link python@2 if needed in my case when I use lldb do the unlink and link back if you need for Gtk, Qt, or..

Thanks, that solved the "ImportError: cannot import name _remove_dead_weakref" error I was getting (among others) when running lldb from the command line.

**Comment by milljm** [comment]
There is _some_ sort of activity and supposed solution here: 
[strange-mixing-of-system-homebrew-python-with-lldb](https://stackoverflow.com/questions/47658596/strange-mixing-of-system-homebrew-python-with-lldb) on Stackoverflow, but I myself can not figure out how to make it work for _my_ situation (using miniconda, not brew). Just thought I would post it here if it might help.

If the above link dies, the solution I was trying to reference was exporting the following environment before running what-ever-the-command-was that is causing the failed import error:

DYLD_FRAMEWORK_PATH="$(brew --prefix python@2)/Frameworks/"
