### ISSUE TITLE
Remove all Dart 2 flags

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#17804]
Beta in the [Beta 2 blog post](https://medium.com/flutter-io/https-medium-com-flutter-io-announcing-flutters-beta-2-c85ba1557d5e) we said:

> Should you need a bit more time to work through this, you can temporarily switch back to the old behavior with the Dart 2 opt-out. This opt-out is expected to be supported for a single beta release only.

With that, let's get all Dart related (both opt-in and opt-out, and from all tools, not just `flutter` removed)

**Comment by eseidelGoogle** [comment]
![image](https://user-images.githubusercontent.com/11857803/40373397-a9903d1e-5d9b-11e8-98be-f181ef5a60d1.png)

**Comment by mit-mit** [comment]
@Hixie are we all clear to go ahead and do this now?

**Comment by Hixie** [comment]
Yes, @cbracken is on the case.

**Comment by cbracken** [comment]
This was landed and reverted a couple times. The only remaining blocker is Fuchsia-specific, getting the frontend compiler available to their test harness. Once I've got that landed, we'll be good to go!

**Comment by mit-mit** [comment]
Any news on this @cbracken ?

**Comment by cbracken** [comment]
I'm currently working on a yak-shave to fix a fuchsia-specific issue with this. There's a non-trivial amount of work to fix all the remaining corner-cases for this.

**Comment by cbracken** [comment]
(Re-)fixed by #21304.
