### ISSUE TITLE
CheckedModeBanner displays weird artifacts when debugPaintSizeEnabled is true.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1780]
Crazy diagonal line.

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
Apparently save/restore should be free these days so we should change the transform/untransform to a save/restore/assert-save-count-has-not-changed.

**Comment by apwilson** [comment]
http://www.quickmeme.com/img/78/788fcd5121faf84eed577a890fd42a1acca15b23ddea9284191876d6e59fecdd.jpg
