### ISSUE TITLE
Suggestion for website page A Tour of the Flutter Widget Framework

### ISSUE THREAD

**Issue by ernestsaunders** [flutter/flutter#17810]
From URL: https://flutter.io/widgets-intro/

As a first time user of Flutter, I think that this page describing the Widget Framework could be even better if visuals of the resulting UI were included for each code sample.  I'd like to see at a quick glance what the code will do without having to go through each code sample.  Seeing a visual would let me say "yeah! That's really similar to the structure that I want to build!  I'm gonna read more!".

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1918](https://github.com/flutter/website/issues/1918) via [**ZenHub**](https://www.zenhub.com/)
