### ISSUE TITLE
IgnorePointered Widgets with elevation overlayed on a scrolling list block scrolling on fuchsia.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#17818]
See me for more details.

**Comment by tvolkert** [comment]
@apwilson it looked like you had a simple repro case when I stopped by.  Can you paste a repro case here?

**Comment by apwilson** [comment]
Somehow we 'fixed' this by using a PhysicalModel instead of a Material but I'm not sure why that fixes the issue.

**Comment by goderbauer** [comment]
Any chance you still have the code that originally showed the problem? Otherwise it will be hard to act on this problem...

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
