### ISSUE TITLE
Disallow software rendering on non-debug builds

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#17815]
Users can currently hack their Android manifest to enable it on Android - we should actively block this capability.

**Comment by NathanaelA** [comment]
Out of curiosity; if a user has to hack it to do it; why is it something that we want to block?

**Comment by tvolkert** [comment]
> why is it something that we want to block?

Because it'll yield significantly slower rendering, which contradicts the 60fps target of release mode.

**Comment by NathanaelA** [comment]
Yes, but if the person has to basically "hack" it enabled; then why do we want to block it per-sey.     I guess the underlying question is that there might be a reason the person needs to activate software mode for a testing purposes then blocking it can cause other issues for those situations that we might not think of...

**Comment by chinmaygarde** [comment]
In addition to what @tvolkert already mentioned, the presence of the software backend on iOS and Android in release builds is an oversight and adds to the engine binary. As we look deeper into reducing the binary size, [we want stop compiling this subsystem](https://github.com/flutter/engine/blob/ecedff3a56b95617acf6bcef359741a2ad6b8daa/shell/platform/darwin/ios/BUILD.gn#L14) entirely. It is not entirely clear if the person making the hack on behalf of the users of their application will monitor the validity of said hack after the subsystem is removed.

**Comment by tvolkert** [comment]
I hear you.  I guess the bottom line is that it's an unsupported config and a fluke that it works at all - "blocking" in this case likely amounts to not compiling in support for it in the first place on release builds in order to not bloat the binary size.

**Comment by tvolkert** [comment]
@chinmaygarde @dnfield is the software backend still included in release builds these days?  If so, seems like it may be relatively low-hanging fruit to save some binary size in the engine.  If not, this can be closed 🙂

**Comment by chinmaygarde** [comment]
> is the software backend still included in release builds these days.

On iOS, no. On Android, yes. This is being used in some test workflows where emulators are used with GPU passthrough issues.

**Comment by tvolkert** [comment]
@chinmaygarde is this still an issue with Impeller?  i.e. is this issue worth keeping open?
