### ISSUE TITLE
Flutter doctor crashes all the time

### ISSUE THREAD

**Issue by aswathm78** [flutter/flutter#17825]
I'm using Lubuntu 17.10 with latest android-studio ,sdk  and flutter . When I run 
`flutter doctor`

I get an error like this

> flutter doctor

> Doctor summary (to see all details, run flutter doctor -v):
> 
> Oops; flutter has exited unexpectedly.
> Sending crash report to Google.
> Crash report sent (report ID: 9bb939c963ebd205)
**> Unhandled exception:
> ProcessException: Permission denied
>   Command: /home/aswath/android-studio/jre/bin/java -version**
> #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
> #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
> #2      Process.runSync (dart:io-patch/process_patch.dart:66)
> #3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
> #4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:253)
> #5      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:34)
> #6      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:76)
> #7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:204)
> #8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:137)
> #9      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:127)
> #10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
> #11     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
> #12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
> #13     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
> #14     AppContext.[] (package:flutter_tools/src/base/context.dart:113)
> #15     androidStudio (package:flutter_tools/src/android/android_studio.dart:15)
> #16     javaPath (package:flutter_tools/src/android/android_studio.dart:29)
> #17     AndroidSdk.findJavaBinary (package:flutter_tools/src/android/android_sdk.dart:302)
> #18     AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:133)
> <asynchronous suspension>
> #19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:69)
> #20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:126)
> <asynchronous suspension>
> #21     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:189)
> #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
> <asynchronous suspension>
> #23     _rootRun (dart:async/zone.dart:1126)
> #24     _CustomZone.run (dart:async/zone.dart:1023)
> #25     runZoned (dart:async/zone.dart:1501)
> #26     AppContext.run (package:flutter_tools/src/base/context.dart:141)
> <asynchronous suspension>
> #27     _doctorText (package:flutter_tools/runner.dart:188)
> <asynchronous suspension>
> #28     _createLocalCrashReport (package:flutter_tools/runner.dart:166)
> <asynchronous suspension>
> #29     _handleToolError (package:flutter_tools/runner.dart:121)
> <asynchronous suspension>
> #30     run.<anonymous closure> (package:flutter_tools/runner.dart:58)
> <asynchronous suspension>
> #31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
> <asynchronous suspension>
> #32     _rootRun (dart:async/zone.dart:1126)
> #33     _CustomZone.run (dart:async/zone.dart:1023)
> #34     runZoned (dart:async/zone.dart:1501)
> #35     AppContext.run (package:flutter_tools/src/base/context.dart:141)
> <asynchronous suspension>
> #36     runInContext (package:flutter_tools/src/context_runner.dart:41)
> <asynchronous suspension>
> #37     run (package:flutter_tools/runner.dart:49)
> #38     main (package:flutter_tools/executable.dart:48)
> <asynchronous suspension>
> #39     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
> #40     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
> #41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Here's my path in .zshrc
`export PATH=$HOME/flutter/bin:$PATH`

Am I missing something?

**Comment by MaskyS** [comment]
The command ` /home/aswath/android-studio/jre/bin/java -version` is not being executed, there's a permission denied error. Some problem in your configuration.

**Comment by aswathm78** [comment]
Thanks for pointing out the problem . When I checked its  status the execution permission is never applied.

Now i granted the permission and works fine

`ls /home/aswath/android-studio/jre/bin/java  -la
-rw-rw-r-- 1 aswath aswath 8646 Apr 13 13:58 /home/aswath/android-studio/jre/bin/java
`

`chmod a+x /home/aswath/android-studio/jre/bin/java`  

`➜  ~ ls /home/aswath/android-studio/jre/bin/java  -la    
-rwxrwxr-x 1 aswath aswath 8646 Apr 13 13:58 /home/aswath/android-studio/jre/bin/java
`
