### ISSUE TITLE
Path glitch when rendering to Canvas and when clipping.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#17827]
When certain Paths are combined either for painting or clipping, a slight vertical and/or horizontal gap appears between the paths that are combined when there should be no gap.

The visual artifact can be reproduced at least on an Nexus 5X and an iPhone 7, though the artifacts are slightly different on each.  It is also possible to see a visual artifact in the iPhone simulator, and possibly also in an Android emulator.

An example of code that causes the issue can be found at the link below with relevant code starting at line 588:
https://github.com/matthew-carroll/flutter_ui_challenge_springy_slider/blob/6989f19b6ed7a6a9de094cbeb49434ffb98213cb/lib/main.dart

![ios-simulator](https://user-images.githubusercontent.com/7259036/40405383-370c9e7e-5e11-11e8-87cd-e8c25c0487ee.gif)

![iphone-7](https://user-images.githubusercontent.com/7259036/40405387-3d5fdfde-5e11-11e8-8825-6120b218f250.gif)

**Comment by chinmaygarde** [comment]
I have verified that this is an issue with Skia. The engine does not seem to be introducing any additional layers or populating raster cache entries. An SKP dump of this scene [is available here](https://github.com/flutter/flutter/files/2055439/flutter_01.skp.zip).

**Comment by chinmaygarde** [comment]
I was able to reproduce this on an iPhone 8.

**Comment by chinmaygarde** [comment]
cc @brianosman

**Comment by chinmaygarde** [comment]
This was brought up in the Skia sync and the update says @reed-at-google is talking a look. Thanks.

**Comment by zoechi** [comment]
Can you still reproduce?

**Comment by markusaksli-nc** [comment]
@matthew-carroll Is this still an issue?

The repro code link leads to a 404 for me so I can't check it without the code.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
