### ISSUE TITLE
[Feature Request] Add support for Polylines in google_maps_flutter package

### ISSUE THREAD

**Issue by bjornbjorn** [flutter/flutter#17832]
https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter

It would be great to have support for Polylines in this package, something like described here: https://developers.google.com/maps/documentation/javascript/examples/polyline-simple

Basically adding a path based on a list of lat/lng coordinates:

```dart
var flightPlanCoordinates = [
  {lat: 37.772, lng: -122.214},
  {lat: 21.291, lng: -157.821},
  {lat: -18.142, lng: 178.431},
  {lat: -27.467, lng: 153.027}
];
var flightPath = new google.maps.Polyline({
  path: flightPlanCoordinates,
  geodesic: true,
  strokeColor: '#FF0000',
  strokeOpacity: 1.0,
  strokeWeight: 2
});
```

Thanks!

cc @mravn-google

**Comment by zoechi** [comment]
cc @Hixie

**Comment by mravn-google** [comment]
@amirh and I are aware of this feature request. We can't promise exactly when we'll get around to it. Hopefully soon, but if you can't wait, PRs are always welcome at the `flutter/plugins` repo. Whoever starts working on this: please let us know immediately through comments or self-assignment on this issue.

**Comment by cujslive** [comment]
any updates on this thread? or can anyone suggest me a method to draw routes inside google_maps_flutter map? currently polyline support is not available.

**Comment by irevans** [comment]
I have added support for drawing polylines to the google maps flutter plugin (as my applications needs that functionality). I have the flutter layer, android code and example application done, I have not yet added support for iOS. 

I would be more than happy to contribute this code/submit it for review. I would also be willing to start work on the iOS side.

Let me know how you would like to proceed.

**Comment by amirh** [comment]
Thanks @irevans that's great! happy to take contributions!

We should have both iOS and Android working before landing it (among other things to make sure the Dart API makes sense for both platforms).

Also note that I'm planning to refactor the Dart API for the maps widget soon, and move everything that makes sense from the controller to widget parameters.

Feel free to send a PR just for Android if you're interested in early feedback.

**Comment by irevans** [comment]
I think that early feedback would be a good idea, I'll send a pull request tomorrow.

**Comment by cujslive** [comment]
thanks @irevans my app too need that functionality. it would be really helpful if you can submit a pr asap.

**Comment by DanialV** [comment]
I need this feature too please submit a pr asap thanks.

**Comment by bjornbjorn** [comment]
@irevans @DanialV FWIW we decided to go with Leaflet which supports polylines: 

![](https://i.imgur.com/cn8xZfT.jpg)

https://pub.dartlang.org/packages/flutter_map

**Comment by bjornbjorn** [comment]
Would still like this functionality in the google maps package though, having options is good :-)

**Comment by cujslive** [comment]
polyline support is now available (android only) via this ref: https://github.com/irevans/plugins/tree/google_maps_polyline

It is not merged, but i don’t have any crashes till now.

![image](https://user-images.githubusercontent.com/35224957/49722468-d9872800-fc8a-11e8-9a7f-01b05964b99d.png)

**Comment by DanialV** [comment]
@responseBody just one question I need to be sure to switch my map dose leaflet on flutter support tracking a marker on a polyline like this [Roads API Inspector](https://developers.google.com/maps/documentation/roads/inspector) and maker info window because I need all of thease features in my app ?

**Comment by DanialV** [comment]
@cujslive how can I use this feature?

**Comment by DanialV** [comment]
@irevans it would be great if you provide ios support for this feature thanks.

**Comment by timtraversy** [comment]
Going to start working on adding this to the main plugin, in case anyone is close to finishing.

**Comment by amirh** [comment]
Note that I'm working on converting the maps plugin from a controller based API to a widget based plugin. I believe these changes will have implications on polyline support, I'd recommend waiting for the overall API design to stabilize before working on this feature (or at least, if you are working on this already keep in mind that it is possible that a complete rewrite will be necessary before merging).

**Comment by timtraversy** [comment]
https://github.com/flutter/plugins/pull/961 This isn't the full conversion?

**Comment by amirh** [comment]
That's just the first easy step 😄

**Comment by timtraversy** [comment]
Ok I'm probably going to base it off the Marker logic so I'll hold off.

**Comment by delphiy** [comment]
not working on IOS,


The result of flutter doctor -v as follows:

Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-GB)
• Flutter version 1.0.0 at /Users/delphix/Documents/Sdk/flutter
• Framework revision 5391447 (3 weeks ago), 2018-11-29 19:41:26 -0800
• Engine revision 7375a0f414
• Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

⣷Unhandled exception:
Exception: adb not responding
#0 throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1 AndroidDevice._getProperty (package:flutter_tools/src/android/android_device.dart:99:9)

#2 AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart:130:21)

#3 Device.descriptions (package:flutter_tools/src/device.dart:309:58)

#4 DeviceValidator.validate (package:flutter_tools/src/doctor.dart:697:31)

#5 Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6 Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#7 _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#8 Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#9 DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#10 _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#11 DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#12 FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#13 _asyncThenWrapperHelper. (dart:async/runtime/libasync_patch.dart:77:64)
#14 _rootRunUnary (dart:async/zone.dart:1132:38)
#15 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16 _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#17Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#18 Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#19 Future._complete (dart:async/future_impl.dart:476:7)
#20 _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21 _AsyncAwaitCompleter.complete. (dart:async/runtime/libasync_patch.dart:33:20)
#22 _rootRun (dart:async/zone.dart:1124:13)
#23 _CustomZone.run (dart:async/zone.dart:1021:19)
#24 _CustomZone.bindCallback. (dart:async/zone.dart:947:23)
#25 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27 _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#28 _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart

**Comment by cujslive** [comment]
> @DanialV add `google_maps_flutter dependency` to your flutter application like this:
> 
> ```yaml
> google_maps_flutter:
>     git:
>       url: git://github.com/irevans/plugins/
>       path: packages/google_maps_flutter
>       ref: google_maps_polyline
> ```
> 
> and use with the map controller like this:
> 
> ```dart
> _mapController.addPolyline(
>   PolylineOptions(
>     width: 10,
>     points: points,
>     endCap: Cap.roundCap,
>     startCap: Cap.roundCap,
>     color: Colors.green.value
>   )
> );
> ```

@delphiy this solution will not work on iOS. Seems like your issue is not even related to flutter. your adb is not responding.

**Comment by delphiy** [comment]
I need add Polyline in ios as well

**Comment by delphiy** [comment]
This works fine on Andriod but not working on ios

**Comment by rafalbednarczuk** [comment]
> That's just the first easy step smile

@amirh 
Do you need help with it?

**Comment by delphiy** [comment]
Hi,

does this plugin(Polylines) works on IOS?

**Comment by timtraversy** [comment]
The google maps plugin is also being majorly rewritten as mentioned above, so any extensions written now would likely have to be redone.

**Comment by zhen1991** [comment]
Hi guys !
I’m asking if there is a way to draw a polyline in flutter and using watch position when I moved so the map is going to draw the polyline ! Is there a way to do this ??

**Comment by awazgyawali** [comment]
I am not much of an Objective C developer, by one of my projects is being stuck due to lack of polyline support on IOS, I am planning to implement it. Any suggestions are appreciated. Specially @irevans, please do suggest if there is anything I should know.

**Comment by delphiy** [comment]
Hi,
I have made poly-line support for both Andriod and Ios .It is under test now . I will publish as soon as possible . 

How can I upload the amended plugin google_map_flutter with polyline support for andriod and ios

**Comment by awazgyawali** [comment]
@irevans Got your points, I am currently working on it right now. Thanks for your work on Android, it's being easy to follow the pattern that you have used.

**Comment by awazgyawali** [comment]
@delphiy Can you add your work on github? Maybe I can help you test and fix some issues.

**Comment by delphiy** [comment]
Yes , I will . Should I upload to my repository or there is another way

**Comment by awazgyawali** [comment]
Have you forked this project? or you just pulled this repo and started editing?

**Comment by delphiy** [comment]
I pulled the last version of google_map_flutter and start editing .

**Comment by zhen1991** [comment]
Hi!
how do u guys save polyline in flutter ??
how to have button which include polyline to be active and a button when finished with drawing ??
thnx for helping:)

**Comment by awazgyawali** [comment]
@irevans Can you add me as a collaborator on your forked repo, I want to push to your repo.

**Comment by awazgyawali** [comment]
Guys, I have added polyline support for IOS too. Currently, cap, pattern type is not supported on IOS. Only colour, width, visibility can be changed, and yes I am aware the plugin is being re-written but I needed the polyline support on IOS anyway. Maybe we can rewrite that part again if needed. 

I want you guys to test the implementation and suggest further improvements.
Add this on pubspec.yaml

```
  google_maps_flutter:
      git:
        url: git://github.com/awazgyawali/plugins/
        path: packages/google_maps_flutter
        ref: google_maps_polyline
```

Credit to the Android part goes to @irevans. I just added support on IOS on his work.

**Comment by Aljoxa88** [comment]
Added polygon support, used a little bit of @irevans code (pattern_item.dart) 
https://github.com/flutter/plugins/pull/1048

**Comment by melvinsalas** [comment]
> Guys, I have added polyline support for IOS too. Currently, cap, pattern type is not supported on IOS. Only colour, width, visibility can be changed, and yes I am aware the plugin is being re-written but I needed the polyline support on IOS anyway. Maybe we can rewrite that part again if needed.
> 
> I want you guys to test the implementation and suggest further improvements.
> Add this on pubspec.yaml
> 
> ```yaml
>   google_maps_flutter:
>       git:
>         url: git://github.com/awazgyawali/plugins/
>         path: packages/google_maps_flutter
>         ref: google_maps_polyline
> ```
> 
> Credit to the Android part goes to @irevans. I just added support on IOS on his work.

Thanks @awazgyawali
Can you provide an example? I want to testing.

**Comment by awazgyawali** [comment]
Check the code inside example folder, also it similar to marker, just add or update marker using controller.

**Comment by melvinsalas** [comment]
> Check the code inside example folder, also it similar to marker, just add or update marker using controller.

Polyline was a blocker on my project, you have saved it. :D
It's work properly, great work.
But, the color parameter is always random, even when I set it. 
```
mapController.addPolyline(
  PolylineOptions(
    color: 0x88000000,
    width: 1.0,
    points: [
      LatLng(1.0, 10.0),
      LatLng(2.0, 30.0),
      LatLng(30.0, 20.0),
      LatLng(10.0, 10.0),
    ],
  ),
);
```
![screen shot 2019-01-08 at 9 33 33 am](https://user-images.githubusercontent.com/708747/50840613-81dee980-1328-11e9-85cc-eedad2d41413.png)

I have a couple of ideas, if you want we can work together to do it :D

**Comment by melvinsalas** [comment]
> Check the code inside example folder, also it similar to marker, just add or update marker using controller.

Polyline was a blocker on my project, you have saved it. :D
It's work properly, great work.
But, the color parameter is always random, even when I set it. 
```
mapController.addPolyline(
  PolylineOptions(
    color: 0x88000000,
    width: 1.0,
    points: [
      LatLng(1.0, 10.0),
      LatLng(2.0, 30.0),
      LatLng(30.0, 20.0),
      LatLng(10.0, 10.0),
    ],
  ),
);
```
![screen shot 2019-01-08 at 9 33 33 am](https://user-images.githubusercontent.com/708747/50841156-af786280-1329-11e9-909c-f7d96d8adbac.png)

I have a couple of ideas, if you want we can work together to do it :D

**Comment by awazgyawali** [comment]
@melvinsalas Thanks for the test, I have to look at the colour parameter to check the issue. And ya sure would love to work together, but as the whole plugin is being rewritten I think it would not be a good idea to add more functionality than the basics. Maybe I should send PR first to get it reviewed.

**Comment by delphiy** [comment]
How you know that the google_map_flutter will be rewritten .

**Comment by awazgyawali** [comment]
> Thanks @irevans that's great! happy to take contributions!
> 
> We should have both iOS and Android working before landing it (among other things to make sure the Dart API makes sense for both platforms).
> 
> Also note that I'm planning to refactor the Dart API for the maps widget soon, and move everything that makes sense from the controller to widget parameters.
> 
> Feel free to send a PR just for Android if you're interested in early feedback.

From this comment, and actually he has started working on it too. Can you please confirm @amirh ?

**Comment by awazgyawali** [comment]
By rewriting, I meant entier refactoring. Sorry for the wrong word there.

**Comment by melvinsalas** [comment]
@awazgyawali I tested on android and iOs, and the differences are:
- Different width
- iOs color is random, on any restart

![screen shot 2019-01-08 at 9 52 11 am](https://user-images.githubusercontent.com/708747/50841905-498cda80-132b-11e9-933e-7b203dee7927.png)

code:
```
mapController.addPolyline(
  PolylineOptions(
    color: 0x88000000,
    width: 5.0,
    points: [
        LatLng(1.0, 10.0),
        LatLng(2.0, 30.0),
        LatLng(30.0, 20.0),
        LatLng(10.0, 10.0),
    ],
    ),
);
```

**Comment by awazgyawali** [comment]
@melvinsalas Found the issue regarding colour, fixed. But regarding width, I was unable to find it. Still debugging.

**Comment by awazgyawali** [comment]
Sent a PR here. https://github.com/flutter/plugins/pull/1049

**Comment by irevans** [comment]
FYI, I (my employer) has signed the cla. I've added a "I signed it!" comment to both my fork and @awazgyawali's branch, but it hasn't triggered a rebuild.

**Comment by irevans** [comment]
It would be good to get an update from the flutter team as to the status of this feature request. It seems to be labelled "waiting for PR to land" despite flutter/plugins#1049 being ready to go.

**Comment by amirh** [comment]
I’m sorry this takes so long! this is definitely an important feature and thanks for putting together the PR!

While I would really want to see this feature landing already, the ecosystem & plugins team is currently very busy with a bunch of other priorities that makes sense to complete before polylines, specifically:

- Putting together a test harness that can test the platform side of plugins, without that it is hard to keep scaling the plugins we currently maintain safely, and until we have that we’re trying to avoid adding new features that are not test covered. I’m not yet sure how features like polylines are going to be tested, but I would really prefer to have the testing story figured before we add more features. This is one of the team’s highest priorities right now, and is tracked in flutter/flutter#10824 and flutter/flutter#26080.

- Getting platform views out of developers preview - right now using the Google Maps plugin on iOS requires running the Flutter Engine with a single thread, this probably means it is not a good idea to launch apps using the maps plugin on iOS yet. So we want to address that before adding new plugin features.

- Completing the transition to a widget-based API - the PR for that is already up(https://github.com/flutter/plugins/pull/1229), we are trying to keep the API for Google Maps as widget-based as possible, this probably means that we will need to work together on redesigning the public API in the pending polylines PR.

I’m assuming that reviewing the polylines PR and bringing it to the finish line will require at least a few solid days. The payoff will definitely be worth it(not only landing the feature but also having at least one more person out there who's comfortable with making significant contributions). But I want to make sure I (or whoever ends up reviewing) have the availability to follow-up on that review before I start it(and that the issues I mentioned above are handled first).

So again - I can’t emphasize enough how great this kind of contribution is, thank you! and I wish I could have gotten to reviewing and landing the PR already. I’m hoping we’ll sort through the higher priorities quick enough and land that PR (but I’ll be honest and say that I expect it to take a few months).

**Comment by tegarkurniawan** [comment]
erorr Note: C:\src\flutter\.pub-cache\git\plugins-864fb5d90a3519435929e5ed50d6e89f9648281a\packages\google_maps_flutter\android\src\main\java\io\flutter\plugins\googlemaps\GoogleMapFactory.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by irevans** [comment]
Thanks @amirh for the detailed response. The prioritisation you outline makes a lot of sense. Let us know as soon as it makes sense to start converting the polylines work over to the new widget based API.

**Comment by tegarkurniawan** [comment]
> @DanialV @bjornbjorn
> polyline support is now available (android only) via this ref: https://github.com/irevans/plugins/tree/google_maps_polyline
> 
> It is not merged, but i don’t have any crashes till now.
> 
> ![image](https://user-images.githubusercontent.com/35224957/49722468-d9872800-fc8a-11e8-9a7f-01b05964b99d.png)

how to get navigate lat long two route ?

**Comment by lvlasuod** [comment]
im waiting for this feature too !

**Comment by awazgyawali** [comment]
I have completed the transfer of the polyline support to widget-based similar to the marker on from the core team. Details on how to use the PR on controller basis and widget basis is mentioned on the description of this PR.

**Comment by iskakaushik** [comment]
With https://github.com/flutter/plugins/pull/1049 merged, you can start using `Polyline`, starting from `0.5.6`. We do not have feature parity yet, but if you have specific things you'd want for polylines, feel free to submit issues or PRs or both. Thanks for your patience.

**Comment by giaur500** [comment]
PolyLine only or other shapes also? Filled polygon etc. As PolyLine support is there, adding other shapes should not require too much effort.

**Comment by bhavyalatha26** [comment]
It would also be helpful if the support for poly utilities is also added.
https://googlemaps.github.io/android-maps-utils/javadoc/com/google/maps/android/PolyUtil.html
Is there any current workaround for this right now ?

**Comment by giaur500** [comment]
I thnik there is not. But you can look at java code for specific method you need and rewrite it to dart.

**Comment by abhijithvijayan** [comment]
Gradient Support?

I was thinking of this between 3 points **A, B & C**

From *A(Red) to B(green) to C(blue)*

![Screenshot from 2019-12-17 22-21-07](https://user-images.githubusercontent.com/34790378/71016748-9d976600-211b-11ea-8462-bbdcc1a879e6.png)
![Screenshot from 2019-12-17 22-23-58](https://user-images.githubusercontent.com/34790378/71017035-ff57d000-211b-11ea-961c-d5826ecab982.png)
