### ISSUE TITLE
Firebase Messaging plugin: 'onLaunch' never called with "Don't keep activities" on Android

### ISSUE THREAD

**Issue by g123k** [flutter/flutter#17839]
Hello,

I have noticed a bug when the "Don't keep activities" toggle is on (in the Developer Options) or the main Activity is killed by Android.
In that case, when the user clicks on the notification, the event won't be forwarded in the onLaunch method in the Dart code.

The reason of this, is that the `onNewIntent` method is called, but the Dart side is not yet ready.
When the `configure` is finally called, a wrong Intent is used (action = `android.intent.action.RUN`), instead of the one called by the notification.

A fix for this would be to call in the `onNewIntent`:
```java
  registrar.activity().setIntent(intent);
```

**Comment by zoechi** [comment]
Seems the linked PR (merged) is supposed to fix this issue.
Thanks a lot for your contribution 👍

**Comment by alex9153** [comment]
I have the same problem. Not clear how to fix. Could you explain ?
