### ISSUE TITLE
Debugger unexpectedly pauses on exception that will be caught

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#17838]
For some reason I can only repro this from Dart Code, not from the command line/Observatory... However I don't believe there's anything obviously wrong in VS Code.

I'm running a small sample app on `flutter-tester` and it breaks at startup on this:

![screen shot 2018-05-23 at 2 25 30 pm](https://user-images.githubusercontent.com/1078012/40427412-91a75d68-5e95-11e8-99f8-c9be53aad48b.png)

However if I go up the stack to `OptionalMethodChannel.invokeMethod` there is a catch statement that would catch this exception:

![screen shot 2018-05-23 at 2 29 05 pm](https://user-images.githubusercontent.com/1078012/40427453-ae2e7296-5e95-11e8-8205-79f05f0ad829.png)

I've confirmed that exception pause mode is `Unhandled`:

```text
[14:31:12]: ==> {"id":"5","method":"setExceptionPauseMode","params":{"isolateId":"isolates/1027928886","mode":"Unhandled"}}
```

Here are full logs from Flutter Run + Observatory:

- [flutter_run.txt](https://github.com/flutter/flutter/files/2031243/flutter_run.txt)
- [observatory.txt](https://github.com/flutter/flutter/files/2031244/observatory.txt)

**Comment by DanTup** [comment]
@rmacnak-google @aam This seems like it might be the opposite problem to #16741 - could it be related to the fix?

**Comment by DanTup** [comment]
@aam @devoncarew Anyone have ideas about this? On the surface it seems kinda serious but since nobody else appears to be reporting it, I'm not sure if there's something specific triggering it (I am using flutter-tester which is likely the cause of the exception, but I don't know if that would influence the actual behaviour seen).

**Comment by devoncarew** [comment]
@a-siva, I believe this is a regression in debugging related to the move to preview dart 2. To paraphrase the issue, we have break on exceptions set to break on uncaught exceptions. In the above issue, we see the VM breaking on a caught exception, regardless of the value of the setting. @DanTup believe that this was not the case a few weeks ago (he's also going to look at writing an integration test for this in flutter_tools).

**Comment by aam** [comment]
@DanTup does this only happen in VSCode when running flutter apps? Do standalone dart apps in VSCode work fine? Have you seen this happening in this particular instance only or handled exceptions are treated as unhandled everywhere? Can you share the app(the smaller the better) that exhibits this behavior please?

**Comment by DanTup** [comment]
@aam so far I've only seen it in VS Code and only in this instance. I tried to write an integration test for it this morning but could not repro. So, the only repro I currently have requires having VS Code and running its test. I will see if I can strip my Dart Code test down to a simple script that can be run, but it might take a little time.

**Comment by DanTup** [comment]
@aam Aha, I repro'd outside of Dart Code :)

- `flutter create my_test_repro`
- `cd my_test_repro`
- `flutter run --start-paused -d flutter-tester`
- open Observatory in browser
- Click on the Isolate, then `main.dart`
- Set a breakpoint on `return new Scaffold(`
- Go to the debugger and run `continue`
- You'll hit the breakpoint, so `continue` again
- `run set break-on-exception Unhandled`
- Perform a hot reload by pressing `r` in the console where you ran `flutter run`
- You'll hit the breakpoint, type `continue`

Now you'll hit the exception:

![screen shot 2018-06-18 at 3 04 39 pm](https://user-images.githubusercontent.com/1078012/41540855-f67cc372-7308-11e8-8cb9-163beb1bf03b.png)

But if you go up to Frame 1, you'll see it's going to be caught - and in fact if you breakpoint on the `return null` then `continue`, it will be hit:

![screen shot 2018-06-18 at 3 06 09 pm](https://user-images.githubusercontent.com/1078012/41540947-2c272594-7309-11e8-9d2e-00ccd88b24e8.png)

I'm using Flutter's master as of today. Let me know if you can't repro it like this.

**Comment by aam** [comment]
Thanks @DanTup for the steps, but after ``You'll hit the breakpoint, type continue``` I am not getting ```Now you'll hit the exception:```

Do you see this happening specifically after hot reload?

**Comment by DanTup** [comment]
Yeah, I only see it after the reload in my tests (I test doing 0, 1 and 2 reloads and the first one passes so I don't think it's occurring without a reload).

Not sure why you're not hitting this! Are you using the test device (I don't think the plugin is missing for normal devices) and on macOS?

**Comment by aam** [comment]
Ah, sorry, I missed `-d flutter-tester`. Yes, I got a breakpoint on the exception now.

**Comment by DanTup** [comment]
If I try to repro this today, the process seems to terminate instead:

```
[{"event":"app.started","params":{"appId":"591634fe-aa6e-4d6a-9f85-9b791f04ad89"}}]
Lost connection to device.
[{"event":"app.stop","params":{"appId":"591634fe-aa6e-4d6a-9f85-9b791f04ad89"}}]
```

I don't know if this means something has changed relating to this, or if it's just crashing earlier than this used to happen.

**Comment by aam** [comment]
Landed as part of https://dart-review.googlesource.com/c/sdk/+/66800, should be in flutter once dart rolls into engine, engine into flutter.

**Comment by aam** [comment]
Should have landed in flutter.

**Comment by DanTup** [comment]
Fix LGTM, thanks! :)

**Comment by Prashanth00** [comment]
Just uninstall and debug again .It might work.
