### ISSUE TITLE
Issue from website page Working with cached images

### ISSUE THREAD

**Issue by efidje** [flutter/flutter#17844]
From URL: https://flutter.io/cookbook/images/cached-images/

This example program gives an error in the IDE. The part of the code that fails;

import 'package:cached_network_image/cached_network_image.dart';

**Comment by zoechi** [comment]
What's the error?
Please add the output of `flutter doctor`

**Comment by efidje** [comment]
Hi,

See attached screen dumps for reference. Maybe there is a step that I
have missed which cause the android studio IDE to complain.

Rgds

**Comment by zoechi** [comment]
That didn't work. Can you please try to add them using the web page?

**Comment by efidje** [comment]
Ok, went to web page and uploaded. Did that work?

**Comment by zoechi** [comment]
No, but you should be able to verify yourself on the web page..

**Comment by efidje** [comment]
![screen_dump](https://user-images.githubusercontent.com/17090510/40445893-be9d28ba-5ecd-11e8-8451-f26115e76da7.jpeg)
![flutter_doctor](https://user-images.githubusercontent.com/17090510/40446046-3295a44a-5ece-11e8-95c5-b47776232397.jpeg)

**Comment by efidje** [comment]
OK, not sure if it worked. Looks like some files are there now

**Comment by zoechi** [comment]
How is `transparent_image` related to https://flutter.io/cookbook/images/cached-images/ ?

**Comment by efidje** [comment]
It's only related in the fact that its listed as an example in the same  "Cookbook" section on the website. I have attached one more screen dump for ref.
![screen_dump2](https://user-images.githubusercontent.com/17090510/40447789-ffa0093a-5ed3-11e8-82dd-2147bf397831.png)

**Comment by zoechi** [comment]
Did you run `flutter packages get`
Also similar problems disappeared after restarting the IDE.

**Comment by efidje** [comment]
Yes, I ran the "flutter packages get" command and restarted the IDE.
No success, same issues.

**Comment by zoechi** [comment]
Please post the content of the `pubspec.yaml` file.

**Comment by efidje** [comment]
The content of the pubspec.yaml file;


name: flutter_app2
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
     - family: Raleway
       fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
     - family: RobotoMono
       fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

**Comment by efidje** [comment]
Anyway, I have moved onto other example code in the Cookbook section. No other issues found. pubspec.yaml file not changed. I have just been "cutting and pasting" the example code into main.dart
