### ISSUE TITLE
Flutter commands doesn't work

### ISSUE THREAD

**Issue by koami** [flutter/flutter#17846]
Hi Guys. Get some issue with my flutter (First of all sorry for the bad english, French People). I'm using Flutter for three months nos, but since yesterday, I can't run any of flutter command line, it's better to say that the command run but never end, The curser just keep biping. Sorry, almost fogeot, when I try to change channel (curent one is beta), I got this error message :
Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").
package:pub_semver/src/version_range.dart 59 new VersionRange
package:pub/src/pubspec.dart 366 Pubspec._ensureEnvironment
package:pub/src/pubspec.dart 331 Pubspec.dartSdkConstraint
package:pub/src/solver/backtracking_solver.dart 511 BacktrackingSolver._checkPubspecMatchesSdkC
onstraint
package:pub/src/solver/backtracking_solver.dart 474 BacktrackingSolver._checkVersion
===== asynchronous gap ===========================
package:pub/src/solver/backtracking_solver.dart 432 BacktrackingSolver._findValidVersion.<fn>
===== asynchronous gap ===========================
dart:async _completeOnAsyncReturn
package:pub/src/solver/backtracking_solver.dart 436 BacktrackingSolver._findValidVersion.<fn>
dart:async _completeOnAsyncReturn
package:pub/src/solver/version_queue.dart 88 VersionQueue.advance
This is an unexpected error. Please run
pub --trace upgrade --verbosity=error --no-packages-dir
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Thanks in advance for your help.

**Comment by zoechi** [comment]
I think that's a known issue with this version. Update manually using
`git clean -xffd` `git pull` flutter doctor` in the Flutter install directory.

**Comment by koami** [comment]
You just save a Man life. Thanks a lot.
