### ISSUE TITLE
Flutter does not refer to the language setting of the device

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#17843]
@najeira made a medium post about CJK support in Flutter after moving from Blink to libTxt:
https://medium.com/@najeira/flutter-and-cjk-font-selection-5dbc6a6164ba

One assertion he made was "Flutter does not refer to the language setting of the device"

I'm not sure exactly what is desired, but this bug is about fixing that. :)

Or if nothing else, fixing https://flutter.io/tutorials/internationalization/ to make clear how to solve the issue.

**Comment by eseidelGoogle** [comment]
Or maybe this is already tracked in https://github.com/flutter/flutter/issues/17501 ?

**Comment by najeira** [comment]
This is related to #17501 , but I think that it is another issue.

In flutter/engine, FlutterView pass device locale to "flutter/localization" channel.
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/FlutterView.java#L202


When #16408 was fixed, this issue will be solved together as well.

**Comment by cbracken** [comment]
Thanks for filing and for your Medium article, @najeira!

#16408 (which you're cc'ed on) will improve things when a font is explicitly specified, but as you note, the proper solution is for us to do locale-aware font fallback in the engine so we render the correct glyphs by default. 

Once we've got that, it might be useful to add CJK tabs to the typography demo in the gallery. /cc @HansMuller.

**Comment by gerryhigh** [comment]
See also [#17933](https://github.com/flutter/flutter/issues/17933)

**Comment by goderbauer** [comment]
@GaryQian Did any of your recent fixes around this fix this issue?

**Comment by GaryQian** [comment]
We now fully pass locale through framework to text layout, I believe this should be fixed. Please let me know if anyone still sees this.
