### ISSUE TITLE
ThemeData constructor is complex and untested

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#17849]
The behavior of the `ThemeData` constructor determines the appearance of Flutter apps and is fairly complex. We should consider writing some tests for this constructor, to document what the important behaviors are.

Relates to #17848.

**Comment by nicolashemonic** [comment]
@collinjackson In my experience it's the most frustrating feature of Flutter. On the paper the Theme is a very cool and useful feature but in fact its implementation is in pain 😥. I found several bugs using Theme and widget style customization in general.  In my experience a lot of Theme values are not take into account while they had to. This enforce my incomprehension about Theme behavior. For example #17717

**Comment by TahaTesser** [comment]
Hi @collinjackson 
Do you think this issue still valid?
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
