### ISSUE TITLE
Scrollview would not bounce back when using CupertinoRefreshControl if the actual content size is smaller than the scrollview's size

### ISSUE THREAD

**Issue by cxq1221** [flutter/flutter#17857]
## Steps to Reproduce

1. Use CupertinoRefreshControl within CustomScrollView
2. Add SliverList, and make sure the count of item is smaller enough to make the contentsize smaller than the scrollView's size
3. Pull down to refresh, when it finishes, the scrollView would not bounce back .

Keep running as shown below:
![img_4811](https://user-images.githubusercontent.com/13374376/40461625-d1598c52-5f3e-11e8-9926-db01161bd07f.PNG)

**Comment by xster** [comment]
We fixed it on master. It should roll into beta shortly
#17599

**Comment by cxq1221** [comment]
It seems not fixed yet , on master channel

**Comment by xster** [comment]
@cxq1221 I got an email of a comment but you may have deleted it since. Are you still having issues on the master branch?
