### ISSUE TITLE
Floating Action Button long-press crash on iOS simulator

### ISSUE THREAD

**Issue by johnfesa** [flutter/flutter#17853]
I can reliably cause an assertion failure in the Flutter native iOS code (results in a crash) by long-pressing a Floating Action Button.

## Steps to Reproduce

1. Build and run the hello_flutter demo application for the iOS simulator (not sure if it reproduces on physical devices). This was done on a Google-internal machine using the internal build system, with Xcode 9.2 and iPhone X 11.2 simulator.
2. Long-press in the direct center of the Floating Action Button
3. App crashes

## Logs
```
*** Assertion failure in void shell::AccessibilityBridge::HandleEvent(NSDictionary<NSString *,id> *)(), ../../flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm:618

Callstack:

*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e70812b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010dd9cf41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e70d2f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010b6a93db -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   Flutter                             0x0000000109e1a349 _ZN5shell19AccessibilityBridge11HandleEventEP12NSDictionaryIP8NSStringP11objc_objectE + 269
	5   Flutter                             0x0000000109e068bc __48-[FlutterBasicMessageChannel setMessageHandler:]_block_invoke + 124
	6   Flutter                             0x0000000109e1d1c6 _ZNK5shell21PlatformMessageRouter21HandlePlatformMessageEN3fxl6RefPtrIN5blink15PlatformMessageEEE + 166<…>
```

**Comment by jonahwilliams** [comment]
The problem is the new semantics events I added are not correctly handled by the accessibility_bridge on the iOS side [here](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm#L612).  The fix is to either remove the assert or add blank branches for the additional actions tap and longpress.

**Comment by CaiJingLong** [comment]
When will this revised version be submitted to flutter?
I met the same problem at beta 0.4.4.

**Comment by jonahwilliams** [comment]
@CaiJingLong when the engine is rolled sometime in the next few hours, you can switch to the master channel for the fix.  I don't know when the next beta release will be.

**Comment by majilesh** [comment]
Thanks @jonahwilliams I have same issue on beta 0.4.4 and as advised tried again switching to master channel and can confirm that it is fixed. Long press will now show the tooltip. Cheers
