### ISSUE TITLE
Flutter Cache and Hot Reloading Hanging issue in Visual Studio

### ISSUE THREAD

**Issue by ajaybeniwal** [flutter/flutter#17858]
## Steps to Reproduce
1.Reload 5 to 6 times in visual studio and hot reloading stops working 
2.After fresh debug instance sometimes old cache is shown

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale en-SG)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2017.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected devices (2 available)

**Comment by DanTup** [comment]
This sounds like #17434; could you try switching to the master branch temporarily (`flutter channel`) and see if the problem goes away?

(Btw, there's also a new beta version that you're on if you `flutter upgrade`, though it doesn't have the above fix in it, you need master for that).

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
