### ISSUE TITLE
Android/Windows [!] Android toolchain - develop for Android devices (Android SDK 27.0.3)

### ISSUE THREAD

**Issue by aitseps** [flutter/flutter#17856]
I'm in the process of installing flutter and when I run 'flutter doctor', I have the following problem:

D:\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [VersiÃ³n 10.0.17134.48], locale es-CL)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] Connected devices
    
your help please.

! Doctor found issues in 1 categories.

**Comment by zoechi** [comment]
Sorry for the late response.

You need to accept the Android license.
If you update to a more recent Flutter version you'll get more concrete instructions how to do that.
Starting Android Studio should also ask you to accept the license.

Can you please check if this is this still an issue with recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
