### ISSUE TITLE
onTapUp isn't called after onLongPress

### ISSUE THREAD

**Issue by NotAVampire** [flutter/flutter#17850]
Hello, 

I'm trying to create a context menu that is displayed after a long press whilst keeping your finger held on the object, afterwards you would select an option (by dragging your finger) and lift it to initiate the action.

I noticed something that to me is a little strange. So first, the code: 

```
        import 'package:flutter/material.dart';
        import 'package:flutter/gestures.dart';

        void main() {
          debugPrintGestureArenaDiagnostics = true;

          runApp(new MaterialApp(
            home: new Scaffold(
              body: new GestureDetector(
                onTapUp: (TapUpDetails details) {
                  print("onTapUp");
                },
                child: new GestureDetector(
                  onLongPress: () {
                    print("onLongPress");
                  },
                  child: new Center(
                    child: new FlutterLogo(),
                  ),
                ),
              ),
            ),
          ));
        }

```
So if I run this, after long pressing the icon, then the handler for "onLongPress" is called but after lifting your finger "onTapUp" isn't called. If I comment out the handler for "onLongPress" (all 3 lines) then after a long press "onTapUp" IS called. I would like to handle both "onTapUp" and "onLongPress".

Any ideas why this is happening ? Am I doing something wrong ? Is there a different way of accomplishing this ?

I've tried debugging it but I didn't manage to find a fix so far. What is interesting is the output of the console after setting debugPrintGestureArenaDiagnostics to true. So after a TapUp : 

```
I/flutter (  642): Gesture arena 1    ❙ ★ Opening new gesture arena.
I/flutter (  642): Gesture arena 1    ❙ Adding: LongPressGestureRecognizer#336bf(debugOwner: GestureDetector, state: ready)
I/flutter (  642): Gesture arena 1    ❙ Adding: TapGestureRecognizer#78e3e(debugOwner: GestureDetector, state: ready)
I/flutter (  642): Gesture arena 1    ❙ Closing with 2 members.
I/flutter (  642): Gesture arena 1    ❙ Rejecting: LongPressGestureRecognizer#336bf(debugOwner: GestureDetector, state: possible)
I/flutter (  642): Gesture arena 1    ❙ Sweeping with 1 member.
I/flutter (  642): Gesture arena 1    ❙ Winner: TapGestureRecognizer#78e3e(debugOwner: GestureDetector, state: ready, finalPosition: Offset(203.8, 385.3))
I/flutter (  642): onTapUp
```

And after a LongPress and lifting the finger : 
```
I/flutter (  642): Gesture arena 2    ❙ ★ Opening new gesture arena.
I/flutter (  642): Gesture arena 2    ❙ Adding: LongPressGestureRecognizer#336bf(debugOwner: GestureDetector, state: ready)
I/flutter (  642): Gesture arena 2    ❙ Adding: TapGestureRecognizer#78e3e(debugOwner: GestureDetector, state: ready)
I/flutter (  642): Gesture arena 2    ❙ Closing with 2 members.
I/flutter (  642): Gesture arena 2    ❙ Accepting: LongPressGestureRecognizer#336bf(debugOwner: GestureDetector, state: possible)
I/flutter (  642): Gesture arena 2    ❙ Self-declared winner: LongPressGestureRecognizer#336bf(debugOwner: GestureDetector, state: possible)
I/flutter (  642): onLongPress
```

I think it might have something to do with how GestureArenaManager works after seeing the log.

I have also posted a question on StackOverflow regarding this : https://stackoverflow.com/questions/50426881/flutter-ontapup-isnt-called-after-onlongpress 

If this isn't the correct way of doing this and I'm missing something feel free to correct me and close the issue.

Thanks in advance

**Comment by alchalade** [comment]
I don't know if the PR will be pass but I've solved it with a new gesture onLongPressUp.

Here is the PR https://github.com/flutter/flutter/pull/18949

**Comment by zoechi** [comment]
Closing as dup of #17072
