### ISSUE TITLE
Tabs widget going blank on a specific device

### ISSUE THREAD

**Issue by kaushiksundar** [flutter/flutter#17863]
I am developing an app that uses the TabBar widget. It went blank in a specific device spec alone, I checked in 3 more devices and also in emulator it worked great. I thought it was a bug in the code I wrote, but figured out that the same is happening in the TabBar widget in the Flutter Gallery app. Is this issue specific to certain android versions?

Here is the screenshot of the `Tabs` screen under `Material` menu from the actual device

![screenshot_2018-05-24-12-47-19-280_io flutter demo gallery](https://user-images.githubusercontent.com/5235298/40474267-31315fa2-5f5c-11e8-8ceb-61258566ff7b.png)

# Phone specs:

![device info](https://user-images.githubusercontent.com/5235298/40474587-103a3854-5f5d-11e8-9671-995991ca638e.png)

**Comment by zoechi** [comment]
please add the output of `flutter doctor`
Is this only in debug or release mode, or both?

**Comment by zoechi** [comment]
Is this still an issue with recent Flutter versions?
Can you please post the output of `flutter doctor -v`?

**Comment by kaushiksundar** [comment]
No in the recent version it is working

**Comment by zoechi** [comment]
Thanks a lot for the update!
