### ISSUE TITLE
BottomSheet

### ISSUE THREAD

**Issue by rodrigosuhr** [flutter/flutter#17868]
Hi, how can I add transparency to a bottomsheet? I basically want to make the bottomsheet's background transparent.

**Comment by cbenhagen** [comment]
You can wrap your widgets in an [opacity widget](https://docs.flutter.io/flutter/widgets/Opacity-class.html). Please ask such questions on [StackOverflow](https://stackoverflow.com/tags/flutter).

**Comment by zoechi** [comment]
@rodrigosuhr did @cbenhagen 's suggestion work for you?

**Comment by satish754ss** [comment]
No, it's not working, I also tried this but not working.
