### ISSUE TITLE
Error in package flutter/src/widgets

### ISSUE THREAD

**Issue by gabulsavul** [flutter/flutter#17869]
I/flutter (23617): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23617): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter (23617): 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 215 pos 16:
I/flutter (23617): 'indexOf(child) > index': is not true.

I/flutter (23617): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 215 pos 16: 'indexOf(child) > index': is not true.
I/flutter (23617): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/chatty  (23617): uid=10080(br.com.savioclubpetro.gabriel.revendedorapk) Thread-3 identical 42 lines
I/flutter (23617): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.

**Comment by zoechi** [comment]
please add the output of `flutter doctor` and the code that allows to reproduce the issue.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
