### ISSUE TITLE
How to hide yellow line of overflower.

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#17865]
My expectation is to gradually hide a layout at the top with rolling.

But in debug mode, the yellow line of overflower will be displayed.

How to hide the line in debug mode.

**Comment by zoechi** [comment]
Why do you want to hide it?
What about fixing it, for example using a scroll view or similar so that id doesn't actually overflow?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
