### ISSUE TITLE
Docs about Custom TabController

### ISSUE THREAD

**Issue by firelight22** [flutter/flutter#17864]
I would like to select which tab is "slideable". 
In my app I have 3 tabs. From left to right : A list, a map and another list. 
I want the map not to listen to the swipe event because it's too confusing with the map.

Thanks

**Comment by zoechi** [comment]
Not sure if this does what you want but you could try to pass

    physics: const NeverScrollableScrollPhysics()

to the constructor of the `PageView` you don't want to be slideable

**Comment by firelight22** [comment]
Thank you for your reply @zoechi.

I tried but I don't understand how to specify just for one tab. Because here, it's for all tabs.


```dart
return new MaterialApp(
            theme: new ThemeData(primarySwatch: Colors.blue,),
            home: new DefaultTabController(
                length: 3,
                child: new Scaffold(
                    appBar: new AppBar(
                        bottom: new TabBar(
                            tabs: listTab,
                        ),
                        title: new Text('Nantes Parking'),
                    ),
                    body: new TabBarView(
                        children: [
                            new MyHomePage(title: 'Flutter Demo Home Page'),
                            new MyMapPage(),
                            new MyListFavorite(),
                        ],
                        physics: const NeverScrollableScrollPhysics(),
                    ),
                ),
            ),
        );
```

**Comment by zoechi** [comment]
I assumed `MyHomePage`, `MyMapPage`, `MyListFavorite` are `PageView`s and that has a `physics` property.

**Comment by firelight22** [comment]
I tried this but they are all scrollable. I think that the TabBarView `physics` property override all other `physics` properties.

```dart
body: new TabBarView(
                        children: [
                            new PageView(
                                children: <Widget>[new MyHomePage(title: 'Flutter Demo Home Page')],
                            ),
                            new PageView(
                                children : [  new MyMapPage()],
                                physics: const NeverScrollableScrollPhysics()),
                            new PageView(
                                children: <Widget>[new MyListFavorite()],
                            ),
                        ],
                    ),
```

**Comment by zoechi** [comment]
Is this still an issue?

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by MaterialTime** [comment]
I'm seeing a similar issue. I need to block scrolling to page another page when a condition is met. Is that possible?
