### ISSUE TITLE
Feature request: Allow null values in `child` or `children[]` collections to signal that an element should not be drawn

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#17862]
Often I have the problem how to solve toggling the existence of a widget on a screen, like you have a column and you add one child by calling a function that will decide if this child should be added or not. Currently the only solution for this is to return an empty container.

like in this example

```dart
              child: Stack(
                children: [
                  Container(
                    child: content,
                  ),
                  buildCloseButton()
                ],
```

Where `buildCloseButton()` not will all a Closebutton widget

So I propose that if a null value is found in a `child` or a `children`  this is allowed and interpreted that this element should not be drawn.

What do you think?

Cheers and many thanks for your awesome work!

**Comment by slightfoot** [comment]
I am not sure the description here is "right". 
> So I propose that if a null value is found in a child or a children this is allowed and interpreted that this element should not be drawn.
I get this, but "element should not be drawn" is not the correct term. I think this should be that null is allowed as a Widget reference and is ignored.

**Comment by escamoteur** [comment]
@slightfoot you are right, ignored is better than not been drawn.
Thanks for clarification

**Comment by hnvn** [comment]
I found out that we can achieve this feature by modifying a line in `MultiChildRenderObjectWidget` class, something like this:
```
abstract class MultiChildRenderObjectWidget extends RenderObjectWidget {

  MultiChildRenderObjectWidget({ Key key, List<Widget> children: const <Widget>[] })
    : assert(children != null),
      children = children.where((child) => child != null).toList(), // -> filter and remove null widget
      super(key: key);

  final List<Widget> children;

  @override
  MultiChildRenderObjectElement createElement() => new MultiChildRenderObjectElement(this);
}
```
But I don't think it's a good idea to do because we have to run a loop to filter out null widgets whenever we create a MultiChildRenderObjectElement widget. Using such a `List<Widget>` (that contains nullable element) is not common case, so we should do filter job in our own code, for example:
```
@override
Widget build(BuildContext context) {
   return new Stack(
     children: <Widget>[
        ....
        _buildWidgetIfNeed(),
        ....
        ].where((child) => child != null).toList(),
   );
}

Widget _buildWidgetIfNeed() {
   return (condition) ? new Container(....) : null;
}
```

**Comment by zoechi** [comment]
I agree it's a bit annoying but I think it's better API design to ensure proper parameter values at the API boundary instead of the requirement to check on multiple places in the implementation if a value is `null`.

I hope extension methods will make it into Dart eventually, then this should be much cleaner than `.where((child) => child != null).toList()`.

**Comment by Hixie** [comment]
I suspect we're more likely to change the language to allow optional additions to list literals than we are to allow nulls.

**Comment by escamoteur** [comment]
How could that look like?

**Comment by zoechi** [comment]
@escamoteur I guess something like #16253. Not sure how this would include filtering `null`s though, but I'm sure the Dart and Flutter team will work closely together when they tackle this issue.

**Comment by yjbanov** [comment]
@escamoteur, it could look like https://github.com/flutter/flutter/issues/3783#issuecomment-217597619. @munificent began a more in-depth investigation over in https://github.com/munificent/ui-as-code/blob/master/ideas/control-flow-elements.md.

**Comment by munificent** [comment]
Like @Hixie says, I hope we can solve this in the language and not resort to filtering out nulls. The problem with the latter is that it you have some incorrect code that returns null when you expect it to return a widget, instead of getting an early error that draws your attention correctly to the location of the bug, you just silently get nothing on screen.

**Comment by escamoteur** [comment]
I m happy with any improvement putting it in the language will be helpful in other places too.

**Comment by rrousselGit** [comment]
I don't think to allow null children is good. 

Flutter is quite different to react in how it handles components. I doubt there's an easy solution to handle null cases everywhere at once. Worse, it could require user-created widgets to handle null-cases too.

I think Hixie's suggestion is a very good alternative.

In the mean-time, `sync*` functions can be a pretty good alternative:

```dart
@override
Widget build(BuildContext context) {
  return Row(
    children: buildChildren(context).toList(),
  );
}

Iterable<Widget> buildChildren(BuildContext context) sync* {
  yield Container();

  if (myVariable == 42) {
    yield Text("Hello World");
  }
}
```

**Comment by yjbanov** [comment]
@ahmadmarafa `Center` should allow a `null` child. Many (if not most) single-child widgets do, such as `SizedBox`, `DecoratedBox`, `Padding`, etc. So you can do `Center(child: loading ? CircularProgressIndicator() : null)`. That said, if `Center` is part of a child list, then it itself cannot be elided.

@rrousselGit using `sync*` is a cool idea! I haven't thought of that.

**Comment by Hixie** [comment]
Yeah using `yield` that way is pretty neat. Maybe a shorthand could be developed to represent it, something like:

```dart
  return Row(
    children: sync* <Widget>[
      yield Container();
      if (myVariable == 42)
        yield Text('Hello World');
    ],
  );
```

...or some such. cc @munificent in case this idea is useful.

**Comment by escamoteur** [comment]
Actually I don't think that using yield improves readability. Best is to create the List upfront with `.add` 
Still I think allowing null for single childs instead of passing a SizedBox would be helpful

**Comment by rrousselGit** [comment]
@escamoteur Well, it allows for everything to be in place. And we get access to a spread operator:

```dart
List<Widget> foo;

List<Widget> children = List.from(() sync* {
  yield Text("Foo");
  yield* foo;
  yield Text("Bar");
}());
````

**Comment by escamoteur** [comment]
true but the `yield` and  `sync*`don't increase readability

**Comment by yjbanov** [comment]
@escamoteur, `yield` and `sync*` could be elided if the contents of the list are constructed as comma-separated _expressions_ as opposed to _statements_. Here's @Hixie's example rewritten:

```dart
  return Row(
    children: <Widget>[
      Container(),
      if (myVariable == 42) {
        yield Text('Hello World');
      },
    ],
  );
```

The `yield` would still be needed inside the `if` block because it's just a block of imperative code (i.e. a list of statements). You can do all kinds of things inside it, e.g.:

```dart
  return Row(
    children: <Widget>[
      Container(),
      if (myVariable == 42) {
        yield Text('Hello');
        if (isEarth)
          yield Text('Earth');
        else
          yield Text('Mars');
      },
    ],
  );
```

Taking this further, we could allow unconditional imperative blocks inside list literals, e.g.:

```dart
  return Row(
    children: <Widget>[
      Container(),
      {
        yield Text('Hello');
        if (isEarth)
          yield Text('Earth');
        else
          yield Text('Mars');
      },
    ],
  );
```

**Comment by escamoteur** [comment]
Yeah this looks great

**Comment by rrousselGit** [comment]
That would require modifying every single `MultiChildRenderObjectWidget` to add that parameter to their constructors.

Tedious, with a very minimal gain.

This would also make migration harder for when we'll have non-nullable types. 
`sync*` functions or a `List<T> filterNull<T>(Iterable<T> iterable)` function seems like a better compromise.

**Comment by cbazza** [comment]
> That would require modifying every single MultiChildRenderObjectWidget to add that parameter to their constructors.

So what? It does not cause performance problems yet it improves readability tremendously.

> Tedious, with a very minimal gain.

Improves readability tremendously (the opposite of minimal gain).

> This would also make migration harder for when we'll have non-nullable types.
sync* functions or a List<T> filterNull<T>(Iterable<T> iterable) function seems like a better compromise.

I don't see the problem, default `removeNullChild` to false and it behaves like now, set it to true and it does the null removal for you. All with better readability and no performance hit.

**Comment by rrousselGit** [comment]
What do you dislike with the following?

```dart
children: filterNull([
  ...
])
```

This is both readable and concise.

**Comment by cbazza** [comment]
> This is both readable and concise.

Yes but how would you know that function exists? People will write their own or do the inline monstrosity. As another parameter on the widget constructor, you can't miss it ;)

**Comment by cbazza** [comment]
Even though the proposal here ( #dart-lang/language/issues/47) supports 'null-aware spread' operator, you still need to support single null value removal here.

**Comment by Hixie** [comment]
For single value, you could do something like `...foo`, where `foo` is a list of either 1 or 0 items. e.g. in the original example of `buildCloseButton`, have that return a list of one widget or an empty list instead of returning a widget or null.

**Comment by cbazza** [comment]
Sure but that complicates things; you basically add the artificial restriction that simple variables can not be used where it makes perfect sense to use them. Simple variables can not be used because they can be null. 

If everything now is a list, why not go further and remove the child & children distinction? I mean there is no child just children and when children is a list of 1 that's a child.

**Comment by bgetsug** [comment]
I've been experimenting with these `If` and `Empty` widgets:

```dart
import 'package:flutter/widgets.dart';

typedef Widget WidgetFunction();

class If extends StatelessWidget {
  final bool condition;
  final WidgetFunction then;
  final WidgetFunction or;

  If(this.condition, {@required this.then, this.or});

  @override
  Widget build(BuildContext context) {
    if (condition) {
      return then();
    }

    if (or != null) {
      return or();
    }

    return Empty();
  }
}

class Empty extends Widget {
  @override
  Element createElement() => EmptyElement(this);
}

class EmptyElement extends Element {
  EmptyElement(Widget widget) : super(widget);

  @override
  void forgetChild(Element child) {}

  @override
  void performRebuild() {}
}
```
Example:
```dart
class IfExample extends StatelessWidget {
  final condition = true;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        If(
          condition,
          then: () => Text("You can see me."),
          or: () => Text("I'm not here."),
        ),
        Text("I'm always here."),
        If(
          !condition,
          then: () => Text("You can't see me."),
          or: () => Text("I'm here."),
        )
      ],
    );
  }
}
```
Any Flutter experts notice anything unnecessary or potentially bad (for performance)?

**Comment by rrousselGit** [comment]
There is currently a feature being implemented in Dart for the sole purpose of this: https://github.com/dart-lang/language/issues/78

Which basically allows `if` and `for` within array declarations.


This is infinitely better than all the other proposed solutions, both in performance and syntax.

____

> Any Flutter experts notice anything unnecessary or potentially bad (for performance)?


Definitely worse than a `if`. 

This has many memory allocations and instructions, including creating a Widget, 2 closures, and an Element and managing all of these. 

That's a lot of computation when opposed to a single instruction.



___

The `Empty` is already doable without editing `Flutter`. It's a `LeafRenderObjectWidget` with a RenderObject that does nothing (besides hit testing). 

The gain is unnnoticiable when opposed to a `const SizedBox()` though.

**Comment by bgetsug** [comment]
Ok, for future readers, don't do what I did. Listen to @rrousselGit and use `sync*` while waiting for Dart improvements.

**Comment by dnfield** [comment]
Control flow collections has landed in Dart and should be available in Flutter either now or shortly.

We may just need documentation at this point illustrating how to use these features to acheive the request in this bug.

**Comment by t-artikov** [comment]
Control flow collections does not fit perfectly. It is not possible to check the return value of the function without a temporary variable:
```
final closeButton = buildCloseButton();
Stack(
    children: [
        Container(child: content),
        if (closeButton != null) closeButton,
    ]
)
```

It would be great if Dart had a syntax for excluding nulls in array literals, something like:
```
Stack(
    children: [
        Container(child: content),
        ?buildCloseButton(),
    ]
)
```

**Comment by a14n** [comment]
> It is not possible to check the return value of the function without a temporary variable

See dart-lang/language#323

**Comment by Muldec** [comment]
> Control flow collections has landed in Dart and should be available in Flutter either now or shortly.

Just tested it on my project and Control flow collections is available in flutter

> Flutter 1.5.4-hotfix.2 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision 7a4c33425d (4 days ago) • 2019-04-29 11:05:24 -0700
> Engine • revision 52c7a1e849
> Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**Comment by josvos** [comment]
I would really like this feature too, but Dart now has a new feature called *collection if* (see http://dart-lang.github.io/linter/lints/prefer_if_elements_to_conditional_expressions.html) that may help in some cases:
```
childen: [
   ...
   if (condition) widget,
   ...
]
```
This of course does not help when you want to use `myButton()`, where `myButton` is a function returning a widget or `null`.  I sometimes use `myButton() ?? Container()` for these cases (probably pretty inefficient too), but this can not always be used, e.g. not when you use a `Row` of `Column` with space between elements, e.g. with `MainAxisAlignment.spaceBetween`.

**Comment by josvos** [comment]
Additional comment: note that my main concern is that it is not allowed to have null values in widget *lists* (e.g. `children` parameters).  I can imagine that allowing null values for every widget in any place (e.g. `child` parameters) is technically much more complex.  Doing `.where((x) => x != null).toList()` after a list looks ugly and I'm also wondering how efficient this is.

**Comment by Muldec** [comment]
> This of course does not help when you want to use `myButton()`, where `myButton` is a function returning a widget or `null`. I sometimes use `myButton() ?? Container()` for these cases (probably pretty inefficient too), but this can not always be used, e.g. not when you use a `Row` of `Column` with space between elements, e.g. with `MainAxisAlignment.spaceBetween`.

That's also true for `StreamBuilders` that does not return a widget for every value of the stream.

**Comment by filiph** [comment]
I wonder if we can close this issue. As discussed above, this issue is the reason we now have `if` in Dart's collection literals. I understand this is not the full solution ([comment](https://github.com/flutter/flutter/issues/17862#issuecomment-488599807)) but that corner case is being tracked over at https://github.com/dart-lang/language/issues/323.

Solving this with `null` seems increasingly unlikely as Flutter and Dart converge on Non-nullability by default. Having that feature basically means Flutter will have to always check for `null` for every element in a children lists, which erases the benefits of NNBD for this particular (and very common) case.

**Comment by escamoteur** [comment]
I agree the ifs are awesome

**Comment by rrousselGit** [comment]
> I understand this is not the full solution (comment) but that corner case is being tracked over at dart-lang/language#323.

To be fair, that specific case should probably be transformed into:

```dart
[
  if (condition)
    buildSomething(),
]
```

instead of having `buildSomething` return `null`.

**Comment by RaoSaqib7860** [comment]
Now you can handle null value 
Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Center(child: Text('data1')),
              ...o.map((element) {
                if (element != 4) return Text('yes');
                return null;
              }),
              Center(child: Text('data4')),
            ].where((element) => element != null).toList()),
