### ISSUE TITLE
Support setting background for FlutterView

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#17874]
FlutterView is black until the isolate can load and run the Flutter app. To allow users to customize the color (or even assign a drawable), FlutterActivityDelegate renders a view _on top of_ the FlutterView until the first frame is rendered.

It would be great if this trick was not necessary and FlutterView itself could support customizing what's being shown on the canvas until the Flutter frame is rendered.

The rationale is that apps would have to copy/paste this trick in add-to-app use cases such as:
- Adding FlutterView to a Fragment
- Adding FlutterView to a custom activity

**Comment by mehmetf** [comment]
I heard another use case for this from customer dream. They would like to have the FlutterView be "transparent" because the user might skin the native app and they want this skin to show through. An interim solution is to pass that skin to Flutter too so it can be rendered as a background but it will lead to artifacts.

I believe it is possible to create a `Material` canvas with transparent background from within Flutter. We need to make sure FlutterView can support being transparent :-).

**Comment by mehmetf** [comment]
Not really.

FlutterView is effectively a SurfaceView. We should be able to set the background color to transparent for that; however Flutter engine itself also draws [a background color](https://github.com/flutter/engine/blob/63e2071da8bd4400addab933f32b9e8728702c1b/shell/platform/android/io/flutter/view/FlutterView.java#L162). My knowledge is very superficial in that area.

**Comment by Hixie** [comment]
My understanding is that making it transparent is possible but has performance implications.

I agree we should support making it transparent. Seems reasonable to support solid color as well since that presumably doesn't have the performance implications.

**Comment by mit-mit** [comment]
This may no longer be relevant; the Flutter View in the module template hides itself until it is ready to render

**Comment by mit-mit** [comment]
cc @mehmetf WDYT?

**Comment by matthew-carroll** [comment]
@mit-mit Maybe it deserves a separate ticket, but the issue of a transparent background on a Flutter View goes well beyond initial loading considerations.

**Comment by mehmetf** [comment]
@mit-mit What does the hide behavior look like? Does the Flutter view "pop" out of nowhere when ready? or does it occupy space but shows the background (i.e. transparent)?

@matthew-carroll, you are right. Transparent flutter view (and its use cases) should be a separate ticket.

**Comment by matthew-carroll** [comment]
Here is the plan for this issue:

We now support transparency in FlutterView which means the black background can be avoided.  In the Android embedding refactor I'm also adding support for explicit splash color and a splash drawable.  Those 2 abilities together should address the use-case issues in this ticket.

If I've missed anything, please re-open.
