### ISSUE TITLE
Connect to a running Flutter app and hot reload

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#17872]
As part of add-to-app effort, we should make Flutter work with the existing application runner. So, one step towards letting developers use their existing deployment flow is enabling hot reload without a flutter runner.

This would also help with when vm_service loses connection to the device. Currently, we recommend developers to rebuild/redeploy their apps. While we track frequent connection loss as separate bugs (internal b/79702390), being able to reconnect would be a better workaround than a full rebuild which often takes 30+ seconds.

**Comment by mehmetf** [comment]
Related: https://github.com/flutter/flutter-intellij/issues/2250

**Comment by mit-mit** [comment]
@mehmetf we now have a new `flutter attach` command for this. Can you see if that works for the google internal workflow also?

**Comment by mehmetf** [comment]
This issue is for external flow so if there's a command to do this now, the issue can be closed. We will need to do some work to wire it in; tracked internally (b/111230095).

**Comment by mit-mit** [comment]
Great, closing
