### ISSUE TITLE
ListView overexpands when at top of list

### ISSUE THREAD

**Issue by dmjones** [flutter/flutter#17880]
## Steps to Reproduce

When the list is scrolled to the top, the list overlaps the elements beneath it. As soon as I scroll down a little, the list respects the boundaries of the Expanded element it sits within and the overlapping stops.

![image 1](https://i.stack.imgur.com/9CxwJ.png) ![image 2](https://i.stack.imgur.com/Stgyc.png)

Above, the left image shows the flaw. Note how the elements are overlapping the red area. The right image shows the situation once I've scrolled a little, now we can see the correct space appearing above the red area.

Sample code is here: https://gist.github.com/dmjones500/4eda8c2a6e69edf1bcdfd62ac94ac9b1

## Logs

Flutter run log is here: https://gist.github.com/dmjones500/8e5b3b0ba635a08b426955c7c8bea7de

```
Analyzing scratch...                                             
No issues found! (ran in 1.3s)
```

```
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-GB)
    • Flutter version 0.4.4 at /Users/duncan/git/flutter
    • Framework revision f9bb4289e9 (13 days ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/duncan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4668.60

[✓] Connected devices (1 available)
    • iPhone X • 03BDC90A-3750-47C1-9C70-6DF9BD2F34A8 • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by dmjones500** [comment]
Also discussed at https://stackoverflow.com/questions/50516141/listview-overlaps-elements-when-at-top-of-list.

**Comment by zoechi** [comment]
Might be related to #17716

**Comment by ctjl96** [comment]
I'm also having this issue, hoping it gets fixed soon! Oddly enough, the top ListView is inside a PageView, and it does not have this issue.  The bottom one is just a plain ListView nested in some column/row stacks.  I've reversed the order to confirm that the ListView inside the PageView does not show this bug, but it's a custom PageView so it may not be the only factor.

![device-2018-05-27-233619](https://user-images.githubusercontent.com/1657236/40597385-ce6d3348-6206-11e8-8564-f6c563743e6a.png)

**Comment by kushal-kapoor** [comment]
even me

**Comment by kushal-kapoor** [comment]
is there any thing wrong here
`import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
//import 'package:firebase_messaging/firebase_messaging.dart';

void main() {
  runApp(new MaterialApp(home: new SecondScreen()));
}


class SecondScreen extends StatelessWidget {
  Builder builder = new Builder();
  Monetization monetization = new Monetization();
  static double total = 0.0;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Order Summary"),
        ),
      body: new Center(
        child: ListView(
          children: <Widget>[
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 8.0,
                ),
              ),
            new Card(
              child: Column(
                children: <Widget>[
                  new Opacity(
                    opacity: 0.0,
                    child: new Divider(
                      height: 8.0,
                      ),
                    ),
                  new Row(
                    children: <Widget>[
                      new Text(
                        // leading: new Icon(Icons.photo_album),
                        "Order Number",

                          style: new TextStyle(
                              fontWeight: FontWeight.bold, fontSize: 20.0),
                        ),
                    ],
                    ),
                  new Row(
                    children: <Widget>[
                      new Text(
                        // leading: new Icon(Icons.photo_album),
                        "Date",
                          style: new TextStyle(fontSize: 12.0),
                        ),
                    ],
                    ),
                  new Opacity(
                    opacity: 0.0,
                    child: new Divider(
                      height: 8.0,
                      ),
                    ),
                ],
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 24.0,
                ),
              ),
            new Row(
              children: <Widget>[
                new Text(
                  // leading: new Icon(Icons.photo_album),
                  "Products",
                    style: new TextStyle(fontSize: 16.0),
                  ),
              ],
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 8.0,
                ),
              ),
            new Card(
              child: new Column(
                children: <Widget>[
                  new Opacity(
                    opacity: 0.0,
                    child: new Divider(
                      height: 8.0,
                      ),
                    ),
                  new Row(
                    children: <Widget>[
                      new Text("Fulfilled"),
                    ],
                    ),
                  new Container(
                    height: 60.0,
                    child: new ListView(
                      children: <Widget>[
                        builder.List_Item("gsuv", "vsfgpsdj", 657, 2, 0),
                        builder.List_Item("sfsd", "dfbndidb", 457, 7, 24),
                      ],
                      ),
                    ),
                  new Opacity(
                    opacity: 0.0,
                    child: new Divider(
                      height: 8.0,
                      ),
                    ),
                  new Row(
                    children: <Widget>[
                      new Text("UnFulfilled"),
                    ],
                    ),
                  new Container(
                    height: 60.0,
                    child: new ListView(
                      children: <Widget>[
                        builder.List_Item("gsuv", "vsfgpsdj", 657, 2, 0),
                        builder.List_Item("sfsd", "dfbndidb", 457, 7, 24),
                      ],
                      ),
                    ),
                ],
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 20.0,
                ),
              ),
            new Text(
              "Bill Details",
              style: new TextStyle(fontSize: 16.0),
              ),
            new Card(
              child: new Container(
                height: 120.0,
                child: new Column(
                  children: <Widget>[
                    new ListTile(
                      title: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[new Text("total")],
                            ),
                          new Row(
                            children: <Widget>[new Text("dicount")],
                            ),
                        ],
                        ),
                      trailing: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[new Text("6536")],
                            ),
                          new Row(
                            children: <Widget>[new Text("345")],
                            ),
                        ],
                        ),
                      ),
                    new ListTile(
                      title: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[new Text("CGST")],
                            ),
                          new Row(
                            children: <Widget>[new Text("SGST")],
                            ),
                        ],
                        ),
                      trailing: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[new Text("764")],
                            ),
                          new Row(
                            children: <Widget>[new Text("764")],
                            ),
                        ],
                        ),
                      ),
                  ],
                  ),
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 8.0,
                ),
              ),
            new Text(
              // leading: new Icon(Icons.photo_album),
              "Payment Details",
                style: new TextStyle(fontSize: 16.0),
              ),
            new Card(
              child: Container(
                height: 112.0,
                child: Column(
                  children: <Widget>[
                    monetization.listItem(267, "Cash"),
                    monetization.listItem(267, "Card"),
                  ],
                  ),
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 8.0,
                ),
              ),
            new Text(
              // leading: new Icon(Icons.photo_album),
              "Customer Details",
                style: new TextStyle(fontSize: 16.0),
              ),
            new Card(
              child: Container(
                height: 50.0,
                child: new ListTile(
                  title: new Column(
                    children: <Widget>[
                      new Row(
                        children: <Widget>[new Text("NAME")],
                        ),
                      new Row(
                        children: <Widget>[new Text("PHONE")],
                        ),
                    ],
                    ),
                  trailing: new Row(
                    children: <Widget>[new Icon(Icons.create)],
                    ),
                  ),
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 8.0,
                ),
              ),
          ],
          ),
        ),
     );
  }
}
class Builder extends StatelessWidget {
  double total = 0.0;

  @override
  Widget build(BuildContext context) {
    return null;
  }

  Widget List_Item(String name, String description, int indPrice, int quantity,
      int discountPercent) {
    int price = quantity * indPrice;
    double opac = 0.0;
    double disc = (discountPercent / 100);
    double mdiscPrice = disc * price;
    String discPrice = mdiscPrice.toStringAsFixed(2);
    // discPrice = discPrice.round() as double;
    //  double discount = discPrice as double;
    mdiscPrice != 0.0 ? opac = 1.0 : opac = 0.0;
    //  double final_price = price - discount;
    //   total = total + final_price;
    return new ListTile(
      leading: new Checkbox(value: false, tristate: true, onChanged: null),
      title: new Row(
        children: <Widget>[
          new Column(
            children: <Widget>[
              new Text("name"),
              new Text("description"),
            ],
            ),
        ],
        ),
      trailing: new Row(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          new Container(
            padding:EdgeInsets.all( 30.0),
            child: new Text('X$quantity '),
            ),
          new Column(
            children: <Widget>[
              new Text('        price'),
              new Opacity(
                opacity: opac,
                child: new Text('-discPrice'),
                ),
            ],
            ),
        ],
        ),
      );
  }
}

class Monetization extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return null;
  }

  Widget listItem(
      int price,
      String mode,
      ) {
    bool cash = false;
    if (mode == 'Cash') {
      cash = true;
    }
    return new ListTile(
      title: new Text('mode'),
      leading: new Icon(
        cash ? Icons.attach_money : Icons.credit_card,
        ),
      trailing: new Text('price'),
      );
  }
}
`

**Comment by pboos** [comment]
Ran into the same problem here.

My setup
```
Column
- Expanded
  - ListView
- Expanded
  - Graph
```
When the ListView is scrolled to the top (as it is in the initial state), then i see the list overlapping (or being drawn behind?) the bottom element.

The list itself has the right size (in the inspector) but seems to draw out of its bounds. Even if they are not drawn, the inspector shows the items outside of its bounds (just not visible on the screen). But it seems they are not hidden correctly if at the top of the list.

**Comment by chrishiste** [comment]
Also ran into this bug today, changing the height of my list items fixed it for me, I changed it from 70.0 to 85.0. It seems like all the values below 85 caused the bug but above it works. I have no clue what is going on. The bug only occurred when at the top of the scroll view with enough content to be scrollable. My code:
```dart
 return SizedBox(
        height: _height * 0.35,
        child: ListView(
            primary: true,
            itemExtent: 85.0,
            shrinkWrap: true,
            children: _buildChoices()),
      );
```

**Comment by dmjones** [comment]
@ctjl96 @chrishiste @kushal-kapoor Can you add a thumbs up to my issue (top post in this chain). Not totally sure, but I think the Flutter crew use that to help figure out which issues need attention.

**Comment by zoechi** [comment]
@dmjones is this still an issue with a recent Flutter version?

**Comment by chrishiste** [comment]
@dmjones Done ;)

**Comment by sfo** [comment]
@zoechi For me, the recent version (0.5.6) resolved this.

To get this version you have to switch to the dev channel:
```
flutter channel dev
flutter upgrade
```

**Comment by chrishiste** [comment]
@sfo  

Oh nice, just a quick question do you think we should switch to dev because the documentation says:

> We strongly recommend tracking the beta branch in the flutter repository, which is where we push ‘known good builds’ of Flutter. 

I'm not sure, if it's not better to just wait for the beta channel to be merged.

**Comment by zoechi** [comment]
@chrishiste In my experience `dev` is the better channel because everything around Flutter is moving so fast and `beta` easily gets outdated because it's update-cycle is too long.
It may also depend on your teams workflow or preferences whether `beta` or `dev` is the better choice. 
Also over time `beta` might become the better choice when not so many things keep changing at the same time.

**Comment by chrishiste** [comment]
@zoechi Thanks, I'm sold

**Comment by zoechi** [comment]
I'm going to close as fixed then. 
Feel free to add a comment to get it reopened if you think this isn't fixed.

**Comment by infohashref** [comment]
> @zoechi Thanks, I'm sold
> 
> If fixed the bug for me too :D

how you fixed ?

**Comment by chrishiste** [comment]
I don't remember exactly but it seems switching to the Dev branch was enough. @infohashref
