### ISSUE TITLE
FlexibleSpaceBar should expose maximum scaleValue

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#17887]
Often times the default 1.5x scale when fully expanded is a bit large for my title.

It would be great if I could do something like:

```dart
new SliverAppBar(
  pinned: true,
  expandedHeight: 140.0,
  expandedScale: 1.25,
  flexibleSpace: new FlexibleSpaceBar(
    title: new Text('My Title'),
  ),
```

or within the `FlexibleSpaceBar` like so:
```dart
new SliverAppBar(
  pinned: true,
  expandedHeight: 140.0,
  flexibleSpace: new FlexibleSpaceBar(
    title: new Text('My Title'),
    expandedScale: 1.25,
  ),
```

The relevant line of code where scaling happens: https://github.com/flutter/flutter/blob/70772ea5a00a9518bea3e611c5008181df3423fe/packages/flutter/lib/src/material/flexible_space_bar.dart#L165

**Comment by niallshaw** [comment]
Any news on this?

**Comment by aragonet** [comment]
I think it would be great if user could specify whether he wants to scale and what the maximum value should be.

Hope this proposal goes further
