### ISSUE TITLE
Extract showDialog from material to widget

### ISSUE THREAD

**Issue by xster** [flutter/flutter#17893]
There are some material specific knowledge in the showDialog static flow. But it also means there's no generic function for showing Cupertino dialogs. Extract the logic.

**Comment by xster** [comment]
also todo: remove the material import from https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/cupertino/cupertino_dialog_demo.dart

**Comment by xster** [comment]
cc @matthew-carroll you may also be interested in this since you just did the cupertino dialogs.

**Comment by matthew-carroll** [comment]
Is there anyone in particular that's going to tackle this? Or is it just on the Cupertino TODO list?

**Comment by xster** [comment]
No one assigned yet. It's just whomever lands on this first going down the project task list.

**Comment by nataliesampsell** [comment]
Closing, implemented in https://github.com/flutter/flutter/pull/20152.
