### ISSUE TITLE
flutter upgrade command try to install new dart-sdk but access denied error 

### ISSUE THREAD

**Issue by nni123** [flutter/flutter#17898]
if anyone encounter this error on windows "Rename-Item $dartSdkPath "$oldDartSdkPrefix$oldDartSdkSuffix"" during recent flutter upgrade to 0.4.4. Error was regarding renaming dart sdk in [<flutter install location>/bin/cache/dart-sdk] directory. Upgrade process was throwing error of access denied to rename <dart-sdk> directory.

The error came from this source file https://github.com/flutter/flutter/blob/master/bin/internal/update_dart_sdk.ps1

Yes it was upgrading dart-sdk come with flutter C:\Users\lenovo\software\flutter\bin\cache\dart-sdk. I think the previous upgrade created dart-sdk.old and new dart-sdk install tries to do the same hence the access denied error.

I believe line 24 has hard coded value ="dart-sdk-old". Either install process should delete that directory or if it exist try to create another name <dart-sdk-old1>

**Comment by hudson-dev** [comment]
This did not work for me. After running the command I got: fatal: not a git repository (or any of the parent directories): ,git
