### ISSUE TITLE
Google sign in  PlatformException(status, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)

### ISSUE THREAD

**Issue by harriscreativity** [flutter/flutter#17906]
```
try {
    await _googleSignIn.signIn();
  } catch (error) {
  print("ERROR IS : "+ error.toString());
}
```

  google_sign_in: 2.1.1
  flutter_facebook_login: "^1.1.1"

I/flutter (25282): ERROR IS : PlatformException(status, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)

**Comment by zoechi** [comment]
Probably https://stackoverflow.com/questions/37273145/error-statusstatuscode-developer-error-resolution-null

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
