### ISSUE TITLE
Material ink ripple error.

### ISSUE THREAD

**Issue by JoshGaunt** [flutter/flutter#17901]
With any component in this app that implements an ink ripple effect when pushed, if you swipe quickly away, as the ink ripple is animating, it draws the ripple permanently on the component and darkens if you do this repeatedly.

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by HansMuller** [comment]
This sounds like an InkRipple bug that was recently fixed: https://github.com/flutter/flutter/pull/17787

**Comment by zoechi** [comment]
Seems to be fixed as commented above.
