### ISSUE TITLE
'MySQL' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by bhavincb** [flutter/flutter#17907]
## Steps to Reproduce

running `flutter` or `flutter doctor` gives below error

## Logs

```
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.
```

 `flutter doctor -v`  also gives same log as above. i'm stuck at here.

**Comment by zoechi** [comment]
That's really weird. Flutter doesn't use MySql in any way.

**Comment by bhavincb** [comment]
Yes I also checked code. And found no use of MySQL . That is why I had
opened issue.

**Comment by bhavincb** [comment]
hii @zoechi ,
any idea on this? i'm stuck at starting flutter.

**Comment by zoechi** [comment]
No ideas. I can't imagine this being caused by Flutter.

**Comment by bhavincb** [comment]
hii @zoechi ,
removing `C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;` and `C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;` from system variable `Path` solved issue.
but still doesn't understand why this error was raising.

**Comment by zoechi** [comment]
Sounds like these MySQL directories contain a `flutter` command.

**Comment by fmatosqg** [comment]
Having `&` in the path in a linux based system sounds quite dangerous. Your OS is clearly not linux but there may be assumptions inside flutter tools that get confused by that.

If you're willing to do an experiment, add something in the fashion of `C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & ABC123` and see if you get an error for `ABC123` not found instead.

Can you post the whole output from `flutter -v` into a gist (http://gist.github.com/)  and add the link here? Better if you can reproduce it with the `ABC123` example.

**Comment by bhavincb** [comment]
hii @fmatosqg ,

adding `C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & ABC123;` does gives me below error.
```
'ABC123' is not recognized as an internal or external command,
operable program or batch file.
'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.
```

you where right original issue was having `&` inside the path.
also issue only exist for `flutter` command. other commands like `git` and `npm` working perfectly fine.

here is gist as you asked: [https://gist.github.com/bhavincb/af059afc27c814808b2e92d3a6aa910e](https://gist.github.com/bhavincb/af059afc27c814808b2e92d3a6aa910e)

**Comment by Lucem-Anb** [comment]
Please check this : I managed to face the error and fix it with a different lib
https://stackoverflow.com/questions/50776550/flutter-mysql-is-not-recognized-as-an-internal-or-external-command

**Comment by Lucem-Anb** [comment]
@Eng-MohamedGadala I appreciate your upvote

**Comment by zoechi** [comment]
I assume this is solved.
Please add a comment if you think there is something that needs to be done by the Flutter team and I'll reopen.

**Comment by zoechi** [comment]
@dawningtruth 

Flutter doesn't contain any mention of `mysql` anywhere it it's codebase.
The issue has to be on your system setup.
Please add the output of `flutter doctor -v` and everything where `mysql` appears in your environment setting.
You should get the environment by executing 
```
env
```
in a terminal window
You can also try
```
env | grep -i mysql
```
to get only the output where `mysql` appears.

**Comment by mirkoarnold** [comment]
Unfortunately, the Zip provided on flutter.io gave me a problem. To avoid this error, I had to use the GitHub repository following the following procedure.

Go to C:\ Drive and create a folder called flutter.
Go to that folder and start git bash
Type git clone -b beta https://github.com/flutter/flutter.git and enter
After its complete, add the path C:\flutter\flutter\bin in environment variables
Finally, start CMD and type flutter doctor and the error is disappeared

source: https://stackoverflow.com/questions/50776550/flutter-mysql-is-not-recognized-as-an-internal-or-external-command

**Comment by timsar2** [comment]
Same Error:  zip file downloaded from flutter site.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.
