### ISSUE TITLE
Hot reload does not work in VSCode

### ISSUE THREAD

**Issue by dashMrl** [flutter/flutter#17912]
When I pressed `cmd+s` , nothing changed and got the error below:
```
NoSuchMethodError: The getter 'isClosed' was called on null.
Receiver: null
Tried calling: isClosed
```

It's so ridiculous to see hot reload works fine in Android Studio.

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by solomon-okolie** [comment]
Same here. Works fine on Android Studio and IntelliJ. flutter doctor -v output below

[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.15063], locale en-GB)
    • Flutter version 0.4.4 at C:\Flutter\flutter
    • Framework revision f9bb4289e9 (2 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\AndroidSetup\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\AndroidSetup\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1
    • Flutter plugin version 24.1.2
    • Dart plugin version 181.4203.498

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.1

[√] Connected devices (1 available)
    • SM G935F • ce01171141a5b8a20c • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by dashMrl** [comment]
`flutter doctor -v` output :
```
[✓] Flutter (Channel master, v0.0.0-unknown, on Mac OS X 10.13.4 17E202, locale en-CN)
    • Flutter version 0.0.0-unknown at /Users/xavier/tools/flutter
    • Framework revision e816b89a1f (13 hours ago), 2018-05-25 11:03:47 -0700
    • Engine revision abd74ed5ed
    • Dart version 2.0.0-dev.55.0.flutter-97b6c2e09d

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/xavier/tools/android_home
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/xavier/tools/android_home
    • Java binary at: /Applications/Android Studio 3.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b02)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b02)

[!] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by DanTup** [comment]
@dashMrl Could you enable [Flutter Run logging](https://dartcode.org/docs/logging/#flutter-run) and provide the log? Where are you seeing the error you posted? Is there a full stack trace?

I think there's also something weird about your `flutter doctor` output; the version number is missing? Here's what mine looks like:

```text
[✓] Flutter (Channel master, v0.4.5-pre.52, on Mac OS X 10.13.4 17E202, locale en-GB)
    • Flutter version 0.4.5-pre.52 at /Users/danny/Dev/Google/flutter
    • Framework revision 8717a5e6f7 (7 days ago), 2018-05-19 03:19:35 +0300
```

It may be worth making the sure working tree is clean (or updating to a different changeset).

**Comment by DanTup** [comment]
Also; if you run `Flutter: Hot Reload` from the command palette or press the `Restart` button on the debug toolbar, do you get the same issue, or does it work?

**Comment by DanTup** [comment]
Also:

1. The `flutter doctor` output suggests you don't have the Android Studio flutter plugin installed - is this the same machine where it works in Android Studio?

2. If you run `Flutter: Hot Reload` from the command palette or press the `Restart` button on the debug toolbar, do you get the same issue, or does it work?

**Comment by dashMrl** [comment]
Here is the log file: 
[flutterRunLogFile.txt](https://github.com/flutter/flutter/files/2041413/flutterRunLogFile.txt) , cleaned the cache before pressing `F5`

I'm using Android Studio 3.2 Canary 15, and created environment variables  for zsh : 
```
export FLUTTER_ROOT=$HOME/tools/flutter
export PUB_HOSTED_URL=https://pub.flutter-io.cn
```

**Comment by dashMrl** [comment]
I got these messages when the project is opened on Android Studio 3.2 Canary :
![screen shot 2018-05-26 at 3 39 27 pm](https://user-images.githubusercontent.com/15999179/40573884-04b9e30e-60fb-11e8-881f-40baf05e689a.jpg)
```
3:39 PM  Unsupported Android Studio version: Canary versions of Android Studio are not supported by the Flutter plugin.
```

**Comment by dashMrl** [comment]
@DanTup 
I fotgot mentioning I cloned the repo with depth option ：`--depth=1`, so all the tags were lost

**Comment by DanTup** [comment]
@dashMrl Thanks! Do you see any similar issues if you run from the command line and press `r` to reload? Could you also try enabling the [Observatory Log](https://dartcode.org/docs/logging/#observatory) to see whether we stack traces for the errors in there?

**Comment by dashMrl** [comment]
@DanTup Thanks for your awesome works! I pulled the latest commit from branch master just now, and found Hot Reload is working both on VSCode and Android Studio 3.2 Canary 15.
And here is the  Observatory Log file :
[observatoryLogFile.txt](https://github.com/flutter/flutter/files/2045861/observatoryLogFile.txt)

**Comment by DanTup** [comment]
I'm not exactly sure what the issue is or what fixed it, but glad it's working. I'm not sure if that log is from when it was broken or working, but there's nothing obviously bad in there (there is a rogue Resume call, but it shouldn't cause any issues like this).

The issue Tim linked above I think is unrelated - that's caused by the Visual Studio Live Sharing extension interfering with debugging, so would only affect VS Code (though should be fixed by a workaround in Dart Code going out later in the week and a change in the VSLS extension going out tomorrow).

**Comment by DanTup** [comment]
> But the Dart and Flutter extensions are installed in VSCode (...and they are not disabled).

It's safe to ignore that `doctor` says you don't have them in the current beta; there's a bug (fixed in dev/master) in the extension detection but it won't affect anything.

There's a lot of stuff in this issue that's probably unrelated to yours so it's probably best to open a new issue. Some things to include:

- What happens if you run from the terminal (`flutter run`) and then press `r` to reload there? Any message?
- Capture a `Flutter Run` log file using the [`Dart: Capture Logs`](https://dartcode.org/docs/logging/) command in VS Code
- Try temporarily [switching to the `dev` or `master` channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels) to see if the issue may have already been fixed

**Comment by NorbertMerkli** [comment]
@DanTup Thanks for your advice, but I've solved the problem. It was my fault! I'm a very beginner who just experimenting with the framework.

My "main.dart" file looks like this:
_________________________________________________
import 'package:flutter/material.dart';

void main() {
  var app = MaterialApp(
    home: Scaffold(
      appBar: AppBar(
        title: Text('Flutter Experiment'),
      ),
    ),
  );

  runApp(app);
}
_________________________________________________

...so I need a restart, not a reload when I change the text in the Text Widget!

Sorry for my stupid comment!

**Comment by zoechi** [comment]
Hot reload doesn't re-execute all code, it just updated the code in memory and then invalidates the root widget so `build()` is executed again for the whole tree.
Anything that is not updated by `build()` will not updated in the UI.

Affected are for example model dialogs that have their own root widget or code that is executed before `runApp(app)` like in your example

```dart
  var app = MaterialApp(
    home: Scaffold(
      appBar: AppBar(
        title: Text('Flutter Experiment'),
      ),
    ),
  );
```

So there are a few less common situations where you need to restart instead of reload.

See also https://flutter.io/hot-reload/#recent-code-change-is-included-but-app-state-is-excluded

**Comment by DanTup** [comment]
Glad you got it sorted :) When I implemented hot reload in VS Code I also didn't realise changes in `main` method wouldn't reload (the Hello World example is all inlined) so I spent a while scratching my head over it too (and [it's not just us](https://github.com/flutter/flutter/issues/12095)). Hopefully we can communicate this sort of thing better in future (we have [tried some things previously](https://github.com/Dart-Code/Dart-Code/issues/502#issuecomment-362558355), but they weren't reliable enough).

**Comment by NorbertMerkli** [comment]
@zoechi Thanks for the explanation and thanks to all of you for the framework! I really like it!

**Comment by zsirfs** [comment]
by `flutter run -v`, look up:

```text
NoSuchMethodError: The getter 'isClosed' was called on null. Receiver: null
```

How to do? vscode can't hot reload.

**Comment by zsirfs** [comment]
thank you @DanTup . I had added `-v` to the `args`. look:

```json

"version": "0.2.0",
  "configurations": [
    {
      "name": "wk-flutter",
      "request": "launch",
      "type": "dart",
      "args": ["-v"]
    }
  ]
```
I had submited the issus. the link is `https://github.com/flutter/flutter/issues/22253`.
thanks again.

**Comment by zsirfs** [comment]
When I run the debug command in flcode directly to generate the debug command, it will cause my iPhone X emulator to be white screen. If I use the custom `lanch.json`, then I will bring the `-v` parameter and it will run. . But it will burst out of this error #22253

**Comment by zsirfs** [comment]
Now，the hot replace is not work.I am very worry.

**Comment by zsirfs** [comment]
This is my `flutter doctor -v` result:

```text
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.8.2 at /Users/zheng/android/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/zheng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/zheng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone X • 6DBBD95F-4D36-47CF-892C-171BFDE35AB4 • ios • iOS 12.0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
@zsirfs If you'd added `-v` to `args` then you may be hitting a bug in VS Code where running Flutter in verbose mode could result in connecting to Observatory too early. Try installing [this beta version](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.19.0-beta.1) and see if the issue goes away.

**Comment by zsirfs** [comment]
thank you reply to me. let me try.

**Comment by craxet** [comment]
I had the same Issue with VS code because I was firing the emulator up from VS code debug >> start debugging on the Menu tab. **I solved** the Issue by stopping the app and re-running it from the console using 'flutter run' the pressing r to reload

**Comment by DanTup** [comment]
@craxet running from the terminal means you won't be able to use the debugger. If you're having issues when launching with F5/Start Debugging from VS Code, please open an issue https://github.com/Dart-Code/Dart-Code and attach a log captured with the [`Dart: Capture Logs` command](https://dartcode.org/docs/logging/#capture-logs-command).

**Comment by icarojobs** [comment]
Stop flutter run with "q" key on terminal and just press "F5" (on VS Code).

Enjoy!

**Comment by zeh** [comment]
This was likely due to an old bug, but if anyone is getting this recently and ended up in this page (as I did), the inability to hot reload/debug in VSCode was caused [by a bug on VSC 1.32.1](https://github.com/Dart-Code/Dart-Code/issues/1518) and already fixed in the latest insider's version.

**Comment by DanTup** [comment]
VS Code 1.32.2 has now been released and contains the fix for the recent issue mentioned above.
