### ISSUE TITLE
Connectivity should provide more types of ConnectivityResult

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#17916]
When changing the "Data status" in the Android Emulator settings in the "Cellular" tabs I can trigger updates in the `_onConnectivityChanged` stream. It will return `ConnectivityResult.cellular` for every option apart from "Roaming". When selecting "Roaming" as the "Data status" the result changes to `ConnectivityResult.none`. I wished that it also reported something different for "Searching", "Denied" and "Unregistered (off)" because those will definitely not deliver connectivity as well!

**Comment by zoechi** [comment]
@Hixie
