### ISSUE TITLE
Improvement suggestion to help to fix Android issues dependencies hard to find

### ISSUE THREAD

**Issue by acrozes** [flutter/flutter#17926]
When we add lot of packages, there are often the same Android dependency with some incompatibles versions (or too old versions), added to the flutter project.
So, when we add or upgrade packages, a warning message to explain which Android dependency is problematic would be very helpfull.
Then we can easly fix the version in the file app\build.gradle like that way: 

```
[...]
configurations.all {
    resolutionStrategy {
        force 'com.google.android.gms:play-services-location:15.0.0'
    }
}
```

**Comment by gerryhigh** [comment]
I just got bit by this issue. I'm using both a [location package](https://pub.dartlang.org/packages/location) and[ google_maps_flutter package](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter) and they were using different versions of google play services. Net result is I got this runtime error below.

>  Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>: java.lang.NoClassDefFoundError: Faile
> d resolution of: Lcom/google/android/gms/internal/zzbfm;
> I/zygote  ( 2954):   at void io.flutter.plugins.googlemaps.GoogleMapBuilder.<init>() (GoogleMapBuilder.java:15)

**google_maps_flutter** was using 'com.google.android.gms:play-services-maps:11.8.0' whereas **location** was using 'com.google.android.gms:play-services-location:15.+'

To fix the runtime issue I modified my fork of google_maps_flutter to use the same 15.+ version.

**Comment by zoechi** [comment]
Similar to #17046

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

See also this comment https://github.com/flutter/flutter/issues/17046#issuecomment-388761358
