### ISSUE TITLE
RefreshProgressIndicator stops spinning after ~5-6 seconds

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#17923]
After a certain amount of time, `RefreshProgressIndicator`s stop spinning and reset to their initial state. This is inconsistent with the behavior of `CircularProgressIndicator`. Our UX designer wants us to use `RefreshProgressIndicator` in many places in our app, so we need this to be fixed for launch.

This is broken if you're using a `RefreshIndicator` too.

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
      home: new Scaffold(
          appBar: new AppBar(
            title: new Text('Test app'),
          ),
          body: _body)));
}

Widget get _body {
  return new RefreshIndicator(
    onRefresh: () => new Future.delayed(const Duration(seconds: 10)),
    child: new ListView(
      physics: const AlwaysScrollableScrollPhysics(),
      children: <Widget>[
        new Container(height: 16.0),
        new Center(child: new CircularProgressIndicator()),
        new Container(height: 16.0),
        new Center(child: new RefreshProgressIndicator()),
      ],
    ),
  );
}
```

See low FPS gif below. I've also attached the original video.

![ezgif-3-dd64680a47](https://user-images.githubusercontent.com/2225255/40567362-c8f03746-6029-11e8-9520-24dfb52232f1.gif)

[demo.mp4.zip](https://github.com/flutter/flutter/files/2040926/demo.mp4.zip)

**Comment by najeira** [comment]
same as #13782

**Comment by Hixie** [comment]
cc @HansMuller
