### ISSUE TITLE
Error when trying to perform full restart (Hot Reload - Caps R) 

### ISSUE THREAD

**Issue by Josemboa** [flutter/flutter#17929]
When I press Caps R to perform a full restart the app crushes. I'm using firebase database and the error is related to firebase_core. When I comment the line 66 (**//assert(await existingApp.options == options);**) on firebase_app.dart file it works fine and I'm able to perform full restart. Please see bellow the error:

**Before I comment the line on firebase_app.dart file**
```
Performing full restart...
Restarted app in 1,675ms.
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'file:///Users/josemboa/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.3/lib/src/firebase_app.dart': Failed assertion: line 66 pos 14: 'await existingApp.options == options': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      FirebaseApp.configure (file:///Users/josemboa/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.3/lib/src/firebase_app.dart)
<asynchronous suspension>
#3      main (file:///Users/josemboa/Documents/UPA/flutter/DezContos/lib/main.dart:17:43)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```
**After I comment the file on firebase_app.dart**
Performing full restart...
Restarted app in 1,733ms.

**Comment by kroikie** [comment]
@Josemboa

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/816. Any further collaboration will be done there.
