### ISSUE TITLE
testWidget adds an additional test group named '-'

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#17932]
If I render the groups/tests from running flutter tests in a tree, I get this:

<img width="928" alt="screen shot 2018-05-24 at 20 07 24" src="https://user-images.githubusercontent.com/1078012/40506057-20396186-5f8e-11e8-99c7-058a8a1aaf0f.png">

The `testWidget` function has added an empty group named '-' and also prefixed the test names. IntelliJ currently has special handling to fix this. I traced this back to this PR:

https://github.com/flutter/flutter/pull/3622#discussion_r61632399

Which has this comment about it from @Hixie:

> as discussed in person (but recorded here for posterity), I'm using the group because I need to be able to tear down state when the test times out, and try/finally blocks in the _runTest won't run if the test times out. I've filed dart-lang/test#426 to track this.

The reference case was considered a dupe of https://github.com/dart-lang/test/issues/93 which seems to have been implemented; so I think this can probably be cleaned up now to avoid more workarounds for it in tooling?

**Comment by Hixie** [comment]
Go for it! :-)
