### ISSUE TITLE
Feature Request: Add 'flutter repair' command that removes and repairs build and Pod files.

### ISSUE THREAD

**Issue by jeroen-meijer** [flutter/flutter#17937]
_Low priority._

Hi there.

I've made a small script that I use sometimes to completely get rid of existing cached files and pods and downloads and builds them again. Maybe it would be nice to bind this to a command like `flutter repair`.

This is the script in `bash`/`zsh`.
```bash
flutterrepair() {
    echo Cleaning project...
    flutter clean 2>&1 >/dev/null

    echo Updating Pod...
    pod repo update

    {if ! ( "${PWD##*/}" == 'ios') 2>&1 >/dev/null
        then cd ios
    fi} 2>&1 >/dev/null

    echo Removing pod files...
    rm -rf Podfile.lock Pods/ 2>&1 >/dev/null

    cd ..

    echo Removing cached flutter dependency files...
    rm -rf pubspec.lock .packages .flutter-plugins 2>&1 >/dev/null

    echo Repairing pub cache...
    flutter pub pub cache repair

    echo Getting all flutter packages...
    flutter packages get

    cd ios

    echo Running pod install...
    pod install

    cd ..

    echo DONE!
}
```

Thank you for your attention.

**Comment by zoechi** [comment]
Looks like a dup of #17784

**Comment by jmagman** [comment]
1. `pod repo update` shouldn't be necessary anymore.
2. `.packages .flutter-plugins` are now removed with `flutter clean`
3. Removing `pubspec.lock` and `Podfile.lock` out from our users is unexpected, they should be checking those files into their repo.
4. `pub cache repair` if you need to run this something is probably amiss--you should file any issues seen against [pub](https://github.com/dart-lang/pub/issues/new/choose).
5. `pod install` should never need to be explicitly run, `flutter build`/`run` does this for you.  If you ever need to explicitly run this, please file an issue with `--verbose` logs and we'll take a look, there's probably a bug we want to fix for all users, not just ones who know about a `repair` command.

If there are leftover files that are "safe" to delete, the logic should be added to `flutter clean`.  Please file a new issue for any files you find like this.

And if it's not safe, or unexpected, or will corrupt a project, or create a bunch of confusing working copy changes, we should avoid it and not have a `flutter really-clean` command.

Closing.
