### ISSUE TITLE
Oops, flutter has exited unexpectedly

### ISSUE THREAD

**Issue by chintansoni202** [flutter/flutter#17935]
I got the below log on console:

```
Launching lib\main.dart on TA 1004 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...

Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\chint\Desktop\material_flutter\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 435

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'C:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Finished with error: Gradle build failed: 1
```

I have attached the crash log: [flutter_01.log](https://github.com/flutter/flutter/files/2041551/flutter_01.log)

**My work environment:**

IntelliJ Idea: IntelliJ IDEA 2018.1.4 (Community Edition)
Build #IC-181.5087.20, built on May 17, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

I would like address one more issue, is that, "Hot Reload" doesn't work for me. "Lightening" yellow button is just not working. Looking at console, it just displays:

```
Performing hot reload...
Reloaded 0 of 389 libraries in 778ms.
```

I always have to make "Hot Restart" with green "Run" button.

If there is anything I can provide you with, just let me know. Thanks!

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

Is it possible that your user account doesn't have write permissions in `C:\flutter\flutter`?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
