### ISSUE TITLE
I want to scroll ListView to the specified serial number

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#17946]
For example, my ListView has 100 item, and I need to jump to a specific serial number based on my passing parameters when routing into the page, for example, 22..
And, because the height of item is not fixed, if I am in Android native, I can use` scrollTo (int position)`, such a method to jump directly to the specified location, and there is the same method in IOS.
How do I need to implement such a function in flutter?

**Comment by jeroen-meijer** [comment]
Maybe this tutorial will be of help to you.
http://cogitas.net/scroll-position-flutter-listview/

**Comment by CaiJingLong** [comment]
@jeroen-meijer 
Thank you for your help, but sometimes height is not fixed. I will refer to your code at a fixed height.

**Comment by goderbauer** [comment]
Closing as dup of https://github.com/flutter/flutter/issues/12319.
