### ISSUE TITLE
flutter messaging: set the notification icon

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#17941]
Hi, i'm using firebase messaging.
My app icon (ic_launcher) is multicolor and i want a different icon for notifies.
How i can set it?

Thanks

**Comment by g123k** [comment]
Hello,

By default the icon of the app is used.
If you want to use a different one on Android, you just have to specify it in the `AndroidManifest.xml` file:

```xml
<!-- Set custom default icon. This is used when no icon is set for incoming notification messages.
     See README(https://goo.gl/l4GJaQ) for more. -->
<meta-data
    android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@drawable/ic_stat_ic_notification" />
```

But be careful, because a mask is applied on Android 5+. So even if your app icon is multicolor the user won't see it.

**Comment by romaluca** [comment]
thanks! 
In ios how can i do?

**Comment by g123k** [comment]
On iOS, you can't customize the icon via FCM. It will always be the launcher icon.

**Comment by lukepighetti** [comment]
@g123k Hello. I have tried following a few guides for adding a notification icon and nothing is working for me. After you paste that snippet, where do you put the icon, at what size, with what name, and in what format?

**Comment by lukepighetti** [comment]
Hey guys, I fought with this for the better part of a day. For some strange reason there are no tutorials out there saying exactly where to put it. So here you go:

```xml
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="When Coin"
        android:icon="@mipmap/ic_launcher">
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/ic_notification" />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
```

The metadata goes at the <application> level, NOT the <activity> level

**Comment by lidroider** [comment]
The solution works perfectly
Tks

**Comment by blendosantos** [comment]
Tks Brother!!! @lukepighetti

**Comment by braysonjohn148** [comment]
> ```
> <meta-data
>             android:name="com.google.firebase.messaging.default_notification_icon"
>             android:resource="@mipmap/ic_notification" />
> ```

still dont work for me

**Comment by drkhannah** [comment]
yes adding meta data still doesn't work for me either, there is no icon at all, in the notification or the status bar

**Comment by epiphanatic** [comment]
not working for me either

**Comment by prabh045** [comment]
when i do this 

>         <meta-data
>             android:name="com.google.firebase.messaging.default_notification_icon"
>             android:resource="@mipmap/ic_notification" />

it shows white icon and when i dont android logo is displayed . what to do if i want to show colored app icon in notification badge.

**Comment by g123k** [comment]
@prabh045 You can't, because Android applies a mask on top of your icon.

**Comment by RumanaB** [comment]
I did the following and it worked for me: 

1) Create a transparent and white notification icon (you can use the following tool:  [AndroidAssetStudio](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default) )

2) Download the zip folder, unzip and you'll see it contains a res folder with different drawable folders. Copy and paste the contents of the res folder in "android\app\src\main\res" path 

![image](https://user-images.githubusercontent.com/6221786/80786594-b754b980-8ba1-11ea-87c8-d90903d28a87.png)

2) Then open the AndroidManifest.xml file and add the following lines to it:
 ```
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_calendar_today" />
```
ic_stat_calendar_today is the name of my notification icon. And each of the drawable folders that have been pasted contain a different size of icon with the same name. 

![image](https://user-images.githubusercontent.com/6221786/80786729-24684f00-8ba2-11ea-91fa-9a3e09a9825a.png)

3) If you want to change the color of the icon then check the above  image. Add the metadata tag after the notification icon tag

`  <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorAccent" />`

4) Go to "android\app\src\main\res\values" and add a colors.xaml file
![image](https://user-images.githubusercontent.com/6221786/80786872-8aed6d00-8ba2-11ea-94df-aaf3c11ab2ab.png)

**Comment by n8crwlr** [comment]
For the curios - for me it only works after the above explained **correct placing of this meta tag** and _Invalidate Caches / Restart..._ (clear Caches, like _gradle_ seems to be needed)

![image](https://user-images.githubusercontent.com/54250425/82117732-8fa14c00-9772-11ea-88f8-7a2510c8e3c7.png)

**Comment by Roshanalexander** [comment]
All that needs to be done is:
1. Add the icon under `"android/app/src/main/res/drawable/notification_icon_large.png"`. Assuming icon name is `"notification_icon.png"`. This must be a transparent background icon because Android applies a mask over it when displayed in Notification Center.

2. Include the following metadata in the AndroidManifest.xml file located in `"android/app/src/main/AndroidManifest.xml"`.
    
    `<meta-data
                android:name="com.google.firebase.messaging.default_notification_icon"
                android:resource="@drawable/notification_icon" />`

**Comment by yourshinsuke** [comment]
`com.google.firebase.messaging.default_notification_color` setting is required?
if it is none, grey icon?

`android/app/src/main/res/values/colors.xaml` is required?

@RumanaB 

I hope text, not screenshot.

```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:android="http://schemas.android.com/apk/res/android">
    <color name="colorAccent">#00FF00</color>
</resources>
```

**Comment by RumanaB** [comment]
@yourshinsuke The color is not required. If you create a transparent and white notification icon, the icon will appear white. 
I have shown how to customize the icon colour.

**Comment by kamleshwebtech** [comment]
> 1. colors.xaml

First of all a big thank you to share your experience. Your solution worked in one go. You saved my time or should i say saved my life :)

a) colors.xaml file name should be colors.xml  It was a tiny typo mistake.

b) your colors.xml code is in image so other user are not able to copy it so i am just sharing colors.xml file code here:

```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:android="http://schemas.android.com/apk/res/android">
	<color name="colorAccent">#00FF00</color>
</resources>
```

Once again thanks to @RumanaB 

Happy coding and share experience with others to make life easier and better :)

**Comment by bdthombre** [comment]
Thank you

**Comment by vaimikpatel2908** [comment]
is there any way we can set a large icon in the notification through FCM notification?

**Comment by sfabio01** [comment]
> I did the following and it worked for me:
> 
> 1. Create a transparent and white notification icon (you can use the following tool:  [AndroidAssetStudio](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default) )
> 2. Download the zip folder, unzip and you'll see it contains a res folder with different drawable folders. Copy and paste the contents of the res folder in "android\app\src\main\res" path
> 
> ![image](https://user-images.githubusercontent.com/6221786/80786594-b754b980-8ba1-11ea-87c8-d90903d28a87.png)
> 
> 1. Then open the AndroidManifest.xml file and add the following lines to it:
> 
> ```
>        <meta-data
>            android:name="com.google.firebase.messaging.default_notification_icon"
>            android:resource="@drawable/ic_stat_calendar_today" />
> ```
> 
> ic_stat_calendar_today is the name of my notification icon. And each of the drawable folders that have been pasted contain a different size of icon with the same name.
> 
> ![androidmanifest](https://user-images.githubusercontent.com/6221786/86433212-bb26c880-bd17-11ea-916e-c5cd2d713111.PNG)
> 
> 1. If you want to change the color of the icon then check the above  image. Add the metadata tag after the notification icon tag
> 
> ` <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorAccent" />`
> 
> 1. Go to "android\app\src\main\res\values" and add a colors.xaml file
>    ![image](https://user-images.githubusercontent.com/6221786/80786872-8aed6d00-8ba2-11ea-94df-aaf3c11ab2ab.png)

The "com.google.firebase.messaging.default_notification_color" meta-data set the color of the icon. Is there a way the keep the icon white and change the background color?

**Comment by vaimikpatel2908** [comment]
That's working fine but I want to set "large icon" for firebase messaging notification which comes on right side of notification. If you noticed that when you get a email notification in gmail then you can see user DP who sent you a email.

**Comment by fenchai23** [comment]
I am also searching for a way to set the large icon. So far no luck.

**Comment by hacnguyen1412** [comment]
> I did the following and it worked for me:
> 
> 1. Create a transparent and white notification icon (you can use the following tool:  [AndroidAssetStudio](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default) )
> 2. Download the zip folder, unzip and you'll see it contains a res folder with different drawable folders. Copy and paste the contents of the res folder in "android\app\src\main\res" path
> 
> ![image](https://user-images.githubusercontent.com/6221786/80786594-b754b980-8ba1-11ea-87c8-d90903d28a87.png)
> 
> 1. Then open the AndroidManifest.xml file and add the following lines to it:
> 
> ```
>        <meta-data
>            android:name="com.google.firebase.messaging.default_notification_icon"
>            android:resource="@drawable/ic_stat_calendar_today" />
> ```
> 
> ic_stat_calendar_today is the name of my notification icon. And each of the drawable folders that have been pasted contain a different size of icon with the same name.
> 
> ![androidmanifest](https://user-images.githubusercontent.com/6221786/86433212-bb26c880-bd17-11ea-916e-c5cd2d713111.PNG)
> 
> 1. If you want to change the color of the icon then check the above  image. Add the metadata tag after the notification icon tag
> 
> ` <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorAccent" />`
> 
> 1. Go to "android\app\src\main\res\values" and add a colors.xaml file
>    ![image](https://user-images.githubusercontent.com/6221786/80786872-8aed6d00-8ba2-11ea-94df-aaf3c11ab2ab.png)

you save me, thanks youuuuuuuu

**Comment by HigorSenna** [comment]
> Hey guys, I fought with this for the better part of a day. For some strange reason there are no tutorials out there saying exactly where to put it. So here you go:
> 
> ```
> <application
>         android:name="io.flutter.app.FlutterApplication"
>         android:label="When Coin"
>         android:icon="@mipmap/ic_launcher">
>         <meta-data
>             android:name="com.google.firebase.messaging.default_notification_icon"
>             android:resource="@mipmap/ic_notification" />
>         <activity
>             android:name=".MainActivity"
>             android:launchMode="singleTop"
>             android:theme="@style/LaunchTheme"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
>             android:hardwareAccelerated="true"
>             android:windowSoftInputMode="adjustResize">
>             
>             <meta-data
>                 android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
>                 android:value="true" />
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN"/>
>                 <category android:name="android.intent.category.LAUNCHER"/>
>             </intent-filter>
>         </activity>
>     </application>
> ```
> 
> The metadata goes at the `<application>` level, NOT the `<activity>` level which seems logical when you first look at `AndroidManifest.xml`

thank you!!!

**Comment by mrhaydari** [comment]
> Hey guys, I fought with this for the better part of a day. For some strange reason there are no tutorials out there saying exactly where to put it. So here you go:
> 
> ```
> <application
>         android:name="io.flutter.app.FlutterApplication"
>         android:label="When Coin"
>         android:icon="@mipmap/ic_launcher">
>         <meta-data
>             android:name="com.google.firebase.messaging.default_notification_icon"
>             android:resource="@mipmap/ic_notification" />
>         <activity
>             android:name=".MainActivity"
>             android:launchMode="singleTop"
>             android:theme="@style/LaunchTheme"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
>             android:hardwareAccelerated="true"
>             android:windowSoftInputMode="adjustResize">
>             
>             <meta-data
>                 android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
>                 android:value="true" />
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN"/>
>                 <category android:name="android.intent.category.LAUNCHER"/>
>             </intent-filter>
>         </activity>
>     </application>
> ```
> 
> The metadata goes at the `<application>` level, NOT the `<activity>` level which seems logical when you first look at `AndroidManifest.xml`

thaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaanks :XXX
