### ISSUE TITLE
Logging that works after unplugging

### ISSUE THREAD

**Issue by haydenflinner** [flutter/flutter#17949]
I'm testing an app that involves moving with the app open to test a feature. Beyond using an emulator, what I've been doing is carrying both my laptop and my phone, with the phone plugged in, to do final testing on the feature. 

A more convenient way to do this would be to be able to unplug the phone, the app under development just saves print calls until it gets plugged in again, at which point it dumps all of the prints that happened while unplugged into the console.

Alternatively I've seen that Android supports debugging over WiFi, didn't look into iOS, but this seems less than ideal because of all the issues that networking usually introduces into things that should be easy.

**Comment by goderbauer** [comment]
Closing this as you can already do this with platform tools as mentioned in the previous comment.
