### ISSUE TITLE
Hello! Can flutter be used for instant messaging application development?

### ISSUE THREAD

**Issue by hadoop835** [flutter/flutter#17940]
Hello! Can flutter be used for instant messaging application development?

**Comment by DanTup** [comment]
Sure; one of the demos on stage at I/O last year was a chat app:

https://www.youtube.com/watch?v=w2TcYP8qiRI

If there's something in particular you think might pose a problem, [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) and the [Gitter channel](https://gitter.im/flutter/flutter) are fairly active and good places to get help with building apps.
