### ISSUE TITLE
IOS error on start: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#17943]
With android emulator i have no problems, but with ios emulator, if i try to start my app i receive this error:

```
Launching lib/main.dart on iPhone 6s in debug mode...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
In file included from /Users/luca/.pub-cache/hosted/pub.dartlang.org/share-0.5.0/ios/Classes/SharePlugin.m:5:
/Users/luca/.pub-cache/hosted/pub.dartlang.org/share-0.5.0/ios/Classes/SharePlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from /Users/luca/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.0/ios/Classes/PathProviderPlugin.m:5:
/Users/luca/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.0/ios/Classes/PathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone 6s.
Exited (sigterm)
```

the flutter doctor is:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.4.6-pre.27, on Mac OS X 10.13.4 17E202, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by Josemboa** [comment]
I have the same problem after upgrading to flutter 0.4.4. Below is the error:

```
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.                                            4.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET nanopb OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/josemboa/.pub-cache/hosted/pub.dartlang.org/device_info-0.2.0/ios/Classes/DeviceInfoPlugin.m:5:
    /Users/josemboa/.pub-cache/hosted/pub.dartlang.org/device_info-0.2.0/ios/Classes/DeviceInfoPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.

**Running flutter doctor:**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (2 available)


• No issues found!

```

**Comment by danielvestergaard** [comment]
I solved this by upgrading cocoapods (pod) to 1.5.3. 

Make sure that you only have 1 installation of cocoapods. I had a gem and brew installation of cocoapods. I believe flutter uses the gem for running pod install.

**Comment by jeroen-meijer** [comment]
I've had this problem a while ago (#16036) but haven't had it in a while, but I don't know how it got fixed back then, I guess just staying on the beta and reinstalling everything.

You could try to run [this bash script](https://github.com/flutter/flutter/issues/17937) to see if deleting all pods and reinstalling all dependencies will help. The script will do it all for you. (Mac and Linux only.)

Here's the script.
```bash
flutterrepair() {
    echo Cleaning project...
    flutter clean 2>&1 >/dev/null

    echo Updating Pod...
    pod repo update

    {if ! ( "${PWD##*/}" == 'ios') 2>&1 >/dev/null
        then cd ios
    fi} 2>&1 >/dev/null

    echo Removing pod files...
    rm -rf Podfile.lock Pods/ 2>&1 >/dev/null

    cd ..

    echo Removing cached flutter dependency files...
    rm -rf pubspec.lock .packages .flutter-plugins 2>&1 >/dev/null

    echo Repairing pub cache...
    flutter pub pub cache repair

    echo Getting all flutter packages...
    flutter packages get

    cd ios

    echo Running pod install...
    pod install

    cd ..

    echo DONE!
}
```

**Comment by Josemboa** [comment]
I solved by downgrading cocoapods from 1.5.3 to 1.5.0 and reinstalling flutter (0.4.4). I also uninstalled the brew's cocoapods installation and installed pod 1.5.0 using gem. It's working now.

**Comment by zoechi** [comment]
Is this still an issue?
Have you tried `pod update` in `ios/`?

**Comment by zoechi** [comment]
Please check the suggestions in #17899

**Comment by romaluca** [comment]
Ok with that suggestions that error is gone. But now i have this other error:
https://github.com/flutter/flutter/issues/20719

**Comment by malibayram91** [comment]
this is the best solution 
https://github.com/flutter/flutter/issues/24428

**Comment by sumit25** [comment]
am having this issue below are the versions which am using to build ios app.

• Flutter version 1.20.2 at /Users/sumit/Flutter_SDK/flutter
    • Framework revision bbfbf1770c (7 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

and am getting issues to build the iOS app with below errors 

/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.2/ios/Classes/FLTURLLauncherPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>


please help me out here what's going wrong suddenly as everything was working as expected till yesterday
