### ISSUE TITLE
Is Flutter support implement the alarm clock function?

### ISSUE THREAD

**Issue by chenmurong** [flutter/flutter#17954]
I need a notifation  with flutter , similar to the alarm clock. 
Or implement other language, and flutter can invoke.
who can help me ?

**Comment by PaulHMason** [comment]
Sounds like the Timer class in the dart:async package, or the Stopwatch class in dart:core is what you want.

**Comment by chenmurong** [comment]
I would like something similar to alarms on Android

**Comment by chenmurong** [comment]
@g123k I would like something similar to alarms on Android

**Comment by g123k** [comment]
There is a plug-in that allows to schedule Android alarms: https://pub.dartlang.org/packages/android_alarm_manager

On iOS you can't have the same feature.
You can trick with a notification, but unless the user opens the app, your code will never run : https://stackoverflow.com/questions/10903568/ios-run-code-once-a-day

**Comment by chenmurong** [comment]
@g123k OK，Thanks， I will try

**Comment by zoechi** [comment]
@chenmurong Did the suggestions solve your problem?

**Comment by zoechi** [comment]
An improved alarm_manager plugin was released recently.

**Comment by JuniorBee** [comment]
> An improved alarm_manager plugin was released recently.

Are we talking about this? [`android alarm manager`](https://pub.dartlang.org/packages/android_alarm_manager)

**Comment by AmanNegi** [comment]
https://pub.dartlang.org/packages/android_alarm_manager does provide a timer but can someone tell how to create a dialog whenever the timer fires

**Comment by AmanNegi** [comment]
Well can we even do anything from it if our app is closed?? Can we show our flutter activity for instance?? If yes please let me know how?
