### ISSUE TITLE
no top-level method 'ThemeData.fallback' declared 

### ISSUE THREAD

**Issue by ahmedo100** [flutter/flutter#17953]
i'm using VS-Code with flutter , and i wanted to run the code on flutter documentation
this one to be precise : 
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Welcome to Flutter',
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Welcome to Flutter'),
        ),
      ),
    );
  }
}
```

but i keep getting this error on my phone and on the debugger 
no top-level method 'ThemeData.fallback' declared 

i think it's a problem with dart 2 ? or am i wrong , if so what's the solution 
ps: it's my first application on flutter ,

**Comment by goderbauer** [comment]
What's the output of `flutter doctor --verbose`?

**Comment by ahmedo100** [comment]
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale fr_DZ.UTF-8)
    • Flutter version 0.4.4 at /home/abd/flutter
    • Framework revision f9bb4289e9 (3 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/abd/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/abd/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/abd/Downloads/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at /home/abd/Downloads/idea-IC-172.4343.14
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 172.4343.25                                                                                                                                   
    • For information about installing plugins, see                                                                                                                     
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.23.1)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by ahmedo100** [comment]
@goderbauer 
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale fr_DZ.UTF-8)
    • Flutter version 0.4.4 at /home/abd/flutter
    • Framework revision f9bb4289e9 (3 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/abd/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/abd/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/abd/Downloads/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at /home/abd/Downloads/idea-IC-172.4343.14
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 172.4343.25                                                                                                                                   
    • For information about installing plugins, see                                                                                                                     
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.23.1)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by Hixie** [comment]
@ahmedo100 Can you paste the entirety of the error message including the stack trace and everything? We can't figure out why it might be happening and we haven't been able to reproduce it here.
