### ISSUE TITLE
Sync firechat-flutter with hackathon branch

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#1795]
We should make sure that the firechat-flutter sample code works with the hackathon.  Issues that I'm aware of:

- [ ] The `apk/` folder was renamed to `android/`. 
- [x] The `Input` widget now requires clients to manage an `InputValue` object, which enables clearing the `Input` widget by supplying an `InputValue.empty` value.

**Comment by collinjackson** [comment]
We're making a bunch of other revisions to firechat-flutter and I'll make sure to include these. Thanks!

**Comment by collinjackson** [comment]
Fixed in https://github.com/flutter/firechat-flutter/pull/7
