### ISSUE TITLE
Regression in hotReloadMillisecondsToFrame benchmark due to #17812

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#17956]
https://github.com/flutter/flutter/pull/17812 introduced a ~500ms regression in the `hotReloadMillisecondsToFrame` benchmark.

We were initially guessing that the regression was due to [serial eviction of assets](https://github.com/flutter/flutter/blob/d79f2ee22335880f70b7d9fd3cae2a77782a6503/packages/flutter_tools/lib/src/run_hot.dart#L303) coming from the Flutter tool.  When trying to reproduce the regression locally, however, I'm seeing much stranger behavior:

1. There's only _one_ service extension method being serviced during the hot reload benchmark, and that's `ext.flutter.reassemble({isolateId: isolates/<isolateId>})`.

1. If I set a `Stopwatch` immediately before and after the [Timer await](https://github.com/flutter/flutter/blob/d79f2ee22335880f70b7d9fd3cae2a77782a6503/packages/flutter/lib/src/foundation/binding.dart#L377), it reports that when the service extension method is being serviced, that one await statement is taking 600ms!

1. I can reliably reproduce the regression locally, but it reliably reproduces a 200ms regression for me, which doesn't match the delay found in the previous bullet.

/cc @Hixie

**Comment by tvolkert** [comment]
Seen on a device lab run with the instrumentation added in #17977:

```
stdout: [        ] Updating files
stdout: [  +32 ms] DevFS: Sync finished
stdout: [        ] Synced 0.0MB.
stdout: [   +2 ms] _reloadSources: {pause: false, rootLibUri: /data/user/0/io.flutter.demo.gallery/cache/edited_flutter_galleryNXNIGZ/edited_flutter_gallery/lib/main.dart.dill, packagesUri: /data/user/0/io.flutter.demo.gallery/cache/edited_flutter_galleryNXNIGZ/edited_flutter_gallery/.packages, isolateId: isolates/237392788}
stdout: [  +11 ms] reloaded 0 of 510 libraries
stdout: [        ] Sending reload events to Moto G 4
stdout: [        ] Sending reload event to "main.dart:main()"
stdout: [        ] getIsolate: {isolateId: isolates/237392788}
stdout: [  +47 ms] _flutter.listViews: {isolateId: isolates/237392788}
stdout: [   +8 ms] Evicting dirty assets
stdout: [        ] Reassembling application
stdout: [   +1 ms] ext.flutter.reassemble: {isolateId: isolates/237392788}
stdout: [  +23 ms] I/flutter (25038): service extension method received: ext.flutter.reassemble({isolateId: isolates/237392788})
stdout: [ +509 ms] I/flutter (25038): Action "Wait for outer event loop" took 0:00:00.505580
stdout: [+1485 ms] ext.ui.window.scheduleFrame: {isolateId: isolates/237392788}
stdout: [  +34 ms] Hot reload performed in 2,789ms.
stdout: [        ] Reloaded 0 of 510 libraries in 2,801ms.
```

Sure enough, the following line is taking half a second:

```dart
await new Future<void>.delayed(Duration.zero);
```

**Comment by Hixie** [comment]
That probably means we are scheduling another microtask before that one, and it's taking a long time (500ms) to run.

**Comment by tvolkert** [comment]
Yep.  Or several microtasks.

While #17812 did expose this, it shouldn't be reverted because it's correct.  The bigger question is what we're doing in a microtask loop that's taking 30 frames...

Note also that if we don't trigger hot reload immediately (as `--benchmark` is coded to do), it's much faster (~60-70% faster) in my anecdotal testing.  So it would seem that we're measuring the hot reload time when there's still a lot of stuff being scheduled in the app.

**Comment by Hixie** [comment]
should we make `--benchmark` ask the app when it's ready?

**Comment by tvolkert** [comment]
Per discussion in #17888, these regressions appear to be a problem with the benchmark reporting, so I'm closing this bug as a dup of #17888
