### ISSUE TITLE
Add iOS dependency to Flutter Plugin 

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#17978]
So far I've the plugin (standalone) and the app created. Now I need to (somehow) use and consume a static framework (obj-c) in iOS plugin.

I've the file `plugin.h` and `plugin.m` and I added the mylib.framework to the root of iOS folder, next to `podspec` file. Also tried to add the `s.dependency 'mylib'` to it. Still, it doesn't seem to work at all. Everytime I try to `flutter build ios` on my main app (using the plugin) I get the  `#import <myplugin/myplugin.h> not found`

PS: The library works if I add to the iOS project on the Flutter app, but I MUST use it on a plugin.

**Comment by miguelpruivo** [comment]
Update: If I add the framework to the Pods folder it compiles great and I can use it. But somehow, even if I have only code related to that library  on my plugin files, I need to have both the mylibrary.framework on the Pods folder and on the Runner/Frameworks folder. This doesn’t make much sense to me tho, because I wanted to make the plugin a stand-alone dependency and now I’ve to import the framework to two directories. Well, at least I’m closer and I can use the plugin.

**Comment by miguelpruivo** [comment]
**Update:** After some time trying and researching around the Pods structure and working (I had no experience on it) I found the solution by adding this lines to your `podspec` file in the ios/ folder of the plugin:

```
  s.preserve_paths = 'yourframework.framework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework yourframework' }
  s.vendored_frameworks = 'yourframework.framework'
```

And then on your Flutter project, in the iOS folder, just run `pod update` on terminal so it can fetch the new dependencies. 

I couldn't find any good information on this on the web but found some people with the same problem, so this might be the correct solution.

Closing issue now.

**Comment by xrnd** [comment]
Hi I have similar issue while running Flutter project in iOS device. Here is the podspec code for the plugin 'connectivity'
`Pod::Spec.new do |s|
  s.name             = 'connectivity'
  s.version          = '0.0.1'
  s.summary          = 'A Flutter plugin for getting commonly used locations on the filesystem.'
  s.description      = <<-DESC
A Flutter plugin for getting commonly used locations on the filesystem.
                       DESC
  s.homepage         = 'https://github.com/flutter/plugins/tree/master/packages/connectivity'
  s.author           = { 'Flutter Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  
  s.ios.deployment_target = '8.0'
 //BASED ON UPDATED ANSER 
  s.preserve_paths = 'connectivity.framework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework connectivity' }
  s.vendored_frameworks = 'connectivity.framework'

end`

Has anyone found solution for similar issue.

**Comment by 1and1get2** [comment]
+1

**Comment by lishuhao** [comment]
+1

**Comment by SAGARSURI** [comment]
Even I am in the same situation. I am trying to add a dependency to my plugin. But the dependency is only available in the `example/ios` through Pod but I want access that dependency in my `ios` folder of my plugin. This is my `podspec`:

```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'comet_chat'
  s.version          = '0.0.1'
  s.summary          = 'A new Flutter plugin.'
  s.description      = <<-DESC
A new Flutter plugin.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'CometChatPro', '1.4.0'

  s.ios.deployment_target = '10.0'
  s.preserve_paths = 'CometChatPro.framework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework CometChatPro' }
  s.vendored_frameworks = 'CometChatPro.framework'
end
```
How to solve this issue? How can I get my dependency only for the plugin?

**Comment by lcn1988** [comment]
> **Update:** After some time trying and researching around the Pods structure and working (I had no experience on it) I found the solution by adding this lines to your `podspec` file in the ios/ folder of the plugin:
> 
> ```
>   s.preserve_paths = 'yourframework.framework'
>   s.xcconfig = { 'OTHER_LDFLAGS' => '-framework yourframework' }
>   s.vendored_frameworks = 'yourframework.framework'
> ```
> 
> And then on your Flutter project, in the iOS folder, just run `pod update` on terminal so it can fetch the new dependencies.
> 
> I couldn't find any good information on this on the web but found some people with the same problem, so this might be the correct solution.
> 
> Closing issue now.


Configure in this way，Run app ld: framework not found  How to Solve the Problem

**Comment by sosospicy** [comment]
For me it's necessary to add the local framework in project Target 'Embedded binaries'.

**Comment by jlhour** [comment]
> Configure in this way，Run app ld: framework not found How to Solve the Problem

Hello. For what it worth, I have been struggling with this during a couple of days and maybe, maybe, I managed to sort it out.
Check `pod --version` when you call `pod update`. Turns out on my VS Code terminal it's `1.5.3` while on the system terminal it's `1.7.1`. I don't remember changing anything else. And after calling the command with the latest pod version, I managed to run the project.

**Comment by AlexitoRD** [comment]
I was having this issue to where I had added:
```
  s.preserve_paths = 'yourframework.framework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework yourframework' }
  s.vendored_frameworks = 'yourframework.framework'
```

to the podspec file but was unable to use my framework. What worked for me was I actually had to add the 'yourframework.framework' file to the plugin's ios folder, I missed this previously.

**Comment by f-martinez11** [comment]
Hello, I'm kind of lost about where should I add the framework itself. I would like to have my plugin as a standalone so I can reuse it easily.

**Comment by savy-91** [comment]
I'm having kind of the same issue, it would be helpful if there were some good documentation on how to integrate precompiled frameworks in a flutter plugin for iOS.

**Comment by umaqs** [comment]
Same issue here! Trying to add a local .framework library in my plugin. This a very common functionality and unfortunately there is no documentation or tutorial on how to do this. Has anyone found a solution yet?

**Comment by PMien** [comment]
After spending a couple of hours reading Pods Spec with some clues from this threat, I was able to get my plugin run independently in its own module. Here is what I did.

1. Copy **myFramework.framework** to folder **myPluginPackage/ios**
2. Open **myPluginPackage/ios/myPluginPackage.podspec** add this line of code

`s.vendored_frameworks = 'myThirdPartyFramework.framework'`

3. In terminal : cd to **myPluginPackage/example/ios** run command 

`pod install` or `pod update`

====================================

To open your plugin from Xcode: `Pods/Development Pods/yourPluginName/../.../example/ios/.symlinks/plugins/yourPluginName/ios/Classes`

**Comment by PMien** [comment]
After spending a couple of hours reading Flutter plugin Pods Spec with some clues from this thread, I was able to get my plugin run in its own module. Here is what I did.

Copy myFramework.framework to folder ** myPluginProject/ios**

Open ** myPluginProject/ios/myPluginPackage.podspec** add this line of code

s.vendored_frameworks = 'myThirdPartyFramework.framework'

In terminal : cd to ** myPluginProject/example/ios** run command

pod install or pod update

====================================

To open your plugin in Xcode(open your iOS project inside example/ios/Runner.xcworkspace): go to Pods/Development Pods/yourPluginName/../../example/ios/.symlinks/plugins/yourPluginName/ios/Classes

Cheer 👆👏🏻🥳

**Comment by PMien** [comment]
After spending a couple of hours reading Flutter plugin Pods Spec with some clues from this thread, I was able to get my plugin run in its own module. Here is what I did.

Copy **myFramework.framework** to folder **myPluginProject/ios**

Open **myPluginProject/ios/myPluginPackage.podspec** add this line of code

   's.vendored_frameworks = myThirdPartyFramework.framework'

In terminal : cd to **myPluginProject/example/ios** run command

   'pod install or pod update'

====================================

To open your plugin in Xcode(open your iOS project inside example/ios/Runner.xcworkspace): go to 
'Pods/Development Pods/yourPluginName/../../example/ios/.symlinks/plugins/yourPluginName/ios/Classes'

Cheer 👆👏🏻🥳

**Comment by PMien** [comment]
Here is what I did.

Copy myFramework.framework to plugin folder /ios

Open plugin folder **/ios/yourPluginPackage.podspec** add this line of code

    `s.vendored_frameworks = 'myFramework.framework.framework'`

In terminal : cd to myPluginProject/example/ios run command

   ` pod install or pod update`

====================================

To open your plugin in Xcode(open your iOS project inside example/ios/Runner.xcworkspace): go to
**Pods/Development Pods/yourPluginName/../../example/ios/.symlinks/plugins/yourPluginName/ios/Classes**

Cheer 👆👏🏻🥳

**Comment by PMien** [comment]
Here is what I did.

Copy myFramework.framework to plugin folder /ios

Open plugin folder /ios/yourPluginPackage.podspec add this line of code

  `s.vendored_frameworks = 'myFramework.framework'`

In terminal : cd to myPluginProject/example/ios run command

  ` pod install or pod update`
====================================

To open your plugin in Xcode(open your iOS project inside example/ios/Runner.xcworkspace): go to
Pods/Development Pods/yourPluginName/../../example/ios/.symlinks/plugins/yourPluginName/ios/Classes

Cheer 👆👏🏻🥳

**Comment by PMien** [comment]
Here is what I did.

Copy myFramework.framework to plugin folder /ios

Open plugin folder /ios/yourPluginPackage.podspec add this line of code

 ` s.vendored_frameworks = 'myFramework.framework' `

In Terminal : cd to 
> ex: zflutter/example/ios run command

```pod install``` or  ```pod update```
====================================

To open your plugin in Xcode(open your iOS project inside example/ios/Runner.xcworkspace): go to
Pods/Development Pods/yourPluginName/../../example/ios/.symlinks/plugins/yourPluginName/ios/Classes

Cheer 👆👏🏻🥳

**Comment by PMien** [comment]
Here is what I did.

1. Place myFramework.framework to iOS plugin folder /ios 
> ex:  myPlugin/ios

2. Update iOS plugin file:  yourPlugin/ios/myPlugin.podspec
Adding 
```
    s.vendored_frameworks = 'myFramework.framework'
```
In Terminal : cd to myPlugin/example/ios 
run command
```
   pod install``` or  ```pod update
```

_Now we can find the iOS plugin code by open your iOS project (example/ios/Runner.xcworkspace) in XCode and go to_
> Pods/Development Pods/yourPlugin/../../example/ios/.symlinks/plugins/yourPluginName/ios/Classes

**Comment by idaWHALE** [comment]
@PMien detail I was looking for was to run `pod install` from `example/ios` dir, thanks!

**Comment by klivin** [comment]
This seems really ugly, manually copying over all dependent frameworks into the `plugin/ios` folder should not be considered a solution by anyone here.  What's the real fix here guys?

**Comment by idaWHALE** [comment]
@klivin could also try putting your framework in [a private cocoapod](https://guides.cocoapods.org/making/private-cocoapods.html)

**Comment by awazgyawali** [comment]
I did the same to add opencv.framework to my podspec as a framework but now I am struggling to add static libraries via podspec. I am getting `Library not found` straight away. Any change someone can guide. I have also asked the same question on SO https://stackoverflow.com/questions/62144692/how-to-add-a-libraries-on-flutter-plugin-via-podspec

**Comment by d3xt3r2909** [comment]
> Even I am in the same situation. I am trying to add a dependency to my plugin. But the dependency is only available in the `example/ios` through Pod but I want access that dependency in my `ios` folder of my plugin. This is my `podspec`:
> 
> ```
> #
> # To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
> #
> Pod::Spec.new do |s|
>   s.name             = 'comet_chat'
>   s.version          = '0.0.1'
>   s.summary          = 'A new Flutter plugin.'
>   s.description      = <<-DESC
> A new Flutter plugin.
>                        DESC
>   s.homepage         = 'http://example.com'
>   s.license          = { :file => '../LICENSE' }
>   s.author           = { 'Your Company' => 'email@example.com' }
>   s.source           = { :path => '.' }
>   s.source_files = 'Classes/**/*'
>   s.public_header_files = 'Classes/**/*.h'
>   s.dependency 'Flutter'
>   s.dependency 'CometChatPro', '1.4.0'
> 
>   s.ios.deployment_target = '10.0'
>   s.preserve_paths = 'CometChatPro.framework'
>   s.xcconfig = { 'OTHER_LDFLAGS' => '-framework CometChatPro' }
>   s.vendored_frameworks = 'CometChatPro.framework'
> end
> ```
> 
> How to solve this issue? How can I get my dependency only for the plugin?

Did you found a solution to this?

**Comment by dazza5000** [comment]
This is what my solution was that worked:

```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint pro_pay_flutter.podspec' to validate before publishing.
#
Pod::Spec.new do |s|
  s.name             = 'pro_pay_flutter'
  s.version          = '0.0.1'
  s.summary          = 'A new flutter plugin project.'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'Flutter'
  s.platform = :ios, '8.0'
  s.preserve_paths = 'AnyPay.framework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework AnyPay' }
  s.vendored_frameworks = 'AnyPay.framework'

  # Flutter.framework does not contain a i386 slice. Only x86_64 simulators are supported.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }
  s.swift_version = '5.0'
  s.public_header_files = 'Classes/**/*.h'
end

```

**Comment by d3xt3r2909** [comment]
@dazza5000 

Can you please confirm me this: 

1. You are using your AnyPay.framework inside 
`Pods/DevelopmentPods/your_plugin/../../example/ios/.sysmlinks/plugins/your_plugin/ios/Classes`
2. You have added AnyPay.framework to your iOS folder inside the directory of your flutter plugin?
3. You added 

```

> #
> # To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
> # Run `pod lib lint pro_pay_flutter.podspec' to validate before publishing.
> #
> Pod::Spec.new do |s|
>   s.name             = 'pro_pay_flutter'
>   s.version          = '0.0.1'
>   s.summary          = 'A new flutter plugin project.'
>   s.description      = <<-DESC
> A new flutter plugin project.
>                        DESC
>   s.homepage         = 'http://example.com'
>   s.license          = { :file => '../LICENSE' }
>   s.author           = { 'Your Company' => 'email@example.com' }
>   s.source           = { :path => '.' }
>   s.source_files = 'Classes/**/*'
>   s.dependency 'Flutter'
>   s.platform = :ios, '8.0'
>   s.preserve_paths = 'AnyPay.framework'
>   s.xcconfig = { 'OTHER_LDFLAGS' => '-framework AnyPay' }
>   s.vendored_frameworks = 'AnyPay.framework'
> 
>   # Flutter.framework does not contain a i386 slice. Only x86_64 simulators are supported.
>   s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }
>   s.swift_version = '5.0'
>   s.public_header_files = 'Classes/**/*.h'
> end
> 

```

inside `Pods/DevelopmentPods/your_plugin/Pod/your_plugin.podspec` file?
4. After all of these things, you just run the `pod install`?


Am I missing something, or using it on wrong way?

**Comment by aarzoo-yourstory** [comment]
> **Update:** If I add the framework to the Pods folder it compiles great and I can use it. But somehow, even if I have only code related to that library in my plugin files, I need to have both the `mylibrary.framework` in the Pods folder and in the Runner/Frameworks folder.
> 
> This doesn’t make much sense to me tho, because I wanted to make the plugin a stand-alone dependency and now I’ve to import the framework for two directories.
> 
> Well, at least I’m closer and I can use the plugin.

Can you please give a more detailed location, where to put the framework.

**Comment by kndl22** [comment]
Is it possible to add multiple frameworks this way?

**Comment by miguelpruivo** [comment]
@kndl22 it should be, divided by a `,`.
```
  s.vendored_frameworks = 'yourframework.framework', 'other.framework'
```

**Comment by UlanNurmatov** [comment]
Where do I find 'yourframework.framework' folder? Looks like it's located in DerivedData?

**Comment by kenptr** [comment]
Looks like `ios/Flutter/Flutter.podspec` is in `.gitignore` (https://github.com/flutter/flutter/blob/master/.gitignore). 
I assume it's always regenerated.

Does anyone know if is it possible to add these configs to pubspec.yaml?

**Comment by AlirezaDaryani** [comment]
I need to add xcframework to podspec, any help?

**Comment by ChittoorM** [comment]
> **Update:** After some time trying and researching around the Pods structure and working (I had no experience on it) I found the solution by adding this lines to your `podspec` file in the ios/ folder of the plugin:
> 
> ```
>   s.preserve_paths = 'yourframework.framework'
>   s.xcconfig = { 'OTHER_LDFLAGS' => '-framework yourframework' }
>   s.vendored_frameworks = 'yourframework.framework'
> ```
> 
> And then on your Flutter project, in the iOS folder, just run `pod update` on terminal so it can fetch the new dependencies.
> 
> I couldn't find any good information on this on the web but found some people with the same problem, so this might be the correct solution.
> 
> Closing issue now.

I am trying to build .xcframeworks (build, profile and release) of a Flutter Module that depends on a Flutter plugin which uses "yourFramework.framework".
The Flutter Module when run standalone is working fine in iOS simulator, but when trying to generate .xcframeworks using the command "flutter build ios-framework --xcframework --no-universal --output=some/path/MyApp/Flutter/", it rises an error "no such module 'yourFramework' " at the line where I imported this framework in the iOS directory of the Flutter Plugin.

Can you please let me know how to solve this?
