### ISSUE TITLE
FirebaseAuthPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by chrisd1997** [flutter/flutter#17976]
## Steps to Reproduce
1. Include Firebase_auth version 0.5.10 (latest)
2. Run `flutter run`

Error is thrown right after that.

`Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.5.10\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.`

## Flutter version
`Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (2 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58`

**Comment by Asoseil** [comment]
same error with 0.5.2 and firebase auth 0.5.11

**Comment by ko2ic** [comment]
I fixed this.
https://github.com/flutter/plugins/pull/814

**Comment by zoechi** [comment]
Should be fixed by https://github.com/flutter/plugins/pull/775

Please add a comment if you're still seeing this to get the issue reopened.

**Comment by tikodrack** [comment]
in my case, I am still getting the same warning (FirebaseAuthPlugin.java uses or overrides a deprecated API) when bulding the APK... but nevertheless, despite the red warnings, the APK did work fine and the App didn't crash...

but then, of course it would be nice if this issue would be resolved...
any ideas?

**Comment by kroikie** [comment]
@chrisd1997

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/815. Any further collaboration will be done there.
