### ISSUE TITLE
Eviction of assets during hot reload is serial

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#17981]
https://github.com/flutter/flutter/blob/7c60b7405a911d37ccbedf120c59e84b74d6cec1/packages/flutter_tools/lib/src/run_hot.dart#L302-L303

We should be sending on vm service message that evicts all the assets at once, as opposed to sending serial messages to evict each asset one at a time.

**Comment by tvolkert** [comment]
Discovered during initial investigation into https://github.com/flutter/flutter/issues/17956

**Comment by jonahwilliams** [comment]
This has since been fixed: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L910
