### ISSUE TITLE
No main.dart file (essentially an empty project) when making a new project follow the "test drive"

### ISSUE THREAD

**Issue by coffeeneed** [flutter/flutter#17986]
So I've followed the installation instruction for Windows 10 (https://flutter.io/setup-windows/) to full extent, but when I'm wrapping everything up and making a new project, there are no lib/main.dart folders or files present (I'm currently on the "Test drive" page: https://flutter.io/get-started/test-drive/#androidstudio).

Anyone know what's going on?

The only thing inside the project folder is:
- `.idea folder` (inside it: codestyles, workspace.xml)
- `android folder` (which is empty)

`flutter doctor` says everything is OK.
"`The above command creates a Flutter project directory called myapp that contains a simple demo app that uses Material Components.`"<- This does not happen.

![image](https://user-images.githubusercontent.com/11244539/40644052-4fbedc46-6322-11e8-92dc-daa1796d38fa.png)

**Comment by zoechi** [comment]
Is this still an issue in recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by nihithreddy** [comment]
Even iam facing the same problem

**Comment by drakor007** [comment]
same problem for mee
