### ISSUE TITLE
Question: is plugins repo acceptable kotlin/swift ?

### ISSUE THREAD

**Issue by azihsoyn** [flutter/flutter#17999]
Hi, I love flutter.

I found flutter plugins repo is only obj-c, Java code for native implementation.

Can I use swift/kotlin for PR?

Thanks.

**Comment by goderbauer** [comment]
@mravn-google

**Comment by mravn-google** [comment]
AFAIK, Swift currently comes with a substantial overhead to the consuming app. Kotlin less so, and adding some proguard rules may get rid of most of it.

Anyway, app bundles (apk/ipa) built from a `flutter -i [objc|swift] -a [java|kotlin] create xyz` projects have the following sizes:
```
Java apk:     7.3MB
Kotlin apk:   7.7MB
ObjC ipa:    49.5MB
Swift ipa:  187.2MB
```
These sizes may not mean much, but it does seem to me that the decision of whether to use Kotlin and Swift should be taken by the app author, not the plugin author.

**Comment by azihsoyn** [comment]
Thank you for answering!

I will support your opinion.

Best regards.
