### ISSUE TITLE
Flutter Video Recording Problems

### ISSUE THREAD

**Issue by mwhite494** [flutter/flutter#17994]
I've recently been testing the new video recording functionality added to flutter's camera plugin v0.2.0 (Flutter version 0.4.4) and I am running into inconsistent problems when I try to record a video using the supplied [example](https://github.com/flutter/plugins/tree/master/packages/camera/example) on a few Android devices.

**On a Samsung Galaxy S7 (Android Version 8.0.0):**
I'm not getting any errors or exceptions but if I record a video and then navigate to the outputted .mp4 in my phone's directory, the file seems corrupted in that the audio and video are not in sync. The entire audio will play over the first frame of the video and then the video will playback with no audio. The quality of the produced video is also fairly low.

**On a Google Pixel 2 (Android Version 8.1.0):**
Again, no errors or exceptions thrown. When playing back the outputted .mp4 the audio and video are in sync, however the forward facing camera produces a video that is darker than normal. Again, video quality of the produced videos is fairly low.

I've also reached out to the [Tengio](https://github.com/Tengio/plugins/tree/master/packages/camera) team that contributed the pull request to add the functionality. I was wondering if anyone is aware of these issues or can offer advice on how to work around them. Thanks!

**Output of the flutter doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.16299.431], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.23.1)
[√] Connected devices (1 available)

• No issues found!
```

**Comment by jonasbark** [comment]
Regarding the bad quality:

I suggested using better default values for https://github.com/flutter/plugins/blob/master/packages/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java#L408 but it was said that this is something for another pull request after it is merged. 
So your option for solving this yourself: Fork the repository, change the values (the video bitrate is important) and use your fork instead - ideally create a pull request.

**Comment by zoechi** [comment]
@Hixie

**Comment by mwhite494** [comment]
I figured out that the issue I was having regarding the video freezing on the first frame was a problem involving Android's native camera packages not working correctly with certain Samsung phones. The work-around mentioned by cybaker in this [issue](https://github.com/googlesamples/android-Camera2Video/issues/24) ended up being a decent solution.
