### ISSUE TITLE
`--debug-port 0` on iOS is not "magical"

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#1799]
Assuming this means the default port.

**Comment by devoncarew** [comment]
We use it to mean (at least for adb devices) that the service should auto-select the port and report that back to the caller. This is the same as `--enable-vm-service:0` on the CLI VM.

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/device_android.dart#L237

**Comment by chinmaygarde** [comment]
>  This is the same as `--enable-vm-service:0` on the CLI VM.

Since we pass along the flag as is to the embedder VM, I believe the behavior should be similar.
