### ISSUE TITLE
Considering moving examples to own repo?

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#180]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Monday Oct 05, 2015 at 20:42 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1491_

----

Now that we have our own org, would it make sense to move examples out of engine and into their own org?

Or are things moving too fast right now...

**Comment by FlutterIssues** [comment]
<a href="https://github.com/j9brown"><img src="https://avatars.githubusercontent.com/u/102276?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [j9brown](https://github.com/j9brown)**
_Monday Oct 05, 2015 at 23:30 GMT_

----

Someday for sure, but I suggest we wait until we figure out the layout
we'll want for our Jiri repos.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Oct 06, 2015 at 04:31 GMT_

----

We very often change the examples atomically with the framework.  Once the framework settles down, I imagine we'll do that less.

I'd like to separate the Dart code from the C++ code though.  That way the Dart part can be more approachable.

**Comment by abarth** [comment]
I think the setup we have now works well.
