### ISSUE TITLE
Touch target for Slider might be too small

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#18006]
The two finger drag can be used to adjust a slider, and is the only way to adjust a slider before the volume controls were added on Android.  Currently our touch target for the slider are too small to perform this gesture.

**Comment by rami-a** [comment]
There's been some changes to slider in the last year and so I believe this is no longer a problem. I was able to trigger the 2 finger drag to adjust the slider on android (or use the volume keys). Closing this one
