### ISSUE TITLE
Cannot receive LayoutChangeNotification

### ISSUE THREAD

**Issue by chaokongzwp** [flutter/flutter#18018]
## Steps to Reproduce
As the picture shows:
![notification_problem](https://user-images.githubusercontent.com/23513781/40706567-d9efd614-6420-11e8-88e1-58448a703f0d.jpg)

The problem may be here：
In the build() method of the _MaterialState class, there is a listener of NotificationListener , which intercepts the report of LayoutChangeNotification
As the picture shows:
![scrollview_notification](https://user-images.githubusercontent.com/23513781/40706570-ddc70302-6420-11e8-8f46-7a00780ea4fb.jpg)

Please change line 308 to "return false"

**Comment by zoechi** [comment]
@Hixie

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
