### ISSUE TITLE
 Can you increase the RSA and DES standard libraries?

### ISSUE THREAD

**Issue by angelbeatsme** [flutter/flutter#18011]
My user information needs to be encrypted, but I can't find a usable RSA library.

**Comment by zoechi** [comment]
You could use PlatformChannel to make native encryption available to Flutter like https://pub.dartlang.org/packages/flutter_sodium does.

**Comment by pyp163** [comment]
https://pub.dartlang.org/packages/pointycastle#-readme-tab- 
https://pub.dartlang.org/packages/pointycastle#-readme-tab-
I found these

**Comment by Nyconing** [comment]
This stop me from using Flutter. This is critical as you cant communicating with server.

**Comment by zoechi** [comment]
There seems to be a RC version (for example `1.0.0-rc4`) of https://pub.dartlang.org/packages/pointycastle that should be Dart 2 compatible

**Comment by gionchat** [comment]
I also need libraries for RSA and DES

**Comment by stuartmorgan** [comment]
Closing as out of scope; this would be best provided by community packages, rather than the Flutter team picking one specific implementation.
