### ISSUE TITLE
Issue with animation not being run from 0 to 1 .

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#18013]
Often I see that my animation runs for a very short duration. On doing some logging I noticed that the AnimationBuilder was calling build build with timings from approx 0.88 (sometime 0.9) to 1.0 .
The fisrt 80% or so of the animation was being skipped. What would something like that happen?

**Comment by jonahwilliams** [comment]
@manujbahl the value is divided across the duration of the animation depending on the easing.  If you set very short animation durations, like 20ms (compared to a single frame which is 16 ms at 60fps), then you will see only a couple values.

**Comment by manujbahl** [comment]
Thanks @jonahwilliams 
Yup,. i was aware of that but was seeing that the controller was getting called for part of the animation.  I think i found the issue. It was something in my code around how i was handling multiple animations
