### ISSUE TITLE
How Icon Widget load local icon images?

### ISSUE THREAD

**Issue by yuiopt** [flutter/flutter#18020]
I want to use Icon Widget load different icon images like what we do in Android, an xml drawable file with selector root element,   and specifies state_pressed and state_enabled  png files, so can Flutter do this?

**Comment by zoechi** [comment]
Does https://flutter.io/assets-and-images/ not answer your question?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
