### ISSUE TITLE
TextAlign attribute is  not work in container widget (Use Visual Studio in Mac)

### ISSUE THREAD

**Issue by aman19ish** [flutter/flutter#18023]
I am using the text in container widget and assign the TextAlign attribute but it is not working.

```dart
   return new Container(

      child: new Text("data1 one", textAlign:  TextAlign.end, 
      textDirection: TextDirection.rtl,
      textScaleFactor: 2.0,

      style: new TextStyle(
         color: Colors.red[500],
         fontSize: 30.0,
          wordSpacing: 15.0,
         letterSpacing: 2.0,
         fontWeight: FontWeight.bold,
         decoration: TextDecoration.underline,
         decorationColor: Colors.green,
         decorationStyle: TextDecorationStyle.solid),
         softWrap:  true,
      )
    );
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by aman19ish** [comment]
[✓] Flutter (on Mac OS X 10.13.4 17E202, locale en-IN, channel alpha)
    • Flutter version 0.0.22-pre.1 at /Users/emp273/flutter
    • Framework revision 553fc4264e (4 months ago), 2018-03-01 09:30:25 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[-] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices
    • iPhone 8 Plus • 076CEFAA-08C2-421C-BF1B-8EF84EC445FB • ios • iOS 11.4 (simulator)

**Comment by zoechi** [comment]
That's a very outdated Flutter version. 
Can you please try if this is still an issue with a recent version?
`flutter channel beta` or `flutter upgrade` should upgrade your installation.

**Comment by aman19ish** [comment]
I tried the flutter upgrade command  but its not working.

**Comment by zoechi** [comment]
What about `flutter channel beta`?

**Comment by zoechi** [comment]
> Can you please help me "How can we see the visual studio code suggestions " for flutter.

Not sure what you mean with that. Perhaps you need to install the Dart and Flutter plugin in IntelliJ.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
