### ISSUE TITLE
Create a CupertinoApp and a CupertinoTheme

### ISSUE THREAD

**Issue by xster** [flutter/flutter#18037]
Create CupertinoApp with default fonts specified in a CupertinoTheme.

**Comment by xster** [comment]
There are 'primary color' themes now in iOS. https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/ 

We should switch the various usages of 'activeBlue/Green' to use the primary color instead

**Comment by dnfield** [comment]
I like this, and it might very well be a separate issue, but it seems like it'd be nice to have a template/harness for doing a Material or Cupertino app depending on the runtime platform.  That's probably a separate issue, but the basic idea would be to have a recommended pattern for handling that kind of scenario.

**Comment by adriancmurray** [comment]
@dnfield I think you're referencing something similar to the topic at #8410

**Comment by dahabit** [comment]
I Like this, we need IOS developers to feel that Cupertino  has the same support as Material Design

**Comment by xster** [comment]
CupertinoApp is done. There's still the CupertinoTheme with default fonts and primary color but I'm deprioritizing that part relative to other Cupertino tasks for now.
