### ISSUE TITLE
Create flutter meta-package in brew

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#1805]
Right now, to get started in ios, the steps include:

$ brew tap dart-lang/dart && brew install dart
$ brew install android-platform-tools
$ brew install ideviceinstaller
$ brew tap flutter/flutter
$ brew install ios-deploy

It'd be much nicer if this were just:

$ brew tap flutter/flutter && brew install flutter

... and the flutter package installed all the dependencies above (and any others that may come in the future).

**Comment by eseidelGoogle** [comment]
First attempt at https://github.com/flutter/homebrew-flutter failed due to hitting https://github.com/Homebrew/homebrew/issues/12130, probably doing this wrong.

**Comment by abarth** [comment]
Sadly, brew does not support meta packages.
