### ISSUE TITLE
Flutter SliverAppBar effect similar of iOS Google Maps

### ISSUE THREAD

**Issue by ajzuse** [flutter/flutter#18050]
I try to implement in Flutter a similar Google Maps AppBar effect using CustomScrollView and SliverAppBar with an flexibleSpaceBar and anothers examples, but I could not reproduce the effect.
The representation of result pretended is this:

[Opened View](https://i.stack.imgur.com/0dpPD.png)
[Bar View](https://i.stack.imgur.com/9nc22.png)

[Effect GIF](https://media.giphy.com/media/feghlEcI1SAPxny7FW/giphy.gif)

After a lot of attempts to develop I don't have success.

Any idea how to make this?

**Comment by zoechi** [comment]
@HansMuller

**Comment by zoechi** [comment]
I think this should better be asked on StackOverflow.
