### ISSUE TITLE
TextFormField counter cannot be hidden

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#18067]
There is no way of hiding the character counter in the TextFormField if the maxLength property is set.

```
[✓] Flutter (Channel master, v0.5.2-pre.18, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.5.2-pre.18 at /Users/vik/Projects/flutter
    • Framework revision 758711c85d (4 hours ago), 2018-05-31 10:33:15 +0200
    • Engine revision d174c4ff01
    • Dart version 2.0.0-dev.59.0.flutter-ff815d05a5

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio - old.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • iPhone 6 • 5DE7BCCC-8793-413A-9924-3D413DE12FCD • ios • iOS 9.0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by HansMuller** [comment]
Sounds reasonable. If we resolve https://github.com/flutter/flutter/issues/18068 by adding support for specifying a counter widget; would could allow one to specify null (or some other special value) to indicate that no counter should be displayed.

**Comment by rockneverdies55** [comment]
Is there any ETA on this?

**Comment by justinmc** [comment]
@rockneverdies55 ETA: very soon!  The referenced PR above should provide a way to hide it.  I'll respond back with how to do it once it's finalized, but you can follow along in that PR if you're interested.

**Comment by martinory** [comment]
Add to InputDecoration:
```
counterText: '',
counterStyle: TextStyle(fontSize: 0),
```

**Comment by justinmc** [comment]
Now that https://github.com/flutter/flutter/pull/25095 is merged, you can do something like this to hide the counter:

```dart
TextFormField(
   maxLength: 10,
   buildCounter: (BuildContext context, { int currentLength, int maxLength, bool isFocused }) => null,
);
```

**Comment by patelkrunal78** [comment]
First declare a bool variable passwordVisible.

Initiate passwordVisible to false in initState()

@override
  void initState() {
    passwordVisible = false;
  }
Following is the TextFormField widget :

TextFormField(
   keyboardType: TextInputType.text,
   controller: _userPasswordController,
   obscureText: passwordVisible,//This will obscure text dynamically
   decoration: InputDecoration(
       labelText: 'Password',
       hintText: 'Enter your password',
       // Here is key idea
       suffixIcon: IconButton(
            icon: Icon(
              // Based on passwordVisible state choose the icon
               passwordVisible
               ? Icons.visibility
               : Icons.visibility_off,
               color: Theme.of(context).primaryColorDark,
               ),
            onPressed: () {
               // Update the state i.e. toogle the state of passwordVisible variable
               setState(() {
                   passwordVisible = !passwordVisible;
               });
             },
            ),
          ),
        );
Hope this help someone!!!

https://icetutor.com/question/how-to-show-hide-password-in-textformfield

**Comment by GursheeshSingh** [comment]
Setting counter as optional

```
TextFormField(
    decoration: showMaxLength ? InputDecoration() : InputDecoration(counter: SizedBox.shrink())
);
```

**Comment by mehdichitforoosh** [comment]
Hi.
fontFamily does not appear to be applied to counter text?!

**Comment by fluttercorner1** [comment]
Here Is Article That Might Be Helpful [How to hide letter counter from the bottom of TextField in Flutter](https://fluttercorner.com/how-to-hide-letter-counter-from-the-bottom-of-textfield-in-flutter/)

**Comment by ajaykaju** [comment]
Adding a **LengthLimitingTextInputFormatter** will do the work, remove the **maxLength:**  property from your **TextField** and add ,

`inputFormatters: [ LengthLimitingTextInputFormatter(text_length), ],`

### If you want to customize your textfield widget by removing borders and counter text
**A full example is here**

```
Container(
    decoration: BoxDecoration(
                          border: Border.all(
                            color: Colors.blueGrey,
                          ),
    borderRadius: BorderRadius.circular(5.0),
    child: TextField(
                  decoration: InputDecoration(
                  hintText: "Mobile Number",
                  errorBorder: InputBorder.none,
                  focusedBorder: InputBorder.none,
                  disabledBorder: InputBorder.none,
                  enabledBorder: InputBorder.none,
                  focusedErrorBorder: InputBorder.none,
                  contentPadding: EdgeInsets.only(left: 10, right: 10),
                        ),
                  keyboardType: TextInputType.number,
                  cursorColor: Colors.black,
                  inputFormatters: [
                           LengthLimitingTextInputFormatter(10),
                          ],
                   ),
 ),
```
