### ISSUE TITLE
Issue when working with WebSockets

### ISSUE THREAD

**Issue by MderM** [flutter/flutter#18065]
From URL: https://flutter.io/cookbook/networking/web-sockets/

When executing this example from the android or ios emulator everything works like expected. When I try it from my actual android device, the connect method states an error that the request was not upgraded. Looking into my server application (asp net core 2.1) the request headers of the emulator look like this:

Cache-Control
no-cache

Connection
Upgrade

Upgrade
websocket

User-Agent
Dart/2.0 (dart:io)

and others.

Whereas the request coming from my pixel 2 device lokks like this:

Cache-Control
no-cache

Connection
Keep-Alive

Accept-Encoding
gzip

User-Agent
Dart/2.0 (dart:io)

and some others.

The question is: Why does the Pixel do not send an upgrade request? Looking into the dart SDK (_http package) the code does not give me any clue why it does not happen. Is this platform dependent, am Ilooking in the wrong driection?

**Comment by MderM** [comment]
To clarify:

over WiFi it works, but over cellular network the keep-alive header is sent to webserver. How does this come?

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/16875#issuecomment-384758566 might be worth a try

**Comment by MderM** [comment]
I wonder how a proxy definition issue should be interconnected with this one? could you explain this further?

To clarify, my problems arise when using a cellular connection for the websocket, which is also the reason why I think it is flutter specific and not in the dart sdk.

**Comment by zoechi** [comment]
Sorry, I misinterpreted your comment.

**Comment by zoechi** [comment]
Is this still an issue?
Could it be related to https://github.com/flutter/flutter/issues/13747#issuecomment-451307615 ?
