### ISSUE TITLE
Unable to include all assets under a folder 

### ISSUE THREAD

**Issue by ad-on-is** [flutter/flutter#18062]
According to the documentation, flutter should include all files within a folder and it's subfolder:
https://flutter.io/assets-and-images/

This is what my pubspec.yml looks like

    flutter:
          uses-material-design: true
          assets:
              - assets/images/

And this is the error message I get:

    Running "flutter packages get" in myapp...
    Launching lib/main.dart on ONEPLUS A3003 in debug mode...
    Initializing gradle...
    Resolving dependencies...
    Running 'gradlew assembleDebug'...
    Built build/app/outputs/apk/debug/app-debug.apk.
    I/FlutterActivityDelegate(28624): onResume setting current activity to this
    No file or variants found for asset: assets/images/.

    Error detected in pubspec.yaml:

If I instead define the path to the file itself, it works without any problems. But I don't want to define a new image each time I add one to the folder.

    flutter:
          uses-material-design: true
          assets:
              - assets/images/image.png

The assets folder is located at the same hierarchy as the pubspec.yaml. It contains a subfolder images, which contains some png-files.

`flutter --version`

    Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
    Framework • revision f9bb4289e9 (3 weeks ago) • 2018-05-11 21:44:54 -0700
    Engine • revision 06afdfe54e
    Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

**Comment by fukemy** [comment]
```
flutter:
      uses-material-design: true
      assets:
          - images/image.png
```

**Comment by ad-on-is** [comment]
@fukemy Sorry, your comment doesn't help me at all. I already stated, that this kind of implementation works.

**Comment by fmatosqg** [comment]
Sounds like either you're running the latest beta or close to that. Pls add the output for `flutter --version`.  Other than that everything looks good.

This feature is still not in beta, pls try either dev or master channel to benefit from it.

Also it still won't support subfolders, but that is not your use case. I created a PR recently to update documentation re: subfolders.

**Comment by ad-on-is** [comment]
@fmatosqg Thank you! It works now! I indeed was on the `beta` channel, which I assumed was the advanced one, but it obviously wasn't. I'm on `master` now, and everything works as you've described.

    Flutter 0.5.2-pre.19 • channel master • git@github.com:flutter/flutter.git
    Framework • revision 4f3fadb6f0 (14 minutes ago) • 2018-05-31 07:40:44 -0700
    Engine • revision c8378e4016
    Tools • Dart 2.0.0-dev.59.0.flutter-3b6caa3517

**Comment by nataliaha** [comment]
1. Create a folder 'images' at the top of the project
2. Copy the images, ex: 'lake.png'
3. add the asset in pubspect.yalm, like this:

flutter:
      uses-material-design: true
      assets:
          - images/lake.png

**Comment by richard457** [comment]
any update to this issue seems it is not solved here.

**Comment by blastrock** [comment]
In case people still have this issue : it is important to finish the path with a '/'. Do not include `assets/images` but `assets/images/` in your pubspec.yaml. At least it solved the problem for me.
