### ISSUE TITLE
Flutter - Firebase Realtime Database on Flutter - denied permission on “auth != null” after user is authenticated

### ISSUE THREAD

**Issue by atreeon** [flutter/flutter#18075]
On Android and after a user has been signed in I am trying to read some data from Firebase Realtime Db but I am receiving a '-3, Permission denied' message. My security rules are
`
  ".read": "auth != null"`

If I change my security rules to
`
  ".read": "true"`

then I can read my data.

After logging the user in, I can get access to my FirebaseUser and it has a uid populated which matches the uid in the Firebase Authentication so it seems like the login part is correct. I login as follows
```dart

    final FirebaseAuth _auth = FirebaseAuth.instance;
    final GoogleSignIn _googleSignIn = new GoogleSignIn();

    //do auth
    var googleAccount = await _googleSignIn.signIn();
    var googleAuth = await googleAccount.authentication;
    await _auth.signInWithGoogle(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
);

```
After waiting for the user to login successfully, I connect to the database as the following.

```dart
var firebaseApp = await FirebaseApp.configure(
  name: 'db2',
  options: const FirebaseOptions(
    googleAppID: GoogleSettings.googleAppID,
    apiKey: GoogleSettings.apiKey,
    databaseURL: GoogleSettings.databaseURL,
  ),
);
var db = new FirebaseDatabase(app: firebaseApp);

//get data
var popsicles = new List<String>();
var popsicleRef = db.reference().child('popcicles');

var result = await popsicleRef.once();
```

Plugins used (all latest as of 31/5/18)
```
    firebase_database
    firebase_core
    firebase_auth
    google_sign_in 3.0.2
```

Here is a gist of the problem (I'm reading data here instead of writing, my security rules are at the top of the page)

https://gist.github.com/twistedinferno/7bc7c62239e009e5195ed4576e7099e8

I'm unsure where I'm going wrong? Do I need to link my FirebaseApp or my FirebaseDatabase with my FirebaseUser?

**Comment by twistedinferno** [comment]
Has anyone else encountered this?  I would have expected this to be fixed by now as I would think it would be quite a high priority bug (unable to turn on authentication rules with firebase I would think is fairly serious).  Maybe I'm the only one?

**Comment by rostopira** [comment]
@twistedinferno nope, you aren't only one, just seems developers prefer cloud firestore over rtdb

**Comment by jefioliveira** [comment]
I`m have a equal problem.

**Comment by kroikie** [comment]
@atreeon

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/814. Any further collaboration will be done there.
