### ISSUE TITLE
Make sure to call FirebaseApp.initializeApp(Context) first Error

### ISSUE THREAD

**Issue by Murtuzakabul** [flutter/flutter#18076]
I followed all the steps for installing the plugin. However despite of several trial and error, I'm ending up with this error only

```
Built build\app\outputs\apk\debug\app-debug.apk.
I/FlutterActivityDelegate(23600): onResume setting current activity to this
I/System.out(23600): Keeping screen on
E/MethodChannel#plugins.flutter.io/firebase_remote_config(23600): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_remote_config(23600): java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process admin.spotmarket.spotmarketapp. Make sure to call FirebaseApp.initializeApp(Context) first.
E/MethodChannel#plugins.flutter.io/firebase_remote_config(23600): 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
E/MethodChannel#plugins.flutter.io/firebase_remote_config(23600): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(Unknown Source
```

My app is in ionic and Firebase remote config works quite well in it. It means that firebase app is properly configured. 

I am trying to access the config in my splash screen. Here is the code of my splash screen

```dart
class splash extends StatefulWidget {
  @override
  splashState createState() {
    return new splashState();
  }
}

class splashState extends State<splash> {

  onValue(dynamic value) {
    debugPrint(value.toString());
    DataProvider.scripNotifier.addListener(listener);
    openchannel();
  }

  Future<RemoteConfig> setupRemoteConfig() async {
    final RemoteConfig remoteConfig = await RemoteConfig.instance;
    // Enable developer mode to relax fetch throttling
    remoteConfig.setConfigSettings(new RemoteConfigSettings(debugMode: true));
    remoteConfig.setDefaults(<String, dynamic>{
      'welcome': 'default welcome',
      'hello': 'default hello',
    });
    return remoteConfig;
  }


  @override
  void initState() {
    super.initState();
    setupRemoteConfig().then(onValue);
  }

```

My assumption is the install instruction is missing some elements. Most probably, changes to androidmenifest.xml file. Not sure though.

Please help me out with this.

**Comment by zoechi** [comment]
> My app is in ionic

What does this mean exactly? Are you mixing Ionic with Flutter?

You can compare your settings with the example app to figure out if something might be missing https://github.com/flutter/plugins/tree/master/packages/firebase_remote_config/example

**Comment by zoechi** [comment]
@Hixie

**Comment by alboteanud** [comment]
Add the apply plugin to the [project]/android/app/build.gradle file.
// ADD THIS AT THE BOTTOM
`apply plugin: 'com.google.gms.google-services''`

check https://github.com/flutter/plugins/blob/master/packages/firebase_auth/README.md

**Comment by collinjackson** [comment]
It looks like this is covered by the documentation instructions above.

**Comment by kroikie** [comment]
@Murtuzakabul

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/813. Any further collaboration will be done there.
