### ISSUE TITLE
engine LICENSE file is empty

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#18079]
https://github.com/flutter/engine/pull/5416 blew away `sky/packages/sky_engine/LICENSE` in the `flutter/engine` repo.  That file gets downloaded into `bin/cache/pkg/sky_engine/LICENSE` by the Flutter tool and is used as the engine license file, to be included in Flutter apps.

We should:
1. Identify why this happened in https://github.com/flutter/engine/pull/5416 and fix the underlying issue
1. Add a test to ensure that that file exists and has non-zero size

**Comment by rmistry** [comment]
Yup, fix tracked in [skbug/8033](https://bugs.chromium.org/p/skia/issues/detail?id=8033).

**Comment by tvolkert** [comment]
This is fixed as of the most recent engine roll, so closing.  Thanks @rmistry for following up on skbug/8033!
