### ISSUE TITLE
labelText of multiline TextFormField should be top aligned

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#18081]
Not specified in the material design guidelines, but pretty sure that the label of a multiline TextFormField should be top aligned. Looks especially weird with the center alignment if the text field is very tall.

This is the current look:
<img width="365" alt="screen shot 2018-05-31 at 10 05 17 pm" src="https://user-images.githubusercontent.com/1539812/40805696-5d3ab9e0-651f-11e8-9b3c-0fee32871f6a.png">

```
[✓] Flutter (Channel master, v0.5.2-pre.18, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.5.2-pre.18 at /Users/vik/Projects/flutter
    • Framework revision 758711c85d (8 hours ago), 2018-05-31 10:33:15 +0200
    • Engine revision d174c4ff01
    • Dart version 2.0.0-dev.59.0.flutter-ff815d05a5

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio - old.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • iPhone 6 • 5DE7BCCC-8793-413A-9924-3D413DE12FCD • ios • iOS 9.0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by HansMuller** [comment]
I agree that the MD spec doesn't cover this but the label looks better top aligned.

**Comment by ianholing** [comment]
Agree, looks strange, even the animation.. any parameter like "labelAlign: TextAlign.start" would be great

**Comment by Hanggi** [comment]
+1, is there any way to set labeltext to the top align of the multiline textfield?

**Comment by justinmc** [comment]
With the PR referenced above, you can now pass `alignLabelWithHint: true` to `InputDecoration` to cause the label to align to the top.

**Comment by SebastianEngel** [comment]
Unfortunately this seems not to work when the TextFormFields new `expands` property is set to true (and maxLines and minLines are null). In this case the hint is vertically centered in the text field.

If `expands` is set to false and maxLines has a value the hint is aligned top as expected.

**Comment by justinmc** [comment]
@SebastianEngel Thanks for pointing that out.  I've seen similar complaints about vertical centering and `expands`, so I created this PR to explore some options: https://github.com/flutter/flutter/pull/31079.  I'm making a note on there to make sure that the solution makes sense with `alignLabelWithHint`.

**Comment by malikkurosaki** [comment]
this fix for me

```dart
 decoration: InputDecoration(
                      labelText: _formKontentTitle[x],
                      alignLabelWithHint: true
                    ),
```
