### ISSUE TITLE
Add embedder hooks for uncaught Dart exceptions

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#18085]
Some background in https://github.com/flutter/flutter/issues/614 and https://github.com/flutter/flutter/pull/13578

Fuchsia would like to be able to launch a Feedback [Module](https://fuchsia.googlesource.com/docs/+/master/glossary.md#module) whenever any Flutter Module experiences an uncaught Dart exception (an error that could cause `FlutterError.onError` to be notified).

Could we add new hooks into Flutter's embedder API such that the Fuchsia embedder could know whenever an uncaught Dart exception happens?

Thoughts, @chinmaygarde?

FYI @Hixie

**Comment by Hixie** [comment]
Side note: FlutterError.onError only fires for _caught_ exceptions (caught by the framework, that is). Uncaught exceptions aren't reported through FlutterError.onError, though you can catch them using Zones if you want.

**Comment by tvolkert** [comment]
So the actual feature request from Fuchsia is to have RSOD incidents trigger the Feedback Module, but I think they'll want uncaught exceptions to do the same.

**Comment by kf6gpe** [comment]
cc @chinmaygarde Did you already work on this? Not looking for you to jump on this, looking for status if you did. Thanks!

**Comment by chinmaygarde** [comment]
This is fixed and the Fuchsia embedder has been patched already to use the new hooks. These only applies to uncaught Dart exceptions however. FlutterError.onError is not an uncaught exception from the engines perspective because it has already been handled before it gets to the root of its event loop activation.
