### ISSUE TITLE
image_picker still hanging after a cancel

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#18095]
i'm using 0.4.2, and this was supposed to be fixed in 0.4.1, but the following

    var image = await ImagePicker.pickImage(source: ImageSource.gallery)
    print('result = $image');

will result in:

Unhandled exception:
PlatformException(multiple_request, Cancelled by a second request, null)

when you cancel the picker and launch it again.  the print is never called unless you choose a pic.

**Comment by goderbauer** [comment]
I just tried this in the examples app of the plugin and the error seems to only happen on iOS and only if I previously canceled a call to `pickVideo`. 

`pickImage` works fine even after cancelling a previous pickImage call.

Is that what you're seeing as well?

**Comment by CaiJingLong** [comment]
The same problem,

Occurred at the time of error and cancellation, and there was no return value.

The prompt should be called two times, but the first call has not returned the value.

**Comment by mlf2020** [comment]
is this problem solved? i have the same question in image_picker 0.6.7+4

**Comment by mi1971** [comment]
Hey @mravn-google This is still broken in 0.7.4. on Web Platform. Awaiting ImagePicker().getImage() never returns if image selection is cancelled.

**Comment by Kaustubh26-velsof** [comment]
Hi I am getting the same error in 0.8.0

**Comment by masterlonghorn** [comment]
Why is this closed? I still have this same issue. Nothing is returned on cancel.

**Comment by lecicdjuro** [comment]
after debugging, I found that getImage() never returns anything on cancel.

**Comment by maxhelskens** [comment]
I think I have found a solution.

```
CancelableOperation<PickedFile> pictureFuture;
bool choosingPicture;
  
void _getImage() {
 
    if (choosingPicture && !pictureFuture.isCanceled && !pictureFuture.isCompleted) {
      // Previous try was canceled: Stop waiting for picture.
      pictureFuture.cancel().then((v) {
        choosingPicture = false;
        _getImage();
      });
    } else {
        
        choosingPicture = true;

        var pFuture = picker.getImage(
          source: ImageSource.gallery,
          maxHeight: 1024,
          maxWidth: 1024,
          preferredCameraDevice: CameraDevice.rear);

        pictureFuture =
          CancelableOperation.fromFuture(pFuture, onCancel: () => {});

        pictureFuture.then((pickedFile) {
            choosingPicture = false;
            // TODO: Implement picture handling
        });
    }
}
  ```
  
  I'd prefere a fix for this package, but at the moment this seems to work..

**Comment by idrish-sorathiya** [comment]
Same issue on the web. On cancel, we are not getting any exceptions or anything. Second time trying to call it is not doing anything. This issue is blocking our release.

**Comment by Goper1M** [comment]
Issue is still happening, nothing is getting returned when cancel is pressed.


`Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
`

**Comment by yurisasc** [comment]
Same issue here. My app is stuck in a loading state because of this.

The native function handling the cancel seems to have correctly returned a `nil`. Not sure what causes this issue.
![image](https://user-images.githubusercontent.com/25047551/124421422-c7b78400-dda4-11eb-8f06-6e2a0cb0fc7c.png)
