### ISSUE TITLE
[BUG] NestedScrollView cannot jumpTo beyond header extend

### ISSUE THREAD

**Issue by BerndWessels** [flutter/flutter#18098]
Hi
I have a `SliverAppBar` with an `expandedHeight` and a `SliverFixedExtentList` inside. Basically [this example](https://docs.flutter.io/flutter/widgets/NestedScrollView-class.html).

Now I want to `jumpTo` `position` `5000.0` in the list.

So I add a `ScrollController` to the `NestedScrollView`. But the `range` that I can `jumpTo` seems to be limited to the height on the header.

I am not able to programatically scroll the `SliverFixedExtentList` to any position.

I believe this is because the `NestedScrollView` doesn't allow access to the `innerController`, but that is just a guess.

Is there a way to achieve this any other way?

Why, because I try to have a `TabBar` and each tab scrolls the `ListView` underneath to a specific section - basically like in the UeberEats app's menu page.

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
