### ISSUE TITLE
Non-hermetic tests in xcodeproj_test.dart

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#18093]
https://github.com/flutter/flutter/pull/16857 introduced a bunch of tests of the new versioning functionality, which is great.   Unfortunately, the tests aren't hermetic - they're accessing the real file system and spawning processes against the real OS.  That makes them subject to significantly more flakiness.

We should move these to be hermetic (using the mock process manager and memory file system, etc.).  For example, the other tests in [`xcodeproj_test.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/ios/xcodeproj_test.dart) use [`testUsingOsxContext()`](https://github.com/flutter/flutter/blob/bf531ba87119cb2292ec3bb4c88231c15e115a6b/packages/flutter_tools/test/ios/xcodeproj_test.dart#L39), which sets up all the hermetic bindings:

https://github.com/flutter/flutter/blob/bf531ba87119cb2292ec3bb4c88231c15e115a6b/packages/flutter_tools/test/ios/xcodeproj_test.dart#L40-L44

**Comment by the4thfloor** [comment]
I will look into it this weekend.

**Comment by the4thfloor** [comment]
@tvolkert https://github.com/flutter/flutter/pull/18548
