### ISSUE TITLE
Support search box inside large title nav bar

### ISSUE THREAD

**Issue by xster** [flutter/flutter#18103]
Support for a second tiered sliver inside the CupertinoSliverNavigationBar.

Need https://github.com/flutter/flutter/issues/9784 first.

**Comment by kerberjg** [comment]
+1

**Comment by leoaccorsi** [comment]
+1

**Comment by skiryuk** [comment]
Very very waiting

**Comment by Klabauterman** [comment]
I need this as well. This is ios default functionality :-(.

**Comment by DanielEdrisian** [comment]
See #9784 

Just been tasked with creating the search box. Will take at the least 1 month, just to set expectations.

**Comment by b3nni97** [comment]
ETA?

**Comment by kishikawa-wg** [comment]
ETA?

**Comment by cboiangiu** [comment]
ETA?

**Comment by SAGARSURI** [comment]
Any update?

**Comment by leonalonso** [comment]
any update?

**Comment by leonalonso** [comment]
I can not believe! From 2019 we are waiting .. absurd! Are there any news??

**Comment by molejnik-mergebit** [comment]
waiting as well, can we bump priority on this?

**Comment by zzundalek** [comment]
Update would be greatly appreciated.

**Comment by matteeosarto** [comment]
I would love to see this implemented. It is a standard iOS behavior...

**Comment by KevinGong2013** [comment]
**Flutter 3.0.0**
