### ISSUE TITLE
card_collection: when you enable text editing, the input controls use the wrong color

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1811]
Should be white, like the labels.

**Comment by sethladd** [comment]
What is card_collection ?

**Comment by abarth** [comment]
https://github.com/flutter/flutter/blob/master/dev/manual_tests/card_collection.dart

**Comment by sethladd** [comment]
Ah, thanks. So, just confirming, is this a bug with text input controls or the framework or... ?

**Comment by Hixie** [comment]
This seems minor and this is just a manual test at this point, not a demo.
