### ISSUE TITLE
the flutter/website builds are flakey

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#18118]
See:

```
https://travis-ci.org/flutter/website/builds/386776246#L977
```

They flake when trying to validate external links, which can occasionally 404.

**Comment by Sfshaza** [comment]
Truth. The *.dartlang sites check only for broken internal links on a commit. But they have a cron job, I believe, that tests external links weekly. @kwalrath?

**Comment by kwalrath** [comment]
I don't think we have such a cron job, but we probably should.

/cc @chalin

**Comment by chalin** [comment]
Right, this is still WIP for both sites (https://github.com/dart-lang/site-www/issues/240, https://github.com/dart-lang/site-webdev/issues/784). In the meantime I check external links by hand now and again.

**Comment by chalin** [comment]
This issue was moved to flutter/website#1177
