### ISSUE TITLE
Flutter framework tests always fail if a prior test failed after setting debug flag

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#18119]
Currently most flutter framework tests acquire disposable resources or set debug flags in the `testWidgets` callback.  The `flutter_test` framework also checks that these resources have been correctly disposed, failing the test otherwise.  The problem is that if a test fails before these resources have been disposed, all remaining tests in the file will fail as well, adding a lot of noise to test failures.

Instead we should use the `setUp` and `tearDown` methods of test to acquire and dispose of these resources and flags.

## Old
```
testWidgets('a test that will fail', (WidgetTester tester) async {
  debugDisableShadows = false;
  
 ...
});

testWidgets('a test that would pass', ...);
```
Every test below the first will fail with
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The value of a painting debug variable was changed by the test.
```

## New
```
group('Some group', () {
  setUp(() { debugDisableShadows = false; });

  tearDown(() { debugDisableShadows = true; });

  testWidgets('A test that fails', ...);

  testWidgets('A test that passes', ...);
});
```

**Comment by tp** [comment]
@jonahwilliams In my local test (where we overwrite the new `debugNetworkImageHttpClientProvider`) I see that `debugAssertAllPaintingVarsUnset` gets invoked before `tearDown`.

Hence it's not possible to neatly clean up using a shared `tearDown`.

Is that by design?
