### ISSUE TITLE
FlutterView should be inflatable without an Activity

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18115]
FlutterView requires android.app.Activity to be inflated. For existing apps, this is a blocker because many complex apps inflate their views using application context then attach the view to an activity after the fact. There are some cases where views exist without an activity altogether. We should be able to inflate FlutterView with application context and later attach activity to it.

**Comment by sceext2** [comment]
+1

[`InputMethodService.onCreateInputView()`](https://developer.android.com/reference/android/inputmethodservice/InputMethodService#onCreateInputView()) on Android requires to create a `View`.
But the input method is running at background as a `Service`, without any `Activity`.

It seems not possible to create an input method with `Flutter` on Android.

**Comment by mit-mit** [comment]
@matthew-carroll is this something you can help with?

**Comment by matthew-carroll** [comment]
@mit-mit We should probably add this to a list of API improvements associated with the Android refactor to match the engine.  This is definitely an issue, in fact I raised this issue with @mehmetf and Mikkel back when I was at Nest....so we should definitely solve this.

**Comment by matthew-carroll** [comment]
@mit-mit I'm going to assign this ticket to myself to see if I can figure it out.  I might toss it back if the Android changes are still too entangled to make this change.

**Comment by mehmetf** [comment]
Our first serious add2app customer reported this as a blocker since they internally use a Fragment implementation that does not provide an Activity object.

**Comment by matthew-carroll** [comment]
@mehmetf for this ticket to be completed, does the change need to be made to the current FlutterView, or can it be handled in the new embedding?

**Comment by mehmetf** [comment]
New embedding should be fine.

**Comment by Hixie** [comment]
I spoke with @matthew-carroll just now and he said he's not sure what the status of this bug is and will talk to @mehmetf about it. I'm moving the milestone out accordingly.

**Comment by mehmetf** [comment]
customer:control has paused its experiments so I am removing the blocker tag.

**Comment by matthew-carroll** [comment]
@mehmetf do you recall why the Application Context needed to be passed?  Was it just to facilitate re-use of a Flutter execution context across multiple Activitys?

**Comment by mehmetf** [comment]
Updated the title. The point of this issue was to avoid the need to pass an activity to FlutterView for inflation.

**Comment by matthew-carroll** [comment]
Right, but why was someone trying to pass something other than an Activity to FlutterView?

**Comment by mehmetf** [comment]
The full story is as follows:

When you were with your previous team, you mentioned that it would be nice to be able to develop features like "Chat Bubbleheads" with Flutter which would require a view created without an activity. This issue was inspired by that.

Later customer:control (which uses an internal Android framework that you know about) asked about this too because the framework's fragments did not provide Activity. Instead it provided some other context that I don't recall at the moment. It might have been a [ContextWrapper](https://developer.android.com/reference/android/content/ContextWrapper).

So if the first use case that you had brought up is no longer there, perhaps this is fixable by just removing the assumption that the Context passed to FlutterView is an Activity. If we *still* need the activity, perhaps we can just handle the ContextWrapper case and walk the parent context list until we find the activity. You would need to check with Charles to see what that internal framework does so we can provide something that works.

**Comment by matthew-carroll** [comment]
Ah yes, the chat bubble scenario!  Ok, I'll go test the new embedding and see what happens when I pass an application context.  This may already be done.

**Comment by matthew-carroll** [comment]
I just tried passing the Application Context into FlutterView and FlutterEngine and it appears to work fine, so I'm going to close this as done.  Feel free to re-open if it is ever discovered that this isn't working.

**Comment by matthew-carroll** [comment]
Re-opening this issue because `AccessibilityBridge` assumes its `Context` is an `Activity`

**Comment by matthew-carroll** [comment]
Ok, now I think this is legitimately handled in the new `FlutterView` and `FlutterEngine` classes.

https://github.com/flutter/engine/pull/8231
