### ISSUE TITLE
card_collection: first item is rendering in the wrong place when editable

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1812]
When an Input ends up too small, we draw the text under the line. Not sure what the right behaviour is, but this is probably not it. If we're going to overflow, we should overflow with the text above the line, so that it's consistent. We could also do something more "clever" (tweak the font size maybe).

**Comment by Hixie** [comment]
@HansMuller Can you see if you resolved this with your text field work, and if not, figure out what we should do for overconstrained text fields and implement that? Thanks!

**Comment by HansMuller** [comment]
As far as I can tell, this isn't a bug anymore.
