### ISSUE TITLE
Dart obfuscation should be mentioned in the Flutter wiki

### ISSUE THREAD

**Issue by Ehud-Banunu** [flutter/flutter#18137]
Hi,
both wiki entries for [apk](https://flutter.io/android-release/) and [ios](https://flutter.io/ios-release/) fail to mention obfuscation,
which is a common deployment requirement.
Dart [supports obfuscation](https://github.com/dart-lang/sdk/issues/30524), and this capability can now be exposed to flutter clients -
see [this SO question](https://stackoverflow.com/questions/50542764/how-to-obfuscate-flutter-apps), which offers users a manual fix.
Please add this to the wiki with a link to the SO question, at least as an optional step,
and consider applying the manual fix in flutter's source.
Thanks!

**Comment by Sfshaza** [comment]
We now have a section on [obfuscation and minification](https://docs.google.com/document/d/1SuMnUSlSXqeEJavhjimnqkjsqiV88zOnXpXcQk6GIEo/edit?usp=sharing). (Though, now that I look at it, the title has a typo.)

**Comment by Sfshaza** [comment]
@cbracken, I added a section on [obfuscation](https://flutter.io/android-release/#minfify-and-obfuscate) to the Android release page (though I misspelled Minify and I'll fix that), but should it also be added to the iOS Release page? Is the process different for iOS?

**Comment by cbracken** [comment]
The process described on the Android releasing page is Android-specific. I'm not aware of any Flutter-specific obfuscation support on iOS. There was some work done on the Dart side a while ago -- @mehmetf may be able to provide more details.

**Comment by Ehud-Banunu** [comment]
@Sfshaza Thanks for addressing this.
The section you added to Android, while important, only mentions Java obfuscation -
I was talking about Dart obfuscation and the --extra-gen-snapshot-options flag.
Please go through the [relevant SO question](https://stackoverflow.com/questions/50542764/how-to-obfuscate-flutter-apps).

**Comment by Ehud-Banunu** [comment]
@Sfshaza In the meanwhile, the current [minification and obfuscation](https://flutter.io/android-release/#minfify-and-obfuscate) section is misleading, as everything **but** user code, which is the important thing here, is obfuscated. Please change the section to reflect that function & class names from Dart code are not obfuscated. An equivalent statement on the iOS release page is needed too.

**Comment by Sfshaza** [comment]
@Ehud-Banunu, you can follow https://github.com/flutter/website/pull/1071

**Comment by Sfshaza** [comment]
@Ehud-Banunu, have you seen that this info is now in the Flutter wiki? Thanks for raising this issue. I'm about to land a  PR that points to it.

**Comment by Sfshaza** [comment]
Fixed in PR https://github.com/flutter/website/pull/1081
