### ISSUE TITLE
possible bug in border_radius.dart

### ISSUE THREAD

**Issue by touseefbsb** [flutter/flutter#18139]
I was following udacity course on flutter and getting error "the constructor being called isn't a const constructor" on the following line

>const _rowHeight = 100.0;
>const _cornerRadius = BorderRadius.circular(_rowHeight / 2);// error is on this line

I also asked the question on stackoverflow and got an answer which solved my problem, but as per that answer there might be a bug in **border_radius.dart**

> for more check here : https://stackoverflow.com/questions/50648874/flutter-const-constructor-error/50650274#50650274

**Comment by jonahwilliams** [comment]
Hi @touseefbsb, this isn't a bug it just isn't currently possible to define a const constructor which in turn allocates a new object.

**Comment by touseefbsb** [comment]
ahan, that follow along code was actually misleading I guess, bcz tht code was trying to do just that, as I wrote above, but thanks for the clarification :)
