### ISSUE TITLE
The Dart SDK included in bin/cache/dart-sdk has inconsistent reported versions

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#18134]
It reports both the version of the source Dart SDK as well as the flutter specific version. We should make this consistent (using the flutter version).

```
cat /Users/devoncarew/projects/flutter/bin/cache/dart-sdk/version 
2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0
```

and:

```
/Users/devoncarew/projects/flutter/bin/cache/dart-sdk/bin/dart --version
Dart VM version: 2.0.0-dev.59.0.flutter-1a185867a9 (Thu May 31 17:38:53 2018 +0000) on "macos_x64"
```

As part of the process for building the flutter specific SDK, we should write the `2.0.0-dev.59.0.flutter-1a185867a9` version into the `<dart-sdk>/version` file.

**Comment by chinmaygarde** [comment]
cc @a-siva

**Comment by cbracken** [comment]
Just verified and this is still an issue today.

**Comment by a-siva** [comment]
@cbracken are you seeing a difference because of the 2.7 version hack that was put in  https://github.com/dart-lang/sdk/blob/master/tools/make_version.py  ?

Is this what you see ?
```
sivalinuxmach[flutter]>more bin/cache/dart-sdk/version
2.7.0-edge.8bdca37e98a59bdb7f52daea9da838b1a60c1cdf

sivalinuxmach[flutter]>bin/cache/dart-sdk/bin/dart --version
Dart VM version: 2.7.0 (Tue Nov 5 13:31:41 2019 +0000) on "linux_x64"

```

**Comment by cbracken** [comment]
That's what I've got, yep.
