### ISSUE TITLE
ListView scrolling issue on Samsung S7 Edge running Android 7.0

### ISSUE THREAD

**Issue by KellanMebane** [flutter/flutter#18133]
ListView scrolling is janky on S7 Edge, but completely fine on Samsung S7 and Motorola Moto Z. Performance overlay says it's 60fps on GPU and UI. My code is here at https://github.com/KellanMebane/Ice-Cream-Reddit on the "checkpoint1" branch and should be public. On the S7E this only occurs (easily noticeable) when I nest Columns and Rows in the list elements, even with just 1 child in each. 

Here's a video showing the differences between the S7 Edge (left) and S7 (right) running the same release apk: https://www.youtube.com/watch?v=HgTWom0Fa1g

**Comment by chinmaygarde** [comment]
Thanks for the reduced test case.

**Comment by kf6gpe** [comment]
@chinmaygarde do you still think this is an issue, or should we close it given the changes in the mean time?
