### ISSUE TITLE
TimePicker touch targets are too small

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#18130]
The touch area for each digit needs to be much bigger - there is room in the existing design it just isn't under the semantics node.

For reference, our time picker compared to android native.

<img src="https://user-images.githubusercontent.com/8975114/40868187-668fe97a-65bf-11e8-843f-e3c55735e769.png" width="300"><img src="https://user-images.githubusercontent.com/8975114/40868181-648fb60a-65bf-11e8-8be2-d4aaeeb7ddb2.png" width="300">

**Comment by jonahwilliams** [comment]
Not working on this right now

**Comment by willlarche** [comment]
cc: @DarrenGoog

**Comment by willlarche** [comment]
Goal is 48x48 when possible.

**Comment by mathieupost** [comment]
I started on this today! Will create a PR tomorrow.
