### ISSUE TITLE
Why Flutter Plugin are not supported Android Studio3.2?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#18146]
Excuse me. I'm using the Android Studio3.2，but the Flutter Plugin isn't supported Android Studio3.2?
Tips like following:

`Unsupported Android Studio version`
`Canary versions of Android Studio are not supported by the Flutter Plugin.`

This is a terriable bug.May fix it quickly.

**Comment by Kartik1607** [comment]
Not a bug.  Canary versions are for preview and used to test to find out bugs before releasing them as stable versions. Use android studio 3.1 to use flutter plugin for now.
