### ISSUE TITLE
Enhancement: flutter format to support a 'diff' mode (or similar)

### ISSUE THREAD

**Issue by dmjones** [flutter/flutter#18142]
This is an enhancement request. It would be helpful, for Git hooks and CI pipelines, if `flutter format` had a new mode that checks if the code is correctly formatted, without altering files.

Perhaps a `diff` mode, where changes are printing to stdout in patch format. Then CI scripts can check for the presence of output.

Alternatively, the tool could return non-zero return codes when using this new mode and facing unformatted code.

I believe this command uses `dartfmt` under the hood, which [seems to support this behaviour already](https://github.com/dart-lang/dart_style#using-dartfmt). I guess I can use that for now, as a workaround, but it would be nice to see it possible through the flutter tools.

**Comment by zoechi** [comment]
>  which seems to support this behaviour already. 

I wasn't able to figure out why you mean it supports this already.

I found https://github.com/dart-lang/dart_style/issues/92 might be related.

**Comment by dmjones** [comment]
The dart_style tool defaults to stdout, rather than overwriting files. This allows a script to check whether the output is empty (e.g. the files are correctly formatted).

By contrast, `flutter format` changes the files in place, which makes it harder to test for bad formatting in a script.

That being said, it seems like there is a `--dry-run` option now in `flutter format`. Either I missed this before or it's a new feature. Either way, this should solve it for me.
