### ISSUE TITLE
cloud_firestore 0.7.3

### ISSUE THREAD

**Issue by ThatRealGuy** [flutter/flutter#18143]
error while running flutter run.
terminal will throw this error
```
 fatal error: 'cloud_firestore/CloudFirestorePlugin.h' file not found
    #import <cloud_firestore/CloudFirestorePlugin.h>
```
any idea how to solve this?

**Comment by unknownzebra** [comment]
were you able to fix this issue?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`.
There were similar issues the last weeks where missing `xxx.h` from various plugins were reported.

https://github.com/flutter/flutter/issues/17943#issuecomment-392330541 mentions `Flutter.h`.
I'm not sure this is the same issue but the proposed solution might be worth a try here as well.

Similar #17196, #16652, #16645, #16621, #16566, #16246, #15409, https://github.com/flutter/flutter/issues/9817#issuecomment-383795349

@tvolkert

**Comment by ThatRealGuy** [comment]
@unknownzebra version 0.6.3 and clean built and working perfectly.

**Comment by ssarangi** [comment]
This is happening with every plugin I have been trying. 

These are the plugin's I have which are causing issues...

font_awesome_flutter
image_picker
google_sign_in
firebase_analytics
firebase_auth
firebase_database
firebase_storage
cloud_firestore
firebase

**Comment by kroikie** [comment]
@ThatRealGuy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/812. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
is the issue still relevant?
