### ISSUE TITLE
I have Installed the Flutter plugin,but Flutter console don't show it?please fix the bug!

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#18155]
I have Installed the Flutter plugin,I can run my project

but In the Flutter Console, run the following command

`flutter doctor -v`

tips like this:

```
[√] Android Studio (version 3.2)
    • Android Studio at E:\develop\anzhuangbao\android-studio-ide3.2-181.4763614-wind
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b03)
```

please fix the bug quickly !  Thank you!

**Comment by zoechi** [comment]
Please add the full output of `flutter doctor`

**Comment by AweiLoveAndroid** [comment]
$ flutter doctor -v
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 0.4.4 at E:\develop\flutter
    • Framework revision f9bb4289e9 (3 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at E:\develop\sdk
    • Android NDK at E:\develop\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = E:\develop\sdk
    • Java binary at: E:\develop\android-studio-ide3.2-181.4763614-windows\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b03)
    • All Android licenses accepted.

[!] Android Studio (version 2.3)
    • Android Studio at E:\develop\android studio2.3.1\android-studio
    X Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 162.2924
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.2)
    • Android Studio at E:\develop\android-studio-ide3.2-181.4763614-windows
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b03)

[!] IntelliJ IDEA Community Edition (version 2017.1)
    • IntelliJ at E:\develop\IntelliJ IDEA Community Edition 2017.1.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by zoechi** [comment]
Did you try installing the plugins in IntelliJ IDEA as well?

**Comment by AweiLoveAndroid** [comment]
I have installed the Flutter plugin and Dart plugin in IntelliJ IDEA ，but the problem also appended in the Flutter console , so  what shall I do?
just Flutter console show the plugin doesn't  be installed.
I can use Flutter write my app well.

**Comment by StormKid** [comment]
Here is the console and plugin @zoechi 
please look at two pictures:

![1wxtu4 uyd 9x6021mvt](https://user-images.githubusercontent.com/13798727/41015527-3f3f1708-697d-11e8-81f9-a7604b6c8653.png)


![tw hp __crn2l f uw ge7](https://user-images.githubusercontent.com/13798727/41015509-2e260396-697d-11e8-8efa-df7bc1810f4b.jpg)

**Comment by XiaYongjie** [comment]
@zoechi I have the same 
![2018-06-18 13-34-09](https://user-images.githubusercontent.com/12043449/41519819-ede691fe-72fc-11e8-889b-7902e3fff0b5.png)
![2018-06-18 13-37-10](https://user-images.githubusercontent.com/12043449/41519820-ee28bd04-72fc-11e8-9de2-8d98a338a1b9.png)

I try to unload reload but it's useless

**Comment by XiaYongjie** [comment]
@zoechi I've solved this problem. I use Android studio not idea , it's my problem

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.

**Comment by hoornet** [comment]
I am seeing the same problem. I have installed it on AS 3.2  and 3.3 and IDEA and only in IDEA and only in IDEA it is recognized by fluttr doctor:

```
D:\Tools\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale sl-SI)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    X Android license status unknown.
[√] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Android Studio (version 3.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] Connected devices (1 available)

! Doctor found issues in 2 categories.
```

**Comment by SPSpisoft** [comment]
me too..
Where is the helper?

**Comment by zoechi** [comment]
@hoornet @SPSpisoft you might want to follow #21881
This issue is closed.

**Comment by maheshts** [comment]
Can any body please help.
i have installed flutter and dart.

D:\Flutter_dev\hello>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[ΓêÜ] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 6.1.7601], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    X Android license status unknown.
[!] Android Studio (version 2.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
[ΓêÜ] Android Studio (version 3.2)
[ΓêÜ] Android Studio (version 3.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 64-bit edition (version 1.21.1)
[ΓêÜ] Connected devices (1 available)

! Doctor found issues in 3 categories.

**Comment by Aishwarya1317** [comment]
Hey @zoechi I am facing a problem... I cant run flutter_console.bat file. Please help me

**Comment by Aishwarya1317** [comment]
On command fire I get 
![flutter_error](https://user-images.githubusercontent.com/47808347/56351204-33c06880-61ea-11e9-92d4-55855ada3ffc.JPG)

**Comment by iapicca** [comment]
Hi @AweiLoveAndroid 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you
