### ISSUE TITLE
Add "marquee" effect for Text

### ISSUE THREAD

**Issue by thphuc** [flutter/flutter#18158]
I'm checking Text class. It has some TextOverflow effects but it seems there is no way to create "marquee" effect. 

Here is the demo effect: 

![image017](https://user-images.githubusercontent.com/4323410/40911054-051d1d2e-6818-11e8-9efd-581ac3f66d1a.gif)

**Comment by nt4f04uNd** [comment]
Nothing actually working a whole year later....

**Comment by preetjdp** [comment]
Hey, have you tried this ==> https://pub.dev/packages/marquee

**Comment by goderbauer** [comment]
Closing as this can just be implemented in a package.
