### ISSUE TITLE
CJK Text doesn't repaint with the updated Locale, suggest to fallback to TW for HK locale

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter#18157]
Should be a follow-up of #16408. First I'd like to thank you for adding this feature. I can't wait to test it out, and have found two issues. 

I have created a simple Flutter app to illustrate the issues. It can be found at https://github.com/tamcy/flutter_cjktest.

Here's the version I am testing against:
```
[√] Flutter (Channel master, v0.5.2-pre.42, on Microsoft Windows [Version 10.0.17134.81], locale zh-HK)
    • Flutter version 0.5.2-pre.42 at C:\flutter
    • Framework revision 4cd5870ece (2 days ago), 2018-06-01 15:57:01 -0700
    • Engine revision 6cef519598
    • Dart version 2.0.0-dev.59.0.flutter-1a185867a9
```

The app shows the character "遍" which has a different preferred form for JP, CN, TW and HK. The text is rendered using the system font and a custom font (https://github.com/adobe-fonts/locl-test/) that is specialized for testing the feature. It also shows buttons to let users switch to another locale in the app.

Here are the issues that I found:

## A. CJK Text doesn't repaint along with the updated Locale

1. When I launch the app with the startup locale of zh_TW, the text is painted with the correct form: 

<img src="https://user-images.githubusercontent.com/959433/40902391-6ed7d932-6806-11e8-88a3-70545176ad67.png" width="500">

2. Now tap on the "ja_JP" button. The locale is successfully changed to ja_JP (note the "close" text is properly updated), but the text is still using the zh_TW form.

<img src="https://user-images.githubusercontent.com/959433/40902426-87918c02-6806-11e8-9abe-730e349af78a.png" width="500">

3. If I set the startup locale to ja_JP and relaunch the app, the text is rendered correctly:

<img src="https://user-images.githubusercontent.com/959433/40902508-d03ec546-6806-11e8-90b3-b3d7644d55c5.png" width="500">

It seems that currently only the starup locale is taken into account.

## B. zh_HK is falling back to zh_CN 

Currently Android doesn't offer localized CJK glyphs for HK. From the screenshot below, it appears that Flutter is using HK's preferred form to render the text when available, but it falls back to the CN form othrewise:

<img src="https://user-images.githubusercontent.com/959433/40902564-f3746278-6806-11e8-9bb6-5aea14118e70.png" width="500">

It is more preferrable to fallback to TW form if no HK form is available, for a number of reasons. To name a few:
 * HK's preferred forms are much closer to the TW forms than that of CN. 
 * The HK version of Noto Sans CJK is still under development, and Android is using TW glyphs for HK locale. 
 * Newer versoin of iOS offers seperate glyphs for TW and HK. Before that, TW and HK share the same set of region-specific ideographs, separate from CN.

**Comment by HansMuller** [comment]
The problem is a typo in RenderParagraph: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/paragraph.dart#L183

Should be:
```
    _textPainter.locale = value;
```

**Comment by tamcy** [comment]
Thanks for the fix. Shall I open another issue for the second problem? Or it's already confirmed that nothing could be done?

**Comment by HansMuller** [comment]
@jason-simmons Is there an open issue for "B" in https://github.com/flutter/flutter/issues/18157#issuecomment-394487314 ?
