### ISSUE TITLE
Why AutomaticKeepAlive widgets must be placed inside SliverMultiBoxAdaptorWidget?

### ISSUE THREAD

**Issue by letsar** [flutter/flutter#18151]
I'm writing a library for creating staggered grid views.
I created my own `SliverMultiBoxAdaptorWidget` in order to handle no-contiguous children and store children in a map and not in a double-linked list.

Now I have something working except when I set `addAutomaticKeepAlives` (for `SliverChildBuilderDelegate`) to true.
The Flutter error is `AutomaticKeepAlive widgets must be placed inside SliverMultiBoxAdaptorWidget`.
I looked into the source code but I don't see why this hierarchy is mandatory.

Can we not replace `SliverMultiBoxAdaptorWidget` by `RenderObjectWidget`?

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

Can you please provide a minimal reproduction for the error?

**Comment by letsar** [comment]
Yes it's still an issue, I created a PR (#19380) to separate the keep alive logic from `SliverMultiBox` classes this and I've been awaiting a code review.

For now, the error is be design, if you put an `AutomaticKeepAlive` in a widget where the parent is not a `SliverMultiBoxAdaptorWidget` it will throw this error. My PR aims to make the KeepAlive feature orthogonal to the child model.

**Comment by letsar** [comment]
Closing since this is not an issue anymore
