### ISSUE TITLE
initState on State classes MUST be called before any other method

### ISSUE THREAD

**Issue by gucotta** [flutter/flutter#18154]
Is this a desired behavior?

When I call initState right after the attributes definition it is recognized and will be called upon class instantiation. However, should I move it right any other method it won't be called.
Check the images..

![image](https://user-images.githubusercontent.com/33966755/40896021-036769f6-6789-11e8-8f9e-67deb483f477.png)

![image](https://user-images.githubusercontent.com/33966755/40896036-189643ba-6789-11e8-991f-1c41bebf5a4b.png)

**Comment by superciccio** [comment]
is missing the @override annototation... 
the order shouldn't matter :/

**Comment by zoechi** [comment]
Adding text (wrapped in ```) instead of screenshots would allow to copy the code.

**Comment by zoechi** [comment]
You are missing a `}` before `void initState()`

**Comment by gucotta** [comment]
My bad, there was indeed missing a '}'. Sorry, closing it.
