### ISSUE TITLE
Using DrawerItem for the stocks settings page is a problem

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1815]
Either we should rename DrawerItem to something more agnostic about its host, like InterfaceItem, or RowButton, or something, or, we should provide a new mechanism for things like the settings page.

**Comment by abarth** [comment]
@collinjackson was suggesting that we use ListItem.

Probably DrawerItem should be removed and drawer should use ListItem

**Comment by Hixie** [comment]
When fixing this, please make sure to document the behaviour of [onPressed] in whatever class replaced [DrawerItem].

**Comment by eseidelGoogle** [comment]
Given how little we've touched Stocks in the last year I think we can close this bug?

**Comment by Hixie** [comment]
This isn't really about stocks, it's a framework issue.

**Comment by HansMuller** [comment]
I'm going to see if we can eliminate DrawerItem (per the suggestions above).
