### ISSUE TITLE
CupertinoSliverNavigationBar border

### ISSUE THREAD

**Issue by andreatoso** [flutter/flutter#18152]
Is there a way to either remove or edit navbar's bottom border using `CupertinoSliverNavigationBar`? I've seen it is possible to do this with standard Cupertino's navigation bar `CupertinoNavigationBar`. I checked the documentation and apparently there's no way to do so.
<img width="372" alt="schermata 2018-06-03 alle 19 46 36" src="https://user-images.githubusercontent.com/19519148/40889483-b5f053b6-6767-11e8-88bd-4d8d3eeb21f7.png">

**Comment by leslieharland** [comment]
I'm note sure what you mean , but you may want to refer to this link

> https://stackoverflow.com/questions/49015038/removing-the-drop-shadow-from-a-scaffold-appbar-in-flutter

I searched 4 hours because I was mislead to think there are two app bars.

**Comment by andreatoso** [comment]
I'm building my app using CupertinoSliverNavigationBar without using the default navbar. Here's my code: 
`@override
  Widget build(BuildContext context) {
    return new Material(
        child: new Container(
      color: Colors.white,
      child: new CustomScrollView(
        slivers: <Widget>[
          new CupertinoSliverNavigationBar(
            largeTitle: new Text("Top Books"),
            backgroundColor: Colors.transparent,
          ),
          new TopBooksCollectionList()
        ],
      ),
    ));
  `
This is the navbar's bottom border I'm talking about:
<img width="372" alt="schermata 2018-06-03 alle 19 46 36" src="https://user-images.githubusercontent.com/19519148/40889458-75c19192-6767-11e8-9bb2-76eac83d18d8.png">

**Comment by leslieharland** [comment]
Yes, you can try using elevation: 0.0 in that Navigation bar widget. See if it works...

**Comment by andreatoso** [comment]
It doesn't work, as you can see in the documentation (https://docs.flutter.io/flutter/cupertino/CupertinoSliverNavigationBar-class.html) there's no this property

**Comment by xster** [comment]
Ah you're right, it's not in the API currently. Though it should be trivial to add if anyone wants to send us a PR :)  (e.g. have https://github.com/flutter/flutter/blob/4cd5870ecef50fbf4fd7e681cf327897f0695abe/packages/flutter/lib/src/cupertino/nav_bar.dart#L267 also pass in a border and have CupertinoSliverNavigationBar take in a border which defaults to `_kDefaultNavBarBorder`)
