### ISSUE TITLE
Unable to evaluate expressions with top level symbols like `print` or class names

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#18160]
I recently implemented something called "log points" in Dart Code where we let the user provide an expression and we wrap it in `print()` and send it to the debugger via `evaluateInFrame`. At some point in the past, I'm certain this worked fine:

<img width="700" alt="logpoint" src="https://user-images.githubusercontent.com/1078012/40912039-60ba0b54-67e8-11e8-9a99-f9b82306f96a.png">

However today, this seems completely broken. I've tried various versions of Flutter and Dart Code and can't make the example in the screenshot work at all (I even went back several beta versions). However, the same thing seems to work fine in Dart VM scripts.

Here's what I get back from the VM in Flutter when trying to use `print`:

```js
{
	"id": "400",
	"method": "evaluateInFrame",
	"params": {
		"expression": "print(\"\"\"_counter\"\"\")",
		"frameIndex": 0,
		"isolateId": "isolates/909101337"
	}
},
{
	"jsonrpc": "2.0",
	"result": {
		"type": "@Error",
		"_vmType": "UnhandledException",
		"kind": "UnhandledException",
		"id": "objects\/1",
		"message":"Unhandled exception:\nNoSuchMethodError: Class '_MyHomePageState' has no instance method 'print'.\nReceiver: Instance of '_MyHomePageState'\nTried calling: print(\"_counter\")\n..."
	}
}
```

And here's what happens if I try to use a class name like `DateTime`:

```js
Unhandled exception:\n'file:\/\/\/Users\/dantup\/Dev\/Dart-Code\/test\/test_projects\/flutter_hello_world\/lib\/main.dart':
malformed type: line 1 pos 9: cannot resolve class 'DateTime' from 'MyHomePage'
```

As well as affecting log points, this happens from the Debug Console, so if the user types `(new DateTime.now()).year` into the Debug Console for a Dart CLI script it works fine, but in Flutter it fails. Using the Flutter version of the SDK for both tests.

**Comment by devoncarew** [comment]
I think this is a dart2 issue - when the CFE is enabled by default. /cc @aam, who's been working expression evaluation in dart2. Alex, is there any new guidance in using expr. eval w/ the CFE enabled?

**Comment by aam** [comment]
Currently, in Flutter engine expressions are evaluated in dart1 mode by dart1-compilant parser that is built-in into engine's dart vm. With https://dart-review.googlesource.com/c/sdk/+/49061 and https://github.com/flutter/flutter/pull/16161 it will get switched to using flutter tools dart2 frontend for expression compilation.

Having said that, I am not sure what is the cause for errors above. Are you able to reproduce those failures if you use expression evaluation in observatory for Flutter app?

**Comment by DanTup** [comment]
@aam Yep, same thing in Observatory web app:

```
$ p print(1)
Unhandled exception:
NoSuchMethodError: No top-level method 'print' declared.
Receiver: top-level
Tried calling: print(1)
#0      NoSuchMethodError._throwNew (dart:core/runtime/liberrors_patch.dart:203:5)
#1      Eval (evaluate:source:1:7)
#2      main (file:///Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/lib/main.dart:3:10)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

```
$ p new DateTime.now()
Unhandled exception:
'file:///Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/lib/main.dart': malformed type: line 1 pos 5: cannot resolve class 'DateTime' from '::'
import 'package:flutter/material.dart';
    ^


#0      _TypeError._throwNew (dart:core/runtime/liberrors_patch.dart:84:75)
#1      Eval (evaluate:source:1:11)
#2      main (file:///Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/lib/main.dart:3:10)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by DanTup** [comment]
Since I have a screenshot showing this working from only a couple of weeks ago, if it's useful I could bisect this and find out which changesets work/fail if it's useful (it'll be a little bit manual, so I'm only gonna do it if you think it'd be useful).

**Comment by aam** [comment]
Ah, I realized just now I was not going far enough back to find working version of Flutter. Turns out it got broken back in March with culprit being 71b2cfb2a0724af692c298a62f86b3a934b6d3ca

**Comment by aam** [comment]
This should get fixed with the switch to dart2 frontend for expression compilation mentioned above in https://github.com/flutter/flutter/issues/18160#issuecomment-394405685

**Comment by DanTup** [comment]
>Turns out it got broken back in March

Weird, I must've somehow been on a really old version of Flutter when I coded this (which is possible, I do have many versions checked out from testing; but I hadn't deliberately been using them recently!).

Is switching the expression compilation to Dart 2 far off?

**Comment by aam** [comment]
Hopefully it happens today

**Comment by aam** [comment]
This should be fixed in f11c8d967c2b13d32badd5171273d12cb7625cee.

**Comment by DanTup** [comment]
LGTM, thanks! :)

<img width="643" alt="screen shot 2018-06-06 at 7 15 31 am" src="https://user-images.githubusercontent.com/1078012/41020079-6b2b8988-6959-11e8-9217-c66662affb5d.png">

**Comment by DanTup** [comment]
@aam there's a report in flutter-dev of evaluation issues recently - I'm not sure if they may have been introduced with this change:

https://groups.google.com/forum/#!topic/flutter-dev/O-mTAk00hos

I can't reproduce any issues myself so have asked for more info, but thought I'd give you a heads up. I'll open a new issue and ping you on it if I can get a repro/log file.

**Comment by aam** [comment]
thanks for the heads up @DanTup
