### ISSUE TITLE
Rectangle dimension doesn't match what was in constructor. 

### ISSUE THREAD

**Issue by jphsiao** [flutter/flutter#18169]
Created a rectangle with a size & offest. When validating the height of the rectangle the value isn't as expected. i.e.

```dart
  Offset offset = Offset.zero;
  Size size = new Size(
    availableWidth,
    0.85,
  );
  // size.height is 0.85
  Rect rect = offset & size;
  // rect.height is 0.8500000238418579
```

**Comment by zoechi** [comment]
This is caused because `Rect` stores the values in `Float32list` and this causes such accuracy loss.
@Hixie any idea if this can be fixed?

**Comment by zoechi** [comment]
```dart
void main() {
  final value = Float32List(1);
  value[0] = 0.85;
  double result = value[0];
  print(result);
}
```

**Comment by Hixie** [comment]
There's always going to be numbers that aren't precisely representable, but it's true that going from 64bit doubles to 32bit floats in Rect is a bit more aggressively imprecise than elsewhere in the system...

**Comment by Hixie** [comment]
cc @rmacnak-google @liyuqian any idea what the performance implications of having Rect use Float64List instead would be?

**Comment by liyuqian** [comment]
I think we need to have actual benchmarks to tell the implications. From my head, I'd be surprised if our flutter_gallery suddenly gets much slower if we switched to Float64 in our Rect.

On the other hand, Skia heavily uses SkScalar = Float32 so changing to Float64 on Flutter probably won't matter much for the rendering. If we ask Skia to change SkScalar to be Float64, the performance impact could be huge. Although CPUs may be as fast on Float64 as Float32, GPUs should be usually much faster on Float32.

**Comment by Hixie** [comment]
If we're going to stick with 32bit at the end anyway, I'm fine with leaving Rect at 32bit.

**Comment by rmacnak-google** [comment]
My intuition is the performance would be the same, with only memory usage different.

**Comment by goderbauer** [comment]
From the comments it sounds like this is working as intended.
