### ISSUE TITLE
On Android, consider tracing significant operations with Android Trace APIs

### ISSUE THREAD

**Issue by ChrisCraik** [flutter/flutter#18178]
From the Android platform side, it's often very useful to see what an app is doing from within Systrace, which shows tracing data from all the processes and services on the device: https://developer.android.com/studio/command-line/systrace

I know Flutter has its own tracing, but it's nice for platform/system-health folks to broadly know what's going on from just Systrace, especially in the context of graphics pipeline.

Note, there are now NDK APIs so you don't have to call up to Java: https://developer.android.com/ndk/guides/tracing

The tracing infrastructure on Android is optimized to be near zero cost when tracing isn't enabled, so it's just a single easily predicted branch in practice. It's somewhat expensive when tracing is on though (roughly 10us per begin/end pair), since it immediately serializes the data to a per-core trace buffer in Kernel owned memory.

Because they're expensive, we generally recommend starting with something minimal, like blocks for UI portion of frame, GPU portion of frame, and any expensive blocks of code like image decode, upload, or compositing operations. Typically want to have a couple dozen events per frame, more than that we've found to be too intrusive.

**Comment by eseidelGoogle** [comment]
I believe Flutter just sits on top of Dart's tracing: https://github.com/flutter/engine/blob/master/fml/trace_event.cc.  Maybe the Dart SDK should know how to plumb trace events down to systrace on Android?

**Comment by Hixie** [comment]
cc @a-siva

**Comment by Hixie** [comment]
cc @rmacnak-google

**Comment by rmacnak-google** [comment]
The VM already supports this. The engine can direct timeline events to Android systrace by setting `--timeline_recorder=systrace` in the VM flags.

**Comment by chinmaygarde** [comment]
@rmacnak-google: I can turn this on by default on Android. Will this also trace to observatory UI?

**Comment by rmacnak-google** [comment]
As discussed offline, this pushes events to systrace instead of the VM's trace buffer, so it would make Observatory show an empty timeline. A flag seems preferable, and would also make it easier to switch to the "startup" recorder when needed.

**Comment by Hixie** [comment]
Can we just always send to both?

**Comment by Hixie** [comment]
(Or have the Observatory fetch the systrace?)
