### ISSUE TITLE
Unable to run stocks app on ios

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#1817]
Trying to start the stocks example app on ios yields the following output in flutter start[1], and trying to open the xcode project and start it from there, yields the following error[2].

@chinmaygarde 

[1]
[flutter-start-out.txt](https://github.com/flutter/flutter/files/128514/flutter-start-out.txt)

[2]
<img width="427" alt="xcode-error" src="https://cloud.githubusercontent.com/assets/15253456/13017808/4a938b8a-d17b-11e5-9c0c-cda8ff9bba09.png">

**Comment by chinmaygarde** [comment]
Is an older version of the application already installed on the device?

**Comment by tvolkert** [comment]
Nope

**Comment by tvolkert** [comment]
Looks like this is related to the fact that there is already an ios folder in the stocks demo.  If I nuke that folder and re-create it via 'flutter ios --init', it works.

**Comment by tvolkert** [comment]
Gonna leave this open for now, since that bad ios folder is checked into git.
