### ISSUE TITLE
Preparing a signed apk release breaks application code

### ISSUE THREAD

**Issue by nathansamson** [flutter/flutter#18171]
## Steps to Reproduce

gist: https://gist.github.com/nathansamson/a1f9aa15d2c607093e2cf8d82480d39b

1. Use the basic "flutter" example app
2. Replace main.dart with the one from the gist
3. Build release apk (`flutter build apk --release`)
4. Copy the apk from `build/app/outputs/apk/release` to another directory (so it won't be overwritten). call this `app.apk`
5. Build signed release apk to upload to play store (`cd android; bundle exec fastlane beta`) (according to https://flutter.io/fastlane-cd/)
6. Copy the apk from `build/app/outputs/apk/release` to another directory call this `app-broken.apk`
6. Install `app.apk` to you phone. See it working fine (showing a list of A and B)
7. Uninstall the app, install `app-broken.apk`.
8. This last app shows "NoSuchMethod No static method 'fromJson' declared in class 'Complex". Reciever: Comple. Tried calling fromJson(_LinkedHashMap len:2)

## Logs

* The issue does not appear in flutter run modus (only the build apk)
* no flutter analyze errors

* doctor -v

```
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.4 at /home/nathan/flutter
    • Framework revision f9bb4289e9 (3 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/nathan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/nathan/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/nathan/android-studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Google • 192.168.56.101:5555 • android-x86 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by nathansamson** [comment]
It looks similar to https://github.com/flutter/flutter/issues/16182

When I do `new Complex.fromJson(...)` as opposed to `Complex.fromJson(...)` it seems to work...

**Comment by nathansamson** [comment]
So adding a few `new SomeClass.factoryMethod` fixed my build but I still think this is a bug

I am not yet familiar enough with dart/flutter to know if the new is strictly needed or what it does, but I don't expect such a behaviour change in debug / release / stripped release mode ( I assume I was running some stripped apk in the end)

**Comment by zoechi** [comment]
I think issues with optional `new` are fixed since a while.
If you still see this please add a comment to have this reopened.
Thanks for reporting!
