### ISSUE TITLE
ContainedButton has incorrect default border stroke color and size

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#18170]

**Comment by clocksmith** [comment]
The current button draws with a 2dp width and a static color, but it should be a 1dp width and 12% of the on surface color. Since on surface color does not exist in the theme, we can use 12% of black, but leave room for the on surface color to be easily added and obtain the 12% opacity.

 https://material.io/design/components/buttons.html#specs

**Comment by zoechi** [comment]
Can't find such information in the specs
and haven't found a `ContainedButton` in Flutter.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
