### ISSUE TITLE
iOS shell code needs to reflect engine changes

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18187]
@chinmaygarde has done a lot of extensive engine updates in the past weeks ([Google-internal doc](https://docs.google.com/document/d/1n7xgoIpgxMmbVqrkbhYQUHTg0br-By1RSv1psXDIMow)). We might need to update the iOS shell code to reflect this new world. 

It is unclear to me how much iOS code needs to change for this. @mravn-google @sigurdm who have done extensive changes for add-to-app use cases.

**Comment by xster** [comment]
@dnfield is there still any work left to do here? I took a quick look at Chinmay's doc and to a layman like me, it appears as if we're already compatible with what's listed.

**Comment by matthew-carroll** [comment]
@mehmetf @dnfield @chinmaygarde Does anyone know if we can close this ticket?

**Comment by matthew-carroll** [comment]
I'm going to close this because the ticket is old, most likely completed, and relevant parties have not chimed in on the status. Please re-open if the issue is still legitimate.
