### ISSUE TITLE
Support putting multiple Flutter bundles in a single APK/IPA

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18185]
In conjunction with https://github.com/flutter/flutter/issues/18114, we also need to support shipping multiple Flutter bundles in the same APK/IPA file. For this to work:

- Need to stop assuming [findAppBundlePath](https://github.com/flutter/engine/blob/86d96fd0ce8d58d2dfcd4398eb97aa66873d3bf7/shell/platform/android/io/flutter/view/FlutterMain.java#L228) is going to return a single path.
- Load the framework files (such as platform.dill) from a separate resource than application bundles.
- Change the way we record the bundle entries in manifest/plist.
- Come up with a way to discover all bundles in the app.
- Pick a reasonable default if no preference is provided.

**Comment by mravn-google** [comment]
@mehmetf Can you elaborate on why we need this? A single Flutter bundle should be able to handle all the views you'd want, if you specify `initialRoute` when creating each one.

**Comment by mehmetf** [comment]
@jason-simmons who is familiar with the discussions with mulligan.

Several motivators for this:
- Being able to load a section of Dart code only meant to execute in the background. I would want that isolate to have a rather small memory footprint and not load my entire Dart app (including Flutter framework itself).
- Have multiple isolates being able to load different bundles so we get proper isolation. With the workaround we currently suggest you would need to load the entire app into memory multiple times to achieve the same effect.
- We will need to support loading Flutter bundles off the wire. It seems that this requirement falls naturally from that.

**Comment by mehmetf** [comment]
I confirmed that customer: dream only needs to be able to dynamically load multiple apps. They don't care about multiple bundles in a single binary.

**Comment by sbaranov** [comment]
I think this can be closed, since Flutter already supports dynamically loaded bundles.

**Comment by mehmetf** [comment]
Sure. Let's close it. 

We get customers asking for this from time to time but the workaround we describe using `initialRoute` has been sufficient for them.
