### ISSUE TITLE
Metal support?

### ISSUE THREAD

**Issue by manhluong** [flutter/flutter#18196]
From here: https://developer.apple.com/ios/whats-new/ it seems that iOS 12 has deprecated OpenGL (look for "Deprecation of OpenGL ES")

From what I understand here: https://flutter.io/technical-overview/ flutter relies on Skia as the rendering engine.

Reading (very quickly) the Skia documentation, I understand that is based on OpenGL / Vulkan ( https://skia.org/user ).

**Question is**: what is the state of Flutter support for Metal?

Does it depend on Skia? For Skia I could find only mentions of Metal in the roadmap: https://docs.google.com/document/d/1LSdO3I-IdZVZCtEnW9pu3k_32gfPIcB_YeSn-OJBGZI/edit

**Comment by nackermann** [comment]
"Metal support has long been considered, this announcement just accelerates that work"

https://twitter.com/danardelean/status/1003737735134351362

**Comment by manhluong** [comment]
Ohh missed that tweet! Thanks @nackermann !

**Comment by timsneath** [comment]
Linking to the tracking issue for this (https://github.com/flutter/flutter/issues/18208) for those who come to this bug organically through Google.

**Comment by kangwang1988** [comment]
It depends on skia.
See: https://docs.google.com/document/d/1LSdO3I-IdZVZCtEnW9pu3k_32gfPIcB_YeSn-OJBGZI
