### ISSUE TITLE
Flutter TextFormField can not see input?

### ISSUE THREAD

**Issue by sarla999** [flutter/flutter#18191]
1. when click TextFormField then keyboard cover input area and input area not display anything.
2. add more TextFormField  out screen , TextFormField can not save input content.

I used Huawei 。

## Logs
no log

[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected devices
    ! No devices available```
```

**Comment by Kartik1607** [comment]
Kindly share some code which was used to create widget and screenshot of the issue.

**Comment by zoechi** [comment]
Dup of #10826 ?

**Comment by goderbauer** [comment]
Closing as dup of #10826.
