### ISSUE TITLE
Firebase Push notification Problem

### ISSUE THREAD

**Issue by rajeshjeshar** [flutter/flutter#18192]
**Scene1:**
When i tried to send push notifications **manually** via Firebase coud Messaging console,it shows notifications **without sound alert**

**Scene2:**
When i disconnect my device then Restarted the "**Run**" in Adroid studio,its not receiving any Notifications, [I MUST HAVE TO Go to my Mobile settings>Notifications>selecting the app then toggle between Turn Off And Turn On the "Show Notifications"]

**Scene3:** 
Even I have typed onresume(),onmessage(),**onLaunch()** functions,Its not showing notifications **after closing** the app

**Scene4:**
When i try to **trigger Firebase Realtime Database**,[When a entry is added or deleted i must receive notifications] **its not working**,But the code itself is deployed successfully??

**Scene5:**
[Scheduled notifications](https://pub.dartlang.org/packages/scheduled_notifications) are working fine with sound alerts too..but firebase notificationsare not working

**Device:** REDMI 4
**IDE:** VsCode ,Android Studio,

**Comment by zoechi** [comment]
I think this needs more information. 
- output of `flutter doctor`
- what is the content of the messages you sent?
- did you follow all the steps in the plugin README.md?

I think for sound `notification: {sound: 'default', ...` is required.
For notifications to be received when the app is not running `data: { click_action: 'FLUTTER_NOTIFICATION_CLICK', ...` needs to be added.

**Comment by rajeshjeshar** [comment]
@zoechi  **the sound issue is fixed by adding ur line.**
Now the only issue is,when the app is minimized it shows notification,**when the app is opened and i'm viewing the app its not showing notifications.**

So I created a testing app with [schedule notification](https://pub.dartlang.org/flutter/packages?q=shcedule+notification) library example,it shows notification even the app is opened and minimized,theres no issues.

then i decided to Add this shcedule notification project's .dart file as a new page 
on my Existing project,but this time the [schedule ntofication](https://pub.dartlang.org/flutter/packages?q=shcedule+notification) is also not showing anything

**Comment by zoechi** [comment]
See also https://stackoverflow.com/questions/50849185/flutter-firebase-push-notification-50-not-working

**Comment by rajeshjeshar** [comment]
@zoechi its me, the same person brother

**Comment by zoechi** [comment]
@rajeshjeshar can this issue be closed?

**Comment by rajeshjeshar** [comment]
@zoechi yes this can be closed and notifications are working 100%,now i'm writing a medium post on the way so it can be closed now thanks

**Comment by zoechi** [comment]
Thanks for the update.
Please post the link when the article becomes available.

**Comment by rajeshjeshar** [comment]
@zoechi here is the post in medium thanks>>
 https://medium.com/@rajeshjr/flutter-firestore-push-notification-on-data-change-youtube-style-subscribing-notifications-one-to-b09654db19e0

**Comment by alvinotienokelly** [comment]
when i try to onBackgroundMessage its says unknown paramter

**Comment by rajeshjeshar** [comment]
> when i try to onBackgroundMessage its says unknown paramter

There is no **onBackgroundMessage** inf Firebase messagiung Plugin.Hope you are asking about the OnLaunch() OnResume() methods ??

**Comment by alvinotienokelly** [comment]
Yes there is in the new version of flutter_messaging plugin

**Comment by alvinotienokelly** [comment]
> 
> 
> > when i try to onBackgroundMessage its says unknown paramter
> 
> There is no **onBackgroundMessage** inf Firebase messagiung Plugin.Hope you are asking about the OnLaunch() OnResume() methods ??

I think there is in the new flutter_messaging plugin version

**Comment by rajeshjeshar** [comment]
> > > when i try to onBackgroundMessage its says unknown paramter
> > 
> > 
> > There is no **onBackgroundMessage** inf Firebase messagiung Plugin.Hope you are asking about the OnLaunch() OnResume() methods ??
> 
> I think there is in the new flutter_messaging plugin version

Yeah! sorry Just now i've seen that change Log.

**Comment by kroikie** [comment]
@rajeshjeshar

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/809. Any further collaboration will be done there.

**Comment by shikharvaish28** [comment]
```
const payload = {
                notification: {
                    title: 'You have a new trip to '+dropLocation,
                    body: 'You have a trip to '+ dropLocation+' at ' + tripTime + ' on '+ tripDate,
                    sound: 'default',
                }
            };

            captainFirebase.messaging().sendToDevice(_token.data().token, payload);
```

I am using this code but the sound in not there when the notification is delivered.

**Comment by viveknimkarde** [comment]
@shikharvaish28 did you find any solution yet ?
