### ISSUE TITLE
Issue from website page Continuous Delivery using Fastlane with Flutter

### ISSUE THREAD

**Issue by csmac3144** [flutter/flutter#18197]
From URL: https://flutter.io/fastlane-cd/

These instructions are wholly inadequate. I am unable to get either Android or iOS to work at a "Hello World" level. iOS devolves into a morass of signing issues -- extremely confusing. Android instructions for me result in a "success", but the apk is visible nowhere in the dev portal.

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by Sfshaza** [comment]
@xster

**Comment by Sfshaza** [comment]
@csmac3144, did @xster answer your question? Please weigh in if there were other issues you encountered. It sounds like the info above can be added to the page.

**Comment by Sfshaza** [comment]
@xster, should this be added to the page? I'll close it out, otherwise.

**Comment by xster** [comment]
I think looking for updated releases on the Google Play Console is standard Play Store usage and isn't Flutter specific. I don't think we need to add more info onto our website.
