### ISSUE TITLE
updateChildren() needs to walk the list forward

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#182]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 05, 2015 at 21:59 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1495_

----

When you have a block with multiple focusable controls, the first one needs to get the focus. This means the first one needs to be the first to be built, so it's the first that calls build() and thus the first that calls Focus.at(). However, right now updateChildren() walks the list backwards which means the last child gets the focus.

We probably want to separate the creation of the Element nodes and the setting of the slots from the actual building of the children, somehow, so we can still walk the list backwards to create the slots but walk it forwards to build.

**Comment by Hixie** [comment]
Another side-effect of this is that if you have a list of images, we load the images bottom-first. That's weird-looking.
