### ISSUE TITLE
Flutter should use Metal instead of OpenGL on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#18208]
_From https://github.com/flutter/flutter/issues/33079:_

Based on guidance from the Skia team, the Metal backend is ready for integration into Flutter. This is a meta-bug listing the various tasks that need to be undertaken for the switch to be completed.

The Skia Metal backend is currently only available on iOS versions 11.0 and above. It is unlikely that the minimum supported version will be lowered all the way down to 8.0 (the current minimum supported by Flutter). The recommended approach is to compile both the OpenGL and Metal backends in the iOS engine and use runtime checks to only use the Metal backend on versions 11.0 and above. OpenGL will still be used on older iOS versions till support for the same persists.

### Tasks
Tracked on [this project board](https://github.com/orgs/flutter/projects/5) but the major ones are:
* Add the `enable-metal` GN flag to existing builds of the iOS engine and re-baseline benchmarks that measure binary size. Binary sizes are expected to regress by around [220 Kbytes uncompressed](https://gist.github.com/chinmaygarde/f0b6cc4924c4c09ac9dfe5dcf6e5d083).
* Enable the Metal backend on iOS versions 11.0 and above.
* Add an `enable-metal` shell flag that allows overriding the rendering backend to use without needing version checks. Duplicate all existing benchmarks to run the same with the Metal backend in addition to the OpenGL backend.
* Ensure plugins that that provide pixel buffers to to the engine for inline composition have the [appropriate compatibility flags set](https://developer.apple.com/documentation/metal/mixing_metal_and_opengl_rendering_in_a_view). 
* Ensure platform views are wired up.

References:
* Notice of OpenGL deprecation on iOS: https://developer.apple.com/ios/whats-new/
* Notice of OpenGL deprecation on Mac: https://developer.apple.com/macos/whats-new/
* Related Flutter issues: https://github.com/flutter/flutter/issues/32569, https://github.com/flutter/flutter/issues/18208

----

This is really a Skia bug, but tracking it here since we've gotten a flood of questions about this after Apple's announcement this week of deprecating OpenGL.

My understanding is Skia has an experimental Metal backend, but it would take some work to bring it to production ready.

Skia also already has a Vulkan backend which Flutter uses on Fuchsia, and has historically used on some Android phones (and could use again if there was demand -- it was recently disabled due to lack of demand).

Another advantage of moving to Metal sooner rather than later is that I'm told that Apple's GL drivers appear to be less maintained than they used to be, and Flutter/Skia have seen a resulting up-tick in Apple-specific GL bugs.

**Comment by eseidelGoogle** [comment]
Filed a bug with Skia https://bugs.chromium.org/p/skia/issues/detail?id=8050 and have reached out to the team directly.  There is some non-trivial amount of work to do here, but certainly possible.

**Comment by amrsolimanmoustafa** [comment]
I am now developing my first mobile app with flutter when i publish it apple store through couple of week what will happen ?

**Comment by pvmhoang** [comment]
I hope Flutter Dev Team will give us the answer about this one. I have just started to learning Flutter :(

**Comment by gedw99** [comment]
This is great news. Really happy about the transparency the flutter team are giving to events and users concern.

Vulcan and metal are not that dissimilar and there is a project called Molten that allowed Vulcan code to work at runtime on metal apple. I am sure the skis team are on to it.

Anyway this maybe will open the door to 3d scenegraphs but I digress .

**Comment by gedw99** [comment]
https://github.com/KhronosGroup/MoltenVK

**Comment by eseidelGoogle** [comment]
Apple has not announced any *removal* of OpenGL support.  Flutter works great on iOS, including iOS 12.

**Comment by Chozzle** [comment]
I think improvements need to be made quickly on the graphics rendering pipeline. This is the biggest thing holding our company back from developing in flutter. Look at the Hamilton app on an iPhone 6 for an example of unacceptable performance.

**Comment by Chozzle** [comment]
Any update on using MoltenVK? Does anyone know if this would allow much 2d performance improvement?

**Comment by SAGARSURI** [comment]
Even I am eagerly looking for an update on this from the dev team.

**Comment by FullstackJack** [comment]
Any movement on this? Should we start worrying that Skia won't make the June 2019 deadline causing Flutter apps to not work on iOS 13? That Skia ticket doesn't seem to have any progress attached.

**Comment by eseidelGoogle** [comment]
I'm not aware of any June 2019 deadline.  Can you link to some communication from Apple?

**Comment by ott-web** [comment]
My mistake. I had read speculation that it would be dropped with new versions of iOS and tvOS at WWDC 2019 in June. I just found this documentation though. See "Deprecations" section. They have begun phasing out OpenGL, but in your experience how many versions will Apple continue to support a deprecated API? We're already one in.

https://developer.apple.com/tvos/whats-new/

**Comment by stuartmorgan** [comment]
Carbon was deprecated in 2012, and it's not until the next release of macOS that it will finally be unavailable (as a side effect of dropping 32-bit support).

There's no way of predicting for any given API how long exactly Apple will keep it around, but announcing the deprecation of a widely used API and then suddenly removing it shortly after is not historically how they have done things. It would also be unusual for them to completely remove a major API without announcing the removal (not just deprecation) in advance.

**Comment by eseidelGoogle** [comment]
For those following along at home, progress continues on Metal support in Skia as part of https://bugs.chromium.org/p/skia/issues/detail?id=8243.  Still a lot of work to do here, just letting folks know this is not forgotten. :)

**Comment by tvolkert** [comment]
Update from @bsalomon on https://github.com/flutter/flutter/issues/31086#issuecomment-489655573

> it's probably not too early to start trying to integrate the Metal backend. We're at the point where it draws almost everything correctly and performance is approx equal to GL with low hanging fruit still left to pick.

**Comment by chinmaygarde** [comment]
Support in Flutter for rendering using Metal on iOS landed in https://github.com/flutter/engine/pull/8936. For now, the engine has to be manually built with the `--enable-metal` flag to have this backend enabled. We need to work some more on lowering the minimum iOS version. Currently, enabling the Metal backend bumps the floor up to 11.0 (from 8.0). But, I don't believe all the latest APIs are strictly necessary.

**Comment by Hixie** [comment]
We do not currently have immediate plans to enable this. We believe there are several weeks' worth of work left to do, and intend to address this once our current higher-priority issues are resolved.

**Comment by lightandshadow68** [comment]
Apple hasn't removed OpenGLES on iOS, despite being depricated, because there are a significant number of existing iOS apps that have shipped which are still using it. However, Apple's new Catalyst environment (iOS on Mac / Marzipan) does not support OpenGL ES as no Catalyst apps have shipped.

**Comment by stuartmorgan** [comment]
There are currently no specific plans to support Catalyst in Flutter, so that's not really a factor in near-term prioritization of this issue.

**Comment by sgldev** [comment]
+1

**Comment by Hixie** [comment]
We were discussing this in today's Triage meeting. Our current plan is to turn Metal on soon. This will increase the size of our engine by ~200KB. We can eventually reduce this by removing the OpenGL code but (a) that would drop support for <iOS10, which we don't want to do anytime soon (Skia only does Metal from iOS10), and (b) would require some work from the Skia team (OpenGL can't currently be removed from the codebase).

**Comment by stuartmorgan** [comment]
> that would drop support for <iOS10

Also the iPhone 5 and 5c, and the 4th generation iPad, all of which can run iOS 10, but don't support Metal.

**Comment by fisforfaheem** [comment]
direct x 11?

**Comment by dannyvalentesonos** [comment]
> We were discussing this in today's Triage meeting. Our current plan is to turn Metal on soon. This will increase the size of our engine by ~200KB. We can eventually reduce this by removing the OpenGL code but (a) that would drop support for <iOS10, which we don't want to do anytime soon (Skia only does Metal from iOS10), and (b) would require some work from the Skia team (OpenGL can't currently be removed from the codebase).

Hi @Hixie . Is there an update on when Flutter will be using Metal?
Also, once it is turned on, will plugins like the video_player which use the Texture Registry work immediately?

Thanks!

**Comment by chinmaygarde** [comment]
@dannyvalentesonos: The March 2020 milestone is accurate.  Metal is currently feature complete on iOS and gated behind a flag. Will provide updated guidance in a couple of days.

> will plugins like the video_player which use the Texture Registry work immediately?

Yes, plugins that use the texture registry like the video player and the camera are tested to work. More guidance surrounding  applications that use the texture registry to provide texture created using OpenGL for inline composition in Flutter will be forthcoming.

**Comment by chinmaygarde** [comment]
I am landing https://github.com/flutter/engine/pull/17431 which turns Metal on-by-default on iOS. A [Metal on iOS FAQ](https://github.com/flutter/flutter/wiki/Metal-on-iOS-FAQ) Wiki page attempts to answer all questions pertaining to this change.
