### ISSUE TITLE
How to differentiate connecting and connected states?

### ISSUE THREAD

**Issue by nex3** [flutter/flutter#18204]
_From @nailgilaziev on June 5, 2018 13:10_

First snapshot that StreamBuilder receives is `ConnectionState.waiting`
This happens when connecting started and in progress. 

after connection is established we do not receive any new snapshots. This is undetermined state.
used this code https://flutter.io/cookbook/networking/web-sockets/
print lines added to track snapshots
```
new StreamBuilder(
  stream: widget.channel.stream,
  builder: (context, snapshot) {
    print("connection state ${snapshot.connectionState}");
    print("data ${snapshot.data}");
    print("error ${snapshot.error}");
    return new Padding(
      padding: const EdgeInsets.symmetric(vertical: 24.0),
      child: new Text(snapshot.hasData ? '${snapshot.data}' : ''),
    );
  },
```
in logs you see only 
```
I/flutter ( 7150): connection state ConnectionState.waiting
I/flutter ( 7150): data null
I/flutter ( 7150): error null
```
 
If connection successful - last snapshot   is `ConnectionState.waiting`
If connection not successful and will die in future (ConnectionTimeout around 2 min) - now you see `ConnectionState.waiting` and can't decide what to do.

snapshot will be active only when server sends some data to client. 

_Copied from original issue: dart-lang/web_socket_channel#21_

**Comment by nex3** [comment]
_From @nailgilaziev on June 5, 2018 13:19_

detailed info about connectionTimeOut in https://github.com/dart-lang/web_socket_channel/issues/22

**Comment by nex3** [comment]
The `StreamBuilder` and `ConnectionState` classes are both from Flutter; I'm moving this issue to their repo.

**Comment by brianegan** [comment]
Thanks @nex3, and hey @nailgilaziev -- Interesting case! 

@nex3: I read through the docs and library a bit, but I couldn't see if there's a way to determine when the IOWebSocketChannel has successfully connected. I only saw information about the error case: when the websocket fails to connect.

From the docs: "If there's an error connecting, the channel's stream emits a WebSocketChannelException wrapping that error and then closes."

Is there a way to determine if the WebSocket is connected, such as a `Future connected` or anything (maybe not the best api, just off the top of my head)? If so, I can update the example to demonstrate how to handle this case.

**Comment by nex3** [comment]
`IOWebSocketChannel` just wraps `dart:io`'s [`WebSocket`](https://api.dartlang.org/stable/1.24.3/dart-io/WebSocket-class.html) class, and I'm not 100% confident about all of the details of how that works, but I *believe* that as soon as the future returned by `IOWebSocketChannel.connect()` completes the connection is successful. In other words, if you have an `IOWebSocketChannel` instance, it was at one point successfully connected.

**Comment by brianegan** [comment]
Thanks for the info! 

Reading through the code, it seems like [`IOWebSocketChannel.connect()`](https://github.com/dart-lang/web_socket_channel/blob/master/lib/io.dart) is a factory that synchronously returns an instance of a `WebSocketChannel`. Inside the constructor, it converts the `Future` returned by `WebSocket.connect` into a `StreamCompleter`. 

Since `IOWebSocketChannel.connect()` doesn't return a Future but rather a simple instance, and I didn't see any code that might emit a "Connected" status to the Stream, I wonder if this might be a feature missing from the `web_socket_channel` library? I could also be misreading the code and completely missed it :)

**Comment by nex3** [comment]
Ah, good point! We should probably add a `Future ready` getter. I'll re-open dart-lang/web_socket_channel#21 for that.

**Comment by zoechi** [comment]
Can this be closed as dup of https://github.com/dart-lang/web_socket_channel/issues/25 ?

**Comment by zoechi** [comment]
Closing as dup of dart-lang/web_socket_channel#25
