### ISSUE TITLE
ListView height issues on iOS

### ISSUE THREAD

**Issue by pk102** [flutter/flutter#18214]
I have an app that uses a listview inside a container, where the container has a "height" attribute. On iOS only, the listview will extend past the parent container's height constraint when the scroll position is at the top of the list.

If you scroll down, it resizes to the correct height. If the height constraint is reduced from 330.0 to 200.0, the issue goes away.

Screen shot shows correct behavior on Android(left) and incorrect behavior on iOS(right).
![screen shot 2018-06-05 at 2 42 14 pm](https://user-images.githubusercontent.com/3067039/40998983-21e167fa-68cf-11e8-9b8b-0cd59a2bc857.png)

## Steps to Reproduce

1) Run the Flutter app linked below on an iOS device or simulator.
https://gist.github.com/pk102/b8f13c002b3343cfafb8ec2c94a38d3e

## Logs

flutter analyze
Analyzing mhub_gdsm_app...                                       
No issues found! (ran in 3.0s)

```
```
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.4.4 at /Users/pkuzich/flutter/flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/pkuzich/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/pkuzich/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android P (API 27) (emulator)
    • iPhone 8                  • A46C8667-B457-4B47-B04B-53A8B8F9FD55 • ios         • iOS 11.4 (simulator)

• No issues found!

```
```

**Comment by chinmaygarde** [comment]
cc @Hixie

**Comment by BondarenkoStas** [comment]
I think the issue is not relevant anymore, couldn't reproduce it with v1.9.1+hotfix.5.
