### ISSUE TITLE
Configurable ConnectionTimeOut for HttpClient

### ISSUE THREAD

**Issue by nailgilaziev** [flutter/flutter#18210]
On mobile connection quality can vary depending on the environment conditions.
And if connection is bad sometimes connecting to websocket servers can't be established because of ConnectionTimeOut.
`WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.2.2, port = 56472`

Currently is around a 2min.
This is too long for creating a realtime applications, and sometimes we need to fail faster.
How this timeout can be configured?

This question belongs to `HttpClient`. Same issue happens when you make plain `GET`/`POST`/etc requests and use Websockets. For websockets case I can instantiate it like this from `HttpClient`
```dart
      var client = new HttpClient();
      var request = await client.openUrl(
          "GET", Uri.parse("http://localhost:${server.port}"));
      request.headers
        ..set("Connection", "Upgrade")
        ..set("Upgrade", "websocket")
        ..set("Sec-WebSocket-Key", "x3JJHMbDL1EzLkh9GBhXDw==")
        ..set("Sec-WebSocket-Version", "13");

      var response = await request.close();
      var socket = await response.detachSocket();
      var innerChannel = new StreamChannel<List<int>>(socket, socket);
      var webSocket = new WebSocketChannel(innerChannel, serverSide: false);
``` 

How can I configure ConnectionTimeOut? 2 minute is too long in some situations.

**Comment by chinmaygarde** [comment]
cc @xster

**Comment by zoechi** [comment]
Related https://github.com/dart-lang/http/issues/21

See also https://stackoverflow.com/questions/51487818/set-timeout-for-httpclient-get-request

**Comment by csells** [comment]
@nailgilaziev hopefully the Stackoverflow answers on this issue solve your problem. If not, please follow up on Stackoverflow. Thanks!
