### ISSUE TITLE
Why Flutter Inspector And Run are different in different PC computers?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#18223]
Different computers have different ways of handling？

1.  Flutter Inspector

I'm using the Flutter on a win7 computer,and also I'm using the Flutter on another win7 computer.
I have installed the same Android Studio And the same Flutter plugin and Dart plugin,all the same,but
when I'm running the same project,in different computer,the Flutter Inspector show different style.
One PC computer shows the simple Widgets that I'm using,but the another PC computer shows all Widgets  Tree(it is very terriable and it's very difficult to find the WIdgets thst I‘m using)
Maybe fix the bug quickly.

2. `Run` speed different.

I'm using the Flutter on a win7 computer,and also I'm using the Flutter on another win7 computer.
 When One PC computer  click `Run` , the running process finished just for 1minutes,and show a little logs in the  `Run` Console,and run app in my phone.
But When The another PC computer click `Run` ,the running process is running for 5minutes,and show a lot of logs in the `Run` Console.

I don't know why the same project,different computers have different ways of handling?

**Comment by zoechi** [comment]
please add the output of `flutter doctor` from both machines

**Comment by AweiLoveAndroid** [comment]
@zoechi 
look at  two screenshots:

![1111](https://user-images.githubusercontent.com/27602662/41075538-9f7d01a8-6a3f-11e8-9c9c-c283fad7474f.png)

![222](https://user-images.githubusercontent.com/27602662/41075542-a350c9f4-6a3f-11e8-9e26-fe80e8b22192.png)

**Comment by zoechi** [comment]
Can't see any `flutter doctor` output ;-)

**Comment by StormKid** [comment]
@zoechi This is not bug , This is the user When he install AS after select the setting between different verision.

**Comment by zoechi** [comment]
@StormKid not sure what you are trying to tell me.
If there is different behavior on 2 machines, the most basic informatiin to check is the output of `flutter doctor`

**Comment by StormKid** [comment]
@zoechi When we opened  the Android Studio after new install , we need choose a setting in beginning dialog .

**Comment by StormKid** [comment]
@zoechi IDEA also need choose

**Comment by AweiLoveAndroid** [comment]
`Run` speed different.

One win7 System computer:

`console`  screenshots:

it runs for 5 minutes,and it's too slow   and the log is too much more.


![](https://github.com/AweiLoveAndroid/Flutter-learning/blob/master/pics/Run%20Console1.png?raw=true)

**Comment by InMatrix** [comment]
The inspector UI difference is likely to be caused by AS and/or the Flutter plugin version difference between the two computers. Also, please make sure you checked `Run applications with --track-widget-creation` in the Language and Frameworks settings.  

![image](https://user-images.githubusercontent.com/348942/41188009-9586fcf8-6b6b-11e8-93a0-a4f781e769da.png)

**Comment by zoechi** [comment]
Still no `flutter doctor -v` output anywhere.
It would have shown what @InMatrix points out in above dialog easily.
I assume the mystery is solved. Thanks @InMatrix
