### ISSUE TITLE
Can I use SDK easily in the Flutter just like Android?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#18224]
I‘m an android deveoper,I hava a question:

as I know,There are many Flutter open source libraries on the `pub`，but I can not find the commonly used open source sdk such as Baidu map,XiaoMiPush,etc

Usually I use the `Over the wall software`  to access the Internet.
People can't use `Google` `Maps` `,Google` `push` ,firebase,etc if they can't use the `Over the wall software` ,and so they can't use the app that we have developed.

Can I use SDK easily in the Flutter just like Android?

**Comment by zoechi** [comment]
https://flutter.io/platform-channels/
https://flutter.io/developing-packages/#plugin
