### ISSUE TITLE
Problem occurs when running flutter commands

### ISSUE THREAD

**Issue by Thinura** [flutter/flutter#18229]
I recently reset my windows. Before that I was using Flutter. Then I downloaded flutter again. and set my environmental variables as C:\Program Files\flutter\bin but when I use cmd for flutter commands this occurs. But when I run flutter commands in administrator cmd it works.

## Logs
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter 

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Program Files\flutter\version' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:354)
#1      _rootRunUnary (dart:async/zone.dart:1134)
#2      _CustomZone.runUnary (dart:async/zone.dart:1031)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#5      Future._propagateToListeners (dart:async/future_impl.dart:662)
#6      Future._completeWithValue (dart:async/future_impl.dart:477)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.81], locale en-US)
    • Flutter version 0.4.4 at C:\Program Files\flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk\
    • Android NDK at C:\Users\HP\AppData\Local\Android\Sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\HP\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.13.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
You shouldn't put Flutter in `C:\Program Files`, that folder is protected on Windows so non-Admins cannot write in it and Flutter needs to write files as part of normal usage. You should move Flutter to somewhere that your user can write without elevated permissions. There are some changes in a future version that better detect when you do this and give a more appropriate message.

It's also possible that if you've copied this folder from a previous Windows install that the file permissions on it are a bit messed up, you should reset them to inherit permissions form the parent folder once you've moved it.

**Comment by AashiqinCode** [comment]
> I recently reset my windows. Before that I was using Flutter. Then I downloaded flutter again. and set my environmental variables as C:\Program Files\flutter\bin but when I use cmd for flutter commands this occurs. But when I run flutter commands in administrator cmd it works.
> 
> ## Logs
> Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> 
> ## command
> flutter
> 
> ## exception
> FileSystemException: FileSystemException: Cannot open file, path = 'C:\Program Files\flutter\version' (OS Error: Access is denied.
> , errno = 5)
> 
> ```
> #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:354)
> #1      _rootRunUnary (dart:async/zone.dart:1134)
> #2      _CustomZone.runUnary (dart:async/zone.dart:1031)
> #3      _FutureListener.handleValue (dart:async/future_impl.dart:129)
> #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
> #5      Future._propagateToListeners (dart:async/future_impl.dart:662)
> #6      Future._completeWithValue (dart:async/future_impl.dart:477)
> #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
> #8      _rootRun (dart:async/zone.dart:1126)
> #9      _CustomZone.run (dart:async/zone.dart:1023)
> #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
> #11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
> #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
> #13     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
> #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
> ```
> 
> ## flutter doctor
> ```
> [✓] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.81], locale en-US)
>     • Flutter version 0.4.4 at C:\Program Files\flutter
>     • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
>     • Engine revision 06afdfe54e
>     • Dart version 2.0.0-dev.54.0.flutter-46ab040e58
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk\
>     • Android NDK at C:\Users\HP\AppData\Local\Android\Sdk\ndk-bundle
>     • Platform android-27, build-tools 27.0.3
>     • ANDROID_HOME = C:\Users\HP\AppData\Local\Android\Sdk\
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 25.0.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
> 
> [✓] VS Code, 64-bit edition (version 1.23.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Dart Code extension version 2.13.0
> 
> [!] Connected devices
>     ! No devices available
> 
> ! Doctor found issues in 1 category.
> ```

Open cmd as Administrator

**Comment by DanTup** [comment]
> Open cmd as Administrator

Please see my comment above yours. You should move Flutter to a non-protected folder instead of running as admin.

**Comment by superuser-chi** [comment]
Guys please help me i am facing a similar issue. The output is the same even though i run command prompt as admin.

# Command
flutter
# Output
Access is denied.
Building flutter tool...
Running pub upgrade...
CreateProcessW failed 193

CreateProcessW failed 193

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\WINDOWS\system32\git.EXE -c log.showSignature=false log -n 1 --pretty=format:%H
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:640:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#5      _runGit (package:flutter_tools/src/version.dart:665:23)
#6      new FlutterVersion (package:flutter_tools/src/version.dart:54:26)
#7      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:133:29)
#8      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#10     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#12     flutterVersion (package:flutter_tools/src/globals.dart:77:46)
#13     new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:190:51)
#14     new Usage (package:flutter_tools/src/reporting/usage.dart:79:9)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:184:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#17     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#20     flutterUsage (package:flutter_tools/src/globals.dart:45:35)
#21     _handleToolError (package:flutter_tools/runner.dart:124:13)
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:78:13)
#23     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:72:17)
#24     _rootRunBinary (dart:async/zone.dart:1208:13)
#25     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#26     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1591:19)
#27     _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#28     Future._propagateToListeners (dart:async/future_impl.dart:632:16)
#29     Future._completeError (dart:async/future_impl.dart:534:5)
#30     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
#32     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#33     _rootRunBinary (dart:async/zone.dart:1204:38)
#34     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#35     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#36     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#37     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#38     Future._completeError (dart:async/future_impl.dart:534:5)
#39     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:582:7)
#40     _rootRun (dart:async/zone.dart:1184:13)
#41     _CustomZone.run (dart:async/zone.dart:1077:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
