### ISSUE TITLE
IconButton really needs a background color option

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#18220]
when used like so:

```dart
IconButton(
             color: Colors.red,
             icon: new Icon(Icons.chevron_left, color: Colors.green, ),
             onPressed: () => {},
),
```

you should be able to set a background color.  either with an explicit field, like with the floating action button, or at least have the color field set it if the Icon color is set like above.

**Comment by apaatsio** [comment]
While waiting for this feature to land, if you want a round icon button with background color here's one way:

```dart
ClipOval(
  child: Container(
    color: Colors.blue,
    child: IconButton(icon: Icon(Icons.pause)),
  ),
)
```

**Comment by HansMuller** [comment]
It's possible to create an IconButton with a filled background that works nicely with the ink splash and highlight: https://github.com/flutter/flutter/pull/26611

**Comment by JojoSalustiano** [comment]
Is better to add only Color or BoxDecoration?

**Comment by duzenko** [comment]
To save other people the pain of clicking through the links
The "recommended" solution
```
              Ink(
                decoration: ShapeDecoration(
                  color: App.color,
                  shape: CircleBorder(),
                ),
                child: IconButton(
                  icon: Icon(Icons.add),
                  color: Colors.white,
                  onPressed: addArea,
                ),
              ),

```
even though it's really just a quick and dirty work around
