### ISSUE TITLE
Navigator needs a way to get the lenght of the history

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#18239]
There need to be a way to access the lenght of the navigator history. e.g. if you want to perform a specific action only if the navigator is at the base route, ...

**Comment by chinmaygarde** [comment]
cc @HansMuller

**Comment by git-xbits** [comment]
I need this solution too.

**Comment by shashikantshaale** [comment]
I had a use case where the navigator has route _**xyz**_

**Comment by markusaksli-nc** [comment]
Please follow up on #45938 and feel free to comment there, closing this issue to track it there.
