### ISSUE TITLE
BackButton does not have ripple effect

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#18240]
The BackButton does not have a ripple effect.
Placing the BackButton in a InkWell does not make the ripple effect appear. 

This behavior is similar to how the back button in a SliverAppBar does not have a ripple effect unless the bar is collapsed. 

Is this effect intentional or perhaps a bug?

**Comment by chinmaygarde** [comment]
cc @HansMuller

**Comment by zoechi** [comment]
I can't reproduce in Gallery app.

Are you still seeing this?

**Comment by zoechi** [comment]
Could be #14202

If you can reproduce please post a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
