### ISSUE TITLE
Make the drag gesture recognizers start from the commit point, not the down point

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#18249]
If a drag gesture recognizer has to compete, then it will commit when the pointer is at a different point than when the gesture started. Currently, we give drag deltas based on the delta from the original point. We should add a configuration option that allows the drag gesture deltas to be based on the commit point instead, and then we should default GestureDetector's gesture recognizers to match the platform's behaviour (which, at least on Android, is to use the commit point).

**Comment by edman** [comment]
Hixie, I'm looking into this issue. What do you mean by commit point? Is that the point from which we're sure it's a drag and the GestureDetector emits an onDragStart?

Also, can you give me pointers on how the platform-specific configuration can be set up?

**Comment by Hixie** [comment]
Yes, the commit point would be when we send onDragStart.

Platform-specific configuration at the widget layer looks like:
https://github.com/flutter/flutter/blob/9fe53b0d2bb091535c16689cab705c95eac1c53d/packages/flutter/lib/src/material/scrollbar.dart#L81-L99

In this case this would be in GestureDetector. However, it's possible that actually all platforms want the same behaviour, in which case it would just be a matter of setting the default behaviour on the recognizer to be the commit point.

**Comment by goderbauer** [comment]
@jslavitz Does your PR https://github.com/flutter/flutter/pull/23424 address this?

**Comment by goderbauer** [comment]
Related: https://github.com/flutter/flutter/issues/15144

**Comment by nt4f04uNd** [comment]
Does the DragStartBehavior do that now?
