### ISSUE TITLE
In Flutter Gallery app, button ripples don't fade away

### ISSUE THREAD

**Issue by ChrisCraik** [flutter/flutter#18244]
Repro steps:

1. Open Flutter Gallery on Android (I'm using Nexus 5x, running O)
1. Start a long press on the "Material" button
1. Drag your finger away

Expected: Ripple fades away

Observed: Ripple disappears instantly

Repros on every button in the initial page, as well as on every every list item in the "Material" list.

Note that this doesn't affect the 'double' ripples on the toolbar - the up button and overflow menu seem to cancel and fade away correctly

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
It looks like InkRipple is starting its fadeOut controller too early, will fix this.

**Comment by lixiaoyan** [comment]
Any updates on this issue?

**Comment by TahaTesser** [comment]
Hi @ChrisCraik 
Testing on flutter_gallery example from latest `stable` channel SDK
Ripples seems to fade away when slow animation is enabled

if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
