### ISSUE TITLE
In Flutter Gallery, list items wiggle as they are tapped

### ISSUE THREAD

**Issue by ChrisCraik** [flutter/flutter#18245]
Looks like a rounding error, maybe related to moving content onto layer?

1. Open "material" list (On Nexus5x running O)
1. Long press on any list item

Expected: Ripple highlight, nothing more

Observed: Ripple highlight, and the list item title offsets vertically by a single pixel

**Comment by Hixie** [comment]
cc @cbracken

**Comment by markusaksli-nc** [comment]
Closing as no longer relevant.
