### ISSUE TITLE
Target of URI doesn't exist: 'package:intl/intl.dart'.

### ISSUE THREAD

**Issue by cityinthepark** [flutter/flutter#18257]
Hi there,

I can't import 'package:intl/intl.dart'.
Always complaint: Target of URI doesn't exist: 'package:intl/intl.dart'.

I"m using VS Code, and flutter doctor return no issue.

Thanks!

**Comment by jonahwilliams** [comment]
@cityinthepark do you have a dependency on package:intl in you pubspec?

**Comment by cityinthepark** [comment]
Oh thank you so much!! Now it’s gone. 

I’m very new to Flutter.

**Comment by jonahwilliams** [comment]
No problem!

**Comment by arslankaleem7229** [comment]
I added intl in pubspec but it's still showing error when i import

**Comment by saadassali** [comment]
@arslankaleem7229 i have the same issue

**Comment by Achudh** [comment]
Just run pub get it! it worked for me since I copy pasted the code from elsewhere and forgot to do a pub get. Rookie mistake
