### ISSUE TITLE
How to stop the Tab Controller's swipe effect?

### ISSUE THREAD

**Issue by cityinthepark** [flutter/flutter#18258]
Hi there,

I was able to add tab controller to my Flutter project. But I do not like the swipe effect that I can swipe between different tabs. Is there a way to stop this effect?

I've tried couple ways, with or without SingleTickerProviderStateMixin. So far no luck.

Thanks a lot,

**Comment by HansMuller** [comment]
This feature has been requested before: https://github.com/flutter/flutter/issues/16474

It's on the Flutter 1.0 feature list.

I'm going to close this issue as a duplicate

**Comment by felipecesar42** [comment]
I'm using `physics: NeverScrollableScrollPhysics(),` inside TabBarView and seems to be working so far.
