### ISSUE TITLE
FirebaseMessage plugin Future never rejects if app is tested on simulator

### ISSUE THREAD

**Issue by ajaybeniwal** [flutter/flutter#18259]
## Steps to Reproduce
I have integrated the firebase message plugin inside my login call but the problem is that the future value never rejects ,it works fine for device since push works fine for ios device but in simulator my code never goes inside the catch block

```dart
login().then((token){
                print("token is recieved with a value");
                return _firebaseMessaging.getToken();
              }).then((firebaseToken){
                print("got a value from firebaes token");
              })
              .catchError((e){
                print("could not get the firebase token value");
                print("stack trace value is unknown");
              });
```

**Comment by chinmaygarde** [comment]
cc @collinjackson

**Comment by kroikie** [comment]
@ajaybeniwal

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/805. Any further collaboration will be done there.
