### ISSUE TITLE
Make ImageProvider errors knowable

### ISSUE THREAD

**Issue by xster** [flutter/flutter#18255]
It seems like ImageProvider.resolve API users has no way of handling errors. 

In https://github.com/flutter/flutter/blob/06140f2b14e3504efc9d112f50843df9442510f4/packages/flutter/lib/src/painting/image_provider.dart#L259, it seems like there's some intent to have non-existent asset loading pipe into a FlutterError.reportError and return a null stream but that path is typically not executed. 

In providers like NetworkImage or PlatformAssetBundle, `load` would construct a MultiFrameImageStreamCompleter that receives a Future.error in the `codec` param. 

MultiFrameImageStreamCompleter would internally swallow that error in its construction but still successfully construct. It would however never receive any progress on its codec. And by that point, ImageProvider.resolve would have already created the stream which would never receive any events on its listeners. 

From the ImageProvider.resolve user's perspective, an ImageStream is created but stuck forever.

**Comment by jonahwilliams** [comment]
Took a look at this when I was working on image caching.  We should  just expose a completeError method on ImageStreamCompleter and an addErrorListener method on ImageStream.
