### ISSUE TITLE
Reference Navigator.of(rootNavigator) in CupertinoTabScaffold documentation

### ISSUE THREAD

**Issue by HaijunWei** [flutter/flutter#18264]
How to hide the CupertinoTabView on pushed like Native iOS APP

**Comment by chinmaygarde** [comment]
cc @Hixie

**Comment by xster** [comment]
Can you elaborate a bit more on what you meant. Or do you have a mock up of the effect you would like to achieve?

**Comment by HaijunWei** [comment]
On the native iOS app, there is an option called hide tabbar on pushed. I didn't find the suboption in Flutter. I don't know how to hide the tabbar in the lower level.

**Comment by zoechi** [comment]
I found https://freakycoder.com/ios-notes-45-how-to-hide-tabbar-when-push-viewcontroller-adceb582a55c, https://stackoverflow.com/questions/8701362/how-to-hide-the-tabbar-when-push-a-view

**Comment by HaijunWei** [comment]
@zoechi  Thank you. I want to know what to do in flutter.

**Comment by xster** [comment]
@HaijunWei, without more details about the navigation hierarchy you're trying to achieve, it's hard to give a specific recommendation. 

If the Cupertino navigation demo's third tab is the effect you're trying to do 
https://github.com/flutter/flutter/blob/226f2c1e99accab83d12bfd49e805f8d7d2d3ed6/examples/flutter_gallery/lib/demo/cupertino/cupertino_navigation_demo.dart#L712

You can use [Navigator.of](https://docs.flutter.io/flutter/widgets/Navigator/of.html) with `rootNavigator = true` to retrieve the Navigator above the CupertinoTabView/CupertinoTabScaffold and push a route over everything.

**Comment by HaijunWei** [comment]
Thanks for help. It work.

**Comment by xster** [comment]
Re-opening as a task item to cross reference `rootNavigator` in the CupertinoTabScaffold documentation

**Comment by adriancmurray** [comment]
@xster curious is there a way to use rootNavigator with pushNamed?

**Comment by Sun3** [comment]
If you are relying on using Bloc or Provider when you use the ```rootNavigator: true``` the side effect is loosing previous Bloc state. This causes a serious issue with passing down state to the page navigated to.

**Comment by liwenDeng** [comment]
The rootNavigator option is removed. Is there any other solution?
