### ISSUE TITLE
video_player can not play video

### ISSUE THREAD

**Issue by JDNew** [flutter/flutter#18263]
I wrote the sample according to the offcial sample , while I get such errors:

code:
```
import 'package:flutter/material.dart;
import 'package:video_player/video_player.dart';

class VideoDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("VideoDetail"),
      ),
      body: new Column(
        children: <Widget>[
          new VideoWidget(),

        ],
      ),
    );
  }
}

class VideoWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new VideoState();
  }
}

class VideoState extends State<VideoWidget> {
  VideoPlayerController _controller;
  bool _isPlaying = false;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller = new VideoPlayerController.network("http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4")
      ..addListener(() {
        final bool isPlaying = _controller.value.isPlaying;
        if (isPlaying != _isPlaying) {
          setState(() {
            _isPlaying = isPlaying;
          });
        }
      })
      ..initialize();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new Center(
      child: new Padding(
        padding: const EdgeInsets.all(10.0),
        child: new AspectRatio(
          aspectRatio: 1280 / 720,
          child: new VideoPlayer(_controller),
        ),
      ),
    );
  }
}
```

> E/ExtMediaPlayer-JNI( 8765): env->IsInstanceOf fails
E/MediaPlayer-JNI( 8765): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/ExtMediaPlayer-JNI( 8765): env->IsInstanceOf fails
E/MediaPlayer-JNI( 8765): JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
D/MediaHTTPConnection( 8765): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 6.0.1)
D/MediaHTTPConnection( 8765): proxy null port 0
D/MediaHTTPConnection( 8765): proxy null port 0
D/MediaHTTPConnection( 8765): proxy null port 0
D/MediaPlayer( 8765): setSubtitleAnchor in MediaPlayer

flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.24.0)
[✓] Connected devices (1 available)
! Doctor found issues in 1 category.

My phone is onePlus 2 , Android 6.0.1

**Comment by zoechi** [comment]
please add the output of `flutter doctor`
and if possible the code that allows to reproduce
