### ISSUE TITLE
 FormatException: Bad UTF-8 encoding 0x3f (at offset 0)

### ISSUE THREAD

**Issue by qq1148120042** [flutter/flutter#18261]
Finished with error: FormatException: Bad UTF-8 encoding 0x3f (at offset 0)

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

What code and what action caused this error?

**Comment by JerryJian** [comment]
I had the same problem. Maybe it's caused by Chinese characters.
When I change the Chinese strings in main.dart, it is successfully built and run.
And change the Chinese back, no error occurred.

**Comment by NawazS** [comment]
I had the same problem. Using ENG-UK windows.

Changing my project encoding to UTF-8 also fixed the problem.

File -> Other Settings -> Settings For New Project, then find "File Encodings", change Project Encoding to UTF-8.
