### ISSUE TITLE
NSURLSessionConfiguration Discretionary property breaks redirects on iOS Simulators when running from Android Studio and Flutter command line,  but not XCode.

### ISSUE THREAD

**Issue by tomnewton** [flutter/flutter#18272]
I've come across a fairly major issue when running/debugging a flutter app on the iOS simulator from Android Studio or using `flutter run -d iPhone\ X`. This issue does not occur when building/running from XCode. 

## Steps to Reproduce

I have built a minimal plugin project with [README](https://github.com/tomnewton/posixerror/blob/master/README.md) and there are also comments to help demonstrate in the [PosixerrorPlugin.m](https://github.com/tomnewton/posixerror/blob/master/ios/Classes/PosixerrorPlugin.m) file to demonstrate: [https://github.com/tomnewton/posixerror](https://github.com/tomnewton/posixerror)

If you set the NSURLSessionConfiguration discretionary property to `YES`, and then try to load any url that redirects, you get an error when building/running/debugging from Android Studio, but not if you build the same project directly from XCode ( i.e. the Runner ). 

When this issue occurs you'll see the failure with the following NSError logged in the debug output in Android Studio, or to the command line if running with `flutter run`:
```
Error Domain=NSPOSIXErrorDomain Code=22 
"Invalid argument" UserInfo={_kCFStreamErrorCodeKey=22, _kCFStreamErrorDomainKey=1}
```

I've also seen a similar issue on the Xamarin project, so maybe related? [Xamarin bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=59793)

## Flutter Doctor
```
[✓] Flutter (Channel unknown, v0.4.2, on Mac OS X 10.13.4 17E202, locale en-KY)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (2 available)


```

**Comment by chinmaygarde** [comment]
cc @cbracken who may have an idea as to what is going on. The application generated by the tooling (invoked by Android Studio) calls `xcodebuild` under the hood. So building from Xcode and the tools should be exactly the same.

**Comment by tomnewton** [comment]
@chinmaygarde is there a different connection created to debug when debugging dart in Android Studio or command line vs the debug connection from xcode when debugging the obj-c code?

**Comment by cbracken** [comment]
I can't say I've run across anything like this before. Quick search turns up the following results:

* https://stackoverflow.com/questions/26396166/unable-to-run-app-in-simulator
* https://github.com/react-community/create-react-native-app/issues/169

Does this occur if you do a `flutter clean`, then `flutter run`? Would you mind attaching the results of the following commands?
```
flutter clean
flutter --verbose run
```

**Comment by BondarenkoStas** [comment]
Is the issue still relevant?

**Comment by iapicca** [comment]
Hi @tomnewton 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
