### ISSUE TITLE
Can i use multiple firebase for firebase auth?

### ISSUE THREAD

**Issue by 3ch3r46** [flutter/flutter#18279]
Firebase auth still using google-service.json. if i use them, can only authenticate for 1 firebase.
So how can i use multiple firebase for authentication?
Please help.

**Comment by chinmaygarde** [comment]
cc @collinjackson

**Comment by OscarEReyes** [comment]
The following blog post details how to do this, however Flutter's FirebaseAuth plugin does not support non-default FirebaseApps at the moment.

https://firebase.googleblog.com/2016/12/working-with-multiple-firebase-projects-in-an-android-app.html

**Comment by HerrNiklasRaab** [comment]
How to do this for iOS?

**Comment by bparrishMines** [comment]
We recently added multi-app support for `firebase_auth` you can now use the `FirebaseAuth.fromApp` constructor to reference different, non-default apps. https://pub.dartlang.org/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/FirebaseAuth.fromApp.html

**Comment by zoechi** [comment]
Related to #23049

**Comment by collinjackson** [comment]
Per @bparrishMines's comment, this should work now.

**Comment by kroikie** [comment]
@3ch3r46

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/804. Any further collaboration will be done there.
