### ISSUE TITLE
Make persistent bottom sheet swipe-to-dismiss an "opt-out" feature

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#18277]
Currently persistent bottom sheets, displayed with showBottomSheet() can be dismissed by swiping downwards. Disabling that by default would be a backwards incompatible change, but it could be an "opt out" feature.

This feature was requested here: https://github.com/flutter/flutter/issues/17928

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/18379 addressed this in a different way: bottom sheets specified with the bottomSheet Scaffold parameter can't be dismissed by swiping downwards.

**Comment by 1and1get2** [comment]
@HansMuller 
is it possible to make a persistent bottom sheet that
1. non dismissable
2. yet expandable (can swiping up to reveal more content, which is similiar to android bottomsheet)

**Comment by feinstein** [comment]
@HansMuller I agree that Flutter Bottom Sheet isn't behaving as the Android Bottom Sheet.

The Android Bottom Sheet can be configured to be `hidable` or not, it can be asked to `expand` or `collapse`.

In Android we can set the `peek height` of the Bottom Sheet so it will collapse to that height, whereas the Flutter Bottom Sheet appears to be way more limited, not satisfying the Material Guidelines and be more cumbersome to work with.

**Comment by tossaro** [comment]
try this guys https://github.com/tossaro/bottom_sheet_stateful
