### ISSUE TITLE
Cupertino dialog barrier should be #66000000

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#18285]
Currently the Cupertino dialog shares logic with the material dialog and the barrier color is set to Black54.

The Cupertino dialog should have a black barrier at #66 opacity, AKA #66000000

This ticket is to achieve the desired barrier color, which will require refactoring showDialog() behavior to be different for material vs cupertino.

**Comment by xster** [comment]
This is done right?

**Comment by matthew-carroll** [comment]
I think so.  It was Nathalie's work.  I didn't get around to reviewing it closely, but I believe she merged in showDialog for Cupertino with updated colors.

**Comment by xster** [comment]
`showCupertinoDialog` shows a 0x6604040F barrier. Please re-open if we need further adjustments.

**Comment by matthew-carroll** [comment]
@xster this reminds me, we really need to start documenting where we get all the iOS color and style values from.  Some come from Apple docs, others are roughly estimated with a color picker from an iOS app.  If we ever need to verify then we'll want to know where a given value came from.

**Comment by xster** [comment]
ya, good point. https://github.com/flutter/flutter/issues/21302
