### ISSUE TITLE
CupertinoDialogAction does not change color on press

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#18280]
CupertinoDialogAction does not change color when the user taps on it in a dialog.  A standard iOS dialog button gets darker when tapped.

**Comment by aqwert** [comment]
related/dup: https://github.com/flutter/flutter/issues/14886

**Comment by matthew-carroll** [comment]
This issue was resolved with the CupertinoAlertDialog work that was merged.  There are still color issues with CupertinoAlertDialog related to the dividers and popup surface background color, but this particular issue is handled.
