### ISSUE TITLE
setTextEntryEmulation docs contradicting

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#18286]
From https://docs.flutter.io/flutter/flutter_driver/FlutterDriver/setTextEntryEmulation.html:

> When disabled, `enterText` will fail with a DriverError. [...] In disabled mode `enterText` can be used to emulate text entry.

Which one is it when disabled? It fails with an error? Or it can be used to enter text?

/cc @yjbanov

**Comment by yjbanov** [comment]
Yep, the last sentence is incorrect, and unnecessary, since the very first sentence in the doc already explains it.

https://github.com/flutter/flutter/pull/18298
