### ISSUE TITLE
flutter sdk is not found in the specified location

### ISSUE THREAD

**Issue by tmexcept** [flutter/flutter#18296]
I'm used Android Studio.
I had download a flutter demo , when i change branch use 'flutter channel beta' with command line, then the IDE cannot found Flutter SDK, also i set the right path. But, if i change branch use 'flutter channel master' with command line, it will be right, and work well.
I would appreciate it if someone could give me a solution

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by tmexcept** [comment]
Thanks，problem solved!
![image](https://user-images.githubusercontent.com/10299901/41210801-5a043414-6d66-11e8-8c1a-8ae3bb9836cf.png)

**Comment by zoechi** [comment]
If you installed Flutter into `c:/Program Files` try installing it into a directory that doesn't require admin privileges for writing.

**Comment by tmexcept** [comment]
@zoechi I installed it into `C:\python36\Lib\site-packages`

**Comment by zoechi** [comment]
@tmexcept That directory should be fine if the user your are logged in with does have write permissions.

**Comment by tmexcept** [comment]
Yes, and thanks for your Help!

**Comment by zoechi** [comment]
@tmexcept You're welcome.
Do you need additional help or can this issue be closed?

**Comment by mrinvicto** [comment]
Try the solution specified in this blog post - [flutter sdk is not found in the specified location](https://ladwhocodes.blogspot.com/2019/02/fix-flutter-sdk-not-found-in-specified-location.html)

It worked well.

**Comment by exeptionerror** [comment]
All Possible Solution Added [[Solved] Flutter SDK is not found in the specified location in Android Studio](https://fluttercorner.com/flutter-sdk-is-not-found-in-the-specified-location-in-android-studio/)
