### ISSUE TITLE
flutter_driver times out when there's a CircularProgressIndicator with a fixed value

### ISSUE THREAD

**Issue by paolosoares** [flutter/flutter#18292]
I have a widget that shows a CircularProgressIndicator with a fixed value:

        new SizedBox(
          width: 64.0,
          height: 64.0,
          child: new CircularProgressIndicator(
            value: progressPercentage, // progressPercentage is never null
            strokeWidth: 8.0,
          ),
        );

Whenever I run a flutter_driver test that shows it, `waitUntilNoTransientCallbacks` times out. Could it be because it creates an `AnimationController` on repeat even when it shouldn't animate?

```
class _CircularProgressIndicatorState extends State<CircularProgressIndicator> with SingleTickerProviderStateMixin {
  AnimationController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new AnimationController(
      duration: const Duration(milliseconds: 6666),
      vsync: this,
    )..repeat();
  }

```

**Comment by chinmaygarde** [comment]
cc @Hixie

**Comment by matthewrice345** [comment]
This can also be reproduced coloring the style of the Progress Indicator which is pretty common. 

`CircularProgressIndicator(valueColor: AlwaysStoppedAnimation<Color>(Colors.white)`

As paolosoares mentioned it's a fixed value (stopped).

**Comment by pedromassangocode** [comment]
Hi @paolosoares 
Can you please confirm if you still experience this issue on latest Flutter?

Thank you.

**Comment by mark-apn** [comment]
I'm still experiencing this on the latest flutter.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by pedromassangocode** [comment]
Hi @mark-apn 
Can you please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
