### ISSUE TITLE
Clicking button widget causes crash on Linux

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#183]
<a href="https://github.com/nlacasse"><img src="https://avatars.githubusercontent.com/u/153325?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nlacasse](https://github.com/nlacasse)**
_Tuesday Oct 06, 2015 at 23:54 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1514_

----

I have a sky/flutter app with a button.  Clicking the button works fine on Android, and it used to work fine on Linux (desktop) as well.

However, the latest release of sky_engine breaks the button on Linux.  Clicking it yields:

```
[1006/163649:ERROR:dart_error.cc(16)] Unhandled exception:
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:211)
#1      _RenderInkWell._handleTap (packages/sky/src/widgets/ink_well.dart:180)
#2      TapGestureRecognizer.handlePrimaryPointer (packages/sky/src/gestures/tap.dart:27)
#3      PrimaryPointerGestureRecognizer.handleEvent (packages/sky/src/gestures/recognizer.dart:107)
#4      PointerRouter.route (packages/sky/src/gestures/pointer_router.dart:45)
#5      FlutterBinding.handleEvent (packages/sky/src/rendering/binding.dart:166)
#6      FlutterBinding.dispatchEvent (packages/sky/src/rendering/binding.dart:160)
#7      FlutterBinding._handlePointerEvent (packages/sky/src/rendering/binding.dart:145)
#8      FlutterBinding._handleEvent (packages/sky/src/rendering/binding.dart:98)
```

I'm running my app with `pub run sky_tools run_mojo` and in multiprocess mode.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/nlacasse"><img src="https://avatars.githubusercontent.com/u/153325?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nlacasse](https://github.com/nlacasse)**
_Tuesday Oct 06, 2015 at 23:57 GMT_

----

cc @afandria

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 00:03 GMT_

----

cc @abarth

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Wednesday Oct 07, 2015 at 00:49 GMT_

----

@j9brown

**Comment by abarth** [comment]
I believe this is fixed now.
