### ISSUE TITLE
ios build archive fails

### ISSUE THREAD

**Issue by katout** [flutter/flutter#18305]
I created an application and try to release build it, it's error .
and I tried it with the smallest project to reproduce it, but it was useless.

please help!

## How to

Terminal 
```
flutter create foober
cd foober
open pubspec.yaml
```

add text

```
shared_preferences: ^0.4.1
```
Terminal
```
flutter packages get
flutter build ios
open ios/Runner.xcodeproj
```

in xcode

```
SideBar -> Runner [click]
Signing -> Team [select my team]
Product -> Destination -> Generic iOS Device.
Product -> Archive
```
error log
```
ld: warning: directory not found for option '-L/Users/{Account}/Library/Developer/Xcode/DerivedData/Runner-dsaqpbxjbtkcgvdontanncvipuur/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/shared_preferences'
ld: library not found for -lshared_preferences
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
## flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.3-pre.11, on Mac OS X 10.13.4 17E202, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by katout** [comment]
If I don't use shared_preferences it will succeed

**Comment by chinmaygarde** [comment]
@cbracken: Could this be because a pod step failed?

**Comment by cbracken** [comment]
This sounds like `pod install` may have failed.

@katout, would you mind attaching the output of `flutter -v build ios`?

Assuming that fails, what happens if you run `flutter -v run` with an iOS device attached?

**Comment by katout** [comment]
Thank you for reply! @chinmaygarde and @cbracken.
I think so too. The cause is cocoapods.

## flutter -v build ios
[notConnect.txt](https://github.com/flutter/flutter/files/2086605/notConnect.txt)

## flutter -v run (with an iOS device attached)
this case, success!
[connect.txt](https://github.com/flutter/flutter/files/2086606/connect.txt)

## found a solution
1. open ios/Runner.xcodeproj
2. I checked Runner/Pods is empty in Xcode sidebar.
3. drop Pods/Pods.xcodeproj into Runner/Pods.
4. "Valid architectures" to only "arm64" (I removed armv7 armv7s) https://github.com/flutter/flutter/issues/13364

**Comment by cbracken** [comment]
@katout thanks for the update.

For what it's worth, as of the latest dev branch release, you *should* be able to safely set the architectures to the default value. Flutter should now be able to detect the change to the project and run the appropriate pod steps. I expect this should make it to the beta branch within a week.

Details of the Xcode changes at:
https://github.com/flutter/engine/wiki/iOS-Builds-Supporting-ARMv7

**Comment by raphaelcrv** [comment]
> I think so too. The cause is cocoapods.
> 
> ## flutter -v build ios
> [notConnect.txt](https://github.com/flutter/flutter/files/2086605/notConnect.txt)
> 
> ## flutter -v run (with an iOS device attached)

Solved! tks u really helped me !! :)

**Comment by raghaaavvvv** [comment]
I figured out the problem, all of the deployment targets need to be the same. That is, in the project file, the target, and the pods project as well.

**Comment by lockelost** [comment]
This is always reproducible.
I even created a new project, just pasting this dependency causes Archive problem.
Build for a physical device or Generic device works fine.

`dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  file_picker: ^1.4.0
  path_provider: ^1.3.0
  #url_launcher: ^5.1.4
  flutter_html: ^0.11.0
  admob_flutter: ^0.3.3
  photos_saver: ^0.0.2
  qrcode_reader: ^0.4.4
`

$ flutter --version

> Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 68587a0916 (2 months ago) • 2019-09-13 19:46:58 -0700
> Engine • revision b863200c37
> Tools • Dart 2.5.0

$ flutter doctor -v

> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en)
>     • Flutter version 1.9.1+hotfix.6 at /Users/brucewang/development/flutter
>     • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/brucewang/Library/Android/sdk/
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = /Users/brucewang/Library/Android/sdk/
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2.1, Build version 11B500
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Connected device (1 available)
>     • ???’s iPhone • ????? • ios • iOS 13.1.3
> 
> • No issues found!
>
