### ISSUE TITLE
Scrollbar thumb's size (length) on iOS calculation is always minimal on very long ListViews

### ISSUE THREAD

**Issue by kavu** [flutter/flutter#18308]
Hi! Excuse me, if I misunderstand some concepts or principles of Flutter, but I have a problem with `Scrollbar` thumb size on iOS. It is really small, almost unseen. As far as I understand `const double _kScrollbarMinLength = 4.0;` in `CupertinoScrollbar ` is causing this.

https://github.com/flutter/flutter/blob/b8c81e46a3a6c198441d43330efea8bad4cc8870/packages/flutter/lib/src/cupertino/scrollbar.dart#L14

It then passed to `ScrollbarPainter` and there is no chance to pass is as an option on `Scrollbar` creation.

https://github.com/flutter/flutter/blob/b8c81e46a3a6c198441d43330efea8bad4cc8870/packages/flutter/lib/src/cupertino/scrollbar.dart#L91

Below I am proving a minimal app, that can demonstrate it.

I didn't expect it will be so small. I think thumb height should be calculated with viewport height and not with real height of scrollable, which in case of really long lists can be really big.

Or we can add an option to pass parameters of `ScrollbarPainter` on `Scrollbar` creation. I'll gladly create a PR on it, if somebody guide me a little :)

Thanks!

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        title: 'Scrollbar Demo',
        home: new Scaffold(
          body: new Scrollbar(
              child: new ListView.builder(
                  itemCount: 2000,
                  itemBuilder: (ctx, index) => new ListTile(
                        title: new Text("Item $index"),
                      ))),
        ));
  }
}
```

## Logs

```
% flutter analyze
Analyzing scrollbar_demo...
No issues found! (ran in 2.4s)
```

```
[✓] Flutter (Channel dev, v0.5.2, on Mac OS X 10.13.3 17D47, locale en-RU)
    • Flutter version 0.5.2 at /usr/local/flutter
    • Framework revision 0a26ac0970 (2 days ago), 2018-06-06 15:28:20 -0700
    • Engine revision a83b37d35a
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/kavu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.24.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.13.2

[✓] Connected devices (1 available)
    • iPhone 8 • F5B27B42-98D1-4A1B-BE63-47355C66CCF6 • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by chinmaygarde** [comment]
cc @Hixie

**Comment by xster** [comment]
Looking at native behaviour, it seems like we should provide 2 minima, one from overscrolling which is 4px and one from being in a very long list which is a bit longer.

**Comment by kavu** [comment]
@xster I've made a little experiment about native iOS thumb sizes, and IMO overscroll thumb size should be more than 4px. Take a look:

<details>
<summary>Screenshot of Flutter overscroll, thumb is exactly the same as in long list. </summary>

![simulator screen shot - iphone 8 - 2018-06-09 at 13 33 32](https://user-images.githubusercontent.com/1994/41191684-ec757cb6-6bfb-11e8-8fb8-bfd1829f5fd2.png)

</details>

<p></p>

<details>
<summary>And here is overscroll thumb in native iOS, in simple demo app I made. </summary>

![simulator screen shot - iphone 8 - 2018-06-09 at 13 34 03](https://user-images.githubusercontent.com/1994/41191689-019f18e0-6bfc-11e8-8d20-117002520828.png)

</details>

<p></p>

As you can see native has thumb size somewhere around 6 or 8 px.

<details>
<summary>By the way, regular scroll thumb for a long list in native also iOS is not just "a bit longer" 😃  </summary>

![simulator screen shot - iphone 8 - 2018-06-09 at 13 38 44](https://user-images.githubusercontent.com/1994/41191719-437790e4-6bfc-11e8-9ae2-30976e6f6f44.png)
</details>

**Comment by nataliesampsell** [comment]
Closing, addressed in https://github.com/flutter/flutter/pull/20101.
