### ISSUE TITLE
ImageCache not clearing

### ISSUE THREAD

**Issue by goodis0** [flutter/flutter#18309]
Hello,

I have a list of items that each have an image stored on a server.  Instead of retrieving those images everytime I pull up the list I am using CacheNetworkImageProvider Widget to store them on the phone.  I am trying to program a button to clear the cache from the phone so it knows to go check for new images, but the 
`ImageCache.clear(), `
and 
`ImageCache.maximumSize = 0
ImageCache.maximumSize = 10000000`

both aren't clearing the image from the phone.  I can manually go into the phone settings > app > storage > clear data and it works but I want to be able to do it from inside of the app.

**Comment by jonahwilliams** [comment]
@goodis0 the `ImageCache` exposed in flutter is an in-memory cache, it doesn't write to disk.  It sounds like the `CacheNetworkImageProvider` is from a library which is handling writing to disk automatically.  In this case, I would ask on the library repo or check the documentation.

**Comment by goodis0** [comment]
I switched to NetworkImage and this worked perfectly, sorry for the delay in closing the issue

**Comment by jonahwilliams** [comment]
Glad you got it working!

**Comment by hariprasadiit** [comment]
I'm getting same problem again in `v0.9.4`. it worked in `v0.8.2`. I've tried setting 

```dart
PaintingBinding.instance.imageCache.maximumSizeBytes = 100 << 20;
PaintingBinding.instance.imageCache.maximumSize = 10;
```

it didn't help. also tried overriding `createImageCache()`.

**Comment by CatEatFishs** [comment]
ImageCache get imageCache => PaintingBinding.instance.imageCache;
imageCache.maximumSizeBytes=50<<20;
    imageCache.maximumSize = 100;
I use this method to clean up the cache " imageCache.clear()",but the cache still exists,  so i want to know How to clean the image cache?

**Comment by Xgamefactory** [comment]
same issue here with Image.file cacheing need to remove to display updated file afrer saved with same image name.

**Comment by MATTYGILO** [comment]
I'm having the same issue has anyone found a solution
