### ISSUE TITLE
The method 'validate' isn't defined for the class

### ISSUE THREAD

**Issue by iPatel007** [flutter/flutter#18304]
Actually i'm making demo app for learning purpose and following official document for create form and gives validation.

[Flutter official document for form and validation demo.](https://flutter.io/cookbook/forms/validation/)

Below is my code 

```dart
    import 'package:flutter/material.dart';    
    
    void main() => runApp(new HOPMeal());
    
    class HOPMeal extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return new MaterialApp(
          title: 'HOP Meal App',
          theme: new ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: new LoginScreen(),
        );
      }
    }
    
    class LoginScreen extends StatefulWidget {
      @override
      createState() => new LoginScreenState();
    }
    
    class LoginScreenState extends State<LoginScreen> {
      final GlobalKey<LoginScreenState> _formKey =
          new GlobalKey<LoginScreenState>();
      @override
      Widget build(BuildContext context) {
        return new Scaffold(
            appBar: new AppBar(
              title: new Text('Login'),
            ),
            body: new Center(
              child: createForm(),
            ));
      }
    
      Widget createForm() {
        return new Form(
          key: _formKey,
          child: new Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              new TextFormField(
                validator: (value) {
                  if (value.isEmpty) {
                    return 'Please enter some text';
                  }
                },
              ),
              new Padding(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                child: new RaisedButton(
                  onPressed: () {
                    if (_formKey.currentState.validate()) { // GETTING ERROR HERE
                      Scaffold.of(context).showSnackBar(
                          new SnackBar(content: new Text('Processing Data')));
                    }
                  },
                  child: new Text('Submit'),
                ),
              ),
            ],
          ),
        );
      }
    }
```

So there is no any **validate()** method in the [Website's Demo](https://flutter.io/cookbook/forms/validation/). Might be you forget to add this portion of code.
Update document that will be help for beginner developer like me.

**Comment by jickay** [comment]
Had the same problem. Turns out all you need is to use `GlobalKey<FormState>` and not the particular widget state (ie. LoginScreenState in your case). Wasn't entirely clear FormState is it's own thing!

**Comment by Sfshaza** [comment]
@brianegan

**Comment by brianegan** [comment]
Thanks @Sfshaza! Traveling to give a talk today, I'll try to patch it up tomorrow when I'm back.

**Comment by brianegan** [comment]
Hey all, I've posted some updates to this recipe to hopefully make it a bit more clear that ya need to use `GlobalKey<FormState>` rather than `GlobalKey<MyCustomFormState>`. Please let me know if you think that will help address the problem, or if it can be made more clear! 

https://github.com/flutter/website/pull/1078

**Comment by Sfshaza** [comment]
Thanks for fixing, @brianegan! Closing.

**Comment by talamaska** [comment]
I'm still getting the same error.

Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (6 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale bg-BG)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.30.1)
[√] Connected device (1 available)

error: The method 'validate' isn't defined for the class 'State<StatefulWidget>'. (undefined_method at [wishmate_flutter_ui] lib\screens\home_page.dart:67)
```
import 'package:flutter/material.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        backgroundColor: Colors.deepPurple.shade700,
      ),
      body: Center(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextFormField(
                // The validator receives the text the user has typed in
                validator: (String value) {
                  if (value.isEmpty) {
                    return 'Please enter some text';
                  }
                },
              ),

              Padding(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                child: RaisedButton(
                  child: const Text('Submit'),
                  onPressed: () {
                    debugPrint('state ${_formKey.currentState.validate()}');
                    if (_formKey.currentState.validate()) { <-- getting error here.
                     print('form is valid')
                    }
                  },
                ),
              ),

            ],
          ),
        )
      ),
    );
  }

}


```

**Comment by rajilesh** [comment]
FormState form = _formKey.currentState;
form.save();

worked for me

**Comment by galhi** [comment]
final GlobalKey _formKey = GlobalKey<FormState>();

remove the GlobalKey type
 final _formKey = GlobalKey<FormState>();

^ use like this

**Comment by glhrmv** [comment]
```dart
final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
```

This works, and it has the type annotation in case you're using `always_specify_types`.

**Comment by lazarvgd** [comment]
> final GlobalKey _formKey = GlobalKey();
> 
> remove the GlobalKey type
> final _formKey = GlobalKey();
> 
> ^ use like this

Can you please explain why is this happening?
