### ISSUE TITLE
SharedPreferences does not actually get written to disk

### ISSUE THREAD

**Issue by GroovinChip** [flutter/flutter#18307]
Hello! I am cloning my app Call Manager in Flutter and I am having a problem with the SharedPreferences plugin. The SharedPreferences never actually get written to storage, so they do not persist after the app is closed. Interestingly, the contents of the sharedpreferences are available during runtime in memory, but it still never gets written to storage

Using the deprecated `commit()` method does not solve the issue

## Steps to Reproduce

```
`@override
  void initState() {
    super.initState();
    print("InitState");
    initCalls();
  }

  initCalls() async {
    await loadCallsFromLocalStorage();
    await saveGlobalListToLocalStorage();
  }

  Future<Null> loadCallsFromLocalStorage() async{
    SharedPreferences callStorage = await SharedPreferences.getInstance();
    String listFromStorage = callStorage.getString("callStorage");
    calls = json.decode(listFromStorage);
  }

  void saveGlobalListToLocalStorage() async {
    SharedPreferences callStorage = await SharedPreferences.getInstance();
    String listOfCalls = json.encode(globals.callsInApplicationState);
    await callStorage.setString("callStorage", listOfCalls);
  }`
```

**Comment by GroovinChip** [comment]
`C:\flutter\bin\flutter.bat --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
[√] Android Studio (version 3.1)
[√] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected devices (1 available)

• No issues found!
Process finished with exit code 0`

**Comment by GroovinChip** [comment]
Does anyone know what might be going on?

**Comment by One-djey** [comment]
What's the solution ?

**Comment by juanlatorre** [comment]
Did it has a solution ?

**Comment by xni06** [comment]
I'm getting the same problem

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
```
