### ISSUE TITLE
Flutter build (release) does not fail on "Compiler terminated unexpectedly

### ISSUE THREAD

**Issue by pboos** [flutter/flutter#18301]
Flutter: Channel beta, v0.4.4

### Problem
`flutter build apk --release` does not fail if there is an compiler error (like a file missing)
`flutter build apk --debug` correctly fails during the build. So it is only with `--release`.

### Details:
I forgot to check in a file `lib/widget/messaging.dart`.

Then the build server ran: `flutter build apk --release`
The build completed successfully. The apk was only 8.3MB though instead of 11.5MB. And the app crashed right when opening with a native crash.

The build server shows the following:
```
compiler message: lib/widget/messaging.dart: Error: No such file or directory
Compiler terminated unexpectedly.
Contents of .packages:
# Generated by pub on 2018-06-08 08:28:24.078157.
```

I would expect the command to stop at `Compiler terminated unexpectedly.` and fail. But it seems like the flutter build ignores it and just continues.

When I tried locally with `--debug` the build correctly stopped. But not when i did `--release`.

**Comment by zoechi** [comment]
Dup of #18200 ?

**Comment by pboos** [comment]
True, didn't find that one in my search. Will close this one and provide the information above in that issue.
