### ISSUE TITLE
Widget Catalog should be updated to include new widgets

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#18319]
`OutlineButton` and other widgets aren't very discoverable because of that.

The Widget Catalog is also probably missing other material widgets, since apparenly it hasn't been updated. (https://flutter.io/widgets/material/)

**Comment by chinmaygarde** [comment]
I don't think all widgets are currently in the catalog. cc @HansMuller, @Hixie

**Comment by jagdishjadeja** [comment]
so how to add there ?

**Comment by HansMuller** [comment]
The outline button is included in the Flutter Gallery app, under "buttons"

**Comment by gabrc52** [comment]
@jagdishjadeja it can be added to https://github.com/flutter/website/ 

@HansMuller it's not that discoverable since the Flutter Gallery app is made to showcase what Flutter can do and shouldn't be where developers get documentation

**Comment by timsneath** [comment]
Moved this issue to the website issue tracker. Thanks for raising it!
