### ISSUE TITLE
FirebaseAuthPlugin: Error codes are not forwarded to Dart

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#18312]
Hi,

I just found out that if an error happens on the FirebaseAuth side like "email already used" I will only get an 

```Dart
      throw new PlatformException(code: errorCode, message: errorMessage, details: errorDetails);
```
with errorCode = "exception" and an error message that isn't localized which isn't really helpful.

Looking at the Java side of the plugin made it obvious

```Java
 private class SignInCompleteListener implements OnCompleteListener<AuthResult> {
    private final Result result;

    SignInCompleteListener(Result result) {
      this.result = result;
    }

    @Override
    public void onComplete(@NonNull Task<AuthResult> task) {
      if (!task.isSuccessful()) {
        Exception e = task.getException();
        result.error(ERROR_REASON_EXCEPTION, e.getMessage(), null);
      } else {
        FirebaseUser user = task.getResult().getUser();
        ImmutableMap<String, Object> userMap = mapFromUser(user);
        result.success(userMap);
      }
    }
  }

This should actually be a [FirebaseAuthException](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthException)

which has a `GetErrorCode` method. Please change that so that Apps can react on error conditions with their own texts.

**Comment by timsneath** [comment]
Good catch - thanks, @escamoteur. Adding @collinjackson.

**Comment by zoechi** [comment]
Similar to #13027

**Comment by escamoteur** [comment]
Difference is that for FirebaseAuth you get an exception on the Dart side but no error code

**Comment by twpochuan** [comment]
After removing the 'google_sign_in' from dependencies, the error codes came back. 
It seems something goes wrong or override the exception when 'google_sign_in' is added into the dependencies.

**Comment by eseidelGoogle** [comment]
This looks like a quick fix.  @bparrishMines or @kroikie may be interested.

**Comment by MateusPalomo** [comment]
If you encounter something like below, 
this is because there is an extra spacing at the end of your email.

Try delete extra spacing,

**Comment by kroikie** [comment]
@escamoteur

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/802. Any further collaboration will be done there.

**Comment by reinaldobrazpereira** [comment]
Obrigado MateusPalomo.
Era um espaço extra mesmo, e fiquei algum tempo em cima deste erro.
Abraço.

**Comment by VisheshAtWork** [comment]
Same issue. Any work around ?

**Comment by KristianBalaj** [comment]
Still an issue.

**Comment by folivi** [comment]
Hi all,
Has this been fixed? Tried calling createUserWithEmailAndPassword inside a try catch block both handling platformException and FirebaseAuthException but the app litterally crashes when an on the email-exists error

**Comment by escamoteur** [comment]
please report here: https://github.com/FirebaseExtended/flutterfire/issues/802

**Comment by escamoteur** [comment]
@kroikie unfortunately the other thread got locked which I find pretty strange if this isn't fixed yet. I am pretty sure there was a PR with this fix from @slightfoot a long time ago

**Comment by slightfoot** [comment]
I did fix this. But the FlutterFire migration work changed the error codes to the web sdk ones. Either way it could be a platform specific regression. @salakar would know.

**Comment by Salakar** [comment]
cc @ehesp

**Comment by muhammadsqln** [comment]
How is this still fixed

**Comment by escamoteur** [comment]
@muhammadsqln does it still not work?

**Comment by muhammadsqln** [comment]
@escamoteur My apologies. I was testing against an older version. Latest is working fine.

**Comment by EriKWDev** [comment]
This is still a problem.. I'm following the very basic usage tutorial code on https://firebase.flutter.dev/docs/auth/usage but PlatformException is thrown and not catched in debug mode on VSCode which makes debugging basically unbearable. I'm not using google_sign_in

**Comment by escamoteur** [comment]
What do you mean by that VS code isn't catching the PlatformException? did you enable break on all exceptions?

**Comment by EriKWDev** [comment]
Sorry, I meant the opposite xP I don't want VSCode to stop on PlatformException but it goeas ahead and does it anyway... I'm running the code 
```dart
UserCredential userCredential;

try {
  userCredential = await FirebaseAuth.instance.signInWithEmailAndPassword(email: email, password: password);
} on FirebaseAuthException catch (e) {
  if (e.code == 'user-not-found') {
    print('No user found for that email.');
  } else if (e.code == 'wrong-password') {
    print('Wrong password provided for that user.');
  }
} on PlatformException catch(e) {
  print(e);
}
```
on an Android emulator from VSCode debug mode. I have "Break on All Exceptions" turned off, but when the code is called the debugger stops anyway on `PlatformException` from message_codecs.dart 

![image](https://user-images.githubusercontent.com/19771356/105488714-5aaaa900-5cb2-11eb-989e-cb0f8a47051a.png)
![image](https://user-images.githubusercontent.com/19771356/105488735-626a4d80-5cb2-11eb-9c0e-689f648f23b8.png)

**Comment by Ehesp** [comment]
Please create new issues on the FlutterFire repo so maintainers have visibility. This will not be seen/addressed here.

**Comment by escamoteur** [comment]
if you hit continue it does not get caught int your 'on PlatformException'?

**Comment by EriKWDev** [comment]
> Please create new issues on the FlutterFire repo so maintainers have visibility. This will not be seen/addressed here.

Will do!

**Comment by EriKWDev** [comment]
> if you hit continue it does not get caught int your 'on PlatformException'?

No, it doesn't.
