### ISSUE TITLE
FirebaseStorage no way to check if a StorageReference "exists"

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#18315]
When I have a `StorageReference` I have no way to check if it actually exists on the server. This also means that any calls like `reference.getData()` `getDownloadUrl()` etc. will throw exceptions on the native part of the plugin, which makes it impossible for me to handle the situation.

**Comment by chinmaygarde** [comment]
cc @collinjackson

**Comment by eturk1** [comment]
Just stumbled on issue with exceptions myself. Found several open issues but seems several months since anyone has addressed the issue. 

Honest question: Should we be avoiding Firebase? I also get a lot of compile warnings.

**Comment by creativecreatorormaybenot** [comment]
This is not possible in any of the native libraries, so there is no reasonable way to add this to the Flutter plugin.

 * https://stackoverflow.com/q/43567626/6509751

 * https://stackoverflow.com/q/37751202/6509751

 * https://stackoverflow.com/q/38184900/6509751

*Catching errors* works fine as a solution.

**Comment by kroikie** [comment]
@creativecreatorormaybenot

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/801. Any further collaboration will be done there.
