### ISSUE TITLE
Open google play and play store from app

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#18326]
Hi is possible open from my app the google play app and play store app positioned in the page of my app?
How can i do it?

Thanks

**Comment by MaskyS** [comment]
@romaluca , please use http://github.com/Purus/launch_review It has examples as well.

**Comment by Kartik1607** [comment]
Hi. To do so you will need to add android_intent plugin. Check it out [here](https://pub.dartlang.org/packages/android_intent)

**Comment by zoechi** [comment]
@romaluca could you make it work using the suggestions?

**Comment by romaluca** [comment]
I used url launcher plugin and it works. Thanks

**Comment by zoechi** [comment]
@Hixie seems there is something wrong with the no-response bot.

![image](https://user-images.githubusercontent.com/405837/41285961-35c8b074-6e3e-11e8-86a3-20df74a689f7.png)

**Comment by Nawsher-Ali** [comment]
Install the package

After creating a new flutter document move to pubspec.yaml file

Find Dependencies and then add the package name.

Note: you should add under cupertino_icons: ^0.1.2

Dependencies:

Launch_review: ^1.0.1
Tap Package get at right corner.

Import the package

Import the package under basic package

import ‘package:launch_review/launch_review.dart’;
Id’s for opening app store page

AndroidAppId: “com.iyaffle.rangoli”
iOSAppId: “585027354”
Create initstate

class _MyAppState extends State<MyApp> {

 @override

 initState() {

   super.initState();
Launch Review

For button

body: new Center(

child: new RaisedButton(

child: new Text("Rate App"),

onPressed: () {

LaunchReview.launch(

androidAppId: "com.iyaffle.rangoli",

iOSAppId: "585027354");

}

), 

),

**Comment by moonyoungCHAE** [comment]
You can use this plug in. [here](https://pub.dev/packages/open_appstore#-readme-tab-)

Super simple.
To use this pulg in, just write the package name (app id) on your dart code like this.
```
OpenAppstore.launch(androidAppId: "com.facebook.katana&hl=ko", iOSAppId: "284882215")
```

**Comment by appstute-pratik** [comment]
I used [url_launcher](https://pub.dev/packages/url_launcher) library.
This worked for me:
`launch("market://details?id=<Package name>");`.

**Comment by NiyatiKhandelwal-99** [comment]
https://github.com/flutter/flutter/issues/18326#issuecomment-588620293
This works! What is the equivalent for directing to the iOS app store?
