### ISSUE TITLE
getting started instructions and android

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1832]
Our getting started instructions (for the mac) say to use `brew install android-platform-tools`. But it looks like this will only install `adb`. I think w/ the changes to our workflow re: building apks and running, adb isn't sufficient. We always (virtually always?) require the android sdk, in order to get the build-tools.

brew also has a `android-sdk` distro. However, after installation the user need to run an app (`android`) to configure and download the rest of the sdk (build-tools, platform-tools).

Not clear if we should keep recommending `brew install android-platform-tools` or another install which will require a lot more configuration on the user's part.

**Comment by devoncarew** [comment]
(sdk tools-only download available here: http://developer.android.com/intl/es/sdk/index.html#Other)

**Comment by devoncarew** [comment]
@qchong, I think we're going to need to update the getting started page to remove references to the brew step to install adb. We'll need the full android sdk. This could be a good page to point people to: https://developer.android.com/intl/es/sdk/installing/index.html?pkg=tools. I have a bit more work to do, but I'm going to try and make it so that users don't need to set an env variable.

**Comment by qchong** [comment]
Fixed by adding instructions for Android setup in the [Flutter Setup](https://flutter.io/setup/#android-setup) page, based on content shared by abarth@.

**Comment by qchong** [comment]
Marking as closed.
