### ISSUE TITLE
If one child of a container layer needs_system_composite, all its siblings needs_system_composite.

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#18320]
Otherwise, the siblings that do not needs_system_composite could be incorrectly occluded by the child that needs_system_composite. More specifically, if one child acquires a vulkan surface (needs_system_composite), all the siblings need to acquire vulkan surfaces as well.

To see the bug, enable PerformanceOverlayLayer (which currently does not needs_system_composite) in Fuchsia with a Flutter app that has a PhysicalShapeLayer (which needs_system_composite) as a child of the root_layer_. The PerformanceOverlayLayer is completely occluded.

**Comment by tvolkert** [comment]
What's the visible manifestation of this bug?

**Comment by liyuqian** [comment]
@tvolkert : See the second paragraph of https://github.com/flutter/flutter/issues/18320#issue-330832233 . I haven't tried it in the last year so I'm not sure whether it's still reproducible.
> To see the bug, enable PerformanceOverlayLayer (which currently does not needs_system_composite) in Fuchsia with a Flutter app that has a PhysicalShapeLayer (which needs_system_composite) as a child of the root_layer_. The PerformanceOverlayLayer is completely occluded.

**Comment by tvolkert** [comment]
@liyuqian since it's 18 months old, can you see if it's still relevant?

**Comment by liyuqian** [comment]
Sure, I'll try to reproduce it once I get back to my desk and have access to the Fuchsia machine. Adding this to my TODO list.

**Comment by jonahwilliams** [comment]
Fixing this is not important.
