### ISSUE TITLE
Error not caught on cancelling google sign in

### ISSUE THREAD

**Issue by nikhilag** [flutter/flutter#18338]
I am using the latest packages with google_sign_in version 3.0.4 and flutter version 0.4.4. The following code doesn't catch sign_in_failed error when I dismiss the google sign in dialog and I get a PlatformException.
```
try {
      googleUser = await _googleSignIn.signIn();
    } catch (error) {
      googleUser = null;
      print(error);
    }
```
Is there some mistake in my code or is it a bug in the package?

**Comment by zoechi** [comment]
related to #17677, #16989

**Comment by zoechi** [comment]
Closing as dup of #17677

**Comment by benjaminhorner** [comment]
I am confused as to why this has been closed as the issue remains in google_sign_in version 3.2.4…

**Comment by zoechi** [comment]
@benjaminhorner  #17677 is still open. This is closed as duplicate

**Comment by remosingh** [comment]
#17677 is totally unrelated. I have having the same issue where when pressing cancel button in google sign in window, an error is thrown.

**Comment by sensuikan1973** [comment]
I have the same issue..

**Comment by sensuikan1973** [comment]
By https://github.com/flutter/plugins/pull/1937 , this problem fixed 👍

**Comment by maheshmnj** [comment]
> By [flutter/plugins#1937](https://github.com/flutter/plugins/pull/1937) , this problem fixed

I can still see the error on v4.1.1 of google_sigin_in
