### ISSUE TITLE
Issue from website page Fade in images with a placeholder

### ISSUE THREAD

**Issue by swashcap** [flutter/flutter#18333]
From URL: https://flutter.io/cookbook/images/fading-in-images/

> You can also consider using local assets for placeholders by following the [Assets and Images](https://flutter.io/assets-and-images/) guide.

Unfortunately, that guide doesn't contain any info on using a bundled image as a placeholder. Digging through the API docs doesn't yield any info on converting an `AssetImage` to `FadeInImage.memoryNetwork`’s `placeholder` type, a `Uint8List`. Any thoughts?

**Comment by Kartik1607** [comment]
FadeInImage have a constructor for loading placeholder from asset bundle. You would need to use `FadeInImage.assetNetwork` . You can find the documentation [here](https://docs.flutter.io/flutter/widgets/FadeInImage-class.html)

**Comment by swashcap** [comment]
> FadeInImage.assetNetwork(/* ... */)
> Creates a widget that uses a placeholder image stored in an asset bundle while loading the final image from the network. [...]

Ah, thanks! This looks like it would work. Can we update the documentation with an example?

**Comment by zoechi** [comment]
@Hixie

**Comment by swashcap** [comment]
Looks like docs are in a separate repo. Created flutter/website#1064 as a start for this.
