### ISSUE TITLE
How do I close my app without call exit(0)

### ISSUE THREAD

**Issue by superciccio** [flutter/flutter#18331]
Hi,

I'm currently developing an app, and from the homepage when back button is pressed I'm calling exit(0) (captured by WillPopScope) which does what it should (everything is fine).

If I then reopen the app the startup is cold startup, not warm.

What's the best to 'close' an app in flutter, I mean how can I send it in background ?

If I don't call exit I got a black screen .

Thanks in advance

PS
Is there any official roadmap for future beta/release ? :)

**Comment by zoechi** [comment]
Does this also happen with a new project that you create with `flutter create`?
I think this is related how you use routes. 

> Is there any official roadmap for future beta/release ? :)

I don't think there is a roadmap. The milestones should give some clue about priorities.

**Comment by superciccio** [comment]
this issue can be closed as I solved this issue :)
Found the problem, I was checking the authentication in the wrong place...

**Comment by lsaudon** [comment]
Solution for iOS ?

**Comment by Mostafa-SA-developer** [comment]
> Solution for iOS ?

SystemChannels.platform.invokeMethod('SystemNavigator.pop');

read the [doc](https://api.flutter.dev/flutter/services/SystemNavigator/pop.html)

**Comment by patelkrunal78** [comment]
Preferable solution is:

SystemChannels.platform.invokeMethod('SystemNavigator.pop');
As described [here](https://icetutor.com/question/flutter-how-to-programmatically-exit-the-app/)

**Comment by bambinoua** [comment]
> > Solution for iOS ?
> 
> SystemChannels.platform.invokeMethod('SystemNavigator.pop');

Did you see the content of SystemNavigator.pop() method? It is the same as you wrote. So why do you wrote this if it **does not work** under iOS?

**Comment by imaNNeoFighT** [comment]
> > Solution for iOS ?
> 
> SystemChannels.platform.invokeMethod('SystemNavigator.pop');
> 
> read the [doc](https://api.flutter.dev/flutter/services/SystemNavigator/pop.html)
It doesn't work

**Comment by LaxmikanthMadhyastha** [comment]
i tried using SystemChannels.platform.invokeMethod('SystemNavigator.pop'); to close the app and it is working fine on android but not working on IOS

**Comment by berkaycapar** [comment]
please clearly help

**Comment by Raghav-Bajaj** [comment]
exit(0);
with dart.io
