### ISSUE TITLE
Query firebase

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#18346]
No type of query works on firebase, and shows no error.

> flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
Can you please provide more information about how to reproduce?
Are you using Firebase realtime database or Firestore?
What code did you use to test?

**Comment by giovannilima262** [comment]
started working again, and 
I do not know
