### ISSUE TITLE
Flutter gallery shows a status bar with black text and icons when opened on iOS

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#18344]
Using:
Channel beta, v0.4.4, on Mac OS X 10.13.3 17D102, locale en-MX
iPad, iOS 11.1.2

**Comment by HansMuller** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
This may have been broken with some previous changes that prevent system chrome updates from being called from the non-active routes.

Ideally once https://github.com/flutter/flutter/pull/17672 is in we can update the gallery to be deterministic

**Comment by jonahwilliams** [comment]
Fixed in https://github.com/flutter/flutter/pull/18735
