### ISSUE TITLE
Disable default Google Auth Account

### ISSUE THREAD

**Issue by YourFavouriteOreo** [flutter/flutter#18355]
I am using the `google_sign_in` package and `firebase_auth`. However, I realized whenever I press the raised button for "Sign In With Google" as I want to use google auth. After the first login, it defaults to one account whenever you press Sign In. Any way to disable that?

**Comment by zoechi** [comment]
Not sure what you ask for.
You don't want the app to automatically re-login with the previously used account?

**Comment by YourFavouriteOreo** [comment]
Yup. In case à user wants to use a different Google account on the same
device.

**Comment by zoechi** [comment]
In my app I offered a logout option, then calling login asks to select an account again.

You might also be looking for https://firebase.google.com/docs/auth/web/auth-state-persistence. I haven't found support for that in the firebase_auth or google_sign_in packages

**Comment by zoechi** [comment]
@Hixie

**Comment by YourFavouriteOreo** [comment]
Using what you said here:

> In my app I offered a logout option, then calling login asks to select an account again.

I found a work around by simply signing out before beginning the sign in process. 

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

final FirebaseAuth auth = FirebaseAuth.instance;
final GoogleSignIn googleSignIn = new GoogleSignIn();

Future < String > _testSignInWithGoogle() async {
  auth.signOut();
  GoogleSignInAccount googleUser = await googleSignIn.signIn();
  print(googleUser);
  GoogleSignInAuthentication googleAuth = await googleUser.authentication;
  FirebaseUser user = await auth.signInWithGoogle(
    accessToken: googleAuth.accessToken,
    idToken: googleAuth.idToken
  );

  assert(user.email != null);
  assert(user.displayName != null);

  print('This user is signed in $user');
  return 'signInWithGooggle succeeded: $user';
}
```

**Comment by zoechi** [comment]
I always sign out both Google SignIn and Firebase.
Ok, sounds you are unblocked. 
We can leave this as feature request for the auth plugins.

**Comment by YourFavouriteOreo** [comment]
I don't have log out implemented yet. However I will definitely do that
once I do

**Comment by kroikie** [comment]
@YourFavouriteOreo

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/798. Any further collaboration will be done there.

**Comment by PratikJH153** [comment]
> I am using the `google_sign_in` package and `firebase_auth`. However, I realized whenever I press the raised button for "Sign In With Google" as I want to use google auth. After the first login, it defaults to one account whenever you press Sign In. Any way to disable that?

Hey, I guess this works: Just before this line (while signing)  [GoogleSignInAccount googleUser = await googleSignIn.signIn();]
Add: googleSignIn.disconnect();

I hope this works..

**Comment by jagadishnallappa** [comment]
> Using what you said here:
> 
> > In my app I offered a logout option, then calling login asks to select an account again.
> 
> I found a work around by simply signing out before beginning the sign in process.
> 
> ```dart
> import 'package:firebase_auth/firebase_auth.dart';
> import 'package:google_sign_in/google_sign_in.dart';
> 
> final FirebaseAuth auth = FirebaseAuth.instance;
> final GoogleSignIn googleSignIn = new GoogleSignIn();
> 
> Future < String > _testSignInWithGoogle() async {
>   await googleSignIn.signOut();
>   GoogleSignInAccount googleUser = await googleSignIn.signIn();
>   print(googleUser);
>   GoogleSignInAuthentication googleAuth = await googleUser.authentication;
>   FirebaseUser user = await auth.signInWithGoogle(
>     accessToken: googleAuth.accessToken,
>     idToken: googleAuth.idToken
>   );
> 
>   assert(user.email != null);
>   assert(user.displayName != null);
> 
>   print('This user is signed in $user');
>   return 'signInWithGooggle succeeded: $user';
> }
> ```
> 
> However this does not seem like a "clean" solution .
> 
> EDIT: Auth Sign Out works only once and GoogleSignIn signout works repeatedly.

This should be the accepted solution. Though google.signIn.disconnect(); also works, it fails to open sign in pop up again upon click of sign in button.
