### ISSUE TITLE
Flexible.crossAxisAlignment to position each child independently

### ISSUE THREAD

**Issue by sushoucanyuan** [flutter/flutter#18356]
Just like the align-self property in CSS

**Comment by zoechi** [comment]
Why do you think that?
Flutter is built from light-weight widgets that do a single thing and do it well.
It should be easy to create a custom widget that does more than one thing at once.

**Comment by sushoucanyuan** [comment]
For example, i have three items in a row like this
![tim 20180611193532](https://user-images.githubusercontent.com/24253664/41229640-5360eac8-6daf-11e8-923f-e5730cd0dfde.png)
Now they're all in the middle.
I think it will be easy to only put the first one on top and put the third one on bottom if i can set crossAxisAlignment property in these items.

**Comment by zoechi** [comment]
What about wrapping them in a https://docs.flutter.io/flutter/widgets/Flex-class.html and set `crossAxisAlignment` there ? (haven't tried myself)

**Comment by sushoucanyuan** [comment]
The `crossAxisAlignment` of Flex is used to set the position of all children, I mean I want to be able to set the position of one child.

**Comment by zoechi** [comment]
I don't have deep knowledge here and don't have time to experiment. 
I'll leave it to @Hixie

**Comment by sushoucanyuan** [comment]
OK, thank you for answering~

**Comment by Hixie** [comment]
You can use `CrossAxisAlignment.stretch` and then place each individual child using `Align`, does that work for you?

**Comment by goderbauer** [comment]
Sounds like this got resolved. I am closing this for now. Please feel free to reopen with additional information if there's more to it.

**Comment by sunyatax** [comment]
The example above is for a Row widget - any insight into how to perform this with a Column widget? I'm trying to independently position a child of a Column widget and Align doesn't work. The Column is nested within a Container widget that has a minHeight constrain.
