### ISSUE TITLE
Hot reloading doesn't work fine with fonts

### ISSUE THREAD

**Issue by cronos88** [flutter/flutter#18364]
[SOLVED] Flutter version: 0.4.4 beta 3
SO: Linux Elementary OS (latest version)
Plugin flutter: Last version on VSC and IntelliJ

In Pubspec.yaml file I set a new font, with font family, style, etc. While app is running, when I change the new font family in the theme ( in MaterialApp), and hot reloading, doesn't change font on my phone. I have stop and restart debug, so that changes new font in screen.

**Comment by zoechi** [comment]
@Hixie

**Comment by Hixie** [comment]
Can you clarify whether you mean that you are changing the `pubspec.yaml` and hot reloading, or whether you are only changing the font family in the theme?

**Comment by Hixie** [comment]
cc @gspencergoog @cbracken @jason-simmons

**Comment by cronos88** [comment]
@hixie When I change font-family in the theme.

**Comment by Hixie** [comment]
Weird. Does it work if you hot restart? (`R` instead of `r`)

**Comment by cronos88** [comment]
Hi @hixie, sorry for answer too late. I was install Lubuntu on my laptop and now hot reloading for fonts working fine. I haven't this issue in this Linux distro. Thanks for you help.

**Comment by zoechi** [comment]
@cronos88 should this issue be closed or do you think there is stll something to do?

**Comment by cronos88** [comment]
@zoechi, you can close this issue. Thanks!!!
