### ISSUE TITLE
he following assertion was thrown while handling a gesture: flutter: type '_BroadcastSubscription<Location>' is not a subtype of type 'StreamSubscription<Null>'

### ISSUE THREAD

**Issue by HieuTranTrung1204** [flutter/flutter#18365]
Log error: 
https://gist.github.com/HieuTranTrung1204/18783bd6c75e3a9edd30cd9dbfa242fc

**Comment by HieuTranTrung1204** [comment]
Syncing files to device iPhone X...
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: type '_BroadcastSubscription<Location>' is not a subtype of type 'StreamSubscription<Null>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _MyAppState.showMap (file:///Volumes/DATA/Projects/Training/TrainingFlutter/lib/main.dart:132:10)
flutter: #1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
flutter: #2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
flutter: #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
flutter: #5      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
flutter: #6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
flutter: #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
flutter: #14     _invoke1 (dart:ui/hooks.dart:134:13)
flutter: #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
flutter:
flutter: Handler: onTap
flutter: Recognizer:
flutter:   TapGestureRecognizer#a2399(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
flutter:   Offset(198.0, 286.3), sent tap down)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Location updated Location{latitude: 37.785834, longitude: -122.406417}
Google Maps SDK for iOS version: 2.6.30421.0
New version of Google Maps SDK for iOS available: 2.7.30514.0
	[1.1 31784E60-48F9-470F-BEA1-8DD6E2A60DAC 2405:4800:5287:37f:3c8f:3e8d:9d9f:3cc7.61253<->2404:6800:4005:80c::200e.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 1.088s, DNS @0.015s took 0.002s, TCP @0.021s took 0.086s, TLS took 0.476s
	bytes in/out: 4083/720, packets in/out: 9/9, rtt: 0.088s, retransmitted packets: 0, out-of-order packets: 0

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`
How can this be reproduced?

**Comment by HieuTranTrung1204** [comment]
Thanks your reply 👍  
Output flutter doctor: 
Trans-MacBook-Pro-2:Flutter trunghieutran$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.2-pre.72, on Mac OS X 10.13.4 17E202, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.24.0)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Trans-MacBook-Pro-2:Flutter trunghieutran$ 

I use map view 
log error when showmap 
Code here: https://gist.github.com/HieuTranTrung1204/7f46825778a34b87aaa0998fa3f07fac

**Comment by matanlurey** [comment]
@HieuTranTrung1204  The following is not valid:

https://gist.github.com/HieuTranTrung1204/7f46825778a34b87aaa0998fa3f07fac#file-demo-map-L115-L152

Your first assignment infers a `StreamSubscription<Location>`:
https://gist.github.com/HieuTranTrung1204/7f46825778a34b87aaa0998fa3f07fac#file-demo-map-L115

While subsequent ones may be of another type.

My recommendation is to either avoid the `sub =` allocation entirely (it doesn't _do_ anything):

```dart
compositeSubscription.add(
  mapView.onLocationUpdated
        .listen((location) => print("Location updated $location"))
);
```

_Or_, explicitly type `sub` as something like `StreamSubscription<void>`:

```dart
StreamSubscription<void> sub =

...

sub =
```

... since `void` can effectively be anything.

**Comment by matanlurey** [comment]
(Sort of unrelated, I don't think `CompositeSubscription` helps much more than a `List` here)
