### ISSUE TITLE
Is there a way to call a custom javascript function in a flutter app.

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#18367]
eg. I have a custom javascript function in a  .js file
```
function myFunction(x, y) {
   return x + y;
}
```

and in my flutter app i want to do something like this. 
```
class TestSample extends StatelessWidget{
    @override
    Widget build(BuildContext context) {
       var result =  js.myFunc(10, 20);
         var widget = new MaterialApp(
                home: new Scaffold(
                    body: new Center( 
                        child: new Text(result),
                    )
                ),
            );
            return widget;
        }
}
```

**Comment by zoechi** [comment]
Flutter doesn't use JavaScript.
```
Future<String> evalJavascript(String code);
```
(see end of https://github.com/dart-flitter/flutter_webview_plugin/blob/172c27c5e2003e55dfaa65e33721a0627bff13b7/README.md)
might do what you need.

I tentatively close this issue. 
Just add a comment if you think the issue should be reopened.

**Comment by manujbahl** [comment]
So this will need me to instantiate a webview widget in the page. Can we not do something with the https://pub.dartlang.org/packages/js

**Comment by zoechi** [comment]
@manujbahl no, package:js only runs in the browser. Dart also only compiles to JS for browser apps, in Flutter it compiles to machine code.

**Comment by manujbahl** [comment]
OK ..  So i tried the following code 
```
        final flutterWebviewPlugin = new FlutterWebviewPlugin();  
        var code = "function myFunction(x, y) { return x + y;}  return myFunction(2, 3);";
        await flutterWebviewPlugin.launch("http://www.cnn.com", withJavascript: true, hidden: true);
        var ret = await flutterWebviewPlugin.evalJavascript(code);
```

and when i did into the error on the channel i see the following error out of the webview evaluateJavaScript call
error	NSError *	domain: @"WKErrorDomain" - code: 4	0x00006000002528d0

Any ideas ?

**Comment by zoechi** [comment]
@manujbahl Sorry, I think I can't help here.
I'd suggest to create an issue in https://github.com/dart-flitter/flutter_webview_plugin/issues.
Please add the output of `flutter doctor` and the FlutterWebviewPlugin version from `pubspec.lock` there.

**Comment by zoechi** [comment]
move to dart-flitter/flutter_webview_plugin#96

**Comment by heinzan** [comment]
@manujbahl  bro did you get any solutions?
