### ISSUE TITLE
complex_layout_scroll_perf__timeline_summary worst_frame_build_time_millis gets slower

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#18378]
Please see the plot in our performance benchmark dashboard. The time first jumped from ~23 ms to ~31ms in 57187b00b2172e7c3e394319764ec95032a0c97f, and then it further jumped from ~31ms to ~41ms around 326caa5d22e01637f3612a2c73960aee01a8e75c

**Comment by liyuqian** [comment]
CC @a-siva @Hixie @HansMuller

**Comment by jason-simmons** [comment]
I can reproduce this reliably on a Moto G4.

It appears to be associated with https://github.com/dart-lang/sdk/commit/0bec11a4f27ea49d09694ef6e008ad2e6db7a3d7

Note that the regression is in the worst build time across all frames in the benchmark.  I didn't notice a significant effect on the average build time.

@zanderso

**Comment by zanderso** [comment]
It is expected that https://github.com/dart-lang/sdk/commit/0bec11a4f27ea49d09694ef6e008ad2e6db7a3d7 will result in more frequent old-gen GC instead of allowing unbounded growth in external allocations.

**Comment by Hixie** [comment]
Please rebaseline the benchmark if the regression is expected and not going to be resolved. Thanks.

**Comment by liyuqian** [comment]
I'm going to close his issue and rebaseline the benchmark.
