### ISSUE TITLE
Flutter may not call UpdateScene in fuchsia if there's a ClipXXXLayer with a single PictureLayer

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#18382]
Currently, ClipRectLayer/ClipRRectLayer/ClipPathLayer only sets need system composite flag if its child needs system composite (the behavior inherits from ContainerLayer). But it should always need system composite even if its child does not need system composite (e.g., PictureLayer). Otherwise, UpdateScene won't be called and we'll lose the scenic Clip node.

**Comment by jonahwilliams** [comment]
Fixing this is not important.
