### ISSUE TITLE
Share Plugin: on iOS: to Facebook/Twitter

### ISSUE THREAD

**Issue by babernethy** [flutter/flutter#18385]
Share Plugin v0.5.2 (but also earlier) - iOS 11.3.1 (iPhone 6S Plus & 6 Plus)

Success trying to share a string to Mail, Message, Messenger apps

Sharing to Facebook or Twitter apps ends up with empty/nothing in the target app.

Screenshots seem pointless as it's just Facebook and Twitter with empty boxes.

Also appears to be an issue with the GMail app.

**Comment by zoechi** [comment]
Can you please add the output of `flutter doctor` and the code that allows to reproduce?

**Comment by babernethy** [comment]
Sure ... sorry, should have done that first ...

> flutter doctor -v
[✓] Flutter (Channel dev, v0.5.2, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.5.2 at /Users/1083906/workspace/flutter
    • Framework revision 0a26ac0970 (6 days ago), 2018-06-06 15:28:20 -0700
    • Engine revision a83b37d35a
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/1083906/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.24.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • IBruce   • 77ad8515b1e04e27964b0f8eae8424e9d3b75309 • ios • iOS 11.3.1
    • iPhone 8 • A3F93DC3-AA2C-4096-8F33-9F172AEDD17E     • ios • iOS 11.4 (simulator)

! Doctor found issues in 1 category.

 ```
                     new FlatButton(
                        child: Row(children: <Widget>[
                          Platform.isIOS
                              ? Icon(CupertinoIcons.share)
                              : Icon(Icons.share),
                          Text(
                            ' SHARE',
                            style: TextStyle(fontFamily: 'Roboto'),
                          )
                        ]),
                        onPressed: () {
                          Share.share(_activity.shareActivityString(
                              (_user != null &&
                                  _user.ClassIds != null &&
                                  _user.ClassIds.contains(_activity.id)),
                              _locationDescription));
                        },
                      ),
```


![share_issue](https://user-images.githubusercontent.com/3207230/41290914-405429c8-6e1c-11e8-96a3-f4e71d44d08d.gif)

**Comment by zoechi** [comment]
Are you sure `_activity.shareActivityString(
                             (_user != null &&
                                 _user.ClassIds != null &&
                                 _user.ClassIds.contains(_activity.id)),` returns a value? Have you tried with a string literal?
Did you check the example https://github.com/flutter/plugins/blob/master/packages/share/example/lib/main.dart ?

**Comment by babernethy** [comment]
Yes, certainly a function in need of refactoring, but I split it up (as below), added some of the example boilerplate (not using iPad, but for good measure) and got success messages and no errors ...

```
                        onPressed: () {
                          final RenderBox box = context.findRenderObject();
                          String _message = _activity.shareActivityString(
                                  (_user != null &&
                                      _user.ClassIds != null &&
                                      _user.ClassIds.contains(_activity.id)),
                                  _locationDescription) ??
                              "null message";
                          Share
                              .share(_message,
                                  sharePositionOrigin:
                                      box.localToGlobal(Offset.zero) & box.size)
                              .then((v) {
                            debugPrint("@@@@ Success in Share");
                          }).catchError((e) {
                            debugPrint("!!!! Error in Share:${e.toString()}");
                          });
                        },
```

**Comment by babernethy** [comment]
I created a new flutter app and added the code in the _incrementCounter() method, and it would bring up the numbers in Message, and Mail, but not in Facebook - might be an issue with Facebook itself and how it handles iOS shares (or something about my configuration).

```
import 'package:flutter/material.dart';
import 'package:share/share.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    final text = _counter.toString();
    final RenderBox box = context.findRenderObject();
    Share.share(text,
        sharePositionOrigin: box.localToGlobal(Offset.zero) & box.size);
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by babernethy** [comment]
Going to close this - it is a change in Facebook policy (other SDKs including native and React Native have the same issue) - you can't pre-populate Facebook with a string, they'll allow at most a URL ...

https://developers.facebook.com/policy/#control

https://github.com/facebook/react-native/issues/15523

> Don’t prefill any content in captions, comments, messages or the user message parameter of posts unless ... (criteria this doesn't fulfill)

So this actually works ...

```
    Share.share("http://flutter.io",
        sharePositionOrigin: box.localToGlobal(Offset.zero) & box.size);
```

Sorry for the confusion, thanks for the help.

Not sure how other apps intercommunicate with Facebook to pass on more than a URL ...
