### ISSUE TITLE
How to use alternative themes of material icons

### ISSUE THREAD

**Issue by kalehv** [flutter/flutter#18384]
Google announced a bunch of updates to Material Guidelines during io2018. One of the updates is themes of material icons - https://material.io/tools/icons/
It now has "Filled", "Outlined", "Rounded", "Two-Tone",  and "Sharp".

In Flutter, I know how to use regular icons which are "Filled" ones. I also know how I can add individual assets to the `assets` folder in Flutter app and use those in my code but I'd like if they were readily available so that you could use them like -
``` Dart
IconButton(
  icon: Icon(Icons.volume_up), // <=== Point of interest here
  tooltip: 'Increase volume by 10%',
  onPressed: () { setState(() { _volume *= 1.1; }); },
)
```

Looking at [this repo](https://github.com/flutter/material_icons_font) I think it only supports default (Filled) right now but are there any plans to add other themes?

Probably
``` Dart
IconButton(
  icon: Icon(Icons.volume_up, theme: IconTheme.outlined), // <=== Example
  tooltip: 'Increase volume by 10%',
  onPressed: () { setState(() { _volume *= 1.1; }); },
)
```

**Comment by pgfepale** [comment]
Same question here.. ??

**Comment by lucaslcode** [comment]
I've made a package that lets you use the the 'outline' theme only: https://pub.dartlang.org/packages/outline_material_icons

**Comment by ThinkDigitalRepair** [comment]
> I've made a package that lets you use the the 'outline' theme only: https://pub.dartlang.org/packages/outline_material_icons

Thank you, sir. Using this

**Comment by lukepighetti** [comment]
I would like to see the following material icons

```dart
Icons.foo; // no change
FilledIcons.foo;
OutlinedIcons.foo;
RoundedIcons.foo;
SharpIcons.foo;
```

Two tone would be great, too. But I'm not sure how difficult it would be to implement.

**Comment by kalehv** [comment]
I think if I were to implement it, I would pass a parameter (enum most probably) to the `Icon` constructor rather that creating new classes like `FilledIcons.XXX` or `OutlinedIcons.XXX`. That way it is scalable if there were new styles to be added in future and it will also stay backward-compatible by defaulting the parameter value to `.Filled` which was default before multiple styles were announced.

**Comment by kalehv** [comment]
To me it would make more sense to leave `Icons.` as is as it is more like a "set of icons" just by their identity and not adhering to a particular theme. To get the icons in different themes, I think it makes more sense to pass it as an enum parameter to the `Icon` class constructor instead of creating multiple `FilledIcons`, `OutlinedIcons`. It would definitely be nice to have those separately created but it does not scale if there were more themes to be added in future. Passing a param with default value set to `.Filled` would be ideal IMHO.

**Comment by nt4f04uNd** [comment]
Ahem, it's september 2019, nothing is done about this???????

**Comment by lukepighetti** [comment]
I think they are available now?

**Comment by oky2abbas** [comment]
+1

**Comment by willlarche** [comment]
Work is currently underway to bring this functionality and additional optimizations for icons. Can't give a release estimate so in the meanwhile, I'd continue to get the icons you need as png assets from material.io if you're blocked. But it's a current priority.

**Comment by willlarche** [comment]
https://github.com/flutter/flutter/pull/54923 is last dependent PR. Then we will update the icon font and consts!
