### ISSUE TITLE
Test expecting error is failing

### ISSUE THREAD

**Issue by benhurott** [flutter/flutter#18386]
I wrote a test that must validate an error thrown. This must succeed, but the test is failing.

Test code:
```dart
test('test with raising error must succeed', () {
      Function executor = () {
        throw new ArgumentError('test');
      };

      expect(
          executor(),
          throwsArgumentError
      );
    });
```
This is the test result:
![image](https://user-images.githubusercontent.com/3187772/41266066-b4a44cdc-6dcb-11e8-8ad7-3e4cf1edae27.png)

All other tests are running ok.

We are using [THIS](https://www.dartdocs.org/documentation/test/latest/index.html#test/test@id_throwsA) documentation.

**Comment by zoechi** [comment]
What about

```
      expect(
          executor/*()*/,
          throwsArgumentError
      );
```
As far as I remember your code would work if `executor` returned a `Future` that completes with an error (not sure myself without trying), but for sync code it needs to be a function reference, otherwise the exception is thrown before `expect()` called.

**Comment by benhurott** [comment]
@zoechi perfect!

I change my test to this:
```dart
test('rightSymbol with number must raises an error.', () {
      Function executor = () {
        new MoneyMaskedTextController(rightSymbol: ' U4');
      };

      expect(
          executor,
          throwsArgumentError
      );
    });
```

And it works fine.

Thanks =)
