### ISSUE TITLE
android/local.properties dose not change when OS changes.

### ISSUE THREAD

**Issue by Schmerzmittel** [flutter/flutter#18387]
### Summary
I use Windows 10 daily since I use Visual Studio a lot. But sometimes, I dual-boot into Linux (more specifically Fedora) whenever I need some coding/programming works specifically for Linux. I usually just share the code on a separate drive whenever I dual-boot. So, I decided to do the same with Flutter; however, it only gave me errors.

### Error message
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
Exit code 1 from: /run/media/eunbin/<name of volume>/<app name>/android/gradlew app:properties:

FAILURE: Build failed with an exception.

* Where:
Build file '/run/media/eunbin/<name of volume>/<app name>/android/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > The SDK directory '/run/media/eunbin/<name of volume>/<app name>/android/C:\ProgramData\Microsoft\AndroidSDK\25' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

```

### Steps
1. Create a flutter project on Windows.
2. Run the project.
3. Now, dual-boot into different OS (supposedly Linux).
4. Try to run the project on the different OS.

This error only happens when I try to run the code on **second** OS.

### One way to get around this issue
I can just simply edit `android/local.properties`, which flutter does not automatically change this.

### flutter doctor -v
```
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.4 at /home/eunbin/Flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/eunbin/Android
    • Android NDK at /home/eunbin/Android/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /home/eunbin/Android
    • Java binary at: /usr/share/android_studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /usr/share/android_studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.24.0)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.13.2

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
I think you should not copy the `local.properties` file. `android/.gitignore` lists this file.
If you'd use a GitHub repo to share your code between machines, a checkout wouldn't contain it because it's ignored.

**Comment by Schmerzmittel** [comment]
I see that could be the solution too. Maybe someone might add a tiny patch which places `android/local.properties` in `.gitignore` file?

**Comment by zoechi** [comment]
> Maybe someone might add a tiny patch which places android/local.properties in .gitignore file?

I checked in my project and it was listed in `android/.gitignore`

**Comment by Schmerzmittel** [comment]
I see it now. I was looking at `.gitignore` at the root directory, not the one in the `android/ folder`.

I originally had this issue because I didn't use version control, but just shared the code in a drive. I think I should just move my code to a repository now.

**Comment by zoechi** [comment]
@Schmerzmittel Can we then close this issue?
