### ISSUE TITLE
The amount of open files exceed maximum limit on iOS

### ISSUE THREAD

**Issue by cxq1221** [flutter/flutter#18395]
```
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.3 17D47, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.24.0)
[✓] Connected devices (1 available)

• No issues found!
```
when I read large amount of files simultaneous ，it will failed
```dart
for (int i = 2; i < 288; i++) {
      final name = 'assets/$i.html';
      var re = await rootBundle.load(name);
      print('$i: $re');
    }
```

failed log:
```
Unable to load asset: assets/228.html
```

According to some research, we found the reason may be as mentioned before

**Comment by zoechi** [comment]
Is the title of this issue the exact error message or is this just prose?
In the later case it looks like a dup of #18225

**Comment by cxq1221** [comment]
This is specifictly for iOS(not in Unix or Linux system), it seems that  iOS has limit the amount to about 250

**Comment by zoechi** [comment]
Sorry, I somehow read OSX. 

Is "The amount of open files exceed maximum limit on iOS" the exact error message you get or is this just what you derived from "Unable to load asset: assets/228.html"?

Please also add the output of `flutter doctor`

**Comment by zoechi** [comment]
@cbracken is this your area?
I'd expect `await` to cause files loaded one-by-one. 
I wouldn't expect 288 file handles to be kept open.

**Comment by cxq1221** [comment]
I've tried await, but the result is the same

**Comment by cxq1221** [comment]
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.3 17D47, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.24.0)
[✓] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
For OSX see this comment https://github.com/flutter/flutter/issues/18225#issuecomment-396315283
