### ISSUE TITLE
Keyboard doesn't dismiss when the drawer comes up

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#184]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 20:13 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1522_

----

Giving the Drawer a Focus should solve this, I think.

**Comment by Hixie** [comment]
Drawer has a Focus, but I guess we're not moving the focus scope to it.
