### ISSUE TITLE
The no-response bot reopens closed issues when it removes the "waiting for customer response" label 

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#18401]
![image](https://user-images.githubusercontent.com/405837/41286053-7cd3da5c-6e3e-11e8-8110-ee4f9839068d.png)

Seen here https://github.com/flutter/flutter/issues/18326#issuecomment-396525072

**update**
again

- #18464 
- #13507

**Comment by zoechi** [comment]
@Hixie

**Comment by Hixie** [comment]
Weird.

**Comment by Hixie** [comment]
Ah, it's a known bug: https://github.com/probot/no-response/issues/16
I'm going to close this one and we can track it over there.
