### ISSUE TITLE
Unable to "update-packages" in Flutter (due to pub package constraints)

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#18402]
I was hoping to update the packages in Flutter to get an updated `test` package into `flutter_test` which has a fix for navigating to tests from an editor.

However, running `flutter update-packages --force-upgrade` currently seems to result in compile errors. It upgrades `archive` to `2.0`, however the current `image` package has a constraint of `archive: '>=1.0.16 <1.1.0'`. So this results in `image` being rolled back from `1.1.32` to `1.1.14` because that one doesn't have this constraint.

I'm not sure what the fix is here. I tried to perform the upgrade and then revert the `archive` upgrade, but it results in the checksum at the bottom of the pubspec being incorrect and I don't know if this is a problem (or whether I can re-calculate it without running `--force-upgrade` which just re-upgrades `archive`).

@devoncarew @Hixie not sure how to proceed, any advice?

**Comment by DanTup** [comment]
Just noticed that both `image` and `archive` have the same author; @brendan-duncan - do you remember why `image` has such a tight constraint on `archive`? Is there an update that supports `archive 2.0.0` coming?

**Comment by brendan-duncan** [comment]
I was trying to push the image and archive versions for dart 2 support, I was told the official dart 2 release was imminent. If you need me to loosen up the restrictions, I can.

Brendan

**Comment by Hixie** [comment]
cc @leafpetersen

**Comment by DanTup** [comment]
I think the usage of `image` is limited only to devicelab tests so if updating `image` is non-trivial it may be easier to swap out (it's not in flutter production code).

I still wonder if there's a way to lock `archive` to < `2.0` while doing a `--force-upgrade` to allow upgrading things in the meantime? (I could manually edit files, but the checksums wouldn't pass and I couldn't find a way to update them without it upgrading `archive` to v2).

(cc @HansMuller @gspencergoog - Devon suggested you may have opinions on this?)

**Comment by brendan-duncan** [comment]
Sorry I've been busy with work the last couple of days and didn't really stop to think about what this issue was saying. I didn't realize I forgot to update the archive version dependency in image, so I did that now and published the new version.

**Comment by DanTup** [comment]
Perfect, thanks! Seems like the upgrade no longer downloads anything, so this is resolved.
