### ISSUE TITLE
Test the updater service or remove it

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1841]
https://github.com/flutter/flutter/commit/af3a10f4e4766ff03921935e6fd1e7709a83ed15#commitcomment-16074109

@mpcomplete thinks it may be dead.  We should be able to test things like this now.

No customers are actively using the updater service, so we could remove it.  However many have expressed great interest! :)

There is no huge rush on this.

**Comment by mpcomplete** [comment]
Updater service isn't currently running. It's been broken as of the flutter/engine repository split.

The pub dart package `updater` needs to be built into a snapshot_blob.bin and included in the .flx package somehow. That's no longer happening.

Action plan:
1. Move updater code (dart package and java service) into its own repo, using the new service stuff. This repo should know how to build the dart package into a snapshot.bin.
2. Have this new snapshot.bin be included in flutter .flx packages.
3. Create a new mojo service that knows how to load a snapshot.bin in a separate process. (Replace update_service_android.cc).
4. Have the updater service call #3's service to load the updater snapshot.bin and run it.

**Comment by mpcomplete** [comment]
Actually, scratch that action plan. Step 3 is hard because we won't have mojo initialized in the updater process.

Simpler plan:
1. Change `flutter build` to snapshot and include the `updater` package in all .flx's at a known location.
2. Change the engine to load the `updater` snapshot from that known location.

**Comment by mpcomplete** [comment]
Investigated some more. Adding the `updater` dart package as a dependency increases the app's snapshot size by 500K. That seems like a lot. Not sure if it's worth pursuing this further until developers start asking for an updater.

**Comment by sethladd** [comment]
I don't believe we are tree shaking snapshots yet. We may be able to get that smaller.

cc @a-siva @iposva-google

**Comment by eseidelGoogle** [comment]
It seems we should still set it up to be tested or somehow exercised.  Otherwise it's just dead code.  If we aren't going to use it we can delete it and save the hash for later resurrection when customers ask.  It wouldn't be the first new feature in Flutter we stored that way. :)

**Comment by mpcomplete** [comment]
I removed the UpdateService for now.
