### ISSUE TITLE
FlutterViewController.setInitialRoute doesn't seem to be working?

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#18411]
I tried using `FlutterViewControl.setInitialRoute` in an iOS Swift application, but it doesn't seem to have any effect.  In my Swift code I do:

```
let project = FlutterDartProject(fromDefaultSourceForConfiguration: ())
let flutterViewController =
    FlutterViewController(project: project, nibName: nil, bundle: nil)
flutterViewController!.setInitialRoute("foo")
NSLog("Called setInitialRoute")
navigationController?.pushViewController(flutterViewController!, animated: true)
```
in `main.dart` I have:
```
void main() {
  print("Hello world!");
  print(window.defaultRouteName);
  runApp(new FlutterView());
}
```
When I run it in an iOS Simulator, the debug output I get is:
```
2018-06-12 11:52:34.362506-0700 ios_flutter[7982:53288] Called setInitialRoute
2018-06-12 11:52:34.427703-0700 ios_flutter[7982:53422] flutter: Observatory listening on http://127.0.0.1:50046/
2018-06-12 11:52:34.428052-0700 ios_flutter[7982:53415] flutter: Hello world!
2018-06-12 11:52:34.428362-0700 ios_flutter[7982:53415] flutter: /
```
Is `FlutterViewController.setInitialRoute` broken, or is there some crucial step that I'm missing?

**Comment by jamesderlin** [comment]
I forgot to mention some things:

* This person seems to have the same problem: https://stackoverflow.com/questions/50731093
* I am using Flutter (Channel master, v0.5.2-pre.62, on Mac OS X 10.13.5 17F77, locale en-US)

**Comment by jamesderlin** [comment]
I think the problem might be that the `setInitialRoute` implementation calls `invokeMethod` with `arguments:route` instead of with `arguments:@[route]`.  I'll try fixing it once I figure out how to test it.

**Comment by jamesderlin** [comment]
Nope, that was a red herring.  The `setInitialRoute` handler in the engine does expect the argument to be a single string.

The problem seems to be that the handler (`shell::Engine::HandleNavigationPlatformMessage`) is never invoked because `shell::Engine::DispatchPlatformMessage` goes down the `IsRootIsolateRunning()` path first.  AFAICT, the isolate enters the running state after I call `setInitialRoute` but before `HandleNavigationPlatformMessage` receives it.

**Comment by jamesderlin** [comment]
This is the same as #18500 which got more traction.

**Comment by ryansong** [comment]
Have the same problem. solved by upgrading & reproduce by upgrading.

**Comment by ryansong** [comment]
@jamesderlin I got the problem again for no reason, Is there some stable version have fixed it ?

**Comment by jamesderlin** [comment]
It should have been fixed, but maybe it regressed?  Let's continue this in #23736.

**Comment by kidzss** [comment]
I solved the problem.
//=======================

@interface XXFlutterViewController : FlutterViewController

@EnD

(void)viewDidLoad {
[super viewDidLoad];
// Do any additional setup after loading the view.
FlutterEngine *flutterEngine = self.engine;

[GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
//custom futter plugin
[XXXFlutterBridge registerWithRegistry:flutterEngine];
}

//open flutter vc
XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
[flutterViewController setInitialRoute:@"xxxxx/xxxx"];
