### ISSUE TITLE
Document how Flutter plugins are supposed to be tested

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18418]
Some gaps here:
- `flutter create -t plugin` does not produce any test files.
- https://flutter.io/platform-channels/ does not mention testing.

Actions items:
- Write a best practices doc for testing plugins. Mention both Dart and native code. Publicize the mock channel implementation (I personally learned about this by reading code in flutter/plugins).
- Add test files to the template.

**Comment by yjbanov** [comment]
@roughike, your proposal makes sense to me. Should we close this as a duplicate of https://github.com/flutter/flutter/issues/10824 and continue the discussion there?

**Comment by mehmetf** [comment]
I agree that this is a duplicate of #10824; closing.
