### ISSUE TITLE
Flutter Feature Request

### ISSUE THREAD

**Issue by QuixoticMillennial** [flutter/flutter#18422]
Kotlin/Native is a great but limited to Objective-C & not Swift interoperability, but Flutter is an open source Framework that currently only uses Dart can somebody extend Kotlin functionality to the Flutter framework?

**Comment by zoechi** [comment]
https://hackernoon.com/why-flutter-uses-dart-dd635a054ebf
https://flutter.io/faq/#why-did-flutter-choose-to-use-dart

I hope this answers your question/request. 
I'm going to close the issue.
