### ISSUE TITLE
Document reasoning for why CustomMultiChildLayout size can't depend on children and how to do it

### ISSUE THREAD

**Issue by xster** [flutter/flutter#18426]
After reading the CustomMultiChildLayout and associated docs, it's not very clear why it auto-grabs the largest constraint sizes instead of passing the incoming constraints to its delegate and letting the delegate return a size for itself. 

It could be a separate widget but still useful to have rather than having a custom render object to avoid all the boilerplate of doing non-layout related things.

cc @matthew-carroll

**Comment by xster** [comment]
cc @Hixie 
Talked about this a few days ago. The reasoning was to not have the delegate implementations also handle various intrinsic sizing functions if the parent's size depended on the children.

**Comment by zoechi** [comment]
Any suggestion how to deal with that?

**Comment by zoechi** [comment]
Seems extending RenderBox is the way to go then.

**Comment by Hixie** [comment]
Yes, if you want to do a custom layout where you define your size based on your children then you just create a render object.

**Comment by zoechi** [comment]
@Hixie I think it would be a good idea to point that out in the docs where CustomMultiChildLayout says that it can't.

**Comment by Hixie** [comment]
That's very reasonable!

**Comment by estevez-dev** [comment]
Could someone please provide an example of extending RenderBox for `CustomMultiChildLayout`?

**Comment by patelkrunal78** [comment]
Very similar to [set layout widgets based on the size of the parent?](https://icetutor.com/question/how-can-i-layout-widgets-based-on-the-size-of-the-parent)

**Comment by creativecreatorormaybenot** [comment]
@estevez-dev https://gist.github.com/jxw1102/a9b58a78a80c8e2f54233b418429fa50

**Comment by creativecreatorormaybenot** [comment]
@estevez-dev I actually came across a question on `StackOverflow` now that was broad enough for me to write a small article about this topic.

Here I explain extensively how to use `CustomMultiChildLayout`: https://stackoverflow.com/a/59483482/6509751
