### ISSUE TITLE
Accessibility: Feedback widget of Draggables is not part of the Semantics tree

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#18428]
In verifying accesibility compatibility for #18374, I noticed that when dragging a list tile, the accessibility context gets lost when the tile picks up. Wrapping the Draggable in a MergeSemantics does not help.

Ideally, the semantics focus would persist when the drag event starts.  The Android input language selector is a good example of this.

How is it possible to do this?

/cc @jonahwilliams

**Comment by jonahwilliams** [comment]
The cause is an ignorepointer widet on the feedback with excludes semantics by default.

**Comment by jonahwilliams** [comment]
Fixed by https://github.com/flutter/flutter/pull/18643
