### ISSUE TITLE
Sample/Example Request

### ISSUE THREAD

**Issue by samgithub-duplicate** [flutter/flutter#18438]
Please include an 'official' sample that shows features that are so common t many forms.
The forms sample here just shows forms with a **TextField**. We need a 'comprehensive' example FORMS sample, including the following features:

a) TextField
b) CheckBox
c) Yes/No button
d) Dropdown
e) ListView (select)
f) Validation
g) Data-Binding with Ajax
h) Button for POSTing (should at least show the serialized input values)

I am coming from a Google Polymer environment and I have spent days reading and trying some samples. The samples I have found on the internet typically show one feature and introduce problems of their own.  It will be helpful to show a an integrated sample (similar to the Polymer iron-form element sample.

 I stumbled upon Flutter recently from a **visualstudiomagazine.com** article.  I like what I see so far but I am finding it much more difficult to learn that Polymer.

BTW -- I have been 'playing around with it for less than a week -- so please pardon my ignorance.

**Comment by PaulHMason** [comment]
Have you looked at the Flutter Gallery sample?

https://github.com/flutter/flutter/tree/master/examples/flutter_gallery

Builds of the sample are also available on the Android and iOS app stores.

**Comment by zoechi** [comment]
@Hixie

**Comment by samgithub-duplicate** [comment]
The FORMS example in the sample was very limited; I finally found a good example at https://codingwithjoe.com/
