### ISSUE TITLE
Adding Firestore Dependency Throws app:processDebugManifest

### ISSUE THREAD

**Issue by Chronic788** [flutter/flutter#18437]
## Description

Following the steps in the Google Code Lab at https://codelabs.developers.google.com/codelabs/flutter-firebase/#7 to add Firestore as a dependency throws this exception:
```
> What went wrong:
Execution failed for task ':app:processDebugManifest'.
Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:appcompat-v7:25.4.0] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.
```
I've tried adding older versions of Firestore in the same manner but to no avail. I gather that there is some discrepancy or incompatibility between versions but it is not immediately clear what is causing the problem or how to know what versions of what are compatible.

## Steps to Reproduce

1. ... Add the current (or any) version of Cloud Firestore to pubspec.yaml

##Flutter Doctor Output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2018.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.23.0)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by zoechi** [comment]
#17335 has the same error

@Hixie

**Comment by kroikie** [comment]
@Chronic788

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/796. Any further collaboration will be done there.
