### ISSUE TITLE
TextField multi line - Ability to add Done button to Keyboard

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter#18439]
We need a way to add a Done button to the Keyboard when a TextField has focus with multi line.

```
new ListTile(
  title: TextField(
    maxLines: null, // Auto Expand vertically as user types. Or maxLines: 4 same results.
    keyboardType: TextInputType.text,
    onChanged: (value) {FocusScope.of(context).requestFocus(new FocusNode());},
    onSubmitted: (value) {FocusScope.of(context).requestFocus(new FocusNode());},
    decoration: new InputDecoration(
      labelText: "Notes",
    ),
  ),
),
```

Thank you.

**Comment by zoechi** [comment]
I guess something like https://stackoverflow.com/a/41022589/217408, right?

@Hixie

**Comment by dpasqualin** [comment]
I have a TextField with maxLines=10 and I can't find a way for the the onSubmitted to be called. There is no "Done" button, pressing Enter just jumps the cursor to the next line (as expected) and losing focus does nothing as well.

How can the onSubmitted be triggered in a TextField with maxLines>1?

**Comment by Xavjer** [comment]
Fixed with #20547 
It is now possible to set `keyboardType` to `text` and `textInputAction` to `done` for maxLines>1

**Comment by dpasqualin** [comment]
@Xavjer , sorry to ask it here, but when can I expect to see this fix in the beta branch?

**Comment by Xavjer** [comment]
Actually I can't tell you that, as I did not fix the issue myself, I just had an other similar problem.
Do you have an actual reason to use the beta branch?, I was using dev myself as dart was not up to date, but that changed recently.

**Comment by dpasqualin** [comment]
Thanks. I use the beta branch because it is the one suggested in the [install guide](https://flutter.io/setup-linux/).

**Comment by Xavjer** [comment]
Ok, they probably recommend beta as it is more stable than master, but the master is actively developed on and many issues are fixed here (Like this one) I would therefore recommend to use master and check if everything works as desired with it.

It's as simple as (In a Terminal in flutter directory):
```
flutter channel master
flutter upgrade
```

If you encounter any issues, you can then revert again with:
```
flutter channel beta
flutter upgrade
```

**Comment by zoechi** [comment]
@dpasqualin also worth trying `dev` channel in case `master` fixes the issue for you.
`dev` is between `beta` and `master` and more stable than `master`.

**Comment by zoechi** [comment]
This appears to be fixed.

**Comment by Nk54** [comment]
Hello, I'd like to know if has been merged to the stable branch ?
I'd like to have a multine TextField (maxlines = null) with both return (newline) and done buttons because users can't validate their input when KeyboardType is set to multiline (the action is return). If I set the KeyboardType to done, there is no way to make a return in the TextField.
If anyone knows how to make this behavior working, it would be nice to let me know.
Thanks everyone !

**Comment by Xavjer** [comment]
Hi NK54, I solved this issue by using https://pub.dartlang.org/packages/keyboard_actions on iOS to display an inputAccessoryView with a done button. Like this, I was able to have the newLine button in the keyboard and a Done button in the view above the keyboard. In android, you can close the keyboard with the return/down button.

**Comment by Nk54** [comment]
Hey @Xavjer that's exacly what I was looking for :)
I was sure it could be done because I already did that on Xamarin Forms so why couldn't it be possible on Flutter ?! :)
You saved my night, I will sleep well ;D
Take good care !

**Comment by Nk54** [comment]
Hello, just a last word after playing a bit with it. I found this Widget to lack somme features. I've opened an issue. But still a great starting point ! Thanks again

**Comment by XiaotuZhang** [comment]
textInputAction to done for maxLines>1 will make it impossible to actively return to a new line when editing

**Comment by AnupKumarPanwar** [comment]
Same problem @XiaotuZhang. I want a multiline input in my TextField. But if I do `textInputAction: TextInputAction.done`. Then I can't input a new line and if I don't add the above properties then I'm unable to exit the keyboard.

**Comment by XiaotuZhang** [comment]
@AnupKumarPanwar I ended up doing a trick which is to add a done or check button on the right side of textField, which can take control of the focus out of textField. Hope it helps

**Comment by omidraha** [comment]
Related [SO](https://stackoverflow.com/a/56288863).

**Comment by omidraha** [comment]
There is no normal  way to exit from the Keyboard in this situation:

```dart
    TextField(
      textInputAction: TextInputAction.newline,
      keyboardType: TextInputType.multiline,
      minLines: 1,
      maxLines: 5, // or maxLines:null
    );
``` 
Related [SO](https://stackoverflow.com/a/56288863).

**Comment by LiMeitong** [comment]
> There is no normal way to exit from the Keyboard in this situation:
> 
> ```dart
>     TextField(
>       textInputAction: TextInputAction.newline,
>       keyboardType: TextInputType.multiline,
>       minLines: 1,
>       maxLines: 5, // or maxLines:null
>     );
> ```
> 
> The `onEditingComplete` and `onSubmitted` methods never called.
> 
> Related [SO](https://stackoverflow.com/a/56288863).

So I changed the keyboardType: TextInputType.multiline to TextInputType.text, then the keyboard shows 'done' instead of 'new line', and onSubmitted works fine. But you can't input a new line when editing.
