### ISSUE TITLE
Material button layout can be difficult

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#1843]
MaterialButton's  padding and size constraints makes it difficult to do layouts like the yellow share/explore flat-buttons in this example from the MD spec:

![button_layout](https://cloud.githubusercontent.com/assets/1377460/13023799/44ef360e-d1a1-11e5-8b71-8c8c08253043.png)

To layout the panel below the "Top 10 Beaches.." image, the natural thing to do is just to add a padded column that ends with the button row.

```
new Padding(
  padding: const EdgeDims.all(16.0)
  child: new Column(
    children: <Widget>[
      descriptionLine0,
      descriptionLine1,
      descriptionLine2,
      new Row(justifyContent: FlexJustifyContent.start, children: shareAndExploreButtons)
    ]
  )
)
```
The buttons' padding and minWidth cause them to be inset from the padded left edge. It would be easier if FlatButtons didn't bother with the minWidth and padding at all.

**Comment by abarth** [comment]
The trick is that the padding is supposed to be part of the hittable region of the button.  If you do what you suggest, tapping just to the left of the share button won't trigger the share button.
