### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by UtomoArdy** [flutter/flutter#18440]
Good day, I see your application really helpful me to motivate using flutter, but maybe you can add some example code for user or something like basic training. Thanks for your attention

**Comment by ebeem** [comment]
I think what you are looking for already exists
check this guide:
https://flutter.io/get-started/install/

and this sample app (you can download load it from Google Play and try it)
https://github.com/flutter/flutter/tree/master/examples/flutter_gallery

the examples are included in the project as well:
https://github.com/flutter/flutter/tree/master/examples

**Comment by SeniorIvan** [comment]
Need more examples of using widgets, for example, such as: WillPopScope, CustomPaint, SafeArea

**Comment by zoechi** [comment]
@brianegan ?

**Comment by UtomoArdy** [comment]
Oke sir, thanks for your information

Pada tanggal Rab, 13 Jun 2018 14.51, Günter Zöchbauer <
notifications@github.com> menulis:

**Comment by zoechi** [comment]
I'm going to close because this issue is too generic to be actionable.
