### ISSUE TITLE
Large forms "lose" data

### ISSUE THREAD

**Issue by Mythar** [flutter/flutter#18442]
I ran into a problem using a large form of TextFormFields.
The problem is that the form is to big for the screen so some of the TextFormFields never gets initialized.
Even when you scroll the form gaps appear in the form data.
Anyway to force all fields to initialize?
Example:
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<FormState> formKey = new GlobalKey<FormState>();
  Map formData = new Map();

  void onSaved(int index, String value) {
    setState(() {
      formData[index] = value;
    });
  }

  void saveForm() {
    if (formKey.currentState.validate()) {
      formKey.currentState.save();
      formData.forEach((key, value) {
        print(key.toString() + ': ' + value);
      });
    }
  }

  List<Widget> buildFormItems() {
    List<Widget> list = new List<Widget>();

    for(var i=0; i<100; i++) {
      list.add(
        new TextFormField(
          initialValue: 'value: ' + i.toString(),
          onSaved: (String value) => onSaved(i, value),
        )
      );
    }

    return list;
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
        actions: <Widget>[
          new FlatButton(
              onPressed: () => saveForm(),
              child: new Icon(Icons.update))
        ],
      ),
      body: new Form(
          key: formKey,
          child: new ListView(
            children: buildFormItems(),
          )
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Can you please add the output of `flutter doctor`?

I think https://github.com/flutter/flutter/pull/15484 should improve the situation together with this suggestion https://stackoverflow.com/questions/45240734/flutter-form-data-disappears-when-i-scroll should make it work.

**Comment by Mythar** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.48], locale en-DK)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!
Process finished with exit code 0

**Comment by Mythar** [comment]
Okay, wrapping the fields in a SingleChildScrollView and Column did the trick, thx :)
It should be in the form documentation...

**Comment by zoechi** [comment]
@Hixie

**Comment by Mythar** [comment]
On another note, if you press a field at the bottom of the screen the keyboard will pop up and cover the field so you cant see what your typing, imo the field should auto scroll into view...

**Comment by zoechi** [comment]
@Mythar that should be fixed with #18291

**Comment by zoechi** [comment]
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by stevenspiel** [comment]
@Mythar I thought I was loosing it. Thanks for posting that solution.

Perhaps flutter could warn you if you have a ListView inside a Form element?

**Comment by langaro** [comment]
@Mythar soluction worked just fine. I wrapped the whole form content with SingleChildScrollView ans Column.
