### ISSUE TITLE
TextStyle adjustments are clunky

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#1845]
In a trivial example, like the one below from the MD spec, the color of the dialog's default content text style has been lightened (per the designer):

> decrease its prominence so that users focus on the main question (which is in the dialog title)

And a slightly larger font than the default was used because the dialog's content is so brief.

![text](https://cloud.githubusercontent.com/assets/1377460/13024165/14022416-d1a6-11e5-838b-25672d62275f.png)

The dialog's contents could be created like this:

```
new Text(contents, Theme.of(context).text.subhead.copyWith(color: theme.text.caption.color))
```

We're not specifying an explicit color here because the code should work no matter what Material theme has been selected. The caption TextStyle happens to have a color that's about right.

This is sad for several reasons:
- The code obscures what we're doing, which is asking for a font that's a little bigger than the default dialog font and with a color that's a little lighter.
- The name "subhead" doesn't mean anything in this context. Likewise for "caption".
- It fails if a theme isn't specified.

Maybe what's needed are APIs provided by containers like Dialog, and modifiers for TextStyle. Something like:

```
Dialog.contentTextStyle(context).largerSize().lighterColor()
```

**Comment by abarth** [comment]
Can these be tweaked in arbitrary ways or are there a set number of common alternatives?  If there are set number of common alternatives, it might be worth adding those as parameters to Dialog and have it set up a new DefaultTextStyle for its content, for example.

**Comment by Hixie** [comment]
We have some constructor and factories that make this a bit better now, but more importantly, we really haven't heard many complaints about this recently, so I'm going to close it for now.
