### ISSUE TITLE
ExpansionPanel header is cut out when font size is scaled up

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#18456]
On Android, you can configure different font sizes, which are followed by Flutter.

This creates a problem with ExpansionPanel because it has a fixed header height. When  the font size is set to "Huge", the bottom part of the header text is cut out.

**Comment by jonahwilliams** [comment]
Underlying issue is here: https://github.com/flutter/flutter/issues/12311

**Comment by mehmetf** [comment]
@robertoscaramuzzi Could we see what the native app behavior is for this as a reference? I don't think Material docs cover this. This most likely manifests in the appbar.

**Comment by robertoscaramuzzi** [comment]
The native app seems to handle this just fine. The app header is tall enough to contain the largest font size.

**Comment by HansMuller** [comment]
We can address this in Flutter.

 Unfortunately there's still not guidance from the [Material Design spec ](https://material.io/design/) about how to change internal component layouts based the text scale factor. Whatever solution we provide now will have to be considered provisional until the general problem is sorted out.

cc @willlarche
