### ISSUE TITLE
Unable to run "pub run test" for flutter_tools tests

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#18455]
The tests in flutter_tools (which are normal Dart VM tests, not Flutter tests) currently don't work if invoked via `pub run test`:

```
00:00 +0 -79: loading test/base/process_test.dart [E]                                                                                                          
  Failed to load "test/base/process_test.dart":
  Unable to spawn isolate: Unhandled exception:
  Could not import "package:test/src/runner/vm/catch_isolate_errors.dart" from
"data:application/dart;charset=utf-8,%20%20%20%20import%20%22dart:isolate%22;%0A%0A%20%20%20%20import%20%22package:stream_channel/stream_channel.dart%22;%0A%0A%20%20%20%20import%20%22package:test/src/runner/plugin/remote_platform_helpers.dart%22;%0A%20%20%20%20import%20%22package:test/src/runner/vm/catch_isolate_errors.dart%22;%0A%0A%20%20%20%20import%20%22file:///Users/dantup/Dev/Google/flutter/packages/flutter_tools/test/base/process_test.dart%22%20as%20test;%0A%0A%20%20%20%20void%20main(_,%20SendPort%20message)%20%7B%0A%20%20%20%20%20%20var%20channel%20=%20serializeSuite(()%20%7B%0A%20%20%20%20%20%20%20%20catchIsolateErrors();%0A%20%20%20%20%20%20%20%20return%20test.main;%0A%20%20%20%20%20%20%7D);%0A%20%20%20%20%20%20new%20IsolateChannel.connectSend(message).pipe(channel);%0A%20%20%20%20%7D%0A%20%20":
No mapping for 'test' package when resolving 'package:test/src/runner/vm/catch_isolate_errors.dart'.
  null
```

The test runner I'm working on for VS Code is going to have to use `pub run test` in order to use the JSON reporter so I'd love to make this work. I'll try and do some digging into this, but if anyone has any existing insight into what's going on here (and whether it's going to be possible to fix), lmk!

(cc @grouma @devoncarew)

**Comment by tvolkert** [comment]
But that's how they're run on our bots, which are passing...

https://github.com/flutter/flutter/blob/b401e765546098fbc642e09d5a0771f1d0805f5d/dev/bots/test.dart#L222

**Comment by DanTup** [comment]
@tvolkert I guess that's good news; it must just be something weird locally then - I'll do more digging - ta!

**Comment by cbracken** [comment]
@DanTup Are you running using `-j1`, as noted in README.md?

**Comment by DanTup** [comment]
Aha, I was not! :( With that I get different failures, but those ones look more like just some local setup (missing file errors etc.). Seems that when running with `--pause-after-load` it'll automatically set concurrency to `1` but I wasn't passing that when testing on the command line.

So this should be a non-issue with yesterday's `test` changes; I can just switch to `--pause-after-load` and it should all work (and without needing to pass `-j1` explicitly).

Thanks all! 👍
