### ISSUE TITLE
Failed hot reloading with a data List

### ISSUE THREAD

**Issue by cronos88** [flutter/flutter#18468]
Flutter versión: 0.4.4 beta 3

I have a fruit list:

```dart
var items = ['Banana', 'Kiwi', 'Lemmon', 'Pineapple', 'apple'];
```

Then, items are passed to a class:

```dart
home: MyListview(items: items,),
```

In the MyListview class I use the list in a ListView.builder to display it:

```dart
class MyListview extends StatelessWidget {

  final List<String> items;

  MyListview({Key key, @required this.items}): super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Mis Contactos'),
      ),
      body: Container(
        margin: EdgeInsets.symmetric(vertical: 20.0),
        child: new ListView.builder(
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text("${items[index]}"),
            );
          },
        ),
      ),
    );
  }
}
```

I run app and display items fine. Now, when I add a new fruit to the list, after it does the hot reloading, the new fruit doesn't display in the screen. Whe I stop and re-run app, new fruit does display fine, but wit hot reloading doesn't.

**Comment by tiagojencmartins** [comment]
Per the documentation, global variables and static fields are treated as a state and not reinitialised when hot reloading. A hot restart is needed.

**Comment by zoechi** [comment]
`main` is not re-executed as well on hot-reload.
We would need to see more code to be able to make suggestions how to fix.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
