### ISSUE TITLE
Firebase Push Notifications

### ISSUE THREAD

**Issue by tiagojencmartins** [flutter/flutter#18464]
I'm still a rookie at Dart & Fluter so bear with me.

In theory if we put the firebase configuration inits in a widget and if that widget gets destroyed, so does the configuration?

How does one persist that in an app with multiple pages? Main?

**Comment by zoechi** [comment]
> firebase configuration inits in a widget

Not sure what you mean by that. 
Firebase once initialized keeps the configuration.

https://medium.com/@agungsurya/basic-state-management-in-google-flutter-6ee73608f96d might help you to get started.

See also https://github.com/flutter/flutter/issues/11093, especially the I/O 2018 video linked to in https://github.com/flutter/flutter/issues/11093#issuecomment-388313078

**Comment by tiagojencmartins** [comment]
Sorry for the confusion and thanks for the links!
