### ISSUE TITLE
improve analytics for hot reload

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#18479]
We want to improve the analytics we're collecting for hot reload. The current idea is:

- locally collect information about the ratio of reloads to restarts
- periodically (daily or weekly) send this info to google analytics

We want the analytics in flutter_tools so we capture it evenly between different clients (CLI users, IntelliJ/AS, and VS Code).

@InMatrix 

(moved from https://github.com/flutter/flutter-intellij/issues/2372)

**Comment by devoncarew** [comment]
I believe this is addressed, with our current analytics, and some creative queries on the backend. @InMatrix, does that sound right?

**Comment by InMatrix** [comment]
Yes, it's fine to close this issue.
