### ISSUE TITLE
Writing DateTime to Firestore via iOS produces incorrect server-side timestamp

### ISSUE THREAD

**Issue by eliothsu** [flutter/flutter#18470]
Steps to Reproduce
------------------------
- Connect a Firebase project to a Flutter app
- Write a DateTime object to a document in Firestore (example code below)
- Test on an iOS device
```dart
Firestore firestore = new Firestore(app: FirebaseApp.instance);
Map<String, dynamic> dataMap = new Map<String, dynamic>();
dataMap["time"] = new DateTime(2018, 6, 13, 21, 0);
firestore.collection("someCollection").document("someDocument").setData(dataMap, merge: true);
```

The Issue
-----------------------
On Android, the above implementation works as expected; on iOS, the Firestore database document entry is populated with some incorrect value. For the example above, that value is something like `December 30, 1969 at 11:27:22 PM (UTC-8)` depending on your time zone.

The Culprit
------------------------
- [Lines 178-179 of cloud_firestore's CloudFirestorePlugin.m](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m#L175-L180)
```
176:    SInt64 value;
177:    [self readBytes:&value length:8];
178:    NSTimeInterval time = [NSNumber numberWithLong:value].doubleValue / 1000.0;
179:    return [NSDate dateWithTimeIntervalSince1970:time];
```

Proposed Solution
-------------------------
1. Replace lines 178-179 with `return [NSDate dateWithTimeIntervalSince1970:(value / 1000.0)];`
2. Replace lines 178-179 with `return [FIRTimestamp timestampWithSeconds:(value / 1000.0) nanoseconds: (value % 1000)];`

Both of the above solutions work on my end. I'd like to request that this issue is validated, as this problem may be an issue with my specific flutter installation and/or project. If others have this issue as well, I'd be happy to make a PR.

**Comment by zoechi** [comment]
@Hixie

**Comment by Scuttman** [comment]
I am having exactly the same problem. All my dates from Firestore on my iPhone are returning 1970 and times different to my current timezone. This change would be great. I will now try and apply @eliothsu fix. Thanks.

**Comment by eliothsu** [comment]
As it's been a little while and other people have the same issue, I've created a PR [#654](https://github.com/flutter/plugins/pull/654) with solution #1 listed in the original post.

**Comment by kroikie** [comment]
@eliothsu I was unable to reproduce this issue. Could you or @Scuttman reproduce this with the example app in the plugin?

**Comment by mrbigwolf67** [comment]
How do i fix this in my Angular6 Application.. 
Where should i put this line ?? 
Replace lines 178-179 with return [NSDate dateWithTimeIntervalSince1970:(value / 1000.0)];
I just dont get it.. ???

**Comment by zoechi** [comment]
@mrbigwolf67 This is about Dart forwarding to iOS's native Firebase implementation and unrelated to Firebase in the browser.

**Comment by AndrewPetrovics** [comment]
Experiencing same issue on iPhone5

**Comment by zoechi** [comment]
@AndrewPetrovics 

from kroikie in https://github.com/flutter/flutter/issues/18470#issuecomment-404241403

> I was unable to reproduce this issue. Could you or @Scuttman reproduce this with the example app in the plugin?

**Comment by AndrewPetrovics** [comment]
I'm having to borrow someone's phone to recreate issue so didn't have time to reproduce with the example app.

However, @eliothsu's fix worked like a charm :)

**Comment by martinvarelaaaa** [comment]
@eliothsu do you have news?

**Comment by mabinici** [comment]
This error seems to be solved for iPhones, but I am able to generate the same issue on an Ipad for some reason.

**Comment by kika** [comment]
I have this issue with Firebase Auth timestamps on iOS simulated iPhone5s with latest flutter from dev channel. iOS timestamps are in seconds while on Android they are in milliseconds.

**Comment by collinjackson** [comment]
I opened flutter/plugins#1207 based on the proposed solution from @eliothsu.

If anyone has any feedback before I land this, please let me know.

**Comment by kroikie** [comment]
@eliothsu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/795. Any further collaboration will be done there.
