### ISSUE TITLE
Image filter support (ex: Tone Curve)

### ISSUE THREAD

**Issue by yagitatsu** [flutter/flutter#18474]
I have seen the excellent default library called CIFilter in iOS.
Do you have any plans to support equivalent function ?

**Comment by zoechi** [comment]
Can you please add a link to CIFilter to make it more clear what the feature request is about?

**Comment by yagitatsu** [comment]
Thanks for your reply.
I'm sorry about that. It would be happy if you check links below: 

https://developer.apple.com/documentation/coreimage/cifilter
https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreImaging/ci_intro/ci_intro.html#//apple_ref/doc/uid/TP30001185

**Comment by zoechi** [comment]
@Hixie

**Comment by goderbauer** [comment]
Related to (and possibly a dupe of) https://github.com/flutter/flutter/issues/13489 orhttps://github.com/flutter/flutter/issues/16296.

**Comment by jonahwilliams** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/16296 .

This can generally be done with fragment shaders, and we're planning to add APIs to make this easier in the future.
