### ISSUE TITLE
TextField cursor is misplaced when textAlign is end, right, or center

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#18483]
TextField cursor is misplaced after one charcacter is input if the TextField's textAlign value is TextAlign.end, TextAlign.right, or TextAlign.center.

This issue just serves to collect the existing issues that have  already reported the cursor problem: #17960, #17625, #17945, #18472.

The source of the problem is the call in TextPainter.to_getOffsetFromUpstream() to  ui.Paragraph.getBoxesForRange(0, 1).  The value returned by getBoxesForRange() would be correct if the text was left/start aligned.

After an additional character is entered, the cursor ends up where it belongs and stays there.

```
import 'package:flutter/material.dart';

class AlignedTextField extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Center(
        child: new SizedBox(
          width: 200.0,
          child: new TextField(textAlign: TextAlign.end), // or TextAlign.right, TextAlign.center
        ),
      ),
    );
  }
}

void main() {
  runApp(new MaterialApp(home: new AlignedTextField()));
}
```

cc @jason-simmons

**Comment by HansMuller** [comment]
We're going to need regression tests for this in the framework. I can add them.

**Comment by Aniki312** [comment]
@HansMuller 

We found another issue might related to this issue. 
After input some text, and click the left side of the textfield
the cursor is still at the end of the textfield, while the actual focus is at the start of the textfield.
You can see from the gif how new characters are appended, and also how backspace stop working after additional characters are deleted. 

![textfield_cursor_issue](https://user-images.githubusercontent.com/2377511/45285888-e58e0d00-b516-11e8-8d0e-44178c19dd7d.gif)

Flutter doctor -v 
```
[✓] Flutter (Channel master, v0.8.2-pre.24, on Mac OS X 10.13.6 17G65, locale zh-Hant-TW)
    • Flutter version 0.8.2-pre.24 at /Users/aniki/git/flutter
    • Framework revision 4d9bbc10f2 (26 hours ago), 2018-09-09 03:15:34 -0400
    • Engine revision 1770f88548
    • Dart version 2.1.0-dev.4.0.flutter-cd9a42239f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/aniki/Library/Android/sdk
    • Android NDK at /Users/aniki/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = /Users/aniki/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (2 available)
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 9 (API 28) (emulator)
    • iPhone X                     • BE0CF3F0-CCBB-469B-A1FE-BE5530372455 • ios         • iOS 11.4 (simulator)
```

**Comment by zoechi** [comment]
@Aniki312 this issue is closed since a while.
Can you please create a new issue (with a link to this one if appropriate)?
Comments on closed issues are easily missed.

**Comment by Aniki312** [comment]
@zoechi 
OK I just created a new issue #21679

**Comment by mzarsaw** [comment]
fix that with set textDirection to ltr. it's cool
