### ISSUE TITLE
LinearGradient documentation: Possible to add an image of what the end results look like?

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#18484]
https://docs.flutter.io/flutter/painting/LinearGradient-class.html

In g3, we had a client building a prototype who was unsure of how to get a gradient to cut off before the full height of the screen.  They used `stops` to try and achieve this effect instead of the `begin` and `end` Alignment parameters.

I suspect that having an image in the `LinearGradient` documentation to show what the gradient looks like.

Optionally, I think it would be valuable to include a sample that uses the default `tileMode` since that will make it easier to illustrate how the begin and end properties work.

**Comment by darshankawar** [comment]
The [PR](https://github.com/flutter/flutter/pull/63604) to address this issue has been merged. Now, the `LinearGradient` documentation has an interactive app example and sample code that shows its usage.
Closing this as fixed. If anybody disagrees, write in comments and I'll reopen it.
