### ISSUE TITLE
FlutterView needs to communicate its preferred size back to the platform

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18482]
The current design asks add-to-app developers to set exact bounds for FlutterView. It either needs to be constrained by the parent (such as screen) or have exact width and height.

We should consider adding support for coordinating the layout passes between native and Flutter so that FlutterView can size itself according to its contents (i.e. wrap_content behavior on Android). Some use cases: 
- Flutter is going to be used alongside native views in a native-controlled scrollable. 
- User changes the text size (accessibility) which needs to resize the FlutterView.

**Comment by mehmetf** [comment]
Copying a comment thread on this issue so customers can see it:

Comment from @Hixie : Sure, it would be relatively straight-forward to do this.

Comments from @jason-simmons : One potential issue is that Android will be expecting measurement to happen synchronously on the platform thread. We would need to send a layout request to Dart on the UI thread and block until completion. Or return a (potentially stale) cached result.

Response from @Hixie : I was imagining you would have it be 0x0, then load the engine, run the code, measure what the code wants, etc, then change the view to be the right size.

**Comment by Hixie** [comment]
I don't think we should implement this as an official feature. It's relatively simple to implement as a message channel on an adhoc basis.

cc @jason-simmons Can you post your demo's java and dart files here?

**Comment by Hixie** [comment]
@mehmetf I believe customer: dream is satisfied by the example we provided; should we close this bug?

**Comment by jason-simmons** [comment]
This app demonstrates how to adjust the size of a Flutter view to wrap the content

[WrapContent.zip](https://github.com/flutter/flutter/files/2143080/WrapContent.zip)
