### ISSUE TITLE
why Flutter can't show preview just like Android Studio?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#18496]
I have an idea,it'a about Flutter preview.
I've drawn a picture about the idea.
As shown below:

![preview](https://user-images.githubusercontent.com/27602662/41462038-1fcade40-70c4-11e8-9ff7-5926cc9f96aa.png)

**Comment by zoechi** [comment]
I don't know the "preview" feature from AS, but it sounds like what the Flutter plugin provides under

![image](https://user-images.githubusercontent.com/405837/44630472-8d73da00-a95e-11e8-9e4a-f05bd03a61d6.png)

It's till work in progress and I haven't seen it working yet.

**Comment by AweiLoveAndroid** [comment]
As I konw ,many developers want to  Visual development，just like Android Studio, you can see what the UI is when writing your code.

**Comment by AweiLoveAndroid** [comment]
As I konw ,many developers want to Visual development，just like Android Studio, you can see what the UI is when writing your code.  @zoechi

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2937](https://github.com/flutter/flutter-intellij/issues/2937) via [**ZenHub**](https://www.zenhub.com/)
