### ISSUE TITLE
Future Building calling builder twice (with and without snapshot data)

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#18490]
I am trying to use a FutureBuilder. and I noticed that the builder is first immediately called with a null snapshot.data and then after the future is resolved. Why is the first one called? How can I ensure that the builder is only called when the data has been populated by the future contact ?

```dart
import 'package:flutter/material.dart';
main() {    
    runApp(new TestSample());
}

class TestSample extends StatelessWidget{
    @override
    Widget build(BuildContext context) {
         var widget = new MaterialApp(
                home: new Scaffold(
                    body: new Center( 
                        child: new MyContainer(),
                    )
                ),
            );
            return widget;
        }
}

class MyContainer extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
        return new FutureBuilder<dynamic>(
            future: getWidgetText(),
            builder: (context, snapshot) {
                return new Text(snapshot.data);
            }
        );
    }

     getWidgetText() async {
        return "CHanges";
    }
}
```

**Comment by jonahwilliams** [comment]
HI @manujbahl , this is the expected behavior of the FutureBuilder.  The build method must always immediately return a widget, and if the future hasn't completed yet the data will be empty.  The snapshot has a connectionState property which will tell you whether or not the future has data in it, from the FutureBuilder documentation:

```dart
new FutureBuilder<String>(
  future: _calculation, // a Future<String> or null
  builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
    switch (snapshot.connectionState) {
      case ConnectionState.none: return new Text('Press button to start');
      case ConnectionState.waiting: return new Text('Awaiting result...');
      default:
        if (snapshot.hasError)
          return new Text('Error: ${snapshot.error}');
        else
          return new Text('Result: ${snapshot.data}');
    }
  },
)
```
Source: [FutureBuilder](https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html)

You can always return a `new Container()` if you don't want anything to be built before the data is loaded.

**Comment by manujbahl** [comment]
My particular scenario is that I don't know what to return. A button click on the page is setting off an event that requires me to make an update the text via an async call. I don't want to store the current text value, which means that on the first call to the future builder I have to either do a placeholder or empty text. If I do that I see a flicker in a situations where the new text after the button click is actually going to be same. That makes to a not so good experience.

**Comment by jonahwilliams** [comment]
It kind of sounds like you don't really want to use a Future, or a FutureBuilder then.  In your example you could rewrite it with a stateful widget.

```dart
class MyContainer extends StatefulWidget {
    @override
    Widget build(BuildContext context) {
        return new FutureBuilder<dynamic>(
            future: getWidgetText(),
            builder: (context, snapshot) {
                return new Text(snapshot.data);
            }
        );
    }
}

class _MyContainerState extends State<MyContainer> {
  String _data = '';

  @override
  void initState() {
    super.initState();
    getWidgetText().then((String value) {
      setState(() {
        _data = value; // only updates text when the data is loaded.
      });
    });
  }

  @override
  Widget build(BuildContext context) => new Text(_data);
}

```

I don't know how you are calling your API, but this is how you would get data from a future.

**Comment by manujbahl** [comment]
Thanks .. i still ended up using a futurebuilder but carrying around the old snapshot data to build the widget while a new snapshot is generated

**Comment by pat64j** [comment]
> @jonahwilliams In my case, the future method of my FutureBuilder fetches data and caches it for offline use of my app.
> I realized the data is being saved twice.

I didn't import the dart:async library.
My issue is solved now.

**Comment by Smartiiez** [comment]
Thx @manujbahl, it was exactly what I need.
