### ISSUE TITLE
Autocompletion of Colors.xy deletes lines of code

### ISSUE THREAD

**Issue by luke-z** [flutter/flutter#18495]
Hello guys

I'm not sure if that issue has been posted before.
I just noticed it today.

Whenever I'm autocompleting a Colors.xy coloring, AndroidStudio removes a big part of my code.

In this example, I was typing "splashColor: Colors.re" and completed it to Colors.redAccent by pressing the Tab button.
If I press "Ctrl+Z" and repeat the same thing, it works though.
Seems like it only happens if the line is newly written.

Regards,
Lukas

Before:
<img width="284" alt="before" src="https://user-images.githubusercontent.com/37207714/41461870-4a763e2e-7091-11e8-890e-42ce42b086e0.PNG">

After:
<img width="316" alt="after" src="https://user-images.githubusercontent.com/37207714/41461869-49e0c902-7091-11e8-87d2-41548a3476a5.PNG">

**Comment by zoechi** [comment]
@devoncarew

**Comment by luke-z** [comment]
Just noticed, that it's with multiple autocompletions that autocomplete after a "."

**Comment by devoncarew** [comment]
@luke-z, could you post the version of Android Studio, and the version of the Dart plugin, that you're using? Thanks!

**Comment by Kartik1607** [comment]
Related to https://github.com/flutter/flutter-intellij/issues/2317

**Comment by luke-z** [comment]
@devoncarew 

Here are the specs from "flutter doctor -v":

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

The exact version of Android Studio is:
V. 3.1.3
Build #AI-173.4819257



Additional information (the whole doctor extract):

> [√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.112], locale de-CH)
    • Flutter version 0.4.4 at C:\src\flutter
    • Framework revision "f9bb4289e9" (5 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

I had to add the quotation marks to the framework revision so it doesn't become a hyperlink :)

> [√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\Luke\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

> [√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

> [√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Users\Luke\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\181.4203.550
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4203.498

> [√] Connected devices (1 available)
    • SM G935F • ad071703b802d502a3 • android-arm64 • Android 8.0.0 (API 26)

> • No issues found!

**Comment by devoncarew** [comment]
@luke-z, thanks for the report; I'm closing in favor of https://github.com/flutter/flutter-intellij/issues/2317, and will follow up there.
