### ISSUE TITLE
Music in demo game still plays when game is not active

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#185]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 20:22 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1523_

----

e.g. when screen is off or when you've hit the home button.

cc @vlidholt

**Comment by jason-simmons** [comment]
fixed
