### ISSUE TITLE
Support for Vuforia AR

### ISSUE THREAD

**Issue by aadishgoel2013** [flutter/flutter#18508]

**Comment by zoechi** [comment]
@Hixie

**Comment by zoechi** [comment]
https://www.vuforia.com/

**Comment by Hixie** [comment]
@aadishgoel2013  Can you elaborate on what exactly you would like to see here?

**Comment by aadishgoel2013** [comment]
A way to add AR content into our flutter apps, like we can do while making native java, kotlin android apps. In them we can directly integrate AR screens in the existing application.
Or
We can have a way directly by which we can integrate vuforia image db's (or any other library) and have something where we can put our AR content directly there in flutter out of the box that would be amazing.

**Comment by vickylance** [comment]
It would be awesome to see any progress here

**Comment by jeromenicholas07** [comment]
It would be amazing..
Maybe this would do the trick [https://pub.dev/packages/flutter_unity_widget]
Can anyone try and confirm?

**Comment by dannycortesv** [comment]
Please, we need one platform like this

**Comment by stuartmorgan** [comment]
This is something that would be best built as a third-party plugin; we generally do not build first-party plugins to wrap third-party, non-OS SDKs.
