### ISSUE TITLE
Support For Unity 3d

### ISSUE THREAD

**Issue by aadishgoel** [flutter/flutter#18509]

**Comment by zoechi** [comment]
@Hixie

**Comment by Hixie** [comment]
@aadishgoel2013 @Sack97 @SirIntruder @armandsLa Can you elaborate on what exactly you would like to see here?

**Comment by Sach97** [comment]
Sorry I don't exactly remember what was my idea when I searched for this and liked this issue as I work on different project now. Maybe I was searching for integrations of an unity views in Flutter like this example in [react native ](https://github.com/f111fei/react-native-unity-view)

**Comment by kerberjg** [comment]
Isn't this achievable now with Platform View?

**Comment by juicycleff** [comment]
Yeah, it is. I even implemented it, but my app crashes after AndroidX upgrade. It follows the React Native Unity View pattern [Flutter Unity View](https://pub.dartlang.org/packages/flutter_unity_widget)

**Comment by juicycleff** [comment]
Hey, guys, I fixed it. The library is fully functional. [Flutter Unity Widget](https://pub.dartlang.org/packages/flutter_unity_widget) Will add tutorial and docs soon

**Comment by juicycleff** [comment]
Hey, guys so I have docs and a working demo. You could take a look. I still need to finish up iOS also, but if you feel like taking a stab at it please do. I need to update flutter_graphql more this week, so will spend little time on flutter_unity for a few days

**Comment by hololeo** [comment]
How about the other way around? Have a flutter widget show inside of Unity? Like a unity plane that renders flutter? Probably more challenging as you have to account for user inputs

**Comment by kerberjg** [comment]
@hololeo In that case it would me more in Unity's scope, rather than Flutter's.

I assume it would be probably doable, but also very hacky

**Comment by kerberjg** [comment]
This seems to be fixed now, can we close this issue?

**Comment by 1l0** [comment]
Yes.

**Comment by SachinGanesh** [comment]
> Hey, guys, I fixed it. The library is fully functional. [Flutter Unity Widget](https://pub.dartlang.org/packages/flutter_unity_widget) Will add tutorial and docs soon

@juicycleff Thank you for your plugin!. Here is a demo of the app we have built using your plugin [Flutter + Unity3D AR Foundation](https://youtu.be/A56gVrDAXbU)

**Comment by rohitdesaidev** [comment]
Redirecting my comments from #73287 
Anybody working on the same to develop plug in for flutter inside Unity 3D. 
Also I am curious about is it possible to embed flutter inside Unity ? Because I don't have much idea about core flutter. 
Any thoughts will be appreciated.

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
