### ISSUE TITLE
Dart SDK location not found on VS Code/Pixelbook/Crostini

### ISSUE THREAD

**Issue by aeroperf** [flutter/flutter#18502]
## Steps to Reproduce

On a Pixelbook running Linux in Crostini. I open VS Code and it loads. After about 15-20 seconds, an analysis starts then the PROBLEMS tab fills with errors (10k+). Flutter and other subfolders on the left pane turn red. VS Code often locks up during this analysis.

I know this works as I was able to get everything working previously (but then restarted a Crostini container for other reasons and lost Flutter). When it did work, I did not have to install a Dart SDK or specify its location, it just worked. I verified that the user settings path to Dart includes the sdk, and it does.

I do not have Android Studio installed and wonder if that's somehow the problem, but can't see why that would be the case. 

I also noticed flutter doctor indicated the VS Code Dart extension is not installed, even though within VS Code, it shows it as installed.

1. Follow instructions in [this post](https://medium.com/@timsneath/flutter-development-on-a-pixelbook-dde984a3fc1e) to get and install Flutter and VS Code
2. Open VS Code; after a few seconds, it find 10k+ errors and the flutter folder is highlighted red.
3. In the past I was given the option to located Dart-SDK location, and when clicking on it, nothing happened.
4. More recently, I'm not given that option anymore.

## Logs

```
User settings:
"dart.sdkPath": "/home/mrv/flutter/bin/cache/dart-sdk/bin",
"dart.flutterSdkPath": "/home/mrv/flutter"
```

```
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.4 at /home/mrv/flutter
    • Framework revision f9bb4289e9 (5 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] VS Code (version 1.24.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[!] Connected devices
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by DanTup** [comment]
Some of these issues seem likely Dart Code rather than Flutter so I've re-opened this over at https://github.com/Dart-Code/Dart-Code/issues/1013. Please check there for my response. Thanks!
