### ISSUE TITLE
Camera plugin doesn't take maximum resolution picture on iOS

### ISSUE THREAD

**Issue by Maleandr** [flutter/flutter#18510]
Camera plugin doesn't take (takePicture method) maximum resolution picture on iOS. It works well on Android (max camera resolution), but it takes only preview resolution picture on iOS. I guess plugin should behave constantly on both platforms (max camera resolution)

AVCapturePhotoOutput is missing setHighResolutionCaptureEnabled and AVCapturePhotoSettings is missing  [settings setHighResolutionPhotoEnabled:YES].

I have also noticed a lot of warnings about iOS 10 sdk, but cocoapod was declared with iOS 8 support. I guess camera plugin won't work for version < 10.

**Comment by Maleandr** [comment]
I have created PR to fix that https://github.com/flutter/plugins/pull/617

**Comment by zoechi** [comment]
flutter/plugins#617 is merged. I assume this issue is fixed.
Thanks for the contribution!
