### ISSUE TITLE
Document how to use url_launcher for sms

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#18517]
How does one specify phone number and sms body in the URL?

**Comment by chinmaygarde** [comment]
The URL launcher is implemented as a platform plugin and each platform has its own format for launching various applications (more than just SMS). The [documentation for iOS](https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/communicating_with_other_apps_using_custom_urls?language=objc) is here. Not sure about Android but @jason-simmons might. There may be an opportunity to abstract this away using a package built on top of the url_launcher plugin.

**Comment by stuartmorgan** [comment]
I think https://pub.dev/packages/flutter_sms handles this use case well.

Since it has platform-specific behaviors rather than an established standard, and the platform behaviors are themselves moving targets, I don't think we want to chase documenting that.
