### ISSUE TITLE
Place icu data into the namespaced assets directory

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#18514]
`icudtl.dat` is currently in assets/ directory in the APK generated by Flutter.  Some apps call the hidden API `addAssetPath` on `AssetManager`. If they happen to do this for an APK that exposes common assets (such as Chrome WebView on Android), the AssetManager might end up returning the wrong ICU. One such case is happening with an internal client and crashing the Flutter engine (Internal bug: b/110084718).

Until we figure out how to reuse ICU data from a different app, we should put this file in a namespace so that we do not clash with other apps.

**Comment by jason-simmons** [comment]
Moved this to `assets/flutter_shared/icudtl.dat` within the APK
