### ISSUE TITLE
[Firebase Auth] Handling provider data causes preventable crash

### ISSUE THREAD

**Issue by dnys1** [flutter/flutter#18513]
I implemented phone number authentication in Swift and it works great, but when I try to then retrieve the user using the `firebase_auth` plugin, it crashes. The issue is on line 21 of `FirebaseAuthPlugin.m` in the method `toDictionary`.

```objective-c
NSDictionary *toDictionary(id<FIRUserInfo> userInfo) {
  return @{
    @"providerId" : userInfo.providerID,
    @"displayName" : userInfo.displayName ?: [NSNull null],
    @"uid" : userInfo.uid,
    @"photoUrl" : userInfo.photoURL.absoluteString ?: [NSNull null],
    @"email" : userInfo.email ?: [NSNull null],
  };
}
```

The method crashes when looping through the provider data with a phone number because, for whatever reason, the main FirebaseAuth sdk returns an object with null uid. See the `_providerData` object (for email provider, this value is equal to the email address):

<img width="375" alt="screen shot 2018-06-11 at 3 22 06 pm 1" src="https://user-images.githubusercontent.com/24740863/41477001-f20bde92-7077-11e8-9f94-2990ce07fe88.png">

When I allow this value to be null, the plugin works fine and I'm able to retrieve the user.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

@Hixie

**Comment by dnys1** [comment]
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.2, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.24.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by cyanglaz** [comment]
This seems to be fixed with a nil check. @dnys1 if you have any related issues, please feel empowered to open another issue with details.

**Comment by kroikie** [comment]
@dnys1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/794. Any further collaboration will be done there.
