### ISSUE TITLE
Need regression tests for aligned TextField input

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#18512]
See https://github.com/flutter/flutter/issues/18483#issuecomment-397658247

> We're going to need regression tests for this in the framework. I can add them.
>
> Verify that flutter/engine#5536 fixed the textfield layout problems.
>
> Issue: #18512

**Comment by justinmc** [comment]
@HansMuller Is this still relevant at all?

**Comment by HansMuller** [comment]
Hard to know for sure. I'll close it, since the issue that triggered the problem is from 2018.
