### ISSUE TITLE
Flutter UI Components plugin or module

### ISSUE THREAD

**Issue by seakleng2016** [flutter/flutter#18529]
it hard to me for switching from native and react native to flutter without native code support . 
example i have applicate need to use it with jwplayer ,but it support only native code.

**Comment by zoechi** [comment]
You can make native features available to Flutter by developing a plugin https://flutter.io/developing-packages/#plugin

**Comment by seakleng2016** [comment]
i see it ,but i don't know how implement UI native code with flutter .
can you give example ?

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/tree/master/examples/flutter_view

**Comment by zoechi** [comment]
Seems this is work in progress
https://github.com/flutter/flutter/issues/73#issuecomment-405667657
This one should be similar to what you need
https://github.com/flutter/plugins/blob/master/packages/video_player/lib/video_player.dart

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/19030#issuecomment-416393456

**Comment by zoechi** [comment]
Did the links help?

**Comment by seakleng2016** [comment]
thank you for that  . but still looking for example source code

**Comment by seakleng2016** [comment]
yes , but still looking for example.

**Comment by seakleng2016** [comment]
look like i found it https://github.com/flutter/flutter/tree/master/examples/flutter_view
but i am not sure it is or not. thank you very much

**Comment by zoechi** [comment]
@seakleng2016 great!
If this is what you were looking for, can this issue be closed then?
