### ISSUE TITLE
some sliver list elements are not painted with a sliver app bar

### ISSUE THREAD

**Issue by ebeem** [flutter/flutter#18527]
## Steps to Reproduce

1. use a custom scroll view and a sliver app bar with a sliver list

gist: https://gist.github.com/ebeem/6f5ce67c51d0817b2acd29f4ec2b0e9d

@liyuqian (38065376fcaf5617715e17bb3a8e51e1eb4a7191)
what I have noticed is that the issue is related to the height of the SliverAppBar
if the height expands to 250, the last 250 height of the sliver list is hidden as well
if the height collapses to 0, all the items are shown

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.5-pre.42, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected devices (1 available)

```

```
```

```
```

**Comment by nonameden** [comment]
I am facing same issue after #18465 
here gif: https://imgur.com/a/HNprC7k

**Comment by jonahwilliams** [comment]
I've reverted that commit in master, should be fixed now.
