### ISSUE TITLE
Add Docker Flutter builders to a suitable container registry.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#18534]
CI solutions that use Docker to run unit tests and build Android artifacts could use a correctly configured Docker container. Configuring and versioning this container is hard (and adding the Android dependency makes the container disgusto gigantic). We should add a Dockerfile and associated post commit hooks to submit versioned contained to a Docker registry.

This came up while attempting to [fix the issue](https://github.com/GoogleCloudPlatform/cloud-builders/issues/292) reported in the cloud-builders repository. A patch that just makes the user [build the container themselves](https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/71) is posted here.

**Comment by godofredoc** [comment]
@chinmaygarde should we close this bug as obsolete?
