### ISSUE TITLE
Remove the acronym "tl;dr" from the API docs.

### ISSUE THREAD

**Issue by gaurav1999** [flutter/flutter#18542]
From URL: https://docs.flutter.io/flutter/widgets/Container-class.html

I was reading documentation it was really well and understandable , but this line on Container Class page under Layout Behavior section's second paragraph which is :- 

"tl;dr: Container tries, in order: to honor alignment,"
I didn't got it , everything was going in simple language and this tl;dr: what it means here ?

**Comment by gaurav1999** [comment]
Yes @Sfshaza , It should be replaced with something more conventional because it's not always a guarantee that everyone will know what is this  , for me personally I thought they might have used some kind of code here😅 , it's not a big issue people can always do google if they don't understand , as the community likes that will be the best. Can you suggest a word to replace it with maybe I can raise a pr based on that ? , Or should I close this issue?

**Comment by Sfshaza** [comment]
In this case, instead of tl;dr, we could use something like the following:

```
The short version:
Container tries, in order: to honor alignment, to size itself to the child, 
to honor the width, height, and constraints, to expand to fit the parent, 
to be as small as possible.

More specifically: 
...
```

I've changed the category of this bug to API docs and the title to be more specific about `tl;dr`. I think that should be sufficient - we don't need a new bug.

@jcollins-g  @gaurav1999

**Comment by Sfshaza** [comment]
Sounds good, @jcollins-g! This topic became a big conversation in the internal writers group. Overall consensus, don't use tl;dr or tldr.

**Comment by gaurav1999** [comment]
@Sfshaza,
I was looking for the website code , so maybe I can try to edit this , but I am little confused I did not find anything in flutter website section of github , one document was there docs.md but it also is not complete , is the website not open sourced ?

**Comment by Sfshaza** [comment]
The website is open sourced. The API docs are part of the source code, so you would need to download the Flutter SDK. The API docs aren't part of the website.

**Comment by gaurav1999** [comment]
I got this mam , that Api docs are not part of the website , but as you said that website is open source then there must be a way to contribute to it as well ?

**Comment by Sfshaza** [comment]
Oh, definitely, @gaurav1999!  You would need to clone the [flutter/flutter](https://github.com/flutter/flutter/) repo. Learn more by reading the [Contribution](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) page.

The API docs are embedded in the source code.

**Comment by goderbauer** [comment]
We currently do not have any more occurrences of "tl;dr" in the code base.
