### ISSUE TITLE
Make iOS keyboard dark when ThemeData brightness is dark

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18540]
Make iOS keyboard dark when ThemeData brightness is dark

**Comment by jonahwilliams** [comment]
It doesn't look like we currently support this setting with out current system chrome api, but we should.

**Comment by lukepighetti** [comment]
What is "current system chrome api" and can I use it to change the keyboard to dark when the theme is dark?

**Comment by jonahwilliams** [comment]
[`SystemChrome`](https://docs.flutter.io/flutter/services/SystemChrome-class.html) is a collection of apis we use to change visual features on the host platform.  You can't use this api to change the keyboard darkness though because we haven't implemented it yet.

**Comment by NiklasPor** [comment]
@lukepighetti Did you find a temporary solution for showing a dark keyboard on iOS in the meantime? 

Developing a dark themed app for iOS is only half as much fun with a white keyboard 😏

**Comment by lukepighetti** [comment]
@NiklasPor I haven't found anything. I was just sorta hoping Flutter team would magically do it for me. 😄 

@jonahwilliams is there any way for me to access the keyboard settings manually 20 days later?

In react-native `<InputField keyboardAppearance="dark"/>`

**Comment by jonahwilliams** [comment]
Sorry for the delay, I have the engine implementation pending here: https://github.com/flutter/engine/pull/5714 and the framework implementation following shortly

**Comment by NiklasPor** [comment]
Thanks a lot @jonahwilliams, you're the real hero here 👍 🚀 Can't wait to build all those beautiful dark UIs 😆

**Comment by lukepighetti** [comment]
Awesome man, great news for the iOS guys. Thank you so much.

**Comment by jonahwilliams** [comment]
This won't actually be usable until the next engine roll, probably early next week

**Comment by lukepighetti** [comment]
What branch will it be on?

**Comment by jonahwilliams** [comment]
master

**Comment by jonahwilliams** [comment]
This should be submitted and implemented for iOS

**Comment by jinfagang** [comment]
@jonahwilliams How to using this feature? I wanna pop up black keyboard on iOS
