### ISSUE TITLE
Custom fonts does not work with Android 8

### ISSUE THREAD

**Issue by gossiks** [flutter/flutter#18544]
Tested on several devices, the same build.
1. Lenovo Tab 3 - Android 6.0.1 - custom font works
2. Samsung J5 - Android 7.0 - custom font works
3. Google Pixel - Android 8.1.0 - **font resets to default**

Font example:
[w.ttf.zip](https://github.com/flutter/flutter/files/2109021/w.ttf.zip)

Flutter version:
Flutter 0.5.4 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 3019ad976d (6 days ago) • 2018-06-11 11:31:25 -0700
Engine • revision d33bbff470
Tools • Dart 2.0.0-dev.60.0.flutter-a5e41681e5

**Comment by zoechi** [comment]
@cbracken

**Comment by flschweiger** [comment]
Also emojis are not displayed on the Android P beta. Tested on a Pixel 2XL.

**Comment by jason-simmons** [comment]
Not sure what's causing this, but it isn't dependent on Android 8 alone.  I can render the attached font with Flutter on a Nexus 5x running Android 8.1.0 (as well as a Moto G4 with Android 7.0)

**Comment by gossiks** [comment]
@cbracken any updates on this issue?

**Comment by gossiks** [comment]
@cbracken @zoechi  any updates?

**Comment by dvdghe** [comment]
@zoechi @cbracken any updates?

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by gossiks** [comment]
@zoechi 
Tested on Flutter (Channel dev, v1.1.4), Google Pixel.
Works well! Issue can be closed as resolved.
