### ISSUE TITLE
Too many required parameters to change Slider ThumbShape

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18550]
I went to change the slider's thumb shape and got a list of about 15 required parameters. I'm not trying to replace existing sliderTheme, just update one value.

<img width="778" alt="screen shot 2018-06-17 at 5 24 31 pm" src="https://user-images.githubusercontent.com/666539/41512241-670004d0-7253-11e8-8add-eeed0a337150.png">

**Comment by lukepighetti** [comment]
Will give it a shot, thank you!

**Comment by gspencergoog** [comment]
What Jonah said should fix your issue.  If not, please reopen it.
