### ISSUE TITLE
[BUG] Navigating back from Navigation push MaterialPageRoute lag

### ISSUE THREAD

**Issue by mitko9000** [flutter/flutter#18559]
Hello I have simple application with multiple pages each one contains a List of elements that are horizontal.

When I navigate back from a page both in Android and iOS I can observe a lag in the animation while closing is this a known issue or I have to do something as a code while a page is closing ?

Any help will be very appreciated because I am trying to use flutter as one project of mine and this is a blocker to me.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by mitko9000** [comment]
@zoechi here it is:
/bin/flutter doctor -v
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E199, locale bg-US)
    • Flutter version 0.4.4 at /Users/dimitari/Downloads/The-10/test/flutter
    • Framework revision f9bb4289e9 (5 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/dimitari/Library/Android/sdk
    • Android NDK at /Users/dimitari/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • CLT L29 • WCR0218428011065 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

**Comment by mitko9000** [comment]
its seems only the default navigation have wrong parameters in the animation I tried with custom transition animation and I cannot reproduce it.

**Comment by zoechi** [comment]
@HansMuller

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
