### ISSUE TITLE
TestPointer changes

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1855]
Driving a pointer in a test right now requires pumping, continually giving the original location, etc.

Instead the API should look something like:

```dart
TestGesture gesture = tester.startGesture(downLocation);
gesture.moveTo(newPoint1);
gesture.moveTo(newPoint2);
gesture.moveTo(newPoint3);
gesture.up(); // or gesture.cancel();
```

moveTo would dispatch a pointer move event with the new point, at downLocation, then pump.

gesture would also expose the TestPointer.

moveTo() would take optional argument "pump: false" or maybe "duration" which is how long to pump (and null would mean don't pump).

**Comment by abarth** [comment]
Sounds good.  Note that we should keep the hit test from the start and re-use it throughout.  Many tests perform new hit tests for move and up, which isn't what happens in real life.
