### ISSUE TITLE
TextFormField with textAlign right but Cursor is in the left

### ISSUE THREAD

**Issue by magnocastro** [flutter/flutter#18555]
I have a TextFormField with attribute `textAlign: TextAlign.right`, but when i run the app, the cursor indicator is on the left only if contains 1 character, for more character the cursor go to right
![capturar](https://user-images.githubusercontent.com/14947820/41515107-dae159ba-7282-11e8-8c59-4fd8d778a5a2.PNG)

![capturar](https://user-images.githubusercontent.com/14947820/41515134-f5ae38d0-7282-11e8-9a65-2f46f1ab4b48.PNG)

**Comment by zoechi** [comment]
somewhat similar to #17625
@Hixie

**Comment by zoechi** [comment]
Probably a dup of #18483 which should be fixed in master after the next engine roll.

**Comment by magnocastro** [comment]
ok

**Comment by jason-simmons** [comment]
Duplicate of https://github.com/flutter/flutter/issues/18483
