### ISSUE TITLE
FlexibleSpaceBar collapse or expanded event

### ISSUE THREAD

**Issue by visualsanity** [flutter/flutter#18567]
I have looked through the documentation for the SliverAppBar / FlexibleSpaceBar widgets for a callback, a state or event to hook into, when the FlexibleSpaceBar is collapse or expanded fully.  I haven't been able to find anything.

What I'm looking for is the ability to change the title field when in a different state.

Am I looking in the right area of the documentation?

[https://stackoverflow.com/questions/50909791/flutter-change-text-when-flexiblespacebar-is-collapsed](https://stackoverflow.com/questions/50909791/flutter-change-text-when-flexiblespacebar-is-collapsed)

**Comment by zoechi** [comment]
@Hixie

**Comment by gunhansancar** [comment]
I think this SliverAppBar component needs more love. 

For the title widget it says it is the primary content when expanded. But if I add paddings etc. and when it collapses it still uses the same widgets and it goes out of the screen. 

And also for the long titles, the text goes out of screen and not wraps properly. 
I'm not sure if anyone is on this widget but it needs more love.

**Comment by jpkontreras** [comment]
now that flutter is getting more traction you guys should focus on solving this issues . <3

**Comment by buddhika-ranasinghe** [comment]
Does anyone has a workaround suggestion for this ?

**Comment by HectorV12** [comment]
Also different background colors for expanded and collapsed states, maybe?

**Comment by hasanzia1993** [comment]
Anything on it yet? Still need something to tell if the flexibleSpaceBar is collapsed or expanded

**Comment by kherel** [comment]
Since the flexibleSpace parameter of SliverAppBar could take any widget. 
Create your own FlexibleSpaceBar widget.

https://stackoverflow.com/a/63407889/5541523

**Comment by pedromassangocode** [comment]
Hi @visualsanity 
Just to make things clear, are you proposing a way to listen for expand/collapse changes?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
