### ISSUE TITLE
GestureDetector onHorizontalDragUpdate doesn't always register

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18563]
Hey guys, I am using `GestureDetector(onHorizontalDragUpdate)` to build a slider that is a star rating system. Unfortunately, it does not always register and thinks that I'm dragging the window up and down slightly.

Here is a screen cap where I am dragging my finger across the device left and right over and over again in an attempt to adjust the star slider.

https://youtu.be/dvuOgvHUo-c

Here is a something which seems to reference this type of issue but I cannot be sure.

https://github.com/flutter/flutter/blob/87445e591311909aaaff5771048a7261b8b4d1cf/packages/flutter/lib/src/gestures/constants.dart#L53-L66

Here is a commit that adjusted these values.

https://github.com/flutter/flutter/commit/87445e591311909aaaff5771048a7261b8b4d1cf#diff-fc6e7bd4a0cd959835d855a2322119acR61

**Comment by zoechi** [comment]
@Hixie

**Comment by lukepighetti** [comment]
As an aside, is there any way for me to override those settings at the project level?

**Comment by lukepighetti** [comment]
I am closing this because I found out that it's a problem of hitSlop, not the gesture detection. Please support #18554
