### ISSUE TITLE
stocks: can double-tap "decrease animation speed", popping entire app

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1856]
STEPS TO REPRODUCE:
1. Open stocks
2. Open menu
3. Double-tap the last menu item.

There are clearly two distinct splashes, and then the main screen is popped off leaving a black screen.

**Comment by Hixie** [comment]
Looks like you can only do this at the start of the app. I'm not sure why.

**Comment by eseidelGoogle** [comment]
IMO we should remove the stocks example at this point, moving its few interesting bits into flutter_gallery.  Filed https://github.com/flutter/flutter/issues/8374  Speculatively closing this year-old bug.
