### ISSUE TITLE
If Expanded is a child of Padding it breaks

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18571]
Broken example 

```
class UserText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(10.0),
      child: Expanded(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text("@username",
              style: TextStyle(
                fontSize: 24.0,
                fontWeight: FontWeight.w500
              )
            ),
            Text("I love tokenized assets, this is probably too long!",
              overflow: TextOverflow.clip,
              softWrap: true,
              style: TextStyle(fontSize: 18.0)
            )
          ],
        )
      )
    );
  }
}
```

Working example
```
class UserText extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Padding(
        padding: EdgeInsets.all(10.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text("@username",
              style: TextStyle(
                fontSize: 24.0,
                fontWeight: FontWeight.w500
              )
            ),
            Text("I love tokenized assets, this is probably too long!",
              overflow: TextOverflow.clip,
              softWrap: true,
              style: TextStyle(fontSize: 18.0)
            )
          ],
        )
      )
    );
  }
}
```

**Comment by zoechi** [comment]
What does "it breaks" mean exactly?
Can you please also add the output of `flutter doctor`?

**Comment by lukepighetti** [comment]
Padding parent of Expanded

<img width="314" alt="screen shot 2018-06-18 at 11 58 30 am" src="https://user-images.githubusercontent.com/666539/41549289-5beaea92-72f3-11e8-81db-f3b0c364b885.png">


Expanded parent of Padding

<img width="335" alt="screen shot 2018-06-18 at 12 10 20 pm" src="https://user-images.githubusercontent.com/666539/41549305-65b235c6-72f3-11e8-93dc-5792e7671369.png">

**Comment by zoechi** [comment]
Adding the output of `flutter doctor` is requested in the issue template and it's always a good idea to do so ;-)

**Comment by lukepighetti** [comment]
```
Lukes-iMac:~ lukepighetti$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.0.0-unknown, on Mac OS X 10.13.5 17F77, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✗] Android Studio (not installed)
[!] VS Code (version 1.24.1)
[✓] Connected devices (2 available)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment]
@HansMuller

**Comment by RedBrogdon** [comment]
I don't believe `Expanded` is meant to work when it isn't a direct descendant of `Row`, `Column`, or `Flex`. From the DartDoc:

> Using an Expanded widget makes a child of a Row, Column, or Flex expand to fill the available space in the main axis (e.g., horizontally for a Row or vertically for a Column). If multiple children are expanded, the available space is divided among them according to the flex factor.

If you look at the yellow text in the red widgets in that screenshot, I believe that's what it's telling you (should also be in the logs).

**Comment by lukepighetti** [comment]
Sounds like a won't-fix? :)

**Comment by HansMuller** [comment]
@RedBrogdon  is correct, the framework is working as intended in this case. It's doing its best to tell you that Expanded must be a child of a Row, Column, or Flex.

**Comment by Hixie** [comment]
FWIW, the message is displayed (more readably) in the console, too.
If the message wasn't clear, please let me know.

**Comment by Wissperwind** [comment]
So, one question: If I am not allowed to use Expanded() in a padding widget, how can I expand my Row inside a padding Widget?

**Comment by lukepighetti** [comment]
I got a notification on this for some reason and I just want to confirm that this definitely is working as expected and should be left closed.
