### ISSUE TITLE
Can't archive iOS app when Swift plugins are used

### ISSUE THREAD

**Issue by flschweiger** [flutter/flutter#18578]
I'm working on an app which uses the `geolocation 0.2.1` Swift plugin and the `cloud_firestore 0.7.3`. The app compiles without an error when deploying to the simulator or an connected iOS device. However, when I try to 'archive' the app in order to upload it to the AppStore, I get the following error message `'cloud_firestore/CloudFirestorePlugin.h' file not found`.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.4, on Mac OS X 10.13.5 17F77, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
[!] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

I'm using Cocoapods 1.5.3.

Podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by flschweiger** [comment]
Also tried with the current master but still the same problem:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.27, on Mac OS X 10.13.5 17F77, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
[✓] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

• No issues found!
``` 

Did no one else face this problem?

**Comment by zoechi** [comment]
@Hixie

**Comment by passsy** [comment]
I canreproduce it. Here is what I did

1. Create project:
```
> flutter create flutter_geo_release_bug
> cd flutter_geo_release_bug
```

2. add `geolocation: 0.2.1` and `cloud_firestore 0.7.3` dependency followed by `flutter pacakges get`
3. Adjust signing in Xcode
4. [Set `SWIFT_VERSION`](https://stackoverflow.com/a/47530482/669294) to `3.2`
4. Create release `flutter build ios --release`

Error:

```
Building net.grandcentrix.flutterGeoBug for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: JCPY7FXGR4
Running pod install...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    /Users/pascalwelsch/.pub-cache/hosted/pub.dartlang.org/geolocation-0.2.1/ios/Classes/GeolocationPlugin.m:7:9: fatal error: 'geolocation/geolocation-Swift.h' file not found
    #import <geolocation/geolocation-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Encountered error while building for device.
```

**Comment by passsy** [comment]
Found the root cause: By default flutter generates an Objective-C iOS project. Integration Swift dependencies isn't straight forward. By generating a Swift project, the procedure above works flawless.

1. Create project:
```
> flutter create -i swift flutter_geo_release_bug
> cd flutter_geo_release_bug
```

2. add `geolocation: 0.2.1` and `cloud_firestore: 0.7.3` dependency followed by `flutter pacakges get`
3. Adjust signing in Xcode
4. Create release `flutter build ios --release`
5. Select "Generic iOS Device"
6. Product > Archive > Success 🎉

---

I don't know if it's possible to convert an Objective-C project to a Swift project but you'll find a way @flschweiger

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/13422#issuecomment-392133780

**Comment by flschweiger** [comment]
Thanks for all your effort @passsy 😃 Unfortunately that's not the issue. I already have a Swift initialised project with a valid ```AppDelegate.swift``` file. Also created a clean Flutter project and copied everything over - still the same issue 😔

**Comment by xster** [comment]
cc @mravn-google, @collinjackson

**Comment by mravn-google** [comment]
@flschweiger Does your project contain an `ios/Podfile` which is different from [the one brought by Flutter tooling](https://raw.githubusercontent.com/flutter/flutter/master/packages/flutter_tools/templates/cocoapods/Podfile-swift)?

**Comment by flschweiger** [comment]
@mravn-google I have set the global platform to 9.0 by uncommenting the second line in the default podfile (which is a requirement for the geolocation library). Otherwise I didn't change anything.

If needed I can also provide access to the repo.

**Comment by flschweiger** [comment]
Any update on this? This also fails when I create a new objective c project which uses Swift plugins (in this case, the geolocation plugin which requires iOS 9 and the Firestore).

**Comment by flschweiger** [comment]
Finally found the issue, it was my fault 🙈 I had opened the `Runner.xcodeproj` instead of the `Runner.xcworkspace` file - as an Android developer I didn't know that there was a difference between those two when opened in Xcode.

**Comment by flschweiger** [comment]
Finally found the issue, it was my fault 🙈 I had opened the Runner.xcodeproj instead of the Runner.xcworkspace file - as an Android developer I didn't know that there was a difference between those two when opened in Xcode.

**Comment by trey-rosius** [comment]
After implementing the steps mentioned by @passy, the first 3 app builds went on without a hassle, then after that, back to this.
/Users/rosius/flutter/.pub-cache/hosted/pub.dartlang.org/geolocation-0.2.1/ios/Classes/GeolocationPlugin.m:7:9: fatal error: 'geolocation/geolocation-Swift.h' file not found
    #import <geolocation/geolocation-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The files for my project are too many. 
Please i desperately need your help on this.

**Comment by flschweiger** [comment]
@trey-rosius Did you open the workspace file instead of the project file?
