### ISSUE TITLE
Failed evaluation expressions are written to stderr of `flutter run` and then exposed to users in Dart Code

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#18574]
I don't know if this is intended, but when I use `evaluateInFrame` with expressions in the Watch window, if the expression fails (eg. because the expression is from another stack frame or different location) the errors are written to stderr of the `flutter run` process:

```
[19:10:04] [FlutterRun] ERR compiler message: ^^^^
compiler message: org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'test' isn't defined for the class '#lib1::StatelessElement'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'test'.
compiler message: test
compiler message: ^
```

Currently in VS Code we route stderr back to the users debug console so if something goes wrong with the process they can see (rather than it just looking like we hung). It's confusing for a user to see all these errors shown on their screen and they're expected to sometimes fail (the watch window will evaluate all of its expressions on every break).

Are these expected here, or should editors not show stderr from processes like `flutter run` to the user?

(cc @devoncarew)

**Comment by aam** [comment]
If I understand correctly, compilation diagnostic for expression evaluation is treated same way as diagnostic for whole program compilation(during hot reload, for example) - it goes to the stdout prefixed with `compiler message:`
How does VSCode handle compilation diagnostic?

**Comment by DanTup** [comment]
Currently we just show stderr from anywhere in the debug console:

![errors](https://user-images.githubusercontent.com/1078012/41586856-ad8e5ade-73a5-11e8-9822-c9f2841c965f.png)

This probably makes sense if it's compilation during startup or a hot reload because it's an important error the user should see. However if we're just evaluating expressions for the VM service API for the Watch window, we don't want this - the watch window is going to cause loads of failures because it's evaluated on every break and often contains local variables that aren't valid. The user already knows these variables can't be viewed because they show an error/message inside the watch window.

Is there a benefit to showing these in stderr (the evaluation ones) when an error is already provided in the VM service response?

**Comment by DanTup** [comment]
I just checked in Android Studio and the same happens here. I'm not show how common it is to use the debug Console there (it's very common in VS Code, it's where a lot of important stuff goes) but it also shows all of the Watch variables evaluation failures:

<img width="1182" alt="screen shot 2018-06-19 at 9 53 34 am" src="https://user-images.githubusercontent.com/1078012/41587291-c36f189c-73a6-11e8-8b8e-74f4f31f19aa.png">

I'm guessing this probably didn't happen with the old expression evaluation.

**Comment by DanTup** [comment]
Ok, this is even worse than I thought... In VS Code we support evaluating expressions on hover. This means you can cursor a variable and a tooltip will show its value. Of course, we don't know what is valid to evaluate, so VS Code calls this a LOT as the user moves their mouse around. 

For example, I moved my mouse over this code:

```
 child: new Container(
            padding: const EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 20.0),
            decoration: new BoxDecoration(
```

and VS Code sent an evaluate request for `"padding"`. This caused the following to show up in the debug console:

```
compiler message: d3161c64-aa88-4b76-977c-887a595157cb build/app.dill.incremental.dill 13
compiler message: org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'padding'.
compiler message: padding
compiler message: ^^^^^^^
compiler message: org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'padding' isn't defined for the class '#lib1::StockRow'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'padding'.
compiler message: padding
compiler message: ^
```

**Comment by devoncarew** [comment]
> compilation diagnostic for expression evaluation is treated same way as diagnostic for whole program compilation

I think we need to change this - IDEs to lots of expr eval, much of it very speculative (i.e. a watch windows contents isn't expected to be valid for most stack frames). @aam (or, @mraleph and @a-siva), who's the best person to look at this?

**Comment by aam** [comment]
Do we want to come up with better way to communicate compilation errors from flutter to IDE plugin?
I don't think we just want to silent expression evaluation diagnostic, because supposedly user does want to see errors in an expression user typed in Watch window.

**Comment by devoncarew** [comment]
I believe we should be getting an Error reference back (https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#evaluate). I assume tools could then choose to show or hide the result of the eval, depending on whether the user can explicitly requested the eval, or it was some more speculative eval from the UI.

**Comment by DanTup** [comment]
Yeah, we're getting an error response back in the API. It's just also in addition being written to stderr. This may make sense when the evaluate request didn't come from the API (eg. compilation, hot reload) I'm not sure, but here it feels wrong (and we never used to get this).

**Comment by DanTup** [comment]
While testing this I still got compiler output on stderr, but it's a different error ([possibly also mentioned here](https://github.com/flutter/flutter/pull/18591#issuecomment-398795191)). I'll re-test once that's resolved.

```
[08:20:47]: <== [{"id":"2","result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.showPerformanceOverlay"}}]
[08:20:47]: <== [{"id":"1","result":{"enabled":"false","type":"_extensionType","method":"ext.flutter.debugPaint"}}]
[08:20:57]: ERR compiler message: Unhandled exception:
[08:20:57]: ERR compiler message: NoSuchMethodError: The getter 'loader' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: loader
compiler message: #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
compiler message: #1      IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:429)
compiler message: <asynchronous suspension>
compiler message: #2      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118)
compiler message: #3      new Future.sync (dart:async/future.dart:222)
compiler message: #4      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118)
[08:20:57]: ERR 
compiler message: #5      _rootRun (dart:async/zone.dart:1126)
compiler message: #6      _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #7      _runZoned (dart:async/zone.dart:1518)
compiler message: #8      runZoned (dart:async/zone.dart:1465)
```
