### ISSUE TITLE
Many issues with Services and Gradle

### ISSUE THREAD

**Issue by voidrealms** [flutter/flutter#18579]
Installed the google auth plugin

https://pub.dartlang.org/packages/google_sign_in#-installing-tab-
Works as expected (at least it compiled)
```
Installed the Flutter auth plugin
https://pub.dartlang.org/packages/firebase_auth
Does not compile, complains it needs Gradle 4.0
Fixed that by opening the project in android studio, but now...

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[15.0.4,15.0.4]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.0,16.0.0]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Finished with error: Gradle build failed: 1
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`.

**Comment by zoechi** [comment]
cc @Hixie

**Comment by voidrealms** [comment]
My results from flutter doctor

rootshell@rootshell-desktop ~ $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.


-----------------------------

One confusing part is...

firebase_auth wants:
  classpath 'com.android.tools.build:gradle:3.1.2'
  classpath 'com.google.gms:google-services:3.2.1'

But also requires google signin which wants (during the firebase registration process)
classpath 'com.android.tools.build:gradle:3.0.1'
classpath 'com.google.gms:google-services:4.0.0'

I'll redo the directions from the start and post the results.

**Comment by MStanoevich** [comment]
Found somewhat of a fix:
Removing/commenting out this line from the app level build.gradle 
`compile 'com.google.firebase:firebase-core:16.0.0'`

From what I've seen most people do not add this line, though it was part of the instructions when I was setting up my firebase android project.

**Comment by voidrealms** [comment]
I set the distributionUrl in /home/rootshell/Code/Flutter/firebaseauth/android/gradle/wrapper/gradle-wrapper.properties to gradle-4.4-all.zip

----------------------------------------------------------
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[15.0.4,15.0.4]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.0,16.0.0]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle build failed: 1
----------------------------------------------------------

**Comment by voidrealms** [comment]
in the project build.gradle i commented out "com.google.gms:google-services:4.0.0" and it compiled.
Will try to find time to actually test the code.

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        //classpath 'com.google.gms:google-services:4.0.0' // - THIS caused the issue in compiling

        // Example existing classpath
        classpath 'com.android.tools.build:gradle:3.1.2'
        // Add the google services classpath
        classpath 'com.google.gms:google-services:3.2.1'
    }

**Comment by voidrealms** [comment]
tested and verified the code works after going through the above steps, i will make a youtube video and post it out later if I have time.

**Comment by voidrealms** [comment]
Step by step on how this was resolved:
https://youtu.be/bROui4ID9_Q

**Comment by yashthakkar1173** [comment]
I have the same issue with firebase but it solved please refer this link for more details!

**Comment by praveen-francium** [comment]
> Step by step on how this was resolved:
> https://youtu.be/bROui4ID9_Q

keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
java.io.IOException: Keystore was tampered with, or password was incorrect
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1048)
	at java.base/sun.security.tools.keytool.Main.run(Main.java:397)
	at java.base/sun.security.tools.keytool.Main.main(Main.java:390)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778)
	... 5 more
@voidrealms I got this error .could you help me overcome this.

**Comment by zoechi** [comment]
@praveen-francium Have you tried without a password?

**Comment by praveen-francium** [comment]
> @praveen-francium Have you tried without a password?
> 
> Btw. `keytool` is not Flutter specific and is probably better to ask on StackOverflow or similar.

@zoechi without password works.Thanks!!!

**Comment by aliiezzeddine** [comment]
* Error running Gradle:
ProcessException: Process "C:\Users\Dell\Documents\Flutter\Flutter\fluttergoogle\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Dell\Documents\Flutter\Flutter\fluttergoogle\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: C:\Users\Dell\Documents\Flutter\Flutter\fluttergoogle\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

how to solve it ?

**Comment by kroikie** [comment]
@voidrealms

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1123. Any further collaboration will be done there.
