### ISSUE TITLE
TextTheme docs should link to material.io

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#18580]
The material.io web site has a good description of the various text theme values.  We should link to it from the TextTheme docs:

https://material.io/design/typography/the-type-system.html

**Comment by zoechi** [comment]
Duplicate of #19060 

PR #26807 to fix it waiting to be merged.

**Comment by johnsonmh** [comment]
Looks like this was fixed in https://github.com/flutter/flutter/pull/26807, `text_theme.dart` now links to [material.io/design/typography](http://material.io/design/typography).
