### ISSUE TITLE
Follow up with Skia on a GN target for Skia that includes no inbuilt image codecs.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#18582]
Subtask of https://github.com/flutter/flutter/issues/17356. Tracking issue on the Skia tracker is filed here https://bugs.chromium.org/p/skia/issues/detail?id=8076.

**Comment by chinmaygarde** [comment]
Skia now exposes the necessary APIs to interface with [platform image generators](https://bugs.chromium.org/p/skia/issues/detail?id=8076).

**Comment by kf6gpe** [comment]
Looks like the underlying Skia dependency is still open as I retriage some older bugs.

**Comment by kf6gpe** [comment]
Upstream dependency is closed. Giving this a P4.

**Comment by jonahwilliams** [comment]
We have the ability to do this with SLIMPELLER on now
