### ISSUE TITLE
Close the application when connecting with fire base and not pick up the data. This only happens with a given, in other normal query.

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#18587]
memory near r1:
00006750 ffffffff ffffffff ffffffff ffffffff
00006760 ffffffff ffffffff ffffffff ffffffff
00006770 ffffffff ffffffff ffffffff ffffffff
00006780 ffffffff ffffffff ffffffff ffffffff
00006790 ffffffff ffffffff ffffffff ffffffff
000067a0 ffffffff ffffffff ffffffff ffffffff
000067b0 ffffffff ffffffff ffffffff ffffffff
000067c0 ffffffff ffffffff ffffffff ffffffff
000067d0 ffffffff ffffffff ffffffff ffffffff
000067e0 ffffffff ffffffff ffffffff ffffffff
000067f0 ffffffff ffffffff ffffffff ffffffff
00006800 ffffffff ffffffff ffffffff ffffffff
00006810 ffffffff ffffffff ffffffff ffffffff
00006820 ffffffff ffffffff ffffffff ffffffff
00006830 ffffffff ffffffff ffffffff ffffffff
00006840 ffffffff ffffffff ffffffff ffffffff

memory near r6:
00006750 ffffffff ffffffff ffffffff ffffffff
00006760 ffffffff ffffffff ffffffff ffffffff
00006770 ffffffff ffffffff ffffffff ffffffff
00006780 ffffffff ffffffff ffffffff ffffffff
00006790 ffffffff ffffffff ffffffff ffffffff
000067a0 ffffffff ffffffff ffffffff ffffffff
000067b0 ffffffff ffffffff ffffffff ffffffff
000067c0 ffffffff ffffffff ffffffff ffffffff
000067d0 ffffffff ffffffff ffffffff ffffffff
000067e0 ffffffff ffffffff ffffffff ffffffff
000067f0 ffffffff ffffffff ffffffff ffffffff
00006800 ffffffff ffffffff ffffffff ffffffff
00006810 ffffffff ffffffff ffffffff ffffffff
00006820 ffffffff ffffffff ffffffff ffffffff
00006830 ffffffff ffffffff ffffffff ffffffff
00006840 ffffffff ffffffff ffffffff ffffffff

memory near r8:
6c3cdbb4 bf00bd70 00658edd 006b79d6 f7feb580
6c3cdbc4 4902ff05 31084479 bd806001 00c30534
6c3cdbd4 bc3ef7f6 0a07ed90 2a09ed90 1a08ed90
6c3cdbe4 3a0aed90 2a02ee30 0a03ed80 3a03ee31
6c3cdbf4 1a04ed80 2a05ed80 3a06ed80 b5b04770
6c3cdc04 460db082 e9d44604 4668230c f00168e9
6c3cdc14 9800fc27 6802b128 68936829 020cf104
6c3cdc24 98014798 f20cb108 b002f09c 0000bdb0
6c3cdc34 f7fdb580 4902ffb1 31084479 bd806001
6c3cdc44 00c304d8 41f0e92d 4605b08e 0810f10d
6c3cdc54 0628f105 4611460c 46324640 ff1af068
6c3cdc64 0050efc0 4628466f 46424621 f947463b
6c3cdc74 f7fe0acf 4630f823 463a4639 fd05f069
6c3cdc84 0acff967 000cf105 0a8ff940 e8bdb00e
6c3cdc94 000081f0 b087b5f0 48224605 460c4e22
6c3cdca4 447e4478 f0044631 2020f815 f5aaf221

memory near ip:
6d14622c 6c9f0b8d 00000000 6d146254 6c235220
6d14623c 6d146254 6d146268 6ca84a3e 740e22d8
6d14624c 6d146678 6c9f0c51 6ca84a3e 6d146268
6d14625c 6ca84862 6c9f779d 00000400 3a647473
6d14626c 6461623a 6c6c615f 6d00636f 6c3cdbd5
6d14627c 00000000 00000000 40330000 40a0a3d6
6d14628c 40a7ae14 00000000 414c7ae1 4240b852
6d14629c c183ae15 00000000 00000000 00000000
6d1462ac 00000000 00000000 00000000 00000000
6d1462bc 00000000 00000000 00000000 00000000
6d1462cc 00000000 00000000 00000000 00000000
6d1462dc 00000000 00000000 00000000 00000000
6d1462ec 00000000 00000000 00000000 00000000
6d1462fc 00000000 00000000 00000000 00000000
6d14630c 00000000 00000000 00000000 00000000
6d14631c 00000000 00000000 00000000 00000000
memory near sp:
6d146180 0000004b 6c235218 6c235220 400e993f
6d146190 400e98c5 0000004a 00000000 6d146238
6d1461a0 00000006 0000000c 00006773 6d14624c
6d1461b0 6d14624c 400eb145 00000006 0000004a
6d1461c0 6ca84916 400eb359 6d1461d4 400ea025
6d1461d0 ffff4208 ffffffdf 0000007f 00000003
6d1461e0 00000000 68000101 00000000 6ca84990
6d1461f0 0000004a 400f98f0 16bbcc21 400eab75
6d146200 401183a7 6d146214 0000004a 400ea085
6d146210 401183a7 6ca84916 0000004a 6ca84990
6d146220 6c235220 0000004a 6ca84990 6c9f0b8d
6d146230 00000000 6d146254 6c235220 6d146254
6d146240 6d146268 6ca84a3e 740e22d8 6d146678
6d146250 6c9f0c51 6ca84a3e 6d146268 6ca84862
6d146260 6c9f779d 00000400 3a647473 6461623a
6d146270 6c6c615f 6d00636f 6c3cdbd5 00000000
code around pc:
400fa018 e8bd00f0 e3700a01 912fff1e e2600000
400fa028 ea006ef6 e92d50f0 e3a07f43 ef000000
400fa038 e8bd50f0 e3700a01 912fff1e e2600000
400fa048 ea006eee e92d50f0 e3a070ee ef000000
400fa058 e8bd50f0 e3700a01 912fff1e e2600000
400fa068 ea006ee6 e1520003 8a00008c f5d1f040
400fa078 e92d4001 e3520010 3a000024 e2603000
400fa088 e213300f 0a00000e e0422003 e1b0cf83
400fa098 44d1e001 44c0e001 24d1c001 24d1e001
400fa0a8 24c0c001 24c0e001 e1b0ce83 aa000001
400fa0b8 f4a1030d f480031d 3a000001 f421070d
400fa0c8 f400071d e2522040 3a000006 f421020d
400fa0d8 f421420d f5d1f100 e2522040 f400022d
400fa0e8 f400422d 2afffff8 e2922020 3a000002
400fa0f8 f421020d e2422020 f400022d e2822020
400fa108 e3120010 0a000001 f4210a0d f4000a2d

code around lr:
400eb124 447b4b13 42b3e010 4812d10e 44786a1e
400eb134 ec60f7fb e9b2f00d 46224631 ef74f00e
400eb144 d00a3001 e00b2400 2b00681b 480ad1eb
400eb154 44782403 ec4ef7fb f001e002 6804f9f7
400eb164 f9f4f001 46206005 bf00bd70 0003b282
400eb174 0003b276 0003b26e 0003b24a bf7ef7ff
400eb184 43f0e92d 4a3d4b3c 589c447b 6823b08b
400eb194 460d4606 f0019309 46a1f9d9 8000f8d0
400eb1a4 d0482d00 f00f4628 280ffe49 d8444604
400eb1b4 ffe4f7ff d1064286 4629200f e87cf00d
400eb1c4 d03c2800 482ee02e f7fb4478 482deb92
400eb1d4 e0154478 d11342b0 482b6a06 f7fb4478
400eb1e4 4a2aec0a 447a2120 a8014633 fa3af013
400eb1f4 a8012101 fd38f01a 46061c42 e011d104
400eb204 28006800 e02cd1e6 46294630 f00d4622
400eb214 1c43e8b8 d11e4607 f998f001 29046801
!@dumpstate -k -t -z -d -o /data/log/dumpstate_app_native -m 26462
Lost connection to device.
Exited 

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

• No issues found!

**Comment by giovannilima262** [comment]
After to use "FirebaseAnimatedList" in other screen, my request in other screen occurs for a while, after show this in my console.

**Comment by zoechi** [comment]
cc @Hixie can you make sense of this information?

**Comment by Hixie** [comment]
This looks like a small segment of a long crash report. @giovannilima262 Can you see if there's more to the logs that you could provide? As described there's not much we can do here.
