### ISSUE TITLE
Touch AppBar to scroll home does not have acceleration in iOS

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18586]
On iOS when you tap the AppBar to scroll to home it does so with an amount of jerk (acceleration curve). Flutter appears to scroll up with a constant velocity. This makes the app look non-native.

**Comment by zoechi** [comment]
@HansMuller

**Comment by lukepighetti** [comment]
In fact, in playing around with it more, none of the navigation has the proper acceleration. Drawers and scroll up are all constant velocity.

For some reason I thought Flutter was exposing UIKit to us like React-Native does, but I see that is not the case. It is a bit disappointing then that the UI, even with material design, does not feel like a native app. This may seem like a small thing but it is very noticeable.

**Comment by lukepighetti** [comment]
Is there any way to expose the acceleration curves that Flutter uses on iOS so I can play with them?

**Comment by jonahwilliams** [comment]
@lukepighetti are you comparing the behavior to native in a debug build or a release/profile build?

**Comment by lukepighetti** [comment]
profile build

**Comment by lukepighetti** [comment]
Ah sorry, I misspoke earlier. When I said Drawer I meant the back/next screen as achieved through routing.

**Comment by jonahwilliams** [comment]
That would be the CupertinoPageRoute class, and it's related CupertinoPageTransition class that it constructs.

**Comment by lukepighetti** [comment]
Hang on, I think I might be learning something. So if you use Material scaffold on iOS it's supposed to feel like Android? It will only feel like iOS if you're using Cupertino scaffold? I am using Material on iOS.

**Comment by jonahwilliams** [comment]
The MaterialPageRoute is designed to be adaptive based on the platform, though you could override this by changing the `platform` of the provided Theme

https://github.com/flutter/flutter/blob/09276bea258737e11b109e227f70eac94a4e1691/packages/flutter/lib/src/material/page.dart#L171

**Comment by lukepighetti** [comment]
OK. Well, in that case, then I would (as before) expect Flutter, in Material or Cupertino, to have the iOS style acceleration for page animation and scroll to home (tap on AppBar), and it is currently not that way. :)

**Comment by lukepighetti** [comment]
Hi! Congrats on today's event.

Yes, there is. If you tap the status bar on iOS when a list view is available, it scrolls to top with a linear speed. I believe iOS uses some custom animation curve.

**Comment by TahaTesser** [comment]
Hi @lukepighetti 
Does this issue still exist with latest stable?

If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
