### ISSUE TITLE
When offline google_sign_in still does online dependency check before building, which fails the build

### ISSUE THREAD

**Issue by AshSimmonds** [flutter/flutter#18594]
https://github.com/Microsoft/vscode/issues/52106#issuecomment-398321696

It won't build the APK because before it even tries the build it does a dependency check online - which of course fails.

Huh, thought I posted a screenshot originally, sorry. I'll do it again... Right, just re-enabled it in the pubspec.yaml file, switched off interwebs, and problem returns:

![20180619181244_screenshot](https://user-images.githubusercontent.com/9034041/41591661-ed5c5c28-73ec-11e8-81a9-afedd2a3c043.png)

Dunno if it's a VSCode problem or the extension specifically, but I'll cross-post and let the devs figure it out.

Text in case anyone else is searching:

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
> Could not determine artifacts for com.google.firebase:firebase-core:12.0.1
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/12.0.1/firebase-core-12.0.1.aar'.
      > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-core/12.0.1/firebase-core-12.0.1.aar'.
         > dl.google.com
```

**Comment by zoechi** [comment]
The `pubspec.yaml` at the top of the screen looks weird. Can you please post the whole content as text (not as screenshot)?
How do you use "offline"?

**Comment by AshSimmonds** [comment]
The pubspec.yaml file is fine AFAIK, it's only when google_sign_in is enabled and the computer is offline that problems occur.

I posted the error as text above.

It's easy to reproduce - at least on my setup - just add google_sign_in to your pubspec, then turn off your internet and try to build/"play" your project.

It works just fine when the internet is on, but when off it can't reach the dependency endpoints and crashes the entire build process.

**Comment by zoechi** [comment]
@AshSimmonds the part that is visible in the screenshot looks invalid to me.

**Comment by zoechi** [comment]
Can you please try adding the `--offline` option?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by AshSimmonds** [comment]
Ok thanks - I haven't checked on whether it's an issue for a couple months,
I'll request re-open if I run into it again.

**Comment by zoechi** [comment]
@AshSimmonds sure, don't hesitate to add a comment here or create a new issue if you run into it again.
