### ISSUE TITLE
Handle onResume when page come back from another page in flutter.

### ISSUE THREAD

**Issue by vithanichandresh** [flutter/flutter#18596]
how i call my method in resume method.

whene i come back from another page then resume state was not called in first page.

in this situation which state will call?

**Comment by zoechi** [comment]
What "another page" are you referring to? Another app?
Perhaps you're looking for 

https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver-class.html

or 

https://flutter.io/flutter-for-android/#how-do-i-handle-incoming-intents-from-external-applications-in-flutter

**Comment by vithanichandresh** [comment]
i have twio page in my app.
one homepage and second my account.
i need to call webservices in on resume of homepage.
but the problem is whene i back from myaccount onresume method not call.
at that situation which state is call ?

**Comment by zoechi** [comment]
I see. Then https://docs.flutter.io/flutter/widgets/RouteObserver-class.html might do what you want (haven't tried myself yet)

**Comment by vithanichandresh** [comment]
simple,
i have a button in home page.
by click that i start my account page using rout.
in home page resumed state i call some api to get data.
now whene i press back icon in myaccount it comes in home page but in home page resumed state was not called.

**Comment by zoechi** [comment]
I assume this is solved. 
Feel free to create a new issue if not.

Please consider asking support questions in one of the channels http://flutter.io/support .

**Comment by kentoapps** [comment]
I have same issue and cannot solve it.
If anyone knows the solution, please let me know.

I have screen A and B.
[A] `Navigator.push(context, MaterialPageRoute(builder: (context) => B())); `
      -> then it goes the screen B.
[B] `Navigator.pop(context) or press back button`
      -> then it goes back the screen A.
[A] I wanna do something when it comes back screen A but `didChangeAppLifecycleState` is not called...

**Comment by kentoapps** [comment]
I don't know it's the best way but I found a solution.
I'm doing this on screen A.
```
onPress: () async {
  await Navigator.push(context, MaterialPageRoute(builder: (context) => B()));
  // do what you want here
},
```

**Comment by ayinmursalin** [comment]
why there are so much idiot comment.

i have the same problem, means
I NEED TO HANDLE WHEN USER PRESS "Back button on Android Device in SECOND PAGE", so that i can refresh my FIRST PAGE.

if you commant Push and Pop i already know that shit, IDIOT

**Comment by patelkrunal78** [comment]
Very Similar to [onResume() and onPause() for widgets on Flutter](https://icetutor.com/question/onresume-and-onpause-for-widgets-on-flutter)

**Comment by sunilbcit** [comment]
Is there any one with the solution? caz i have same problem.

**Comment by ayinmursalin** [comment]
@sunilbcit i have another option. Navigator.push() is return a Future<dynamic>, that is the result you send back from Navigator.pop(context, arrayOfResult);

Example.
Detail Screen
`Navigator.pop(context, [1]);`
or, if you don't want to send back any data, you can only call
`Navigator.pop(context);`

Main Screen
```
Navigator.push(
  context,
  MaterialPageRoute(
    builder: (context) => DetailPage(),
  ),
).then((value) {
  debugPrint(value);
  _reload();
});
```

so `_reload();` method will be called after back/pop from DetailPage

**Comment by sunilbcit** [comment]
@ayinmursalin Thanks It works.
