### ISSUE TITLE
date picker overlay not removed when date is selected

### ISSUE THREAD

**Issue by Fenilsmiley** [flutter/flutter#18598]
open Date picker on textFormField's listener Flutter, when i click on birthday textFormField ,open date picker but i select date & then press ok , that time not remove date picker dialogue , 2 or 3 time press ok then remove date picker dialog successfully. i need help for 1 time press ok & remove datepicker dialogue.

```dart
import 'dart:async';

import 'package:connectivity/connectivity.dart';
import 'package:flutter/material.dart';
import 'package:flutter_statusbarcolor/flutter_statusbarcolor.dart';

class EditAccountScreen1 extends StatefulWidget {
  @override
  _EditAccountScreenState createState() => _EditAccountScreenState();
}

class _EditAccountScreenState extends State<EditAccountScreen1> {
  String _birthday;

  changeStatusColor(Color color) async {
    await FlutterStatusbarcolor.setStatusBarColor(color);
  }

  final TextEditingController _birthdayController = new TextEditingController();
  DateTime _date = new DateTime.now();

  @override
  void initState() {
    super.initState();

    _birthdayController.addListener(_selectDate);
  }

  @override
  void dispose() {
    super.dispose();
    _birthdayController.removeListener(_selectDate);
    _birthdayController.dispose();
  }

  _EditAccountScreenState() {
    changeStatusColor(Colors.myColor);
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          title: new Text("Edit Account"),
        ),
        body: new Stack(fit: StackFit.expand, children: <Widget>[
          new Form(child: new Theme(data: new ThemeData(
            primaryColor: Colors.myColor,
            textSelectionColor: Colors.myColor
          ), child: new Container(
            child: new Column(
              children: <Widget>[
                new TextFormField(
                    controller: _birthdayController,
                    decoration: new InputDecoration(
                      labelText: "Birthday",
                    )),
                new Padding(padding: new EdgeInsets.only(top: 15.0)),
                new MaterialButton(
                  child: new Text("SAVE"),
                    color: Colors.myColor,
                    textColor: Colors.white,
                    onPressed: () => {})
              ],
            ),
          )))
        ]));
  }

  Future<Null> _selectDate() async {
    final DateTime picked = await showDatePicker(
        context: context,
        initialDate: _date,
        firstDate: new DateTime(1918),
        lastDate: new DateTime.now());

    if (picked != null) {
      print("Date Selected $_date");
      setState(() {
        _date = picked;
        _birthdayController.text = picked.toString();
      });
    }
  }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by Fenilsmiley** [comment]
D:\PROJECTS\Flutter\central_pos_flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.15063], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!

**Comment by Fenilsmiley** [comment]
i upgraded flutter. But same issue.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.15063], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!

when _selectDate method called on Button onPressed that times completely remove date picker overlay and also set value in TextFormField,
but i take _selectDate method called on TextFormField Listener & set value in this TextFormField that time not remove datepicker overlay.

exactly issue is that, TextFormField listener per open datepicker but i select date & press ok that time remove date picker overlay & instant 2nd time automatically open date picker. all time remove datepicker & automatic open datepicker.

**Comment by zoechi** [comment]
Thanks for the update.

**Comment by zoechi** [comment]
@Hixie

**Comment by Fenilsmiley** [comment]
any solution ??

**Comment by Fenilsmiley** [comment]
ty

**Comment by rahul-multipl** [comment]
Hi want to remove edit option of the Date Picker to keep only calendar date picker option
