### ISSUE TITLE
Getting current code to run requires multiple hot restarts.

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#18590]
![20180619_162622](https://user-images.githubusercontent.com/23037821/41629365-f55c4bea-73dd-11e8-8e16-2d1bb07d594b.png)
In MacOS, I'm switching from iPhone to iPad in the simulator and when I switch back and forth, an old build launches from time to time. Hot restarting 3 times makes it launch the current build.

Update: Deleting the build folder fixes it too even though Gradle rebuilds every time for android.
Update 2: [Video Added](https://youtu.be/MUUeQ4M92EQ). Testing done on physical Android Device.
Also, when debugging, it shows the breakpoints in a new locked file, which isn't preferable for editing mistakes and setting new breakpoints.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.5-pre.24, on Mac OS X 10.13.6 17G39b, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by zoechi** [comment]
@tvolkert

**Comment by ThinkDigitalRepair** [comment]
More details added

**Comment by ThinkDigitalRepair** [comment]
Figured this out! It happens when you're running multiple debug/run sessions and don't close the old ones. It locks in the version of the oldest running process it seems. The issue was resolved when I closed my other debug sessions in the editor. @zoechi @tvolkert

**Comment by ThinkDigitalRepair** [comment]
Yeah, and only after XCode builds again. I've deleted the build folder and if XCode doesn't build, it runs the old code.

**Comment by ThinkDigitalRepair** [comment]
Flutter clean doesn't fix the issue either... The debugger is stopping on old breakpoints in files that have been changed a while ago.

**Comment by zoechi** [comment]
Is this only an issue with iOS builds or only for Android?

**Comment by ThinkDigitalRepair** [comment]
Both if I remember correctly.

**Comment by ThinkDigitalRepair** [comment]
@zoechi, Video added to the original post.

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by ThinkDigitalRepair** [comment]
@zoechi no, not with my current projects. I haven't moved back to this project in a while though.

**Comment by zoechi** [comment]
@ThinkDigitalRepair Thanks for the update.
Feel free to reopen if you run into this again.

**Comment by josephmangmang** [comment]
Hey there, I always experience this issue. When first run (without flutter clean) old code was used. Need to hot reload to use the latest code or flutter clean then run again. Android
