### ISSUE TITLE
Add test for: Blinking cursor still fires timer when app is not active

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#186]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 20:23 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1524_

---

e.g. when it's not the active application, but is still running in the background. (You can see this by putting a print in markNeedsBuild when you have a focus text field.)

See also #1523.

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/pull/955 for infrastructure which will make this much easier to do.
We probably should just have the cursor be ticked from a periodic timer that is marked as being only runnable while the app is in the foreground.

**Comment by eseidelGoogle** [comment]
@Hixie added some hooks to the testing framework to catch things like this.  Do we know if this is still an issue?

**Comment by Hixie** [comment]
Pretty sure we fixed this, but we should figure out a way to test it. I'm not sure we have a test for it.

To see if it's fixed just put a print in the beginFrame logic, then run an app, get a blinking cursor, and hit the home button. See if you keep getting log messages.

**Comment by Hixie** [comment]
I'm going to announce a policy that we shouldn't fine "add a test for..." bugs. Either add the test, or hope someone adds the test. But the bug isn't going to make the latter happen.
