### ISSUE TITLE
Dart roll @optionalTypeArgs regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#18609]
This roll https://github.com/flutter/flutter/pull/18575 required that types be specified in more places, despite the `@optionalTypeArgs` annotations. This is a regression that means our documentation is now less clear than before.

**Comment by Hixie** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
Is `@optionalTypeArgs` just used for the examples? I see additional types added in that PR in places like this: https://github.com/flutter/flutter/pull/18575/files#diff-c798125dc01f08ce6bd3a0931482078bR906.

**Comment by devoncarew** [comment]
It looks like the definition of the annotation is here: https://pub.dartlang.org/documentation/meta/latest/meta/optionalTypeArgs-constant.html.

**Comment by Hixie** [comment]
Yeah I don't understand what happened with the types in that PR. @gspencergoog reported that there were new analyzer warnings that previously did not occur; I haven't looked into why this happened.

**Comment by devoncarew** [comment]
Ok, it looks like the implementation for this is in the linter, and it's a way to configure the `always_specify_types` lint.

**Comment by devoncarew** [comment]
@gspencergoog (or @Hixie) - any chance you know of a smaller repo case than the entire flutter repo?

**Comment by devoncarew** [comment]
I only see the types added to the examples in the dartdoc; is that correct? If so, I'll investigate the code that analyzes the examples.

**Comment by devoncarew** [comment]
I don't see locally. From talking to @gspencergoog, I'm going to prepare a PR which reverts the specific type args (which look like they were just applied to the dartdoc comments in `navigator.dart`, and see what the result is on the bots.
