### ISSUE TITLE
add a `flutter config` command?

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1860]
Related to https://github.com/flutter/flutter/pull/1859:

it would be good to have a way to configure where the android sdk is w/o using env variables or requiring a param passed into every cli command. I'm considering add a `flutter config` command. It would look something like this:

```
flutter config --android-home=/foo/bar/baz
```

And our instructions would call it out as a way to point flutter to a specific sdk. The data would persist on disk in some metadata file (perhaps `~/.flutter/config.yaml`).

**Comment by Hixie** [comment]
Is there really no way to determine it from the path? Surely there's some binary that ends up in the path that is in some well-defined location relative to the path we need.

**Comment by devoncarew** [comment]
We try that with `aapt` here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L57, adnd with `adb` as well. I suspect that people who've just downloaded the android sdk won't have any of it on their path however. We could additionally check some common install locations, though I am not aware if there are typical install locations.

I don't love adding another command as we already have quite a few. I'm not sure what other options are. We could vend a version into the flutter repo; or we could try and create a minimal adb toolchain per platform and store and provision it from google storage.

**Comment by Hixie** [comment]
Shipping our own isn't out of the question. It would help guarantee what we
don't get bit by compatibility issues, for one.

**Comment by devoncarew** [comment]
Closing this; our getting started experience w/ android is better now, and we may end up installing bits of the android sdk ourselves.
