### ISSUE TITLE
Depricated references warning in XCode

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#18605]
This warning pops up when deploying code to physical ios Devices. 
"The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target."

**Comment by zoechi** [comment]
Closing as dup of #18673
