### ISSUE TITLE
Exception Caught By Widget Library

### ISSUE THREAD

**Issue by imsaurabh1998** [flutter/flutter#18607]
I/flutter (11310): The following assertion was thrown building LayoutBuilder:
I/flutter (11310): 'package:flutter/src/animation/animations.dart': Failed assertion: line 340 pos 15: 'parent !=
I/flutter (11310): null': is not true.
I/flutter (11310): 
I/flutter (11310): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11310): more information in this error message to help you determine and fix the underlying cause.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor` and the code that caused the exception and allows to reproduce.
Looks a bit like #13030

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
