### ISSUE TITLE
Dart roll isInstanceOf/TypeMatcher regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#18608]
This roll https://github.com/flutter/flutter/pull/18575 required backwards-incompatible changes to our tests because of this change https://github.com/dart-lang/matcher/pull/88. I do not think we should make these changes as they are going to break our users, do not appear to be idiomatic, and the TypeMatcher name conflicts with our existing TypeMatcher class in a way that is worse than before as a result.

**Comment by Hixie** [comment]
This should be mostly addressed by https://github.com/flutter/flutter/pull/18614 for now.

**Comment by mravn-google** [comment]
The new `isInstanceOf` top-level function in package `flutter_test` shadows the same-named class in package `matcher`. So existing test code like this now fails:
```dart
import 'package:flutter_test/flutter_test.dart';
:
expect(foo, const isInstanceOf<Foo>());
```

**Comment by Hixie** [comment]
Yeah, that's intentional.

**Comment by zoechi** [comment]
I believe this issue is stale.
