### ISSUE TITLE
Fuchsia build dashboard runs out of file descriptors on WiFi

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#18617]
Steps to reproduce:

1. In the Fuchsia source tree, build the "dashboard" product.
2. Run the dashboard on WiFi
3. Wait one or two days.

Expected behavior:

The dashboard continues to show the build status.

Actual behavior:

The dashboard fails to fetch build status because the Dart VM has run out of file descriptors.

Notes:

Something in the Flutter engine is leaking file descriptors.  My guess its related to the repeated network requests made by the dashboard.  The issue reproduces easily on WiFi, but I think it will reproduce whenever the network is flaky.  In the past, I've reproduced it by unblocking a wired network connection from a NUC that does not have WiFi.

It's possible the leak is in the dashboard mod itself, but there's nothing obvious there that would leak.  We might want to create a reduced test case that demonstrates the leak in a simpler program.

@tvolkert @zanderso @jimbeveridge

**Comment by Hixie** [comment]
@abarth do you have a reduced test case?

**Comment by abarth** [comment]
Not yet.  I'll try to build one.

**Comment by Hixie** [comment]
HttpClient being able to allocate resources that it can't free seems like a serious problem.

**Comment by abarth** [comment]
Thanks for investigating!  I filed the connect() error code issue as NET-1064 in the Fuchsia bug database.

**Comment by Hixie** [comment]
@zanderso Should I assign this to you?

**Comment by zanderso** [comment]
Yes.

**Comment by zanderso** [comment]
The above fixes have rolled into Fuchsia. Not on WiFi, but I observed the dashboard running without exhausting fds for 6-7 days.
