### ISSUE TITLE
'LUTTER_TOOL_ARGSsnapshot_path*' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by sudarshanc** [flutter/flutter#18613]
**First time**
flutter upgrade
Upgrading Flutter from C:\flutter...
From https://github.com/flutter/flutter
   f9bb428..c7ea3ca  beta       -> origin/beta
   3019ad9..020e0ef  dev        -> origin/dev
   d8d4c74..dd1c3e6  flutter_module -> origin/flutter_module
   b8b34de..bb23a11  master     -> origin/master
 * [new branch]      revert-18465-skippaint -> origin/revert-18465-skippaint
 * [new tag]         v0.5.5     -> v0.5.5
Updating f9bb428..c7ea3ca
 .../fake-extension.txt                             |   0
 271 files changed, 7793 insertions(+), 1685 deletions(-)

Upgrading engine...
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 1ed25ca7b7e3e3e8047df050bba4174074c9b336...
Unzipping Dart SDK...
Updating flutter tool...
Downloading package sky_engine...

Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (6 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

Running "flutter packages upgrade" in <appname>...            32.0s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.251], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.24.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
**

> 'LUTTER_TOOL_ARGSsnapshot_path*' is not recognized as an internal or external command,
> operable program or batch file.

**

**Second time** 
>flutter upgrade
Upgrading Flutter from C:\flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (3 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Running "flutter packages upgrade" in <appname>...            29.6s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.251], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.24.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by prabhuthiran** [comment]
I am also facing the same issue

**Comment by Herohtar** [comment]
This happened to me as well.

**Comment by zoechi** [comment]
@tvolkert 

@prabhuthiran 
@Herohtar 
Consider using 
![image](https://user-images.githubusercontent.com/405837/41703161-ad70be82-7532-11e8-8907-4fac80b8bb6b.png) in the top-most comment because they can be better used to track how many are affected, instead of "me too" or "+1" comments,

**Comment by Jephen** [comment]
And I also have `[!] VS Code, 64-bit edition (version 1.24.1)` problem.

`flutter doctor -v` show like
```
[!] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

But I have installed.

**Comment by DanTup** [comment]
@Jephen There's a bug in the current beta with the VS Code extension not being detected. It's fixed in latest code so you'll get a fix in an upcoming update. It's safe to ignore that one, it doesn't affect your use of Flutter or VS Code.

**Comment by timsneath** [comment]
This should be closed as of https://github.com/flutter/flutter/issues/14578. Let us know if you still see it, @sudarshanc.
