### ISSUE TITLE
Feature Request: FirebaseUI Support

### ISSUE THREAD

**Issue by clarktank** [flutter/flutter#18625]
I really like FirebaseUI. It is very convenient and helps me focus on my application rather than a tedious authentication flow implementation. Can you make a FirebaseUI plugin for Flutter? Or implement it in dart?

**Comment by namiwang** [comment]
Especially for Firebase Auth.

**Comment by caseycrogers** [comment]
Yes please! It seems really silly for everyone to rewrite their own auth page.

**Comment by b-cancel** [comment]
Although I have not been able to find a super solid solution there are two packages that have been created

this one https://pub.dartlang.org/packages/flutter_firebase_ui
I have tested and it seems to work(UI, and the right things pop up), although to really confirm you would probably have to see things server side

this other one https://github.com/yiyisf/firebaseui
seems to be trying to do the same thing but its example did not build for some reason

I am currently working on a solution, I'll be recording a video and some gifs showing off all the functionality in the next week. Until then feel free to check out my other flutter packages on github.

**Comment by HerrNiklasRaab** [comment]
Me to! :)

**Comment by JosefJezek** [comment]
@b-cancel any progress?

**Comment by Purus** [comment]
FirebaseUI as available for other platforms, it would be super useful to have it for Flutter too.

**Comment by heatonandy** [comment]
Is there any update on this?

**Comment by b-cancel** [comment]
@HerrNiklasRaab @JosefJezek @Purus @heatonandy @JarikH I have been too busy working to continue building for flutter... however the progress that I made on a pure email and password solution can be found here https://github.com/b-cancel/Flutter_FeatureFilledTextForms

I added many features for ease of use so it is miles ahead of most other solutions I knew of (2 or 3 months back) 

Hopefully, this will provide a good start.

I will try my best to get back to it and refine it soon. Thanks for reaching out and have a great day!

**Comment by S1r-Lanzelot** [comment]
For a short term solution I ended up using the native packages and utilized channels to get the prebuilt UIs that I needed, works well for me.

https://proandroiddev.com/communication-between-flutter-and-native-modules-9b52c6a72dd2

**Comment by bhumkong** [comment]
[flutter_firebase_ui](https://pub.dartlang.org/packages/flutter_firebase_ui) package seems to be abandoned, but there is a fork: [firebase_ui](https://pub.dartlang.org/packages/firebase_ui)

**Comment by CiriousJoker** [comment]
The official firebaseui has a different way of working though. I've only tested the web version, but that one looks way different than the firebase_ui package.

**Comment by gurmukhp** [comment]
Both of the existing solutions don't tend to work well (they don't build).

Would anyone mind sharing their implementation that takes advantage of Platform Channels? I would've expected Google to provide this as a first attempt :(

**Comment by kroikie** [comment]
@clarktank

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/789. Any further collaboration will be done there.

**Comment by polina-c** [comment]
This is firebase authentication UI in flutter: https://pub.dev/packages/faui
This is demo: https://flatter-auth-ui-demo1.codemagic.app/#/
