### ISSUE TITLE
"Downloading" output from flutter tool could be improved

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1862]
When downloading the engine we output two lines that sound like they're independent but are really saying the same thing. We should either say the first on the second. I recommend saying the first line only, and making the second line only appear if you say `--verbose`, and in that case, not saying "Downloading %s." but saying "URL: %s" (so that it looks like more detail for the previous line, and doesn't concatenate a "." with the URL).

Also, once we're done downloading we should update the line to say how long it took. See https://github.com/flutter/flutter/issues/1704 for more on this.

Current output:
```
Downloading linux-x64 artifacts from the cloud, one moment please...
Downloading https://storage.googleapis.com/mojo_infra/flutter/b847a505177113f39056ddc516090273be958aff/linux-x64/artifacts.zip.
```

Suggested output normally:
```
Downloading linux-x64 artifacts from the cloud, one moment please...
```
...becoming:
```
Downloading linux-x64 artifacts from the cloud, one moment please... (2.5MB, 4.9 seconds)
```

Suggested verbose output:
```
[   10 ms] Downloading linux-x64 artifacts from the cloud, one moment please...
[   10 ms] URL: https://storage.googleapis.com/mojo_infra/flutter/b847a505177113f39056ddc516090273be958aff/linux-x64/artifacts.zip
[ 4910 ms] Downloaded 2.5MB in 4.9 seconds.
```

**Comment by abarth** [comment]
This is largely fixed by moving the downloading earlier.  There are still some downloads (like third-party services) that we do via the old codepath, however, that could still be improved.

**Comment by eseidelGoogle** [comment]
This seems much improved now.

**Comment by devoncarew** [comment]
Closing this out as there've been several improvements to the download progress display.
