### ISSUE TITLE
Flutter Inspector in VS Code

### ISSUE THREAD

**Issue by Gaurav-Mall** [flutter/flutter#18629]
Hey, everybody! I'm trying to use Visual Studio Code instead of Android Studio for developing apps with **Flutter**. I recently learned about **Flutter Inspector** and its very helpful _features_. But the problem is that I only see the inspector in an android studio project(window) and cannot find it in VS Code. Is it possible to use Flutter Inspector in VS Code? Any suggestions would be helpful.

**Comment by zoechi** [comment]
@DanTup

**Comment by DanTup** [comment]
Unfortunately the Flutter Inspector is not currently available in VS Code. The issue for adding it is here:

https://github.com/Dart-Code/Dart-Code/issues/519

We did some investigation into embedded web views in VS Code (since it's extension points for completely custom UI are limited) but there are still some unanswered questions about how it'll work.

You can subscribe to the issue above for updates when work begins, so I'll close this as a dupe.

**Comment by Gaurav-Mall** [comment]
Thanks very much for the information. I've decided to use Android Studio because of the limitations in VS Code. Hopefully, when they put it in I'll get back into using it. Thank you very much, everybody!

**Comment by DanTup** [comment]
If there are other things you're missing besides the inspector, please do open issues in the [Dart Code](https://github.com/Dart-Code/Dart-Code) repo (or if there are already issues for them, add a 👍 ); it helps us know what's most important to users. Thanks!

**Comment by venvyt** [comment]
is there a way i could preview the app like in android studio designer but when using flutter, instead of having to run the app to see how the UI looks like?

**Comment by zoechi** [comment]
@venvyt no, you have to run the app

**Comment by DanTup** [comment]
@venvyt Like the Inspector, the [live preview](https://github.com/flutter/flutter-intellij/wiki/Using-live-preview) is not currently available in VS Code.

**Comment by venvyt** [comment]
okay, i get it now

**Comment by prasadsunny1** [comment]
google may want you to not use vs code, And to make you come back to studio even if you try to.

**Comment by hariangr** [comment]
What's the status?

**Comment by DanTup** [comment]
@hariangr Please follow https://github.com/Dart-Code/Dart-Code/issues/519 for info on this - the top post contains the most recent info.

**Comment by tkshehan** [comment]
DevTools were added in a recent update to the Dart Code extension for VSCode.
https://dartcode.org/releases/v2-24/

If you are up to date the command vscode command is Dart: Open DevTools

**Comment by shift14wx** [comment]
@tkshehan I want to open a little sidebar like android studio provides, but instead I have to open up Google Chrome for this kind of feature.

**Comment by DanTup** [comment]
@shift14wx please check out the release notes for the last release -> https://dartcode.org/releases/v3-12/#preview-embedded-devtools :)

**Comment by GoooGu** [comment]
Is it possible to toggle between Android and iOS devices in the flutter inspector in VS Code like it is in Android Studio?

**Comment by DanTup** [comment]
@GoooGu you can toggle between them using the **Flutter: Toggle Platform** in the VS Code command palette:

<img width="447" alt="Screenshot 2020-09-11 at 14 55 06" src="https://user-images.githubusercontent.com/1078012/92933972-d5c79d00-f43e-11ea-9ea6-188563bc1c09.png">

**Comment by GoooGu** [comment]
Thanks! That perfectly solved it:)
