### ISSUE TITLE
detect android sdk via ANDROID_SDK_ROOT in addition to deprecated ANDROID_HOME

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#18627]
As said in android's doc (https://developer.android.com/studio/command-line/variables), `ANDROID_HOME` is deprecated and should migrate to `ANDROID_SDK_ROOT`.

**Comment by zoechi** [comment]
Duplicate of #15273

**Comment by zoechi** [comment]
Duplicate of #15144
