### ISSUE TITLE
Add "rotation" to ScaleUpdateDetails in GestureDetector

### ISSUE THREAD

**Issue by Tomucha** [flutter/flutter#18632]
Feature request / proposal:

ScaleUpdateDetails event now provides the developer with convenient "scale" property, but I really would have a use for "rotation".

Two fingers define a line on the screen, at any given time. Comparing the original fingers position with current fingers position should give us information about rotation.

**Comment by Tomucha** [comment]
Hi! This seems to be done:
https://docs.flutter.io/flutter/gestures/ScaleUpdateDetails/rotation.html

Thanks!!!

**Comment by zoechi** [comment]
@Tomucha Sounds like this issue can be closed.

**Comment by Tomucha** [comment]
Thank someone for me please :-) Exactly what I need in my app :-)
