### ISSUE TITLE
Websocket not even creating the headers, but still connecting to ws://echo.websocket.org only

### ISSUE THREAD

**Issue by gatertronics** [flutter/flutter#18630]
Hi everyone,
I have just tried to run the Websockets example in both a Youtube video and also the websocket code samples, so nothing exiting...

I made the example app and yes, it connects to the ws://echo.websocket.org website to do the echo of your text as expected.  You type some text in and press the send button and yes, it responds with the same text........

However,  I then tried to make it connect to my existing server running websockets as well. Should be no big deal. I found it wasn't connecting and just ignores the connection altogether.  So, I captured the packet and have attached them below from WireShark...

[websocket flutter test.zip](https://github.com/flutter/flutter/files/2118690/websocket.flutter.test.zip)
![image](https://user-images.githubusercontent.com/6510756/41650731-1bad134e-74c2-11e8-929a-72ec43c10d33.png)

Then I went back to my original webapp written in NSB basic and does work well... and captured this to my website.....
[websocket from app.zip](https://github.com/flutter/flutter/files/2118691/websocket.from.app.zip)
![image](https://user-images.githubusercontent.com/6510756/41652445-60fc72ba-74c6-11e8-915d-c5b942e8d231.png)

So, in the first instance the example mobile app written in flutter /dart/in vscode ide seems to echo when sending text to the test site, as per the first sample, the second sample is from my webapp sending to my existing website clearly showing in wireshark that is is upgrading and is now a webocket protocol.

The example code never upgrades to websocket protocol, BUT, it also never even start to send the header asking to upgrade to a wenbsocket it starts instead with a PSH,ACK THEN ACK, THEN ACK, THEN PSH,ACK

Thats not right at all. What stupid thing am I doing wrong here?

flutter doctor shows:

C:\000nav\flutterapp\robtest1>flutter doctor -v
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.48], locale en-AU)
    • Flutter version 0.4.4 at C:\Users\Rob_Laptop\Downloads\flutter_windows_v0.4.4-beta\flutter
    • Framework revision f9bb4289e9 (6 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\Rob_Laptop\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 1 category.

The dart code issue is weird... I install it and it goes away, then it comes back and I haven't done anything????

Not sure if this is linked.

Thanks,
Rob.

ps. just to add to the dart install error as you can see here:
![image](https://user-images.githubusercontent.com/6510756/41651799-c34b4ee8-74c4-11e8-83e4-4f0c1f5cbd61.png)

If I click on the link to install dart it asks to install on the button..... but in the same pic you can see that in the ide, dart is installed???????

**Comment by gatertronics** [comment]
Just to add more detail to this... I rebuilt the same sample flutter websocket example in Android studio instead of visual studio code and it does the same thing.... This is driving me mad..... Any help would be greatly appreciated.

**Comment by zoechi** [comment]
Could you try in plain Dart and see if this does reproduce there as well?
In this case you'd probably get better feedback if the bug is reported in the dart-lang/sdk repo.

**Comment by gatertronics** [comment]
I have now tried putting wireshark on the server side and CAN see the correct http get request etc as expected, but it then just dumps the connection with the final response containing the original text.. Very weird.  I am now trying to create a separate websocket server on my server to use Superwebsockets instead of what I had with microsoft standard sockets and then manually creating the response etc in case I have done something wrong.  Either way, I could see the response on wireshark from echo.websocket.org giving the initial text back unaltered in a closing frame. Not what should be happening in websockets. I will keep trying..

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/16875#issuecomment-384758566 might be worth a try

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/11444 might be related as well if the server only accepts headers in a specific casing.

**Comment by goderbauer** [comment]
@gatertronics What package are you using to connect to the websocket? Is it https://pub.dartlang.org/packages/web_socket_channel? In that case, https://github.com/dart-lang/web_socket_channel/issues may be a better place to get help with this issue.

**Comment by gatertronics** [comment]
Sorry, that was a long time ago. I was using the package that comes with flutter. I don't bother with web sockets anymore. It's easier to just use normal sockets. Sent on the go with Vodafone-------- Original Message --------Subject: Re: [flutter/flutter] Websocket not even creating the headers, but still connecting to ws://echo.websocket.org only (#18630)From: Michael Goderbauer To: flutter/flutter CC: gatertronics ,Mention @gatertronics What package are you using to connect to the websocket? Is it https://pub.dartlang.org/packages/web_socket_channel? In that case, https://github.com/dart-lang/web_socket_channel/issues may be a better place to get help with this issue.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flutter/flutter","title":"flutter/flutter","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/flutter/flutter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@goderbauer in #18630: @gatertronics What package are you using to connect to the websocket? Is it https://pub.dartlang.org/packages/web_socket_channel? In that case, https://github.com/dart-lang/web_socket_channel/issues may be a better place to get help with this issue."}],"action":{"name":"View Issue","url":"https://github.com/flutter/flutter/issues/18630#issuecomment-450947396"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/flutter/flutter/issues/18630#issuecomment-450947396",
"url": "https://github.com/flutter/flutter/issues/18630#issuecomment-450947396",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by goderbauer** [comment]
I am closing this as obsolete for now. Anybody, who has more details, should feel free to reopen with those information.
