### ISSUE TITLE
Flutter ChangeLog doesn't document Dart changes

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#18639]
Briefly documenting significant changes to Dart in Flutter's [ChangeLog](https://github.com/flutter/flutter/wiki/Changelog) would help developers who are tracking one of the Flutter channels.

For example, it appears that differences between the version of Dart bundled in Flutter versions 0.4.4 and 0.5.1 made it no longer possible to include the public [bignum package ](https://pub.dartlang.org/packages/bignum/versions/0.1.0).  See https://github.com/flutter/flutter/issues/18634.

Obviously the Flutter ChangeLog doesn't need to list the compatibility of every Dart package with every Flutter version. On the other hand, it would be useful to summarize significant changes to Dart between  Flutter versions and, when needed, pointers to more detailed reports. See also: https://github.com/dart-lang/pub-dartlang-dart/issues/1395

**Comment by zoechi** [comment]
Perhaps a link to the Dart changelog would do?
