### ISSUE TITLE
Release-process Wiki entry, step 8, buckets not betas

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#18642]
Step 8 should refer to "bucketN" milestones, not "betaN": https://github.com/flutter/flutter/wiki/Release-process#rolling-the-beta-channel

**Comment by zoechi** [comment]
I haven't found any mention of `bucketN` or `betaN`.

Perhaps this was replaced by 

```
Move all the open bugs in the current milestone to the Overdue milestone.
```

I assume this issue is stale.
