### ISSUE TITLE
Release-process Wiki entry, step 3 could be clearer

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#18644]
Step 3 in https://github.com/flutter/flutter/wiki/Release-process#rolling-the-beta-channel

How exactly does one test these assertions?

- can be successfully upgraded to from the dev build to which the beta branch currently points (via 'flutter upgrade')
- can be successfully upgraded from to a later dev build (via 'flutter upgrade')
- can switch channels successfully (via 'flutter channel')

It would be worth spelling it out, since individuals don't do beta rolls very often.

**Comment by kf6gpe** [comment]
Looks like this was done at some point; closing as I think it's obsolete.
