### ISSUE TITLE
TextField longpress is unusable in Accessibility mode

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#18646]
In the gallery, try out the text fields demo in a11y mode.

Enter some text into the first box, and then a11y long-press (one tap then hold on the second tap).

The 'paste' or 'select all' overlay pops up, but it is not tappable.

**Comment by DaveShuckerow** [comment]
@jonahwilliams /cc

**Comment by jonahwilliams** [comment]
This works just fine for me, if the flutter version was old it might be related to a sorting change i fixed where widgets were hit tested wrong in a11y mode.  that would place the overlay behind the material

![flutter_02](https://user-images.githubusercontent.com/8975114/42004757-1724418a-7a26-11e8-9c6c-bd44d7c006d2.png)

**Comment by jonahwilliams** [comment]
Closing as fixed but feel free to reopen if you are still seeing this
