### ISSUE TITLE
macOS: flutter upgrade/doctor reports brew components missing (they are not)

### ISSUE THREAD

**Issue by lukasgit** [flutter/flutter#18658]
On macOS, after running ```$ flutter upgrade``` today flutter doctor reports I am missing brew components (when I am not).

For security reasons, homebrew is not installed under the "recommended" /usr/local.  Custom location is pointing just fine under export PATH, and flutter ios apps are also working just fine.

```
Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (3 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
```

**Comment by zoechi** [comment]
@tvolkert

**Comment by lukasgit** [comment]
@tvolkert 

### UPDATE:

I resolved the CocoaPods issue by uninstalling and reinstalling cocoapods:

```
$ brew uninstall cocoapods
$ brew install cocoapods
```

Unfortunately, flutter doctor still fails to recognize libimobiledevice and ideviceinstaller even though they both exist after performing an uninstall and re-install:

**NOTE: homebrew is installed in my home application directory (~/Applications/homebrew) and NOT /usr/local (this is intentional for security reasons). I'm wondering if Flutter is hard coded to look for libimobiledevice in /usr/local/lib ?**

```
$ ls Applications/homebrew/lib/libimobiledevice.*
Applications/homebrew/lib/libimobiledevice.6.dylib	Applications/homebrew/lib/libimobiledevice.dylib
Applications/homebrew/lib/libimobiledevice.a
```
```
$ ls Applications/homebrew/bin/ideviceinstaller 
Applications/homebrew/bin/ideviceinstaller
```
```
Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (3 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.24.1)
[!] Connected devices
    ! No devices available
```

**Comment by muer2000** [comment]
+1

**Comment by zoechi** [comment]
@muer2000 using 
![image](https://user-images.githubusercontent.com/405837/41773350-15c0ffd0-761c-11e8-9d8c-b438db6ff385.png) in the first comment is a way better way to increase priority than `+1` comments.

**Comment by luisnuxx** [comment]
Same thing is happening to me. 
-------------

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
[!] VS Code (version 1.24.1)   
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
@luisnuxx That's probably a different issue

**Comment by lukasgit** [comment]
@zoechi @luisnuxx Yes, Doctor also barks an issue with VS Code, but that is for another issue I will open separately.

**Comment by lukasgit** [comment]
@zoechi @tvolkert 

**RESOLVED**... albeit a terrible way to resolve this issue. There is a problem, however, with `$ flutter ugprade` not actually upgrading flutter (I will open a separate issue).

**SOLUTION**

* Delete flutter
* Delete homebrew
* Re-install homebrew
* Re-install flutter

**STEP 1: Delete Flutter and Homebrew**

$ cd ~/Development/
$ rm -rf flutter/
$ rm -rf homebrew/

$ cd _(back to home)_
$ rm -rf .flutter
$ rm -rf .cocoapods/

**STEP 2: Re-install Flutter and Homebrew**

$ cd ~/Development/
$ unzip ~/Downloads/flutter_macos_v0.5.1-beta.zip
$ mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
$ flutter doctor
```
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
```
$ brew install --HEAD libimobiledevice
$ brew install ideviceinstaller
$ brew install ios-deploy
$ brew install cocoapods
$ pod setup
$ flutter doctor -v
```
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3
```

**Comment by lukasgit** [comment]
Fixed as of Flutter v0.9.2 (Channel dev)

**Comment by Hypercruse** [comment]
Getting this error again, with Flutter (Channel master, v1.0.1-pre.3, on Mac OS X 10.14.1 18B75, locale de-DE)

followed all instructions but this error wont disappear, flutter also wont recognice my usb-linked iphone. Everything worked until i upgraded. Any help would be appreciated!

**Comment by lukasgit** [comment]
@Hypercruse can you run 'flutter doctor -v' and post the output here?

**Comment by Hypercruse** [comment]
[✓] Flutter (Channel master, v1.0.1-pre.3, on Mac OS X 10.14.1 18B75, locale
    de-DE)
    • Flutter version 1.0.1-pre.3 at /Users/apple/Desktop/flutter
    • Framework revision d74b1c2051 (23 hours ago), 2018-12-07 14:19:09 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK at /Users/apple/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

i use intelij for other stuff so we can ignore this, but i have a iphone 7 connected to my mac so it should recognize it (it always did)

**Comment by tvolkert** [comment]
@Hypercruse, sorry for the extra churn, but what about `flutter -v doctor -v`?

**Comment by Hypercruse** [comment]
@tvolkert 
[  +16 ms] executing: [/Users/apple/Desktop/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/apple/Desktop/flutter/] git rev-parse --abbrev-ref
HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/Users/apple/Desktop/flutter/] git ls-remote --get-url
origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/apple/Desktop/flutter/] git log -n 1
--pretty=format:%H
[  +47 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] d74b1c205103ed2132fc5ae536a94217ec965fb3
[        ] executing: [/Users/apple/Desktop/flutter/] git log -n 1
--pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 days ago
[        ] executing: [/Users/apple/Desktop/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[  +69 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +1 ms] v1.0.0-3-gd74b1c205
[ +197 ms] executing: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[ +162 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[   +1 ms] 3.2
[ +523 ms] executing: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[  +70 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[   +1 ms] 3.2
[  +88 ms] java -version
[ +864 ms] executing: idevice_id -h
[  +10 ms] executing: ios-deploy --version
[  +11 ms] executing: pod --version
[ +117 ms] executing: /usr/bin/defaults read /Applications/IntelliJ
IDEA.app/Contents/Info CFBundleShortVersionString
[  +63 ms] Exit code 0 from: /usr/bin/defaults read /Applications/IntelliJ
IDEA.app/Contents/Info CFBundleShortVersionString
[        ] 2018.2.4
[  +12 ms] [✓] Flutter (Channel master, v1.0.1-pre.3, on Mac OS X 10.14.1 18B75,
locale
               de-DE)
[   +1 ms]     • Flutter version 1.0.1-pre.3 at /Users/apple/Desktop/flutter
[        ]     • Framework revision d74b1c2051 (2 days ago), 2018-12-07 14:19:09
-0800
[        ]     • Engine revision 7375a0f414
[        ]     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
⣾[   +2 ms] executing: /Users/apple/Library/Android/sdk/platform-tools/adb
devices -l
[   +9 ms] Exit code 0 from: /Users/apple/Library/Android/sdk/platform-tools/adb
devices -l
[        ] List of devices attached
[   +4 ms] executing: idevice_id -h
[   +8 ms] /usr/bin/xcrun simctl list --json devices
[ +260 ms] executing: /Users/apple/Library/Android/sdk/platform-tools/adb
devices -l
⣽[  +43 ms] List of devices attached
[   +2 ms] executing: ios-deploy --version
[  +14 ms] 1.9.4
[   +1 ms] executing: ios-deploy --version
[  +14 ms] executing: ios-deploy --version
[  +16 ms] 1.9.4
[  +11 ms] executing: /Users/apple/Library/Android/sdk/tools/bin/sdkmanager
--licenses
⣽[ +767 ms] 1.6.0.beta.2
[+1673 ms] [✓] Android toolchain - develop for Android devices (Android SDK
28.0.3)
[        ]     • Android SDK at /Users/apple/Library/Android/sdk
[        ]     • Android NDK at /Users/apple/Library/Android/sdk/ndk-bundle
[        ]     • Platform android-28, build-tools 28.0.3
[        ]     • Java binary at: /Applications/Android
                 Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build
                 1.8.0_152-release-1136-b06)
[        ]     • All Android licenses accepted.
[        ] [!] iOS toolchain - develop for iOS devices (Xcode 10.1)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 10.1, Build version 10B61
[        ]     ✗ libimobiledevice and ideviceinstaller are not installed. To
install with
                 Brew, run:
[        ]         brew update
[        ]         brew install --HEAD usbmuxd
[        ]         brew link usbmuxd
[        ]         brew install --HEAD libimobiledevice
[        ]         brew install ideviceinstaller
[        ]     • ios-deploy 1.9.4
[        ]     • CocoaPods version 1.6.0.beta.2
[        ] [✓] Android Studio (version 3.2)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Flutter plugin version 30.0.1
[        ]     • Dart plugin version 181.5616
[        ]     • Java version OpenJDK Runtime Environment (build
                 1.8.0_152-release-1136-b06)
[        ] [!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[        ]     • IntelliJ at /Applications/IntelliJ IDEA.app
[        ]     ✗ Flutter plugin not installed; this adds Flutter specific
functionality.
[        ]     ✗ Dart plugin not installed; this adds Dart specific
functionality.
[        ]     • For information about installing plugins, see
[        ]       https://flutter.io/intellij-setup/#installing-the-plugins
[        ] [!] Connected device
[        ]     ! No devices available
[        ] ! Doctor found issues in 3 categories.
[  +10 ms] "flutter doctor" took 4.915ms.

**Comment by Hypercruse** [comment]
Still having that problem right here, any help would be appreciated!

**Comment by lukasgit** [comment]
@Hypercruse Do you have brew installed? From what I can tell about your Flutter doctor output, you need to do the following:

```
$ brew update
$ brew install --HEAD usbmuxd
$ brew link usbmuxd
$ brew install --HEAD libimobiledevice
$ brew install ideviceinstaller
```
If that still doesn't resolve the issue, try following my instructions here to start a fresh installation:
https://github.com/flutter/flutter/issues/18658#issuecomment-400547521

Good luck, and please let everyone on this thread know if and what resolved the problem you are experiencing!

**Comment by Hypercruse** [comment]
@lukasgit Yeah i did those prompts a couple of times, everything was installed but it still showed me that message and i couldn't run my project on my physical ios device. 

However, I just solved it with your advice.
For me, I didn't have to reinstall flutter, it was enough to uninstall homebrew/cocoapods and make a fresh installs! Afterwards i had to follow all prompts in the flutter doctor output and it worked!

Thank you so much for your help, and a happy new year!

**Comment by konstantintuev** [comment]
Try relinking everything, as it turns out installing `libimobiledevice` is not enough and you need to `brew link libimobiledevice`.
Try it with everything flutter depends on from brew.

**Comment by yangqin22** [comment]
![image](https://user-images.githubusercontent.com/9441458/54893972-66c95200-4ef3-11e9-82d9-7e5d2639e2e1.png)

**Comment by konstantintuev** [comment]
@yangqin22 first you need to install libusbmuxd:
```
$ brew install --HEAD usbmuxd
$ brew link usbmuxd
```
