### ISSUE TITLE
Support custom fallback chain in a font family?

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter#18669]
It would be great if Flutter allow us to specify our own font fallback chain, just like what we can do now in CSS's font-family property.

Android only provides a regular weight of Noto Sans CJK. I want to add a bold typeface to my app, but currently this means that I have to give up using Roboto as the default font for Latin characters (unless I craft my own Roboto+Noto Sans CJK custom font). What I would like to do is to specify my font family to use system's Roboto first, followed by my custom font in the application. Of course a different fallback chain will be needed for iOS, but you get what I mean.

**Comment by HansMuller** [comment]
cc @jason-simmons

**Comment by zoechi** [comment]
@GaryQian does #25585 fix this?

**Comment by GaryQian** [comment]
Yes, this feature should be added by #25585.

**Comment by kevlar700** [comment]
Perhaps this should be added to ThemeData also or perhaps the default should be null to avoid unexpected internet connections?

I'm not sure if wasm also downloads Roboto for some reason in any case on flutter for web release. As I see a random string KFOmCnq...ttf fetch failure which is Roboto to fonts.google.com when offline. I do not see that in html mode.

https://github.com/flutter/devtools/issues/2420#issuecomment-810486249
