### ISSUE TITLE
How to override linter version used for analysis

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#18662]
I have some changes in linter I'd like to test on flutter codebase.

Previously (before `flutter analyze --flutter-repo` uses analysis server) I used a `dependency_overrides` section in [packages/flutter_tools/pubspec.yaml](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml) to use a local linter.

Now that the analysis server is used I can not figure out how to use a custom version of linter. How can I do that ?

@devoncarew @scheglov @bwilkerson

**Comment by bwilkerson** [comment]
It might not be the _best_ way, but you should be able to update the version of linter in your local checkout of the SDK (by updating the DEPS file and running `gclient sync` or by directly overwriting the linter package's directory), and then build an SDK as normal. That SDK's analysis server will use the updated version of linter.

**Comment by devoncarew** [comment]
Yes, if you can build the sdk, then you can run flutter analyze w/ a custom version of the analysis server:

```
flutter analyze --dart-sdk=<path-to-sdk>
```

**Comment by a14n** [comment]
Thanks for your advice. It would be great to be able to do that without building a sdk.

Would it be easier if the linter package had been an analyzer plugin? Would a simple change in `pubspec.yaml` have been enough?

**Comment by devoncarew** [comment]
You could also consider using the `bin/linter.dart` entrypoint. I'm not sure if the way it sets up a context will let it locate flutter's analysis options file, but if not, you could always add a `--flutter` cli flag to it which does some flutter specific setup.

**Comment by zoechi** [comment]
@a14n Do you think there is still something to do?
