### ISSUE TITLE
Asset Images disappearing and creating Exceptions/Freezes

### ISSUE THREAD

**Issue by LiveRock** [flutter/flutter#18661]
I am experiencing exceptions that the AssetImages is not loading because of null. It loads fine when app launches but after a few mins, even without any activities (like remain on a screen), one by one, the exception will suddenly pop up, crashing the app.

This is the error:

```
compiler message: org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'pubspec'.
compiler message: pubspec
compiler message: ^^^^^^^
compiler message: org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'pubspec' isn't defined for the class '#lib1::PlatformAssetBundle'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'pubspec'.
compiler message: pubspec
compiler message: ^
flutter: Another exception was thrown: Unable to load asset: assets/bar.jpg
```

I suspect that the asset images were disposed off, creating this exception but not sure what is actually going on..

**Comment by MichaelSowah** [comment]
could you post the results of flutter doctor -v

**Comment by zoechi** [comment]
Also try `flutter clean`.

**Comment by LiveRock** [comment]
flutter doctor -v
[✓] Flutter (Channel dev, v0.5.5, on Mac OS X 10.13.5 17F77, locale en-SG)
    • Flutter version 0.5.5 at /Users/peterlum/dev/flutter
    • Framework revision 020e0ef55c (6 days ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Applications/AndroidDev/sdk
    • Android NDK at /Applications/AndroidDev/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Applications/AndroidDev/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b02)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 162.2924
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • LG D855   • LGD855a710c089                       • android-arm • Android 5.0 (API 21)
    • iPhone 5s • CF5D9DEE-1673-498C-B09B-308D3DAA06A2 • ios         • iOS 11.3 (simulator)

! Doctor found issues in 1 category.

**Comment by LiveRock** [comment]
Done flutter clean and it is still the same.


```
flutter: Another exception was thrown: Unable to load asset: assets/avatars/avatar-1.jpg
flutter: Another exception was thrown: Unable to load asset: assets/bar.jpg
```

**Comment by cbracken** [comment]
@LiveRock a few questions. Would you mind providing a bit more detail on how to reproduce the issue and the conditions under which it occurs?

1. Is this behaviour reproducible on both iOS and Android, or just one?
2. What does your image loading code look like, if you don't mind providing those lines?
3. As I understand it, you start the app and the images load fine. After that, are you moving the widget with the images onscreen/offscreen? When do you see the error messages below? Does the app keep running for a bit, or does it crash immediately once the image fails to load?
4. Are there any crash reports? For Android, in the logs, for iOS from _Xcode > Window > Devices and Simulators_, then select the device and click _View Device Logs_.

**Comment by LiveRock** [comment]
1. Mostly I test on ios both Sim and Device. I just tested with an Android device, seems fine.
2. 
```
DecorationImage backgroundBar = new DecorationImage(
  image: new AssetImage('assets/bar.jpg'),
  fit: BoxFit.cover,
);

DecorationImage nodata = new DecorationImage(
  image: new AssetImage('assets/nodata.png'),
  fit: BoxFit.cover,
);

return (new Container(
        width: screenSize.width,
        height: imageBackgroudHeight==null ? screenSize.height / 2.5 : imageBackgroudHeight,
        decoration: new BoxDecoration(image: backgroundBar),
        child: new Container(....
```

3. Start app, loads fine. After signing in using Firebase Auth, move to Home screen or any screen, wait for a while with or without any activity, boom. The app runs a bit. Also, I notice it happens when I am using vcode for debugging. When I detach my device and run without debugging, it didn't crash but also, I do not know what is going on behind the scenes because there are no console messages.

4. Will try to get these reports.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
