### ISSUE TITLE
MLKit Custom model plugin

### ISSUE THREAD

**Issue by startupgurukul** [flutter/flutter#18660]
@bparrishMines Thank you for the official MLKit Vision plugin located here, 
https://github.com/flutter/plugins/tree/master/packages/firebase_ml_vision

This is a request for Custom MLIntepreter plugin, supported by MLKit
https://firebase.google.com/docs/reference/android/com/google/firebase/ml/custom/package-summary

**Comment by zoechi** [comment]
@Hixie

**Comment by cortexuvula** [comment]
The current firebase_ml_vision plugin does not support custom model. Could you please add custom model feature to the plugin or standalone plugin?

**Comment by sardox** [comment]
Would love to use custom local tflite models generated by AutoMl

**Comment by MJohnson159** [comment]
Are custom models still not supported by flutter? A project I'm currently working on uses a .tflite model and I'm currently using flutter. Not terribly experienced with flutter atm, but if it was supported in flutter vs having to do this in kotlin and get it to work with flutter (haven't even tried yet), that would be ideal.

**Comment by Peet-A** [comment]
waiting for the custom model plugin , any news guys ?

**Comment by bparrishMines** [comment]
Unfortunately, we are still working on getting full integration testing working with the rest of our plugins. We most likely won't add any additional plugins until we do.

**Comment by ASentimentalMan** [comment]
It's 9012 we are still wishing for our custom model support lol

**Comment by ASentimentalMan** [comment]
It's 9102 we are still wishing for our custom model support lol

**Comment by jithin-pal** [comment]
I have built a custom ML model, when it comes to prediction it is crashing the application. What is the error? When i use the mobilenet downloaded from internet works fine. How do i fix this?

**Comment by startupgurukul** [comment]
Until it's implemented officially, here is a package that supports custom
models

https://github.com/azihsoyn/flutter_mlkit

**Comment by jithin-pal** [comment]
But, i see no support of tflite model involved in it. I am working with tflite models.

**Comment by startupgurukul** [comment]
https://github.com/azihsoyn/flutter_mlkit/blob/master/README.md#custom-model-interpreter

modelName: "mobilenet_v1_224_quant" is a tflite file hosted on firebase via
mlkit (you can use a local version too but this was one need not push a app
update for model change.

**Comment by kroikie** [comment]
@startupgurukul

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/788. Any further collaboration will be done there.

**Comment by mady143** [comment]
HI @zoechi  @Hixie  @cortexuvula  @kroikie  @csells 
I had an tflite model which is locally placed and doing operation now i want to call it from the server like firebase ml kit i had also summarised the documentation related to this from **https://firebase.google.com/docs/ml-kit/android/use-custom-models#java** but here it is written in java android not for the dart and for flutter I am using flutter so please help me to  resolve this help me in changing the code in dart file 

Thanks and Regards,
Manikantha Sekhar.

**Comment by bparrishMines** [comment]
@mady143 The issue for this feature has moved to FirebaseExtended/flutterfire#788. Feel free to leave a thumbs up on that issue if you would like to see the feature prioritized.
