### ISSUE TITLE
How to make flutter (and dart) more popular?

### ISSUE THREAD

**Issue by kokizzu** [flutter/flutter#18664]
By officially supporting this https://github.com/flutter2js/flutter2js

People will sold if one code can support all 3 most popular platform (web, android, iOS)

**Comment by Kartik1607** [comment]
This shouldn't be a place for advertising.

**Comment by carlosjs23** [comment]
why is this a issue?, the flutter and dart popularity are already increasing.

**Comment by rbarisic** [comment]
This ticket should be closed. There are currently 3,331 open Issues, we should get that number down.

**Comment by zoechi** [comment]
This was asked a lot, but it's not too easy. 
It was also explored in https://github.com/yjbanov/butterfly.
AFAIK there are currently no such plans in that direction.
