### ISSUE TITLE
android studio parameter info and quick documentation is not fully aware of the context 

### ISSUE THREAD

**Issue by mhamri** [flutter/flutter#18676]
since the flutter widgets are meant to be written inside each other, it's a must to have scope aware IDE. at moment it is showing information only about the most top level widget

![image](https://user-images.githubusercontent.com/8991783/41723520-ec146cae-759d-11e8-84d6-c60a1019afba.png)

**Comment by zoechi** [comment]
I think this should be moved to dart-lang/sdk.
This functionality is provided by the dart_analyzer.

**Comment by mhamri** [comment]
well, I believe this should somehow contribute from flutter team to dart repo, no one in right mind instantiates 100 over class inside each other. in severe case your IOC container takes care of it for you. but since its' a very special usage of the classes that flutter needs, and this strange requirement is known better by flutter developers, it will be easier to address if somehow see it as an internal problem

**Comment by zoechi** [comment]
@devoncarew ?

**Comment by devoncarew** [comment]
Yup, I agree, this is likely an issue with the analysis server - will move repos.
