### ISSUE TITLE
why the flutter_view example is slow?

### ISSUE THREAD

**Issue by hpsoar** [flutter/flutter#18670]
this example contains a page half native and half flutter, the flutter part needs to wait for seconds before showing up.

Why is that? I suppose flutter should have good performance.

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment]
Can you please provide more details about the issue?
Debug builds are not representative for performance evaluation. Ensure you are using a profile or release build.

**Comment by hpsoar** [comment]
when I run the example, It firstly shown as the first image, after seconds it become the second image.

there's  an obvious delay.

![screenshot_20180625-175721](https://user-images.githubusercontent.com/1549522/41843973-6d6b78e6-78a1-11e8-9e1d-9ef0c194d07e.png)
![screenshot_20180625-175715](https://user-images.githubusercontent.com/1549522/41843980-7318f692-78a1-11e8-8c23-4e73314d95d1.png)

**Comment by zoechi** [comment]
Debug build or release build?
Please also add the output of `flutter doctor`

**Comment by hpsoar** [comment]
╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 51 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E199, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.0)
[!] IntelliJ IDEA Community Edition (version 2017.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.23.0)
[!] Connected devices
    ! No devices available

! Doctor found issues in 5 categories.

**Comment by hpsoar** [comment]
it's debug build

**Comment by zoechi** [comment]
There is a new beta version out since a while and debug builds are not representative for performance comparison.
