### ISSUE TITLE
MaterialDesign TextField with Icon

### ISSUE THREAD

**Issue by arsensaruhanyan2611** [flutter/flutter#18674]
So, I have a bug with my text field. When I try to use icon: Icon(...), I get this:
[imgur](https://imgur.com/a/pKoAb9j)
First of all, icons isn't inside text fields (which is not great for me). And look at this 'Password' hint on the top of it..
## Steps to Reproduce
I use this code:

```
inputDecorationTheme: InputDecorationTheme(
      border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(5.00))),
    ),


PrimaryColorOverride(
              child: TextField(
                controller: _usernameController,
                decoration: InputDecoration(
                  icon: Icon(Icons.account_circle),
                  labelText: 'Username',
                ),
              ),
            ),
            new SizedBox(height: 12.0),
            PrimaryColorOverride(
              child: TextField(
                controller: _passwordController,
                obscureText: true,
                decoration: InputDecoration(
                  icon: Icon(Icons.play_arrow),
                  labelText: 'Password',
                ),
              ),
            )

```

P.S. If this isn't repository where I have to put this issue, then please tell me about it.

**Comment by arsensaruhanyan2611** [comment]
Ok, I understand, icon is on the outside because of material guidelines. Still, I don't understand this because I have no other choice. Anyway, I think this bug should be fixed.

**Comment by jonahwilliams** [comment]
@arsensaruhanyan2611 to place an icon inside the text field you want to use a `prefixIcon`.  I will look into the password hint though

**Comment by arsensaruhanyan2611** [comment]
Oh.. Thanks! And yeah, this label with a hint looks like this not only in the password field. Just try to use code I attached here.

**Comment by HansMuller** [comment]
Sorry about the icon layout bug. It was fixed in https://github.com/flutter/flutter/issues/18493

**Comment by zhen1991** [comment]
Hi guys!

I am facing a problem in fluter textField and having icon outside when i Tap the TextField. You'll notice the "Details" hintText is not in the cut-out of the InputBorder, as it should have been.
![bildddddddd](https://user-images.githubusercontent.com/37370847/47644797-71afce80-db6f-11e8-82ae-eab06fa105fc.png)
