### ISSUE TITLE
firebase_messaging notification doesn't show if app is killed

### ISSUE THREAD

**Issue by alevittoria** [flutter/flutter#18675]
#Hi! I copy the example from this link:

https://github.com/flutter/plugins/tree/master/packages/firebase_messaging/example

But it works only with app in foreground or in background.
If I send a notification with the app killed from task manager, the notification doesn't show.
This is what I send on body :

```json
{
  "notification": {"body": "message","title": "this is a title"}, 
  "priority": "high",
  "data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "id": "1", "status": "done"}, 
  "to": "myToken"
}
```
Someone can help me?

**Comment by nevi-me** [comment]
On which platform does it do that, and I presume that you've made the required changes on the Android manifest and the necessary places on iOS?

If you're developing with Android Studio/IntelliJ, can you please:

1. open the Logcat with the app killed
2. Select your app in the app filter
3. Send yourself a notification
4. Share the log output that you get.

You also haven't included log details, your Flutter doctor version, etc.

**Comment by alevittoria** [comment]
Ok, now I have try with another device (Samsung Note 8 with Android 8) and all work without problems.
This problem was with an "Huawai P8 Lite"  (Android 5.1) but now we have understand that the problem was linked with power settings for this device and we were able to resolve that.
For completeness this was logcat of Huawai device:

```
V/ActivityManager(  835): Broadcast: Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 pkg=com.yourcompany.flutternotifiche (has extras) } ordered=true userid=0 callerApp=ProcessRecord{3db43b7d 2273:com.google.android.gms.persistent/u0a12}
W/GCM     ( 2273): broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=com.yourcompany.flutternotifiche (has extras) }
```

And this was message from flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.492], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2017.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 32-bit edition
[!] VS Code, 64-bit edition (version 1.24.1)
[√] Connected devices (1 available)

! Doctor found issues in 3 categories.

``

Thanks for your help.
