### ISSUE TITLE
BoxFit.none does not take into account image scale, images always pixelated and scaled incorrectly

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#18682]
My application provides 3 background image variants (1.0x, 2.0x, 3.0x) with a size of 48x48 which are used as repeatable background images, for example:

```dart
new Container(
  width: 200.0
  height: 200.0,
  decoration: new BoxDecoration(
    image: new DecorationImage(
      image: new AssetImage('images/test.png'),
      repeat: ImageRepeat.repeat,
      fit: BoxFit.none,
    ),
  ),
)
```
`BoxFit.none` is used to keep the original size of the image (48x48 units)

Depending on the device pixel ratio, Flutter chooses the correct image variant (3.0x in the screenshot) so that the images are sharp even on high resolution displays.

The problem is that the painting logic does not take into account the scale of the image, it just makes them bigger. For example, on a 3.0x device, the 3.0x image variant (which has a real pixel size of 144x144) is scaled up to a size of 144x144 units, which equals 432x432 real pixels = **a blurry pixel mess**.

This is a serious bug which makes the image variant system unusable.

The bug also occurs when `BoxFit.none` or `BoxFit.scaleDown` are used in a regular `Image.asset `widget:

```dart
new Image.asset(
  'images/test.png',
  height: 200.0,
  fit: BoxFit.none,
  repeat: ImageRepeat.repeat,
)
```

-----
Example application (boxfit branch): https://github.com/sir-boformer/flutter_image_bugs/tree/boxfit

Current Behavior: | Expected Behavior:
------------ | -------------
![](https://user-images.githubusercontent.com/22688477/41732892-983a6edc-7582-11e8-8238-1b42542fceb2.png) | ![](https://user-images.githubusercontent.com/22688477/41732990-e35b3a22-7582-11e8-9b59-cafdb8a98c2b.png)

**Comment by sir-boformer** [comment]
It's probably this line that needs to be changed:

https://github.com/flutter/flutter/blob/09276bea258737e11b109e227f70eac94a4e1691/packages/flutter/lib/src/painting/decoration_image.dart#L369

**Comment by DanielSmith1239** [comment]
I'm having this issue right now...

**Comment by shahinmursalov** [comment]
Have exactly the same issue.

**Comment by sir-boformer** [comment]
It seems like @Hixie is to blame for it.

I thought about contributing a fix for this. I'm just afraid that I'm unable to provide test cases (like golden tests). How would I go about that?

**Comment by Hixie** [comment]
we have a wiki page that describes how to create golden tests: https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package%3Aflutter
