### ISSUE TITLE
Using mysql with flutter

### ISSUE THREAD

**Issue by cconnerj** [flutter/flutter#18687]
Hey I am very new to all of this and these questions may sound stupid. I don't need to know step by step instructions, I just want to know if it is possible.

To preface this, I am an intern practicing with app development and could maybe use the app i'm creating.

- I was told that the company i work for has an existing database in mysql in conjunction with PHP (backed by a firewall) that my app could benefit from. I was wondering if it is at all possible and secure to call from this in my flutter app and not from firebase. 

- Would the sqljocky dependency help me out?

- Also if there is any documentation that could help me with all of this that would be greatly appreciated.

thank you

**Comment by eddywm** [comment]
Flutter as a client library **doesn't really have any relation with the type of database** you are using in your back-end.
You just have to expose a web API where you can do http requests from the Flutter side.

What you need is  simple :
1. Ask your co-workers to give you the API documentation of the backend of your company's system.
2. Get a Flutter HTTP library.
3. Call that API from the client (Flutter mobile app) get the response, it's most of time in Json, transform the Json into plain objects.
4. Render the data into your mobile app.
