### ISSUE TITLE
Binaries in IPAs should be stripped

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#18693]
It looks like IPAs for Flutter apps downloaded from the iOS AppStore include unstripped binaries. Removing the debug symbols from those binaries could significantly reduce the IPA sizes of Flutter apps.

Here is the investigation that led me to believe that binaries in IPAs do not get stripped before they reach the phone of the user:

With an old version of iTunes I was able to download the IPA of the Hamilton app from the iOS AppStore to my Mac. I ran `strip -S` on the bundled `App.framework/App` and `Flutter.framework/Flutter` to strip off its debug symbols and was able to see a great size reduction:

```
~/Desktop/hamilton-unzip/Payload/Runner.app $ ls -l  Frameworks/Flutter.framework/Flutter 
-rwxr-xr-x  1 goderbauer  eng  11642848 Jun 16 11:39 Frameworks/Flutter.framework/Flutter
~/Desktop/hamilton-unzip/Payload/Runner.app $ strip -S  Frameworks/Flutter.framework/Flutter 
~/Desktop/hamilton-unzip/Payload/Runner.app $ ls -l  Frameworks/Flutter.framework/Flutter 
-rwxr-xr-x  1 goderbauer  eng  9285312 Jun 21 10:03 Frameworks/Flutter.framework/Flutter

~/Desktop/hamilton-unzip/Payload/Runner.app $ ls -l  Frameworks/App.framework/App 
-rwxr-xr-x  1 goderbauer  eng  17393824 Jun 16 11:39 Frameworks/App.framework/App
~/Desktop/hamilton-unzip/Payload/Runner.app $ strip -S  Frameworks/App.framework/App 
~/Desktop/hamilton-unzip/Payload/Runner.app $ ls -l  Frameworks/App.framework/App 
-rwxr-xr-x  1 goderbauer  eng  15065024 Jun 21 10:04 Frameworks/App.framework/App
```

Stripping shaves ~2MB off each binaries. We should probably update our process to strip those binaries before uploading them to Apple since Apple doesn't seem to strip them automatically.

**Comment by goderbauer** [comment]
The binaries in question are copied into the IPA as part of the "Embed Frameworks" Build Phase. Xcode actually has a setting to "Strip Debug Symbols During Copy". It defaults to No, but when I set it to Yes, the binary sizes in the resulting IPA are reduced (the first one was build with default settings, the second one with that option set to Yes):

```
~/Desktop $ ls -lisa Runner-default\ 2018-06-21\ 12-33-33/Payload/Runner.app/Frameworks/App.framework/App 
8599095974 61232 -rwxr-xr-x  1 goderbauer  eng  31349280 Jun 21 12:31 Runner-default 2018-06-21 12-33-33/Payload/Runner.app/Frameworks/App.framework/App
~/Desktop $ ls -liosa Runner-stripped\ 2018-06-21\ 12-39-29/Payload/Runner.app/Frameworks/App.framework/App 
8599099224 52816 -rwxr-xr-x  1 goderbauer  eng  27038752 Jun 21 12:39 Runner-stripped 2018-06-21 12-39-29/Payload/Runner.app/Frameworks/App.framework/App

**Comment by goderbauer** [comment]
Just for a test I uploaded both IPAs from the previous comment to Apple's App Store connect and these are the download sizes that Apple reports for them (the only difference between them is the value for option "Strip Debug Symbols During Copy"):

Sizes reported by Apple's App Store Connect with "Strip Debug Symbols During Copy" left at No:
![image](https://user-images.githubusercontent.com/1227763/41745723-c99089a6-755c-11e8-973d-5baef1052813.png)

Sizes reported by Apple's App Store Connect with "Strip Debug Symbols During Copy" changed to YES:
![image](https://user-images.githubusercontent.com/1227763/41745741-d8ccb32c-755c-11e8-8f4e-b0e70a54112a.png)


To me, this indicates that neither Apple nor our Xcode setup strip binaries and the users are downloading unstripped binaries from the store. We should probably change that and strip our binaries.

/cc @cbracken @chinmaygarde @rmacnak-google

**Comment by cbracken** [comment]
I can take a look at this. We probably want to also make sure we generate and ship dSYMs as part of the build too (related #12012).

**Comment by goderbauer** [comment]
Talked offline: We've decided to strip the release-build of Flutter.framework on our bots and produce a prober dSYM file there. Additionally, we will strip App.framework at the place where it is generated in flutter tools.

**Comment by goderbauer** [comment]
The build bots are stripping symbols from `Flutter.framework` starting with https://github.com/flutter/engine/commit/931d3cbbc250dbeec1c485f6bee869a15080ac0e. This reduces the IPA download size of the minimal hello world flutter app by 0.7 MB and the install size of the IPA is reduced by 4MB (both numbers are taken from Apple's App Store Connect).
