### ISSUE TITLE
Drawers and popup menus are no longer stateful

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#187]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 21:22 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1528_

----

e.g. the card_collection.dart demo's drawer's checkboxes don't check when you tap them.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 08, 2015 at 02:38 GMT_

----

Interesting.  It's not clear to me how to fix this bug.  The stock menu tries to solve this problem by calling setState on the navigator, which seems a bit wonky.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 08, 2015 at 02:39 GMT_

----

I guess we can make the contents of the drawer a stateful component and then call setState on that.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 22, 2015 at 19:32 GMT_

----

This issue applies to menus now too.

**Comment by abarth** [comment]
Fixed.

**Comment by Hixie** [comment]
This wasn't fixed.

**Comment by abarth** [comment]
Oh noes!
