### ISSUE TITLE
 drawer's elements are not painted after an element with a 'Chip' trailing is painted

### ISSUE THREAD

**Issue by ebeem** [flutter/flutter#18708]
## Steps to Reproduce

gist: https://gist.github.com/ebeem/0c2bb55565f93324cf48f53a7bcaeafe

note: some elements other than Chip might cause the same behavior
Texts do not cause this behavior and work normally

caused by the PR #18616 
@liyuqian 

## Logs

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.51, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected devices (1 available)

• No issues found!
flutter upgrade  28.66s user 8.47s system 6% cpu 8:52.48 total

```

**Comment by ebeem** [comment]
![1](https://user-images.githubusercontent.com/25146039/41764877-1bdb6466-760b-11e8-9cbc-db26e75bbc34.jpg)
![2](https://user-images.githubusercontent.com/25146039/41764878-1c168870-760b-11e8-9c5e-208aec8ff6d5.jpg)

**Comment by zoechi** [comment]
cc @Hixie

**Comment by ebeem** [comment]
I am not able to reproduce the shader on text, I am running the same app on the same environment, but it looks fine now.

**Comment by zoechi** [comment]
@ebeem should the issue be closed then?

**Comment by ebeem** [comment]
@zoechi 
the drawer issue still exists
the shader is probably there as well, I just don't know how to reproduce it

it's probably caused by the file 'paragraph.dart'
it seems like the author of that file knows the issue and commented it, but his workaround was removed in the commit #18616

this is the code

```
-      if (_overflowShader != null) {
-        // This layer limits what the shader below blends with to be just the text
-        // (as opposed to the text and its background).
-        canvas.saveLayer(bounds, new Paint());
-      } else {
         canvas.save();
-      } 
```

**Comment by ebeem** [comment]
I have changed the title and provided a gist file
I could not produce the blending text issue, hopefully, it will not come back

the other issue regarding a drawer element not being painted has been clarified in details and a gist was provided to reproduce

**Comment by liyuqian** [comment]
Thanks for reporting! I'll take a look and send a fix as soon as I can.
