### ISSUE TITLE
How to find route one distance to another in flutter?

### ISSUE THREAD

**Issue by vijaya06** [flutter/flutter#18706]
i cant understand where i put textfield in google map and how to calculate this?

**Comment by zoechi** [comment]
@Hixie

**Comment by nevi-me** [comment]
Hi @vijaya06, can you provide more details of what you're trying to do? I assume you're using [lat,lng]s?

If so, there's a library called [haversine :: https://pub.dartlang.org/packages/haversine](https://pub.dartlang.org/packages/haversine), which might do what you're looking for.

**Comment by vijaya06** [comment]
i am fresher may be that's why i dont  understand how to implement map in flutter. i want to do map implementation where i could find distance and route between them.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
