### ISSUE TITLE
export: not valid in this context: /Users/rainedAllNight/futter/bin:

### ISSUE THREAD

**Issue by rainedAllNight** [flutter/flutter#18705]
when i update envionment variable, it show me these message
![39cacd36-487a-4ff4-a23b-ea0fb8e1f83c](https://user-images.githubusercontent.com/16357931/41754022-2379d19c-7603-11e8-890f-5000b5db83ed.png)

**Comment by goderbauer** [comment]
Did you maybe mean to type `export PATH=~/flutter/bin:$PATH`?

**Comment by rainedAllNight** [comment]
Yes, my local patch is "~/futter"

**Comment by zoechi** [comment]
@rainedAllNight did you see the missing `PATH=` part in the response?
Did this fix your problem?

**Comment by rainedAllNight** [comment]
it only show me this message "export: not valid in this context: /Users/rainedAllNight/flutter/bin:"

**Comment by rainedAllNight** [comment]
what do you mean "the missing PATH= part in the response"

**Comment by rainedAllNight** [comment]
this is my complete screenshot
![095d0ea2-397d-4785-8a5d-fa831ef16bba](https://user-images.githubusercontent.com/16357931/41903136-bce466be-7967-11e8-9377-a99c7ebe55bb.png)

**Comment by zoechi** [comment]
Seems to be a zsh specific https://unix.stackexchange.com/questions/208607/zsh-export-not-valid-in-this-context

**Comment by rainedAllNight** [comment]
thank you, it is working, but it show me this message after "source $HOME/.bash_profile"
![0197586a-58f1-44ee-b0ec-eda3ceb275ba](https://user-images.githubusercontent.com/16357931/41948979-ed4f8e34-79f1-11e8-9e35-e9738dcfabb8.png)

**Comment by zoechi** [comment]
@rainedAllNight sorry, can't help you here, that's zsh specufic and not related to Flutter.

**Comment by rainedAllNight** [comment]
anyway，thank you very much

**Comment by zoechi** [comment]
I'm going to close this issue because it seems to be only about hot to set an environment variable in ZSH which isn't really related to Flutter.
