### ISSUE TITLE
One of the web page link maybe error in https://codelabs.flutter-io.cn/

### ISSUE THREAD

**Issue by ZzqiZQute** [flutter/flutter#18707]
![error](https://user-images.githubusercontent.com/39512431/41760172-ac9f607e-7624-11e8-9369-4c4ba47898d0.png)

The link surrounded by the red lines should be linked to 
https://codelabs.flutter-io.cn/codelabs/first-flutter-app-pt1-cn/index.html#0 
but now it is linked to it's sister
https://codelabs.flutter-io.cn/codelabs/first-flutter-app-pt2-cn/index.html#0

**Comment by zoechi** [comment]
@Hixie

**Comment by Sfshaza** [comment]
@ZzqiZQute, I just checked and this appears to be fixed. Let me know if you aren't seeing it.
