### ISSUE TITLE
Making scrolling, when the keyboard pop up, more dynamic.

### ISSUE THREAD

**Issue by Norbert515** [flutter/flutter#18714]
With the current implementation the keyboard scrolls right below the TextField.

![](https://user-images.githubusercontent.com/13968468/41531354-56539872-72f3-11e8-992f-fbfde683f1aa.gif)

I made a [PR ](https://github.com/flutter/flutter/pull/18562)to expose the constant (which is currently set to 20.0) to the constructor. This would solve that problem.

I talked to @slightfoot and he said it would also be great to allow setting the alignment (on the screen) besides the scrollPadding.

Also, wouldn't it be better to extract that logic into a separate widget and wrap the EditableText with said widget internally? 
Reusability would benefit a lot from this. For example, if there's another widget which would like to be scrolled into view when focused it could just wrap itself with that widget.

I think something like @slightfoot s' [widget ](https://gist.github.com/slightfoot/5db1582dcc49b1d6602fc7682fc9e987) would do a great job for that. 

What do you think?

**Comment by zoechi** [comment]
The PR was merged and seems to have fixed the issue.
