### ISSUE TITLE
flutter doctor :   [!] VS Code, 32-bit edition (version 1.24.1)

### ISSUE THREAD

**Issue by Simpler1** [flutter/flutter#18717]
## Steps to Reproduce

1. Windows 10, VS Code with the flutter extension v2.14.0
2. Install flutter from [flutter_windows_v0.5.1-beta.zip](https://storage.googleapis.com/flutter_infra/releases/beta/windows/flutter_windows_v0.5.1-beta.zip) 
3. Run `flutter doctor -v`

It complains about VS Code:
```
[!] VS Code, 32-bit edition (version 1.24.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

The Flutter extension is installed in vscode:
![image](https://user-images.githubusercontent.com/5922273/41778673-7a643098-75fd-11e8-94f4-fd3cc5b1c95a.png)

## Full output

```
C:\>flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.5.1 at C:\Programs\flutter
    • Framework revision c7ea3ca377 (3 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\user1\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\user1\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 32-bit edition (version 1.24.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • SAMSUNG SM G935A • e61e98ab • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

Why does flutter doctor complain about VS Code?

**Comment by MichaelSowah** [comment]
seeing the same issue on the latest dev channel but not on the master

**Comment by westy92** [comment]
A shot in the dark here, but have you tried the 64-bit version of vscode?

**Comment by goderbauer** [comment]
Isn't it just complainin about a missing Flutter extension for Vcode?

>  Flutter extension not installed; install from https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

@DanTup

**Comment by LostInBrittany** [comment]
Same here, on a Ubuntu 18.04, and the extension is indeed installed.

```
[!] VS Code (version 1.24.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by Simpler1** [comment]
@goderbauer Yes.  It is complaining about the Flutter extension for VS Code, but the extension is installed (as shown in the original post).  That's the question.  Why is it complaining about an extension that is installed.

**Comment by DanTup** [comment]
There was a change in VS Code recently that broke our detection of the extension on case-sensitive OSes. There's a fix for it in master (https://github.com/flutter/flutter/pull/18515) but it's not available in the beta channel yet.

This warning is safe to ignore; `doctor` not being able to find the extension won't impact the use of Flutter or the VS Code extension in any way. Sorry for the confusion!

**Comment by ndlive** [comment]
same here : [!] VS Code, 64-bit edition (version 1.25.1)
please someone help

**Comment by yaronlevi** [comment]
Got:

> [!] VS Code (version 1.25.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

But the extension is installed correctly in vscode.

**Comment by absin1** [comment]
Seems to be happening because of case mismatch between the plugin name and what flutter checks. Check [18515](https://github.com/flutter/flutter/pull/18515)

**Comment by DanTup** [comment]
@yaronlevi See [this comment further up](https://github.com/flutter/flutter/issues/18717#issuecomment-399652325).

**Comment by Morisf** [comment]
Same issue on MacOs
[!] VS Code (version 1.26.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

But everything was installed

**Comment by ADitya024** [comment]
Just install all plugins of flutter in VS code (64) ,  then run flutter doctor . For me it works.
