### ISSUE TITLE
Offline Copy of Flutter Docs?

### ISSUE THREAD

**Issue by GoogledRoland** [flutter/flutter#18723]
Does anyone here have an offline copy of Flutter documentation?

**Comment by dnys1** [comment]
In the flutter repo, run the script `dev/bots/docs.sh` to generate the docs. It will generate the folder `dev/bots/doc/` which will be fairly large (~650MB).

**Comment by zoechi** [comment]
@GoogledRoland does this mean @dnys1 suggestion didn't work?
What was the problem? Did you get an error message?

**Comment by MartinTello** [comment]
@dnys1 Im on w10 and it didnt work for me. I tried with cmd, powershell and git-bash and always get the same result:
Running docs.sh
Downloading Dart SDK from Flutter engine e54bc4ea1832352c4c92f54ed6919ac5bff154ab...
Unknown operating system. Cannot install Dart SDK.

**Comment by zoechi** [comment]
@MartinTello you're probably still using mingw in powershell. That's covered by #8860 and probably unrelated to this issue about offline Flutter docs..

**Comment by FlutterIODev** [comment]
> In the flutter repo, run the script `dev/bots/docs.sh` to generate the docs. It will generate the folder `dev/bots/doc/` which will be fairly large (~650MB).

when I'm run this command I have an error

`Emad@Emad-PC MINGW64 /D/Program Files/flutter (dev)
$ dev/bots/docs.sh
Running docs.sh
Flutter 0.8.2 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (12 days ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2
dev/bots/docs.sh: line 66: /D/Program Files/flutter/bin/cache/dart-sdk/bin/pub: No such file or directory
`

can you please tell me what I'm doing wrong?

**Comment by zoechi** [comment]
@FlutterIODev If `/D/Program Files/` is the windows `Program Files` folder then your user account probably doesn't have the required permissions. You should install Flutter in a different directory.
See 2) in https://flutter.io/setup-windows/#get-the-flutter-sdk

**Comment by FlutterIODev** [comment]
Hello, thanks for the replay 

No /D/Program Files/ is not the windows Program Files. my windows Program Files is on C partition.

**Comment by FlutterIODev** [comment]
> @FlutterIODev If `/D/Program Files/` is the windows `Program Files` folder then your user account probably doesn't have the required permissions. You should install Flutter in a different directory.
> See 2) in https://flutter.io/setup-windows/#get-the-flutter-sdk

If there is any direct link for downloading the documentation it will solve my problem.

I spent some time searching for offline flutter documentation and I have found a google dive link from [here](https://github.com/flutter/flutter/issues/9955#issuecomment-401955171).

his docsets works prefectly with [Zeal](https://zealdocs.org/) and Intellij ide, but the problem is the conetent on his drive for an older version of flutter.

So I was trying to download a new copy of [Flutter docs](https://docs.flutter.io) html files to repalce it with his old files and then reuse the Zeal with the last copy of the flutter documentation.

**Comment by kinsflow** [comment]
> In the flutter repo, run the script `dev/bots/docs.sh` to generate the docs. It will generate the folder `dev/bots/doc/` which will be fairly large (~650MB).

i used this, it eventually installed some file but how do i use the files?

**Comment by chornbe** [comment]
If only a simple package of HTML and/or PDFs was downloadable. (sigh)

I tried this from every relative path, with and without full pathing, relying on the $path or using full pathspec to the .sh file, with sudo, without, consistent errors on mac os 10.14.5.

BE LESS GOOGLEY. Just compile the docs for download, guys. I can afford the time to hit a link and do other things. I can not afford the time to track down shell script bugs - ps... the file in question actually does exist. :( 

FileSystemException: Cannot open file, path = 'packages/flutter_build/pubspec.yaml' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:547:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:592:18)
#4      findPackages.<anonymous closure> (file:///Users/chris/development/flutter/dev/tools/dartdoc.dart:453:23)
#5      WhereIterator.moveNext (dart:_internal/iterable.dart:439:11)
#6      CastIterator.moveNext (dart:_internal/cast.dart:61:30)
#7      new List.from (dart:core-patch/array_patch.dart:45:19)
#8      Iterable.toList (dart:core/iterable.dart:398:5)
#9      findPackages (file:///Users/chris/development/flutter/dev/tools/dartdoc.dart:456:6)
#10     findPackageNames (file:///Users/chris/development/flutter/dev/tools/dartdoc.dart:441:10)
#11     main (file:///Users/chris/development/flutter/dev/tools/dartdoc.dart:55:26)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

**Comment by eralpkaraduman** [comment]
https://github.com/flutter/flutter/issues/9955#issuecomment-476234675

**Comment by MyracleDesign** [comment]
I think this Issue should be open again. I can't create the documentation of flutter locally on my windows machine to test my documentation changes.

If I try to run docs.sh after I run flutter doctor I get the error message that it cannot find pub file. 
![image](https://user-images.githubusercontent.com/8026644/61586488-8fbfd200-abc9-11e9-94fc-ab2b5bd3a622.png)

I change the pub file to pub.bat it crashes later in the dartdoc.dart where I found the following snippet.
```Dart
/// This will only work on UNIX systems, not Windows. It requires that 'git' be
/// in your path. It requires that 'flutter' has been run previously. It uses
/// the version of Dart downloaded by the 'flutter' tool in this repository and
/// will crash if that is absent.
```

![image](https://user-images.githubusercontent.com/8026644/61586495-d6adc780-abc9-11e9-90cc-dc78a7fc3b56.png)

So it seems that currently on windows os it is not possible to create the docs.

**Comment by iseeflames** [comment]
@amreniouinnovent what do i do with the file after it is downloaded please walk me through it

**Comment by amreniouinnovent** [comment]
@iseeflames  Just open index.html

**Comment by chornbe** [comment]
Am I seriously the only one thinking that if there needs to be so much discussion on how to create/generate docs for reading from local source, that maybe yet again our industry kinda got it wrong?

**Comment by rahmanrezaee** [comment]
tans

**Comment by davey555** [comment]
How can I download the flutter docs

**Comment by skynette** [comment]
cool offline download link https://master-api.flutter.dev/offline/flutter.xml

**Comment by darken-boy** [comment]
j'ai telechargé le fichier  mais je fait quoi ensuite ?

**Comment by Raja3131** [comment]
> cool offline download link https://master-api.flutter.dev/offline/flutter.xml
The Link does'nt work bro

**Comment by darken-boy** [comment]
It is working .....

**Comment by darken-boy** [comment]
you will have some thing like that

<entry>
<version>1.19.0-4.0.pre.124</version>
<url>https://master-api.flutter.dev/offline/flutter.docset.tar.gz</url>
</entry>

**Comment by darken-boy** [comment]
https://master-api.flutter.dev/offline/flutter.docset.tar.gz

this is the link

**Comment by Raja3131** [comment]
I Got This Page Bro. I attached screen shot of it

**Comment by hyokito12** [comment]
> In the flutter repo, run the script `dev/bots/docs.sh` to generate the docs. It will generate the folder `dev/bots/doc/` which will be fairly large (~650MB).

After running the script, you can open the file `dev/docs/doc/api/index.html` and it will show the whole documentation.

**Comment by vyuh** [comment]
I think this link works now. https://api.flutter.dev/offline/flutter.xml

**Comment by CodeHunta** [comment]
> I think this link works now. https://api.flutter.dev/offline/flutter.xml (replace `master-api` with `api`).

Page wasn't found. Gives me a 404 response page.

I am using Windows 10, when I ran `dev/bots/docs.sh` in my flutter directory `C:\src\flutter\flutter>` I got this response: `'dev' is not recognized as an internal or external command operable program or batch file.`

Please I desperately need help with this. Thank you!

**Comment by vimal-gayakwad** [comment]
> 
> 
> > cool offline download link https://master-api.flutter.dev/offline/flutter.xml
> > The Link does'nt work bro


this will work

https://master-api.flutter.dev/offline/flutter.docset.tar.gz

**Comment by kanishkdgrt** [comment]
https://api.flutter.dev/offline/flutter.docset.tar.gz****use this link to download :)****
