### ISSUE TITLE
Documentation request – how to draw a polygon

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18733]
Since Flutter does not have a lot of functionality in terms of bringing in SVGs that can be animated etc, I need to use Custom Painter. That's fine, but I'm finding the documentation to be extremely difficult. The documentation would really benefit from a use case type of narrative.

"Want to draw a polygon? Use XYZ, here's a snippet"

I'm also bugging the fine folks on the Flutter Discord and still having trouble figuring out how to draw a custom shape.

**Comment by sir-boformer** [comment]
I agree with you that the canvas isn't documented very well.

I recommend you to look at Android canvas tutorials. The API is very similar because Flutter is based on the same underlying graphics engine.

**Comment by lukepighetti** [comment]
There is a Fluttie tutorial (egg timer) that recommends rotating the entire canvas to use CustomPainter to act as a facsimile for cylindrical coordinates. I have noticed a few people recommending this as a tutorial in the absence of documentation.

My concern is that rotating the entire canvas a couple hundred times to draw shapes is expensive, but I'm honestly not sure. Again, documentation on best practices with CustomPainter is going to be very helpful for people like me.

**Comment by sir-boformer** [comment]
@lukepighetti Actually that's very cheap. Only the transformation matrix is rotated, not the canvas itself.

**Comment by lukepighetti** [comment]
Good to know, thanks!

**Comment by markusaksli-nc** [comment]
Closing, since this is now documented in [CustomPainter](https://api.flutter.dev/flutter/rendering/CustomPainter-class.html).
