### ISSUE TITLE
how to check current time between two times.

### ISSUE THREAD

**Issue by vithanichandresh** [flutter/flutter#18748]
i have two times.
String openTime = "10:30";
String closeTime = "13:00"

How do i check current time is between openTime and closeTime.

**Comment by ebeem** [comment]
I think this should be a stackoverflow question ...
anyways, use the DateTime class, if your open & close time is in string, then you will have to cast it to DateTime


```
  DateTime before = DateTime.now();
  DateTime after = DateTime.now();
  print(before.difference(after).inMilliseconds);
```

**Comment by sir-boformer** [comment]
```dart
final startTime = DateTime(2018, 6, 23, 10, 30);
final endTime = DateTime(2018, 6, 23, 13, 00);

final currentTime = DateTime.now();
      
if(currentTime.isAfter(startTime) && currentTime.isBefore(endTime)) {
  // do something
}
```

**Comment by zoechi** [comment]
@vithanichandresh I'm going to close this issue because I think the suggestions are sufficient.
Please add a comment if you think otherwise to get the issue reopened.

**Comment by vithanichandresh** [comment]
thanks for help.
and sorry but this ans is not sufficient.
cause i want to compare current date's three time.

   **DateFormat dateFormat = new DateFormat.Hm();
   
   DateTime open = dateFormat.parse("10:30");
    DateTime close = dateFormat.parse("15:30");
    DateTime now = DateTime.now();
   
    print("open ${open}");
    print("close ${close}");
    print("now ${now}");

   output:-
    
  open 1970-01-01 10:30:00.000
  close 1970-01-01 15:30:00.000
  now 2018-06-25 16:36:26.355255

**

in above how i set time in current date.

**Comment by zoechi** [comment]
`dateFormat.parse(...)` doesn't make the time a time of the current day.
What you can do is 
```dart
DateTime now = DateTime.now();
DateTime open = dateFormat.parse("10:30");
open = new DateTime(now.year, now.month, now.day, open.hour, open.minute);
DateTime close = dateFormat.parse("15:30");
close = new DateTime(now.year, now.month, now.day, close.hour, close.minute);
```

**Comment by vithanichandresh** [comment]
thank you.
its working.

**Comment by patelkrunal78** [comment]
You can use the difference method provide by DateTime class

 //the birthday's date
 final birthday = DateTime(1967, 10, 12);
 final date2 = DateTime.now();
 final difference = date2.difference(birthday).inDays;

https://icetutor.com/question/flutter-finding-difference-between-two-dates

**Comment by milanpatel18** [comment]
Similar to https://icetutor.com/question/flutter-finding-difference-between-two-dates/

**Comment by bhanuka96** [comment]
> `dateFormat.parse(...)` doesn't make the time a time of the current day.
> What you can do is
> 
> ```dart
> DateTime now = DateTime.now();
> DateTime open = dateFormat.parse("10:30");
> open = new DateTime(now.year, now.month, now.day, open.hour, open.minute);
> DateTime close = dateFormat.parse("15:30");
> close = new DateTime(now.year, now.month, now.day, close.hour, close.minute);
> ```

Undefinded `dateFormat`

**Comment by Shaydoth** [comment]
@bhanuka96 add the line 

`DateFormat dateFormat = new DateFormat.Hm();`

As seen above

**Comment by fluttercorner** [comment]
[How to Display Current DateTime in Flutter](https://fluttercorner.com/how-to-display-current-datetime-in-flutter/)

**Comment by braysonjohn148** [comment]
`DateTime now = DateTime.now();
                                     now = DateTime.parse(now.toString());
                                     DateTime start = DateTime.parse(livelessons[index].date);
                                     DateTime stop = DateTime.parse(livelessons[index].stop);
                                     
                                     
                                     if(now.isAfter(start) && now.isBefore(stop)) {
                                        print(start.toString()+"-----------------"+now.toString()+"-------------------"+stop.toString());
                                      }else{
                                        print(start.toString()+"**************************************"+stop.toString()); 
                                      }`

OUTPUT:
I/flutter ( 6190): 2020-10-10 22:40:15.000-----------------2020-10-14 09:42:28.375548-------------------202020-10-10 23:10:25.000
I/flutter ( 6190): 2020-10-10 22:40:15.000-----------------2020-10-14 09:42:28.423132-------------------202020-10-10 23:10:25.000

**Comment by rush181200** [comment]
how to check is starttime  = 23:00
endtime = 5:00
currenttime = 00:00
