### ISSUE TITLE
BottomNavigationBar is broken according to material.io specifications

### ISSUE THREAD

**Issue by amrnt** [flutter/flutter#18740]
I've been looking into this for a while. But I guess after the release for the latest version of Material specification, it's time to open this issue/request.

Before the release, I was trying to implement the BottomNavigationBar behaviour that I can find everywhere on my mobile (ios/android). Youtube, instagram, ... they all implement (almost) the `new` Material specification.

Some of the specification are implemented in a way in `CupertinoTabBar` here: https://docs.flutter.io/flutter/cupertino/CupertinoTabBar-class.html

Reading here: https://material.io/design/components/bottom-navigation.html#behavior

```
Tapping a bottom navigation destination results in one of the following:
* It takes the user to the screen associated with it
* On a visited section, it returns the user to their previous scroll position there
* On the current section, it scrolls the page back to the top and may refresh it

Bottom navigation destinations don’t:
* Open menus or dialogs

On Android, the Back button does not navigate between bottom navigation destinations.
```

Understanding the behaviour can result in this implementation that CupertinoTabBar already implements: `Each "tab" has its own routing state`, as well as they the bottom navigation bar is always presents in the application.

For when you tap on the bottom navigation item, one implementation I suggested here: https://github.com/flutter/flutter/issues/15493 that is the answer (kindof) to the point `It takes the user to the screen associated with it`.

I hope I can see feedback and suggestions on this.

**Comment by philiplindberg** [comment]
I've been looking for this exact functionality. Would love to see this implemented.

**Comment by miguelpruivo** [comment]
+1

**Comment by HansMuller** [comment]
It's (now) possible to to use a BottomNavigationBar to select among pages that have their own Navigator. See https://github.com/flutter/flutter/issues/31483#issuecomment-486344199

**Comment by amrnt** [comment]
@HansMuller This is working because you are using `IndexedStack`.

So this not an implementation out of the box to satisfy the specs on material.io, comparing to the behaviour and the implementation of Cupertino which implements it out of the box.

**Comment by HansMuller** [comment]
@amrnt - that's correct, the point of the example in  https://github.com/flutter/flutter/issues/31483#issuecomment-486344199 was just to demonstrate that it's possible to use BottomNavigationBar to select among Navigators. There's still more work to be done to match what's in the current Material spec.

**Comment by a5l3** [comment]
+1

**Comment by Rusfighter** [comment]
Probably a good thing to have this out of box since many major apps like YouTube (aka Google) and Instagram have this per tab stack + global stack. Perhaps someone knows a good implementation which mimics YouTube's navigation behaviour?

**Comment by HansMuller** [comment]
@amrnt - I wrote a medium.com article about bottom navigation bars with a navigator per tab view (per "destination"), cross fading upon tab changes, even sliding the bottom navigation bar in and out of view the the view is scrolled. It's here: https://medium.com/flutter/getting-to-the-bottom-of-navigation-in-flutter-b3e440b9386

**Comment by amrnt** [comment]
@HansMuller A very nice article... I think I will consider it to implement my next NavigationBar 👍

**Comment by doppio** [comment]
Thanks for the great article, @HansMuller! I do hope we see this functionality built into BottomNavigationBar soon, though.

**Comment by jascodes** [comment]
@HansMuller 
> It's (now) possible to to use a BottomNavigationBar to select among pages that have their own Navigator. See [#31483 (comment)](https://github.com/flutter/flutter/issues/31483#issuecomment-486344199)
This uses nesting of Scaffold widget. Is it supported and/or recommended way of doing it?

Thx

**Comment by HansMuller** [comment]
@jascodes Yes, nesting Navigators and Scaffolds is OK.

Note also: the article neglected to explain how nested navigators can work with Android's system back button.

When you press Android’s back button there’s no way for the system to know which navigator to pop, so it uses the app’s top level navigator. In this example we want the current destination’s navigator to be popped instead. To do that the app is wrapped in a WillPopScope widget, whose onWillPop callback vetoes the default behavior and pops the current destination’s navigator instead. Each destination’s navigator gets a GlobalKey so that the onWillPop callback can look it up.

There’s a version of the demo that’s implemented this way here:
https://gist.github.com/HansMuller/0fdde5aac7a3ce6f5bf6c30978bea850

**Comment by jascodes** [comment]
@HansMuller I ran into another tricky situation with multiple scaffolds. Check out the attached image where I require upon touching on FAB bottom sheet sliding up but have bottom menu still there.

![Screenshot from 2019-08-01 16-22-55](https://user-images.githubusercontent.com/1231593/62287999-02a63400-b479-11e9-930c-8f884533fac1.png)

I guess there would be more then one way to do it, what do think about it?

**Comment by therealjohnsummer** [comment]
@HansMuller The multiple navigator solution that you have shown doesn't appear to support showing pages outside of the bottom navigation bar - in this instance, how can one show a full screen page that doesn't have a bottom navigation bar and then when that page is shown - the bottom navigation bar would be shown again.

**Comment by cpboyd** [comment]
@HansMuller With this solution, what's the best option for using a `FirebaseAnalyticsObserver`?  Does one have to be created for each tab, since they can't be reused for different navigators?

Additionally, what's the best option for deep navigation?  Like `/home/list`?

Let's say that you handle an external link that takes you to a `/home/list/item1` (or even from within a different tab)?

**Comment by cpboyd** [comment]
> in this instance, how can one show a full screen page that doesn't have a bottom navigation bar and then when that page is shown - the bottom navigation bar would be shown again.
 
@therealjohnsummer You should be able to use the root navigator from `MaterialApp` with:
```dart
Navigator.of(context, rootNavigator: true)
```

If nesting navigators, it helps to use `navigatorKey` as well to handle that sort of navigation.

**Comment by ayham95** [comment]
I created a small, super easy to use package that let you do that effect [CustomNavigator](https://pub.dev/packages/custom_navigator). And wrote a tutorial about it on Medium you can find it here.

The cool thing about this library that it works efficiently. It creates a nested navigator (which is very unpleasant to do) and uses it for navigation in your widget tree. And of course you can always use the default navigator from MaterialApp

**Comment by HansMuller** [comment]
@cpboyd  - there are significant changes planned for routes and navigation, including support for deep linking. See flutter.dev/go/navigator-with-router

**Comment by bardiarastin** [comment]
opened this issue on Jun 23, 2018 and we still can not have a normal navigation bar with behavior like Instagram which every tab has it's own stack. (this exists in Cupertino tab scaffold but for now, we just have to copy and modify https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/tab_scaffold.dart in order to work in a MaterialApp)

**Comment by jascodes** [comment]
@HansMuller 

> @jascodes Yes, nesting Navigators and Scaffolds is OK.
> 
> Note also: the article neglected to explain how nested navigators can work with Android's system back button.
> 
> When you press Android’s back button there’s no way for the system to know which navigator to pop, so it uses the app’s top level navigator. In this example we want the current destination’s navigator to be popped instead. To do that the app is wrapped in a WillPopScope widget, whose onWillPop callback vetoes the default behavior and pops the current destination’s navigator instead. Each destination’s navigator gets a GlobalKey so that the onWillPop callback can look it up.
> 
> There’s a version of the demo that’s implemented this way here:
> [gist.github.com/HansMuller/0fdde5aac7a3ce6f5bf6c30978bea850](https://gist.github.com/HansMuller/0fdde5aac7a3ce6f5bf6c30978bea850)


In your old reply you posted awesome snippet. But this uses stack and animation of  stack's layer's opacity for switch-fading effect. Is it possible to use something like AnimatedSwitcher but still able to preserve state?

The issue with above approach is that some layers always on top of other; which result in diff animation effect when switching back and forth (you have to think about it for sec. to get what I am saying).

**Comment by celesteking** [comment]
`WillPopScope` will not register Android back button handler if you nest `Scaffold`s. The whole thing is rigged with bugs.

**Comment by HansMuller** [comment]
The example added in https://github.com/flutter/flutter/pull/98440 should address the issues raised here. It is based on nested navigators and scaffolds and can easily be applied to TabBar, BottomNavigationBar, NavigationRail.
