### ISSUE TITLE
Squircle button decoration

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#18752]
Looking for a button decoration to give it squircle corners (g3 curvature continuity) instead of just rounded corners. Will improve the native look on iOS.

**Comment by nesscx** [comment]
#13914

**Comment by goderbauer** [comment]
This looks like a dupe of https://github.com/flutter/flutter/issues/13914.

**Comment by dnfield** [comment]
FYI this is now available as of #26295 in the framework.

#13914 will stay open to track actually using it when on iOS.
