### ISSUE TITLE
OutlineInputBorder borderSide doesn't work.

### ISSUE THREAD

**Issue by kidcosmic** [flutter/flutter#18751]
```dart
TextField(
                  decoration: InputDecoration(
                      border: OutlineInputBorder(
                          borderSide:
                              BorderSide(color: Colors.green, width: 2.0)),
                      helperText: "username"),
                )))
```

Added some logs to OutlineInputBorder's constructor, and paint lines. Looks like the OutlineInputBorder is being recreated with the theme defs (1.0, black). Added some logs to InputBorder and InputDecorator:

```
flutter: CONSTRUCTOR: MaterialColor(primary value: Color(0xff4caf50))
flutter: Copying border with color Color(0x8a000000)
flutter: copy Border
flutter: CONSTRUCTOR: Color(0x8a000000)
flutter: BORDERSIDE : Color(0x8a000000), 1.0
flutter: PAINT: Color(0x8a000000) , 1.0
```

Looks like `input_decorator:1556` copies the border with the theme params depending on state of the input. This makes the `borderSide` option in borders obsolete for `TextField`. 

```dart
final InputBorder border = decoration.border.copyWith(
      borderSide: new BorderSide(
        color: _getBorderColor(themeData),
        width: _borderWeight,
      ),
    );

double get _borderWeight {
    if (decoration.isCollapsed || decoration.border == InputBorder.none || !decoration.enabled)
      return 0.0;
    return isFocused ? 2.0 : 1.0; // Breaks an user defined border weights
  }

  Color _getBorderColor(ThemeData themeData) {
    if (!decoration.enabled) {
      if (decoration.filled == true && !decoration.border.isOutline)
        return Colors.transparent;
      return themeData.disabledColor;
    }
    return decoration.errorText == null
      ? _getActiveColor(themeData)
      : themeData.errorColor; // breaks any user defined colors
  }
```

This kind of evolves to a feature request at this point. The reason border styles break here is because InputDecorator tries to statefully define border color. Please add stateful property assigns for InputDecoration/borders.

**Comment by usercao** [comment]
I also meet this bug.

**Comment by HansMuller** [comment]
Thanks for the report and my apologies for taking so long to respond to it.

I see that @CaiJingLong has taken a stab at correcting the problem: https://github.com/flutter/flutter/pull/19071

This is a bit tricky since by default the border's weight and color depend - in a complex way - on the input decorator's configuration. InputDecorator could just unconditionally use the BorderSide as specified, although it would be more flexible to provide a callback that can compute the borderSide when its needed.

**Comment by AxesandGrinds** [comment]
Reopen this issue. It's 2020 and still borderSize color property doesn't work.

**Comment by AxesandGrinds** [comment]
From here https://github.com/flutter/flutter/issues/17592
the solution that worked for me seems to be 

```
enabledBorder: OutlineInputBorder(
borderRadius: BorderRadius.circular(10.0),
borderSide: BorderSide(color: Colors.red))
```

**Comment by pickledbrill** [comment]
Similar issue here but I'm using `OutlineButton` and try to define the color in the `shape` attribute. 
This doesn't work:
```
OutlineButton(
    shape: StadiumBorder(side: BorderSide(color: Colors.red))
)
```
This work:
```
OutlineButton(
    borderSide: BorderSide(color: Colors.red),
    shape: StadiumBorder()
)
```

**Comment by JulianKowalczuk** [comment]
@HansMuller why is it closed?
enabledBorder/focusedBorder props are ADDITIONAL PROPS.
border prop should WORK AS IT'S DESCRIBED IN DOCS.
I can't believe that this issue is not solved yet, since EVERY APP USES FORM FIELDS and MANY DESIGNS require outlined fields.
How can I force ReactNative lovers to switch to Flutter while this issue is unresolved?!
if it won't be reopened, I will spam Flutter repo with same issue from 3987482742394 accounts...

**Comment by lukepighetti** [comment]
We are completely unable to adjust border radius or color using the following

```dart
  static final _border = OutlineInputBorder(
    borderRadius: BorderRadius.zero,
    borderSide: BorderSide(
      color: Colors.red,
    ),
  );

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      controller: controller,
      decoration: InputDecoration(
        focusedBorder: _border,
        enabledBorder: _border,
      ),
    );
  }
```

**Comment by shafiqruslan** [comment]
This is my workaround. I avoid using OutlineInputBorder instead I use BoxDecoration and put it on parent element of TextField.

`  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        border: Border.all(
          color: Colors.black,
          width: 1,
        ),
        color: kBackgroundColor,
        borderRadius: BorderRadius.all(
          Radius.circular(10),
        ),
      ),
      child: TextField(
        obscureText: true,
        cursorColor: kPrimaryColor,
        decoration: InputDecoration(
          hintText: hintText,
          hintStyle: TextStyle(
            fontWeight: FontWeight.w500,
            color: kLightTextColor,
          ),
          contentPadding: EdgeInsets.all(10),
          labelStyle: TextStyle(
            color: kPrimaryColor,
          ),
          border: InputBorder.none,
        ),
      ),
    );
  }`
