### ISSUE TITLE
Flutter Run hangs at "Starting Xcode build..."

### ISSUE THREAD

**Issue by tomadimitrie** [flutter/flutter#18750]
Sometimes when running a Flutter project an iOS the process hangs at "Starting Xcode build...". The only workaround I found is deleting DerivedData, cleaning the project, building it from Xcode and then trying again to run from Flutter, but this is only temporary. I tried multiple projects but same result.
Running it in verbose mode shows the following (the last line):

> [ios/] /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/.../Downloads/antimony/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/.../pipe_to_stdout

**Comment by mattijsf** [comment]
Very weird, I have this too now. Weird this is: It is stuck for lets say 5+ minutes but as soon as I run `tail -f /path/to/pipe_to_stdout` it immediately continues. At the same time that `tail` command starts printing progress from that point. Blows me away. Looks to me that some process is waiting for another process to pickup that file handle / stream.

Output of the above tail command:
```
demo_project mattijs$ tail -f /var/folders/3q/738s_cl50gz9lyb8q1_pmkgh0000gn/T/flutter_build_log_pipe.53S2df/pipe_to_stdout
 ├─Generating dSYM file...
done
 ├─Stripping debug symbols...
done
 ├─Assembling Flutter resources...
done
 └─Compiling, linking and signing...
```

**Comment by mattijsf** [comment]
Btw, I only experience this when using `flutter run` with the `--release` flag. Debug builds run fine.

**Comment by knopp** [comment]
I never had this until I updated to current master. It really looks like whatever is supposed to be reading from that pipe isn't causing it to block the build process.

**Comment by knopp** [comment]
Looks like it was broken by this commit: https://github.com/flutter/flutter/commit/34bc1e3c8c772c615f8a5c9ce023805ed9ebb1d8 . Flutter stops reading from the pipe after first 'done', but there are more compilation steps pending and thus the compilation script stalls until something reads from the pipe.

**Comment by aam** [comment]
thank you for the report and the analysis @knopp ! #24310 should fix the problem.

**Comment by zoechi** [comment]
This issue is quite old. 
#24139 seems to be a recent one about the same issue

**Comment by mattijsf** [comment]
I tried the PR. It works now!

**Comment by aam** [comment]
thank you for confirmation @mattijsf ! The patch landed in master.

**Comment by JosephDunivan** [comment]
What so what do I have to do? Im experiencing this issue too now.

**Comment by zoechi** [comment]
@JosephDunivan updating to the latest Flutter version.
