### ISSUE TITLE
Debugger doesn't break on Stackoverflow exceptions

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#18765]
Hi,

I yesterday found out that the debugger although set to break on all exceptions doesn't break on an stackoverflow exception. If putting inside a Try-catch it is caught with the correct stack trace.

Here is a imple reproproject that show the problem. 

https://github.com/escamoteur/overflow_exception_repro

PS C:\Entwicklung\FlutterApps\Tests\overflow_exception_repro> flutter doctor -v
[√] Flutter (Channel dev, v0.5.5, on Microsoft Windows [Version 10.0.17134.112], locale de-DE)
    • Flutter version 0.5.5 at C:\Entwicklung\Flutter
    • Framework revision 020e0ef55c (10 days ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 32-bit edition (version 1.24.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
@devoncarew not sure what the correct place is for that issue.
Perhaps https://youtrack.jetbrains.com ?

Just as a note
I found dart-lang/sdk#32966 that should have made it easier to debug such errors.

**Comment by escamoteur** [comment]
Why Jetbrain? This is comes from Flutter its the same on VS code

**Comment by zoechi** [comment]
If it's the same in VS code then it's probably a VM issue and then dart-lang/sdk is the right place.
Jetbrains and Dart team members monitor Jetbrains issue tracker for Dart plugin bugs (what I assumed this is about at first).
I don't think Flutter is involved here.

**Comment by escamoteur** [comment]
I opened one here too https://github.com/dart-lang/sdk/issues/33646

**Comment by devoncarew** [comment]
Thanks for opening issues for this! I think we can track the regression here: https://github.com/dart-lang/sdk/issues/33646.
