### ISSUE TITLE
Issue from website page Fade in images with a placeholder

### ISSUE THREAD

**Issue by Sacchid** [flutter/flutter#18768]
From URL: https://flutter.io/cookbook/images/fading-in-images/

Getting following errors-
1. error: The function 'MyApp' isn't defined. (undefined_function at [fade_in] lib\main.dart:5)
2. error: 'MaterialApp' isn't a function. (invocation_of_non_function at [fade_in] lib\main.dart:13)
3. error: 'Scaffold' isn't a function. (invocation_of_non_function at [fade_in] lib\main.dart:15)
4. error: 'AppBar' isn't a function. (invocation_of_non_function at [fade_in] lib\main.dart:16)
5. error: 'Text' isn't a function. (invocation_of_non_function at [fade_in] lib\main.dart:17)
6. error: 'Stack' isn't a function. (invocation_of_non_function at [fade_in] lib\main.dart:19)
7. error: 'Center' isn't a function. (invocation_of_non_function at [fade_in] lib\main.dart:21)
8. error: 'CircularProgressIndicator' isn't a function. (invocation_of_non_function at [fade_in] lib\main.dart:21)
9. error: 'Center' isn't a function. (invocation_of_non_function at [fade_in] lib\main.dart:22)
10. error: The method 'memoryNetwork' isn't defined for the class 'FadeInImage', but a constructor with that name is defined. (undefined_method_with_constructor at [fade_in] lib\main.dart:23)

**Comment by Sacchid** [comment]
That was because Dart 2 was not enabled.
Running app with `flutter run --preview-dart-2` solved it.
Sorry for bothering.

**Comment by zoechi** [comment]
That's the default in Flutter for several weeks.
Please consider updating to a newer Flutter version using `flutter upgrade`
