### ISSUE TITLE
Google Map & Firebase Messaging Plugin ERROR

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#18766]
Please read README section first.

https://github.com/NTMS2017/Google_Map_and_Notification

**Comment by NTMS2017** [comment]
And this is the flutter doctor -v output

Niyazis-MacBook-Pro:niyazibank niyazitoros$ flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-CY)
• Flutter version 0.5.1 at /Users/niyazitoros/flutter
• Framework revision c7ea3ca (4 weeks ago), 2018-05-29 21:07:33 +0200
• Engine revision 1ed25ca7b7
• Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
• Android SDK at /Users/niyazitoros/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 27.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 9.4.1, Build version 9F2000
• ios-deploy 1.9.2
• CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 25.0.1
• Dart plugin version 173.4700
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
• IntelliJ at /Applications/IntelliJ IDEA CE.app
• Flutter plugin version 25.0.2
• Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
Niyazis-MacBook-Pro:niyazibank niyazitoros$

**Comment by NTMS2017** [comment]
Hi Zoechi,

I already placed similar issue in here. https://github.com/flutter/flutter/issues/18764
Google Groups they advice me to make minimal example and place in GitHub so that can investigate.

**Comment by zoechi** [comment]
What's the difference between #18764 and this issue?
I don't understand what this issue is about exactly.
The title says "Plugin ERROR". If there is such an error the issue should contain the full error output.

**Comment by zoechi** [comment]
According to comments above close as dup of #18764

**Comment by NTMS2017** [comment]
Zoechi, why did you close the issue? Any good news yet?

**Comment by zoechi** [comment]
@NTMS2017 because of your comments. 
I still don't seem to understand what the difference between #18764 and this issue is or what this issue is about.

**Comment by NTMS2017** [comment]
Ok. you can close this one and I am moving details to 18764.
