### ISSUE TITLE
Suggestion: Create repo for Firebase widgets

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#18777]
I've got a couple of widgets that are Firebase specific and I've debated adding them to the plugin repos or not. The **no** argument is that they're not essential to the purpose of working with Firebase / Firestore. The **yes** argument is that they require Firebase to work. I'm not sure whether we want to make a ui-based repo for this specific purpose? My vote is yes, we do want a new repo.

I'm happy to make a third-party repo, or do nothing, but I figured this is probably something that is best maintained centrally?

Android equivalent is https://github.com/firebase/FirebaseUI-Android.

Thoughts?

//cc @collinjackson

**Comment by Kartik1607** [comment]
Since, Firebase / Firestore  have no dependency on Widgets why to include them to the same repo? I think it would be unnecessary and instead they should be bundled into a third-repo. And since, widgets have a dependency on Firebase / Firestore, they can simply use the latest plugin as dependency.

**Comment by lukef** [comment]
That's what I'm proposing. There would be a `flutter/firebase-ui` (or something) repo and that's where the widgets would live.

**Comment by zoechi** [comment]
@lukef is this issue still relevant?

**Comment by lukef** [comment]
In the near term it isn't relevant. I'd suggest it is still a good idea, but the Firebase team probably would have to take it up 😄 

You can close it.
