### ISSUE TITLE
Unclear why a widget transitioning out from a navigator.push gets call to `didChangeDependencies`

### ISSUE THREAD

**Issue by lukaspili** [flutter/flutter#18774]
**Flutter version:** dev 0.5.5 and master 0.5.6-pre.61

**Demo setup:**

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      routes: {'widget-b': (context) => WidgetB()},
      home: WidgetA(),
    );
  }
}

class WidgetA extends StatefulWidget {
...
}

class WidgetB extends StatefulWidget {
...
}
``` 

Perform a navigation from widgetA to widgetB:

```dart
Navigator.of(context).pushNamed('widget-b');
```

**Observed result:** 
`widgetA.didChangeDependencies` gets called once the `navigator.pushNamed` transition has completed. 

**Current documentation:**

> Called when a dependency of this State object changes.
> 
> For example, if the previous call to build referenced an InheritedWidget that later changed, the framework would call this method to notify this object about the change.
> 
> This method is also called immediately after initState. It is safe to call BuildContext.inheritFromWidgetOfExactType from this method.
> 
> Subclasses rarely override this method because the framework always calls build after a dependency changes. Some subclasses do override this method because they need to do some expensive work (e.g., network fetches) when their dependencies change, and that work would be too expensive to do for every build.

I don't know if it's a bug or if the documentation is incomplete. 
Specifically I find the last paragraph misleading. It seems wrong to suggest to do some expensive work based on this event, if it gets also fired once the widget is no longer visible/active in the navigation stack.

**Comment by burkard** [comment]
I'm having a problem with this; when I call the Navigator.pushReplacement in the didChangeDependencies method, it crashes (since the caller page has been disposed); if I use push, instead, the called page is called over and over.
Am I doing something wrong?

**Comment by rrousselGit** [comment]
That happens because when pushing a route, all other routes get temporarily deactivated, which remove the binding between a given Widget and the InheritedWidget it uses.

Once these are reactivated, `didChangeDependencies` is forcibly called to resynchronize everything.

**Comment by enricobenedos** [comment]
@rrousselGit I understand your explanation. But..
I'm using BloC pattern in my app. I normally call `myBloc.fetchData()` in the `didChangeDependencies`. It happens that for example if I push a new widget\page and then turn back, the `didChangeDependencies` is newly called and there is a big resource usage (HTTPS call) that is unusefull because I've already the data. Is it better to move data fetching on `initState()` ?

**Comment by rrousselGit** [comment]
> I normally call myBloc.fetchData() in the didChangeDependencies

That's fine. But you should wrap your call in a `if`:

```dart
MyBloc bloc;

@override
void didChangeDependencies() {
  super.didChangeDependencies();
  final bloc = MyBloc.of(context);
  if (bloc != this.bloc) {
    this.bloc = bloc;
    bloc.fetchData();
  }
}
```

**Comment by micimize** [comment]
The general idea is that widgets often have at least one implicit dependency in the form of routing, so one always has to keep track of the identity of specific dependencies for invalidation in `didChangeDependencies`.

This is especially important to note when developing libraries, because it is easy to assume the only dependencies your component will have are the ones you explicitly defined

**Comment by enricobenedos** [comment]
> @override
> void didChangeDependencies() {
>   super.didChangeDependencies();
>   final bloc = MyBloc.of(context);
>   if (bloc != this.bloc) {
>     this.bloc = bloc;
>     bloc.fetchData();
>   }
> }

But in this case I'm bound to use inherited widget. If I instantiate/use/dispose the bloc only in the "main page" there are no reasons to use inherited widget. 
In my case I have a "Reports (main page)" page that use bloc to fetch data. Reports are showed using a list of cards. User can click on a each card and check the report details. The detail widget has a constructor that accept a details object that is contained in report object.

**Comment by darshankawar** [comment]
Hi @lukaspili,
I tested this on latest stable (1.20.3) and confirmed that `didChangeDependencies` is called only after `initState()` and not everytime after a push.

```
I/flutter (17825): init called
I/flutter (17825): didChangeDependencies called
I/flutter (17825): pushed to route
I/flutter (17825): pushed to route
```

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (2 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

</details>

<details>
<summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      routes: {'widget-b': (context) => WidgetB()},
      home: WidgetA(),
    );
  }
}

class WidgetA extends StatefulWidget {



  @override
  _WidgetAState createState() => _WidgetAState();
}

class _WidgetAState extends State<WidgetA> {
  int _counter = 0;

  @override
  void initState() {
    super.initState();
    print('init called');
  }

  @override
  void didChangeDependencies() {
    print("didChangeDependencies called");
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Widget A'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Tap'),
          onPressed: () {
            Navigator.of(context).pushNamed('widget-b');
            print('pushed to route');
          },
        )
      )
    );
  }
}

class WidgetB extends StatefulWidget {

  @override
  _WidgetBState createState() => _WidgetBState();
}

class _WidgetBState extends State<WidgetB> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Widget B'),
        ),
    );
  }
}
```

</details>

Can you confirm at your end if this is still an issue ?
Thanks.

**Comment by lukaspili** [comment]
Can confirm, does not happen anymore. Thanks!
