### ISSUE TITLE
Missing implementation for updatePassword in firebase_auth plugin

### ISSUE THREAD

**Issue by felixng1028** [flutter/flutter#18783]
The method updatePassword is not implemented in firebase_auth.
It is a critical function in my flutter application, could the team arrange to implement this function?

Thanks a lot.

**Comment by felixng1028** [comment]
Moreover, are there any workaround to update current user password?
Is it possible to use firebase web plugin in a webview to perform this action?

**Comment by zoechi** [comment]
Closing as dup of #16775

**Comment by kroikie** [comment]
@felixng1028

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/780. Any further collaboration will be done there.
