### ISSUE TITLE
GIF image doesn't get disposed even when parent Widget does

### ISSUE THREAD

**Issue by jogboms** [flutter/flutter#18787]
## Steps to Reproduce
1. Navigate to page that contains an Image widget pointing to a GIF
2. Pop out of that page
3. Navigate back to the page
4. For a self-repeating GIF, it appears to be working normally since it just keeps playing, but for a one-time GIF, after popping out of the page, it keeps playing until it ends in the background and even after revisiting the page, it just appears frozen.

## Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.62, on Mac OS X 10.13.3 17D47, locale en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

• No issues found!
```

## Attachment
![thank-you](https://user-images.githubusercontent.com/6208486/41840917-db9a2c88-785e-11e8-93a7-e7e3d171d32b.gif)

**Comment by jogboms** [comment]
@zoechi this might get lost in time. 🙂

**Comment by zoechi** [comment]
@jogboms Yup, time is always too short, also for Googlers :-/
First I/O preparation then vacation season and 3.5k open issues.
Sorry for the delay but all are working hard.

**Comment by jogboms** [comment]
Yeah @zoechi. I can only just imagine. I pushed the app to the Store already. Had to use another GIF. God-speed.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/6230 This _might_ help provide a workaround/temporary fix for this issue.

**Comment by mklim** [comment]
That seems unlikely to me from looking at the description. :( This sounds like a bug in how `Codec` responds (or fails to respond) to the UI state changing. flutter/engine#6230 changes how animated image frames are decoded and cached in memory so that they don't cause the app to crash with out of memory exceptions. That PR shouldn't change anything visually about the animations.

**Comment by keitoro** [comment]
I just run in into the same problem with an animated webp, I was looking into another way to show short animation in an easy light way, but I yet to find a solution. So tried to used webp because of the light weight of the file, but I noticed the twice looping as it is instructed to do only one,  but that I can manage. However the disposing of the widget but still completing the animation is something I can't fix. But kind of workaround can I use for this.

**Comment by Bernardomrf** [comment]
Any news on this issue?

**Comment by torvalde** [comment]
This issue is severe for me right now, it it is possible to force reload asset images I could maybe do that but I have not found a way to do it.

**Comment by nmarafo** [comment]
I think you must dispose like a class with SingleTickerProviderStateMixin.
at initState on this class that return de gif, you must create an AnimationController and after, at dispose, you must dispose that animationcontroller:


class AnimatedLogo extends StatefulWidget {
  @override
  _AnimatedLogoState createState() => _AnimatedLogoState();
}

class _AnimatedLogoState extends State<AnimatedLogo> with SingleTickerProviderStateMixin {
  AnimationController _animationController;
  Animation<double> animation;
  bool isPlaying = false;

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(duration: const Duration(seconds: 4), vsync: this);
    animation = Tween<double>(begin: 0, end:1).animate(_animationController);
    _animationController.forward();
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Image(image: AssetImage("images/optical_illusion.gif"),),
    );
  }
}

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
