### ISSUE TITLE
Entering text in Stocks app on iOS device crashes the app

### ISSUE THREAD

**Issue by davenotik** [flutter/flutter#1878]
Start the stocks app on an iOS device, click the button to add a new company and start typing, and the app crashes. I read somewhere that text input is still not done on Flutter?

**Comment by abarth** [comment]
Text input isn't done, but we should be beyond the "it crashes" stage.  :)

**Comment by abarth** [comment]
I think I have a fix.

**Comment by abarth** [comment]
I couldn't actually reproduce the crash in the simulator, but I did fix two pieces of bad behavior:

https://github.com/flutter/engine/pull/2401
https://github.com/flutter/flutter/pull/1880

Once those land, I'll try this with a real iOS device in the office.
