### ISSUE TITLE
Error: Unable to update Dart SDK

### ISSUE THREAD

**Issue by JakePrim** [flutter/flutter#18790]
## Steps to Reproduce

flutter doctor

## Logs

Checking Dart SDK version...
无法将“Unblock-File”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查
名称的拼写，如果包括路径，请确保路径正确，然后重试。
所在位置 行:1 字符: 13
+ Unblock-File <<<<  -Path 'C:\Users\linksus\flutter/bin/internal/update_dart_s
dk.ps1'; & 'C:\Users\linksus\flutter/bin/internal/update_dart_sdk.ps1'
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Downloading Dart SDK from Flutter engine 1ed25ca7b7e3e3e8047df050bba4174074c9b33
6...
Import-Module : 未能加载指定的模块“BitsTransfer”，因为在任何模块目录中都没有
找到有效模块文件。
所在位置 C:\Users\linksus\flutter\bin\internal\update_dart_sdk.ps1:46 字符: 14
+ Import-Module <<<<  BitsTransfer
    + CategoryInfo          : ResourceUnavailable: (BitsTransfer:String) [Impo
   rt-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Comm
   ands.ImportModuleCommand

Error: Unable to update Dart SDK. Retrying...

```
```

**Comment by DanTup** [comment]
What version of Windows and PowerShell do you have? (You can type `$PSVersionTable` into a PowerShell prompt to get version info).

`Unblock-File` was added in PowerShell 3.0 so I wonder if you're on something older?

**Comment by JakePrim** [comment]
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by DanTup** [comment]
This looks like PowerShell Core. Did you use that deliberately? As far as I can tell, PowerShell Core is a restricted set of PowerShell:

> Any usage of .NET-based functionality (e.g. C# cmdlets, Add-Type, and the invocation of static .NET Methods), relies on the .NET Core runtime. This means PowerShell Core is limited to the functionality exposed by .NET Core and .NET Standard.

I guess the cmdlets used by Flutter are not available in PowerShell Core. Can you try from a "full" PowerShell console (`powershell.exe`, instead of `pwsh.exe`) and let me know if that works. If so, there should probably be some detection and a useful error (or even a review of whether supporting PowerShell Core is feasible).

**Comment by DanTup** [comment]
@JakePrim To confirm - was this issue because you were running in PowerShell Core? (If so, I think we can detect it and add a message to make it clearer in future).

**Comment by pitoszud** [comment]
Just run into similar problem:
**Steps:**
flutter upgrade

**Log**
 The term 'Unblock-File' is not recognized as the name of a cmdlet, function, sc
ript file, or operable program. Check the spelling of the name, or if a path wa
s included, verify that the path is correct and try again.
At line:1 char:13
+ Unblock-File <<<<  -Path 'E:\flutter\flutter/bin/internal/update_dart_sdk.ps1
'; & 'E:\flutter\flutter/bin/internal/update_dart_sdk.ps1'
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Flutter requires PowerShell 5.0 or newer.

The PowerShell exe file is located in C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

I read that the naming convention was a design mistake admitted by Microsoft. The product version is 6.1.7600.16385 in my case. The v1.0 indicates that this is version 6.1 (Service Pack 1) not 1.0 as the folder name suggests.
Works perfectly fine on Windows 10, but Windows 7 has this issue.

The strange thing is that the upgrade was running fine after "Flutter requires PowerShell 5.0 or newer."
Building flutter tool...
Running pub upgrade...
Upgrading Flutter from E:\flutter\flutter...
Checking out files:   3% (26/668)
Checking out files:   4% (27/668)
Checking out files:   5% (34/668)
Checking out files:   6% (41/668)
Checking out files:   7% (47/668)
Checking out files:   8% (54/668)
....

Until it started checking Dart SDK version:
Checking Dart SDK version...
The term 'Unblock-File' is not recognized as the name of a cmdlet, function, sc
ript file, or operable program. Check the spelling of the name, or if a path wa
s included, verify that the path is correct and try again.
At line:1 char:13
+ Unblock-File <<<<  -Path 'E:\flutter\flutter/bin/internal/update_dart_sdk.ps1
'; & 'E:\flutter\flutter/bin/internal/update_dart_sdk.ps1'
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

'Flutter requires PowerShell 5.0 or newer.

**Comment by DanTup** [comment]
@pitoszud if you run `$PSVersionTable` in PowerShell, what's the output look like?

**Comment by pitoszud** [comment]
2.0 ?!?!  I'll ask IT to update to PS 5.0 or 5.1 and will update the issue.

Both VScode and Android Studio don't show any error message after e.g flutter packages get, (just running and waiting for resources), so it would be useful to add an exception error message to the extension/plugin if PS 5.0 is indeed required.

Name                           Value
----                           -----
CLRVersion                     2.0.50727.8806
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1

**Comment by DanTup** [comment]
PoSh v5 is required by Flutter, not the editor extensions. It probably doesn't make sense to encode Flutter's requirements into the editors (running `flutter doctor` is somewhat supposed to do that), however they should still show the error message from Flutter if it complaints about this.

If you could open an issue at https://github.com/Dart-Code/Dart-Code with a screenshot of what you see and exactly what you did/command you ran, I'll do some investigation into why you're not seeing suitable errors.
