### ISSUE TITLE
any timeline regarding support for dynamic link ? (receiving)

### ISSUE THREAD

**Issue by superciccio** [flutter/flutter#18797]

**Comment by dedeswim** [comment]
Maybe you can take a look at the official Firebase Dynamic Links [plugin](https://pub.dartlang.org/packages/firebase_dynamic_links) for Flutter for the generation, and at [this](https://github.com/avioli/uni_links) repository by @avioli to handle them

**Comment by zoechi** [comment]
@superciccio I'm going to close because there are plugins available as suggested by @dedeswim .
Please add a comment if this doesn't match your requirements to get the issue reopened.
