### ISSUE TITLE
Replicate the iOS health app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#18804]

**Comment by jslavitz** [comment]
Is this from an aesthetic standpoint on a functionality standpoint as well?

**Comment by xster** [comment]
Both. It's to make sure we can be aesthetically accurate and ergonomically easy to do as well.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
