### ISSUE TITLE
Debug apk is  different with the release apk

### ISSUE THREAD

**Issue by pp126** [flutter/flutter#18818]
I copied a demo from gallery-animation and I changed something.  The demo running well on debug mode(Android) ,but when I packaged on released mode ,the demo's animation  not worked。

**Comment by mraleph** [comment]
Can you post a reproduction of the issue? We will need more information to help you resolve it.

**Comment by pp126** [comment]
@mraleph Sorry about that.I copied these files : home.dart, sections.dart, widgets.dart
![image](https://user-images.githubusercontent.com/24835186/41894715-655574ac-7952-11e8-8d1e-3bb97ad529b6.png)
I rename the  'home.dart'  to 'main.dart'  and I  added the 'main'   function in this dart file .
![image](https://user-images.githubusercontent.com/24835186/41894820-d4b08e2c-7952-11e8-943a-4ec04d847e66.png)
Like this,if I run it on debug mode(Android studio),the animation is the same of Gallery.But I build release with "flutter build apk",the animation is disappeared.
I hope you can understand my bad English.

**Comment by pp126** [comment]
@mraleph I got a picture:
![image](https://user-images.githubusercontent.com/24835186/41895256-1a4a6f10-7954-11e8-8134-23aa9c4903b3.png)
the release apk like this,the auto_animation is not worked

**Comment by mraleph** [comment]
Thanks! Can you also attach the output of `flutter doctor` so that we know which version of Flutter you are running?

**Comment by pp126** [comment]
@mraleph I tried to release the Gallery ,the issue disappeared,   it worked well   on both mode.   But when I copied the Animation module out  and  released it , the problems arise。

**Comment by mraleph** [comment]
@pp126 I have tried reproducing this and unfortunately I was not able to. 

I copied the animation module out and run it on its own - and works both in release and debug mode for me. 

Could you put the code that reproduces the problem for you somewhere, e.g. create a repo on GitHub and put all the code there. 

(Note: one thing to note is that animation demo also depends on some assets from flutter_gallery_assets. Did you copy those?)

**Comment by pp126** [comment]
@mraleph Thanks a lot,I have pulled my code on GitHub's repertory。https://github.com/pp126/animation_test

**Comment by pp126** [comment]
@mraleph Excuse me.I checked my code again,I couldn't found the problem out.Help please.

**Comment by mraleph** [comment]
Unfortunately, I don't have access to either. @Hixie can somebody try to repro on S6/S8 if we have those in the device lab?

**Comment by pp126** [comment]
@mraleph Thank you very much. I will check my code again and test it on more devices.

**Comment by zoechi** [comment]
@pp126 Is this still an issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by pp126** [comment]
@zoechi Please open this issue.  Today I tried  again. I copy the same code from GitHub(https://github.com/pp126/animation_test),when I run with debug mode on Android device ，animation it's woked. But I run released mode ,it's not woked.
Flutter version: stable, v1.2.1

**Comment by pp126** [comment]
@mraleph I think you can reappearance of this bug .1,create a new flutter project .2,copy the dart code from https://github.com/pp126/animation_test.

**Comment by escamoteur** [comment]
Hi,
could you please tell me if this bug still appears on the latest stable version?

**Comment by pp126** [comment]
@escamoteur I have builded a release apk again.This bug appeared again. 
  code : https://github.com/pp126/animation_test

**Comment by pp126** [comment]
@escamoteur 
![image](https://user-images.githubusercontent.com/24835186/65814400-cb9f9500-e213-11e9-9ea7-8a022bcea850.png),  This is my SDK version.

**Comment by escamoteur** [comment]
could you please try again with creating a new project and copy the files over? There has been a lot of changes in the meantime.

**Comment by escamoteur** [comment]
Could you perhaps make an gif of what happens in debug and what happens in release mode?

**Comment by pp126** [comment]
@escamoteur I created a new project,It dosen't work.
![video_2019-10-02_09-36-10](https://user-images.githubusercontent.com/24835186/66012198-cfc00100-e4f8-11e9-883a-a62b017c1942.gif)

**Comment by escamoteur** [comment]
@pp126 thanks for sending the Video, I'm not sure what is wrong?

**Comment by pp126** [comment]
@escamoteur Sorry!  I mean  this page widget's spring disappeared. when I slide the widget,it should be auto slipping to top or bottom.But it doesn't work on release apk (debug mode is ok).

**Comment by escamoteur** [comment]
Could you please add a gif of the debug behaviour?

**Comment by pp126** [comment]
@escamoteur 
![video_2019-10-04_10-17-50](https://user-images.githubusercontent.com/24835186/66176463-74287b80-e690-11e9-9a7e-96881ae6c9bd.gif)

**Comment by escamoteur** [comment]
I'm not sure that I saw a difference. Could you try to describe t so that I know what to look for?

**Comment by pp126** [comment]
@escamoteur 
![telegram-cloud-document-5-6107288884679278699](https://user-images.githubusercontent.com/24835186/66248671-3729bb00-e75c-11e9-9697-12b68b59904c.gif)

**Comment by iapicca** [comment]
Hi @pp126 
are you still experiencing this issue with the latest stable version of flutter?
If so can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
