### ISSUE TITLE
Issue from website page Testing Flutter Apps

### ISSUE THREAD

**Issue by mockturtl** [flutter/flutter#18813]
From URL: https://flutter.io/testing/

Can I run `flutter test` on GitLab CI?  (I think the answer is yes, e.g. [flutter_redux](https://github.com/brianegan/flutter_redux/blob/master/.gitlab-ci.yml))  

Could the docs link to instructions (as with Travis)?

**Comment by zoechi** [comment]
Can you please elaborate a bit more about what is unclear?
Why do you think there is something special required for Travis?

**Comment by mockturtl** [comment]
@zoechi The [CI section](https://flutter.io/testing/#continuous-integration-and-testing) links to info about fastlane and Travis.

I suggest the docs should also link to information for **GitLab CI**, to emphasize that it's also supported (not only GitHub).
