### ISSUE TITLE
TextField maxLines = null should occupy all the area available to it

### ISSUE THREAD

**Issue by d-silveira** [flutter/flutter#18825]
This is my opinion, so check if it makes sense to you.
Personally I think what makes sense is that if you set ``maxLines=null`` it logically means it is unbounded, reason why the textField should inherit it's parents constraints instead of starting with one line and growing to it. 
If the current behaviour is required by some people, then I suggest a flag be added to control whether it should minimize or maximize it's footprint, similarly to the column with it's  ``MainAxisSize.min`` and ``MainAxisSize.max``
This is what I propose so that the TextField's syntax makes a little more sense, at least to me.

**Comment by InsanityOnABun** [comment]
I would like to see this as well.

**Comment by zoechi** [comment]
@InsanityOnABun Upvote using add reaction on the initial comment instead of a comment would make it easier to track the number of affected developers and set the priority.

**Comment by justinmc** [comment]
Indeed we can't change the current API since we need to maintain backwards compatibility, but I've proposed adding an `expands` parameter that should make this sort of thing doable: https://github.com/flutter/flutter/pull/27205

**Comment by zoechi** [comment]
Looks like a dup of #15388

**Comment by justinmc** [comment]
Closing this with https://github.com/flutter/flutter/pull/27205.

With that PR, you can allow a `TextField` to inherit its parent's constraints by setting the new `expands` parameter to true.  Setting `maxLines: null` will continue to mean that the `TextField` grows with its content, in order to maintain backwards compatibility.
