### ISSUE TITLE
Incorrect value of bool.fromEnvironment('dart.vm.product') in release mode

### ISSUE THREAD

**Issue by WoodyGuo** [flutter/flutter#18829]
We've been stripping the debug/verbose logs out from the release build with the following code:
```
  const bool isReleaseMode = const bool.fromEnvironment('dart.vm.product');
  if (isReleaseMode) {
    debugPrint = (String message, {int wrapWidth}) {};
  }
```

It was working fine, but got broken since we upgraded Flutter to v0.5.1.
If isReleaseMode is set to true by hand, then the logs are stripped out as expected.

The following is the output of running `flutter doctor -v':
```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-CN)
    • Flutter version 0.5.1 at /Users/woody/apps/flutter
    • Framework revision c7ea3ca377 (4 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/woody/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/woody/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
```

**Comment by mraleph** [comment]
This is because we moved constant evaluation into a Kernel-to-Kernel transformation: this transformation does not correctly set `dart.vm.product` in release Flutter builds. This needs to be wired specially (we have a CL in the pipeline but landing of it got delayed for non-technical reasons).

As a workaround you should be able to do this:

```
$ flutter build aot --release --extra-front-end-options=-Ddart.vm.product=true
```

/cc @sjindel

**Comment by WoodyGuo** [comment]
Thanks for the information and the workaround, which we'll use while waiting for the issue to be resolved.

**Comment by mraleph** [comment]
@sjindel could you land a change to pass `-Ddart.vm.product=true` to CFE when building release builds? That should be one liner.

**Comment by sjindel-google** [comment]
I'm addressing this in https://github.com/flutter/flutter/pull/18876.

**Comment by mraleph** [comment]
This should be fixed now on the master branch.
