### ISSUE TITLE
url_launcher SMS Scheme act differently on IOS and Android

### ISSUE THREAD

**Issue by sabik22** [flutter/flutter#18823]
Scheme: 
`'sms:98456454&body=text%20message'`
IOS: Working
Android: Now Working. (All numbers from scheme pass as number) 

Scheme: 
`'sms:98456454?body=text%20message'`
IOS: Now Working. (All numbers from scheme pass as number) 
Android: Working

Conclusion: i have put '&' between message sms and body to work on IOS, and '?' for android..

**Comment by lilipu1** [comment]
do you find the solution?

**Comment by zoechi** [comment]
You could use https://docs.flutter.io/flutter/dart-io/Platform-class.html to decide what string to pass.

**Comment by jaumard** [comment]
@zoechi that's what I used, look like an easy fix to do on plugin side to do it automatically 
```
final separator = Platform.isIOS ? '&' : '?';
      _launchURL('sms:$number${separator}body=${Uri.encodeFull(content)}&subject=${Uri.encodeFull(subject)}');
```

**Comment by lenlo** [comment]
Please don't use Uri.encodeFull when escaping query parameters. It does not escape valid URL syntax, like '?', '&', '#', etc. Use Uri.encodeComponent or Uri.encodeQueryComponent instead.

**Comment by stuartmorgan** [comment]
`url_laucher` just hands URIs to the OS; the difference here is due to the platforms themselves, not the plugin.

We could potentially have a utility method just for SMS, but that's kind of is from an API perspective. It might be better for someone to make a wrapper package for handling specific URI schemes.

**Comment by stuartmorgan** [comment]
And in fact, it looks like https://github.com/fluttercommunity/flutter_sms does exactly that.

**Comment by WhileTrueCH** [comment]
Does `url_launcher` support multiple recipients? Something like `sms:1111111;6666666;7777777&body=Testing`

**Comment by akashgk** [comment]
what is the query param for SMS body in iOS?

**Comment by stuartmorgan** [comment]
We're going to keep `url_launcher` focused on being a general hand-off tool, and leave scheme-specific APIs for wrappers like the one linked above, so closing.
