### ISSUE TITLE
hot reload does't work in as

### ISSUE THREAD

**Issue by lizuojing** [flutter/flutter#18834]
![image](https://user-images.githubusercontent.com/4328469/41915465-5eaedf2c-7988-11e8-8519-75e3397beed2.png)

**Comment by lizuojing** [comment]
hot reload does't work in android studio.some days ago,it worked very well,but tody i find it does't work at all. i want to know why i can't click hot reload button.tks

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by vladaman** [comment]
We struggle with hot-reload too. Very often it just does not reload for various reasons and it's unreliable. I'd say I need to recompile and run app every 5 minutes or so. I either get error that flutter is not running or the changes just don't reflect in the emulator.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.24.1)
[✓] Connected devices (1 available)
```

**Comment by lizuojing** [comment]
![image](https://user-images.githubusercontent.com/4328469/41952692-e4c2e68c-7a03-11e8-9558-4294f64b7992.png)
I have already installed the flutter plugin in android studio,but the console still display this issue? Have anyone come across this problem？

**Comment by zoechi** [comment]
@lizuojing the message is about the plugin not being installed in IntelliJ. It seems you have installed IntelliJ and AS and you need to install the plugin on both (if you use both with Flutter), otherwise you can ignore that message.

**Comment by lizuojing** [comment]
@zoechi  I have already installed the flutter plugin in android studio,but when i excute 'flutter doctor' the console still display the issue?I want to know why it come across this problem! I try reinstall the plugin but it still does't work.

**Comment by zoechi** [comment]
Because AS and IntelliJ are two different things ;-)
If you don't use IntelliJ with Flutter, you can ignore that warning.

**Comment by zoechi** [comment]
Might be a dup of #16881

**Comment by zoechi** [comment]
Closing as dup of #16881

**Comment by zoechi** [comment]
@coderjiang  What does "not working" mean exactly?

**Comment by zoechi** [comment]
@coderjiang after hot-reload applies code changes it runs `build()` of your root component.
Code changes to code that is not invoked by `build()` won't have any effect.
In your 2nd example there is no code invoked by `build()`.

https://flutter.io/docs/development/tools/hot-reload#limitations

> After the VM updates classes with the new versions of fields and functions, the Flutter framework automatically rebuilds the widget tree, allowing you to quickly view the effects of your changes.
