### ISSUE TITLE
Keep chained scaffold bottomBar below the keyboard

### ISSUE THREAD

**Issue by d-silveira** [flutter/flutter#18837]
I have a textfield inside an expanded and below it a horizontal listview, tried both in a column, and also  having the horizontal listview in a bottombar, but in both cases the behaviour is the same, when the keyboard appears, the list is kept above the keyboard, making the textfield area smaller than I wanted it to (I have a big appBar).
The obvious solution is to have the listview kept below the keyboard, because it isn't needed when typing on the textfield.
The problem is that I can't seem to have it be ignored by the keyboard driven resize. Even after setting it has a bottomBar. Granted this scaffold is inside another, but according to the Material spec, the bottomBar should always be kept below the keyboard, which is exactly what I want to accomplish.

What is the magic necessary to force a widget to be kept below the keyboard? Maybe I could manually reproduce it on a specific widget.
Or maybe there should be a flag for Widget to mark it as ignored by keyboard...

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/material/Scaffold/resizeToAvoidBottomPadding.html might be what you're looking for (not sure)

**Comment by d-silveira** [comment]
thanks @zoechi , unfortunatelly it was the first thing I tried, and it doesn't work, all it does is hide my textfield if I set it ti true (or leave it as default), so I have it to false

**Comment by zoechi** [comment]
You might also wrap your content into a scrollable.
Perhaps the discussion in #10826 can give some hints.

**Comment by d-silveira** [comment]
what I'm asking is the opposite of that discussion. I need to keep something below the keyboard, whilst focusing on the textfield above it. 
At least putting it on the bottomBar should work according to spec, but in this case, which is a chained scaffold it seems not to

**Comment by zoechi** [comment]
I don't have good knowledge about this topic, I'm mostly throwing in related discussions I remember seeing that might give you some hints. I'll leave it to more knowledgeable people.

Can you please add the output of `flutter doctor`.

**Comment by d-silveira** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!

**Comment by goderbauer** [comment]
@d-silveira Any chance you can include some example code? These issues are way easier to fix/debug with example code that shows the behavior.

**Comment by sGurkaran** [comment]
did you changed android:theme in manifest file?

**Comment by sGurkaran** [comment]
@d-silveira did you changed the android:theme in manifest file?

**Comment by pedromassangocode** [comment]
Hi @d-silveira 
Can you please confirm if this issue is still valid with the latest Flutter?

Thank you

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
