### ISSUE TITLE
flutter logs leaves orphaned tail processes behind

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1883]
It leaves orphaned tail processes when listening to ios simulator logs. I haven't checked, but it likely leaves `adb logcat` processes orphaned as well (for adb devices).

We could listen to SIGINT and try and cleanup spawned processes (https://api.dartlang.org/1.12.0/dart-io/ProcessSignal/watch.html). Or we could move to a dart only solution for tailing files.

**Comment by eseidelGoogle** [comment]
Have we seen this since?  I recall seeing it in person, but haven't heard of a report since.

**Comment by devoncarew** [comment]
The new `log` code will cleanup the logs listeners on exit (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/logs.dart#L64).
