### ISSUE TITLE
Add option to override search hint for full screen material search

### ISSUE THREAD

**Issue by hundeva** [flutter/flutter#18831]
The following example produces a very basic search screen. When the query is empty, it is displaying "_Search_" in the query field, which comes from `hintText: MaterialLocalizations.of(context).searchFieldLabel` (currently 425th line of search.dart).

Please add an option to override this hint text, and default back to it only when nothing else is provided. It could be either part of the passed delegate, or the way the search is opened, a new optional parameter could be provided, similar to the query parameter.

Example code:

```dart
class SearchApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Search demo'),
        ),
        body: Center(
          child: Builder(
            builder: (context) => MaterialButton(
                  child: Text('Search'),
                  onPressed: () => showSearch(
                        context: context,
                        delegate: DummyDelegate(),
                      ),
                ),
          ),
        ),
      ),
    );
  }
}

class DummyDelegate extends SearchDelegate<String> {
  @override
  List<Widget> buildActions(BuildContext context) => [];

  @override
  Widget buildLeading(BuildContext context) => IconButton(
        icon: Icon(Icons.close),
        onPressed: () => Navigator.of(context).pop(),
      );

  @override
  Widget buildResults(BuildContext context) => Text('Result');

  @override
  Widget buildSuggestions(BuildContext context) => Text('Suggestion');
}
```

Suggested solution 1:
```dart
                  onPressed: () => showSearch(
                        context: context,
                        delegate: DummyDelegate(),
                        hintText: 'My hint text',  // new way of overriding hint text
                      ),
```

Suggested solution 2:

```dart
class DummyDelegate extends SearchDelegate<String> {
  @override
  String get hintText => 'My hint text'; // new way of overriding hint text
  // rest of the delegate here
}
```

**Comment by marinat** [comment]
How to solve such now?

**Comment by mannprerak2** [comment]
Someone posted a workaround here 
https://stackoverflow.com/questions/54518741/flutter-change-search-hint-text-of-searchdelegate

**Comment by speanut-land** [comment]
the searchTextField hint text is still "Search"!!!  I add this following code ,  it doesn't work... so flutter 1.7.8 how to solve such now?
 @override
  String get hintText => 'My hint text';"

**Comment by shihaohong** [comment]
This should be fixed with https://github.com/flutter/flutter/pull/36409
