### ISSUE TITLE
Text input does not replace selected text in 0.5.1, this worked in 0.4.4

### ISSUE THREAD

**Issue by rmarau** [flutter/flutter#18853]
The problem occurs when typing over a selection in a TextField. 
Instead of replacing the selected piece with the typed char, it prepends the char to the start of selection and positions the cursor next to the prepended char.

Now, the bug occurs with TextInputType.number and running in Android (IOS is fine).

The behaviour was fine in Beta 0.4.4. I nailed the problem to this commit in flutter:
677df7c3511ef25564a39175dcd802ab04012726, which points to commits on May 24 in flutter/engine

Btw, also tested against the master branch today with no luck.

**Comment by rmarau** [comment]
The code to reproduce.
Controller and focusNode are there just for convenience. It fails anyway without them.

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        // This is the theme of your application.
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  TextEditingController myController;
  final FocusNode _focus = new FocusNode();

  @override
  void initState() {
    super.initState();
    myController =  new TextEditingController(text: "123456");
    _focus.addListener(_onFocusChange);

  }

  @override
  void dispose() {
    myController.dispose();
    super.dispose();
  }

  void _onFocusChange() {
    if (_focus.hasFocus)
      myController.selection =
          TextSelection(baseOffset: 0, extentOffset: myController.text.length);
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new TextField(
          keyboardType: TextInputType.number,
          controller: myController,
          focusNode: _focus,

        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by rmarau** [comment]
The problem is still there using dev v0.7.1.

Another way to reproduce the problem using gallery:
- Open Gallery in Android (not IOS)
- Go to Material > Text Fields
- Type in the Salary form
- Long press to select all
- Type again

The selected text should have been replaced with the new one typed and it is not.

**Comment by jonahwilliams** [comment]
cc @jslavitz

**Comment by zoechi** [comment]
Seems https://github.com/flutter/engine/pull/6113 should fix that

**Comment by rmarau** [comment]
Fixed! Thks
