### ISSUE TITLE
Embedder API should support receiving responses from messages

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#18852]
Per the embedding header's description of FlutterPlatformMessage's response_handle:
  // The response handle on which to invoke
  // |FlutterEngineSendPlatformMessageResponse| when the response is ready. This
  // field is ignored for messages being sent from the embedder to the
  // framework.

This means FlutterEngineSendPlatformMessage can't receive responses from messages sent into Flutter, which is inconsistent with the messaging APIs on mobile.

This is especially problematic given that MethodChannel eats all exceptions that happen during message processing and turns them into error responses; if it's impossible to set up a handler to receive those responses on the native side, debugging problems is *very* painful. (E.g., https://github.com/google/flutter-desktop-embedding/pull/80 took me several unnecessary hours to debug because the type exception was being silently dropped.)

**Comment by stuartmorgan** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
Please feel free to file more issue related to debugging experience while working with the embedder API.

**Comment by GeertJohan** [comment]
Is this on the roadmap? I'd love to implement replies to host->client messages for [go-flutter](https://github.com/go-flutter-desktop/go-flutter).

**Comment by AndruByrne** [comment]
Chinmay, I hope you take this the right way, but I could kiss you; thanks for fixing the bug I just spent 8 hours finding!!!

`  -   nullptr);	     + response);`

![nicolson_nodding](https://user-images.githubusercontent.com/3012429/62239165-34d86880-b389-11e9-9e63-08a24d8e876d.gif)

**Comment by smanilov** [comment]
Just a heads up that https://github.com/flutter/engine/blob/master/shell/platform/common/cpp/client_wrapper/include/flutter/method_channel.h:55 still refers to this issue, in case you missed it :)

**Comment by stuartmorgan** [comment]
@smanilov Thanks, good catch. Filed #38977 to add the last missing bits that had referenced this.

**Comment by franciscojma86** [comment]
Landed! Thanks for the heads up!

**Comment by smanilov** [comment]
Thanks a lot for following up! I'll use this right away :)
