### ISSUE TITLE
Run Flutter Doctor command nothing happened

### ISSUE THREAD

**Issue by djkloop** [flutter/flutter#18869]
## Steps to Reproduce

After dragging it down from Git, the first run downloads some dependencies, and then one card is in this position.
And then run it again Run Flutter Doctor command nothing happened （macOS 10.13.5 ）
But Dart consumes 100 of the RAM.

![image](https://user-images.githubusercontent.com/21050914/41968770-f0ac4b80-7a37-11e8-8a41-64ec3974a31e.png)
![image](https://user-images.githubusercontent.com/21050914/41968789-fcf12fb4-7a37-11e8-9575-ed282f38a96f.png)

**Comment by zoechi** [comment]
Did you follow these instructions https://github.com/flutter/flutter/wiki/Using-Flutter-in-China ?

**Comment by djkloop** [comment]
@zoechi 
I downloaded the flutter and followed the connection settings you gave me, and I waited 10 minutes or so and I didn't respond.
![image](https://user-images.githubusercontent.com/21050914/41970199-84ee894e-7a3c-11e8-881c-b5c9006cddf7.png)
![image](https://user-images.githubusercontent.com/21050914/41970256-b6575678-7a3c-11e8-9ae6-98b6b065f341.png)

**Comment by djkloop** [comment]
@zoechi 

Open Activity Monitor open dart details found to have been circulating this vnode:fd unavailable

![image](https://user-images.githubusercontent.com/21050914/42122832-63f68c6a-7c7a-11e8-86c8-3e8284517b2b.png)

**Comment by djkloop** [comment]
I have found the reason, because I have previously installed an old version of the Mamp software, I uninstall the software after he can run it will not appear above the problem ... It looks like dart will go to the node_modules below that software to find a problem with typescript dependencies.

![image](https://user-images.githubusercontent.com/21050914/42123384-dc46b33a-7c83-11e8-8a23-21ceda13f052.png)

**Comment by HannesArni** [comment]
Moving the flutter directory to some place not requiring admin privileges
