### ISSUE TITLE
flutter.io/setup/ should say to make a permanent change to your path

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1886]
We suggest several times running commands that update the PATH environment variable, but we never actually tell the developer to make those changes permanent. We just give the command that will make it work that one time. We should either give a command that actually has a permanent effect, or, more likely, just say that doing so is recommended so that you don't have to keep resetting the PATH.

**Comment by Hixie** [comment]
This has regressed. The /setup/ page no longer makes a permanent change to your path anymore.

**Comment by sethladd** [comment]
@LarkAscending @lukechurch did we do this? do we plan on doing this?

**Comment by LarkAscending** [comment]
This issue was actually a feature request for Flutter, so I didn't close it.
But yes, https://github.com/flutter/website/pull/413 applies a documentation patch.

**Comment by sethladd** [comment]
Great, thanks!

If the tool needs to do something more, let's open an issue for that.

**Comment by LarkAscending** [comment]
Could be wrong but I believe the fix is an installer...and we don't have an issue for that.
