### ISSUE TITLE
"Updating flutter tool" is confusing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1887]
We shouldn't say "Updating flutter tool" when doing the pub get for the tool. It makes it sound like it's upgrading the flutter repo or something.

How about "Setting up flutter tool...".

Also, if it takes more than a couple of seconds we should add "Please stand by, this can take a while."

**Comment by abarth** [comment]
In https://github.com/flutter/flutter/pull/1895 I'm chaing this to say "Building flutter tool..."
