### ISSUE TITLE
flutter_gallery_instrumentation_test is flaky

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#18879]
There are a few yellow flakes on the dashboard and on my last commit it went red. In all the flaky cases the issue seems the same:

```
stdout: Starting 1 tests on Moto G (4) - 7.0
Force quitting process:
command : ./tool/run_instrumentation_test.sh 
  started : 2018-06-22 15:04:59.272512
  pid     : 11236
exitcode: -15
Task execution finished

Task failed with the following reason:
Timeout waiting for task process to exit: Future not completed
```

@Hixie @yjbanov not sure what to do here - should we mark the test as flaky? Seems to be very infrequent, but not sure how to make the build go green otherwise (so people may be waiting to merge things).

**Comment by Hixie** [comment]
What we should do is fix the problem. :-)

**Comment by Hixie** [comment]
(but yes in the meantime feel free to mark the test as flaky or just delete it)

**Comment by yjbanov** [comment]
This test used to be very stable. It is also a very valuable test. It is the only test we have that makes sure that we are able to run tests on off-the-shelf infrastructures, such as Firebase Test Lab, Saucelabs, AWS Device Farm, etc.

**Comment by Hixie** [comment]
We should definitely figure out when it became flaky then.

**Comment by DanTup** [comment]
It's yellow twice on the build dashboard, and red for the first (visible) time on the last checkin. So seems to fail fairly rarely (and those I could see were all with this same message - timeout waiting for exit).

PR to mark flaky in the meantime: https://github.com/flutter/flutter/pull/18887

**Comment by Hixie** [comment]
One of the recent failures was actually 
```
stdout: Starting 1 tests on Moto G (4) - 7.0
stdout: 
stdout: io.flutter.demo.gallery.FlutterGalleryInstrumentationTest > activityLoaded[Moto G (4) - 7.0] [31mFAILED [0m
stdout: Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
stdout: Tests on Moto G (4) - 7.0 failed: Instrumentation run failed due to 'Process crashed.'
stdout: :app:connectedDebugAndroidTest FAILED
stderr: 
stderr: FAILURE: Build failed with an exception.
stderr: 
stderr: * What went wrong:
stderr: Execution failed for task ':app:connectedDebugAndroidTest'.
stderr: > There were failing tests. See the report at: file:///home/linux2/.cocoon/flutter/examples/flutter_gallery/build/app/reports/androidTests/connected/index.html
stderr: 
stderr: * Try:
stderr: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
stderr: 
stderr: * Get more help at https://help.gradle.org
stderr: 
stderr: BUILD FAILED in 1m 16s
stdout: 135 actionable tasks: 125 executed, 10 up-to-date
exitcode: 1
Task failed: Executable failed with exit code 1.

Stack trace:
package:flutter_devicelab/framework/utils.dart 77:3        fail
package:flutter_devicelab/framework/utils.dart 283:5       exec
===== asynchronous gap ===========================
dart:async                                                 _AsyncAwaitCompleter.completeError
package:flutter_devicelab/framework/utils.dart             exec
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/framework/utils.dart 261:10      exec
bin/tasks/flutter_gallery_instrumentation_test.dart 24:13  main..
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
bin/tasks/flutter_gallery_instrumentation_test.dart 18:50  main..
package:flutter_devicelab/framework/utils.dart 369:24      inDirectory

Task execution finished

Task failed with the following reason:
Task failed: Executable failed with exit code 1.
Deleting build/ directories, if any.
```

**Comment by DanTup** [comment]
Most recent flake (today) was:

```
stderr: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
stderr: > java.lang.OutOfMemoryError
```

Before that (ignoring two builds that broke loads of tests) was about a week ago:

```
2018-08-17T20:18:50.086563: stderr: Execution failed for task ':app:packageDebug'.
2018-08-17T20:18:50.091555: stderr: > Java heap space
```

And the Yellow run before that was the same. I'm guessing these issues are not related to this test (they're in the Gradle/Java build, before the test code runs) so maybe if we can figure out what's causing the memory issues this test can be un-marked flaky.

**Comment by Hixie** [comment]
Hopefully fixed by https://github.com/flutter/flutter/pull/20968

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by DanTup** [comment]
I haven't seen it myself, and the dashboard looks clean (the most recent commit is yellow for this test, but appears to have been an issue with connecting to the dashboard rather than the test). I think it's reasonable to close and re-visit if we see it again - doesn't seem like there's anything we can actively investigate here without a recent failure.
