### ISSUE TITLE
Make API docs and API doc search easier to access

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#18880]
I received the following feedback from a study participant. I think this is related to the removal of the API Docs link from the top navigation we implemented for the beta website. We should revisit this decision.

> At the moment, the doc search is top right here: https://docs.flutter.io/
> But from the main site.. you have to follow this path:
> * Goto https://flutter.io/
> * Click Docs
> * Click Visit on API Docs (This moves around when the page size changes width.. very annoying!)
> * Click Search
> * Enter Search Query Text.
> * Click Result

> I believe since Flutter is developer centric the API docs search box should be accessible from the home-page. Perhaps also with a list of suggestions underneath to draw new developers into reading some of the more important docs. I personally have learn't a lot more from reading the doc's then the tutorials on the site.
> 
> My wish.. something like:
> * Goto https://flutter.io/
> * Enter Search Query Text. (perhaps have it auto focus to the API search field)
> * Click Result.
> Perhaps that's a bit much but at least having a search box and reading recommendations on the home-page will engage revisiting developers.

My takeaways from this feedback: 1) The entry point to the API docs is too buried now and accessing it requires many clicks. The global site search is needs to be more useful for searching API docs. Perhaps we can add filters for different kinds of content. 

Cc: @filiph @Sfshaza

**Comment by nujabse** [comment]
I agree with that. The official site needs some change.

**Comment by Sfshaza** [comment]
@InMatrix, I'm not defending the design of the home page, but I want to point out that there IS a search text field on the front page. Entering, for example, MaterialWidget, kicks off our custom search engine. It looks through both the API docs and the flutter.io docs. (I'd like to categorize the output better.) So, entering the widget brings up a list with the API page, with one click.

**Comment by InMatrix** [comment]
@Sfshaza You're right, that's an option. However, the search box on the landing page works differently from the search box in the API docs. For example, it doesn't autocomplete class names. From the site analytics, only a very small fraction of users do use the search box on the landing page.

**Comment by Sfshaza** [comment]
+1

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2006](https://github.com/flutter/website/issues/2006) via [**ZenHub**](https://www.zenhub.com/)
