### ISSUE TITLE
Add TextFormField validation states (dirty, touched, etc)

### ISSUE THREAD

**Issue by Chris1234567899** [flutter/flutter#18885]
Another feature request:
At the moment TextFormField allows to use autovalidate activated or deactivated which is nice.
The "problem" is that if autovalidate is active, it validates the initial state of the input right away, marking a field as  invalid when a user opens first time a login page for example -  which does not look very nice.

A possible solution would be using additional states. Something like:

- field is empty and untouched 
- field is empty but user wrote something before (and deleted it again)
- field has content,
- user is currently typing

**Comment by YAPPDEF** [comment]
+1
would be nice to have autovalidate but not from beginning on when the user didn't touch the field yet.

**Comment by larssn** [comment]
This is pretty crucial for any Framework.

**Comment by liri2006** [comment]
+1
Would be great to have this out of the box!

**Comment by GenuineRex** [comment]
+1
The closer Flutter comes to feature parity with Angular, the easier it is to move between the frameworks.

**Comment by GenuineRex** [comment]
Workaround - add a bool touched=false to the form.  Set to true when submitting the form and validation fails.  Set audovalidate: touched on each form field.  The initial editing will be clean, when the user is fixing validation issues the form fields will autovalidate.

**Comment by EcoGames** [comment]
+1 Angular has this feature, as well as many other Frameworks. Therefore, Flutter should have this, especially a way to check if a field is "dirty" and only mark that field as invalid.

**Comment by filiph** [comment]
Hi, I'm removing the `a: annoyance` tag. Not that I think this omission in functionality isn't annoying. I just try to reserve the `a: annoyance` tag only for issues with existing stable features (see [definition](https://github.com/flutter/flutter/wiki/Triage#labels)).

**Comment by justinmc** [comment]
There is some great discussion about this problem in https://github.com/flutter/flutter/pull/48155 for anyone that's interested.  My best current solution is to use composition like in https://github.com/flutter/flutter/pull/48155#issuecomment-580930754, but I'm keeping this issue open in hope of a deeper solution, or at least some docs/communication improvements.

**Comment by nateshmbhat** [comment]
@filiph @justinmc Please review this PR #56132 
it seems like a neat fix for the first render issue.

**Comment by yalva** [comment]
> Workaround - add a bool touched=false to the form. Set to true when submitting the form and validation fails. Set audovalidate: touched on each form field. The initial editing will be clean, when the user is fixing validation issues the form fields will autovalidate.

Is it posible to set autoValidate to true in onChaged() of every field?
