### ISSUE TITLE
Android Studio on OSX can not use Assists

### ISSUE THREAD

**Issue by wisit-phusi** [flutter/flutter#18895]
I have tried to wrap widget list with new widget assist by using Alt+Enter, But nothing happens.

**Comment by zoechi** [comment]
Do you have the Dart and Flutter plugins installed in AS?
Please add the output of `flutter doctor -v`

**Comment by wisit-phusi** [comment]
I use IntelliJ IDEA 2018.1.4, Android Studio 3.1.3, Flutter Plugin version 25.0.1 and Dart Plugin version 173.4700.

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
[✓] VS Code (version 1.24.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
@devoncarew

**Comment by wisit-phusi** [comment]
This is an example when it does not work.
<img width="875" alt="screen shot 2561-06-30 at 01 06 32" src="https://user-images.githubusercontent.com/32625530/42107894-24b34862-7c03-11e8-8be5-fc6a4f726248.png">

**Comment by devoncarew** [comment]
Is this the same as https://github.com/flutter/flutter-intellij/issues/2448?
