### ISSUE TITLE
"flutter start" on mac doesn't work if you just follow the getting started guide

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1889]
The getting started guide doesn't mention ideviceinstaller, xcode, homebrew, simctl, xcode-select, or connecting devices, but running flutter start on mac when it says to do so results in complaints about all these things.

**Comment by Hixie** [comment]
Ah, it does mention these, but much later. We should reorder the content or at least link to the iOS instructions from earlier.

**Comment by Hixie** [comment]
I don't know what I was reading yesterday but now that I look again, I don't see this. So never mind.

**Comment by Hixie** [comment]
The problem is that "flutter create" ends with an invitation to run "flutter run", but by that point in the getting started guide, you still haven't installed either the android or iOS dependencies.

**Comment by danrubel** [comment]
The getting started guide has a "Before you begin" section with a link to Flutter Setup and `flutter doctor` helps you figure out what you still need to do. I think this issue has been addressed.
