### ISSUE TITLE
flutter run throws 'no application found for targetplatform.ios' error

### ISSUE THREAD

**Issue by vijaykanta** [flutter/flutter#18894]
I had completed a project in Ubuntu/Flutter/AS and migrated it to a fully installed Mac computer running high Sierra. I got almost everything done, but the project cannot run in either Xcode (which is different issue), it can't even run in the terminal. I had followed all steps in flutter official docs, but when I type 'flutter run' inside my project it threw following error and exited

`Launching lib/main.dart on iphonexxx in debug mode`
`No application found for TargetPlatform.ios.`
`Is your project missing an ios/Runner/Info.plist?`
`Consider running "flutter create ." to create one`

This is ridiculous as the file already exists, and this process repeats for any new dummy project that I create. What's going wrong?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`

**Comment by vijaykanta** [comment]
Actually I fixed it. I forgot the Pod package from brew, then six python extension. Also, the apple store asked me to update command line tools which I did. Now interestingly I am deploying to iPhone directly off Android Studio flutter project by choosing it in devices. This is way more faster than I imagined.
