### ISSUE TITLE
Capitalisations inconsistent with Effective Dart Style Guide

### ISSUE THREAD

**Issue by jayjun** [flutter/flutter#18912]
The [style guide](https://www.dartlang.org/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words) on the official Dart page states

> acronyms and abbreviations are capitalized like regular words, except for two-letter acronyms.

| Do                         | Don’t                       |
|------------------|--------------------|
|`HttpConnection`|`HTTPConnection`|
|`IOStream`           |`IoStream`              |

I crawled through Flutter’s API as best I could and found these offending names.

| This                                 | Should Be                       |
|------------------------|-------------------------|
|`HSVColor`                     |`HsvColor`                     |
|`JSONMessageCodec`  |`JsonMessageCodec`  |
|`JSONMethodCodec`    |`JsonMethodCodec`     |
|`SystemUiOverlayStyle`|`SystemUIOverlayStyle`|

Personally I prefer full uppercase abbreviations, so I’m only bothered by `SystemUi`. In fact, that triggered my style guide search because Flutter obviously took that casing verbatim from Android (that is, Java conventions).

We should really decide if Flutter must follow Dart’s style guide before 1.0 is out.

**Comment by jayjun** [comment]
[`dart:convert`](https://api.dartlang.org/dev/2.0.0-dev.65.0/dart-convert/dart-convert-library.html) has a ton of abbreviations, with names like `JsonUtf8Encoder`.

**Comment by jolleekin** [comment]
A few more:
- `TextInputType.toJSON`
- `TextInputConfiguration.toJSON`
- `TextEditingValue.toJSON`

Since Flutter uses Dart, it should follow Dart's style guides. Also, ALLCAPS are hard to read and really hurt the eyes (imagine two or more ALLCAPS abbreviations in a single identifier such as XMLHTTPRequest)

**Comment by jolleekin** [comment]
This should be fixed ASAP. The longer we wait, the more breaking it is.

**Comment by goderbauer** [comment]
Flutter has its own style guide which is slightly different than effective dart.

**Comment by om-ha** [comment]
@goderbauer Care to link us to Flutter style guide?

**Comment by goderbauer** [comment]
It's in the wiki: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo

**Comment by om-ha** [comment]
@goderbauer much obliged

**Comment by om-ha** [comment]
@goderbauer although this is a closed issue, my question is related to it.

I think there's an inconsistency [Abbreviations convention](https://dart.dev/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words) in Effective Dart's Style guide.

Specifically, the `uiHandler` bit. I agree with everything in there except for this.

Shouldn't it be `UIHandler` for types and `uiHandler` for identifiers?

In this particular paragraph, types and identifiers are not distinguished when it comes  to abbreviations naming, and it's a little bit misleading.

**Comment by jolleekin** [comment]
The style guide doesn't say clearly how to capitalize abbreviations. The only example I found is `UiKit`, which implies abbreviations are capitalized as words (Json, Xml, ...).
>Avoid starting class names with iOS since that would have to capitalize as Ios which is not how that is spelled. (Use "Cupertino" or "UiKit" instead.)
