### ISSUE TITLE
Embedder switched to using presence of kernel shapshot to decide run mode

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#18926]
It used to be that an embedder could control whether to run in source mode vs. kernel mode by whether or not main_dart_file_path was null, which made it easy to control. At some point (I believe during the Dart 2 transition), the logic changed, and now the decision is based on whether or not a kernel snapshot is present (see shell/platform/embedder/embedder.cc around line 155).

That's problematic because flutter_assets is required either way, which means `flutter build bundle` needs to be run even for source mode... but that creates the kernel snapshot too. So running in source mode actually requires deleting a file on disk, which is a) hard to discover, and b) not something that a higher-level wrapping API (like the one provided by flutter-desktop-embedding) can control.

Ideally it would either go back to using the presence of a main path, or provide an explicit switch that controls the mode (the latter would probably be less fragile, since it would be self-explanatory in the implementation and thus less likely for someone to break without noticing).

**Comment by stuartmorgan** [comment]
@chinmaygarde

**Comment by mraleph** [comment]
Source mode will go away when we delete Dart 1 support. There will only be kernel mode left. What is the reason for you to run from source?

**Comment by zoechi** [comment]
Dart1 support seems to be removed in 2.1.0-dev.2.0
(not sure if this is all)
See comment in https://github.com/dart-lang/sdk/issues/34109#issuecomment-415551625

**Comment by mraleph** [comment]
@zoechi the referenced issue is just about dart2js.

Dart VM will start removing Dart 1 support when Fuchsia pieces are removed.

@stuartmorgan Kernel mode and source mode are not different - you can have multiple entry points in Kernel mode too. So I am going to go ahead and close this issue - feel free to reopen if you feel like we need to do something.

**Comment by stuartmorgan** [comment]
@mraleph I don't appear to have permission to re-open this, but I'm not seeing how the embedder API allows for multiple entry points in kernel mode. See:
https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.cc#L157

To be very clear, this bug is about what's possible using the Flutter embedder API, not what the Dart VM supports.

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by stuartmorgan** [comment]
Closing since apparently the fact that this is no longer possible is WAI.
