### ISSUE TITLE
Can't keep google_sign_in persistent between two different pages inside app

### ISSUE THREAD

**Issue by fvorwerk** [flutter/flutter#18920]
Please look at my repo, where I describe this Problem in detail.

https://github.com/fvorwerk/Broken-Google-Sign-In-Flutter

Thank you very much!

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by kroikie** [comment]
@fvorwerk

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/777. Any further collaboration will be done there.
