### ISSUE TITLE
Navigator error (Drawer button logout)

### ISSUE THREAD

**Issue by ChAraya** [flutter/flutter#18925]
I have a Drawer that i share in all my StatefulWidget like this

`@override`
`Widget build(BuildContext context) {`
    `return new Scaffold(`
      `key: _scaffoldKey,`
      `drawer: SharedDrawer()`
`... //More code` 

In the Drawer i put a LogOut button that redirect the user to the login page cleaning all the router stack like this.

`Navigator.of(context).pop();`
  ` Navigator.of(context).pushNamedAndRemoveUntil('/', (Route<dynamic> route) => false);`

but when i try to log in again to the app this error appears.

`flutter: Looking up a deactivated widget's ancestor is unsafe.`
`At this point the state of the widget's element tree is no longer stable. To safely refer to a widget's`
`ancestor in its dispose() method, save a reference to the ancestor by calling`
`inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.`

what i'm doing wrong ?

how i can manage the login/out in the app or is something with the navigator stack ?

Regards!

**Comment by zoechi** [comment]
Where do you get `context` from? This context is short-lived and can't be stored and reused.

**Comment by lyquocnam** [comment]
ya, `context` from here: ` Widget build(BuildContext context) {}`, i think it still in local, i just split to many parts for clear code

**Comment by zoechi** [comment]
Can you please add the code that allows to reproduce.
Please create a new project and post the code that needs to be added to reproduce.

**Comment by ChAraya** [comment]
Sorry guys i was very busy now i'm back, ok i tried to recreate the problem but couldn't in the test proyect work just fine, So i figured out that the problem wasn't the navigator, was the login interface so i fix it and now all works, sorry =/

**Comment by vibhuvardhansingh** [comment]
I'am dealing with the same problem.
I have Navigation Drawer in multiple screens but sign out works only in the first screen and not for the rest  
Can you please share the code of Login interface and Navigation drawer.
