### ISSUE TITLE
Cloud Firestore transaction exception on iOS

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#18923]
Just got this exception while running the app on iOS Simulator.
Will update here if able to reproduce reliably.

```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010dca51e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010d33a031 objc_exception_throw + 48
	2   Runner                              0x00000001093a6710 -[FSTTransaction ensureCommitNotCalled] + 112
	3   Runner                              0x00000001093a47a8 -[FSTTransaction writeMutations:] + 56
	4   Runner                              0x00000001093a56a0 -[FSTTransaction deleteDocument:] + 320
	5   Runner                              0x00000001092b28c0 -[FIRTransaction deleteDocument:] + 160
	6   Runner                              0x00000001094d9770 __51-[FLTCloudFirestorePlugin handleMethodCall:result:]_block_invoke.475 + 256
	7   libdispatch.dylib                   0x0000000110af06cb _dispatch_call_block_and_release + 12
	8   libdis<…>
Lost connection to device.
```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.74, on Mac OS X 10.13.5 17F77, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[!] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by pulyaevskiy** [comment]
Oh, I think I figured it out. I didn't `await` delete operations inside my transaction handler which was causing my transaction to commit before delete calls completed, producing the above error.

First time used Firestore transactions though.

I guess the issue is resolved for me but I'm wondering if there is some sort of guard condition we can add to protect against such errors.

Or, catch `FSTThrowInvalidUsage` and fail the transaction on the Flutter side with a meaningful error message to saying "please await all async calls inside your transaction handler".

The Firestore exception gets thrown here:

https://github.com/firebase/firebase-ios-sdk/blob/b8eb4e04497a5d51343e94465fd01b39a520c29c/Firestore/Source/Core/FSTTransaction.mm#L249-L254

Currently this causes an app to crash, which is probably not very friendly.

**Comment by cyanglaz** [comment]
cc @collinjackson It seems to me that this issue could happen for all firebase transaction methods, not just `delete`

**Comment by kroikie** [comment]
@pulyaevskiy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/776. Any further collaboration will be done there.
