### ISSUE TITLE
mac: "flutter start" is confusing even after installing command line tools

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1892]
So I ran "flutter start", it complained about some command line tools, I told the dialog to install them, it sid it did, and then I ran "flutter start" again:

```
idevice_id not found. To work with iOS devices, please install ideviceinstaller.
If you use homebrew, you can install it with "$ brew install ideviceinstaller".
Error executing simctl: 72
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH

Unable to run application - no connected devices.
```

- [ ] We probably should only say "idevice_id not found" if `--verbose` is set. In normal mode, we should just calmly say that you need to install ideviceinstaller.
- [ ] Maybe we should offer to do that for you, or ship with it, or fold its functionality into our tool, or something.

The following issues are also covered by https://github.com/flutter/flutter/issues/1891: 
- [ ] "Error executing simctl: 72; xcrun: error: unable to find utility "simctl", not a developer tool or in PATH" is meaningless to a flutter devloper. We should catch whatever is causing this error and turn it into something actionable.
- [ ] We shouldn't complain about no connected devices if we've already established nothing is going to work.

**Comment by Hixie** [comment]
I plugged in a device and it still says "no connected devices", so the earlier errors should definitely be fatal.

**Comment by abarth** [comment]
Is this still an issue after flutter doctor?

**Comment by Hixie** [comment]
I don't think flutter doctor affects either of those issues, but I'd have to test it again to be sure.

**Comment by danrubel** [comment]
with no device connected:
```
$ flutter run
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
```

**Comment by danrubel** [comment]
`flutter run` produces the same message with a device connected because at this point we cannot tell without additional tools installed. Running `flutter doctor` as suggested by the output above indicates next steps. I believe this issue has been properly addressed.
