### ISSUE TITLE
Android Module Template: couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by jonasbark** [flutter/flutter#18939]
Trying to use the new android module template I followed https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps closely and integrated the module with an existing application (no jetifier or anything).

Compilation worked but execution failed with couldn't find "libflutter.so". 
Using Android Studio 3.2 Beta 2 on a OnePlus 3T with Android 8.0.

```
[✓] Flutter (Channel master, v0.5.6-pre.100, on Mac OS X 10.13.5 17F77, locale de-DE)
    • Flutter version 0.5.6-pre.100 at /Users/boni/Documents/Programmieren/Dart/flutter
    • Framework revision 7e4038fe27 (17 hours ago), 2018-06-28 14:10:26 +0100
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at /Users/boni/Library/Android/sdk
    • Android NDK at /Users/boni/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • ONEPLUS A3003 • 75aef492                                 • android-arm64 • Android 8.0.0 (API 26)
    • Iphone 6 Grau • 75c53fe05e0703ae0d22634f157f01193712d211 • ios           • iOS 11.0.2
```

**Comment by mravn-google** [comment]
Integrating the Flutter module appears to work fine using Android Studio 3.1.3 and a newly created Android App based on the "Basic Activity" template. @jonasbark Would you be able to share your Gradle scripts? Meanwhile, I'll try the Android Studio 3.2 preview.

**Comment by jonasbark** [comment]
I can confirm this to be working with a fresh Application using Android Studio 3.1.3. Interestingly the same project also works within Android Studio 3.2 beta 2 without upgrading the Gradle version.
After setting gradle-wrapper.properties to use gradle 4.6 and using 'com.android.tools.build:gradle:3.2.0-beta02' I'll get the following error:

Transform output file /Users/boni/Documents/Programmieren/Android/hornbach_flutter_base/.android/Flutter/build/intermediates/flutter/flutter-x86.jar does not exist.

With a fresh Application using the wizard from Android Studio 3.2 beta 2 it's the same.

So my conclusion: 
The module template currently is not compatible with gradle 4.6 and / or Android Gradle Plugin 3.2.0-beta02 as this seems to expect different places for the build files.

**Comment by mravn-google** [comment]
@jonasbark Thanks, I reached the same conclusion and am working on a PR to avoid non-standard location of the `build/` folder.

**Comment by jonasbark** [comment]
Regarding the integration with an existing app which fails with libflutter.so missing error some more information:

Android Studio 3.1.3 is used.

```
06-29 10:02:05.542 28701-28701/de.ffuf.hornbach.profi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.ffuf.[redacted], PID: 28701
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.ffuf.[redacted]-JzGaQtdYbj_PDQnC2bT9RQ==/base.apk"],nativeLibraryDirectories=[/data/app/de.ffuf.[redacted]-JzGaQtdYbj_PDQnC2bT9RQ==/lib/arm64, /data/app/de.ffuf.[redacted]-JzGaQtdYbj_PDQnC2bT9RQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:170)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:147)
        at io.flutter.facade.Flutter.createView(Flutter.java:43)
        at io.flutter.facade.FlutterFragment.onCreateView(FlutterFragment.java:38)
```

According to the APK analyzer the *.so files are integrated within the APK:
![image](https://user-images.githubusercontent.com/1151304/42080668-bb216a70-7b83-11e8-813f-1a207f3a7c9b.png)

Some parts of the used gradle files (some libraries are outdated - this is quite an old project):

Project gradle:
```
buildscript {
    ext.kotlin_version = '1.2.21'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:3.1.2'
        classpath 'me.tatarka:gradle-retrolambda:3.7.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

App gradle:
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 27

    defaultConfig {
        applicationId "[redacted]"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode Integer.parseInt('git rev-list HEAD --first-parent --count'.execute([], project.rootDir).text.trim())
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
}

repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

ext {
    supportLibVersion = '27.1.1'
    playServicesVersion = '11.8.0'
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:multidex:1.0.3'

    compile "com.android.support:appcompat-v7:${supportLibVersion}"
    compile "com.android.support:design:${supportLibVersion}"
    compile "com.android.support:cardview-v7:${supportLibVersion}"
    compile "com.android.support:exifinterface:${supportLibVersion}"
    compile "com.google.firebase:firebase-crash:${playServicesVersion}"
    compile "com.android.support:support-v4:${supportLibVersion}"
    compile "com.google.android.gms:play-services-maps:${playServicesVersion}"
    compile "com.google.android.gms:play-services-analytics:${playServicesVersion}"


    compile('com.weiwangcn.betterspinner:library-material:1.1.0') {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
    compile 'com.koushikdutta.ion:ion:2.2.1'
    compile 'com.afollestad.material-dialogs:core:0.9.5.0'
    compile 'com.bignerdranch.android:expandablerecyclerview:3.0.0-RC1'
    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'
    compile 'com.jakewharton:butterknife:8.5.1'
    compile 'net.danlew:android.joda:2.9.9'
    compile 'com.github.jkwiecien:EasyImage:2.0.2'
    testCompile 'junit:junit:4.12'
    kapt 'com.jakewharton:butterknife-compiler:8.5.1'
    compile 'com.github.gcacace:signature-pad:1.2.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'pub.devrel:easypermissions:0.2.1'

    compile 'com.alexvasilkov:gesture-views:2.2.0'

    compile 'com.itextpdf:itextg:5.5.10'
    compile group: 'com.itextpdf.tool', name: 'xmlworker', version: '5.5.13'

    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    compile project(path: ':flutter')
}

apply plugin: 'com.google.gms.google-services'
```

Using gradle-4.4
Proguard rule:
```
-dontwarn java.lang.invoke.*
```

I'll make sure to test it again with the upcoming Pull Request you just mentioned.

**Comment by kevinvandenbreemen** [comment]
Hey there,
I'm on a team investigating Flutter for our existing Android app and we're experiencing the same sort of issue.
The app works on an emulator but when deployed to a physical device we are getting:

`    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/app.package-AF8sRcuegr0QFRPQpQ1EZQ==/base.apk"],nativeLibraryDirectories=[/data/app/app.package-AF8sRcuegr0QFRPQpQ1EZQ==/lib/arm64, /data/app/app.package-AF8sRcuegr0QFRPQpQ1EZQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:170)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:147)
        at io.flutter.facade.Flutter.createView(Flutter.java:71)
        at io.flutter.facade.FlutterFragment.onCreateView(FlutterFragment.java:39)
        at io.flutter.facade.FlutterFragment.onCreateView(FlutterFragment.java:20)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

Developing on Android Studio v. 3.1.3 , gradle version 4.4.1

I've run Flutter Doctor and also pulled down the latest version of the Flutter project master branch but to no avail.

**Comment by mravn-google** [comment]
@kevinvandenbreemen @jonasbark I have tried to reproduce the `UnsatisfiedLinkError` using the Gradle files listed above and my trusted LGE Nexus 5X. I had no success until I specified ABI filters like so:
```gradle
android {
  defaultConfig {
    ndk {
      abiFilters "armeabi", "x86"
    }
  }
}
```
Adding `, "armeabi-v7a"` to the filters list then removed the `UnsatisfiedLinkError` again.
Wondering if you have ABI filters specified somewhere, e.g. in your `gradle.properties`?

**Comment by mravn-google** [comment]
Looking more closely at your apk analysis output above, the cause of the error might instead be that the app tries to load `libflutter.so` from `lib/arm64-v8a/` from where it is missing. I'll see if I can found out how to fix that, seem to recall that there is a target platform property somewhere. Hang on.

**Comment by mravn-google** [comment]
Cf https://github.com/flutter/flutter/issues/16917

**Comment by jonasbark** [comment]
I did not specify abiFilters myself in any of the gradle files. I can indeed confirm it works when adding (in my case):

```
defaultConfig {
        ndk {
            abiFilters "armeabi", "x86", "armeabi-v7a"
        }
    }
```

**Comment by mravn-google** [comment]
OK, so the `target-platform` Gradle property can be set to `android-arm` or `android-arm64`. Using the latter, you'll get a `libflutter.so` in `lib/arm64-v8a/`
```
# In gradle.properties
target-platform=android-arm64
```

**Comment by kevinvandenbreemen** [comment]
Good evening,
@mravn-google 
One thing that concerns me about this solution however is backward compatibility.  Correct me if I am wrong, but won't changing setting target-platform attribute in an Android project necessarily exclude certain devices from being able to run the app?

Are there plans in the future to make Flutter just work out of the box in an existing Android project without any need to specify the target architecture in order for the app to be able to find the flutter binary?

For example I understand other teams have addressed problems like this by writing their own "re-linker" packages (for example, https://github.com/KeepSafe/ReLinker ).

**Comment by xxseabxx** [comment]
Have the same problem - but flutter.so not included in "armeabi-v7a folder.
Has only third party libraries for x86 and armeabi-v7a - but no arm64.
Would like to build flutter only for "armeabi-v7a with 
 ndk{
            abiFilters "armeabi-v7a" // also not work"armeabi", "x86",
        }
and set as target-platform as @mravn-google suggest in to android-arm64.

APK without specify arch and include libraries
<img width="746" alt="screen shot 2018-07-26 at 21 06 53" src="https://user-images.githubusercontent.com/604580/43283002-fe1b245c-9117-11e8-88f8-918b4f82319f.png">

APK with specify arch and include libraries
<img width="748" alt="screen shot 2018-07-26 at 21 10 30" src="https://user-images.githubusercontent.com/604580/43283147-5e2004a8-9118-11e8-8f6e-294737f26c41.png">

Any suggestion how to debug further steps?

**Comment by hua407035000** [comment]
阿斯顿发送到

**Comment by hua407035000** [comment]
> dontwarn
41/5000  
My error is the same as yours. May I ask how to solve it? I am a Chinese programmer. It is difficult for me to read English. I am looking forward to your reply

**Comment by lekanbar** [comment]
Just in case, someone out there may find this useful, if like me they stumble on this thread while almost losing their minds for 2 days!

Background: I upgraded to [AndroidX](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility) and was trying to integrate Braze's flutter plugin which is dependent on firebase.

What finally worked: I removed the following dependencies from the app/build.gradle 

> implementation "com.google.firebase:firebase-core:17.0.1"

> implementation "com.google.firebase:firebase-messaging:19.0.1"

And added the following dependencies to pubspec.yaml

> firebase_core: ^0.4.0+8
  
> firebase_messaging: ^5.1.2

I suspect there is something in there that makes it fail, not sure, but this worked for me in resolving this issue. If you encounter a similar issue, it maybe be helpful to check your dependencies on Android's build.gradle and flutter's pubspec.yaml.

**Comment by rlecheta** [comment]
I'm integrating flutter in some existing app and I have the same error
/base.apk!/lib/x86_64, /system/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
And this doesn't solve the problem:
ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
        }
I can build a release apk, but I can't run it on emulador using Android Studio.

**Comment by whiteLT** [comment]
> 
> 
> I'm integrating flutter in some existing app and I have the same error
> /base.apk!/lib/x86_64, /system/lib64]]] couldn't find "libflutter.so"
> at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
> at java.lang.System.loadLibrary(System.java:1669)
> And this doesn't solve the problem:
> ndk {
> abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
> }
> I can build a release apk, but I can't run it on emulador using Android Studio.

Just create emulator with x86_64 architecture

**Comment by richard457** [comment]
Still, this does not solve the issue, of installing on x86 devices, what is the solution please?
