### ISSUE TITLE
DropDown crashes if used in very short screen

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#18933]
If a DropDown widget is used when the screen is very small (e.g. in an add-to-app scenario), the drop-down widget will crash because the second argument to `selectedItemOffset.clamp(0.0, size.height - _kMenuItemHeight)` in `_DropdownMenuPainter.paint` is negative (I'm guessing).

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
I believe this was fixed by https://github.com/flutter/flutter/pull/22594

**Comment by zoechi** [comment]
Assuming this is fixed.
