### ISSUE TITLE
DropDown doesn't say that it needs localizations

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#18932]
if you use a Material DropDown without a MaterialApp, you get an exception because you don't have localizations, but it doesn't warn you in the build method. We should do the usual assert in the build method to require the presence of all our InheritedWidget dependencies.

In general we should audit all our widgets to make sure we are asserting for the right dependencies.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
Fixed by https://github.com/flutter/flutter/pull/20787
