### ISSUE TITLE
Because every version of flutter_driver from sdk depends on vector_math 2.0.6 and flutter_gallery depends on vector_math 2.0.5, flutter_driver from sdk is forbidden.So, because flutter_gallery depends on flutter_driver any from sdk, version solving failed.

### ISSUE THREAD

**Issue by linguowu** [flutter/flutter#18937]
when i update my flutter，and then run gallery example,the console of android studio show below log:
> Because every version of flutter_driver from sdk depends on vector_math 2.0.6 and flutter_gallery depends on vector_math 2.0.5, flutter_driver from sdk is forbidden.So, because flutter_gallery depends on flutter_driver any from sdk, version solving failed.

**Comment by chapskev** [comment]
@zoechi  what is the reason for the above...am new to flutter and my experience with dependency package manager has me banging my head. 

Mind you, I am just trying to run the examples on flutter GitHub. Will revert back if the resolutions you have provided works. Also on the above message, I feel it creates more problems than a solution. My thinking is that when the error pops up we can give some solutions to troubleshoot the problem, Similarily to what brew does.

**Comment by zoechi** [comment]
As far as I know `flutter_gallery` is supposed to work with Flutter `beta`.
Other Flutter versions require newer dependency versions. If you want to use a newer Flutter version, you probably need to update dependencies in `flutter_gallery` yourself.
The alternative is as suggested to use the Flutter version `flutter_gallery` is tested with.

**Comment by justbane** [comment]
I didn't even update flutter - just cloned the repo and tried to run platform_view. Got the same error... so the examples are just broken then? Whats the fix here?

**Comment by Hixie** [comment]
reopening, sorry about the overzealous bot

**Comment by Hixie** [comment]
If you are seeing this please paste the output of `flutter doctor -v` here, along with the result of running `flutter run -v` in the directory where `flutter run` isn't working for you. Also maybe include the output of `git status` and `git diff`. Thanks.

**Comment by rupertlustosa** [comment]
@zoechi I have the same problem and after I have executed your commands, the problem continues:

> Because every version of flutter_driver from sdk depends on file 5.0.4 and stocks depends on file 5.0.6, flutter_driver from sdk is forbidden.
> So, because stocks depends on flutter_driver any from sdk, version solving failed.
> 

> [rupertlustosa@rumobile stocks]$ flutter doctor -v
> [✓] Flutter (Channel beta, v0.6.0, on Linux, locale pt_BR.UTF-8)
>     • Flutter version 0.6.0 at /home/rupertlustosa/development/flutter
>     • Framework revision 9299c02cf7 (2 weeks ago), 2018-08-16 00:35:12 +0200
>     • Engine revision e3687f70c7
>     • Dart version 2.1.0-dev.0.0.flutter-be6309690f
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at /home/rupertlustosa/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-27, build-tools 27.0.3
>     • ANDROID_HOME = /home/rupertlustosa/Android/Sdk
>     • Java binary at: /usr/local/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /usr/local/android-studio
>     • Flutter plugin version 27.1.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [✓] Connected devices (1 available)
>     • S5, API 19, 1080x1920 • 192.168.56.101:5555 • android-x86 • Android 4.4.4 (API 19)
> 
> • No issues found!
> 


This happens with: catalog, flutter_gallery, stocks, platform_channel
It Works with: flutter_view, hello_world, layers, platform_view
I didn't test with platform_channel_swift

**Comment by chef9** [comment]
I have the same problem

**Comment by rupertlustosa** [comment]
After I returned to the master, my Flutter updated again and is now working. Thank you!

**Comment by chef9** [comment]
Same here. I got stock working on the master channel

**Comment by brkr** [comment]
i have the same problem too.

`$ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.12.5 16F73, locale en-US)
    • Flutter version 0.7.3 at /Users/berker/development/flutter/flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/berker/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    ✗ Flutter requires a minimum Xcode version of 9.0.0.
      Download the latest version or update via the Mac App Store.
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4694.29

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
`

**Comment by antoninobajeli** [comment]
My flutter doctor is:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Versione 10.0.17134.285], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!


I'M STILL FACING THE ISSUE : 

Running "flutter packages get" in flutter_gallery...
**Because every version of flutter_driver from sdk depends on file 5.0.4 and flutter_gallery depends on file 5.0.6, flutter_driver from sdk is forbidden.**
So, because flutter_gallery depends on flutter_driver any from sdk, version solving failed.
pub get failed (1)
Process finished with exit code 1

**Comment by antoninobajeli** [comment]
Switching flutter to DEV channel solved the ISSUE !!!

**Comment by tudodetalhado** [comment]
Today I got this error message:
`Because flutter_gallery depends on flutter_driver any from sdk which depends on source_maps 0.10.7, source_maps 0.10.7 is required.
So, because flutter_gallery depends on source_maps 0.10.8, version solving failed.

pub upgrade failed (1)`

**Comment by matsyendra** [comment]
run:
flutter channel dev

**Comment by basefox** [comment]
> Switching flutter to DEV channel solved the ISSUE !!!

@antoninobajeli thanks bro..

command : 
flutter channel dev
flutter packages get

Checking Dart SDK version...
The term 'Unblock-File' is not recognized as the name of a cmdlet, fun
file, or operable program. Check the spelling of the name, or if a pat
, verify that the path is correct and try again.
At line:1 char:13
+ Unblock-File <<<<  -Path 'C:\flutter\flutter/bin/internal/update_dar
'C:\flutter\flutter/bin/internal/update_dart_sdk.ps1'
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) []
   oundException
    + FullyQualifiedErrorId : CommandNotFoundException

Downloading Dart SDK from Flutter engine e5ec3cf3ea5ce78c6c3116271601f
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Downloading package sky_engine...                                3,8s
Downloading common tools...                                     15,7s
Downloading windows-x64 tools...                                35,5s
Downloading android-arm-profile/windows-x64 tools...             3,3s
Downloading android-arm-release/windows-x64 tools...             4,5s
Downloading android-arm64-profile/windows-x64 tools...           7,3s
Downloading android-arm64-release/windows-x64 tools...           4,1s
Downloading android-arm-dynamic-profile/windows-x64 tools...      3,6s
Downloading android-arm-dynamic-release/windows-x64 tools...      3,5s
Downloading android-arm64-dynamic-profile/windows-x64 tools...      4,
Downloading android-arm64-dynamic-release/windows-x64 tools...      4,
Downloading android-x86 tools...                                24,9s
Downloading android-x64 tools...                                20,5s
Downloading android-arm tools...                                12,5s
Downloading android-arm-profile tools...                        12,0s
Downloading android-arm-release tools...                        14,5s
Downloading android-arm64 tools...                              12,6s
Downloading android-arm64-profile tools...                      11,8s
Downloading android-arm64-release tools...                       8,0s
Downloading android-arm-dynamic-profile tools...                16,5s
Downloading android-arm-dynamic-release tools...                15,2s
Downloading android-arm64-dynamic-profile tools...              31,1s
Downloading android-arm64-dynamic-release tools...              16,4s
Running "flutter packages get" in catalog...                    30,8s

command : 

λ flutter run
Launching lib/main.dart on Redmi Note 3 in debug mode...
Initializing gradle...                                          18,4s
Resolving dependencies...                                       22,9s
Gradle task 'assembleDebug'...                                  132,5s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                     12,4s
Syncing files to device Redmi Note 3...                          3,3s

now its work ..

**Comment by pratikbutani** [comment]
Have you checked [this article](https://pratikbutani.medium.com/flutter-2-upgrade-flutter-version-solving-failed-error-33ac1087cb6b)
