### ISSUE TITLE
What is the bar for something being added to Flutter's Runtime?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#18931]
My experience is it's a relatively high-bar to add something to Flutter's runtime.

There is a disk-size impact.
There is an argument about things being in the core being less extensible/replaceable than things not.

@Hixie and I definitely have biases here.  I'm just not sure if we've written them down anywhere.  @cbracken might know?

**Comment by eseidelGoogle** [comment]
One thing to write down for example, would be the binary size constraints imposed by Instant Apps, or @goderbauer's current work to reduce our APK/IPA sizes in https://github.com/flutter/flutter/issues/16833.

**Comment by Hixie** [comment]
@eseidelGoogle Not sure what this is asking for, but maybe https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#philosophy answers this now? I'm going to close this bug since it's not really actionable.
