### ISSUE TITLE
Cant Move the Map Google Map Flutter

### ISSUE THREAD

**Issue by theogumilang** [flutter/flutter#18947]
Hi i want to add Map to my flutter app so i use this plugin https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter, when i use the example code in the documentation is working fine. But when i tried to create my own map to add it in my drawer item i don't know why the map is not working , i can't drag or swipe my map, the map is freezing . i don't know if its my code that wrong, or its bug from the plugin it self here is my code below to show my maps.

```dart
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:flutter/material.dart';


class MapPage extends StatelessWidget {
  
  static GoogleMapOverlayController controller =
      GoogleMapOverlayController.fromSize(width: 300.0, height: 200.0);
  static Widget mapWidget = GoogleMapOverlay(controller: controller);

  final Widget mapsWidget = mapWidget;
  final GoogleMapController controllers = controller.mapController;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(15.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          Center(child: mapsWidget),
          RaisedButton(
            child: const Text('Go to London'),
            onPressed: () {
              controllers.animateCamera(CameraUpdate.newCameraPosition(
                const CameraPosition(
                  bearing: 270.0,
                  target: LatLng(51.5160895, -0.1294527),
                  tilt: 30.0,
                  zoom: 17.0,
                ),
              ));
            },
          ),
        ],
      ),
    );
  }
}
```

**Comment by phuongdt8x** [comment]
You will need to add your controllers to Material navigatorObservers.
If it still not work please post full code.

**the example:**
GoogleMapController kcontrollers = kcontroller;
List<NavigatorObserver> kobservers;

@override
  void initState() {
    super.initState();

    kcontroller = GoogleMapOverlayController.fromSize(width: 300.0, height: 200.0);
    kobservers = <NavigatorObserver>[];
    kobservers .add(kcontroller.overlayController);
  }

@override
  Widget build(BuildContext context) {
    return new MaterialApp(
               home: MapPage(),
               navigatorObservers: kobservers
   );
  }

**Comment by zoechi** [comment]
@theogumilang Did above suggestion solve the issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
