### ISSUE TITLE
Getting started guide only explains how to do things with brew but doesn't install brew

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1894]
We should either say that "brew" is a recommend prerequisite and then show you how to install it, or we should give instructions for how to install things without it. For Dart we almost do the latter (see #1884), but later we just assume you have brew available.

**Comment by Hixie** [comment]
At this point the only thing we use homebrew for is ideviceinstaller. I think we'd be better off just internalising that dependency somehow. Filed that as https://github.com/flutter/flutter/issues/1907 which would make this bug moot.

**Comment by devoncarew** [comment]
We could also consider have a brew recipe to install flutter. That would be an easy install process for mac users. We could also use the idea from here: https://github.com/flutter/flutter/issues/1805, and have brew install other needed deps for us in one go.

**Comment by Hixie** [comment]
that sounds good to be. not sure if brew supports the "check out a github repo in a subdirectory of the user's home directory" model though.

**Comment by abarth** [comment]
Will be addressed by https://docs.google.com/document/d/1wL_7BvpExxyvLqtf5am3_iMQThWBZ0Ak1uPVFiI3KN8/edit?usp=sharing

**Comment by qchong** [comment]
Made this fix for the iOS setup instructions in the [Flutter Setup](https://flutter.io/setup/) page, based on doc shared by abarth@.

**Comment by qchong** [comment]
Marking as closed.
