### ISSUE TITLE
Is there a plan to add the ability to theme a dialog in stead of just the background color?

### ISSUE THREAD

**Issue by Edward608** [flutter/flutter#18946]
Currently there is only a option in `Theme` for `dialogBackgroundColor`, but the text inside the dialog seems to not be able inherite the theme defined at `MaterialApp` level.

**Comment by zoechi** [comment]
There were related changes recently
#25339 #24169 #23858 #23569

I'm going to close. If there are things missing, please create a new more specific issue.
Thanks for reporting!
