### ISSUE TITLE
Flutter Android Module Template: not compatible with gradle-4.6

### ISSUE THREAD

**Issue by jonasbark** [flutter/flutter#18940]
I'm getting the following error when building:

> Cannot open a library at 'FileMapping(from=/Users/[redacted]/Documents/Programmieren/Android/[redacted]/[redacted]_module_flutter_base/.android/Flutter/build/intermediates/flutter/flutter-x86.jar, to=/Users/[redacted]/.gradle/caches/transforms-1/files-1.1/flutter-x86.jar/77ccf32321279b8c89c3dea709a9e700/jetified-flutter-x86.jar)'

If I make the following changes to the .android/build.gradle file...
```
rootProject.buildDir = 'Flutter'
subprojects {
    project.buildDir = "${rootProject.buildDir}/build"
}
```
it will build again but execution fails with "couldn't find "libflutter.so"" crash, see https://github.com/flutter/flutter/issues/18939. 
This only happens with:

```
android.useAndroidX=true
android.enableJetifier=true
```

```
[✓] Flutter (Channel master, v0.5.6-pre.100, on Mac OS X 10.13.5 17F77, locale de-DE)
    • Flutter version 0.5.6-pre.100 at /Users/boni/Documents/Programmieren/Dart/flutter
    • Framework revision 7e4038fe27 (17 hours ago), 2018-06-28 14:10:26 +0100
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at /Users/boni/Library/Android/sdk
    • Android NDK at /Users/boni/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • ONEPLUS A3003 • 75aef492                                 • android-arm64 • Android 8.0.0 (API 26)
    • Iphone 6 Grau • 75c53fe05e0703ae0d22634f157f01193712d211 • ios           • iOS 11.0.2
```

**Comment by jonasbark** [comment]
Additional information see https://github.com/flutter/flutter/issues/18939#issuecomment-401274943 - it might not have something to do with jetifier after all but the gradle and Android Gradle plugin version.

**Comment by jonasbark** [comment]
@mravn-google with the changes applied from the pull request to a newly created module something seems to still not work correctly with jetifier enabled:

```
org.gradle.api.artifacts.transform.ArtifactTransformException: Failed to transform file 'flutter-x86.jar' to match attributes {artifactType=jetified-jar} using transform JetifyTransform |  
-- | --
java.lang.RuntimeException: Failed to transform '/Users/[redacted]_flutter_base/.android/Flutter/build/intermediates/flutter/flutter-x86.jar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=/Users/[redacted]_flutter_base/.android/Flutter/build/intermediates/flutter/flutter-x86.jar, to=/Users/[redacted]/.gradle/caches/transforms-1/files-1.1/flutter-x86.jar/7f2fa40daf0856838343eff9eadf19a2/jetified-flutter-x86.jar)'. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file. |  
java.io.FileNotFoundException: Cannot open a library at 'FileMapping(from=/Users/[redacted]_flutter_base/.android/Flutter/build/intermediates/flutter/flutter-x86.jar, to=/Users/[redacted]/.gradle/caches/transforms-1/files-1.1/flutter-x86.jar/7f2fa40daf0856838343eff9eadf19a2/jetified-flutter-x86.jar)' |  
```
And indeed flutter-x86.jar is not created in the Flutter/build/intermediates/flutter directory. That one only contains a "debug"-Dir.

I can confirm that it's working now on a project without jetifier but I'm getting the libflutter.so missing error as described in my other ticket (https://github.com/flutter/flutter/issues/18939#issuecomment-401282130)

**Comment by jonasbark** [comment]
Another update: 
- android gradle version 3.2.0-beta02
- gradle-4.6
- jetifier not enabled

Also getting a flutter-x86.jar error: 

> Caused by: org.gradle.api.InvalidUserDataException: Transform output file /Users/.../.android/Flutter/build/intermediates/flutter/flutter-x86.jar does not exist.

I changed the issues title accordingly.

**Comment by mravn-google** [comment]
Confirmed. The new Android Studio Gradle plugin appears to have added an undocumented task called `compileDebugSources` whose execution requires the existence of `flutter-x86.jar` (via some new `:app:debugCompileClasspath` configuration). Yet even though the host `:app` project has an `implementation` dependency on the `:flutter` project, the plugin does not execute `flutter:compileDebugSources` before `app:compileDebugSources`.

The result is that this call fails
```
$ ./gradlew clean app:compileDebugSources
```
while this one works:
```
$ ./gradlew clean flutter:compileDebugSources app:compileDebugSources
```
Similarly for `assembleDebug`. Still investigating.

**Comment by Mars1986** [comment]
Flutter Android Module Template: not compatible with gradle-3.3.

**Comment by sbaranov** [comment]
Should be fixed by https://github.com/flutter/flutter/pull/21466

**Comment by matthew-carroll** [comment]
I'm going to close this as per #21466 - please re-open if the issue continues.
