### ISSUE TITLE
Issue while wrapping a Row inside a ListView builder

### ISSUE THREAD

**Issue by gbakthavatchalam** [flutter/flutter#18958]
## Steps to Reproduce

```dart
Widget build(BuildContext context) {
    // TODO: implement build
    return new Scaffold(
      body: new Container(
          //width: 500.0,
          //height: 800.0,
          child: new Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              new Expanded(
                flex: 1,
                //fit: FlexFit.loose,
                child: new ListView.builder(
                    itemBuilder: (BuildContext context, int index) {
                      return new Row(
                        mainAxisSize: MainAxisSize.min,
                        //mainAxisAlignment: MainAxisAlignment.start,
                        //crossAxisAlignment: CrossAxisAlignment.center,
                        children: <Widget>[
                          new Image.network(items[index]['img']),
                          new ListTile(
                            title: new Text(items[index]['name']),
                            onTap: null,
                            trailing: new Text(items[index]['locality']),
                          )
                        ],
                      );
                    })
              )
            ],
          )
      )
    );
  }
```

```
## Logs
I/flutter ( 6513): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 6513): The following assertion was thrown during performLayout():
I/flutter ( 6513): RenderFlex children have non-zero flex but incoming width constraints are unbounded.
I/flutter ( 6513): When a row is in a parent that does not provide a finite width constraint, for example if it is in a
I/flutter ( 6513): horizontal scrollable, it will try to shrink-wrap its children along the horizontal axis. Setting a
I/flutter ( 6513): flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining
I/flutter ( 6513): space in the horizontal direction.
I/flutter ( 6513): These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
I/flutter ( 6513): cannot simultaneously expand to fit its parent.
I/flutter ( 6513): Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible
I/flutter ( 6513): children (using Flexible rather than Expanded). This will allow the flexible children to size
I/flutter ( 6513): themselves to less than the infinite remaining space they would otherwise be forced to take, and
I/flutter ( 6513): then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum
I/flutter ( 6513): constraints provided by the parent.
I/flutter ( 6513): The affected RenderFlex is:
I/flutter ( 6513):   RenderFlex#ec4e8 relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 6513): The creator information is set to:
I/flutter ( 6513):   Row ← MediaQuery ← Padding ← SafeArea ← UnconstrainedBox ← Padding ← ConstrainedBox ← Semantics ←
I/flutter ( 6513):   Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ← ⋯
I/flutter ( 6513): The nearest ancestor providing an unbounded width constraint is:
I/flutter ( 6513):   RenderFlex#8d30b relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 6513):   creator: Row ← RepaintBoundary-[<0>] ← NotificationListener<KeepAliveNotification> ← KeepAlive ←
I/flutter ( 6513):   AutomaticKeepAlive ← SliverList ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter ( 6513):   IgnorePointer-[GlobalKey#33368] ← Semantics ← ⋯
I/flutter ( 6513):   parentData: <none> (can use size)
I/flutter ( 6513):   constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
I/flutter ( 6513):   size: MISSING
I/flutter ( 6513):   direction: horizontal
I/flutter ( 6513):   mainAxisAlignment: start
I/flutter ( 6513):   mainAxisSize: min
I/flutter ( 6513):   crossAxisAlignment: center
I/flutter ( 6513):   textDirection: ltr
I/flutter ( 6513):   verticalDirection: down

```

```
```

```
```

**Comment by gbakthavatchalam** [comment]
Can someone please advice. I'm struck with this now. Kindly help

**Comment by ebeem** [comment]
according to what I understood, you just want to show a listview in your scaffold
if that's the case, then you are making it complicated by wrapping the list view inside multiple widgets like (`Container`, `Column`, `Expanded`)

so my suggestion, is to make it immediately a child of the scaffold
some important parameters you pass to the `ListView.builder` like `itemCount` which is the count of the widgets inside a view.

Also, you seem to be missing the differences between a `Row` and a `ListTile`
a `Row` is just a normal row layout, while a `ListTile` is a kind of `Row` but with a ready template that you can use to simply create a quality content. I think in your case you want to just use a `ListTile`, you use a `Row` if you want more customization.

so here is an example of how the code should look like

```
return new Scaffold(
      appBar: new AppBar(),
      body: new ListView.builder(
        itemCount: 20,
        itemBuilder: (BuildContext context, int index) {
          return new ListTile(
            title: new Text("Test"),
            onTap: () {},
            trailing: new Text("Test"),
          );
        },
      ),
    );
```

I used a lot of assumtions here, let me know if you are looking for something else

**Comment by gbakthavatchalam** [comment]
@ebeem  Thank you . It worked.

Below is the code

@override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new Scaffold(
      //appBar: new PreferredSize(child: new HeaderComponent(), preferredSize: const Size.fromHeight(100.0)),
      body: new Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          new Container(
            decoration: const BoxDecoration(
              border: const Border(
                bottom: const BorderSide(width: 1.0, color: Colors.grey),
              ),
            ),
            child: new HeaderComponent(),
          ),
          new Expanded(
            child: new ListView.builder(
                itemCount: items.length,
                itemBuilder: (BuildContext context, int index) {
                  return new ListTile(
                    leading: new Image.network(items[index]['img']),
                    title: new Text(items[index]['name']),
                    onTap: null,
                    trailing: new Text(items[index]['locality']),
                  );
                })
          )
        ],
      )
    );
  }

Have one more doubt.

How can we increase the the size of the list tile ?

**Comment by ebeem** [comment]
you don't increase the font of the `ListTile`
you increase the font of the `Text`

```
new Text(
   "Test",
   style: TextStyle(fontSize: 22.0),
)
```

**Comment by gbakthavatchalam** [comment]
Thanks a lot. Eventually figured it out myself. Now another one

new ListView.builder(
                itemCount: items.length,
                itemBuilder: (BuildContext context, int index) {
                  return new Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      new Padding(padding: EdgeInsets.only(left: 10.0)),
                      new InkWell(
                          child: new Image.network(items[index]['img'], height: 100.0, width: 100.0, fit: BoxFit.fitWidth,),
                          onTap: null
                      ),
                      new Padding(padding: EdgeInsets.only(left: 10.0)),
                      new InkWell(
                        child: new Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: <Widget>[
                            new Text(items[index]['name'], style: listItemTextStyle),
                            //new Padding(padding: EdgeInsets.only(left: 3.0)),
                            new Text(items[index]['locality'])
                          ],
                        ),
                        onTap: null,
                      ),
                      new Icon(Icons.favorite)
                      //new Padding(padding: ,)
                    ],
                  );
                })

How do I push my favorite icon to be aligned to the end of the row ?

**Comment by ebeem** [comment]
you can find all the documentation here https://flutter.io/docs/
if you want to achieve something, maybe you shall provide an image of how you want your ui to look like ... it will be much easier

**Comment by zoechi** [comment]
Please consider asking this kind of questions on StackOverflow.

**Comment by patelkrunal78** [comment]
https://icetutor.com/question/how-to-put-two-listview-in-a-column

Similar issue at there

**Comment by Pranshul2002** [comment]
![Screenshot_20210818-190233](https://user-images.githubusercontent.com/57452974/129907694-76c9b91b-d7dc-45bb-8674-f8dcb7c6d4b3.jpg)

This is the layout I am trying to achieve. It has a row inside a listview builder. I am setting alignment based on who sent the message. Thanks for your help.
