### ISSUE TITLE
Unknown operating system. Cannot install Dart SDK.

### ISSUE THREAD

**Issue by SongJun973208** [flutter/flutter#18953]
##  flutter doctor
Downloading Dart SDK from Flutter engine 1ed25ca7b7e3e3e8047df050bba4174074c9b336...
Unknown operating system. Cannot install Dart SDK.

```
```

```
```

```
```

**Comment by zoechi** [comment]
Can you please provide some information about your operating system?
Did you check https://github.com/flutter/flutter/wiki/Using-Flutter-in-China (in case it applies to you)?

**Comment by mengwuhen** [comment]
I have the same problem 
detail information 
![image](https://user-images.githubusercontent.com/22239802/43113637-c170121a-8f2d-11e8-9074-14fdbee46d0e.png)

**Comment by mengwuhen** [comment]
I have the same problem

system : windows 7  64 bit
RAM: 8 G

**Comment by zoechi** [comment]
Looks like a dup of #8860

@mengwuhen do any of the suggestions there work for you?
What shell are you using?

**Comment by sparshsaini** [comment]
Hay mengwuhen how you do it cause I am also stuck here please tell me from where you set up environment veriable

**Comment by Bob-Thomas** [comment]
I just used windows cmd to run flutter doctor and no problems.
But when I use git-bash I do get the unknown operating system error

**Comment by Rambou** [comment]
It should have been a good feature to pass operating system as parameter in case flutter can't find it.

**Comment by shikechen** [comment]
If you encounter this problem in the Git Bash window and are opening Android Studio, you should close Android Studio and the Flutter command will work.

**Comment by samayo** [comment]
Thanks Bob. 

If you are already on git-bash, you can switch to CMD mode using by just typing `cmd`

**Comment by SurajBahadur** [comment]
You will see this issue when you are running flutter doctor on git-bash, that happened in my case. So i have switch to normal window CMD terminal and then it works

**Comment by LPIX-11** [comment]
For those on windows, if you use git bash you'll have a problem like:
Downloading Dart SDK from Flutter engine fee001c93f25a1e7258e762781a7361f122d29f5...
Unknown operating system. Cannot install Dart SDK.

Use directly windows terminal

**Comment by Pils36** [comment]
Thanks for that @LPIX-11. I used windows terminal

**Comment by Leon-Africa** [comment]
Use windows cmd and add git to your path

**Comment by Pils36** [comment]
Thanks... Done that

**Comment by MarFelix** [comment]
Funciona con cmd windows 10 home single lenguage

**Comment by itMcdull** [comment]
I integrated git-bash in vscode and this problem also appeared

**Comment by MdGolam-Kibria** [comment]
> @zoechi thanks for your replay I have solve the problem. It because in my Environment Variables can not find git path. so I add the path to Environment Variables . I using Powershell .

how to add your git path please help me
