### ISSUE TITLE
Image cache too small? Cache evicting too aggressive?

### ISSUE THREAD

**Issue by Tomucha** [flutter/flutter#18952]
Based on discussion at https://github.com/flutter/flutter/pull/18135, cc @jonahwilliams 

I have two big (2000x1200) images (A and B) on in the tree of widgets. Both in the different paths of the tree, different BuildContexts, nested in different parents. At some point I throw away image A, replace it with B (which becomes new A) and load a third one, which becomes the new B.

At this point the B image shortly blinks (also the listener at ImageProvider.resolve(...).addListener(...) is called asynchronously).

This behavior appeared after the last upgrade to:
Flutter 0.5.6-pre.105 • channel master • https://github.com/flutter/flutter.git
Framework • revision 35e8cd83d0 (21 hours ago) • 2018-06-28 11:27:22 -0700
Engine • revision 6fe748490d
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2

Increasing the cache helped:
PaintingBinding.instance.imageCache.maximumSizeBytes = 100 * 1000 * 1000;

Question is:
- is 10MB default cache size enough?
- is cache evicting too aggressive?

**Comment by jonahwilliams** [comment]
To clarify, The image blinks while it is at least partially on screen?

**Comment by Tomucha** [comment]
Yes. Now, with the increased cache size I see a smooth transition from position B to position A without any blinking and it's clearly visible throughout the transition.

And to make it more complicated, I'm using CachedNetworkImageProvider from cached_network_image package. But it seems reasonable, the provider extends ImageProvider and only implements ImageStreamCompleter load(CachedNetworkImageProvider key) method.
