### ISSUE TITLE
Flutter Firestore library relies on outdated DocumentID generator, screwing up Firestore streams?

### ISSUE THREAD

**Issue by CosmicPangolin** [flutter/flutter#18956]
Simple but impactful issue - the Flutter Firestore library has a push_id_generator.dart that generates a very different docID than other Firestore platforms (for instance, with timestamp embedding and "-" as a first char).

This seems to lead to issues when constructing streams from Firestore collections where documents are written from multiple platforms (say, Flutter and Cloud Functions) - given the '-' char, the flutter ID's are ordered before all others and lists built from a Firestore stream will look like this:

FlutterID
FlutterID
newFlutterID
CloudFunctID
CloudFunctID
newCloudFunctID

Am I missing something important about how to effectively use StreamBuilder?  I realize a work-around is to build a custom ID generator in Dart, but I figure this issue could affect everyone so I wanted to bring it up (and see if I'm missing something about Firestore streams).

Thanks for any insights!

**Comment by kroikie** [comment]
@CosmicPangolin

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/773. Any further collaboration will be done there.
