### ISSUE TITLE
[Feature request] Read color info from single pixel

### ISSUE THREAD

**Issue by rvlajcev** [flutter/flutter#18950]
Hello.

**Requested feature:**
Ability to read color information from pixel specified by X and Y coordinates
in Canvas or Window class.

Here's an implementation I'm currently using in another framework
with Skia as external library.

```dart
SkImageInfo imageInfo = new SkImageInfo
            {
                Width = 1,
                Height = 1,                
                ColorType = SkColorType.Rgba8888,
                AlphaType = SkAlphaType.Premul
            };

SkBitmap skBitmap = new SkBitmap(imageInfo);
IntPtr ptrBuffer = skBitmap.GetPixels();
SkSurface.ReadPixels(imageInfo, ptrBuffer, imageInfo.RowBytes, posX, posY);

SkColor pixelColor = skBitmap.GetPixel(0, 0);
// Since there is no GetPixel method in Skia's
// SkBitmap class, I presume getColor method is used.
```
Now, I understand that this is a niche feature and you have more
important matters to attend to, but please reconsider on implementig
something like this in one of Flutter's future releases.

Thank you.

**Comment by hoaquo** [comment]
I'm hungry for this feature. Why does flutter engine not implement SkBitmap/ Surface? Is there's a different way (e.g `ffi`) to make it work?

**Comment by jonahwilliams** [comment]
Pixels can be read out of dart:ui Image objects
