### ISSUE TITLE
Opencv for Flutter SDK

### ISSUE THREAD

**Issue by rubencg195** [flutter/flutter#18969]
Is there any wrapper of Opencv for Fluttter?

**Comment by duasfh** [comment]
As you already searched (most probably), that question has already been asked.
But, it seems, there're no (opensource at least) implementations yet.
Try to build your own.
And also, i'll try to do it today/tomorrow, bcse i ran into this right now too)
Keep it up.

**Comment by zoechi** [comment]
If it's not on pub.dartlang.org, it probably doesn't exist, at least not open source.
https://pub.dartlang.org/packages?q=opencv

**Comment by rubencg195** [comment]
If possible, the results can be awesome. AR/VR, Machine Learning, Filters, etc. On top of a beautiful UI.

**Comment by zoechi** [comment]
That would be a great opportunity for community contribution.

**Comment by 926** [comment]
How about :
https://pub.dartlang.org/packages/flutter_opencv

?
