### ISSUE TITLE
No documentation for the Stack widget

### ISSUE THREAD

**Issue by vinicentus** [flutter/flutter#18967]
There doesn't seem to bee any documentation on the page https://docs.flutter.io/flutter/widgets/Stack-class.html, in fact the whole page doesn't seem to be working as intended. The search box just says "Loading search...".

**Comment by bounty-torn** [comment]
It's working fine for me in Chrome and Ffox - try a different browser.

**Comment by vinicentus** [comment]
I tried both chrome and brave desktop and Google webview mobile (chrome) but nothing seems to work.

**Comment by zoechi** [comment]
Works for me as well in Safari and Chrome.
Other pages are working?

**Comment by zoechi** [comment]
Do you still see this?
It doesn't look like others encountered this as well.

**Comment by vinicentus** [comment]
Yes, I still see this. If I use a VPN (to for example USA or Sweden), it works as expected (tested on chrome mobile). FYI I am in Finland, but I can't see why that would be a problem. Someone should probably do some digging to find out what the problem is, it's just that I seem to be the only one experiencing this.

**Comment by zoechi** [comment]
I don't think "some digging" would help if one can't reproduce.
If someone can reproduce it's probably easy. As nobody else seems to have encountered that problem it's likely that your network causes that and I don't see how anybody could do anything about that.

**Comment by zoechi** [comment]
> only tried on a couple of mobile network operators

With or without the VPN? Did it work with all/some/none of them?

**Comment by vinicentus** [comment]
Without the VPN of course, and it works with none of them...

**Comment by zoechi** [comment]
Ok, then we know it's not related to the network operators and the VPN.
Can you reproduce on different devices?

**Comment by vinicentus** [comment]
Could you try a Finnish or Estonian VPN? I have tried some and it didn't work over those (used OpenVPN Servers android app to find servers). Some other countries I tested work, so it's probably something to do with network configuration.

**Comment by zoechi** [comment]
Only when you use VPN or without VPN as well. I still have troubles to see a pattern here.

**Comment by vinicentus** [comment]
> Only when you use VPN or without VPN as well. I still have troubles to see a pattern here.

When I don't use VPN, and apparently when I used a Finnish or an Estonian VPN server.

**Comment by zoechi** [comment]
Sorry, but I have no idea what could cause that.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1964](https://github.com/flutter/website/issues/1964) via [**ZenHub**](https://www.zenhub.com/)
