### ISSUE TITLE
Remote Config should listen to real time device language changes

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#18977]
*Remote Config* does this on iOS and Android *native*. In Flutter, however, the user needs to restart their application in order for the configuration change to propagate.

 [StackOverflow question related to this issue](https://stackoverflow.com/questions/50978624/device-language-changes-in-flutter)

**Comment by creativecreatorormaybenot** [comment]
You can use [`WidgetsBindingObserver.didChangeLocales`](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeLocales.html) to reload your Remote Config data.

**Comment by kroikie** [comment]
@creativecreatorormaybenot

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/772. Any further collaboration will be done there.
