### ISSUE TITLE
flutter doesn't recognize applications installed through flatpak (linux)

### ISSUE THREAD

**Issue by Simbaclaws** [flutter/flutter#18970]
## Steps to Reproduce

1. install android studio, intellij idea or visual studio code through flatpak
2. install flutter
3. run flutter doctor

## Logs

```
flutter doctor -v 
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /opt/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/simbaclaws/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_172-b11)
    • All Android licenses accepted.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

Apparently when you install applications through flatpak on linux, they are not recognized as actual applications by flutter doctor.

This is because those applications won't be in the PATH since they are isolated from the main operating system. Now in order to have these binaries available so you can still run them from the command line you could use the flatpak wrapper scripts located in: `/var/lib/flatpak/exports/bin`. Adding these wrapper scripts to your path like so: `export PATH=/var/lib/flatpak/exports/bin:$PATH` still won't work because they essentially are scripts that are invoked on the application id instead of a application/binary name.

I figured since that won't work, perhaps I can create an alias for those application id's like so: `alias android-studio="com.google.AndroidStudio"`. Alas an alias has not gotten it to work so far.

Is there perhaps any insight on how flutter doctor recognizes when applications are installed? So I can perhaps find a workaround for getting flutter to work with flatpak apps?

Strangely enough it says that Android Studio is not installed while vs code and intellij are not even mentioned by flutter doctor while they are also installed.

EDIT: I have not yet tried setting the ANDROID_HOME environment variable yet, I will try so soon.

**Comment by cuzox** [comment]
I ended up doing:
```
flutter config --android-studio-dir=/var/lib/flatpak/app/com.google.AndroidStudio/x86_64/stable/7a56d0aad75311cf18ab0d695464ce0c08747e66cef18cdc44731f5518f6a9fd/files/extra
```
which caused flutter doctor -v output to be:
```
[✓] Android Studio
    • Android Studio at /var/lib/flatpak/app/com.google.AndroidStudio/x86_64/stable/7a56d0aad75311cf18ab0d695464ce0c08747e66cef18cdc44731f5518f6a9fd/files/extra
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /var/lib/flatpak/app/com.google.AndroidStudio/x86_64/stable/7a56d0aad75311cf18ab0d695464ce0c08747e66cef18cdc44731f5518f6a9fd/files/extra
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
```
So now it is detecting the android studio installation, but not the flutter and dart pluggins:
![capture](https://user-images.githubusercontent.com/3461464/44188518-f8feb180-a0eb-11e8-8e09-2f0d51c7d369.png)

**Comment by robertpro** [comment]
I can confirm this error, any update on this ?

**Comment by giannissc** [comment]
I have the solution (mostly):
To get everything working appart from android studio you need to go to /home/user/.bashrc and add this:

``` bash
PATH="$PATH:$HOME/development/flutter/bin"
PATH="$PATH:$HOME/development/Android/SDK" # (optional)
export ANDROID_HOME="$HOME/development/Android/SDK"
export PATH
```
To get everything except the plugins to work just add to the terminal

``` bash
flutter config --android-studio-dir=/var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/
```
However due to how flatpak works everything installed at runtime (in this case the plugins) cannot be installed in that directory cause it would require root access. Hence flatpak creates on "/home/user/.AndroidStudio3.3" 

The plugins can be located in "/home/user/.AndroidStudio3.3/config/plugins" (note that plugins installed with android studio will be located in the previous directory). If there was a way to specify a different directory for android studio and a different directory for the plugins of android studio  using the "flutter" command then this could work.

e.g.

`flutter config android-studio-dir=...`
and 
`flutter config android-studio-plugins=...`

**Comment by robertpro** [comment]
Hey @giannissc can you try: `flatpak override --user --filesystem=/home/user/.AndroidStudio3.3` I would like to know if that fixes the Dart plugin runtime issue (I can not do it in this computer)

**Comment by giannissc** [comment]
Hey @robertpro  already had it set to host and have trying also now explicitly setting to `/home/user/.AndroidStudio3.3` but it didn't work

**Comment by robertpro** [comment]
@giannissc ok, also I found another way, I installed AndroidStudio with Snap instead of Flatpak, and is working without issues, but I prefer Flatpak...

**Comment by giannissc** [comment]
@robertpro I know that snap works directly (due to its option for classic confinement). However, classic confinement doesn't work out of the box for Fedora. And also I like flatpak more!!

**Comment by kynrai** [comment]
How does flutter detect the plugins? symbolic linking the dark and intellij plugins to the flatpak directory does not work either

**Comment by kandarpgautam** [comment]
facing the same issue guys, just installed flutter and it's not detecting android studio that i installed via flatpak.

**Comment by alexandru-calinoiu** [comment]
Same issue for me also, any development on this ?

**Comment by MuhammadAliKhan1** [comment]
Same issue for me also, any development on this ?

**Comment by firrae** [comment]
Still an issue it seems, hopefully there's a way around this that isn't "install it a different way" as flatpak is becoming more common.

**Comment by Stilborg** [comment]
I Have the same issue on pop os, bummer

**Comment by montythemack** [comment]
> I Have the same issue on pop os, bummer

Same here. Hope this gets fixed soon!

**Comment by NikolayKantur** [comment]
This problem still exists

**Comment by gabrc52** [comment]
On some distros (like Fedora 33 in my experience), using the Flatpak is your only option, as the non-Flatpak package doesn't work.

**Comment by lewyuburi** [comment]
For Flutter 1.22.5, channel stable and Android Studio 4.1.1 (Flatpak) in KDE Neon (Ubuntu):
- Run `flutter config --android-studio-dir=/var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio`
- Then run `flutter doctor`

**Comment by Scaremonger** [comment]
Nice to find this fix, but it took me a long time to find it!

**Comment by jjardon** [comment]
> Still an issue it seems, hopefully there's a way around this that isn't "install it a different way" as flatpak is becoming more common.

In case it helps, this is an example of what is needed for package a flutter app: https://github.com/flathub/im.fluffychat.Fluffychat/blob/master/im.fluffychat.Fluffychat.json

**Comment by Simbaclaws** [comment]
> For Flutter 1.22.5, channel stable and Android Studio 4.1.1 (Flatpak) in KDE Neon (Ubuntu):
> 
> * Run `flutter config --android-studio-dir=/var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio`
> * Then run `flutter doctor`

Seems like the android-studio-dir flag was added to flutter doctor that fixes the issue?

I'm on vacation and can't check whether this command works. If someone can check whether this command solves the issue I'll close the thread as solved.

**Comment by grigoriy-a** [comment]
@Simbaclaws 
Hi, it works sort of, but then something else comes up -
![image](https://user-images.githubusercontent.com/74003289/123522685-84378880-d6c7-11eb-9e2a-305fb723e1c9.png)

**Comment by grigoriy-a** [comment]
@Simbaclaws 
Yes, checked just now. It helps.

**Comment by Simbaclaws** [comment]
Issue has been solved by:

> For Flutter 1.22.5, channel stable and Android Studio 4.1.1 (Flatpak) in KDE Neon (Ubuntu):
> 
> * Run `flutter config --android-studio-dir=/var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio`
> * Then run `flutter doctor`
