### ISSUE TITLE
CloudFirestore Plugin - A couple of questions 

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter#18972]
According to the Firebase website documentation offline persistence is enabled by default on Android and iOS. I was looking for the config option that would disable it but there does not seem to be one. 

I have been running some tests on an old-ish Android device which involved loading data from a file and persisting it to the Firestore. The app was struggling quite a bit as the garbage collector was constantly running in the background. I restarted the app but that did not help as the plugin just carried on synchronizing the offline data into the store (which is what it should do).  The data was eventually persisted but the whole thing it took quite a long time. I was wondering if there is a way to clear the offline cache which would have helped in this case but it might be also handy if the offline data gets corrupted for some reason.

And finally could you explain a bit more in detail `WriteBatch.setData` behavior when the `merge` flag is set to `true`? I had a case when I was persisting some data (with `merge: true`) and one of the properties was a String that changed from a `non-null` value to `null`. When the data was persisted I noticed that the property remain unchanged in the database as if the `null` was ignored by the plugin (setting the property to empty string worked as expected btw).

**Comment by zoechi** [comment]
What kind of data do you persist in firestore?
I think it's better to use Firebase Cloud Storage for image and similar files, then synchronization shouldn't cause such issues.

It doesn't look like the `cloud_firestore` plugin supports disabling offline yet.

>  The app was struggling quite a bit as the garbage collector was constantly running in the background. 

Not sure what you mean by that. The Android system kicking apps out on memory pressure?

> property remain unchanged in the database as if the null was ignored

I'd expect `null` to be treated the same as a non-existent node. You probably need to explicitly delete the node.
Do you have any reference how it behaves natively?
