### ISSUE TITLE
Can not publish my package, it keeps saying my package is oversize

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#18976]
_From @serenader2014 on July 1, 2018 11:43_

I'm trying to update my package to the pub.dartlang.org, but it keeps saying that my package is oversize, here is the full output when I execute `flutter packages pub publish --dry-run`:

```
Publishing carousel_slider 0.0.5 to https://pub.dartlang.org:
|-- .gitignore
|-- .metadata
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- example
|   |-- .gitignore
|   |-- .metadata
|   |-- README.md
|   | (5 more...)
|   |-- pubspec.yaml
|   |-- screenshot.gif
|   '-- test
|       '-- widget_test.dart
|-- lib
|   '-- carousel_slider.dart
|-- pubspec.yaml
'-- test
    '-- widget_test.dart
Missing requirements:
* Your package is 253.2 MB. Hosted packages must be smaller than 100 MB.
Suggestions:
* line 10, column 1 of example/test/widget_test.dart: This package doesn't depend on example.
  import 'package:example/main.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 3, column 1 of example/lib/main.dart: This package doesn't depend on cached_network_image.
  import 'package:cached_network_image/cached_network_image.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://www.dartlang.org/tools/pub/cmd/pub-lish.
pub finished with exit code 65
```

The GitHub repo of my package is https://github.com/serenader2014/flutter_carousel_slider , the repo's size is about 14MB, so I don't know why it says 253.2MB.

I have published the packages several times about one month before, without problems. Maybe it is because I've upgraded the flutter?

Here is my flutter doctor result:

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-CN)
    • Flutter version 0.5.1 at /Users/f/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/f/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)

! Doctor found issues in 1 category.

```

_Copied from original issue: dart-lang/pub-dartlang-dart#1422_

**Comment by isoos** [comment]
@serenader2014: I can't really comment on the package size, moved the issue here because it may be flutter related.

However, for the first part of the warning, there is this line: 
```
This package doesn't depend on cached_network_image.
  import 'package:cached_network_image/cached_network_image.dart';
```

If your project uses that package, you shall include it in your `pubspec.yaml` as a dependency. You can get an in-depth view of the dependencies [here](https://www.dartlang.org/tools/pub/dependencies), but in short, you should do something like this:

````
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^0.4.1
````

**Comment by zoechi** [comment]
Looks like a dup of #10001 
Seems `flutter packages pub publish` doesn't exclude `example` as it should.
Not sure if the "oversize" message is related though.

**Comment by isoos** [comment]
> Seems flutter packages pub publish doesn't exclude example as it should.

Is there a rule that it should? E.g. pub.dartlang.org displays code examples submitted along the package.

**Comment by zoechi** [comment]
For pure Dart packages there is no point in publishing anything except `bin/`, `lib/` and `pubspec.yaml` as far as I am aware.  
For Flutter plugin packages there are probably additional directories like `ios/`, `android/`, but I doubt publishing `example/` provides any value.

**Comment by isoos** [comment]
Couple of counter-points:

- When you are on a package page, you can take a quick look of the main example file, e.g. [here](https://pub.dartlang.org/packages/ecb_fx#-example-tab-). When you are still deciding on which library to depend on, this can be very helpful in a more complex case. I'm not sure if it is widely publicised, but it developed in response to developers asking for it.

- We are considering to actually factor in the example project (included in the package, because these are immutable) as part of the package's code health / overall score. E.g. in certain cases we could be able to run that code, and catch runtime errors that static analysis did not reveal, adding further confidence to the score.

**Comment by zoechi** [comment]
> you can take a quick look of the main example file

I saw support for this mentioned recently. To me this looks a bit like a rats nest.
What structure do you support there? Single *.dart files, sub-projects?
In my opinion the homepage link would be enough to point to examples.

I see some merits in including it in score, but again seems like a rats nest to me.

I was only thinking about what is required when you add a dependency to `pubspec.yaml`.
You are doing great work on pub.dartlang.org, perhaps it's just my limited imagination, so don't let yourself discourage from my rambling ;-)

**Comment by serenader2014** [comment]
So how can I solve the 'oversize' problem? This is the main reason why I can not publish the package.

**Comment by zoechi** [comment]
@serenader2014 could you try moving the example directory out and try publishing again?

**Comment by serenader2014** [comment]
That's weird, I try to run `flutter packages pub publish --dry-run` on another MacBook, and this time the output doesn't report oversized. Here is the output:

```
Publishing carousel_slider 0.0.5 to https://pub.dartlang.org:
|-- .gitignore
|-- .metadata
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- example
|   |-- .gitignore
|   |-- .metadata
|   |-- README.md
|   | (5 more...)
|   |-- pubspec.yaml
|   |-- screenshot.gif
|   '-- test
|       '-- widget_test.dart
|-- lib
|   '-- carousel_slider.dart
|-- pubspec.yaml
'-- test
    '-- widget_test.dart
Suggestions:
* line 10, column 1 of example/test/widget_test.dart: This package doesn't depend on example.
  import 'package:example/main.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 3, column 1 of example/lib/main.dart: This package doesn't depend on cached_network_image.
  import 'package:cached_network_image/cached_network_image.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Package has 2 warnings.
pub finished with exit code 65
```

When I delete the example folder and try again, the warnings disappeared:

```
Publishing carousel_slider 0.0.5 to https://pub.dartlang.org:
|-- .gitignore
|-- .metadata
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- lib
|   '-- carousel_slider.dart
|-- pubspec.yaml
'-- test
    '-- widget_test.dart

Package has 0 warnings.
```

The flutter doctor result of these two machines are identical. But I haven't build the example on the latter machine, maybe this is the problem?

**Comment by zoechi** [comment]
You can also try to delete the `example/build/` directory on the first machine.

**Comment by serenader2014** [comment]
After deleting the example folder on my first machine I can finally publish my package.

**Comment by serenader2014** [comment]
Just wonder if there is any solution to fix the oversize problem? Deleting the example folder on each publishing isn't a long term solution.

**Comment by mit-mit** [comment]
if we are not already excluding the `<root>/build` and `<root>/example/build` folders we certainly should, cc @gspencergoog

**Comment by zoechi** [comment]
@mit-mit I think all in `example/` should be excluded except what pub.dartlang.org explicitly supports and I think that's only `example/example.dart` @isoos please correct me if I'm wrong.

Assume I have

- pubspec.yaml
- example
  - example1
    - lib
    - build
  - example2
    - lib
    - build

**Comment by mit-mit** [comment]
Flutter packages are supported, see e.g.:
https://pub.dartlang.org/packages/path_provider#-example-tab-

**Comment by gspencergoog** [comment]
So, it looks like `pub` [already excludes files that are in a `.gitignore` file for a repo](https://github.com/dart-lang/pub/blob/5962908a66e814dd78f6856a4e5f792c6db65fbc/lib/src/package.dart#L224), which seems like a pretty good mechanism for excluding files from the package, given that they are probably the same set of files. If you didn't have `build/` in your `.gitignore`, or weren't using git for your source code control system, then it will publish the `build` directory.

It does mean that in order for it to take effect, you have to put your package into a git repo, which is a little bit odd, but is workable (it's pretty easy to `git init` a repo, even if you're not using `git` for your source code control system).

I'm going to close this bug and call it "fixed", but we could also file a bug with `pub` to add an alternate exclusion mechanism if people think that using `git` to do this is a little too odd.

**Comment by mit-mit** [comment]
> It does mean that in order for it to take effect, you have to put your package into a git repo

Doesn't it just mean you need a `.gitignore` file, but you could use any SCC provider, or none if you prefer? 

And with that, given our templates all have `.gitignore` now I totally agree that we can close this as "fixed" now.

**Comment by gspencergoog** [comment]
No, it means you really need to have a git repo, and you need to add your files to it, and have a `.gitignore`.

Pub uses git to list the files to include, relying on git's .gitignore code to do the filtering.

**Comment by serenader2014** [comment]
Just want to let you know that I finally figure out the 'oversized' problem, it's because the `example/ios/.symlinks` folder is not in the .gitignore file. When I execute the publish command, it will try to upload the symlink folder to the pub server, and that's why I get the oversized error.

I try to remove the example folder, and recreate the example project, this time flutter doesn't create the `example/ios/.symlinks` folder, and publishing is working.

**Comment by gspencergoog** [comment]
Great, we'll look at adding the `ios/.symlinks` dir to the `.gitignore`.  Thanks for the update!

**Comment by tabarakMohammed** [comment]
run "flutter clean" command in whole package and example
