### ISSUE TITLE
UI stopped animating during heavy operations

### ISSUE THREAD

**Issue by StaymanHou** [flutter/flutter#18999]
I'm implementing a search function in my Flutter app. The search function loads a data file in the local storage and walk through the data according to the search query. It usually takes 1 - 5 seconds to execute the search. I want to display a LinearProgressIndicator to indicate that the search is in progress. However the progress bar is frozen during the search operation.

Here's the actual code.

```dart
// this method is called upon tapping the search button
Future _executeSearchQuery() async {
  if (_searchQuery.queryString == null || _searchQuery.queryString.trim().isEmpty) return;
  if (_searchQuery.books == null || _searchQuery.books.length <= 0) return;
  setState(() {
    // this state enables the progress bar
    _isSearching = true;
  });
  _thisScaffoldKey.currentState.showSnackBar(new SnackBar(
    content: new Text('Searching...'),
    backgroundColor: Theme.of(context).primaryColor,
  ));

  _results = await SearchEngine.search(_data, _searchQuery); // the heavy operation that takes 1-5 sec
  setState(() {
    // disable the progress bar
    _isSearching = false;
  });
}
```

**Comment by Kartik1607** [comment]
Can you post the code for build() function as well?

**Comment by zoechi** [comment]
If `SearchEngine.search` runs in the UI thread (isolate) and does not yield frequently there is no time for other ui tasks like animation. So this is expected behavior.

You can for example use https://docs.flutter.io/flutter/foundation/compute.html to execute code in a different isolate, but there are some limitations. Currently plugins can only be used from the UI isolate.

**Comment by zoechi** [comment]
@Kartik1607 async is concurrency on the same thread. If some code waits for async execution to complete, like a network request, it registers a callback which will be added to the event queue and execution yields. If the even (network request completed) is emitted and no other sync code is executed the callback is taken from the queue and executed (.`then(...)` or `await` in Dart). 

So there can only be one sync line of code be executed at a time.

An isolate is a new thread with its own event queue that can run in parallel with code in the main isolate (if there are enough cores to actually run code in parallel on your system, but that's usually the case nowadays)

In Dart communication between isolates happens about message passing, so there can be no race conditions caused by 2 or more threads accessing a variable at the same time, but this also means that one isolate can work with stale data if you do not design synchronization carefully.

**Comment by jonahwilliams** [comment]
@StaymanHou, are you using any of the sync variants of the file APIs in that method?  If you could post the source of it that would help to identify the issue.

**Comment by StaymanHou** [comment]
@Kartik1607 , here's the code for the build function

```dart
@override
Widget build(BuildContext context) {
  return new Scaffold(
    key: _thisScaffoldKey,
    appBar: new AppBar(
      title: new Form(
        child: new TextFormField(
          decoration: new InputDecoration(
            hintText: 'Search ...',
            suffixIcon: new IconButton(
              icon: const Icon(Icons.clear),
              onPressed: () {
                _searchFieldController.clear();
                setState(() {
                  _searchQuery.queryString = '';
                  _results = null;
                });
              }
            )
          ),
          autofocus: true,
          controller: _searchFieldController,
          onFieldSubmitted: (String value) {
            _searchQuery.queryString = value;
            _executeSearchQuery(); // this is the heavy search operation
          },
        )
      ),
      actions: <Widget>[
        new SizedBox(
          width: 70.0,
          child: new FittedBox(
            fit: BoxFit.scaleDown,
            child: new FlatButton(padding: EdgeInsets.zero, onPressed: _showTranslationDialog, child: new Text('$_currentTranslationShortName  ▼')),
          ),
        ),
        new IconButton(
            icon: Icon(Icons.filter_list),
            color: _searchQuery.books.length == 0 ? null : Theme.of(context).accentColor,
            tooltip: 'Filter',
            onPressed: _showFilterDialog
        )
      ],
      bottom: _isSearching == false ? null : new PreferredSize(
        child: new LinearProgressIndicator(), // this is the progress bar that freezes
        preferredSize: new Size.fromHeight(0.1),
      ),
    ),
    body: _buildSearchResultBody()
  );
}
```

**Comment by StaymanHou** [comment]
@jonahwilliams, yes, I'm using some of the sync variants of the file APIs in that method. It's hard to post the code of the search method. However, I can put part of the underlining random file access class.

```dart
MyFileStream(String filepath) {
  File file = new File(filepath);
  _fis = file.openSync();
  _pos = 0;
}

// ...

int get currentPosition => _pos;
int get size => _fis.lengthSync();

// ...

Uint8List read(int nbytes) {
  _pos += nbytes;
  return _fis.readSync(nbytes);
}

// ...

void seek(int position) {
  _fis.setPositionSync(position);
  _pos = position;
}

// ...

void close() {
  _fis.closeSync();
}
```

**Comment by StaymanHou** [comment]
@zoechi, here's the `flutter doctor` output:

```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/stayman/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/stayman/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/stayman/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/stayman/Downloads/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /home/stayman/Downloads/idea-IC-181.4203.550
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
@StaymanHou those sync API will entirely block the UI while they are executing, and if you have multiple calls to them it makes sense that it will freeze your app.  They are really only designed to make command like scripts easier to write and should generally never be used on a Flutter app.  We should definitely do something so that users are aware of this

**Comment by jonahwilliams** [comment]
You could also run those operations in an isolate like @zoechi suggested

**Comment by StaymanHou** [comment]
Oh, I see. That make sense. Thanks for looking into the issue.

**Comment by jonahwilliams** [comment]
@StaymanHou There is a convenience function in the flutter foundation library, just import `flutter/foundation.dart`.  https://docs.flutter.io/flutter/foundation/compute.html

**Comment by mselmanyildirim** [comment]
I encountered a similar issue.
In my app, I need to make a computation (specifically, an inference of AI, using tflite_flutter package) which takes several seconds. The method is async. Meanwhile, I want to inform the user by a circular progress indicator, but the UI freezes until the computation finishes, thus progress indicator doesn't animate at all. 

> You can for example use https://docs.flutter.io/flutter/foundation/compute.html to execute code in a different isolate, but there are some limitations. Currently plugins can only be used from the UI isolate.

Is this still the case? I mean, can I run a heavy computation using a plugin on a separate isolate? If not, could you suggest a workaround? All I need is informing the user with an animation that computation is continuing.
