### ISSUE TITLE
Keyboard disappears and reappears when focus is moved by autofocus

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#190]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 07, 2015 at 21:28 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1531_

----

When a field goes away and a new field grabs autofocus in the same frame, the keyboard is hidden and shown again. When you just tap on another field, the keyboard doesn't move.

This is inconsistent.

**Comment by abarth** [comment]
I believe @jason-simmons fixed this issue.
