### ISSUE TITLE
Mismatch in test behavior for flutter_tools/test/commands/attach_test.dart between dart1 and dart2

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#19009]
The attach test runs properly on Travis, but fails in the tests on the g3 roll.

We get the following error:

```dart
NoSuchMethodError: The method '_setExpected' was called on null....
NoSuchMethodError: The method '_setExpected' was called on null.
Receiver: null
Tried calling: _setExpected(Closure: (Invocation) => T)
dart:core                                                                               Object.noSuchMethod
package:mockito/src/mock.dart 354:15                                                    PostExpectation._completeWhen
package:mockito/src/mock.dart 336:12                                                    PostExpectation.thenReturn
../../tmp/archives/third_party/dart/flutter_tools/test/commands/attach_test.dart 41:37  main.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                                              _AsyncAwaitCompleter.completeError
../../tmp/archives/third_party/dart/flutter_tools/test/commands/attach_test.dart        main.<fn>.<fn>
```

I spoke with @srawlins about this, and we believe this is related to package:flutter_tools using dart version < 2.0.0, while the g3 tests are using Dart 2.0.

The line that fails is:

```dart
when(portForwarder.unforward).thenReturn((ForwardedPort _) async => null);
```

which is using a tearoff of the unforward method instead of the method itself.

The Dart 2 approach is to do this:

```dart
when(portForwarder.unforward(any)).thenReturn(null);
```

This fix doesn't appear to work in the current test runner.

**Comment by DaveShuckerow** [comment]
The solution is going to be to switch the flutter_tools package pubspec to using Dart 2.0.

**Comment by zoechi** [comment]
> The solution is going to be to switch the flutter_tools package pubspec to using Dart 2.0.

That has happened. I assume this issue is stale.
Please just reopen if you think this is still valid.
