### ISSUE TITLE
Can't click on annotations in docs to see what they mean.

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#19001]
Example: https://docs.flutter.io/flutter/widgets/NavigatorState/push.html

```
@optionalTypeArgs
Future<T> push <T extends Object>(
    Route<T> route
)
```

`optionalTypeArgs` is a symbol, but it's not possible to tap on it to find out what it means. I can search for it though: https://docs.flutter.io/flutter/meta/optionalTypeArgs-constant.html

**Comment by zoechi** [comment]
Should this be moved to https://github.com/dart-lang/dartdoc ?

**Comment by goderbauer** [comment]
@zoechi Yes, can you move it? Thanks.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2153](https://github.com/flutter/website/issues/2153) via [**ZenHub**](https://www.zenhub.com/)
